### ISSUE TITLE
Live Reloading of Symfony 4

### ISSUE THREAD

**Issue by blachawk** [symfony/symfony#33640]
### **My Request**  
Can we automate the refreshing of a browser or a Twig content area in the browser, whenever a CSS or JS file attached to the Twig template is modified?

### **My Symfony Setup**

-------------------- ---------------------------------
  Symfony
 -------------------- ---------------------------------
  Version              4.3.4
  End of maintenance   01/2020
  End of life          07/2020
 -------------------- ---------------------------------
  Kernel
 -------------------- ---------------------------------
  Type                 App\Kernel
  Environment          dev
  Debug                true
  Charset              UTF-8
  Cache directory      ./var/cache/dev (139.5 MiB)
  Log directory        ./var/log (367 KiB)
 -------------------- ---------------------------------
  PHP
 -------------------- ---------------------------------
  Version              7.2.18
  Architecture         64 bits
  Intl locale          n/a
  Timezone             UTC (2019-09-19T12:42:35+00:00)
  OPcache              false
  APCu                 false
  Xdebug               false
 -------------------- ---------------------------------

### **My Current Process**
> I don't know if this requested feature already exist in a **service** or a **bundle**, but here's my current **Gulp/npm** setup:

### First, I created a custom ServerName for my symfony project, with a custom proxy:

```apache
<VirtualHost 127.0.0.1:80>
  DocumentRoot "C:/Users/.../php/symfony/sb01testb/public"
  ServerName local.symfony.app01b.wip
   DirectoryIndex index.php
  <Directory "C:/Users/lewisk/Documents/mTraining/php/symfony/sb01testb/public">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
    Order allow,deny
    allow from all
       <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ /index.php [QSA,L]
        </IfModule>
  </Directory>
</VirtualHost>
```

```powershell
symfony proxy:start
symfony proxy:domain:attach local.symfony.app01b
```

* With my current domain name at `local.symfony.app01b.wip` I moved forward with installing my Gulp/npm features as described below:
  * Within my gulpfile.bable.js file, I have the following browser-sync setup:
  ```js
  //...
  import browserSync from 'browser-sync';

  const server = browserSync.create();
  export const serve = done => {
    server.init({
      port: 80,
      proxy: "http://local.symfony.app01b.wip/blog/"  //I also tried http://127.0.0.1:8000 but no luck!
    });
    done();
   };
   //...

  export const buildDev = gulp.series(cleanDirectory, gulp.parallel(generateStyles, genertateScripts, copyFontAwesome), serve, watch);
  export default buildDev;


### My base.html.twig template

```twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}Welcome!
            {% endblock %}
        </title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/assets/css/bundle.css') }}">
        {% endblock %}
    </head>
    <body>

        {% block body %}{% endblock %}
        {% block javascripts %}
            <script type="text/javascript" src="{{ asset('build/assets/js/bundle.js')}}"></script>
        {% endblock %}
    </body>
</html>

```

* **But!** when I run my project from Gulp, the following errors populate in my terminal after 15 seconds and my page breaks....

```
> buildDev: 'watch' errored after 15 s
> buildDev: FAILED
> buildDev: Error: no parsers registered for: "]a(r)"
```

All I'm requesting for is a way for Symfony 4 to reload itself when CSS or JS assets are modified. Is there a simple way to set this up?

Many thanks!

**Comment by blachawk** [comment]
I see that it is available via https://flex.symfony.com/ If it's as simple as installing with composer from the terminal, I'll give it a shot!  

Many thanks on that!

**Comment by abdounikarim** [comment]
@blachawk you're welcome.

And if you need, you can see those tutorials about [Webpack](https://symfonycasts.com/screencast/javascript-webpack) and [Webpack encore](https://symfonycasts.com/screencast/webpack-encore).

Cheers 😉

**Comment by javiereguiluz** [comment]
Let's close this one as "fixed" because as @abdounikarim this feature is already provided by Webpack Encore. Thanks!
