### ISSUE TITLE
Allow MockResponse to emulate response from HEAD request

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#33655]
**Description**  
As stated in the current implementation, "empty body will result emulating idle timeout and so on an exception ...".

This means we can't simulate the result from a HEAD request.

Why not check - instead - the existence of "error" info property to create a fake "exception response" while allowing the emptiness of the body

**Example**  

```php
public function testTheClientAcceptsHttpMethodOverride(): void
{
   
    $client = new new MockHttpClient([
        new MockResponse('', []),
    ]);

    self::assertEmpty($client->request('HEAD', 'https://www.google.com'));
}
```

(adapted from the Resiliency library) see https://github.com/loveOSS/resiliency/pull/32

**Comment by nicolas-grekas** [comment]
A timeout is simulated by *yielding* an empty string, this is not what your example does.
I'm not sure how to help more with the current description sorry.

**Comment by mickaelandrieu** [comment]
Hi @nicolas-grekas,

forget about it, the issue was between the screen and the keyboard ^^

Time to sleep I guess, thanks for your instant feedback :+1:
