### ISSUE TITLE
function name must be callable - a string, Closure or class implementing __invoke, currently \Symfony\Component\HttpFoundation\Session\SessionInterface

### ISSUE THREAD

**Issue by isopen** [symfony/symfony#33664]
**Symfony version(s) affected**: 4.3

**Description**
`Resuest::getSession:$this->setSession($session = $session());`
`function name must be callable - a string, Closure or class implementing __invoke, currently \Symfony\Component\HttpFoundation\Session\SessionInterface`

**How to reproduce**  
open phpstorm and go to Request class

**Possible Solution**  
Try to follow the problem description

**Comment by xabbuh** [comment]
I am not sure what exactly you are reporting here. Can you please be a bit more precise?

**Comment by isopen** [comment]
Apparently there used to be an `abstract class` or just a `class`. Then the situation changed and the `interface` appeared. It became necessary to implement `$session` at user class. But it needs to be checked on several versions of `Symfony`.

In my opinion, a strange mechanism has been preserved in the new distribution (artifact).

**Comment by chr-hertel** [comment]
can you please reference the part of the documentation you're referring to and provide some example code of **your** application. it's easier to understand the issue that way :)

**Comment by isopen** [comment]
https://symfony.com/components/HttpFoundation

Yes. I’m not sure that the session mechanism works correctly due to the artifact found.
There are fears that when the session is initialized using the interface, it will be read incorrectly by the vendor.

**Comment by stof** [comment]
Please provide us a reproducing case for your issue. Otherwise, we'll have to consider that as an invalid issue.

**Comment by isopen** [comment]
https://gist.github.com/isopen/e1d081ae6329f97dedecee559fecf85b

Should this be used in `Symfony 4.3` or left as in `Symfony < 4.1`?

**Comment by stof** [comment]
I still don't understand what you mean. Please provide a clear reproducing case, as well as the exact error you get (and explaining the steps to reach the error).

**Comment by isopen** [comment]
Will this work correctly? https://github.com/symfony/symfony/search?q=getSession&unscoped_q=getSession
If I set up a session inside the class which in the example above. https://symfony.com/doc/current/session.html

**Comment by xabbuh** [comment]
I suggest that you stick to using the session as described in the documentation for now and not worry about the potential warning displayed by PhpStorm. If at some point in the future, you encounter some real issue/misbehaviour in your application, please provide a small example that allows to reproduce it and we can investigate the root cause then.
