### ISSUE TITLE
[Mailer] Amazon payload extension (ConfigurationSetName)

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#33680]
**Description**  
Allow emails sent via Amazon API to contain additional parameters.

Current [code](https://github.com/symfony/amazon-mailer/blob/master/Transport/SesApiTransport.php#L62) builds then immediately sends a _payload_ with no room for additional parameters.
Such other [parameters](https://github.com/aws/aws-sdk-php/blob/master/src/data/email/2010-12-01/examples-1.json) exist and may find useful.

**Example**
I would like to use a [ConfigurationSet](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets.html) for my email.
It'd [would be possible](
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets-in-email.html) using plain **Amazon SMTP** but only the **API** offers extended logging/permissions features.

**Comment by natepage** [comment]
The title is talking about Amazon, but it would be nice to find a generic way to extend the payload per transport.

Recently I wanted to use the mailer with Postmark and they provide a way to tag the emails so you can then filter them on their dashboard but for now I don't have a way to set the `Tag` in the payload.

**Comment by fabpot** [comment]
The Symfony Mailer component tries to provide features supported by as many providers as possible. See PR #35050 for tag/metadata support.

**Comment by drzraf** [comment]
:+1:  for #35050!
(but sorry to see Amazon transport wasn't adapted accordingly while this MR was hot)

**Comment by drzraf** [comment]
@fabpot : #35050 considered Mandrill, Mailgun, Postmark, but, AFAICT, not SES.
Is it possible to re-open this very issue in order to keep tracking it?

**Comment by cvmiert** [comment]
@drzraf #37897 should resolve this!
