### ISSUE TITLE
[Mailer] SentMessage->getMessageId()

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#33681]
**Description**  
`Message-Id` is a convenient (and robust) way to ensure a given transport actually accepted the request.
It has many use, from error-handling to logging through bounce handling.

**Example**  
- Mandrill stores the resulting Message-Id in `result[0]['_id']`
- Amazon in `result->get('MessageId');`
- ...

It would be **very** useful to get a consistent access to this feature.

**Comment by fabpot** [comment]
`Message-Id` is part of the Email we send. So, it's already part of `SentMessage` instance. Or am I missing something?

**Comment by javiereguiluz** [comment]
I think @drzraf doesn't refer to the random message ID that Symfony generates when creating a message ... but a message ID created by Amazon, Mailchimp, etc. when actually sending the email. If you get a message ID, you know that the message was really sent. I don't know if this is true ... but it's what I understood.

**Comment by fabpot** [comment]
Would that mean that these providers do not use the Message-Id we provide?

**Comment by Mouerr** [comment]
@fabpot yes they are not using it.

**Comment by matthiastosch** [comment]
hey @drzraf - i'm trying to find a setup to get the message_id from the transport when i use the new mailer component with async transport. It seems like you are some steps ahead with the implementation. Could you give me a hint for your approach?

Every works fine and smooth (bis thanks to the symfony team!) but until now i didn't have the chance to read the response from my mail provider.

**Comment by drzraf** [comment]
Sadly not, I can't move forward and I still have to rely on my own ~150 LoC home-made abstraction (Mandrill/Amazon) for the sole reason of this very issue (and #33680 which is about some `addTags()/addHeader()`).
I believe an API for `getMessageId()` (or any similar `isSent()`) will come up because sending an email is *the* operation every programmer check the return value... and `Message-Id` happens to not only be an ideal control method but is also handy in multiple situation from logging to delivery notification handling (eg: aws-sns)

**Comment by fabpot** [comment]
Implemented in #33967. Can you please test that it works well for your provider?

**Comment by AndreiIgna** [comment]
Oh wow, this is great. Just read the code and this would make email integration for a project I'm working on easier to add. Thank you


From countless tests, I know the current [SMPT Transport for Postmark](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkSmtpTransport.php) won't return the correct Message-ID.
> By default, Postmark will replace all Message-ID headers for outbound SMTP messages.

From https://postmarkapp.com/developer/user-guide/sending-email/sending-with-smtp section "Why isn’t my custom Message-ID being sent through Postmark?"

Should be ok using the PostmarkApiTransport or adding the header `X-PM-KeepID: true` to message when sending with PostmarkSmtpTransport

**Comment by fabpot** [comment]
@AndreiIgna fixed in the referenced PR now: https://github.com/symfony/symfony/pull/33967/commits/157f7e9ff3bf84239e1ae840f10951ada3ccaadf

**Comment by ThomasLandauer** [comment]
I just suggested a method to retrieve the **Queue-ID** which is sometimes confused with the Message-ID - so I'm mentioning it here.  
https://github.com/symfony/symfony/issues/36115

* A Message-ID is part of the mail, the corresponding header looks something like this:
  ```
  Message-ID: <42e11adad3889474ef61064fe29cd9e0@example.com>
  ```

  It is recommended that the Message-ID follows the same structure as an email address (even though it is none); it has to be globally unique.

* A Queue-ID is not part of the mail, it's the MTA's internal number for this message. It is usually communicated in the final response of the receiving SMTP server, which looks something like this:
  > 250 OK id=1eGWNZ-0000uc-UK

**Comment by fchris82** [comment]
How can I get the `SentMessage` object? `TransportInterface` creates and gets back, but `Mailer` doesn't do anything with it: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Mailer/Mailer.php#L42 . Is there any event where I can get it? I would need the final messageID.

**Comment by dvalverdeGF** [comment]
Sendings emails using TransportInterface and AWS SES, getMessageId() method from SentMessage results in the original random ID generated by Symfony. 

`c9c6cd6205a694f53fdaffc870f376d8@example.com` 
and I receive a message with an ID like this:

`01020177763dff4d-f029e9ea-7c8c-42c5-aea1-af922be171b0-000000@eu-west-1.amazonses.com`

¿Has AWS changed any thing in it response?

**Comment by drzraf** [comment]
@dvalverdeGF : You may want to check you're **not** using the Amazon **SMTP** transport (not all transport are created equal and this one does not attempt to reflect the remote Message-ID), see https://github.com/symfony/symfony/issues/46323

**Comment by dvalverdeGF** [comment]
> @dvalverdeGF : You may want to check you're **not** using the Amazon **SMTP** transport (not all transport are created equal and this one does not attempt to reflect the remote Message-ID), see #46323

@drzraf That was the problem. Thank you very much, it works now.
