### ISSUE TITLE
[Messenger] Retry Transport does not send the message back to retry transport on failing

### ISSUE THREAD

**Issue by BrentRobert** [symfony/symfony#33685]
**Symfony version(s) affected**: 4.3.3

**Description**  
When using the messenger:failed:retry command, the message is retried immediately. When it fails again, it should be requeued to the failure transport, but this does not happen due to the following code in the SendFailedMessageToFailureTransportListener class

```
 // avoid re-sending to the failed sender
        if (null !== $envelope->last(SentToFailureTransportStamp::class)) {
            return;
        }
```

Is this expected behavior?

**How to reproduce**  
Let a handler fail and queue it to the failure transport. Retry the message using the messenger:failed:retry command

**Comment by Tobion** [comment]
I also understood this wrong at first. 
But the failed message will be sent back to the failure transport depending on the retry strategy of the failure transport (which is enabled by default). So yes it is going back to the failure transport under normal circumstances.
See https://github.com/symfony/symfony/pull/32341#issuecomment-515525301
