### ISSUE TITLE
[Validator][DI] DI is not used to create Validator instances

### ISSUE THREAD

**Issue by TomPradat** [symfony/symfony#33699]
**Symfony version(s) affected**: 4.3.4

**Description**  
According to https://symfony.com/doc/current/validation/custom_constraint.html#constraint-validators-with-dependencies, I should be able to inject services in my custom validators.

Though it seems that these validators are not instantiated using the DI => https://github.com/symfony/validator/blob/3570629dcc673956b7191e58fb90a1f8b606c032/ConstraintValidatorFactory.php#L36-L46

**Comment by xabbuh** [comment]
That's done by the [ContainerConstraintValidatorFactory](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/ContainerConstraintValidatorFactory.php). Did you experience any actual issues or is it something you were wondering about while reading the code?

**Comment by TomPradat** [comment]
Well i'm trying to use a service in this validator. I need to call some database. Should I reimplement the ContainerConstraintValidatorFactoryInterface ? I think this is not the exepected behavior

**Comment by xabbuh** [comment]
How do you use the Validator component? Is it outside of a common Symfony application? If so, how did you set up the validator?

**Comment by TomPradat** [comment]
I'm working in a symfony application, i'm using the validator as follows : 
```php
$validator = Validation::createValidatorBuilder()
            ->addMethodMapping('loadValidatorMetadata')
            ->getValidator();
$errors    = $validator->validate($this);
```

My custom validator extends `ConstraintValidator` and was working fine until I decided to try to inject a service in it.

**Comment by xabbuh** [comment]
Is there a reason you do not use the `validator` service instead but create your own instance here?

**Comment by TomPradat** [comment]
I guess not, i'll try to refactor this to use the `validator` service and let you know. I see what's going on indeed

**Comment by TomPradat** [comment]
So to give you more context, I'm using DDD and wanted to use symfony validation to validate some value objects (in the constructor).

The problem is that i can't use DI on these value objects because they are basically dumb classes.

That's why I was creating the validator by hand in the constructor.

That said I understand why i can't have DI in my Custom validators.

**Comment by stof** [comment]
well, if you create things by hand, the DI container cannot do anything for you, as it is not involved. Relying on DI to work in a code not using DI is a weird expectation.

**Comment by TomPradat** [comment]
Yeap I understand it well, that's just that I wrote the code creating the validator by hand some time ago and didn't realize where the problem was. But this makes perfect sense now
