### ISSUE TITLE
[Mailer] missing commands

### ISSUE THREAD

**Issue by garak** [symfony/symfony#33694]
While SwiftmailerBundle has some useful commands, the new Mailer component is missing them.

Commands present in SwiftmailerBundle:
- `NewEmailCommand` the most important IMHO
- `DebugCommand` I guess it could be useful, too
- `SendEmailCommand` maybe not needed? I guess it could be handled with Messenger queue now

**Comment by fabpot** [comment]
`NewEmailCommand`: I don't see the use cases and as such, I don't want it in core

`DebugCommand`: Not sure if this is needed as all mailers are fully described via their DSNs.

`SendEmailCommand` is not needed as async emails are sent via the Messenger (`messenger:consume`).

**Comment by garak** [comment]
I understand the will of keeping core tidy. So, if you suggest me to write a library to provide such command , I'll do.
