### ISSUE TITLE
[Validator] issue with Range constraint while testing 4.4.x-dev

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#33700]
**Symfony version(s) affected**: 4.4.x-dev

**Description**  
While testing Symfony 4.4.x-dev on my biggest work project I discovered a test fail:

```
Failed asserting that 'This value should be between 1 and 6.' contains "Bitte wählen Sie eine gültige Bewertung aus". 
```

This happens because of changes in this PR: https://github.com/symfony/symfony/pull/32435

Constraint:

```php
    /**
     * @Assert\Range(min=1, max=6,
     *     minMessage="select_a_valid_rating_value",
     *     maxMessage="select_a_valid_rating_value",
     *     invalidMessage="select_a_valid_rating_value"
     * )
     */
    private $averageRating;
```

The form type that maps to this property specifies a custom translation domain via the `translation_domain` option. Inside this domain there are the translations for the message `select_a_valid_rating_value`.

**Possible Solution**  
Is this a BC break? Or should it be documented?

Ping @Lctrs

**Comment by Lctrs** [comment]
Hi @dmaicher,

To fix this, you can use the new option [`notInRangeMessage`](https://symfony.com/doc/4.4/reference/constraints/Range.html#notinrangemessage) which is used to translate this new message.

**Comment by dmaicher** [comment]
@Lctrs thanks I know how to solve it on my app. But usually there should not be anything to fix while upgrading from 4.3 to 4.4 :wink: That's why I created this issue to discuss this possible BC

**Comment by nicolas-grekas** [comment]
What's the solution? Up for a PR?

**Comment by Lctrs** [comment]
I dont know if you consider this kind of things as a BC break.

If that's the case, I see 2 solutions :
- completely revert my PR,
- revert my PR on 4.4, but keep it for 5.0.

**Comment by dmaicher** [comment]
Maybe it's enough to document this in the UPGRADE file? So that people are aware of it?

**Comment by dmaicher** [comment]
I propose to mention it in the UPGRADE file: https://github.com/symfony/symfony/pull/33880
