### ISSUE TITLE
[HttpClient] implement async client

### ISSUE THREAD

**Issue by garak** [symfony/symfony#33710]
It would be nice to implement php-http/async-client-implementation

**Comment by nicolas-grekas** [comment]
This could be added to `HttplugClient` I suppose. We have all the code infrastructure, so it's "just" a matter of writing the implementation :)

Help wanted.

**Comment by nicolas-grekas** [comment]
Could be of interest: https://github.com/getsentry/sentry-php/issues/878#issuecomment-535360902

**Comment by B-Galati** [comment]
I see some implementation (like Curl one from Httplug) that do not start the request when calling `sendAsyncRequest`. What should we do with this one?

IMHO it's better to start the request ASAP but not sure it fits with the specifications.

**Comment by Nyholm** [comment]
I crafted a PR for this feature. I really want some reviews or someone to test this for me. 

https://github.com/symfony/symfony/pull/33743
