### ISSUE TITLE
[DependencyInjection] Added support for variadic & tagged service

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#33720]
I got an idea, but I'm not sure if it's that useful and I'm wondering if we could add that to Symfony.

Tagged service + tagged iterator are really nice because they are lazy loaded. But sometimes, we don't need lazy loading because we know we will use each services. What's my use case ? I wanted to split N lines of code into smaller services, and foreach' them.

So basically, I want to do this:

```php
namespace App;

class Baz
{
    private $foobars;

    public function __construct(FoobarInterface ...$foobars) // Note the variadic here
    {
        $this->foobars = $foobars;
    }
```

and I would like to be able to write the following config:

```php
services:
    _instanceof:
        App\Foobar\FoobarInterface:
            tags: [ foobar ]

    App\Baz:
        arguments:
            $foobars: !tagged_variadic foobar # this does not exist yet
```

I could use tagged_iterator, but I will have to remove my type hint, that's why I'm proposing this RFC.
WDYT?

**Comment by nicolas-grekas** [comment]
To me, this is hacking variadics to workaround the fact PHP misses typed collections (for now).
But that's not an object. Works for me, I'm +0. `!tagged_array` could also be useful, when the code type-hints for `array` and thus doesn't work with the iterator. (That'd be defeating laziness too)

**Comment by lyrixx** [comment]
Looks like this is not a "must wanted feature". 
Let's close it

**Comment by pkruithof** [comment]
> Looks like this is not a "must wanted feature".

I was actually waiting for a feature like this since I learned about `tagged_iterator`. Sorry to bring up an old issue, but is there any chance to re-evaluate this feature? And how is a feature determined to be "must wanted"? Is there a possibility to vote on it or something?

**Comment by Wirone** [comment]
Yeah, I also was looking for this. I very much prefer to use strictly-typed variadic argument instead of `iterable`. I googled it but did not find result in docs, just got here. But at this point it wouldn't help use since we're on 5.4 and it would be added to 6.x 😞

**Comment by bechir** [comment]
Hope it will be added natively in the coming PHP versions.

**Comment by packagespace** [comment]
Also hoping for this feature.
