### ISSUE TITLE
Compilation failed: lookbehind assertion is not fixed length at offset 0

### ISSUE THREAD

**Issue by pesc** [symfony/symfony#33730]
**Symfony version(s) affected**: 4.4

Compilation failed: lookbehind assertion is not fixed length at offset 0 in /home/[...]/shopware6/vendor/symfony/routing/Matcher/Dumper/StaticPrefixCollection.php on line 177

I'm using it on FreeBSD with PHP7.3 and the PCRE2 Library. 

**How to reproduce**  
Installing a Symfony based application (Shopware6 in our example) and you will get an error when it tries to build all the routes & caches

I printed all subPattern and tested the resulting regex:
https://github.com/symfony/symfony/commit/465b15caa8e7023c4d18f3869c63c8e9d5d30796#diff-b24d3469ad085b21701584ed8f679d2dR177
```
console_log($subPattern);
if ($prefix !== $anotherPrefix && !preg_match('/^\(\[[^\]]++\]\+\+\)$/', $subPattern) && !preg_match('{(?<!'.$subPattern.')}', '')) {
```
test.php
```
<?php
preg_match('{(?<!(?:/([^/]++)))}', '');
preg_match('{(?<!(.*))}', '');
preg_match('{(?<!([^/]++))}', '');
preg_match('{(?<!([0-9a-f]{32}))}', '');
preg_match('{(?<!((?:\/[0-9a-f]{32}\/(?:extensions\/)?[a-zA-Z-]+)*\/?))}', '');
preg_match('{(?<!([0-9a-f]{32}(?:\/(?:extensions\/)?[a-zA-Z-]+\/[0-9a-f]{32})*\/?))}', '');
preg_match('{(?<!([a-zA-Z-]+))}', '');
preg_match('{(?<!(\d+))}', '');
?>

php-head test.php 
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 2
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in est.php on line 3
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 4
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 6
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 7
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 8
PHP Warning:  preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset 0 in test.php on line 9

```

**Possible Solution**  
Don't know - may this helps: https://www.pcre.org/original/doc/html/pcrepattern.html#lookbehind

**Comment by nicolas-grekas** [comment]
I'm sorry but to the best I'd like, there is nothing in this report that would allow understanding which conditions trigger the issue.

Could you please provide a reproducer, in the form of a repository we could clone and run locally to hit the warning?

**Comment by pesc** [comment]
Ok, will provide this tomorrow or the day after tomorrow

**Comment by pesc** [comment]
@nicolas-grekas Sorry, I mixed two different problems in one issue. I've just updated the main issue with problem nr. 1 :+1:

**Comment by nicolas-grekas** [comment]
Thank you, that's better. But that still doesn't make sense :)
The preg_match call you link is enclosed in a `set_error_handler()` that precisely catches this message, see https://github.com/symfony/symfony/blob/732c0344eaaab7b6e3092b7aae6172eaf439d561/src/Symfony/Component/Routing/Matcher/Dumper/StaticPrefixCollection.php#L198-L201

If you still see the message, I don't know why at all and I don't think it's related to Symfony, but maybe do some extension you might have installed locally?

**Comment by pesc** [comment]
Ok, yes so this works as it should work
