### ISSUE TITLE
error_get_last returns warnings in controller

### ISSUE THREAD

**Issue by pravdinalex** [symfony/symfony#33745]
**Symfony version(s) affected**: 4.2.11, 4.3.4

**Description**  

Calling ``` error_get_last() ``` somewhere in controller returns errors, that normaly, not affects page processing. 

My use case was:
```
        $context = stream_context_create([
            'http' => [
                'method' => 'POST',
                ...
            ]
        ]);

        $response = file_get_contents($someServiceURL, false, $context);
        $e = error_get_last();

        if ($e && is_array($e)) { ... process error ... }
```

I found that ```$e``` contains warnings, not depending from ```file_get_contents()``` call.

In 4.2.11 I got warning ``` Option "matcher_cache_class" given to router Symfony\Bundle\FrameworkBundle\Routing\Router is deprecated since Symfony 4.3. ```

In 4.3.4 I got warning ``` include(): Failed opening '/var/www/my-project-name/.env.local.php' for inclusion (include_path='.:/usr/share/php') ``` 

**How to reproduce**  

// somewhere in a controller:
$e = error_get_last();
// $e['message'] will not empty 

**Possible Solution**  

I think, somewhere in Symfony's code (before calling code from controller?) ``` error_clear_last() ```  should be called to reset warnings from Symfony's code.

**Additional context**  

```
PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
```
```
    "require": {
        "php": "^7.2.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "symfony/apache-pack": "^1.0",
        "symfony/console": "4.3.*",
        "symfony/dotenv": "4.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "4.3.*",
        "symfony/monolog-bundle": "^3.4",
        "symfony/twig-bundle": "4.3.*",
        "symfony/yaml": "4.3.*"
    },
```

**Comment by nicolas-grekas** [comment]
Hi, that's expected: it's your responsibility to call `error_clear_last()` before caliing file_get_contents in your example.

**Comment by pravdinalex** [comment]
In a clear code - yes, I should reset last error before my actions.

But I think that this behaviour is a kind of side effect, when same code inside and outside Symfony executes different. And ```error_clear_last``` appears in PHP 7.0 only - how it was working before ?

...And in PHP documentation to ```error_get_last``` there is no reference to use ```error_clear_last``` before action :(

**Comment by nicolas-grekas** [comment]
`error_clear_last()` has been exactly for the use case you mention. I was missing before, but now you can and should call it before `error_get_last()`.
There is nothing we can and should do in the base code.
