### ISSUE TITLE
Workflow component defaults to deprecated class

### ISSUE THREAD

**Issue by holtkamp** [symfony/symfony#33749]
**Symfony version(s) affected**: dev-master

**Description**  
The default markingStore is the _deprecated_ / already removed `MultipleStateMarkingStore`:

**How to reproduce**  
https://github.com/symfony/workflow/blob/bcf929f721b88d7310d74ab41aa6152cf5b5a6ad/Workflow.php#L44

**Possible Solution**  
Default to `MethodMarkingStore` just as done in the StateMachine:

https://github.com/symfony/workflow/blob/bcf929f721b88d7310d74ab41aa6152cf5b5a6ad/StateMachine.php#L25

**Comment by lyrixx** [comment]
Thanks, I have forgot to update this one :)
For the record It was not possible to do that on 4.X to ensure BC promise
