### ISSUE TITLE
Symfony\Component\Messenger\Envelope final modifier make hard to test some scenario

### ISSUE THREAD

**Issue by pfazzi** [symfony/symfony#33740]
**Symfony version(s) affected**: 4.3

**Description**  
`Symfony\Component\Messenger\Envelope` has been marked as final. Sometimes, for testing purposes it's useful to mock it. Phpspec, for instance, does it under the hood. But the final modifier represent a problem in such scenario.

**Possible Solution**  
I suggest to remove the final modifier or extract an `EnvelopeInterface`.

**Comment by ro0NL** [comment]
it's a value object ..., why do you need to mock it?

**Comment by pfazzi** [comment]
Let me show you an example where phpspec is involved.

Let's consider this service that dispatches a message:

```php
<?php

namespace App;

use Symfony\Component\Messenger\MessageBusInterface;

class SomeService
{
    /**
     * @var MessageBusInterface
     */
    private $bus;

    public function __construct(MessageBusInterface $bus)
    {
        $this->bus = $bus;
    }

    public function dispatch()
    {
        $this->bus->dispatch(new SomeMessage());
    }
}
```

I want to test that the message id dispatched so i implement a spec using phpspec:
```php
<?php

namespace spec\App;

use App\SomeService;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;
use Symfony\Component\Messenger\MessageBusInterface;

class SomeServiceSpec extends ObjectBehavior
{
    function let(MessageBusInterface $bus)
    {
        $this->beConstructedWith($bus);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(SomeService::class);
    }

    function it_dispatches_messages(MessageBusInterface $bus)
    {
        $this->beConstructedWith($bus);

        $bus->dispatch(Argument::any())->shouldBeCalledOnce();

        $this->dispatch();
    }
}
```
The execution of this spec leads to an error:
```bash
> vendor\bin\phpspec run "App\SomeService"
App\SomeService
  22  - it dispatches messages
      could not reflect class Symfony\Component\Messenger\Envelope as it is marked final.

                  50%                                     50%                    2
1 specs
2 examples (1 passed, 1 broken)
54ms
```

**Comment by ro0NL** [comment]
im not a phpspec user but shouldnt `Argument::any()` be the actual argument, thus an envelope. Compared to PHPUnit; you are asserting that Symfony's message bus is invoked with the expected message right?

Honestly, i find your `it_dispatches_messages` hard to reason about :man_shrugging:

**Comment by pfazzi** [comment]
I used `Argument::any()` because i'm lazy 😃 
The right test should be like:

```php
function it_dispatches_messages(MessageBusInterface $bus)
{
	$this->beConstructedWith($bus);

	$bus->dispatch(Argument::type(SomeMessage::class))->shouldBeCalledOnce();

	$this->dispatch();
}
```

Basically SomeService::dispatch return nothing so i need a mock object that verify that the message is dispatched.

This can be achived using a so called Prophet Objects, in particular i'm using a Mock. You can read more [here](https://www.phpspec.net/en/stable/manual/prophet-objects.html#mocks) where there is a similar example.

**Comment by ro0NL** [comment]
but if you are mocking a `MessageBusInterface`,  who is mocking the Envelope then? and why? AFAIK the only reference now is from https://github.com/symfony/symfony/blob/e627989089fba30fdcef403208fd4a26d6601220/src/Symfony/Component/Messenger/MessageBusInterface.php#L24

**Comment by pfazzi** [comment]
It's phpspec that does it under the hood and that is why i'm asking if Envelope can be transformed into and interface so that it can be compatible with this testing framework ;)

**Comment by ro0NL** [comment]
i'll let others decide :) im not sure what phpspec does is legit.

**Comment by sroze** [comment]
Wait. Prophecy can't work with `Argument::type(Envelope::class)`? 🤔

**Comment by pfazzi** [comment]
@sroze The problem is not in `Argument::type(Envelope::class)`, in fact you can get the same error even with `Argument::any()`. It seems that not only collaborators are mocked by Prophecy but also their return types. Infact in order to bypass the problem I specified the return object as follows:

```php
function it_dispatches_messages(MessageBusInterface $bus)
{
	$this->beConstructedWith($bus);

	$bus->dispatch(Argument::type(SomeMessage::class))
		->shouldBeCalledOnce()
		->willReturn(new Envelope(new \stdClass()));

	$this->dispatch();
}
```

**Comment by nicolas-grekas** [comment]
:-1: on my side: as @ro0NL mentions, that's a value object. Adding an interface wouldn't make sense. Tools/tests need to adapt to the design, not the opposite.

**Comment by xabbuh** [comment]
I agree with @nicolas-grekas.

**Comment by fabpot** [comment]
I agree as well, let's close.

**Comment by OskarStark** [comment]
Because I need to think about this all the time in a new project, I added a double instead of mocking the MessageBus:

```php
<?php

declare(strict_types=1);

namespace App\Tests\Double\Symfony\Component\Messenger;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\MessageBusInterface;
use function Safe\sprintf;

final class CollectingMessageBus implements MessageBusInterface
{
    /**
     * @var object[]
     */
    private array $dispatchedMessages = [];

    public function dispatch($message, array $stamps = []): Envelope
    {
        if (!\is_object($message)) {
            throw new \TypeError(sprintf(
                'Invalid argument provided to "%s()": expected object, but got "%s".',
                __METHOD__,
                \gettype($message)
            ));
        }

        $this->dispatchedMessages[] = $message;

        return Envelope::wrap(
            $message,
            $stamps
        );
    }

    /**
     * @return object[]
     */
    public function dispatchedMessages(): array
    {
        return $this->dispatchedMessages;
    }
}
```

and then:
```php
<?php

declare(strict_types=1);

namespace App\Tests\Unit\EventSubscriber;

use App\EventSubscriber\SendSmsSubscriber;
use App\Kernel;
use App\MessageHandler\Notification\SendSmsToUser;
use App\Tests\Double\Symfony\Component\Messenger\CollectingMessageBus;
use PHPUnit\Framework\TestCase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\HttpKernelInterface;

final class NotificationRequestSubscriberTest extends TestCase
{
    /**
     * @test
     */
    public function dispatches(): void
    {
        $bus = new CollectingMessageBus();

        $subscriber = new SendSmsSubscriber($bus);

        $request = Request::create('/', Request::METHOD_GET, ['phone' => '123']);

        $event = new RequestEvent(
            new Kernel('dev', false),
            $request,
            HttpKernelInterface::MAIN_REQUEST
        );

        $subscriber->onKernelRequest($event);

        $dispatchedMessages = $bus->dispatchedMessages();

        self::assertCount(1, $dispatchedMessages);
        self::assertInstanceOf(SendSmsToUser::class, $dispatchedMessages[0]);
    }
}
```

Hope this helps someone who will end here by googling 👍

**Comment by garak** [comment]
I have the same issue simply trying to mock the bus in PHPUnit. I see there's already a proposed solution, but I was wondering if it could be made easier, maybe by providing a testing helper?
Here's my super simple test (on Symfony 6.4):

```php
<?php

namespace Tests\Command;

use MyApp\Command\MyCommand;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Console\Tester\CommandTester;
use Symfony\Component\Messenger\MessageBusInterface;

class MyCommandTest extends WebTestCase
{
    public function testExecute(): void
    {
        $client = self::createClient();
        $bus = $this->createMock(MessageBusInterface::class);
        $application = new Application($client->getKernel());
        $application->add(new MyApp($bus));
        $command = $application->find('app:my-command');
        $commandTester = new CommandTester($command);
        $output = $commandTester->execute(['command' => $command->getName()]);
        self::assertEquals('foo', $output);
    }
}
```

So, I don't try to mock the Envelope, I'm not even interested in mocking it: I just need a mock of the bus to test my command (which has the bus injected to dispatch a command, which also I'm not really interested to test).
It seems to me a very basic need...

**Comment by garak** [comment]
Found a simple solution, posting it here for the same purpose explained above.
It's simple enough as adding `$bus->expects(self::once())->method('dispatch')->willReturn(new Envelope(new \stdClass()));`
