### ISSUE TITLE
Cannot use console on latest 4.4.-dev

### ISSUE THREAD

**Issue by garak** [symfony/symfony#33756]
**Symfony version(s) affected**: 4.4.x-dev (symfony/console is at b32d395)

**Description**  
If i run console from terminal, I get:

>Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Application::renderException() must be an instance of Exception, instance of TypeError given, called in [myproject]/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php on line 129 and defined in [myproject]/vendor/symfony/console/Application.php on line 796

>TypeError: Argument 1 passed to Symfony\Component\Console\Application::renderException() must be an instance of Exception, instance of TypeError given, called in /user/sportlinx/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php on line 129 in [myproject]/vendor/symfony/console/Application.php on line 796

>Call Stack:
    0.1228   15531960   1. Symfony\Component\ErrorHandler\ErrorHandler->handleException() [myproject]/vendor/symfony/error-handler/ErrorHandler.php:0
    0.1241   15613472   2. Symfony\Component\ErrorHandler\ErrorHandler->handleException() [myproject]/vendor/symfony/error-handler/ErrorHandler.php:616

**How to reproduce** 
Install 4.4.x-dev and run `bin/console`

**Comment by garak** [comment]
Tried to remove type-hint from relative methods, I got:

>Argument 1 passed to Symfony\Component\VarDumper\Command\Descriptor\CliDescriptor::__construct() must be an instance of Symfony\Component\VarDumper\Dumper\CliDumper, instance of Symfony  
  \Component\VarDumper\Dumper\ContextualizedDumper given, called in [myproject]/var/cache/dev/ContainerXjRudiy/getVarDumper_Command_ServerDumpService.php on line 22

**Comment by nicolas-grekas** [comment]
Where the report comes after the fix :P
