### ISSUE TITLE
Deprecation message is displayed twice

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33765]
**Symfony version(s) affected**: 5.0

**Description**  
Deprecation message id duplicated:

![image](https://user-images.githubusercontent.com/73419/65891278-8e1e4180-e3a4-11e9-927e-73698f427ae1.png)

Here are the details of each deprecation:

![image](https://user-images.githubusercontent.com/73419/65891302-96767c80-e3a4-11e9-8780-8ded1e913994.png)

**How to reproduce**  
```bash
$ symfony new my_project --full --version=dev-master
$ cd my_project/
$ symfony serve
```

The "Welcome Page" will display 2 deprecation messages.

**Comment by stof** [comment]
Can you show the trace for both ?

**Comment by javiereguiluz** [comment]
Would this be enough? Thanks!

![image](https://user-images.githubusercontent.com/73419/65893707-b4de7700-e3a8-11e9-9b99-49f9dbf64d9b.png)

**Comment by stof** [comment]
Thanks. This allowed me to identify the issue. We trigger the deprecation twice:

- once in the WebServerExtension during the compilation of the container (the second one in your screenshot)
- once in the WebServerBundle on boot (the first one in your screenshot)
