### ISSUE TITLE
Possibility to add a default role to the AnonymousToken

### ISSUE THREAD

**Issue by igst** [symfony/symfony#33778]
**Description**  
If i want use ACLs and want to grant an action to a **not** logged in user but this action should **not** be **allowed** to an **logged in** user I have to use a separate role for the AnonymousToken. 

Unfortunately there is no built-in possibility to add default roles to the AnonymousToken so I have to create a CompilerPass to override the Service Definition of the AnonymousAuthenticationListener to replace the line

`$token = new AnonymousToken($this->secret, 'anon.', []);`

with

`$token = new AnonymousToken($this->secret, 'anon.', ['ROLE_NOT_LOGGED_ID']);`

Maybe it would be more elegant to have the possibility to define a default "not logged in"-role in the security settings of the framework?

**Comment by xabbuh** [comment]
I am not convinced that using a role for this is the appropriate solution. I would rather create a custom voter that grants access when the token is an `AnonymousToken` and denies otherwise.

**Comment by derrabus** [comment]
Would it make sense to add such a voter to the security component?

**Comment by igst** [comment]
Yes, it would be possible to solve this with a voter, but in my case i am using KunstmaanBundles CMS and the security component of this CMS is using ACLs. 

A voter would not help in that case, it's not dynamically addable.

**Comment by derrabus** [comment]
I'm not familiar with how this specific CMS checks if the current user has a certain role. Granting a permission (or role) via a voter does not work? Have you tried?

If that CMS really checks the roles assigned to the token instead of querying the authorization checker, that would be something that should be fixed on their side.

**Comment by igst** [comment]
Ok, I will try to explain it more in detail. 

I have a CMS and can add a role with an action (e.g. VIEW) to a dynamically created page. It works with ACLs. 

I have a table where I can define the oermissions dynamically. Please have a look on the attached screenshot. 
![Bildschirmfoto 2019-10-01 um 11 54 47](https://user-images.githubusercontent.com/5346377/65952529-56fe6d80-e442-11e9-931b-4f91a92b97c4.png)

I am able to create dynamically roles in the settings of the CMS and add permissions to these roles to grant some permissions to (also dynamically created) pages. This is dynamic right management via ACL. Voters are "hard coded" and I cannot see how to use voters in this case - or I did not understand the concept behind voters.  

The CMS is checking the permissions by the default AuthorizationChecker but because I am granting permissions and not denying, I must use a dynamic role to grant a permission to a not logged in user (which current has no roles but IS_ANONYMOUSLY_AUTHENTICATED) and to deny access to a logged in user (which would also get access through the pseudo role IS_ANONYMOUSLY_AUTHENTICATED).

So, if I add "VIEW" to "IS_ANONYMOUSLY_AUTHENTICATED", logged in and NOT logged in users can see the page. But I want to grant "VIEW" only to NOT logged in users...

And the only way I can reach this is a special "NOT_LOGGED_IN_ROLE".

I hope the problem is more clear!?

**Comment by stof** [comment]
I would say that this should rather be fixed by supporting voters in the CMS for complex cases.
I don't think adding roles to the anonymous token makes sense.

**Comment by igst** [comment]
Of course it's possible to use voters in some way, but if ACLs are used instead of voters (maybe a considered and allowed decision) my case cannot be covered...

With the **possibility** and not a **condition** to add a default role to the anonymous token via the config or to change the AnonymousToken class there would be one more feature in my opinion. 

But anyway, I close the ticket.

**Comment by derrabus** [comment]
> The CMS is checking the permissions by the default AuthorizationChecker 

> And the only way I can reach this is a special "NOT_LOGGED_IN_ROLE".

All right, but then you should be able to create that special role and only grant it via a voter. If the CMS uses the authorization checker to check a user's roles, you should be good.
