### ISSUE TITLE
[Lock] Check isAcquiredByAnyone('generate-pdf-*')

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony#33800]
**Description**  
To check `$lock->isAcquiredByAnyone('generate-pdf-*-process')`
The `*` symbol may be unique string. Like searching using `Finder` component

**Comment by erlangp** [comment]
**Example**  

`$lockA->acquire('generate-pdf-1-process'); // Client A` 
`$lockB->acquire('generate-pdf-2-process'); // Client B`
`$lockC->acquire('generate-pdf-3-process'); // Client C`

`$lockX->isAcquiredByAnyone('generate-pdf-*-process'); // Cron // true`

`$lockA->release();`
`$lockB->release();`

`$lockX->isAcquiredByAnyone('generate-pdf-*-process'); // true`

`$lockC->release();`

`$lockX->isAcquiredByAnyone('generate-pdf-*-process'); // false`

**Comment by erlangp** [comment]
@nicolas-grekas sir :D

**Comment by pyatnitsev** [comment]
Ok, Interesting Idea. I have looked at the code of component. 
`isAcquired `calls `exists()` method of a store class, and that method just get an object by specific key. 
I can Imagine multiple calls of `exists` method for array of keys and check `isAcquired`, but I have no idea how to implement wildcard symbols without rewrite all supported stores. 

WDYT?

**Comment by erlangp** [comment]
thanks @pyatnitsev maybe using regex? preg_match?

**Comment by pyatnitsev** [comment]
> thanks @pyatnitsev maybe using regex? preg_match?

it's a possible solution, but it's require to change in all supported adapters.

@nicolas-grekas, please suggest.

**Comment by jderusse** [comment]
What's the use case of such methods?

note: if `isAcquiredByAnyone`return false, does not mean, that calling `acquire` will be successful. calling 2 methods is not atomic.

see: https://github.com/symfony/symfony/issues/36024#issuecomment-619377265
