### ISSUE TITLE
Symfony binary source code not open source.

### ISSUE THREAD

**Issue by mcfedr** [symfony/symfony#33817]
The recommended way to download and work with Symfony has recently(ish) been changed in all the docs to be using `symfony` cli tool. Given that its such an important part of the Symfony environment it seems such a shame that its not an open source tool. Symfony has such a large community, and has contributions from many people working on, I'm sure there are features and improvements the community could also make to the tools for working with Symfony.

**Comment by mcfedr** [comment]
I've only just noticed that its not open source because there was something I wanted to take a look at how its implemented, I would imagine this is the case for most people using it, as the web page for downloading it on is all "Free and Open Source", "Symfony is publicly hosted on GitHub". Its a bit misleading in this sense.

**Comment by nicolas-grekas** [comment]
Wrong repo. https://github.com/symfony/cli maybe
But Symfony is MIT, don't be confused :)

**Comment by mcfedr** [comment]
ah, google failed me.

**Comment by mcfedr** [comment]
I know that Symfony framework is MIT, but its a shame the cli tool to go with it is not.

**Comment by kaznovac** [comment]
@mcfedr as open source usually does here's the ongoing effort https://github.com/Orbitale/Rymfony

**Comment by mcfedr** [comment]
@kaznovac This is awesome stuff! I'll be checking that out right away.
