### ISSUE TITLE
[Mailer] Get failing email addresses

### ISSUE THREAD

**Issue by thafirstone** [symfony/symfony#33812]
**Description**  
Hi, 
I'm looking for a way to display the email addresses to which the message was not sent.

**Example**  
Something like that used to exist on Swiftmailer

```
$failure = [];

        if (!$this->mailer->send($message, $failure)) {
            ....
        } 

```
With `$failure`  containing the emails to which the message was not sent

**Comment by fabpot** [comment]
There is a big difference between Swiftmailer and Symfony Mailer. As we only care about transactional emails, an exception is thrown when there is a problem. So, if the email was not sent, you will get an exception. That does not means that the email will be received if there is no exception, just that it was sent.

**Comment by ro0NL** [comment]
@thafirstone the failed recipients are an artifact of `Swift_RfcComplianceException`, thus holds the invalid address (you can validate this yourself as well, before sending)

ultimately only the transport can tell us something was delivered yes/no, or attempted to at least.

**Comment by torian257x** [comment]
@ro0NL not sure what you mean with `artifact` but at least it seems that https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L491 does actually catch `\Swift_TransportException` so at the least it is not only `\Swift_RfcComplianceException`
