### ISSUE TITLE
[FrameworkBundle] About the "assets: install" copy method

### ISSUE THREAD

**Issue by emnsen** [symfony/symfony#33823]
Hello,

I've created 2 bundles. 1 bundle is slider bundle. This bundle converted from third-party php script and when create slider, assets of slider uploads inside to this bundle directory.

But problem is here when running assets:install command all assets of bundles removed and re-copy(i’m using copy method) and this situation my slider assets is removed but i don’t want removed, just i want to copy(override).

If "--override" option add in [AssetsInstallCommand](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php#L256) this problem is solved.

```php
// line 256
$this->filesystem->mirror($originDir, $targetDir, Finder::create()->ignoreDotFiles(false)->in($originDir), ['override' => $override]);
```

What do you think about it?

**Comment by xabbuh** [comment]
Can you explain why it is an issue for your use case to have it removed and then recreated again?

**Comment by emnsen** [comment]
I've created slider bundle but this bundle contains third-party plugins.
When I upload a new file, the uploaded file is moved to the "bundles/my-slider-bundle/uploads" directory.

Example;
```
public/bundles/my-slider-bundle

upload new file -> public/bundles/my-slider-bundle/uploads/new.file
```

I can't changed the target upload path because this plugin doesn't allow for this.

In this case when i run composer update command, assets:install command triggering after composer update and "assets: install" command removes and re-copies the directory "my-slider-bundle" in which case my "my-slider-bundle/uploads" directory is deleted.

I think if we add the "--override" option, maybe we can solve problems like this?

I created my own assets: install command. I'm using it for now. You can see in [this gist](https://gist.github.com/emnsen/f138ac678d4a7859ea3c931e0a9afeab).

**Comment by xabbuh** [comment]
This sounds like an edge case to me that rather needs to be fixed in the plugin to store the files somewhere else. Having the `--override` would effectively mean that orphaned assets would not be cleaned up and that users would have to do that themselves. To me your solution with the custom command sounds better.

**Comment by emnsen** [comment]
Thank you @xabbuh 👍

**Comment by ThomasLandauer** [comment]
@xabbuh By "orphaned assets" you mean that after removing some bundle, its (previously generated) assets would stay inside `public` forever?
