### ISSUE TITLE
choice_translation_domain does not work when expanded is true

### ISSUE THREAD

**Issue by dbrekelmans** [symfony/symfony#33826]
**Symfony version(s) affected**: 4.3.2

**Description**  
When rendering a choice type, the `choice_translation_domain` is not used to translate the choices when the option `expanded` is `true`.

When `expanded` is set to `false`, the translation domain is used to translate the choices (this is the expected behaviour).

**How to reproduce**  
Translation file (`foobar.en.yml`):
```yaml
bar: 'test1'
baz: 'test2'
```

FormType:
```php
public function buildForm(FormBuilderInterface $builder, array $options): void
{
  $builder->add('foo', ChoiceType::class, [
    'expanded' => true,
    'choice_translation_domain' => 'foobar',
    'choices' => [
      'bar' => 'bar',
      'baz' => 'baz'
    ]
  ]
}
```
Twig template:
```twig
{{ form_row(form.foo) }}
```

**Possible Solution**  

**Additional context**  
Possibly related:
- https://github.com/symfony/symfony/issues/15140#issuecomment-116719606
- https://github.com/sonata-project/SonataAdminBundle/issues/4550

**Comment by xabbuh** [comment]
Which form theme do you use? Can you create a small example application that allows to reproduce your issue?

**Comment by dbrekelmans** [comment]
Hi @xabbuh , thanks for your response.

I just set up an example from a clean symfony install and indeed the bug is not present.
The project where this occurred does use a custom form theme, so that must be causing it.

I did look in the form theme before reporting the bug, but I didn't see anything strange.
I will investigate further.

Thank you for your time!
