### ISSUE TITLE
[Mailer] Implicitly set SES region to eu-west-1

### ISSUE THREAD

**Issue by vittominacori** [symfony/symfony#33827]
**Symfony version(s) affected**: 4.3.4

**Description**  
SES Transport Factory and constructors (like [this](https://github.com/symfony/amazon-mailer/blob/master/Transport/SesHttpTransport.php#L36)) use a nullable `$region` param but then (if null) it is set to `eu-west-1`.

So if we try sending email from our SES domain in `us-east-1` we receive the following:

```
Failed to authenticate on SMTP server with username "<MY_AWS_ACCESS_KEY>" using the following authenticators: "PLAIN", "LOGIN". Authenticator "PLAIN" returned "Symfony\Component\Mailer\Exception\TransportException: Expected response code "235" but got code "535", with message "535 Authentication Credentials Invalid"
``` 

which made us lose some time before we realized that the credentials were correct.

Then we added region to our env config and it start working.

```
MAILER_DSN=smtp://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses?region=$AWS_SES_REGION
MAILER_DSN=http://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses?region=$AWS_SES_REGION
```

**How to reproduce**  
Having SES domain not in `eu-west-1`, install `symfony/amazon-mailer` with the default config and try using it.

```
###> symfony/amazon-mailer ###
AWS_ACCESS_KEY=<YOUR-KEY>
AWS_SECRET_KEY=<YOUR-SECRET>
MAILER_DSN=smtp://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses
MAILER_DSN=http://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses
###< symfony/amazon-mailer ###
```

**Possible Solution**  
Requiring `$region` instead of set it as `null` by default and throw an esplicative Exception message.

Or update env recipe by adding the `region` param like something below, so developers realize that they have to insert it.

```
###> symfony/amazon-mailer ###
# AWS_SES_REGION=eu-west-1
# AWS_ACCESS_KEY=
# AWS_SECRET_KEY=
# MAILER_DSN=smtp://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses?region=$AWS_SES_REGION
# MAILER_DSN=http://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@ses?region=$AWS_SES_REGION
###< symfony/amazon-mailer ###
```

**Comment by thePanz** [comment]
@vittominacori Can you have a look at: https://github.com/symfony/recipes/pull/653?
I added the recipe as suggested by your example

**Comment by fabpot** [comment]
Closing as the recipe has been merged now.
