### ISSUE TITLE
[httpClient] NO_PROXY option is ignored in NativeHttpClient::request() method 

### ISSUE THREAD

**Issue by Harry-Dunne** [symfony/symfony#33832]
**Symfony version(s) affected**: 4.3.4

**Description**  
Overriding HTTP Proxy settings in $options argument passed to NativeHttpClient::request() method works for "proxy" option but doesn't work for "no_proxy" option.

**How to reproduce**  

Call the NativeHttpClient::request() method with options overriding your proxy settings in environment variables:
```php
$client = HttpClient::create();
$client->request('GET', 'http://my-host.com/', [
    'no_proxy' => 'my-host',
]);
```

**Possible Solution**  

I think that the bug lies in this line:

https://github.com/symfony/http-client/blob/92ceb25f8c850d4ec8bce9234c8001c5b32d8387/NativeHttpClient.php#L224

Possible fix:

```php
$noProxy = $options['no_proxy'] ?? $_SERVER['no_proxy'] ?? $_SERVER['NO_PROXY'] ?? '';
```

**Comment by nicolas-grekas** [comment]
Your fix look good to me, would you like to submit it as a PR against branch 4.3?

**Comment by Harry-Dunne** [comment]
No problem, I will submit it in the next few days.
