### ISSUE TITLE
Cache stampede prevention fails when calculation time is less than a second

### ISSUE THREAD

**Issue by dharple** [symfony/symfony#33837]
**Symfony version(s) affected**: 4.3.4

**Description**  
When using cache contracts, if the callback that generates the data to cache takes less than a second to run, the stampede prevention logic will never fire.

**How to reproduce**
I'm not quite sure how to demonstrate this as a unit test, but I was able to reproduce it using a console command.  You can see from the output, the stampede protection doesn't start firing until the delay reaches 1 second.

```php
    <?php

    namespace App\Command;

    use Psr\Log\LoggerInterface;
    use Symfony\Component\Cache\Adapter\FilesystemAdapter;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Contracts\Cache\ItemInterface;

    class TestStampede extends Command
    {
        protected static $defaultName = 'test:stampede';
        protected $logger;

        public function __construct(LoggerInterface $logger)
        {
            parent::__construct();
            $this->logger = $logger;
        }

        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $cache = new FilesystemAdapter(
                'test',
                0,
                '/tmp/test'
            );

            $cache->setLogger($this->logger);

            foreach ([100000, 500000, 900000, 1000000] as $delay) {
                $this->logger->info('running with a {delay}s delay', [
                    'delay' => sprintf('%0.2f', $delay / 1000000.0)
                ]);

                $key = 'test-' . random_int(1, PHP_INT_MAX);
                for ($x = 0; $x < 1000000; $x++) {
                    $value = $cache->get($key, function (ItemInterface $item) use ($delay) {
                        $item->expiresAfter(15);
                        usleep($delay);
                        return 'test.data';
                    });
                }
            }
        }
    }
```

run with `bin/console -vv test:stampede`

Note that this will push load up on your machine, because we're brute forcing our way in to the stampede protection.

**Possible Solution**  
The easiest way I've found to fix this is to adjust the math that calculates CTIME in `Symfony\Component\Cache\Traits\ContractsTrait`.

Replace

```php
$item->newMetadata[CacheItem::METADATA_CTIME] = $metadata[CacheItem::METADATA_CTIME] = 1000 * (int) ($endTime - $startTime);
```

with

```php
$item->newMetadata[CacheItem::METADATA_CTIME] = $metadata[CacheItem::METADATA_CTIME] = (int) (1000 * ($endTime - $startTime));
```

**Additional context**  
The stampede prevention math in `Symfony\Contacts\Cache\CacheTrait` is where the other half of this bug lives; the `0` value in `$ctime` short-circuits the formula that otherwise works brilliantly.

**Comment by dharple** [comment]
Sample output from the console command that reproduces the issue:

    01:09:14 INFO      [app] running with a 0.10s delay ["delay" => "0.10"]
    01:09:14 INFO      [app] Lock acquired, now computing item "test-5373044919050655914" ["key" => "test-5373044919050655914"]
    01:09:26 INFO      [app] running with a 0.50s delay ["delay" => "0.50"]
    01:09:26 INFO      [app] Lock acquired, now computing item "test-4452018719803803369" ["key" => "test-4452018719803803369"]
    01:09:39 INFO      [app] running with a 0.90s delay ["delay" => "0.90"]
    01:09:39 INFO      [app] Lock acquired, now computing item "test-7097454395565359012" ["key" => "test-7097454395565359012"]
    01:09:51 INFO      [app] running with a 1.00s delay ["delay" => "1.00"]
    01:09:51 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:09:53 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.9s before its expiration ["key" => "test-2517168084299008080","delta" => "12.9"]
    01:09:53 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:09:55 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.8s before its expiration ["key" => "test-2517168084299008080","delta" => "12.8"]
    01:09:55 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:09:56 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 13.1s before its expiration ["key" => "test-2517168084299008080","delta" => "13.1"]
    01:09:56 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:09:58 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.3s before its expiration ["key" => "test-2517168084299008080","delta" => "12.3"]
    01:09:58 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:01 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 11.5s before its expiration ["key" => "test-2517168084299008080","delta" => "11.5"]
    01:10:01 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:03 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.1s before its expiration ["key" => "test-2517168084299008080","delta" => "12.1"]
    01:10:03 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:07 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 10.7s before its expiration ["key" => "test-2517168084299008080","delta" => "10.7"]
    01:10:07 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:09 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.8s before its expiration ["key" => "test-2517168084299008080","delta" => "12.8"]
    01:10:09 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:11 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 12.2s before its expiration ["key" => "test-2517168084299008080","delta" => "12.2"]
    01:10:11 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]
    01:10:15 INFO      [app] Item "test-2517168084299008080" elected for early recomputation 10.5s before its expiration ["key" => "test-2517168084299008080","delta" => "10.5"]
    01:10:15 INFO      [app] Lock acquired, now computing item "test-2517168084299008080" ["key" => "test-2517168084299008080"]

**Comment by nicolas-grekas** [comment]
Thank you for the detailed report, this should be fixed by #33846.

**Comment by dharple** [comment]
Thank you, Nicolas. I pulled a copy of your development branch and confirmed that your commit, https://github.com/nicolas-grekas/symfony/commit/ba63e181fd00b75bd3a7e74035665a69d337dbe7, fixes my issue.

**Comment by dharple** [comment]
Sorry, I closed this too soon.
