### ISSUE TITLE
Serializer does not map basic non-string types correctly in XML and CSV

### ISSUE THREAD

**Issue by mkrauser** [symfony/symfony#33849]
**Symfony version(s) affected**: 3.4, 4.4

**Description**  
In XML and CSV, all values are represented the same way, it is not possible to determine if a value is intended to be a string, int, float or boolean. 

If something with non string properties (int, float, bool) is deserialized, an error is thrown:

```
PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "width" attribute for class "App\Entities\Building" must be one of "float" ("string" given). in ./symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php:298
Stack trace:
#0 ./symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php(202): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize('App\\Entities\\Bu...', 'width', '10.1', 'xml', Array)
#1 ./symfony-collection-serializer-bug/Serializer.php(172): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
#2 ./symfony-collection-serializer-bug/Serializer.php(123): Symfony\Component\Serializer\Serializer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
...
```
**How to reproduce**  
I'll submit a PR with a failing test

**Possible Solution**  
The values need to be converted cast to the expected type. 

**Additional context**  
Tested with php 7.2

**Comment by warslett** [comment]
This is a massive problem which makes the Serializer component completely unusable with XML. We are required to handle XML content on our API so that it can integrate with legacy technology. Same problem in API Platform @dunglas

**Comment by warslett** [comment]
https://github.com/api-platform/api-platform/issues/1299

**Comment by warslett** [comment]
@mkrauser is this issue still moving? It's holding up the fix in API Platform. Let me know if you don't have time to finish it I'll pick it up in a separate PR.

**Comment by mkrauser** [comment]
@warslett Yes, definitly!

**Comment by ugo-fl** [comment]
I still get that issue in the case of a custom normalizer (`implements ContextAwareDenormalizerInterface` in my specific case).

My `denormalize` function checks if `$data` corresponds to an existing entity in the database, and calls `$this->serializer->denormalize($data, $class)` otherwise. In the end, I had to manually cast every attributes to float.
