### ISSUE TITLE
Can't override template/bundles folder in symfony 4.3 

### ISSUE THREAD

**Issue by Pasuvan** [symfony/symfony#33845]
Symfony version(s) affected: 3.4/4.3
**Description**  
Updating an Symfony 3.4 to Symfony 4.3 and the new flex directory structure.
Before using app/resource/view/sonataDoctrineOrmBundle/* now moved templates/bundles/SonataDoctrineOrmBundle. This was not overriding 
even with the file in the proper location according to the docs.
Liip/theme-bunlde also added my package

**How to reproduce**  

**Possible Solution**  
I think Liip/theme-bundle can not override template/bundles folder, Because this constructor has only 3 override folders only
```php
$defaultPathPatterns = array(
            'app_resource' => array(
                '%app_path%/themes/%current_theme%/%template%',
                '%app_path%/views/%template%',
            ),
            'bundle_resource' => array(
                '%bundle_path%/Resources/themes/%current_theme%/%template%',
            ),
            'bundle_resource_dir' => array(
                '%dir%/themes/%current_theme%/%bundle_name%/%template%',
                '%dir%/%bundle_name%/%override_path%',
            ),
        );
```
 here and locateBundleResource function need to change then only work.
https://github.com/liip/LiipThemeBundle/blob/master/Locator/FileLocator.php
**Additional context**  
Liip/theme-bundle upgrade not available for symfony 4.3 please give a solution
thanks,

**Comment by k0d3r1s** [comment]
check filename/folder case. 
I don't know what you were overriding, but bundle name should start with uppercase.

**Comment by Pasuvan** [comment]
@k0d3r1s yes I'm using an uppercase letter, typing mismatch. i override to vendor/sonata-dotrine-orm-bundle/views/CRUD/ .twig to templates/bundles/sonataDoctrineOrmBundle/.twig .Liip/theme-bunlde can not supprot symfony 4.3 *templates/bundles/* overriding.

**Comment by yceruto** [comment]
@Pasuvan the correct path is `templates/bundles/SonataDoctrineOrmBundle/` (note `Sonata*` instead of `sonata*`) and make sure to enable the templating configuration as discussed here https://github.com/symfony/symfony/issues/29299

**Comment by xabbuh** [comment]
@Pasuvan Does https://github.com/symfony/symfony/issues/33845#issuecomment-538382983 solve your issue?

**Comment by Pasuvan** [comment]
@yceruto I changed (Sonata* instead of sonata* and also) framework configuration, But not working overriding.
@xabbuh it's not solved.
Can you check that below link
https://github.com/liip/LiipThemeBundle/blob/master/Locator/FileLocator.php
i think LiipThemeBundle can not support symfony 4.3 overring because this constructor doesn't have templates/bundles/ path configuration. Please check that above link.
Thanks,

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue then? Though if this only doesn't work in the `FileLocator` from LiipThemeBundle, you will probably need to report the issue over there.

**Comment by Pasuvan** [comment]
Fixed https://github.com/liip/LiipThemeBundle/issues/201
