### ISSUE TITLE
Make it easier to use multiple mailers

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33874]
**Description**  
In #33409 it's explained that you need to do this to select the transport to use to send the email message:

```php
// use the first "main" transport
$mailer->send($email);

// or use the "important" one
$email->getHeaders()->addTextHeader('X-Transport', 'important');
$mailer->send($email);
```

That doesn't look very user friendly 😐  Could we make it easier to use? Maybe like [using multiple SwiftMailer mailers in Symfony apps](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#using-multiple-mailers)? (Maybe that's already the case and we just need to document it?) Or maybe add another argument to `send()` method or add another method to select the transport?

**Comment by nicolas-grekas** [comment]
Named autowiring aliases to the rescue?
I think that's the nice generic solution for all these multiple-services problems.

**Comment by xabbuh** [comment]
I agree with Nicolas.

**Comment by ro0NL** [comment]
a util like `$email->transport('important')` is still valueable though? To reduce the boilerplate ...

**Comment by fabpot** [comment]
We made a conscious decision here. There are already mechanisms in Symfony, so let's not add more.
