### ISSUE TITLE
Filesystem class improvement

### ISSUE THREAD

**Issue by vaso123** [symfony/symfony#33873]
**Description**  
In the class `Symfony\Component\Filesystem\FileSystem.php` there is an `exists()` method what is not usable as it is for so much things.

That could be good to improve it with add more methods, like `directoryExists` `fileExists`. It does not check what kind of type is it, just is that exists. Not check is that readable, writeable.

Of course I can handle it with the native `is_file()`, `is_dir()`, `is_executable()` functions, but that could be good, if it will be the job of `Filesystem` class.

**Example**  

`$fileSystem->fileExists($path, [Filesystem::READABLE_FILE, FileSystem::WRITEABLE_FILE]);`

also a public `writeable()` etc... could be handy...

`$fileSystem->fileExists($path)` without parameter just only need to check, is the file is exists and is it a file.

What do you think?

**Comment by jejem** [comment]
I improved the exists() method to be able to check against a file type (optional second argument), that means we are now able to check against files and directories, and differentiate them.

I considered the readable/writable/executable cases, and feel like they don't belong in an exists() context, as the operation is to check whether the file/directory is present on the filesystem. To me, readable/writable/executable is a permissions context and a second operation, aka: `if exists() and is readable`

I could work on a readable/writable/executable permissions checking in a following PR, in the meantime standard PHP functions would probably do the trick.

**Comment by nicolas-grekas** [comment]
I'm closing because `is_dir()` and `is_file()` are just fine. The component doesn't need to re-implement the native function that are working well enough.
Thanks for opening.
