### ISSUE TITLE
Select group and add extra attributes in Serializer

### ISSUE THREAD

**Issue by GaylordP** [symfony/symfony#33888]
Hello everyone,

With Symfony Serializer, I can select group with :

`[
    'groups' => 'api_index',
]`

I can select attributes with :

`[
    'attributes' => [...],
]`

I can ignore attributes with :

`[
    'ignored_attributes' => [...],
]`

But I want to select a group **and add extra attributes**.

Can you help me ?
Thanks you :)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
