### ISSUE TITLE
`lint:twig` is not allowing spaceship operator

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#33895]
**Symfony version(s) affected**: `symfony/twig-bridge:v4.3.5`

**Description**  

`lint:twig` command is marking spaceship operator (`<=>`) as unexpected token:
```
Unexpected token "operator" of value ">".
```
**How to reproduce**  

```{% for value in collection|sort((a, b) => b.id <=> a.id) %}```

**Comment by xabbuh** [comment]
Which version of Twig do you have installed?

**Comment by phansys** [comment]
`v2.12.0`. But Twig is working fine with that syntax. The only problem I've found is with the `lint:twig` command.

**Comment by phansys** [comment]
I'm sorry, the mistake was in my environment. I was using `v2.12.0` locally, while in the CI suite where the error was reported is running `v2.11.3`.
I'm closing this.
Thank you!
