### ISSUE TITLE
Translation keys passed in 'label_attr' are not being translated

### ISSUE THREAD

**Issue by o-alquimista** [symfony/symfony#33917]
**Symfony version(s) affected**: 4.3.4

**Description**  

Any translation keys passed in attributes of the label are not being translated. The key itself is rendered in the HTML.

**How to reproduce**  

Use something like this. I've also tested and reproduced the problem with other Form Types, such as EmailType. It likely affects all of them.
```
->add('avatar', FileType::class, [
    'label' => 'label.avatar',
    'required' => false,
    'label_attr' => [
        'data-browse' => 'label.select',
    ],
])
```
Then set the translation strings in `messages+intl-icu.<lang>.xlf`.

**The result:**
![Captura de tela_2019-10-08_15-40-24](https://user-images.githubusercontent.com/25424263/66423445-21c5c280-e9e2-11e9-9b5b-48f773acae82.png)
![Screenshot_2019-10-08 Symfony Profiler](https://user-images.githubusercontent.com/25424263/66423447-21c5c280-e9e2-11e9-8be5-2def937b6f79.png)

**Comment by xabbuh** [comment]
That's expected. By default, attributes are not translated. You will have to do that yourself.

**Comment by o-alquimista** [comment]
All right, I got it working using another approach suggested in the Bootstrap documentation. I'll close this.
