### ISSUE TITLE
Issues with AbstractTagAwareAdapter

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#33924]
I'm having a closer look at the implementation of `AbstractTagAwareAdapter`. Here are some notes for discussion (/cc @andrerom as the original author):
- `deleteItems()` calls `doFetch()` to get access to the tags stored next to an item. Because the values are stored as `['value' => $item->value, 'tags' => [...]]`, it means the value is actually unserialized when only the tags are needed. This can be problematic (perf-wise at least).
 That's the reason why `TagAwareAdapter` stores them under separate keys in the storage. Can we do the same here?
- `doClear($namespace)` doesn't clear the tags related to the items found in the namespace when one is provided. For `FilesystemTagAwareAdapter` that looks fixable. For `RedisTagAwareAdapter` I'm not sure how involving it could be. We could also consider this not worth fixing: the only side effect is that a value might be invalidated while it shouldn't (because it doesn't have the tag anymore).
- why use symlinks in `FilesystemTagAwareAdapter` instead of a single file that lists all item files? Using files would allow fixing `doInvalidate`, which leaks inodes right now.

**Comment by andrerom** [comment]
> That's the reason why `TagAwareAdapter` stores them under separate keys in the storage. Can we do the same here?

Unsure about code/logic implications here right now, but  I think we can.

> `doClear($namespace)` doesn't clear the tags related to ...

I think this was on purpose as it would eventually be consistent, but if we can fix it why not.

**Comment by nicolas-grekas** [comment]
I'm adding a third item: why use symlinks instead of a single file that lists all item files?

**Comment by nicolas-grekas** [comment]
@andrerom about the 3 listed issues, would you be able to fix some of them soon enough for 4.4?

**Comment by andrerom** [comment]
> I'm adding a third item: why use symlinks instead of a single file that lists all item files?

no specific reason, for more broad windows support it can be changed

> @andrerom about the 3 listed issues, would you be able to fix some of them soon enough for 4.4?

no availability to commit to look into this right now

**Comment by nicolas-grekas** [comment]
> File representing cache tag where you append cache keys?
> Could do that, but then:
> - more work (with race) to clean up relationship when tags are removed from an item _(unless we continue to view that as eventually consistent)

eventually consistent would be fine to me

> - can it hit file limits if it only appends and never cares if cache key is already there?

dunno, I'd say we don't care :)
a bloom filter could help implementing some dedup logic, but let's wait for the issue to arise.

> - on invalidation probably need to rename like with redis to be able to iterate and clear without race possibilities

yep - the current approach already has the possible races, but renaming the directory would break on Windows that's why we don't do it, isn't it?

>Would it be better than replacing symlinks with just simple files that contain the cache key as value?

Better maybe, by saving many inodes and fixing possible race conditions.

**Comment by andrerom** [comment]
> but renaming the directory would break on Windows that's why we don't do it, isn't it?

unsure
