### ISSUE TITLE
[String] Should UnicodeString return all code points for a given grapheme?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33923]
**Symfony version(s) affected**: 5.0

**Description**  
While documenting the new String component in https://github.com/symfony/symfony-docs/pull/12440 I found something which doesn't make sense to me.

A "grapheme cluster" is a series of one or more code points.

Then, why does our "grapheme string" return a single code point (the first one) instead of all of them for a given cluster?

**How to reproduce**  
Take for example the Hindi word "hello", which is `नमस्ते`.

```php
$bString = b('नमस्ते');

echo "Bytes: ";
for ($i = 0; $i < $bString->length(); $i++) {
    echo $bString->byteCode($i)." ";
}

$cString = $bString->toCodePointString();
echo "Code Points: ";
for ($i = 0; $i < $cString->length(); $i++) {
    echo $cString->codePoint($i)." ";
}

$uString = $bString->toUnicodeString();
echo "Grapheme Code Points: ";
for ($i = 0; $i < $uString->length(); $i++) {
    echo $uString->codePoint($i)." ";
}
```

The output is:

```
Bytes: 224 164 168 224 164 174 224 164 184 224 165 141 224 164 164 224 165 135

Code Points: 2344 2350 2360 2381 2340 2375

Grapheme Code Points: 2344 2350 2360 2340
```

However, I expected the output to be:

```
// ...

Grapheme Code Points: 2344 2350 [2360, 2381] [2340, 2375]
```

**Possible Solution**  
`UnicodeString` should not return `?int` but `?array` (the other classes should keep returning `?int`).

**Comment by stof** [comment]
Well, you are asking for a code point. A grapheme cluster is composed from multiple code points, but that does not make them a single codepoint.

We would need a `codePoints` method returning an array.

**Comment by stof** [comment]
> **Possible Solution**
> `UnicodeString` should not return `?int` but `?array` (the other classes should keep returning `?int`).

my suggestion is to have a different method name, which will be less confusing that having the same name with a different signature.

**Comment by nicolas-grekas** [comment]
`codePoint()` is the Unicode equivalent of [`ord()`](https://php.net/ord), which returns the code for the first character (byte in this case) also.

Here is a way to do what you want:
```
foreach (u('abc')->chunk() as $c) {
    echo $c->codePoint();
}
```

We need to provide a primitive that allows accessing a single code point in a string without forcing one to convert the full (potentially big string to array.

JavaScript names this `codePointAt`.

**Comment by stof** [comment]
@nicolas-grekas the issue here is that the index passed to UnicodeString are based on graphemes. And so some code points can never be retrieved at all from there. It always gives you the first code point of the cluster, with no way to access others.

**Comment by stof** [comment]
Javascript's `codePointAt` is the equivalent of `CodePointString::codePoint`, which allows you to get the code point at a given index, where incrementing the index moves to the next code point.
But `UnicodeString::codePoint` considers that incrementing the index moves to the next grapheme cluster.

**Comment by nicolas-grekas** [comment]
@stof indeed. Should we move the method to `CodePointString` only?

**Comment by gharlan** [comment]
CodePointString: `codePoint` with return type `?int`
UnicodeString: `codePoints` with return type `int[]|null`
?

**Comment by stof** [comment]
@nicolas-grekas for the existing method returning a single code point, definitely.
But having a method returning the list of code points for a given grapheme cluster might also be useful.
