### ISSUE TITLE
[Form] CollectionType's allow_add doesn't run Transformers

### ISSUE THREAD

**Issue by Tarmean** [symfony/symfony#33933]
**Symfony version(s) affected**: 4.3.3

**Description**  
When the form is rendered after submission the submitted form data normally goes through a `reverseTransform => transform` cycle.  
When a CollectionType field receives extra data and is configured with `allow_add` new fields are added for the extra data. However the data for those fields doesn't go trough the `reverseTransform => transform` cycle.

Motivation for wanting this is a ResolvedType which (usually) maps an id to a hidden id field and some resolved field. Think of an autocomplete field that returns in a hidden id field or an editable list where entries are displayed as markup but tagged with an id.

**How to reproduce**  

- Create a form type FooType and use `addViewTransformer` in `buildView`
- Create a form with a CollectionType field
- use `['entry_type' => FooType::class, 'allow_add' => true]` as options
- add a new field to the CollectionType list in the browser or using javascript
- When submitting and re-rendering the untransformed value will be shown

Here is code for an example. 

https://gist.github.com/Tarmean/f8dbd3da7f74a26f491bca57038c87e6

I can create a full bug reproducer if needed but am not sure how symfony usually sets up the dependencies. This example comes from a legacy app with some symfony components added.

**Comment by xabbuh** [comment]
@Tarmean Yes, please create a fully working application. That will make debugging the issue much easer. Thank you!

**Comment by xabbuh** [comment]
@Tarmean Do you have any update for us that allows us to investigate?

**Comment by Tarmean** [comment]
Probably gonna be a while until I get around to this. For now this is a workaround if anyone else runs into this:

```php
$form->handleRequest();
if (!$form->isSubmitted() || !$form->isValid()) {
    if ($form->isSubmitted()) {
        $formBuilder->setData($form->getData());
        $form = $formBuilder->getForm();
    }
```

**Comment by xabbuh** [comment]
Let's close for now then. We can reopen once we are able to reproduce the issue. Thank you for understanding.

**Comment by Tarmean** [comment]
Finally came around to this. The three files that matter are:

https://github.com/Tarmean/symfony_form_bug_reproduction/blob/6a382636db1da969adde0c3f3710a1c4fc477fcd/src/Controller/DefaultController.php
https://github.com/Tarmean/symfony_form_bug_reproduction/blob/6a382636db1da969adde0c3f3710a1c4fc477fcd/src/Forms/PassthroughType.php
https://github.com/Tarmean/symfony_form_bug_reproduction/blob/6a382636db1da969adde0c3f3710a1c4fc477fcd/src/Forms/TransformedType.php

Without the line

        $form = $b->getForm()->setData($form->getData());

one gets

```
Direct transformed(reverseTransform(direct))
Indirect
Child indirect
```

with the line one gets

```
Direct transformed(reverseTransform(direct))
Indirect
Child transformed(reverseTransformed(indirect))
```


However doing this also removes all form errors so doing this is likely a horrible idea.

I actually did also track down why this happens. Simplifying the control flow in Symfony\Component\Form\Form::submit a lot one gets:

![FormFlow](https://user-images.githubusercontent.com/11866759/73747069-e3090480-4756-11ea-8bf9-4d6dd034c93c.png)

The submitted data is first propagated to the leaves. Afterwards the transformers are run. 

- In a non-compound type this directly changes view data and is rendered
- In a compound type this also changes view data but never reaches the children so it is not rendered

The only sensible solution I can spot is to set the transformed data on the children when the transformer is on a compound type
