### ISSUE TITLE
PhpDumper tries to access undefined method Alias::isShared

### ISSUE THREAD

**Issue by gquemener** [symfony/symfony#33942]
**Symfony version(s) affected**: 4.2+

**Description**  
PhpDumper tries to access unknown method `isShared` from class `Symfony\Component\DependencyInjection\Alias`.

Here's the exact PHP error:
```
Error: Call to undefined method Symfony\Component\DependencyInjection\Alias::isShared() 

/app/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1892
/app/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:184
```

**How to reproduce**  
1. Clone the https://github.com/prooph/service-bus-symfony-bundle repository
2. Install the dependencies (this will install `symfony/dependency-injection:4.3.*`)
3. Run the testsuite (`./vendor/bin/phpunit`)

I haven't been able (yet) to create a more minimalist environment, sorry about that!

**Possible Solution**  
In `PhpDumper::isSingleUsePrivateNode`, apply the following patch:
```patch
- if ($edge->isLazy() || !$value->isShared()) {
+ if ($edge->isLazy() || ($value instanceof Definition && !$value->isShared())) {
```

**Additional context**  
Further investigations are being led on https://github.com/prooph/service-bus-symfony-bundle/issues/79

**Comment by nicolas-grekas** [comment]
`if ($edge->isLazy() || !$value instanceof Definition || !$value->isShared()) {` should do it.
Tests still fail after the change, but I don't know why. At least the fatal error is gone.
Please submit a PR on 4.3 when you're ready.

**Comment by gquemener** [comment]
> if ($edge->isLazy() || !$value instanceof Definition || !$value->isShared()) { should do it.

Sure, however I'm not sure what I'm doing here. I've spent a few hours trying to understand the internal of the php dumper and wondering where was the bug.
Is it that we have an Alias instance as the node value (thus, the bug is on the bundle side), or is it that the `isSingleUsePrivateNode` method does not handle this case (thus, the bug is on the component side).

What do you think?
By reading the docblocks, it seems that having an `Alias` as the node value is a valid use case (https://github.com/symfony/symfony/blob/v4.3.5/src/Symfony/Component/DependencyInjection/Compiler/ServiceReferenceGraphNode.php#L101-L105).

**Comment by gquemener** [comment]
For information, the testsuite of the bundle passes with `symfony/dependency-injection:4.1.12`, `symfony/http-kernel:4.1 `symfony/framework-bundle:4.1`.

**Comment by nicolas-grekas** [comment]
> if ($edge->isLazy() || !$value instanceof Definition || !$value->isShared()) { should do it.

this patch is clearly needed
dunno yet why the test fail then
