### ISSUE TITLE
.gitattribute updates

### ISSUE THREAD

**Issue by reedy** [symfony/symfony#33946]
Is it possible to get a .gitattributes file added to exclude tests and .gitignore to these two repos https://github.com/symfony/translation-contracts and https://github.com/symfony/service-contracts ?

Wasn't sure the right place to report this as the issues are disabled over there

Other repos like symfony/yaml are missing .gitignore

Is it possible to get the .gitattributes files more widely across the various repos, with at least tests and .gitignore in them?

Thanks!

**Comment by nicolas-grekas** [comment]
There is nothing to remove from service-contracts (the `Test` is part of the contracts)
And one should not use symfony/contracts but always use symfony/*-contracts.
That's why these two files don't exist.

**Comment by Tobion** [comment]
> There is nothing to remove from service-contracts (the Test folder is part of the contracts.)

What do you mean? https://github.com/symfony/service-contracts/blob/master/Test/ServiceLocatorTest.php should be excluded shouldn't it?

**Comment by nicolas-grekas** [comment]
Nope it shouldn't: it's part of the dependencies one can use to run their test suites. We use the same convention for all Symfony components: `Test` folder vs `Tests` one.

**Comment by Tobion** [comment]
I see, maybe the class should be made abstract to clarify it's not actually used for tests inside the contracts. And https://github.com/symfony/service-contracts/blob/ffcde9615dc5bb4825b9f6aed07716f1f57faae0/Test/ServiceLocatorTest.php#L20 could be protected as far as I see.

**Comment by nicolas-grekas** [comment]
Good idea, up for sending the PR?

**Comment by reedy** [comment]
This seems a useful clarification :). It certainly makes more sense that they are needed

>Other repos like symfony/yaml are missing .gitignore

If stuff like this can be done too, and normalise it across the repos etc, that'd be appreciated

**Comment by nicolas-grekas** [comment]
PR welcome.
