### ISSUE TITLE
Optionally fail for deprecations in our various lint commands

### ISSUE THREAD

**Issue by stof** [symfony/symfony#33957]
A common use case for the lint commands (`lint:yaml`, `lint:twig` and `lint:xliff`) is to run them on CI.
While they report syntax errors currently, they don't allow failing when a deprecated feature is used (this is relevant at least for twig and yaml today). If would be great if they could have an option that would turn on reporting of any deprecation triggered as part of the parsing rather than only reporting parsing errors. This way, the CI can also prevent using deprecated Twig/YAML features.

**Comment by chalasr** [comment]
`lint:yaml` already reports deprecation notices as parse errors since https://github.com/symfony/symfony/pull/22274. 
👍for doing the same for twig and making it opt-in.

**Comment by yceruto** [comment]
:+1: PR for `lint:twig` here https://github.com/symfony/symfony/pull/33961
