### ISSUE TITLE
How to force Symfony/Var-Dumper to use __debugInfo() method?

### ISSUE THREAD

**Issue by 6562680** [symfony/symfony#33952]
I saw there is $hasDebugInfo variable in Caster.php, and its detecting correctly, but when i dumping my variable i still see those variables that been removed inside __debugInfo() as object properties.

For example - am trying to hide "container" property from object (container is very big to process it)

```
public function __debugInfo()
{
  $data = get_object_vars($this);
  unset($data['container']);
  return $data;
}

dd($object); // MyObject ( #container: ... )
var_dump($object); // object(MyObject)#23 {}
```

Hope, somebody could help me...

**Comment by nicolas-grekas** [comment]
If you want to override a property, you must use its full name as generated by the `(array)` casting operator.

**Comment by 6562680** [comment]
tried
unset($data['*container']);
unset($data[' *container']);
unset($data['* container']);
unset($data[' * container']);
unset($data['#container']);

Container still there.

Analyzed Caster.php code - it first cast through (array) caster, then adding values from __debugInfo() instead of intersection...

**Comment by nicolas-grekas** [comment]
you cannot unset a value, but you can set it to something else:
`$data["\0*\0container"] = new CutStub($this->container);`

**Comment by nicolas-grekas** [comment]
Note that you could also register `['Symfony\Component\VarDumper\Caster\StubCaster', 'cutInternals']` as a caster of your VarCloner instance and get rid of all container objects everywhere.

**Comment by 6562680** [comment]
will try ty

**Comment by 6562680** [comment]
I replaced it manually with CutStub, dump starts to working 10times faster, but property still there... am confused but expected effect received.

**Comment by genesiscz** [comment]
I know it is an old question, but if somebody wonders how to do that: Don't forget that it's `\0*\0`, not the spaces you tried there
