### ISSUE TITLE
Missing cache item tags with TagAwareAdapter and Redis eviction policy 

### ISSUE THREAD

**Issue by v-m-i** [symfony/symfony#33953]
**Symfony version(s) affected**: 3.4.31 (probably other versions too)

**Description**  

Tags on cached items might be randomly lost when using TagAwareAdapter with RedisAdapter as items pool and having Redis set with eviction policy that evicts keys. Because of that, affected items can't be invalidated using tags but are still treated as valid items (cache hit) when retrieved from cache.

**How to reproduce**  

1) Create item-tags pair in Redis using `TagAwareAdapter`, for example:
   - `"something:my-great-item"`
   - `"something:\x00tags\x00my-great-item"`
1) Fetch it using `TagAwareAdapter`
   - returned CacheItem has `isHit` set to `true` and `getPreviousTags` returns tags
1) Manually delete `tag` from pair to simulate eviction:
   - `DEL "something:\x00tags\x00my-great-item"`
1) Fetch it using `TagAwareAdapter`
   - returned CacheItem has `isHit` set to `true` and `getPreviousTags` returns empty tags, making it impossible to invalidate

**Possible Solution**  

If I am correct, cache items are always stored in item-tags pairs, regardless of item having or not having tags. Based on that, when item is fetched and does not have tags pair it should be deleted from cache and treated as cache miss.

**Comment by nicolas-grekas** [comment]
Thanks for the detailed report.
An alternative solution might be to always set a shorter expiration date on items than on their tags, so that eviction for items would always happen prior to tags.
/cc @andrerom am I right?

**Comment by andrerom** [comment]
So unless something got changed now, tags don't have a expiration, but cache has.

This is why this adapter requires that you use `volatile-*` eviction policies, see:
https://github.com/symfony/symfony/blob/38b9a27976d36c4ffbfeb9e666319d77ffc8b3c0/src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php#L32-L33

**Comment by nicolas-grekas** [comment]
Note that the report is about `TagAwareAdapter`. How does this problematic applies to it?

**Comment by andrerom** [comment]
Ah, sorry assumed RedisTagAwareAdapter given you cc'ed me here..
--
Both proposed solutions should be done imho :)

**Comment by v-m-i** [comment]
As far as I see, setting shorter expiration date would work only for `volatile-ttl` policy. 

That sounds fine, but I agree with @andrerom that both solutions should be done as we want to be sure that loaded CacheItem is in valid state, regardless of way it was retrieved and policy that is used.

**Comment by nicolas-grekas** [comment]
But your solution alone would be enough right? Since it's way easier to implement and requires ad hoc configuration of the Redis server, no need to implement the expiry-based one then.

Would you be able to send a PR with the fix? (on branch 3.4)

**Comment by v-m-i** [comment]
Yes, it would be enough.

Sure, I can do PR with the fix :)
