### ISSUE TITLE
[Workflow] Increase checks to ensure a valid statemachine

### ISSUE THREAD

**Issue by holtkamp** [symfony/symfony#33972]
**Description**  
Currently it is possible to instantiate an "invalid" StateMachine. It would be nice to have some checks in place to prevent this.

**Example**  
For example:

```php
<?php

use Symfony\Component\Workflow\Definition;
use Symfony\Component\Workflow\StateMachine;
use Symfony\Component\Workflow\Transition;

$states = ['created', 'activated', 'deleted'];
$stateTransitions = [
    new Transition('activate', 'created', 'activated'),
    new Transition('activate', 'created', 'deleted'), //oops, copy-paste mistake: 'activate' should have been 'delete'
];
$definition = new Definition($states, $stateTransitions);
$stateMachine = new StateMachine($definition);
```

This would result in an "invalid" StateMachine... 

<img width="275" alt="Screenshot 2019-10-13 at 19 25 50" src="https://user-images.githubusercontent.com/776405/66719415-b3bd3900-edef-11e9-94ad-8d37cfb06f85.png">

Maybe some inspiration can be derived from [this implementation of a StateMachine](https://github.com/zf1/zend-search-lucene/blob/8a07584308d86c86fdd9f743d574cc2cbfffc7ac/library/Zend/Search/Lucene/FSM.php#L268)

**Comment by OskarStark** [comment]
cc @lyrixx

**Comment by lyrixx** [comment]
Even if there is a typo, this workflow is totally valid. With a state machine, you can have many transitions with the same name and with the same origin.
I don't see how we can validate something here.
I read the code you linked and they put more limitation on a workflow... so we can not grab this code.

**Comment by stof** [comment]
> With a state machine, you can have many transitions with the same name and with the same origin.

are you sure about that for a state machine ? Wouldn't you move you to multiple states ?

IIRC, we allow having the same name with *different* origins.

I think the main issue here is that the validator is not applied on your definition, so you don't run the checks. These checks are not part of the StateMachine constructor for performance reason: if you define your workflow in the config file, Symfony will run the validation during cache warmup, and so running the validation on each instantiation would be useless overhead.

**Comment by holtkamp** [comment]
>are you sure about that for a state machine ? Wouldn't you move you to multiple states ?

Indeed, a (Finite)StateMachine can only be in one state at a certain moment in time. For WorkFlows this rule does not apply...

**Comment by lyrixx** [comment]
> are you sure about that for a state machine ? Wouldn't you move you to multiple states ?

You make me doubt :) I guess you are right!

@holtkamp As @stof mentionned, some validator already exist. And this issue is already [covered](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Workflow/Validator/StateMachineValidator.php#L38-L41)

I think we can close this issue, and there is nothing we can do here since everything already exist.

**Comment by holtkamp** [comment]
>I think we can close this issue,

Indeed, I was not aware of the [StateMachineValidator](https://github.com/symfony/symfony/blob/16d528504cd57c4f967ea095e8c603260e119125/src/Symfony/Component/Workflow/Validator/StateMachineValidator.php)

Closing issue!

**Comment by lyrixx** [comment]
> maybe it can be documented?

Good idea. Would you mind open a PR or an issue ?

**Comment by holtkamp** [comment]
@lyrixx sure, will give a PR a shot. 

I suppose a section on [this page](https://symfony.com/doc/4.4/components/workflow.html) would be the most appropriate?
