### ISSUE TITLE
Fatal error: Allowed memory size exhausted (Monolog)

### ISSUE THREAD

**Issue by o-alquimista** [symfony/symfony#33976]
**Symfony version(s) affected**: 4.3.5

**Description**  

Today I setup a Symfony website on a VPS. It operates normally... until I try to upload an image in a form. I get this error about memory, even though I am not running out of RAM (it's not even swapping yet).
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/devdungeon/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 108

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/devdungeon/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
```

The size of the image doesn't matter. The amount of data it tries to allocate is always 20480 and 32768. I tried with an 800 KB image and a 3.6 MB image.

At home, on my development system, this doesn't happen. The VPS was configured with the exact same PHP and Apache settings. I literally just copy-pasted them from here onto the VPS. The only difference is that while the VPS has only 1 GB of RAM, this machine here has 8 GB.

Things I've tried:
- Increased memory_limit from 128 MB to 256 MB, didn't solve it.

PHP settings I'm overriding:
```
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
post_max_size = 24M
upload_max_filesize = 6M

[Date]
date.timezone = UTC
```

Output of `free -m`
```
              total        used        free      shared  buff/cache   available
Mem:            954         489         170          15         293         304
Swap:           952           3         949

```

VPS specs:
- Ubuntu Server 18.04.3 LTS
- RAM: 1 GB (using 531MiB of 954MiB)
- CPU: Intel Xeon Silver 4114 CPU @ 2x 2.195GHz
- Kernel: x86_64 Linux 4.15.0-39-generic

**How to reproduce**  

To try to reproduce this, you should setup this project according to the instructions in the README.md file: https://github.com/o-alquimista/devdungeon. If you want to reproduce this on the application currently running on my VPS, head to http://191.252.204.98/en/user/settings/profile, login as user `symfony` and password `symfony` and try to upload any profile picture.

**Additional context**  

PHP error log is attached. Relevant errors are near the bottom.
[phpErrorLog.txt](https://github.com/symfony/symfony/files/3722508/phpErrorLog.txt)

**Comment by o-alquimista** [comment]
Apparently it was a permission problem on the project directory. After fixing the ownership and permissions of the project files, I can no longer reproduce this.

**Comment by tomaszkane** [comment]
It also may be caused by missing SELinux permissions (CentOS).

**Comment by kundukundu** [comment]
On Ubuntu, I did

` composer update`

And it's working well now.

**Comment by danbower** [comment]
It was a permission issue for me as well although it was falling over at a different point in the code. I had the wrong php-fpm user set and the permission issue would produce some weird nested encoding which was eating up all of the memory. Very hard to pin down and although it's not really a library issue, I found very few results on Google so thought this might help someone.

**Comment by gentooza** [comment]
Hi, I've the same problem using symfony 5 in a virtual server through Canonical's multipass
Could you explain with more detail, what to check about permissions and ownership? 

cheers
