### ISSUE TITLE
[Routing] Trailing hyphen matching error

### ISSUE THREAD

**Issue by anasbouzid** [symfony/symfony#33977]
**Symfony version(s) affected**: 4.3.5

**Description**  
A route with a hyphen `-` followed by an optional parameter doesn't match a URL without a parameter

**How to reproduce** 
First, run `composer require symfony/routing`
Then, execute this code:
```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Routing\Matcher\UrlMatcher;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

$route = new Route('/foo-{slug?}');
$routes = new RouteCollection();
$routes->add('foo', $route);

$context = new RequestContext('/');

$matcher = new UrlMatcher($routes, $context);

var_dump($matcher->match('/foo-'));
// Raise ResourceNotFoundException

var_dump($matcher->match('/foo'));
// Unexpectedly matches

var_dump($matcher->match('/foo-bar'));
// Works as expected
```

**Comment by Tobion** [comment]
This is the expected behavior at the moment. See https://github.com/symfony/symfony/blob/791810a4e14c7b8fe1165c16e762fcb2a1ad10fa/src/Symfony/Component/Routing/RouteCompiler.php#L24-L29

What's the use-case for matching `/foo-`?
