### ISSUE TITLE
@ParamConverter not found fails phpunit test with symfony/skeleton

### ISSUE THREAD

**Issue by LaurentMarquet** [symfony/symfony#33989]
**Symfony version(s) affected**: 4.3

**Description**  
Not finding an Entity via @ParamConverter makes the phpunit test fail if project is created with `symfony/skeleton`.

**How to reproduce**  
I have built 2 projects [ParamConverterPass](https://github.com/LaurentMarquet/ParamConverterPass) and [ParamConverterFail](https://github.com/LaurentMarquet/ParamConverterFail) to help reproduce the problem.

The problem is that if we use @ParamConverter to get a **non-existing entity**, with Doctrine, using data in url, it will make the phpunit test fail if the project is built with `symfony/skeleton`.

Even if both projects return 404, the one built with `symfony/skeleton`is not catched by phpunit and return "Sorry, the page you are looking for could not be found." while the one built with `symfony/website-skeleton` return "App\Entity\Player object not found by the @ParamConverter annotation."

**Possible Solution**  
Haven't got time to investigate yet

**Additional context**

**Comment by stof** [comment]
This is probably related to the fact that before Symfony 4.4 (where the ErrorRenderer component is introduced precisely to solve that), the handling of error pages is implemented by TwigBundle, and `symfony/skeleton` does not install it.

**Comment by LaurentMarquet** [comment]
Yes, but my "main" problem is that the phpunit test fails, even if 404 is launched.
As it's for an API, Twig is not really required.
I have tried by requiring twig and I receive (in phpunit execution) "2019-10-15T15:19:38+02:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "App\Entity\Player object not found by the @ParamConverter annotation." at /home/laurent/web/dev/github/issues/ParamConverterFail/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php line 107" but the test passes.

**Comment by dmaicher** [comment]
Should this not be fixed since this PR?

https://github.com/symfony/symfony/pull/27519

**Comment by LaurentMarquet** [comment]
It seems not.
I've tried by replacing the content of the files with the PR but I still have "Symfony\Component\HttpKernel\Exception\NotFoundHttpException: App\Entity\Player object not found by the @ParamConverter annotation." and "/home/.../vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php:107".
SF 4.3.5 is used

**Comment by dmaicher** [comment]
Ok this is indeed not working anymore. It was reverted in https://github.com/symfony/symfony/pull/31868

So on 4.3 you either add your own KernelExceptionListener that could turn this exception into a response or you need to install the `twig-pack`.

As @stof mentioned on 4.4 it will work out of the box :blush:

**Comment by LaurentMarquet** [comment]
Yes it works with Twig, but the test still return the error between the tests: 

```
ParamConverterFail$ php bin/phpunit
PHPUnit 7.5.16 by Sebastian Bergmann and contributors.

Testing Project Test Suite
.2019-10-18T10:35:14+02:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "App\Entity\Player object not found by the @ParamConverter annotation." at /home/.../vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php line 107
.                                                                  2 / 2 (100%)
```

Time: 226 ms, Memory: 16.00 MB

But let's close this issue as it's solved in 4.4
Thanks!

**Comment by dmaicher** [comment]
You can get rid of the log output by adding a "real logger" like monolog. You can simply install `symfony/monolog-bundle` :wink:

**Comment by LaurentMarquet** [comment]
Yep it disappeared :) by using too much `symfony/website-skeleton` you forget what's "inside"...
Thanks!
