### ISSUE TITLE
[RFC]Disable schema:update if you use migration command

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony#33988]
**Description**  
Since i use migration file in project with team, i can't block command schema:update for forcing used migration only. 

I think use a configuration or other possibility (optionnal) for choose only one of command.

**Example**  
For example in .env 
DATABASE_UPDATE:MIGRATION_FILE

**Comment by stof** [comment]
this command is not part of symfony/symfony, so this is not something that can be solved in this repo.

**Comment by TheGarious** [comment]
@stof oh ok, doctrine repo is right for this issue?

**Comment by javiereguiluz** [comment]
@TheGarious the `schema:update` command is implemented here: https://github.com/doctrine/DoctrineBundle/blob/master/Command/Proxy/UpdateSchemaDoctrineCommand.php  so please, open the issue here: https://github.com/doctrine/DoctrineBundle/issues

Thanks!
