### ISSUE TITLE
Unable to upgrade from 4.2 to 4.3 on prod, works fine on dev

### ISSUE THREAD

**Issue by lfjeff** [symfony/symfony#33984]
**Symfony version(s) affected**: 4.3

**Description**  
I am unable to upgrade to from 4.2.11 to 4.3.5 on my production system.  I cannot reproduce the problem in the dev environment, the upgrade works fine there and everything runs OK.

I had the same problem when the initial 4.3 release came out, so I thought I would wait for a few more releases.  However, I have the same problem with 4.3.5

I tried fixing all the issues that were giving me deprecation warnings, but it makes no difference.

**How to reproduce**  
I cannot reproduce in my dev environment. It only occurs on my production system (Ubuntu 16.04/Apache 2.4.8/PHP 7.2.22)

After running `composer install` and `php bin/console cache:clear` on production, I get the errors below...

**Additional context**  
...
  - Updating symfony/web-profiler-bundle (v4.2.11 => v4.3.5): Loading from cache
  - Updating symfony/process (v4.2.11 => v4.3.5): Loading from cache
  - Updating symfony/console (v4.2.11 => v4.3.5): Loading from cache
  - Updating symfony/web-server-bundle (v4.2.11 => v4.3.5): Loading from cache
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!  PHP Fatal error:  Method class@anonymous::__toString() must not throw an exception, caught Symfony\Component\DependencyInjection\Exception\AutowiringFailedException:  in /home/avrsites/websites/booking.azvr.com/symfony/vendor/symfony/dependency-injection/Compiler/AutowirePass.php on line 233
!!  16:54:30 CRITICAL  [php] Fatal Error: Method class@anonymous::__toString() must not throw an exception, caught Symfony\Component\DependencyInjection\Exception\AutowiringFailedException:  ["exception" => Symfony\Component\Debug\Exception\FatalErrorException^ { …}]
!!
!!  In AutowirePass.php line 233:
!!
!!    Error: Method class@anonymous::__toString() must not throw an exception, ca
!!    ught Symfony\Component\DependencyInjection\Exception\AutowiringFailedExcept
!!    ion:
!!

**Comment by mhujer** [comment]
@lfjeff have you tried removing `var/cache/` directory manually to be sure that it is not a caching issue?

What happens when you try to run cache clear and warmup on your **dev** machine with `--env=prod`?
```
php bin/console cache:clear --env=prod
php bin/console cache:warmup --env=prod
```

**Comment by lfjeff** [comment]
Yes, I tried manually deleting the cache on production and the problem still occurs.  I also tried setting `--env=prod` on my dev system, but I still cannot duplicate the problem.

I can't do much testing on the production server (or people quickly start complaining), so I'm a bit stuck. I've never had any problems with Symfony updates up thru 4.2.11, they only occurred when I tried upgrade to 4.3.  As soon as I roll things back to 4.2.11, production works normally.

**Comment by nicolas-grekas** [comment]
Can you go inside that `__toString` method and report back the exception that cannot get through?

**Comment by lfjeff** [comment]
```226             $getValue = function () use ($type, $parameter, $class, $method) {
227                 if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_IN#
228                     $failureMessage = $this->createTypeNotFoundMessageCallback($ref, sprintf('argument "$%s" of method "%s()"', $par#
229
230                     if ($parameter->isDefaultValueAvailable()) {
231                         $value = $parameter->getDefaultValue();
232                     } elseif (!$parameter->allowsNull()) {
233                         throw new AutowiringFailedException($this->currentId, $failureMessage);
234                     }
235                 }
```

**Comment by lfjeff** [comment]
Did some hot testing on production and here are the values just before the exception is thrown on line 233:
```
type=Braintree\WebhookNotification
parameter=ReflectionParameter Object
(
    [name] => notification
)

class=App\Webhook\Event\BraintreeWebhookEvent
method=__construct
currentId=App\Webhook\Event\BraintreeWebhookEvent
```

**Comment by lfjeff** [comment]
If comment out line 233,
`//throw new AutowiringFailedException($this->currentId, $failureMessage);`
then everything seems to work normally.

**Comment by lfjeff** [comment]
Here's something interesting I found when tracing the execution on my `dev` server...

Line 233 is throwing the same exception on `dev`, but it is apparently being caught someplace.  On `prod`, the exception is not caught and causes a failure.

**Comment by lfjeff** [comment]
I don't understand this...

On line 228, `$failureMessage` is set and is a Closure Object.  On line 233, `$failureMessage` is passed to `AutowiringFailedException()` which is expecting a `string` as the second argument.

This is what triggers the `__toString()` method. And a Closure Object apparently does not have a default `__toString()` defined.  This means that the non-existent `__toString()` exception is triggered first and the `AutowiringFailedException()` never happens.

However, this does not explain why the exception is caught on `dev` and not on `prod`

**Comment by lfjeff** [comment]
Found a fix, but don't like it...

If I change `BraintreeWebhookEvent::__construct()` to allow a null to be passed on the first argument, it fixes the issue:

`public function __construct(?WebhookNotification $notification, $testMode = false)`

However, I don't really want to allow a null be passed as the first argument.  Also, Symfony 4.3 insists on trying to autowire this class, even when I try to exclude it in my `services.yaml` file:
```
App\Webhook\:
    resource: '../src/Webhook/*'
    exclude: '../src/Webhook/{Entity,Event,Migrations,Tests,Kernel.php}'
```
Could that be the real problem?

**Comment by javiereguiluz** [comment]
@lfjeff did you finally fix this issue or found an alternative solution? Thanks!

**Comment by lfjeff** [comment]
This was fixed, don’t remember the details anymore. Now I’m working on upgrade from 4.4 to 5.0.

**Comment by xabbuh** [comment]
Let's close then. Thank you for the feedback.

**Comment by arnaudbagnis** [comment]
Hello I have the same error. Only this issue has the same error as me.
If anyone has even a stupid idea, I'll take it. I've been stuck on it for a long time ...
my **composer.json** :
```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "accord/mandrill-swiftmailer-bundle": "^1.3",
        "api-platform/api-pack": "^1.1",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/doctrine-bundle": "^1.0",
        "doctrine/doctrine-migrations-bundle": "^2.2",
        "doctrine/orm": "^2.7",
        "friendsofsymfony/ckeditor-bundle": "^2.1",
        "friendsofsymfony/user-bundle": "~2.0",
        "knplabs/knp-paginator-bundle": "^4.0",
        "paragonie/random_compat": "^2.0",
        "ramsey/uuid-doctrine": "^1.4",
        "sensio/framework-extra-bundle": "^5.1",
        "sentry/sentry-symfony": "^3.1",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/asset": "^4.1",
        "symfony/console": "^4.1",
        "symfony/dotenv": "^4.1",
        "symfony/expression-language": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.1",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/monolog-bundle": "^3.1",
        "symfony/process": "^4.1",
        "symfony/security-bundle": "^4.1",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "^4.1",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "^4.1",
        "symfony/web-link": "^4.1",
        "symfony/webpack-encore-pack": "*",
        "symfony/yaml": "^4.1",
        "vich/uploader-bundle": "^1.9"
    },
    "require-dev": {
        "hautelook/alice-bundle": "^2.0",
        "doctrine/data-fixtures": "^1.3",
        "behat/behat": "^3.4",
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^4.1",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "^1.0",
        "symfony/web-server-bundle": "^4.1"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}
```
