### ISSUE TITLE
EnvelopeListener manipulates wrong header

### ISSUE THREAD

**Issue by auipga** [symfony/symfony#33991]
**Symfony version(s) affected**: ^4.3

**Description**  
EnvelopeListener manipulates BCC instead of TO

**How to reproduce**  

- https://github.com/auipga/symfony-envelope-bug
- set `GMAIL_USERNAME=` and `GMAIL_PASSWORD=` in `.env`file
- run `symfony console send:mail`

**Possible Solution**  
n/a

**Additional context**  
https://github.com/symfony/symfony-docs/issues/11836

**Comment by fabpot** [comment]
EnvelopeListener does not manipulate To or Bcc, it changes the envelope of the message.

**Comment by auipga** [comment]
Yes, it's a Gmail thing... See https://github.com/symfony/symfony-docs/issues/11836#issuecomment-542289171
