### ISSUE TITLE
[Mailer] Amazon SES error when message id is empty

### ISSUE THREAD

**Issue by garak** [symfony/symfony#34006]
**Symfony version(s) affected**: 4.4.0-DEV

**Description**  
Sending an email with Amazon SES is resulting in an error:
>Argument 1 passed to Symfony\Component\Mailer\SentMessage::setMessageId() must be of the type string, null given, called in /myproject/vendor/symfony/amazon-mailer/Transport/SesHttpTransport.php on line 71

**How to reproduce**  
Just send an email with Amazon SES

**Additional context**  
Problem was introduced in b42c269760b1f1c5735631e103eb0ddf9504000e

**Comment by fabpot** [comment]
Could you submit a PR to fix that? Thank you.

**Comment by garak** [comment]
Of course, I'm just not sure about the wanted behavior.
Can we just accept `null` values in `setMessageId()` method?

**Comment by fabpot** [comment]
But why is it null? It should not.

**Comment by garak** [comment]
I tried a dump of `$result`, got this:
```
SimpleXMLElement {#3442 ▼
  +"SendRawEmailResult": SimpleXMLElement {#3464 ▼
    +"MessageId": "0102016dd9b768cc-166564d6-675e-4605-9f32-e8edb85d847a-000000"
  }
  +"ResponseMetadata": SimpleXMLElement {#3488 ▼
    +"RequestId": "6d618837-ae6e-4019-befb-13d868314b4b"
  }
}
```

**Comment by limitstudios** [comment]
Are you sending attachments look at getPayload() in the SES mailer transport we change the action from SendEmail to SendRawEmail so looks like we need to change where we get the messageId from after

**Comment by garak** [comment]
I'm not sending any attachment

**Comment by limitstudios** [comment]
Ok are you sending plain text, html or both

**Comment by garak** [comment]
I use inky, so I guess it's both text and html

**Comment by fabpot** [comment]
see #34015 Can you confirm it fixes your issue? Would be great if you could switch to `ses+api` to see if that works as well.

**Comment by limitstudios** [comment]
Yep that would be it as when multipart is used it goes via SendRawEmail

**Comment by garak** [comment]
@fabpot proposed PR is OK for me.
Sorry, but I can't try `ses+api` option too

**Comment by fabpot** [comment]
@limitstudios updated
