### ISSUE TITLE
[Mailer] Memory spool?

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#34010]
**Description**  
In swiftmailer we had the option to memory spool the messages so that they would be sent at the end of the request rather than send them right away. Reading through the Mailer and Messenger docs I couldn't find any equivalent option, either it's "send them right away" or "send them to a remote queue and then use a worker". There's an in-memory transport on the Messenger component but it seems to be used only for testing purposes.

So should we have a `InMemoryTransport` on the mailer component? It would be basically a memory buffer + an `onTerminate` request listener that should be registered.

Thanks!

**Example**  

```
swiftmailer:
    spool: { type: 'memory' }
```

**Comment by fabpot** [comment]
We talked about having a Messenger transport that would handle messages on the terminate event and after some back and forth (we even had a PR), we decided against it.

**Comment by acasademont** [comment]
@fabpot I understand, maybe a note in the docs would come in handy talking about it and proposing alternatives. Especially for those of us who are trying to "upgrade" from SwiftMailer, the first thing I was looking for is this page (https://symfony.com/doc/current/email.html#how-to-spool-emails) on the Mailer docs (https://symfony.com/doc/current/mailer.html)
