### ISSUE TITLE
[Messenger] TraceableMessageBus is still enabled when debug=false

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#34026]
**Symfony version(s) affected**: 4.3.5

**Description**  
`messenger_debug.xml` does not depend on `kernel.debug`, see [line](https://github.com/symfony/symfony/blob/0b4c37a36c01673b27d5789b8ff24e5021993c19/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L537). Is that on purpose?

**Comment by xabbuh** [comment]
That part is only executed when the profiler is enabled (we do the same for other components here btw.). Did you experience any actual issues?

**Comment by vudaltsov** [comment]
So in `dev` with enabled profiler this is the expected behavior, right?

![image](https://user-images.githubusercontent.com/2552865/67095267-2c404300-f1be-11e9-9dcd-7834d3130b3f.png)

**Comment by vudaltsov** [comment]
I am dispatching domain events after loading fixtures in `dev` environment. And I was surprised to get out of memory with  `--no-debug`. That's how I came across this issue. For now made a compiler pass.

**Comment by Tobion** [comment]
The current behavior is based on the profiler configuration not on debug as described by @xabbuh.

**Comment by vudaltsov** [comment]
Okay, thanx for explanations.

**Comment by nu111** [comment]
So the solution would be to disable the profiler?
How to do this on Symfony 5.4?
