### ISSUE TITLE
[DI][Routing] Not autowire optional parameters in actions 

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#34033]
**Symfony version(s) affected**: 4.3

When using optional Entity (default null, or can be null) parameters in Controller actions, DI builder always tries to autowire them and this behaviour cause exceptions in case when Entity constructor has arguments. 
But when arguments in the Controller actions are not optional or Entity does not have any arguments  in the constructor everything works properly. 
Note that `Entity` is excluded from the DI. 

Here is the example.
This code will throw `Cannot autowire service` exception, because `Category` has required `$title` and `$key` parameters. 

```php
class Controller {
    /**
     * @Route("", name="cms_category_index", methods={"GET"})
     * @Route("/children/{parent}", name="cms_category_children", methods={"GET"})
     *
     * @param CategoryProvider $provider
     *
     * @param Category|null    $parent
     * @return Response
     */
    public function index(CategoryProvider $provider, ?Category $parent): void
    {}
}


class Category {
    public function __construct(string $title, ?string $key){}
}

```

But, if you change code a little bit, it works properly.

```php
class Controller {
    /**
     * @Route("/children/{parent}", name="cms_category_children", methods={"GET"})
     *
     * @param CategoryProvider $provider
     *
     * @param Category|null    $parent
     * @return Response
     */
    public function index(CategoryProvider $provider, Category $parent): void
    {}
}

class Category {
    public function __construct(string $title, ?string $key){}
}
```

And it becomes strange, because `Category` itself excluded from the DI, and in my opinion it must not be autowired in any places, not only in `Controller` actions, and it does not matter optional argument or not. That's why i'm thinking  that it's a bug.

The solution can be:  
Skip the optional parameters only when they are excluded from DI.

**Comment by xabbuh** [comment]
I am not sure I understand why the second example should work. How can the `Category` object be constructed in this case if the required title is still missing? Also, what part of your application actually constructs these `Category` instances? Do you use the `ParamConverter` from the SensioFrameworkExtraBundle?

**Comment by wtorsi** [comment]
Same as me. 
In the second example, in my opinion, `Category` is not injected as a DI argument (but I don't know why) and there is no exception. But why in this case DI builder does not try to inject `Category`, and do this when argument is optional `?Category`?

And yes, by request `Entity` is constructed by `Doctrine` `ParamConverter`, it does not use `__construct` method when building entity.

**Comment by xabbuh** [comment]
Could you create a small example application that allows to reproduce and debug the issue?

**Comment by wtorsi** [comment]
Sorry, while creating test app, found where i was wrong. Close this issue.

````
# wrong
exclude: '../../src/Catalog/{Entity|Exception}'

#correct 
exclude: '../../src/Catalog/{Entity,Exception}'
````
