### ISSUE TITLE
SF4- Compile Error: Cache warmup : Segmentation fault

### ISSUE THREAD

**Issue by dvapelnik** [symfony/symfony#34047]
**Symfony version(s) affected**: 4.3.4

**Description**  
Command `cache:clear` became to fail after few iterations of development.

**How to reproduce**  
```
$ php bin/console cache:clear

 // Clearing the cache for the dev environment with debug true                                                          

Segmentation fault (core dumped)
```

**Possible Solution**  
Command fails only when xdebug is enabled.

```
$ php --ri xdebug | grep Version
Version => 2.7.2
```

**Additional context**  
Same problem was found in #26094

**Comment by nicolas-grekas** [comment]
Please report the issue to XDebug, segfaults are not solvable from PHP-side.
