### ISSUE TITLE
non-existent parameter "container.build_id"

### ISSUE THREAD

**Issue by videni** [symfony/symfony#34040]
I created an issue [overblog/GraphQLBundle](https://github.com/overblog/GraphQLBundle/issues/588), however it seems this is out of scope of that bundle. I have debugged it for several hours, did't find any clues.  cany anybody help me this please?

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce this issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
