### ISSUE TITLE
UniqueEntity constraint does not work on GUID field (related entity)

### ISSUE THREAD

**Issue by kekcius** [symfony/symfony#34068]
**Symfony version(s) affected**: 4.3

**Description**  
When using @UniqueEntity constraint on related entity's guid (char(36)) field, the uniqeness check does not work. But it works fine on integer fields.

**How to reproduce**  
Create an entity with guid PK, for example `User`. 
```/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @JMS\ExclusionPolicy("all")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     *
     * @JMS\Expose
     * @JMS\Groups({"list", "profile"})
     */
    private $id;
```

Then create another entity (say, `UserWatchlist`) related to first one (ManyToOne) and set Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity constraint:

```
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserWatchlistRepository")
 * @UniqueEntity(
 *     fields={"user", "direction"},
 *     errorPath="direction",
 *     message="User already has this direction"
 * )
 */
class UserWatchlist
```

When `user` field set as a part of unique value, it is being ignored.

I'd appreciate any feedback if I'm doing something wrong, but have no ideas.

**Possible Solution**  

**Additional context**

**Comment by dmaicher** [comment]
I cannot reproduce the issue:

https://github.com/symfony/symfony/compare/4.3...dmaicher:issue-34068?expand=1

Results in a violation:

```
There was 1 failure:

1) Symfony\Bridge\Doctrine\Tests\Validator\Constraints\UniqueEntityValidatorTest::testValidateUniquenessOnRelatedGuidIdEntity
0 violation expected. Got 1.
Failed asserting that 1 is identical to 0.
```

Can you create a small example project that shows this issue? Or adjust my test scenario?

**Comment by dmaicher** [comment]
@kekcius any feedback? :blush:

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
