### ISSUE TITLE
Symfony - How to Connecting TLS-enabled Amazon DocumentDB cluster

### ISSUE THREAD

**Issue by elangovanshanthi** [symfony/symfony#34077]
How to integrated the below [TLS enabled amazon documentDB cluster](https://docs.aws.amazon.com/documentdb/latest/developerguide/connect.html#connect-tls-enabled) in symfony. Please find the sample script and can you provide sample example or steps?

```
<?php
//Include Composer's autoloader
require 'vendor/autoload.php';

$SSL_DIR = "/home/ubuntu";
$SSL_FILE = "rds-combined-ca-bundle.pem";

//Specify the Amazon DocumentDB cert
$ctx = stream_context_create(array(
    "ssl" => array(
        "cafile" => $SSL_DIR . "/" . $SSL_FILE,
    ))
);

//Create a MongoDB client and open connection to Amazon DocumentDB
$client = new MongoDB\Client("mongodb://<dbusername>:<dbpassword>@mycluster.node.us-east-1.docdb.amazonaws.com:27017", array("ssl" => true), array("context" => $ctx));

//Specify the database and collection to be used
$col = $client->test->col;

//Insert a single document
$result = $col->insertOne( [ 'hello' => 'Amazon DocumentDB'] );

//Find the document that was previously written
$result = $col->findOne(array('hello' => 'Amazon DocumentDB'));

//Print the result to the screen
print_r($result);
?>
```
**Note :** I have ssh credentials and pem files also. It works fine for plain php in server.
Let me know your thoughts.

**Comment by javiereguiluz** [comment]
@elangovanshanthi I'm afraid that in this GitHub repository we only discuss about Symfony bugs and new features.

For support questions like this one, please use any of the support channels described here: https://symfony.com/support. Also, if you think this is indeed an error related to MongoDB client/library, this issue should be reported either to Doctrine MongoDB library (https://github.com/doctrine/mongodb-odm) or Doctrine MongoDB bundle (https://github.com/doctrine/DoctrineMongoDBBundle).

Thanks.

**Comment by elangovanshanthi** [comment]
> @elangovanshanthi I'm afraid that in this GitHub repository we only discuss about Symfony bugs and new features.
> 
> For support questions like this one, please use any of the support channels described here: https://symfony.com/support. Also, if you think this is indeed an error related to MongoDB client/library, this issue should be reported either to Doctrine MongoDB library (https://github.com/doctrine/mongodb-odm) or Doctrine MongoDB bundle (https://github.com/doctrine/DoctrineMongoDBBundle).
> 
> Thanks.

If it is mongo client issue means i will ask corresponding team, but issue is from your side. Symfony will give some steps right, to connect the mongo db connections.

**Comment by stof** [comment]
Symfony does not do anything with MongoDB. So how could it be on our side ?
