### ISSUE TITLE
[Mailer] Sending mails sync when the async transport is down

### ISSUE THREAD

**Issue by mynameisbogdan** [symfony/symfony#34071]
**Description**  
When `messenger` is configured with `'Symfony\Component\Mailer\Messenger\SendEmailMessage': async` and the messenger transport is down (in my case redis), sending an email will throw an exception, eg: `RedisException`. 

Wouldn't be nicer when the messenger transport is down to fallback to sync? Or an event dispatcher in case of exception so can an user decide to send the mail without an messenger transport? Third argument to method `send`: `bool $useBus = true` to be easier to use in a try/catch block?

```php
public function send(RawMessage $message, ?SmtpEnvelope $envelope = null, bool $useBus = true): void
{
    if ($useBus && $this->bus !== null) {
        $this->bus->dispatch(new SendEmailMessage($message, $envelope));

        return;
    }
   ...
}
```
**Example**  
Currently on 4.3 I'm decorating `mailer.mailer` with the following `send` method

```php
 public function send(RawMessage $message, ?SmtpEnvelope $envelope = null): void
    {
        try {
            if ($this->bus !== null) {
                $this->bus->dispatch(new SendEmailMessage($message, $envelope));

                return;
            }
        } catch (Throwable $exception) {
            // noop
        }

        $this->transport->send($message, $envelope);
    }
```

Maybe there is an easier way that I manage to find?

**Comment by fabpot** [comment]
That's not something that should be done at the Mailer level. You should configure the Messenger transport as you see fit (you can for instance implement a retry strategy).
