### ISSUE TITLE
symfony/routing PHP 7.4 preloading - Unknown type dependencies

### ISSUE THREAD

**Issue by EtienneBruines** [symfony/symfony#34089]
**Symfony version(s) affected**: 4.3.5

**Description**  
`
[23-Oct-2019 14:04:05 UTC] PHP Warning:  Can't preload unlinked class Symfony\Component\Routing\Loader\AnnotationClassLoader: Unknown type dependencies in /home/e.bruines00000/workspaces/mossaino/prod/vendor/symfony/routing/Loader/AnnotationClassLoader.php on line 57
`

**How to reproduce**  
Use PHP 7.4 and configure ini-setting `opcache.preload` to this script:

*./preload.php*
```php
<?php 

opcache_compile_file('vendor/symfony/config/Loader/LoaderInterface.php'); 
opcache_compile_file('vendor/symfony/routing/Loader/AnnotationClassLoader.php');
```

**How to reproduce with docker**
```bash
# Enable preloading config
mkdir config
echo "opcache.preload=`pwd`/preload.php" > config/preloading.ini
# Write the preloading-script
echo "<?php opcache_compile_file('vendor/symfony/config/Loader/LoaderInterface.php'); opcache_compile_file('vendor/symfony/routing/Loader/AnnotationClassLoader.php');" > preload.php
docker run --rm -v `pwd`:`pwd` -e NEW_UID=`id -u` -e NEW_GID=`id -g` -v `pwd`/config:/etc/php-custom.d devilbox/php-fpm:7.4-work
```

**Possible Solution**  

**Additional context**

**Comment by Nyholm** [comment]
Hey. 

I dont think this an issue with Symfony. It is an issue with how preloading works. If you want to preload `AnnotationClassLoader` you also need to preload all classes that `AnnotationClassLoader` depends on. 
Have a look at `Symfony\Component\DependencyInjection\Dumper\Preloader` in Sf4.4 That will help you. 

```php
<?php 
// preload.php
$classes[] = 'Symfony\Component\Config\Loader\LoaderInterface';
$classes[] = 'Symfony\Component\Routing\Loader\AnnotationClassLoader';

Preloader::preload($classes);
```

If you are using Symfony 4.4 you may also be interested in using this file as your `opcache.preload`.

> var/cache/prod/App_KernelProdContainer.preload.php

**Comment by EtienneBruines** [comment]
The problem however, is that even when preloading all files within the optimized composer classmap - it does not work.

The `LoaderInterface` in your snippet was also present in the original question. It therefore should not throw an error.

**Comment by Nyholm** [comment]
Correct. Preloading all files in composers classmap does not work. 

Please try with the Preloder class that I suggested.

**Comment by nicolas-grekas** [comment]
Preload warning can be ignored.
