### ISSUE TITLE
 `workflow_marked_places()` doesn't handle property `marking_store.property`

### ISSUE THREAD

**Issue by amalricBzh** [symfony/symfony#34092]
**Symfony version(s) affected**: 4.3.5

**Description**  
Calling Twig bridge `workflow_marked_places()` on a workflow using custom `marking_store.property`, with an entity which don't have `getMarking()` getter raise an error.

**How to reproduce**  
1. Create a workflow with a custom marking field

```` workflow.yaml
      supports: App\Entity\MyEntity
      marking_store:
                type: single_state
                property: status
````

2. MyEntity has status field with getter and setter:

````
    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $status;

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return MyEntity 
     */
    public function setStatus(string $status): MyEntity 
    {
        $this->status = $status;
        return $this;
    }
````
3. In Twig view, call `workflow_marked_places`

````
{% for place in workflow_marked_places(oneEntity) %}
    {{ place }}
{% endfor %}
````

**Possible Solution** 
The bridge try to call `getMarking()` on my entity instead of `getStatus()`. If I had a `getMarking()` in my entity wich give the status field it's OK. But I think I shouldn't have this getter in my entity as I don't have a `$marking` property...

````
    /**
     * @return string
     */
    public function getMarking(): string
    {
        return $this->status;
    }
````

Traces and warning below may help you...

**Additional context**  
The error and trace:
```
> Symfony\Component\PropertyAccess\Exception\ NoSuchPropertyException

Neither the property "marking" nor one of the methods "getMarking()", "marking()", "isMarking()", "hasMarking()", "__get()" exist and have public access in class "App\Entity\Tud\Transcription".
in vendor/symfony/property-access/PropertyAccessor.php (line 419)
in vendor/symfony/property-access/PropertyAccessor.php->readProperty (line 93)
in vendor/symfony/workflow/MarkingStore/SingleStateMarkingStore.php->getValue (line 46)
in vendor/symfony/workflow/Workflow.php->getMarking (line 55)
in vendor/symfony/twig-bridge/Extension/WorkflowExtension.php->getMarking (line 98)
in var/cache/dev/twig/95/95fbfe4eb42dd8e45d89142d3197a1579c76c4f042676c73aeb29a45c69fade1.php->getMarkedPlaces (line 246)
in vendor/twig/twig/src/Template.php->block_body (line 184)
in var/cache/dev/twig/69/69cea8d72335b574079f91fdfd25b1dc0c169b9258dd1ab7ffe3fde559a0c954.php->displayBlock (line 154) 
```

The Workflow component throw a deprecation warning:
 > User Deprecated: "Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore" is deprecated since Symfony 4.3, use "Symfony\Component\Workflow\MarkingStore\MethodMarkingStore" instead.

**Comment by amalricBzh** [comment]
The bug is caused by the workflow configuration : the deprecation warning is not clear (for me) and it is thrown because the configuration key `marking_store.type` in my example has another value than `method`.

Replacing 
```` workflow.yaml
marking_store:
    type: single_state
````
By
```` workflow.yaml
marking_store:
    type: method
````
makes everything fine : no more deprecation warning, no more `getMarking()`/`setMarking()` methods needed.

So I'm not sure this is a bug, but maybe the deprecation message can be more understandable ?

**Comment by lyrixx** [comment]
Hello. Indeed this is an issue with the documentation.

You have 2 options:

**The old way**:
```yaml
marking_store:
    type: single_state
    arguments: ['state']
```

**The new way**:
```yaml
marking_store:
    type: method
    property: state
```

I saw you open a [PR in the doc](https://github.com/symfony/symfony-docs/pull/12539) thanks for that :+1:

I also fixed another [bug in the doc ](https://github.com/symfony/symfony-docs/pull/12557)

And I also open [a PR](https://github.com/symfony/symfony/pull/34152
) to forbid such situation

**Comment by lyrixx** [comment]
Note: In symfony 5.0, all this confusion will be removed. You can read more about it [on the blog](https://symfony.com/blog/new-in-symfony-4-3-workflow-improvements#simpler-configuration)

**Comment by amalricBzh** [comment]
Thank you, it is my first use of this component. I wonder why I didn't use it sooner !
