### ISSUE TITLE
feature request: number form field type

### ISSUE THREAD

**Issue by nimasdj** [symfony/symfony#34106]
I want to have a spinner in my symfony form:

    <input type="number" />

It seems symfony does not have such form field type? and it seems their custom form field type is not for this job? https://symfony.com/doc/current/form/create_custom_field_type.html
How can I make it? or should I ask for a feature request?

**Comment by yceruto** [comment]
Use the `html5` and `attr` options to add any HTML attribute in your form input. For exmaple:
```php
$builder->add('price', NumberType::class, [
    'html5' => true, // <input type="number" />
    'attr' => ['min' => 0, 'step' => 5], // <input ... min="0" step="5" />
]);
```

Let's close here as it's already supported.
