### ISSUE TITLE
[Validator] Add PostalConstraint

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#34108]
**Description**  
At [Assoconnect](https://www.assoconnect.com), we have listed all the rules for postal code for a lot of countries. We are refactoring some code and we plan to make a constraint with it.

Would you accept a PR with this constraint (linked to the CountryConstraint) or should we keep it part of our business code?

The constraint would check a postal code along with a country code (like the BicValidator with the IBAN: https://symfony.com/doc/current/reference/constraints/Bic.html#ibanpropertypath)

**Comment by noniagriconomie** [comment]
Sometimes a constraint comes with a formtype, do you plan to include a type as well?
For me a constraint validator could be good, would definitly use it :)

**Comment by ro0NL** [comment]
see #32356 :)

**Comment by sylfabre** [comment]
@noniagriconomie A type is out of scope for us

@ro0NL nice one, I'll close this one then
