### ISSUE TITLE
[Security] access_control doesn't work with ip parameter

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#34118]
**Symfony version(s) affected**: 4.3.5

**Description**  
I can not set up IP access control in the security.yaml. IP control does not seem to work.

**How to reproduce**  

Example :

```yaml
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [64.105.200.100] } 
```

**Comment by Devristo** [comment]
According to https://symfony.com/doc/current/security/access_control.html#matching-access-control-by-ip it should be `ips` instead of `ip`.

**Comment by ro0NL** [comment]
we should validate for unknown fields :sweat_smile:

**Comment by xfifix** [comment]
Yes the example is false ....

**Comment by xabbuh** [comment]
`ip` should work the same as `ips`.

@xfifix Did it make difference for you if you replaced `ips` with `ip`?

**Comment by xabbuh** [comment]
Apart from that what did you expect to happen and what happened instead? How do your other access control rules look like?

**Comment by akshayachar2011** [comment]
@xfifix : The ips and ip parameter key works same way. Both can be used for adding single and multiple ips.

**Comment by xfifix** [comment]
@akshayachar2011 yes, 
@xabbuh I want the person who does not have the IP address to fall on the refusal page

**Comment by xabbuh** [comment]
Then you need to add a second access control rule that denies access for the user not coming from the configured IP address (see the explanation at https://symfony.com/doc/current/security/access_control.html#matching-access-control-by-ip):

```yaml
access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [64.105.200.100] }
    - { path: ^/api/login, roles: ROLE_NO_ACCESS }
```

I am closing here as the behaviour you observe is expected.

**Comment by xfifix** [comment]
@xabbuh 
it does not work, I always fall into denial even with the good IP.
