### ISSUE TITLE
[DotEnv] Parsing .env file with JSON value in Docker

### ISSUE THREAD

**Issue by jlekowski** [symfony/symfony#34117]
**Symfony version(s) affected**: 4.3.5

**Description**  
Setting in `.env` something like `APP_JSON='{"a":1}'` is parsed correctly by Symfony (`DotEnv`). However, when `.env` file is passed to docker to set env vars inside, `APP_JSON` becomes `'{"a":1}'` (surrounded by single quotes) and results in:
> In EnvVarProcessor.php line 183:
>                                                     
>   Invalid JSON in env var "APP_JSON": Syntax error  

Changing env var to `APP_JSON={"a":1}` (no single quotes around JSON) works inside docker, but not when parsed by Symfony (`DotEnv`) from the file directly.

**How to reproduce**  
A repo with the description https://github.com/jlekowski/symfony-docker but in general:
1. Create new Symfony app `symfony new symfony-docker`
2. Add to `.env` something like `APP_JSON='{"a":1}'` and use is somewhere, e.g. bind `$appJson: '%env(json:APP_JSON)%'`.
3. Run docker by passing `.env` file into it and run application that tries to parse this variable, .e.g. `docker run -it --rm -v "$PWD":/app --env-file=.env -w "/app" symfony-docker sh -c "bin/console debug:container --env-vars"`

**Possible Solution**  
Potentially it might be:
- bug in docker - parsing `.env` files incorrectly
- workaround/fix that would deal with env vars having values surrounded by `'` or `"`
- another workaround

**Additional context**  
See repo for this issue https://github.com/jlekowski/symfony-docker

**Comment by ro0NL** [comment]
i believe the docker .env file parser is a poor one yes, see also https://github.com/symfony/recipes/pull/487

personally i gave up on a one-size-fits-all .env file

**Comment by nicolas-grekas** [comment]
Roland is right, the issue should be reported to docker-compose instead.

**Comment by jlekowski** [comment]
If anyone else is looking, might be related to https://github.com/docker/compose/issues/2854 and https://github.com/docker/compose/pull/6923.

**Comment by kamermans** [comment]
Yes @jlekowski, I'm trying to get this fixed in docker-compose (https://github.com/docker/compose/pull/6923).

**Comment by arlauskas** [comment]
I have faced this issue with docker not with docker-compose. And seems like issue not directly with docker, but with environment. When you pass variables as environment variables, it missing from $_ENV and $_SERVER superglobals.
For example when you can see them when using command printenv.
Remove apostrophes should start to work.
APP_JSON='{"a":1}' change to APP_JSON={"a":1}

**Comment by jlekowski** [comment]
>When you pass variables as environment variables, it missing from $_ENV and $_SERVER superglobals.

@arlauskas, check your php.ini [variables_order](https://www.php.net/manual/en/ini.core.php#ini.variables-order). When switching to php:apache image I had to add `echo "variables_order=EGPCS" >> $PHP_INI_DIR/php.ini` to my Dockerfile.

**Comment by n2nco** [comment]
Removing apostrophes worked for me
e.g. changing 
`TEST_DATA='{"partition_key": "98989"}'` to
`TEST_DATA={"partition_key": "98989"}`
