### ISSUE TITLE
[RFC] Alternate structure for translation files

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#34121]
Looking at the `translations/` directory, it holds N*N files. That is each domain, for each locale:

```
domain.en.yaml
domain.nl.yaml
other.en.yaml
...
```

instead, i like to propose:

```
en/
  domain.yaml
  other.yaml
nl/
  domain.yaml
```

The directory is much less cluttered:
- we see the supported locales
- in the default locale we the supported domains
- adding a new locale is simple like `cp -R en fr`

Thoughts?

**Comment by wouterj** [comment]
Or should we have some `path_template` setting oid that allows you to configure your dir structure? I.e. `%locale%/%domain%.yaml`?

**Comment by ro0NL** [comment]
actually i think we can do it more simple, and avoid deprecation or new configs

```
en/messages.yaml
messages.en.yaml # top-level override
```

i think these 2 structures are sufficient, and allows to mix&match or stick with your structure of choice

**Comment by yceruto** [comment]
This is currently supported:
```
en/
  domain.en.yaml
  other.en.yaml
nl/
  domain.nl.yaml
```
Can this work for you?

**Comment by ro0NL** [comment]
i see, it's because of how symfony/finder works right? Could appreciate an explicit lookup for `locale/domain.yaml` though :angel: not sure it's worth it then.
