### ISSUE TITLE
Welcome page overlap issue with WDT

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#34122]
**Symfony version(s) affected**: 4.4

**Description**  
<img width="620" alt="Screen Shot 2019-10-25 at 3 54 57 PM" src="https://user-images.githubusercontent.com/121003/67600298-e0524880-f73f-11e9-9f0a-64e6e83cca46.png">

At least on my resolution, the WDT partially hides under part of the welcome page. It completely shows up if you scroll down, but it's not *quite* right.

**How to reproduce**  
Stock Symfony 5 project + profiler - with Chrome on Mac.

**Additional context**  
In case it's something specific to my setup, screen size, etc - I'm happy to provide more info.

Thanks!

**Comment by weaverryan** [comment]
Follow-up: the menus that fold-up from the WDT also cause issues:

<img width="1145" alt="Screen Shot 2019-10-25 at 4 00 19 PM" src="https://user-images.githubusercontent.com/121003/67600683-95850080-f740-11e9-9af0-728cfa0f5c7c.png">

**Comment by yceruto** [comment]
It looks like an `z-index` value problem, we should adjust that value in the WDT to make it higher. Could you please check that in your browser style inspector?

**Comment by wouterj** [comment]
I would rather think we should modify the welcome page's `z-index` values, given that those of the WDT are set to [`z-index: 99999;`](https://github.com/symfony/web-profiler-bundle/search?q=z-index&unscoped_q=z-index).

**Comment by yceruto** [comment]
That's weird, because the welcome page's `z-index` value is `1`.
https://github.com/symfony/http-kernel/search?q=z-index&unscoped_q=z-index

**Comment by wouterj** [comment]
Hmm, then we need to see if values are overridden or if the toolbar is not in the root `<body>` element (And thus inheriting it's base z-index from a parent)

**Comment by yceruto** [comment]
@weaverryan could you please check if https://github.com/symfony/symfony/pull/34124 solve the issue? Thanks!

**Comment by weaverryan** [comment]
Looks like #34124 fixed it - thank you @yceruto!
