### ISSUE TITLE
[Monolog] Add Feature to Create Log in Daily Basis

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#34132]
Sorry my english is too bad

Log file example:

```
dev-20191027.log
dev-20191028.log
dev-20191029.log
```

When using log rotate, we have limitation because the log is deleted in n basis

With this feature, we don't have missing log and it easy to read, capturing, mitigation and resolving problem

**Comment by akshayachar2011** [comment]
Hi @ad3n, Currently we have this feature in the monolog to create the log file based on the date by specifying type as rotating_file. For more info you can check this link: https://symfony.com/doc/current/logging.html#how-to-rotate-your-log-files

**Comment by ad3n** [comment]
@akshayachar2011 : thanks for mentioning, i miss that doc when searching this feature. thanks
