### ISSUE TITLE
AccessDeniedException returns 500 instead of 403 when no firewall is defined.

### ISSUE THREAD

**Issue by theredled** [symfony/symfony#34148]
**Symfony version(s) affected**: 3.4.32

**Description**  
When you throw a AccessDeniedException in a controller and no firewall is defined, a 500 error code is given instead of the expected 403.

**How to reproduce**
- make a new project (`symfony new app`)
- in a new controller/action, write `throw new AccessDeniedException();` or `throw $this->createAccessDeniedException();`
- call page
- a 500 error is raised.

**Expected**
A 403 error should be raised.

**Notes**
I know there are similar issues but they all are closed without having been fixed - for what I've seen.
(#15236 #11663 #19906 #8467 #20233)

**Comment by javiereguiluz** [comment]
If I'm right, this is considered a "feature", not a "bug". But I'd like this behavior to be reconsidered. My reasoning is:

* If you throw `AccessDeniedException`, you clearly mean "you don't have access to this" ... so 403 seems the most reasonable response.
* If your application has problems (security is not installed, firewall is not properly configured, etc.) that's "your problem" and shouldn't "leak" to end-users as a 500 HTTP error.

The only caveat is: if you throw 403 ... how can you know in `dev` environment that there's a config problem in your app? With a 500 error this is easy to spot.

**Comment by jvasseur** [comment]
> If your application has problems (security is not installed, firewall is not properly configured, etc.) that's "your problem" and shouldn't "leak" to end-users as a 500 HTTP error.

I disagree here, a problem in your application is exactly why a 500 is for.

**Comment by javiereguiluz** [comment]
@jvasseur yes ... but at the same time ... the application is working perfectly and the controller is being executed perfectly ... and you put the "you don't have access" exception perfectly ... so it may be debatable that a 403 should be returned.

**Comment by nicolas-grekas** [comment]
*Some* exception do have semantics related to HTTP codes. But any other exceptions don't have meaning. They're 500. Why would this specific exception be known by HttpKernel when it's in a foreign component? There is no reasons to me. A firewall is the bridge between both worlds. If there is no bridge, a 500 is legit.

**Comment by javiereguiluz** [comment]
Then, let's close this as "won't fix/won't change". Thanks.

**Comment by theredled** [comment]
There's still something illogical to me:
- either it's an Access Denied error and it has to be code 403.
- or, as you say, it's a problem with configuration, then it shouldn't display "Access Denied", but some explicit error message like "No Firewall defined".

Here, everything looks like a 403, except the real return code 500 that is hidden in some network toolbar. There's something wrong.

**Comment by nicolas-grekas** [comment]
Thanks to new code infrastructure, we might be able to improve this. See #49193
