### ISSUE TITLE
[Cache] Race condition on file/directory rename.

### ISSUE THREAD

**Issue by B-Galati** [symfony/symfony#34162]
**Symfony version(s) affected**: 4.3.5 (Did not test for other versions)

**Description**  
When deploying I would randomly have cache warning such as:

```cache.WARNING: Failed to save key "%5BApp%5CSignature%5CDomain%5CModel%5CRecipientId%5D%5B1%5D" of type array: rename(/opt/project/var/cache/prod/pools/tg0eD9QRf0/5db80bb43f0ba7.15501439,/opt/project/var/cache/prod/pools/tg0eD9QRf0/K/U/0sZW3brGANb0d9H37T2Q): No such file or directory```

That looks like a race condition that could be mitigated a bit like explained here -> https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#mkdir-race-condition

**How to reproduce**  
That looks to be a race condition issue that can tough to reproduce.

**Additional context**  
![image](https://user-images.githubusercontent.com/895123/67756949-358da300-fa3b-11e9-98ed-987f687d1001.png)

**Comment by linaori** [comment]
Are you deploying over a running version of your app?

**Comment by B-Galati** [comment]
@linaori Nop!

@nicolas-grekas Fair enough, would it make sense to add a `@` on the `rename` function call?

Closing the issue :-)
