### ISSUE TITLE
[HttpKernel] Possible BC break in 4.2 - log dir has changed

### ISSUE THREAD

**Issue by smoench** [symfony/symfony#34164]
**Symfony version(s) affected**: >=4.2

**Description**  
With HttpKernel 4.2 the log dir has been changed from `logs` to `log`.
In 4.1 it points to [`logs`](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/HttpKernel/Kernel.php#L377) and in 4.2 to [`log`](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/HttpKernel/Kernel.php#L396).

With flex/recipes in use the log dir method has got overridden with `log` since [3.3](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php#L25)

There might been not many people/projects affected with but IHMO there should be a discussion about if it should be reverted or "just" documented as a BC-Break.

**Comment by Tobion** [comment]
Also since 4.2 is not supported anymore changing it back in 4.4 would be kind of another bc break. So it does not seem worth it anymore.

**Comment by smoench** [comment]
It might be not worth it but there should be an upgrading guide or blog post about it. People trying upgrading a 3.4 LTS project to next LTS might fail as 3.4 proposed [`logs`](https://github.com/symfony/symfony-standard/blob/3.4/app/AppKernel.php#L48) in the standard edition.

**Comment by nicolas-grekas** [comment]
@smoench would you mind sending a PR doing so?

**Comment by smoench** [comment]
@nicolas-grekas Which branch should I target (as 4.2 is in security fixes only)?

**Comment by nicolas-grekas** [comment]
4.3

**Comment by Tobion** [comment]
Closing as there hasn't been any activity
