### ISSUE TITLE
[RFC] Enable AutoAliasServicePass compiler pass by default

### ISSUE THREAD

**Issue by X-Coder264** [symfony/symfony#34194]
Why isn't the `AutoAliasServicePass` compiler pass enabled by default?

It was added in https://github.com/symfony/symfony/pull/12526 and even there some people are asking the same question.

I needed this exact functionality and I found this compiler pass by going through all compiler passes in the dependency injection component and only later I saw the little mention about it (and how it has to be manually added to the container) in the [documentation](https://github.com/symfony/symfony-docs/blob/4.4/reference/dic_tags.rst#auto-alias) where the `auto_alias` tag was documented.

**Comment by nicolas-grekas** [comment]
I'd suggest sending a PR doing so to trigger the discussion.
