### ISSUE TITLE
Symfony 4.3 validation doesn't work - not even the automatic

### ISSUE THREAD

**Issue by fdbatista** [symfony/symfony#34193]
**Symfony version(s) affected**: 4.3.5

**Description**  
I'm trying to use Symfony 4.3 automatic validation on an entity, but it just doesn't work.

I've uncommented the auto mapping lines from validator.yaml and I have enabled validation: {enable_annotations: true} in framework.yaml config file, and it still does not work.

**How to reproduce**  
```bash
symfony new my-app
composer require ... #all the orm/validator related dependencies
```
Follow [this tutorial](https://symfony.com/doc/current/validation.html)

**Possible Solution**  
Maybe there is some extra configuration needed, which is not being explained in this tutorial.

**Additional context**

**Comment by s1k3s** [comment]
I have just tested this in a fresh installation and everything works as expected, see below.

The difference seems that I installed with `composer create-project symfony/website-skeleton` and I didn't require orm/validator dependencies since they have been installed by default.

Note that if you enable auto mapping for entities, the `@ORM` annotations will be used when validating, as explained here: https://symfony.com/blog/new-in-symfony-4-3-automatic-validation

```
// src/Entity/Test.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TestRepository")
 */
class Test
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
```
```
// /config/packages/validator.yaml
framework:
    validation:
        email_validation_mode: html5

        auto_mapping:
            App\Entity\: []

```

```
// /config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    validation: { enabled: true }
```

```
// src/Controller/IndexController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Test;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * Class IndexController
 * @package App\Controller
 */
class IndexController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(ValidatorInterface $validator)
    {
        $a = new Test();

        $violations = $validator->validate($a);

        dd($violations);

        return $this->render('index/index.html.twig', [
            'controller_name' => 'IndexController',
        ]);
    }
}
```

**And the output of ->validate($a) is:**

```
IndexController.php on line 27:
ConstraintViolationList^ {#525 ▼
  -violations: array:1 [▼
    0 => ConstraintViolation^ {#588 ▼
      -message: "This value should not be null."
      -messageTemplate: "This value should not be null."
      -parameters: array:1 [▶]
      -plural: null
      -root: Test^ {#522 ▶}
      -propertyPath: "name"
      -invalidValue: null
      -constraint: NotNull^ {#582 ▶}
      -code: "ad32d13f-c3d4-423b-909a-857b961eb720"
      -cause: null
    }
  ]
}
```

**Comment by fdbatista** [comment]
Thanks, @s1k3s . I was making a mistake by not using dependency injection.
I was instantiating the $validator object using ```Validation::createValidator()```.

This way of instantiating the validator component may be confusing for newbies.
When switched to the DI approach validations started to work.

I'm closing this issue.
Thanks for the quick response.
