### ISSUE TITLE
Symfony server wrong route matching using ajax requests

### ISSUE THREAD

**Issue by nithiz** [symfony/symfony#34206]
**Symfony version(s) affected**: 4.3 (running on php 7.3)

**Description**  
Symfony server matches the wrong routes when two requests are done at the same time. When doing the requests one by one with a 1000ms delay the correct routes get matched.

**How to reproduce**  
I'm using a RouteLoader as described in the docs to load dynamic routes for my bundle. I also have some fixed configured routes in my routing.yaml file. When using router:debug i simply see a correct list of routes. 

When i approach the routes one by one in my browser i get the correct match and correct result. When i use axios in my react interface 2 routes get loaded at the same time through ajax. I'm using the symfony server which then randomly matches either the first route or the second route for both requests while they're completely different routes (/admin/admins_list and /resource/product).

When i add a setTimeout of 1000ms in my react interface for one of the axios ajax requests the correct route gets matched.

**Additional context**  
When looking at the server logs we see a strange thing where the order of the logs is correct but the times are weird:
`Oct 31 22:29:33 |INFO | SERVER GET  (200) /admin/admins_list 
Oct 31 22:29:33 |INFO | REQUES Matched route "mint_admin_resource_product_list". method="GET" request_uri="https://127.0.0.1:8000/resource/product" route="mint_admin_resource_product_list" route_parameters={"_controller":"App\\Controller\\ProductAdminController::listAction","_route":"mint_admin_resource_product_list"}
`

`Oct 31 22:29:34 |INFO | SERVER GET  (200) /resource/product 
Oct 31 22:29:33 |INFO | REQUES Matched route "mint_admin_resource_product_list". method="GET" request_uri="http://127.0.0.1:8000/resource/product" route="mint_admin_resource_product_list" route_parameters={"_controller":"App\\Controller\\ProductAdminController::listAction","_route":"mint_admin_resource_product_list"}
`

In the second request we can see the get request coming in at 22:29:34 while the match for this route happens at 22:29:33.

I tried clearing my normal cache and opcache with no luck. I also tried clearing the cache and php folder in the ~/.symfony folder and restarting the server with no luck..

Any help would be nice :)

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by Tobion** [comment]
Also it might be more related to https://github.com/symfony/cli as you mentioned the symfony server
