### ISSUE TITLE
[Form] FormBuilder is using Doctrine Proxies instead of Entities

### ISSUE THREAD

**Issue by jacraade** [symfony/symfony#34201]
**Symfony version(s) affected**: 4.3 (4.3.5)

**Description**  
My EntityType and CollectionType were not calling set / add / remove so i added by_reference to them to force them to call it. However that causes an error:  

> Could not determine access type for property "myprop" in class "Proxies\\_\_CG\_\_\App\Entity\MyEntity": Neither the property "myprop" nor one of the methods "addMyprop()"/"removeMyprop()", "addMyprop()"/"removeMyprop()", "setMyprop()", "Myprop()", "\__set()" or "\__call()" exist and have public access in class "Proxies\\_\_CG\_\_\App\Entity\MyEntity".

**How to reproduce**  
Create a custom FormType for an entity and create the form with any entity from a EntityManager find. Something like this:

```php
class MyEntityType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('myprop', CollectionType::class, [
            'label' => false,
            'entry_type' => SomeEntityType::class,
            'entry_options' => [
                'label' => false,
            ],
            'allow_add' => true,
            'allow_delete' => true,
            'by_reference' => false, // true => add / remove wont get called, false => error
        ]);
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => MyEntity::class,
        ]);
    }
}

class SomeEntityType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('myvalue', TextType::class, [
            'label' => false,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => SomeEntity::class,
        ]);
    }
}
```

Entities are generated with make:entity and got all the get/set or get/add/remove methods it needs

**Comment by jacraade** [comment]
ok found out that it has to do with custom AbstractType nesting as the first type got the right entity in POST_SET_DATA event but all the childs then just have the Proxy class

**Comment by xabbuh** [comment]
Does it mean that we can close here and this will need to be fixed in your custom type?

**Comment by jacraade** [comment]
> Does it mean that we can close here and this will need to be fixed in your custom type?

there is nothing i can do in my custom type. my custom type has data_class set to the right entity, yet it receives the doctrine proxy instead

**Comment by xabbuh** [comment]
Could you please create a small example application that allows to reproduce your issue then?

**Comment by jacraade** [comment]
tried to reproduce the issue over the weekend but was unable to do so (always got App/Entity/Something as return and also for all childs).

today i did some more debugging and here is what i found:

it is not the formbuilders fault that i get proxies as the are already in the object that $em->getRepo...->find($id) returns (the object i fetch is an entity, but all childs are proxies. i guess thats because they are not loaded yet)

 these child proxies work fine and also call custom functions from the original entity when i use them.

however when i put them in the formbuilder the functions wont be called or error is shown that it cant find them.

here is an example of a child in that entity (that gets resolved into a proxy):

```php
    // Entity Orders
    /**
     * @var Orderrevisions (is actually Proxies\__CG__\App\Entity\Orderrevisions)
     * 
     * @Assert\Valid
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Orderrevisions", inversedBy="orders")
     * @ORM\JoinColumn(nullable=true)
     */
    private $currentRevision;

    // Entity Orderrevisions
    /**
     * @var Orders
     * 
     * @ORM\OneToOne(targetEntity="App\Entity\Orders", mappedBy="currentRevision")
     */
    private $orders;
```

so that should be fine.

no idea whats going on

**Comment by stof** [comment]
Your error messages contain `myprop` while your entity code snippet contains other property names. This makes me think that you tried to *partially* anonymize your report. But this is hurting debugging, as we have no way to figure out how your different snippets are related.

Thus, the error message complains about some access methods not being defined, but you don't show the accessors at all in your snippets.
Also, given that the names of these accessors are tied to converting from plural to singular in the names to get the name of the adder and remover accessors, I strongly suggest you to keep the original property names, as they might actually be the cause of your issue.

**Comment by stof** [comment]
Btw, this message probably does not come from the FormBuilder, but from the PropertyInfo component, which will deal with whatever object was given to it. That's probably where the Doctrine proxy comes from. But given Doctrine proxies extend the entity class, I *never* got such errors due to something specific to the proxy object. I was always caused by something belonging to the names in the entity itself (and inherited by the proxy).

**Comment by jacraade** [comment]
yea i tried to remove the names and make it generic as i have this problem on multiple places with different entities. but yes i shoulnd't have done that sorry.

HOWEVER by checking again i just saw the real issue (that i overlooked before). Its the entity naming. I imported the entites from the database and they have quite horrible names (tables are in plural) and the childs also are in plural even if its just one. the formbuilder then tries to call the singular add

for example:

```php
    /**
     * @var Collection|Orderrequestequipmenttypes[]
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\Orderrequestequipmenttypes", mappedBy="orderrequests", orphanRemoval=true, cascade={"persist"})
     */
    private $orderrequestequipmenttypes;


    /**
     * @return Collection|Orderrequestequipmenttypes[]
     */
    public function getOrderrequestequipmenttypes(): ?Collection
    {
        return $this->orderrequestequipmenttypes;
    }

    public function addOrderrequestequipmenttypes(Orderrequestequipmenttypes $orderrequestequipmenttypes): self
    {
        ...
    }

    public function removeOrderrequestequipmenttypes(Orderrequestequipmenttypes $orderrequestequipmenttypes): self
    {
        ...
    }
```

and in the formbuilder 

```php
    $builder->add('orderrequestequipmenttypes', CollectionType::class, [
            'label' => false,
            'entry_type' => OrderrequestequipmenttypesType::class,
            'entry_options' => [
                'label' => false,
                'new' => $new,
            ],
            'allow_add' => true,
            'allow_delete' => true,
            'by_reference' => false,
        ]);
```

and the formbuilder then says:

> Could not determine access type for property "orderrequestequipmenttypes" in class "App\Entity\Orderrequests": Neither the property "orderrequestequipmenttypes" nor one of the methods "addOrderrequestequipmenttyp()"/"removeOrderrequestequipmenttyp()", "addOrderrequestequipmenttype()"/"removeOrderrequestequipmenttype()", "setOrderrequestequipmenttypes()", "orderrequestequipmenttypes()", "__set()" or "__call()" exist and have public access in class "App\Entity\Orderrequests".

its missing the singular get/add/remove methods since the classes are plural and fucks up the auto naming.

i dont think this counts as a bug in symfony and i'm going to close this issue.

Thanks for your help
