### ISSUE TITLE
bc break: Responses are marked private because of UsageTrackingTokenStorage 

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony#34220]
**Symfony version(s) affected**: 4.4-dev

**Description**  

Because of PR #33663, responses are now marked private when they weren't before.
`getToken()` is called in `Symfony\Component\Security\Http\Firewall\AccessListener` if a firewall is defined. Calling this method increases the usage counter, then `AbstractSessionListener` detects that the session has been used (it's not the case in 4.3) and mark the response a private (but shouldn't).

**How to reproduce**  

This breaks the API Platform test suite. To reproduce:

    git clone https://github.com/api-platform/core
    cd core
    jq '. + {"minimum-stability": "dev"}' composer.json | sponge composer.json
    composer install
    rm -Rf tests/Fixtures/app/var/cache/* && php -dmemory_limit=-1 ./vendor/bin/behat features/http_cache/headers.feature

**Comment by teohhanhui** [comment]
Is there a reason why we're not marking our `default` firewall (in the test app) as `stateless`? Or is it not related to this issue?

**Comment by dunglas** [comment]
Making the API Platform test firewall stateless fixes our test suite. However this can be a big issue for people (using API Platform or not) upgrading to 4.4 and having no cache anymore.

**Comment by teohhanhui** [comment]
I'm not sure about that. If a firewall is not stateless, the user should assume that it'll use the session.

**Comment by dunglas** [comment]
You have explicitly marked a response has public (as done by the API Platform listener), you upgrade to 4.4, your Varnish servers don't do anything anymore. It looks like a big issue to me.

**Comment by teohhanhui** [comment]
> You have explicitly marked a response as public

This wouldn't be the first time then: https://github.com/symfony/symfony/issues/25448 :see_no_evil:

**Comment by nicolas-grekas** [comment]
We love doing BC breaks Han as you know, thanks for highlight it...

Here, I'm not sure there is any bug in fact. If the session is used, the response cannot be public. I don't know why it was before actually. But setting an response public is not enough: using the session has higher priority regarding setting the response private. There's a mechanism to take over to still force things to be public, but it's only for advanced needs.

No bug until proven there's one to me here.

**Comment by teohhanhui** [comment]
> using the session has higher priority regarding setting the response private

Because the app developer cannot be trusted to have full control over their app? The same argument as #25448, the message seems to be that Symfony knows better... :x

**Comment by nicolas-grekas** [comment]
I'm closing as explained: "No bug until proven there's one to me here."

We discussed on Slack with @teohhanhui and shared this idea that the moment where the session starts you be logged / displayed somehow in the inspector. - If anyone thinks the idea is worth purpusing, please open a PR and/or an issue.

**Comment by teohhanhui** [comment]
Safe by default! :rocket:

**Comment by mpdude** [comment]
I'm probably a bit late to the party here, but I must say that this "privacy protection" and the `NO_AUTO_CACHE_CONTROL_HEADER` have bitten me more than one time – and every time it's that rather by chance I find it to be the cause when investigating performance issues related to non-caching.

Also, it's not very intuitive: When you have a really simple and explicit controller like

```php
namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @Cache(smaxage=3600)
     */
    public function indexAction()
    {
        return new Response('test');
    }
}
```

... it gives you `Cache-Control` headers that don't match what you're expecting, without further explanations.

So, I am probably missing something here... but what about `Vary: Cookie`? Wouldn't that serve the same purpose, with the additional benefit that `Cache-Control: public` would remain as-is and work for all requests unless there's actually a cookie (= session) involved?

Or, the other way round: If I have a `stateless` firewall (say, for example, with some API token?), and by mistake create `public` responses that in fact rely on the user's personal data. Will the `AbstractSessionListener` thing even save the day?

**Comment by nicolas-grekas** [comment]
Safe by default. The other choice is to accept privacy leaks by default, that wouldn't be reasonable.

We added the `@stateless` annotation in 5.1 to improve the DX around this behavior, which in itself is compliant with the semantics of the http rfc.
