### ISSUE TITLE
Add ability to deactivate Web Debug Toolbar for a request

### ISSUE THREAD

**Issue by jhony1104** [symfony/symfony#34253]
**Description**  
I'd like to disable the Web Debug Toolbar for specific requests in the controller.

**Example**  
An idea, on how to do this, would be setting a header.
```php
$response->headers->set('Symfony-Debug-Toolbar-Disable', 1);
```
and nor injecting the toolbar if the header is set.

A possible place to check, if the header is set is [WebProfilerBundle/EventListener/WebDebugToolbarListener.php:101](https://github.com/symfony/symfony/blob/ba1ba971d67a982223a794f7f780d3cd975a0485/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L101).

**Comment by stof** [comment]
Do you want to disable just the toolbar but still collecting the profile (to be able to search for it in the profiler) ? Or do you want to disable the profiling entirely ?

The second thing is already possible by calling the `->disable()` method on the `profiler` service.

**Comment by jhony1104** [comment]
Only disable the toolbar

**Comment by derrabus** [comment]
IIRC the toolbar ist already disabled if Symfony detected an AJAX call. Shouldn't be too hard too hook into this. 🤔

**Comment by fabpot** [comment]
The linked PR gives some ways to achieve that.

**Comment by jkobus** [comment]
Just a quick update, for anyone else wondering what happened to this feature - it was not accepted. Right now I'm creating a tool to render an iframe in dev mode and had to struggle with duplicating toolbars and had no way of disabling them.

I did a quick hack, so maybe this will save someone time:

`services_dev.yaml`
```
services:
  Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener:
    alias: web_profiler.debug_toolbar
```

In controller, before sending the request back:

```
    public function __construct(
        private WebDebugToolbarListener $webDebugToolbarListener,
    ) {
    }

    private function __invoke(): Response
    {
        $this->webDebugToolbarListener->setMode(WebDebugToolbarListener::DISABLED);
        ...
    }
```

Remember, that this works for me as the tool is intended for dev env only. In prod, there is no `WebDebugToolbarListener` class.

**Comment by RobQuistNL** [comment]
Another small FYI; you might also want to look into using things like [StreamedResponse](https://symfony.com/doc/current/components/http_foundation.html#streaming-a-response) [[Sourcecode](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/HttpFoundation/StreamedResponse.php)] or [JsonResponse](https://symfony.com/doc/current/components/http_foundation.html#creating-a-json-response) [[Sourcecode](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/HttpFoundation/JsonResponse.php)].

These also prevent the debug bar from "spawning". This might ofcourse not be what you're looking for if you want to render a normal page, but then again, the streaming response was the solution for me, so just posting for posterity :)

**Comment by janklan** [comment]
To add some fuel to this, here is my take that's not driven by code in the controller, but a header in the request. It seems to be working OK:

```yaml
# services.yaml
when@dev:
    services:
        Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener: '@web_profiler.debug_toolbar'
```

```php
<?php declare(strict_types=1);

// src/Listener/DisableWebDebugToolbarListener.php

namespace App\Core\Listener;

use Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Validator\Constraints\When;

#[When('dev')]
#[AsEventListener(KernelEvents::REQUEST)]
readonly class DisableWebDebugToolbarListener
{
    public function __construct(private WebDebugToolbarListener $webDebugToolbarListener) {}

    public function __invoke(RequestEvent $event): void
    {
        if ('disabled' === $event->getRequest()->headers->get('Symfony-Debug-Toolbar')) {
            $this->webDebugToolbarListener->setMode(WebDebugToolbarListener::DISABLED);
        }
    }
}
