### ISSUE TITLE
Dumps in commands don't display their location

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#34256]
**Symfony version(s) affected**: 4.4

**Description**  
In #31446 we added a feature to show the file path and line number where the `dump()` or `dd()` call was made inside a command. However, I cannot make it work.

**How to reproduce**  
```bash
# create a 4.4 project
$ symfony new test_dumper --full --version=4.4.x-dev

# create a command
$ php bin/console make:command app:test-dumper

# edit the command file and add dd() or dump() somewhere

# run the command
$ php bin/console app:test-dumper
```

This is what I see:

![image](https://user-images.githubusercontent.com/73419/68298915-d7943780-009a-11ea-8ca4-a04a5af2d29d.png)

The output is the same as in the previous Symfony versions, so this feature is not working as expected.

**Comment by nicolas-grekas** [comment]
what happens when you hover the `^`?
and when you ctrl+click it?

**Comment by javiereguiluz** [comment]
When I hover it, I don't see anything. When I `Command + C` I go to the right file+line. So, this feature is almost working ... the output knows the file+line, but it's not displayed.

I'm using macOS and iTerm2.

**Comment by nicolas-grekas** [comment]
OK, so, it works: outputting the file+line info would be way too verbose when dumping in loops. This is the compromise we settled on. On other terms, the target of the link is displayed on hover.

**Comment by javiereguiluz** [comment]
Could we reconsider this? The discoverability of this feature is not great :(  I'd have never clicked in the `^` without you telling me about it.

**Comment by dkarlovi** [comment]
Agree with @javiereguiluz, this would never occur to me to check, it's almost invisible.

If you're optimizing for the loop, maybe add the file/line only the first time it's dumped in that loop? Like Chrome dev tools adds a number next to the last `console.log` if the new line is identical to the last one?

**Comment by nicolas-grekas** [comment]
I think the compromise is sound. Your terminal should do a better job at hinting about links. It's like asking a browser to display the URL of links next to the content of the `<a>` tag.

+ using dump() in a loop with file+line info would totally destroy DX. Give it a try.

**Comment by javiereguiluz** [comment]
I asked about this in Slack and some people told that their consoles don't even allow to click on them, so they can see the `^` but they can't click on it.

Just asking: in my experience *"dumping in a loop"* is a much less common scenario than doing some dumps here and there. Could we change this to display the file+line even if it's a bit verbose for loops?

**Comment by nicolas-grekas** [comment]
> maybe add the file/line only the first time it's dumped in that loop

I don't know how this could be achieved as dumps are currently independent from each other.
PR welcome.

**Comment by nicolas-grekas** [comment]
> Could we change this to display the file+line even if it's a bit verbose for loops?

I'd better revert this feature than cripple the debugging output sorry.

**Comment by dkarlovi** [comment]
> Your terminal should do a better job at hinting about links

Meanwhile in Symfony Slack by @linaori:
> Didn't know you could do these kind of interactive clicks in the commandline 

> It's like asking a browser to display the URL of links next to the content of the <a> tag

You actually **do** that when the context changes to something where users don't naturally expect to use their mouse to hover stuff, like printing the page, for example.

**Comment by javiereguiluz** [comment]
In case we want to reconsider this, I made a quick test of outputing this information in a loop, both with a small dumped content (the worst case scenario) and with the dump of a huge variable (the best case scenario):

![image](https://user-images.githubusercontent.com/73419/68305140-6f981e00-00a7-11ea-8bb6-0abb52789cd9.png)

**Comment by romaricdrigon** [comment]
It is not supra obvious, but I guess it won't used by a lot of Users, so I would say it is fait if it says a more "power user" feature.
Just a small note, I would change `^` to `#`, as it is the character usually used for links or anchors. For example, on Github, when you over a title. So I guess most users would be familiar with it.

**Comment by linaori** [comment]
I rather have a bit more verbose output with the files/lines always showing to be honest. We're debugging, not holding a beauty contest. I want useful information :smile: 

> Just a small note, I would change `^` to `#`, as it is the character usually used for links or anchors. For example, on Github, when you over a title. So I guess most users would be familiar with it

The `#` is already used (see screenshot above), so it will not improve anything.

**Comment by nicolas-grekas** [comment]
Here is another example where dumps contain links, see the `^`:

![image](https://user-images.githubusercontent.com/243674/68305727-74110680-00a8-11ea-9f09-03b8694df983.png)

Note also that `#` is already used to display object references.

> I rather have a bit more verbose output with the files/lines always showing to be honest. We're debugging, not holding a beauty contest. I want useful information smile

Sorry, but I would strongly object here. I'm using dump in tight loops quite often and I certainly want to be able to focus on the useful info on screen rather than having to parse secondary if not lesser info.

**Comment by romaricdrigon** [comment]
Maybe we could keep it collapsed by default, so it is unobtrusive, and allow to "expand" inks by setting an env var?

**Comment by nicolas-grekas** [comment]
> Maybe we could keep it collapsed by default, so it is unobtrusive, and allow to "expand" inks by setting an env var?

teaching + learning an env var is way harder that discovering the link...

**Comment by dkarlovi** [comment]
> I don't know how this could be achieved as dumps are currently independent from each other.

1. if the previous file and line is identical to current, suppress, otherwise print
2. store current file and line

So, if in a loop, you'd only get the first file and line. If not, you'd get it for each debug, but only once.

**Comment by nicolas-grekas** [comment]
Closing as explained, thanks for asking.

(@dkarlovi "store current file and line" - that's the mysterious part if we want it to be clean - "if in a loop, you'd only get the first file and line" - what if I dump a few times in the loop? - that's why I wrote "I don't know how this could be achieved" - but if you want to have a better look, please do of course!)

**Comment by ktherage** [comment]
Well, I've been mentionned on #34494, may I help someone (TLDR :sweat_smile:).
