### ISSUE TITLE
Twig compile all files, even thoses which are not template

### ISSUE THREAD

**Issue by remmel** [symfony/symfony#34273]
**Symfony version affected**: 4.3.6

**Description**  
The TwigBundle index all the files of configured folders, even thoses which are not twig templates. 
The 1st response will be to indicate that only **.twig** files should be live in that folder. But in the reality of our project or Symfony framework, this is not the case, as we can see it in `Symfony/vendor/symfony/web-profiler-bundle/Resources/views/Icon/menu.svg`
The problem, is that it takes time to generate useless file and load useless class in memory. In some project, we can find in thoses folder 

**How to reproduce**  
- run the command `bin/console cache:clear`
- search for example for `echo "<svg` in `var/cache/dev/twig` folder
- you will find the generated class

**Possible Solution**  
Add the filter `->name('*.twig')`
```
foreach (Finder::create()->files()->name('*.twig')->followLinks()->in($dir)->exclude($excludeDirs) as $file) {
```
of [TemplateIterator::findTemplatesInDirectory](https://github.com/symfony/twig-bundle/blob/master/TemplateIterator.php#L84)

**Comment by yceruto** [comment]
Hi @remmel, you're right it's not the ideal behavior, and I agree we should do something about it.

Please follow this thread https://github.com/symfony/symfony/issues/34142 where we are analyzing the best way to achieve it.

Let's close this as a duplicate, thank you!

**Comment by stof** [comment]
These svg files in web-profiler-bundle are actually treated as Twig templates (with no Twig syntax in them): we include them in the right place as template includes. And so warming the cache for them is actually right.
