### ISSUE TITLE
[Workflow] Change order of dispatch() call

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34279]
**Description**  
In the component, we dispatch many events

https://github.com/symfony/symfony/blob/ba07cda3580a0e74e52eec7b2a57cff358520405/src/Symfony/Component/Workflow/Workflow.php#L324-L326

But I think the order is not really convenient.

In my application, I have two kind of listeners

* specific listeners (listen for example: `workflow.reservation.transition.confirm`)
* global listeners (listen for example: `workflow.reservation.transition`)

In global listeners, I may need values set by a specific listener, but since events are dispatched from most generic to most specific I can not achieve that.

To say that in another form:

> I need my specific listeners to be executed first, then global listeners

I did not do a PR, because I want to gather feedback first:

* Does it make sens to you?
* Is it a BC break? (I tend to say yes :grimacing:)

**Example**  
So in when to reverse theses linked lines to:

```php
$this->dispatcher->dispatch($event, sprintf('workflow.%s.transition.%s', $this->name, $transition->getName()));
$this->dispatcher->dispatch($event, sprintf('workflow.%s.transition', $this->name));
$this->dispatcher->dispatch($event, WorkflowEvents::TRANSITION);        
```

**Alternative**

If someone has the same issue, an alternative exist:

Do not use specific listener, listen for global events. Then in your listener, filter the event:

<details>
```php
class ConfirmationSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            // This subscriber should be run before others
            'workflow.reservation.transition' => ['confirm', 10],
        ];
    }

    public function __construct()
    {
    }

    public function confirm(TransitionEvent $event)
    {
        if ('confirm' !== $event->getTransition()->getName()) {
            return;
        }

        // your logic here
    }
}
```
</details>

**Comment by lyrixx** [comment]
OK this is not that simple.

Let's say I want to

1. have a global listener that add to the context
    * the client IP
    * the current user
    * the current date
1. have a specific listener with many business logic
1. have a global listener that record in another table the audit log 
1. have a global listener that convert the new marking to an old 'manual' implementation of a workflow (:joy: - not mine)

So here, I want some global listener before **and** after the specific ones.

The best solution IMHO is to mix all listeners, and execute them by priority. 
But the [Symfony Event Dispatcher (component)](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/EventDispatcher/EventDispatcherInterface.php) does not expose such information. 

However I think I can make it thanks to `getListeners()` and `getListenerPriority()`

But the [Workflow](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Workflow/Workflow.php#L28) expects an [EventDispatcherInterface (contracts)](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Contracts/EventDispatcher/EventDispatcherInterface.php#L41-L56) and this one does not expose this information

**Comment by stof** [comment]
IMO, the solution would be to dispatch only one event, and have listeners filtering things based on the info in the event object (which is what all other components do) or to have a workflow-specific EventDispatcher instance rather than using the global event dispatcher (as done by the form component where each Form object will have their own listeners) depending on the use case (I cannot tell what makes more sense for the workflow component, as I'm not using the component).

Such dynamic event names are really weird to me.

**Comment by lyrixx** [comment]
> Such dynamic event names are really weird to me.

Indeed. I was in the [very first](https://github.com/symfony/workflow/commit/2348da7f80fdaf22b9f268370b6dcfad861fc254#diff-14cbafb4275fcb1f9ee0077696a32de5R169) version of the component, and I never challenged this part.

Having only one event per type is not perfect, since listener will be called each team and so they will be instantiated :grimacing: (I have the same issue with APIP listener)

**Comment by noniagriconomie** [comment]
For me the actual implementation is the right one, from global to unitary workflow even
Changing it to reverse order seems not « logic »

For me userland specific postworkflow logic must be applied with userland events, not workflow components one

**Comment by lyrixx** [comment]
Let's close this one, I agree with  @noniagriconomie
