### ISSUE TITLE
[HttpClient] - Cannot catch TransportException error

### ISSUE THREAD

**Issue by arvilmena** [symfony/symfony#34281]
**Symfony version(s) affected**: 

symfony/http-client                v4.3.4

**Description**  

I am having trouble catching `Symfony\Component\HttpClient\Exception\TransportException` when doing a GET request on servers without SSL installed.

**How to reproduce**  

Trying to catch, `\Symfony\Component\HttpClient\Exception\TransportException` nor `\Exception` nor `\Throwable` doesn't seem to help.

	$client = HttpClient::create();

	try {
		$response = $client->request( 'GET', 'https://xxxx.xxxx' );
	} catch ( \Symfony\Component\HttpClient\Exception\TransportException | \Exception | \Throwable $exception ) {
		die( $exception->getMessage() );
	}

Still throws `Fatal error`: https://pastebin.com/raw/edfnSeu5

**PS**

In case it might help, I have the following packages too:

`composer show` https://pastebin.com/raw/mXJSxqQj
`composer.json` https://pastebin.com/raw/05PbqDZS

Hope somebody can help.

**Comment by nicolas-grekas** [comment]
As stated in the doc, responses are lazy: https://symfony.com/doc/current/components/http_client.html

The exception happens after the call to request(), at destruction time - ie outside of the try/catch.
Call any methods on $response (exception getInfo()) - that will make the client wait for the network, thus throw.

**Comment by arvilmena** [comment]
Ahhh, feels weird, but got it now. Thanks!

**Comment by stof** [comment]
Well, the goal of lazyness is that you can start multiple requests, and waits only after that. This way, the network can run them in parallel.

**Comment by er1z** [comment]
Do you think that is there a room for documentation improvement? How do you recommend to catch-up the exceptions within lazy approach?

So far, I'm using:
```
try{
  $response = $httpClient->request(…);
  $response->getStatusCode();
  return $response;
}catch(…){
  //
}
```

**Comment by nicolas-grekas** [comment]
Not this way @er1z - that disables a safety measure that requires ppl to write correct error handling code.

**Comment by er1z** [comment]
@nicolas-grekas so what is a better way?

**Comment by nicolas-grekas** [comment]
It depends on the use case: if one doesn't care about the response, there is no need to create a variable for it.
And if one cares, the error should be dealt with at the location where the response status (or the headers, or the body) is read and used.

**Comment by zahitrios** [comment]
I had the same error in Symfony5, and I **solved** adding `use Exception;` in the first lines of my class (In my case I was building a Service)
