### ISSUE TITLE
[Console] Ease creation of single command application

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34293]
**Description**  

I write lot's of "simple" Symfony CLI Application.

I already submitted many PRs to be able to use the following boilerplate code:
```php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

(new Application())
    ->register('processbar')
        ->setCode(function(InputInterface $input, OutputInterface $output) {
            $output->writeln('hello');
        })
    ->getApplication()
    ->setDefaultCommand('processbar', true)
    ->run()
;
```

Even if this is already straightforward, I think we can do better.
What do you think of the following code instead:

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

(new SingleApplicationCommand())
    ->setCode(function(InputInterface $input, OutputInterface $output) {
        $output->writeln('hello');
    })
;
```

**Comment by jkufner** [comment]
Passing anonymous function like that tends to make code messy. I would prefer the use of a class. Something like this:

    class AppCommand extends Command {
        // ... command as usual
    }
    (new SingleApplicationCommand(new AppCommand()))->run();

This way, it would be easier to reuse commands later, when the app gets bigger. This also allows to easily move command into a separate executable. And also, it uses already known and well-established interface to configure the commands.

**Comment by lyrixx** [comment]
@jkufner the point here is to make only one command and so with the less boilerplate code. And we could leverage the existing infrastructure, it's better. This is why I think "anonymous function like that tends to make code messy" is not relevant here.

**Comment by jkufner** [comment]
@lyrixx How simple and readable that minimalistic boilerplate code gets when the command needs a few options and a nice help? How can DI container inject few dependencies?

The anonymous function is fine for the most trivial case, but it does not scale well to handle nontrivial cases. I think that the one extra line the class declaration requires is worth the scalability.

**Comment by lyrixx** [comment]
> How simple and readable that minimalistic boilerplate code gets when the command needs a few options and a nice help

Like before:

```
(new SingleApplicationCommand())
    ->setHelp()
    ->addOption(...)
    ->setCode(function(InputInterface $input, OutputInterface $output) {
        $output->writeln('hello');
    })
;
```

> How can DI container inject few dependencies?

Usually, single command does not use a DIC, because it's not really useful here. 

But anyway, if you want, you can inject your dependencies like following

A] see the `use` (I tested it an approoved it) 

```
(new SingleApplicationCommand())
    ->setHelp()
    ->addOption(...)
    ->setCode(function(InputInterface $input, OutputInterface $output) use ($a, $b) {
        $output->writeln('hello');
    })
;
```

B] Another idea (I did not tested it)
```
(new class extends SingleApplicationCommand() {
    private $a;
    public function __construct($a) {
        $this->a = $a;
        parent::__construct();
    )

    public function execute(InputInterface $input, OutputInterface $output) {
        $output->writeln('hello');
    }
})
    
;
```

**Comment by derrabus** [comment]
The whole discussion around closures is beside the point. With a regular command, you have the choice to either use `setCode()` with a closure or to create a subclass of `Command` and override `execute()`. A potential `SingleApplicationCommand` could be built the same way.
