### ISSUE TITLE
[Form][DX][RFC] Shortcut to define global form options

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#34315]
Hello,

Here's a small RFC before working on a PR.

**Motivation**

Recently, I've been working a lot on forms. I found it pretty repetitive to have to reconfigure some option on every Form Type I was using, for instance:

```php
    ->add('type', ChoiceType::class, [
        'attr' => [
            'class' => 'custom-select',
        ],
    ])
    ->add('canDo', CheckboxType::class, [
        'label_attr' => [
            'class' => 'switch-custom',
        ],
    ])
    ->add('createAt', DateType::class, [
        'widget' => 'single_text', // To get HTML5 picker
    ])
    ->add('name', TextType::class, [
        'translation_domain' => 'my_domain',
    ])
```

I found it pretty repetitive to have to type those options every time, and it makes harder to reach consistency: it is easy to forget such option, and then the page may look/behave differently.
I think those option should be enforced globally. 

At the moment, Symfony has [FormExtensions](https://symfony.com/doc/current/form/create_form_type_extension.html), which allow to do exactly that. The process is heavy though ; setting those 4 very small options requires at least one class, reading some advanced documentation, etc. I think we need an easier and faster way to set defaults, as [it was requested in the past](https://github.com/symfony/symfony/issues/10505).

*Note: those options from my example could be set in form_theme ; I don't consider it a good option, though, as I imagine my point could also apply to options you can't change in form_theme, I just don't have a good example at hand.*

**Proposal**  

1) As we want to make configuration easier, I would go for some YAML configuration. So no code required. The idea is to allow to set some options very quickly, any advanced use case should fall back to Form Extensions. So supporting only scalar & no conditional options is fine.
Options would be collected and set as defaults on their respective types, so they can easily be overridden locally by user.

Such configuration would look like this:
```yaml
framework: # <- since Form component integration is provided by framework bundle 
    form:
        default_options:
            Symfony\Component\Form\Extension\Core\Type\ChoiceType:
                attr:
                    class: ["custom-select"]
```

*Bonus: such configuration could easily be provided by a Flex recipe, so later we can leverage that to even enhance DX*

2) Implementation-wise, I wonder what would be the correct entry point for that. I would have gone for a `DefaultOptionsFormExtension`, but maybe there's a more optimized way to do this, since implementation will be internal?

**Comment by vudaltsov** [comment]
The problem with the global defaults is that they are global. Imagine you install a 3rd party library (like EasyAdminBundle) which relies on different defaults than yours. It's gonna break 8 times out of 10. 

The extension approach also suffers from this, by the way. But I guess extensions are not for changing defaults, but for adding completely new functionality to existing types. 

So I would recommend to add new custom types in your project. They would extend from the built-in ones and override options based on your needs. It's a little bit more of work, but based on my own experience with forms I think it's safer and more reliable. As a bonus you will be always ready to change other methods like `buildForm`, `buildView`, `finishView` etc.

**Comment by romaricdrigon** [comment]
Thats very good points, and actually it makes me realize that FormExtensions are even more broken (DX-wise) than what I thought. Adding another layer on top of those won't help.
So safe solution for those scenarios is to use the form theme. I'm closing this RFC.
