### ISSUE TITLE
Message ID header malformed

### ISSUE THREAD

**Issue by TomasSjosten** [symfony/symfony#34324]
**Symfony version(s) affected**: 4.3.5

**Description**  
When sending email with symfony/mailer, API as transport, and adding header id by:

```
function generateMessageId(Headers $headers): string
    {
        if ($headers->has('Sender')) {
            $sender = $headers->get('Sender')->getAddress();
        } elseif ($headers->has('From')) {
            $sender = $headers->get('From')->getAddresses()[0];
        } else {
            throw new LogicException('Sender and From required');
        }
        return bin2hex(random_bytes(16)).strstr($sender->getAddress(), '@');
    }
...
$headers->addIdHeader('Message-ID', $id);
```
I end up with a message id in Mailgun that looks like this:

`"message-id": "Message-ID: <ff54379f02c55b9dec34e967e227c3e6@...`

**Possible Solution**  
Remove "Message-ID: <" from `"Message-ID: <ff54379f02c55b9dec34e967e227c3e6@...`.

**Comment by fabpot** [comment]
Which transport are you using? SMTP, HTTP or API?

**Comment by TomasSjosten** [comment]
Using API as transport

**Comment by TomasSjosten** [comment]
> Which transport are you using? SMTP, HTTP or API?

@fabpot I'm using API as transport

**Comment by chungryan** [comment]
Just bumped into this myself and is due to the whole header line, name included, being passed as a value to the API in src/Symfony/Component/Mailer/Bridge/Mailgun/Http/Api/MailgunTransport.php:107:
`$payload['h:'.$name] = $header->toString();`

Passing the body only will fix it:
`$payload['h:'.$name] = $header->getBodyAsString();`

**Comment by chungryan** [comment]
@TomasSjosten I'd suggest you to go back to good old SMTP in the mean time. It should be working without changing any of your code.

**Comment by fabpot** [comment]
@chungryan Would you like to send a PR?

**Comment by chungryan** [comment]
@fabpot sure thing

**Comment by fabpot** [comment]
Closing as this has been fixed now.
