### ISSUE TITLE
[Translator component] Add possibility to check if locale for translation exists

### ISSUE THREAD

**Issue by Randriamitsiry** [symfony/symfony#34325]
**Description**  
For some case, user does not want to use the behaviour that when translation for the given locale does not exists, use the default.

Because, it does not make sens to have French content instead of Arabian for example

**Example**  

```
    public function isLocaleExist(string $locale)
    {
        //If locale exists return true, else return false
    }
```

Then, if user does not want to use the default behaviour, he can use this function then react depending of the result like: 

   
 ```
  public function useFunction(string $locale)
    {
        if ($this->translator->isLocaleExist($locale)) {
            //do setLocale or process to translation
        } else {
            //throw exception or fallback to another locale than the default 
        }
    }
```

**Comment by derrabus** [comment]
I don't think that this is a good idea. You would create a codebase full of `if`/`else` blocks constructed around translator calls. Code that calls the translator should not bother how the translation is produced.

Can you elaborate on your use-case a bit more?

**Comment by ghost** [comment]
I have one use case for this: I would like to assert in my tests that each supported language (which are in a list defined by me) has a corresponding, non-fallback message file. I suppose I could check for `messages.*.yaml` file existence in the project, but that doesn't feel like a clean solution.
