### ISSUE TITLE
[Twig/Forms] not possible to set title for button without text

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#34330]
**Symfony version(s) affected**: every ?

**Description**  
- I'm creating form button, that has only icon ... It's not possible to define title for button, that has no text

**How to reproduce**  
````
$builder->add('reset', ResetType::class, [
	'label' => false,
	'attr' => [
		'title' => 'word.reset_filter'
	]
]);
````

**My Solution**  
override block *button_widget*
````
{% block button_widget -%}
    {% set original_translation_domain = translation_domain %}
    ....
{%- endblock button_widget %}
````

override block *button_attributes*
````
{%- block button_attributes -%}
    {% set translation_domain = original_translation_domain %}
    id="{{ id }}" name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif -%}
    {{ block('attributes') }}
{%- endblock button_attributes -%}
````

**Comment by xabbuh** [comment]
Which form theme do you use?

**Comment by poolerMF** [comment]
I was using bootstrap_4_layout
I tried it on SF 4.2.10

**Comment by stephen-lewis** [comment]
I've had a go at reproducing this, but I can't seem to do so. By setting label to false and setting attr['title'] as you have, the title comes through fine for me. This is on 4.3.8, mind you, the latest stable version. Bootstrap 4 form styling all configured.

My reproduction attempt is at [https://github.com/stephen-lewis/symfony_bug_34330_reproducer](https://github.com/stephen-lewis/symfony_bug_34330_reproducer), and as you can see by the screenshot below, the title attribute is there (a tooltip also displays, but I couldn't capture that!).

Perhaps there is something else going wrong... I'd start by upgrading to 4.3.x. Then, if the issue persists, can you give some more detail so we can reproduce it?

![image](https://user-images.githubusercontent.com/4210939/69015423-913cb380-098b-11ea-9a98-976ef432d804.png)

**Comment by poolerMF** [comment]
I'm sorry, my fault - bad description and title

it's not possible to translate title for button without text
it's bug about translations (that's why I was in my solution remembering old translation_domain)

**Comment by stephen-lewis** [comment]
No worries, your workaround makes more sense now! I've [reproduced it](https://github.com/stephen-lewis/symfony_bug_34330_reproducer) in latest; can confirm issue: 
'title' attribute is not translated when label is null. Issue persists without bootstrap or bootstrap form theme.

**Comment by stephen-lewis** [comment]
button_widget explicitly sets translation_domain to false if label==false. translation_domain is then checked for false to avoid breaking the translator if it tries to translate a non-string. I've created a pull request that changes this logic to check both the label and the translation_domain for false prior to translating, and then removed the explicit setting of translation_domain to false. I've tested it and there don't seem to be any side effects.

**Comment by TomaszGasior** [comment]
@poolerMF Creating button without text should not be possible. You SHOULD never ever create button without text and only with icon. Button without text inside is not accessible for screen readers, which means that blind people won't be able to use that button (title attr is not solution here).

It does not mean that you cannot hide text button. You can if your design requires this. But in HTML itself (in this case, in HTML generated by Symfony Form component  & Twig) text should be placed inside the button but YOU should wrap that text around some <span> wrapper with visually hidden class which hides contents from the screen but keeps it available for blind people. Proper .visually-hidden implementation example: https://a11yproject.com/posts/how-to-hide-content/

To fix your problem you can:
- create custom form extenstion to add new setting like "visually_hidden_label" to ButtonType and friends,
- create your own form theme and override ButtonType's form_label block to wrap label text itself in <span class="visually-hidden"> wrapper.

**Comment by poolerMF** [comment]
@TomaszGasior the button may have an icon
