### ISSUE TITLE
[Console] Use of undefined constant STDOUT

### ISSUE THREAD

**Issue by lazosweb** [symfony/symfony#34341]
**Symfony version(s) affected**: 4.3.7

**Description**  
The latest update of Symfony Console 4.3.7 errors when calling an artisan command from a controller in Laravel with the following error message "ErrorException
Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)".

See attached image.
![Screenshot_2019-11-12 🧨 Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version ](https://user-images.githubusercontent.com/19972355/68697548-b98d7200-0587-11ea-857e-2dfe87b78cdb.png)

**How to reproduce**  
Windows Server 2016
IIS 10
PHP 7.3.11
Laravel 6.X
Laravel 5.8
Run an artisan command in Laravel from a controller.

**Comment by derrabus** [comment]
I don't have a Windows machine at the moment. Can you please test, if #34344 fixes your problem?

**Comment by lazosweb** [comment]
Yes, problem solved.
