### ISSUE TITLE
Preparing for 4.4 BETA, got compile error about declaring methods with missing type hints

### ISSUE THREAD

**Issue by Beyonit** [symfony/symfony#34345]
I got this error:

```
Compile Error: Declaration of Symfony\Component\Serializer\Normalizer\ProblemNormalizer::normalize($exception, $format = NULL, array $context = Array) must be compatible with Symfony\Component\Serializer\Normalizer\NormalizerInterface::normalize($object, ?string $format = NULL, array $context = Array)
```
In `Normalizer/ProblemNormalizer.php`. The methods don't use the type hints as defined in `NormalizerInterface`. This is what I changed and then it works:

`public function normalize($exception, $format = null, array $context = [])`
to
`public function normalize($object, string $format = null, array $context = [])`

and

`public function supportsNormalization($data, $format = null): bool`
to
`public function supportsNormalization($data, string $format = null): bool`

**Comment by chalasr** [comment]
Thanks for the report, see #34348 for the patch. 
Looks like you have 5.0 installed though, not 4.4.

**Comment by derrabus** [comment]
@Beyonit Can you please paste the output of `composer show | grep symfony` here?
