### ISSUE TITLE
empty_data empty string being casted to null

### ISSUE THREAD

**Issue by masterofnothing11** [symfony/symfony#34354]
**Symfony version(s) affected**: 4.2.1

**Description**  
Whenever creating a class based form builder with a `ChoiceType::class` and setting the `empty_data` to `''` it casts the data to `null` instead of an empty string. 

**How to reproduce**  
Create a simple form class:

```
public function buildForm(FormBuilderInterface $builder, array $options)
{
  $builder->add('defaultWarehouse', ChoiceType::class, [
                'choices' => [
                  'foo' => '1',
                  'bar' => '2'
                ],
                'placeholder' => 'Choose foor or bar',
                'required' => false,
                'empty_data' => '',
            ])
}
```

When handling the request with a simple 
```
$form = $this->createForm(UserType::class, $user);
$form->handleRequest($request);
```
it casts `defaultWarehouse` to `null` instead of an empty string giving the error message: `Expected argument of type "string", "NULL" given at property path "defaultWarehouse".`

I have researched about it but I didn't see anyone with the same problem so I'm assuming this is a bug.

**Comment by derrabus** [comment]
Symfony 4.2.1 is not maintained anymore. Please try to reproduce your problem with the latest 4.3 release.

**Comment by masterofnothing11** [comment]
Not a bug. Just a problem I didn't know existed:

https://stackoverflow.com/questions/58833980/empty-data-choicetype-returning-null/58835438#58835438
