### ISSUE TITLE
[Routing] Out of range integer in Symfony route

### ISSUE THREAD

**Issue by VereschakSun** [symfony/symfony#34356]
/**
 * @Route\Get("product/{idProduct}", requirements={"idProduct" = "(\d+)"})
 */
public function getUserAction(int $idProduct)
{
}

Now if I request http://localhost/product/1 everything is fine. But if I request http://localhost/product/11111111111111111 I get 500 error and Exception

 Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError:  must be of the type integer, string given

**Comment by adrienfr** [comment]
Hi,

This result is expected, `11111111111111111` is beyond the bounds of an integer type (see [here](https://www.php.net/manual/en/language.types.integer.php#example-42)).
