### ISSUE TITLE
[Profiler] Enabled Bundles report, class paths truncated too much

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#34359]
**Symfony version(s) affected**: 4.4.0-BETA2 (Only version tested, might be happening on earlier versions but not tested.)

**How to reproduce**  

Use debug toolbar to get to the configuration page e.g https://example.com/_profiler/c4498a?panel=config

Note the layout of Enabled Bundles box, loads of whitespace that can be used, yet path/namespace/class names are ... far too much, actually making it very unuseable and unhelpful.

its making 

`/a/helpful/path/to/some/namespaced/class`

into 

`/a/.../some/.../cla...`

<img width="1062" alt="Screenshot 2019-11-13 at 11 36 41" src="https://user-images.githubusercontent.com/400092/68760682-55f85880-060a-11ea-80b0-e4fe21358b7b.png">

**Possible Solution**  
Dont hide so much :)

**Comment by fabpot** [comment]
My preferred solution would be to remove that information. It's not something that changes from one request to another. And the information is already available via Composer, or 'bundles.php'.

**Comment by PhilETaylor** [comment]
Im not fussed either way - its not useful in its current state anyway :)

**Comment by derrabus** [comment]
I apparently did not have that issue when tinkering with 5.0-BETA1 last night. Strange. 🤔  https://twitter.com/derrabus/status/1194349953587597312

> My preferred solution would be to remove that information. It's not something that changes from one request to another. And the information is already available via Composer, or 'bundles.php'.

Please keep it. I work with a few clients that have non-standard Symfony setups with multiple kernels and/or containers. Not that I think that this is something someone should do, but seeing what bundles were actually loaded is really helpful for me in those situations.

**Comment by PhilETaylor** [comment]
Its done by the css classes output by dump

```
<td class="font-normal"><pre class="sf-dump" id="sf-dump-1153497182" data-indent-pad="  ">"<a href="phpstorm://open?file=/Users/phil/Sites/example.com/src/SinglepageMyJoomla&amp;line=0" rel="noopener noreferrer"><span class="sf-dump-str" title="/var/www/current/src/SinglepageMyJoomla
39 characters"><span class="sf-dump-ellipsis sf-dump-ellipsis-path">/var/www/current</span><span class="sf-dump-ellipsis sf-dump-ellipsis-path">/</span>src/SinglepageMyJoomla</span></a>"</pre><script>Sfdump("sf-dump-1153497182", {"maxDepth":0})</script></td>
```

**Comment by nicolas-grekas** [comment]
The last part should never be truncated and always be green. Anyone to find the faulty CSS that enables the ellipses on the final part of the path?

**Comment by stof** [comment]
@nicolas-grekas AFAIK, the green part corresponds to the subpath inside package. Many bundles have the bundle class defined at the root of the composer package, and so won't have such subpath.

**Comment by stof** [comment]
maybe the package name should not be truncated either here.

**Comment by PhilETaylor** [comment]
Just a quick not to say Thank You... its not a life changing change of code, but every little thing helps :)

**Comment by PhilETaylor** [comment]
Just circling back here, with RC1 - everything looks cool - thanks :-) 
![Screenshot 2019-11-17 at 19 00 33](https://user-images.githubusercontent.com/400092/69012335-96d6d100-096c-11ea-9731-2db836d00f8d.png)
