### ISSUE TITLE
DependencyInjection not passing service via interface

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#34361]
**Symfony version(s) affected**: 4.4.0-BETA1

**Description**  
In SF 4.3 I adding my custom services like:

```
    # SERVICES #
    Intranet\Service\:
        resource:      '../../src/Service'
        public:        true
        autowire:      true
        autoconfigure: true
```
So my all services pathname was a _ProjectDir_/src/Service. Each service implements custom interface naming like class name of service + 'Interface'. Path of interfaces was _ProjectDir_/src/Interfaces/Service so namespace looking like: Intranet\Interfaces\Service.

When I passing via DI one service using a interface, in SF 4.3 everything was fine, and i getting a object of passed service.

After update to 4.4 now i'm getting a error from DI like:
`Cannot autowire service "Intranet\Controller\AdministracjaController": argument "$parseAddressIPService" of method "__construct()" references interface "Intranet\Interfaces\Service\ParseAddressIPServiceInterface" but no such service exists. You should maybe alias this interface to the existing "Intranet\Service\ParseAddressIPService" service.`

Changing to passing directly by service resolve problem, but I don't wanna make this.

**Comment by nicolas-grekas** [comment]
Might be related to changes done in #33350
Can you provide a small reproducer app?

**Comment by michaljusiega** [comment]
@nicolas-grekas I will try.

**Comment by michaljusiega** [comment]
@nicolas-grekas see https://github.com/michaljusiega/issue-34361 & readme.md

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, it allowed me to spot the issue!

**Comment by TomasVotruba** [comment]
Will this be backported to 4.3? That would be great :+1: 

That's the minimum version I use now and it would allow me to drop my own compilser pass that adds this feature.
