### ISSUE TITLE
Symfony 4.4.0-BETA2: Segmentation fault with PHPUnit 6.5.14

### ISSUE THREAD

**Issue by COil** [symfony/symfony#34368]
**Symfony version(s) affected**: 4.4.0-BETA2

**PHP Version**: 7.2.17

**Description**  
PHPunit crashed with a segmentation fault.

```
[21:50:49] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ bin/phpunit --stop-on-failure
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
Testing Project Test Suite
..fish: 'bin/phpunit --stop-on-failure' terminated by signal SIGSEGV (Address boundary error)
```
Or when launching with my MakeFile:

```
[22:02:18] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ make test
bin/phpunit --stop-on-failure
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing Project Test Suite
..make: *** [test] Segmentation fault: 11
```

**Additional context**  
The site looks to work without problem, but as I can't run all the tests I can't be sure.
It's seems that failing test-suites contains loops. No error when accessing the URLs with the browser.

May be related :
[phpunit-segmentation-fault-11](https://stackoverflow.com/q/13268942/633864)

If you need more information, tell me. COil 🙂

**Comment by derrabus** [comment]
A segfault is first of all an issue of the php runtime, so the php version would be interesting to know. You could also try to update your php installation if you haven't done so already.

**Comment by COil** [comment]
PHP version added. Symfony 4.4 is supposed to work with 7.2.

**Comment by derrabus** [comment]
> Symfony 4.4 is supposed to work with 7.2.

True, but no php application should ever be able to trigger a segfault. So this is primarily a php bug that you're hitting. Would upgrading to the latest php 7.2 release be a big problem for you?

**Comment by nicolas-grekas** [comment]
There is one case when php segfault and it's userland's fault: infinite recursion.
Xdebug is able to report them, can you please try running this crash with xdebug enabled and report back what you get?

**Comment by COil** [comment]
I have enabled Xdebug: 

```
[08:01:09] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ php -i | grep xdebug.max_nesting_level
xdebug.max_nesting_level => 256 => 256
```

But the recursion is not caught. Do I have something more to set-up?

**Comment by derrabus** [comment]
No, that should do the trick. So if there‘s no recursion, next things you can try:

* Upgrade to the latest patch release of the php branch you‘re using (7.2.24 or 7.2.25RC1 in your case)
* If you use any exotic php extensions, disable them and check if the error still occurs.

**Comment by COil** [comment]
PHP upgraded. , same result.

```
[20:16:41] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ php -v
PHP 7.2.24 (cli) (built: Oct 25 2019 11:14:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
[20:16:49] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ make test
bin/phpunit --stop-on-failure
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing Project Test Suite
...make: *** [test] Segmentation fault: 11
[20:16:51] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$
```

**Comment by COil** [comment]
The bug come from loops like this:

```
    /**
     * @covers BlogController::show()
     */
    public function testShow(): void
    {
        $kernelBrowser = static::createClient();
        foreach (self::ARTICLES as $lang => $articles) {
            foreach ($articles as $slug) {
                $this->assertResponseIsOk($kernelBrowser, '/'.$lang.'/blog/'.$slug);
            }
        }

        $kernelBrowser->request('GET', '/en/blog/'.self::INACTIVE);
        $this->assertTrue($kernelBrowser->getResponse()->isNotFound());
    }
```
If I replace the loop by using a [PHPUnit dataprovider](https://blog.martinhujer.cz/how-to-use-data-providers-in-phpunit/), it works.

**Comment by COil** [comment]
Really I am playgin with the tests and it's related with the number of times: ```$kernelBrowser->request('GET', $url);``` is called.

**Comment by nicolas-grekas** [comment]
Can you maybe profile with Blackfire to see how memory is used with a number of iterations that doesn't make the script crash?

**Comment by COil** [comment]
I have tested on my Ubuntu Workstation with the same PHP version:

' ' ' 
[13:14:47] lvernet@lvernetZ240:~/workspace/strangebuzz.com$ php -v
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
' ' ' 

And this time, everything works correctly. So It may be a PHP parameter of Brew or something like this. Still annoying.

**Comment by nicolas-grekas** [comment]
Can you please try with this change?
```diff
--- a/src/Kernel.php
+++ b/src/Kernel.php
@@ -34,6 +34,7 @@ class Kernel extends BaseKernel
     {
         $container->addResource(new FileResource($this->getProjectDir().'/config/bundles.php'));
         $container->setParameter('container.dumper.inline_class_loader', true);
+        $container->setParameter('container.dumper.inline_factories', true);
         $confDir = $this->getProjectDir().'/config';
 
         $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
```

**Comment by COil** [comment]
When calling `$client->insulate(true);` before the request, it works. But the tests are very slow. (30 seconds instead of 3)

**Comment by COil** [comment]
I don't understand, now it works, even without the insulate calls:

```
[22:16:50] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ php -v
PHP 7.2.24 (cli) (built: Oct 25 2019 11:14:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
[22:22:30] coil@Mac-mini-de-COil.local:/Users/coil/Sites/strangebuzz.com$ make test
bin/phpunit --stop-on-failure
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing Project Test Suite
..................                                                18 / 18 (100%)

Time: 6.8 seconds, Memory: 70.25MB

OK (18 tests, 163 assertions)
```

The memory consumption doesn't look high. Well, I guess we can close this issue. I'll check on the next betas. Thanks for you help.

**Comment by nicolas-grekas** [comment]
Did you apply my patch or not?

**Comment by COil** [comment]
No, I can't reproduce now. But I noticed that test are faster with this line.

```
$container->setParameter('container.dumper.inline_factories', true);
```

3,8 seconds vs 4.8 seconds. 🙂

**Comment by COil** [comment]
I am closing this if it's OK for you.

**Comment by jul6art** [comment]
> Can you please try with this change?
> 
> ```diff
> --- a/src/Kernel.php
> +++ b/src/Kernel.php
> @@ -34,6 +34,7 @@ class Kernel extends BaseKernel
>      {
>          $container->addResource(new FileResource($this->getProjectDir().'/config/bundles.php'));
>          $container->setParameter('container.dumper.inline_class_loader', true);
> +        $container->setParameter('container.dumper.inline_factories', true);
>          $confDir = $this->getProjectDir().'/config';
>  
>          $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
> ```

That solved the problem for me, in PHP7.3 with brew

**Comment by YetiCGN** [comment]
> There is one case when php segfaults and it's userland's fault: infinite recursion.

Thanks! That was a good pointer to prohibit the possibilty of any recursion in our current REST API project.

> Xdebug is able to report them, can you please try running this crash with xdebug enabled and report back what you get?

I have some weird behavior with Symfony 4.4.0 and PHPUnit as well. Tried in combination with PHPUnit 8.3, 7.5 and 6.5. With xdebug enabled the tests just run very very slow but never crash or catch an infinite recursion.

I will try the change to Kernel.php above and maybe get some more info.

**Comment by COil** [comment]
I also have this "slowness" problem. But only when the container need to be recompiled (after a change in services.yml for example). At the second run, the tests are fast as they used to.

**Comment by YetiCGN** [comment]
I have now thrown out xdebug and exchanged it for pcov, no more slowness **at all**!

The segfaults are still there with Symfony 4.4.0 on PHP 7.4.0rc6, though. Had to revert to Symfony 4.3.8.

**Comment by Devristo** [comment]
I'm watching this thread as I am still experiencing occassional segfaults when running tests using the kernel with PHP 7.4.0 RC6 as well. 

Trimming the container as much as possible (excluding classes for value objects etc) seem to have lower the chance of errors but they still occasionally happen to me after a code change.

Unfortunately I could not create a reproducing example yet. Will give it another go later today. 

Remember: could very well be a bug in PHP instead of symfony.

**Comment by nicolas-grekas** [comment]
Does #34580 fix the issue? Could anyone give it a try?

**Comment by Devristo** [comment]
Sorry I forgot to mention I did try that patch. It seems to lower the chances for me, but it is still happening occassionally. However it definitely helps. Will try to debug my issue later today :)

**Comment by YetiCGN** [comment]
> Does #34580 fix the issue? Could anyone give it a try?

I can confirm that it mitigates the problem. I have added `"symfony/http-kernel": "4.4.x-dev@dev",` to my `composer.json`. I have only checked one Symfony 4.4 project, will validate with the other one shortly.

**Comment by Devristo** [comment]
It took me a while to create a core dump, it suggests pcov is the culprit. Will investigate more, but for it seems unrelated to this issue.

**Comment by YetiCGN** [comment]
Negative, I have segfaults without either pcov or xdebug as well:

    PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

    Runtime:       PHP 7.4.0RC6
    Configuration: /mnt/[...]/phpunit.xml.dist
    
    Testing Explicatis Website Tests
    ...............................................................  63 / 191 ( 32%)
    ............................................................... 126 / 191 ( 65%)
    .............Segmentation fault (core dumped)

**Comment by COil** [comment]
Hi @nicolas-grekas , I can confirm #34580 fixed the slowness issue for me.

**Comment by YetiCGN** [comment]
Dramatically! Our test suite here dropped from 26 minutes runtime and 1,000 MB of memory to a mere 2 minutes and 176.5 MB! Even with PCOV activated for code coverage, it takes only 2.3 minutes for 191 tests and 1,169 assertions now.
