### ISSUE TITLE
Setting cookie Samesite property does not work

### ISSUE THREAD

**Issue by axeljeremy7** [symfony/symfony#34362]
**Symfony version(s) affected**: x.y.z

**Description**  
`$cookie = new Cookie('BEARER', $tokenJWT, (
        new \DateTime())
            ->add(new \DateInterval('PT' . $ttl . 'S')), '/', null, true, true, false, 'strict');`

When I sent the cookie to the header
`$response->headers->setCookie($cookie);`

In the browser, it appears the Samesite to unset, and i try different values and still the same result. I need the Sameiste to be set.
Also, I am testing this using axios including the credentials.

![Blog_Who-codes-500x500](https://user-images.githubusercontent.com/16569050/68785411-277b7d00-060c-11ea-868f-cc3038312761.jpg)

**Comment by derrabus** [comment]
> **Symfony version(s) affected**: x.y.z

Can you please specify what version you are using?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by axeljeremy7** [comment]
> I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

$cookie = new Cookie('BEARER', $tokenJWT, ( new \DateTime()) ->add(new \DateInterval('PT' . $ttl . 'S')), '/', null, true, true, false, 'strict');
$cookie = new Cookie('BEARER', $tokenJWT, ( new \DateTime()) ->add(new \DateInterval('PT' . $ttl . 'S')), '/', null, true, true, false, 'sameSite');

when i check in chrome browser the cookie, is still unset the the string for either 'strict' or 'sameSite', im in symfony 4.3

**Comment by lionelkimbs** [comment]
Hello @axeljeremy7 how did you solve your problem ? I have the same :'(

**Comment by axeljeremy7** [comment]
I haven’t yet

Best regards,

Axel Jeremy Solano
Phone: 269-910-8172

Email: axel.jeremy.7@gmail.com

On March 2, 2020 at 10:40 GMT, lionelkimbs <notifications@github.com> wrote:

Hello [@axeljeremy7](https://github.com/axeljeremy7) how did you solve your problem ? I have the same :'(
