### ISSUE TITLE
Symfony 3.4.35 Monolog Extension error after running composer update

### ISSUE THREAD

**Issue by kevinkooyizen** [symfony/symfony#34372]
**Symfony version(s) affected**: 3.4.35

**Description**  
After running composer update, an error is requested for Monolog version to be downgraded.
                                                                                
In MonologExtension.php line 55:                                                 
                                                                                   
    Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to ve    
    rsion 1.

**How to reproduce**  
1. Create a new Symfony 3.4 project. 
2. Run composer update.

**Comment by xabbuh** [comment]
This needs to be fixed in MonologBundle (see symfony/monolog-bundle#330).
