### ISSUE TITLE
Symfony BrowserKit Follows Redirects Indefinitely 

### ISSUE THREAD

**Issue by lrehmann** [symfony/symfony#34371]
**Description**  
The Symfony BrowserKit user-agent appears to follow redirects without end. 
On a website I host, a user browsing with Symfony BrowserKit came upon an incorrectly configured page redirecting to itself (HTTP 302). Most browsing agents I've seen will follow a redirect like this around 20 times before giving up. Chrome and others respond with "the server redirected you too many times". 
Symfony BrowserKit never gives up and will continuously hammer the url until the user notices their 'crawler' is hanging. This behavior wastes both client and server resources. 

**How to reproduce**  
Request an external url with a 302 redirect loop.

**Possible Solution**  
Limit the number of allowed redirects.
wget handles this with the --max-redirect=1 flag
curl uses --max-redirs

**Comment by xabbuh** [comment]
Did you try using the `setMaxRedirects()` method of the BrowserKit's `Client` class?

**Comment by lrehmann** [comment]
setMaxRedirects should have a default (not infinity) -- to behave more like most good user-agents. 

Without a default, you're needlessly wasting both client and server resources. 

I am unable to set the MaxRedirects as the issue I'm facing is with an unknown symfony client browsing my server.
