### ISSUE TITLE
[DoctrineBridge] Dependency on a non existent service RegistryInterface

### ISSUE THREAD

**Issue by Matts** [symfony/symfony#34377]
**Symfony version(s) affected**: 4.4.0-BETA2

**Description**  

When upgrading to 4.4, I got the following error
![image](https://user-images.githubusercontent.com/3371705/68858771-17d06700-06e6-11ea-8a2e-9bc6010b79ab.png)

This most likely happened during the deprecation of the RegistryInterface (#32394) where possibly the class alias has been removed.

**How to reproduce**  

```
App\Repository\Repository:
        arguments:
            - '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']
```

**Possible Solution**  

Reregister the class alias

**Additional context**

**Comment by nicolas-grekas** [comment]
This happens when you use Doctrine Bundle 2 - it's not related to the bridge.
See https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md

**Comment by Matts** [comment]
@nicolas-grekas Ah, so it is not a BC break due to this being a major version of Doctrine, gocha.

**Comment by Lopton** [comment]
> 
> 
> This happens when you use Doctrine Bundle 2 - it's not related to the bridge.
> See https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md

@nicolas-grekas  For those of us that need a little more help (like the 500+ viewing [this](https://stackoverflow.com/questions/59327363/deprecation-warnings-after-upgrading-symfony-4-3-9-to-4-4-1) ). Can you give any advice on what the solution it is? Also I am unclear why the document you mentioned, as well as the Symfony Documentation, says to use Doctrine\Common\Persistence\ManagerRegistry when that is also deprecated and being removed?

**Comment by nicolas-grekas** [comment]
That's because the deprecation happened after the linked document was written, like last week. Could you please send a PR to update it?
