### ISSUE TITLE
Mailer component: change sendmail command

### ISSUE THREAD

**Issue by adelinoo** [symfony/symfony#34386]
Hello,
i want to use the experimental component Mailer.
I develop under docker and i dont have sendmail package installed but i use MailHog for testing.
Mailer use  `/usr/sbin/sendmail -bs` in SendmailTransport class, and there's no way to change this.
I thought that if you add a package paramater will be very useful.
Thanks for your help.

**Comment by fabpot** [comment]
If you are using Mailhog, I suppose you need to use SMTP instead of sendmail. You can change the sendmail command as this is the first arg of the SendmailTransport constructor.

**Comment by bernhardberger** [comment]
I'd want to open this for another reason: our agency hoster doesn't support sendmail -bs, only -t.

This is very much needed.

**Comment by xabbuh** [comment]
@bernhardberger As Fabien said you can change the sendmail command by passing it as the first argument to the constructor of the `SendmailTransport` class. Doesn't that solve your issue?

**Comment by gmuehl** [comment]
If you are using async Mails with `symfony/messenger` i see no chance to change the Constructor of `SendmailTransport` - Sendmail ist used because of the DSN configured in `.env` - but how can i change -bs to -t then ?

**Comment by ericjacolin** [comment]
The feature request was to be able to do this by configuration of mailer.transports.
Like it is possible for Swiftmailer: `command: '/usr/bin/msmtp -t'`
Makes for simpler code than having to create a new scheme and SendMailTransport factory class just to be able to override the constructor's first argument.
