### ISSUE TITLE
Routing utf8 option doesn't work as expected

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#34392]
**Symfony version(s) affected**: 4.4 (maybe it affects to 4.3 too?)

**Description**  
I'm testing 4.4-dev and I created a simple route like this:

```php
    /**
     * @Route("/blog/{category}")
     */
    public function someMethod(string $category)
    {
        // ...
    }
```

If I browse `/blog/日本`, everything works as expected, because `framework.router.utf8` is set to `true` by default when creating a new Symfony app.

However, if I set that option to `false`, the route still matches. And if I define the route in YAML and add `options: { utf8: false }` explicitly to it ... it still works.

I think it's great that UTF-8 routes work always ... but I wonder if this option works as expected or it's no longer needed (or maybe, I'm doing something wrong or I don't understand how this works 😓). Thanks.

**Comment by nicolas-grekas** [comment]
UTF-8 routes always match even if the option is not set, that's since 2.0.
The option is not about allowing or not UTF-8 - it's about matching *requirements* using UTF-8 or not.
`{..}` (2 chars) matches `日本`  with `utf8: true` - and doesn't match without the option.

**Comment by javiereguiluz** [comment]
Thanks for the explanation. However, if I set the `utf8` option to true and change the URL definition to this:

```
    /**
     * @Route("/blog/{category}", requirements={"category"=".."})
     */
```

The URL `/blog/ab` works, the URL `/blog/abc` doesn't work (as expected) but the following URL doesn't work either: `/blog/日本`. This is the error:

![image](https://user-images.githubusercontent.com/73419/68939689-80304e80-07a1-11ea-8dd8-2d23be226d1a.png)

**Comment by nicolas-grekas** [comment]
Works for me - maybe you didn't set the option?

**Comment by javiereguiluz** [comment]
I checked and it's set ... but don't worry, it's probably an issue on my side. Cheers!

**Comment by nicolas-grekas** [comment]
Send a reproducer if you want.
