### ISSUE TITLE
Translation cache warming ineffective since #34129

### ISSUE THREAD

**Issue by jaikdean** [symfony/symfony#34395]
**Symfony version(s) affected**: 4.3.7/4.3.8

**Description**  
Since 4.3.7, warming translation caches then deploying to a different path results in the warmed cached being ignored and regenerated. I believe this is caused by the change in #34129, which effectively adds the full project path to the cache key for the translator.

**How to reproduce**  
* Warm the translation cache.
* Rename the project directory.
* Warm the translation cache again. At this point, the translation cache file names will change.

For example, `var/cache/prod/translations/catalogue.en_GB.FOO.php` will be replaced with `var/cache/prod/translations/catalogue.en_GB.BAR.php`.

**Possible Solution**  
Could the project directory be removed from the paths in "scanned_directories"?

**Comment by fancyweb** [comment]
Status: reviewed

Looks like we need to remove the root directory from the passed scanned directories list. I'll have a look.

**Comment by fancyweb** [comment]
Alternative: we enable https://github.com/symfony/symfony/pull/34129 only in debug mode.

**Comment by jaikdean** [comment]
> Alternative: we enable #34129 only in debug mode.

Only enabling this in debug mode feels safer and more reliable than fudging paths, if that fulfills the need of the original change.

**Comment by fabpot** [comment]
I would prefer having the same behavior in dev and prod if possible.
