### ISSUE TITLE
Updating from sf 3.4.32 to 3.4.35 results in "Uncaught RuntimeException: Symfony 5 is required for Monolog 2 support."

### ISSUE THREAD

**Issue by manuelkiessling** [symfony/symfony#34393]
**Symfony version(s) affected**: 3.4.32, 3.4.35

**Description**  
A Symfony project based on the composer.json and composer.lock setup at https://gist.github.com/manuelkiessling/2b44ab1b9d39ecd8112f63746c7c17cf runs into `PHP Fatal error:  Uncaught RuntimeException: Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1. in vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:55` when running `composer update --with-dependencies`.

**How to reproduce**  
Set up a new Symfony 3 project with the composer.json and composer.lock settings as seen in https://gist.github.com/manuelkiessling/2b44ab1b9d39ecd8112f63746c7c17cf. Run `composer install`. Then, run `composer update --with-dependencies`.

**Possible Solution**  
Add `"monolog/monolog": "^1.25.2"` in the `require` section of composer.json before running `composer update --with-dependencies`.

**Additional context**  
Composer version 1.9.1 2019-11-01 17:20:17, PHP 7.3.11 (cli) (built: Oct 23 2019 16:31:28) ( NTS ), on Linux 5.3.10-arch1-1 #1 SMP PREEMPT Sun, 10 Nov 2019 11:29:38 +0000 x86_64 GNU/Linux

**Comment by xabbuh** [comment]
This needs to be fixed in MonologBundle (see symfony/monolog-bundle#330).
