### ISSUE TITLE
php const in doctrine yaml broken since v4.3.6

### ISSUE THREAD

**Issue by t12ung** [symfony/symfony#34394]
**Symfony version(s) affected**: ~4.3.6

**Description**  
Use of php const in doctrine.yaml cannot find defined constant since `symfony/yaml` package updated from `4.3.5`.

This following error appears on running: `php bin/console cache:clear` so also happens on `composer update`.

`
The file "/config/packages/doctrine.yaml" does not contain valid YAML: The constant "CONSTANT_DBHOST" is not defined at line 8 (near "host: !php/const CONSTANT_DBHOST") in /config/packages/doctrine.yaml (which is loaded in resource "/config/packages/doctrine.yaml").
`

Using `!php/const` in `/config/services.yaml` works fine and does not report errors, unlike in `doctrine.yaml`.

(Note: I removed my application's directory in filepaths mention in error message)

_I know that this is not best practice for environment configuration, but I'm in the middle of a partial migration to Symfony Framework so don't want to change the existing application configuration just yet. So please, no comments about what I **should** be doing instead._

_EDIT: Going back over Symfony documentation, I realised that the use of php constants was **only** described for use as parameters in the services container. So whilst using php const in doctrine.yaml worked before, maybe this was not intended as a feature so this issue is not strictly a bug!?_

**How to reproduce**  
- Define a constant in `/public/index.php`
- Refer to this constant in `/config/packages/doctrine.yaml`, e.g.:

```
doctrine:
    dbal:
        host: !php/const CONSTANT_DBHOST
```

**Possible Solution**  (added with new edit)
A workaround would be to define the doctrine.yaml configuration using parameters as values instead of php constants. This indeed works fine.

**Additional context**  
The same error message is reported by the following files:
- FileLoader.php line 166
- YamlFileLoader.php line 649
- Inline.php line 597

**Comment by xabbuh** [comment]
The `public/index.php` file is never loaded when you execute the application from the command-line. I fail to see how this should have ever worked.

**Comment by stof** [comment]
PHP constants are a feature of the YAML component, so they will work in any YAML file. But they require that the constant is defined at the time the YAML file is parsed.

**Comment by t12ung** [comment]
~~Actually, it would be accurate to say that it ignores the public/index.php from command-line, which is why the error happens when it tries to parse the yaml file. So maybe the `doctrine.yaml` was previously never parsed in v4.3.5?~~ (last para)

I did try to include the php file defining the constant in FileLoader.php and that fixed the error message - but obviously don't want to go hacking symfony core files as a workaround.

Having updated symfony on my own dev environment and then rolling back to v4.3.5 I am no longer able to reproduce the environment where the cli does NOT complain about the constant. This is very puzzling; as on another dev environment where the issue was initially found - it was resolved by reverting back to v4.3.5 from 4.3.8 in exactly the same way as I am doing on my own dev.

Anyhow, logically thinking I do agree just like @xabbuh mentioned, the `public/index.php` would not be picked up on the CLI - so why does `services.yaml` not raise the same error as `doctrine.yaml`?

Currently set up like this with no errors:

`services.yaml`
```
parameters:
    db.name: !php/const CONSTANT_DBNAME
```

`doctrine.yaml`
```
doctrine:
    dbal:
        dbname: '%db.name%'
```

**Comment by nicolas-grekas** [comment]
Would you be able to provide a reproducer we could run locally?

**Comment by t12ung** [comment]
Sorry, I've been too busy with work, but I'll try do provide a reproducer soon.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
