### ISSUE TITLE
Can't create a new projet with a specified version

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#34402]
**Symfony version(s) affected**: All

**Description**  
Documentation (https://symfony.com/doc/current/setup.html#symfony-lts-versions) indicate that we can specify a version to `symfony new` command, to install a specific version.

It works with a major version `and` a minor version specified (`4.3` for example).
But that's can't be with only a major version specified (`4` for example) or a major + minor + bugfix (`4.3.8` for example)
`symfony/skeleton` package don't have minor versions (`x.y.99` versions only) so `/usr/bin/composer create-project symfony/skeleton project x.y.z` called internally will not work.

**How to reproduce**  
`symfony new foo --version=4.3.8`

```bash
$ symfony new foo --version=4.3.8
* Creating a new Symfony 4.3.8 project with Composer
  (running /usr/bin/composer create-project symfony/skeleton foo 4.3.8)

 ◓  
                                                               
  [InvalidArgumentException]                                   
  Could not find package symfony/skeleton with version 4.3.8.  
                                                               

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

                                                                                            
  unable to run /usr/bin/composer create-project symfony/skeleton foo 4.3.8: exit status 1
```

**Comment by fabpot** [comment]
The documentation is indeed wrong. You cannot specify a patch version.

**Comment by steevanb** [comment]
And a major version too ;)

```bash
$ symfony new foo --version=4
* Creating a new Symfony 4 project with Composer
  (running /usr/bin/composer create-project symfony/skeleton foo 4)

 ◒  
                                                           
  [InvalidArgumentException]                               
  Could not find package symfony/skeleton with version 4.  
                                                           

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

                                                                                        
  unable to run /usr/bin/composer create-project symfony/skeleton foo 4: exit status 1  
```

**Comment by nicolas-grekas** [comment]
Correct, you need a version that composer can deal with.
I'm closing because there is no bug here - that's normal Composer behavior, given the tags that exist on the symfony/skeleton repository.

**Comment by steevanb** [comment]
I agree that's the normal behavior of Composer.

But to me, documentation is wrong (as @fabpot said) or symfony/skeleton should add tags to respect the documentation (better solution I think, but hardest to do).

**Comment by nicolas-grekas** [comment]
Would you mind sending a doc PR?
About tags, we won't add more because that's extra maintainance work we'd like to avoid. They're not required.
