### ISSUE TITLE
request always contain empty BasePath in unit tests

### ISSUE THREAD

**Issue by isomT** [symfony/symfony#34412]
Symfony version(s) affected: 3.4.31

**Description** 
Let's start with a simple question : why the request object always contain an empty basePath in my unit test, but it works very well on the browser?

As now the problem is comming from $request->getBasePath() methode in Symfony\Component\HttpFoundation\Request because always return empty string but the expected behaviour is to return the PATH_TO_MY_PROJECT_FOLDER\web, in my case must return projects\web_apps\MY_PROJECT_FOLDER_NAME\web

**How to reproduce**  
I have a controller has an action that looks something like this:
```
/**
 * @Route("/my_route_path", name="my_route_name")
 */
public function doSomethingAction(Request $request)
{
    $myPath = $request->getScheme().'://'.$request->getHttpHost().''.$request->getBasePath();
    $data = file_get_contents($myPath. '/data_folder/data.json');

    return $this->render('@Entry/my_template.html.twig', array(
        'data' => json_decode($data, true)
    ));
}
```

And I create a test for this action like this:
```
/** @test */
public function doSomething_should_success()
{
    $client = static::createClient();
    $crawler = $client->request('GET', '/my_route_path');
    $this->assertEquals(200, $client->getResponse()->getStatusCode());
}
```
But I can't run the functional test I still get : 
`Failed asserting that 500 is identical to 200` 
So, after I checked the test.log file I find this error : `file_get_contents(http://localhost/data_folder/data.json):failed to open stream`

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
