### ISSUE TITLE
[Serializer] Wrong output when filtering objects

### ISSUE THREAD

**Issue by dpinheiro** [symfony/symfony#34424]
**Symfony version(s) affected**: 3.4

**Description**  
When using `array_filter` to filter a object array before calling the serializer the output is wrong. The serialized string is only wrong if the output of the `array_filter` is not the same as the input.
The major problems are with `json`, `csv` and `yml` encoding. With `xml` the only noticeable difference is the index of the item

**How to reproduce**  

```
$objects = [
    [
        'id' => 1,
        'valid' => true
    ],
    [
        'id' => 2,
        'valid' => false
    ],
    [
        'id' => 3,
        'valid' => true
    ]
];

$filtered = array_filter($objects, function($object) {
    return $object['valid'];
    //return true; (if we return all the objects this problem doesn't occur)
});

$serializer->serialize($filtered, 'json');
```

**Possible Solution**  
Looks like this is due to the index numbering. After applying the `array_filter` the index is not sequencial

**Additional context**  
This is the output of running the code above when serializing to json and csv

```
'{"0":{"id":1,"valid":true},"2":{"id":3,"valid":true}}'
```

```
0.id,0.valid,2.id,2.valid
1,1,3,1
```

**Comment by xabbuh** [comment]
That's expected. If some indexes are missing in between, the data structure cannot be treated as a sequence anymore, but is dumped as a map instead. If you want to it to be serialized as a sequence, you can use `array_values()` to ensure that the input actually still is a sequence:

```php
$serializer->serialize(array_values($filtered), 'json');
```

I am closing here as explained.
