### ISSUE TITLE
Possibility EntityType[EntityType] in Forms

### ISSUE THREAD

**Issue by isopen** [symfony/symfony#34439]
**Description**  
`CollectionType[EntityType][EntityType][field,...,fieldn]` in forms

**Example**  
```
class TestType {
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('test', CollectionType::class, [
             'entry_type' => EntityType::class,
             'entry_options' => [
              'class' => Test::class,
              'class_options' => [
                'field' => Test::class,
                ...
                'filed' => Testn::class
              ]
              ...
            ]) ;
    }
}
request data: test[test][0][field] = 1
...
test[test][1][filedn] = 2
```
This is the case when the link table is used.
Maybe there is already a solution for this?

**Comment by stof** [comment]
I don't understand what you are asking for here. `EntityType` does not have a `class_options` field.

Your description makes me think that you want to edit the fields of the related entities in the collection. But then, you should not be using `EntityType` as your `entry_type`, as `EntityType` is about selecting an existing entity (it is rendered as a `<select>` field). It seems to me that your use case would be to use a different (custom) type as your entry_type.

**Comment by isopen** [comment]
Yes, I tried to do so:
```
class TestType {
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('test', CollectionType::class, [
             'entry_type' => CustomType::class,
             'allow_extra_fields' => true,
            ]) ;
    }
}
```
```
class CustomType {
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('field', EntityType::class, [
              'class' => Test::class,
              'allow_extra_fields' => true,
            ])
            ->add('fieldn', EntityType::class, [
              'class' => Test1::class,
              'allow_extra_fields' => true,
            ]);
    }
}
```
Result: installation recommendations `compound true` and `500`

**Comment by xabbuh** [comment]
This rather looks like a support request to me. I am sorry, but we are using GitHub only to track issues and feature requests. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by isopen** [comment]
Thanks. Here is a solution for connected forms
https://symfony.com/doc/current/form/form_collections.html
for nested values: `'allow_extra_fields' => true`
If necessary, then: `'by_reference' => false`
