### ISSUE TITLE
Tests on appveyor need some love

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#34444]
Looks like there might be a cleanup missing?

Testing src\Symfony/Component/Cache
[...]
There were 2 errors:
1) Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest::testDsn with data set #1 ('sqlite:C:\Users\appveyor\AppD...E0.tmp', 'C:\Users\appveyor\AppData\Loc...E0.tmp')
PDOException: SQLSTATE[HY000]: General error: 1 table cache_items already exists
C:\projects\symfony\src\Symfony\Component\Cache\Adapter\PdoAdapter.php:169
C:\projects\symfony\src\Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest.php:82
2) Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest::testDsn with data set #2 ('sqlite3:///C:\Users\appveyor\...E0.tmp', 'C:\Users\appveyor\AppData\Loc...E0.tmp')
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE cache_items (item_id CLOB NOT NULL, item_data BLOB NOT NULL, item_lifetime INTEGER UNSIGNED DEFAULT NULL, item_time INTEGER UNSIGNED NOT NULL, PRIMARY KEY(item_id))':
SQLSTATE[HY000]: General error: 1 table cache_items already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractSQLiteDriver.php:47
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php:166
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php:146
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1100
C:\projects\symfony\src\Symfony\Component\Cache\Adapter\PdoAdapter.php:138
C:\projects\symfony\src\Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest.php:82
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 table cache_items already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1098
C:\projects\symfony\src\Symfony\Component\Cache\Adapter\PdoAdapter.php:138
C:\projects\symfony\src\Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest.php:82
Caused by
PDOException: SQLSTATE[HY000]: General error: 1 table cache_items already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:41
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1098
C:\projects\symfony\src\Symfony\Component\Cache\Adapter\PdoAdapter.php:138
C:\projects\symfony\src\Symfony\Component\Cache\Tests\Adapter\PdoAdapterTest.php:82
ERRORS!
Tests: 2119, Assertions: 491, Errors: 2, Skipped: 795.
KO src\Symfony/Component/Cache

----

Testing src\Symfony/Component/Lock
SSSSSSSSSSSSSSSSSSSSSSS........S...EE..........SSSSSSSSSSSSSSSS  63 / 234 ( 26%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Time: 46.69 seconds, Memory: 4.00 MB
There were 2 errors:
1) Symfony\Component\Lock\Tests\Store\PdoStoreTest::testDsn with data set #1 ('sqlite:C:\Users\appveyor\AppD...1E.tmp', 'C:\Users\appveyor\AppData\Loc...1E.tmp')
PDOException: SQLSTATE[HY000]: General error: 1 table lock_keys already exists
C:\projects\symfony\src\Symfony\Component\Lock\Store\PdoStore.php:285
C:\projects\symfony\src\Symfony\Component\Lock\Tests\Store\PdoStoreTest.php:86
2) Symfony\Component\Lock\Tests\Store\PdoStoreTest::testDsn with data set #2 ('sqlite3:///C:\Users\appveyor\...1E.tmp', 'C:\Users\appveyor\AppData\Loc...1E.tmp')
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE lock_keys (key_id VARCHAR(64) NOT NULL, key_token VARCHAR(44) NOT NULL, key_expiration INTEGER UNSIGNED NOT NULL, PRIMARY KEY(key_id))':
SQLSTATE[HY000]: General error: 1 table lock_keys already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractSQLiteDriver.php:47
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php:166
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php:146
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1100
C:\projects\symfony\src\Symfony\Component\Lock\Store\PdoStore.php:259
C:\projects\symfony\src\Symfony\Component\Lock\Tests\Store\PdoStoreTest.php:86
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 table lock_keys already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1098
C:\projects\symfony\src\Symfony\Component\Lock\Store\PdoStore.php:259
C:\projects\symfony\src\Symfony\Component\Lock\Tests\Store\PdoStoreTest.php:86
Caused by
PDOException: SQLSTATE[HY000]: General error: 1 table lock_keys already exists
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:41
C:\projects\symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1098
C:\projects\symfony\src\Symfony\Component\Lock\Store\PdoStore.php:259
C:\projects\symfony\src\Symfony\Component\Lock\Tests\Store\PdoStoreTest.php:86
ERRORS!
Tests: 107, Assertions: 71, Errors: 2, Skipped: 82.
KO src\Symfony/Component/Lock

**Comment by stof** [comment]
it might be broken windows compat. `sqlite3:///C:\Users\appveyor...1E.tmp` looks weird as path, as we have 3 slashes there. But the third slash in a Unix sqlite URL DSN is the beginning of an absolute path AFAIK, and that's not how paths look like on windows. This might create issue with the sqlite initialization.
