### ISSUE TITLE
[symfony/contracts] Why hard dependency to php 7.2.9?

### ISSUE THREAD

**Issue by Defcon0** [symfony/symfony#34442]
**Symfony version(s) affected**: v3.4.35

**Description**  
I can't install symfony/contracts on a SUSE SLES 12 (SP4) system since it only has php 7.2.**5**. symfony/contracts requires 7.2.**9**.

**Possible Solution**  
Set the dependency to `^7.2` insteadt of `^7.2.9`.

**Additional context**  
If a pull reuqest is needed, just tell me.

**Comment by nicolas-grekas** [comment]
Let's give it a try, see #34443

**Comment by Defcon0** [comment]
Awesome. Thanks!

**Comment by Matts** [comment]
Probably the version was ^7.2.9 because 7.2.8 has a CVE?
