### ISSUE TITLE
[YAML] Multiline string as scalar block for tagged values

### ISSUE THREAD

**Issue by natepage** [symfony/symfony#34450]
**Symfony version(s) affected**: 3.4 to latest

**Description**  
The Yaml component is able to parse scalar bock for tagged values:

```yaml
foo: !bar |
    foo
    another line
```

If parse the above YAML string you will get the expected `TaggedValue` containing the string with line breaks, amazing!

However if you try to dump a PHP value to this YAML string you are not getting the intended output but the following:

```yaml
foo: !bar "foo\nanother line"
```

And that's because the parsing tag `Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK` isn't used for tagged value.

**How to reproduce**  
Try to dump a PHP value containing a `TaggedValue` with a string with line breaks as a value while the tag `Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK` is passed.

```php

use Symfony\Component\Yaml\Tag\TaggedValue;
use Symfony\Component\Yaml\Yaml;

$php = ['foo' => new TaggedValue('bar', "foo\nanother line")];
$yaml = Yaml::dump($php, 1, 0, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
```

**Possible Solution**  
If this is identified as a legit issue, I've created a PR to fix it. #34449

**Comment by fancyweb** [comment]
Can you please close the issue as your PR was merged? Thanks 😄
