### ISSUE TITLE
[Serializer] MetadataAwareNameConverter break groups parameters

### ISSUE THREAD

**Issue by spike31** [symfony/symfony#34455]
**Symfony version(s) affected**: 4.3.7  

**Description**  
Since #34035, cannot denormalize with that syntax `['groups' => 'user']`

**How to reproduce**  
```
$obj = $normalizer->denormalize(['bar' => 'Api Platform'], Foo::class, null, ['groups' => 'user']);

-->

/**
In MetadataAwareNameConverter.php line 126:
                                                                                 
Warning: array_intersect(): Expected parameter 2 to be an array, string given
*/
```
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/NameConverter/MetadataAwareNameConverter.php#L126

**Possible Solution**  

@antograssiot If you could have a look at this

**Additional context**

**Comment by bizley** [comment]
I can confirm the same problem. Changing the `groups` value to array helped. Possible solution is the array cast in [this line](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Serializer/NameConverter/MetadataAwareNameConverter.php#L126):

    if ($groups && !array_intersect($groups, (array)$context[AbstractNormalizer::GROUPS] ?? [])) {

**Comment by antograssiot** [comment]
I just submitted a fix, apologies for that 😞
