### ISSUE TITLE
[Session] PdoException when upgrading from 4.3 to 4.4

### ISSUE THREAD

**Issue by s-duval** [symfony/symfony#34479]
**Symfony version(s) affected**: 4.4

**Description**  
After upgrade from 4.3 to 4.4 the session didn't work anymore when using PDO Session handler in MySQL context, here is the error

`SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'sess_lifetime' at row 1`

The table was created using the SQL statement provided in the documentation https://symfony.com/doc/4.4/doctrine/pdo_session_storage.html : 

`CREATE TABLE `sessions` (
    `sess_id` VARCHAR(128) NOT NULL PRIMARY KEY,
    `sess_data` BLOB NOT NULL,
    `sess_time` INTEGER UNSIGNED NOT NULL,
    `sess_lifetime` MEDIUMINT NOT NULL
) COLLATE utf8mb4_bin, ENGINE = InnoDB;`

**How to reproduce**  
Use PDO Session handler in 4.3 and then upgrade to 4.4

**Comment by nicolas-grekas** [comment]
MEDIUMINT should be replaced by INTEGER - can you please send a PR to fix the doc?

**Comment by xabbuh** [comment]
already fixed in symfony/symfony-docs#12641 (merged now)
