### ISSUE TITLE
[Validator] Breaking change caused by return types upgrade from 4.3 to 4.4

### ISSUE THREAD

**Issue by s-duval** [symfony/symfony#34478]
**Symfony version(s) affected**: 4.4.0

**Description**  
Upgrading from 4.3 to 4.4 today causing cache clearing and the bundle  : sonata admin bundle to throw errors.

From the commit "Add return types to internal|final|private methods" 32116184d7c62639d7351c49c160927935e5ba99

Return type was forced even on magic methods which can cause breaking changes on third party libraries overriding them without specifying the return type

**How to reproduce**  
To reproduce the bug simply create a new Constraint class overriding one of the method where the return type was forced in 4.4, this class will work in 4.3 but not when upgrading in 4.4

`
class MyConstraint extends Constraint
{
public function __sleep(){ ...}
}
`

**Possible Solution**  
Maybe don't force return types on 4.4 version to keep retro compatibility
and do those breaking changes in 5 ?

**Comment by xabbuh** [comment]
The `__sleep()` method is marked as internal. For those the BC promise does not apply. If you override internal methods, you will need to be prepared to update your code if we change them. Thus, I am going to close here as explained.

**Comment by nicolas-grekas** [comment]
Actually we might want to reconsider this one: __sleep is the only way to serialize an objet so there is no other choice than overriding it. It doesn't totally "belong to us".

**Comment by dmaicher** [comment]
I believe this particular issue was fixed already though: https://github.com/sonata-project/SonataCoreBundle/pull/716

**Comment by jaikdean** [comment]
> I believe this particular issue was fixed already though: [sonata-project/SonataCoreBundle#716](https://github.com/sonata-project/SonataCoreBundle/pull/716)

That fix isn't released, and is on a bundle that is now deprecated. The Sonata bundles typically have quite a slow release cycle, so it'll almost certainly be faster to get this fixed in Symfony.

**Comment by er1z** [comment]
@nicolas-grekas — what should we do? Make a bugfix release to Symfony? This issue is pretty important because prevents our projects from upgrading to 4.4 LTS.

**Comment by xabbuh** [comment]
see #34513 for the fix
