### ISSUE TITLE
Update to 5.0 from 4.4

### ISSUE THREAD

**Issue by pyatnitsev** [symfony/symfony#34473]
**Symfony version(s) affected**: 5.0

**Description**  
I just updated my app to 4.4 and after it to 5.0, composer ok, but on post-update I got error:

 [KO]
Script cache:clear returned with error code 255
!!
!!
!!  TypeError: Argument 1 passed to Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer::__construct() must be an instance of Symfony\Component\Validator\ValidatorBuilderInterface, instance of Symfony\Component\Validator\ValidatorBuilder given, called in /var/www/own/app/var/cache/dev/ContainerZERLxPf/getValidator_Mapping_CacheWarmerService.php on line 13 in /var/www/own/app/vendor/symfony/framework-bundle/CacheWarmer/ValidatorCacheWarmer.php on line 38
!!
!!  Call Stack:
!!      0.0003     408432   1. {main}() /var/www/own/app/bin/console:0
!!      0.0401     886256   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/own/app/bin/console:29
!!      0.0574     982080   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/own/app/vendor/symfony/console/Application.php:148
!!      0.0574     982080   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /var/www/own/app/vendor/symfony/framework-bundle/Console/Application.php:65
!!      0.0574     982080   5. App\Kernel->boot() /var/www/own/app/vendor/symfony/framework-bundle/Console/Application.php:159
!!      0.0647    1097680   6. App\Kernel->initializeContainer() /var/www/own/app/vendor/symfony/http-kernel/Kernel.php:136
!!      5.0077   13738472   7. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() /var/www/own/app/vendor/symfony/http-kernel/Kernel.php:657
!!      5.0077   13740400   8. ContainerZERLxPf\srcApp_KernelDevDebugContainer->{closure:/var/www/own/app/var/cache/dev/ContainerZERLxPf/getCacheWarmerService.php:12-21}() /var/www/own/app/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:89
!!      5.0077   13740400   9. ContainerZERLxPf\srcApp_KernelDevDebugContainer->load() /var/www/own/app/var/cache/dev/ContainerZERLxPf/getCacheWarmerService.php:13
!!      5.0078   13743792  10. require('/var/www/own/app/var/cache/dev/ContainerZERLxPf/getValidator_Mapping_CacheWarmerService.php') /var/www/own/app/var/cache/dev/ContainerZERLxPf/srcApp_KernelDevDebugContainer.php:439
!!      5.0270   13919200  11. Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer->__construct() /var/www/own/app/var/cache/dev/ContainerZERLxPf/getValidator_Mapping_CacheWarmerService.php:13
!!
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer::__construct() must be an instance of Symfony\Component\Validator\ValidatorBuilderInterface, instance of Symfony\Component\Validator\ValidatorBuilder given, called in /var/www/own/app/var/cache/dev/ContainerZERLxPf/getValidator_Mapping_CacheWarmerService.php on line 13 in /var/www/own/app/vendor/symfony/framework-bundle/CacheWarmer/ValidatorCacheWarmer.php on line 38
!!
!!  Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer::__construct() must be an instance of Symfony\Component\Validator\ValidatorBuilderInterface, instance of Symfony\Component\Validator\ValidatorBuilder given, called in /var/www/own/app/var/cache/dev/ContainerZERLxPf/getValidator_Mapping_CacheWarmerService.php on line 13 in /var/www/own/app/vendor/symfony/framework-bundle/CacheWarmer/ValidatorCacheWarmer.php on line 38
!!
!!  Call Stack:
!!      5.0283   11512232   1. Symfony\Component\Debug\ErrorHandler->handleException() /var/www/own/app/vendor/symfony/debug/ErrorHandler.php:0
!!

**How to reproduce**  
Just update to 5,0

What's could be wrong?

**Comment by duduclx** [comment]
Hi,

Try remove your dev cache ( /var/www/own/app/var/cache/dev/ ).

**Comment by pyatnitsev** [comment]
I tried to remove all cache directories, but after composer install I've got error anyway =(

**Comment by xabbuh** [comment]
Can you show the output of `composer show`?

**Comment by pyatnitsev** [comment]
Problem on my side, sorry.

**Comment by pyatnitsev** [comment]
`bacon/bacon-qr-code                 2.0.0              BaconQrCode is a QR code generator for PHP.
beberlei/doctrineextensions         v1.2.3             A set of extensions to Doctrine 2 that add support for additional query functions available in MySQL and Oracle.
clue/stream-filter                  v1.4.1             A simple and modern approach to stream filtering in PHP
dasprid/enum                        1.0.0              PHP 7.1 enum implementation
doctrine/annotations                v1.8.0             Docblock Annotations Parser
doctrine/cache                      1.9.1              PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                1.6.4              PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     v2.11.0            PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces,...
doctrine/data-fixtures              1.4.0              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.10.0            Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            2.0.0              Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle   3.3.0              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle 2.1.2              Symfony DoctrineMigrationsBundle
doctrine/event-manager              1.1.0              The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                  1.3.1              Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.3.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.2.0              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 2.2.0              PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes t...
doctrine/orm                        v2.7.0             Object-Relational-Mapper for PHP
doctrine/persistence                1.2.0              The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 v1.0.0             Doctrine Reflection component
easycorp/easy-log-handler           v1.0.9             A handler for Monolog that optimizes log messages to be processed by humans instead of software. Improve your productivity with logs that are easy to understand.
egulias/email-validator             2.1.11             A library for validating emails against several RFCs
endroid/qr-code                     3.7.2              Endroid QR Code
endroid/qr-code-bundle              dev-master 4cf6dd4 Endroid QR Code Bundle
geocoder-php/common-http            4.2.0              Common files for HTTP based Geocoders
geocoder-php/host-ip-provider       4.0.1              Geocoder HostIp adapter
geocoder-php/ipstack-provider       0.1.0              Geocoder Ipstack adapter
geocoder-php/plugin                 1.1.0              Plugins to Geocoder providers
guzzlehttp/guzzle                   6.4.1              Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1             Guzzle promises library
guzzlehttp/psr7                     1.6.1              PSR-7 message implementation that also provides common utility methods
jdorn/sql-formatter                 v1.2.17            a PHP SQL highlighting library
jean85/pretty-package-versions      1.2                A wrapper for ocramius/package-versions to get pretty versions strings
khanamiryan/qrcode-detector-decoder 1.0.2              QR code decoder / reader
knplabs/knp-components              v2.2.1             Knplabs component library
knplabs/knp-paginator-bundle        v4.1.0             Paginator bundle for Symfony to automate pagination and simplify sorting and other features
knpuniversity/oauth2-client-bundle  v1.30.1            Integration with league/oauth2-client to provide services
league/oauth2-client                2.4.1              OAuth 2.0 Client Library
league/oauth2-google                3.0.2              Google OAuth 2.0 Client Provider for The PHP League OAuth2-Client
monolog/monolog                     2.0.1              Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/php-enum                    1.7.2              PHP Enum implementation
nikic/php-parser                    v4.3.0             A PHP parser written in PHP
nyholm/psr7                         1.2.1              A fast PHP7 implementation of PSR-7
ocramius/package-versions           1.5.1              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.2.3              A library providing utilities to generate, instantiate and generally operate with Object Proxies
php-http/client-common              2.1.0              Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                  1.7.0              Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter            v2.0.1             Guzzle 6 HTTP Adapter
php-http/httplug                    v2.0.0             HTTPlug, the HTTP client abstraction for PHP
php-http/httplug-bundle             1.16.0             Symfony integration for HTTPlug
php-http/logger-plugin              1.1.0              PSR-3 Logger plugin for HTTPlug
php-http/message                    1.8.0              HTTP Message related tools
php-http/message-factory            v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/promise                    v1.0.0             Promise used for asynchronous HTTP requests
php-http/stopwatch-plugin           1.2.0              Symfony Stopwatch plugin for HTTPlug
phpdocumentor/reflection-common     2.0.0              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.2              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         1.0.1              A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                           1.0.1              Common interface for caching libraries
psr/container                       1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-client                     1.0.0              Common interface for HTTP clients
psr/http-factory                    1.0.1              Common interfaces for PSR-7 HTTP message factories
psr/http-message                    1.0.1              Common interface for HTTP messages
psr/link                            1.0.0              Common interfaces for HTTP links
psr/log                             1.1.2              Common interface for logging libraries
psr/simple-cache                    1.0.1              Common interfaces for simple caching
ralouphie/getallheaders             3.0.3              A polyfill for getallheaders.
sensio/framework-extra-bundle       v5.5.1             This bundle provides a way to configure your controllers with annotations
sentry/sentry                       1.10.0             A PHP client for Sentry (http://getsentry.com)
sentry/sentry-symfony               2.3.0              Symfony integration for Sentry (http://getsentry.com)
swiftmailer/swiftmailer             v6.2.3             Swiftmailer, free feature-rich PHP mailer
symfony/amqp-pack                   v1.0.12            A pack for using the AMQP transport with Symfony Messenger
symfony/asset                       v5.0.0             Symfony Asset Component
symfony/browser-kit                 v5.0.0             Symfony BrowserKit Component
symfony/cache                       v4.4.0             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts             v2.0.0             Generic abstractions related to caching
symfony/config                      v4.4.0             Symfony Config Component
symfony/console                     v4.4.0             Symfony Console Component
symfony/css-selector                v5.0.0             Symfony CssSelector Component
symfony/debug                       v4.4.0             Symfony Debug Component
symfony/debug-bundle                v5.0.0             Symfony DebugBundle
symfony/debug-pack                  v1.0.7             A debug pack for Symfony projects
symfony/dependency-injection        v4.4.0             Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.4.0             Symfony Doctrine Bridge
symfony/dom-crawler                 v5.0.0             Symfony DomCrawler Component
symfony/dotenv                      v5.0.0             Registers environment variables from a .env file
symfony/error-handler               v4.4.0             Symfony ErrorHandler Component
symfony/event-dispatcher            v4.4.0             Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v1.1.7             Generic abstractions related to dispatching event
symfony/expression-language         v5.0.0             Symfony ExpressionLanguage Component
symfony/filesystem                  v4.4.0             Symfony Filesystem Component
symfony/finder                      v4.4.0             Symfony Finder Component
symfony/flex                        v1.4.8             Composer plugin for Symfony
symfony/form                        v4.4.0             Symfony Form Component
symfony/framework-bundle            v4.3.8             Symfony FrameworkBundle
symfony/http-client                 v4.3.0             Symfony HttpClient component
symfony/http-client-contracts       v1.1.8             Generic abstractions related to HTTP clients
symfony/http-foundation             v4.4.0             Symfony HttpFoundation Component
symfony/http-kernel                 v4.4.0             Symfony HttpKernel Component
symfony/inflector                   v5.0.0             Symfony Inflector Component
symfony/intl                        v5.0.0             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle                v1.14.3            Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                   v4.3.8             Symfony Messenger Component
symfony/mime                        v5.0.0             A library to manipulate MIME messages
symfony/monolog-bridge              v5.0.0             Symfony Monolog Bridge
symfony/monolog-bundle              v3.5.0             Symfony MonologBundle
symfony/options-resolver            v4.4.0             Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.7             A pack for the Doctrine ORM
symfony/phpunit-bridge              v5.0.0             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.12.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn           v1.12.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring           v1.12.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.12.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73              v1.12.0            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                     v5.0.0             Symfony Process Component
symfony/profiler-pack               v1.0.4             A pack for the Symfony web profiler
symfony/property-access             v4.4.0             Symfony PropertyAccess Component
symfony/property-info               v5.0.0             Symfony Property Info Component
symfony/psr-http-message-bridge     v1.2.0             PSR HTTP message bridge
symfony/routing                     v4.4.0             Symfony Routing Component
symfony/security-bundle             v4.3.8             Symfony SecurityBundle
symfony/security-core               v4.4.0             Symfony Security Component - Core Library
symfony/security-csrf               v4.4.0             Symfony Security Component - CSRF Library
symfony/security-guard              v4.4.0             Symfony Security Component - Guard
symfony/security-http               v4.4.0             Symfony Security Component - HTTP Integration
symfony/serializer                  v5.0.0             Symfony Serializer Component
symfony/serializer-pack             v1.0.2             A pack for the Symfony serializer
symfony/service-contracts           v2.0.0             Generic abstractions related to writing services
symfony/stopwatch                   v4.4.0             Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.4.0             Symfony SwiftmailerBundle
symfony/test-pack                   v1.0.6             A pack for functional and end-to-end testing within a Symfony app
symfony/translation                 v4.4.0             Symfony Translation Component
symfony/translation-contracts       v2.0.0             Generic abstractions related to translation
symfony/twig-bridge                 v4.4.0             Symfony Twig Bridge
symfony/twig-bundle                 v4.3.8             Symfony TwigBundle
symfony/validator                   v5.0.0             Symfony Validator Component
symfony/var-dumper                  v4.4.0             Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v5.0.0             A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                    v5.0.0             Symfony WebLink Component
symfony/web-profiler-bundle         v4.3.8             Symfony WebProfilerBundle
symfony/web-server-bundle           v4.4.0             Symfony WebServerBundle
symfony/yaml                        v4.4.0             Symfony Yaml Component
twig/twig                           v2.12.2            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.5.0              Assertions to validate method input/output with nice error messages.
willdurand/geocoder                 4.2.1              Common files for PHP Geocoder
willdurand/geocoder-bundle          5.9.2              Integration of Geocoder into Symfony
zendframework/zend-code             3.4.0              Extensions to the PHP Reflection API, static code scanning, and code generation
zendframework/zend-eventmanager     3.2.1              Trigger and listen to events within a PHP application`

**Comment by christhomas** [comment]
> Problem on my side, sorry.

can you elaborate what the problem was? cause I'm having the same problem now
