### ISSUE TITLE
Redis Session Handler - Multiple Host DSN

### ISSUE THREAD

**Issue by WhiteRabbitDE** [symfony/symfony#34477]
Hello everyone!

https://github.com/symfony/symfony/pull/34177 says we can now use DSNs for configuring the session handler. For me, it works fine when using a single Redis server. But what if i try to use multiple servers ? I copied a example dsn from the cache component which looks like this :

` 'redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1'`

or in the yaml

`  handler_id:  'redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1'`

This causes an error because "redis:?" is not proccessed as a redis dsn. 

Is my configuration wrong or is this a bug in the implementation ?

Thanks in advance !

**Comment by nicolas-grekas** [comment]
Looks like something we forgot about (we check for redis:// and not only for redis: isn't it?)

PR welcome to fix the issue (the patch attached to #34177 should be a good start to know where the code needs to be adjusted.)

**Comment by WhiteRabbitDE** [comment]
Yes, thats what i thought when looking into the class. Should be easily fixed, i will test that tomorrow and create a PR.

**Comment by panslaw** [comment]
@WhiteRabbitDE @nicolas-grekas The same should be done in https://raw.githubusercontent.com/symfony/lock/master/Store/StoreFactory.php for lock component
