### ISSUE TITLE
Tests are missing in the Composer dist package

### ISSUE THREAD

**Issue by brusch** [symfony/symfony#34486]
**Symfony version(s) affected**: 4.4.0

**Description**  
Tests are missing when installing Symfony via Composer. 
Example: https://github.com/symfony/symfony/tree/v4.4.0/src/Symfony/Component/Cache/Tests

**How to reproduce**  
Download dist package from GitHub, extract and look for the tests in the caching component. 
https://github.com/symfony/symfony/archive/v4.4.0.zip

**Comment by stloyd** [comment]
It's not issue, it desired move: https://github.com/symfony/symfony/pull/33579
