### ISSUE TITLE
[PHPUnitBridge] composer update ignores extra.symfony.require setting

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#34484]
**Symfony version(s) affected**: 4.4.0

**Description**  
When doing a composer update with extra.symfony.require set to 4.4.*, I get the following output

`Updating symfony/phpunit-bridge (v4.3.8 => v5.0.0)`

all other symfony packages (in that project) are correctly updated to 4.4.0

**How to reproduce**  
```
  "require-dev": {
    "symfony/phpunit-bridge": "*"
  },
  "extra": {
    "symfony": {
      "allow-contrib": false,
      "require": "4.4.*"
    }
  }
```

**Comment by nicolas-grekas** [comment]
that's normal: the bridge is not part of symfony/symfony "replace" section, which is the one that lists packages affected by extra.symfony.require
