### ISSUE TITLE
[Workflow] State machine is blocked by marking

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#34489]
**Symfony version(s) affected**: encountered on 4.3

We have a state machine with some transition having multiple "froms":

```yaml
do-it:
  from: [A, B]
  to: C
```

Then we have a guard event for this transition, at this point the current marking is e.g. *A*.

We add a transition blocker.

During `apply` we see `The marking does not enable the transition.`, where our custom "explanation" from the transition blocker was expected.

I think a bug lies in

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Workflow/Workflow.php#L257-L278

Our current place is "A", but it expects A and B to be set in the marking :thinking:

Is this something Petri net specific still?

cc @lyrixx  :) maybe im missing it.

**Comment by xabbuh** [comment]
This looks expected to me. If you specify multiple froms, the workflow needs to be in all of them in order to be able to apply the transition. For your case it seeems to me that using two transitions would be the solution.

**Comment by ro0NL** [comment]
Im not sure, the graph is correctly generated (nor did we get any compile errors for invalid workflow config :thinking: )

Looking at https://symfony.com/doc/current/workflow/workflow-and-state-machine.html#state-machines

For our business im not sure we can split 1 transition into 2, as we allow `A > C` and `B > C` which is both the "to-b" transition.

**Comment by ro0NL** [comment]
The docs demo this usecase as well. Now looking at

https://github.com/symfony/symfony/blob/dab6732f3917deb4944375c284ea43e14f9f52c5/src/Symfony/Component/Workflow/Tests/StateMachineTest.php#L86-L108

ref https://github.com/symfony/symfony/issues/28432

This works as expected, but `apply($subject, 't1')` gives the wrong transition blocker list in `NotEnabledTransitionException` (not tested if `can` works as expected though).

**Comment by lyrixx** [comment]
Hello, Could you give me a reproducer ? Thanks

**Comment by ro0NL** [comment]
Hi @lyrixx here's a failing test (based on current master): https://github.com/ro0NL/symfony/commit/fbe0a5a26cb1708e92019fee5c9d578abecbeb16

invocation

```
$ ./phpunit src/Symfony/Component/Workflow/Tests/StateMachineTest.php --filter=testBuildTransitionBlockerListReturnsExpectedReasonOnBranchMerge
#!/usr/bin/env php
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Testing Symfony\Component\Workflow\Tests\StateMachineTest
F                                                                   1 / 1 (100%)

Time: 109 ms, Memory: 6.00 MB

There was 1 failure:

1) Symfony\Component\Workflow\Tests\StateMachineTest::testBuildTransitionBlockerListReturnsExpectedReasonOnBranchMerge
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Transition blocker of place a'
+'The marking does not enable the transition.'

/home/roland/dev/symfony/var/symfony-src/src/Symfony/Component/Workflow/Tests/StateMachineTest.php:107

FAILURES!
Tests: 1, Assertions: 4, Failures: 1.
```

i figured the bug(?) lies in `apply`, as we get the same transition name twice, and the last one is blocked by marking, which is the list we keep using.

**Comment by lyrixx** [comment]
Thanks for the reproducer. I was able to find and fix the issue. I did not applied the same conditions between the `buildTransitionBlockerList()` and the `apply()` method. 

I reused your tests :+1: and I make theme passed.
