### ISSUE TITLE
[Translator] Upgrading translation package from 4.3.8 to 4.4.0 breaks dependency on translation contract interfaces

### ISSUE THREAD

**Issue by jcakokorev** [symfony/symfony#34482]
**Description**  
Upgrading translation package from 4.3.8 to 4.4.0 breaks dependency on contract interfaces.

`Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) `

**How to reproduce**  
Upgrade [symfony/translation](https://github.com/symfony/translation) to 4.4.0

**Possible Solution**  
Adding correct implementation of methods [symfony/translation-contracts](https://github.com/symfony/translation-contracts) (v2.0) in [symfony/translation](https://github.com/symfony/translation) (v4.4.0)

**Comment by xabbuh** [comment]
Which version of PHP do you use?

**Comment by jcakokorev** [comment]
@xabbuh  PHP version:  7.3.9

**Comment by xabbuh** [comment]
Are you sure? PHP 7.3 should be able to deal with this (see https://3v4l.org/WQhqq).

**Comment by derogithub** [comment]
PHP 7.1.29,  "laravel/framework": "5.8.*". same exception.
change composer.json, require "symfony/translation-contracts": "^1.1.6" is ok.

**Comment by xabbuh** [comment]
@derogithub How did you end up with `symfony/translation-contracts` version 2 when using PHP 7.1.29? Version 2 requires PHP 7.2.5 or higher (for the 2.0 release PHP even has to be 7.2.9 or higher)?

**Comment by derogithub** [comment]
> @derogithub How did you end up with `symfony/translation-contracts` version 2 when using PHP 7.1.29? Version 2 requires PHP 7.2.5 or higher (for the 2.0 release PHP even has to be 7.2.9 or higher)?

sorry,my fault ,composer on the server which php version is 7.3.8, deploy on the server which php version is  7.1.29

**Comment by jcakokorev** [comment]
@xabbuh my bad, i have different PHP version for bash console (7.3.9) and server (7.1.9). After updating sever version to 7.3 everything is ok now. Thanks

**Comment by xabbuh** [comment]
Thanks for the feedback, let's close here then.

**Comment by mallahsoft** [comment]
i got the same error 

i solved it  by add 
```
"symfony/translation": "4.3.8"
```
to my composer.json file 

and then run 
` composer update ` 

every thing work good after that

**Comment by rsaylor73** [comment]
My local mac is running php 7.3 and my local container is running 7.1

I found somebody else mention deleting the composer.lock then run composer install.

I found the matching php 7.1 on my local machine and ran /usr/bin/php /usr/local/bin/composer install

Issue resolved.
