### ISSUE TITLE
[VarDumper] What mean the Circumflex (^)?

### ISSUE THREAD

**Issue by rentalhost** [symfony/symfony#34494]
After update to 4.4.0 I can see a circumflex at start of dump, as following image:

![image](https://user-images.githubusercontent.com/421851/69351195-a8b0c080-0c59-11ea-9656-329481cec988.png)

I could not found any commit related to this change.

**Pre-edit:** seems related to #31446 and f0a59d3eabcd29709f6c2a11fe73e0a78728f67e, but I still can't understand what mean `^` here (I am using the web version of dump).

**Comment by ogizanagi** [comment]
It's just an handy, uncluttering link to the source code (the path a which the `dump` function was called from).
However, where do you see this on web ?

**Comment by rentalhost** [comment]
@ogizanagi I am using Laravel `dd()`.

![image](https://user-images.githubusercontent.com/421851/69364530-42379c80-0c71-11ea-83e8-6debe7c9188f.png)

Additionally, pinging author also: @ktherage

**Comment by javiereguiluz** [comment]
@rentalhost we recently had a discussion about this because some of us thought it was not clear enough (see #34256). We decided to not change it for now and see how do people use it and understand once they start seeing it. So, let's close for now. Thanks!

**Comment by dkarlovi** [comment]
@javiereguiluz The fact this issue was open hints that the DX issue you pointed out in #34256 wasn't baseless.

**Comment by ogizanagi** [comment]
What I don't understand here is that this issue is about dumps rendered in a web context. AFAIK, the `^` is only available in CLI, the original issue being these dumps in CLI didn't show their location, whereas HTML ones already did.

So is the Laravel helper using the CLI dumper instead of the HTML one somehow, or did I missed something?

**Comment by nicolas-grekas** [comment]
@rentalhost maybe this should be reported to the package that is responsible for generating this page? @ogizanagi is right, but this looks like a maybe bad usage of the component (or a bug on our side, but right now I've no clue about that.)

**Comment by rentalhost** [comment]
@nicolas-grekas I will report it, but I do not think that it is related to Laravel, once that the web version is generated correctly except by add `^`. And I belive that is related to a [static code](https://github.com/symfony/symfony/commit/f0a59d3eabcd29709f6c2a11fe73e0a78728f67e#diff-b7da1fbb4f32889387b2e3ff85ff9365R302) that is not managed by user itself.

Laravel issue: https://github.com/laravel/framework/issues/30684

**Comment by nicolas-grekas** [comment]
Oh, OK. Here is the issue: dump() should never be used as part of a regular rendering job. It's ONLY meant as a debugging tool. If you want to dump values (like in your screenshot), you should use the classes provided by the component instead.

**Comment by rentalhost** [comment]
@nicolas-grekas yes, I know. This topic is only related to "what mean the ^", because it is not clear.

**Comment by nicolas-grekas** [comment]
OK, so this has been answered. I think the Laravel issue can be closed also: everything is as expected.
