### ISSUE TITLE
The "twig.exception_controller" configuration key has been deprecated in Symfony 4.4, set it to "null" and use "framework.error_controller" configuration key instead.

### ISSUE THREAD

**Issue by leoborel** [symfony/symfony#34493]
Since I updated Symfony to 4.4, i got this deprecation ...

![deprecation](https://user-images.githubusercontent.com/38795368/69344662-0a7c2500-0c70-11ea-828a-c99248b872eb.PNG)

**Comment by xabbuh** [comment]
Making the suggested changes does not help?

**Comment by leoborel** [comment]
@xabbuh I'm a newbie so I didn't found where can I making the suggested changes ... I tried to make changes in Symfony\Bundle\TwigBundle\DependencyInjection\Configuration.php but it didn't works :(

**Comment by mdeglas** [comment]
@leoborel you need to check the file [UPGRADE-4.4.md](https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md) and find the part **twigBundle**

**Comment by leoborel** [comment]
@mdeglas Oh ! I did not know that this kind of doc exists! Thanks !

**Comment by jochendaum** [comment]
UPGRADE-4.4.md is now at https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md
