### ISSUE TITLE
[Messenger] AutoSetup option (false) for doctrine transport is not being taken into account when running setup command

### ISSUE THREAD

**Issue by cardillomarcelo** [symfony/symfony#34499]
**Symfony version(s) affected**: 4.4.0

**Description**  
The auto_setup option is not used in Symfony\Component\Messenger\Transport\Doctrine\Connection#setup(), it is only set to false before returning from the method, thus the table is created even tho the option can be set to false.

**Comment by ogizanagi** [comment]
The auto_setup options means the transport will setup automatically the required stuff (the schema here) when consuming the connection, if not already setup.
So the methods using this flag are actually the ones requiring to access the database schema for the first time, e.g: `\Symfony\Component\Messenger\Transport\Doctrine\Connection::get()`.

`Connection::setup` does no need to consume this flag. Calling the setup command should always setup the transport, regardless of this flag, right?

**Comment by cardillomarcelo** [comment]
Well, I think at least it might be a bit confusing, what if for example I wanted to take care of creating the table myself for a specific transport and use the command for the rest?

**Comment by ogizanagi** [comment]
You can call the setup command for each transport but the one you want to create yourself. Or simply create  it yourself beforehand. Then calling the setup command would have no effect, right?

**Comment by cardillomarcelo** [comment]
Makes sense. Thanks for your input!
