### ISSUE TITLE
composer require twig-bundle: Installation problems

### ISSUE THREAD

**Issue by DaedalusWings** [symfony/symfony#34500]
**Symfony version(s) affected**: 4.11.0

**Description**  
Cannot install Twig-bundle with `composer require twig-bundle`

**How to reproduce**  
During completing a CRUD Symfony tutorial, I need twig for rendering views. 
But after executing `composer require twig-bundle` in the terminal (macOS Mojave 10.14.6).
I get this message:
![Bildschirmfoto 2019-11-21 um 22 53 57](https://user-images.githubusercontent.com/5040277/69380034-e6d9ce80-0cb1-11ea-867d-c1c6fd1936fb.png)

**Possible Solution**  
I tried to update my PHP version 7.1.23 to PHP 7.2 following this manual:
https://jasonmccreary.me/articles/upgrade-php-mac-os-x/

Oddly enough, when i execute `export PATH=/usr/local/php5/bin:$PATH` in the terminal and look after my actual PHP version using `php -v`, i get the new PHP version 7.2.21
![Bildschirmfoto 2019-11-21 um 22 59 55](https://user-images.githubusercontent.com/5040277/69380556-f9083c80-0cb2-11ea-97f2-df9b4bd51b29.png)

Any ideas how to install twig?

**Additional info**
![grafik](https://user-images.githubusercontent.com/5040277/69380819-9e231500-0cb3-11ea-9420-7b515276db54.png)
![grafik](https://user-images.githubusercontent.com/5040277/69380861-b4c96c00-0cb3-11ea-9a9d-6cdf26034c56.png)

**Comment by abdounikarim** [comment]
Hello, on your composer.json file, did you try to update the php version ? 

Cheers 😉

**Comment by DaedalusWings** [comment]
No, i do not know how. Just update `"php": "^7.1.3",` to `"php": "^7.2.0",` in the composer.json file?

Meanwhile, i did a workaround. I installed a prior version of twig:
`composer require "twig/twig:^2.0"`
and then run:
`composer require twig-bundle`
It works for me.

I spend so much time fixing this problem for me, so I try your solution next time. 
Thanks for the fast reply. 😄

**Comment by abdounikarim** [comment]
You're welcome, you can close this issue for now.
