### ISSUE TITLE
Bug Migration with Symfony 4.4

### ISSUE THREAD

**Issue by AlexandrePetrone** [symfony/symfony#34503]
**Symfony version(s) affected**: 4.4

**Description**  
When I launch make:migration after create a relation, Doctrine doesn't see the modification.

**How to reproduce**  
* Create a new project Symfony on version 4.4
* Create an Entity Article with title and slug fields (string, 255)
* Make a migration and doctrine:migrations:migrate
* Create an Entity Category with title and slug fields (string, 255)
* Make a migration and doctrine:migrations:migrate
* Update Article Entity with command line an add a ManyToMany relation between Article and Category 
* Try a migration 

At this moment the command line return : [WARNING] No database changes were detected.   

The same process on 4.3 project work.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/issues/688
