### ISSUE TITLE
Declaration of TranslatorInterface::setLocale($locale) must be compatible with LocaleAwareInterface::setLocale(string $locale)

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony#34506]
**Symfony version(s) affected**: "^4.3.4"

```
"name": "symfony/translation-contracts",
            "version": "v2.0.0",
```

**Description**  
```
   "message": "Declaration of Symfony\\Component\\Translation\\TranslatorInterface::setLocale($locale) must be compatible with Symfony\\Contracts\\Translation\\LocaleAwareInterface::setLocale(string $locale)",
        "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
        "file": "D:\\abc\\vendor\\symfony\\translation\\TranslatorInterface.php",
        "line": 24,
        "trace": []
    }
```

**Comment by shenheishe** [comment]
Same problem

**Comment by xabbuh** [comment]
It looks like you ran `composer update` with a different PHP version than the one that is used to execute the application (see also #34482).

**Comment by erlangp** [comment]
thanks @xabbuh

**Comment by shenheishe** [comment]
thanks @xabbuh

**Comment by sharik709** [comment]
Another solution is to do following 

in `Symfony/translation-contracts/composer.json` edit 
```
"require": {
        "php": "^7.2.9"
},
```
to
```
"require": {
        "php": "^7.1.3"
},
```
then add `"symfony/translation-contracts": "^1.1.6"` to `project/composer.json` after that run `composer update` it should work :)

source: https://laracasts.com/discuss/channels/laravel/installation-fresh-laravel?page=1#reply=558018

**Comment by nikankad** [comment]
@sharik709  it worked thanks!

**Comment by xabbuh** [comment]
Modifying vendor files is *never* the solution. Instead, make sure that you run `composer update` with a PHP version that is not newer than the one used to run your application or configure the target PHP version using the platform config.

**Comment by mohammed-roccomedia** [comment]
> Modifying vendor files is **never** the solution. Instead, make sure that you run `composer update` with a PHP version that is not newer than the one used to run your application or configure the target PHP version using the platform config.

can you pleas say how to update it ??

**Comment by stof** [comment]
how to update what ?

**Comment by pablolopezj** [comment]
I had the same problem, I installed php 7.3 but when I used PHPINFO it showed me an older version 7.2 so I disabled 7.2 and activated 7.3 

`sudo a2dismod php7.2`

`sudo a2enmod php7.3`

I restarted Apache and it worked for me.

**Comment by manimirzaa** [comment]
@xabbuh worked for me thanks

**Comment by nicolasvahidzein** [comment]
this is still a huge problem for me
i'm using php version 7.3

i get this error:

 Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale
 ($locale) must be compatible with Symfony\Contracts\Translation\LocaleAware
 Interface::setLocale(string $locale)

**Comment by xabbuh** [comment]
Please use one of the [support channels](https://symfony.com/support) if you need help using Composer or with configuring your system. Thank you for understanding.

**Comment by nicolasvahidzein** [comment]
Everyone here is having this same problem. It would make more sense to help us fix it here so everyone can be updated. This is a big problem.

**Comment by nicolas-grekas** [comment]
The reason has been given by @xabbuh above.
