### ISSUE TITLE
[FrameworkBundle] Upgrade path for multiple clients in WebTestCase?

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#34507]
**Symfony version(s) affected**: 4.4.0

**Description**  
In Symfony 4.4/5.0 creating multiple `WebTestCase` clients is deprecated/forbidden. The docs however don't mention anything about it and I don't see any other way of creating multiple clients. What would be the recommended upgrade path?

https://symfony.com/doc/current/testing/insulating_clients.html

This examples throw an exception in SF 5.0

**How to reproduce**  
Just follow the https://symfony.com/doc/current/testing/insulating_clients.html docs

This changes were commited in #32056

**Comment by acasademont** [comment]
From what I can see, the example in the docs should be changed to this?

```php
// ...
use Symfony\Component\HttpFoundation\Response;

$harry = static::createClient();
static::ensureKernelShutdown()
$sally = static::createClient();

$harry->request('POST', '/say/sally/Hello');
$sally->request('GET', '/messages');

$this->assertEquals(Response::HTTP_CREATED, $harry->getResponse()->getStatusCode());
$this->assertRegExp('/Hello/', $sally->getResponse()->getContent());
```

**Comment by xabbuh** [comment]
Can you explain what you would like to achieve/what problem you try to solve for which you need two clients at the same time?

**Comment by acasademont** [comment]
I'm simulating an e2e test with some interaction between an "admin" client and a "normal" one

**Comment by acasademont** [comment]
I see 2 different cases here:

- Non-insulating clients: In this case, we just need another client/browser with different parameters, it should be fine to reuse the same Kernel, the `createClient` shouldn't attempt to boot another Kernel, just create another client, as the name implies.

- Insulating clients: Here we need indeed another Kernel in a separate PHP process. 

IMHO the `createClient` needs a bit of a rework to better accomodate these 2 different use cases?

**Comment by glhms** [comment]
```
protected function setUp()
{
    $this->client = self::createClient();
}
public function test1{}
public function test2{}
```
I just want to use a fresh new client in my tests.

If I create 2 test, setUp() creates 2 kernel (one for every test) and throws errors.

**Comment by acasademont** [comment]
@glhms your case is weird, in theory the Kernel is automatically shut down after every test in the `tearDown` method of `KernelTestCase`

**Comment by nCrazed** [comment]
Running into same problem while testing interaction between different users/roles.

**Comment by acasademont** [comment]
@xabbuh any ideas on how should we move this forward?

**Comment by s-duval** [comment]
Hello, running into the same problem as well, creating multiple clients to test interactions is something usual I guess.

**Comment by nicolas-grekas** [comment]
Can you check https://github.com/symfony/symfony-docs/pull/13351?

**Comment by acasademont** [comment]
@nicolas-grekas sure, it works, but it still seems a bit weird, a `self::ensureKernelShutdown` call makes it seem like there can't be more than 1 kernel at the same time, when in fact you can. But yeah, the issue can be closed.
