### ISSUE TITLE
Return value of Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector::convertToBytes() must be of the type int, float returned

### ISSUE THREAD

**Issue by tony5Dim** [symfony/symfony#34508]
**Symfony version(s) affected**: 5.0.0

**Description**  
A fresh install of Sf5 and produce that error : `Return value of Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector::convertToBytes() must be of the type int, float returned`

**How to reproduce**  
A fresh install and a `Symfony server:start`

**Possible Solution**  
In the file MemoryDataCollector.php l.110 the switch make a float and not an int. An int can be forced. A `return (int)$max;` at l.120 do the job

**Comment by fancyweb** [comment]
What is your PHP memory_limit and how is it written? I guess the int becomes a float because it goes above the maximum supported int (PHP_INT_MAX). Casting such float to int cannot work.

**Comment by xabbuh** [comment]
see #34516

**Comment by tony5Dim** [comment]
Yes this is it. PHP_INT_MAX is 2147483647 and $max 2147483648
