### ISSUE TITLE
Translation classes incompatibility

### ISSUE THREAD

**Issue by otherperspectives** [symfony/symfony#34518]
**Symfony version(s) affected**: 4.4

**Description**  
I updated my packages and now I get this error: 
 Declaration of Symfony\Component\Translation\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)

**How to reproduce**  
Install Symfony 4.4

**Comment by xabbuh** [comment]
This is not a bug. You need to run `composer update` with the same PHP version that you use to execute your application (see #34482 and #34511 for example).
