### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Invalid "af 2" locale.").

### ISSUE THREAD

**Issue by Starwox** [symfony/symfony#34510]
Symfony version: 4.3.8 

**Description**  
My problem occurs when I tried to put my form on my template with 
`{{ form(form) }}`

I can't use the cache clear of composer anymore
I had this error: 

!!    In Translator.php line 480:                       
!!    Invalid "af 2" locale. 

php bin/console cache:clear -vvv :
https://zupimages.net/viewer.php?id=19/47/o5yj.png

**How to reproduce**  
Controller: 

    public function register(Request $req, UserPasswordEncoderInterface $passwordEncoder)
    {
        $register = new Users();

        $form = $this->createForm(UserFormType::class, $register);

        $form->handleRequest($req);

        if ($form->isSubmitted() && $form->isValid())
        {
            $em = $this->getDoctrine()->getManager();

            $register->setPassword(
              $passwordEncoder->encodePassword($register, $form->get('password')->getData())
            );
            $register->setEmail($form->get('email')->getData());

            $register->setLogin($form->get('login')->getData());

            $register->setPhone($form->get('phone')->getData());

            $em->persist($register);
            $em->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('forms/register.html.twig', [
            'controller_name' => 'register',
            'form' => $form->createView()
        ]);
    }

Form:

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('login', TextType::class, [
                'label' => 'Login',
                'attr' => ['placeholder' => 'Login'],
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat password']
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => ['placeholder' => 'Email'],
            ])
            ->add('phone', IntegerType::class, [
                'label' => 'Phone',
                'attr' => ['placeholder' => 'Phone Number'],
            ])

            ->add('agreeTerms', CheckboxType::class, [
                'label' => 'Agree ?',
                'mapped' => false
            ])
            ->add('submit', SubmitType::class, ['label' => 'Submit'])
        ;
    }

Template:

    <div class="form">
        
        {{ form_start(form) }}

        
        {{ form_label(form.login) }}
        {{ form_widget(form.login) }}

        
        {{ form_label(form.password) }}
        {{ form_widget(form.password) }}

        
        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}

        
        {{ form_label(form.phone) }}
        {{ form_widget(form.phone) }}

        
        {{ form_label(form.agreeTerms) }}
        {{ form_widget(form.agreeTerms) }}

        
        {{ form_label(form.submit) }}
        {{ form_widget(form.submit) }}

        {{ form_end(form) }}
    </div>

**Possible Solution**  

So i tried to update translation:

`php bin/console translation:update --force af2`
`php bin/console translation:update --force af-2`
`php bin/console translation:update --force af_2`
`php bin/console translation:update --force "af 2"`

Doesn't work

I can't update with composer.

Thank you guys

**Comment by xabbuh** [comment]
Where is this locale coming from?

**Comment by Starwox** [comment]
He's coming from the Vendor, I renamed it, then i used `composer install`.
It resolve my problem.

**Comment by Drektilar** [comment]
HI,
I have the same bug : An exception has been thrown during the rendering of a template ("Invalid "ar 2" locale.").

Where is the Translator.php with locale ?
 Thanks a lot

**Comment by lostfocus** [comment]
I just had the same problem, manually deleting the cache and vendor directory (both, just either one of them on its own wasn't enough) and running composer install again fixed it for us.
