### ISSUE TITLE
Require "symfony/translation-contracts": "^1.1.6|^2" is throwing declaration exception

### ISSUE THREAD

**Issue by N69S** [symfony/symfony#34511]
**Symfony version(s) affected**: 4.4.0

**Description**  
On PHP 7.2.13 environment, "symfony/translation" v4.4.0 has this requirement "symfony/translation-contracts": "^1.1.6|^2"
but "symfony/translation-contracts" v2.0 has the method setLocate with the type hinting
`public function setLocale(string $locale);`
This triggers a Declaration exception of Symfony\\Component\\Translation\\TranslatorInterface::setLocale($locale)

**How to reproduce**  
PHP: 7.2.* > 7.2.3

**Possible Solution**  
Change the requirement to "symfony/translation-contracts": "^1.1.6"

**Comment by dzschille** [comment]
I have the same error. I use PHP 7.3.

**Comment by xabbuh** [comment]
see #30655

**Comment by dzschille** [comment]
@xabbuh how is the issue you mentioned connected to this one?

**Comment by N69S** [comment]
@xabbuh how is the issue #30655 relating to a dependency issue ?

**Comment by xabbuh** [comment]
The fatal error is only triggered by PHP when it is **not** PHP 7.2 or higher. This means that you ran `composer update` with a different PHP version that what is used to run your application or that you ignore platform requirements when updating dependencies. Otherwise, you would either not end up with version 2 of the contracts being installed or you wouldn't see this fatal error.

**Comment by N69S** [comment]
@xabbuh  The fatal error is triggered by PHP >= 7.2.5 which is a condition for symfony/translation-contracts v2 to be installed. Which making `Symfony\Component\Translation\TranslatorInterface` implementation of `Symfony\Contracts\Translation\LocaleAwareInterface` throw the exception.

**Comment by xabbuh** [comment]
I guess that you are accidentally not using PHP 7.2. With PHP 7.2+ you shouldn't see this error (see https://3v4l.org/WQhqq).

**Comment by N69S** [comment]
@xabbuh indeed, it is a difference between the front and cli php version. sorry for the inconvenience.

**Comment by xabbuh** [comment]
No need to worry, I also just realised that I linked the wrong issue (it should have been #34482).

**Comment by dzschille** [comment]
@xabbuh i made the mistake that my local php cli was PHP 7.3 but the docker container was running PHP 7.1. I now upgraded the container to PHP 7.3 and the error message is gone. Thanks for your help!
