### ISSUE TITLE
symfony/messenger component doesn't work after updating doctrine bundle

### ISSUE THREAD

**Issue by voodooism** [symfony/symfony#34514]
**Symfony version(s) affected**: 4.3.8

**Description**  

I use symfony/messenger component with DoctrineTransport.
After updating the dependencies via composer the **symfony/messenger** component doesn't work. It just gives this Exception:
`"message": "Argument 1 passed to Symfony\\Component\\Messenger\\Transport\\Doctrine\\DoctrineTransportFactory::__construct() must be an instance of Symfony\\Bridge\\Doctrine\\RegistryInterface, instance of Doctrine\\Bundle\\DoctrineBundle\\Registry given, called in /var/www/var/cache/dev/ContainerXGVEEUc/getMessenger_Transport_Doctrine_FactoryService.php on line 12"`

**How to reproduce**  

`composer update`

**Additional context**  

It exactly depends on the doctrine-bundle version. If I use 1.12 version everything works well

It's composer updating log

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Package operations: 2 installs, 6 updates, 1 removal
  - Removing doctrine/doctrine-cache-bundle (1.3.5)
  - Updating ocramius/package-versions (1.4.1 => 1.4.2): Loading from cache
  - Updating symfony/swiftmailer-bundle (v3.3.1 => v3.4.0): Loading from cache
  - Updating symfony/phpunit-bridge (v4.3.8 => v4.4.0): Loading from cache
  - Updating doctrine/cache (1.9.0 => 1.9.1): Loading from cache
  - Updating doctrine/doctrine-bundle (1.11.2 => 2.0.0): Loading from cache
  - Updating doctrine/orm (v2.6.4 => v2.7.0): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing graylog2/gelf-php (1.6.3): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

Symfony operations: 1 recipe (e4ddb6e6ee73a8dcb059b4ba9baec2ec)
  - Unconfiguring doctrine/doctrine-cache-bundle (>=1.3.5): From auto-generated recipe
Executing script cache:clear [OK]
Executing script assets:install public [OK]
```

**Comment by xabbuh** [comment]
It looks like this is the same as doctrine/DoctrineBundle#1062.

**Comment by floriansemm** [comment]
This issue is still a problem in Symfony 4.4.1/4.4.2 in combination with doctrine-bundle v2.0.6

**Comment by xabbuh** [comment]
@floriansemm Can you please create a new issue and provide a small example application that allows to reproduce?
