### ISSUE TITLE
Get data based on search text

### ISSUE THREAD

**Issue by tisuchi** [symfony/symfony#34529]
Hi, 

I am wondering is there any way to extract data by searching any specific text from the html?

For example, I have this code-

```
<p><strong>Study Subject:&nbsp;</strong>Fellowship&nbsp;is&nbsp;tenable in biomedical engineering at the&nbsp;University of Oslo in Norway.</p>
<p><strong>....</strong></p>
<p><strong>....</strong></p>
<p><strong>....</strong></p>
```

Is there any way to get __Fellowship&nbsp;is&nbsp; tenable in biomedical engineering at the&nbsp; the University of Oslo in Norway. __?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
