### ISSUE TITLE
Singly implemented interfaces are not being registered since v4.4 through DirectoryLoader

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#34524]
**Symfony version(s) affected**: 4.4.0

**Description**  
Consider class `A` implements interface `I`

I used to register class `A` as a service. Then I DI autowired `I`. Symfony aliased `I` automatically to `A` on container init if there was only single implementation of `A`.

This behaviour is not working since v4.4. I'm getting:

> Cannot autowire service "Service\With\Constructor": argument "$i" of method "__construct()" references interface "I" but no such service exists. You should maybe alias this interface to the existing "A" service.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue?

**Comment by simPod** [comment]
https://github.com/symfony/symfony/commit/c1f39709ffd35843d1090fab5ba17cef414e0d7b#diff-ad1ed76aba6a80df5a48dfa4585adcf3R78-R88 The bug is here.

I manually call

`$loader->registerClasses(...)` (DirectoryLoader) which also used to register interfaces. Now it throws them away.

**Comment by nicolas-grekas** [comment]
> I manually call [...] which also used to register interfaces. Now it throws them away.

Is this what you really do in your use case or is this constructed for highlighting the issue?
Can you please provide a small reproducing app?

**Comment by simPod** [comment]
@nicolas-grekas that's what I really do. Here's minified repo:

https://github.com/simPod/Symfony-SII

Master is on DI v4.4. https://github.com/simPod/Symfony-SII/tree/sf-di-4.3 is on DI v4.3.

`bin/console test` works on the later with no issues as interface is being registered.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, I now understand the issue, fixed in #34729

**Comment by simPod** [comment]
@nicolas-grekas tried upgrading to last commit on `4.4` branch and seems to be working. Thanks!
