### ISSUE TITLE
[Mailer] SMTP Authentication is not performed when using STARTTLS. 

### ISSUE THREAD

**Issue by crazy-weasel** [symfony/symfony#34522]
**Symfony version(s) affected**: 4.4.0, 5.0.0

**Description**  
Capabilities reported in EHLO after performing STARTTLS are ignored. It's possible that the AUTH-capabilitiy is only reported after the STARTTLS-command. In such situations the communication with the smtp-server would be unauthenticated, and the sending of emails would fail (in most situations).

https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php#L105

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php#L128

**How to reproduce**  
Use the mailer with an smpt-server (like postfix) using submission and STARTTLS.

**Possible Solution**  
Move `$capabilities = $this->getCapabilities($response);` after the block which starts STARTTLS and use the response from the second EHLO-command, like it was in 4.3.

**Additional context**

**Comment by cyrilverloop** [comment]
Hi,

@crazy-weasel's solution seems to work for me.

**Comment by DjLeChuck** [comment]
Hi,

Same issue here. Using the same solution, add `$capabilities = $this->getCapabilities($response);` just after the second `EHLO`, the send works.

The `AUTH` capabilities are not send in the first response.

```
      < 220 mydomain.tld ESMTP Postcow
      > EHLO [127.0.0.1]
      < 250-mydomain.tld
      < 250-PIPELINING
      < 250-SIZE 104857600
      < 250-ETRN
      < 250-STARTTLS
      < 250-ENHANCEDSTATUSCODES
      < 250-8BITMIME
      < 250-DSN
      < 250 CHUNKING
      > STARTTLS
      < 220 2.0.0 Ready to start TLS
      > EHLO [127.0.0.1]
      < 250-mydomain.tld
      < 250-PIPELINING
      < 250-SIZE 104857600
      < 250-ETRN
      < 250-AUTH PLAIN LOGIN
      < 250-AUTH=PLAIN LOGIN
      < 250-ENHANCEDSTATUSCODES
      < 250-8BITMIME
      < 250-DSN
      < 250 CHUNKING
      > MAIL FROM:<noreply@XXX>
      < 250 2.1.0 Ok
      > RCPT TO:<XXX>
      < 554 5.7.1 <XXX>: Client host rejected: Access denied
```

**Comment by lucascdsilva** [comment]
Hi @crazy-weasel 
I used this solution to connect smtp office 365

**Comment by fabpot** [comment]
Anyone willing to create a pull request?

**Comment by DjLeChuck** [comment]
I'm on it! :+1:

**Comment by DjLeChuck** [comment]
If anyone wants to help with unit testing of my PR: https://github.com/symfony/symfony/pull/34760

Thank you! :)
