### ISSUE TITLE
[ContainerLint] linting process fails when `ide` option picked under framework bundle

### ISSUE THREAD

**Issue by shieldo** [symfony/symfony#34526]
**Symfony version(s) affected**: 4.4.0, 5.0.0

**Description**  

**How to reproduce**  

1. Create a new project:

```sh
composer create-project symfony/skeleton lint_bug
```

2. Add config line to config/packages/framework.yaml

```yaml
    ide: phpstorm
```

3. run command (`bin/console lint:container`)

Expected outcome:

Command completes successfully with no output.

Actual outcome:

<img width="1311" alt="lint_output" src="https://user-images.githubusercontent.com/97280/69437639-9ad36c00-0d3b-11ea-85c4-b26df63a938b.png">

**Possible Solution**  
Not yet (but will provide info/ PR if I get a clear idea!)

However, this is to do with the parameter value containing a raw `%` character, which is then processed as if there is an embedded parameter within the value.

**Comment by fancyweb** [comment]
What an interesting bug. The XML container file we dump does not escape % for parameters since the container is not yet compiled when it is processed. Therefore, when it's read for the lint command, it cannot be processed correctly. @nicolas-grekas Let's talk about this tomorrow 😁

**Comment by ro0NL** [comment]
maybe related to #30930
