### ISSUE TITLE
[BUG] Abstract Voter class has wrong type hints? Or missing cast?

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#34532]
**Symfony version(s) affected**: 4.4

**Description**  
The methods `\Symfony\Component\Security\Core\Authorization\Voter\Voter::supports` and `\Symfony\Component\Security\Core\Authorization\Voter\Voter::voteOnAttribute` claim that the attribute is a string. However, when using `allow_if` it is actually an object of type `\Symfony\Component\ExpressionLanguage\Expression`.
This can be a problem as a third bundle might expect a string and therefore uses functions that only work with a string type and will fail.

**How to reproduce**  
Just part of the documen tation

**Possible Solution**  
Fix PHPDoc and maybe also add / adjust corresponding documentation.

**Comment by AndreasA** [comment]
Actually I just noticed that with the latest changes you even enforce string:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/Voter/Voter.php#L57

Maybe it would be more correct to convert the object value to string here:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/Voter/Voter.php#L33
instead.

**Comment by andrew-demb** [comment]
Ref #31245

**Comment by xabbuh** [comment]
closing in favour of #31245
