### ISSUE TITLE
Cannot install Symfony web server on Symfony 5

### ISSUE THREAD

**Issue by janbodnar** [symfony/symfony#34531]
**Symfony version(s) affected**: 5.0.0

**Description**  
The Symfony webserver cannot be installed. Tested on Windows 10.

**How to reproduce**  
$ composer create-project symfony/skeleton simple
$ cd simple
$ composer require server --dev
  [InvalidArgumentException]
  Could not find package symfony/web-server-bundle in a version matching 5.0.*

**Comment by xabbuh** [comment]
The WebServerBundle was deprecated in Symfony 4.3. It won't get any future releases. You can use the [Symfony CLI](https://symfony.com/download) instead.

**Comment by kouessivi** [comment]
You are need 
composer require symfony/web-server-bundle --dev ^4.4.2
