### ISSUE TITLE
[Notifier][RFC] Chatters and texters should not be transports

### ISSUE THREAD

**Issue by magnusnordlander** [symfony/symfony#34545]
I was trying to understand the notifier component in order to write documentation for it, and I'm confused by Chatters and Texters. 

I don't understand why Chatters and Texters are transports? Is there a use case where you'd want to do something like the following?

```
<?php
$notifier = new Notifier([
    new SmsChannel(new Chatter(new TwilioTransport('foo', 'bar', 'baz')))
]);

```

I'd be happy to work on a PR for this, but I would like some feedback first.

#SymfonyHackday

**Comment by wouterj** [comment]
I think the main idea is not in initialization, but in usage. You can write a class that is agnostic on how the notification is actually sent. It would be happy to accept a chatter, a texter or the high-level notifier object. This makes it somewhat easier to switch between these.

**Comment by fabpot** [comment]
The idea is that you can use Chatters and/or Texters without Notifier.
