### ISSUE TITLE
[4.4][FrameworkBundle] `lint:container` fails on fresh web-skeleton

### ISSUE THREAD

**Issue by c33s** [symfony/symfony#34559]
**Symfony version(s) affected**: 4.4.0

**Description**  
running `php bin/console lint:container` fails with the following error on a fresh symfony 4.4.99 web-skeleton project.
```
Invalid service ".debug.http_client": method "Symfony\Contracts\HttpClient\HttpClientInterface::setLogger()" does not exist.
```

**How to reproduce**  
```
composer create-project symfony/website-skeleton lint-test 4.4.99
cd lint-test
php bin/console lint:container
```

**Additional context**  
- win7x64
- php7.3.12x64nts

**Comment by dsentker** [comment]
I have got the same issue.
* Win10 x64
* php 7.3.9
