### ISSUE TITLE
[Notifier] Add a LinkedInTransport

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#34563]
**Description**  
Add a LinkedIn Transport as it's done for Slack, Twilio, Telegram...

I began to work on my side https://github.com/ismail1432/notifier-linkedin/tree/add-notifier-transport I don't know if it's should be supported by Symfony

**Comment by OskarStark** [comment]
Why not, can you create a PR?

**Comment by ismail1432** [comment]
OFC but I need a specific repository because it's related to the framework

**Comment by OskarStark** [comment]
Please have a look on other Notifier pull requests for more information and the structure.

**Comment by javiereguiluz** [comment]
Before creating this, I'd wait for more replies. This component is too new and we don't know yet the strategy for it (will we add everything proposed by the community? only some selected notifiers?)

**Comment by ismail1432** [comment]
TY :+1: 
I created a Bridge https://github.com/ismail1432/notifier-linkedin. :rocket:  It's not perfect but it's working

**Comment by fabpot** [comment]
I'm closing this issue. You can create a PR, we do have many third party providers now, so LinkedIn can be one of them as well.

**Comment by ismail1432** [comment]
thanks @fabpot I'll create a PR asap
