### ISSUE TITLE
[Webpack Encore] Attempted to load class "GenericLinkProvider" from namespace "Fig\Link". Did you forget a "use" statement for "Symfony\Component\WebLink\GenericLinkProvider"

### ISSUE THREAD

**Issue by sabruss** [symfony/symfony#34572]
**Symfony version(s) affected**:  5

**Description**  
Attempted to load class "GenericLinkProvider" from namespace "Fig\Link". Did you forget a "use" statement for "Symfony\Component\WebLink\GenericLinkProvider"

**How to reproduce** 
create new project symfony/skeleton
`composer req encore`
activate preload

```yaml
webpack_encore:
    preload: true
```
in config/package/webpack_encore.yaml

`composer req web-link` as requested by the bundle

**Possible Solution**  
change namespace from `Fig\Link` to `Symfony\Component\WebLink` in `Symfony\WebpackEncoreBundle\EventListener\PreLoadAssetsEventListener`

**Comment by nicolas-grekas** [comment]
Please report on https://github.com/symfony/webpack-encore-bundle/ (or better: send a fix :) )
/cc @weaverryan FYI

**Comment by DurandSacha** [comment]
In my case : I fixed it with `npx browserslist@latest --update-db`
