### ISSUE TITLE
[4.4][FrameworkBundle] `lint:container` fails on `Symfony\Component\Lock\Factory` with `FlockStore`

### ISSUE THREAD

**Issue by rpkamp** [symfony/symfony#34585]
**Symfony version(s) affected**: 4.4+

**Description**  
Command `lint:container` fails when type hinting for `Symfony\Component\Lock\Factory` in a service and then injecting the default `@lock.store.flock` service with the following message:
```
  Invalid definition for service "My\Custom\Service": argument 1 of "Symfony\Component\Lock\Factory::__con  
  struct" accepts "Symfony\Component\Lock\StoreInterface", "Symfony\Component\Lock\PersistingStoreInterface" passed.
```

**How to reproduce**  
1. Create a service that type hints for `Symfony\Component\Lock\Factory` in the constructor
1. Supply `@lock.store.flock` as the argument for that service
1. Run `bin/console lint:container`

**Possible Solution**  
I haven't looked at the code, but it appears that the linter assumes classes can only implement one interface, and when that interface doesn't match the expected interface it fails. If that is indeed the case the linter should be made aware that classes can implement multiple interfaces.

**Additional context**  
N/A

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce?

**Comment by rpkamp** [comment]
Sure thing, I'll create one somewhere this week.

**Comment by rpkamp** [comment]
@xabbuh project created: https://github.com/rpkamp/symfony-container-lint-lock-bug

**Comment by rpkamp** [comment]
Digging some deeper the problem appears to be that the flock store is defined as class `\Symfony\Component\Lock\PersistingStoreInterface` - which is not a class but an interface, and the type hint in `LockFactory` is for `StoreInterface`. This works fine, because `PersistingStoreInterface` extends `StoreInterface`.

However, the compilerpass doesn't pick up on this.

Modifying `\Symfony\Component\DependencyInjection\Compiler\CheckTypeDeclarationsPass::checkType` to the following solves it for me:

```
if ($value instanceof Definition) { // existing
    $class = $value->getClass();

    // added from here
    $reflectionClass = new \ReflectionClass($type);
    if ($reflectionClass->isInterface() && \in_array($class, $reflectionClass->getInterfaceNames(), true)) {
        // $type is an interface that extends $class (also an interface, but named class ...)
        return;
    }

    // more here
```

However, I'm not 100% sure it always works, and I'm also not sure it won't break other scenarios...

**Comment by xabbuh** [comment]
Thank you for the example. #34653 should fix this.

**Comment by rpkamp** [comment]
That should do it indeed :slightly_smiling_face:
