### ISSUE TITLE
Symfony 4.3 encode password failed, unable to fetch the response from the backend: unexpected EOF.

### ISSUE THREAD

**Issue by lijunhaoabroad** [symfony/symfony#34589]
**Symfony version(s) affected**: x.y.z
Symfony 4.3
**Description**  

algorithm: auto
trying to $pass=$passwordEncoder->encodePassword($user,$data['password']);
 dump($pass);die;
symfony local web server shows error:unable to fetch the response from the backend: unexpected EOF.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you please check if there is something in the logs of your application? Could you also please provide a small example application that allows to reproduce?

**Comment by lijunhaoabroad** [comment]
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class RegistrationController extends AbstractController
{
    /**
     * @Route("/register", name="register")
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function register(Request $request,UserPasswordEncoderInterface $passwordEncoder)
    {
        $form=$this->createFormBuilder()
            ->add('username')
            ->add('password',RepeatedType::class,[
                    'type' => PasswordType::class,
                    'required' => true,
                    'first_options'  => ['label' => 'Password'],
                    'second_options' => ['label' => 'Confirm Password'],
                ]
            )
            ->add('register',SubmitType::class,[
                'attr'=>[
                    'class'=>'btn btn-success float-right'
                ]
            ])
            ->getForm();

        $form->handleRequest($request);


        if($form->isSubmitted()){
            $data=$form->getData();


            $user=new User();
            $user->setUsername($data['username']);
          $pass= $passwordEncoder->encodePassword($user,$data['password']);
            dump($pass);die;
            $user->setPassword(
                $passwordEncoder->encodePassword($user,$data['password'])
            );


            $em=$this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            return $this->redirect($this->generateUrl('app_login'));
        }

        return $this->render('registration/index.html.twig', [
          'form'=>$form->createView()
        ]);
    }
}
<img width="532" alt="Screen Shot 2019-11-25 at 16 38 16" src="https://user-images.githubusercontent.com/15603606/69554442-16365700-0fa2-11ea-8eb9-59cb1a52a17c.png">
<img width="567" alt="Screen Shot 2019-11-25 at 16 38 10" src="https://user-images.githubusercontent.com/15603606/69554453-19314780-0fa2-11ea-8bc1-8d06aeff2469.png">

**Comment by lijunhaoabroad** [comment]
`<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class RegistrationController extends AbstractController
{
    /**
     * @Route("/register", name="register")
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function register(Request $request,UserPasswordEncoderInterface $passwordEncoder)
    {
        $form=$this->createFormBuilder()
            ->add('username')
            ->add('password',RepeatedType::class,[
                    'type' => PasswordType::class,
                    'required' => true,
                    'first_options'  => ['label' => 'Password'],
                    'second_options' => ['label' => 'Confirm Password'],
                ]
            )
            ->add('register',SubmitType::class,[
                'attr'=>[
                    'class'=>'btn btn-success float-right'
                ]
            ])
            ->getForm();

        $form->handleRequest($request);


        if($form->isSubmitted()){
            $data=$form->getData();


            $user=new User();
            $user->setUsername($data['username']);
          $pass= $passwordEncoder->encodePassword($user,$data['password']);
            dump($pass);die;
            $user->setPassword(
                $passwordEncoder->encodePassword($user,$data['password'])
            );


            $em=$this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            return $this->redirect($this->generateUrl('app_login'));
        }

        return $this->render('registration/index.html.twig', [
          'form'=>$form->createView()
        ]);
    }
}
`

**Comment by stof** [comment]
This looks like an issue of the Symfony local webserver here, not of the password encoder.

/cc @fabpot @tucksaun

**Comment by tucksaun** [comment]
There's a segfault in PHP, probably something related to libsodium or libargon if it only happens during password check.

**Comment by lijunhaoabroad** [comment]
> There's a segfault in PHP, probably something related to libsodium or libargon if it only happens during password check.

So you mean, changing algorithm:auto to algorithm: bcrypt in security.yaml, which can fix that?

**Comment by tucksaun** [comment]
@lijunhaoabroad no it means your local PHP installation has probably some issues.
I personally had the same issue on macOS, upgrading `libsodium` fixed it.

**Comment by nicolas-grekas** [comment]
Which versions of libsodium are affected and which ones work?

**Comment by tucksaun** [comment]
AFAIK, this is more a build issue than a bug in libsodium (as my version remained 1.0.18 after upgrade)

**Comment by apfelbox** [comment]
I think you are calling the method the wrong way, that's why libsodium crashes (or sth else). You are calling:

```php
$pass = $passwordEncoder->encodePassword($user, $data['password']);
// (with $user probably being an object / entity)
```

but instead you should just call:

```php
$pass = $passwordEncoder->encodePassword($data['password']);
```

**Comment by lijunhaoabroad** [comment]
> @lijunhaoabroad no it means your local PHP installation has probably some issues.
> I personally had the same issue on macOS, upgrading `libsodium` fixed it.

Last night I changed auto to argon2i, and the local server works. It definitely has something wrong with libsodium with php on mac. I think u helped me fix my problem. This issue can be closed..... thank you.

**Comment by edvaldotorres** [comment]
Hello, can anyone help me with this same problem on mac M1 Air Sonoma 14.0

**Comment by mahesame** [comment]
> Hello, can anyone help me with this same problem on mac M1 Air Sonoma 14.0

Hallo @edvaldotorres, I just face this issue in Sonoma and solve this. To solve this EOF problem, first find php.ini location by executing 'php --ini', and then after that inside of php.ini, change 'output_buffering' value from 4096 to 65535. Next, restart the Symfony server and the problem will be disappeared. It worked for me.
