### ISSUE TITLE
4.4 and MongoDB ODM DoctrineType

### ISSUE THREAD

**Issue by Romaxx** [symfony/symfony#34581]
**Symfony version(s) affected**: 4.4 (4.3 was ok)

**Description**  
Argument 1 passed to Symfony\Bridge\Doctrine\Form\Type\DoctrineType::getQueryBuilderPartsForCachingHash() must be an instance of Doctrine\ORM\QueryBuilder, instance of Doctrine\ODM\MongoDB\Query\Builder given, called in /usr/local/www/vendor/symfony/doctrine-bridge/Form/Type/DoctrineType.php on line 125

**How to reproduce**  
Create FormType with ODM entity extending DoctrineType

**Comment by xabbuh** [comment]
see #34600 for the fix
