### ISSUE TITLE
[RFC] Basic documentation required for new components before release

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#34588]
**Description**  
It's always exciting to try out new components - such as the Symfony Notfier. In the Github repository the [link to the documentation is dead](https://github.com/symfony/notifier), and the [homepage docs](https://symfony.com/components/Notifier) explains only the installation via Composer (which seems auto-generated). Especially at this stage, it would be important to encourage as many developers as possible to test and try out the new component. However, lacking sufficient documentation eliminates the motivation to test undocumented features.

I have already noticed this publication behavior with other new components.

Would not it be correct, together with the Beta Relase of a component, to update the documentation (obligatory)?

**Comment by nicolas-grekas** [comment]
"Obligatory" means someone must enforce the obligation. That's not how open-source dynamics work as you might know.

I would encourage you to contribute some documentation if you want. Or just be patient.
