### ISSUE TITLE
[HttpKernel] Multiple container dumps when executing functional tests after clearing cache

### ISSUE THREAD

**Issue by casanova922** [symfony/symfony#34595]
**Symfony version(s) affected**:
4.4.0
5.0.0

**Description**  
When executing functional tests in Symfony 4.4 and 5.0, a new container initialization and dump is done for each test. This makes the overall test suite take a lot more time to complete (we have approximately 300 test running in our CI and it breaks the 1 hour limit when before it was taking no more than 14 minutes), in previous versions it was working fine. After the first time executing the tests (and if no change has been made that could cause a new container dump), it continues to work correctly.

This seems to be caused by the changes introduced in this commit: 7f9556ce1931a4021a320ef688247f846b87d2b5

For what I can see, as now the cache is checked only once per process, it keeps being not fresh even though a new container has already been initialized.

**How to reproduce**  
This problem can be reproduced using the demo Symfony application (upgrading it to v4.4.0).

**Possible Solution**  
The easier solution would be to mark the cache as fresh just after dumping the container here:

https://github.com/symfony/symfony/blob/7719fc709e6d5f5d44d15417b0ff132c4ee39a3f/src/Symfony/Component/HttpKernel/Kernel.php#L553-L555

**Comment by Devristo** [comment]
See https://github.com/symfony/symfony/issues/34567

**Comment by casanova922** [comment]
Missed that, sorry!

Closing this then.
