### ISSUE TITLE
Twig/extension install impossible

### ISSUE THREAD

**Issue by wolpheus** [symfony/symfony#34590]
Hi,
On Symfony 5, error compatibility version with twig/extensions.
composer require twig/extensions
Nice list 

Regards..

**Comment by abdounikarim** [comment]
Hello @wolpheus , as i see, this package was abandoned as said here : 
https://packagist.org/packages/twig/extensions

Can you try with the new package ? 

Cheers 😉

**Comment by wolpheus** [comment]
Ha, ok ...
I’m starting a project again that was with version 4.3 that I started a month ago.
I take advantage that the project is not too big to put it with version 5 and I put filled in via the documentation:
https://symfony.com/doc/current/templating/twig_extension.html
So I had no idea there was another version.

Thank you for your answer,
Very cordially
