### ISSUE TITLE
The translation:update command fails in 4.4.0 due to missing optional Twig filters

### ISSUE THREAD

**Issue by sarcher** [symfony/symfony#34618]
**Symfony version(s) affected**: 4.4.0

**Description**  
Running the translation extraction/update command that worked in Symfony 4.3.x produces the following error after upgrading to 4.4.0, with no other changes:
```
  [Twig\Error\SyntaxError]            
  Unknown "markdown_to_html" filter.
```

This uncovers two other missing Twig filters, `inky_to_html` and `inline_css`, all of which are optional so not included in Twig by default.

**How to reproduce**  
Run the following command without the optional Twig extensions installed:
`bin/console translation:update --force --output-format=xlf en`

**Possible Solution**  
This can be worked around by adding optional Twig dependencies:
```
composer require twig/extra-bundle twig/markdown-extra twig/inky-extra twig/cssinliner-extra
```

**Additional context**  
The errors are from the following files which the translation command is picking up as they are Twig templates:
```
/vendor/symfony/twig-bridge/Resources/views/Email/zurb_2/notification/content_markdown.html.twig
/vendor/symfony/twig-bridge/Resources/views/Email/zurb_2/notification/body.html.twig
```

These are the component versions from `composer show`:
```
symfony/twig-bridge                 v4.4.0             Symfony Twig Bridge
symfony/twig-bundle                 v4.4.0             Symfony TwigBundle
twig/twig                           v2.12.2            Twig, the flexible, fast, and secure template language for PHP
```

Normally I would provide a PR or idea on a fix but I am unsure what the intent here is. Since this is in the TwigBridge my guess is the templates are intended, but [the Twig filters are clearly optional](https://twig.symfony.com/doc/2.x/filters/markdown_to_html.html), so I am a bit lost.

**Comment by sarcher** [comment]
Of course after writing this, I see #34586 where the same issue is reported. :)

**Comment by chalasr** [comment]
Let's continue the discussion in #34586 and close here then. Thank you for the detailed report
