### ISSUE TITLE
BC Break in symfony/routing 4.4.0

### ISSUE THREAD

**Issue by B4rb4ross4** [symfony/symfony#34612]
**Symfony version(s) affected**: 4.4.0

**Description**  
Today I tried to composer update our application dependencies in a released version of our software. The update brought in the 4.4 version of symfony/routing. This version contains a BC break, because it removes the old syntax for defining a custom route loader service with 1 colon (https://symfony.com/doc/3.4/routing/custom_route_loader.html#loading-routes-with-a-custom-service).

> Invalid resource "legacy.route_loader:loadRoutes" passed to the "service" route loader: use the format "object_id::method" or "object_id" if your object class has an "__invoke" method in legacy.route_loader:loadRoutes (which is being imported from "XXXBundle/Resources/config/routes.yaml"). Make sure there is a loader supporting the "service" type.

I did some digging and I think the source is this commit https://github.com/symfony/routing/commit/314fecb7545793ecfbe3b29d1448b3ee8de808f9#diff-601db0a084e4f4006fa48555089f7bf9.

Our used composer version constraint is `^4.3`

**How to reproduce**  
Define a custom service to load routes with the old syntax with one colon:
https://symfony.com/doc/3.4/routing/custom_route_loader.html#loading-routes-with-a-custom-service
Which was deprecated with 4.2 I think: https://symfony.com/doc/4.2/routing/custom_route_loader.html#loading-routes-with-a-custom-service

``` yaml
legacy:
    resource: legacy.route_loader:loadRoutes
    type: service
```

**Comment by fancyweb** [comment]
Which class is throwing? `ObjectLoader` or `ObjectRouteLoader`?
