### ISSUE TITLE
Preloading file is missing from the website-skeleton app

### ISSUE THREAD

**Issue by murphpdx** [symfony/symfony#34611]
**Symfony version(s) affected**: 5.0

**Description**  

A preload file was generated at `var/cache/dev/srcApp_KernelDevDebugContainer.preload.php` but is now missing.
 
**How to reproduce**  

Create a new website-skeleton app and check for the file.
**Possible Solution**  

**Additional context**

**Comment by ahmedash95** [comment]
I tried 
- `$ composer create-project symfony/website-skeleton my_project`
- `cd my_project && symfony serve` 
and the app works fine

**Comment by murphpdx** [comment]
I'm not having any trouble running the app. I want to use the preload file, that was added here: https://github.com/symfony/symfony/pull/32032 
We were using this to test preloading but the file has since gone away and I'm not sure if that was a mistake?

**Comment by kricha** [comment]
I also have this problem. No preload file in skeleton or my apps.

**Comment by Plopix** [comment]
have a look here, it might be the same issue. https://github.com/symfony/symfony/issues/34750

**Comment by nicolas-grekas** [comment]
Can you please confirm that your app is in a folder at the root of the filesystem? e.g. `/app/src/Kernel.php`? What's the full path to your `Kernel.php` file otherwise?

**Comment by kricha** [comment]
@nicolas-grekas yes, my application is in /app folder.

**Comment by khs1994** [comment]
sure Fixed? I can't find preload filen now.
