### ISSUE TITLE
symfony/doctrine-bridge uses ORM\QueryBuilder typehint for DocumentType

### ISSUE THREAD

**Issue by esserj** [symfony/symfony#34624]
**Symfony version(s) affected**: symfony/doctrine-bridge: 4.4.0

**Description**  
symfony/doctrine-bridge has added type hints to the DocumentType that are for the ORM QueryBuilder, it's also next to impossible to add a typehint there because the typehints are all different (phpcr, mongodb, ...)

**How to reproduce**  
use a DocumentType with a Doctrine PHPCR implementation

**Possible Solution**  
Remove the typehint because there is no common interface

**Additional context**

**Comment by xabbuh** [comment]
see #34581 (will be fixed by #34600) :)
