### ISSUE TITLE
TwigBundle error controller issue with Symfony 4.4

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#34631]
**Symfony version(s) affected**: 4.4.0

**Description**  
I'm upgrading to Symfony 4.4 and going through the following steps:

* Deprecated twig.exception_controller configuration option, set it to "null" and use framework.error_controller instead.

First I set `twig.exception_controller` to null:

```yaml
twig:
    exception_controller: null
```

Next I need to set `framework.error_controller`. The default value is `twig.controller.exception::showAction` as can be seen in https://github.com/symfony/twig-bundle/blob/4.4/DependencyInjection/Configuration.php#L41

```yaml
framework:
    error_controller: 'twig.controller.exception::showAction'
```

This results in the following error:

> Argument 2 passed to Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction() must be an instance of Symfony\Component\Debug\Exception\FlattenException, instance of TypeError given, called in vendor/symfony/http-kernel/HttpKernel.php on line 146

**How to reproduce**  
See above.

**Comment by yceruto** [comment]
This `twig.controller.exception::showAction` is the default value for `twig.exception_controller` option, which is being deprecated too. 

After you migrate to the new `framework.error_controller` option,  this is the new default [ErrorController](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpKernel/Controller/ErrorController.php).

You still can typehint the `FlattenException`, but make sure it comes from `ErrorHandler\FlattenException` instead.

**Comment by yceruto** [comment]
Btw, if you don't have a custom error controller, you don't need this step:
```yaml
framework:
    error_controller: 'twig.controller.exception::showAction'
```

**Comment by XWB** [comment]
@yceruto I don't have a custom error controller, but without `twig.controller.exception::showAction` the custom _error pages do not work:

```yaml
twig:
    exception_controller: null
```

```yaml
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error
```

/_error/404
/_error/500

Results in:

> Unable to find the controller for path "/_error/404". The route is wrongly configured.

**Comment by yceruto** [comment]
it should be `'@FrameworkBundle/Resources/config/routing/errors.xml'` instead

**Comment by XWB** [comment]
Thank you @yceruto, that did the trick.

The change to `@FrameworkBundle/Resources/config/routing/errors.xml'` is not listed in the [upgrade note](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md) and https://symfony.com/doc/current/controller/error_pages.html has not been updated either.

![image](https://user-images.githubusercontent.com/1032281/69647439-c7ec8b00-1069-11ea-9380-ba78f494ecdd.png)

Hence I got stuck :)

**Comment by yceruto** [comment]
Yep, wip https://github.com/symfony/symfony-docs/pull/12687
