### ISSUE TITLE
default_index_method not handled without index_by

### ISSUE THREAD

**Issue by codegain** [symfony/symfony#34637]
**Symfony version(s) affected**: 4.3.8

**Description**  
If "default_index_method" is used and "index_by" is omitted, the tagged services are not indexed.

**How to reproduce**  
1. Use _instanceof in your services.yaml to attach a tag to an interface
```
_instanceof:
    App\Test\TagTestInterface:
        tags: ['app.list']
```
2. Add a class to your services.yaml and inject the tagged list:
```
TestTagList:
    arguments: [!tagged { tag: app.list } ]
```
3. Use the "default_index_method" as described here (https://symfony.com/doc/current/service_container/service_subscribers_locators.html#indexing-the-collection-of-services)
```
TestTagList:
    arguments: [!tagged { tag: app.list, default_index_method: 'getTest' } ]
```
4. The injected tagged list will not have been indexed.

**Possible Solution**  
You can add
`index_by: 'somestring'`
in order for "default_index_method" to be working.
```
TestTagList:
    arguments: [!tagged { tag: app.list, index_by: 'somestring', default_index_method: 'getTest' } ]
```

Maybe this is not a bug but just not clear enough in the docs.

**Comment by stof** [comment]
That's expected. We don't allow setting an default index method if you don't also configure a way to set the index in the tag itself. The presence of `index_by` is what triggers the indexing logic.

@nicolas-grekas should we fail explicitly (or maybe just log something) when `default_index_method` is used without `index_by` ?

**Comment by codegain** [comment]
@stof I think that should be noted in the docs and the code example should include the `index_by`
 
f.e.
```
key:
# config/services.yaml
services:
    # ...

    App\HandlerCollection:
        arguments: [!tagged_locator { tag: 'app.handler', index_by: 'value', default_index_method: 'myOwnMethodName' }]
```

But only the "presence" of the `index_by` key does not trigger this logic, it must also be not `null`.

**Comment by stof** [comment]
hmm, the doc is indeed wrong here. Please open an issue on the symfony-docs repo then.

**Comment by stof** [comment]
> But only the "presence" of the `index_by` key does not trigger this logic, it must also be not `null`.

well, `null` represents an absence of value in programming.

**Comment by codegain** [comment]
> > But only the "presence" of the `index_by` key does not trigger this logic, it must also be not `null`.
> 
> well, `null` represents an absence of value in programming.

Yes :) But I think `index_by` is checked by `$options['index_by'] ?? null` or `isset($options['index_by'])`. If it were checked via `array_key_exists` this wouldn't be a problem I think.

**Comment by stof** [comment]
but `null` is not a valid indexing attribute. The whole point is that we don't want to turn on the feature if you provide `null`.

**Comment by codegain** [comment]
I see your point there. I personally don't like the idea that I have to provide some arbitrary value for the `index_by` key. I think this will just confuse people looking at the code/configuration.

**Comment by nicolas-grekas** [comment]
@stof is right, this is expected: the reason for that is that the code should never be the place that decides how it is going to be used. That's also the reason why the attribute contains the word "default": because that's the least "power" we can give to the code. The most power should go to the part that wires things together - which can be any custom configuration.

IPlease open a doc PR or issue.

**Comment by nicolas-grekas** [comment]
Closing as explained. Please consider a doc PR or issue.
