### ISSUE TITLE
Simplify the PHP version in the config data collector

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#34638]
**Description**  
A few days ago someone (I can't remember who, sorry!) shared this screenshot (I think it was on Symfony Slack):

![image](https://user-images.githubusercontent.com/73419/69654126-9200d400-1074-11ea-8a3e-4de6b8067241.png)

The "PHP version" box looks ugly because of the super long suffix.

I propose to strip all suffixes and always display the version as `\d+\.\d+\.\d+`  Would you agree with that? Or is the long PHP version suffix really meaningful? Thanks!

**Comment by ro0NL** [comment]
We actually already do that in the toolbar panel. For the detailed panel it's fine as-is for me personally ... having `7.3.11-1+ubuntu18.04.1+deb.sury.org+1`.

Alternatively what about moving the full version to a title attribute, eventually you'll know anyway following `View full PHP configuration`.

**Comment by javiereguiluz** [comment]
I'm closing as "won't fix" because the previous comment about "it's fine as-is" was upvoted by everybody, so let's keep it. Thanks!
