### ISSUE TITLE
There is no way configure mailer component without using message bus

### ISSUE THREAD

**Issue by voodooism** [symfony/symfony#34633]
**Symfony version(s) affected**: 4.3.8

**Description**  

There is no way to configure the mailer component without a bus. If I have the messenger component in my app mailer automatically works via bus. But I want to send a message instantly without using a message bus
https://github.com/symfony/mailer/blob/4.3/Mailer.php#L29

**Possible Solution**  
Maybe it is a good idea to add the ability to configure this?

**Comment by mhujer** [comment]
@voodooism looking at the linked code I can see that the message bus is optional and the messages is sent immediately if no message bus is provided.

https://github.com/symfony/mailer/blob/a2e19255ce8de3a9c4e5228fde33ca9390af787c/Mailer.php#L35-L41

**Comment by voodooism** [comment]
> @voodooism looking at the linked code I can see that the message bus is optional and the messages is sent immediately if no message bus is provided.
> 
> https://github.com/symfony/mailer/blob/a2e19255ce8de3a9c4e5228fde33ca9390af787c/Mailer.php#L35-L41

Yes, you are absolutely right. But, I have `messenger.default_bus` provided by [symfony/messenger](https://github.com/symfony/messenger). And [this](https://github.com/symfony/framework-bundle/blob/4.4/Resources/config/mailer.xml#L10) it is injected as an argument. 
I want to use the mailer component without a bus, even if I have the bus in the project.
Is there any way to set `MessageBusInterface` as null directly?

**Comment by voodooism** [comment]
I had added the [pull request](https://github.com/symfony/symfony/pull/34646) with my propose. I did pull request first time in the Symfony repository, so let me know if something is wrong. Any feedback
