### ISSUE TITLE
subtree symfony/security-bundle not up to date

### ISSUE THREAD

**Issue by MeihdiDjebli** [symfony/symfony#34630]
**Symfony flex security-bundle**: 4.4 up

**Description**  
At least one commit (https://github.com/symfony/symfony/commit/0950cfbc65bc0b9bbeb682eb237d028a4e3033c5) is not visible on Symfony's subtree component security-bundle.

**How to reproduce**  
Use Symfony Flex and symfony/security-bundle 4.4 with an anonymous firewall without declaring a provider.

symfony/security-bundle require a provider.

**Additional context**  
May be I'm not aware of how works subtree...

**Comment by chalasr** [comment]
The split happens when branches are merged up to master. Commit should be there now
