### ISSUE TITLE
Cannot run webpage using symfony 5.0

### ISSUE THREAD

**Issue by jgudavalli** [symfony/symfony#34644]
**Symfony version(s) affected**: 5.0

**Description**  
I have installed symfony 5.0 and tried to run a webpage. I get the below error:

Compile Error: Declaration of class@anonymous::write($content, ?array $metadata = NULL) must be compatible with Symfony\Component\Config\ConfigCacheInterface::write(string $content, ?array $metadata = NULL)

flock($lock, LOCK_EX | LOCK_NB, $wouldBlock);                if (!flock($lock, $wouldBlock ? LOCK_SH : LOCK_EX)) {                    fclose($lock);                } else {                    $cache = new class($cachePath, $this->debug) extends ConfigCache {                        public $lock;                        public function write($content, array $metadata = null)                        {                            rewind($this->lock);

**How to reproduce**  

composer create-project symfony/skeleton <projectname>

and run the project in apache

**Possible Solution**  
not known

**Additional context**

**Comment by xabbuh** [comment]
Which PHP did you use to run the application?

**Comment by paco7777** [comment]
I have the same problem

**Comment by xabbuh** [comment]
@paco7777 Which PHP did you use to run the application?

**Comment by alsemyannikow** [comment]
i have the same problem using php 7.3

**Comment by xabbuh** [comment]
Does the same happen with a Symfony 4.4 application? If not, please double-check that the web-server indeed uses PHP 7.3. The interpreter used by the web server can be different from the one used on the command-line.

**Comment by paco7777** [comment]
@xabbuh Thanks, my Xampp version was 7.1.33, I download the 7.3.12 and it's working !
