### ISSUE TITLE
[Contracts] symfony/contracts 1.1.8 relaese missing for many repos

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#34655]
**Symfony version(s) affected**:  symfony/contracts 1.1.8

**Description**  
The release of symfony/contracts 1.1.8 was not propagated to the many-repos, like 
`symfony/cache-contracts`, `symfony/event-dispatcher-contracts`.
This can lead to bugs if you require it in the given version, in some instances composer picks up the mono-repo in the according version as it replaces the many-repos, under some other circumstances composer will just error because the versions do not exist.

**How to reproduce**  
`composer require symfony/cache-contracts:1.1.8`

**Possible Solution**  
Releases made to the mono-repo should also be propagated to the many repos like the releases prior to v1.1.8 and the 2.0.0 release

**Comment by nicolas-grekas** [comment]
That's on purpose: we don't tag the individual contracts if they don't change.
