### ISSUE TITLE
[MonologBundle][RFC] Migrate `server:log` command away from deprecated WebServerBundle

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#34657]
By deprecating the WebServerBundle, we also deprecated the `server:log` command which does not have equivalent in `symfony` cli: when people manage their own stack (ie. Docker), `server:log` is very usefull to display logs.

I suggest to migrate it to MonologBundle in 4.4 in order to propose a migration path to users? do you think it's doable?

**Comment by ogizanagi** [comment]
I'd suggest to move classes to the bridge (& add the deprecations in 4.4 WebServerBundle indeed). We just need the wiring in the bundle.
