### ISSUE TITLE
[Console] display PHP version and path to binary

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#34656]
**Description**  
PHP version used to run Symfony Console may be different from the one used in the webserver for whatever reason (e.g. improper configuration when maintaining several available versions locally).

It would be useful to see which PHP version and from where is used. I know you can check the version using the `about` command, but it would be more convenient to see it each time.

What do you think? Should I prepare a PR?

**Example**  
![image](https://user-images.githubusercontent.com/353372/69723447-d8f4d500-1119-11ea-8a8e-f194e40b242a.png)

**Comment by chalasr** [comment]
Closing as explained in #34706.
