### ISSUE TITLE
[Validator] Avoid infinite recursions in GroupSequence

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#34667]
**Description**  
In Symfony Docs you can read this about GroupSequence:

> This means that you have to use the {ClassName} (e.g. User)
> group when specifying a group sequence. When using Default,
> you get an infinite recursion (as the Default group references
> the group sequence, which will contain the Default group which
> references the same group sequence, ...).

The docs about GroupSequences are too difficult to read sometimes, so I'd like to simplify some things.

If using `Default` inside `GroupSequence` produces an infinite recursion ... why couldn't we detect in code if `'Default'` is being used inside `GroupSequence` and display instead a useful error message? In addition to improving DX, this could allow us to simplify the docs a bit. Thanks!

**Comment by ismail1432** [comment]
Hi Javier ! 
"Comment ça va ?" :fr: 

Are we sure that there is a recursion because I found this in base code https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Mapping/ClassMetadata.php#L397 and this code thrown an error 

```php
/**
 * @Assert\GroupSequence({"User", "Default"})
 */
class User 
```

**Comment by javiereguiluz** [comment]
@ismail1432 you are right! The code works as I was proposing ... so let's close this as fixed and let's try to simplify the docs. Thanks!
