### ISSUE TITLE
[Debug] Symfony reports a class is already used but it's not

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34678]
**Symfony version(s) affected**: 5.0 (4.4 too - and IIRC 4.3 too)

I'm sorry, but I don't have time ATM to dig and fix this issue 😬

**Description**  

This is a typo I make quite often while refactoring: Badly rename a file and a class. When there is a missmatch between the name and the file Symfony trigger the following error:

```
PHP Fatal error:  Cannot declare class App\Command\FoobarCommand, because the name is already in use in /home/gregoire/dev/tmp/command/src/Command/Foobar.php on line 12

Fatal error: Cannot declare class App\Command\FoobarCommand, because the name is already in use in /home/gregoire/dev/tmp/command/src/Command/Foobar.php on line 12
Symfony\Component\ErrorHandler\Error\FatalError^ {#3102
  -error: array:4 [
    "type" => 64
    "message" => "Cannot declare class App\Command\FoobarCommand, because the name is already in use"
    "file" => "/home/gregoire/dev/tmp/command/src/Command/Foobar.php"
    "line" => 12
  ]
  #message: "Compile Error: Cannot declare class App\Command\FoobarCommand, because the name is already in use"
  #code: 0
  #file: "./src/Command/Foobar.php"
  #line: 12
}
```

But this is wrong.

Each time, I spend few minutes to understand what is wrong in my code. I think we ca do better. And I think in previous version of symfony the message was something like

> The class Foobar was expected in the file Foobar, but FoobarCommand was found insteand

**How to reproduce**  

```
symfony new --full command
cd command
bin/console make:command app:foobar
mv src/Command/FoobarCommand.php src/Command/Foobar.php # Yes this is wrong, but it happens when refactoring
bin/console
```

**Comment by xabbuh** [comment]
Related to #34658?

**Comment by nicolas-grekas** [comment]
Closing as duplicate.
