### ISSUE TITLE
[DependencyInjection] Lazy ServiceLocator

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#34683]
I'd like use a [ServiceLocator](https://symfony.com/doc/master/service_container/service_subscribers_locators.html#defining-a-service-locator) for some of my services. However with the documented way I'm running into circular reference issues. What I need is for the ServiceLocator to be lazy - it should not receive all the services in it's constructor but instead should only receive their names and get them from the container when first used. How can I do that? Of course I assume all the services would have to be public but that's fine.

It's also for performance reasons. Most of the time only one or two services will actually be used so there is no point in initializing the rest.

**Comment by BoShurik** [comment]
AFAIK it is lazy

> Service Subscribers are intended to solve this problem by giving access to a set of predefined services while instantiating them only when actually needed through a Service Locator, **a separate lazy-loaded container**.

**Comment by enumag** [comment]
Then maybe I'm just doing something wrong... the thing is that I need to create the ServiceLocator in a CompilerPass and not in yaml. What is the proper equivalent of this for a CompilerPass?

```
    app.command_handler_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                App\FooCommand: '@app.command_handler.foo'
                App\BarCommand: '@app.command_handler.bar'
```

I'm currently using this:

```
		$definition = new Definition();
		$definition->setClass(ServiceLocator::class);
		$definition->setArgument(0, $services);
		$container->setDefinition('my_servic_locator', $definition);
```

Where `$services` is array of `Reference`. This causes `ServiceCircularReferenceException`.

**Comment by BoShurik** [comment]
You forgot to add `container.service_locator` tag

**Comment by enumag** [comment]
Ok, that seems to have helped. Thank you!
