### ISSUE TITLE
AssertEmail with strict mode does not check for DNS.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#34681]
**Symfony version(s) affected**: 4.3

**Description**  
When using
```
@Assert\Email(mode="strict")
```

There is no error for a `fooBar@gmailcom` email value

**Possible Solution**  
The EmailValidator use 
```
$strictValidator->isValid($email, new NoRFCWarningsValidation())
```
A better check could be
```
$strictValidator->isValid($email, new MultipleValidationWithAnd([new NoRFCWarningsValidation(), new DNSCheckValidation()]))
```

**Comment by fabpot** [comment]
see #28842

**Comment by VincentLanglet** [comment]
@fabpot I don't understand the link.

In your PR, you deprecate the checkMX and checkHost options. You said
> Email validation is complex (see the various PRs on this topic) and opinionated [...] so I propose to instead deprecate checkMX and checkHost and remove them in 5.0.

I understand `Symfony` does not want to include complexity about email validation.
But when using the `mode=strict`, we're using the `egulias/email-validator` library.

And the NoRFCWarningsValidation seems arbitrary chosen for the check
Why not using all the validations provided by this library by adding the DNSCheckValidation ?

**Comment by fabpot** [comment]
Because the Symfony core team think that checking the DNS is not a good idea as it is not reliable.

**Comment by nicolas-grekas** [comment]
I would recommend always using html5 validation mode.
Strict mode is not very pragmatic as is stick to the RFC, which itself is too lax.

**Comment by VincentLanglet** [comment]
Thanks for the advice !

**Comment by VincentLanglet** [comment]
We started to use strict mode because someone use this email adresse
```
foo..bar@gmail.com
```
And we got an exception with the mailer because this is not a valid email address.

Html5 mode (and loose mode) checks for the dot in the host, but both does not check for the previous pattern.

But
```
     * @Assert\Email(mode="strict")
     * @Assert\Email(mode="html5")
```
wont be a solution since sometimes I could get two error messages

**Comment by VincentLanglet** [comment]
@fabpot @nicolas-grekas Would you accept a PR with the following change ?

```
private static $emailPatterns = [
        Email::VALIDATION_MODE_LOOSE => self::PATTERN_LOOSE,
        Email::VALIDATION_MODE_STRICT => self::PATTERN_LOOSE,
        Email::VALIDATION_MODE_HTML5 => self::PATTERN_HTML5,
    ];
```
