### ISSUE TITLE
[DI] XmlDumper looses parameters types while dumping

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony#34689]
**Symfony version(s) affected**: 4.4.0

**Description**  

`XmlDumper` doesn't preserve container parameter types.
Use any numeric-like parameter in container parameter value leads to have loaded value type `float|int` from xml cache.

**How to reproduce**  

Use parameter with value something like `'+1238523'`.
Expected loaded value: `string(8) "+1238523"`
Actual loaded value: `double(1238523)`

Reproducer:
https://gist.github.com/andrew-demb/02c8487cd1a457f3d37d20c7afedd76c

**Possible Solution**  

Support more cases here and set needed `type` attribute.
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php#L316-L320

**Additional context**

**Comment by xabbuh** [comment]
see #34716
