### ISSUE TITLE
[DX][HttpKernel] Remove the Kernel::boot() method

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34680]
Hi!

**Description**  

We write this code all the time (bin/console, public/index.php, test.php, In functionnal test, etc):

```php
$k = new AppKernel('dev', true);
$k->boot();

// ...
```

I did not remember if I needed once to instantiate the kernel without booting it.
IMHO, we could increase the DX by moving the `boot()` call to the constructor directly. 

WDYT?

**Comment by sstok** [comment]
This would make it impossible to lazily boot a Kernel, which in some cases might be needed (as you only need the object, but not that's started already). I don't really see the problem with calling a single method 😄

Alternatively you can add an extra argument (not in favor of btw) to automatically boot the kernel upon constructing.

**Comment by TomasVotruba** [comment]
Sometimes you need to add/change something after constructor and before booting.

**Comment by gmponos** [comment]
Wont this affect tests...? There is a boot kernel method there if I remember..

**Comment by Pierstoval** [comment]
> Wont this affect tests...? There is a boot kernel method there if I remember..

If the method is called from the constructor, it's considered as a big change, so tests will have to change accordingly, so "this affects tests" is not really a good reason 😄 


However, I agree with the "no" statements. Creating the kernel and booting it are two separate operations. The `Application` class for instance needs to execute many actions before fetching the command in the kernel (which boots the kernel). Having a booted kernel before using it seems like a bit of overhead in cases where the kernel is "not yet" used by its dependents.

**Comment by stof** [comment]
Delaying boot is very important for HttpCache, as the kernel is booted only if there is a cache miss.

**Comment by lyrixx** [comment]
@stof very good point. I did not know that. Let's close this issue then.

**Comment by stof** [comment]
btw, note that if you use your kernel to handle requests, you already don't need to boot it explicitly as `handle()` triggers the booting (which is exactly how lazy booting is done when using HttpCache).

If you look in a project, `bin/console` is **not** calling `boot`, neither is `public/index.php` (contrary to what your issue description says). The only place where I'm seeing `boot()` calls are tests where you want to boot a kernel to get services from the container, rather than using the kernel for its HttpKernelInterface API (so rather integration tests than functional tests).

**Comment by Pierstoval** [comment]
And for such case of "integration test", calling `KernelTestCase::bootKernel()` is fairly enough, does all the checks to shut the kernel down if necessary, its two arguments allow you to customize the env & debug vars, and it's one single line of code, so we already are okay about booting the kernel
