### ISSUE TITLE
[Messenger] Looks like the delivery_mode=2 is missing

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34685]
**Description**  

I was working on an application that uses Swarrot and I notice it does not publish (by default)  messages with `delivery_mode=2`. 

It's very important to set this property if you don't want to loose messages.

Durable queue is not enough!
TL;DR:
* Durable queue means the queue will be persisted after a crash (but content will be lost)
* Message with delivery_mode=2 will be persisted after a crash

So I looked into the Messager component to be sure we did not make the same mistake.
And ... It looks like we made the same error. I did not deeply search for delivery_mode=2 but at the first glance I was not able to find it. 

~~More over, it looks like it's not possible at all to to set the delivery_mode :/~~ 
**EDIT**: it looks like [is possible](https://github.com/sroze/messenger-enqueue-transport#setting-custom-configuration-on-your-message)

I'm not an expert of Messenger Component, this is why I'm opening this issue to be 100% sure we did not miss anything.

Thanks

**Comment by fabpot** [comment]
Looks like an important issue. /cc @sroze @weaverryan

**Comment by lyrixx** [comment]
I confirm that the delivery mode is missing.
This is a screenshot of an email sent with messenger

![image](https://user-images.githubusercontent.com/408368/70522376-4c96d900-1b41-11ea-8c34-3f8b43189610.png)

This is a screenshot of a queue I manage with directly the PECL (I can not use messenger here, I need the full power of rabbitmq)

![image](https://user-images.githubusercontent.com/408368/70522439-6b956b00-1b41-11ea-87ca-f45d903d32e3.png)


As you can see, the delivery mode is missing from the first screenshot.

This means: **if I restart rabbitmq, I will loose my message**. Data can be lost, not only when rabbitmq crash. A restart is enough.

**Comment by weaverryan** [comment]
@lyrixx is there any downside to making this the default? We could put it right here: https://github.com/symfony/symfony/blob/65a988880d719f0de2329b39eb2e7c1b56d7532f/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L231

**Comment by lyrixx** [comment]
Yes, they are. It will be a bit slower because the message will be persisted to disk. BUT we are talking about big number vs big number (30K msg/sec). 

IMHO, safety is much more important than performance. And If people want better perf, it's up to them to allow potential message lost.

Swarrot does that by default and theses days I'm working with https://github.com/streadway/amqp, a golang AMQP lib  and it does that by default too. The following sentence comes from this documentation and it resumes quite well the situation (feel free to copy it to the code / doc):
> DeliveryMode. Transient means higher throughput but messages will not be restored on broker restart. The delivery mode of publishings is unrelated to the durability of the queues they reside on. Transient messages will not be restored to durable queues, persistent messages will be restored to durable queues and lost on non-durable queues during server restart.

**Comment by weaverryan** [comment]
@lyrixx would you be able to create a PR to add the attribute? As I mentioned, I think it would go here: https://github.com/symfony/symfony/blob/65a988880d719f0de2329b39eb2e7c1b56d7532f/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L231 - basically if `delivery_mode` is not set on `$attributes`, we will set it to 2.
