### ISSUE TITLE
symfony/http-client composer require problem

### ISSUE THREAD

**Issue by schefpet** [symfony/symfony#34686]
Hi there,
it is impossible to install thist packages. It says:

The contents of https://repo.packagist.org/p/symfony/http-client-contracts%241dbfb65fb93090e56f7ca9cd57633b732c9fda4f9f3ebced78e3fccc0cb60c3c.json do not match its signature. This could indicate a man-in-the-middle attack or e.g. antivirus software corrupting   
  files. Try running composer again and report this if you think it is a mistake.

Thanks for help.

**Comment by stof** [comment]
This is not an issue in Symfony. Composer is reporting an issue when downloading the metadata from composer, and even gives you indications about what could be wrong in case the error persist when retrying.
I'm closing this issue as there is strictly nothing the Symfony team can do here.
