### ISSUE TITLE
symfony/translation v4.4.0 TranslatorInterface::setLocale not compatible with translation-contracts v 2.0 LocaleAwareInterface

### ISSUE THREAD

**Issue by FreekVR** [symfony/symfony#34692]
**Symfony version(s) affected**: 4.4.0

**Description**  
It looks like recently the symfony/translations-contracts package was updated with additional type declarations, specifically in this commit:
https://github.com/symfony/translation-contracts/commit/8feb81e6bb1a42d6a3b1429c751d291eb6d05297

The `symfony/translation` package v 4.4.0 indicates that it should be compatible with both the 1.x and 2.x version of `translation-contracts`:
```
php composer.phar why symfony/translation-contracts
symfony/translation  v4.4.0  requires  symfony/translation-contracts (^1.1.6|^2)  
```

However, with symfony/translation 4.4.0 and translation-contracts 2.0 installed, I am getting the following fatal error: 
`Fatal Error: Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)`

**How to reproduce**  
Install symfony/translation 4.4.0 and symfony/translation-contracts 2.0. Run a tool that does static analysis on the PHP files (for example squizlabs/PHP_CodeSniffer /w PHPStorm, running PHP 7.2.x).

**Possible Solution**  
Either:
- Drop the 2.x version of `translation-contracts` from  `symfony/translations 4.4.x`

Or:
- Make TranslatorInterface::setLocale($locale) compatible by changing it to TranslatorInterface::setLocale(string $locale). (but that may not be compatible with translation-contracts ^1.1.6)

I was able to mitigate the issue myself by adding a dependency to translation-contracts ^1.1.6 to my projects `composer.json`

**Comment by xabbuh** [comment]
You need to ensure that Composer does not install packages that are not compatible with the PHP version that you use to execute your application (see for example #34482).

**Comment by Zae** [comment]
But the packages are compatible with his version of PHP right?

It's just that the packages are not compatible with eachother because one has type declarations and the other does not? So the method signatures do not match anymore.

**Comment by xabbuh** [comment]
That is supported by PHP 7.2+. Composer will ensure that the installed package versions are compatible if you run it with a proper PHP environment.

**Comment by Zae** [comment]
Learned something new today, thanks for clarifying!
