### ISSUE TITLE
[Symfony 5.0, 4.4] Bug php bin/console make:migration 

### ISSUE THREAD

**Issue by JefDc** [symfony/symfony#34696]
**Symfony version(s) affected**: 5.0, 4.4

**Description**  
Hello,

I have a problem when I want to migrate an entity with the terminal command "php bin/console make:migration" which has a ManyToOne relationship.

Just before I create an entity via the command "php bin/console make:entity" which has several fields (title VARCHAR, slug VARCHAR, content TEXT, category MANY TO ONE). 

After the migration command, when I go to see in the migration file, in the up function I have this:

<img width="1250" alt="15746015435814_Capture d’écran 2019-11-24 à 14 02 53" src="https://user-images.githubusercontent.com/42522845/69819815-f56b3d00-11ff-11ea-97cc-dc2e28516af1.png">

My entity file 

<img width="730" alt="Capture d’écran 2019-11-28 à 16 53 17" src="https://user-images.githubusercontent.com/42522845/69819748-d4a2e780-11ff-11ea-83b1-87afc1d0c829.png">
<img width="730" alt="Capture d’écran 2019-11-28 à 16 53 36" src="https://user-images.githubusercontent.com/42522845/69819752-d7054180-11ff-11ea-8faa-764fff8a2489.png">

**Comment by dmaicher** [comment]
Which version of DoctrineBundle are you using?

Most likely this was caused by the bug that was fixed in https://github.com/doctrine/DoctrineBundle/pull/1073

**Comment by JefDc** [comment]
v1.8.0

**Comment by JefDc** [comment]
After update, work !!!
Tank you for your reponse !
