### ISSUE TITLE
[HttpClient] HttpClient 4.4 cannot be used in Symfony 3.4 projects

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#34698]
**Symfony version(s) affected**: 4.4.0

**Description**  
Because of a conflict rule in `symfony/http-client`, it is not possible to install version 4.4.0 in Symfony 3.4 projects. However `sensiolabs/security-checker` (which is installed on projects created with Symfony Standard Edition) uses the HttpClient library.

The consequence is that Symfony 3.4 projects are pinned to HttpClient 4.3, a branch that will go EOL before Symfony 3.4. I think, we should fix that.

**How to reproduce**
```
composer create-project symfony/framework-standard-edition my-project
cd my-project
composer config platform.php 7.1.33
composer update
composer show | grep http-client
```

**Possible Solution**
Allow HttpKernel 3.4 and HttpClient 4.4 to be installed together.

**Comment by nicolas-grekas** [comment]
There must be a reason, but we can maybe relax it. Did you have a look at what is blocking, past the composer.json rule? PR welcome if you spot a patch :)

**Comment by derrabus** [comment]
The conflict rule was introduced by @fancyweb when working on the data collectors, IIRC.

**Comment by stof** [comment]
The conflict rule probably needs a lower bound, to conflict only with FrameworkBundle versions configuring the HttpClient without proper data collector usage.
