### ISSUE TITLE
Interactive console aborted on: Windows PHP 7.4.0 (only)

### ISSUE THREAD

**Issue by julien-boudry** [symfony/symfony#34702]
**Symfony version(s) affected**: 4.4.0 & 5.0.0 on PHP 7.4 Windows NTS only

**Description**  
This bug only happen on PHP 7.4 Windows NTS > RC4. Working well on 7.4 RC4 and lower. Tested on two very different installation of windows 10 (up to date).
Not tested on TS. Working well on Linux.

**Interactive console not working:** (Windows 10, PHP 7.4.0, Console 4.4.0)
![image](https://user-images.githubusercontent.com/4020317/69828445-31140000-121c-11ea-9bc3-4a130a51d877.png)

Crash directly without anyuser interaction 

**Expected outcome:** (Debian, PHP 7.4.0, Console 4.4.0)
![image](https://user-images.githubusercontent.com/4020317/69828549-8223f400-121c-11ea-96a4-bbb3829eaa70.png)

**How to reproduce**  
Here from
https://github.com/julien-boudry/Condorcet/blob/dev-2.1/lib/Console/Commands/ElectionCommand.php

**Possible Solution**

PHP 7.4 bug since RC5?

**Comment by julien-boudry** [comment]
PHP bug: https://bugs.php.net/bug.php?id=78883

**Comment by nicolas-grekas** [comment]
Closing then.

**Comment by julien-boudry** [comment]
@nicolas-grekas : Maybee not exactly this bug. This one seam from RC2, but I'm formal, mine from RC5.

https://bugs.php.net/bug.php?id=78883&thanks=3 (see news comments)

**Comment by julien-boudry** [comment]
php/php-src#4952

**Comment by sboo** [comment]
Update to PHP 7.4.1 and it will work correctly again

**Comment by seewhy17** [comment]
Hi, I am having the same issue; when running  "php artisan schedule:run" on 
Laravel 6.7.0
Windows
Php 7.3.5
