### ISSUE TITLE
[Mailer] Custom personalizations for SendgridApiTransport?

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#34700]
**Description**  
We would really like to add some more personalizations (https://sendgrid.com/docs/for-developers/sending-email/personalizations/) to our Sendgrid emails, but we're not sure what would the best approach for a PR. The only way I can think of to pass that extra data to the `SendgridApiTransport` class is by a custom json-encoded header on the `Email`  like "x-sendgrid-personalizations" that we would then merge with the personalizations array created in the `SendgridApiTransport` class?

**Comment by acasademont** [comment]
A `ParameterizedHeader` could also work I guesss

**Comment by Koc** [comment]
Relates to #35050

**Comment by fabpot** [comment]
Closing as there is a related PR now.

**Comment by rgarnica** [comment]
Did #35050 solve this? I think it only mentioned Sendgrid. But the implementation has not affected sendgrid transport. Should we reopen this and submit a new PR?

**Comment by fabpot** [comment]
@rgarnica The infrastructure is in place now. If you know how to support Sendgrid, a PR would be more than welcome indeed. Thank you.
