### ISSUE TITLE
[HttpKernel] Missing deprecation trigger of GetResponseEvent

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#34703]
**Symfony version(s) affected**: 4.3, 4.4

**Description**  
I was implementing integration tests in https://github.com/getsentry/sentry-symfony/pull/277 to spot deprecations, and I noticed that, even if I have two listeners on deprecated events, I'm not getting any deprecation warning.

**How to reproduce**  
 * Clone `sentry/sentry-symfony` at this commit: https://github.com/getsentry/sentry-symfony/pull/277/commits/2712152db8b5964a0ef4f4b0bd4bf6f7469c3729
 * run `composer install` and chech that `symfony/http-kernel:^4.3` is in use
 * run `vendor/bin/phpunit test/End2End`

I should get deprecation warnings due to [this listener being used](https://github.com/getsentry/sentry-symfony/blob/2712152db8b5964a0ef4f4b0bd4bf6f7469c3729/src/EventListener/RequestListener.php#L43).

**Possible Solution**  
We should trigger the deprecation when `GetResponseEvent` (or similar events) is autoloaded.

**Comment by nicolas-grekas** [comment]
The description is correct, yet we cannot trigger the deprecation when GetResponseEvent (or similar events) is autoloaded because those classes are extended by not-legacy classes as part of the required BC layer.

There is nothing we can do about this, unfortunately. That's where a static analyzer is needed.

Thanks for reporting.

**Comment by Jean85** [comment]
> That's where a static analyzer is needed.

For anyone wondering, one possible solution is to use PHPStan with https://github.com/phpstan/phpstan-deprecation-rules

Thanks Nicolas.

**Comment by nicolas-grekas** [comment]
Or Symfonyinsight, which has a Black Friday coupon available until December 6 btw ;)
See https://insight.symfony.com/blackfriday

**Comment by Jean85** [comment]
BTW those aren't a solution for a redistributable packages, because backward compat pieces would be marked as a failure in CI :disappointed:
