### ISSUE TITLE
Validator does not validate the whole entity when constraints=null

### ISSUE THREAD

**Issue by alexchuin** [symfony/symfony#34701]
**Symfony version(s) affected**: 4.4.0

**Description**  
When i use the Validator to validate an entity with `constraints=null`, the entity is not validated.
Maybe {@link \Symfony\Component\Validator\Constraints\Valid} is assumed. doesn't work ?

Based on : https://symfony.com/doc/current/validation.html#using-the-validator-service

**How to reproduce**  
I have an entity with :
```
   /**
     * @var string
     * @ORM\Column(type="string")
     *
     * @Assert\Choice(callback="getMimeTypes")
     * @Groups({"read", "write"})
     */
    private $mimeType;
```

I validate with : 
`$this->validator->validate($data, null, ['write']);`

**Possible Solution**  
When I validate with `$this->validator->validate($data);` it's OK.
So how can I validate the whole entity with a group ?

Thanks !
Alex

**Comment by xabbuh** [comment]
The issue is with how you configure the groups. The `@Groups` annotation is not related to the Validator component. You need to use the `groups` option instead:

```php
/**
 * @Assert\Choice(callback="getMimeTypes", groups={"read", "write"})
 */
```
