### ISSUE TITLE
The translation:update command should be aware of the +intl-icu variant

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#34713]
If I'm using a file named `translations/messages+intl-icu.fr.xlf` for translations, the `translation:update` command will create a `translations/messages.fr.xlf` file instead of updating the existing one.

/cc @yceruto

**Comment by fabpot** [comment]
The `translation:update` command should also probably generate `+intl-icu` files by default, no?

**Comment by yceruto** [comment]
> https://github.com/symfony/symfony/pull/28952
> The way to opt-in is to put messages in a domain with the +intl-icu suffix *at loading/declaration time.*

would that mean you should also update the suffix in the code to make it work properly? 
```twig
{% trans_default_domain 'messages+intl-icu' %}
```
It works, but @nicolas-grekas (as author of this code) can confirm it better.

**Comment by nicolas-grekas** [comment]
Nope, there should be no need to update the code/template.

**Comment by stof** [comment]
@yceruto `trans_default_domain` is part of the usage time, not of the loading/declaration time. Your are translating things there, not defining your translations.

**Comment by yceruto** [comment]
Okay, so it's a buggy behavior related to the `FileDumper` when there are new translation keys. 

> The translation:update command should also probably generate +intl-icu files by default, no?

I think it will depend:

| Intl extension (or polyfill) installed | default domain |
| --- | --- |
| no | messages |
| yes | messages+intl-icu |

but also if we are updating an existing (single) file, we must keep the domain attached to it, regardless whether Intl ext is installed or not. And if both files exist (`messages.en.xlf` and `messages+intl-icu.en.xlf`) the new keys should be generated into the default guessed earlier.

Can you confirm that's what we want before make the changes?

**Comment by nicolas-grekas** [comment]
@yceruto LGTM!

**Comment by yceruto** [comment]
ready for review https://github.com/symfony/symfony/pull/34797

**Comment by timosmit** [comment]
I would like to reopen this issue as I have been experiencing similar issues with the `translation:update` command after upgrading from 5.0.2 to 5.0.3. Even though I have the PHP intl extension installed, the command refuses to output the messages in the ICU format.

The issue also exists in the latest bugfix release (5.0.7 at the moment of writing).

Here's what I'm currently using:
* Windows 10
* PHP 7.4.2
* symfony/intl 5.0.7
* symfony/translation 5.0.7

**Comment by fabpot** [comment]
Please, open a new issue.
