### ISSUE TITLE
[Messenger] RFC: Worker Status / lifecycle

### ISSUE THREAD

**Issue by rjhllr** [symfony/symfony#34727]
**Description**  
Currently, messenger seems to provide no status information about running workers. There should be a way to get this kind of information out of the component. 

I also have not found a way to easily implement this: the `ConsumeMessagesCommand` class provides no events and decorating the command service does not really work either, since most of the code is mostly enclosed in the execute function, without providing any entry points for customization.
 
I could not find an issue relating to this by searching for "health", "lifecycle" and "worker status". Only thing I found was an issue talking - among other things - about how nice a panel would be (https://github.com/symfony/symfony/issues/30540), but to get there we need to add this feature anyway.

Example usages: system health monitoring, configuration / sanity checks, metrics, predictions

**Example**  
There are a few ways this could turn out, I'm not too sure what the "most Symfony" way of doing it would be. Options that come to mind:
- make the command's class more verbose and easier to extend. You could then create a parent class that - for example - can access the worker and provide this information wherever you need it
- lifecycle events for workers (started, stopped, processing…)
- ???

Excuse me if I missed anything while creating this issue or if it's a duplicate. I'd be more than happy to provide a small PR, but will definitely need some guidance in doing so.

**Comment by noniagriconomie** [comment]
There are events dispatched in the messenger process https://github.com/symfony/messenger/tree/master/Event
For status informations, you mean for the profiler ? Or production ?

**Comment by rjhllr** [comment]
Thank you, I'm still on the 4.3 (and did forget to check the current code base, sorry!). I reckon this can be closed for now, thank you!

**Comment by rjhllr** [comment]
Are those events all that useful? Upon further inspection, I've found that we do indeed get the worker object from those events, but the worker object in and of itself is quite useless, given that you get no information from the worker object about say for example which transports it's listening on. 
Shouldn't that info be exposed?

**Comment by weaverryan** [comment]
If some additional info would be helpful for you in the event, then yea - you should definitely open a PR for that :). I created most of those events - but I purposely didn't expose a lot of information because I wanted real need to drive *what* we expose - i.e. what we actually need :)

**Comment by Tobion** [comment]
Closing as the issue too generic. Some kind of dashboard with status information could be useful. If you want to work on this, feel free to create a concrete PR or best try to provide such a feature in an external bundle.
