### ISSUE TITLE
isGranted remove Deprecated Feature

### ISSUE THREAD

**Issue by appaydin** [symfony/symfony#34724]
**Description**  
Feature [#33584 ](https://github.com/symfony/symfony/pull/33584) 
I don't use ExpressionLanguage. But you're forcing me to use this feature.

**Example**  
    
    /* deprecated error */
    $this->isGranted(['ROLE_ADMIN', 'ROLE_OTHER'])

**Comment by xabbuh** [comment]
You need to rewrite your code this:

```php
$this->isGranted(['ROLE_ADMIN']) || $this->isGranted(['ROLE_OTHER'])
```

**Comment by appaydin** [comment]
That's ridiculous. Both are entering the array value. Array must be monovalent.

**Comment by stloyd** [comment]
https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#security
I guess that @xabbuh made a little typo & had in mind:
```php
$this->isGranted('ROLE_ADMIN') || $this->isGranted('ROLE_OTHER')

**Comment by xabbuh** [comment]
Indeed, that was a mistake when I copied and update your example. I fixed the comment.
