### ISSUE TITLE
Tag Doctrine's EntityManager with ResetInterface

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#34720]
**Description**  
Following this discussion on Twitter with @lyrixx and @nicolas-grekas , I'm opening this issue.

It seems that the Doctrine's `EntityManager`s are not tagged with the `ResetInterface` `interface` and so they are not reset when calling `Application::reset()` method.

Currently I've not verified on my own, but I trust what @lyrixx said in the Twitter 3d.

**Comment by xabbuh** [comment]
Can you open the issue in the DoctrineBundle repository? That's where the service for the entity manager is defined.

**Comment by nicolas-grekas** [comment]
Actually we do reset the entity managers, it's the job of `ManagerRegistry`, see https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/ManagerRegistry.php

This works only when ocramius/proxy-manager is installed - for some reason I don't recall - but they must be serious (please prove me wrong :) )

**Comment by Aerendir** [comment]
So, in the end, the answer is "Yes, the EntityManager is reset when calling `Application::rest()`"?

**Comment by nicolas-grekas** [comment]
It's a bit more subtle but yes, the answer is yes :)

**Comment by Aerendir** [comment]
What do you mean by “a bit more subtle”?🤔

**Comment by nicolas-grekas** [comment]
@Aerendir what I wrote above :)

> This works only when ocramius/proxy-manager is installed

**Comment by nicolas-grekas** [comment]
On a closer look, while the code infrastructure is there, it looks like it's not wired by default.
I opened https://github.com/doctrine/DoctrineBundle/issues/1083 as a follow up.

**Comment by alcaeus** [comment]
A fix has been released in DoctrineBundle 1.12.4 and 2.0.4. Thanks for your patience!
