### ISSUE TITLE
[Serializer][DX] Existing circular_reference_limit is disturbing

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#34744]
**Symfony version(s) affected**: 4.3

**Description**  
Maybe I missed something (turning it into a documentation issue) but I had this issue for far too much time.

The `AbstractNormalizer::CIRCULAR_REFERENCE_LIMIT` option exists but is never used. The user **must** define its own circular reference handler. Which means this issue is useless. I even didn't see a circular reference handler provided by Symfony that may use this option in the code base. I think it should be deprecated then removed.

**How to reproduce**  
```php

$serializer->serialize($response, 'json', [
    AbstractNormalizer::CIRCULAR_REFERENCE_LIMIT => 2 // Does nothing !
]);
```

**Possible Solution**  
- Deprecate the option
- Say it in the documentation

**Comment by xabbuh** [comment]
I see this being used in `AbstractNormalizer::isCircularReference()` for example

**Comment by Nek-** [comment]
Yeah. I was tired obviously. >.>
