### ISSUE TITLE
[DebugBar] Quick fix needed for copy and paste of route name ;-)

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#34745]
Please can we have a quick fix to the rendering of the route name so that a double click of it allows us to copy (for the purposes of pasting into PHP code) the route name?

The problem at the moment is that the "name" also gets selected, making more work for devs to delete it (or forget it, and cause an error on next page load) 

see: 

![Screen Recording 2019-12-01 at 06 02 PM](https://user-images.githubusercontent.com/400092/69918012-ca355780-1464-11ea-875f-2261116130ce.gif)

**Comment by nicolas-grekas** [comment]
Up for a PR to improve that @PhilETaylor?

**Comment by juuuuuu** [comment]
Cannot reproduce the issue (Linux/Firefox/Profiler 3.4).

@PhilETaylor Which OS/Browser are you using?

**Comment by PhilETaylor** [comment]
Pretty standard iMac with latest google chrome :-)

**Comment by PhilETaylor** [comment]
Firefox on Mac is working as expected. 
![Screen Recording 2019-12-02 at 02 58 PM](https://user-images.githubusercontent.com/400092/69969348-2a370700-1514-11ea-94e4-ce485be67fcf.gif)


The source code is 

```html
<div class="sf-toolbar-info-piece">
    <b>Route name</b>
    <span>myjoomla_admin_dashboard</span>
</div>
```

**Comment by PhilETaylor** [comment]
ok This is a Chrome bug from 2010 that seems to have regressed.

Test this JS Fiddle - https://jsfiddle.net/py28svea/ 

Double clicking AST100393 will highlight `Code:AST100393` in Google Chrome and `AST100393` in other browsers

Chromium bug report from 2010, where someone commented recently 

```
Comment 22 by dis...@gmail.com on Fri, Sep 13, 2019, 8:19 AM GMT+1
After some of the recent updated (now I'm on Version 77.0.3865.75 (Official Build) (64-bit) on Ubuntu 18.04) Chrome started to behave wrongly. You can test it on the file attached in comment #2. Is it a regression?
```



https://bugs.chromium.org/p/chromium/issues/detail?id=39795#c2

Therefore Im closing this as a `wont fix` as its not a symfony bug.

**Comment by PhilETaylor** [comment]
Tagging https://bugs.chromium.org/p/chromium/issues/detail?id=850460 too as thats a recent bug - same issue

**Comment by juuuuuu** [comment]
Part of the solution is in your hand, stop using Chrome ;)
By the way, adding `&nbsp;` like this `<b>Route name&nbsp;</b>` is solving the problem for me in Chrome. Not a real solution, but a workaround for you.

**Comment by PhilETaylor** [comment]
I'm not going to start a browser war ;-) 

The &nbsp; works ... but a bit naff. 

I guess we could do that, or just leave it, seems its only "affecting" me... 

or maybe implement a 3kb JS clipboard helper (https://clipboardjs.com/) and use that when clicking the route name it automatically copies to clipboard.... ?
