### ISSUE TITLE
[Form] CSRF token always invalid with custom html 

### ISSUE THREAD

**Issue by syntaxgirl** [symfony/symfony#34749]
**Symfony version(s) affected**: 4.4.0

**Description**  
When using custom html form with form builder, token always get invalid even if it's present as hidden input. Same happen if the token is manually validated.

**How to reproduce**  
Create form with form builder, add few fields and set defaults with csrf_protection set to true, csrf_field_name with the name of the hidden field of the token and add csrf_token_id to make it more secure. 
Next create html.twig and add form with the inputs fields which you used inside form builder. Add hidden field and add generate token inside input value with {{ csrf_token('_token') }}.
Next create controller create form with the form type created at the beginning, handle request, check if form is submitted and if it's valid.

**Comment by xabbuh** [comment]
Please create a small example application that allows to reproduce your issue.

**Comment by syntaxgirl** [comment]
I have updated to Symfony **4.4.1** and added the token as `{{ form_row(form._token) }}` and everything worked fine.
