### ISSUE TITLE
[Notifier] Add possibility to extract path from provided DSN

### ISSUE THREAD

**Issue by espectrio** [symfony/symfony#34746]
**Description**  
I'm currently working on Microsoft Teams Webhook Notifier (https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook), and there is no way to provide DSN for it, because of missing parse_url()['path'] option

**Example**  

It looks like 
`teams://outlook.office.com/webhook/{uuid}@{uuid}/IncomingWebhook/{id}/{uuid}`
and I'd like to be able to build Notifier Transport endpoint from it

**Comment by espectrio** [comment]
It's possible to use stand-alone property as in mentioned PR
or we can add parsed path to $options array instead under '#path' key to not interfere with possible parse_str() outcomes

**Comment by espectrio** [comment]
Another case is for Microsoft Botframework where DSN would look like:
`botframework://APP_ID:APP_TOKEN@smba.trafficmanager.net/apis`

**Comment by espectrio** [comment]
As seen in #33200 path is already added here.
IMO we should think about #32546 to extract DSN builder because there are many symfony components that uses it's own implementation: e.g. Notifier, Mailer, Messenger, Cache, PDO, Http

**Comment by OskarStark** [comment]
Is there any progress on the MS Teams Implantation? I would really like to use it 👍🏻
