### ISSUE TITLE
[String] FR: snake case but with underscore before numbers

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#34777]
**Description**  
I have not found a way how to convert `Something1` into `something_1` with String component. `snake()` method converts `Something1` into `something1` which I think is correct behaviour.

I wonder what if we added a new method, like `underscore()` that would do the conversion mentioned above?

**Example**  
```php
assertSame('something_1', u('Something1')->underscore()->toString());
```

**Comment by nicolas-grekas** [comment]
`u('Something1')->snake()->replaceMatches('/([^\d])(\d++)/', '\1_\2')` maybe?

**Comment by simPod** [comment]
@nicolas-grekas there are definitely ways to work around this but I'd rather not create my own wrapper around String component to have nice api for this :)

**Comment by nicolas-grekas** [comment]
Closing as discussed on the linked PR.
