### ISSUE TITLE
[Security] isPasswordValid() throws an exception when the user has no password set

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony#34775]
**Symfony version(s) affected**: 4.4.0

**Description**  
I'm getting an exception thrown when a user who has no password set at all (their password field is null, they use another method to log in) attempts to change their password:

![paveikslas](https://user-images.githubusercontent.com/2812673/70036559-afc2c180-15bd-11ea-9e9a-782417a7fd76.png)

I'm not sure if this will be considered a bug, but I don't think that passwordEncoders should assume that the value stored as the password will always be a string.

From looking at the code, it seems that `needsRehash()` is perhaps the only method which makes that assumption. I was about to suggest to allow non-string values in `needsRehash()`, but in this particular case, `needsRehash()` is called as part of checking the supplied password for validity: 
https://github.com/symfony/symfony/blob/6c163906f2ca4e3498061380d8f6b40e374badd2/src/Symfony/Component/Security/Core/Encoder/MigratingPasswordEncoder.php#L51

Presumably, this is to avoid extra checks with other encoders if the password hash appears valid to the current encoder. This doesn't seem necessary, so perhaps just removing this check would be acceptable?

Alternatively, perhaps `$encoded` could be cast to string in that call?

**How to reproduce**  
1. Create a user without a password.
2. Try logging in with that user with a password.

**Comment by xabbuh** [comment]
Can you confirm that #34779 fixes the issue for you?

**Comment by rimas-kudelis** [comment]
I think it does, yes.

**Comment by rimas-kudelis** [comment]
Will the fix make it into the 4.4 branch?

**Comment by xabbuh** [comment]
Yes, we regularly merge branches up into all maintained branches.
