### ISSUE TITLE
 symfony/http-foundation vulnerabilities

### ISSUE THREAD

**Issue by Aravindkrishna2010** [symfony/symfony#34798]
While checking with **synk.io**, we have issues in symfony/http-foundation. 

*I added link below. Please check.*

https://snyk.io/vuln/composer:symfony%2Fhttp-foundation

**Comment by gmponos** [comment]
Some of these versions are not supported any more.. and some others have been alrady patched...

**Comment by fabpot** [comment]
This information probably comes from us anyway.
