### ISSUE TITLE
High memory usage in Symfony 4.4.1

### ISSUE THREAD

**Issue by ilicmsreten** [symfony/symfony#34792]
**Symfony version(s) affected**: 4.4.1/ 4.3.*

**Description**  
After upgrade from `v3.4.36`  to `v4.4.1` we encountered high memory usage in the test environment.

```
Symfony 3.4.36.
Time: 14.72 minutes, Memory: 817.00 MB
Tests: 1411, Assertions: 21790, Skipped: 8.
```
```
Symfony 4.4.1.
Time: 23.38 minutes, Memory: 2.07 GB
Tests: 1411, Assertions: 21790, Skipped: 8.
```

Our test relies on `Symfony\Component\BrowserKit` so we create a simple test with several requests
https://blackfire.io/profiles/compare/01b36bf6-033f-46b6-8c4c-be6cb12cae50/graph

Ignore part with handling a bad request, I think the main  issue is related with `request` method

**Comment by adrienfr** [comment]
Might be the same as https://github.com/symfony/symfony/issues/34687
