### ISSUE TITLE
Error Renderer repo not found

### ISSUE THREAD

**Issue by ujwaldhakal** [symfony/symfony#34799]
My one package uses error renderer but seems like https://github.com/symfony/error-renderer not found on github

**Comment by fancyweb** [comment]
The ErrorRenderer component was never officially released and was finally kind of "merged" into the new ErrorHandler component.

**Comment by ujwaldhakal** [comment]
Ok looks like it was removed recently as my builds were getting failed dnt knw which package was using error handler :) I was using laravel anyways thank for the information. Now i have removed it from lock as i can see errorHandler too

**Comment by xabbuh** [comment]
Thanks for the confirmation. 👍 Let's close here then.
