### ISSUE TITLE
Attempted to call an undefined method named "invalidateTags" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#34800]
**Symfony version(s) affected**: 4.4.1 (probably >3.2)

**Description**  

I'm using a tagAware cache, like so:

```yaml
framework:
    cache:
        pools:
            app.cache_pool:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.apcu
                    - cache.adapter.redis
                tags: true
```

but when using it (in env=dev), I get an error:

  Attempted to call an undefined method named "invalidateTags" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".  
  

**How to reproduce**  

Add config (see above)

```php
use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;

class TestController 
{
  /** @var TagAwareAdapterInterface */
  private $appCachePool;

  // note: automatic Dependency Injection is tied to this interface.. but for PHPStorm we typehint it TagAwareAdapterInterface, because the actual adapter is expected to be TagAware (because of config `tags: true`)
  public function __construct(CacheItemPoolInterface $appCachePool) 
  {
    $this->cache = $appCachePool;
  }

  /** @Route("/test") */
  public function test()
  {
    $this->cache->invalidateTags('sometag');
  }
}
```

**Possible Solution**  

Looks easy enough to add the `TagAwareAdapterInterface` to the `TraceableAdapter` and implement some logic to trace the usage of tags. A separate story could be made to use this info in the profiler to show information about tags being used and invalidated.

Adding the code snippet below was enough to solve the bug. The actual implementation (for the profiler) could be a separate feature request.

```php
class TraceableAdapter implements AdapterInterface, CacheInterface, PruneableInterface, ResettableInterface, TagAwareAdapterInterface

    ...

    public function invalidateTags(array $tags)
    {
        // TODO: Implement invalidateTags() method.
    }
}
```

**Additional context**  

Possibly related to https://github.com/symfony/symfony/issues/20764.

The solution from @pascalwacker in 2017 probably works.. but I think it's an ugly work-around. I personally think we should support the automatic autowire and also make tagAware cache traceable and show it in the profiler at some point (separate feature request probably).

Also note that `tag()` is always available in the `ItemInterface`, which is the default way to use the cache, as used through the cache contracts. This means it's a part of the Symfony eco-system and should be part of it's profiler and autowiring

**Comment by rbaarsma** [comment]
I made a PR for a (hopefully acceptable) quick-fix. https://github.com/symfony/symfony/pull/34803

**Comment by nicolas-grekas** [comment]
That's expected: you type hinted for `CacheItemPoolInterface`, which doesn't provide any `invalidateTags()` methods. You need to type-hint for a tag-aware interface - either `TagAwareAdapterInterface` or `TagAwareCacheInterface`.

**Comment by pascalwacker** [comment]
Not sure if this is the right way forward, as the default Cache Adapter is compatible with [PSR-6](https://www.php-fig.org/psr/psr-6/), so if you want to use a tag aware cache, you should tell Symfony about it.

**Comment by rbaarsma** [comment]
@nicolas-grekas Indeed it works when I typehint `TagAwareCacheInterface`, but then the `TraceableAdapter` is not used, and presumably we don't have profiler info about usage of this cache adapter. 

So I guess I should change the bug description - or create a new bug - about there being no profiler info for TagAware cache? Do you agree?

**Comment by nicolas-grekas** [comment]
Please submit a new issue yes.

**Comment by rbaarsma** [comment]
Also to further complicate the matter, I'm using the `CacheInterface` (contract) to get the same cache where I actually create the cache

```php
    public function __construct(CacheInterface $appCachePool)
    {
        $this->appCachePool = $appCachePool;
    }

    public function findContent(string $id): ?string
    {
        return $this->appCachePool->get("content.$id", static function (ItemInterface $item) {
            $item->tag('content');
            // some logic to warm the cache
        });
    }
```

In my functional test I'm testing this code, but it seems to somehow use the `TraceableAdapter`, which says it's not taggable

```
Symfony\Component\Cache\Exception\LogicException : Cache item "content.publish-content-test-thip.655d7c95-189a-4d59-9738-d84117f9e6af-1549370662" comes from a non tag-aware pool: you cannot tag it.
 /var/www/application/vendor/symfony/cache/CacheItem.php:117
 /var/www/application/src/Content/Repository/ContentRepository.php:40
 /var/www/application/vendor/symfony/cache/Adapter/TraceableAdapter.php:51
 /var/www/application/vendor/symfony/cache/LockRegistry.php:87
 /var/www/application/vendor/symfony/cache/Traits/ContractsTrait.php:88
 /var/www/application/vendor/symfony/cache-contracts/CacheTrait.php:68
 /var/www/application/vendor/symfony/cache/Traits/ContractsTrait.php:95
 /var/www/application/vendor/symfony/cache-contracts/CacheTrait.php:30
 /var/www/application/vendor/symfony/cache/Adapter/ChainAdapter.php:101
 /var/www/application/vendor/symfony/cache/LockRegistry.php:99
 /var/www/application/vendor/symfony/cache/Traits/ContractsTrait.php:88
 /var/www/application/vendor/symfony/cache-contracts/CacheTrait.php:68
 /var/www/application/vendor/symfony/cache/Traits/ContractsTrait.php:95
 /var/www/application/vendor/symfony/cache-contracts/CacheTrait.php:30
 /var/www/application/vendor/symfony/cache/Adapter/ChainAdapter.php:101
 /var/www/application/vendor/symfony/cache/Adapter/ArrayAdapter.php:62
 /var/www/application/vendor/symfony/cache/Adapter/ChainAdapter.php:101
 /var/www/application/vendor/symfony/cache/Adapter/ChainAdapter.php:112
 /var/www/application/vendor/symfony/cache/Adapter/TraceableAdapter.php:56
 /var/www/application/src/Content/Repository/ContentRepository.php:61
 /var/www/application/tests/functional/Content/Repository/ContentRepositoryTest.php:44
 ```

**Comment by rbaarsma** [comment]
nvm my last comment. If you use the `TagAwareCacheInterface` (instead of the PSR-6 TagAwareAdapterInterface), it works fine in automated tests.

**Comment by nicolas-grekas** [comment]
`CacheInterface` doesn't allow using tags, use `TagAwareCacheInterface` instead.

**Comment by rbaarsma** [comment]
Closing in favor of more to the point new issue https://github.com/symfony/symfony/issues/34810
