### ISSUE TITLE
[phpunit-bridge] phpunit.xml.dist brake installation on php 7.0

### ISSUE THREAD

**Issue by TL-Luca-Ricci** [symfony/symfony#34809]
**Symfony version(s) affected**:
- Symfony 3.4.36
- symfony/phpunit-bridge 
- php 7.0.33

**Description**  
requiring symfony phpunit-bridge on a php7.0 machine (debian 9 lts) download a phpunit.xml.dist file that force phpunit7.5 that doesn't run on php7.0 (phpunit6.5 required as from the default in simple-phpunit.php)

**How to reproduce**  
on a machine with php7.0
composer require --dev symfony/phpunit-bridge
./bin/phpunit

**Possible Solution**  
maybe removing SYMFONY_PHPUNIT_VERSION from phpunit.xml.dist file?

**Additional context**  
simple-phpunit.php script falls back to phpunit.xml.dist if phpunit.xml isn't found, is it actually fine to use .dist files as fallbacks?

**Comment by xabbuh** [comment]
We have a block like this:

```php
if (PHP_VERSION_ID >= 70100) {
    // PHPUnit 7 requires PHP 7.1+
    $PHPUNIT_VERSION = $getEnvVar('SYMFONY_PHPUNIT_VERSION', '7.4');
} elseif (PHP_VERSION_ID >= 70000) {
    // PHPUnit 6 requires PHP 7.0+
    $PHPUNIT_VERSION = $getEnvVar('SYMFONY_PHPUNIT_VERSION', '6.5');
} elseif (PHP_VERSION_ID >= 50600) {
    // PHPUnit 5 requires PHP 5.6+
    $PHPUNIT_VERSION = $getEnvVar('SYMFONY_PHPUNIT_VERSION', '5.7');
} else {
    $PHPUNIT_VERSION = '4.8';
}
```

Based on that I would expect that you get PHPUnit 6.5. Do you by chance override `SYMFONY_PHPUNIT_VERSION` somewhere?

**Comment by stof** [comment]
@xabbuh I think the recipe is forcing a version.

**Comment by xabbuh** [comment]
I don't see anything like that in the current version of the recipe.

**Comment by TL-Luca-Ricci** [comment]
The simple-phpunit.php file is fine, is there that I found what was wrong. when you require the phpunit-bridge for the first time it generate a phpunit.xml.dist in your project dir that override the default from the script

**Comment by xabbuh** [comment]
Does it mean you were able to solve your issue?

**Comment by TL-Luca-Ricci** [comment]
Yes, I already solved my problem when I posted this issue, I posted it to fix it for others.

**Comment by xabbuh** [comment]
Thanks, I now understand the issue. That specific line can be found here: https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/4.1/phpunit.xml.dist#L15

**Comment by xabbuh** [comment]
I have opened an issue in the recipes repository so we can further discuss the matter there (see symfony/recipes#701).
