### ISSUE TITLE
[Messenger] Messenger failed commands not available in CLI.

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony#34806]
**Symfony version(s) affected**: 4.4

**Description**  
When trying to run `messenger:failed:show`, no command is found. The output is:

```
  There are no commands defined in the "messenger:failed" namespace.

  Did you mean this?
      messenger
```

The FailedMessagesShowCommand is in the vendors and consuming messages work just fine.

**How to reproduce**  
Running the following command: `messenger:failed:show`

**Possible Solution**  

**Additional context**  
One thing I noticed: All working commands directly inherit from `Command`. All none-working commands inherit from `AbstractFailedMessagesCommand`.

<img width="673" alt="Bildschirmfoto 2019-12-04 um 10 15 11" src="https://user-images.githubusercontent.com/5689499/70129405-f7f5e880-167e-11ea-98fb-8b9a2c8514cf.png">

**Comment by fancyweb** [comment]
Those commands are only available when the "failure_transport" is configured. Did you configure it?

Status: waiting feedback.

**Comment by CoalaJoe** [comment]
Thanks a lot. I forgot to uncomment the config.
