### ISSUE TITLE
Annotated return type on HttpFoundation\Response::getContent seems unnecassarily wide

### ISSUE THREAD

**Issue by bdsl** [symfony/symfony#34818]
**Symfony version(s) affected**: v5.0.1, v5.0.0, v4.4.0, v4.3.9. v4.3.8,  v4.3.9 v4.3.8 v4.3.7 v4.3.6 v4.3.5 v4.3.4 v3.4.36 v3.4.35 v3.4.34 v3.4.33 v3.4.32 v3.4.31

**Description**  
The function HttpFoundation\Response::getContent is annotated with: https://github.com/symfony/symfony/blob/c732122b574ecfb083d44324ac18f9508e95471d/src/Symfony/Component/HttpFoundation/Response.php#L399

Before commit ef5ead00059fc32 it was just https://github.com/symfony/symfony/blob/1f7250139f6c81d0e63a902035df21d067f412d8/src/Symfony/Component/HttpFoundation/Response.php#L410 

which is a lot easier to work with when writing staticly analysed code. Because of the change Psalm is giving me many `PossiblyFalseArgument` errors.

The implementation of getContent simply returns the value of the content property, which is still annotated as string https://github.com/symfony/symfony/blob/c732122b574ecfb083d44324ac18f9508e95471d/src/Symfony/Component/HttpFoundation/Response.php#L91 I'm not clear on why the return type should be wider than the property type.

**Possible Solution**  
Change the annotation to `@return string`

As a workaround, callers can cast the returned value to string, or if using Psalm and mostly having trouble in test cases as I am tell it to suppress the `PossiblyFalseArgument` errors in the test directory.

**Comment by ro0NL** [comment]
Looks like a bug

https://github.com/symfony/symfony/blob/c732122b574ecfb083d44324ac18f9508e95471d/src/Symfony/Component/HttpFoundation/Response.php#L90-L93

**Comment by nicolas-grekas** [comment]
That's the interface:
https://github.com/symfony/symfony/blob/ef5ead00059fc321e7fda20c2dfdd4440585be26/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L339

**Comment by ro0NL** [comment]
i missed this "interface" :sweat_smile: 

isnt throwing (or returning the actual contents lazy) still considerable, e.g. currently `BinaryFileResponse::__toString` looks incompatible :thinking:

**Comment by bdsl** [comment]
I missed it too, but I see that the annotation needs to be as it is, and I suppose shouldn't be changed until Symfony 6 because code outside Symfony may extend `Response`, and narrowing the return type would break compatility with those extensions.

**Comment by bdsl** [comment]
I will look for an alternative way to test. The problem came up in tests because I have an `\Symfony\Component\HttpKernel\HttpKernelBrowser` object, and I'm effectivly calling `json_decode($browser->getResponse()->getContent())`. `json_decode` needs a string.
