### ISSUE TITLE
[String] Slugify a string with an apostrophe

### ISSUE THREAD

**Issue by carlog80** [symfony/symfony#34822]
Using the String component (love it btw) v5.0.1 and the AsciiSlugger class to slugify a string, I noticed that apostrophes are not removed but they are replaced with the default dash separator.

Example:

`(new AsciiSlugger())->slug("I'll see")` result is **I-ll-see** instead of **ill-see**

I temporarily fixed adding a replace in my custom slugify method that extend the UnicodeString class:

```php
public function slugify(): self
{
    $str = clone $this->folded()->replace('\'', '');

    $str->string = (string) (new AsciiSlugger())->slug($str->string);

    return $str;
}
```

Will it be possible to replace apostrophes by default in future release? Thanks :)

**Comment by stof** [comment]
well, why would it be an issue to replace apostroph by a dash, when we already do it for all other chars not allowed in the slug ? Why making only the apostroph char different ?

**Comment by carlog80** [comment]
> well, why would it be an issue to replace apostroph by a dash, when we already do it for all other chars not allowed in the slug ? Why making only the apostroph char different ?

Because in many functions that i used in the past (like Stringy) to slugify a string the apostrophe was replaced by default with nothing and not with the separator. Some online services do the same thing. (https://blog.tersmitten.nl/slugify/, https://slugify.online/)

Honestly, I don't know which way is the correct one. If I was wrong about it, I apologize.

**Comment by ro0NL** [comment]
IMHO `ill` and `i'll` should produce different slugs. Those services seem to replace any non-word character or so.

e.g. `d$d` gives `dd` / `ddollard`. Whereas i think `d-d` / `d-dollar-d` would be human readable.

**Comment by carlog80** [comment]
> IMHO `ill` and `i'll` should produce different slugs. Those services seem to replace any non-word character or so.
> 
> e.g. `d$d` gives `dd` / `ddollard`. Whereas i think `d-d` / `d-dollar-d` would be human readable.

I agree with you, even for me this way is more readable. But there are many sites that use another way to do that.

For example, this card of an horse named **Smith's Bay** become **smiths-bay** on this site url (https://www.racingpost.com/profile/horse/1765131/smiths-bay/form) and there are many sites that doing the same thing.

On my side, for back-compatibility, I replaced the apostrophes. I thought it was an issue but I was wrong.

**Comment by ro0NL** [comment]
it's funny how for cosmetic reasons everybody expects this :grin: 

https://github.com/todda00/meteor-friendly-slugs/issues/11 / https://github.com/norman/friendly_id/issues/329

i somewhat agree `'s` is a special case :)

**Comment by ro0NL** [comment]
there are also sites not doing it: https://symfony.com/blog/let-s-talk-at-symfonycon

i tend to believe it's matter of preference mostly. Personally i couldnt care less if the url says `lets` or `let-s`.

**Comment by carlog80** [comment]
> there are also sites not doing it: https://symfony.com/blog/let-s-talk-at-symfonycon
> 
> i tend to believe it's matter of preference mostly. Personally i couldnt care less if the url says `lets` or `let-s`. I guess ideally it expands to `let-us`

If I had to make slug for a blog or similar honestly I didn't care too much about aesthetics but it's a case of "reverse engineering" so I have to generate an url with slug and other info inside a php crawler developed by me years ago...it's long story... :stuck_out_tongue_closed_eyes:

**Comment by stof** [comment]
@carlog80 we cannot tailor the component behavior specifically for the reverse-engineered algorithm of a specific site, otherwise we would have to build tons of algorithms in the component (as there is no standardized algorithm for generating a slug).
If your needs are to reproduce the behavior of another site, I suggest you to implement the slug generation yourselves so that you can reverse-engineer all details.

**Comment by xabbuh** [comment]
I agree with @stof here. And since there is no real downside in the current implementation I think we can safely close here. Thank you all for the discussion.
