### ISSUE TITLE
[Process] Process::fromShellCommandline() raises exception when command contains bash/shell variables

### ISSUE THREAD

**Issue by fideloper** [symfony/symfony#34838]
**Symfony version(s) affected**: 4.4.x

**Description**  

This affects when the commands passed to Process are strings, instead of arrays (which some commands need in order to process correctly).

The assumption here is the use of the `Process::fromShellCommandline()` static method.

When a command string includes variables that the command itself sets, Process returns exception `Command line is missing a value for key %s: %s.` from method [`replacePlaceholders`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L1592-L1601).

These variables may not be able to be predefined as environment variables, leading us to a situation where we cannot move forward.

**How to reproduce**  

```php
// Multi-line command which includes a shell/bash variable that is not parsed by PHP:

$cmd = 'SOMECOUNT=0
if [[ "$SOMECOUNT" == 0 ]]; echo "it is zero"; fi'

$p = Process::fromShellCommandline($cmd);
$p->run(); 
```

Result:

```
Symfony/Component/Process/Exception/InvalidArgumentException with message 'Command line is missing a value for key "$SOMECOUNT": SOMECOUNT=0
if [[ "$SOMECOUNT" == 0 ]]; echo "it is zero"; fi.'
```

**Possible Solution**  

I've so far only been able to get around this via this "trick", which replaces the variable `$SOMECOUNT` with an equivalent string content:

```php
$cmd = 'SOMECOUNT=0
if [[ "$SOMECOUNT" == 0 ]]; echo "it is zero"; fi'

$p = Process::fromShellCommandline($cmd);
$p->run(null, ['SOMECOUNT' => '$SOMECOUNT']); 
```

**Additional context**  

This doesn't happen in all cases. For example, this works:

```php
$cmd = 'SOMETHINGGENERATED=`date +"%m-%d-%y"`; echo $SOMETHINGGENERATED';
$p = Process::fromShellCommandline($cmd);
$p->run(); // No exception
```

I don't know what the difference is between the 2. Perhaps something in the regex.

**Comment by nicolas-grekas** [comment]
You can use `"${SOMECOUNT}"` to work around the issue also, that'd be better I think.

Shell command lines are a nightmare.

Use the constructor if you can, providing an array as argument, with the shell as the command, then `-c`, then the script. If you can.

**Comment by fideloper** [comment]
I’ll try that out, thanks much!

**Comment by fideloper** [comment]
(While I'm still not sure I like this feature in general in Symfony - which is to say, I don't understand the use case for its existence - using the `${FOO}` format worked for me in Mac/*Nix environments. Not sure it would work in Windows, but luckily I don't need to care).

**Comment by nicolas-grekas** [comment]
Revert proposed in #34845
