### ISSUE TITLE
[HttpClient] ClientInterface::stream() throws multiple times on same response

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#34837]
**Symfony version(s) affected**: 4.4

**Description**  

When using the `stream()` method, there's an exception thrown for every single chunk of the same response.

**How to reproduce**  

1. `composer require symfony/http-client ^4.4`
2. `php reproducer.php`

Here's the `reproducer.php`:

```php
<?php

include_once 'vendor/autoload.php';

$client = \Symfony\Component\HttpClient\HttpClient::create();

$responses = [];
$responses[] = $client->request('GET', 'https://httpstat.us/500');

foreach ($client->stream($responses) as $response => $chunk) {
    try {
        $response->getHeaders();
    } catch (\Exception $e) {
        var_dump($e->getMessage());
    }
}
```

In my case, I get this:

```
string(74) "HTTP/1.1 500 Internal Server Error returned for "https://httpstat.us/500"."
string(74) "HTTP/1.1 500 Internal Server Error returned for "https://httpstat.us/500"."
string(74) "HTTP/1.1 500 Internal Server Error returned for "https://httpstat.us/500"."
```

So the exception is thrown 3 times.

**Possible Solution**  

If I understood the internals of HttpClient enough, I would've provided a PR right away 🙈

**Comment by nicolas-grekas** [comment]
Oh, this one is normal!
An `HttpExceptionInterface` doesn't interupt the stream: a 500 might be a response you want to read, so all chunks are yield.
A `TransportExceptionInterface` would mean the stream is interupted.

**Comment by Toflar** [comment]
Ah, I see. Let me update the docs then :)
