### ISSUE TITLE
Failed login attempts are logged as error

### ISSUE THREAD

**Issue by Fl0ux** [symfony/symfony#34836]
**Symfony version(s) affected**: 4.4.1

**Description**  
Every failed login attempts are logged as errors : 

`[2019-12-05T11:47:47.157808+01:00] security.ERROR: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/foulques/PhpstormProjects/MonAvisCitoyenV2/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"18691mac@yopmail.com\" not found. at /home/foulques/PhpstormProjects/MonAvisCitoyenV2/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:65)"} []`

... and every time I receive a mail to warn me about this...

**How to reproduce**  
Try to log in with bad credentials and watch logs.

**Additional context**  
Commit who changed the log type from "info" to "error" : https://github.com/symfony/symfony/commit/867eb78cfea8d45334faddbbf1ad62b52fe5ed1a#diff-f074ae27e23362de22ea81ae1c51ac65
Pull request that talk about this change : https://github.com/symfony/symfony/pull/28462

**Comment by edefimov** [comment]
I also would like to revert the pull request discussed in #28462. Moreover there is [another](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordJsonAuthenticationListener.php#L176) place in code with exactly the same message but different logging level what makes the system behave different on the same situation.
I think notice level would be the best choice here.

**Comment by COil** [comment]
I can confirm. I now receive slack notifications when authentication fails.

```
@slackAPPLI 19 h 48
Message
Authentication request failed.
Level
ERROR
Aujourd’hui à 19 h 48
```

**Comment by weaverryan** [comment]
We're also getting our logs now filled with all login failures. I think we either need to revert this or fix it somehow: it's the only case (I can think of) where an `->error()` is logged that can be caused by normal user activity - other than 4xx errors, but ones like 404 can be filtered out (and this case can't because it is a 302 for a login form).

Status: reviewed
