### ISSUE TITLE
[HttpClient] ResponseInterface contract misses  `toStream` signature

### ISSUE THREAD

**Issue by Devristo** [symfony/symfony#34834]
**Symfony version(s) affected**: 4.4 and 5.0

**Description**  
Since the release of Symfony 4.4 and 5.0 the HttpClient can return responses as stream. See https://symfony.com/doc/current/components/http_client.html#processing-responses .

However the `\Symfony\Contracts\HttpClient\ResponseInterface` lacks the signature of `toStream()` (https://github.com/symfony/symfony/blob/master/src/Symfony/Contracts/HttpClient/ResponseInterface.php). 

Of course the functionality still works, but the feature is not discoverable in IDEs and static analysis will error out as well.

I will create a PR to add this signature shortly.

**Comment by nicolas-grekas** [comment]
I didn't add the method to `ResponseInterface` on purpose: adding it would make the contract very difficult to implement separately, and would make it harder to use for decorators. Another argument for not adding it is that it's possible to implement `toStream()` with the current `HttpClientInterface` (which is bound to `ResponseInterface`). An idea might be to make is a separate interface. Or there may be another better idea. Dunno.
For thoughts :)

**Comment by Devristo** [comment]
You are right, I now understand the implications. But it is quite unfortunate that the only way this feature is discoverable is by looking at the documentation of the component on the site. Can't think of a nice solution at the time though.

**Comment by stof** [comment]
@nicolas-grekas Given that converting to stream is possible on top of the existing ResponseInterface according to what you said, shouldn't we rather move this implementation to a separate helper class taking a response as argument of the method ? That way, it would be usable also when decorators are involved (with the method in the Response but not the interface, it is totally lost if the response get decorated, forcing to actually implement the helper I'm suggesting AFAICT).

**Comment by nicolas-grekas** [comment]
@stof there is [StreamWrapper::createResource()](https://github.com/symfony/symfony/blob/c732122b574ecfb083d44324ac18f9508e95471d/src/Symfony/Component/HttpClient/Response/StreamWrapper.php#L52) for that but it's not as powerful as toStream, for internal detail reasons. That's why `$response->toStream()`: the implementation is better because we have access to internal state.

**Comment by Devristo** [comment]
Nice, didn't know about `StreamWrapper`.

**Comment by nicolas-grekas** [comment]
Let's do something:
`StreamWrapper::createResource()` should call `$response->toStream()` when possible and it's the only argument provided.

**Comment by Devristo** [comment]
:+1 

It gets the job done. The only thing is that the call stack will be quite confusing (createResource() -> toStream() -> createResource()).

**Comment by nicolas-grekas** [comment]
@Devristo up for a PR doing so?

**Comment by Devristo** [comment]
Yes, will put it on my list :)
