### ISSUE TITLE
TranslatorInterface not compatible with LocalAwareInterface

### ISSUE THREAD

**Issue by ampersand** [symfony/symfony#34840]
**Symfony version(s) affected**: ?

**Description**  

- Laravel Version: 6.6.2
- PHP Version: 7.3.10

Running `composer update` on a Laravel v6.6.2 project will install:
- symfony/translation (4.4.1)
- symfony/translation-contracts (2.0.1)

Within these packages TranslatorInterface extends from LocalAwareInterface.  However  the `setLocale` methods are not compatible.

- [TranslatorInterface::setLocale](https://github.com/symfony/translation/blob/v4.4.1/TranslatorInterface.php#L62)
- [LocaleAwareInterface::setLocale](https://github.com/symfony/translation-contracts/blob/v2.0.1/LocaleAwareInterface.php#L23)

The results in the following error being generated.
> Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) 

**How to reproduce**  

```
composer create-project --prefer-dist laravel/laravel blog
```

**Possible Solution**  
Update `setLocale` to be compatible or update package dependencies?

**Additional context**  
Originally reported at https://github.com/laravel/framework/issues/30769

**Comment by xabbuh** [comment]
Please use the search (see for example #34692).

**Comment by ampersand** [comment]
Sorry for the trouble. I found that my web server and CLI versions of PHP were different.
