### ISSUE TITLE
PHP 7.4.0 + symfony/console 4.3.9

### ISSUE THREAD

**Issue by denma-fr** [symfony/symfony#34855]
**Symfony version(s) affected**: 4.3.9
symfony/console 4.3.9

**Description**  

Issue with php7.4.0-cli and symfony/console with a clean installation of symfony 4.3.6 and Laravel 6.2.
When I use php bin/console the follow issues are :
 - with Laravel : Wrong interpretation of characters & Frozen command line tool
 - with Symfony : Frozen command line tool

**How to reproduce**  

- Create a new Symfony or Laravel project with Composer command line.
- Execute php bin/console command

Command line tool used : Git bash

**Possible Solution**  

Use php-cli <7.3

**Additional context**  

![image](https://user-images.githubusercontent.com/22539649/70325339-0df7da80-1832-11ea-99d0-ec076a1d89fb.png)

**Comment by denma-fr** [comment]
Wrong characters issue are fixed in symfony/console 4.3.9.
Still, there is the command line who doesn't return anything when you use twice php bin/console.
Don't work with MINGW.
Work with windows command line.

**Comment by nicolas-grekas** [comment]
@denma-fr would you be able to debug this issue and maybe provide a fix?
I fear this is specific to your environment and only someone that experiences the issue could be able to fix it.

**Comment by stof** [comment]
PHP 7.4.0 has a bug on Windows regarding the handling of pipes. This will be fixed in 7.4.1.
For instance, the QuestionHelper is broken on Windows when running on PHP 7.4.0.

This issue might be related to the same bug.

**Comment by nicolas-grekas** [comment]
Closing then, please report back if the issue remains with PHP 7.4.1+

**Comment by birneos** [comment]
I ve the same issue with PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:32) ( ZTS Visual C++ 2017 x64 )
