### ISSUE TITLE
4.4.0 trigger_error E_USER_WARNING or E_USER_NOTICE result in ErrorException

### ISSUE THREAD

**Issue by Allmytc** [symfony/symfony#34851]
**Symfony version(s) affected**: 4.4.0

**Description** 
In any Controller of my project if I use trigger_error("message", E_USER_WARNING) or trigger_error("message", E_USER_NOTICE), I have a ErrorException.

**How to reproduce**  
Just put a trigger_error("message", E_USER_WARNING) in a method.

**Possible Solution**  

**Additional context**  
Php version : 7.1.3

**Comment by nicolas-grekas** [comment]
This looks like the same as #34968, which provides this solution:
>  replace the use Symfony\Component\Debug\Debug; to use Symfony\Component\ErrorHandler\Debug;

(in `public/index.php` and `bin/console`)

Does that fix it for you also?
