### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) 

### ISSUE THREAD

**Issue by BlankHat1610** [symfony/symfony#34870]
I have the same error but when i try to do what others said but it doesn't work, what should I do, please help me
file project/composer.json

>     "require": {
>         "php": "^7.2",
>         "fideloper/proxy": "^4.0",
>         "laravel/framework": "^6.2",
>         "laravel/tinker": "^2.0"
>     },

and file symfony/translation-contracts/composer.json

>     "require": {
>         "php": "^7.2.5"
>     },

**Comment by xabbuh** [comment]
Please use the search. You need to run your application using PHP 7.2 or higher.
