### ISSUE TITLE
MySQL8.0 caching_sha2_password

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#34874]
**Symfony version(s) affected**: 5.0.1

**Description**  
Doctrine doesn't work with mysql8.

> In AbstractMySQLDriver.php line 106:
> 
>   An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the c
>   lient
> 
> 
> In PDOConnection.php line 31:
> 
>   SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
> 
> 
> In PDOConnection.php line 27:
> 
>   SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
> 
> 
> In PDOConnection.php line 27:
> 
>   PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]
> 

**How to reproduce**  
Connect to mysql8 with any doctrine command from console.

**Possible Solution**  
Mmm, have to add caching_sha2_password encoder...?

**Additional context**  
-

**Comment by Vandetho** [comment]
it seems that you just need to set default value in my.conf file to 
default_authentication_plugin=mysql_native_password
and the error is gone

**Comment by RSalo** [comment]
> it seems that you just need to set default value in my.conf file to
> default_authentication_plugin=mysql_native_password
> and the error is gone

It's workaround but not solution...

**Comment by Devristo** [comment]
It is a PHP / PDO problem though, not a Symfony one. Did you try PHP 7.4.0 ?

https://github.com/php/php-src/commit/4f06e67ad2201390ed35a9ea6288a00c0b04782b

**Comment by RSalo** [comment]
> It is a PHP / PDO problem though, not a Symfony one. Did you try PHP 7.4.0 ?
> 
> [php/php-src@4f06e67](https://github.com/php/php-src/commit/4f06e67ad2201390ed35a9ea6288a00c0b04782b)

Nope. I use 7.3.

**Comment by xabbuh** [comment]
Thank you for reporting. I am closing here nonetheless since there is nothing we can do in Symfony about that as said by @Devristo.

**Comment by hackdavid** [comment]
if you are facing "caching_sha2_password" error during connectivity of your mysql database using python ,
go through this
https://www.youtube.com/watch?v=YNq-EuQEJos
