### ISSUE TITLE
[HttpKernel] getProjectDir() dependency issue

### ISSUE THREAD

**Issue by wickedOne** [symfony/symfony#34885]
**Symfony version(s) affected**: ^3.3 | ^4.0 | ^5.0

**Description**  
the ``getProjectDir()`` function of the HttpKernel relies on the presence of a ``composer.json`` file
https://github.com/symfony/symfony/blob/ae00ff4cfaa377870289cd3e4adf271d1a747049/src/Symfony/Component/HttpKernel/Kernel.php#L288
which makes it impossible to delete the ``composer.json`` file prior to deployment

**How to reproduce**  
remove the ``composer.json`` file from your application root and try to run it

**Possible Solution**  
for symfony ^4.0 | ^5.0 wouldn't it make more sense to rely on a file which is needed by the application to run and is specific to it, like ``.env``?

**Comment by mbabker** [comment]
> for symfony ^4.0 | ^5.0 wouldn't it make more sense to rely on a file which is needed by the application to run and is specific to it, like `.env`?

That couples the component to a file used in a Symfony or Laravel application, whereas `composer.json` is PHP agnostic.

If you follow [the Kernel recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php) then this method is overridden to hardcode the path and not rely on being able to dynamically determine the project directory.

**Comment by fabpot** [comment]
@mbabker gave the right solution.

**Comment by yannoff** [comment]
> > for symfony ^4.0 | ^5.0 wouldn't it make more sense to rely on a file which is needed by the application to run and is specific to it, like `.env`?
> 
> That couples the component to a file used in a Symfony or Laravel application, whereas `composer.json` is PHP agnostic.
> 
> If you follow [the Kernel recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php) then this method is overridden to hardcode the path and not rely on being able to dynamically determine the project directory.

Why the hell would a `composer.json` file be more framework agnostic than a `.env` file ???
