### ISSUE TITLE
[Messenger] AMQP Decoding FlattenException from Messenger gives NotNormalizableValueException when previous exception is null

### ISSUE THREAD

**Issue by monteiro** [symfony/symfony#34898]
**Symfony version(s) affected**: 4.4,5

**Description**  

When there is an flatten exception without a previous inside the message and tries to decode it, I get an error:

```
[Symfony\Component\Serializer\Exception\NotNormalizableValueException]                                                                              
  Failed to denormalize attribute "previous" value for class "Symfony\Component\ErrorHandler\Exception\FlattenException": Expected argument of type   
  "Symfony\Component\Debug\Exception\FlattenException", "null" given at property path "previous"..           
```

**How to reproduce**  

0. Configure messenger to use a middleware that throws your own exception.
1. fail a message from the queue with an exception (throw new \InvalidArgumentException('some error')), putting that in the handler
2. Force it to go the failed queue.
3. Execute `bin/console messenger:consume failed` to read message from failed queue.
4. The exception is thrown and message is discarded from the queue because of the decoding exception.

**Possible Solution**  

Don't know how to solve this... Should it be in the FlattenException itself, ObjectNormalizer or even the Messenger to prevent the previous null somehow.

**Additional context**  

I thought the problem was the middleware throwing its own exception (instead of the `HandlerFailedException`) but no. Same error remains. 

It tries to serialize into a flatten exception with previous:null... The problem is that when decoding using the Serializer it calls `setPrevious(null)` which is not possible with the FlattenException class from ErrorHandler, because type is required and cannot be null.

**Comment by weaverryan** [comment]
Is this the same as #32719?

**Comment by monteiro** [comment]
@weaverryan yes, seems to me this PR https://github.com/symfony/symfony/pull/33650/files will fix the issue.

**Comment by xabbuh** [comment]
Let's close this in favour of #32719 then.

**Comment by shubaivan** [comment]
@monteiro only need replace deprecated class `Symfony\Component\Debug\Exception\FlattenException` to `Symfony\Component\ErrorHandler\Exception\FlattenException`. And everything works like a charm
