### ISSUE TITLE
[ErrorHandler] Breaks json headers when updating to 4.4.1

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#34893]
**Symfony version(s) affected**: 4.4.1

**Description**  

Hello I have a problem with the update to symfony 4.4.1 and the response headers. I am upgrading from 4.3.9 to 4.4.1

From my CI:
```
SendTemplateEmailControllerTest::whenVersionDoesNotExistThenItMustReturnNotFound
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'application/json'
+'application/x-www-form-urlencoded'
```

Line that fails:

```
        $this->assertSame('application/json', $response->headers->get('content-type'));
```

I got this error when i set up in twig.yaml according to [UPGRADE.md](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#twigbundle):

```
exception_controller: null
```

I also tried in the framework.yaml:
```
    error_controller: 'error_controller'
```

But setting this inside `framework.yaml` seems to work again (make my tests pass):
```
error_controller: 'twig.controller.exception::showAction' this seems to work
```

Also my route contains this: 

```
defaults={"domain"="%email_api_primary_domain%", "_format"="json"},
```

So what I expect is to get a json response in case of an error.

**Extra context**

TBH if this is a misconfiguration of mine I can not really how to fix this. 
I read this:
https://symfony.com/blog/new-in-symfony-4-4-errorhandler-component?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+symfony%2Fblog+%28Symfony+Blog%29

And the changelog:
https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#twigbundle

And also tried slack channel for help... :)

**Comment by gmponos** [comment]
btw I also have a branch for upgrading to sf5... same error happens there as well.

**Comment by yceruto** [comment]
Hi @gmponos, do you have the Serializer component installed and enabled in your tests suite config?

**Comment by yceruto** [comment]
> error_controller: 'twig.controller.exception::showAction' this seems to work (edited)

It's not needed if you don't have a custom error controller, also this class/service `twig.controller.exception::showAction` is deprecated.

**Comment by yceruto** [comment]
We recently updated this doc https://symfony.com/doc/current/controller/error_pages.html#testing-error-pages-during-development

**Comment by gmponos** [comment]
Wait wait... Please read again my initial post.. if I am not clear reach to me through slack..  

1. Yes.. I have serializer enabled.
2. No I didn't have a custom error controller.. but setting `exception_controller: null` according to changelog is breaking my tests hence my responses..
3. I know that `twig.controller.exception::showAction` is deprcated... Setting it inside `framework.yaml` `twig.controller.exception::showAction` is a temp solution. I first tried this `error_controller: 'error_controller'`
4. I read that article too.. I don't want to override the controller.. I want the headers to be set as before.. meaning that if my route has the `format` json it should return a json content type in headers...

**Comment by gmponos** [comment]
It seems that before this was done here: https://github.com/symfony/symfony/blob/v4.3.9/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php#L71

But I can't seem to find a similar functionality to the new component.

**Comment by yceruto** [comment]
It's determined here:
https://github.com/symfony/symfony/blob/6e44447e5d9ff1b5f28a65624741eb993e4a55e9/src/Symfony/Component/HttpFoundation/Response.php#L271-L277

> No I didn't have a custom error controller.. but setting exception_controller: null according to changelog is breaking my tests hence my responses..

Note that if you've changed the default error controller you'll need also change the tested response content. However, the content-type should be the same as before.

Could you provide a small reproducer app?

**Comment by gmponos** [comment]
Well before it was getting from `$request->getRequestFormat()` could it be that the issue is that now it gets it from 

```
                 $format = $request->getPreferredFormat(); 
```

Will try to change the current line before a reproducer..

**Comment by yceruto** [comment]
> defaults={"domain"="%email_api_primary_domain%", "_format"="json"},

the `_format` attribute has top priority in the preferrer algorithm, so `$request->getRequestFormat()` should work fine and return the same as `$request->getPreferredFormat()` in this case.

**Comment by yceruto** [comment]
Could you show us the code of this functional test?

**Comment by gmponos** [comment]
> Well before it was getting from $request->getRequestFormat() could it be that the issue is that now it gets it from

Yea the above has nothing to do..


This is one of the test that fails and I can share...
```
    /**
     * @test
     */
    public function whenInvalidHttpMethodIsUsedThenMethodIsNotAllowedMustBeReturned()
    {
        $faker = Factory::create();
        $faker->seed();

        $method = $faker->randomElement([
            Request::METHOD_GET,
            Request::METHOD_DELETE,
            Request::METHOD_PUT,
            Request::METHOD_OPTIONS,
            Request::METHOD_PATCH,
            Request::METHOD_CONNECT,
            Request::METHOD_TRACE,
            Request::METHOD_PURGE,
        ]);

        $this->client->request($method, '/send/template');
        $this->assertStatusCode(405, $this->client);
        $response = $this->client->getResponse();
        $this->assertSame('application/json', $response->headers->get('content-type'));
        $content = \GuzzleHttp\json_decode($response->getContent(), true);
        $this->assertSame(405, $content['error']['code']);
        $this->assertSame('Method Not Allowed', $content['error']['message']);
    }
```

Will try to give a reproducer.. but most probably not today...

**Comment by gmponos** [comment]
btw I know that I must also fix the next lines too: 

```
        $this->assertSame(405, $content['error']['code']);
        $this->assertSame('Method Not Allowed', $content['error']['message']);
```

**Comment by gmponos** [comment]
Btw this works:

```
<?php

declare(strict_types=1);

namespace App\Serializer;

use Symfony\Component\ErrorHandler\Exception\FlattenException;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class ApiProblemNormalizer implements NormalizerInterface
{
    public function normalize($exception, string $format = null, array $context = [])
    {
        if (!$exception instanceof FlattenException) {
            throw new \Exception();
        }

        if ($format === 'json') {
            $exception->setHeaders(['Content-Type' => 'application/json']);
        }

        return [
            'error' => [
                'code' => $exception->getStatusCode(),
                'message' => $exception->getStatusText(),
            ],
        ];
    }

    public function supportsNormalization($data, string $format = null): bool
    {
        return $data instanceof FlattenException;
    }
}

```

But I consider it a hack.. also i believe it is enough to prove that the problem is that the exception does not contain the header and there is where the problem is... Never the less it takes more time for me for a reproducer.. will try to give one tomorrow...

**Comment by yceruto** [comment]
Yes, this line shouldn't be needed:
```
if ($format === 'json') {
    $exception->setHeaders(['Content-Type' => 'application/json']);
}
```

**Comment by yceruto** [comment]
What is the route definition of this path `'/send/template'`?

**Comment by gmponos** [comment]
Hello..

Here is the reproducer: https://github.com/gmponos/issue34893

If you run the test you can see that they fail. The project is new with zero configuration.

Although it is on sf5 as I said the problem I believe occurs in both versions v4.4.1 and 5

Hope it helps

**Comment by gmponos** [comment]
Btw I added an extra test and checked also if the response is JSON. 
https://github.com/gmponos/issue34893/blob/master/tests/Controller/ApiControllerTest.php#L18

In my case at least the body was json.. in the reproducer above the content of the response is not json either..

**Comment by yceruto** [comment]
@gmponos thanks for the reproducer, that will help a lot! 

Before I start debugging, are you sure it worked (as is) on 4.3 or previous versions?
```php
public function testApi()
{
    $client = static::createClient();
    $client->request('post', '/api');
    $this->assertSame(405, $client->getResponse()->getStatusCode());
    $this->assertSame('application/json', $client->getResponse()->headers->get('Content-type'));
    $this->assertJson($client->getResponse()->getContent());
}
```
Because AFAIK the "method not allowed exception (405)" is fired on Url matching process, it means that the request attributes: `_route`, `_controller`, `_format` and any other defined in your route `defaults={...}` won't be available in the request instance after this exception.

**Comment by yceruto** [comment]
Confirmed, I've tested it in 3.4 and 4.3 and that test case also fails.

@gmponos could you update the reproducer app with the test case that is OK in 4.3 and breaks in 4.4+?

**Comment by yceruto** [comment]
Btw, can pass the *accept* header on the request to make that test pass:
```php
$client->request('post', '/api', [], [], ['HTTP_ACCEPT' => 'application/json']);
```
only works as of 4.4

**Comment by gmponos** [comment]
First of @yceruto thank you for your help.

> Before I start debugging, are you sure it worked (as is) on 4.3 or previous versions?

Yes.. it seems you are right. This was not working on previous versions as well...

Symfony is not seem to throw a Json Exception if the method is not allowed when I format is `json` which is very disturbing :/

It seems that in order for us to deal with this issue one of our developers had added something like this in our project: https://github.com/gmponos/issue34893/blob/master/src/Listener/ApiListener.php

On the same project above I pushed a [4.3.9 branch](https://github.com/gmponos/issue34893/tree/4.3.9).

Because of this Listener the tests are passing now on 4.3.9.. but when I switch to 5.0.1 and I have the listener there as well the tests are failing.. 

I hope we are getting somewhere :)

**Comment by yceruto** [comment]
> Because of this Listener the tests are passing now on 4.3.9.. but when I switch to 5.0.1 and I have the listener there as well the tests are failing..

In this case, the request listener will run for the sub-request (i.e the error controller request), since the priority is less than 32 the RouterListener throws the `MethodNotAllowedException` first, so the master request wouldn't have the format value. The same happens in 4.3, unlike the content-type is set early, in the exception controller "using the sub-request".

Solution: changes the priority of the listener to 32+ to set the format to the master request and it will work as before.

Btw, there is no BC break here: the 4.4 BC layer will work the same as 4.3, hence I think it's a support issue rather than an bug.

**Comment by gmponos** [comment]
OK.. It took me a while to understand what you were saying.. In other words by our mistake we were setting the content type only on sub request and the previous Error Handling was also setting the error based on the sub request and not based on the request... 

Thank you so much for spending the time following this and explaining.

BTW Would it be hard for symfony to take into account the _format passed on the route and display an appropriate error depending on the format?

**Comment by yceruto** [comment]
> BTW Would it be hard for symfony to take into account the `_format` passed on the route and display an appropriate error depending on the format?

In fact, that's already the case, except for the `ResourceNotFoundException` (impossible to determine the attributes as it doesn't match any route) and `MethodNotAllowedException` errors.

**Comment by gmponos** [comment]
Thanks for following this and having the patience.
