### ISSUE TITLE
[ErrorHandler] Symfony\Component\ErrorHandler\ExceptionHandler not exists.

### ISSUE THREAD

**Issue by subcores** [symfony/symfony#34908]
**Symfony version(s) affected**: 4.4.1

**Description**  
The ExceptionHandler Class not exists in the ```symfony/error-handler``` package as discribed in [https://symfony.com/doc/4.4/components/error_handler.html#debugging-uncaught-php-exceptions](url)

**Comment by nicolas-grekas** [comment]
Good catch, please open a documentation issue.
