### ISSUE TITLE
[BC Break] Form POSTs w/o Accept return application/x-www-form-urlencoded response Content-Type

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#34906]
**Symfony version(s) affected**: 4.4.0

**Description**  
Hi! Due to #32344, if you POST a form submit but do *not* send any `Accept` headers, the response `Content-Type` will be the invalid `application/x-www-form-urlencoded`.

This doesn't happen in practice in a browser (which sends an `Accept` header), but DOES happen in functional tests - and is very difficult to debug.

The problem is that, in `$response->prepare()`, `$request->getPreferredFormat()` is called to try to figure out the correct `Content-Type`. If there is no `Accept` header, it eventually falls back to to using the request `Content-Type` as the default value:

https://github.com/symfony/symfony/blob/5e75edf57898e4464cd0f7a8d7c4e966d126cd97/src/Symfony/Component/HttpFoundation/Request.php#L1600

But in 4.3, it used "html".

**How to reproduce**  
Set up or find any deployed 4.4 form submit. Submit in your browser, then use the "Copy as Curl" tool in your browser network tools. Paste that into your terminal, but remove the `-H Accept` header.

That's it! Check out the `Content-Type` header on the response.

**Possible Solution**  
The last 2 lines of Request::getPreferredFormat() should maybe be:

```diff
- $this->preferredFormat = $this->getRequestFormat($preferredFormat ?: $this->getContentType());
+ $this->preferredFormat = $this->getRequestFormat($preferredFormat ?: $default);
```

Ping @yceruto :)

**Comment by gmponos** [comment]
Hi... is this possible dup of https://github.com/symfony/symfony/issues/34893

**Comment by thewalkingcoder** [comment]
Same result for older browser like <= IE 10; don't have 'text/html' on Accept so application/x-www-form-urlencoded is return and force to download page instead to render page #34857

**Comment by yceruto** [comment]
Fixed in https://github.com/symfony/symfony/pull/34921

**Comment by dasbrowedx** [comment]
Which branch is this fixed in? I still have the issue if I upgrade to 4.4.1

**Comment by weaverryan** [comment]
It should be in 4.4.2, which isn’t released yet at this moment
