### ISSUE TITLE
Having problems linking js file

### ISSUE THREAD

**Issue by MarkoM91** [symfony/symfony#34914]
I'm having problem linking my js file in symfony I run encore dev and run encore watch and webpack generates the js and the css file in the public/build folder but when I try to link it and run the javascript I  get nothing in return.

<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>

<meta charset="utf-8">

<link rel="stylesheet" href="public/build/style.css">

<title></title>

</head>

<body>

<div id="app"></div>

<div id="info">Wiggle your cursor</div>

<script src="public/build/index.js"></script>

</body>

</html>

what could be possibly be the problem?

 it does load css, the problem is only with js for some reason. It result linked but it doesn't execute the code. 

If I remove public from the url it doesn't link the file.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
