### ISSUE TITLE
Bearer token verification error 

### ISSUE THREAD

**Issue by emass293** [symfony/symfony#34919]
**Symfony version(s) affected**: 4.4.1

**Description**  

The verification of jwt token send an invalid token but the topken coms from OAuth : I think the "=" char is not valid

**Possible Solution**  

change line 114 of HttpClientTrait.php with :
       <code> if (isset($options['auth_bearer']) && (!\is_string($options['auth_bearer']) || !preg_match('{^[-._=~+/0-9a-zA-Z]++=*+$}', $options['auth_bearer']))) { </code>

**Comment by pbouska** [comment]
Bearer token returned from Twitter OAuth throws exception in HttpClientTrait too, when used in 'auth_bearer' option.

Workaround: sending bearer token from Twitter OAuth directly in header works fine:
`$response = $this->httpClient->request(
                'GET',
                $url,
                [
                    'headers' => ['authorization: Bearer '.$bearerToken]
                    //'auth_bearer' => $bearerToken,
                ]
            );`

**Comment by nicolas-grekas** [comment]
Can you please send a PR to update the regexp to `'{^[-._=~+/0-9a-zA-Z]++$}'`, on branch 4.3?

**Comment by emass293** [comment]
I am not sure to know how to do that
