### ISSUE TITLE
Default value for Intl ICU select.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#34926]
**Description**  
Actually, with the following translations
```
truc: >-
    {value, select,
        caseA    {Something}
        caseB    {Something}
        other  {Default}
    }
```

The following code
```
{{ 'truc'|trans('value': null) }}
```
Show `Default`

But the following code
```
{{ 'truc'|trans() }}
```
Show `{value}`

I was expecting having the same behaviour, both showing `Default`.

If it's not managed by `symfony`, do you know in which library should I report the behaviour/make a PR ?

**Comment by nicolas-grekas** [comment]
It looks like this is the expected behavior. Using plain PHP:
```php
$a = '{value, select, caseA    {Something} caseB    {Something} other  {Default} }';
echo MessageFormatter::formatMessage('en_US', $a, array());
```
display `{value}`

thank you for submitting.
