### ISSUE TITLE
ErrorHandler

### ISSUE THREAD

**Issue by mila76** [symfony/symfony#34938]
**Description**  
Using "old" Debug classes i cant pass error_reporting level so i can (for example) disable notify errors
With the new ErrorHandler classes it can't be done anymore....

**Example**  
Debug::enable(E_ALL & ~E_NOTICE);

**Comment by fancyweb** [comment]
This change was intentional, see https://github.com/symfony/symfony/pull/34312.

> Simplified the logic in Debug::enable() - nobody uses its arguments

**Comment by mila76** [comment]
I can agree is intentional and maybe not super useful for everyone... but its a Feature Request and an easy one.. 5 line of code.

I already make the copy/paste of the old argument setting

**Comment by nicolas-grekas** [comment]
I'm :-1: to do anything in the `Debug` class.
USe `error_reporting(E_ALL & ~E_NOTICE);` instead.

**Comment by lyrixx** [comment]
I agree with @nicolas-grekas and he gaves a simple solution.
Thanks for your feedback but I'm going to close this issue.

**Comment by mila76** [comment]
Sorry i never try to set the error_report after Debug(); I simply thinked dont work :(
Work like a charm... thanks a lot
