### ISSUE TITLE
[Mime] Email address with non-ascii characters not supported

### ISSUE THREAD

**Issue by ke20** [symfony/symfony#34932]
**Symfony version(s) affected**: 4.3.8

**Description**  
With the component Symfony/Mime, it seems not possible to use email address with non ascii characters.

For example, if try to send an email for the address `stöff@yopmail.com` or `ßert@yopmail.com` the error `Non-ASCII characters not supported in local-part os "<email>"` occurs.

**How to reproduce**  
The bug is simple to reproduce. Install with composer the component Symfony/Mailer in your project and copy/paste this code below : 

```php
<?php 

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Mime\Email;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;

$email = (new Email())
    ->from('hello@example.com')
    ->to('Stöff@yopmail.com')
    ->subject('Time for Symfony Mailer!')
    ->text('Sending emails is fun again!');

$transport = new EsmtpTransport('localhost');
$mailer = new Mailer($transport);
$mailer->send($email);
```

**Possible Solution**  
In the class `Symfony\Component\Mime\Encoder\IdnAddressEncoder` there are references to the class `Utf8AddressEncoder` and the class `SmtpUtf8Handler`.
But these classes does not exist into the project `Symfony/Mime` but exist into the project `Swiftmailer`.

I think we can use some elements of this pull request to fix this problem : https://github.com/swiftmailer/swiftmailer/pull/1056/files

**Additional context**  
None

**Comment by piotrantosik** [comment]
Any proposition of how to implement this?
Currently `Address` class is marked as final and encoder is a static property.:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Address.php#L72

**Comment by dmaicher** [comment]
I can confirm the issue. Proposing to fix it in https://github.com/symfony/symfony/pull/36178

**Comment by adrianrudnik** [comment]
Just encountered the first critical error in production today in a german env with umlauts in the local parts.

Is this not handled as a bug right now for 4.4 LTS?

We found a workaround but here are the painpoints:

- The email constraint in strict works with `egulias/email-validator` and passes the email into the system where `Address` passes it through the `IdnAddressEncoder` which fails hardly and with a non-validator-exception.
- We thought about extending `Address` but it's final.
- We through about just uninstalling the `static::$encoder` but the approach is as-default, so `null` actually uses the `IdnAddressEncoder` and it's not possible to just not use any encoder at all. So we must(!) use an encoder to `null` it basically, as you can see in the current version of `Swift_AddressEncoder_Utf8AddressEncoder` we just need the string back as-is.
- We can't fix the email address that is required in the `Address`instantion.

Luckily it's a private static. So here is the workaround:

```
<?php

declare(strict_types=1);

namespace App\EventSubscriber\Workaround;

use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Mime\Address;

/**
 * @todo: remove on upgrade to Symfony 5.2
 * @see: https://github.com/symfony/symfony/issues/36000
 * @see: https://github.com/symfony/symfony/pull/36178
 * @see: https://github.com/symfony/symfony/issues/34932
 * @see: https://github.com/symfony/symfony/commit/63f8827cf042adc966d0392598399309f4c16f4b
 */
class MimeAdressUtf8Subscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            RequestEvent::class => 'fixMimeAddressEncoder',
            ConsoleEvents::COMMAND => 'fixMimeAddressEncoder',
        ];
    }

    public function fixMimeAddressEncoder(): void
    {
        $r = new \ReflectionClass(Address::class);
        $p = $r->getProperty('encoder');
        $p->setAccessible(true);
        $p->setValue(new \Swift_AddressEncoder_Utf8AddressEncoder());
    }
}
```

Just unsure about the events to subscribe to as we miss something like `kernel boot`, I hope `on kernel request` and `on console command` are good enough here.

**Comment by dmaicher** [comment]
@adrianrudnik yes this was merged as a feature and not a bugfix :confused: 

One other way could also be to replace the `IdnAddressEncoder` class with your own class using composer autoloading?

See for example https://stackoverflow.com/a/58806137

I never tried that though :yum:

**Comment by fritzfr** [comment]
I just got this very error (`Invalid addresses: non-ASCII characters not supported in local-part of email.`) in production with Laravel 12 (symfony/mailer v7.4.3, symfony/mime v7.4.0).

I will open a new bug report https://github.com/symfony/symfony/issues/63215.
