### ISSUE TITLE
[HttpClient] the stream is not select()able

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#34944]
**Symfony version(s) affected**: 4.4+
**PHP version**: 7.3.9

**Description**  
The stream generated by the response is supposed to be stream_selec()able according to the documentation.

**How to reproduce**  

```php
$client = \Symfony\Component\HttpClient\HttpClient::create();
$response = $client->request('GET', 'https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.2.0-amd64-standard.iso');

$stream = $response->toStream();

$read = [$stream];
$write = [];
$except = [];

// the following returns false !
$success = @stream_select($read, $write, $except, null, 0);
var_dump($success);

// According to PHP documentation "this can happen if the system call is interrupted by an incoming signal"
// wut?
```

**Comment by nicolas-grekas** [comment]
Only NativeHttpClient is stream-selectable. That's because curl doesn't expose any low level file handle we could pass to stream select. That's something that is missing - a feature request for bugs.php.net...

**Comment by Nek-** [comment]
Oh. And an issue of the documentation then I guess.
