### ISSUE TITLE
Proposed TodoBackend Symfony 4 + ApiPlatform demo

### ISSUE THREAD

**Issue by olberger** [symfony/symfony#34946]
Following a suggestion by @nicolas-grekas here's a link to a proposed demo of Symfony 4 + ApiPlatform implementation of the TodoBackend REST API for a ToDo application, I deployed at https://still-ravine-70063.herokuapp.com/todos and whose code is at https://gitlab.com/olberger/todobackend-symfony4

See https://www.todobackend.com/ for the purpose of that site, which helps compare server-side REST frameworks.

Here's my PR to their site
https://github.com/TodoBackend/todo-backend-site/pull/193

I guess the Symfony code could be improved, as I'm not exactly an expert in REST matters with Symfony nor CORS for instance.

In any case, as the previous Symfony instance was Symfony 2 it may improve Symfony's profile a bit (but not sure the TodoBackend site is so much popular, anyway...).

I'm not exactly sure this issue is really helpful, but @nicolas-grekas suggested that I open one, so...

Hth,

**Comment by olberger** [comment]
Should be available soon, as the PR was merged.

**Comment by olberger** [comment]
It is now live, indexed from http://www.todobackend.com/ :-)

**Comment by ro0NL** [comment]
If the project is listed at http://www.todobackend.com and t solve this isuse, is there any actionable item left ... todo? (pun intended :D)

**Comment by olberger** [comment]
There hasn't ever been a ToDo actually ;-)... in case @nicolas-grekas has more ideas ?

**Comment by javiereguiluz** [comment]
This looks finished so far. @olberger thanks a lot for taking care of this. For those of you wanting to collaborate with this, you can find the code at https://gitlab.com/olberger/todobackend-symfony4. Thanks!
