### ISSUE TITLE
ErrorException: Warning: Zend OPcache API is restricted by "restrict_api" configuration directive

### ISSUE THREAD

**Issue by hracik** [symfony/symfony#34947]
**Symfony version(s) affected**: 4.4.1

**Description**  
When opcache.restrict_api is set then symfony/http-kernel/Kernel.php (line 555) throws an exception ErrorException Warning: Zend OPcache API is restricted by "restrict_api" configuration directive.

Probably can be fixed same way as this https://github.com/symfony/symfony/issues/25985.

**How to reproduce**  
```PHP
$kernel = new Kernel($env, $debug);
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
```

**Possible Solution**  
```PHP
if (\function_exists('opcache_invalidate') && filter_var(ini_get('opcache.enable'), FILTER_VALIDATE_BOOLEAN)) {
  @opcache_invalidate($this->getPath(), true);
}
```

**Comment by dschiffel** [comment]
This error also occurs in the version 5.0.1. Need to create a new issue?
```
Zend OPcache API is restricted by "restrict_api" configuration directive in vendor/symfony/http-kernel/Kernel.php on line 474
```
