### ISSUE TITLE
PTY mode: Input/output error

### ISSUE THREAD

**Issue by cheack** [symfony/symfony#34945]
**Symfony version(s) affected**: v4.4.1

**Description**  
When I set PTY mode for process, I get the following error:
```
fread(): read of 8192 bytes failed with errno=5 Input/output error
```

OS: official `ubuntu:18.04` [docker image](https://hub.docker.com/_/ubuntu/).
PHP: 7.4.0 from `ondrej/php` [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php):
```
PHP 7.4.0 (cli) (built: Nov 28 2019 07:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
```

**How to reproduce**  
Here is a minimal example:
```php
$process = new Process(['echo', '123']);
$process->setPty(true);
$process->run();
```

**Comment by mbardelmeijer** [comment]
Able to reproduce this as well on PHP 7.4. Execution of the process is still successful, but the notice is outputted. 

Perhaps these need to be suppressed from 7.4?

https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.fread-fwrite

> fread() and fwrite() will now return FALSE if the operation failed. Previously an empty string or 0 was returned. EAGAIN/EWOULDBLOCK are not considered failures.
> These functions now also raise a notice on failure, such as when trying to write to a read-only file resource.

**Comment by Alig96** [comment]
Also encountering this issue on 7.4

**Comment by ged15** [comment]
Just upgraded to PHP 7.4 and started encountering when `\Symfony\Component\Console\Application::renderThrowable` is invoked. `symfony/console` version `4.4.4`.
