### ISSUE TITLE
[HttpClient] Support for non-blocking io in streams

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#34943]
**Description**  

If I do the following code, I will get an error because Symfony StreamWrapper does not support `stream_set_option`.

```php
$client = \Symfony\Component\HttpClient\HttpClient::create();
$response = $client->request('GET', 'https://example.com');

$stream = $response->toStream();
\stream_set_blocking($stream, 0); // Trigger error / Returns false
```

**Comment by nicolas-grekas** [comment]
Here is the warning (please add it next time):
`PHP Warning:  stream_set_blocking(): Symfony\Component\HttpClient\Response\StreamWrapper::stream_set_option is not implemented!`

So, let's implement it :)
That's possible only for NativeHttpClient, which is the one that will populate the StreamWrapper::$handle property.

PR welcome.

**Comment by Nek-** [comment]
https://github.com/symfony/symfony/pull/35209 fixed it!
