### ISSUE TITLE
SF 4 - Bug of unserialization PHP function in AbstractToken.php-> Notice: unserialize(): Error at offset 8089 of 14081 bytes 

### ISSUE THREAD

**Issue by bastien70** [symfony/symfony#34948]
**Symfony version(s) affected**: 4.3.9

**Description**  

I have deserialization bugs of the token, which causes me this error:

> Notice: unserialize(): Error at offset 11282 of 17034 bytes

![error](https://user-images.githubusercontent.com/53140475/70707349-396a4180-1cd8-11ea-95b9-beac6e48a171.PNG)

I noticed that I was not the only one with this problem:

 => https://github.com/symfony/symfony/issues/29459

To work around the problem I just implemented Serializable in my User entity by selecting only certain attributes. But it's not a good solution to do that, I really want to fix the real problem without pushing it away.

In another topic with the same kind of problem, a solution has been made: https://github.com/symfony/symfony/issues/29951#issuecomment-457626478

But that means I'm going to have to edit a very important file, and that's not a good solution I think. Does someone have an idea ? Should I go back to PHP 7.2?

**How to reproduce**  

Unfortunately I do not have any code to copy because I'm working on a big project and I can not share code. I do not know how to reproduce that, but I'm not the only one who has this problem.

**Possible Solution**  

I tried to go back to PHP 7.2.
In another issue, someone said he had the same problem in 7.2. For me, that solved the problem. At least, that's what I thought. Oddly enough, I no longer had the error when I went to the pages that caused it to me yesterday. But today, strangely, the same mistakes have come back.

Another technique that can work: Implement Serializable in the User entity. But unfortunately, that only pushes back the error because when I want to deepen the serialization rules on this entity, the error returns. For example if I want to use JMS Serializer, I won't be able to.

A solution has been proposed but it forces us to modify part of the code ourselves, and I don't know if it's a good thing to do that. What will happen if I update later? https://github.com/symfony/symfony/issues/29951#issuecomment-457626478

**Additional context**  

I have many links related this problem : 

https://stackoverflow.com/questions/59290185/symfony-4-php-7-3-error-in-authentication-token-abstracttoken-php?noredirect=1#comment104790059_59290185 ==> My stackOverflow topic

And this link : https://github.com/symfony/symfony/issues/29459

**Comment by nicolas-grekas** [comment]
The previous reports on the topic are quite old, and many things changed meanwhile on the topic.
I'm not sure anyone is experiencing the issue anymore. We would have more reports if that werethe case I think.
Implementing `Serializable` is strongly discouraged as [it brings design issues](https://wiki.php.net/rfc/custom_object_serialization) with it.

Are you using the database where token are stored from several apps? Are they all using the same version of Symfony? If not, that might be the issue.

We'd need a reproducer and more ppl reporting the issue to confirm there is one to me.

**Comment by bastien70** [comment]
Sorry for the wait, I hadn't seen that there was an answer. I use a database, not tokens.
And for me, the implementation of `Serializable `solved the problem despite everything, I see no other solution unfortunately

**Comment by xabbuh** [comment]
Let's close here then. We won't be able to work on a fix anyway if we are not able to reproduce.
