### ISSUE TITLE
[Profiler] Labeled profiles

### ISSUE THREAD

**Issue by henry2778** [symfony/symfony#34941]
**Description**  
Hi! Back in the day I was refactoring my app and I had to open a bunch of profiles in new tabs, then comparing the performance (after I tweaked my code). So if you have like 3 or more cases you want to compare - its getting harder to remember what tab is for what case, basically. So the idea is to give a profile some human readable label. 

I guess we can use just browser persistence like local storage (assign 'token' => 'label' -  just JS code), or we can go further and change the Profile class. Personally for me - the browser level approach is enough :)

What do you think?

If that makes sense, I would like to work on that :)

**Example**  
![image](https://user-images.githubusercontent.com/13105599/70653241-c40d5b00-1c5c-11ea-9cdf-da367645b305.png)

**Comment by ro0NL** [comment]
wouldnt including the token in  `<title>` be suffcient?

Or what's the proposal implementation behind

> So the idea is to give a profile some human readable label.

**Comment by henry2778** [comment]
@ro0NL well, the token in title does not give a developer pretty much anything, if he is switching between the tabs and trying to figure out what he is debugging/profiling :) 

I think by default the profile opens as it opens now, but we can add new button, which will open a modal window to input a label for the profile. After that just save that to browser storage and use it in <title> and/or profile metadata. That's pure JS.

**Comment by ro0NL** [comment]
i still think any reference (token, date/time) generally will do to classify some profiler window.

I agree we need something in the `<title>` for this type of debugging purpose.

A button/modal overlay is too much IMHO, if anything here's a quick mock:

![image](https://user-images.githubusercontent.com/1047696/70790659-d63ee480-1d95-11ea-8a9b-cca7cc5a33b4.png)

then it will auto-update the title etc.

**Comment by henry2778** [comment]
@ro0NL agree

**Comment by jkufner** [comment]
What about using current branch name?

It will be automatic and useful by default. Also, we do not have to use Git binary, we can just check `.git` directory (note: the `.git` may be a file with path to the real .git directory) for the `HEAD` file and get the branch (ref) name from there. Such an approach should be viable for other mainstream VCS too.
