### ISSUE TITLE
Remember me token vs LDAP auth

### ISSUE THREAD

**Issue by wrbmmpl** [symfony/symfony#34953]
**Symfony version(s) affected**: 5

**Description**  
the token generated deletes the password, but it is required in Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices::generateCookieValue()

**How to reproduce**  
Activate the remember me option in security.yaml, during an LDAP Auth

**Comment by LinkingYou** [comment]
We can confirm the exact same problem.

**Comment by chalasr** [comment]
Fixed by https://github.com/symfony/symfony/pull/35335
