### ISSUE TITLE
HttpClient upload file not processable

### ISSUE THREAD

**Issue by freiondrej** [symfony/symfony#34951]
**Symfony version(s) affected**: 5.0.1

**Description**  
When following the documentation of HttpClient (https://symfony.com/doc/current/components/http_client.html#uploading-data), the section starting with "To submit a form with file uploads..." shows an example of how to upload a file as `multipart/form-data`. The code works for me when using NativeHttpClient, but when using CurlHttpClient, it fails - the uploaded file is not recognized by the server.

**How to reproduce**  

**Possible Solution**  
I've narrowed the problem down to the missing `Content-Length` header, but I don't know the problematics enough to send a PR.

**Additional context**

**Comment by nicolas-grekas** [comment]
Can you provide a simple script to reproduce the issue?

**Comment by freiondrej** [comment]
@nicolas-grekas Thanks for short response time, Symfony support rocks!

Not working for me: (profiler shows Content-Length to be empty string)

```php
$client = new CurlHttpClient(['base_uri' => 'http://localhost:8000']);

$formFields = [
	'file' => DataPart::fromPath(__DIR__."/testAssets/img.png"),
];

$formData = new FormDataPart($formFields);

$response = $client->request('POST', '/api/images', [
	'headers' => $formData->getPreparedHeaders()->toArray(),
	'body' => $formData->bodyToIterable(),
]);
```

Working for me: (profiler shows Content-Length to be "1438704")

```php
$client = new NativeHttpClient(['base_uri' => 'http://localhost:8000']);

$formFields = [
	'file' => DataPart::fromPath(__DIR__."/testAssets/img.png"),
];

$formData = new FormDataPart($formFields);

$response = $client->request('POST', '/api/images', [
	'headers' => $formData->getPreparedHeaders()->toArray(),
	'body' => $formData->bodyToIterable(),
]);
```

By the way, I observed probably unrelated behavior - when trying to access `$response->getInfo('debug')` of the CurlHttpClient, I got 
` Uncaught TypeError: Argument 1 passed to Symfony\Component\Mime\Encoder\EightBitContentEncoder::encodeString() must be of the type string, resource given, called in /vendor/symfony/mime/Part/TextPart.php on line 120 and defined in /vendor/symfony/mime/Encoder/EightBitContentEncoder.php:31` while accessing debug info of NativeHttpClient was just fine.

**Comment by nicolas-grekas** [comment]
I tried to reproduce the "Uncaught TypeError" but didn't manage to, can you please provide a reproducer?
About the Content-Length, that's expected behavior: CurlHttpClient uploads the file using a stream, which uses either chunked-encoding on HTTP/1.1 or a similar mechanism in HTTP/2.
Because `NativeHttpClient` cannot stream the upload, it has to turn the body into a string before doing the request, thus it can compute the content-Length.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by freiondrej** [comment]
@nicolas-grekas sorry for delayed response, I was out of office during Christmas.

I cannot reproduce the "Uncaught TypeError" any more, so please ignore it.

Thank you for explaining how the Content-Length header works. Would it be possible to make Content-Length available in `\Symfony\Component\Mime\Part\Multipart\FormDataPart::getPreparedHeaders()`? I wanted to compute it myself but did not find an easy way to retrieve boundary length to calculate the total body length.

**Comment by nicolas-grekas** [comment]
Please open an issue if you want this to be discussed.
Maybe you can send a PR that could enable your use case?

**Comment by ThomasLandauer** [comment]
I'm having the same issue, I'm getting:

> HTTP/1.1 411 Length Required returned

I think this should be explained at https://symfony.com/doc/4.4/http_client.html#uploading-data - or is this so uncommon?

So what's the status? Since `Content-Length` is not available when using cURL, the only workaround so far is to use `NativeHttpClient`?

**Comment by nicolas-grekas** [comment]
Turning the body into a string prior to sending it should do the job.

**Comment by ThomasLandauer** [comment]
Yeah, great, changing
```php
'body' => $formData->bodyToIterable(),
```
to
```php
'body' => $formData->bodyToString(),
```
fixed it! :-)

I'd like to commit this to the docs. Should I just mention `bodyToString()` for this specific use case (i.e. error 411)?

**Comment by nicolas-grekas** [comment]
Sure! "If the server is not compatible with streaming the uploaded body (eg error 411), then etc", something like that.
