### ISSUE TITLE
4.4.0 trigger_error E_USER_WARNING or E_USER_NOTICE result in ErrorException

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony#34968]
Symfony version(s) affected: 4.4.0 and more

Description
In any Controller of my project if I use trigger_error("message", E_USER_WARNING) or trigger_error("message", E_USER_NOTICE), I have a ErrorException which should not throw an exception because it's only a warning or a notice !

How to reproduce
Just put a trigger_error("message", E_USER_WARNING) or trigger_error("message", E_USER_NOTICE), in a method.

Possible Solution
Only do an error_log if the level is not error or more ?
Or not throwing an exception and let the same behavior than a E_USER_DEPRECATED ?

Additional context
PHP version : 7.1.3

**Comment by QuentinCurtet** [comment]
@javiereguiluz Any solution on this ?

**Comment by derrabus** [comment]
You should aim at creating a notice-free application. If a piece of code triggers a warning, the solution would be to eliminate the source of the warning.

On production, the error handler by default is more forgiving, so that the execution of the application won't be stopped on warnings and notices there.

**Comment by QuentinCurtet** [comment]
We are on a migration project, we need these notices during the migration.
Furthermore, a warning or a notice shouldn't throw an exception !

**Comment by derrabus** [comment]
Feel free to reconfigure the error handler in that case. Throwing exceptions for notices in non-production environments is a reasonable default.

**Comment by QuentinCurtet** [comment]
@derrabus We didn't see anything to reconfigure the Symfony Error Handler in the doc, do you have any link ?

**Comment by lerminou** [comment]
your kernel may be in "strict mode", and it's activated by default if you're in DEV mode with the debug flag set to true

**Comment by QuentinCurtet** [comment]
@lerminou Thanks for the answer, how can i change it for dev environnement ?

**Comment by QuentinCurtet** [comment]
@fabpot @nicolas-grekas @dunglas Any idea on this ?

**Comment by lerminou** [comment]
just read the docs about it, you can find many resources on it.
https://symfony.com/doc/4.1/configuration/environments.html#executing-an-application-in-different-environments
you can set the $_SERVER['APP_DEBUG']

**Comment by QuentinCurtet** [comment]
@lerminou My question was not "how do to define env", but how can i define the not_strict mode ?
Because there is no configuration for error handler.

And it's not normal to throw exception after a notice or a warning.

**Comment by nicolas-grekas** [comment]
Here is the page in the doc:
https://symfony.com/doc/current/reference/configuration/framework.html#throw

I'm closing as there is no bug to keep track of here, please use support channels as listed on https://symfony.com/support if you need further help.

**Comment by QuentinCurtet** [comment]
Now it's fixed but not thanks to the doc (upgrade guide not up to date)
Just replace the use `Symfony\Component\Debug\Debug;` to use `Symfony\Component\ErrorHandler\Debug;`

**Comment by nicolas-grekas** [comment]
How could we guess, this has nothing to do with any of the hints above???
@QuentinCurtet could you please send a PR to improve the update files, branch 4.4?

**Comment by QuentinCurtet** [comment]
Normally it's the default bootstrap of a new Symfony project, i didn't know i had to precise it.

I am making the PR related to this issue
