### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by billsinc** [symfony/symfony#34960]
**Symfony version(s) affected**: 4.3.9

**Description**  
Running Symfony commands in the terminal is resulting in panics. I upgraded my Symfony version today upon being prompted after running `symfony server:start`.

**How to reproduce**  
Running any symfony command in the terminal is creating the problem.
`symfony console`

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x463bf21]
> 
> goroutine 1 [running]:
> github.com/hashicorp/go-version.(*Version).String(0x0, 0x0, 0x0)
> 	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/version.go:359 +0x51
> github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc00020ceb0, 0xc0001d0040)
> 	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/version.go:118 +0x2f
> github.com/hashicorp/go-version.(*Version).LessThan(...)
> 	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/version.go:298
> github.com/symfonycorp/go-php.versions.Less(...)
> 	/go/pkg/mod/github.com/symfonycorp/go-php@v0.0.0-20191128115051-441c255ee06a/version.go:34
> sort.insertionSort(0x4d4abe0, 0xc0001d0020, 0x0, 0x7)
> 	/usr/local/go/src/sort/sort.go:27 +0xc4
> sort.quickSort(0x4d4abe0, 0xc0001d0020, 0x0, 0x7, 0x6)
> 	/usr/local/go/src/sort/sort.go:209 +0x201
> sort.Sort(0x4d4abe0, 0xc0001d0020)
> 	/usr/local/go/src/sort/sort.go:218 +0x79
> github.com/symfonycorp/go-php.(*PHPStore).loadVersions(0xc0003dcc80)
> 	/go/pkg/mod/github.com/symfonycorp/go-php@v0.0.0-20191128115051-441c255ee06a/store.go:126 +0x123
> github.com/symfonycorp/go-php.NewStore(0xc0003b9000, 0x18, 0x0, 0x0, 0x18)
> 	/go/pkg/mod/github.com/symfonycorp/go-php@v0.0.0-20191128115051-441c255ee06a/store.go:37 +0x8e
> github.com/symfonycorp/symfony-cli/local/php.(*Executor).Config(0xc000625e38, 0xc0001bbaaf, 0xc0001bbb60)
> 	/go/src/github.com/symfonycorp/symfony-cli/local/php/executor.go:62 +0xa2
> github.com/symfonycorp/symfony-cli/local/php.(*Executor).Execute(0xc000625e38, 0x0)
> 	/go/src/github.com/symfonycorp/symfony-cli/local/php/executor.go:190 +0x4f
> main.main()
> 	/go/src/github.com/symfonycorp/symfony-cli/cmd/symfony/main.go:47 +0x2d5
> 

**Possible Solution**  

**Additional context**  
I've tried updating other packages, restarting, etc. I'm not sure if I've done anything else recently that would cause this.

**Comment by javiereguiluz** [comment]
@billsinc thanks for reporting this. I'm moving this issue to the repository of the Symfony CLI, because it looks related to that instead of to the Symfony framework.

**Comment by stof** [comment]
@javiereguiluz you could have transferred the issue, as github now support that.

**Comment by javiereguiluz** [comment]
@stof yes, I wanted to but I don't have permissions in the target repo 😢
