### ISSUE TITLE
[RFC] New form type: DateTimeWithTimezoneType

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#34971]
A couple of weeks ago I wrote a blog post about [dates and timezones with Forms](https://www.orbitale.io/2019/10/28/proper-dates-with-easyadmin.html) with an example using EasyAdmin, after discovering the [`model_timezone`](https://symfony.com/doc/current/reference/forms/types/datetime.html#model-timezone) and the [`view_timezone`](https://symfony.com/doc/current/reference/forms/types/datetime.html#view-timezone) options and testing them, and I started to think that it would be very convenient to be able to specify these directly in the frontend.

The most straightforward solution would be to create a form type that would be a compound form, made with one mandatory `DateTimeType`-based form and two optional `TimezoneType`-based forms: one for the view timezone, one for the model timezone.

Something like this seems to be the only current possible solution in the userland:

```php
class DateTimeWithTimezoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('datetime', DateTimeType::class)
            ->add('model_timezone', TimezoneType::class)
            ->add('view_timezone', TimezoneType::class)
        ;

        // ... Handle timezone conversion manually in a Form Event
    }
}
```

This would solve some common use cases with timezones, such as things like _"We store everything in UTC"_, which means **people** using the app (and not the app itself) must remember to enter the right date, with the timezone and hours differences in mind. And with daylight saving time, this becomes a PITA because we have to change our mind twice a year.

By using such form type, the specs could still be _"We store everything in UTC"_ but on the view/frontend-side, the user would be able to **specify the timezone** of the date they want to use, and it will in the end be stored as UTC, without any additional field in the storage.

To me, this could really improve both UX (because we enter the timezone on the frontend so users don't have to remember about DST and hours differences) and also DX because we can have a simpler workflow with the _"Store everything as UTC"_ strategy (which is IMO a good practice).

I didn't start any implementation because I'm not sure about what we already have in the userland for this, but a native Symfony integration for this seems a good idea to me.

I'm also not really sure about whether it should be a new form type or a new feature of the existing `DateTimeType` (which is already a big form type having tons of features).

But I'll gladly work on this if it's considered a good idea by the community 🙂

**Comment by jkufner** [comment]
I don't like the model and view time zone separation. I think it is unnecessary complication. … And probably wrong.

The timezone must be stored together with the time, but your example sets the model timezone in the form definition instead of the data. The DateTime class (both mutable and immutable versions) include timezone. So, use it. There is no need to configure anything.

If times are stored using UTC timezone, then the database layer should return DateTimeImmutable with UTC timezone set. Then it makes sense to configure the view time zone to show local time correctly.

> // ... Handle timezone conversion manually in a Form Event

If you do this, then the whole component is useless.

**Comment by cjunge** [comment]
As a FYI: Storing datetime as UTC with offset for a date in the future can be problematic, as the rules around DST/offsets can change. A good example is the recent changes removing EU daylight savings.

A better solution is to refer to the "Database Name" (ie. `Europe/Paris`) at time of saving/viewing and allow the conversion to happen at request time.

Also, most DBs aren't really timezone-aware, they may convert a given datetime with a timezone into UTC/server time, depending on the server/settings.

https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/

**Comment by Pierstoval** [comment]
Most DateTime instances people use in their apps will be created through `new DateTime()` therefore use the preconfigured timezone, and when storing them in the database, most of the time the value is stored using `$datetime->format('Y-m-d H:i:s');`, with no timezone.

As you say @cjunge, most dbs are not yet timezone-aware (well, Postgresql seems to be the only one among the popular DBMSs), so the timezone must be handled on the application side.

Having such timezone configuration directly in our forms would allow us to make sure we don't even need to update the server's timezone configuration: we can create the DateTime objects directly based on the provided timezones and convert from a format to another if it's specified in the form configuration.

I'm okay to make the implementation directly in the native form type instead of creating a new one :)

**Comment by jkufner** [comment]
The best way to store past and near-future times anywhere is using unix timestamp (where the timezone is irrelevant). The only problem with this approach is when timezone definitions change — but that always happens in reasonably distant future.

**Comment by xabbuh** [comment]
I wonder if it's really a common use case to ask the end user not only to add date and time, but also to select the timezone for it. I don't remember ever to have been asked by a customer to add these inputs. So I am not sure if that really is a common enough use case.

**Comment by jkufner** [comment]
@xabbuh Not very common, but when necessary, it is really difficult to get it right.

**Comment by Pierstoval** [comment]
@xabbuh I don't think it's common at all, it's just that I've personally encountered this on applications that have date-sensitive business logic that implies timezones. I added many workarounds in the app to avoid potential issues, but something native like this seems a better solution, and I wasn't sure about the implementation (as said in my original post, my first idea was to use a form containing the 3 fields: date, model timezone and view timezone, but having it in the native DateTimeType is fine too, maybe a bit more cumbersome but still relevant).

Considering the amount of positive reactions on the post, I might work on this soon then :)
