### ISSUE TITLE
"Double free or corruption" error in PHP 7.4 when trying to enable preloading

### ISSUE THREAD

**Issue by mikemix** [symfony/symfony#34983]
**Symfony version(s) affected**: 4.4.1

**Description**  
I'm trying to enable the PHP 7.4 preload feature in my app, in a `nginx:1-alpine` + `php:7.4-fpm` docker stack, but it's not working, I'm consistently getting the error below:

```
$ docker-compose logs php
php_1  | double free or corruption (!prev)
php_1  | [15-Dec-2019 09:25:45] WARNING: [pool www] child 7 exited on signal 6 (SIGABRT - core dumped) after 11.953494 seconds from start
php_1  | [15-Dec-2019 09:25:45] NOTICE: [pool www] child 9 started
```

using settings below:

```
$ docker-compose exec php cat /usr/local/etc/php/conf.d/opcache.ini
opcache.enable = 1
opcache.preload = /var/www/html/var/cache/prod/App_KernelProdContainer.preload.php
opcache.preload_user = www-data
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 16
opcache.validate_timestamps = 0
opcache.revalidate_freq = 0
```

When I disable the `preload` the app works perfectly fine.

**Comment by nicolas-grekas** [comment]
That's a PHP issue, not a Symfony one.
Please try with PHP 7.4.1 before submitting an issue on bugs.php.net, it contains fixes related to preloading.

**Comment by mikemix** [comment]
Thanks Nicolas!
