### ISSUE TITLE
[Session] bad merge in `PdoSessionHandler`?

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#34995]
**Symfony version(s) affected**: master

**Description**  
I was just reading the code of the `PdoSessionHandler`, when I encountered something that looks like a bad merge:

https://github.com/symfony/symfony/blob/c8f3053be80bf7d7da66de1503d8643114fab4e4/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L871-L875

Just wanted somebody to confirm that. As `bindValue` just overwrites the previously set value, it seems that all sessions in SQLServer are immediately invalidated, as the last value bound to the expiry fields is just `time()`.

**How to reproduce**  
I don't run SQLServer, so I have no easy way to confirm this. Just wanted to confirm that I am not misreading the code.
I can try to then add a failing test case.

**Possible Solution**  
Remove duplicate lines and only leave the ones with `+ $maxlifetime`.

**Additional context**  
—

**Comment by nicolas-grekas** [comment]
A git blame leads to https://github.com/symfony/symfony/pull/33169, which means no bad merge, but that's what the PR author actually wrote.
/cc @azjezz can you please tell us why you did it this way?

**Comment by azjezz** [comment]
looking into the PR now, i believe this was a mistake on my side, which should have been : 

```php
			$mergeStmt->bindParam(1, $sessionId, \PDO::PARAM_STR);
            $mergeStmt->bindParam(2, $sessionId, \PDO::PARAM_STR);
            $mergeStmt->bindParam(3, $data, \PDO::PARAM_LOB);
            $mergeStmt->bindValue(4, time() + $maxlifetime, \PDO::PARAM_INT);
 			$mergeStmt->bindValue(5, time(), \PDO::PARAM_INT);
            $mergeStmt->bindParam(6, $data, \PDO::PARAM_LOB);
            $mergeStmt->bindValue(7, time() + $maxlifetime, \PDO::PARAM_INT); 
            $mergeStmt->bindValue(8, time(), \PDO::PARAM_INT); 
```

**Comment by apfelbox** [comment]
@nicolas-grekas the intention is clear, but the duplicate calls have no effect, if I see that correctly (as all previous values are overwritten. The call in PHP probably doesn’t validate the values, but only the database when actually executing).

@azjezz thanks for clearing it up!

**Comment by gsirin** [comment]
I am using sqlsrv and pdo sessions on a symfony project I just updated from 4.3.9 to 4.4.1.

When accessing my sessions I am getting the exception
SQLSTATE[07002]: [Microsoft][ODBC Driver 13 for SQL Server]COUNT field incorrect or syntax error

Replacing lines 870-877 with the mentioned code above works for me and solves the problem

            $mergeStmt->bindParam(1, $sessionId, \PDO::PARAM_STR);
            $mergeStmt->bindParam(2, $sessionId, \PDO::PARAM_STR);
            $mergeStmt->bindParam(3, $data, \PDO::PARAM_LOB);
            $mergeStmt->bindValue(4, time() + $maxlifetime, \PDO::PARAM_INT);
            $mergeStmt->bindValue(5, time(), \PDO::PARAM_INT);
            $mergeStmt->bindParam(6, $data, \PDO::PARAM_LOB);
            $mergeStmt->bindValue(7, time() + $maxlifetime, \PDO::PARAM_INT); 
            $mergeStmt->bindValue(8, time(), \PDO::PARAM_INT);

**Comment by nicolas-grekas** [comment]
Thanks for the confirmation @gsirin!
