### ISSUE TITLE
Service Container can't be set as public

### ISSUE THREAD

**Issue by diogotozzi** [symfony/symfony#34999]
**Symfony version(s) affected**: 5.0.1
**PHP Version**: 7.4.0

**Description**  
According to the Service Container documentation about [public vs private](https://symfony.com/doc/current/service_container.html#public-versus-private-services) services, I cannot reproduce a public accessible service via `$container->get()`.

Even if I follow the [How to Create Service Aliases and Mark Services as Private](https://symfony.com/doc/current/service_container/alias_private.html), with an alias, the service still behaves as _private_.

**How to reproduce**  

The services configuration file:
```yaml
# config/services.yaml
services:
    # ...
    App\Service\MessageGenerator:
        public: true
```

The controller file:
```php
use App\Service\MessageGenerator;

// ...

public funciton new()
{
    $message = $this->container->get(MessageGenerator::class);
}
```

The error:

![Screen Shot 2019-12-16 at 4 01 51 PM](https://user-images.githubusercontent.com/529593/70935510-0baa3300-201f-11ea-8943-7b2d0cebdd5f.png)

**Comment by ro0NL** [comment]
i figure you're accessing the service locator from AbstractController ..., which is a smaller subset of the full container :) AFAIK you should inject the full container `@service_container / ContainerInterface $container` as needed. Do the docs tell otherwise?

**Comment by diogotozzi** [comment]
@ro0NL Yes, I understand the error message and the situation. But I'm following the docs for public services, not injection, and it's not working as it says so.

Or we have a problem at the documentation, or a bug at the framework.

**Comment by ro0NL** [comment]
the DI/service container docs dont assume AbstractController, so this is confusing .. but technically correct :)

for controllers (https://symfony.com/doc/current/controller.html) we dont mention accessing the service locator even.. so it seems 2 concepts are combined, but im not sure how to handle it in the docs ;)

**Comment by diogotozzi** [comment]
@ro0NL I couldn't find this _full container_ injection at the docs. Just following the documentations I cited, I'm unable to reproduce a public service.

I think we need an upgrade at the docs, or this is a bug. 😕

**Comment by stof** [comment]
This is a documentation issue IMO. The issue in your case is that `$this->container` in an AbstractController is *not* the DIC Container (and that's on purpose). So `$container` in the doc you are reading is not the same than `$this->container` in the code you write.

In older Symfony versions, controllers were based on the (now removed) Controller abstract class, which contained a reference to the full DI Container object. So the confusion was not present. In modern Symfony versions, accessing the DI container instance is much less common.

**Comment by diogotozzi** [comment]
@stof @ro0NL Thanks for the explanations guys! Now I know the differences about DI in Symfony 4 and Symfony 5.

The documentation is really out of date for version 5.* and beyond.

**Comment by stof** [comment]
Well, the documentation of the DI components talks about a `$container` variable. AFAIK, it never tells you that this is the same that `$this->container` in your controller.

**Comment by ro0NL** [comment]
IMHO we should remove the "controller" example in https://symfony.com/doc/current/service_container.html#public-versus-private-services, in favor of a global runtime.

The example uses `$this->container` (controller like), but the next line mentions `$container->get()` (global runtime)

**Comment by nicolas-grekas** [comment]
Please open a doc issue. CLosing as there is nothing to keep track of on the code side. Thanks for submitting.

**Comment by ro0NL** [comment]
@nicolas-grekas perhaps transfer the issue to the doc repo instead :)
