### ISSUE TITLE
[EventDispatcher] Wrong priorities displayed in profiler if a listener is registered multiple times

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#34997]
**Symfony version(s) affected**: 3.4.36, 4.4.1, 5.0.1

**Description**  
If the same listener is registered multiple times with different priorities, the web profiler displays all calls, but for each call, the highest priority is of all calls to that very listener is displayed.

**How to reproduce**  
Wire this subscriber into your Symfony application.

```php
namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\KernelEvents;

final class MultiSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => [
                ['doSomething', 42],
                ['doSomething', 21],
                ['doSomething', 0],
                ['doSomething', -21],
                ['doSomething', -42],
            ]
        ];
    }

    public function doSomething(): void
    {
    }
}
```

**Possible Solution**  
Display the correct priorities. 😉 

**Additional context**  
<img width="1066" alt="Bildschirmfoto 2019-12-16 um 18 22 11" src="https://user-images.githubusercontent.com/1506493/70928395-41581780-2031-11ea-98a0-6aabe64b5778.png">

**Comment by dmaicher** [comment]
Related: https://github.com/symfony/symfony/issues/34149

**Comment by derrabus** [comment]
@dmaicher Thanks! The linked ticket describes exactly the same issue. Why didn‘t I find it? 🙈 

Anyway, let‘s close this issue as duplicate then.
