### ISSUE TITLE
Fresh encoded password is immediatelly not valid

### ISSUE THREAD

**Issue by leik-software** [symfony/symfony#35002]
**Symfony version(s) affected**: v4.4.1 (symfony/security-bundle)

**Description**  
I have an console import job, which creates new user objects with an insert query like this:
```php
protected function createNewUser(array $partnerRow): void
{
    $userInsertSql =
        'INSERT INTO user (enabled, password, ...)
        VALUES (:enabled, :password, ...)';

    $stmt = $this->connection->prepare(
        $userInsertSql
    );
    $stmt->bindValue(':enabled', ('J' === $partnerRow['ACTIVE'] ? 1 : 0), \PDO::PARAM_INT);
    $stmt->bindValue(':password', $this->getHashedPassword($partnerRow['CLEARPASSWORD'] ?? '', new User()), \PDO::PARAM_STR);
    $stmt->execute();

}

protected function getHashedPassword(string $plainPassword, User $user): string
{
    return $this->passwordEncoder->encodePassword($user, $plainPassword);
}
```

Then I have a custom LoginFormAuthenticator which does this:
```php
if (!$this->passwordEncoder->isPasswordValid($user, $credentials['password'])) {
    throw new CustomUserMessageAuthenticationException(
        $this->translator->trans('login wrong password')
    );
}
```

The passwordEncoder is Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface, which leads to MigratingPasswordEncoder which has NativePasswordEncoder as $bestEncoder - I dumped this while creating and in login process.

The created password is 
```
$argon2id$v=19$m=10240,t=3,p=1$ai9tZ2JMbkpuazBNOGNnNg$UVqcmhAA/vqPJ88RfpKjJ3zYfaro/6YOGcLAUf7G/38
```
But the login only works if I change it to 
```
$2y$13$gEXunMWrg5Rg14UkdzX23uvY6uPE8Whd5.EgmCbSnR/c2qSBjeTa2
```
security.yaml:
```yaml
encoders:
      App\Entity\User:
        algorithm: auto
        cost: 4
        memory_cost: 10240
        time_cost: 3
```

We had an update from v4.3.2, this code worked for the last 2 years and now I don't know how to deal with it. I checked some related issues but found nothing what would match to my problem.

https://github.com/symfony/symfony/issues/31758
https://github.com/symfony/symfony/issues/32166
https://github.com/symfony/symfony/issues/34113

**Comment by chalasr** [comment]
@leik-software Can you paste a clear password along with its (invalid) hash?

**Comment by leik-software** [comment]
@chalasr you guided me to the solution. I found out that my user comes with null password value from source data. I am very sorry, I should have checked that. With not null passwords everything works.
