### ISSUE TITLE
NotificationEmail does not work with markdown() option

### ISSUE THREAD

**Issue by lfjeff** [symfony/symfony#35018]
**Symfony version(s) affected**: 4.4

**Description**  
I have tried to use the `markdown()` method in the new `NotificationEmail` class and and it throws a `LogicException` error when you try to send the email that was created.

If I use the `html()` method, it works fine.

**How to reproduce**
I followed the example given here:
https://symfony.com/blog/new-in-symfony-4-4-notification-emails#comment-23723

Then I tried to send the message via standard sendmail transport:
```
$transport = new SendmailTransport();
$mailer = new Mailer($transport);
$mailer->send($email);
```

**Possible Solution**  
I tried to trace through the code in `symfony/twig-bridge` and unless I'm missing something, I don't see how it can possibly work.

I cannot figure how or where it is translating the markdown to HTML. There is a template called ` Resources/views/Email/zurb_2/notification/content_markdown.html.twig`, but I don't see any code that uses it.

The `NotificationEmailTest` appears to pass, but it is not a very thorough test and does not attempt to actually send a message.  The test should be improved to check that an HTML message is actually created.

If I had to guess, the working code may still be in a branch on someone's development system.  The released code may have passed the simple tests, but the working code was never correctly checked into github.

**Additional context**  
`PHP Fatal error:  Uncaught Symfony\Component\Mime\Exception\LogicException: A message must have a text or an HTML part or attachments. in /home/avrsites/websites/azvr.com/web/vendor/symfony/mime/Email.php:405`

**Comment by monteiro** [comment]
@lfjeff it would help a lot if you could create a simple symfony 4.4 project and create a console command replicating this issue.

**Comment by lfjeff** [comment]
OK, attached is a sample project that shows the issue.  Run this command to see the problem:
    `bin/console app:test:notification_email user@domain.com`

[test_notification_email.zip](https://github.com/symfony/symfony/files/4022633/test_notification_email.zip)

**Comment by allcode** [comment]
@lfjeff NotificationEmail and the markdown option rely on the use of Twig to render the email body. This is handled via event listeners which render its contents before the email is sent. In your example, you are instantiating the mailer instance yourself, without injecting the application event subscriber. This means that the twig event listeners are not triggered and the email contents is not rendered. This results in a LogicException telling you that the html and text body are not defined.

You should instead inject a MailerInterface instance via the constructor. This will ensure that the provided mailer instance is fully configured. An example can be found [in the documentation](https://symfony.com/doc/4.4/mailer.html). To render markdown, you will also need twig/markdown-extension and a markdown renderer like league/commonmark ([see documentation](https://symfony.com/doc/4.4/mailer.html#rendering-markdown-content)).

**Comment by lfjeff** [comment]
@allcode I'm trying to using this in a standalone PHP application, so I can't rely on Symfony events.  I just created the sample project in order to illustrate the problem.

What you say makes sense, but I've always thought that Symfony components were designed to be used by themselves and not reliant upon the framework.  How can I duplicate the "behind the scenes" stuff that will allow me to send markdown-formatted messages in a non-Symfony application?

**Comment by allcode** [comment]
@lfjeff It's no problem to instantiate it yourself. The message body is rendered via a [MessageListener](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/EventListener/MessageListener.php). With twig integration, this listener is injected with the [Twig BodyRenderer](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Mime/BodyRenderer.php).

To instantiate a Mailer yourself, you have to instantiate an [event dispatcher](https://symfony.com/doc/4.4/components/event_dispatcher.html) and add the MessageListener (make sure you have provided the listener with the twig body renderer instance). Inject the event dispatcher when instantiating the transport instance.

**Comment by lfjeff** [comment]
@allcode That all sounds good, but could you give me a bit of sample code to illustrate?  I don't fully understand how all the pieces you mentioned fit together.

**Comment by lfjeff** [comment]
@allcode It appears that I need to somehow load a Twig template from `NotificationEmail`, but I can't figure out how to do this.

**Comment by allcode** [comment]
You have to make sure that Twig can find the template. To do this, you can create a FilesystemLoader which points to the template path and register it with namespace `email`. More information information about twig loaders can be found [in the documentation](https://twig.symfony.com/doc/3.x/api.html#loaders).
If you want to use markdown, you'll also have to register the [twig/markdown-extra](https://twig.symfony.com/doc/3.x/filters/html_to_markdown.html) extension.

**Comment by lfjeff** [comment]
@allcode Thanks for all your help.  I finally figured out how to put all the pieces together and now it works perfectly.  I'm an old dog, but I learned a few new tricks with this project.

In case someone else is interested in sending markdown-formatted notification emails without using the full Symfony framework, the full working code is below.

I'm in the process of creating a composer package that will allow us to use the same notification emails in our non-Symfony projects.  I've got a basic version working now, but I need to clean things up a bit before I consider posting it on packagist.

````
namespace App\Command;

use Symfony\Bridge\Twig\Mime\BodyRenderer;
use Symfony\Bridge\Twig\Mime\NotificationEmail;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\Mailer\EventListener\MessageListener;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mailer\Transport\SendmailTransport;

use Twig\Loader\FilesystemLoader as TwigFilesystemLoader;
use Twig\Environment as TwigEnvironment;
use Twig\Extra\CssInliner\CssInlinerExtension;
use Twig\Extra\Inky\InkyExtension;
use Twig\Extra\Markdown\DefaultMarkdown;
use Twig\Extra\Markdown\MarkdownExtension;
use Twig\Extra\Markdown\MarkdownRuntime;
use Twig\RuntimeLoader\RuntimeLoaderInterface;

/**
 * simple demo of how to create a command
 *
 * @see https://symfony.com/doc/current/console.html
 * @see https://symfony.com/doc/current/console/input.html
 */
class TestNotificationEmail extends Command
{
    protected function configure()
    {
        $this
            // name of the command (the part after "bin/console")
            ->setName('app:test:notification_email')

            // short description (what will show when running "bin/console list")
            ->setDescription('Test NotificationEmail')

            // full description (what shows when running with "--help" option)
            ->setHelp('Test NotificationEmail')

            // configure arguments
            ->addArgument('email', InputArgument::REQUIRED, 'email address')

            ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $toEmail = $input->getArgument('email');

        $viewsDir = __DIR__.'/../../vendor/symfony/twig-bridge/Resources/views';

        $loader = new TwigFilesystemLoader();
        $loader->addPath("$viewsDir/Email", 'email');
        $loader->addPath("$viewsDir/Form", 'form');

        $twig = new TwigEnvironment($loader);
        $twig->addExtension(new InkyExtension());
        $twig->addExtension(new CssInlinerExtension());
        $twig->addExtension(new MarkdownExtension());

        $twig->addRuntimeLoader(new class implements RuntimeLoaderInterface{
            public function load($class) {
                if (MarkdownRuntime::class === $class) {
                    return new MarkdownRuntime(new DefaultMarkdown());
                }
            }
        });

        $twigBodyRenderer = new BodyRenderer($twig);

        $messageListener = new MessageListener(null, $twigBodyRenderer);

        $dispatcher = new EventDispatcher();
        $dispatcher->addSubscriber($messageListener);

        $transport = new SendmailTransport(null, $dispatcher);
        $mailer = new Mailer($transport);

        $notificationEmail = (new NotificationEmail())
            ->from('info@symfony.com')
            ->to($toEmail)
            ->subject('My first notification email via Symfony')
            ->markdown(<<<EOF
                There is a **problem** on your website, you should investigate it
                right now. Or just wait, the problem might solve itself automatically,
                we never know.
                EOF
            )
            ->action('More Info?', 'https://symfony.com')
            ->importance(NotificationEmail::IMPORTANCE_HIGH);

        $mailer->send($notificationEmail);
    }
}

````

**Comment by lfjeff** [comment]
Figured out how to make it work, not actually a Symfony bug.
