### ISSUE TITLE
is_granted cannot be passed an array as a second argument (subject)

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#35026]
**Symfony version(s) affected**: 5.0.1

**Description**  

Twig function `is_granted` does not accept `mixed` any more for its second argument, instead requiring `object` or `null` with a PHP typehint. `AuthorizationCheckerInterface::isGranted`, where this argument is passed, has no typehint in code and is typehinted as `mixed` in PHPDoc.

This makes it impossible to have a check in Twig template with code similar to this:

`{% if is_granted('ROLE_MY_APP', {foo: 'bar', bar: 'baz'}) %}...{% endif %}`

Is this something that was intended, because it doesn't seem so? Upgrade docs mention that the attribute cannot be an array anymore in `AuthorizationCheckerInterface::isGranted`, but it does not mention that the subject is now required to be a PHP object.

Thank you!

**Comment by stof** [comment]
Given that the phpdoc of the AuthorizationCheckerInterface is `@param mixed $subject`, this indeed looks like a bug in the Twig function.

**Comment by emodric** [comment]
I can make a PR if it is indeed a bug.

**Comment by nicolas-grekas** [comment]
@emodric please do :)

**Comment by emodric** [comment]
Done in https://github.com/symfony/symfony/pull/35028
