### ISSUE TITLE
[Security] Multiple user providers on 1 authenticator can wrongfully re-authenticate

### ISSUE THREAD

**Issue by linaori** [symfony/symfony#35045]
**Symfony version(s) affected**: 3.4, 4.3, 4.4, 5.0

**Description**  
Report to clarify #29653, which was closed due to lack of activity.

There's no check whether a user provider supports a given user during the `refreshUser()` process, thus will attempt to refresh the user against every provider, rather than just the supported providers: https://github.com/symfony/symfony/blob/4d064a258479c9b998b5485cc88ce01a792f1ad5/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L185-L196

I've found a case where:
 - The first the correct provider is hit (`WebsiteUserProvider`), this de-authenticates the token because the user has changed
 - The second provider is hit (`ApiUserProvider`), this one does not support this user class, and immediately returns the User object
```php
    public function refreshUser(UserInterface $user)
    {
        return $user;
    }
```
Because the `ApiUserProvider` gives the same user object back, the token is not de-authenticated after the `setUser()` is called.
```
$refreshedUser = $provider->refreshUser($user); // $user = WebsiteUser instance 1
$newToken = clone $token;
$newToken->setUser($refreshedUser); // $refreshedUser = WebsiteUser instance 1
```

When the token receives a  `setUser($user)` where the instance of `$user` is identical to the instance it contains internally, the token's authentication state will not be changed: https://github.com/symfony/symfony/blob/4d064a258479c9b998b5485cc88ce01a792f1ad5/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L108-L114

Because the second token will not hit the `continue;`, it will return the token and be considered "authenticated", thus the user won't be authenticated. This breaks the de-authentication flow and could result in accounts being logged in while they shouldn't.

_Edit:_
 - The `isSupported()` is not called in the `refreshUser()` for the `ChainUserProvider`, would have to be changed in a similar fashion.

**How to reproduce**  
n/a - will have to make a failing test to prove this

**Possible Solution**  
While `refreshUser()` indicates it can throw a `UnsupportedUserException`, this is not intuitive and is easy to miss, especially as `supportsUser()` exists. I think the solution of #29653 is the right direction. There was some feedback that had not been processed yet and is missing some tests.

**Additional Context**
Does the `UnsupportedUserException` even make sense at this point? It duplicates a feature in two different ways. Some core classes actually throw this exception, which would no longer be required if the `supportsClass()` would be used.

**Comment by chalasr** [comment]
Works for me as a bugfix as we'll keep catching `UnsupportedUserException` anyways.

**Comment by linaori** [comment]
While looking further, the `isSupported()` is not called in the `refreshUser()` for the `ChainUserProvider` either, which means it would break there as well. Adding this to the main issue.

Some other classes will throw the `UnsupportedUserException` in certain scenarios, and I feel like all of those cases could eventually be refactored to all work with `isSupported()`, to reduce the amount of code duplication and complexity. The other option would be to deprecate the `isSupported()` and rely on the `refreshUser()` to throw this, though this feels more error prone, it's an implementation detail that's easily forgotten.
