### ISSUE TITLE
symfony/contracts v1 is NOT compatible with psr/event-dispoatcher

### ISSUE THREAD

**Issue by remicollet** [symfony/symfony#35048]
`PHP Fatal error:  Declaration of Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch($event) must be compatible with Psr\EventDispatcher\EventDispatcherInterface::dispatch(Psr\EventDispatcher\object $event) ...`

So, obviously psr/event-dispatcher should NOT be suggested, and even code should NOT take care of it.

(v2 seems ok, but not tested)

**Comment by remicollet** [comment]
Notice https://github.com/symfony/symfony/blob/4.4/composer.json#L28
V1 is still required by Symfony 4.x

**Comment by nicolas-grekas** [comment]
Please double check that you're actually running this on PHP 7.2+
`Psr\EventDispatcher\object` is a bug hint this is not the case to me.

**Comment by remicollet** [comment]
hmm... indeed, looks like 7.1 was (temporarily enable on my machine... where all version from 5.6 to 7.4 are available)

My bad

**Comment by cbj4074** [comment]
Thanks for explaining this. The cause was not obvious because like you, @remicollet , I have many different interpreters configured in my IDE (PhpStorm) and had selected 7.1 instead of 7.3. Much appreciated!
