### ISSUE TITLE
[Security] PlainTextPasswordEncoder::isPasswordValid() throws an exception when the user has no password set (password is null)

### ISSUE THREAD

**Issue by ammoushbib** [symfony/symfony#35040]
**Symfony version(s) affected**: 4.4

**Description**  
Actually PlainTextPasswordEnocder::isPasswordValid() throws an exception when the user has no password set (password is null)

**How to reproduce**  

When UserInterface::password is null and the encoder is PlainTextPasswordEncoder an exception is thrown 
![image](https://user-images.githubusercontent.com/33282931/71169444-354e9e80-2259-11ea-99b1-2f5163225d2e.png)

**Possible Solution**  

I think PlainTextPasswordEnocder::isPasswordValid() should return false when the user's password is null.

**Comment by xabbuh** [comment]
Do you still experience the issue with Symfony 4.4.2? This may already be fixed by #34779 or #34802.
