### ISSUE TITLE
[Serializer] Improve performance of CacheClassMetadataFactory::getMetadataFor()

### ISSUE THREAD

**Issue by bastnic** [symfony/symfony#35041]
**Symfony version(s) affected**: I'm on 4.4.1 but surely may be all versions

**Description**  
In prod mode, the system cache is a chain [phpArray, apcu]. This is given to CacheClassMetadataFactory that does the job to cache the computed data across each requests. 

On an API Platform, I got this stacktrace tht calls CacheClassMetadataFactory: 

```
#0 /var/www/project/apps/api/vendor/symfony/cache/Adapter/ChainAdapter.php(124): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem('Lib_Core_Entity...')
#1 /var/www/project/apps/api/vendor/symfony/cache/Adapter/PhpArrayAdapter.php(127): Symfony\Component\Cache\Adapter\ChainAdapter->getItem('Lib_Core_Entity...')
#2 /var/www/project/apps/api/vendor/symfony/serializer/Mapping/Factory/CacheClassMetadataFactory.php(54): Symfony\Component\Cache\Adapter\PhpArrayAdapter->getItem('Lib_Core_Entity...')
#3 /var/www/project/apps/api/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(166): Symfony\Component\Serializer\Mapping\Factory\CacheClassMetadataFactory->getMetadataFor('Lib\\Core\\Entity...')
#4 /var/www/project/apps/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php(151): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(Object(Lib\Core\Entity\Site), 'json', Array)
#5 /var/www/project/apps/api/vendor/symfony/serializer/Serializer.php(152): ApiPlatform\Core\Serializer\AbstractItemNormalizer->normalize(Object(Lib\Core\Entity\Site), 'json', Array)
```

The same calls is made a few hundred times. Each hitting apcu. 

![image](https://user-images.githubusercontent.com/84887/71169807-1d2b4f00-225a-11ea-9019-79ae0df19c95.png)

A very simple local cache clears everything:

![image](https://user-images.githubusercontent.com/84887/71169867-3e8c3b00-225a-11ea-8e00-c9d781c39044.png)

**How to reproduce**  
basic apip and symfony with last versions and apcu available. But should be reproducible with any use of AbstractObjectNormalizer.php.

**Possible Solution**  
I'm not sure about the correct fixe:
- a simple local cache
- inject another chain cache containing a simple array specifially to this cache, as it has no chance to change in prod mode.
- inject an array adapter in system cache, but seems more dangerous (https://github.com/symfony/symfony/pull/32294#issuecomment-508067745)
- phparray should have it precalculated?
- fix it in userland (symfony/serializer/Normalizer/AbstractObjectNormalizer.php)
- did I missed something?

**Comment by bastnic** [comment]
ping @dunglas as it concerns apip and it wrote CacheClassMetadataFactory

**Comment by dunglas** [comment]
A local cache looks like the best, and easiest fix to me.

**Comment by nicolas-grekas** [comment]
I would prefer using an ArrayAdapter in DI configuration.
Handling local caches is added complexity we should avoid.

**Comment by fbourigault** [comment]
What about https://github.com/symfony/symfony/pull/29117?

**Comment by bastnic** [comment]
@fbourigault love the idea of the warmer!

The proposed fix fixes potentially more than just this issue, and could clean some userland local caches.

**Comment by fbourigault** [comment]
I'm curious about such figures as ClassMetadataFactoryInterface expects implementations to have a local cache.
https://github.com/symfony/symfony/blob/bd9dc7c573f537c5a751fc3543774cab9ad4770b/src/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactoryInterface.php#L25-L26

**Comment by bastnic** [comment]
ping #34708
