### ISSUE TITLE
[Mailer] message metadata and tags

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#35047]
**Description**  
Transports like Postmark and Mailgun support message metadata and tags. The context of this issue will be Postmark.

#34766 implements tag support in Postmark by using a `Tag` header. This will work when using the Postmark API transport but not using the SMTP transport. For SMTP you need to add a custom header: 

```
X-PM-Tag: password-reset
```

With the Postmark API, metadata is a key, value object added to the payload:

```json
"Metadata": {
    "Color":"blue",
    "Client-Id":"12345"
}
```

With SMTP, it is a custom header for each value:

```
X-PM-Metadata-Color: blue
X-PM-Metadata-Client-Id: 12345
```

**Example**  
Ideally, it would be nice to be able to do the following:

```php
$email->setTag('password-reset');
$email->addMetadata('Color', 'blue');
$email->addMetadata('Client-Id, '12345');
```

Then the transports could convert to their specific tag/metadata format.

I can work on a PR for this if we can nail down how we want this to work.

**Comment by fabpot** [comment]
I did not implement features that are not standards. If we want to implement some of these features, we should think of an abstraction for all/most transports. I don't want to recreate specific abstractions for each transport.

**Comment by kbond** [comment]
What about two new headers:

```php
class TagHeader extends UnstructuredHeader
{
    public function __construct(string $value)
    {
        parent::__construct('X-Tag', $value);
    }
}
```

```php
class MetadataHeader extends UnstructuredHeader
{
    private $key;

    public function __construct(string $name, string $value)
    {
        $this->key = $name;

        parent::__construct('X-Metadata-'.$name, $value);
    }
    
    public function getKey(): string
    {
        return $this->key;
    }
}
```

When creating an email, you can then do the following:

```php
$email->getHeaders()->add(new TagHeader('password-reset'));
$email->getHeaders()->add(new MetadataHeader('Color', 'blue'));
$email->getHeaders()->add(new MetadataHeader('Client-ID', '12345'));
```

If a transport doesn't support metadata, the headers are just added to the message:

```
X-Tag: password-reset
X-Metadata-Color: blue
X-Metadata-Client-ID: 12345
```

**Comment by fabpot** [comment]
Sounds like a good idea. Is the "tag" and "metadata" "concepts" shared among third-party providers?

**Comment by kbond** [comment]
@fabpot [I replied here](https://github.com/symfony/symfony/pull/35050#issuecomment-567541369) to move the conversation to the PR.

**Comment by fabpot** [comment]
Closing to focus on the PR now.
