### ISSUE TITLE
[security] redirection fault with balancer managing https certificates

### ISSUE THREAD

**Issue by belinde** [symfony/symfony#35054]
Trying to simplify the management of HTTPS certificates on all servers, our IT department tried to place the certificates only on the load balancer. At the moment the DNS points to the balancer that listen only on 443 port (the application shouldn't run on http); the balancer decrypt the request and pass as http on port 80 to the webserver.
The problem is that for Symfony the request is a plain http one; that's not normally an issue, because all the links are managed as absolute paths and the few cross domain redirection that I do are now done as network paths. In the security component, though, the `Symfony\Component\Security\Http\EntryPoint\FormAuthenticationEntryPoint` use the `createRedirectResponse()` method of `Symfony\Component\Security\Http\HttpUtils`.
If I put a path as a target of the login page I got redirect using scheme and host from the request, so I get an http, and the balancer bounce me. If I use a route name and I try to juggle with the schemes (using also `""`, empty string) the better thing I get is being redirect, bounced, but on a reload I get access.

Is there any recommended way to deal with this kind of situation? Basically I'd need to get ALWAYS redirections as network paths, but doesn't seem to exist such an opportunity.

**Comment by dmaicher** [comment]
Maybe this helps?
https://symfony.com/doc/current/routing.html#routing-force-https

**Comment by cfoehrdes** [comment]
If I understand correctly you are explaning the concept of TLS termination. In this case the load balancer or proxy is terminating the TLS (https) connection and forwarding the request without encryption via http to the actual web server. When implementing this the load balancer or proxy usually adds `X-Forwarded-*` headers to the request to give the application information about the original request. This header family has an `X-Forwarded-Proto` header containing the protocol used by the request sent from client to the load balancer. In your example this header would have the value `https`.

You should have a look at the [documentation article about proxys](https://symfony.com/doc/current/deployment/proxies.html). They explain how you can tell symfony which headers it should trust from a proxy. When setting up symfony to trust your load balancers IP and the `X-Forwarded-Proto` header it will treat the request as https even when receiving it via http.

**Comment by belinde** [comment]
@dmaicher pointed out the right solution for me! I imagined that a simple approach should have been enough, but I didn't find that page in the docs.
Informations provided by @cfoehrdes are also useful and I'm sure that in the future I'll make good use of them, so really thank you!
