### ISSUE TITLE
[twig] dump runs out of memory

### ISSUE THREAD

**Issue by kavalanche** [symfony/symfony#35052]
**Symfony version(s) affected**: 5.0.1, 4.2.1, possibly earlier

**Description**  
Using `{{ dump(object) }}` in Twig results in blank screen and memory limit exhausted error.

**How to reproduce**  
Put `{{ dump(object) }}` in twig file.

**Possible Solution**  
`vendor/twig/twig/src/Extension/DebugExtension.php` uses var_dump, which runs out of memory.
`vendor/symfony/twig-bridge/Extension/DumpExtension.php` seems to be correct but is not used.
Maybe there is a way to use the latter file?

**Comment by strawburrypokki** [comment]
might be related to https://github.com/symfony/symfony/issues/31077#issuecomment-567539017

**Comment by kavalanche** [comment]
Yes, it is related. I checked the `symfony/debug-bundle` and it works as expected.
