### ISSUE TITLE
symfony/messenger component doesn't work with doctrine-bundle v2.0

### ISSUE THREAD

**Issue by floriansemm** [symfony/symfony#35068]
**Symfony version(s) affected**: 4.4.1 / 4.4.2

**Description**  
The problem is the same as in https://github.com/symfony/symfony/issues/34514

After updating Symfony and doctrine-bundle to 2.0 the `messenger:consume` throws the exception

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /var/cache/dev/ContainerXxHOhVH/getMessenger_Transport_Doctrine_FactoryService.php on line 9 in /vendor/symfony/messenger/Transport/Doctrine/DoctrineTransportFactory.php:29
```

**How to reproduce**  
`composer update` + `./bin/console messenger:consume`

**Comment by dmaicher** [comment]
This seems strange. You are really using `symfony/messenger` 4.4.2?

https://github.com/symfony/symfony/blob/v4.4.2/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php#L28

I don't see how it can trigger the error you describe.

**Comment by xabbuh** [comment]
Please provide a small example application that allows to reproduce your issue.

**Comment by floriansemm** [comment]
We had those two lines in our `composer.json` 
```
"symfony/http-client": "4.3.*",
"symfony/messenger": "*",
```

This restricted the messenger-package to version 4.3.*. I have changed this and everything works as expected. Sorry for the confusion ;)
