### ISSUE TITLE
Internationalized urls: UrlGenerator lost locale passed in parameter

### ISSUE THREAD

**Issue by dsoriano** [symfony/symfony#35069]
**Symfony version(s) affected**: 4.2.12 to 5.0.2, probably 4.1 too

**Description**  
On internationalized urls, when you want to generate an url with non default locale, this locale is overriden by default.

**How to reproduce**  
This controller for example :

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;

class FooController extends AbstractController
{
    /**
     * @var RouterInterface
     */
    private $router;

    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    /**
     * @Route({
     *  "en": "/foo",
     *  "fr": "/bar"
     *  }, name="foo")
     *
     *
     */
    public function index()
    {
        return new Response($this->router->generate('foo', ['_locale' => 'en']));
    }
}
```
if you go to url `/fr/bar` the url generated is `/fr/foo` instead of `/en/foo`

The problem is not on non internationalized urls

**Possible Solution**  
Problem is coming from the new system of internationalized urls. 

In UrlGenerator::generate() method, the parameters of `foo.en` route are fetched and `_locale` is removed from `$parameters`

```php
        if (null !== $locale) {
            do {
                if (null !== ($route = $this->routes->get($name.'.'.$locale)) && $route->getDefault('_canonical_route') === $name) {
                    unset($parameters['_locale']);
                    break;
                }
            } while (false !== $locale = strstr($locale, '_', true));
        }
```
When UrlGenerator::doGenerate() is called, parameters are merged :

```php
$mergedParams = array_replace($defaults, $this->context->getParameters(), $parameters);
```

`$parameters` doesn't contain `_locale` anymore and `$this->context->getParameters()` overwrite the `_locale` of `$defaults`

A possible solution is to update the parameters merge with :

```php
$mergedParams = array_replace($this->context->getParameters(), $defaults, $parameters);
```

**Comment by xabbuh** [comment]
This looks like the same as #34469.
