### ISSUE TITLE
Randomly 500 loading debug toolbar

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#35086]
**Symfony version(s) affected**: 4.4.2

**Description**  
Sometimes web debug toolbar doesn't load becasue a 500 errors. It throws Argument 1 passed to Symfony\Component\HttpKernel\Profiler\Profile::setCollectors() must be of the type array, null given, called in xxx/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php on line 281

**How to reproduce**  
Randomly debug toolbar

**Possible Solution**  

**Additional context**  
Updatin a project to symfony 4.4

**Comment by markitosgv** [comment]
I found the issue, when I executed 
```
bin/console debug:event
```

It throws me an error:

```
[Symfony\Component\Mime\Exception\RfcComplianceException]  
  Email "" does not comply with addr-spec of RFC 2822.
```

Solving this, it appears WDT always works.

Thanks!

**Comment by ProElbs** [comment]
Hi there,

Did you find the solutio? I've got the exact same error and it drives me nuts !

**Comment by xabbuh** [comment]
Can anyone of you create a small example application that allows to reproduce the issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by ProElbs** [comment]
Sorry, due to Covid-19 pandemic, I didnt had time to do a quick project to show you this

**Comment by xabbuh** [comment]
Don't worry about that. Just leave us a comment here when things have cleared up a bit and we can then reopen.

**Comment by captain-digitalsailors** [comment]
I am not a symfony expert, so this is a wild guess based on observations:

I see the same issue. I am running a symfony app locally on MacOS behind nginx/php-fpm. Whenever I get a 500 status for the _wdt request and manually do that request again, it succeeds and the data looks good. 

Could it be, that the first request is so quick that the file in the cache is in some undefined state? The error in xxx/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php described in the initial description could point to that, too.

**Comment by Surf-N-Code** [comment]
I just had this issue. On my docker container symfony sometimes doesn't have enough rights to write to the cache, which I store in /dev/shm/... Clearing the cache helped in my case with this issue.
