### ISSUE TITLE
Annotation validation failed on validating array of objects

### ISSUE THREAD

**Issue by gundamftw** [symfony/symfony#35083]
**Symfony version(s) affected**: 5 / 4.2

**Description**  
In my DTO/entity class, I have a property that holds an array of objects, according to the documentation, the `@Assert\All` and `@Assert\Collection` combination should be use to validate this. This did work when writing the constraint in php form, but failed with annotation form. The validation will fail with the error, for my case  `Object(App\DTO\InfoDTO).images[0]: This value should be of type array`.

A question in [stackoverflow](https://stackoverflow.com/questions/54769002/validating-collectiontype-array-of-object-symfony-4-2) also reported the same problem. What he ended up is writing the constraint in php form.

**How to reproduce**  
my object structure:
```
{
    "id": 1,
    "name": "mike",
    "images": [
        { "id": 1 },
        { "id": 2 }
    ]
}
```

DTO class

```
class InfoDTO
{
    /**
     * @Assert\All({
     *    @Assert\Collection(
     *        fields = {
     *            "id" = @Assert\Type("integer")
     *        }
     *    )
     * })
      */
    $images;
}
```
The validation passes if I took out the `"id" = @Assert\Type("integer")` line.

**Comment by xabbuh** [comment]
How did you configure the constraints using PHP when this used to work?

**Comment by gundamftw** [comment]
I wrote the constraint in the controller

```
$constraint = new Assert\All(['constraints' => [
                          new Assert\Collection([
				'id'	=> [	new Assert\Type('integer') ]
                          ]
                     ]);

$error = $validator->validate(InfoObject['images'], $constraint);
```

**Comment by xabbuh** [comment]
I cannot spot a difference here. Can you create a small example application that allows to reproduce this please?

**Comment by gundamftw** [comment]
After many tests, I found that both the annotation and php form will fail complaining about the property not being an array. However the php form will pass if I convert the object to array and validate that array.

// converting object to array
$infoArray = json_decode(json_encode($infoObject), true);
$errors = $validator->validate($infoArray['images'], $constraint);   // this will pass

Here's my sample test project:
https://www.mediafire.com/file/r78g7ll8kvsz3br/sample_project.7z/file

**Comment by xabbuh** [comment]
What type is the object that you validate before casting it to an array?

**Comment by gundamftw** [comment]
In my own app, the object was converted from a json string from a post request
```
$jsonData = $request->getContent();
$dataObject = json_decode($jsonData);
```

In the test app, the object was created using std class with some properties
```
$infoObject = new \stdClass();
$infoObject->id = 1;
$infoObject->images = [(object)['id'=> 1], (object)['id'=> 2]];
```

**Comment by xabbuh** [comment]
That's expected then. You cannot validate `stdClass` instances this way.

**Comment by gundamftw** [comment]
Okay I think I got it. The validation can only validates arrays, so in order to validate my array of objects, I need to convert it to array of arrays first? For my case working with json and DTO, I will need to convert the json to array, then store them into DTO, then run the validation on the DTO?

**Comment by xabbuh** [comment]
Why don't you add validation constraints to your DTO so that you can validate it directly?

**Comment by gundamftw** [comment]
I did, see my first post, I have annotation on my DTO properties.

**Comment by MAZEN-Kenjrawi** [comment]
This is the correct expectation of the `Assert\Collection`.
See the [Collection constraint documentation](https://symfony.com/doc/current/reference/constraints/Collection.html):

> This constraint is used when the underlying data is a collection (i.e. an array or an object that implements Traversable and ArrayAccess)

You are using it to validate an `stdClass`, which is wrong.

A better approach for your case is to define an `ImageDTO`:
```
class Image
{
    /**
     * @Assert\Type("integer")
     */
    $id;
}
```

And in your `InfoDTO`:
```
class Info
{
    /**
     * @Assert\All({
     *    @Assert\Type("App\Model\Image")
     * })
     * @Assert\Valid
     */
    $images;
}
```
Note the new `@Assert\Valid` annotation above the `$images` it used to perform `ImageDTO` validation check while validating the `InfoDTO` instance.

**Comment by gundamftw** [comment]
> This is the correct expectation of the `Assert\Collection`.
> See the [Collection constraint documentation](https://symfony.com/doc/current/reference/constraints/Collection.html):
> 
> > This constraint is used when the underlying data is a collection (i.e. an array or an object that implements Traversable and ArrayAccess)
> 
> You are using it to validate an `stdClass`, which is not correct.
> 
> A better approach for your case is to define an `ImageDTO`:
> 
> ```
> class ImageDTO
> {
>     /**
>      * @Assert\Type("integer")
>      */
>     $id;
> }
> ```
> 
> And in your `InfoDTO`:
> 
> ```
> class InfoDTO
> {
>     /**
>      * @Assert\All({
>      *    @Assert\Type("App\DTO\ImageDTO")
>      * })
>      * @Assert\Valid
>      */
>     $images;
> }
> ```
> 
> Note the new `@Assert\Valid` annotation above the `$images` it used to perform `ImageDTO` validation check while validating the `InfoDTO` instance.

Hi I tried your method, but it's giving me a validation error.

```
Object(App\DTO\InfoDTO).images[0]:
    This value should be of type App\DTO\ImageDTO. 
Object(App\DTO\InfoDTO).images[1]:
    This value should be of type App\DTO\ImageDTO. 
Object(App\DTO\InfoDTO).images[2]:
    This value should be of type App\DTO\ModelPartDTO.
```

**Comment by MAZEN-Kenjrawi** [comment]
@gundamftw 
The images now should be an instances of `App\DTO\ImageDTO`.

Suppose you have setup the setters and getters correctly, so your code should look like this:
```php
$images = [
    (new ImageDTO())->setId(4),
    (new ImageDTO())->setId(5),
];

$info = new InfoDTO();
$info->setImages($images);
```

**Comment by xabbuh** [comment]
In any case, this does not look like a bug to me, but rather how to use the component. For support, please refer to one of the [support channels](https://symfony.com/support). So I am going to close here as we use GitHub only to track bugs and feature requests. Thank you for understanding.
