### ISSUE TITLE
Incorrect PHPDoc for ValidatorInterface::validate(), that confused a lot

### ISSUE THREAD

**Issue by alexs76** [symfony/symfony#35088]
**Symfony version(s) affected**: 3.4+, 4.4+, etc

**Description**  
ValidatorInterface::validate() contains incorrect PHPDoc line
`@param array|null  $groups`, but should be mixed, because this parameter can be GroupSequence class. Also, there is the same situation with related classes

![image](https://user-images.githubusercontent.com/15169703/71359646-c60ddd00-25bf-11ea-9ba4-fcd1d737ea84.png)

it's very confusing

**Possible Solution**  
Fix PHPDoc. just need to replace on array|GroupSequence|null

**Comment by adriangornypl** [comment]
Hm, for 3.4 version I can see that it is actually

>  (string|GroupSequence)[]

 so it's pretty valid to me :) What version are you using?

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php

**Comment by alexkingdom** [comment]
Seems the problem only for 3.3 Symfony and was fixed in 3.4

**Comment by alexs76** [comment]
ah, yes
for 3.4 is ok 
`@param string|GroupSequence|(string|GroupSequence)[]|null $groups`
