### ISSUE TITLE
[Console] identical alternatives shouldn't be considered ambiguous

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#35089]
symfony/messenger 4.4
![изображение](https://user-images.githubusercontent.com/12619075/71363257-49412a00-25e4-11ea-9b70-a146b526a957.png)
![изображение](https://user-images.githubusercontent.com/12619075/71363272-552cec00-25e4-11ea-9393-998366fd99d6.png)
![изображение](https://user-images.githubusercontent.com/12619075/71363533-32e79e00-25e5-11ea-91e7-82dc07d43160.png)

symfony/messenger 5.0
![изображение](https://user-images.githubusercontent.com/12619075/71363339-886f7b00-25e4-11ea-9f68-435707331b0f.png)
![изображение](https://user-images.githubusercontent.com/12619075/71363431-d5535180-25e4-11ea-887a-256e5813790a.png)

**Comment by toooni** [comment]
So what? Use `message:consume` and you are on the safe side when `messenger:consume-messages` is removed. Or make a PR yourself.

**Comment by nicolas-grekas** [comment]
Looks like we could collapse multiple identical alternatives and skip the ambiguity.
I'm reclassifying this issue as a feature request on the Console component.
@zorn-v up for a PR?

**Comment by fancyweb** [comment]
The `messenger:consume-messages` command was removed in Symfony 5.0. I cannot reproduce the original issue of still having this command in 5.0.

**Comment by zorn-v** [comment]
Yep, my fault. Deprecated command removed from `symfony/console` component, not `symfony/messenger`. But issue was not useless anyway :smile:
