### ISSUE TITLE
[Mailer][Postmark] Header value contains the header name

### ISSUE THREAD

**Issue by fbourigault** [symfony/symfony#35095]
**Symfony version(s) affected**: 4.4.2

**Description**
In https://github.com/symfony/symfony/blob/4e5b15353d643316fe9d47a0e2b654e7d706abb8/src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php#L87, the header value is set using `$header->toString()`. This looks wrong to me as `$email->getHeaders()->add(new UnstructuredHeader('X-PM-Metadata-emailUuid', '7ebbf720-e280-4f70-ad5c-89729ee708fa'))` will produce a header with the whole header line as a value (i.e. `X-PM-Metadata-emailUuid: 7ebbf720-e280-4f70-ad5c-89729ee708fa`.

The header value should be `7ebbf720-e280-4f70-ad5c-89729ee708fa`.

**Possible Solution**  
In this case, does the solution is to use `$header->getBodyAsString()` to get the value?

**Comment by fabpot** [comment]
Can you submit a PR for a fix? Also, can you check that we did not make the same mistake elsewhere (in other providers)?
