### ISSUE TITLE
[Form][HttpFoundation] Filtering FileBag removes items from CollectionType with FileType

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#35100]
**Symfony version(s) affected**: all

**Description**  
Similar to https://github.com/symfony/symfony/issues/24546

When file is not uploaded I get previously defined one but it's impossible to separate deletion of collection item and not uploading a file

**How to reproduce**  
```php
class IssueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('files', CollectionType::class, [
                'entry_type' => FileType::class,
                'entry_options' => [
                    'required' => false,
                ],
                'allow_add' => true,
                'allow_delete' => true,
            ])
        ;

        $builder->get('files')->addEventListener(FormEvents::PRE_SUBMIT, function(FormEvent $event) {
            $data = (array)$event->getForm()->getData();
            $exist = [];
            foreach ((array)$event->getData() as $index => $item) {
                // Expect 0 => null for not uploaded file
                if ($item !== null) {
                    $data[$index] = $item; // Replace file
                }

                $exist[$index] = true;
            }

            $keys = array_keys($data);
            foreach ($keys as $key) {
                if (!isset($exist[$key])) {
                    unset($data[$key]); // Remove deleted element
                }
            }

            $event->setData($data);
        });
    }
}
```

**Comment by xabbuh** [comment]
I am not sure that I understand what you mean. Can you explain what you expected and what happened instead?

**Comment by BoShurik** [comment]
@xabbuh here is the reproducer https://github.com/BoShurik/symfony-file-bag-issue

When you submit form without uploading files, collection with FileTypes resets

**Comment by xabbuh** [comment]
If I understand your concerns correctly, this is just how handling HTML forms work here. If you do not select a file to be uploaded, the client will not send any data for it so it even won't be `null` on the side where the Form component is doing its job.

So I am going to close here as there is nothing we can change in the component.

If I understood you wrong, please leave a comment with some more explanation and we can consider to reopen.

**Comment by BoShurik** [comment]
Problem in HttpFoundation component.
```
<input type="file" name="single">
<input type="file" name="multiple[]" multiple="multiple">

<input type="file" name="array[0]">
<input type="file" name="array[1]">

<input type="file" name="hash[key0]">
<input type="file" name="hash[key1]">
```

```
dump($request->files->get('single')); // null
dump($request->files->get('multiple')); // []
dump($request->files->get('array')); // []
dump($request->files->get('hash')); // { key1 => null, key2 => null }
```

`hash` and `single` receive `null`s

The problem is that client do send data: `UPLOAD_ERR_NO_FILE` - is what I need.

As I can see https://github.com/symfony/symfony/pull/24198 was introduced to fix `FileType` with `multiple => true` 

> This causes a problem later when using FileType with multiple option - if no files are sent the form data are [0 => ''] instead of [].

I tried to remove [changes](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/FileBag.php#L91-L93) made in that PR and all tests in Form component are pass,
`FileType` with `multiple => true` is produce correct result (`[]`) with empty file 

```
dump($request->files->get('single')); // null
dump($request->files->get('multiple')); // [ 0 => null]
dump($request->files->get('array')); // [ 0 => null, 1 => null]
dump($request->files->get('hash')); // { key1 => null, key2 => null }
```

Does this change considered as a BC break? If so, maybe you know a workaround? 
I tried to use string keys for a collection (with DataTransformer) but looks like it is ignored in [ResizeFormListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php)

**Comment by BoShurik** [comment]
@xabbuh filtering `$request->files` can be easily achieved in resulting application, but it's impossible to unfilter it
