### ISSUE TITLE
cache:clear

### ISSUE THREAD

**Issue by azarual** [symfony/symfony#35105]
**Symfony version(5.0.0) 

**Description**  
the   php bin/console cache:clear   doesn't work 

**How to reproduce**  
i modified my entity by deleting a proprety (also deleted them from BDD and every thing in order migrations and ...) but it keeps looking for the column  in BDD

**Possible Solution**  
 I must every time delete it manualy in the folder var

**Additional context**  
it makes me think about another issue when i didn't detecte changes in the entity when trying to megrate and we had to run the command php bin/vonsole doctrine:migrations:cache:clear-metedata

**Comment by xabbuh** [comment]
Can you please show the output of `composer show`?

**Comment by azarual** [comment]
Of course and i hope that this will help.

C:\Symfony Projects\AzaImmo>composer show
behat/transliterator                v1.2.0  String transliterator
cocur/slugify                       v3.2    Converts a string into a slug.
doctrine/annotations                v1.8.0  Docblock Annotations Parser
doctrine/cache                      1.9.1   PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                1.6.4   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     v2.11.0 PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection suppor...
doctrine/data-fixtures              1.4.0   Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.10.0 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            2.0.0   Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle   3.3.0   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle 2.1.2   Symfony DoctrineMigrationsBundle
doctrine/event-manager              1.1.0   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                  1.3.1   Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.3.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.2.0   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 2.2.0   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and ...
doctrine/orm                        v2.7.0  Object-Relational-Mapper for PHP
doctrine/persistence                1.2.0   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 v1.0.0  Doctrine Reflection component
easycorp/easy-log-handler           v1.0.9  A handler for Monolog that optimizes log messages to be processed by humans instead of software. Improve your productivity with logs that are easy to u...
egulias/email-validator             2.1.11  A library for validating emails against several RFCs
fzaninotto/faker                    v1.9.1  Faker is a PHP library that generates fake data for you.
jdorn/sql-formatter                 v1.2.17 a PHP SQL highlighting library
jms/metadata                        2.1.0   Class/method/property metadata management in PHP
knplabs/knp-components              v2.3.0  Knplabs component library
knplabs/knp-paginator-bundle        v5.0.0  Paginator bundle for Symfony to automate pagination and simplify sorting and other features
monolog/monolog                     2.0.1   Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser                    v4.3.0  A PHP parser written in PHP
ocramius/package-versions           1.4.2   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.2.3   A library providing utilities to generate, instantiate and generally operate with Object Proxies
phpdocumentor/reflection-common     2.0.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         1.0.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                1.0.0   Standard interfaces for event handling.
psr/link                            1.0.0   Common interfaces for HTTP links
psr/log                             1.1.2   Common interface for logging libraries
sensio/framework-extra-bundle       v5.5.1  This bundle provides a way to configure your controllers with annotations
symfony/asset                       v5.0.0  Symfony Asset Component
symfony/browser-kit                 v5.0.0  Symfony BrowserKit Component
symfony/cache                       v5.0.0  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts             v2.0.0  Generic abstractions related to caching
symfony/config                      v5.0.0  Symfony Config Component
symfony/console                     v5.0.0  Symfony Console Component
symfony/css-selector                v5.0.0  Symfony CssSelector Component
symfony/debug-bundle                v5.0.0  Symfony DebugBundle
symfony/debug-pack                  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection        v5.0.0  Symfony DependencyInjection Component
symfony/doctrine-bridge             v5.0.0  Symfony Doctrine Bridge
symfony/dom-crawler                 v5.0.0  Symfony DomCrawler Component
symfony/dotenv                      v5.0.0  Registers environment variables from a .env file
symfony/error-handler               v5.0.0  Symfony ErrorHandler Component
symfony/event-dispatcher            v5.0.0  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v2.0.0  Generic abstractions related to dispatching event
symfony/expression-language         v5.0.0  Symfony ExpressionLanguage Component
symfony/filesystem                  v5.0.0  Symfony Filesystem Component
symfony/finder                      v5.0.0  Symfony Finder Component
symfony/flex                        v1.4.8  Composer plugin for Symfony
symfony/form                        v5.0.0  Symfony Form Component
symfony/framework-bundle            v5.0.0  Symfony FrameworkBundle
symfony/http-client                 v5.0.0  Symfony HttpClient component
symfony/http-client-contracts       v2.0.0  Generic abstractions related to HTTP clients
symfony/http-foundation             v5.0.0  Symfony HttpFoundation Component
symfony/http-kernel                 v5.0.0  Symfony HttpKernel Component
symfony/inflector                   v5.0.0  Symfony Inflector Component
symfony/intl                        v5.0.0  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                      v5.0.2  Symfony Mailer Component
symfony/maker-bundle                v1.14.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                        v5.0.0  A library to manipulate MIME messages
symfony/monolog-bridge              v5.0.0  Symfony Monolog Bridge
symfony/monolog-bundle              v3.5.0  Symfony MonologBundle
symfony/notifier                    v5.0.0  A library to notify messages
symfony/options-resolver            v5.0.0  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.7  A pack for the Doctrine ORM
symfony/phpunit-bridge              v5.0.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme      v1.12.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu           v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn           v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer    v1.12.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73              v1.12.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                     v5.0.0  Symfony Process Component
symfony/profiler-pack               v1.0.4  A pack for the Symfony web profiler
symfony/property-access             v5.0.0  Symfony PropertyAccess Component
symfony/property-info               v5.0.0  Symfony Property Info Component
symfony/routing                     v5.0.0  Symfony Routing Component
symfony/security-bundle             v5.0.0  Symfony SecurityBundle
symfony/security-core               v5.0.0  Symfony Security Component - Core Library
symfony/security-csrf               v5.0.0  Symfony Security Component - CSRF Library
symfony/security-guard              v5.0.0  Symfony Security Component - Guard
symfony/security-http               v5.0.0  Symfony Security Component - HTTP Integration
symfony/serializer                  v5.0.0  Symfony Serializer Component
symfony/serializer-pack             v1.0.2  A pack for the Symfony serializer
symfony/service-contracts           v2.0.0  Generic abstractions related to writing services
symfony/stopwatch                   v5.0.0  Symfony Stopwatch Component
symfony/string                      v5.0.0  Symfony String component
symfony/templating                  v5.0.2  Symfony Templating Component
symfony/test-pack                   v1.0.6  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                 v5.0.0  Symfony Translation Component
symfony/translation-contracts       v2.0.0  Generic abstractions related to translation
symfony/twig-bridge                 v5.0.0  Symfony Twig Bridge
symfony/twig-bundle                 v5.0.0  Symfony TwigBundle
symfony/twig-pack                   v1.0.0  A Twig pack for Symfony projects
symfony/validator                   v5.0.0  Symfony Validator Component
symfony/var-dumper                  v5.0.0  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v5.0.0  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                    v5.0.0  Symfony WebLink Component
symfony/web-profiler-bundle         v5.0.0  Symfony WebProfilerBundle
symfony/webpack-encore-bundle       v1.7.2  Integration with your Symfony app & Webpack Encore!
symfony/yaml                        v5.0.0  Symfony Yaml Component
twig/extra-bundle                   v3.0.0  A Symfony bundle for extra Twig extensions
twig/twig                           v3.0.0  Twig, the flexible, fast, and secure template language for PHP
vich/uploader-bundle                1.12.1  Ease file uploads attached to entities
webmozart/assert                    1.5.0   Assertions to validate method input/output with nice error messages.
zendframework/zend-code             3.4.0   Extensions to the PHP Reflection API, static code scanning, and code generation
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application

**Comment by xabbuh** [comment]
Does the issue persist when you update the DoctrineBundle? This looks like it could be the same as doctrine/DoctrineBundle#1069.

**Comment by xabbuh** [comment]
Let's close here for now. We can consider to reopen if it turns out that updating DoctrineBundle does not help.
