### ISSUE TITLE
[HttpClient] Infinite loop with mbstring.func_overload enabled on php 7.2

### ISSUE THREAD

**Issue by TiGR** [symfony/symfony#35114]
**Symfony version(s) affected**: 4.4.2

**Description**  
Here:
https://github.com/symfony/symfony/blob/b138fbcb891f05d788b6506530bfb6dc8082e803/src/Symfony/Component/HttpClient/HttpClientTrait.php#L495
When `mbstring.func_overload` 1 or 2 `substr` here returns false instead of empty line. As result, exit condition is never met.

**How to reproduce**  
Use PHP 7.2. Set `mbstring.func_overload` to 1 or 2, and make any request, containing path part (e.g `https://google.com/index.html`)

**Possible Solution**  
Add `false` to list of exit conditions here:
https://github.com/symfony/symfony/blob/b138fbcb891f05d788b6506530bfb6dc8082e803/src/Symfony/Component/HttpClient/HttpClientTrait.php#L483

Or add check for `false` here:
https://github.com/symfony/symfony/blob/b138fbcb891f05d788b6506530bfb6dc8082e803/src/Symfony/Component/HttpClient/HttpClientTrait.php#L495

**Comment by nicolas-grekas** [comment]
>  Add false to list of exit conditions here:

can you please send a PR doing so, branch 4.3?

**Comment by stof** [comment]
IIRC, we dropped supported for `mbstring.func_overload` in the framework in 4.x

**Comment by nicolas-grekas** [comment]
> we dropped supported for mbstring.func_overload

Sure, but if all it takes is adding `false` in this list, we can still do it imho.
@TiGR please check if there is anything else of course.

**Comment by TiGR** [comment]
So,as per PR discussion it's a wontfix. Closing then.
