### ISSUE TITLE
Use horizontal ellipsis

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#35143]
**Description**  
We have a lot of occurences of `...` (3 points) in the code. We could use `…` (horizontal ellipsis) instead since it carries a meaning.

👍 or 👎?

**Comment by linaori** [comment]
I don't even know how to type that, I don't think that makes sense.

**Comment by nicolas-grekas** [comment]
That would defacto make the messages incompatible with non-utf8 systems, eg the windows cmd.exe

**Comment by fancyweb** [comment]
> I don't even know how to type that, I don't think it makes sense.
I meant when we display it. Especially in console commands.

**Comment by linaori** [comment]
@fancyweb When this becomes a standard within Symfony, that means contributors have to be able to use this standard as well.

**Comment by ro0NL** [comment]
i cannot type `€` either ... i have to google it. But it doesnt mean the EUR sign should not be used because of it.

overall we should prefer `xxx …` over `xxx...` IMHO.

However, if it breaks non utf systems it may need a ternary solution; `$cond ? '…' : '...'`. At this point im not sure it's worth it.

**Comment by linaori** [comment]
With the difference that you don't have to write the Euro sign in the source code.

**Comment by fancyweb** [comment]
I guess we can close this one 😅

**Comment by staabm** [comment]
could we get a constant or method, which can handle the ellipsis like symfony/thanks does for the used icons?

https://github.com/symfony/thanks/blob/a8a5fbe3907a52cb7e2bb704d3b0231782b4193c/src/Thanks.php#L92-L102

that way we would e.g. call a method, which returns whatever the current terminal supports
