### ISSUE TITLE
[BrowserKit] HttpBrowser ignores base uri of HttpClient

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#35159]
**Symfony version(s) affected**: >= 4.3

**Description**
The HttpBrowser ignores the base uri of a ScopingHttpClient & uses localhost instead. This is because the AbstractBrowser [converts the uri to an absolute uri](https://github.com/symfony/symfony/blob/b38a717d78d9c189a989abc0651b6c83a78d8d7c/src/Symfony/Component/BrowserKit/AbstractBrowser.php#L357) by using the HTTP_HOST server variable. Since the varibale is not set it fallbacks to localhost.

**How to reproduce**
```php
use Symfony\Component\BrowserKit\HttpBrowser;
use Symfony\Component\HttpClient\HttpClient;

$browser = new HttpBrowser(HttpClient::createForBaseUri('https://www.mydomain.com'));

$browser->request('GET', '/somepage.html');

/** @var Symfony\Component\BrowserKit\Request $request */
$request = $browser->getRequest();

var_dump($request->getUri());

// Expected: string(42) "https://www.mydomain.com:443/somepage.html"

// Actual: PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TransportException: Couldn't connect to server for "http://localhost/somepage.html".
```

**Possible Solution**  
[Goutte](https://github.com/FriendsOfPHP/Goutte) solved this problem by [setting the server variables](https://github.com/FriendsOfPHP/Goutte/blob/v3.3.0/Goutte/Client.php#L58) to the values provided by the client. Perhaps a similar approach can be taken with the HttpBrowser.

**Comment by nicolas-grekas** [comment]
As explained in the linked PR, BrowserKit accepts only absolute URLs.
