### ISSUE TITLE
SF 5.0.*: make:entity command uses deprecated ManagerRegistry class

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#35180]
**Symfony version(s) affected**: 5.0.2

**Description**  
I created a new project with the symfony binary. If i type php bin/console make:entity Foo to the CLI, a repository is created together with the entity class (as expected). I noticed in the generated repository class the deprecated argument for  a Doctrine\Common\Persistence\ManagerRegistry instance. The ManagerRegistry class is deprecated since doctrine/persistence 1.3 and will be removed in 2.0. Why is SF5 making use of that?

**How to reproduce**  
* Create a new SF5 application
* php bin/console make:entity Foo
* symfony serve
* see deprecation notices

**Possible Solution**  
Use \Doctrine\Persistence\ManagerRegistry instead.

This bug may be related to #34981 but does not help.

**Comment by ro0NL** [comment]
see https://github.com/symfony/maker-bundle/pull/524 :)

**Comment by dsentker** [comment]
Thank you, the referenced issue is well written and also placed in the correct repository. My issue can then be closed.

**Comment by ro0NL** [comment]
@dsentker you should be able to close your own issues :thinking:
