### ISSUE TITLE
[FrameworkBundle] AbstractController getUser() Phpdocs

### ISSUE THREAD

**Issue by natewiebe13** [symfony/symfony#35185]
**Symfony version(s) affected**: 5.0.*

**Description**  
The phpdocs for `getUser()` in `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` state that it returns `UserInterface`. `UserInterface` is not imported or uses a FQN, so it appears to return `Symfony\Bundle\FrameworkBundle\Controller\UserInterface` which doesn't exist.

**How to reproduce**  
Check out Symfony 5.0.*

**Possible Solution**  
Either use FQN in phpdocs or add use statement for `Symfony\Component\Security\Core\User\UserInterface`

**Comment by derrabus** [comment]
Status: Reviewed
