### ISSUE TITLE
[Workflow] Hide internal services

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#35197]
Looking at `bin/console debug:container`, there's a lot of noise.

In general im curious if we can prepend service IDs with a dot in 5.0, but im not sure if it involves any BC breaks (or if we care for these services), hence an issue for now.

Example:

```
  state_machine.abstract                  Symfony\Component\Workflow\StateMachine
  state_machine.some                      Symfony\Component\Workflow\StateMachine
  state_machine.some.definition           Symfony\Component\Workflow\Definition 
  state_machine.some.listener.audit_trail Symfony\Component\Workflow\EventListener\AuditTrailListener
  state_machine.some.transition.0         Symfony\Component\Workflow\Transition
```

Having multiple state machines (`some` is a single example), the noise is N*N.

**Comment by lyrixx** [comment]
Good idea @ro0NL 

Is it a BC break to rename some internal / not documented services ? 
If it's not, i'll do the PR

**Comment by ro0NL** [comment]
Alternatively, we can do it by the book:

rename `state_machine.some.transition.0` to `.state_machine.some.transition.0`
add a deprecated alias `state_machine.some.transition.0`

**Comment by fabpot** [comment]
I would not consider this as a BC break. I think it can be done on master without deprecations.

**Comment by lyrixx** [comment]
okay, I will do it :+1:

**Comment by ro0NL** [comment]
i tend to agree, but im not sure what to do whenever a report comes in about broken references/compiler passes etc.

raises the question; from a vendor perspective, can we assume dot-prefixed services BC free, thus internal? cc @nicolas-grekas was it designed with such rules in mind?
