### ISSUE TITLE
[CssSelector] Simple selector fails

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#35191]
**Symfony version(s) affected**: 4.3.9
**Description**  

The assertion
```
$this->assertSelectorTextSame('th', 'Brutto', $this->client->getResponse()->getContent());
```
fails for an input of e.g.
```
....</tr>
		<tr>
		<th>Brutto</th>
		<td>
			Bla .....
```
Obviously this should not fail.

However, if I restrict the assertion with a class like 
```
$this->assertSelectorTextSame('th.test', 'Brutto', $this->client->getResponse()->getContent());
```
and add this class accordingly
```
....</tr>
		<tr>
		<th class="test">Brutto</th>
		<td>
			Bla .....
```
then it works as I'd expect.

**Comment by xabbuh** [comment]
What is the failure message that you get? Are you sure there aren't any other `th` elements?

**Comment by flaushi** [comment]
The message is just ` Failed asserting that Symfony\Component\DomCrawler\Crawler Object ... matches selector "th" and has a node matching selector "th" with content "Brutto".

Did I maybe understand wrongly, that this assertion does not search all elements matching this selector (all th's), and check if at least one of them matches the search text? 

In this case, the [docs](https://symfony.com/doc/current/testing/functional_tests_assertions.html) are confusing. I think I understand the example now, the important fact is that the exemplary `html` element is always unique...

**Comment by flaushi** [comment]
So, if I want to assert that at least one `th` has a certain text, I will have to loop over `$crawler->filter('th')`?

**Comment by xabbuh** [comment]
@flaushi Can you open an issue in the documentation repository so that we can improve the docs about it? Thank you!
