### ISSUE TITLE
.gitignore and bin

### ISSUE THREAD

**Issue by guenneguezt** [symfony/symfony#35199]
Why the default .gitignore doesn't exclude the bin directory ?

Thanks
Thomas

**Comment by derrabus** [comment]
Why should it?

**Comment by guenneguezt** [comment]
If I have anderstand, this folder contain the console binary.
So when you commit an application developped with symfony, it's not a good idea to comit this directory on the github repository.

**Comment by derrabus** [comment]
Yes, please commit your `bin/console`. It should be part of the repository.

**Comment by xabbuh** [comment]
As Alexander explained. The `console` file is part of your application and should be committed to the git repository. Thus there is nothing to be changed here.

**Comment by domdetre** [comment]
If you install symfony/phpunit-bridge that creates a phpunit binary in the bin folder. I'm sure that the phpunit binary is NOT part of the application.

**Comment by domdetre** [comment]
Also if you do composer install it will recreate the console and any other binaries, just like it does populate the vendor library. so it feels like the original question is still valid. 

Moreover I would say the whole vendor folder is part of the application, it would not run without it, still we don't commit that folder at all.

**Comment by xabbuh** [comment]
You can modify the files in the `bin` directory to adapt them in a way that they fit your needs. They will not be overwritten automatically if you don't ask for that. But you will never want to modify the files in the `vendor` directory.

**Comment by domdetre** [comment]
Aah, I see your point and that makes sense, thanks!
