### ISSUE TITLE
Impossible to write test for forms using type guessing

### ISSUE THREAD

**Issue by TomaszGasior** [symfony/symfony#35202]
**Symfony version(s) affected**:  4.4.1

# Description

I want to write smoke test for all of my forms. I want to just test whether they are building. Basically something like:

```
class BasicFormsTest extends TypeTestCase
{
    /**
     * @dataProvider formTypesProvider
     * @doesNotPerformAssertions
     */
    public function testBuildForms(string $formClass): void
    {
        $this->factory->create($formClass);
    }

    public function formTypesProvider(): iterable
    {
        yield [FirstExampleType::class];
        yield [SecondExampleType::class];
        yield [ThirdExampleType::class];
        yield [NextExampleType::class];
        yield [FooExampleType::class];
        yield [BarExampleType::class];
        yield [BazExampleType::class];
    }
}
```

The problem is I use type guessing in my form definitions (specifically: only default type guessers). Of course Form's `TypeTestCase` provides `getTypeGuessers()` mechanism but to make it actually working I need to instantiate type guesser class (or type extentions providing that type guesser in real code) with **real**, not mocked dependencies. To achieve this I need to get the whole container to satisfy that dependencies. It's possible using `KernelTestCase` from FrameworkBundle (in reality — `WebTestCase`). The main problem is: I **cannot** inherit from both  `WebTestCase` and `TypeTestCase` since multiple inheritance does not exist in PHP.

To check whether this mess makes any sense, I created this workaround. Well, my eyes hurt when I'm reading it too but it works.

```
class BasicFormsTest extends TypeTestCase
{
    /**
     * Terrible hack.
     */
    private function getContainer()
    {
        $kernelTestCase = new class extends KernelTestCase
        {
            public function getContainer()
            {
                self::bootKernel();

                return self::$container;
            }
        };

        return $kernelTestCase->getContainer();
    }

    protected function getExtensions(): array
    {
        $container = $this->getContainer();

        return [
            new DoctrineOrmExtension($container->get(ManagerRegistry::class)),
            new ValidatorExtension($container->get(ValidatorInterface::class)),
        ];
    }

    /**
     * @dataProvider formTypesProvider
     * @doesNotPerformAssertions
     */
    public function testBuildForms(string $formClass): void
    {
        $this->factory->create($formClass);
    }

    public function formTypesProvider(): iterable
    {
        yield [FirstExampleType::class];
        yield [SecondExampleType::class];
        yield [ThirdExampleType::class];
        yield [NextExampleType::class];
        yield [FooExampleType::class];
        yield [BarExampleType::class];
        yield [BazExampleType::class];
    }
}
```

# Possible Solution

Create trait for `KernelTestCase` functionality. Or for `TypeTestCase`. Or for both?

**Comment by derrabus** [comment]
Why don‘t you build your `BasicFormsTest` against `KernelTestCase`? What do you need `TypeTestCase` for in this specific context?

**Comment by TomaszGasior** [comment]
@derrabus To use form factory. Yep, I can cheat and just copy paste code which creates factory or just get it from container  but TypeTestCase provides useful mechanism for settings types, extensions, type guessers etc. It seems to me it's useful to be able to use both classes at the same time.

**Comment by xabbuh** [comment]
If your form types heavily depend on services managed by the Symfony DI container, I would not use the `TypeTestCase` but rather use the `form.factory` service and use that to get an instance of the concrete form you try to test.

The `TypeTestCase` is rather useful for writing simple unit tests for form types that do not need a complex setup.

**Comment by TomaszGasior** [comment]
@xabbuh Agreed completely. I just forgot to close the issue. Sorry! For other readers, I use this code now:

```
