### ISSUE TITLE
[CONTRACT] Add user contract

### ISSUE THREAD

**Issue by core23** [symfony/symfony#35237]
**Description**  
Symfony does not provide a good solution for custom user providers and there were big problems with the FOSUserBundle in the past, which made the upgrade process really hard. There are still around [~600 projects](https://packagist.org/packages/friendsofsymfony/user-bundle/dependents) which rely on the unmaintained version.

**Example**  
I suggest to create a new user contract repository which contains all interfaces that are needed for user management (e.g. UserInterface, UserProviderInterface, ...).

**Comment by linaori** [comment]
I don't think this will solve any problems. These interfaces are only used and required by the Security component. What would moving these to the contracts solve?

**Comment by fabpot** [comment]
I agree with @linaori
