### ISSUE TITLE
Long execution TraceableFirewallListener

### ISSUE THREAD

**Issue by pcholewa** [symfony/symfony#35232]
4.4.2

Hi,

I have problem with long execution of TraceableFirewallListener. Sometimes its takes 40-50 sec., but after refresh same page its ok.

**Comment by chalasr** [comment]
Hi,

I'm going to close this issue as the provided description is too broad.
Please consider creating a new issue with the bug report template properly filled, including enough context to reproduce the situation. Also, given this is about performance, you may consider providing a [blackfire profile](https://blackfire.io).

Thanks
