### ISSUE TITLE
Always Include Route Default Values

### ISSUE THREAD

**Issue by herbyxxx** [symfony/symfony#35246]
**Symfony version(s) affected**: 4.4.2 (in my case)

**Description**  
Regarding this link: [New in Symfony 4.3: Always Include Route Default Values](https://symfony.com/blog/new-in-symfony-4-3-always-include-route-default-values)

Following code given:
```
class BlogController extends AbstractController
{
    /**
     * @Route("/blog/{!page?1}", name="blog_list")
     */
    public function list($page)
    {
        //default value of $page = 1
        //url should be forced to use default value if no value is given e.g. /blog/1 not just /blog
    }
}
```
Opening following url should work, but it does not (No route found in all cases):
- /blog
- /blog/1
- /blog/2

Also if I remove the `!` making it  `@Route("/blog/{page?1}", name="blog_list")` the url is generated incorrectly (or atleast not as documented):
- /blog (works with default value = 1)
- /blog/1 (redirects to /blog - should actually be /blog/1)
- /blog/2 (works with value 2)

**How to reproduce**  
Try code above.

**Possible Solution**  
?

**Comment by xabbuh** [comment]
Same as #33224?

**Comment by herbyxxx** [comment]
@xabbuh Wups, sorry. Yes seems to be the same issue.
`@Route("/blog/{!page}", name="blog_list"), defaults={"page": 1})` seems to be the only working way atm.

**Comment by xabbuh** [comment]
Thanks for the confirmation. Let's close this as a duplicate then. :)
