### ISSUE TITLE
Deprecation warning on Symfony 4.4.* 

### ISSUE THREAD

**Issue by arturslogins** [symfony/symfony#35241]
Hello 

Running PHPUnit 8.5.1. and Symfony 4.4.  i got deprecation warning on running php unit tests. 

Other deprecation notices (1)
  1x: The "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedListFilter" class is considered final. It may change without further notice as of its next major version. You should not extend it from "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedList".

Should i ignore that? 
If i ignore this warning my pipeline fails on unittest stage 

Any help would be appreciate

**Comment by maxhelias** [comment]
It's look like an issue for PHPUnit, not Symfony

**Comment by arturslogins** [comment]
Ok i will post this issue in phpunit repo too

**Comment by ro0NL** [comment]
i think the issue needs some more details..

where does `PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedList` come from? Who's extending it actually? I cant find it in the phpunit repo :thinking: 

ultimately it may be an phpunit bridge (thus Symfony) issue, for not detecting the same-vendor correctly ...

**Comment by arturslogins** [comment]
I write in PHPUnit community, and they said that this message is not coming from sebastianbergmann/phpunit package   

https://github.com/sebastianbergmann/phpunit/issues/4002

Looks like it comes from phpunit bridge ?

**Comment by xabbuh** [comment]
Are you able to create a small example application that allows us to reproduce?

**Comment by arturslogins** [comment]
> Are you able to create a small example application that allows us to reproduce?

I will try

**Comment by xabbuh** [comment]
@arturslogins Do you have anything for us that we can look at?

**Comment by arturslogins** [comment]
> @arturslogins Do you have anything for us that we can look at?

Yes i upload project example in my repo 

https://github.com/arturslogins/unit-example

You should install on your local computer phpunit 8.5.1

Install dependencies with composer and run test 

 phpunit -v
PHPUnit 8.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /c/www/zm/unit-test-example/phpunit.xml.dist

Testing Project Test Suite
.                                                                   1 / 1 (100%)

Time: 177 ms, Memory: 12.00 MB

OK (1 test, 1 assertion)

Other deprecation notices (1)

  1x: The "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedListFilter" class is considered final. It may change without further notice as of its next major version. You should not extend it from "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedList".

**Comment by xabbuh** [comment]
I also had to install PHPUnit (`composer require --dev phpunit/phpunit`), but then tests did not run without any issues:

```
$ vendor/bin/phpunit 
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Testing Project Test Suite
.                                                                   1 / 1 (100%)

Time: 46 ms, Memory: 6.00 MB

OK (1 test, 1 assertion)
```

**Comment by xabbuh** [comment]
This might be related to how you run PHPUnit in your project. Could you debug where this deprecation is being triggered?

**Comment by arturslogins** [comment]
> I also had to install PHPUnit (`composer require --dev phpunit/phpunit`), but then tests did not run without any issues:
> 
> ```
> $ vendor/bin/phpunit 
> PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
> 
> Testing Project Test Suite
> .                                                                   1 / 1 (100%)
> 
> Time: 46 ms, Memory: 6.00 MB
> 
> OK (1 test, 1 assertion)
> ```

i installed phpunit on my local linux 

wget https://phar.phpunit.de/phpunit-8.5.1.phar
chmod +x phpunit.phar
sudo mv phpunit.phar /usr/local/bin/phpunit

**Comment by xabbuh** [comment]
I still cannot reproduce the issue. Can you please debug by what the deprecation is triggered?

**Comment by arturslogins** [comment]
My be this is answer https://github.com/myclabs/DeepCopy/issues/148

**Comment by xabbuh** [comment]
Let's close then as it seems that we cannot do anything about it then.
