### ISSUE TITLE
Warning: session_start(): Failed to decode session object. Session has been destroyed

### ISSUE THREAD

**Issue by Trunks93** [symfony/symfony#35253]
I get this error, when i want to navigate on another page of my projet symfony 4.3.9

**Comment by Trunks93** [comment]
how to solve this ?

**Comment by NikoGrano** [comment]
Are you saving anything into the session manually. Like a Entity?

**Comment by Trunks93** [comment]
No I don't save something, just the current user. when the user is authenticated, he is redirected to the backend of the application and after that, if i click anywhere i get that error.

**Comment by linaori** [comment]
Please use one of the support channels for support questions: https://symfony.com/support

Thanks!

**Comment by Trunks93** [comment]
thank you @linaori

**Comment by javiereguiluz** [comment]
@Trunks93 let's close this support question and hopefully you'll get some answers in Symfony's Slack. Thanks.
