### ISSUE TITLE
[DoctrineBridge] UniqueEntityValidator for a given $entityClass 

### ISSUE THREAD

**Issue by scroach** [symfony/symfony#35279]
**Symfony version(s) affected**: symfony/doctrine-bridge 4.3.6

**Description**  
I am currently trying to implement an API in symfony and wanted to use the `UniqueEntityValidator` in a DTO.
`UniqueEntity` offers the ability to specify `$entityClass` and `$fields` therefore I thought it would be possible to validate if an entity of type `User` exists for an incoming `UserDTO`

The `UniqueEntityValidator` fetches Classmetadata for the currently validated entity and ignores the specified classname, but later on gets the repository for the specified classname.

https://github.com/symfony/doctrine-bridge/blob/v4.4.2/Validator/Constraints/UniqueEntityValidator.php#L78

https://github.com/symfony/doctrine-bridge/blob/v4.4.2/Validator/Constraints/UniqueEntityValidator.php#L125

Am I missing something or is this just a bug that has been overseen?

**Possible Solution**  
Fetch all metadata and repository for the specified entity class.

**Example**  

```php
/**
 * Class UserRegistrationDTO
 *
 * @package App\DTO
 * @UniqueEntity(entityClass="App\Entity\User", fields={"email"})
 */
class UserRegistrationDTO
{

    /**
     * @var string
     * @Assert\Length(min="5")
     */
    public $username;

    /**
     * @Assert\Email
     */
    public $email;
}
```

**Comment by dmaicher** [comment]
This seems to be a duplicate of https://github.com/symfony/symfony/issues/22592

**Comment by scroach** [comment]
You're totally right - sorry, I somehow did not find that issue before.
At least I'm not the only one being confused or thinking it should work.
