### ISSUE TITLE
[Form] `getClickedButton()` missing in FormInterface returned by builder

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#35277]
**Symfony version(s) affected**: 4.4

phpstan reports:
> Call to an undefined method Symfony\Component\Form\FormInterface::getClickedButton()

According to @althaus this is because `getClickedButton()` is not included in the FormInterface returned by the builder, see https://github.com/phpstan/phpstan-symfony/issues/12#issuecomment-479493557

**Comment by ThomasLandauer** [comment]
And when trying it the other way as explained at https://symfony.com/doc/current/form/multiple_buttons.html

```php
$form->get('saveAndAdd')->isClicked()
```
... I'm getting:

> Call to an undefined method Symfony\Component\Form\FormInterface::isClicked()

**Comment by xabbuh** [comment]
`getClickedButton()` is not part of the interface as it wouldn't make much sense for a `Button` implementation which also implements the `FormInterface`. Likewise `isClicked()` is not part of the interface as it is only useful for buttons.

If you want to stop PHPStan complaining about it without adding it to the baseline, you can do something like this:

```php
if ($form instanceof Form) {
    $button = $form->getClickedButton();
}

// or

/** @var Form $form */
$button = $form->getClickedButton();
```

I don't think there is anything we can do in the Form component about this.

**Comment by ro0NL** [comment]
at least SF anticipates each form implementation may implement this:

https://github.com/symfony/symfony/blob/80cc6bda60cfe68c5399ac248b7a5fcf894e6de0/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L167-L169

which to me is a hint it's missing in some contract, somewhere

**Comment by xabbuh** [comment]
@ro0NL Technically there could be other implementations of the `FormInterface`. So the `FormValidator` takes the safe path and performs this check first to prevent type errors even if it's probably always `true` in a typical Symfony application.

I am closing as explained in https://github.com/symfony/symfony/issues/35277#issuecomment-572540892.
