### ISSUE TITLE
Incorrect throw of LogicException in SwitchUserListener

### ISSUE THREAD

**Issue by wolf-decix** [symfony/symfony#35283]
**Symfony version(s) affected**: 4.2.12

**Description**  
Incorrect throw of LogicException in [SwitchUserListener.php#L144](https://github.com/symfony/security-http/blob/v4.2.12/Firewall/SwitchUserListener.php#L144). 
It seems like this line was left over from debugging in development or so, before it was committed: [Commit](https://github.com/symfony/security-http/commit/8024422eeaca7b0b33ce2900b2f75e20259de7aa?diff=unified)

**How to reproduce**  
Implement and perform a switch to another user. 

**Possible Solution**  
Get rid of line 144 - as it has really no business there - like already done in 4.3: 
[SwitchUserListener.php#L157-L168](https://github.com/symfony/security-http/blob/4.3/Firewall/SwitchUserListener.php#L157-L168)

**Additional context**  
As a workaround you will have to downgrade `symfony/security-bundle` to 4.2.11.

**Comment by nicolas-grekas** [comment]
4.2 is not maintained anymore, you need to move to 4.3 (or better: 4.4 as 4.3 is going to be EOLed in 2 weeks also). Note that downgrading to 4.2.11 would expose your server to a known vulnerability...
I'm thus closing, thanks for reporting.
