### ISSUE TITLE
[Form] Many ID attributes are generated for a form element

### ISSUE THREAD

**Issue by Russellmd** [symfony/symfony#35287]
**Symfony version(s) affected**: 4 - 5

**Description**  
Symfony Forms generate elements with 2 id

**How to reproduce**  
Create a form object. For an element and/or the form set id attribute
```
$builder
            ->add('field_name', TextType::class, [
		'attr' => ['id' => 'myTestId']
	]) ;
```
```
$resolver->setDefaults([
            // Configure your form options here
		'attr' => ['id' => 'myTestFormId']
        ]);
```
Use form in twig view like:
```
{{form(testForm)}}
```
The result (taking from browse "view source"):
```
<html>
  <body>
    <form name="test_form" method="post" id="myTestFormId">
      <div id="test_form" id="myTestFormId">  <--- 2 IDs
        <div>
          <label for="test_form_field_name" class="required">Field name</label>
          <input type="text" id="test_form_field_name" name="test_form[field_name]" 
required="required" id="myTestId" />     <--- 2 IDs
        </div>
      </div>
    </form>
  </body>
</html>
```

**Comment by xabbuh** [comment]
You might be interested in reading the discussion at #20965.

**Comment by Russellmd** [comment]
Thank you @xabbuh,

I took a look to your suggestion, even it's not a good idea to change generated ID at this level, however having 2 IDs is also not good (at least for w3 validation).

I'm not well-known with all details for forms, but, for my case, I decided to override some blocks in this way:
```
{%- block widget_attributes -%}
    {%- if attr['id'] is defined and attr['id'] is not empty %}id="{{ attr['id'] }}"{% else %}id="{{ id }}"{% endif -%} 
    {% set attr = attr|merge({ 'id': false }) %} name="{{ full_name }}"
    {%- if disabled %} disabled="disabled"{% endif -%}
    {%- if required %} required="required"{% endif -%}
    {{ block('attributes') }}
{%- endblock widget_attributes -%}

{%- block widget_container_attributes -%}
    {%- if id is not empty %}{% if attr['id'] is defined and attr['id'] is not empty and attr['id'] is same as(id) %}id="{{id~'_'~attr['id']}}"{% else %}id="{{id}}"{% endif %}{% endif -%}
    {%- set attr = attr|merge({ 'id': false }) -%}
    {{ block('attributes') }}
{%- endblock widget_container_attributes -%}

{%- block button_attributes -%}
    {%- if attr['id'] is defined and attr['id'] is not empty %}id="{{ attr['id'] }}"{% else %}id="{{ id }}"{% endif -%}
    {% set attr = attr|merge({ 'id': false }) %} name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif -%}
    {{ block('attributes') }}
{%- endblock button_attributes -%}
```

**Comment by ro0NL** [comment]
> however having 2 IDs is also not good (

so, why arent you removing yours then from the attributes? Why does it need to be custom?

Ultimately SF manages the ID attribute, so as per

> We should also add a notice to say that the `id` attribute cannot be set with this option. https://github.com/symfony/symfony-docs/issues/6462#issuecomment-267761647

should we start deprecating doing so?

**Comment by xabbuh** [comment]
Not using custom ids is the way to go. If, for some reason, you really need to use your own ids, you will have to overwrite the related rendering part in a custom form theme to not render the automatically generated id.
