### ISSUE TITLE
Form "PercentType" parameter "scale" inconsistency with "NumberType"

### ISSUE THREAD

**Issue by emmanuelballery** [symfony/symfony#35296]
**Description**

Parameter `scale` of `PercentType` is a bit confusing when you know how it works for the `NumberType` one:

- `NumberType` will round the submitted value, meaning the model will be rounded too; What's saved and what's shown in the view is identical.
- `PercentType` will round the view only, but will save the model with all the decimals sent.

**Example**

Consider this form:

```php
$form = $this
    ->createFormBuilder()
    ->add('number', NumberType::class, ['scale' => 2])
    ->add('percent', PercentType::class, ['type' => 'integer', 'scale' => 2])
    ->getForm();
```

Then submit values with more decimals than the scale is set to and dump the model:

![image](https://user-images.githubusercontent.com/1687685/72141437-260fcc00-3393-11ea-86aa-c2d364697977.png)

Something like:

```php
$form->submit(['number' => 1.234, 'percent' => 1.234]);
dump($form->getData());
```

The `NumberType` will actually round the model. The `PercentType` one will ignore this scale and keep every decimals in the model.

![image](https://user-images.githubusercontent.com/1687685/72140576-5a828880-3391-11ea-9f60-3b22dddc570b.png)

But the view will then show:

![image](https://user-images.githubusercontent.com/1687685/72141576-68390d80-3393-11ea-8815-faf47699ccb9.png)

Leading to something strange, in my opinion.

Having the same behaviour for both would be great, or changing the name of this parameter in `PercentType` to make this difference clearer like `view_scale` for example.

Thanks!

**Comment by cybernet** [comment]
👍

**Comment by VincentLanglet** [comment]
Is there a reason for keeping the different behaviour ?
I expect the value to be rounded too for the PercentType.

**Comment by emmanuelballery** [comment]
I wanted to add that the `scale` parameter is required in `PercentType` (in `PercentToLocalizedStringTransformer` you will see that `$scale` is set to `0` if null is provided). But in `NumberType`, it's fine to ignore the `scale` and `NumberToLocalizedStringTransformer` will ignore the rounding process). There is no reason to require a scale, sometimes it's just not necessary.

**Comment by VincentLanglet** [comment]
It doesn't seem clear to me in the documentation that the different rounding behaviour are expected. 
https://symfony.com/doc/current/reference/forms/types/percent.html#scale
https://symfony.com/doc/current/reference/forms/types/number.html#scale

**Comment by VincentLanglet** [comment]
@emmanuelballery I started a PR here: https://github.com/symfony/symfony/pull/35729
