### ISSUE TITLE
[Form/Constraint] Email allows multiple inputs separated by comma

### ISSUE THREAD

**Issue by gsirin** [symfony/symfony#35307]
**Affected version**
Symfony 4.4.2

**Description**
Using the Email constraint allows the visitor to entry multiple email addresses separated by a comma. 
(e.g. "_email1@mail.com, email2@mail.com_" is a valid input)

```
->add('additional_email', EmailType::class, array(
		'label' => 'weitere E-Mail',
		'constraints' => array(
			new Email()
		)
	)
)
```

I think this behaviour is kind of unexpected? Or do I miss something to prevent this?

**Comment by allcode** [comment]
The email constraint supports [three modes](https://symfony.com/doc/4.4/reference/constraints/Email.html#mode): loose, html5 and strict. This mode is used by the email validator, which by default uses the loose mode.
The loose mode validates the email string with regular expression `/^.+\@\S+\.\S+$/`, which allows any character before the last @.
If you want more strict validation, you should use the html5 mode, which validates the string using `/^[a-zA-Z0-9.!#$%&'*+\\/=?^_``{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/`.
Strict mode requires [egulias/email-validator](https://github.com/egulias/EmailValidator), which provides even more in-depth validation options.

I do agree that using loose mode by default is a rather strange choice. I guess in the end it does not matter what pattern you use, you'll always have to send an email to actually confirm the address is valid.

**Comment by xabbuh** [comment]
As @allcode explained you can change to a more strict mode if you need to. Therefore I am closing here as there is no bug. Thank you for understanding.

**Comment by gsirin** [comment]
Validating emails has never been easy. Thanks for getting back on me on this one. I will use one of the other both modes but I encourage you to think about changing the default behaviour because this is really nobody expecting. I think it's more an feature to input multiple adresses.
