### ISSUE TITLE
[Intl] Intl does not return region specific language

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#35309]
**Symfony version(s) affected**: >= 4.4.0 (4.3.9 works)

**Description**  

The `Intl::getLanguageBundle()->getLanguageName('de, 'AT', 'en');` does not longer return the region specific language. Expected `Austrian German` got `German` same for `en`, `GB` expect `British English` got `English`.

also `getLanguages` seems not longer contain `Austrian German` and the other region specific values.

**How to reproduce**  

```php
Intl::getLanguageBundle()->getLanguageName('de, 'AT', 'en'); // should return `Austrian German` does return `German`
```

```php
Intl::getLanguageBundle()->getLanguages('en'); // does not longer contain `Austrian German`
```

**Additional context**  

Think it has something todo with @ro0NL changes in https://github.com/symfony/symfony/pull/33148 I always landing in the [exception case](https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/ResourceBundle/LanguageBundle.php#L50-L51) with

> Couldn't read the indices [Names][en_GB] for the locale "en" in "sulu/web-twig/vendor/symfony/intl/Resources/data/languages". The indices also couldn't be found for the fallback locale(s) "root".

**Comment by ro0NL** [comment]
Hi @alexander-schranz, that's correct and intended from my side :)

We excluded locales (or localized languages / or region specific languages) from the dedicated list of "language codes", which is ISO standard and shouldnt include locales but only pure language codes.

From the example code, it seems you are using the deprecated API in 4.4. Indeed, this lead to the exception case as both the old and new API read from the same data source.

For the new API, localized language names can be obtained using `Languages::getName()`. See docs:

https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/Languages.php#L53-L59

:}

**Comment by ro0NL** [comment]
Alternatively, to fix the legacy API in 4.4, we could check the `LocalizedNames` indice here:

https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/Data/Provider/LanguageDataProvider.php#L55

so similar like the new API in 4.4:

https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/Languages.php#L59-L74

i agree we effectively broke the old API as of 4.4, as these indices became unavailable:

https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/ResourceBundle/LanguageBundle.php#L45-L52

but im not sure sure it's worth fixing :)

**Comment by alexander-schranz** [comment]
@ro0NL Thank you for your fast response.

> but im not sure sure it's worth fixing :)

Think if I did understand the code correctly I can replace `getLanguage` with `getLocale` and `LanguageType` form type with `LocaleType` and it should be fine. So from my case if I'm the only running into this issue we can close it and mark it as wontfix.

**Comment by ro0NL** [comment]
language codes and locales are 2 independent lists, that's why we excluded locales from language codes in  #33148

you should replace the old API with the new API as of 4.3, and then all is good :)

**Comment by ro0NL** [comment]
>  I always landing in the exception case with

@alexander-schranz how did you get the exception actually?

> // does not longer contain `Austrian German`

this is a bugfix :)

**Comment by alexander-schranz** [comment]
> how did you get the exception actually?

@ro0NL its catched so don't worry the exception is not thrown out just did debug and saw that it always landed in the catched case.

https://github.com/symfony/symfony/blob/7e1a7b753e57aa381366e07948a6d680c72f0b95/src/Symfony/Component/Intl/ResourceBundle/LanguageBundle.php#L50-L51

**Comment by ro0NL** [comment]
ah, i see what you mean now :) i think we can close then. The bugfix/change was intended.

**Comment by alexander-schranz** [comment]
@ro0NL sure. Thank you for the clarification.
