### ISSUE TITLE
Is it possible to update version of ocramius/proxy-manager?

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony#35300]
**Description**  
Currently, when you have `symfony/proxy-manager-bridge` 4.4.2 in composer.json, composer will install `ocramius/proxy-manager`  2.2.3 which has dependency on  `zendframework/zend-code (^3.3.0)`. 
Currently composer reports package `zendframework/zend-code` as abandoned, with possible replacement. At the same time `ocramius/proxy-manager` has new version without abandoned dependencies.
It is possible to update `symfony/proxy-manager-bridge` requirements (in 4.4 branch and may be in branch 3.4) so we could install version `ocramius/proxy-manager` 2.6.0?

**Example**  
Now composer output `Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.`

**Comment by Ocramius** [comment]
`symfony/proxy-manager-bridge` already allows usage of `ocramius/proxy-manager:2.6.0`:

https://github.com/symfony/symfony/blob/37a886354a4619c3994f9cd75a60f7cffe615403/src/Symfony/Bridge/ProxyManager/composer.json#L21

Besides, relying on `zendframework/*` packages is perfectly fine for now: they won't be un-published, but you will need to migrate away if a security issue arises.
