### ISSUE TITLE
flock in Kernel.php locks up waiting - NFS

### ISSUE THREAD

**Issue by mhitza** [symfony/symfony#35312]
**Symfony version(s) affected**: dev-master

**Description**  
During the execution of `./bin/console --ansi cache:clear` the process freezes up on Kernel.php:454

**How to reproduce**  
Boot up a vagrant machine with a NFS shared folder and run `composer install` or `./bin/console --ansi cache:clear` directly.

**Possible Solution**  
Possibly revert 0b5b3ed7f9b770dbf33735aa36bb1b0bdf2c9b1c

**Additional context**  
I've looked over PR #33703 and not sure how that fix is supposed to work but manually patching Kernel.php locally with similar changes didn't work for me, as it locks up in the flock call, in any lock mode.

**Comment by mhitza** [comment]
@nicolas-grekas pinging you as I've seen you fixed the other NFS related issue #33392

**Comment by nicolas-grekas** [comment]
Can you try https://github.com/symfony/symfony/pull/35243?
If that doesn't fix the issue, we'll need more details. "It doesn't work" is not enough for understanding what happens. Please try to debug the situation and report as much observations as possible.

**Comment by mhitza** [comment]
I'm on the latest version, commit 0adcc6ada48edff331fed1d11db5b18458cb9244 for [symfony/http-kernel](https://github.com/symfony/http-kernel/commits/master) which includes changes in that PR.

I would hope that I've provided more information than "it doesn't work", but maybe phrased it poorly. The Kernel.php just locks up when `flock` is called in [Kernel.php:454](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L454) on the NFS shared folder. And waits until the PHP timeout is reached.

I've created symlinks from var/cache and var/log to locations outside the NFS shared path to avoid this for now.

**Comment by nicolas-grekas** [comment]
> `flock($lock, LOCK_EX | LOCK_NB, $wouldBlock);`

The `LOCK_NB` here means this should not happen. Can you reproduce the lock on a simple standalone usage of the function? Does anyone else have the issue? Is it a documented bug with NFS?

Moving `var/*` outside of the NFS folder is a very nice idea regardless, you'll get much better perf with a local folder.

**Comment by mhitza** [comment]
I'm able to replicate it easily with the following files (saved as `lock.php` on my end):
```
<?php

$fh = fopen("./lock-me.txt", "w");
echo "before lock\n";
flock($fh, LOCK_EX | LOCK_NB, $wouldBlock);
echo "after lock\n";
```

And the following Vagrantfile (tried a Debian VM as well, all the same):
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.60.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["vers=3,tcp"]
  
  config.vm.provision "shell", run: "always", inline: "sudo yum install -y php"
end
```

Then
```
cd /vagrant
touch lock-me.txt
php lock.php
```

It's documented that flock is not supported on NFS (but not how it will respond to a flock operation), and other mechanisms I've read about, like `fcntl(F_SET_LK)` are available in PHP just via the [dio extensions](https://www.php.net/manual/en/book.dio.php). Which would require a separate package install on most (if not all) Linux distributions.

Information I have on this topic is from this page https://web.archive.org/web/20190210072444/http://0pointer.de/blog/projects/locking.html

**Comment by nicolas-grekas** [comment]
Borrowed from https://github.com/thephpleague/flysystem/issues/445#issuecomment-78160189

If I change the mount options to `rw,vers=3,tcp,fsc`, it fixes the issue, isn't it?

**Comment by nicolas-grekas** [comment]
Closing as this is a miss configuration of the NFS mount point.
Maybe something to document btw? @mhitza please open a doc issue/PR if you think so.

**Comment by lonalore** [comment]
> Borrowed from [thephpleague/flysystem#445 (comment)](https://github.com/thephpleague/flysystem/issues/445#issuecomment-78160189)
> 
> If I change the mount options to `rw,vers=3,tcp,fsc`, it fixes the issue, isn't it?

I had the same issue, and this fixed it! Thank you!

**Comment by jderusse** [comment]
@lonalore would you mind to open a PR on the documentation with this TIP?
