### ISSUE TITLE
[Mailer][MailgunApiTransport]: Unable to send email with prepared on Mailgun side template.

### ISSUE THREAD

**Issue by Metalrex100** [symfony/symfony#35329]
**Symfony version(s) affected**: 4.4

**Description**  
Mailgun API allows you to prepare email HTML templates on it's side and later send an email with template name and template variables only (no `text` or `html` parameters needed when `template` parameter specified)
Link to Mailgun API docs: https://documentation.mailgun.com/en/latest/user_manual.html#templates

Currently `MailgunApiTransport` does not support this feature, because `getPayload()` method does not contain `template` param in `$payload` array and `Mime\Email` class does not have `template` field eather. 
link to `getPayload()` method: https://github.com/symfony/mailgun-mailer/blob/4.4/Transport/MailgunApiTransport.php#L79

There is also impossible to specify `template` param with headers, because all headers which are not in `$headersToBypass` array will be concatenated with `h:` prefix. Instead of `template` header we will get `h:template` header, which will be ignored by Mailgun API.

**Possible Solution**  
1. Add `template` field to Mime\Email class or extend it with some specific Email class for emails with prepared templates. (But with child class will be needed hacks to pass Mime\Email validation, e.g. to change in constructor `text` field to empty string)
2. Add condition to Email object validation to ignore null `text` and `html` fields if `template` field != null. (Otherwise you will have to specify `text` or `html` field with empty string, which is quite wrong). 
link to `Mime\Email` validation method: https://github.com/symfony/mime/blob/master/Email.php#L402
3.  In `getPayload()` method add `template` param to `$payload` array if it is not equal to null.

I can prepare a pull request if my solution is ok for you.

P.S. For those who faced same problem there is a possible way to send email with prepared template:
```
$email = new Email();

$email->to('to@example.com');
$email->from('from@example.com');
$email->subject('subject');
$email->html('any_symbol'); //otherwise Mailgun API will return error that both `text` and `html` fields are empty

$headers = $email->getHeaders();
$headers->addTextHeader('X-Mailgun-Template-Name', 'your_template_name');
$headers->addTextHeader('X-Mailgun-Variables', json_encode(['name' => 'value']));

$mailer->send($email);
```

**Comment by fabpot** [comment]
The goal of the Mailer component is to allow one to create their own Email messages (via Mime) and send them in an agnostic way. So, "advanced" features of some providers are not supported and will never be. I think this is one of them. Considering that there is even a way to workaround it, I think we can close this issue. Thanks for your understanding.

**Comment by Metalrex100** [comment]
@fabpot thank you for reply.
I agree that Mailer and Mime components should have some common behavior for all email providers.

But there are also components with specific for each provider transports (e.g. `mailgun-mailer`).
Each transport knows about it's provider specifics. 
For example `MailgunApiTransport::getPayload` method adds additional Mailgun specific symbols to email headers.
Probably such feature as `template` parameter could be implemented on transport level?

Such code may could be added to `MailgunApiTransport::getPayload` method to support `prepared templates` feature:
```
if ($email->getHeaders()->has('template')) {
    $payload['template'] = $email->getHeaders()->get('template')->getBodyAsString();
}
```

**Comment by Orkin** [comment]
Hi @fabpot,

I completely understand your point to get an agnostic email system but maybe it's possible to go further and find a way to support both without the need to break the actual purpose.

If we would like to use the mailer component with a third party integration like mailgun (but it's the same for many other intergration, for me it's postmark). The way to send email must stay agnostic but we could find a workaround. For me there is two way to do that : 
- the first one is to add a new property on Email object to allow to define template like `textBody` or `htmlBody` with this it could be really easy to implement external template feature without breaking anything and without hard dependencies. It's stay agnostic but I'm not sure that the Email object had to manage that purpose
- the second one is to play with headers like @Metalrex100 say. We can use headers to set if we would like to use template maybe with header name like `with-template` and we use the properties `textBody` and/or `htmlBody` to provide template name/id/alias. With this the Email object don't need to be modified and headers stay abstract and are only used by the provider integration. This is not the most elegant solution but it can be a way to go further and find something that can match to the most case.

The main motivation behind the usage of external template is that templated email can be managed by other team that don't need to know how the application works (technically). The product team know which variables that are available for a specific template and can work on design on their side. The other point is in case of API development. We don't need the usage of twig or templating library and if we would like to send templated email without the usage of external templates we are forced to use twig to render those emails.

What do you think about that ? Do you think it can be possible to discuss about that to find the best way to do it. I think it can be a really good feature to support that. This is a common usage and it could be harm to have to do without this component for this reason.

Thanks for ready and sorry for my bad english 😉
