### ISSUE TITLE
Exception when getting swiftmailer.mailer  using container.

### ISSUE THREAD

**Issue by papnoisanjeev** [symfony/symfony#35331]
Getting exception when getting swiftmailer.mailer  using container.

**The "swiftmailer.mailer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead**

swiftmailer.mailer is already public.

**Comment by derrabus** [comment]
> swiftmailer.mailer is already public.

By default, it‘s not. What versions of Symfony and SwiftmailerBundle are you using? How did you make `swiftmailer.mailer` public?

**Comment by papnoisanjeev** [comment]
@derrabus 
We are using Symfony 4.3.8.

We have checked by **php bin/console debug:container** and this service was showing
so we come to know that it is public.

Please let us know how to make this public if it is not.

**Comment by xabbuh** [comment]
The SwiftmailerBundle is not part of this repository. Please consider to open a new issue [over there](https://github.com/symfony/swiftmailer-bundle) if you think that you discovered a bug. Thank you for understanding.

**Comment by nyneplus** [comment]
@papnoisanjeev ever found a solution? 
When i edit EmailService.php to use the alias directly by name:
` $mailer = $this->container->get('swiftmailer.mailer.mailer_4650');`
 it works but by class i get this error.

UPDATE
Found it! never name the mailer id default... If it is default it is cleared because internally it is used too...

**Comment by papnoisanjeev** [comment]
@nyneplus 

Actually in our case this issue was coming due to password contains  !   and after changing password and use a simple one it started working.

Also we finally we encrypted the password and decrypted it later resolved the issue and accept each and every password for swiftmailer may be it is coming while parsing specials characters if present in password.
