### ISSUE TITLE
Lock Component - multiple host DSN

### ISSUE THREAD

**Issue by stajnert** [symfony/symfony#35350]
Hello,

StoreFactory shouldn't check 
```
redis:\\
rediss:\\
```

because when we want to use multiple hosts we should use 
```
redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1
```

Source:
https://raw.githubusercontent.com/symfony/lock/master/Store/StoreFactory.php

**Comment by Jontsa** [comment]
I'm facing the same problem. We are already using Cache component with Redis cluster as backend but Lock component does not accept the same DSN syntax as Cache.

**Symfony version(s) affected**: 4.4, 5.0

**Description**

`Symfony\Component\Lock\Store\StoreFactory` uses `Symfony\Component\Cache\Adapter\AbstractAdapter` to create instance of one of the available Redis classes. AbstractAdapter accepts
DSN starting with `redis:` or `rediss:` but StoreFactory requires DSN to start with `redis://` or `rediss://`.

This prevents user from defining multiple servers in single DSN when using
Redis cluster as described here https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#configure-the-connection

**How to reproduce**  


**Possible Solution**  

Update StoreFactory to accept same DSN syntax as AbstractAdapter.

**Additional context**
