### ISSUE TITLE
[DOM Crawler] decodes &shy; to a soft-hyphen-character, but should leave the crawled content intact

### ISSUE THREAD

**Issue by spackmat** [symfony/symfony#35354]
**Symfony version(s) affected**: 5.0.2

**Description**  
I am using the DOM Crawler to scrape contents from another website within our organization. That page uses the `&shy;` entity a lot (for stupid reasons that are not subject here), but the DOM crawler decodes them to a `u+000AD` codepoint, which is displayed as a `-` character in the console and my IDE, leading to odd contents like "some looo-oooo-ooo-ng words". This is a problem, because the crawled content is imported to another CMS and the codepoints are not visible (or displayed like `-`) in the editor.

**How to reproduce**  
Parse any html content with the DOM crawler containing `&shy;` entities and observe them being decoded to a `u+000AD` codepoint. The web output of `dump` restores the entity, so you have to dump to a console or write the output to a file to see the effect (see code below).

**Possible Solution**  
Invisible entities line `&shy;` should not be decoded at all (due to their special behavior). Or the crawled content should not be decoded i any way or there should be a switch to turn that off, if the raw content is needed.

I could replace all those `u+000AD` codepoints after extracting the data, but that would be just a workaround, and I assume that there are other entities that are decoded unsolicited by the crawler.

**Additional context**  
Loading HTML directly into a DOMDocument-instance leaves the `&shy;` intact:

    $doc = new DOMDocument();
    $doc->loadHTML('<html><body>Te$shy;st<br></body></html>');
    echo $doc->saveHtml();

**Comment by stof** [comment]
Are you using the HTML5 parsing in your project (which is turned on when you have `masterminds/html5` installed and your HTML has the HTML5 doctype) ? If yes, it might be an issue in the `masterminds/html5` library.

**Comment by spackmat** [comment]
@stof it happens both with and without the html5 library. I looked through the code of Crawler.php while I was sitting in a meeting, but couldn't find the code reaponsible for the decoding of entities so far.

**Comment by spackmat** [comment]
The page I crawl uses a xhtml 1.0 strict doctype. But that is not the problem here. I tried to reproduce the effect in another application and there the `&shy;` is left intact, when I do the crawling in a test controller and output it in a browser. But when I do the same thing in a console command like the following, the `&shy;` is decoded to a `u+000AD` codepoint, which is a soft-hyphen character. To confuse us all, this is displayed as a `-` character in my IDE and on the console, but copied for example to this GitHub input field here, not displayed at all. This happens not just within the dumped-output in the console, but also when written directly to a file, so it is not due to the console output filtering or other console-only quirks. Because, to make things weird, writing the same string into a file inside the controller also leads to the conversion.

    <?php
    declare(strict_types=1);
    namespace App\Command;
    
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Component\DomCrawler\Crawler;
    
    class TestCrawlCommand extends Command
    {
        protected static $defaultName = 'app:testcrawl';
    
        protected function configure()
        {
            $this->setDescription('Reproduces a possible entity decoder bug.');
        }
    
        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $crawler = new Crawler('<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><p id="test">We wan&shy;t that <code>&amp;shy;</code> thing left intact.</p></body></html>');
    
            $testdata = $crawler->filter('#test')->html();
            file_put_contents(__DIR__ . '/out.txt', $testdata);
            dump($testdata);
            return 0;
        }
    }

Here, both outputs have the `&shy;` converted. So let's try it inside a controller:

    /**
     * @Route(
     *     "/testcrawl.html",
     *     name="testcrawl",
     *     methods={"GET"},
     * )
     */
    public function testCrawlAction()
    {
        $crawler = new Crawler('<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><p id="test">We wan&shy;t that <code>&amp;shy;</code> thing left intact.</p></body></html>');

        $testdata = $crawler->filter('#test')->html();
        file_put_contents(__DIR__ . '/out.txt', $testdata);
        dump($testdata);
        return new Response('');
    }

I have to process and display the crawled data as is, with the `&shy;` intact, just as is when used in a web context. So new question is: Why is the `&shy;` decoded to its unicode counterpart in a Command context or when it's written to a file, but not when I dump it to a web output?

**Comment by stof** [comment]
> The page I crawl uses a xhtml 1.0 strict doctype. But that is not the problem here, having masterminds/html5 or not installed makes no difference.

if you use XHTML, that's expected, as DomCrawler will never use the HTML5 parser for this case.

> Both dump-calls in the Crawler-part of the controller lead to the same code, but the file itself differs.

Are you sure that this is not an artifact of the software you use to read the file, then ?

**Comment by spackmat** [comment]
> Are you sure that this is not an artifact of the software you use to read the file, then ?

Quite sure, as I would expect a string beginning with `We wan&shy;t` but have 'We want' (with the invisible soft-hyphen character) or 'We wan-t' in it, depending on the editor displaying that file. Dumping the output of the DOMDocument shows the expected behavior.

**Comment by nicolas-grekas** [comment]
> have 'We want' (with the invisible soft-hyphen character) or 'We wan-t' in it, depending on the editor displaying that file.

doesn't this lead to this conclusion: the "shy" is always here, but it's not always displayed, depending on the tools that does the rendering? I think the behavior of turning `&shy;` to `u+000AD` is deterministic and the correct one. Displaying or not this code point unrelated to Symfony. Replace "\u{00AD}"` with the empty string if that's what you want.

**Comment by spackmat** [comment]
I just need the scraped content untouched without any unsolicited entity-decoding or whatever for further processing.

Sure could I replace the decoded entities back, but I don't know which entities were decoded besides `&shy;` so I don't know which should be replaced. Also coding back and forth just because I cannot turn off the decoding in the first place doesn't seem a good design to me.

**Comment by nicolas-grekas** [comment]
`&shy;` is the only unicode character with this behavior, you're safe removing it and let the rest as is. People use it to do hyphenation, and it's true this complicates extracting texts, but this in unrelated to decoding HTML contents, which must happen by the very definition of the API.

I'm closing here because there is no bug, just a special case that should be dealt with on your side.

**Comment by spackmat** [comment]
First: I accept that the issue is closed and I don't want it reopened.

> People use it to do hyphenation, and it's true this complicates extracting texts, but this in unrelated to decoding HTML contents, which must happen by the very definition of the API.

I don't understand what you mean by that. To be precise: What API declares that a DOM crawler must decode html entities? PHPs DOMDocument doesn't and its saveHtml() method returns the raw content of the loaded HTML tree not touching the content strings. I expected also the DomCrawler to not be opinionated about the crwaled/extracted content and that it doesn't touches it in any way.

> &shy; is the only unicode character with this behavior

There are several unicode characters that are not visible (like the ZERO WIDTH SPACE U+200B) and a good way to handle them for an input field in a CMS is to use their entities. In practice nearly all cases are about the soft-hyphen, but all those things happen and that's why I want to process the raw content as is and not as a normalized derivate.

**Comment by ZaneCEO** [comment]
Sorry for the necroposting, but I'm in the same situation as @spackmat : moving data across different systems. Plus: I've a test attached to it, and it fails like this:

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'O&O'
+'O&amp;O'
```

I triple-checked the HTML of the actual page, and it has `<meta charset="utf-8">` and the content is actually outputted as `O&O`. The test fails because the crawler is doing some behind-the-scene encoding.

@spackmat said it best:

>  I expected also the DomCrawler to not be opinionated about the crwaled/extracted content and that it doesn't touches it in any way.

--------------

**Edit**: I replaced `$crawler->filter('body h1')->html()` (this is instruction causing the problem for me) with `$crawler->filter('body h1')->getNode(0)->nodeValue` and now it works 🎉  as expected. Since this seems solid, it's OK for me
