### ISSUE TITLE
[RFC][YAML] Support binary int notation

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#35357]
**Description**  
According to the 1.1 spec (https://yaml.org/type/int.html), `0b\d+` should be supported as binary int notation, which isn't currently the case on the parser.

The 1.2 spec (which is the spec used by the component) is known to be a superset of the 1.1 (see the status on https://yaml.org/spec/1.2/spec.html), and doesn't define anything on types, so it should be safe to assume that the rules on types, unless specified otherwise, are still applying.

**Example**  
```yaml
my_int: 0b101 # translate to 5
```

This can be useful when declaring a config with flags.

I'd be glad to work on that, just wanted to open this RFC first.

**Comment by Taluu** [comment]
The subject has been mentioned in #8094, but doesn't really seem to have popped back up. As it's been a while, I'd like to discuss this once again.

**Comment by stof** [comment]
The 1.2 spec defines things for types in what they call a schema. See https://yaml.org/spec/1.2/spec.html#id2804923

**Comment by derrabus** [comment]
> The 1.2 spec (which is the spec used by the component) is known to be a superset of the 1.1

YAML 1.2 is not a superset of 1.1, but a superset of JSON. The spec contains breaking changes, for instance for booleans (`on` and `off` were valid boolean literals according to YAML 1.1, but a YAML 1.2 parser has to parse them as strings).

YAML 1.2 refers to the JSON spec when it comes to literals and the JSON spec does not define the `0b` syntax, AFAIK. My interpretation of the YAML 1.2 spec is that the binary integer notation is not supported anymore.

**Comment by xabbuh** [comment]
I read the spec the same way as explained by @derrabus.

**Comment by Taluu** [comment]
Hum, saw that JSON doesn't indeed support binary int notation. Too bad, we will have to keep using hacks to support it then (fetching the string, checking if it's a binary notation and then convert it).

Closing.
