### ISSUE TITLE
Symfony 5 - An error occurred while loading the web debug toolbar.

### ISSUE THREAD

**Issue by vl20100** [symfony/symfony#35365]
Symfony 5.0.2

I have set up a new project using "composer create-project symfony/website-skeleton myproject".

The debug toolbar shows the message "An error occurred while loading the web debug toolbar."

I installed the symfony/apache-pack but the problem is already there.

I searched the web for hours to find a solution and nothing helps.

When I open the javascript console, I have this error : "/myproject/public/_wdt/afab40:1 Failed to load resource: the server responded with a status of 404 (Not Found)"

Is it a bug or a configuration error ?

![image](https://user-images.githubusercontent.com/11457015/72541512-f2e1a700-3882-11ea-8242-35aadcfa5a76.png)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by hichamzaher** [comment]
hello vl20100,
 I have the same problem as you, I would like to know if you have found the solution and if can you share it with me 
thank you in advance

**Comment by hichamzaher** [comment]
Problem solved

**Comment by antoine1003** [comment]
How did you solve it?

**Comment by plencovich** [comment]
In my case, creating the `.htaccess` file in `/public`, it was fixed

```
   <IfModule mod_rewrite.c>
       RewriteEngine On
       RewriteCond %{REQUEST_FILENAME} !-f
       RewriteRule ^(.*)$ index.php [QSA,L]
   </IfModule>
```

**Comment by edwardbrosens** [comment]
> In my case, creating the `.htaccess` file in `/public`, it was fixed
> 
> ```
>    <IfModule mod_rewrite.c>
>        RewriteEngine On
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </IfModule>
> ```

Worked for me too.

**Comment by ValBocquet** [comment]
> In my case, creating the `.htaccess` file in `/public`, it was fixed
> 
> ```
>    <IfModule mod_rewrite.c>
>        RewriteEngine On
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </IfModule>
> ```

Perfect. Thanks.

**Comment by fazliddin** [comment]
Wow `.htaccess` solves the problem. But it is strange that Symfony does not have it by default.

**Comment by ortiz-facundo** [comment]
> In my case, creating the `.htaccess` file in `/public`, it was fixed
> 
> ```
>    <IfModule mod_rewrite.c>
>        RewriteEngine On
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </IfModule>
> ```

It worked for me too. (Also i would like to know why its necesary, and what it does. If any have the time to respond that it would be helpful). TY

**Comment by skipper-henrik** [comment]
Thank you very much folks. worked for me with Symfony 7.2.4 version

**Comment by wakori** [comment]
> In my case, creating the `.htaccess` file in `/public`, it was fixed
> 
> ```
>    <IfModule mod_rewrite.c>
>        RewriteEngine On
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </IfModule>
> ```

Thank you! This one worked with version Symfony 6.4

**Comment by renewable** [comment]
> In my case, creating the `.htaccess` file in `/public`, it was fixed
> 
> ```
>    <IfModule mod_rewrite.c>
>        RewriteEngine On
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </IfModule>
> ```

Thank you! The .htaccess solution worked for me too,  with Symfony version 7.3.2 - serving with Apache on MacOS.

**Comment by artem01x-ai** [comment]
in my case, for php-fpm, the same only in nginx config
location / {
	try_files $uri /index.php?$query_string;
}

<img width="684" height="474" alt="Image" src="https://github.com/user-attachments/assets/166a8328-8e97-4ab6-a897-e963b3f2061a" />
