### ISSUE TITLE
Validation @Assert\DateTime on a doctrine date field indicates that the value must be of type string

### ISSUE THREAD

**Issue by jfsenechal** [symfony/symfony#35378]
**Symfony version(s) affected**: 5.0.2

**Description**  
When validating the form which has a date field with a "single_text" widget the assertion dateTime returns an error indicating that a string type is required 

**How to reproduce**  
`
//Entity
/**
     * @ORM\Column(type="date")
     * @Assert\DateTime
     */
    private $datedebut;
`

`
//Form
$builder
            ->add(
                'datedebut',
                DateType::class,
                [
                    'widget' => 'single_text',
                    'required' => false,
                ]
            );
`

**Possible Solution**  
I think it's due to a recent update at doctrine.
Maybe : https://github.com/doctrine/persistence/releases/tag/1.3.6 ??

**Additional context**  
![Capture du 2020-01-17 20-45-16](https://user-images.githubusercontent.com/7106002/72641440-83df7d80-396a-11ea-840d-46569fbbd316.png)

**Comment by HeahDude** [comment]
Hello @jfsenechal, you should use `@Assert\NotNull` instead of `@Assert\DateTime`.
Using date constraints to validate date objects has been deprecated in Symfony 4 and throw an exception in 5.0 for values that are not strings.
If you really want to perform a type check you should use the type constraint `@Assert\Type("DateTime")`.

**Comment by xabbuh** [comment]
I am closing here as this is the expected behaviour as explained by @HeahDude. Thank you for understanding.

**Comment by FadelChafai** [comment]
Use :  #[Assert\Type("\DateTimeInterface")]
