### ISSUE TITLE
[EventDispatcher] Problems with TraceableEventDispatcher

### ISSUE THREAD

**Issue by Pheetbag** [symfony/symfony#35380]
**Symfony version(s) affected**: 4.4.2

**Description**  

`Symfony/EventDispatcher` class `TraceableEventDispatcher` is not compatible with the new stablished standards (Using `Symfony\Contracts\EventDispatcher\Event` instead of `Symfony\Component\EventDispatcher\Event`).

**How to reproduce**  
In any current installation of the framework, the usage of `Symfony\Contracts\EventDispatcher\Event` as base class for an Event will throw an error when emitting an event using the recently deprecated `EventDispatcher::dispatch($eventName, $event);` 

**Possible Solution**  

This is because the TraceableEventDispatcher have a conditional that only check for instances of the deprecated `Symfony\Component\EventDispatcher\Event` so when using the new `Symfony\Contracts\EventDispatcher\Event` it just break my system. 

This is a small extract from the conflicting part of the code.

```php
        if (\is_object($event)) {
            $eventName = $eventName ?? \get_class($event);
        } else {
            @trigger_error(sprintf('Calling the "%s::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.', EventDispatcherInterface::class), E_USER_DEPRECATED);
            $swap = $event;
            $event = $eventName ?? new Event();
            $eventName = $swap;

            // !!! This conditional is the one giving problems
            if (!$event instanceof Event) {
                throw new \TypeError(sprintf('Argument 1 passed to "%s::dispatch()" must be an instance of %s, %s given.', EventDispatcherInterface::class, Event::class, \is_object($event) ? \get_class($event) : \gettype($event)));
            }
        }
```

I guess the inclution of `Symfony\Contracts\EventDispatcher\Event` in the validation will be enough but i want to check for opinions before making a PR.

**Comment by xabbuh** [comment]
If you use any other object than the old `Event` class from the component, you need to pass it as the first argument to `dispatch()`.

**Comment by xabbuh** [comment]
To explain this a bit more: If you pass the event as the second argument, you are using the legacy API. But that API never supported passing any other objects. If you want to change your application, you not only need to switch to using the `Event` class from the contracts, but you also need to swap arguments when calling `dispatch()`.

I am closing here as there is no bug.

**Comment by Pheetbag** [comment]
@xabbuh i understand now. Anyway IMHO the message needs more information in that regard. Those changes feels like individual changes that i can implement at muy own pace and no information explain that they come as a single change, so when faced with this error It feels more like a BC break (i know is not the case but It might be confusing).

And thanks for the help!
