### ISSUE TITLE
Symfony5 getenv() returns false

### ISSUE THREAD

**Issue by bogdandovgopol** [symfony/symfony#35388]
Hi,

I'm using new symfony5 project and trying to access .evn variables using  getenv().
```
getenv('APP_ENV');
getenv('APP_SECRET');
...
```
But for some reason it always returns false.
When I try $_SERVER or $_ENV, value is correctly returned.

**Comment by xabbuh** [comment]
As `putenv()` is not thread-safe it is not called by default. If you still want to have your environment variables populated with `putenv()`, you need to pass `true` to the constructor of the `Dotenv` class.

**Comment by bogdandovgopol** [comment]
@xabbuh Thanks, so what is recommended to use to get .env variables? $_ENV?

**Comment by nicolas-grekas** [comment]
Injecting variables via dependency injection, that's the recommended way. i.e. code shouldn't care where the value comes from.

**Comment by martynwheeler** [comment]
Hi,

Just stumbled on this.  Would you mind giving a pointer as to how to inject variables via dependency injection, please?

Thanks

**Comment by AkashicSeer** [comment]
How do we test classes that are dependency injected into other services, controllers etc? 
I've figured out how to set the environmental variables.
 I've figured out how to set them as secrets in the vault.
 I have figured out how to get these values passed to my classes that need them with the services.yaml file.
 I have figured out how the Dependency Injection works etc. etc. etc. etc.
 I have no clue how the hell to test classes that rely on these values when they are dependency injected other than hard coding them in the tests and that is what we try to avoid. 
I tried dependency injecting the Test cases, that doesn't work, nothing gets passed to them.  I don't know why. I don't know what to google. 
I guess our only option for testing classes that are dependency injected is to write the test then delete it so no one sees the values. Wow how useful.
 
I have googled and dug in the docs and google and googled and tried everything. It is seriously pathetic that those with the knowledge to help new comers refuse to do so and rather watch us all struggle. I'll never understand the mindset of people like this. 
Is it a power trip thing? Is it to feel special that you know something other people don't know? Does it make you feel cool to harbor and hide information that would make other peoples lives tremendously easier? What is it can anyone help me understand this situation and why people do this? It plagues the industry terribly. 

Why hide information that would take minutes to share? It really reflects the kind of person you are.

**Comment by nicolas-grekas** [comment]
Here is the pointer to the doc about env vars:
https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables

>  I have no clue how the hell to test classes that rely on these values when they are dependency injected other than hard coding them in the tests and that is what we try to avoid?

Maybe this could help:
https://symfony.com/doc/current/testing.html#accessing-the-container

> It really reflects the kind of person you are.

I don't know if you realize it, but this comment completely ruins any will to further communicate with you. If you're looking for psychological bias, you could have a look at the paradox of expertise on Google. That's one of the reasons why the documentation absolutely needs new contributions from fresh minds. I hope you will contribute to the doc once you figure out the answer you're looking for. Before that, to get knowledge, I invite you to connect with the community as explained on https://symfony.com/support. Please mind your general tone, nobody owes anyone anything. All happens because we're nice to each other.

**Comment by kyrrr** [comment]
Seems using putenv is kind of bugged. 

I can call ```usePutenv(true)``` on the Dotenv object, but this does not work.

```php
// index.php
$env = new Dotenv();
$env->usePutenv(true);
$env->bootEnv(dirname(__DIR__).'/.env');

... 

var_dump(getenv("APP_ENV")); // bool(false)

```

Manually setting ```private $usePutEnv = true``` in the class works, but that's hardly a workable solution. 

```php
// Dotenv.php
...
private $usePutenv = true;

...

var_dump(getenv("APP_ENV")); // string(3) "dev"
```

**Comment by melbings** [comment]
> As `putenv()` is not thread-safe it is not called by default. If you still want to have your environment variables populated with `putenv()`, you need to pass `true` to the constructor of the `Dotenv` class.

Or, since passing booleans into the constructor is now deprecated, use `usePutenv(true)`. For example, in my `public/index.php`:

```php
(new Dotenv())->usePutenv(true)->bootEnv(dirname(__DIR__).'/.env');
```

**Comment by apogadaev** [comment]
> > As `putenv()` is not thread-safe it is not called by default. If you still want to have your environment variables populated with `putenv()`, you need to pass `true` to the constructor of the `Dotenv` class.
> 
> Or, since passing booleans into the constructor is now deprecated, use `usePutenv(true)`. For example, in my `public/index.php`:
> 
> ```
> (new Dotenv())->usePutenv(true)->bootEnv(dirname(__DIR__).'/.env');
> ```

@melbings Thank you! That helps a lot.
