### ISSUE TITLE
[Console][5.0] FatalError due to typehint mismatch

### ISSUE THREAD

**Issue by PatchRanger** [symfony/symfony#35385]
**Symfony version(s) affected**: 5.0.2

**Description**  
Adding typehint for interface in https://github.com/symfony/symfony/commit/26624ed5294b590c2213cd18e74824a26cb1ccd0 caused inconsistency, resulting in the following fatal error:
```
Fatal error: Declaration of Symfony\Component\Console\Input\Input::getArgument($name) must be compatible with Symfony\Component\Console\Input\InputInterface::getArgument(string $name) in .../vendor/symfony/console/Input/Input.php on line 28
```
I gave a fast look, it looks the problem is with these 2 methods: `getArgument`, `setArgument`.

**Possible Solution**  
I guess we just need to add proper typehints.

**Comment by nicolas-grekas** [comment]
@xabbuh is right (and your PR is good, but not for the reason reported here :))

**Comment by PatchRanger** [comment]
@xabbuh I've checked: yes, you're right, I use `tetraweb/php` docker image, that's why my PHP version was 7.1 maximum. That explains the error message I get.
@nicolas-grekas I agree)
Thank you all for participation, I appreciate your time)
