### ISSUE TITLE
Mailgun-Mailer replyTo() prefixing name with "Reply-To: "

### ISSUE THREAD

**Issue by nicholaswright** [symfony/symfony#35389]
**Symfony version(s) affected**: symfony/mailgun-mailer 5.0.2

**Description**  
Since upgrading to the latest Mailgun-Mailer reply-to address names are being prefixed with the string "Reply-To". E.g. `"Reply-To: $name" <$address>`. If no name is provided then Reply-To is still included e.g. `"Reply-To: " <$address>`.

**How to reproduce**  
````
$dsn = sprintf('mailgun+api://%s:%s@default', $mailgunApiKey, $mailgunDomain);
$transport = Transport::fromDsn($dsn);
$mailer = new \Symfony\Component\Mailer\Mailer($transport);

$email = new Email();
$email->to($toAddress);
$email->from($fromAddress);
$email->subject($subject);
$email->html($body);
$email->replyTo($replyTo);

$mailer->send($email);
````

**Additional context**  
This is how Gmail is presenting the reply to information:
![Screenshot 2020-01-19 at 15 30 14](https://user-images.githubusercontent.com/5063452/72683594-a12e5c00-3ad0-11ea-8b65-d23a9b4e0de5.PNG)

**Comment by fabpot** [comment]
This has been fixed in 5.0.3.
