### ISSUE TITLE
PHP 7.4, Symfony 5, command extends non type hinted property

### ISSUE THREAD

**Issue by egormanakin** [symfony/symfony#35386]
**Symfony version(s) affected**: 5.0

**Description**  
Compile Error: Type of Symfony\Component\Translation\Command\XliffLintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)

**Comment by xabbuh** [comment]
Can you please be more specific? What exactly did you do? How can we reproduce the issue?

**Comment by mbabker** [comment]
It sounds like you're trying to add the type to the `$defaultName` class property:

```php
final class MyCommand extends Command
{
    protected static string $defaultName = 'my-command';
}
```

This isn't supported.  If the parent class doesn't have a type on a property, you can't add it in a child class.  This is a PHP limitation, and as Symfony 5 supports PHP 7.2 it can't add types to class properties.

**Comment by egormanakin** [comment]
> It sounds like you're trying to add the type to the `$defaultName` class property:
> 
> ```
> final class MyCommand extends Command
> {
>     protected static string $defaultName = 'my-command';
> }
> ```
> 
> This isn't supported. If the parent class doesn't have a type on a property, you can't add it in a child class. This is a PHP limitation, and as Symfony 5 supports PHP 7.2 it can't add types to class properties.

It is a bug of symfony/translation package.

Class Symfony\Component\Console\Command has property $defaultName typed as string. But class Symfony\Component\Translation\Command\XliffLintCommand which extends Command has not a string type.

It needs to developers add string type to symfony translation command class.

**Comment by mbabker** [comment]
No it doesn't, see [this line](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Console/Command/Command.php#L35) to confirm.

It's possible the type got added in your local environment somehow.  I remember seeing somewhere in the last couple of weeks that a tool someone was using added the type to the parent `Command` class when they were trying to add the type to their subclass and it caused this error, maybe the same thing happened for you?

**Comment by egormanakin** [comment]
> It's possible the type got added in your local environment somehow. I remember seeing somewhere in the last couple of weeks that a tool someone was using added the type to the parent `Command` class when they were trying to add the type to their subclass and it caused this error, maybe the same thing happened for you?

Yes. You're absolutely right. PhpStorm helps to add type hint and changes it in abstract vendor classes.
Thank you!

**Comment by ben-grandin** [comment]
Hello guys,

I'm using PhpStorm too and I'm facing the same problem when I'm trying to start my php container since I've add those lines to my Dockerfile : 
```sh
RUN apk add libxml2-dev
RUN	docker-php-ext-install xml; \
	docker-php-ext-install soap;
```

Here the errors: 
```php
Executing script cache:clear [KO]

[KO]

Script cache:clear returned with error code 255

!!

!! Fatal error: Type of Symfony\Component\Yaml\Command\LintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command) in /srv/api/vendor/symfony/yaml/Command/LintCommand.php on line 248

!! PHP Fatal error: Type of Symfony\Component\Yaml\Command\LintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command) in /srv/api/vendor/symfony/yaml/Command/LintCommand.php on line 248

!! Symfony\Component\ErrorHandler\Error\FatalError {#655

!! -error: array:4 [

!! "type" => 64

!! "message" => "Type of Symfony\Component\Yaml\Command\LintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)"

!! "file" => "/srv/api/vendor/symfony/yaml/Command/LintCommand.php"

!! "line" => 248

!! ]

!! #message: "Compile Error: Type of Symfony\Component\Yaml\Command\LintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)"

!! #code: 0

!! #file: "./vendor/symfony/yaml/Command/LintCommand.php"

!! #line: 248

!! }

!!

Script @auto-scripts was called via post-install-cmd
```

I don't know how to fixe them.. I mean, changing vendor files isn't a good solution right ?

Ps : i'm on a API Platform setup if it could help

[EDIT] I delete my vendor, and this works. Btw, you must not type $defaultName.

**Comment by jbonnier** [comment]
I'm pretty sure that if you exclude the vendor directory PhpStorm will not attempt to change files in vendors, it might even give you an error when you try to do so.

![image](https://user-images.githubusercontent.com/14863969/105560894-3b783f80-5ce3-11eb-8e91-fe8d5d7f4862.png)

**Comment by do-web** [comment]
When this will be fixed?

**Comment by stof** [comment]
@do-web there is nothing to be fixed here. If you edit the code of Symfony locally to introduce bugs in it, there is nothing to fix in Symfony itself.

**Comment by jbonnier** [comment]
@do-web most likely your IDE is "fixing" some vendor code which causes the issue. If you are using PhpStorm make sure to mark your vendor as excluded so PhpStorm never edits code in that directory.

**Comment by andythedandy** [comment]
Thx for this discussion! It saved me quite some hours of searching for a phantom bug.
So removing the vendor folder and another `composer install` did the job.
