### ISSUE TITLE
[OK] Your project is now ready but it does not appear

### ISSUE THREAD

**Issue by MehdiZox** [symfony/symfony#35383]
**Symfony version(s) affected**: 5.0

**Description**  
Create a new folder in my office called test.

I want to create a new project called myProject.

He tells me that everything is ok and that my project is ready, but it does not appear.

See screenshot [S1]

**How to reproduce**  
Run -> `symfony new myProject --full`

**Possible Solution**  
I did some tests which are indicated on this site in General section : https://getcomposer.org/doc/articles/troubleshooting.md#package-not-found

I have a screenshot [S2]

**Additional context**  
**[S1]**

Create a new folder ...
![Capture1](https://user-images.githubusercontent.com/36897560/72667133-bcd62b80-3a18-11ea-98db-6b79f7be6802.JPG)

Executing command and wait only 5seconds ...
![Capture3](https://user-images.githubusercontent.com/36897560/72667149-df684480-3a18-11ea-8986-c1f9004fe58a.JPG)

[S2]
![4K6Fu](https://user-images.githubusercontent.com/36897560/72667162-fad34f80-3a18-11ea-9e40-b260011a356c.jpg)

**Comment by xabbuh** [comment]
Same as Symfony/cli#195?

**Comment by MehdiZox** [comment]
Yes, exactly !

**Comment by xabbuh** [comment]
Thank you for the confirmation. :+1: Let's close here then.
