### ISSUE TITLE
FileLocator paths are missing since v5 so cannot load resources from ../src as said in docs

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#35381]
In this PR https://github.com/symfony/symfony/pull/33285 the second and third argument of `FileLocator::__construct` were removed.

Before (<= v4.4) the lookup for resources was done from 2 paths.

```
/Users/path/src
/Users/path/src/Resources
```

\+ current path `/Users/path/src/Home/Config/routes`

Now (v5) the `$paths` property in `FileLocator` is empty so only current path is applied.

The resource is atemped to be resolved only as `/Users/path/src/Home/Config/routes/../src/Home/Application/Controller` for my definition `<import resource="../src/Home/Application/Controller" prefix="/home" type="annotation" />`

The [documentation still says](https://symfony.com/doc/current/routing.html#creating-routes-in-yaml-xml-or-php-files) to do this:

```yaml
# config/routes.yaml
controllers:
    resource: '../src/Controller/'
    type:     annotation
```

But for that cannot work. Is the documentation outdated and this is the correct behaviour or the `root_dir` should have been replaced by `project_dir` instead and this is a bug? Thanks-

**Comment by javiereguiluz** [comment]
@simPod thanks for reporting this issue. As you said, this was a doc issue that is already solved. The current docs (see https://symfony.com/doc/current/routing.html#creating-routes-as-annotations) are in sync with the latest annotation routing recipe (see https://github.com/symfony/recipes/blob/master/doctrine/annotations/1.0/config/routes/annotations.yaml).

So, closing as fixed.
