### ISSUE TITLE
symfony/cache 4.4.2 psr/simple-cache should be "require" instead of "require-dev"

### ISSUE THREAD

**Issue by nvanheuverzwijn** [symfony/symfony#35406]
**Symfony version(s) affected**: symfony/cache 4.4.2

**Description**  
psr/simple-cache is declared as a "require-dev" dependency in composer.json. It should be declared as "required" because it is explicitely used in Simple/AbstractCache.php (https://github.com/symfony/cache/blob/v4.4.2/Simple/AbstractCache.php#L15).

This makes AbstractCache unusable in production environment when composer is optimised to remove dev dependencies.

**How to reproduce**  
composer install symfony/cache version 4.4.2
instanciate AbstractCache

**Possible Solution**  
Move psr/simple-cache from require-dev to require.

**Comment by ro0NL** [comment]
i think the `Cache/Simple` package is an additional addon, thus optional. IF `psr/simple-cache` is available (a root dependency of your project), then `symfony/cache` provides simple cache support.

**Comment by nicolas-grekas** [comment]
@ro0NL is correct, we have this policy in Symfony: it's your responsibility to "require" this dependency if you use that (optional) feature of the component.
Closing therefore.

**Comment by nvanheuverzwijn** [comment]
Thanks for the information, sorry for bothering :(
