### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by KvnOnWeb** [symfony/symfony#35405]
Hello,

I try to call multiple requests in the same time but the delay of all request is the same that for each one. Your component support the "real" concurrent call like Guzzle PHP ? 

My goal feel to make less time because i call a very slow API. Maybe i have not understand the documentation here : https://symfony.com/doc/current/components/http_client.html#concurrent-requests

Sincerely,
Kévin

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
