### ISSUE TITLE
[Mailer] SMTP with certificate ssl not valid 

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#35403]
**Symfony version(s) affected**: 4.4.3

**Description**  
i try to send a mail on the SMTP server but this one don't have a certicate valid. 
So How to disable the ssl ? 

**How to reproduce**  
the error : 
```Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed```

**Comment by devDzign** [comment]
same error

**Comment by xfifix** [comment]
@nicolas-grekas  need your help :)

**Comment by javiereguiluz** [comment]
@xfifix please keep in mind that even our friend Nicolas is the current biggest contributor to Symfony ... he can't fix all reported issues. Let's wait for other members of the community to investigate this issue and try to provide a pull request to fix it. Thanks!

**Comment by fabpot** [comment]
The error message seems to indicate a user error, not a bug in the framework. Help should be done via our official support channels StackOverflow or Slack: https://symfony.com/support Thank you.
