### ISSUE TITLE
Impossible to access an attribute ("value") on a double variable ...

### ISSUE THREAD

**Issue by DamienHarper** [symfony/symfony#35419]
**Symfony version(s) affected**: 4.4.3 (I haven't tested 5.0.3 so far)

**Description**  
The cache panel is not accessible since 4.4.3: it triggers an exception
> Impossible to access an attribute ("value") on a double variable 

**How to reproduce**  
Open the profiler and try to access the cache panel.

**Possible Solution**  
change `value.value` to `value` in `Resources/views/Collector/cache.html.twig`at line 111

**Comment by bogdandovgopol** [comment]
Have the same error when accessing cache panel in symfony profiler:
Impossible to access an attribute ("value") on a double variable ("x.xxxx").

Symfony 5.0.4

**Comment by xabbuh** [comment]
@bogdandovgopol Can you please show the output of `composer show`?

**Comment by bogdandovgopol** [comment]
> beberlei/doctrineextensions          v1.2.6  A set of extensions to Doctrine 2 that add support for 
> additional query functions available in MySQL and Oracle.
> doctrine/annotations                 v1.8.0  Docblock Annotations Parser
> doctrine/cache                       1.10.0  PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
> doctrine/collections                 1.6.4   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
> doctrine/common                      2.12.0  PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces, pro...
> doctrine/dbal                        v2.10.1 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
> doctrine/doctrine-bundle             2.0.7   Symfony DoctrineBundle
> doctrine/doctrine-migrations-bundle  2.1.2   Symfony DoctrineMigrationsBundle
> doctrine/event-manager               1.1.0   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
> doctrine/inflector                   1.3.1   Common String Manipulations with regard to casing and singular/plural rules.
> doctrine/instantiator                1.3.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> doctrine/lexer                       1.2.0   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
> doctrine/migrations                  2.2.1   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it...
> doctrine/orm                         v2.7.0  Object-Relational-Mapper for PHP
> doctrine/persistence                 1.3.6   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
> doctrine/reflection                  v1.1.0  The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functionality on top of the reflection functionality that comes ...
> easycorp/easy-log-handler            v1.0.9  A handler for Monolog that optimizes log messages to be processed by humans instead of software. Improve your productivity with logs that are easy to understand.
> egulias/email-validator              2.1.15  A library for validating emails against several RFCs
> geocoder-php/common-http             4.2.0   Common files for HTTP based Geocoders
> geocoder-php/google-maps-provider    4.4.0   Geocoder GoogleMaps adapter
> geocoder-php/plugin                  1.1.0   Plugins to Geocoder providers
> giggsey/libphonenumber-for-php       8.11.3  PHP Port of Google's libphonenumber
> giggsey/locale                       1.8     Locale functions required by libphonenumber-for-php
> guzzlehttp/guzzle                    6.5.2   Guzzle is a PHP HTTP client library
> guzzlehttp/promises                  v1.3.1  Guzzle promises library
> guzzlehttp/psr7                      1.6.1   PSR-7 message implementation that also provides common utility methods
> jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
> knplabs/knp-snappy                   v1.2.1  PHP5 library allowing thumbnail, snapshot or PDF generation from a url or a html page. Wrapper for wkhtmltopdf/wkhtmltoimage.
> knplabs/knp-snappy-bundle            v1.7.0  Easily create PDF and images in Symfony2 by converting Twig/HTML templates.
> knpuniversity/oauth2-client-bundle   v1.32.0 Integration with league/oauth2-client to provide services
> laminas/laminas-code                 3.4.1   Extensions to the PHP Reflection API, static code scanning, and code generation
> laminas/laminas-eventmanager         3.2.1   Trigger and listen to events within a PHP application
> laminas/laminas-zendframework-bridge 1.0.1   Alias legacy ZF class names to Laminas Project equivalents.
> league/oauth2-client                 2.4.1   OAuth 2.0 Client Library
> league/oauth2-google                 3.0.2   Google OAuth 2.0 Client Provider for The PHP League OAuth2-Client
> monolog/monolog                      2.0.2   Sends your logs to files, sockets, inboxes, databases and various web services
> nikic/php-parser                     v4.3.0  A PHP parser written in PHP
> nyholm/psr7                          1.2.1   A fast PHP7 implementation of PSR-7
> ocramius/package-versions            1.5.1   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
> ocramius/proxy-manager               2.6.1   A library providing utilities to generate, instantiate and generally operate with Object Proxies
> odolbeau/phone-number-bundle         v3.0.0  Integrates libphonenumber into your Symfony application
> php-http/discovery                   1.7.4   Finds installed HTTPlug implementations and PSR-7 message factories
> php-http/httplug                     2.1.0   HTTPlug, the HTTP client abstraction for PHP
> php-http/message-factory             v1.0.2  Factory interfaces for PSR-7 HTTP Message
> php-http/promise                     v1.0.0  Promise used for asynchronous HTTP requests
> phpdocumentor/reflection-common      2.0.0   Common reflection classes used by phpdocumentor to reflect the code structure
> phpdocumentor/reflection-docblock    4.3.4   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
> phpdocumentor/type-resolver          1.0.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
> psr/cache                            1.0.1   Common interface for caching libraries
> psr/container                        1.0.0   Common Container Interface (PHP FIG PSR-11)
> psr/event-dispatcher                 1.0.0   Standard interfaces for event handling.
> psr/http-client                      1.0.0   Common interface for HTTP clients
> psr/http-factory                     1.0.1   Common interfaces for PSR-7 HTTP message factories
> psr/http-message                     1.0.1   Common interface for HTTP messages
> psr/log                              1.1.2   Common interface for logging libraries
> psr/simple-cache                     1.0.1   Common interfaces for simple caching
> ralouphie/getallheaders              3.0.3   A polyfill for getallheaders.
> ramsey/uuid                          3.9.2   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
> ramsey/uuid-doctrine                 1.6.0   Allow the use of ramsey/uuid as a Doctrine field type.
> sensio/framework-extra-bundle        v5.5.3  This bundle provides a way to configure your controllers with annotations
> stripe/stripe-php                    v7.22.0 Stripe PHP Library
> symfony/apache-pack                  v1.0.1  A pack for Apache support in Symfony
> symfony/asset                        v5.0.4  Symfony Asset Component
> symfony/browser-kit                  v5.0.4  Symfony BrowserKit Component
> symfony/cache                        v5.0.4  Symfony Cache component with PSR-6, PSR-16, and tags
> symfony/cache-contracts              v2.0.1  Generic abstractions related to caching
> symfony/config                       v5.0.4  Symfony Config Component
> symfony/console                      v5.0.4  Symfony Console Component
> symfony/css-selector                 v5.0.4  Symfony CssSelector Component
> symfony/debug-bundle                 v5.0.4  Symfony DebugBundle
> symfony/debug-pack                   v1.0.7  A debug pack for Symfony projects
> symfony/dependency-injection         v5.0.4  Symfony DependencyInjection Component
> symfony/doctrine-bridge              v5.0.4  Symfony Doctrine Bridge
> symfony/dom-crawler                  v5.0.4  Symfony DomCrawler Component
> symfony/dotenv                       v5.0.4  Registers environment variables from a .env file
> symfony/error-handler                v5.0.4  Symfony ErrorHandler Component
> symfony/event-dispatcher             v5.0.4  Symfony EventDispatcher Component
> symfony/event-dispatcher-contracts   v2.0.1  Generic abstractions related to dispatching event
> symfony/expression-language          v5.0.4  Symfony ExpressionLanguage Component
> symfony/filesystem                   v5.0.4  Symfony Filesystem Component
> symfony/finder                       v5.0.4  Symfony Finder Component
> symfony/flex                         v1.6.2  Composer plugin for Symfony
> symfony/form                         v5.0.4  Symfony Form Component
> symfony/framework-bundle             v5.0.4  Symfony FrameworkBundle
> symfony/http-client                  v5.0.4  Symfony HttpClient component
> symfony/http-client-contracts        v2.0.1  Generic abstractions related to HTTP clients
> symfony/http-foundation              v5.0.4  Symfony HttpFoundation Component
> symfony/http-kernel                  v5.0.4  Symfony HttpKernel Component
> symfony/inflector                    v5.0.4  Symfony Inflector Component
> symfony/intl                         v5.0.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
> symfony/mailer                       v5.0.4  Symfony Mailer Component
> symfony/maker-bundle                 v1.14.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
> symfony/mime                         v5.0.4  A library to manipulate MIME messages
> symfony/monolog-bridge               v5.0.4  Symfony Monolog Bridge
> symfony/monolog-bundle               v3.5.0  Symfony MonologBundle
> symfony/notifier                     v5.0.4  A library to notify messages
> symfony/options-resolver             v5.0.4  Symfony OptionsResolver Component
> symfony/orm-pack                     v1.0.7  A pack for the Doctrine ORM
> symfony/phpunit-bridge               v5.0.4  Symfony PHPUnit Bridge
> symfony/polyfill-intl-grapheme       v1.13.1 Symfony polyfill for intl's grapheme_* functions
> symfony/polyfill-intl-icu            v1.13.1 Symfony polyfill for intl's ICU-related data and classes
> symfony/polyfill-intl-idn            v1.13.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
> symfony/polyfill-intl-normalizer     v1.13.1 Symfony polyfill for intl's Normalizer class and related functions
> symfony/polyfill-mbstring            v1.13.1 Symfony polyfill for the Mbstring extension
> symfony/polyfill-php73               v1.13.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
> symfony/process                      v5.0.4  Symfony Process Component
> symfony/profiler-pack                v1.0.4  A pack for the Symfony web profiler
> symfony/property-access              v5.0.4  Symfony PropertyAccess Component
> symfony/property-info                v5.0.4  Symfony Property Info Component
> symfony/routing                      v5.0.4  Symfony Routing Component
> symfony/security-bundle              v5.0.4  Symfony SecurityBundle
> symfony/security-core                v5.0.4  Symfony Security Component - Core Library
> symfony/security-csrf                v5.0.4  Symfony Security Component - CSRF Library
> symfony/security-guard               v5.0.4  Symfony Security Component - Guard
> symfony/security-http                v5.0.4  Symfony Security Component - HTTP Integration
> symfony/serializer                   v5.0.4  Symfony Serializer Component
> symfony/serializer-pack              v1.0.2  A pack for the Symfony serializer
> symfony/service-contracts            v2.0.1  Generic abstractions related to writing services
> symfony/stopwatch                    v5.0.4  Symfony Stopwatch Component
> symfony/string                       v5.0.4  Symfony String component
> symfony/test-pack                    v1.0.6  A pack for functional and end-to-end testing within a Symfony app
> symfony/translation-contracts        v2.0.1  Generic abstractions related to translation
> symfony/twig-bridge                  v5.0.4  Symfony Twig Bridge
> symfony/twig-bundle                  v5.0.4  Symfony TwigBundle
> symfony/twig-pack                    v1.0.0  A Twig pack for Symfony projects
> symfony/validator                    v5.0.4  Symfony Validator Component
> symfony/var-dumper                   v5.0.4  Symfony mechanism for exploring and dumping PHP variables
> symfony/var-exporter                 v5.0.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
> symfony/web-profiler-bundle          v5.0.4  Symfony WebProfilerBundle
> symfony/yaml                         v5.0.4  Symfony Yaml Component
> tijsverkoyen/css-to-inline-styles    2.2.2   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
> twig/cssinliner-extra                v3.0.1  A Twig extension to allow inlining CSS
> twig/extra-bundle                    v3.0.1  A Symfony bundle for extra Twig extensions
> twig/string-extra                    v3.0.1  A Twig extension for Symfony String
> twig/twig                            v3.0.1  Twig, the flexible, fast, and secure template language for PHP
> webimpress/safe-writer               2.0.0   Tool to write files safely, to avoid race conditions
> webmozart/assert                     1.6.0   Assertions to validate method input/output with nice error messages.
> willdurand/geocoder                  4.2.2   Common files for PHP Geocoder
> willdurand/geocoder-bundle           5.11.0  Integration of Geocoder into Symfony

**Comment by xabbuh** [comment]
This looks good. I suggest you open a new issue and provide a small example application that allows to reproduce your issue.

**Comment by arcticlinux** [comment]
I'm also having this issue, which was supposed to be fixed in https://github.com/symfony/symfony/pull/35423

I opened vendor/symfony/web-profiler-bundle/Resources/views/Collector/cache.html.twig and changed it to:

{% if key == 'time' %}
-  {{ '%0.2f'|format(1000 * value) }} <span class="unit">ms</span>
+ {{ (1000 * value)|round(2) }} <span class="unit">ms</span>

**Comment by shaaxx** [comment]
Same issue here. 
@arcticlinux solution work for me.

**Comment by leadinpier** [comment]
manually deleting your cache will fixe the issue
go to [your-project]/code/var/cache/
delete all (linux :  rm -fr *)
