### ISSUE TITLE
[Messenger] BC break when merging headers for amqp messages

### ISSUE THREAD

**Issue by mleczakm** [symfony/symfony#35439]
**Symfony version(s) affected**: 4.3.7, 5.0.3

**Description**  
Changing order of `array_merge`[ parameters](https://github.com/symfony/symfony/pull/34134#discussion_r341166022) made overriding `type` header in AMQP  impossible and hardcoded it to FQCN of message, which is not nice for interoperability.

**How to reproduce**  
Before this change, overriding header for envelope was simple like that:
```
/** @var Symfony\Component\Messenger\Envelope $envelope */
$envelope = $envelope->with(
                new AmqpStamp(
                    null, AMQP_NOPARAM, [
                        'headers' => [
                            'type' => 'CUSTOM_MESSAGE_TYPE',
                        ],
                    ]
                )
            );
```

**Possible Solution**  
Parameters order should be reverted, as it is BC change, or [HeaderStamp PR should be merged](https://github.com/symfony/symfony/pull/34481) to reenable overriding headers - it is must-have for sharing messages between codebases.

**Comment by Nyholm** [comment]
You should select a different serializer. I created an implementation that may be overkill https://github.com/Happyr/message-serializer

I will send a PR to the docs to show this feature better.

**Comment by Tobion** [comment]
The type header is a requirement by the serializer. If you don't want the type header, change the serializer and you can return any headers you want.

**Comment by mleczakm** [comment]
@Nyholm @Tobion are you aware that overriding type header works before update to 4.3.7 and is not possible anymore? It is BC break, it is bug, it can't be closed because it works for you...
