### ISSUE TITLE
4.3: Unable to find file "@FrameworkBundle/Resources/config/routing/errors.xml"

### ISSUE THREAD

**Issue by haivala** [symfony/symfony#35442]
**Symfony version(s) affected**: 4.3.10

**Description**  
Unable to find file "@FrameworkBundle/Resources/config/routing/errors.xml"

**How to reproduce**  
install symfony/frameworkbundle 4.3

**Possible Solution**  
file is not found in git branch 4.3 so perhaps it should be put back in place?
https://github.com/symfony/symfony/tree/4.3/src/Symfony/Bundle/FrameworkBundle/Resources/config
The release is broken?

**Comment by xabbuh** [comment]
This file was added in #33271 which was first released with Symfony 4.4. How did you end up with the file being loaded in your application?

**Comment by haivala** [comment]
Ah! 
I have been trying to update to 4.4. and come to conclusion it is working yet then I downgrade to 4.3 so the config is not removed on downgrade.. which is right.

**Comment by xabbuh** [comment]
Can you describe which steps you did perform to eventually reach a state where this file is loaded?

**Comment by haivala** [comment]
Now that I investigated further: I think it was case of some bundle (probably sonata) first allowing symfony 4.4 and then removing the support because it was not working as intended. meanwhile I made it work by adding that config. 
my composer.json says symfony/frameworkbundle: ^4.1

**Comment by haivala** [comment]
https://github.com/sonata-project/SonataPageBundle/blob/3.x/composer.json#L43 probably this

**Comment by xabbuh** [comment]
Okay, let's close then. Thank you for the feedback.

**Comment by Hyperalpha** [comment]
In my case it was because I had duplicated files that contain the same information => config/routes/framework.yaml and config/routes/dev/framework.yaml.
If you remove config/routes/dev/framework.yaml, the problem disappears.
