### ISSUE TITLE
[Messenger] Symfony serializer does not check all serializer failures

### ISSUE THREAD

**Issue by waaghals** [symfony/symfony#35446]
**Symfony version(s) affected**: 4.4|5.0

**Description**  
When the serialization of a message fails a `MessageDecodingFailedException` should be thrown. 
But this only happens for `UnexpectedValueException` in the [transport serializer](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L82).
This means that any other exceptions from the serializer like `MissingConstructorArgumentsException` do not result in a `MessageDecodingFailedException` from the messenger transport serializer.

Because this is not the case, the worker crashes and does not reject the message. This also means that the message stays in the queue, resulting in a crash loop of the worker.

**How to reproduce**  

1. Create a message in the bus without a worker running.
2. Add an extra field to the constructor of the created message
3. Run the worker
4. Message is not rejected because no `MessageDecodingFailedException` was thrown.

**Possible Solution**  
Instead of checking for `Symfony\Component\Serializer\Exception\UnexpectedValueException` check for `Symfony\Component\Serializer\Exception\ExceptionInterface` in `Symfony\Component\Messenger\Transport\Serialization\Serializer`

**Comment by Nyholm** [comment]
Thank you @waaghals. 

I agree with your solution. Could you send a PR to fix this issue?

**Comment by Tobion** [comment]
I think it's safe to just catch any exception there.
