### ISSUE TITLE
[HttpClient] Calling $httpClient->request(...) can result in unexpected exceptions

### ISSUE THREAD

**Issue by mleczakm** [symfony/symfony#35458]
**Symfony version(s) affected**: Probably 4.4 / 5.0

**Description**  
Calling `$httpClient->request(...)` (using Curl client) results in immediately destroyed `CurlResponse` object, which calls during destroying `checkStatusCode` method from `ResponseTrait` if no `$this->info['error']` is set. Problem is that when request timed out over `max_duration`, `$this->info['error']` can be empty (error message is shown in `debug` IIRC) and checking for status code throws exception.

**How to reproduce**  
```
// create Symfony/HttpClient with max_duration, expect unexpected exceptions thrown from `doDestruct` method of `ResponseTrait`
$httpClient->request('HEAD', 'some-timing-out-url');
```

**Possible Solution**  
Do not check status code in `doDestruct` method, fix empty `$info['error']` when request timed out over `max_duration`.

**Comment by nicolas-grekas** [comment]
> when request timed out over max_duration, $this->info['error'] can be empty

Can you provide a reproducer that would lead to an empty message?
The rest of your description is by design: the destructor throws when the status code is unchecked, check https://symfony.com/doc/current/components/http_client.html

**Comment by mleczakm** [comment]
So I would consider changing this design, because there are situations when some action need to be ended and i shouldn't need to care if there are somewhere unacked responses. I will try to reproduce this missing `error` message ASAP, because it breaks also our custom progress logger - after changing to `max_duration` timeout errors are no longer logged.

**Comment by mleczakm** [comment]
Unfortunately, cancelling request in `TraceableHttpClient` results in another bug - `request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined index: http_method" at /var/www/html/vendor/symfony/http-client/DataCollector/HttpClientDataCollector.php line 119`.
