### ISSUE TITLE
Depraction warning loading file assets from src is deprecated

### ISSUE THREAD

**Issue by Voetloos** [symfony/symfony#35457]
I have stuff like `@import '../assets/scss/WebsiteBundle/font.scss';` in `scss/WebsiteBundle/default.scss`, however, since Symfony 4.4 I get the following depracitation warning.

`Loading the file "../assets/../_photo.scss" from the global resource directory ".../src" is deprecated since Symfony 4.4 and will be removed in 5.0.`

I can't seem to find anything in the documentation about this. Can someone help me?

**Comment by xabbuh** [comment]
Is this related to the [WebpackEncoreBundle](https://github.com/symfony/webpack-encore-bundle)?

**Comment by Voetloos** [comment]
> Is this related to the [WebpackEncoreBundle](https://github.com/symfony/webpack-encore-bundle)?

Yes

**Comment by xabbuh** [comment]
Could you open the issue in the [WebpackEncoreBundle repository](https://github.com/symfony/webpack-encore-bundle)? I think the issue needs to be investigated there first if this actually is a bug in the Symfony core.

**Comment by Voetloos** [comment]
I fixed this by using
```php
$configDirectories = [__DIR__ . '/../../templates'];
$fileLocator = new FileLocator($configDirectories);
$fileName = $fileLocator->locate($resource, null, true);

```
