### ISSUE TITLE
[Mailer] Add ability to inject additional transport factories for DSN support

### ISSUE THREAD

**Issue by badams** [symfony/symfony#35469]
**Description**  
I'd like to be able to inject a custom transport factory when  calling `\Symfony\Component\Mailer\Transport::fromDsn` to add support for additional schemes, however the way that the Transport class is designed does not allow for additional factories to be specified, even if extended.

**Example**  
For example I've developed a custom transport for amazon SES that utilizes the official SDK for authentication, I'd like to be able to configure this via DSN like so

```
Transport::fromDsn('ses+sdk://ACCESS_KEY:SECRET_KEY@default`)
```

If an additional parameter was added to allow an array containing a list of custom factory classes was added to these factory methods it would be quite useful in this situation

My proposed changes would be to alter the methods `fromDsn`, `fromDsns`  and `getDefaultFactories` to also accept an array custom factory classes, `getDefaultFactories` would then yield a list of factories including both the default and custom factories,  the method should be renamed at that point to `getFactories`.

Now the following would be possible

```
Transport::fromDsn('ses+sdk://ACCESS_KEY:SECRET_KEY@default`, null, null, null, [
    SesSdkTransport::class
]);
```

I'd be happy to submit a PR if this proposal sounds acceptable

**Comment by micheh** [comment]
I did not check it completely, but can't you do the following:

1. Implement the `Symfony\Component\Mailer\Transport\TransportFactoryInterface`
2. Tag your custom factory with `mailer.transport_factory` 
3. Do _not_ use the static method `Symfony\Component\Mailer\Transport::fromDsn`. Instead use the instance (use the service `mailer.transport_factory` or autowire the dependency with typehint `Symfony\Component\Mailer\Transport`). The instance should contain your custom factory.

**Comment by badams** [comment]
@micheh I'm not using symfony framework or symfony's DI container, so I'm not familiar with the tagging concept, so please forgive me if I'm wrong here. but I still don't think that would work if I wanted to be able to configure the transport via DSN and maintain support for the default factories.

I could for example as you suggest, not use the static method for construction like so:

```php
$dsn = "custom://foo:bar@default";
$myTransportFactory = $container->get(MyTransportFactory::class);
$transport = new Symfony\Component\Mailer\Transport([$myTransportFactory]);

$myCustomTransport = $transport->fromString($dsn);
```

This would work to resolve my custom transport from a DSN string, however I'd lose support for all the default transports.

My use case for this component, and custom transport is that I have a environment variable defined  `MAILER_DSN` which is used to initialize the transport like so:

```php
// Container definitions
[
    TransportInterface::class => function () {
        return Symfony\Component\Mailer\Transport::fromDsn(getenv('MAILER_DSN'));
    }
]

// Some service using mailer, resolved with auto-wiring
class MyService {
    protected $mailer;
    public function __construct(Mailer $mailer)
    {
        $this->mailer = $mailer;
    }
}
```

So for example in a development or test environment I might use a different DSN `null://null` or `smtp://mailcatcher` for example

**Comment by fabpot** [comment]
You could merge your transport factory with the default ones, but `getDefaultFactories` is private right now. See #35519 for a fix. In the meantime, you can copy/paste the ones you want to support (adding of them is only a few lines of code).

**Comment by badams** [comment]
Thanks @fabpot 👍

**Comment by sofigio** [comment]
> I did not check it completely, but can't you do the following:
> 
> 1. Implement the `Symfony\Component\Mailer\Transport\TransportFactoryInterface`
> 2. Tag your custom factory with `mailer.transport_factory`
> 3. Do _not_ use the static method `Symfony\Component\Mailer\Transport::fromDsn`. Instead use the instance (use the service `mailer.transport_factory` or autowire the dependency with typehint `Symfony\Component\Mailer\Transport`).
> 4. Use the non-static method `Symfony\Component\Mailer\Transport::fromString` of the instance. This method should consider your custom factory.

Sorry if I comment on this issue but I'm trying to do something similar and maybe the solution is easy...

I need to read the SMTP settings from the database instead of hardcoding them to the .env file, so I copied the https://github.com/symfony/google-mailer with little changes:

```
<?php

namespace App\Utils\Mail;

use App\Service\Settings;
use Symfony\Component\Mailer\Transport\AbstractTransportFactory;
use Symfony\Component\Mailer\Transport\Dsn;
use Symfony\Component\Mailer\Transport\TransportInterface;

/**
 * Custom transport to read the email settings from the database, by using the Settings service
 */
class MailSettingsTransportFactory extends AbstractTransportFactory
{
    public function __construct(
        private Settings $settings
    ) {
        parent::__construct();
    }

    public function create(Dsn $dsn): TransportInterface
    {
        return new MailSettingsTransport($this->settings, $this->dispatcher, $this->logger);
    }

    protected function getSupportedSchemes(): array
    {
        return ['db-settings'];
    }
}

class MailSettingsTransport extends EsmtpTransport
{
    public function __construct(Settings $settings, EventDispatcherInterface $dispatcher = null, LoggerInterface $logger = null)
    {
        parent::__construct($settings->get('params.mailer_host'), $settings->get('params.mailer_host'), true, $dispatcher, $logger);

        $this->setUsername($settings->get('params.mailer_user'));
        $this->setPassword($settings->get('params.mailer_password'));
    }
}
```

in the yaml I have:

```
framework:
    mailer:
        dsn: 'db-settings://default'

services:
    App\Utils\Mail\MailSettingsTransportFactory:
        tags: [mailer.transport_factory]
```



But I have this problem: 

> [messenger] Error thrown while handling message Symfony\Component\Mailer\Messenger\SendEmailMessage. Sending for retry #2 using 2000 ms delay. Error: "Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: A message must have a text or an HTML part or attachments

What am I doing wrong? I found no documentation on how to implement a custom *Mailer* Transport, only for a *Messenger* transport, which it took some time for me to realize they are two different things... 😵
