### ISSUE TITLE
[PHPUnit bridge] Use paratest test runner

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#35467]
Follow-up of old issue #12091

The `simple-phpunit` approach via `bin/phpunit` is great, and removes unneeded dependencies for runtime.

**Description**  

The [`paratest` test runner](https://github.com/paratestphp/paratest) can be dropped-in without further configuration, and drastically reduces time needed to run tests.

Letting users use another test runner could be a matter of configuring in composer's `extra` section:

**Example**  

```json
"extra": {
    "symfony-phpunit-bridge": {
        "test-runner": "paratest"
    },
},
```

```sh
$ bin/phpunit

PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

>> Custom test runner configured: paratest. Enabled parallel testing for PHPUnit.

Running phpunit in 1 process with /codebase/bin/.phpunit/phpunit-8-0/phpunit

**Comment by theofidry** [comment]
Paratest also re-implements quite a lot of part PHPUnit hence can be tricky to always keep up to date. Instead of attempting to make the PHPUnitBridge richer, maybe it would be better to try to do more work on PHPUnit directly to enable easier parallelisation: https://github.com/sebastianbergmann/phpunit/issues/3387

**Comment by javiereguiluz** [comment]
In case you missed it, PHPUnit has a built-in feature to run tests in parallel. See https://symfony.com/doc/current/components/phpunit_bridge.html#running-tests-in-parallel . Did you try that? Did it fall short for some reason? Thanks!

**Comment by rvanlaak** [comment]
@javiereguiluz that is great, thank you for referring to that.

Feel free to close this issue.
