### ISSUE TITLE
[Translation] Add support for default fallback 

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#35466]
First, I'm not an expert on this component, so I will talk here as a user of this component.

**Description**  

In my application, we like to use unique key per template. For example I will have

* `mail_1.html.twig`: `{{ 'mail_1.item1.cta.url'|trans }}`
* `mail_2.html.twig`: `{{ 'mail_2.item1.cta.url'|trans }}`
* `mail_3.html.twig`: `{{ 'mail_3.item1.cta.url'|trans }}`

Like that, the final client is able to change the CTA link on one specific email.
But, in reality, he uses the same link for all emails. But sometime (it is a real need) he changes the link on just one very specific email.

So now, it's a bit boring to add N new keys to translate for each new template (mail or not).
(Boring as a dev, and extra works are needed for the translator)

It would be nice to have support for a "fallback key"

**Example**  

I could imagine something like:

* `mail_1.html.twig`: `{{ 'mail_1.item1.cta.url'|trans(default='after_sale_url') }}`
* `mail_2.html.twig`: `{{ 'mail_2.item1.cta.url'|trans(default='after_sale_url') }}`
* `mail_3.html.twig`: `{{ 'mail_3.item1.cta.url'|trans(default='after_sale_url') }}`

in this case, `after_sale_url` will be translated too. But maybe it's better to not translate it and force the following syntax:

```twig
{{ 'mail_1.item1.cta.url'|trans(default='after_sale_url'|trans) }}
```

The later one seems more semantic and flexible, but more verbose too.

WDYT ?

**Comment by ro0NL** [comment]
inspired by twig's template resolution, maybe

`[key, fallback.key]|trans`

**Comment by javiereguiluz** [comment]
MY comment is a bit un-related, but still: I think that using the translator component to translate "full contents" (a CMS page, a blog post an email) is "a mistake".

We should use the Translator component to translate the interface of the app/site. If you know a full long email is translated into multiple languages, create `templates/email/login/en.html.twig`, `templates/email/login/fr.html.twig`, `templates/email/login/es.html.twig`, etc.  And select the right template to render based on the locale.

Otherwise, your emails look complicated because of all those `|trans()` filters or your translation files look complicated because you put the entire email content in a single translation key.

**Comment by lyrixx** [comment]
@javiereguiluz I disagree with you. email a are really hard because of browser / mail client compatibility. I can not let my final client write HTML, they will mess-up everything.

More over we add new language often by changing a an array in a config.
It will be more complicated to have to check all templates.

And finally, it's totally not "complex". This is an example of what we have:
```
{% extends 'mails/XXXXX/layout_pixar.html.twig' %}

{% block content %}
    {# Title #}
    {{ include('mails/XXXXX/_components/_title.twig', {
        'txt': 'mail_sqills_v2.bus_delayed_90.title'|trans({
            '%delay%': delay
        })
    }) }}

    {# Paragraph #}
    {{ include('mails/XXXXX/_components/_paragraph.twig', {
        'txt': 'mail_sqills_v2.bus_delayed_90.excuse'|trans
    }) }}

    {# Divider #}
    {{ include('mails/XXXXX/_components/_divider.twig') }}

    {# Link to the booking #}
    {{ include('mails/XXXXX/_booking_manage.html.twig') }}

    {# Divider #}
    {{ include('mails/XXXXX/_components/_divider.twig') }}

{% endblock %}
```

**Comment by lyrixx** [comment]
> i tend to be  for a template global prefix key. I dont understand the example neither :)

I agree. I removed it from the main description

**Comment by digilist** [comment]
:+1: I like the idea of having a default. In a former project of mine we had to deal with defaults a lot where this feature would have been very handy.
 
@lyrixx The implementation is for Twig, but wouldn't it make also sense to add it to the Translator in general, so that this even works for translations outside of Twig templates?

**Comment by wbrinkman** [comment]
Maybe I don't understand your use-case exactly either, but the translator already supports fallback locales. 

If you need a fallback message-id on top of that, then I feel that that is an issue you should solve in your code / tests / CI/CD pipeline, not in the translator.

Are you generating your message-id's programmatically?

**Comment by goetas** [comment]
I think that here @Nyholm could give good feedback

**Comment by Nyholm** [comment]
Thank you for the ping. I saw this issue a while ago but I waited to give my answer until I clearly made up my mind. 

I agree with @javiereguiluz that **some** content are best to duplicate the template instead of using the Translation component. But I tend to do that rarely and @lyrixx example with emails design makes sense. 

I don't like the idea of having a "fallback key". The obviously are increased complexity for both the component and the user for a minimal benefit. But lets put that aside for a moment.

The background to this (as far as I understand) is that you want your client to be able to change translations without changing your template AND at the same time keep your translation keys to a minimum. 

I believe we (the community) need a better guidance in our key strategy and developing process. One could achieve the same goal by some cleaver naming of keys. 

Example, These keys:  
- `mail.item1.cta.url...1`
- `mail.item1.cta.url...2`
- `mail.item1.cta.url...3`

.. could all fallback to the translation of `mail.item1.cta.url` if they are not defined. That could be implemented in a translator decorator or in your CI flow for translations. 

Currently we got a real powerful component but not much practical instructions. Only "hello world" stuff and we display features.

**Comment by emullaraj** [comment]
In my experience I see @lyrixx issue in apps that actually needed to solve the translations aspects with an in-app feature. This could be achieved for example by structuring the translation, using a translator decorator as @Nyholm mentioned and giving a UI for actual content management to the user/translator.
In the CTA url example it would be a matter of creating a new translation key and filling the content from an existing translation key.
The benefits of integrating the translations behaviours in your app would "translate" in releasing the development area from the translations workflow (key definition, content definition and updates, missing contents, etc.). IMHO this separations of concerns makes development focus on delivering well defined features and reduces the cognitive load.

**Comment by emmanuelballery** [comment]
Hi @lyrixx, I don't like the idea of configuring this default key in my templates, it's way too verbose.

A custom solution would be to use your own translation syntax (Yaml example, sorry).

```yaml
after_sale_url: This is the real translation
mail_1.item1.cta.url: @after_sale_url
```

It's a custom logic, not that hard to implement in apps.

- It looks like the way service aliases are defined ;
- Easy to understand ;
- Can be resolved and cached ;
- Simplify the templating part ;

**Comment by lyrixx** [comment]
@wbrinkman:

> Maybe I don't understand your use-case exactly either, but the translator already supports fallback locales.

I think you indeed did not understand my RFC :grimacing: 

> If you need a fallback message-id on top of that, then I feel that that is an issue you should solve in your code / tests / CI/CD pipeline, not in the translator.

I could re-implement what I did in the PR in my codebase, yes. But I would like to put it in the core like that every users of symdony could use it.

I don't see how my tests, CI / CD pilepine are connected to this issue. We know some key are missing for some locale. That is not an issue at all. (Some part of the website are not even accessible for some locale).

> Are you generating your message-id's programmatically?

No, but the follow our standard `{controller_name}.{action].{something]`

---

@Nyholm 

> I agree with @javiereguiluz that some content are best to duplicate the template instead of using the Translation component

This is something that can be done when you have very few language to support **and** the translator know HTML and git and everything about that.

By saying that, you are saying the the Translator component is useless.

---

@emullaraj:

> This could be achieved for example by structuring the translation, using a translator decorator as @Nyholm mentioned and giving a UI for actual content management to the user/translator.

The translator team already use an UI: http://localise.biz/ It's really nice :+1:  BTW

> In the CTA url example it would be a matter of creating a new translation key and filling the content from an existing translation key.

I don't want to let the translator doing this job because because - in the end - they will process the same amount of job as before.

> IMHO this separations of concerns makes development focus on delivering well defined features and reduces the cognitive load.

This is out of topic, isn't?

---

@emmanuelballery  

> Hi @lyrixx, I don't like the idea of configuring this default key in my templates, it's way too verbose.

Indeed, this is a bit verbose :grimacing: but:

* It's very explicit 
* It's easy to extract this data and to send it to an external tool used by translator.

> A custom solution would be to use your own translation syntax (Yaml example, sorry).

I thought about this, but this is too complex for translator. (see next section)

---

To all:

I think I was not enough clear about my issue (some totally understand it, and some are totally out of the topic :grimacing:), and what I want to achieve. I'm sorry. 

**I will try to summary summary everything**

1. We use translator to translate our application.
1. We have 8 locales
1. We use a fallback locale
1. We have 12500 translation
1. We use an external tools https://localise.biz/
1. Translator use only this tools
1. Translation are fetched directly on production and so deployed as soon as a new translation is done
1. We don't validate translation in the CI or whatever. The final client and the translator team has full power on this part. They and us (dev team) are really happy with this workflow. More over we can't. It does not mean anything to validate translation. Some part of the website are not available for some locale. So it's pointless to translate them.
1. Translators does not know anything about HTML, git, etc. They know only about translating a string from a local to another locale
1. We give to our client a very flexible content management by using key of the following format `controller.action.something` (ex: `city.booking.origin.placeholder` or `
product.map.select.origin_placeholder`)
1. Sometime, they use the same translation for 2, 3, or more key:

  * `comparator.stations.origin.title` => `Departure point`
  * `lost_objects_form.origin.label` =>  `Departure point`

1. And sometime they change a bit the wording:

 * city.booking.origin.placeholder => `Your departure point`

So. I naively thought I could simplify the life of the translator team with the following syntaxe:

`{{ 'comparator.stations.origin.title'|trans(default='origin.title|trans) }}`

In the UI, translators will see something like:

![image](https://user-images.githubusercontent.com/408368/74318483-a3a56e00-4d7d-11ea-8d90-42276d4eaa1c.png)
(see the `default: origin.placeholder`)

When they will see that, they know they don't need to translate it, except if they want to customize the translation.

IMHO the best place for that is in the `Translator::trans()` directly. 
* It expose the semantic directly
* It does not hide a mapping
* It makes extracting easier (to send this information to the translator team)

---

I hope it's clearer... 
Initially, that was an idea to reduce the workload of the translator team. I don't really need this feature :joy:. So ATM I'm considering to close this RFC :)

**Comment by nicolas-grekas** [comment]
@lyrixx I think you missed this suggestion from @Nyholm:

> `mail.item1.cta.url...1` could fallback to the translation of `mail.item1.cta.url`

Which I'm going to improve to:
`{{ 'mail_1.item1.cta.url??after_sale_url'|trans }}`

This would solve your issue elegantly with a decorator.
We already "parse" keys when doing plurals. I think this is viable and elegant actually :)

**Comment by odolbeau** [comment]
Another use case I had:

All my pages contains a `meta` tag `property="og:title"`.

The content for this property can be translated.
The rule is **really** simple: if a specific translation exists for this tag, it's used. Otherwise it's the page title which is used.

I ended doing this check in an Extension:
```php
$transKey = "page.$pageName.og_title";

if ($transKey !== $translation = $this->translator->trans($transKey)) {
    return $translation;
}

return $this->getTitle($pageName);
```

As you can imagine it's far from perfect. For example, the profiler always show untranslated keys: this is the case but it's on purpose.

**Comment by javiereguiluz** [comment]
@odolbeau that's a nice and clear example!

With Nicolas proposal, you could this instead in the base Twig template:

```twig
<meta property="og:description"
      content="{{ ('page.'~page.name~'.og_title' ?? 'page.default.og_title')|trans }}">
```

**Comment by odolbeau** [comment]
I like this solution! :+1: 

The real question is: should the implementation lives in my application or directly in the component?
If it's in the component, should it be a decorator or is it a behavior which should be available by default?
If it's a decorator, should it be used by default in Symfony?

**Comment by nicolas-grekas** [comment]
See #35745

**Comment by lyrixx** [comment]
It looks like we can not reach a consensus here + I can live without this feature.
That' why I'm closing it.

Thanks everyone involving in this issue.

**Comment by walva** [comment]
Hello everyone! I wanted to use this feature today, and I end up here.
My app is working a lot with inheritance (everything is Product and Purchase), and regarding the type of purchase, I need to change the translation. Example:

File: email.en.yaml

```yaml
booking_confirmation.subject: Congratulation for your purchase !
booking_confirmation.court_rental.subject: Your %sport% pitch is waiting you !
booking_confirmation.membership.subject: You membership is activated !
booking_confirmation.entrance.subject: Your tickets are ready ! 
booking_confirmation.prepaid_card.subject: You can now book services using your credit at %place% ! 
```

In PHP, I would use this:

```
$subject = $this->translator->trans(
    [
        "booking_confirmation.$type.subject",
        "booking_confirmation.subject"
    ], $params, $locale);
```

And in YAML:

```
{{ [booking_confirmation."~ type ~".subject", "booking_confirmation.subject"]|trans(params) }}
```

Using a **decorator** should be fine, but it needs to accept more than a string for the `$id` parameter.

From : 
```
namespace Symfony\Contracts\Translation;

interface TranslatorInterface
{
    public function trans(string $id, array $parameters = [], string $domain = null, string $locale = null);
}

```
To:

```
namespace Symfony\Contracts\Translation;

interface TranslatorInterface
{
    public function trans(string|string[] $id, array $parameters = [], string $domain = null, string $locale = null);
}
