### ISSUE TITLE
[HttpFoundation] Change visibility of emulateSameSite

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#35460]
For subclassing `Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage` it would be very helpful if the `emulateSameSite` variable would become `protected` instead of `private`.

See https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L55

In my current use case I need to override the `regenerate` method (at least temporarily, for solving https://github.com/symfony/symfony/issues/28577) and to avoid breaking behaviour I need to duplicate the whole variable including everything which reads or writes into it.

**Comment by linaori** [comment]
If this is a temporary workaround, wouldn't it be easier to use reflection at some point to make it accessible?

**Comment by Guite** [comment]
No. Because there may be other use cases for subclasses with partial overriding.
