### ISSUE TITLE
Online info based on specific Symfony versions should be easily searchable

### ISSUE THREAD

**Issue by taylankasap** [symfony/symfony#35470]
**Description**  
Half of the time I research Symfony related stuff I get old (no-longer-valid) info. And I feel like named versions can help (like Android or Ubuntu or macOS etc. does).

**Example**  
Symfony 2: Barbarian
Symfony 3: Cleric
Symfony 4: Druid
Symfony 5: Esper

**Edit**  
This issue is not about named versions. Even if you don't like that idea see title of the issue for the main problem.

**Comment by javiereguiluz** [comment]
Thanks for your proposal.

In my opinion, names are problematic for several reasons:

* It's really hard to find names which are exciting/interesting and also comply with most people's beliefs, opinions, etc.
* It's harder to remember if a version is older than another one. Example: *"this feature was introduced in "Cleric" version. I'm using "Druid" version ... is it included or not?"* vs *"this feature was introduced in 4.0 version ... I'm using 4.2 version, so I'm 100% sure it's included"*.
* 30% of world population (2.3 billion people!) don't use Latin scripts. So "Druid", "Cleric", etc. looks strange to them ... while "4", "5", etc. looks natural (numbers are one of the few things truly universal).

Another reason for keep using numbers is that Symfony follows a common sense scheme (simple numbers, sequential increase, no gaps, no year-based numbering, etc.) so it's super easy to learn and follow it.

About your references (Ubuntu, Android, etc.), in case you are not aware, Android stopped using version numbers in the last version. It's now simply "Android 10", without any other version name.

**Comment by taylankasap** [comment]
Good points about naming the versions. I changed the issue from **naming versions** to **old info**, since that is actually the core issue for me. I don't care about the names themselves. I have another idea, not sure if it is worth the hassle.

What about writing the version number adjacent to the word "Symfony" in **everywhere**?

I mean changing "Symfony 4" to "Symfony4" (and other versions too of course). I admit it looks a little worse but would it help with search engines and website search pages?

I'm also open to any other suggestions since the main issue is old info popping out of nowhere all the time. I know this is not a direct improvement to the Symfony itself. But I feel like something needs to be done about this kind of things (UX?) or we won't gain new users easily.

Note: I changed the title but wording looks weird. Please do recommend a title with better wording.

**Comment by taylankasap** [comment]
Note that I'm not talking about Symfony docs. They are good and relatively easier to find what I'm looking for in them. But when searching for more detailed stuff, no matter how good the documentation is, it won't be able to cover everything. That's where the community (StackOverflow etc.) steps in. And that's what this issue is mostly focused on.

**Comment by xabbuh** [comment]
If we do not talk about named versions, what would you suggest that could be done to make e.g. StackOverflow questions and answers easier discoverable?

**Comment by taylankasap** [comment]
Besides [named versions](https://github.com/symfony/symfony/issues/35470#issue-555068802) and [adjacent version number](https://github.com/symfony/symfony/issues/35470#issuecomment-578397000) I don't have any idea right now.

I'm also interested to hear about this from you (and others) if you experience same issue or is it just me.

**Comment by linaori** [comment]
> Half of the time I research Symfony related stuff I get old (no-longer-valid) info.

Which isn't something Symfony can do about, as these are external posts/websites. Though most of the search results I find, indicate some form of mentioning which Symfony version it is. Dates can also help if posted on these pages.

**Comment by javiereguiluz** [comment]
Let's close this because the proposal didn't gain much support. In any case, @taylankasap thanks for taking the time to submit a proposal for Symfony. We hope you send more in the future. Thanks!
