### ISSUE TITLE
Symfony 4.3: Mailgun Provider incompatible

### ISSUE THREAD

**Issue by alexschwarz89** [symfony/symfony#35491]
**Symfony version(s) affected**: 4.3.x

**Description**  
In Symfony 4.3.x the MAILER_DSN isn't parsed correctly which causes an error on instantiation of MailgunTransport class. Instead of passing the "region" parameter, the HttpClient is passed which causes the fatal error provided in additional context.

As this is already fixed in Symfony 4.4 i just want to help others having this issue with SF 4.3 

**How to reproduce**  
Setup Symfony 4.3 (latest), symfony/mailer and symfony/mailgun-mailer. 
Configure .env and set MAILER_DSN according docs for the HTTP Transport. 
Try to send a mail

**Possible Solution**  
Upgrade to Symfony 4.4 solves the issue as the DSN is parsed correctly.

**Additional context**  

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 3 passed to Symfony\Component\Mailer\Bridge\Mailgun\Http\MailgunTransport::__construct() must be of the type string or null, object given, called in /home/wwwroot/sf4/vendor/symfony/mailer/Transport.php on line 107 in /home/wwwroot/sf4/vendor/symfony/mailgun-mailer/Http/MailgunTransport.php:35
Stack trace:
#0 /home/wwwroot/sf4/vendor/symfony/mailer/Transport.php(107): Symfony\Component\Mailer\Bridge\Mailgun\Http\MailgunTransport->__construct('key-bf7215d6d1a...', 'mail.shopguardi...', Object(Symfony\Component\HttpClient\CurlHttpClient), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Symfony\Component\HttpKernel\Log\Logger))
#1 /home/wwwroot/sf4/vendor/symfony/mailer/Transport.php(58): Symfony\Component\Mailer\Transport::createTransport('http://key-bf72...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Symfony\Component\HttpClient\CurlHttpClient), Object(Symfony\Component\HttpKer in /home/wwwroot/sf4/vendor/symfony/mailgun-mailer/Http/MailgunTransport.php on line 35
`

**Comment by Nyholm** [comment]
Thank you for writing this down and making this issue searchable. 
If I recall correctly, the DSN strings changed a bit between 4.3 and 4.4. 

Do you think this is something that needs fixing? Sf 4.3 goes end of bug fix on Friday and the component was “experimental”. 

Or should we be happy that this is documented here in the issue tracker and just close the issue?

**Comment by alexschwarz89** [comment]
@Nyholm As the upgrade to 4.4 can be easily done i would say just for documentation. Thanks for the quick response!
