### ISSUE TITLE
Changelog update for anonymous comportment in 4.4

### ISSUE THREAD

**Issue by bastnic** [symfony/symfony#35496]
**Symfony version(s) affected**: 4.4

**Description**  
Upgrading from 4.3 to 4.4 with the previous default anonymous config results in losing the htttp cache. This is nowhere documented. 

**How to reproduce**  
I created an API in Symfony 4.3 with [this recipe](https://github.com/symfony/recipes/blob/master/symfony/security-bundle/3.3/config/packages/security.yaml).

https://github.com/symfony/recipes/blob/e9ca0382bedfa3b2c36b44b187b478942aea92ab/symfony/security-bundle/3.3/config/packages/security.yaml#L1-10

Later I upgraded  to 4.4, following [the changelog](https://github.com/symfony/symfony/blob/2837c0e97893b6fd8927384725085d208139d221/CHANGELOG-4.4.md).

As a result I don't have http cache anymore, because the `anonymous: true` [now start the session](https://symfony.com/blog/new-in-symfony-4-4-lazy-firewalls), and so, change the header to `cache-control: max-age=0, must-revalidate, private`.

I should upgrade to `anonymous: lazy`.

By the way, the recipe is now using `anonymous: lazy` in 4.4.

https://github.com/symfony/recipes/blob/e9ca0382bedfa3b2c36b44b187b478942aea92ab/symfony/security-bundle/4.4/config/packages/security.yaml#L10

**Possible Solution**  
Two solutions:
- document this change in `UPGRADE-4.4.md`
- rollback or better handle this changes.

**Additional context**  
One more test to add in my app.

**Comment by wouterj** [comment]
I'm not sure if this is really the case. As far as I know, the behavior of `anonymous: true` isn't changed in 4.4. It always started the session. This is why `anonymous: lazy` is introduced to allow anonymous firewalls that don't start the session.

**Comment by nicolas-grekas** [comment]
Closing as this staled and the behavior is likely correct.
