### ISSUE TITLE
[DependencyInjection] Possible tiny bug with test

### ISSUE THREAD

**Issue by signor-pedro** [symfony/symfony#35505]
**Symfony version(s) affected**: 5.0

**Description**  
There is a test called `testThrowsException...` but it does not `expectException`. 

https://github.com/symfony/dependency-injection/blob/0f495ead513e83d01e4363995c1d6984e2a0f9ed/Tests/ContainerBuilderTest.php#L1100

Either the test is misnamed (should be rather `testNoExceptionWhenAddServiceOnACompiledContainer`) or it might be a false-positive and the exception check was forgotten (improbable).

**Possible Solution**  
Rename the test or add the necessary check.

I assume this is a typo so I renamed the test in my PR.

**Comment by nicolas-grekas** [comment]
For reference, next step found in https://github.com/symfony/symfony/pull/35507#issuecomment-579705167
PR welcomed, for master.

**Comment by fancyweb** [comment]
I think this one can be closed isn'it?
