### ISSUE TITLE
Can't login manually with multiple roles

### ISSUE THREAD

**Issue by VelMrnk** [symfony/symfony#35509]
Yesterday my project moved from 4.3.4 to 4.4.3 and I got a problem. 

I have a piece of code that allows to login as other user without sign out. So admin can login with ROLE_ADMIN first and then login as user and have roles: ROLE_ADMIN, ROLE_OWNER, ROLE_USER.  In result admin will have permissions of admin and user. He can view admin and user pages at the same time.

Listing: 
```
public function loginAsClient(TokenStorageInterface $tokenStorage, User $user)
{
    $user->setRoles(array_unique(array_merge($this->getUser()->getRoles(), $user->getRoles())));

    $token = new UsernamePasswordToken($user, null,  'main', $user->getRoles());
    $tokenStorage->setToken($token);

    $this->get('session')->set('_security_main', serialize($token));
    $this->get('session')->save();

    return $this->redirectToRoute('dashboard_index');
}
```

And everything worked until I did upgrade. Now nothing happens after this action. Just redirection without saving of new roles in a session.

Also, I notices that if do not merge roles, and give just user roles(without ROLE_ADMIN) authentication will work, but now admin will lost admin permissions and logout will be required. 

Has something changed in the new security version or is this type of manual login is deprecated?

**Comment by linaori** [comment]
You should not do anything with the user token directly, let the security component handle this. Perhaps this can help you? https://symfonycasts.com/screencast/symfony-security/registration-auth

**Comment by VelMrnk** [comment]
> You should not do anything with the user token in the session directly, let the security component handle this. Perhaps this can help you? https://symfonycasts.com/screencast/symfony-security/registration-auth

I saw this solution, but looks like I need to mix admin and user roles on a fly, without saving roles to database. So permissions must stores only in a session. Your example load user from a db.

**Comment by linaori** [comment]
Have you tried this feature? https://symfony.com/doc/current/security/impersonating_user.html

**Comment by VelMrnk** [comment]
> Have you tried this feature? https://symfony.com/doc/current/security/impersonating_user.html

Thanks, this is helpful.

**Comment by gorshkov-ag** [comment]
It is because of compare roles update in abstractToken class https://github.com/symfony/symfony/commit/4f4c30d59ed429bc08a34f330c45de2b04059d0a.
Try to extend AbstractToken with custom token and override setUser method to use restricted roles.
Nothing else need to do.
```
public function loginAsClient(TokenStorageInterface $tokenStorage, User $user)
{
    $token = new CustomToken($user, null,  'main', ['ROLE_USER]);
    $tokenStorage->setToken($token);

    return $this->redirectToRoute('dashboard_index');
}
```
