### ISSUE TITLE
User automatically logout after updating their information

### ISSUE THREAD

**Issue by GaylordP** [symfony/symfony#35501]
**Symfony version(s) affected**: 5, 4

**Description**  
1. I create a basic form so that the logged user can update their information.
2. I disable HTML5 validation in order to test the assert.
3. I empty the "username" and "email" information
4. I submit the form, which returns errors to me (because **@NotBlank assert in entity for "username" and "email" = OK**)
5. But since the User object has been modified (_but not persisted in the database because the form returns errors_), **then it is automatically disconnected**

**How to reproduce**  
Controller : 

`

    public function information(Request $request): Response
    {
        $form = $this->createForm(UserType::class, $this->getUser());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Not executed in my situation : @NotBlank asserts on "username" and "email"
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            return $this->redirectToRoute('user_information');
        }

        return $this->render('user/user/information.html.twig', [
            'form' => $form->createView(),
        ]);
    }

`

I don't voluntarily put any other code ... my code is the most basic (Controller, Form, Entity and constraints) :)

**Comment by Nyholm** [comment]
Im not sure I can give you all the answers, but here is a bunch of information you may feel is relevant. =)

On every new request, the firewall reads the session token, takes the serialized user and "refresh it" with some help of UserProviders. [source](https://github.com/symfony/symfony/blob/v5.0.3/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L216-L221)

We use the refreshed user and set it to the token. If you look at [AbstractToken](https://github.com/symfony/symfony/blob/v5.0.3/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L85) you will see that it looks if the user has changed. Ie, the memory user vs the database user. If it has changed, the token will be `authenticated=false`.

-----------

Looking at your code though.. I dont see any issues. Are you sure this is specific to submitting **this** form? Or is it any form? Or is it the second request after login?

**Comment by dmaicher** [comment]
@Nyholm I guess the changed user (with empty email/password) is serialized into the session token at the end of the request?

**Comment by GaylordP** [comment]
Thank you for your answers

In fact, this is a global problem, even though I realized this by testing the @ NotBlank assert on username in a form.

If from a controller, I do:

    public function information(Request $request): Response
    {
        $this->getUser()->SetUserName( '');
    }

The user is logged out ... even if no flush () has taken place.
Symfony considers this normal?

**Comment by Nyholm** [comment]
No. Something weird is going on here that I cannot explain from the given information.

Are you doing some is_granted checks in twig AND have configured the firewall to validate the token every time is_granted is executed?

**Comment by GaylordP** [comment]
I'm sorry but I don't think it comes from my code. I just tested with [Symfony demo](https://github.com/symfony/demo).

If I change this file : 
https://github.com/symfony/demo/blob/master/src/Controller/Admin/BlogController.php :

`

    public function index(PostRepository $posts): Response
    {
        $this->getUser()->setUsername('aaa');
        $authorPosts = $posts->findBy(['author' => $this->getUser()], ['publishedAt' => 'DESC']);

        return $this->render('admin/blog/index.html.twig', ['posts' => $authorPosts]);
    }

`

**User is automatically logged out.**

I think I solved my problem by putting the username and the original email if the form is invalid, with a clone : 

`

    public function information(Request $request): Response
    {
        $cloneUser = clone $this->getUser();
        
        $form = $this->createForm(UserType::class, $this->getUser());
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->flush();

                $this->get('session')->getFlashBag()->add(
                    'success',
                    [
                        'user.information.updated_successfully'
                    ]
                );

                return $this->redirectToRoute('user_information');
            } else {
                $this->getUser()->setUsername($cloneUser->getEmail());
                $this->getUser()->setEmail($cloneUser->getEmail());
            }
        }

        return $this->render('user/user/information.html.twig', [
            'form' => $form->createView(),
        ]);
    }

`

Maybe Symfony will have to look into this, I'm not sure if this is desired behavior or not.

**Comment by linaori** [comment]
> I think I solved my problem by putting the username and the original email if the form is invalid, with a clone

Cloning entities will cause more problems than it solves, I would not advice this. 

> Maybe Symfony will have to look into this, I'm not sure if this is desired behavior or not.

Yes, this is intended behavior.

--

The problem is that you're using `$this->getUser()`, which results in having the entity within your Security token. At the end of the request, this object (and thus the changes you made) are stored in the session. The next request the database entity differs from what's in your session, as those changes are stored in your previous request. 

This is an issue a lot of people are facing and can be solved:
 1. by implementing the `EquatableInterface`, and narrow down what could trigger the "user has changed"
 2. by stop binding your entities to everything

I'd say (2) is the most effective. You can create a read only DTO to use the `UserInterface` on. This will permanently stop you from changing the session user contents. In regards of your form, I'd also advice to not bind your entity, as you might still flush invalid changes by accident _somewhere_ during the life-cycle request.

When using your entity as security user, I believe you will also get the same entity from doctrine as put in your session, due to doctrine already knowing that particular instance.

**Comment by chalasr** [comment]
Closing as explained.
