### ISSUE TITLE
"symfony/translation": composer not found "symfony/contracts" or "symfony/translation-contracts" package

### ISSUE THREAD

**Issue by Axent96** [symfony/symfony#35512]
**Symfony version(s) affected**: 4.4.3

**Description**  
`Warning: Ambiguous class resolution, "Symfony\Contracts\Translation\TranslatorInterface" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/translation-contracts/TranslatorInterface.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Translation/TranslatorInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Translation\LocaleAwareInterface" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/translation-contracts/LocaleAwareInterface.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Translation/LocaleAwareInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Translation\TranslatorTrait" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/translation-contracts/TranslatorTrait.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Translation/TranslatorTrait.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Service\ServiceSubscriberInterface" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/service-contracts/ServiceSubscriberInterface.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Service/ServiceSubscriberInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Service\ResetInterface" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/service-contracts/ResetInterface.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Service/ResetInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Service\ServiceProviderInterface" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/service-contracts/ServiceProviderInterface.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Service/ServiceProviderInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Service\ServiceSubscriberTrait" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/service-contracts/ServiceSubscriberTrait.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Service/ServiceSubscriberTrait.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Service\ServiceLocatorTrait" was found in both "/srv/source/digon-backend/cart-service/vendor/symfony/service-contracts/ServiceLocatorTrait.php" and "/srv/source/digon-backend/cart-service/vendor/symfony/contracts/Service/ServiceLocatorTrait.php", the first will be used.`

**How to reproduce**  
composer require symfony/translation:4.4.3

**Additional context**  
PHP 7.4.2, Composer version 1.9.2

**Comment by ro0NL** [comment]
can you investigate how come both `vendor/symfony/contracts` as `vendor/symfony/translation-contracts` are available? i.e. `composer show`

It should not be possible, given `symfony/contracts` replaces `symfony/translation-contracts`. As such i cannot reproduce:

```bash
$ composer require symfony/translation:4.4.3
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/translation-contracts (v2.0.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.13.1): Loading from cache
  - Installing symfony/translation (v4.4.3): Loading from cache
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
Writing lock file
Generating autoload files

$ ls vendor/symfony/
polyfill-mbstring  translation  translation-contracts
```

**Comment by Axent96** [comment]
Yes, I can approve it, "symfony/translation-contracts" installed but I get the warnings of composer.

PHP 7.4.2, Composer version 1.9.2

I changed title of issue

**Comment by stof** [comment]
Can you run `composer show 'symfony/*` to show us the installed version of all Symfony packages ?

**Comment by Axent96** [comment]
Sorry, it was broken composer process
