### ISSUE TITLE
[Mailer] SMTP transport creates too many NOOP commands

### ISSUE THREAD

**Issue by micheh** [symfony/symfony#35515]
When using the SMTP transport for the Mailer component, it can be difficult to send many emails within the same SMTP session.

The problem is that the transport will ping the server (send a NOOP command) before every email:
https://github.com/symfony/symfony/blob/7ecb5aad8e81a6146c86f0f449fcf754dcec0c14/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php#L163

This is fine if you send only a couple of emails, but may lead to problems when sending more than 10 emails, as SMTP servers usually will drop the connection with too many nonmail commands (like NOOP).

A potential workaround is to call `setRestartThreshold` in order to restart the connection after a specified number of mails was sent (e.g. 10). But maybe it is a better idea to not ping the server before every email?

**Comment by Nyholm** [comment]
Thank you. I think it makes sense to ping it once per ever x seconds. Ie, if we have a long running process that sends one email every hour, we sure want to ping with every email. 

But if we send 100 mails in 10 seconds, then yes, one ping is enough. 

Could one save a local cache when we last pinged? And if we pinged the last 10(?) seconds, then we just ignore it. Is that a good solution?

**Comment by micheh** [comment]
Yes, we could save the time when the last email was sent with the transport and then compare this with the current time before a new email is sent. Only if the difference is above a threshold, the server will be pinged.

However, I think 10 seconds is still way too low. The default timeout is 5 minutes according to [RFC5321](https://tools.ietf.org/html/rfc5321#section-4.5.3.2). With a threshold of only 10 seconds, it is much more likely that the connection will still be dropped due to too many NOOP commands than an actual timeout.

@xabbuh This is a bug, not a feature.
