### ISSUE TITLE
SameSite not supported by Symfony 3.4 LTS on PHP 7.4.2

### ISSUE THREAD

**Issue by jayesbe** [symfony/symfony#35520]
**Symfony version(s) affected**: 3.4.36

**Description**  
Chrome is currently throwing a warning:

`A cookie associated with a cross-site resource at was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure.`

**How to reproduce**  

      session:
          # storage_id: app.dynamic.session.storage
          handler_id: ~
          name: "%session.name%"
          cookie_secure: true
          cookie_httponly: true
          cookie_lifetime: 2630000 # 1-Month
          cookie_samesite: strict

Add the cookie_samesite option. The value does not matter as adding the option results in

`Unrecognized option "cookie_samesite" under "framework.session"`

**Possible Solution**  

**Additional context**  

Symfony 3.4 LTS is still a maintained branch, SameSite is now going into affect in browsers with Chrome expected to deploy soon. I am currently trying to implement this 

https://www.chromium.org/updates/same-site/incompatible-clients

which is supposed to help determine when SameSite is required.  Without Symfony 3.4 LTS support, this isn't possible. 

The application is being deployed to a Ubuntu 18.04 LTS server with PHP 7.4.2.

**Comment by nicolas-grekas** [comment]
Since Symfony 3.4 is in maintenance mode, it means we cannot add features to it.
But I think you can already define the setting using the `session.cookie_samesite` php.ini setting so there is a way to send this attribute if you're using PHP 7.4.

**Comment by jayesbe** [comment]
The value needs to be dynamic though.. I don't understand how a static value in php.ini helps.

**Comment by jayesbe** [comment]
Wait.. can I just use ini_set ? Will try that.

**Comment by nicolas-grekas** [comment]
You can use `ini_set()` at runtime so it can also be dynamic.
The alternative is upgrading to Symfony 4.4 of course.

**Comment by jayesbe** [comment]
Thanks @nicolas-grekas

**Comment by ConneXNL** [comment]
@jeyesbe @fabpot 

I hope I am wrong but I see the impact of not making any changes to Symfony 3.4 will have a tons of sites break if we cannot set the cookie's samesite setting (in the framework session and remember me) before Chrome pushes this update.

Very soon all existing cookies are no longer going to work with cross-domains if you do not specify 'None' for the cookie_samesite. All external APIs that use cookies and are running SF 3.4 will break and devs will have no quick solution to fix their auth process.

If you are using PHP 7.4, yes you can most likely use ini_set to workaround this issue. 

However, ini_set('cookie_samesite') does not work in PHP Version <= 7.2.
I am not even sure PHP 7.3 supports the value 'None' as https://php.watch/articles/PHP-Samesite-cookies says it has support for 'Lax' and 'Scrict'.

This effectively means SF 3.4 on PHP 7.2 (or PHP 7.3) is no longer supported for cross domain APIs with cookies. People would have to either update PHP to 7.4 (if they even can?) or go to Symfony 4 (with a dead live site is going to be a complete disaster).

What am i missing?

**Comment by jayesbe** [comment]
@ConneXNL it does seem like due to the samesite change that php 7.4 is now the minimum.  I finished upgrading my projects over the weekend and deployed this past monday.  I am not sure there is any option for < 7.4

**Comment by nicolas-grekas** [comment]
Please open an issue if you want anything to happen.

**Comment by ConneXNL** [comment]
@nicolas-grekas isn't this supposed to be the issue?

I just elaborated on the issue and tried to make clear why it's important.

**Comment by jayesbe** [comment]
Thanks @ConneXNL for the support on this. 
@nicolas-grekas @fabpot you guys are awesome.
