### ISSUE TITLE
[Finder] - Finder::getIterator()->current() return null

### ISSUE THREAD

**Issue by youssefbenhssaien** [symfony/symfony#35529]
**Symfony version(s) affected**: 4.4.1

**Description**  
The `current()` method of `Symfony\Component\Finder\Iterator\XXXXIterator` return null while `foreach` or `current(iterator_to_array())` return the `SplFileInfo` object.

**How to reproduce**  
```php
    public function getRejectFile(int $fileKey): ?SplFileInfo 
    {
        $iterator = $this->getRejectFilesIteratorByKey($fileKey); // Instance of Symfony\Component\Finder\Iterator\PathFilterIterator

        foreach ($iterator as $file) return $file; // Return SplFileInfo

        return current(iterator_to_array($iterator)); / Return SplFileInfo

        return $iterator->current(); // Return null
    }

    public function getRejectFilesIteratorByKey(int $fileKey): \Iterator
    {
        $finder = Finder::create()->in($this->rejectsDir);

        return $finder->name(sprintf('%d_*.csv', $fileKey))->files()->getIterator();
    }
```

**Comment by stof** [comment]
Well, `->current()` return `null` when the iterator is not in a valid state (check `->valid()`). A `foreach` loop is not only calling `current`. It rewinds the iterator first, and then check for `valid` during iteration to decide whether the loop is ended. I suspect that your issue is a misunderstanding of the `Iterator` interface of PHP.

**Comment by youssefbenhssaien** [comment]
This is exactly what is missing, calling `$iterator->rewind()` before `return $iterator;`

I created a small pull request https://github.com/symfony/symfony/pull/35543

**Comment by youssefbenhssaien** [comment]
Maybe calling `rewind` is not a good idea here since `getIterator()` is not responsible for rewind process and the caller statement may work on this iterator before looping over it, so I may close this issue and the pul request too.

**Comment by stof** [comment]
rewinding the iterator is part of *using* it, not of creating it. The Finder component should **not** rewind it automatically.

**Comment by youssefbenhssaien** [comment]
I'm closing this issue since is not the logical behaviour behind getIterator() to use current()
