### ISSUE TITLE
[Form] Methods in classes implementing ChoiceListFactoryInterface have invalid declarations

### ISSUE THREAD

**Issue by Tetragramat** [symfony/symfony#35524]
**Symfony version(s) affected**: 5.0.3

**Description**  

> PHP Fatal error:  Declaration of Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator::createListFromChoices(iterable $choices, $value = NULL) must be compatible with Symfony\Component\Form\ChoiceList\Factory\ChoiceListFactoryInterface::createListFromChoices(iterable $choices, ?callable $value = NULL) in /home/www/app/vendor/symfony/form/ChoiceList/Factory/CachingFactoryDecorator.php on line 24

**How to reproduce**  
Run any (even empty) phpunit test which extends `Symfony\Component\Form\Test\TypeTestCase`

Example:
```
<?php

namespace App\Tests;

use Symfony\Component\Form\Test\TypeTestCase;

class FormTest extends extends TypeTestCase
{
    public function testEmpty() {}
}
```

**Comment by xabbuh** [comment]
Please make sure to run your application using PHP 7.2 or higher (see https://3v4l.org/AF7Fn). I am closing here as there is nothing to fix. Thank you for understanding.
