### ISSUE TITLE
[RFC] [Console] [Lock] Locking a command on multiple servers

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#35535]
**Description**  

Hi,

RFC issue related to https://symfony.com/doc/master/console/lockable_trait.html, and the sentence `the same command in a single server`

I want to know if this console lock feature can be extended/improved to have a `multiple server` feature?

Using for example pdo lock or redis one.

Thank you,

**Comment by stof** [comment]
Well, use the Lock component directly for that. It is able to do that. But locks shared between servers require a shared storage (a Redis server for instance), so this cannot be implemented in the LockableTrait which hides the details of using the Lock component.

**Comment by noniagriconomie** [comment]
@stof thx for the fast answer :)

yes my request was mainly to put the pdo lock in this trait, inside the symfony core
99% of the project do have a database

to avoid relying on a devland implementation
wdyt, is it reasonable?

**Comment by stof** [comment]
We cannot put the PDO lock in the trait.
The trait instantiates the lock store and the lock factory internally to hide the usage of the lock component in an easy-to-use API for commands. But that means it can only use stores which require no dependency.

As soon as you want to use a lock factory injected through dependency injection (to be able to use the pdo store configured by FrameworkBundle), the trait is useless. All the remaining logic is already encapsulated in the lock component itself: https://symfony.com/doc/master/components/lock.html#usage

And making the trait itself support injecting a factory inside it would make it more complex.

**Comment by noniagriconomie** [comment]
@stof ok i see your point now, I will duplicate such trait to my devland code then and leveraging the pdo lock feature instead

thank you again for your time

(closed)
