### ISSUE TITLE
[Notifier] Rename/Change AdminRecipient class

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#35558]
While testing out the new Notifier component to write some docs about it (ref symfony/symfony-docs#13025), I've found the `AdminRecipient` classname a bit confusing. It makes sense when purely looking at it from an error notification perspective. 

However, I think the Notifier component shines in being able to sent any kind of notification to any kind of transport.

I would propose to merge this with `Recipient`, so the base class can have both email or phone:

```php
$recipient = (new Recipient())->phone(...);
$recipient = (new Recipient())->email(...);
$recipient = (new Recipient())
    ->phone(...)
    ->email(...)
;
```

**Comment by fabpot** [comment]
Let's close the issue and continue the discussion on the PR instead.
