### ISSUE TITLE
[String] Add preserve parameter to truncate method

### ISSUE THREAD

**Issue by franmomu** [symfony/symfony#35567]
**Description**  

I was trying to replace [the `truncate` filter from `twig/extensions`](https://github.com/twigphp/Twig-extensions/blob/master/src/TextExtension.php#L36) with the new `u` filter, but it looks like [`u.truncate` doesn’t have a `preserve` option](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/String/AbstractString.php#L625), is there a way to achieve the same thing? If not, I could add the parameter to the `truncate` method.

**Example**  

With `twig/extensions`:
```twig
{{ "Hello World!"|truncate(7, true) }} // Hello World!
```
With `u` filter:
```twig
{{ "Hello World!"|u.truncate(7) }} // Hello W
```

**Comment by OskarStark** [comment]
Friendly ping here @nicolas-grekas. Could you leave your 2 cents here if we should provide a PR or if we should do copy paste in the lib? Thanks 🙏

**Comment by nicolas-grekas** [comment]
Please open an issue and/or a PR on Symfony.
