### ISSUE TITLE
[ErrorHandler] Logger regression

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#35569]
**Symfony version(s) affected**: 4.4
**Description**  

In https://github.com/symfony/symfony/pull/24244/commits/03cd9e553b26008707b82388f41910c49cbb9f7f i tweaked the webprofiler to not show the "Logs" tab in the exception panel, as it has a dedicated panel.

Currently it's shown again

![image](https://user-images.githubusercontent.com/1047696/73640100-fab88e00-466d-11ea-9abe-fd4a72d1b31e.png)

**Comment by ro0NL** [comment]
In the frontend it's

![image](https://user-images.githubusercontent.com/1047696/73640991-91d21580-466f-11ea-990e-4eb8efa811c2.png)

the broken output is due an unescape json_encode call.

cc @yceruto

**Comment by yceruto** [comment]
@ro0NL the logs tab is currenly hidden if unavailable like in https://github.com/symfony/symfony/commit/03cd9e553b26008707b82388f41910c49cbb9f7f

https://github.com/symfony/symfony/blob/ed7bb826fbe5ca91d61c7a5b8641f0b2c3ecf29d/src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php#L65-L82

about https://github.com/symfony/symfony/issues/35569#issuecomment-581317792, where does this "unescaped json_encode call" comes from?

**Comment by ro0NL** [comment]
the wrongful output comes from

https://github.com/symfony/symfony/blob/ed7bb826fbe5ca91d61c7a5b8641f0b2c3ecf29d/src/Symfony/Component/ErrorHandler/Resources/views/logs.html.php#L38

for the regression, i think somehow we have a logger instance now ... this wasnt the case before (hence the full tab hidden).

Also, AFAIK, we should never see collected data from the profiler itself, within the profiler GUI. I.e. `matched route _profiler` is a bug.

**Comment by ro0NL** [comment]
another weird thing i found today (it still happens in 5.1.5)

![image](https://user-images.githubusercontent.com/1047696/93897655-9dec0f80-fcf2-11ea-9531-2567d911eb5e.png)

**Comment by stof** [comment]
this looks like missing HTML escaping (and Xdebug having HTML in the messages makes that clear). The culprit is the line you linked in your previous comment. PHP templates don't have auto-escaping.

**Comment by ro0NL** [comment]
the JSON syntax erorr and  `context.xdebug_message` in logs is related to xdebug being enabled, disabling it these issues dissapear. However i'd expect SF to avoid HTML injection generally :thinking: 

regardless of xdebug, the profiler keeps a logger instance ... meaning it has an unexpected logs tab in the exception panel.

the unescaped `context.xdebug_message` in logs also

**Comment by ro0NL** [comment]
@stof yes escaping the json_encode output solves first 2 issues :+1: ill make  a PR.
