### ISSUE TITLE
[EventDispatcher] EventSubscriberInterface::getSubscribedEvents() cannot be dynamic

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#35579]
**Symfony version(s) affected**: 3.3 and up.

**Description** 
Currently, `RegisterListenersPass` call `EventSubscriberInterface::getSubscribedEvents()` and map each event to a clear `EventDispatcherInterface::addListener()`. It was potentially done as a performance optimization.
Therefore, subscribed events cannot be dynamic in a `EventSubscriberInterface`. I cannot find reference if it is intended or not.

**Event subscribers in error**
On Symfony 4.4:
- `DebugHandlersListener` uses `PHP_SAPI` to choose if it should subscribe to `ConsoleEvents::COMMAND`. `DebugHandlersListener::configure()`is therefore not called during a console command if the container was compiled by an HTTP request. Bad.
- `Flex` checks if it is active through a static. Very bad. But I don't know Flex well enough to say if it is a problem in a normal flow.
- `DumpListener` checks if a ConsoleEvents exists. Acceptable. Container should be recompiled if a new composer package is installed.
- `DispatchPcntlSignalListener` and `StopWorkerOnSigtermSignalListener` check if a pcntl function is available. Acceptable. If PHP extensions or environment changes, container recompilation could be developper responsability.

**Possible Solution**
Either fully allows dynamic subscribers or fully disallows it. Both would require a documentation update and a fix to either of the issues described above.

**Comment by alex-dev** [comment]
I am willing to work on it. Just need to know which behavior we want.

**Comment by nicolas-grekas** [comment]
Bad, very bad or fine to you isn't a description of a problem.
If you have an actual real world use case, please explain it and others might want to help.
Right now there's nothing to work on here, at least nothing I understand.

**Comment by alex-dev** [comment]
> DebugHandlersListener::configure()is therefore not called during a console command if the container was compiled by an HTTP request.

Error logs are not handled by configured logger (such as Monolog's) injected to `DebugHandlersListener` but by ErrorHandler default BootstrappingLogger.
That's a problem in a real world use case. I don't receive mail in prod when crons error out.

Everything else are other potential errors depending on their exact use cases.

**Comment by nicolas-grekas** [comment]
> DebugHandlersListener::configure()is therefore not called during a console command if the container was compiled by an HTTP request.

that's a good catch, this should be fixed!

**Comment by alex-dev** [comment]
No problem.. I'd just advise to state clearly in doc whether `EventSubscriberInterface::getSubscribedEvents()` should be compile-time or if it can be dynamic. Then I could fix code accordingly.

**Comment by xabbuh** [comment]
If you use the EventDispatcher component in framework-context, event listeners are wired during container compilation. From the code side that's the expected behaviour and there is nothing to be changed. If you feel like some docs could be improved, please feel free to submit a pull request. :) Therefore, I am closing here.

**Comment by nicolas-grekas** [comment]
The issue with the registration of `DebugHandlersListener` is fixed in https://github.com/symfony/symfony/pull/35718
