### ISSUE TITLE
[Router or HttpFoundation] allow request scheme to be overwritten in parameters

### ISSUE THREAD

**Issue by Matts** [symfony/symfony#35585]
**Description**  
I make use of the router to generate URL's to be displayed in emails, and also to create redirect URL's to be displayed in a IFrame. This, however, causes issues when running behind a reverse proxy to add a https certificate.

The application thinks it is running on HTTP as all requests come in as :80.

It would be a nice addition to be able to overwrite the result of request::getScheme

**Example**  
![image](https://user-images.githubusercontent.com/3371705/73726883-a1fdf980-4730-11ea-9091-a06957efe1f2.png)

Used in RequestContext::fromRequest
![image](https://user-images.githubusercontent.com/3371705/73726907-af1ae880-4730-11ea-861b-97b2abd11df4.png)

Used in URLGenerator
![image](https://user-images.githubusercontent.com/3371705/73726964-d2459800-4730-11ea-9bb1-c20e714980e6.png)

**Comment by lyrixx** [comment]
Hello. 

Did you tried to [configure symfony to work with proxies](https://symfony.com/doc/current/deployment/proxies.html)  ?

And if you are sending email with CLI, you can read this [doc](https://symfony.com/doc/2.6/cookbook/console/sending_emails.html)

**Comment by Matts** [comment]
@lyrixx thanks for triggering me on that. I didn't notice that my proxy configuration already set the X_FORWARDED_PROTO. 

It was just a case of trusting the host and it worked :D 👍
