### ISSUE TITLE
Composer install can not resolve dependencies if .git directory removed

### ISSUE THREAD

**Issue by denormalizer** [symfony/symfony#35618]
**Symfony version(s) affected**: v4.4.4 (also tested on v5.0.4)

**Description**  
After `.git` directory is removed `composer install` could not resolve dependencies.

There is nothing in composer.json (as far as I can tell) that says there is dependency on git/vcs

**How to reproduce**  

    git clone https://github.com/symfony/framework-bundle.git
    cd framework-bundle
    git checkout -f v4.4.4
    rm -rf .git/    <-- Remove DIR -->
    composer install

Output:

> Your requirements could not be resolved to an installable set of packages.

    Problem 1
      - symfony/twig-bundle 4.4.x-dev conflicts with symfony/framework-bundle[No version set (parsed as 1.0.0)].
      - symfony/twig-bundle 5.0.x-dev conflicts with symfony/framework-bundle[No version set (parsed as 1.0.0)].
      - ...

**Possible Solution**  
n/a

**Additional context**  

Env1:
* Ubuntu 18.04 (WSL)
* PHP 7.2

Env2
* CentOS 7.7
* PHP 7.3

**Comment by ro0NL** [comment]
Why do you want to remove the .git folder when cloning from source?

**Comment by denormalizer** [comment]
My use case is that I don't want to push the .git dir to production because often it is too "heavy"

**Comment by ro0NL** [comment]
The link clarfies why there's no `version` defined in composer.json

Not sure i understand the setup, but `symfony/framework-bundle` would be a dependency of your project no? I.e. you'd never install the dependencies from `symfony/framework-bundle` itself on prod :thinking:

**Comment by ro0NL** [comment]
E.g. using the regular `composer require symfony/framework-bundle:v4.4.4` in your project ... chances are composer will install from dist if possible. Then there's no .git folder in `vendor/symfony/framework-bundle`

**Comment by nicolas-grekas** [comment]
Run composer install --prefer-dist from your project if you don't want .git in your vendor directory.

I'm closing because we use this repo for development of the code, please use other channels for support, eg Symfony's Slack.

**Comment by denormalizer** [comment]
Sorry, I'm using this wrong. I'm confusing this with symfony/framework-standard-edition - which is no longer used in symfony 4
