### ISSUE TITLE
Validator Component need an instance of Constraint class, when that one is abstract.

### ISSUE THREAD

**Issue by lionelkimbs** [symfony/symfony#35652]
**Symfony version(s) affected**: 4.4.*

**Description**  
There is a "non sense" in the Validator Component. Symfony\\Component\\Validator\\Mapping\\GenericMetadata::addConstraint() must be an **instance** of Symfony\\Component\\Validator\\Constraint, when that class is an **abstract** class.

**How to reproduce**  
I suppose I have a ValidatorInterface on my code. If i try to do this : 
`$this->validator->validate($entity->getAnyField(), new Constraint() );`

**Possible Solution**  
Not sure, but maybe Constraint class need to not be an abstract class.
Thank you.

**Comment by Tobion** [comment]
The constrait class is abstract because it must be extended like all the existing contraints there are.

For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
