### ISSUE TITLE
[Security][DX] Make ldap user provider extensible

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#35650]
**Description**  
I think the [LdapUserProvider](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Security/LdapUserProvider.php) is a good thing to have inside Symfony. The problem is that every LDAP configuration is so different that the standard behavior of the LdapUserProvider is often not enough. The class is not final, which means we could possibly extend it. But its design (everything private, no method you can redefine, returning a standard Sf User) makes everything complicated.

Actually, for now, the LdapUserProvider looks like something you should copy/paste and then modify to fit your needs, while it actually provides interesting code and its copy/pasting could be avoid.

I suggest creating methods inside the class, making them protected, as well as most of the attributes. I also think having an LDAP user instead of a simple User would be great. WDYT?

**Comment by OskarStark** [comment]
@Simperfit what do you think? ✌🏻

**Comment by chalasr** [comment]
As for almost any core service, we recommend decorating instead of extending. And yes, the provider class itself is very straightforward. 

We can expose some methods to improve reusability, preferably by adding a trait or more public methods in the class itself (which could then be made final in both cases).

Can you be more precise about the use case(s) into which you faced this situation so we can identify the feature scope?
Making everything protected is a no-go.

**Comment by Nek-** [comment]
I agree without a ldap in hands to work with what I say may be a little bit too much abstract.

So here is an example ([sorry for long post](https://files.nekland.fr/potato/sorry-long-post.webp)). Let's consider this fixtures:

```php
class UserFixtures extends Fixture
{
    public function __construct(Ldap $ldap, LdapEncoder $encoder)
    {
        $this->encoder      = $encoder;
        $this->ldap         = $ldap;
    }

    public function load(ObjectManager $manager)
    {
        $this->ldap->bind('cn=admin,' . $this->getBaseDn(), 's3cr3tpassw0rd');

        $definedQuery = $this->getUsersDn();
        $entryManager = $this->ldap->getEntryManager();

        $ou = new Entry($definedQuery, [
            'objectClass' => ['organizationalUnit'],
            'ou' => ['People']
        ]);
        $entryManager->add($ou);
        $entryManager->add(ew Entry(sprintf($this->getUserDn($username), $username), [
            'objectClass' => [
                'inetOrgPerson',
            ],
            'sn'  => [$username],
            'uid' => [$username],
            'cn'  => ['LastName'],
            'gn'    => ['FirstName'],
            'userPassword' => [$this->encoder->encodePassword('password', null)]
        ]));
    }
}
```

I want to persist users in my app. It's not that complicated because decorating the LdapUserProvider here is completely ok:

```php
use Symfony\Component\Security\Core\User\LdapUserProvider;
class CustomLdapUserProvider implements UserProviderInterface
{
    /** @var LdapUserProvider */
    private $decoratedProvider;

    /** @var UserRepository */
    private $users;

    public function __construct(UserRepository $users, LdapUserProvider $decorated)
    {
        $this->decoratedProvider = $decorated;
        $this->users = $users;
    }

    public function loadUserByUsername($username)
    {
        $ldapUser = $this->decoratedProvider->loadUserByUsername($username);

        // Try to find an existent user in the db
        if (null === $user = $this->users->findOneBy(['username' => $username])) {
            // Create unknown user
            $user = new User($ldapUser->getUsername(), User::ROLE_USER);
            $this->users->save($user);
        }

        return $user;
    }

    // ...
}
```

But my user entity also contains firstName and lastName fields... Which are not retrieved by the default LdapUserProvider (besides it's (kinda) standard to use `gn` and `cn` for that purpose). Here are solutions I see with the current implementation of the LdapUserProvider:
- Copy/pasting the whole code and adding mine (also returning another kind of user and maybe removing the custom ldap provider that I write before)
- Adding a new decorator that calls ldap again with same query (stupid but working)

But what looks best here would be to be able to extend the LdapUserProvider to me.

------------------------------------------

> Making everything protected is a no-go.

Understandable, adding `final` keyword should be considered then, it would indicate the way of working with this provider.

**Comment by Nek-** [comment]
Closing; it's not necessary anymore because Sf 4.4 introduced the LdapUser (missed that one feature!)

Sorry guys.
