### ISSUE TITLE
DOM Crawler v4.4.4 commented method arguments

### ISSUE THREAD

**Issue by Sybio** [symfony/symfony#35664]
**DOM crawler affected**: v4.4.4

**Description**  
Arguments of method Crawler::text() are commented and so ignored.

**Possible Solution**  
Uncomment.

**Additional context**  
https://github.com/symfony/dom-crawler/blob/b66fe8ccc850ea11c4cd31677706c1219768bea1/Crawler.php#L605

**Comment by lyrixx** [comment]
Hello. Thanks for for issue. But This is done on purpose.

We do that when we will add an argument in the next major version.
We can not add a new argument to the current version because it would break the BC.

However, you can use theses argument. They do are supported
