### ISSUE TITLE
Typed property Proxies\__CG__\App\Entity\Account\Company::$childCompanies must not be accessed before initialization (in __sleep)

### ISSUE THREAD

**Issue by dompie** [symfony/symfony#35660]
**Symfony version(s) affected**: 5.0.4

**Description**  
A typed property on an Entity with PHP7.4 and strict_types=1 that is initialized *only* in the constructor can not be serialized by the ContextListener

**How to reproduce**  
I see the same error message on my objects that have a not nullable object property that is *only* initialized in the constructor():
```php
<?php
declare(strict_types=1);

//namespace and so on...

/**
 * @ORM\Entity()
 */
class Company
{
    use UuidIdentity;
    /**
     * @ORM\OneToMany(targetEntity="Company", mappedBy="parentCompany")
     */
    protected Collection $childCompanies;
//...snip
    public function __construct() {
        $this->childCompanies = new ArrayCollection();
    }
//...snip
```
Although the property is initialized in the constructor, it can not be serialized by the firewall component.
I have many other places in my code that throw such error. My best solution until now was to set and initialize them as nullable:
```php
    protected ?Collection $someValue = null;
```
This will prevent the error from being thrown, but you have to make properties nullable that should not be nullable.

**Possible Solution**  
I did read somewhere that it might help to add a custom `Company::_sleep()` function that does not return uninitialized properties. Although I do not really understand why the `childCompanies` property is considered as uninitialized.

**Additional context**  
Stack trace:
```
Error:
Typed property Proxies\__CG__\App\Entity\Account\Company::$childCompanies must not be accessed before initialization (in __sleep)

  at vendor/symfony/security-http/Firewall/ContextListener.php:178
  at serialize()
     (vendor/symfony/security-http/Firewall/ContextListener.php:178)
  at Symfony\Component\Security\Http\Firewall\ContextListener->onKernelResponse()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:178)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (vendor/symfony/http-kernel/HttpKernel.php:124)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:191)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:25) 
```

**Comment by dompie** [comment]
I did some research and found a related doctrine issue:
https://github.com/Ocramius/GeneratedHydrator/issues/118
Don't know if this affects the `serialize` call in the `ContextListener`.

**Comment by skalpa** [comment]
This is not a Symfony issue, it is an issue with the proxies generated by Doctrine.

Your main `User` class, that the security component tries to serialize, must have a lazy relationship to the `Company` class. Therefore Doctrine replaces the Company with a proxy, and the problem arises when the proxy gets serialized.

You need to add `__serialize()` / `__unserialize()` methods (that's the recommended way to customize the PHP serialization on PHP 7.4+) to your **User** class (not the Company) and make sure the relationship to Company is not serialized. The security component will reload the User from the DB during subsequent requests, so you only need to serialize the fields that make the identifier.

```php
class User
{
    private Company $company;

    public function __serialize(): array
    {
        return ['id' => $this->getId()];
    }
    public function __unserialize(array $data): void
    {
        $this->id = $data['id'];
    }
}
```

**Comment by Amunak** [comment]
This also applies to Sf 4.4 and really every version that supports PHP 7.4

**Comment by greedyivan** [comment]
Do not use `private` properties in entities: [Projects/ORM/Documentation/Architecture#Serializing entities](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/architecture.html#serializing-entities). Doctrine does not support that.

The described bug was fixed in 2.12.0 (https://github.com/doctrine/common/pull/882)

**Comment by dompie** [comment]
Hi @skalpa,
thanks for the hint, but I have also the same error on other properties, that is not a relation-only issue:
```
    /**
     * @ORM\Column(type="datetimetz")
     */
    protected \DateTime $createdAt;

    public function __construct()
    {
       //...more initialization
        $this->createdAt = new \DateTime();
    }
```
When I implement the serialize/unserialize functions that you suggest, I can not authenticate. The `stateless=false` firewall somehow looses the user roles and inherited roles.

**Comment by stof** [comment]
Well, the serialize function need to return a bit more than just the id. Properties used as part of the `hasUserChanged` check must be included too: https://github.com/symfony/symfony/blob/b3b368b80033e16448601fd565aca6140030e53e/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L255-L287

**Comment by dompie** [comment]
@stof, thanks, now it works :+1:

**Comment by xabbuh** [comment]
Let's close then. Thank you.
