### ISSUE TITLE
More completed glob support

### ISSUE THREAD

**Issue by blry** [symfony/symfony#35679]
**Description**  
In documentation said (https://symfony.com/doc/current/service_container.html):
The value of the resource and exclude options can be any valid glob pattern. 

I was working with services.yml and found out that glob patterns are not completely supported.
I tried to use **!, |, (), +** - these all symbols are not working as expected.

See https://en.wikipedia.org/wiki/Glob_(programming)

Symfony\Component\Finder\Glob::toRegex just escapes all these symbols.

Propose to improve the class, so symbols like **!, |, (), +** will work as expected

**Example**  
services.yml:

>     App\:
>         resource: '../src/*'
>         exclude: '../src/{Domain/**/!(*Service|*Interface).php,DependencyInjection,Migrations,Tests,Kernel.php}'

**Comment by stof** [comment]
The `!` symbol does **not** have the feature that you seem to expect it, according to the wikipedia article that you linked yourselves.

what seems to be missing compared to the wikipedia article is support for `[...]` (and then the extension of `!` inside this operator)

**Comment by nicolas-grekas** [comment]
As demonstrated recently, `glob()` is performance critical. We cannot "improve" it as its a native function, and any userland variant is going to be too slow.

**Comment by stof** [comment]
And `|` and `[)` are not special chars at all in globs. But the Finder `Glog::toRegex` util supports brace expansion.

**Comment by blry** [comment]
Hi @nicolas-grekas , I talked regarding the symfony's extension Glob::toRegex which is used in services.yml.
Do you think it can became slower if we just unescape **()**; **|** and convert **!** to regex **^** symbol? Actually these symbols are not used in class names / namespaces. If someone use them, probably they don't expect these symbols to be escaped.

Hi @stof , you're right, I just verified the link from wiki and found out that there're many different implementations. Personally, I used https://globster.xyz/ to debug my Globs.
It can work with many different pattern types: ?, *, /, **, {a,b}, ?(a|b), *(a|b), +(a|b), @(a|b), !(a|b)
I thought Symfony will convert such glob patterns to regex, however found out that many symbols are escaped.

**Comment by nicolas-grekas** [comment]
Yes, I'm talking about the same.
Finder is used only as a fallback.
The most common path doesn't use it, but uses the native glob() function instead.

**Comment by blry** [comment]
@nicolas-grekas yeah, the most common path uses only native glob() function. Symfony\Component\Config\Resource\**GlobResource** which is used inside symfony/dependency-injection begins with native  **glob()** function, then extended version from Symfony\Component\Finder\**Glob::toRegex**.

I have also noticed that **Glob::toRegex()** converts **{a,b}** to regex (a|b)
(see https://github.com/symfony/finder/blob/master/Glob.php#L83)

However **!** is not converted anyway, it's just escaped. I created PR for this please take a look :)
@nicolas-grekas @stof @xabbuh 

https://github.com/symfony/finder/pull/8
