### ISSUE TITLE
[Finder] Unable to scan root in unix like systems.

### ISSUE THREAD

**Issue by xandros15** [symfony/symfony#35683]
**Symfony version(s) affected**: 5.0.4 and 4.4.4 and maybe others.

**Description**  
When i use `'/'` or `['/']` as parametr in method `Finder::in`, got exception during iteration: `Directory name must not be empty. In line 48 /vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php`. 

**How to reproduce**
(code should works of unix like systems)
```php
use Symfony\Component\Finder\Finder;

$finder = new Finder();
$finder->in('/');
foreach($finder as $item){
}
```

**Comment by dompie** [comment]
I can confirm the behaviour for Symfony 5.0.4 (did not try other version).
A single `/` is [normalized away in this function](https://github.com/symfony/symfony/blob/31fb219896685632d42d2eaf540ee34317946473/src/Symfony/Component/Finder/Finder.php#L783). Therefore the native PHP \RecursiveDirectorySeparator gets an [empty string passed in `Symfony\Component\Finder\Iterator\RecursiveDirectorySeparator`](https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php#L48)

Maybe you can workaround it by using something like `/home/../` for now ?
