### ISSUE TITLE
[VarDumper] dumping DateTime instance with additionnel properties

### ISSUE THREAD

**Issue by Veridis** [symfony/symfony#35699]
**Description**  

The VarDumper component is shipped with a [DateCaster](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/DateCaster.php) class that cast `DateTimeInterface` objects.
When dumping a child class of `DateTime` with additional properties, those properties will not be displayed.

**Example**  

I recently worked with [azuyalabs/yasumi](https://github.com/azuyalabs/yasumi) which introduce a [Holiday](https://github.com/azuyalabs/yasumi/blob/develop/src/Yasumi/Holiday.php) class extending `DateTime`. 
Here's the result when I dump a `Holiday` instance:

![Capture d’écran 2020-02-12 à 17 59 31](https://user-images.githubusercontent.com/4425529/74429068-885c6080-4e5a-11ea-9899-91e593a88ade.png)

I've started on a PR to have the following result:

![Capture d’écran 2020-02-12 à 17 59 41](https://user-images.githubusercontent.com/4425529/74429097-9316f580-4e5a-11ea-8711-9d14f133164b.png)

But before submitting it, I would like to know if hiding child properties is intended ?

**Comment by nicolas-grekas** [comment]
Hi, thanks for the report.
Hiding properties is not intended, we're looking forward to your PR :)
