### ISSUE TITLE
Error thrown when using an entity named "File" and trying to render it with bootstrap_4_layout.html.twig form theme

### ISSUE THREAD

**Issue by petitj** [symfony/symfony#35695]
**Symfony version(s) affected**: 4.4.4

**Description**  
The following error is thrown when using an entity named "File" and trying to render it with bootstrap_4_layout.html.twig form theme. This problem does not happen with default and foundation themes. 

> Twig\Error\RuntimeError:
> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class App\Entity\File could not be converted to string").
> 
>   at vendor/symfony/twig-bridge/Resources/views/Form/form_div_layout.html.twig:17
>   at Twig\Template->displayBlock('form_widget_simple', array('value' => object(File), 'attr' => array('class' => 'custom-file-input'), 'form' => object(FormView), 'id' => 'file', 'name' => 'file', 'full_name' => 'file', 'disabled' => false, 'label' => null, 'label_format' => null, 'multipart' => false, 'block_prefixes' => array('form', 'file', '_file'), 'unique_block_prefix' => '_file', 'row_attr' => array(), 'translation_domain' => null, 'label_translation_parameters' => array()...

**How to reproduce**  
I made a bug reproducer there : https://github.com/petitj/twig-bug-reproducer
When pulled and dependencies installed, you just need to launch the symfony server and point to http://127.0.0.1:8000/

**Comment by fancyweb** [comment]
Status: works for me

You use a custom `FileType` form type. By default, the block prefix of your custom form type is `file` (it's related to the name of the class). When the form view is rendered, the form theme `file_widget` block is used but it is not compatible with your custom form type (it is supposed to be used for the core `FileType` form type). See https://symfony.com/doc/current/form/create_custom_field_type.html#creating-the-form-type-template and https://symfony.com/doc/current/form/form_themes.html#form-fragment-naming.

**Comment by xabbuh** [comment]
The issue actually is that your form type is named `FileType`. The then automatically picked up block prefix is `file` which interferes with the blocks for the built-in `FileType`. You can fix that by implementing the `getBlockPrefix()` method (see #16899 for some more background information on why that's necessary). I am closing here as there is nothing we can do in the core about it. Thank you for understanding.

**Comment by xabbuh** [comment]
see also #28217

**Comment by petitj** [comment]
Thanks a lot for your answers ! I suspected something like that but i'm pretty new to symfony so was a bit lost and my searches didn't get me to that part of the documentation.
I hope i didn't waste too much of your time.
Thanks again :)
