### ISSUE TITLE
[Lock] The redis store forces a TTL on the key even when there is no TTL

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#35725]
Reproducer:

```php
<?php

use Symfony\Component\Lock\Key;
use Symfony\Component\Lock\Lock;
use Symfony\Component\Lock\Store\RedisStore;

require __DIR__.'/vendor/autoload.php';

$redis = new Redis();
$redis->connect('172.17.0.2');

$store = new RedisStore($redis);
$key = new Key('test-lock');
$lock = new Lock($key, $store);
$lock->acquire();

sleep(100);
```

Then, When I check the key:

```
172.17.0.2:6379> TTL test-lock
(integer) 297
```

---

As you can see, I did not set a TLL, but the key got a TTL on it 

Related code:

https://github.com/symfony/symfony/blob/f46ab58bcff6305331678892c3b4f9f3cf34a15d/src/Symfony/Component/Lock/Store/RedisStore.php#L60-L68

**Comment by jderusse** [comment]
Redis Store have a default TTL to 300 sec: https://github.com/symfony/symfony/blob/c6cf433589ead18e8390ecaa1fa4915ff553843e/src/Symfony/Component/Lock/Store/RedisStore.php#L38

Remote stores (redis, memcached, Doctrine) have all a default TTL to avoid zombi lock in case of fatal failure.

**Comment by lyrixx** [comment]
I understand the reason, but it is actually wrong.

But I don't need this feature anymore, so feel free to close this issue

**Comment by jderusse** [comment]
Closing for above reason. Redis store **requires** TTL
