### ISSUE TITLE
WebProfilerBundle console addEventListener error

### ISSUE THREAD

**Issue by keshancs** [symfony/symfony#35739]
**Symfony version(s) affected**: 5.0.*

**Description**  
It appears that in WebProfilerBundle [base_js.html.twig](https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Profiler/base_js.html.twig#L509) addEventListener is being added to ".sf-toolbar-block-ajax" which does not exist, as a result there is a console error.

**How to reproduce**  
By installing the profiler-pack for 5.0.*

**Possible Solution**  
If this element is needed, easy work around is to check whether the element exists or not, but as of right now, because the element does not exist, a more correct way would be to remove those 2 addEventListener calls.

**Additional context**  
![error](https://user-images.githubusercontent.com/9093609/74603323-e8514200-50ba-11ea-9bb2-1b06eb674ff6.jpg)

**Comment by chr-hertel** [comment]
cannot reproduce by installing profiler-pack in fresh skeleton or website-skeleton. could you please add some additional information about your project/setup?

**Comment by keshancs** [comment]
> cannot reproduce by installing profiler-pack in fresh skeleton or website-skeleton. could you please add some additional information about your project/setup?

**composer.json**
```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "gedmo/doctrine-extensions": "^2.4",
        "liip/imagine-bundle": "^2.3",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "5.0.*",
        "symfony/console": "5.0.*",
        "symfony/dotenv": "5.0.*",
        "symfony/expression-language": "5.0.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.0.*",
        "symfony/framework-bundle": "5.0.*",
        "symfony/http-client": "5.0.*",
        "symfony/intl": "5.0.*",
        "symfony/mailer": "5.0.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "5.0.*",
        "symfony/orm-pack": "*",
        "symfony/process": "5.0.*",
        "symfony/security-bundle": "5.0.*",
        "symfony/serializer-pack": "*",
        "symfony/string": "5.0.*",
        "symfony/translation": "5.0.*",
        "symfony/twig-pack": "*",
        "symfony/validator": "5.0.*",
        "symfony/web-link": "5.0.*",
        "symfony/webpack-encore-bundle": "^1.7",
        "symfony/yaml": "5.0.*"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "^1.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.0.*"
        }
    }
}
```

This code is generated automatically in *DEV* environment and I haven't touched it.

**Comment by chr-hertel** [comment]
unfortunately the composer.json itself is not enough. i guess the best way would be for you to  [create a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)

**Comment by keshancs** [comment]
> unfortunately the composer.json itself is not enough. i guess the best way would be for you to [create a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)

Okay, give me some time, I'll do it

**Comment by keshancs** [comment]
After investigating and not being able to reproduce, I have deleted my vendor folder and ran composer install, the issue is gone. It was weird, because profiler was skipping the rendering of ajax block in the toolbar even though the Profiler model had it. The problem was only on my side, so I am closing this.
