### ISSUE TITLE
[DI] confusing deprecation in TypedReference in 4.4

### ISSUE THREAD

**Issue by linaori** [symfony/symfony#35752]
In #26636 (4.1) the `$requiringClass` argument in `TypedReference` has been deprecated: https://github.com/symfony/symfony/pull/26636/files#diff-6561cf4254b86cdc43ada0985f87e4a4R29

While helping someone on Slack whom received this deprecation, we had a hard time figuring out what the actual issue was. As `$requiringClass` is removed, the deprecation is referencing to a non-existing argument. I was thinking about something shown below as alternative, though I'm not 100% sure about it.

```php
public function __construct(string $id, string $type, /* $requiringClass, */ $invalidBehavior = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE, $name = null)
```

With as message:
> _The $requiringClass argument of "%s()" is deprecated since Symfony 4.1. All existing arguments should move 1 position to the left._

Edit: can make a PR based on this change: https://github.com/symfony/symfony/commit/f473c24e4b4436a0036718ecaffc5197ddc4dd8a

**Comment by nicolas-grekas** [comment]
We don't document old signatures so that we shouldn't add the `/* $requiringClass, */` part.
Not sure how to improve this. Isn't doing nothing the best option?
Please send a PR of course if you want (with the 1st statement in mind :) )

**Comment by linaori** [comment]
The problem is finding out what `$requiringClass` means as there are no argument references to it. Currently `$invalidBehavior` would act as `$requiringClass`, this means you have to fully understand argument shuffle that happens. 

Do you have a suggestion how to find out what `$requiringClass` in the message is referring to?

**Comment by nicolas-grekas** [comment]
Passing the requiring class as 3rd argument to ... is deprecated etc?
