### ISSUE TITLE
Controller denyAccessUnlessGranted fails when using array syntax for attributes

### ISSUE THREAD

**Issue by brianfreytag** [symfony/symfony#35755]
**Symfony version(s) affected**: 5.0.4

**Description**  
When upgrading from Symfony 3.4 to 5.0.4 (and to Flex), we've found that the instances in our Controllers where we utilize `$this->denyAccessUnlessGranted['ROLE_X', 'ROLE_Y'])` have begun to fail. 

If we remove the `array` syntax and do:

```php
$this->denyAccessUnlessGranted('ROLE_X') 
$this->denyAccessUnlessGranted('ROLE_Y') // Technically they only need one, not both, but we wanted to test the theory
```

The authenticated user passes through. Even trying just a single one that they pass on with array syntax fails:

```php
$this->denyUnlessGranted(['ROLE_X']) 
```

Throws an `AccessDeniedException`

**How to reproduce**  
Upgrade from Symfony 3.4 to 5.0.4 and try to use `$this->denyUnlessGranted(['ROLE_X'])` in your controller method.

I've traced the issue down to a few commits/conversations from the past:

https://github.com/symfony/security-core/commit/a718b282c0e9fbd88d2730c242a74d0d6c16b83f

https://github.com/symfony/security-core/commit/653f0418d784f5d1e78916c02d6932fcd00968fe

https://github.com/symfony/security-core/commit/d83ec4322b9b6b041020d0d03f92887c1f7efbf4

It appears that the ability to pass an array of attributes was deprecated and it recommends using multiple `isGranted` calls? 

Was there a discussion somewhere about this about the reasoning behind this design choice?

**Comment by xabbuh** [comment]
see #33584 for more information
