### ISSUE TITLE
Missing bootstrap.php file

### ISSUE THREAD

**Issue by methodeprog** [symfony/symfony#35756]
Dear Sir, 
after monthes of developping my application i realised that i've missing my bootstrap.php file.
That weird, application still running well so i'm a little confused. I upgrade to 5.0 and still have no bootstrap.php file. I dont really know the moment i lost the file.

I installed a new source of symfony 5.0 and bootstrap.php file is present.

I need advice for a secure procedure please if i've to copy and paste bootstrap.php in my project.

Best regards

We use GitHub issues only to discuss about Symfony bugs and new features. For
this kind of questions about using Symfony or third-party bundles, please use
any of the support alternatives shown in https://symfony.com/support

Thanks!

**Comment by wouterj** [comment]
Please read the default text of this issue type that you left at the end of your issue description 😃

**Comment by nicolas-grekas** [comment]
This could happen if you are using the recipes for branch 5.1, which is unreleased. If you're using an stable version, which you should, you can maybe run composer sync-recipes.
I'm closing as noted by wouterj.
