### ISSUE TITLE
composer require dependency injection, but it is already ther

### ISSUE THREAD

**Issue by highmoonrays** [symfony/symfony#35769]
"name": "symfony/dependency-injection",
            "version": "v5.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/dependency-injection.git",
                "reference": "86338f459313525dd95f5a012f8a9ea118002f94"
            },

Thats my composer.lock

when Im trying to  run 

composer require php-amqplib/rabbitmq-bundle

get this stuff

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-amqplib/rabbitmq-bundle v1.14.4 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.3 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.2 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.1 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.0 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - Installation request for php-amqplib/rabbitmq-bundle ^1.14 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.14.0, v1.14.1, v1.14.2, v1.14.3, v1.14.4].
 
Any help appreciated

**Comment by ro0NL** [comment]
see https://github.com/php-amqplib/RabbitMqBundle/pull/605, meanwhile you could downgrade symfony to v4 for the time being :)

i think the error, or "this stuff", is quite self-explanatory. Or what did you expect ... :sweat_smile: 

see also https://symfony.com/support, nothing to solve here ;)
