### ISSUE TITLE
[Expression-Language] Exception not trigger when APP_DEBUG=0

### ISSUE THREAD

**Issue by rimoi** [symfony/symfony#35767]
**Symfony version(s) affected**: 4.4.2

**Description**
```php
$condition = "content.len <= 2600"; // I wrote the length wrong to get the exception.

$item = (object) ["length" => 45];
try {
    $language->evaluate($condition, compact('item');
} catch (\Exception $e) {
    // ... I do something
}
```

**How to reproduce**
To make it simple when I execute this regular expression, in mode `APP_DEBUG = 0` (I have an exception), and `APP_DEBUG = 1` (I have no exception)
With `APP_DEBUG = 0` => `item.len` returns `null`
With `APP_DEBUG = 1` => `item.len`  exception `Notice: Undefined property: stdClass::$len`

**Comment by dmaicher** [comment]
As far as I know by default notices and warnings are not turned into exceptions for non-debug mode.

This is controlled by the container parameter `debug.error_handler.throw_at`.

In one of my apps I use this value:

```yaml
# throw exceptions for (E_ERROR | E_RECOVERABLE_ERROR | E_WARNING| E_PARSE | E_NOTICE) even when not in debug mode
debug.error_handler.throw_at: 4111
```

Also see https://symfony.com/doc/current/reference/configuration/framework.html#throw

**Comment by rimoi** [comment]
Thank you @dmaicher,
I don't know if it's a good idea to activate it in production for this!

**Comment by nicolas-grekas** [comment]
That's expected to me - that's what debug mode means. The code should be written in a warning-free way during dev (ie no exception should be thrown even when debug mode in on) - then prod will behave the same.

I'm closing as explained.
