### ISSUE TITLE
Invalid @author docblocks in some files

### ISSUE THREAD

**Issue by JurRutten** [symfony/symfony#35766]
**Description**  
A lot of files contain invalid @author docblocks, specifily for Tobias Schultze

**Example**  
`@author Tobias Schultze <http://tobion.de>` is used in a lot of files, but the text between '<' en '>' should be an email address, not a website

**Comment by nicolas-grekas** [comment]
That's fine to me, everybody understands it.

**Comment by JurRutten** [comment]
I understand, but some reflection packages (used by phpspec for instance) throw exceptions on this, because it should be an email address. Just saying.

**Comment by nicolas-grekas** [comment]
Then the packages should be fixed :) That's declarative statements, there is no need to be strict there - and the tool could actually accept URLs, that'd be a nice improvement (emails are private data, URLs not)

**Comment by fabpot** [comment]
Let's see what @Tobion think about it :)

**Comment by Tobion** [comment]
Closing as I agree with Nicolas statement.
