### ISSUE TITLE
HEADER_X_FORWARDED_HOST not detected when reverse proxy is present

### ISSUE THREAD

**Issue by santhoshpalan** [symfony/symfony#35765]
My application is behind reverse proxy and hence have set Trusted Proxies  accordingly [10.0.0.0/8] .
But when [getUriForPath](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1043) is called , It is returning symfony application server  IP address rather than the domain name set it in $_SERVER['HEADER_X_FORWARDED_HOST'].

I was able able to fix it by changing the public/index.php 

From
`Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);`

to 
`Request::setTrustedProxies(explode(',', $trustedProxies),  Request::HEADER_X_FORWARDED_HOST);`

Am I missing any configuration ?
Please help.

**Comment by nicolas-grekas** [comment]
You must set the 2nd argument of the method call to the headers that come from your reverse proxy. By default, we don't trust `HEADER_X_FORWARDED_HOST` - that's what the defaults mean. You "to" means you trust *only* `HEADER_X_FORWARDED_HOST. I think that's not what you want, but only you knows what your reverse proxy sends. Once you know, you should list more trusted headers, using `H1 | H2 | H2`.
You likely want to trust all the standard headers, which means `Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL)` could be your way. But again, it's on you to confirm.

Closing as there is no bug here, please check https://symfony.com/support or the doc for any follow up.
