### ISSUE TITLE
[Mailer][Mailgun] Support more headers

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#35776]
Mailgun has a number of headers available. Example is `o:deliverytime` and `v:my-var`. There is no way of setting these headers with the current implementation. All headers get prefixed with `h:`. See `MailgunApiTransport::getPayload()`

It would be a good idea to allow user to set these headers. See here for a complete list: https://documentation.mailgun.com/en/latest/api-sending.html#sending

I suggest to only allow headers that begins with `h:`, `t:`, `o:`, `v:` and then fallback to prefix with `h:`. That will allow us to add this in a BC compatible way.

**Comment by fabpot** [comment]
That works for me.

**Comment by Nyholm** [comment]
Hm. 
How?

I’m doing something like this:

$email->getHeaders()->addTextHeader('o:deliverytime', $sendAt->format(\DateTimeInterface::RFC2822));

But I get a payload like: “h:o:deliverytime”

**Comment by greedyivan** [comment]
`MailgunApiTransport` does not do much with various headers:
https://github.com/symfony/symfony/blob/269c4a2e15975896fbf32a0e913b26ec79ee2bb4/src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunApiTransport.php#L114-L132

**Comment by Nyholm** [comment]
Oh. I see. Thank you.  I was just looking at 5.0. 

But there is still no way to set o:deliverytime

**Comment by greedyivan** [comment]
It was added here: https://github.com/symfony/symfony/issues/35047

That was done for Postmark. To fully support Mailgun, it should be done something similar.

**Comment by greedyivan** [comment]
Regarding these:
- https://github.com/symfony/symfony/issues/35047#issuecomment-567499814
- https://github.com/symfony/symfony/issues/35047#issuecomment-567526041

@fabpot, can we implement a `CustomHeader` class instead of a bunch of specialized classes as `TagHeader`, `MetadataHeader` and so on, to move all customization logic to the `ApiTransport` layer?

**Comment by Nyholm** [comment]
@greedyivan Yes, I think that is a good idea. The `CustomHeader` should be able to define both its name and value. Drawbacks of using the custom header is of course that values will be provider specific. 

Do you mind submitting a PR?

**Comment by greedyivan** [comment]
> @Nyholm Drawbacks of using the custom header is of course that values will be provider specific.

I did some research and found out that the only place where it is needed is `MailgunApiTransport`. Even `MailgunHttpTransport`, as well as transports of all other providers, do not change the name of the header.

Thus, I suggest break BC and removing the addition of `h:` to the header in `MailgunApiTransport` by default.

The upgrade will consist of the need to explicitly set the full name of the header.

**Comment by Nyholm** [comment]
Thank you!

Im all for making things consistent. But I really don't want to break BC. 
Since this feature is MailgunApiTransport specific again, could we change it slightly so we allow all headers that begins with `h:`, `t:`, `o:`, `v:` and then fallback to prefix with `h:`. That will allow us to add this in a BC compatible way.

**Comment by greedyivan** [comment]
It is much more complicated than just adding prefix support.

Currently, `MailgunApiTransport` does not support these parameters of Mailgun API:
- `amp-html`
- `template`
- `t:version`
- `t:text`
- `o:dkim`
- `o:deliverytime`
- `o:deliverytime-optimize-period`
- `o:testmode`
- `o:tracking`
- `o:tracking-clicks`
- `o:tracking-opens`
- `o:require-tls`
- `o:skip-verification`
- `recipient-variables`

Just add support for `t:` doesn't mean anything without `template`.

I understand that the Mailer component is not a full substitution for the original API library, but we must decide what part of that API it should support. It looks good that it supports arbitrary custom headers using the `h:` prefix. Should it supports any of Mailgun extensions? If not and we want not to break BC, I think it’s better not to add anything at all.

**Comment by OskarStark** [comment]
Let’s not complicate it to much, it’s a BC break but it’s still experimental, so it should be no problem to change this behavior if it makes sense. We did this quite often in messenger component

**Comment by fabpot** [comment]
What @OskarStark said. The goal of a component being experimental is precisely to allow us to break BC whenever it makes sense.
