### ISSUE TITLE
[HttpClient] Undefined index: url

### ISSUE THREAD

**Issue by stevro** [symfony/symfony#35779]
**Symfony version(s) affected**: 4.4.4

**Description**  
When using a scoped http client the profiler collector throws an undefined index exception.

$this->paymentAPI->request('POST', 'new_payment', [
                'json' => [ ... ]
]);

**Error trace**
```
ErrorException:
Notice: Undefined index: url

  at /home/vagrant/code/...../vendor/symfony/http-client/DataCollector/HttpClientDataCollector.php:123
```

**Possible Solution**  
Same fix as in https://github.com/symfony/symfony/issues/35458 should be applied

**Comment by nicolas-grekas** [comment]
You mean #35672 I suppose.
