### ISSUE TITLE
[VarDumper] Add ddf() and dumpf() functions to dump to a file

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#35801]
**Description**  
Currently there are the functions `dd()` and `dump()` that dumps the content of the given variable.
If used in the browser, the dump is perfectly readable and navigable.

The problems arise when using the functions in CLI.

In this case, in fact, we have a big listing that is hard to navigate.

More often, if the dump is really big, it goes out of the console (I use PHPStorm) and so part of the dumped tree is lost (also if it is possible to increase the number of lines shown in the CLI, but the other problems still remain).

I'm currently working on a Rector (https://github.com/rectorphp/rector) and I need to print very big dumps (the tree that represents the parsed PHP code).

Reading the tree in the CLI is impractical as there are many links between nodes and navigate them is really really hard.

So I created two small functions: `ddf` and `dumpf`.

They doo exactly what the corresponding `dd` and `dump` functions do: they dump the passed variable.

But, instead of dumping the variable in the *medium* used (CLI or browser) they always create a file and put into it an HTML version of the dump.

![Schermata_2020-02-20_alle_15_03_48](https://user-images.githubusercontent.com/1968622/74940884-6a5ea500-53f2-11ea-9ea7-3404f4d20ecc.png)

Doing this permits to have all the advantages of an HTML dump, but from the CLI.

<img width="932" alt="Schermata 2020-02-20 alle 15 07 20" src="https://user-images.githubusercontent.com/1968622/74941090-bc9fc600-53f2-11ea-80a4-2a99beeb62f7.png">

It is also useful when working with API as, sometimes, the responses are parsed in a tree of related objects and navigate them in the CLI, again, is really hard.

WDYT? If you like the idea, I can submit a PR.

**Comment by stof** [comment]
Rather than adding new functions, I think you should achieve this by using the existing dumping API, but customizing the dumper.

Symfony already contains some special dumpers:

- the ServerDumper in the VarDumper component, to see logs to a separate dumping server (implemented as a CLI command that you run in a separate terminal)
- the DumpDataCollector in the HttpKernel component, to store dumped data in the profiler

you could implement a FileDumper wiring this to a file (and using either the HtmlDumper internally to perform the actually dumping).

**Comment by Aerendir** [comment]
@stof , it is exactly what I did: I used the `HtmlDumper`.

But as I find myself rewriting the same simple logic in more than one application each time, I created a package for my use and I think it can be useful to others, too.

We are speaking of very simple logic that, anyway, is annoying to write over and over again.

It is like this:

```php
function dumpf($var, ...$moreVars)
    {
        VarDumperCliToHtml::dump($var);

        foreach ($moreVars as $v) {
            VarDumperCliToHtml::dump($v);
        }

        if (1 < func_num_args()) {
            return func_get_args();
        }

        return $var;
    }
```

And the `VarDumperCliToHtml::dump` is something like this:

```php
if (false === \in_array(\PHP_SAPI, ['cli', 'phpdbg'])) {
            throw new \LogicException('You can use DumperCliToHtml only from the command line.');
        }

        static $output = null;
        $cloner        = new VarCloner();
        $dumper        = new HtmlDumper();

        if (null === $output) {
            $now = new \DateTime();
            /** @psalm-suppress InvalidOperand */
            $file = $now->format('Y-m-d\TH-i-s-u') . '_' . random_int(0, mt_getrandmax()) . '.html';
           
            $output = fopen($file, 'a+b');
        }

        if (false === is_resource($output)) {
            throw new \RuntimeException('Something went wrong creating the dump file.');
        }

        $dumper->dump($cloner->cloneVar($var), $output, []);
```

As simple as useful...

Or are you saying something different?

**Comment by ogizanagi** [comment]
As already mentioned by @stof, I think the [VarDumepr server](https://symfony.com/blog/new-in-symfony-4-1-vardumper-server) alreadys answer such use cases.

All you need is to configure the dump_destination to enabled the feature:

```yaml
# config/packages/debug.yaml
debug:
   dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
```

(`VAR_DUMPER_SERVER` is a default IP already registered for you by Symfony)

then, start the server with html format redirected to the desired file:

```bash
 php bin/console server:dump --format=html > dump.html
```
(you can start this in a dedicated terminal or as a background task)

then, any dump will be output to the server (hence to your file) instead of the original medium used.

This also works out of using Symfony Framework Bundle, with a bit more work.
See the official documentation:

- https://symfony.com/doc/current/components/var_dumper.html#the-dump-server

**Comment by Aerendir** [comment]
@ogizanagi , thank you for the extensive explanation.

Anyway, as I already told, I’m not speaking about the use in a Symfony application but about the use in any PHP package that often is not an application but a “simple” library.

More often, is also a library developed by someone else to which I’m simply contributing.

In such cases I don’t want to create a class and then start the web server, then removing the class, and then add it again, and so on.

In that cases I want to simply write ‘dumpf($variable)’ and see what’s inside, then continue the development.

We are speaking about the time required to write ‘dumpf()’ and the time required to create the class and start the web server (and then remembering of removing the class or at least exclude it from the commit) versus 5 characters and two parenthesis.

For sure, it is not so much, but in a day it makes a difference.

Considering that we are not speaking of a so complex code, I think it is not a so big overhead for the Symfony team, also considering that we have a ‘dd()’ function that is equivalent to ‘dump();die;’.

So we have a dedicated function to avoid writing a simple ‘die’ but you are refusing to have a ‘ddf()’ function to avoid writing an entire dedicated class each time and run an entire command in the console each time.

Mah, this is illogical in my honest opinion.

**Comment by ogizanagi** [comment]
Another alternative that does not requiring you changing anything in the code is using `VAR_DUMPER_FORMAT=html` env var and redirecting the output of your CLI command to a file:

```bash
VAR_DUMPER_FORMAT=html [your-cli-command] > dump.html
```

you'll get mixed output and dumps inside the file, but the html dumps are easily identifiable.

Note for now, we're not pronouncing about having or not a `dumpf` but trying to identify your use-case and if it can legitimately be solved with existing solutions or not, as we try to avoid providing too much ways too perform the same thing. It's not only a code maintenance issue, but the increased perceived complexity of having multiple solutions that look too similar and how to document it.
(Also `dd` made it the long way. It was multiple times refused and was eventually added by popular demand of the community)

**Comment by Aerendir** [comment]
> Note for now, we're ... trying to identify your use-case and if it can legitimately be solved with existing solutions or not, as we try to avoid providing too much ways too perform the same thing. It's not only a code maintenance issue, but the increased perceived complexity of having multiple solutions that look too similar and how to document it.

Ok, I understand your PoV and it is more than reasonable.

So, let's continue exploring my use case.

Let's make me explain...

The concrete situation that lead me to implement the `ddf()` and `dumpf()` functions is this.

I'm developing a rector to automatically add `@throw` tags to methods and functions.

Before writing the code I write a failing test case, then run something like this:

```console
vendor/bin/phpunit --filter AnnotateThrowable
```

The rector I'm developing fails the tests, so I add somewhere `dd()` or `dumpf()` to see what's going on: in the console the output is practically not readable.

So I use the solution you proposed:

```
VAR_DUMPER_FORMAT=html vendor/bin/phpunit --filter AnnotateThrowable > dump.html
```

Now in the console I cannot read any output and I'm forced to open the `dump.html` file (or refresh it).

This means that if now I want to "turn off" the dumping to the file, I have to write again the command (or searching it in the previous commands using arrow keys up and down):

```
endor/bin/phpunit --filter AnnotateThrowable
```

Doing this three, four, five, ten times, is acceptable, but when you develop for four or five hours, it becomes very fast very annoying to search the command in the previous executed ones or rewrite the same command over and over again.

Without considering the mixing of outputs in the `dump.html` file.

The reason why I created these two small functions is exactly this: each solution current solution has its own drawbacks and in the long run of a development session causes a lot of losses of time (more, on very boring things).

Using the two functions, instead, requires max three seconds to write the functions, then inspect the output generated, and then other very few seconds to remove (or comment) the function call.

I found these two functions very very useful.

Now, I know that your job is to maintain Symfony "usable", avoiding adding overheads or complexity.

I'm only saying that not anyone ever knows has a problem like this that can be solved in a so simple way.

I think they are very useful functions to have at hand while developing commands that work with very big variables and object trees (like the ones created by PhpParser or by the retrieval of data from APIs)...

Personally I cannot imagine anymore developing a command without having these two functions ready to be used.

**Comment by stof** [comment]
@Aerendir I'm almost sure that the core team would reject adding more high-level functions in VarDumper, based on our previous discussion on this (I know for sure that I would be against it). VarDumper is already extensible to provide this.

Given that your use case is to dump things while running phpunit, you could have your phpunit bootstrap file configuring a custom handler in the VarDumper component (you would do that once, not everytime you want to toggle dumping or no, unless you also consider that having the VarDumper component in your `require-dev` is something you toggle each time). And then, you would be using the **existing** `dump` and `dd` high-level functions to trigger the dumping.

```php
$dumper = new HtmlDumper();
$cloner = new VarCloner();

$handler = function ($var) use ($dumper, $cloner) {
    $output = // open the appropriate file handle here...

    $dumper->dump($cloner->cloneVar($var), $output);
};

VarDumper::setHandler($handler);
```

**Comment by Aerendir** [comment]
Again, I have to write and remove each time the code... And if the library doesn't have a bootstrap file, I have to create it...

But, after all, it is not a problem of mine: I was trying simply to improve DX.

But if you don't like the feature... I have my own, small, composer package anyway :)

**Comment by Aerendir** [comment]
Just for clarity, the example I provided is only the last situation in which the functions are useful.

There are other situations where PHPUnit is not involved, like, as told, when dealing with APIs, or when writing complex commands, where having such functions is very useful.

But, again, this not a problem of mine anymore...

**Comment by nicolas-grekas** [comment]
My preference: have an env var control the desired behavior of dd()/dump()

**Comment by ogizanagi** [comment]
Could a `VAR_DUMPER_FORMAT=server` work then? 
For instance, by reopening #26695 to get sensible defaults for the server dumper and perhaps locking the handler as soon as this env var is set?

This would mean anyone can use `dump` in any project (requiring-dev `symfony/var-dumper`), without changing a single line of code (appart adding `dump`) by:
- starting  server using `./vendor/bin/var-dump-server --format=html > dumps.html`
- using the env var: `VAR_DUMPER_FORMAT=server [your-cli-command]`

**Comment by Aerendir** [comment]
@ogizanagi , yes, it is really near what I tried to accomplish with my functions `ddf()` and `dumpf()`.

Obviously is more verbose as I need to first start the var-dump-server and then also add the env var at the beginning of the command, but the end result is very useful anyway.

The only drawback (but this is loose from the main topic of this issue) is the ordering of the dumps: it seems that the the last dump is the first shown, so, to read the dumps in order I need to go to the bottom of the file: on very big dumps this is a bit annoying.

**Is there a way to reverse the order of dumps?**

In the end, the end result is very very good, but I still prefer to only have one simple function to call instead of having to start the server and prepend the env var 😬

**Comment by Aerendir** [comment]
Anyway, it seems not working outside of Symfony applications and seems to be slower than the functions I'm proposing.

If I use this solution in a Symfony app, the result is what I told in my previous comment; if I use it in a library, I don't get any dump.

https://symfony.com/doc/current/components/var_dumper.html#the-dump-server

**Comment by ogizanagi** [comment]
> Is there a way to reverse the order of dumps?

that's just a css rule. Dumps are already from first to last in the file as its a stream. Adding a way to toggle this rule might be possible if really wanted.

> If I use this solution in a Symfony app, the result is what I told in my previous comment; if I use it in a library, I don't get any dump.

I need to check, but no reason it should not work.

**Comment by ogizanagi** [comment]
@Aerendir : I confirm the exact code from documentation is working fine (in a dedicated file, outside of a Symfony app).

**Comment by ogizanagi** [comment]
See #35967 for the `VAR_DUMPER_FORMAT=server` suggestion
