### ISSUE TITLE
[Mailer] AbstractTransport silently doing nothing if no recipients set

### ISSUE THREAD

**Issue by jschaedl** [symfony/symfony#35805]
Today I struggled a bit with sending an email via the Mailer class.

Here is some example code of what tried to do:

```
$email = (new Email())
    ->from('test@test.de')
    ->subject('Subject')
    ->text('Content')
;

$this->mailer->send($email);
```

```
# .env
MAILER_DSN=smtp://localhost:1025
```

The implementation and the mailer configuration looked fine to me, but the email was not send out. There was also no Exception that indicated what I probably did wrong.

So I debugged my code and could find this line in the `AbstractTransport`.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Transport/AbstractTransport.php#L68 

As you can see the `AbstractTransport::send()` method is just returning `null` in case there are no recipients set, which means the transport is failing "silently" without sending the email. Ok, my bad, I forgot to set a recipient. Problem solved.

But I was wondering, if this is intended behaviour? I actually would have expected an Exception telling me that I forgot to set a recipient.

**Comment by noniagriconomie** [comment]
@jschaedl I got this also when trying the component bah then

maybe adding a log `info` or `warning` could be usefull wdyt?

as there is a `$this->logger`

**Comment by jschaedl** [comment]
Probably duplicate of #33753
