### ISSUE TITLE
[VarDumper] Improve rendering in HTML format

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#35800]
**Description**  
Currently the dump is rendered expended and then it is collapsed by JavaScript which creates an annoying flickering. Also I think there is a performance problem here. To process a dump of a big object like HTTP Kernel `Sfdump()` calls `toggle()` about 120 times and it takes 35 - 50 ms on my environment. That's too slow.
Can we render an object dump collapsed by applying an appropriate CSS styles on server side?

**Comment by nicolas-grekas** [comment]
I'm sure we can, but I don't know how. Someone needs to make it happen. Up to give it a try?
