### ISSUE TITLE
password encoder mismatch register/login v. 4.4

### ISSUE THREAD

**Issue by BernardA** [symfony/symfony#35810]
**Symfony version(s) affected**: 4.4.4

**Description**  
Passwords encoder/decoder on registration/login do not seem to match throwing `bad credentials`. This was working fine on v 4.3, but not so on 4.4.

Also, passwords generated by `fixtures` differ, encoder wise,  from those generated by registration script.

Bad credentials error is thrown at `symfony/security-core/Authentication/Provider/DaoAuthenticationProvider.php:65`.

**How to reproduce**  
On /config/packages/security.yaml

          encoders:
               App\Entity\User:
                   algorithm: auto
                   cost: 12

/src/DataFixtures/AppFixtures

     use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
     .....
     $user->setPassword(
                $this->passwordEncoder->encodePassword(
                    $user,
                    $userFixture['password']
                )
            );

/src/EventSubscriber/UserRegisterSubscriber

     use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
     ....
     $user->setPassword(
            $this->passwordEncoder->encodePassword($user, $user->getPassword())
        );

So, a password generated running `php bin/console doctrine:fixtures:load` will look like `$argon2id$v=19$m=65536,t=4,p=1$AHgt+c3Vd0y9uMwJsE6tpw$B4iqM2zI8Czb2HO4endZ2p0ZdO74PA7/geLBUI/3crg`. That's clearly `argonb2i`. 

But a password generated through normal registration form, using above `UserRegisterSubscriber` will look like 
      `$2y$12$iNQErYOd/Mqb5fYBSr/H2.qKCeBowBLIMMHcNz2Xm2LSje9sELWMa`. 
Which looks like regular `bcrypt`. 

Attempting to login a user generated by `fixtures` will throw the error while a user registered 'normally' will not. 

If I change config as below

      On /config/packages/security.yaml

          encoders:
               App\Entity\User:
                   algorithm: argon2i
                   cost: 12

Fixtures will still create user with the argon encoded password. But `UserRegisterSubscriber` will throw an error: 
      `Unknown password hashing algorithm: 2" at /symfony/security-core/Encoder/NativePasswordEncoder.php line 71`

Changing the encoder to `bcrypt` as below will have Fixtures and EventSubscriber both create `bcrypt` password and login will work fine. 

          encoders:
               App\Entity\User:
                   algorithm: bcrypt
                   cost: 12

**Possible Solution**  

**Additional context**  
full code at https://github.com/BernardA/quiamo-api

**Comment by xabbuh** [comment]
Is the PHP version run on the CLI that loads the fixtures the same as the one used when the application is accessed through HTTP?

**Comment by BernardA** [comment]
The site is being served with Symfony's server
`Using PHP version 7.3.11 (from default version in $PATH) `

On terminal where I run fixtures:load,  it tells me that the `PHP -version` is 
`PHP 7.3.8 (cli) (built: Aug 14 2019 16:42:46) ( NTS )`

**Comment by stof** [comment]
Well, make sure that you either have the sodium extension enabled in both your PHP runtimes (if you want to use argon2id) or in none of them (if using bcrypt is fine). Otherwise, you should stop using `auto` (as your fixtures will think that using stronger algorithms provided by sodium is fine but your web server won't know how to deal with it)

**Comment by xabbuh** [comment]
closing here as there doesn't seem anything to be fixed

**Comment by BernardA** [comment]
So, if this 

     On /config/packages/security.yaml

      encoders:
           App\Entity\User:
               algorithm: argon2i
               cost: 12

throws: 

     Unknown password hashing algorithm: 2" at /symfony/security-core/Encoder/NativePasswordEncoder.php line 71

You think there's nothing to be fixed?! Interesting.

**Comment by xabbuh** [comment]
@BernardA As far as we understood the issue you generated the hashes on a different system than the one that validated them. You then need to make sure that the algorithm that is picked automatically by the generating system is also supported by the one validating the hashes. If we misunderstood that, please provide more information about what you are doing and how we could reproduce this. Thank you.

**Comment by BernardA** [comment]
@xabbuh, yes there's the question concerning passwords generated by `fixtures:load` and then trying to login through the 'normal' route. Even in that case, the only difference is a small version of PHP ( 7.3.8 to 7.3.11 ). It's hard to see how that would cause such a mismatch.

But, as I pointed out on my original post, registering a user through the 'normal' process does not generate other hash than `bcrypt` .
If one sets algorithm to `auto`, it will generate `bcrypt`.
If one sets algorithm to `argon2i` it will generate error as shown
If one sets algorithm to 'brcrypt` it will generate `brcrypt`

So, while the different algorithms are available for registration using `fixtures:load`, that's not the case for the 'normal' registration. It will do nothing but `bcrypt`

**Comment by stof** [comment]
Do your PHP runtimes have the same extensions loaded ? If no, that's *another* difference between them (and a very important one when you rely on `auto` to choose the best algorithm based on supported features).

**Comment by BernardA** [comment]
I set Symfony's server PHP version to the same as the one for 'fixtures' ( 7.3.8 ) by creating a `.php_version` file. 

It is working fine now, so it probably was as you suggested above, an extension issue. Thanks

**Comment by BernardA** [comment]
@stof I deployed the app to AWS Elastic Beanstalk and the issue is back. 

So, there must be a very specific and finicky requirement for the `auto` set to work properly. 

I am setting it back to `bcrypt`. It's the only one that works consistently.
