### ISSUE TITLE
 symfony/mailer configuration file

### ISSUE THREAD

**Issue by crashkita** [symfony/symfony#35812]
I need a bit  help with configurations symfony/mailer in config/*.yaml.  
For TLS connection i want inject StreamOptions that he don't checked certificat and don't have SSL Error: "routines:tls_process_server_certificate:certificate verify failed" 
For SwiftMailer  this strings deciding  problem: 
$transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));,  
How can i do this with this package  (symfony/mailer).

**Comment by chalasr** [comment]
We use github issues for tracking bugs and feature requests.
Please consider checking our [support platforms](https://symfony.com/support).
