### ISSUE TITLE
[ErrorHandler] DebugClassLoader reports bad static method should be implemented

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#35836]
**Symfony version(s) affected**: 5.0.4

**Description**  
If a `@method` annotation with `static` return type is present on an interface, the `DebugClassLoader` reports `Class Foo should implement method static FooInterface::method().`

As per [phpDocumentor method tag](https://docs.phpdoc.org/latest/references/phpdoc/tags/method.html) if a method is static the return type is mandatory. This implies that

```
 * @method static getInstance()
```

should be parsed as non-static method with `static` return type, but now is parsed as static untyped method.

**Possible Solution**  
The `@method` parse regex on DebugClassLoader.php:L430 should capture return type and check it while determining if a method should be static or not.

**Comment by nicolas-grekas** [comment]
> if a method is static the return type is mandatory

cool, that's the rule we missed implementing. Up for a PR @alekitto?

**Comment by alekitto** [comment]
> Up for a PR @alekitto?

:+1: opened #35836
