### ISSUE TITLE
[Form] Errors added to form fields during PRE_SUBMIT disappear

### ISSUE THREAD

**Issue by iquito** [symfony/symfony#35831]
**Symfony version(s) affected**: 5.0.4 (and previous versions, [this question on Stackoverflow](https://stackoverflow.com/questions/30276786/symfony-2-6-adderror-inside-pre-submit-event/60359927) described it for Symfony 2.6)

When adding an error to a form field during PRE_SUBMIT, that error disappears completely from the form. Yet if an error is added to the Form object itself, it is displayed. This seems inconsistent and is not documented in the [Form Events documentation](https://symfony.com/doc/current/form/events.html). Either all errors added during PRE_SUBMIT should be shown/handled, or all errors should be removed plus this would need to be documented so people do not rely on such behavior.

While usually you would add form errors in the POST_SUBMIT event, there are use cases where it might make sense to already add them during PRE_SUBMIT - in my case because the form field is not mapped to the data_class and all the processing is done in PRE_SUBMIT, so being able to add it there would be handy.

This is a simple example to show the behavior (and could be included in tests to verify behavior):

```php
class PreSubmitExampleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('textField', TextType::class, [
                'label' => 'Input some text!',
                'required' => false,
            ]);

        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
            $form = $event->getForm();

            $form->get('textField')->addError(new FormError('Field error!'));
            //$form->addError(new FormError('Form error!'));
        });
    }
}
```

If you uncomment `$form->addError` and submit this form, that error will be shown, yet the error for `textField` is never shown. I also added [the full file to this issue](https://github.com/symfony/symfony/files/4240670/PreSubmitExampleType.zip) to easier reproduce the issue.

**Comment by yceruto** [comment]
By definition, Form errors are collectable during the submission only.

However, adding form errors on `PRE_SUBMIT` event is possible, but to achieve it correctly the listener must be linked to the form field itself, not to the parent form, e.g.:
```php
$builder->get('textField')->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $form = $event->getForm();
    $form->addError(new FormError('Field error!'));
});
```
That's because the Form is processed following its hierarchy, first parent, then its children, and before `PRE_SUBMIT ` the Form errors are emptied out.

This is a basic workflow that could clarify why you shouldn't add errors to child fields on `PRE_SUBMIT` event:
```
submit( data ):
    - initialize form errors to `[]`.
    - PRE_SUBMIT event // any error added to any child field here will have no effect
    - for each child field -> submit( child_data ) and repeat the process
    - view to norm (Normalize data to unified representation)
    - SUBMIT event
    - norm to model and view (Synchronize representations)
    - POST_SUBMIT event
```

**Comment by iquito** [comment]
Thanks for the explanation! As I see it, this just confirms that this is a bug, as the parent form and its child forms should not have different behavior in that regard. When writing a form you might not even know how it will be used in the end. If a form is used as the parent, attaching an error during PRE_SUBMIT will work, but when it is then used as a child it will not work. Even if you test your forms thoroughly it is likely this special case can be missed.

As I see it, a better workflow would be to initialize the errors outside of the submit function (for example when the form is created) and then follow this reduced workflow in the submit function:

```
- PRE_SUBMIT event
- for each child field -> submit (without initializing/resetting the errors)
- view to norm (Normalize data to unified representation)
- SUBMIT event
- norm to model and view (Synchronize representations)
- POST_SUBMIT event
```

Because to me, resetting the errors is a bit unexpected anyway and would be something nice for the application to be able to control (flushing errors could be a specific decision). The current behavior requires specific internal knowledge of the form component to know when errors are reset, and adding an error at the wrong time will lead to it being silently removed (and there is no way to prevent that). Because the removal is silent, it is easy to miss / never notice.

**Comment by yceruto** [comment]
Probably there is a bug already solved behind it. 

Maybe some old Form's friends @xabbuh @HeahDude or @stof remember why the form errors have to be reset in this place, but I agree with you that it's unwanted.

**Comment by yceruto** [comment]
Conceptually, this is what we're preventing:
```php
$form->addError(new FormError('Error!'));
$form->submit('foobar'); // reset errors
$form->getErrors(); // empty
```

**Comment by xabbuh** [comment]
I am afraid there is not much we can do about this besides improving the documentation in regard to how forms are submitted.

**Comment by xabbuh** [comment]
I am closing here as explained. I'd be happy to review a documentation PR though which clarifies this a bit.
