### ISSUE TITLE
German Umlauts in Console

### ISSUE THREAD

**Issue by bnjmnfnk** [symfony/symfony#35842]
**Symfony version(s) affected**: 5.0.4

**Description**  
German Umlauts ignored in Console Question Helper

**How to reproduce**  

```
protected function execute(InputInterface $objInput, OutputInterface $objOutput)
{
	$objHelper = $this->getHelper('question');

	$objQuestion = new Question('Title: ');

	$strTitle = $objHelper->ask($objInput, $objOutput, $objQuestion);

	$objOutput->writeln($strTitle);

        return 0;
}
```

If i type "aaaöäübbb" in console i just get "aaa\\\bbb" as outout. If i just type umlauts like "öäü" the output is empty.

**Comment by stof** [comment]
Please provide a bit more info:

- OS you use
- PHP version
- Terminal you use (maybe it is an issue with a specific terminal)
- encoding you use in your terminal.

**Comment by benjaminfunk** [comment]
- Windows 10
- PHP 7.4.1
- Default Windows Command and GIT bash
- Dont know. Where can i find/set it?

Its not limited by the output. It happens when i write file too or in my case communicate with the shopify API.

**Comment by malteschlueter** [comment]
Maybe it's a encoding problem with windows?
I tested your example code with the same input and get the correct output with umlauts.
My setup:
* MacOS 10.15.4
* PHP 7.4.4
* Default Mac Terminal
* Should be UTF-8

**Comment by arueckauer** [comment]
I could reproduce the this on Windows 10.0.19041.173 using cmd, PowerShell 5.1 and PowerShell 7.0. Changing the active console code page to 65001 `chcp 65001` did bring the desired outcome. Not sure yet, how to solve this.

It looks like an encoding issue of the shell. Execution on the WSL works fine.

**Comment by YaFou** [comment]
I opened an issue related to this issue #36324. I think, this issue is due to the [`fgets`](https://www.php.net/manual/fr/function.fgets) function [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php#L125):
```php
$ret = fgets($inputStream, 4096);
```
**I explained this in more detail in my [comment](https://github.com/symfony/symfony/issues/36324#issuecomment-610443872).**
