### ISSUE TITLE
HttpClient: Request with closed resource triggers a Curl Warning

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#35859]
When a destructing a `Response` which does not have yet streamed all the request, a curl warning is triggered

> PHP Warning:  curl_multi_exec(): CURLOPT_INFILE resource has gone away, resetting to default

reproduct case:
```php 
$client = HttpClient::create();

// create a resource
$body = \fopen('php://temp', 'rw+');
fwrite($body, 'some content');

$response = $client->request('PUT', 'https://httpbin.org/put', ['body' => $body]);

// start streaming but do not consume chunks
$client->stream($response);

// close the resource
fclose($body);

unset($response);
```

**Comment by nicolas-grekas** [comment]
There needs to be an error for sure - closing the body before it's been sent is invalid. What behavior would you expect? A TransportException?

Up for a PR?

**Comment by jderusse** [comment]
closed as won't fix
