### ISSUE TITLE
symfony/http-client idn_to_ascii raise exception for some domain

### ISSUE THREAD

**Issue by warwar** [symfony/symfony#35852]
**Symfony version(s) affected**: 4.4.4

**Description**  
for domain 0-------------------------------------------------------------0.com raise InvalidArgumentException

**How to reproduce**  
$http_client = HttpClient::create();
$response = $http_client->request('GET', 'http://0-------------------------------------------------------------0.com');

**Possible Solution**  

**Additional context**  
[Symfony\Component\HttpClient\Exception\InvalidArgumentException]
In HttpClientTrait.php line 446:
Unsupported host in "http://0-------------------------------------------------------------0.com/".

**Comment by nicolas-grekas** [comment]
This looks like the normal behavior of `idn_to_ascii()`: https://3v4l.org/U0ct2
If you think that's an issue, please submit a bug report to https://bugs.php.net

What we can do in Symfony is replace the "if" block on that line with:
`$host = \defined('INTL_IDNA_VARIANT_UTS46') ? idn_to_ascii($host, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46) ?: strtolower($host) : strtolower($host);`

up for a PR with a test case?
