### ISSUE TITLE
Service not found for v 4.4

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#35856]
**Symfony version(s) affected**: 4.4

**Description**  

New Services not injected.

**How to reproduce**  

https://github.com/BonBonSlick/symfony-4-4-doctrine-fixtures-di-bug

**Possible Solution**  

Seems it can not auto-wire, because not autoconfigured. 
By autoconfigured, I mean, we have interface and implementation, implementation is never cached, wired, as result service is hidden.

Maybe there is some config I missed.

Namespace is right, and services.yaml config seems also fine. 
 php bin/console debug:autowiring
php bin/console debug:container
show that there are no PostInterface service.

Docs used https://symfony.com/doc/4.4/service_container.html

**Additional context**

**Comment by koenreiniers** [comment]
Classes in src/Entity are excluded from being automatically registered as services (see line 18 in config/services.yaml)

**Comment by BonBonSlick** [comment]
@koenreiniers thanks, my bad.

**Comment by xabbuh** [comment]
let's close then
