### ISSUE TITLE
Symfony Process Component does not run audit2allow properly

### ISSUE THREAD

**Issue by bilogic** [symfony/symfony#35862]
**Symfony version(s) affected**:
symfony/process                       v4.4.4     Symfony Process Component

**Description**  
Seems that ```audit2allow``` is prevented from accessing ```/var/log/audit/audit.log``` even though PHP is as root.

**How to reproduce**  
```exec("audit2allow -a -M a2a");``` works just fine, ```a2a.pp``` and ```a2a.te``` is produced. However,
```
        $process = new Process(['audit2allow', '-a', '-M', 'a2a']);
        $process->run();
        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }
        echo $process->getOutput();
```
yields
```
   Symfony\Component\Process\Exception\ProcessFailedException  : The command "'audit2allow' '-a' '-M' 'a2a'" failed.

Exit Code: 1(General error)

Working directory: /var/www/html/example

Output:
================
compilation failed:
a2a.te:6:ERROR 'syntax error' at token '' on line 6:


/usr/bin/checkmodule:  error(s) encountered while parsing configuration
/usr/bin/checkmodule:  loading policy configuration from a2a.te
```
which is the typical output when there is a empty ```/var/log/audit/audit.log```

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions, please use any StackOverflow.

Thanks!

**Comment by bilogic** [comment]
@fabpot I dug further, when I execute just 'audit2allow' '-a' on my command line, there is some output. But when I put it through Symfony Process Component, there is no output. Does not sound like Symfony Process Component is working correctly.

**Comment by Pierstoval** [comment]
@bilogic is it only related to `audit2allow`?

**Comment by bilogic** [comment]
@Pierstoval I only tried it out with ```audit2allow``` and have not gone on to others yet. My expectation was for it to perform just like PHP's ```exec()```
