### ISSUE TITLE
[Secrets] Unsuspected behavior of secrets:decrypt-to-local

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#35868]
**Symfony version(s) affected**: 4.4, 5.0

**Description**  
I'm not sure if this is a documentation issue, an implementation issue, or a bad practice in my project: At [this location](https://symfony.com/doc/current/configuration/secrets.html#referencing-secrets-in-configuration-files) the documentation states that secrets are being overridden by environment variables. However, when I use the ```secrets:decrypt-to-local```-command [as described](https://symfony.com/doc/current/configuration/secrets.html#deploy-secrets-to-production), the secrets are put at the end of the ```.env.prod.local``` file. Thus, swapping the override behavior, since secrets are now overriding the environment variables.

**How to reproduce**  
- ```php bin/console secrets:set TESTVALUE --env=prod```
- ```echo "OTHER_TESTVALUE='abc'" > .env.prod.local```
- ```php bin/console secrets:decrypt-to-local --force --env=prod```
- ```cat .env.prod.local```
Output is:
```
OTHER_TESTVALUE='abc'
TEST='abc'
```

**Possible Solution**  
In my opinion ```secrets:decrypt-to-local``` should put the secrets on top of the .env.prod.local file, or the documentation should better describe the behavior.

**Additional context**  
My main reason to use the 'decrypt-to-local'-feature was to reuse the value stored in a secret in an environment variable, since in the URL pattern only the password part is secret in most cases. This behavior can be bypassed by storing the full URL as a secret (eliminating the need for a certain order in the declaration of env vars), but it is still unsuspected.

**Comment by nicolas-grekas** [comment]
This is the expected behavior: env vars take over secrets.
When you "decrypt to local", you turn secrets into env vars, exactly like you describe it.

**Comment by nicolas-grekas** [comment]
(feel free to contribute to the doc of course!)
