### ISSUE TITLE
Mailer support for mail function

### ISSUE THREAD

**Issue by nimaia-conti** [symfony/symfony#35865]
**Description**  
I coundn't find a way to set up the new mailer component to work with the native mail function.
I think it might be useful for certain server setup.
For istance in my case the function proc_open (which is used in Sendmail transport) is disabled in production server.

**Example**  
It might exists a MailTransport class which use the native mail function.
It could be configured with a dsn like: mail://default

Thanks for the attention.

**Comment by fabpot** [comment]
We won't support it as it is known to be impossible to use it securely. It has been removed from Swiftmailer in the past as well for that reason.

**Comment by xxorax** [comment]
Proper (still controversial) [explanation](https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-289291228).
Appreciate [this one](https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-367298536).
