### ISSUE TITLE
[String] Unexpected result for length() of a UnicodeString

### ISSUE THREAD

**Issue by dompie** [symfony/symfony#35869]
**Symfony version(s) affected**: 5.0.4

**Description**  
Length of a UnicodeString returns 3 instead of expected 4.

**How to reproduce**  
Put somewhere in your Symfony app:
```php
$word = 'नमस्ते';
dump((new UnicodeString($word))->length()); //returns 3, but should return 4 according to docs.
```

According to https://symfony.com/doc/current/components/string.html#methods-related-to-length-and-white-spaces a length of **4** should be returned as explained earlier in [that image before](https://symfony.com/doc/current/_images/bytes-points-graphemes.png). But currently it returns **3** on my system with PHP7.4.3, on Ubuntu 18.04.

I tried also PHP's built in `grapheme_strlen()`, `mb_strlen()` and `iconv_strlen` functions. None of them returned the suggested result **4**.

**Possible Solution**  
Either fixing the documentation or fixing PHP's strlen() function(s). 

**Additional context**  
None.

**Comment by nicolas-grekas** [comment]
Surprizing.
Here, it reports 4 correctly: https://3v4l.org/2iNdQ
This must be a bug in PHP, related to the version of the intl extension I'd say.
Please report it at https://bugs.php.net.
I'm closing here as we cannot fix the issue in Symfony: `grapheme_strlen()` has to be fixed.

**Comment by nicolas-grekas** [comment]
https://bugs.php.net/79308
