### ISSUE TITLE
Messenger[Async][Symfony5.1] - AmazonSqsTransportFactory not implemented 

### ISSUE THREAD

**Issue by blry** [symfony/symfony#35866]
**Symfony version(s) affected**: 5.1

**Description**  
When we try to dispatch an event using MessageBus **async** (Doctrine) from Symfony 5.1 - it returns an exception:
Attempted to load class "AmazonSqsTransportFactory" from namespace "Symfony\Component\Messenger\Bridge\AmazonSqs\Transport".
Did you forget a "use" statement for another namespace?

**How to reproduce**  
Install symfony 5.1; Dispatch an async event; Get an exception

**Possible Solution**  
Integrate Symfony 5.1 with https://github.com/symfony/amazon-sqs-messenger

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by blry** [comment]
@xabbuh Of course, if it helps

However do you really need it? If we take a look at composer.json at AmazonSqsTransport repository - it requires symfony/messenger **5.0**
(see https://github.com/symfony/amazon-sqs-messenger/blob/master/composer.json).

But other transports require symfony/messenger **^5.1**. See:
https://github.com/symfony/doctrine-messenger/blob/master/composer.json
https://github.com/symfony/amqp-messenger/blob/master/composer.json

Probably there's a problem

**Comment by xabbuh** [comment]
To be honest, I do not really understand the issue. I mean if want to use the Amazon SQS transport, you will need to install the `symfony/amazon-sqs-messenger` package.

**Comment by blry** [comment]
@xabbuh, Firstly, I don't want to use it at all. I just wanted to dispactch a message using Async by Doctrine, but messenger requires it.
Secondly, even if I wanted, there would not be a way, because amazon-sqs-messenger doesn't work with Symfony 5.1

> php-cli@2de3c1da4e9a:/var/www/api$ composer require symfony/amazon-sqs-messenger
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

 >Problem 1
 >    Installation request for symfony/amazon-sqs-messenger 5.1.* -> satisfiable by symfony/amazon-sqs-messenger[5.1.x-dev].
>     symfony/amazon-sqs-messenger 5.1.x-dev requires symfony/http-client ^4.3|5.0 -> no matching package found.

So there's no way to dispatch an async message in Symfony 5.1

**Comment by xabbuh** [comment]
I am not sure. So I think having an example application that allows to reproduce it would help to investigate what is going on and what we could do about it.

**Comment by blry** [comment]
Hi @xabbuh 
Just installed clean symfony 5.1. with messenger and added a message in async transport (doctrine).
https://github.com/blry/symfony-5.1-amazon-sqs-incompotibility

Also I created an endpoint for dispatching an async message:
https://github.com/blry/symfony-5.1-amazon-sqs-incompotibility/blob/master/src/Controller/TestController.php
https://github.com/blry/symfony-5.1-amazon-sqs-incompotibility/blob/master/config/packages/messenger.yaml

When we try to call it, we get an error:
> Attempted to load class "AmazonSqsTransportFactory" from namespace "Symfony\Component\Messenger\Bridge\AmazonSqs\Transport".
> Did you forget a "use" statement for another namespace?

If we try to install amazon-sqs-transport, we'll get:
>     composer require symfony/amazon-sqs-messenger
>     ./composer.json has been updated
>     Loading composer repositories with package information
>     Updating dependencies (including require-dev)
>     Restricting packages listed in "symfony/symfony" to "5.1.*"
>     Your requirements could not be resolved to an installable set of packages.
> 
>     Problem 1
>     Installation request for symfony/amazon-sqs-messenger 5.1.* -> satisfiable by symfony/amazon-sqs-messenger[5.1.x-dev].
>     symfony/amazon-sqs-messenger 5.1.x-dev requires symfony/http-client ^4.3|5.0 -> no matching package found.

**Comment by xabbuh** [comment]
Thank you, that helped a lot. See #35907 for the fix.

**Comment by blry** [comment]
Yes, thanks! @xabbuh
