### ISSUE TITLE
phpdocumentor/reflection-docblock should be in 'require' block in symfony/property-info

### ISSUE THREAD

**Issue by allansun** [symfony/symfony#35874]
**Symfony version(s) affected**: ~4|~5

**Description**  
symfony/property-info uses phpdocumentor/reflection-docblock package in \Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor. However it was only included in 'require-dev' block in its composer.json

**How to reproduce**  
1. In my own composer.json require "symfony/property-info": "~4|~5" 
1. run `composer update` (This would be done in development phase)
1. `use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;` in my own code make sure everything works
1. run `composer install --no-dev` (This would normally be done in production environment)
1. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php#L62 throws an error that I don't have phpdocumentor/reflection-docblock

**Possible Solution**  
Manually included phpdocumentor/reflection-docblock in my own package. Ideally it should be done in composer.json in symfony/property-info

**Comment by fabpot** [comment]
We don't include optional packages in the require section of the package to avoid pulling too many deps when they are not strictly needed. Instead, we have a mechanism (as you pointed) that throws a nice error telling you how to fix the issue.
