### ISSUE TITLE
[Notifier] Support WhatsApp notifier

### ISSUE THREAD

**Issue by Arman-Hosseini** [symfony/symfony#35878]
**Description**  
Create WhatsApp notifier to send notifications to the designated user.
Implementing this feature using the WhatsApp Unofficial API.

**Comment by javiereguiluz** [comment]
I'm afraid we can't use an unofficial API to implement a Notifier feature, moreover for such an important service as WhatsApp.

We should use https://www.whatsapp.com/business/api but it seems to be only for medium and large businesses.
