### ISSUE TITLE
[Notifier] Support Google Chat

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#35875]
**Description**  
[Google Chat](https://gsuite.google.fr/intl/en/products/chat/) is a similar to Slack for Google Suite consumers. 

Specificities :
- Every message creates a new thread or a response to an existing thread (if the `thread.name` is sent)
- Authentication uses Google Signin or [webhook url](https://developers.google.com/hangouts/chat/quickstart/incoming-bot-node) for simplicity.
- 2 exclusive formats : [basic](https://developers.google.com/hangouts/chat/reference/message-formats/basic) or [card](https://developers.google.com/hangouts/chat/reference/message-formats/cards)

API Documentation : https://developers.google.com/hangouts/chat

**Example** 

```php
use Symfony\Component\HttpClient\HttpClient;

$httpClient = HttpClient::create();
$webhookURL = '<INCOMING-WEBHOOK-URL>';

$response = $httpClient->request('POST', $webhookURL, [
    'json' => ['text' => 'Hello from a PHP script!'],
])->toArray();

$response = $httpClient->request('POST', $webhookURL, [
    'json' => ['text' => 'Response to the thread', 'thread' => ['name' => $response['thread']['name']]],
])->toArray();
```

![Screenshot_20200227-221612](https://user-images.githubusercontent.com/400034/75487527-d3c05400-59ae-11ea-9432-fc76922b5adf.png)

**Comment by fabpot** [comment]
@GromNaN Would you like to work on a PR?

**Comment by GromNaN** [comment]
Yes, I'll work on it. Using weekhook URLs and simple text messages for beginning.

It there something existing for keeping the thread ID ?
