### ISSUE TITLE
[WebProfilerBundle] Add Nonce Generator as a dependency through config

### ISSUE THREAD

**Issue by pavlakis** [symfony/symfony#35883]
**Description**  

The `WebProfiler` will generate a `nonce` but when setting up a custom Content Security Policy, the same nonce should be able to be reused and passed in the response header in order to match other `script` tags where it needs to be used.

If we could have a `NonceGeneratorInterface` which is not coupled to the `WebProfiler` bundle - as that is only used on development environment - and can optionally add it to the `web_profiler.yaml` config so it can then be reused elsewhere too (e.g. Twig helper, CSP library)

**Example**  

The `Nonce` interface can be moved in its own namespace in the `Security` component.

e.g.
```
namespace Symfony\Component\Security\Core\Csp;

interface NonceGeneratorInterface
{
     public function generate(): string;
}

```

The current class will need to use this interface:

```
namespace Symfony\Bundle\WebProfilerBundle\Csp;
class NonceGenerator implements NonceGeneratorInterface { ... }
```

And also update the `ContentSecurityPolicyHandler` class to accept the interface:

```
class ContentSecurityPolicyHandler
{
   // ...
    public function __construct(NonceGeneratorInterface $nonceGenerator)
    {
      // ...
    }
}
```

Then the `dev/web_profiler.yaml` could have one more option:

```
web_profiler:
    nonce:
        - App\Csp\NonceGenerator
```

**Comment by stof** [comment]
It is perfectly valid to have multiple nonce in the CSP header. So I don't think we need to make the WebprofilerBundle nonce configurable at all.

Note that if you want to deal with CSP nonce on your own scripts, https://github.com/nelmio/NelmioSecurityBundle/ provides the feature.

**Comment by pavlakis** [comment]
@stof thank you. I wasn't aware you can have multiple nonce in the CSP header. That actually solved my problem.
