### ISSUE TITLE
[DI] XmlFileLoader bad error message

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#35886]
Today we debugged an error message coming from `XmlFileLoader` in the DI component:

```
File some.xml does not contain valid XML, it is empty.
```

Coming from

https://github.com/symfony/symfony/blob/421c7f8fcd42aa64d1d7d6adee0558993ede9a41/src/Symfony/Component/Config/Util/XmlUtils.php#L125-L128

The file is not empty :) removing the `@` reveals the true error: 

```
PHP Warning:  file_get_contents(file.ext): failed to open stream: Permission denied 
```

So if `$content` is false (before trim casts to string) we cant assume an empty file. Ideally the original errors bubbles up.

**Comment by przemyslaw-bogusz** [comment]
@ro0NL Are you looking for volunteers?

**Comment by ro0NL** [comment]
Yes, go for it :}
