### ISSUE TITLE
Serializer class __construct PHPdoc not suitable for phpstorm

### ISSUE THREAD

**Issue by EvgeniiR** [symfony/symfony#35896]
**Description**

\Symfony\Component\Serializer\Serializer class method __construct() have php-doc:
```
/**
 * @param (NormalizerInterface|DenormalizerInterface)[] $normalizers
 * @param (EncoderInterface|DecoderInterface)[]         $encoders
 */
```
It can't be parsed by either PHPstorm or Psalm, so we don't receive warnings when providing incorrect arguments(only exception in runtime)

**How to reproduce**  
See https://github.com/symfony/serializer/blob/0faaab526695708140cbb624f6ebf9ac18cbe566/Serializer.php#L71

**Possible Solution**  
Change PHPdoc to 
```
/**
 * @param NormalizerInterface[]|DenormalizerInterface[] $normalizers
 * @param EncoderInterface[]|DecoderInterface[]         $encoders
 */
```

**Comment by ro0NL** [comment]
Most likely that becomes valid PHPDoc ... as it's in draft currently (PHP-FIG PSR-5)

It seems psalm understands: https://psalm.dev/r/669c0b478b

The proposal solution is a different behavior. Im :-1:  for that.

We can try generics e.g. `array<int, NormalizerInterface|DenormalizerInterface>`, but conceptually it's equal. Though, if such a variant improves PHPStorm you might try a PR.

Ultimately tools should adapt standards, not vice versa.

**Comment by EvgeniiR** [comment]
> It seems psalm understands: https://psalm.dev/r/669c0b478b

Strange, but only with primitive types - https://psalm.dev/r/b1388ba698

You are right about standards, but afaik PSR-5 is only on draft stage now.

Also, a little more searching I found a few more phpdocs like this in symfony components(
vendor/symfony/mime/Address.php:99
vendor/symfony/mime/Part/Multipart/FormDataPart.php:29
vendor/symfony/mime/Header/Headers.php:62
vendor/symfony/console/Descriptor/TextDescriptor.php:301
)
