### ISSUE TITLE
Expected to find class "Whatever" in file "/whereever" while importing services from resource "/**/*.php"

### ISSUE THREAD

**Issue by oojacoboo** [symfony/symfony#35908]
**Symfony version(s) affected**: 3.0 - 5.0

**Description**  
When autowiring PHP classes for a given resource, if there is a syntax error in a PHP file, the error states that it expected to find the class, but was not found.

**How to reproduce**  
Put some bad syntax in a PHP file and try to autowrire it.

**Solution**  
Add a better error that clearly states that the file contains syntax errors, if possible.  If not, include the syntax error suggestions in the error message.

**Additional context**  
I've found myself hitting this issue multiple times and wasting WAY too much time on it.  It's always little things that even a quick scan doesn't really highlight with static analysis tools, etc.  The issue is there, it's clear, but it's sometimes easy to overlook and this will be the first error that your application hits - which is VERY misleading.

**Comment by nicolas-grekas** [comment]
This should be fixed in the versions that have been released today. Please upgrade and report back.

**Comment by xabbuh** [comment]
Closing here for now. We can consider to reopen if there is a reproducible example application using the latest patch releases.

**Comment by oojacoboo** [comment]
@nicolas-grekas works great - get a `ParseError` now, as it should be.

**Comment by php4fan** [comment]
Is this supposed to be fixed in Symfony 5.4?

I'm getting this error and I don't know whether it's a parse error in my case or something else (pretty sure it's something else) but it's definitely not what the error says. The class is there with the expected namespace in the expected file.

**Comment by php4fan** [comment]
It's not a parse error in my case.

What other cases can cause this error other than what the error says, that is, when the class definitely _is_ in the file?

**Comment by xabbuh** [comment]
@php4fan Please open a new issue and provide an example application that allows to reproduce your issue.
