### ISSUE TITLE
[Framework-Bundle] Allow json helper in AbstractController to accept native json data as input 

### ISSUE THREAD

**Issue by llaville** [symfony/symfony#35900]
**Description**  
See my PR attempt at https://github.com/symfony/framework-bundle/pull/29, with explains and unit test to demonstrate the issue.

**Comment by xabbuh** [comment]
I do not really see the advantage of having a call like `return $this->json($json, 200, [], [], true);` instead of `return JsonResponse::fromJsonString($json);`.

**Comment by ro0NL** [comment]
agree, this only serves a cosmetic purpose; "a good looking conditional return". But IMHO it's more implicit even.

I'd propose

```
try {
  return ...;
} catch {
  return ...;
}
```

for your case. Or simply `return $json ? ... : ...;`.

If anything, for the base controller id expect `jsonString()`, thus not solving your case ;) as it would still be `return !$json ? $this->json() : $this->jsonString()`.

**Comment by llaville** [comment]
@ro0NL I don't like your design proposal , because (not in my example) we can also use the `finally` keywork (on try-catch) and your return strategy begin a bit difficult to handle.

@xabbuh Finally i won't use the json helper, and stay on standard strategy to handle a `JsonResponse` object that accept my use case.
