### ISSUE TITLE
[process] How to return a subprocess value?

### ISSUE THREAD

**Issue by techno-express** [symfony/symfony#35919]
**Symfony version(s) affected**: 
Process 5.0.4

**Description**  
Need a way to retrieve just the last output to `stdout`, or in my case the return value from the process. Currently only all output, or incrementally, which I shouldn't have to read first. 
- I want the last line written to `stdout`. 
- None of your tests use or check for a `return` value.

**How to reproduce**  
In tests at:
https://github.com/symfony/process/blob/55bebe44b76b82d618e9eeea83f6562ad03a1a67/Tests/ProcessTest.php#L1212
Could check for:
`$this->assertSame('pong', $process->getResult());`
in tests at:
https://github.com/symfony/process/blob/55bebe44b76b82d618e9eeea83f6562ad03a1a67/Tests/ProcessTest.php#L1242
Could check for:
`$this->assertSame('456', $process->getResult());`

**Possible Solution**  
add: `private $result;`
add to method `addOutput(string $line)`:  `$this->result = $line;`
```
    /**
     * Return the last/final line `written` to output.
     *
     * @return mixed
     */
    public function getResult()
    {
        return $this->result;
    }
```

**Additional context**  
Additional there is not way to return a final result in any of your tests.
Here is a rework of one of your tests 
https://github.com/symfony/process/blob/55bebe44b76b82d618e9eeea83f6562ad03a1a67/Tests/ProcessTest.php#L1195
```
    public function testGetResult()
    {
        $p = $this->getProcessForCode("
                echo 'hello ';
                usleep(10000);
                echo 'child';
                usleep(10000);
                return 3;
            ");

        $lastResult = null;
        $p->start(function ($type, $data) use (&$lastResult) {
            $lastResult = $data;
        });

        $p->wait();
        $this->assertSame('hello child', $p->getOutput());
        $this->assertSame('hello child', $lastResult);
        // will fail, the return value not captured
        $this->assertSame('hello child3', $lastResult);
        // so will still fail with the change
        $this->assertSame(3, $p->getResult());
    }
```
I have a package that wraps this library with the above test, but `getOutput()` returns full with `3` encoded. With the change i could a least get that part directly to decode, without local changes.
https://github.com/symplely/processor/blob/147b6328981559255401b70cbba943f101e6f16a/tests/ProcessorTest.php#L134. 

Maybe the way your tests setup to not return any usable value?

**Comment by nicolas-grekas** [comment]
A subprocess is a separate process. The return value from a PHP script, as in `return 3;` is ignored, there is no way around.
Processes have only few limited ways to communicate with each other.
Writing to stdout/stderr is one of them: you can "echo 3;" instead and parse the output from the main process.

I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the support channels. Thank you for understanding.

**Comment by techno-express** [comment]
> Processes have only few limited ways to communicate with each other.

What? 
It seems you missed the point, or no foresight.
For one, I wasn't looking for a solution. I already had one for you. I already get a return value from my scripts in the links i posted.  So:

> Writing to stdout/stderr is one of them: you can "echo 3;" instead and parse the output from the main process.

Makes no sense, your tests doesn't pick it up. And still from your `"echo 3;"`
How would you get just that part separate from the other output? 
The solution would do just that. It should have been clear, from the test/example the shortcoming of your tests, they wasn't capturing the return or even the just the last the thing written.

> I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the support channels. Thank you for understanding.

I seems you looked at the title and left it there, you didn't review or anything, I would hate to have you in charge of any security issues.

**Comment by Pierstoval** [comment]
Return value might be relevant for PHP scripts only, then, but this means that instead of running a sub-process, you actually need to **include** the PHP file. Else, any `return` statement in a PHP script executed in a sub-process can't be fetched at all (it's PHP, so the `return` is executed in the PHP engine, and the process itself cannot know that).

**Comment by techno-express** [comment]
> Retrieving the last `stdout` line should be possible with `$lastLine = end($process->getOutput());`

Maybe add a test for that, I already have a working solution. Also, isn't `end()` just for arrays?

> Else, any return statement in a PHP script executed in a sub-process can't be fetched at all (it's PHP, so the return is executed in the PHP engine, and the process itself cannot know that).

The links I provided do just the opposite. I get the return value to `stdout` right from symfony process. It's a script the process will execute any passed in function in a **try/catch** block the result to `stdout`, or `stderr` on exception.

**Comment by Nyholm** [comment]
Hey. 
Im Tobias and I work with the [CARE team](https://symfony.com/doc/current/contributing/code_of_conduct/care_team.html). 

@techno-express, I would like to remind you about our [code of conduct](https://symfony.com/doc/current/contributing/code_of_conduct/code_of_conduct.html). Comments like you made on this PR is a violation to our COC. I would recommend you to use a more welcoming language and be more respectful. That will create a better community for everyone. 

It is okey to have different opinions or to think that somebody else is wrong. But there are better ways to express your dissatisfaction.

**Comment by techno-express** [comment]
Well, replies offering a solution I already implemented and stated, does
not seem like anyone actually read the submition.

At least address that first.

**Comment by Nyholm** [comment]
I understand that you may be annoyed. It is okey to be annoyed. 
I understand that you think others are incorrect. That is okey too. 
It is also okey to make a possible wrong decision and close a PR. 

What is **not** okey is: 
- Insulting/derogatory comments and personal attacks
- Public or private harassment
- Other conduct which could reasonably be considered inappropriate in a professional setting

... among other things stated in the [Code of conduct](https://symfony.com/doc/current/contributing/code_of_conduct/code_of_conduct.html)

--------------

I am fine leaving this PR unlocked for now. But if there is more discussions about CoC or more CoC violations, then I'll lock it. 

If somebody have questions about the CoC, feel free to email me at care@symfony.com.

**Comment by techno-express** [comment]
I think someone been misreading, there is no PR open, and did not request
one.

Your reply should  be directed elsewhere, the issue been pre close, without
addressing the actual contents. The replies afterwards was also misplaced.

At least point out each part you all detailed, issue submit requirements.
That no seem to have read.

Everybody do have there opinions, code is not one, it either does want said
or not , and that can be proven.
