### ISSUE TITLE
deprecate & remove the PlaintextPasswordEncoder

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony#35927]
Symfony currently offers a [PlaintextPasswordEncoder](https://github.com/symfony/symfony/blob/f632b76824f5048124d39069e7762025b43ee124/src/Symfony/Component/Security/Core/Encoder/PlaintextPasswordEncoder.php#L21) that was introduced back in 2010ish. In an effort to move the framework forward and not provide a means to implement / "encourage" bad security practices, I think we should:

- deprecate the `PlaintextPasswordEncoder::class` in the next minor 5.x release
- remove the `PlaintextPasswordEncoder::class` in the next major (6.x) release

I can't think of any reason to keep this encoder considering it was [de-referenced](https://github.com/symfony/symfony-docs/issues/9299) from the docs in 2018. 

Thoughts and opinions?

_I'll reference the PR for deprecation here as soon as I have it written_

**Comment by jrushlow** [comment]
see PR https://github.com/symfony/symfony/pull/35929

**Comment by xabbuh** [comment]
I suggest to keep the encoder. Being able to use it is quite handy in tests when you just need a password encoder and do not really care about the used hashing algorithm.

**Comment by jrushlow** [comment]
> I suggest to keep the encoder. Being able to use it is quite handy in tests when you just need a password encoder and do not really care about the used hashing algorithm.

I agree, as I'm finding out writing up the PR with a test case in the security bundle. But wouldn't it make more sense to have a test fixture for handling plain text passwords rather than a public encoder that could be use in a "real" app out in the wild?

Granted it would add an additional layer of complexity to those tests needing such functionality..

**Comment by fbourigault** [comment]
It's a must have for functional testing. In most apps test suite, using the plaintext encoder instead of the auto encoder make the whole testsuite run at least 10 times faster.

**Comment by jrushlow** [comment]
Any other ideas that would allow for a plain password encoder solely for testing purposes while preventing the use of such an encoder in a app? Perhaps moving this encoder to a phpunit-bridge helper class or something along those lines?

**Comment by fbourigault** [comment]
> Perhaps moving this encoder to a phpunit-bridge helper class or something along those lines?

I have an app that doesn't use PHPUnit for functional tests but Behat.

I don't think you need to change anything to this encoder.

As Symfony promotes the `auto` encoder, there is no encouragements about bad security.

Keeping things as is allows to save lots of CPU cycles, mainly on CI by not encoding passwords.

Thinks about it as green IT ;)

**Comment by fabpot** [comment]
I'm against this change as well. The plain text encoder has been there for testing purposes from day one. Maybe a sentence in the phpdoc of the class can hint about when to use it.

**Comment by xabbuh** [comment]
I am closing here as we are not going to remove the `PlaintextPasswordEncoder`. PR welcome if anyone wants to improve the docblock of the class.
