### ISSUE TITLE
[Form] Validator listener

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#35922]
**Description**  

Hi everyone 👋 

During the submission of a form, the `ValidationListener::validateForm` is called once the form is submitted, this subscriber trigger the validation and map the violations into the form fields.

The idea here is to allow the "form" to dispatch (don't know if it worth the work or if it's a good idea) a new event (maybe `Symfony\Component\Form\FormEvents::SUBMISSION_FAILURE`) that allows us to "listen" the failures and maybe trigger a session message (or a Mercure one when using it)

**Example**  

AFAIK, this implementation requires to edit the `FormEvent` class and the `Form` class, maybe following these lines: 

```php

$this->submitted = true;
$this->modelData = $modelData;
$this->normData = $normData;
$this->viewData = $viewData;

if ($dispatcher->hasListeners(FormEvents::POST_SUBMIT)) {
   $event = new FormEvent($this, $viewData);
   $dispatcher->dispatch(FormEvents::POST_SUBMIT, $event);
}

// Dispatch the submission failure event
if ($this->submitted && !$this->isValid()) {
    $event = new FormEvent($this, $form);
    $dispatcher->dispatch(FormEvents::SUBMISSION_FAILURE, $event);
}
```

Thanks for the feedbacks 🙂

**Comment by xabbuh** [comment]
Could you explain the benefit this would have over registering an event listener on the `POST_SUBMIT` event and checking for any errors there?

**Comment by Guikingone** [comment]
Hi @xabbuh 👋 

Sorry for the delay, yes, my bad, I was thinking about a specific event for something not related to the `Form` and I've realised that there is no benefit of dispatching a custom event, the `POST_SUBMIT` is enough. 

I'm closing this issue, thanks for the feedback 🙂
