### ISSUE TITLE
[PhpUnitBridge] Support for phpunit/phpunit:^9

### ISSUE THREAD

**Issue by localheinz** [symfony/symfony#35952]
**Description**  

[`phpunit/phpunit:9.0.0`](https://github.com/sebastianbergmann/phpunit/releases/tag/9.0.0) was released on February 7, 2020.

When can we expect to be able to use this with `symfony/phpunit-bridge`?

What needs to be done to make it work?

**Comment by wouterj** [comment]
Seems like it should be compatible already: https://github.com/symfony/symfony/issues/35662 ?

**Comment by localheinz** [comment]
Ha, thanks for the quick feedback, @wouterj - going to take a look!

👍

**Comment by localheinz** [comment]
Thank you, @wouterj - works for me!

**Comment by xabbuh** [comment]
Thank you for the confirmation Andreas.
