### ISSUE TITLE
Numerical keys used with tagged_iterator/tagged_locator reset to 0..n-1

### ISSUE THREAD

**Issue by CthulhuDen** [symfony/symfony#35953]
**Symfony version(s) affected**: 5.0

**Description**  
When !tagged_iterator have index_by set, and the corresponding tag property values are numeric, the keys actually reset to 0-based index. See repro PR

**How to reproduce**  
See PR #35954

**Comment by nicolas-grekas** [comment]
Can you check if #35957 doesn't fix the issue already?
