### ISSUE TITLE
createNamedBuilder $name argument type-hinted

### ISSUE THREAD

**Issue by leoborel** [symfony/symfony#35950]
**Symfony version(s) affected**:  5.0.5

**Description**  
In Symfony 4.4.5, the first argument passed to createNamedBuilder wasn't type-hinted, now it's type-hinted, but 

> $this->registry->getType($type)->getBlockPrefix()

 return null, so I got this error : 

> Argument 1 passed to Symfony\Component\Form\FormFactory::createNamedBuilder() must be of the type string, null given, called in C:\xampp\htdocs\admin-emfor-bfc\vendor\symfony\form\FormFactory.php on line 52

**How to reproduce**  
Creating a form

**Possible Solution**  
```
public function createNamedBuilder(?string $name, string $type = 'Symfony\Component\Form\Extension\Core\Type\FormType', $data = null, array $options = [])
```

instead of 

```
public function createNamedBuilder(string $name, string $type = 'Symfony\Component\Form\Extension\Core\Type\FormType', $data = null, array $options = [])
```

**Comment by xabbuh** [comment]
The question then is why does `getBlockPrefix()` return `null` in your case?

**Comment by leoborel** [comment]
@xabbuh I had a custom FormType (FiltreType) which doesn't works without (in Symfony 4.4.5) :
```
public function getBlockPrefix()
    {
        return null;
    }
```
When I tried to return a string like 'filtre' or something else it doesn't works.

Now (in Symfony 5.0.5) I may replace null by '', but I don't think it's a good way to do it. Probably something I didn't understand ..

**Comment by xabbuh** [comment]
Well, `getBlockPrefix()` is documented to return a string in the `FormTypeInterface` and in the `ResolvedFormTypeInterface`. From what can see return the empty string would indeed be the solution in your case.

**Comment by stof** [comment]
Be careful, the empty string might lead to weird behavior during the form rendering (form themes are the main reason for `getBlockPrefix` to exist, and the reason for its naming). I strongly recommend against that.

What do you mean when saying `When I tried to return a string it doesn't work` ? `it doesn't work` is not an accurate description of your issue.

**Comment by fmonts** [comment]
> I strongly recommend against that.

Do you recommend any alternative to obtain a form like this:

    <select name="countries[]" ...>

Instead of:

    <select name="form_name[countries][]" ...>
