### ISSUE TITLE
Undefined variable zvalIsRef after upgrading to php 7.4

### ISSUE THREAD

**Issue by sasokovacic** [symfony/symfony#35964]
**Symfony version(s) affected**: x.y.z

symfony/var-dumper v4.2 used by Laravel 5.8

**Description**  

I'm getting "Undefined variable zvalIsRef" inside of the "symfony/var-dumper/Cloner/VarCloner.php" file on line 268 after upgrading to php 7.4.0. Before I was using php 7.2 and it worked fine.

**How to reproduce**  

Install Laravel 5.8 to a php 7.4.0 web server. Dump something using dump() method inside of a controller or route closure function  and make a REST request.

See the image bellow:

![image](https://user-images.githubusercontent.com/4608330/75906284-bffd6d80-5e46-11ea-90b0-69963439ddf7.png)

**Comment by nicolas-grekas** [comment]
Can you upgrade to 7.4.3 and try again?

**Comment by sasokovacic** [comment]
I've tested it on staging server and it works for php 7.4.3. Is there any chance you will fix it for php 7.4.0? If not, then I'll have to contact Devilbox team to add new php image. This could take time...

**Comment by nicolas-grekas** [comment]
Ok thanks for the confirmation. Nope, we're not going to try to make it work on 7.4.0, that'd be a waste of time.
