### ISSUE TITLE
Symfony 4.4 route /{slug}  existing routes

### ISSUE THREAD

**Issue by demahom** [symfony/symfony#35977]
I have the entity Page identified by slug. Also I have the action to view a page in the Page controler :
 
 
`class PageController extends AbstractController`
`{`
    `/**`
    ` * @Route("/{slug}", name="fronend_page")`
     `*/`
    `public function show(Page $page)`
    `{`
        `return $this->render("font_end/page/show.html.twig", [`
           ` "page" => $page,`
   `     ]);`
  `  }`
`}
`

I am looking for good practice to validate the slug ( check if exist in routes) before save it in the database without use prefixes 
Example :

route exist  : @Route ("/blog")

check if blog exist before create slug :  /{slug}   =   /blog   

thanks

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
