### ISSUE TITLE
[Form] TimeType does not work in new Edge

### ISSUE THREAD

**Issue by jackbentley** [symfony/symfony#35989]
**Symfony version(s) affected**: all

**Description**  
When submitting a form via Edge using the `TimeType`; Edge will submit the value with both seconds and milliseconds every time regardless of the `step` attribute (e.g. `20:11:00.000`). This is valid [according to W3C](https://www.w3.org/TR/2012/WD-html-markup-20120329/input.time.html).

It looks like Symfony is unable to parse the milliseconds in the `DateTimeToStringTransformer` and this then causes an invalid value.

This only seems to be an issue since Edge has moved to Webkit.

**How to reproduce**  

1. Create a form with a TimeType
2. Attempt to submit the form with a value in Edge 80+

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you please be a bit more precise? What does "does not work" mean?

**Comment by jackbentley** [comment]
@xabbuh Apologies, I submitted the bug report before typing the info in. Have updated the description now.

**Comment by jackbentley** [comment]
My current work around is to add an event listener to strip the parts of the value that aren't expected by the `TimeType`'s `$format` in the `DateTimeToStringTransformer`.

The `array_slice` here only give hours and minutes, as my input doesn't use the `with_seconds` option.

```php
$builder->get('time')->addEventListener(
    FormEvents::PRE_SUBMIT,
    function (FormEvent $e) {
        return $e->setData(
            implode(
                ':',
                array_slice(
                    explode(
                        ':',
                        explode(
                            '.',
                            $e->getData()
                        )[0]
                    ),
                    0,
                    2
                )
            )
        );
    }
);
```

**Comment by xabbuh** [comment]
@jackbentley Does that mean that Edge will always submit the value in the `20:11:00.000` format?

**Comment by jackbentley** [comment]
@xabbuh Correct. And it looks like the type is expecting `hh:mm` or `hh:mm:ss` if you have `with_seconds`.

**Comment by xabbuh** [comment]
@jackbentley Can you confirm that #36020 fixes this issue?
