### ISSUE TITLE
Doctrine migrations immediately aborted in 5.0.5 and 4.4.5

### ISSUE THREAD

**Issue by jacekpl** [symfony/symfony#35988]
**Symfony version(s) affected**: 5.0.5 and 4.4.5

**Description**  
Yesterday I updated some of my projects to the newest versions of Symfony. I noticed that both in Github Actions and Bitbucket Pipelines my CI/CD process failed (with no other code changes made). After downgrading back to 4.4.4 and 5.0.4 everything went fine.

**How to reproduce**  
Create Symfony project in the newest version in Bitbucket or Github with enabled CI/CD and mysql + sample migration. I've created sample repository with minimal code possible to show how it looks like.
 
Master branch (5.0.5): https://github.com/jacekpl/symfony-migrations-issue
Failed pipeline for master: https://github.com/jacekpl/symfony-migrations-issue/runs/490266168?check_suite_focus=true

Delevop branch (5.0.4): https://github.com/jacekpl/symfony-migrations-issue/tree/develop
Ok pipeline for develop: https://github.com/jacekpl/symfony-migrations-issue/runs/490130516?check_suite_focus=true

**Additional context**  
Expected bahaviour:
```
                    Application Migrations                    
                                                              

Migrating up to 20200306090544 from 0

  ++ migrating 20200306090544

     -> CREATE TABLE test (id INT AUTO_INCREMENT NOT NULL, message VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB

  ++ migrated (took 32.8ms, used 28M memory)

  ------------------------

  ++ finished in 34.5ms
  ++ used 28M memory
  ++ 1 migrations executed
  ++ 1 sql queries
```

Actual behaviour in 5.0.5:
```
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)
            
  Aborted.  
```

**Comment by Tobion** [comment]
This is a change in doctrine migrations, not Symfony. All you need to do is add `--no-interaction` as option to the migration command so it does not try to ask for confirmation.

**Comment by jacekpl** [comment]
`--no-interaction` will fix it, but the behaviour has changed between patch versions (and probably it shouldn't).

**Comment by ElisDN** [comment]
@Tobion No, it is a change in Symfony #33897, not Migrations. It breaks all `composer app ...` calls.

**Comment by bendavies** [comment]
adding `--no-interaction` is not the solution. #33897 should be reverted.

**Comment by faizanakram99** [comment]
I also found it after upgrading to sf 4.4.5 but just added -n in our build scripts to fix this.
It is easy but it is still a BC break in minor minor version upgrade which is not optimal imho.
