### ISSUE TITLE
[Dependency-injection] CustomNormalizer not injected until set with priority

### ISSUE THREAD

**Issue by metfan** [symfony/symfony#35991]
**Symfony version(s) affected**: 4.4.5

**Description**  
After upgrade from 4.4.4 to 4.4.5, I see my app crashed because of missing CustomNormalizer.
I must add priority on the tag to see this normalizer injected in Serializer.

**How to reproduce**  
With this simple config in service.yaml CustomeNormalizer is injected to Serializer before 4.4.5
```yaml
Symfony\Component\Serializer\Normalizer\CustomNormalizer:
```

with 4.4.5 I must write:
```yaml
Symfony\Component\Serializer\Normalizer\CustomNormalizer:
    tags:
        - { name: serializer.normalizer, priority: 100 }
```

**Comment by metfan** [comment]
probably related to https://github.com/symfony/symfony/issues/35916

**Comment by xabbuh** [comment]
@metfan Can you confirm that #35957 also fixes this issue?

**Comment by metfan** [comment]
@xabbuh yes #35957 fix this issue, I just checked.
