### ISSUE TITLE
[Mailer] EsmtpTransport TLS option

### ISSUE THREAD

**Issue by Flower7C3** [symfony/symfony#36005]
**Symfony version affected**: 5.0.5

**Description**  
I am not sure if it is really bug, or I am using something in wrong way. But when I want to setup EsmtpTransport with no TLS option it will be launched anyway. It was created [on Aug 19, 2019](https://github.com/symfony/mailer/commit/4e6a8b24c10803d780bebfe5c045e72b0716da4a#diff-b38d185c710fdfad602286b083d77929R124) and still exists in [master code](https://github.com/symfony/mailer/blob/2e32c62adca8185b9f31646d53ad774ff7666f38/Transport/Smtp/EsmtpTransport.php#L109).

**Comment by sebheitzmann** [comment]
i've got the same error.

`MAILER_DSN=smtp://mail.2le.net:25`

and when I try to send something :
```
In SocketStream.php line 154:
                                                                                                     
  Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:  
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed               
                                                                                                     
```

**Comment by Flower7C3** [comment]
I find out one solution for this is to disable SSL verify_peer and verify_peer_name. But I still thinks that there is a bug in the code I mention above.

```
$socketStreamOptions = json_decode('{"ssl":{"verify_peer":false,"verify_peer_name":false}}');

 /** @var Transport\Smtp\EsmtpTransport $transport */
$transport = Transport::fromDsn($dsn);

/** @var Transport\Smtp\Stream\SocketStream $socketStream */
$socketStream = $transport->getStream();
$socketStream->setStreamOptions($socketStreamOptions);

$mailer = new Mailer($transport);
```

**Comment by stof** [comment]
Well, if your SMTP server advocates STARTTLS support but does not have a valid cert, the bug is in your SMTP setup, not in Symfony.

**Comment by sebheitzmann** [comment]
Thanks for the advice. I will check that.

**Comment by sebheitzmann** [comment]
It's ok. The posfix config was wrong. Sorry. You can close this issue
