### ISSUE TITLE
[Mailer] - DKIM Signer

### ISSUE THREAD

**Issue by Hadrien45** [symfony/symfony#36014]
Hi,

I want to switch from Swift Mailer to the Symfony Mailer component.  
In Swift Mailer, I use a DKIM signature (cf the example below).  
I don't find this signer into the Mailer component documentation.  
```php
# In Swift_Mailer
$privateKey = file_get_contents($this->dkim_private_key);
$domainName = 'MY_DOMAIN';
$selector = 'default';
$signer = new \Swift_Signers_DKIMSigner($privateKey,$domainName,$selector);
```
Thanks

**Comment by OskarStark** [comment]
@sstok I know you were working hard on the signage topic, maybe you can have a look at this issue?

Thanks 🙏

**Comment by MockingMagician** [comment]
DKIM sign possibility is really missing here... :sob:

**Comment by fabpot** [comment]
See #37165

**Comment by Hadrien45** [comment]
Thanks !

**Comment by MockingMagician** [comment]
Great!
