### ISSUE TITLE
[Env] Web and console load different environments

### ISSUE THREAD

**Issue by Tarasovych** [symfony/symfony#36019]
**Symfony version(s) affected**: 5.0.4

**Description**  
I noticed, that web `APP_ENV` and console `APP_ENV` are different, after I created custom `stage` environment.

I've added `dd($_ENV);` in the `bootstrap.php` (5th line from the bottom):
```php
<?php

use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__) . '/vendor/autoload.php';

// Load cached env vars if the .env.local.php file exists
// Run "composer dump-env prod" to create it (requires symfony/flex >=1.2)
if (is_array($env = @include dirname(__DIR__).'/.env.local.php') && (!isset($env['APP_ENV']) || ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV']) === $env['APP_ENV'])) {
    foreach ($env as $k => $v) {
        $_ENV[$k] = $_ENV[$k] ?? (isset($_SERVER[$k]) && 0 !== strpos($k, 'HTTP_') ? $_SERVER[$k] : $v);
    }
} elseif (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
} else {
    // load all the .env files
    (new Dotenv(false))->loadEnv(dirname(__DIR__) . '/.env');
}
dd($_ENV); //<---
$_SERVER += $_ENV;
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? null) ?: 'dev';
$_SERVER['APP_DEBUG'] = $_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? 'prod' !== $_SERVER['APP_ENV'];
$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = (int) $_SERVER['APP_DEBUG'] || filter_var($_SERVER['APP_DEBUG'], FILTER_VALIDATE_BOOLEAN) ? '1' : '0';
```
After that I went to a web page - I got
```
//other env variables
"APP_ENV" => "loc"
```
but in the console (`$ php bin/console`) I got
```
//other env variables
"APP_ENV" => "stage"
```

My `.env`:
```
APP_ENV=${APP_ENV} # so I can handle it using Docker environment
APP_SECRET=...
DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7
```

My `.env.stage`:
```
APP_ENV=stage
```

Inside the contained `$ echo $APP_ENV` outputs `stage`.

I've tried to `$ composer dump-env stage`, because of
> // Load cached env vars if the .env.local.php file exists
// Run "composer dump-env prod" to create it (requires symfony/flex >=1.2)

but web environment didn't changed.

Am I missing somethig?

Thanks in advance!

**Comment by strawburrypokki** [comment]
My guess is the env variable you setup from docker is not provided to your PHP server.
By default, the server env var are cleared and will not be available in `$_SERVER`.
Look for the `clear_env` option (https://www.php.net/manual/fr/install.fpm.configuration.php)

Please, keep in mind that this is not a production safe configuration.

**Comment by Tarasovych** [comment]
> My guess is the env variable you setup from docker is not provided to your PHP server.

But being inside PHP container, `$ echo $APP_ENV` outputs `stage`...
