### ISSUE TITLE
SerializerErrorRenderer automatically replaces HtmlErrorRenderer

### ISSUE THREAD

**Issue by umulmrum** [symfony/symfony#36013]
**Symfony version(s) affected**: 4.4.5, most likely 4.4.*.

**Description**  
Not exactly sure if this should be called a bug, but at least for me it is unexpected.
I'm currently replacing the Twig ExceptionController as it is deprecated and set `twig: exception_controller: ~` to use the ErrorController from HttpKernel. When the Serializer component is installed and enabled, errors are displayed as JSON string instead of pretty HTML. I didn't see any mechanism to control this behavior (except a compiler pass), so it seems to assume that any application using the Serializer is an API.

Could someone explain if this works as intended? Thanks!

**How to reproduce**
- Setup "standard" web project.
- Set config `twig: exception_controller: ~`.
- Install Serializer component.
- Throw any exception.

**Possible Solution**  
~

**Additional context**  
When the Serializer is installed, FrameworkExtension will load serializer.xml. There an alias is set unconditionally like this: `<service id="error_renderer" alias="error_renderer.serializer" />`. This replaces the default error_renderer alias that points to the HtmlErrorRenderer.

**Comment by yceruto** [comment]
That's the expected behavior for non-HTML request formats.

I failed to reproduce the issue on 4.4. Could you create a small app that reproduces your issue and share it with us?

> When the Serializer is installed, FrameworkExtension will load serializer.xml. There an alias is set unconditionally like this: <service id="error_renderer" alias="error_renderer.serializer" />. This replaces the default error_renderer alias that points to the HtmlErrorRenderer.

Looks at `error_handler.error_renderer.serializer` service definition and you'll see the `error_renderer.html` service is being injected there and works as fallback renderer for unknown serializer formats.

**Comment by yceruto** [comment]
> and works as fallback renderer for unknown serializer formats.

that's the case for HTML requests.

**Comment by umulmrum** [comment]
Thanks for the pointer, it helped in finding the issue in my application code: There is a custom JsonEncoder that accepts the `html` format accidentally. Therefore `NotEncodableValueException` is never thrown and the fallback never called. Fixing the encoder solved the problem.

Thank you very much and sorry for the inconvenience.
