### ISSUE TITLE
how to add a customized logger class instead of LoggerChain

### ISSUE THREAD

**Issue by engharb** [symfony/symfony#36011]
is it possible to autowire or define a customized logger class globally instead of LoggerChain via service.yml file?
Because I can not read a private logger variable from LoggerChain class.

```
# in the repository
$logger = $this->getEntityManager()->getConnection()->getConfiguration()->getSQLLogger() 
```

I am using symfony 4.4.4

Thanks!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
