### ISSUE TITLE
[Lock] add $lock->isAquiredBySomeone to check if lock is acquired by someone, without acquiring it

### ISSUE THREAD

**Issue by micheleorselli** [symfony/symfony#36024]
**Description**  
As of now there is no way to check if a lock is acquired by someone, without acquiring it. This could be useful as a way to see if another process is running without stealing the lock. I propose to implement this by adding a method `isAquiredBySomeone` to the Lock class

A PR with a similar idea was proposed (https://github.com/symfony/symfony/issues/24430) some time ago. This proposal in my opinion is different since the intended use of `isAquiredBySomeone` is as a query method, to read the current state of the lock.

**Example**  
Imagine this scenario:
- there's a web page used to launch a cli script as separate process
- there's supposed to be only one instance of the cli script running at a given time
 - the user wants to check, through the web page, if the script is running

One approach to implement the previous scenario could be:
- the cli script creates and acquires a lock, to be sure there's only one instance running
- the web page checks if the lock is acquired, without acquiring, and display this information to the user

the code in the cli script: 
```php
// create lock in the cli script
$lock = $factory->createLock('pdf-invoice-generation');
$lock->acquire()
```

the code in the web page: 
```php
// check if the lock is acquired
$lock = $factory->createLock('pdf-invoice-generation');
$lock = $lock->isAquiredBySomeone();
```

Does it makes sense? I'm willing to work on a PR is there's interest in adding this feature

**Comment by lyrixx** [comment]
Hello. Thanks for this RFC

IHMO the initial design is wrong. FPM (or mod_php) should not run long process.
You have no control nor feedback on what is going on.

Since Symfony Messenger is mainstream now, you can (should) publish a Message to a bus.
Then with a worker, you will be able to consumer this message. You will have the  guaranty that only one PDF is rendered at a time. You don't need a real broker such as RabbitMQ: your current database will be very good for small traffic, and you will get a nice error reporting, retry, dead queue, etc.

More over, I did not see a lib (golang, rust, etc) where this method exist.

That's why I'm :-1: on this new method

**Comment by micheleorselli** [comment]
Hi @lyrixx,
thank you for taking the time to respond, it's really appreciated!

> Hello. Thanks for this RFC
> 
> IHMO the initial design is wrong. FPM (or mod_php) should not run long process.
> You have no control nor feedback on what is going on.
> 
> Since Symfony Messenger is mainstream now, you can (should) publish a Message to a bus.
> Then with a worker, you will be able to consumer this message. You will have the guaranty that only one PDF is rendered at a time. You don't need a real broker such as RabbitMQ: your current database will be very good for small traffic, and you will get a nice error reporting, retry, dead queue, etc.
> 

The scenario I described early is for sure a really naive way to offload work out of a web request and I'm aware there are a lot of solid battle tested solutions: Messenger, Gearman, ..., you name it, but for that specific project they were not a viable solution. 

Still, using the Lock component felt a bit strange to me, maybe because even if the lock is a shared resource, `isAcquired` is instance based and this is a bit counterintuitive to me. That's why I came up with a new method. 

For the use case mentioned above, I ended up implementing something on my own without the lock component, but I though I could try to formulate a proposal.

> More over, I did not see a lib (golang, rust, etc) where this method exist.

I managed to found [some](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock) [examples](https://docs.python.org/2/library/threading.html#lock-objects) in Python where, if I got it right, there is a method that does what I mean, though it's called `locked`

> That's why I'm 👎 on this new method

Feel free to close this issue if you don't think it makes sense to discuss about it anymore :-)

**Comment by jderusse** [comment]
I'm not sure this is something that should be part of the component:

because this can be achieves easily at userland by acquiring and releasing the lock. 
```php
public function function isAcquiredBySomeone($lock) {
  if (!$this->lock->acquire(false)) {
    return true;
  }
  $lock->release();
  return false;
}
```

But I fear people will missuses such function with:
```php
if ($lock->isAquiredBySomeone()) {
  return;
}
$lock->acquire();
```
which would be BAD!

**Comment by lyrixx** [comment]
I totally agree with @jderusse :+1:

**Comment by jderusse** [comment]
closing for above reason
