### ISSUE TITLE
[Form] Allow to customize individual collection items in form themes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#36039]
**Description**  
For some app I need to customize each item inside a CollectionType form field. We have `{% block collection_row %}`, `{% block collection_widget %}`, etc. But we don't have a `{% block collection_entry %}` and `{% block collection_entry_row %}`, `{% block collection_entry_widget %}`, etc.

At the end I needed to do this. It works, but it looks fragile:

```twig
{% block form_row %}
    {# ... #}

    {% set is_collection_item = block_prefixes|last ends with '_entry' %}

    {% if is_collection_item %}
        <div class="property-collection-item">
            {{ form_widget(form) }}
        </div>
    {% else %}
        {{ form_widget(form) }}
    {% endif %}
{% endblock %}
```

So, should we add support for these `collection_entry_*` blocks?

Thanks!

**Comment by yceruto** [comment]
:+1: to add this block prefix by default for collection entries.

As workaround, you could also create a type extension that adds this new block prefix to all collection entries by using the `block_prefix` form option or doing this directly:
```php
->add('items', CollectionType::class, [
    'entry_options' => [
        'block_prefix' => 'collection_entry',
    ],
])
```
later use `collection_entry_*` blocks for theme customization:
```twig
{% block collection_entry_row %}
        <div class="property-collection-item">
            {{ form_widget(form) }}
        </div>
{% endblock %}
```

**Comment by HeahDude** [comment]
See #36088.
