### ISSUE TITLE
[FORM][PROPERTY/ACCESS][PHP 7.4] access to an uninitialized property

### ISSUE THREAD

**Issue by abdel-geniusespro** [symfony/symfony#36051]
**Symfony version(s) affected**: 5.0.*

**Description**  
Error when handling request using symfony/form : Typed property Car::$brandName must not be accessed before initialization.

**How to reproduce**  
1 - create a class with typed property : 
```
Class Car 
{
    /**
    * @var string
    */
    private string $brandName;

   public function getBrandName(): string
    {
        return $this->brandName;
    }

    public function setBrandName(string $brandName): self
    {
        $this->brandName = $brandName;

        return $this;
    }
}
```
2 - Create a form type for your class.
```
Class CarType extends AbstractType 
{
    /**
     * {@inheritDoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('brandName')
        ;
    }

    /**
     * {@inheritDoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}
```
3 - Handle your request
```
Class CarController extends AbstractController
{
    public function postCar(Request $request, FormFactoryInterface $formFactory): Response
    {
        $form = $formFactory->create(CarType::class);
        $form->handleRequest($request); // this will throw the error
    }
}
```
**Possible Solution**  
Check if the property is initialized before accessing.

**Additional context**  
After consulting trace, the error origin is here : https://github.com/symfony/property-access/blob/18617a8c26b97a262f816c78765eb3cd91630e19/PropertyAccessor.php#L382

**Comment by HeahDude** [comment]
Hello, @abdel-geniusespro. Indeed, the same applies for a public property:
```php
class Car
{
    public string $brandName;
}
```
But I'd argue that the above code is incorrect, since it is error prone independently of any Symfony component. Instead it should be written as:
```php
class Car
{
    public string $brandName = '';
}
```
or
```php
class Car
{
    public string $brandName;

    public function __construct(string $brandName)
    {
        $this->$brandName = $brandName;
    }
}
```
or accept nullable `?string`.

So I'm not sure we should consider this a bug and fix it in core. IMHO we should not encourage writing such fragile code in the first place.

**Comment by xabbuh** [comment]
This is not a bug to me. It's inherent of an object that serves as the source for a form to be in invalid states and being accessed by the form in this invalid state. Your code needs to account for that or add custom means to improve the error handling (see also #36022).

I am going to close here as explained in https://github.com/symfony/symfony/issues/36022#issuecomment-597531498.
