### ISSUE TITLE
PreAuthenticatedAuthenticationProvider calls loadUserByUsername with a user object rather than a string

### ISSUE THREAD

**Issue by nescim** [symfony/symfony#36054]
**Symfony version(s) affected**: 4.4.5 (likely others as well)

**Description**  
I have a custom User provider, based on the one provided in `symfony/ldap`. I encountered an exception due to the fact that the provider's `loadUserByUsername` method was passed a user object rather than a string.

Reading the stack trace, I found this snippet in `PreAuthenticatedAuthenticationProvider`:
```php
# in vendor\symfony\security-core\Authentication\Provider\PreAuthenticatedAuthenticationProvider.php (line 57)

        if (!$user = $token->getUser()) {
            throw new BadCredentialsException('No pre-authenticated principal found in request.');
        }
        $user = $this->userProvider->loadUserByUsername($user);
```
If this behavior is expected then the documentation, the PHPDoc block in `UserProviderInterface` and the stub class generated by the Maker bundle all need to be revised, since they are quite clear that that method is going to receive a string.

**How to reproduce**  
This is a rare case of a problem that is evident by mere static code analysis.

The bug was triggered by an `authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')` call made by `stof/doctrine-extensions-bundle` on a page with no anonymous access (even if there is a third party bundle involved, I highly doubt that a call to `isGranted` could be done wrong). My custom user provider is close enough to the one in `symfony/ldap` that it should also throw an exception.

**Workaround**
Two workarounds are working for me so far:

- implementing `__toString` in my user class
- checking for the type of the `$username` parameter in my user provider and invoking `getUsername` in there.

**Possible Solution**  
If the behaviour is expected, amend the documentation and PHPDoc blocks accordingly. 

If this is indeed a bug, a naive one-line patch could be to introduce a call to `getUsername` in `PreAuthenticatedAuthenticationProvider` but more likely the right fix will have to do with the logic that class is using. Maybe it should call `refreshUser` instead?

**Comment by chalasr** [comment]
Thanks for the report!
See #36134
