### ISSUE TITLE
BC Break: Length of password field / new hashing algorithm

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#36050]
Sorry, I'm not sure which exact version this refers to :-(

**Description**  
Previously, the recommended length for the `password` field of the User entity was 64 - see
https://symfony.com/doc/4.0/doctrine/registration_form.html

Now, when creating a User entity with `bin/console make:user` it creates a password field with no length given (which probably translates to 255).

Where's the problem?:
If you still have your (not so) "old" entity in place, then update Symfony (`composer update`), you now end up with this in your `prod.log` 

> Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO ... :  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(64)" at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0)

This just happend to me in production :-(

The reason seems to be that Symfony changed the password hashing algorithm.

**Comment by xabbuh** [comment]
So you use `auto` as the value for the password hashing algorithm in your security config?

**Comment by ThomasLandauer** [comment]
No, I'm using `bcrypt`, as recommended at https://symfony.com/doc/4.0/doctrine/registration_form.html#handling-the-form-submission

And that's probably the *real* problem we're talking about: The (failing) value I saw yesterday was `$argon2i$v=19$m=65536,t=4,p=1$ejJ6Q3R3...`, so it looks like Symfony silently switched from bcrypt to argon, which causes the hashed passwords to be too long. Right?

There should have been a deprecation notice about this in advance.

**Comment by nicolas-grekas** [comment]
That shouldn't happen: configuring for `bcrypt` has no reasons to lead to argon.
Can yo inspect how this happened?

**Comment by ThomasLandauer** [comment]
Inspect what exactly?

It's a registration form. I ran `composer update` yesterday, but didn't change anything security-related. And since yesterday, all passwords in the database are starting with `$argon2i$v=19` and are longer, while before yesterday all are starting with `$2y$13...` and are shorter.
Now it's Symfony 4.4.5, and it was 4.4.x before (don't know the exact version). I didn't save the output of `composer update` (BTW: I probably should have done - what's the best practice to do this?)

**Comment by stof** [comment]
@ThomasLandauer if your composer.lock file is versioned (that's the best practice), changes performed by a composer update are already saved, as that's what changes in the lock file are (and https://github.com/davidrjonas/composer-lock-diff can give you a human-readable summary of the update).

**Comment by ThomasLandauer** [comment]
Thanks, but this didn't give any information - see https://github.com/davidrjonas/composer-lock-diff/issues/25 - probably I'm not in the right git status.

Anyway, should I post my previous `composer.lock`s?

**Comment by xabbuh** [comment]
Alternatively you can also reset to the working commit hash and see what update (downgrade) operations `composer install` performs.

Do you also see the change in behaviour when starting a new application with the same configuration that you currently have?

**Comment by ThomasLandauer** [comment]
Sorry, I cannot reproduce this :-( Not on dev machine, not on staging server. But what's really weird: Even running `bin/console security:encode-password` on prod on CLI gives me `$2y$13...`, while at the same time the real user passwords in the database are starting with `$argon2i$v=19...`

So I'm closing this. If somebody else observes the same behavior, they will hopefully stumble over this issue... 

> Alternatively you can also reset to the working commit hash and see what update (downgrade) operations composer install performs.

There you go - just for reference:
```
Package operations: 0 installs, 65 updates, 0 removals
  - Updating hirak/prestissimo (0.3.10 => 0.3.9): Loading from cache
  - Updating dompdf/dompdf (v0.8.5 => v0.8.4): Loading from cache
  - Updating symfony/polyfill-php72 (v1.14.0 => v1.13.1): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.14.0 => v1.13.1): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.14.0 => v1.13.1): Loading from cache
  - Updating egulias/email-validator (2.1.17 => 2.1.15): Loading from cache
  - Updating stripe/stripe-php (v7.27.1 => v7.23.0): Loading from cache
  - Updating symfony/asset (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/doctrine-bridge (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/var-dumper (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/debug (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/error-handler (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/var-exporter (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/cache (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/expression-language (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/inflector (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/property-access (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/options-resolver (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/intl (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/polyfill-intl-icu (v1.14.0 => v1.13.1): Loading from cache
  - Updating symfony/event-dispatcher (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/form (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/polyfill-php73 (v1.14.0 => v1.13.1): Loading from cache
  - Updating symfony/mime (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/http-foundation (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/http-kernel (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/routing (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/finder (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/filesystem (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/dependency-injection (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/config (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/framework-bundle (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/console (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/maker-bundle (v1.14.6 => v1.14.3): Loading from cache
  - Updating symfony/monolog-bridge (v4.4.5 => v4.4.4): Loading from cache
  - Updating doctrine/orm (v2.7.1 => v2.7.0): Loading from cache
  - Updating symfony/stopwatch (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/orm-pack (v1.0.8 => v1.0.7): Loading from cache
  - Updating symfony/process (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/security-core (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/security-http (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/security-guard (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/security-csrf (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/security-bundle (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/templating (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/translation (v4.4.5 => v4.4.4): Loading from cache
  - Updating twig/twig (v2.12.5 => v2.12.3): Loading from cache
  - Updating symfony/twig-bridge (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/validator (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/yaml (v4.4.5 => v4.4.4): Loading from cache
  - Updating behat/gherkin (v4.6.1 => v4.6.0): Loading from cache
  - Updating webmozart/assert (1.7.0 => 1.6.0): Loading from cache
  - Updating phpdocumentor/type-resolver (1.1.0 => 1.0.1): Loading from cache
  - Updating phpdocumentor/reflection-docblock (5.1.0 => 5.0.0): Loading from cache
  - Updating phpspec/prophecy (v1.10.3 => v1.10.2): Loading from cache
  - Updating codeception/lib-asserts (1.11.0 => 1.10.1): Loading from cache
  - Updating symfony/dom-crawler (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/browser-kit (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/css-selector (v4.4.5 => v4.4.4): Loading from cache
  - Updating codeception/codeception (4.1.1 => 4.1.0): Loading from cache
  - Updating codeception/lib-innerbrowser (1.3.1 => 1.3.0): Loading from cache
  - Updating phpstan/phpstan (0.12.14 => 0.12.9): Loading from cache
  - Updating symfony/dotenv (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/twig-bundle (v4.4.5 => v4.4.4): Loading from cache
  - Updating symfony/web-profiler-bundle (v4.4.5 => v4.4.4): Loading from cache
```
