### ISSUE TITLE
File::guessExtension() returns .mpga over .mp3

### ISSUE THREAD

**Issue by dwolfhub** [symfony/symfony#36068]
To me, if someone uploads an `audio/mpeg` mime type, it's more likely to be an .mp3 than a .mpga

There is an old ticket #8678 that talks about how 
"it is the first associated extension in the list maintained by Apache". 

In my opinion, just because it is first in the list doesn't mean we should make it the default on our end. Should we consider changing the order of the list? 

Happy to provide PR. Thanks

**Comment by fabpot** [comment]
A PR would be appreciated indeed.
