### ISSUE TITLE
[Secrets] How to configure secrets location on console runs?

### ISSUE THREAD

**Issue by danoc93** [symfony/symfony#36061]
I have started a symfony server which builds a /config/secrets/local folder; unfortunately, after moving to a dockerized environment, the console command needs the secret dir to be created and it fails because the default folder is not writable (this is by design). Is it possible for this folder to be configured somewhere? I am unable to find this in the documentation.

**Comment by nicolas-grekas** [comment]
Would this help?

https://speakerdeck.com/nicolasgrekas/configuring-symfony-from-localhost-to-high-availability?slide=48

![image](https://user-images.githubusercontent.com/243674/76638100-2e7bb300-654c-11ea-923b-2fa93a700a28.png)
