### ISSUE TITLE
[PHPUnitBridge] Non WebTestCase starting a session fails

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#36065]
**Description**
Running a `TestCase` which is not a `WebTestCase` and starting a session causes a failures due to output already having been sent.

[Here is a minimal reproduction.](https://github.com/alex-dev/symfony-phpunit-bridge-bug/tree/master/tests) To trigger the bug, make sure to output to `--stderr`.

**Cause**
`Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait::startTestSuite()` output `"Testing $suiteName\n"` to stdout.

**Comment by alex-dev** [comment]
`session_start` is mandatory here. Functionnal test consumes legacy code.

**Comment by alex-dev** [comment]
Ideally, tests session storage would override `session_*` stuff. I'm pretty sure it's impossible without monkey patching.

`Symfony\Bridge\PhpUnit\ClassExistsMock` is a decent approach but it relies on two assumptions:
- The tested code must be in a namespace;
- The code must not use `\session_start`;

When building integration tests around legacy code either of these can be wrong.

**Comment by chalasr** [comment]
I'm going to close this issue because it has been open for a long time but it didn't receive any feedback from the community nor the core team, which probably means the use case is not common enough.
Thanks for your understanding.
