### ISSUE TITLE
profiler only shows Request / Response page

### ISSUE THREAD

**Issue by fun2life** [symfony/symfony#36071]
**Symfony version(s) affected**: at least since Symfony 5.0.4 and still in 5.0.5

**Description**  
When opening the Profiler, it is not possible to view for example the Translation, the Doctrine or any page other than the "Request / Response" page. Even though the active URL is "_profiler/3c4028?panel=translation" or "_profiler/3c4028?panel=db", for example, the "Request / Response" page is being displayed.

I'm on a xampp/Apache system and the problem can be reproduced when either using subdirectories or not.

**edit**
Upon further exploring I noticed that if you have an exception in a AJAX request and click on the request in the Toolbar, the Exception page opens and you're not able to open any other page, also not the "Request / Response" page.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce this issue?

**Comment by fun2life** [comment]
Sample application ist here:
https://test.pilatusmail.ch/

There is the home site and then there is "Page 2", that throws an exception due to an undefined Twig variable. Both pages allo acces to the profiler via the Symfony bar and in both examples, navigating within the profiler is not possible.

and sourcecode can be found here:
https://test.pilatusmail.ch/downloads/demoapplication.zip

**Comment by xabbuh** [comment]
Thank you very much for creating this example application. However I am sorry but I couldn't reproduce the behaviour you observed when checking out the application locally.

**Comment by xabbuh** [comment]
Oh, and please note that I can also navigate the profiler on the application that you linked without any issue.

**Comment by fun2life** [comment]
Sorry, but I have now tested it on Windows 7 and Windows 10, both using Firefox, Chrome and Internet Explorer, as well as on an iPad and iPhone using Safari and it does not work for me. Browser cache was empty.

http://test.pilatusmail.ch/_profiler/________?panel=request
http://test.pilatusmail.ch/_profiler/________?panel=logger
http://test.pilatusmail.ch/_profiler/________?panel=translation
(replace ________ with your token number)
all show the exact same page. Anyway, since the server should deliver different pages, it can't be a Browser problem.

What does work for me are the buttons Request, Response, Session and Server Paramters under "MainController :: home".


I have now added the line {% trans %}mymessage{% endtrans %} to the first page. Can you really click on the translation button in the Profiler bar and not land on "MainController :: home", but the translation page? Or open the profiler, click on Translation in the left menu bar and see the correct content?

**Comment by xabbuh** [comment]
You are right. I can see the behaviour you described on your hosted application. However, locally this still looks good:

<img width="956" alt="Bildschirmfoto 2020-03-27 um 20 32 03" src="https://user-images.githubusercontent.com/1957048/77793317-23f00c00-706a-11ea-94e6-a2aa7cb6cc4c.png">

<img width="968" alt="Bildschirmfoto 2020-03-27 um 20 32 10" src="https://user-images.githubusercontent.com/1957048/77793339-281c2980-706a-11ea-8f55-0fcc59a91854.png">

<img width="956" alt="Bildschirmfoto 2020-03-27 um 20 32 23" src="https://user-images.githubusercontent.com/1957048/77793351-2e120a80-706a-11ea-811c-9b0313d5b5e2.png">

**Comment by fun2life** [comment]
The hosted server is Apache 2 on Linux, my local environment is the newest Version of XAMPP (Apache) on Windows.

Looks like an issue with how Apache handles Get variables. Is the profiler supposed to only work with the built-in webserver? When I started with Symfony 5.0.0 it all worked fine on XAMPP.

**Comment by xabbuh** [comment]
No, it should also work with Apache. I am afraid you will need to debug a bit yourself what is going on.

**Comment by fun2life** [comment]
I will and post my findings here

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
