### ISSUE TITLE
[phpunit] sh: composer: command not found

### ISSUE THREAD

**Issue by devcut** [symfony/symfony#36084]
Hello,

I try to execute phpunit with `./bin/phpunit` but i have this error :

```
#!/usr/bin/env php
sh: composer: command not found
```
 
Composer is installed globally and works but not for this command.
` "symfony/phpunit-bridge": "^5.0",`

Any ideas ?

**Comment by xabbuh** [comment]
What is the output of `which composer`?

**Comment by devcut** [comment]
I have not output with `which composer`

**Comment by xabbuh** [comment]
This does not answer my question.

**Comment by devcut** [comment]
No output when i make `which composer`

**Comment by xabbuh** [comment]
You need to make sure that `composer` is part of your `$PATH`.

**Comment by devcut** [comment]
I have already `PATH` in my `bash_profile`.

I move `composer.phar` in `usr/local/bin/composer/composer.phar` in `usr/local/bin/composer.phar` and in my bash profile i write `alias composer='php /usr/local/bin/composer.phar'`

It's working now, thanks @xabbuh

**Comment by xabbuh** [comment]
Let's close then.
