### ISSUE TITLE
[Uid] integration with the other components

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#36102]
Now that the component is mostly ready, let's start integrating it with the rest of the stack.

Help wanted for finding where we want to have such integration.

What I spotted so far:
- [x] a normalizer/denormalizer for `Serializer` #36406
- ~a command line to generate new UIDs?~
- an argument value resolver for controllers?
- a form type?
- a twig extension? (not sure about this one)
- a `UuidValidator`
- [x] Doctrine type ##37678
- [x] a UID factory #36097

We could have a look at https://github.com/mcfedr/uuid-extra-bundle and https://github.com/ramsey/uuid-doctrine

Help wanted for the implementations!

**Comment by lyrixx** [comment]
I agree with everything except:

> a command line to generate new UIDs?

Useless IMHO. More over, it's juste a matter of `php -r 'echo uuid_create();'`. Or use any generator online

>an argument value resolver for controllers?
 Useless too imho. You usually want to get your entity, not the Id of the entity

> a form type?

I don't understand what this will be

**Comment by ro0NL** [comment]
Dont forget about UuidValidator :) perhaps we can support ramsey/sf/pecl transparently here ... thus keep this one in the Validator component. Then we can clean up its own UUID logic in favor of external infra, much like EmailValidator.

additionally, UlidValidator & co. for the Uid component.

**Comment by Nek-** [comment]
> > a command line to generate new UIDs?
>
> Useless IMHO. More over, it's juste a matter of php -r 'echo uuid_create();'. Or use any generator online

1. `php -r 'echo uuid_create();'` is a pain, and is not working without the uuid ext (+ this component/polyfill is kind of useless if you consider only this)
2. The command `uuidgen` does a super-great-job. 
3. But still, not many people know this command... and it does not work on windows, on mac it generate UUIDs with caps... So I don't know, it may be a good thing.

**Comment by gmponos** [comment]
Also a Uuid processor for monolog would be a nice idea... I can take on that.. it's simple.. but I guess this fits to the monolog-bundle? right?

**Comment by xabbuh** [comment]
@gmponos The processor is probably best places in the Monolog bridge while its wiring would happen in the bundle.

**Comment by vudaltsov** [comment]
I agree that a console command does not seem to be useful. Most devs use plugins in their editors like https://plugins.jetbrains.com/plugin/8320-uuid-generator or https://plugins.jetbrains.com/plugin/9836-randomness with multicursor support and etc.

**Comment by guillbdx** [comment]
I'm working on a PR for the normalizer, the form type, controller argument resolver and validator.

**Comment by Gemorroj** [comment]
@nicolas-grekas need add form type at least. At this time we can't use the default TextType for Uuid. Need make setter or tranformer to use Uuid with Symfony froms.

**Comment by nicolas-grekas** [comment]
@Gemorroj would you be up to work on this?

**Comment by Gemorroj** [comment]
@nicolas-grekas I'll try it #39863
