### ISSUE TITLE
can't delete cookie with clearCookie: should add SameSite param

### ISSUE THREAD

**Issue by pravdinalex** [symfony/symfony#36107]
**Symfony version(s) affected**: 4.4.5

**Description**  
Seems, should add SameSite param to clearCookie method at HttpFoundation, because in some situations, can't clear cookie. 

**How to reproduce**  

There is a SPA at, say, http://localhost:8080 and API for it at, say, https://api 

At API, I set cookie at controller:

```
        $response->headers->setCookie(
            new Cookie(
                'my-cookie-name',
                $myCookieContent,
                time() + 3600 * 24 * 7,
                '/',
                null,
                true, // https
                true, // http only
                false,
                'None' // same site
            )
        );
```

Deleting cookie with this code doesn't work:
```
        $response->headers->clearCookie(
            'my-cookie-name',
            '/',
            null,
            true, // https
            true  // http only
        );
```

But deleting cookie with that code does (code from clearCookie, but with sameSite = 'None'):
```
        $response->headers->setCookie(
            new Cookie(
                'my-cookie-name',
                null,
                1,
                '/',
                null,
                true, // https
                true, // http only
                false,
                'None'
            )
        );
```

**Possible Solution**  
Add $sameSite param to clearCookie method.

**Comment by guillbdx** [comment]
Hi @pravdinalex Please, can you give more informations about the context:

- What browser do you use? Which version?
- Can you provide the javascript code that performs the request?

It looks like it could be relative to Chrome update 80: https://www.thinktecture.com/en/identity/samesite/how-to-delete-samesite-cookies/

By the way, your client uses http while your api uses https, which can be a source of problems as well.

Thank you!

**Comment by pravdinalex** [comment]
> What browser do you use? Which version?

Yes, I found it when new Chrome 80 arrived (and broke my auth). (Chrome 80.0.3987.149, Wnidows 8.1 64bit)

> Can you provide the javascript code that performs the request?

There's no js code: cookie is http only.

> By the way, your client uses http while your api uses https, which can be a source of problems as well.

Yes, I know: it's my developement env. But as I said it works with SameSite=None explitly set... 

In Chrome dev tools: deleting cookie with setCookie

![image](https://user-images.githubusercontent.com/2210640/77260599-174e6b00-6c9a-11ea-9461-00d71972dab8.png)

... and deleting cookie with clearCookie: sameSite = lax by default, Chrome shows warning:

![image](https://user-images.githubusercontent.com/2210640/77260559-d6eeed00-6c99-11ea-8a6c-2d860c750b25.png)
