### ISSUE TITLE
Expanded ChoiceType field data incorrect when submitted with !clearMissing

### ISSUE THREAD

**Issue by emarref** [symfony/symfony#36104]
**Symfony version(s) affected**: 4.4.4 and 4.4.5 (possibly others, but confirmed with these two)

**Description**  
When a form has a ChoiceType field that has the `expanded` option set `true`, a `$form->submit($data, false)` (i.e. not `handleRequest`, and with clearMissing set false) will cause the `$form->getData()` to be wrong.

**How to reproduce**  

1. A form
2. A child field of type ChoiceType, with `expanded` option set to true
3. Submit the form with `$form->submit($data, false);` (i.e. don't clear missing fields)
4. `$form->getData()` will return incorrect values

E.g.

```
        $data = ['field' => ['B']];

        $form = $this->createFormBuilder($data)
            ->add('field', ChoiceType::class, ['expanded' => true, 'multiple' => true, 'choices' => ['A' => 'A', 'B' => 'B', 'C' => 'C']])
            ->getForm();

        $form->submit(['field' => ['A', 'C']], false);

        $result = [
            'submitted' => $form->isSubmitted(),
            'valid'     => $form->isValid(),
            'formData'  => $form->getData(),
        ];
```

The result is:

```
Array
(
    [submitted] => 1
    [valid] => 1
    [formData] => Array
        (
            [field] => Array
                (
                    [0] => B
                    [1] => A
                    [2] => C
                )
        )
)
```

I would expect the result:

```
Array
(
    [submitted] => 1
    [valid] => 1
    [formData] => Array
        (
            [field] => Array
                (
                    [0] => A
                    [1] => C
                )
        )
)
```

When the choice field is configured with the `expanded` option set to false, the form works as expected. I.e. with checkboxes, the data is incorrect. With a multi-select the data is correct.

Code to explain and reproduce here: https://github.com/emarref/form-bug/

**Comment by xabbuh** [comment]
Thank you for reporting. However, I am closing here as we already have #16802 for this issue. Thank you for understanding.
