### ISSUE TITLE
dump() and dd() no display in command console  via ssh 

### ISSUE THREAD

**Issue by askuiop** [symfony/symfony#36106]
**Symfony version(s) affected**: 4.4.5

**Description**  
dump() and dd() not working in command and no display in command console  via SSH connection .
my OS: fedora  ssh on centos 

**How to reproduce**  
SSH on  a server with Terminal which symfony run on it, then run command with dump("anything"). 
It will display nothing.

**Comment by noniagriconomie** [comment]
in which env did you run the `bin/console` script?
if it is prod, the dump function is not for production, maybe prefer the console output feature or log instead

also you could use this https://symfony.com/blog/new-in-symfony-4-1-vardumper-server

also, maybe sharing some code can help :)

**Comment by askuiop** [comment]
of course, I run it in  dev env.

**Comment by jpjoao** [comment]
I can reproduce it. Seems to be related to configurations on the server, not related to Symfony.
What cross my mind is that the output has colours and may ssh configurations and servers end up not playing well with giving the impression that there was no output.

Here is what I've done trying to reproduce it.

I created a dummy command:
```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DummyCommand extends Command
{
    protected static $defaultName = 'my:dummy:command';

    protected function execute(InputInterface $input, OutputInterface $output): ?int
    {
        dump('anything');

        dd('anything2');
    }
}
```

Sent it to a server of mine (built a docker image and shipped it):
Server details:
```
/srv/app # bin/console about
 -------------------- --------------------------------- 
  Symfony                                               
 -------------------- --------------------------------- 
  Version              5.1.0-DEV                        
  Long-Term Support    No                               
  End of maintenance   01/2021                          
  End of life          01/2021                          
 -------------------- --------------------------------- 
  Kernel                                                
 -------------------- --------------------------------- 
  Type                 App\Kernel                       
  Environment          dev                              
  Debug                true                             
  Charset              UTF-8                            
  Cache directory      ./var/cache/dev (686 KiB)        
  Log directory        ./var/log (0 B)                  
 -------------------- --------------------------------- 
  PHP                                                   
 -------------------- --------------------------------- 
  Version              7.4.4                            
  Architecture         64 bits                          
  Intl locale          en_US_POSIX                      
  Timezone             UTC (2020-03-28T15:53:43+00:00)  
  OPcache              true                             
  APCu                 true                             
  Xdebug               false                            
 -------------------- --------------------------------- 
```
Command run:
```
/srv/app # bin/console my:dummy:command
^ "anything"
^ "anything2"
```

**Comment by askuiop** [comment]
No, it  related to Symfony.  This problem has been present since version 4.4, which was not present in previous versions.

**Comment by stof** [comment]
@askuiop then provide a full reproducer, because when @jpjoao tried it, they got an output. So something might be different either on your server or in your project.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by andyyj** [comment]
```<?php
return function() {
    dump("something");
    dd("anything");
};
```

terminal in phpstorm
![image](https://user-images.githubusercontent.com/48076884/172331452-dd293240-8c9b-4381-8d38-07816d835c46.png)

mac terminal
![image](https://user-images.githubusercontent.com/48076884/172331564-f962175b-1d5f-4358-9467-16aa2abeb05d.png)
