### ISSUE TITLE
Symfony Process not parsing commands properly when using array?

### ISSUE THREAD

**Issue by arthur798** [symfony/symfony#36114]
so I have a code like this

```
            $splitPdfcommand = ['/usr/bin/pdftk', $document, 'burst output', $directory, '/page%02d.pdf'];
            $splitPdf = new Process($splitPdfcommand);
            
            $this->info('Running Command');

            $splitPdf->run();
```

when I do `dd($splitPdf)`  I get 

"'/usr/bin/pdftk' '/var/www/html/storage/app/documents/T6Ahiyv0-1/inCase - All Features - MultiSign.pdf' 'burst output' '/var/www/html/storage/app/documents/T6Ahiyv0-1' '/page%02d.pdf'"

All those simple quotes around the command are causing the command to fail as if I do 
"/usr/bin/pdftk "/var/www/html/storage/app/documents/T6Ahiyv0-1/inCase - All Features - MultiSign.pdf" burst output /var/www/html/storage/app/documents/T6Ahiyv0-1/page%02d.pdf"

See the output below from first command which ran fine, and the other 2 which failed due to the '. Now when the Process was still in v4 it allowed strings and everything was fine but now syntax requires array which messed things up for me

```
root@cffc7825c275:/var/www/html# /usr/bin/pdftk "/var/www/html/storage/app/documents/T6Ahiyv0-1/inCase - All Features - MultiSign.pdf" burst output /var/www/html/storage/app/documents/T6Ahiyv0-1/page%02d.pdf
root@cffc7825c275:/var/www/html# /usr/bin/pdftk "/var/www/html/storage/app/documents/T6Ahiyv0-1/inCase - All Features - MultiSign.pdf" 'burst output /var/www/html/storage/app/documents/T6Ahiyv0-1/page%02d.pdf'
Error: Unable to find file.
Error: Failed to open PDF file:
   burst output /var/www/html/storage/app/documents/T6Ahiyv0-1/page%02d.pdf
Done.  Input errors, so no output created.
```

**Comment by nicolas-grekas** [comment]
if `burst` and `output` are two separate arguments, you must split them:
`['/usr/bin/pdftk', $document, 'burst', 'output', $directory, '/page%02d.pdf']`

**Comment by stof** [comment]
And if `$director` and `/page%02d.pdf` are meant to build a path passed as a single argument (as seems to be the case in your expectation), you will need to concatenate them to pass them as a single argument.

**Comment by arthur798** [comment]
@stof didn't release that would be the case, thanks
