### ISSUE TITLE
[Serializer] Misconfiguration when multiple serializers are defined

### ISSUE THREAD

**Issue by davidkmenta** [symfony/symfony#36113]
**Symfony version(s) affected**: 4.3.0

**Description**  
Normalizers and encoders implementing `\Symfony\Component\Serializer\SerializerAwareInterface` may become inconsistent when multiple serializers are defined.

**How to reproduce**  
1. Create custom definition of serializer service (autoconfigured, autowired).
2. Create custom defintion of `PropertyNormalizer` service (autoconfigured, autowired) and pass it to the serializer from step 1.
3. Create custom denormalizer and pass it to the custom serializer from step 1 (**DON'T autoconfigure or autowire it**).

Into the existing serializer service definition (`@serializer`) is the `PropertyNormalizer` service mentioned above automatically passed because it is autocofigured. A that's the problem (I guess) because the instance of `PropertyNormalizer` firstly receives through the `\Symfony\Component\Serializer\SerializerAwareTrait::setSerializer` new definition of serializer and when the generic `@serializer` is instatiated the custom serializer inside `PropertyNormalizer` is overwritten by it but without the custom NON-tagged denormalizer. And that's causing problems when (de)normalizing data...

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by alanpoulain** [comment]
Related information can also be found in the description of my PR: https://github.com/symfony/symfony/pull/35374.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
