### ISSUE TITLE
Externalise routes

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#36139]
It seems the native i18n routing (see [blog post](https://symfony.com/doc/current/routing.html#localized-routes-i18n)) does not support externalised translations. So it requires having all translated routes at the `@Route` annotation directly which is difficult for translators and site admins that are not developers.

This seems a blocker for replacing JMSi18nRoutingBundle by this native system.

**Comment by fancyweb** [comment]
Duplicate of https://github.com/symfony/symfony/issues/30098?

**Comment by Guite** [comment]
Indeed, thanks for the pointer. Closing as dup.
