### ISSUE TITLE
postUpdate is not called when changing related collection from non-empty to empty

### ISSUE THREAD

**Issue by sidPL** [symfony/symfony#36138]
**Symfony version(s) affected**: 5.0.5

**Description**  

I have User entity with ManyToMany UserRoles collection. Also have EventSubscriber class which has postUpdate event subscribed. Everything is working fine until change on User is removing all objects from collection `$user->userRoles` - `postUpdate()` is not called and collection's `getDeleteDiff()` is empty. 

**How to reproduce**  
```
class User {
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UserRole")
     */
    private $userRoles;
    (...other fields...)
}
```
- When changing non-relational fields - event is called. 
- When adding to `$user->userRoles` some roles - event is called (changes are visible using collection's `getInsertDiff()`)
- When removing from `$user->userRoles` - event is called (changes are visible using collection's `getDeleteDiff()`) but ONLY when after-update collection is not empty 
- When removing ALL roles from collection `$user->userRoles` - postUpdate event is NOT called
- When removing ALL roles from collection `$user->userRoles` AND changing some other field - event is called, changes of other field - visible, but there are no visible changes on `$user->userRoles` in `$user->userRoles->getDeleteDiff()`

**Comment by xabbuh** [comment]
The collection classes are not part of the Symfony code. Please report this over to the Doctrine project. Thank you for understanding.
