### ISSUE TITLE
Assert\Email with html5 and strict are both too lax

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#36142]
**Description**  
`email..email@yopmail.com` is not a valid email, but it pass the `Assert\Email(mode=html5)` validation. Later if you try to send an email with the `\Swift_Mailer`, you'll get an exception.

`email..email@yopmail.com` is catched by the `Assert\Email(mode=strict)` validation, but `email..email@yopmailcom` is not since there is no DNS check.

This means there is no actual constraint which is able to check for a totally valid email.

I would be better to
- either use the DNS validation from the `egulias/email-validator`. I know symfony removed the his own dns validation. But since `strict` mode means "Use external validation", and `egulias` provide a DNS validation, I think the `strict` should use all the validations provided by the library. If there are issues with the validaiton it will be `egulias` issues, not `symfony` issues.
- either improve the html5 validation to handle the `..` case (and maybe some others). Because the fact that a valid address can create a `\Swift_Mailer` exception is kinda sad.

**Comment by fabpot** [comment]
The email you mention is valid in Japan for instance (historical reason). In any case, we won't change the current status quo on this topic. We've debated it for years in many different issues.

**Comment by VincentLanglet** [comment]
@fabpot 
My issue is that `Assert\Email(mode=html5)` consider as valid the `email..email@yopmail.com` email but the `Swift_Mailer` return an exception.
![image](https://user-images.githubusercontent.com/9052536/78897711-e3818c80-7a72-11ea-931b-3947b82c0fc5.png)

Because the checks made by the `Swift_Mailer` is strict.
```
if (!$this->emailValidator->isValid($address, new RFCValidation())) {
```

I will create an issue to at least improve the `@throw` documentation in the `Swift_Mailer`.
