### ISSUE TITLE
Undefined index errorCount at LoggerDataCollector

### ISSUE THREAD

**Issue by dbalabka** [symfony/symfony#36159]
**Symfony version(s) affected**: >=3.4.37

**Description**  
The following error might appear which blocks Debug Toolbar to be loaded:
```
Uncaught PHP Exception ErrorException: "Notice: Undefined index: errorCount" at /Users/torinaki/www/htdocs/fithealthy2/vendor/symfony/http-kernel/DataCollector/LoggerDataCollector.php line 190
```

**How to reproduce**  
TBD
```
@trigger_error("1", E_USER_DEPRECATED)
```
Such a log message might be thrown by:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Config/Definition/ArrayNode.php#L238
in case if configuration child is deprecated and depreciation message for some reason is "1"

**Possible Solution**  
Fix logic of:
https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L168

1. There no guarantee that "errorCount" exists but it is not a root cause. 
https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L195
2. `$sanitizedLogs` contains numeric and assoc. keys. It should be avoided:
https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L175
https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L195

**Additional Context**
It happened because of incorrect passed deprecation message:
https://github.com/Sylius/SyliusMailerBundle/blob/1.4/src/Bundle/DependencyInjection/Configuration.php#L76
It was possible because of missing type hint:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Config/Definition/BaseNode.php#L170
which is fixed in 5.0 version of Symfony:
https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Config/Definition/BaseNode.php#L204

**Comment by fancyweb** [comment]
Status: reviewed

I'm looking at this issue. I think the easiest way to deal with this is simply to prepend a fixed string to the messages so numeric and message keys never collide.

**Comment by chancegarcia** [comment]
I ran into this issue when a Configuration TreeBuilder node used `setDeprecated(true)` instead of a string

**Comment by dbalabka** [comment]
@fancyweb thanks!
