### ISSUE TITLE
Check available parameters in `lint:container` command

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/symfony#36156]
Now `lint:container` command doesn't catch error when we get ParameterBag by autowire in some service and trying to get unknown parameter from it. Therefore, if we don't want to catch such errors in runtime and can't cover with tests all cases, we are forced to pass parameters explicitly into our services in arguments list and describe such services in services.yaml or add such parameters in _defaults.bind.

If `lint:container` will be able to parse `get` calls of ParameterBagInterface instances and check that required parameter is available (or not), it would be very usefull.

**Comment by xabbuh** [comment]
Implementing such a feature would mean to statically analyse all the classes that get a `ParameterBag` injected. IMO this is out of the scope of this command (and here we are even not talking about the fact that the value passed to `get()` may be dynamic).

**Comment by fabpot** [comment]
Let's close then.
