### ISSUE TITLE
[Config] ext-dom is missing in composer.json

### ISSUE THREAD

**Issue by dontub** [symfony/symfony#36150]
**Symfony version(s) affected**: >=3.4 (and previous)

**Description**  
The config component uses the PHP extension DOM in class `XmlUtils`, though `ext-dom` is missing in composer.json.

**Possible Solution**  
Add `ext-dom` as requirement or suggestion in composer.json.

**Comment by stof** [comment]
We currently don't have suggestions for `ext-*` packages in our packages.
