### ISSUE TITLE
Unable to find template "" (looked into: /home/ubuntu/.../app/Resources/views, /home/ubuntu/..../vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

### ISSUE THREAD

**Issue by aaronat1** [symfony/symfony#36163]
Hi, I have problem when deploy my project in AWS. My web application has an Export/Import functionality than has working fine in my local deployment, but In AWS when click in export button I am receiving this error: 

> Unable to find template "" (looked into: /home/ubuntu/.../app/Resources/views, /home/ubuntu/..../vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

Can somebody help me please? Regards

**Comment by wouterj** [comment]
Hi @aaronat1! GitHub is a place to discuss new features or report bugs, it is not a place to ask for community support. You can find both community and professional support on https://symfony.com/support (for instance, you can use StackOverflow or the Symfony Slack).
