### ISSUE TITLE
E-mail constraint should have a mode to enable both HTML5+strict validation

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#36179]
**Description**  
E-mail constraint [offers different modes](https://symfony.com/doc/current/reference/constraints/Email.html#mode) of validation, but sometimes it makes sense to use two of those modes. When using strict validation, there are some addresses considered valid, but they are then rejected by Sendgrid SMTP. When using HTML5 validation some addresses are allowed in form, but are rejected by Symfony Mail which uses strict validation.

The workaround is to add two validators:
```
     * @Assert\Email(mode=Email::VALIDATION_MODE_HTML5)
     * @Assert\Email(mode=Email::VALIDATION_MODE_STRICT)
```

But produces duplicated error when the entered address does not comply with neither of them.

It would be nice to have a `strictest` mode (not sure about the name) which would check that the e-mail address complies with both strict and HTML5 validations.

**Comment by dmaicher** [comment]
This might be solved by the upcoming `Sequentially` constraint in 5.1?

see https://symfony.com/blog/new-in-symfony-5-1-reusable-sets-of-constraints#validate-constraints-sequentially

**Comment by nicolas-grekas** [comment]
@mhujer do you agree? Let's close then?

**Comment by mhujer** [comment]
I thought it would be nice to have  `VALIDATION_MODE_STRICTEST` mode built-in, but if you don't think it should be included in core, feel free to close the issue. I'm fine with creating in my app (after upgrading to 5.1 😃 )

**Comment by fabpot** [comment]
I think that the new Sequentially constraint is "best". Let's close.
