### ISSUE TITLE
Bug in the identity impersonalization part of the security package

### ISSUE THREAD

**Issue by AllanFousse** [symfony/symfony#36174]
**Symfony version(s) affected**: 5.0.5

**Description**  

Impersonalisation not working if we use Uuid for username in Postgresql database

**How to reproduce**  

use uuid type instead string in postgresql database for username

**Possible Solution**  
generate à uuid string instead of pure random string line 152 of SwitchUserListener.php

**Additional context**  
the error is SQLSTATE[22P02]: Invalid text representation

**Comment by fancyweb** [comment]
Thanks for reporting @AllanFousse. What is the exact exception you get please?

**Comment by AllanFousse** [comment]
![Annotation 2020-03-26 184850](https://user-images.githubusercontent.com/11208885/77679172-7d850780-6f92-11ea-8055-e09c0ff66550.png)

**Comment by fancyweb** [comment]
Yes, thank you. Can you check https://github.com/symfony/symfony/pull/36223 please?

**Comment by AllanFousse** [comment]
I try the modification, and it's work fine for me
