### ISSUE TITLE
Yaml LintCommand misses invalid syntax

### ISSUE THREAD

**Issue by domculpa** [symfony/symfony#36188]
**Symfony version(s) affected**: 4.4.5

**Description**  
Invalid security.yml is not recognized by lint:yaml command. 

**How to reproduce**
Following security.yml example is considered valid by LintCommand (error is >'< after "roles"):

```
security:
    access_control:
        - { path: ^/api/some/path, roles': 'ROLE' }
```

results in:
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException : Unrecognized option "roles'" under "security.access_control.0". Did you mean "roles"?

**Additional context**  
Setting the >'< before "roles" results in syntax violation. Would be great if the linter could also look the other way! The bug was introduced through some nifty merge conflict and wasn't recognized by code quality pipeline and tests. Thanks for looking into it!

**Comment by stof** [comment]
The think is, this is not an invalid YAML. `roles'` is a valid key in YAML.

**Comment by stof** [comment]
here, you don't have an invalid YAML syntax. You have an invalid configuration (coming from a different component)
