### ISSUE TITLE
Remove composer install step from phpunit-bridge / also solves composer github rate limit issue in CI.

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#36198]
**Description**  
When using symfony/phpunit-bridge or symfony/test-pack, and the first time you use bin/phpunit, phpunit will be installed (through composer) according to the given phpunit version in your phpunit.xml. 

*TL;DR: Reduce global energy usage by removing this extra composer install.*

I have no idea why this was done, but there's a few things wrong with it:
* (most important) In modern CI we use dockerized builds to do our unit and/or functional tests. A good CI caches the image by default, but that is usually *before* phpunit is run. Then, when phpunit is run, it needs to download the phpunit package. In our CI this happends both for the unit and the functional tests (twice). Since yesterday github changed something and this became annoying because it starts hitting rate limits in CI. Aside from that it is also wasteful for our global energy, because cumatively this can cause millions to billions of downloads each day in CI systems that could have been avoided
* it's weird that the phpunit version is decided in the phpunit.xml and not in the composer file
* in PHPStorm you always need to do a manual step to point to the `bin/phpunit` (or even `bin/.phpunit/phpunit-8-5/phpunit` to avoid problems). If it was in composer, it could be auto-detected correctly.

**Possible solution**  
Why not put it in composer? If I overwrite bin/phpunit manually with the .phar from the phpunit website, everything works as expected, as long as I keep the same phpunit.xml (with the `Symfony\Bridge\PhpUnit\SymfonyTestsListener` listener)

**Real solution**
Note that I was in the SymfonyCon 2019 and know that there's the intention to work together with PHPUnit's Sebastien to remove the need for the symfoy/phpunit-bridge. In my eyes that would be the even better solution, but I haven't seen that effort yet. In any case, this ticket could be a bridge, as it should re-introduce phpunit as a composer dependency and therefore make it easier to deprecate itself (ex. phpunit could be part of symfony/test-pack and eventually phpunit-bridge can be removed from symfony/test-pack)

**Comment by Riches** [comment]
We are also seeing that GitHub has more strictly enforced a rate limit that is affecting our symfony/phpunit-bridge CI setup. Our setup closely mirrors the one described by @rbaarsma 

Passing a GitHub OAuth token to the installer may temporarily get around this issue, although I haven't found a way to achieve this. The bridge installer doesn't seem to read the token from ~/.composer/auth.json

For now we've had to take PHPUnit tests out of our pipelines, so any temporary workarounds would also be appreciated if anyone has any suggestions.

**Comment by wouterj** [comment]
> [The PHPunit Bridge] Provides a modified version of PHPUnit that allows 1. separating the dependencies of your app from those of phpunit to prevent any unwanted constraints to apply; 2. running tests in parallel when a test suite is split in several phpunit.xml files; 3. recording and replaying skipped tests;
> -- https://symfony.com/doc/current/components/phpunit_bridge

It cannot be dropped. PHPunit and Symfony share dependencies, meaning that if PHPunit is installed there might be other versions of your dependencies installed than in production (where PHPunit is not installed). This explains point (2) you're raising.

The bridge comes with an install option though: `bin/phpunit install`. Running this in the container build solves problem (1).

**Comment by pscheit-lillydoo** [comment]
@rbaarsma when you are installing your vendors in the build of your composer image. Just execute the phpunit-bridge once (simple-phpunit --version || true), so it installs the deps. So that you have the deps in the image as well.

**Comment by nicolas-grekas** [comment]
> The bridge comes with an install option though: bin/phpunit install. Running this in the container build solves problem (1).

Correct, that's the way. Having a token is also recommended.

I'm therefor closing, thanks for asking.
