### ISSUE TITLE
!tagged_iterator strange issues

### ISSUE THREAD

**Issue by niji-bcondaminet** [symfony/symfony#36190]
**Symfony version(s) affected**: symfony/dependency-injection v4.4.5

**Description**  
After updating symfony/dependency-injection to v4.4.5, the !tagged_iterator has strange issues when one of the tagued service is overiden with custom priority. I see that this version add some modification for multiple tags iterator.

**How to reproduce**  
Do the last part of the documentation (with the priority override) : https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services for me the overriden service appear twice in the !tagged_iterator service arg, and my second tagued service is missing.

**Possible Solution**  
Don't know sorry.

**Comment by stof** [comment]
Can you share a reproducing case ?

**Comment by niji-bcondaminet** [comment]
Sorry I just saw that it's the same issue than : #35916 
I Rolled back to v4.4.4 for now waiting the fix for the next release.

**Comment by nicolas-grekas** [comment]
Closing as duplicate then.
