### ISSUE TITLE
Class PHPUnit\Framework\TestCase not found and could not be autoloaded

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#36202]
**Symfony version(s) affected**: 4.4 / 5.0

**Description**  

I created a new project and added PHPStan to analyze my code. The thing is that now PHPStan is reporting an error `Class PHPUnit\Framework\TestCase not found and could not be autoloaded.` - which is technically correct because symfony didn't install phpunit into `vendor` but instead created a separate launcher `bin/phpunit` which installs PHPUnit when first used into `bin/.phpunit/phpunit-9-0/vendor`. So of course PHPStan can't find it.

Why is PHPUnit even installed in this weird way instead of having it in `require-dev` normally?
What are the benefits of installing it like this?
What is the recommended way of fixing this?

**How to reproduce**  

- Create new Symfony project using `symfony new --full`.
- Add a unit test.
- Install PHPStan and configure it to analyze both `src` and `tests` directories
- Run PHPStan

EDIT: Psalm is failing too because of the same problem.

**Comment by ondrejmirtes** [comment]
Check this out: https://github.com/phpstan/phpstan/issues/694#issuecomment-350724288

But of course it'd be nice if Symfony didn't have this problem out of the box.

**Comment by enumag** [comment]
Yeah, figured as much. I guess there should be some similar option for psalm too somewhere... Plus I need to use some harmless phpunit command in CI in order to install it but not run the tests in my phpstan job. Overall it seems like a rather ugly workaround.

**Comment by enumag** [comment]
Bump. By the way since `symfony/phpunit-bridge` doesn't have `provides phpunit/phpunit`, further problems can occur if regular phpunit gets installed anyway as a composer dependency of some other package (such as https://github.com/phpstan/phpstan-phpunit or https://github.com/psalm/psalm-plugin-phpunit) - especially if the phpunit version installed this way is different from the version installed by symfony.

Please give me some answers on this.

**Comment by pmishev** [comment]
I'm very interested in a solution for this problem too.
At the moment my workaround is putting a line like:
`<server name="SYMFONY_PHPUNIT_VERSION" value="8.5.4" />`
in phpunit.xml.dist, to make sure the phpunit-bridge installs the same version as the phpunit I have in the `vendor` dir (installed by `dms/phpunit-arraysubset-asserts` in my case).

But this is not maintainable:
1. having to remember to do this every time after phpunit in vendor is upgraded
2. a CI environment (jenkins) having an overriding phpunit.xml that needs to be updated as well manually

**Comment by enumag** [comment]
bump

**Comment by nicolas-grekas** [comment]
Adding phpunit in a composer.json file is not recommended. I know many do this because it is convenient to manage the version of it, but this comes with the drawback of messing up with your real dependencies. phpunit is a tool. Yes, there are classes that your app needs. Using phpunit as a `phar` is another valid option.

Then, for phpstan and similar tools, they need some configuration for sure.

I whish we could be able to build several vendor dirs, to manage "tools" using separate set of deps for them, while still using composer.json to commit their versions.

Note that phpstan is following exactly the same recommendation since it installs a phar when one requires phpstan/phpstan.

Maybe we could take inspiration for its approach.

**Comment by enumag** [comment]
Even if you avoid composer conflicts by separate vendor directory (which is possible by using multiple composer json files by the way) or a phar, you could easily run into issues when running the tool unless it's prefixed like PHPStan or Rector. I'm not quite sure if an integration plugin between two prefixed tool could work well though.

Anyway your reasons are not enough to justify the drawbacks of this approach in my opinions so I'll revert to standard phpunit usage in my projects.

**Comment by nicolas-grekas** [comment]
Closing as this has been sorted out.

**Comment by enumag** [comment]
@nicolas-grekas well the reasons have been answered but no recommended solution that symfony users can immediately use have been provided so I don't consider it resolved.

**Comment by nicolas-grekas** [comment]
Well, the solution is on the plugins, not here.

**Comment by bodik** [comment]
my 2 cents on this matter with help of symfony-devs #support is:

symfony 5.1
phpstan 0.12.28

```shell
composer require --dev phpstan/phpstan
vendor/bin/simple-phpunit install
cat >phpstan.neon.dist <<__EOF__
    bootstrapFiles:
       - vendor/bin/.phpunit/phpunit-7.5-0/vendor/autoload.php
__EOF__
```
I'm not really sure, but it should respect @nicolas-grekas recomendation (not adding phpunit/phpunit directly) and uses phpunit which comes with the symfony bridge.

**Comment by ondrejmirtes** [comment]
Yes, this is the recommended approach in PHPStan.

**Comment by mbrodala** [comment]
You can also use this since there is a generic symlink in place which points to the latest PHPUnit installation:

```yaml
parameters:
  bootstrapFiles:
    - bin/.phpunit/phpunit/vendor/autoload.php
```

This way you don't need to change this when updating PHPUnit.
