### ISSUE TITLE
[Router] Auto-redirect for trailing slashes fails to match when both routes exist

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#36203]
**Symfony version(s) affected**: 4.4.x, 5.*

**Description**  
Router auto-redirection for trailing slashes (https://symfony.com/doc/master/routing.html#redirecting-urls-with-trailing-slashes) fails to match the route correctly when both routes (with and without trailing slashes) are defined. In that case, whichever the first route is is matched, and the other redirects to it always.

**How to reproduce**  

Define two routes on a controller

```
     * @Route("/foo", name="foo", defaults={"_format"="json"}, methods={"GET"})
     * @Route("/foo/", name="foo_bc", defaults={"_format"="json"}, methods={"GET"})
```

Accessing /foo works, accessing /foo/ redirects to /foo, even though the exact match route exists. That sounds to me like a bug/overly greediness of the trailing slash redirecter.

Alternative solution or in addition to the bugfix, could be to offer an option for this behavior, which could be configured to either:
- redirect (current)
- allow /foo/ to match a /foo route silently, and /foo to match a /foo/ route also
- no magic, just strict match or 404

**Comment by fancyweb** [comment]
Status: reviewed

I was able to reproduce the problem. I'm looking for a fix.

**Comment by blowski** [comment]
Inspired by yesterday's online session, I'm happy to take this on if nobody else has started?

**Comment by nicolas-grekas** [comment]
To me there is no bug here, this is the behavior we've always had for routes with dynamic parameters, and we fixed static routes in 4.1.

**Comment by nicolas-grekas** [comment]
Check #33342 for a still open discussion on the topic, which contains a link to a way to reclaim back control of trailing slashes: https://github.com/symfony/symfony/pull/33362#issuecomment-526251779

**Comment by Seldaek** [comment]
Thanks for the issue links.. I read a lot there and I still disagree. I can see that for /Foo/{bar} where placeholder is optional then it gets complicated as it can conflict with a /Foo route, but imo if the exact route exists without optional placeholder and both trailing and no trailing slash then both should be routable.

Ironically.. this is possibly all my fault https://github.com/symfony/routing/commit/c39683b905f246a94babdf69c907e4cbe4cc5fe6

**Comment by Tobion** [comment]
See also https://github.com/symfony/symfony/issues/32996#issuecomment-525416971 ff.

**Comment by blowski** [comment]
What's the desired behaviour here? Is there a bug that needs fixing? I'm looking for something to do on Symfony core, so I'm happy to have a go at this, but don't really understand what needs doing.

**Comment by nicolas-grekas** [comment]
@blowski this won't be resolved soon, the current situation is well defined and consistent. There is no bug here - but there are objections to the current behavior, "that's all". Better look for something else if you want to contribute.

**Comment by blowski** [comment]
Ah ok, thanks for letting me know @nicolas-grekas .

**Comment by Seldaek** [comment]
Closing as it doesn't seem like this will go anywhere.
