### ISSUE TITLE
[Form] VO corresponding to simple string

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#36229]
**Symfony version(s) affected**: all

**Description**  
The form component supports values objects thanks to the DataMapper feature. But this feature is active only for [array or object data](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L373-L376).

_(and it's in the middle of the bug and the feature, because it's a special case that occurs often...)_

**How to reproduce**  

```php
// The VO
class ColorVo
{
    private $color;
    public function __construct(string $color)
    {
        $this->color = $color;
    }

    public function getHexaColor(): string
    {
        return $this->color;
    }
}

// The Form Type
class ColorType extends AbstractType implements DataMapperInterface
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setDataMapper($this);
    }

    public function mapDataToForms($viewData, iterable $forms)
    {
        // Will obviously not work but should
        $forms->setData($viewData->getHexaColor());
    }

    public function mapFormsToData(iterable $forms, &$viewData)
    {
        $viewData = new ColorVo($forms->getData());
    }
}

// inside a controller
$form = $formFactory->createNamedBuilder('')->add('color', ColorType::class)->getForm();
$form->submit(['color' => '#000000']);
```

**Comment by HeahDude** [comment]
Hello @Nek-, it seems to me that this expected, the mapper is for compound forms only, your case should be solved by using a data transformer instead.

**Comment by xabbuh** [comment]
I agree with @HeahDude. This behaviour is expected and there already is a solution for this problem. So I am going to close here. Thank you for understanding.
