### ISSUE TITLE
file_get_contents to localhost uses wrong port

### ISSUE THREAD

**Issue by abramsba** [symfony/symfony#36220]
**Symfony version(s) affected**: v4.13.3

**Description**  
I'm trying to convert HTML to DOCX. I use twig to render the template than phpdocx for the conversion. During the rendering of the template from the backend, not via a frontend, it fails to find images in the HTML file:

```
Mar 26 13:47:52 |INFO | SERVER GET  (200) /api/docx/test ip="127.0.0.1"
Mar 26 13:49:39 |INFO | PHP    Matched route "printDocx". path="/usr/local/Cellar/php/7.4.2/sbin/php-fpm" php="7.4.2"
Mar 26 13:49:39 |DEBUG| PHP    Warning: file_get_contents(http://localhost/images/logo.png): failed to open stream: Connection refused
```

I am running the application on port `8000` and it's trying to get to the files via port `80`. 

Using the correct port I can retreive the file as expected:

```
[~]$ curl localhost:8000/images/logo.png
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

```
Mar 26 14:04:46 |INFO | SERVER GET  (200) /images/logo.png
```

**How to reproduce**  
- Run server via `symfony serve`.
- Create a twig template with an <img> tag in it with href being `<img src="{ asset(images/test.png) }"/>`
- Render theme in Controller using `$this->get('twig')->render('template.twig.html`);`
- Error message in console

**Comment by xabbuh** [comment]
I don't see how this is related to Symfony. Can you explain where the `file_get_contents()` call should be issued?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
