### ISSUE TITLE
Refresh requirements for symfony/serializer-pack

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony#36228]
**Description**  
I've started a project yesterday and wanted to install `symfony/serializer-pack` today. As another package installed before required `phpdocumentor/reflection-docblock` in v5, the serializer could not be installed.

**Possible Solution**  
Update `symfony/serializer-pack` such that is compatible with `phpdocumentor/reflection-docblock` v5, or remove that dependency altogether (when installing `symfony/serializer` without that pack, that dependency isn't pulled in either)

**Comment by xabbuh** [comment]
see symfony/serializer-pack#2

**Comment by NicoHaase** [comment]
Thank you! I didn't know whether there are any more side effects - for example, why is that docblock package required after all?

**Comment by xabbuh** [comment]
IIRC this is used by the PropertyInfo component (which is also installed through the serializer pack) to extract information from the docblock.
