### ISSUE TITLE
[2.2] [Validator] Constraints\Valid does not respect "groups" option

### ISSUE THREAD

**Issue by ruimarinho** [symfony/symfony#3622]
I have an entity where I'm using the following validators:

``` php
/**
 * @Assert\Callback(methods={"isValid"}, groups={"group1", "group2"})
 */
class UserProduct
{
    /**
     * @var string $title
     * @Assert\NotBlank(message="title.blank", groups={"group1", "group2"});
     */
    private $title;

    /**
     * @var Project\AuthenticationBundle\Entity\User
     * @Assert\Valid(groups={"group2"});
     */
    private $user;
```

Calling `$this->get('validator')->validate($userProduct, array('group1'))` asserts the class constraint (`@Assert\Callback`) and the `$title` property but also the `$user` one too, even though it's not included in the validation group. The same happens if no groups are passed to the `Valid` constraint.

Removing the `@Assert\Valid()` constraint and running the same validation again for `group1` does not assert the `$user` property, as expected.

The `MemberMetadata` class appears to always force the cascading of the `Valid` constraint, although I'm unsure if this is exactly related to the issue I'm experiencing.

```
// Symfony\Component\Validator\Mapping\MemberMetadata.php
        if ($constraint instanceof Valid) {
            $this->cascaded = true;
            $this->collectionCascaded = $constraint->traverse;
        } else {
            parent::addConstraint($constraint);
        }
```

Running on Symfony2 master.

**Comment by webdevilopers** [comment]
:+1:

**Comment by TomasVotruba** [comment]
:-1:

**Comment by TomasVotruba** [comment]
:+1:

**Comment by ste93cry** [comment]
:+1: It's too easy for bundles to provide their own constraints in groups that have a name that user can't use anymore if he wants to override them.

**Comment by iBasit** [comment]
+1 is this resolved? I have similar issue http://stackoverflow.com/questions/33600454/assert-valid-on-entity-remove-the-validation-on-form

**Comment by backbone87** [comment]
Maybe something like https://gist.github.com/backbone87/4bd02388a0e96815c3a6 provides the desired behavior?
```
/**
 * @Validate({
 *   "local_group" = "foreign_group",
 *   "local_group2" = {"foreign_group", "foreign_group2"}
 * })
 */
private $foreignObject;
```

**Comment by aromer** [comment]
Is there any progress on this? Previously "cascade_validation" was a work around, but that's now been deprecated and removed in Symfony 3.0. Is there another solution or work around? I need to be able to conditionally require child forms based on choices in the parent form.

**Comment by iltar** [comment]
I ran into the same situation, a work around can be to assign the constraint via your form type. It seems like only via annotations it's not provided. If I add the constraint when adding the field to the builder, it works fine. 

Basically I have this:
```
CancelData
    - contract_cancel (ContractCancelData)
CancelType
    $builder->add('contract_cancel', ContractCancelType::class);

ContractCancelData
    - cancel_when
    - cancel_at @Assert\NotBlank(message="cancel.at.required", groups={"cancel-at-date"})

ContractCancelType
    $constraint = new AfterMonth();
    $constraint->groups = ['cancel-at-date'];

    $form->add('cancel_at', TextType::class, ['constraints' => [$constraint]]);
```

In this case when I set the validation groups to `['Default', 'cancel-at-date']`, the AfterMonth is validated but the NotBlank is not. When I had the notBlank on the type directly, it _is_ triggered. Note that this is added via the event: `form.post_set_data`.

/cc @webmozart any idea why those constraints are validated but not the annotations?

**Comment by kminh** [comment]
This issue makes me wonder whether deprecating `cascade_validation` in 2.7 is reasonable, since replacing `cascade_validation` with `Assert\Valid` (which is recommended) will break any embedded form that has `validation_groups` specifically set. `cascade_validation` should be deprecated only when `Assert\Valid` has support for the `groups` option IMO.

**Comment by trsteel88** [comment]
I agree with @kminh.

**Comment by MichaelMackus** [comment]
:+1:  and definitely agree with @kminh 

This is compounded by the issue(s) in #5953... makes overriding/modifying validation groups very annoying, especially with cascades. This means if I use a different validation group(s) for the parent, the children must have their own custom validation group(s) (without using cascade_validation of course, which unfortunately sounds like its deprecated as well...)

**Comment by ABM-Dan** [comment]
+1.

**Comment by webmozart** [comment]
@iltar can you provide a project that reproduces your problem?

**Comment by iltar** [comment]
@webmozart not as is, managed to get around the problem. It seems like the main issue is that I don't (did) know how to do it right. If I run into this again, I will provide a full example.

**Comment by jaikdean** [comment]
I have created a package with a `Validate` constraint which should allow the behaviour most of us here are after: https://github.com/fluoresceco/validate-embedded

It's likely far from perfect as I've only built it this afternoon to suit my own needs, so PRs and issues are welcomed.

**Comment by backbone87** [comment]
@jaikdean thats basically an implementation of https://github.com/symfony/symfony/issues/17622 ?

**Comment by jaikdean** [comment]
@backbone87 Correct, I knew I'd seen the idea somewhere 😊

**Comment by ABM-Dan** [comment]
@webmozart a simple example would be two different sibling forms that are bound to the same class through different attributes, like $mailingAddress and $billingAddress, Since they would both @Embed the Address model, they share the validations, but on the outside model class, they would have @Valid("BillingAddress") and @Valid("MailingAddress") so they can be validated or not validated individually.

**Comment by rvanlaak** [comment]
@ABM-Dan in addition I'd assume that `AddressType` should be usable outside of the scope of your situation too right? We have other pages that should be able to use the type. So ideally, we do not want to change the `validation_groups` on the entity or type for every scenario.

Next to that, we also want to validate them dynamically [using a closure as documented here](http://symfony.com/doc/current/form/data_based_validation.html).

**Comment by ABM-Dan** [comment]
@rvanlaak I'm not entirely sure what you mean by that. My example described a small and pretty common occurrence in which having validation groups for @Valid would be useful.

**Comment by rvanlaak** [comment]
Yes I agree to your scenario, what I meant to say is that we have an `Address` without specific validation groups that simply is used to add addresses. 

Next to that, we also have a page where we can apply multiple scenarios on that same `AddressType`, but we want to apply a `validation_group` to the `Address` there so it can be combined with other fields related to the scenarios.

**Comment by kgilden** [comment]
@webmozart I'm noticing similar behavior in v2.8.6 what @iltar is seeing. A constraint with a validation group added to a form field is applied, but the same constraint (same options) added via configuration does not trigger a validation error.

Sorry, can't provide a project right now, hopefully later.

**Comment by xabbuh** [comment]
I opened #21111 which is an attempt to add group support to the `Valid` constraint. I would be happy if you could try the patch with your applications and leave feedback in the PR comments.
