### ISSUE TITLE
[Expression] Allow constants in hash

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#36225]
I'm trying to define  cURL key-value options in a container as:

```xml
<argument key="$options" type="expression">{constant("CURLOPT_TIMEOUT"): 60}</argument>
```

However, I'm unable to use `constant()` Expression in a "hash" key.

This works but is not as verbose as I'd like
```diff
- <argument key="$options" type="expression">{constant("CURLOPT_TIMEOUT"): 60}</argument>
+ <argument key="$options" type="expression">{13: 60}</argument>
```

**Comment by nicolas-grekas** [comment]
If you want to submit a PR, this is the file:
src/Symfony/Component/DependencyInjection/ExpressionLanguageProvider.php

**Comment by simPod** [comment]
There it seems to be already supported. It fails on https://github.com/symfony/symfony/blob/1fc7b86f07993495e6f8c35b0694ba464b528fa0/src/Symfony/Component/ExpressionLanguage/TokenStream.php#L68

> A hash key must be followed by a colon (:). Unexpected token "punctuation" of value "(" ("punctuation" expected with value ":") around position 10 for expression `{constant("CURLOPT_TIMEOUT"): 60}`

I did not find a test that touches that line though. Did not find a way the whole test suite while avoiding phpunit bridge.

**Comment by fabpot** [comment]
Have you tried `{(constant("CURLOPT_TIMEOUT")): 60}`?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by simPod** [comment]
Wrks, thanks!
