### ISSUE TITLE
Symlink Error with PHPUnit Bridge

### ISSUE THREAD

**Issue by pcmanprogrammeur** [symfony/symfony#36238]
**Symfony version(s) affected**: 4.4.4

**Description**  
Hi,
I installed PHPUnit Bridge and i have the error :
`
PHP Warning:  require(/var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/../symfony/phpunit-bridge/bootstrap.php): failed to open stream: No such file or directory in /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/autoload_real.php on line 69
PHP Stack trace:
PHP   1. {main}() /var/www/app/bin/phpunit:0
PHP   2. require() /var/www/app/bin/phpunit:13
PHP   3. include() /var/www/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:343
PHP   4. require() /var/www/app/bin/.phpunit/phpunit-7.5-0/phpunit:4
PHP   5. ComposerAutoloaderInitda22a4a82724781b5e2920b84d165cd2::getLoader() /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/autoload.php:7
PHP   6. composerRequireda22a4a82724781b5e2920b84d165cd2() /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/autoload_real.php:59
PHP Fatal error:  require(): Failed opening required '/var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/../symfony/phpunit-bridge/bootstrap.php' (include_path='.:/usr/share/php7') in /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/autoload_real.php on line 69
PHP Stack trace:
PHP   1. {main}() /var/www/app/bin/phpunit:0
PHP   2. require() /var/www/app/bin/phpunit:13
PHP   3. include() /var/www/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:343
PHP   4. require() /var/www/app/bin/.phpunit/phpunit-7.5-0/phpunit:4
PHP   5. ComposerAutoloaderInitda22a4a82724781b5e2920b84d165cd2::getLoader() /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/autoload.php:7
PHP   6. composerRequireda22a4a82724781b5e2920b84d165cd2() /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/composer/autoload_real.php:59
`
**How to reproduce**  
`composer require --dev symfony/phpunit-bridge`
`php bin/phpunit`

Here is the bug :
`ls -l /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/symfony/phpunit-bridge`
`lrwxrwxrwx    1 root     root   /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/symfony/phpunit-bridge -> /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/symfony/phpunit-bridge`
The simlink is pointing to itself.

**Possible Solution**  
To make it works, i did my own hack :  
`rm /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/symfony/phpunit-bridge`
`ln -s ../../../../../vendor/symfony/phpunit-bridge /var/www/app/bin/.phpunit/phpunit-7.5-0/vendor/symfony/phpunit-bridge`

**Comment by jpjoao** [comment]
Hi @pcmanprogrammeur ,

Have you tried to follow the steps on the documentation?
https://symfony.com/doc/current/components/phpunit_bridge.html#usage

The correct usage is through ` ./vendor/bin/simple-phpunit` and not `bin/phpunit`:

```bash
composer require --dev symfony/phpunit-bridge
Using version ^5.1@dev for symfony/phpunit-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/phpunit-bridge (dev-master 4da3488): Downloading (100%)         
Writing lock file
Generating optimized autoload files
30 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony operations: 1 recipe (ce92ddac607703eeae5c3a99d3f0001c)
  - Configuring symfony/phpunit-bridge (>=4.3): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

              
 How to test? 
              

  * Write test cases in the tests/ folder
  * Run php bin/phpunit

/srv/app # ./vendor/bin/simple-phpunit 
Creating a "phpunit/phpunit" project at "./phpunit-7.5-0"
Installing phpunit/phpunit (7.5.20)
Plugins have been disabled.
  - Installing phpunit/phpunit (7.5.20): Downloading (100%)
Created project in /srv/app/vendor/bin/.phpunit/phpunit-7.5-0
composer.json has been updated
Loading composer repositories with package information
Updating dependencies

Prefetching 27 packages 🎶 💨
  - Downloading (100%)

Package operations: 28 installs, 0 updates, 0 removals
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.9.5): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing doctrine/instantiator (1.3.0): Loading from cache
  - Installing sebastian/exporter (3.1.2): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpdocumentor/reflection-common (2.0.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.15.0): Loading from cache
  - Installing webmozart/assert (1.7.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.1.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.1.0): Loading from cache
  - Installing phpspec/prophecy (v1.10.3): Loading from cache
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/environment (4.2.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-token-stream (3.1.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (6.1.4): Loading from cache
  - Installing phpunit/php-timer (2.1.2): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing symfony/phpunit-bridge (7.5.99): Symlinking from /srv/app/vendor/symfony/phpunit-bridge
Writing lock file
Generating optimized autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.



Time: 10.13 seconds, Memory: 4.00 MB

No tests executed!

```

**Comment by jaytaph** [comment]
I have the same issue. Works fine locally... symlink issue on gitlab runner. The symlink there is also pointing to itself.. The path in composer.json points to the correct directory though:

         "repositories": {
         "phpunit-bridge": {
             "type": "path",
             "url": "/builds/seams-cms/react-api/vendor/symfony/phpunit-bridge"
         }
     }

**Comment by pcmanprogrammeur** [comment]
@jpjoao, Thanks for your help but the problem always persists 😢 
@jaytaph Thanks, i will try your two solutions. I will try them asap.

**Comment by pcmanprogrammeur** [comment]
@jaytaph !
Well done !!!
The composer version was the problem 😃
Thank you very much !
