### ISSUE TITLE
[Typo] Rename occurence to occurrence

### ISSUE THREAD

**Issue by pgrimaud** [symfony/symfony#36242]
**Description**  

You're using the term `occurence` in some files :
- `src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/DeprecationNotice.php`
- `src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/DeprecationGroup.php`

And associated tests :
- `src/Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/DeprecationNoticeTest.php`
- `src/Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/DeprecationGroupTest.php`

`Occurence` is the French term. You should use `Occurrence` instead.

**Comment by nicolas-grekas** [comment]
Up for a PR? Branch 3.4 isn't it?

**Comment by pgrimaud** [comment]
This typo was added with the PR https://github.com/symfony/symfony/pull/35271.
It's for 5.1, so I could make a PR on master?

**Comment by nicolas-grekas** [comment]
Master then yes, thanks.

**Comment by wouterj** [comment]
Yes, the PR should be on master indeed.

Please mention the PR introducing these methods in your description. As the methods where not yet in a Symfony release, they can be renamed without breaking backwards compatibility. If that's clear for the core team, you're more likely to get quick approval for your PR :)
