### ISSUE TITLE
Display Twig's avaiable variables in profiler.

### ISSUE THREAD

**Issue by Nayte91** [symfony/symfony#36247]
Hi there,

As a template designer working on Twig, I may need to know exactly which variables are avaiable when my template is rendered. 'posts', 'users', 'previous', 'next', ...

I can look at the $this->render controller part, but it can miss some added further upstream (like users).
I can ask my dev, but he can forgot some, especially when the project is big.
I can {{ dump() }} in my file, but I already have a tool to help me... The profiler !

I'ld feel natural to have this information displayed in the profiler ! There's already a "Twig" section. Maybe a card (where you find "Render time", "Template calls", ...) with "Variables" and even a slight explanation from where it come, can be piece of cake for you ?

For sure, it will be a big quality of life improvement for us, as I usually find some several months old {{ dump() }} in templates...

Sorry in advance if such a feature already exists,
Thank you very much
Julien "Nayte" Robic

**Comment by noniagriconomie** [comment]
Yeah agreed, it could be great to have them « dumped » in a new twig part of the profiler :)

But there are a lot of twigs vars:

- twig global vars (from config context)
- controller rendered vars
- twig local vars declared in extended templates of the actual one
- maybe i miss more

I do not know the twig logic render flow a lot but maybe some are hard to « datacollect » to made them available in the profiler

If someone knowing can help me i can try this

**Comment by 94noni** [comment]
Hi @Nayte91 
I've opened a PR on https://github.com/symfony/symfony/pull/36249 to give it a try

**Comment by javiereguiluz** [comment]
I'm not sure if the proposed feature is technically feasible (because of how flexible Twig is) and I'm not sure either about the performance implications (Twig variables can be huge).

Another thing you may try is to add annotations in Twig templates declaring the most important variables (see for example this Twig fragment: https://github.com/EasyCorp/EasyAdminBundle/blob/master/src/Resources/views/crud/field/date.html.twig)  It's not possible to do that in some scenarios, but it's OK for other apps and it works great to enable autocompletion in IDEs like PhpStorm.

**Comment by Nayte91** [comment]
Hi @javiereguiluz 
About technical part : you know better than me. But any arbitrary limitation can be OK, like "only the variables passed by the controllers involved in this render AND  ONLY the app.user part IF security is installed..." of course everything-that-twig-can-render-to-hack-your-backend is not the goal.

About performance : if the scope is limited, is the performance implication a huge concern in dev environment ?

About your workaround : Smart ! I'm looking forward to use this practice. But as it's not dynamic, If something changes at your users management i.e...

**Comment by fabpot** [comment]
I fear that this is not possible to implement such a thing. We won't add a feature that is not able to list all variables. I suggest that you try to implement that outside of core first. Let's close for now here.
