### ISSUE TITLE
Display only error 500, when you have the wrong configuration in debug mode.

### ISSUE THREAD

**Issue by ikakarov** [symfony/symfony#36254]
**Symfony version(s) affected**: 4.4.*

**Description**  
When you have the wrong configuration, instead of showing exceptions, an 500 page is displayed.
This problem does not depend on the environment.

**How to reproduce**  
Just set malformed *.ymal file something like this :
```yaml
# config/routes/annotations.yaml
;321-
```

**Comment by nicolas-grekas** [comment]
What else would you expect? If the app is broken, a 500 is the correct display, isn't it?
If you mean that you'd expect a nice customized error page, that's not possible: because the config is broken, the nice error page cannot be configured...

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by blowski** [comment]
In debug mode, it shows a `LoaderLoadException`, telling you which file contains malformed YAML. 

```
ParseException > InvalidArgumentException > LoaderLoadException
HTTP 500 Internal Server Error 

The file "config/routes/annotations.yaml" does not contain valid YAML in config/routes/annotations.yaml (which is loaded in resource "config/routes/annotations.yaml").
```

You can't compile the container, so you can't register an ExceptionListener that would do anything else. I'm not sure how you could do anything else at the Symfony level. You *could* use your webserver (e.g. nginx or Apache) to intercept 500 errors and show something more end-user friendly, but I'd first try to change the workflow so I don't need to handle broken YAML files in production.

**Comment by ikakarov** [comment]
### !!! Sorry for may very bad english !!!
@nicolas-grekas I expect at least two things:
1. possability to see errors in debug mode. 
2. possability to change error page. 

This is a very annoying problem because not all errors will be captured and a page that does not change will be displayed.

@blowski It is on symfony level, overwrites all server and php configurations. 

when you have error in routes/*.yaml  if you have this page: 
![image](https://user-images.githubusercontent.com/53010894/77913064-4e291000-729c-11ea-874f-d10bbb08cb96.png)

This page generated in `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer` and not correct pass $debug __construct parameter. 

After small but very stupid fix something like this : 
```php
#vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php
...
 /**
     * @param bool|callable $debug        The debugging mode as a boolean or a callable that should return it
     * @param bool|callable $outputBuffer The output buffer as a string or a callable that should return it
     */
    public function __construct($debug = false, string $charset = null, $fileLinkFormat = null, string $projectDir = null, $outputBuffer = '', LoggerInterface $logger = null)
    {

        if (!\is_bool($debug) && !\is_callable($debug)) {
            throw new \TypeError(sprintf('Argument 1 passed to "%s()" must be a boolean or a callable, "%s" given.', __METHOD__, \is_object($debug) ? \get_class($debug) : \gettype($debug)));
        }

        if (!\is_string($outputBuffer) && !\is_callable($outputBuffer)) {
            throw new \TypeError(sprintf('Argument 5 passed to "%s()" must be a string or a callable, "%s" given.', __METHOD__, \is_object($outputBuffer) ? \get_class($outputBuffer) : \gettype($outputBuffer)));
        }
  if(getenv('APP_ENV') != 'prod' 
            OR getenv('APP_DEBUG') == 1
            OR (isset($_SERVER['APP_DEBUG']) AND $_SERVER['APP_DEBUG'] == 1) 
        ){
            $debug = true;
        }
        $this->debug = $debug;
        $this->charset = $charset ?: (ini_get('default_charset') ?: 'UTF-8');
        $this->fileLinkFormat = $fileLinkFormat ?: (ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format'));
        $this->projectDir = $projectDir;
        $this->outputBuffer = $outputBuffer;
        $this->logger = $logI can't overwrite  `error_handler.error_renderer.html` service. In my case i just replace Symfony\Component\ErrorHandler\ErrorRenderer namesapce in composer whit my own file. ger;
    }
...
```
i have this page : 
![image](https://user-images.githubusercontent.com/53010894/77913763-83822d80-729d-11ea-9975-85774f0bdb18.png)

I can't overwrite  `error_handler.error_renderer.html` service. In my case i just replace Symfony\Component\ErrorHandler\ErrorRenderer namesapce in composer whit my own stupid fix class.

**Comment by blowski** [comment]
Thanks for the update.

I just did the following:

* clean install of Symfony 4.4
* entered invalid Yaml in config/routes/annotations.yaml
* load in the browser (Symfony webserver)

I get the "nice error page" you showed in your comment, which leads me to think you have a configuration problem. Can you use xdebug (or at least `dd(debug_backtrace())`) to figure out what's being passed to HtmlErrorRenderer?

**Comment by ikakarov** [comment]
@blowski like this ? 
```
  0 => array:7 [▼
    "file" => "/repos/Tutorials/ApiPlatform/PaerOne/lesson1/start/vendor/symfony/error-handler/ErrorHandler.php"
    "line" => 707
    "function" => "__construct"
    "class" => "Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer"
    "object" => Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer {#3637 ▼
      -debug: null
      -charset: null
      -fileLinkFormat: null
      -projectDir: null
      -outputBuffer: null
      -logger: null
    }
    "type" => "->"
    "args" => array:1 [▼
      0 => false
    ]
  ]
```

**Comment by blowski** [comment]
Yes, that's really useful, thanks. Go back through the whole backtrace and figure out why `debug` is either null or false - it should be true in the `dev` environment. 

Some pointers:
1. The `.env` file should have a line like `APP_ENV: dev`.
2. In `public/index.php` you should see something like `if($_SERVER['APP_DEBUG']) { Debug::enable(); }`. 
3. `$_SERVER['APP_DEBUG']` is set in `config/bootstrap.php`.

**Comment by yceruto** [comment]
Yes, you should be able to see the detailed exception page if the debug mode is enabled only. Please, check the @blowski's [comment](https://github.com/symfony/symfony/issues/36254#issuecomment-606026731).

**Comment by ikakarov** [comment]
@blowski Everything is standard. The problem is that Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer does not pass parameters when there is a syntax error.

I think the problem is that error_handler.error_renderer.html expects a data request service as a parameter when there is a syntax error.

**Comment by blowski** [comment]
I can't reproduce your problem from this side, so I can't really do much to help debug. For me, with a clean install running in dev, I get a full error message. 

Are you getting full error message only for malformed YAML, or for all other errors as well?

The only next steps I can think of are to try doing a clean install on your environment to see if there's something weird going on that's producing an edge case.

**Comment by yceruto** [comment]
@blowski the html error renderer won't work as service because there is a config error, so the container compilation process is broken. However, there is a fallback mechanism to catch that errors: see `ErrorHandler::renderException()` -> `new HtmlErrorRenderer($this->debug)`.

You should see the exception page if `$this->debug` is `true`, and that will happen only if debug mode (`Debug::enable()`) is called on your front.

**Comment by blowski** [comment]
@yceruto Thanks.

I don't get why @ikakarov is not experiencing all sorts of weirdness if not in debug mode.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Herz3h** [comment]
I upgraded from symfony 3.4 to 4.4 and ever since, sometimes I get a nice error page showing the exception, and sometimes I just get the  500 error page. Luckily I have sentry to report me the errors, for instance now it shows error 500 without any additional info, and sentry reports: 

`Object of class Doctrine\ORM\PersistentCollection could not be converted to string`

Output of `dd(debug_backtrace())` returns:

```
 [▼
    "file" => "/Users/home/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php"
    "line" => 80
    "function" => "handleRaw"
    "class" => "Symfony\Component\HttpKernel\HttpKernel"
    "object" => Symfony\Component\HttpKernel\HttpKernel {#607 ▼
      #dispatcher: Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher {#602 …8}
      #resolver: Symfony\Component\HttpKernel\Controller\TraceableControllerResolver {#518 ▼
        -resolver: Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver {#517 ▼
          #parser: Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser {#647 ▼
            #kernel: AppKernel {#17 ▼
              #bundles: array:35 [▶]
              #container: Container0EKP23g\appAppKernelDevDebugContainer {#63 …20}
              #rootDir: "/Users/home/project/app"
              #environment: "dev"
              #debug: true
              #booted: true
              #name: "app"
              #startTime: 1597215689.1078
              -projectDir: null
              -warmupDir: null
              -requestStackSize: 1
              -resetServices: true
            }
          }
...
]
```

After reading above, I don't  have any .env file, I tried adding one with value of: `APP_ENV=dev` and no difference. I have `Debug::enable()` and `new AppKernel('dev', true)` in `app_dev.php`

**Comment by Herz3h** [comment]
After searching a bit in code, I found out that [this line](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpKernel/HttpKernel.php#L81) is maybe the reason it doesn't catch exceptions. As of [php 7](https://www.php.net/manual/en/language.errors.php7.php), errors are not reported using traditional error mechanisms, but reported as exception of type `Error`.

To test this, I just changed \Exception to \Error, and the exception is displayed.

**Comment by ikakarov** [comment]
https://github.com/symfony/symfony/issues/36254#issuecomment-672697223 - This solution is tested and worked, i just changed this   
```php 
} catch (\Exception $e) {
```
 to this 
```php
 } catch (\Exception|\Error $e) {
``` 
at line 85. But this solution is not optimal, and I'm not convinced it will work everywhere.

**Comment by Herz3h** [comment]
Still facing this annoying issue, should I open a new issue?

**Comment by msieracki00** [comment]
> Still facing this annoying issue, should I open a new issue?

Same issue for me

**Comment by stof** [comment]
> I upgraded from symfony 3.4 to 4.4.10

Can you check which `Debug::enable()` call you have in your front controller ? Symfony 4.4 contains 2 such classes:
- the old one `Symfony\Component\Debug\Debug`
- the new one `Symfony\Component\ErrorHandler\Debug`

Maybe the issue happens only when using the old Debug class (i.e. when upgrading Symfony without updating the front controller) ?

**Comment by Herz3h** [comment]
> Debug::enable

That was it, thank you very much!!

**Comment by stof** [comment]
@nicolas-grekas looks like something is still wrong in the BC layer when using the old component. It might be good to fix it if possible.

**Comment by AkashicSeer** [comment]
Is there any fix to this yet?

This is an absolute problem. How do I get Symfony to record in the error logs WTF it is erroring out? I can't fix anything If  I don't have any info to go by. This one thing is keeping me from getting my Symfony app from working. This is the stupidest thing I have ever encountered.

**Comment by jbgomond** [comment]
I can confirm the problem coming from 4.0 to 4.4 :) The debug page is not shown when using 

> Symfony\Component\Debug\Debug 

instead of

> Symfony\Component\ErrorHandler\Debug

**Comment by xabbuh** [comment]
I am not able to reproduce the described issue. Can someone of you please create a small example application that allows to do so?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
