### ISSUE TITLE
Embedded collection form and how to dynamically modify it

### ISSUE THREAD

**Issue by bvdham** [symfony/symfony#36255]
**Symfony version(s) affected**: 5.0.*

**Description**
After reading [How to Embed a Collection of Forms](https://symfony.com/doc/current/form/form_collections.html)  and [How to Dynamically Modify Forms Using Form Events](https://symfony.com/doc/current/form/dynamic_form_modification.html) i've a situation where i need to combine those two techniques. Let me try to clarify myself and the problem with some example code and a reproducer.

Just like Embed Collection of Forms i've a Tag and in my example changed Task to Release. Release has the fields `message` and `tags` and a Tag has the fields `versions`, `type (lightweight|annotated)` and `message`.

The part collection is working, i could add or remove a tag, see screenshot below (for simplicity i've used examples without styles)
![image](https://user-images.githubusercontent.com/7288381/77848257-ca9bf000-71c3-11ea-8fec-5fd525bc7c9a.png)

Now for the Dynamically modify part, where in my situation when a user select `annotated` from the type choice field, the message field should be appear. In my code (TagType) i've created the eventListeners with a formModifier, see code below

```
class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('version', TextType::class, [
            'label' => 'Version'
        ]);

        $builder->add('type', ChoiceType::class, [
            'label' => 'Type',
            'placeholder' => 'Select Type ...',
            'attr' => [
                'class' => 'type'
            ],
            'choices' => [
                'Lightweight' => 'lightweight',
                'Annotated' => 'annotated'
            ]
        ]);

        $builder->add('delete', ButtonType::class, [
            'label' => 'Delete this tag',
            'attr' => [
                'class' => 'collection-type-remove'
            ]
        ]);

        $formModifier = function (FormInterface $form, Tag $tag = null) {
            if(null !== $type = $tag->getType()) {
                if($type === 'annotated') {
                    $form->add('message', TextType::class, [
                        'label' => 'Message',
                        'required' => true
                    ]);
                }
            }
        };

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) use ($formModifier) {
            $form = $event->getForm();

            /** @var Tag $tag */
            if(null === $tag = $event->getData()) {
                return;
            }

            $formModifier($form, $tag);
        });

        // attempt 1, event listener on type field

        // problem is we need to get an Tag data object (filled with post data) but
        // how is this possible, only getting the type 'type' value
        // or the parent data what is null.
        $builder->get('type')->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event) use ($formModifier) {
            // select parent else warning could not modify posted form
            $form = $event->getForm()->getParent();

            // expected data should be Tag but getting null
            // $tag = $event->getForm()->getParent()->getData(); null ?

            // posted data (lightweight|annotated) but need Tag object
            // $tag = $event->getForm()->getData();

            // test to add form should be done by calling $formModifier but need Tag object how?
            $form->add('message', TextType::class, [
                'label' => 'Message',
                'required' => true
            ]);

            // could be used only when $tag is Tag object
            // we need this approach because like the docs tell:
            // ::add new children to the parent form, the Form component will detect the new field automatically and map it to the submitted client data.
            // $formModifier($form, $tag);
        });

        // attempt 2, event listener on complete form TagType

        // This attempt will add the form field but when submitting the value is not being updated
//        $builder->addEventListener(FormEvents::SUBMIT, function(FormEvent $event) use ($formModifier) {
//            $form = $event->getForm();
//            $tag = $event->getData();
//
//            $formModifier($form, $tag);
//        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
            'allow_extra_fields' => true,
            'attr' => [ 'class' => 'tag collection-type-entry' ]
        ]);
    }
```

There are three EventListeners, this first is the `PRE_SET_DATA` that is calling the `$formModifier`, the formModifier should add the field `message` to the form, when the user Posts an `Tag` object where `type` is equals to annotated.  The first Param is FormInterface and the second param needs to be a Tag object. 

I've created two attempts (different event listeners). One that listens to the field `type` (attempt 1) and one that listens to the main form (attempt 2). The problem in attempt 1 is a need a Tag object filled with the correct post data, that could be used in the formModifier, but Tag is always null (thats why i just add message here to the form for testing).

Attempt 2 is filling the Tag and after calling formModifier the field message is being added, but data is not set correctly on submitting, because the dynamic fields are null. If you post the data like the image above in this attempt the dump tell us that the dynamically field message is null (so its not automatically mapped to the submitted client)
![image](https://user-images.githubusercontent.com/7288381/77848713-18662780-71c7-11ea-8710-c2799b1ded6c.png)

So i need attempt 1 (where the Form component will detect the new field automatically and map it to the submitted client data) but also need a Tag data object given to formModifier with the give posted data.

**How to reproduce**  
I have a small app that reproduces it here: https://github.com/bvdham/collection-form-embedded-auto.git. Let me explain the detail 

1) Clone repository
2) Run the server by `symfony serve`
3) Go to the application `http://127.0.0.1:8000/`
4) On the simple index page, add a new release
5) Now in code you could test both attempts ,  uncomment one of them
**Attempt 1:** https://github.com/bvdham/collection-form-embedded-auto/blob/master/src/Form/TagType.php#L71
**Attempt 2:** https://github.com/bvdham/collection-form-embedded-auto/blob/master/src/Form/TagType.php#L98
6) On submit you should see aan dump with the form data

Hope someone has an possible solution

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
