### ISSUE TITLE
Stale cache is not regenerating correctly

### ISSUE THREAD

**Issue by AndreRudolph** [symfony/symfony#36253]
**Symfony version(s) affected**: 5.0.4

**Description**  
Somehow the automatic invalidation of the Symfony core cache is not working properly for my project. Whenever I change a class that is considered by the container (e.g. a controller), the cache is broken and Symfony is not able to regenerate the cache by itself. The only way of getting the application work again is clearing the cache manually with the respective console command.

I have debugged this issue as far as I can and it seems to be broken within the MergeExtensionConfigurationPass while validating / loading the configuration files (e.g. web.xml and services.xml) from the FrameworkBundle. The trouble causing class is:

Symfony\Component\DependencyInjection\Loader\XmlFileLoader.php (Line: 638):

`$valid = @$dom->schemaValidateSource($source);`

The execution of this line breaks the code execution immediately without any logged error (neither in the Symfony nor in the php error logs, log level is set to E_ALL). This sometimes fails first at the web.xml and on other occassions this fails later while validating the services.xml. I have also tried to remove the '@' and surround the call with a Throwable catch and no error / exception was caught.

Environment is set to 'dev' and debug is enabled.

Is this a symfony bug? And what can I do to get a clear error message what happens there?

Thanks in advance!

**Comment by nicolas-grekas** [comment]
What's the error then?
Can you provide a reproducer we could run locally to experience this issue?

**Comment by AndreRudolph** [comment]
I got no error message which is the main problem behind this. The execution suddenly stops. I can not provide my project but I can also reproduce it with the symfony skeleton app:

`composer create-project symfony/website-skeleton symfonytest`

After creating a simple controller:

`<?php
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    public function index()
    {
        return $this->render('base.html.twig');
    }
}`

The app gets broken and I need to refresh the cache manually by using 

`php bin/console cache:clear`

Whenever I change something in this controller after running this command, the app is broken again and I need to re-execute the cache clear command.

**Comment by xabbuh** [comment]
I cannot reproduce this. I am afraid you will need to do some debugging yourself to find out what is actually going on.

**Comment by AndreRudolph** [comment]
Okay, thanks for your effort! I guess it is somehow related to my environment then. I am using PHP 7.4.1 in a MAMP environment by the way. I will investigate more time in debugging this issue and post the outcome here, thanks. :)

**Comment by nicolas-grekas** [comment]
Did you try removing the `@` on that line to see what happens?

**Comment by AndreRudolph** [comment]
Yes, I tried to remove that error supression `@` but it didn't change anything unfortunately. The strange thing about this is, that when it fails the execution stops immediately without any error and triggers a new execution and then it fails again at this line. This execution gets 'repeated' two times in total and after that the process is completely finished and the cache is still broken. 

I guess I need to investigate more time in debugging this issue.

**Comment by xabbuh** [comment]
@AndreRudolph Did you by chance manage to gather some more insights?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
