### ISSUE TITLE
Extending MimeTypes class

### ISSUE THREAD

**Issue by elshobokshy** [symfony/symfony#36275]
What is the proper way to extend the `MimeTypes` class in order to change the order of, for example : 

    'audio/mpeg'` => ['mpga', 'mp2', 'mp2a', 'mp3', 'm2a', 'm3a'],

to 

    'audio/mpeg' => ['mp3', 'mpga', 'mp2', 'mp2a', 'm2a', 'm3a'],

in `Symfony\Component\Mime\MimeTypes`

**Comment by javiereguiluz** [comment]
You could create a custom class that calls to Symfony MIME guesser and do this change only for this extension. Or you could add your own MIME type guesser as explained in https://symfony.com/doc/current/components/mime.html#mime-types-utilities

In any case, we don't answer support questions in this repository. Please, use the alternatives shown in https://symfony.com/support Thanks!

**Comment by elshobokshy** [comment]
Thank you! Sorry to bother :)
