### ISSUE TITLE
[Serializer] Groups not working 

### ISSUE THREAD

**Issue by pesseyjulien** [symfony/symfony#36288]
**Symfony version(s) affected**: 4.4.x

**Description**  
Hi, 

I'm using groups to serialize data but it's not always working.

For example : 

```
    /**
     * @ORM\Column(type="array", nullable=true)
     * @Groups({"me_user", "write_user"})
     */
    protected $register_purposes;
```

```
        //return serialized data
        $serializedEntity = $this->container->get('serializer')->serialize($users, 'json', array('groups' => ['me_user']));
        return new Response($serializedEntity, 200, ['Content-Type' => 'application/json']);
```

Won't work until I passed the field with public access. 
So : public $register_purposes;

Any idea why ?

**Comment by xabbuh** [comment]
What do you mean with "won't work"? What did you expect? What happens instead? How do things behave differently when you do not use groups?

**Comment by pesseyjulien** [comment]
Well the field is not hydrated and therefore not returned in the response. I have to force the hydratation by passing the field scope to 'public'.

**Comment by xabbuh** [comment]
Is this different when you do not use groups?

**Comment by pesseyjulien** [comment]
not working either indeed, with or without groups. I don't get it..

**Comment by pesseyjulien** [comment]
Can it be a conflict with ApiPlatform  ?

```
 * @ApiResource(
 *
 *   attributes={"normalization_context"={"groups"={"read_company"}}, "denormalization_context"={"groups"={"write_company"}}},
```

**Comment by pesseyjulien** [comment]
But it's not doing that with all the fields, for example the following works 

```
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read_company", "write_company"})
     */
    protected $email;
```

**Comment by danieljank** [comment]
I'm facing some similar problem.

Does your behavior change if you add, for example, the following to your @ApiResource Annotation?

`
collectionOperations={
    "get",
},
itemOperations={
    "get",
}`

For me, by not adding those operations, results in adding `"skip_null_values" => true` to the context.

**Comment by pesseyjulien** [comment]
I have them already 

```
 *   collectionOperations={ "get"={"method"="GET"} },
 *
 *   itemOperations={ "get"={"method"="GET"}, "delete"={"method"="DELETE"} }
```

And I have values for the fields not being hydrated/returned. Only solution for me is to make them 'public' but it's not normal..

**Comment by lmasforne** [comment]
@pesseyjulien it seems to be the name of your property '$register_purposes' try with 'registerPurposes' it seems not resolving the snake case i dont kown why i'm finding

**Comment by lmasforne** [comment]
@pesseyjulien i try to get data with the method 'getRegister_purpose' but it think you got getRegisterPurpose in your Entity

**Comment by pesseyjulien** [comment]
Good catch @lmasforne, did not think about that.. Hopefully your PR will be accepted !

**Comment by xabbuh** [comment]
@pesseyjulien Wouldn't your issue be solved by injecting the needed name converter into the `GetSetMethodNormalizer` in your application?

**Comment by pesseyjulien** [comment]
Do you have an example @xabbuh ?

**Comment by lmasforne** [comment]
@pesseyjulien i'm sorry but this change could not be added for several reason : 
- Symfony doesn't want to support all possible combinations of conventions. The supported conventions are documented. Mixing snake case (for property names) and camel case (for method names) isn't supported. see here : https://symfony.com/doc/current/components/serializer.html#camelcase-to-snake-case
-  It's already possible to support such conventions userland by using the ObjectNormalizer along with a custom implementation of the PropertyAccessorInterface
see here :
https://symfony.com/doc/4.4/serializer/normalizers.html

**Comment by pesseyjulien** [comment]
Got it, thanks. I will check the doc and resolve this on my end.
