### ISSUE TITLE
[Process] Commands with parentheses will fail on Windows OS

### ISSUE THREAD

**Issue by benjaminfunk** [symfony/symfony#36298]
**Symfony version(s) affected**: 5.0.*

**Description**  
The process command will fail if you use multiple parentheses in the command. Its just on Windows.

In the example the Exception will thrown but with the wrong error (not the magick error (unable to open...))

**How to reproduce**  
```
$objProcess = Process::fromShellCommandline('magick ( "test.miff" ) ( -clone 0 hardlight -write "test.miff" ) +delete -blur 3x5 "test.miff"');
$objProcess->run();

if (!$objProcess->isSuccessful())
{
   	throw new ProcessFailedException($objProcess);
}
```

**Possible Solution**  
Remove predefined parentheses in this line: https://github.com/symfony/process/blob/2e48825eae8cf1318cf0e2dc960e35d743c43c07/Process.php#L1553

or

Make the predefined parentheses optional

**Comment by nicolas-grekas** [comment]
Won't removing these parentheses break something else?

**Comment by benjaminfunk** [comment]
Not in my cases, but of course I cannot guarantee all the other commands :/

**Comment by benjaminfunk** [comment]
I updated the Possible Solution(s)

**Comment by nicolas-grekas** [comment]
What do the bracket mean in your command line? To me, no shell allow unescaped brackets.

**Comment by nicolas-grekas** [comment]
OK, I just read the doc.
The issue is on your side: unescaped brackets have a meaning for the shell, both on windows and on linux. You need to use this instead, this will take care of escaping:

`$objProcess = new Process(['magick', '(', 'test.miff', ')', '(', '-clone', '0', 'hardlight', '-write', 'test.miff', ')', '+delete', '-blur', '3x5', 'test.miff']);`

**Comment by benjaminfunk** [comment]
Thanks nicolas. Your suggestion works well!
