### ISSUE TITLE
[HttpClient] Asynchronous requests are not send (immediately)

### ISSUE THREAD

**Issue by Jeroeny** [symfony/symfony#36299]
**Symfony version(s) affected**: ^4.3 (but confirmed on 5.0.7)

**Description**  

When using `Symfony\Component\HttpClient\HttpClient` to send a request, it should be send asynchronously. Which means upon calling the `request` method, the call should be sent, but not wait for a response.
When calling `getContents` or other function on the `ResponseInterface`, it _will_ wait for the response. In my application this seems to be working as intended.
However in this Bug Reproducer, it sends the request similar to as how the `HttplugClient` does it (which is the implementation for which I was originally making this bug report), described below.

When wrapping `Symfony\Component\HttpClient\HttpClient` in `Symfony\Component\HttpClient\HttplugClient`, the same logic would be expected.
However, no request it sent upon calling `request`. It is only sent when:
- `wait()` is called on the return value of `Symfony\Component\HttpClient\HttplugClient`, which is `Http\Promise\Promise`
- `__destruct` is called for the `\Symfony\Component\HttpClient\Response\CurlResponse`
- when another call is made using the same `CurlClient` 

This does not seem to be expected when reading the docs or in case of `Http\Client\HttpAsyncClient::sendAsyncRequest`. I've discovered it due to a request where we do not use the response and do not check it, so never wait for it with a blocking call. In a web application, the call might be sent on `__destruct`. However this logic is running in a messenger container. Which is a long running process. 

**How to reproduce**  
**Bug Reproducer**: https://github.com/Jeroeny/reproduce/tree/symfony-httpclient-async

**Possible Solution**  
I've gone through the `CurlHttpClient`, but couldn't find where/what happens. If this is in fact a bug - and not expected behaviour - I'm willing to create a PR if someone has found out what causes this bug. 

Edit:
While further debugging, I've found that the behaviour is the same regardless of using `CurlHttpClient` or `NativeHttpClient`, and using `ScopingHttpClient` or not.

**Comment by nicolas-grekas** [comment]
Yes, this is not a bug but this is expected. In PHP, there is no event loop. This means absolutely nothing runs in the background. If you don't give the engine an opportunity (or many actually) to actually spend time dealing with the request/response, nothing will happen. That's how things work.

**Comment by Jeroeny** [comment]
> Yes, this is not a bug but this is expected. In PHP, there is no event loop. This means absolutely nothing runs in the background. If you don't give the engine an opportunity (or many actually) to actually spend time dealing with the request/response, nothing will happen. That's how things work.

Thanks for your reply. I'm indeed aware that you have to call it to actually get the response or check the status

However, the docs state:
> Responses are always asynchronous, so that the call to the method returns immediately instead of waiting to receive the response:

Does that mean when doing `the call to the method`, the Http request is not send?  And:

> Thanks to responses being lazy, requests are always managed concurrently. On a fast enough network, the following code makes 379 requests in less than half a second when cURL is used:

(https://symfony.com/doc/current/components/http_client.html#concurrent-requests)

Is that first `foreach` then not actually sending requests, but are they sent in the second `foreach`? Because that is the behaviour I'm experiencing.

**Comment by nicolas-grekas** [comment]
Sending a request is a multi-step process. First there is DNS resolution, then there is connection opening or pooling, then there is writing to the network. And I'm missing a lot of steps. "sending the request" is a blocking operation. What the client *possibly* does is initiate the first non-blocking steps. This never goes up to actually writing all the request to the network, for the reasons I just mentioned. But you should not rely on such an implementation detail...

**Comment by Jeroeny** [comment]
Interesting. So if I try to send a second request (which causes the first request to actually be send), I may be that the first request has resolved it's DNS (or performed other needed operations) and is then able to write the request to the network? I guess I'm used to the Httplug and Guzzle interfaces, where the request is indeed send. But unfortunately that may indeed be an implementation detail.

**Comment by nicolas-grekas** [comment]
Yes, you're correct: on the 2nd request, the client will usually also complete all newly non-blocking operations

**Comment by Jeroeny** [comment]
Alright, I'll make it wait for the response then. Thank you!
