### ISSUE TITLE
[FORM] Raw password when submit form Symfony 5.0.7

### ISSUE THREAD

**Issue by Mael-91** [symfony/symfony#36300]
**Symfony version(s) affected**: 5.0.7

**Description**  
When the form is submitted, and we do a dd on the $user variable (User entity), the password is not encoded

**How to reproduce**  
``` php
public class myclass(Request $request, User $user) {
	$form = $this->createForm(MyForm::class, $user);
	$form->handleRequest($request);
        // before the condition, when I do a dd on $user variable, the password is encoded
	if ($form->isSubmitted() && $form->isValid()) {
		// When you doa dd on $user variable, it displays information related to the current user
		dd($user); // display raw password (not encoded) but when a person sign up the password is encoded via UserPasswordEncoderInterface
	}
}
```

I don't know if this is a bug or if I'm the one who made a mistake in my code

Have a nice day !

**Comment by xabbuh** [comment]
My guess is that your form contains a field for the user password. When submitting it the data is mapped to the underlying object. Now, you need to be aware that the submitted raw password data is not magically hashed by Symfony if you do not add some code that does this. In any case, this does not look like a bug to me.

If you need more help with setting up your form, please refer to one of the [support channels](https://symfony.com/support) as we use GitHub issues only to discuss new features and for bug reports. So I am going to close here. Thank you for understanding.
