### ISSUE TITLE
[Dotenv] Default value - variable fallback

### ISSUE THREAD

**Issue by develforever** [symfony/symfony#36309]
**Description**  
When I try fallback to default value with variable, dotenv return string representation . 

**Example**  
This no return server value of key `HTTP_HOST`, but string HTTP_HOST
```
APP_HOST=${HTTP_X_FORWARDED_HOST:-HTTP_HOST}
```
Other usage also not work and throw format exception
```
APP_HOST=${HTTP_X_FORWARDED_HOST:-$HTTP_HOST}
APP_HOST=${HTTP_X_FORWARDED_HOST:-${HTTP_HOST}}
```
**Question**
How to do this with dotenv? 

**Suggestion**
It would be helpful to return the string value of a variable instead of string  - like in bash
```
a=1
b=2
echo "var = ${b?b:a}"
2
```

**Comment by fr4ngus** [comment]
Maybe I'm wrong but generally, for fallback values, it's safer to use a string instead of a variable which can be undefined.

**Comment by develforever** [comment]
Right but. I mean "variable" from eg. SERVER array like a string key. Do You already now what I mean? Sample if I use HTTP_HOST and not exist then i want use HTTP_FORWARDED_HOST instead. This is not the same as usage of PHP variables. Now I must use in PHP code with if statements to do that.

**Comment by nicolas-grekas** [comment]
The Dotenv component doesn't support all possible syntax allowed by a real shell.
But maybe this specific one is simple enough to support? Would you like to submit a PR to give it a try?

**Comment by develforever** [comment]
Yes, I will try.

**Comment by fr4ngus** [comment]
In this specific case (using value from $_SERVER array which has a key beginning by http_) is not allowed by default by the DotEnv component.

**Comment by develforever** [comment]
@fr4ngus  what exactly do You mean? Example:
`APP_HOST=${HTTP_X_FORWARDED_HOST:-$HTTP_HOST}`
You mean first or second key that will not working?

**Comment by fr4ngus** [comment]
According to the following line:

https://github.com/symfony/symfony/blob/09645a9103a4eb55c8ff081ea8632179c408dce9/src/Symfony/Component/Dotenv/Dotenv.php#L519

**Comment by develforever** [comment]
@fr4ngus Ok. I think my usage is problematic. This issue may be closed. Thanks for Your time.
