### ISSUE TITLE
[Console] Special characters on asking question

### ISSUE THREAD

**Issue by YaFou** [symfony/symfony#36324]
**Symfony version(s) affected**: 5.0.7

**Description**  
In a command, when the user answers a question with special characters with accents (é, è, à, ...); the output doesn't consider these characters and removes them from the string.

**How to reproduce**  
1. Create a command
2. In the `execute` method, write the code below:
```php
$io = new SymfonyStyle($input, $output);
$userInput = $io->ask('Type here');
$io->writeln($userInput);
return 0;
```
3. Execute the command and type such as `Bonjour à tous !`
4. The output should be `Bonjour \ tous !`
> I've reproduced the project in a [repository](https://github.com/YaFou/symfony-bug-console).

**Possible Solution**  
It's possibly the encoding of my terminal or in the source code.

**Additional context**  
I use the Windows Terminal Preview with Git Bash. And I've tested on the Windows terminal.
![image](https://user-images.githubusercontent.com/33806646/78290796-96f2fa00-7524-11ea-8d62-09ab7d4a80dc.png)

**Comment by lmasforne** [comment]
I have tested too, and i think it's a specific windows bash encoding problem because it's work on linux correctly as you can see : 
![capture-console](https://user-images.githubusercontent.com/2681907/78423327-dd03a700-7665-11ea-95d4-bc4a88197fab.png)

**Comment by YaFou** [comment]
I've tested with a simple script like this:
```php
echo 'Type here: ';
$input = readline();
echo $input;
```
and I have no problem with the encoding as you can see:
![image](https://user-images.githubusercontent.com/33806646/78459690-11ee1900-76bb-11ea-8db0-53ca706eda6a.png)

**Comment by YaFou** [comment]
After some research, I find where this issue come: [QuestionHelper#L125](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php#L125).
```php
$ret = fgets($inputStream, 4096);
```

Here, it's a simple way to test it:
```php
echo 'Type here: ';
$resource = fopen('php://stdin', 'r');
$input = fgets($resource);
echo $input;
```

**So, finally, the problem comes from PHP and not Symfony. However, there is no solution to avoid to use `fgets()`?**

**Comment by benjaminfunk** [comment]
```
sapi_windows_cp_set(437);

echo 'Type here: ';
$resource = fopen('php://stdin', 'r');
$input = fgets($resource);
echo $input;
```

Will fix the problem for me. I tried "chcp 437" in my console but it always reset the settings to default 850.

https://bugs.php.net/bug.php?id=76897 Its not a bug from PHP (look comment)

https://stackoverflow.com/questions/8331353/how-to-read-non-ascii-characters-from-cli-standard-input
