### ISSUE TITLE
[preload][cache] ContractsTrait cause EOF while preloading

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#36328]
Symfony 5.0.7

PHP7.4 Preloading of code which uses `Cache` or `CacheInterface` cause `EOF` or `signal 11 (SIGSEGV)`. 

I've prepared the example https://github.com/wtorsi/symfony-cache of full Symfony app.

```php
class AppController extends AbstractController
{
    /**
     * @Route("/ok")
     */
    public function ok()
    {
        return new Response('ok');
    }

    /**
     * @Route("/not")
     */
    public function not(CacheInterface $cache)
    {
        $value = $cache->get('test_key', function (CacheItemInterface $item) {
            $item->expiresAfter(5 * 60);

            return 'value_1';
        }, INF);

        return new Response('not_ok'.$value);
    }
}
```
After some investigations I found that the problem occurred by the 58 line of `Symfony\Component\Cache\Traits\ContractsTrait` 

```php
namespace Symfony\Component\Cache\Traits;
...
trait ContractsTrait
...
    private function doGet(AdapterInterface $pool, string $key, callable $callback, ?float $beta, array &$metadata = null)
    {
        if (0 > $beta = $beta ?? 1.0) {
            throw new InvalidArgumentException(sprintf('Argument "$beta" provided to "%s::get()" must be a positive number, %f given.', static::class, $beta));
        }

        static $setMetadata; //58 line, which causes the problem

        $setMetadata = $setMetadata ?? \Closure::bind(
...
```

I am not good enough in preloading, so I don't know how to fix this problem properly. But i'm ready to fix it, if smb describes the solution.

**Comment by lmasforne** [comment]
Hello @wtorsi 
I try your code and copy / paste in a fresh Symfony 5.07 install and i don't got your error, the response is 'not_okvalue_1' and i see the key 'test_key' on the web profiler.
My configuration : 
- Symfony 5.07
- Php 7.4.4
- The symfony web server from binary

**Comment by wtorsi** [comment]
@lmasforne sounds strange, did you enable `opcache.preload` ?

**Comment by nicolas-grekas** [comment]
Which exact version of PHP do you use @wtorsi? Segfaults are not on Symfony's side but on PHP's. Yet, maybe this is fixed already and you're not on the latest version? If you are, this should be submitted to bugs.php.net.

**Comment by nicolas-grekas** [comment]
Did anyone submit a PHP bug report about this? @luca-nardelli can you open one please? I think you have the most precise description (a static inline variable inside a trait).

/cc @nikic as that might ring a bell to you maybe :) (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Traits/ContractsTrait.php#L58)

**Comment by luca-nardelli** [comment]
I'll submit the bug report, give me some time to create the example

**Comment by luca-nardelli** [comment]
Here it is: https://bugs.php.net/bug.php?id=79548

Also, reproducer repo is here: https://github.com/luca-nardelli/symfony-cache-segfault-reproducer/tree/master

**Comment by luca-nardelli** [comment]
Update: PHP 7.4.6 is out (https://www.php.net/ChangeLog-7.php#7.4.6), but there's no mention of the bug in the changelog, so it's probably going to be in the next patch release I hope

**Comment by nikic** [comment]
@luca-nardelli Yes, this change will be in 7.4.7.

**Comment by nicolas-grekas** [comment]
Nice. Thankyou all for your involvement. Closing here then.
