### ISSUE TITLE
Problem with overwriting form data (PRE_SUBMIT & setData)

### ISSUE THREAD

**Issue by m-adamski** [symfony/symfony#36331]
**Symfony version(s) affected**: 5.0.5

**Description**  
I’m facing some problem with Form module. I know there have been similar submissions, but the advice was to listen to the PRE_SUBMIT event as I do. I am trying to change the value of a given field (the example below is a simplification in relation to my code, but it shows what I have a problem with).

**How to reproduce**  
```(php)
 public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add("firstName", TextType::class, [
                "label"    => "First name",
                "required" => true
            ])
            ->add("lastName", TextType::class, [
                "label"    => "Last name",
                "required" => true
            ]);

        // Add Event Listeners
        $builder->addEventListener(FormEvents::PRE_SET_DATA, [$this, "onPreSetData"]);
        $builder->addEventListener(FormEvents::PRE_SUBMIT, [$this, "onPreSubmit"]);
    }

    public function onPreSetData(FormEvent $event) {
        $event->getForm()
            ->add("emailGroups", TextareaType::class, [
                "label"    => "Access to mailing groups (please write out the groups to which access is to be assigned)",
                "required" => false
            ]);
    }

    public function onPreSubmit(FormEvent $event) {
        $formData = $event->getData();
        $formData["emailGroups"] = "example@example.com";

        $event->setData($formData);
    }
```

And controller:

```(php)
if ($request->isMethod("POST")) {
    $currentForm->handleRequest($request);

        if ($currentForm->isSubmitted()) {
            s($request->request->all()); die();
        }
}
```

I get the value entered in the form and not changed in the onPreSubmit function. I'm not sure if this is a bug or should it be, but is there a way to do it?

**Comment by xabbuh** [comment]
A form event listener does not change the data inside the `Request` object, but only modifies the request data inside the form submission cycle. That's why you do not see any side effect inside your controller when dumping `$request->request->all()`.
