### ISSUE TITLE
Various Workflow classes are declared final without any apparent reason.

### ISSUE THREAD

**Issue by efthymiou** [symfony/symfony#36358]
**Symfony version(s) affected**: 5.0.7

**Description**  

Various classes in symfony/workflow are decleared final, preventing extension. For example I cannot extend `Symfony\Component\Workflow\MarkingStore\MethodMarkingStore` to account for 0 values which are valid in my case.

**How to reproduce**  

Try extending Symfony\Component\Workflow\MarkingStore\MethodMarkingStore

**Possible Solution**  

Remove final declaration from class.

**Additional context**

**Comment by lmasforne** [comment]
Hello @efthymiou , 
Can you explain more with objects exemples in what case you dont need to define values in this class ?
Thanks

**Comment by efthymiou** [comment]
```php
class Value {
    /** @var int this may be 0 */
   protected $marking;
  
   // …
}
```

Now the provided MethodMarkingStore  has the following check in the ```getMarking()``` method

```php
    public function getMarking(object $subject): Marking
    {
        // …
        if (!$marking) {
            return new Marking();
        }
```

That does not work in my case since 0, which is a valid value in my case, evaluates to false.

What is the rationale behind the `MethodMarkingStore` class being final? Why is it prohibited to extend it?

The `InMemoryMetadataStore` class is also declared as final. Why?

**Comment by nicolas-grekas** [comment]
Final classes help maintainance without removing any possibilities from users, usually. We need to first confirm your case cannot be addressed in any other way than inheritance before taking the hassle of increased maintenance overhead.

**Comment by efthymiou** [comment]
Well I obviously can copy'n'paste the provided code and change the getMarking function accordingly.

**Comment by Devristo** [comment]
Wouldn't a custom marking store suffice in this case?

```
framework:
    workflows:
        my_workflow:
            marking_store:
                service: 'App\Service\MyMarkingStore'
```

**Comment by efthymiou** [comment]
I do not use the yaml configuration, but yes as I said, I can make a custom MarkinStore by copy'n'pasting the code in MethodMarkingStore into MyMarkingStore

**Comment by lyrixx** [comment]
Hello. I open 2 PRs in order to fix the following statement: 

> That does not work in my case since 0, which is a valid value in my case, evaluates to false.

Using numeric for place name seems a bit odd to me. May I ask you why you prefer numeric over string with meanings?


> The `InMemoryMetadataStore` class is also declared as final. Why?

What is your issue with this class?

**Comment by efthymiou** [comment]
> Hello. I open 2 PRs in order to fix the following statement:
> 
> > That does not work in my case since 0, which is a valid value in my case, evaluates to false.
> 
> Using numeric for place name seems a bit odd to me. May I ask you why you prefer numeric over string with meanings?

I am converting a legacy system, where states are numeric constants. For the time being, converting the state type is not possible. While not the best choice IMO, numeric constants for status are not unusual.

> > The `InMemoryMetadataStore` class is also declared as final. Why?
> 
> What is your issue with this class?

It is also final. It does not seem sensible to me, as it is not in any way an internal class. I have to copy'n'paste the whole class, if I want to modify its behavior.

**Comment by ro0NL** [comment]
how would you hook-in using extending? the answer should be applicable to decorating as well :)

**Comment by efthymiou** [comment]
Well you obviously follow some doctrine with final classes. I drop my case since I am neither a maintainer nor a contributor of this package.

**Comment by VaN-dev** [comment]
@lyrixx GuardEvent is also defined as final, which prevent from mocking it and unit-test the guard listeners receiving the event as argument. How are we supposed to unit test our guard listeners ? maybe you could provide a `GuardEventInterface` setting contract for `isBlocked`, `setBlocked`, `getTransitionBlockerList` and `addTransitionBlocker` methods ? so we could just mock the interface instead of the impl.

If this proposal is fine for you, i'd be happy to make a PR with that interface.

**Comment by lyrixx** [comment]
Hello,
Sure, you can unit test all listeners. 
To do so, you don't need a mock, use the real object directly. It's much simpler :)
