### ISSUE TITLE
Symfony 4.4 receives an XML request whose text node contains more than 10 MB, the module "BoDyListerner.php" causes an exception with the message "Invalid xml message received".

### ISSUE THREAD

**Issue by athanaselos** [symfony/symfony#36360]
Hi,
**Symfony 4.4**, we receive an XML query whose text node contains more than **10 MB**, the module "**BoDyListerner.php**" causes an exception with the message "**Invalid xml message received**". This is due to the absence of the "**LIBXML_PARSEHUGE**" option at the constructor level of the class "**Symfony\Component\Serializer\Encoder\XmlEncod**e".

How can this option be provided by configuration?

Apr 3 09:04:45 intgxn01 xnetusp[13524]: 14510136 e0ca54a2fae495a348f1c45d1e635336 0 "anonymous" "OTHER-0" FR Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid xml message received" at /var/www/xnet/Release_4.23/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115

**Comment by athanaselos** [comment]
Hi,
**Symfony 4.4**, we receive an XML query whose text node contains more than **10 MB**, the module "**BoDyListerner.php**" causes an exception with the message "Invalid xml message received". This is due to the absence of the "**LIBXML_PARSEHUGE**" option at the constructor level of the class "Symfony\Component\Serializer\Encoder\XmlEncode". How can this option be provided by configuration?

Apr  3 09:04:45 sacdintgxn01 xnetusp[13524]: 14510136 e0ca54a2fae495a348f1c45d1e635336 0 "anonymous" "OTHER-0" FR  Unca 
ught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid xml message received" at /var/www/xnet/Release_4.23/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115

**Comment by dmaicher** [comment]
> friendsofsymfony/rest-bundle/EventListener/BodyListener.php line 115

so this issue is related to https://github.com/FriendsOfSymfony/FOSRestBundle, right?

**Comment by athanaselos** [comment]
Hi,

We do not use Fos_rest Serializer, but Symfony's serializer and we want 
to provide an options to XmlEncoder classe.

Best regards,

JRA

Le 06/04/2020 à 16:39, David Maicher a écrit :

**Comment by xabbuh** [comment]
Well, but the stack trace points to the `BodyListener` class from FOSRestBundle. Can you provide a small example application that allows to reproduce?

**Comment by athanaselos** [comment]
Hi,

I solved the problem by replacing the Fos XML decoder with our own, a 
copy of their module, but we add the additional parameter 
"LIBXML_PARSEHUGE" to handle nodes greater than 10 MB, at the 
constructor level.

> classXmlDecoder implementsDecoderInterface
> {
> private$_encoder;
> /**
> * Constructeur de la classe de décodage XML
> */
> publicfunction__construct()
> {
> $this->_encoder =newXmlEncoder(
> 'response',
> LIBXML_NONET|LIBXML_NOBLANKS|LIBXML_PARSEHUGE
> );
> syslog(LOG_NOTICE, "{XmlDecoder}::_constructor - Ok");
> }
> /**
> * {@inheritdoc}
> *
> * @parammixed$data Données XML
> *
> * @returnvoid
> */
> publicfunctiondecode($data)
> {
> try{
> return$this->_encoder->decode($data, 'xml');
> } catch(UnexpectedValueException $e) {
> return;
> }
> }
> }
Best regards.


Le 17/04/2020 à 14:24, Christian Flothmann a écrit :

**Comment by xabbuh** [comment]
Thank you for the feedback. Let's close then.
