### ISSUE TITLE
[String] Slugger should only replace special characters for the English locale

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#36383]
**Symfony version(s) affected**: 5.0+

**Description**  
The Slugger provided by String replaces `&` by `and` and `@` by `at`. This is only correct for English, but it looks like it's doing it unconditionally. See https://github.com/symfony/symfony/blob/168574db2961ad693dec6ed3fe09b4278c2bcc55/src/Symfony/Component/String/Slugger/AsciiSlugger.php#L100-L101

**Possible solution** 
Do this replacement only for English. If it's not possible to detect the locale, then it's preferable to not do the replacement.

**Additional context**  
This was originally reported in [this comment](https://symfony.com/blog/new-in-symfony-5-1-string-improvements#comment-23933) of the Symfony blog.

**Comment by fancyweb** [comment]
Shouldn't we have an `EnglishAsciiSlugger` then and have that kind of replacements inside this class? For example, it would be interesting to replace `&` with `et` in French, but we're not going to handle all languages with a big if I guess?

**Comment by fancyweb** [comment]
I looked at this again and I realized we can't have a dedicated class for one language since we can pass the locale to the slug method. Therefore, AsciiSlugger must be able to handle all locales.

**Comment by nicolas-grekas** [comment]
Can't we pass a translator to the constructor?

**Comment by fancyweb** [comment]
> Can't we pass a translator to the constructor?

What is your idea?

I was thinking of adding something like this:

```php
private const REPLACEMENTS_MAPPING = [
    'en' => [
        '@' => 'at',
        '&' => 'and',
    ],
    'fr' => [
        '&' => 'et',
    ],
];

// ...

foreach (self::REPLACEMENTS_MAPPING[$shortLocale] ?? [] as $from => $to) {
    $slug = $slug->replace($from, $separator.$to.$separator);
}

**Comment by nicolas-grekas** [comment]
My idea is to let ppl be able to define these map on their own, adding locales if they want to, using regular translation maps, if that makes sense.

**Comment by lmasforne** [comment]
I had an option 'replace_chars'  where you can put your own chars replacement logic as @nicolas-grekas purpose, is for us the right approach ?
