### ISSUE TITLE
[Mime] Line endings not correct when using S/MIME and Linux

### ISSUE THREAD

**Issue by TokkCorp** [symfony/symfony#36398]
**Symfony version(s) affected**: 5.0+

**Description**  
When sending mails using the symfony mailer the line endings in the message to the mailserver are missing the carriage return if S/MIME encryption is used on a linux server. 

I've prepared four examples of what gets send to the mailserver: 

* [windows_unencrypted_mail.txt](https://github.com/symfony/symfony/files/4455138/windows_unencrypted_mail.txt) - A plaintext mail generated on a windows system. All line endings are \<CR\>\<LF\>
* [linux_unencrypted_mail.txt](https://github.com/symfony/symfony/files/4455136/linux_unencrypted_mail.txt) - A plaintext mail generated on a linux system. All line endings are \<CR\>\<LF\>
* [windows_encrypted_mail.txt](https://github.com/symfony/symfony/files/4455137/windows_encrypted_mail.txt)  - An encrypted mail generated on a windows system. All line endings are  still \<CR\>\<LF\>
* [linux_encrypted_mail.txt](https://github.com/symfony/symfony/files/4455135/linux_encrypted_mail.txt)  - An encrypted mail generated on linux. The line endings in the mail header are still \<CR\>\<LF\> but in the mail body the \<CR\> is missing, only the \<LF\> is present. 

Because of the wrong endings sending huge files leads to the following error:
`PHP Fatal error:  Uncaught Symfony\Component\Mailer\Exception\TransportException: Expected response code "250" but got code "501", with message "501 Syntax error - line too long". in /example/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:298`

**How to reproduce**  
The Problem will occur always when sending an S/MIME encrypted Mail like this:

````
$email = (new Email())
    ->from('sender@example.com')
    ->to('recipient@example.com')
    ->subject('Encrypted mail with attachment')
    ->attachFromPath('./attachments/LoremIpsum.pdf')
    ->text(fopen('./attachments/content.txt', 'r'))
    ->html(fopen('./attachments/content.html', 'r'));

$encrypter = new SMimeEncrypter('./cert/smime.cer');
$encryptedEmail = $encrypter->encrypt($email);
````

The wrong line endings are also present without an attachment but the server error will occure only if the message is long enough to exceed the maximal line length. 

**Possible Solution**  
Fix the line endings in S/MIME encrypted messages.

**Additional Information**
 It is working using Swiftmailer on the same systems so I would conclude  the error is in the mailer component and not in openssl or any other system.

**Comment by sstok** [comment]
https://github.com/openssl/openssl/blob/6d9b4d7f4bf1ea9bc1d1b1bd8b7e83c6fbeed395/crypto/asn1/asn_mime.c#L244 

```
if (flags & SMIME_CRLFEOL)
        mime_eol = "\r\n";
    else
        mime_eol = "\n";
```

But there is no way to use this constant directly in PHP (gotta love the OpenSSL extension).
I'm working on a pull request to normalize the line-ending to their correct format 👍

**Comment by sstok** [comment]
@TokkCorp can you try if #36463 fixes the problem?

**Comment by TokkCorp** [comment]
Just tried and can confirm that it is working with the change from this commit.
