### ISSUE TITLE
Soucis affichage formulaire Symfony 4

### ISSUE THREAD

**Issue by cassanogabriele** [symfony/symfony#36393]
J'ai ce soucis d'affichage de formulaire avec Symfony 4, ayant cherché longtemps et essayé toutes les solutions trouvées qui ne fonctionnent pas dans mon cas, je vous demande de l'aide :

Variable "form" does not exist.

Exception Stack Trace 

Twig\Error\ RuntimeError
in templates/job/registration.html.twig (line 6)

    {% extends "base.html.twig" %}
    {% block body %}
        <h1 class="my-4 animated swing">Publiez votre annonce</h1>    
        
        {{ form(form) }}
        
    {% endblock %}

in var/cache/dev/twig/e0/e050d65d099d0dd177f71deeac46d347501ea956ff75e6a050a667f6ebd64c1e.php->{closure} (line 69)
in vendor/twig/twig/src/Template.php->block_body (line 184)
in var/cache/dev/twig/52/52c3e3ee76acb9846c4b8ddde91798c6289998569e98610242c776f721825823.php->displayBlock (line 88)
in vendor/twig/twig/src/Template.php->doDisplay (line 379)
in vendor/twig/twig/src/Template.php->displayWithErrorHandling (line 356)
in var/cache/dev/twig/e0/e050d65d099d0dd177f71deeac46d347501ea956ff75e6a050a667f6ebd64c1e.php->display (line 46)
in vendor/twig/twig/src/Template.php->doDisplay (line 379)
in vendor/twig/twig/src/Template.php->displayWithErrorHandling (line 356)
in vendor/twig/twig/src/Template.php->display (line 364)
in vendor/twig/twig/src/TemplateWrapper.php->render (line 47)
in vendor/twig/twig/src/Environment.php->render (line 319)
in vendor/symfony/framework-bundle/Controller/ControllerTrait.php->render (line 229)
AbstractController->render('job/registration.html.twig', array('form_create_job' => object(FormView))) in src/Controller/JobController.php (line 40)
in vendor/symfony/http-kernel/HttpKernel.php->register (line 150)
in vendor/symfony/http-kernel/HttpKernel.php->handleRaw (line 67)
in vendor/symfony/http-kernel/Kernel.php->handle (line 198)
Kernel->handle(object(Request)) in public/index.php (line 25)

Mon code :

src/Form/JobformType.php (le formulaire créé avec la commande php bin/console make:form)

namespace App\Form;

use App\Entity\Job;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobformType extends AbstractType
{
   	public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type')
            ->add('company')
            ->add('logo')
            ->add('url')
            ->add('position')
            ->add('location')
            ->add('description')
            ->add('howToApply')
            ->add('token')
            ->add('isPublic')
            ->add('isActivated')
            ->add('email')
           /* ->add('expiresAt')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('category')*/
        ;
}

public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
       'data_class' => Job::class,
    ]);
}
}

src/Entity/Job.php (l'entité, déjà utilisé pour l'affichage des "jobs", la partie commentée pose un autre soucis mais n'est pas nécessaire pour le formulaire)

namespace App\Entity;

use App\Helper\SlugifyHelper;
use DateTime;
use Doctrine\Common\Persistence\Event\LifecycleEventArgs;

class Job
{
    // Durée de vie d'une offre en jours
	public const OFFER_LIFETIME = 30; // en jours

    /** @var int */
    private $id;

    /** @var Category */
    private $category;

    /** @var string */
    private $type;

    /** @var string */
    private $company;

    /** @var string */
    private $logo;

    /** @var string */
    private $url;

    /** @var string */
    private $position;

    /** @var string */
    private $location;

    /** @var string */
    private $description;

    /** @var string */
    private $howToApply;

    /** @var string */
    private $token;

    /** @var bool */
    private $isPublic;

    /** @var bool */
    private $isActivated;

    /** @var string */
    private $email;

    /** @var DateTime */
   // private $expiresAt;

    /** @var DateTime */
   // private $createdAt;

    /** @var DateTime */
   // private $updatedAt;

    /**
     * Get ID
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Get category
     *
     * @return Category
     */
    public function getCategory(): Category
    {
        return $this->category;
    }

    /**
     * Set category
     *
     * @param Category $category
     * @return Job
     */
    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Job
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get company slug
     *
     * @return string
     */
    public function getCompanySlug(): ?string
    {
        return SlugifyHelper::slugify($this->company);
    }

    /**
     * Get company
     *
     * @return string
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * Set company
     *
     * @param string $company
     * @return Job
     */
    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string
     */
    public function getLogo(): ?string
    {
        return $this->logo;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Job
     */
    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Job
     */
    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get position slug
     *
     * @return string
     */
    public function getPositionSlug(): ?string
    {
        return SlugifyHelper::slugify($this->position);
    }

    /**
     * Get position
     *
     * @return string
     */
    public function getPosition(): ?string
    {
        return $this->position;
    }

    /**
     * Set position
     *
     * @param string $position
     * @return Job
     */
    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get location slug
     *
     * @return string
     */
    public function getLocationSlug(): ?string
    {
        return SlugifyHelper::slugify($this->location);
    }

    /**
     * Get location
     *
     * @return string
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return Job
     */
    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Job
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get howToApply
     *
     * @return string
     */
    public function getHowToApply(): ?string
    {
        return $this->howToApply;
    }

    /**
     * Set howToApply
     *
     * @param string $howToApply
     * @return Job
     */
    public function setHowToApply(string $howToApply): self
    {
        $this->howToApply = $howToApply;

        return $this;
    }

    /**
     * Get token
     *
     * @return string
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Set token
     *
     * @param string $token
     * @return Job
     */
    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get isPublic
     *
     * @return bool
     */
    public function isPublic(): ?bool
    {
        return $this->isPublic;
    }

    /**
     * Set isPublic
     *
     * @param bool $isPublic
     * @return Job
     */
    public function setIsPublic(bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    /**
     * Get isActivated
     *
     * @return bool
     */
    public function isActivated(): ?bool
    {
        return $this->isActivated;
    }

    /**
     * Set isActivated
     *
     * @param bool $isActivated
     * @return Job
     */
    public function setIsActivated(bool $isActivated): self
    {
        $this->isActivated = $isActivated;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Job
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get expiresAt
     *
     * @return DateTime
     */
    /*public function getExpiresAt(): ?DateTime
    {
        return $this->expiresAt;
    }*/

    /**
     * Set expiresAt
     *
     * @param DateTime $expiresAt
     * @return Job
     */
   /* public function setExpiresAt(DateTime $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }*/

    /**
     * Get createdAt
     *
     * @return DateTime
     */
    /*public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }*/

    /**
     * Get updateAt
     *
     * @return DateTime
     */
   /* public function getUpdatedAt(): ?DateTime
    {
        return $this->updatedAt;
    }*/

    /**
     * Set expiresAt
     *
     * @param LifecycleEventArgs $event
     * @return Job
     */
   /* public function setExpiresAtValue(LifecycleEventArgs $event): self
    {
        // nous remplissons automatiquement la date d'expiration si cette dernière n'a pas été saisie
        // manuellement
        if (!$this->expiresAt) {
            $this->expiresAt = new DateTime('+'.self::OFFER_LIFETIME.' day');
        }

        return $this;
    }*/

    /**
     * Set createdAt
     *
     * @param LifecycleEventArgs $event
     * @return Job
     */
    /*public function setCreatedAtValue(LifecycleEventArgs $event): self
    {
        $this->createdAt = new DateTime();

        return $this;
    }*/

    /**
     * Set updatedAt
     *
     * @param LifecycleEventArgs $event
     * @return Job
     */
    /*public function setUpdatedAtValue(LifecycleEventArgs $event): self
    {
        $this->updatedAt = new DateTime();

        return $this;
    }*/
}

src/Controller/JobController.php

namespace App\Controller;
use App\Entity\Category;
use App\Entity\Job;
use App\Form\JobformType;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Request;

class JobController extends AbstractController
{
    public function index()
    {
		return $this->render('job/index.html.twig');	
    }
	
	public function home(){
		 return $this->render('job/home.html.twig');
	}
	
	public function profile(EntityManagerInterface $em){
		$jobs = $em->getRepository(Job::class)->findAll();

        return $this->render('job/profils.html.twig', [
            'jobs' => $jobs,
        ]);
	}	
	
	public function register(){
		$job = new Job();	
		
		$form = $this->createForm(JobformType::class, $job);
		
		// return $this->render('job/registration.html.twig');
		
		return $this->render('job/registration.html.twig', [
            'form_create_job' => $form->createView(),
        ]);
	}

	// https://www.youtube.com/watch?v=EiC_TGdMINc
	/*public function new(Request $request)
    {
        $jobcreate = new Jobcreate();	
		
		$form = $this->createForm(JobformType::class, $jobcreate);
	 
		return $this->render('job/registration.html.twig', [
            'form_create_job' => $form->createView(),
        ]);
    }*/
	
    public function show(EntityManagerInterface $em, int $id, string $company, string $location, string $position) : Response
    {
        // dans un projet réel, il sera nécessaire de faire une requête permettant de vérifier que tous les éléments
        // correspondent à une offre d'emploi valide
        $job = $em->getRepository(Job::class)->find($id);
		
        if (null === $job) {
            throw new NotFoundHttpException();
        }

        $currentDate = new DateTime();		
      
        return $this->render('job/show.html.twig', [
            'job' => $job,
        ]);
    }
}

templates/job/registration.html.twig (template twig d'affichage du formulaire)

{% extends "base.html.twig" %}

{% block body %}
<h1 class="my-4 animated swing">Publiez votre annonce</h1>	
	
{{ form(form) }}
	
{% endblock %}

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions about using Symfony please use any StackOverflow.

Thanks!
