### ISSUE TITLE
Soucis de route pour simple Module Drupal 8

### ISSUE THREAD

**Issue by cassanogabriele** [symfony/symfony#36394]
J'ai créé un simple module drupal 8, à partir de ce tuto :  https://www.youtube.com/watch?v=mHTuXXfBs7Y,  dans : modules/custom/drupalup_controller(nom du module créé), il annonce qu'il ne trouve pas la page quand je tente de l'afficher : 

url_de_mon_site/drupalup/articles

ERREUR :  
Page non trouvée
La page demandée n'a pas pu être trouvée.

Après avoir pas mal cherché, et essayé toute les solutions trouvées, je n'ai toujours pas compris pourquoi, et les solutions ne fonctionnent pas dans mon cas. J'ai besoin d'aide...

Voici le code : 

modules/custom/drupalup_controller/drupalup_controller.info.yml

name: Drupal Up Controller with template
type: module
description: C'est mon premier module Drupal 8.
package: Example Modules
version: 1.0
core: 8.x

modules/custom/drupalup_controller/drupalup_controller.module

function hook_theme($existing, $type, $path){
    return array(
        'article_list' => array(           
            'variables' => array('items' => array(), 'tite' = > '')
        )
    );
}

modules/custom/drupalup_controller/drupalup_controller_routing.yml

drupalup_controller.article_list:
  path: '/drupalup/articles'
  defaults:
    _controller: '\Drupal\drupalup_controller\Controller\ArticleController::page'
    _title: 'Our custom Article list'
  requirements:
    _permission: 'access content'

modules/custom/drupalup_controller/src/Controller/ArticleController.php

namespace Drupal\drupalup_controller\Controller;

class ArticleController extends ControllerBase {  
    public function page() {
		$items = array{
			array('name' => 'Article one'),
			array('name' => 'Article two'),
			array('name' => 'Article three'),
			array('name' => 'Article one'),
			array('name' => 'Article four'),
		};
		
        return array(
            '#theme' => 'article_list',
            '#items' => $items,
			'#title' => 'Our article list'
        );
    }

}

modules/custom/drupalup_controller/templates/article-list.html.twig

<h4>{{ title }}</h4>
<ul>
{% for article in items %}
	<li>{{ article.title }}</li>
{% endfor %}
</ul>

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions about using Symfony please use any StackOverflow.

Thanks!
