### ISSUE TITLE
MicroKernelTrait guesses incorrect project directory if trait used in abstraction

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony#36404]
**Symfony version(s) affected**: master

When using the `MicroKernelTrait` in a abstract kernel class, then extending the abstraction class in a different directory; `%kernel.project_dir%` is guess/defined incorrectly.

i.e.

```
// /root/project/

tests/Fixtures/AbstractKernel.php (uses the MicroKernelTrait)
tests/Functional/TestKernel.php (extends AbstractKernel)

%kernel.project_dir% = /root/project/project/test/Functional
```

An working example can be found here https://github.com/jrushlow/reset-password-bundle/runs/574232421

Discovered in https://github.com/SymfonyCasts/reset-password-bundle/pull/96

**Comment by ro0NL** [comment]
that's the intended feature of MicroKernelTrait AFAIK. shouldnt you override AbstractKernel::getProjectDir instead?

**Comment by stof** [comment]
if you want the project dir to be guessed based on the AbstractClass, you should indeed override the method yourselves.
Guessing based on the actual kernel class is the expected behavior in Symfony.
