### ISSUE TITLE
[PHPUnit-Bridge] Use COMPOSER_BINARY if available

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#36401]
This long blob can be replaced by `getenv('COMPOSER_BINARY')` when run within a composer script, which is not always of course, so the blob has to stay I guess, but if COMPOSER_BINARY is present it'd be nice to use it as that will be guaranteed correct. I just had a case where I had a composer.phar lying around in the current dir and it caused me some problems as it wasn't the composer I wanted to use.

https://github.com/symfony/symfony/blob/168574db2961ad693dec6ed3fe09b4278c2bcc55/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L146-L151

**Comment by nicolas-grekas** [comment]
Would anyone like to give this a try? Could target branch 3.4 as a bug fix to me.
