### ISSUE TITLE
Error when trying to enable the profiler conditionally

### ISSUE THREAD

**Issue by COil** [symfony/symfony#36414]
**Symfony version(s) affected**: 5.0.7
**PHP**: 7.4.4

**Description**  
I am following https://symfony.com/doc/current/profiler.html#enabling-the-profiler-conditionally. Its works with the dev and debug env but not on the prod envronment.

**How to reproduce**  

I have created a repo : https://github.com/COil/symfony-issue36414

Access "/" and switch from dev to prod env. 

    // services.yml
    services:
        Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

Ok in dev. In prod I am the following message :

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "profiler".

**Possible Solution**  

I found a workaround by using a named parameters : 

    services:
        _defaults:
            bind:
                $profiler: '@?profiler'

**Additional context**  

With this it works in both env : 

```
    /**
     * @Route("/phpinfo", name="phpinfo")
     */
    public function phpInfoAction(Request $r, ?Profiler $profiler): Response
    {
        if ($profiler !== null) {
            $profiler->disable();
        }
```

I tried to use the same syntax for the alias, but it doesn't work:

    // services.yml
    services:
        Symfony\Component\HttpKernel\Profiler\Profiler: '?@profiler'

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: A service definition must be an array or a string starting with "@" but "string" found for service "Symfony\Component\HttpKernel\Profiler\Profiler"

It you need more info, don't hesitate to ping me.

**Comment by ro0NL** [comment]
DId you enable the bundle for the prod environment?

By default it's not: https://github.com/symfony/recipes/blob/2de05e19f916c8841102f2a35f0dc08dbac219ed/symfony/web-profiler-bundle/3.3/manifest.json#L3

**Comment by stof** [comment]
Well, given that the Profiler service does not exist in prod, I think the solution for it to work out of the box is to make the method argument optional, so that the argument resolver accepts not seeing it: `?Profiler $profiler = null`

**Comment by COil** [comment]
Hi, tested with ```?Profiler $profiler = null ``` but same result. Here is the repo to reproduce: https://github.com/COil/symfony-issue36414

**Comment by ro0NL** [comment]
i figured we dont support optional service aliases :) i suggest a compiler pass, or propose the alias in core.

**Comment by COil** [comment]
Hi @ro0NL , thanks to take time on this issue. So, it's more a documentation issue? 

I was surprised that this syntax works for named parameters:

    $profiler: '@?profiler'

So, may it's the way to go in this case? As it will work in both dev and prod environment.

**Comment by ro0NL** [comment]
> So, it's more a documentation issue

IMHO yes. The doc example as-is wont work in prod as you've figured out.

There's a distinction between "optional injection" vs. "optional definition". So an optional named binding (`$profiler: '@?profiler'`) makes more sense than a optional alias/service definition.


> So, may it's the way to go in this case

I guess :) it will work per-file though, hence a compiler class may suit better, as it's global.

**Comment by COil** [comment]
Hi @javiereguiluz , should I create an issue on the doc tracker?

**Comment by nicolas-grekas** [comment]
Closing as this has been solved and the bahavior explained.
