### ISSUE TITLE
IIS and PHP 7.4 cause "Bad file descriptor" notice

### ISSUE THREAD

**Issue by no-one** [symfony/symfony#36413]
**Symfony version(s) affected**: 4.4.7

**Description**  
In the mentioned constellation (IIS + PHP 7.4) Symfony generates a "Bad file descriptor" notice. This is also documented here: https://bugs.php.net/bug.php?id=79166 and is created in the Logger.php in line 82.
Even though this was already mentioned on bugs.php.net, I wanted to report it here as well, because Symfony is currently not usable with this webserver and PHP 7.4.

**How to reproduce**  
Run Symfony 4.4 with IIS and PHP 7.4 with APP_ENV=dev

**Comment by xabbuh** [comment]
Can you confirm that #36434 will fix this?

**Comment by no-one** [comment]
> 
> 
> Can you confirm that #36434 will fix this?

Yes, that's how I fixed it locally for me. I was just unsure if that was also "officially" the right solution. Thanks @xabbuh
