### ISSUE TITLE
[Form] RepeatedType with not mapped fields allows to have different values

### ISSUE THREAD

**Issue by biozshock** [symfony/symfony#36410]
**Symfony version(s) affected**: 3.4

**Description**  
If one (or both) fields in RepeatedType is not mapped the form allows to have different values

**How to reproduce**  
Add to `Tests/Extension/Core/Type/RepeatedTypeTest.php`
```php
public function testSubmitUnequalNotMapped(): void
{
    $input = ['first' => 'foo', 'second' => 'bar'];

    $form = $this->factory->create(static::TESTED_TYPE, null, [
        'type' => TextTypeTest::TESTED_TYPE,
        'first_options' => ['mapped' => false],
        'second_options' => ['mapped' => false],
    ]);

    $form->submit($input);

    $this->assertSame('foo', $form['first']->getViewData());
    $this->assertSame('bar', $form['second']->getViewData());
    $this->assertFalse($form->isSynchronized());
    $this->assertSame($input, $form->getViewData());
    $this->assertNull($form->getData());
}
```

Happens because `\Symfony\Component\Form\Extension\Core\DataTransformer\ValueToDuplicatesTransformer` is called with `value === null` on unmapped field.

**Comment by HeahDude** [comment]
Hello @biozshock, thank you for opening this issue with a reproducer.

May I ask what is the use case that requires to not map repeated inner fields?

**Comment by biozshock** [comment]
@HeahDude I have reused one of application types that has defaults set as not mapped. 

I wouldn't say that this is the bug in the symfony itself, but it would be helpful to have an exception or other error of some sort, just to save time for the developer in case they use not mapped repeated fields.
Maybe some validation in `configureOptions` is the right place, but I'm not sure if that one can catch that inner fields have default not mapped or not.

**Comment by HeahDude** [comment]
We agree this is not a bug, as this is the expected behavior and inner fields should always be mapped. But adding some kind of validation to it can be complex.

So to resume IIUC, your case is something like:
```php
$builder
    ->add('email', RepeatedType::class, [
        'type' => CustomEmailType::class,
    ])
;
```
where `CustomEmailType` has a default `mapped=false` option, so you need to do:
```php
$builder
    ->add('email', RepeatedType::class, [
        'type' => CustomEmailType::class,
        'first_options' => ['mapped' => true],
        'second_options' => ['mapped' => true],
    ])
;
```
in order to have it working properly, is that right?

**Comment by biozshock** [comment]
Yes, that's how i solved this 15 minutes ago. Came here to write the workaround.

But i would say that setting `mapped=true` for both fields as values you can not override would be a perfect solution.
