### ISSUE TITLE
[Security] TokenInterface::getUser()method makes a lot of request

### ISSUE THREAD

**Issue by pesseyjulien** [symfony/symfony#36416]
Hi,

I'm using Api Platform with Symfony v4.4 and Lexik JWTAuthenticationBundle. 

When using the TokenInterface::getUser() method, not only it fetch my logged in user but it also makes a bunch of requests which I don't really want :

![Capture d’écran 2020-04-10 à 20 25 06](https://user-images.githubusercontent.com/10850944/79013597-6b49c280-7b69-11ea-89dd-821d14e846f4.jpg)

Any idea how to change this behaviour ?

Thanks in advance for your help !

**Comment by stof** [comment]
Well, that's about what you do in your authentication later. These are not queries done by Symfony itself.

**Comment by wouterj** [comment]
What probably happends here is that you are using a lazy firewall. This means that Symfony doesn't authenticate the current request, unless you fetch the user (e.g. to check if they have enough permissions, or to fetch the user from the token like you're doing now).

Instead of doing this at the start of the request, lazy firewalls do this at the first `getUser()` call. Use `anonymous: null` instead of `anonymous: lazy` if you want to disable this behavior (but please note that this means these queries are done at the start of every request).

**Comment by pesseyjulien** [comment]
> Well, that's about what you do in your authentication later. These are not queries done by Symfony itself.

I do not have an AuthenticationSuccessListener. Could it be from the jwt bundle or the fosuser bundle ?



> What probably happens here is that you are using a lazy firewall. This means that Symfony doesn't authenticate the current request, unless you fetch the user (e.g. to check if they have enough permissions, or to fetch the user from the token like you're doing now).
> 
> Instead of doing this at the start of the request, lazy firewalls do this at the first `getUser()` call. Use `anonymous: null` instead of `anonymous: lazy` if you want to disable this behavior (but please note that this means these queries are done at the start of every request).

I have tried the following for my firewall config, but no change, still making the additional queries :/

```
        api:
            pattern:   ^/
            stateless: true
            anonymous: null
            provider: db_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

I think the 'issue' might be coming from the 'lexik_jwt_authentication.jwt_token_authenticator'

**Comment by pesseyjulien** [comment]
If I follow this : https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md

I have then 0 doctrine query (as expected by the feature), so might be the jwt bundle which is causing issue ?

**Comment by pesseyjulien** [comment]
Solved this by not extending the FOS\UserBundle\Model\User class but implementing the FOS\UserBundle\Model\UserInterface directly instead. 

Don't really know why extending the FOS user class would make extra queries..

**Comment by pesseyjulien** [comment]
The issue comes from the lastLoginListener : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/EventListener/LastLoginListener.php

**Comment by wouterj** [comment]
Good to hear you managed to find the problem! If I'm correct, there is nothing to do for Symfony Core here? If so, can you please close? Thanks for sharing all your findings and debugging this!

**Comment by pesseyjulien** [comment]
Yep, nothing to do with Symfony indeed, it's all on fosuserbundle side. I'm removing it. Thanks for the help !
