### ISSUE TITLE
ReflectionExtractor does not extract from property with declared type (PHP 7.4)

### ISSUE THREAD

**Issue by pszalko** [symfony/symfony#36425]
**Symfony version(s) affected**: symfony/property-info v5.0.7 (probably all versions) with PHP 7.4

**Description**  
`ReflectionExtractor` does not extract property type from properties with declared type.

**How to reproduce**  
```
class ProjectCreateRequest
{
    public ProjectModel $project;
}

$expectedType = $extractor->getTypes(ProjectCreateRequest::class, 'project');
```

Current implementation:
* `$expectedType` is `null`

Expected implementation:
* `$expectedType` refers to the class `ProjectModel` as type for property `project`.
* declared type takes precedence before mutators, accessors or constructor

**Comment by cv65kr** [comment]
That was fixed in https://github.com/symfony/symfony/pull/34557
All previous versions will be have this problem.
