### ISSUE TITLE
JsonResponse::create() should be compatible with Response::create()

### ISSUE THREAD

**Issue by galo4kin** [symfony/symfony#36421]
**Symfony version(s) affected**: master, v5.0.7
**PHP version(s)**: 7.3.16-1

**Description**  
\Symfony\Component\HttpFoundation\JsonResponse::create() should be compatible with \Symfony\Component\HttpFoundation\Response::create()

**Possible Solution**  
Change first param type hint to `?string ${string_name}` for:
```
\Symfony\Component\HttpFoundation\BinaryFileResponse::create
\Symfony\Component\HttpFoundation\JsonResponse::create
\Symfony\Component\HttpFoundation\RedirectResponse::create
\Symfony\Component\HttpFoundation\StreamedResponse::create
```

**Additional context**  
From
![image](https://user-images.githubusercontent.com/1070532/79039083-77746500-7be7-11ea-9442-4d7f1ac5dcb0.png)
To
![image](https://user-images.githubusercontent.com/1070532/79039096-8fe47f80-7be7-11ea-9f20-6e8f9e23324e.png)

**Comment by nicolas-grekas** [comment]
LSP is not really applicable to static factory methods, so this doesn't apply here. Thanks for reporting.

**Comment by nicolas-grekas** [comment]
Oh, btw, remving a type hint in a child class is LSP-legal - but need PHP 7.2 to work effectively.

**Comment by mwolff-fn** [comment]
This is still an issue with PHP >= 7.4.8 and HttpFoundation 5.1.8 - what do you mean by "it needs PHP 7.2 to work effectively"?

**Comment by derrabus** [comment]
> This is still an issue

@mwolff-fn This ticket has been closed because the issue described here is not a bug. Can you elaborate, how this issue impacts you?

**Comment by mwolff-fn** [comment]
> > This is still an issue
> 
> @mwolff-fn This ticket has been closed because the issue described here is not a bug. Can you elaborate, how this issue impacts you?

Sorry, I got the error report from a colleague and did not check the environment myself before posting - turns out, the server throwing the error had an outdated PHP version running. So nothing to see here, move along, everything is working just fine :-)
