### ISSUE TITLE
[HttpClient] Can't get content of a 404 response

### ISSUE THREAD

**Issue by COil** [symfony/symfony#36435]
**Symfony version(s) affected**: 5.0.7
**PHP version**: 7.4

**Description**  

Can't get the content of a 404 response.

**How to reproduce**  

```
        try {
            $this->httpClient->request('GET', 'https://www.strangebuzz.com/index.php/');
        } catch (ClientException $e) {
            $response = $e->getResponse();
            $this->assertSame(Response::HTTP_NOT_FOUND, $response->getStatusCode());
            //$this->assertStringContainsStringIgnoringCase('perdus', $response->getContent()); // exception is thrown again
        }
```

I can't test that the content contains a string because `$response->getContent()` will re throw an exception.

**Possible Solution**  

Don't re throw the exception.

**Additional context**  

This code is ran in a functional test extending `WebTestCase`.

**Comment by nicolas-grekas** [comment]
Did you try passing false as argument?

**Comment by COil** [comment]
Oops, sorry. Didn't saw the argument.
