### ISSUE TITLE
[Form] implemention of isModied () method

### ISSUE THREAD

**Issue by E2-08** [symfony/symfony#36442]
This method will allow you to check that the form has been modified when updating the data

so we can have something like this:

 if ($form->isSubmitted() && $form->isValid()) {

    if($form->isModfield()) {
        // ... perform some action, such as saving data to the database.
        return $this->redirectToRoute('formModufied_success');
    }

 }

**Comment by fabpot** [comment]
This has been suggested a few times already and rejected. Have a look at past issues and PRs for more details.
