### ISSUE TITLE
Form field setRendered throwing exceptions

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#36448]
**Symfony version(s) affected**: 5.0.7 (not sure when that change was introduced though)

**Description**  
Previously you could do something like this:
``` 
{{ form_start(form) }}
{% do form.FIELD.setRendered %}
<!-- Custom render of FIELD -->
{{ form_widget(form) }}
{{ form_end(form) }}
```

But now it seems to throw this: 
`An exception has been thrown during the rendering of a template ("Field "FIELD" has already been rendered, save the result of previous render call to a variable and output that instead.").`

Is this behaviour intended? Cause that makes it a BIG pain to render complex custom form elements using Angular/React/What ever.

**How to reproduce**  
Set a form field rendered
render form as shown above

**Possible Solution**  
One possible solution would be to return to the old behaviour of the form accepting that the element has been rendered.
If that change was intended to break this kind of usage maybe a different flag that tells it that we intend to render it manually.

**Comment by fancyweb** [comment]
AFAIK, that is still supposed to work because we don't try to render an already rendered child. Which form theme are you using? Can you try with the `form_div_layout` one (ie without any override by your custom theme)? Can you share a full reproducer? Thanks.

**Comment by KDederichs** [comment]
I myself don't touch the theme, it's in the Easy admin bundle that I get that problem with.
Here's a minimal reproducer though:
https://github.com/KDederichs/setRenderReproducer

Just start the project go to the admin with /admin and try to edit or create an entity

**Comment by KDederichs** [comment]
ok nvm, seems like it's related to the easy admin bundle and it just worked before?
I assume you guys did add some sort of check/change that broke it

**Comment by fancyweb** [comment]
@KDederichs Could you please close the issue as the problem was in EasyAdmin?

**Comment by lfjeff** [comment]
I had a similar problem with some of my Twig templates and was able to fix it by getting rid of the `setRendered` calls and replacing them with this:
```
{{ form_widget(form._token) }}{# needed if you're using CSRF #}
{{ form_end(form, {'render_rest' : false}) }}
```

**Comment by TomasVotruba** [comment]
I'm facing the same error. 

Not sure where the problem is yet, but the error trigger was added in Symfony 5.0:
https://github.com/symfony/form/commit/1faaa90c5b5f51222429c891889100045413f2a6
