### ISSUE TITLE
How to set mariadb

### ISSUE THREAD

**Issue by xorgxx** [symfony/symfony#36444]
SF 5.0.5 php 7.3.11 mariadb-10.3.21
HI i have trouble, juste not possible to connect to the database BY SYMFONY only, all "client" navicat, phpstorm acces wihtout any probleme !!!

in my env : 
```
DATABASE_URL=mysql://root:</98C3la>B<O3s6@localhost:3307/op5.dev?serverversion=mariadb-10.3.21
```

i have try most all .
Thanks!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by xorgxx** [comment]
well it since that it's he bug !!! i just have change ONLY the PWS to 123456789 and it since to work perfect !!

but you can see that the pws 123456789 is to match secure ;-) agains </98C3la>B<O3s6

thanks enyway for you help.
