### ISSUE TITLE
Impossible to access an attribute () on a double variable ("00.00").

### ISSUE THREAD

**Issue by rogergerecke** [symfony/symfony#36452]
**Symfony version(s) affected**: 5.0.7
```
"require": {
    "php": "^7.2.5",
    "ext-ctype": "*",
    "ext-iconv": "*",
    "sensio/framework-extra-bundle": "^5.1",
    "symfony/apache-pack": "^1.0",
    "symfony/asset": "5.0.*",
    "symfony/console": "5.0.*",
    "symfony/dotenv": "5.0.*",
    "symfony/expression-language": "5.0.*",
    "symfony/flex": "^1.3.1",
    "symfony/form": "5.0.*",
    "symfony/framework-bundle": "5.0.*",
    "symfony/http-client": "5.0.*",
    "symfony/intl": "5.0.*",
    "symfony/mailer": "5.0.*",
    "symfony/monolog-bundle": "^3.1",
    "symfony/notifier": "5.0.*",
    "symfony/orm-pack": "*",
    "symfony/process": "5.0.*",
    "symfony/security-bundle": "5.0.*",
    "symfony/serializer-pack": "*",
    "symfony/string": "5.0.*",
    "symfony/swiftmailer-bundle": "^3.4",
    "symfony/translation": "5.0.*",
    "symfony/twig-pack": "*",
    "symfony/validator": "5.0.*",
    "symfony/web-link": "5.0.*",
    "symfony/webpack-encore-bundle": "^1.7",
    "symfony/yaml": "5.0.*",
    "ext-json": "*"
  },
```
**Description**  
I want to access a usually variable from database. But Twig acknowledges this with the error:
Impossible to access an attribute ("lat") on a double variable ("49.12").

**How to reproduce**  
Entity:
```
@ORM\Column(type="json", nullable=true)  
private $weather_data = [];
```

In my config:
```
config\packages\twig.yaml
openweather: '@App\Service\OpenWeatherService'
```

In my Service:
```
public function _getWeatherArray()
    {
        $output = null;

        $weather = $this->repository->findOneBy(['data_type' => $this->type]);
        if ($weather->getImportStatusCode() == 200) {

            $output = [
                'status' => 200,
                'weather' => $weather->getWeatherData()
            ];

            return $output;
        }

        return ['status' => false];
    }
```

In my twig template:
```
{% for item in openweather._getWeatherArray.weather %}
{{ item.lat }}
{% endfor %}
```

**Possible Solution**  
I do not know

**Comment by AhmedRaafat14** [comment]
Based on the description you wrote that means the `$output` variable looks like that:
```
[
   'status' => 200,
   'weather' => "49.12" # not a JSON just a float variable
 ];
```
And this makes sense to show this error you see because of course there is not `lat` defined on the number `49.12` right!
Can you try in your twig to just print the item `{{ item }}` and also are you sure your output looks like this:
```
[
   "status" => 200,
   "weather" => {'lat': 7377464, lang: 99373637, ....}
]
```
try to log it and see as well?

**Comment by rogergerecke** [comment]
**Database Shema:**

![open_weather](https://user-images.githubusercontent.com/25885048/79375930-b2fd8f00-7f59-11ea-8c3e-cb2384dcb6b1.png)


**Data is json:**

![opneweather](https://user-images.githubusercontent.com/25885048/79377367-dc1f1f00-7f5b-11ea-9923-b4147aa0950b.png)




**print_r($weather->getWeatherData()) in my class OpenWeatherService show:**

`Array ( [lat] => 49.12 [lon] => 10.7 [daily] => Array ( [0] => Array ( [dt] => 1586689200 [uvi] => 4.58 [rain] => 2.79 [temp] => Array ( [day] => 294.41 [eve] => 287.2 [max] => 294.41`



**In Twig template:**

{% for item in openweather._getWeatherArray.weather %}
{{ item.lat }}
{% endfor %}


**Symfony shows me the correct value in the error message. I do not understand where there is a mistake.**

![sym-error](https://user-images.githubusercontent.com/25885048/79377993-d83fcc80-7f5c-11ea-8871-4463fbc3fa98.png)

**Comment by AhmedRaafat14** [comment]
Hmm okay will try this out and see why it happens if it needs a fix will open a PR or will let you know how to fix it 👍

**Comment by rogergerecke** [comment]
i got it i am a idiot

**Comment by rogergerecke** [comment]
dump(item)
show my

```
49.12
10.7
array:8 [▼
  0 => array:14 [▼
    "dt" => 1586689200
    "uvi" => 4.58
    "rain" => 2.79
    "temp" => array:6 [▶]
    "clouds" => 20
    "sunset" => 1586714658
    "sunrise" => 1586665862
    "weather" => array:1 [▶]
    "humidity" => 32
    "pressure" => 1015
    "wind_deg" => 192
    "dew_point" => 277.07
    "feels_like" => array:4 [▶]
    "wind_speed" => 1.44
  ]
```
