### ISSUE TITLE
Testings Types from the Service Container doesn't find dependencies

### ISSUE THREAD

**Issue by rgrassian** [symfony/symfony#36462]
**Symfony version(s) affected**: 4.4.7

**Description**  
In my case I can't test a type with a dependency, I get the following error :
```
ArgumentCountError: Too few arguments to function Symfony\Bridge\Doctrine\Form\Type\DoctrineType::__construct()
```

**How to reproduce**  
```
class ContractCommercialGestureNewTypeTest extends TypeTestCase
{
    /**
     * @var CommercialGestureRepository|MockObject
     */
    protected $commercialGestureRepository;

    /**
     * @return void
     */
    protected function setUp(): void
    {
        $this->commercialGestureRepository = $this->createMock(CommercialGestureRepository::class);

        parent::setUp();
    }

    /**
     * @return void
     */
    public function testSubmitForm(): void
    {
        $contractCommercialGestureToCompare = new ContractCommercialGesture();
        $form = $this->factory->create(ContractCommercialGestureNewType::class, $contractCommercialGestureToCompare);
    }

    /**
     * @return array<FormExtensionInterface>
     */
    protected function getExtensions(): array
    {
        $type = new ContractCommercialGestureNewType($this->commercialGestureRepository);

        return [
            new PreloadedExtension([$type], []),
        ];
    }
}
```

**Possible Solution**  

**Additional context**  
The construct of my type :
```
    public function __construct(CommercialGestureRepository $commercialGestureRepository)
    {
        $this->commercialGestureRepository = $commercialGestureRepository;
    }
```
The link of the documentation :
https://symfony.com/doc/current/form/unit_testing.html#testings-types-from-the-service-container

**Comment by stof** [comment]
Well, you will need to register the DoctrineExtension in your TypeTestCase if you rely on the Doctrine types in the form you test.
The TypeTestCase is not using the container (it does not even boot the kernel and does not even require having a kernel) to register form types.

**Comment by rgrassian** [comment]
Thank you, how would you do this ? And should it be added to the documentation ?

**Comment by wouterj** [comment]
See the next chapter in the docs you linked: https://symfony.com/doc/current/form/unit_testing.html#adding-custom-extensions

**Comment by VincentLanglet** [comment]
> See the next chapter in the docs you linked: https://symfony.com/doc/current/form/unit_testing.html#adding-custom-extensions

IMHO, this is not clear enough.

First, without documentation, I don't think everybody will know that the DoctrineOrmExtension is required for a form with a EntityType. 

Then, the extension is not easy to use. You have to write 
```
protected function getExtensions(): array
    {
        return [
            new DoctrineOrmExtension($registry),
        ];
    }
```
But you need a $registry !

If we go deep in some tests written by Symfony, we can find a way to get a $registry:
```
$entityManager = DoctrineTestHelper::createTestEntityManager();
$registry = $this->createMock(ManagerRegistry::class);

$registry->method('getManager')->willReturn($entityManager);
$registry->method('getManagerForClass')->willReturn($entityManager);

return $registry;
```
This can also be found in [StackOverflow](https://stackoverflow.com/questions/49874598/how-to-unit-test-symfony-4-form-with-entitytype-field/49879186#49879186)

But this only works with `EntityRepository`, not `ServiceEntityRepository` !
With a `ServiceEntityRepository`, you receive the following error message
```
TypeError: Argument 1 passed to FooRepository::__construct() must implement interface Doctrine\Persistence\ManagerRegistry, instance of Doctrine\ORM\EntityManager given
```
This error can be found on [StackOverflow](https://stackoverflow.com/questions/59715497/typetestcase-with-entitytype-and-serviceentityrepository)  without any resolution.

Maybe I missed an easy solution but in my case, I only made it work with:
```
$factory = new TestRepositoryFactory();
$configuration->setRepositoryFactory($factory);
$entityManager = DoctrineTestHelper::createTestEntityManager($configuration);

$repository = $this->createMock(EntityRepository::class);
$repository->method('createQueryBuilder')->willReturn($this->createMock(QueryBuilder::class));
$factory->setRepository($entityManager, Foo::class, $repository);
```
Which is far from being easy.

**Comment by HeahDude** [comment]
Hello @VincentLanglet, I agree we need a doc update, I have opened symfony/symfony-docs#13552.

The `KernelTestCase` (instead of the `TypeTestCase`) should be your way to go in this case, using the "real" form factory.

I think we should close here though as there is nothing we can do about it in core.

**Comment by VincentLanglet** [comment]
> The `KernelTestCase` (instead of the `TypeTestCase`) should be your way to go in this case, using the "real" form factory.

Indeed, the kernel would be useful.
But the TypeTestCase would still be necessary if I want to add form extensions and stuff, isn't it ? 
Should the `TypeTestCase` extend the `KernelTestCase` then ?

**Comment by HeahDude** [comment]
>But the TypeTestCase would still be necessary if I want to add form extensions and stuff, isn't it ?
Should the TypeTestCase extend the KernelTestCase then ?

Both should not be related. The `KernelTestCase` is using the "real" container (based on `test` env config though) so you don't have to do anything more since the form factory will be loaded as a service and will register everything just like when your application is handling a request.

**Comment by nicolas-grekas** [comment]
Closing as that's related to the doc and this staled here.
