### ISSUE TITLE
[Mailer] Attaching instead of embedding

### ISSUE THREAD

**Issue by alex8444** [symfony/symfony#36478]
When using the email.image method in Twig, or embedFromPath method on a TemplatedEmail, the file is attached to the email instead of being just embedded.

![image](https://user-images.githubusercontent.com/34007058/79582873-a8173b80-80cc-11ea-85e9-cffd7c9d2601.png)

It happens on symfony/mailer 5.0.7

**Comment by xabbuh** [comment]
Can you please share some example code that allows to reproduce your issue?

**Comment by fabpot** [comment]
Closing as there is no feedback. Feel free to reopen with some code that allows us to reproduce the issue. Thank you.
