### ISSUE TITLE
[Mercure] [Notifier] Add Mercure integration

### ISSUE THREAD

**Issue by GaryPEGEOT** [symfony/symfony#36481]
Would be nice to have a Mercure integration on Notifier component to send "real time" notifications on SPA's !

I can give it a try, unless @dunglas is working on it?

**Comment by dunglas** [comment]
I tried but Mercure alone is not enough. It's just a transport (such as WebSocket). It doesn't tell anything about how to represent the notification (it can be any format of any shape...). Maybe could we use LDN for the payload itself? https://www.w3.org/TR/ldn/

What do you think @fabpot?

**Comment by fabpot** [comment]
I have no ideas to be honest. I'm going to close and if one wants to open a PR? they are more than welcome.
