### ISSUE TITLE
Duplicate uploadIniSizeError if entity form is nested in the form of another entity

### ISSUE THREAD

**Issue by thibaut-decherit** [symfony/symfony#36503]
**Symfony version(s) affected**: 4.4.7

**Description**  
Error based on php.ini `upload_max_filesize` is thrown two time if the file entity form is nested in the form of another entity (e.g. a `Company` and a `Logo` entities) AND the file entity itself has a `File` or `Image` constraint.

**Steps to reproduce**
You can download the "bug reproducer" here: https://github.com/thibaut-decherit/nested-file-entity-bug

Make sure you have `upload_max_filesize = 2M` in your `php.ini`.

Go to `localhost:8000/new` and submit an image larger than 2Mo.
Two errors should appear instead of one.

**Assumption**
It's like the file size is validated prior to `@Assert\Image()` in `src/Entity/Logo.php` (maybe by the form itself or indirectly through a caught exception?) then a second time by `@Assert\Image()`, this time properly overwritten by `maxSize="2M"` (note the `[...] size is 2 MB` instead of `[...] size is 2 MiB`):
![](https://raw.githubusercontent.com/thibaut-decherit/nested-file-entity-bug/master/docs/1.png)

Note that if you remove `@Assert\Valid()` from `src/Entity/Company.php` only the first error is thrown:
![](https://raw.githubusercontent.com/thibaut-decherit/nested-file-entity-bug/master/docs/2.png)
(but `@Assert\Image()` is ignored so it is not a solution, you can confirm this by trying to submit a file other than jpeg, you will not get an error)

**Comment by xabbuh** [comment]
Could it be the same issue as #32045?

**Comment by thibaut-decherit** [comment]
Thank you for your feedback!

Yes and no.
 #32045 seems to occur on any form with a file upload exceeding `upload_max_filesize` from `php.ini`, "my" bug only occurs if the FormType owning the file input is **nested** in another form.

I have not encountered this issue with nonnested forms. Furthermore, in my case all errors are properly translated.

**Comment by lmasforne** [comment]
As i see there two messages because you got one message with the `FileType` constraint of the `Form` component and one with the ''File" constraint of the `Validator` component. I supposed when the same constraint is lauched, it could be merged in one same constraint ? I try to use xdebug your code when i post the file but it's extremly slow, what class is supposed to merge two constraint of different components ?

**Comment by thibaut-decherit** [comment]
> I supposed when the same constraint is lauched, it could be merged in one same constraint ?
I believe it is the expected behaviour, it does seem to work like that if the FormType with a file input is not nested in another FormType.

**Comment by xabbuh** [comment]
Can you please check if #39119 fixes this?
