### ISSUE TITLE
Custom Error Page Not Show in Production

### ISSUE THREAD

**Issue by broko-de** [symfony/symfony#36508]
Hello community, I tell you I have a project in symfony 3.4, create the custom error pages in the app / Resources / TwigBundle / view / Exception / error.html.twig directory but I can't get them to be displayed in production.
I followed the steps given at https://symfony.com/doc/3.4/controller/error_pages.html but I had no results.
Could you help me? Am I forgetting some other settings?
Thank you very much and sorry for my English.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
