### ISSUE TITLE
Filesystem remove() does not clear include cache

### ISSUE THREAD

**Issue by flack** [symfony/symfony#36532]
**Symfony version(s) affected**: 5.0.7

**Description**  
If you delete a file that has been loaded with `include` earlier in the same request, then it can later be included again, even though it doesn't exist any more

**How to reproduce**  

- create a file called `test.php` with the following content:
```php
<?php return 'hello';
```
- create a file called `bug.php` in the same folder with the following content:
```php
var_dump(include 'test.php');
$fs = new Symfony\Component\Filesystem\Filesystem();
$fs->remove('test.php');
var_dump(file_exists('test.php'));
var_dump(include 'test.php');
```

- open `bug.php` in a browser

***Expected output:***
```
string 'hello'
boolean false
Warning: include(): Failed opening 'test.php' 
```
***Actual output:***
```
string 'hello'
boolean false
string 'hello'
```

**Possible Solution**  
When I add a call to `opcache_reset();` it works as expected

**Additional context**  
At least on macOS where I tested the issue persists for a couple of seconds, so if you refresh the page really quickly after the initial load, it will reoccur (until the opcache expires I guess?)

**Comment by flack** [comment]
P.S.: Just noticed that the `opcache_reset();` workaorund is only effective for the second request, i.e. the first time you access `bug.php`, you get the wrong output, when you reload, you imediately get the correct output (as opposed to before, where it would take about 3 seconds).

**Comment by nicolas-grekas** [comment]
That's normal php behavior, it can be controlled by php.ini settings:
https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.revalidate-freq

**Comment by fabpot** [comment]
Closing then.
