### ISSUE TITLE
Web Profiler Memory usage in MB instead of MiB

### ISSUE THREAD

**Issue by Lozik** [symfony/symfony#36533]
**Symfony version(s) affected**: 4.4.5

**Description**  

In the Symfony Web Profiler, the peak memory usage is given in `MB`. However, if I understand the code correctly, the calculations are such that the memory usage is actually given in `MiB`. The label `MB` would thus be wrong.

**How to reproduce**  

Add, into controller:
```twig
dump(memory_get_peak_usage(true));
```
Then, open web profiler and check for peak memory usage. If one converts the dumped value into MB, it is not the same value as the one in the profiler tab `Performance`.

My values:
Dumped values: `4194304B` = `4.19MB` = `4MiB`
Peak memory, as in the `Performance`-Tab: `4.00MB` = `3.81MiB`

**Possible Solution**  

IMHO, only the label `MB` has to be changed into `MiB`.

**Additional context**  

I can offer my help to submit a pull request, if this gets confirmed, as it's only 2 small changes.

**Comment by fancyweb** [comment]
Status: reviewed

I think you are right because that's what we already do in Console Helper::formatMemory(). Can you send a PR that change the labels to MiB?

**Comment by Lozik** [comment]
Yes, I'm on it.

**Comment by Lozik** [comment]
I submitted the PR #36571 based on 3.4. However, one file has been changed since (starting at 4.3) and completely rewritten (`Resources/views/Collector/time.html.twig`). Should I add an additional PR for the changes of only the part that has changed in 4.3 or redo a PR with all the changes necessary for 4.3 to be correct?

**Comment by wouterj** [comment]
I think the best idea is to wait for your first PR to be merged. You can mention in your PR that this file is completely changed in 4.3, so mergers can take that into account when merging the branches up. I think they'll fix this when merging up and otherwise, you can submit a new PR afterwards :) (please note that 4.3 is no longer maintained).

**Comment by Lozik** [comment]
Okay, I got it, thank you! :)
