### ISSUE TITLE
[MakerBundle] Offer new Option

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#36537]
**Description**  
When you have symfony project with custom architecture you lost a part of powerfull maker bundle because directory isn't at the same place.

Actually i create a wrapper to do that [TwcMakerBundle](https://github.com/thewalkingcoder/maker-bundle) but may be is interesting to introduce this feature directly.

Before work to PR, do you think the idea/feature can help, or is out of context ?

@weaverryan WDYT ?

**Comment by fabpot** [comment]
You should probably create an issue on the maker bundle repo instead. Thank you.
