### ISSUE TITLE
Dynamic Form Modification - Works in 'new' but not in 'edit'

### ISSUE THREAD

**Issue by rwkt** [symfony/symfony#36542]
**Symfony version(s) affected**: 4, 5

**Description**  
I have followed the doc here: https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms

This works fine for 'new', but when the same form is used in 'edit', the POST event triggered by the category select field results in the error below.

**How to reproduce**  
Demo app code is available here: https://github.com/rwkt/demo-dynamicform

**Stack tace**  

> Symfony\Component\PropertyAccess\Exception\InvalidArgumentException:
> Expected argument of type "string", "null" given at property path "title".
> 
>   at C:\GitHub\demo-dynamicform\vendor\symfony\property-access\PropertyAccessor.php:198
>   at Symfony\Component\PropertyAccess\PropertyAccessor::throwInvalidArgumentException('string', array(array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\property-access\\PropertyAccessor.php', 'line' => 548, 'function' => 'setTitle', 'class' => 'App\\Entity\\Post', 'type' => '->', 'args' => array(null)), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\property-access\\PropertyAccessor.php', 'line' => 114, 'function' => 'writeProperty', 'class' => 'Symfony\\Component\\PropertyAccess\\PropertyAccessor', 'type' => '->', 'args' => array(array(object(Post)), 'title', null)), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\form\\Extension\\Core\\DataMapper\\PropertyPathMapper.php', 'line' => 86, 'function' => 'setValue', 'class' => 'Symfony\\Component\\PropertyAccess\\PropertyAccessor', 'type' => '->', 'args' => array(object(Post), object(PropertyPath), null)), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\form\\Form.php', 'line' => 631, 'function' => 'mapFormsToData', 'class' => 'Symfony\\Component\\Form\\Extension\\Core\\DataMapper\\PropertyPathMapper', 'type' => '->', 'args' => array(object(RecursiveIteratorIterator), object(Post))), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler.php', 'line' => 109, 'function' => 'submit', 'class' => 'Symfony\\Component\\Form\\Form', 'type' => '->', 'args' => array(array(), true)), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\form\\Form.php', 'line' => 492, 'function' => 'handleRequest', 'class' => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler', 'type' => '->', 'args' => array(object(Form), object(Request))), array('file' => 'C:\\GitHub\\demo-dynamicform\\src\\Controller\\PostController.php', 'line' => 74, 'function' => 'handleRequest', 'class' => 'Symfony\\Component\\Form\\Form', 'type' => '->', 'args' => array(object(Request))), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\http-kernel\\HttpKernel.php', 'line' => 157, 'function' => 'edit', 'class' => 'App\\Controller\\PostController', 'type' => '->', 'args' => array(object(Request), object(Post))), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\http-kernel\\HttpKernel.php', 'line' => 79, 'function' => 'handleRaw', 'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel', 'type' => '->', 'args' => array(object(Request), 1)), array('file' => 'C:\\GitHub\\demo-dynamicform\\vendor\\symfony\\http-kernel\\Kernel.php', 'line' => 191, 'function' => 'handle', 'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel', 'type' => '->', 'args' => array(object(Request), 1, true)), array('file' => 'C:\\GitHub\\demo-dynamicform\\public\\index.php', 'line' => 25, 'function' => 'handle', 'class' => 'Symfony\\Component\\HttpKernel\\Kernel', 'type' => '->', 'args' => array(object(Request)))), 0, 'title')
>      (C:\GitHub\demo-dynamicform\vendor\symfony\property-access\PropertyAccessor.php:118)
>   at Symfony\Component\PropertyAccess\PropertyAccessor->setValue(object(Post), object(PropertyPath), null)
>      (C:\GitHub\demo-dynamicform\vendor\symfony\form\Extension\Core\DataMapper\PropertyPathMapper.php:86)
>   at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(object(RecursiveIteratorIterator), object(Post))
>      (C:\GitHub\demo-dynamicform\vendor\symfony\form\Form.php:631)
>   at Symfony\Component\Form\Form->submit(array(), true)
>      (C:\GitHub\demo-dynamicform\vendor\symfony\form\Extension\HttpFoundation\HttpFoundationRequestHandler.php:109)
>   at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(Request))
>      (C:\GitHub\demo-dynamicform\vendor\symfony\form\Form.php:492)
>   at Symfony\Component\Form\Form->handleRequest(object(Request))
>      (C:\GitHub\demo-dynamicform\src\Controller\PostController.php:74)
>   at App\Controller\PostController->edit(object(Request), object(Post))
>      (C:\GitHub\demo-dynamicform\vendor\symfony\http-kernel\HttpKernel.php:157)
>   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
>      (C:\GitHub\demo-dynamicform\vendor\symfony\http-kernel\HttpKernel.php:79)
>   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
>      (C:\GitHub\demo-dynamicform\vendor\symfony\http-kernel\Kernel.php:191)
>   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
>      (C:\GitHub\demo-dynamicform\public\index.php:25)

**Comment by rwkt** [comment]
One workaround I have found is to replace the following:-

> var data = {};
> data[$category.attr('name')] = $category.val();

with this instead:-

> var data = $form.serializeArray();

However, it doesn't work correctly since (in **Edit**) the following statement executes and returns a redirect (where-as in New, it doesn't execute the statement at all).

> if ($form->isSubmitted() && $form->isValid()) { ... }

I'm alittle lost as to why the same thing is treated differently ...

**Comment by xabbuh** [comment]
Looking at the stack trace the issue is that the submitted form tries to map `null` to the `$title` attribute of your `Post` object which doesn't work as `setTitle()` doesn't allow `null`. This looks expected to me.

**Comment by rwkt** [comment]
Thanks for your reply.

> Looking at the stack trace the issue is that the submitted form tries to map `null` to the `$title` attribute of your `Post` object which doesn't work as `setTitle()` doesn't allow `null`. This looks expected to me.
That's what's confusing me - since the `$title` in the `Post` object isn't `null` in the Controller. If i were to do `dd($post->getTitle())` in `edit` then it would show the title (not null) in the js POST request.

If I were to do the following in the js, it would pass the `title` and it won't result in the null error anymore. I don't understand why required fields need to be passed for `edit` but not for `new`; plus the $post object already has a title.
```
var $postTitle = $('#post_title');
data[$postTitle.attr('name')] = $postTitle.val();
```

**Comment by xabbuh** [comment]
You have to pass all the data and not only the changed bits. The form would not know if you only omitted some fields because they didn't change or if data should be set to `null` (there is a second argument for the `submit()` method which can be used to change this behaviour though). So to me it seems that this is not a bug but a misunderstanding of what is happening. So I am going to close here. Thank you for understanding. If you still need help with your implementation I suggest to seek for assistance on the Symfony Slack.
