### ISSUE TITLE
Misleading exception message when injecting `ContainerInterface` into a service without implementing the `ServiceSubscriberInterface`

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#36563]
**Symfony version(s) affected**: 4.4.7

**Description**  
When you're having a service that receives a `ContainerInterface` but forgot to implement the `ServiceSubscriberInterface`, you'll get an exception message saying:

„The "App\MyService" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.”

**How to reproduce**  

```php
<?php declare(strict_types=1);

namespace App\AwesomeThings;

use App\MyService;
use Psr\Container\ContainerInterface;

class AwesomeService
{
    private ContainerInterface $container;

    public function __construct (ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function doSomething () : void
    {
        // The exception happens here!
        //    - „The "App\MyService" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.”
        $myService = $this->container->get(MyService::class);
        // …
    }

    /**
     * @inheritdoc
     */
    public static function getSubscribedServices () : array
    {
        return [
            MyService::class,
        ];
    }
}

class MyService {}
```

To fix the actual underlying exception here, we simply have to implement the forgotten `ServiceSubscriberInterface`:

```php
<?php declare(strict_types=1);

namespace App\AwesomeThings;

use App\MyService;
use Psr\Container\ContainerInterface;

class AwesomeService implements ServiceSubscriberInterface
{
    private ContainerInterface $container;

    public function __construct (ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function doSomething () : void
    {
        $myService = $this->container->get(MyService::class);
        // …
    }

    /**
     * @inheritdoc
     */
    public static function getSubscribedServices () : array
    {
        return [
            MyService::class,
        ];
    }
}

class MyService {}
```

**Possible Solution**  
Make the exception more context-sensitive/clear to this actual use-case

**Comment by nicolas-grekas** [comment]
This will be fixed by #35879
I'm not sure we can do better for now.

**Comment by Nyholm** [comment]
I agree that the exception message is not tailor made for your specific scenario. 

The message is however correct. You are trying to get a service from a container but the service has been removed. 

Using `ServiceSubscriberInterface` is also an advanced thing and something that rarely should be used (unless you are really really sure). That is why I don't think it should be mentioned in the exception message. 

I vote for closing this issue.

**Comment by xabbuh** [comment]
I agree with @Nyholm. So I am going to close here.
