### ISSUE TITLE
Process Component add support for option "create_new_console"

### ISSUE THREAD

**Issue by andrei0x309** [symfony/symfony#36583]
**Description**  
I saw that PHP has added in version 7.4.4 the option "create_new_console" for the function _proc-open.php_ (https://www.php.net/manual/en/function.proc-open.php),  "create_new_console" can totally change the behavior of  _proc-open.php_ on windows so it may be important for some users.

This is the description of the option:

>  create_new_console (windows only): the new process has a new console, instead of inheriting its parent's console

From what I've seen The symfony Process component doesn't support this option. 
And I think it can be implemented very easily.

In fact I think Process::start should have an additional parameter [] in order to pass (other_options) to proc-open.

**Comment by nicolas-grekas** [comment]
What is the use case for this function? Do you have one?
Please submit a PR if you think this should be implemneted.
