### ISSUE TITLE
Request sort by distance

### ISSUE THREAD

**Issue by dd2424** [symfony/symfony#36588]
Hello,

I have a form that only includes an Address field, in summary, the site geolocates using this address and displays the articles but without sorting distance!

Here is my request in my repo:
```
    /**
     * @return Query
     */
    public function findAllVisibleQuery(AdSearch $search): Query
    {
        $query = $this->findVisibleQuery();
 
        if ($search->getLat() && $search->getLng() && $search->getDistance()) {
            $query = $query
                ->select('a')
                ->andWhere('(6353 * 2 * ASIN(SQRT( POWER(SIN((a.lat - :lat) *  pi()/180 / 2), 2) +COS(a.lat * pi()/180) * COS(:lat * pi()/180) * POWER(SIN((a.lng - :lng) * pi()/180 / 2), 2) ))) <= :distance')
                ->setParameter('lng', $search->getLng())
                ->setParameter('lat', $search->getLat())
                ->setParameter('distance', $search->getDistance());
        }
 
    private function findVisibleQuery(): QueryBuilder
    {
        return $this->createQueryBuilder('a')
            ->where('a.publishedAt != false');
    }
```

**The query works fine** but when I add:
`->orderBy('a.distance', 'ASC')`

I have the error message:

> [Semantical Error] line 0, col 253 near 'distance ASC': Error: Class App\Entity\Ad has no field or association named distance

How to do ? Thank you.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
