### ISSUE TITLE
form option 'empty_data' is not working

### ISSUE THREAD

**Issue by kricha** [symfony/symfony#36593]
**Symfony version(s) affected**: 5.0.7

**Description**  

form option 'empty_data' is not working (text, choice types...)

**How to reproduce**  

clone and run '/' on https://github.com/kricha/symfony-empty-data

**Additional context**  

In example repo introduced only text type, but with choice type, number type, integer type - same situation.

**Comment by xabbuh** [comment]
Can you explain what happens and what you did expect to happen instead?

**Comment by kricha** [comment]
@xabbuh sorry, my fault, i thought it also affects render result.
