### ISSUE TITLE
Does ValidatorException shouldn't extends LogicException instead of RuntimeException ?

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#36597]
**Description**  

When doing,
```
new CustomConstraint([...])
```
`InvalidOptionsException`, `MissingOptionsException` and `ConstraintDefinitionException` can be thrown.

I'm using a static-analysis tool which is checking that I try/catch every `RuntimeException` (or adding a `@throws`tag to the phpDoc of my function). It ignores `LogicException` because they are `developer logic exception` which should never happen or be fixed in dev environment.

I feel like most of the `ValidatorException` are in the second case. I don't think it's expected to write: 
```
try {
    $constraint = new CustomConstraint([...])
} catch (...) {
     ...
}
```
This kind of exceptions should directly lead to a fix in the code.

Am I wrong ?

**Comment by Nyholm** [comment]
That is an excellent observation. 

However, ValidationException can happen because of user input. It is not necessarily because a programming issue. 

Im closing this PR since it will also be a massive BC break if we change it. =)

**Comment by VincentLanglet** [comment]
> That is an excellent observation.
> 
> However, ValidationException can happen because of user input. It is not necessarily because a programming issue.
> 
> Im closing this issue since it will also be a massive BC break if we change it. =)

Yes, I wasn't really expecting a change because of the BC-break.

BTW, the fact every Symfony exception are extending a custom exception/implementing a custom interface is really nice since it allows me to configure my static analysis tool to ignore them.
