### ISSUE TITLE
I am not able to install Composer

### ISSUE THREAD

**Issue by VeeRHunter** [symfony/symfony#36602]
Once I type this command "sudo composer install", I am getting this error.

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

[RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command:

 PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "EasyAdminBundle" from namespace "EasyCorp\Bundle\EasyAdminBundle".

Composer version is 1.10.5.
Symfony is 3.4.

Please help me

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
