### ISSUE TITLE
composer install --no-dev --optimize-autoloader return class not found.

### ISSUE THREAD

**Issue by Guervyl** [symfony/symfony#36604]
**Symfony version(s) affected**: 5.0

**Description**  
I am following this guide: https://symfony.com/doc/current/deployment.html#common-post-deployment-tasks.

I'm on a linux system. Centos 7.

I uploaded my source code on the server. I installed the dependencies on the server. I ran `composer dump-env prod`. I ran `composer require symfony/dotenv`. I set `APP_ENV=prod` in the `.env`. *Note I don't have `.env.local` but `.env.local.php`*. I ran `export APP_ENV=prod` then `export SYMFONY_ENV=prod`. And finally `composer install --no-dev --optimize-autoloader`.

The output of composer is:

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 23 removals
  - Removing zendframework/zend-eventmanager (3.2.1)
  - Removing zendframework/zend-code (3.4.1)
  - Removing symfony/stopwatch (v5.0.7)
  - Removing symfony/orm-pack (v1.0.8)
  - Removing symfony/maker-bundle (v1.15.0)
  - Removing symfony/doctrine-bridge (v5.0.7)
  - Removing ocramius/proxy-manager (2.2.3)
  - Removing ocramius/package-versions (1.5.1)
  - Removing nikic/php-parser (v4.3.0)
  - Removing jdorn/sql-formatter (v1.2.17)
  - Removing doctrine/reflection (1.2.1)
  - Removing doctrine/persistence (1.3.7)
  - Removing doctrine/orm (v2.7.2)
  - Removing doctrine/migrations (2.2.1)
  - Removing doctrine/instantiator (1.3.0)
  - Removing doctrine/inflector (1.3.1)
  - Removing doctrine/event-manager (1.1.0)
  - Removing doctrine/doctrine-migrations-bundle (2.1.2)
  - Removing doctrine/doctrine-bundle (2.0.7)
  - Removing doctrine/dbal (v2.10.1)
  - Removing doctrine/common (2.12.0)
  - Removing doctrine/collections (1.6.4)
  - Removing doctrine/cache (1.10.0)
Generating optimized autoload files
ocramius/package-versions: Package not found (probably scheduled for removal); generation of version class skipped.
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Error: Class 'Doctrine\Bundle\DoctrineBundle\DoctrineBundle' not found in /home/trantkwr/public_html/src/Kernel.php:23
!!  Stack trace:
!!  #0 /home/trantkwr/public_html/vendor/symfony/http-kernel/Kernel.php(369): App\Kernel->registerBundles()
!!  #1 /home/trantkwr/public_html/vendor/symfony/http-kernel/Kernel.php(123): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /home/trantkwr/public_html/vendor/symfony/framework-bundle/Console/Application.php(169): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /home/trantkwr/public_html/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /home/trantkwr/public_html/vendor/symfony/console/Application.php(140): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /home/trantkwr/public_html/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Compo in /home/trantkwr/public_html/src/Kernel.php on line 23
!!
Script @auto-scripts was called via post-install-cmd

**Comment by xabbuh** [comment]
Can you share your `composer.json` file?

**Comment by xabbuh** [comment]
Well, your kernel still tries to load the DoctrineBundle (for example in `config/bundles.php`) while you didn't list the `doctrine/doctrine-bundle` package in your `composer.json` file.

**Comment by Guervyl** [comment]
I didn't do anything. It's just a Symfony project from `composer create-project`. And I installed the Doctrine bundle running 
`composer require symfony/orm-pack
 composer require --dev symfony/maker-bundle`  And the project is running fine in Dev and also running fine in APP_ENV=prod.

How can I fix it?

**Comment by xabbuh** [comment]
Looks like somehow the ORM pack was removed. Does running `composer require symfony/orm-pack` again help?

**Comment by Guervyl** [comment]
> composer require symfony/orm-pack

I don't know why it was removed from the `composer.json`. But after running `composer require symfony/orm-pack` It just put it back:

composer require symfony/orm-pack
Using version ^1.0 for symfony/orm-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Nothing to install or update
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
45 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Then ` composer install --no-dev --optimize-autoloader` works fine:

 composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 2 removals
  - Removing symfony/maker-bundle (v1.15.0)
  - Removing nikic/php-parser (v4.3.0)
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
44 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Thanks for your support :)

**Comment by xabbuh** [comment]
Without actually knowing what output your received before or what might have happened additionally that's indeed hard to say. :) But I am glad that you manage to resolve your issue.

**Comment by ghost** [comment]
Hello, 

In short if you have issue of missing package / (class not found) after running the above command -> the solution is just add that package to section "require" (this is production sections) or run "composer require symfony/yourmissingpackageorclass" that will fix it.

A late one, but thank you for sharing. I found out that when going into production, there are some packages you have to move from dev to prod for example: 

in your composer.json

 "require": { package-from-dev:version, package2:version, package3:version}
"require-dev": { package2:version, package3:version}

![image](https://github.com/symfony/symfony/assets/4603672/47d5cde6-2d52-4afa-adfb-7972713476fd)

this post helps me.
