### ISSUE TITLE
[Security] Rename VerifyAuthenticatorCredentialsEvent

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#36608]
Reported by @javiereguiluz on Slack:

> `VerifyAuthenticatorCredentialsEvent` looks awfully long ... can it be renamed as `VerifyCredentialsEvent`?

I think we can - and should. At first, we put the word "authenticator" in any class we made to distinguish between "old" and "new" security classes. However, the final PR introduced many classes without "authenticator" and `VerifyCredentialsEvent` is not similar to any existing class.

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
LGTM, shorter is always better. What about `CheckCredentialsEvent`?

**Comment by wouterj** [comment]
> What about `CheckCredentialsEvent`?

👍 That seems to fit better with current Symfony terminology (e.g. the `checkCredentials()` Guard method).
