### ISSUE TITLE
Fatal error: Interface 'Symfony\Contracts\Service\ResetInterface' not found in vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcherInterface.php on line 23

### ISSUE THREAD

**Issue by emulgeator** [symfony/symfony#36618]
**Symfony version(s) affected**:
            "name": "symfony/event-dispatcher",
            "version": "v4.4.8",

**Description**  
`codeception/codeception` version `2.5.6` is requiring `symfony/event-dispatcher` version constraint `>=2.7 <5.0`

The mentioned Interface is in `symfony/service-contracts` and as I see `symfony/event-dispatcher` only requires that package for `dev`

**How to reproduce**  
Just install the NOT dev requirements of `symfony/event-dispatcher` .

**Possible Solution**  
Add the `symfony/service-contracts` as a NON dev requirement

**Comment by nicolas-grekas** [comment]
`TraceableEventDispatcherInterface` is an optional feature of the component.
Our policy is to *not* force-require dependencies of optional features.
Requiring `symfony/service-contracts` explicitly is the way to go.
We could make this more explicit as proposed in https://github.com/symfony/symfony/pull/37512

Please send a PR doing so if you can.

**Comment by emulgeator** [comment]
@nicolas-grekas So you say that I should report this issue to CodeCeption as it depends on a so called "optional feature" and they should add your requirements in their composer.json?

**Comment by nicolas-grekas** [comment]
If codeception uses TraceableEventDispatcher, definitely yes.
