### ISSUE TITLE
[Messenger] Redis Transport removes message from stream on rejection

### ISSUE THREAD

**Issue by Steveb-p** [symfony/symfony#36619]
**Symfony version(s) affected**: 5.0.7

**Description**  
Redis Messenger transport deletes messages when rejecting, causing other consumers / applications to be unable to reach that message.

This is specifically because of the line:
https://github.com/symfony/symfony/blob/3945a5c80e149168f405ea948def2542162a7d24/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L237
which causes messages to be removed from the stream, instead of being acknowledged only by a particular consumer group.

This affects primarily cases where Messenger component is used to read/write with other, third party applications.

**How to reproduce**  
1. Create two transports with different consumer groups.
2. Dispatch a message that cannot be handled properly, for example due to failing deserialization.
3. Start consuming from both transports. Only one of consumers will pick up this message.

**Possible Solution**  
Removing the delete command should suffice, but I'm not sure if it doesn't affect some other use cases.

**Additional context**

---

**Comment by Nyholm** [comment]
I think this is the intended behavior. Same for SQS: https://github.com/symfony/symfony/pull/32454#discussion_r370996345

But the message is going to the failure queue, right?

**Comment by Steveb-p** [comment]
The thing is @Nyholm, this practically makes this transport unusable in conjunction with third-party apps. And in this case, since the error occurs on deserialization (strictly, denormalization phase) it does not get sent to failure queue (message is assumed corrupted).

Streams in redis are supposed to be consumed by multiple consumer groups, which stands in opposition to SQS I believe (I'm unfamiliar with SQS). Deleting message from stream causes it to become unavailable to other consumer groups (which would be third-party apps, PHP or not) - it is strictly deleted from Redis. 
Simply acknowledging it on the other hand marks the message as processed (even if it was "rejected") and what will happen other apps might still pick that message up, since for them it might be valid.
At the same time, since that message was acknowledged in this consumer group, it will not be processed again by this group.

**Comment by Nyholm** [comment]
Hm. I know that other transports are deleting the message... I might be wrong. 
Let's ping @soyuka and @Tobion for their input.

**Comment by Tobion** [comment]
What's the equivalent of a redis consumer group in amqp?

**Comment by stof** [comment]
Well, in AMQP, if you want to have the equivalent, you would bind multiple queues bound on the same exchange (so that publishing a message in the exchange creates 2 separate messages in queues) and have each consumer group use its own queue.

**Comment by Tobion** [comment]
In amqp acknowledge/rejection only affects one queue. So the issue seems valid that in redis rejection should also be per consumer group.

**Comment by Steveb-p** [comment]
In current implementation there exists a property that controls what should happen to messages that are acknowledged in Redis transport:

https://github.com/symfony/symfony/blob/75e71e3bbefffe1e67d80e842d66721b98f6a531/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L35

Should PR assume that this property also works for deleting, or should it introduce another one?
