### ISSUE TITLE
[Form] DependencyInjectionExtension Type extension exception

### ISSUE THREAD

**Issue by 7ochem** [symfony/symfony#36610]
**Symfony version(s) affected**: 4.2.0 and above (currently up until 5.1)

**Description**  
The `getTypeExtensions($name)` method of \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension throws a strange exception message:

> The extended type specified for the service "0" does not match the actual extended type. Expected "Vendor\Bundle\AcmeBundle\Form\FooType", given "Vendor\Bundle\AcmeBundle\Form\BarType".

See the hightlighted code lines of the `getTypeExtensions()` method in the additional context below, the `$serviceId` variable contains the integer key of the items of the `$this->typeExtensionServices[$name]` iterable. Apparently, this has been set to an actual service ID by a service ID guesser before Symfony went full FQCN and now it just remains a numeric key. But the thrown exception message has not been adjusted to the new situation. This results is a very unclear error.

**How to reproduce**  
Have a Type extension's `getExtendedType`(`s`) return invalid type(s)

**Possible Solution**  
Clarify the exception message with useful data. Also the key in the loop is therefore probably no longer needed.

**Additional context**  
https://github.com/symfony/symfony/blob/4170346ea736d90de32384cf4fea45f2aa0f4d73/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php#L64-L78

**Comment by xabbuh** [comment]
I think #36613 will provide a more helpful message.
