### ISSUE TITLE
[Twig] Translations not substituting placeholders?

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#36620]
**Symfony version(s) affected**: 5.0.7, 5.0.8 (as I know of)

**Description**  
As far as I'm aware of (and as far as the documentation tells me) translating stuff like this should work in twig:
`    {{ 'translateme' | trans({'%username%': 'It worked'}, 'email', 'en') }}`
where this is the translation file:

```
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="en" datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
      <trans-unit id="Nnddh2u" resname="translateme">
        <source>translateme</source>
        <target>I should be translated and this should be substituted: %username%</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

Now I'm fairly certain this worked fine in earlier versions and substituted the placeholder but now it doesn't seem to do that anymore and I'm not exactly sure why it would not.

The translation itself loads fine but `%username%` is not getting replaced by `It worked`

**How to reproduce**  
Here's a minimal project that reproduces this behaviour:
https://github.com/KDederichs/translate_bug

just start a Webserver and go to the home page

**Comment by stof** [comment]
you created a file named `email+intl-icu.xliff`, so you should be using the ICU format for placeholders in it (that's what the `+intl-icu` in the name is about: opting in for the new format).

**Comment by KDederichs** [comment]
ah good to know, I did in-fact not create that file it was created by the `php bin/console translation:update --force en` command

**Comment by stof** [comment]
yeah, that command uses the new format by default, as that's the new recommendation (the ICU format supports more features).
