### ISSUE TITLE
[FrameworkBundle][RFC] Introduce a new RedirectException

### ISSUE THREAD

**Issue by pyrech** [symfony/symfony#36626]
**Description** 

Often, you need to do small checks in a controller resulting in some HTTP redirections. It can be cumbersome to have to handle manually a response to return each time.

In the same way there is already `AccessDeniedException`, `NotFoundHttpException`, I would like to introduce a new `RedirectException`.

**Example**  

Before:

```php
class Controller extends AbstractController
{
    public function step2Action(): HttpResponse
    {
        if ($response = $this->guardStep2()) {
            return $response;
        }

        // ...
    }

    public function guardStep2(): ?HttpResponse
    {
        if (XXX) {
            return new RedirectResponse('/step1')
        }
    }
}
```

After:

```php
class Controller extends AbstractController
{
    public function step2Action(): HttpResponse
    {
        $this->guardStep2();

        // ...
    }

    public function guardStep2()
    {
        if (XXX) {
            throw new RedirectException('/step1');
        }
    }
}
```

The new RedirectException would also give the benefit to services to trigger HTTP redirections without having to deal with the response flow.

*Edit: removed the controller shortcut proposal*

**Comment by dbrumann** [comment]
I am not sure about this. It looks like a sneaky return to me and what's worse is, that it's hidden in a function call not in the controller action itself, which could potentially lead to hard to trace behavior. Compare this with `createNotFoundException()` as per docs:

```
class Controller extends AbstractController
{
    public function step2Action(): HttpResponse
    {
        if (XXX) {
            throw $this->createNotFoundException();
        }
    }
    // ...
}
```

The method does not throw an exception and stop the action. Changing your example to be in line with `createNotFoundException()` would - as far as I can tell - not make much of a difference compared to your first example, so we wouldn't really gain anything.

**Comment by pyrech** [comment]
I agree the controller shortcut may not be much needed. Updated the description to remove it

So the issue is now only about adding a RedirectException :wink:

**Comment by Nyholm** [comment]
Thank you. 
I think this is interesting and I sure have been in this situation before. But Im not sure this change is preferable. 

Im 👎 for the reasons @dbrumann mentioned and for the fact that a "redirect" is not an "exception". It is a feature or a logical decision.
