### ISSUE TITLE
PHPUnit Bridge breaking on 5.3

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#36638]
**Symfony version(s) affected**: 3.4.40

**Description**  

Running vendor/bin/simple-phpunit ends up in:
```
PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /home/runner/work/composer/composer/vendor/bin/.phpunit/phpunit-4.8/phpunit on line 13
```

This seems to have started a couple days ago with the release of 3.4.40 

Last successful build:

https://github.com/composer/composer/runs/625560043?check_suite_focus=true (see the " Install highest dependencies from composer.json using composer binary provided by system" step, it installs 3.4.39)

All newer builds fail with the above error message, e.g. https://github.com/composer/composer/runs/627782977?check_suite_focus=true

**Comment by Seldaek** [comment]
Just to make sure, I added a conflict against 3.4.40 and indeed build passes again so it's most likely not a problem on our side.

**Comment by stof** [comment]
The PR fixing it already exists :smile:

**Comment by Seldaek** [comment]
Ah I searched for issues, obviously that missed the PR.. Thanks
