### ISSUE TITLE
RequiredValidator missing from 3.4.40 release

### ISSUE THREAD

**Issue by vlahanas** [symfony/symfony#36637]
**Symfony version(s) affected**: 3.4.40

**Description**  
The RequiredValidator is missing from Symfony\Component\Validator\Constraints and breaks the usage of ```new Constraints\Required()```

**Comment by stof** [comment]
The `Required` and `Optional` constraints are special ones meant to be used only inside the `Collection` one (to decide whether each field in the collection of fields is optional or required). They are not meant to be usable standalone.

**Comment by renjinsk** [comment]
Actually, this is how we use it:
```php
$validator   = Validation::createValidator();
$constraints = new Constraints\Collection([
    'theField'  => [
        new Constraints\Required(),
        new Constraints\NotBlank(),
    ],
]);```
Correct us if we are wrong..
The "break" was introduced from version 3.4.39 to latest one 3.4.40

**Comment by stof** [comment]
Correct usage of the Collection constraints looks like that AFAICT:

```
$constraints = new Constraints\Collection([
    'theField' => new Constraints\Required([
        new Constraints\NotBlank(),
    ])
]);
```

Also note that fields for which you pass an array of constraints instead of an Optional or Required object get it wrapped in a Required automatically. So your code is equivalent to using a standard Required constraint inside a required field.

**Comment by Nyholm** [comment]
Thank you @stof for your explanation. 

There is no `RequiredValidator` in any version of Symfony. They are only annotations used by the `Collection`.

**Comment by xabbuh** [comment]
see also #36723

**Comment by xabbuh** [comment]
see #36894
