### ISSUE TITLE
Symfony component notifier - Mattermost integration errors

### ISSUE THREAD

**Issue by seb37800** [symfony/symfony#36632]
**Symfony version(s) affected**: 5.1

**Description**  
Many errors when we want to integrate mattermost notification using the package symfony/mattermost-notifier.

**How to reproduce**  
Update your composer.json file to use mattermost notification :
```
"symfony/notifier": "dev-master",
"symfony/mattermost-notifier": "dev-master",
```
Add the following code into a controller : 
```
$message = (new ChatMessage('Test mattermost integration'))
                ->transport('mattermost');

$chatter->send($message);
```
Also add this in argument to your method
`ChatterInterface $chatter`

**Possible Solution**  
We have multiple errors in src/Symfony/Component/Notifier/Bridge/Mattermost/MattermostTransport.php : 
- line 59 endpoint is forced to https : ok my local docker mattermost is on http, but it could be interesting to make it flexible in the future. Allowed scheme endpoint in MATTERMOST_DSN ? 
- line 59 endpoint call api/v4/post instead of api/v4/posts according to https://api.mattermost.com/#tag/posts/paths/~1posts/post
- line 72 a condition on a response code 200 is wrong, it must be a 201 cf response samples in https://api.mattermost.com/#tag/posts/paths/~1posts/post

Thanks for this new feature.

**Comment by fabpot** [comment]
@seb37800 Can you work on a PR?

For http vs https, that's something we do everywhere and it should not be configurable. For everything else, bug fixes are more than welcome in a PR. Thank you.

**Comment by seb37800** [comment]
@fabpot Thanks for the explanation on the https force, I suspected that there was a reason behind.
If i find time i could work on a PR.

**Comment by fabpot** [comment]
If the bridge does not work, we will remove it before 5.1. There is no point in keeping something broken. 

/cc @thePanz

**Comment by thePanz** [comment]
I can have a look by the end of this week, is it ok for you @fabpot  @seb37800 ?

**Comment by seb37800** [comment]
@thePanz Thank you I just submitted a PR if you want to take a look

**Comment by thePanz** [comment]
Thanks @seb37800 I can confirm that your changes are working. I am still puzzled as my initial PR was working on my side :thinking:
