### ISSUE TITLE
Ability to determine if Event was fired from TraceableEventDispatcher

### ISSUE THREAD

**Issue by Syntaf** [symfony/symfony#36631]
**Description**  
_Note: If this sounds like something the Symfony team would be ok with I'd be happy to submit a PR for this_

I'm trying to write a functional test around the following situation:
- I have an API endpoint, `/api/interactions/1/view` which Mobile Apps communicate with
- This endpoint validates incoming data then dispatches a `ItemViewEvent` event
- I want to validate that this endpoint dispatches an `ItemViewEvent` event, I don't necessarily care if anyone is listening though

It doesn't seem like there's any simple way to do this with `TraceableEventDispatcher` at the moment.

For a solution, I could add new member variable to the traceable dispatcher which collects all event names in `preProcess`. A method like `verifyEventDispatched(string $event)` could then return `true` or `false` depending on if the event was ever dispatched (regardless of if someone was listening).

**Example(s)**
It would be great if there was a method like `verifyEventDispatched(string $event)` so I could do the following:

```php
public function testInteractionEndpoint()
{
    $client = static::createClient();

    // ....

    /** @var TraceableEventDispatcher $traceableEventDispatcher */
    $dispatcher = static::$container->get('event_dispatcher');

    $this->assertTrue($dispatcher->verifyEventDispatched(ItemViewEvent::class));
}
```

Since there isn't, here's what I currently have to do:

```php
public function testInteractionEndpoint()
{
    $client = static::createClient();

    // ....

    /** @var TraceableEventDispatcher $traceableEventDispatcher */
    $dispatcher = static::$container->get('event_dispatcher');

    $dispatchedEvents = array_column($dispatcher->getCalledListeners(), 'event');
    $orphanedEvents = $dispatcher->getOrphanedEvents();

    $found = false;

    // look through dispatched events
    foreach($dispatchedEvents as $event) {
        if ($event == ItemViewEvent::class) {
            $found = true;
            break;
        }
    }
    
    // look through orphaned events
    if (!$found) {
        foreach ($orphanedEvents as $event) {
            if ($event == ItemViewEvent::class) {
                $found = true;
                break;
            }
        }
    }

    $this->assertTrue($found);
}
```

**Comment by Nyholm** [comment]
Thank you for this issue. 

The `TraceableEventDispatcher` and most other `Traceable*` classes are decorators that are used to populate the WebProfiler with data. It is not ment to be used in testing like this. 

I usually write a dummy implementation of the EventDispatcherInterface to make it easy to collect dispatched events. Or I may mock the EventDispatcherInterface.

**Comment by fabpot** [comment]
@Nyholm is right. Let's close.

**Comment by wouterj** [comment]
We do have a documentation article about using the profiler to test specific statistics in functional tests: https://symfony.com/doc/current/testing/profiling.html

Given @Nyholm's comment, I think we should consider what the Symfony recommended practice is.  If we think writing a spy event dispatcher is the best idea, we should rewrite or remove that article.

For the record: I don't have a strong opinion on this one. I completely agree with @Nyholm from a design perspective. Yet at the same time, the traceable class already has everything that's needed to be a spy - except from a relatively small "is this event fired" method.

**Comment by Syntaf** [comment]
Thanks for the replies! Knowing that the traceable classes aren't meant to be used in testing like this, I used a dummy event listener to verify the event fired:

```php
public function testEndpointDispatchesViewEvent()
        $client = static::createClient();

        // Set the priority to a very low value to ensure it executes last.
        // If any other listeners stop propagation this test will fail.
        static::$container->get('event_dispatcher')
            ->addListener(
                ItemViewEvent::class,
                function (ItemViewEvent $event)
                {
                    $this->eventFired = true;
                },
                -1000000
            );

        $client->request(
            'GET',
            '/interaction/1/thread/item/1234',
            /* ... */
        );

        $response = $client->getResponse();

        $this->assertTrue($response->isSuccessful());
        $this->assertTrue($this->eventFired);
}
```

I got the original idea to use the `TraceableEventListener` from the link @wouterj provided. Should the above approach be preferred then? Not sure which section this documentation would fall under, but I'd be willing to draft up a doc and submit a pr.
