### ISSUE TITLE
[Translation] As a standalone component, XmlUtils::class not found when using XliffFileLoader

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony#36658]
**Symfony version(s) affected**: All?

**Description**  
When using `symfony/translation` as a stand alone component, `XliffFileLoader::class` requires `Symfony\Component\Config\Util\XmlUtils::class`. As `symfony/config` is a `require-dev` dependency, the `XmlUtils` is not found unless you explicitly require `symfony/config`

**How to reproduce**  
```
// test.php

<?php

require __DIR__.'/vendor/autoload.php';

use \Symfony\Component\Translation\Loader\XliffFileLoader;

$loader = new XliffFileLoader();
$loader->load('file.xlf', 'en');
```
```
?> php test.php

Fatal error: Uncaught Error: Class 'Symfony\Component\Config\Util\XmlUtils' not found in /var/htdocs/vendor/symfony/translation/Loader/XliffFileLoader.php:54
```

**Possible Solution**  
Move the `"symfony/config": "^4.4|^5.0",` from `require-dev` to `require` in `composer.json`

**Additional context**  
While it's not your average use case to use translations as a standalone component - I ran into this when creating a CLI app to auto-magically create translation files for me using a 3rd party translation service.

I'm more than happy to submit a PR with the aforementioned solution. Thoughts?

**Comment by xabbuh** [comment]
Using the `XliffFileLoader` is optional and our policy is to not promote dependencies for optional features to the `require` section. But I think we can improve DX here by checking for the existence of the `XmlUtils` class in the constructor of `XliffFileLoader` and throw an exception there if it is missing.

**Comment by jrushlow** [comment]
@xabbuh sounds good. Should we base this off of master rather than 3.x? This would be more of a new feature rather than a bug fix.

**Comment by Nyholm** [comment]
Let's do it on master. I think it will be a quite small PR so to move branch later should not be an issue in case Im wrong. =)
