### ISSUE TITLE
[Mailer / Amazon Mailer] Valid AWS secret key characters removed / throwing invalid DSN exception

### ISSUE THREAD

**Issue by nspyke** [symfony/symfony#36669]
**Symfony version(s) affected**: 4.4.8

**Description**  
I am setting up the Symfony Amazon mailer component and passed my AWS key and AWS secret to the mailer DSN. My AWS secret contains a `+` character in it, eg `A57+VZcaA` (obviously not a real key). I noticed I was getting signature errors.
Adding a dump and echo to line 41 of Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpTransport using the example secret above outputs the following;

https://pasteboard.co/J6ErpBL.png

As a workaround, I generated a new access key and secret, and this time it contains two / characters in it eg `...se/J1/0p`, and am getting the exception;
```
 The "ses://xxxxx:xxxxse/J1/0p@default?region=us-west-2" mailer DSN is invalid
```

**How to reproduce**  
Setup symfony/mailer with the Amazon SES mailer. 
Generate a access key and secret that has a + or / character in it.
Add;
```
        echo($this->secretKey);
        dd($this->secretKey);
```
to line 41 of Symfony\Component\Mailer\Bridge\Amazon\Transport\SesHttpTransport

**Additional context**  
I also tried to reference a service parameter instead of a .env variable and the plus character was also removed from that as well.
When I edited the SesHttpTransport class and changed the $secretKey variable to my actual key in the constructor, the email was sent successfully.

In an attempt to figure out where the cause is a `dd($dsn)` on line 96 of Symfony\Component\Mailer\Transport shows the full correct key being presented to the Transport classes.

A further dump on line 125 of the same class shows the secret with the + symbol removed.

**Comment by Nyholm** [comment]
Hm. 

I had a similar issue in another DSN parser: https://github.com/Nyholm/dsn/pull/12

The `nyholm/dsn` package is very similar to how the CacheComponent parses Redis DSN and I think also similar here.

**Comment by drekinov** [comment]
mailer/Transport/DSN.php  urldecode username and password - you can check source code.

so you need to encode username and password(replace + with %2B and etc urlencode())
then DSN works.

Tricky part is that there is no ENV processor to urlencode value on the fly. so if you are constructing dsn in config you cant use default AWS_* envs but you should have:
AWS_SECRET_ACCESS_KEY - regular
AWS_SECRET_ACCESS_KEY_ENCODED - use in dsn

async aws sdk in symfony 5.1 should solve most of the issues i have with EC2 role authentication which is not supported right now :)

**Comment by fabpot** [comment]
Closing as @drekinov gave the current solution.

**Comment by nspyke** [comment]
While the solution does work, it is completely undocumented. I feel that in
order for this to be resolved, there needs to be something in the mailer
documentation that explains how to use special characters in DSN keys.

**Comment by fabpot** [comment]
You're right, can you open an issue on the docs repo?

**Comment by nspyke** [comment]
> 
> 
> You're right, can you open an issue on the docs repo?

Hi @fabpot . I've submitted a docs PR.
https://github.com/symfony/symfony-docs/pull/13838

**Comment by janklan** [comment]
I just tripped over the same problem. I think having to keep an url-encoded copy of another variable is not ideal. 

I found the SES client used by Amazon Mailer can inherit the system-wide credentials set in `config/packages/aws.yaml` in the most basic way:

```
aws:
    version: latest
    region: "%env(AWS_REGION)%"
    credentials:
        key: "%env(AWS_IAM_ACCESS_KEY)%"
        secret: "%env(AWS_IAM_SECRET_KEY)%"
```

All you then have to do is to omit the username and password in `MAILER_DSN`:

```
MAILER_DSN=ses+api://default?region=${AWS_REGION}
```

Note: you do have to include the `AWS_REGION` in `MAILER_DSN`. The default value is decided by the SES transport class, which ignores the global AWS SDK settings.

**Comment by janklan** [comment]
I dug a bit deeper into the default region thing. I tried what happens when I use null as the default value here https://github.com/symfony/amazon-mailer/blob/5.3/Transport/SesTransportFactory.php#L44, and the SES client provided by AWS SDK correctly adopted the system-wide region. 

Why do we have `eu-west-1` as a default region in the first place? It doesn't make sense.
