### ISSUE TITLE
conflict with php-psr

### ISSUE THREAD

**Issue by JoeByte** [symfony/symfony#36676]
```bash
pecl install psr
```
Symfony conflict with php-psr

> Compile Error: Cannot declare interface Psr\Container\ContainerInterface, because the name is already in use

**Comment by xabbuh** [comment]
Is there a specific reason you need this PECL package? If you cannot stop using it, you will need to make sure that the PSR Composer packages are not installed too by listing them in the `replace` section of your `composer.json` file like this:

```json
{
    "replace": {
        "psr/container": "1.*"
    }
}
```

In any case, this is not related to Symfony itself and there is nothing we can change about this. So I am going to close here. Thank you for understanding.

**Comment by JoeByte** [comment]
I test phalcon, and it use Psr PECL package, 

thank you for your help
