### ISSUE TITLE
Reference Tagged Services combined with Autoconfiguring Tags does not work

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#36682]
**Symfony version(s) affected**: 4.3.11

**Description**  
[Reference Tagged Services](https://symfony.com/doc/4.3/service_container/tags.html#reference-tagged-services) combined with [Autoconfiguring Tags](https://symfony.com/doc/4.3/service_container/tags.html#autoconfiguring-tags) does not work

**How to reproduce**  
1. Create interface
2. Tag the interface under `_instanceof` - as described in [Autoconfiguring Tags](https://symfony.com/doc/4.3/service_container/tags.html#autoconfiguring-tags)
3. Create a service and pass all `!tagged` services as its arguments - as described in [Reference Tagged Services](https://symfony.com/doc/4.3/service_container/tags.html#reference-tagged-services)
4. Run `bin/console cache:clear` (or any other command)
5. You will see `Cannot autowire service (…): argument "$handlers" of method "__construct()" is type-hinted "iterable", you should configure its value explicitly.` exception

Is it a bug?

**Workaround**
1. Create a Compiler Pass class that implements `CompilerPassInterface`
2. Call `findTaggedServiceIds()` + `addMethodCall()` as described in [How to Work with Compiler Passes](https://symfony.com/doc/current/service_container/compiler_passes.html)

Is there another solution?

**Comment by xabbuh** [comment]
Symfony 4.3 doesn't receive bugfixes anymore. Do you still experience this using Symfony 4.4?

**Comment by kniziol** [comment]
I have focused more on this problem. Problem does not appear in 4.3 and 4.4 (both versions verified).

There was mistake, related to configuration 🤦
