### ISSUE TITLE
[HttpKernel] [Routing] RequestListener should not assume that its Context and Matcher's (Router's) Context are the same object

### ISSUE THREAD

**Issue by Amunak** [symfony/symfony#36685]
**Symfony version(s) affected**: 4.4.8 (but all really; it's 5+ years old code)

**Description**  
HttpKernel's RequestListener, a service responsible for calling Routing's RequestMatcher (Router), has a RequestContext object holding information about the current request. When RouterListener is called, it modifies this object with the current Request's data, and then calls the Router to resolve the actual route.

This works perfectly when RouterListener and Router have the same instance of RequestContext, but it completely breaks down when that is not the case: RouterListener still modifies the RequestContext with current Request's data but Router doesn't see those changes - it has its own RequestContext instance, and happily proceeds with matching using that context, which might (for example) have a different Method than the actual one from the Request.

It does not happen under normal circumstances. I stumbled upon this when I enabled "router cache" in the Codeception test framework, which causes the Router service (and its RequestContext) to persist between Request calls, which in turn causes the services to have different instances of RequestContexts, causing this issue. I have also opened an issue for them at codeception/module-symfony#8.

However it still seems like bad design: you have a **hidden dependency** in there; the two classes (Listener and Router) just *assume* that they have the correct Context instead of actually making sure that this is the case.

**How to reproduce**  
1. Ensure that RouterListener's RequestContext is not the same object as Router's RequestContext
2. Handle a Request with non-default values (e.g. with Method: POST).
3. Observe that Router matches routes with `methods: GET` instead of `methods: POST`.

I made a reproducer at [Amunak/symfony-routing-bug-reproducer](https://github.com/Amunak/symfony-routing-bug-reproducer) - run it with `php public/index.php` and observe that it returns a GET route instead of a POST route (when you comment out the forceful change of RequestContext you will see that it works correctly, which is thankfully the default for most Symfony projects and the way they are run).

**Possible Solution**  
There are several solutions and I'm not sure which one is architecturally correct for Symfony, but;

1. RouterListener could simply remove the dependency on RequestContext through DI, and it could always just grab the context from the Matcher. This would require however that RequestMatcherInterface be a descendant of RequestContextAwareInterface, just like UrlMatcherInterface is. Symfony Router already implements both interfaces, so it would be easy there.
2. RouterListener could explicitly call `setContext()` on the matcher, to force it to use its (correct) Context, and to explicitly show the dependency. Once again this would require RequestMatcherInterface to extend RequestContextAwareInterface.
3. Classes implementing RequestMatcherInterface already receive the full Request. They could use this to update their Context and completely ignore the Context RouterListener uses.
4. RouterListener could pass the Context as a parameter when it calls `match()`/`matchRequest()`; this could also work if it's treated as an "override" for the Matcher's Context. Make it an optional argument, if not used the class Context would be used. This would allow for full compatibility with existing code, though it would pollute the interfaces with a new argument and overall it feels "ugly".

There are probably other solutions I haven't thought of. It's all BC breaks city unfortunately. It would help if we didn't have two different Matcher interfaces though.

**Comment by nicolas-grekas** [comment]
I'm not sure there is really an issue. The same happens with then entity manager: ppl expect to always get the same instance, but nothing enforces it.

If one wants to still work on this, I'd suggest going with the approach that requires *no* stateful services. (E.g 1./4. but not 2./3.)

**Comment by Amunak** [comment]
The difference is, I think, that here it is two services that are used "internally" and rarely touched by users doing this. Then *something* happens that breaks this hidden dependency, and it's extremely hard to debug and there is no proper fix for it.

Whereas when I use some services (like the EntityManager) directly it's up to me to make sure I get the correct instance, make sure it isn't closed, etc.

Though in the end what's most confusing to me I guess is the architectural decision to make RequestContext a service. It's essentially a DTO; it should be a "dumb" model, not a service present in DI.

And I also feel like it shouldn't be RouterListener's responsibility to convert a Request into RequestContext; that should probably be a job for RequestMatcher. It's puzzling to me why it accepts a full on Request object and then almost doesn't use it.

Regardless I have no idea *if* I went about attempting to create a patch for this issue, should it be considered a breaking change if I made something like (4) without changing method properties and such? It could potentially break someone's code if they pass their own Context in such edge caseas it would get overriden with data from the Request (which is probably the fix I would make), but I would expect noone does this (and if they do, why?). Also if it is deemed a BC break that would mean it would get incorporated when, a year and a half from now?

**Comment by nicolas-grekas** [comment]
I agree that this should not be a service anymore. About this specific issue, I would suggest to close it, as we identified the path forward. Focusing on the underlying reason will help ppl know what is expected and maybe contribute a PR.
This is going to be a non-trivial topic, to figure out how to properly deprecate the existing system without breaking it and build the new one next to it.

**Comment by Amunak** [comment]
Closing as per discussion. Will create separate issue to track the fix.
