### ISSUE TITLE
SendEmailMessage class marked as internal

### ISSUE THREAD

**Issue by ricohumme** [symfony/symfony#36699]
**Symfony version(s) affected**: 4.4.*|5|master

**Description**  
Currently the constructor for this class is still marked as internal, and I am wondering why that is?
Is it so that this is class is still subjected to change, or doesn't have BC promise?
I'm currently implementing this message in my application, and  PHPStorm struck the classname, so I started to investigate.

I noticed users saying that PHPStorm should not strike these classes when marked as internal, but the question of changes and/or BC promise remains.

Thanks in advance.

**Comment by fabpot** [comment]
I think we can safely remove the annotation. That's a leftover from a previous version of my local code. Fixed in #37181

**Comment by ricohumme** [comment]
Thnx Fabien
