### ISSUE TITLE
SerializerErrorRenderer sets a "Vary" response header

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#36698]
**Symfony version(s) affected**: 4.0.7+

**Description**  
When throwing http exceptions for 404 cases I noticed that the `vary` header on my `@Cache` annotation (framework-extra-bundle) is ignored. Any existing `Vary` header is [kept](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/src/EventListener/HttpCacheListener.php#L135) by default.

This is because of this change
https://github.com/symfony/symfony/commit/0050a4dafb18a5a616cc33fe5fc8027b03045158#diff-11a172176225cc4b366ca0342ba2c20aR64

And actually in my case this is wrong. There is no vary on this header in my application. The API in question just supports json.

**Possible Solution**  
Revert adding the `Vary` header? I don't think it makes sense to assume this for every response.

cc @yceruto

**Comment by nicolas-grekas** [comment]
The `$format` callback is configured by default to call `getPreferredFormat`, which does use the `Accept` header. Not that the patch you link to is part of a security fix, we should be extremely careful to not reintroduce the issue.

**Comment by dmaicher** [comment]
For now I decorated the renderer to solve my issue:

```php
class VaryHeaderRemovingErrorRenderer implements ErrorRendererInterface
{
    private ErrorRendererInterface $wrappedRenderer;

    public function __construct(ErrorRendererInterface $wrappedRenderer)
    {
        $this->wrappedRenderer = $wrappedRenderer;
    }

    public function render(\Throwable $exception): FlattenException
    {
        $exception = $this->wrappedRenderer->render($exception);
        $exception->setHeaders(array_diff_key($exception->getHeaders(), ['Vary' => 1]));

        return $exception;
    }
}
```

**Comment by yceruto** [comment]
I think the question is if this `Vary: Accept` is really necessary when there is no `Accept` header on the request, or it wasn't taken into account to guess the request format (e.g. because `_format` attribute took precedence over `Accept` header). Anyway, at this point, we wouldn't know which variant was used (unless we do something to know it) so we decided to send the `Vary: Accept` header always.

**Comment by dmaicher** [comment]
Closing this for now
