### ISSUE TITLE
[Lock] Update the MongoDbStore to work with the latest version of the mongodb extension

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony#36702]
The MongoDbStore is not compatible with the latest versions of mongodb extension. The latest mongodb extension uses a new way of creating the client.

Instead of [`MongoDB\Client`](https://docs.mongodb.com/php-library/v1.6/reference/method/MongoDBClient__construct/) we now have [`MongoDB\Driver\Manager`](https://www.php.net/manual/en/class.mongodb-driver-manager.php).

Some options to consider:

1. Make the store work for both interfaces.
2. Migrate the store to the new interface.
3. Create a new MongoDbStore implementation for the latest version of the interface.
4. Use an adapter: https://github.com/alcaeus/mongo-php-adapter.
5. Drop mongodbstore.

**Comment by nicolas-grekas** [comment]
1. if possible :)

**Comment by jakzal** [comment]
BTW, looks like the old mongo extension doesn't even work with PHP 7, so there's no need to keep supporting it on the branches that only work with PHP 7.

**Comment by kralos** [comment]
@jakzal I'm not sure what you mean by "not compatible with the latest versions of mongodb extension"? I use this store in production on `php` `7.4.4` with `ext-mongodb` `1.7.4` and `mongodb/mongodb` `1.6.0`.

`MongoDB\Client` hasn't been replaced by `MongoDB\Driver\Manager`. They do different things at different layers.

`MongoDB\Driver\Manager` is the official latest PECL extension driver (aka `ext-mongodb`). see https://pecl.php.net/package/mongodb

`MongoDB\Client` is from the official latest PHP adapter (aka packagist `mongodb/mongodb`) that sits on top of the PECL driver. see https://github.com/mongodb/mongo-php-library

There was a legacy driver (`ext-mongo`). packagist package `alcaeus/mongo-php-adapter` is a compatibility layer exposing the `ext-mongodb` interfaces but using `ext-mongo` under the hood.

**Comment by jakzal** [comment]
@kralos thanks for the clarification. One stackoverflow answer led me to believe the class is from the previous version of the extension. What I was missing is the `mongodb/mongodb` package though!
