### ISSUE TITLE
[RFC] [DI] Compiler pass to remove optional/invalid services

### ISSUE THREAD

**Issue by alcaeus** [symfony/symfony#36701]
**Description**  
The idea for this feature came when looking at a PR in DoctrineBundle. For optional integrations (e.g. integrating Doctrine ORM with the Messenger component), we provide a bunch of service definitions that are then removed in the extension if the necessary class doesn't exist (see [example](https://github.com/doctrine/DoctrineBundle/blob/98e038ded65cf31fc11ee6d497977b7b8b67abe9/DependencyInjection/DoctrineExtension.php#L842)). To avoid having this kind of boilerplate code, a compiler pass could act upon the information in a tag:

```xml
<service id="potentially_missing" class="Potentially\Missing\Class">
    <tag name="symfony.remove_service" if="!class_exists('Potentially\Missing\Class')" />
</service>
```

Ideally, the `if` part would be an expression, allowing users to include any logic there. For example, if another service has a dependency on the (now non-existent) service, it would also have to be removed:
```xml
<service id="has_dependency" class="existing_class">
    <argument type="service" id="potentially_missing" />
    <tag name="symfony.remove_service" if="!container.has('Potentially\Missing\Class')" />
</service>
```

This would require the compiler pass to do multiple passes over the container until it removed all services. Since this only happens during compilation and is an opt-in feature, the performance impact should hopefully not be too severe.

I'd like your opinion and ideas as to how this could be used (or abused).

**Comment by mbabker** [comment]
As a package maintainer I'd be 👍 on this.  I've wired up passes in a number of packages to remove unused services from a variety of conditions (config has feature disabled, requisite Composer package or PHP extension not installed, etc.) so having something in the framework to help facilitate this would be interesting.

**Comment by xabbuh** [comment]
This looks quite promising to me. We also have a lot of code like this in the Symfony codebase (especially in the FrameworkBundle).

**Comment by stof** [comment]
I'm not sure we should allow arbitrary expressions or have specific use cases implemented (note that the naming is to be defined):

```php
<tag name="symfony.clean_container" required-service="potentially_missing" />
<tag name="symfony.clean_container" required-class="Potentially\Missing\Class" />
```

For more complex conditions, bundles can still provide their own compiler passes doing crazy logic (they would need it anyway if the conditions they want to write cannot be expressed with the ExpressionLanguage variables and functions we would expose in your `if` proposal, as allowing PHP code that we would run through `eval` is a no-go IMO).

**Comment by alcaeus** [comment]
Good point, I was wondering if the expression language is enough to cover all use-cases. Limiting this to missing services and missing classes is a good idea.

**Comment by umulmrum** [comment]
Just a quick thought: Maybe this can be simplified even more. For parameters and service arguments there is the optional attribute `on-invalid`. Would it make sense to use this attribute also for services? "invalid" could be interpreted as "anything in the service definition is invalid" or narrowed down to "a class or service referenced in the service definition or an argument does not exist".

From a DX perspective we should (for any solution) think about what happens if a removed service is referenced by a service without this new annotation. Most likely it will fail, in which case providing a custom message would certainly help. I could also imagine something like `on-invalid="replacement-service"` with `replacement-service` being any service that will be used instead, providing some dummy or fallback logic. If not used this service would be removed by the container optimization.

**Comment by nicolas-grekas** [comment]
If #36778 becomes the default, we might not need this at all.
Lower complexity is better.

**Comment by stof** [comment]
Well, for the `class_exists` case, indeed. For the "missing service", no, because you cannot check that from config files in DI extensions (that's before container is merged with other DI extensions)

**Comment by nicolas-grekas** [comment]
@stof true. I would be interested in gathering some facts about the actual lines of code this could replace, by looking at our own codebase + some important bundles. Anyone would be up to give this a shot?

**Comment by nicolas-grekas** [comment]
On 2nd thought, I'm not sure it's worth the complexity nor that it'll be worth teaching/using, versus doing almost the same in a DI extension.

**Comment by alcaeus** [comment]
Considering that #36778 was merged and route/service configuration is now done in PHP for all core extensions, I don't think there's the need to provide this as part of the DI component. Thanks for all the suggestions and feedback!
