### ISSUE TITLE
New getProjectDir in MicroKernelTrait is too opinionated

### ISSUE THREAD

**Issue by garak** [symfony/symfony#36719]
**Symfony version(s) affected**: 5.1.0

With changes introduced in commit a68980738798233d257fa46875f32827f4537254, is always supposed that Kernel is simply in `src` directory.
This breaks applications where Kernel is put elsewhere (that, by the way, would work fine with the base definition of `getProjectDir` in the base kernel class).

I suggest to revert such change and to remove `getProjectDir` from MicroKernelTrait

**Comment by nicolas-grekas** [comment]
That's just the defaults, you are free to provide your own implementation the fits your layout.

**Comment by xabbuh** [comment]
I think the point is that if you were already using the trait in 5.0 the value returned by `getProjectDir()` now changes when updating to 5.1 and thus one needs to actively change application code when updating.

**Comment by garak** [comment]
> That's just the defaults, you are free to provide your own implementation that fits your layout.

But we already have a default (in base Kernel) and it's better. Why to redefine it in trait?

**Comment by nicolas-grekas** [comment]
I just ran some benchmarks, I measure no diff when I drop the implem in MicroKernel. I suppose replacing `file_exists()` by `is_file()` reclaimed the loss.

Please send a PR @garak
