### ISSUE TITLE
MimeTypes::getMimeTypes() errors on custom mimetypes.

### ISSUE THREAD

**Issue by mcneely** [symfony/symfony#36715]
**Symfony version(s) affected**: looks like 4.2+

**Description**  
`Type error:  Type error: Return value of Symfony\Component\Mime\MimeTypes::getMimeTypes() must be of the type array, string returned` when passing custom map through constructor.

**How to reproduce**  
`$type =(new MimeTypes([
        'application/octet-stream' => ['rrd']
    ]))->getMimeTypes('rrd')`

**Possible Solution**  
Add `[]`'s around `$mimeType` in constructor

**Comment by nicolas-grekas** [comment]
Would you mind sending a fix with some test cases? From your description it should target 4.4.

**Comment by mcneely** [comment]
@nicolas-grekas done.
