### ISSUE TITLE
[HttpClient] Invalid HTTP status codes raise a warning using CurlHttpClient

### ISSUE THREAD

**Issue by aleksblendwerk** [symfony/symfony#36717]
**Symfony version(s) affected**: 5.0.8

**Description**  
When sending a GET request that is answered with a `999` status code (which is horrible behavior, no doubt), a warning is raised.

Is there a way to prevent this?

```
Warning: curl_multi_exec(): Could not call the CURLOPT_HEADERFUNCTION in /vendor/symfony/http-client/Response/CurlResponse.php on line 261

[...]

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: Invalid or missing HTTP status line. in /vendor/symfony/http-client/Response/ResponseTrait.php on line 273

Symfony\Component\HttpClient\Exception\TransportException: Invalid or missing HTTP status line. in /vendor/symfony/http-client/Response/ResponseTrait.php on line 273
```

At least I *think* it is the `999` that breaks things, I am using Symfony's HttpClient within a crawler and a link similar to https://www.linkedin.com/company/linkedin/ made it break.

**How to reproduce**  

```
$client = new \Symfony\Component\HttpClient\CurlHttpClient();

$response = $client->request('GET', 'https://www.linkedin.com/company/linkedin/');
$contents = $response->getContent();
```

If that LinkedIn link does not return a `999` for you, you will probably need to manually set up a site that does to encounter the error. Not sure how they decide when to respond with `999`. While gathering information for this report it returned the `999` in Chrome for me as well but eventually also worked once or twice. Probably security measures based on User-Agent and IP.

More people plagued by this over here: https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin.

**Comment by nicolas-grekas** [comment]
What a strange behavior! I think the code is not prepared to deal with non conformant status codes, but it should be possible to fix and even add a test case I suppose. Would you like to give it a try? This should target branch 4.4.

**Comment by aleksblendwerk** [comment]
@nicolas-grekas 

I will have a look tomorrow!

**Comment by aleksblendwerk** [comment]
Short update on this: I started by adding a test to `HttpClientTestCase`, just requesting the URL given under 'How to reproduce' above. When running that single test method within `CurlHttpClientTest`via PHPUnit I am still getting the Exception but **not** getting the warning. 

I am currently clueless why... I didn't change any of the PHPUnit configuration and it fails correctly when I add other code that triggers a warning.

I am getting the warning when I run my 'reproduce' code above on my 4.4 fork but not within the tests.

**Comment by aleksblendwerk** [comment]
All right, took me long enough but after some debug sessions I think I finally figured out what's happening here.

The headers returned by https://www.linkedin.com/company/linkedin/ look something like this:

```
HTTP/1.1 999 Request denied
Content-Length: 1461
Content-Type: text/html
Set-Cookie: trkCode=ripf; Max-Age=5
Set-Cookie: trkInfo=[...]; Max-Age=5
Set-Cookie: rtc=[...]; Max-Age=120; path=/; domain=.linkedin.com
X-Li-Pop: afd-prod-lva1
X-LI-Proto: http/1.1
X-LI-UUID: [...]
X-MSEdge-Ref: [...]
Date: Fri, 08 May 2020 21:47:57 GMT
```

`CurlResponse` registers `self::parseHeaderLine` as callback for `CURLOPT_HEADERFUNCTION`. 

So as soon as those headers come in, eventually `ResponseTrait::addResponseHeaders` is called, the status code part `([12345]\d\d)` of the regex fails because the status code is above `599`. 

`$info['http_code']` is never set and a `TransportException` with message `Invalid or missing HTTP status line.` is thrown. Now for some reason things get all messed up and the curl instance attempts to call `self::parseHeaderLine` again when parsing the next header `Content-Length: 1461` but can not access it anymore. This is why the warning comes up.

I tried a few things, for example catching the exception in `self::parseHeaderLine` and unset the callback hook with `curl_setopt($ch, CURLOPT_HEADERFUNCTION, false);` but no luck, always ends up with the same warning, probably due to _async things_ beyond my understanding.

So if we don't want this happen, maybe throwing the Exception has to be held back until curl is done parsing headers.

Also from the perspective as a user of this library, I would prefer if as much of the response as possible is handled and parsed, even if the status code is invalid. The way it is now, I would never be able to have a look at the response body.

But I think it might be time for someone to step in who knows that code better than me...  @nicolas-grekas

One more thing: as described above, I didn't examine further yet why the warning doesn't come up in the tests, might be related to a special error handler.

**Comment by nicolas-grekas** [comment]
Let's relax this regexp I agree.

**Comment by aleksblendwerk** [comment]
Many thanks @nicolas-grekas!

I wasn't sure how to go on about the fix, so I'm glad you took over. Maybe next time!

**Comment by bytehead** [comment]
Thank you @nicolas-grekas! 🙏
