### ISSUE TITLE
Warning: preg_match(): Compilation failed

### ISSUE THREAD

**Issue by elkarouani** [symfony/symfony#36728]
I faced this exception and i don't know how to solve it :

Warning: preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 0

Can anyone describe why this exception is appeared ?

**Comment by xabbuh** [comment]
Without more context nobody will be able to help you. Can you provide an example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
