### ISSUE TITLE
[Validator] Constraint validator "Symfony\Component\Validator\Constraints\RequiredValidator" does not exist or is not enabled

### ISSUE THREAD

**Issue by w1nsun** [symfony/symfony#36723]
**Symfony version(s) affected**: 3.4.40

3.4.39 is OK

**Description**  
I get an error: Constraint validator "Symfony\Component\Validator\Constraints\RequiredValidator" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Required".
Line: 49
File: "/data/www/site/current/vendor/symfony/symfony/src/Symfony/Component/Validator/ContainerConstraintValidatorFactory.php"

**How to reproduce**  
```
use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Validator\ValidatorInterface;

//$this->validator - ValidatorInterface (service @validator)
$violations = $this->validator->validate($value, new All([
            new Collection([
                'email' => [
                    new NotBlank(),
                    new Email(),
                ],
                'verified' => [
                    new Required(),
                    new Choice(['strict' => true, 'choices' => [1, 0, "1", "0", true, false]]),
                ],
            ]),
        ]));
```

**Comment by aidenko** [comment]
I have the same on 4.4.8

**Comment by dmaicher** [comment]
Cannot reproduce this on 4.4.8

**Comment by codegain** [comment]
I have the same on 4.4.8 with `Required` and `Òptional` constraint.
No error on 4.4.7.

**Comment by dmaicher** [comment]
Can anyone provide a small [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)?

For me this works fine on 4.4.8:

```php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Required;

$kernel = new AppKernel('dev', true);
$kernel->boot();

$violations = $kernel->getContainer()->get('validator')->validate([[]], new All([
    new Collection([
        'email' => [
            new NotBlank(),
            new Email(),
        ],
        'verified' => [
            new Required(),
            new Choice(['strict' => true, 'choices' => [1, 0, "1", "0", true, false]]),
        ],
    ]),
]));

dump($violations);

**Comment by codegain** [comment]
@dmaicher

```
<?php

require dirname(__DIR__).'/config/bootstrap.php';

use Symfony\Component\Validator\Constraints\Required;

$kernel = new \App\Kernel('dev', true);
$kernel->boot();

$violations = $kernel->getContainer()->get('validator')->validate(null, [
    new Required(),
]);

dump($violations);
```
In my case this prints for 4.4.8:
```
Constraint validator "Symfony\Component\Validator\Constraints\RequiredValidator" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Required".
```
and for 4.4.7:
```
Symfony\Component\Validator\ConstraintViolationList {#712
  -violations: []
}
```

**Comment by xabbuh** [comment]
The best would be if one of you could provide a small example application allowing to reproduce the issue as [suggested by @dmaicher](https://github.com/symfony/symfony/issues/36723#issuecomment-624770287).

**Comment by R11baka** [comment]
@xabbuh Here reproducer for a bug! [Reproducer](https://github.com/R11baka/symfony-36723-reproducer)
<img width="1273" alt="Screenshot 2020-05-07 at 13 00 45" src="https://user-images.githubusercontent.com/614113/81282561-0009e800-9064-11ea-81c2-7bcb1830df74.png">

**Comment by aidenko** [comment]
In my case the issue was reproduced on 4.4.8

the code created for symfony 3.3.36 and now updated to the 4.4.8. After this update I experienced the issue.

Just for test I downgraded 4.4.8 -> 4.4.7 and could not reproduce the issue.

After that I updated to 4.4.8 again. And everything works and the issue not reproduced

**Comment by xabbuh** [comment]
@R11baka Thank you, I was able to reproduce. The behaviour changes is related to #36365. I don't know how we could achieve both (the solved issue and the way the constraint is used in the example). However, using the `Required` constraint in the way as in the reproducer doesn't make much sense. So I am not sure if we really need to change anything.

**Comment by codegain** [comment]
@xabbuh I'm using the `Required` constraint in a form in the `constraints` array. Just modify the controller in @R11baka's reproducer to:

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\Request;

class Test extends AbstractController
{

    public function test(Request $request){
        $form = $this->get('form.factory')->createNamedBuilder('testForm')
                ->add('test', HiddenType::class, [ 'constraints' => [ new Required() ] ])
                ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
                dump('valid');
        }

        dump('not submitted');
    }

}
```
Then require `symfony/form` via composer, restart the symfony web server, open`http://127.0.0.1:8000/?testForm[test]=foo` and the output is:
```
Constraint validator &quot;Symfony\Component\Validator\Constraints\RequiredValidator&quot; does not exist or is not enabled. Check the &quot;validatedBy&quot; method in your constraint class &quot;Symfony\Component\Validator\Constraints\Required&quot;. (500 Internal Server Error)
```
Is this an unsupported use case for constraints?

**Comment by xabbuh** [comment]
Basically yes, or to be more precise: Before the constraint placed in this way was just useless (i.e. there was no difference in having it or not). The `Required` constraint is  meant to be used inside a `Collection` constraint: https://symfony.com/doc/current/reference/constraints/Collection.html#required-and-optional-field-constraints

**Comment by stof** [comment]
@codegain I'm quite sure that your use case was actually to use `NotBlank`, not `Required`

**Comment by codegain** [comment]
@stof Currently I use the `Optional` constraint like this:

```
'constraints' => [
    (null === $someVariable) ? new NotBlank() : new Optional(),
]
```

I know there are other mechanisms like validation groups but that seemed to be the easiest option since `null` is not allowed. It seems I will have to rewrite some of these forms if this is no longer possible.

**Comment by xabbuh** [comment]
see #36894
