### ISSUE TITLE
[Form] preg_match() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by Matts** [symfony/symfony#36734]
**Symfony version(s) affected**: 3.4.39

**Description**  
After upgrading to 3.4.40 I am receiving a preg_match error within our unit tests on TimeType. This issue has been introduced within #36020

Even though this issue would probably have been created due to assumptions in our code base, we would expect that the backwards compatibility promise would ensure the working of this code through patch updates.

**How to reproduce**  
submit a form where the data of a TimeType is of type DateTme

**Possible Solution**  
Make sure the second argument is a string when using preg_match or skip logic if data is an object instead of a string

**Additional context**  
![image](https://user-images.githubusercontent.com/3371705/81276217-02b01180-9053-11ea-9038-afeb5c243a60.png)

**Comment by Matts** [comment]
Due to legal reasons I cannot provide more details in a _public_ issue report

**Comment by xabbuh** [comment]
This looks suspicious to me. How can `$data` be a `DateTime` object in a `PRE_SUBMIT` event listener?

**Comment by Matts** [comment]
@xabbuh indeed interesting. _In a unit test_, we are calling ->submit with a custom built array that has a datetime within it.

An assumption that was made by one of our developers, that datetime should be passed there.

**Comment by xabbuh** [comment]
It looks like your unit test is testing something but not what would happen in a real application. During submission the values are scalars or arrays of scalars. I suggest to fix your test to act like the application would actually behave.

So I am going to close here as there is nothing to fix in core.

**Comment by Matts** [comment]
Understood, conclusion BC break for us in a patch version, but this is due to an unusual configuration on our side.
