### ISSUE TITLE
[Validation][Countries]The existing Country Validator does not fails alpha3 codes.

### ISSUE THREAD

**Issue by crayner** [symfony/symfony#36733]
[Validation][Countries]The existing Country Validator does not fails alpha3 codes.

**Symfony version(s) affected**: 3.4,.* 4.3.*, 5.0.*, 5.1.*

**Description**  
The current (5.0.8) version of the Country Validator does not account for alpha3 codes, only validating against alpha2 codes.

**How to reproduce**  
Any validation of an alpha3 country code returns a country validation error.

**Possible Solution**  
I already have a solution built, with both a strict and a alpha3 property.  The alpha3 property is boolean, set to false by default, and strict also sets to false by default.

In non-strict mode, the value handed to the validator is tested for length and tested appropriately regardless of alpha3 setting. (i.e. an alpha2 or alpha3 code will validate correctly.)

In strict mode, the the validator will only test the value against the setting described by the alpha3 property in the constraint.  alpha3=true, only alpha3 tested, alpha3=false only alpha2 tested.

**Additional context**  
Backwards Compatibility:  Would be the same if strict mode is true and alpha3 is false.  I am suggesting that default settings be strict and alpha3 both be false.

I am happy to try and submit the changes I have made, but I have found the process of submitting changes to Symfony onerous, to the point that previous attempts have always failed as I do not understand who's advice to follow, and I have enough to do without engaging in the politic of this site.  Sorry, just the way I see it.  My existing code for the validator is attached.

``` 
/**
 * Validates whether a value is a valid country code.
 *
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class CountryValidator extends ConstraintValidator
{
    /**
     * {@inheritdoc}
     */
    public function validate($value, Constraint $constraint)
    {
        if (!$constraint instanceof Country) {
            throw new UnexpectedTypeException($constraint, Country::class);
        }

        if (null === $value || '' === $value) {
            return;
        }

        if (!is_scalar($value) && !(\is_object($value) && method_exists($value, '__toString'))) {
            throw new UnexpectedValueException($value, 'string');
        }

        $value = (string) $value;

        if ($constraint->strict) {
            if ($constraint->alpha3 ? !Countries::alpha3CodeExists($value) : !Countries::exists($value)) {
                $this->context->buildViolation($constraint->message)
                    ->setParameter('{{ value }}', $this->formatValue($value))
                    ->setCode(Country::NO_SUCH_COUNTRY_ERROR)
                    ->addViolation();
            }
        } else {
            if (!(Countries::alpha3CodeExists($value) || Countries::exists($value))) {
                $this->context->buildViolation($constraint->message)
                    ->setParameter('{{ value }}', $this->formatValue($value))
                    ->setCode(Country::NO_SUCH_COUNTRY_ERROR)
                    ->addViolation();
            }
        }
    }
}
````

**Comment by crayner** [comment]
Noticed after posting that the alpha3 has been added to the master, but not a strict mode.  IMHO we should have this.

**Comment by ro0NL** [comment]
I dont understand why toggling alpha3/alpha2 validation based on the value its length qualifies as "strict". That's effectively allowing both versions ..., but what's the usecase for allowing both type country codes? Shouldnt you anticipate either alpha2 or alpha3 codes?

**Comment by crayner** [comment]
>  ! dont understand why toggling alpha3/alpha2 validation based on the value its length qualifies as "strict". 

This would be a non-strict use case based on an exists in either alpha2/alpha3.  You have flipped the logic of my statements.  Some of that confusion may have been because my code have an older section, now removed.

Strict would enforce alpha2/alpha3.  Not strict would allow either alpha2/alpha3.  I would tend to use strict 100% of the time, but I have seen legacy code that uses a mix, (and I don't know why, except perhaps incomplete upgrade from 2 to 3.) so allowing either may have a small use case, which is on my desk at the moment.

**Comment by xabbuh** [comment]
I am not sure if I understand you correctly, but wouldn't it solve your problem if you added the constraint twice (one with `alpha3` enabled and one without) and only require one of them to succeed (using the new `AtLeastOneOf` constraint)?

**Comment by crayner** [comment]
That would work but with performance hit.

**Comment by xabbuh** [comment]
IMO the use case isn't common enough to justify changes to the `Country` constraint and its validator if there already is a way to achieve this.

**Comment by crayner** [comment]
Thanks for the views.
