### ISSUE TITLE
Case mismatch between class and real file names

### ISSUE THREAD

**Issue by itinfoway** [symfony/symfony#36731]
"symfony/symfony": "3.4.*"

Uncaught PHP Exception RuntimeException: "Case mismatch between class and real file names: "Symfony\Component\Intl\DateFormatter\DateFormat\TimezoneTransformer.php" vs "Symfony\Component\Intl\DateFormatter\DateFormat\TimeZoneTransformer.php" in "E:\xampp\htdocs\post\vendor\symfony\symfony\src\"." at E:\xampp\htdocs\post\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php line 217

**Comment by xabbuh** [comment]
Which Symfony version do you use? dba163950b4ea7d7e7938b07bb974077987f71e6 seems to have fixed this three years ago.

**Comment by parthajudiya** [comment]
version used symfony/symfony": "3.4.*"

**Comment by parthajudiya** [comment]
> Which Symfony version do you use? [dba1639](https://github.com/symfony/symfony/commit/dba163950b4ea7d7e7938b07bb974077987f71e6) seems to have fixed this three years ago.
version used symfony/symfony": "3.4.*"

**Comment by xabbuh** [comment]
@parthajudiya Please show the output of `composer show` in your application.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by itinfoway** [comment]
> @parthajudiya Please show the output of `composer show` in your application.

{
  "name": "ali/fix",
  "license": "proprietary",
  "type": "project",
  "autoload": {
    "psr-4": {
      "": "src/"
    },
    "classmap": [
      "app/AppKernel.php",
      "app/AppCache.php"
    ]
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "require": {
    "php": ">=5.5.9",
    "symfony/symfony": "3.4.*",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-cache-bundle": "^1.2",
    "symfony/swiftmailer-bundle": "^2.3.10",
    "symfony/monolog-bundle": "^3.0.2",
    "symfony/polyfill-apcu": "^1.0",
    "sensio/distribution-bundle": "^5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "^2.0",
    "twig/twig": "^1.0",
    "friendsofsymfony/user-bundle": "~2.0@dev",
    "knplabs/knp-paginator-bundle": "^2.5",
    "jms/i18n-routing-bundle": "^2.0",
    "twig/extensions": "^1.3",
    "nlp-tools/nlp-tools": "^0.1.3",
    "knplabs/doctrine-behaviors": "~1.1",
    "nelmio/api-doc-bundle": "^2.11",
    "friendsofsymfony/rest-bundle": "^2.4",
    "jms/serializer-bundle": "^1.0",
    "knplabs/knp-time-bundle": "^1.7",
    "nelmio/cors-bundle": "^1.5",
    "lexik/jwt-authentication-bundle": "2.4.4",
    "predis/predis": "^2.0@dev",
    "liip/imagine-bundle": "^1.7",
    "jp/firebase-notification-bundle": "^2.0",
    "hwi/oauth-bundle": "^1.1",
    "php-http/guzzle6-adapter": "^2.0",
    "php-http/httplug-bundle": "^1.18",
    "phpoffice/phpexcel": "^1.8"
  },
  "require-dev": {
    "sensio/generator-bundle": "^3.0",
    "symfony/phpunit-bridge": "^3.0",
    "doctrine/doctrine-fixtures-bundle": "^2.3"
  },
  "scripts": {
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ]
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    }
  }
}

**Comment by xabbuh** [comment]
That's not the output of `composer show`.

**Comment by itinfoway** [comment]
> That's not the output of `composer show`.

![image](https://user-images.githubusercontent.com/63038000/82425777-9dbdd800-9aa4-11ea-9b42-5832931f59b5.png)

**Comment by xabbuh** [comment]
I am sorry, but posting unrelated output will not help here. If you would like to get feedback on your issue, please run `composer show` to get the list of actually installed package versions.

**Comment by itinfoway** [comment]
> composer show

![image](https://user-images.githubusercontent.com/63038000/82432203-538d2480-9aad-11ea-8915-9e68570ff240.png)

![image](https://user-images.githubusercontent.com/63038000/82432173-47a16280-9aad-11ea-8a8b-7e48f1c8fb94.png)

**Comment by xabbuh** [comment]
What is the content of the ` E:\xampp\htdocs\post\vendor\symfony\symfony\src\Symfony\Component\Intl\DateFormatter\DateFormat\TimeZoneTransformer.php` file?

**Comment by itinfoway** [comment]
> What is the content of the ` E:\xampp\htdocs\post\vendor\symfony\symfony\src\Symfony\Component\Intl\DateFormatter\DateFormat\TimeZoneTransformer.php` file?


`<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Intl\DateFormatter\DateFormat;

use Symfony\Component\Intl\Exception\NotImplementedException;

/**
 * Parser and formatter for time zone format.
 *
 * @author Igor Wiedler <igor@wiedler.ch>
 *
 * @internal
 */
class TimezoneTransformer extends Transformer
{
    /**
     * {@inheritdoc}
     *
     * @throws NotImplementedException When time zone is different than UTC or GMT (Etc/GMT)
     */
    public function format(\DateTime $dateTime, $length)
    {
        $timeZone = substr($dateTime->getTimezone()->getName(), 0, 3);

        if (!\in_array($timeZone, ['Etc', 'UTC', 'GMT'])) {
            throw new NotImplementedException('Time zone different than GMT or UTC is not supported as a formatting output.');
        }

        if ('Etc' === $timeZone) {
            // i.e. Etc/GMT+1, Etc/UTC, Etc/Zulu
            $timeZone = substr($dateTime->getTimezone()->getName(), 4);
        }

        // From ICU >= 59.1 GMT and UTC are no longer unified
        if (\in_array($timeZone, ['UTC', 'UCT', 'Universal', 'Zulu'])) {
            // offset is not supported with UTC
            return $length > 3 ? 'Coordinated Universal Time' : 'UTC';
        }

        $offset = (int) $dateTime->format('O');

        // From ICU >= 4.8, the zero offset is no more used, example: GMT instead of GMT+00:00
        if (0 === $offset) {
            return $length > 3 ? 'Greenwich Mean Time' : 'GMT';
        }

        if ($length > 3) {
            return $dateTime->format('\G\M\TP');
        }

        return sprintf('GMT%s%d', ($offset >= 0 ? '+' : ''), $offset / 100);
    }

    /**
     * {@inheritdoc}
     */
    public function getReverseMatchingRegExp($length)
    {
        return 'GMT[+-]\d{2}:?\d{2}';
    }

    /**
     * {@inheritdoc}
     */
    public function extractDateOptions($matched, $length)
    {
        return [
            'timezone' => self::getEtcTimeZoneId($matched),
        ];
    }

    /**
     * Get an Etc/GMT timezone identifier for the specified timezone.
     *
     * The PHP documentation for timezones states to not use the 'Other' time zones because them exists
     * "for backwards compatibility". However all Etc/GMT time zones are in the tz database 'etcetera' file,
     * which indicates they are not deprecated (neither are old names).
     *
     * Only GMT, Etc/Universal, Etc/Zulu, Etc/Greenwich, Etc/GMT-0, Etc/GMT+0 and Etc/GMT0 are old names and
     * are linked to Etc/GMT or Etc/UTC.
     *
     * @param string $formattedTimeZone A GMT timezone string (GMT-03:00, e.g.)
     *
     * @return string A timezone identifier
     *
     * @see https://php.net/timezones.others
     *
     * @throws NotImplementedException   When the GMT time zone have minutes offset different than zero
     * @throws \InvalidArgumentException When the value can not be matched with pattern
     */
    public static function getEtcTimeZoneId($formattedTimeZone)
    {
        if (preg_match('/GMT(?P<signal>[+-])(?P<hours>\d{2}):?(?P<minutes>\d{2})/', $formattedTimeZone, $matches)) {
            $hours = (int) $matches['hours'];
            $minutes = (int) $matches['minutes'];
            $signal = '-' === $matches['signal'] ? '+' : '-';

            if (0 < $minutes) {
                throw new NotImplementedException(sprintf('It is not possible to use a GMT time zone with minutes offset different than zero (0). GMT time zone tried: "%s".', $formattedTimeZone));
            }

            return 'Etc/GMT'.(0 !== $hours ? $signal.$hours : '');
        }

        throw new \InvalidArgumentException(sprintf('The GMT time zone "%s" does not match with the supported formats GMT[+-]HH:MM or GMT[+-]HHMM.', $formattedTimeZone));
    }
}
`

**Comment by itinfoway** [comment]
> What is the content of the ` E:\xampp\htdocs\post\vendor\symfony\symfony\src\Symfony\Component\Intl\DateFormatter\DateFormat\TimeZoneTransformer.php` file?


```
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Intl\DateFormatter\DateFormat;

use Symfony\Component\Intl\Exception\NotImplementedException;

/**
 * Parser and formatter for time zone format.
 *
 * @author Igor Wiedler <igor@wiedler.ch>
 *
 * @internal
 */
class TimezoneTransformer extends Transformer
{
    /**
     * {@inheritdoc}
     *
     * @throws NotImplementedException When time zone is different than UTC or GMT (Etc/GMT)
     */
    public function format(\DateTime $dateTime, $length)
    {
        $timeZone = substr($dateTime->getTimezone()->getName(), 0, 3);

        if (!\in_array($timeZone, ['Etc', 'UTC', 'GMT'])) {
            throw new NotImplementedException('Time zone different than GMT or UTC is not supported as a formatting output.');
        }

        if ('Etc' === $timeZone) {
            // i.e. Etc/GMT+1, Etc/UTC, Etc/Zulu
            $timeZone = substr($dateTime->getTimezone()->getName(), 4);
        }

        // From ICU >= 59.1 GMT and UTC are no longer unified
        if (\in_array($timeZone, ['UTC', 'UCT', 'Universal', 'Zulu'])) {
            // offset is not supported with UTC
            return $length > 3 ? 'Coordinated Universal Time' : 'UTC';
        }

        $offset = (int) $dateTime->format('O');

        // From ICU >= 4.8, the zero offset is no more used, example: GMT instead of GMT+00:00
        if (0 === $offset) {
            return $length > 3 ? 'Greenwich Mean Time' : 'GMT';
        }

        if ($length > 3) {
            return $dateTime->format('\G\M\TP');
        }

        return sprintf('GMT%s%d', ($offset >= 0 ? '+' : ''), $offset / 100);
    }

    /**
     * {@inheritdoc}
     */
    public function getReverseMatchingRegExp($length)
    {
        return 'GMT[+-]\d{2}:?\d{2}';
    }

    /**
     * {@inheritdoc}
     */
    public function extractDateOptions($matched, $length)
    {
        return [
            'timezone' => self::getEtcTimeZoneId($matched),
        ];
    }

    /**
     * Get an Etc/GMT timezone identifier for the specified timezone.
     *
     * The PHP documentation for timezones states to not use the 'Other' time zones because them exists
     * "for backwards compatibility". However all Etc/GMT time zones are in the tz database 'etcetera' file,
     * which indicates they are not deprecated (neither are old names).
     *
     * Only GMT, Etc/Universal, Etc/Zulu, Etc/Greenwich, Etc/GMT-0, Etc/GMT+0 and Etc/GMT0 are old names and
     * are linked to Etc/GMT or Etc/UTC.
     *
     * @param string $formattedTimeZone A GMT timezone string (GMT-03:00, e.g.)
     *
     * @return string A timezone identifier
     *
     * @see https://php.net/timezones.others
     *
     * @throws NotImplementedException   When the GMT time zone have minutes offset different than zero
     * @throws \InvalidArgumentException When the value can not be matched with pattern
     */
    public static function getEtcTimeZoneId($formattedTimeZone)
    {
        if (preg_match('/GMT(?P<signal>[+-])(?P<hours>\d{2}):?(?P<minutes>\d{2})/', $formattedTimeZone, $matches)) {
            $hours = (int) $matches['hours'];
            $minutes = (int) $matches['minutes'];
            $signal = '-' === $matches['signal'] ? '+' : '-';

            if (0 < $minutes) {
                throw new NotImplementedException(sprintf('It is not possible to use a GMT time zone with minutes offset different than zero (0). GMT time zone tried: "%s".', $formattedTimeZone));
            }

            return 'Etc/GMT'.(0 !== $hours ? $signal.$hours : '');
        }

        throw new \InvalidArgumentException(sprintf('The GMT time zone "%s" does not match with the supported formats GMT[+-]HH:MM or GMT[+-]HHMM.', $formattedTimeZone));
    }
}

```

**Comment by xabbuh** [comment]
Is the file named `TimeZoneTransformer.php` or `TimezoneTransformer.php` (not the different case of the Z)?

**Comment by itinfoway** [comment]
> TimeZoneTransformer.php

TimeZoneTransformer.php

**Comment by itinfoway** [comment]
> Is the file named `TimeZoneTransformer.php` or `TimezoneTransformer.php` (not the different case of the Z)?

TimeZoneTransformer.php

**Comment by xabbuh** [comment]
Can you please delete your whole `vendor` directory and then run `composer install` to see if that fixes the filename (it should be `TimezoneTransformer.php`)?
