### ISSUE TITLE
Symfony/Contracts/Deprecation/function.php not autoloading with 5.1.0 Beta1

### ISSUE THREAD

**Issue by craigh** [symfony/symfony#36730]
**Symfony version(s) affected**: 5.1.0-BETA1

**Description**  
`Symfony/Contracts/Deprecation/function.php` not autoloading

**How to reproduce**  
I added the following to my composer.json file of my existing project successfully using Symfony 5.0.8

```json
    "minimum-stability": "dev",
    ...
    "require": {
        "symfony/symfony": "5.1.*@beta",
```
(previously was simply `symfony/symfony: 5.*`

run `composer update`

my composer scripts includes

            "bin/console cache:clear --env prod",

So, the update seems to run fine, but on the script above, I get this error:

```shell
Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Dotenv\trigger_deprecation() in /Applications/MAMP/htdocs/core.git/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/core.git/config/bootstrap.php(33): Symfony\Component\Dotenv\Dotenv->__construct('')
#1 /Applications/MAMP/htdocs/core.git/src/Zikula/CoreBundle/bin/console(43): require('/Applications/M...')
#2 {main}
  thrown in /Applications/MAMP/htdocs/core.git/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php on line 49
Script bin/console cache:clear --env prod handling the zikula-scripts event returned with error code 255
Script @zikula-scripts was called via post-update-cmd
```

so, apparently the function `trigger_deprecation` is not defined. So I traced that it should be [autoloaded](https://github.com/symfony/symfony/blob/master/src/Symfony/Contracts/composer.json#L44) but it is not added to my `vendor/composer/autoload_files.php` file (no point pasting the file contents, here - it isn't listed there).

so - while it is more likely that **I** have made the mistake, I thought I would report it and see if it is possibly a bug.

Yes, I know I could simply fix the `bootstrap.php` file and remove the deprecated argument, but that is not really the issue here, right? The issue is that an error should not occur at all, but rather a "silenced deprecation notice" should occur and it doesn't.

**Comment by craigh** [comment]
Here is the shell output through the whole process:

```shell
[Craigs-iMac2013:MAMP/htdocs/core.git] craig% symfony composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 1 update, 0 removals
  - Installing symfony/polyfill-uuid (v1.15.0): Downloading (100%)
  - Installing symfony/polyfill-php80 (v1.15.0): Downloading (100%)
  - Updating symfony/symfony (v5.0.8 => v5.1.0-BETA1): Downloading (100%)
symfony/polyfill-uuid suggests installing ext-uuid (For best performance)
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.
Writing lock file
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
20 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> composer dump-autoload
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
Generated autoload files
> bin/console cache:clear --env prod

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Dotenv\trigger_deprecation() in /Applications/MAMP/htdocs/core.git/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php:49
```

**Comment by wouterj** [comment]
So, seems like the autoload configuration is missing in `symfony/symfony`'s `composer.json` (it's only there in the contract package). I'm not sure if `symfony/symfony` is still supported, if it is then the autoload config should be added.

**Comment by nicolas-grekas** [comment]
`symfony/symfony` does *not* replace `symfony/deprecation-contracts`. There's no reasons it should list `function.php`

`symfony/contracts` does both, so it should work... 

Please check which version of it you have.

**Comment by craigh** [comment]
`installed.json` and `composer.lock`  both say I have v2.1.0 of symfony/contracts

```json
    {
        "name": "symfony/contracts",
        "version": "v2.1.0",
        "version_normalized": "2.1.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/symfony/contracts.git",
            "reference": "b3b9b70bfacfd204d352e7e7350e02c02c0fff78"
        },
```

**Comment by craigh** [comment]
`installed.json` and `composer.lock` both indicate I have version 2.1.0 installed

```json
    {
        "name": "symfony/contracts",
        "version": "v2.1.0",
        "version_normalized": "2.1.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/symfony/contracts.git",
            "reference": "b3b9b70bfacfd204d352e7e7350e02c02c0fff78"
        },
```

**Comment by craigh** [comment]
I do not have `symfony/deprecation-contracts` installed at all.

**Comment by wouterj** [comment]
Ah, seems like we're missing a release of `symfony/contracts`: https://github.com/symfony/contracts/compare/v2.1.0...master The `Deprecation/functions.php` autoload configuration exists only on the `master` branch, not in the `v2.1.0` tag.

**Comment by craigh** [comment]
I just noticed something else that is odd - there are two symfony/contracts...

![Screen Shot 2020-05-07 at 8 05 37 AM](https://user-images.githubusercontent.com/350048/81292417-8fe66c80-9039-11ea-997b-ac7679b410f7.png)

**Comment by craigh** [comment]
I can't find any reason for the duplicate vendor. in my [current (5.0.8) composer.lock](https://github.com/zikula/core/blob/master/composer.lock#L5868) file, you will see that symfony/contracts is only required by `symfony/symfony`. I cannot find any other vendor that is requiring it.

**Comment by xabbuh** [comment]
There's nothing wrong with that. You have two packages coming with the classes/functions for the contracts (`symfony/contracts` and `symfony/symfony`). But only the classes provided by `symfony/contracts` will be registered for the autoloader.

**Comment by nicolas-grekas** [comment]
Please run compose update again, this should be fixed.

**Comment by craigh** [comment]
Greetings. Yes, the problem is now **fixed**, although a simple `composer update` was insufficient. I had to delete the `vendors/symfony` directory to force the re-download of `symfony/contracts` (since the version number was the same, it kept using the local cache)

**Comment by nicolas-grekas** [comment]
Oh, OK. Thanks for the report and the useful details.
