### ISSUE TITLE
[ServiceSubscriber] Method "getSubscribedServices()" is not inheritable

### ISSUE THREAD

**Issue by thled** [symfony/symfony#36741]
**Symfony version(s) affected**: 4.4.7

**Description**  
The "Service Subscribers" pattern does not work if I define the `getSubscribedServices()` method in the parent class.

**How to reproduce**
Given the following code example:
```php
abstract class AbstractFoo implements ServiceSubscriberInterface
{
    /** @var ContainerInterface */
    protected $locator;

    public static function getSubscribedServices(): array
    {
        return [ObjectManager::class];
    }

    final public function persistEntity($entity): void
    {
        $manager = $this->locator->get(ObjectManager::class);
        $manager->persist($entity);
    }
}

final class Foo extends AbstractFoo
{
    public function __construct(ContainerInterface $locator) {
        $this->locator = $locator;
    }
}
```
If I would call something like `$foo->persistEntity($newEntity);` (given `$foo` is an instance of `Foo`) it fails because `$manager` is `null`.
It works if I have the `getSubscribedServices()` method in the class `Foo`.

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by thled** [comment]
Sorry there is no such bug! I just debugged the wrong way for the whole day..Sry!
