### ISSUE TITLE
symfony/messenger: Tests/ directory went missing after symfony update from 4.3.11 -> 4.4.8

### ISSUE THREAD

**Issue by xtothea123** [symfony/symfony#36752]
**Symfony version(s) affected**: symfony/messenger ^4.4

**Description**  

(not sure if composer or symfony repository issue)

The `Tests` directory of my symfony/messenger dependency goes missing after an update from `symfony 4.3` to `^4.4`

**How to reproduce**  
In my specific case i was just switching the composer version for some packages from `4.3.*` to `4.4.*`
After clearing `composer cache`  and running `composer update symfony/messenger`
these components were updated:

```

diff --git a/composer.json b/composer.json
index 2ac12a6..35061a6 100644
--- a/composer.json
+++ b/composer.json
@@ -13,10 +13,10 @@
   },
   "require": {
     "php": "^7.3",
-    "symfony/http-kernel": "4.3.*",
-    "symfony/dependency-injection": "4.3.*",
-    "symfony/config": "4.3.*",
-    "symfony/messenger": "4.3.*",
+    "symfony/http-kernel": "4.4.*",
+    "symfony/dependency-injection": "4.4.*",
+    "symfony/config": "4.4.*",
+    "symfony/messenger": "4.4.*",

```

```
- Updating symfony/http-foundation (v4.4.8 => v5.0.8)
- Installing symfony/var-dumper (v5.0.8):
-  Installing symfony/error-handler (v4.4.8)
- Updating symfony/http-kernel (v4.3.11 => v4.4.8):
- Updating symfony/service-contracts (v1.1.8 => v2.0.1):
- Updating symfony/dependency-injection (v4.3.11 => v4.4.8)
- Updating symfony/filesystem (v4.4.8 => v5.0.8):
- Updating symfony/config (v4.3.11 => v4.4.8):
And
  - Updating symfony/messenger (v4.3.11 => v4.4.8): Downloading https://api.github.com/repos/symfony/messenger/zipball/518595aaf10a177623685be49b585c09e96aedc3
Downloading (connecting...)
Following redirect (2) https://codeload.github.com/symfony/messenger/legacy.zip/518595aaf10a177623685be49b585c09e96aedc3
Downloading https://codeload.github.com/symfony/messenger/legacy.zip/518595aaf10a177623685be49b585c09e96aedc3
```

When i switch back to 4.3, the Tests file is back.
When i download the symfony package via one of those links directly the Tests dir is also missing.

**Possible Solution**  
--
**Additional context**  
If im completely wrong in here, please provide a place where i can get help with this issue.

**Comment by linaori** [comment]
The Test directories have been removed from the dist version: see #33579. The tests should not be part of your dependencies.

If you want to get the tests back, you can install the source variant by using `composer install --prefer-source` 

Status: reviewed

**Comment by xabbuh** [comment]
This was done on purpose as explained by @linaori. So I am going to close here.
