### ISSUE TITLE
lint:container says that array is passed as 3rd argument to addListener, when it is an int

### ISSUE THREAD

**Issue by kojidev** [symfony/symfony#36750]
**Symfony version(s) affected**: 5.0.8

**Description**  
I'm using sentry/sentry-symfony:3.5.0 (latest). When I run `php bin/console lint:container -e prod`
it complains that I'm trying to pass array value to int argument, and doesn't say where, thru debugging I figured it complains about sentry registering a listener, but parameter that sentry tries to pass is an integer, but gets reassigned to array here: https://github.com/symfony/dependency-injection/blob/b9f508fd25012361565ed6ad77600ad2ba64592c/Compiler/CheckTypeDeclarationsPass.php#L202

**How to reproduce**  
Reproducer: https://github.com/kojidev/lint-repr

**Possible Solution**  
I'm not familiar with symfony/di implementation, so Idk how to go about fixing it.

**Additional context**  
For some reason it only happens in prod environment, even tho it doesn't seemed that sentry configures itself any different in either environment

**Comment by R11baka** [comment]
Hi! Tested on @kojidev  reproducer. I can confirm this behavior!
status: reviewed

**Comment by nicolas-grekas** [comment]
@fancyweb maybe?

**Comment by fancyweb** [comment]
@nicolas-grekas You can close, it was fixed by https://github.com/symfony/symfony/pull/37193.
