### ISSUE TITLE
[Messenger] Doctrine transport requires sender and receiver to use the same time zone 

### ISSUE THREAD

**Issue by jlekowski** [symfony/symfony#36769]
**Symfony version(s) affected**: 4.4, 5.0, 5.1

**Description**  
To add and fetch record from DB (doctrine+postgres in my case) Messenger uses `$now = new \DateTime();` for `created_at, available_at, delivered_at`. That uses sender/consumer default time zone, so when they differ, messages might be consumed before/after intended time.

**How to reproduce**  
1. Configure doctrine transport (with postgres in my case)
2. Run consumer with `date_default_timezone_set('Etc/GMT');`
3. Run sender with `date_default_timezone_set('Etc/GMT+1');` and delay message for an hour `new DelayStamp(60*60*1000);`
4. Message is consumed instantly (it is delayed when using redis transport)

**Possible Solution**  
* Replace `$now = new \DateTime()` with `$now = new \DateTime('now', new \DateTimeZone('UTC'));`
* Add TZ config and documentation to use the same TZ in sender/consumer

**Additional context**  
I only tested it using postgres DB. Redis seemed to be immune to TZ changed.

**Comment by Nyholm** [comment]
Thank you for this. It is good practice to always run your servers in UTC timezone. 

This bug is caused when you have two servers with different timezones that is sharing a database. Correct? 
(Or if you are changing timezones during a php process)

**Comment by jlekowski** [comment]
>It is good practice to always run your servers in UTC timezone.

I agree.

> This bug is caused when you have two servers with different timezones that is sharing a database. Correct?

Yes, that's the case. I only noticed that because I was sending the message from an API running on docker (with UTC timezone), but I was consuming it on my machine (which has the local time set).

**Comment by Nyholm** [comment]
Im not sure if this is important to fix. 

You possible solution will work, but we also need to consider the upgrade path for users. We could possibly add a note on the documentation. But Im leaning towards closing this issue with no change.

**Comment by jlekowski** [comment]
>Im not sure if this is important to fix.

Personally, I find it a low priority one. The fix seemed to be pretty straightforward (to me), but It is up to you guys. I won't feel offended regardless of your approach.

**Comment by Nyholm** [comment]
I appreciate that you opened this issue. Im just sorry that I didn't see it until now. 

I've opened https://github.com/symfony/symfony-docs/issues/15004 to ask the docs team for their opinon. 

Thank you

**Comment by Dallas62** [comment]
Hi @Nyholm 
I don't understand why this issue is closed ?

The solution assume that we have the control of the timezone.
In my case, I don't have choice of the timezone of the producer, which leads to a delay of 2 hours (MySQL).

I can change the TZ of the producer to fix this, but the right solution should be to store the TZ inside the `available_at` then compare the result should works.

Did I miss something ?

**Comment by Nyholm** [comment]
It was discussed that if you have two machines using the same database, then you should be running them at the same timezone. It is even good practice to always run your machines in UTC. 

We solved this issue with explicit documentation about this scenario: https://github.com/symfony/symfony-docs/pull/15055

**Comment by Dallas62** [comment]
I saw the change on the documentation.

I work with a mobile application across continents and I take care of the timezone to avoid wrong behaviour to users, this is works well.
And today, I'm really surprise that a producer and a consumer can't work when the timezone is well defined.

I can hear that TZ miss-configured might have issue, but in 2021 we should not take the easy solution of: "use the same timezone".

I'm a developer I can hear that, but imagine you have to say to a user: "Change the timezone of your phone to not receive your notification at night".

**Comment by Dallas62** [comment]
The solution should be to store the datetime using the same TZ, without impact the configuration at system.

**Comment by Nyholm** [comment]
> this is works well.

... 

That is not really what Im suggesting. The machines should all run in UTC, but you should (in the application layer) make sure the users get their notifications on the correct time according to their timezone.

**Comment by Dallas62** [comment]
> > this is works well.
> 
> ...
> 
> That is not really what Im suggesting. The machines should all run in UTC, but you should (in the application layer) make sure the users get their notifications on the correct time according to their timezone.

As mentioned in the first comment, you don't always have the control of the timezone at system.

**Comment by fritzmg** [comment]
This is also an issue when the PHP CLI has a different time zone set than the Symfony application itself. e.g. the application might excecute

```php
date_default_timezone_set('Europe/Vienna');
```

causing the messages to be stored in the UTC+1 timezone - but `bin/console messenger:consume` might run with PHP's default `UTC` timezone, causing the messages to not be consumed for an hour.

> It is good practice to always run your servers in UTC timezone.

Regardless of what your server is run at - the application might use a different timezone (in order to display timestamps correctly).
