### ISSUE TITLE
Symfony / ORM adds extra queries during hydration causing n+1 problem with "normal" one to one and self-referenced relations

### ISSUE THREAD

**Issue by sabat24** [symfony/symfony#36760]
**Symfony version(s) affected**: 4.4.7

**Description**  
`News` are related to each other using one-to-many self-referencing approach (one news is parent and can have many children). What's more each `News` has got normal one to one relation with `Event` and `Gallery` . When I run simple DQL

```sql
SELECT n FROM App\Entity\News n WHERE n.publishAt <= CURRENT_TIMESTAMP() AND n.parent = :id ORDER BY n.publishAt DESC" 
```

and hydrate results by `getResults` method with default `HYDRATION_OBJECT` value set, extra queries are made somewhere inside `getResults` method. 

```
SELECT t0.* FROM event t0 WHERE t0.news_id = 2 AND ((t0.deleted_at IS NULL));
SELECT t0.* FROM gallery t0 WHERE t0.news_id = 2 AND ((t0.deleted_at IS NULL));
SELECT t0.* FROM event t0 WHERE t0.news_id = 1 AND ((t0.deleted_at IS NULL));
SELECT t0.* FROM gallery t0 WHERE t0.news_id = 1 AND ((t0.deleted_at IS NULL));
```
Where `news_id = 1` and `news_id = 2` are children of news selected by first query. 

`News` has got also not self-referenced one to many relations (I ignored them here), but hydration make no extra queries about them. The problem occurs only when there is `parent` relation involved in `where` statement. 

**How to reproduce**  
```
// news Entity
/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @ORM\Table(uniqueConstraints={@UniqueConstraint(name="news_slug_deleted", columns={"slug","deleted_at"})})
 */
class News {
use SoftDeleteableEntity;
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
/**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128)
     */
    private $slug;
/**
     * @ORM\OneToOne(targetEntity="App\Entity\Gallery", mappedBy="news", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var Gallery
     */
    private $gallery;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Event", mappedBy="news", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var Event
     */
    private $event;
    /**
     * One News has Many News.
     * @ORM\OneToMany(targetEntity="News", mappedBy="parent")
     */
    private $children;

    /**
     * Many News have One News.
     * @ORM\ManyToOne(targetEntity="News", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true)
     * @ORM\OrderBy({"publishAt" = "ASC"})
     */
    private $parent;
}
```

```
/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @Gedmo\SoftDeleteable()
 */
class Event
{
    use SoftDeleteableEntity;
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\News", inversedBy="event", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $news;
```

`Gallery` entity is simmilar to `Event` so I ignored it here.

```
// News controller

public function index(NewsRepository $newsRepository, $slug)
{
        $news = $newsRepository->findOneBy(['slug' => $slug]);
        $newsRepository->getConnectedNews($news->getId());
}
```

```
// news repository

class NewsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, News::class);
    }
    public function getConnectedNews($newsId) {
        $query = $this->createQueryBuilder('n')->andWhere('n.parent = :id')->setParameter('id', $newsId);
        return $query->getQuery()->getResult(AbstractQuery::HYDRATE_OBJECT);
    }
}
```

If I run the last query using as ID news which has got 20 children I end up with: 20 * 2 + 1 (n*r+1) queries in profiler, where:
(n) 20 is the number of children
(r) 2 is the number of one to one relations
1 is the basic query

I'm not sure if it's a bug or maybe I do something wrong, but I didn't find any solution or explanation how to deal with such queries with self-referenced relations and other one to one relations to not trigger extra queries.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by sabat24** [comment]
I see but I don't think that I need a support. I think it's some kind of Doctrine bug (or at least an unwanted behaviour) with hydrating objects when entity has got one to one relations and self-reference relation.
