### ISSUE TITLE
[Intl]  Countries does not include "AN", "ANT", Antilles

### ISSUE THREAD

**Issue by crayner** [symfony/symfony#36768]
**Symfony version(s) affected**: 5.0.8

**Description**  
The Intl lists does not include Antilles

**How to reproduce**  
N.A.

**Possible Solution**  
Add Antilles to package

**Additional context**  
Am building a linked IDD Phone list, so AN = 599.. Other codes also missing.

**Comment by ro0NL** [comment]
See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Transitional_reservations + https://en.wikipedia.org/wiki/List_of_country_calling_codes#+599

**Comment by crayner** [comment]
Hi ro0NL,
   Wikipedia is out of date with the standard, and should NOT be used as a reference. See [https://www.iso.org/obp/ui/#iso:code:3166:AN](https://www.iso.org/obp/ui/#iso:code:3166:AN) which is the standard.  Wikipedia also does not show IDD Code so [https://countrycode.org/netherlandsantilles](https://countrycode.org/netherlandsantilles) for more accurate information.

So, as stated in the bug:
AN ANT Antilles is missing from Intl Lists. in Symfony,  They appear in these references

**Comment by ro0NL** [comment]
https://www.iso.org/obp/ui/#iso:code:3166:AN 

> Status Transitionally reserved

That's the same status as wikipedia; our list of countries contains only officially assigned country codes.

"country dial-in codes" is currently not provided by the Intl component, so those are a bit out-of-scope anyways, but following my previous reference (https://en.wikipedia.org/wiki/List_of_country_calling_codes#+599), it explicitly mentions

> +599 – Former  Netherlands Antilles, now grouped as follows:

which matches with https://countrycode.org/netherlandsantilles as it doesnt mention any "national dial codes" (e.g. 599 on itself), only "city dial codes" (e.g. 599-7 bonaire)

**Comment by crayner** [comment]
Thanks.  I am writing the phone part, and I don't expect Symfony to provide that code.   The site does clearly give the idd code ,
![Annotation 2020-05-09 161951](https://user-images.githubusercontent.com/918953/81465926-10ab9100-9211-11ea-9714-4db2906007e1.gif)

 I understand from your reply that the Countries data supplied by Symfony does not include Transitional reservation from the International Standard Organisation 3166 List.  Fair enough, I will bypass in my Phone Code.  Too bad if you live in Antilles and you wish to use Symfony.

**Comment by ro0NL** [comment]
@crayner Antilles is divided into smaller regions (countries), please see https://www.iso.org/obp/ui/#iso:code:3166:AN

> The Netherlands Antilles was divided into Bonaire, Saint Eustatius and Saba (BQ, BES, 535), Curaçao (CW, CUW, 531) and Sint Maarten (Dutch part) (SX, SXM, 534).

country codes `BQ, CW, SX` are provided by Symfony.

**Comment by crayner** [comment]
Thanks. Will follow up.

**Comment by crayner** [comment]
Thanks for the detail.  Unfortunately, the cities of Bonaire, Saint Eustatius and Saba (BQ, BES, 535), share an ISO-3166 code, but do NOT share a Phone IDD Code.  So I will stick with the AN, ANT, Antilles for my PhoneCode class.
