### ISSUE TITLE
[Mime - Email] - Symfony\Component\Mime\Email::setHeaderBody() must be an instance of object

### ISSUE THREAD

**Issue by elionaimc** [symfony/symfony#36767]
**Symfony version(s) affected**: 5.0

**Description**  
It is throwing *"Return value of Symfony\Component\Mime\Email::setHeaderBody() must be an instance of Symfony\Component\Mime\object, instance of Symfony\Component\Mime\Email returned"* error when using this component in a Slim 4 application.

**How to reproduce** 

```php
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

final class UserMailer
{
    /**
     * @var MailerInterface
     */
    private $mailer;

    public function __construct(MailerInterface $mailer)
    {
        $this->mailer = $mailer;
    }

    public function sendEmail()
    {
        $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>My HTML content</p>');

        $this->mailer->send($email);
    }
}
```

**Possible Solution**  
Changing the expected return signature of method bellow:
```php
private function setHeaderBody(string $type, string $name, $body): object
{
//
}
```
To the following:
```php
private function setHeaderBody(string $type, string $name, $body): self
{
//
}
```

**Comment by nicolas-grekas** [comment]
Thanks for the report. This error means you didn't use PHP 7.2 to run the code but 7.1 or maybe 7.0. If you use PHP 7.2 or higher, it will work as expected.
The supported version of PHP is declared in the composer.json file, please have a look.
