### ISSUE TITLE
[Messenger] Doctrine transport does not guarantee FIFO message order

### ISSUE THREAD

**Issue by jlekowski** [symfony/symfony#36770]
**Symfony version(s) affected**: 4.4, 5.0, 5.1

**Description**
Doctrine transport does not guarantee FIFO order when messages have the same `available_at` value.
When using postgres 9.5 (sorting was "correct" in postgres 10) and running `SELECT * FROM messenger_messages ORDER BY available_at ASC` messages with the same `available_at` are not sorted by `id` (primary key). Using redis transport it was always FIFO for me.

**How to reproduce**
1. Configure doctrine transport with postgres 9.5
2. Add at least 2 messages one after another (so that they have the same `available_at`)
3. Run consumer (e.g. with `limit 1`)
4. Message with higher id is consumed (first)

**Possible Solution**
Add ordering by id https://github.com/jlekowski/symfony/commit/906d9daf5cdf4426e77837b508e0d4a2db77c64c

**Additional context**
Reproduced using postgres 9.5. Working as expected when using postgres 10 and redis.

**Comment by fabpot** [comment]
No transport should guarantee FIFO. You should not rely on message ordering (that's very important when you are using retries for instance).

**Comment by xabbuh** [comment]
I am closing here as there is no bug as explained.
