### ISSUE TITLE
dump() not working

### ISSUE THREAD

**Issue by BernardA** [symfony/symfony#36772]
**Symfony version(s) affected**:4.13.3

**Description**  
dump() outputs nothing
var_dump() does

**How to reproduce**  
I installed: 

>        composer require --dev symfony/var-dumper
>        composer require --dev symfony/debug-bundle
> 

Then: 

>         var_dump($rootAlias); // this outputs
>         dump($rootAlias); // no output 

I tried dumping both to `Postman` and to `/localhost/api/graphql`

**Possible Solution**  

**Additional context**  
Only note that this is an API-Platform app

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by BernardA** [comment]
Hmm... not sure how to create a small application out of this. I do have a repository but it is private as it happens. 

Would help if I provide composer.json? 

      {
    "type": "project",
    "license": "proprietary",
    "name": "bernard/quiamo-api",
    "description": "small ads app",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/api-pack": "^1.2",
        "gesdinet/jwt-refresh-token-bundle": "^0.7.1",
        "google/apiclient": "^2.0",
        "lexik/jwt-authentication-bundle": "^2.6",
        "sensio/framework-extra-bundle": "^5.4",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/amazon-mailer": "4.4.*",
        "symfony/console": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "^4.0",
        "symfony/google-mailer": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/mailer": "4.4.*",
        "symfony/monolog-bundle": "^3.4",
        "symfony/orm-pack": "^1.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/yaml": "^4.0",
        "vich/uploader-bundle": "^1.10",
        "webonyx/graphql-php": "^0.13.8"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.3",
        "fzaninotto/faker": "^1.8",
        "symfony/debug-bundle": "4.4.*",
        "symfony/maker-bundle": "^1.13",
        "symfony/profiler-pack": "^1.0",
        "symfony/var-dumper": "4.4.*",
        "symfony/web-server-bundle": "4.4.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    }
    }

After that I have created a `DefaultController` only to test this as so;

        /**
    * @Route("/", name="default_index")
    */
    public function index(Request $request)
    {
        $data = $request->getContent();
        $data = json_decode($data, true);
	$this->adRepo = $this->em->getRepository(Ad::class);
	$result = $this->adRepo->getAdGroupbyCategory();
        var_dump('vardump', $result);
        dump('dump', $result);
        return $this->json([
            'result' => $result,
            'data' => $data,
        ]);
    }

If I try to access `localhost/` it will output 

      string(7) "vardump"
        array(5) {
          [0]=>
            array(2) {
               ["id"]=>
                 int(6144)
          [1]=>
             string(2) "95"
         }
        [1]=>
           array(2) {
            ["id"]=>
             int(6140)
              [1]=>
            string(2) "74"
         }
      ....
There's no output from `dump()`

**Comment by xabbuh** [comment]
If these code parts allow to reproduce your issue, please create a fully working example application from that. I am afraid that you would have to debug the issue yourself otherwise.

**Comment by BernardA** [comment]
I can keep on just fine with var_dump()

**Comment by ZdravkoZaprev** [comment]
Profiler block dump from executing
