### ISSUE TITLE
UrlGeneratorInterface::NETWORK_PATH generate wrong url

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#36781]
It is generate url with `//` prefix. It is ok for local resource loading, but if I want to pass "callback url" to some api it is bad of cause

**Comment by xabbuh** [comment]
I am afraid I that I do not fully understand your issue. Can you please provide some concrete example and explain what you did expect to happen and what happened instead?

**Comment by zorn-v** [comment]
If you use somethig like
```php
public function __construct(UrlGeneratorInterface $urlGenerator)
{
    $this->callbackUrl = $urlGenerator->generate('callback_route', [], UrlGeneratorInterface::NETWORK_PATH);
}
```
It will generate url like `//my-domain.com/callback`
It is ok for include to html for js/css loading, but not for pass urls to external system.

**Comment by xabbuh** [comment]
Can you explain why you pass `UrlGeneratorInterface::NETWORK_PATH` then instead of `UrlGeneratorInterface::ABSOLUTE_URL`?

**Comment by xabbuh** [comment]
In any case, this does not look like a bug to me so I am closing here. Thank you for understanding.
