### ISSUE TITLE
A strange mistake, no correct prompt

### ISSUE THREAD

**Issue by 441211324** [symfony/symfony#36787]
Let me describe the process of this problem. After several business code submissions, I didn't clear the cache file. After I clear the cache file again, I find that the whole project can't be opened, and the interface only shows:

www.xxx.com/app_dev.php

HTTP ERROR 500

In various attempts, I began to seriously think about this problem. The cache file was not completely generated. Compared with the history, it may have generated a part of it. Later, I returned several business versions and found the problem.

public function testpaperSubmitAction(Request $request)
{
      if (1isset($fromData['courseId'])) {
       }
}

In fact, when the code is submitted, no code is found  **isset()**  One more number in front 1。

It's strange that no error is reported. The access program is，**HTTP ERROR 500**，I can hardly find out what caused the error。

--------------------------------------------------------------------------
isset()     !isset()     **1isset()**

In the shortcut, if shift is not pressed, 1 will appear

**Comment by stof** [comment]
Well, `HTTP ERROR 500` *is* reporting an error. Then, to get more details about errors, check how you configured your PHP runtime to log fatal errors. Symfony cannot really do anything for them (they are fatal).

**Comment by chalasr** [comment]
Closing as explained, this is not a Symfony bug.

**Comment by 441211324** [comment]
very thanks!
