### ISSUE TITLE
Add an option to fail tests when a translation is missing.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#36792]
**Description**  
I don't see a lot to say about this idea ;
The webProfiler currently reports the missing translations. But I never heard about an option to report these missing translations as error when running functional tests.

**Comment by arodiss** [comment]
One way to implement this is to add CLI command that return non-zero code if there are missing translations (and outputs some info).
The end user can add this command to his CI pipeline

**Comment by xabbuh** [comment]
When using the standard functional `KernelTestCase` setup, you can enable the profiler and at the end of your test you can check the translation data collector for the number of missing translations. This would need some polishing of course if you wanna use this in every single functional tests. I am just not sure if the use case is common enough to be part of the Symfony core.
