### ISSUE TITLE
Symfony Process - "mv" command

### ISSUE THREAD

**Issue by mistris** [symfony/symfony#36801]
**Symfony version(s) affected**: 5.0.7

**Description**  
Symfony Process doesn't execute `mv` command if there is `/*` at the end of source directory:

```
$process = new Process(['mv', '/var/tmp/test/*', '/var/shared']);
$process->start();

foreach ($process as $type => $data) {
    if ($process::OUT === $type) {
        dump("Read from stdout: ".$data);
    } else { // $process::ERR === $type
        dump("Read from stderr: ".$data);
    }
}
```

**Output:**
```
Read from stderr: mv: can't rename '/var/tmp/test/*': No such file or directory
```

Both directories (source `/var/tmp/test/` and target `/var/shared`) exist.
Directory `/var/tmp/test/` contains files and sub-directories.

If I try to move the whole `test` directory, it works:
```
$process = new Process(['mv', '/var/tmp/test', '/var/shared']);
```

But it also moves the `test` directory that I don't need. I need to move only the content (files and directories) of `/var/tmp/test` directory.

If I call `exec('mv /var/tmp/test/* /var/shared')` instead, it works as expected, but I would like to use the Symfony Process.

**Comment by R11baka** [comment]
Thank you @mistris . I've reproduced this bug! here is skeleton https://github.com/R11baka/symfony_36801_reproducer
For reproduce this bug run create test directory in your temp folder.
`mkdir /tmp/test/;touch /tmp/test/1.out;mkdir /tmp/1;` and run console command
`php bin/console test:mv`.
as I understand in vendor/symfony/process/Process.php line 300
commandline equals `exec 'mv' '/tmp/test/*' '/tmp/1'` and after that error

**Comment by derrabus** [comment]
This is expected behavior. If you create a process via the constructor, all arguments are escaped as strings which means that you cannot use a glob here that the shell needs to expand.

Instead, you can use the following expression to create a process that does what you want.

```php
Process::fromShellCommandline('mv /var/tmp/test/* /var/shared')
```
