### ISSUE TITLE
[Form] Empty string gets converted to null

### ISSUE THREAD

**Issue by yyaremenko** [symfony/symfony#36815]
**Symfony version(s) affected**: 4.4.7

**Description**  
```Empty string``` gets converted to ```null``` if form config has no view transformers. Further, when this value is passed to validator, the validation does not run properly, as, for instance, ```LengthValidator``` treats ```empty string``` and ```null``` in a different way.

**How to reproduce**  
1. Create a form with field
```
$builder
    ...
    ->add('title', TextType::class)
    ...
```
2. Create a controller, submit this form with data
```
['title' => '']
```
3. In Symfony\Component\Form\Form::submit(), before ```return```, add the following code
```
var_dump($this->modelData);
var_dump($this->normData);
var_dump($this->viewData);
die;
```

**Expectation:**
```
string(0) "" // model data
string(0) "" // normalized  data
string(0) "" // view data
```

**Reality:**
```
NULL // model data
NULL // normalized  data
string(0) "" // view data
```

**Problem source**
Form::viewToNorm()
```
    private function viewToNorm($value)
    {
        if (!$transformers = $this->config->getViewTransformers()) {
            return '' === $value ? null : $value;
        }
...
```
Model Data gets constructed based on Norm Data, and later on Model Data is retrieved by calling ```Form::getData()``` in ```Symfony\Component\Form\Extension\Validator\Constraints\FormValidator::validate()```

**Possible Solution**  
Probably fix this? And write test validating the fix.

**Comment by xabbuh** [comment]
This is expected. You can set the `empty_data` option to the empty string if you like to always get a string. I am closing here as there is nothing to fix.
