### ISSUE TITLE
Task Scheduling / Cronjobs Configuration Inside Framework

### ISSUE THREAD

**Issue by checkphi** [symfony/symfony#36821]
**Description**  
A scheduled task in symfony is usually a command that is called from an external scheduling system, for example the linux cron system. While this has its advantages, it also has the drawback that the configuration is not in source control or at least at a different location.

Other frameworks, for example Laravel (https://laravel.com/docs/7.x/scheduling) solved this in a simple way. There is only one cronjob to be configured with the lowest period (every minute) that calls a central command. This command detects all commands that have a scheduling configuration an executes them if necessary.

**Example**  
See https://laravel.com/docs/7.x/scheduling

**Comment by javiereguiluz** [comment]
Thanks for your suggestion!

Currently we have:

* A pending pull request in this repo to add a new Scheduler component (https://github.com/symfony/symfony/pull/35315)
* A recently released bundle that is similar to the library you referred: https://github.com/zenstruck/schedule-bundle

**Comment by raziel057** [comment]
It would be great to allow the execution of jobs from a specific route (for scalability purposes). It would allow tasks to run only once when deploying on multiple nodes. Generally I create a specific JobRunnerController to manage that.

**Comment by Guikingone** [comment]
Hi @raziel057 👋 

In the PR listed by Javier, that's already implemented: https://github.com/symfony/symfony/blob/09db4c3314159dbf6b67ee426b6dab2d8e146f9a/src/Symfony/Component/Scheduler/EventListener/TaskSubscriber.php

**Comment by raziel057** [comment]
Oh yes that’s great thank you!

**Comment by Guikingone** [comment]
Hi @raziel057 and @checkphi 👋 

As you probably notice the PR #35315 has been closed, for now, the Scheduler experimentation is not planned for `5.2` (I don't know for `5.3`), I don't additional have informations for the future of the PR so I recommend you to switch to https://github.com/zenstruck/schedule-bundle (thanks to @kbond) and wait for informations about a dedicated component in the future or a public recipe for Kbond bundle in Symfony flex 🙂 . 

As Symfony 6 is "near to us", maybe the core team will work on a component for the next major version 🙂 . 

Have a great day 👋 

PS: I don't know if @checkphi will receive this message but if not, I think that the issue can be closed for now except if @javiereguiluz has any additional informations 🙂 .

**Comment by fabpot** [comment]
@Guikingone is working on a solution, so I don't think we need to keep this issue open
