### ISSUE TITLE
[HttpClient] Optional content-type check when using ->toArray

### ISSUE THREAD

**Issue by mikelerch** [symfony/symfony#36828]
**Description**  
It can be considered an edge case, but it occasionally happens that an API returns JSON content without the correct content type `application/json`. In this caes `->toArray` will fail and the response body needs to be decoded manually.

```php
$contentType = $this->headers['content-type'][0] ?? 'application/json';

if (!preg_match('/\bjson\b/i', $contentType)) {
    throw new JsonException(sprintf('Response content-type is "%s" while a JSON-compatible one was expected for "%s".', $contentType, $this->getInfo('url')));
}
```

This could be improved by not forcing a content type check, or making it optional.

**Comment by nicolas-grekas** [comment]
We could just remove the content-type check. I don't see any drawback, do you?
Up for a PR, branch 4.4?

**Comment by mikelerch** [comment]
Yeah sure, I'll submit one as soon as possible.

**Comment by nicolas-grekas** [comment]
I'm closing meanwhile. Please submit when you can.
