### ISSUE TITLE
Lazy load for UserInterface's props without 'security' logger channel

### ISSUE THREAD

**Issue by he110** [symfony/symfony#36834]
**Symfony version(s) affected**: 5.0.8

**Description**  
At my `User` class I have a property with ManyToOne relation which is used at `getUsername` implementation of `UserInterface` interface. Maybe it should not be used that way, but it worked well until I disabled **security** channel at my `main` monolog handler.

After disabling **security** channel, my `User` class become unable to get data from mentioned ManyToOne property. It has only `id` field. 

**How to reproduce**  
1. Create `User` class with ManyToOne relation with another Entity and implement `UserInterface`;
2. At the `getUsername` method of your `User` class use **get** method for ManyToOne property;
3. Disable **security** channel for your current environment;
4. Try to login with any possible method.

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by he110** [comment]
I've created a skeleton project to reproduce and everything works fine.
In my project, it still brokes on `security` channel disable.
I'll close that issue and continue researching my case.
