### ISSUE TITLE
RuntimeExceptions should give more detail

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony#36847]
**Symfony version(s) affected**: 5.0 and prior

**Description**  

Various places in the code throw a RuntimeException, but these don't give enough detail. If you're running something that interprets multiple expressions in multiple places, you don't know which one has the problem.

e.g.

```
                    throw new \RuntimeException('Unable to get a property on a non-object.');
```

and others.

**How to reproduce**  

Try to access a property on NULL, e.g. "objectparameter->notaproperty->reallynotgoingtowork"

**Possible Solution**  

Give the full expression that caused the problem, and ideally the variable that caused the problem too.

**Additional context**

**Comment by chalasr** [comment]
PR(s) improving error messages are welcome, we do it constantly.
