### ISSUE TITLE
PHP Preload Segfault with Cache Component

### ISSUE THREAD

**Issue by natewiebe13** [symfony/symfony#36853]
**Symfony version(s) affected**: 4.4, 5.0

**Description**  
When using `Symfony\Contracts\Cache\CacheInterface::get()` with preloading enabled, PHP segfaults.

**How to reproduce**  
I have created a repository and outlined the steps to reproduce here: https://github.com/natewiebe13/php-preload-segfault

It's using the latest version of PHP 7.4

**Comment by nicolas-grekas** [comment]
Similar to #36807 maybe? See https://bugs.php.net/bug.php?id=79603 also
Segfaults should be reported to the php bug tracker since there is nothing we can do about them here.
Thanks for the report.

**Comment by nicolas-grekas** [comment]
See #36328 + https://bugs.php.net/bug.php?id=79548 actually.
