### ISSUE TITLE
WebProfiler toolbar vanishes on 5.1-RC1

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#36854]
**Symfony version(s) affected**: 5.1-RC1

**Description**  
I'm running a dev project on the Symfony 5.1-BETA1 version and the WebProfiler toolbar sticks around on DEV as usual. As soon as I "composer update" to RC1 and reload the page the toolbar is just gone. Directly accessing the profiler shows valid requests. I haven't change anything otherwise.

I have no clue where to start with debugging. Seems the profiler code isn't injected into the response. Will update the post with more details I can find.

**How to reproduce**  
Run BETA1 and update to RC1?

Kind regards
Matthias

**Comment by nicolas-grekas** [comment]
Thanks for the report and for playing fir 5.1. This one is fixed already.

**Comment by althaus** [comment]
Oh... sorry for my bad Search Fu. I've monkey patched the listener and continue using the RC1.

Thanks for your faaast reaction.
