### ISSUE TITLE
[DependencyInjection][FrameworkBundle] Private non-shared services are removed from the test container

### ISSUE THREAD

**Issue by dbrekelmans** [symfony/symfony#36856]
**Symfony version(s) affected**: confirmed on 4.4.4+, but possibly 4.1.1+ (see related issues in additional context)

**Description**  
Private non-shared services are removed from the test container.

IF private non-shared service `x` is injected into service `y` AND the service definition of `x` is replaced by a service reference through a compiler pass THEN the following error occurs in the test environment: `The service "y" has a dependency on a non-existent service "x".` 

**How to reproduce**  
* Check out [reproducer](https://github.com/dbrekelmans/symfony-test-container-bug-reproducer)
* Run `composer install`
* Run `bin/console ca:cl -e test`

The following error occurs: `The service "App\Twig\FooRuntime" has a dependency on a non-existent service "App\Services\FooService".`

This error only triggers in the test environment (dev and prod produce `[OK]`)

**IMPORTANT:** Note that `App\Twig\FooRuntime` goes through compiler pass `Symfony\Bundle\TwigBundle\DependencyInjection\Compiler\RuntimeLoaderPass`due to the class implementing `RuntimeExtensionInterface`. Either removing `implements RuntimeExtensionInterface` or deleting `App\Controller\DefaultController` resolves the issue.

**Possible Solution**  
Disabling `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\TestServiceContainerWeakRefPass` resolves the issue; a solution might be found inside that class.

The following lines in `Symfony\Component\DependencyInjection\Compiler\InlineServiceDefinitionsPass` also seem related.
```
if (!$definition->isShared() && !$definition->isPublic()) {
    $container->removeDefinition($id);
}
```

**Additional context**  
Related issues:
* #27488
* #29628

**Comment by alexislefebvre** [comment]
It looks like it's the expected behaviour: https://github.com/symfony/symfony/issues/30104#issuecomment-461508884

See also https://github.com/symfony/symfony-docs/pull/14819

The blog post was updated too:

> Keep in mind that, because of how Symfony's service container work, unused services are removed from the container. This means that if you have a private service not used by any other service, Symfony will remove it and you won't be able to get it as explained in this article. The solution is to define the service as `public` explicitly so Symfony doesn't remove it.

Source: https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing

---

Update: My bad, the problem is different but the solution of `public: true` could solve this issue.

**Comment by dbrekelmans** [comment]
Thanks for the info @alexislefebvre. Indeed, `public: true` is a workaround, but this is still a bug. In #30104, the service is unused and therefor rightfully removed from the container. In this issue the service **is** used by another service, but still removed from the container. I still believe this is a bug.

Maybe @nicolas-grekas can confirm? If it's expected behavior then I will close the issue.

**Comment by nicolas-grekas** [comment]
I confirm this is a bug somewhere in `TestServiceContainerWeakRefPass`. For some reason, the pass decides to remove the service while it's referenced by lazy edges (a vocabulary found in the pass).

Help wanted if someone wants to dig there.

**Comment by alexislefebvre** [comment]
I tested the reproducer, it was broken as you described. But it worked after `composer update`.

**Comment by nicolas-grekas** [comment]
Great, thanks @alexislefebvre!

**Comment by dbrekelmans** [comment]
Thanks for the quick update both of you!

**Comment by alexislefebvre** [comment]
> Great, thanks @alexislefebvre!

Well, I didn't do much. 🙂

@dbrekelmans did it work for you too after an update?
