### ISSUE TITLE
Arguments in translations don't get replaced with value when translation loaded from file

### ISSUE THREAD

**Issue by simivar** [symfony/symfony#36861]
**Symfony version(s) affected**: 5.0.8

**Description**  
While using a translation with the argument (placeholder) in Twig template the placeholder doesn't get replaced with value if the translation is loaded from a translation file.

I am not sure if that's an actual bug or a limitation of the translation library and/or Twig but I couldn't find any information about that anywhere on the internet. 

For example:
```twig
{% trans with {'%name%': name} %}Hello %name%{% endtrans %}
{{ 'Hello %name%'|trans({'%name%': name}) }}
```

gets printed as:
```
Hello %name% 
```

instead of 
```
Hello simivar
```

**How to reproduce**  
https://github.com/simivar/symfony-translation-issue/commit/473a278a5b93251111ad1d417725b58a51e4325d

**Possible Solution**  

**Additional context**  

**Workaround**
```
{{ 'Hello %name%'|trans|replace({'%name%': name}) }}
```

**Comment by yceruto** [comment]
I think you're missing pass the `%name%` argument to the `trans` filter:
```twig
{{ 'Hello %name%'|trans({'%name%': name}) }}
```
https://symfony.com/doc/current/translation/templates.html

**Comment by xabbuh** [comment]
I am closing here as this does not look like a bug.

**Comment by simivar** [comment]
@yceruto doesn't work as well, I've updated the example: https://github.com/simivar/symfony-translation-issue/commit/d1de82ed553cb8c666f1c89f13ca94e9307be079

![obraz](https://user-images.githubusercontent.com/828020/82259253-8cb57f80-995b-11ea-85c0-594f84e95e27.png)

**Comment by simivar** [comment]
@xabbuh you could have given me some time to answer, it doesn't work. I've committed the wrong example after a few tries.

**Comment by simivar** [comment]
@yceruto I've updated example: [comparsion](https://github.com/simivar/symfony-translation-issue/compare/0b2b455badb9200ccb64f08734f7ad96ecf08e35..0e80b4fa6370f82ab339e73a0ecce12463982892 ).

As you can see the usage is the same but the one below replaces `%name%` with its value and the one above doesn't. It seems to me like this bug or I am not seeing something. 

![obraz](https://user-images.githubusercontent.com/828020/82261199-e9666980-995e-11ea-8e5b-591e065ff9f1.png)

@xabbuh you could have given me some time to respond :/.

**Comment by yceruto** [comment]
Read https://github.com/symfony/symfony/issues/35328

**Comment by simivar** [comment]
Removing `+intl-icu` from filename helped. It is the same bug.

**Comment by xoniq** [comment]
> Removing `+intl-icu` from filename helped. It is the same bug.

This is the way. I had the same issue, did everything by the book, everywhere the %% variables were not replaced. After changing the filename it suddenly works on the whole project.

**Comment by stof** [comment]
If you use the `+intl-icu` suffix in the filename, your placeholders must be in the ICU message format, not with `%` delimiters.
