### ISSUE TITLE
[Mailer] Improve an error message related to Gmail and 2FA

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#36878]
**Description**  
Not sure if it's technically possible or desirable, but when working with Gmail in `dev` environment, we could improve an error message (this is related to https://github.com/symfony/symfony-docs/issues/13686).

This is the error message I got:

```
request.CRITICAL:
Uncaught PHP Exception Symfony\Component\Mailer\Exception\TransportException:
"Expected response code "250" but got code "535", with message
"535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8
https://support.google.com/mail/?p=BadCredentials c17sm2019832wrn.59 - gsmtp"
```

And this other error message would have saved me lots of time and troubles:

```
request.CRITICAL:
Uncaught PHP Exception Symfony\Component\Mailer\Exception\TransportException:
"Expected response code "250" but got code "535", with message
"535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8
https://support.google.com/mail/?p=BadCredentials c17sm2019832wrn.59 - gsmtp"
"If your Gmail account has 2-Factor Authentication enabled, use an App Password
instead of your Gmail password (see https://myaccount.google.com/apppasswords)"
```

**Comment by fabpot** [comment]
Not sure how that could be done. To be honest, Gmail should probably never be used.

In dev, use a webmail catcher (built-in with Symfony CLI) and in prod, use a "real" email provider.

**Comment by javiereguiluz** [comment]
Let me share some details:

* I was developing an app that sends emails
* I used MailHog (https://github.com/mailhog/MailHog) because MailCatcher is much more complex to install and configure
* When I finished, I wanted to send the email for real ... because I wanted to test how it looks on Gmail. This is mandatory ... because it's really hard to make emails look right in real email clients.
* That's why I tried to use Gmail also for sending the email.

So, instead of changing this error message, here are two questions:

* How do people test real emails in real clients?
* Could we make Symfony CLI compatible with MailHog too?

Thanks.

**Comment by fabpot** [comment]
The link in the error message does give hints. In any case, there is no way we can improve the situation here.

Regarding your last comment, mailcatcher does not need any config and when using Docker and Symfony CLI, it's probably much easier than MailHog to install.

Anyway, I'm going to close here as there is nothing we can improve.

**Comment by javiereguiluz** [comment]
Yes, I agree with closing this!

About mailcatcher vs MailHog ... MailHog is a Go binary with zero configuration and no Docker required. That's why I used it instead of mailcatcher.
