### ISSUE TITLE
Run Symfony 3.4+ on PHP 8

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#36872]
Twig has just been made [compatible with PHP 8](https://github.com/twigphp/Twig/pull/3331). The `.travis.yml` trick to run the test suite can be reused on this repo.

Then we'll have some deprecations/failures to take care of.

Is anyone willing to give it a try and make Symfony (3.4 first) compatible with PHP 8?

Todo:
- [x] fix the nighlty job on Travis
- [x] ~allow DBAL v3 once it's ready~ (v2 doesn't allow PHP8, even if it works but in a few edge cases)
- [ ] enable a PHP 8 job using GitHub Action
- [ ] enable skipped extensions on travis' job for nightly
- [ ] remove the 7.4.99 hack from the travis file once deps allow php 8
- [x] remove weak deprecation mode once deps are ready (phpdocumentor)

**Comment by vasilvestre** [comment]
Actual state : 
- Flex support of php8 is needed
- Composer version that work with php 8 is composer 2, a PR to solve flex dependency exist https://github.com/symfony/flex/pull/617
- Here's my try of updating flex php version then https://github.com/symfony/flex/pull/624

**Comment by derrabus** [comment]
> Is anyone willing to give it a try and make Symfony (3.4 first) compatible with PHP 8?

The active support for Symfony 3.4 will most likely end before the final php 8.0.0 release. Do you really aim at 100% compatibility with php 8.0 or do you just want to keep to the diff to the 4.4 branch small? What about components like `ClassLoader` that have been removed in Symfony 4? Do we fix them as well?

I have no strong opinions on this, I'm just curious about your motivation. :smiley: 

Can we already add a php 8 job to the travis configuration that is allowed to fail, so we can monitor the work that is ahead of us? Maybe this is a task that we can split component-wise again, like we did with the parameter types.

**Comment by nicolas-grekas** [comment]
Let's try having PHP 8 in the CI asap. The journey towards this goal will give us the answers to your questions.

**Comment by derrabus** [comment]
One thing that might become a problem is the PHPUnit version that we're using on Travis right now, which is 8.3. IIRC (@sebastianbergmann might want to correct me if I'm wrong), compatibility issues with php 8 will be addressed in PHPUnit 9 only, so if we run into any, we'd be on our own.

I don't want to build too many blockers for this issue, but it might be a good idea to upgrade to PHPUnit 9 first.

**Comment by nicolas-grekas** [comment]
I [made the phpunit-bridge work with PHP 8](https://github.com/symfony/phpunit-bridge/compare/0963625c56a448613006dd54634aa44879a3c1fd..ede4a677e78ae31bd16099f41e2875b11ceb3df2) yesterday so that we can see it in action.

[It works great for Twig.](https://travis-ci.org/github/twigphp/Twig/jobs/689584051), even if phpunit 8.3 is used.

**Comment by derrabus** [comment]
Doctrine is a blocker right now because of doctrine/dbal#3791. Apparently, the issue will be fixed in the DBAL 3.0 branch, but there's no compatible ORM 2.x branch yet. We will need to skip a couple of test because we would run into fatal errors otherwise.

**Comment by derrabus** [comment]
All right, I ran the test suites of all components against a self-compiled php 8 installation with minimal extensions (intl + mbstring, basically) and opened PRs for all low hanging fruits (sorry).

Findings:

* PHPUnit's mock framework suffers from the deprecation of `ReflectionType::getClass()` as well. Those deprecations popped up quite frequently.
* I skipped Process and VarDumper. They're deep red and my knowledge of their internals is a bit limited.
* PHP triggers a deprecation if optional parameter precede a mandatory one in a function signature. While Symfony's actual codebase is not affected by this issue, some fixtures are.

**Comment by heddn** [comment]
Not sure if this is the right place, but over in https://www.drupal.org/project/drupal/issues/3109885 we're starting to run Drupal's test suite against PHP 8. And the first issue seems to be a need to bump the composer.json to allow for PHP 8.

See https://www.drupal.org/pift-ci-job/1745432

**Comment by wouterj** [comment]
This has already been done for all symfony packages. 4.4.10 also includes this bump, for some reason the output you're showing installs 4.4.9. So seems like there are some very strict version constraints somewhere?

Something that may help Drupal, Symfony is faking as if PHP 7.4.99 is installed in the PHP 8 test run, to prevent all these errors:
https://github.com/symfony/symfony/blob/659699b9cea9dbb612a400bef9d27ccdd95f949f/.travis.yml#L257-L261

**Comment by heddn** [comment]
Thanks for the info about the minimum version. We don't really want to fake things though, as we want to make sure that folks can in fact run on PHP 8. We do have another test run that ignores platform requirements too. This is just catching all the composer issues.

**Comment by derrabus** [comment]
The test of the Debug component currently fail because of a Composer bug. I've submitted composer/composer#9183 to fix it.

**Comment by derrabus** [comment]
I think, we can close this issue. 😉
