### ISSUE TITLE
Constraints GreaterThan, LessThan detect/allow to change format for variable {{ compared_value }}

### ISSUE THREAD

**Issue by hracik** [symfony/symfony#36887]
Constraints like GreaterThan, LessThan (and similar ones) can compare dates/times, but in the violation message there is fixed format for variable {{ compared_value }} 'Y-m-d H:i:s' which looks weird to display value "1. 1. 1970, 10:10" when comparing just times in format "H:i". Same way is weird to display time there when comparing just dates.

If it is possible to detect format of values being compared then would be great to keep it. If not then make optional variable "format" where format can be specified.

**Comment by xabbuh** [comment]
Thank you for suggesting this feature. I am still closing here as it looks like we already have an open issue for this (see #36784). Thank you for understanding.
