### ISSUE TITLE
[Messenger] Consume batch of messages (manually, instead of worker), consuming multiple messages at once, BULK message processing at once

### ISSUE THREAD

**Issue by vgrankin** [symfony/symfony#36910]
Greetings! I can't believe it but i can't find any information regarding this trivial use-case. I am currently reacting to RabbitMQ messages in MyConsumer::consume() method, but i don't want to process these messages immediately 1 by 1, so i decided to use Messenger to dispatch/put them in MySQL table using Doctrine transport to process some BATCH of them later. 
I want to process multiple messages of one class type at once, as a group. I have some reasons for it. For example to avoid multiple network requests for each message and instead perform 1 request of 10 messages (for example).

So everything looked good until I realised that I still have the same problem. Messenger's worker consumes 1 message at a time. I can not consume a BATCH of messages AT ONCE using default Worker. Like I don't have control over manually pulling the ones I want and acknowledging/rejecting them as a group.

This is a disaster! I really want functionality of Messenger, like putting messages to failed queue in case of fail of delivery for several times etc.. But I want to process messages for some class type in BULK, acknowledge them after ALL messages in the batch are handled/processed or reject all of them. Also, there is no way i can group these messages in advance. I can do it only at a later stage, when messages ended up in the messenger_messages table.

More precisely: messages are coming. I want to put them into mysql table. Then I have a cron which will run let's say every 10 minutes. In this cron i want to iterate over all messages of some type, aggregate some data into 1 object of my interest which i will then try to send over the network. If this fails X times (server is down, whatever), I want to put all messages in this iteration to failed queue and at some point try again for some amount or all of these failed messages.

Is there any way around this? Or should I write a custom worker for this? What i need is more like a cron which processes batches, not a 1 by 1 message listener/worker. Here is a prototype of what I mean if Worker was processing in BULK, hope it makes sense:

```php
foreach ($this->receivers as $transportName => $receiver) {
	$envelopes = $receiver->get();

	foreach ($envelopes as $envelope) {
            if ($envelope->getMessage() instanceof \App\Message\Entities\LuckyEntity) {
	        $data      = $this->extractPartialData($envelope);
	        $this->fullData->append($data);
            }
	}

	try {
	    $this->process($this->fullData);
	} catch (\Exception $e) {
	    $this->rejectAll($envelopes);
                
	    return;
	}
            
	$this->ackAll($envelopes);
```
Also I tried to investigate how messages are transported to the queue (mysql table) and thought of kinda joining data to 1 row instead of creating multiple rows, so to later extract multiple messages from 1 row in a table, but currently it doesn't look like a trivial task. Also thought about custom Worker.. or maybe some intermediate stage, which aggregates/rearranges rows in the queue..

**Comment by Tobion** [comment]
Can't you just write a message handler that collects several messages in memory and then batch processes them? I don't see the problem.

**Comment by vgrankin** [comment]
Actually ended up doing something similar by creating intermediate queue + command which groups messages and then dispatches them to another queue as a "grouped" message. This way process is fully delegated to Messenger. But as I said, would love to avoid to invent this bicycle and having this feature in the library instead.

Thanks fur suggestion anyway!

**Comment by sstok** [comment]
You mean something like this?

```

use Symfony\Component\Messenger\MessageBusInterface;

final class BatchCommandHandler
{
    /** @var MessageBusInterface */
    private $commandBus;

    public function __construct(MessageBusInterface $commandBus)
    {
        $this->commandBus = $commandBus;
    }

    public function __invoke(BatchCommand $batch): void
    {
        foreach ($batch->commands as $command) {
            $this->commandBus->dispatch($command);
        }
    }
}

/**
 * Allows to combine multiple Commands into a single transaction.
 */
final class BatchCommand
{
    /**
     * READ-ONLY.
     *
     * @var object[]
     */
    public $commands;

    public function __construct(object ...$commands)
    {
        $this->commands = $commands;
    }
}
```

Or am I misunderstanding 😅

**Comment by vgrankin** [comment]
Here is a minimal implementation, hope it helps :)

```
# your .env
MESSENGER_TRANSPORT_DSN=doctrine://default
```

```
# config/packages/messenger.yaml
framework:
  messenger:
    failure_transport: failed

    transports:
      aggregatables:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          table_name: messenger_aggregatables
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed: 'doctrine://default?queue_name=failed'

    routing: # specifying what goes where
      'App\Message\Consumer\Entities\ProductsEntity': aggregatables
      'App\Message\Consumer\Collections\ProductsEntityCollection': async
```
```
# services.yaml or some dedicated file
services:

  App\Message\Consumer\Processors\ProductsDispatcher:
    autowire: true

  #...

  App\Message\MessageHandler\ProductsEntityCollectionHandler:
    tags: [messenger.message_handler]
```
```
  # commands.yaml
  App\Command\Messenger\QueueAggregatorCommand:
    arguments:
      - '@messenger.bus.default'
      - '@messenger.receiver_locator'
    tags:
      - {name: 'console.command', command: 'app:aggregate-queue'}
```
```
class ProductsDispatcher implements Processor
{
    private $bus;

    public function __construct(MessageBusInterface $bus)
    {
        $this->bus = $bus;
    }

    // this one is reacting to RabbitMQ messages, thus only giving us messages 1 by 1
    public function process($entity): void // <- ProductsEntity instances are among ones coming here
    {
        // dispatch and send to queue here (using aggregatables transport)..
        $this->bus->dispatch($entity);
    }
}
```

```
// let's run this command to aggregate previously collected messages!
class QueueAggregatorCommand extends Command
{
    protected static $defaultName = 'app:aggregate-queue';

    private $routableBus;
    private $receiverLocator;

    public function __construct(MessageBusInterface $routableBus, ContainerInterface $receiverLocator)
    {
        $this->routableBus = $routableBus;
        $this->receiverLocator = $receiverLocator;

        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->setDefinition([
                new InputArgument('receiver', InputArgument::REQUIRED, 'Name of the receiver/transport to consume'),
            ])
            ->setDescription('Aggregate and dispatch messages');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $receiverName = $input->getArgument('receiver');
        if (!$this->receiverLocator->has($receiverName)) {
            $message = sprintf('The receiver "%s" does not exist.', $receiverName);

            throw new RuntimeException($message);
        }

        $receiver = $this->receiverLocator->get($receiverName);

        $worker = new QueueAggregator($receiver, $this->routableBus);
        $worker->run();

        return 0;
    }
}
```
```
// actual aggregation (for example ProductsEntity messages are collected into ProductsEntityCollection). Make sure corresponding collection class exists
class QueueAggregator
{
    private $receiver;
    private $bus;

    /**
     * @param ReceiverInterface $receiver Transport name
     * @param MessageBusInterface $bus
     */
    public function __construct(ReceiverInterface $receiver, MessageBusInterface $bus)
    {
        $this->receiver = $receiver;
        $this->bus = $bus;
    }

    /**
     * Receive the messages, transform them and dispatch to the bus.
     *
     * Collection docs: https://www.doctrine-project.org/projects/doctrine-collections/en/1.6/index.html
     */
    public function run(): void
    {
        $envelopes = $this->receiver->get();
        $groups = $this->groupByClassType($envelopes);

        foreach ($groups as $classType => $envelopes) {
            $collectionClass = $this->getCollectionClass($classType);
            /** @var ArrayCollection $collection */
            $collection = new $collectionClass($this->getMessages($envelopes));
            $this->handleMessage($collection);
            $this->acknowledge($envelopes);
        }
    }

    private function groupByClassType($envelopes)
    {
        $groups = [];
        foreach ($envelopes as $envelope) {
            $groups[get_class($envelope->getMessage())][] = $envelope;
        }

        return $groups;
    }

    /**
     * Derive collection class name out of given class name
     *
     * @param string $classType Class name to derive collection class name from
     *
     * @return string
     * @throws \Exception
     */
    private function getCollectionClass(string $classType): string
    {
        $collectionClass = str_replace('Entities', 'Collections', $classType);
        $collectionClass = $collectionClass . 'Collection';
        if (!class_exists($collectionClass)) {
            throw new \Exception(
                sprintf("Unable to find collection %s for given class %s", $collectionClass, $classType)
            );
        }

        return $collectionClass;
    }

    /**
     * @param Envelope[] $envelopes
     *
     * @return Entity[]
     */
    private function getMessages(array $envelopes): array
    {
        return array_map(function ($envelope) {
            return $envelope->getMessage();
        }, $envelopes);
    }

    /**
     * @param ArrayCollection $collection
     *
     * @return void
     */
    private function handleMessage(ArrayCollection $collection): void
    {
        // this one will go to async transport according to our yaml config
        $envelope = $this->bus->dispatch($collection);

        // log stuff here
    }

    /**
     * Bulk acknowledge (we "know" for sure that we can acknowledge, because in fact we only group and move messages to a different table on the same database, thus we don't care about rejection etc.)
     *
     * @param Envelope[] $envelopes
     *
     * @return void
     */
    private function acknowledge(array $envelopes): void
    {
        array_walk($envelopes, function ($envelope) {
            $this->receiver->ack($envelope);
        });
    }
}
```
```
namespace App\Message\Consumer\Entities;
use ...
class ProductsEntity extends Entity
{

}
```
```
namespace App\Message\Consumer\Collections;
use Doctrine\Common\Collections\ArrayCollection;
class ProductsEntityCollection extends ArrayCollection
{

}
```
```
// use regular worker to consume these: php bin/console messenger:consume async -vv
namespace App\Message\MessageHandler;
class ProductsEntityCollectionHandler implements MessageHandlerInterface
{
    // so now we have a collection of previously grouped messages which we can finally process as 1 entity! (So if we reject, then whole collection is rejected. Goal accomplished)
    public function __invoke(ProductsEntityCollection $collection)
    {
        $this->doSomethingTo($collection); // exception thrown here will reject our group of entities (which was previously created at QueueAggregator)
    }

    // ...
}
```

**Comment by Guikingone** [comment]
Actually, I only see 3 options: 

- Store a "collection" in the default message
- Extends the default command and create your own batch logic to consume messages
- Extends the transport to create a "batch-style" transport

The main issue is that Messenger receive messages 1 by 1 (that the responsibility of the transports, not the Bus) so maybe you can extends the transports and decorate/wrap them into a "batch-style" transport that can store and retrieve X messages at the time. 

At the same time, keep in mind that the Worker can only "run" 1 message at the time (maybe we can use tools like a "auto-scale" worker that can create multiples instance of the worker in order to consume X messages at the same time (a [lib](https://github.com/krakphp/symfony-messenger-auto-scale) already implement this idea)?

**Comment by githoober** [comment]
It would be beneficial if the official Symfony team's stand on whether they will ever support batching in Messenger was documented here.

We, at our organization, are trying to decide whether we can fully invest into Symfony Messenger and migrate away from RabbitMQBundle that has been inactive recently and been loosing support. The are a few problems that we are trying to solve with this migration, and one of them is a lack of any batch product/consumer support in Messenger.

I am tagging @nicolas-grekas to hopefully get a feedback here.

**Comment by oleg-andreyev** [comment]
I don't think it's a responsibility of messenger component to implement batches because it's basically is a wrapper for ext-amqp which does not have batch processing and even in terms of CQRS you don't process batches.

If we need batches, we should implement your own transport same as it's done in rabbitmq-bundle (https://github.com/php-amqplib/RabbitMqBundle/blob/cf67adaa4e306d8e9cb6855a72d79263b425ded8/RabbitMq/BatchConsumer.php#L235)

**Comment by quazardous** [comment]
I'm using messenger to process data synchronisations between two softwares. The master software sends lots of webhooks when an item is modified (title, status, etc). So I'm trying to aggregate the messages at consume time because I don't need to sync many times the same item in a row.

I've look at the `messenger:consume` worker command and it uses subscribers to handle limits (`-l`, `-m`, `-t` options).

What would be nice is some `WorkerLimitEventAwareInterface` that could recieve and handle "limitReached" events. So this middleware could stack and aggregate messages depending on needed use case. Or just some event to subscribe to (LimitReachEvent).

**Comment by lyrixx** [comment]
Hi! Indeed this is feature that really lack in Symfony Messenger and the use case is really common.

Some examples:

* you need to index document in Elasticsearch: instead of calling ES each time for each message, you want to call it once for N message
* you need to call an API that is rate limited (for example to upload translations) 
* you need to aggregate some data before processessing it.

I have some time to explore this subjet, I'll keep you posted

**Comment by lyrixx** [comment]
Hi folks. What do you think of #42873 ?
I really like the API, I hope you like it too!
