### ISSUE TITLE
AmpHttpClient missing a new timeout function call

### ISSUE THREAD

**Issue by richard4339** [symfony/symfony#36911]
**Symfony version(s) affected**: 5.1.0-RC1

**Description**  
AmpHttpClient's request method sets these timeout values:
```php
$request->setTcpConnectTimeout(1000 * $options['timeout']);
$request->setTlsHandshakeTimeout(1000 * $options['timeout']);
$request->setTransferTimeout(1000 * $options['max_duration']);
```
However, the amphp/http-client module introduced a fourth timeout in [version 4.3.0](https://github.com/amphp/http-client/releases/tag/v4.3.0) released on May 3rd, an inactivity timeout, as seen here: https://github.com/amphp/http-client/pull/263

**How to reproduce**  
Make a request and sleep for 11 seconds before calling getContent().

**Possible Solution**  
Adding `$request->setInactivityTimeout(1000 * $options['max_duration']);` works, but I'm not sure that is the appropriate $options value to use (timeout would make sense, as would a non-existent new option).
Another temporary option could be to restrict the package to version 4.2.2 when Symfony 5.1 is released?

**Comment by nicolas-grekas** [comment]
Just to confirm, did you actually run into any issue related to this?
Because the code already handled inactivity timeouts to me, this new method is not needed to implement them.

If yes, can you please provide a full reproducer? E.g. one using httpbin.org

**Comment by richard4339** [comment]
I’ll work on a simple reproducer, it’s difficult to provide on the api I was using because of oauth requirements.

Gist of the problem was making 1000 request calls in an array and getting rate limited and needing to sleep for about 30 seconds 800 requests in. Next code call is a new for loop with a getContents() call. Because of the sleep, by the time it got to the calls right before the sleep, more then ten seconds passed, and the new Amp inactivity timeout kicked in. Reverting from 4.3 to 4.2.2 that didn’t have that new baked in inactivity timeout of ten seconds resolved the problem. My point in this issue is that I think that Amp’s inactivity timeout is overriding the Symfony one, and because I can’t manually touch the actual Amp client, I can’t manually call their new method or pass an option through to touch it.

**Comment by nicolas-grekas** [comment]
Thanks for the useful details.

FYI, Symfony 5.2 will provide support for pausing without calling sleep, see https://github.com/symfony/symfony/pull/37136

About inactivity timeouts, the issue is that there is now a default value set to 10s.

Would you mind sending a PR (branch 5.1) to disable this timeout by setting it to `0` when the method exists?
