### ISSUE TITLE
Symfony/VarDumper copy to clipboard button

### ISSUE THREAD

**Issue by 6562680** [symfony/symfony#36922]
Would be great to have button like on several websites used on generated fields like tokens;

```
dump(json_encode('tonns_of_data'));
```
-> copy with single button

also it will help with var_export().

**Comment by nicolas-grekas** [comment]
What content would you expect to get copy/pasted?
How much javascript does this require? If this needs a full-fledged JS lib, that might be out of reach.

**Comment by nicolas-grekas** [comment]
Closing as staled, feel free to submit a PR if you're up to working on this of course.
