### ISSUE TITLE
Architecture question - separating public and private APIs

### ISSUE THREAD

**Issue by NikitaObukhov** [symfony/symfony#36950]
Hello guys. Architectural question here. I am going to start a new project with Symfony 5. The project consists of public and private (admin) rest APIs. The idea is to completely separate them and deploy on different webservers.

![diagram](https://user-images.githubusercontent.com/5229418/82781275-8ce5db80-9e83-11ea-984f-6b4d8267a6c1.png)

My approach is to make separate kernels (as described [here](https://symfony.com/doc/current/configuration/multiple_kernels.html)) and at least 3 modules (bundles): CoreBundle (used by both apps), MembersBundle (for the public app) and AdminBundle.

In practice, there will be a single repository and different kernels that enable different bundles.

```
src
│   AdminKernel.php
│   MembersKernel.php   
│
└───Acme
│   └───CoreBundle
│   └───MembersBundle
│   └───AdminBundle
│   
public
    │   members.php
    │   admin.php
```

What is confusing is that warning message in the docs that this approach is no longer recommended. Same is about bundles (modules). But that is the only known to me way to make a modular architecture which has a long and proven track record in software development btw.

I know such a modular system is used in at least two popular open-source projects based on Symfony, Sylius and Akeneo and this was a recommended way before 4 was released.

So the question is. What do you guys think about this approach? Maybe Symfony5 provides any other alternatives? And my main concern is future support. Is it possible that SF6 will drop bundle support and it will be not possible to update apps with such architecture? What do you think?

Thanks in advance!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
