### ISSUE TITLE
make:entity command changes the group of the file

### ISSUE THREAD

**Issue by Cartman34** [symfony/symfony#36969]
**Symfony version(s) affected**: 5.0.8
maker-bundle version is v1.17.0

**Description**  
Command **make:entity** changes the group of the file.

**How to reproduce**  
On existing entity class file, set user of you entity file to **youruser**:www-data and permission to 750.
Use `php bin/console make:entity` to add one field with **youruser**.
The file's group is now **youruser**.

**Comment by fabpot** [comment]
You should report this issue on the symfony/maker-bundle repo instead. Thank you.

**Comment by Cartman34** [comment]
Done
https://github.com/symfony/maker-bundle/issues/622
