### ISSUE TITLE
[Serializer] symfony returns object of objects instead of array of objects when removing an object from an Arraycollection

### ISSUE THREAD

**Issue by Mouerr** [symfony/symfony#36965]
**Symfony version(s) affected**: 4.4..8

**Description**  
i have a field called documents(ArrayCollection) when i try to remove an objects from documents and serialize it $this->json($article); i find that it returns object of objects not array of objects.

**How to reproduce**  
1) create a new field type relation and give it OneToMany(article Has Many Documents)
2) create an action that removes one object from collection:
$article = $articleRepository->get($id);
$article->removeDocument($document);
$em->persist($article);
$em->flush();

3) return $this->json($article,200);

**Additional context**  
i noticed that:
+ If I removed the last object from the collection, it returns array of arrays.
+ If i removed an object from the middle of the collection, it returns object of objects.
+ If I Added the a new object to the collection, it returns array of arrays.
+ If i get the collection and serialize it, it returns array of arrays.

**Comment by dunglas** [comment]
This is a known issue coming from Doctrine. PHP has a single data structure for both lists and maps (associative arrays). When serializing an associative array to JSON, it will create a JSON array if keys in the arrays are consecutive integers, and a JSON object if they aren’t.

removeDocument from Doctrine Collection doesn’t reorder the keys of the underlying array.

To prevent this issue you must reorder the Doctrine collection when you modify it, directly in your entity as described here: https://api-platform.com/docs/core/serialization/#collection-relation

**Comment by Mouerr** [comment]
thanks @dunglas

**Comment by LicenceOne** [comment]
God knows I love my wife and my kids. But @dunglas  you overpassed this love in a post ❤️
