### ISSUE TITLE
[WebProfilerBundle] silent failure on Travis

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#36962]
On branch 3.4 (and up to master), [the tests of the WebProfilerBundle display this](https://travis-ci.org/github/symfony/symfony/jobs/690915785#L2992):

> [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Panel "this-panel-does-not-exist" is not available for token "c72f51"." at /home/travis/build/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php line 111

the message can be reproduced locally.

Either it should be a failure, or the message should be removed.

Would anyone be available to have a look?

**Comment by stof** [comment]
This is probably a log message going to `php://stderr` due to the default logger added by the kernel. The functional tests of the bundle should register a NullLogger as the logger instead.

**Comment by stof** [comment]
The test is passing because the test is asserting that the response is a 404 (which will be the case for a NotFoundHttpException handled by the ExceptionListener).
