### ISSUE TITLE
[Uid] Uuid::fromBinary() is missing

### ISSUE THREAD

**Issue by rybakit** [symfony/symfony#36978]
I store UUIDs in the database in binary format (16 bytes) and was looking for a method to construct `Uuid` objects from these binary strings. According to the [documentation](https://symfony.com/doc/5.1/components/uid.html#generating-uuids), there is a `fromBinary()` method for this:

> If your UUIDs are generated in binary format, use the fromBinary() method to create the objects for them:
> ```php
> $uuid = Uuid::fromBinary($uuidBinaryContents);
> ```

However, I cannot find this method in the sources. I can use `Uuid::fromString()`, but I wonder if this is the recommended way to build `Uuid`s even if you know that the string you build from is always a binary string of 16 bytes?

**Comment by nicolas-grekas** [comment]
fromString is the way to go yes: it auto-detects the format based on the length of the input string
can you please send a doc PR to fix it?
