### ISSUE TITLE
It is no longer possible to use Symfony Process as an extendable base class

### ISSUE THREAD

**Issue by greg-1-anderson** [symfony/symfony#36988]
**Symfony version(s) affected**: 5+

**Description**  
The project [consolidation/site-process](https://github.com/consolidation/site-process) provides an API that returns Symfony Process objects for executing commands on remote environments. The type of remote environment is abstracted with transports; the ssh transport may be used to run commands on remote servers using ssh, and the docker transport may be used to run commands in a docker container. The client is generally unaware of transports, which are part of the site object that is passed to the site process factory to produce a Symfony Process object.

The implementation of the SiteProcess class was an extension of the Symfony Process class. This allowed clients the ability to use a familiar interface, perhaps even repurposing existing code that takes a Process object as a parameter. At the same time, being a subclass allowed SiteProcess to add convenience methods related to the remote nature of the new kind of process object.

In Symfony 5, the setCommandLine method was removed, making it impossible for site-process to wrap the commandline with the transport.

**How to reproduce**  
Failing tests are at https://github.com/consolidation/site-process/pull/50.

**Possible Solution**  
1. Direct support: The setCommandLine method could be restored to the Process class, but as a protected method rather than a public method. This would still allow subclasses to wrap commands with a transport.
1. Eat your own dogfood: The Process:start() method et. al. could call the getCommandLine() method rather than accessing the private field directly. This also would allow subclasses to control how the commandline is generated. 
1. Will not fix: site-process could become an object that produces Symfony Process objects (a Process factory, rather than isa Process). This is undesirable, because it breaks the site-process API, and the resulting API is not a simple and easy to use.
1. Will not fix: site-process could copy all of the Symfony Process code into its own class, or perhaps use the hasa Process model rather than isa. This is undesirable, because it would require duplication of code. The isa relationship could perhaps still be maintained, though, if SiteProcess still extended Process without calling through to the Symfony Process implementation.

**Additional context**  
If one of the proposed solutions involving changing symfony/process is acceptable, I'd be happy to make a pull request.

**Comment by nicolas-grekas** [comment]
Couldn't you manage a separate `Process` instance internally?
You could still extend the base Process class, but you would not rely on the parent methods to actually run the process - instead you would get through `$this->process->etc()`.

The issue with `setCommandLine()` is that it has a hidden requirement for escaping command line argument outside of it. And there is no reliable way to escape arguments in a portable way. That's why passing the command as an array is really encouraged.

**Comment by greg-1-anderson** [comment]
Yeah, that is option 4. Whenever Symfony Process added or changed a method interface, Site Process would also have to be updated. Also, Site Process needs to manipulate the command array, so there would be some duplication.

> And there is no reliable way to escape arguments in a portable way.

Ultimately, Symfony Process must do this itself internally, though. I really don't want to reduce the array to a string myself, though. It would be even better if the Process class provided a way for derived classes to manipulate the command array.

If you're not up for that, you can close this and I will revert to the `hasa` implementation.

**Comment by nicolas-grekas** [comment]
I'm not suggesting copy/pasting the code on your side. This looks unnecessary to me. I'm not sure I see any blocker with the solution I'm talking about. Manipulating the array of options can be done before (re)instantiating the internal process object in my proposal.

**Comment by greg-1-anderson** [comment]
The hasa implementation is feasible, and I can do it; I simply prefer the option of subclassing. The main duplication of the hasa implementation would be of all the public method signatures with pass-through calls.

**Comment by nicolas-grekas** [comment]
Can you can call the constructor as a method maybe? This would be OK since you're inheriting.

**Comment by greg-1-anderson** [comment]
I need to modify the commandline array after the user calls my convenience methods to configure their process object (just like the usage model of Symfony Process).

**Comment by greg-1-anderson** [comment]
Maybe bring back setCommandLine, but keep it protected and typehint the parameter to `array`?

**Comment by nicolas-grekas** [comment]
Can't you call the constructor after instantiation to reinitialize the object with the modified array ?

**Comment by nicolas-grekas** [comment]
> Maybe bring back setCommandLine, but keep it protected and typehint the parameter to array?

I don't think this is really desired. There are ways without as we figured out so that it would only be a convenience method. Ideally, Process would be immutable (it might become in the future). This would mean decorating the constructor would be the only sensible way to wrap it with a transport. I'd like we could figure out a way that fits this envisioned design.

**Comment by greg-1-anderson** [comment]
An immutable Process would be a completely different API. If you're not in favor of extending the model of the current API to subclasses, I'll use one of the workarounds instead. Thanks.
