### ISSUE TITLE
[Sendgrid-Mailer] Passing data to a payload from an email message

### ISSUE THREAD

**Issue by dskora-rdi** [symfony/symfony#36998]
**Description**  
It would be nice to pass parameters to a payload (SendgridApiTransport) e.g. template_id.

**Example**  
Maybe via headers or context of TemplatedEmail.

Can create PR if needed. (tried to use X-SMTPAPI with filters but getting invalid header for template_id)

**Comment by fabpot** [comment]
We do have some possibilities here for tags for instance, but we won't support templates.
