### ISSUE TITLE
[FW] function addFlash should not use the session as service

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#36996]
AFAIK there is an ongoing process of removing the session declared as service.. Can't find the related issue.

Would you accept a MR allowing the session to pass as argument here: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L200
and raise a deprecation warning if the developer does not pass one.

**Comment by fabpot** [comment]
I don't think this is an isolated change we would consider. It would be better to have a global strategy.

**Comment by gmponos** [comment]
Found the issue. https://github.com/symfony/symfony/issues/10557

> I don't think this is an isolated change we would consider. It would be better to have a global strategy.

Fair enough. 

But isn't this a code part that you will have to change sooner or later. I am mostly interpreting your answer as.. "This might not be the solution we want.. but we haven't also concluded to a solution". Which is fine.. but if you have other directions that I could follow.. like the shortcut method ([here](https://github.com/symfony/symfony/issues/10557#issuecomment-466966636)) let me know.. just wanted to help...

feel free to close or postpone it for later 😄

**Comment by fabpot** [comment]
I think you're right: it does not feel like a good solution to pass the session explicitly here, but I don't have any other idea for now. Working on a global solution might help find better solutions than this one.
To be honest, I don't have the full picture anymore in mind, so I would need to dig in the code before having clearer ideas or directions.
If you like to work on this one (which would be great), feel free to think of a plan and discuss it on the issue so that we can iterate there before implementing anything.

**Comment by nicolas-grekas** [comment]
Another idea might be to rely on the Notifier component.
What about killing session flashes and replace them with notifications instead?
There is already a transport that uses ... flash bags. But the big difference is that then, this becomes an implementation detail.

**Comment by gmponos** [comment]
> What about killing session flashes and replace them with notifications instead?

Yes.. It is an idea.. it feels weird.. not necessarily in a bad sense.

- Devs are used to `addFlash` and they can use only the Session in order to display notifications.. now they will need to require an extra component.
- Not sure if they are exactly "notifications" 
  - they need to be removed after they are flashed... 
  - Some ppl cound describe them as "announcements"/"alerts" but it is just schematic... 

Not sure what other complications might rise..
