### ISSUE TITLE
Add (amqp) ssl capacity to messenger DSN

### ISSUE THREAD

**Issue by vasilvestre** [symfony/symfony#37002]
**Description**  
I tried using Amazon MQ and this error poped :
`Uncaught PHP Exception Symfony\Component\Messenger\Exception\InvalidArgumentException: "No transport supports the given Messenger DSN "amqps://private-ip:5671/ouag"." at /var/task/vendor/symfony/messenger/Transport/TransportFactory.php line 40`

I don't know what's needed to handle SSL on this protocol but it would be cool !

Here's the PHP amqp integration https://github.com/php-amqp/php-amqp/pull/205/files

**Comment by DavidGarciaCat** [comment]
I have the same problem, in my case using a company's AMQPS host:

```
No transport supports the given Messenger DSN "amqps://USER:PASSWORD@SERVER:PORT/%2f/messages"
```

An update would be highly appreciated

**Comment by vasilvestre** [comment]
> I have the same problem, in my case using a company's AMQPS host:
> 
> ```
> No transport supports the given Messenger DSN "amqps://USER:PASSWORD@SERVER:PORT/%2f/messages"
> ```
> 
> An update would be highly appreciated

Symfony 5.2 will ship these changes :)

**Comment by DavidGarciaCat** [comment]
I've been following up the PR so I'm eager to test the new functionality. Lucky me, I upgraded my SF4.4 app to 5.1 a few months ago so it will be easy to test it.

Are the SSL certificates a requirement for the `amqps` protocol?

**Comment by vasilvestre** [comment]
Definitly not, you can even use amqp dsn and specify the port used (search
documentation PR linked for explanation)

Le lun. 21 sept. 2020 à 10:42, David Garcia <notifications@github.com> a
écrit :

**Comment by stof** [comment]
@DavidGarciaCat if you use the `amqps` scheme, we enforce the usage of a TLS certificate, yes. Using a AMQPS scheme without doing actual TLS would not make sense.

**Comment by DavidGarciaCat** [comment]
> @DavidGarciaCat if you use the `amqps` scheme, we enforce the usage of a TLS certificate, yes. Using a AMQPS scheme without doing actual TLS would not make sense.

Weird thing, as my SysAdmins told me the requirement is to use `amqps` but not the TLS certificates. Anyway, if this is a requirement for the component, I will try to arrange a meeting with them once SF 5.2 is out.

Thanks!

**Comment by vasilvestre** [comment]
We are just enforcing the behavior, use amqp://localhost:5671 (default rabbitmq ssl port https://www.rabbitmq.com/ssl.html) and you can do the same.
If he won't let you use certificate, so every option defined here (https://www.rabbitmq.com/ssl.html#enabling-tls) become useless (may be wrong tho)
