### ISSUE TITLE
Messenger component will not start after deploying to production

### ISSUE THREAD

**Issue by peteruu** [symfony/symfony#37005]
**Symfony version(s) affected**: 4.4.8

**Description**  
When we deploy our application which is working completely fine on developer environment we have problem on production server with messenger component and we are getting this error
Attempted to call function "pcntl_signal" from namespace "Symfony\Component\Messenger\EventListener".
Even when we run cache:clear command it is not working, we must delete the cache folder on the production environment to make it work.

This happens when we call our URL which is calling messenger:consume command 

**How to reproduce**  
we were unable to reproduce this problem even in our development server.

**Comment by xabbuh** [comment]
Could it be that faulty cache was generated with a PHP environment having the process control extensions while this extension was not available at runtime?

**Comment by peteruu** [comment]
Hi i just talked with my hosting company and it is like this when we deploy app with deployer it is run by php (cli) which has "pcntl_signal" function so cache is created. But when website is loaded with php from webserver it does not have "pcntl_signal" function so because of that we have bad caches as you told me. 
It is possible somehow make it work with those conditions ?

**Comment by xabbuh** [comment]
You should be able to solve this by adding a compiler pass that removes the service definition for that specific event listener. But the setup is still risky as there may be other places where different extensions in the CLI environment can lead to issues in your application when later executed through FPM.

**Comment by peteruu** [comment]
i probably don't understand fully we need to use that command we can not remove it just like that maybe only one time when the cache is created in deployment process that is all but i really don't know how to achieve that. If you can be little more specific I would really appreciate that

**Comment by peteruu** [comment]
```
public function process(ContainerBuilder $container)
    {
        if (php_sapi_name() === 'cli') {
            $container->removeDefinition('messenger.listener.dispatch_pcntl_signal_listener');
            $container->removeDefinition('messenger.listener.stop_worker_on_sigterm_signal_listener');
        }

    }
```
i put this code to Kernel.php and it is working now. 
thank you very much for your assistence.

**Comment by GuilhermeMReis** [comment]
For me it was the missing php module `pcntl` from my Dockerfile.

Fixed adding them in. (given that you're image is the  `php:fpm`)

`Dockerfile`
```
RUN docker-php-ext-configure pcntl --enable-pcntl
RUN docker-php-ext-install pcntl
```

I hope more people like me can get the fix done

**Comment by MariusTBjercke** [comment]
> For me it was the missing php module `pcntl` from my Dockerfile.
> 
> Fixed adding them in. (given that you're image is the `php:fpm`)
> 
> `Dockerfile`
> 
> ```
> RUN docker-php-ext-configure pcntl --enable-pcntl
> RUN docker-php-ext-install pcntl
> ```
> 
> I hope more people like me can get the fix done

I'm a little late, but thank you! Worked like a charm.
