### ISSUE TITLE
[Form] EmailType has name confilct when custom form type is named EmailType

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#37010]
**Symfony version(s) affected**: 5.0.8

**Description**  
I created a custom form type `App\Form\Contact\EmailType`

``` php
<?php

namespace App\Form\Contact;

use App\Entity\Contact\Email;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label')
            ->add('address')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Email::class,
        ]);
    }
}
```

When I try to use it in a parent form with `CollectionType`, the field is rendered as an email input (reading the `__toString` value of the entities) instead of rendering a collection of forms containing `label` and `address` fields.

``` php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('emails', CollectionType::class, ['entry_type' => 'App\Form\Contact\EmailType'])
            // this result in a `<input type="email">` field instead of a collection
        ;
    }
```

If I rename my form type to `App\Form\Contact\Email2Type`, everything works properly

**UPDATE**
The conflict is on the block prefix name.
If I change the block prefix name with the below code, the form work properly.
```
    public function getBlockPrefix()
    {
        return 'email2';
    }
```

**Comment by Seb33300** [comment]
I just found that this issue can be reproduced on `integer` field too.
If I edit my form to return `integer` in the `getBlockPrefix` function, the collection will be rendered as `<input type="integer">` field.

I am not sure if form types provided by Symfony should be considered as reserved keywords, but if it's the case, we probably may trigger an exception if we try to use a reserved name.

**Comment by xabbuh** [comment]
see also #16899, #17009 and #28217

**Comment by Seb33300** [comment]
Indeed, same issue as the one you reported.

The block prefix seems to be used to determine which twig function should be used to render the form type :/

**Comment by xabbuh** [comment]
So I am going to close here as this is how it works and we cannot change it without breaking BC. If you feel like we could document this better, please consider opening an issue in the documentation repository.
