### ISSUE TITLE
Entity constraints are not called in the CollectionType field form

### ISSUE THREAD

**Issue by thomas-miceli** [symfony/symfony#37014]
**Symfony version(s) affected**: 5.0.8 and 5.1.0

**Description**  
When adding a `CollectionType` field on a form, if its `entry_type` is another custom form type linked to a `data_class`, the constraints of the `data_class` will not be triggered when you submit the first form.

**How to reproduce**  
Project code to reproduce the bug is here (5.1 version) : https://github.com/thomas-miceli/collectiontype-assert-bug
Let's say we have two entities with `@Asserts\` on each field : `Book` and `Author`. 
Navigate to **`/book`** to create a single book (with no author), here is the `BookType` to create a single book
```php
class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Book title',
            ])
            ->add('price', NumberType::class, [
                'label' => 'Book price',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}
``` 
**It works well**, the constraints defined in the **mapped** class `Book` entity class are **triggered** and will not permit unwanted values as expected. You can see in the debug toolbar everything worked well.

Now, navigate to **`/author`** to create a new Author, where you can directly add the author name and a collection of the books he wrote. Here is the `AuthorType` to create a new author.
```php
class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Author name'
            ])
            ->add('books', CollectionType::class, [
                'entry_type' => BookType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'entry_options' => ['label' => false],
                'by_reference' => false,
                'label' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}
```

If you add books on the collection from the HTML form, the book constraints **will not be triggered** when you submit the form, that means you can put any value to the book fields, the constraints defined in the `Book` entity class **are bypassed**. The author and his books with non verified values are persisted to the database. You can see that in the debug toolbar aswell. However the `Author` constraints are still called.

The only way to have the constraints working is to add `constraints` options to the `BookType`, (uncomment them in my project code to see them working), which not make sense because this form type is **mapped** to the `Book` entity. So i have to write my constraints twice.

**Possible Solution**  

**Additional context**  
I originally found this bug in the 5.0.8 version, but i tested it in the 5.1 (pre release) version and it was still there.

**Comment by xabbuh** [comment]
This does not seem like a bug to me. When your `Book` objects are embedded inside the `Author` object, validation starts at the root of the object graph (i.e. with the `Author` instance). You then need to configure it to cascade validation into the nested `Book` instances like this:

```php
/**
 * @ORM\OneToMany(targetEntity=Book::class, mappedBy="author", cascade={"persist"})
 *
 * @Assert\Valid()
 */
private $books;
```

Can you confirm that your application behaves as expected with these changes?

**Comment by thomas-miceli** [comment]
It is working as intended, so it's my bad. 

Anyway, I do believe it will be good to add [here](https://symfony.com/doc/current/form/form_collections.html) a section about how to validate data using the `Valid` constraint since I think that constraint name might not be that obvious.

**Comment by cavasinf** [comment]
Just spent 3 hours trying to understand why Assert constraints in entity inside a CollectionType where not checked.
Stumbled on this issue (thank god!)

`#[Assert\Valid]` should be in the doc of [CollectionType](https://symfony.com/doc/current/reference/forms/types/collection.html) AND/OR in [How to Embed a Collection of Forms](https://symfony.com/doc/current/form/form_collections.html) ❗
