### ISSUE TITLE
getClientIp() gives server IP or Random IP rather than visitor IP

### ISSUE THREAD

**Issue by Atiladanvi** [symfony/symfony#37023]
**Symfony version(s) affected**: 5.0

**Description**  
I'm trying to track IP addresses of visitors. When using getClientIp(), I get the server's IP address rather than the visitor's. I tried this on multiple machines at multiple locations and they all resulted in the exact same IP.
I have look at the follow line:
https://github.com/symfony/http-foundation/blob/0553e8b8cb3a48d6b84a91968871e6e14d5602a4/Request.php#L798
```php
public function getClientIps()
{
   $ip = $this->server->get('REMOTE_ADDR');

   if (!$this->isFromTrustedProxy()) {
       return [$ip];
  }

  return $this->getTrustedValues(self::HEADER_X_FORWARDED_FOR, $ip) ?: [$ip];
}
```
**How to reproduce**  
I have noted this behavior in my network. But i have the problems with this method in heroku. The results ip's are random in some cases. I have used https://ngrok.com/ for local tests. I have a visitor tracker made with on rails and it  works for all network and all cases.
I have tested in my heroku server and i have catch the results:
_Different ips for same client._
![image](https://user-images.githubusercontent.com/11599205/83352485-12eda080-a322-11ea-950d-cc4377ca797b.png)

**In my ruby application running in heroku always it works:**

![image](https://user-images.githubusercontent.com/11599205/83352552-98715080-a322-11ea-9916-e40bebc543ee.png)

**Possible Solution**  

:eyes:
**Additional context**  
Test locally with ngrock
```php
public function getClientIps()
{
  $ip = $this->server->get('REMOTE_ADDR');

   // if (!$this->isFromTrustedProxy()) {
   //   return [$ip];
   // }
      var_dump($this->getTrustedValues(self::HEADER_X_FORWARDED_FOR, $ip))
      return $this->getTrustedValues(self::HEADER_X_FORWARDED_FOR, $ip) ?: [$ip];
}
```
Output
```
^ array:2 [▼
  0 => "127.0.0.1"
  1 => "177.66.107.164"
]
```

**Comment by xabbuh** [comment]
Well, if your web server is behind a proxy server, you will indeed have to configure the trusted proxies to retrieve the real client IP address.

**Comment by xabbuh** [comment]
see https://symfony.com/doc/current/deployment/proxies.html

**Comment by Atiladanvi** [comment]
yep but i think this can be solve if in this case. I have used several http kernels and only symphony has this behavior.

**Comment by Atiladanvi** [comment]
we have a lot of applications that rely on the GetClientIp method. Implementations that limit the exhaustive request for responses just don't work., There could be some way to facilitate this configuration without having to change Request :: setTrustedProxies. Or simply do not use symfony to discover clients' ip.
