### ISSUE TITLE
[Form] Some form errors are no longer shown since 3.4.41

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#37025]
**Symfony version(s) affected**: 3.4.41

**Description**  
Since https://github.com/symfony/symfony/pull/36865/commits/b819d94d1413e426237f35e6b6eddbc380dbccf9 some form field errors have been hidden. 
**How to reproduce**  
I am able to reproduce when using `property_path` option set to field to another object and `form_rest`. Attaching reproducer [symfony-demo.zip](https://github.com/symfony/symfony/files/4707756/symfony-demo.zip)

Go to http://127.0.0.1:8000/en/admin/post/1/edit and hit submit. Field "author name" should show error, but doesn't. Web profiler toolbar does show form error.

cc @xabbuh

**Comment by bendavies** [comment]
It's not even as complex as `property_path` being on another object.
It can just be an field on the current object, but with a different name to the form field. i.e.

```
->add('amount_closing_balance', MoneyType::class, [
    'property_path' => 'closingBalance',
])
```

So far I've found the `Violation Path` is changing:
4.4.8: `children[amount_closing_balance].children[amount]`  
4.4.9: `children[closingBalance].children[amount]`

And then maybe the `ViolationMapper` in the `Form` component can no longer map this path back to the correct field.

**Comment by xabbuh** [comment]
Thank you for the feedback. I am working on a patch.

**Comment by xabbuh** [comment]
Can you both confirm that #37085 would fix this issue?

**Comment by ostrolucky** [comment]
It solves the issue for me
