### ISSUE TITLE
TypeError: Argument 1 passed to str_contains() must be of the type string, null given

### ISSUE THREAD

**Issue by mariosvasiliou** [symfony/symfony#37035]
**Symfony version(s) affected**: 4.4.9

**Description**  
The replacement of get_class() with get_debug_type() and addition of dependency polyfill for php v8 in [recent changes](https://github.com/symfony/debug/compare/v4.4.8...v4.4.9) causes problem if you have lower php version for e.g php 7.2.x and when using laravel framework

**How to reproduce**  
Install laravel framework v6.x.
Create some code and use str_contains() function with null the first or second parameter....

**Possible Solution**  
Check php version or revert to get_class?

**Comment by stof** [comment]
Well, the PHP `str_contains` function does not accept `null` as first argument. It accepts only strings. So this TypeError is expected. PHP 8 would give you the same error 

And I don't see any usage of `str_contains` in the commit you linked, so I doubt it is related to this change.

**Comment by mariosvasiliou** [comment]
> Well, the PHP `str_contains` function does not accept `null` as the first argument. It accepts only strings. So this TypeError is expected. PHP 8 would give you the same error
> 
> And I don't see any usage of `str_contains` in the commit you linked, so I doubt it is related to this change.

Thank you for the reply,
Yes I know, actually the problem is with the helper package for Laravel framework because it already has a function named str_contains  that accepts nullable parameters....and with the addition of polyfill for PHP 8, it broke that functionality.
I have already opened an [issue ](https://github.com/laravel/framework/issues/33045) in Laravel project also but they stated that I have to choose between helper function or PHP one... The problem is that I don't have PHP 8 so I don't want to make that decision now or change my code and all usages now...but the dependency of symphony debugbar in laravel framework made this conflict and brokes code.

**Comment by stof** [comment]
Well, Laravel won't be able to tell people to choose between their helper and the PHP 8 function. They will need to rename their helper (or to declare their framework as incompatible with PHP 8)

**Comment by lcharette** [comment]
A simple fix would be to replace `str_contains` with `Str::contains`, but be aware that making sure you're passing a string would be the ideal solution, as [`Str::contains` expect strings even if they don't enforce it as of 5.8](https://github.com/illuminate/support/blob/5.8/Str.php#L100).

See https://laravel.com/docs/5.8/helpers#method-str-contains

**Comment by nicolas-grekas** [comment]
We could make the polyfill accept `null` and trigger a deprecation when this happens. If you think we should consider this, please open a PR on the polyfill repository.
But since the Laravel helper is deprecated and there are alternatives, we might just decide to do nothing.
I'm therefor closing. Thanks for submitting.
