### ISSUE TITLE
Assert Type is not working with api-platform

### ISSUE THREAD

**Issue by befabry** [symfony/symfony#37030]
**Symfony version(s) affected**: 4.4.9

**Description**  
Assert Type not working

**How to reproduce**  
Download this project : https://github.com/befabry/api-platform
I tried to put a validation on the App\Entity\CheeseListing entity of type integer. It is not working. I tried the int as well, not working either. I played around with various types.

Send this resource :
`{
  "title": "string",
  "price": "apple",
  "description": "string"
}`

It returns an error on the normalization. The validation did not work.

**Possible Solution**  

**Additional context**  

![image](https://user-images.githubusercontent.com/17452648/83362303-7e6e5700-a390-11ea-8302-0ca313392e04.png)
![image](https://user-images.githubusercontent.com/17452648/83362313-8d550980-a390-11ea-8cc4-7e78b0d304fb.png)

**Comment by xabbuh** [comment]
I am no API Platform expert, but if I am not mistaken, the data is deserialized first before being validated. So as far as I can see there is not much we can do here.

**Comment by befabry** [comment]
Thanks, I'll open a ticket for API Platform

**Comment by xabbuh** [comment]
Let's close here then. Thank you for understanding.
