### ISSUE TITLE
new security authenticator fails

### ISSUE THREAD

**Issue by bitgandtter** [symfony/symfony#37033]
**Symfony version(s) affected**: 5.1

**Description**  
after enabled **enable_authenticator_manager: true** i got **The service "security.listener.csrf_protection" has a dependency on a non-existent service "security.csrf.token_manager".**

Minimal project with issue https://github.com/bitgandtter/sf-security

**Comment by wouterj** [comment]
Thanks for testing the new system!

Can you please show some context (configuration of `framework.csrf` and `security` or - preferably - a minimal application that reproduces the error)?

**Comment by bitgandtter** [comment]
@wouterj i updated the issue with a link to the minimal project

**Comment by wouterj** [comment]
Thanks for your quick response! I've submitted a fix: #37047 I'm amazed that I've always tested the new system in a Symfony app with CSRF enabled 😄

**Comment by umpirsky** [comment]
Strange, but I still get:

```
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                 
  The service "security.listener.csrf_protection" has a dependency on a non-existent service "security.csrf.token_manager". 
```

in Symfony `v5.4.25`. Both `!$container->has('security.authenticator.manager')` and `!$container->has('security.csrf.token_manager')` are `false` in `RegisterCsrfFeaturesPass::registerCsrfProtectionListener()`, but I still get an error.

**Comment by xabbuh** [comment]
please open a new issue and provide a small example application that allows to reproduce it
