### ISSUE TITLE
AddExpressionLanguageProvidersPass breaks custom routers

### ISSUE THREAD

**Issue by wizhippo** [symfony/symfony#37042]
**Symfony version(s) affected**: 5.1

**Description**
Previously in 5.0 there were no services tagged with `routing.expression_language_provider` so the issue did not arise.  There is in 5.1 so the issue can occur. 

`addExpressionLanguageProvider` is not part of the router interface.  As such `AddExpressionLanguageProvidersPass` should not use it if the router does not support it as the router could be replaced with a custom router that does not support the function.

https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddExpressionLanguageProvidersPass.php#L34

**How to reproduce**  
Example ezplatform replaces the router.default with its own router which does not implement `addExpressionLanguageProvider` nor should it have to if it is not part of the interface. 

**Possible Solution**  
Check it router supports `addExpressionLanguageProvider` first.
Make `addExpressionLanguageProvider` part of the router interface.
Apply to `router.default` instead of `router` and stipulate `route.default` has to be the symfony router or extended class.

**Comment by wizhippo** [comment]
"Apply to router.default instead of router and stipulate route.default has to be the symfony router or extended class." Is what I would suggest.

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR, branch 5.1?
An `is_a()` check might do it, isn't it?

**Comment by wizhippo** [comment]
Personally I think the pass should target `router.default` instead of router.  This would fix the issue I am seeing.  It is `router` that normally would be replaced and `router.default` is added to the `chain_router`
