### ISSUE TITLE
Symfony Doctrine bridge needs Doctrine ORM but it is not mandatory dependency

### ISSUE THREAD

**Issue by arnolanglade** [symfony/symfony#37045]
**Symfony version(s) affected**: 5.0.9

**Description**  
Symfony Doctrine bridge does not require Doctrine DBAL nor Doctrine ORM but they are only "suggested" (https://packagist.org/packages/symfony/doctrine-bridge). I am working on a project which uses Doctrine DBAL but does not use Doctrine ORM. Since the last patch of Symfony (v5.0.9) we had to hard code the version doctrine bridge to v5.0.8 to avoid errors (described in the next section). 

**How to reproduce**  

* Install Symfony project with `DoctrineBundle` and `Doctrine DBAL` but **without** `Doctrine ORM`.
* Run ` bin/console doctrine:database:drop --force`
* Then you get the error: `Attempted to load class "ToolEvents" from namespace "Doctrine\ORM\Tools".  Did you forget a "use" statement for another namespace?`

**Additional context**  

The problem comes from https://github.com/symfony/doctrine-bridge/blob/master/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php#L93. This class uses Doctrine `ORM` and `DBAL` events. Should we move those libraries from "suggested" to "required"?

```
{
   "message":"Command \"doctrine:database:drop --force\" exited with code \"1\"",
   "context":{
      "command":"doctrine:database:drop --force",
      "code":1
   },
   "level":100,
   "level_name":"DEBUG",
   "channel":"console",
   "datetime":"2020-06-01T14:53:25.165344+00:00",
   "extra":{

   }
}{
   "message":"Uncaught Error: Class 'Doctrine\\ORM\\Tools\\ToolEvents' not found",
   "context":{
      "exception":{
         "class":"Error",
         "message":"Class 'Doctrine\\ORM\\Tools\\ToolEvents' not found",
         "code":0,
         "file":"/path/to/vendor/symfony/doctrine-bridge/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php:93"
      }
   },
   "level":500,
   "level_name":"CRITICAL",
   "channel":"php",
}
```

**Comment by xabbuh** [comment]
Can you confirm that #37056 fixes the issue you experience?

**Comment by arnolanglade** [comment]
Yes it works, thank you!
