### ISSUE TITLE
[PropertyAccess] BC break due to a modified getter calling logic  

### ISSUE THREAD

**Issue by 1ed** [symfony/symfony#37052]
**Symfony version(s) affected**: 5.1.0

**Description**  
I think there is a BC break in the PropertyAccess component due to the changes were introduces in https://github.com/symfony/symfony/pull/30704 (I think). The  original logic is in https://github.com/symfony/symfony/blob/v5.0.9/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L470-L520. Maybe it's an edge case, but it breaks out app.

**How to reproduce**  
See #37053, the tests green on 5.0, but without the patch failing on. 5.1

**Possible Solution**  
See #37053 for a naive solution.

**Comment by norkunas** [comment]
We also hit this.
