### ISSUE TITLE
Cannot declare class EntityManager_*, because the name is already in use     

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#37059]
**Symfony version(s) affected**: 5.1

**Description**  

After upgrading Symfony to 5.1 my CI started to fail with this error. It also occasionally happens on localhost. I'm not exactly sure why it happens yet and I'm not able to reproduce it reliably at this point. Is this bug known / resolved already?

Why is new Symfony generating a proxy for EntityManager anyway? In master branch EntityManager is in fact [final](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityManager.php#L66) so whatever is the reason this won't work with doctrine 3.0.

**Comment by grachevko** [comment]
Same error, need to cache:warmup twice because first one always fail.

**Comment by lugosium** [comment]
Same for me since upgrade 5.1

**Comment by xabbuh** [comment]
I guess we will need a small example application that allows to reproduce the issue.

**Comment by enumag** [comment]
@grachevko @lugosium Do you guys have a way to reliably reproduce this? I did get the error once when calling cache:warmup but never again even after rm -rf var/cache.

From my findings, when this happens the var/cache/dev directory seems to contain two `Container<hash>` directories. And apparently both of them are loaded in same script. While this is already dubious and shouldn't happen in my opinion, it wouldn't be a problem normally since the classes are namespaced. The bug happens only because of the very last line in the generated container file:

```
\class_alias(__NAMESPACE__.'\\EntityManager_9a5be93', 'EntityManager_9a5be93', false);
```

**Comment by nicolas-grekas** [comment]
Nice catch @enumag. Could you please send a pr to add a class_exists check around the alias definition?

**Comment by enumag** [comment]
@nicolas-grekas I could if I knew where this alias is generated. Right now I have no idea where that happens.

**Comment by nicolas-grekas** [comment]
Check PhpDumper IIRC
1. Because that's the only way when running cache:clear (boot the command with the current container, build the new one and run cache warmers with it)
2. Dunno, not sure we should care here.

**Comment by enumag** [comment]
> Check PhpDumper IIRC

Okay I think I found it.

> Dunno, not sure we should care here.

Where should I ask about that then?

**Comment by enumag** [comment]
I think we need to add a class_exists [here](https://github.com/symfony/symfony/blob/b25168fe28d5569e731c44009f862252a3b9b718/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L570). But what I'm unsure about is which branch I should target. This bug might have possibly been present for a long time but the code around here changed quite a bit in recent versions. Also it seems noone really encountered a problem until v5.1.

**Comment by nicolas-grekas** [comment]
Let's go with 5.1: the dumped code changed in 5.1, this looks related.

**Comment by lugus** [comment]
Sorry @enumag, could not reproduce. 

Got this problem 3 times yesterday. Today try many times to rm -rf var/cache/dev, cache:clear, flush app/system redis cache etc to reproduce the issue but don't get it again. 

It's very sporadic.

**Comment by alekitto** [comment]
I have the same error but not on EntityManager, but on another lazy service.
I've found that the error is thrown at `Kernel->reboot()` as `class_alias`es calls try to declare aliases of the lazy proxies into the global namespace. Passing a salt into the ProxyDumper constructor (in `Kernel::dumpContainer` method) resolves the conflicts.

Additionally, I've found that setting the `container.dumper.inline_factories` parameter to `false`, make everything work correctly.

**Comment by kricha** [comment]
same error
```
Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code 1
 !!  
 !!   // Clearing the cache for the dev environment with debug                       
 !!   // true                                                                        
 !!  
 !!  
 !!  In App_KernelDevDebugContainer.php line 8654:
 !!                                                                                 
 !!    Warning: Cannot declare class EntityManager_9a5be93, because the name is al  
 !!    ready in use                                                                 
 !!                                                                                 
 !!  
 !!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
 !!  
 !!  
 Script @auto-scripts was called via post-install-cmd
```

**Comment by lugosium** [comment]
@enumag

I can reproduce the error each time i add or remove a service in my `config/services.yaml`.
I don't have autowired enabled for information.
