### ISSUE TITLE
[String] moving translation-contracts to require-dev is a BC break

### ISSUE THREAD

**Issue by ubermuda** [symfony/symfony#37051]
**Symfony version(s) affected**: 5.1.0

**Description**  
The `AsciiSlugger` requires `symfony/translation-contracts` but the dependency has been moved to `require-dev`. Any project that relied on `symfony/string:^5.0` to use the `AsciiSlugger` is going to break as soon as they upgrade `symfony/string`.

**How to reproduce**  
1. Have a project using `AsciiSlugger` through `symfony/string:5.0.x`
2. Run `composer update`
3. Your project is now broken

**Possible Solution**  
Revert dependency to `require` until `6.0` I guess?

**Comment by ro0NL** [comment]
in 5.0 the component was experimental still.

**Comment by fabpot** [comment]
Closing then.
