### ISSUE TITLE
[Security] New LoginFormAuthenticator fails on InsufficientAuthenticationException with missing AuthenticationEntryPoint

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#37068]
**Symfony version(s) affected**: 5.1

**Description**  

I've replaced my guard login authenticator with a version based on the `AbstractLoginFormAuthenticator` and enabled the AuthenticationManager. Everyhing works fine except hitting a page which requires `IS_AUTHENTICATED_REMEMBERED` without actual being logged in.

This triggers an `AccessDeniedException` which gets caught by the firewall ExceptionListener. This creates an `InsufficientAuthenticationException` and tries to  `startAuthentication()` with it. That method then throws an HttpException because there's not AuthenticationEntryPoint defined:

~~~php
        if (null === $this->authenticationEntryPoint) {
            throw new HttpException(Response::HTTP_UNAUTHORIZED, $authException->getMessage(), $authException, [], $authException->getCode());
        }
~~~

The guard system correctly uses the configured entry point to redirect to my login page.

**How to reproduce**

1. Build a login form based on the new authenticator
2. Build a page requiring a authenticated user
3. Hit the page w/o authentication

**Possible Solution**  

Define an entry point for the authenticator?

Sorry if I missed some doc. I've checked the blog post and Wouter's additional article, but couldn't find help.

Kind regards
Matthias

**Comment by wouterj** [comment]
Thanks for testing! The custom authenticator config doesn't yet set the entry point for you, so you have to manually set it:

```yaml
security:
  firewalls:
    main:
      custom_authenticator: App\Security\CustomFormAuthenticator
      entry_point: App\Security\CustomFormAuthenticator
```

Can you maybe try this?

I'm trying to come up with something that does this automatically, but it's more trickier than I expected (we need to somehow check if the custom authenticator implements `AuthenticationEntryPointInterface`, contrary to guards this is no longer required in the new authenticators): https://github.com/symfony/symfony/pull/37075

**Comment by althaus** [comment]
I'll check it out later today.

What if the listener would add a info/warning to the log before converting it instantly into a HttpEx? Like "Hey there's no entry point set, so I make this an error now. You could set the.config.value to change my behaviour."

**Comment by althaus** [comment]
> Can you maybe try this?

Setting `entry_point` fixed the issue. 👍
