### ISSUE TITLE
[RFC][Serializer] Non-nullable format string

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#37063]
See

https://github.com/symfony/symfony/blob/608b770f1bf155a9d84649d239440b733cd07959/src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php#L41

https://github.com/symfony/symfony/blob/608b770f1bf155a9d84649d239440b733cd07959/src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php#L51

AFAIK the null case can can never happen in practice, as serialize/deserialize do require a format:

https://github.com/symfony/symfony/blob/608b770f1bf155a9d84649d239440b733cd07959/src/Symfony/Component/Serializer/SerializerInterface.php#L30

https://github.com/symfony/symfony/blob/608b770f1bf155a9d84649d239440b733cd07959/src/Symfony/Component/Serializer/SerializerInterface.php#L39

`$format` being nullable is a rather annoying case, as i have to account for "no format" or "some default format", which is totally irrelevant for implementations.

Should we deprecate it? cc @dunglas

**Comment by jvasseur** [comment]
I personally used it a few times when I was using the Serializer component only to do object normalization without serializing it.

**Comment by ro0NL** [comment]
Hm touche. How do you interpret thaR? May it receive any format string or only null?

Ultimately this only affects direct usage, thus `normalize($obj)` becomes `normalize($obj, 'json')`.

Or for the case mentioned by @jvasseur `normalize($obj, '')` could be sufficient.

**Comment by jvasseur** [comment]
`normalize($obj, '')` could work, but `''` feels less natural than `null` to indicate that we don't care about the format.
