### ISSUE TITLE
UrlGeneratorInterface does not allow generating URL for object resources anymore

### ISSUE THREAD

**Issue by ambroisemaupate** [symfony/symfony#37062]
**Symfony version(s) affected**: ^5.0.0

**Description**  
`Symfony\Component\Routing\Generator\UrlGeneratorInterface` does not allow generating URL for `object` resources anymore. This will prevent https://github.com/roadiz/roadiz to upgrade to symfony v5+.

**How to reproduce**  
Use Symfony CMF `ChainRouter` and implement a new `VersatileGeneratorInterface` that extends `Router` class. This new Router could, for example, generate URL for `Page` objects which have `getSlug(): string` and a `getParent(): Page` methods.  Your `PageRouter::generate` method will loop over `Page::getParent()` and concate their `getSlug()` value to generate a dynamic URL.

```php
<?php
use Symfony\Cmf\Component\Routing\VersatileGeneratorInterface;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\Router;
use App\Entity\Page;

class PageRouter extends Router implements VersatileGeneratorInterface
{
    public function supports($name)
    {
        return $name instanceof Page;
    }

    /**
    * Convert a route identifier (name, content object etc) into a string
    * usable for logging and other debug/error messages.
    *
    * @param mixed $name       In Symfony 5, the name can only be a string
    * @param array $parameters Which might hold a route object or content id or similar to include in the debug message
    *
    * @return string
    */
    public function getRouteDebugMessage($name, array $parameters = [])
    {
        if ($name instanceof Page) {
            return $name->getSlug();
        }
        return 'Route name is not instance of ' . Page::class;
    }

    /**
     * @param mixed $name
     * @param array $parameters
     * @param int   $referenceType
     *
     * @return string
     */
    public function generate($name, $parameters = [], $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH): string
    {
        if (null === $name || !$name instanceof Page) {
            throw new RouteNotFoundException();
        }

        if (!empty($parameters['canonicalScheme'])) {
            $schemeAuthority = trim($parameters['canonicalScheme']);
            unset($parameters['canonicalScheme']);
        } else {
            $schemeAuthority = $this->getContext()->getScheme() . '://' . $this->getHttpHost();
        }

        /*
         * Walk the page graph to build path
         */
        $pagePath = [$name->getSlug()];
        /** @var Page $parent */
        $parent = $name;
        while (null !== $parent = $parent->getParent()) {
            $pagePath[] = $parent->getSlug();
        }
        $pagePath = implode('/', array_reverse($pagePath));

        if ($referenceType == UrlGeneratorInterface::ABSOLUTE_URL) {
            // Absolute URL
            return $schemeAuthority . $this->getContext()->getBaseUrl() . '/' . $pagePath;
        }

        // Absolute path
        return $this->getContext()->getBaseUrl() . '/' . $pagePath;
    }

    /**
     * Returns the HTTP host being requested.
     *
     * The port name will be appended to the host if it's non-standard.
     *
     * @return string
     */
    private function getHttpHost(): string
    {
        $scheme = $this->getContext()->getScheme();

        $port = '';
        if ('http' === $scheme && 80 != $this->context->getHttpPort()) {
            $port = ':'.$this->context->getHttpPort();
        } elseif ('https' === $scheme && 443 != $this->context->getHttpsPort()) {
            $port = ':'.$this->context->getHttpsPort();
        }

        return $this->getContext()->getHost() . $port;
    }
}
```

For example, *Roadiz* CMS handles DTO for each user content, such as pages, blog-posts and allows generating **dynamic** URL using `Router`:

```twig
{% set page = nodeSource %}
{{ path(page) }} {# Here Router generates an URL using DTO attributes #}
```

**Possible Solution**  
Change type hint `UrlGeneratorInterface::generate` `$name` argument to `mixed`. Or provide a more abstract `UrlGeneratorInterface` that will accept `mixed` routes *names* and create a `StaticUrlGeneratorInterface` that will accept only `string` route names.

**Additional context**  
In *Roadiz* CMS, *routes names* can be *objects* in order to generate URL with a dynamic router.

https://github.com/roadiz/roadiz/blob/master/src/Roadiz/Core/Routing/NodeRouter.php#L186

**Comment by fabpot** [comment]
I think that you examples are abusing the interface and were never meant to work. They worked because PHP does not care about types.

**Comment by Tobion** [comment]
See https://github.com/symfony-cmf/Routing/pull/250 how this was solved in the CMF

**Comment by ambroisemaupate** [comment]
Thanks @fabpot @Tobion for your quick and useful answers.

@Tobion I don’t see how you addressed this changes in `Symfony\Bridge\Twig\Extension\RoutingExtension`. I think it could be useful to create a compatibility layer at the point not to introduce such complexity in `path` and `url` *Twig* functions. It should be transparent for front-end developers to use these function with `string` or `object` routes names.

```php
public function getPath($name, $parameters = [], $relative = false)
{
    if (is_string($name)) {
        return $this->generator->generate(
            $name, 
            $parameters, 
            $relative ? UrlGeneratorInterface::RELATIVE_PATH : UrlGeneratorInterface::ABSOLUTE_PATH
        );
    }
    return $this->generator->generate(
        RouteObjectInterface::OBJECT_BASED_ROUTE_NAME, 
        array_merge($parameters, [RouteObjectInterface::ROUTE_OBJECT => $name]), 
        $relative ? UrlGeneratorInterface::RELATIVE_PATH : UrlGeneratorInterface::ABSOLUTE_PATH
    );
}
```

**Comment by Tobion** [comment]
Symfony core does not have objects as route names. The CMF solved it like I linked. Maybe you can do a similar solution in your case. The twig extensions can be overwritten in user-land to support your case as well. Or you write a twig function with a different name that does what you need. But this is not for Core as there are no object route names as I said.

**Comment by Tobion** [comment]
Ref. https://github.com/symfony/symfony/issues/10395

**Comment by ambroisemaupate** [comment]
Ok I see the subject was well debated. So I think we will stick to Symfony interfaces in PHP configuration and classes, but we will add some user-land methods to ease-up Url generation, especially in Twig templates.

**Comment by xabbuh** [comment]
I am closing here as it doesn't  look like there is anything to do here.
