### ISSUE TITLE
[HttpFoundation] IpUtilsTest failure on Alpine

### ISSUE THREAD

**Issue by neclimdul** [symfony/symfony#37076]
**Symfony version(s) affected**: 4.4, 5.0, 5.1

I'm not sure if this is really a bug but IpUtilsTest contains platform specific behavior that means it can't always pass.

```
['::123.234.235.236', '::123.234.235.0'], // deprecated IPv4-compatible IPv6 address
```
This deprecated notation seems to be treated as invalid on alpine/musl and gives a different value.
```
-'::123.234.235.0'
+'::'
```

This is still "anonymized" so I think the underlying method works but it ends up only testing system dependent behaviors of inet_* instead of the method under test.

**How to reproduce**  
The easiest way to reproduce this is with docker installed. Run this in your syfmony checkout.
`docker run --rm -it -v $PWD:/app -w /app php:alpine ./vendor/bin/simple-phpunit ./src/Symfony/Component/HttpFoundation/Tests/IpUtilsTest.php`

**Possible Solution**  
I'm not sure if the case provides any additional coverage so it might be able to be removed.

It also might just be fine the way it is and this issue can serve as a reference for someone else running into it :)

**Comment by nicolas-grekas** [comment]
What's your recommendation? I'm personally fine closing. Alpine is rarely a good choice for Symfony apps.

**Comment by neclimdul** [comment]
I'd probably remove the assertion. The RFC said it didn't need to support it 14 years ago so finding it in the wild seems pretty unlikely and some future glibc or other implementation could treat it as invalid as well. Closing this is fine too though, a test failure outside the test suite is pretty minor and I don't see any bug in the actual code.

I don't understand why you'd knock on alpine though. I run _all_ my symfony apps on alpine containers and this edge case in a test is the first time I've run into any issues. PHP is good at its job of abstracting system specific behaviors, ip2long is just one of those exceptions since it relies on `inet_pton` support and system implementations of inet_pton.

**Comment by nicolas-grekas** [comment]
About Alpine, check https://github.com/symfony/symfony/pulls?q=is%3Apr+alpine+is%3Aclosed :)

I'm fine removing the test case, PR welcome (on the lowest maintained branch where this exists).

Closing meanwhile, thanks for the report.

**Comment by neclimdul** [comment]
Cool, those aren't too scary. Thanks for your work on them.

I'll see about getting you that PR.
