### ISSUE TITLE
[SymfonyForm] Updating to 4.4.9 crash with Unable to get a property on a non-object.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#37072]
**Symfony version(s) affected**: 4.4.9

**Description**  

I'm using a childAdmin with Sonata 
https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/child_admin.html

When I'm on a playList/idPlaylist/video/create url and try to submit the form to create a video and add it to the playlist, I get `Unable to get a property on a non-object.`.

Everything worked fined with symfony-form@4.4.8, but when I update to 4.4.9 I get an error.

**Additional context**  
![image](https://user-images.githubusercontent.com/9052536/83531560-6e1fbe80-a4ed-11ea-81ab-fc5a7a02f71b.png)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue?

**Comment by VincentLanglet** [comment]
Is that https://github.com/ak3l/symfony4/pull/33 enough ? @xabbuh

**Comment by xabbuh** [comment]
I will try to look at it. Maybe this is also "just" the same as (or related to) #37025 and #37027?

**Comment by VincentLanglet** [comment]
I tried https://github.com/symfony/symfony/issues/37027#issuecomment-636954080
And it didn't fix my issue.

It certainly related to the same PR, but I preferred to open a separate issue since the error message wasn't the same.

I've made some investigation
https://github.com/ak3l/symfony4/pull/33#issuecomment-637688634

I can't really do more...

**Comment by xabbuh** [comment]
Can you check if #37085 fixes this by chance?

**Comment by VincentLanglet** [comment]
@xabbuh I tried editing my vendor with your changes, I still get the error

**Comment by xabbuh** [comment]
I tried to checkout your example, but didn't manage to do so. Can you reduce it a bit so that I don't need stuff like Homestead and Vagrant and/or can you post the exact error and the stack trace of the exception?

**Comment by VincentLanglet** [comment]
> I tried to checkout your example, but didn't manage to do so. Can you reduce it a bit so that I don't need stuff like Homestead and Vagrant and/or can you post the exact error and the stack trace of the exception?

I never made a symfony project without a vagrant... What was the issue you encountered ?
This project needs a database, I don't know how to do another way.

Maybe if you provide me a Symfony 4 project with a database which is working on your device, I can reproduce the error. @xabbuh 

The exact error and the stack trace are in the screenshot.
It's coming from the FormValidator line 141.

**Comment by xabbuh** [comment]
> Maybe if you provide me a Symfony 4 project with a database which is working on your device, I can reproduce the error. @xabbuh

You can try the [Symfony Demo application](https://github.com/symfony/demo). It comes with an Sqlite database which can easily be used on any computer.

**Comment by xabbuh** [comment]
@VincentLanglet Please do not spend too much time right now on the example application. I am looking into the `ExpressionLanguage` constraint you mentioned above to see if I can reproduce it without all the rest.

**Comment by VincentLanglet** [comment]
> @VincentLanglet Please do not spend too much time right now on the example application. I am looking into the `ExpressionLanguage` constraint you mentioned above to see if I can reproduce it without all the rest.

If you still need one, I've made https://github.com/VincentLanglet/demo/pull/1 @xabbuh

**Comment by xabbuh** [comment]
Can you try if #37103 fixes this?

**Comment by VincentLanglet** [comment]
> Can you try if #37103 fixes this?

It does on my demo. I will try tomorrow with the project I use for work, but I think you've found the solution :)

**Comment by xabbuh** [comment]
Thank you! :) No we "just" need to write some tests to prevent future regressions.

**Comment by VincentLanglet** [comment]
@xabbuh I just tried on the project I use for work. It does definitely fix the bug :)

**Comment by xabbuh** [comment]
@VincentLanglet Thank you! :)
