### ISSUE TITLE
Return type improvement for InputBag::get

### ISSUE THREAD

**Issue by iquito** [symfony/symfony#37079]
**Symfony version(s) affected**: 5.1.0

**Description**  

When using static analyzers like Psalm or PHPStan the new `InputBag` in HttpFoundation generates a log of false-positives because it states the `get` function can return `string|null`. I have looked at the code of InputBag, and if you define the parameter `$default` as a string then it will never return null:

```php
// Either 'start' exists as a GET variable, or if it does not exist it will return '0' 
// Never returns null!
$start = $request->query->get('start', '0');
```

When using static analyzers this "wrong" return type can generate hundreds of new errors in existing projects (errors starting with `PossiblyNull` in Psalm). The following three lines starting with `@template` would solve this:

```php
/**
 * Returns a string input value by name.
 *
 * @template D of string|null
 * @psalm-param D $default
 * @psalm-return string|D
 *
 * @param string|null $default The default value if the input key does not exist
 *
 * @return string|null
 */
public function get(string $key, $default = null)
```

I wanted to post this as an issue first, but I can make a pull request if this would be accepted. By the way, the `@psalm-param` and `@psalm-return` are used as progressive enhancements to not confuse IDEs or other tools, and both Psalm and PHPStan support them.

**Comment by nicolas-grekas** [comment]
psalm and phpstan have plugins for Symfony, check https://github.com/psalm/psalm-plugin-symfony and https://github.com/phpstan/phpstan-symfony

This issue arises because `InputBag` is new and the plugins need to be made aware of it. Please consider sending a PR there.

**Comment by iquito** [comment]
Sure, I will do that, although I think adding correct DocBlocks right in Symfony would be beneficial long-term too, because they are documenting the behavior and will make Symfony itself be checkable by static analyzers (without plugins).

The generics syntax (`@template`) has settled in the last two years to a certain consensus where if you add the correct DocBlocks in Symfony, anything analyzing the codebase (like IDEs or other tools) could benefit from it, instead of restricting it to a plugin for one specific tool.
