### ISSUE TITLE
Routes not being loaded from config/routes.php

### ISSUE THREAD

**Issue by carlosdiasmarques** [symfony/symfony#37084]
**Symfony version(s) affected**: 5.1.0

**Description**  

Routes configured inside a file **routes.php** are not recognized, resulting in the error "No route found for "GET /something" (404 Not Found)".   When running `debug:router`, these routes are not listed.

The same route works great when configured in `routes.yaml`.

In a different project using `Symfony 5.0.8`, route configuration via `routes.php` works perfectly. 

I don't know if this is really a bug or a case of outdated documentation. The change was made in this [commit](https://github.com/symfony/recipes/commit/5d24d659fc54e2ed564ae93f2f09a2fefe0c850f), that makes the method `configureRoutes` rely only in `.yaml` files.

This following [commit](https://github.com/symfony/recipes/commit/8da7d03c93669667772d4cd9f1f7cd4cd3f9513b) makes it possible to use `.php` files again, but this change was reverted.

**How to reproduce**  
1. Create a controller:
```php
<?php
//src/Controller/SchoolController.php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;

class SchoolController
{
    public function list()
    {
        return new Response('ok');
    }
}
```

2. Create a `routes.php` file:
```php
<?php
//config/routes.php example

use App\Controller;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return function(RoutingConfigurator $routes)
{
    $routes->add('schools_list', '/schools')
        ->controller([Controller\SchoolController::class, 'list'])
        ->methods(['GET']);
};
```
3. Running `debug:router` will result in:
```
 ---------------- -------- -------- ------ -------------------------- 
  Name             Method   Scheme   Host   Path                      
 ---------------- -------- -------- ------ -------------------------- 
  _preview_error   ANY      ANY      ANY    /_error/{code}.{_format}  
 ---------------- -------- -------- ------ -------------------------- 
```
4. Configure the same route inside `routes.yaml`:
```yaml
#config/routes.yaml
schools_list:
    path: /schools
    controller: App\Controller\SchoolController::list
    methods: GET
```
5. Running `debug:router` will result in:
``` 
 ---------------- -------- -------- ------ -------------------------- 
  Name             Method   Scheme   Host   Path                      
 ---------------- -------- -------- ------ -------------------------- 
  _preview_error   ANY      ANY      ANY    /_error/{code}.{_format}  
  schools_list     GET      ANY      ANY    /schools                  
 ---------------- -------- -------- ------ -------------------------- 
```

**Comment by xabbuh** [comment]
The difference probably is that your older kernel takes into account several file extensions inside the `configureRoutes()` method of your `Kernel`.

**Comment by xabbuh** [comment]
see symfony/recipes#705

**Comment by carlosdiasmarques** [comment]
Should that change be mentioned on docs?

In [Creating Routes in YAML, XML or PHP Files](https://symfony.com/doc/current/routing.html#creating-routes-in-yaml-xml-or-php-files) it's said:
> Instead of defining routes in the controller classes, you can define them in a separate YAML, XML or PHP file. The main advantage is that they don't require any extra dependency.

It does not mention the need to adapt your `Kernel.php` if you want to use something different from `.yaml`

**Comment by xabbuh** [comment]
Yes, I think that makes sense. Can you open an issue there please?

**Comment by xabbuh** [comment]
closing here as there is nothing to fix in the code

**Comment by syntaxseed** [comment]
This note was added to the docs:
> New in version 5.1:Starting from Symfony 5.1, by default Symfony only loads the routes defined in YAML format. If you define routes in XML and/or PHP formats, update the src/Kernel.php file to add support for the .xml and .php file extensions.

But there is no information of how to do this. I've tried some StackOverflow answers and they don't work. Simply duplicating the lines in that method to support .php extension doesn't work.

I keep getting this error:

>In TextDescriptor.php line 557:                                                                   
>  Warning: strpos() expects parameter 1 to be string, array given
