### ISSUE TITLE
phpUnitBridge - 5.1.0 - Undefined index: versions - php 7.4.5

### ISSUE THREAD

**Issue by youssefbenhssaien** [symfony/symfony#37086]
**Symfony version(s) affected**: 4.4.8

**Description**  
Working with `Symfony 4.4.8` and `PHP 7.4.5`, having thoses errors after upgrading `symfony/phpunit-bridge` to `5.1.0` : 
- `Notice: Undefined index: versions in /var/www/html/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 185`
- `Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 185`
- `sh: 1: composer: not found`

![image](https://user-images.githubusercontent.com/7301643/83654969-1c933480-a5be-11ea-9c88-aa8fe91baaf8.png)

**How to reproduce**  
1. Install PHP 7.4.5
1. Install Symfony 4.4.8
1. Install phpunit-bridge 5.1.0
1. Run `bin/phpunit`

**Possible Solution**  

**Additional context**  
> Works fine with only downgrading phpunit-bridge to `5.0.8`

- Composer version `1.10.5`
![image](https://user-images.githubusercontent.com/7301643/83658224-39ca0200-a5c2-11ea-99d8-845d626ac900.png)

**Comment by mariusbuescher** [comment]
`symfony/phpunit-bridge` Version 3.4.41 has similar problems.

It also completely ignores the `SYMFONY_PHPUNIT_VERSION` environment variable as well as the automatically determined PHPUnit version from the PHP environment. It currently tries to install PHPUnit in version 9.1.x under all circumstances.
