### ISSUE TITLE
User Deprecated

### ISSUE THREAD

**Issue by jakofys** [symfony/symfony#37098]
**Symfony version(s) affected**: 
symfony/skeleton 5.1.99

**Description**  
Since this version, when i test debug:route command, this info log appears:
"User Deprecated: Since symfony/dependency-injection 5.1: Not setting the attribute "version" of the node "deprecated" is deprecated" without more information

**How to reproduce**  
Just create a skeleton symfony application, and require api, orm-pack and maker-bundle package.
And then, run "debug:route" command.

**Comment by xabbuh** [comment]
Does #37022 help here?

**Comment by jakofys** [comment]
> Does #37022 help here?

Yes, thanks ^^
