### ISSUE TITLE
[PHPUnit-Bridge] symlink phpunit-bridge with relative paths?

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#37099]
**Description**  

We use Docker containers for our symfony app, and inside the Docker container the Symfony app lives on the "/app" directory and everything works fine. However, from time to time I'd like to execute some specific unit tests from my local machine, which has a very different absolute root directory, and phpunit fails with a file not found error, the main reason being PHPUnit Bridge symlinks with an absolute path to the main vendor folder that doesn't exist outside the Docker container. 

```
    "repositories": {
        "phpunit-bridge": {
            "type": "path",
            "url": "/app/vendor/symfony/phpunit-bridge"
        }
    }
```

Would it be possible to symlink using relative paths? Or if not, would it be ok to tell composer to not symlink and mirror instead? Both solutions would work. Happy to send a PR. Not sure also if this could be considered a bug-fix or not.

Thanks!

**Comment by nicolas-grekas** [comment]
The symlink is created by composer. I'm afraid there is nothing we can do here.
Did you try using the "symlink" option of composer, as explained in https://getcomposer.org/doc/05-repositories.md#path ?

Closing as explained.

**Comment by acasademont** [comment]
I'm sorry @nicolas-grekas but this has nothing to do with my composer.json but the composer.json generated by the phpunit bridge here https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L214

Could you please reopen the issue?

**Comment by nicolas-grekas** [comment]
Sure. But as I noted, this link is created by composer...

**Comment by nicolas-grekas** [comment]
An idea might be to replace this symlink by the one you want in your Dockerfile.

**Comment by acasademont** [comment]
On Windows we're already using the "copy" option over the symlink. Is there any reason we might not do the same on Linux?

**Comment by nicolas-grekas** [comment]
> Is there any reason we might not do the same on Linux?

yes: because it's convenient to have one single copy of the bridge when working on the bridge itself.

**Comment by acasademont** [comment]
I agree it's convenient. Another solution might be to use a relative path instead of an absolute one on the symlink, I believe composer doesn't really care about absolute vs relative. I'll try to work on a PR for that.

**Comment by nicolas-grekas** [comment]
@Seldaek just taught me about [the `COMPOSER_MIRROR_PATH_REPOS` env var](https://getcomposer.org/doc/03-cli.md#composer-mirror-path-repos). That looks like the perfect solution, isn't it?

**Comment by acasademont** [comment]
Ah! Yes that would fix it, I added the env variable and it works like a charm, thank you. In case anybody ends up here in the future, this how my bin/phpunit looks like with the changes

```php
#!/usr/bin/env php
<?php

if (!file_exists(dirname(__DIR__).'/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php')) {
    echo "Unable to find the `simple-phpunit.php` script in `vendor/symfony/phpunit-bridge/bin/`.\n";
    exit(1);
}

if (false === getenv('SYMFONY_PHPUNIT_DIR')) {
    putenv('SYMFONY_PHPUNIT_DIR='.__DIR__.'/.phpunit');
}

//We use this Composer ENV variable so that repositories in the bridge are mirrored and not symlinked to avoid Docker issues
if (false === getenv('COMPOSER_MIRROR_PATH_REPOS')) {
    putenv('COMPOSER_MIRROR_PATH_REPOS=1');
}

require dirname(__DIR__).'/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php';
```

Thanks @nicolas-grekas

**Comment by zimzat** [comment]
This appears to be caused by a logic change in Composer in 1.10.4 (released Apr 9) in https://github.com/composer/composer/issues/8700 

When the repository phpunit-bridge sets the path to is absolute, the symlink is now set as absolute.

Is it possible to make the `url` set in the `composer.json` be relative so it reverts to the original behaviour? Or is the recommendation for every project that works with multiple paths (e.g. locally and within a virtual machine) to specify the `COMPOSER_MIRROR_PATH_REPOS`, as recommended above, in their local `bin/phpunit`?
