### ISSUE TITLE
Disc Space management

### ISSUE THREAD

**Issue by DemigodCode** [symfony/symfony#37108]
**Description**  
The WebProfilerBundle is writing all requests into the cache.
In our case we have some more Debug information in the bundle which can be very heavy in using disc space.
A max count of saved request profile data would be very nice, to limit disc space usage.

**Example**  
if(count(profiles) > configMaxValue) {
    deleteOldestProfiling();
}

**Comment by fabpot** [comment]
A while back, we've decided to not manage the storage explicitly in the code. Instead, you can flush the cache by clearing your cache, which should be enough for a debug tool only used in dev.

**Comment by DemigodCode** [comment]
In the meanwhile I found a symfony 4.4 release which should decrease the space using compression.

Wer are using 4.3 right now. Will try to update to 4.4 in the next weeks. Maybe it's low enough then.
Currently 30-60 site requests can be answered before the cache is going to reach 1GB. Then the fs-mount is full and no other site call can be answered.
