### ISSUE TITLE
Global Configuration of CSRF Token Names

### ISSUE THREAD

**Issue by bmendonca** [symfony/symfony#37112]
**Description**  
Allow changing of the default token name by configuration file.

In `framwork.yaml`, we'd be able to do something like:

```
framework:
    csrf_protection: true
    csrf_token_name:my_custom_csrf_token_name
```

In some automated scanners such as OWASP Zap and Tenable.io, the scanner checks for a CSRF token are based on the field name. They look for a form field with a predefined name and id such as "_anticsrf", "csrf", etc. In cases where the CSRF token name used by Symfony are not what the scanner is looking for, a false positive security violation can be detected since the scanner won't recognize that the token field is a valid anti-csrf token.

**Example**  
Instead of `name="form_name[_token]"`, could I designate what the token name can be? i.e: `name="form_name[_csrf_token_custom_name]"` .

This would be something that could be customized at the app/global level rather than configuring each formType options individually as stated in the docs: https://symfony.com/doc/4.4/security/csrf.html#csrf-protection-in-symfony-forms 

```
 public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'      => Task::class,
            // enable/disable CSRF protection for this form
            'csrf_protection' => true,
            // the name of the hidden HTML field that stores the token
            'csrf_field_name' => '_token',
            // an arbitrary string used to generate the value of the token
            // using a different string for each form improves its security
            'csrf_token_id'   => 'task_item',
        ]);
    }
```

This would also be an alternative to writing a custom form type extension.

Some relevant links:

https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/Form/Extension/Csrf/CsrfExtension.php#L42 

https://github.com/symfony/symfony/blob/bdc583cf0eb8ce04704a2fbab543d79abfdb7f4f/src/Symfony/Component/Form/Extension/Csrf/Type/FormTypeCsrfExtension.php#L80-L84 

Does this seem like a good idea compared to writing a form extension and wiring it at a service?
Regardless, thank you for your consideration!

**Comment by rosier** [comment]
You can configure the default token name with:
```
framework:
    form:
        csrf_protection:
            field_name: my_custom_csrf_token_name
```
However this setting seems to be missing from the documentation on https://symfony.com/doc/4.4/reference/configuration/framework.html

I found this setting with `php bin/console config:dump-reference framework`

**Comment by xabbuh** [comment]
Let's close here then.

**Comment by bmendonca** [comment]
> 
> 
> You can configure the default token name with:
> 
> ```
> framework:
>     form:
>         csrf_protection:
>             field_name: my_custom_csrf_token_name
> ```
> 
> However this setting seems to be missing from the documentation on https://symfony.com/doc/4.4/reference/configuration/framework.html
> 
> I found this setting with `php bin/console config:dump-reference framework`

Thank you so much! That's great to know!
