### ISSUE TITLE
"Use of undefined constant STDIN - assumed 'STDIN'"

### ISSUE THREAD

**Issue by francoism90** [symfony/symfony#37124]
**Symfony version(s) affected**: `symfony/console v5.1.0`

**Description**  
I'm keep getting his error on Laravel, I don't know if this should be reported to them or if this is a Symfony issue?

**How to reproduce**  
Update to latest deps.

**Possible Solution**  
I don't think the constant exists when using it as a dep, shouldn't it be checked if it is?

**Additional context**  
Converting the constant works fine, but I don't think this is the solution:
```
public function __construct(OutputInterface $output, $input = 'STDIN')
    {
        $this->output = $output;
        $this->input = $input;
    }
```

**Comment by xabbuh** [comment]
I think #37130 should fix this.

**Comment by francoism90** [comment]
@fabpot  Thanks for the fix. :)
