### ISSUE TITLE
Add option to disable welcome page

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#37129]
**Description**  
Add an option to disable the special 404 error page ("Welcome to Symfony!") which is shown on `/` when you haven't configured any home page yourself.

Reason: When creating an API, you might not have a "home" route. And you might not want to reveal any information when somebody probes `/`.

**Example**  
* Add a boolean option `show_welcome` somewhere (`framework.yaml`?) with default value `true`
* Add an `if` to [Symfony\Component\HttpKernel\EventListener::onKernelException()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L150)

**Comment by ro0NL** [comment]
what if we only show the welcome page, when _no_ routes are configured? :thinking:

**Comment by Tobion** [comment]
Closing as the debug mode is already preventing "probing /" as explained.

**Comment by ThomasLandauer** [comment]
Thanks! I explained this in the docs for https://symfony.com/doc/4.4/reference/configuration/framework.html#debug - see https://github.com/symfony/symfony-docs/pull/13772

I'm not sure if it also applies to Symfony 3.4, so I targeted 4.4.

**Comment by yceruto** [comment]
> Thanks! I explained this in the docs for https://symfony.com/doc/4.4/reference/configuration/framework.html#debug - see [symfony/symfony-docs#13772](https://github.com/symfony/symfony-docs/pull/13772)
> 
> I'm not sure if it also applies to Symfony 3.4, so I targeted 4.4.

Yes, it applies to Symfony 3.4 also

**Comment by ThomasLandauer** [comment]
For Symfony 3.4 it's already explained: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpKernel/Resources/welcome.html.php#L65
