### ISSUE TITLE
Environment variables "APP_SECRET" are never used.

### ISSUE THREAD

**Issue by ralusnom** [symfony/symfony#37123]
**Symfony**: 5.1.x

**Description** 
After upgrading to 5.1.x this error is shown every time, after Cache-Clear Symfony complains:

**Environment variables "APP_SECRET" are never used. Please, check your container's configuration.**

I have the `APP_SECRET` var in my `.env` or `.env.local.php` set. 
Also in framework.yaml
```
framework:
  secret: '%env(APP_SECRET)%'
```

![image](https://user-images.githubusercontent.com/266216/83944998-e47f3200-a807-11ea-85b7-6060ec7e19cb.png)

**How to reproduce**  
`composer update`
wait until cache:clear starts.

**Possible Solution**  
Temporarily removing `'secret' => '%env(APP_SECRET)%',` from `MicroKernelTrait` helps.

```public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(function (ContainerBuilder $container) use ($loader) {
            $container->loadFromExtension('framework', [
         //     'secret' => '%env(APP_SECRET)%',
                'router' => [
                    'resource' => 'kernel::loadRoutes',
                    'type' => 'service',
                ],
            ]);
```

**Comment by ro0NL** [comment]
If it's unused, you are free to remove its reference :) but this raises questions about the default setup for sure.

**Comment by ralusnom** [comment]
The thing is, my application is quite big already, a bazillion of packages installed, so many configs and a little lack of competence leaves me confused with this issue. I tried to set 
```
framework:
  secret: null
```
- what didnt help - and all the other things, disabling, enabling everthing what might be related.. I dunno.
Is it maybe that one of the security, kernel or app setting needs to use this variable, but actually isn't configured?

**Comment by ro0NL** [comment]
Hm, im not fully aware of the current execution flow ... perhaps try overwriting in `configureContainer` from within the kernel class, 

See e.g. this example: https://github.com/symfony/symfony/blob/bdc583cf0eb8ce04704a2fbab543d79abfdb7f4f/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L50-L54

**Comment by ralusnom** [comment]
OH YES , sorry @ro0NL your suggestion worked!
Setting 
```
framework:
  secret: null
```
solved the issue. Sorry, was too confused obviuosly 😃

**Comment by ralusnom** [comment]
But does this affect the "security"?

**Comment by wouterj** [comment]
Well, I think it's a bug. I'm not sure why declaring it twice would result in an error "it is not used". One of them should overwrite the other?
