### ISSUE TITLE
[Form] [Validator] Form with ArrayAccess and field with property_path=>[key] broken

### ISSUE THREAD

**Issue by lucagtc** [symfony/symfony#37125]
**Symfony version(s) affected:** 4.4

**Description**
When form with object $data type ArrayAccess (example Doctrine ArrayCollection) is validate and the field use 'property_path' => '[key]', is generated wrong validation path -> [[key]]. 

**How to reproduce**
Create a form with data type ArrayCollection and add field with property_path => '[key]'. Then insert wrong value and validate.

Here a piece of wrong code (in my opinion)
https://github.com/symfony/symfony/blob/879e68c49b373355342052f8cc9963532b7dd1c5/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L103

**Comment by xabbuh** [comment]
Can you please check if #37085 fixes this?

**Comment by lucagtc** [comment]
Yes, this fix solve my problem.

Thank's

**Comment by xabbuh** [comment]
Thank you for the confirmation. Let's close here then.
