### ISSUE TITLE
bulma_0_layout.html.twig missing in the repository

### ISSUE THREAD

**Issue by sebastianklus** [symfony/symfony#37134]
Hi there,
Just wanted to let you know that the bulma_0_layout.html.twig, that is [referenced in the documentation](https://symfony.com/doc/current/form/form_themes.html#symfony-built-in-form-themes), is currently missing in the repository.

I like the idea of Bulma and Symfony a lot, BTW.
If there still was something missing in the twig file, I'd be happy to try to complete it.

Regards,
Sebastian

**Comment by fabpot** [comment]
The PR has not been merged yet (#36351). So, docs should be fixed.

**Comment by javiereguiluz** [comment]
Docs were updated to remove the reference to this theme.
