### ISSUE TITLE
isGranted() or is_granted() does not accept an array of ROLEs

### ISSUE THREAD

**Issue by tbs-trappy** [symfony/symfony#37132]
**Symfony version(s) affected**: all

**Description**  
Passing an array into is_granted always returns false, while checking for the same as a individual role does not return false. according to the documentation, is_granted is supposed to support arrays as well as strings.

**How to reproduce**
{{ dump(is_granted(["ROLE_ADMIN"]) }} 
{{ dump(is_granted("ROLE_ADMIN")) }} 

**Possible Solution**  
security-core/Authorization/Voter/RoleVoter.php
line 39++ needs to be rewritten to accept an array of $attribute in order to satisfy the specification that is_granted can accept both string and string[] (ref: https://symfony.com/doc/current/reference/twig_reference.html#is-granted)

**Comment by xabbuh** [comment]
Being able to vote on multiple attributes was deprecated in Symfony 4 and this feature was dropped in 5.0. There is nothing to change here so I am going to close this issue. Thank you for understanding.

**Comment by tbs-trappy** [comment]
OK. wouldn't this need to be updated in that case on the documentations? sorry for wasting your time, I couldn't find anything about the deprecation.

**Comment by xabbuh** [comment]
Can you please open an issue in the docs repository and point to the places where we still document this wrongly?

**Comment by tbs-trappy** [comment]
the place that I was following was here:
https://symfony.com/doc/current/reference/twig_reference.html#is-granted

I have created the issue and referenced back to here. thanky you!

**Comment by sovetski** [comment]
I don't understand, passing an array with Symfony 6.x work for me

Anyone can explain what happended please?
