### ISSUE TITLE
[PropertyInfo] Bug creating the Type for a property 'self' with PHPDocumentor

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#37149]
**Symfony version(s) affected**: All current supported versions

**Description**  
The class name specified if the return type is `self` will become `elf`. However ideally it should return the name of the class that the property belongs to.

**How to reproduce**  
It has been picked up as an issue in API Platform here: https://github.com/api-platform/core/issues/3344 - if there is an annotation `@return self` - the `Type` object returned will define the class as `elf`

**Possible Solution**  
The simplest fix that I can see would be adding it to the list of unsupported return types here:
https://github.com/symfony/property-info/blob/82d9fc8b6a531f479d9545e229f8a5e35dc12775/Util/PhpDocTypeHelper.php#L98

If possible it'd be better to return the FQCN of the object - but I'm not sure how that would work if a patch is applied to also support the return type `static` that looks to be coming in PHP 8.

**Comment by xabbuh** [comment]
see #40208
