### ISSUE TITLE
Constraint Language in Constraint All not translated

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#37143]
**Symfony version(s) affected**: 5.1.0

**Description** 
Hi,

When I use a Language constraint in an All constraint, the Language constraint is not translated

The code below does return `user.languages_invalid`. It is "This value is not valid." who returned.

```php
// src/Entity/User.php

/**
 * @ORM\Column(type="simple_array")
 * @Assert\All({
 *     @Assert\Language(
 *         message="user.languages_invalid"
 *     )
 * })
 */
private $languages = [];
```

The code below returns well `user.language_invalid`
```php
// src/Entity/User.php

/**
 * @ORM\Column(type="string")
 * @Assert\Language(message="user.language_invalid")
 */
private $language;
```

Thanks for reply :)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by seb-jean** [comment]
It's good for me in fact.
The message came from the "invalid_message" parameter of the Form Type LanguageType
