### ISSUE TITLE
[MIME] Method getMimeType() returns wrong SVG format

### ISSUE THREAD

**Issue by filipbekic01** [symfony/symfony#37148]
**Symfony version(s) affected**: 5.0.0

**Description**  
It's about `symfony/mime` package.

When uploading `image/svg+xml` file, method `getMimeType()` returns `image/svg` instead. It cuts `+xml` suffix for some reason. 

**How to reproduce**  
Simply call `getMimeType()` on uploaded file in controller or wherever.

**Comment by filipbekic01** [comment]
Actually i found that even the native PHP method `finfo` returns `image/svg` only.

```
 $finfo = new finfo(FILEINFO_MIME_TYPE);
 die(var_dump($finfo->file($_FILES['file']['tmp_name'])));

**Comment by filipbekic01** [comment]
There is PHP bug report on this https://bugs.php.net/bug.php?id=79045

**Comment by nicolas-grekas** [comment]
Thanks for investigating. That's not on Symfony then, isn't it?

**Comment by filipbekic01** [comment]
No it's not, i found it's PHP bug, sorry for opening ticket here.
