### ISSUE TITLE
Adding translation:add or translation:create command

### ISSUE THREAD

**Issue by Anteste** [symfony/symfony#37156]
**Description**  
The command "translation:update" of the symfony framework-bundle parses the templates in search of strings to translate. It cannot take into account translations from a service or a controller, or dynamic strings (eg: {{ ("status" ~ entity.status)|trans }}). It is a bit burdensome to add translations manually. What do you thing about adding a command "translation:add" or "translation: create" to add translation from the console ?

I'd be happy to contribute on this topic if the core team thinks it's a good idea.

**Comment by yceruto** [comment]
duplicated of https://github.com/symfony/symfony/issues/36830
