### ISSUE TITLE
Delete Class Ace

### ISSUE THREAD

**Issue by samsamm777** [symfony/symfony#3715]
Having some issues with this code...

		// creating the ACL
		$aclProvider = $this->get('security.acl.provider');
		$objectIdentity = new ObjectIdentity($acl->getClassIdentifer(), $acl->getClass());
		$currentAcl = $aclProvider->findAcl($objectIdentity);
		
		$classACEs = $currentAcl->getClassAces();
		foreach ( $classACEs as $index => $classACE ) {
			$currentAcl->deleteClassAce($index);						
		}
		$aclProvider->updateAcl($currentAcl);

Im thinking there may be a bug in the deleteClassAce function? Gives an error "The index '1' does not exist."

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
