### ISSUE TITLE
Check if the password is a valid password hash

### ISSUE THREAD

**Issue by UtechtDustin** [symfony/symfony#37170]
Today i migrated a old silex application to symfony, anything worked fine on mine develop server.
As i tried to deploy it to our productionsystem, i always got a BadCredentialsException while logging in.

Silex used bcrypt for password hashing on symfony i choosed argon2.
On the first loggin Symfony tried to set the new argon2 hash which is nice.
But on the second login i always got the BadCredentialsException.

I spend almost 3 hours to find out that the database field was VARCHAR(60).
That means the passwordhash was cut and symfony always throw that exception.

Would it make sense to check if the password is a valid hash ?

**Comment by stof** [comment]
Well, the thing is, how do you know that ?

The root cause of the issue here is rather than you have your MySQL server configured in non-strict mode and so truncating data instead of failing...

**Comment by UtechtDustin** [comment]
@stof This was just an idea, im not sure if this is possible to check.
But does hashes dont have a pattern which is checkable ?

A lot of applications runs on webspaces, you get a database access but you cant configure the server so this is not possible.

**Comment by stof** [comment]
well, each algorithm may produce a different length, and there is no automatic way to know that AFAIK (well, we would have to compute a hash and compare the length, assuming that the output is fixed length).

**Comment by UtechtDustin** [comment]
It was just a quick idea, but if this is not possible then the issue can be closed.

**Comment by wouterj** [comment]
I think it'll be quite hard to implement (especially because we now recommend using the "auto" encoder and we don't know what the future holds 🔮).

Do you hink it would make sense to add a warning to the documentation about the database column length? Would that have solved this problem or made finding the error easier?

**Comment by UtechtDustin** [comment]
@wouterj If this is to hard (or not possible) then forget my idea.

I guess the documentation dont need a update, maybe this is just a edge case because i upgraded an old (silex) application to symfony with the same database.

**Comment by xabbuh** [comment]
Let's close here then.
