### ISSUE TITLE
[Translator] debug:translation doesn't show the correct fallback

### ISSUE THREAD

**Issue by Growiel** [symfony/symfony#37184]
**Symfony version(s) affected**: 5.1.0 at least

**Description**  
When running `debug:translation` with the locale `fr_FR` I expect the command to show me three things: `fr_FR`, `fr` and whatever the `default_locale` is configured to.

However, the `fr` column is missing:

![Screenshot from 2020-06-10 12-04-03](https://user-images.githubusercontent.com/5228735/84255189-907b9280-ab12-11ea-976e-c5d1cacee746.png)

I feel like the correct output should be:

![Screenshot from 2020-06-10 12-05-47](https://user-images.githubusercontent.com/5228735/84255319-bdc84080-ab12-11ea-998b-e38647daad02.png)

The reasoning being that most of the time, the value from the "main" locale is good enough and I'd like to see if it's a translation that's really missing, or if I can live with it being defined in the fallback `fr`.

Also, this would be match what actually happens when you use `$translator->trans()`. 
It's been confusing to see the `debug:translation` command say one thing and the output of `trans()` say another.

**How to reproduce**  
- Install the `translation` bundle.
- Create a `messages.fr.yaml` file in `/translations`, add a key inside, for example `gender.other: 'Autre'`.
- Create a `messages.en.yaml` file in `/translations`, add a key inside, for example `gender.other: 'Other'`.
- Do NOT create a `messages.fr_FR.yaml`.
- Run the command: `php bin/console debug:translation fr_FR --domain=messages` , get the following output:

![Screenshot from 2020-06-10 12-04-03](https://user-images.githubusercontent.com/5228735/84255189-907b9280-ab12-11ea-976e-c5d1cacee746.png)

**Comment by YaFou** [comment]
I can't reproduce your issue. I followed each steps without success. I used Symfony `5.1.3`. Could you provide a repository that reproduce this bug?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Growiel** [comment]
Sorry guys I got super busy.

As requested here's the repository with the bug:

https://github.com/Growiel/translator_bug

I was missing a step in my "how to reproduce" which is why you couldn't reproduce.

Just clone the repository and run the command, you'll see that the preview message for `fr_FR` is not the one from `fr`.

However, if you go to the page `/foo`, you'll see that the actual value used when using the `fr_FR` locale is indeed the value from `fr`.

Let me know if you need more help.
