### ISSUE TITLE
Symfony Upgrade from 4.3 to 4.4

### ISSUE THREAD

**Issue by Raistlfiren** [symfony/symfony#37197]
**Symfony version(s) affected**: 4.4.*

**Description**  
When updating from 4.3 to 4.4, I am receiving the following error - "The DoctrineBundle is not registered in your application. Try running "composer require symfony/orm-pack"."

**Possible Solution**  
https://github.com/doctrine/DoctrineBundle/issues/804

**Additional context**  

Running /usr/local/php5/bin/php ./bin/console debug:container "doctrine" shows:
Information for Service "doctrine"
```
==================================

 References all Doctrine connections and entity managers in a given Container.

 ---------------- ----------------------------------------- 
  Option           Value                                    
 ---------------- ----------------------------------------- 
  Service ID       doctrine                                 
  Class            Doctrine\Bundle\DoctrineBundle\Registry  
  Tags             -                                        
  Public           yes                                      
  Synthetic        no                                       
  Lazy             no                                       
  Shared           yes                                      
  Abstract         no                                       
  Autowired        no                                       
  Autoconfigured   no                                       
 ---------------- ----------------------------------------- 

```

**Comment by Tobion** [comment]
Have you done https://github.com/doctrine/DoctrineBundle/issues/804#issuecomment-382760362 ? Does it not solve the problem?

**Comment by Raistlfiren** [comment]
@Tobion  - I guess I am confused on how I would update this. I look in my composer.json file and see `"symfony/framework-bundle": "4.4.*"`. I am unsure how to get 1.9.1. If I look at the `AbstractController` it has the following -

```php
public static function getSubscribedServices()
    {
        return [
            'router' => '?'.RouterInterface::class,
            'request_stack' => '?'.RequestStack::class,
            'http_kernel' => '?'.HttpKernelInterface::class,
            'serializer' => '?'.SerializerInterface::class,
            'session' => '?'.SessionInterface::class,
            'security.authorization_checker' => '?'.AuthorizationCheckerInterface::class,
            'templating' => '?'.EngineInterface::class,
            'twig' => '?'.Environment::class,
            'doctrine' => '?'.ManagerRegistry::class,
            'form.factory' => '?'.FormFactoryInterface::class,
            'security.token_storage' => '?'.TokenStorageInterface::class,
            'security.csrf.token_manager' => '?'.CsrfTokenManagerInterface::class,
            'parameter_bag' => '?'.ContainerBagInterface::class,
            'message_bus' => '?'.MessageBusInterface::class,
            'messenger.default_bus' => '?'.MessageBusInterface::class,
        ];
    }
```

**Comment by Tobion** [comment]
You need to update doctrine/doctrine-bundle not symfony/framework-bundle for the bug fix.

So `composer update doctrine/doctrine-bundle`

I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by Raistlfiren** [comment]
Thank you @Tobion! I wasn't expecting a BC break for a minor version upgrade. That resolved the issue though.
