### ISSUE TITLE
Dotenv default value changed

### ISSUE THREAD

**Issue by rkeet** [symfony/symfony#37195]
**Symfony version(s) affected**: 5.1
**Description**  

`config/bootstrap.php` does a `(new Dotenv(false))-> { ... }` call. 

Since SF 5.1 (maybe earlier, in the middle of things and this popped up in phpunit): `Since symfony/dotenv 5.1: Passing a boolean to the constructor of "Symfony\Component\Dotenv\Dotenv" is deprecated, use "Dotenv::usePutenv()"`

However, this used to be: 

    public function __construct(bool $usePutenv = false)
    {
        $this->usePutenv = $usePutenv;
    }

(prev version: https://github.com/symfony/dotenv/blame/e10ca028fa8fa7b816813bc2f7ee9eeafc2669bb/Dotenv.php)

It is now: 

    public function usePutenv($usePutenv = true): self
    {
        $this->usePutenv = $usePutenv;

        return $this;
    }

(current: https://github.com/symfony/dotenv/blame/465e7eed76324919b6693311f9b74dde8f54ccd7/Dotenv.php#L74)

Docs from old constructor have been copied to new setter function: 

    /**
     * @var bool If `putenv()` should be used to define environment variables or not.
     *           Beware that `putenv()` is not thread safe, that's why this setting defaults to false
     */

As it says the now default `true` value is not thread safe, should it be the default?

**Possible Solution**  

If intentional: close ticket. 

If this may cause issues, change `true` to `false`

**Additional context**  

Links provided in desription

**Comment by xabbuh** [comment]
I think there is a misunderstanding. The Dotenv component will not call `putenv()` by default. In previous versions one could opt-in for this feature by passing `true` to the constructor of the `Dotenv` class. This is now deprecated as the signature will be changed in 6.0 to accept only `$envKey` and `$debugKey` arguments. If you now would like to have the `putenv()` calls being made, you will have to call the new `usePutenv()` method. However, if you passed `false` before, the only change you need to do is to fully remove this argument (you do not need to call `usePutenv()` then).
