### ISSUE TITLE
[Console] option parsed incorrectly

### ISSUE THREAD

**Issue by nerg4l** [symfony/symfony#37210]
**Symfony version(s) affected**: 4.4.8

**Description**  

When I add a string argument to a command which starts with one dash or double dash, the dash parsed as an option. I should be able to use quotes to "escape" a dash.

**How to reproduce**  

1. Create a command with one argument.
2. Run the command with one argument where the argument is wrapped in quotes and contains a dash as the first character.

```
cli.php "- "
```

3. This throws `RuntimeException` with the following message:

> The "- " option does not exist.

**Possible Solution**  

--

**Additional context**  

It does not happen when the first char is not a dash.

**Comment by chalasr** [comment]
Thanks for the report, but I'm not sure we can do anything here TBH. 
Per http://docopt.org

> Words starting with one or two dashes (with exception of "-", "--" by themselves) are interpreted as short (one-letter) or long options, respectively.

If you feel like giving it a try, please do.
I'm closing as "won't fix"  meanwhile.

**Comment by nerg4l** [comment]
Shouldn't quotes (`'` and `"`) escape a string? For example not parse `StringInput` token as an `ArgvInput` because it is a parameter value.

On the try page of http://docopt.org I can use quotes to escape a string. Link for an example: http://try.docopt.org/?doc=Naval+Fate.%0D%0A%0D%0AUsage%3A%0D%0A++naval_fate.py+<name>%0D%0A%0D%0A&argv=%27-a%27

Furthermore, docopt is a "Command-line interface description language"which parses a description of a command and not a cli command. Am I wrong?

**Comment by nerg4l** [comment]
https://www.gnu.org/software/bash/manual/bash.html#Quoting

- Single Quotes
> Enclosing characters in single quotes (‘'’) preserves the literal value of each character within the quotes. [...]

- Double Quotes
> Enclosing characters in double quotes (‘"’) preserves the literal value of all characters within the quotes, with the exception of ‘$’, ‘`’, ‘\’, and, when history expansion is enabled, ‘!’. [...]

**Comment by wouterj** [comment]
IIRC, you can use the `--` character for this, see also the docopt specs:

> A double dash "--", when not part of an option, is often used as a convention to separate options and positional arguments, in order to handle cases when, e.g., file names could be mistaken for options.

`cli.php -- '- '` should work

Please note that `- ` also doesn't work on docopt: http://try.docopt.org/?doc=Naval+Fate.%0D%0A%0D%0AUsage%3A%0D%0A++naval_fate.py+%3Cname%3E%0D%0A%0D%0A&argv=%27-+%27

**Comment by nerg4l** [comment]
Thanks for the suggestion about the double-dash. I can make it work with that. However, I opened an issue in the reference docpot implementation to see if they plan to fix it or not.
