### ISSUE TITLE
[String] AsciiSlugger : iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE//TRANSLIT' is not allowed

### ISSUE THREAD

**Issue by gnutix** [symfony/symfony#37213]
**Symfony version(s) affected**: 5.0.7

**Description**  
Passing extended UTF-8 characters into `AsciSlugger->slug()` throws an error : 

```
iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE//TRANSLIT' is not allowed
```

Stacktrace: ![image](https://user-images.githubusercontent.com/310134/84384496-60a1bd00-abee-11ea-9a12-2f271193c575.png)

**How to reproduce**  
```php
<?php
use Symfony\Component\String\Slugger\AsciiSlugger;

(new AsciiSlugger())->slug('😋');
```

I tried with an emoji `😋` and a braille character `⠚`, but probably that other characters have the same fate.

**Possible Solutions**  
1. Remove the characters that would trigger this error (preemptively or by catching it)
2. Delegate the decision to the user by providing a callable to the slug method that would receive the "faulty" character as input : 

```php
use Symfony\Component\String\Slugger\AsciiSlugger;

$slug = (new AsciiSlugger())->slug('😋', '-', null, fn(string $c) => '');

var_dump($slug->toString()); // outputs ""
```

**Additional context**  
Here's a list of characters to play with : https://www.utf8-chartable.de/unicode-utf8-table.pl

**Comment by nicolas-grekas** [comment]
I don't reproduce this warning, can you please share the output of running this command?
```sh
php --ri iconv
```

**Comment by gnutix** [comment]
On my local machine : 

```
iconv

iconv support => enabled
iconv implementation => glibc
iconv library version => 2.27

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value
```

from inside our Docker container based on `php:7.2.28-fpm-alpine` : 

```
iconv

iconv support => enabled
iconv implementation => unknown
iconv library version => unknown

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value
```

**Comment by gnutix** [comment]
```php
<?php
use Symfony\Component\String\Slugger\AsciiSlugger;
require_once __DIR__.'/../vendor/autoload.php';

$slug = (new AsciiSlugger())->slug('a😋b');
echo 'Result: '.$slug;
```

```
me@my-local-machine $ php var/test.php
Result: a-b
```

So it confirms that the issue lies within my Docker environment.
Any idea how I could fix it ?

**Comment by nicolas-grekas** [comment]
Move away from alpine, it's defective...

**Comment by nicolas-grekas** [comment]
Of course, we might want to provide some better behavior than a warning.
For reference: https://wiki.musl-libc.org/functional-differences-from-glibc.html#iconv

**Comment by gnutix** [comment]
We will soon switch our infra to match the local setup with the prod environment, thus throwing out alpine. In the meantime, I've found this fix which should work : https://github.com/wallabag/docker/pull/158/files

**Comment by Tarasovych** [comment]
@gnutix have you managed to run your `test.php` under Alpine? I have that `LD_PRELOAD` in my Dockerfile, but still getting an exception
> "Symfony\Component\String\UnicodeString" requires a translit-able iconv implementation, try installing "gnu-libiconv" if you're using Alpine Linux

**Comment by thirdwheel** [comment]
I had this error when running composer install on another project. I changed out iconv for mbstring and it worked.

**Comment by bootmii** [comment]
There is a correct ASCII mapping for dots 256, and that's `J`.
