### ISSUE TITLE
Router cache warmer with multiple routers

### ISSUE THREAD

**Issue by alexpozzi** [symfony/symfony#37221]
**Symfony version(s) affected**: 4.4.8

**Description**  
On my project I have multiple routers with different contexts that all needs to be cached.
For every router service I configured a different cache directory (as described in the docs) and a cache warmer service.
When warming up the cache, the system seems not to care about the configured router cache directory and caches everything under the base cache directory.
The result is that the router cached files are overridden and their content includes just the last warmed up router.

**How to reproduce** 
Here you can find an example router configuration to be able to reproduce the issue
```
services:
    App\Router\First:
        class: Symfony\Bundle\FrameworkBundle\Routing\Router
        arguments:
            - '@Symfony\Component\DependencyInjection\ContainerInterface'
            - '%kernel.root_dir%/config/routes_first.yml'
            - cache_dir: '%kernel.cache_dir%/firstRouter'
              debug: '%kernel.debug%'
            - '@App\Router\First\Context'
        calls:
            - [ setConfigCacheFactory, [ '@config_cache_factory' ] ]

    App\Router\First\CacheWarmer:
        class: Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: 'container.service_subscriber', id: 'App\Router\First', key: 'router' }
            - { name: 'kernel.cache_warmer' }

    App\Router\Second:
        class: Symfony\Bundle\FrameworkBundle\Routing\Router
        arguments:
            - '@Symfony\Component\DependencyInjection\ContainerInterface'
            - '%kernel.root_dir%/config/routes_second.yml'
            - cache_dir: '%kernel.cache_dir%/secondRouter'
              debug: '%kernel.debug%'
            - '@App\Router\Second\Context'
        calls:
            - [ setConfigCacheFactory, [ '@config_cache_factory' ] ]

    App\Router\Second\CacheWarmer:
        class: Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: 'container.service_subscriber', id: 'App\Router\Second', key: 'router' }
            - { name: 'kernel.cache_warmer' }
```

**Additional context**  
I saw that the [Router::warmUp method](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L91-L104) called by the RouterCacheWarmer service overrides the router configured cache directory and, I guess, this is the reason of my issue.

If, instead of using different cache directories, I use the deprecated `generator_cache_class` and `matcher_cache_class` options to set different cache classes for every router, everything works correctly.

Is this a bug or just a mis-configuration on my side?

**Comment by Tobion** [comment]
The cache warming warms up the cache in a temporary directory AFAIK which is then renamed. For this reason, the it uses the argument to warmUp() instead of the configured route cache dir. You could probably just extend the RouterCacheWarmer and change the warmup dir to be different for both routers.

**Comment by alexpozzi** [comment]
IIRC the cache directory passed by the cache warmer was the `kernel.cache_dir` and not a temporary directory.
I'm gonna have a look at it again to see if I can improve my code.
For the moment I just extended the base [Router](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php) class and overridden the `warmUp` method in order to save cached files in the configured directory.

Thanks!

**Comment by alexpozzi** [comment]
I'm gonna close this issue as I did find a workaround for the problem.

**Comment by philge-k** [comment]
> IIRC the cache directory passed by the cache warmer was the `kernel.cache_dir` and not a temporary directory. I'm gonna have a look at it again to see if I can improve my code. For the moment I just extended the base [Router](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php) class and overridden the `warmUp` method in order to save cached files in the configured directory.
> 
> Thanks!

Was this your workaround or did you find something else?
