### ISSUE TITLE
Messages in ICU format are not handled

### ISSUE THREAD

**Issue by someonewithpc** [symfony/symfony#37228]
**Symfony version(s) affected**: 5.1.0

**Description**  
Messages written in the ICU format are not being translated properly. By this I mean that the ICU format string itself is returned. I assume I'm doing something wrong, since I ran the tests in `symfony/translation` and they all pass, and I saw that some tested for what I'm trying to do.

I used the example from [the documentation](https://symfony.com/doc/current/translation/message_format.html#pluralization). I tried it in tests and in a controller.

**How to reproduce**  
tests:

```
static::bootKernel();
$translator = static::$container->get(TranslatorInterface::class);
static::assertSame('2 apples', $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 2]));
```

controller:

```
echo $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 0]);
echo $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 0], 'foo+intl-icu');
echo $translator->trans('num_of_apples', ['apples' => 1], 'foo+intl-icu');
```
and `foo+intl-icu.en.yaml` has (from [this doc page](https://symfony.com/doc/current/translation/message_format.html#pluralization))

```
num_of_apples: >-
    {apples, plural,
        =0    {There are no apples}
        one   {There is one apple...}
        other {There are # apples!}
    }
```

(different on purpose to make sure the file was being loaded)

**Additional context** 

The outputs from the controller are:

```
{0, plural, =1 {1 apple} other {0 apples}}
{0, plural, =1 {1 apple} other {0 apples}}
{1, plural, =0 {There are no 1} one {There is one apple...} other {There are # 1!} }
```

I also tested on a new project.

**Comment by stof** [comment]
Support for the ICU format was added for keys loaded from catalogues opting-in through the `+intl-icu` in their name.
Here, your test does not use the `num_of_apples` key defined in such a file. So there is no reason for the ICU formatter to be used.

**Comment by someonewithpc** [comment]
Uh... Yes it does. The file is called `foo+intl-icu.en.yaml` and the domain on the call matches. It must be something else.

**Comment by stof** [comment]
The **only** key in your `foo+intl-icu.en.yaml` is the `num_of_apples` one. and that is **not** the key you pass to the translator in your test.

**Comment by someonewithpc** [comment]
@stof but it is in the controller. Walk me through the process, please. Do I need to use symbolic messages? They need to be in a file labeled `+intl-icu`, correct? Does the domain I use when asking for the message also have to have `+intl-icu`? Is there any other step missing? Because I think I did all those steps.

**Comment by stof** [comment]
you need to pass `foo` as domain, not `foo+intl-icu`. The `+intl-icu` is added by the translator to try the optin on top of what you pass. So if you pass `foo+intl-icu`, the file would need to be named `foo+intl-icu+intl-icu` to optin

**Comment by someonewithpc** [comment]
Okay, that does work, but is there no way to use the messages inplace? Because my goal was to write a wrapper that would convert a string or array of strings and parameters to the ICU and pass it to trans. Is that not possible? What is the function that handles the ICU conversion?

**Comment by stof** [comment]
If you have a string using the ICU format already and you want to apply the formatting, use the [MessageFormatter](https://www.php.net/MessageFormatter) class of PHP directly.

**Comment by someonewithpc** [comment]
Okay, thanks for the help and sorry for the bother

**Comment by someonewithpc** [comment]
Okay, I've been doing some more testing and I still believe this is a bug. @stof your proposed solution would have me reimplementing a big part of the translation module, which is not what I'm after. I'll make a PR.

My goal is to be able to do the following

```
$apples = [1 => '1 apple', '{count} apples'];
echo _m($apples, ['{count}' => 0]);
```

where `_m` is implemented in terms of `trans`, but if given an array, converts the array to the ICU format,
