### ISSUE TITLE
[console] debug:container SessionHandlerInterface

### ISSUE THREAD

**Issue by ybenhssaien** [symfony/symfony#37245]
**Symfony version(s) affected**: 4.4.9

**Description**  
- Looking for `session.handler` by running `bin/console debug:container session.handler-v`  we get the result 
![image](https://user-images.githubusercontent.com/7301643/84495983-6eb61300-acac-11ea-9406-2a243729b231.png)

- But running a `bin/console debug:container SessionHandlerInterface -v`  we get `[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "session.handler".`
![image](https://user-images.githubusercontent.com/7301643/84496026-7f668900-acac-11ea-9ede-2f7737406de9.png)

**How to reproduce**  
- Without any Service implements SessionHandlerInterface (the case for a fresh symfony installation from skeleton)
- Run the console command : `bin/console debug:container SessionHandlerInterface -v`

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
@youssefbenhssaien would you like to have a closer look and submit a PR?
