### ISSUE TITLE
Expression Language throws different errors in DEV and PROD environment

### ISSUE THREAD

**Issue by fabioflx** [symfony/symfony#37249]
**Symfony version(s) affected**: 5.1.0

**Description**  
The evaluation of an expression on an empty resource throws two different errors between the DEV and PROD environments. 

**How to reproduce**
This only works in development environment:
```
try {  
  $result = (new ExpressionLanguage)->evaluate('value', []);
} catch (ErrorException $e) {
  ...
}
```
While this only works in production environment:
```
try {  
  $result = (new ExpressionLanguage)->evaluate('value', []);
} catch (RuntimeException $e) {
  ...
}
```

**Possible Solution**  
The solution I am using for the moment is to catch a generic Exception instead.

**Comment by xabbuh** [comment]
What is the FQCN of both exceptions when being thrown and what is the exception message respectively?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
