### ISSUE TITLE
You have requested a non-existent parameter "kernel.secret"

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#37256]
Hi!

**Symfony version(s) affected**: 5.1.1

**Description**  
Maybe BC, maybe just a docs issue:
I have remember me functionality on my site, as shown in the docs, here: https://symfony.com/doc/current/security/remember_me.html

After 5.1.1 I got the error in the title.

**How to reproduce**  

**Possible Solution**  
readd the variable or update the docs to use  `secret: '%env(APP_SECRET)%'` instead of  `secret: '%kernel.secret%'`

**Additional context**  
Maybe related to this PR: https://github.com/symfony/symfony/pull/37154

**Comment by mmarton** [comment]
@nicolas-grekas could you clarify what's the right way here?

**Comment by nicolas-grekas** [comment]
Related yes, here is the patch you need to apply to you config:

```diff
--- a/config/packages/framework.yaml
+++ b/config/packages/framework.yaml
@@ -1,4 +1,5 @@
 framework:
+    secret: '%env(APP_SECRET)%'
     #csrf_protection: true
     #http_method_override: true
```

**Comment by mmarton** [comment]
Should I close it, or can you move to docs?

**Comment by nicolas-grekas** [comment]
The recipe has been updated already. There's nothing else to do I think. Apps that use the "broken" recipe will need to be updated...

**Comment by mmarton** [comment]
I've ment because of the remember_me part of the docs

**Comment by nicolas-grekas** [comment]
Oh. No need to patch the doc, the above one is all we need here.
