### ISSUE TITLE
 Login throttling

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#37266]
Hi :)

It would be great to have an option for the connection to limit the number of failed login attempts over a period of time.

Thanks :)

**Comment by simonberger** [comment]
This is part of #30914 but there seems to exist no specific issue yet.
It could be noted behind the entry of the rework tasks
/cc @curry684

**Comment by fabpot** [comment]
Closing here as this is already part of #30914

**Comment by curry684** [comment]
> there seems to exist no specific issue yet.

Simply means nobody is working on it publicly. #30914 is a tracker issue grouping a ton of marginally related tasks to get security up to date. Once somebody picks it up the PR will be the tracker.

**Comment by simonberger** [comment]
> Simply means nobody is working on it publicly. #30914 is a tracker issue grouping a ton of marginally related tasks to get security up to date. Once somebody picks it up the PR will be the tracker.

I added the note because I was surprised there was no issue for it yet.
I do not really agree to close this. The tracker issue #30914 can still change a lot and entries being removed.

**Comment by curry684** [comment]
There is no added value in this issue now - it's just reiterating the task in the tracker issue. If it would have been a full proposal with a screen of specs it would've been a different case, now it's just a duplicate.

It should also be noted that https://github.com/symfony/symfony/pull/33558 added `VerifyAuthenticatorCredentialsEvent` and `LoginFailed` events which can be trivially used to implement login throttling.  First class citizen support is just a wishlist item on top of that.

**Comment by wouterj** [comment]
Yeah, I would recommend creating a listener on these events and storing a count in the session. We don't need to add this to the "legacy" security system.

I think Laravel's [`ThrottlesLogins`](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Auth/ThrottlesLogins.php#L91-L94) implementation can function as example on how to do this.

**Comment by fabpot** [comment]
Implemented in 5.2.

**Comment by seb-jean** [comment]
Thanks all!
