### ISSUE TITLE
[security-bundle] Unable to connect on a test environment

### ISSUE THREAD

**Issue by rimoi** [symfony/symfony#37285]
**Symfony version(s) affected**: 5.1.1

**Description**  
When i'm in a **test** environment i can't connect, i think it's the csrf token that blocks my connection!

_Info:_ I use the **security component** 

Someone has an idea how to fix this?
Thanks

**Comment by wouterj** [comment]
Yes, this is probably related to https://github.com/symfony/symfony/issues/37277#issuecomment-643776018 .

**Comment by chalasr** [comment]
Closing as duplicate of #37277.
