### ISSUE TITLE
[Config] Soft BC break in `->setDeprecated()`

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#37284]
**Symfony version(s) affected**: 5.1.x

**Description**  
There is a soft BC break in the new features for `->setDeprecated()` in the config builder.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/BaseNode.php#L208

**How to reproduce**  
```diff
-    public function setDeprecated(?string $message)
+    public function setDeprecated(?string $package/*, string $version, string $message = 'The child node "%node%" at path "%path%" is deprecated.' */)
```
Adding the parameters at the front makes it impossible to both support 5.1+ and <5.1 as a bundle.

If you use the intended 5.1+ way:

```php
->setDeprecated("my/bundle", "1.0", "this node is deprecated, do sth else")
```

* in 5.1+ we will show the message "this node is deprecated, do sth else"
* in <5.1 we will show the message "my/bundle"

Is there a (non-hacky) way to have the real message in both versions?

**Possible Solution**  
No idea. Avoiding a second BC break would be great, but the current version is rather unhelpful for lower symfony versions -- that might warrant a second break?

**Additional context**  

This is a separate ticket, to get visibility on this issue from this comment: https://github.com/symfony/symfony/pull/35871#discussion_r439030773

/cc @nicolas-grekas @atailouloute as you authored / merged this. wdyt?

**Comment by nicolas-grekas** [comment]
DoctrineBundle solved this nicely I think, with a helper, see
https://github.com/doctrine/DoctrineBundle/blob/2.0.x/DependencyInjection/Configuration.php#L95

**Comment by apfelbox** [comment]
@nicolas-grekas in your opinion, is that something that every bundle should fix like in the doctrine bundle, or is there something to improve in symfony itself?

**Comment by nicolas-grekas** [comment]
I don't think Symfony can do anything about this...

**Comment by apfelbox** [comment]
Not anymore at least. One BC way would have been to just invert the parameters for this specific case:

`public function setDeprecated(string $message, ?string $package, string $version)`

But that ship has sailed 🌬️ ⛵ 
(and it is debatable whether it would have been great to not use the usual parameter order...)

Thanks for the workaround, nothing to do here then.
