### ISSUE TITLE
[HttpClient] Allow to configure `CURLOPT_SSLCERTTYPE` for CurlHttpClient

### ISSUE THREAD

**Issue by smoench** [symfony/symfony#37297]
**Description**  
Currently the HttpClient only allows `PEM`-files for `local_cert` but curl has more options (`DER`, `ENG`, `P12`). Unfortunately this needs to be configured via another option `CURLOPT_SSLCERTTYPE`.

My proposal is to add the option `local_cert_type` to the CurlHttpClient. This could configured manually or probably guessed by the file extension.

I don't know if it is supported by the AmpHttpClient.

**Comment by nicolas-grekas** [comment]
what about converting your der/eng/p12 certificates to pem instead? openssl has commands to do so.

**Comment by smoench** [comment]
I did that :-) But now I have two pem-files one for cert and one for private key. My use case is sending requests to apple push notification service for wallet updates. We also need to sign the wallets with an p12. With this option we would have only one file instead three.

**Comment by nicolas-grekas** [comment]
Can't you bundle them both in the same file? This should work IIRC.
I'm leaning toward a :-1: on this since it will create portability issued between implementations (making it more complex to move from curl to native or amp)

**Comment by smoench** [comment]
Closing for keeping portability. Feel free to open again when those client implementation will support p12 certificates.
