### ISSUE TITLE
Session is not work as before with logout listeners

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#37292]
**Symfony version(s) affected**: 5.1.0

**Description**  
Moving from sf 5.0 to 5.1 the LogoutHandlers become deprecated and you have to use listeners instead.

I have an issue with my session. I was writing something to my flashbag that later I was viewing this to the customers. Moving to a listener this does not seem to work.

**How to reproduce**  
I have created a reproducer project [here](https://github.com/gmponos/symfony-handlers-reproducer):

**branch:** master, **version**: v5.0

I have a [handler](https://github.com/gmponos/symfony-handlers-reproducer/blob/master/src/Security/MyHandler.php#L27) that writes something to the flashbag that after the logout process it will be [displayed to the user](https://github.com/gmponos/symfony-handlers-reproducer/blob/master/templates/default/homepage.html.twig#L22)

I also [have a test](https://github.com/gmponos/symfony-handlers-reproducer/blob/master/tests/Controller/Admin/BlogControllerTest.php#L200) that validates this behavior.

**branch:** v5.1, **version**: v5.1

On the branch above I migrated the handler [to a listener](https://github.com/gmponos/symfony-handlers-reproducer/blob/v5.1/src/Security/MyLogoutListener.php#L19) the test exists also on that branch but it fails.

**concluding**

Is this the expected behavior or os this a bug? If it is expected why is that?

**Comment by gmponos** [comment]
I also added a branch **v5.1-handlers** which uses handlers instead of listeners and the tests are passing.. So it does not seem related with the update as such.. more related with the migration path.

**Comment by gmponos** [comment]
Friendly ping here... this is blocking me from updating :(

**Comment by wouterj** [comment]
Can you please try with version 5.1.2? I believe I fixed a wrongly configured session migration logout listener in the latest version.

**Comment by gmponos** [comment]
Hi @wouterj on the reproducer project above I have updated composer file to use [~v5.1.2](https://github.com/gmponos/symfony-handlers-reproducer/blob/v5.1/composer.json#L22) on all `sf` components.

This is the result of ` composer show | grep "symfony/" | grep "5.1."`:

```
symfony/asset                          v5.1.2            Symfony Asset Component
symfony/browser-kit                    v5.1.2            Symfony BrowserKit Component
symfony/cache                          v5.1.2            Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                         v5.1.2            Symfony Config Component
symfony/console                        v5.1.2            Symfony Console Component
symfony/css-selector                   v5.1.2            Symfony CssSelector Component
symfony/debug-bundle                   v5.1.2            Symfony DebugBundle
symfony/dependency-injection           v5.1.2            Symfony DependencyInjection Component
symfony/doctrine-bridge                v5.1.2            Symfony Doctrine Bridge
symfony/dom-crawler                    v5.1.2            Symfony DomCrawler Component
symfony/dotenv                         v5.1.2            Registers environment variables from a .env file
symfony/error-handler                  v5.1.2            Symfony ErrorHandler Component
symfony/event-dispatcher               v5.1.2            Symfony EventDispatcher Component
symfony/expression-language            v5.1.2            Symfony ExpressionLanguage Component
symfony/filesystem                     v5.1.2            Symfony Filesystem Component
symfony/finder                         v5.1.2            Symfony Finder Component
symfony/form                           v5.1.2            Symfony Form Component
symfony/framework-bundle               v5.1.2            Symfony FrameworkBundle
symfony/http-foundation                v5.1.2            Symfony HttpFoundation Component
symfony/http-kernel                    v5.1.2            Symfony HttpKernel Component
symfony/inflector                      v5.1.2            Symfony Inflector Component
symfony/intl                           v5.1.2            A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                         v5.1.2            Symfony Mailer Component
symfony/mime                           v5.1.2            A library to manipulate MIME messages
symfony/monolog-bridge                 v5.1.2            Symfony Monolog Bridge
symfony/options-resolver               v5.1.2            Symfony OptionsResolver Component
symfony/phpunit-bridge                 v5.1.2            Symfony PHPUnit Bridge
symfony/process                        v5.1.2            Symfony Process Component
symfony/property-access                v5.1.2            Symfony PropertyAccess Component
symfony/property-info                  v5.1.2            Symfony Property Info Component
symfony/routing                        v5.1.2            Symfony Routing Component
symfony/security-bundle                v5.1.2            Symfony SecurityBundle
symfony/security-core                  v5.1.2            Symfony Security Component - Core Library
symfony/security-csrf                  v5.1.2            Symfony Security Component - CSRF Library
symfony/security-guard                 v5.1.2            Symfony Security Component - Guard
symfony/security-http                  v5.1.2            Symfony Security Component - HTTP Integration
symfony/stopwatch                      v5.1.2            Symfony Stopwatch Component
symfony/string                         v5.1.2            Symfony String component
symfony/translation                    v5.1.2            Symfony Translation Component
symfony/twig-bridge                    v5.1.2            Symfony Twig Bridge
symfony/twig-bundle                    v5.1.2            Symfony TwigBundle
symfony/validator                      v5.1.2            Symfony Validator Component
symfony/var-dumper                     v5.1.2            Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                   v5.1.2            A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle            v5.1.2            Symfony WebProfilerBundle
symfony/yaml                           v5.1.2            Symfony Yaml Component
```

The [test here](https://github.com/gmponos/symfony-handlers-reproducer/blob/master/tests/Controller/Admin/BlogControllerTest.php#L200) is still failing.

Some more steps to reproduce

- clone the project
- run `composer install`
- run `yarn install`
- run `yarn encore dev`
- run `php bin/phpunit tests/Controller/Admin/ --stop-on-failure`

**Comment by wouterj** [comment]
I just added a functional test case to the Symfony repo with your listener and it passes: https://github.com/wouterj/symfony/commit/868252b9ce7768b3c10ded4a9a6cfce38ebe9195 I can't use your reproduction application as I only have PHP set-up on this computer, but it appears not to be a Symfony bug. Is your listener's `getSubscribedEvents()` method called? Is `onLogout()` called?

**Comment by gmponos** [comment]
![image](https://user-images.githubusercontent.com/5675248/85199877-70f71d80-b2fb-11ea-9518-735e697382cb.png)

Yea.. so it seems... 🤔

**Comment by gmponos** [comment]
I [added the same assertion](https://github.com/gmponos/symfony-handlers-reproducer/blob/v5.1/tests/Controller/Admin/BlogControllerTest.php#L195) and it's failing.. FYI as I said initially I used symfony/demo app out of the box..  nothing custom...

**Comment by wouterj** [comment]
Aha, I'm now able to reproduce your bug. I had a closer look at the `logout` configuration in your reproducer app and seems like adding `logout.target` to the configuration results in the failure you describe: https://github.com/wouterj/symfony/commit/22952d9bc468331d18d35b766e9912f86438a296#diff-bcb4516d3c082fb13e1812bed4a0b888R21

---

I don't have much time now to further debug stuff. If you want to do it, here is some context that might be usefull:

https://github.com/symfony/symfony/blob/6ad781c834c0fc842703c43ad62f96109e884e97/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L406-L409

This `target` setting is set in the `DefaultLogoutListener`. Weirdly, the default is `/` and I fail to see how changing it to something else clears the flashbag (even weirder, why doesn't this happen with logout handlers).

https://github.com/symfony/symfony/blob/6ad781c834c0fc842703c43ad62f96109e884e97/src/Symfony/Component/Security/Http/EventListener/DefaultLogoutListener.php#L43

Changing the priority of the custom logout listener doesn't change anything. So I think it's best to debug if the two sessions (the one in the listener and the one in the test) are equal and if so, what is causing the flashbag to be cleared (i.e. does something fetch the flash messages already?)

**Comment by gmponos** [comment]
> are equal and if so,

Yea I was on it..  did this:

```
        $session = self::$container->get('session');
        $client->request('GET', '/en/logout');
        $this->assertSame( self::$container->get('session'), $session);
        $this->assertSame(['My custom message'], self::$container->get('session')->getFlashBag()->all());
```

The test failed on `$this->assertSame(['My custom message'], self::$container->get('session')->getFlashBag()->all());`

**Comment by gmponos** [comment]
OK.. there is the `SessionLogoutListener` which calls the `invalidate` after the `MyLogoutListener`

I tried to reconfigure the order of my events but I could not.. check this:

These are the listeners registered to the `EventDispatcher` after the `MyLogoutListener` has run

![image](https://user-images.githubusercontent.com/5675248/85201005-98061d00-b304-11ea-9e0d-f09522e53d24.png)


And these are the listeners after the `SessionLogoutListener`

![image](https://user-images.githubusercontent.com/5675248/85201027-bec45380-b304-11ea-899c-237938eb4815.png)

**Comment by wouterj** [comment]
Aah, so we created an issue in the "event bubbling" logic. Each firewall has its own event dispatcher: `security.event_dispatcher.FIREWALL_NAME`. At a fixed position, there is a listener that also triggers events on the main `event_dispatcher` dispatcher. That's a major issue, as this means that you can't determine the position at which your event listener is executed if you're registering on the main `event_dispatcher`.

So the temporary fix is to register your custom listener on the firewall dispatcher:
```
services:
    App\Security\MyLogoutListener:
        tags:
            - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.main }
```

In the meantime, this bug should be fixed by Symfony. I think the best way is to attach security-related event listeners/subscribers on the global event dispatcher to the firewall specific dispatchers on container compilation.

**Comment by gmponos** [comment]
Great.. I applied the temp solution and tests seem to pass on my project (haven't applied to the reproducer) 

The Security internals are a little bit complicated for me.. not sure how much I can help with a PR... If I can do something more let me know..

**Comment by wouterj** [comment]
Honestly, I'm not 100% confident in the code related to this bug as well (it's in a magic event dispatcher class): https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php

What I think has to be done:

* After `RegisterListenersPass` is executed, the `event_dispatcher` service definition has many `addListener` calls for all listeners and subscribers
* We should iterate over all of these (in a new security specific compiler pass) and if they are listening on a security event (`LogoutEvent`, `LoginSuccessEvent`, `LoginFailureEvent` or `CheckPassportEvent`), we should add the `addMethodCall` to all firewall dispatchers with the configured priority.

**Comment by wouterj** [comment]
A fix has just been merged in 5.1-dev. If you have some time left, can you please test out removing `dispatcher: security.event_dispatcher.main` and using 5.1-dev? This is was a somewhat large change and I want to make sure I didn't break existing applications. If you don't have time, please say so and I'll build a demo app.

**Comment by gmponos** [comment]
The test on my project that was previously failing it is passing now.. Haven't updated the reproducer app though above.. will try to find some time to do so as an extra confirmation.

**Comment by wouterj** [comment]
Alright, thanks a lot for trying it. I appreciate it a lot! Symfony will be a bit more stable thanks to the time you've invested in this ticket :)

**Comment by DennisdeBest** [comment]
Thanks @gmponos and @wouterj this helped me a lot on changing the response to JSON on a separate api firewall :) :)
