### ISSUE TITLE
Symfony Notifier Bug

### ISSUE THREAD

**Issue by smokezp** [symfony/symfony#37298]
Hi, I updated symfony to 5.1.2 and I got issue with symfony notifier when I do  ./bin/console cache:clear
it Says: 
In PhpDumper.php line 1824:
Cannot dump definition because of invalid class name ('chatter.transport_factory').

**Comment by smokezp** [comment]
ok it looks like I set ^5.1.2 and composer installed dev-master version. for 5.1.2 it is ok

**Comment by chalasr** [comment]
Hi, closing then. Thanks
