### ISSUE TITLE
Cookie sf_redirect and samesite

### ISSUE THREAD

**Issue by demos77** [symfony/symfony#37301]
**Symfony version(s) affected**: 5.1.0

**Description**  
In a simple login page with login guard when i submit the form I have this error message:

> Le cookie « sf_redirect » sera bientôt rejeté car son attribut « sameSite » est défini sur « none » ou une valeur invalide, et sans attribut « secure ». Pour en savoir plus sur l’attribut « sameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

I use Firefox and in the framework.yaml I have **cookie_samesite: lax** and in the security.yaml i have try for the remember_me **samesite: lax** but no difference.

**Comment by chalasr** [comment]
Unable to reproduce. Are you browsing your application using TLS?

**Comment by demos77** [comment]
@chalasr  i use symfony serveur with https

**Comment by chalasr** [comment]
Can you create a minimal app with the minimum amount of code needed to reproduce the issue, and describe all the steps required to run it? (firefox version, OS or any other information related to your environment are welcome)

**Comment by demos77** [comment]
I have create a simple symfony project (5.1.2), create User (with make) and auth (with make).
Git clone the project, create database and just submit the form.

https://gitlab.com/askeen/samesite

I use Symfony serveur with HTTPS and Firefox 77.0.1 (64 bits)

**Comment by limitstudios** [comment]
To confirm I get this same error also

**Comment by demos77** [comment]
So for you it's a Symfony bug ?

**Comment by wouterj** [comment]
Hmm, interesting. If I search for `sf_redirect` in the Symfony code, the only thing I find is here:

https://github.com/symfony/symfony/blob/bf2fb938be7ef03339976b12db76aa1b1e59aa97/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L147-L160

So at least the good news is that this cookie is only set when the profiler is enabled (thus probably not in production).

**Comment by nicolas-grekas** [comment]
@demos77 @limitstudios could you please investigate why/when the `Set-Cookie` header is sent without the samesite attribute? Quickly looking at the code, it looks like it should be sent. From your report, it's not. This needs to be debugged. Thanks!

**Comment by limitstudios** [comment]
I see it when logging in/logging out using a guard authenticator, my config is similar to this

```
            guard:
                authenticators:
                    - App\Security\Authenticator\User\FormAuthenticator
            logout:
                path: user_logout
                target: user_login
```

`sf_redirect` then triggers the console error **Cookie “sf_redirect” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute.** when it does it's 302 redirect

**Comment by wouterj** [comment]
Can you find a file that is probably called `vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php` and then check if you find the code similar to what I posted in my previous comment? If it is, you might want to check the `vendor/symfony/http-foundation/Cookie.php` file and debug (using `dump()` or tools like xDebug) if `$this->sameSite` is set correctly on this line:

https://github.com/symfony/symfony/blob/70ebf7e912a3aa9b6cf3ad5272644a2cd6efb02a/src/Symfony/Component/HttpFoundation/Cookie.php#L110

That should hopefully give us some leads on how debugging this. You can also create a minimal Symfony application that has this bug and push that to github or the like, that way we can replicate your bug on our local machines and debug ourselves.

**Comment by limitstudios** [comment]
Just done a quick xDebug, and from looking at Firefox just changing the case from "lax" to "Lax" the errors disappears

**Comment by wouterj** [comment]
Hmm, might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1633511 then:

> As you can see, Lax and Strict cookies are displaying as "None", if they do not match the case exactly.
> Although I'm brand new to looking at the Firefox codebase, I do think this is simply a display issue in the Network Panel - the cookies still behave correctly.

So maybe it's just a firefox dev toolbar issue and not a Symfony/PHP one?

**Comment by nicolas-grekas** [comment]
> So maybe it's just a firefox dev toolbar issue and not a Symfony/PHP one?

Closing as this is the most likely reason why. Please provide additional details if you think this is still a Symfony issue.
