### ISSUE TITLE
Allow decoration of Form class

### ISSUE THREAD

**Issue by passioneight** [symfony/symfony#37309]
## Description  
In order to create a custom `Form` based on the `Symfony\Component\Form\Form` class, one has to override quite some files, which seems cumbersome and comes with some significant drawbacks (see below).

## Required Implementation
The following steps are necessary:
1. Override the `form.resolved_type_factory` alias:
```yaml
form.resolved_type_factory:
    class: <Custom ResolvedFormTypeFactory Class>
```
2. Override the `createResolvedType` method of the custom `ResolvedFormTypeFactory`, so that a custom `ResolvedFormType` is used:
```php
public function createResolvedType(FormTypeInterface $type, array $typeExtensions, ResolvedFormTypeInterface $parent = null)
{
    $resolvedFormType = parent::createResolvedType($type, $typeExtensions, $parent);
    return new ResolvedFormType($resolvedFormType->getInnerType(), $resolvedFormType->getTypeExtensions(), $resolvedFormType->getParent());
 }
```
3. Override the `newBuilder` method of the custom `ResolvedFormType`, so that a custom `FormBuilder` is used:
```php
protected function newBuilder($name, $dataClass, FormFactoryInterface $factory, array $options)
{
    $builder = parent::newBuilder($name, $dataClass, $factory, $options);

    if($builder instanceof SymfonyFormBuilder) {
        $builder = new FormBuilder($builder->getName(), $builder->getDataClass(), $builder->getEventDispatcher(), $builder->getFormFactory(), $builder->getOptions());
    }

    return $builder;
}
```
4. Override the `getForm` method of the custom `FormBuilder`, so that the custom `Form` is used:
```php
public function getForm()
{
    $symfonyForm = parent::getForm();

    $form = new Form($symfonyForm->getConfig());

    $children = $this->all();
    foreach ($children as $child) {
        $form->add($child->setAutoInitialize(false)->getForm());
    }

    if ($this->getAutoInitialize()) {
        $form->initialize();
    }

    return $form;
}
```

Especially the last step is problematic, as a possible future update of the original `getForm` method will most likely not be supported - due to the lines _after_ creating the custom `Form`. Additionally, `$children->all()` has to be called in order populate the custom `Form` with the corresponding children. By doing so, the children will again be resolved (which already happens in `parent::getForm`).

## Actual Request
Provide an easier way to extend the `Symfony\Component\Form\Form`.

## Possible Solution
Maybe we could add some configuration that allows to set the `Form` class that is used when creating the form within `getForm`.

Alternatively, add a getter in the `FormBuilder` class, which only returns the FQCN could be used to instantiate the class, like so:
```php
protected function getFormClass(): string
{
    return Form::class;
}
```
This could be called in the `getForm` method instead of `new Form(...);`:
```php
$formClass = $this->getFormClass();
$form = new $formClass($this->getFormConfig());
```

This way, the `getForm` method does not need to be overriden at all.

> If there is another way to achieve this, please let us know, as we didn't find anything about this - a link to the docs will suffice.

**Comment by xabbuh** [comment]
Can you explain a use case where you need to create a custom implementation of the `FormInterface`?

**Comment by passioneight** [comment]
We are triggering a custom event, namely `FormEvent`, which let's the developer handle the form submission in an `EventListener`.

```php
use Symfony\Component\Form\FormEvent as SymfonyFormEvent;
use Symfony\Component\HttpFoundation\Response;

class FormEvent extends SymfonyFormEvent
{
    /** @var Response $response */
    private $response;

    /**
     * @param Response $response
     */
    public function setResponse(Response $response)
    {
        $this->response = $response;
    }

    /**
     * @return Response
     */
    public function getResponse()
    {
        return $this->response;
    }
}
```

The `FormEvent` can have a `Response` set in the corresponding `EventListener`, using `$event->setResponse(...);`. Now, we'd like to use the `FormEvent` to return the `Response` in our controller, using `$event->getResponse();`.

However, we are providing a custom service to decrease implementation efforts.
```php
// Only the related method is shown for brevity

public function buildForm(string $formClass, $object = null, array $options = [])
{
    $object = is_string($object) ? new $object() : $object;

    $form = $this->createForm($formClass, $object, $options);
    $form->handleRequest($this->getRequest());

    $formEvent = new FormEvent($form, $object ?: $form->getData());
    $form->setEvent($formEvent);

    $this->onCreated($formClass, $form, $object);
    if ($form->isSubmitted()) {
        if ($form->isValid()) {
            $this->onSuccess($formClass, $form, $object);
        } else {
            $this->onError($formClass, $form, $object);
        }
    }

    return $form;
}
```

Now, we'd like the developer to be able to call `$form->getEvent()->getResponse()` if the need arises. This requires our custom `Form` implementation.

```php
use Symfony\Component\Form\Form as SymfonyForm;

class Form extends SymfonyForm
{
    /** @var FormEvent $event */
    private $event;

    /**
     * @return FormEvent
     */
    public function getEvent(): FormEvent
    {
        return $this->event;
    }

    /**
     * @param FormEvent $event
     */
    public function setEvent(FormEvent $event)
    {
        $this->event = $event;
    }
}
```

Of course, one can argue that our service could have a property, so the event can be accessed using a getter. However, when it comes to multiple forms on one page, the code needs to be cluttered by some kind of mapping (in order to know which event corresponds to which form). Resulting in a method-call similar to `$service->getFormEvent(MyFormType::class);`. Compared to this `$form->getEvent()->getResponse();` seems much cleaner - which, of course, is a subjective point of view.

Looking forward to your thoughts on this.

**Comment by passioneight** [comment]
Just a quick ping @xabbuh as we're wondering whether you already had some time to review this ticket :-)

**Comment by xabbuh** [comment]
I must admit that I do not fully grasp the solution that you have right now. But couldn't you solve this with some custom options and event listeners which are added by a form type extension?

**Comment by passioneight** [comment]
The goal is to provide a simple interface to the developer in order to get the `Response`, set in an `EventListener`/`EventSubscriber`, within the controller, like so:

```php
$form->getFormEvent()->getResponse();
```

Unfortunately, this cannot be achieved with a custom `FormType` - unless we misunderstood and you had something different in mind, in which case: would you mind ellaborating on your suggestion?

#### Current Approach
[Here's the current solution in place](https://github.com/passioneight/form-builder) - a bundle built for `Pimcore`, which builds on top of `Symfony`. Have a look at the [example controller](https://github.com/passioneight/form-builder/blob/master/documentation/30_usage.md#example) at the very end of the example.

As you can see, the `buildForm` method of our [`FormBuilderService`](https://github.com/passioneight/form-builder/blob/master/src/Service/FormBuilderService.php) is called, which will trigger the aforementioned `FormEvent`. The developer can now [handle the form submission](https://github.com/passioneight/form-builder/blob/master/documentation/30_usage.md#handling-the-form-submission) and, thus, set a `Response` on the `FormEvent`:

```php
$event->setResponse(new RedirectResponse($url));
```

Now, to provide the intended interface to the developer, the `Form` class actually needs to be decorated. However, this is currently not possible (as described in the initial comment). This results in a [custom `FormBuilder` class](https://github.com/passioneight/form-builder/blob/master/src/Symfony/Component/Form/FormBuilder.php#L37).

So, ultimately, the goal is too keep things as simple as possible for the developers.

From our point of view, this will leave us with 3 options:
1. Being stuck with the current implementation of the custom `FormBuilder` (which adds some overhead),
2. Adding a configuration to decorate the `Form` class (preferred, but will need further inspection of _how_ and _if_ possible, without introducing BCs),
3. Creating a PR, which adds the [`getFormClass`](https://github.com/passioneight/form-builder/blob/master/src/Symfony/Component/Form/FormBuilder.php#L59) to the `FormBuilder` and updates the instantiation of the `Form` class [like so](https://github.com/passioneight/form-builder/blob/master/src/Symfony/Component/Form/FormBuilder.php#L41).

Looking forward to your thoughts on this.

**Comment by passioneight** [comment]
Hi there,

we've decided to take a different approach, which renders this issue obsolete.
