### ISSUE TITLE
Controller action unavailable / not working as POST but 'works' as GET

### ISSUE THREAD

**Issue by carlos-mg89** [symfony/symfony#37310]
**Symfony version(s) affected**: 5.0.x/5.1.x

**Description**  

I've just found an issue that is becoming a 'nightmare' and hard to understand for me. One controller action isn't working as a POST AJAX call but works well if I paste it in the browser (GET).

**How to reproduce**  

If I copy this method in my AdsController (I've tried renaming the controller with the same luck), the request/response isn't even produced (attached picture shows the Symfony toolbar status)
![Captura de pantalla de 2020-06-16 18-01-35](https://user-images.githubusercontent.com/19690868/84798729-946c5080-affb-11ea-9c3e-6db83262f0e8.png)

Method content:
```
/**
     * @Route("/generic/upload_ad_picture/{id}", name="ad_generic_upload_picture")
     *
     * @param Request $request
     * @param GenericAd $genericAd
     * @return Response
     */
    public function genericAdUploadPictureAction(Request $request, GenericAd $genericAd): Response {
        $message = "KO";
        $newPhotoUrl = null;
        $newDeletePhotoUrl = null;

        try {
            /** @var UploadedFile $newAdPhotoFilename */
            $newAdPhotoFilename = $request->files->get('file');

            if ($newAdPhotoFilename) {
                $newPhotoName = $this->storePhoto($newAdPhotoFilename, self::ADS_DIRECTORY);
                if ($newPhotoName != null) {
                    $adPhotos = $genericAd->getPhotos();
                    $adPhotos[] = $newPhotoName;
                    $genericAd->setPhotos($adPhotos);
                    $this->getEm()->persist($genericAd);
                    $this->getEm()->flush();

                    $newPhotoUrl = $request->getUriForPath("/uploads/ads/" . $newPhotoName);
                    $newDeletePhotoUrl = $this->generateUrl('ad_generic_remove_photo', [
                        'id' => $genericAd->getId(),
                        'photo' => $newPhotoName
                    ]);
                    $message = "OK";
                }
            }
        } catch (Exception $exception) {
            $message = "KO";// . $exception->getFile()."@".$exception->getLine()." " . $exception->getMessage();
        }

        return new JsonResponse([
            "message" => $message,
            "newPhotoUrl" => $newPhotoUrl,
            "newDeletePhotoUrl" => $newDeletePhotoUrl
        ]);
    }
```

Copying this method action into my SellerController, works perfectly fine. The differences between those controllers are these ones (they have different actions too, of course, however there are no duplication actions in AdsController that could confuse things):

```
/**
 * @IsGranted("ROLE_USER")
 * @Route("/app/ads")
 */
class AdsController extends BaseController
```

```
/**
 * @IsGranted("ROLE_USER")
 * @Route("/app")
 */
class SellerController extends BaseController
```

As you can see, the route prefix is different (/app and /app/ads). Actually, if I prepend to the route annotation in the SellerController the /ads prefix, the error happens again in the SellerController:

`@Route("/ads/generic/upload_ad_picture/{id}", name="ad_generic_upload_picture")`

What's wrong with my code??? It's the exact same function. Just copy pasted it from one controller to the other one. I thought the controller name (changed from AdController to AdsController) could somehow affect the issue, or the prefix (I changed it from /app/ad to /app/ads (the current one) with the same luck.

The Firefox console is even more cryptic / useless. The call isn't being done at all, like if the generated URL, (which I see in the source code and again, if I copy paste it works as a GET request in the browser) isn't right. Attached you see the `console.error` of my JavaScript code: 
![Captura de pantalla de 2020-06-16 18-10-55](https://user-images.githubusercontent.com/19690868/84799800-19a43500-affd-11ea-8eda-676389b0e044.png)

Any possible help? I'd like this method to be in the AdsController, since it's related with that and not with the other controller. As I said, changing the controller class name nor file name, didn't help at all. This controller is extremely simple, and an action code shouldn't affect another one, right?

Thanks in advance and please, ask for anything else. I didn't want to paste all my code, since I really don't think is relevant at all. The controller only has 2 more controller actions. And one of them is a simple render of a template.

**Comment by carlos-mg89** [comment]
I've managed to completely isolate the situation.

This controller works perfectly fine:

Same controller as below one, just changing the route annotation to this one:

```
/**
 * @IsGranted("ROLE_USER")
 * @Route("/app/generic_ads")
 */
```

This controller doesn't work (POST method only, the GET works). 

```
<?php

namespace App\Controller\App;

use App\Controller\BaseController;
use App\Entity\GenericAd;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/app/ads/generic")
 */
class GenericAdsController extends BaseController
{
    /**
     * @Route("/upload_ad_picture/{id}", name="ad_generic_upload_picture")
     *
     * @param Request $request
     * @param GenericAd $genericAd
     * @return Response
     */
    public function genericAdUploadPictureAction(Request $request, GenericAd $genericAd): Response {
        $message = "KO";

        try {
            /** @var UploadedFile $newAdPhotoFilename */
            $newAdPhotoFilename = $request->files->get('file');

            if ($newAdPhotoFilename) {
                $newPhotoName = $this->storePhoto($newAdPhotoFilename, AdsController::ADS_DIRECTORY);
                if ($newPhotoName != null) {
                    $adPhotos = $genericAd->getPhotos();
                    $adPhotos[] = $newPhotoName;
                    $genericAd->setPhotos($adPhotos);
                    $this->getEm()->persist($genericAd);
                    $this->getEm()->flush();

                    $message = "OK";
                }
            }
        } catch (Exception $exception) {
            $message = "KO";// . $exception->getFile()."@".$exception->getLine()." " . $exception->getMessage();
        }

        return new JsonResponse([
            "message" => $message
        ]);
    }
}
```

The difference between the 2 controllers as I see is the directory levels in one and another. Same code at the rest. Is there a limitation to only 2 directory levels in a route annotation?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
