### ISSUE TITLE
WebTestCase Request Method incorrect

### ISSUE THREAD

**Issue by ProfM2** [symfony/symfony#37311]
**Symfony version(s) affected**: 4.4.10

**Description**  
WebTestCase::createClient->request doesn't always follow the 'method' provided

**How to reproduce**  

Given the Route/Method, and the test function:
```
@Route("/api/delete/{id}", name="delete", methods={"DELETE"})

public function testRouteDelete()
    {
        $client = static::createClient();
        $client->followRedirects(true);
        $client->request('DELETE', '/api/delete/1');
        $this->assertResponseIsSuccessful();
    }
```
**Fails**: ...MethodNotAllowedHttpException: No route found for "GET /api/delete/1": Method Not Allowed (Allow: DELETE)
I expected the request method of DELETE to match the route method of DELETE ... however, the route not found error says "GET" - the request method is wrong

Given the Route/Method, and the test function:
```
Route:  @Route("/api/show/{id}", name="show", methods={"GET"})

public function testRouteShow()
    {
        $client = static::createClient();
        $client->followRedirects(true);
        $client->request('GET', '/api/show/1');
        $this->assertResponseIsSuccessful();
    }
```
**Succeeds**
This is expected

Given the Route/Method, and the test function:
```
@Route("/api/edit/{id}", name="edit", methods={"POST"})

public function testRouteEdit()
    {
        $client = static::createClient();
        $client->followRedirects(true);
        $client->request('POST', '/api/edit/1');
        $this->assertResponseIsSuccessful();
    }
```
**Fails**: ...\MethodNotAllowedHttpException: No route found for "GET /api/edit/1": Method Not Allowed (Allow: POST)
I expected the request method of POST to match the route method of POST ... however, the route not found error says "GET" - the request method is wrong

The one that points to a bug is this example:
```
@Route("/api/edit/{id}", name="edit", methods={"GET"})

public function testRouteEdit()
    {
        $client = static::createClient();
        $client->followRedirects(true);
        $client->request('POST', '/api/edit/1');
        $this->assertResponseIsSuccessful();
    }
```
**Fails**: ...\MethodNotAllowedHttpException: No route found for "POST /api/edit/1": Method Not Allowed (Allow: GET)
I was expecting the request method and route method to fail like the other POST/DELETE ... however what caught my eye is the error of **No route found for "POST /api/edit/1"** ... in this example, the request method was correct.

**Comment by xabbuh** [comment]
What happens if you remove the `$client->followRedirects(true);` calls?

**Comment by ProfM2** [comment]
Without the `$client->followRedirects(true);`, phpunit fails assertions of 301 redirects.

Removed those, and it uncovered numerous other issues that I was not doing correctly, namely, properly authenticating.

Ended up finding this document that helped:
[https://symfony.com/doc/4.4/testing/http_authentication.html](url)

**Comment by tianadev75** [comment]
> Without the `$client->followRedirects(true);`, phpunit fails assertions of 301 redirects.
> 
> Removed those, and it uncovered numerous other issues that I was not doing correctly, namely, properly authenticating.
> 
> Ended up finding this document that helped: [https://symfony.com/doc/4.4/testing/http_authentication.html](url)

really thank you ProfM2

**Comment by Schrank** [comment]
Because I stumbled over it and if anyone is wondering: Although it was specified to NOT change the method on redirect with 301 and 302 in the original, browsers didn't do it, so it was changed later. So having a redirect the next request is get. If you don't want this you can do a 307 (today I Learned).

Reference: https://www.rfc-editor.org/rfc/rfc7231, Page 54
