### ISSUE TITLE
[Mailer]: Add `from` and `headers` to `mailer.yaml` configuration file

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#37328]
**Description**  
Allow setting some default options at the message level in `config/packages/mailer.yaml`. Suggestions:
* `from`: The way suggested at https://symfony.com/doc/master/mailer.html#email-addresses (event subscriber) seems (a) cumbersome and (b) inflexible (what if I want the ability to override the default `from` in *some* cases?)
* `headers`: The `X-Auto-Response-Suppress` header explained at https://symfony.com/doc/master/mailer.html#message-headers would be a good candidate

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/pull/36736 solves it right?

**Comment by fabpot** [comment]
Yes, it does.
