### ISSUE TITLE
[Messenger] How to get messages in the failed transport

### ISSUE THREAD

**Issue by devbysb** [symfony/symfony#37323]
Hi, 
Is it possible to get messages in the failed transport (I use doctrine) ?
I have try to inject ReceiverInterface in my controller but it's not working. I need to do something like the command but in my controller

thank you

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
