### ISSUE TITLE
Polyfill new phpunit 9.1 assertions

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#37320]
We should polyfill the new assertions added to phpunit 9.1 in our bridge, so that they can be used on lower versions of php:
https://github.com/sebastianbergmann/phpunit/blob/9.1.5/ChangeLog-9.1.md#910---2020-04-03

See links in https://github.com/symfony/symfony/pull/32922 for inspiration.

See also https://github.com/sebastianbergmann/phpunit/pull/4210/files

Help wanted!

**Comment by phpfour** [comment]
@nicolas-grekas I'm up for it ✋

**Comment by nicolas-grekas** [comment]
Nice thanks, can't wait! (but no hurry either :) )

**Comment by phpfour** [comment]
> Nice thanks, can't wait! (but no hurry either :) )

I'll get started on this and hopefully will have an update by the weekend 🤞🏼

**Comment by derrabus** [comment]
@phpfour I started working on this topic a couple of weeks ago. If this commit is helpful for you, feel free to copy over as much as you like. 😃  https://github.com/derrabus/symfony/commit/a05d504971bbbd6a4e2ef27fbec47d53b61a4cdd

**Comment by phpfour** [comment]
hi @derrabus, thanks for your reference...that's quite a large commit you have...I am thinking whether it would be beneficial if I contribute to your repository to get it completed rather than doing on my own? WDYT?

**Comment by wouterj** [comment]
You can fetch Derrabus' fork and then cherry-pick the commit into your branch and work from that:

``` 
git remote add derrabus https://github.com/derrabus/symfony.git
git fetch derrabus
git cherry-pick a05d50
```

**Comment by derrabus** [comment]
The commit is rather large because I've partly migrated the Symfony test suite to the polyfilled methods already. I don't think that this is necessary just yet. The interesting part is in `PolyfillAssertTrait.php`.

**Comment by nicolas-grekas** [comment]
I confirm migrating the test suite is not desired unless some methods are deprecated. This will save merge conflicts.

**Comment by phpfour** [comment]
Thanks guys for the direction, hoping to back soon with some update.

**Comment by derrabus** [comment]
@phpfour Is there anything I can do to support you?

**Comment by phpfour** [comment]
I've just pushed the commit and created the PR, sorry this has been sitting idle for a few days 😔

@nicolas-grekas @derrabus would request your review 🙏
