### ISSUE TITLE
[Security] Added type-hints to user providers breaks third party security packages

### ISSUE THREAD

**Issue by walva** [symfony/symfony#37333]
**Symfony version(s) affected**: from 5.0.0 to 5.1.2

**Description**  
The commit [[Security] Added type-hints to user providers](https://github.com/symfony/security-core/commit/38f92636925745488e561fe31e6560b274e18274) breaks some third party security packages such as [IDC-Consulting/IDCIKeycloakSecurityBundle](https://github.com/IDCI-Consulting/IDCIKeycloakSecurityBundle)

IDCIKeycloakSecurityBundle use the getCredentials method to create a AccessToken. The access token is passed to the loadUserByUsername (which should be loadUserByCredentials?). It works fine until 5.0 because loadUserByUsername($username) became loadUserByUsername(**string** $username). Maybe this issue was addressed by [the next generation of guards](http://wouterj.nl/2020/04/authenticators-new-symfony-security#the-next-generation-of-guards)? ping @wouterj 

**How to reproduce**  
I'll will work on this asap

**Possible Solution**  
Reverse the commit [[Security] Added type-hints to user providers](https://github.com/symfony/security-core/commit/38f92636925745488e561fe31e6560b274e18274) ?

**Additional context**  
In my specific use case, I don't store the users in the database. A username is not enough for me to load the user.

![diagram symfony security layer](https://user-images.githubusercontent.com/3897363/84997439-e40f6100-b14e-11ea-8c82-0999842232a7.png)

**Comment by xabbuh** [comment]
How does that change break your package? What do you pass to the method if not a string?

**Comment by walva** [comment]
Hi @xabbuh, thanks for answering me. It is not my package but I'm doing a similar job at the moment with symfony 5.0.9. The original package receive an access token in the loadUserByUsername method in the current version.
I think there is some misunderstanding of the current behavior on my side (and the author of the package). I was expecting loadUserByUsername to fulfill the responsibility of the Symfony\Component\Security\Guard\AuthenticatorInterface::getUser().

At the moment, I'm searching a way to ignore loadUserByUsername or to by pass its usage.

**Comment by walva** [comment]
If I bypass the [UserProvider](https://github.com/symfony/security-core/blob/master/User/UserProviderInterface.php#L46) in the method [getUser](https://github.com/symfony/security-guard/blob/master/AuthenticatorInterface.php#L81), the first step works. But then I get redirected to the next page (member area for example) and then the loadUserByUsername is called anyway and I cannot get a user based on the $username string.
I'm tempted to use the session to give the current user but it feels dangerous.

**Comment by wouterj** [comment]
The contract described in the PHPdocs has always been `@param string $username`. So if you used something else than a string, it worked because of PHP's loose typing, but it wasn't part of the contract or support in Symfony.

So I think this a bug in https://github.com/IDCI-Consulting/IDCIKeycloakSecurityBundle, not Symfony.

**Comment by walva** [comment]
@wouterj okey it make sense. I agree with you, it is not a bug. I am mimicking the bundle to make keycloak work in my symfony 5.0 app. If I find a solution, I will definitly show my result to this bundle.
I definitely considering migrating to 5.1 and use the new gen of guards. I'll have a chat with my team for that. At least I would give a try. At this point, I'm stuck with loadUserByUsername being called after been successfully authenticated.

**Comment by xabbuh** [comment]
Let's close here then.
