### ISSUE TITLE
Composer update is removing symfony/mailer package

### ISSUE THREAD

**Issue by etshy** [symfony/symfony#37330]
First, I'm not sure if this kind of issue belong here.

I spent some time tody to update from symfony 5.0 to 5.1 and changed my Mailer function to use symfony/mailer instead of Swift_Mailer.
I can use `composer require symfony/mailer` just fine, but when I run `composer update` after it says this
```
Restricting packages listed in "symfony/symfony" to "^5.1"
Package operations: 0 installs, 0 updates, 3 removals
  - Removing symfony/mailer (v5.1.2)
  - Removing egulias/email-validator (2.1.18)
```

I'm not really sure how restrictions is working but I updated my composer.json to use `^5.1` on the`extra.symfony.require` option.

Here is my composer.json
```
{
  ...
  "require": {
    "php": "^7.4",
    "ext-iconv": "*",
    "ext-json": "*",
    "claviska/simpleimage": "dev-master",
    "doctrine/doctrine-bundle": "^2.0",
    "doctrine/mongodb-odm-bundle": "^4.0",
    "doctrine/orm": "^2.6",
    "etshy/php-zip-bundle": "^0.1",
    "friendsofsymfony/jsrouting-bundle": "^2.3",
    "hhxsv5/php-sse": "~1.0",
    "j0k3r/php-imgur-api-client": "^3.0",
    "knplabs/knp-time-bundle": "^1.11",
    "sensio/framework-extra-bundle": "^5.2@dev",
    "sensiolabs/security-checker": "^6",
    "antishov/doctrine-extensions-bundle": "^1.4@dev",
    "symfony/apache-pack": "dev-master",
    "symfony/asset": "^5.1",
    "symfony/console": "^5.1",
    "symfony/dotenv": "^5.1",
    "symfony/expression-language": "^5.1",
    "symfony/flex": "^1.0",
    "symfony/messenger": "^5.1",
    "symfony/monolog-bundle": "^3.3",
    "symfony/psr-http-message-bridge": "^1.0@dev",
    "symfony/security-bundle": "^5.1",
    "symfony/serializer-pack": "^1.0",
    "symfony/translation": "^5.1",
    "symfony/twig-bundle": "^5.1",
    "symfony/validator": "^5.1",
    "symfony/webpack-encore-bundle": "^1.0",
    "symfony/yaml": "^5.1",
    "vich/uploader-bundle": "^1.9",
    "babdev/pagerfanta-bundle": "^2",
    "laminas/laminas-diactoros": "^2.3"
  },
  "require-dev": {
    "symfony/profiler-pack": "dev-master",
    "symfony/web-server-bundle": "^4.4"
  },
  "minimum-stability": "stable",
  "config": {
    "preferred-install": {
      "*": "dist"
    },
    "sort-packages": true,
    "platform": {
      "ext-mongo": "1.6.16"
    }
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/"
    }
  },
  "replace": {
    "symfony/polyfill-iconv": "*",
    "symfony/polyfill-php71": "*",
    "symfony/polyfill-php70": "*",
    "symfony/polyfill-php56": "*"
  },
  "scripts": {
    "auto-scripts": {
      "cache:clear": "symfony-cmd",
      "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd",
      "security-checker security:check": "script",
      "assets:install %PUBLIC_DIR%": "symfony-cmd"
    },
    "post-install-cmd": [
      "@auto-scripts"
    ],
    "post-update-cmd": [
      "@auto-scripts"
    ]
  },
  "conflict": {
    "symfony/symfony": "*"
  },
  "extra": {
    "symfony": {
      "require": "^5.1",
      "allow-contrib": false
    }
  }
}

```

I guess I forgot to update something but I don't know what I'm missing here.

**Comment by Tobion** [comment]
Your composer.json does not list symfony/mailer. So you didn't run `composer require symfony/mailer`.

**Comment by etshy** [comment]
I didn't notice that it was missing.
I clearly did run it though, when i run it again I have this message
```
>composer require symfony/mailer
Restricting packages listed in "symfony/symfony" to "^5.1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^5.1"
Nothing to install or update
Writing lock file
```
meaning it's already installed

And i have the symfony/mailer folder in my vendor.

I'll try adding it manually to my composer.json later and see if it's still removed by running `composer update`.

**Comment by nicolas-grekas** [comment]
Can you run `composer why symfony/mailer`?

**Comment by etshy** [comment]
Yep
Here is the result
```
>composer why symfony/mailer
symfony/google-mailer  v5.1.2  requires  symfony/mailer (^4.4|^5.0)
```

If I add `"symfony/mailer": "^5.1"` in the composer.json It gave the following
```
>composer why symfony/mailer
__root__               dev-3rd-party-host  requires  symfony/mailer (^5.1)
symfony/google-mailer  v5.1.2              requires  symfony/mailer (^4.4|^5.0)
```
(I also added `symfony/google-mailer` for dev purposes)

btw, if I add `"symfony/mailer": "^5.1"` in the composer.json it seems the `update` doesn't remove it.
It might be a problem with my composer or something ?

**Comment by Tobion** [comment]
>composer require symfony/mailer
Restricting packages listed in "symfony/symfony" to "^5.1"
./composer.json has been updated

It says composer.json has been updated. If it didn't there is a problem. Maybe update your composer. You can even try to latest composer v2 alpha release.

**Comment by nicolas-grekas** [comment]
What about `composer why symfony/google-mailer`, etc, until you list one of your root deps?

**Comment by gmponos** [comment]
not sure if this is related https://github.com/composer/composer/issues/8467

since `symfony/google-mailer` is not required at the root.. so running update could be the reason that the package `mailer` is removed. Could it be that you removed the `google-mailer` with the `remove` command?

**Comment by etshy** [comment]
Well It seems the problem was with a soft that sync the folder where my projects are with a server I use to test, and for some reason it started downloading from server instead of uploading only ...
So the `composer.json` was reverted after being changed by composer...

As it never happened to me before I assumed it was related to the symfony update but no.

I'm sorry for wasting your time like that, I'll close the issue.
