### ISSUE TITLE
[Messenger] Filesystem transport

### ISSUE THREAD

**Issue by YaFou** [symfony/symfony#37347]
**Description**  
For small projects or micro-services, there is no transport for the Messenger component to store messages in a directory like [the Filesystem Cache Adapter](https://symfony.com/doc/current/components/cache/adapters/filesystem_adapter.html). The configuration will be really simple with only the path of the messages directory. For instance, it can be used for tests.

**Example**  
`.env` file example:
```.env
MESSENGER_TRANSPORT_DSN=filesystem://%kernel.cache_dir%/messages
```

**Comment by nicolas-grekas** [comment]
Using an sqlite database might be the best way to achieve this IMHO.
Creating a transport is not trivial. I'm not sure it's worth implementing and maintaining a dedicated one here.

**Comment by xfifix** [comment]
@nicolas-grekas i have the same need but to listen to a file stream XML.I'm just thinking of using the get method which listens to a directory. What do you think ?

**Comment by nicolas-grekas** [comment]
Closing as explained.
