### ISSUE TITLE
[EventDispatcher] Missing dependency on symfony/event-dispatcher-contracts:^1.1

### ISSUE THREAD

**Issue by vincentchalamon** [symfony/symfony#37349]
**Symfony version(s) affected**: 4.4.*

**Description**

The symfony/event-dispatcher component and the symfony/event-dispatcher-contracts both depend on `Psr\EventDispatcher\StoppableEventInterface` interface. But the dependency psr/event-dispatcher is only required symfony/event-dispatcher-contracts:^2, not on ^1.1 which is required by symfony/event-dispatcher:^4.4.

This causes the following error on phpstan execution:
> Reflection error: Psr\EventDispatcher\StoppableEventInterface not found.

**How to reproduce**

Bug can be seen and reproduced on gheb/docusign-bundle CI: https://github.com/GregoireHebert/docusign-bundle/runs/787512792

```
composer config extra.symfony.require "4.4.*"
composer update
vendor/bin/phpstan analyze
```

**Possible Solution**

Move psr/event-dispatcher dependency from suggest to require on symfony/event-dispatcher-contracts:^1.1

**Comment by xabbuh** [comment]
I fail to see why that is necessary. The EventDispatcher component works quite well even without the package not being installed.

**Comment by vincentchalamon** [comment]
It breaks on the PHPStan analysis because of the missing interface `Psr\EventDispatcher\StoppableEventInterface` used in symfony/event-dispatcher-contracts and symfony/event-dispatcher.

The error can be seen and reproduced here: https://github.com/GregoireHebert/docusign-bundle/runs/787512792

**Comment by xabbuh** [comment]
Honestly, I do not understand that report. Why does it the event classes from that bundle which don't use the interface?

But anyway, using `instanceof` with a class that does not exist is perfectly valid. If PhpStan stumbles over it, there may be something to be fixed there.

**Comment by vincentchalamon** [comment]
The psr/event-dispatcher dependency seems to not be required in symfony/event-dispatcher-contracts:^1.1 for backward compatibility reasons, but is required from ^2.0, so that's logical!

In this case, this issue must be solved by updating the phpstan configuration in the bundle.

Thanks for your feedback.
