### ISSUE TITLE
Composite probably should not be @internal

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#37348]
**Symfony version(s) affected**: 5.1

@xabbuh , I think that `Composite` should not be `@internal`. Even with the new `@Compound` constraint `Composite` is still useful for complex custom validators. 

For example, I have `@ExcelColumn(string $column, array $constraints)` that checks that all cells in a column of an uploaded Excel file are valid. This cannot be expressed with `@Compound`.

**Comment by nicolas-grekas** [comment]
Please open a PR instead to get more attention.
