### ISSUE TITLE
[PhpUnitBridge] replace Blacklist by Excludelist to fix deprecations on phpunit 9.4

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#37344]
**Symfony version(s) affected**: 3.4

The phpunit-bridge us using "blacklist" classes that are [deprecated since phpunit 9.4](https://github.com/sebastianbergmann/phpunit/commit/8e9c76d33dab4095c9066072076f368193e4166d).

We need to account for this change and make the code in the bridge able to use either the old or the new classes depending on which version of phpunit is in use.

Help wanted.

**Comment by gennadigennadigennadi** [comment]
I had a look today and noticed there are some internal changes made in PHPUnit9.3 (PHPUnit\TextUI\Configuration\Configuration, PHPUnit\TextUI\Configuration\Registry) that make CommandForV9 fail, which I'll have a look at (and try to fix) first.

**Comment by gennadigennadigennadi** [comment]
https://github.com/symfony/phpunit-bridge/pull/13 # should fix the problems.

**Comment by gennadigennadigennadi** [comment]
#37418 that's the fix for the problem from above.
