### ISSUE TITLE
[Mailer] Backport basic configuration options from 5.1 to 4.4 LTS

### ISSUE THREAD

**Issue by srsbiz** [symfony/symfony#37356]
We have just migrated symfony stack from 4.3 to 4.4 and noticed broken builds related to mailer component:

- hardcoded timeout value to 5 seconds and not respecting ini settings
- enforced TLS without option to disable peer verification 

Both issues seems to be addressed in 5.1, but I can't imagine LTS version without them.

**Comment by fabpot** [comment]
We never backport features in older versions. Once released, versions are in maintenance more with bug fixes and security fixes only. So, closing here.

**Comment by srsbiz** [comment]
Well, I see these as bug fixes, not features. At least timeout issue - it was not specified in changelog, either in [symfony/symfony](https://github.com/symfony/symfony/blob/master/CHANGELOG-4.4.md) nor in [mailer](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/CHANGELOG.md)

Moreover, [changelog for mailer in current master](https://github.com/symfony/symfony/blob/4b854da73efb9f5dd1424c31f511077fd70a37c1/src/Symfony/Component/Mailer/CHANGELOG.md) mentions **verify_peer** option under 4.4 version, which is not true.
