### ISSUE TITLE
[Mailer] Add constants for header names

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#37363]
**Description**  
Use constants for header names. Especially useful for headers with "complicated" spelling, e.g. `Message-ID`. Could be used at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Message.php#L96 and https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/SentMessage.php#L41

**Example**  
Define them e.g. at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Header/Headers.php#L24 :
```php
public const HEADER_MESSAGE_ID = 'Message-ID';
```
Then use it:
```php
$headers->addIdHeader(Headers::HEADER_MESSAGE_ID, '123@example.com');
```

More or less the same reasons as having constants for HTTP status codes... https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L24

**Comment by fabpot** [comment]
Not sure we need this. For most common headers, we have specialized methods already. The example you give is an edge case as most of the time, you would not set the message id.

**Comment by ThomasLandauer** [comment]
Well, I don't know if it's common - but I do set the Message-ID in a real project ;-) And in Swift Mailer you even had a method for this: `setId()`: https://swiftmailer.symfony.com/docs/messages.html#the-structure-of-a-message So having people type out the string "Message-ID" themselves looks like a step back to me...

Besides, other "exotic" headers might also profit from this: `In-Reply-To`, `References`, `Return-Path`.

**Comment by fabpot** [comment]
For day-to-day headers, we have methods on Email, like `returnPath()`.
I did not add `setId()` like Swiftmailer on purpose. I wanted to expose only the main headers to not clutter the interface and to make a difference between headers people generally have/can set and other ones.
I'm closing as I'm still not convinced that this is useful.

**Comment by ThomasLandauer** [comment]
Well, I still can't see why adding a handful of `const`s somewhere would do any harm, or clutter anything.

But OK, it's not that important to have endless discussions over it...
