### ISSUE TITLE
Custom UserChecker dependency on "non existing service" error

### ISSUE THREAD

**Issue by filipealonso** [symfony/symfony#37365]
**Symfony version(s) affected**: 5.1

**Description**  
Created a custom UserChecker and get the following error
`The service "security.listener.user_checker" has a dependency on a non-existent service "Symfony\Component\Security\Core\User\UserCheckerInterface".`

**How to reproduce**  
Follow the provided documentation. https://symfony.com/doc/current/security/user_checkers.html .

Since the autowire and autoconfigure are on I didn't declare anything else in the services.yaml like it says at the bottom of the article.

When I add
`pattern: ^/`
`user_checker: App\Security\UserChecker`
to the security.yaml file I get the error as mentioned above.

**Possible Solution**  
Don't know. Either there's something wrong/outdated with the documentation or there's something wrong with the autowire/autoconfigure I assume.

**Comment by wouterj** [comment]
Thank you @filipealonso! I've provided a fix in https://github.com/symfony/symfony/pull/37366 . Am I correct that you're using the new Security system? (`enable_authenticator_manager: true`) That's great news :)

As a temporary fix, you can create a service alias for `UserCheckerInterface`:
```yaml
# config/services.yaml
services:
    # ...
    Symfony\Component\Security\Core\User\UserCheckerInterface: @App\Security\UserChecker
```

**Comment by filipealonso** [comment]
Hi @wouterj
Yes, indeed I'm using the new Security system :)

Thank you for both fixing and the temporary solution. I tested and can confirm it works now.
Keep up the good work.
