### ISSUE TITLE
Error after update from 5.1.0 to 5.1.2 caused by orm-pack / doctrine/migrations

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#37360]
**Symfony version(s) affected**: 5.1.2

**Description**  
After updating from 5.1.0 to 5.2 I get this error message:
`Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "factories", "migrations", "migrations_paths", "organize_migrations", "services", "storage".`

I don't know how to handle this. I tried to remove symfony/orm-pack and install only doctrine/bundle and doctrine/orm instead, but this did not work out. Any Ideas?

I also update composer to latest version 1.10.7.
PHP Version is 7.3.8 running on Windows 10

Here's my composer.json
```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-pdo": "*",
        "league/html-to-markdown": "^4.9",
        "phpoffice/phpspreadsheet": "^1.13",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "5.1.*",
        "symfony/console": "5.1.*",
        "symfony/dotenv": "5.1.*",
        "symfony/flex": "^1.7.1",
        "symfony/form": "5.1.*",
        "symfony/framework-bundle": "5.1.*",
        "symfony/mailer": "5.1.*",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "5.1.*",
        "symfony/translation": "5.1.*",
        "symfony/validator": "5.1.*",
        "symfony/yaml": "5.1.*",
        "twig/cssinliner-extra": "^3.0",
        "twig/extra-bundle": "^3.0",
        "twig/twig": "^3.0"
    },
    "require-dev": {
        "symfony/debug-pack": "^1.0",
        "symfony/maker-bundle": "^1.18"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "platform": {
            "php": "7.3.17"
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.1.*"
        }
    }
}
```
EDIT: Maybe related to https://github.com/symfony/symfony-docs/issues/13375 from March this year

**Comment by xabbuh** [comment]
It looks like you not only updated Symfony, but also update DoctrineMigrationsBundle from 2.x to 3.0 (see https://github.com/doctrine/DoctrineMigrationsBundle/issues/338).

**Comment by Shoplifter** [comment]
You're right . I ran `composer update` on the project. But shouldn't it be expected that the configuration in composer.json rules out incompatible packages? Migrations have been installed via symfony's doctrine recipe (install command:  `composer require doctrine` )

**Comment by tseho** [comment]
There is no version constraints in `orm-pack`, see https://github.com/symfony/orm-pack/blob/3644badedf565a5a0ff6b1cba117daee4bf7bdfc/composer.json

IMHO, you should unpack.
It's perfectly normal for Doctrine to introduce BC breaks in major versions and it's a really bad idea to use `"*"` as a dependency constraint.

And after unpacking, downgrade to `"doctrine/doctrine-migrations-bundle": "^2.0"`

**Comment by xabbuh** [comment]
:+1: thank you for the confirmation, let's close here then

**Comment by MakRatanakKh** [comment]
@Shoplifter I've had the same problem. I've been stuck at it for a week. But your idea solved my problem. Now It works. Thanks 😀

**Comment by TheKeymaster** [comment]
Anyone else having this issue, may check the latest [symfony/orm-pack v1.1.0](https://github.com/symfony/orm-pack/releases/tag/v1.1.0) release. They now have pinned all doctrine versions to version 2, which may have caused issues, since some people (me including) already updated it to version 3, and now we need to update it again to make it compatible with version 2 again.

Commit: https://github.com/symfony/orm-pack/commit/bd91c8fcf6c583c51bb2cb8d50dd661f5dad123a

*composer.json*
```json
"require": {
    "composer/package-versions-deprecated": "*",
    "doctrine/orm": "^2",
    "doctrine/doctrine-bundle": "^2",
    "doctrine/doctrine-migrations-bundle": "^2"
}
```

**Comment by ChrisBPB** [comment]
The latest release again goes back to v3 (https://github.com/symfony/orm-pack/commit/46aa731f213140388ee11ff3d2b6776a3b4a0d90)

So @Shoplifter has provider the solution above

**Comment by Nux007** [comment]
> 
> 
> Anyone else having this issue, may check the latest [symfony/orm-pack v1.1.0](https://github.com/symfony/orm-pack/releases/tag/v1.1.0) release. They now have pinned all doctrine versions to version 2, which may have caused issues, since some people (me including) already updated it to version 3, and now we need to update it again to make it compatible with version 2 again.
> 
> Commit: [symfony/orm-pack@bd91c8f](https://github.com/symfony/orm-pack/commit/bd91c8fcf6c583c51bb2cb8d50dd661f5dad123a)
> 
> _composer.json_
> 
> ```json
> "require": {
>     "composer/package-versions-deprecated": "*",
>     "doctrine/orm": "^2",
>     "doctrine/doctrine-bundle": "^2",
>     "doctrine/doctrine-migrations-bundle": "^2"
> }
> ```
Did the job ! Thank's ;-)

**Comment by DickelDia** [comment]
I had the same problem but now with your solution it works. Thank you so much !
