### ISSUE TITLE
Typed property and empty data (php 7.4)

### ISSUE THREAD

**Issue by adpeyre** [symfony/symfony#37377]
**Symfony version(s) affected**: 5.1.0

**Description**  
My class has a typed property. Empty value for this property in the submitted form shouldn't be converted to null.

What do you think about that ?

**How to reproduce**  
``` php
public string $title = '';
```

**`Type property App\Entity\MyEntity::$title must be a string, null used.`**

**Comment by xabbuh** [comment]
This looks expected to me. User submitted data are inherently invalid. The underlying data structure needs to adapt for that. I see several options:

* use a DTO (see https://stovepipe.systems/post/rethinking-form-development)
* allow `null` for you properties
* use something like [RichModelFormsBundle](https://github.com/sensiolabs-de/rich-model-forms-bundle/)
* write your own data mapper dealing with type errors

**Comment by xabbuh** [comment]
closing as explained above
