### ISSUE TITLE
[HttpClient] cURL handles are not resources in php8

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#37378]
**Symfony version(s) affected**: 5.1.2

**Description**  
A console tool that I'm building uses the HttpClient component to query an API. It works perfectly fine of php 7.4, but if I run it on php 8 with `ext-curl`, I get the following error:

```
TypeError {#81
  #message: "curl_setopt(): Argument #1 ($handle) must be of type CurlHandle, null given"
  #code: 0
  #file: "./vendor/symfony/http-client/Response/CurlResponse.php"
  #line: 72
  trace: {
    ./vendor/symfony/http-client/Response/CurlResponse.php:72 { …}
    ./vendor/symfony/http-client/CurlHttpClient.php:311 { …}
    ./path/to/my/code { …}
  }
}
```

**How to reproduce**  
The problem is apparently, that the code assumes that "curl handles" returned by `curl_init()` and `curl_multi_init()` are resources. However, in php 8 they're objects of type `CurlHandle`.

**Possible Solution**  
Adjust `CurlHttpClient` and related classes to the new type of curl handles. I could work on a patch.

**Additional Context**
`is_resource()` is called on a handle:
https://github.com/symfony/symfony/blob/2c9e9cd0c20f5206003948c63ba027ae760e060b/src/Symfony/Component/HttpClient/Response/CurlResponse.php#L46

A handle is cast to an int which does not work on objects:
https://github.com/symfony/symfony/blob/2c9e9cd0c20f5206003948c63ba027ae760e060b/src/Symfony/Component/HttpClient/Response/CurlResponse.php#L60

**Comment by nicolas-grekas** [comment]
PR welcome :)
See https://github.com/php/php-src/pull/5743 for some recent related progress.

**Comment by nicolas-grekas** [comment]
Oh, and if you're up to, we might want a Vardumer Caster for the new objects btw.

**Comment by derrabus** [comment]
See #37379 and https://github.com/php/php-src/commit/26171c3690874743e1c71766e60248fbd974782f

Thanks for the quick support, @nikic.
