### ISSUE TITLE
Swiftmailer: cannot send email with german umlauts in domain

### ISSUE THREAD

**Issue by antond1990** [symfony/symfony#37384]
**Symfony version(s) affected**: 2.8

**Description**  
I have a Symfony 2.8.x project which uses swiftmailer 2.6.3 and FOSUserBundle 1.3.7.

When I try to register with an email with german umlauts in domain - e.g. test@schöne-domain.de - I get the following error message:

Address in mailbox given [test@schöne-domain.de] does not comply with RFC 2822, 3.6.2.

The symfony validator validates this mail address as valid.

**Comment by xabbuh** [comment]
Swiftmailer has [its own repository](https://github.com/swiftmailer/swiftmailer/). If you think there is a bug, please report it over there. Thank you for understanding.

**Comment by YaFou** [comment]
I think it's a but because we are allowed to use accents in email addresses. To fix in Swiftmailer.
