### ISSUE TITLE
[Validator] Type Properties not working in Constraints

### ISSUE THREAD

**Issue by nico-incubiq** [symfony/symfony#37387]
**Symfony version(s) affected**: 5.1.2 (and others too, as long as you're using PHP 7.4 and typed properties)

**Description**  
PHP 7.4 introduced typed properties, which seem to be the way forward to build type-safe applications. But due to the way the Constraint component works to validate its options, it is not possible to use typed properties in a Constraint.

**How to reproduce**  
```php
class PostCode extends Constraint {
    public string $countryCode; // This is not initialised yet.
}

/// later ///

new PostCode(['countryCode' => 'CA']); // This throws an exception saying "countryCode" is not a valid option
```

**Possible Solution**  
The issue is due to the Constraint class using `get_object_vars($this)` in its constructor to find all the available properties on the class, which won't return the uninitialised ones, as explained here https://bugs.php.net/bug.php?id=78954. One solution is to use Reflection to find out what properties are available.

**Comment by nico-incubiq** [comment]
I've actually tried to use the Reflection API to fix this but it didn't help...
```
diff --git a/src/Symfony/Component/Validator/Constraint.php b/src/Symfony/Component/Validator/Constraint.php
index f967055211..929c5c65d5 100644
--- a/src/Symfony/Component/Validator/Constraint.php
+++ b/src/Symfony/Component/Validator/Constraint.php
@@ -107,7 +107,9 @@ abstract class Constraint
     {
         $invalidOptions = array();
         $missingOptions = array_flip((array) $this->getRequiredOptions());
-        $knownOptions = get_object_vars($this);
+        $knownOptions = array_map(function (\ReflectionProperty $property): string {
+            return $property->getName();
+        }, (new \ReflectionClass($this))->getProperties());
 
         // The "groups" option is added to the object lazily
         $knownOptions['groups'] = true;
~
```

**Comment by xabbuh** [comment]
see #37392

**Comment by nico-incubiq** [comment]
@fabpot this also need to go into newer branches, what's the process? thanks

**Comment by xabbuh** [comment]
@nico-incubiq Branches are regularly merged up into all other maintained branches.

**Comment by nico-incubiq** [comment]
Great, thank you
