### ISSUE TITLE
Form Regression / TransformationFailedException

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#37386]
**Symfony version(s) affected**: 4.4.10

**Description**  
I have a project on 4.4.8. I have a form with a compound child form. The child form will throw a TransformationFailedException for some missing fields. I updated and got v4.4.10. Somehow this is no longer works. Instead of the form being marked as invalid, the form is 'valid' as per $form->isSubmitted() && $form->isValid() but getData returns null.

**How to reproduce**  
I'll work to create a reproducer and edit this.

**Possible Solution**  
Not sure yet. I did a diff of the Form component and saw only minor changes so haven't isolated the issue yet.

**Comment by xabbuh** [comment]
Can you please check if this is the same as #37262 and thus fixed by #37345?

**Comment by gnat42** [comment]
Hello, I applied #37345 to my local project and that does indeed fix the issue (even though my fields aren't dates).

Duplicate of #37262
