### ISSUE TITLE
Form: NumberType option scale has a maximum of 12?

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#37398]
**Symfony version(s) affected**: 5.1.2 (maybe older versions too?)

**Description**  
For saving geocodes (latitude, longitude) to the database I tried to set the scale option for thes fields to 16, but the validator seems to round the value to 12 decimals only. I think it's the validator and not the view transformer, because stored values are displayed correctly.

*code in form builder*
 ```
  ->add('longitude', NumberType::class, [
                'required' => true,
                'label' => 'label.location.longitude',
                'scale' => 16,
                'attr' => ['readonly' => 'readonly']
            ])
```

**Comment by xabbuh** [comment]
Are you sure that's related to the validator and not how PHP handles these values?

**Comment by Shoplifter** [comment]
**Screenshot**

![image](https://user-images.githubusercontent.com/1181094/85411717-fc291b00-b568-11ea-943c-4d8c5599729c.png)


**Code**
```
dump($location->getLatitude());
$form->handleRequest($request);
dump($request->request->get($form->getName())['latitude']);
dd($location->getLatitude());
```
before submitting the form, the correct value has been displayed.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce this?

**Comment by Shoplifter** [comment]
never mind and sorry to have bothered you with that. Indead PHP is the 'culprit'. That thing simply happens when a string  is casted to float in php. bcmath might help here, but i guess I'll do well without this accurcy. Thnaks. Closing this.
