### ISSUE TITLE
[DomCrawler] Unexpected behavior while parsing commented html

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#37394]
**Symfony version(s) affected**: 5.0.8

**Description**  
Symfony DomCrawler respects comments. I don't know whether it's a bug or feature. Can I disable this behavior?

**How to reproduce**  
```
$html = <<<EOL
<head>
    <link rel='stylesheet' href='#' type='text/css' media='all' />
    <!--[if lte IE 8]>
        <link rel='stylesheet' href='#' type='text/css' media='all' />
    <![endif]-->
</head>
<body>
</body>
EOL;
        $crawler = new Crawler($html);

        /** @var \DOMElement[]|Crawler $aTags */
        $aTags = $crawler->filter('link');
        die(var_dump($aTags->count())); // 1 (One)
```
Expected result is 2

**Comment by stof** [comment]
The expected result is **not** 2. In browsers parsing HTML in the standard way (i.e., not old IE having this proprietary syntax for conditional comments), there is only one `<link>` tag. The second one you see is inside a comment.
