### ISSUE TITLE
How can i add an attribute to optgroup

### ISSUE THREAD

**Issue by hou1919** [symfony/symfony#37397]
I have a field with type ChoiceType in my choises option i have an array like this one : 
array:2 [▼
  "group1" => array:5 [▼
    "opt1" => 1
    "opt2" => 2
  ]
  "group2" => array:1 [▼
    "opt12" => 12
  ]
]

i want to add in my group1 the disabled property, how can i do this ?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
