### ISSUE TITLE
Forms: allow_extra_fields explanation

### ISSUE THREAD

**Issue by timrasche** [symfony/symfony#37407]
**Description**  
Please add explanation about sended fields that are not in form definition e.g. when received message "This form should not contain extra fields". It would be nice if keylist of the not allowed fields was send back in error details.

**Comment by xabbuh** [comment]
You can change the translation for the error message being used and embed the `{{ extra_fields }}` which will contain the extra fields. Does that solve your issue?

**Comment by timrasche** [comment]
> You can change the translation for the error message being used and embed the `{{ extra_fields }}` which will contain the extra fields. Does that solve your issue?

Thanks a lot. This helps for the moment. It would still be nice if you could evaluate this list programmatically, for example in the error details (not the text value)

**Comment by xabbuh** [comment]
I think you should be able to get them with something like `$error->getCause()->getInvalidValue()`.

**Comment by timrasche** [comment]
> I think you should be able to get them with something like `$error->getCause()->getInvalidValue()`.

Excuse the delay, your very welcome, thanks
