### ISSUE TITLE
[Mailer] Send email command

### ISSUE THREAD

**Issue by YaFou** [symfony/symfony#37409]
**Description**  
A simple command to send an email via the console (`bin/console`). It can be used for a test. There is already a command like this in the Swiftmailer Bundle (`swiftmailer:email:send`).

**Example**  

```
$ bin/console mail:send

From
> sender@localhost.fr

To
>receiver@localhost.fr

Subject
> A amazing subject!

Body
> Tell your life...

Email sent!
```

**Comment by garak** [comment]
I did same request a few months ago, Fabien told me that it's not needed/wanted in the core.
See #33694

**Comment by fabpot** [comment]
I haven't changed my mind :)

**Comment by sparrowek** [comment]
Such a command might be useful to test if mail setup is correct in a certain environment though. I mean to test sending a real email and not a unit test that mock up a mailer. Recently I had a problem where a mail was correctly sent on a developer machine but was not sent on the production server and there were no errors in the log. Or maybe there is already a better way to do it?
