### ISSUE TITLE
UniqueEntity constraint does not work when used on an embedded object using the Valid constraint

### ISSUE THREAD

**Issue by sandermarechal** [symfony/symfony#37405]
**Symfony version(s) affected**: 4.4.10

**Description**  
The UniqueEntity constraint does not work when used on an embedded object using the Valid constraint. It triggers a constraint violation when it should not.

**How to reproduce**  
I have two doctrine entities `Parent` and `Child` when `Parent` has a oneToMany to `Child` and reverse. The `Parent` entity has a UniqueConstraint. The `Child` entity has a Valid constraint on the `parent` field. If I create a new `Child` for an exisiting `Parent` and validate the `Child` entity, the UniqueConstraint fails if that parent already has another `Child`.

Example config:

```php
/**
 * @ORM\Entity
 * @UniqueConstraint(fields={"email"})
 */
class Parent
{
    /**
     * @ORM\Column(type="string")
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="Child", mappedBy="parent", orphanRemoval=true)
     */
    private $children;

    // ...
}
```
```php
/**
 * @ORM\Entity
 */
class Child
{
    /**
     * @ORM\ManyToOne(targetEntity="Parent", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     * @Valid()
     */
    private $parent;

    // ...
}
```

Then:
* Create parent 1
* Create child 1
* save
* Create child 2 for parent 1
* Validate child 2

Validation will fail. The UniqueConstraintValidator will compare an entity with a query result. But in this case the entity being passed to the validator is Child 2 and the query results contains Child 1.

I am not sure what the proper solution should be. I would expect that Parent 1 is passed to the UniqueConstraintValidator, not Child 2. But there's probably a good reason for that.

My workaround for now is removing the @Valid annotation and validating both parent and child separately.

**Comment by xabbuh** [comment]
I am not really sure to understand the issue. Could you create a small example application that allows to reproduce it?

**Comment by sandermarechal** [comment]
Yes, I'll try to create a skeleton app that reproduces the issue

**Comment by sandermarechal** [comment]
Nevermind. I could not reproduce it and eventually found a bug in my application code that also used a UniqueConstraint. My apologies.
