### ISSUE TITLE
Consider using another source for MIME types

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#37412]
**Description**  
PHP is switching from Apache to "MIME-db" because the Apache MIME type list is incomplete and it doesn't update frequently. See https://github.com/php/php-src/pull/5764

The differences are not huge, but for example, `.ini`, `.json5`, `.jsx`, `.less`, `.m4p` (<- not a typo) and other extensions are missing in our list but exist in MIME-db; others have different default types (e.g. `.gz`, `.xlf`, etc.)

**Comment by fabpot** [comment]
This should indeed be considered for master where we already have a script to update the list (`src/Symfony/Component/Mime/Resources/bin/update_mime_types.php`). Anyone willing to work on this?

**Comment by fabpot** [comment]
@desarrolla2 This issue is yours now. Thank you.
@redjanym Sorry, @desarrolla2 was faster. We will have some other ones though. I think I will start advertizing similar issues more in the future to give more opportunities. Anyway, thanks for proposing.
