### ISSUE TITLE
[Easy Admin 3.0] - Choice question must have at least 1 choice available

### ISSUE THREAD

**Issue by StephanGR** [symfony/symfony#37427]
Hi,

I got an error while i'm doing this command

`php bin/console make:admin:crud`

I got this error :

`In ChoiceQuestion.php line 36: Choice question must have at least 1 choice available.`

If someone got and idea i take :)

**Comment by stof** [comment]
`make:admin:crud` is not part of symfony itself. Please report that to the EasyAdminBundle repository: https://github.com/EasyCorp/EasyAdminBundle/issues
