### ISSUE TITLE
can't override error pages

### ISSUE THREAD

**Issue by tserofcj** [symfony/symfony#37439]
**Symfony version(s) affected**: 5.2

**Description**  
i've been trying to customize my error pages following the doc https://symfony.com/doc/master/controller/error_pages.html, but i got an error in dev env : "Argument 1 passed to Symfony\Bridge\Twig\Extension\RoutingExtension::getPath() must be of the type string, null given, called"
and in prod env my error pages are not overridedden

**How to reproduce**  
 create templates/bundles/TwigBundle/Exception/error.html.twig and try to check your error pages.
if i remove my file error.html.twig file, i got the original error page.

**Comment by xabbuh** [comment]
#
Can you create a small example application that allows to reproduce your issue?

**Comment by yceruto** [comment]
> "Argument 1 passed to Symfony\Bridge\Twig\Extension\RoutingExtension::getPath() must be of the type string, null given, called"

Can you show the content of your `templates/bundles/TwigBundle/Exception/error.html.twig` file? I seems you're missing the route name `{{ path(here) }}`

**Comment by tserofcj** [comment]
yes here it is : 
```
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Une erreur s'est produite</h1>
    <p>
        Veuillez contacter l'administrateur du site.
        <a href="{{ path('homepage') }}">Retourner sur la page d'accueil</a>.
    </p>
{% endblock %}
```

**Comment by tserofcj** [comment]
@xabbuh i created a new project and there was no error. I removed "{% extends 'base.html.twig' %}" from my template and it's working. base.html.twig exist, so it's weird

**Comment by xabbuh** [comment]
Do you maybe use something like `path(app.request.attributes.get('_route'))` in your base template?

**Comment by andreybolonin** [comment]
+1
5.2 version
use `path(app.request.attributes.get('_route'))`

**Comment by MarcoValeri** [comment]
I have the same issue and if I remove `{% extends 'base.html.twig' %}` from my error page it works.

Apparently, the issue is related to the `path(app.request.attributes.get('_route'))` that I'm using in the `base.html.twig`

**Comment by emircanerkul** [comment]
I got this error when I tried to put a canonical URL.

Here is the solution:

```twig
{% if app.request.attributes.get('_route') is not null %}
        <link rel="canonical" href="{{ url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}"/>
{% endif %}
```
