### ISSUE TITLE
Environment variables "APP_ENV" are never used.

### ISSUE THREAD

**Issue by Romaixn** [symfony/symfony#37434]
Symfony: 5.0.10

Same as https://github.com/symfony/symfony/issues/37123#issue-632482142 but with APP_ENV.

**Description**
After upgrading to 5.0.10 this error is shown every time, after Cache-Clear Symfony complains:

`Environment variables "APP_ENV" are never used. Please, check your container's configuration.`

I have the APP_ENV var in my .env set.

**Comment by EvKoh** [comment]
???
