### ISSUE TITLE
Symfony does not allow overriding the `--version` option

### ISSUE THREAD

**Issue by bor0** [symfony/symfony#37459]
**Symfony version(s) affected**: `"symfony/console": "^5.1"`

**Description**  
When overriding `\Symfony\Component\Console\Application`'s `getDefaultInputDefinition` to not contain `--version` - in attempt to use it in other commands - the framework will print the current version and exit instead of allowing you to get its input value and process

**How to reproduce**  
Have this application.php:

```php
<?php
namespace WR;

use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

/**
 * Overriding default Application class for implementation on some specific methods.
 */
class Application extends \Symfony\Component\Console\Application {
	/**
	 * Gets the default input definition.
	 *
	 * @return InputDefinition An InputDefinition instance
	 */
	protected function getDefaultInputDefinition() {
		return new InputDefinition(
			array(
				new InputArgument( 'command', InputArgument::REQUIRED, 'The command to execute' ),
				new InputOption( '--help', '-h', InputOption::VALUE_NONE, 'Display this help message' ),
			)
		);
	}
}
```

Further, implement a command that does `$input->getOption( 'version' );` and try to use that option in the command. Symfony will print the current application's version and exit, instead of printing the version.

**Possible Solution**  
I will create a proposed PR to address this. In my opinion, the main `--version` should only be printed if no other command was passed AND `version` exists in the default input definition.

**Comment by chalasr** [comment]
I'm going to close this one for the reason given in the linked PR. Thanks
