### ISSUE TITLE
File constraint and application/json mime type not working together

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#37457]
**Symfony version(s) affected**: 3.4.42

**Description**  

In my file upload form, I'm using a constraint similar to this for `FileType` form:

```
'constraints' => [
    new Constraints\File([
        'mimeTypes' => [
            'application/json'
        ],
    ])
]
```

Even if I upload a valid JSON file (with `.json` extension), Symfony complains that I uploaded `text/plain`. If I inspect the `UploadedFile` object, it has a correct mime type assigned. The validation fails because the `FileValidator` uses `UploadedFile::getMimeType` to validate the mime type, which in turn uses mime guesser which finally incorrectly guesses the mime type to be `text/plain`.

**How to reproduce**  

Create a file upload form which limits the mime type to `application/json` and upload a valid JSON document.

**Comment by mamontovdmitriy** [comment]
I can't reproduce this. I think the constraint works fine. Is your JSON file a really valid? Could you attach your file

**Comment by emodric** [comment]
Yes, the JSON file is valid. It is attached to this comment (with a `.txt` extension since it seems GitHub does not allow `.json` extension).

[example.txt](https://github.com/symfony/symfony/files/4857072/example.txt)

**Comment by emodric** [comment]
Here is a screenshot which shows that the `File` constraint fails, while `UploadedFile` has a correct mime type.

![image](https://user-images.githubusercontent.com/362286/86231767-55a9cf00-bb93-11ea-8060-d4e8cf8c5e6e.png)

**Comment by YaFou** [comment]
I managed to reproduce this bug and it is indeed present. I've created a small application to test it: https://github.com/YaFou/symfony-symfony-37457. I will investigate on it now.

**Comment by YaFou** [comment]
@emodric, I found the origin of this issue:
[The validator](https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/Validator/Constraints/FileValidator.php#L176) calls [this function](https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/HttpFoundation/File/File.php#L75) which defines the mime type from the file extension. However, before being sent to the server, the navigator stores the file as a temporary file on the disk, so its filename becomes `/path/to/tmp/xxxxx.tmp`. After this operation, the guesser can't define the mime type and believes that the file is a temporary file.
Sorry for the mistakes I may have made, I'm non-fluent in English 😅

**Comment by YaFou** [comment]
The better way to solve this issue is to get the client mime type with [this function](https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L112). I will open a new pull request.

**Comment by mamontovdmitriy** [comment]
I've just carried a small research. 
I think, this is not a Symfony issue. The matter is in a bug into `finfo` function. 
If we have an empty array in json (like this '"limitations": []'), it returns a wrong result ('text/plain').

Additional info:
- vendor/symfony/mime/FileinfoMimeTypeGuesser.php:57

**Comment by emodric** [comment]
@mamontovdmitriy Indeed. If I replace all empty arrays with some other value, it works fine. As soon as JSON file has an empty array (`[]`) or an empty object (`{}`), `FileinfoMimeTypeGuesser` fails to recognize it as `application/json`.

**Comment by YaFou** [comment]
Fixed: #37468

**Comment by emodric** [comment]
I don't know if this is a bug in PHP or it is system related, bug I have reported it to bugs.php.net nevertheless: https://bugs.php.net/bug.php?id=79764

**Comment by YaFou** [comment]
I think the problem does not come from PHP because I resolved this bug in my pull request above. Today, the validator gets the mime type from the base file (the temporary file) because it checks if the file is just an instance of an HTTP Fondation file. But the uploaded file provides a second path which is the original path and provides also a function to get the mime of this original file. To resolve it, I've just checked if the file is an instance of an uploaded file and get the mime type of the client file (the original file).

**Comment by emodric** [comment]
@YaFou Your fix potentially fixes this for Syfmony (which is also fine and thank you for this!), but I reported it to PHP project because I managed to reproduce it without Symfony on latest PHP version.

**Comment by mamontovdmitriy** [comment]
@emodric , Great!

**Comment by nicolas-grekas** [comment]
I think there is no bug here. Guessing naturally leads to false guesses, but at least they are safe (not trusting user input by default.)

Maybe we could guess first, then have some logic to validate that the submitted content-type is acceptable (by using the guess + some extra logic I suppose).

That'd be a new feature for sure (and I don't know how this would be implemented exactly - to be investigated).

**Comment by xabbuh** [comment]
> EDIT: Not a bug in PHP, turns out that `file` command on my system returns `text/plain` for that file. Why, I don't know :(

I'd vote to close here then as there is nothing we can do about that.
