### ISSUE TITLE
 PHP Notice:  Only variables should be assigned by reference 

### ISSUE THREAD

**Issue by arunkumar4534** [symfony/symfony#37467]
How to fix the following error?

PHP - 7.2.31

PHP Notice:  Only variables should be assigned by reference in /var/www/html/plugins/system/jxtcadminlock/jxtcadminlock.php on line 39

**Comment by stof** [comment]
This error does not happen in Symfony. The symfony issue tracker is not a support forum for random PHP issues. Try asking on stackoverflow or in the issue tracker of that jxtcadminlock plugin (whather that is).
