### ISSUE TITLE
And what about Generators in DomCrawler?

### ISSUE THREAD

**Issue by kirya-dev** [symfony/symfony#37465]
And what about Generators?

`yield from $nodes->each()` doesnt work :-(

**Comment by YaFou** [comment]
I don't know what you mean by that but referring to [the documentation](https://symfony.com/doc/current/components/dom_crawler.html#accessing-node-values) the `each` function works like a foreach:
```php
$crawler->each(function(Crawler $node) {
    echo $node->text();
});
```

**Comment by kirya-dev** [comment]
Use echo bad practices.
Following code must be works?

`yield from $crawler->each(function(Crawler $node) {
    yield $node->text();
});`

**Comment by YaFou** [comment]
This should work:
```php
function doEach(): Generator
{
	$html = <<<'HTML'
	<!DOCTYPE html>
	<html>
		<body>
			<p class="message">Hello World!</p>
			<p>Hello Crawler!</p>
		</body>
	</html>
	HTML;

	$crawler = new Crawler($html);

	yield from $crawler->each(function(Crawler $node) {
		return $node->text();
	});
}

foreach(doEach() as $text) {
	echo $text;
}
```

**Comment by Tobion** [comment]
@kirya-dev The closure you pass must return the value, not yield it. See https://github.com/symfony/symfony/blob/8cc90b984500222ce3213844f6eb9e0d51aed797/src/Symfony/Component/DomCrawler/Crawler.php#L338-L346
So this is the correct code:

```
yield from $crawler->each(function(Crawler $node) {
    return $node->text();
});
```

For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by kirya-dev** [comment]
What if 
```PHP
yield from $crawler->each(function(Crawler $node) {
    $text = $node->text();
    if ($text) {
         return $node->text();
    }
});
```
