### ISSUE TITLE
Improve folders customization

### ISSUE THREAD

**Issue by Nayte91** [symfony/symfony#37475]
Hi there,

So, how can I tell symfony to respect a folder template ? I looked (quickly) into config/ files & service container doc, but didn't see such setting. Any idea ?

**Description**  
Regulary pulling new versions of the symfony demo blog, I saw that they moved the migration/ folder from src/ to /, and that's something I like a lot because:

- It reduce the size of src/, relieve it from more "data & structure oriented" parts of the symfony tools
- Allow the src/ to bright more as a business code folder than a symfony/doctrine/whatever perfect little project.

So I did the same as @rosier, editing services.yaml & doctrine_migrations.yaml. Then I wanted to do so with some others :

- move fixtures from src/ to /data (Along with Migrations/ & sqlite db if configured so)
- move repository/ from src/ to src/entity
- maybe pull out controllers also from src/, why not, but not sure. Anyway, "personal decision" you know.

But here's the problem : changing the namespace is not enough. When I move repository/, I have some injections that break also. And when I move fixtures, they aren't find anymore, even if they implements ORMFixtureInterface.

of course, it needs more configuration. And as far as I know, we don't have the possibility to set the default-directory of those classes.

Maybe configs would carry this information, and it's a pretty good timing with your php-config-revamp to think about it.

WDYT ?

Best regards,
Julien

**Comment by wouterj** [comment]
Data fixtures is something belong to the DoctrineFixturesBundle and I believe they need to conform to some specific folder.

As for controllers and repositories, there is no required for them to be in any namespace (same applies to many other classes).

**Comment by ro0NL** [comment]
see https://github.com/symfony/recipes/issues/718

and related demo change https://github.com/symfony/demo/pull/1125

not to fond of this practice where the demo goes ahead from the recipe.

**Comment by xabbuh** [comment]
I don't really see (or understand) what needs to be done here or what is the actual suggestion for changes.

**Comment by xabbuh** [comment]
I am closing here for now. We can still reopen when there are more concrete ideas to discuss.
