### ISSUE TITLE
[HttpClient] Make the client aware of throttling / rate limits

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony#37471]
**Description**  
When making API requests, some providers implement rate limits: for example, an API might define that you can only perform 50 requests in five seconds. All exceeding requests will be answered with error code 429 ("Too many requests").

Currently, this error is not caught or handled anywhere. A future solution could catch this directly somewhere in the core HttpClient and react to it: simply wait for some time (maybe the response's headers already tell you how long to wait?) and retry the request.

@nicolas-grekas already provided the first steps in #36779, and I'd like to see how this could help to resolve 429 responses

**Comment by stof** [comment]
Well, that's a perfect job for a decorating client rather than having it in the core HttpClient class. Then, whether this decorator is implemented in core or in third-party remains to be decided (to have it in core would require that the way to determine the action to do is standard, to avoid needing to have multiple such decorators in core).

**Comment by NicoHaase** [comment]
That's my plan :) With "the core HttpClient", I wanted to refer to the component, not to the class itself. 

As you are speaking of the "standard", would you have one in mind? I've asked @nicolas-grekas about his thoughts, and he recommended to evalute whatever the [`Retry-After` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) provides.

**Comment by mynameisbogdan** [comment]
More likely HttpClient needs middleware support. I'm already using a throttling middleware in Guzzle which doesn't mess with the "core".

**Comment by nicolas-grekas** [comment]
5.2 provides all the required infrastructure, see https://github.com/symfony/symfony/pull/36779

**Comment by NicoHaase** [comment]
@nicolas-grekas I don't want to sound stupid, but could you explain that further? All that I came up with so far is https://github.com/NicoHaase/symfony/blob/feature/37471-http-throttling/src/Symfony/Component/HttpClient/ThrottleAwareHttpClient.php (while still lacking the evaluation of all 429 related headers to delay the next request attempt), and it does not look related to #36779 after all

**Comment by nicolas-grekas** [comment]
The linked code defeats async. Making it both async and non blocking (aka no usleep()) requires leveraging AsyncResponse.

**Comment by brentybh** [comment]
@NicoHaase You may take a look at [this](https://github.com/symfony/symfony-docs/pull/13736/files) and [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpClient/Tests/AsyncDecoratorTraitTest.php) to have a basic idea of how to use it.
But honestly I think it should be explained more. Because I still don't have idea how to build to practical thing with it.

**Comment by nicolas-grekas** [comment]
Here is another PR where AsyncResponse ise used: https://github.com/symfony/symfony/pull/36692
Help welcome to improve the doc!

**Comment by NicoHaase** [comment]
@nicolas-grekas thanks for linking that PR - I think I'm starting to understand. Is https://github.com/NicoHaase/symfony/blob/feature/37471-http-throttling/src/Symfony/Component/HttpClient/ThrottleAwareHttpClient.php going in the right direction?

**Comment by nicolas-grekas** [comment]
Yes, that's a good start!
You'll need to yield the chunk in the `else` case.

**Comment by wouterj** [comment]
In my RateLimiter component PR (which we decided does not directly relate to this one), I was made aware of this blog posts showing a more advanced backoff algorithm to handle the wait time: https://blog.heroku.com/rate-throttle-api-client Might be of interest for this implementation as well :) (or maybe some sort of customizable backoff algorithm?)

**Comment by NicoHaase** [comment]
As far as I see, this looks solved through https://github.com/symfony/symfony/pull/38182
