### ISSUE TITLE
[HttpClient] HttplugClient::sendAsyncRequest doesn't always return full promise implementation

### ISSUE THREAD

**Issue by brentybh** [symfony/symfony#37488]
**Symfony version(s) affected**: 4.x, 5.x

**Description**  

https://github.com/symfony/symfony/blob/b3df84c857f41084720f58aef91fe35e272bc3b6/src/Symfony/Component/HttpClient/HttplugClient.php#L117
`RejectedPromise` returned here is `Http\Promise\RejectedPromise`, but not the full implementation like `Symfony\Component\HttpClient\Response\HttplugPromise` (as in docblock `@return`)
This can cause problem. For example, promises returned by then functions will be treated as plain value.

The code:
https://github.com/php-http/promise/blob/02ee67f2346b4eec3861afec741c656f5ff717ab/src/RejectedPromise.php

How Guzzle promise settle promises:
https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/RejectedPromise.php#L40
https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/Promise.php#L108

**How to reproduce**  

https://github.com/brentybh/symfony-37488
Sorry, it's not finished yet.
Because I have to bring in a retry middleware.
The Httplug simple promise CAN cover most simple use cases. But the retry middleware implementation is different...
**Possible Solution**  

emm.. Maybe it's not strictly an issue of Symfony but a problem of Httplug....
**Additional context**

**Comment by nicolas-grekas** [comment]
Can you try this patch? does it fix the issue? If yes, can you please add a test case and submit it as PR (with the patch)?

```diff
--- a/src/Symfony/Component/HttpClient/HttplugClient.php
+++ b/src/Symfony/Component/HttpClient/HttplugClient.php
@@ -12,6 +12,7 @@
 namespace Symfony\Component\HttpClient;
 
 use GuzzleHttp\Promise\Promise as GuzzlePromise;
+use GuzzleHttp\Promise\RejectedPromise;
 use Http\Client\Exception\NetworkException;
 use Http\Client\Exception\RequestException;
 use Http\Client\HttpAsyncClient;
@@ -22,7 +23,6 @@ use Http\Message\RequestFactory;
 use Http\Message\StreamFactory;
 use Http\Message\UriFactory;
 use Http\Promise\Promise;
-use Http\Promise\RejectedPromise;
 use Nyholm\Psr7\Factory\Psr17Factory;
 use Nyholm\Psr7\Request;
 use Nyholm\Psr7\Uri;
@@ -114,7 +114,7 @@ final class HttplugClient implements HttplugInterface, HttpAsyncClient, RequestF
         try {
             $response = $this->sendPsr7Request($request, true);
         } catch (NetworkException $e) {
-            return new RejectedPromise($e);
+            return new HttplugPromise(new RejectedPromise($e));
         }
 
         $waitLoop = $this->waitLoop;
```

**Comment by brentybh** [comment]
It should fix. I'll test it tomorrow.
But the problem is that I need to return a Guzzle promise inside the then function, because HttplugPromise is on top of Guzzle promise.
Anyways, this is the best quick fix available

**Comment by nicolas-grekas** [comment]
Tomorrow is great. It should work with a Guzzle promise I suppose, these things are quite interoperable.

**Comment by brentybh** [comment]
Found the way to solve the issue! PR soon

**Comment by brentybh** [comment]
PR here #37491
