### ISSUE TITLE
Master and slave databases are not synchronized

### ISSUE THREAD

**Issue by wspot** [symfony/symfony#37487]
hello everyone ,
i followed the [Symfony docs](https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html )  to configure master and slave replication  : 

<pre>
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset:  UTF8
                schema_filter: ~^(?!zipdata|custom_field_setting|import_user_|user_ambassadors)~
                slaves:
                    slave1:
                        dbname:               '%env(resolve:SLAVE_DBNAME)%'
                        host:                 mysql
                        port:                 3306
                        user:                 '%env(resolve:SLAVE_DBUSER)%'
                        password:             '%env(resolve:SLAVE_DBPASS)%'
                        charset:              UTF8
</pre>

the result is everything working perfectly : (inserts and updates operations goes to the master / reads operations are coming from the slave) ,  **but the problem is the master and slave are not synchronized** ( the slave is not getting the changes that happens on the master database ) .
 so here is my question : is my config wrong or the symfony framework does not take care of synchronizing the two databases ?

**Comment by chapterjason** [comment]
Symfony do not sync any databases. It's a feature of your mysql database to make master-slave replications.

**Comment by wspot** [comment]
@chapterjason thank you , i don't have any doubts about that now :+1:
