### ISSUE TITLE
Remove putenv() calls in Symfony/Console/Application

### ISSUE THREAD

**Issue by Bertie2011** [symfony/symfony#37489]
*This is a request for change, it's not a bug, neither a new feature*

**Description**  
Most shared hosting servers disabled the usage of putenv(). So after commenting out all putenv calls in the Application class, calling `Artisan::call('migrate')` from Laravel still works. The putenv calls only register console width and height, so I don't see why that has to be in an environment variable. I would argue that it's bad OO programming, but I don't know the fine details of it. If this "request" gets denied, perhaps somebody could clarify why it's necessary?

**Side Note**
I saw that the "Support" template had a ⛔ sign and a link to a symfony web page. As far as I could tell, I had to either create a new community account that I didn't want to create or use the "support for commerical products" form, which I don't own a license for. Perhaps a more common platform, like Discord or whatever would be a nice addition.

**Comment by Bertie2011** [comment]
So I did a full search on the vendor directory of my Laravel project and the only occurances of `LINES` and `COLUMNS` (the variables being set) is in the getHeight and getWidth methods of Symfony/Console/Terminal. The interesting thing is that those methods are also the ones supplying the values for the putenv() calls.

![image](https://user-images.githubusercontent.com/44732286/86483235-e929fe00-bd53-11ea-836f-4006e3520c96.png)
![image](https://user-images.githubusercontent.com/44732286/86483258-f6df8380-bd53-11ea-9194-cd0e5a936574.png)

It seems like env is used to cache results from a previous call. This use case could be implemented in so many other ways.... There is setenv(), $_ENV, a singleton could be used, perhaps a static field, etc....

Even if putenv() cannot be removed, perhaps a simple wrap in try/catch will do, since there are already 2 other fallbacks implemented. (`self::initDimensions()` and `50`)

**Comment by wouterj** [comment]
Related: https://github.com/symfony/symfony/pull/19724 Feel free to submit a  PR if we can find an alternative that supports that case as well.

_Btw, it's not really constructive to call a `putenv()` call "bad OO programming". It literally has nothing to do with that, and even if it did, the statement doesn't add anything to the process of solving your problem_

**Comment by linaori** [comment]
@Bertie2011 when you follow the link listed when opening a new issue, you will see this: 
![image](https://user-images.githubusercontent.com/1754678/86647730-94e77e00-bfe0-11ea-9284-d687d02ea3e2.png)

**Comment by Bertie2011** [comment]
Oh, on the desktop version of the page it isn't as obvious and I've missed those links. Even on the desktop version they're still in plain sight, so I don't know why I've missed them.

**Comment by chalasr** [comment]
This issue is getting old and did not receive much attention so far (which hints that it does not impact much people).
Feel free to open a PR for changing `putenv()` to another alternative.
Closing meanwhile. Thanks everyone.
