### ISSUE TITLE
TokenInterface parameter might be null

### ISSUE THREAD

**Issue by gassan** [symfony/symfony#37501]
**Symfony version(s) affected**: 5.1.2

**Description**  
Token might be null if enable_authenticator_manager = true
Error:
Argument 3 passed to Symfony\Component\Security\Http\RememberMe\AbstractRememberMeServices::logout() must be an instance of Symfony\Component\Security\Core\Authentication\Token\TokenInterface, null given, called in /usr/www/users/igneed/login/vendor/symfony/security-http/EventListener/RememberMeLogoutListener.php on line 47

**How to reproduce**
add remember_me section to main firewall and unauthenticated go to /logout 

**Possible Solution**  

add ? to last parameter (?TokenInterface) in Symfony\Component\Security\Http\RememberMe\AbstractRememberMeServices::logout()

**Comment by chalasr** [comment]
See #37504
