### ISSUE TITLE
[Console] Color support detection ends with TypeError on Windows and PHP 8

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/symfony#37508]
This is the same problem as https://github.com/symfony/symfony/issues/26210 but `@` silence operator doesn't help because it ends with TypeError:

```php
TypeError: sapi_windows_vt100_support() was not able to analyze the specified stream
```

**Comment by nicolas-grekas** [comment]
Shouldn't this be reported as a bug to PHP instead? TypeError looks wrong to me.

**Comment by ondrejmirtes** [comment]
I'm trying to submit a bug to PHP but currently can't: https://twitter.com/OndrejMirtes/status/1280248625554247681

I'll let you know what happens next :)

**Comment by ondrejmirtes** [comment]
I was able to open the bug: https://bugs.php.net/bug.php?id=79805

**Comment by ondrejmirtes** [comment]
Linking PR in php-src: https://github.com/php/php-src/pull/5863

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/php/php-src/pull/5863, thanks for the report and the follow up.
