### ISSUE TITLE
[Console] doctrine:query:sql issue when two fields have same name 

### ISSUE THREAD

**Issue by xmillies** [symfony/symfony#37525]
**Symfony version(s) affected**: 5.1.2

**Description**  
doctrine:query:sql issue when two fields have same name 

**How to reproduce**  

select t1.id, t2.id from t1 inner join t2 on t1.id = t2.id

**Possible Solution**  
use full field name when several same field name.

**Comment by ro0NL** [comment]
Doesnt this belong to the DoctrineBundle repo? As it's the actual vendor defining the `doctrine:query:sql ` command.

**Comment by xabbuh** [comment]
closing here as the command is not provided by Symfony itself as explained in https://github.com/symfony/symfony/issues/37525#issuecomment-655573564
