### ISSUE TITLE
[Security][new system] Voter can not vote anymore on "anonymous"

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#37523]
**Symfony version(s) affected**: 5.1

**Description**  

_With the new Security system (5.1+) enabled_

We have some a specific use case in our app I couldn't find how to handle: Voter can not handle anymore authorization of anonymous/unconnected users.

Our use case in details:
 - some objects in our application can be seen by everybody (including anonymous Users) or only some specific Users
 - so those objects each have `isGranted(?User $user)` method
 - to handle that, a Voter is used, it will fetch token from Security and call object's `isGranted` with the User it eventually found, or `null`

if there is no connected User, we are getting a `InsufficientAuthenticationException`: "Full authentication is required to access this resource"
The exception is raised by `Symfony\Component\Security\Core\Authorization\AuthorizationChecker:isGranted()`. It throws exception when there is no token. In the legacy system, an `AnonymousToken` was present.

**How to reproduce**  

1. set `security.enable_authenticator_manager: true`
2. implement a Voter which allows anonymous Users
3. configure any controller action with corresponding security attribute
4. try to access it while unlogged

**Possible Solution**  

Right now, I couldn't think of any work around in userland, as it happens in the authorization layer, outside of the authentication Guard we can configure.

Twig is working around it with a `try... catch`- which is also creating an inconsistency, btw (#30609) - but it prevents Voters from being able to decide if an anonymous User can be granted or not (cf. line 55 of `Symfony\Component\Security\Core\Authorization\AuthorizationChecker:isGranted()` - if there is no token, even if no exception is sent, all authorization checks are bypassed).

I have the impression a bypass over authentication/authorization separation - maybe something like `AuthenticationVoter`? Of `Voter::supportsAnonymous`?
`AuthorizationManager` could then call these voters even if no token is present.

*Edit:* I found an ugly workaround, adding an `AnonymousAuthenticator` called on every request, to re-add an `AnonymousToken` through an `AnoymousPassport`(internal class). It feels a little bit hacky to do that user-side, but it allows to keep BC:
https://gist.github.com/romaricdrigon/63f1d83ba7c516e6c6205b384c18376f

**Additional context**  

RFC related to the same topic: #30609

**Comment by wouterj** [comment]
Hi! Thanks for sharing so much detail. There are two things going on here:

**1) You get an exception.** That is slightly surprising, because I introduced a flag to not throw the exception when using the new system:

https://github.com/symfony/symfony/blob/ba4d57bb5fc0e9a1b4f63ced66156296dea3687e/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php#L50-L56

Is there a chance you can check if that exception is correctly configured in your case? (it should be `false` in the new system)

**2) You need `isGranted()` to grant access to some public entities.** This is a use-case that is very common, but we somehow completely missed while writing the new system. A month ago, I've talked about this with Ryan and we think we'll have a solution (creating a `NullToken`, which is only used in the `AuthorizationChecker` if there is no token). I'll come up with a PR soonish.

**Comment by wouterj** [comment]
Status: Reviewed

**Comment by romaricdrigon** [comment]
Hello,

**1)** Indeed, my first report phrasing is a little bit ambiguous - sorry: `Exception` is raised by `IsGrantedListener`, not by `AuthorizationChecker` itself. The flag `$exceptionOnNoToken` is `false` as it should.

I wanted to say "it leads to an exception later".  Which leads to **2)**, and indeed a `NullToken` sounds like a possible approach

I migrated an app with some complex authentication scenarios to the new authenticator-based system, and I found a few more small issues / things to polish. I will open a few more reports / suggestions, but nothing major, really it is way better than the old system - thank you for your work!

**Comment by wouterj** [comment]
> I migrated an app with some complex authentication scenarios to the new authenticator-based system, and I found a few more small issues / things to polish.

Thank you! Great to see a complex security system being an early adapter of the experimental system. That can only result in a more polished stable version of the system!
