### ISSUE TITLE
Keyword self used as type hint to RouteCollection::addCollection

### ISSUE THREAD

**Issue by Addvilz** [symfony/symfony#37522]
**Symfony version(s) affected**: 5.x

**Description**  
`\Symfony\Component\Routing\RouteCollection::addCollection` uses `self` as parameter type hint. It should use `RouteCollection` instead. 

Using self as a type hint in method declarations prevents extension of the RouteCollection, particularly, when creating test doubles (Prophecy).

Ex.

```
warning: 
Declaration of Double\Symfony\Component\Routing\RouteCollection\P12::addCollection(Double\Symfony\Component\Routing\RouteCollection\P12 $collection) 

should be compatible with

Symfony\Component\Routing\RouteCollection::addCollection(Symfony\Component\Routing\RouteCollection $collection)

in XXXvendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) :eval()'d code line 2
```

**Possible Solution**  
Replace `self` with `RouteCollection`

**Comment by xabbuh** [comment]
This rather looks like something that needs to be fixed in Prophecy then.

**Comment by Addvilz** [comment]
I don't believe so. Using `self` as a method type hint is ambiguous and fairly useless since you can't actually use that information anywhere in the implementation - you can only have an implementation against something that is known, not against some potential subclass that might or might not exist. Since that is true, and the information `self` carries is inherently discarded anyway, having a concrete hint would serve better because the at the end - it would work exactly the same, but the public interface of the `RouteCollection` would be much clearer.

On a sidenote, I am preparing a ticket for Prophecy to handle this case better, however, I also think this should be changed in the Router (and potentially wherever else it's done in a similar manner).

On another sidenote, I have no clue why PHP even allows self as type hint in arguments, I can't think of a single case where it makes sense. As a return type - sure, reflection and all that. But as a type hint...?

**Comment by ciaranmcnulty** [comment]
Is this https://github.com/phpspec/prophecy/issues/484 ?

**Comment by nicolas-grekas** [comment]
Using self and/or RouteCollection have strictly the same meaning.
Thanks for the link @ciaranmcnulty 
Closing here as that's a bug in prophecy.

**Comment by Addvilz** [comment]
@nicolas-grekas sorry, but I don't agree - public interfaces should be explicit and communicate intent clearly. Using self as a type hint only serves to introduce ambiguity (why self? is there special anything about how the argument is handled? ... etc) - so despite the fact that they are effectively the same feature-wise, using self as a type hint has no value to anything - on the contrary, using concrete hint has a benefit of communicating clearly what the interface expects to receive and what it is implemented against. All in all I'd say this is a code smell.

I understand this is a trivial issue and perhaps not worthy of a bug, but then again - changing this would make the interface clearer than it is now.

I suspect above is also the reason why there are only handful of cases I found where this is actually used in Symfony codebase. so if you want more arguments - consistency might be another.

**Comment by nicolas-grekas** [comment]
`self` and `RouteCollection` have *strictly* the same meaning in this class. This means we're arguing over a pure code-style issue, isn't it? There's no point arguing over these. No style is right or wrong when they mean exactly the same. It then becomes a pure matter of preference. Once a preference is set, what is important is consistency. In the Symfony codebase, we use php-cs-fixer to consistently use `self` all the time when possible.

**Comment by Addvilz** [comment]
`php-cs-fixer` indeed seems to replace concrete hints with self with Symfony .php_cs. I still don't think it's a good idea, but since that is how it is implemented already, I rest my case.

**Comment by ro0NL** [comment]
self avoid terms duplication in general, it's a plus :)

**Comment by nicolas-grekas** [comment]
It's a pure matter of preference. Let's stop before entering into bikeshedding, please.
