### ISSUE TITLE
Code style question about "private static function" usages instead of instance method usages

### ISSUE THREAD

**Issue by ionutcodreanu** [symfony/symfony#37531]
Hello,

I see in the project codebase some usage of "private static function". I'm curious what is the reasoning behind using "private static function" instead of instance method "private function" and if there any guidelines when to use class vs instance method in private scope.

A sample is src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php:110

Thanks for your time.

**Comment by ro0NL** [comment]
as i wrote AboutCommand.php:110 :) i followed my personal rule of thumb; use static if you dont need the instance :sweat_smile: usually utililty code, or anything "stateless".
