### ISSUE TITLE
Error: Remember-me user when reopens browser - Call to a member function getUser() on null.

### ISSUE THREAD

**Issue by featuriz** [symfony/symfony#37534]
**Symfony version(s) affected**: 5.1.2

**Description**  
When user successfully logged in and restart browser (closed the browser tab and browser). Later when open browser and visit any page. Site throws error as follows:
**Call to a member function getUser() on null.**
From: 
[symfony\security-http\Authenticator\RememberMeAuthenticator.php (line 76)]( https://github.com/symfony/security-http/blob/master/Authenticator/RememberMeAuthenticator.php)
Code: (At the time of my error)
```

 public function authenticate(Request $request): PassportInterface
    {
        $token = $this->rememberMeServices->autoLogin($request);
        return new SelfValidatingPassport($token->getUser());
    }

```

**How to reproduce**  

1. - Symfony 5.1.2 login with remember-me checkbox.
2. - Close browser tab and close browser.
3. - Open browser and go to any page.

**Possible Solution**  
I'm not sure about this, but #37504. will help, i think so.
Here, when logout token checking is removed (else throws error when logout. #37510). Url /logout works fine.

**Comment by featuriz** [comment]
When I open the page for first time the error throws. But if I refresh, the error goes, and works good. 
**As per now:**
The error is only for FIRST RUN.

**Comment by featuriz** [comment]
I think I found the correct problem, maybe i'm on the right track.
My auth code is:
```
public function authenticate(Request $request): PassportInterface {
        $credentials = $this->getCredentials($request);
        $user = $this->getUser($credentials);
        return new SelfValidatingPassport($user, [
            new RememberMeBadge(),
            new CsrfTokenBadge('authenticate', $request->request->get('_csrf_token'))]);
    }
```
Here, **SelfValidatingPassport** has $user and custom array. But the error shows, only user is passed, while/when remember-me browser restart. So, we need a proper place to do all these stuff, or do something on the core (as per error msg file symfony\security-http\Authenticator\RememberMeAuthenticator.php (line 76).)

**Comment by featuriz** [comment]
ADDITIONAL PROBLEMS:
1. On a normal browser run everything working fine.
2. When close the browser and open the page. I GET THIS ISSUE ERROR.
3. When refresh the page, error disappears, I'm logged in as previous user - good and fine
4. Again if I restart the browser, There is no error. I'm logged out. 

When working on this I noted that at 3rd point, There is no remember-me cookie.

As per security doc: We can give always remember me. Do i have to do "always remember-me" or stay with this. :: For this I have set 1 week time for remember me.

**Comment by PhilETaylor** [comment]
I can replicate this.

The underlying root issue I can replicate is this

 - Start project AA (dockerised)
 - note that Project AA loads from http://127.0.0.1/
 - Login to project AA with username/password and remember me checked 
 - Stop docker containers
 - Start Project BB
 - navigate to http://127.0.0.1/ expecting to see Project BB login page 
 - See the reported error.

This is because Project BB is reading the project AA remember me cookie... and failing to return a token based on that as the users are all different in Project BB.

**Comment by wouterj** [comment]
Thank you for the reports and replication steps. I think this should be fixed by: https://github.com/symfony/symfony/pull/37943 It would be great if anyone can confirm this by testing the changes to the `RememberMeAuthenticator` locally :)

**Comment by PhilETaylor** [comment]
I have tested #37943 against my [replication steps](https://github.com/symfony/symfony/issues/37534#issuecomment-671906602) in  #37534 and it resulted in a graceful failure as expected. 🎉🎉 Thanks for this @wouterj
