### ISSUE TITLE
Symfony\Component\Validator\Context;

### ISSUE THREAD

**Issue by inforob** [symfony/symfony#37530]
i have a problem when i build a custom constraint for a normal formType. The text is :
`Error: Class Symfony\Component\Validator\Context\ExecutionContext contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Validator\Context\ExecutionContextInterface::addViolationAt`

i have fix adding in class Symfony\Component\Validator\Context\ExecutionContext
`   public function addViolationAt(string $string, string $string1)
    {
        // TODO: Implement addViolationAt() method.
    }`

i dont know if this is deprecated

**Comment by xabbuh** [comment]
Without knowing what exactly you did I would doubt that there really is a bug, but I would rather guess that you somehow made a mistake. If you still think there is something wrong, please provide some steps to reproduce this.

**Comment by inforob** [comment]
i write this in my formType 
` $builder
                ->add('password', PasswordType::class)
                ->add('repeat-password', PasswordType::class, [
                    'mapped' => false,
                    'required' => true,
                ])->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
                    $data = $event->getData();
                    $form = $event->getForm();

                    if($data['password'] !== $data['repeat-password']){
                        $form
                            ->add('password', PasswordType::class, [
                                'constraints' =>  new Assert\Callback([$this, 'validateEventDates']),
                            ])
                        ;
                    }
                });`

and add the method 

`  public function validateEventDates(string $value, ExecutionContextInterface $context)
    {
        $context->buildViolation('This name sounds totally fake!')
            ->atPath('password')
            ->addViolation()
        ;
    }`

and launched the exception of before

**Comment by inforob** [comment]
this is my custom constraint:

```
 if($data['password'] !== $data['repeat-password']){
                        $form
                            ->add('password', PasswordType::class, [
                                'constraints' =>  new Assert\Callback([$this, 'validateEventDates']),
                            ])
                        ;
                    }
```

and my method
```
 public function validateEventDates(string $value, ExecutionContextInterface $context)
    {
        $context->buildViolation('This name sounds totally fake!')
            ->atPath('password')
            ->addViolation()
        ;
    }
```

when i submit the form then appear the exception of before

**Comment by inforob** [comment]
the interface **ExecutionContextInterface** has a method for implement

` public function addViolationAt(string $string, string $string1);` and the class **ExecutionContext** not implement it

**Comment by xabbuh** [comment]
I don't know where you found that method nor how you ended up with this error. Please create a small example application that allows us to reproduce it.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
