### ISSUE TITLE
Doctrine Migration Freezes

### ISSUE THREAD

**Issue by hbrawnak** [symfony/symfony#37544]
In Symfony 5.1, why I need to always make migration when a migration file is already generated from different machine? When there is/are migration file(s), it freezes the migration.

I used this command for migration `php bin/console make:migration` .

**Comment by dmaicher** [comment]
Might be a duplicate of https://github.com/symfony/symfony/issues/37322 ?

**Comment by Tobion** [comment]
Looks like this should be reported in https://github.com/symfony/maker-bundle not symfony/symfony.
