### ISSUE TITLE
[Validator] getClassMetadata on null value

### ISSUE THREAD

**Issue by biozshock** [symfony/symfony#37554]
**Symfony version(s) affected**: 3.4.41

**Description**  
After merging https://github.com/symfony/validator/commit/b50cd17d3a154d096344ef22f54b8e3655cdf913 there is a possibility to have an exception (here https://github.com/symfony/validator/blob/b50cd17d3a154d096344ef22f54b8e3655cdf913/Validator/RecursiveContextualValidator.php#L317) when running down the code with null value as a result of `$value->getPropertyValue()`.
For me that caused that the form errors were not mapped back to form children fields.

**How to reproduce**
Create a validator with getter validation, pass an object with such a validation to the form.

**Comment by xabbuh** [comment]
Can you confirm that this will be fixed by #37447?

**Comment by biozshock** [comment]
Yes! Somehow overlooked it in commits list. Thank you!
