### ISSUE TITLE
HttpClient with private proxy doesn't work

### ISSUE THREAD

**Issue by louia** [symfony/symfony#37551]
**Symfony version(s) affected**: 4.4.10
**Description**  
Setting the proxy option with HttpClient Component with private proxy (username and password) doesn't work while with CurlHttpClient it works like a charm.

**How to reproduce**  

WORK : 
```php
        $client = new CurlHttpClient([
            'proxy' => 'http://username:password@ip:port/',
        ]);
        $response = $client->request(
            'GET',
            'http://google.com/'
        );
```

DOESNT WORK : 
```php
        $client = HttpClient::create([
            'proxy' => 'http://username:password@ip:port/',

        ]);
        $response = $client->request(
            'GET',
            'http://google.com/'
        );
```

**Possible Solution**  

??

**Additional context**  

In a Command behind a corporate proxy.

**Comment by fancyweb** [comment]
Is the client created by HttpClient::create an instance of CurlHttpClient?

**Comment by louia** [comment]
CurlHttpClient is import via
 `use Symfony\Component\HttpClient\CurlHttpClient;`

And HttpClient::create is create via 
`use Symfony\Component\HttpClient\HttpClient;`

**Comment by stof** [comment]
Yeah, but `HttpClient::create` actually returns either a `CurlHttpClient`, a `AmpHttpClient` or a `NativeHttpClient` depending on some conditions. The question being asked here is to check the type of the returned object to know which HttpClient implementation was used in your case.

**Comment by louia** [comment]
`HttpClient::create` use the default, `NativeHttpClient` according to the declaration of it : 

```php
    /**
     * @param array $defaultOptions     Default request's options
     * @param int   $maxHostConnections The maximum number of connections to a single host
     * @param int   $maxPendingPushes   The maximum number of pushed responses to accept in the queue
     *
     * @see HttpClientInterface::OPTIONS_DEFAULTS for available options
     */
    public static function create(array $defaultOptions = [], int $maxHostConnections = 6, int $maxPendingPushes = 50): HttpClientInterface
    {
        if (\extension_loaded('curl')) {
            if ('\\' !== \DIRECTORY_SEPARATOR || ini_get('curl.cainfo') || ini_get('openssl.cafile') || ini_get('openssl.capath')) {
                return new CurlHttpClient($defaultOptions, $maxHostConnections, $maxPendingPushes);
            }

            @trigger_error('Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient', E_USER_WARNING);
        }

        return new NativeHttpClient($defaultOptions, $maxHostConnections);
    }
```

So with the "DOESNT WORK :" section in my original post, the `HttpClient::create` is an instance of `NativeHttpClient `.

**Comment by nicolas-grekas** [comment]
Would you be able to provide us with a docker setup that reproduces the issue?
Without a reproducer, we might not be able to fix the issue.

**Comment by brentybh** [comment]
Just tested a private HTTP proxy with NativeHttpClient, it worked.

**Comment by xabbuh** [comment]
Let's close here for now. We can reopen anyway once we are able to reproduce.
