### ISSUE TITLE
Option order_by - ChoiceType

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#37553]
Hi,

It would be great to add the option `order_by` to `ChoiceType`

Thanks :)

**Comment by xabbuh** [comment]
Could you explain why would need that instead of providing already ordered choices?

**Comment by seb-jean** [comment]
I use choice_label to redefine the choice label.
Then I would like to sort it alphabetically.

**Comment by xabbuh** [comment]
In this case I think a proper solution still would be to transform choice labels first and then pass that with the `choices` option. As I don't think we are going to add this extra complexity to the component I am going to close here. Thank you for understanding.
