### ISSUE TITLE
Request argument resolver resolves missing argument

### ISSUE THREAD

**Issue by amigian74** [symfony/symfony#37574]
Symfony 5.1

**Description**  
I have to entities with an dependeny like this:

```
class Item
   /**
     * @var int
     *
     * @ORM\Column(name="id", type="bigint", nullable=false, options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

   /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="ItemShadow", mappedBy="item")
     */
    private $shadows;
};

class ItemShadow {
   /**
     * @var int
     *
     * @ORM\Column(name="shadow_id", type="bigint", nullable=false, options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $shadowId;

   /**
     * @var Item
     *
     * @ORM\ManyToOne(targetEntity="Item", inversedBy="shadows")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id", referencedColumnName="id")
     * })
     */
    private $item;
}
```

and a contoller function like this

```
   /**
     * @Route("/ws/item/{item}/{shadow}", name="ws_item", methods={"GET"}, defaults={ "item": null, "shadow": null })
     * @param Item|null $item
     * @param ItemShadow|null $shadow
     * @return Response
     */
    public function item(?Item $item = null, ?ItemShadow $shadow = null) {
    ....
    }
```

However the following request is served with both arguments (but shadow should be NULL):

localhost/ws/item/2

I'm not sure if this is a bug or I do something wrong here.

**Comment by xabbuh** [comment]
What do you mean with " is served with both arguments"? What is the actual value passed for the `$shadow` argument? And can you debug where that is resolved?

**Comment by amigian74** [comment]
Sorry for the inconvenience, but after some debugging I found the real problem. The DoctrineParamConverter converts the given null for shadow because of the existing association, unless there are many possible shadows for each item. The real bug in my opinion is the behaviour of the DoctrineParamConverter.

As a workaroud I'm created my own ParamConverter fpr ShadowItem-Entities

To answer the question anyway:

As seen in the URL the shadow parameter is missing and therfore NULL by default. But the shadow-Entity in the Controller function is not NULL as expected but any assiciated shadow entity.

**Comment by xabbuh** [comment]
Thank you for the feedback. I am closing here then.
