### ISSUE TITLE
[Twig, Form Types] Form text field placeholder can not be null. Why?

### ISSUE THREAD

**Issue by dawsza** [symfony/symfony#37573]
**Symfony version(s) affected**: 5.1.2

**Description**  
Form input placeholder can be empty string or false but can not be null. Why?
Another attributes like for example class can by null.

Error: Argument 1 passed to Symfony\Bridge\Twig\Extension\TranslationExtension::trans() must be of the type string, null given

**How to reproduce**  
```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, ['attr' => [
                'placeholder'   => null,
            ]])
        ;
    }
```

**Comment by xabbuh** [comment]
Can you explain why you would want to set the `placeholder` attribute to `null` instead of not setting it at all?

**Comment by dawsza** [comment]
Because placeholder comes from database and sometimes can be null value.
Of course I can casting null to string, but why it's works with false (boolean) or works with null for another attributess (class for example)?

**Comment by apfelbox** [comment]
@xabbuh I had the same issue some time ago.

If you have an optional placeholder, this one is way easier:

```php
$form
    // 10 Form Fields
    ->add("someField", null, [
        // ...
        "attr" => [
            "placeholder" => $data->getPlaceholder(),
        ],
    ])
    // 4 more form fields
```

instead of

```php
$someFieldAttributes = [
    // ...
];

if (null !== $data->getPlaceholder())
{
    $someFieldAttributes["attr"]["placeholder"] = $data->getPlaceholder();
}

$form
    // 10 Form Fields
    ->add("someField", null, $someFieldAttributes)
    // 4 more form fields
```

1. now the options for this one field are somewhere else of all the other, also
2. when making `$data->getPlaceholder()` nullable later on will lead to some dozen line changes in the form class.

**Comment by xabbuh** [comment]
Please have a look at #38595. Does it work for you?

**Comment by apfelbox** [comment]
Looks great, thanks @xabbuh ! 🎉
