### ISSUE TITLE
[Mailer] Allow to set Transport from MessageEvent

### ISSUE THREAD

**Issue by pableu** [symfony/symfony#37588]
**Description**  
I would love to be able to choose the Mailer Transport based on some attributes of the Message (e.g. depending on recipient or presence of attachments). 

I think this the nicest way from a developer perspective would to implement this using an Event Listener. 

**Attempted Solution**
```php
<?php
namespace App\EventSubscriber\Mailer;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Mailer\Event\MessageEvent;
use Symfony\Component\Mime\Email;

class MailTransportPicker implements EventSubscriberInterface
{

    public static function getSubscribedEvents(): array
    {
        return [MessageEvent::class => ['onMessage']];
    }

    public function onMessage(MessageEvent $event): void
    {
        $mail = $event->getMessage();
        if (
            $mail instanceof Email
            // && custom business logic to determine if we want to set the X-Transport header
        ) {
            $mail->getHeaders()->addTextHeader('X-Transport', 'local');
        }
    }
}
    

```

**Why it doesn't work**  
As far as I've gathered, this can't work because there are two locations where a `MessageEvent` is dispatched: 

1. [\Symfony\Component\Mailer\Mailer::send](https://github.com/symfony/symfony/blob/367aa1df6caa2c739a58165ead81e7fe50e6599e/src/Symfony/Component/Mailer/Mailer.php#L48)
Here, we dispatch a `MessageEvent` **before** passing the Email to Messenger. 

    The `\Symfony\Component\Mime\RawMessage` is **cloned** for the `MessageEvent`. Because it's only a clone, any changes we do to the `RawMessage` in an Event Listener are lost.

2. [\Symfony\Component\Mailer\Transport\AbstractTransport::send](https://github.com/symfony/symfony/blob/367aa1df6caa2c739a58165ead81e7fe50e6599e/src/Symfony/Component/Mailer/Transport/AbstractTransport.php#L62)
This code is executed when we're back from the Messenger. 

    We create a `MessageEvent` using the original instance of the `\Symfony\Component\Mime\RawMessage`. This means we can change it (which would be perfect to add the `X-Transport` header). 

    But there is one problem: We're already inside a Transport, so the `X-Transport` header is not considered anymore (because the transport has already been picked). 

**Solution**
I don't know. The above code shows what I would like to do :-)

What is the reason for **cloning** the `RawMessage` for the `MessageEvent` in `Mailer::send`? If we would pass the original instance there, I guess my Event Listener would work.

**Comment by emarref** [comment]
Correct me if I'm wrong or misunderstanding, but isn't the cloned message delivered? Which means that the event listener will be able to modify the cloned message?

```
$message = clone $message;
```

I think the reason for cloning the message is so that any reference to the message in the calling code will not be able to modify the message once it is sent. But event listeners should have access to the cloned message, which is eventually delivered to the bus.

**Comment by pableu** [comment]
Thanks for taking the time to look at my issue. I think you're on to something, but I beg to differ. 

1. The code in the Mailer is `$clonedMessage = clone $message;` (so the clone is assigned to a new variable and the original still exists).
2. The `$clonedMessage` goes into the MessageEvent which is given to the event dispatcher.
3. But it's the **original** `$message` that is passed to the MessageBus. So any modifications from the event listener are lost.

I think either doing `$message = clone $message;` (overwriting the original variable with the clone) **or** passing the `$clonedMessage` to the message bus would work.

What do you think? Worth a PR?

**Comment by emarref** [comment]
Sorry, I've been looking at 4.4 branch.

https://github.com/symfony/mailer/blob/4.4/Mailer.php

It seems the 5.x branch introduces your issue

https://github.com/symfony/mailer/commit/f62d7ebdc095f6a3e0922317d963765279be115c#diff-f3cbd3bd5920e440654a822116a6e7cc2407bd61f72415ade9b495e139b07672
https://github.com/symfony/mailer/commit/be41599ea773ccf5ee205d350b58123206349dfb#diff-f3cbd3bd5920e440654a822116a6e7cc2407bd61f72415ade9b495e139b07672

It may be an oversight. So you could attempt setting up a pull request to dispatch the cloned message instead of the original.

**Comment by OskarStark** [comment]
Couldn't this be achieved by using a dedicated "TransportPickerStamp" in your case which is taken into account when sending the mail?

**Comment by pableu** [comment]
@OskarStark yeah, good idea, but that would be larger commit. I think my proposed fix in #39123 would be just fine, and that's what the X-Transport-Header is for.

**Comment by walva** [comment]
I'm having the same issue as @pableu. I'm trying to guest which transport to used based on custom logic.
Unfortunately, if the X-Transport header is added in a listener, it won't alter the transporter. But if the header is added before the transporter, it will work.
![image](https://user-images.githubusercontent.com/3897363/140058091-92c68554-7dce-45f7-a50e-02f570e66d7a.png)

This is related to https://github.com/symfony/symfony/pull/39123

**Comment by pableu** [comment]
@walva I ended up just writing simple decorator for the `Mailer`. I just added my custom logic to pick the transport there. Not very pretty but very pragmatic.
