### ISSUE TITLE
phpunit bridge broken with composer v2

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/symfony#37601]
**Symfony version(s) affected**: 5.1.2 (for example)

**Description**  
https://github.com/symfony/phpunit-bridge/blob/v5.1.2/bin/simple-phpunit.php#L190 assumes that dev versions with have a count of exactly one version. This is not the case in general (stable versions might have no dev branch and only one tag), and in particular, in composer v2, 9.3.* has two dev versions printed, which means that line 191 is not executed when it was meant to be.

**How to reproduce**  
`PHPUNIT_VERSION=9.3`

**Comment by colinodell** [comment]
You can manually run the Composer command that `simple-phpunit` uses to see what's happening.

Using Composer 1:

```bash
$ composer info --no-ansi -a -n phpunit/phpunit "9.3.*" | grep versions
versions : 9.3.x-dev

$ composer info --no-ansi -a -n phpunit/phpunit "9.2.*" | grep versions
versions : 9.2.x-dev, 9.2.6, 9.2.5, 9.2.4, 9.2.3, 9.2.2, 9.2.1, 9.2.0
```

Using Composer 2:

```bash
$ composer info --no-ansi -a -n phpunit/phpunit "9.3.*" | grep versions
versions : dev-master, 9.3.x-dev

$ composer info --no-ansi -a -n phpunit/phpunit "9.2.*" | grep versions
versions : 9.2.x-dev, 9.2.6, 9.2.5, 9.2.4, 9.2.3, 9.2.2, 9.2.1, 9.2.0
```

Note that Composer 2 shows two dev versions for 9.3.

**Comment by GrahamCampbell** [comment]
I think we just need to filter out `dev-*` and `*-dev` names, and see if the count is zero, to determine if `-s dev` is needed.

**Comment by colinodell** [comment]
Good idea!  I've submitted https://github.com/symfony/symfony/pull/37607 with that fix.

**Comment by GrahamCampbell** [comment]
Excellent. 👍
