### ISSUE TITLE
{_locale} parameter in routing not working with Symfony >= 4.4.8

### ISSUE THREAD

**Issue by vincentjdc** [symfony/symfony#37602]
Hi,

I've a weird issue when using Symfony 4.4.8 or above.

A route defined with `{_locale}` parameter leads to a 404 route not found error.

I have the following routes defined

```php
/**
 * @Route("/sites/{id}",
 *    name="site_get",
 *    methods={"GET"},
 *    requirements={"id": "\d+"},
 * )
 *
 * @Route("/{_locale}/sites/{id}",
 *    name="site_get_with_locale",
 *    methods={"GET"},
 *    requirements={"id": "\d+", "_locale": "fr|en"},
 * )
 *
 */
```

### With Symfony 4.4.8

When calling `/en/sites/1` I get a 404 error "route not found".
The `debug:router` show the defined routes :
```
site_get.0                                      GET         ANY      ANY    /api/sites/{id}                                                 
site_get_with_locale.0                          GET         ANY      ANY    /api/{_locale}/sites/{id} 
```

But the profiler gives a different routing configuration : 
![image](https://user-images.githubusercontent.com/50613035/87775216-0798fa80-c826-11ea-8d0a-8a9aba373fa4.png)

### With Symfony 4.4.7

When calling `/en/sites/1` everything is fine, I get the desired resource
The `debug:router` show the defined routes :
```
site_get.0                                      GET         ANY      ANY    /api/sites/{id}                                                 
site_get_with_locale.0                          GET         ANY      ANY    /api/{_locale}/sites/{id} 
```

And the profiler routing section : 
![image](https://user-images.githubusercontent.com/50613035/87775350-3e6f1080-c826-11ea-8ade-1a30f9503561.png)

I also wrote a post on stackoverflow : 
https://stackoverflow.com/questions/62934810/symfony-4-setting-locale-parameter-in-route-definition-leads-to-no-route-f

**Comment by YaFou** [comment]
I think this issue comes from this change: #36500 (this is the only change on the router component between the release 4.4.7 and 4.4.8).

**Comment by fancyweb** [comment]
Status: works for me

I could not reproduce the issue. Can you provide a minimal project that reproduces it please? I think there is something else in play here because your route names end up suffixed with `.0`.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
