### ISSUE TITLE
[DX] KernelBrowser (default 'test.client' does not support 'json' as a key to parameters argument of request

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#37608]
**Description**  

The KernelBrowser and the symfony/httpclient, though having a very similar interface, behave differently on the `->request` method

When writing functional test, especially for json API,  writing 

```php
$client->request(
    'POST',
    '/submit',
    [],
    [],
    ['CONTENT_TYPE' => 'application/json'],
    '{"name":"Fabien"}'
);
```
is fastidious, especially as the symfony/http-client support the following syntax:

```php
$response = $client->request('POST', 'https://...', [
    'json' => ['name' => 'fabien'],
]);
```
that will automatically add the header and json encode (and avoid setting 2 empty parameters) 

as they are similar,  I was tempted to follow the same syntax, and as this guy (not me) on stackoverflow , i actually wasted quite some type to understand why on the other side I was getting an empty body:

https://stackoverflow.com/questions/57884508/how-to-do-json-request-on-webtestcase

So can KernelBrowser , support having a `json` parameter here, so that it behave like the symfony http client ?

**Comment by fabpot** [comment]
Closing for the same reason given in the related PR.
