### ISSUE TITLE
AWS SES API Signature V3 is deprecated

### ISSUE THREAD

**Issue by ddebin** [symfony/symfony#37610]
**Symfony version(s) affected**: 5.0.10

**Description**  
Class `SesApiTransport`, `SesHttpTransport` still use AWS SES API V3 signature.
Beginning October 1st, 2020, Amazon SES will only support requests signed using Signature Version 4. If you use an older version of the AWS Signature, you must adopt AWS Signature Version 4 prior to that date.

**How to reproduce**  
Send an email with SES API and look for header `X-Amzn-Authorization: AWS3-HTTPS [...]`, meaning you are using V3 signature. Plus you get a warning in SES API Console.

**Possible Solution**  
Implement V4 Signature or use AWS PHP SDK.

**Additional context**  
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html
https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by ddebin** [comment]
It seems it has been fixed in branch 5.1. https://symfony.com/blog/new-in-symfony-5-1-async-aws-support
But [documentation](https://symfony.com/doc/current/components/mailer.html) lacks a warning.

**Comment by fabpot** [comment]
@ddebin Can you create an issue on the docs instead? And perhaps propose a PR with a fix? Thank you.

**Comment by garak** [comment]
What about Symfony 4.4? It's still fully supported, and I think it should get a fix as well.

**Comment by jderusse** [comment]
see https://github.com/symfony/symfony/issues/36956#issuecomment-785678737
