### ISSUE TITLE
Console cyrillic input chars

### ISSUE THREAD

**Issue by inFureal** [symfony/symfony#37619]
**Symfony version(s) affected**: `symfony/console@5.1.2`

**Description**  
Cannot pass cyrillic chars to console input.

**How to reproduce**  
```php
$io = new SymfonyStyle($input, $output);
$name = $io->ask('Write name', 'Default');
var_dump($name);
```
**Output**
```
 Write name [Default]:
 > Имя

string(7) "Default"
```

**Comment by andreyserdjuk** [comment]
Could not represent. Need more info about env: OS, PHP version. If it's a dockerized app it would be good to have image data.

**Comment by inFureal** [comment]
- PHP 7.3.9
- Windows 10 Pro [build 18362.959]

**Comment by YaFou** [comment]
Please upgrade to version 5.1.3. See #37385.

**Comment by inFureal** [comment]
- Updated to 5.1.3
- Test was same as starting message
No, this doesn't fix this. It can read chars, but writes question marks instead valid input. 
---
Maybe it only my problem with my cmd/powershell, idk anyway

**Comment by YaFou** [comment]
> - Updated to 5.1.3
> - Test was same as starting message
> No, this doesn't fix this. It can read chars, but writes question marks instead valid input. 
> ---
> Maybe it only my problem with my cmd/powershell, idk anyway

I don't really understand what do you mean by writing the question marks instead the input: the question marks is written and when you type these characters, the default input is printed? Maybe the CMD does not supports these specific characters.

---
Can you try this example in a simple PHP script?
```php
<?php

echo 'Type here: ';
$input = readline();
echo $input;
```

**Comment by inFureal** [comment]
```
Type here: Привет
Привет
```

Yeap, as expected, got me same input

**Comment by inFureal** [comment]
> writing the question marks
Nope, output writes questions marks

**Comment by YaFou** [comment]
> ```
> Type here: Привет
> Привет
> ```
> 
> Yeap, as expected, got me same input

So, it's not your terminal that throw this issue apparently. However you should investigate about the encoding with `sapi_windows_cp_set`. Apparently, my fix did not cover all cases.

**Comment by YaFou** [comment]
Hi @inFureal!

I've done some tests on my local machine but I did not find any solution for your issue 😔 However, there is some code page which works: 855 and 866 that you can define with the function `sapi_windows_cp_set` (see [here](https://ss64.com/nt/chcp.html) & this function only works on Windows). However, with this code page, it will break other characters like `é` or `â`.

**Comment by inFureal** [comment]
@YaFou 
It seems that my PowerShell is broken... I had to fix that and if 'bug' isn't disapere - I'll open new issue with more derails.
(Sorry for my englandsky 😄)
