### ISSUE TITLE
[Messenger] BC break in SF 5.0 for stamps due to changes stamp classes

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#37616]
**Symfony version(s) affected**: >=5.0

**Description**  
Moving the transports to separate packages in #35422 broke BC for the stamps.

**How to reproduce**  
Using the deprecated classes to fetch stamps does not work anymore since the stamps are now added to the envelope using the new classes. So this code `$envelope->last(\Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp::class);` does not find the stamp anymore.

**Possible Solution**  
Duplicate the stamps in the evelope with the new class and deprecated classes. Or add some logic in the retrieving methods to know about new and old class names.

**Comment by ogizanagi** [comment]
#37826 should do it
