### ISSUE TITLE
Easyadmin upgrade error

### ISSUE THREAD

**Issue by frenci8** [symfony/symfony#37617]
**Symfony version(s) affected**: 5.1.2

**Description**  
`Argument 1 passed to Symfony\Component\String\u() must be of the type string, array given, called in /Users/myusername/website.com/vendor/easycorp/easyadmin-bundle/src/Cache/CacheWarmer.php on line 38 `

**How to reproduce**  
Follow the easyadmin upgrade instructions from 2 to 3. I get this error everytime after I write `php bin/console make:admin:migration` in the terminal. If i ignore that error and proceed with the rest of the instructions from https://symfony.com/doc/master/bundles/EasyAdminBundle/upgrade.html , I end up with this error when I try to open the project  `Warning: require(/Users/myname/website.com/var/cache/dev/easyadmin/routes-dashboard.php): failed to open stream: No such file or directory.` 

Any has any ideas?

Thank you

**Comment by fabpot** [comment]
You should report the error on the easyadmin repository instead. Thank you.
