### ISSUE TITLE
[Cache] Doctrine migration exception due to PDO cache adapter

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#37623]
**Symfony version(s) affected**: v5.1.0-BETA1 and up

**Description**  
Getting an exception when trying to diff my database schema:

`Attempted to call an undefined method named "configureSchema" of class "Symfony\Component\Cache\Adapter\TraceableAdapter". `

```
Exception trace:
  at C:\wamp64\www\printhub\vendor\symfony\doctrine-bridge\SchemaListener\PdoCacheAdapterDoctrineSchemaSubscriber.php:40
```

**How to reproduce**  
- Configure a cache pool with a PDO adapter
- run doctrine:migrations:diff

**Possible Solution**  

Expose the inner adapter of `TraceableAdapter` with a `getPool` method and do an instance check?

**Additional context**  
Suspect change: https://github.com/symfony/symfony/commit/2dd9c3c3c8901b8e470cfa4723d32e53a37ecadf

Dumping the injected adapters here https://github.com/symfony/symfony/blob/2dd9c3c3c8901b8e470cfa4723d32e53a37ecadf/src/Symfony/Bridge/Doctrine/SchemaListener/PdoCacheAdapterDoctrineSchemaSubscriber.php#L33 results in

![Screenshot_2020-07-21 Screenshot](https://user-images.githubusercontent.com/776488/88006059-183dbf00-cb0b-11ea-9c2b-ed8ea29b329f.png)

Cache adapters get replaced here: https://github.com/symfony/symfony/blob/8a7c776b92c92ef6867fdd6a1682171c17f76de1/src/Symfony/Component/Cache/DependencyInjection/CacheCollectorPass.php#L77

Temporary fix - downgrade:
`"symfony/doctrine-bridge": "5.0.10",`

**Comment by ghazale-javaheri** [comment]
i have same issue

**Comment by Padam87** [comment]
@ghazale-javaheri For me `extra.symfony.require` version in composer.json was set to 5.1, and that blocked the downgrade.

**Comment by nicolas-grekas** [comment]
I think the issue can be solved by registering `CacheSchemaSubscriberPass` as `PassConfig::TYPE_BEFORE_REMOVING`.

This is for the https://github.com/doctrine/doctrinebundle repository. Please submit a PR there.
