### ISSUE TITLE
[Messenger] running php bin/console make:migration with auto_setup: true

### ISSUE THREAD

**Issue by tommym9** [symfony/symfony#37626]
**Symfony version(s) affected**: 5.0.8

**Description**  
I installed the messenger component and setup the default transport to be doctrine. I left the `auto_setup` config to true and the messenger_messages table was created and thats all working fine.

The issue I've got is when I next ran `php bin/console make:migration` as I'd added a new Entity, the migration dropped the messenger_messages table:

```
public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
     
       // Redacted queries to add my entity here

        $this->addSql('DROP TABLE messenger_messages');
    }
```

**How to reproduce**  
- Install messenger `composer require symfony/messenger`
- Set `doctrine://default` as the messenger transport
- Push a message to the queue
- See that the table messenger_messages is created
- Add an entity via the cli
- Run `php bin/console make:migration`
- See that the latest migration has a drop statement for the messenger_messages table

**Possible Solution**  
If auto_setup is true then exclude the messenger_messages from any future migrations.

**Comment by noniagriconomie** [comment]
You can skip migration on those tables via
https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables

**Comment by xabbuh** [comment]
closing here as this doesn't look like a bug, but that you need to configure DoctrineMigrationsBundle as described in https://github.com/symfony/symfony/issues/37626#issuecomment-662127133

**Comment by tommym9** [comment]
Hi @noniagriconomie thanks for the heads up on that one. Worth adding to the documentation for Messenger?

**Comment by noniagriconomie** [comment]
@tommym9

> Worth adding to the documentation for Messenger?

it is wierd that i saw it in https://symfony.com/doc/4.4/messenger.html#doctrine-transport

but not at https://symfony.com/doc/current/messenger.html#doctrine-transport

maybe create an issue on the symfony-docs repo to see if it was removed on purposes or by mistake etc

cheers !
