### ISSUE TITLE
Symfony installable cli application (Windows) adds extra characters around commands & titles

### ISSUE THREAD

**Issue by rkeet** [symfony/symfony#37632]
**Symfony version(s) affected**: Symfony CLI version v4.18.0 (c) 2017-2020 Symfony SAS

**Description**  
In Git Bash (https://git-scm.com/) running `symfony` command will show commands & titles like so: 

```
←[33mManage a project on Cloud←[39m

  ←[32mlogin←[39m        Log in with your SymfonyConnect account
  ←[32minit←[39m         Initialize a new project using templates
```

Running it in Command Prompt shows correctly.

**How to reproduce**  
On Windows download and install Symfony (https://symfony.com/download using the "Download setup.exe" button). 

Restart any Bash Terminals and Command Prompt sessions. 

Run `symfony` command

**Additional context**  
![image](https://user-images.githubusercontent.com/3327864/88147291-47ccf400-cbfd-11ea-9f3b-46394003b23e.png)

**Comment by YaFou** [comment]
This issue is not related to the Symfony code. Please open an issue in [symfony/cli](https://github.com/symfony/cli).

**Comment by rkeet** [comment]
Copied to: https://github.com/symfony/cli/issues/312

This one may be closed.
