### ISSUE TITLE
[PhpUnitBridge] CoverageListenerTrait is incompatible with PHPUnit 8.5

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#37637]
**Symfony version(s) affected**: 3.4

**Description**  

When running the testsuite of PhpUnitBridge with PHPUnit 8.5, it fails with the following exception:

```
ReflectionException: Property PHPUnit\Util\Test::$annotationCache does not exist in /path/to/symfony/src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:73
```

**How to reproduce**  

Run the test suite of Symfony's 3.4 branch with PHPUnit 8.5.

**Additional context**  

Apparently, PhpUnitBridge tries to fiddle with a private property `PHPUnit\Util\Test::$annotationCache`.

https://github.com/symfony/symfony/blob/a397c490b018095a6a4bee3b107c80d109293976/src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php#L73

That property has been removed in PHPUnit 8.4 and replaced by a new class `PHPUnit\Util\Annotation\Registry`.

**Comment by nicolas-grekas** [comment]
@derrabus up for having a look?

**Comment by derrabus** [comment]
I won't find time this week, I'm afraid.

I've already hat a look back then (https://github.com/symfony/symfony/pull/37566#issuecomment-658944504). I think, @lyrixx was the original author of that listener. Maybe he has an idea how to fix this.

**Comment by sanmai** [comment]
FWIW this was introduced here: https://github.com/sebastianbergmann/phpunit/commit/f57e88b86e486706414a3a6f351182acaa59f4b7

**Comment by sanmai** [comment]
@nicolas-grekas Can we get these fixes somehow released before schedule? 

These are no BC breaks, but they really holding us up from testing projects with PHP 8.

**Comment by derrabus** [comment]
> These are no BC breaks, but they really holding us up from testing projects with PHP 8.

Why aren't you testing against dev snapshots of the packages that are blocking you?

**Comment by sanmai** [comment]
Well, I meant _broad_ testing. I do run internal tests against snapshots, else I wouldn't have come up with a fix for this issue, just for an example. But that's not _broad_ testing, this is developer only testing.

**Comment by derrabus** [comment]
I understand, but php 8 is still a moving target. We're constantly patching incompatibilities. Creating new releases everytime we do a php 8 fix would generate a lot of unnecessary noise. And a php-8-compatible release could be incompatible the day after the release already.

Then again, a snapshot of the 3.4, 4.4 and 5.1 branches should always be stable enough for a rollout, even to production.

**Comment by sanmai** [comment]
Well, sorry about the confusion but I'm more concerned not about PHP 8 but about PHPUnit 9.3+.
