### ISSUE TITLE
lint:container expression as factory class

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#37661]
**Symfony version(s) affected**: 5.1.2

**Description**  
The `lint:container` command fails in a peculiar case

**How to reproduce**  

Add the following definition to the container builder (in our case this is done in a compiler pass):

```php
$definition = new Definition('Acme\ORMFooRepository', ['Acme\Foo']);
        $definition->setFactory([
            new Expression(sprintf(
                'service("doctrine").getManagerForClass("%s")',
                addslashes('Acme\Foo')
            )),
            'getRepository',
        ]);
```

This will result in:

```
$ bin/console lint:container
In AbstractRecursivePass.php line 182:

  [Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Invalid service "Acme\FooService": class "service("doctrine").getManagerForClass("Acme\\Foo")" does not exist.
```

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
@fancyweb would you be up to have a look?

**Comment by fancyweb** [comment]
@nicolas-grekas From what I found in the code, we don't support expressions as factory classes intentionally. Firstly, when we dump the debug XML container we don't indicate that the factory class is an expression, so it cannot be converted back when loaded. Secondly, we don't handle the case where the factory class is an expression (to evaluate it) in AbstractRecursivePass. The only problem is that it currently works perfectly well in the PhpDumper 😁 Should we try to support it everywhere or close as "wontfix"?

**Comment by nicolas-grekas** [comment]
@fancyweb thanks for investigating. I'm for closing then!

@theofidry you can replace this expression by a proper service definition, using inline Definition objects. I'd recommend doing so instead of using EL here.

Closing as explained.

**Comment by theofidry** [comment]
@nicolas-grekas I'd be happy to use something cleaner, but I don't really understand the how tbh

**Comment by nicolas-grekas** [comment]
@theofidry in your example above, this would be:
```php
$managerFactory = (new Definition(RepositoryManager::class))
	->setFactory([new Reference('doctrine'), 'getManagerForClass'])
	->addArgument('Acme\Foo');

$definition = new Definition('Acme\ORMFooRepository', ['Acme\Foo']);
        $definition->setFactory([$managerFactory, 'getRepository']);
```

**Comment by theofidry** [comment]
👌
