### ISSUE TITLE
Remember me functionality is broken

### ISSUE THREAD

**Issue by PF4Public** [symfony/symfony#37672]
**Symfony version(s) affected**: 5.1.2

**Description**  
After upgrading to Symfony 5.1.2 Remember me functionality got broken. It always replies with "This token was already used. The account is possibly compromised." 

Turns out after successful login, remember me token got saved incorrectly. The `onLoginSuccess` function got called and every parameter was correct in this part:
https://github.com/symfony/symfony/blob/0ab5eeddf97d0a277c5ad956a51365aba93b27b9/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php#L107-L115

Upon persisting `$this->generateHash($tokenValue),` to a database (Postgresql) however, this value was padded by spaces up till its supposed size in database: 88 characters. Later, upon comparing these values:
https://github.com/symfony/symfony/blob/0ab5eeddf97d0a277c5ad956a51365aba93b27b9/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php#L139-L141
`hash_equals` decides, that they are not.

**Possible Solution**  
* Identify, why was this value persisted with extra spaces. I could track this issue up to doctrine-bridge.
* Remove extra spaces received from database. (If `rtrim ($persistentToken->getTokenValue())` is a suitable fix, let me know, I'll do a PR)

**Comment by chalasr** [comment]
Changing the `value` column's datatype from `char` to `varchar` should fix the problem.

**Comment by PF4Public** [comment]
@chalasr Thank you for your suggestion. That actually worked. This probably needs to be addressed [in docs](https://symfony.com/doc/current/security/remember_me.html) then, I suppose.

Should I do a PR and replace `char` to `varchar` there?

**Comment by chalasr** [comment]
@PF4Public That would be great. The PR should be submitted against the 3.4 branch.

**Comment by chalasr** [comment]
I'm closing here as a doc PR has been submitted, see symfony/symfony-docs#14034.
Thank you @PF4Public.
