### ISSUE TITLE
bin/phpunit with possibility to save deprecations

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#37679]
**Description**  
I would like to be able to see a short output of deprecations and be able to write the details in a file.

To see the test results in more details, I can use the arguments `--log-teamcity` or `--log-junit`. I miss a similar functionality for deprecations. I suggest that the generated file contains the same as the full deprecation message (see example).

The option could be enabled by an argument or by an environment variable.

**Example**  
```console
$ bin/phpunit --log-deprecations deprecations.txt # or SYMFONY_DEPRECATIONS_LOG=deprecations.txt bin/phpunit 
...
Tests: 778, Assertions: 898, ...

Remaining direct deprecation notices (11)

Remaining indirect deprecation notices (77)

Other deprecation notices (93)

$ head deprecations.txt

Remaining direct deprecation notices (11)

  3173x: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.
...
```

**Comment by nicolas-grekas** [comment]
Up for a PR? The target output file should be set with a new option in `SYMFONY_DEPRECATIONS_HELPER`

**Comment by michaelKaefer** [comment]
I will try this.
