### ISSUE TITLE
[VarDumper] VarDumper started adding empty `<note></note>` formatting before arrays in v5.1.3

### ISSUE THREAD

**Issue by bobthecow** [symfony/symfony#37674]
**Symfony version(s) affected**: 5.1.3

**Description**  
VarDumper started adding empty `<note></note>` formatting tags before arrays in v5.1.3, which seems unnecessary :)

**How to reproduce**  
https://travis-ci.org/github/bobthecow/psysh/jobs/712002303

**Comment by stof** [comment]
I suspect that this is caused by the change in https://github.com/symfony/symfony/pull/36230

**Comment by stof** [comment]
I don't know why the tag name is `class` though. This looks weird to me.

**Comment by bobthecow** [comment]
the `class` tag is coming [from psysh's Presenter](https://github.com/bobthecow/psysh/blob/master/src/VarDumper/Presenter.php#L39). the actual tag name is `note`.

**Comment by stof** [comment]
OK, then this is definitely the PR I identified.

**Comment by l-vo** [comment]
I'm going to look at that.

**Comment by nicolas-grekas** [comment]
A simple fox could be for the HtmlDumper to not dump empty tags.

**Comment by stof** [comment]
I don't think psysh uses the HTML formatter (I think this is the coloration notation of `symfony/console` instead)

**Comment by bobthecow** [comment]
Thanks!
