### ISSUE TITLE
EventDispatcher is injected at the very last time in FrameworkBundle/Console/Application, maybe at wrong place ?

### ISSUE THREAD

**Issue by matks** [symfony/symfony#37680]
**Symfony version(s) affected**: since (at least) 3.4 and still valid (5.1.3)

**Description**  

This is a minor issue but I report it nonetheless. Maybe it's worth it after all.

Today I needed to inject my own instance of EventDispatcher into [Symfony\Bundle\FrameworkBundle\Console\Application](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Application.php).

I spent quite a lot of time struggling to understand why my code was not working, until I finally understood that the `dispatcher` instance in this class is being overriden when `doRun()` is called:

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L80

```
public function doRun(InputInterface $input, OutputInterface $output)
    {
        $this->registerCommands();

        if ($this->registrationErrors) {
            $this->renderRegistrationErrors($input, $output);
        }

        $this->setDispatcher($this->kernel->getContainer()->get('event_dispatcher'));

        return parent::doRun($input, $output);
    }
```

**So even if you either inject manually or using DI another event dispatcher before, at runtime, when `doRun()` is triggered, your `dispatcher` instance is replaced by the one from the framework.**

### Design issue ?

There is no faulty behavior about that, however it feels a bit weird (wrong ?) to do this at this moment. I was expecting, just like so many other classes/services into Symfony, this kind of dependency injection and assignment to happen in `__construct()` or in earlier phases of this class.

In a web context, it could be similar to a Controller overriding the `Twig` dependency when being called, wiping out any previously injected Twig instance.

That would seem weird, right ? And it also prevents people to override this dependency. It's a hard-coded dependency which limits extension capabilities.

**Possible Solutions**  

Multiple solutions could be applied. Please tell me if one is relevant/eligible, I will be happy to submit a PR.

1. Fix the design issue : assign `dispatcher` earlier in the class lifecycle. However this might not be possible to do it in `__construct()` because it requires a booted container which might not be available at this moment.

2. As I think this is code was designed intentionally like this, when assigning `dispatcher` in `doRun()`, if `dispatcher` was not null before, log an error for developers to be notified of this possible issue (so the replacement is not fully silent which would help debugging this situation)

This would not fix the design issue but it would help developers struggling just like me to understand quicker what is wrong. The help is provided by the error messaged.

3. Override `setDispatcher()` in this class to throw an exception in order to make sure developers calling it would be notified this will have no effect.

This would not fix the design issue but it would help developers struggling just like me to understand quicker what is wrong. The help is provided by the exception throwing.

**Comment by stof** [comment]
The `Application` is instantiated in the `bin/console` file. It is not managed by the DI container. As such, it is more similar to the kernel than to controllers (commands would be the equivalent of controllers btw).

**Comment by matks** [comment]
> The `Application` is instantiated in the `bin/console` file. It is not managed by the DI container. As such, it is more similar to the kernel than to controllers (commands would be the equivalent of controllers btw).

I understand.

After sleeping on it, I finally succeeded into putting words on that "it feels weird" idea.

If I am not wrong, the fact this assignment of the dispatcher is performed in `doRun()` is a violation of a the Single Responsibility principle of SOLID. This is why I never expected to find this in there. `doRun()` responsibility is, according to its name, to perform the targeted action, not to initialize/configure dependencies.

This is why I think the assignment of `$dispatcher` should happen somewhere else.

**Comment by stof** [comment]
IIRC, the kernel is not yet booted earlier than that.

**Comment by nicolas-grekas** [comment]
Closing as @stof explained.
