### ISSUE TITLE
When @IsGranted is provided with an array of roles, access is always denied

### ISSUE THREAD

**Issue by ldesgrange** [symfony/symfony#37685]
**Symfony version(s) affected**: 5.1.3 

**Description**  
What I understand from [@IsGranted documentation](https://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/security.html#isgranted) is that providing an array of roles should grant access to any user having any of those roles, but access is denied for all users including users having all roles.

**How to reproduce**  
Create a controller with something like:
```php
    /**
     * @Route("/some-page")
     * @IsGranted({"ROLE_ADMIN", "ROLE_OPS"})
     */
    public function somePage()
    {
        // …
    }
```
Then try to go to `/some-page` with a user having `ROLE_ADMIN` or `ROLE_OPS` or both roles. Access is always denied.

**Possible Solution**  
It seems that in this case [RoleVoter](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/Voter/RoleVoter.php) is receiving an array of array of roles in `$attributes` instead of an array of roles, so the voter will never match anything.

Shouldn't [AuthorizationChecker](https://github.com/symfony/symfony/blob/0ab5eeddf97d0a277c5ad956a51365aba93b27b9/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php#L62) check if `$attribute` is already an array and enclosing it into an array only if it's not?

**Comment by jvasseur** [comment]
The ability to treat an array of roles specially in `is_granted` has been removed in Symfony 5 so it's normal that the role voter receive an array of array of roles.

You can see the reasoning of why we did that in https://github.com/symfony/symfony/pull/33584.

The problem here is in the documentation, could you open an issue in the doc repo so that it is fixed ?

**Comment by ldesgrange** [comment]
Thank you for the information, I created a pull request to fix the documentation.
