### ISSUE TITLE
Add debugging shortcut commands

### ISSUE THREAD

**Issue by larzuk91** [symfony/symfony#37689]
**Description**  
Would be nice to add a couple of shortcut commands for:
`debug:container —env-vars` -> `debug:env-vars`
`debug:container —parameters` -> `debug:parameters`

I was talking to @weaverryan and we came to the conclusion that is very easy to forget what options you can pass into the `debug:container` (Especially to newcomers).

Do you think those shortcuts would be useful too?

**Comment by ro0NL** [comment]
if we do separate commands, i'd prefer to keep it in the container namespace, thus `debug:container:env-vars` (`d:c:e` as a shortcut out-of-the-box).

raises the question if the command should be an alias, or just move the --env-vars part to it's own command.

**Comment by larzuk91** [comment]
I like better `debug:env-vars` because it reads nice and it's shorter but I think yours makes more sense from a technical point of view.

**Comment by fabpot** [comment]
I'm against that change. We already have many commands in Symfony, so let's use everything we have to make things easier (namespaces, args, options, ...).
