### ISSUE TITLE
Deprecation not showing in profiler in 4.4, gives an error after upgrading to Symfony 5.1

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#37698]
**Symfony version(s) affected**: 4.4.11

**Description**  
Symfony is not reporting the deprecation which has been added in #28723, in the profiler. As a result, as soon as I upgraded some internal server errors popped up.

**How to reproduce**  
I have created a very simple repository to reproduce the issue: https://github.com/tjveldhuizen/symfony-missing-deprecation-reproducer. When running this with 'symfony serve', at https://localhost:8000/ a very simple form is shown and the profiler is not showing any deprecations.
After replacing all "4.4" with "5.1" in composer.json and running `composer upgrade`, it shows a LogicException `Cannot use the "format" option of "Symfony\Component\Form\Extension\Core\Type\DateTimeType" when the "html5" option is enabled.`

**Comment by fancyweb** [comment]
Status: reviewed

Thanks for providing a reproducer.
