### ISSUE TITLE
Allow listed deprecations to be skipped

### ISSUE THREAD

**Issue by alexpott** [symfony/symfony#37715]
**Description**  
Drupal is using Symfony's PHPUnit bridge to detect usages of deprecated code during tests. This has proved amazing useful in managing our technical debt and has helped us prepare for Symfony 4 and 5. One problem we've faced because of Drupal's size is that it is not always possible to address new deprecations at the same time as upgrading a dependency. In order to handle this we've added the ability to skip specific deprecations which we can then handle in a separate issue.

When skipping a deprecation we can either match the entire message or use a regex for a dynamic deprecation message.

**Example**  
For example, Drupal 9 is using Symfony 4 and we're skipping the `The "Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser" class is deprecated since Symfony 4.3, use "Symfony\Component\Mime\MimeTypes" instead.` deprecation notice and handling the changes we need to make to Drupal in https://www.drupal.org/project/drupal/issues/3055193

**Comment by nicolas-grekas** [comment]
What about allowing one to snapshot the current deprecations and use that as a base for next runs? This could be implemented via some option to the SYMFONY_DEPRECATIONS_HELPER

**Comment by alexpott** [comment]
@nicolas-grekas that does seem an interesting functionality - we could build on top of this to do that.

**Comment by stof** [comment]
yeah, having a baseline file (the name is taken from the phpstan feature) seems interesting.

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/issues/34496 :blush: I also thought about that a while back and found it useful
