### ISSUE TITLE
[Lock] downgrade log.info to log.debug

### ISSUE THREAD

**Issue by rvitaliy** [symfony/symfony#37710]
**Description**  
the Lock class log to info level, but it's not a useful information to store in my production logs.
see:
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L81
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L138

I think that this type of log should be downgraded to debug instead of info
Currently i configure this class with NullLogger but it's not ideal because i can lost usefull logs like:
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L141

**Comment by stof** [comment]
I agree that these looks like debug log messages.

**Comment by fabpot** [comment]
@rvitaliy Do you want to submit a PR?

**Comment by rvitaliy** [comment]
@fabpot from which branch can i start to develop this fix?

**Comment by fabpot** [comment]
You should start from the master branch.
