### ISSUE TITLE
[HttpFoundation] inconsistent argument annotation for method set()

### ISSUE THREAD

**Issue by dFayet** [symfony/symfony#37717]
**Symfony version(s) affected**: 5.1.*

**Description**  
The annotation of the argument `$value` for the method `set` in `Http-foundation/InputBag` limits its value to be `string|array|null` but the function only checks if `$value` is `null|array|scalar`.
Doing  `$request->query->set('myArgument', 1.2)` will work fine.
See https://github.com/symfony/http-foundation/blob/master/InputBag.php#L72-L84

Before creating a wild PR changing the docblock, I just wanted to be sure about the right behaviour.
Are only `string|array|null` supported or are the other scalar type allowed?

Have a good day.

**Comment by nicolas-grekas** [comment]
I think everything is correct here, passing `1.2` is OK (when not using strictmode) even if only `string` is allowed.
Closing therefor.

**Comment by greg0ire** [comment]
@nicolas-grekas are you talking about the first argument? This is about the second one.

**Comment by nicolas-grekas** [comment]
About the 2nd one yes.

**Comment by greg0ire** [comment]
I don't quite get your remark about the strict mode then: there is no type declaration on the second argument. The inconsistency my colleague is pointing at is between the `string` phpdoc for the second argument, and the call to `is_scalar()`. Shouldn't either the phpdoc be widened and the deprecation message changed, or maybe that `is_scalar()` changed to `is_string()`? Passing a float is deprecated according to the deprecation message.

**Comment by nicolas-grekas** [comment]
My reasoning is the following:
if you call this method with a float, the day we will add the explicit type-hint (in SF6), PHP will cast the float to a string transparently. That's why there is no deprecation currently in this situation.
Of course, if you use strict mode, you will get an error. But the BC promise doesn't cover strict mode - it would be just impossible to change anything if it were.

**Comment by greg0ire** [comment]
Thanks, I get it now, and good to know about the BC promise :slightly_smiling_face:

**Comment by greg0ire** [comment]
Sorry to dig this up again, but I think there is are 2 other BC-breaks though, if you don't use strict mode but still expect a float:

```php
Assert::isFloat($bag->get('non-existent-param', 4.2));
```

If in Symfony 7 or 8 we require php 8, we will be able to also add a type declaration to `set`'s  second argument as we will have union types (so `string|array|null`), and there will another BC-break here too.

```php
$bag->set('my-param', 4.2);
Assert::isFloat($bag->get('my-param'));
```

Why not also warn the user in these cases?
