### ISSUE TITLE
[Validator] Unique constraint value comparison

### ISSUE THREAD

**Issue by artyuum** [symfony/symfony#37721]
## Description

Right now, the Unique constraint sees the following values as different:
- Sun
- sun

This is correct, but what if an user needs to **ensure** that a value has not been passed more than once (no matter if it's in lowercase/uppercase)?

## Example
My suggestion would be to add an option like:
```
@Assert\Unique(caseInsensitive=true)
```
The Unique constraint will then see both values ("Sun" & "sun") as the same and will add a violation.

To make this change, I would edit both files as follow:

**[UniqueValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/UniqueValidator.php)** 

**Before**
```php
foreach ($value as $element) {
    ...
}
```

**After**
```php
if ($constraint->caseInsensitive) {
    $value = array_map('strtolower', $value); // or maybe use mb_strtolower()?
}

foreach ($value as $element) {
    ...
}
```

**[Unique](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/Unique.php)** 

**Before**
```php
class Unique extends Constraint
{
    public const IS_NOT_UNIQUE = '7911c98d-b845-4da0-94b7-a8dac36bc55a';

    ...
}
```

**After**
```php
class Unique extends Constraint
{
    public const IS_NOT_UNIQUE = '7911c98d-b845-4da0-94b7-a8dac36bc55a';

    public $caseInsensitive = false;

    ...
}
```

EDIT: Improved readability

**Comment by xabbuh** [comment]
#37507 looks like a suggestion that would solve this issue too

**Comment by xabbuh** [comment]
Let's close in favour of #37507. Having one issue to keep track of this feature request is enough.
