### ISSUE TITLE
Event Subscriber and Logout Event

### ISSUE THREAD

**Issue by ndantonio** [symfony/symfony#37727]
Hi, I'm new in Symfony. I would like to know how to implement an automatic logout once user session expires using an event subscriber and the new logout event? Thank you.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by ndantonio** [comment]
No problem. Thanks @xabbuh !
