### ISSUE TITLE
Incorrect generated URL when Symfony app is exposed behind a gateway

### ISSUE THREAD

**Issue by maximeag** [symfony/symfony#37720]
**Symfony version(s) affected**: 5.1

**Description**

I'm deploying a Symfony application in a container exposed behind my company's gateway but encountering an issue when generating absolute paths.

![symfony-with-gateway](https://user-images.githubusercontent.com/3855368/89068480-9010b280-d371-11ea-836e-aa0fb4767dc7.png)

As you can see, the gateway transforms the URL to redirect the request to my Symfony app. But then the generated absolute paths using Twig function `path()` do not contain the base path : `gateway/my-symfony-app`.

|||
|-|-|
|**Developed**|`<a href="path('my_route')">json</a>`|
|**Generated**|`<a href="/my-route">json</a>`|
|**Expected**|`<a href="/gateway/my-symfony-app/my-route">json</a>`|

I managed to generate the assets urls by setting a `base_path` :
```yaml
#config/packages/framework.yaml
framework:
    assets:
        base_path: 'gateway/my-symfony-app'
```

but didn't find any solution when using third party bundles like in this API Platform template : https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig#L74

**Possible Solution**  

I found out that it's possible to set a router's default URL but not in a Web Context : [New in Symfony 5.1: Simpler Request Context (Symfony Blog)](https://symfony.com/blog/new-in-symfony-5-1-simpler-request-context)

Is there a way to use it in my case ?

Thank you for your help!

**Comment by GromNaN** [comment]
Do you get the original path in any header that the proxy would fill ?

**Comment by khaledalam** [comment]
@maximeag try to check if routes are ok in console or not, run: `php bin/console debug:router`

**Comment by maximeag** [comment]
> Do you get the original path in any header that the proxy would fill ?

@GromNaN Yes the gateway forwards some headers that could help me to guess the initial path. Do you know if I can use them to correctly generate the URLs ? 

> @maximeag try to check if routes are ok in console or not, run: `php bin/console debug:router`

@khaledalam  Here is what I got :
```
application@60dbg7849zb7:/app$ php bin/console debug:router
 -------------------------- -------- -------- ------ ------------------------------------- 
  Name                       Method   Scheme   Host   Path                                 
 -------------------------- -------- -------- ------ ------------------------------------- 
  _preview_error             ANY      ANY      ANY    /_error/{code}.{_format}             
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                        
  _profiler_home             ANY      ANY      ANY    /_profiler/                          
  _profiler_search           ANY      ANY      ANY    /_profiler/search                    
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar                
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                   
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results    
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                      
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                   
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router            
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception         
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css     
  api_entrypoint             ANY      ANY      ANY    /api/{index}.{_format}               
  api_doc                    ANY      ANY      ANY    /api/docs.{_format}                  
  api_jsonld_context         ANY      ANY      ANY    /api/contexts/{shortName}.{_format}  
 -------------------------- -------- -------- ------ ------------------------------------- 
```

**Comment by khaledalam** [comment]
Try [this](https://api-platform.com/docs/core/operations/#prefixing-all-routes-of-all-operations)

**Comment by maximeag** [comment]
@khaledalam I already tried something this :
```yaml
# config/routes/api_platform.yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /gateway/my-symfony-app/api
```
But didn't solve the issue because now routes are exposed here :
`https://my.company/gateway/my-symfony-app/gateway/my-symfony-app/api`

**Comment by maximeag** [comment]
I dug in Symfony source code and it seems that the base path is supported by an instance of RequestContext.
Is there a way to alter this RequestContext ?

**Comment by maximeag** [comment]
I managed to alter RequestContext with an Event Subscriber :

```php
<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Routing\RouterInterface;

class RequestSubscriber implements EventSubscriberInterface
{
    private $router;

    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    public function onKernelRequest(RequestEvent $event)
    {
        $this->router->getContext()->setBaseUrl(
            "/gateway/my-symfony-app",
        );
    }

    public static function getSubscribedEvents()
    {
        return [
            'kernel.request' => 'onKernelRequest',
        ];
    }
}
```

Could someone tell me if it's a good way to do it ?

**Comment by stof** [comment]
#36809 is about the same topic, specifically asking for supporting the `X-Forwarded-Prefix` header added by traefik.

Would this solution work for you ?

**Comment by Deltachaos** [comment]
Possibly related to #32307

**Comment by maximeag** [comment]
Yes totally related to #36809 #32307. The solution I found works..ish.
Actually I'm trying to get both twig functions `path/url` and `asset` working by altering the RequestContext but only works with `path/url` so far.
I'm still digging and I will keep you posted.

**Comment by nicolas-grekas** [comment]
Closing then.
For reference in case it helps:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#x-forwarded-prefix-header
