### ISSUE TITLE
SingleCommandApplication can't use in CommandTester

### ISSUE THREAD

**Issue by ochi51** [symfony/symfony#37723]
**Symfony version(s) affected**: v5.1.2

**Description**  
I'm testing a SingleCommandApplication with CommandTester(PHPUnit).
However, the execution result cannot be received because it is `exit`.
I think this is because [`autoExit`](https://github.com/symfony/console/blob/v5.1.2/Application.php#L71) is `true`.
If possible, I want to run [`setAutoExit(false)`](https://github.com/symfony/console/blob/v5.1.2/Application.php#L363) from the test code.

**How to reproduce**  

```MainCommand.php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

class MainCommand extends SingleCommandApplication
{
    public function __construct()
    {
        parent::__construct('Test');
        $this->setUp();
    }

    private function setUp()
    {
        $this
            ->setCode(
                function (InputInterface $input, OutputInterface $output) {
                    return Command::SUCCESS;
                }
            );
    }
}
```

```MainCommandTest.php
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;

class MainCommandTest extends TestCase
{
    public function test()
    {
        $command = new \MainCommand();
        $commandTester = new CommandTester($command);
        $commandTester->execute([]);
        self::assertEquals(Command::SUCCESS, $commandTester->getStatusCode());
    }
}
```

**Comment by chalasr** [comment]
See #37732 for `setAutoExit()`. 
For 5.1 you can use `.phpt` tests (see e.g. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Tests/phpt/single_application/arg.phpt)

**Comment by ochi51** [comment]
@chalasr 
Thank you!
I could know everything I wanted to know!
