### ISSUE TITLE
[RFC] Split the Intl polyfill from the Intl CLDR features

### ISSUE THREAD

**Issue by stof** [symfony/symfony#37758]
**Description**  
The `symfony/intl` package provides 2 independent sets of features:

- polyfills for various `ext-intl` classes exposing ICU features (`IntlDateFormatter`, `IntlNumberFormatter`, `Collator` and `Locale`)
- public APIs exposing some CLDR data that is not available through `ext-intl`. That's the `\Symfony\Component\Intl\Intl` class in older Symfony versions, and its replacements in newer versions (`\Symfony\Component\Intl\{Currencies,Locales,Locale,Languages,Countries,Scripts,Timezones}`)

When we created the symfony polyfills (many years later), we created a `symfony/polyfill-intl-icu`, which is semantically meant to provide the first half, but is actually implemented by requiring `symfony/intl`. This has several effects:

- it does not make it clear what the intended usage is (in the modern way, packages needing only polyfills for ICU classes should depend on `symfony/polyfill-intl-icu`)
- packages requiring `symfony/polyfill-intl-icu` actually receive the full `symfony/intl` package, which is by far the biggest contributor to the size of vendors among Symfony components (and bigger than many packages in the ecosystem) due to the size of the CLDR data, which is not needed for their use case.
- polyfills are using a very specific architecture (all the implementation goes in an internal abstract class used as parent), which is very common in `symfony/polyfills` but can be confusing when finding it in `symfony/symfony` (see #37756 for instance, which is caused by such confusion)
- if you use the [`replace` trick](https://github.com/symfony/skeleton/blob/bddaf2fe22e0c1ddf2456ab321c8729f16f5b935/composer.json#L38-L46) to remove unnecessary polyfills because your project has a requirement on `ext-intl`, you will still get the polyfill implementation in your vendors (which might confuse the IDE due to double class definitions)

**Proposal**  
My proposal is to actually move the implementation of ICU polyfills to `symfony/polyfill-intl-icu` directly (the only change needed would be the namespace used for internal classes), and then change the order of the dependency. `symfony/polyfill-intl-icu` would be standalone, and `symfony/intl` would require `symfony/polyfill-intl-icu` (with the new version containing the polyfill as lowest bound).
This would give clear responsibilities to both packages, one providing the polyfill and the other one providing extra features.

The only impact would be on projects requiring `symfony/polyfill-intl-icu` and actually using the `symfony/intl` APIs without noticing they don't define a requirement for them, as `symfony/intl` might not be installed anymore. But the `symfony/polyfill-intl-icu` package does not document that these APIs become available due to the implementation details.

**Comment by nicolas-grekas** [comment]
That'd make sense, help wanted!

**Comment by stof** [comment]
Do we want to make some complex git magic to preserve the git history of the various polyfill files in the polyfill repository (this would probably result into a branch starting from an separate root in the history, and merged when merging the code) or are we OK with a dumb copy in the new repo resulting into a single `import` commit (which might reference the commit from symfony/symfony from which it is imported and allowing to find the older history) ?

**Comment by stof** [comment]
There is one thing I wonder: to avoid duplicate class definitions, we might need to make `symfony/polyfill-intl-icu` 1.19+ (or whatever the release including this ends up being) conflict with `symfony/intl versions shipping the polyfill. If that's indeed the case (I need to check the behavior of Composer 1.x and 2.x regarding this to confirm it), would it be OK to apply the change in 3.4 so that all maintained branches are updated to rely on  `symfony/polyfill-intl-icu` for the polyfill implementation ? AFAICT, the only changes between 3.4 and master in the polyfills part of symfony/intl are:
- fixing the `::create` method to use late static binding to create an instance of the child class. This is actually a bug fix, as `\Collator::create()` would not create a `\Collator` instance when using the polyfill from 3.4 but an instance of the internal parent class. I don't know why this has not been applied in older branches but it looks like a mistake.
- marking the internal implementation classes abstract (which is probably how the previous bug was discovered), which is OK as they are internal and they would change namespace anyway in the symfony/polyfill repo.
- adding scalar typehints in the methods. This should probably not be kept in symfony/polyfill to keep supporting older PHP version (the current behavior is that it potentially installs an unmaintained version of `symfony/intl` on old PHP versions)

**Comment by stof** [comment]
@nicolas-grekas any answer ?

**Comment by nicolas-grekas** [comment]
I gave this a try. I have a locally rewritten history of the polyfill classes. But I have one blocker: `NumberFormatter` uses the data from `Currencies`, which is only found in symfony/intl.
Looks like a dead end. WDYT?

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/polyfill/pull/310

**Comment by stof** [comment]
@nicolas-grekas the fallback NumberFormatter implements English only, and only needs 2 info about the currencies: the symbol and the fraction digits. We could bundle that (much smaller) info in the polyfill package (without exposing it to the outside, as that's what `Currencies` from `symfony/intl` does).

**Comment by stof** [comment]
@nicolas-grekas should this really be closed ? I think it requires changes in symfony/symfony too.
