### ISSUE TITLE
[Intl] IntlDateFormatter is abstract, yet it promotes instantiation

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#37756]
**Symfony version(s) affected**: 4.4.11

**Description**  
In https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php#L24-L27 it promotes creation, but it's abstract.

**Possible Solution**  
Update docs.

**Comment by stof** [comment]
This class is the internal class containing the polyfill implementation (`\Symfony\Component\Intl\DateFormatter\IntlDateFormatter`). The usage of the polyfill is done by using `\IntlDateFormatter`, where the polyfill implementation is at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/Resources/stubs/IntlDateFormatter.php

Extracting the implementation to a parent abstract class in the Symfony namespace is done to ease our maintenance work. But we still document which APIs of `\IntlDateFormatter` are supported by the polyfill implementation.

So to me, there are no docs to update.
