### ISSUE TITLE
Ability disable weblink on dev mode

### ISSUE THREAD

**Issue by nuryagdym** [symfony/symfony#37772]
Hi,
I am using Weblink to preload js, css assets, but when I use changes in these files are reflected in browser (at least Chrome browser).
Without using it if I use Chrome shortcut `CTRL+F5`  latest version of assets are loaded. However, when I use Weblink I need to open the asset file itself on browser and use `CTRL+F5` shortcut there in order to load latest version.
option to disable Weblink on development environment would solve I guess.

**Comment by dunglas** [comment]
You should disable the browser cache when developing (most web browsers have a setting to disable cache when dev tools are open).

If you really want to disable this in dev mode, you can use the `app.environment` Twig variable to not use the `preload` helper in dev mode (but IMHO it's not a good idea).

**Comment by nuryagdym** [comment]
I did not know that we can disable cache on chrome when dev tools open, thanks for this tip!
By saying this is not a good idea, I guess you mean checking `app.environment` value?
All in all, is it a bad idea to add this feature I purposed?

**Comment by fabpot** [comment]
Based on @dunglas comment, I think we won't implement it in code.
