### ISSUE TITLE
Review of php-symfony server generator

### ISSUE THREAD

**Issue by ybelenko** [symfony/symfony#37785]
Hey, Symfony team!

Thanks for awesome framework! I'm top contributor to [OpenAPI-Generator](https://github.com/OpenAPITools/openapi-generator) project (open-source fork of Swagger Codegen). It makes possible to create server stubs from [OAS3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md) API schema with single command:
```console
openapi-generator generate -i petstore.yaml -g php-symfony -o /output
```
As result you'll get PHP server stubs which looks like [these samples](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/php-symfony).

We deeply ask for any review/advices/suggestions from Symfony team. Our project is huge (1500+ contributors and [very long list of companies](https://github.com/OpenAPITools/openapi-generator#4---companiesprojects-using-openapi-generator) which use our codegen) and we don't want to disappoint such a big group of users. We're close to next major release `5.0.0` which will contain a lot of updates.

Here is [config options for `php-symfony`](https://openapi-generator.tech/docs/generators/php-symfony).

___Significant Note!___
___I'm in the middle of creating new `php-symfony5` generator right now. Pull request will be submitted soon. Maybe it doesn't make sense to review current generator based on Symfony4 anymore. Anyway, just let us know whether you interested or not.___

cc founders of OpenAPI Generator @wing328 and @jimschubert

**Comment by fabpot** [comment]
I've also posted a message on Slack.

**Comment by ybelenko** [comment]
@fabpot Thanks a lot!
Should we mention someone from your team in PRs(of course only when changes related to Symfony)?
