### ISSUE TITLE
PHPUnit deprecates the at() matcher for mock objects

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#37780]
**Symfony version(s) affected**: 3.4, 4.4, 5.1, 5.2

**Description**  
See sebastianbergmann/phpunit#4297.

The Symfony testsuite makes heavy use of the `at()` matcher to model multiple expected calls to a test double. The PHPUnit project plans to remove that functionality with PHPUnit 10.

**How to reproduce**  
Run the testsuite with PHPUnit 9.3.

**Possible Solution**  
* @greg0ire has worked on a PR for Doctrine Annotations: doctrine/annotations#345. Maybe we can apply similar changes.
* Work with the PHPUnit project on a proper replacement for that feature.
* Switch to a different mocking framework. 🙈 

**Additional context**  
When running the 3.4 testsuite with PHPUnit 9.3, about 170 deprecation warnings are logged regarding the planned removal of that functionality: https://travis-ci.org/github/symfony/symfony/jobs/716119378

Related to #37564

**Comment by xabbuh** [comment]
I have started to work on this (see #37808).
