### ISSUE TITLE
Issues in embedded multiple form invalidation messages.

### ISSUE THREAD

**Issue by trendkill** [symfony/symfony#37789]
**Symfony version(s) affected**: 4.4.10

**Description**  
First we display a form to modify records, with multiple embedded forms and we add 3 new invalid embedded records, so that the invalidation messages are displayed. Then we delete the first one that we just added and send the form to obtain the invalidation records again, some of the embedded forms will be displayed, without the invalidation messages.

This is due to the fact that the propertyPaths are correlatively returned incorrect because when you eliminate a multiple embedded form, the correlativity of the numbers that make up the values ​​of the HTML attributes: name and id, of multiple embedded forms, is breaking.

An attempt was made to implement a trick to force correlativity via JS when loading the collection, but this corrupts the delete action of multiple forms, causing the corresponding ones to not be deleted.

There was also an attempt to force from the server side, in the project's PHP code, but no workable solution was found.

**Possible Solution**  
Fix the "propertyPath" values ​​that the invalidation messages contain, since the indexes do not necessarily have to be correlative.

data.hitos[0].name
data.hitos[1].name
data.hitos[2].name
data.hitos[3].name

**Additional context**  
In the symfony debug bar it is possible to review the "propertyPath" values.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by trendkill** [comment]
> Can you create a small example application that allows to reproduce your issue?

Unfortunately I don't have time anytime soon
