### ISSUE TITLE
[Routing] Locale is ignored

### ISSUE THREAD

**Issue by pcmanprogrammeur** [symfony/symfony#37802]
Hi all,

Here is the context : I have a multi country website and i have an url which is the same between France and Belgium website but I want them to redirect to different actions.
Here is a simple sample of my controller :

```
    /**
     * @Route({
     *     "fr": "/over-ons",
     *     "be": "/about-us"
     * }, name="about_us")
     */
    public function about()
    {
        die("about");
    }


    /**
     * @Route({
     *     "fr": "/about-us",
     *     "be": "/over-ons"
     * }, name="about_us_2")
     */
    public function about2()
    {
        die("about 2");
    }
```

Then, i created a LocaleSubscriber (based on https://symfony.com/doc/current/session/locale_sticky_session.html) :

```
<?php
namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class LocaleSubscriber implements EventSubscriberInterface
{
    private $defaultLocale;

    public function __construct($defaultLocale = 'en')
    {
        $this->defaultLocale = 'fr';
    }

    public function onKernelRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();

        $request->setDefaultLocale($this->defaultLocale);
        $request->setLocale($this->defaultLocale);
        $request->attributes->set('_locale', $this->defaultLocale);
        $routeParams = $request->attributes->get('_route_params');
        $routeParams['_locale'] = $this->defaultLocale;
        $request->attributes->set('_route_params', $routeParams);
    }

    public static function getSubscribedEvents()
    {
        return [
            // must be registered before (i.e. with a higher priority than) the default Locale listener
            KernelEvents::REQUEST => [['onKernelRequest', 20]],
        ];
    }
}
```
Then i opened http://localhost/about-us and wanted to see the message "about 2" but i have "about".

So the road "about-us" with locale "fr" shoud be matched with about2 action but it matches with about action.

Do you kown if it is possible that the Router match a route with a specific locale please ?

Thanks for your help !

**Comment by Tobion** [comment]
The locale is irrelevant for matching the routes AFAIK. So /about-us just matches whatever route is defined first with that path (in this case the about() action).

I don't get the use-case really. Maybe you want to use different hosts for about() and about2()? Then that could be used to differentiate the two routes.
You subscriber only changes some params. But it doesn't change the fact which controller was matched. In theory you could maybe change the `_controller` param to change this. But as I said, I don't see the use-case of all this.

**Comment by Tobion** [comment]
Closing due to missing feedback.
