### ISSUE TITLE
[Form] ChoiceType without the `choices` data

### ISSUE THREAD

**Issue by njutn95** [symfony/symfony#37817]
Is it in any way possible to submit ChoiceType (expanded=false, multiple=true) with the values that are not defined inside the `choices` key? 

This is the code I'm working with:
```
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tagsText', ChoiceType::class, [
                'attr'=>['class'=>'tags select2-tags'],
                'multiple'=>true,
                'mapped'=>false,
                'required'=>false
            ])
        ;
    }

    // ...
}
```

And this is my front-end:

```
{{ include('_form.html.twig' }}

<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
<script>
$('select.select2-tags').select2({
    closeOnSelect: false,
    tags: true
});
</script>
```

Select2 has the `tags` option which allows user to enter data that isn't in the list. And in this concrete example, it makes complete sense - user wants to add tags to each item, and if he previously entered that tag he can select it, or add a completely new one (without having to previously create new tag and then selecting it in the form).

The problem I receive after entering new data is `This value is not valid.`. As I've been trying to make a workaround on this topic, by making the field unmapped, changing validation groups and so on, I am left without ideas so I came here now. 

Thanks in advance!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by njutn95** [comment]
Understandable, I was hesitating whether to post it here or not, as I'm not really sure whether it's really a bug or just a feature I'm looking to achieve here!
