### ISSUE TITLE
[FORM] ChoiceType - multiple = true does not work anymore on 5.0.11

### ISSUE THREAD

**Issue by ldecoker** [symfony/symfony#37825]
**Symfony version(s) affected**: 5.0.11

**Description**  
The generated HTML for a ChoiceType form field with expanded = true and multiple = true is not correct. The generated HTML is missing a "[]" in the checkbox field name.

**How to reproduce**  

- add a ChoiceType field in a form:

```
$builder->add('choicesField', ChoiceType::class, [
					'label' => false,
					'multiple' => true,
					'expanded' => true,
					'mapped' => true,
					'choices' => [
						"choice1" => value1,
                                                 "choice2" => value2,
                                                 "choice3" => value3,
                                                "choice4" => value4,
                                                "choice5" => value5,
					],
				]);
```
In the twig template:

```
{{ form_errors(form) }}
{{ form_start(form) }}
{{ form_row(form.choicesField) }}
{{ form_end(form) }}
```

The generated HTML looks like the following:

`<input type="checkbox" id="status_choicesField_0" name="status[choiceFields]" class="form-check-input" value="choice1">`

This should be:

`<input type="checkbox" id="status_choicesField_0" name="status[choiceFields][]" class="form-check-input" value="check_data">`

**Comment by xabbuh** [comment]
Can you create. a small example application that allows us to reproduce the issue?

**Comment by ldecoker** [comment]
Any suggestion on how to do it (in an easy way 😸  )?

**Comment by xabbuh** [comment]
Does https://symfony.com/doc/current/contributing/code/reproducer.html help?

**Comment by ldecoker** [comment]
I was preparing a bug app but I was not able to reproduce the problem. Thx to that I found out that a modification in the choice_widget_expanded block rendering (I have made) has the side effect to remove the "[]" in the name field in case of multiple checkbox. The faulty section:

```
{% block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        {%- for child in form %}
            {{- form_widget(child, {
                full_name: full_name,
                parent_label_class: label_attr.class|default(''),
                translation_domain: choice_translation_domain,
                valid: valid,
            }) -}}
        {% endfor -%}
    </div>
{%- endblock choice_widget_expanded %}
```

Now I need to find out why I did that and how I can solve it. Sorry for this and thx for helping me to see where was the issue.
Next time, I will first do a clean app with the minimum to see if it's a real bug or if it's me the bug 😸 

Have a beautiful day!
