### ISSUE TITLE
Environment Variable Processors not working in security.yml

### ISSUE THREAD

**Issue by alexgit2k** [symfony/symfony#37836]
**Symfony version(s) affected**: 4.4

**Description**  
https://symfony.com/doc/current/configuration/env_var_processors.html says that there are json and csv processors which can be used for environment variables like `%env(csv:TRUSTED_HOSTS)%` with `env(TRUSTED_HOSTS): "10.0.0.1, 10.0.0.2"`

However using this for IP-protection in security.yml like https://symfony.com/doc/current/security/access_control.html#matching-access-control-by-ip fails with `Invalid type for path "security.access_control.2.ips.0". Expected one of "bool", "int", "float", "string", but got "array".`

**How to reproduce**

* config/packages/security.yaml
```
security:
    # ...
    access_control:
        - { path: '^/internal', roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: '%env(csv:TRUSTED_HOSTS)%' }
        - { path: '^/internal', roles: ROLE_NO_ACCESS }
```

* .env.local.php
```
return array (
 ...
 'TRUSTED_HOSTS' => '10.0.0.1, 10.0.0.2',
 ...
);
```

Execute `bin/console cache:clear`

The same is happening when using json-processor with `%env(csv:TRUSTED_HOSTS)%` and `'TRUSTED_HOSTS' => '["10.0.0.1", "10.0.0.2"]',`

**Additional context**  

Failure message:
```
In BaseNode.php line 543:

  Invalid type for path "security.access_control.2.ips.0". Expected one of "bool", "int", "float", "string", but got "array".
```

**Comment by ro0NL** [comment]
i believe this is the same issue as #27683

see also https://github.com/symfony/symfony/issues/27683#issuecomment-440337881 - the docs are wrong.

**Comment by x1a** [comment]
I have the same issue in Symfony 5.1

secyrity.yml
`
firewalls:
        ....................
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            security: '%env(bool:API_SECURITY)%'
            .......
`
but it does not work

**Comment by nicolas-grekas** [comment]
@x1a why do you think your issue is related to the original description? "it does not work" could have thousands or different reasons...

**Comment by nicolas-grekas** [comment]
Closing as duplicate of #27683

**Comment by x1a** [comment]
@nicolas-grekas because it is also related to using environment variables in security.yaml

I tried such two simple cases (on fresh installed Symfony 5.1)

```
parameters:
    api.security: false

security:
    // ...
    firewalls:
        // ...
        api:
            //...
            security: '%api.security%'
    
```
and
```
parameters:
    env(API_SECURITY): 'false'
    api.security: '%env(bool:API_SECURITY)%'

security:
    // ...
    firewalls:
        // ...
        api:
            //...
            security: '%api.security%'
    
```
for first case it works as expected (security is turned off), for second case it does not

This test is passed for both cases
```
    public function testSomething()
    {
        $this->assertFalse(self::$container->getParameter('api.security'));
    }
```
It looks weird for me though may be I don't understand smth
