### ISSUE TITLE
Bogus code discovered

### ISSUE THREAD

**Issue by soletan** [symfony/symfony#37848]
**Symfony version(s) affected**: don't ... found it on github.com

**Description**  

Stumbled over this code while searching for a solution to suppress undefined-index-notices in Symfony-4.2-logs, however the code isn't related to 4.2 ...

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L427

The value returned in line 428 is always false. So, either this is an unnecessarily complex way of achieving that or there is an issue with intended behaviour in this place.

**How to reproduce**  

Just test: the condition in line 427 is `true` if either `$type` is falsy or `$log` and `$throw` are falsy. So, to conclude, either `$type` or `$log` must be falsy to enter this branch. But in that case the expression in there can't be true.

**Possible Solution**  

**Additional context**

**Comment by fancyweb** [comment]
Status: reviewed

Judging from the code, I also don't see how it could return anything else than false. However, that's not a bug, just a code optimization.

I traced back the change to https://github.com/symfony/symfony/commit/15ef182b9971472aa30753da6349c0d28f477d43#diff-e7d086f2c2086fdb8f108e74f11dac5bR359.

**Comment by fancyweb** [comment]
Could you send a pull request on 4.4 btw?
