### ISSUE TITLE
Inconsistent Non-Shared Services

### ISSUE THREAD

**Issue by natewiebe13** [symfony/symfony#37863]
**Symfony version(s) affected**: 4.x, 5.x (potentially more)

**Description**  
When configuring a service with `shared: false`, autowiring multiple instances within a controller action will return new instances, but autowiring into a service (including controllers) via `__construct()` will return the same instance.

I think it would be best for either situation to behave similarly or if this behaviour is intended, it should be documented. Probably here: https://symfony.com/doc/current/service_container/shared.html

**How to reproduce**  
A reproducer has been created here: https://github.com/natewiebe13/symfony-service-inconsistency/pull/1 oddly enough, if we also try to autowire the non-shared service through the constructor, a `ServiceNotFoundException` is thrown which is likely a separate issue from this one. A reproducer for the exception is here: https://github.com/natewiebe13/symfony-service-inconsistency/pull/2

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, you found two bugs with non-shared services, kudos :)
Here is the fix: #38023

**Comment by natewiebe13** [comment]
@nicolas-grekas thanks for the fix. To clarify, is the intended behavior that autowiring the same service into a constructor twice will result in two unique instances like in the controller actions? (hoping so)

**Comment by nicolas-grekas** [comment]
Yes, the fix injects two different instances.
