### ISSUE TITLE
[HttpFoundation] inconsistent argument annotation for method $request->query->get()

### ISSUE THREAD

**Issue by angelbachev** [symfony/symfony#37882]
**Symfony version(s) affected**: 5.1.*

**Description**  
In version 5.1.* the type of $query property in Request class was changed from ParameterBag to InputBag.
InputBag extends ParameterBag but modified method get() signature.
This make the following code (which works fine in 5.0.*) invalid
`$languages = $request->query->get('languages', ['en']);`
In the project I'm currently working on we use [PHPStan](https://github.com/phpstan/phpstan) which is part of our continuous integration process.
PHPStan throws a lot of warnings because of this inconsistency.

**How to reproduce**  
Run a PHPStan on a file which call $request->query->get() with array as default argument.

**Possible Solution**  
Change Request::query type back to ParameterBag

**Additional context**  
In Symfony 5.0.*
![image](https://user-images.githubusercontent.com/17396581/90610643-66c7a180-e20e-11ea-816c-168731848ec1.png)

In Symfony 5.1.*
![image](https://user-images.githubusercontent.com/17396581/90612454-bb6c1c00-e210-11ea-9be2-cc850e47ba69.png)

PHPStan error:
Parameter #2 $default of method Symfony\Component\HttpFoundation\InputBag::get() expects string|null, array<int, string> given.                             

According to the official Symfony 5.1.* documentation the type of query is ParameterBag, not InputBag.
https://symfony.com/doc/current/components/http_foundation.html#accessing-request-data
![image](https://user-images.githubusercontent.com/17396581/90613236-c07d9b00-e211-11ea-9020-4627511dd764.png)

**Comment by Tobion** [comment]
The phpstan warning is correct. You'll also get a deprecation, see https://github.com/symfony/symfony/blob/890f8f0c78c2a56c2b214dc8ed0c1121d5032d7d/src/Symfony/Component/HttpFoundation/InputBag.php#L32-L34
This is intentional per #34363

The documentation problem can be reported and fixed in https://github.com/symfony/symfony-docs. Thanks
