### ISSUE TITLE
Repository name invalid

### ISSUE THREAD

**Issue by mook73** [symfony/symfony#37901]
Hello,

Sorry for my poor english...
I am a junior and this is the first time that I have made a mistake like this, I hope I do.
The bug being simple I did not consider it relevant to put an example code.

At work I am on a Symfony 3.4 project (under ubuntu 18.04 and phpStorm 2020.1) and tried to create a repository for my ServiceGroup entity named ServiceGroupRepository.

Impossible! phpStorm / Symfony? never detected my class ... I spent the day researching why the name **ServiceGroupRepository** was not detected ...

I finally changed the name to ServicegroupRepository and everything worked out fine.

Hope this helps.

Thank you for your attention.

**Comment by xabbuh** [comment]
@mook73 Please note that we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
