### ISSUE TITLE
[HttpClient] CurlHttpClient mutiple resolves to same host with different IPs not working

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#37924]
**Symfony version(s) affected**: 4.4.11

**Description**  
When making multiple requests to the same host with different IPs set with the `resolve` option the `CurlHttpClient` doesn't work as expected. It caches the IP of the first request & ignores the IP set in any subsequent request.

The problem seems to be in the cURL multi handle itself which seems to do the caching.

The `NativeHttpClient` **doesn't** experience the same problem.

**How to reproduce**  
```php
    public function index(HttpClientInterface $httpClient)
    {
        $httpClient->request('PURGE', 'https://example.com/image.jpg', [
            'resolve' => [
                'example.com' => '192.168.0.155',
            ],
        ]);

        $httpClient->request('PURGE', 'https://example.com/image.jpg', [
            'resolve' => [
                'example.com' => '192.168.0.156',
            ],
        ]);
    }
```

I was able to reproduce the problem using vanilla PHP:

```php
$mh = curl_multi_init();

$ch = curl_init();
curl_setopt($ch, CURLOPT_RESOLVE, ['example.com:443:192.168.0.155']);
curl_setopt($ch, CURLOPT_URL, 'https://example.com/image.jpg');
curl_setopt($ch, CURLOPT_DNS_USE_GLOBAL_CACHE, false);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PURGE');
$active = 0;
curl_multi_add_handle($mh, $ch);
while (CURLM_CALL_MULTI_PERFORM === curl_multi_exec($mh, $active));

var_dump(curl_getinfo($ch));


// $mh = curl_multi_init();  // <-- doesn't work without this line

$ch = curl_init();
curl_setopt($ch, CURLOPT_RESOLVE, [
    '-example.com:443' => '-example.com:443',
    'example.com:443:192.168.0.156',
]);
curl_setopt($ch, CURLOPT_URL, 'https://example.com/image.jpg');
curl_setopt($ch, CURLOPT_DNS_USE_GLOBAL_CACHE, false);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PURGE');
$active = 0;
curl_multi_add_handle($mh, $ch);
while (CURLM_CALL_MULTI_PERFORM === curl_multi_exec($mh, $active));

var_dump(curl_getinfo($ch));
```

**Possible Solution**  
Reset the cURL multi handle when `$this->multi->dnsCache->removals` is not empty.

**Additional context**  
Debug info from the profiler (`CurlHttpClient`):

First request:

```
  "debug_info" => [▼
    "primary_ip" => "192.168.0.155"
    "primary_port" => 443
    "debug" => """
      * Added example.com:443:192.168.0.155 to DNS cache
      * Hostname example.com was found in DNS cache
      *   Trying 192.168.0.155...
```

Second request:

```
  "debug_info" => [▼
    "primary_ip" => "192.168.0.155"
    "primary_port" => 443
    "debug" => """
      * Added example.com:443:192.168.0.156 to DNS cache
      * Hostname example.com was found in DNS cache
      *   Trying 192.168.0.155...
```

**Comment by nicolas-grekas** [comment]
Could you please check with https://github.com/curl/curl if they think this is a bug or normal, and if normal, why?

**Comment by nicolas-grekas** [comment]
I'm closing because this is not specific to Symfony's CurlHttpClient.
Please provide us with details once you get feedback from the curl maintainers.

**Comment by HypeMC** [comment]
Turns out the problem was an old version of `libcurl`, these issues have been fixed with https://github.com/curl/curl/commit/846f4920535461a9f25c412cc2d1e519067e103b and https://github.com/curl/curl/pull/2622/files
