### ISSUE TITLE
[Session] RedisSessionHandler add read locks to session

### ISSUE THREAD

**Issue by nusje2000** [symfony/symfony#37928]
**Description**  
I don't know if this is a bug or a new feature. Currently when reading the session using the RedisSessionHandler, the handler won't create a read lock. Because of this, asynchronous requests can overwrite the session with older data.

It would be nice if the handler creates a read lock when reading a session that will be removed when the session is closed. When a read lock is active, the handler will wait with reading from the session until the read lock is removed. This will prevent the problem of data loss with multiple concurrent requests.

**Example**
This feature can be implemented using the lock component:
```php
namespace Symfony\Component\HttpFoundation\Session\Storage\Handler;

use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\LockInterface;

class RedisSessionHandler extends AbstractSessionHandler
{
   /** @var array<string, LockInterface>
    protected $locks = [];

    // Made LockFactory nullable for BC
    public function __construct($redis, array $options = [], ?LockFactory $lockFactory = null)
    {
        // ....
        $this->lockFactory = $lockFactory;
    }

    protected function doRead($sessionId): string
    {
        if ($this->lockFactory === null) {
            return $this->redis->get($this->prefix.$sessionId) ?: '';
        }

        // The ttl could be added as additional constructor argument so it could be configured in the service definition
        $lock = $this->locks[$sessionId] ?? $this->locks[$sessionId] = $this->lockFactory->create('session_' . $sessionId, 30);
        if (!$lock->aquire(false)) {
            throw new LogicException('Could not aquire read lock');
        }

        return $this->redis->get($this->prefix.$sessionId) ?: '';
    }

    public function close(): bool
    {
        // Removing the locks should release then since the locks are created using the
        // autoRelease option (this is default lock behavior)
        $this->locks = [];

        return true;
    }
}
```
Instead of the LockFactory being nullable, it could also be replaced by a new instance of the LockFactory with the RedisStore instead. I think this would be the correct method if this issue would be considered a bug. If this is a new feature, then it being nullable would not break any current behavior.

**Comment by Tobion** [comment]
See #4976
