### ISSUE TITLE
[BC] Filter method `trans` of Twig Bridge should allow null values for `$message` parameter again

### ISSUE THREAD

**Issue by Flinsch** [symfony/symfony#37931]
**Symfony version(s) affected**: 5.*

**Description**  
Upgrading Symfony from 4.4 to 5.* has led to BC breaks in our projects since filter method `trans` of class `Symfony\Bridge\Twig\Extension\TranslationExtension` does not allow null values for `$message` anymore. In our projects, we tried to overcome this problem by using the null coalescing operator with an empty string where it was required, but this change turned out to be too time-consuming, so we just provided our own Twig implementation for `trans` hiding/overriding that from the Symfony Twig Bridge. Yes, this is pretty dirty and we feel bad about it, so we hope for a "correction" of the BC break.

**How to reproduce**  
To reproduce the problem just call `trans` on a null value in one of your Twig templates, for example:
```
{{ null|trans }}
```

**Possible Solution**  
I suggest allowing null values for the `$message` parameter of filter method `trans` in `Symfony\Bridge\Twig\Extension\TranslationExtension` again:
```
public function trans(?string $message, array $arguments = [], string $domain = null, string $locale = null, int $count = null): string
{
    if (empty($message)) {
        return ''; // Early out, but not really necessary.
    }

    if (null !== $count) {
        $arguments['%count%'] = $count;
    }

    return $this->getTranslator()->trans($message, $arguments, $domain, $locale);
}
```

**Additional context**  
All implementations of `Symfony\Contracts\Translation\TranslatorInterface` in fact do allow null values as well, so there is no need to restrict the parameter to be not null. On the contrary, it is even inconsistent to forbid null values.

One might think it's nonsense to write something like `{{ null|trans }}`. Yes, but this was just a simple example for reproducing the problem. When the possible to-be-translated string comes from some kind of user-configured object, for example, then it makes perfect sense:
```
{{ form_row(form.shop_contact_url, { attr: { placeholder: tenant.findContactDetailByType('TYPE_WEBSITE') } }) }}
```
(The value of `placeholder` gets translated by calling `trans` filter automatically.)

**Comment by jvasseur** [comment]
Passing `null` values to the translator was never supported : https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/TranslatorInterface.php#L29

It worked because we couldn't enforce it but it never was a supported use of the translator.

**Comment by Flinsch** [comment]
> Passing `null` values to the translator was never supported : https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/TranslatorInterface.php#L29
> 
> It worked because we couldn't enforce it but it never was a supported use of the translator.

Please have a look at `Symfony\Contracts\Translation\TranslatorTrait`, even there null values are allowed. And most (all?) implementations of `Symfony\Contracts\Translation\TranslatorInterface` also allow null values. However, it is a BC break. Please be reasonable.

**Comment by jvasseur** [comment]
Well, the Symfony translator use `inheritdoc` meaning it also clams to only support strings.

**Comment by Flinsch** [comment]
> Well, the Symfony translator use `inheritdoc` meaning it also clams to only support strings.

And it yet allows null values. Please look at the code. The type of the to-be-translated parameter is `?string` and the method explicitly checks for null values.

**Comment by jvasseur** [comment]
You're right, I checked the 4.4 version and not the last one. I'm not sure why it was decided to allow `null` for concrete implementations and not in the interface.

The problem is: we can't change the typing of the interface since it would be a BC break, and since the translation extension claim to support all implementations of the interface, modifying the extension to allow could lead to error case when coupled with implementations that support `null`, it wouldn't necessarily be a problem but could lead to harder to debug errors.

**Comment by Flinsch** [comment]
Thank you for your reply, @jvasseur. I get your point, well, somehow. We _already have_ a BC break here, in the Twig Bridge, because null values were allowed before, but now they are not anymore.

How would loosen the type declaration from `string` to `?string` in the interface lead to BC breaks, especially while the implementations disregard it anyway? Consequently, the implementations would have to be tighten to only allow `string` as well, but _this_ would really lead to _further_ BC breaks.

However, I don't care too much about the translator interface, because the Twig Bridge doesn't implement the interface at all: it just _uses_ the interface for delegation. So the easiest and probably cleanest solution would be to allow null values in the Twig Bridge again to fix the BC break, and then to explicitly check for null values here, for an early out, in order to not pass possible null values to the actual translator, which currently still allows null values as well, but might follow the specification of the "not-null interface" one day.

I have added a commit for this additional aspect of explicitly checking for null values in order to not pass them to the actual translator.

**Comment by jvasseur** [comment]
> How would loosen the type declaration from `string` to `?string` in the interface lead to BC breaks, especially while the implementations disregard it anyway? Consequently, the implementations would have to be tighten to only allow `string` as well, but _this_ would really lead to _further_ BC breaks.

This would break BC if someone was implementing the interface without loosening the type to allow null. In this case, if we change the interface they would end up with an implementation that doesn't accept all the types that the interface accepts witch is a LSP violation.

> However, I don't care too much about the translator interface, because the Twig Bridge doesn't implement the interface at all: it just uses the interface for delegation. So the easiest and probably cleanest solution would be to allow null values in the Twig Bridge again to fix the BC break, and then to explicitly check for null values here, for an early out, in order to not pass possible null values to the actual translator, which currently still allows null values as well, but might follow the specification of the "not-null interface" one day.

I agree with you here, if we do something, it has to be in the Twig bridge
