### ISSUE TITLE
Entity creation with terminal fails

### ISSUE THREAD

**Issue by ldelpri** [symfony/symfony#37939]
**Symfony version(s) affected**: 5.1.3

**Description**  
If I create an entity with `php bin/console make:entity` , when I insert a field's name it crashes with this error:

![bug_symfony](https://user-images.githubusercontent.com/12738084/91173783-a7c42800-e6de-11ea-8bdd-b7b246e43d51.PNG)

**Comment by fabpot** [comment]
You should report it on the Symfony Maker bundle repository instead.
