### ISSUE TITLE
New Project build failed

### ISSUE THREAD

**Issue by Fabricio872** [symfony/symfony#37936]
**Symfony version(s) affected**: 4.4.11

**Description**  
I have a problem installing new project with symfony cli version 4.18.4. Project seems to install correctly but after running it with symfony CLI server it outputs error: 

Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /home/fabricio/PhpstormProjects/tw_catalog/tw_catalog_build/var/cache/dev/ContainerPxvsF1h/srcApp_KernelDevDebugContainer.php on line 4575 

And also the error message seems broken (see attached image) also in image the profiler is in middle of the page it is because i captured whole page with firefox screenshots not only visible part

**How to reproduce**  
 - installl project with command:
  ``` symfony new tw_catalog_build --version=4.4 --full ```
 - run dev enviroment with command:
  ``` symfony serve ```
> i have php version 7.4.3, Composer version 1.10.1 and OS Ubuntu 20.04

**Possible Solution**  

**Additional context**  

![Screenshot_2020-08-25 Welcome to Symfony ](https://user-images.githubusercontent.com/29705379/91158242-a424a700-e6c6-11ea-8297-204783bc34d3.png)

**Comment by fabian-laine** [comment]
+1

**Comment by ro0NL** [comment]
see #37935

**Comment by ldelpri** [comment]
same errorr appears creating an entity with terminal:

```
Argument 2 passed to Symfony\Bundle\MakerBundle\Validator::validateDoctrineFieldName() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bun  
  dle\DoctrineBundle\Registry given, called in C:\wamp64\www\centro_ticket\vendor\symfony\maker-bundle\src\Maker\MakeEntity.php on line 303  
```

**Comment by fabpot** [comment]
This is due to a BC break in Doctrine (see https://github.com/doctrine/DoctrineBundle/pull/1202). Fixed in FrameworkExtraBundle with a new release (v5.6.0). Everything should work again.

**Comment by Fabricio872** [comment]
> This is due to a BC break in Doctrine (see [doctrine/DoctrineBundle#1202](https://github.com/doctrine/DoctrineBundle/pull/1202)). Fixed in FrameworkExtraBundle with a new release (v5.6.0). Everything should work again.

Thank you ti works now
