### ISSUE TITLE
ExpectDeprecationTrait::expectDeprecation doesn't cover every case

### ISSUE THREAD

**Issue by snoob** [symfony/symfony#37932]
**Symfony version(s) affected**: 5.1.3

**Description**  
The new method ExpectDeprecationTrait::expectDeprecation doesn't work exactly like the old deprecated @expectedDeprecation annotation

**How to reproduce**  
I know i should not but one of my class extends a vendor internal class (AbstractSearchFilter from api-platform)
Previously (sf 4.4), i was able to silent this deprecation thank to the annotation and the legacy group like that :

```
/**
     * @group legacy
     * @expectedDeprecation The "ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Filter\AbstractSearchFilter" class is considered internal. It may change without further notice. You should not use it from "App\Adapter\ApiLegacy\ApiPlatform\Elasticsearch\TermFilter".
*/
```

With the new method expectDeprecation is was not able to silent this deprecation on code coverage generation stage
and the process returns 1 exist code so the CI fails.

Did i miss something ? This behavior changes was expected ?

**Possible Solution**  
The test doesn't directly trigger the deprecation. The @internal deprecations are collected by DebugClassLoader and triggered by DeprecationErrorHandler on shutdown function. I guess DebugClassLoader could be aware of annotations which is not possible with a method call.

**Comment by fancyweb** [comment]
Hello, can you provide a small projet that reproduce the issue please?

**Comment by snoob** [comment]
I tested in a small project and i noticed it was an issue on my test. The deprecated was referenced in my Test class and it was not necessary. 

By the way, the old @expectedDeprecation worked in this case.

If you are curious you can see the repository here : https://github.com/snoob/symfony-37932

**Comment by nicolas-grekas** [comment]
@snoob not sure I get your last comment. Can you please close this issue if there is no issue? Or maybe explain the issue if there is one?

**Comment by snoob** [comment]
The current and old behavior seem to be different but my use case / test was weird so i think we can close the issue.
