### ISSUE TITLE
getSubscribedServices() does not support all valid container service names

### ISSUE THREAD

**Issue by TerjeBr** [symfony/symfony#37933]
**Symfony version(s) affected**: 3.4 and up

**Description**  
When implementing the `Symfony\Component\DependencyInjection\ServiceSubscriberInterface` the method `getSubscribedServices()` is supposed to return all services that the class can get from the container.

The problem is that if the service name has a `.` in it it will not be allowed.
Not all services are defined as a fully qualified class name, some (may be for legacy reasons or other reasons) may still be defined in the container with `.` in it.

**How to reproduce**  
Crate a service in the dependency container called f.ex: "my.test.service".

Then create another service `App\MyService` that implements `Symfony\Component\DependencyInjection\ServiceSubscriberInterface` and is trying to use this service. The method `getSubscribedServices()` could look like this

```
public static function getSubscribedServices()
{
    return ['key' => 'my.test.service'];
}
```

Then you get the error:
```
"App\MyService::getSubscribedServices()" must return valid PHP types for service "App\MyService" key "key", "my.test.service" returned.
```

**Possible Solution**  
The regex in code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php line 71 should be removed or relaxed so that all possible container service names and aliases are allowed.

**Comment by ro0NL** [comment]
see #37613

**Comment by TerjeBr** [comment]
No #37613 seems to be different. I want to be able to use a dot in the value, not in the key.

**Comment by ro0NL** [comment]
But the value specifies the expected PHP type: `foreach ($class::getSubscribedServices() as $key => $type) {`

So this looks a new feature request, rather than a bug.

**Comment by TerjeBr** [comment]
The key is the local alias for the service in the class implementing `ServiceSubscriberInterface`. The value is the actual service name in the real dependency container.

I want to be able to use actual service names that are not necessarily the FQCN of the class implementing the service. I works well for any service not containing a `.`.  I think it is a meaningless restriction to not allow dot in service names here.

**Comment by nicolas-grekas** [comment]
`ServiceSubscriberInterface` is defined as a key of (name => PHP-type) array. Adding support for service ids would break its contract. The fact that some service ids work is "by chance", you should avoid relying on it.

**Comment by TerjeBr** [comment]
"Adding support for service ids would break its contract." It would not break it in a non backwards compatible way.

So what you are saying is that it is not a bug but a feature. Then would you be so kind to mark this issue as a new feature request then.

I think it is an unnecessary limitation of ServiceSubscriberInterface to only support services that has their FQCN as their service name. Please make it support any service that is defined in the dependency container.

Do you think this is an unreasonable feature request? For f.ex. symfony commands the ServiceSubscriberInterface is the only "officially" approved way of getting access to container services.

**Comment by nicolas-grekas** [comment]
> Do you think this is an unreasonable feature request?

yes, I would object this proposal, here is why: `ServiceSubscriberInterface` defines a standalone concept, that allows one class to describe "what" it consumes from the service locator it uses. The "what" is defined in terms of name+type. You can compare this to a parameter declaration: `function (Foo $abc)`: `Foo` is the type, `$abc` is the name. `ServiceSubscriberInterface` is designed to declare exactly the same thing, just nor for parameters but for items in a locator. Put in short, your request is similar to asking for `function (my.test.service $key)` to be legal, "because autowiring would get what this means". I hope my explanations are clear enough. Your proposal mixes two separate concepts: type-declaration of dependencies and service wiring. But both are split.

> For f.ex. symfony commands the ServiceSubscriberInterface is the only "officially" approved way of getting access to container service

or you can inject as many services as you want using regular DI: via constructor, setters, etc.

**Comment by TerjeBr** [comment]
@nicolas-grekas  said:
> The "what" is defined in terms of name+type.

The problem is that the "name" here is the new name or alias for the service, used only in the class that implements `ServiceSubscriberInterface`. There is no way to say which "original service name" we want from the dependency container.

So this way the `ServiceSubscriberInterface` is lacking, in that it cannot extract anything from the container, only some services. Also consider that the exact php type is not important, that can anyway be figured out from the existing service definition if needed.

> Your proposal mixes two separate concepts: type-declaration of dependencies and service wiring. But both are split.

The problem here is that the concepts are not split. If they had been split in the first place I would not have raised this issue.
The problem is that what you see as "type-declaration of dependencies" only, is also the only way that this interface tells which services to wire.

Could you please reconsider this? How can or should I get access to the service "my.test.service" in the class `App\MyService` that is implementing the `ServiceSubscriberInterface`?

**Comment by dmaicher** [comment]
@TerjeBr I think this should be doable with a binding?

Like
```
App\MyServiceSubscriber:
    bind:
        App\MyService: '@my.test.service'
```

**Comment by TerjeBr** [comment]
@dmaicher The problem is that the static function `getSubscribedServices()` does not have access to bindings.

My major use case for the `ServiceSubscriberInterface` is when the function `getSubscribedServices()` has some actual work to do, and what it returns is dynamic and depending on other factors.

Then your solution will not work, because the bindings are static definitions in the services.yaml file.

**Comment by nicolas-grekas** [comment]
>  There is no way to say which "original service name" we want from the dependency container.

Yes, there is: bindings allow taking over for most needs as @dmaicher explained, but you can also use a service tag to precisely wire any service into any key of a service subscriber. I get that's maybe not documented. Dunno about bindings also. Would you consider a PR to the doc, adding the kind of info you missed and made you open this very issue?

**Comment by nicolas-grekas** [comment]
> getSubscribedServices() has some actual work to do, and what it returns is dynamic and depending on other factors.

I think that's a design issue on your side: you need to think of this function as parameter type declarations - you cannot compute these of course. That's the same here: if there is any logic, it should be sourced from the code itself, never from any "global state".

**Comment by TerjeBr** [comment]
My use case is that I have in the configuration file for my bundle a list of valid rabbitmq vhosts. For each vhost I want the service implementing `ServiceSubscriberInterface` to be able to access a list of rabbitmq provider services, one for each vhost.

This list of "rabbitmq provider services" is only known after my bundle has read its configuration files. So how can I do this, if the function `getSubscribedServices()` cannot specify the exact service name to get from the container?

**Comment by nicolas-grekas** [comment]
Using a factory to implement the logic?

**Comment by TerjeBr** [comment]
No, using a factory is not an option. The "rabbitmq provider services" all has to be defined in advance as services in the container. This is a limitation of a third party bundle I am working with.

**Comment by nicolas-grekas** [comment]
Then you might be looking after a compiler pass?

**Comment by TerjeBr** [comment]
I did not want to write a compiler pass, since I thought the `ServiceSubscriberInterface` could be a good fit to solve my problem.

But I guess it might be that I will need to resort to that.

**Comment by nicolas-grekas** [comment]
That's the best I think yes.
Closing now that this has been resolved by the discussion.
Thanks for asking.
