### ISSUE TITLE
[Doctrine] Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given

### ISSUE THREAD

**Issue by jhfyang** [symfony/symfony#37935]
Just installed with Symfony-CLI a new project in 5.1.3

When using doctrine I get this errror: 

`Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /home/yang/Projects/noyz-symfony/var/cache/dev/ContainerZxrp7lI/App_KernelDevDebugContainer.php on line 1512`

Indeed when looking we have `Doctrine\Bundle\DoctrineBundle\Registry extends Symfony\Bridge\Doctrine\ManagerRegistry`  and not `Doctrine\Common\Persistence\ManagerRegistry` as expected in at `DoctrineParamConverter`

Possible fix would be to change in `DoctrineParamConverter.php`:
`use Doctrine\Common\Persistence\ManagerRegistry;`
to
`use Symfony\Bridge\Doctrine\ManagerRegistry;`

**Comment by fabpot** [comment]
See https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/691

**Comment by fabpot** [comment]
This is due to a BC break in Doctrine (see https://github.com/doctrine/DoctrineBundle/pull/1202). Fixed in FrameworkExtraBundle with a new release (v5.6.0). Everything should work again.

**Comment by jhfyang** [comment]
@fabpot Thanks a lot !

**Comment by tomislavsantek** [comment]
I'm also having this issue on a fresh install of Symfony 4.4.11 skeleton project.

**Comment by virengawale** [comment]
> I'm also having this issue on a fresh install of Symfony 4.4.11 skeleton project.

Facing same issue

**Comment by fabpot** [comment]
Can you give some more information?

**Comment by ivleneb** [comment]
> 
> 
> > I'm also having this issue on a fresh install of Symfony 4.4.11 skeleton project.
> 
> Facing same issue

Similar issua after "composer update" on symfony 4.4:
Argument 1 passed to
		Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an
		instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of
		Doctrine\Bundle\DoctrineBundle\Registry given

**Comment by fabpot** [comment]
Can you check that you are using the latest version of Symfony Extra Bundle?

**Comment by ivleneb** [comment]
> 
> 
> Can you check that you are using the latest version of Symfony Extra Bundle?

I'm using version 5.2, but in other machine i haven't any problem. I'll try updating to 5.6

**Comment by fabpot** [comment]
You need v5.6.1.

**Comment by ivleneb** [comment]
> 
> 
> You need v5.6.1.

Yes, thank you, now it works.
