### ISSUE TITLE
Duplicate entries in composer.json

### ISSUE THREAD

**Issue by yoannk** [symfony/symfony#37944]
**Symfony version(s) affected**: 5.1.3

**Description**  
I am reading and writing the code in Symfony 5 book, and i noticed i have duplicates entries in `require` and `require-dev` in `composer.json`. I am not sure if this is normal and what i can do to prevent it.

![Annotation 2020-08-25 173355](https://user-images.githubusercontent.com/18040372/91195308-2e85fe80-e6f9-11ea-9c02-64cfd01b01a9.jpg)

**Comment by nicolas-grekas** [comment]
This is likely https://github.com/symfony/flex/issues/597
Closing therefor, PR welcome on flex.
