### ISSUE TITLE
redirectToRoute not working - Submit form and new tab

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#37956]
**Symfony version(s) affected**: 5.1.3
**Chrome version affected**: 84.0.4147.135

**Description**  
I get the impression that `$this->redirectToRoute()` is not working when submitting a form and opening a new tab.

**How to reproduce** 
1. I open a new tab in my browser.
2. I go to `/register`.
3. I submit the form.
4. The page turns in circles.

Here is my code:
```php
    /**
     * @Route("/register", name="register")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, AppAuthenticator $authenticator): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_homepage');
        }

        return $this->render('registration/register.html.twig', [
            'form' => $form->createView(),
        ]);
    }
```

**Comment by ro0NL** [comment]
This looks like a support request ... are you in fact redirected to "app_homepage"? e.g. is the excpected HTTP location header present in the response? Then, why is the homepage redirecting back to /register? This isnt clear based on your issue.

See also https://symfony.com/support

**Comment by seb-jean** [comment]
I am not redirected to `app_homepage`

**Comment by ro0NL** [comment]
Oh right, i misread a bit. So it seems your form is not submitted or invalid ... unless i misunderstood "The page turns in circles.".

**Comment by linaori** [comment]
Most likely scenario is that you're logged out because your security user isn't the same anymore. You're also using `$user` without actually setting this variable, so there are probably pieces of the code you're not showing.

**Comment by fabpot** [comment]
Closing as it looks like an app issue and not a Symfony one.
