### ISSUE TITLE
  [DI] tagged_locator doesn't works with configuration in php

### ISSUE THREAD

**Issue by jfsenechal** [symfony/symfony#37954]
**Symfony version(s) affected**: 5.1.3

**Description**  
 My configuration with  tagged_locator works with configuration in yaml but when I switch to configuration in php
it doesn't work

**How to reproduce**  
I put the code from a symfony skeleton :
https://github.com/jfsenechal/tagged_locator_bug/commit/918aed8ae8ac7ad9886bac726dd491ece6b609b9

Test with command bin/console app:test
I my PostPublish service when I dump property "criteria"

`  public function supports()
    {
        dump($this->criteria->getProvidedServices());
    }`

With config.yaml the 2 services that implement interface CriterionInterface are loaded in my property  "criteria"
but in php config, the property is a empty array

**Comment by nicolas-grekas** [comment]
Thanks for the report, this is an issue in your configuration file.
Configurators are not mutable: you need to store and use the return value of the call to defaults() and instanceof():

```php
[...]
    $services = $services->defaults()
        ->autowire()
        ->autoconfigure();

    $services = $services->instanceof(CriterionInterface::class)
        ->tag('app.post');
[...]
```

**Comment by jfsenechal** [comment]
I'm sorry but I don't understand what I must change in my config.php [https://github.com/jfsenechal/tagged_locator_bug/blob/master/config/services.php](url)

**Comment by chalasr** [comment]
@jfsenechal 

```diff
diff --git a/config/services.php b/config/services.php
index fcef057..966383c 100644
--- a/config/services.php
+++ b/config/services.php
@@ -15,6 +15,9 @@ return static function (ContainerConfigurator $containerConfigurator): void {
         ->autowire()
         ->autoconfigure();
 
+    $services = $services->instanceof(CriterionInterface::class)
+        ->tag('app.post');
+
     $services->load('App\\', __DIR__.'/../src/')
         ->exclude(
             [
@@ -28,9 +31,6 @@ return static function (ContainerConfigurator $containerConfigurator): void {
     $services->load('App\Controller\\', __DIR__.'/../src/Controller/')
         ->tag('controller.service_arguments');
 
-    $services->instanceof(CriterionInterface::class)
-        ->tag('app.post');
-
     $services->set(PostPublish::class)
         ->args([tagged_locator('app.post')]);
 };
```

**Comment by nicolas-grekas** [comment]
Also 
```diff
-    $services->defaults()
+    $services = $services->defaults()
```

**Comment by jfsenechal** [comment]
Ok I dont' see $services **=** 
Thank you ! :-)
