### ISSUE TITLE
$tokenStorage->getToken()->getRoleNames() does not contain IS_IMPERSONATOR

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#37958]
**Symfony version(s) affected**: 5.1.3

**Description**  
ROLE_PREVIOUS_ADMIN has been [deprecated](https://symfony.com/blog/new-in-symfony-5-1-simpler-security-attributes), but `$tokenStorage->getToken()->getRoleNames()` does not contain the new IS_IMPERSONATOR. 

For consistency, the new IS_IMPERSONATOR should be added also to that method, so we'll still be able to detect if the user is an impersonator once ROLE_PREVIOUS_ADMIN is removed, and we're outside the controller so we don't have access to the isGranted method (for example inside a onKernelTerminate listener). 

Or are we supposed to use `$token instanceof SwitchUserToken`? I didn't see that mentioned in any docs.

The Symfony profiler as well doesn't contain the new attribute:
![image](https://user-images.githubusercontent.com/8755314/91329773-3c0eb780-e7d1-11ea-9e0f-cf25851865c5.png)

**Comment by wouterj** [comment]
There is a difference between *Security attributes* and *roles*. A security attribute is whatever you pass to `isGranted()`. It activates a voter that checks whether someone is granted something or not. A security role is just someones "role" on that website (e.g. "I'm admin" or "I'm just a user").

By default, every attribute starting with `ROLE_` is checked by the `RoleVoter`, which uses the role of the user to detect whether or not they are allowed a certain action. However, attributes are by no other means related to roles.

The new `IS_IMPERSONATOR` *attribute* is checked by the `AuthenticatedVoter` based on the type of token, it is not a user role.

See https://symfony.com/doc/current/security/securing_services.html on how to use `isGranted()` when you're not extending from `AbstractController` (e.g. in your event listener). See https://wouterj.nl/2020/01/grant-on-permissions-not-roles (sorry for the shameless self promotion) for a blog post explaining the differences a bit more in detail.

**Comment by fmonts** [comment]
Thank, I'll close the issue
