### ISSUE TITLE
[Console] PHP 7.4: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by CWX-iggy** [symfony/symfony#37969]
**Symfony version(s) affected**: 3.4.43

**Description**  

I have a phpunit test that calls a symfony console command.
```
 $result = $this->command->run(
    $this->input,
    $this->output->get()
);
```
Input is:
```
$this->input = new ArgvInput(
    [
        'admin:reserve',
        '12345',
        250,
        3,
        4,
    ]
);
```
Error on running test.
```
ErrorException: Trying to access array offset on value of type int

****/vendor/symfony/console/Input/ArgvInput.php:83
```
**How to reproduce**  

**Possible Solution**  

If I change the input args to string literals, it works, but that breaks my test and the functionality of the command, as it expects integer values for those arguments.

The offending line is:
```
protected function parse()
{
...
    } elseif ($parseOptions && '-' === $token[0] && '-' !== $token) {
...
}
``` 
Should possibly be:
```} elseif ($parseOptions && 0 === strpos($token,'-') && '-' !== $token) {```

**Additional context**  

I have a number of external project dependencies that also rely on `symfony/console@^3`

**Comment by lyrixx** [comment]
IMHO, Your test is wrong since it does not reflect the reality. In CLI all arguments are strings. In your test, you are using an integer. If your code need an integer, you should cast the argument from string to int in your application.

**Comment by nicolas-grekas** [comment]
We could still make the code more resilient.
@CWX-iggy up for submitting a PR (with tests of course)?
If not, we could close also.

**Comment by CWX-iggy** [comment]
@nicolas-grekas  thanks. I try and get a PR submitted at some stage. For now, I have just fixed the tests.

**Comment by nicolas-grekas** [comment]
I'm closing meanwhile. PR welcome when you can.
