### ISSUE TITLE
form package is missing

### ISSUE THREAD

**Issue by trottera** [symfony/symfony#37975]
hi,

i was trying to create a new project using composer:
composer create-project symfony/website-skeleton .

The script executes without an error. But if i try to create a form afterwards by executing php bin/console make:form,
there's an error message:

[ERROR] Missing package: to use the make:form command, run:

         composer require form

Running composer require form doesn't help, because there's "nothing to install or update".

Also, there seems to be an "subset" of the files in vendors/symfony/form. The only files in this directory are:

    FormTypeInterface.php
    FormView.php
    Guess/
    LICENSE
    NativeRequestHandler.php
    PreloadedExtension.php
    README.md
    RequestHandlerInterface.php
    ResolvedFormType.php
    ResolvedFormTypeFactory.php
    ResolvedFormTypeFactoryInterface.php
    ResolvedFormTypeInterface.php
    Resources/
    ReversedTransformer.php
    SubmitButton.php
    SubmitButtonBuilder.php
    SubmitButtonTypeInterface.php
    Test/
    Util/

I tried this with both the 5.1.* and the 4.4 version of symfony.

**Comment by ro0NL** [comment]
Having a "subset" of files in vendor/ doesnt seem right ... can you try a fresh composer install?

**Comment by trottera** [comment]
reinstalled composer as described [here](https://getcomposer.org/download/).
Still the same outcome

**Comment by ro0NL** [comment]
srry, i meant a fresh `composer install` :sweat_smile: 

e.g.

```
rm -rf vendor
composer install
```

**Comment by trottera** [comment]
i tried it with `composer install` and `composer install --no-cache`

still, nothing has changed

**Comment by ro0NL** [comment]
that's weird. Id argue something's wrong with composer, so it's most likely something else :) better ask for support then, see https://symfony.com/support

At this point i doubt anything's wrong with the code.

**Comment by fabpot** [comment]
Closing as it cannot be related to Symfony itself.
