### ISSUE TITLE
In Symfony 5.1 Kernel.php replacing RouteCollectionBuilder with RoutingConfigurator causes Routing failure

### ISSUE THREAD

**Issue by mehmetsen80** [symfony/symfony#37996]
**Symfony version(s) affected**: 5.1

**Description**  
When I replace RouteCollectionBuilder with RoutingConfigurator to avoid deprecation, it causes loosing all routing

**How to reproduce**  
Go to Kerne.php, replace RouteCollectionBuilder with RoutingConfigurator, then run php bin/console debug:router. You won't see any routing listed

**Possible Solution**  
My guess is it looses its annotation config. It might forces to use config for routing instead of annotation

**Additional context**  
No router is listed when I run this:
$ php bin/console debug:router
  Name                                  Method   Scheme   Host   Path

**Comment by xabbuh** [comment]
Can you show the full code of your `Kernel` class please?

**Comment by wouterj** [comment]
Did you also take care of updating some method usages? Both classes have different methods and method arguments, which can cause things to be ignored.

**Comment by mehmetsen80** [comment]
Here is the Kernel.php I have

```
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\Config\Resource\FileResource;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Component\Routing\RouteCollectionBuilder;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    const CONFIG_EXTS = '.{php,xml,yaml,yml}';

    public function getCacheDir()
    {
        return $this->getProjectDir().'/var/cache/'.$this->environment;
    }

    public function getLogDir()
    {
        return $this->getProjectDir().'/var/log';
    }

    public function registerBundles()
    {
        $contents = require $this->getProjectDir().'/config/bundles.php';
        foreach ($contents as $class => $envs) {
            if (isset($envs['all']) || isset($envs[$this->environment])) {
                yield new $class();
            }
        }
    }

    protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
    {
        $container->addResource(new FileResource($this->getProjectDir().'/config/bundles.php'));
        // Feel free to remove the "container.autowiring.strict_mode" parameter
        // if you are using symfony/dependency-injection 4.0+ as it's the default behavior
        $container->setParameter('container.autowiring.strict_mode', true);
        $container->setParameter('container.dumper.inline_class_loader', true);
        $confDir = $this->getProjectDir().'/config';

        $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}_'.$this->environment.self::CONFIG_EXTS, 'glob');
    }

    protected function configureRoutes(RouteCollectionBuilder $routes)
    {
        $confDir = $this->getProjectDir().'/config';

        $routes->import($confDir.'/{routes}/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}'.self::CONFIG_EXTS, '/', 'glob');
    }
}
```

As I said, if you change RouteCollectionBuilder to RoutingConfigurator  then run php bin/console debug:router won't list any routes. It's like the annotation rotuing is not recognized anymore. 

@wouterj No I haven't updated any method usage

**Comment by jschaedl** [comment]
@mehmetsen80 

The `RoutingConfigurator::import(...)` method has different arguments than the`RouteCollectionBuilder::import(...)` method:
See:
https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/Routing/Loader/Configurator/RoutingConfigurator.php#L39

https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/Routing/RouteCollectionBuilder.php#L62

Just change your `configureRoutes()` method to something like this and it should work as expected:

```php
protected function configureRoutes(RoutingConfigurator $routes): void
{
    $confDir = $this->getProjectDir() . '/config';

    $routes->import($confDir . '/{routes}/*' . self::CONFIG_EXTS);
    $routes->import($confDir . '/{routes}/' . $this->environment . '/**/*' . self::CONFIG_EXTS);
    $routes->import($confDir . '/{routes}' . self::CONFIG_EXTS);
}
```

**Comment by xabbuh** [comment]
closing as explained, please comment if this doesn't help and ideally provide a small example application then that allows us to reproduce the issue

**Comment by mehmetsen80** [comment]
Thank u it worked!
