### ISSUE TITLE
Avoid using is_subclass_of for primitive types

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#37992]
**Symfony version(s) affected**: master

**Description**  
When a controller accepts type hinted arguments of primitive types (int, bool, array, etc) the `RequestValueResolver` still tries to resolve them using `is_subclass_of` which triggers autoloader.
https://github.com/symfony/symfony/blob/v5.1.3/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestValueResolver.php#L30

Loading classes is rather expensive operation in terms of performance. 

**Possible Solution**  
Check if an argument is of primitive type before calling `is_subclass_of`.

**Comment by fabpot** [comment]
Have you been able to notice a significant performance impact?

**Comment by Chi-teck** [comment]
On my environment (without Xdebug and DebugClassLoader) it costs 0.007 ms for each argument resolving. That's not significant, of course.

**Comment by nicolas-grekas** [comment]
I don't think there is any benefit in doing so...

**Comment by fabpot** [comment]
Let's close then.

**Comment by nicolas-grekas** [comment]
@Chi-teck if you really think we should do something here, please send a PR with the improvement (no need to keep an issue open for a while as you might have understood.)
