### ISSUE TITLE
[Notifier] DataCollector for Notifier component not available

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#38009]
**Symfony version(s) affected**: 5.1.4

**Description**  

For me it currently looks the DataCollector for the `notifier` component is not registered?

**How to reproduce**  

```php
$client->enableProfiler();
$client->request('POST', '/api/...');

$profile = $client->getProfile();
$profile->getCollector('notifier'); // there seems not exist any data collector for notifier component?
```

**Possible Solution**  

Not sure for me it seems like the [NotificationLoggerListener](https://github.com/symfony/symfony/blob/v5.1.4/src/Symfony/Component/Notifier/EventListener/NotificationLoggerListener.php) and [NotificationDataCollector](https://github.com/symfony/symfony/blob/v5.1.4/src/Symfony/Component/Notifier/DataCollector/NotificationDataCollector.php) are never registered, not sure how they should be registered.

**Comment by jschaedl** [comment]
I can confirm that the `NotificationLoggerListener` and `NotificationDataCollector` 
 are not registered. I ran into the same issue while working on https://github.com/symfony/symfony/pull/36479
