### ISSUE TITLE
[Doctrine Bridge] Throw exception on validate anonymous class

### ISSUE THREAD

**Issue by ZhukV** [symfony/symfony#38008]
**Symfony version(s) affected**: >= 3.4.*

**Description**  
System throw exception if we try to validate anonymous class. Exception throwed from Doctrine Class MetadataFactory, but not catch in Doctrine Bridge.

**How to reproduce**  
```php
<?php

namespace Acme;

use Plutus\Kernel;
use Symfony\Component\Validator\Constraints as Assert;

include __DIR__.'/config/bootstrap.php';
$kernel = new Kernel('dev', true);
$kernel->boot();

class ParentObject
{
    /**
     * @var string
     *
     * @Assert\NotBlank()
     */
    public $name;
}

class ChildObject extends ParentObject  {
}

$validator = $kernel->getContainer()->get('validator');

$constraints = $validator->validate(new ParentObject());
var_dump($constraints);

$constraints = $validator->validate(new ChildObject());
var_dump($constraints);

$constraints = $validator->validate(new class () extends ParentObject{});
var_dump($constraints);
```

**Possible Solution**  
Root problem on Doctrine side: https://github.com/doctrine/persistence/blob/2.0.x/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php#L160
In this method we retrieve `class@anonymous/code/test.php:33$0` and `strpos` returns true.

1. Fix on Doctrine side for correct process anonymous classes.
2. Catch `ORMException` error on DoctrineBridge side, but `ORMException` is a general error on Doctrine and as result we must additional check message error on catching.

**Comment by xabbuh** [comment]
IMO having this fixed in Doctrine is enough.

**Comment by greg0ire** [comment]
If anybody can get a stack trace for this, please post it at https://github.com/doctrine/persistence/issues/24

More on what a stack trace is and how to get one at https://github.com/symfony/symfony-docs/pull/13699/files

**Comment by marcortola** [comment]
IMHO it is not the responsibility of doctrine, it is the responsibility of the validator Metadata Factory.

I think an additional check should be added before reaching the get_class function:
https://github.com/symfony/symfony/blob/76c22fab021c006262a6ef20532c052072a2cebe/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php#L74-L78

As a temporary fix, I have chosen to decorate the ValidatorBuilder to inject this decorated LazyLoadingMetadataFactory: 
```php
final class LazyLoadingMetadataFactory implements MetadataFactoryInterface
{
    private MetadataFactoryInterface $decorated;

    public function __construct(MetadataFactoryInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function getMetadataFor($value)
    {
        $this->assertNotAnonymousClass($value);

        return $this->decorated->getMetadataFor($value);
    }

    public function hasMetadataFor($value)
    {
        try {
            $this->assertNotAnonymousClass($value);
        } catch (NoSuchMetadataException $e) {
            return false;
        }

        return $this->decorated->hasMetadataFor($value);
    }

    /**
     * @param mixed $value
     */
    private function assertNotAnonymousClass($value): void
    {
        if ($this->isAnonymousClass($value)) {
            throw new NoSuchMetadataException(
                sprintf('Cannot create metadata for anonymous classes. Got: "%s".', \gettype($value))
            );
        }
    }

    /**
     * @param mixed $value
     */
    private function isAnonymousClass($value): bool
    {
        return \is_object($value) && (new \ReflectionClass($value))->isAnonymous();
    }
}
```
