### ISSUE TITLE
How to directly create an object as a service call？

### ISSUE THREAD

**Issue by lanrenbulan** [symfony/symfony#38005]
How can I directly create an object instance in a certain way, this object is a task handler, , the processor of each task may be different. Is it similar to the method of Yii::createObject(). I don’t want to register handlers in service.yarml, because there may be many handlers.

I want this:
```
$task = new Task;
// $handler = $this->container->get($task->getHandlerName()); 
$handler = createObject($task->getHandlerName());
$handler->handle($task);
```

// Handler

```
class MyHandler {
     private $manager;

      // autowiring
     public function __construct(EntityManagerInterface $manager) {
            $this->manager = $manager;
     }
     public function handle() {

     }
}
```

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
