### ISSUE TITLE
Can not update symfony/amazon-mailer and symfony/validator to 5.1.4

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#38000]
**Symfony version(s) affected**: 5.1.4

**Description**  
https://packagist.org/packages/symfony/amazon-mailer#v5.1.4
https://packagist.org/packages/symfony/validator#v5.1.4
Amazon-Mailer 5.1.4 needs symfony/mailer:^5.2 which has not yet been released.
Validator 5.1.4 needs symfony/deprecation-contracts: ^2.0 

**How to reproduce**  
composer.json for symfony/amazon-mailer
```
...
 "symfony/amazon-mailer": "^5.1",
 "symfony/mailer": "^5.1",
...
```

composer.json for symfony/validator
```
...
 "symfony/deprecation-contracts": "^2.1",
 "symfony/validator": "^5.1",
...
```

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
Can you please send a PR to fix this ?

**Comment by michaljusiega** [comment]
Yes - I can :)

**Comment by derrabus** [comment]
There is also another problem with the Validator component: It has a conflict rule `"symfony/phpunit-bridge": "^5.1"`, so composer will refuse to install it if PhpUnitBridge is present in a up-to-date version.

**Comment by rmikalkenas** [comment]
> There is also another problem with the Validator component: It has a conflict rule `"symfony/phpunit-bridge": "^5.1"`, so composer will refuse to install it if PhpUnitBridge is present in a up-to-date version.

Did a workaround:
- defined `"symfony/phpunit-bridge": "^5.0"`
- added `"extra": {"symfony": {"require": "5.1.*"}}`
- then run composer update with the result: `Downgrading symfony/phpunit-bridge (v5.1.3 => v5.0.11)` and all the rest components: `v5.1.3 => v5.1.4`

but not sure if its a good way to do that

**Comment by michaljusiega** [comment]
I think the error to `symfony/validator` is due to `symfony/deprecation-contracts` invalid contraint. But I can be wrong.
