### ISSUE TITLE
Why is not REQUEST_TIME_FLOAT set by default when constructing a Request object?

### ISSUE THREAD

**Issue by imanoleguskiza** [symfony/symfony#38019]
When creating a Symfony\Component\HttpFoundation\Request object several server parameters are set, including REQUEST_TIME. However, the float equivalent REQUEST_TIME_FLOAT is not set. I tried looking for documentation about this to no avail. Is this intentional? Could we open a feature request to include it?

**Comment by xabbuh** [comment]
I can imagine that `REQUEST_TIME_FLOAT` wasn't a thing when the class was initially written (this field was added in PHP 5.4).
