### ISSUE TITLE
Notice: unserialize() Error xxxx

### ISSUE THREAD

**Issue by botjaeger** [symfony/symfony#38027]
**Symfony version(s) affected**: 4.4.x

**Description**  
I'm just doing some simple update operation with EasyAdmin bundle (2.x) then suddenly may web profiler is not displaying properly.

By checking the logs I saw these

`request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: unserialize(): Error at offset 8297041 of 8297041 bytes" at /var/www/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 126 {"exception":"[object] (ErrorException(code: 0): Notice: unserialize(): Error at offset 8297041 of 8297041 bytes at /var/www/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:126)"} []`

**How to reproduce**  
default configs

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
We would need more info to be able to decide if this is a bug or something else.
Please provide a reproducer ideally.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
