### ISSUE TITLE
[Form] Usage of `Valid` constraint on simple form type breaks property path resolving

### ISSUE THREAD

**Issue by lchrusciel** [symfony/symfony#38039]
**Symfony version(s) affected**: ^v3.4.41, ^v4.4.9, ^v5.0.9 

**Description**  
Hello folks 👋 

I'm bringing to you kind of edge case. Since v3.4.41(and upmerged releases) usage of `Valid` constraint on simple form types (relating directly to the field instead of encapsulating another object) like ChoiceType, TextType, or IntegerType breaks property path resolution of other fields with a `Valid` constraint. This happens only if a particular field passes validation, and another field is failing. Everything works as expected if both fields are valid or invalid. As a result, the error message cannot be displayed on the right field, though the form is still correctly validated. 

To illustrate this issue, let's validate ReviewForm from Sylius. It contains 4 fields: rating, title, description, and author. Rating(for whatever reason) and author have defined `'constraints' => Valid()`. If one would submit an empty form, this is the result:
![image](https://user-images.githubusercontent.com/6213903/92019355-c8335880-ed56-11ea-9346-82d3026d2a66.png)
and the validator calls:
![image](https://user-images.githubusercontent.com/6213903/92019376-d2555700-ed56-11ea-8b32-682acb584eaa.png)
everything works as expected.
However, if the rating field would be filled, this is the current result:
![image](https://user-images.githubusercontent.com/6213903/92019617-34ae5780-ed57-11ea-9d53-753fc672f896.png)
and the validator calls:
![image](https://user-images.githubusercontent.com/6213903/92019646-3f68ec80-ed57-11ea-9f4d-9557dcf70846.png)

As you can see, in the second example, `children[author].data.email` is replaced with `[author].data.email`, which cannot be mapped to the form.

**How to reproduce**  
The bug is reproduced here: https://github.com/symfony/symfony/commit/053d8fb2df4250980aa2b23d5935bd8a6cd3ecf2.

In the attached commit, only one test will fail with the following result:
![image](https://user-images.githubusercontent.com/6213903/92020154-02e9c080-ed58-11ea-8f40-59dbdbaaba4e.png)

**Possible Solution**  
I assume there is one wrong if statement in `FormValidator`, which be fixed. Nonetheless, I wasn't able to spot it.

Since I've fixed our build by removing the `new Valid()` constraint, I'm not sure if I should commit more energy into it. I can help you with solving it if you find this particular problem worth solving and if you give me some guidance. 

**Additional context**  
The bug was introduced somewhere here: https://github.com/symfony/form/compare/v4.4.8...v4.4.9, probably by this commit: https://github.com/symfony/form/commit/48ec67571d7d83bd16a13036f120e954bcbc5a67
The problem may be solved on our end with the removal of probably unnecessary `new Valid()` constraint.

I'm openining this issue, as it is affected by wrong configuration in the first place and I'm not sure if there is a point in fixing it. Nevertheless, the "wrong" configuration was working properly since [November 2016 and since version 3.0.0](https://github.com/Sylius/Sylius/pull/6821/files#diff-c1b4cd814ddaeb8d78ef496f97836b5aR57) until version 4.4.9.

**Comment by xabbuh** [comment]
Thanks for opening this issue. I agree that there is at least some confusing behavior. Your example greatly allows to reproduce it and I am currently trying to understand what is going.

**Comment by xabbuh** [comment]
see #39333

**Comment by lchrusciel** [comment]
Great! Thank you a lot :) As you've used my test case, does it mean I've become a Symfony contributor? :D

**Comment by xabbuh** [comment]
For the record, this seems to have been broken in #36865. Previously, we didn't properly cascade into nested forms which means that misconfigurations like the one from the failing test case went unnoticed.

@lchrusciel Yes, congratulations to your first contribution. :)
