### ISSUE TITLE
TypeError in symfony 4.4.13 on php 7.1

### ISSUE THREAD

**Issue by GaneshKandu** [symfony/symfony#38042]
**Symfony version(s) affected**: 4.4.13

**Description**  
```composer create-project symfony/website-skeleton symfony4413 4.4.99```
when i install symfony 4.4.13 on php 7.1 using composer i get error
```
Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in var/cache/dev/ContainerDPswZhH/srcApp_KernelDevDebugContainer.php on line 4507
```

**How to reproduce**  
install symfony 4.4.13 on php 7.1 using composer

**Possible Solution**  
when i install symfony 4.4.13 on php 7.1 using composer it cause error but when i install 4.4.13 on php 7.2 it works probably you need to change minimum php requirement 

or 

resolve problem for php 7.1  

**Additional context**  
installing symfony 4.4.13 on php 7.2 using composer works
but not on 7.1

if i install synfony on php 7.1 and after i delete cache and update php to 7.2 then also it doesn't work

**Comment by xabbuh** [comment]
Does updating SensioFrameworkExtraBundle to 5.6.1 resolve the issue?

**Comment by GaneshKandu** [comment]
```
  Problem 1
    - Installation request for sensio/framework-extra-bundle 5.6.1 -> satisfiable by sensio/framework-extra-bundle[v5.6.1].
    - sensio/framework-extra-bundle v5.6.1 requires php >=7.2.5 -> your PHP version (7.1.33) does not satisfy that requirement.
```

**Comment by xabbuh** [comment]
Can you report that over at the [SensioFrameworkExtraBundle repository](https://github.com/sensiolabs/SensioFrameworkExtraBundle/) please? This needs to be fixed in the bundle. There's nothing we can do in Symfony about it.

**Comment by GaneshKandu** [comment]
OK,
Symfony's dependency required "php": ">=7.2.5" and Symfony 4.4.13 required "php": ">=7.1.3"
