### ISSUE TITLE
[Validator] ConstraintValidatorTestCase regression

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#38048]
**Symfony version(s) affected**: 5.1.4

**Description**  

After the last update a problem appeared in one of my tests.

It's a test case for my custom constraint validator. I'm using extending the `ConstraintValidatorTestCase` from Symfony to make things easier.

The validator itself does some logic and delegates the validation to some other constraint like this:

```php
		$this->context
			->getValidator()
			->inContext($this->context)
			->atPath($this->context->getPropertyPath())
			->validate(...);
```

So in the test I need mock the ContextualValidator a little bit which worked fine until recently but now triggers this error:

```
Trying to configure method "atPath" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

**How to reproduce**  

```php
final class MyValidatorTest extends ConstraintValidatorTestCase
{
	public function testValidate(): void
	{
		/** @var MockObject $contextualValidator */
		$contextualValidator = $this->context->getValidator()->inContext($this->context);
		$contextualValidator
			->method('atPath')
			->willReturnSelf();

		// ...
	}

	protected function createValidator(): MyValidator
	{
		return new MyValidator();
	}
}
```

**Comment by enumag** [comment]
The BC break appeared in version 5.1.4. Most likely some of the [changes](https://github.com/symfony/validator/compare/v5.1.3...v5.1.4#diff-fddc91c5746b37f30922bd4780bf2217) in the ConstraintValidatorTestCase class.

**Comment by xabbuh** [comment]
Can you confirm that #38131 fixes this issue?

**Comment by enumag** [comment]
@xabbuh Not easily since it targets 3.4 while I'm on 5.1. I'll have to copy paste the individual changes when I have more time...
