### ISSUE TITLE
Serializer 5.1 Breaking Changes

### ISSUE THREAD

**Issue by oojacoboo** [symfony/symfony#38050]
**Symfony version(s) affected**: 5.1.5

**Description**  
After updating to 5.1.5 from 5.0.11, things are now broken on a lib we're maintaining.  I'm unable to locate a changelog outside of parsing through the commit history, or a list of breaking changes.

The issues exists when deserializing a nested associative array into a Collection of specific objects.  I tried a number of things to locate the issue, but honestly, this component is a black box.  All of the property overloading, reflection, etc. make it very difficult to debug, especially when you're not already familiar with the component, as is the case for myself.

**How to reproduce**  
The lib in question is:
https://github.com/rentpost/forte-payments-php

Unfortunately it'd be a bit difficult to run the integration tests that are causing issues without API keys.

**Comment by xabbuh** [comment]
I am afraid we won't be able to help without being able to reproduce. Could you please create a small example application that allows to do so?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
