### ISSUE TITLE
Exception "Symfony\Component\String\UnicodeString" requires a translit-able iconv implementation...

### ISSUE THREAD

**Issue by Surfoo** [symfony/symfony#38060]
**Symfony version(s) affected**: 5.1.5

**Description**  
With **Windows 8** and **PHP 7.4**, an exception is thrown: 

Here the phpinfo if needed : https://gist.github.com/Surfoo/293c14052c882c08bfab1368af38a3e7
```
Exception "Symfony\Component\String\UnicodeString" requires a translit-able iconv implementation, try installing "gnu-libiconv" if you're using Alpine Linux.
```
![Exception](https://user-images.githubusercontent.com/553659/92234749-e2824900-eeb2-11ea-879a-64decf596661.png)

**How to reproduce**

In a controller : 

     dd((string) $this->slugger->slug('🐎 test unicode character'));

**Comment by notFloran** [comment]
I have the same issue with macOS Catalina and homebrew:

`php -v`:

```
PHP 7.4.10 (cli) (built: Sep  3 2020 18:21:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
    with blackfire v1.39.1~mac-x64-non_zts74, https://blackfire.io, by Blackfire
```

`php --ri iconv`:

```
iconv

iconv support => enabled
iconv implementation => libiconv
iconv library version => 1.11

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value
```

I try https://github.com/symfony/symfony/pull/38195 and no changes.

**Comment by nicolas-grekas** [comment]
What's the output of this on your machine?
```php
echo iconv('UTF-8', 'ASCII//TRANSLIT', '²');
echo iconv('UTF-8', 'ASCII//TRANSLIT', 'é');
```

**Comment by notFloran** [comment]
Result:

```
php > echo iconv('UTF-8', 'ASCII//TRANSLIT', '²');
^2
php > var_dump(iconv('UTF-8', 'ASCII//TRANSLIT', 'é'));
string(2) "'e"
```

**Comment by nicolas-grekas** [comment]
Thanks, can you try #38195 again?

**Comment by notFloran** [comment]
> Thanks, can you try #38195 again?

It's good 👍 , thanks
