### ISSUE TITLE
[Cache] TagAwareAdapter not invalidating items when used with ProxyAdapter

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#38066]
**Symfony version(s) affected**: 4.4.11+

**Description**  
Its related to https://github.com/symfony/symfony/issues/37667

I actually stumbled upon another issue with the `TagAwareAdapter`. 

When we wrap an adapter into a `ProxyAdapter` and use that as the `tagsPool` then items are not invalidated.

**How to reproduce**  
```php
public function testClearsCacheProperly(): void
{
    $arrayAdapter = new \Symfony\Component\Cache\Adapter\ArrayAdapter();

    $adapter = new \Symfony\Component\Cache\Adapter\TagAwareAdapter(
        $arrayAdapter,
        new \Symfony\Component\Cache\Adapter\ProxyAdapter($arrayAdapter, 'some_namespace')
    );
    $item = $adapter->getItem('foo');

    $this->assertFalse($item->isHit());

    $item->tag('bar');
    $item->expiresAfter(100);
    $adapter->save($item);

    $this->assertTrue($adapter->getItem('foo')->isHit());

    $adapter->invalidateTags(['bar']);

    // this fails on 4.4.11+ and passes on 4.4.10
    $this->assertFalse($adapter->getItem('foo')->isHit());
}
```

**Additional context**  
I guess it might also be caused by https://github.com/symfony/symfony/pull/37562

ping @philipp-kolesnikov any chance you can help out here?

**Comment by nicolas-grekas** [comment]
What about https://github.com/symfony/symfony/issues/37950 which has been fixed more recently?

**Comment by dmaicher** [comment]
> What about #37950 which has been fixed more recently?

It was fixed by https://github.com/symfony/symfony/pull/37671, right? I tried `4.4.12`. Same result.

**Comment by dmaicher** [comment]
> Th current version is 4.4.13

Yes but the fix was released in 4.4.12 :wink: Anyway I also tested 4.4.13. Same.

**Comment by nicolas-grekas** [comment]
Ok :)
Can you please send the reproducer as a test case ? That would ease following up.

**Comment by dmaicher** [comment]
@nicolas-grekas you mean something like this?

https://github.com/symfony/symfony/compare/4.4...dmaicher:reproducer_38066?expand=1

Interestingly that test passing on 3.4 (but failing on 4.4) :thinking:
