### ISSUE TITLE
"Sqlite platform does not support alter foreign key. the table must be fully recreated using getAlterTableSQL."

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#38067]
**Symfony version(s) affected**: 5.1.5

**Description**  
When trying to create a migration using the maker bunder, with sqlite as the database: I get this error. in In SqlitePlatform.php line 827

```
"Sqlite platform does not support alter foreign key, the table must be fully recreated using getAlterTableSQL."
```

**How to reproduce**  
- Create a few simple entities with a manytoone relationship,, set up the `.env` file for sqlite, then attempt to make:migrate.

**Additional context**  
PHP 7.4.3

**Comment by beberlei** [comment]
@ChangePlaces which version is doctrine/dbal at in your setup? Call `composer show doctrine/dbal`. Also can you add the full stack trace of the exception, call the maker bundle command with `-v`

**Comment by MarcelKr** [comment]
I'm having the same problem. 

- Created the project yesterday with `~/.symfony/bin/symfony new --full .`
- `doctrine/dbal` Version: `versions : * 2.10.3`
- relevant line in `.env`: `DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db`
- PHP 7.4.10

Full `make:migration -v` output:

```
$ php bin/console make:migration -v

In SqlitePlatform.php line 827:
                                                                                                                 
  [Doctrine\DBAL\DBALException]                                                                                  
  Sqlite platform does not support alter foreign key, the table must be fully recreated using getAlterTableSQL.  
                                                                                                                 

Exception trace:
  at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php:827
 Doctrine\DBAL\Platforms\SqlitePlatform->getDropForeignKeySQL() at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:121
 Doctrine\DBAL\Schema\SchemaDiff->_toSql() at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:101
 Doctrine\DBAL\Schema\SchemaDiff->toSql() at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:442
 Doctrine\DBAL\Schema\Schema->getMigrateFromSql() at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/DiffGenerator.php:94
 Doctrine\Migrations\Generator\DiffGenerator->generate() at /home/marcel/Projekte/02_WEB/scheduly/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php:145
 Doctrine\Migrations\Tools\Console\Command\DiffCommand->execute() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/maker-bundle/src/Maker/MakeMigration.php:93
 Symfony\Bundle\MakerBundle\Maker\MakeMigration->generate() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/maker-bundle/src/Command/MakerCommand.php:104
 Symfony\Bundle\MakerBundle\Command\MakerCommand->execute() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/console/Application.php:934
 Symfony\Component\Console\Application->doRunCommand() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/marcel/Projekte/02_WEB/scheduly/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /home/marcel/Projekte/02_WEB/scheduly/bin/console:43

make:migration [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by greg0ire** [comment]
Does the issue go away if you install `doctrine/dbal` 2.10.2?

**Comment by MarcelKr** [comment]
Works with `2.10.2` :+1:

**Comment by fabpot** [comment]
Closing then

**Comment by MarcelKr** [comment]
@fabpot shouldn't the dependencies be correctly set while using the symfony installer? Right now it's leaving you with a broken installation which isn't great I think.

**Comment by onokje** [comment]
same issue here: fixed when downgrading `doctrine/dbal` to 2.10.2. 
2.10.3 seems to brake it.

**Comment by ChangePlaces** [comment]
uhm, so the problem hasn't been fixed or what?

**Comment by greg0ire** [comment]
It hasn't been fixed, but it does not have to do with Symfony, it has to do with Doctrine.

>  shouldn't the dependencies be correctly set while using the symfony installer? Right now it's leaving you with a broken installation which isn't great I think.

You can contribute something like https://github.com/laravel/framework/issues/34093#issuecomment-687014642 if you want to address this.

**Comment by ChangePlaces** [comment]
but it causes a problem with symfony as you have a broken install (the problem), so this issue hasn't been fixed.

**Comment by wouterj** [comment]
Feel free to submit the fix :)

**Comment by nicolas-grekas** [comment]
Or at least open an issue on the proper repository so that the correct persons can track it following their processes. As far as this repo is concerned, the issue should be closed, there's nothing we can do about it here.

**Comment by greg0ire** [comment]
Absolutely! Please report this to `doctrine/dbal`, with a stack trace, much like @MarcelKr did. If you don't know how to get a stack trace, you can read https://github.com/symfony/symfony-docs/pull/13699/files
A minimal reproducer project on Github would help a lot too.
