### ISSUE TITLE
[HttpClient] Inconsistent interface for adding headers with/out file uploads

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#38082]
**Description**  
Usually you add a header like this - see https://symfony.com/doc/current/http_client.html#headers
```php
$response = $client->request('POST', 'https://...', [
    'headers' => [
        'User-Agent' => 'foo',
    ],
]);
```

But how can you add a header when doing a file upload? https://symfony.com/doc/current/http_client.html#uploading-data doesn't say anything about this, so I'm guessing:
```php
$headers = $formData->getPreparedHeaders()->toArray();
$headers[] = 'User-Agent: foo';
```
Questions:
1. Is this really the best way to do it? => If yes, I'd come up with a PR to add this to the docs
2. Notice the inconsistent syntax: associative array vs. indexed array. So what about a `addHeader` method that works in all cases?
3. (somewhat off-topic) It would be nice to have a method to override the config from `framework.yaml` for the *client* (not the request). My use case: I'm doing `$client-request()` multiple times, and I need the same User-Agent for all of them. The string is dynamic (so I can't set it in `framework.yaml`), but it's the same for every PHP session, so something like `$client->setOptions(...)` would work.

**Comment by ThomasLandauer** [comment]
Another example for 3 would be `base_url`.

**Comment by nicolas-grekas** [comment]
> Is this really the best way to do it? => If yes, I'd come up with a PR to add this to the docs

Yes. all syntaxes are allowed exactly for this: to ease with different styles depending on the situation. Consistency is on the side of the consumer, if it matters.

> So what about a addHeader method that works in all cases?

Could be added to the `HttpOptions` class if you want to have a look.

> something like $client->setOptions(...) would work.

there is another way that frees us from having a mutable service (which would be no-go): use decoration.

Something like that:
```php
$configuredClient = new ScopingHttpClient($injectedClient, ['.*' => ['headers' => ['User-Agent' => 'foo']]]);
```

If this is common enough, we might consider a factory method in `ScopingHttpClient`?

**Comment by nicolas-grekas** [comment]
Closing as explained.
