### ISSUE TITLE
[HttpClient] Failed to parse address "0"

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#38081]
**Symfony version(s) affected**: 4.4+

**Description**  
Using the native HTTP client on php 7.3.22 and 7.4.10 produces the following error:

```
fopen(http://some/url): Failed to open stream: Failed to parse address "0"
```

**How to reproduce**  
Run the test suite on php 7.3.22 or 7.4.10.

**Possible Solution**
Either:
* Change the default value for `bindto` in the contract from `0` to `0:0`.
* Implement a workaround that removes `bindto` from the stream context is it has been set to `0`.
* Implement a workaround that adds `:0` is the port is missing.
* Fix php and restore the previous behavior. 

**Additional context**  
The problem seems to be that `fopen` fails if we provide an address without a port as `bindto` inside the stream context. This is unfortunate because HttpClient uses `0` as a default value, which means that if we don't explicitly set a value here, the request will fail. The default value is provided by the contract's `ClientInterface`. Changing it to `0:0` makes the tests pass again.

This change has been introduced with php 7.3.22/7.4.10. Running the test suite on php 7.3.21 or 7.4.9 works fine.

**Comment by derrabus** [comment]
I've filed this issue as a php bug as well: https://bugs.php.net/bug.php?id=80067

**Comment by derrabus** [comment]
@nicolas-grekas Your PR that has just been merged fixes the default case with `bindto = 0`.

For the record: code that uses an actual IP address without a port (e.g. `bindto = 192.168.0.1`) here will still fail. Adding the zero-port (`bindto = 192.168.0.1:0`) again fixes the issue.

**Comment by nicolas-grekas** [comment]
> Adding the zero-port (bindto = 192.168.0.1:0) again fixes the issue

can you please comment on the php bug report that this change also for non -0 addresses?

**Comment by nicolas-grekas** [comment]
Apparently, the `bindto` option might need some more love:
- in curl, the port info is ignored as we don't use [`CURLOPT_LOCALPORT`](https://curl.haxx.se/libcurl/c/CURLOPT_LOCALPORT.html )
- in native client (and in amp consequently), I agree we would add `:0` explicitly with the port is missing

@derrabus up to give it a try?

**Comment by derrabus** [comment]
Yes, I can look into this later this week.

**Comment by YetiCGN** [comment]
Thanks, Alex! I just came across this after a package update where suddenly the communication from symfony/http-client with a Mercure server would fail.

**Comment by derrabus** [comment]
The issue should be fixed by php/php-src#6104

**Comment by nicolas-grekas** [comment]
> The issue should be fixed by php/php-src#6104

Cool! There's still the thing about curl above.

**Comment by derrabus** [comment]
#38215

**Comment by denis-gol** [comment]
Is it possible to make changes to the book "Symfony5: The Fast Track"?
Upgrading package "symfony/http-client" to version 5.2.* helped me with it problem in Step 16.
