### ISSUE TITLE
Symfony\Bridge\Doctrine\Logger\DbalLogger->normalizeParams truncating values before a database query

### ISSUE THREAD

**Issue by hitsuji** [symfony/symfony#38097]
**Symfony version(s) affected**: 4.4.13 with debug true and monolog logging
running php 7.4.3 on Ubuntu 20.04

**Description**
for my dev environment I'm running into an issue where a fetchAll call on a Doctrine/DBAL/Connection results in a incorrect response as the param values are being modified along the way through the call. This forces me to have to test the calls with debug off to get a correct response.

for instance a call to fetchAll with paramaters such as:
Array
(
    [p_api_key] => bUv3CPcmoPe1L9FlZsLeFgNJJkl5PT2puUuI96twTXUrZnAvUxlG
)

gets modified and the param p_api_key gets trucated as follows:
Array
(
    [p_api_key] => bUv3CPcmoPe1L9FlZsLeFgNJJk [...]
)

I've tracked down the culprit to Symfony\Bridge\Doctrine\Logger\DbalLogger->normalizeParams destructively modifying the param values in the code blocks:

    // non utf-8 strings break json encoding
    if (!preg_match('//u', $params[$index])) {
      $params[$index] = self::BINARY_DATA_VALUE;
      continue;
    }

    // detect if the too long string must be shorten
    if (self::MAX_STRING_LENGTH < mb_strlen($params[$index], 'UTF-8')) {
      $params[$index] = mb_substr($params[$index], 0, self::MAX_STRING_LENGTH - 6, 'UTF-8').' [...]';
      continue;
    }

**Comment by dmaicher** [comment]
> results in a incorrect response as the param values are being modified along the way through the call.

I'm trying to understand what exactly you mean by this.

So you have an issue with the logging output being truncated? I mean the `DbalLogger` does not receive the `$params` array by reference. So it cannot mutate it with an effect for the caller of `DbalLogger::startQuery`, right?

**Comment by hitsuji** [comment]
Sorry,

I wrote the intial report in a rush. The response to the database call is incorrect as the params to the database call is being modified by normaliseParams.

After a further review of the code, this may in fact be a php copy-on-write bug rather than a symphony bug as normaliseParams is not expicitly pass by reference, nor it's predecessors.

**Comment by hitsuji** [comment]
I will update this if i believe its a symfony bug with an example.

**Comment by dmaicher** [comment]
Ok then this can be closed in the meantime, right? You can re-open if you have a reproducer.
