### ISSUE TITLE
Comparison Validator: Add option to override value in error message

### ISSUE THREAD

**Issue by flack** [symfony/symfony#38098]
I have a form with a `start` field and an `end` field. Both are displayed as datepickers in the frontend and save unixtime in the backend. I want to have a validation that makes sure that `end >= start`. So I added the following validator to the `start`field:

```php
new Symfony\Component\Validator\Constraints\LessThanOrEqual(['propertyPath' => 'parent.all[end].data'])
```

This works fine. The only problem is that the error message display in the frontend is kind of useless:

<img width="471" alt="Bildschirmfoto 2020-09-07 um 19 59 18" src="https://user-images.githubusercontent.com/425166/92410519-a5cd8080-f144-11ea-9c2c-52a68f6ccb28.png">

By default, `{{ compared_value }}` in the error message gets replaced with the literal value in the form's data. It would by much more useful if there was a way to get it to display the name of the field it compares to, i.e. instead of 

```
This value should be less than or equal to 1597017600.
```

I want to print

```
This value should be less than or equal to End date.
```

I realize I can just build a custom validator, but still, I would posit that in the case of comparing two form fields, the label of the form field is more useful to the end user than the raw value, so it would be nice if there was a way to achieve this out of the box (it can be something simple like a new option for `AbstractComparison`, something like `comparisonFieldLabel` or something)

**Comment by jschaedl** [comment]
@flack You can override the default message by using the `message` option of the `LessThanOrEqual` Constraint. 
See: https://symfony.com/doc/current/reference/constraints/LessThanOrEqual.html#message

**Comment by flack** [comment]
@jschaedl yes, that is possible, but then I would lose all translation.. The advantage of the builtin messages is that they are available in many languages by default. What I am looking for is something like this:

```php
$this->context->buildViolation($constraint->message)
    ->setParameter('{{ compared_value }}', $label)
    ->addViolation();
```
