### ISSUE TITLE
ArgvInput throws an exception that does not link back to offending code

### ISSUE THREAD

**Issue by bilogic** [symfony/symfony#38105]
**Symfony version(s) affected**:
symfony/console                       v4.4.13            Symfony Console Component

**Description**  

Referring to this class, https://github.com/symfony/console/blob/master/Input/ArgvInput.php, I ran into a situation where ```$argv``` is ```NULL``` by default and in turn caused ```$this->tokens``` to be ```NULL```. This will cause an exception to be thrown when ```foreach()``` is applied on ```$this->tokens``` below:
- https://github.com/symfony/console/blob/a729c1d1f122a0f3a356f0882400d63cb44c9d5c/Input/ArgvInput.php#L243
- https://github.com/symfony/console/blob/a729c1d1f122a0f3a356f0882400d63cb44c9d5c/Input/ArgvInput.php#L279

**How to reproduce**  

Many have reported about it in the past decade:
- https://stackoverflow.com/questions/57848968/invalid-argument-supplied-for-foreach-in-laravel-schedular-job
- https://laracasts.com/discuss/channels/laravel/invalid-argument-supplied-for-foreach-when-scheduling-task
- https://stackoverflow.com/questions/49149556/laravel-5-5-cron-job-proc-open-and-argvinput-problems

**Possible Solution**  

Never allow ```$this->tokens``` to be ```NULL```, at minimum, it should be an empty array.
1. In ```__construct()```, change the assign to call ```$this->setTokens($argv);```
2. In ```setTokens()```, ```if (null == $tokens) $tokens = [];```

**Additional context**  

In the cases above (including my own), this exception does not link back to the offending code and becomes a real challenge to trace. I can submit a PR. Thank you.

**Comment by ro0NL** [comment]
i think we can safely update the constructor to do `$argv = $argv ?? $_SERVER['argv'] ?? [];` :+1: 

see also https://www.php.net/manual/en/reserved.variables.argv.php#118368

**Comment by bilogic** [comment]
Sure, but ```setTokens(null)``` can still cause this same exception. Would that be a concern?

**Comment by ro0NL** [comment]
setTokens is guarded to be array :)

https://github.com/symfony/symfony/blob/3ba965a6cd22e7ae4e55075d200eb9a8cf5bd3fb/src/Symfony/Component/Console/Input/ArgvInput.php#L60

**Comment by bilogic** [comment]
> i think we can safely update the constructor to do `$argv = $argv ?? $_SERVER['argv'] ?? [];` 

Ah, Got it. How should we proceed? Should I PR?

**Comment by chalasr** [comment]
Please, yes (should be submitted against the 4.4 branch).

**Comment by bilogic** [comment]
@chalasr Sorry, I'm quite new to PRs. https://github.com/symfony/console/pull/60
Did I do it wrongly?

**Comment by chalasr** [comment]
@bilogic Pull requests are managed in this repository (https://github.com/symfony/symfony), can you please resubmit your patch here ?

**Comment by bilogic** [comment]
@chalasr Yea, I got it! Thank you. :)
https://github.com/symfony/symfony/pull/38114
