### ISSUE TITLE
Possible BC Break: service that are meant to public are marked as private and remove from DI

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#38115]
**Symfony version(s) affected**: 3.4.44

**Description**  
We're upgrading our project from 3.4.x to 4.x.
in order resolve some deprecations we've upgrade doctrine/doctrine-bundle to latest (2.1.2) which requires symfony/doctrine-bridge ^4.3.7|^5.0 and which conflicts with symfony/http-kernel <4.3.7 (symfony/dependency-injection v4.4.13)

So in the end we're running so in the end we're running framework-bundle 3.4.44 and http-kernel v4.4.13

We know that all service are private=true by default starting from 4.x so as B/C for 3.4 `\Symfony\Component\DependencyInjection\Definition` has `$public=true` and `$private=true` at the same time.

But unfortunately `\Symfony\Component\DependencyInjection\Compiler\ResolvePrivatesPass` make this B/C to break, because all services that are meant to be public e.g.: `form.type`, `jms_serializer.event_listener` and etc. are now **private** and eventually `RemoveUnusedDefinitionsPass` is removing them

**How to reproduce**  
- Install framework-bundle v3.4.44, doctrine/doctrine-bundle v2.1.2
- Create simple form
```
The "form.type.entity" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

As a workaround created custom compiler pass which does:
```
        foreach ($container->findTaggedServiceIds('form.type') as $id => $tag) {
            $definition = $container->getDefinition($id);
            $definition->setPublic(true);
        }
```

**Possible Solution**  
- Utilize `\Symfony\Component\DependencyInjection\Compiler\ResolvePrivatesPass` to process public first, private second and explicitly call `setPublic(true)` for all public and `setPrivate(true)` for all private.

**Additional context**  
![image](https://user-images.githubusercontent.com/1244112/92501208-e42b7400-f206-11ea-8970-f6dbd159c9e0.png)

**Comment by nicolas-grekas** [comment]
Not sure I see any issue here. DI v4.4 has private services by default, v3.4 has not.
If you use DI v4.4, eg. form types are private since `setPublic(true)` is never called for them.

**Comment by oleg-andreyev** [comment]
But that means framework-bundle 3.4.44 and http-kernel v4.4.13 are not compatible, no?

**Comment by xabbuh** [comment]
Looking at the stack trace the `Container::get()` call originates in the Sonata CoreBundle. I would investigate if it has been fixed there.

**Comment by oleg-andreyev** [comment]
@xabbuh no. it has nothing to do with Sonata CoreBundle, it's just a BC layer, eventually it does the same as `DependencyInjectionExtension` in Form Component.

**Comment by xabbuh** [comment]
The `DependencyInjectionExtension` from the Form component does not use the full container, but a special service locator (see https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/DependencyInjection/FormPass.php).

**Comment by xabbuh** [comment]
It also seems that the SonataCoreBundle is deprecated: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/README.md

**Comment by oleg-andreyev** [comment]
Ok. It looks like it's not Symfony fault. It's too dependencies and are outdated and probably Symfony constraints are misused.
