### ISSUE TITLE
[Workflow] New validation event workflow.validation

### ISSUE THREAD

**Issue by RonanSauvage** [symfony/symfony#38112]
Recently i've implemented workflow component in new application to manage expense report with multiples roles and authorizations et some states. 

The most interesting case here is we propose two states to add one expense report : saved & submitted. 

Basically, saved is just for himself when submitted requires validation by admin. 
To simplify imagine you have four attributes for one expense report : 

- one date 
- one amount
- one title
- one file

When one use add one expense report, he need to inquire at least one attribute to saved (and can add the others later) but need to feed the fourth to submit for validation.
So, you have to validate your expense report according to the data entered in the form by your user. 

To validate your expense report, you can't use Guard event because 

> There are a special kind of events called “Guard events”. Their event listeners are invoked every time a call to Workflow::can, Workflow::apply or Workflow::getEnabledTransitions is executed. With the guard events you may add custom logic to decide what transitions that are valid or not. Here is a list of the guard event names.

So, if you use guard, when you wanna display availables transitions, your user need to feed the four attributes previously before seeing the transition. 

In a concrete case, your use save one expense report with just one date. 
If he edits it, he need to feed the other three fields then must save before be able to submit. 

Overall, you can't use event to validate your data in workflow and you need to add your specific validation in one service (or in your controller .. with eventually your specifics validation groups based on your transitions). 

So, my idea is add a new validation event with exactly same behaviour than guard but which would not be called in `Workflow::getEnabledTransitions`. Just on `Workflow::can` and `Workflow::apply`. @lyrixx add in SF 4.1 the `transition blocker`, th goal would be to use its in this validation.event.

For example : https://gist.github.com/RonanSauvage/84c34e6b79387615448a3015846b10e9

**Comment by ro0NL** [comment]
i try to understand, but fail to see how workflow and validation are related

> So, you have to validate your expense report according to the data entered in the form by your user.

why arent you validating the form data then?

**Comment by RonanSauvage** [comment]
Thank for your answer. Imo, in some case your validation is closely linked with one transition. Of course, you can manager your validation in your action and validate your entity but I want my validation to be intimately linked to the transition 
(hence the idea of ​​going through an event). 

In this example (called by controller transition action), I need to add validation step after having checked that the transition was `possible`. (Here it is a multiple transition action but it does not matter)
```

            $expenseReportFlow = $this->workflow->get($expenseReport);
            $expenseReportFlow = $this->workflow->get($expenseReport);
             /** In my idea, `can` will provide specific validation below
            if($expenseReportFlow->can($expenseReport, $expenseReportTransition->getTransition()))
            {
                /** @var ConstraintViolationList $errors */
                $errors = $this->validator->validate($expenseReport, null, [$expenseReportTransition->getTransition()]);
                if(count($errors) > 0) {
                    $expenseReportTransitionResults->addTransitionError(new ExpenseReportTransitionResult($expenseReport, $errors));
                }
                else{
                    $expenseReportFlow->apply($expenseReport, $expenseReportTransition->getTransition());
                    $expenseReportTransitionResults->addTransitionSuccess(new ExpenseReportTransitionResult($expenseReport));
                }
            }
            else {
                $errors = new ConstraintViolationList();
                $errors->add(new ConstraintViolation(sprintf('Impossible transition : %s', $expenseReportTransition->getTransition()),  null, [], '', 'transition', $expenseReportTransition->getTransition()));
                $expenseReportTransitionResults->addTransitionError(new ExpenseReportTransitionResult($expenseReport, $errors));
            }

```

**Comment by ro0NL** [comment]
i think i understand. However i'd expect if `can()` returns true, the transition is also available in `getEnabledTransitions()`.

> when you wanna display availables transitions, your user need to feed the four attributes previously before seeing the transition.

is that a problem? Your form has set the fields already no? or the field values would be loaded in case of an existing subject.

So to me it sounds the guard event is the right place.

Alternatively, in the context of forms, the logic could be reversed; after a form submit check `workflow::can()` and add a "form error" as needed.

**Comment by RonanSauvage** [comment]
I agree with 

> So to me it sounds the guard event is the right place.

Guard is a really nice concept and usefull. 
But the guard influence availables transitions when you call it in your form view. 

Imagine this object [expense_report](https://gist.github.com/RonanSauvage/150875ca28439361bc1c2a6b40a5f5e4)

Your user save one expenseReport with only one title. His expense report has "saved" state. Now he wanna add `amount`, `receipt` and `date`. You can't define this `NotNull` validation in the guard otherwise when you call $workflow->getEnabledTransitions($expenseReport), you apply your guard restriction (so here `submit` transition would be unavailable because your asserts are not valid when with current expense report state). 

That's why, I think you can't use this validation rules in the guard because guard is called in `getAvailableTransition`. 
With new event / configuration `validation`, you can define your specific logic and use validator component directly in the transition process. 

Currently, in normal process you need to call `$flow->can` (validates guard) then `validator->validate`. My idea is to include the possibility to validate your entity in the `can` call. (If your assert are not valid, workflow add TransitionBlocker object like guard process)

**Comment by lyrixx** [comment]
Hello @RonanSauvage 

I read carefully your issue, and I think everything is right with the current implementation.
Indeed, `getAvailableTransition` use guard events and it will stay like this.
And I still think Guard Event is the right place to do some validation.

I usually solve issues like your with **one of** the following method

1. I move the logic from a guard to a transition listener. Then, if all requirements are not fulfilled, I throw a custom exception and I deal with it in my controller or whatever. It's super simple. Sometime, I used the Validator Component and I throw an exception that embed a `ConstraintViolationList`
1. I hardcode the transition in my view layer, even if the transition is not enabled. Then when the user apply the transition, I display the exception to them.

I hope I give you enough solution to fix your issue. That's why I'm going to close this issue.
But if you have more question, don't hesitate to reply here.
