### ISSUE TITLE
[Console] Failed to switch to codepage 1252

### ISSUE THREAD

**Issue by akoval777** [symfony/symfony#38111]
**Symfony version(s) affected**: 5.1.5

**Description**  
Get error when try to run migrations:
"In QuestionHelper.php line 115: Warning: sapi_windows_cp_set(): Failed to switch to codepage 1252"

**How to reproduce**  
php bin/console doctrine:migrations:migrate

Windows 10 v2004 (19041.488)
PHP 7.4.7

**Comment by chalasr** [comment]
See #38116
