### ISSUE TITLE
User Deprecated: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API

### ISSUE THREAD

**Issue by gmuehl** [symfony/symfony#38121]
**Symfony version(s) affected**: 4.4.13 with Orm-Pack 2.0

**Description**  
User Deprecated: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API

**How to reproduce**  
Looks like Deprecation occurs in all 4.x Installations.

**Possible Solution**  
1.x explicitely loaded in
vendor/doctrine/orm/composer.json
instead of 2.x

Looks like ORM-Pack is using doctrine-orm 2.7.3 at the Moment. I guess this Deprecation is Doctrine-Only and does not affect upgrading Symfony from 4.x to 5.x ?

**Additional context**  
![image](https://user-images.githubusercontent.com/151238/92565062-699c3c00-f27a-11ea-9188-8f11639298c4.png)

**Comment by xabbuh** [comment]
Are you sure that upgrading to a more recent version of the ORM package is blocked by Symfony? Can you double-check please?

**Comment by gmuehl** [comment]
Upgrading orm-pack 1.x to 2.x was no Problem. Though, the Deprecation stayed. So, you want me to explicetely add the inflector to package.json with Version 2.x ? Question is: what will happen when upgrading Symfony 4.x to 5.x. When i search through src and vendor it looks like nothing but Doctrine itself is using the Inflector. So this Deprecation could be a poor Doctrine-Thing, and could have nothing to do with Symfony itself? 

![image](https://user-images.githubusercontent.com/151238/92571027-e501eb80-f282-11ea-9b2a-b3116e7663b1.png)

Deprecation from Maker-Bundle should only be thrown, when using make on Dev.

**Comment by xabbuh** [comment]
I would try to debug where the deprecated call originates and then check whether it goes away by installing a more recent version of said package first.

**Comment by XWB** [comment]
Afaik this will be fixed in Doctrine DBAL 2.11 (not yet released).

**Comment by xabbuh** [comment]
Let's close here then.

**Comment by flaushi** [comment]
Sorry for re-opening, doctrine/dbal is already on 2.12, but the deprecation is still there.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce?

**Comment by gjuric** [comment]
I believe this depends on Doctrine ORM 2.8 release, see here: https://github.com/doctrine/orm/issues/8137

**Comment by xabbuh** [comment]
let's close then

**Comment by arderyp** [comment]
@gjuric does ORM 2.8 require symfony 5?  I tried updating to it on symfony 4.4 project, and it caused all sorts of autowiring issues.
