### ISSUE TITLE
[Translation] Nullable locale inside tests

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#38124]
**Symfony version(s) affected**: 4.4.11

**Description**  

When a form triggers some error, the code flow goes that way:
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Validator/Violation/ConstraintViolationBuilder.php#L161-L165
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/DataCollectorTranslator.php#L54-L60
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/Translator.php#L224
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/Translator.php#L284-L297

**How to reproduce**  

Inside my tests there are errors like that:

> TypeError: Argument 1 passed to Symfony\Component\Translation\Translator::initializeCacheCatalogue() must be of the type string, null given, called in vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php on line 317
> 
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:338
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:317
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:293
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:224
> vendor/symfony/symfony/src/Symfony/Component/Translation/DataCollectorTranslator.php:56
> vendor/symfony/symfony/src/Symfony/Component/Validator/Violation/ConstraintViolationBuilder.php:164
> vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/NotBlankValidator.php:45
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:767
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:609
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:520
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:315
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:138
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php:104
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:767
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:492
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:315
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:138
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveValidator.php:93
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/TraceableValidator.php:66
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php:50
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:264
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:239
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:73
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php:44
> vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:671
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php:109
> vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:493

**Possible Solution**  
Allow nullable locale? Or manual how to properly set a locale in tests/CLI/whatever?

**Additional context**  
With Symfony 3.4.35 there are no errors like these.

I also tried to add `\Locale::setDefault('en');` inside `setUpBeforeClass()` method, but didn't work.

**Comment by ro0NL** [comment]
the translator takes a default locale (passing null is deprecated since 4.4)

we need to verify the translator used during validation is configured as such, otherwise you should have gotten a deprecation about it.

The default translator service takes `default_locale` from the framework config, which defaults to `en`. But perhaps it's explcicitly configured as null.

I agree the bug is real, and Translator::getLocale() returning null (the deprecated case) should be accounted for.
