### ISSUE TITLE
New Preloader related issues causing "Failed opening required '/var/www\vendor/autoload.php'" 

### ISSUE THREAD

**Issue by ralusnom** [symfony/symfony#38123]
**Symfony version(s) affected**: 5.1.6

**Description**  

Path resolution does not work with the newly integrated cache handler `cache/Xxx_KernelProdDebugContainer.preload.php`

`require dirname(__DIR__, 3).'\\vendor/autoload.php';`

The two backslashes are resolved to this square character: `.\endor/autoload.php` (see picture) since \v is an escape secquence for vertical jumps, as far as I remember.

The screenshot below show the debug output. 

**How to reproduce** 

- `$ composer dump-env prod`
- Open web page
- 💣 

**Possible Solution** 
Also, `dirname(__DIR__,3)` doesnt resolve correctly (might be a configuration issue from my side/app).
The only temp solution is to change to this weird non-scalable path settings:
```
require __DIR__.'/../../../vendor/autoload.php'; <-- changed
require __DIR__.'/ContainerU2aLZw8/Vince_KernelProdDebugContainer.php';
```
**Additional context**  
![image](https://user-images.githubusercontent.com/266216/92570987-d9aec000-f282-11ea-8376-b492b55606f4.png)

**Comment by ralusnom** [comment]
I see, the issue starts when the DebugContainer is generated in `vendor/symfony/dependency-injection/Dumper/PhpDumper.php:329`
![image](https://user-images.githubusercontent.com/266216/92580600-dc171700-f28e-11ea-8611-08193a9ed5e2.png)

I also need to add that I'm working on a Windows machine and empty the cache from the local command line. The app itself runs in a docker container with Apache on Ubuntu.

This means that before `$autoloadFile = trim($this->export($autoloadFile), '()\\');` the variable `$autoloadFile` has a Windows path format.

**Comment by nicolas-grekas** [comment]
Can you please try this patch?

It changes back-slashes into forward-slashes in dumped containers, making them path-independent.

```diff
--- a/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
+++ b/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
@@ -2056,7 +2056,13 @@ EOF;
             $suffix = $matches[0][1] + \strlen($matches[0][0]);
             $matches[0][1] += \strlen($matches[1][0]);
             $prefix = $matches[0][1] ? $this->doExport(substr($value, 0, $matches[0][1]), true).'.' : '';
-            $suffix = isset($value[$suffix]) ? '.'.$this->doExport(substr($value, $suffix), true) : '';
+
+            if ('\\' === \DIRECTORY_SEPARATOR && isset($value[$suffix])) {
+                $suffix = '.'.$this->doExport(str_replace('\\', '/', substr($value, $suffix)), true);
+            } else {
+                $suffix = isset($value[$suffix]) ? '.'.$this->doExport(substr($value, $suffix), true) : '';
+            }
+
             $dirname = $this->asFiles ? '$this->containerDir' : '__DIR__';
             $offset = 2 + $this->targetDirMaxMatches - \count($matches);
```

**Comment by ralusnom** [comment]
Yes, it's getting better, but then it's failing for the twig imports. I changed the first require_once manually.

![image](https://user-images.githubusercontent.com/266216/92591204-be9d7980-f29d-11ea-9f89-661118328de5.png)

I also had to remove 

```
...
#12 require dirname(__DIR__, 3).'/vendor/autoload.php';
#13 require __DIR__.'/ContainerTTUj7xS/Vince_KernelProdDebugContainer.php';
...
```
because of
`Compile Error: Cannot declare class ContainerTTUj7xS\Vince_KernelProdDebugContainer, because the name is already in use`

**Comment by fabpot** [comment]
Problem comes from the fact that the preload.php file is stored under src/, which is managed by the DebugClassLoader. So, we either need to have some special treatment for the file, or move it elsewhere.

**Comment by ralusnom** [comment]
Pulling it out of src would be advantageous. At least I had to exclude it from the service configuration as well.
This is not a class/file that needs to be managed in src, right? Or is it intended that this file can be adjusted manually later?

**Comment by ralusnom** [comment]
...ahm... I think this solved the issue. After extending service exlusion by `preload.php` 

```
  App\:
    resource: '../src/App/*'
    exclude: '../src/App/{[....],Kernel.php,preload.php}'
```
And it now even works without the suggested changes from Nikolas.

Did you mention this somewhere in the docs?
