### ISSUE TITLE
Error [Symfony\Component\Debug\Exception\ContextErrorException] without stack trace

### ISSUE THREAD

**Issue by tonywei92** [symfony/symfony#38125]
I only get error message like this:
```
 [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: GoPay
```
There are like 50ish "GoPay" in the project files.

How to enable stack trace?

Symfony 2.6.1

**Comment by ro0NL** [comment]
in CLI the stack trace is outputted in verbose mode: `-vvv`, allthough im only guessing this is CLI related.

**Comment by tonywei92** [comment]
@ro0NL you're life saver!
