### ISSUE TITLE
Add UuidValidator / UlidValidator

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#38152]
Or maybe a UidValidator with an attribute to specify the variant?

Help Wanted

**Comment by laurent35240** [comment]
Hi

I can see that there is already UuidValidator available here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/UuidValidator.php
So for this issue we just need to add UlidValidator class or am I missing something with Uuid?

**Comment by gennadigennadigennadi** [comment]
In one of the comments `For better compatibility, both loose and strict, you should consider using a specialized UUID library like "ramsey/uuid" instead.`

I assume Nicolas wants to use the Symfony/uid package for the valdation instead of the current validation logic.

**Comment by laurent35240** [comment]
Hi,

@nicolas-grekas I opened pull request https://github.com/symfony/symfony/pull/38322 for adding Ulid constraint and validator.
Let me know if it is what you had in mind or if you wanted instead to merge UUID and ULID into a single UID constraint and validator.
