### ISSUE TITLE
Add "different statements" to web debug toolbar

### ISSUE THREAD

**Issue by lomby92** [symfony/symfony#38158]
**Description**  
The Symfony Web Debug Toolbar is a powerful tool. Whenever a dev sees a colored section it starts to fear what it has potentially broken.

The Doctrine section is very useful as it shows the number of queries and the query time. If something goes wrong it became red/yellow and the dev is ready to detect what/where is the problem.
This section could be better if it also takes into account the __different statements__ count (that is already shown in the dedicated Symfony profiler page).

This information is useful to detect repeated queries that potentially impact performances. It could be also a detector for N+1 queries created due to a Doctrine bug.

**Example**  
The "different statements" information could be placed into the div that appears on mouse hover (as in the image below)
![proposal](https://user-images.githubusercontent.com/5825081/93365028-8ec81600-f849-11ea-8db9-8166ea5f1b88.png)

To have a fast detection of repeated queries, the Doctrine section of the toolbar could be colored with orange/yellow (the alert color) when the count of "different statements" is less than the count of "database queries".

**Comment by ro0NL** [comment]
the doctrine panel is maintained in https://github.com/doctrine/DoctrineBundle :)

**Comment by lomby92** [comment]
Maybe you were right before: the Twig is into https://github.com/doctrine/DoctrineBundle/blob/master/Resources/views/Collector/db.html.twig
