### ISSUE TITLE
Symfony/Mime Path ... is not readable.

### ISSUE THREAD

**Issue by SebCargo** [symfony/symfony#38155]
**Symfony version(s) affected**: 5.1.* - Symfony/Mime > 5.1.2

**Description**  

I'm using [fromPath()](https://github.com/symfony/mime/blob/master/Part/DataPart.php).
I'm passing remote image with an url. It was working well until the Symfony/Mime 5.1.2 (included).

But now I have an error for some files with the message "Path ... is not readable." It seem to be for some files only and when I'm checking the url, the url is correct and the file can be opened.

If I force to the 5.1.2 of the symfony/mime it's working well and the file is processed successfully.

It seem that the new condition on line 59 (https://github.com/symfony/mime/blob/master/Part/DataPart.php) with the php function `is_readable()` is causing the problem. I don't know why at this point.

Comparing 2 images (one working on who is not) is not showing anything.

**How to reproduce**  

It's difficult to reproduce as it's happening only for some files. But using the fromPath function with a remote url.

**Possible Solution**  

Removing the new condition added on 5.1.3 or not using the `is_readable` function from php ?

**Additional context**  
-

**Comment by xabbuh** [comment]
see #38047

**Comment by SebCargo** [comment]
@xabbuh I'm not sure if it's the same problem as I don't want to attach a file to an email. And the problem is more the fact that the php function is_readable is not behaving consistently.

Or do we want to avoid passing url to the fromPath function too ?

To add more context I need this because I need to send files from an url in an S3 bucket to an API.

```php
private function addImage(Image $image)
    {
        $formFields = [
            'pictures' => DataPart::fromPath($image->getFullPath())
        ];

        $formData = new FormDataPart($formFields);
        $headers = $formData->getPreparedHeaders();
        $headers->addTextHeader('X-Api-Key', $this->thirdPartyService->getToken());
        $headers->addTextHeader('accept', 'application/vnd.bridge+json; version=1');


        $client = HttpClient::create();
        $client->request(
            'POST',
            sprintf(
                '%s/locations/%s/media',
                $this->thirdPartyService->getUrl()->getUrl(),
                $this->solocalLocation->_id
            ),
            [
                'headers' => $headers->toArray(),
                'body' => $formData->bodyToIterable()
            ]
        );
    }
```

**Comment by stof** [comment]
An external URL is not the same thing than a path.

**Comment by SebCargo** [comment]
Ok so I think I will extend DataPart and add a fromUrl() to fits my needs. Thx

**Comment by dgfmdrv** [comment]
Hello, I come here trying to read a UNC path. 
is_readable return false but  fopen or file_get_contents can read the file.

 https://stackoverflow.com/questions/34531749/php-on-iis-is-readable-over-unc-path
