### ISSUE TITLE
Internal server error when recursive extends for twig files in templates

### ISSUE THREAD

**Issue by AlexNguetcha** [symfony/symfony#38150]
**Symfony version(s) affected**: 5.1.5

**Description**  

Web server return an internal error with status 500 when i extends a twig file in him.

**How to reproduce**  

For Example create a  **home.html.twig** then insert this part of code
```twig
{% extends "home.html.twig" %}
 <!--- a memory overflow will be produce.-->
```
**Possible Solution**  

throw ans error when recursive inclusion in twig templates.

**Comment by fabpot** [comment]
That’s a Twig error, not a Symfony one.

IIRC it’s not easy to implement. I’m closing here for now. If you want to propose a fix feel free to open a pull request.

On 10 Sep 2020, at 22:46, AlexNguetcha <notifications@github.com> wrote:

﻿

Symfony version(s) affected: 5.1.5

Description

Web server return an internal error with status 500 when i extends a twig file in him.

How to reproduce

For Example create a home.html.twig then insert this part of code

{% extends "home.html.twig" %}
 

Possible Solution

throw ans error when recursive inclusion in twig templates.
