### ISSUE TITLE
[Yaml] Parsing behaviour changed between 3.4.43 and 3.4.44 

### ISSUE THREAD

**Issue by tobias-kuendig** [symfony/symfony#38154]
**Description**  

October CMS uses the `symfony/yaml` component to parse the changelog of a plugin.

In one of our plugins, we have used a `:` in an unquoted string: https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files

This has been working fine for months, but a few days ago, this line started being parsed as an object/array, instead of a simple string. This caused the update routine of the plugin to break.

Downgrading `symfony/yaml` from version `3.4.44` to `3.4.43` made the issue disappear. It looks like this change is causing the issue: https://github.com/symfony/yaml/commit/12473febc5f2b19756339922e55035f52558d7bb

To be clear: I am aware that the `:` inside the unquoted string was a mistake to begin with. But this change feels like a breaking change that should not have been included in a patch version.

Looking closer at this issue, I found out that the real problem is the `!!!` start of the line, which October uses to mark an update the user has to manually confirm. It looks like this is parsed as a ["non-specific tag"](https://stackoverflow.com/questions/9664113/what-does-a-single-exclamation-mark-do-in-yaml).

**How to reproduce**  

The following `ParserTest` passed in `3.4.43` but fails in `3.4.44`:

```php
class ParserTest extends TestCase
{
    // ...
    public function testStringWithColonAndExclamationMarks()
    {
        $yaml = <<<YAML
1.2.3:
    - !!! Link to website: https://google.com
YAML;

        $this->assertSame(['1.2.3' => ['!!! Link to website: https://google.com']], $this->parser->parse($yaml));
        
    }
}
```

**Additional context**  

The culprit of this issue is the [`'!' === $values['value'][0]`](https://github.com/symfony/yaml/commit/12473febc5f2b19756339922e55035f52558d7bb#diff-037865b8555f7db5ac9338cfb5be7466R236) line in the modified if statement. Using an unquoted `!!!` seems to be a bad idea in the first place so I wonder if you even want to do something about this problem.

Let me know if I should provide a PR.

Refs https://github.com/octobercms/october/issues/5271

**Comment by stof** [comment]
`!` is a reserved char at the beginning of values in Yaml. Your existing Yaml file was an invalid file, which was working only by luck due to a bug in the parser. As this bug has been fixed (to make tags work properly in object keys, not only in values), your file is now parsed differently.

**Comment by xabbuh** [comment]
closing as explained by @stof
