### ISSUE TITLE
Serialization of Form Errors Ignores Error Mapping

### ISSUE THREAD

**Issue by 9ae8sdf76** [symfony/symfony#38161]
**Symfony version(s) affected**: 4.4

**Description**  
When a form type has defined the `error_mapping`, errors are expected to be mapped according to the given definition. This works flawlessly in Twig and will correlate the mapped errors (e.g., [error_mapping in the docs](https://symfony.com/doc/current/reference/forms/types/form.html#error-mapping)).

However, when serializing the form errors (e.g., `$this->json($form->getErrors())`), those error mappings are ignored and the originals are used instead. This breaks being able to correlate mapped error messages based solely on the serialized data. In other words, I have to leak my error mapping details in my Javascript front-end when I'm processing form errors from a JSON endpoint.

**How to reproduce**  
Build a form with error mapping, then serialize the errors. The `cause.propertyPath` in the output will point to the original field name and not the mapped name as expected. For example, map one field's errors to another fields or use a method for validation.

**Comment by xabbuh** [comment]
Can you please show an example of what the resulting JSON looks like in your case?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
