### ISSUE TITLE
Warning: session_cache_limiter(): Cannot change cache limiter when session is active

### ISSUE THREAD

**Issue by AzazelOnni777** [symfony/symfony#38170]
**Symfony version(s) affected**: 3.1.10

**Description**  
Cannot change cache limiter when session is active. 

**How to reproduce**  
    private $session;
    

    public function __construct(){
        $this->session = new Session();

**Comment by chalasr** [comment]
Can you create a [minimal app that reproduces the issue](https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs)?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
