### ISSUE TITLE
[Profiler] Add Web Vitals Indicators

### ISSUE THREAD

**Issue by bnjmnfnk** [symfony/symfony#38178]
The Web Vitals Indicators becoming more and more important. maybe this could be a feature in the near future.

The API and wrapper are available in JS - https://web.dev/vitals

**Comment by javiereguiluz** [comment]
@bnjmnfnk they are very important ... but they are client-side based, right? Symfony, from the backend, can't access to these values or calculate them itself. So, we couldn't add them to the profiler. Maybe I'm missing something?

**Comment by bnjmnfnk** [comment]
@javiereguiluz They are client-side. But the toolbar uses also Javascript so the possibility is there.

**Comment by stof** [comment]
@bnjmnfnk the data is collected server side, not client side, though.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" for now because of the reasons given. The good news is that Google provides a great browser extension to quickly access this information, so it should be OK. Thanks!
