### ISSUE TITLE
Cache not cleared with ChainAdapter

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#38184]
**Symfony version(s) affected**: since 4.4.11

**Description**  
The commit https://github.com/symfony/cache/commit/59bde160873886d643d30da1cbe1e5f147b47839 seems to broke our Cache. It seems so using expire 0 does not work on Redis. The data still exists.  (https://github.com/symfony/cache/commit/59bde160873886d643d30da1cbe1e5f147b47839#diff-f33ff1923ceb8c163902c260b87d724fR92)

When I set it back to `null` and clear Redis. It works like expected. 

**How to reproduce**  
Set up a TagAware Chain Adapter with ArrayAdapter and RedisAdapter. Create a Tagged Item. Invalide it, The Item does not invalidate in Redis

**Possible Solution**  
Set this back to `null`
https://github.com/symfony/cache/commit/59bde160873886d643d30da1cbe1e5f147b47839#diff-f33ff1923ceb8c163902c260b87d724fR92

**Additional context**

**Comment by nicolas-grekas** [comment]
can you please check with 4.4.12?
if it doesn't work, with the latest 4.4 branch?
we fixed this recently AFAIK

**Comment by shyim** [comment]
Tested against `4.4.x-dev` works for me now. We have to patch it for our project then until an official release is out.

Thanks for the fast answer! :heart:
