### ISSUE TITLE
composer init error

### ISSUE THREAD

**Issue by hdliyu** [symfony/symfony#38180]
Hi!
I'm trying to init composer.json via composer command in CMD. Whenever I run composer init is interrupted by error message reading:

[Symfony\Component\Console\Exception\RuntimeException]
Aborted

![image](https://user-images.githubusercontent.com/13653157/93032340-ab0a5e00-f663-11ea-8841-143294e96dfc.png)

**Comment by ro0NL** [comment]
cannot reproduce `Composer version 1.10.13`

i think this belongs in https://github.com/composer/composer either way, unless you can show us an issue e.g. with symfony/console causing it.
