### ISSUE TITLE
Http redirects are not followed when using caching http client

### ISSUE THREAD

**Issue by dmolineus** [symfony/symfony#38207]
**Symfony version(s) affected**: `^4.3.0`

**Description**  

I use the http client for a `GET` request. By default an instance of `Symfony\Component\HttpClient\HttpClient` follows redirects (by default up to 20). When using the `Symfony\Component\HttpClient\CachingHttpClient` every redirect leads to an exception.

The issue is caused by the `Symfony\Component\HttpKernel\HttpClientKernel` which overrides the `max_redirects` option:

https://github.com/symfony/symfony/blob/9c8cd0827f6fab9bf840b7fd2940bcbe1b16e75e/src/Symfony/Component/HttpKernel/HttpClientKernel.php#L53-L57

**How to reproduce**  
```php
<?php

$client = Symfony\Component\HttpClient\HttpClient::create();
$cachingClient = new Symfony\Component\HttpClient\CachingHttpClient(
    $client,
    new Symfony\Component\HttpKernel\HttpCache\Store('/path/to/the/cache') 
);

// Work as expectede
$client->request(
    'GET', 
    // Redirect to https://api.github.com/repositories/109533757/git/matching-refs/tags/ happens here
    'https://api.github.com/repos/humbug/box/git/matching-refs/tags/', 
    ['headers' => ['Authorization' => 'token XXX']
);

// Throws Symfony\Component\HttpClient\Exception\RedirectionException
$cachingClient->request(
    'GET', 
    // Redirect to https://api.github.com/repositories/109533757/git/matching-refs/tags/ happens here
    'https://api.github.com/repos/humbug/box/git/matching-refs/tags/', 
    ['headers' => ['Authorization' => 'token XXX']
);

```

**Additional context**  

* https://github.com/symfony/symfony/pull/30625

**Comment by nicolas-grekas** [comment]
This line should be removed, it's a left over from BrowseKit.
PR welcome, branch 4.4 please.

**Comment by dmolineus** [comment]
I checked the browser kit, it forces `max_redirects=0`, it seems to be save to remove it:

https://github.com/symfony/symfony/blob/237d91f3b2df68a27e6bd77efbdf141da95e2b87/src/Symfony/Component/BrowserKit/HttpBrowser.php#L50-L54
