### ISSUE TITLE
Remember Me on a lazy firewall causes refresh of cookie on every request

### ISSUE THREAD

**Issue by qurben** [symfony/symfony#38206]
**Symfony version(s) affected**: 5.1.5

**Description**  

A firewall with `lazy: true` and remember me enabled will refresh the remember me token on every request, causing a `CookieTheftException` if multiple requests with the same remember_me cookie are sent.

Configuration must use `PersistentTokenRememberMeServices`

**How to reproduce**  

~https://github.com/qurben/symfony_issue_38206~ If needed I can make a reproducer, but it is a bit involved as it also requires Doctrine or some database access.

**Possible Solution**  

The remember me authenticator will already check the cookie and update it when `supports` is called. In a lazy configuration there is no token at this moment causing the remember em authenticator to check (and update) the cookie for each request.

It possibly should just check if the cookie exists, to give the ContextListener a chance to create a session and skip updating the cookie.

**Comment by qurben** [comment]
The current version of the reproduce repo has a bug causing it to fail. And I accidentally used `TokenBasedRememberMeServices` instead of `PersistentTokenBasedRememberMeServices`

**Comment by qurben** [comment]
With lazy disabled on the firewall the issue is now that `PersistentTokenBasedRememberMeServices::processAutoLoginCookie` is called twice, once by `RememberMeAuthenticator::supports` and then again by `RememberMeAuthenticator::authenticate` and it tries to set the cookie twice.

**Comment by qurben** [comment]
Reverting back to 5.1.3 (the version my project was previously on) fixes this issue.

**Comment by qurben** [comment]
https://github.com/symfony/symfony/commit/93aea910d939d33cddc07b8dbd0cff2d8dfc2ea0 Seems to be the cause, it fails if supports is called more than once. And it is called twice by AuthenticatorManager.

https://github.com/symfony/symfony/blob/4c96577d4d911f985d09f980d18a921b0b067f07/src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php#L101

https://github.com/symfony/symfony/blob/4c96577d4d911f985d09f980d18a921b0b067f07/src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php#L139

**Comment by fancyweb** [comment]
Status: reviewed

https://github.com/symfony/symfony/commit/93aea910d939d33cddc07b8dbd0cff2d8dfc2ea0 definitely caused a regression for lazy firewalls using remember me. We cannot call `RememberMeServicesInterface::autoLogin()` in `RememberMeAuthenticator::supports()`. It seems as we need to know whether the `RememberMeServicesInterface` service can auto login without actually doing it. Perhaps with `RememberMeServicesInterface::canAutoLogin(Request $request): bool`? WDYT @wouterj?
