### ISSUE TITLE
can not run symfony command from yii2 rest api

### ISSUE THREAD

**Issue by saidhappy010** [symfony/symfony#38222]
I have a yii2 api in which there is a symfony cammnd.
This command returns null to me, using shell_exec () or exec () functions, although it works fine on cmd.
This is what I did in my yii2 code:

```
$strPath = "C:/inetpub/wwwroot/MyApp";
chdir ($strPath);
return $output = shell_exec ('php app/console command ........');
```
  or

```
$strPath = "C:/inetpub/wwwroot/MyApp";
chdir ($strPath);
$returSig = exec ('"C:\Program Files (x86)\PHP\php-5.5.12-nts-Win32-VC11-x86\php.exe" app/console command.......', $ status);
return $status;
```

**MyApp** is a symfony app.
 yii2 api and symfony app are hosted in windows server
please I would like to run symfony command in yii2 api
I read an article saying that shell_exec returns NULL if an error occurred.
How can we solve this problem? 
It is true that there is a problem
please help me
Thank you

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by saidhappy010** [comment]
Thank you.
