### ISSUE TITLE
[PhpUnitBridge] SYMFONY_DEPRECATIONS_HELPER and DeprecationErrorHandler

### ISSUE THREAD

**Issue by shehi** [symfony/symfony#38239]
**Symfony version(s) affected**: 5.1.5

**Description**  
This [line](https://github.com/symfony/symfony/blob/v5.1.5/src/Symfony/Bridge/PhpUnit/bootstrap.php#L129), where `DeprecationErrorHandler` is being registered, relies on the fact that a `SYMFONY_DEPRECATIONS_HELPER` env value exists in $_ENV. Problem is, this bootstrapping happens while inside Composer autoloader:

![image](https://user-images.githubusercontent.com/653569/93638059-ef488600-f9f6-11ea-96c1-13f8063687bb.png)

At this point, `phpunit.xml` file hasn't even been loaded, as a result, the aforementioned env value which is provided there isn't put into $_ENV yet. This technically invalidates the point of this line in the code if you don't provide the env value via command shell.

Once autoloader is loaded (at this point we are past the point of loading `DeprecationErrorHandler`) env values are loaded from `phpunit.xml`:

![image](https://user-images.githubusercontent.com/653569/93638804-3be09100-f9f8-11ea-9924-07749ecf7a41.png)

**How to reproduce**  

1. `phpunit.xml` file has line: `<env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />`
2. Create some test with deprecated usage triggerable.
3. Run tests and you still will get `THE ERROR HANDLER HAS CHANGED!` error at the end of the test, which is emitted by [`DeprecationErrorHandler`](https://github.com/symfony/symfony/blob/v5.1.5/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L186). 
![image](https://user-images.githubusercontent.com/653569/93638936-7fd39600-f9f8-11ea-8f5a-b3045572a6dc.png)
4. Run the same tests with env variable passed in command shell: `SYMFONY_DEPRECATIONS_HELPER="disabled" phpunit` and no errors will be emitted.
![image](https://user-images.githubusercontent.com/653569/93638997-97ab1a00-f9f8-11ea-82ad-ce0ec3986ada.png)

And guys... All caps?! Seriously?!

**Comment by shehi** [comment]
My `phpunit.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/9.3/phpunit.xsd"
         colors="true"
         bootstrap="config/bootstrap.php"
         stopOnFailure="true"
>
    <php>
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled"/>
        <env name="KERNEL_CLASS" value="App\Kernel" />
        <ini name="error_reporting" value="32767" />
        <ini name="memory_limit" value="256M" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="9.3" />
    </php>
    <testsuites>
        <testsuite name="Backend Model Tests">
            <directory>tests/Model/</directory>
        </testsuite>
        <testsuite name="Backend Functional Tests">
            <directory>tests/Functional/</directory>
        </testsuite>
        <testsuite name="Backend Legacy Functional Tests">
            <directory>tests/FunctionalLegacy/</directory>
        </testsuite>
        <testsuite name="Backend Unit Tests">
            <directory>tests/Unit/</directory>
        </testsuite>
    </testsuites>
    <listeners>
        <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
    </listeners>
    <logging>
        <junit outputFile="./.coverage/logfile.xml"/>
    </logging>
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src/</directory>

        </include>
        <exclude>
            <directory suffix="Exception.php">src/</directory>
            <directory>src/Application/Dto/Constraints/</directory>
            <directory>src/Resources/DataFixtures/</directory>
        </exclude>
        <report>
            <clover outputFile="./.coverage/coverage.xml" />
            <html outputDirectory="./.coverage/report" lowUpperBound="35" highLowerBound="70" />
        </report>
    </coverage>
</phpunit>
```

**Comment by nicolas-grekas** [comment]
Could you please make a repo with the reproducer? That would help us get quickly to running into the issue locally.

**Comment by michaelKaefer** [comment]
### Related issues
- https://github.com/symfony/symfony/issues/28726
- https://github.com/symfony/symfony/issues/28519

### Reproducer
I created a reproducer:
```bash
git clone git@github.com:michaelKaefer/reproducer-38239.git
cd reproducer-38239
composer install
```

No message with:
```bash
$ SYMFONY_DEPRECATIONS_HELPER="disabled" ./bin/phpunit
[...]
OK (1 test, 1 assertion)
```

With the following you get the message "THE ERROR HANDLER HAS CHANGED!", although in `phpunit.xml` file has line: `<env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />`:
```bash
$ ./bin/phpunit
[...]
OK (1 test, 1 assertion)
THE ERROR HANDLER HAS CHANGED!
```

### Fix
I can try to fix it, this solutions come to my mind:
- Somewhere in `vendor/symfony/phpunit-bridge/bin/simple-phpunit.php` read all env variables from `phpunit.xml` and load them with something like:
```php
putenv("$envName=$envValue");
$_SERVER[$envName] = $_ENV[$envName] = $envValue;
```
- In `src/Symfony/Bridge/PhpUnit/bootstrap.php` read the value of `SYMFONY_DEPRECATIONS_HELPER` from `phpunit.xml` before using it. Which of the two following solutions is better for this?
  - From `src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php` copy paste the variable `$getEnvVar = function ($name, $default = false) use ($argv) { ... };` to `src/Symfony/Bridge/PhpUnit/bootstrap.php` and use it there.
  - In `src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php` make the variable `$getEnvVar = function ($name, $default = false) use ($argv) { ... };` globally available, and then use it in `src/Symfony/Bridge/PhpUnit/bootstrap.php`.
- If `SYMFONY_DEPRECATIONS_HELPER` should not be defined in `phpunit.xml` anymore then it must be changed in the docs at https://symfony.com/doc/current/components/phpunit_bridge.html#configuration

Or is there a better solution?

**Comment by michaelKaefer** [comment]
Related issues: 
- https://github.com/symfony/symfony/issues/28726
- https://github.com/symfony/symfony/issues/28519

**Comment by shehi** [comment]
> If SYMFONY_DEPRECATIONS_HELPER should not be defined in phpunit.xml anymore then it must be changed in the docs at https://symfony.com/doc/current/components/phpunit_bridge.html#configuration

I vote for this solution. The minimalist in me says there is no need to invent tons of stuff for a simple thing such as this.
