### ISSUE TITLE
Can`t read symfony session data from other server - Notice: unserialize(): Error at offset

### ISSUE THREAD

**Issue by salirzv** [symfony/symfony#38240]
**Symfony version(s) affected**: 5.1.5

**Description**  

Hi
I am developing a Symfony App that the sessions are required in other server , so I`m storing the session in the database  , everything works fine until I want to read the data in the other server .

This is the BLOB data in my database :

`_sf2_attributes|a:6:{s:26:"_security.main.target_path";s:52:"https://localhost:8000/panel/courses/learning-course";s:24:"_csrf/https-authenticate";s:43:"qiwpT9GaqgnpiZN7lKnNgo-WiQXny7RjOUd-yFlPZAU";s:23:"_security.last_username";s:18:"sali.rzv@gmail.com";s:14:"_security_main";s:3147:"O:67:"Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken":2:{i:0;s:4:"main";i:1;a:5:{i:0;O:15:"App\Entity\User":12:{s:19:"App\Entity\Userid";i:1;s:22:"App\Entity\Useremail";s:18:"sali.rzv@gmail.com";s:22:"App\Entity\Userroles";a:2:{i:0;s:10:"ROLE_ADMIN";i:1;s:12:"ROLE_TEACHER";}s:25:"App\Entity\Userpassword";s:97:"$argon2id$v=19$m=65536,t=4,p=1$SHRSZmIwRU96VVpxQ3BiTA$AMo5+LfqJpEr5fggPpRE78n89lPDmOKWjTnU0GiwxTk";s:21:"App\Entity\Username";s:33:"Ø³ÛŒØ¯ Ø¹Ù„ÛŒ Ø±Ø¶ÙˆØ§Ù†ÛŒ Ø±Ø§Ø¯";s:27:"App\Entity\Usercreated_at";O:8:"DateTime":3:{s:4:"date";s:26:"2020-09-13 17:25:53.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:11:"Asia/Tehran";}s:22:"App\Entity\Userphone";s:11:"09128468592";s:27:"App\Entity\Useris_teacher";b:1;s:24:"App\Entity\Usercourses";O:33:"Doctrine\ORM\PersistentCollection":2:{s:13:"*collection";O:43:"Doctrine\Common\Collections\ArrayCollection":1:{s:53:"Doctrine\Common\Collections\ArrayCollectionelements";a:0:{}}s:14:"*initialized";b:0;}s:30:"App\Entity\Userupload_secret";s:13:"5f652e78e6039";s:41:"App\Entity\Userupload_secret_created_at";O:8:"DateTime":3:{s:4:"date";s:26:"2020-09-19 02:32:32.942192";s:13:"timezone_type";i:3;s:8:"timezone";s:11:"Asia/tehran";}s:41:"App\Entity\Userupload_secret_for_course";O:32:"Proxies\__CG__\App\Entity\Course":15:{s:17:"__isInitialized__";b:1;s:21:"App\Entity\Courseid";i:1;s:30:"App\Entity\Coursefront_title";s:21:"Ø¯ÙˆØ±Ù‡ Ø¢Ù…ÙˆØ²Ø´ÛŒ";s:23:"App\Entity\Courseslug";s:15:"learning-course";s:29:"App\Entity\Coursemeta_title";s:60:"Ø¹Ù†ÙˆØ§Ù† Ù†Ù…Ø§ÛŒØ´ Ø¯Ø§Ø¯Ù‡ Ø´Ø¯Ù‡ Ø¨Ù‡ Ø¹Ù†ÙˆØ§Ù† Ù…ØªØ§";s:29:"App\Entity\Courseshort_desc";s:47:"ØªÙˆØ¶ÛŒØ­Ø§Øª Ù…Ø®ØªØµØ± Ø¯Ø±Ø¨Ø§Ø±Ù‡ Ø¯ÙˆØ±Ù‡";s:28:"App\Entity\Coursemeta_desc";s:66:"ØªÙˆØ¶ÛŒØ­Ø§Øª Ù…Ø®ØªØµØ± Ø¯Ø±Ø¨Ø§Ø±Ù‡ Ø¯ÙˆØ±Ù‡ ÙˆÙ„ÛŒ Ø¯Ø± Ù…ØªØ§";s:24:"App\Entity\Courseprice";i:250000;s:24:"App\Entity\Courseowner";r:4;s:24:"App\Entity\Courseimage";O:31:"Proxies\__CG__\App\Entity\Image":5:{s:17:"__isInitialized__";b:1;s:20:"App\Entity\Imageid";i:16;s:28:"App\Entity\Imagecreated_at";O:8:"DateTime":3:{s:4:"date";s:26:"2020-09-18 08:29:17.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:11:"Asia/Tehran";}s:22:"App\Entity\Imagepath";s:63:"/public/statics/images/courses/logo-5f643095d40271.89670655.png";s:27:"App\Entity\Imagehtml_path";s:56:"/statics/images/courses/logo-5f643095d40271.89670655.png";}s:28:"App\Entity\Courseis_public";b:1;s:29:"App\Entity\Coursecreated_at";O:8:"DateTime":3:{s:4:"date";s:26:"2020-09-15 16:36:57.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:11:"Asia/Tehran";}s:29:"App\Entity\Courseupdated_at";O:8:"DateTime":3:{s:4:"date";s:26:"2020-09-15 16:36:57.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:11:"Asia/Tehran";}s:33:"App\Entity\Coursetotal_duration";i:0;s:27:"App\Entity\Coursesessions";O:33:"Doctrine\ORM\PersistentCollection":2:{s:13:"*collection";O:43:"Doctrine\Common\Collections\ArrayCollection":1:{s:53:"Doctrine\Common\Collections\ArrayCollectionelements";a:0:{}}s:14:"*initialized";b:1;}}}i:1;b:1;i:2;N;i:3;a:0:{}i:4;a:3:{i:0;s:10:"ROLE_ADMIN";i:1;s:12:"ROLE_TEACHER";i:2;s:9:"ROLE_USER";}}}";s:13:"upload_secret";s:13:"5f652e78e6039";s:34:"_csrf/https-panelSingleProductPage";s:43:"o0rbttRHy6iHQs3YcO0Hqgv-2NTyS-OqQtIl_ATDs9w";}_sf2_meta|a:3:{s:1:"u";i:1600466552;s:1:"c";i:1600466498;s:1:"l";s:1:"0";}`

And when I want to read the data in the destination server , I do like this : 

```
$user_sql = $pdo->prepare('select * from user_session where sess_id = ?');

$user_sql->execute([$sess_id]);

$user_session = $user_sql->fetch();

$session_data = $user_session['sess_data'];

$array = unserialize($session_data);
```
Which gives me this result : 

`Notice: unserialize(): Error at offset 0 of 3644 bytes`

**Comment by xabbuh** [comment]
Do both servers use the same PHP version?

**Comment by derrabus** [comment]
The prefix `_sf2_attributes|` in your blob is not a valid input for `unserialize`.

**Comment by salirzv** [comment]
> Do both servers use the same PHP version?

Yes , both servers are in local right now and using the latest version of PHP

**Comment by salirzv** [comment]
> The prefix `_sf2_attributes|` in your blob is not a valid input for `unserialize`.

Adding this code fixed the problem , thank you 

`$fixed_session_data = str_replace('_sf2_attributes|' , '' , $session_data);`

The symfony documentation says that you should store session data in DB if you want to read it in the other server , so the data should be serialized in the way that it is easy to be unserialized , I think this is an unexpected behavior , or am I missing something?

**Comment by derrabus** [comment]
> so the data should be serialized in the way that it is easy to be unserialized

No, the data should be serialized in a way that it can be read by the same session handler class that wrote it. If you want to parse that serialization yourself, you're basically on your own.

**Comment by marcbln** [comment]
For unserializing the sess_data, you can use the class posted here: https://stackoverflow.com/a/9843773/2848530
