### ISSUE TITLE
No password encoder with nested mongoDB document

### ISSUE THREAD

**Issue by pinksnotdead** [symfony/symfony#38249]
**Symfony version(s) affected**: 5.1

**Description**  
No encoder has been configured for account "App\Document\Users\User".
This appears when User class is nested and security can't find it. After moving "App\Document\Users\User" class to "App\Document\User" everything works fine.

More info can be found here:
https://stackoverflow.com/questions/63979700/symfony-api-platform-no-encoder-has-been-configured-for-account-app-document?noredirect=1#comment113137342_63979700

**Possible Solution**  
this should be treated as bug or in official documentation should be mentioned, that user provider for mongoDB can't  be nested

**Comment by xabbuh** [comment]
I am not sure I understand the issue. What do you mean with nesting user providers?

**Comment by pinksnotdead** [comment]
It means that encoder can't be found in case doctrine document (mongoDB) is placed in nested directrory (folder). 
I've got error: No encoder has been configured for account "App\Document\Users\User" when my User class was in src/Document/Users/User.php. 
But  the error disappeared when i moved it on top level in stuctrure to src/Document/User.php.

I guess, that security can't find user class when it is placed in subdir.

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
@pinksnotdead check your config in `config/packages/security.yaml` to see which class name is used for your encoder config there. I suspect a mismatch between your configuration and your actual class name.

**Comment by pinksnotdead** [comment]
Sorry for my late response, i was working on another project. it must have been a mistake in my code or configuration. I can't reproduce it again. Once again sorry for silence and sorry for the confusion.
