### ISSUE TITLE
 EntityType with two fields/choice_label or custom rendering ?

### ISSUE THREAD

**Issue by kaamui** [symfony/symfony#38242]
```
Year
{
    Month[12]
}

Month
{
    Foo[]
}

Foo
{
   name, defaultValue
}
```

When creating a new `Year` I want to list every `Foo` in database so the user can select them and customize `defaultValue` like following :

```
CHECKBOX [x] LABEL name1, INPUT defaultValue1
CHECKBOX [ ] LABEL name2, INPUT defaultValue2
CHECKBOX [x] LABEL name3, INPUT defaultValue3
CHECKBOX [x] LABEL name4, INPUT defaultValue4
//etc
```

... the aim is to generate automatically Foo objects according to the selection made above, in every one of the 12 `Month` objects of this new `Year`

I tried to use `Foo` as an `EntityType` but it is not working because I want to expose `defaultValue` too. 

```
->add('foos', EntityType::class, [
            "class" => Foo::class,
            "mapped" => false,
            "multiple" => true,
            "expanded" => true
}
```

I also tried like this : 
```
->add('foos', CollectionType::class, [
    "mapped" => false,
    'entry_type'    => SharedFooType::class
])

class SharedFooType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enabled', CheckboxType::class, [
                "mapped" => false
            ])
            ->add('name' , TextType::class) //not a label but not important for now
            ->add('defaultValue' , MoneyType::class); 
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Foo::class,
        ]);
    }
}
```

But with this code the mapping is not working, 

Can I modify the rendering of the entityType so it displays the property name as a label and the property defaultValue as an input ?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
