### ISSUE TITLE
[2.2] Allow Form Crawler to add missing inputs when submitting

### ISSUE THREAD

**Issue by meglio** [symfony/symfony#3824]
Often on web page load js generates additional inputs and adds them to the FORM DOM element, for example it happens often for adding browser and system information, if available.

When we use Form then and pass values for inputs to be set, Form class says then something like "I cannot reach these inputs" - because they initially where not in the HTML loaded.

Adding some bool parameter like `createMissingInputs` may help in such a case. Otherwise we have to first manually add input dom nodes to the form node, and only then call `->form()` method. Passing an array of desired inputs will simplify Form usage in such a case.

**Comment by alexislefebvre** [comment]
I had the same question and I found this issue.

I'm looking for a way to get a form through `Client`, add data by using the `$form` array and in the same request add some fields not present in the original page (those created by Javascript).

Let's say I have a form with simple fields (a text field that is always present) and dynamic fields (created with Javascript).

Here is a convenient way to submit a form with data (it works with Symfony 2.8):

    $crawler = $client->request('GET', '/');
    $form = $crawler->filter('input[type=submit]')->form();
    $form['form_name[value]'] = 'foo';
    $crawler = $client->submit($form);

It would be really nice to be able to use something like this:

    $crawler = $client->request('GET', '/');
    $form = $crawler->filter('input[type=submit]')->form();
    $form['form_name[value]'] = 'foo';
    // Set some values for fields generated by Javascript:
    $myNewValues = array(
        'form_name' => array(
            'collection' => array(
                0 =>
                    'name' => 'foo'
                )
            )
        )
    );
    );
    // Submit the form with the text field and the new values:
    $crawler = $client->submit($form, $myNewValues);

With Symfony 2.8, this code will trigger an error if the `form_name[collection][0][name]` field is not in the DOM, which is the case when items of a collection are added dynamically.

---

May we find a way to disable this check, for example by adding a third argument to the `submit()` function? With a switch like this, I may easily submit a form with supplementary fields in order to tests my forms which have collections.

**Comment by alexislefebvre** [comment]
Here is a working code where a value is added to a form without checking the existing fields:

    // Get the form.
    $form = $crawler->selectButton('Save')->form();
    
    // Set some values of existing fields.
    $form['task[description]'] = 'Lucas';
    
    // Add some data.
    $values = array_merge_recursive(
        $form->getPhpValues(),
        array(
            'task' => array(
                'tags' => array(
                    // Add an element to the Collection.
                    // Array key will be added automatically.
                    array('name' => 'tag3'),
                )
            )
        )
    );
    
    // Submit all the values.
    $crawler = $client->request($form->getMethod(), $form->getUri(), $values, $form->getPhpFiles());

What is interesting here is that I don't have to fetch the token, it's already set.

**Comment by jakzal** [comment]
@alexislefebvre unfortunately adding an argument to the `submit()` method would be a [BC break](http://symfony.com/doc/current/contributing/code/bc.html#changing-classes). We'll probably need a new method to add additional fields to the form.

**Comment by alexislefebvre** [comment]
@jakzal Thanks, I didn't know that adding an argument with a default variable was a BC break. I'll add a method as you suggest.

**Comment by alexislefebvre** [comment]
@jakzal I followed your advice and I added a new method. I'm not sure it's ready for a PR so I put it in a PR on my fork: https://github.com/alexislefebvre/symfony/pull/3/files

Feedback is welcome.

**Comment by Nemo64** [comment]
I just had the same problem and created a more sophisticated workaround. My html looks something like this:

```HTML
<div id="collection_type" data-prototype="[html]" data-prototype-name="[placeholder]">
```

So I created a method like this:

```PHP
    /**
     * @param \DOMElement $node
     * @param string $index
     */
    protected function appendPrototypeDom(\DOMElement $node, $index = '0')
    {
        $prototypeHTML = $node->getAttribute('data-prototype');
        $prototypeHTML = str_replace($node->getAttribute('data-prototype-name'), $index, $prototypeHTML);
        $prototypeFragment = new \DOMDocument();
        $prototypeFragment->loadHTML($prototypeHTML);
        foreach ($prototypeFragment->getElementsByTagName('body')->item(0)->childNodes as $prototypeNode) {
            $node->appendChild($node->ownerDocument->importNode($prototypeNode, true));
        }
    }
```

Which can then simply be used before creating the form instance like this:

```PHP
        $formCrawler = $crawler->filter('form[name="form_name"]');
        $this->appendPrototypeDom($crawler->filter('#collection_type')->getNode(0), '1');
        $form = $formCrawler->form();
        $form["some_field_that_wasnt_there_before"] = 'value';
```

**Comment by marcoalbarelli** [comment]
@Nemo64 's solution is fine. 
I just propose a small improvement to make it more ready to use
```php
       /**
     * @param \DOMElement $node
     * @param int $currentIndex
     * @param int $count
     */
    protected function appendPrototypeDom(\DOMElement $node, $currentIndex = 0, $count = 1)
    {
        $prototypeHTML = $node->getAttribute('data-prototype');
        $accumulatedHtml = '';
        for ($i = 0; $i < $count; $i++) {
            $accumulatedHtml .= str_replace('__name__', $currentIndex + $i, $prototypeHTML);
        }
        $prototypeFragment = new \DOMDocument();
        $prototypeFragment->loadHTML($accumulatedHtml);
        foreach ($prototypeFragment->getElementsByTagName('body')->item(0)->childNodes as $prototypeNode) {
            $node->appendChild($node->ownerDocument->importNode($prototypeNode, true));
        }
    }
```

replacing the string `__name__` is more adherent to the cookbok recipe 
http://symfony.com/doc/current/form/form_collections.html#allowing-new-tags-with-the-prototype
and this way you can choose how many new elements you want to add

Also, this works well with file uploads as well:
```php
        $formCrawler = $crawler->filter('form[name="some_form"]');
        $this->appendPrototypeDom($crawler->filter('.allegati')->getNode(0), 0, 2);
        $form = $formCrawler->form();
        $values = $form->getValues();
        $values['some_form[allegati][0][description]'] = 'some description';
        $values['some_form[allegati][0][file][file]'] = new UploadedFile(
            __DIR__.'/../Assets/some.pdf',
            'some.pdf',
            'application/postscript',
            filesize(__DIR__.'/../Assets/some.pdf')
        );
        $values['some_form[allegati][1][description]'] = 'some description';
        $values['some_form[allegati][1][file][file]'] = new UploadedFile(
            __DIR__.'/../Assets/some.pdf',
            'some.pdf',
            'application/postscript',
            filesize(__DIR__.'/../Assets/some.pdf')
        );
```

I think this could be put in the documentation or become a PR against the crawler code

P.S.
I tried the solution proposed in this pr https://github.com/symfony/symfony-docs/pull/6427 but it wasn't working in my case. Also in a E2E testing scenario this approach makes more sense IMHO

**Comment by BenoitDuffez** [comment]
Huge thanks, @marcoalbarelli. I even added another parameter: the prototype name, which I needed because I have nested collections (collections of collections) which imply having different prototype names to avoid collision.

**Comment by Visibility7** [comment]
Please, I need help! have same problem but I don't use collection_type!

Error : 
InvalidArgumentException: The current node list is empty.

and my code : 
 $form = $crawler->filter("form")->form();

        $client->submit($form, array(
            'slug'  => 'symfony',
            'name'  => 'test',
            'content' => 'bla',
            'description' => 'bla bla',
        ));

**Comment by alexislefebvre** [comment]
@Visibility7 Please don't use GitHub issues for support, you'll find other ways to get support here: https://symfony.com/support

**Comment by Visibility7** [comment]
@alexislefebvre okay! Thanks

**Comment by fabpot** [comment]
Closing as the pull request was closed in favor of some documentation in symfony/symfony-docs#6427
