### ISSUE TITLE
Guestbook can't deploy

### ISSUE THREAD

**Issue by paolotormon** [symfony/symfony#38254]
[
![symfonyerror](https://user-images.githubusercontent.com/61226023/93751863-5a30d180-fc30-11ea-8dbd-172bd8dc6067.PNG)
](url)

How do I fix this?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by fabpot** [comment]
@paolotormon You need to run `composer up` first and commit the result `git commit -m"Bump deps"`. Or you can ignore the warning by using `symfony deploy --bypass-checks`

**Comment by paolotormon** [comment]
@fabpot I did both of those, still giving the same error. Pls help

![symfonyerror2](https://user-images.githubusercontent.com/61226023/93766457-02529480-fc49-11ea-9ef8-0174545f20e9.PNG)

**Comment by stof** [comment]
The failed deployment is done because of the security check but because of the invalid configuration file.

**Comment by paolotormon** [comment]
@stof I didn't edit anything, it's straight up from
>symfony project:init

**Comment by wouterj** [comment]
As said before, please don't use GitHub issues for user support. There are multiple (open source and paid) [support channels](https://symfony.com/support) available for user support.

**Comment by paolotormon** [comment]
For anyone else experiencing the same issue:
The solution is in in .symfony.cloud.yaml, delete the empty 
```
variables:
php:
```

then do a git commit.

**Credits to Tugdual Saunier from SymfonyCloud Support**
