### ISSUE TITLE
Question: In what circumstance will the function Finder::getIterator return SplFileInfo[]

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [symfony/symfony#38267]
https://github.com/symfony/symfony/blob/7cb8ba585dcb4243c4245487281654df149bd3ad/src/Symfony/Component/Finder/Finder.php#L603

I want to call Iterator functions on the returned Object, those might fail if it is not of type \Iterator but SplFileInfo[] as the docblock states.

**Comment by ro0NL** [comment]
it's an old convention to denote "generics". Both supported by psalm&phpstorm, and is interpreted like `\Iterator<\SplFileInfo>`

see also https://psalm.dev/docs/running_psalm/configuration/#allowphpstormgenerics

not sure SF embraced generic syntaxt in docblocks already, i think it does ... and if so im :+1: for updating these docblocks.

But then we have a severe practical issue in phpstorm: https://github.com/Haehnchen/idea-php-generics-plugin/issues/14

**Comment by OwnerOfThisIsle** [comment]
Thx for the clarification..
