### ISSUE TITLE
[String] allow string to be constructed with null

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#38260]
**Description**  
Just recently started really using the component and am finding it annoying that a string can't be constructed with `null` (think nullable entity fields). Maybe at least the helper functions? I wanted to gauge interest before submitting a PR.

There was a PR accepted to allow this for the Twig StringExtension (https://github.com/twigphp/Twig/pull/3259).

**Example**  
Instead of `s((string) $possibleNullString)`, it would be nice to just do `s($possibleNullString)`.

**Comment by derrabus** [comment]
And what should `s(null)` produce in that case?

**Comment by kbond** [comment]
The same as `s((string) null)` (`s('')`)

**Comment by nicolas-grekas** [comment]
Why not, but only for the functions, not for the class' constructors, isn't it? Please send a PR so we can discuss the idea on actual code.
