### ISSUE TITLE
Upgrade To 5.1.5 from 4.4

### ISSUE THREAD

**Issue by Holliver** [symfony/symfony#38276]
Argument 3 passed to Symfony\Bridge\Twig\Extension\RoutingExtension::getPath() must be of the type bool, array given, called in /Users/olivierbaviere/Sites/hde/var/cache/dev/twig/67/67545e2f7b89df170de2d026923c62c1a210c737d3ff6c1b02b62a95a51f9738.php on line 146  
`
   ```
 /**
     * @route("/{id}/show", name="affaire_show", methods={"GET","POST"})
     * @param Affaire $id
     * @return Response
     */
    public function show(Affaire $id): Response
    {
        /** @var object $affaire */
        $affaire = $this->getDoctrine()
            ->getRepository(Affaire::class)
            ->findOneBy(['id' => $id]);
        if (($affaire->getStatutDevis() !== 'Facture sans devis') && ($affaire->getNumDevis() === null)) {
            /** @var int $numDev */
            $numDev = $this->getDoctrine()->getRepository(Affaire::class)->maxNumDevis();
            if ($numDev) {
                $numD = (int)$numDev[0]['lastNumDev'];
                ++$numD;
            } else {
                $numD = 1;
            }
            $affaire->setNumDevis($numD);
        }
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->createQuery(
            $nbrlignes = $this->getDoctrine()
                ->getRepository(Rubrique::class)
                ->countLignesByRubriques($affaire));
        $nbreTot = 0;
        foreach ($nbrlignes as $nbrligne => $value) {
            $nbreTot += $value['nbreLignes'];
        }
        $affaire = $this->getDoctrine()
            ->getRepository(Affaire::class)
            ->findOneBy(['id' => $id]);
        $entityManager->flush();
        return $this->render(
            'affaire/show.html.twig',
            [
                'affaire' => $affaire,
                'nberub' => count($affaire->getRubrique()),
            ]
        );
    }`
```
He run in 4.4
the line 146  of cache/dev/twig/67/67545e..... is:
        echo twig_escape_filter($this->env, $this->extensions['Symfony\Bridge\Twig\Extension\RoutingExtension']->getPath("rubrique_edit", ["id" => twig_get_attribute($this->env, $this->source, $context["rubrique"], "id", [], "any", false, false, false, 37)], ["affaireId" => twig_get_attribute($this->env, $this->source, (isset($context["affaire"]) || array_key_exists("affaire", $context) ? $context["affaire"] : (function () { throw new RuntimeError('Variable "affaire" does not exist.', 37, $this->source); })()), "id", [], "any", false, false, false, 37)]), "html", null, true);

**Comment by wouterj** [comment]
Did you try removing the cache? Cache is not necessarily compatible between minor/major versions.

**Comment by Holliver** [comment]
I solve the problem: is was the view twig.
This request is canceled.
Thanks
