### ISSUE TITLE
[Translation] Please remove dependency of INTL plugin

### ISSUE THREAD

**Issue by peter-mw** [symfony/symfony#38279]
Hello,

as of this commit

https://github.com/symfony/translation/commit/fe0e1f2c61715d6d6e33bf533ca2db4467307605#diff-c93f36c15d5c29291cda962db092b47bR161

the `symfony/translation` package now requires the INTL plugin which is not installed on the majority of users and i get the error `Class 'Locale' not found`   . https://www.php.net/manual/en/book.intl.php 

Using symfony/translation version '5.1' breaks a lot of installs because of this dependency 

I needed to revert to symfony/translation  version '5.0'

Can you please fix this dependency as INTL plugin does not come by default

**Comment by ro0NL** [comment]
that's a good catch :+1: i think it's best to add a class_exists check for `\Locale`, and eventually fallback to `en` hardcoded in case the extension/polyfill is unavailable.

**Comment by xabbuh** [comment]
see #38282

**Comment by ro0NL** [comment]
@xabbuh ai, i picked the same issue - https://github.com/symfony/symfony/pull/38283
