### ISSUE TITLE
UPGRADE-4.4 gives outdated instructions about handling RegistryInterface deprecation

### ISSUE THREAD

**Issue by GPHemsley** [symfony/symfony#38281]
(Alluded to in #34377 but not followed up on.)

`Symfony\Bridge\Doctrine\RegistryInterface` has been deprecated. The UPGRADE-4.4 documentation indicates that it should be replaced with `Doctrine\Common\Persistence\ManagerRegistry`. However, that in turn has been deprecated in favor of `Doctrine\Persistence\ManagerRegistry`.

The UPGRADE-4.4 documentation needs to be updated to reflect this change. (The deprecation warning issued by the code already gets this right.)

**Comment by nicolas-grekas** [comment]
Could you please send the pr you have in mind? Branch 4.4

**Comment by Matts** [comment]
Will look at this.
