### ISSUE TITLE
InputBag deprecated notice on KernelBrowser test with followRedirect

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#38306]
**Symfony version(s) affected**: 5.1

**Description**  
In unit tests I am following a redirect from Easy Admin 3. I get the error: 

`Since symfony/http-foundation 5.1: Retrieving a non-string value from "Symfony\Component\HttpFoundation\InputBag::get()" is deprecated, and will throw a "Symfony\Component\HttpFoundation\Exception\BadRequestException" exception in Symfony 6.0, use "Symfony\Component\HttpFoundation\InputBag::all($key)" instead.
`

**How to reproduce**  
This is my test, where the test extends WebTestCase, 
```
        $this->client = static::createClient();
        $this->client->request('GET', '/admin');
        $this->client->clickLink('Locations');
        $this->client->followRedirect();
        $this->assertResponseIsSuccessful();
```

**Comment by nicolas-grekas** [comment]
Could you please provide a full stack trace or better, a reproducer?
The issue might not be in Symfony btw, it might be EasyCorp/EasyAdminBundle#3822 instead.

**Comment by azjezz** [comment]
To help track this down, i suggest you add the following to your tests/bootstrap.php file ( before including `vendor/autoload.php` ), and providing the stack trace:

```php
    function trigger_deprecation(string $package, string $version, string $message, ...$args): void
    {
        if ('symfony/http-foundation' === $package) {
            throw \Exception(sprintf($message, ...$args));
        }
    }
```

this will result in an exception being thrown instead, which should including a stack trace.

**Comment by ChangePlaces** [comment]
Sorry for the delay - been really super busy and still got another crazy week ahead. I'll get to this as soon as i can

**Comment by azjezz** [comment]
yes :) this is an easyadmin issue.
