### ISSUE TITLE
[FrameworkBundle] ConfigDumpReferenceCommand uses yaml even when not present

### ISSUE THREAD

**Issue by garak** [symfony/symfony#38301]
**Symfony version(s) affected**: 5.1.5 (probably other versions, too)

**Description**  
If you don't use symfony/yaml component, the command "config:dump-reference" is trying to use yaml as default value for "format" option, resulting in an error.

**How to reproduce**  
* create a symfony project without symfony/yaml component (or remove symfony/yaml component from an existing project).
* try to dump configuration for any bundle, e.g. `console config:dump-reference twig`
* see error (in YamlReferenceDumper.php line 111) : 

>Attempted to load class "Inline" from namespace "Symfony\Component\Yaml".  
>Did you forget a "use" statement for another namespace?   

**Possible Solution**  
A check for existance of above class should be added. If not present, default value of "format" option should be "xml" instead of "yaml".

**Comment by chalasr** [comment]
Situation improved on 5.2 thanks to #38394.
