### ISSUE TITLE
[RFC] Move Translatable to contracts

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#38319]
Currently the new `Translatable` value object and its corresponding `t()` factory, live in the `Translator` component.

Given its general purpose usability for any translator implementation, i suggest to move both symbols to the `Translation` contract.

It seems more reasonable to leak contracts into our domain layer, rather than an infrastructural component.

Besides, this provides a defacto standard for translation extractors to act upon as well.

**Comment by ro0NL** [comment]
i think the twig bridge proves my point as well :)

https://github.com/symfony/symfony/blob/6349a1b2fc2abd54c3dfdde32fe445f2ae0ec5ec/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php#L18-L20

**Comment by natepage** [comment]
@ro0NL Would that include creating a contract such as `TranslatableInterface`? Because right now `Translatable` is a final class, I think it would be great to work with a contract so projects can implement that interface on their own classes instead of having to instantiate a new `Translatable`.

**Comment by ro0NL** [comment]
we can just move `Symfony\Component\Translation\Translatable` to  `Symfony\Contracts\Translation\Translatable` :)

it seems many ppl expect an interface, but i fail to see it's purpose still. If we have the urge to add it, please feel free to PR though.

**Comment by fabpot** [comment]
I think moving Translatable to the contract is a good move. I don't think we need an interface though as Translatable is a data object.

**Comment by nicolas-grekas** [comment]
Check #38328

**Comment by juanmiguelbesada** [comment]
I'm +1 for having a TranslatableInterface.

As I see it Transatable is Domain layer, and the domain could be so specific where Translatable class may not fit.

Another use case could be simplify translating exceptions.

**Comment by nicolas-grekas** [comment]
A `TranslatableInterface` should only be this then IMHO:
```
interface TranslatableInterface
{
     public function trans(TranslatorInterface $translator, string $locale = null): string;
}
```

I can add it to #38328 if we have a consensus on it.

**Comment by nicolas-grekas** [comment]
See #38330 for a `TranslatableInterface`.

**Comment by natewiebe13** [comment]
I do prefer the approach taken in https://github.com/symfony/symfony/pull/38330, it's closer to my original implementation. The one change I do see that isn't as obvious is that passing parameters to the `trans` filter will no longer merge with the `Translatable` message. I think this should be fine though.
