### ISSUE TITLE
Mailer logs to default app channel instead of dedicated channel

### ISSUE THREAD

**Issue by oxan** [symfony/symfony#38318]
**Description** 
The Mailer component logs to the (default) app channel. As far as I've experienced this is the only component that does so. Especially the SMTP transport is quite noisy with 4 messages per usage. This causes quite some pollution in my application logs. It'd be nice if the mailer would log to its own channel.

**Comment by fabpot** [comment]
Which version of Symfony? In "recent" versions, we don't log anymore in favor of a system where you can get the whole SMTP/HTTP dialog in a variable.

**Comment by oxan** [comment]
I'm using 4.4.13.

I haven't tried it with 5.1 yet, but judging from [the code](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php#L238) it still logs (though maybe another logger gets injected there).

**Comment by chalasr** [comment]
See #39480
