### ISSUE TITLE
Yaml::dump adds erroneous trailing \n (with Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK)

### ISSUE THREAD

**Issue by geek-merlin** [symfony/symfony#38310]
**Symfony version(s) affected**: 3.4.41 (and probably master too)

**Description**  

Yaml::parse(Yaml::dump("a\nb")) === "a\nb\n"

In other words, multiline YML does not roundtrip, it seems to always get a trailing newline.

**How to reproduce**  

```
# In my Drupal/Drush env:
$ drush ev 'print json_encode(\Symfony\Component\Yaml\Yaml::parse(\Symfony\Component\Yaml\Yaml::dump(["a\nb"],2,4, \Symfony\Component\Yaml\Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK))) . "\n";'
["a\nb\n"]
```

**Possible Solution**  

Add such test and fix code.

**Additional context**  

- Raised this already in #25842, but witn "\r\n", and in the heat of the battle, the problem was just hidden by un-multilining "\r\n".
- This is strongly wanted for Drupal config dump [here](https://www.drupal.org/project/drupal/issues/2844452)

**Comment by geek-merlin** [comment]
I just updated the IS, it contained a wrong and heavily confusing "How to reproduce". SORRY.

**Comment by geek-merlin** [comment]
Convenience: The [related PR](https://github.com/symfony/symfony/pull/25864/files).

It looks like all the "multiline" tests contain a "\r\n" and iigir, are not dumped as multiline anymore after that PR, leaving us with no multiline test coverage.

**Comment by xabbuh** [comment]
I forgot to comment here. I was already able to extract a good test case. Unfortunately, the fix wasn't that easy back then when I tried it. But it's on my list of things to do.

**Comment by geek-merlin** [comment]
@xabbuh Great it's on your list! As noted in the IS, quite some Drupal folks will :heart: this.

IIGIR, the key to solve this is the [Block Chomping Indicator](https://yaml-multiline.info/) "|-"/">+".

**Comment by xabbuh** [comment]
here we go: #39668
