### ISSUE TITLE
The "mailjet+smtp" scheme is not supported.

### ISSUE THREAD

**Issue by sandoche** [symfony/symfony#38316]
**Symfony version(s) affected**: 5.2

**Description**  
I have `symfony/mailer` and `symfony/mailjet-mailer` installed.

My composer.json contains this.
```json
{
#...
        "symfony/mailer": "5.2.*",
        "symfony/mailjet-mailer": "^5.2@dev",
#...
}
```

My `.env` contains:
```
MAILER_DSN=mailjet+smtp://xxx:yyy@default
```

I get the following error:
```
The "mailjet+smtp" scheme is not supported.
```

I also get a similar error with `mailjet+api`

**Comment by nicolas-grekas** [comment]
Hello,
why do you think this should work? Did you read it should somewhere?

**Comment by stof** [comment]
can you give the stack trace of the error ?

**Comment by stof** [comment]
I think the issue is that `mailjet-mailer` is not know by the FrameworkBundle DI extension: https://github.com/symfony/symfony/blob/88412a1e2b2282d1a8d4cbdf6ee056fd653211ec/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2126-L2134

**Comment by sandoche** [comment]
> Hello,
> why do you think this should work? Did you read it should somewhere?

Saw it here:
https://symfony.com/doc/master/mailer.html (5.2 version)

**Comment by vico-gs** [comment]
@sandoche , hey I've had the exact same situation this afternoon, turns out the package 'symfony/framework-bundle' supports this update if you use ^5.1 at least. Had to update some of packages as well as many conflicts follows his upgrade .

**Comment by 7system7** [comment]
I have the same issue.
