### ISSUE TITLE
Symfony An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve

### ISSUE THREAD

**Issue by virkse** [symfony/symfony#38335]
I am facing an issue with symfony version 5.1. I ran the migrations it create the database as well as the tables and field by command line. but when i running the localhost/test in browser or via post man it throwing the error.

Please see the error exception and find the connection string from it. like "admin:admin@" it showing **mysql://admin:admin@database:3306/ourdb?serverVersion=5.7**
But in my .env **DATABASE_URL=mysql://admin:admin@localhost:3306/ourdb?serverVersion=8.0.21**

That's why i think i getting the error **An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve**

Is it possible that in connection string showing **database** instead of **localhost** this the cause? if it is the cause then symfony is not reflecting the connection string from .env?
Can you please help me, how i should sort out this issue? Thanks all those can help me.

`{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":500,"detail":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve","class":"Doctrine\\DBAL\\Exception\\ConnectionException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","line":112,"args":[]},{"namespace":"Doctrine\\DBAL\\Driver","short_class":"AbstractMySQLDriver","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","function":"convertException","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":182,"args":[["string","An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve"],["object","Doctrine\\DBAL\\Driver\\PDO\\Exception"]]},{"namespace":"Doctrine\\DBAL","short_class":"DBALException","class":"Doctrine\\DBAL\\DBALException","type":"::","function":"wrapException","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":169,"args":[["object","Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver"],["object","Doctrine\\DBAL\\Driver\\PDO\\Exception"],["string","An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve"]]},{"namespace":"Doctrine\\DBAL","short_class":"DBALException","class":"Doctrine\\DBAL\\DBALException","type":"::","function":"driverException","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOMySql\/Driver.php","line":30,"args":[["object","Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver"],["object","Doctrine\\DBAL\\Driver\\PDO\\Exception"]]},{"namespace":"Doctrine\\DBAL\\Driver\\PDOMySql","short_class":"Driver","class":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver","type":"->","function":"connect","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":360,"args":[["array",{"url":["string","mysql:\/\/admin:admin@database:3306\/ourdb?serverVersion=5.7"],"host":["string","database"],"port":["string","3306"],"user":["string","admin"],"password":["string","admin"],"driver":["string","pdo_mysql"],"driverOptions":["array",[]],"defaultTableOptions":["array",{"collate":["string","utf8mb4_unicode_ci"]}],"dbname":["string","mingletrip"],"serverVersion":["string","5.7"],"charset":["string","utf8mb4"]}],["string","admin"],["string","admin"],["array",[]]]},{"namespace":"Doctrine\\DBAL","short_class":"Connection","class":"Doctrine\\DBAL\\Connection","type":"->","function":"connect","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1753,"args":[]},{"namespace":"Doctrine\\DBAL","short_class":"Connection","class":"Doctrine\\DBAL\\Connection","type":"->","function":"getWrappedConnection","file":"\/var\/www\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1536,"args":[]},{"namespace":"Doctrine\\DBAL","short_class":"Connection","class":"Doctrine\\DBAL\\Connection","type":"->","function":"beginTransaction","file":"\/var\/www\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/UnitOfWork.php","line":379,"args":[]},{"namespace":"Doctrine\\ORM","short_class":"UnitOfWork","class":"Doctrine\\ORM\\UnitOfWork","type":"->","function":"commit","file":"\/var\/www\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/EntityManager.php","line":370,"args":[["null",null]]},{"namespace":"Doctrine\\ORM","short_class":"EntityManager","class":"Doctrine\\ORM\\EntityManager","type":"->","function":"flush","file":"\/var\/www\/src\/Controller\/AuthController.php","line":33,"args":[]},{"namespace":"App\\Controller","short_class":"AuthController","class":"App\\Controller\\AuthController","type":"->","function":"register","file":"\/var\/www\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":157,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["object","Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoder"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/var\/www\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":79,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/var\/www\/vendor\/symfony\/http-kernel\/Kernel.php","line":196,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/var\/www\/public\/index.php","line":28,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}`

**Comment by virkse** [comment]
I listed the vars it showing DATABASE_URL" => "mysql://admin:admin@database:3306/ourdb?serverVersion=5.7" but in .env its different what is happening?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
