### ISSUE TITLE
Support for non-scalar tag attributes

### ISSUE THREAD

**Issue by aschempp** [symfony/symfony#38339]
**Description**  
Currently, it is not possible to tag a service with an array of attributes. [CheckDefinitionValidityPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php#L67) prevents that. Is there a specific reason for that, especially to not support arrays of scalar values? If not, I'd be willing to provide a pull request 🙃 

**Example**  
In [Contao CMS](https://www.contao.org) we're extensively using tags (and [tags from annotations](https://github.com/terminal42/service-annotation-bundle)) to improve DX when adding new elements to the CMS. In our latest release, we're supporting dynamic routes (based on CMF-Routing) from controller services. It looks like this:

```php
<?php

namespace App\Controller;

use Contao\CoreBundle\ServiceAnnotation\Page;

/**
 * @Page(path="foo/{id}", requirements={"id"="\d+"})
 */
class CustomPageController
{
}
```

This is automatically registered as a new *Page Type*, which CMS admins can place in their site structure. A page can be defined multiple times, either across domains or with a *page alias* (prefixed to the path).

**Unfortunately, Symfony currently forbids array attributes in tags**, which I don't understand why. I can work around this by simply removing the attributes in a compiler pass that runs before `CheckDefinitionValidityPass` (see https://github.com/contao/contao/pull/2372), but that can't really be the solution? Also, we can't use YAML for the same because the [YamlFileLoader checks for arrays as well](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L593).

**Comment by ro0NL** [comment]
I believe it's an XSD limitation currently, thus not supported by XML. I figure we could think of a nested structure, similar as argument collections.

**Comment by aschempp** [comment]
Thanks for the hint @ro0NL, it took me a while to realize what you meant (because I never use XML). I've created a draft PR in https://github.com/symfony/symfony/pull/38540 to attempt a new feature 🙃. Should this issue be closed then?
