### ISSUE TITLE
[Translation] Dumping YAML translations as tree

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#38344]
**Description**  
In Symfony 2.8(!!) `as_tree` option was introduced to `YamlFileDumper`. However, until today there isn't possibility to use this option in Symfony app since `translation:update` command [doesn't pass this option to `TranslationWriterInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L305).

**Example**  
```
bin/console translation:update --domain messages --output-format=yml --force --as-tree en
```

**Comment by Wirone** [comment]
Workaround for now:

```
<?php

declare(strict_types=1);

namespace App\Application\Translation;

use Symfony\Component\Translation\MessageCatalogue;
use Symfony\Component\Translation\Writer\TranslationWriter as SymfonyWriter;

/**
 * Workaround for dumping YAML translation files as tree.
 * @see https://github.com/symfony/symfony/issues/38344
 *
 * @author Grzegorz Korba <grzegorz.korba@codito.pl>
 */
class TranslationWriter extends SymfonyWriter
{
    public function write(MessageCatalogue $catalogue, string $format, array $options = [])
    {
        $options['as_tree'] = true;

        parent::write($catalogue, $format, $options);
    }
}
```

and

```
services:
    translation.writer:
        class: App\Application\Translation\TranslationWriter
```

Which will override writer's class and use extended one, with hardcoded `as_tree` option (of course it's easy to make it configurable via env variable).

**Comment by Wirone** [comment]
Request to Maintainers: please provide information which implementation would be better:

- explicit support for `--as-tree` (one new option)
- flexible `--dumper-option key=value` which could be used multiple times to pass options to dumper

First one is (obviously) much simpler, second one could resolve any problems with other dumpers' options.

**Comment by nicolas-grekas** [comment]
On my side, I think I'd prefer `--as-tree`.
