### ISSUE TITLE
[LDAP] Deprecated functions will be removed in PHP 8.0

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#38352]
**Symfony version(s) affected**: since 4.3.x

**Description**  
Deprecated functions since PHP 7.4:
```
ldap_control_paged_result()
ldap_control_paged_result_response()
```
used in LDAP component 
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L100
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L136

will be not available in PHP 8.0
See https://github.com/php/php-src/pull/6235 or https://github.com/php/php-src/commit/550a4f2fa89c3d3bc858aa81c62dbfa0f59f0e7c

**How to reproduce**  

**Possible Solution**  
Checking PHP Version or if method exist ?

**Additional context**

**Comment by michaljusiega** [comment]
Changes has been merged in https://github.com/php/php-src/commit/550a4f2fa89c3d3bc858aa81c62dbfa0f59f0e7c

**Comment by MCMic** [comment]
See example 5 of https://www.php.net/manual/en/ldap.examples-controls.php to see how to use the new API to use pagination controls (added in PHP 7.3).

**Comment by chalasr** [comment]
PR welcome. Don't hesitate to ping me for guidance (e.g. on slack).
