### ISSUE TITLE
override error.html.php without twig

### ISSUE THREAD

**Issue by killerwolf** [symfony/symfony#38374]
Hi,

Documentation states that twig is the only way to customize/override error*html.php templates.
https://symfony.com/doc/current/controller/error_pages.html#use-default-error-controller

i'd like to customize them without adding twig to my prod require sections.

Thanks.

**Comment by yceruto** [comment]
Option 1: Configure your own error controller in:
```yaml
framework:
    error_controller: App\Controller\CustomErrorController
```
https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-errorcontroller

Option 2: Take a look at `HtmlErrorRenderer` class and `error_handler.error_renderer.html` service, so decorating it and fallback to it on debug mode would be OK?

---

Option 1 is simpler, but it will catch there all kind of errors, api errors, debug errors, etc. so you'll have to take care, maybe fallbacking to the default system too, whereas Option 2 will take care of HTML errors only.

Also nothing guarantees that this custom html error will be displayed on kernel boot error (e.g. container build error) or a php parser error.

**Comment by nicolas-grekas** [comment]
Closing as this has been answered.

**Comment by yceruto** [comment]
@killerwolf check also https://github.com/symfony/symfony/issues/38697, in 5.2 we've added a new method to change this template.
