### ISSUE TITLE
Chat Message no working

### ISSUE THREAD

**Issue by ashokchitroda** [symfony/symfony#38399]
Message > chat > send message not received to opposite person and if opposite person send message but not received without refresh.

**Comment by tcheymol** [comment]
Hello @ashokchitroda ,

I guess you are talking about the ChatMessage from the Notifier component

Can you give us more details to help us reproduce the bug ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
