### ISSUE TITLE
http-foundation - toArray() will break Laravel projects

### ISSUE THREAD

**Issue by AegirLeet** [symfony/symfony#38400]
**Symfony version(s) affected**: 5.2.x (unreleased)

**Description**  
https://github.com/symfony/symfony/commit/f589ff41cac45239fe225c7851fd012ca37614fe adds a `toArray()` method with an `array` return type to the `Request` class. Laravel currently extends that class and also has a `toArray()` method (see [here](https://github.com/laravel/framework/blob/0bdd5c6f12cb7cb6644e484169656245af417735/src/Illuminate/Http/Request.php#L621-L629)).

Unfortunately, the declarations are incompatible, because Laravel's `toArray()` doesn't declare a return type. This will generate an error ("Declaration of Illuminate\Http\Request::toArray() must be compatible with Symfony\Component\HttpFoundation\Request::toArray(): array"). Laravel can't easily add the return type to its `toArray()` because that would break BC for anyone extending the Laravel `Request` class.

I suggested https://github.com/laravel/framework/pull/34662 as a fix in Laravel, but as @GrahamCampbell noted, that's not ideal either. I realize it isn't really a BC break or bug for Symfony itself, but seeing how many projects (any Laravel 7.x or 8.x project) this would break, maybe we can come up with some kind of solution? Just removing the return type would help.

See https://github.com/laravel/framework/issues/34660, https://github.com/laravel/framework/pull/34662

**Comment by GrahamCampbell** [comment]
This is a BC break because the class is not final.

**Comment by GrahamCampbell** [comment]
Moreover, it's not just some theoretical break, it's a break that actually affects Laravel, and Laravel cannot simply add the array return type to it's code because that would in turn be a BC break for people extending Laravel's class.

**Comment by wouterj** [comment]
Without stating anything about whether this is or isn't a BC break, it might be worth revisiting the BC policy document for return types. At the moment, the policy says [Add public method: Yes](https://symfony.com/doc/current/contributing/code/bc.html#changing-classes).

**Comment by GrahamCampbell** [comment]
I think, in general that policy is fine, since being super strict with semver prevents adding public methods to non-final classes, which in general is overkill causion, but I also think it makes sense to make an exception here, in order to avoid breaking `laravel/framework` when Symfony v5.2.0 is tagged.

**Comment by GrahamCampbell** [comment]
I would advocate for simply removing the return type in Symfony 5, and adding it back in Symfony 6 (similar to existing plans to introduce return typing in other parts of Symfony).

**Comment by wouterj** [comment]
I agree. @AegirLeet are you up to create a PR to remove the PHP return type and instead add a PHPdoc with the return type?

From the past, I've learned that changes like this generate more traction quicker (i.e. are merged quicker) if there is a PR ready to be merged. And afaics, this change should only involve a single line change.
