### ISSUE TITLE
symfony/process documentation does not mention it is included in symfony/symfony

### ISSUE THREAD

**Issue by ianef** [symfony/symfony#38401]
**Symfony version(s) affected**: 3.4.0

**Description**  
The documentation does not make clear that the component is part of the symfony/symfony bundle.

**How to reproduce**  
Create a package and use symfony/processs:^3.4 as a dependency.
The package build works fine until you try and use it in a 3.4 project, you cannot get symfony/project to install. I spent a few hours chasing this problem because of other errors thinking it was a composer issue until I noticed this:
``` bash
$ composer depends symfony/process
my-project/proj   my-test-branch  requires  symfony/process (^3.4)          
symfony/symfony  v3.4.0                                      replaces  symfony/process (self.version)  
```
symfony/symfony replaces the independent bundle. If I had known this by looking at the documentation I could have been a little less grey haired!

**Possible Solution**  
Please add a comment towards the top of the Process documentation that states that this package is actually part of the symfony/symfony package and does not not need to be included as a separate package if you are using this.

In fact why is this actually listed as a separate package anyway? Either it's a component of Symfony or it's not! Making it both is confusing and wastes a lot of development time when you get it wrong.

**Comment by dbrumann** [comment]
This is not an issue for symfony/symfony, but rather [symfony/symfony-docs](https://github.com/symfony/symfony-docs), I suppose. The composer.json in symfony/symfony states which components it replaces and each component repo links back to the main Symfony repository. Additionally the [docs overview for components](https://symfony.com/doc/current/components/index.html) states:

> The Components implement common features needed to develop websites. They are the foundation of the Symfony full-stack framework, but they can also be used standalone even if you don't use the framework as they don't have any mandatory dependencies.

Feel free to open a Pull Request over at symfony/symfony-docs with your proposed changes though, if you think that component-specific hints would be helpful as well and if you have an idea what they should say.

**Comment by xabbuh** [comment]
closing as explained then
