### ISSUE TITLE
Use env var on config framework.disallow_search_engine_index throw an error

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#38412]
I am using this config :

**config/packages/framework.yaml** : 
```
framework:
    disallow_search_engine_index: '%env(bool:DISALLOW_SEARCH_ENGINE_INDEX)%'
```

**.env :** 
```
APP_ENV=dev
DISALLOW_SEARCH_ENGINE_INDEX=true
```

Now i have the folowing error : 
```
  Environment variables "bool:DISALLOW_SEARCH_ENGINE_INDEX" are never used. Please, check your container's configurat  
  ion.                             
```                                                                                    
Whats is the problem ?

**Context :** 
"symfony/framework-bundle": "5.0.*",
PHP 7.4.11 
Linux acantepie 5.8.12-arch1-1

**Comment by chalasr** [comment]
The problem is that using env vars for this config option is not supported. 
Config options are not all meant to be set via env vars. 

Given that the default value for this option depends on the debug mode being enabled or not, I don't see the need for changing its value dynamically without clearing caches.

What is your use case? Can't you use a (non-env) container parameter?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by acantepie** [comment]
@chalasr I can use a (non env) parameters. I can override config using packages/prod 

But i have a strange behaviour if i am trying to doing this : 

```
parameters:
    dsei: '%env(bool:DISALLOW_SEARCH_ENGINE_INDEX)%'

framework:
    disallow_search_engine_index: "%dsei%"
```

disallow_search_engine seems always setted to true even if DISALLOW_SEARCH_ENGINE_INDEX was setted to false.

**Comment by jderusse** [comment]
all parameters does not accept env variable.
see explanation in similar issue https://github.com/symfony/symfony/issues/38915#issuecomment-719971021
