### ISSUE TITLE
[Routing] add Multiclass per file loader

### ISSUE THREAD

**Issue by ybenhssaien** [symfony/symfony#38414]
**Description**  
Since the [AnnotationFileLoader](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationFileLoader.php) loads annotation on one class per file (which is a PSR recommendation) the framework may be able to load annotations from multiple class in the same file (may be usefull in same cases like a DefaultController with default actions ...)

The idea here is to add a `AnnotationMultipleClassFileLoader` with `annotations` type key to support multiple class per file declaration

**Example**  
```php
<?php

namespace App;

use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(path="/", name="home")
 */
class IndexController
{
    public function __invoke()
    {
        return __METHOD__;
    }
}

class TestController
{
    /**
     * @Route(path="/test.{format}", name="test", requirements={"format": "\w+"}, defaults={"format": "html"})
     */
    public function test()
    {
        return __METHOD__;
    }

    /**
     * @Route(path="/test1.{format}", name="test1", requirements={"format": "\w+"}, defaults={"format": "html"})
     */
    public function test1()
    {
        return __METHOD__;
    }
}
```

## `AnnotationFileLoader` Vs `AnnotationMultipleClassFileLoader` : 
The first dump `Annotation file` is loaded with  `AnnotationFileLoader` while the second `Annotation file multiple class` is loaded with `AnnotationMultipleClassFileLoader` : 

![image](https://user-images.githubusercontent.com/7301643/95041941-788ad880-06d8-11eb-943a-e36b01b51a89.png)

**Comment by jkufner** [comment]
Multiple classes in a single file is a bad practice. It degrades code quality over time. Do we want to support that?

**Comment by ybenhssaien** [comment]
No need to support this feature, a separate doc merge request is already merged to mention this behaviour as a caution.
