### ISSUE TITLE
[Http Client] Support a "Fallback strategy" into the Retryable Http client

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#38415]
**Description**  

I've just noticed that a new Http client was merged into Symfony thanks to @jderusse &  @weaverryan (kuddos btw).

I've worked on Resilient applications the last two years while improving the PrestaShop CMS in my previous job and I've end up
creating our very own library that implements the [Circuit Breaker](https://martinfowler.com/bliki/CircuitBreaker.html) design pattern: https://github.com/loveOSS/resiliency.

This design pattern decorates any (HTTP) client and implements 2 patterns:
* the **Retry** pattern;
* the **Fallback** pattern;

Can we imagine the declaration of a class (or an event ?) that could have the responsibility to return a response if the server is unavailable ?

This way, every Symfony (HTTP-dependent) application could be resilient by design. 

**Example**  

I'm not sure about the implementation it should have into Symfony, but this is how it [works](https://github.com/loveOSS/resiliency/blob/main/tests/CircuitBreakerWorkflowTest.php#L47
) in Resiliency and in most of non PHP libraries that provide this kind of features.

Thanks for your time !

And feel free to close it if it's out of the scope of the framework/component.

**Comment by nicolas-grekas** [comment]
This could be interesting. It'd need someone to actually implement it though. We might close if nobody is interested in implementing it at some point.

Some challenges I foresee:
- currently, `RetryDecisionInterface` doesn't give control to the maxRetry limit. This means a half-open/closed circuit breaker could not be implemented with it.
- while a passthru as managed by `AsyncResponse` can replace/alter the body of a response, I'm not sure it can do so for the status code / the headers. But returning a fake response would require so.
- provided the previous point is solved, there is no mechanism in `RetryableHttpClient` to allow replacing the response.

All these points could be improved.

What would be nice, before implementing directly this proposal, is to review the current design of `RetryableHttpClient` + `Retry\*Interface` and wonder if it could be improved to pave the way for adding some circuit-breaker logic.

Note that I'm wondering if a circuit-breaker is a good idea at all here: what kind of fallback content would fit better than an error?

**Comment by mamoot64** [comment]
Hello,

> Note that I'm wondering if a circuit-breaker is a good idea at all here: what kind of fallback content would fit better than an error?

Error can breaks the output, that's why return cached response, loaded response from containers parameters or fetched the database or whatever can be an interesting fallback.

This type of fallback is a graceful degradation and it's handle by the "configuration" and not by "code". (try/catch)

**Comment by jderusse** [comment]
> Error can breaks the output, that's why return cached response, loaded response from containers parameters or fetched the database or whatever can be an interesting fallback.

cache, containers, database, all these fallbacks are not available **here**: in the http client, in an http request/response context.

Decorating the HttpClient is not right place to implement a circuit breaker. This should be done at the higher level.

**Comment by mickaelandrieu** [comment]
> Decorating the HttpClient is not right place to implement a circuit breaker. This should be done at the higher level.

I do agree with you, and I was pretty sure the Retry mechanism should not be managed by the Client itself too: that's why I've suggested one more step 😄 

I remember a little chat we had with @nicolas-grekas 1 year ago about reworking my library using the Workflow component and suggest it as a new component: we may need a real "Circuit Breaker" Component and not an out-of-scope contribution to the HttpClient Component.

> We might close if nobody is interested in implementing it at some point.

It's totally fine ! In the meantime, the Resiliency library is still there even if I don't really maintain it as I'm not working with PHP these days... 😕, you may also rely on the PrestaShop Circuit Breaker library (also created by me, but maintained by them now).

**Comment by nicolas-grekas** [comment]
Doing the retry in http client makes the logic compatible with async.
But I agree with @jderusse: http-client is too low level to provide a circuit-breaker.
Closing therefor, thanks for proposing.

**Comment by Rastusik** [comment]
> But I agree with @jderusse: http-client is too low level to provide a circuit-breaker. Closing therefor, thanks for proposing.

@nicolas-grekas how can you configure a circuit breaker on a higher level, when there is a retryable http client inside this layer? The circuit breaker would only be activated after several retries, right? Or am I missing something here?
