### ISSUE TITLE
[Security] providers become mandatory without any warning when using new authenticator system

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#38429]
**Symfony version(s) affected**: 5.2.0-beta1

**Description**  

I just try to update to latest beta and it seems that `providers` config in `security.yaml` became mandatory when enabling new authenticator manager.

Without any providers i get the following error :
![image](https://user-images.githubusercontent.com/245494/95183648-8dde3080-07c6-11eb-901d-a5d866dcc56a.png)

But in Symfony 5.1.7, it was not a big deal to not having a user provider.

**How to reproduce**  

Remove any providers and using `enable_authenticator_manager: true`

**Possible Solution**  

I would check if we have really one provider here:
https://github.com/symfony/symfony/blob/5f1c3a797247a6d54992384df00bb22741fc1c34/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L256

If not throw an exception saying, you must provide a user_provider.

I'm ready to make a PR you are fine with this solution.

**Additional context**  

I don't have any provider as I use aws cognito JWT system where user identity is in the token.

**Comment by wouterj** [comment]
Thanks for testing the beta release & reporting any errors @tyx!

This has been introduced in https://github.com/symfony/symfony/commit/907ef311bf789f5641dfc718a5a59dcd9fd5ace4 , where a Security listener has been added that automatically loads the user based on the `UserBadge`. 

There is indeed a wrong assumption that there always is a user provider, in this service: https://github.com/symfony/symfony/blob/907ef311bf789f5641dfc718a5a59dcd9fd5ace4/src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php#L78-L82

I think the best fix is to check if `count($userProviders)` equals `0` and if so, remove that service definition from the container (this can be done at the location you referenced). There is no reason not to support 0 user providers (but having a user provider *does* make your life a bit easier :) ). Are you able to make that change?

**Comment by wouterj** [comment]
status: reviewed

**Comment by tyx** [comment]
Hi @wouterj !

No problem for the PR, already on my way to make it.

But I want to be sure:
> if so, remove that service definition from the container

We talk about `security.listener.user_provider` ?

**Comment by wouterj** [comment]
> We talk about `security.listener.user_provider` ?

Correct!
