### ISSUE TITLE
Tag repository for Hacktoberfest

### ISSUE THREAD

**Issue by garak** [symfony/symfony#38427]
This year, [Hacktoberfest](https://hacktoberfest.digitalocean.com/) decided that repositories need to opt-in their participation.
To opt-in, a repository needs to have "hacktoberfest" topic (e.g. the ones that currently read as "framework php symfony symfony-bundle bundle php-framework").
It would be nice if symfony/symfony repository (and maybe also other symfony repositories too?) would add such topic.

**Comment by nicolas-grekas** [comment]
I don't think we need this tag. We're always open to contributions, and we don't want to attact ppl that are looking for t-shirts.

Closing therefor.

**Comment by garak** [comment]
It's a pity that you consider such initiative like "ppl that are looking for t-shirts".

**Comment by nicolas-grekas** [comment]
Don't get me wrong, that's not what I wrote nor what I meant. Hacktoberfest is a nice initiative. We're also always open to contributions. But see what happened in recent days on so many repos.

**Comment by garak** [comment]
Would you mind to at least add "hacktoberfest-accepted’" label, so specific PRs can participate in?

**Comment by nicolas-grekas** [comment]
How should we decide to add this label? When ppl ask for it when they submit PRs?

**Comment by Jean85** [comment]
What happens if the PR gets merged? Does it count regardless of any labels?

**Comment by garak** [comment]
> How should we decide to add this label? When ppl ask for it when they submit PRs?

It needs to be added to https://github.com/symfony/symfony/labels first. Then, it can be added to issues and PRs. Assigning labels requires write access to repo.

> What happens if the PR gets merged? Does it count regardless of any labels?

It only counts for Hacktoberfest if repo is tagged OR if PR is tagged.

**Comment by nicolas-grekas** [comment]
label added

**Comment by romaricdrigon** [comment]
I have to admit I quite enjoyed getting the Hacktoberfest t-shirt last year, and I was somehow quite proud of it. And last but not least, it got me (and I guess many people) more active, which is great.

This year the party was ruined by spammer at the beginning. But the proposed workaround, especially the  tag over PR, is a good solution I believe. I think it would be fair for every approved PR over a `symfony/` repository to get the tag. This way, contributors are encouraged and rewarded, if they want they can get the swag, but since Symfony PR acceptation bar is quite high, spammer won't be attracted.

**Comment by TheGarious** [comment]
I give my opinion about the Hacktoberfest, last year I participated and this challenge gives "hype" for the open-source contribution (I disagree with spammers and useless PR).

BTW, I don't know how we add a label in Pull Request.

**Comment by Jean85** [comment]
> It only counts for Hacktoberfest if repo is tagged OR if PR is tagged.

I discovered that this is not (or no longer?) true! Screenshot from my profile: 

![immagine](https://user-images.githubusercontent.com/6729988/95452365-6d9aa700-0969-11eb-9f95-6841e5d5eb7e.png)

So both merging and an approval are fine to accept it!

**Comment by fabpot** [comment]
Thanks for that @Jean85. So, the question is: how can a maintainer know when they should tag a PR?

**Comment by stof** [comment]
@Jean85 see https://hacktoberfest.digitalocean.com/hacktoberfest-update Merging or approving the PR would count only when the tag is applied on the repo.

@fabpot if we don't tag the repo, we should apply the label to accepted PRs so that they can count.

**Comment by fabpot** [comment]
Understood. I've just added the topic on the repo, so PRs will now be automatically accepted as a hacktoberfest contribution.

**Comment by TheGarious** [comment]
@fabpot i think Symfony-docs and other repositories into Symfony should be got this topic no ?

**Comment by javiereguiluz** [comment]
@fabpot would it be possible to tag `symfony-docs` repo too? Thanks!

**Comment by nicolas-grekas** [comment]
I added the tag to symfony-doc
