### ISSUE TITLE
Translation: Ability to configure default domain

### ISSUE THREAD

**Issue by sjadema** [symfony/symfony#38436]
**Description**  
Symfony's Translation component has a hard coded default domain of `messages`. For our application (which has a lot of legacy), i need a dynamic default domain (the default is based on the request 'type'). It would be helpful if i could configure the default domain on the `Translator` on runtime (e.g. i could then change the default with an event subscriber). As an added bonus, make it possible to configure the default domain on compile time (as a config option for the component, our base default isn't `messages`).

I fixed this by introducing a custom `Translator` (which i needed anyway for different reasons) but i needed to overwrite the `LoggingTranslator` & `DataCollectorTranslator` as well since they hard code the `messages` domain themselves.

**Example**  

Adding to `Symfony\Bundle\FrameworkBundle\Translation\Translator`:

```php

/**
 * The default domain if no domain is passed to the translate methods.
 * @var string
 */
private string $defaultDomain;

/**
 * Determines the default domain. Has a fallback to 'messages' if no default domain is configured.
 * @param string|null $domain The domain.
 * @return string The domain.
 */
public function determineDomain(?string $domain): string {
	return $domain ?? $this->getDefaultDomain() ?? 'messages';
}

/**
 * Returns the default domain.
 * @return string|null The default domain.
 */
public function getDefaultDomain(): ?string {
	return $this->defaultDomain;
}

/**
 * Sets the default domain for the catalogues.
 * @param string|null $domain The domain.
 */
public function setDefaultDomain(?string $domain): void {
	$this->defaultDomain = $domain;
}

```

The data collector & logging translator could then retrieve the default domain from the wrapped `Translator` instead of hard coding it themselves. It's also
possible to introduce an extended `DefaultDomainTranslatorInterface` which adds support for default domain to the `TranslatorInterface`. The chosen Translator could then be configurable based on your needs (the interface contract could be satisfied with a trait).

**Comment by stof** [comment]
I think you could easily achieve that in your app by decorating the translator service with an implementation determining the domain before calling the inner translator (which would then never rely on its default value anymore as it always receive a domai explicitly).
And by choosing the right priority for the service decoration, this should work without any change to the LoggingTranslator and DataCollectorTranslator (make sure that your `DomainGuesserTranslator` is wrapping the `LoggingTranslator` rather than the opposite)

**Comment by sjadema** [comment]
You're right about decorating just the default domain logic. I needed to extend the `Translator` anyway to add cachable database support so i hadn't considered moving just the domain guesser logic to a decorator. Smart thinking!

**Comment by sjadema** [comment]
Yeah, this will work just fine. I'll close the RFC as it isn't necessary anymore :).
