### ISSUE TITLE
Missing dependencies after fresh installation

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#38448]
**Symfony version(s) affected**: 5.1 (maybe other versions too)

**Description**  
After a fresh installation with `composer create-project symfony/skeleton foo`, if i try to validate dependencies with [composer-require-checker](https://github.com/maglnet/ComposerRequireChecker) some dependencies are missing: 

```
ComposerRequireChecker 2.1.0@0c66698d487fcb5c66cf07108e2180c818fb2e72
The following unknown symbols were found:
+---------------------------------------------------------------------------------+--------------------+
| unknown symbol                                                                  | guessed dependency |
+---------------------------------------------------------------------------------+--------------------+
| Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator |                    |
| Symfony\Component\HttpKernel\Kernel                                             |                    |
| Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator               |                    |
+---------------------------------------------------------------------------------+--------------------+
```

**How to reproduce**  
```
composer create-project symfony/skeleton foo
cd foo
docker run \
    -it \
    --rm \
    -v $(pwd):/app:ro \
    steevanb/composer-require-checker:2.1.0
```

**Possible Solution**  
Add `symfony/dependency-injection`, `symfony/http-kernel` and `symfony/routing` dependencies in composer.json.

**Comment by fabpot** [comment]
Can you try again as I'm not able to reproduce?

**Comment by nicolas-grekas** [comment]
That's an issue with steevanb/composer-require-checker, which doesn't know how the Symfony project manages optional deps.
In Symfony, we don't make a dep mandatory when it's needed for an optional feature.

**Comment by steevanb** [comment]
@fabpot i've reproduced it with this 2 commands :
```bash
docker run -it -v /tmp:/app composer create-project symfony/skeleton /app/foo
docker run -it --rm -v /tmp/foo:/app:ro steevanb/composer-require-checker:2.1.0
```

@nicolas-grekas `composer-require-checker` is not my tool, i've just created the docker image to use it.
`http-kernel` is not an optionnal dep, it's used in `src/Kernel.php`, same for `dependency-injection` and `routing` (see the uses)
```php
# /src/kernel.php
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;
```

To mee it's optionnal when i use each component, but when i create a project with `symfony/skeleton` it's mandatory.

**Comment by fabpot** [comment]
As I said, when I tried to create a new project, all the files were there. So, I don't see what we can do here.

**Comment by steevanb** [comment]
All files are here that's true, but they are here "by luck": some dependencies are installed because they are in another dependency (soft dependency), but they are used in our code.

For example `symfony/http-kernel` is installed cause it's required by `symfony/framework-bundle` but we use it in our code (in `src/Kernel.php`). That's what composer-require-checker call `soft dependency`.

If someday `symfony/framework-bundle` remove `symfony/http-kernel` from it's dependencies, our application will stop working, because `symfony/http-kernel` will be deleted: we have to add it in root `composer.json` too.

https://github.com/maglnet/ComposerRequireChecker scan it.
