### ISSUE TITLE
symfony/console (v5.1.7)

### ISSUE THREAD

**Issue by flacerte** [symfony/symfony#38447]
**Symfony version(s) affected**: 5.1.7

**Description**  
When I try to update symfony/console with composer I get a trojan detection by Windows 10 security

**How to reproduce**  
composer update

**Possible Solution**  

**Additional context**

**Comment by flacerte** [comment]
Here's the description of the Trojan detected: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fForetype.A!ml&threatid=2147724345

**Comment by fabpot** [comment]
Nothing we can do.

**Comment by fermevc** [comment]
Same here.
Yesterday, Laravel installation finished without issues.
Today, during clean Laravel install (Composer cache cleared) "Symfony/Console 5.1.7 zip file" is blocked/quarantined by Window Defender because of "Trojan:Win32/CryptInject!ml" and installation process stops with error. I'm not saying you should do anything, but maybe you could give us a bit more information what we can try to do insted of closing the issue report.

**Comment by fabpot** [comment]
I'm not using Windows, so not sure what you can do. As you're not the only one to have the same issue, perhaps you can report it to Microsoft?

**Comment by OndrejBakan** [comment]
@fabpot You, as a developer, could submit the package for malware analysis? https://www.microsoft.com/en-us/wdsi/filesubmission

Users can submit files too.

**Comment by lpj145** [comment]
Same thing here: 
![image](https://user-images.githubusercontent.com/11980109/95336855-86cb2700-0887-11eb-859a-1d74d3426c6f.png)

**Comment by lpj145** [comment]
Solving issue: 
![image](https://user-images.githubusercontent.com/11980109/95337180-f93c0700-0887-11eb-99e9-e303d0a39d59.png)

Force "symfony/console": "5.1.6"

**Comment by fabpot** [comment]
Problem should be solved now.

**Comment by kamerat** [comment]
For me, even after locking console to 5.1.6 in lock file, I still got a threat.
Removing `dist` from composer.lock under `"name": "symfony/console"` and doing a new install solved it for me.

**Comment by fermevc** [comment]
@fabpot 
I can confirm that the problem is solved. No issues found during clean Laravel 8 install.
