### ISSUE TITLE
[Messenger] Implement an ExecuteAfterDateStamp

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#38459]
**Description**  
Currently the component has a `DelayStamp()`.

It accepts the amount of seconds to wait before to process the message.

It is really helpful.

However, there are situations where I need to set the execution on a defined future date.

In this case, I need to do the calculations on my own, to calculate the diff and transform it in seconds, then set those seconds in the `DelayStamp`: nothing complex, but this is a use case I have often.

So, it would be useful to have a `ExecuteAfterDateTimeStamp` that automatically does all the calculations: we only need to pass it a future `DateTimeInterface` object.

**Current workaround**

I currently use a factory method `ExecuteAfterDateStamp::executeAfter()` that basically returns the calculated `DelayStamp`.

The code is below.

**Example**  

```php
use Symfony\Component\Messenger\Stamp\DelayStamp;

/**
 * Creates a DelayStamp starting from a date in the future.
 */
final class ExecuteAfterDateStamp
{
    /**
     * Disable instantiation.
     */
    private function __construct()
    {
    }

    public static function executeAfter(\DateTimeInterface $executeAfter): DelayStamp
    {
        $now  = (new \DateTimeImmutable())->format('U');
        $diff = \abs($executeAfter->format('U') - $now) * 1_000;

        return new DelayStamp($diff);
    }
}
```

**Other context**

I'm just starting understanding the mechanics of the Messenger Component.

From what I've seen reading the code, the `DelayStamp` is used by transports directly (ex.: https://github.com/symfony/doctrine-messenger/blob/master/Transport/DoctrineSender.php#L46).

So I think that implementing a new `ExecuteAfterDateTimeStamp` requires rewriting also all the senders to understand the new stamp.

**Possible solutions**

### Solution 1: static facttory method
Maybe a better and easier solution is to create implement the static method I provided directly in the `DelayStamp` class, so we will be able to do something like this:

```php
$delayStamp = DelayStamp::executeAfter($futureDate);
``` 

A solution that doesn't require much effort, is practical and, maybe, also more logic.

### `ExecuteAfterDateTimeStamp extends DelayedStam`

Not so complex to understand: simply the new stamp extends the already present `DelayedStamp` and passes it the calculated value.

**Comment by Nyholm** [comment]
I think your current workaround makes a lot of sense. The message component is not really a job scheduler. The delay stamp is basically just to "back off" for a second or two after the handler errored. 

Also be aware that some implementations (like AWS SQS) does not support very long delays. Ie, you cannot put a message on SQS that will run next week. 

Like #38463; I like the idea, I can see that it is useful in some specific scenarios. But I dont think this is a good idea to move in to core.

**Comment by maxhelias** [comment]
Related to https://github.com/symfony/symfony/pull/36512

**Comment by Aerendir** [comment]
@Nyholm , I understand your point... Please, let me reformulate your phrase: "The message can be used as a job scheduler, but not all transports are suitable for this purpose (ex.: AWS SQS), so keep attention to the transport you use"... Do you think this reformulated phrase is acceptable?

@maxhelias , thank you for the link... So, what to do now?

**Comment by Nyholm** [comment]
Thank you @maxhelias for the link. 

I am 👎 to a `ExecuteAfterDateStamp`. 

I am okey with a new factory method to `DelayStamp`. Making it `DelayStamp::to(\DateTimeInterface date)` as @ogizanagi suggested makes sense. 

@Aerendir if you would like, feel free to add a PR for that.

**Comment by Aerendir** [comment]
Ok @Nyholm , I prefer the factory method, too...

I've posted a message in the discussion of the PR: waiting for feedback from the others involved...

**Comment by Nyholm** [comment]
No need to wait. 5 people already given that thumbs up. =)

**Comment by Guikingone** [comment]
It looks like you're trying to schedule the consumption of messages depending on dates (as @Nyholm said, Messenger is not built to handle this type of workload).

Maybe it could be a good idea to look at bundles like the one from @kbond : https://github.com/zenstruck/schedule-bundle, this, you can schedule the Messenger command to execute messages depending on a specific date?

**Comment by Aerendir** [comment]
@Guikingone , I developed a bundle for this task: https://github.com/Aerendir/bundle-commands-queues

It works very well, but if I can delegate the development/maintenance, then I will... And if doing this I can contribute to a bigger and better supported OS project, then I will...

So, I'm going to investigate the possibilities of deprecating my bundle in favor of Messenger (as I already did).

Messenger is perfect to do this kind of tasks: you have only to configure it well... Maybe in the intentions it is not meant to be used this way, but it is anyway suitable for this kind of tasks...

IMHO...

Why do you think it isn't?

**Comment by Aerendir** [comment]
@Guikingone , I've given a look at the bundle you linked.

As far as I understand, it is anyway tied to the concept of "cronjob".

I want to completely untie from that concept as it is really complex to handle some kind of tasks using cronjobs.

Without speaking about the fact of configurations that doesn't allow the use of traditional cronjobs (for example on Heroku, where it is a bit complex to configure them using only one backend dyno)...

**Comment by Guikingone** [comment]
IMO (I can be wrong and I'm probably wrong 😄 ), Messenger is built to dispatch and consume messages, nothing more, it can handle the whole lifecycle of a message but not the "infrastructure" that use Messenger. 
The need here is to delay the consumption of the message, actually, Messenger's worker cannot handle this behaviour (I'm sure it could thanks to some refactoring) and IMHO, it should not be in charge of this.

A scheduler is built to "schedule" tasks that can be commands, shell scripts, etc, this way, a scheduler is capable of handling the "infrastucture" aspect of the Messenger usage aka launching the command, notifying if it fails and so on. 

If I look at the bundle, here's the first thing that I see: 

> It is possible to run a single job or start a daemon that listens for new jobs and processes them as they are pushed into the queue.

That's IMHO, what a scheduler is for, it run a daemon that execute repetitive or single job, this job could be a command that launch Messenger with specific arguments/options. 

When it comes to the bundle and traditional cronjobs, some PAAS/SAAS sometimes offer things like HTTP based scheduler and so on, maybe @kbond bundle can be improved with this kind of feature?

Again, that's just my vision of the issue here, I'm probably wrong but trying to solve an infrastructure need with an "application" component is IMHO, an anti-pattern.

**Comment by Aerendir** [comment]
@Guikingone , I understand what you are saying and I generally agree with what you are saying.

What you are saying is this:

1. Dispatch the message
2. The Messenger daemon receives the message
3. The received message creates/schedules the command to be executed
4. The daemon pick the scheduled command
5. The daemon executes it.

What I'm saying, instead, is this:

1. Dispatch the message
2. The messenger daemon receives the message
3. The received message is executed LIKE a scheduled command

Am I understanding right?

I think I'm...

Then, in my concrete situation, I know there are differences, I know Messenger is not the best tool for the job (for example, it cannot pick 50 messages at the same time - like, for example, asked here https://github.com/symfony/symfony/issues/36910 - and I agree it should not) and I know that I'm practically creating a "debt" in my application.

I'm exploring the use of Messenger and I'm understanding the differences with my bundle (and the one you linked) and I'm understanding that they MUST stay different because different are the their purposes.

Thank you for this discussion that is helping me to better understand the subtle differences that exists.

**Comment by Guikingone** [comment]
Actually, here's my idea: 

- Call the MessageBus and dispatch your messages
- Create a command that it's executed thanks to a scheduler and that call the consume command of Messenger (with some arguments/options if needed)
- The commande consume your messages thanks to the scheduler and based on an expression/start date/end date (some scheduler support ISO 8601 so it can easily be extended to consume during a certain amount of time)

The idea is to have a daemon (background or not) that launch the Messenger command in order to consume the messages.

I'm not saying that this is the best solution but that's just my "vision" of a solution to the problem that you're facing 🙂 .

**Comment by kbond** [comment]
Just some notes on [zenstruck/schedule-bundle](https://github.com/zenstruck/schedule-bundle):

1. In [this doc](https://github.com/zenstruck/schedule-bundle/blob/master/doc/run-schedule.md) I describe some alternatives to using a cronjob (Symfony Cloud/Scheduled webhook) but I haven't tested. If I recall, Heroku's scheduler min frequency is 10 minutes and doesn't guarantee it runs exactly at the 10 minute mark so using the bundle here wouldn't work.
2. I have an [open issue](https://github.com/zenstruck/schedule-bundle/issues/9) for a daemon. Within the current architecture of the bundle, there are some roadblocks to implementing.
3. The bundle does not support "Message Tasks" out of the box but this is used as a [custom task example](https://github.com/zenstruck/schedule-bundle/blob/master/doc/extending.md#custom-tasks).
