### ISSUE TITLE
[Security] Microsoft Defender detecting virus on symfony/console

### ISSUE THREAD

**Issue by n123456789k** [symfony/symfony#38457]
![image](https://user-images.githubusercontent.com/32820112/95314743-93e91580-0889-11eb-87f9-979c8cf20e60.png)

![image](https://user-images.githubusercontent.com/32820112/95314793-9fd4d780-0889-11eb-8b43-765e3726bbcb.png)

Laravel app, here's the composer.json:
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "akaunting/money": "^1.2",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/sanctum": "^2.4",
        "laravel/tinker": "^2.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "yab/laravel-scout-mysql-driver": "^3.0"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "knuckleswtf/scribe": "1.6.0",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ]
    }
}
```

**Comment by fancyweb** [comment]
Duplicate of https://github.com/symfony/symfony/issues/38447.

**Comment by n123456789k** [comment]
There should be one pinned as this is an ongoing issue and shouldn't be closed. Would stop duplication.

**Comment by n123456789k** [comment]
Ping to @fabpot - Can we get this pinned and an up to date open discussion, it's going to be a high traffic issue i believe as it stops the install of certain frameworks on windows.

**Comment by garas** [comment]
Bad zip is in https://api.github.com/repos/symfony/console/zipball/04c3a31fe8ea94b42c9e2d1acc93d19782133b00.

```
- Downloading symfony/console (v5.1.7)
Downloading https://api.github.com/repos/symfony/console/zipball/04c3a31fe8ea94b42c9e2d1acc93d19782133b00
[302] https://api.github.com/repos/symfony/console/zipball/04c3a31fe8ea94b42c9e2d1acc93d19782133b00
Following redirect (1) https://codeload.github.com/symfony/console/legacy.zip/04c3a31fe8ea94b42c9e2d1acc93d19782133b00
[200] https://codeload.github.com/symfony/console/legacy.zip/04c3a31fe8ea94b42c9e2d1acc93d19782133b00
```
Same URL is used for 5.1.6 as it is same commit.

If I open with 7zip and rename root folder inside from `symfony-console-04c3a31` to `symfony-console-04c3a3x`, zip is _clean_, but goes 132KB to 130KB. It is something wrong with zip itself, not its contents. Some hidden metadata or something.

Downloading same files from alternate URLs are clean:
https://github.com/symfony/console/archive/v5.1.7.zip
https://github.com/symfony/console/archive/04c3a31fe8ea94b42c9e2d1acc93d19782133b00.zip

**Comment by fabpot** [comment]
Problem should be solved now.

**Comment by n123456789k** [comment]
Not fixed @fabpot

**Comment by nicolas-grekas** [comment]
The fix might need some time to be propagated to packagist then to your composer.
Clear caches.

**Comment by n123456789k** [comment]
@nicolas-grekas Do we know what the issue was?

**Comment by nicolas-grekas** [comment]
A false-positive from MS Defender. We just put the tag v5.1.7 on a new commit hash (same exact code) and that fixed the issue...

**Comment by fabpot** [comment]
Just bad luck really :)
