### ISSUE TITLE
[HttpClient] client timeout doubled when streaming response

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#38498]
**Description**  
When stream a response with `$client->stream($response)` the time take to stream the content, is not taken into account by the __destructor.
Meaning, the request is played twice longer as expected.  

**How to reproduce**  
```
$client = HttpClient::create(['timeout' => 3]);           // 3 seconds timeout
$response = $client->request('GET', 'https://httpstat.us/200?sleep=5000#'); // sleep for 5 seconds
$start = time();
try {
    foreach ($client->stream($response) as $chunk) { // Triggers an EXPECTED idle timeout after 3s
    }
} catch (\Exception $e){
    echo $e->getMessage().PHP_EOL;
}
echo (time()-$start).PHP_EOL;
try {
    unset($response);                    // Try again for 3s :( <= unexpected
    echo 'OK'.PHP_EOL;
} catch (\Exception $e){
    echo $e->getMessage().PHP_EOL;
}
echo (time()-$start).PHP_EOL;  // At this end, my script run 5 seconds instead of 3 (defined by the initial timeout)
```

generates
```
Idle timeout reached for "https://httpstat.us/200?sleep=5000".
3
OK
5

```

**Comment by nicolas-grekas** [comment]
That's expected actually. Timeouts are not fatal errors, they're just opportunities to give control back to the code. If you want a timeout to cancel the request, you must cancel it explicitly (in the foreach).
If you don't, the timeout still applies when the destructor waits for headers.
