### ISSUE TITLE
[Console] "pcntl_signal_get_handler() has been disabled for security reasons" during installation

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#38496]
**Symfony version(s) affected**: 5.2-dev (0000dfe)

**Description**  
When running the Symfony CLI to install the 5.2 dev, I get this error:

```
Symfony operations: 3 recipes (41e56f6eef7707ea357a0a4dd6d9d3b8)
  - Configuring symfony/framework-bundle (>=5.2): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=5.1): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=5.1): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In SignalRegistry.php line 28:
!!
!!    Warning: pcntl_signal_get_handler() has been disabled for security reasons
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

  unable to run /usr/local/bin/composer create-project symfony/skeleton /home/wouter/projects/local/symfony/sf-52 5.2.x@dev: exit status 1
```

I never explicitly disabled any functions, so it seems like it ships as default settings on some distributions (for reference, I'm using Debian with Sury's PHP repository). Googling online, it seems like the `pcntl_*()` functions are one of the functions that are more frequently disabled.

Even more, when commenting this line in my php.ini, it seems like Symfony CLI (4.19.2) explicitly disables these functions:
```
§ php -r "var_dump(ini_get('disable_functions'));"
Command line code:1:
string(0) ""

§ symfony php -r "var_dump(ini_get('disable_functions'));"
Command line code:1:
string(384) "pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,"
```

**How to reproduce**  

```
symfony new --version=next
```

**Possible Solution**  

* Should we add a friendlier error message if this function is disabled? (or maybe just skipping the new signal features if this function is disabled?)
* Or should we add this to the Symfony installation requirements (in the docs and in the requirement checker)?

**Additional context**  
-

**Comment by stof** [comment]
@fabpot why is the symfony CLI disabling these functions ?

**Comment by fabpot** [comment]
Symfony CLI doesn't do anything, I suppose that `symfony php` is not the same PHP version as `php`.

**Comment by wouterj** [comment]
Oh, after a little debugging I found out that `symfony php` also includes `~/php.ini`, while my normal `php` doesn't. In here, a complete PHP config file was located, again including this disable rule. Commenting that line out as well has fixed this.

This still poses the question whether we should fail a bit less hard here? E.g. `if (!\in_array('pcntl_signal_get_handler', ini_get('disable_functions'))` and then throw an exception or disabling the signal registry.

**Comment by fabpot** [comment]
Indeed, I think we should not fail at all and only fail is the signal registry is used.

**Comment by wouterj** [comment]
@fabpot "only fail if the signal registry is used". Do you have an idea how this should be done? When looking at `Application`, there are 2 ways its used: https://github.com/symfony/symfony/blob/9f6d604b5205e090aac5d76e55e4ef1c053c482e/src/Symfony/Component/Console/Application.php#L288-L289 https://github.com/symfony/symfony/blob/9f6d604b5205e090aac5d76e55e4ef1c053c482e/src/Symfony/Component/Console/Application.php#L956-L957

The second case is easy to catch: if the command isn't subscribing on signals, it's not used.  
However, the first one seems very hard to discover as there is no way to see if a listener is listening for that event.

**Comment by lyrixx** [comment]
> However, the first one seems very hard to discover as there is no way to see if a listener is listening for that event.

Is it not possible with the follow method?
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/EventDispatcher/EventDispatcherInterface.php#L74

---

If not, I propose the following path:

We should not listen any signal by default, and so empty this array: https://github.com/symfony/symfony/blob/9f6d604b5205e090aac5d76e55e4ef1c053c482e/src/Symfony/Component/Console/Application.php#L92-L94

So, if the array is not empty **and** the function is not available => throw a better exception

And to make it more user friendly, we could add a method to "fill" this array. like this it would become option.

**Comment by wouterj** [comment]
> Is it not possible with the follow method?

That would require restricting the event dispatcher type. At the moment, it uses the event dispatcher contract, which only has a `dispatch()` method: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Contracts/EventDispatcher/EventDispatcherInterface.php

Your proposal makes sense to me (someone who doesn't know anything about console signals). :)

**Comment by chalasr** [comment]
Alternative proposal in #38589
