### ISSUE TITLE
[Kernel] Lifecycle hooks

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#38494]
**Description**  

Hi everyone 👋 

I'm creating this issue (as a feature request, I'm not sure about this) due to a recent "limitation" that I'm facing, here's the context: 

- I'm currently working an a `Scheduler` experimentation, the idea is to bring the capacity of scheduling tasks in Symfony (which can be commands, shell scripts, etc), for now, the "internal logic" is done and I'm working on minor improvements (DataCollector, DX, etc), this way, I'm working on bringing "shortcuts" to ease developer usage of the experimentation/component.

The problem is: 

- I'm trying to make the Kernel (the one called in `public/index.php`) capable of scheduling tasks thanks to a specific method (called `schedule(SchedulerInterface $scheduler): void` for now and defined in an interface `SchedulerAwareInterface`)

The issue is: 

- As the kernel is synthetic, I cannot interact with it (I've tried to use `addMethodCall()` but nothing) or define "hooks" directly via the container. 

The idea is: 

- What if we have hooks like the one provided by `MicroKernelTrait` but available every time (maybe things like `preCompilation()` and `postCompilation()` which can call methods defined in interfaces/classes tagged via `kernel.hooks`)?

**Example**  

The implementation (note that this is the final usage, not the "internal" logic): 

```php
<?php

use ...;

interface PreBootHookInterface
{
    public function addHooks(KernelInterface $kernel): void;
}
```

```php
<?php

use ...;

interface PostBootHookInterface
{
    public function addHooks(KernelInterface $kernel): void;
}
```

I'm not sure about the interfaces/methods (as it will probably impact the kernel lifecycle) and I don't know if this idea could fit into the actual kernel but it could be a good idea IMHO, again, I could be wrong and I'm probably wrong about this kind of "edge cases" but as we already have pre/post controller hooks thanks to the `EventDispatcher`, having the same idea in the kernel could be something interesting IMHO. 

Thanks again for the feedback and have a great day 🙂

**Comment by Nyholm** [comment]
Ah, I see you are going for the heart of Symfony =)

I assume you are aware of the [Symfony events](https://symfony.com/doc/current/reference/events.html) for the flow of the request. Those events are for when you want to "hook" into the request flow. Ie when `public/index.php` is called. 

It also seams like you want to do things when the container is built. The container should be built once, then we deploy the app to prod and the container is never built again. If you want to hook in the the build process I suggest you look into [Compiler passes](https://symfony.com/doc/current/service_container/compiler_passes.html). 

I believe that you can "hook" into everywhere you should (based on good software design), but it might be tricky to find out exactly where and how.

**Comment by ro0NL** [comment]
AFAIK you can handle pre/post cases in Kernel::boot() already :/ to obtain a service at this point it must be public.

An interesting thought is to be able to inject services into the kernel after booting, similar like eg. controller arguments are injected at call time.

**Comment by fabpot** [comment]
"I'm trying to make the Kernel (the one called in public/index.php) capable of scheduling tasks thanks to a specific method (called schedule(SchedulerInterface $scheduler): void for now and defined in an interface SchedulerAwareInterface)"

Why?

**Comment by Guikingone** [comment]
@Nyholm Yes, I've tried to play with CompilerPasses but it seems that the kernel is not called even if I add a tag on it thanks to an interface, the tag and `addMethodCall` directives are set then nothing once the kernel is ready, that's why I was thinking about kernel hooks which can be called during the boot phase.

I can play with events (maybe `kernel.request`) but once the kernel is set in the container, the method is no longer available.

@ro0NL I was thinking about controller arguments which are injected during call time, maybe that's a solution to the "issue" that I'm facing, the thing is, arguments are resolved via events so maybe it's too late to schedule the tasks/call methods? 🤔 

@fabpot The idea is to be able to schedule the tasks when the app boot, this way, the tasks are defined once and for all and we have a single "entry point" that schedule all the tasks once. 

Maybe that's a wrong way of thinking, I agree that it seems weird, the idea is to be able to schedule tasks outside of the controllers/commands/etc, a little bit like it's done for the routes/configuration loading 🤔 

The thing is, outside of the kernel, everything is working great, controllers/commands/services can schedule tasks and trigger the logic but the kernel cannot, maybe I'm trying to do something which is an anti-pattern 😅

**Comment by Nyholm** [comment]
It sounds like you have a list of scheduled items. You want to make sure they run as often as possible, Ie, every time a visitor hits your application you want to check "Should I run a scheduled task?"

For that use case you should look at the `kernel.request`. 

-----

Note that compiler passes only run when you are compiling the container. You only compile the container when your cache is cold/empty. 

-------

I'm closing this issue as we should not add `PreBootHookInterface` or similar. It seams like the nature of this issue is more for support. I've given you some links and info already. Feel free to join the [#support channel on slack](https://symfony.com/support) and ask your question there.
