### ISSUE TITLE
[HttpClient] Memory leak in CurlHttpClient

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#38492]
**Symfony version(s) affected**: 4.4

**Description**  
The `CurlHttpClient` has a memory leak which seems to have been caused by this PR #35674 .
When an exception occurs the `CurlResponse::close` method never gets called from `__destruct` cause of the PR & the handler never gets unset from the `CurlClientState::$openHandles` & `CurlClientState::$handlesActivity` arrays. Over time this leads to a lot of handlers piling up in the memory, causing a memory leak. I've notice this while using the HttpClient in a Messenger handler.

**How to reproduce**  
```php
class MyMessageHandler implements MessageHandlerInterface
{
    //...

    public function doSomething(MyMessage $myMessage): void
    {
        //...
        try {
            $this->httpClient->request(/*...*/);
        } catch (HttpExceptionInterface $e) {
            //...
        }
    }
}
```

**Additional context**  
![image](https://user-images.githubusercontent.com/2445045/95517864-27bdfd00-09c2-11eb-9030-37cdd0cb28ef.png)

**Comment by Nyholm** [comment]
I can confirm that `symfony/http-client: 4.4.15` and `5.x-dev` has this issue. 

```php
<?php

use Symfony\Component\HttpClient\CurlHttpClient;

include __DIR__.'/vendor/autoload.php';

$client = new CurlHttpClient();

$start = 0;
for($i=0; $i<20; $i++) {
    try {
        $client->request('POST', 'https://example.com/foo');
    } catch (\Throwable $exception) {

    }

    if ($i === 5) {
        $start = memory_get_usage();
    }
}
$end = memory_get_usage();

if ($start < $end) {
    echo 'MEMORY LEAK!!'. PHP_EOL;
}

echo 'Start:', $start / 1024 / 1024, PHP_EOL;
echo 'End:', $end / 1024 / 1024, PHP_EOL;
```
