### ISSUE TITLE
[Http Client] RetryableHttpClient, HttplugClient and sendAsyncRequest issue

### ISSUE THREAD

**Issue by Jibbarth** [symfony/symfony#38509]
**Symfony version(s) affected**: 5.2.0-BETA1

**Description**  
I tried the "RetryableHttpClient". It work perfectly when it decorate the HttpClient. when I using it inside a HttplugClient with `sendRequest`, everything is ok. But with `sendAsyncRequest`, I got a strange error :

```
In AsyncResponse.php line 241:
 
  A chunk passthru must yield an "isLast()" chunk before ending a stream.
```

It don't call nor on the `onFullfilled` and the `onRejected` methods

**How to reproduce**  

Simple reproducer : 

```php
<?php
// ...
$client = new RetryableHttpClient(HttpClient::create());
$httplugClient = new HttplugClient($client);
$request = $httplugClient->createRequest('GET', 'https://httpbin.org/status/429');

$httplugClient->sendAsyncRequest($request)
    ->then(function ($response) {
        dump($response);
    }, function ($reject) {
        dump($reject);
    });
```

**Possible Solution**  

**Additional context**

**Comment by Nyholm** [comment]
I can confirm this bug. I've tried fixing it but I didn't get far.. 

Ping @jderusse maybe you can help?
