### ISSUE TITLE
Symfony Messenger: Send logged messenger errors per email (via swift_mailer)?

### ISSUE THREAD

**Issue by ahmed-bhs** [symfony/symfony#38512]
I've configured monolog to send errors via email as described in the symfony docs here: https://symfony.com/doc/4.3/logging/monolog_email.html

Works well with all errors happing during a request, as well as console command errors.
But it does not send emails for errors which occurred during the handling of a messenger message. 

Errors are shown when running the consumer `bin/console messenger:consume async -vv` and they also show up in prod.log like this:
`[2020-01-10 12:52:38] messenger.CRITICAL: Error thrown while handling message...`

Thanks for any hints on how to set up monolog to get messenger errors emailed too.

**Comment by noniagriconomie** [comment]
As the messenger worker is a background process that « never » stop until stopped/killed, i think logs are buffered and not streamed by email directly 

When the worker stop, did you get those emails?

**Comment by ahmed-bhs** [comment]
In fact monolog `swift_mailer` type use <a href="https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Monolog/Handler/SwiftMailerHandler.php">SwiftMailerHandler </a>
wish also implements reset interface and use memory spool by default wish keep all emails in buffer until it is destructed, so till  the end of request :
* onKernelTerminate
* onCliTerminate
* OR till reset method is called, which means that for messenger worker no emails will be send ever because ther's no instant flush - all of them will be kept in in-memory buffer, and probably lost if the process will be killed.

To solve this, we can just disable tje default spool ``memory`` setting for swiftmailer.
Another solution is to flush emails after `WorkerMessageFailedEvent`  event gets fired, we implement an event subscriber to do it for this.


    use Symfony\Component\EventDispatcher\EventSubscriberInterface;
    use Symfony\Component\Messenger\Event\WorkerMessageFailedEvent;
    use Symfony\Component\Messenger\Event\WorkerMessageHandledEvent;
    use Symfony\Contracts\Service\ResetInterface;
    
    /**
     * Class ServiceResetterSubscriber.
     */
    class ServiceResetterSubscriber implements EventSubscriberInterface
    {
    
         protected ResetInterface $servicesResetter;
         public function __construct(ResetInterface $servicesResetter)
         {
             $this->servicesResetter = $servicesResetter;
         }
         public function resetServices(): void
         {
             $this->servicesResetter->reset();
         }
         public static function getSubscribedEvents(): array
         {
             return [
                 WorkerMessageFailedEvent::class => ['resetServices', 10],
             ];
         }

     }

Register your service with the right argument:


    App\EventSubscriber\ServiceResetterSubscriber:
        arguments: ['@services_resetter']
