### ISSUE TITLE
Why does Symfony throws deprecation warning logs about it`s own classes

### ISSUE THREAD

**Issue by salirzv** [symfony/symfony#38514]
**Symfony version(s) affected**: 5.1.7

**Description**  
So my symfony 5.1.7 is giving me a deprecation log : 
`User Deprecated: Since symfony/framework-bundle 5.1: The "session.flash_bag" service is deprecated, use "$session->getFlashBag()" instead.`

that is related to : 
`{▼
  /home/ali/Desktop/exchangeProject/var/cache/dev/ContainerEsfHCzk/getSession_FlashBagService.php:22 {▼
    ContainerEsfHCzk\getSession_FlashBagService::do($container, $lazyLoad = true) …
    › {
    ›     trigger_deprecation('symfony/framework-bundle', '5.1', 'The "session.flash_bag" service is deprecated, use "$session->getFlashBag()" instead.');
    › 
  }`

so this is not my code , and if I go to the symfony files and change the class , it is pointless because symfony files will be regenerated next time I update my app to 5.1.8 .
I was wondering that do I have to fix deprecation warnings that are related to the symfony it self and not the code  I wrote?
And why it`s throwing these warnings in the first place ?

![Screenshot from 2020-10-11 14-13-11](https://user-images.githubusercontent.com/58882891/95676577-ee58dd80-0bcb-11eb-8735-dc5c863d47f5.png)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce this?

**Comment by salirzv** [comment]
@xabbug 

https://github.com/salirzv/testSymfony

I made this small app , check the src/Service folder , the deprecation warning is coming from that file

**Comment by stof** [comment]
you should be injecting the SessionInterface, not the FlashBagInterface

We probably need to deprecate the `FlashBagInterface` autowiring alias too.

**Comment by salirzv** [comment]
@stof 

so how should I add flash messages inside services?

**Comment by salirzv** [comment]
I figured it out how to add flashes from service : 

```
class AddToSession {

    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    public function addToSession()
    {
        $flashBag = $this->session->getBag('flashes')->add('test' , 'from service');
    }
}
```

closing the issue , thanks for your time
