### ISSUE TITLE
[DomCrawler] The "less-than" sign truncates content

### ISSUE THREAD

**Issue by Sicaa** [symfony/symfony#38527]
Package version: `v3.4.35`

I'm aware that this is not the last version, but this is the one used in some of my projects and I did not found this issue mentioned anywhere. Correct me if I've missed something.

Seems that the `<` sign (not the `&lt;` version) makes the content to be truncated.

Reproduction:
```
$crawler = new \Symfony\Component\DomCrawler\Crawler("<html><body><p>Pain de mie < Baguette</p></body></html>");
$h = $crawler->html();
dump($h); // output: <body><p>Pain de mie </p></body>
```

Note that the `>` does not cause any trouble:

```
$crawler = new \Symfony\Component\DomCrawler\Crawler("<html><body><p>Pain de mie > Baguette</p></body></html>");
$h = $crawler->html();
dump($h); // output: <body><p>Pain de mie &gt; Baguette</p></body>
```

**Comment by stof** [comment]
that's related to the behavior of libxml (which is used by PHP when using `DOMDocument->loadHTML()`). It does not support unescaped `<` (note that older browsers have the same limitation, as the recovery of an unescaped `<` is defined only as part of HTML 5, not in HTML 4).

There is 2 solutions for that:
- make the Crawler use the HTML 5 parsing. This is done by installing `masterminds/html5` and making sure that your HTML uses the HTML5 doctype (i.e. its first non-whitespace non-comment content is `<!doctype html>`)
- escape special chars properly to be compatible with older parsers.

**Comment by Sicaa** [comment]
Understood. Thank you for your quick help!

**Comment by Sicaa** [comment]
Reopening because I just tried what you suggested and it doesn't work either.

Installed `masterminds/html5` (version `2.7.4`)
Tried:
```
$crawler = new \Symfony\Component\DomCrawler\Crawler("<!doctype html><html><body><p>Pain de mie < Baguette</p></body></html>");
$h = $crawler->html();
dump($h); // output: <body><p>Pain de mie </p></body>
```

Am I missing something?

**Comment by stof** [comment]
hmm, I missed the fact that you are using Symfony 3.4. Support for using the `masterminds/html5` parser has been added in 4.3

**Comment by Sicaa** [comment]
Ok. I'll fix that the other way. Thank you.
