### ISSUE TITLE
Exception while clearing cache in 5.2.0-BETA1

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#38547]
**Symfony version(s) affected**:5.2.0-BETA1

**Description**  
Exception  `Cannot rename because the target ".../var/cache/de~" already exists.`

**How to reproduce**  
Every second run `bin/console c:c` will fail

**Possible solution**  
The problem is in

https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L164-L173

```php
if ($oldBuildDir) { // /var/cache/de~
    $fs->rename($realBuildDir, $oldBuildDir);
} else {
    $fs->remove($realBuildDir);
}
if ($oldCacheDir) { // /var/cache/de~
    $fs->rename($realCacheDir, $oldCacheDir); // Exception
} else {
    $fs->remove($realCacheDir);
}
```

`$oldBuildDir` and `$oldCacheDir` is [equal](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpKernel/Kernel.php#L343)

**Additional context**  
This bug was introduced in https://github.com/symfony/symfony/pull/36515
/cc @mnapoli

**Comment by Nyholm** [comment]
I added a patch here: #38548 will that fix your issue?

**Comment by rtarnaud** [comment]
Still happens in 5.4.11
