### ISSUE TITLE
Lock with RedisStore: LockAcquiringException on second acquisition of lock within the same process (after TTL)

### ISSUE THREAD

**Issue by MichaelS86** [symfony/symfony#38541]
**Symfony version(s) affected**: 5.1.7

**Description**  
If I want to acquire and release twice within the same process whereby the second acquisition is attempted after the TTL, there is a LockAcquiringException which is the result of a LockExpiredException.
It seems that a lock can expire after it has been released which is an obstacle to a later re-acquisition.

IMHO it should be possible to acquire and release a lock as often as wanted.

**How to reproduce**  
```
<?php


namespace App\Service;

use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\Store\RedisStore;
use Symfony\Component\Lock\Store\RetryTillSaveStore;

class LockHelper
{
    protected $lock;

    public $initialTTL;

    public function __construct($redisHost) {
        $redis = new \Redis();
        $redis->connect($redisHost);

        $store = new RedisStore($redis);
        $store = new RetryTillSaveStore($store);
        $factory = new LockFactory($store);

        $this->initialTTL = 2;

        $this->lock =$factory->createLock('maintenance', $this->initialTTL);
    }

   // this reproduces the error
    public function testBadScenario() {
        $this->lock->acquire();
        $this->lock->release();
        Sleep($this->initialTTL+1);
        $this->lock->acquire();
        $this->lock->release();
    }

    ...
}
```

**Possible Solution**  
I am not familiar with that but maybe this has to do something with `Key $key` which should undergo some kind of a reset in `$this->lock->release()`?

**Additional context**  
The output of the test is as follows:
```
Symfony\Component\Lock\Exception\LockAcquiringException : Failed to acquire the "maintenance" lock.
 PROJECT_DIR/vendor/symfony/lock/Lock.php:108
 PROJECT_DIR/src/Service/LockHelper.php:38
 PROJECT_DIR/tests/Service/LockHelperTest.php:31
 
 Caused by
 Symfony\Component\Lock\Exception\LockExpiredException: Failed to store the "maintenance" lock.
 
PROJECT_DIR/vendor/symfony/lock/Store/ExpiringStoreTrait.php:27
 PROJECT_DIR/vendor/symfony/lock/Store/RedisStore.php:72
PROJECT_DIR/vendor/symfony/lock/Store/RetryTillSaveStore.php:54
PROJECT_DIR/vendor/symfony/lock/Lock.php:77
PROJECT_DIR/src/Service/LockHelper.php:38
PROJECT_DIR/tests/Service/LockHelperTest.php:31
```

**Comment by Nyholm** [comment]
Thank you for this issue. The reproducer script was really helpful. 

To the best of my understanding after reading the [documentation about expiring locks](https://symfony.com/doc/current/components/lock.html#expiring-locks) and the source code. I think this is the expected behavior. 

```php
$lock = $factory->createLock('maintenance', 2);
```

This will create a lock that should be valid (or auto released) after 2 seconds. Time starts when you acquire the lock. You cannot reuse the lock, then you need to create a new one.

**Comment by stof** [comment]
Well, trying to acquire it again after you released it yourselves should work IMO. I don't think there is anything preventing to re-use a lock object to acquire. btw, in the reproducing script, the lock gets released before it expires AFAICT. So this should not be a case of an expired lock.

**Comment by MichaelS86** [comment]
Thanks for your comments!

IMHO  it should not matter if a lock is manually released or "auto-released" due to expiration in terms of a re-acquisition later on. The documentation just says that it is auto-released after the expiration time.
A lock should be able to be acquired again after release anyway, no matter when or why it was released.

**Comment by MichaelS86** [comment]
> Well, trying to acquire it again after you released it yourselves should work IMO. I don't think there is anything preventing to re-use a lock object to acquire. btw, in the reproducing script, the lock gets released before it expires AFAICT. So this should not be a case of an expired lock.

Yes, it is released before expiration. I.e. in this case, the expiration time only affects the second acquisition of that lock and does not even have an effect on the first one.

**Comment by jderusse** [comment]
This is a bug. It should be possible to acquire several time in a row the same lock. And releasing the lock should not prevent acquiring it again.

**Comment by Nyholm** [comment]
Hm.. Okey. 

I'll look into it more then.

**Comment by MichaelS86** [comment]
Thanks for fixing that issue! When is the next release planned that contains that fix?
