### ISSUE TITLE
[Messenger] Automatic schema updates with redis transport requires redis to run during database migrations

### ISSUE THREAD

**Issue by natepage** [symfony/symfony#38558]
**Symfony version(s) affected**: 5.1.7

**Description**  
The event subscriber for [Automatic schema updates](https://symfony.com/blog/new-in-symfony-5-1-automatic-schema-updates) will loop over the messenger transports and check if they are Doctrine transports, if yes then it will run the schema update, great feature! However, we're having some issues with the Redis transport.

Locally, we're using redis as messenger transport. The automatic schema update subscriber instantiates all messenger transports to check if they're a Doctrine transport or not, the `Symfony\Component\Messenger\Bridge\Redis\Transport\Connection` is attempting to connect to redis in its constructor which breaks our migrations if redis isn't running.

The way around it, is to make sure that redis is running while trying to migrate the database, but I create this issue because IMHO it feels "wrong" that this messenger transport not related to the database breaks the migrations.

**How to reproduce**  
- Setup messenger transport to use redis
- DO NOT start redis service
- Run database migrations

**Possible Solution**  
Do not try to connect to redis in the `Connection` constructor but only when trying to interact with redis.

**Comment by Nyholm** [comment]
If you use the lazy option in your Redis dsn, then it will work exactly as you want. 

Edit: 
Oh, the "lazy" option is only for the cache component.... I'll see if I can make a PR to fix this.

**Comment by Nyholm** [comment]
@natepage Can you try out my patch in #38563? Please confirm that it works for you.

**Comment by natepage** [comment]
@Nyholm I've replied in the PR directly but yes! It works like a charm! Thank you 👍
