### ISSUE TITLE
Validator Regex always pass empty string

### ISSUE THREAD

**Issue by maxgorovenko** [symfony/symfony#38568]
**symfony/validator**: 4.3

**Description**  
I have a validator constraint Regex with not empty pattern '/^[a-f0-9]{24}$/i'. I believe this pattern should not pass zero length string, but it does.

**How to reproduce**  
This constraint should not pass empty string, It should pass only strings that matches the pattern (exactly 24 characters of a-f, A-F and 0-9):
new Regex(['pattern' => '/^[a-f0-9]{24}$/i']),

**Possible Solution**  
At /symfony/validator/Constraints/RegexValidator.php:36 remove check for empty string. Empty string is a string and it still can match the pattern or not.

**Additional context**  
no

**Comment by xabbuh** [comment]
That's intended. All core constraints abstain then to allow values to be optional. You need to combine the `Regex` constraint with `NotBlank` in your case.
