### ISSUE TITLE
[DependencyInjection] Cannot declare interface Stringable

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#38588]
**Symfony version(s) affected**: 5.1.7

**Description**  
I'm currently testing some applications for php 8 compatibility. Because I'm switching the runtime from 7.4 to 8.0 back and forth, it might happen, that I'm working on 8.0 with a cache that has been warmed up on 7.4. In that case I am greeted by the following exception.

<img width="1080" alt="Bildschirmfoto 2020-10-15 um 14 20 01" src="https://user-images.githubusercontent.com/1506493/96122267-8539d880-0ef1-11eb-8f63-640d12d8d54d.png">

The reason is that the DI component compiles the following line into one of the service factories (in my case `secrets.vault`) of the dumped container:

```php
include_once \dirname(__DIR__, 4).'/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php';
```

This is probably not an issue that happens on production environments. The problem however is a bit annoying for development because it forces me to manually clear the cache when switching php versions.

**How to reproduce**  
Create a Symfony application under php 7.4, run it on php 8.0.

**Possible Solution**  
* Don't compile `include` calls for polyfilled classes into the dumped container
* Compile different caches for different runtime versions.

**Comment by nicolas-grekas** [comment]
We could add a class_exists check around the class definition in the polyfill.
I'm :-1: for any generic solution, they're too costly to implement for too little benefit.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/polyfill/pull/295
