### ISSUE TITLE
console: auto activate ansi colors in github actions

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#38585]
**Symfony version(s) affected**: 4.x

**Description**  
[Github Actions added support for ansi colors recently.](https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/)

it turns out that symfony console based apps don't auto-enable syntax coloring.
initially I had reported this issue on https://github.com/composer/composer/issues/9269 but jordi would instead want a fix in symfony/console and/or Github Actions instead.

therefore I also opened a issue on the Github actions runner, without feedback yet though
https://github.com/actions/runner/issues/750

to get fancy colors on github actions, we need to manually enable `..ansi` which is tedious:
see e.g. https://github.com/redaxo/redaxo/pull/3939/files

**How to reproduce**  

run `composer install` within a github action

**Possible Solution**  
imply `--ansi` when `false !== getenv('GITHUB_ACTION')`

**Additional context**  
people work arround this problem by sprinkling additional `--ansi` flags across all the php based tools invoked within github action already, see e.g. https://tomasvotruba.com/blog/2020/09/28/how-to-add-colors-to-continuious-integration-output/

**Comment by derrabus** [comment]
> imply `--ansi` when `false !== getenv('GITHUB_ACTION')`

Is there a way we could auto-detect color support without building a workaround specific to GitHub actions? I understand that this is kind of what you're asking in actions/runner#750 already.

I don't feel confident about solely relying on that env variable. One scenario I could imagine here: You would use the Process component to run another Symfony Console based tool (e.g. your tool calls Composer for certain tasks). In that case the env variable would still be set, but auto-enabling color output is probably not desirable in that context.

**Comment by stof** [comment]
env-based detection are a bad idea. they would break scripts running things like `some-comment > output.txt`, as it would consider that output.txt supports ANSI colors...

**Comment by chalasr** [comment]
I'm closing this issue as the proposed solution does not look right. This would better be solved on GA' side to me.
