### ISSUE TITLE
Types of request param in KernelBrowser are now string instead of integer

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#38591]
**Symfony version(s) affected**: 5.2.0-beta2

**Description**  

In the request stack does now only contain strings instead of integer like before:

**How to reproduce** 

I did test sulu against the newest 5.2.0-dev and some tests are failing now a basic example looks like this:

```php
$this->client->request(
    'PUT',
    '/api/contacts/' . $contact->getId(),
    [
        'account' => [
            'id' => 5, // a integer type
        ],
    ]
);
```

If we then debug the value is now a `string`, in 5.1.7 its correctly a `integer`:

```php
$request->request->all()['account']['id'];
```

Before this was a integer with `5` and now its an string with `"5"` and so this make in our case some test fail which I think should not happen.

**Possible Solution**  

Not sure yet where and why this behaviour was changed.

**Comment by fabpot** [comment]
IMHO, you should fix your tests as everything coming from a request is a string (that's what we fixed in 5.2).

**Comment by alexander-schranz** [comment]
@fabpot In our case we are testing a JSON Api. Is there an option on the client that its able to set the client send the requestBody as json so its handled like before? Else I think it will be a lot of refactoring for some projects changing this.

**Comment by alexander-schranz** [comment]
Some background we are using the `FOSRestBundle` which converts the `json` into the `Request::request` object with its BodyListener. I think it would help many devs to introduce some kind of `jsonRequest` into the BrowserKit then. I created a PR for it #38596.

**Comment by ro0NL** [comment]
I suggested to support json payloads in $request->request consistently: https://github.com/symfony/symfony/pull/38224#issuecomment-694719959 but it was ignored :)

I agree with @fabpot, the only supported usecase is x-form-www-urlencoded data e.g. $_POST.
