### ISSUE TITLE
[DoctrineBridge] Ulid on Postgres throws error on insert

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#38599]
**Symfony version(s) affected**: 5.2.0

**Description**  
I tried to insert an ULID into a Postgres database but uppon doing so it will error out like this:
`Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "01EMRHA3S6SZRG41BKZEAKCRVE"`

**How to reproduce**  
Insert a ULID into a Postgres Database

**Possible Solution**  
Seems like it's not happy with the format. If you insert it with `toRfc4122` it works.

**Comment by nicolas-grekas** [comment]
Sure, why would an ulid fit into an uuid field? Calling toRfc4122 is the correct way to disguise an ulid as an uuid for the db.

**Comment by KDederichs** [comment]
Blegh actually I ran into a differen issue as well:
The doctrine `setParameter` on query builders will just string cast this again. 
To my knowledge there isn't a a way to hook into that one?

Tbh 2 options here:

1. Require the dev to manually cast all `setParameter` usages with `toRfc4122`
2. Make that the default toString value

Oppinions?

**Comment by stof** [comment]
> The doctrine `setParameter` on query builders will just string cast this again.

That's not true. It depends on which DBAL type is used. As the ORM does not know about the UlidType of Symfony, it cannot automatically guess it when you don't pass a type. But it you use the third argument of `setParameter` to tell Doctrine that your parameter is an UlidType, things should work.

**Comment by KDederichs** [comment]
Ah indeed it does work.
But that still doesn't make it intuitive/convenient.

**Comment by stof** [comment]
@KDederichs passing `null` as parameter type (which is the default when omitting the argument) tries to guess the right type. But the Doctrine ORM currently does not provide any extension point to extend the guessing logic to support custom types.

**Comment by KDederichs** [comment]
@stof yeah I do get that.
I'm just saying it's unintuitive in a sense that for all the other 'first party' symfony doctrine mappings you do not have to think about appending that parameter. Just this one needs it (which probably should be mentioned in a doc somewhere).
But yeah since you can not extend that particular Doctrine behavious the only way of keeping the behavious consistant with all the other types would be for ULID to output RFC4122 by default.

**Comment by stof** [comment]
The only DBAL types provided in Symfony are the UlidType and UuidType. So I think that the other types you think about are not provided by Symfony, but are the core Doctrine types
And as far as the Doctrine ORM is concerned, Symfony is *not* a first party but a third party.

**Comment by KDederichs** [comment]
Hmm I guess yeah. 
I was under the impression Symfony did have more types but I guess not. 
My bad.
