### ISSUE TITLE
Symfony ContextErrorException: Warning: unserialize() has been disabled for security reasons in /home/

### ISSUE THREAD

**Issue by saadux** [symfony/symfony#38594]
Hi Guys,

Im using symfony and i migrate my project from my localhost to my production server, 

When i execute my projet have this message error on my project

ContextErrorException: Warning: unserialize() has been disabled for security reasons in /home/xxxxx.com/bxxxxxx/htdocs/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCache.php line 76
![erreur symfony](https://user-images.githubusercontent.com/28957566/96234285-22981980-0f91-11eb-9ca7-618005d911b1.png)

help !
thanks !

**Comment by Nyholm** [comment]
Hey!

It seams like your PHP environment has removed the `unserialize` function. You should ask around on [slack or stackoverflow](https://symfony.com/support). 

Im closing this as it is not a bug or issue with symfony.

**Comment by saadux** [comment]
thanks
