### ISSUE TITLE
compatibility symfony 2.4 and php 7

### ISSUE THREAD

**Issue by saadux** [symfony/symfony#38598]
Hey,

I would like to know if symfony 2.4 is compatible with php 7, if not what is the right way to migrate the project.

thanks

**Comment by dbrumann** [comment]
It's possible to install it on PHP 7 according to the composer.json, but it is very likely there will be issues. Upgrading to a new major version is probably the best way to go. Depending on your dependencies it is possible you will not be able to upgrade to the newest version, but hopefully you can at least get to 4.4, the current LTS release. There is a page in the docs that goes into some detail on how to perform a major upgrade: https://symfony.com/doc/3.4/setup/upgrade_major.html

If you have any trouble during the upgrade process feel free to get in touch with the community, e.g. on the [Slack #support channel](https://symfony.com/slack) or on [StackOverflow](https://stackoverflow.com/questions/tagged/symfony).
