### ISSUE TITLE
Issue with Https when running symfony with istio

### ISSUE THREAD

**Issue by mikaint** [symfony/symfony#38590]
When using trusted proxies (app running on EKS with ELB) as per [documentation](https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies), things working fine. When enabling istio though, the application even though is accessible on https, `$request->isSecure()` always returns false.

I tried several ways, including the following one which I believe it should be working but I had the same issue: 

```
Request::setTrustedProxies(['0.0.0.0/0'], Request::HEADER_X_FORWARDED_ALL);
```

For running Symfony I have 2 containers, php-fpm and nginx. A 3rd container is added when enabling istio for istio-proxy (envoy)

**Comment by Nyholm** [comment]
I don’t know of istio, but if that is a proxy you need to set it to the request to show that you trust it. Doing 0.0.0.0/0. Doesn’t work (if I remember correctly). 

If you print all the http headers in the request and you will see the Ip of your proxy.

**Comment by mikaint** [comment]
It looks like envoy proxy removes the X-FORWARDED-* headers (proto & port) and as a result Symfony does not consider the request as trusted. I didn't find a way to handle this on envoy so as a temporary solution i just inject those missing header through the Istio's VirtualService.
