### ISSUE TITLE
[Uid] Fail using Uuid as Doctrine type on 5.2.0-BETA2

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#38613]
Hi,

On a personal app, after successfully upgraded to https://github.com/symfony/symfony/releases/tag/v5.2.0-BETA2,
I also wanted to test this feature https://symfony.com/blog/new-in-symfony-5-2-doctrine-types-for-uuid-and-ulid

But I have this error (web):

```
Unknown column type "uuid" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType().
You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap().
If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type.
Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes().
If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

On cli when using `symfony console doc:sc:validate`:

```
 [FAIL] The entity-class App\Entity\Reminder mapping is invalid:
 * The field 'App\Entity\Reminder#uuid' uses a non-existent type 'uuid'.
```

-----------------

What is missing? Either my config or the documentation?

All symfony/* and doctrine/* packages are at latest (I can give the full composer if needed)
PHP v7.4, MySQL v5.7

Thank you :)

**Comment by nicolas-grekas** [comment]
Can you please try with v5.2-dev? We might have fixed this already.

**Comment by 94noni** [comment]
Hi @nicolas-grekas 

What do you mean by `v5.2-dev`?

I've tried to use the `https://github.com/symfony/symfony/blob/5.x/link` file to link the latest `symfony/*` codebase with my project locally, and the problem is still here after clearing cache etc

**Comment by nicolas-grekas** [comment]
I mean the code in `5.x` yes

**Comment by 94noni** [comment]
@nicolas-grekas FYI I had to add manually to make it works with current `5.x` codebase:

```
# config/packages/doctrine.yaml
doctrine:
    dbal:
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
```

Is this required as process or the framework should take care of it?
(maybe should be added inside the blog post)

Edit: @nicolas-grekas It appears that the `RegisterUidTypePass` is not called in the doctrine bundle, waiting next release

Many thanks

**Comment by ThePeterMick** [comment]
I'm on a freshly baked `--full` project using 5.2.1 and was still getting the exact same error.

`Unknown column type "uuid" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType()`

https://symfony.com/blog/new-in-symfony-5-2-doctrine-types-for-uuid-and-ulid states you only need to have doctrine installed but actually you still need to run `composer require symfony/uid` https://symfony.com/doc/current/components/uid.html

**Comment by zemigpt** [comment]
Fresh new project with Symfony 5.2.4 and had the same problem as @peternetio 
Solved the same way with ``composer require symfony/uid`` .

**Comment by danielrestrepo** [comment]
Same here with a freshly installed Symfony 5.3

**Comment by fabpico** [comment]
Same here with a fresh install of Symfony 6.2.
This worked for me https://github.com/symfony/symfony/issues/38613#issuecomment-712301754 .
````
# config/packages/doctrine.yaml
doctrine:
  dbal:
    # ..
    types:
      uuid: Symfony\Bridge\Doctrine\Types\UuidType
````

But this also worked `composer require symfony/uid` https://github.com/symfony/symfony/issues/38613#issuecomment-792044737.
