### ISSUE TITLE
Event classes can not be mocked because they are final

### ISSUE THREAD

**Issue by Bonemeijer** [symfony/symfony#38627]
**Symfony version(s) affected**: 5.1.5

**Description**  
Certain event objects can not be mocked with phpunit because they have the "final" keyword.

And you will get the following error;
`Class "Symfony\Component\HttpKernel\Event\ControllerEvent" is declared "final" and cannot be mocked.`

This happens for
* \Symfony\Component\Form\Event\SubmitEvent
* \Symfony\Component\Form\Event\PreSetDataEvent
* \Symfony\Component\Form\Event\PostSubmitEvent
* \Symfony\Component\Form\Event\PostSetDataEvent
* \Symfony\Component\Form\Event\PreSubmitEvent
* \Symfony\Component\Console\Event\ConsoleCommandEvent
* \Symfony\Component\Console\Event\ConsoleTerminateEvent
* \Symfony\Component\Console\Event\ConsoleErrorEvent
* \Symfony\Component\HttpKernel\Event\FinishRequestEvent
* \Symfony\Component\HttpKernel\Event\ViewEvent
* \Symfony\Component\HttpKernel\Event\ExceptionEvent
* \Symfony\Component\HttpKernel\Event\TerminateEvent
* \Symfony\Component\HttpKernel\Event\ControllerEvent
* \Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent
* \Symfony\Component\HttpKernel\Event\ResponseEvent
* And probably for other events that belong to packages that I don't have installed right now

**How to reproduce**  
Try to mock ControllerEvent in a phpunit test.
For example:

```php
        /** @var ControllerEvent|MockObject $eventMock */
        $eventMock = $this->createMock(ControllerEvent::class);
```

**Possible Solution**  
Unless there is a good reason for those classes to be final, the final keyword could be removed.

**Comment by Bonemeijer** [comment]
Perhaps this should be an "improvement" and not a bug

**Comment by wouterj** [comment]
I think this is intended. An event class is just a data object, you shouldn't mock these in your tests. As a general practice, it's often good to only mock interfaces and not implementations.

**Comment by derrabus** [comment]
I agree with @wouterj. I don't really see why I would want to mock event classes.

**Comment by Bonemeijer** [comment]
Fair enough. I would agree in most cases. 

Please consider the situation where you're writing a test for an event listener that requires `\Symfony\Component\HttpKernel\Event\ControllerEvent`. The event listener is only interested in the `isMasterRequest()` method.

Option 1: You could instantiate the `ControllerEvent` and pass the following arguments:
* a mock of `KernelInterface`
* some void callback
* a mock of `Request`
* `HttpKernelInterface::MASTER_REQUEST` to indicate that it is a master request

Option 2: Or you could just mock the `isMasterRequest` method
* `$eventMock->method('isMasterRequest')->willReturn(true);`

I would say Option 1 introduces unneeded complexity to the test. The test case is much more easily broken by an update of Symfony code that the second case. The second case does exactly what it needs to, and nothing more.

**Comment by derrabus** [comment]
Option 1 is usually what I do in my tests. Although I rather subscribe to the request event if I don't care about the controller.

**Comment by lukaszgoworko** [comment]
Hi in my opinion clean interfaces for the Events are missing. You could easily mock the interface then in your tests.

**Comment by gsdevme** [comment]
Mocking out the internals of `ExceptionEvent` for example is pretty tedious for when you don't really care about the internals of "said DTO" you just want to test your actual code. Would have thought having interfaces for each public method would ease alot of this. Feel like they are stretching beyond a simple DTO given they are not that mutable either
