### ISSUE TITLE
[HttpClient] Missing response content in profiler after adding retryable http client

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#38631]
**Symfony version(s) affected**: 5.2.0-BETA2

**Description**  
Before
```
Request
[▼
  "query" => [▶]
]

Response
[▼
  "info" => [▶]
  "url" => "..."
  "response_headers" => [▶]
  "response_json" => [▶]
]
```
After
```
Response
[▼
  "buffer" => false
  "query" => [▶]
]

Response
[▼
  "info" => [▶]
  "url" => "..."
  "response_headers" => [▶]
]
```

Is this a bug or expected behaviour?

**Comment by Nyholm** [comment]
Thank you for trying out the beta release. <3

Ping @jderusse, Do you know on the top of your head? or should I try to investigate?

**Comment by jderusse** [comment]
I'm on it @Nyholm

**Comment by jderusse** [comment]
Issue is:

1) RetryableHttpClient -> decorates TracableHttpClient -> decorate CurlClient.
2) RetryableHttpClient use AsyncResponse.
3) Body reported in Profiler is buffered when user call `$response->getContent/toArray`

When user call `AsyncResponse::getContent()` it don't call `decoratedReponse->getContent()`, it steams the response instead.

The `TracableResponse::getContent` method is never called, thus never bufferise the content and never report it in the Profiler.

PR opened #38633

**Comment by Nyholm** [comment]
Lovely. Thank you.

@BoShurik Does this patch work for you?

**Comment by BoShurik** [comment]
@Nyholm Is there easy way to test PR on existing project? I tried a [patch](https://github.com/symfony/symfony/pull/38633.patch) but it's for `symfony/symfony` not `symfony/http-client`

**Comment by Nyholm** [comment]
The simplest way is just to copy the few lines from the PR. 

If it was a larger PR or your really wanted to do the "proper" way. Then you need to clone symfony/symfony, pull the fork and then use the `link` command. 
See [the docs](https://symfony.com/doc/current/contributing/code/pull_requests.html#use-your-branch-in-an-existing-project) for more details.
