### ISSUE TITLE
MicroKernel configureRoutes wrong parameter

### ISSUE THREAD

**Issue by timotheemoulin** [symfony/symfony#38634]
https://github.com/symfony/framework-bundle/blob/66583f3fdda7346a76dc9998be55128d7f617bf2/Kernel/MicroKernelTrait.php#L190

`MicroKernelTrait` call to `configureRoutes` should pass a `RoutingConfigurator` object instead of the given `RouteCollectionBuilder`.

Or have I missed something ? This now result (in my case) in no route being defined.

Deprecated: Since symfony/framework-bundle 5.1: Using type "Symfony\Component\Routing\RouteCollectionBuilder" for argument 1 of method "App\Kernel:configureRoutes()" is deprecated

**Comment by wouterj** [comment]
It [does pass the `RoutingConfigurator`](https://github.com/symfony/framework-bundle/blob/66583f3fdda7346a76dc9998be55128d7f617bf2/Kernel/MicroKernelTrait.php#L196), unless your method is still using the old signature and trying to typehint for `RouteCollectionBuilder`. The lines you're linking to are the BC layer that is used in that case.

Btw, when migrating from the routing collection builder to the configurator, please be aware that some method names have equal names, but different arguments. That sometimes causes routes to be missed (especially when importing IIRC).

If you still have this issue, can you please create a reproducer? (or at least the kernel class where you're using the `MicroKernelTrait`)
