### ISSUE TITLE
Unable to send email to other servers with SwiftMailer

### ISSUE THREAD

**Issue by romain-neil** [symfony/symfony#38655]
**Symfony version(s) affected**: 5.1.2

**Description**  
I can send email to our local domain using exchange's smtp server to local users (ex: user_a@our_local_domain) but when I try with a gmail address, I got the following error:
(Swift_TransportException)

Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
"

**How to reproduce**  
`
$message = (new Swift_Message())
                ->setSubject("The message title")
                ->setFrom($user->getExtraFields()["mail"])
                ->setTo($user->getEntry()->getAttribute('mail'))
                ->setBody($this->renderView('emails/invitation.html.twig'))
                ->setContentType('text/html')
                ->setPriority(Swift_Mime_SimpleMessage::PRIORITY_HIGH)
                ->attach($attachment)
            ;
            //We have many emails to send
            if($addresses !== false && $addresses !== "") {
                $addresses = explode(";", urldecode($addresses));
                foreach($addresses as $addr) {
                    if($addr !== "") {
                        $message->setTo($addr);
                        $mailer->send($message);
                    }
                }
            } else {
                $mailer->send($message);
            }`

**Possible Solution**  
No possible solution

**Additional context**  
This work fine with my local address

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions, please use any StackOverflow.

Thanks!
