### ISSUE TITLE
LDAP deprecated functions still in use in LTS 4.4

### ISSUE THREAD

**Issue by igorbga** [symfony/symfony#38654]
**Symfony version(s) affected**: 4.4.15

**Description**  
Some PHP ldap functions have been deprecated and will dissapear in PHP 8.0. This issue has been already addressed in issue #38352 and the changes seem to be present in branch 5.x, but not in branch 4.4, which is the current LTS version.

Although this doesn't affect functionality it pollutes the log output. In my case and using it from a command and it produces INFO level output that scares the final user.

**How to reproduce**  
Use ldap component to do a paged query:
`
$ldap->query($searchBase, $filter, [ 'pageSize' => $pageSize]);`

**Possible Solution**  
If 8.0 will not be supported in LTS 4.4 then just prepending @ to the usage of the deprecated functions might be enough.

**Additional context**  
See #38352

**Comment by W0rma** [comment]
@igorbga The mentioned symfony version 4.4.15 was released before https://github.com/symfony/symfony/pull/38392 was merged. The fix will be part of the next minor release.

**Comment by chalasr** [comment]
Indeed, the patch will be part of the upcoming 4.4.16 release.
