### ISSUE TITLE
[BrowserKit] BC-Break with casting parameters to string

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#38651]
**Symfony version(s) affected**: 5.2.0-BETA2

**Description**  
My CI/CD tests are crazy after upgrade to Symfony 5.2.0-BETA2. So...
All parameters as `null` value are casting to string. So `(string) null is '' (empty string)`.

**How to reproduce**  
```
$browserClient = self::createClient();
$browserClient->request(Request::METHOD_GET, '/url', ['string_value' => 'string', 'nullable_value' => null]);
```
```
/** @var \Symfony\Component\HttpFoundation\Request $request */
dd($request->query->all());
```

**In Symfony 5.2-BETA2**:
```
array:2 [
  "string_value" => "string"
  "nullable_value" => ""
]
```
**In Symfony 5.1 and lower**:
```
array:2 [
  "string_value" => "string"
  "nullable_value" => null
]
```

**Possible Solution**  
Workaround and ignore nullable values:

```
        array_walk_recursive($parameters, static function (&$value) {
            $value = (string) $value;
        });
```
to:
```
        array_walk_recursive($parameters, static function (&$value) {
            if (null !== $value) {
                $value = (string) $value;
            }
        });
```

**Additional context**  
See https://github.com/symfony/symfony/issues/37740 and https://github.com/symfony/symfony/pull/37755

I'm ready to make PR.

**Comment by Nyholm** [comment]
Big thank you @michaljusiega for testing the beta versions and writing so many great tickets. 

Just a quick question: 
How would a HTTP request look like for you to be able to do `dd($request->query->all());` and get the following result:

```
array:2 [
  "string_value" => "string"
  "nullable_value" => null
]
```

**Comment by michaljusiega** [comment]
> How would a HTTP request look like for you to be able to do `dd($request->query->all());` and get the following result:

You mean what the URL would look like before `HttpFoundation Request` parse it ?

**Comment by derrabus** [comment]
`http://www.example.com/some/path?string_value=string&nullable_value`

**Comment by Nyholm** [comment]
Yes, That is what I meant. URL or full HTTP text. 

@derrabus No, not really. 

<img width="642" alt="Screenshot 2020-10-20 at 23 32 44" src="https://user-images.githubusercontent.com/1275206/96646571-9ee18280-132c-11eb-85db-f277f01fb186.png">

-------

My point here is: If there is no URL or HTTP request that can generate a `dd()`-dump like that, then I think the current behaviour makes sense. 

```
array:2 [
  "string_value" => "string"
  "nullable_value" => null
]
```

**Comment by derrabus** [comment]
Oh right. 🙈 

I agree with @Nyholm. If there is no way we can trigger a `null` inside `$_GET` via a HTTP request, it doesn't make much sense to allow to emulate it.

**Comment by michaljusiega** [comment]
Maybe you have a right, changes can be confusing so We should add `[BC break]` information to `UPGRADE-5.2.md` ?

**Comment by xabbuh** [comment]
refs #38591

**Comment by jperovic** [comment]
Sorry to jump in 3 years later

I am just upgrading Symfony 4.4 to use Flex and was hit by this. Wasn't there an option to skip sending the `null` request parameter (in both GET and POST) altogether?

This way, if I generate my test payload dynamically (say, from pre-populated DB), I have to take into account whether the attribute was `null` or not. But the failing test case would not care about that attribute in particular.

For me at least, `null` was always very much different from `''`

**Comment by jperovic** [comment]
Since, in my test, I use my own `Client` factory, I was able to preprocess the `$parameters` just before passing them to `request` method.

In case somebody else finds it useful: 

```
private function unsetNullsRecursively(array &$data, bool $removeEmptyArrays): void
{
    foreach ($data as $key => &$value) {
        if (is_array($value)) {
            $this->unsetNullsRecursively($value, $removeEmptyArrays);

            if (empty($value) && $removeEmptyArrays) {
                unset($data[$key]);
            }
        } else if (is_null($value)) {
            unset($data[$key]);
        }
    }
    unset($value);
}
```
