### ISSUE TITLE
Error "Notice: Undefined variable: values" while make:migration in Symfony 5: The Fast Track

### ISSUE THREAD

**Issue by SergioNodriza** [symfony/symfony#38656]
**Symfony version(s) affected:** 5.0.11

**Description**
The `$values` variable is not being loaded as an array thru the preg_match function when enclosed into `assert`, thus throwing an error of undefined in later uses, but splitting the code with assignation of the result of preg_match works. Suspected to be a PHP bug.

**How to reproduce**  
Following "Symfony 5: The Fast Track" when trying step 13.2, " $ symfony console make:migration", i got an error:

In PostgreSqlSchemaManager.php line 165:
"Notice: Undefined variable: values" 

Line 165 ->
```
assert(preg_match(
            '/FOREIGN KEY \((.+)\) REFERENCES (.+)\((.+)\)/',
            $tableForeignKey['condef'],
            $values
        ) !== 0);
```

**Possible Solution**  

```
$n= preg_match(
            '/FOREIGN KEY \((.+)\) REFERENCES (.+)\((.+)\)/',
            $tableForeignKey['condef'],
            $values
        );
        assert($n !== 0);
```

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/doctrine/dbal/pull/4364
