### ISSUE TITLE
Error when debugging twig with name argument

### ISSUE THREAD

**Issue by SylvanoTombo** [symfony/symfony#38676]
**Symfony version(s) affected**: 4.4.15

**Description**  
When i run bin/console debug:twig 'form_path', it's give an error like below:

 Argument "name" not supported, it requires the Twig loader "Twig\Loader\FilesystemLoader".

**Comment by Nyholm** [comment]
Do you have TwigBundle installed?

In there is a service defined like this: 

```
        <service id="twig.loader.native_filesystem" class="Twig\Loader\FilesystemLoader">
            <argument type="collection" /> <!-- paths -->
            <argument>%kernel.project_dir%</argument>
            <tag name="twig.loader"/>
        </service>
```

It defined the FilesystemLoader and tags it with `twig.loader`. The TwigBundle will make sure your TwigEnvironment gets that loader and you will not see the error message again.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
