### ISSUE TITLE
Twig random behaviour

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#38672]
**Symfony version(s) affected**: 4.4.15

**Description**  
Twig weird behaviour

I have this code into a base template
`<meta name="description" content="{% block meta_desc %}{{ meta_desc }}{% endblock %}">`

That gets rendered into this
`<meta name="description" content="<div id="sfwdt`

`{{ meta_desc }}` is a global variable with static content, like `meta_desc: 'best html5 page'`

php error log is empty .. i have no ideea what more details I could give
![out](https://user-images.githubusercontent.com/125879/96824841-b0f41b80-1427-11eb-9da3-f78aa91504bd.png)

LE:
It worked perfectly fine until I have installed Messenger component - default configuration
I removed it, however it still persists

**Comment by Nyholm** [comment]
I strongly think that you assigned some other value to `meta_desc`. Can you try the following things. Which ones will help?

1. Rename the block
```
<meta name="description" content="{% block meta_desc_block %}{{ meta_desc }}{% endblock %}">
```

2. Rename the variable
```
<meta name="description" content="{% block meta_desc %}{{ meta_desc_foobar }}{% endblock %}">
```
Also rename your global variable value in the config. `meta_desc_foobar: 'best html5 page'`

3. Search for `meta_desc` in your project. Do you find anything that assign a value to that variable?

**Comment by javiereguiluz** [comment]
By the way, the `<div id="sfwdt` fragment is the `<div>` used by the Web Debug Toolbar.

**Comment by Nyholm** [comment]
Interesting. Thank you.

**Comment by stof** [comment]
the toolbar is injected in the place of `</body>`. could it be that you have that in your `meta_desc` block for some reason ?

**Comment by cybernet** [comment]
> the toolbar is injected in the place of `</body>`. could it be that you have that in your `meta_desc` block for some reason ?

not a chance :)

here is a gist

https://gist.github.com/cybernet/a3a581954b5a6204b874bd1b7964396d

**Comment by Nyholm** [comment]
What was the result of my three suggestions?

**Comment by cybernet** [comment]
> What was the result of my three suggestions?

same result-ish - first it did a 502 gateway timeout, then it reverted to previous error - it's a new project, the only place the variable is used is in base.html.twig.
I have replaced the var with `meta_desc_tag` ( see gist )

also replaced in services.yaml & twig.yaml

i'm willing to provide access to the project if one would know what to look for ...

**Comment by Nyholm** [comment]
Sure. I'll have a look for you if you want.

**Comment by cybernet** [comment]
> Sure. I'll have a look for you if you want.

let's have a chat - t.me/<meta name="author">

**Comment by Nyholm** [comment]
Sure. Im available at the Symfony slack channel, ping me directly if you want. 

https://symfony.com/support

**Comment by Nyholm** [comment]
After some checks and discussions. We failed to reproduce this. 

@cybernet, feel free to correct me if Im wrong. But I think we can close this.

**Comment by cybernet** [comment]
After I disabled OPcache it stops. everything is working smoothly. how do we reproduce this ?

**Comment by derrabus** [comment]
> After I disabled OPcache it stops. everything is working smoothly. how do we reproduce this ?

Which exact php version are you using?
