### ISSUE TITLE
Performance comparison between 5.1 and 5.2 beta2

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#38683]
The Symfony Demo app is [running on Symfony 5.2 beta2](https://github.com/symfony/demo/pull/1163) so we can find deprecations or bugs. I decided to also check the performance differences between 5.1 (5.1.7) and 5.2 (beta2).

I took two non-trivial pages ("blog index" and "edit post form") and I took care to run `rm -fr var/cache/*` and `composer dump-autoload -o` before each run. These are the results (using PHP 7.4.11 and no preloading):

| Page                    | Env    | Result            | Details
| ----------------------- | ------ | ----------------- | -----------------------
| `/en/blog`              | `dev`  | 5.2 is 7% slower  | [Full Profile](https://blackfire.io/profiles/compare/d0822fd6-6d7c-464e-a18a-5332cd6381c6/graph)
| `/en/blog`              | `prod` | 5.2 is 4% faster  | [Full Profile](https://blackfire.io/profiles/compare/edf600e0-fa9b-4e91-b4d9-09c135ad5801/graph)
| `/en/admin/post/1/edit` | `dev`  | 5.2 is 10% slower | [Full Profile](https://blackfire.io/profiles/compare/fa29eeb3-e196-4a22-a46f-744adaf8d53e/graph)
| `/en/admin/post/1/edit` | `prod` | 5.2 is 3% slower  | [Full Profile](https://blackfire.io/profiles/compare/2ce7809a-47f4-485a-b406-17a1ff0184b5/graph)

I'd say results are OK ... except in some `dev` cases. If you check the [full Blackfire profile](https://blackfire.io/profiles/compare/fa29eeb3-e196-4a22-a46f-744adaf8d53e/graph) of the "edit post form" in "dev", you'll see thousands of new calls to `preg_match()` and `ReflectionReference::fromArrayElement()`. Maybe we should check. Thanks!

**Comment by wouterj** [comment]
If I use the GitHub search, the only usage of `ReflectionReference::fromArrayElement()` is here: https://github.com/symfony/symfony/blob/6844cb8685abb7ab2899d5bf368cc50e1e75ae22/src/Symfony/Component/VarDumper/Cloner/VarCloner.php#L69

**Comment by nicolas-grekas** [comment]
About the perf in "dev", the diff is only found in VarCloner: we might have more data to clone for the profiler in 5.2. About the diffs in "prod", I don't see anything special to explain it. This might just be noise...

**Comment by stof** [comment]
> About the diffs in "prod", I don't see anything special to explain it. This might just be noise...

or the usual small slow-down due to additional conditions to handle BC layers...

**Comment by Nyholm** [comment]
Thank you @javiereguiluz for testing and getting back with the results. 

I looked too. I didn't find anything particular.
