### ISSUE TITLE
ErrorHandler Component Missing ::setTemplate

### ISSUE THREAD

**Issue by stempora** [symfony/symfony#38697]
Last version of the component its missing 

// If you want a custom generic template when debug is not enabled
// HtmlErrorRenderer::setTemplate('/path/to/custom/error.html.php');

**Comment by yceruto** [comment]
Same as https://github.com/symfony/symfony/issues/38374 ?

**Comment by stempora** [comment]
Seems to be in the branch 5.x but it wasnt published yet for composer.

**Comment by yceruto** [comment]
Did you mean the new method `HtmlErrorRenderer::setTemplate()` that will be available in 5.2?

**Comment by stempora** [comment]
Yep, i installed the standalone component and didnt see its for 5.x.

**Comment by yceruto** [comment]
It's in beta version, 5.2 is not released yet.

**Comment by yceruto** [comment]
Check your composer constraint, you might be installing the stable version rather than the beta or dev version of the component.

**Comment by Nyholm** [comment]
Thank you for this issue. 

Try out with dev-master instead of beta and you will be fine.
