### ISSUE TITLE
Rename Twig "app" global variable

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#38692]
**Description**  
I cannot access the ["app" global variable](https://symfony.com/doc/current/templates.html#template-variables) because I'm already using that name in my templates for something else. I discovered this feature afterwards because Symfony lets me override this variable name without any warning or indication that data is being masked away. Obviously I could rename all my usages, however I'd rather keep my work as is and access framework features by a different name or mechanism.

Ideally the "app" global could be configured to be named something else. Alternatively, an `app()` function might be available as an alternative way to access the same.

**Example**  
```yaml
twig:
  # Rename the "app" global to something else
  app_global_var: symfony 
```

**Comment by jvasseur** [comment]
Making it configurable would means that any bundles that use this variable would break as soon as you change its name.

**Comment by Bilge** [comment]
@jvasseur Not if it merely made the same data available at an additional name. Considering there are no consequences for overriding the default name it seems fairly harmless to leave it as is, regardless of this configuration setting.

**Comment by javiereguiluz** [comment]
I think @jvasseur is right. In a third-party bundle called EasyAdmin for example we use things like this in some templates:

```twig
{% set sort_field_name = app.request.get('sort')|keys|first %}
{% if app.session is not null and app.session.started %}
```

So this would break if the application changes the name of the `app` global variable. I know that it's a bummer, but you should probably change the name of your own global variable instead.

**Comment by Bilge** [comment]
@javiereguiluz 
1. My variable is local from the controller, not global.
2. https://github.com/symfony/symfony/issues/38692#issuecomment-715371238

**Comment by Nyholm** [comment]
I agree with @jvasseur and @javiereguiluz 

If your variable is local form your controller, then I suggest you change that variable name in your controller. The effects of changing the Symfony variable name is greater. 

To make things work properly for your app, make sure you add the service called `twig.app_variable` to your Twig environment as a global variable.

**Comment by Bilge** [comment]
@Nyholm Why does everyone keep assuming the only solution is to ***change*** the Symfony variable name. As I [already described](https://github.com/symfony/symfony/issues/38692#issuecomment-715371238), there are *at least* two other alternatives, including *copying* the variable to an *additional name* and exposing other mechanisms to access the same information, such as an accessor function.

Of course it's easy for you to dismiss the situation out of hand demanding I change the name of my variable, even though the name of my variable is actually correct. Consider an App store selling apps; clearly when I display the apps in my template they should be referred to as *app*. Of course, *app* is a loaded term with many different meanings, but for Symfony to just assume it can use this name for its own purposes, providing no other alternative is plainly obnoxious and a poor implementation choice. Something should be done about it.

I implore you to reconsider alternative solutions and reopen this issue until other options have been fully explored.

**Comment by yceruto** [comment]
@Bilge you already can "change" the `app` name globally for your application:
```yaml
twig:
    globals:
        symfony_app: '@twig.app_variable'
```
https://symfony.com/doc/current/templating/global_variables.html#referencing-services

edit: and `app` will keep working too.

**Comment by Bilge** [comment]
@yceruto Good post, thank you. 👍

**Comment by Nyholm** [comment]
Thank you Yonel for giving an example of what I explained.
