### ISSUE TITLE
GHA failures

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#38705]
In https://github.com/symfony/symfony/runs/1302020775
there are two failures to investigate:

> ✗ flex Could not setup flex

and 

> Your Composer dependencies require the following PHP extensions to be installed: xsl

Help wanted /cc @derrabus maybe :)

**Comment by derrabus** [comment]
Is the flex problem related to the Composer 2 release? Maybe we can force Composer 1 temporarily until we know why the setup-php action is failing suddenly.

**Comment by derrabus** [comment]
Forcing Composer 1 doesn't really help: https://github.com/derrabus/symfony/runs/1302071945

I can't look into the issue any further right now. Maybe I'll find some time tomorrow.

**Comment by nicolas-grekas** [comment]
Fixed in #38707
