### ISSUE TITLE
Access flashbag form AbstractFormLoginAuthenticator

### ISSUE THREAD

**Issue by Saryon61** [symfony/symfony#38700]
Symfony version: 5.1.7

When using a form authenticator (AbstractFormLoginAuthenticator), the method "onAuthenticationSuccess" output a redirection. 
After this redirection, I would like to display a message of success for the user who successfully logged in. 

The use of the flashbag from the authenticator would have been nice for this use case, and that's what I have implemented through injecting "Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface" to make use of the service "session.flash_bag". 
Combined with: $this->flashbag->set('login_successfull', 'message_login_form_valid');
It works.

But after upgrading to Symfony 5.1, I discovered this deprecation:
_User Deprecated: Since symfony/framework-bundle 5.1: The "session.flash_bag" service is deprecated, use "$session->getFlashBag()" instead._

I am trying to solve this deprecation by using "$flashbag = $request->getSession()->getBag('flash')", but I can't make it work as there are no methods on $flashbag to set a message (only "getName", "getStorageKey", "clear" or "initialize").

I have also tryed to inject the autowired "session" service available. But, it comes form SessionInterface that doesn't let you retrieve and set the flashbag, in the same way I mentioned above.

Maybe I don't see things correctly, do you have any advise to solve this use case? 
I have though of dropping the idea of using the flashbag for this, but I can't see a nice way to pass information after a redirection?

Finally: if this is not the good way to ask for support, please tell me how I should do it because I am new to Github.

Thanks in advance

**Comment by subcores** [comment]
Its not a bug. Just use this in the onAuthenticationSuccess method:
`$request->getSession()->getFlashBag()->add('login_successfull', 'message_login_form_valid');`

**Comment by xabbuh** [comment]
For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by ahundiak** [comment]
Just wanted to point out that SessionInterface has no getFlashBag() method defined.  So when dealing with things like $request->getSession() which returns a SessionInterface or even when injecting the SessionInterface service directly, IDEs will not show the method nor will they list the FlashBagInterface specific methods.

I kinda think that getFlashBag needs to be added to the SessionInterface though I suspect that will break any non-Symfony session implementations.  Bit of a quandary really.  

This works in PHPStorm though to be honest I am not sure why PHPStorm does not flag the undefined SessionInterface::getFlashBag method.
```
class SomeService
{
    private SessionInterface $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }
    public function doSomething()
    {
        /** @var FlashBagInterface $flashBag */
        $flashBag = $this->session->getFlashBag();
        $flashBag->add('msg','me');
    }
}
```

**Comment by jderusse** [comment]
This has already been reported several times:

https://github.com/symfony/symfony/pull/22395
https://github.com/symfony/symfony/issues/20258
https://github.com/symfony/symfony/pull/37106
