### ISSUE TITLE
Help adding translations

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38710]
Hey!

My very first contribution to Symfony was [adding some Swedish translations](https://github.com/symfony/symfony/pull/11561). These translations are helpful for everyone that runs a Swedish Symfony website.

Symfony core uses translations mostly for error messages. When new error messages are added, so is English translations. But there is also a continuous effort to translate these new strings into Spanish, Arabic, Serbian, Japanese, German etc. 

I created a status page that will show what language that is currently missing translations for each component and branch. If you speak a language that has missing translations, I would really appreciate if you took the time to submit a PR. 

See current translation status at: https://symfony-translations.nyholm.tech

If this is the first time you make a PR to Symfony, or maybe it is your first time making a PR at all? No worries. The Symfony community is always happy to help. Do your best effort and we will make sure it gets merged together. There is also some really great people in the #support channel on [Slack](https://symfony.com/slack).

**Comment by derrabus** [comment]
I'll look into the German translations.

**Comment by derrabus** [comment]
I think, your documentation on how to update translations would be a helpful addition to the official docs: symfony/symfony-docs#14481

**Comment by TavoNiievez** [comment]
I'll look into the Spanish translations.

**Comment by andrewmy** [comment]
Will look into Latvian

**Comment by ben29** [comment]
I will do Hebrew translation if still needed ...

**Comment by Nyholm** [comment]
Wohoo. We have made some great progress here. Just a few languages left to translate.

**Comment by rezendus** [comment]
I'll look into the Portuguese translations.

**Comment by slash686** [comment]
I'll look into the Russian translations.

**Comment by I-Valchev** [comment]
I'll work on the Bulgarian translations.

**Comment by VincentLanglet** [comment]
Hi @Nyholm, is the code of this website available on Github ?

**Comment by Nyholm** [comment]
Yes it is. See https://github.com/symfony-tools/symfony-translation-checker

**Comment by andreacivita** [comment]
I would like to collaborate to italian translation. I commented #43445 issue and i'm waiting to receive assign. :)

**Comment by qzylalala** [comment]
I'd like to collaborate to Chinese(zh_CN) translation.
