### ISSUE TITLE
Missing translations for Albanian (sq)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38722]
Hello,

There are some missing translation for Albanian (sq). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sq.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.sq.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by abame** [comment]
I'd like to take over this issue :smiley:

**Comment by Nyholm** [comment]
Please do. 
Thank you
