### ISSUE TITLE
Missing translations for Azerbaijani (az)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38725]
Hello,

There are some missing translation for Azerbaijani (az). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.az.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.az.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.az.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.az.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.az.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.az.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Wow, @seferov, you did your first contribution back in 2013. =)

Could I ask you to help out with some more translations?

**Comment by seferov** [comment]
@Nyholm :) sure, you can assign this to me.

**Comment by Nyholm** [comment]
Awesome. Thank you
