### ISSUE TITLE
Missing translations for Belarusian (be)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38727]
Hello,

There are some missing translation for Belarusian (be). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.be.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.be.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.be.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Hey @vtsykun, you did quite some work on these last year, could I ask you to add a few more missing translations?

**Comment by belangela** [comment]
Hi! I'm that girl from Twitter who offered to help just now. I have no coding experience (I have a PhD in the humanities, this is how far removed I am from programming), so I'm not really sure on what I should translate and how to begin. I do speak Belarusian and English and am reasonably familiar with the terminology (and will use @vtsykun 's translated bits as a model). Give me a hand, maybe? :)

**Comment by Nyholm** [comment]
Thank you. 

I suggest you use Githubs "Edit file" feature. Open these files/links: 

- https://github.com/Nyholm/symfony/blob/translation-be/src/Symfony/Component/Form/Resources/translations/validators.be.xlf
- https://github.com/Nyholm/symfony/blob/translation-be/src/Symfony/Component/Security/Core/Resources/translations/security.be.xlf
- https://github.com/Nyholm/symfony/blob/translation-be/src/Symfony/Component/Validator/Resources/translations/validators.be.xlf

Click on the pen icon. Now you can modify the code. Just change the English text between `<target>` and `</target>` (note that some texts are already translated). As you notice, most of these texts are warnings or form errors. 

When you are done with one file, click on "Propose changes". Under the hood, Gitlab will fork the repo, create a new branch and commit the changes to the branch. 

Once the changes are made on your fork, I'll help you create a pull request to symfony/symfony. After the pull request is merged, all symfony websites in Belarusian will benefit from this.

**Comment by andrewshadura** [comment]
@Nyholm, FWIW it’d probably be useful to set up a project at [Weblate](https://hosted.weblate.org) to enable contributions from more users.

**Comment by OxanaKozlova** [comment]
Hi) I'm Symfony developer from Belarus. I would like to help with translations!
