### ISSUE TITLE
Missing translations for Basque (eu)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38726]
Hello,

There are some missing translation for Basque (eu). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.eu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.eu.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.eu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.eu.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.eu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.eu.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Hey @cluster28, could I ask you to look at this ticket please?

**Comment by cluster28** [comment]
@Nyholm I will check it ASAP

**Comment by Nyholm** [comment]
Nice. Thank you

**Comment by cluster28** [comment]
@Nyholm, @olatzromeo will review those missing translations for us

**Comment by Nyholm** [comment]
Maybe @ikerib can start and @cluster28 will help out with the review (if you can)?

**Comment by ikerib** [comment]
sure!
