### ISSUE TITLE
Missing translations for Estonian (et)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38738]
Hello,

There are some missing translation for Estonian (et). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.et.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.et.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.et.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Hey @Sheitak, could you help out with these too?

**Comment by Sheitak** [comment]
Hello @Nyholm , I am currently busy with other issues, but if I have a moment I will get back to you thanks

**Comment by Nyholm** [comment]
Maybe @glodzienski could start and @Sheitak could review the PR later (if you can)?

**Comment by crysglodzienski** [comment]
@Nyholm yes, for sure.

**Comment by glodzienski** [comment]
Yes, for sure @Nyholm

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
@glodzienski did you have time to look at this?

**Comment by Nyholm** [comment]
There are about 50 strings that should be translated. Most of them are form validation errors. "Please add a valid integer" etc

**Comment by hluup** [comment]
I could look into this. I'm no translator though.
WIP https://github.com/symfony/symfony/pull/42485
