### ISSUE TITLE
Missing translations for Danish (da)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38736]
Hello,

There are some missing translation for Danish (da). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.da.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.da.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.da.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.da.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.da.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.da.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Hey, @henrikbjorn can you help me ping somebody who could help with this?

**Comment by AnneKir** [comment]
Hey, I can do this

**Comment by Nyholm** [comment]
Nice!
