### ISSUE TITLE
Missing translations for European Portuguese (pt_PT)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38739]
Hello,

There are some missing translation for European Portuguese (pt_PT). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.pt_PT.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.pt_PT.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.pt_PT.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.pt_PT.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.pt_PT.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.pt_PT.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by brunosinister** [comment]
@Nyholm this issue is the same #38774 .

**Comment by brunosinister** [comment]
@Nyholm I can work in that, but what the difference for #38774 ?

**Comment by Nyholm** [comment]
Nice

**Comment by Nyholm** [comment]
It is a different dialect I guess. 

We might not need to translate all keys. Only those that are different from pt

**Comment by brunosinister** [comment]
There are 2 dialects for Portuguese:  Brazilian Portuguese and European Portuguese. So I believe that this one is unnecessary

**Comment by Nyholm** [comment]
Thank you for clarifying. 

Symfony translation works like this: 

If the locale is `pt_PT`, Symfony will look for a file named `validators.pt_PT.xlf` and then `validators.pt.xlf`. 
If the locale is `pt`, Symfony will just look for a file named `validators.pt.xlf`. 

So what is the "main" dialect? Those translations should be added to `validators.pt.xlf`. If there is any "typical" Brazilian translations, they should be added in `validators.pt_BR.xlf`. Same for "typical" European translations to be added in `validators.pt_PT.xlf`.

Note that `validators.pt_PT.xlf` and `validators.pt_BR.xlf` does not need to be complete as the translation component will fallback to `validators.pt.xlf`. 

------

Given the information above, could you and @pedroresende (and maybe @antonioribeiro) sync up these 3 translation locales?

**Comment by brunosinister** [comment]
Thank you for clarifying. 

Now I understood :D . I will work in it.

**Comment by Nyholm** [comment]
Note that we should target branch 4.4 now

**Comment by raziel057** [comment]
@Nyholm Currently there is no [src/Symfony/Component/Security/Core/Resources/translations/security.pt.xlf](src/Symfony/Component/Security/Core/Resources/translations/security.pt.xlf) file. 

I think we should rename the security.pt_PT.xlf to security.pt.xlf as it's on Validator component.

Validator translations:
https://github.com/symfony/symfony/tree/4.4/src/Symfony/Component/Validator/Resources/translations

Security translations:
https://github.com/symfony/symfony/tree/4.4/src/Symfony/Component/Security/Core/Resources/translations

**Comment by Nyholm** [comment]
I agree with that. Thank you.

**Comment by Nyholm** [comment]
Can you make that PR?

After that there is only a few translations missing on Portuguese (pt)
