### ISSUE TITLE
Missing translations for Catalan (ca)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38731]
Hello,

There are some missing translation for Catalan (ca). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.ca.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.ca.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.ca.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.ca.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.ca.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.ca.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Hey @rogerguasch, could you help out with this?

**Comment by rogerguasch** [comment]
Hi,
this three files are already translated, isn't it?

**Comment by Nyholm** [comment]
Yes, but if you look at the English versions of those 3 files, you will see that some translations are missing.

**Comment by rogerguasch** [comment]
Ok, working on!

**Comment by rogerguasch** [comment]
@Nyholm PR open ;)

**Comment by Nyholm** [comment]
WohoO!
