### ISSUE TITLE
Missing translations for Greek (el)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38743]
Hello,

There are some missing translation for Greek (el). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.el.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.el.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.el.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.el.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.el.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.el.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by pavlakis** [comment]
I will take a look at the Greek translations :)

**Comment by Nyholm** [comment]
Cool. Thanks

**Comment by Nyholm** [comment]
Fixed in https://github.com/symfony/symfony/pull/38829
