### ISSUE TITLE
Missing translations for Hungarian (hu)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38745]
Hello,

There are some missing translation for Hungarian (hu). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.hu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.hu.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.hu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.hu.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.hu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.hu.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by masitings** [comment]
i got this too... same to 4.4 branch right ?

**Comment by Nyholm** [comment]
Yes sir.
