### ISSUE TITLE
Missing translations for French (fr)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38741]
Hello,

There are some missing translation for French (fr). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.fr.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.fr.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by TheGarious** [comment]
Hello @Nyholm, 

I can work for translation for French. 

Nice initiative 👍🏻 

Thanks for this issue :D

**Comment by Nyholm** [comment]
I think @zairigimad just made some in this PR: https://github.com/symfony/symfony/pull/38719

Could you review that and make sure it is correct?

**Comment by TheGarious** [comment]
Yes @Nyholm,

I look him PR.
