### ISSUE TITLE
Missing translations for Japanese (ja)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38748]
Hello,

There are some missing translation for Japanese (ja). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.ja.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.ja.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.ja.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.ja.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.ja.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.ja.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Ippey** [comment]
Hi,
I'm trying to translate for Japanese.
Then I found that "src/Symfony/Component/Validator/Resources/translations/validators.ja.xlf" is lack for translation.

validators.en.xlf has `<trans-unit id="97">` and `<trans-unit id="98">` , but validators.ja.xlf doesn't have them.

I can also translate 97, 98.
Should I translate them in same branch? Or create another issue and PR?

Thank you.

**Comment by Nyholm** [comment]
Hey. 

That would be great. Thank you

You can create just one PR. Do it for branch 3.4.

**Comment by Ippey** [comment]
@Nyholm Thank you.
Then I'll start to translate.
