### ISSUE TITLE
Missing translations for Hebrew (he)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38744]
Hello,

There are some missing translation for Hebrew (he). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.he.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.he.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.he.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
@ben29 will work on this

**Comment by ben29** [comment]
The last commit it’s from me
So few things left to do
Will do it soon as possible 

Thanks

**Comment by Nyholm** [comment]
Awesome. Let me know if I can help you in any way.

**Comment by ben29** [comment]
@Nyholm 
validators.he.xlf - looks good and ready.
security.he.xlf - I finish it , waiting for pull request approval.
validators.he.xlf -  I don't see something wrong. and it's completed.

**Comment by Nyholm** [comment]
Awesome. Thank you. 

Have a look at this page: https://symfony-translations.nyholm.tech/#pr

You need to copy the translation keys from the English file.

**Comment by ben29** [comment]
It’s the same keys from en file
What i miss?

**Comment by Nyholm** [comment]
The English files contains many more keys, right?

Lets copy all missing keys from [src/Symfony/Component/Form/Resources/translations/validators.en.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.en.xlf) to [src/Symfony/Component/Form/Resources/translations/validators.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.he.xlf). Ie, keys with id 99 to id 128. 

Same with the other files. (But they only have a few translation keys missing)

**Comment by ben29** [comment]
Ohhh you meaning to another file
Ok
Will do

**Comment by ben29** [comment]
@Nyholm done.

**Comment by ben29** [comment]
@Nyholm everything is done. with new changes...
please confirm now everything is ok.

**Comment by Nyholm** [comment]
Excellent. These looks okey. 

Now there is only 5 strings missing form [the validator component](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.he.xlf)

```
 <trans-unit id="95">
                <source>This value is not a valid hostname.</source>
                <target>This value is not a valid hostname.</target>
            </trans-unit>
            <trans-unit id="96">
                <source>The number of elements in this collection should be a multiple of {{ compared_value }}.</source>
                <target>The number of elements in this collection should be a multiple of {{ compared_value }}.</target>
            </trans-unit>
            <trans-unit id="97">
                <source>This value should satisfy at least one of the following constraints:</source>
                <target>This value should satisfy at least one of the following constraints:</target>
            </trans-unit>
            <trans-unit id="98">
                <source>Each element of this collection should satisfy its own set of constraints.</source>
                <target>Each element of this collection should satisfy its own set of constraints.</target>
            </trans-unit>
            <trans-unit id="99">
                <source>This value is not a valid International Securities Identification Number (ISIN).</source>
                <target>This value is not a valid International Securities Identification Number (ISIN).</target>
            </trans-unit>
```

**Comment by ben29** [comment]
@Nyholm 
```
            <trans-unit id="95">
                <source>This value is not a valid hostname.</source>
                <target>ערך זה אינו שם מארח חוקי.</target>
            </trans-unit>
            <trans-unit id="96">
                <source>The number of elements in this collection should be a multiple of {{ compared_value }}.</source>
                <target>מספר האלמנטים באוסף זה צריך להיות מכפיל של {{ compared_value }}.</target>
            </trans-unit>
            <trans-unit id="97">
                <source>This value should satisfy at least one of the following constraints:</source>
                <target>ערך זה אמור לעמוד לפחות באחד התנאים הבאים:</target>
            </trans-unit>
            <trans-unit id="98">
                <source>Each element of this collection should satisfy its own set of constraints.</source>
                <target>כל אלמנט באוסף זה אמור לעמוד בקבוצת התנאים שלו.</target>
            </trans-unit>
            <trans-unit id="99">
                <source>This value is not a valid International Securities Identification Number (ISIN).</source>
                <target>ערך זה אינו מספר זיהוי ניירות ערך בינלאומי תקף (ISIN).</target>
            </trans-unit>
```

**Comment by Nyholm** [comment]
Cool. 👍 

Add those in a new PR and you can get another PR merged today =)

**Comment by ben29** [comment]
@Nyholm 
check if need more translate.

**Comment by Nyholm** [comment]
Excellent. 

Great work. 
I think this is enough. I'll double check next time the [dashboard](https://symfony-translations.nyholm.tech/) updates.
