### ISSUE TITLE
Missing translations for Lithuanian (lt)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38750]
Hello,

There are some missing translation for Lithuanian (lt). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.lt.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.lt.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.lt.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.lt.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Could I ask @rmikalkenas or @gautierderuette to have a look at this?

**Comment by rmikalkenas** [comment]
@Nyholm done!
