### ISSUE TITLE
Missing translations for Persian (fa)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38757]
Hello,

There are some missing translation for Persian (fa). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.fa.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.fa.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.fa.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.fa.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by a-shafaat** [comment]
Hi, 

I want to help solving this issue.

**Comment by Nyholm** [comment]
Awesome. 

Thank you
