### ISSUE TITLE
Missing translations for Luxembourgish (lb)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38752]
Hello,

There are some missing translation for Luxembourgish (lb). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.lb.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.lb.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.lb.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.lb.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.lb.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.lb.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Maybe @evxzibit could help out?

**Comment by Nyholm** [comment]
Hey @mweimerskirch, could you have a look at this?

**Comment by mweimerskirch** [comment]
I'll do that, but probably not today.

**Comment by Nyholm** [comment]
Awesome. Thank you
