### ISSUE TITLE
Missing translations for Norwegian Nynorsk (nn)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38756]
Hello,

There are some missing translation for Norwegian Nynorsk (nn). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.nn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.nn.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.nn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.nn.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.nn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.nn.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
Ping @themilanfan, There is already Bokmål added, could you have a look at the Nynorsk?

**Comment by Nyholm** [comment]
Or maybe @glye is around to help out again?

**Comment by glye** [comment]
@Nyholm I've done this before? Hm, git confirms. Okay :) How urgent is it?
NB: I'm a native Norwegian speaker, but not a native Nynorsk writer. I can do a semi-decent job, but if there's a native writer here, it would be good of you to step in.

**Comment by Nyholm** [comment]
=)

If you do a first attempt that would be great. I'll see if I can find some other native to confirm the work. 

It is not urgent, it is open source =). Sooner the better of course, but life always comes first.

**Comment by Nyholm** [comment]
@glye did you have time to have a look at this?

**Comment by glye** [comment]
Sorry, not yet, and sorry about the late reply. Do you have an idea about how many strings are missing? Is the procedure still to check out the English file and manually copy over missing parts, then translate?

**Comment by Nyholm** [comment]
> Do you have an idea about how many strings are missing?

It is about 30-40 strings. Most of them are similar to "Please enter a valid week". 

> Is the procedure still to check out the English file and manually copy over missing parts, then translate?

Yes, pretty much. 
I have a small example of the procedure you described at https://symfony-translations.nyholm.tech/#pr

**Comment by glye** [comment]
Thanks, that's not much. I'll get it done.

**Comment by glye** [comment]
PR: https://github.com/symfony/symfony/pull/40435
One failing test so far, which is nothing to do with this.
