### ISSUE TITLE
Missing translations for Thai (th)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38767]
Hello,

There are some missing translation for Thai (th). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.th.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.th.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.th.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.th.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.th.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.th.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by ibotdotout** [comment]
Hi, I will work on this.

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
Note that we should target branch 4.4 now
