### ISSUE TITLE
Missing translations for Ukrainian (uk)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38769]
Hello,

There are some missing translation for Ukrainian (uk). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.uk.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.uk.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Comrade42** [comment]
Hi, I'll take this.

**Comment by Nyholm** [comment]
Cool cool cool. 

Thank you

**Comment by kefzce** [comment]
> Hi, I'll take this.

@Comrade42 could you also please fix this 
https://github.com/symfony/symfony/blob/56316c43862ff6833bfff588fcbe15f5c50669d7/src/Symfony/Component/Validator/Resources/translations/validators.uk.xlf#L115

```suggestion
однаковими
```
as far as I see there are many inconsistencies between the original phrase and Ukrainian translate above and below 😞

**Comment by Comrade42** [comment]
@kefzce okay, I'll check the rest of translations as well.
