### ISSUE TITLE
Missing translations for Serbian (sr_Latn)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38761]
Hello,

There are some missing translation for Serbian (sr_Latn). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sr_Latn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.sr_Latn.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sr_Latn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.sr_Latn.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
@tambait could you help out again please?

**Comment by tambait** [comment]
@Nyholm Good timing, I was about to push missing translations for SR (Latn & Cyrl) as well as BS :)

**Comment by Nyholm** [comment]
Hehe, nice!

I will be happy to review that =)
