### ISSUE TITLE
Missing translations for Slovak (sk)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38762]
Hello,

There are some missing translation for Slovak (sk). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sk.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.sk.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sk.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.sk.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.sk.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.sk.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by miromichalicka** [comment]
Working on this now.
