### ISSUE TITLE
Missing translations for Spanish (es)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38764]
Hello,

There are some missing translation for Spanish (es). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.es.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.es.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.es.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.es.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.es.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.es.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by Nyholm** [comment]
@TavoNiievez just started to work on this

**Comment by TavoNiievez** [comment]
@Nyholm happy to help 😄
maybe this can be closed now.

**Comment by Nyholm** [comment]
Yes sir!

Thank you
