### ISSUE TITLE
Missing translations for Slovenian (sl)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38763]
Hello,

There are some missing translation for Slovenian (sl). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.sl.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.sl.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.sl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.sl.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by masitings** [comment]
Can i take this aswell ?

**Comment by Nyholm** [comment]
@masitings Do you speak Norwegian, Hungarian and Slovenian?

If so, that is impressive =)

**Comment by masitings** [comment]
I'll try my best to do that.. i know a bit but hopefully that would be help.

**Comment by Nyholm** [comment]
Okey. 

It is important that we get human translations. Machine translations are not preferred. 

If you do your best try for Slovenian then we can ask somebody else than me proof read it. 

Thank you

**Comment by Nyholm** [comment]
Ping @petk, maybe you could help out?
