### ISSUE TITLE
Missing translations for Portuguese (pt)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#38774]
Hello,

There are some missing translation for Portuguese (pt). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.pt.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.pt.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.pt.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.pt.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by BrunoAlou** [comment]
Hello Tobias,

I'd like to work on this issue.

**Comment by Nyholm** [comment]
Great. Thanks

**Comment by brunosinister** [comment]
> Hello Tobias,
> 
> I'd like to work on this issue.

Hello Bruno, I can help you, I have the form validators already translated.

**Comment by Nyholm** [comment]
Note that we should target branch 4.4 now

**Comment by Nyholm** [comment]
Cool. So the translations are almost done. There is just a handful left. Who is working on this at the moment?

**Comment by NicolasJourdan** [comment]
Hello Tobias,

I worked on it :).

**Comment by Nyholm** [comment]
Closed by #39345
