### ISSUE TITLE
doctrine:migration:create not create a database with a specific charset

### ISSUE THREAD

**Issue by wcervini** [symfony/symfony#38772]
**Symfony version(s) affected**: 4.4.15

**Description**  
when try to create a database  on console, take the default charset default on MySQL Database.

**How to reproduce**  
Udpate the doctrine.yaml file (See screenshot1):

**Possible Solution**  
- run on console octrine:migrations:generate
- add in the public function up on the created migration file (See Screenshot2):

**Additional context**  

![Screenshot1](https://user-images.githubusercontent.com/51060/97111289-f0479400-16d5-11eb-8c4a-9842a95c6c77.jpg)
![Screenshot2](https://user-images.githubusercontent.com/51060/97111290-f178c100-16d5-11eb-9e77-109efdca36fe.jpg)

**Comment by derrabus** [comment]
The Doctrine integration is not maintained in this repository. Please open your issue here: https://github.com/doctrine/DoctrineBundle/
