### ISSUE TITLE
AppVeyor build broken on 4.4

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#38803]
**Symfony version(s) affected**: 4.4-dev

**Description**  
Our AppVeyor build is currently broken. Each test suite fails with the following error:

```
Composer detected issues in your platform:
Your Composer dependencies require the following PHP extensions to be installed: mbstring
```

The reason for that is a failed platform check enforced by Composer 2. That check for `ext-mbstring` is installed because PHPUnit explicitly asks for the extension:

https://github.com/sebastianbergmann/phpunit/blob/e936ac1a54a49d1636f05e6c8871f73a79b877f6/composer.json#L28

Of course, we could just enable the extension. But I believe, `ext-mbstring` among other extensions is missing here on purpose because we want to test Symfony with minimal extensions enabled.

**How to reproduce**  
https://ci.appveyor.com/project/fabpot/symfony/builds/35947101

**Possible Solution**  
* Enable `ext-mbstring` anyway.
* Find a way to get around the platform check (e.g. same hack as #38707).

**Comment by stof** [comment]
No need for a hack. Composer has a built-in way to disable platform checks through the config: https://getcomposer.org/doc/06-config.md#platform-check

**Comment by derrabus** [comment]
Oh, good to know. PhpUnitBridge could apply that setting while installing PHPUnit.
