### ISSUE TITLE
[Console] Signal does not work with Question

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#38820]
**Symfony version(s) affected**: 5.2.x

I broke symfony, sorry !

**Description**  

Signal handling does not work well with question! 

**How to reproduce**  

Use `bin/console make:controller` and then press <kbd>CTRL+C</kbd>
=> it does not work anymore until you press <kbd>enter</kbd>

**Possible Solution**  

Empty this list https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Application.php#L94
Most of the time, we don't care about signal. It's only useful for long running process. But since we use this list **before** running the command, the "Signal To Symfony Event" feature will become hard to implement. We may register signal listener if the command implement a certain insterface.

The other solution would be to not use [`fgets`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Helper/QuestionHelper.php#L517) but `stream_select()`

**Additional context**  

I created a simple reproducer:
```
<?php

pcntl_signal(SIGINT, function () {
    dump('CAUGHT');
});
pcntl_async_signals(true);


$stream = \STDIN;
$what = fgets($stream, 4096);

dump('AFTER');
```

=>

```
php test.php 
^C^C^C^C
^ "CAUGHT"
^ "CAUGHT"
^ "CAUGHT"
^ "CAUGHT"
^ "AFTER"
```

As you can see, I pressed 4 times <kbd>CTRL+C</kbd> and it did not worked until I pressed <kbd>enter</kbd>

**Comment by chalasr** [comment]
Good catch. Not subscribing to any signal by default makes sense to me 👍

**Comment by lyrixx** [comment]
@chalasr, but if we do that, the whole system with Symfony Event could not work anymore. What about my proposal ?

**Comment by chalasr** [comment]
@lyrixx Sorry, I missed that part. I see now, enabling the feature from the command (typically worker) sounds good.

Could we rely on `SignalableCommandInterface` to automatically subscribe to default signals? Or do we need another one?

**Comment by lyrixx** [comment]
IMHO, we need another one, because one may want to use only event, without bothering with handling manually the signal.

I'll propose a PR soon
