### ISSUE TITLE
[Messenger][SQS] Prevent calling getQueueUrl() when DSN is a SQS queue URL

### ISSUE THREAD

**Issue by natepage** [symfony/symfony#38849]
**Description**  
In #37306 we added the support for SQS queue URL as DSN, however we're still calling getQueueUrl() internally, we could prevent that request as we already know the queue URL in that case.

I'm happy to work on a PR for this, but I would like to have some feedback about how we would like this to be implemented 😄 

**Idea**
In `Connection`, to allow this to work with both `fromDsn()` and the constructor, I was thinking about adding an option `queue_url` which defaults to `null`.

This way someone instantiating the connection directly has the ability to pass that option, and in `fromDsn()` we can set this option based on `$dsn`.

Then we just need to update the `getQueueUrl()` method to use the option if set.

**Comment by jderusse** [comment]
Hey @natepage thank you for the issue, it was on my TODO list. No need to add a new property. We already have one, we just need to allow user injecting a value in `__constructor`. 

I opened #38850 would you mind to have a look ?

note: Instead of adding a new parameter, I prefer using the DSN when it looks like a queueUrl which is already supported by the component.

**Comment by natepage** [comment]
> Should we also update the `setup()` method? 
> 
> Because even if we set `$queueUrl` on the connection, if we don't explicitly set `auto_setup: false` it will check if the queue exists which triggers an unnecessary request to SQS still.  

The `setup` method calls `SqsClient::queueExists()` which call the `GetQueueUrl` API operation. This can not be removed, because it's the purpose of the method: We have to check if the queue exists (even if the DSN is a queueUrl) to decide if a queue need to be created. 

User can (should) disable it with `auto_setup=false` to prevent this.
