### ISSUE TITLE
symfony/doctrine-bridge 4.4.16 breaks indexBy funtionality

### ISSUE THREAD

**Issue by tannyl** [symfony/symfony#38861]
**symfony/doctrine-bridge version(s) affected**: 4.4.16

**Description**  
After updating from version 4.4.15 to 4.4.16 the Symfony app Sylius breaks with the following error:
```
In MappingException.php line 621:
  Cannot find a field on 'Sylius\Component\Core\Model\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exi  
  st or an association exists but it has multiple join columns.
```

This is due to the use of `indexBy` here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml#L40

After the changes here https://github.com/symfony/doctrine-bridge/compare/v4.4.15...v4.4.16 the `indexBy` needs to be the column name and not the field name as it used to.

The fix for this should be easy. Change "**channelCode**" to "**channel_code**". This does in fact fix the above error. But Sylius still breaks due to a new problem.

Now in 4.4.16 it ignores the `indexBy` and uses numbers as keys instead of what is defined in `indexBy`. Which in turn breaks Sylius again, as it expects the returned `collection` to have "**channelCodes**" as the keys.
Interesting enough, is that if I use the "id" in `indexBy` it correctly uses the ids as the keys in the `collection`

Please see the issue here as well: https://github.com/Sylius/Sylius/issues/11970

**How to reproduce**  
Install Sylius as decribed here https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html
Remember to only use doctrine-bridge version 4.4.15.
Verify it works.
Update to doctrine-bridge version 4.4.16
Run console/bin cache:clear

**Comment by nicolas-grekas** [comment]
Can you check if #38628 fixes the issue?

**Comment by tannyl** [comment]
@nicolas-grekas It does not seem to change anything at all. It still works as described above, and changing back to "channelCode" just results in the same error again. (`Cannot find a field....`)

**Comment by ro0NL** [comment]
Same, it's a BC break not a bug.

Given `<one-to-many field="items" target-entity="App\Entity\Some" mapped-by="mapped" index-by="some"/>` and `<field name="some"/>`

i get the breakage. The patch in #38628 doesnt work neither.


```
$ composer update symfony/doctrine-bridge
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 0 installs, 1 update, 0 removals
  - Updating symfony/doctrine-bridge (v5.1.7 => v5.1.8): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
102 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In FileLoader.php line 173:
!!                                                                                 
!!    Cannot find a field on 'App\Entity\Some' that is mapped to colum  
!!    n 'some'. Either the field does not exist or an association exists b  
!!    ut it has multiple join columns in . (which is being imported from "
!!    /app/config/routes/api_platform.yaml"). Make sure there i  
!!    s a loader supporting the "api_platform" type.                               
!!                                                                                 
!!  
!!  In MappingException.php line 621:
!!                                                                                 
!!    Cannot find a field on 'App\Entity\Some' that is mapped to colum  
!!    n 'some'. Either the field does not exist or an association exists b  
!!    ut it has multiple join columns.                                             
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by bwach** [comment]
This can occur when we treat "indexBy" as column name rather than field name, so when we have a indexBy=foo but the column name is bar_bar, it will fail too.

@tannyl your problem seems to be that if you set indexBy to "channel_code" (the column name), the indexing doesn't work as it expects indexBy to be a field name

**Comment by tannyl** [comment]
> @tannyl your problem seems to be that if you set indexBy to "channel_code" (the column name), the indexing doesn't work as it expects indexBy to be a field name

@bwach the changes in 4.4.16 made it so you have to use the column name instead of field name otherwise it won't work. But it seems somewhere else in the doctrine_bridge code it still expects a fieldname when trying to assign keys to the final collection you get back from doctrine. And since you can't use a fieldname anymore, they keys don't get assigned with the expected values.

**Comment by bwach** [comment]
> > @tannyl your problem seems to be that if you set indexBy to "channel_code" (the column name), the indexing doesn't work as it expects indexBy to be a field name
> 
> @bwach the changes in 4.4.16 made it so you have to use the column name instead of field name otherwise it won't work. But it seems somewhere else in the doctrine_bridge code it still expects a fieldname when trying to assign keys to the final collection you get back from doctrine. And since you can't use a fieldname anymore, they keys don't get assigned with the expected values.

It seems although doctrine doesn't validate the "indexBy" field annotation (you can put anything there) and the docs aren't clear on that, it expects the field name:

https://github.com/doctrine/orm/blob/c1943624ab1260c629316bab104dc5130c060154/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L516

but since column names follow the namingStrategy usually, it works in most cases, until the column name and the field name are are totally different

**Comment by juanmiguelbesada** [comment]
#38628 was updated, can you check if it solves the issue now?

**Comment by tannyl** [comment]
@juanmiguelbesada I just got around to test it, and the problem seems to be fixed now. It works again using the field name (**channelCode**).

Now we just need a 4.4.17 with the fix applied.

**Comment by xabbuh** [comment]
@tannyl Thank you for the confirmation. That's much appreciated.

**Comment by lchrusciel** [comment]
Thanks for all your efforts as well!
