### ISSUE TITLE
[Ldap] Warning on reset pagination

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/symfony#38874]
**Symfony version(s) affected**: 5.1.8

**Description**  
After #38392 \Symfony\Component\Ldap\Adapter\ExtLdap\Query::resetPagination returns warning from Adapter/ExtLdap/Query.php::239

```
Warning: ldap_parse_result() expects parameter 2 to be resource, int given
```

I can suppose that cause is on Adapter/ExtLdap/Query.php::177

**Comment by a-menshchikov** [comment]
@lucasaba Could you watch this?

**Comment by Nek-** [comment]
Hello @a-menshchikov does this ( https://github.com/symfony/symfony/pull/38875 ) fix your problem as expected?

**Comment by lucasaba** [comment]
@a-menshchikov  I'm on it. But that's quite strange: how is the resource supposed to change and become an int ?

**Comment by a-menshchikov** [comment]
@Nek- yes, your fix helped.

**Comment by lucasaba** [comment]
Just to confirm that I've added the error. As @jderusse pointed out in #38875 , I've changed a method with the wrong name.
