### ISSUE TITLE
symfony/mime requires phpdocumentor/reflection-docblock but doesn't use it

### ISSUE THREAD

**Issue by garak** [symfony/symfony#38886]
**Symfony version(s) affected**: 5.2

**Description**  

In [1a5636c](https://github.com/symfony/mime/commit/1a5636cbf45cbf1d9c1c9b3716f680340b0a826b) a dependency has been introduced, even if mime library doesn't use directly phpdocumentor library.

**Possible Solution**  

Remove phpdocumentor/reflection-docblock from dependencies of symfony/mime

**Comment by nicolas-grekas** [comment]
Please send a PR
