### ISSUE TITLE
[Serializer] Not able to ignore constructor when instantiating object through normalizer

### ISSUE THREAD

**Issue by onionpsy** [symfony/symfony#38880]
**Symfony version(s) affected**: 4.4

**Description**  
hey. I'm trying to keep track of all properties changed when instantiating a new object through serializer (and normalizer) but values are being unset once normalized. My class has parameters in the constructor so it goes through [this part](https://github.com/symfony/serializer/blob/6f5ac2d398a025e2b064d80a0ccd55f12b02dbd2/Normalizer/AbstractNormalizer.php#L380) and an `unset` is called, which removes the values from the normalized data.

**How to reproduce** 
Using the `ObjectNormalizer` with `PhpDocExtractor` in the serializer and calling `deserialize` on this kind of json:
```
{
    "postcode": "1234"
}
```
Data class:
```
class Address
{
    public function __construct(
        ?string $postcode = null,
        ?string $city = null
    ) {
        $this->postcode = $postcode;
        $this->city = $city;
    }
    ...
    (getters & setters)
}
```

**Possible Solution**  
Either having the possibility to pass an option to the `ObjectNormalizer` to ignore the `unset` when going through the constructor or ignoring the constructor arguments when params are nullable and have a default value of null

**Additional context**

**Comment by xabbuh** [comment]
I am not sure I understand the issue. What did you expect and what happened instead? Do you get any error message?

**Comment by onionpsy** [comment]
Sorry just reread it and I realise my explanation are not completely clear. Here a more explicit example:
```
class Address
{
    public $modifiedFields = [];

    private $postcode;
    private $city;

    public function __construct(?string $postcode = null)
    {
        $this->postcode = $postcode;
    }

    public function addModifiedFields(array $modifiedField): void
    {
        $this->modifiedFields = array_merge($this->modifiedFields, $modifiedField);
    }
        
    (getters & setters)

}
```
```
// PropertyAccessor Decorator, then injected in the serializer
public function setValue(&$address, $propertyPath, $value)
{
    $address->addModifiedFields([$propertyPath]);
    $this->propertyAccessor->setValue($address, $propertyPath, $value);
}
```
```
// logic
$object = $serializer->deserialize('{"postcode": 1234, "city": "Foobar"}', Address::class, 'json');
dump($object); // city and postcode are correctly set
dump($object->getModifiedFields()); // show ["city"] but expect ["city", "postcode"]
```

So no error but because of the default parameter in the constructor, the PropertyAccessor doesn't keep track of the property.

**Comment by stof** [comment]
well, your postcode is injected through the constructor, not by the PropertyAccessor. So this is logical.

**Comment by xabbuh** [comment]
Closing as explained by @stof then. Thank you for understanding.
