### ISSUE TITLE
improve php doc

### ISSUE THREAD

**Issue by javansolo** [symfony/symfony#38892]
hi
Function name must be callable - a string, Closure or class implementing __invoke, currently \Symfony\Component\HttpFoundation\Session\SessionInterface or callable on phpdoc

https://github.com/symfony/symfony/blob/9aac4f444a3cae77759d096b086acf3c11be262d/src/Symfony/Component/HttpFoundation/Request.php#L187
change to 
SessionInterface|callable

![](https://user-images.githubusercontent.com/11363999/97446347-8b917100-1943-11eb-8e1c-170fa838be30.png)

**Comment by Nyholm** [comment]
Excellent. 
Thank you for this issue. 

It is fixed in 4.4 and will soon (the next few days) be merged up to 5.1 and 5.x.
