### ISSUE TITLE
[DoctrineBridge] Massive memory usage increase in 5.1

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#38890]
**Symfony version(s) affected**: 5.1

**Description**  

After upgrading to 5.1 my tests suddenly started failing on memory limit. So I ran them through blackfire and found out that between Symfony 5.0 and 5.1 the memory usage in my tests increased from < 500 MB to over 1.2 GB.

Then I tried to upgrade just a few packages at a time to find out which one was causing it and the culprit is `symfony/doctrine-bridge`. More specifically, the [changes in `Symfony\Bridge\Doctrine\Form\Type\DoctrineType` class](https://github.com/symfony/doctrine-bridge/compare/v5.0.11...v5.1.8#diff-393efbcebf08c47d11ba4ff598f11e511ef7ee71e8a725b5ce2ccb388817ada6). When I revert just this class to it's 5.0 version, the problem disappears.

Git blame leads me to #30994 as the most likely cause.

cc @HeahDude

**Comment by cybernet** [comment]
+1

**Comment by enumag** [comment]
Fixed it in my test suite by calling this in `tearDown()`

```php
static::$kernel->getContainer()->get('services_resetter')->reset();
```

**Comment by simonberger** [comment]
@enumag  @cybernet Are you running all your tests with one kernel?
You could try to watch the memory usage of the caches in `DoctrineType`. That seemed to me as the most likely reason.
EntityLoader Cache existed already before. Not sure if the class could be bigger now though.

I added some logging to the class for idReaders and entityLoaders and ran my tests:

```
private function getCachedEntityLoader(ObjectManager $manager, $queryBuilder, string $class, array $vary): EntityLoaderInterface
    {
        $hash = CachingFactoryDecorator::generateHash($vary);

        if (isset($this->entityLoaders[$hash])) {
            return $this->entityLoaders[$hash];
        }

        $memBefore = memory_get_usage();
        $el = $this->entityLoaders[$hash] = $this->getLoader($manager, $queryBuilder, $class);
        $memAfter = memory_get_usage();

        log("Memory Usage EL:" . ($memAfter - $memBefore));

        return $el;
    }

private function getCachedIdReader(ObjectManager $manager, string $class): ?IdReader
    {
        $hash = CachingFactoryDecorator::generateHash([$manager, $class]);

        if (isset($this->idReaders[$hash])) {
            return $this->idReaders[$hash];
        }

        $memBefore = memory_get_usage();
        $idReader = new IdReader($manager, $manager->getClassMetadata($class));

        $this->idReaders[$hash] = $idReader->isSingleId() ? $idReader : null;

        // don't cache the instance for composite ids that cannot be optimized

        if ($this->idReaders[$hash] !== null) {
            $memAfter = memory_get_usage();
            log("Memory Usage IDR:" . ($memAfter - $memBefore));
        }

        return $this->idReaders[$hash];
    }
```

In my case there weren't that many calls and also no alarming high numbers but the objects might get much bigger than those I got.

**Comment by stof** [comment]
I think we need to reset `$this->idReaders` as well in the `reset()` method
