### ISSUE TITLE
[Console] Too many arguments message contains an incorrect number of missing arguments

### ISSUE THREAD

**Issue by aadmathijssen** [symfony/symfony#38904]
**Symfony version(s) affected**: 5.1.8 (and earlier)

**Description**  

Whenever a Symfony Console command is called with too many arguments, a "Too many arguments" error is shown on the CLI. This message also states _which_ arguments are expected. But this message always contains `"command"` as an extra argument. This can be confusing for the user, as the reported number of arguments is one off with what it should be.

**How to reproduce**  

Install the Symfony skeleton and run the following command:

```
bin/console secrets:list foo
```

It shows the following message:

```
Too many arguments, expected arguments "command".
```

This is incorrect, as the command itself expects no arguments at all.

Similarly, the command

```
bin/console secrets:set foo bar baz
```

shows the message:

```
Too many arguments, expected arguments "command" "name" "file".
```

Here I would have expected a message stating that that `"name"` and `"file"` are the expected arguments, but not `"command"`.

**Possible Solution**  

The message is thrown on [line 139 of src/Symfony/Component/Console/Input/ArgvInput.php](https://github.com/symfony/symfony/blob/v5.1.8/src/Symfony/Component/Console/Input/ArgvInput.php#L169).

Here it can be seen that keys of the `$this->definition->getArguments()` array are printed.

The simplest solution to fix this seems to remove the first key of the array when creating the exception message.

**Comment by Nyholm** [comment]
Hm.. I think there is a terminology confusion here. 

The actual command/program/binary you are running is `bin/console`. The first argument to that command is "symfony-command-name", (ie a cli name of a class extending `Command`). 

When you are running: 

```
bin/console secrets:list foo
```

It is the `bin/console` command/program/binary that says: "Hey, too many arguments, Im only expecting a symfony-command-name."

Does it make more sense?

**Comment by aadmathijssen** [comment]
Well, I think the problem is that the contents of the error message depend on the command that is used. More precisely, the names of the actual expected arguments (except from `"command"`) only make sense for the command that was supplied.

So I think it is better to formulate the exception in the context of the command that is used, i.e. use something like

```
Too many arguments supplied for this command, expected "name" "file".
```

instead of

```
Too many arguments, expected arguments "command" "name" "file".
```

**Comment by Nyholm** [comment]
Yeah. I can agree with that. Or even better:

> Too many arguments supplied for “acme:foobar” command, expected "name" "file".

**Comment by aadmathijssen** [comment]
Yes that's even better. Thanks for the PR, @Nyholm!
