### ISSUE TITLE
[Serializer] XmlEncoder  value & attributes

### ISSUE THREAD

**Issue by stempora** [symfony/symfony#38914]
Hello, 

I want to generate an xml like 
`<test>
    <component attr="value">some content</component>
</test>`

Any way to achieve that ? Some content if i leave without a key it will generate an `<item key="0">some content</item>`

Thanks

**Comment by derrabus** [comment]
Hello and thank you for reaching out. This issue tracker is not meant for support questions. You can get help via Slack or StackOverflow, as described here: https://symfony.com/support

**Comment by stempora** [comment]
Hi, This is not a support question its more like a missing feature ...

**Comment by dweipert-3138720606** [comment]
Not a missing feature. Here is an example: https://github.com/symfony/symfony/issues/34579

You can add the content to the node with the `#` key.
