### ISSUE TITLE
Too many arguments, expected arguments "command". LARAVEL 5.7

### ISSUE THREAD

**Issue by michelmelo** [symfony/symfony#38937]
**Symfony version(s) affected**: 4.4.0

**Description**  
Too many arguments, expected arguments "command".
Too many arguments, expected arguments "command". {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Too many arguments, expected arguments \"command\". at /XXX/vendor/symfony/console/Input/ArgvInput.php:172)

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
see #38904
