### ISSUE TITLE
Not well-formed translation file for Galician (gl) 

### ISSUE THREAD

**Issue by wkania** [symfony/symfony#38935]
**Symfony version(s) affected**: 4.4

**Description**  
Introduced by https://github.com/symfony/symfony/pull/38905  
Pull request tests didn't report any error but cache clear did.
`vendor/symfony/form/Resources/translations/validators.gl.xlf"; Errors: [ERROR 1843] Elemen  
  t '{urn:oasis:names:tc:xliff:document:1.2}body': Character content other than whitespace is not allowed because the content type is 'el  
  ement-only'`

**Possible Solution**  
There is a dot there https://github.com/symfony/symfony/pull/38905/files#diff-274c5f6a97ba57976d71383ac61a71d1fa205e47bccb56f41a8e0b7b5e44d99cR20

**Comment by Nyholm** [comment]
Excellent. Thank you for reporting and fixing this.
