### ISSUE TITLE
Symfony Finder: Get all the files with a specific extension and all the directories within a specific directory

### ISSUE THREAD

**Issue by leo95batista** [symfony/symfony#38949]
Hi, I'm sorry to ask my question here, but from my country I can't use Slack. I am using the ```Symphony Finder``` component to get all the files with a certain extension and all the directories in a specific directory.

```

    protected function getDirectoryContent(string $directory): array
    {
        $finder = Finder::create()
            ->in($directory)
            ->depth(0)
            ->name(['*.json', '*.php'])
            ->sortByName();

        return iterator_to_array($finder, true);
    }

```
In this way, this method returns only all the files with extension ```.php``` or ```.json``` within a certain directory. For example, the directory structure I am looking in is the following:

```
/my/directory/
├── A
├── A.JSON
├── anotherfile.kas
├── file0.ds
├── file1.json
├── file2.php
├── file3.php
├── B
└── C
```

```A```, ```B``` and ```C``` are directories.

When I pass the above ```directory path``` as the ```$directory``` argument in the method I showed above, I get an array with the following elements:

```
file1.json
file2.php
file3.php
```

Great!, but my question is, how could I also add all the ```directories``` to the resulting array? My expectations are to get an array like the following:

```
A
B
C
file1.json
file2.php
file3.php
```

**Comment by Nyholm** [comment]
Hey. 
You cannot :(

Because the directory names do not match "*.json" or "*.php". You need to create another finder instance and only get directories.

Something like this maybe:

```php
    protected function getDirectoryContent(string $directory): array
    {
        $finder = Finder::create()
            ->in($directory)
            ->depth(0)
            ->name(['*.json', '*.php']);
        $finderDir = Finder::create()
            ->in($directory)
            ->depth(0)
            -> directories();

        $files = iterator_to_array($finder, true);
        $dirs = iterator_to_array($finderDir, true);

        return array_merge($files,$dirs);
    }
```
See https://symfony.com/doc/current/components/finder.html#files-or-directories

----

Also note that stackoverflow is excellent for questions: https://symfony.com/support

**Comment by ZhukV** [comment]
It's possible with use `filter` model. For more details see answer https://stackoverflow.com/a/64649990/1787682
