### ISSUE TITLE
Error when i add custom interface on CurlHttpClient

### ISSUE THREAD

**Issue by ioniks** [symfony/symfony#38979]
**Symfony version(s) affected**: 5.1.8
**Serveur version**: Ubuntu 16.04
**Apache version**: 2.4.43
**Php version** : 7.4.8

**Description**  
When i create a new CurlHttpClient and i make a requestion with option :
`['bindto' => 'eth0:1']`
i have an error Failed binding local connection end
On SF 5.1.5 all work well

**How to reproduce**  
A fresh install of 5.1.8 with a request with CurlHttpClient and just the same parameters (and a FO ip on the serveur)

**Comment by derrabus** [comment]
This might be my fault: #38215

**Comment by nicolas-grekas** [comment]
Reading https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html I'd suggest adding support for the special if! prefix to fix this.
We could also retry such failures and skip CURLOPT_LOCALPORT  when doing so.

**Comment by nicolas-grekas** [comment]
We might need to account for https://curl.haxx.se/libcurl/c/CURLOPT_LOCALPORTRANGE.html btw

**Comment by ioniks** [comment]
The fix for this can be in 5.2 release ?

**Comment by nicolas-grekas** [comment]
Please use `if!eth0:1` once 5.1.9 is released.
