### ISSUE TITLE
[InvalidArgumentException] Unable to require symfony/mailjet-mailer

### ISSUE THREAD

**Issue by SwordaDev** [symfony/symfony#38984]
**Symfony version(s) affected**: 5.1.8

**Description**  
Trying to require [symfony/mailjet-mailer](https://github.com/symfony/mailjet-mailer).
Getting the error prompt:
```
[InvalidArgumentException]
Could not find package symfony/mailjet-mailer in a version matching 5.1.*
```

**How to reproduce**  
Trying to execute `composer require symfony/mailjet-mailer` while on the version 5.1.8 of Symfony.

**Comment by xabbuh** [comment]
The symfony/mailjet-mailer package will have the first stable release when Symfony 5.2 is tagged. You need run something like this: `composer require symfony/mailjet-mailer:^5.2@beta`
