### ISSUE TITLE
console: Ansi stripped on stdout when stderr is redirected

### ISSUE THREAD

**Issue by cxj** [symfony/symfony#38981]
**Symfony version(s) affected**: 5.1.8

**Description**  
ANSI color is stripped (command behaves if run with `--no-ansi` flag) from standard output when standard error is redirected.

**How to reproduce**  
Pick any console app that issues output with ANSI color, and in a POSIX shell such as `sh` or `bash`, redirect standard error, e.g.:

`bin/console some:command 2> /dev/null`

**Possible Solution**  
I would guess the `*_isatty()` check is being done on both stdout and stderr file descriptors and if either is not a TTY, the ANSI flag is wrongly cleared for both.  Solution would be to check and manage the 2 file streams or descriptors separately.

**Additional context**  
Explicitly adding the `--ansi` flag makes it work, e.g.:
`bin/console --ansi some:command 2> /dev/null` 
correctly outputs the stdout text, such as `[OK] message`, in ANSI color.

**Comment by wouterj** [comment]
Thank you @cxj for opening an issue after your tweet! I can reproduce this on Symfony 4.4 as well.

Seems like at first Symfony used to only check stdout (ref #10592), as the output formatter is shared between stdout and stdin. 2 PRs were submitted to fix this behavior:

* #13661 proposed to clone the output formatter, to allow differences between stdout and stderr. The issue raised here was "this breaks applications using a custom output formatter that cannot be cloned".
* #15771 proposed to instead do the check on stdout and stderr and disable decoration of any of them isn't a tty. "It's not a perfect solution but it's better than having both enabled as this breaks things."

I think we should reconsider #13661. It's very unlikely AFAICS that someone overrides the output formatter with something that cannot be closed. Seems like the PR simply stalled and Composer didn't have the time to wait for the perfect solution.

Status: Reviewed

**Comment by cxj** [comment]
Note this also fails in the opposite way.  If one redirects standard output, then the TTY receiving the standard error data also loses the ANSI color, unless an explicit `--ansi` is provided.  Example:
```sh
bin/console somecommand > output/file  # fails, stderr on tty screen has no color
```
```sh
bin/console --ansi somecommand > output/file  # works, stderr on sceen has color
```

Thanks for looking into this.  Because Unix/POSIX has a very strong model of using pipe-lined commands at the CLI, it's important to support this model of usage.  For example, user sees errors, warnings, metadata and progress, while final data is in the output file:
```sh
% bin/console get:data | fgrep 'target-string' | sort | uniq -c | sort -n > frequencies.dat
connected to mysql @ 127.0.0.1 via TCP/IP
123456 rows selected
123400 rows extracted
56 duplicate data rows
```

**Comment by wouterj** [comment]
I've tested both directions with the patch provided in #38991. It seems like this patch fixes it.
