### ISSUE TITLE
PHP8RC3 Segmentation fault after accessing cache pools with preload enabled.

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#38997]
**Symfony version(s) affected**: Reproducer in 5.1.7, but my project is 4.x

**Description**  
Not sure if this is a Symfony thing or just plain PHP 8 RC3 bug, there seems to be lots of segmentation faults with preloading already raised in bugs.php.net for PHP8 ... 

**How to reproduce**  

Install PHP 8.0.0 RC 3 (However you wish, mine was a docker container)
symfony new --demo my_project
edit .env set ENV=prod
php bin/console cache:clear
cd my_project/public
php -S 0.0.0.0:8000

**Note the project loads fine without preload enabled!**

Now, edit your php.ini to add (and check your paths) 

```
[opcache]
opcache.enable=1
opcache.preload='/application/var/cache/prod/App_KernelProdContainer.preload.php';
opcache.preload_user=www-data
```

Then start server again `php -S 0.0.0.0:8000`

Attempt to load a page over http

<img width="669" alt="Screenshot 2020-11-05 at 00 35 01" src="https://user-images.githubusercontent.com/400092/98182889-c4f74d00-1efe-11eb-8d3e-930d67df7d88.png">

Note that it segfaults... 

With a strace running on the process it ALWAYS segfaults with the Pools random folder names being the last folder accessed - **I CAN REPLICATE THAT WITH MY LIVE PROJECT,** its always just after accessing the cache pools. 

<img width="802" alt="Screenshot 2020-11-05 at 00 39 53" src="https://user-images.githubusercontent.com/400092/98183196-93cb4c80-1eff-11eb-8a00-4d03e02551be.png">

**Comment by nicolas-grekas** [comment]
Segfaults are always php bugs, please report this to bugs.php.net with a minimalist reproducer if possible.
(Thanks for testing php8 btw :))

**Comment by PhilETaylor** [comment]
No worries, I'll do that. My reproducer was the simple `symfony new --demo my_project` out of the box so should be easy to replicate.

**Comment by PhilETaylor** [comment]
https://bugs.php.net/bug.php?id=80321

**Comment by stof** [comment]
@PhilETaylor this might not be a *minimalist* reproducer though

**Comment by PhilETaylor** [comment]
@stof Im running PHP8RC3 all this weekend, so if I can make it more "minimalist" then I will.

**Comment by PhilETaylor** [comment]
Im pleased to report, after compiling PHP from git sources, in Alpine Docker containers, and running PHP 8.1.0-dev with my Symfony 4.4.16 application, with PHP Preloading enabled, and JIT Enabled, this bug seems resolved and PHP doesn't segfault.

It seems this has been fixed since PHP8.0RC3 :-) in PHP bug https://bugs.php.net/80307.

Thanks.
