### ISSUE TITLE
[Validator] - message as default option for some constraints

### ISSUE THREAD

**Issue by ybenhssaien** [symfony/symfony#39000]
**Description** 

The idea is to make `message` as the default option for the list of constraints below since the message is almost times the only  option custimized for default group  :
- [x] [`Blank`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Blank.php)
- [x] [`NotBlank`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/NotBlank.php)
- [x] [`IsTrue`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/IsTrue.php)
- [x] [`IsFalse`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/IsFalse.php)
- [x] [`IsNull`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/IsNull.php)
- [x] [`NotNull`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/NotNull.php)
- [x] [`Email`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Email.php)
- [x] [`Date`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Date.php)
- [x] [`Country`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Country.php)
- [x] [`Currency`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Currency.php)
- [x] [`Iban`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Iban.php)
- [x] [`Ip`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Ip.php)
- [x] [`Issn`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Issn.php)
- [x] [`Isin`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Isin.php)
- [x] [`Json`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Json.php)
- [x] [`Language`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Language.php)
- [x] [`Locale`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Locale.php)
- [x] [`Luhn`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Luhn.php)
- [x] [`NotCompromisedPassword`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/NotCompromisedPassword.php)
- [x] [`Time`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Time.php)
- [x] [`Unique`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Unique.php)
- [x] [`Url`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Url.php)
- [x] [`Uuid`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Uuid.php)
- [x] [`Ulid`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Validator/Constraints/Ulid.php)

```php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class User
{
    /**
     * @Assert\NotBlank(message="The name accepts only a non blank string, '{{ value }}' is given")
     */
    public ?string $name = null;

    /**
     * @Assert\Country("The given country is not in Alpha2 nor Alpha3 format")
     */
    public ?string $countryCode = null;
}
```

Passing a message without an option throws exception : 
![image](https://user-images.githubusercontent.com/7301643/98236508-bf801e00-1f63-11eb-8ec3-65f90ea9b213.png)

**Example** 

```diff

    /**
-     * @Assert\NotBlank(message="The name accepts only a non blank string, '{{ value }}' is given")
+     * @Assert\NotBlank("The name accepts only a non blank string, '{{ value }}' is given")
     */
    public ?string $name = null;

    /**
-     * @Assert\Country(message="The given country is not in Alpha2 nor Alpha3 format")
+     * @Assert\Country("The given country is not in Alpha2 nor Alpha3 format")
     */
    public ?string $countryCode = null;
```

**Comment by ogizanagi** [comment]
Thanks for proposing, but this was rejected in #39024
