### ISSUE TITLE
Dependency Injection inifinite loop handling circular references consuming memory 

### ISSUE THREAD

**Issue by soyuka** [symfony/symfony#39015]
**Symfony version(s) affected**: 5.2.x

**Description**  
Clearing the cache with latest symfony breaks on `api-platform/core`

**How to reproduce**  

```bash
git clone git@github.com:api-platform/core
cd core
# If you have moreutils, or just add the minimum-stability dev to the composer.json
jq '. + {"minimum-stability": "dev"}' composer.json | sponge composer.json
composer install
php tests/Fixtures/app/console cache:warmup -vv
```

This will lead to an out of memory error (be sure you don't use `memory_limit=-1`)

**Possible Solution**  

Revert the code changed in PhpDumper (see https://github.com/symfony/symfony/pull/38980/files#diff-82d7ebdd6477cecb404b0d3f100a9026e950529edb9a665460ae0330dfad7080L454)

```diff
        foreach ($edges as $edge) {
            $node = $edge->getDestNode();
            $id = $node->getId();
+            if (!$node->getValue() instanceof Definition || $sourceId === $id || $edge->isLazy() || $edge->isWeak()) {
-            if (!$node->getValue() instanceof Definition || $sourceId === $id || $edge->isWeak()) {
                continue;
            }
```

If you reproduced and want to try the fix, just `rm -rf tests/Fixtures/app/var/cache/` and use the command again.

ref: #38980

**Comment by jderusse** [comment]
I optimized the way the loop are detected (see #39019 )
Tell me of it fixes your issue.

Note: this is not an infinite loops, but an exponential loop that consume a huge amount of memory

**Comment by soyuka** [comment]
> Note: this is not an infinite loops, but an exponential loop that consume a huge amount of memory

Using 8gb of memory also breaks on my issue. 

The patch in #39021 does not fix the issue. 

Some more details on the error:

```
php -dmemory_limit=1g tests/Fixtures/app/console cache:warmup --no-optional-warmers -vvv

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /home/soyuka/forks/core/tests/Fixtures/app/var/cache/test/ContainerKApm16H/EntityManager_9a5be93.php on line 163
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /home/soyuka/forks/core/tests/Fixtures/app/var/cache/test/ContainerKApm16H/EntityManager_9a5be93.php on line 163
```

The code there looks like this:

```
    public function getConfiguration()
    {
        $this->initializer6977e && ($this->initializer6977e->__invoke($valueHoldera8e22, $this, 'getConfiguration', array(), $this->initializer6977e) || 1) && $this->valueHoldera8e22 = $valueHoldera8e22;
        return $this->valueHoldera8e22->getConfiguration();
    }
```

It's always the same `EntityManager` related code that consumes memory indefinitely.

**Comment by jderusse** [comment]
Hmm, this breaks since #3812 because now, a lazy service used a proxy. Which end in an infinity loop where the proxy is injected inside the proxy.

this is fixed by https://github.com/symfony/symfony/compare/85d8004602f0b4e18999ade5cb8ecabfa6a06f42..d3b951b767e70a40c80ddbb9ebfcfe7518f14c81 could you give a try @soyuka ?

@nicolas-grekas this second issue, shows that some lazy services MUST stop the loop detection, do you have other similar case in mind?

**Comment by soyuka** [comment]
https://github.com/symfony/symfony/compare/85d8004602f0b4e18999ade5cb8ecabfa6a06f42..d3b951b767e70a40c80ddbb9ebfcfe7518f14c81 fixes the issue.
