### ISSUE TITLE
[Notifier] Dynamic transports

### ISSUE THREAD

**Issue by HanXHX** [symfony/symfony#39014]
**Description**  

The notifier must be configured statically in config files.

However, it can be useful to load some config (from DB). For example, you can have a Slack config per logged user.

**Example**

```php
// user fetched from db

$recipient = new Recipient($user->getEmail())
if ($user->getSlackId() !== null) {
    $recipient->setExtraTransports([new SlackTransport($user->getSlackId())])
}

$notification = (new Notification('New Invoice'))
    ->content('You got a new invoice for 15 EUR.')
    ->importance(Notification::IMPORTANCE_HIGH);

$notifier->send($notification, $recipient);
```

**Comment by kevincerro** [comment]
I'm interested in this too.

Can be very interesting for example if you develop a SaaS product, where each user will provide their own transport credentials.
