### ISSUE TITLE
Symfony LDAP testing

### ISSUE THREAD

**Issue by lucasaba** [symfony/symfony#39028]
**Symfony version(s) affected**: 4.4.* and following

**Description**  
LDAP test are never run.

**How to reproduce**  
ALL test are skipped when no LDAP server is reachable. And no LDAP is provided in github actions, Travis CI and in AppVeyor.

**Possible Solution**  
Add an OpenLDAP server in Github Actions

**Additional context**  
I'm developing on a separate branch a possible solution. The branch is this: https://github.com/lucasaba/symfony/tree/add-ldap-tests

It already adds some of the proposed solution from @Nek- in #38875 
It adds an external dependency on an [openldap docker image](https://hub.docker.com/repository/docker/lucasaba/symfony-openldap) that I'm trying to avoid but... with no luck.
Using this information I was able to run almost all test and to correct some problem on them.

I'm working on fixing a strange error when dealing with PHP 7.1: ["Crtitical extension unavilable"](https://github.com/lucasaba/symfony/runs/1368325731?check_suite_focus=true#step:9:71). As soon as I've fixed that, I'll made a PR.

Any help to avoid dealing with my personal docker image for openldap on github actions would be gratly appreciated.

**Comment by wouterj** [comment]
Travis does include some set-up for openldap. So I'm not sure why they are skipped, but it seems there at least was an intention to test ldap on Travis.

https://github.com/symfony/symfony/blob/67948a7ffb88fb6146ad57e12a745dbd9341a592/.travis.yml#L102-L106

**Comment by lucasaba** [comment]
I think symfony is moving on github actions. At least that's what I could understand from @nicolas-grekas [response](https://github.com/symfony/symfony/pull/38392#issuecomment-703528763).

But I can have a look at Travis too.

**Comment by derrabus** [comment]
We've shifted integration tests to GHA, so testing LDAP on GHA sounds reasonable.

**Comment by wouterj** [comment]
Yes, I think it's fine to "move" ldap integration tests to github actions. We should then remove the travis ldap set-up I think (that might also improve Travis performance a bit).
