### ISSUE TITLE
[HttpClient] TraceableHttpClient does not implement ClientInterface (from PSR-18)

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#39023]
**Symfony version(s) affected**: 5.1.3 

**Description**  

When using a service that requires `ClientInterface` from `PSR-18`, the `TraceableHttpClient` cannot be injected as it does not implement the interface.

**How to reproduce**  

Create a fresh project, install the `psr/http-client` along with `nyholm/psr7` and create a service that requires `ClientInterface` in its constructor. 

**Possible Solution**  

Create a `TraceablePsr18HttpClient` which implement the interface.

**Additional context**  

Here's the error message: 

```
08:24:28 CRITICAL  [php] Uncaught Error: Argument 3 passed to MeiliSearch\Client::__construct() must implement interface Psr\Http\Client\ClientInterface or be null, instance of Symfony\Component\HttpClient\TraceableHttpClient given, called in /Users/guillaume/Desktop/ms/var/cache/dev/ContainerEtEvIM9/App_KernelDevDebugContainer.php on line 814
```

The bug is related to the usage linked here: https://github.com/Guikingone/MeiliSearchBundle/blob/master/src/DependencyInjection/MeiliSearchExtension.php#L144

The internal `Client` class requires a `ClientInterface` implementation: https://github.com/meilisearch/meilisearch-php/blob/master/src/Client.php#L56

**Comment by nicolas-grekas** [comment]
You should inject the traceable client into the psr18 adapter.
