### ISSUE TITLE
[Serializer] Add a way to provide a context in mapping

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#39039]
**Description**  

Originally described in https://github.com/symfony/symfony/issues/38993#issuecomment-723556450, I'd suggest adding a new `@Serializer\Context` annotation/php attribute/xml and yaml mapping config.

It could accept a `normalizationContext`, `denormalizationContext` or both `context` at once (default option), and perhaps a `traverse` option to forward the context on deeper nodes if any (when applied on class/object properties).

**Example**  

```php
class Foo
{
    /**
     * @var \DateTime
     *
     * @Serializer\Context({
     *      DateTimeNormalizer::FORMAT_KEY = 'Y-m-d',
     * })
     */
    public $date;
}
```

This specifically changes the format used to (de)normalize the `Foo::$date` property while keeping the default context (or the one provided in the `(de)serialize` call) everywhere else.

Any normalizer with specific context options would benefit from it, as it'll allow to configure anything on a per-case basis.

**Comment by ro0NL** [comment]
do we expect multiple context variations on the same prop, based on groups?

maybe related to https://github.com/symfony/symfony/pull/37903

**Comment by ogizanagi** [comment]
Hmm, that's an interesting idea. I'd like to keep it simple in first place, but why not iterate.
I'm not the one that'll use such a feature though, as I tend to avoid groups as much as possible to keep things simple clear, mostly using different DTOs. So perhaps first see if that's something someone would need?

**Comment by ro0NL** [comment]
@ogizanagi agree, nevertheless groups are first class documented feature. Along with #37903 i think it raises certain expectations, we perhaps could anticipate more explicitly: `@ContextualGroups()` maybe.

Im not sure we'd like to end up with different annotations, handling "per group" configuration, potentially all in different ways.

**Comment by ogizanagi** [comment]
See https://github.com/symfony/symfony/pull/39399 for a suggested implementation
