### ISSUE TITLE
[HttpKernel][Console] Inconsistent logging between the components

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#39050]
**Symfony version(s) affected**: 3.4, 4.4, 5.x

**Description**
`Symfony\Component\HttpKernel\EventListener\ErrorListener`  logs non-HTTP exceptions as `LogLevel::CRITICAL`.
`Symfony\Component\Console\EventListener\ErrorListener`  logs exceptions as `LogLevel::ERROR`.

This is incoherent. Both listeners should log non-HTTP exceptions at the same level.

**Possible Solution**
Correcting `Symfony\Component\Console\EventListener\ErrorListener` so it logs at `LogLevel::CRITICAL.`

**Comment by micheh** [comment]
See also #29138

**Comment by chalasr** [comment]
I'm closing this issue for the reasons given in #29138.

**Comment by alex-dev** [comment]
Reasons given in #29138 do not address the issue at all.
- `Symfony\Component\Messenger\Worker` logs its unrecoverable errors at `LogLevel::CRITICAL`. 
- `Symfony\Component\HttpKernel\EventListener\ErrorListener` logs its unrecoverable errors at `LogLevel::CRITICAL`.

Why would `Symfony\Component\Console\EventListener\ErrorListener` have another behaviour?
Here is the relevent PSR-3 documentation.
> ```
>     /**
>      * Critical conditions.
>      *
>      * Example: Application component unavailable, unexpected exception.
>      *
>      * @param string $message
>      * @param array $context
>      * @return void
>      */
>     public function critical($message, array $context = array());
> 
>     /**
>      * Runtime errors that do not require immediate action but should typically
>      * be logged and monitored.
>      *
>      * @param string $message
>      * @param array $context
>      * @return void
>      */
>     public function error($message, array $context = array());
> ```

Unexpected exceptions should logged at `LogLevel::CRITICAL`, not at `LogLevel::ERROR`.
