### ISSUE TITLE
@Autowired annotation

### ISSUE THREAD

**Issue by Microtribute** [symfony/symfony#39054]
**Description**  
It would be nice if we had `@Autowired` annotation like Spring. Rather than injecting services via the constructor, we could use `@Autowired` annotation to make it even simpler. Check out the examples below:

**Example**  
Currently we're injecting services via the constructor.

```php
namespace App\Manager;

use Psr\Log\LoggerInterface;
use Symfony\Component\Routing\Matcher\UrlMatcherInterface;

class TrafficManager
{
    private UrlMatcherInterface $urlMatcher;
    private LoggerInterface $logger;

    public function __construct(UrlMatcherInterface $urlMatcher, LoggerInterface $logger)
    {
        $this->urlMatcher = $urlMatcher;
        $this->logger = $logger;
    }

    public function match(string $url)
    {
        try {
             $this->urlMatcher->match($url);
        } catch (\Throwable $e) {
            $this->logger->error($e->getMessage());
        }
    }
}
```

If we had `@Autowired` annotation, we could make this simpler eliminating the need of creating a constructor.

```php
namespace App\Manager;

use Psr\Log\LoggerInterface;
use Symfony\Component\Routing\Matcher\UrlMatcherInterface;
use Symfony\Comonent\DependencyInjection\Annotations\Autowired;

class TrafficManager
{
    #[Autowired]
    private UrlMatcherInterface $urlMatcher;
    
    #[Autowired]
    private LoggerInterface $logger;

    public function match(string $url)
    {
        try {
             $this->urlMatcher->match($url);
        } catch (\Throwable $e) {
            $this->logger->error($e->getMessage());
        }
    }
}
```

**Comment by michaljusiega** [comment]
Currently is `@required` annotation, but working only on public properties. See https://symfony.com/doc/current/service_container/autowiring.html#autowiring-other-methods-e-g-setters-and-public-typed-properties

**Comment by derrabus** [comment]
We have `#[Required]` that does just that for public properties. For private properties, use constructor injection instead. If you have php 8 available, you can use constructor property promotion.

```php
namespace App\Manager;

use Psr\Log\LoggerInterface;
use Symfony\Component\Routing\Matcher\UrlMatcherInterface;

class TrafficManager
{
    public function __construct(
        private UrlMatcherInterface $urlMatcher,
        private LoggerInterface $logger,
    ) {}

    public function match(string $url)
    {
        try {
             $this->urlMatcher->match($url);
        } catch (\Throwable $e) {
            $this->logger->error($e->getMessage());
        }
    }
}
```

**Comment by Microtribute** [comment]
A deadly simple example of injecting a service into a non-public property would look like this.

```php
class Service
{
    /**
     * @Autowired
     */
    private LoggerInterface $logger;

    public function getLogger(): LoggerInterface
    {
        return $this->logger;
    }
}


$service = new Service();

$ref = new ReflectionObject($service);

$properties = $ref->getProperties();

foreach ($properties as $property) {
    $isAutowired = false !== strpos($property->getDocComment(), '@Autowired');

    if ($isAutowired) {
        $type = $property->getType();

        if ($type && $container->hasService($type)) {
            $property->setAccessible(true);
            $property->setValue($service, $container->getService($type));
        } else {
            throw new TypeError('Invalid type for autowired service property');
        }
    }
}
```

> Btw, this code only works for PHP 7.4+

**Comment by derrabus** [comment]
Yes, this feature isn't hard to build. But we have rejected injecting private properties in the past (see the discussion on #34769), so I doubt that it's going to happen this time.

The main problem for me is that you would create classes that cannot be instantiated without a DIC or similar tooling anymore. That is a situation that should be avoided imho.

**Comment by xabbuh** [comment]
> The main problem for me is that you would create classes that cannot be instantiated without a DIC or similar tooling anymore. That is a situation that should be avoided imho.

I agree with this reasoning. Thus 👎  from me for adding this feature.
