### ISSUE TITLE
[DomCrawler] Terrible perfomance filterXpath - new Crawler

### ISSUE THREAD

**Issue by benito103e** [symfony/symfony#39067]
**Symfony version(s) affected**: 3.4 // 4.4

**Description**  
I have terrible performance issue when I follow documentation to parse quiet large XML (3Mo) with nested query.

**How to reproduce**  
```php
$crawler = new Crawler();
$crawler->addXmlContent(file_get_contents(__DIR__.'/rfc1767_33000.xml'));

foreach ($crawler->filterXPath('//transaction') as $nodeTransaction) {
    $crawlerTransaction = new Crawler($nodeTransaction);
    $actionCode = $crawlerTransaction->filterXPath('transaction/documentCommand/documentCommandHeader/@type')->text();
    $transactionId = $crawlerTransaction->filterXPath('transaction/transactionIdentification/entityIdentification')->text();

    foreach ($crawlerTransaction->filterXPath('//catalogue_item_notification:catalogueItemNotification') as $nodeItem) {
        $crawlerItem = new Crawler($nodeItem);
        $documentId = $crawlerItem->filterXPath('//catalogueItemNotificationIdentification/entityIdentification')->text();
        $recipientGln = $crawlerItem->filterXpath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient')->text();
        $highestLevelGtin = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin')->text();
        $targetMarket = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode')->text();
        $documentStatusCode = strtolower($crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/documentStatusCode')->text());

        foreach ($crawlerItem->filterXPath('catalogue_item_notification:catalogueItemNotification//catalogueItem') as $nodeCatalogueItem) {
            $crawlerCatalogueItem = new Crawler($nodeCatalogueItem);
            $gtin = $crawlerCatalogueItem->filterXPath('//catalogueItem/tradeItem/gtin')->text();
            dump($gtin);
        }
    }
}
```
=> Memory used **1.2Go**  **30sec** for execution

Only With Php \Dom
```php
$dom = new \DOMDocument('1.0');
$dom->validateOnParse = true;
@$dom->loadXML(file_get_contents(__DIR__.'/rfc1767_33000.xml'), \LIBXML_NONET);
$xpath = new \DOMXpath($dom);

foreach ($xpath->query('transaction') as $nodeTransaction) {
    $actionCode = $xpath->query('documentCommand/documentCommandHeader/@type', $nodeTransaction)->item(0)->nodeValue;
    $transactionId = $xpath->query('transactionIdentification/entityIdentification', $nodeTransaction)->item(0)->nodeValue;

    /** @var \DOMNode $nodeItem */
    foreach ($xpath->query('.//catalogue_item_notification:catalogueItemNotification', $nodeTransaction) as $nodeItem) {
        $documentId = $xpath->query('//catalogueItemNotificationIdentification/entityIdentification', $nodeItem)->item(0)->nodeValue;
        $recipientGln = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient', $nodeItem)->item(0)->nodeValue;
        $highestLevelGtin = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin', $nodeItem)->item(0)->nodeValue;
        $targetMarket = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode', $nodeItem)->item(0)->nodeValue;
        $documentStatusCode = $xpath->query('//catalogue_item_notification:catalogueItemNotification/documentStatusCode', $nodeItem)->item(0)->nodeValue;

        /** @var \DOMNode $nodeCatalogueItem */
        foreach ($xpath->query('.//catalogueItem', $nodeItem) as $nodeCatalogueItem) {
            $gtin = $xpath->query('tradeItem/gtin', $nodeCatalogueItem)->item(0)->nodeValue;
            dump($gtin);
        }
    }
}
```
=> Memory used **20Mo**, **500ms** for execution

**Possible Solution**  
I don't know where is the memory leak. It seems to be Crawler initializations.

**Additional context**  
Did I miss something when using Crawler ?

Thanks in advance

**Comment by derrabus** [comment]
Can you share an XML file that we can reproduce your problem with?

**Comment by benito103e** [comment]
Hello I generated a sample XML.

[rfc1767_33000.txt](https://github.com/symfony/symfony/files/5535504/rfc1767_33000.txt)

**Comment by simonberger** [comment]
I do not notice any memory leak but it is indeed really slow. Almost 100% of the time is spent on this query: 
```
$domxpath->query(sprintf('(//namespace::*[name()="%s"])[last()]', $this->defaultNamespacePrefix === $prefix ? '' : $prefix));
```
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DomCrawler/Crawler.php#L1254

This seems related #12298

**Comment by stof** [comment]
the issue is related to the fact that this code uses a `foreach` loop getting nodes, and the create a new `Crawler` for that node. As such, it does not benefit from the optimizations we did in the past when creating a subcrawler.
We should probably provide an alternative iteration API giving you subcrawlers rather than nodes directly, for cases where you want to drill-down on each of the nodes separately.

**Comment by benito103e** [comment]
> the issue is related to the fact that this code uses a `foreach` loop getting nodes, and the create a new `Crawler` for that node. As such, it does not benefit from the optimizations we did in the past when creating a subcrawler.
> We should probably provide an alternative iteration API giving you subcrawlers rather than nodes directly, for cases where you want to drill-down on each of the nodes separately.

You're right : Crawler's initialization is really expensive.
I tried a way to get the crawler (built with createSubCrawler) instead of having to rebuild at each node.
=> But it doesn't seem possible

**Comment by stof** [comment]
> But it doesn't seem possible

the current API indeed does not expose an API to get a subcrawler for one of the nodes of the Crawler.

**Comment by simonberger** [comment]
As all the time is running into namespace detection it is possible to bring the time down to 0,1 seconds also with the use of Crawler in its current state. Two `registerNamespace` calls are needed.


```php
$crawler = new \Symfony\Component\DomCrawler\Crawler();
$crawler->addXmlContent(file_get_contents(__DIR__.'/rfc1767_33000.xml'));

foreach ($crawler->filterXPath('//transaction') as $nodeTransaction) {
    $crawlerTransaction = new \Symfony\Component\DomCrawler\Crawler($nodeTransaction);
    $crawlerTransaction->registerNamespace('catalogue_item_notification', 'urn:gs1:gdsn:catalogue_item_notification:xsd:3');

    $actionCode = $crawlerTransaction->filterXPath('transaction/documentCommand/documentCommandHeader/@type')->text();
    $transactionId = $crawlerTransaction->filterXPath('transaction/transactionIdentification/entityIdentification')->text();

    foreach ($crawlerTransaction->filterXPath('//catalogue_item_notification:catalogueItemNotification') as $nodeItem) {
        $crawlerItem = new \Symfony\Component\DomCrawler\Crawler($nodeItem);
        $crawlerItem->registerNamespace('catalogue_item_notification', 'urn:gs1:gdsn:catalogue_item_notification:xsd:3');

        $documentId = $crawlerItem->filterXPath('//catalogueItemNotificationIdentification/entityIdentification')->text();
        $recipientGln = $crawlerItem->filterXpath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient')->text();
        $highestLevelGtin = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin')->text();
        $targetMarket = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode')->text();
        $documentStatusCode = strtolower($crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/documentStatusCode')->text());

        foreach ($crawlerItem->filterXPath('catalogue_item_notification:catalogueItemNotification//catalogueItem') as $nodeCatalogueItem) {
            $crawlerCatalogueItem = new \Symfony\Component\DomCrawler\Crawler($nodeCatalogueItem);

            $gtin = $crawlerCatalogueItem->filterXPath('//catalogueItem/tradeItem/gtin')->text();
            dump($gtin);
        }
    }
}
```

Beside being unable to iterate with sub-crawlers, only manually registered namespaces are copied to sub-crawlers. Therefor registering DOMXPath namespaces in `Crawler::createDOMXPath` needs a cache as well.

**Comment by simonberger** [comment]
I played with several ideas to enhance the crawler and fix this problems.

**Approach 1: Public `createSubCrawler` function (dropped)**
The easiest change would be to cache the discovered namespaces and make `createSubCrawler` public or add a similar function. I didn't really like this though.

**Approach 2: Add an optional `contextNode` parameter to `filterXPath`**
I came up with the API `DOMXPath::query` uses and added an optional contextNode parameter:
`public function filterXPath($xpath/*, \DOMNode $contextNode = null*/)` 

On the example it looks like this:
```php
$crawlerTransactions = $crawler->filterXPath('//transaction');
foreach ($crawlerTransactions as $nodeTransaction) {
    $actionCode = $crawlerTransactions->filterXPath('transaction/documentCommand/documentCommandHeader/@type', $nodeTransaction)->text();
    $transactionId = $crawlerTransactions->filterXPath('transaction/transactionIdentification/entityIdentification', $nodeTransaction)->text();

    $crawlerItem = $crawlerTransactions->filterXPath('//catalogue_item_notification:catalogueItemNotification', $nodeTransaction);
    foreach ($crawlerItem as $nodeItem) {
        $documentId = $crawlerItem->filterXPath('//catalogueItemNotificationIdentification/entityIdentification', $nodeItem)->text();
        $recipientGln = $crawlerItem->filterXpath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient', $nodeItem)->text();
        $highestLevelGtin = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin', $nodeItem)->text();
        $targetMarket = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode', $nodeItem)->text();
        $documentStatusCode = strtolower($crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/documentStatusCode', $nodeItem)->text());

        $crawlerCatalogueItem = $crawlerItem->filterXPath('catalogue_item_notification:catalogueItemNotification//catalogueItem', $nodeItem);
        foreach ($crawlerCatalogueItem as $nodeCatalogueItem) {
            $gtin = $crawlerCatalogueItem->filterXPath('//catalogueItem/tradeItem/gtin', $nodeCatalogueItem)->text();
            dump($gtin);
        }
    }
}
```

It is also possible to use `$crawler` for all queries and the result of `filterXPath` in the foreach directly.

It needs just a few changes internally. Above example is working.
If this is a  preferred change I add a PR.

**Comment by benito103e** [comment]
I think Approach 2 is the good solution, we reuse PHP builtin capabilities.

**Comment by stof** [comment]
I see approach 3: a method giving you an iterator over subcrawlers (which still guarantees that subcrawlers are created only for nodes that belong to the document of this Crawler rather than allowing to pass any node, which would break the invariants of the class, and is the reason why making `createSubCrawler` public was rejected)

> Beside being unable to iterate with sub-crawlers, only manually registered namespaces are copied to sub-crawlers. Therefor registering DOMXPath namespaces in `Crawler::createDOMXPath` needs a cache as well.

this sounds like a bug to me.

**Comment by simonberger** [comment]
> this sounds like a bug to me.

I prepare a PR for this separately. Still having to check if or where a cache could cause any new problems.

> a method giving you an iterator over subcrawlers

Thought of this too but it sounds like a lot of overhead in terms of memory and/or performance overhead in big documents you want to iterate just some sub-notes. I agree that it would be the more comfortable design. In the same time it feels wrong to get a crawler for each and every node.

> ... which would break the invariants of the class, and is the reason why making createSubCrawler public was rejected

True, this argument also applies to approach 2 but the developers could be trusted here imho.

I'll still try how such an iterator would perform.

**Comment by stof** [comment]
> Thought of this too but it sounds like a lot of overhead in terms of memory and/or performance overhead in big documents you want to iterate just some sub-notes. I agree that it would be the more comfortable design. In the same time it feels wrong to get a crawler for each and every node.

Well, if you don't need a separate crawler for each node, then don't use that API but a separate existing API (maybe using `$crawlerTransactions->filterXPath()` directly to find all matching sub-items at once, if your use case can treat them in batch).

But the advantage of exposing a Crawler iterator compared to adding the context node to `filterXPath` would be that you could use any Crawler method on the sub-crawler, not just filtering by XPath.

> True, this argument also applies to approach 2 but the developers could be trusted here imho.

having hidden invariants that must be respected implicitly would imply that we actually don't have such invariant. It is not about trust. If our API allows weird cases, they will be relied upon by someone, and a refactoring breaking such weird cases would become a BC break.
Thus, exposing it won't be simple. We cannot simply forward the argument as is to `DOMXPath::query`, because the Crawler already uses the context argument of `DOMXPath::query` (which is what allowed us to stop copying the whole node tree to a separate crawler to keep crawler nodes at the root of the document)

**Comment by simonberger** [comment]
I tested adding a simple crawler-iterator function like this:

```PHP
public function getSubCrawlerIterator(): \Traversable
{
    return new \ArrayIterator(array_map(function($node) {
        return $this->createSubCrawler($node);
    }, $this->nodes));
}
```

Runtime for the example using this is roughly 4 seconds (down from 9 seconds of the cache fix PR). Why not even faster? The problem is also related to this test script. It uses the prefix just for the second loop which means this isn't cached for all calls from the first loop. But all succeeding `filterXPath` calls including the third loop are using the cache. This isn't fixable with the iterator pattern. It might be a good enough solution though?
I experimented also with returning a new `CrawlerIterator` class (implementing `Iterator`) creating crawler instances dynamically. This works good as well. Not sure if this is worth the extra class.

**Comment by simonberger** [comment]
Here is a demonstration PR in my fork. 
https://github.com/simonberger/symfony/pull/1
Beside the function of the previous comment it adds the optional `$contextNode` parameter to `filterXPath` including an ownerDocument check which should be enough to be acceptable or not?

I know details like signature changes of public functions still need to be changed. Its just up for discussion if this an acceptable API change.

**Comment by stof** [comment]
> Runtime for the example using this is roughly 4 seconds (down from 9 seconds of the cache fix PR). Why not even faster? The problem is also related to this test script. It uses the prefix just for the second loop which means this isn't cached for all calls from the first loop. But all succeeding filterXPath calls including the third loop are using the cache. This isn't fixable with the iterator pattern. It might be a good enough solution though?


A solution for that might be a to an `ArrayObject` for the cache instead of an `array` in #39097. That way, the cache would be shared between all related crawlers (and so a namespace discovered by a subcrawler would be known to all these crawlers)

**Comment by stof** [comment]
> I experimented also with returning a new `CrawlerIterator` class (implementing `Iterator`) creating crawler instances dynamically. This works good as well. Not sure if this is worth the extra class.

or just using a Generator, actually.
