### ISSUE TITLE
Mailgun there is not http-client as dependency

### ISSUE THREAD

**Issue by eerison** [symfony/symfony#39081]
**Symfony version(s) affected**: 4.4.16

**Description**  
[symfony/mailgun-mailer](https://github.com/symfony/mailgun-mailer) need of **symfony/http-client** to work

**Possible Solution**  
Add this dependency in [compose.json](https://github.com/symfony/mailgun-mailer/blob/4.4/composer.json)

**Comment by fabpot** [comment]
It's not requirement if you are using SMTP.

**Comment by derrabus** [comment]
@fabpot Would adding HttpClient to the `"suggest"` block of MailgunMailer and similar packages an option?
