### ISSUE TITLE
Form submission - handleRequest raises exception when editing trying to set null instead of validate data

### ISSUE THREAD

**Issue by sabat24** [symfony/symfony#39106]
**Symfony version(s) affected**: 5.1.5

**Description**  
When I create a new entity and try to send empty `description` field the `new` action works as expected. It passes `handleRquest` and later I get a nice validation message that `description` field can't be empty. When I try the same thing but editing entity the `$form->handleRequest()` raises an exception `"Expected argument of type \"string\", \"null\" given at property path \"description\"."`

It should behave just like when I create new entity. It should pass `handleRequest` and later return me a validation error.

**How to reproduce**  

```php
// controller - create new Activity action
public function new(Request $request)
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);
        if ($form->isSubmitted() && ! $form->isValid()) {
            // return errors
        }
}
```

```php
// controller - edit exisitng Activity action
public function edit(Request $request, Activity $activity)
    {
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);
        if ($form->isSubmitted() && ! $form->isValid()) {
            // return errors
        }
}
```

```php
class Activity
{
/**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
/**
     * @ORM\Column(type="text")
     */
    private $description;
public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
         $metadata->addPropertyConstraint('description', new NotBlank());
     }
}
```

**Possible Solution**  

I know that I can change my setter to allow null values and then it works fine. But I don't think it should be the correct behaviour.

**Comment by JohJohan** [comment]
We use DTO's to transform form data to entity data https://en.wikipedia.org/wiki/Data_transfer_object. That way you can have valid entity meaning you have to pass values via constructor.

**Comment by xabbuh** [comment]
This is the expected behavior. If the user doesn't submit any data or leaves a field empty, `null` is passed by default to the mapped property path (the setter method in your example). In Symfony 5.2 you will be able to define callbacks in the form configuration to handle this yourself: https://symfony.com/blog/new-in-symfony-5-2-form-mapping-callbacks

I am going to close here as there is nothing to fix in Symfony. Thank you for understanding.
