### ISSUE TITLE
[Intl] Countries data issue in Symfony 3.4

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#39103]
It looks like there is something wrong in Intl data with Symfony 3.4 because it is not in sync with Symfony 4.4 & 5.
Maybe a merge issue?

For example:

Symfony 3.4 has `XA` & `XB` countries (`pseudo-accents` & `pseudo-bidi`) which I think is a mistake:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Intl/Resources/data/regions/fr.json#L250-L251

They are not included in Symfony 4.4: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Intl/Resources/data/regions/fr.json
Or 5.X: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Intl/Resources/data/regions/fr.json

**Comment by stof** [comment]
https://github.com/symfony/symfony/pull/31365 was considered a new feature, which is why it was not applied in 3.4
