### ISSUE TITLE
Support for multi-line HTTP headers in HttpFoundation\Response

### ISSUE THREAD

**Issue by drjayvee** [symfony/symfony#39124]
## Problem
`Reponse` currently doesn't support sending multi-line headers.

## Example
For example, [RFC6750](https://tools.ietf.org/html/rfc6750#section-3) (Bearer authentication) requires the following response (in certain situations)
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="example",
                  error="invalid_token",
                  error_description="The access token expired"
```

Developers might intuitively write the following to accomplish this
```php
$response->headers->set(
	'WWW-Authenticate',
	'Bearer realm="example",' . "\r\n" .
	'                 error="invalid_token",' . "\r\n" .
	'                 error_description="The access token expired"'
);
```
This doesn't work, as `header()` will report an error:
```
Header may not contain more than a single header, new line detected
```

One sneaky alternative would be to use
```php
$response->headers->set('WWW-Authenticate', 'Bearer realm="example",');
$response->headers->set('', '                 error="invalid_token",');
$response->headers->set('', '                 error_description="The access token expired"');
```
This doesn't work because `Response` will always print a semicolon after the name, even if it's empty. The result will be
```
WWW-Authenticate: Bearer realm="example",
:                  error="invalid_token",
:                  error_description="The access token expired"
```

### Intuitive usage
To support the intuitive usage, `Reponse::sendHeaders` would have to `preg_split('\r?\n', $value)` (see footnote) and call `header()` multiple times, with only the first call specifying `$name . ': '`.

I'd be glad to provide a PR with this change.

### Sneaky usage
The following diff would support the "sneaky" `set('', $value)` usage
```
diff --git a/src/Symfony/Component/HttpFoundation/Response.php b/src/Symfony/Component/HttpFoundation/Response.php
index df65652456..76a94c7a80 100644
--- a/src/Symfony/Component/HttpFoundation/Response.php
+++ b/src/Symfony/Component/HttpFoundation/Response.php
@@ -356,7 +356,7 @@ class Response
         foreach ($this->headers->allPreserveCaseWithoutCookies() as $name => $values) {
             $replace = 0 === strcasecmp($name, 'Content-Type');
             foreach ($values as $value) {
-                header($name.': '.$value, $replace, $this->statusCode);
+                header(($name ? "$name: " : '').$value, $replace, $this->statusCode);
             }
         }

```

## Testing
Testing this is hard, because `header()` can't be mocked.

**Footnote:** The spec requires CRLF (`\r\n`) to separate lines, but many implementations only provide LF (`\n`).

**Comment by drjayvee** [comment]
Then again, if I understand [RFC2616](https://tools.ietf.org/html/rfc2616#section-4.2) (HTTP/1.1) correctly, multiline headers are possible but optional:

> Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT.

> Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma. The order in which header fields with the same
   field-name are received is therefore significant to the
   interpretation of the combined field value, and thus a proxy MUST NOT
   change the order of these field values when a message is forwarded.

**Comment by derrabus** [comment]
If `header()` does not support multi-line, I'm not really sure if we should. Is there anything I cannot do if I don't have multi-line headers available?

**Comment by drjayvee** [comment]
I'm not sure if
```
Name: k1=v1,k2=v2
```
if semantically equivalent to
```
Name: k1=v1,
 k2=v2
```

If it is, then this is a non-issue I guess.

**Comment by stof** [comment]
My understanding of the spec (which refers to the RFC2617 about `Authentication`) is that the `WWW-Authenticate` value is a comma-separated list. As such, newlines are not significant in it.

**Comment by fabpot** [comment]
You should do it on one line, no need to use newlines in such a header.
