### ISSUE TITLE
Async message handler failing on entity persist does not show a helpful error message

### ISSUE THREAD

**Issue by BurningDog** [symfony/symfony#39125]
**Symfony version(s) affected**: 4.4.15 to latest 5.x

**Description**  
When handling a message to be handled by the async transport which is using the Doctrine Transport, if that message passes a Doctrine entity and the handler needs to persist that entity, the following error occurs:

`Symfony\Component\Messenger\Exception\HandlerFailedException: Notice: Undefined index: 0000000034bc49bc0000000006123554`

This error message is confusing (and requires understanding Doctrine's internal implementation to understand what it means). The issue is that since the entity is going to be persisted, it needs to be loaded from the database first, otherwise Doctrine thinks it's a new entity and attempts to save it, except it has no internal record of it which results in that rather unhelpful error message.

The documentation at https://symfony.com/doc/current/messenger.html#doctrine-entities-in-messages _prefers_ that the entity's primary key is passed rather than the object, but doesn't say that this is the *only* approach which will work if you need to persist the entity in the message handler.

**How to reproduce**  

A message which returns the User object instead of the user ID:

```php
// src/Message/UpdateUserEvent.php
namespace App\Message;

use App\Entity\User;

class UpdateUserEvent
{
    private User $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function getUser(): User
    {
        return $this->user;
    }
}
```

A message handler which changes something on the user object and tries to save it:

```php
// src/MessageHandler/NewUserWelcomeEmailHandler.php
namespace App\MessageHandler;

use App\Message\UpdateUserEvent;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class NewUserWelcomeEmailHandler implements MessageHandlerInterface
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function __invoke(UpdateUserEvent $updateUserEvent)
    {
        $user = $updateUserEvent->getUser();
        $timesUpdated = $user->getTimesUpdated();
        $user->setTimesUpdated($timesUpdated++);

        $this->entityManager->persist($user);
        $this->entityManager->flush(); // <- the error occurs here, but only when using an async transport handler
    }
}
```

**Possible Solution**  

Append the documentation at https://symfony.com/doc/current/messenger.html#doctrine-entities-in-messages in order to say:
> If you need to persist the entity in your handler, then you must load the object first (from the Entity Manager or a Repository), otherwise Doctrine doesn't know about it and the persist won't work.

The other solution is to show a useful error message to the developer:
> Ensure you are re-loading the entity from the database rather than passing the object. See https://symfony.com/doc/current/messenger.html#doctrine-entities-in-messages

In order to accomplish the latter, I suggest the following:

```diff
diff --git a/src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php b/src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php
index eaf6b95..cff1b65 100644
--- a/src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php
+++ b/src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php
@@ -63,9 +63,13 @@ class HandleMessageMiddleware implements MiddlewareInterface
                 $handledStamp = HandledStamp::fromDescriptor($handlerDescriptor, $handler($message));
                 $envelope = $envelope->with($handledStamp);
                 $this->logger->info('Message {class} handled by {handler}', $context + ['handler' => $handledStamp->getHandlerName()]);
-            } catch (\Throwable $e) {
+            } catch (\ErrorException $e) {
+                if (stristr($e->getMessage(), 'Notice: Undefined index: 00000000')) {
+                    $newException = new \ErrorException('Ensure you are re-loading the entity from the database rather than passing the object. See https://symfony.com/doc/current/messenger.html#doctrine-entities-in-messages');
+                    $exceptions[] = $newException;
+                }
                 $exceptions[] = $e;
-            }
+            } catch (\Throwable $e) {
         }

         if (null === $handler) {
```

**Additional context**  

When running the doctrine async queue handler with `php bin/console messenger:consume async --limit=10` the error looks like:

```
12:34:41 ERROR     [messenger] Error thrown while handling message App\Message\Event\MyCustomEvent. Sending for retry #1 using 1000 ms delay. Error: "Notice: Undefined index: 0000000034bc49bc0000000006123554" ["message" => App\Message\Event\MyCustomEvent^ { …},"class" => "App\Message\Event\MyCustomEvent","retryCount" => 1,"delay" => 1000,"error" => "Notice: Undefined index: 0000000034bc49bc0000000006123554","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
```

The first bit of the stack trace:

```
#0 vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(692): Doctrine\ORM\UnitOfWork->getEntityIdentifier(Object(Proxies\__CG__\App\Entity\User))
#1 vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(730): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->prepareUpdateData(Object(App\Entity\HubspotContact))
#2 vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(277): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->prepareInsertData(Object(App\Entity\HubspotContact))
#3 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1088): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(401): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(371): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 src/MessageHandler/Event/ContactUpdatedAndSendToHubspot.php(48): Doctrine\ORM\EntityManager->flush()
#7 vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(63): App\MessageHandler\Event\ContactUpdatedAndSendToHubspot->__invoke(Object(App\Message\Event\MyCustomEvent))
#8 vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(79): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->handle(Object(
```

**Comment by noniagriconomie** [comment]
Arent you suppose to persist/flush first in your controller/service 
Then pass a user id/uuid into your message and dispatch it
And in your handler retreive the full user from its identifier
To finally do things on it/persist/flush in the handler?

Or alternativly, pass via the message all the bare data to instanciate a new user in the handler directly, then do things on it/persist/flush

**Comment by BurningDog** [comment]
re: your first paragraph: yes, you're correct. However, if you don't do that, the persist works in the handler *only if* it's handled synchronously. But switching to an async handler fails, with a non-meaningful error message.

The current messenger documentation doesn't make that clear, and the error message means having to understand Doctrine's internals to work out why the persist failed (specifically, `Doctrine\ORM\UnitOfWork->getEntityIdentifier()`).

**Comment by noniagriconomie** [comment]
Ho i see your point know
For my part i only use messenger like said before, thus never faced this

Maybe it is worth an update on the documentation side as well ?

**Comment by BurningDog** [comment]
Yes, I think the documentation update makes sense.

Is the change I've proposed to `HandleMessageMiddleware.php` worthy of a PR?

**Comment by noniagriconomie** [comment]
I do not know :s @BurningDog 
from my side, i really do not think this usage is legit for async, i mean it is an other process, thus obviously the doctrine logic will fail: message must be as stateless as possible to be "reloaded" from the other process :)

I would recommand first you open a PR on the doc side, so that ppl are aware of this and discuss if it is good to PR this file to handle such case

**Comment by BurningDog** [comment]
> thus obviously the doctrine logic will fail

Yes, agreed - but if you *don't* already know that (I didn't, oops), then both documentation and the error message should be clear.

I'll open a PR on the doc side, and discuss there if my suggested change here is useful.

**Comment by camilledejoye** [comment]
Hi,
I didn't find any related PR on https://github.com/symfony/symfony-doc so I will respond here.

For me the error you got is totally unrelated to the messenger component and Symfony.
The unclear message originate from Doctrine, so there is not much that can be done here.
You can always try to propose an improvement on their [repository](https://github.com/doctrine/orm).

If you really want to change the message on your project to avoid confusion the next time, it might be better to create a dedicated middleware.
This way you can configure it to be only added in the development environment and you have a dedicated service for a specific purpose.

> but doesn't say that this is the only approach which will work

This is not true, you can put your entity directly into your message.
Your handler will work, if you load the entity first.
In case of a synchronous message, as long as you fetch your entity using its identifier you don't have to worry about performance issue: the identity map will gave you the object already stored in memory.
In case of an asynchronous message, if you want to avoid loading the entity you can use [Reference Proxies](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/advanced-configuration.html#reference-proxies).

But as you can see you'll always end-up using a different object than the one you got from your message.
That's why the doc suggest to not include the all entity, it's simply a best practice to avoid those kinds of error.

About the idea of updating the documentation I guess you'll have to create an issue and wait for a feedback.

**Comment by chalasr** [comment]
I'm closing here as everything has been said, the suggested patch is too specific for being part of the Messenger component.
Feel free to checkout our [support platforms](https://symfony.com/support) if you need advices regarding your usage of the component, or to open an issue/PR on https://github.com/symfony/symfony-docs  if you think something can be improved there.
Thanks
