### ISSUE TITLE
[Form] single_text DateTimeType widget does not support non-default, 24H format

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#39136]
**Symfony version(s) affected**: 4.4.16

**Description**  
If you use single_text with DateTimeType and specify custom format, this does not work when you use 24h clock format when submitting time > 12h, as Form component is unable to transform this date.

**How to reproduce**  

```php
$form = $this->factory->create(static::TESTED_TYPE, null, [
    'input' => 'string',
    'widget' => 'single_text',
    'format' => 'dd/MM/yyyy hh:mm',
]);

$form->submit('21/11/2020 16:00');

$this->assertEquals('2020-11-21 16:00:00', $form->getData());
```

**Possible Solution**  
Don't disable lenient processing here https://github.com/symfony/symfony/blob/4d6a02a0e186b9afc8e2f31ab736e45a01a538be/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L182-L182

**Additional context**  
Issue is in `DateTimeToLocalizedStringTransformer` which does following and it doesn't work for this case: https://3v4l.org/Q7jL8

**Comment by xabbuh** [comment]
Shouldn't you use `HH` instead of `hh` for the hour in your format string?

**Comment by ostrolucky** [comment]
Indeed. It works with HH. Thx
