### ISSUE TITLE
empty_data option is ignored on HiddenType

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#39148]
Hi!

**Symfony version(s) affected**: 5.1.8, 5.2.0-RC2

**Description**  
empty_data option is ignored on HiddenType formtype

**How to reproduce**  
```php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class DemoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('text', TextType::class, ['required' => false, 'empty_data' => ''])
            ->add('hidden', HiddenType::class, ['empty_data' => ''])
            ->add('submit', SubmitType::class);
    }
}

<?php

namespace App\Controller;

use App\Form\DemoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DemoController extends AbstractController
{
    /**
     * @Route("/demo")
     */
    public function demo(Request $request): Response
    {
        $form = $this->createForm(DemoType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            dump($form->getData());
        }

        return $this->render('demo.html.twig', ['form' => $form->createView()]);
    }
}
```

dumps:
```
array:2 [▼
  "text" => ""
  "hidden" => null
]
```

**Comment by mmarton** [comment]
Tested with 5.2.0-RC2 with the same result

**Comment by xabbuh** [comment]
This is expected. The empty string will be transformed to `null` by the Form component (see also https://symfony.com/doc/current/reference/forms/types/form.html#empty-data). The `TextType` has some special hard coded data transformation that you would need to apply to your `HiddenType` too if you want to achieve the same behavior: https://github.com/symfony/symfony/blob/49eafee03323253328d76ec9cb4c515f94d2f202/src/Symfony/Component/Form/Extension/Core/Type/TextType.php#L54-L66 I am going to close here as there is nothing to fix. Thank you for understanding.

**Comment by mmarton** [comment]
@xabbuh Could you please explain why is this expected? What's the difference between text and other input types regarding this behavior?
the file you linked has a comment in the buildForm method:

> // When empty_data is explicitly set to an empty string,
// a string should always be returned when NULL is submitted
// This gives more control and thus helps preventing some issues
// with PHP 7 which allows type hinting strings in functions
// See https://github.com/symfony/symfony/issues/5906#issuecomment-203189375

that's the exact problem I have. With php7.4 I have a not nullable typed property mapped to an entity and getting "InvalidArgumentException: Expected argument of type "string", "null" given at property path"

**Comment by xabbuh** [comment]
The difference is that the `TextType` is the only type having this behavior implemented with a custom data transformer. We could debate if adding this to some more selected types may be an option. But currently that's how things work.

**Comment by pbowyer** [comment]
This inconsistency frustrated me today when I changed a `TextType` to a `HiddenType` (as a JS widget is now used to create the input's content) - and my app promptly broke, because `''` is expected not `null` when an empty value is submitted.

It would be very helpful to get consistency on this, either by removing the special case in `TextType` and having it as a generalised behaviour, or by adding it to other text-like fields.

**Comment by yapro** [comment]
The same problem!
