### ISSUE TITLE
[Uuid] Regression with Doctrine

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#39152]
**Symfony version(s) affected**: 5.2.0-RC2  

**Description**  
Regression from 5.2.0-RC1 on Uuid and Doctrine

**How to reproduce**  

name     : symfony/uid
versions : * v5.2.0-RC2
name     : doctrine/doctrine-bundle
versions : * 2.2.1

Previous code ok:

```php
$uuid = Uuid::fromString($request->query->get('humidor_uid'));
$humidor = $humidorRepository->findOneByUuid($uuid);
```

Actual same code returns `null`

**Possible Solution**  
.

**Additional context**  
It appears also that, the generation and the persistence is broken
Maybe related on changes here: https://github.com/symfony/symfony/compare/v5.2.0-RC1...v5.2.0-RC2

See previous issue at https://github.com/symfony/symfony/issues/38929
Maybe related also to https://github.com/symfony/symfony/issues/39144

Thank you

**Comment by jderusse** [comment]
Hello @94noni 
The format of `UUID` and `ULID` changed between `5.2-RC1` and `5.2-RC2`. Items that have been persisted while you are running `RC1` are not compatible with query sent with `RC2`.


```diff
 $ show create table my_table;
 ...
-# symfony 5.2-RC1
-`my_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:ulid)',

+ # symfony 5.2-RC2
+`my_id` binary(16) NOT NULL COMMENT '(DC2Type:ulid)',
 ...
```

Could you please check the content of the table and assert the table contains binary fileds like:
```sql
mysql> select * from my_table;
+------------------------------------+------+
| my_id                              | name |
+------------------------------------+------+
| 0x0175FC41B374F72A3B65BD44884DFFDB | demo |
+------------------------------------+------+
1 row in set (0.00 sec)
```

If you are still using `char(36)`, you should perform a migration: change the type of the column and change the value of the data inside.

**Comment by 94noni** [comment]
@jderusse thank you for this explanation, will try it very soon and report back (and close the issue if it is ok)

**Comment by 94noni** [comment]
@jderusse 

yes indeed, they are represented like this in database `char(36)` with value like `9df9ec44-ac4b-4f8d-ae3c-673f1888734c`

when adding a new prop and regenerating a migration, the SQL migration looks like:
```
ALTER TABLE user ADD uuid2 BINARY(16) NOT NULL COMMENT '(DC2Type:uuid)';
```

I will then drop those column and recreate them, repopulating the data :)
But i also sometimes insert inside those table via the UUID sql function, will try to find how to swap also

thank you!

**Comment by stof** [comment]
@94noni if you use MySQL 8 (or newer), you can use the `UUID_TO_BIN` function if you need to convert a RFC4122 string (such as the one returned by MySQL's `UUID` function) into the binary representation in SQL.

**Comment by 94noni** [comment]
@stof yes i've read that but now i am on 5.7
I plan to upgrade soon :) thx
