### ISSUE TITLE
Guard authenticator called on url protected by IS_AUTHENTICATED_ANONYMOUSLY

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#39161]
Hi,

```
security:
    role_hierarchy:
        ROLE_ADMIN:           [ ROLE_USER ]

    providers: ...

    access_control:
        - { path: ^/foo, roles: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        main:
            pattern: ^/
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\CasAuthenticator

```

On url /bar my CasAuthenticator::support() was called even if this url doesn't require a fully auth.
Is it normal ? Is there a easy way to know if my route is only protected by IS_AUTHENTICATED_ANONYMOUSLY role ? I see nothing about that on documentation.

**EDIT**
symfony/framework-bundle : 4.4.15
symfony/security-bundle : 4.4.15

**Comment by derrabus** [comment]
Yes, this is intended behavior. Authentication and authorization are handled separately. You can be authenticated although you don't need to be.

**Comment by acantepie** [comment]
You don't give any solution to check if my route is only protected by IS_AUTHENTICATED_ANONYMOUSLY on CasAuthenticator::support() method (and there is no exemple on documentation).

**Comment by derrabus** [comment]
This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
