### ISSUE TITLE
Command make:migration is blocked by not asked question

### ISSUE THREAD

**Issue by pink6440** [symfony/symfony#39169]
**Symfony version(s) affected**: 5.1 (php 7.4)

**Description**  
For an (for now) unknown reason, the migration table with versions info disappears from my database.
Later, **i try to run the make:migration command**, then, it looks like blocked.

**When i remove all file from the migrations folder, it works fine.**
But **then, when i re run the command again, it it stucked again**.

For debug, i use directly the "doctrine:migration:diff" commande and the behaviour is the same.

I'm sorry to not give a full context for reproduce it but i am actually on a deadline so i miss some time.

**How to reproduce**  
Create a project with some entity and execute the make:migration
Do not execute the migration
Re run the commande make:migration

**Possible Solution**  
On the DiffCommand.php, on method **checkNewMigrationsOrExecutedUnavailable**, if i force to return true, it works again.

**It does not show the message** " [WARNING] You have 1 available migrations to execute" and most important, **it does not show the "Are you sure you wish to continue?'" question**.

My guess is that this question is the stucked point.

And it does not take care of the --no-interaction option when i try to use it.

**Additional context**

**Comment by stof** [comment]
Neither `doctrine:migration:diff` nor `make:migration` are part of Symfony itself. The first one belongs to the doctrine/migrations package and the second one belongs to MakerBundle. So this is the wrong issue tracker to report it.
