### ISSUE TITLE
[String] AsciiSlugger's symbolsMap should apply to all locales for a language

### ISSUE THREAD

**Issue by jontjs** [symfony/symfony#39178]
**Description**  
Make the AsciiSlugger's symbolsMap apply to all locales for a given language.

**Example**  
When using the AsciiSlugger under the 'en_GB' locale, it doesn't change '&' to 'and', it removes it. However it does do this if your locale is 'en'.

**Proposed approach**  
If the current locale is not explicitly in the symbolsMap, explode the locale string on underscores and apply the symbolsMap for the first part. E.g. for a locale of 'en_GB', it would use the 'en' symbolsMap.

**Comment by nicolas-grekas** [comment]
Nice idea, would you like sending a PR to implement this behavior?
