### ISSUE TITLE
Functionnal test don't assertEmailCount with sync:// transport.

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#39171]
**Symfony version(s) affected**: 4.4.16

**Description**
Functionnal test don't assert email or transport with messenger component.

I try to test (functionnal) email is send with messenger component.

submit form -> Commandbus handler $command -> generate event -> event handler send mail.

Works perfectly but on functionnal test i don't have expected behaviour.

**How to reproduce**  
I create simple project to reproduce and explain expected in the README.MD
https://github.com/thewalkingcoder/messenger

**Comment by stof** [comment]
does this work if you remove `->followRedirects()` in your functional tests ? The page loaded after the redirection has indeed not sent any email.

**Comment by thewalkingcoder** [comment]
thanks @stof if i remove `->followRedirects()` tests successfully.

but why `->followRedirects()` impact behaviour, we are in a the same page after submit

```php
public function index(Request $request): Response
    {
        $command = new CreatePostCommand();
        $form = $this->createForm(PostType::class, $command);

        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {
            $this->commandBus->dispatch($command);
        }

        return $this->render(
            'app/index.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }
```
