### ISSUE TITLE
[Cache] The namespace keys is "APP_DEBUG dependent"

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#39175]
**Symfony version(s) affected**: 5.1.2

**How to reproduce**  

```
$ APP_DEBUG=0 bin/console cache:pool:clear cache.app 
// "SCAN" "0" "COUNT" "1000" "MATCH" "wu1MerR6oe:*" (redis-cli monitor)

$ APP_DEBUG=1 bin/console cache:pool:clear cache.app
// "SCAN" "0" "COUNT" "1000" "MATCH" "nonmBNxiVY:*" (redis-cli monitor)
```

**Possible Solution**  

We can see below that the namespace keys is generated from the class name of the cache adapter.

https://github.com/symfony/symfony/blob/49eafee03323253328d76ec9cb4c515f94d2f202/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L90-L97

In the CacheCollectorPass, this class can be decorated by a TraceableAdapter in debug mode. Once decoracted, the namespace changes.

https://github.com/symfony/symfony/blob/49eafee03323253328d76ec9cb4c515f94d2f202/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L164-L168

**Comment by linaori** [comment]
I can indeed confirm this behavior. I ran into this issue where a web request would start a process, and due to a misconfigured env var in the `console`, never received the correct setting. This also goes for prod vs dev. Imo the cache key should be the same, regardless of the symfony mode or debug.

**Comment by nicolas-grekas** [comment]
Can you please check if it could be related to #35890?

**Comment by maidmaid** [comment]
https://github.com/symfony/symfony/pull/35890 fixes the prefix keys with the APP_ENV dependency but it doesn't seem enough because there is also a dependency on the APP_DEBUG as explained here.

**Comment by nicolas-grekas** [comment]
> In the CacheCollectorPass, this class can be decorated by a TraceableAdapter in debug mode. Once decoracted, the namespace changes.

This surprised me so I checked in the code and I cannot spot where this behavior could be implemented.
To me, the namespace does not depend on whether the pool is decorated or not. Please provide details of your claim here.

About namespaces being different in debug/non-debug, that's expected, at least by default.

If you want to change this, you can in 5.2, by defining the `cache.prefix.seed` parameter, thanks to #35890

**Comment by maidmaid** [comment]
Indeed, the decorator isn't related, it's the kernel name containing the word debug. #35890 solves this.
