### ISSUE TITLE
Cannot access protected property Symfony\Component\Uid\UuidV4::$uid

### ISSUE THREAD

**Issue by chindit** [symfony/symfony#39186]
**Symfony version(s) affected**: 5.2.0-RC2

**Description**  
When trying to register a user with UUID as main ID, this issue occurs

**How to reproduce**  
Create a basic project, add maker bundle and all required bundles to make «make:registration» works and use the form.
Connect user to a simple User entity.
User have this type of ID:
```
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidV4Generator::class)
     */
    private string $id;
```

**Possible Solution**  
Make the property public

**Additional context**  
If needed, full project is here: https://github.com/chindit/url-shortener
Checkout, composer & yarn install and go to /register should reproduce the issue.

**Comment by jderusse** [comment]
Could you please provide a call stack?. i'm not able to reproduce the bug with the project you share.

**Comment by chindit** [comment]
Sure.

Here is the full cal stack:
```
Error:
Cannot access protected property Symfony\Component\Uid\UuidV4::$uid

  at C:\Users\littl\Documents\url-shortener\vendor\symfony\uid\AbstractUid.php:105
  at Symfony\Component\Uid\AbstractUid->__toString()
  at ReflectionProperty->setValue(object(User), object(UuidV4))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\persistence\lib\Doctrine\Persistence\Reflection\TypedNoDefaultReflectionProperty.php:46)
  at Doctrine\Persistence\Reflection\TypedNoDefaultReflectionProperty->setValue(object(User), object(UuidV4))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataInfo.php:762)
  at Doctrine\ORM\Mapping\ClassMetadataInfo->setIdentifierValues(object(User), array('id' => object(UuidV4)))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:955)
  at Doctrine\ORM\UnitOfWork->persistNew(object(ClassMetadata), object(User))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:1781)
  at Doctrine\ORM\UnitOfWork->doPersist(object(User), array('000000003d83e035000000005a3547fb' => object(User)))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:1737)
  at Doctrine\ORM\UnitOfWork->persist(object(User))
     (C:\Users\littl\Documents\url-shortener\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:610)
  at Doctrine\ORM\EntityManager->persist(object(User))
     (C:\Users\littl\Documents\url-shortener\src\Controller\RegistrationController.php:36)
  at App\Controller\RegistrationController->register(object(Request), object(UserPasswordEncoder), object(GuardAuthenticatorHandler), object(LoginAuthenticator))
     (C:\Users\littl\Documents\url-shortener\vendor\symfony\http-kernel\HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (C:\Users\littl\Documents\url-shortener\vendor\symfony\http-kernel\HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (C:\Users\littl\Documents\url-shortener\vendor\symfony\http-kernel\Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (C:\Users\littl\Documents\url-shortener\public\index.php:28)
```

If useful, I'm on Windows, with PHP 7.4.1 and running `symfony serve` (last version)

**Comment by stof** [comment]
Something looks broken there. The `$uid` property is defined as protected in `AbstractUid`, not in `UuidV4`.

**Comment by nicolas-grekas** [comment]
Php 7.4.1 is old, please upgrade and report back if the issue persists.

**Comment by chindit** [comment]
Tested with PHP 8.0.0 and it's working.
Should be re-tested with PHP 7.4.X and maybe put an incompatibility in `composer.json`

**Comment by jderusse** [comment]
regarding the stack trace, I believe this is an issue in PHP 7.4.1: `AbstractUid::__toString` is allowed to read `UuidV4::$uid` as it's defined in `AbstractUid` class.
I tested with the latest version of 7.4 and didn't have issue with your repo.

Thanks for your help.

**Comment by axelbest** [comment]
I have the same issue. 
`Cannot access protected property Symfony\Component\Uid\UuidV4::$uid`
I put my configs below, but the weird thing is that it's working on windows but not working on linux, same project, some minor differences but i'll describe them below:

Common things:
server -> symfony serve -d
same project,
same composer version

Windows (10 PRO 21H1):
PHP 7.4.19
Database: mariaDB locally hosted

Linux (Ubuntu 20.04 LTS):
PHP 7.4.3
Database: mySQL hosted on NAS over LAN

I'll make some research today about it, because I think it might be related to the extensions which were loaded in PHP.

**Comment by YaFou** [comment]
As mentioned earlier, @axelbest you have to upgrade your PHP version to PHP 7.4.19 on Linux. See [this comment](https://github.com/symfony/symfony/issues/39186#issuecomment-734705630).

**Comment by axelbest** [comment]
@YaFou yeah, that's the easiest solution, but as I made some investigation - i found out that php on my linux machine is non-thread safe, and php on windows is thread safe. While debugging i've encountered the same error as in here
https://github.com/symfony/symfony/issues/21048
