### ISSUE TITLE
[String] trimEnd swallows additional character

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#39181]
**Symfony version(s) affected**: 5.2-RC2

**Description**  
We experienced an issue with the `trimEnd` method: it removed one additional character.

**How to reproduce**  
```php
        $result = s('ThemeModule')->trimEnd('Module')->toString();
        if ('Module' !== $result) {
            throw new \Exception('Ooops: ' . $result);
        }
```

**Comment by derrabus** [comment]
Confirmed on 5.1 and 5.2.

**Comment by derrabus** [comment]
```php
dump(dump(dump(s('ThemeModule'))->trimEnd('Module'))->toString());
```

![Bildschirmfoto 2020-11-26 um 16 33 32](https://user-images.githubusercontent.com/1506493/100369426-29409480-3005-11eb-93cd-9a7adfb2e182.png)

**Comment by nicolas-grekas** [comment]
That's expected, you're looking for `beforeLast()` maybe?
trim expects a list of chars to trim, not words.

**Comment by Guite** [comment]
Thanks for elaborating @nicolas-grekas

**Comment by derrabus** [comment]
Oh right. 😓
