### ISSUE TITLE
web profiler 404 on some mailer_url parameters

### ISSUE THREAD

**Issue by mote0230** [symfony/symfony#39185]
**Symfony version(s) affected**: 5.1.8

**Description**  
When inserting the swiftmailer service in a controller method, when the mailer_url in the .env file has certain parameters, the web profiler will return 404

**How to reproduce**  
In a controller method, add the mailer service \Swift_Mailer $mailer
in .env.local , add MAILER_URL=smtp://foobarserver:587?transport=smtp&username=foo&password=bar&encryption=null
Not sure how relevant, but trying to connect to an exchange 2010 server
Visit the page of the controller method and try to find the web profiler

**Possible Solution**  
changing encryption to ssl, or removing the encryption part works. Changing to tls doesn't work. 

**Additional context** 
I was converting my symfony4 mailer config of parameter file with only mailer_transport, mailer_host, mailer_user, and mailer_password to what i found for symfony5 in https://symfony.com/doc/current/email.html#configuration . I tried to stay close to the example by changing the port, and then playing with other variables to see what works, but encountered above problem. The https://symfony.com/doc/current/reference/configuration/swiftmailer.html reference doesn't provide the default values. At first i tried to delete the cache, restart php services, check if mail spoolers where running. Later I looked in the reference for just the values that worked in the old config, and with that email flowed again.

**Comment by derrabus** [comment]
Can you provide a reproducer for this problem?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by mote0230** [comment]
I've run into this problem again on another project, which doesn't use flex yet so I have to twiddle with the parameters in a config file.
After setting the timeout to 3seconds (default 30) I could see the debug toolbar pop up after a couple 404 requests. 

So this seems to be the root cause of the problem, the debug toolbar is waiting on the swiftmailer to timeout. Maybe a solution for this would be to lazily load this info.
