### ISSUE TITLE
[Cache] The namespace keys never changes even if prefix_seed is dynamic

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#39201]
**Symfony version(s) affected**: 5.1.2

**Description**  
If the `prefix_seed` config is dynamic and built from an env variable, the redis calls are wrong, using a wrong namespace keys. That's because the namespace is generated at the container compilation and so it will never changes.

https://github.com/symfony/symfony/blob/49eafee03323253328d76ec9cb4c515f94d2f202/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L144

**How to reproduce**  

```yml
framework:
    cache:
        prefix_seed: "myapp_%env(MYAPP_CLIENT)%"
```

```
$ MYAPP_CLIENT=client1 bin/console cache:pool:clear cache.app 
// "SCAN" "0" "COUNT" "1000" "MATCH" "wu1MerR6oe:*" (redis-cli monitor)

$ MYAPP_CLIENT=client2 bin/console cache:pool:clear cache.app
// "SCAN" "0" "COUNT" "1000" "MATCH" "wu1MerR6oe:*" (redis-cli monitor)
```

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
Yes, that's a feature :)
Cache namespaces must be static, because they have to be known at warmup time.

**Comment by maidmaid** [comment]
In my use case, the Symfony codebase is used by different clients from one request to another and I need to prefix keys by the client name to avoid collisions. I understand that `cache.system` needs to be static but `cache.app` could stay dynamic.

We can imagine a concatenation between a dynamic prefix_cache and a static hash:


```diff
- hash of "cache.app.my_prefix_seed.App_KernelProdContainer.Symfony\Component\Cache\Adapter\RedisAdapter"
+ my_prefix_seed + hash of "cache.app.App_KernelProdContainer.Symfony\Component\Cache\Adapter\RedisAdapter"
```

**Comment by nicolas-grekas** [comment]
I think you should be able to achieve this with a compiler pass, adding a prefix to the generated namespace.

**Comment by maidmaid** [comment]
Yes, it's what I did. Would you be interested by a PR separating `prefix_seed` from the static hash ?

**Comment by nicolas-grekas** [comment]
This looks quite specific to me, not sure it should be part of core.
