### ISSUE TITLE
Slack notifier SlackTransport doesn't parse Slack DSN correctly

### ISSUE THREAD

**Issue by r-ichard** [symfony/symfony#39204]
**Symfony version(s) affected**: 5.1.*

**Description**  
When I set my webhook url as DSN like this : 

`SLACK_DSN=slack://hooks.slack.com/services/xxxxx/xxxxx/xxxxx`

Slack notification doesn't work as the post URL in SlackTransport.php becomes: 

https://hooks.slack.com/services/services/xxxxx/xxxxx/xxxxx

A confusing exception is thrown as Slack responds with HTTP 200 and the content of the https://api.slack.com page.
"Unable to post the Slack message: <!DOCTYPE html><html lang="en-US" class="">..." 

**How to reproduce**  
- Install symfony/slack-notifier
- Set Slack DSN as (no https unless an other error will trigger)  : 
`SLACK_DSN=slack://hooks.slack.com/services/YOUR/CUSTOM/WEBHOOK-URL`
- Try to send a Slack notification. 

**Possible Solution**  

The only way to make it work is to remove "/services" from the webhook URL in DSN  as: 

 `SLACK_DSN=slack://hooks.slack.com/xxxxx/xxxxx/xxxxx`

Another solution would be to fix symfony/slack-notifier by modifying SlackTransport.php: 

```
        $response = $this->client->request('POST', sprintf('https://%s/services/%s', $this->getEndpoint(), $id), [
            'json' => array_filter($options),
        ]);
```
to 
```
        $response = $this->client->request('POST', sprintf('https://%s/%s', $this->getEndpoint(), $id), [
            'json' => array_filter($options),
        ]);
```

**Additional information**   
The main issue is that the correct syntax for Slack DSN with webhook is unclear in the documentation. 
I had to guess the syntax by myself. Maybe this issue just requires a documentation update.

**Comment by evertharmeling** [comment]
For **Symfony 5.1.*** I'm using the following DSN syntax (which works):
`slack://default/xxxxx/xxxxx/xxxxx`

For **Symfony 5.2.*** this syntax doesn't seem valid anymore (got an Exception when I just updated). I need to investigate if this legitimate or that the '5.1' syntax should be kept supported... (or maybe someone knows :))

Fix for me for now is to stick to **5.1.***.

**Comment by fabpot** [comment]
The DSN changed between 5.1 and 5.2 (component is still experimental).

**Comment by derrabus** [comment]
If this is a common pitfall: Can we detect the old DSN syntax and throw a helpful exception?

**Comment by vntw** [comment]
If somebody stumbles over this as well, what's working for me with a single channel in 5.2 is

```
SLACK_DSN=slack://{Bot User OAuth Access Token}@default?channel={Channel ID}

// e.g. SLACK_DSN=slack://xoxb-12345-12345-L12345@default?channel=G12345
```

**Comment by fabpot** [comment]
I agree that having a proper exception would be great. Anyone willing to work on that for 5.2?

**Comment by malteschlueter** [comment]
I tried my luck to add a the exception.

WDYT?
