### ISSUE TITLE
Voters - different behavior on dev/test and production enviroment

### ISSUE THREAD

**Issue by adeptofvoltron** [symfony/symfony#39205]
**Symfony version(s) affected**: tested on 5.0.10  (but from what I see in a code, 

**Description**  

Basically each voter in dev/test env is wrapped in `\Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter` proxy.  In [that commit](https://github.com/symfony/symfony/commit/65d942010c25914ff32f2514649f9bfcec5f644e) @nicolas-grekas added return type `int`. Because there is no "strict types" in file...all return results are type juggled to int. 
In prod env, there is no such proxy so the result is not juggled into an int.

Voter Result is used in \Symfony\Component\Security\Core\Authorization\AccessDecisionManager where it is strictly compared.

**How to reproduce**  

There are several possible solutions, and I would be happy to implement it. However, I do not know properly the "Symfony way" to contribute. So I am going to be more than happy by pointing to the correct solution: 

- Option nr . 1 Use strict types in TraceableVoter -> It will throw an error if someone's voter will return different type than boolean.
       disadventages: backward-incompatible, some projects may not handle such error + I did not see using strict_types in Symfony(surprised tbh).

- Option nr . 2 Cast return from Voter in AccessDecisionManager into "int". I think it is an ugly version, but most likely to be correct here

- Option nr. 3 remove return type declaration from vote method (after allis cause the problem). There is no such declaration in VoterInterface

- Option nr. 4 - most elegant imho. Adding the return type declaration in VoterInterface. however in breaks backward compatibility so that solution can be introduced in 6.0 framework.

**Additional context**

**Comment by lyrixx** [comment]
All voters must return an int.
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Security/Core/Authorization/Voter/VoterInterface.php#L38

Why do you return something else? 

IMHO nothing should be fixed here

**Comment by jvasseur** [comment]
I think the problem is that if you make a mistake and return something that is castable ton an int (for example `true` instead of `ACCESS_GRANTED`) it will work in dev environment where it shouldn't, and the bug will only appear in production.

**Comment by wouterj** [comment]
Thanks for all information in the issue description, that makes it very easy to trace the exact problem here.

I would propose the following solution:

1. Remove the `: int` type juggling indicator in the 4.4 branch
2. Deprecate not returning an int in 5.x. This can be done exactly like done in the Console component in 4.4: https://github.com/symfony/symfony/blob/aa5ec20a0c81cbb63293395bedb3e9952060ad9d/src/Symfony/Component/Console/Command/Command.php#L257-L259
3. Add an exception in 6.0, like in the Console component: https://github.com/symfony/symfony/blob/f0dfb9eefe1a83e162c16c00e85f62fbd03f3cb8/src/Symfony/Component/Console/Command/Command.php#L258-L260

Are you willing to create a PR for (1) and (2)?

> There is no such declaration in VoterInterface

There is, in the PHPdoc: https://github.com/symfony/symfony/blob/f0dfb9eefe1a83e162c16c00e85f62fbd03f3cb8/src/Symfony/Component/Security/Core/Authorization/Voter/VoterInterface.php#L36-L38 As types are very new in PHP (and Symfony is still migrating to PHP types), PHPdocs are just as important for the contract as PHP types.

**Comment by adeptofvoltron** [comment]
@wouterj thx for the response. I will do exactly the way you suggested. today in the late afternoon(CET time zone).

**Comment by adeptofvoltron** [comment]
@jvasseur and @lyrixx that is correct. However, the dev environment should escalate errors, not hide them.

**Comment by jvasseur** [comment]
@adeptofvoltron yes, but erroring in this case would be a BC break, that why we can only deprecate it for now.
