### ISSUE TITLE
Cannot create new symfony version on PHP 8

### ISSUE THREAD

**Issue by aquzif** [symfony/symfony#39218]
**Symfony version(s) affected**: cli v4.21.0

**Description**  

I cannot create new symfony project from symfony CLI on PHP 8. In error logs i see that it's caused by orm-pack and doctrine-migrations-bundle, which want PHP v7

**How to reproduce**  

![image](https://user-images.githubusercontent.com/67521903/100549994-f56ca580-3276-11eb-87e6-45be396150d6.png)

**Possible Solution**  

upgrade orm-pack and doctrine-migrations-bundle to PHP 8

**Comment by maxhelias** [comment]
It's not a Symfony issue but related to doctrine migration bundle : https://github.com/doctrine/DoctrineMigrationsBundle/pull/383

**Comment by jderusse** [comment]
`symfony/orm-pack` does not have constraints on php version as of version 1.0.8 (https://github.com/symfony/orm-pack/blob/v1.0.8/composer.json).

migration-bundle is managed by doctrine project as mentioned by @maxhelias (thanks for the link to the issue)
