### ISSUE TITLE
[Forms] - Change Dynamically Forms with DataMapper and EventSubscriber

### ISSUE THREAD

**Issue by waeyy** [symfony/symfony#39219]
**Symfony version(s) affected**: 4.4.4

Question deleted as Github issues are not made for support.

Thank you for your help!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
