### ISSUE TITLE
symfony/mime v5.2.0 broken file upload

### ISSUE THREAD

**Issue by naelsaid** [symfony/symfony#39225]
**Symfony version(s) affected**: symfony/mime v5.2.0

**Description**  
Today I ran composer update for a project and found that file uploads in all forms broke. After investigating the problem I figured out that if I go back to symfony/mime v5.1.9 everything works again.

Our project uses Laravel 8 which in turn uses symfony/mime

**Comment by Nyholm** [comment]
Thank you. 
Could you show some a minimal example of what is broken?

**Comment by naelsaid** [comment]
Unfortunately I am not an expert in debugging such kind of errors. All I can provide is that in Laravel I get the error
```
Illuminate\Validation\ValidationException: The given data was invalid
```
When I upload an image.
this is the validation rules set for the uploaded image

```
'mimes' => 'png,jpg,gif,jpeg',
```

Hope it helps.

i thought it might be a Laravel issue but when I downgrade symfony/mime to v5.1.9 everything works like normal. So I do not think it is a Laravel issue.

**Comment by Nyholm** [comment]
Hm.. We are very much in the "Something is wrong" area. =)

I need something more. 

It sounds like you have an image upload form and validation that it only accepts some specific extensions. But you get a validation error. 

I see on your validation rules you have `mimes` key and the value is a list of extensions. That does not look correct. 

Is there an `extensions` key you can use instead? Or will it be better if you used mimes instead? Example mime is: `image/png`

**Comment by fragkp** [comment]
I tracked the issue further to this file:
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/File/File.php#L61

`getExtensions()` from the `MimeTypes` class returns a different order for `image/jpeg` mime.

5.1:
```php
array:3 [
  0 => "jpeg"
  1 => "jpg"
  2 => "jpe"
]
```

5.2:
```php
array:3 [
  0 => "jpg"
  1 => "jpeg"
  2 => "jpe"
]
```

**Comment by Nyholm** [comment]
Thank you @fragkp. You are correct. But that is fine, ie, there is no BC break and @mnaas code should not fail because of it.

**Comment by naelsaid** [comment]
Yes I was investigating and found the same problem
I opened an issue where I do not know if this is a Laravel or Symfony/mime issue 
https://github.com/laravel/framework/issues/35417

**Comment by Nyholm** [comment]
Thank you for the reports. 

@fragkp found the cause of this change and @NEGits fixed it in https://github.com/laravel/framework/pull/35416

Awesome work!

**Comment by driesvints** [comment]
Not that I want to start a discussion around this @Nyholm but imo this is a change in behavior which should be considered a BC break. It's a gray area for sure. Anyway, I think we can work around this easily. Thanks for your work 👍

**Comment by mfn** [comment]
FTR, the actually merged PR for 6.x was https://github.com/laravel/framework/pull/35419

**Comment by Nyholm** [comment]
Awesome!
