### ISSUE TITLE
PHP E_WARNING on writing cache

### ISSUE THREAD

**Issue by rxu** [symfony/symfony#39227]
**Symfony version(s) affected**: 5.1.9+

**Description**  
`public function dumpFile(string $filename, $content)` produces `E_WARNING` (`No such file or directory`) at this line
https://github.com/symfony/symfony/blob/586f5b72da9f38ef0f7d1b5a30b476ee68302e8b/src/Symfony/Component/Filesystem/Filesystem.php#L670

The code was added with this PR https://github.com/symfony/symfony/pull/39059

Custom error handler has been used. `E_WARNING` example (from XDebug):
```
msg_handler( $errno = 2, $msg_text = 'unlink(C:\\Program Files\\Apache\\htdocs\\40\\cache\\production\\aut970C.tmp): No such file or directory', $errfile = 'C:\\Program Files\\Apache\\htdocs\\40\\vendor\\symfony\\filesystem\\Filesystem.php', $errline = 670 )
```

**How to reproduce**  
```php
<?php

use Symfony\Component\Config\ConfigCache;

set_error_handler('myErrorHandler');

$cached_file_content = "<php /* Some comment */ \n";
$cached_file_name = 'my_cached_file.php';
require_once __DIR__.'/vendor/autoload.php';
$configCache = new ConfigCache($cached_file_name, false);
$configCache->write($cached_file_content);

// error handler function
function myErrorHandler($errno, $errstr, $errfile, $errline)
{
    switch ($errno) {
    case E_WARNING:
        echo "<b>PHP WARNING</b> [$errno] $errstr<br />\n";
        break;

    default:
        echo "Unknown error type: [$errno] $errstr<br />\n";
        break;
    }

    /* Don't execute PHP internal error handler */
    return true;
}

```

**Possible Solution**  
Check `$tmpFile` for existence before unlinking at line 670 as at thit point `$tmpFile` should be normally already renamed and doesn't exist unless renaming has failed.

**Additional context**  
Windows, PHP 7.4 and PHP 8.0 tested, Apache/2.4.37, Symfony 5.1.9
![image](https://user-images.githubusercontent.com/212322/100589914-45567580-3326-11eb-8d57-b8d04e420081.png)

**Comment by nicolas-grekas** [comment]
That's a bug in your error handler: the call is silenced, the error handler should account for it.

**Comment by rxu** [comment]
Why would you want to suppress E_WARNING instead of fixing the actual bug in the code? :)
That's weird, but whatever.

**Comment by stof** [comment]
@rxu the PHP function raises a warning and returns a `false` value to report the failure. Symfony silences the warning precisely because it wants to handle the failure on its own.

**Comment by rxu** [comment]
@stof All those explanations are good, but currently this issue prevents me from upgrading phpBB to Symfony 5.1 as it breaks container builder here
https://github.com/phpbb/phpbb/blob/c11f9bbe0d6c94df98fa272963a416791529eea7/phpBB/phpbb/di/container_builder.php#L487
Silencing this error doesn't affect anything, it just produces the error shown above on the screenshot (simply because container wasn't built because of the error). That wasn't the case before the Symfony 5.1.9.
phpBB's custom error handler [does handle](https://github.com/phpbb/phpbb/blob/c11f9bbe0d6c94df98fa272963a416791529eea7/phpBB/includes/functions.php#L2967-L2971) `@` operator but it doesn't help.
I've presented simple custom error handler above just to give the way to reproduce the issue, it was never used in real applications.

**Comment by nicolas-grekas** [comment]
See #39243

**Comment by stof** [comment]
The error in your screenshot is absolutely not an issue about the warning triggered by `unlink`, but about a fatal error when using `getParameter` on `null` in `includes/functions.php` at line 2986 (my guess is that this location is inside your `msg_handler` function but I cannot be sure as I don't have access to the code).

**Comment by rxu** [comment]
@stof `getParameter` is called on `null` as far as container builder object is null, just because it wasn't built properly :)
@nicolas-grekas So I'm not the only one. Thanks.

**Comment by stof** [comment]
@rxu I would say that the issue is not that the cotnainer has not been built properly, but that it has not been built **yet**. If your custom error handler relies on having a working container, you should not register it before building the container, but only after. Otherwise, errors during the container building will call your custom error handler while not satisfying the assumptions of that custom error handler.
