### ISSUE TITLE
PHP8 lint:container issue with isBuiltIn() use

### ISSUE THREAD

**Issue by jdelaune** [symfony/symfony#39233]
**Symfony version(s) affected**: 5.2.0

**Description**  
Run lint:container command and I get the error:

```
In CheckTypeDeclarationsPass.php line 288:
Attempted to call an undefined method named "isBuiltin" of class "ReflectionUnionType".
```

**How to reproduce**  
Run lint:container

**Possible Solution**  
Might be similar to this: https://github.com/symfony/symfony/issues/38836

**Additional context**  
n/a

**Comment by derrabus** [comment]
I'll have a look at this later today.

**Comment by derrabus** [comment]
4.4 is also affected.

**Comment by derrabus** [comment]
@jdelaune Can you have a look at #39251?
