### ISSUE TITLE
Filesystem::dumpFile() tries to remove not existing file on symfony/filesystem 5.1.9

### ISSUE THREAD

**Issue by gechetspr** [symfony/symfony#39235]
**Symfony version(s) affected**: 5.1.9

**Description**  
On our project we have a custom error handler that shows all errors, even ignored one.
With this update https://github.com/symfony/filesystem/compare/v5.1.8...v5.1.9 we try to unlink temporary file in any case, even if it was successfully renamed.
Because we have this custom error handler, now we get an error every time we try to dump a file.

**How to reproduce**  
Update symfony/filesystem to at least version 5.1.9. Try to dump file via Filesystem;

**Possible Solution**  
We can use `catch (Throwable $e) { @unlink($tmpFile); throw $e;}` instead of `finally` block

**Comment by nicolas-grekas** [comment]
Your error handler is broken I suppose. Can you please send a PR adding a file_exists check around the call so that we can discuss the change on a PR?

**Comment by gechetspr** [comment]
@nicolas-grekas I've created a PR, thanks!

As i know our error handler intended to be that way for development env.

https://github.com/symfony/symfony/pull/39239

P.S. I hope I didn't miss smth for PR. This is my first one :)

**Comment by gechetspr** [comment]
https://github.com/symfony/symfony/pull/39243
