### ISSUE TITLE
[Form] Collection's prototype data is not available in PRE_SET_DATA event on submit

### ISSUE THREAD

**Issue by digilist** [symfony/symfony#39253]
**Symfony version(s) affected** 5.1.9 and 4.4.17 (did not test it with other versions yet)

**Description**  
I might have found a problem in the form component which is related to the PRE_SET_DATA listener, collections and prototype data. It can be best explained with an example:

```php
class TestType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            var_dump($event->getData());
        });
    }
}


// Create form
$form = $this->factory->createBuilder()
    ->add('collection', CollectionType::class, [
        'entry_type' => TestType::class,
        'prototype_data' => 'prototype data',
        'allow_add' => true,
    ])
    ->getForm()
;

$form->submit([
    'collection' => [
        [],
    ],
]);
```

The output here is the
```
string(14) "prototype data"
NULL
```

So what happens is that the prototype form is initiated with the prototype data. When the PRE_SET_DATA event listener is initiated the form event contains the prototype data (`$event->getData() === 'prototype data'`). When the form is then submitted with a new entry the prototype data is not available when the PRE_SET_DATA listener is called for that new entry (`$event->getData() === null`).

This means, that when the form is constructed it can be adjusted based on the prototype data. But when the form is submitted with a new entry, those modifications are no longer possible, because the prototype data is not available.

I am not sure if this is a bug or by design (I admit it's quite an edge case). But this behavior was quite confusing for me and it took a bit to point it to the prototype data and that it is not available on form submission for new entries.

**Comment by yceruto** [comment]
Hey, thanks for this detailed report. However, could you elaborate a bit more about what is the expected result for your example? I don't see any problem with the current result.

> When the form is then submitted with a new entry the prototype data is not available when the PRE_SET_DATA listener is called for that new entry ($event->getData() === null).

It's expected in my opinion. The prototype form/data is aimed at the view layer, and there is no relation between the prototype data and the new entries data on submitting. Also, the `PRE_SET_DATA` event is called before the submitting data is set, hence it will be null in your case always.

> But when the form is submitted with a new entry, those modifications are no longer possible and will result in an error.

Please, update the description with the error you're facing here.

**Comment by digilist** [comment]
Thank you for looking into this.

I am expecting to configure the form on submit in the same way it was configured before the submit. So for example, you can use an `PRE_SET_DATA` event listener to modify form fields depending on the current data (e.g. add a company name field for a company address entity, but not for a person entity). So when the form is built, a new field is added and shown on rendering. On submit the `PRE_SET_DATA` event listener adds the field again and the posted value can be processed.

And this usually works, but not in the particular edge case that I described with collections and prototype data. There, the form is built using the prototype data before submit, but on submit the prototype data is not available and so the form cannot be modified like before.

So using my example from above if you have a collection of addresses and it is known that it runs in a "company context" you can have a `CompanyAddress` object as prototype data. The  `PRE_SET_DATA` event listener in an `AddressType` then checks the class of the current data and adds the company name for an `CompanyAddress` object. But on submit the prototype data in the event object is not available like it was before submit and so the address is either not added or it might result in an error, because a method of that object is accessed (expecting the data to be available).

Or to say it differently, I think it's confusing that it is possible to configure/built a form using the prototype data, but you cannot apply the same logic again on submit for a new entity. The problem is not, that the submitted data is not available for the `PRE_SET_DATA` event.

> Please, update the description with the error you're facing here.
Sorry, this was from an earlier example that I wanted to use. In general there is no "error", but it can result in an error, e.g. by calling a method on a null value. In my first example I was accessing the data, but later replaced it with the `var_dump()` to show that the data is null.

**Comment by xabbuh** [comment]
@digilist Could you please create a small example application that allows to reproduce it? I think I need to debug a bit and understand what is going on before judging whether or not this is a bug.

**Comment by digilist** [comment]
Sorry, did not find time for creating an example yet. Now that you closed this issue, you do not consider this a bug or what's the reason for closing this?

**Comment by xabbuh** [comment]
As written in https://github.com/symfony/symfony/issues/39253#issuecomment-758475388 I would need to debug this a bit before deciding whether or not this is a bug or the expected behavior. When you find some time to create an example application, please don't hesitate to comment here and we'll reopen.

**Comment by digilist** [comment]
I created a project with a reproducible example: https://github.com/digilist/symfony_issue_39253_reproducer

1. Clone the project and run `composer install`
2. Start the PHP Webserver: `php -S localhost:8000 -t public`
3. Go to http://localhost:8000
4. Submit the form by adding a third address (which is based on the prototype, so a new address should be created)

The example is a bit constructed, but I think it will show the issue.

And just in case I delete that repository at some point, here is the commit as a patch:
<details>

```patch
From 70f3b00a7b95f2b2b7ff6f6aa35ba3b849a6ae08 Mon Sep 17 00:00:00 2001
From: Markus Fasselt <m************@gmail.com>
Date: Sun, 31 Jan 2021 12:34:56 +0100
Subject: [PATCH] Add reproducable code for issue symfony/symfony#39253

---
 composer.json                      |  2 +-
 config/routes.yaml                 |  6 ++---
 src/Controller/IndexController.php | 27 ++++++++++++++++++++++
 src/Entity/Address.php             | 23 +++++++++++++++++++
 src/Entity/Company.php             | 10 +++++++++
 src/Form/AddressType.php           | 36 ++++++++++++++++++++++++++++++
 src/Form/CompanyType.php           | 22 ++++++++++++++++++
 templates/index.html.twig          | 11 +++++++++
 8 files changed, 133 insertions(+), 4 deletions(-)
 create mode 100644 src/Controller/IndexController.php
 create mode 100644 src/Entity/Address.php
 create mode 100644 src/Entity/Company.php
 create mode 100644 src/Form/AddressType.php
 create mode 100644 src/Form/CompanyType.php
 create mode 100644 templates/index.html.twig

diff --git a/composer.json b/composer.json
index b0622c8..c1baa51 100644
--- a/composer.json
+++ b/composer.json
@@ -4,7 +4,7 @@
     "minimum-stability": "dev",
     "prefer-stable": true,
     "require": {
-        "php": ">=7.2.5",
+        "php": ">=7.4",
         "ext-ctype": "*",
         "ext-iconv": "*",
         "composer/package-versions-deprecated": "1.11.99.1",
diff --git a/config/routes.yaml b/config/routes.yaml
index c3283aa..c63a56f 100644
--- a/config/routes.yaml
+++ b/config/routes.yaml
@@ -1,3 +1,3 @@
-#index:
-#    path: /
-#    controller: App\Controller\DefaultController::index
+index:
+    path: /
+    controller: App\Controller\IndexController
diff --git a/src/Controller/IndexController.php b/src/Controller/IndexController.php
new file mode 100644
index 0000000..222a3ee
--- /dev/null
+++ b/src/Controller/IndexController.php
@@ -0,0 +1,27 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Controller;
+
+use App\Entity\Address;
+use App\Entity\Company;
+use App\Form\CompanyType;
+use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+
+final class IndexController extends AbstractController
+{
+    public function __invoke(Request $request): Response
+    {
+        $company = new Company();
+        $company->addresses[] = Address::forCompany('Hamburg');
+        $company->addresses[] = Address::forCompany('New York');
+
+        $form = $this->createForm(CompanyType::class, $company);
+        $form->handleRequest($request);
+
+        return $this->render('index.html.twig', ['form' => $form->createView()]);
+    }
+}
diff --git a/src/Entity/Address.php b/src/Entity/Address.php
new file mode 100644
index 0000000..64f86a2
--- /dev/null
+++ b/src/Entity/Address.php
@@ -0,0 +1,23 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Entity;
+
+final class Address
+{
+    public string $type;
+    public ?string $companyName = null;
+    public ?string $city = null;
+
+    public function __construct($type = 'personal', ?string $city = null)
+    {
+        $this->type = $type;
+        $this->city = $city;
+    }
+
+    public static function forCompany(?string $city = null): self
+    {
+        return new self('company', $city);
+    }
+}
diff --git a/src/Entity/Company.php b/src/Entity/Company.php
new file mode 100644
index 0000000..9b61706
--- /dev/null
+++ b/src/Entity/Company.php
@@ -0,0 +1,10 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Entity;
+
+final class Company
+{
+    public array $addresses = [];
+}
diff --git a/src/Form/AddressType.php b/src/Form/AddressType.php
new file mode 100644
index 0000000..a07abd6
--- /dev/null
+++ b/src/Form/AddressType.php
@@ -0,0 +1,36 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Form;
+
+use App\Entity\Address;
+use App\Entity\Company;
+use Symfony\Component\Form\AbstractType;
+use Symfony\Component\Form\Extension\Core\Type\TextType;
+use Symfony\Component\Form\FormBuilderInterface;
+use Symfony\Component\Form\FormEvent;
+use Symfony\Component\Form\FormEvents;
+use Symfony\Component\OptionsResolver\OptionsResolver;
+
+final class AddressType extends AbstractType
+{
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        $builder->add('city', TextType::class);
+
+        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
+            $address = $event->getData();
+            if ($address->type === 'company') { // on Form Submit $address is null and this results in an error
+                $event->getForm()->add('companyName', TextType::class);
+            }
+        });
+    }
+
+    public function configureOptions(OptionsResolver $resolver)
+    {
+        $resolver->setDefaults([
+            'data_class' => Address::class,
+        ]);
+    }
+}
diff --git a/src/Form/CompanyType.php b/src/Form/CompanyType.php
new file mode 100644
index 0000000..e72f0af
--- /dev/null
+++ b/src/Form/CompanyType.php
@@ -0,0 +1,22 @@
+<?php
+
+declare(strict_types=1);
+
+namespace App\Form;
+
+use App\Entity\Address;
+use Symfony\Component\Form\AbstractType;
+use Symfony\Component\Form\Extension\Core\Type\CollectionType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+final class CompanyType extends AbstractType
+{
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        $builder->add('addresses', CollectionType::class, [
+            'entry_type' => AddressType::class,
+            'prototype_data' => Address::forCompany(),
+            'allow_add' => true,
+        ]);
+    }
+}
diff --git a/templates/index.html.twig b/templates/index.html.twig
new file mode 100644
index 0000000..8dd8a4a
--- /dev/null
+++ b/templates/index.html.twig
@@ -0,0 +1,11 @@
+{{ form_start(form) }}
+{{ form_rest(form) }}
+
+<p>
+    Add new address via prototype:
+</p>
+{# based on the prototype, but faked without JS here #}
+<div><label class="required">2</label><div id="company_addresses_2"><div><label for="company_addresses_2_city" class="required">City</label><input type="text" id="company_addresses_2_city" name="company[addresses][2][city]" required="required" /></div><div><label for="company_addresses_2_companyName" class="required">Company name</label><input type="text" id="company_addresses_2_companyName" name="company[addresses][2][companyName]" required="required" /></div></div></div>
+
+<input type="submit" />
+{{ form_end(form) }}
-- 
2.30.0
```

</details>

**Comment by xabbuh** [comment]
Thanks for the application. I have checked it and the behaviour looks expected to me. `null` is returned for the form that is not present when the form is initially rendered, but that is added dynamically after submission.

**Comment by digilist** [comment]
Thank you for checking. But I am not sure I can follow your explanation.

Just to be clear: The following part of the code is executed without any error for the prototype / with the prototype data before the form is submitted (but fails on form submission with any new element):
```php
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $address = $event->getData();
            if ($address->type === 'company') { // on Form Submit $address is null and this results in an error
                $event->getForm()->add('companyName', TextType::class);
            }
        });
```

So on form rendering `$address === Address::forCompany()` (which is the prototype data), but on submission `$address === null` (which results in an error in the next line, as `$address` is null). So, when the form with the prototype is initially remdered, the data/`$address` is not null, but after submission for any new element.

So this is expected? Still looks odd for me. But anyway, even if it is, thank you for taking a look :)

**Comment by xabbuh** [comment]
Initially, there are three children for the collection type. The one for the prototype indeed receives the prototype data. But the other two children receives the concrete `Address` instances that you added inside your controller (i.e. "Hamburg" and "New York"). The fourth child is added on submission when the `CollectionType` detects the new data. For this child there is no data to publish in the `PRE_SET_DATA` event as the data was only passed during the submission of the form. You would observe the same behaviour without submitting the form if you added a `null` child to the `$company->addresses` property.
