### ISSUE TITLE
[Security][5.2.0 only] Call to a member function getUserLoader() on null

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#39262]
**Symfony version(s) affected**: 5.2.0
*5.2-RC2 was not affected*

**Description**  

Using the new authenticator-based security,
and a custom authenticator (which extends `AbstractAuthenticator`),
users get this error after login: `Call to a member function getUserLoader() on null`

![image](https://user-images.githubusercontent.com/919405/100719957-9d8c8680-33bd-11eb-8303-403210a65571.png)

This is caused by `PasswordMigratingListener`, being triggered automatically since #39213, to assume than every Passport contains an UserBadge. This is nor documented ([here](https://symfony.com/doc/current/security/experimental_authenticators.html)) nor enforced by `UserPassportInterface`, so I believe it should be tested.

**How to reproduce**  

/ 

**Possible Solution**  

PR coming soon

**Comment by wouterj** [comment]
Actually, the `UserBadge` should be the new way to go in 5.2 (See https://github.com/symfony/symfony/commit/907ef311bf789f5641dfc718a5a59dcd9fd5ace4). But we haven't documented it yet and it appears like my BC layer is no good:  https://github.com/symfony/symfony/blob/ff97b5f17b63d5198cc56584623d1bb09f923b5b/src/Symfony/Component/Security/Http/Authenticator/Passport/Passport.php#L42-L45

(it should instead initialize a `UserBadge` if a `UserInterface` was passed)

**Comment by romaricdrigon** [comment]
This issue is that this BC layer is within `Passport` ; nothing forbids a developer from implementing its own Passport (actually, I did), and then nothing in `UserPassportInterface` guides him. IMO, `UserPassportInterface` should be modified to enforce properly required badges.

Right now, I still think #39263 is the proper way to go. Until the deprecation/migration path regarding `UserPassportInterface` is done.

**Comment by wouterj** [comment]
Yes, #39263 is the way to go no matter what other things we do imho. 

(fyi, this BC layer only lasts one minor version, in the 5.3 release we remove it and switch to `UserBadge` completely. So I would suggest you to update your own passport to use `UserBadge`)

**Comment by romaricdrigon** [comment]
Since PR was merged, issue can be closed. 
Thank you for the piece of advice @wouterj
