### ISSUE TITLE
Symfony Benchmark on PHP 8 and JIT

### ISSUE THREAD

**Issue by CoderChang65535** [symfony/symfony#39278]
I saw the benchmark from [PHP 8.0 release page](https://www.php.net/releases/8.0/en.php):
<img width="1639" alt="benchmark" src="https://user-images.githubusercontent.com/19420270/100823404-1f98b000-348f-11eb-8be5-146dcec6be43.png">

It seems **using PHP8 with JIT** to run Symfony would cause performance loss...
How to understand the benchmark result?
Is that a good choice to switch to PHP8 now?

**Comment by javiereguiluz** [comment]
From what I understand, JIT is mostly intended for CPU-intensive tasks. A simple HTTP request to load a Symfony Demo page doesn't fit in that use-case, so that's why the results are disappointing.

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

Nothing in the article says PHP 8 cause performance loss in Symfony. But it says "Typical application performance is on par with PHP 7.4."
This graph does not compares PHP 8 with previous version, it compares PHP 8 with "Tracing JIT" and "Function JIT"

If you have a benchmark with a specific Symfony case, feel free to reopen this issue.

**Comment by CoderChang65535** [comment]
> Hello and thank you for reaching out.
> 
> Nothing in the article says PHP 8 cause performance loss in Symfony. But it says "Typical application performance is on par with PHP 7.4."
> This graph does not compares PHP 8 with previous version, it compares PHP 8 with "Tracing JIT" and "Function JIT"
> 
> If you have a benchmark with a specific Symfony case, feel free to reopen this issue.

Hi @jderusse , thanks for your reply so maybe we should avoid using JIT to run Symfony on PHP8.

**Comment by jderusse** [comment]
Why? Does something in the article shows a performance change with JIT?

As far as I understand, it compares PHP 8 with engine `function JIT` and PHP 8 with engine `tracing JIT`

**Comment by javiereguiluz** [comment]
@jderusse in the chart, the black vertical line is "PHP 8 without JIT" ... so the bars below that line are slower and above that line are faster.

**Comment by CoderChang65535** [comment]
> @jderusse in the chart, the black vertical line is "PHP 8 without JIT" ... so the bars below that line are slower and above that line are faster.

Yes, that's my confusion

**Comment by stof** [comment]
The only conclusion of that benchmark relevant for Symfony is that you should not configure your PHP to use the function JIT when running a Symfony app, as that makes it slower. Running without JIT or with the tracing JIT seems to do the same regarding performance so both are fine (probably because the tracing JIT stays a no-op here due to not detecting CPU-intensive work in its tracing).

**Comment by derrabus** [comment]
> so maybe we should avoid using JIT to run Symfony on PHP8.

This has nothing to do with Symfony. The Symfony demo app used for that comparison is a simple web application that displays data from a database. This is the kind of application that won't benefit from JIT. This is why you see similar results with Wordpress and MediaWiki.

If you have long running Symfony Messenger workers – depending on what they do – the results might look different.

**Comment by CoderChang65535** [comment]
@stof @derrabus 
Yes, I take your points and I will do further research and discussion on upgrading env to PHP8 in my side.
In my situation, there are Symfony APIs and websites and I am not familiar with CPU-intensive works like Symfony Messenger(using MQ instead).
