### ISSUE TITLE
[DomCrawler] Namespace-Prefixes with null value cached but not found

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#39277]
**Symfony version affected**: 5.x-dev

**Description**  
In #39097 namespace caching has been added. Not found namespaces (prefix with namespace-value null) are cached but this value is not found in https://github.com/symfony/symfony/blob/a8e85ecbbd52bc2aaa50d58daf02afb8b4764e9d/src/Symfony/Component/DomCrawler/Crawler.php#L1197

**Possible Solution**  
Change cache check or do not cache null values anymore (performance hit in edge cases).

**Comment by bastnic** [comment]
Good catch! Same thing as #35252, isset could be replaced by `array_key_exists`.

**Comment by simonberger** [comment]
Not at this particular place. An `ArrayObject` is used.

**Comment by stof** [comment]
the solution would be to use `offsetExists` directly here.

**Comment by derrabus** [comment]
@simonberger Would you like to submit a PR for this?

**Comment by simonberger** [comment]
Feel free to take it. The related PR was enough fun for this year.
