### ISSUE TITLE
[Console] Override output verbosity for throwable rendering

### ISSUE THREAD

**Issue by arnegroskurth** [symfony/symfony#39273]
**Description**  
I'm currently using the `Symfony\Component\Console\Tester\ApplicationTester` to test commands of a CLI application. Some of those commands use the default `--quiet` option to suppress non-essential output of the command (just like e.g. `docker ps -q`) which is also covered by a test-case.
When the test-case now fails (e.g. within a CI-pipeline) the `--quiet` option also suppresses printing the full-stack trace by the throwable renderer which would be very helpful.

So my feature request would be to introduce an override for the output verbosity used for throwable renderings (this could be an additional field in `Symfony\Component\Console\Application`).

**Example**  
```php
<?php

$application = new Symfony\Component\Console\Application();
$application->setAutoExit(false);
$application->setThrowableRenderingVerbosity(\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_DEBUG); // proposal

$applicationTester = new Symfony\Component\Console\Tester\ApplicationTester($application);
$applicationTester->run(['my-command', '--quiet']);

// full stack-trace is rendered on failure...
```

**Comment by ro0NL** [comment]
im not sure another option to undo --quiet makes sense really :/

IIUC the missing piece is to obtain the last thrown exception from either Application or ApplicationTester for inspection ... (the inspection parts makes me think it belongs to ApplicationTester)

for regular flow event subscribers may listen to ConsoleEvents::ERROR, for you to process exceptions as needed

why not test without --quiet and eg. increase verbosity by passing its option to `ApplicationTester::run()`

**Comment by chalasr** [comment]
I agree with @ro0NL here, adding such methods to the API would be confusing. 
Feel free to comment if you have something else to propose or if you disagree.
Closing meanwhile, thanks for your understanding.

**Comment by arnegroskurth** [comment]
Sorry for the delayed answer.

> im not sure another option to undo --quiet makes sense really :/
>

I also agree that an override for the output verbosity might not be the best solution here.

> IIUC the missing piece is to obtain the last thrown exception from either Application or ApplicationTester for inspection ... (the inspection parts makes me think it belongs to ApplicationTester)
> 
> for regular flow event subscribers may listen to ConsoleEvents::ERROR, for you to process exceptions as needed
> 

I have to admit that I was not aware of the injectable event dispatcher. This solves my problem by invoking a command within my test-case like this:

```php
$application = new Application();
$application->setAutoExit(false);

// set up exception rendering even when using --quiet
$output = new ConsoleOutput(OutputInterface::VERBOSITY_DEBUG);
$eventDispatcher = new EventDispatcher();
$eventDispatcher->addListener(ConsoleEvents::ERROR, function(ConsoleErrorEvent $event) use ($application, $output) {

    $application->renderThrowable($event->getError(), $output);
});
$application->setDispatcher($eventDispatcher);

$applicationTester = new ApplicationTester($application);
$applicationTester->run(['my-command', '--quiet']);
```

This obviously relies on the function `Symfony\Component\Console\Application::renderThrowable` being supported as part of the package interface. (@chalasr @ro0NL Is it?) Otherwise I would have to re-implement that functionality.
Btw.: Maybe it makes sense to refactor that into a separate class anyway as at least the internally called method `doRenderThrowable` is completely independent from the application-context.

> why not test without --quiet and eg. increase verbosity by passing its option to `ApplicationTester::run()`

This is not ideal as my application-code uses the `--quiet` option to alter its behaviour - suppressing non-essential output - which I want to also be covered by test-cases.

**Comment by chalasr** [comment]
@arnegroskurth Yes, `Application::renderThrowable()` is part of the component' public API. You can safely call it from your code.
