### ISSUE TITLE
console cache:clear throws php unlink "No such file" errors

### ISSUE THREAD

**Issue by ovgray** [symfony/symfony#39287]
**Symfony version(s) affected**: 4.4.17

**Description**  
When I update from 4.4.16 to 4.4.17, the following appears in my dev.log:
 
> php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3D4A.tmp): No such file or directory {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":698,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\config\\\\ResourceCheckerConfigCache.php\",\"line\":124,\"function\":\"dumpFile\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3DA8.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3E26.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3E47.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3EE4.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat3EE5.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat401E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat406D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat41D6.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4206.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4255.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4265.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat42E3.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat42F4.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4372.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4383.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat43F1.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4402.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4432.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4433.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat44C0.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4500.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat457E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat458E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat45ED.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat45EE.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat464D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat465D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat469D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat469E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat46FD.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat470D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat476C.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat477D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat47DB.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat47DC.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat483B.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat483C.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat489B.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat48AC.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat490A.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat491B.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat497A.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat498A.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat49E9.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat49FA.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4A39.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4A3A.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4AB8.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4AC9.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4B37.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4B38.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4BA7.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4BB7.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4C16.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4C27.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4C95.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4C96.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4CF5.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4D25.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4D74.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4D75.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4DD3.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4DE4.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4E52.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4E63.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4ED1.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4EE2.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4F41.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4F42.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4FB0.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat4FC1.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5000.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5011.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat508F.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5090.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat512D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat512E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat518D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat519E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat51ED.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat51FD.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat525C.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat525D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5377.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat53D6.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat54B2.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5511.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat559E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat55AF.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat560E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat561E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat566D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat567E.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat56DD.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat56DE.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat574C.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat574D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat57AC.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat57BC.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat583A.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat587A.tmp): No such file or directory {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":698,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\config\\\\ResourceCheckerConfigCache.php\",\"line\":132,\"function\":\"dumpFile\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5927.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5957.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat59B5.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat59B6.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat59F6.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5A07.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5A36.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5A57.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5A77.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\translations\cat5A88.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\Url769C.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\Url769D.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\Url76BD.tmp): No such file or directory [] []
>  php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\Url76BE.tmp): No such file or directory [] []

If I run cache:clear a second time, the following is added to dev.log:

> php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\UrlB0C1.tmp): No such file or directory {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":698,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\adrexpedite\\\\vendor\\\\symfony\\\\config\\\\ResourceCheckerConfigCache.php\",\"line\":124,\"function\":\"dumpFile\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
> php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\UrlB0D2.tmp): No such file or directory [] []
> php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\UrlB0E3.tmp): No such file or directory [] []
> php.DEBUG: Warning: unlink(C:\xampp\htdocs\adrexpedite\var\cache\dev\UrlB0E4.tmp): No such file or directory [] []

No such errors appear in dev.log when I revert to 4.4.16.

The packages that I am upgrading/downgrading are:
>  symfony/asset 
>  symfony/dom-crawler 
>  symfony/browser-kit 
>  symfony/console 
>  symfony/css-selector 
>  symfony/var-dumper 
>  symfony/twig-bridge 
>  symfony/mime 
>  symfony/http-foundation 
>  symfony/event-dispatcher 
>  symfony/debug 
>  symfony/error-handler 
>  symfony/http-kernel 
>  symfony/debug-bundle 
>  symfony/doctrine-bridge 
>  symfony/dotenv 
>  symfony/var-exporter 
>  symfony/cache 
>  symfony/expression-language 
>  symfony/filesystem 
>  symfony/finder 
>  symfony/inflector 
>  symfony/property-access 
>  symfony/options-resolver 
>  symfony/intl 
>  symfony/form 
>  symfony/http-client 
>  symfony/mailer 
>  symfony/monolog-bridge 
>  symfony/property-info 
>  symfony/security-core 
>  symfony/security-http 
>  symfony/security-guard 
>  symfony/security-csrf 
>  symfony/dependency-injection 
>  symfony/config 
>  symfony/security-bundle 
>  symfony/serializer 
>  symfony/stopwatch 
>  symfony/translation 
>  symfony/validator 
>  symfony/yaml 
>  symfony/process 
>  symfony/twig-bundle 
>  symfony/routing 
>  symfony/framework-bundle 
>  symfony/web-profiler-bundle

**Comment by mbabker** [comment]
This should be fixed by https://github.com/symfony/symfony/pull/39243

**Comment by ovgray** [comment]
Thank you.

**Comment by xabbuh** [comment]
closing as explained
