### ISSUE TITLE
[HttpClient] AsyncResponse/AsyncDecoratorTrait - How to use it, how to use it with dependency injection and missing documentation?

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#39284]
I would like to know how to go about using the AsyncResponse for HttpClient. I could not find any real documentation but apparently it is Symfony's middleware implementation?
Also how would this work with dependency injection? I guess it can be stacked to allow multiple middleware AsyncResponse in between?

Also: How would one go about to add e.g. an authentication middleware that has to execute a request prior to the main request like e.g. OAuth2 ? And upon unauthorized retrieves a new token too? I think it should be possible using this but to be honest I am not completely sure how to be use it.
In that regard: Do you plan to add an OAuth2 client using this too?

And I know this is quite a new feature but it looks interesting and I would like to know how to use it.

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

- StackOverflow: https://stackoverflow.com/questions/tagged/symfony
- Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by derrabus** [comment]
If I may add: If you think that we need additional documentation on the feature, https://github.com/symfony/symfony-docs/issues would be the right place for such a request.

**Comment by AndreasA** [comment]
@jderusse @derrabus Then you should adjust you github issue templates as 
I can create a support issue and a documentation issue here.

Now that I know about it, it shows the stop icon and a minor description below but it still has the get started button and I just thought that you did not provide a specific icon for it. 

Maybe you can adjust those templates to disable the get started button and show a tooltip on click/hover there? Not sure if that is configurable though.

**Comment by stof** [comment]
@AndreasA at the time we configured the issue templates, there was no way to add external links as options. So that's the best we could do at that time.
In the meantime, github added more features, so we could indeed improve that.

**Comment by AndreasA** [comment]
@stof A great that it is possible now. I would definitely do so to avoid confusion. 

I admit I should have read the small print description text too before opening the ticket but that is actually the point, in most cases that doesn't happen 😄

**Comment by nicolas-grekas** [comment]
There is https://github.com/symfony/symfony-docs/pull/13736, which is pending some love.

@AndreasA maybe you'd like to send a PR to add these links in the issue template? I don't know about these features personaly.

**Comment by AndreasA** [comment]
@nicolas-grekas Already found it and added a comment for a bit of improvement to it. However, it already helps quite a bit.
