### ISSUE TITLE
Typehints have not been added to the [DI] FileLoader class

### ISSUE THREAD

**Issue by CoeusCC** [symfony/symfony#39290]
**Symfony version(s) affected**: 5.2.0

**Description**  
I received the error below on a recent update to our Symfony packages:

```
===================BEGIN BACKTRACE===================
Declaration of

Symfony\Component\DependencyInjection\Loader\FileLoader::import($resource, $type = NULL, $ignoreErrors = false, $sourceResource = NULL, $exclude = NULL)

should be compatible with

Symfony\Component\Config\Loader\FileLoader::import($resource, ?string $type = NULL, bool $ignoreErrors = false, ?string $sourceResource = NULL, $exclude = NULL)

at ../vendor/symfony/dependency-injection/Loader/FileLoader.php 30:

  ../site.null/htdocs/index.php (7) calling require()
  ../bootstrap.php (41) calling {closure}()
  ../bootstrap.php (37) calling require_once()
  ../bootstrap/service_container.php (29) calling spl_autoload_call()
  ../vendor/composer/ClassLoader.php (322) calling Composer\Autoload\includeFile()
  ../vendor/composer/ClassLoader.php (444) calling include()
  ../vendor/symfony/dependency-injection/Loader/PhpFileLoader.php (24) calling spl_autoload_call()
  ../vendor/composer/ClassLoader.php (322) calling Composer\Autoload\includeFile()
  ../vendor/composer/ClassLoader.php (444) calling include()
====================END BACKTRACE====================
```

**How to reproduce**  
When using the Dependency Injection FileLoader class, have any code that calls the `import()` method.

**Possible Solution**  
Add types to the DI FileLoader class. **It's possible this could be an issue for the entire package, or maybe it's only scoped to this file.**

**Additional context**  
The project in which this was discovered was using Symfony as a non-standard install; i.e. not using Symfony Kernel, and leveraging packages individually.

**Comment by derrabus** [comment]
What version of PHP are you using?

**Comment by CoeusCC** [comment]
I was about to say 7.3, but I double-checked and I would have been wrong. It looks like a dev environment had been wiped and the version was rolled back. Apologies. I will close this since it's a configuration error, not a code error.

**Comment by derrabus** [comment]
We did not add the type declarations to `symfony/dependency-injection` 5.0, so the package could remain compatible with `symfony/config` 4.4. In the meantime, we've dropped support for the 4.4 package, so we could add the declarations now.
