### ISSUE TITLE
Symfony Yaml 5.2 does not handle space after a quote.

### ISSUE THREAD

**Issue by Xachman** [symfony/symfony#39296]
**Symfony version(s) affected**: 5.2

**Description** 
If you parse valid yaml with a space after a quote you will receive the error:

```
Unexpected characters near " space after the quote" " at line 1 (near "test: "anything with a space after the quote" ").
```

**How to reproduce**  

Parse any valid yaml that uses quotes for a value and has a space at the end.

Example:

```
\Symfony\Component\Yaml\Yaml::parse("test: 'a one line quote test' ");
```

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Thank you for the report. This is already fixed by #39274 which will be part of the next release.

**Comment by Xachman** [comment]
Thank you @xabbuh!  Should switching to 5.x-dev give you this update?

**Comment by derrabus** [comment]
5.2-dev should work as well.
