### ISSUE TITLE
Symfony/Form validation before putting values into entity

### ISSUE THREAD

**Issue by piotrp321** [symfony/symfony#39303]
Hello,

Is it possible to return form validation errors before values are assigned to entities?
I am using typed properties PHP 7.4 and the values are assigned before validation and I get errors that I try to insert null into a field that cannot be null.

**Comment by ro0NL** [comment]
the underlying model is first hydrated, then the model is validated.

put different, you are forced to account for invalid state at the model layer.

the way i do this is using `array` (no data_class) for a model, along with `constraints` option per field.

Then hydrate some model myself during POST_SUBMIT and if $form->isValid()
