### ISSUE TITLE
The class 'DateTime' was not found in the chain configured namespaces App\Entity since update to doctrine/orm 2.8

### ISSUE THREAD

**Issue by fabien007** [symfony/symfony#39312]
**Symfony version(s) affected**: 5.1

**Description**  
Since I updated to doctrine/orm 2.8 i got this error
"The class 'DateTime' was not found in the chain configured namespaces App\Entity"
When i do a query->getResult();

**How to reproduce**  
Do a query->getResult(); with doctrine/orm 2.8 maybe with entity fields of type datetime

**Possible Solution**  

**Additional context**

**Comment by stof** [comment]
should be reported to the doctrine/orm project if that's an issue happening when updating the ORM.

**Comment by AxelBriche** [comment]
Same problem here.

**Comment by derrabus** [comment]
doctrine/orm#8369
