### ISSUE TITLE
Console progress bar broken in PhpStorm

### ISSUE THREAD

**Issue by amcsi** [symfony/symfony#39314]
**Symfony version(s) affected**: >=5.1.0; more specifically this is the first bad commit based on my bisect: https://github.com/symfony/console/commit/7d292dc7044160e5ea54c7620d02b4cdfeb54163

OS: Ubuntu 20.04
PHP version: 7.4
PhpStorm version: 2020.2.4 and 2020.3

**Description**  
When running a console command in the PhpStorm run window in Symfony, the progress bar as it advances shows up one after the other on the same line:

```
/usr/bin/php7.4 /home/attila/0/quick/console/attila-test.php
  0/50 [>---------------------------]   0%  1/50 [>---------------------------]   2%  2/50 [=>--------------------------]   4%  3/50 [=>--------------------------]   6%
```

Rather than overwriting the line to work as expected:

```
/usr/bin/php7.4 /home/attila/0/quick/console/attila-test.php
  3/50 [=>--------------------------]   6%
```

**How to reproduce**  

attila-test.php
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;

// creates a new progress bar (50 units)
$consoleOutput = new ConsoleOutput();
$consoleOutput->setDecorated(true);
$progressBar = new ProgressBar($consoleOutput, 50);

// starts and displays the progress bar
$progressBar->start();

$i = 0;
while ($i++ < 50) {
    // ... do some work

    sleep(1);
    // advances the progress bar 1 unit
    $progressBar->advance();

    // you can also advance the progress bar by more than 1 unit
    // $progressBar->advance(3);
}

// ensures that the progress bar is at 100%
$progressBar->finish();

```

**Additional context**  
![image](https://user-images.githubusercontent.com/116494/101207107-6a255280-3670-11eb-9760-d5621404b590.png)

**Comment by aivchen** [comment]
Couldn't replicate it. Show a screenshot of Settings - Tools - Terminal window.

**Comment by amcsi** [comment]
@aivchen you are running it with a Run configuration in PhpStorm, right? The issue is not in Terminal; it's fine there. The problem only happens when running the script with PhpStorm's Run window.

(And I tried without the Grep Console plugin enabled as well, in case you'd be suspecting that. The issue still happens.)

![image](https://user-images.githubusercontent.com/116494/101243514-2b8ba880-3701-11eb-97c9-a9b63b4c1b11.png)

In any case, I will provide my Terminal configuration as well since you asked for it. Though I think it's not relevant:

![2020-12-05_13-47](https://user-images.githubusercontent.com/116494/101243518-3f370f00-3701-11eb-8a76-484675c73d17.png)

**Comment by amcsi** [comment]
@aivchen have you been able to try this out in the Run tab? This is still an issue FYI.

**Comment by aivchen** [comment]
Sorry for the late response. Yes, I was able to replicate it. But it's not a Symfony/Console bug. It's a PhpStorm bug: https://youtrack.jetbrains.com/issue/IDEA-244814
