### ISSUE TITLE
[Security] Add a debug:firewall command

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#39321]
This is an idea that we while looking at https://github.com/symfony/symfony/pull/39276 

A `debug:firewall` in the first place would show all listeners for security events, allowing you to quickly have an overview of what listeners are configured on the firewall. We can add many more useful information to this command, some suggestions:

- Configured authenticators
- Entry point
- Allowed badges (maybe derive from the registered listeners)

**Comment by TimoBakx** [comment]
For the working of this command: Perhaps a list of available firewalls if used without any options/arguments.
And be able to specify a firewall to get more information (events, authenticators, badges, entry point)?

**Comment by wouterj** [comment]
Yes,that's an excellent idea @TimoBakx!

**Comment by TimoBakx** [comment]
I'd love to work on this for the #SymfonyHackday.
