### ISSUE TITLE
[PhpUnitBridge] Broken with PHPUnit 9.5

### ISSUE THREAD

**Issue by sanmai** [symfony/symfony#39329]
**Symfony version(s) affected**: v5.2.0

**Description**  

PhpUnitBridge's CoverageListenerTrait is incompatible with PHPUnit 9.5, probably due to [missing/inaccessible `getAnnotations()` method](https://github.com/symfony/phpunit-bridge/blob/92a76ca5e64effd41ce111b8f476144dfa29f1f0/Legacy/CoverageListenerTrait.php#L45).

**How to reproduce**  

Example of [a build with the error](https://github.com/FriendsOfPHP/PHP-CS-Fixer/runs/1503268631#step:9:17):
```
 PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.13
Configuration: /home/runner/work/PHP-CS-Fixer/PHP-CS-Fixer/phpunit.xml.dist
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing 
Call to undefined method PhpCsFixer\Tests\AbstractFixerTest::getAnnotations()
Error: Process completed with exit code 2.
```

[And another.](https://github.com/infection/infection/pull/1452/checks?check_run_id=1503353661#step:7:13)

**Workaround**  

Use PHPUnit 9.4.

**Comment by derrabus** [comment]
I'll look into it. In the meantime, you can use PHPUnit 9.4. It should work fine. 🤞🏻
