### ISSUE TITLE
[Mailer] Symfony 5.2 DkimSigner not working (DKIM lookup failure)

### ISSUE THREAD

**Issue by zerrrr** [symfony/symfony#39354]
Hello everyone,

I've just upgraded my Symfony projet from 5.0 to 5.2 because I needed to DKIM sign my emails (thanks to @fabpot).

I basically followed documentation by implementing my signature on my mail like that :

```php
$email = (new TemplatedEmail())
         ->from(new Address('noreply@domain.com', 'Noreply'))
         ->to($userEmail)
         ->subject('Subject')
         ->text('My email text format')
         ->htmlTemplate('email.html.twig')
         ->context([
            ...
         ]);

$signer = new DkimSigner(
    'file://'.dirname(__DIR__).'/../'.$this->getParameter('private_key_filename'),
    $this->getParameter('domain_name'),
    $this->getParameter('selector')
);
$signedEmail = $signer->sign($email);

$mailer->send($signedEmail);
```

I also tried by getting content :

```php
$signer = new DkimSigner(
    file_get_contents(dirname(__DIR__).'/../'.$this->getParameter('private_key_filename')),
    $this->getParameter('domain_name'),
    $this->getParameter('selector')
);
```

I still have "body has been altered" when using multiple DKIM lookup and the test fail.

I don't think there is a problem in charging the private key file because I first had those kind of errors that I fixed by adding the "/../" on the path.

I've set the public key on my DNS with TXT record and domain `selector._domainkey.domain.com` like that :

`v=DKIM1;k=rsa;p=mypublickey`

I don't think this is a problem of key integrity because I used openssl to generate the private and public keys :

```
openssl genrsa -out private.key 1024
openssl rsa -in private.key -pubout -out public.key
```

And I can't sign my email by using my SMTP server because I'm having a mutualized offer and I can't change server configurations.

Did I miss something ?

Thank you for your time and I hope someone had the same problem !

**Comment by zerrrr** [comment]
**UPDATE :**

Even after trying to put the private key as text on a variable like in the DkimSignerTest.php test file of the commit (https://github.com/symfony/symfony/pull/37165/files), it is not working :

```
$pk = <<<EOF
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
EOF;
```

**Comment by zerrrr** [comment]
**UPDATE :** 

I found something strange when the DKIM part of the code is used : 

```php
$signer = new DkimSigner(
    'file://'.dirname(__DIR__).'/../'.$this->getParameter('private_key_filename'),
    $this->getParameter('domain_name'),
    $this->getParameter('selector')
);

$signedEmail = $signer->sign($email);
```

- It seems that textTemplate() **AND** htmlTemplate() are not working when used together : _Email is not sending_
- So I replaced textTemplate() by text() function instead. When there is text() **AND** htmlTemplate() function, the htmlTemplate() seems to not working anymore : _Email is always sending in text format only_
- So I tried to remove text() function and leave only htmlTemplate() : _Email is not sending at all_

```php
$email = (new TemplatedEmail())
         ->from(new Address('noreply@domain.com', 'Noreply'))
         ->to($userEmail)
         ->subject('Subject')
         **->text(**'My email text format')
         **->htmlTemplate(**'email.html.twig')
         ->context([
            ...
         ]);
```

I decided to completely remove DKIM part on my code for now, and my email can be sent with textTemplate() (or text()) **AND** htmlTemplate() with html template as a result and text format if asked...

Am I doing something wrong or is it a bug of the DkimSigner feature ?

**Comment by stof** [comment]
`textTemplate()` and `htmlTemplate()` need to be resolved by the BodyRenderer (hooked into a listener). And signing needs to happen after the body rendering is done.

so I think that to make the DKIM signing compatible with TemplatedEmail, the signing should happen in a listener (at lower priority than the body rendering) instead of being done before calling `Mailer::send`.
what do you think @fabpot ?

**Comment by zerrrr** [comment]
Thanks for your reply @stof, I tried to do as you told : 

```
$email = (new TemplatedEmail())
         ->from(new Address('noreply@domain.com', 'Noreply'))
         ->to($userEmail)
         ->subject('Subject')
         ->textTemplate('email_text.txt.twig')
         ->htmlTemplate('email.html.twig')
         ->context([
            ...
         ]);

//with $environment is an instance of Twig\Environment injected
$renderer = new BodyRenderer($environment);
$renderer->render($email);

$signer = new DkimSigner(
            'file://'.dirname(__DIR__).'/../'.$this->getParameter('private_key_filename'),
            $this->getParameter('domain_name'),
            $this->getParameter('selector')
        );
$signedEmail = $signer->sign($email);

$mailer->send($signedEmail);
```

By adding the BodyRenderer before signing, it resolved the html display problem of textTemplate() and htmlTemplate() together. But the DKIM signature is still in failure...

**Comment by comp64** [comment]
+1 vote for fixing this issue. Signing the TemplatedEmail does not currently work as in the examples.
TemplatedEmail is in the unrendered state, which results in an empty getBody() when trying to sign it.
If instead you try to render it as @zerrrr proposed, the email gets signed, but then it re-renders upon sending and it breaks the integrity.

My workaround is as @stof suggests - signing in a listener that gets called after the MessageListener.

**Comment by comp64** [comment]
Also investigated this further. The signing in a listener only worked for me in the dev env.

There is a huge underlying problem with the Email class itself which regenerates the mail body, and in this case - multipart boundary random string. This causes the signature to become corrupted after signing, on the way to the transport.
Solution to this would include somehow freezing the email body, for example by returning a fully generated RawMessage from the sign() method.

There is another problem related to signing in a listener / subscriber, as the Message carried in MessageEvent is immutable (but the Envelope is mutable). So after the MessageEvent is dispatched and handled, the AbstractTransport doesn't care about $event->getMessage() and only uses the original message. The way DkimSigner works requires mutation in the event / loading the mutated message in the AbstractTransport.

The DKIM signing is clearly not yet mature. But to be constructive, I can help with a fix.

**Comment by metaer** [comment]
I confirm this issue. My temporary solution is to use swiftmailer bundle using plugin (which implements Swift_Events_SendListener) to sign email.

UPD: my temporary solution not actual anymore: https://symfony.com/blog/the-end-of-swiftmailer

**Comment by EriCreator** [comment]
@metaer  can you share the code of your temporary solution?
I seem to have a similar problem with the DkimSigner

**Comment by metaer** [comment]
> @metaer can you share the code of your temporary solution?
> I seem to have a similar problem with the DkimSigner

@EriCreator for this temporary solution I used swift-mailer bundle: https://symfony.com/doc/current/email.html#installation

Here is my service defenition for custom swift mailer signer plugin for default mailer:

```yaml
App\SwiftMailerPlugins\SwiftMailerSignerPlugin:
    tags:
        - { name: swiftmailer.default.plugin }
```

where `default` can be replaced with your alternative mailer if you use multiple swiftmailer services:
```
swiftmailer.mailer.default
swiftmailer.mailer.your_second_mailer
```

My custom signer plugin class code example:
```php
<?php

namespace App\SwiftMailerPlugins;

use App\Service\ParametersProvider;
use Swift_Events_SendEvent;
use Swift_Events_SendListener;
use Swift_Message;
use Swift_Signers_DKIMSigner;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Contracts\Service\Attribute\Required;

class SwiftMailerSignerPlugin implements Swift_Events_SendListener
{
    #[Required]
    public ParametersProvider $parametersProvider;

    public function beforeSendPerformed(Swift_Events_SendEvent $evt)
    {
        /** @var Swift_Message $swiftMessage */
        $swiftMessage = $evt->getMessage();

        if (!$swiftMessage instanceof Swift_Message) {
            return;
        }

        $privateKeyFilePath = $this->parametersProvider->getParameter('kernel.project_dir').'/dkim/dkim_private_example.pem';
        $filesystem = new Filesystem();

        if (!$filesystem->exists($privateKeyFilePath)) {
            return;
        }

        $domainName = 'example.com';
        $selector = 'selector';
        $signer = new Swift_Signers_DKIMSigner("file://$privateKeyFilePath", $domainName, $selector);
        $swiftMessage->attachSigner($signer);
    }

    public function sendPerformed(Swift_Events_SendEvent $evt)
    {
    }
}
```

Sending message example:
```php
$message = (new \Swift_Message())
    ->setFrom($from)
    ->setTo($to)
    ->setSubject($subject)
    ->setBody($body, 'text/html')
;

$result = $defaultSwiftMailer->send($message);
```

Usefull links:
https://symfony.com/doc/current/reference/dic_tags.html#swiftmailer-default-plugin
https://swiftmailer.symfony.com/docs/plugins.html
https://symfony.com/doc/current/reference/configuration/swiftmailer.html

**Comment by EriCreator** [comment]
It's indeed working this way. Thank you so much for helping @metaer !!

**Comment by kriskoch** [comment]
I am having this same issue. I really want to use the mailer component, but the templated email just doesnt work with DKIM signing.  spent a couple hours yesterday rewriting my mailer wrapper to switch from switft mailer to this and debugging why it wasnt working, and now it looks like I will have to revert it back unfortunately.

**Comment by kriskoch** [comment]
Ok, so I was able to get it working in a hackish way, unforunetly it requires a 1 line change in the symfony code.

First I set up my own custom Listener:
Here are the two important functions in the listener
```php
    public static function getSubscribedEvents()
    {
        return [
            MessageEvent::class => [['onMessage', -40]],
        ];
    }

    public function onMessage(MessageEvent $event)
    {
        $eventMessage = $event->getMessage();
        $signer       = new DkimSigner('file://'.$this->dkimKeyFile, $this->dkimDomain, $this->dkimSelector);

        $message = new Message($eventMessage->getPreparedHeaders(), $eventMessage->getBody());
        $signed  = $signer->sign($message);
        $event->setMessage($signed);

    }
```

Priority must be in the negative so this listener runs after template rendering.
2nd I havent investigated why but you need to create a new message out of the existing message. If you try to use the existing message it fails dkim.


Now there needs to be a change in vendor/symfomy/mailer/Transport/AbstractTransport.php
As you can see in previous code we set the message on the event, however the AbstractTransport doesnt use it, it uses the one that was passed into the function.
So in the send function you need to change the line from
`
 $message = new SentMessage($message, $envelope);`
to

` $message = new SentMessage($event->getMessage(), $envelope);`


This now worked and passed DKIM verification. However this solution isnt really valid since it requires a modification to the vendor code.
Hopefully someone can use this to hopefully come up with a PR to fix.

**Comment by metaer** [comment]
One more thing.
if you have multiple transports - you should pass
```php
['headers_to_ignore' => ['x-transport']]
```
into the second parameter of `sign` method.

If you do not - signature will contain X-Transport:
`h=From: Subject: To: X-Transport: MIME-Version: Date: Message-ID;`

But email will not:
https://github.com/symfony/symfony/blob/810599d2f0fd19558d140c19bc50eb4dc0021a2e/src/Symfony/Component/Mailer/Transport/Transports.php#L56

And signature will not pass checking.

I think it should be added to the documentation.

UPD: this should be fixed in the code, not in the docs: https://github.com/symfony/symfony-docs/pull/15603#issuecomment-895206311
UPD-2: Fixed in https://github.com/symfony/symfony/pull/42659

**Comment by metaer** [comment]
@zerrrr There is another temporary solution.
You can use `\Twig\Environment::render` method for rendering body from the template before signing, and use `new Email()` instead of `new TemplatedEmail()`

```php
$email = (new Email())
    ->from($from)
    ->to($to)
    ->subject($subject)
    ->html($this->twig->render('emails/email.html.twig'))
;
```
In this case DKIM signature is going to be valid

**Comment by kriskoch** [comment]
Yeah, that works as well. The only thing this loses is not having access to
the special 'email' function for embedding images/attachments.

Was thinking could do it yourself by   'email' => new
WrappedTemplatedEmail($twig, $email). but $email needs to be instance of TemplatedEmail which it wouldnt be.
The unfortunate part is WrappedTemplatedEmail constructor doesnt even need it to be a TemplatedEmail, the Email class is enough, but it is a final class so cant extend it. I guess I could copy & paste it into my own class.

**Comment by metaer** [comment]
Swiftmailer [is not going to be maintained](https://symfony.com/blog/the-end-of-swiftmailer) after November 2021, so [this temporary solution](https://github.com/symfony/symfony/issues/39354#issuecomment-872944978) is not actual anymore.

**Comment by FranzBruckner** [comment]
I just came across this issue which still exists.

To summarize:
**Issue 1 TemplatedEmail ist not rendered when we want DkimSigner to sign it.**

```php
// Workaround #1 render html manually
$email = (new TemplatedEmail());
$args['email'] = new WrappedTemplatedEmail($this->twig, $email);
$email->html($this->twig->render($templatePath, $args));
// ... sign & send
```

**Issue 2 DKIM is not working for multipart-message (e.g. html and txt)**
The above workaround could be easily changed to the following, so that the txt-part and all embedded images would be set properly.
```php
// Workaround #2 for multipart-emails (NOT WORKING!)
$email = (new TemplatedEmail())
    ->context($args)
    ->htmlTemplate($templatePath);
(new BodyRenderer($this->twig))->render($email);
// ... sign & send
```

It seems that the (already signed) multipart e-mail gets changed before it is sent. These changes leads to failing DKIM signature-checks.

I am not experienced enough with the application-flow of the mailer-component.
So unfortunately I'm not able to bring in some proposals for solution at the moment.

**Comment by fischel** [comment]
Yesterday I spent hours of trying to send html-emais with dkim by symfony/mailer until I found this issue. :(

So, the bug still exists. If you send a text-mail the dkim pass will be valid, but if you send a multipart-message the dkim pass will be fail.

I tested this with symfony 5.2, 5.3. and 5.4.

**Comment by fischel** [comment]
> @zerrrr There is another temporary solution. You can use `\Twig\Environment::render` method for rendering body from the template before signing, and use `new Email()` instead of `new TemplatedEmail()`
> 
> ```
> $email = (new Email())
>     ->from($from)
>     ->to($to)
>     ->subject($subject)
>     ->html($this->twig->render('emails/email.html.twig'))
> ;
> ```
> 
> In this case DKIM signature is going to be valid

I think you're wrong

**Comment by cedgex** [comment]
Hi,
Same problem, symfony 5.4.
if I send email html only it's work.
if I send html +txt not work
if I send html only but with a embedFromPath is not working to....

use twig is not working

**Comment by calebsolano** [comment]
I have investigated this for hours now and can not seem to find any way to get a passing DKIM signature for multi-part emails. 

Text Only = PASS
HTML Only = PASS
Text + HTML = FAIL
Text + Attachments = FAIL

My instincts tell me it has something to do with the multipart boundary, in particular with it being random...but I can't determine where in the code it instantiates a second one that would have a different value between creating the body hash and the actual body

**Comment by ghost** [comment]
I suggested a PR to fix the issue: https://github.com/symfony/symfony/pull/46863.
