### ISSUE TITLE
Update translations with concatenated strings

### ISSUE THREAD

**Issue by galatea-nl** [symfony/symfony#39351]
**Symfony version(s) affected**: 4.4

**Description**  
Extraction translations from Twig fail to extract concatenated strings

**How to reproduce**  
use the translation:update command on a template like this:
```{{ ('aa' ~ 'bb')|trans }}```

**Possible Solution**  
change the TranslationNodeVisitor so it gets the concatenated strings

**Comment by JohJohan** [comment]
I can confirm this works on `4.4.17` i just tested it.
