### ISSUE TITLE
[PHPUnitBridge] Autoloading issue

### ISSUE THREAD

**Issue by villfa** [symfony/symfony#39376]
**Symfony version(s) affected**: 5.2.0
Previous versions are most certainly affected too, depending on the context.

More context:
* PHP 7.4
* PHPUnit 8.3.5
* [PHPCPD 6.0.3](https://packagist.org/packages/sebastian/phpcpd)

**Description**  

Using *PHPUnit-Bridge* and *PHPCPD* at the same time leads to an autoloading issue.
PHPUnit and PHPCPD share a common dependency: [phpunit/php-timer](https://packagist.org/packages/phpunit/php-timer)
The problem is that when PHPUnit runs it loads its own dependencies from the wrong `vendor/` dir and, in my case, tries to use an incompatible version of php-timer.

**How to reproduce**  

Bug reproducer: https://github.com/villfa/test-phpunit-timer.

**Possible Solution**  

**Additional context**  

```
$ vendor/bin/simple-phpunit

No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-8.3-1"
Installing phpunit/phpunit (8.3.5)

[...]

PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.13
Configuration: /home/runner/work/test-phpunit-timer/test-phpunit-timer/phpunit.xml
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/phpunit/php-timer/src/Timer.php:24
Stack trace:
#0 /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/bin/.phpunit/phpunit-8.3-1/src/Framework/TestResult.php(659): SebastianBergmann\Timer\Timer::start()
#1 /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/bin/.phpunit/phpunit-8.3-1/src/Framework/TestCase.php(680): PHPUnit\Framework\TestResult->run()
#2 /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/bin/.phpunit/phpunit-8.3-1/src/Framework/TestSuite.php(568): PHPUnit\Framework\TestCase->run()
#3 /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/bin/.phpunit/phpunit-8.3-1/src/Framework/TestSuite.php(568): PHPUnit\Framework\TestSuite->run()
#4 /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/bin/.phpunit/phpunit-8.3-1/src/TextUI/TestRunner.php(616): PHPUnit\Framework\TestSuite->run()
#5 /home/runner/work/test-phpunit-timer/tes in /home/runner/work/test-phpunit-timer/test-phpunit-timer/vendor/phpunit/php-timer/src/Timer.php on line 24

Testing unit-tests

Unsilenced deprecation notices (1)

  1x: Non-static method SebastianBergmann\Timer\Timer::start() should not be called statically
    1x in TestResult::run from PHPUnit\Framework

Error: Process completed with exit code 255.
```

**Comment by derrabus** [comment]
The problem would probably go away for now if you upgraded to PHPUnit 9 or if you installed PHPCPD as a PHAR instead of pulling it via composer.

We can't do much about this issue, I guess. You would pretty much run into the same problem if you ran PHPUnit 8.3 from the official PHAR. The combination PHPCPD and PHPUnit version that you're trying to use is incompatible if you try to load both of them at the same time.

**Comment by nicolas-grekas** [comment]
Might be solved by #39387, isn't it?

**Comment by derrabus** [comment]
I don't see how. 🤔

**Comment by nicolas-grekas** [comment]
With the envisioned env var, phpcpd could be installed inside the vendor/ dir *of the bridge*.
Then a symlink would be required to give the phpcpd entry script a nicer name.

**Comment by nicolas-grekas** [comment]
Anyway, your first answer is correct. Closing therefor.

**Comment by derrabus** [comment]
I'm a bit afraid of turning PhpUnitBridge into a general-purpose tool installer, I must admit. 😅
