### ISSUE TITLE
please make array validation easier.

### ISSUE THREAD

**Issue by vidyli** [symfony/symfony#39372]
it is very handy to [validate raw array](https://laravel.com/docs/8.x/validation#creating-form-requests) in Laravel, it would be great if Symfony also has this feature.

# Validate  raw array in Laravel
```
$request->validate([
    'title' => 'required|unique:posts|max:255',
    'author.name' => 'required',
    'author.description' => 'required',
]);
```

# [Validate raw array in Symfony](https://symfony.com/doc/current/validation/raw_values.html)
lots of boilerplate code.

```
groups = new Assert\GroupSequence(['Default', 'custom']);

$constraint = new Assert\Collection([
    // the keys correspond to the keys in the input array
    'name' => new Assert\Collection([
        'first_name' => new Assert\Length(['min' => 101]),
        'last_name' => new Assert\Length(['min' => 1]),
    ]),
    'email' => new Assert\Email(),
    'simple' => new Assert\Length(['min' => 102]),
    'eye_color' => new Assert\Choice([3, 4]),
    'file' => new Assert\File(),
    'password' => new Assert\Length(['min' => 60]),
    'tags' => new Assert\Optional([
        new Assert\Type('array'),
        new Assert\Count(['min' => 1]),
        new Assert\All([
            new Assert\Collection([
                'slug' => [
                    new Assert\NotBlank(),
                    new Assert\Type(['type' => 'string'])
                ],
                'label' => [
                    new Assert\NotBlank(),
                ],
            ]),
            new CustomUniqueTagValidator(['groups' => 'custom']),
        ]),
    ]),
]);

$violations = $validator->validate($input, $constraint, $groups);
```
life is too short to waste time on this.

**Comment by fd6130** [comment]
Wow... i didn't know laravel validate are easy like this. Indeed laravel won this point in validation part.

And even though symfony validations are longer and make our life harder but it provide flexibility and customization capability for us.

**Comment by ro0NL** [comment]
what's the proposed way of doing it then?

**Comment by wouterj** [comment]
Hi @vidyli! Thanks for this issue.

You're correct that Symfony is a bit more verbose. However, it's not as extreme as you show in the issue description. The Symfony example is validating a nested associative array with way more fields. :smile: 

The Laravel example in Symfony is like this (except that we currently don't have a way to validate unique items like this, feel free to contribute if you need it):

```php
$requestData = $request->request->all();
$validator->validate($requestData, new Collection([
    'title' => new All([new NotBlank(), new Length(['max' => 255])]),
    'author' => new Collection([
        'name' => new NotBlank(),
        'description' => new NotBlank(),
    ]),
]));
```

As you can see, it's not a lot more verbose, just a little.

I would argue that we shouldn't change things here, the difference is mainly the typical Laravel string format (`<function>:<args>|...<function>:<args>`), which is not something used in the Symfony framework (instead of using plain PHP, which imho is a win). And `$request->validate()` sounds nice at first, but is only possible with service location, which is a design pattern that Symfony is trying to avoid.

However, if you have a great idea to make this easier to use, I would like to learn about it :)

**Comment by vidyli** [comment]
you know, we can define validation rules in yaml, but it forces us to create an object.   for example. 

```
App\Command\AddAuthorCommand:
    getters:
        title:
            - NotBlank: ~
        author:
            - Collection: 
                name:
                    - NotBlank: ~
                description:
                    - NotBlank: ~
```

below is the equivalent array version  without object, also no need to repeat `new Assert\XXX()`. 
```
$violations = $validator->validate(
    $request->request->all(), 
   [
        'title' => [
            'NotBlank'
        ]，
        'author' => [
            'Collection' => [
                'name' => [
                    'NotBlank',
                ],
                'description' => [
                    'NotBlank',
                ],
        ],
    ], , 
    $groups
);

```

this doesn't change too much,  is still tedious.  then we can suport a concise way which is similar to Laravel's,   the concise way  covers Symfony constraint major options, this should cover most use cases, In terms of rare cases, we can fallback to the tedious way.

**Comment by siganushka** [comment]
My opinion is that request should not be coupled with validate，I agree @wouterj

**Comment by fd6130** [comment]
> My opinion is that request should not be coupled with validate，I agree @wouterj

Put validation in DTO?

**Comment by xabbuh** [comment]
I honestly do not see this being implemented in the Validator component. If someone wants to give this a try though, the proposed syntax from the issue description could be implemented in a different package which interprets that syntax and calls the Symfony validator then. So I am closing here. Thank you for understanding.
