### ISSUE TITLE
[PhpUnitBridge] Enable Prophecy integration via env variable

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#39387]
**Description**  
PHPUnit's built-in Prophecy integration is deprecated and will be removed soon. The replacement package `phpspec/prophecy-phpunit` however only works with PHPUnit 9.

Maybe we can have `simple-phpunit` install that package if we're running PHPUnit 9 and a yet to be defined environment variable is set.

**Comment by nicolas-grekas** [comment]
Like `SYMFONY_PHPUNIT_REQUIRE` to mirror `SYMFONY_PHPUNIT_REMOVE`?

**Comment by derrabus** [comment]
Yes something like that. But with the extra constraint that `phpspec/prophecy-phpunit` will only be installed for PHPUnit 9.1 and above and assumed to be present if we're on a lower PHPUnit version.

**Comment by nicolas-grekas** [comment]
We do remove prophecy by default in the bridge...
I'd better not do any fancy logic here...

**Comment by acasademont** [comment]
This would be great! Right now we have a ton of deprecation messages when using phpunit 9.4 provided by the bridge that we can't really fix.

PS: Unless we require `phpspec/prophecy-phpunit` directly on our composer, which is not really desirable as it will install phpunit as a dependency
