### ISSUE TITLE
Symfony Forms `form_div_layout.html.twig` rendering useless checkboxes and radio buttons

### ISSUE THREAD

**Issue by I-Valchev** [symfony/symfony#39397]
**Symfony version(s) affected**: Any `symfony/form` version.

**Description**  
The default `form_div_layout.html.twig` renders checkboxes and radio buttons without the label for the specific option. This renders this type of input _**completely**_ useless. The problem seems to be here:

https://github.com/symfony/twig-bridge/blob/5c808411b699dbad72f8540b8f9e6b1fe0ca95ca/Resources/views/Form/form_div_layout.html.twig#L93-L95

What type of user can select a radio/checkbox without a text description?!

**How to reproduce**  

**Possible Solution**  
Fix it so that it includes the {{ value }} or pretty value (as with the regular select)

**Comment by derrabus** [comment]
Thank you very much for your friendly bug report. I'm sorry to hear that the HTML that was rendered for you did not meet your expectations.

Can you please provide steps to reproduce your problem, or better provide a small application that allows us to reproduce your bug?

**Comment by ro0NL** [comment]
widget and label are different components: https://symfony.com/doc/current/form/form_themes.html#form-fragment-naming

probably an implementation problem :)

**Comment by I-Valchev** [comment]
Thank you both for the responses. I've tried to reproduce it without success, so let's close this one for now. If the issue comes up again, I'll detail in more thoroughly.
