### ISSUE TITLE
Symfony binary tries to create 5.3 version of symfony which is not yet released

### ISSUE THREAD

**Issue by anuri73** [symfony/symfony#39396]
**Symfony version(s) affected**: 5.3

**Description**  
On trying to create new symfony project using [symfony binary](https://symfony.com/download) it tries to create with 5.3 version, which is not yet released.

**How to reproduce**  
1. Download new binary
2. Create new project: `symfony new symfony5-sample --version=next`

**Additional context**  
PHP version:
```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```
![image](https://user-images.githubusercontent.com/5062812/101617073-5f850780-3a3a-11eb-931b-c95fb12b6b58.png)

**Comment by derrabus** [comment]
With `--version=next` you literally tell the CLI to use an unreleased version of Symfony.
