### ISSUE TITLE
[Form] [Uid] Error on invalid uid submitted

### ISSUE THREAD

**Issue by geoffrey-brier** [symfony/symfony#39407]
**Symfony version(s) affected**: 5.2 (symfony/uid + symfony/form)

**Description**  
Hello,

I am using the newly shipped uid component :rocket: (great work btw) and implementing tests.

I have :
* a Product with a uuid as a primary key
* a form type having a product field which is an EntityType

When I submit the form with an invalid uid, it throws an exception causing a 500 which is not really friendly.

**How to reproduce**  

**Possible Solution**  
Would it be possible to have the same behaviour as any other choicetype so that we can have a 400 with an invalid error message ?

**Additional context**  
![sf-uid-500](https://user-images.githubusercontent.com/1224811/101634684-55a6d880-3a29-11eb-8111-1f87c899c5c0.png)

**Comment by jderusse** [comment]
`60b6693f-d6c4-454a-a1bf-804b681b3e6` is not a valid UUID, I don't know how you end up with such value in your database but on character is missing here.

**Comment by geoffrey-brier** [comment]
Yes I know @jderusse , I am submitting voluntarily an invalid data. On the database side everything is correct.

**Comment by stof** [comment]
this is the same kind of issue than https://github.com/symfony/symfony/issues/17488 (except that this one is an error thrown by Postgresql itself and not the DBAL layer).

**Comment by jderusse** [comment]
I submitted a PR to fix it.
I'm not sure this should be addressed exactly as #17488: I agree to silent and ignore it blank value, but in case the value is invalid, I suggest to throw a proper exception in order to display a message to the end-user

**Comment by geoffrey-brier** [comment]
I agree to that as well.
Thanks a lot for the quick fix @jderusse

**Comment by pluk77** [comment]
Is there some way that the hard-coded type-check `(\in_array($type, ['ulid', 'uuid', 'guid']))` can be removed so that it relies (more)  on the `Type::hasType($type)` check?

Reason for asking is that besides the normal uuid, there are other custom doctrine types that require conversion (like uuid_binary) and current we need to overwrite the whole class and create an extended EntityType in order to add uuid_binary to the hard-coded if statement.
