### ISSUE TITLE
[Doctrine Bridge] RegisterUidTypePass relies on non-existent parameter "doctrine.dbal.connection_factory.types"

### ISSUE THREAD

**Issue by craue** [symfony/symfony#39400]
**Symfony version affected**: 5.2.0

**Description**
While updating a bundle I noticed that running tests with Symfony 5.2 raised this error.

**How to reproduce**
If `dbal` is not explicitly enabled by config, DoctrineBundle's `DoctrineExtension` won't [set `doctrine.dbal.connection_factory.types`](https://github.com/doctrine/DoctrineBundle/blob/2.2.2/DependencyInjection/DoctrineExtension.php#L117). `RegisterUidTypePass` [tries to access it anyway](https://github.com/symfony/symfony/blob/v5.2.0/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterUidTypePass.php#L31).

**Additional context**
[installed dependencies](https://travis-ci.org/github/craue/CraueFormFlowBundle/jobs/748517984#L451)
[error log](https://travis-ci.org/github/craue/CraueFormFlowBundle/jobs/748517984#L538)

**Comment by stof** [comment]
the compiler pass should check for the parameter and become a no-op if not there. If DBAL is not configured, there is no need to register the uid type.
