### ISSUE TITLE
DateType selects rendered with unwanted characters if format is set dd-MM-yyyy

### ISSUE THREAD

**Issue by benstinton** [symfony/symfony#39415]
**Symfony version(s) affected**: 4.4, 5.2

**Description**  
If you set a 'format' in the DateType such as 'dd-MM-yyyy' and the field is rendered as select boxes then dashes (i.e. '-') appear between the select boxes.

**How to reproduce**  
With a DateType set 
`'format' => 'dd-MM-yyyy'`

**Possible Solution**  
In DateType the date_pattern is created with regex that converts groups of d M Y to {{ day }} {{ month }} {{ year}}. 
The string is not being cleaned as expected.

           
```
            // remove special characters unless the format was explicitly specified
            if (!\is_string($options['format'])) {
                // remove quoted strings first
                $pattern = preg_replace('/\'[^\']+\'/', '', $pattern);

                // remove remaining special chars
                $pattern = preg_replace('/[^yMd]+/', '', $pattern);
            }

```
I think we need to remove the exclamation mark as this code is intended to be run on strings, but can currently only be run on non strings. Format can be a string or an int

**Additional context**

**Comment by benstinton** [comment]
I'd be happy to create a patch if you agree with my possible solution

**Comment by derrabus** [comment]
Hello and thank you for your bug report.

Unfortunately, we are not maintaining Symfony 2.3 anymore, as you can see on https://symfony.com/releases

Please upgrade your application to a maintained version of Symfony. If you still encounter this bug after the upgrade, please don't hesitate to file a new bug report.

**Comment by benstinton** [comment]
This bug still affects v 5.2. Sorry for not being clear. I meant to say that v2.3 is as far back as I have checked @derrabus

**Comment by nicolas-grekas** [comment]
Can you please provide a reproducer or a failing test case maybe?

**Comment by benstinton** [comment]
No problem, here it is https://github.com/benstinton/date_type_bug 
You can see the issue by starting a web server navigating to `/form` in a browser

**Comment by benstinton** [comment]
Screenshot:

<img width="158" alt="Screenshot 2020-12-09 at 21 56 16" src="https://user-images.githubusercontent.com/5198015/101693506-99b9cd80-3a69-11eb-8df4-9d95de2f7687.png">

You can see the dashes between the selects above. This is produced by the code below.

```php
<?php


namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 *
 * Class DefaultController
 * @package App\Controller
 */
class DefaultController extends AbstractController
{
    /**
     * @Route("/form", name="form", methods={"GET"})
     * @return Response
     */
    public function formAction()
    {
        $form = $this->createFormBuilder()
            ->add('date', DateType::class, [
                'format' => 'dd-MM-yyyy'
            ])
            ->getForm();

        return $this->render('date_form.html.twig', [
            'form' => $form->createView()
        ]);
    }
}
```

**Comment by xabbuh** [comment]
Can you explain why your format includes the dashes in the first place at all? I think that changing the behavior here would be a BC break as developers can intentionally pass additional characters to enforce having characters rendered between the dropdowns. So after all I am not sure the current behavior actually is a bug.

**Comment by benstinton** [comment]
I am trying to get the select boxes to render in the order: day, month and year. This is the method as set out in the docs
https://symfony.com/doc/current/reference/forms/types/date.html#widget

Format expects the dashes in the date format 
https://symfony.com/doc/current/reference/forms/types/date.html#format

I agree this could cause a BC break, but I still think this behaviour is unintentional and in probably not wanted so should still be a bug. The dashes are there only as part of the date format. And actually putting anything else in their intentionally I think would cause an issue with the format.

An alternative would be to use another property to set the render order.

**Comment by xabbuh** [comment]
So isn't it just that you need to set the format to `ddMMYYYY` then?

**Comment by benstinton** [comment]
Thanks @xabbuh . Not sure how I missed this
