### ISSUE TITLE
Allow multiple parts with the same name in FormDataPart

### ISSUE THREAD

**Issue by tavy315** [symfony/symfony#39506]
**Symfony version(s) affected**: 5.2.0

**Description**  
This is my first bug report, so please let me know if I did something incorrectly.
The change did within https://github.com/symfony/mime/commit/8239e124100416d35b889c171db8c8aa5ee9b85d allows multiple parts with the same name in FormDataPart, but it fails to allow usage of multiple DataPart values, with exception message `Form field values with integer keys can only have one array element, the key being the field name and the value being the field value`...

This used to work before upgrading to 5.2, as I have been using it just fine for the last past 9 months, based on an example from Sylius' tests https://github.com/Sylius/Sylius/blob/master/tests/Controller/ProductApiTest.php#L508

**How to reproduce**  
I added a new test into FormDataPartTest.php and it passes with 5.1 while it fails on 5.2.
```php
    public function testFormFieldsWithIntegerKeysAndMultipleUploadedFiles()
    {
        $f = new FormDataPart([
            [
                new DataPart($foo = str_repeat('foo', 1000), 'foo.txt', 'text/plain'),
                new DataPart($bar = str_repeat('bar', 1000), 'bar.txt', 'text/plain'),
            ],
        ]);

        $parts = $f->getParts();
        $this->assertEquals($foo, $parts[0]->bodyToString());
        $this->assertEquals($bar, $parts[1]->bodyToString());
    }
```

**Additional context**  
The issue where this change was described is https://github.com/symfony/symfony/issues/38258 and is based on an array of TextPart values.

**Comment by OskarStark** [comment]
friendly ping @HypeMC as you introduced the mentioned change in #38323, thanks.

**Comment by HypeMC** [comment]
Hi, you seem to be using it wrong, the nested array is not needed:

```php
$f = new FormDataPart([
    new DataPart($foo = str_repeat('foo', 1000), 'foo.txt', 'text/plain'),
    new DataPart($bar = str_repeat('bar', 1000), 'bar.txt', 'text/plain'),
]);
```

This works in both Symfony 5.1 and 5.2 and is how it's intended to be used. The fact that your code works seems like a bug to me.

**Comment by HypeMC** [comment]
Also, the Sylius test is different as it uses string keys and not numeric ones, eg this works as well:

```php
$f = new FormDataPart([
    ['one' => new DataPart($foo = str_repeat('foo', 1000), 'foo.txt', 'text/plain')],
    ['two' => new DataPart($bar = str_repeat('bar', 1000), 'bar.txt', 'text/plain')],
]);
```

You can check out the [official documentation](https://symfony.com/doc/5.2/http_client.html#uploading-data) for some more examples.

**Comment by tavy315** [comment]
Hi, they are using nested arrays with numeric keys, having "file" string key in each nested array.
```php
$this->client->request(
            'POST',
            '/api/v1/products/',
            [],
            ['images' => [
                ['file' => new UploadedFile(sprintf('%s/../Resources/fixtures/ford.jpg', __DIR__), 'ford')],
                ['file' => new UploadedFile(sprintf('%s/../Resources/fixtures/mugs.jpg', __DIR__), 'mugs')],
            ]],
            static::$authorizedHeaderWithContentType,
            $data
        );
```
which if I'm not mistaken, gets uploaded as:
```php
$_FILES['images'][0]['file'] =
$_FILES['images'][1]['file'] = 
```
I guess that is like that because their [ImageType](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/ImageType.php) has 2 fields: `file` and `type`. 

So I tried to see if I can use a string key for children of `images` array:
```php
        $f = new FormDataPart([
            'images' => [
                'file0' => [
                    'file' => new DataPart($foo = str_repeat('foo', 1000), 'foo.txt', 'text/plain'),
                    'type' => 'image',
                ],
                'file1' => [
                    'file' => new DataPart($bar = str_repeat('bar', 1000), 'bar.txt', 'text/plain'),
                    'type' => 'image',
                ],
            ],
        ]);
```
This seems to be working fine like this, so we can close the issue. I will also submit an issue to Sylius, perhaps that might help other people having same issue.
