### ISSUE TITLE
symfony/mime uses egulias/email-validator but requires as dev dependency

### ISSUE THREAD

**Issue by lukaslangen** [symfony/symfony#39512]
**Symfony version(s) affected**: 5.2.0

**Description** 

As described in the title, `symfony/mime` requires `egulias/email-validator` as a dev dependency.

`\Symfony\Component\Mime\Address::class` throws a LogicException if `Egulias\EmailValidator\EmailValidator::class` does not exist.

This makes the package unusable on its own.

This is also not documented.

**How to reproduce**  

Clone `symfony/mime` and execute `composer install --no-dev`
Afterwards run the unit tests.

You also can create a small script, that can look like this. I used this to get the stack trace provided in "Additional context"

```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Mime\Address;

$address = new Address('user@example.com');
```

**Possible Solution**  

Instead of requiring `egulias/email-validator` as a dev dependency in "require-dev" require it as a production depency in "require"

**Additional context**  

Stack trace from test script:
```
PHP Fatal error:  Uncaught Symfony\Component\Mime\Exception\LogicException: The "Symfony\Component\Mime\Address" class cannot be used as it needs "Egulias\EmailValidator\EmailValidator"; try running "composer require egulias/email-validator". in /path-to-libs/symfony/mime/Address.php:44
Stack trace:
#0 /path-to-libs/symfony/mime/bin/test.php(7): Symfony\Component\Mime\Address->__construct('user@example.co...')
#1 {main}
  thrown in /path-to-libs/symfony/mime/Address.php on line 44

Fatal error: Uncaught Symfony\Component\Mime\Exception\LogicException: The "Symfony\Component\Mime\Address" class cannot be used as it needs "Egulias\EmailValidator\EmailValidator"; try running "composer require egulias/email-validator". in /path-to-libs/symfony/mime/Address.php on line 44

Symfony\Component\Mime\Exception\LogicException: The "Symfony\Component\Mime\Address" class cannot be used as it needs "Egulias\EmailValidator\EmailValidator"; try running "composer require egulias/email-validator". in /path-to-libs/symfony/mime/Address.php on line 44

Call Stack:
    0.0010     396144   1. {main}() /path-to-libs/symfony/mime/bin/test.php:0
    0.0036     548104   2. Symfony\Component\Mime\Address->__construct() /path-to-libs/symfony/mime/bin/test.php:7
```

**Comment by derrabus** [comment]
`egulias/email-validator` is an optional dependency that you only need for specific features. The current behavior is intended.
