### ISSUE TITLE
[YAML] Algorithm for quoting has changed

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony#39517]
**Symfony version(s) affected**: 4.4.17

**Description**  
A change in the YAML component affects the service definition. By putting a string there that ends in a backslash, the service configuration does not load anymore

**How to reproduce**  

Put the following lines in `services.yaml`:

```
parameters:
    ldap_domain: 'DOMAIN\'
    ldap_admin_username: 'user'
```

...and clear the cache, for example using `bin/console cache:clear`. The following error occurs:

>  The file "/var/www/html/config/services.yaml" does not contain valid YAML: Unexpected characters near " ldap_admin_username: '" at line 4 (near "ldap_admin_username: 'user'").  

Online tools like https://jsonformatter.org/yaml-validator or https://codebeautify.org/yaml-validator tell me this is valid YAML, and this has been part of my configuration since years. When downgrading to 4.4.16, the configuration is loaded properly again

**Comment by stof** [comment]
can you try again with 4.4.x-dev ? I think this regression has already been fixed

**Comment by NicoHaase** [comment]
Indeed, this is a duplicate of https://github.com/symfony/symfony/issues/39265 - sorry for not checking that before posting....
