### ISSUE TITLE
how to import CSV File in symfony 5?

### ISSUE THREAD

**Issue by HamzaRouissi** [symfony/symfony#39527]
im looking for a sample solution to upload a CSV file to an existent symfony 5 in server so i have an existent code but written in symfony 2 ..
here is the code of controller :

`public function uploadCSVAction() {
    $request = $this->get('request');
    $em = $this->getDoctrine()->getManager();
    $form = $this->createForm(new UploadFichesType($em));
    if ($request->getMethod() == 'POST') {
        if (!$session->get('liste')) {
            $form->bind($request);
            if ($form->isValid()) {
                // Upload file server
                if (file_exists("uploads/".$_FILES["App_uploadfiches"]["name"]["fichier"])){
                    unlink( "uploads/".$_FILES["App_uploadfiches"]["name"]["fichier"]);
                    move_uploaded_file($_FILES["App_uploadfiches"]["tmp_name"]["fichier"],"uploads/".$_FILES["App_uploadfiches"]["name"]["fichier"]);
                }else{
                    move_uploaded_file($_FILES["App_uploadfiches"]["tmp_name"]["fichier"],"uploads/".$_FILES["App_uploadfiches"]["name"]["fichier"]);
                }

here is the code of UploadFichesType:

`class UploadFichesType extends AbstractType {

private $em;

public function __construct($em) {
    $this->em = $em;
}

/**
 * @param FormBuilderInterface $builder
 * @param array $options
 */
public function buildForm(FormBuilderInterface $builder, array $options) {
    $builder
            ->add('fichier', 'file', array('label' => 'Fichier'))
            ->add('campagne', 'entity', array('label' => 'Campagnes', 'class' => 'AppBundle:VicidialCampaigns', 'choice_label' => 'campaignName', 'attr' => array('class' => 'form-control')))
            ->add('liste', 'choice', array('label' => 'Listes', 'attr' => array('class' => 'form-control')))
            ->add('code_pays', 'text', array('label' => 'Code Pays', 'attr' => array('class' => 'form-control'), 'data' => '33'))
            ->add('duplication', 'choice', array('label' => 'Contrôle de Duplication', 'choices' => array('NONE' => 'PAS DE VÉRIFICATION DE DUPLICATION', 'DUPLIST' => 'VÉRIFIER LA DUPLICATION DU TÉLÉPHONE DANS LA LISTE ', 'DUPCAMP' => 'VÉRIFIER LA DUPLICATION DU TÉLÉPHONE DANS TOUTE LA CAMPAGNE', 'DUPSYS' => 'VÉRIFIER LA DUPLICATION DU TELEPHONE DANS TOUT LE SYSTÈME'), 'attr' => array('class' => 'form-control')))
            ->add('bloctel', 'checkbox', array('label' => ' Vérification BLOCTEL', 'required' => false))
            ->add('formulaire', 'checkbox', array('label' => 'Ajouter des données du formulaire', 'required' => false))
    ;

    $ls = function(FormInterface $form, $campagne) {
        $listes = $this->em->getRepository('XarixBundle:VicidialLists')->findBycampaignId($campagne);
        $leslistes = array();
        if ($listes) {
            foreach ($listes as $liste) {
                $leslistes[$liste->getListId()] = $liste->getListName();
            }
        }
        $form->add('liste', 'choice', array('label' => 'Listes', 'attr' => array('class' => 'form-control'),
            'choices' => $leslistes));
    };

    $builder->get('campagne')->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event) use ($ls) {
        $ls($event->getForm()->getParent(), $event->getForm()->getData());
    });
}

/**
 * @param OptionsResolverInterface $resolver
 */
public function setDefaultOptions(OptionsResolverInterface $resolver) {
    $resolver->setDefaults(array(
        'attr' => ['id' => App_uploadfiches']
    ));
}

fichier is the CSV file which would be import to the server , so the first form will upload the csv file and after there is a a second form for reading csv file header ..just im looking for the first step now : importing the CSV file to server thank you`

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by wouterj** [comment]
Hi @elliotalld! The GitHub issue tracker is used purely for bug reports and feature requests.

You seem to have a question and you would like some help. Please use [one of the support channels](https://symfony.com/support) for that purpose (e.g. Slack or StackOverflow). I hope someone there can help you!

Edit: Oh wow, didn't see @derrabus' comment before posting this one. Sorry for the duplicate!

**Comment by HamzaRouissi** [comment]
thank you i will use support channels :)
