### ISSUE TITLE
Support for a build / distribution .env file (eg. env.build)

### ISSUE THREAD

**Issue by rjd22** [symfony/symfony#39524]
**Description**  
Some systems like sentry give environment variables as an example for storing the version of the application. I kind of found out that if you look at the dotenv configuration closely there is not really room for an automatically on build packed version with the env files.

- The files that end with `.local` should not be committed
- The files without `.local` can be committed but cannot be risk free replaced.

Would it be an good idea to add support to the dotenv for and extra env file that can be packed within the build and pack process but does not have to be committed nor, be on the server environment?

I'm willing to make an PR but I'm looking for some feedback on this first.

Sentry documentation on release versions:
https://github.com/getsentry/sentry-symfony#configuration-of-the-sdk

**Example**  

_What we support now_
- .env: defines the default values of the env vars needed by the application;
- .env.local: overrides the default values for all environments but only on the machine which contains the file. This file should not be committed to the repository and it’s ignored in the test environment (because tests should produce the same results for everyone);
- .env.\<environment\> (e.g. .env.test): overrides env vars only for one environment but for all machines (these files are committed);
- .env.\<environment\>.local (e.g. .env.test.local): defines machine-specific env var overrides only for one environment. It’s similar to .env.local, but the overrides only apply to one environment.

_What we add_
- .env.build: can be added in build process is for example copied in with the Docker build or an application build process and contains build related information like `release_version` etc...

Symfony docs on environment variables:
https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local

**Comment by jkufner** [comment]
Why not to build the `.env.local`?

**Comment by aurimasniekis** [comment]
> Why not to build the `.env.local`?

That's a good point, considering the docker example you building a docker image with source code embedded you can just generate `.env.local` file inside the docker image as it is not going to be pushed to the repository and technically it's local in this docker image. 

But if it's decided to use something like `.env.build` it is also not bad, just different naming I guess.

**Comment by rjd22** [comment]
@jkufner @aurimasniekis It doesn't necessarily have to be docker builds, but could also be packaged versions that are deployed to servers.

In these cases there is already a env.local on the server that you don't want to replace. That is why I proposed a separate file that is specially meant for the build servers to avoid conflicts with other .env files.

**Comment by ro0NL** [comment]
.env.build being something special would be confusing to me (IIUC in the proposal here it's not a dedicated environment as per `.env.<environment>` then)

what actually stops you from committing (or building) .env_build and invoke `if file_exists { Dotenv::load }` as such? Isnt this more of a recipe proposal?

**Comment by rjd22** [comment]
@ro0NL Of course we can fix this manually but most of the loading of .env and what files to load is done in the Dotenv library. There is also the concern of the `composer dump-env prod` command that puts the .env variables in a PHP file.

When working with sentry and asset dump on a non-containerized environment that it deployed by CI I really feel that the ability to add extra .env variables that are understood by symfony but do not conflict with the other .env files was missing.

The reason I'm making an issue and not a PR right away is of course to ask for feedback first.

**Comment by ro0NL** [comment]
solving it via recipes will also work for everyone, but i tend to believe scales better for everyone (more granularity).

either way we'll introduce a new(?) convention, of which im not sure it should be hardcoded in Dotenv.

what exactly are the semantics of `.env.build`? Defaulting or overriding? eg. compared to `.env.dev`, does it come before or after?

**Comment by jkufner** [comment]
Dotenv is already more complicated than it should be.

You know you can use the properties for this, right?

**Comment by rjd22** [comment]
@jkufner I might be missing something but what do you exactly mean with the properties?

@ro0NL The semantics of the `.env.build` is that the variables in it are appended when it is found. It is not required and should not be commited to the repository but should also not be in the shared directory on the server. The place for it to be included is on the build / packaging of the application so that information of the build result can be shared with the application.

I feel that everyone thinks this is an bad idea so I will most likely close this issue.

**Comment by jkufner** [comment]
@rjd22 Sorry. "[Parameters](https://symfony.com/doc/current/configuration.html#configuration-parameters)". You can generate the config that serves as defaults when `.env` does not define the values. Thats how we did this before `.env`.

**Comment by rjd22** [comment]
@jkufner This is indeed how I solved it now. Felt like the wrong way to deal with this but it seems it isn't. I will be closing this issue then. Thank you all for you time and input!

**Comment by NicoHaase** [comment]
Even if this comes too late: you could also use an additional file, and store the version number in that file. Reading that file through env achieves that you only have to override that file during the build process

```
parameters:
    env(VERSION_FILE): '../config/version-number'
    version_number: '%env(file:VERSION_FILE)%'
```

**Comment by rjd22** [comment]
@NicoHaase Thank you for this extra information. That is very helpful :+1:. As reference to others that might find this issue and are wondering the same. In my Makefile I have the following rules that package the application and change the version in services.yaml.

```
.PHONY: build
build: composer-install-prod js-install-prod set-release-version build-package
	@echo "Success, application build and packaged."

.PHONY: set-release-version
set-release-version:
	@ if [ "$(release_version)" = "" ]; then \
		echo "Error: release_version not set, set it by adding release_version=v0.0.0 or release_version=<commit-hash>"; \
		exit 1; \
	fi
	sed -i "s/release_version: 'local'/release_version: '$(release_version)'/g" config/services.yaml

.PHONY: build-package
build-package:
	mkdir -p build/
	tar -czf build/build.tar.gz  bin/ config/ migrations/ public/ src/ templates/ translations/ var/ vendor/ composer.json composer.lock
```
