### ISSUE TITLE
[Form] How to remove days from DateType?

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#39536]
Hello!

Any ideas how to remove days from DateType?

Thx

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
