### ISSUE TITLE
symfony-bundles/json-request-bundle got deleted/removed/private

### ISSUE THREAD

**Issue by telemmaite** [symfony/symfony#39535]
Hello it looks like the bundle repo was moved which triggered **massive CI failures** on our end, as we were expecting the bundle is well supported and under the symfony-bundles group.
https://packagist.org/packages/symfony-bundles/json-request-bundle

We can now see that was not the case, as the actual repo is which now gives 404.
github.com/**mgid**/json-request-bundle

Is there a safe list/group of bundles in github that Symfony group is maintaining?

**Comment by jderusse** [comment]
This package is not related to `symfony/symfony`. Please contact the vendor `mgid` or `symfony-bundles`.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by apfelbox** [comment]
> Is there a safe list/group of bundles in github that Symfony group is maintaining?

Basically everything under `symfony/*`
