### ISSUE TITLE
[Security] TypeError: Argument 1 passed to Symfony\Component\Security\Core\Exception\AuthenticationException::__unserialize() must be of the type array, null given

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#39540]
**Symfony version(s) affected**: 4.4.17

**Description**  
In some specific circumstances, PHP 7.4 session could not be unserialized in PHP 7.3. I asusme it's related to https://bugs.php.net/bug.php?id=79759.

This is a common scenario in multi-server environment, when PHP is upgraded server by server. It's strange that there are no previous bug reports on this subject.

Errors I collected:

```
TypeError: Argument 1 passed to Symfony\Component\Security\Core\Exception\AuthenticationException::__unserialize() must be of the type array, null given, called in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php on line 137
#24 /vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php(96): Symfony\Component\Security\Core\Exception\AuthenticationException::__unserialize
#23 /vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php(137): Symfony\Component\Security\Core\Exception\AuthenticationException::__wakeup
#22 [internal](0): session_start
#21 /vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(156): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::start
#20 /vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(323): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::getBag
```
How does `session_start()` knows about `AuthenticationException`?

```
"PHP message: PHP Warning:  session_start(): Session object destruction failed in vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 156"
```

**How to reproduce**  
Save session in PHP 7.3, and load it in PHP 7.4. but bug only affects small portion of users, so it's not easy to reproduce.

**Possible Improvement**  
One minor improvement for better DX and error handling is to check if `$this->serialized` is `null` before trying to unserialize and fail with a better error.

**Comment by derrabus** [comment]
This is indeed are rare case. Event if we fix this for the `AuthenticationException`, you'll probably run into more issues of this kind. I'm curious: Are you planning to run php 7.3 and 7.4 webservers in parallel for a longer period or would it be feasible to enable session pinning in your load balancer while you upgrade the webservers?

**Comment by umpirsky** [comment]
With session pinning load balancing is not very fair in our case, some servers can get overworked, so, it is not ideal option.

After downgrading [igbinary](http://pecl.php.net/package-changelog.php?package=igbinary), from 3.1.6. to 3.0.1, this error is gone, but new one happens:

```
PHP message: PHP Warning:  Erroneous data format for unserializing 'Symfony\Component\Security\Core\Authentication\Token\RememberMeToken'
```

when trying to unserialize `unserialize($ession->getBag('attributes')->get('_security_secured_area'))` in PHP 7.3 if data is serialized in PHP 7.4. But that is out of the scope of this issue. 

We need to prevent error from the issue description, as we will need to upgrade igbinary sooner or later. 
Even if we enable session pinning, that will only address sessions and not other cases where serialization is the problem.

Thanks for sharing ideas, really appreciate it.

**Comment by jmalinens** [comment]
We also have experienced multiple issues with sessions when switching from PHP 7.1 to 7.4 and also from Symfony 3.4 to 4.4 so @umpirsky You are not alone :)

Two major issues are:
* PHP serialization between major PHP version has changed and in many cases are not compatible
* Symfony session format also has changed few times

We ended up with ugly solution patching ContextListener so session is backward and forward compatible with different PHP and symfony versions so multiple projects with different Symfony or PHP version could understand session data.

Similar problem we are experiencing with moving from 4.4 to 5.x as Role class is removed in Symfony5 which breaks unserializing session data for PHP.
Also there are problems if Symfony4 project tries to use Symfony5 session as it expects old Symfony session structure.
For forward compatibility we copied Role class to Symfony5 projects so they can unserialize it.
For backward compatibility we ended up patching AbstractToken `__unserialize()` method.

Maybe somebody has cleaner solution?

**Comment by nicolas-grekas** [comment]
I think there is little we can do here.
A safer migration strategy would be to upgrade PHP and Symfony separately, as from what I understand, the issue happens when both are upgraded at the same time.

Anyway, I'm closing here as I don't think we can do anything in Symfony itself.

Or course, PR welcome if you think I'm wrong!

**Comment by derrabus** [comment]
> as from what I understand, the issue happens when both are upgraded at the same time.

No, @umpirsky's issue occurs if you run PHP 7.3 and 7.4 at the same time with the same application.

The aspect of different Symfony versions was introduced by @jmalinens, but that is indeed a different problem (and one that we shouldn't solve). Let's not mix this up.

**Comment by stof** [comment]
Well, migration layers defined in Symfony are supporting the case where you upgrade PHP and you need to unserialize an old session (serialized with the old PHP version), which relies on the fact that PHP itself supports backward compatibility there.
But PHP makes no guarantee that PHP 7.3 can unserialize data serialized by PHP 7.4 (the only way to guarantee that would be to forbid changing the serialization algorithm entirely as PHP 7.3 does not know about the changes done in 7.4).

**Comment by umpirsky** [comment]
Having similar issue when switching PHP7.4 to PHP8.0:

```
TypeError

Argument 1 passed to Symfony\Component\Security\Core\Exception\AuthenticationException::__unserialize() must be of the type array, null given, called in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php on line 146
```

And PHP8.0 to PHP7.4:

```
TypeError

Symfony\Component\Security\Core\Exception\AuthenticationException::__unserialize(): Argument #1 ($data) must be of type array, bool given, called in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/CustomUserMessageAuthenticationException.php on line 73 and defined in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php:105
```

This happens on `vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(156): session_start()`.  

Can someone tell me where and why Symfony (`v4.4.35`) serializes this exceptions? 

Thanks in advance and sorry for bringing up this topic again, but it really makes PHP upgrades problematic in a multi-server environment.

**Comment by umpirsky** [comment]
Looks like it's in `AbstractFormLoginAuthenticator::onAuthenticationFailure()`:

```php
public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
{
    if ($request->hasSession()) {
        $request->getSession()->set(Security::AUTHENTICATION_ERROR, $exception);
    }

    $url = $this->getLoginUrl();

    return new RedirectResponse($url);
}
```

**Comment by umpirsky** [comment]
> For backward compatibility we ended up patching `AbstractToken __unserialize()` method.

@jmalinens Hey, do you remember what kind of patch you did here?

For my error `Argument 1 passed to AuthenticationException::__unserialize() must be of the type array, null given` I don't think changing to `public function __unserialize($data): void` is an option, since many classes override `AuthenticationException::__unserialize()` and changing all of them is just too much.
