### ISSUE TITLE
[Http Client] Easy access to requests

### ISSUE THREAD

**Issue by loevgaard** [symfony/symfony#39551]
I am doing http requests to an external service using the Symfony HTTP client. When the requests fail I would like to be able to see the *exact* http request that was sent to the external service, so I can rerun it myself in i.e. Postman, but right now I am not able to get that from the http client.

What is the best/correct to get this if it's possible?

**Comment by nicolas-grekas** [comment]
`$response->getInfo('debug')` provides all the details.
See `$response->getInfo()` for even more details.

**Comment by loevgaard** [comment]
I have no idea why I didn't check that. Sorry for wasting your time :(

**Comment by loevgaard** [comment]
I tested it right now and I have this output from `$response->getInfo('debug')`:

```
* Found bundle for host businesscentral.dynamics.com: 0x55d845319a90 [can multiplex]
* Re-using existing connection! (#0) with host businesscentral.dynamics.com
* Connected to businesscentral.dynamics.com (13.94.202.175) port 443 (#0)
* Using Stream ID: 7 (easy handle 0x55d845315fa0)
> POST /*****.onmicrosoft.com/Production/ODataV4/Company('******')/SylCustomer HTTP/2
Host: businesscentral.dynamics.com
accept: application/json
content-type: application/json
authorization: Basic *****
user-agent: Symfony HttpClient/Curl
accept-encoding: gzip
content-length: 351

* We are completely uploaded and fine
< HTTP/2 400 
< content-length: 0
* Added cookie WFESessionId="16ef2d75-9ada-4f21-a9bc-9286b3a2c80f" for domain businesscentral.dynamics.com, path /, expire 0
< set-cookie: WFESessionId=16ef2d75-9ada-4f21-a9bc-9286b3a2c80f; path=/; secure; samesite=none; httponly
< request-context: appId=cid-v1:1278b3f8-7136-40a2-b821
```

The request payload isn't present. Is there a way to see that?

**Comment by stof** [comment]
@loevgaard I don't think curl can send the payload to the debug output

**Comment by loevgaard** [comment]
Okay, do you have a suggestion to get it somehow? If I could access the initial request I sent somehow I could get the `$options['json']`

**Comment by nicolas-grekas** [comment]
With a decorator you should be able to catch the request I suppose. TraceableHttpClient does so.

**Comment by loevgaard** [comment]
Will look into that. Thank you!
