### ISSUE TITLE
How to add methods and properties to a Symfony SplFileInfo class?

### ISSUE THREAD

**Issue by leo95batista** [symfony/symfony#39567]
I would like to know if there is any way to add a method or property to a ```SplFileInfo``` class in order to extend its functionality.

https://www.php.net/manual/en/class.splfileinfo.php

Let me explain, I am using ```Laravel``` and making use of Symfony's [Finder][1] component to get all the files inside a directory, I am doing it as follows:

```
    private function getDirectoryContent(string $path)
    {
        $finder = Finder::create()
            ->in($path)
            ->depth(0)
            ->sortByName();

        return collect($finder);
    }
```

The value returned by this method is the following:

```
dd($this->getDirectoryContent('/var/www/my_project/resources'));
```

```
Illuminate\Support\Collection^ {#764
  #items: array:15 [
    "/var/www/my_project/resources/lang/en" => Symfony\Component\Finder\SplFileInfo^ {#789
      -relativePath: ""
      -relativePathname: "en"
      path: "/var/www/my_project/resources/lang"
      filename: "en"
      basename: "en"
      pathname: "/var/www/my_project/resources/lang/en"
      extension: ""
      realPath: "/var/www/my_project/resources/lang/en"
      aTime: 2020-12-18 01:22:21
      mTime: 2020-12-16 03:20:23
      cTime: 2020-12-16 03:20:23
      inode: 9241026
      size: 4096
      perms: 040755
      owner: 1000
      group: 1000
      type: "dir"
      writable: true
      readable: true
      executable: true
      file: false
      dir: true
      link: false
    }
    ....

```

As you can see it is a collection with many objects of type: ```Symfony\Component\Finder\SplFileInfo```.

This object type extends from the ```SplFileInfo``` base class with 4 new methods added by ```Symfony```:

 - ```getRelativePath()```
 - ```getRelativePathname()```
 - ```getFilenameWithoutExtension()```
 - ```getContents()```

It happens that in the future I will need to obtain a calculated value in each of these objects. I was wondering if it is possible to extend Symfony's ```SplFileInfo``` class to be able to achieve something similar to the following:

```
    private function exampleMethod(SplFileInfo $object)
    {
        $collection = $this->getDirectoryContent($object->getRealPath());
        
        foreach($collection as $item) {
            echo $item->MyCustomMethod(); // see here
        }
    }
```

is this possible? How could I do it? In essence I would like to define a new class and in it extend the class: ``` Symfony\Component\Finder\SplFileInfo``` to define the methods and properties that I want when it returns the result of: ```Symfony\Component\Finder\Finder```

Thank you very much in advance.

  [1]: https://symfony.com/doc/current/components/finder.html

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
