### ISSUE TITLE
Circular dependency for intl

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#39595]
The [Symfony/intl](https://packagist.org/packages/symfony/intl) has a dependency on [symfony/polyfill-intl-icu](https://packagist.org/packages/symfony/polyfill-intl-icu) which has a dependency on `symfony/intl`. 

Is this really correct?

**Comment by ro0NL** [comment]
it's part of the bc layer yes.

https://packagist.org/packages/symfony/polyfill-intl-icu#dev-main ;)

**Comment by Nyholm** [comment]
Thank you for your quick answers Roland. 

Good good. I thought it looked weird but naturally it was no misstake.
