### ISSUE TITLE
Add a custom Notifier SMS channel

### ISSUE THREAD

**Issue by aurelienheyliot** [symfony/symfony#39594]
Hi,

I want to use my own SMS Channel and use the Symfony Notifier feature.

I have created a new transport module from the example: https://github.com/symfony/twilio-notifier and I want to "call" my module from my project which is a dependency loaded from my personal Github.
I took care to add in notifier.yaml my new transport channel.

I wanted to overload Symfony\Component\Transport from the .yaml services with a new entry in the "FACTORY_CLASSES" table that corresponds to my new provider but impossible for Symfony to understand that there is a new SMS Channel.
Is it possible to add my own channel? How is it possible to do so if yes ?

Thank you for your help.

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
