### ISSUE TITLE
[Form] Remove dependency on symfony/intl

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#39596]
The form component have a hard dependency on `symfony/intl`. I like that component, but it feels a bit overkill to download 18MB of code for if you only are creating a small form. 

Currently, there is only the LocaleType, CountryType, CurrenyType, LanguageType and TimezoneType that is using `symfony/intl`. I suggest that we should remove Form component's dependency in Intl in Symfony 6 to make the form component lighter.

**Comment by ro0NL** [comment]
See https://github.com/symfony/symfony/issues/29229

i think now after https://github.com/symfony/symfony/pull/38974 the road is open :)

**Comment by nicolas-grekas** [comment]
This should be for v5.x actually, with some potential deprecations.
