### ISSUE TITLE
How to use capture_stderr_separately?

### ISSUE THREAD

**Issue by abeal-hottomali** [symfony/symfony#39615]
Trying to create tests for my custom Symfony command, as per the [docs](https://symfony.com/doc/current/console.html#testing-commands).  I'm trying to ensure I see a particular error message when I run a command in a prod environment.  

When I call:
```php
        // snippet
        $commandTester = new CommandTester($command);
        $commandTester->execute();
        self::assertEquals("My expected exception message", $commandTester->getErrorOutput());
        // end snippet
```

I get:
```bash
LogicException: The error output is not available when the tester is run without "capture_stderr_separately" option set.
```

But when I call:
```php
        // snippet
        $commandTester = new CommandTester($command);
        $commandTester->execute(['capture_stderr_separately' => true]);
        self::assertEquals("My expected exception message", $commandTester->getErrorOutput());
        // end snippet
```

I get:
```bash
Symfony\Component\Console\Exception\InvalidArgumentException: The "capture_stderr_separately" argument does not exist.
```

How is this meant to be used?

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by sweoggy** [comment]
I know this issue is closed, but it was the first search result I got on Google, so I thought I might as well answer.

You need to pass the capture_stderr_separately option as second argument to $commandTester->execute():

`$commandTester->execute([], ['capture_stderr_separately' => true]);`
