### ISSUE TITLE
Segmentation fault on cache clear

### ISSUE THREAD

**Issue by maxkain** [symfony/symfony#39619]
**Symfony version(s) affected**: 5.2.1

**Description**  
Update symfony from 5.2.0 to 5.2.1:
composer update symfony/*
Then error on cache:clear:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/.../var/cache/dev/ContainerEOpepOZ/App_KernelDevDebugContainer.php on line 19176

Increasing memory limit to 512M. Segmentation fault error appears. Increasing imit to 2048M - the same error.
After downgrading the error disappears:
Package operations: 0 installs, 52 updates, 1 removal
  - Removing symfony/proxy-manager-bridge (v5.2.1)
  - Downgrading symfony/http-foundation (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/event-dispatcher (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/var-dumper (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/error-handler (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/http-kernel (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/doctrine-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dependency-injection (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/string (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/console (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/filesystem (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/config (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/routing (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/finder (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/var-exporter (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/cache (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/framework-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/stopwatch (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/process (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/expression-language (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/uid (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/twig-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/twig-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/translation (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-core (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/property-info (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/property-access (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-http (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-guard (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-csrf (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/intl (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/options-resolver (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/form (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/asset (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/templating (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/mime (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/http-client (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dom-crawler (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/browser-kit (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/css-selector (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/web-profiler-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/monolog-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/debug-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dotenv (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/lock (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/maker-bundle (v1.26.1 => v1.25.0): Extracting archive
  - Downgrading symfony/orm-pack (v2.1.0 => v2.0.0): Extracting archive
  - Downgrading symfony/phpunit-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/serializer (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/validator (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/web-link (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/yaml (v5.2.1 => v5.2.0): Extracting archive

**Comment by jderusse** [comment]
Could you provide a reproducer?

**Comment by maxkain** [comment]
There is a doctrine event subscriber. Another service is autowired to it. And entity manager is autowired to the service. If I remove the entity manager autowiring, the error disappears.

**Comment by maxkain** [comment]
So, what to do? I can not update.

**Comment by nicolas-grekas** [comment]
Can you try `composer require symfony/proxy-manager-bridge`?
Even if it works, a reproducer would help us understand the root cause.
Thanks for anything you could do.

**Comment by calvera** [comment]
i have the same, upgrade from 4.4.17 to 4.4.18... when i revert it and try `composer require symfony/proxy-manager-bridge
` it fails with 

```
                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11".         
                                                          

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:366
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:198
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:125
 Composer\Util\ProcessExecutor->doExecute() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:65
 Composer\Util\ProcessExecutor->execute() at /app/vendor/symfony/flex/src/ScriptExecutor.php:58
 Symfony\Flex\ScriptExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code:620
 Symfony\Flex\Flex_composer_tmp4->executeAutoScripts() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:172
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:86

```

not sure how to make a simple reproducer because the project is not open source, sorry

**Comment by maxkain** [comment]
> Can you try `composer require symfony/proxy-manager-bridge`?

The same error with it on 5.2.0

**Comment by baurelien** [comment]
Same error. Segmentation fault during cache:clear after symfony/proxy-manager-bridge installation
But on 4.4.16

**Comment by soifou** [comment]
Same here, upgrading with Composer from 5.2.0 to 5.2.1 (with PHP 7.4.9)

```
> post-update-cmd: @auto-scripts
> auto-scripts: Symfony\Flex\Flex->executeAutoScripts
Executing script cache:clear


  [Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "11".


Exception trace:
 () at phar:///usr/bin/composer/vendor/symfony/process/Process.php:366
 Symfony\Component\Process\Process->wait() at phar:///usr/bin/composer/vendor/symfony/process/Process.php:198
 Symfony\Component\Process\Process->run() at phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php:125
 Composer\Util\ProcessExecutor->doExecute() at phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php:65
 Composer\Util\ProcessExecutor->execute() at /app/vendor/symfony/flex/src/ScriptExecutor.php:58
 Symfony\Flex\ScriptExecutor->execute() at /app/vendor/symfony/flex/src/Flex.php:620
 Symfony\Flex\Flex->executeAutoScripts() at n/a:n/a
 call_user_func() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:172
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:86
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:198
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:101
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/bin/composer/src/Composer/Installer.php:339
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:231
 Composer\Command\UpdateCommand->execute() at /app/vendor/symfony/flex/src/Command/UpdateCommand.php:39
 Symfony\Flex\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:63
 require() at /usr/bin/composer:24
```

Removing manually the cache folder then reissuing `cache:clear` seems to fix the problem of clearing the cache.

But now the app fails to run with a doctrine cyclic reference error:

```
Error:
Maximum function nesting level of '256' reached, aborting!

  at /app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:752
  at ContainerHo452I3\App_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService()
     (/app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:757)
  at ContainerHo452I3\App_KernelDevDebugContainer->ContainerHo452I3\{closure}()
     (/app/var/cache/dev/ContainerHo452I3/EntityManager_9a5be93.php:36)
  at Closure->__invoke()
     (/app/var/cache/dev/ContainerHo452I3/EntityManager_9a5be93.php:36)
  at ContainerHo452I3\EntityManager_9a5be93->getMetadataFactory()
     (/app/vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php:182)
  at Doctrine\Persistence\AbstractManagerRegistry->getManagerForClass()
     (/app/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php:30)
  at Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository->__construct()
     (/app/src/Repository/ServiceRepository.php:29)
  at App\Repository\ServiceRepository->__construct()
     (/app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:1398)
  at ContainerHo452I3\App_KernelDevDebugContainer->getServiceRepositoryService()
     (/app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:731)
  at ContainerHo452I3\App_KernelDevDebugContainer->getDoctrine_Dbal_DefaultConnectionService()
     (/app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:860)
  at ContainerHo452I3\App_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService()
     (/app/var/cache/dev/ContainerHo452I3/App_KernelDevDebugContainer.php:757)
  at ContainerHo452I3\App_KernelDevDebugContainer->ContainerHo452I3\{closure}()
     (/app/var/cache/dev/ContainerHo452I3/EntityManager_9a5be93.php:36)
  at Closure->__invoke()
     (/app/var/cache/dev/ContainerHo452I3/EntityManager_9a5be93.php:36)
  at ContainerHo452I3\EntityManager_9a5be93->getMetadataFactory()
     (/app/vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php:182)
  at Doctrine\Persistence\AbstractManagerRegistry->getManagerForClass()
     (/app/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php:30)
  at Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository->__construct()
     (/app/src/Repository/ServiceRepository.php:29)
  at App\Repository\ServiceRepository->__construct()
...
```

**Comment by nicolas-grekas** [comment]
Hello everyone.

Please don't post "me too" comments, that doesn't really help.
What would definitely help is a reproducer instead!

**Comment by maxkain** [comment]
> What would definitely help is a reproducer instead!

The error occurs if there is event listener with injected service which has injected entity manager interface. This information is not enough to reproduce the bug?

**Comment by nicolas-grekas** [comment]
I'm not sure. A repository with a small project that reproduces the issue is the thing that would really really help. Please post the link to it once you have one ready please if you can.

**Comment by maxkain** [comment]
It's difficult to reproduce the same, but looks like this:
https://github.com/maxkain/symfony-bug

**Comment by maxkain** [comment]
I have updated the reproducer. With proxy-manager-bridge bug occurs even if getting any repository by entity manager in event subscriber constructor: $em->getRepository(AnyEntity::class);
Without proxy-manager-bridge bug occurs only if injecting repository in event subscriber.

**Comment by jderusse** [comment]
Thank you for the reproducer. 
I understand, now, why it fails. I'm working on a fix.

**Comment by nicolas-grekas** [comment]
If the issue is that a lazy is service is used to instantiate another service, then I suggest creating a pass that removes the lazy flag when it detects the situation (with some log) - at least when this happens in a loop.

**Comment by jderusse** [comment]
@maxkain  could you please give a try to https://github.com/symfony/symfony/issues/39619?

**Comment by maxkain** [comment]
> @maxkain could you please give a try to #39619?

The same error after updating to 5.2.1

**Comment by jderusse** [comment]
> > @maxkain could you please give a try to #39619?
> 
> The same error after updating to 5.2.1

I'm not sure to understand what you mean. How did you tried the patch to check if your issue has been fixed?

**Comment by maxkain** [comment]
> > > @maxkain could you please give a try to #39619?
> > 
> > 
> > The same error after updating to 5.2.1
> 
> I'm not sure to understand what you mean. How did you tried the patch to check if your issue has been fixed?

I have edited the vendor file:
```php
        $container->registerForAutoconfiguration(ServiceEntityRepositoryInterface::class)
            ->setLazy(true)
            ->addTag(ServiceRepositoryCompilerPass::REPOSITORY_SERVICE_TAG);
```
But the same error

**Comment by ostrolucky** [comment]
@maxkain have you also cleared the cache?

**Comment by maxkain** [comment]
> @maxkain have you also cleared the cache?

Yes. I added it manually in the folder.

**Comment by jderusse** [comment]
> > > > @maxkain could you please give a try to #39619?
> > > 
> > > 
> > > The same error after updating to 5.2.1
> > 
> > 
> > I'm not sure to understand what you mean. How did you tried the patch to check if your issue has been fixed?
> 
> I have edited the vendor file:
> 
> ```
>         $container->registerForAutoconfiguration(ServiceEntityRepositoryInterface::class)
>             ->setLazy(true)
>             ->addTag(ServiceRepositoryCompilerPass::REPOSITORY_SERVICE_TAG);
> ```
> 
> But the same error

Indeed, the patch does not work with the updated version of you repository when you inject the EntityManager directly inside the EventSubscriber... let me check somethingelse

**Comment by jderusse** [comment]
Please, have a look to #39799

**Comment by maxkain** [comment]
> Please, have a look to #39799

It works!
