### ISSUE TITLE
PasswordUpgrader called but token not updated : unwanted log out at next request because hasUserChanged() returns true

### ISSUE THREAD

**Issue by oadam** [symfony/symfony#39628]
**Symfony version(s) affected**: 5.2

**Description**  
I'm using `enable_authenticator_manager`. My userProvider implements `PasswordUpgraderInterface`.
When logging in with a user whose password is using `bcrypt`, I successfully login and my `upgradePassword` is called.
During the next request, `AbstractToken->hasUserChanged` sees that `getPassword` returns something different than what is stored in the session and the user is logged out.

**How to reproduce**  
Custom userProvider that does password upgrade, `algorithm: auto`, login with a user whose password is in bcrypt.

**Possible Solution**  
Once the password is migrated, make `PasswordMigratingListener` reload the user and store it in the TokenStorage ?

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
