### ISSUE TITLE
[Validator] `strict` email validation mode name is misleading

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony#39627]
**Symfony version(s) affected**: all supported versions

**Description**  
The documentation for Email constraint currently lists three choices for `mode`:
- `loose`
- `strict`
- `html5`

While it's shortly explained what these choices are, I don't think that explanation is clear enough on the simple fact that `loose` is what most real-life use-cases should choose.
(EDIT 2022-02: I believe I actually meant to say `html5`, not `loose` here)

Specifically, the name of the `strict` mode sounds like it performs some 'extra strict' checks to ensure that an email address is valid. While in reality (at least after reading the docs it seems that) it just checks that the email address conforms to the RFCs by using a 3rd-party library. And conformance to RFCs means that emails like `a@a` and likely even `a@[127.0.0.1]` are seen as valid.

Thus, I think the name `strict` is simply misleading, and I suggest that it be changed and/or documented more thoroughly.

**Comment by fabpot** [comment]
There is no way to be stricter than the RFC, so I'm not sure there is anything we can do here. If you think docs can be improved, feel free to submit a pull request.

**Comment by rimas-kudelis** [comment]
> There is no way to be stricter than the RFC

I believe there is: you can _restrict_ accepted email addresses to a subset of what the RFC allows. All accepted addresses then still _strictly_ conform to the RFC, but also satisfy additional constraints. And that's precisely what the other two options are doing.
