### ISSUE TITLE
[WebProfiler] wrong scheme used for debug toolbar

### ISSUE THREAD

**Issue by Selion05** [symfony/symfony#39620]
**Symfony version(s) affected**: 5.2.1
**Description**

I recently switched to traefik for https in my dev environment. 
Now I run into cors issues with the debug toolbar.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://symfony.docker.localhost/_wdt/fa0c30. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Note the `http://` instead of `https://`

according to [symfony docs][1] I added

    parameters:
        router.request_context.scheme: 'https'
        asset.request_context.secure: true

but that didn't work. 

The url is displayed here
https://github.com/symfony/symfony/blob/14a3730afa1768e3cedba9c074b6c05fbfc7da01/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L425

**Possible Solution**  
Use `path` function instead of `url`

  [1]: https://symfony.com/doc/current/routing.html#forcing-https-on-generated-urls

**Comment by derrabus** [comment]
Please have a look at https://symfony.com/doc/current/deployment/proxies.html about how to configure Symfony to work behind a reverse proxy like Traefik.

**Comment by Selion05** [comment]
```
  // public/index.php
  // var_dump($_SERVER);
  'HTTP_X_REAL_IP' => string '192.168.208.1' (length=13)
  'HTTP_X_FORWARDED_SERVER' => string '84408d71ab3c' (length=12)
  'HTTP_X_FORWARDED_PROTO' => string 'https' (length=5)
  'HTTP_X_FORWARDED_PORT' => string '443' (length=3)
  'HTTP_X_FORWARDED_HOST' => string 'symfony.docker.localhost' (length=24)
  'HTTP_X_FORWARDED_FOR' => string '192.168.208.1' (length=13)
```
So `HTTP_X_FORWARDED_PROTO` is already set.


With 
```
Request::setTrustedProxies(['127.0.0.1', 'REMOTE_ADDR'], Request::HEADER_X_FORWARDED_TRAEFIK);
```
I get to many redirects because symfony redirects to http  and then traefik to https again :/

**Comment by fabpot** [comment]
Closing as there is no issues in Symfony. Please use any StackOverflow if you need further help. Thanks!
