### ISSUE TITLE
[Form] Profiler in 404 error when the page includes large ChoiceType choices

### ISSUE THREAD

**Issue by Johnson66666** [symfony/symfony#39638]
**Symfony version(s) affected**: 4.4.x

**Description**  
When a page contains a form that load 5000+ entities as ChoiceType data, it results on a 404 profiler.

**How to reproduce** 
Person is a complex entity with 43 fields. An array of 5000+ persons make profiler in a 404 state

```php
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class TestFormType extends AbstractType
{
    protected $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $choices = $this->entityManager->getRepository(Person::class)->findBy([], ['firstName' => 'ASC']);
        $builder
            ->add('persons', ChoiceType::class, [
                'choices' => $choices, // too many choices
                'data' => $choices[0] ?? [],
                'label' => 'Persons',
            ]);
            ->add('save', SubmitType::class, [
                'label' => 'form.save'
            ]);
    }
}
```

**Additional context** 
![404-Profiler](https://user-images.githubusercontent.com/75082359/103217697-8045cc00-4919-11eb-8345-cfc5eca933d3.png)

**Comment by k0d3r1s** [comment]
do you really need those 43 fields in choice type? or you can write a simple repository method to return only needed fields? 5k with 43 fields does not seem to be symfony problem - with that amount of data to display, you most likely have some memory or performance problem as display of that would require an enormous amount of resources

**Comment by Johnson66666** [comment]
> do you really need those 43 fields in choice type? or you can write a simple repository method to return only needed fields? 5k with 43 fields does not seem to be symfony problem - with that amount of data to display, you most likely have some memory or performance problem as display of that would require an enormous amount of resources

I could but it would be more complex, as Symfony handle parents using Data Transformers. Anyway, this is not a display issue. Even if my page is very light, profiler is in a 404 state. It's the repository method that creates this issue.

**Comment by Johnson66666** [comment]
Hi again.

I close this issue, and come back for the explanation a bit late.

This is not a Doctrine but a form issue. On huge entities with many fields, data transformers are breaking the php memory limit. I had to make my array of entities lighter by choosing two fields, and handling this form field by myself

```
        $choices = [];
        $choicesTemp = $this->entityManager->getRepository(Person::class)->findBy([], ['firstName' => 'ASC']);
        foreach ($choicesTemp as $choice) {
            $choices[$choice->displayName()] = $choice->getId();
        }
        $builder
            ->add('persons', ChoiceType::class, [
                'choices' => $choices,
                'data' => reset($choices) ?? [],
                'label' => 'Persons',
            ]);
            ->add('save', SubmitType::class, [
                'label' => 'form.save'
            ]);
```

So I could avoid this memory limit error and see my toolbar again

> [2021-02-04 09:35:24] php.CRITICAL: Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /var/www/mysite/vendor/symfony/http-kernel/DataCollector/DataCollector.php:98)"} []
> [2021-02-04 09:35:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)" at /var/www/mysite/vendor/symfony/http-kernel/DataCollector/DataCollector.php line 98 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /var/www/mysite/vendor/symfony/http-kernel/DataCollector/DataCollector.php:98)"} []
> [2021-02-04 09:35:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"440485"},"request_uri":"http://apidev.mysite.com/_wdt/440485","method":"GET"} []
> [2021-02-04 09:35:25] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"440485"},"request_uri":"http://apidev.mysite.com/_wdt/440485","method":"GET"} []
> [2021-02-04 09:35:26] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"440485"},"request_uri":"http://apidev.mysite.com/_wdt/440485","method":"GET"} []
> [2021-02-04 09:35:27] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"440485"},"request_uri":"http://apidev.mysite.com/_wdt/440485","method":"GET"} []
> [2021-02-04 09:35:29] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"440485"},"request_uri":"http://apidev.mysite.com/_wdt/440485","method":"GET"} []
