### ISSUE TITLE
Transaction and their propagation management

### ISSUE THREAD

**Issue by TheHett** [symfony/symfony#39651]
The Symfony now uses one global entiry manager (or Document Manager for DoctrineODM, the essence is the same).
It leads to the troubles when we deal with long-lived demons (console applications). For excample we may want to clear UoW in some service, but this will affect other services.

In the Spring Framework this problem is solved by using sessions and transaction propagation levels:
simple article https://www.baeldung.com/spring-transactional-propagation-isolation
full official documentation https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/transaction.html#tx-propagation

It is worth noting that the Spring uses own individual Document Manager for each isolated transaction (session).

Have you considered adding a similar mechanism to the Symfony?
It would be very cool to be able to manage transactions and their propagation level through annotations.

**Comment by rmikalkenas** [comment]
I think this should be discussed in doctrine repository and not symfony as this is purely related with persistence layer..

**Comment by xabbuh** [comment]
I agree with the previous comment. So I am going to close here. Thank you for understanding.

**Comment by TheHett** [comment]
Sorry, my mistake, I thought that all issues for related projects concentrate here, include doctrine.
