### ISSUE TITLE
[Mailer] Can't use >= 3.0 egulias/EmailValidator dep

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#39656]
**Symfony version(s) affected**: 4.4 / 5.1 / 5.2

**Description**  
It is not possible to update to newest `3.0` version (https://github.com/egulias/EmailValidator/releases/tag/3.0.0) because `symfony/mailer` has constraint for using `^2.1.10` version.

**How to reproduce**  
Create project with `composer.json`
```
"egulias/email-validator": "^3.0",
"symfony/mailer": "^5.2",
```

**Possible Solution**  
Modify `symfony/mailer` `composer.json` for allow `^2.1.10|^3.0` or `>=2.1.10`

**Additional context**  
At first look, there is no BC-BREAK changes.

Ready to make PR.

**Comment by derrabus** [comment]
We should allow v2 and v3 to allow users to migrate at their own pace.

> Ready to make PR

Yes please. But please note that `egulias/email-validator` is not only used by Mailer.

**Comment by michaljusiega** [comment]
@derrabus PR is currently opened (https://github.com/symfony/symfony/pull/39657).

**Comment by derrabus** [comment]
New PR: #39685
