### ISSUE TITLE
[Question] Upgrading path from symfony v2.6

### ISSUE THREAD

**Issue by hsuabina** [symfony/symfony#39650]
Hi,

Apologies if this sort of request is not a good fit for an issue, but I couldn't think of any other better place.

I'm working in a monolyth webapp running with symfony v2.6 and we are preparing to bringing it up to more a recent version. I'm looking for advice on what would be the best migration path to update symfony v2.6 to v4.4.

I imagine a hop on v3.4 would be necessary, but I'm uncertain if getting there from v2.6 in one bump would be too much.

~I'm also looking for highlights of passing through specific versions, like for example the [deprecation of the security context component](https://symfony.com/blog/new-in-symfony-2-6-security-component-improvements) which we will have to address as soon as we reach v2.7. Articles like this one or ways to fin these big changes between versions would much appreciated.~ Never mind about this, I just found this [living on the edge](https://symfony.com/blog/category/living-on-the-edge) series of articles which is precisely what I was looking for.

I would still appreciate some thoughts on the migration path, thanks.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
