### ISSUE TITLE
[Security] Impossible to use switch user feature is the token storage is empty with the new system

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#39669]
**Symfony version(s) affected**: 5.2

I'm updating my [workflow demo](https://github.com/lyrixx/SFLive-Paris2016-Workflow) in order to fix a Symfony [issue](https://github.com/symfony/symfony/issues/39505) with the new system but I face an issue. In the demo, I want to show how a workflow behave in function of the connected user. But I did want to add login / form because it's a bit boring for end user to enter all information. I could pre-complete the form but I did not choose this solution. Instead I allowed [anonymous user + added a switch_user firewall](https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/master/config/packages/security.yaml). You can [test the demo](https://symfony-workflow-demo.herokuapp.com/) if you want.

**Description**  

So, before the new system, it was possible to use this configuration:

```yaml
    firewalls:
        main:
            pattern: ^/
            logout: true
            switch_user:
                role: IS_AUTHENTICATED_ANONYMOUSLY
```

Now, it does not work anymore, since Anonymous token are gone. So I hit the following exception:

<details>
Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException:
Could not find original Token object.

  at vendor/symfony/security-http/Firewall/SwitchUserListener.php:109
  at Symfony\Component\Security\Http\Firewall\SwitchUserListener->authenticate()
     (vendor/symfony/security-bundle/Debug/WrappedLazyListener.php:49)
  at Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate()
     (vendor/symfony/security-http/Firewall/AbstractListener.php:26)
  at Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke()
     (vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:62)
  at Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners()
     (vendor/symfony/security-http/Firewall.php:86)
  at Symfony\Component\Security\Http\Firewall->onKernelRequest()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:133)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:28)     
</details>

**How to reproduce**  

use https://github.com/lyrixx/SFLive-Paris2016-Workflow and apply this patch:

```diff
diff --git a/config/packages/security.yaml b/config/packages/security.yaml
index 6ed062e..8b313c8 100644
--- a/config/packages/security.yaml
+++ b/config/packages/security.yaml
@@ -1,4 +1,6 @@
 security:
+    enable_authenticator_manager: true
+
     role_hierarchy:
         ROLE_ADMIN: [ROLE_WRITTER, ROLE_SPELLCHECKER, ROLE_JOURNALIST]
     encoders:
@@ -20,7 +22,7 @@ security:
 
         main:
             pattern: ^/
-            anonymous: true
+            # anonymous: true
             logout: true
             switch_user:
                 role: IS_AUTHENTICATED_ANONYMOUSLY
```

**Possible Solution**  

I naively tested this, and it works

```diff
diff --git a/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php b/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php
index 4d91656a42..897899b288 100644
--- a/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php
+++ b/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php
@@ -15,6 +15,7 @@ use Psr\Log\LoggerInterface;
 use Symfony\Component\HttpFoundation\RedirectResponse;
 use Symfony\Component\HttpFoundation\Request;
 use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\Security\Core\Authentication\Token\NullToken;
 use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
 use Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken;
 use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
@@ -105,7 +106,8 @@ class SwitchUserListener extends AbstractListener
         $request->attributes->remove('_switch_user_username');
 
         if (null === $this->tokenStorage->getToken()) {
-            throw new AuthenticationCredentialsNotFoundException('Could not find original Token object.');
+            $this->tokenStorage->setToken(new NullToken);
+            // throw new AuthenticationCredentialsNotFoundException('Could not find original Token object.');
         }
 
         if (self::EXIT_VALUE === $username) {
```

I can make a PR, just tell me

**Comment by wouterj** [comment]
Hi! Thanks for the detailed report (lots of links to check out :smile: )

I personally don't think we should "fix" this, for 2 reasons:

1. I would argue that this is an unrealistic example that only occurs in demo situations (like your case). I think it's a great unintended side-effect to disallow switching from an unauthenticated session to an authenticated one (and it's fine to break here, the experimental system doesn't have to be BC with the legacy one).  We could do a better job with the exception message though (PR welcome).
2. The `NullToken` is not intended to make it to the `TokenStorage`. Any token in the token storage should be authenticated, to avoid all previous issues with the strange "anonymously authenticated" situation of the legacy system. The `NullToken`'s only function is to be used by voters to grant public access in specific cases (e.g. public blog posts).

**Comment by chalasr** [comment]
I agree that there is nothing to do here.

**Comment by lyrixx** [comment]
OK, let's close this
