### ISSUE TITLE
Symfony Proxy Manager bridge  release version

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [symfony/symfony#39664]
**Description**  
I have seen that inside composer.json of 5.2.x branches of Symfony Proxy Manager there isn't `ocramius/proxy-manager` but tagged versions 5.2.x is with that dependency. 

Is it possible to release a tag without that dependency or with an upgrade of that?

**Comment by wouterj** [comment]
Hi!

Symfony has moved to a fork of Proxy Manager: https://github.com/FriendsOfPHP/proxy-manager-lts/ This will be included in the next release of 5.2, which - given previous release dates - will probably be released somewhere mid-January.

I think this resolves this issue, but I'm not sure if I understood you 100% correctly. If I missed something, please feel free to comment on this issue and we'll reopen :)

**Comment by AlessandroMinoccheri** [comment]
Sorry @wouterj I mean this repository:
https://github.com/symfony/proxy-manager-bridge

If you can see inside composer.json there is `ocramius/proxy-manager` but not in the release version.

**Comment by wouterj** [comment]
Yes, that repository is released together with the rest of Symfony next month (all bridges, bundles and components are split from this monorepository and released at the same time).

**Comment by derrabus** [comment]
@AlessandroMinoccheri You can switch to `^5.2@dev` in your composer.json, if you don't want to wait for the next release.

**Comment by AlessandroMinoccheri** [comment]
Yeah, I know @derrabus but I would prefer to use an official release for another open-source library. At the moment I hope that it could be good enough. 
Thanks.
