### ISSUE TITLE
AcceptHeader::fromString does not correctly detect Turbo Stream 

### ISSUE THREAD

**Issue by beberlei** [symfony/symfony#39673]
**Symfony version(s) affected**: 4.4.18

The Turbo js library makes Ajax requests with an Accept header of the form: `text/html; turbo-stream, text/html, application/xhtml+xml`. This is parsed into just `text/html` and `application/xhtml+xml` and the turbo-stream information gets lost.

See: https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission

**How to reproduce**  

```php
namespace App;

use Symfony\Component\HttpFoundation\AcceptHeader;
use PHPUnit\Framework\TestCase;

class TurboTest extends TestCase
{
    public function testTurboAcceptHeader()
    {
        $accept = AcceptHeader::fromString('text/html; turbo-stream, text/html, application/xhtml+xml');
        var_dump($accept);
    }
}
```

**Possible Solution**  

The header `text/html; turbo-stream` should possible be detected as that and not as `text/html` and then overwritten by the second one.

This also ties into `Request::getPreferredFormat`, I would love in the end to be able to do something like this:

```php
        return match ($request->getPreferredFormat()) {
            'turbo-stream' => [
                new TurboStream('id', 'replace', 'partial1.html.twig', [...]),
                new TurboStream('id2', 'append', 'partial2.html.twig')
            ],
            'html' => ['alerts' => $alerts]
        };

**Comment by dunglas** [comment]
The problem has been fixed in Turbo itself: https://github.com/hotwired/turbo/issues/24
I don't think that we have to change something in Symfony, Turbo's media type was invalid.
