### ISSUE TITLE
Symfony var dumper dump() shows different results as compared to print_r and var_dump when connecting to mysql

### ISSUE THREAD

**Issue by kingx619** [symfony/symfony#39680]
I am using symfony var dumper in my project and It shows deviation in result in comparison to print_r() and var_dump() in PHP . I am using PHP version 8.0 and symfony var dumper version 5.2.1 for connecting to my sql database. Also attaching you an image of the problem. My sql database version is 8.0.22 .

![1](https://user-images.githubusercontent.com/75287291/103454253-2de52080-4d08-11eb-9263-009ac8740791.PNG)

In case of database connection with mysqli it only shown null whereas default functions print_r and var_dump work fine and are giving as expected results

![Capture](https://user-images.githubusercontent.com/75287291/103456888-76a8d380-4d20-11eb-9904-7890acd7e9e8.PNG)

**Comment by derrabus** [comment]
I'll have a look.

**Comment by derrabus** [comment]
This looks like a PHP bug to me. VarDumper internally relies on PHP's object-to-array cast. This cast produces the array that you can see in your output. Try this:

```
$mysqli = mysqli_connect(/* Insert your connection details here */);
var_dump($mysqli);
var_dump((array) $mysqli);
```

The first `var_dump` shows all properties of the `mysqli` object as expected, but in the second call, all properties are set to `null`.

**Comment by kingx619** [comment]
I also tried with a singleton class for the database connection but this time its working...seems like some kind of problem with Symfony var dumper. Symfony var dumper is still showing everything as null
![AB](https://user-images.githubusercontent.com/75287291/103460489-8c2bf680-4d3c-11eb-82a8-67b7b3b94463.PNG)

**Comment by kamil-tekiela** [comment]
@derrabus Can you please report the bug on https://bugs.php.net/

**Comment by derrabus** [comment]
The `(array)` cast is not a deep cast: As you can see, the the `mysqli` instance is still an object in your output. VarDumper however applies `(array)` recursively to all nested objects.

**Comment by kingx619** [comment]
I will be reporting it...thanks a lot for your support...I also have one more problem that has not been looked for over 20 days ...
https://github.com/symfony/cli/issues/380
My symfony installer keeps on crashing after update..and does not work please also do something for that

**Comment by OskarStark** [comment]
@kingx619 please post a Link to the php bugreport here.

Regarding your last issue, keep in mind it was Christmas 🎄 so answers can be a bit slow.

**Comment by kingx619** [comment]
Already reported the bug and it has also been verified .you can have a look here 
https://bugs.php.net/search.php?limit=30&order_by=id&direction=DESC&cmd=display&status=Open&bug_type=All&phpver=8.0&project=PHP

ID: 80575

**Comment by OskarStark** [comment]
Thank you

https://bugs.php.net/bug.php?id=80575

**Comment by xabbuh** [comment]
Let's close here then as this will be fixed in PHP itself.

**Comment by derrabus** [comment]
php/php-src#6587
