### ISSUE TITLE
Incorrect triggered deprecation message: "Please install the "intl" PHP extension for best performance."

### ISSUE THREAD

**Issue by rimvislt** [symfony/symfony#39687]
**Symfony version(s) affected**: 5.2.0

**Description**  

Wrong error that intl not installed.   ==>  "Please install the "intl" PHP extension for best performance."

"extension_loaded('intl') " => true  
"defined('PHPUNIT_COMPOSER_INSTALL')" => false  (because not using phpunit bridge and do not want to use it)

Code part which is causing it:
 › if (!\extension_loaded('intl') && !\defined('PHPUNIT_COMPOSER_INSTALL')) {
        ›     trigger_deprecation('', '', 'Please install the "intl" PHP extension for best performance.');
        › }

**How to reproduce**  

Install intl extension but do not install phpunit bridge, check logs for deprecated error will tell you that intl not installed but it is installed.

**Possible Solution**  

From code:
 › if (!\extension_loaded('intl') && !\defined('PHPUNIT_COMPOSER_INSTALL')) {
        ›     trigger_deprecation('', '', 'Please install the "intl" PHP extension for best performance.');
        › }

Remove part  "\defined('PHPUNIT_COMPOSER_INSTALL')" or define as different error, since it has nothing to do with intl 

**Additional context**

**Comment by derrabus** [comment]
Where is that piece of code coming from?

**Comment by rimvislt** [comment]
Piece of code comes from here:
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L254

**Comment by derrabus** [comment]
All right. For my understanding, _if_ you have `ext-intl` enabled, the expression
```php
!\extension_loaded('intl') && !\defined('PHPUNIT_COMPOSER_INSTALL')
```
should evaluate to false, no matter what that constant is set to, right?

* `extension_loaded('intl')` ➡️ `true`
* `!extension_loaded('intl')` ➡️ `false`
* `false && anything` ➡️ `false`

**Comment by rimvislt** [comment]
Yep you are right after double checking and deleting cache files deprecation message is gone :thinking: 
Thank you for checking this.
