### ISSUE TITLE
[Security] Change "Encode" to "Hash" to avoid any confusion

### ISSUE THREAD

**Issue by TavoNiievez** [symfony/symfony#39698]
As mentioned:

> @paragonie-scott you are right about this. Symfony should replace "encode" by "hash" everywhere. Sadly we cannot do this now because it will be a nightmare to do that change without breaking anything. I know it's not the same, but the docs now explain this misnaming: http://symfony.com/doc/current/book/security.html#dynamically-encoding-a-password

_Originally posted by @javiereguiluz in https://github.com/symfony/symfony/issues/17857#issuecomment-221796049_

`Encode` is an inaccurate term for what is actually done in the security component. `Hash` is the correct term.

I hope you agree that documenting the use of the term in the Symfony context was a temporary solution.

Symfony 5.4 would be a good time to rename all classes where `encode` is used and actually `hash` is done. The use of old names can be deprecated, and then removed in Symfony 6.0

**Comment by fabpot** [comment]
As this is security related, I agree that we must use the right words to avoid any confusion.

**Comment by fabpot** [comment]
Deprecations can happen in 5.3, no need to wait for 5.4.

**Comment by chalasr** [comment]
I'm going to take care of this.

**Comment by chalasr** [comment]
Here we go: #39802
