### ISSUE TITLE
Symfony CLI Installer version 1.1.5 symfony version 4.21.3 closes automatically (Crashes) with video recording Proof

### ISSUE THREAD

**Issue by kingx619** [symfony/symfony#39690]
Installer version is 1.1.5 and symfony version is 4.21.3.. But its crashing.. turning off immediately as i click on the symfony cli in my windows 10 . It turns off itself after clicking..Earlier it was working fine but I am facing this problem since 20-21 days after I updated the cli tool. I have even uninstalled and then installed it from symfony website under downloads section but outcome is the same. I have also verified that my antivirus and firewall is not blocking it

Also posted the same problem here https://github.com/symfony/cli/issues/380

https://user-images.githubusercontent.com/75287291/103471926-c3d28700-4dac-11eb-811c-9d5799ad5275.mp4

**Comment by jderusse** [comment]
Closing this issue, has it's related to cli and not symfony/symfony
