### ISSUE TITLE
[DependencyInjection] Generated getExtractorService tries to include already loaded class

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/symfony#39722]
**Symfony version(s) affected**: 5.2.1

**Description**  

Generated getExtractorService tries to load PhpParser\NodeVisitor with no regard to whether the class is already loaded in PHP runtime:

```php
    /**
     * Gets the private 'Translation\Extractor\Extractor' shared service.
     *
     * @return \Translation\Extractor\Extractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/Extractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/FileExtractor/FileExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/FileExtractor/PHPFileExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/Visitor/Visitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/Visitor/BaseVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-translation/extractor/src/Visitor/Php/BasePHPVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php'; // THIS LINE
```

**How to reproduce**  

Have `PhpParser\NodeVisitor` already loaded from some other location (so that `include_once` doesn't help) and invoke the code that executes `getExtractorService::do()`.

**Possible Solution**  

Wrap the line with `interface_exists` condition.

**Additional context**  

Originally reported as PHPStan issue: https://github.com/phpstan/phpstan/issues/4272

**Comment by nicolas-grekas** [comment]
Adding a function call here looks like a bad idea to me, as that would affect runtime performance, while the issue exists only when doing static analysis.

A workaround could be to turn off these inline `include_once` by setting the `container.dumper.inline_class_loader` parameter to `false`.

An alternative might be to not analyze the dumped container.

**Comment by stof** [comment]
or to analyze it in a static way, without executing it (and so without including the file)

**Comment by ondrejmirtes** [comment]
PHPStan is executing this file because phpstan-symfony and phpstan-doctrine need to access the services in order to analyze Symfony commands (it's getting the actual instances to read the definitions) and to access the EntityManager (to get the real Entity metadata). The user isn't analyzing the dumped container...

**Comment by stof** [comment]
then the solution is to disable the inlining of the class loading.

**Comment by nicolas-grekas** [comment]
> Have PhpParser\NodeVisitor already loaded from some other location

which other location btw?

**Comment by stof** [comment]
@nicolas-grekas phpstan includes PhpParser in its phar.

**Comment by ondrejmirtes** [comment]
Thank you all :)
