### ISSUE TITLE
PHP 8 support issue in handling of current() factories in DI

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#39737]
**Symfony version(s) affected**: 4.4.18

**Description**  
https://github.com/symfony/symfony/blob/9b719ab13d59a4bd3e845d846b675bd098feae6a/src/Symfony/Component/DependencyInjection/Exception/InvalidParameterTypeException.php#L28 does not support ReflectionParameter which are on a function and not a class. `$parameter->getDeclaringClass()->getName()` fails because `getDeclaringClass` returns null.

This only happens on PHP 8 because https://github.com/symfony/symfony/blob/fe91b862c5c549493674217a8f3211707c2b551a/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterControllerArgumentLocatorsPass.php#L155 using `current` in PHP 8 will result in a parameter type hint being `array|object`, while PHP 7 did not have a type hint: https://3v4l.org/YKHtO and apparently Symfony also does not support union types as per @nicolas-grekas.

**How to reproduce**  
I could not reduce it to a minimal repro case sorry

**Comment by derrabus** [comment]
#39746

**Comment by derrabus** [comment]
> apparently Symfony also does not support union types

I'd call it "passive support" for union types: If you can make Symfony 4.4 explode by using a union type in your application, this is a bug we need to fix. 😃

**Comment by derrabus** [comment]
~~#39746 fixes the exception constructor, but you said the exception should not be raised in the first place. A reproducer would really be appreciated here. The exception in question is raised by `CheckTypeDeclarationsPass` and I did fix this pass for union types in #39251. But that fix should've shipped with the 4.4.18 release.~~

**Comment by derrabus** [comment]
Forget what I just wrote. It's late and I should go to bed. 😉 The pass raises the exception internally and drops it if one of the types of the union matches. So #39746 should actually fix your problem.

**Comment by Seldaek** [comment]
Thanks for the quick fix @derrabus, I can confirm it works for me :)
