### ISSUE TITLE
Implement VirtualProperty in Serializer

### ISSUE THREAD

**Issue by Lenny4** [symfony/symfony#39754]
**Description**  
Hi, I was wondering if you planned to implement a `VirtualProperty` as JMS did https://github.com/schmittjoh/serializer/blob/master/src/Annotation/VirtualProperty.php ?

Doc JMS: https://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty

**Example**  
```php
<?php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;
use Symfony\Component\Serializer\Annotation\VirtualProperty; // don't exist

/**
 * @ORM\Entity()
 */
class MyEntity
{
    /**
     * @var int|null
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"myGroup"})
     */
    private $id;

    /**
     * @var string|null
     * @Groups({"myGroup"})
     * @ORM\Column(type="string", nullable=true)
     */
    private $someValue;

    /**
     * @VirtualProperty()
     * @Groups({"myGroup"})
     * @SerializedName("anotherValue")
     * @return string|null
     */
    public function getMyCustomFunction(): ?string
    {
        if (/** something **/) {
            return null;
        } else {
            return 'customValue';
        }
    }
}

```

Thank you !

**Comment by lmasforne** [comment]
Hello Lenny4,

I'm don't understand what is the goal of  `@VirtualProperty()` , if i write this code 

```
/**
     * @Groups({"myGroup"})
     * @SerializedName("anotherValue")
     * @return string|null
     */
    public function myCustomFunction(): ?string
    {
        if (/** something **/) {
            return null;
        } else {
            return 'customValue';
        }
    }
```
I've got a non existent property `anotherValue` with the return of function `myCustomFunction` on my serializer group 
`myGroup`

**Comment by Lenny4** [comment]
@lmasforne 

https://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty

> This annotation can be defined on a method to indicate that the data returned by the method should appear like a property of the object.

**Comment by YaFou** [comment]
The serializer can detect methods like `get*()` or `is*()`. So if I understood, you want explicitly add a new method to be serialized without the previous formats?

**Comment by Lenny4** [comment]
Hi @YaFou I just want the same `VirtualProperty` annotation as JMS, I don't know if it has restrictions on methods (like `myCustomFunction` must start with a `get` si it would be `getMyCustomFunction`) but I think you're right I shloud have add a `get` in my example.

**Comment by YaFou** [comment]
Yes, maybe you have to rename your methods with `get`. However, it would be nice to have an annotation to make the serializer aware of methods despite no `get` in the method name.

---
If you want to experiment, I have created a little application:
1. `git clone https://github.com/YaFou/symfony-39754`
2. `cd symfony-39754`
3. `composer install`
4. `php bin/console app:test`
