### ISSUE TITLE
polyfill-mbstring uses php 7.4 syntax while it supports >7.1

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#39766]
polyfill-mbstring uses php 7.4 syntax while it supports >7.1. Currently a 7.3 version doesn't run on v1.22.0 because of `??=`

https://github.com/symfony/polyfill-mbstring/blob/main/bootstrap80.php#L125

**Comment by derrabus** [comment]
Duplicate of symfony/polyfill#326
