### ISSUE TITLE
\Symfony\Component\Config\Loader::load's phpdoc is missing @return

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#39761]
**Symfony version(s) affected**: all

**Description**  

`\Symfony\Component\Config\Loader::load()` function is intended to return _something_ hence its phpdoc declaration must address it as well.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
Please send a PR, no need for an issue for that.
