### ISSUE TITLE
Yaml dumper unquotes string when using an ideographic space

### ISSUE THREAD

**Issue by jasonvarga** [symfony/symfony#39767]
**Symfony version(s) affected**: 5.2.1

**Description**  

When the Yaml dumper encounters an [ideographic space](https://www.fileformat.info/info/unicode/char/3000/index.htm), the whole string becomes unquoted.

**How to reproduce**  

Here's a unit test to go in `src/Symfony/Component/Yaml/Tests/DumperTest.php`.

```php
public function testDumpIdeographicSpaces()
{
    $this->assertSame("{ alone: '　', within_string: 'a　b', regular_space: 'a b' }", $this->dumper->dump([
        'alone' => '　',
        'within_string' => 'a　b',
        'regular_space' => 'a b',
    ]));
}
```

```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'{ alone: '　', within_string: 'a　b', regular_space: 'a b' }'
+'{ alone: 　, within_string: a　b, regular_space: 'a b' }'
```

Thanks!

**Comment by stof** [comment]
the exact rule is more "when it does not encounter a space (or some of the few other chars that mandate the use of quoting the string), it outputs an unquoted string.
The resulting Yaml is equivalent

**Comment by xabbuh** [comment]
see #39769
