### ISSUE TITLE
Add Symfony template to Github Actions starter workflows

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#39771]
**Description**  
https://github.com/actions/starter-workflows provides basic Github Actions workflows, a selection of them (based on the project type) is suggested when creating your first workflow through the Github UI.

It would be nice to have one for Symfony (Laravel already has one).

An attempt has been made in https://github.com/actions/starter-workflows/pull/526 but abandoned, it could be a good start.

**Comment by Ippey** [comment]
I made the Symfony template below, reference the Laravel one.
I'll make PR to starter-workflow if it has no problem. Would you check it, please?

https://github.com/Ippey/starter-workflows/commit/e307c1a8bb6443eef9ae87a6804afbb0aea034dc

**Comment by Ippey** [comment]
@chalasr Hi, I found this issue and a PR template.

https://github.com/actions/starter-workflows/issues/631
https://github.com/actions/starter-workflows/blob/main/.github/pull_request_template.md

> Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.

[Starter-workflows](https://github.com/actions/starter-workflows) only accepts new starter workflow for code scanning.
It might be rejected if I submit a PR for Symfony template for CI.

Publishing a Symfony starter workflow on [the marketplace](https://github.com/marketplace) by [the Symfony group](https://github.com/symfony/), it might be better, I think.

Thank you.

**Comment by stof** [comment]
starter workflows cannot be published on the marketplace for now AFAIK

**Comment by chalasr** [comment]
closing for now then, will reopen when new starters are welcome again

**Comment by chalasr** [comment]
Fixed in https://github.com/actions/starter-workflows/pull/1069 thanks to @TheGarious.
