### ISSUE TITLE
[HttpClient] Foreach asynchronous behaviour

### ISSUE THREAD

**Issue by pag1903** [symfony/symfony#39789]
**Symfony version(s) affected**: 5.2
**Description**  
When I send a Request the HTTP Client don't behave the same way if I add the Response to an array or if I just assign the Response to a variable.

Array:
`$responses[] = $client->send('GET', 'https://http2.golang.org/gophertiles?x=0&y=0&latency=1000');`
In this case, the Request is submitted then the Response will be fetched on the getContent() call.

Variable:
`$response = $client->send('GET', 'https://http2.golang.org/gophertiles?x=0&y=0&latency=1000');`
In this case, the Response is directly fetched, so the code is still blocked.

**How to reproduce**  
```
$client = Symfony\Component\HttpClient\HttpClient::create();
foreach ([0, 1] as $x) {
    $response = $client->request('GET', "https://http2.golang.org/gophertiles?x=$x&y=0&latency=1000");
}
echo 'FIN'.PHP_EOL;
```

**Comment by nicolas-grekas** [comment]
Hi,

that's expected: doing `$response = ...` erases the previous value of the $response variable, thus calling the destructor of the previous response, leading to this difference.

**Comment by pag1903** [comment]
OK thank you!
