### ISSUE TITLE
[Mailer] Sendgrid Personalizations

### ISSUE THREAD

**Issue by frost-byte** [symfony/symfony#39807]
**Description**  
The current Sendgrid Mailer Transport does not provide a mechanism for specifying Dynamic Template Data.
According to the [SendGrid v3 API Documentation](https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send), the values for Dynamic Template Data should be included in the 'personalizations' section and a template ID also needs to be included.

The SendgridMailer Transport builds the payload for the message using [Symfony\Component\Mime\Email](https://github.com/symfony/mime/blob/5.x/Email.php), however the current interface for that class does not provide any way of specifying custom data fields - it contains the standard fields for an email: subject, sender, recipients, etc.

One way to address this issue would be to add custom data in the form of an associative array.  This would provide a mechanism for any third party/cloud service without having to explicitly define unused/non-standard fields within the Email class.

**Possible Implementation**
[Symfony\Component\Mime\Email](https://github.com/symfony/mime/blob/5.x/Email.php)
```php
    private $customFields = [];

    public function setCustomField(string $field, $value)
    {
        $this->customFields[$field] = $value;
        return $this;
    }

    public function getCustomField(string $field)
    {
         if (key_exists($this->customFields, $field)) {
             return $this->customFields[$field];
         }
         
         return null;
    }
```
[Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridApiTransport](https://github.com/symfony/sendgrid-mailer/blob/f523791455b51545ccfe67398994af33e91e8a3a/Transport/SendgridApiTransport.php#L64)
```php
    private function getPayload(Email $email, Envelope $envelope): array
    {
        //...
        
        // Add Custom Field Data for Dynamic Template, if it exists
        if (
            $templateData = $email->getCustomField('dynamic_template_data') and
            $templateId = $email->getCustomField('template_id') 
        ) {
            $personalization['dynamic_template_data'] = $templateData;
            $payload['template_id'] = $templateId;
        }

        $payload['personalizations'][] = $personalization;
         //...
    }
```

**Example Usage**
```php
    public function sendEmail(MailerInterface $mailer)
    {
        $templateData = [
            'test' => '123'
        ];
        $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            ->subject('Time for Symfony Mailer!')
            ->setCustomField('dynamic_template_data', $templateData)
            ->setCustomField('template_id', YOUR_SENDGRID_TEMPLATE_ID);

        $mailer->send($email);

        // ...
    }
```

**Comment by frost-byte** [comment]
One piece that I've overlooked is the serialization/deserialization, which would probably affect the feasibility of this approach, in terms of compatibility.

**Comment by fabpot** [comment]
That's probably out of the scope of the component. The idea is to be able to move from one provider to another, so the features should be the same on all providers. We do have some abstractions for common extensions like tags, but templating is not one of them (if you are not using Twig, then you should probably not be using Symfony Mailer but Sendgrid's SDK directly).
