### ISSUE TITLE
Unfill Required field doctrine annotation dosn't throw AnnotationException anymore

### ISSUE THREAD

**Issue by Kleinast** [symfony/symfony#39811]
**Symfony version(s) affected**: v5.2.1  v5.2.0 v5.2.0-RC2 v5.2.0-RC1 v5.2.0-BETA3 v5.2.0-BETA2 v5.2.0-BETA1

**Description**  
Just upgrade one project with doctrine/annotations, from 5.0 to 5.2.1
One of my test check that my custom annotation required a field and expect have AnnotationException throwed.
It was the case on 5.0 and it's not anymore on 5.2.1 (it return me a Context)

**How to reproduce**  
```
/** @CustomAnnotation() */
class BadObject
{
}

public function testKeyRequiredOnAnnotation()
{
    $this->expectException(AnnotationException::class);
    $annotationReader = new AnnotationReader();

    $context = new Context(new BadObject());
    $context->annotations = Annotations::createFromContext($annotationReader, $context);
}
```

```
/**
 * @Annotation
 * @Target({"CLASS"})
 */
class CustomAnnotation
{
    /**
     * @Required()
     */
    public $key;
}
```

I think it can be related to this work:
https://github.com/symfony/framework-bundle/commit/2855f3806fb99b2003a5c83544cc49284e1abee7#diff-2d1a74d6155f9146567444b1b6085a0ae69bfc2de0524802f4403596831587ce
and PR https://github.com/doctrine/annotations/pull/125

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce this? Looking at your code sample I don't see how that could be related to the Symfony code.

**Comment by xabbuh** [comment]
Closing as explained, though we can reopen anytime once we are able to reproduce the issue.
