### ISSUE TITLE
I set roles manually by NbAclService.setAccessControl in myCustomAuthService in login method, but when I call isGranted NbAclService.state is empty

### ISSUE THREAD

**Issue by saniyauspanova** [symfony/symfony#39829]
Hello for everyone!
I set roles manually by NbAclService.setAccessControl in myCustomAuthService in login method, but when I call isGranted NbAclService.state is empty.
But if I set settings NbAclService.state in appModule it work right. 

I need use manually set role and I read in other Issue there, that NbAclService.setAccessControl help me)
`export class AuthService {
********
  permissions: NbAccessControl={};
  private currentUserSubject: BehaviorSubject<User>;
  
  constructor(private router: Router, 
    private apiService: ApiService, 
    private nbAclService: NbAclService) {

    this.currentUserSubject = new BehaviorSubject<User>(
      JSON.parse(localStorage.getItem("UserList")) as User
    );

  }
  
  public get currentUserValue(): User {
    return this.currentUserSubject.value;
  }
  login(username: string, password: string, id: number) {
    return new Promise((resolve, reject) => {

      var authData = `grant_type=password&username=${username}&password=${password}`
      
      this.apiService.postFormData('Login/Auth', authData).pipe(take(1))
      .subscribe(
          (res) => {           
            
            let data = res as User

            if (data.access_token) {             
              
              data.Id = id
              data.Name = username

              localStorage.setItem("userList", JSON.stringify(data));
              this.permissions= {
                guest: {
                    view: ['report']
                  },
                user: {
                  create: ['Item', 'dictionary']
                  }
                }
              
              this.nbAclService.setAccessControl(this.permissions);
              this.currentUser.next(data);
              resolve(data);
            } else {
              reject(data);
            }
          },
          (error) => {
            reject(error);
          }
        );
    });
  }`

**use is granted**

`{
export class SidebarComponent {
  constructor(public accessChecker: NbAccessChecker) { 
    
  }

  items: NbMenuItem[] = [
    {
      title: 'Reports',
      icon: {
        icon: 'wrench',
        pack: 'fa'
      },
      hidden: !this.accessChecker.isGranted('view','report')
    },
    {
      title: 'Dictionaries',
      icon: {
        icon: 'wrench',
        pack: 'fa'
      },
      hidden: !this.accessChecker.isGranted('create','dictionary')
    }
  ];
}
}`

Thanks!

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
