### ISSUE TITLE
http client error: Couldn't resolve host name

### ISSUE THREAD

**Issue by do-web** [symfony/symfony#39827]
Sometimes i receive "Couldn't resolve host name for https://......."

Line: 65
symfony/http-client/Chunk/ErrorChunk.php

How can i prevent this kind of error? And i do not why this happend only sometimes.

If i try to debug i get:

Message:
Due to a bug in curl 7.64.0, the debug log is disabled; use another version to work around the issue.

**Comment by do-web** [comment]
Workaround, i switched to the nativeclient.

**Comment by nicolas-grekas** [comment]
Looks like a DNS issue with curl. I don't think we can do anything about it here. Closing therefor.
