### ISSUE TITLE
Deprecation notice when using Framework 4.4 with PropertyAccess 5.2

### ISSUE THREAD

**Issue by jorrit** [symfony/symfony#39830]
**Symfony version(s) affected**: 4.4.18

**Description**

I have FrameworkBundle 4.4.18 and PropertyAccess 5.2.1.

The first argument provided to the `property_access` service used to be a boolean, but is a bitmask since 5.2.
The class `FrameworkExtension` sets this argument based on the boolean configuration property and this triggers the following deprecation warning:

> PHP Deprecated: Since symfony/property-access 5.2: Passing a boolean as the first argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated. Pass a combination of bitwise flags instead (i.e an integer).

**How to reproduce**

1. Install FrameworkBundle 4.4.* and PropertyAccess 5.2.*.
2. Consume the `property_access` service.

**Possible Solution**  

`FrameworkExtension->registerPropertyAccessConfiguration()` could be updated to check if `PropertyAccess::MAGIC_CALL` is defined and then convert the boolean value to the bitmasks before putting this configuration in the container.

```php
...
$magicCall = $config['magic_call'];
if (defined('Symfony\Component\PropertyAccess\PropertyAccessor::MAGIC_CALL')) {
  $magicCall = ($magicCall ? PropertyAccessor::MAGIC_CALL : 0) | PropertyAccessor::MAGIC_GET | PropertyAccessor::MAGIC_SET;
}

$container
  ->getDefinition('property_accessor')
  ->replaceArgument(0, $magicCall)
...
```

If this is acceptable, I'll make a PR.

**Comment by derrabus** [comment]
The PR would be welcome, I guess. :-)
