### ISSUE TITLE
How to use DeauthenticatedEvent event?

### ISSUE THREAD

**Issue by udaypt** [symfony/symfony#39835]
Hi,
I am using `symfony 4.4` and I want to implement some logout cleanup where I need the authentication token of the logging out session.
I tried to follow this documentation
https://symfony.com/doc/current/components/security/authentication.html#authentication-events

Here is what I am trying to do:

```<?php
namespace App\Security\Authentication;

use Symfony\Component\Security\Http\Event\DeauthenticatedEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class LogoutSubscriber implements EventSubscriberInterface
{
	public function onLogout(DeauthenticatedEvent $event)
	{
		$token = $event->getOriginalToken();

		var_dump($token);
	}

	public static function getSubscribedEvents(): array
    {
        return [
            'security.logout_on_change' => 'onLogout',
        ];
    }
}
```

But seems like this code block is not being executed. 

Also, I could not find the definition of `security.logout_on_change` here https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/SecurityEvents.php

Could some one please help me on this? Am I missing anything?

Thanks
Uday

**Comment by chalasr** [comment]
Looks like a documentation bug.
Try using the event FQCN instead:
```
return [
    DeauthenticatedEvent::class  => 'onLogout',
];
```

Could you please reopen this issue on https://github.com/symfony/symfony-docs?

**Comment by udaypt** [comment]
But it didn't work even. I tried 
```
return [
      DeauthenticatedEvent::class => 'onLogout',
 ];
```
As well as 
```
return [
      'DeauthenticatedEvent::class' => 'onLogout',
 ];
```

Both didn't work.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by udaypt** [comment]
> Can you create a small example application that allows to reproduce your issue?

Here is the sample application. Please check the readme file for setup details.
https://github.com/udaypt/symfony4.4-sample

**Comment by YaFou** [comment]
The `DeauthenticatedEvent` event is only triggered when the token was unauthenticated if the user has been changed.
https://github.com/symfony/symfony/blob/d093475ce546dfef738139cd10f90fb718bc4c68/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L261
So, in your example, the user manually logouts. The password didn't change and the token was not refreshed.
Tell me if I misunderstood something.

---

There is a way to customize logout:
1. Before 5.1: https://symfony.com/doc/current/reference/configuration/security.html#reference-security-logout-success-handler
2. After 5.1: https://symfony.com/doc/current/security.html#customizing-logout

**Comment by udaypt** [comment]
> The `DeauthenticatedEvent` event is only triggered when the token was unauthenticated if the user has been changed.

In that case this last statement of this document seems misguiding 🤔 

https://symfony.com/doc/4.4/components/security/authentication.html
It says: `it can help you doing some clean-up task when a logout has been triggered.`

**Comment by YaFou** [comment]
Yes, I think the documentation needs to be changed. I will work on a PR

**Comment by wouterj** [comment]
Thank you @udaypt for your patience and quick reactions to this issue and @YaFou for clarifying the issue here. I'm closing this one as it'll be concluded/continued by symfony/symfony-docs#14846
