### ISSUE TITLE
[PhpUnit-Bridge] Parse error caused by legacy test listener trait

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony#39841]
**Symfony version(s) affected**: main

**Description**  
```
PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')' in /home/runner/work/reset-password-bundle/reset-password-bundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php on line 283
```

**How to reproduce**  
mark a test with `@group legacy` that tests a deprecated method.

**Additional Context**
PHP: `7.2`, `7.3`, `7.4`, & `8.0`
```
...
Installing phpunit/phpunit (8.5.13)
...
Installing symfony/phpunit-bridge (8.5.99)
...
```

**Comment by chalasr** [comment]
A mistake happened while merging up. I'm on it.

**Comment by jrushlow** [comment]
Change appears in https://github.com/symfony/phpunit-bridge/commit/3912cdd2c17e90c56c9acadee043c53af9f3b3c5 https://github.com/symfony/phpunit-bridge/blob/3912cdd2c17e90c56c9acadee043c53af9f3b3c5/Legacy/SymfonyTestsListenerTrait.php#L283

**Comment by jrushlow** [comment]
thanks @chalasr https://github.com/symfony/symfony/commit/4add45d1c93adbd29da5753493b26b91a8a22c8d fixed the problem
