### ISSUE TITLE
[Dependency Injection] Can not remove dependency injection tag in a compiler pass

### ISSUE THREAD

**Issue by soyuka** [symfony/symfony#39845]
**Symfony version(s) affected**: 5.2.x

**Description**  
I can not remove a definition's dependency injection tags.

**How to reproduce**  

Using a compiler pass (note I had the same results trying directly in the Kernel):
 
```php
class RemoveTaggedService implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        $definition = $container->getDefinition('doctrine.orm.default_entity_manager.property_info_extractor');
        $definition->setTags([]);
        $container->setDefinition('doctrine.orm.default_entity_manager.property_info_extractor', $definition);
    }
}
```

In appearance this works, as `bin/console debug:container --tag=property_info.type_extractor` outputs:

```
  property_info.reflection_extractor   -1002      Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor
```

But if you use the `PropertyInfoExtractor` service, you'll see that it does contain the presumably removed `Symfony\\Bridge\\Doctrine\\PropertyInfo\\DoctrineExtractor`.

The reproduction is available at: https://github.com/soyuka/symfony-tag-removal-repro 
1. fork
2. symfony server:start
3. curl -s localhost:8001/basic | jq

It may have something to do with the `cache.property_info` service? 

@Korbeil has a similar issue on normalizers, may you add some additional information?

**Comment by Korbeil** [comment]
Thanks @soyuka for the clean reproducer & issue !
I have same behavior with tags & CompilerPass:

- I have a bundle that adds a Normalizer (with `serializer.normalizer` tag) to the Serializer;
- A CompilerPass that checks some stuff and remove that Normalizer tag and replace it with another Normalizer;
- But when I check the dumped container, my first Normalizer is still the one used in the Serializer.

My bundle Normalizer tag (in the Bundle Extension):
```php
        if ($config['normalizer']) {
            $container
                ->getDefinition(AutoMapperNormalizer::class)
                ->addTag('serializer.normalizer', ['priority' => 1000])
            ;
        }
```

The CompilerPass that update previous Normalizer:
```php
    public function process(ContainerBuilder $container)
    {
        if ($container->has('api_platform.resource_class_resolver') && class_exists(ApiPlatformNormalizer::class)) {
            $container
                ->register(ApiPlatformNormalizer::class, ApiPlatformNormalizer::class)
                ->addArgument($container->getDefinition(AutoMapperNormalizer::class))
                ->addArgument($container->getDefinition('api_platform.resource_class_resolver'))
                ->addTag('serializer.normalizer', ['priority' => 1000])
            ;

            $container
                ->getDefinition(AutoMapperNormalizer::class)
                ->clearTag('serializer.normalizer')
            ;
        }
    }
```

**Comment by lyrixx** [comment]
Hi, 

IMHO, there are nothing wrong here. You are using a "default type" pass with a "default priority".
The `PropertyInfoPass` use the same "configuration". 

So if you want to modify things **before** the `PropertyInfoPass`, you need to set a higher priority than the `PropertyInfoPass` (which is 0).

With your reproducer, If I apply the following diff to be sure your compiler pass is processed before the Property one, Everything work as expected:

```diff
diff --git a/src/Kernel.php b/src/Kernel.php
index 22355e5..4ddc2d6 100644
--- a/src/Kernel.php
+++ b/src/Kernel.php
@@ -4,6 +4,7 @@ namespace App;
 
 use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
 use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\Compiler\PassConfig;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
 use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
 use Symfony\Component\HttpKernel\Kernel as BaseKernel;
@@ -25,7 +26,7 @@ class Kernel extends BaseKernel
 
     protected function buildContainer() {
         $container = parent::buildContainer();
-        $container->addCompilerPass(new RemoveTaggedService());
+        $container->addCompilerPass(new RemoveTaggedService(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
         return $container;
     }
 ```


---

Anyway, thanks for the reproducer, it was easy to reproduce and find what was going wrong here :)

**Comment by soyuka** [comment]
guess the same thing applies to @Korbeil's code :P  thanks @lyrixx 

How did you find the priority to overlap?

**Comment by lyrixx** [comment]
I put something bigger than 0. I randomly chose 100 😁
