### ISSUE TITLE
Does DeauthenticatedEvent work?

### ISSUE THREAD

**Issue by udaypt** [symfony/symfony#39867]
I have made this commit https://github.com/udaypt/symfony4.4-sample/commit/4b42da5de6d8687cea56eae3c01b55976bf7735d

to check if the DeauthenticatedEvent even works with switch-user feature. Unfortunately, I am not able to see it functional here.
Could anyone please help me if I am missing anything or the `DeauthenticatedEvent` has not been implemented properly and it is non-functional at all (even with switch-user feature) in symfony 🤔 

I have tried this documentation:
https://symfony.com/doc/4.4/components/security/authentication.html#authentication-events

My previous discussion (probably associated with this finding)
https://github.com/symfony/symfony/issues/39835

**Comment by YaFou** [comment]
See the following repository: https://github.com/YaFou/symfony-39867
1. `composer i`
2. `bin/console doctrine:database:create`
3. `bin/console doctrine:schema:update --force`
4. `bin/console doctrine:fixtures:load -n`
5. Serve
6. Go to `/login` and login with `email@symfony.com`, `password`
7. Go to `/change-password`
8. See the result

**Comment by udaypt** [comment]
@YaFou I appreciate for this help, but unfortunately I have to do it for symfony 4.4. Could you please help me for this version of symfony?

**Comment by udaypt** [comment]
I see your solution is based on Symfony 5.2, but I have to do it for 4.4

**Comment by chalasr** [comment]
We use github issues for tracking bugs and feature requests only. 
Please check our official support platforms at https://symfony.com/support (slack, stackoverflow, commercial, ...) .

**Comment by YaFou** [comment]
See https://github.com/YaFou/symfony-39867-bis @udaypt
