### ISSUE TITLE
[HttpFoundation] Route not found when URIs contains subdomain (virtualhosts)

### ISSUE THREAD

**Issue by BafS** [symfony/symfony#39882]
**Symfony version(s) affected**: ^5.1.9

**Description**  

https://github.com/symfony/symfony/pull/38614 introduce a BC when using URL rewriting and that the URI contains the same string as the subdomain.

**How to reproduce**  

1. Setup URL rewriting from `domain.com/index.php/api` to `api.domain.com`
2. Add a route containing `/api/` (for example `@Route("/foo/api/bar")`)
3. Go to `api.domain.com/foo/api/bar`, you will have a 404

**Possible Solution**  

Change the if in the PR to not change `$basename` when the URI contains the subdomain where `strpos !== 0`, basically revert the PR.

**Comment by nicolas-grekas** [comment]
/cc @mvorisek could you please have a look?

Alternatively @BafS maybe you know how to fix this and you can send a PR?

**Comment by BafS** [comment]
I don't think there is an easy way to have both behaviors.

This previous data used to pass (if you add it in `RequestTest::getBaseUrlData()` with Symfony <= 5.1.8)

```php
            [
                '/foo/api/bar',
                [
                    'SCRIPT_FILENAME' => '/home/user/public_html/api/index.php',
                    'SCRIPT_NAME' => '/api/index.php',
                    'PHP_SELF' => '/api/index.php',
                ],
                '',
                '/foo/api/bar',
            ],
```

and since the PR it doesn't, the current workaround is simply to extends the Request and revert the `prepareBaseUrl()` changes.

**Comment by nicolas-grekas** [comment]
OK, then I'd be for reverting #38614, and maybe adding a test case to prevent a regression and document the expected behavior. Can you submit one @BafS, please?

@mvorisek please let us know if you think there is a better way.

Right now, our policies would tell us to preserve BC with 4.4.

**Comment by mvorisek** [comment]
It is always a guess. I think we should add support to some specific enviroment variable which webserver can set. As discussed in #38614, the standard server enviroment variables are not enough.
