### ISSUE TITLE
Bug: Cannot use Mailer inside entity listener when having a database log handler

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#39894]
**Symfony version(s) affected**: Symfony 4.4 with Mailer Component 5.2

**Description**  
I have this monolog handler that stores log entries to a `Log` entity in the database: https://nehalist.io/logging-events-to-database-in-symfony/
Now, when I send an email inside an entity listener (`preUpdate` or `preFlush`), PHP hangs either with
> Error: Maximum execution time of 30 seconds exceeded in vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php (line 644)

or

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 327680 bytes) in vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 1337

Reason: [`Symfony\Component\Mailer\Transport\Smtp\SmtpTransport::start()`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php#L247) is writing to the log too.

Workarounds:
* Comment out this line ;-)
* Comment out the database handler in `config/packages/monolog.php`
* Oddly, raising the log level for the `app` channel (=database handler) in `config/packages/monolog.php` to `info` does *not* solve it :-(

**Possible Solution**  
* Is there a way to increase the log level for mailer? Can't find anything on https://symfony.com/doc/current/reference/configuration/framework.html
* Or configure another logger channel for Mailer?

**Comment by jderusse** [comment]
IMHO this is not something in Symfony, but a recursive loop in your application and how you setup each piece (`Log` -> `Database` -> `EventListener` -> `Email` -> `Log`).

I suggest to setup a protection mechanism inside your eventListener
```
if ($this->loop) {
  return;
}
$this->loop = true;
try {
  $this->sendEmail();
} finally {
  $this->loop = false;
}
```

**Comment by ThomasLandauer** [comment]
I can't really see the loop here :-(
The entity listener is defined like so in the entity:
```php
@ORM\EntityListeners({FooListener::class})
```
`services.yaml`:
```yaml
App\EventListener\FooListener:
    tags: ['doctrine.orm.entity_listener']
```
Listener:
```php
public function preUpdate(Foo $foo): void
```
So this should only react on events of a `Foo`, right? So why does the `Log` produced by Mailer interfere with it?

Your code fixes it - but I don't understand why ;-)
So I think I'm going to circumvent the issue by setting the `app` channel to another handler.

I do see this as a bug, cause what I'm doing here isn't "special" or "exotic" - it's even mentioned in the docs explicitly at https://symfony.com/doc/current/logging.html#handlers-writing-logs-to-different-locations

> The logger has a stack of handlers, and each can be used to write the log entries to different locations (e.g. files, database, Slack, etc).

So using standard Symfony features leads to a (BTW very hard to debug) error.

**Comment by jderusse** [comment]
> So this should only react on events of a `Foo`, right? So why does the `Log` produced by Mailer interfere with it?

hard to tell without the code, but persisting new items while EntityManager is flushing and computing the changeSet might recompute everything and triggers your listener with the same event.

Generally speaking, there are 2 things you should do carefully:
- logging (or calling a service that log) inside a LogHandler or LogProcessor
- adding new entity in EntityManager inside an DventListener

**Comment by OskarStark** [comment]
Can you create a small reproducer app? 

Did you think about writing the logs to your database async using message/message-handler mechanism?

**Comment by ThomasLandauer** [comment]
There you go: https://github.com/ThomasLandauer/symfony-issue-39894

The sqlite database is included. Instructions:

1. Open `/test-listener` in a browser and lean back for 30 seconds ;-)

> Did you think about writing the logs to your database async using message/message-handler mechanism?

Well, I didn't want to complicate it more than it already is ;-) So I "fixed" it for me by just sending the `app` channel to a file.

**Comment by jderusse** [comment]
Thank your for this reproducer, I able to reproduce the issue, and confirm what I've told you:

here is the loop (read from the bottom to the top)
```
#51 Monolog\Logger->debug()                                         called at [/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:238]
#52 Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start()  called at [/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:192]
#53 Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend() called at [/vendor/symfony/mailer/Transport/AbstractTransport.php:68]
#54 Symfony\Component\Mailer\Transport\AbstractTransport->send()    called at [/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:132]
#55 Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send()   called at [/vendor/symfony/mailer/Transport/Transports.php:51]
#56 Symfony\Component\Mailer\Transport\Transports->send()           called at [/vendor/symfony/mailer/Mailer.php:42]
#57 Symfony\Component\Mailer\Mailer->send()                         called at [/src/EventListener/FooListener.php:28]

#58 App\EventListener\FooListener->preUpdate()                      called at [/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:112]

#59 Doctrine\ORM\Event\ListenersInvoker->invoke()                   called at [/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1175]
#60 Doctrine\ORM\UnitOfWork->executeUpdates()                       called at [/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:408]
#61 Doctrine\ORM\UnitOfWork->commit()                               called at [/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:371]
#62 Doctrine\ORM\EntityManager->flush()                             called at [/var/cache/dev/ContainerN3nZvcn/srcApp_KernelDevDebugContainer.php:2927]
#63 ContainerN3nZvcn\EntityManager_9a5be93->flush()                 called at [/src/Service/MonologDatabaseHandler.php:33]

#64 App\Service\MonologDatabaseHandler->write()                     called at [/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:42]

#65 Monolog\Handler\AbstractProcessingHandler->handle()             called at [/vendor/monolog/monolog/src/Monolog/Logger.php:317]
#66 Monolog\Logger->addRecord()                                     called at [/vendor/monolog/monolog/src/Monolog/Logger.php:487]
#67 Monolog\Logger->debug()                                         called at [/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:238]
```

1. When logging something: Monolog call your `MonologDatabaseHandler`
2. Your `MonologDatabaseHandler` add a record in the Doctrine **AND** flush the entityManager
3. The entity manager grab the list of items updated and trigger your `FooListener`
4. your `FooListener` send an email
5. the email logs something

It's important to understand here, that triggering a `FLUSH` while the previous `FLUSH` in not yet finished reset the flushing process, and doctrine re-process everything and re-send events
see similar issue: https://github.com/doctrine/orm/issues/6857#issuecomment-347978033

**Comment by ThomasLandauer** [comment]
Thanks for looking into it!

What I still don't understand:
What you're describing is the effect of this line in the controller https://github.com/ThomasLandauer/symfony-issue-39894/blob/main/src/Controller/TestListenerController.php#L19, right? So why does the following happen?:

> The entity manager grab the list of items updated and trigger your `FooListener`

Cause there is no `Foo` involved. I was thinking an entity listener only kicks in if this entity is updated?!

And how could this be prevented *generally*? It's not possible to raise the log level of the `app` channel, cause when the kernel is in debug mode (=default in DEV environment), the log level is always `debug`, right?

What about a switch in `framework.yaml` to disable the Mailer's startup/shutdown log entries? Or another one which allows sending the Mailer's logs to another channel?
In any case, I'd like to mention that this log entry is generated, somewhere on https://symfony.com/doc/current/mailer.html. Is this happening for *all* transports or just for SMTP?

**Comment by jderusse** [comment]
> What you're describing is the effect of this line in the controller https://github.com/ThomasLandauer/symfony-issue-39894/blob/main/src/Controller/TestListenerController.php#L19, right? So why does the following happen?:

nop, the loop started here https://github.com/ThomasLandauer/symfony-issue-39894/blob/main/src/Controller/TestListenerController.php#L27 

When you **flush** a the EntityManager _that_ contain a Foo object _that_ trigger your listener _that_ trigger the mailer that _logs_ a message _that_ trigger your handler _that_ persist an object in EM and **flush** the EntityManager _that_ still contain a Foo Object

**Comment by xabbuh** [comment]
Closing here then as there is nothing to fix.
