### ISSUE TITLE
Let's form handle the success !

### ISSUE THREAD

**Issue by Cartman34** [symfony/symfony#39908]
**Description**  
In my apps, controllers are generating success messages for every forms but I have to do some complicated thing to bring the message to the template to insert it in the right place in the rendered form.
Currently, Symfony is only suggesting to use the flash messages but in my opinion, this is not appropriate for most cases.
But in fact, Symfony/form should handle it as it handles the errors...

**Example**  

CountryController.php
```php
$countryForm = $this->createForm(CountryForm::class, $country);
if( $countryForm->isSubmitted() && $countryForm->isValid() ) {
	// Country is saved
	$countryForm->addSuccess('country.update.success', ['name' => $country->getName()])
}
```
Twig file
```
form_success(countryForm)
```
The way we are using it is not so important but I think the feature is required to produce a clean code.
We could also suggest to add a success message on a field, or a success mark.

**Comment by xabbuh** [comment]
The proposal would only work if the same controller that handled the form was also displaying the success message. As soon as you use a redirect (which is done most of the times from my experience) this will break as the context gets lost.

**Comment by Cartman34** [comment]
Yes, you are right, I forgot that. But I am never redirecting, to never lose context, it's the most important for me.
This could be implemented to be compatible with both case if symfony/form tries to get the success messages about this form from the session.

**Comment by xabbuh** [comment]
IMO if we added such a method which would only work under certain circumstances that would cause too much confusion. I suggest to create some userland solution in your application instead.

**Comment by stof** [comment]
Given that the best practice is to redirect (so that a browser refresh does not re-submit the form), I agree with @xabbuh that this does not belong to the core.

**Comment by derrabus** [comment]
Same here. That's 3x 👎🏻 , let's close this ticket. Thank you very much for proposing that feature, though.

**Comment by Cartman34** [comment]
Currently, FormInterface and Form class does not provide any way to handle it, I need to wrap it under one of my object, it looks more like a hack than a real feature because FormInterface does not provide any way to add custom data from the controller, this is a limiting point.
If the feature is handling success messages like FlashBag does (or using FlashBag), you will be able to show success messages automatically through redirections.

But it seems I am the only one showing success message on my app...

**Comment by stof** [comment]
@Cartman34 if you redirect after submitting a form, you won't ever have a template where you can do `form_success(countryForm)`:

- the template after redirection don't have the form object
- the template rendering the form is not called in case of success

For flash messages, use `$this->addFlash('success', $message);` in your controller to add a success flash message.

**Comment by Cartman34** [comment]
When you have a form to edit an entity, It's very rare to redirect to smething else the edit form, you generally want to stay on the same page. It makes sense for me and for my customers and users...

I thought about the redirection... If you are only redirecting with success, you are not preventing form refresh if an error occurred, so this argument has no value. And If this is about to no insert several times the same entity... You must check about duplicates, in all cases, the redirection should not be the only solution.
But in this case, redirecting is preventing possible complexe calculation in case of refresh.
And I know I will add more redirection to my apps, but no in all cases, not in the case of entity edition, because we stay on the same page and refresh are idempotent.

**Comment by stof** [comment]
> I thought about the redirection... If you are only redirecting avec success, you are not preventing form refresh if an error occurred, so this argument has no value.

But re-submitting the invalid form is not an issue, as such case has not saved the change anyway

**Comment by Cartman34** [comment]
If the form is created multiple entities and you want to continue to save good ones and report error for wrong ones.
So you can not redirect and you want to report success for those who the script succeeded to save.

In the idyllic case, IMO, the form should report all messages from any type (info, warning, success, errors, ...), it's not only the business of errors. It's really improving UX.
