### ISSUE TITLE
[Validator] Attribute::TARGET_PARAMETER is missed in constraints

### ISSUE THREAD

**Issue by kubk** [symfony/symfony#39901]
**Symfony version(s) affected**: 5.2

**Description**  
I'd like to use PHP 8 property promotion feature. To make Symfony constraints work with it TARGET_PARAMETER is needed. Currently, there are only \Attribute::TARGET_PROPERTY,  \Attribute::TARGET_METHOD, \Attribute::IS_REPEATABLE: 
https://github.com/symfony/symfony/blob/c6100bc3867c7d13da8506bb73b583c841af3e35/src/Symfony/Component/Validator/Constraints/NotBlank.php#L24

**How to reproduce**  
```php
use Symfony\Component\Validator\Constraints as Assert;

class Dto
{
    public function __construct(
       #[Assert\NotBlank] public  $id
    ) {
    }
}
```

**Solution**  
Change this line:
https://github.com/symfony/symfony/blob/c6100bc3867c7d13da8506bb73b583c841af3e35/src/Symfony/Component/Validator/Constraints/NotBlank.php#L24

To this:
```php
#[\Attribute(\Attribute::TARGET_PARAMETER | \Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
```

This fix should be applied to other constraints too like GreaterThan, Count, Email, etc.

**Additional context**  
The same fix has been merged to API Platform: https://github.com/api-platform/core/issues/3949

**Comment by xabbuh** [comment]
I doubt that just making this change is sufficient if I understood correctly what you are trying to achieve. The validator would still not validate the method argument as that's not a supported feature.

**Comment by YaFou** [comment]
@xabbuh I think the attributes are supported as a property of the class and not parameters. It needs testing.

**Comment by YaFou** [comment]
You can test this:
```php
<?php

#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
class Foo
{
    public function __construct(public $baz)
    {
        
    }
}

class Dummy
{
    public function __construct(#[Foo("Hello world!")] public $bar)
    {

    }
}

$reflection = new ReflectionClass(Dummy::class);
$attribute = $reflection->getProperty('bar')->getAttributes()[0];
$attribute = $attribute->newInstance();
var_dump($attribute);
```

@kubk I don't understand your request because the code above works without declaring the parameter scope in the attribute.

**Comment by kubk** [comment]
@YaFou Thank you, I'll try to provide a reproducible demo on GitHub. In my project there is no error, but the property isn't validating.

**Comment by derrabus** [comment]
When using property promotion, the attribute is attached to both, the constructor parameter **and** the property. So, you'll technically get two attributes here. This is fine as long as you don't try to call `newInstance()` on the parameter attribute.

https://3v4l.org/HfGE1

As long as we don't evaluate attributes on parameters anywhere, I don't feel like we should target parameters.

**Comment by YaFou** [comment]
I have created a small project and I found no issue @kubk: https://github.com/YaFou/symfony-39901

**Comment by kubk** [comment]
@YaFou Thank you, looks like it's my setup issue and not a Symfony issue. :+1:
