### ISSUE TITLE
[Configuration]  $node->validate()->ifNull()->thenUnset() is not compatible with environment-based parameters

### ISSUE THREAD

**Issue by melkamar** [symfony/symfony#39902]
**Symfony version(s) affected**: 5.1.10

**Description**  

The combination of having environment-based parameters and Configuration with optionally-unset values does not work. I have encountered this in Doctrine ODM but it reproduces in everywhere.

**How to reproduce**  

## Setup
Take this Node configuration:
```php
->scalarNode('username')
    ->validate()->ifNull()->thenUnset()->end()
->end()
```

Imagine we are creating a parameter in an `Extension` class based on whether the `username` is null:
```php
if (array_key_exists('username', $config)) {
    $container->setParameter('some_parameter_if_username_exists', $config['username']);
}
```

And this parameter is then consumed by a service:
```php
class SomeService {
    public function __construct(ParameterBagInterface $params)
    {
        var_dump($params->get('some_parameter_if_username_exists'));
    }
}
```

Let's see what happens in four different scenarios.

### Non-null static value 🆗 
```yaml
# config.yml

username: static-username
```

```
# stdout/err

# string(15) "static-username"
```

### Null static value 🆗 
```yaml
# config.yml

username: ~
```

```
# stdout/err

#  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
# The parameter "some_parameter_if_username_exists" must be defined.
```
This is expected. The username config value is null, so it is unset and does not exist -> accessing it causes a crash.

### Non-null environment-based value 🆗 
```yaml
# config.yml

username: '%env(string:default::USERNAME)%'
# USERNAME=env-based-value
```

```
# stdout/err

string(15) "env-based-value"
```

### Non-null environment-based value ⛔ 
```yaml
# config.yml

username: '%env(string:default::USERNAME)%'
# === USERNAME is not defined ===
```

```
# stdout/err

NULL
```

This is incorrect. The behavior should be the same as with the null-static-value. This shows that passing `null` directly and through the `%env()%` notation **behaves differently**.

## Actual problem
The above example was the most simplified version of this issue I could come up with. The actual problem where this came up is with my Doctrine ODM configuration. I want to move the config to be environment-based (for better containerization support) and it needs to support connecting to Mongo both with and without credentials. Hence:

```yaml
doctrine_mongodb:
    connections:
        default:
            options:
                username: '%env(string:default::MONGODB_USERNAME)%'
                password: '%env(string:default::MONGODB_PASSWORD)%'
```

This works when username and password are provided. But it breaks down when those values are empty. Because in that case Doctrine will attempt to create a Mongo Client class ([see code](https://github.com/mongodb/mongo-php-library/blob/b6d178f6738c5e0c8c3b49413d203c9d58f68460/src/Client.php#L129)) with 
```php
$uriOptions = [
    'username': null,
    'password': null
```
When it should actually be an empty array. This fails because the Manager class assumes that when the `username` key exists in the array, it will be non-null. 

And this all goes back to Symfony passing in a `null` value instead of removing the value altogether as requested by `->validate()->ifNull()->thenUnset()->end()`.

**Possible Solution**  

**Additional context**

**Comment by stof** [comment]
The thing is, it **cannot** remove the value. the whole point of `%env(...)%` is that these env variables are resolved at runtime (without requiring a cache clearing). This means that the compilation of the container cannot depend on the values.

If the ODM bundle wants to support using env placeholders for this config, it must make sure that it can support a case where `null` is only known at runtime.

**Comment by melkamar** [comment]
I see your point. I don't know enough about the internals of how the config resolving work but I understand the reason why this doesn't work. So that means that there's nothing I can do to fix my case, other than fixing ODM to work with nulls?

From what you said it then follows that "normal" and "environment-based" variables cannot be used interchangeably. I think this would be good to mention in [the documentation](https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables) because that's not obvious to first-time users. What do you think?

**Comment by nicolas-grekas** [comment]
Closing as there is nothing to do in this repo, as explained by @stof 
PR welcome on the doc of course. "Not all config options are compatible with env vars", that's the pitch :)
Dunno if patching ODM could help, I'll let you check there.
