### ISSUE TITLE
Autowire ServiceLocator with iterable of tagged services

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#39924]
**Description**  

Use attributes to have autowiring between ServiceLocator and tagged services, by key that can be either FQCN (default) or allow users to define it. Upgrade of implementation: https://github.com/symfony/symfony/issues/29203

**Example of FQCN index, along with psalm annotation use:**

```php
class MyService
{
    public function __construct(
        #[Tagged(name: 'form.type')] private ServiceLocator $tagged
    ) {}
    
    /**
    * @param class-string<FormTypeInterface> $className
    */
    public function get(string $className): FormTypeInterface
    {
        return $this->tagged->get($className);
    }
}

$formType = $myService->get(EntityType::class);
```

---

If users want different index (like #29203), optional parameter would be the name of static method used:

```php
interface ExporterInterface
{
    public static function getName(): string;
}

class CSVExporter implements ExporterInterface
{   
    public static function getName(): string
    {
        return 'csv_exporter';
    }
}

class MyService
{
    public function __construct(
        #[Tagged(name: 'app.exporter', indexMethod: 'getName')] private ServiceLocator $tagged
    ) {}
    
    public function get(string $name): ExporterInterface
    {
        return $this->tagged->get($name);
    }
}

$exporter = $myService->get('csv_exporter'); // this would be instance of CSVExporter
```

---

If of any relevance, stub for ServiceLocator can be this:

```php
/** 
 * @template T
 */
class ServiceLocator
{
    /** @return T */
    public function get($id){}
}
```

**Comment by zmitic** [comment]
Best case would be to allow interface usage instead of string-based tag names:

```php
class MyService
{
    public function __construct(
        #[TaggedInterface(FormTypeInterface::class)] private ServiceLocator $tagged
    ) {}
    
    /**
    * @param class-string<FormTypeInterface> $className
    */
    public function get(string $className): FormTypeInterface
    {
        return $this->tagged->get($className);
    }
}

$formType = $myService->get(EntityType::class);
```

A feature like this could be useful for a day we get generics; tools like rector might provide automigration:

```php
public function __construct(private ServiceLocator<FormTypeInterface> $tagged)
```

**Comment by nicolas-grekas** [comment]
> `#[Tagged(name: 'form.type')]`

This looks like just one step after #39897 - could happen in 5.3 :)

> `#[TaggedInterface(FormTypeInterface::class)]`

I would clearly advise against this. It's a shortcut that forgets that tags are absolutely required as intermediaries to create collections of services in a decoupled way.

But fortunately, together with #39804, you might end up being able to provide a very similar DX.

**Comment by zmitic** [comment]
>I would clearly advise against this.

That is OK. My tagged services have same name as interface i.e. 

```php
$container->registerForAutoconfiguration(ExporterInterface::class)->addTag(ExporterInterface::class);
```

so I thought to maybe even remove this one line. But yes, it might be too much, sorry.

**Comment by nicolas-grekas** [comment]
PR welcome @zmitic

**Comment by zmitic** [comment]
@nicolas-grekas For ``#[TaggedInterface]``? 

If so; would I be allowed to create another class instead of ``ServiceLocator``, and add stubs like in the first comment?

**Comment by nicolas-grekas** [comment]
For `#[Tagged(name: 'form.type')]` (see above about `#[TaggedInterface]`)

**Comment by zmitic** [comment]
@nicolas-grekas 

I am sorry I didn't have time for this before.

Before I start, just to confirm: 

- unless ``indexAttribute`` is defined, keys should be class names instead of integers; correct?

---

I.e. instead of this way to get class-name based index:

<details>
  <summary markdown="span">Copy&paste from real project</summary>

```php
class MyMainService
{
    public function __construct(
        #[TaggedLocator(tag: ViewFactoryInterface::class, indexAttribute: 'default')] 
        private ServiceLocator $tagged,
    )
    {
    }
}

abstract class AbstractViewFactory implements ViewFactoryInterface
{
    public static function getDefaultName(): string
    {
        return self::class;
    }
}
```
</details>

it should work this way when ``indexAttribute`` is null. Is this correct?

**Comment by zmitic** [comment]
With latest @fractalzombie patch, everything works perfectly.

Thank you all.
