### ISSUE TITLE
[Features] Wavy welcome page

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#39925]
I love the job you did with the welcome interface since SF4. It happens on my website that I use similar wavy shapes as you did, but animated with some basic javascripts. So I just had fun and tried to make something like a mix. It's lightweight, responsive and configurable (more & deeper waves !).

[welcome.html.php.txt](https://github.com/symfony/symfony/files/5851111/welcome.html.php.txt)
EDIT: IT looks like this on my website https://www.glitchr.io/

**Comment by derrabus** [comment]
Thank you for your feedback. Happy to hear that you like the welcome page.

If you want to suggest changes to that page, you can do so by submitting a pull request instead of attaching files to an issue. I'm closing this issue now because it does not contain a bug description or a feature request.
