### ISSUE TITLE
[Contracts] symfony/contracts is not replaced in symfony/symfony

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#39934]
In symfony 4.4.X I noticed multiple existing definitions of the Cache Interfaces. After looking at them they are in the symfony package and also the symfony/contracts package. Same in the newest 5.X release.
I am pretty sure this has some (composer related?) reasons but why is the contracts package even additionally required?

Sorry if it is asked regularly. I did not find an issue or documentation of this. Is there anything we can do to be able to replace the package in symfony?

**Comment by nicolas-grekas** [comment]
Contracts are versioned separately from other Symfony components. That's why.

From what I understand, you're using `symfony/symfony` to get all components at once. This is a discouraged practice and it may stop working in the future.

You should reference individual components instead, including individual contracts.

**Comment by simonberger** [comment]
Thank you for the informations. It does not answer though why `symfony/contracts` is included in the `symfony/symfony` package at all then and not just required.

Apart of this I am aware that the symfony flex approach is recommended and we are on the way to it. It just takes some time for old monolith projects.

**Comment by nicolas-grekas** [comment]
It's part of the source because that's how the development happens, on this very repo.
I guess we could remove it from dist archives using .gitattributes.

**Comment by stof** [comment]
The `symfony/symfony` package contains the source code but does not register it for autoloading. So your project won't have duplicate class definitions.

> I guess we could remove it from dist archives using .gitattributes.

that would be a good idea (also for the PHPUnit bridge which is not replaced either)
