### ISSUE TITLE
Bitly v4 bundle

### ISSUE THREAD

**Issue by phplicengine** [symfony/symfony#39937]
Sorry, if I am in a wrong place to ask because I cannot use Slack.
I wanted to ask if there is any Bitly v4 bundle for Symfony? I appreciate if you tell me some bundles for this, as I searched and found several bundles for bitly v3 which is deprecated.

**Comment by stof** [comment]
This issue tracker is only used for tracking issues in symfony itself, not for general discussion about the ecosystem.
