### ISSUE TITLE
[Security] Configuration definition does not respect configuration merging

### ISSUE THREAD

**Issue by nusje2000** [symfony/symfony#39939]
**Symfony version(s) affected**: All versions since 3.4 ([commit that introduced the bug](https://github.com/symfony/security-bundle/commit/06393dac7bcf60912e999c41884d72dd66fd6ab4))

**Description**  
The security bundle grants you the option to define a access_decision_manager strategy. The default value for this configuration is "affirmative". However the way this default is set, does not respect the configuration merging that is done before processing the configuration. The default is set while normalizing the individual configuration arrays, so each config will have its own value for the strategy even when this is not explicitly set in the configuration itself:
```php
// Configs before normalization
$configs = [
    [
        'access_decision_manager' => [
            'strategy' => 'unanimous',
        ]
    ],
    [
        'encoders' => [],
        'providers' => [],
        'firewalls' => []
    ]
];

// Configs after normalization
$configs = [
    [
        'access_decision_manager' => [
            'strategy' => 'unanimous',
        ]
    ],
    [
        'encoders' => [],
        'providers' => [],
        'firewalls' => [],
        'access_decision_manager' => [
            'strategy' => 'affirmative',
        ]
    ]
];

// Merged configuration
$configuration = [
    [
        'encoders' => [],
        'providers' => [],
        'firewalls' => [],
        'access_decision_manager' => [
            'strategy' => 'affirmative',
        ]
    ]
];
```
In this example you can see that even although the strategy is set to "unanimous" by the first config set, it is overwriten by the default "affirmative" strategy because the default is set while normalizing the configuration sets. I would expect the output to be similar to this:
```php
$configuration = [
    [
        'access_decision_manager' => [
            'strategy' => 'unanimous',
        ]
        'encoders' => [],
        'providers' => [],
        'firewalls' => []
    ]
];
```

**How to reproduce**  
When in a symfony project with security set up, configure the strategy in the securiy.yaml like this:
```yaml
security:
    access_decision_manager:
        strategy: unanimous

    // ... other security configuration
```
Then add a `security_dev.yaml` that is loaded when in the dev environment:
```yaml
security:
    // ... dev security configuration
```
Make sure both configurations are loaded when in the dev environment:
```yaml
// config.yaml
imports:
    - { resource: security.yaml }

// ... other config
```
```yaml
// config_dev.yaml
imports:
    - { resource: config.yaml }
    - { resource: security_dev.yaml }

// ... other config
```

**Possible Solution**  
At first I thought that the solution would be to use the `defaultValue()` function when defining the configuration, but I found out that this was the case [a few years ago](https://github.com/symfony/security-bundle/commit/06393dac7bcf60912e999c41884d72dd66fd6ab4#diff-7b64e0832f4269117765021ddef60d6bb4bb2a00917273ac3cd7e9274f73eb19L76) and this was changed to [defining the default while normalizing](https://github.com/symfony/security-bundle/commit/06393dac7bcf60912e999c41884d72dd66fd6ab4#diff-7b64e0832f4269117765021ddef60d6bb4bb2a00917273ac3cd7e9274f73eb19R62-R81) because the `service` option was added, and having a default value was not possible since this would conflict with the [validation](https://github.com/symfony/security-bundle/commit/06393dac7bcf60912e999c41884d72dd66fd6ab4#diff-7b64e0832f4269117765021ddef60d6bb4bb2a00917273ac3cd7e9274f73eb19R101-R104). Because either `service` or `strategy` can be defined and not both, I can't think of a solution strait away.

A solution might be to add a bit of documentation to [How to Use Voters to Check User Permissions](https://symfony.com/doc/current/security/voters.html#changing-the-access-decision-strategy) explaining that the strategy configuration must be defined explicitly in each security configuration file.

**Additional context**  
In a project I'm working, this "bug" is currently occurring, but fortunately I'm not allowed to share these configurations.

**Comment by OskarStark** [comment]
Can you please setup a small reproducer repository?

**Comment by wouterj** [comment]
Hi! Thanks for the detailed issue description!

This bug has already been reported in #25609, so I'm going to close this one as a duplicate.

**Comment by nusje2000** [comment]
@OskarStark @wouterj thanks for reviewing this issue, if I can provide any further information, I'll be happy to help 👍
