### ISSUE TITLE
Symfony5: setting ['required'=>false] to the form prevents overriding "required" in fields

### ISSUE THREAD

**Issue by Ser5** [symfony/symfony#39943]
**Symfony version(s) affected**: 5.2.1

**Description**  
The issue stems from here:
https://stackoverflow.com/questions/65823351/symfony5-forms-how-to-disable-required-for-all-fields-by-default

Symfony has the `required` flag enabled by default for all form fields - the feature I don't need, I need to have it backwards - to have all fields **not required** by default.

I have two methods on my mind to do this:
1. Set `['required'=>false]` to the very top **form**
2. Force `['required'=>false]` via an **extension**

But both methods produce puzzling results:
* If I don't set any `required` on the **form**, then for the individual **fields** I can set `required` to whichever I want - `true` or `false`
* If I set `['required'=>true]` on the **form**, I can freely override `required` also
* But if on the form I set `['required'=>false]`, then Symfony refuses to override `required` on any individual **field** - `required` stays `false` forever
* The same results I get when forcing `['required'=>false]` with the help of an **extension**

For the demonstration see **the test project** I put on github. It creates a **form and 3 fields** inside it.
* 1st field uses default `required`
* 2nd one uses `['required'=>true]`
* 3rd one uses `['required'=>false]`

When you run the `index.php` from CLI, it shows `required` values for these **3 fields**.

You can modify the behavior of the **form** by using **command-line options**:
* No options - form with default `required`
* `--set=form --required=true` - form with `['required'=>true]`
* `--set=form --required=false` - form with `['required'=>false]`
* `--set=ext --required=false` - form with `required` forced to `false` via an extension

**How to reproduce**  
https://github.com/Ser5/SymfonyRequireBug

	git clone https://github.com/Ser5/SymfonyRequireBug.git
	cd SymfonyRequireBug/lib/
	composer install
	cd ../

	php index.php
	php index.php --set=form --required=true
	php index.php --set=form --required=false
	php index.php --set=ext --required=false

The main question is: is this behavior intended? I find it totally confusing and counterintuitive. Or is this a bug? Should it be fixed?

**Possible Solution**  
Allow overriding `required` on form fields despite the value set on the form.

**Additional context**  
Windows 10
PHP 8

**Comment by Ser5** [comment]
Are there any updates? Is it a bug or a feature?

I was poking the code here and there myself. What I found:

* Fields in the [Form](https://github.com/symfony/form/blob/5.x/Form.php) object doesn't use any options inheritance
* Options inheritance is applied inside [createView()](https://github.com/symfony/form/blob/58639b92c062c291bc5fef3556b9ffcdd268f370/Form.php#L1027) method
* There is a loop inside, which creates views for all the children by calling `$child->createView($view)`
* Then, for each child, it enters `$type->buildView($view, $this, $options);`
* Where it calls `$this->parent->buildView($view, $form, $options);` - where the parent is the form itself
* Inside the form it calls `$this->innerType->buildView($view, $form, $options);`
* Which goes into [FormType::buildView()](https://github.com/symfony/form/blob/58639b92c062c291bc5fef3556b9ffcdd268f370/Extension/Core/Type/FormType.php#L81)
* Containing `array_replace()`, which replaces view vars with some other values, where the `required` is replaced by the result of `isRequired()` method
* That `isRequired()` - it's called for each child (form field), and each child is an instance of `Form`
* Therefore, for checking a field `required` value, [Form::isRequired()](https://github.com/symfony/form/blob/58639b92c062c291bc5fef3556b9ffcdd268f370/Form.php#L241) is called
* That method contains some odd code: it first checks vars of the parent element, which is in our case is a form:
	1. If the form has `required=true`, the field returns it's own value - which can be `true` or `false`
	2. But if the form has `required=false`, the field ignores everything and always returns `false`
	3. Also, if we didn't explicitly set form's `require` to anything, it defaults to `true`, and everything acts as variant 1

As a result, whenever a form has `required=false`, all the fields are forced to have `required=false` also.

I see this as a bug, and understand as follows: `required` has only two possible values - `true` and `false`, and mixes two behaviors - "*whether the value is set/not set*" and "*whether the value has true/false*":   
* When `required` has `true`, Symfony silently assumes that it can be a default value and allows to override it
* When `required` has `false` for the parent element and `true` for the child element, Symfony assumes that `false` one is set manually by the user, and `true` one is the default - then skips that "default", inheriting "manual" `false`

Actually `required` should has three states: `not set`, `true`, `false`:   
* If `not set`, then inherit from a parent type, or use default hardcoded - `true` for example
* `true` - use `true`, don't inherit, don't use default value
* `false` - use `false`, don't inherit, don't use default value

Is this info useful for the issue?

**Comment by xabbuh** [comment]
Even though this can be confusing I think that the current behaviour is correct. If a parent type is not required, rendering its children as required would be confusing. Or put differently: If the child is required, its parent would then have to be required too. Does that make sense?

**Comment by xabbuh** [comment]
I am going to close here as I don't think there is anything that needs to be changed (see my previous comment). Though please feel free to comment if you don't agree or if you have further questions and we can consider to reopen.

**Comment by VincentLanglet** [comment]
I just found this issue, and it's really confusing @xabbuh, I think it should be reopen.

There is often a `*` used in order to tell if a field is required or not.
When I use a CollectionType, I do not want this `*` since adding a row to the collection is not required
![image](https://user-images.githubusercontent.com/9052536/118800656-74df4700-b8a0-11eb-966f-8985669ac38b.png)

But if I use `required => false` on the CollectionType, I lose the `required` attribute on all the children
![image](https://user-images.githubusercontent.com/9052536/118800879-aeb04d80-b8a0-11eb-8edb-9cb66cacd9e9.png)
Become 
![image](https://user-images.githubusercontent.com/9052536/118800978-cbe51c00-b8a0-11eb-86fd-fd62248376d8.png)
And I'm looking for 
![image](https://user-images.githubusercontent.com/9052536/118801112-f33be900-b8a0-11eb-8999-d941a539d98d.png)

**Comment by xabbuh** [comment]
@VincentLanglet Please open a new issue. I think your case is more special than the generic request where this issue came from.

**Comment by VincentLanglet** [comment]
Done @xabbuh https://github.com/symfony/symfony/issues/41368

**Comment by willherzog** [comment]
@Ser5 If you're still looking for a solution, I discovered that this can be accomplished with a form extension that applies to each type directly (e.g. ChoiceType, TextType, etc.) rather than extending FormType. @xabbuh The issue is that FormType is technically a parent form and thus setting required false on it (i.e. in a form extension) overrides that option on *every* form type. It would be nice if there were a more convenient way to change the default while still preserving the parent > child behavior you cited.

**Comment by renepupil** [comment]
> If a parent type is not required, rendering its children as required would be confusing.

@xabbuh I also think the current behavior is more confusing: most default options set on form class can be overwritten or extended by field options (e.g. label, constraints etc.).

Therefore it makes it more similar to other options if the "required" attribute in a field option overwrites the default required "false"...

**Comment by Kryyto** [comment]
I'd like to add that calling `required` a boolean is misleading. Sure it IS a boolean, but in practice it's not used like most would think at first.

For whatever reason, boolean attributes are true when existing and false if missing.

Which means that the correct writing is not: `required="true"` or `required="false"`
But this: `required` or nothing if you want it false

Where I got this info:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

Some example provided:
![image](https://github.com/symfony/symfony/assets/69859497/cf45983a-ba03-4df1-a12e-e2d35ad477a1)

**Comment by stof** [comment]
Setting a *boolean* value in the PHP config does not set `require="true"` or `required="false`. `true` and `'true'` are 2 different things

**Comment by stof** [comment]
And boolean attributes in the HTML spec are precisely the ones for which the presence or the absence of the attribute is relevant. that's the official name for this concept: https://html.spec.whatwg.org/#boolean-attributes

**Comment by Kryyto** [comment]
> Setting a _boolean_ value in the PHP config does not set `require="true"` or `required="false`. `true` and `'true'` are 2 different things

That's right, and that's where some people (me included) might be confused. Just wanted to point it out.

**Comment by stof** [comment]
Well, using a PHP boolean to configure boolean attribute makes perfect sense as an API. and it is much easier to use than forcing to conditionally set the key in the array of attributes. And it allows our rendering logic to support any attribute without hardcoding which ones are boolean attributes and which ones are not (anything containing a boolean value is treated like a boolean attribute, for which `false` avoids putting the attribute in the HTML).
Changing boolean attributes to consider any configured value (including the boolean `false`) to mean that the boolean attribute is present in the HTML is a no-go IMO: 
- it makes the API harder to use
- it is a big BC break for the ecosystem
- it probably forces to hardcode a list of which attributes are boolean attributes and which ones are not, which is harder to maintain

**Comment by Kryyto** [comment]
Yeah, once you know it, it makes perfect sense, it just is a bit different from your regular usage of booleans.
