### ISSUE TITLE
[Serializer] Fails to denormalize into php 8 mixed property

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#39947]
**Symfony version(s) affected**: 5.2.1

**How to reproduce**  
```php
final class DTO
{
    public mixed $a;
}

$serializer->deserialize('{"a": 1}', DTO::class, 'json');
```

gives error `The type of the "a" attribute for class "DTO" must be one of "" ("int" given).`

**Additional context**  
Works well if phpdoc `mixed` type is used instead.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by YaFou** [comment]
I can't reproduce your issue on an empty project.

**Comment by xabbuh** [comment]
Let's close here for now then until we are able to reproduce.

**Comment by vudaltsov** [comment]
Here's the reproducer: https://github.com/vudaltsov/symfony-serializer-mixed-reproducer
@xabbuh , reopen, please :)

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
see #40160
