### ISSUE TITLE
[Mailer][Mime] In some areas header is not treated in a case-insensitive manner

### ISSUE THREAD

**Issue by piku235** [symfony/symfony#39953]
**Symfony version(s) affected**: 5.2

**Description**  
Recently, I've had a problem with a capitalized header when I tried to define a global sender in the framework config. The issue happens in the `Headers::addHeader()` when trying to resolve a header class from the header class map.

Also, `Headers::isUniqueHeader()` is affected and header rules in the `MessageListener::addHeaderRule()`.

The feature [pull request](https://github.com/symfony/symfony/pull/36736) for reference.

**How to reproduce**
The following config leads to an exception in `Headers::addHeader()`
```yaml
framework:
    mailer:
        headers:
            From: foo@localhost
```
```
TypeError(code: 0): Argument 2 passed to Symfony\\Component\\Mime\\Header\\Headers::addTextHeader() must be of the type string, array given
```

**Possible Solution**  
The fix is simple, we need to ensure that `strtolower()` is used when doing something specific on a user-supplied header name.

**Comment by plandolt** [comment]
Unfortunately I can't :(
