### ISSUE TITLE
Compile error after cache clearing 2+ times while script run

### ISSUE THREAD

**Issue by horror** [symfony/symfony#39957]
**Symfony version(s) affected**: 4.4.18 (all versions?)

**Description**  
This is related to [#25654](https://github.com/symfony/symfony/issues/25654).

**How to reproduce**  

*Step 0:*
U have 1 dir in cache dir `Container**hash1**` and **APP_ENV=prod** in **.env**
Run script like: 
```
sleep(200);
$container->get(\Swift_Mailer::class)->send('msg');
```
*Step 1:*
While script run, change some of .yml files from config folder, in order to new container folder be like `Container**hash1**` different with old `Contaner**hash2**` and run **php bin/console cache:clear --no-debug**. 
In your cache dir u have 2 dirs  `Container**hash1**`, `Contaner**hash2**`

*Step 2:*
Repeat step 1.
Now u have 2 dirs  `Container**hash2**`, `Contaner**hash3**`

*Step 3:*
Script completed after 200 seconds with 
`Fatal Compile Error: require(): Failed opening required '/.../cache/prod/Container**hash1**/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php')
`

**Possible Solution**  
We can do configurable TTL of old container cache folders, that allows avoid Fatal Compile Error.
For example. My script run not more 24 hour and finished. I can configure this param like 25 hours, and never getting Fatal Compile Error

https://www.diffchecker.com/YTxElgdn - code fix example

Do I need to make a pull request myself with realization of my possible solution?
I see too many issues releates this bug and no solution 5+ years, this is so bad

**Comment by horror** [comment]
up

**Comment by xabbuh** [comment]
I am not sure I understand the issue here. What is the use case for changing the configuration of an actively executed application?

**Comment by horror** [comment]
> I am not sure I understand the issue here. What is the use case for changing the configuration of an actively executed application?

clearing cache 2nd times, while application executed. For example symfony command, executed 1h+ and computing something(web scrapping, etc)

[#25654](https://github.com/symfony/symfony/issues/25654) this old description, how users see it without going into the details of why this happens

**Comment by xabbuh** [comment]
You shouldn't clear the cache for a running application. The behaviour that you observe is exactly the reason why that's not a good idea. I don't think there is anything we can do here. So I am going to close. Thank you for understanding.

**Comment by horror** [comment]
lol, serious? Do you live in the real world?
