### ISSUE TITLE
An exception has been thrown during the rendering of a template ("An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target computer expressly refused it. ").

### ISSUE THREAD

**Issue by alexandre-leng** [symfony/symfony#39955]
**Symfony version(s) affected**: 
Symfony CLI version v4.21.6 (c) 2017-2021 Symfony SAS

**Description**  
No connection could be made because the target computer expressly refused it.. 
HTTP 500 Internal Server Error 

i just devellop a website in symfony and i had this error
I think it's a server error 

i use symfony serve

**How to reproduce**  
i really don't know my git about this projet 
https://github.com/alexandre-leng/La-boutique-informatique---SYMFONY

[INTERNAL ERROR.zip](https://github.com/symfony/symfony/files/5860887/INTERNAL.ERROR.zip)

**Comment by alexandre-leng** [comment]
[stacktrace.zip](https://github.com/symfony/symfony/files/5860891/stacktrace.zip)
FULL STACKTRACE

**Comment by ghost** [comment]
Hi

In your code your .env is not correct you have conflict line 32.
Your database is Postgresql server ? because the driver choose is Postgresql

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
