### ISSUE TITLE
Cache PdoAdapter has hard coded charset for creating cache table (mysql)

### ISSUE THREAD

**Issue by pdragun** [symfony/symfony#39969]
**Symfony version(s) affected**: 5.2.0

**Description**  
Class [PDOAdapter](https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/Cache/Adapter/PdoAdapter.php) has hard coded charset for creating cache table (only for mysql). Standard charset is now utf8mb4, but cache table is still utf8.

**How to reproduce**  
Line 141
`$sql = "CREATE TABLE $this->table ($this->idCol VARBINARY(255) NOT NULL PRIMARY KEY, $this->dataCol MEDIUMBLOB NOT NULL, $this->lifetimeCol INTEGER UNSIGNED, $this->timeCol INTEGER UNSIGNED NOT NULL) COLLATE utf8_bin, ENGINE = InnoDB";`

**Possible Solution**  
Remove 'COLLATE utf8_bin' from code above and let user to set COLLATE during creating PDO connection (via dsn, or $options['db_connection_options'] in constructor of PDOAdapter class? Or change utf8 to utf8mb4?

It is in the code from [first commit](https://github.com/symfony/symfony/commit/82a0de212b5575e53dc7802153e2dfbf118974c0) until now.

**Comment by nicolas-grekas** [comment]
Does this create any actual problem?

**Comment by pdragun** [comment]
No.
But if I look to my DB and one table has different collation ... you know ... it's a little bit disturbing ...

**Comment by nicolas-grekas** [comment]
Can you please send a PR to branch 5.x?
That'd be fine to me as an improvement (that's not a bugfix, so not for lower branches).
Please also update src/Symfony/Component/Lock/Store/PdoStore.php which uses the same collaction.

**Comment by pdragun** [comment]
No problem, but please which solution do you prefer? Remove 'COLLATE utf8_bin' or change it to 'COLLATE utf8mb4_unicode_ci'? Thanks.

**Comment by nicolas-grekas** [comment]
`utf8mb4_bin`

this *must* collate a `bin` variant, to be case sensitive.
