### ISSUE TITLE
Authorization header cause 502 or 503 error 

### ISSUE THREAD

**Issue by MateuszGrzy** [symfony/symfony#39977]
**Symfony version(s) affected**: 5.2, 5.1

**Description**  
Whenever I make request with Authorization header with token i get 502 error in localhost [imgur](https://i.imgur.com/ldZQbRp.png) and 503 error in dev environment in remote server. 
Error can be skipped only when I remove cache folder in /var/cache/dev but afterwards it comebacks.

**How to reproduce**  
security.yaml
```
security:
    firewalls:
        api:
            pattern:  ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\TokenAuthenticator
```
App\Security\TokenAuthenticator.php
```
class TokenAuthenticator extends AbstractGuardAuthenticator
{
	/**
	 * @var UserTokenRepository
	 */
	private $apiTokenRepository;
	/**
	 * @var ApiResponse
	 */
	private $rest;
	/**
	 * @var Logger
	 */
	private $logger;
	
	/**
	 * TokenAuthenticator constructor.
	 *
	 * @param UserTokenRepository $apiTokenRepository
	 * @param ApiResponse         $rest
	 * @param Logger              $logger
	 */
	public function __construct(UserTokenRepository $apiTokenRepository, ApiResponse $rest, Logger $logger)
	{
		$this->apiTokenRepository = $apiTokenRepository;
		$this->rest = $rest;
		$this->logger = $logger;
	}
	
	public function supports( Request $request )
	{
		/**
		 * Check if in headers of request is value with key named Authorization and value started with Bearer
		 *
		 * Checking token will go in further steps
		 */
		
		return ($request->headers->has( 'Authorization' ) && strpos( $request->headers->get( 'Authorization' ), 'Bearer ' ) === 0)
		       || ($request->headers->has( 'authorization' ) && strpos( $request->headers->get( 'authorization' ), 'Bearer ' ) === 0);
	}
	
	public function getCredentials( Request $request )
	{
		$authorizationHeader = $request->headers->has( 'Authorization' ) ? $request->headers->get( 'Authorization' ) : $request->headers->get( 'authorization' );
		$this->logger->log('security','getCredentials',
			[
				'token'=>substr( $authorizationHeader, strlen( 'Bearer ' ) )
			]
		);
		// Skip Bearer part
		return substr( $authorizationHeader, strlen( 'Bearer ' ) );
	}
	
	public function getUser( $credentials, UserProviderInterface $userProvider )
	{
		/** @var UserToken $token */
		$token = $this->apiTokenRepository->findOneBy( [
			'token' => $credentials,
		] );
		
		if ( ! $token )
		{
			throw new CustomUserMessageAuthenticationException( 'Invalid TOKEN' );
		}
		
		if ( $token->isExpired() )
		{
			throw new CustomUserMessageAuthenticationException( 'TOKEN expired' );
		}
		
		$this->logger->log('security','getUser',
			[
				'user'=> $token->getUser()->getId()
			]
		);
		
		return $token->getUser();
	}
	
	public function checkCredentials( $credentials, UserInterface $user )
	{
		return TRUE;
	}
	
	public function onAuthenticationSuccess( Request $request, TokenInterface $token, string $providerKey )
	{
		$this->logger->log('security','onAuthenticationSuccess',
			[
				'user'=> $providerKey
			]
		);
	}
	
	public function onAuthenticationFailure( Request $request, AuthenticationException $exception )
	{
		$this->rest->setStatus( false );
		$this->rest->setMessage( $exception->getMessageKey() );
		$this->rest->setStatusCode(401);
		$this->rest->setErrorCode(401);
		$this->rest->setCustomData('onAuthenticationFailure',true);
		
		$this->logger->log('security','onAuthenticationFailure',
			[
				'exception'=> $exception->getMessage()
			]
		);
		
		return new JsonResponse( $this->rest->response(), $this->rest->getStatusCode() );
	}
	
	public function start( Request $request, AuthenticationException $authException = NULL )
	{
		$this->rest->setStatus( false );
		$this->rest->setMessage( 'No token was sent' );
		$this->rest->setStatusCode(401);
		$this->rest->setErrorCode(401);
		$this->rest->setCustomData('start',true);
		
		$this->logger->log('security','start',
			[
				'exception'=> $authException->getMessage()
			]
		);
		
		return new JsonResponse( $this->rest->response(), $this->rest->getStatusCode() );
	}
	
	public function supportsRememberMe()
	{
		return FALSE;
	}
}
```

**Possible Solution**  
I renamed Authorization prop in postman to Auth and it works

**Additional context**  
![symfony-authorization](https://user-images.githubusercontent.com/20776274/105857257-6b2c8d80-5fea-11eb-99b6-d58cdc5f4cd4.PNG)

**Comment by xelan** [comment]
The header name `Authorization` is reserved for [HTTP/Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication). By default, most web proxies/servers do not pass this header, so that must be enabled. Which tech stack do you use? Do you have any better error messages, as text and preferably in English?

**Comment by MateuszGrzy** [comment]
I use exact same code for token authorization in my other project and it works fine in same stack but the other project is running in symfony 5.0 and this error is for 5.1 and 5.2. 
Tech stack for both projects:
dev: 
- php 7.3
- MySQL 5.7
- postman for api testing
- windows 10
- wampp
prod: 
- php 7.3
- MySQL 5.7 
- Debian 7

libraries I use in both projects for api
- nelmio cors bundle
- FOSRestBundle

The error from screenshot translated to english:
Unable to fetch the response from backend: read tcp 127.0.0.1:62149->127.0.0.1:62700:  wsarecv an existing connection was forcibly closed by the remote host.

When I unchecked "Authorization" header from postman request everything works fine. I think something is wrong with cache because when cache is cleared and I send Authorization header everything is working, requests are going through TokenAuthenticator.php and I can dump it.

I got same error when I test it with LexikJWTAuthenticationBundle. Request with username/password json works fine but then second request with Authorization: Bearer TOKEN causes error

**Comment by xelan** [comment]
Which cache do you mean, the Symfony container/parameter/template/... cache in `var/cache`? Could you maybe provide a small reproducer for the issue?

**Comment by xabbuh** [comment]
@MateuszGrzy Can you please create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
