### ISSUE TITLE
Notice: serialize(): &quot;&quot; returned as member variable from __sleep() but does not exist

### ISSUE THREAD

**Issue by pifaace** [symfony/symfony#39989]
**Symfony version(s) affected**: 5.1.10

**Description**  
Hi,
As soon as I switch my application in production env, I get this error (I enabled DEBUG_MOD in production to get this)
![image](https://user-images.githubusercontent.com/17497139/105912147-515f6a80-602b-11eb-848d-57f9563678df.png)
on a specific Ajax POST route. As soon as I get this error, all my authenticated routes are a 500 
I have absolutely no idea what is going on. 

It seems that the error is coming up from there (line 178): 
![image](https://user-images.githubusercontent.com/17497139/105912502-d9de0b00-602b-11eb-83ce-00f77806a55b.png)

Here is the log when I switch DEBUG_MOD to 0 in production : 
![image](https://user-images.githubusercontent.com/17497139/105913298-e44cd480-602c-11eb-9129-50074277b12e.png)

Note that the error is not at the same line.

additionally, I don't have this error when a switch my localhost env to prod.
My server is a Nginx.

Thanks for your help

**Comment by lmasforne** [comment]
Hello pifaace,

In your log we can see you've got permission write problem in production you can clear cache in specific environnement like this 

`bin/console cache:clear --env=prod`

If you always got permission problem, put the right permission to you cache folder to let Symfony create it correctly.
I think it will fix you notice error

**Comment by pifaace** [comment]
Hi @lmasforne 
Thanks for your answer.
I followed this [article](https://symfony.com/doc/current/setup/file_permissions.html#using-acl-on-a-system-that-supports-setfacl-linux-bsd) and `cache:clear` 
Warning cache message disappeared but 500 sill there :/ 
![image](https://user-images.githubusercontent.com/17497139/105974658-6b7e6480-608e-11eb-8fde-76be728ea290.png)

**Comment by apfelbox** [comment]
The error message explains your problem: you are using a typed property, that is typed to `string` but try to assing `null` to it.

That can happen, for example, when you pass your `Workspace` into a form and the user submits an empty string (as it will be transformed to `null`).

**Comment by xabbuh** [comment]
Let's close here then as it doesn't look related to the Symfony code.

**Comment by cetver** [comment]
```
rm -rf var/cache/*
bin/console c:c
```
