### ISSUE TITLE
[Security] SwitchUserListener doesn't refresh user in original token

### ISSUE THREAD

**Issue by AndrolGenhald** [symfony/symfony#39991]
**Symfony version(s) affected**: 5.2.1

**Description**  
SwitchUserListener doesn't automatically refresh the user in the original token. This means anything that uses that user on switch user requests won't be able to assume that it has been refreshed, and it can cause problems with things like Doctrine relations which only work correctly after the user has been refreshed.

**How to reproduce**
- Clone https://github.com/AndrolGenhald/symfony_bug_39991.
- `composer install`
- `bin/console doctrine:migrations:migrate -q`
- Run preferred web server, such as `php -S localhost:8000 -t public`
- Login with "user_1", "password"
- Impersonate user_2_*
- Impersonate user_3_*
- Exception is thrown in CanImpersonateVoter

**Comment by lmasforne** [comment]
Hello AndrolGenhald ,

I think you forgot to put sqllite database in your sample project : 

`DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"`

I try to bootstrap you project with mysql but it doesn't work : 

```
An exception occurred while executing 'CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, manager_id INTEGER DEFAULT NULL, username VARCHAR(255) NOT NULL  
  , password VARCHAR(255) DEFAULT NULL)':                                                                                                                                   
                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the rig  
  ht syntax to use near 'AUTOINCREMENT NOT NULL, manager_id INTEGER DEFAULT NULL, username VARCHAR(255) N' at line 1  
```

**Comment by AndrolGenhald** [comment]
Did you perhaps forget to run `bin/console doctrine:migrations:migrate -q`? That should create the sqlite database and add the data. I just tried cloning it and the steps I listed seem to work fine for me. I suppose it may have been easier to just commit the database in this instance, though I'm more used to migrations.

**Comment by oadam** [comment]
This issue is similar to https://github.com/symfony/symfony/issues/39628
