### ISSUE TITLE
How to find out origin of request

### ISSUE THREAD

**Issue by marvoh** [symfony/symfony#39993]
We use GitHub issues only to discuss about Symfony bugs and new features. For
this kind of questions about using Symfony or third-party bundles, please use
any of the support alternatives shown in https://symfony.com/support

Thanks!
Is it possible to know whether a request is from the console or browser? 

I would like to perform certain functionality in my listener but only if request was initiated from browser activity and not console command. 

Thank you

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by marvoh** [comment]
Thank you, apologies for the oversight
