### ISSUE TITLE
YamlFileLoader SERVICE_KEYWORDS patch breaks easy-coding standard for Symfony 4 projects

### ISSUE THREAD

**Issue by sean-ww** [symfony/symfony#40015]
**Symfony version(s) affected**: 4

**Description**  
This patch: https://github.com/symfony/dependency-injection/commit/d749132342b401fb36621bfdee91363dffb87189
breaks all easy-coding-standard versions (8 and below) for Symfony 4
See https://github.com/symplify/symplify/issues/2872

**How to reproduce**  
Use ECS (8 or below) with the latest 4.4 dependency-injection patch

**Possible Solution**  
reverse the change, or adjust it so ECS still works

**Comment by nicolas-grekas** [comment]
ECS is/was apparently accessing a private property by reflection. That is not supported, sorry.
