### ISSUE TITLE
[FrameworkBundle][Routing] Boolean container parameters for routes trigger cache refresh on each request

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#40017]
**Symfony version(s) affected**: 4.4

**Description**  
Using boolean container parameters for routes triggers a cache refresh on each request.
The bug was introduced with https://github.com/symfony/symfony/pull/30379 . The problem is that bool values get [cast into a string](https://github.com/symfony/symfony/blob/8533ea223e99c8e0161fdf5b32e99e5d7567fb88/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L182) and are stored in the meta file as `"0"` or `"1"`. When the `ContainerParametersResourceChecker` checks whether the cache of fresh [it compares a string to a bool](https://github.com/symfony/symfony/blob/8533ea223e99c8e0161fdf5b32e99e5d7567fb88/src/Symfony/Component/DependencyInjection/Config/ContainerParametersResourceChecker.php#L45) (`"1" === true`) which is always false.

**How to reproduce**  
```yaml
# routes.yaml
foo:
    path: /foo
    condition: '%parameter.condition%'
```

A simple test case:
```php
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Config\ResourceCheckerConfigCache;
use Symfony\Component\Config\ResourceCheckerConfigCacheFactory;
use Symfony\Component\DependencyInjection\Config\ContainerParametersResourceChecker;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Routing\Loader\YamlFileLoader;

$cacheDir = __DIR__.'/cache';

$container = new Container();
$container->set('routing.loader', new YamlFileLoader(new FileLocator(__DIR__.'/config')));

$container->setParameter('parameter.condition', true);

$router = new Router($container, 'routes.yaml', [
    'debug' => true,
    'cache_dir' => $cacheDir,
]);

$resourceCheckers = [
    new ContainerParametersResourceChecker($container),
];

$router->setConfigCacheFactory(new ResourceCheckerConfigCacheFactory($resourceCheckers));

$router->getMatcher(); // trigger cache build

$cache = new ResourceCheckerConfigCache($cacheDir.\DIRECTORY_SEPARATOR.'UrlMatcher.php', $resourceCheckers);

var_dump($cache->isFresh()); // should be true, is false
```

**Comment by nicolas-grekas** [comment]
@HypeMC up for a PR?

**Comment by HypeMC** [comment]
@nicolas-grekas Sure, I'm just not sure how to go about this one though, I'll continue later today, any advice would be appreciated. :smile:

**Comment by stof** [comment]
The `condition` for a route expects an expression of ExpressionLanguage. So expecting a string is totally expected to me.
