### ISSUE TITLE
[DX] Remove @internal from ProfilerStorageInterface

### ISSUE THREAD

**Issue by ottaviano** [symfony/symfony#40011]
**Description**  
We use another storage (`Redis`) to store a profiler data and it improves Dev performance because it reduces write/read on file system. Some devs in our team work on MacOs and the project directory is mounted to the VM via NFS (with `/var/cache` dir). When FileStorage generates profiler data in `/var/cache/profiler` directory it takes some times and CPU to sync this directory with the host's one and the app becomes slower.

What do you think about removing `@internal` notation from `ProfilerStorageInterface` and keeping overridable this mechanism?

**Comment by fabpot** [comment]
It was marked as @internal as using another store is not supported anymore. But nothing prevents you from using it anyway if you want to.
