### ISSUE TITLE
Notice: Undefined index: index_type 

### ISSUE THREAD

**Issue by fluxion8** [symfony/symfony#40026]
**Symfony version(s) affected**: 5.2

**Description**  
Newly installed project but occurred following error on migration

**Error**  

-> php bin/console doctrine:migrations:migrate or php bin/console make:migration

[error] Error thrown while running command "doctrine:migrations:migrate". Message: "Notice: Undefined index: index_type"

In MySqlSchemaManager.php line 88:
                                       
  Notice: Undefined index: index_type

**Comment by xabbuh** [comment]
The `MySqlSchemaManager` class is not part of the Symfony code, but is provided by Doctrine DBAL. Looks like you need to report the issue there. But please take the time to provide them with more information that makes it actually possible to reproduce your issue.
