### ISSUE TITLE
[Notifier] Notification::getChannels() unused argument

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#40021]
Hi everyone 👋🏻 

I'm currently trying to normalize/denormalize a `Notification` in a Symfony bundle and the `Serializer` encounter an error when trying to access the channels, problem is, the only way to access the channels is to use `Notification::getChannels()` which requires a `Recipient` to be passed as an argument, thing is, this argument is not used 🤔 

```php
public function getChannels(RecipientInterface $recipient): array
{
    return $this->channels;
}
```

Is there any reason to keep the `$recipient` argument or can it be removed as it's not used? 

Thanks again for the feedback and have a great day 🙂

**Comment by norkunas** [comment]
It can be used to dynamically determine channels based on available recipient data.

**Comment by Guikingone** [comment]
Thanks @norkunas for the answer, it solved my use case 🙂
