### ISSUE TITLE
[Serializer] Need to clear cache when updating Annotation Groups on Entities

### ISSUE THREAD

**Issue by jc-oclock** [symfony/symfony#40034]
**Symfony version(s) affected**: 5.1/5.2

**Description**  
Serializer Groups Annotations not updating when updated, need to `cache:clear` on each `@Groups` modification. In `dev` environment at least (not tested in `prod`).

Changing a arbitrary `.yaml` config updates cache and the Group is updated too.

**How to reproduce**  
Create an app in ~~5.0~~ 5.1-5.2 with Doctrine entities, add Serializer group and call the Serializer on this group : 

```php
    /**
     * @ORM\Column(type="string", length=70)
     * @Assert\NotBlank
     * @Groups("movies_get")
     */
    private $title;
```

Call the URL, all the JSON fields are OK.
Remove or add a Group annotation, reload the URL, the JSON fields are not updated.
Clear the cache in any way, the JSON fields are OK.

**Possible Solution**  
Possible link with : https://github.com/symfony/symfony/issues/39988 ?
As the issue seems similar but at a _higher_ level :nerd_face: 

Or, when switching from 5.0 to 5.1, Doctrine packages has changes, need code updates, so perhaps the issue comes from here ?

**Additional context**  
If you have any questions, let me know.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by jc-oclock** [comment]
Thanks !

Here's the repo with the sample app : 
https://github.com/jc-oclock/sample-debug-symfony-serializer-groups

The README contains the informations to reproduce the issue (it's detailed to speed-up installation, although I assume you know the commands !).

PS to be clear if needed : Prior to 5.1, the Groups annotations cache was updated automatically.

**Comment by digilist** [comment]
I also noticed this behavior when I tried to create a new project with a reproducible example for issue #39988. But as I did not have any problem with annotations in my main project (which has only problems with attributes), I assumed I did something wrong and did not investigate this any further (both have on the same Symfony version 5.2.1)

**Comment by monteiro** [comment]
I was debugging this behavior.
Thanks @jc-oclock for the example. I was able to mimic the issue.

The issue is from this line: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Serializer/Mapping/Factory/CacheClassMetadataFactory.php#L54

This is the first time I'm seeing this code, maybe I need some help here.
According to that code:

The key is always the same, related to the entity:
In this specific project, is the name of the class "Contact" (saved [here](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Serializer/Mapping/Factory/CacheClassMetadataFactory.php#L62)). So even if we change the group annotations, it will hit the cache in development always. If we delete cache (where we save this metadata information) everything is reloaded, as normal.

**Shouldn't we have some sort of a hash (with the entity metadata content) here appended to the key?**

**Comment by jc-oclock** [comment]
Hi @monteiro,

Thanks for investigating.
I'm totally new to debugging Symfony code, but I'll try 🤓 

You wrote

> The key is always the same, related to the entity:
In this specific project, is the name of the class "Contact" (saved here). So even if we change the group annotations, it will hit the cache in development always. If we delete cache (where we save this metadata information) everything is reloaded, as normal.

I investigate over here on your suggestion, and indeed it is the condition `if ($item->isHit())` [at line 57](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Serializer/Mapping/Factory/CacheClassMetadataFactory.php#L57) that returns the cached value.

Should the problem probably comes from the way the cache is updated rathen than checked ? (isHit)

I'll try to find in which part of the code the cache is updated (I mean where it looks for annotations changes) but if you have a clue 🕵🏻

**Comment by monteiro** [comment]
I think the solution should be to make some sort of metadata hash and cache it, so if there are any changes the cache is not hit. But maybe @xabbuh can help us here.

In production, the code works. But in development, cache is not refreshed because the key is always the same.

**Comment by jc-oclock** [comment]
I try to understand the usage of the key, and if we check the commit concerning the file you pointed, there is no change about a "unique" key ? If I follow you : 

https://github.com/symfony/symfony/commit/3a4675359d7b0ec9636618519cfe26e07b22c64b#diff-de8953f7dd0d7b154d4df70182a797f5055eef3dfe7d6f77eea3c1773c14aec2R47

Just adding `rawurlencode()` could not have broken the cache ? 🤔 
I mean this part of the code does not seem to be involved (I removed the `rawurlencode()` function and the cache still not updates).

Correct me if I'm wrong, Symfony code is a bit complex for me 🤓

**Comment by monteiro** [comment]
@jc-oclock just created a PR: https://github.com/symfony/symfony/pull/40856 This is a proposal with a fix. Not sure about the solution.

**Comment by nicolas-grekas** [comment]
Maybe we should simply not enable the cache in debug mode? /cc @dunglas

**Comment by dunglas** [comment]
@nicolas-grekas the dev environnement is already very slow on large projects. I'm not sure if it's a good idea (but I'm not strongly opposed to it either).

**Comment by stof** [comment]
if we don't have resource-tracking to automatically invalidate the cache in debug mode, I would say that we should not enable the cache automatically (but we may still allow to opt-in for the cache in those environment if the devs decide this trade-off is worth the DX loss of having to clear the cache manually)

**Comment by jc-oclock** [comment]
Thanks for your proposal @monteiro.

I replied to @nicolas-grekas on the other issue.
