### ISSUE TITLE
[Routing] Failed loading route resource while upgrade from PHP 7.4 to PHP 8.0

### ISSUE THREAD

**Issue by talalong** [symfony/symfony#40032]
**Symfony version(s) affected**: 5.0.11

**Description**  
First of all, I don't know if this is the right place to post this issue, but I have found in this group exact the same issue which was posted 4 years ago. https://github.com/symfony/symfony/issues/25225.
Running on PHP 7.4 was totally fine.
After upgrading to PHP 8 and run `composer update` I got this error: (The `1\` is quiet interesting)

> In FileLoader.php line 173:
>                                                                                                                         
>   Class "1\DummyController" does not exist in /app/config/routes/../../src/Controller/ (which is being imported from "  
>   /app/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.                               
>                                                                                                                         
> 
> In AnnotationDirectoryLoader.php line 62:
>                                             
>   Class "1\DummyController" does not exist  

Below are some config files I haven't changed since PHP 7.4. 
**How to reproduce** 

run `bin/console debug:router` or `composer update` will lead me to this error.

**config/routes/annotation.yaml**

```
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
```

**config/routes.yaml**

```
controllers:
  resource: '../src/Controller/'
  type:     annotation
  prefix:   /api/
```

**src/Controller/DummyController.php**

```
<?php

namespace App\Controller;

class DummyController extends AbstractController
{

}
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by talalong** [comment]
@xabbuh After updating to Symfony 5.2 and removing some .lock files. I got the project with PHP 8 up and running. It might not be Symfony's fault, but my misconfigurations somewhere.
Thank you :)

**Comment by weppyk** [comment]
Could you please write, how did you solve it? I have similar problem. Thanks

**Comment by talalong** [comment]
@weppyk It depends on how did you upgrade your application.
I am using Docker in my case. And the way Docker built new PHP8.0 image is that it used the existing composer.lock (contains php7.4), which was not my goal. So I removed composer.lock and symfony.lock files. After the PHP8.0 was successfully installed, I ran composer update/install in order to generate new *.locks files. Make sure you have all dependecies in composer.json, that are compatible with PHP8.0.

**Comment by drupol** [comment]
I'm also having the issue, running PHP 7.4.20.

If you want a small example application, you can find it here: https://github.com/loophp/go-unfloc-yourself-bundle

I'm unable to run the Behat tests locally, it doesn't work anymore and yes they were working 1 or 2 weeks ago.

```
$ ./vendor/bin/behat                                                                                                                           
Feature: It adds the Permissions-Policy header on responses

  Scenario: Test                                                                 # features/it_add_the_proper_header.feature:3
[critical] Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Cannot load resource "../Controller/". Make sure to use PHP 8+ or that annotations are installed and enabled." at /home/pol/dev/git/go-unfloc-yourself/vendor/symfony/config/Loader/Loader.php line 79

    Given I am on "/"                                                            # Behat\MinkExtension\Context\MinkContext::visit()
    Then the header "Permissions-Policy" should be equal to "interest-cohort=()" # Behatch\Context\RestContext::theHeaderShouldBeEqualTo()
[critical] Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Cannot load resource "../Controller/". Make sure to use PHP 8+ or that annotations are installed and enabled." at /home/pol/dev/git/go-unfloc-yourself/vendor/symfony/config/Loader/Loader.php line 79

    When I send a POST request to "/" with body:                                 # Behatch\Context\RestContext::iSendARequestToWithBody()
      """
      {"Permissions-Policy":"foobar"}
      """
    Then the header "Permissions-Policy" should be equal to "foobar"             # Behatch\Context\RestContext::theHeaderShouldBeEqualTo()
      The header 'Permissions-Policy' should be equal to 'foobar', but it is: 'interest-cohort=()' (Behat\Mink\Exception\ExpectationException)
    │
    │  The debug profile URL 
    │
    └─ @AfterStep # Behatch\Context\DebugContext::failScreenshots()

--- Failed scenarios:

    features/it_add_the_proper_header.feature:3

1 scenario (1 failed)
4 steps (3 passed, 1 failed)
0m0.24s (24.47Mb)
$                                                                                                                                      
```

I'm looking for the issue because we have several packages depending on the same kind of tests, which are all failing as well.

**Comment by nicolas-grekas** [comment]
@drupol your issue is unrelated. Here is the patch you need to apply to your bundle to make it pass:
```diff
--- a/src/Tests/Fixtures/App/Kernel.php
+++ b/src/Tests/Fixtures/App/Kernel.php
@@ -39,6 +39,7 @@ final class Kernel extends BaseKernel
                 'test' => true,
                 'router' => ['utf8' => true],
                 'secrets' => false,
+                'annotations' => true,
             ]
         );
     }
```

The reason is that because annotations are a dev-dep, you now need to enable them explicitly.

**Comment by drupol** [comment]
Oh... ok.

I now feel stupid.

Thanks again Nicolas!

**Comment by bakotiinii** [comment]
Have the same issue with symfony 5.0 also.

Is there any ideas, why php8.0 lead to error, while the same config on php7.4 works fine?

**Comment by nacholibre** [comment]
You need to install `composer require sensio/framework-extra-bundle` to fix this issue.

**Comment by derrabus** [comment]
> You need to install `composer require sensio/framework-extra-bundle` to fix this issue.

No, please don't do that.

**Comment by olberger** [comment]
> No, please don't do that.

Uh, care to be more explicit on why ?

**Comment by xabbuh** [comment]
That bundle is deprecated.

**Comment by stof** [comment]
If you have an issue today, please open a new ticket instead of commenting on a 2 years old bug. Your issue is likely to be a different issue than that one

**Comment by derrabus** [comment]
Let's lock the issue.

To everyone getting here by googling error messages: Almost everyone who commented "me too" here has a different problem that needs a different solution. In this thread, you probably won't find a solution that fits your problem.

If you need help, please open a discussion over at https://github.com/symfony/symfony/discussions or see https://symfony.com/support for further options.
