### ISSUE TITLE
doctrine-bridge - different instances of UnitOfWork in repositories

### ISSUE THREAD

**Issue by pelikan7** [symfony/symfony#40030]
**Symfony version(s) affected**: symfony/doctrine-bridge 4.4.19

**Description**  
After switching from doctrine-bridge 4.4.18 to 4.4.19 I had multiple errors during doctrine:fixtures:load, mostly when I tried to add an existing item (fetched from database) as a relation to a newly persisted record (in this case, I tried to create a new DocumentTemplate and add already existing DocumentType):

` A new entity was found through the relationship 'App\Entity\DocumentTemplate#documentType' that wa  
  s not configured to cascade persist operations for entity: App\Entity\DocumentType@0000000074bd901  
  d00000000254ec2c5. To solve this issue: Either explicitly call EntityManager#persist() on this unk  
  nown entity or configure cascade persist this association in the mapping for example @ManyToOne(..  
  ,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entit  
  y\DocumentType#__toString()' to get a clue.           `

I found out that DocumentType I just fetched from repository is not saved into UoW's identityMap. After a second check, I realized that DocumentTypeRepository is not using the same Unit of Work as other repositories and ObjectManager.

After a lot of debugging I found out that the problem occurs when I inject a repository straight into EventSubscriber/EventListener. Injected repositories has a different, clean UoW, never used anywhere else. Those repositories that are never injected and fetched using Manager->getRepository($className) works correctly.

**How to reproduce**  
1. Create two entities with repositories
2. Create an EventSubscriber and inject only one repository directly
3. Write a code that fetches items from both repositories and some other entities (with a generic repository)
4. Compare identityMap of both repositories ($repository->_em->unitOfWork

**Additional context**  
Here is a screenshot of Xdebug showing two repositories side by side - DocumentTypeRepository is injected in a Subscriber while CompanyRepository isn't

![obraz](https://user-images.githubusercontent.com/24898564/106189383-87762900-61a8-11eb-8216-107f182262fd.png)

**Comment by jderusse** [comment]
Hello, Thank you for this well explained issue. Could you please provide a reproducer?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
