### ISSUE TITLE
wrong autogenerated script for user-table in sql server

### ISSUE THREAD

**Issue by thepercival** [symfony/symfony#40033]
**Symfony version(s) affected**: 4.21.5
sqlserver version : Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64) \n	Jun 10 2020 18:25:25 \n	Copyright (C) 2019 Microsoft Corporation\n	Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)\n

**Description**  
When creating the migration for the user-entity under sqlserver, square brackets are used for extended properties. This returns an error

**How to reproduce**  
php bin/console make:user
php bin/console make:migration
php bin/console doctrine:migrations:migrate
EXEC sp_addextendedproperty N'MS_Description', N'(DC2Type:json)', N'SCHEMA', 'dbo', N'TABLE', '[User]', N'COLUMN', roles
When migrating:
Error: Object is invalid. Extended properties are not permitted on 'dbo.[User].roles', or the object does not exist.

**Possible Solution**  
Remove the square brackets
EXEC sp_addextendedproperty N'MS_Description', N'(DC2Type:json)', N'SCHEMA', 'dbo', N'TABLE', 'User', N'COLUMN', roles

**Comment by stof** [comment]
Migrations are not implemented in Symfony but in Doctrine. The SQL queries for the schema creation are managed by doctrine/dbal.

**Comment by thepercival** [comment]
Sorry for posting in the wrong repository, I will post it at doctrine dbal. Thanks for the answer
