### ISSUE TITLE
Customize Error Pages not apply

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#40058]
**Symfony version(s) affected**: 5.2.2

**Description**  
I have  override the default error templates with new file templates on _templates/bundles/TwigBundle/Exception_ 

![image](https://user-images.githubusercontent.com/10476280/106479083-31f09380-64aa-11eb-9937-c84c94ad5abd.png)

it's work fine when try a bad route or generate **NotFoundHttpException** on controller

![image](https://user-images.githubusercontent.com/10476280/106483804-38cdd500-64af-11eb-904f-0259588a492b.png)

but if a create a listener like that

```php
App\Listener\FireListener:
        tags:
            - { name: kernel.event_listener, priority: 0 }
```
and generate **NotFoundHttpException**

```php

public function __invoke(RequestEvent $event)
{
        $host = $event->getRequest()->getHost();
        $uri = $event->getRequest()->getRequestUri();

        if($host === 'mycustomdomain.com'){
            $match = preg_match("/demo-test/", $uri);
            if($match === 1){
                throw new NotFoundHttpException('page not found');
          }
 }

```
on **PROD** mode **The default error template** is apply, not the custom.

![image](https://user-images.githubusercontent.com/10476280/106478327-6021a380-64a9-11eb-9541-b50a955c0de5.png)

**Possible Solution**  
In first i thinks is the priority, i try different number 300, 0 , -300 no effect.

any idea to resolve that ?

**Comment by pifaace** [comment]
Hi,
What do you mean by customize error page ? Because on your dev screen this is definitely the default error page just with custom message.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by thewalkingcoder** [comment]
@xabbuh you can try with
https://github.com/thewalkingcoder/firewallpoc

turn on 

`
APP_ENV=prod
`

On the home page

![image](https://user-images.githubusercontent.com/10476280/106734487-5d42c200-6613-11eb-8f31-2723f84a8757.png)

`NotFoundHttpException` throw on route `/contact` or try `/badrouteblablabla`

![image](https://user-images.githubusercontent.com/10476280/106734530-69c71a80-6613-11eb-9336-8a7301509a53.png)

`NotFoundHttpException` throw with Listener

![image](https://user-images.githubusercontent.com/10476280/106735029-012c6d80-6614-11eb-8c88-3cbd0a6072b8.png)

**Comment by thewalkingcoder** [comment]
I temporarily change approach 

Instead of generate `NotFoundHttpException`  i generate directly 404 response

```php

//condition

$template = 'bundles/TwigBundle/Exception/error404.html.twig';
$pageNotFound = $this->twig->render($template);
return $requestEvent->setResponse(new Response($pageNotFound, 404));

```

**Comment by xabbuh** [comment]
@thewalkingcoder Symfony issue a subrequest to render the error template. If you restrict your listener to only react on the master request, it will not intercept these subrequests and the template will be rendered as expected. So I am going to close here as this does not look like a bug.

**Comment by thewalkingcoder** [comment]
ok thanks for explanation
