### ISSUE TITLE
The mailchimp-mailer should handle all the possible configuration of the API

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#40056]
**Description**  
The mailchimp mailer is based on the mandrill API and create a payload 
https://github.com/symfony/mailchimp-mailer/blob/5.x/Transport/MandrillApiTransport.php#L77-L83

But this payload could have other values
https://mandrillapp.com/api/docs/messages.html

For instance I'm using a lot `track_opens` and `track_clicks`.
```
$message = [
    'to'           => $recipients,
    'html'         => $body,
    'subject'      => $subject,
    'from_email'   => $fromEmail,
    'attachments'  => $attachments,
    'track_opens'  => true,
    'track_clicks' => true,
];
```

It would be great to add these two values (and maybe all the possible options of the API).

How should it be implemented ?
Does it require something like `Email::getOptions()` ?

**Comment by fabpot** [comment]
We are only implementing features that can be made generic enough to apply to almost all providers. See past PRs/issues on the same topic.

**Comment by VincentLanglet** [comment]
> See past PRs/issues on the same topic.

I looked for and didn't find something related. Do you have a topic in mind ?

> We are only implementing features that can be made generic enough to apply to almost all providers. 

I totally understand this point, that's why I proposed a `getOptions` method which could take every transport-specific features. But another solution I had in mind would be to add a Transport configuration.

mailchimp_transport.yaml
```
mailchimp_transport:
    track_opens: true
    track_clicks: true
```

and using the options when creating the message
https://github.com/symfony/mailchimp-mailer/blob/5.x/Transport/MandrillApiTransport.php#L77-L83

This way a feature specific to one transport is developed in this transport only.
Would it be better @fabpot ?

**Comment by fabpot** [comment]
Again, I'm not interested in a generic way to pass options as I don't want to replace the official SDKs. If you need specific features, the official SDK is the way to go.
