### ISSUE TITLE
security:check getting a 403 from https://security.symfony.com/check_lock

### ISSUE THREAD

**Issue by leberknecht** [symfony/symfony#40054]
**Symfony version(s) affected**: running this on 4.4

**Description**  
The command gives 
```
The web service failed for an unknown reason (HTTP 403).
```
The payload of the response is `error code: 1020`, in `\SensioLabs\Security\Crawler::doCheck`
![image](https://user-images.githubusercontent.com/1165177/106466689-f353dc80-649b-11eb-9524-6ddd9ff5b609.png)

**How to reproduce**  
Nothing special here:
```
composer create-project symfony/website-skeleton test
cd test
composer require sensiolabs/security-checker
./bin/console security:check -vvv
```

**Possible Solution**  
I guess the backend is down.. even though `403` seems to be a somehow strange response for that

**Additional context**  
Happens on gitlab CI as well as on local

**Comment by fabpot** [comment]
See https://twitter.com/fabpot/status/1354038012892618755
And https://github.com/fabpot/local-php-security-checker for an Open-Source version or the API.
