### ISSUE TITLE
Syntax Error on where condition with postgres

### ISSUE THREAD

**Issue by nathan-cuvellier** [symfony/symfony#40061]
**Symfony version(s) affected**: 5.2.1

**Description**  

I want get only users with a specific role, so i excute this request, but symfony return a syntax error
![image](https://user-images.githubusercontent.com/25644340/106498714-f234a680-64bf-11eb-9436-65c406f5e4dc.png)

It's ok when i try directly in pgAdmin
![image](https://user-images.githubusercontent.com/25644340/106498668-e5b04e00-64bf-11eb-94aa-ba964824e4df.png)

**How to reproduce**  

**In UserRepository :**
```
public function getAllCustomer()
{
    $qb = $this->createQueryBuilder("u");

    $qb->where("u.roles::jsonb ? 'ROLE_CUSTOMER'");

    return $qb->getQuery()->getResult();
}
```

**Additional context**  

Perhaps there is a better solution?

**Comment by stof** [comment]
This is the wrong issue tracker for that, for 2 reasons:

- the API you are using is not provided by Symfony but by Doctrine, which is a separate project maintained by a different team (which does not read this issue tracker)
- the behavior you see is not even coming from Doctrine but from PHP itself: PDO uses `?` as its markup for parameters in prepared queries, which requires escaping it if you want an actual `?` in the SQL

**Comment by nathan-cuvellier** [comment]
Indeed, I'm sorry!
