### ISSUE TITLE
symfony/workflow add function to find transitions to get to a particular state

### ISSUE THREAD

**Issue by Bast1onCZ** [symfony/symfony#40064]
**Description**  
Hello,
could you please add a feature to `symfony/workflow` into the `WorkflowInterface` (and implementations) to allow user to find suitable transitions to get to a particular state?

**Example**  
```
/** @var StateMachine $cartWorkflow */
$cartWorkflow = $request->getContainer()->get('commerce_bundle.state_machine.cart');
$transition = $cartWorkflow->findSuitableTransition($cart, $request['state']); // Find any transition to be able to get to desired state

$cartWorkflow->apply($cart, $transition);
```

**Comment by jkufner** [comment]
Do you consider the side effects of the transitions? What if you find a path that have some destructive transitions, but a slightly longer path is the desired one, e.g., providing some prerequisities instead of removing what needs them?

**Comment by Aerendir** [comment]
I don’t think this is something useful: you should know on yourself where you can go next. If you don’t, then you have a problem. A very big problem.

why do you need this feature?

**Comment by jkufner** [comment]
A reasonable use case for this feature is to inspect reachability of a desired state by a given user. Such an inspection could be included in tests to verify that a user is allowed to create and submit a multi-step order. However, I aggree that it is unlikely to be of use in the application itself (I'm not the author of this issue).

**Comment by noniagriconomie** [comment]
Is this kind of related to this? https://github.com/symfony/symfony/issues/36759

i think the code behavior could go crazy if it has to find all possibilities if many

can you detail the use case of your usage of this? 
i agree that a workflow and its states and transition are known in advance a thus do not understand why a feature like that is useful

**Comment by Bast1onCZ** [comment]
> Is this kind of related to this? #36759

No, the only think I want is to find a transition to get from one state to another, without any states between.

> can you detail the use case of your usage of this?
> i agree that a workflow and its states and transition are known in advance a thus do not understand why a feature like that is useful

Imagine a situation, that you have an `Order` in your system. The entry state is `PLANNED` and an administrator user can change the state to either `PACKED` (transition `pack`) or `REFUNDED` (transition `refund`). Moreover, any `PACKED` order can be also switched to `REFUNDED` (transition `break`). The administrator wants to change a state, he can decide from currently available ones. He really does not care how the transition between particular states is named (and the system does not translate transition names to his language, because transitions aren't obviously a part of the `Order`).

**Comment by Aerendir** [comment]
@Bast1onCZ , so, basically you want to be able pre-populate a select field with available next states: am I understanding well?

**Comment by noniagriconomie** [comment]
I think the next transition/state, and next of the next
maybe you should just [dump the workflow](https://symfony.com/doc/current/workflow/dumping-workflows.html) and diplay it on your GUI so that the human can view and decide 

there is also already the 

```php
// See all the available transitions for the post in the current state
$transitions = $workflow->getEnabledTransitions($post);
// See a specific available transition for the post in the current state
$transition = $workflow->getEnabledTransition($post, 'publish');
```

also, have a look at this https://symfony-workflow-demo.herokuapp.com/article/show/3523, it can gives ideas

**Comment by Bast1onCZ** [comment]
> @Bast1onCZ , so, basically you want to be able pre-populate a select field with available next states: am I understanding well?

No, this problem I addressed in https://github.com/symfony/symfony/issues/40119.

In this issue, I want to find a transition that gets me to desired available state on a state machine (which is actually a primitive algorithm that I would compare to finding a substring inside a string, but this algorithm is missed in the symfony/workflow package or I cannot find it).

**Comment by jkufner** [comment]
@Bast1onCZ The algorithm is BFS (breadth first search) and you can find an implementation in my Smalldb library (https://github.com/smalldb/libSmalldb/blob/v2.0.2/lib/Graph/GraphSearch.php#L77), for example. It is not very complicated, but it is a bit tricky to get the API right. It should be relatively easy to convert your workflow to the `Smalldb\Graph\Graph` and then run the algorithm via the `Smalldb\Graph\GraphSearch::BFS()`. (There is also a Graphviz-like visualization tool available. Moreover, I can move the library into standalone repository and package, if desired.)

**Comment by Bast1onCZ** [comment]
> @Bast1onCZ The algorithm is BFS (breadth first search) and you can find an implementation in my Smalldb library (https://github.com/smalldb/libSmalldb/blob/v2.0.2/lib/Graph/GraphSearch.php#L77), for example. It is not very complicated, but it is a bit tricky to get the API right. It should be relatively easy to convert your workflow to the `Smalldb\Graph\Graph` and then run the algorithm via the `Smalldb\Graph\GraphSearch::BFS()`. (There is also a Graphviz-like visualization tool available. Moreover, I can move the library into standalone repository and package, if desired.)

I know how to implement it, I also have it in my private package. But the best place for this is in my opinion symfony's original package.

**Comment by Aerendir** [comment]
Again, sorry, but I don't understand why is this useful: you should know, given the current place, to what other places you can go. Or you should be able to "calculate" the path to the desired place.

I'm missing the point.

From what I understand, you need to discover something that you should already know.

**Comment by eFrane** [comment]
Knowing the possible transitions assumes that the workflow is known to the presenter. I can see how this could be useful in a setup where selections for next states shall be made from available transitions *and* the workflows come from an external package. In any case, to me this broadens the question to whether basic graph traversal algorithms should be available for workflow definitions.

**Comment by Aerendir** [comment]
> from an external package

Study it and you will know the transitions it makes available.

What changes if a feature like this is implemented? You have a list of available transitions, but you have to study them anyway: maybe there are subscribers, other things happen on a transition... You cannot blindly apply transitions hoping all will go well.

**Comment by Nyholm** [comment]
This is an interesting discussion. 

The workflow component main focus is to provide help/a tool for structure your code's logic. The feature you are asking for belongs to a Petri net. (A workflow is a subset of a petri net). I do understand that there is a specific scenario where you want to do searches in the graph. I do also see the complexity it will bring in, ie to support Guards. 

I dont think this is a good idea to bring into the component, but I would be interested to read a blog post about your current private implementation. Or maybe event to see a library.
