### ISSUE TITLE
Translation priority according to docs not working

### ISSUE THREAD

**Issue by codegain** [symfony/symfony#40063]
**Symfony version(s) affected**: 4.4.19

**Description**  

In the 4.4 docs there is this passage about translations priorities: https://symfony.com/doc/4.4/translation.html#translation-resource-file-names-and-locations

```
Symfony looks for message files (i.e. translations) in the following default locations:

the translations/ directory (at the root of the project);
the src/Resources/<bundle name>/translations/ directory;
the Resources/translations/ directory inside of any bundle.

The locations are listed here with the highest priority first. That is, you can override the translation messages of a bundle in any of the top two directories.

The override mechanism works at a key level: only the overridden keys need to be listed in a higher priority message file. When a key is not found in a message file, the translator will automatically fall back to the lower priority message files.
```

However in my project this priority doesn't seem to work: I would like to overwrite the translation for the `NotCompromisedPassword` message in the `validators` domain:

**vendor/symfony/validator/Resources/validators.de.xlf**
```
<trans-unit id="93">
                <source>This password has been leaked in a data breach, it must not be used. Please use another password.</source>
                <target>Dieses Passwort ist Teil eines Datenlecks, es darf nicht verwendet werden.</target>
</trans-unit>
```

**translations/validators.de.xliff**
```
<trans-unit id="This password has been leaked in a data breach, it must not be used. Please use another password." xml:space="preserve">
        <source>This password has been leaked in a data breach, it must not be used. Please use another password.</source>
        <target>foobar</target>
</trans-unit>
```

If I then clear the cache and dump `$this->translator->trans('This password has been leaked in a data breach, it must not be used. Please use another password.', [], 'validators')` it displays "Dieses Passwort ist Teil eines Datenlecks, es darf nicht verwendet werden." and not my overwritten string "foobar".

**How to reproduce**  

1. Create a `validators.de.xliff` translation file in your "translations" directory and try to override any translation found in `vendor/symfony/validator/Resources/validators.de.xlf`
2. The translation will not be overwritten

**Additional context**  

I dumped some infos in the translator and found out that my translation files are loaded first (translations/..., translations/...) and the files in vendor appeared later in the `$this->resources` array which appears to me that my translations are being overwritten by the ones defined in the vendor directory. This should not occour according to the documentation.

**Comment by xabbuh** [comment]
Same as #40014?

**Comment by codegain** [comment]
@xabbuh Yes, sorry about the duplicate. The mentioned workaround by adding `"symfony/finder": "=4.4.19"` to the `conflicts` section did fix this for me.

**Comment by xabbuh** [comment]
Thanks for the feedback. Closing here then in favour of the other issue.
