### ISSUE TITLE
Cannot autowire service argument of method is type-hinted

### ISSUE THREAD

**Issue by brettins** [symfony/symfony#40073]
**Symfony version(s) affected**: 

```
        "symfony/framework-bundle": "5.1.*",
```
**Description**  

Getting an error:
`Cannot autowire service argument of method is type-hinted "bool", you should configure its value explicitly.`

I have in my services.yaml:

```
    App\Service\MyService:
        arguments: 
            $isDebug: true
```

That's reduced from the series of .env variables I was trying to pass, and since this basic setup still doesn't work I don't know how to proceed. 

This seems to be the way to add parameters to a specific service in the docs and in the Symfony casts. I'm not sure what other debug information I need to be providing for context here, just that I am following very simple instructions from the Symfony docs & casts and it it's giving me a fatal error.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
