### ISSUE TITLE
Misconfigured environment is hard to debug

### ISSUE THREAD

**Issue by BackEndTea** [symfony/symfony#40071]
**Symfony version(s) affected**: 5.2

**Description**  
When the environment (either when passing it with `--env` in CLI, or the APP_ENV env variable), is an empty string, a hard to debug error comes up:

```
In BaseNode.php line 340:
                                                                                                                  
  Configuration path "security.access_control" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.             
````

**How to reproduce**  

On a fresh symfony project run:
```
bin/console --env=''
```

When a non existing environment is provided, everything works 'normally'. The error only occurs if the environment is empty. e.g.

```
bin/console --env='foo'
```

**Possible Solution**  

Detect an empty environment as a bug, and report it to the user.

**Comment by Keenegan** [comment]
I had this error and can confirm this could be a nice improvement. I would have not found the answer without this issue.

I had no error on my local environment, but my github action CI had no specified environment, so the fix was just to add this in my worflow yml file:

```yaml
env:
    APP_ENV: dev
```

**Comment by nicolas-grekas** [comment]
PR welcome then.

**Comment by BackEndTea** [comment]
I think this got fixed by https://github.com/symfony/symfony/pull/41402

**Comment by BackEndTea** [comment]
Just verified that PR fixed my issue. Thanks @nicolas-grekas

**Comment by escopecz** [comment]
This error re-appeared in Symfony 7.4.0. New issue: https://github.com/symfony/symfony/issues/62547
