### ISSUE TITLE
[Notifier] Firebase data field

### ISSUE THREAD

**Issue by Raresmldvn** [symfony/symfony#40078]
Hello
I've noticed that symfony/firebase-notifier has no support for the `data` field to be sent to the Firebase API server. It only sends the `to` and `notification` fields ( https://firebase.google.com/docs/cloud-messaging/http-server-ref ).
I need that field for a project I am currently working on.
Is there a particular reason for this not being implemented? 
I would like to open a PR for setting up this field in the payload as well. 

What needs to be done is add the `data` field in the `FirebaseOptions` class as well.

**Comment by OskarStark** [comment]
No reason I guess, FirebaseOptions seems to be the right place 👍🏻
