### ISSUE TITLE
NotFoundHttpException in subrequest results in error 500

### ISSUE THREAD

**Issue by grossmannmartin** [symfony/symfony#40079]
**Symfony version(s) affected**: 4.4.19, 5.2.3

**Description**  

**How to reproduce**  
Create controller (SubrequestController) and throw NotFoundHttpException in index action.

Render controller in twig template of another action
```twig
    {{ render(controller('\\App\\Controller\\SubrequestController:index')) }}
 ```

See error 500 on the main controller instead of predictable 404.

**Possible Solution**  
This behavior could be documented, maybe changed, or some workaround will be nice.

**Comment by derrabus** [comment]
This is expected behavior, as far as I can tell. If you feel like this should be documented differently, please open an issue at https://github.com/symfony/symfony-docs/

**Comment by grossmannmartin** [comment]
Hi, @derrabus thanks for the response. 
Can you please elaborate, why is this expected behavior? I don't understand the use-case, where this is wanted.

Do you know some way, how to change this behavior?

**Comment by derrabus** [comment]
You tried to render the result of a subrequest into a template. The subrequest failed, so the template cannot be rendered. The Twig extension that you are using here can't possibly know how to recover from that failure.
