### ISSUE TITLE
[Framework] Inherited Application methods have incorrect signatures

### ISSUE THREAD

**Issue by wimski** [symfony/symfony#40083]
**Symfony version(s) affected**: 5.2.1

**Description**  
`Symfony\Bundle\FrameworkBundle\Console\Application` has incorrect method signatures for some of the inherited methods from `Symfony\Component\Console\Application`.

**How to reproduce**  
```php
// original
public function get(string $name)

// inherited
public function get($name)
```
[original](https://github.com/symfony/console/blob/56d4c04ca6069c93857c7335a626dbe747fa82d4/Application.php#L518)
[inherited](https://github.com/symfony/framework-bundle/blob/e741e262c83725de8700887eef28bbb2c803c5d5/Console/Application.php#L122)

```php
// original
public function find(string $name)

// inherited
public function find($name)
```
[original](https://github.com/symfony/console/blob/56d4c04ca6069c93857c7335a626dbe747fa82d4/Application.php#L629)
[inherited](https://github.com/symfony/framework-bundle/blob/e741e262c83725de8700887eef28bbb2c803c5d5/Console/Application.php#L112)

```php
// original
public function all(string $namespace = null)

// inherited
public function all($namespace = null)
```
[original](https://github.com/symfony/console/blob/56d4c04ca6069c93857c7335a626dbe747fa82d4/Application.php#L739)
[inherited](https://github.com/symfony/framework-bundle/blob/e741e262c83725de8700887eef28bbb2c803c5d5/Console/Application.php#L138)

**Possible Solution**  
Update the methods in the framework console application class to match the original.

**Comment by xabbuh** [comment]
There is no issue here. PHP allows to drop type information when extending a class. So I am going to close here. Thank you for understanding.

**Comment by wimski** [comment]
Is that with a specific version PHP, because the following simple test shows a clear issue. At least for 7.4.

http://sandbox.onlinephpfunctions.com/code/0dcd67323d7d725e9876b91e8d0e7377b4241c02

```php
<?php

class Foo
{
    public function echo(string $var): void
    {
        echo $var;
    }
}

class Bar extends Foo
{
    public function echo($var)
    {
        echo $var . ' from Bar';
    }
}

$bar = new Bar();
$bar->echo('foo');
```

```
Fatal error:  Declaration of Bar::echo($var) must be compatible with Foo::echo(string $var): void [...] on line 13
```

**Comment by jvasseur** [comment]
@wimski you get this error because you drop de `void` return type in the inherited class, if you only remove the argument type it works without problems in PHP 7.4
