### ISSUE TITLE
Annotation in ContainerInterface::getParameter causing trouble with static analysis

### ISSUE THREAD

**Issue by garak** [symfony/symfony#40088]
**Description**  

Current phpdoc of getParameter method in [ContainerInterface](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/DependencyInjection/ContainerInterface.php) reads like following:

```php
    /**
     * Gets a parameter.
     *
     * @param string $name The parameter name
     *
     * @return array|bool|float|int|string|null The parameter value
     *
     * @throws InvalidArgumentException if the parameter is not defined
     */
    public function getParameter($name);
```

Problem is that if you try to do something like `$path = $container->getParameter('kernel.project_dir').'/public/myfile.png'`, phpstan is complaining: 

>Binary operation "." between array|bool|float|int|string|null and '/public/myfile.png' results in an error.

You can't event try to force parameter to string, like `$dir = (string) $container->getParameter('kernel.project_dir')`, because it's causing

>Cannot cast array|bool|float|int|string|null to string.

I think the only way to solve this is replacing current return type with "mixed"

**Comment by xabbuh** [comment]
Why would `mixed` change anything here? `mixed` also covers `array` for example which should lead to the same (a similar) report, right?

**Comment by xabbuh** [comment]
I guess to satisfy your static code analyzer you need to write something like this:

```php
/* @var string $projectDir */
$projectDir = $container->getParameter('kernel.project_dir');
```

**Comment by garak** [comment]
Yes, forcing every instance can be a solution, but it's a bit cumbersome (needed to be repeated for every occurrence).
By the way, "mixed" is not causing any complaint from phpstan

**Comment by nicolas-grekas** [comment]
But `mixed` is less accurate than the current union, as it tells that objects would be allowed, which would be wrong.

**Comment by fabpot** [comment]
Closing as there is nothing wrong in Symfony.

**Comment by xabbuh** [comment]
> By the way, "mixed" is not causing any complaint from phpstan

Isn't that a bug in PhpStan?

**Comment by stof** [comment]
@xabbuh I think phpstan treats `mixed` in the same way than Typescript treats `any`: allowing anything on it. I'm pretty sure that Psalm does it the other way as it tends to be stricter.

**Comment by wouterj** [comment]
By the way, this might be something that can be contributed to https://github.com/phpstan/phpstan-symfony.

Also, you can "fix" this by injecting the parameter instead of using the container as service locator.

**Comment by garak** [comment]
> By the way, this might be something that can be contributed to https://github.com/phpstan/phpstan-symfony.

Ah, that's an interesting option! Do you have an idea on how we could proceed?
 
> Also, you can "fix" this by injecting the parameter instead of using the container as service locator.

I normally do that, but this was a case where I needed parameter inside a test

**Comment by wouterj** [comment]
> Do you have an idea on how we could proceed?

Sorry, I haven't gone that deep into PHPstan. You may use [PHPstan's GitHub discussion](https://github.com/phpstan/phpstan/discussions) or `#static-analysis` on Symfony slack to ask for pointers from the PHPstan maintainers/contributors. E.g. a basic one is to create a static stub in the package that defines `@return mixed` for this method. But a better fix would probably use the container dump to evaluate the return type based on the parameter name.
