### ISSUE TITLE
New component : Obfuscator

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#40090]
Hi,
It would be great to have a new component: Obfuscator.

For instance, with a ID (ex: 58), it's generates a integer obfuscated (ex: 1762817945).

We will be able to encode and decode this integer.

**Comment by ro0NL** [comment]
https://github.com/vinkla/hashids
https://github.com/jenssegers/optimus

i dont see a need to compete with those :/

**Comment by fabpot** [comment]
I agree with @ro0NL
