### ISSUE TITLE
[Cache] No logs with TagAwareAdapter

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#40108]
**Symfony version(s) affected**: all

Contrary to other adapters, `TagAwareAdapter` does not have a `$logger` property so it produces no logs. It's especially visible if you have an existing pool: adding `tags: true` makes the logs disappear. Implementing `LoggerAwareInterface` and using `LoggerAwareTrait` + tweaking some DI definitions resolve it. Can we consider this a bug fix, or is that a feature?

**Comment by nicolas-grekas** [comment]
But a TagAwareAdapter takes another pool as argument. It's expected that this decorated pool logs. Maybe that's a wiring issue then?

**Comment by fancyweb** [comment]
The decorated pool does not log.
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Cache/Traits/ContractsTrait.php#L88 `$this->logger` here does not exist.

**Comment by nicolas-grekas** [comment]
That's why then. PR welcome :)
