### ISSUE TITLE
symfony/workflow add feature to get all available states

### ISSUE THREAD

**Issue by Bast1onCZ** [symfony/symfony#40119]
**Description**  
Hello, 
could someone please add feature in `symfony/workflow` to `WorkflowInterface` and its implementations to allow users to get all states, that are accessible through current available transitions? 

**Example implementation**  
```
$orderWorkflow = $info->getContainer()->get('state_machine.commerce_order');

$availableStates = [];
foreach ($orderWorkflow->getEnabledTransitions($order) as $transition) {
  foreach ($transition->getTos() as $availableState) {
     $availableStates[] = $availableState;
  }
}
                    
return array_unique($availableStates);
```

**Comment by Nyholm** [comment]
Hey. 

Thank you for this issue. Your implementation works great for a StateMachine. But a Workflow's "state" could have multiple places. 

Could you elaborate why this feature is needed? What is your scenario?

**Comment by Bast1onCZ** [comment]
Well, I think that this feature would be mainly used for state machines (but doesn’t have to be limited just for them).

The reason why I’d appreciate it is that sometimes you want to let users of your system select one of currently available states without forcing them to think what possible transitions are behind this.

**Comment by Nyholm** [comment]
Thank you for giving me your use case. 

The workflow component is very much a tool to manage your code. It is not meant to be exposed for users. I do understand that there are applications where this might be handy (and the component work excellent for that). 

What you describing is an edge case for an application feature, I think it is fair to not merge such feature into the core. The few lines of code you provided is an excellent workaround for state machines. 

I appreciate the suggestion.

**Comment by jeroendesloovere** [comment]
This feature would be so nice
