### ISSUE TITLE
Easily opt out from Traceable decorations

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#40110]
```php
final class ArgumentValueResolver1 implements ArgumentValueResolverInterface
{
}

final class ArgumentValueResolver2 implements ArgumentValueResolverInterface
{
	private ArgumentValueResolver1 $argumentValueResolver1;

	public function __construct(ArgumentValueResolver1 argumentValueResolver1)
	{
		$this->argumentValueResolver1 = $argumentValueResolver1;
	}
}
```
Basically, one of my argument value resolver is encapsulating another one. It doesn't work well in dev since the argument value resolvers are decorated into `TraceableValueResolver` (so the argument passed to `ArgumentValueResolver2` does not respect the contract). I guess it can happen with all Traceable*. It's not easy to opt out from it: only use anonymous service, or manually undo what `ControllerArgumentValueResolverPass` did. Could we think of a better way?

**Comment by ro0NL** [comment]
why not depend on the decorator contract? `ArgumentValueResolverInterface $argumentValueResolver1` + binding/manual wiring

ultimately we could check if the decorated service matches the type, in case the decorator doesnt. Then unpack it on the fly ... autowiring 2.0 :)

**Comment by Neirda24** [comment]
If you use decoration as well, why not use the decoration priority? Would it not fix your trouble and allow the traceable on your new decoration?

**Comment by fancyweb** [comment]
> why not depend on the decorator contract?

The real case is more complicated. The argument value resolvers implement a common interface. I want to type the arg with that interface. Allowing any `ArgumentValueResolverInterface` instances is not OK from my POV.

> why not use the decoration priority?

I don't think decoration priority can solve it. In the end, there is only one instance of  `ArgumentValueResolver1` in the container and it is decorated and `TraceableValueResolver` does not implement my interface.

My current solution is to inline the `ArgumentValueResolver1` arg for `ArgumentValueResolver2` and have another separate real instance.

**Comment by Neirda24** [comment]
> I don't think decoration priority can solve it. In the end, there is only one instance of ArgumentValueResolver1 in the container and it is decorated and TraceableValueResolver does not implement my interface.

Create your own TraceableValueResolver as so :

new YourTraceableValueResolver(new TraceableValueResolver(new ArgumentValueResolver1... and so on ? Just trying to help.
