### ISSUE TITLE
Multiple connection to databases

### ISSUE THREAD

**Issue by lfaveur** [symfony/symfony#40115]
Hi,
I followed this documentation for muti connection to database https://symfony.com/doc/4.4/doctrine/multiple_entity_managers.html

I created an entity correctly using make:entity but when I wanted generated migration ...  I got an error when i do this 
`php bin/console doctrine:migrations:migrate --em=customer`

![image](https://user-images.githubusercontent.com/20400434/107117995-58357b00-687e-11eb-8410-d2956f2b7938.png)
 
'second' is the name of my connection. The problem is --em option does not exist.

In my composer.json I have doctrine/doctrine-migrations-bundle, this bundle require doctrine/migrations so I search all available option : 
`php bin/console doctrine:migrations:migrate --help`

but i didn't saw --em option ... what i did wrong ? 

Thanks for any help !

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
