### ISSUE TITLE
[HttpFoundation] Sync session not found exception

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#40112]
Since #38616 there's exception type variance in `getSession()` between `RequestStack` and `Request`, when the session is not found 

https://github.com/symfony/symfony/blob/a12db94a06fbfc6077c2613d479f9de559c9af03/src/Symfony/Component/HttpFoundation/RequestStack.php#L110-L112

vs.

https://github.com/symfony/symfony/blob/a12db94a06fbfc6077c2613d479f9de559c9af03/src/Symfony/Component/HttpFoundation/Request.php#L737-L738

for simplicity, i think we should throw the same exception type in Request::getSession(), and let RequestStack simply forward the call.

the `catch(BadMethodCallException)` as "cheap hasSession" will break, but we explicitly mentioned to use hasSession instead already

https://github.com/symfony/symfony/blob/f1a7dcafe0ca490fd018b54a6c99221cc0d144c2/src/Symfony/Component/HttpFoundation/Request.php#L726-L727

ppl doing it as of 5.x rely on implementation details (the `@throws BadMethodCallException` isnt documented)

so, given both are LogicException it seems reasonable :) 

cc @jderusse

**Comment by jderusse** [comment]
#40114 I think `SessionNotFoundException extends \BadMethodCallException` works and provide a migration path to users.
