### ISSUE TITLE
Error when upgrading twig/extra-bundle to v3.2.1

### ISSUE THREAD

**Issue by bastien70** [symfony/symfony#40117]
**Symfony version(s) affected**: 5.2.3

**Description**  
After a composer update, my **twig/extra-bundle** to **v3.2.1**.

While caching clear, I have a big error, and now my pages are inaccessible, and I have the following error:

```
Attempted to call an undefined method named "registerUndefinedTokenParserCallback" of class "Twig\Environment".
Did you mean to call e.g. "registerUndefinedFilterCallback" or "registerUndefinedFunctionCallback"?
```

**How to reproduce**  
Just update to twig/extra-bundle v3.2.1 : 

![image](https://user-images.githubusercontent.com/53140475/107119441-dc403080-6887-11eb-8f7b-d6ae482c8adb.png)

**Additional context**  

**Symfony version** : 5.2.3
**PHP version** : 7.3.5
**Twig version** : 2.14.3

UPDATE : It was because of **twig/extensions**. I deleted it, and was able to update Twig to v3. No more worries.

But is there something replacing **twig/extensions**?

**Comment by Nyholm** [comment]
Most things in twig/extensions has been added to twig core. There are a few "extra" packages, you will find them here https://packagist.org/packages/twig/

**Comment by xabbuh** [comment]
Let's close here as the issue is not related to Symfony.
