### ISSUE TITLE
Issue with $this->getUser() relations

### ISSUE THREAD

**Issue by AmirZandi13** [symfony/symfony#40122]
How we can delete all left joins when we call $this->getUser()?

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
