### ISSUE TITLE
[Notifier] Should not throw when no recipients

### ISSUE THREAD

**Issue by norkunas** [symfony/symfony#40128]
**Description**  
When having many notifications it's cumbersome to manually resolve recipients list all the time so you start abstract the recipient resolving somewhere to reuse it. Sometimes there are no recipients because nobody subscribed to notification topic or all just unsubscribed and when trying to send with empty recipients then Symfony adds NoRecipient to the list. The problem is that none of configured channels supports it and then Notifier throws error.

At least it would be nice to have this configurable or skip notifying at all if no recipients.

**Example**  
None

**Comment by OskarStark** [comment]
While thinking about this topic, does it make sense to send notifications without a recipient?

IIRC @jschaedl you worked on that topic, maybe you can leave your 2 cents here? Thank you

**Comment by norkunas** [comment]
> While thinking about this topic, does it make sense to send notifications without a recipient?

Then there so would many checks.. :D

**Comment by fabpot** [comment]
I agree with @OskarStark, when you call decide to send a notification, we need a recipient, that's a check that should be done in the application, not Symfony.

**Comment by xabbuh** [comment]
@norkunas I suggest to decorate the notifier in your application that doesn't forward to the one from core if there is no recipient.

**Comment by norkunas** [comment]
@xabbuh thanks, yes, went this way recently with decoration :)

But it is still unclear to me why Notifier adds the `NoRecipient` to the recipients list if there are none instead of just throwing directly?
