### ISSUE TITLE
Declaration of RedirectResponse::create($url = '', int $status = 302, array $headers = Array) should be compatible with Response::create(?string $content = '', int $status = 200, array $headers = Array)

### ISSUE THREAD

**Issue by php-cpm** [symfony/symfony#40123]
**Symfony version(s) affected**: v5.2.3

**Description**  

I got error with omnipay using component `symfony/http-foundation`

[2] ErrorException in api/vendor/symfony/http-foundation/RedirectResponse.php line 19
Declaration of Symfony\Component\HttpFoundation\RedirectResponse::create($url = '', int $status = 302, array $headers = Array) should be compatible with Symfony\Component\HttpFoundation\Response::create(?string $content = '', int $status = 200, array $headers = Array)

**How to reproduce**  

I don't konw how, i read the `symfony/http-foundation` code, it's there in a long time

**Possible Solution**  

change  

Symfony\Component\HttpFoundation\RedirectResponse::create($url = '', int $status = 302, array $headers = Array)

to

Symfony\Component\HttpFoundation\RedirectResponse::create(?string $url = '', int $status = 302, array $headers = Array)

**Additional context**

**Comment by xabbuh** [comment]
seems like you were running your application with PHP 7.1 (see https://3v4l.org/30v17) while you need PHP 7.2.5 or higher
