### ISSUE TITLE
Inconsistent docblock in web-link / Link.php

### ISSUE THREAD

**Issue by Punk-UnDeaD** [symfony/symfony#40126]
**Symfony version(s) affected**: 4.4.* | 5.*

**Description**  
Link.php implements EvolvableLinkInterface and override withAttribute(string $attribute, string $value) by withAttribute($attribute, $value), $value can by mixed now, but in docblock still string.
Child can extend parent param types and all work ok, but phpstan report error when I use withAttribute('crossorigin', true).

[HttpHeaderSerializer](https://github.com/symfony/web-link/blob/5.x/HttpHeaderSerializer.php#L40) support not only string.
[twig-bridge](https://github.com/symfony/twig-bridge/blob/5.x/Extension/WebLinkExtension.php#L53) docblock contain info about supporting true and real values.

We need update docblock to actual.

**Comment by nicolas-grekas** [comment]
Related: https://twitter.com/mbabker/status/1358948688303968257

**Comment by nicolas-grekas** [comment]
Also related: https://github.com/symfony/web-link/pull/1
