### ISSUE TITLE
[messenger][Doctrine] doctrine:schema:create breaks

### ISSUE THREAD

**Issue by alexdruhet** [symfony/symfony#40130]
**Symfony version affected**: 5.2.3

**Description**  
Using Postgresql and `symfony/doctrine-messenger`, upgrading to `symfony/doctrine-messenger` 5.2.3 breaks `doctrine:schema:create` command.

**How to reproduce**  
`bin/console doctrine:schema:create`

**Possible Solution**  
The bug was introduced by PR #40055. Reverting it solve the issue but also reopens #39928. This must be taking into account to define a PR. 

For now I have put a composer version constraint:
```
...
"symfony/doctrine-messenger": "^5.1 <5.2.3",
...
```

**Additional context**  
The response returned by `bin/console doctrine:schema:create`:
> In ToolsException.php line 34:
>                                                                                                                                                                 
>   Schema-Tool failed with Error 'An exception occurred while executing 'LOCK TABLE messenger_messages;':                                                        
>                                                                                                                                                                 
>   SQLSTATE[25P01]: No active sql transaction: 7 ERROR:  LOCK TABLE can only be used in transaction blocks' while executing DDL: LOCK TABLE messenger_messages;  
>                                                                                                                                                                 
> 
> In AbstractPostgreSQLDriver.php line 102:
>                                                                                                            
>   An exception occurred while executing 'LOCK TABLE messenger_messages;':                                  
>                                                                                                            
>   SQLSTATE[25P01]: No active sql transaction: 7 ERROR:  LOCK TABLE can only be used in transaction blocks  
>                                                                                                            
> 
> In Exception.php line 18:
>                                                                                                            
>   SQLSTATE[25P01]: No active sql transaction: 7 ERROR:  LOCK TABLE can only be used in transaction blocks  
>                                                                                                            
> 
> In PDOConnection.php line 125:
>                                                                                                            
>   SQLSTATE[25P01]: No active sql transaction: 7 ERROR:  LOCK TABLE can only be used in transaction blocks  
>                                                                                                            
> 
> doctrine:schema:create [--dump-sql] [--em [EM]]

**Comment by jrushlow** [comment]
I'm having a similar issue when attempting to run tests using https://github.com/zenstruck/foundry or when running `bin/console messenger:setup-transports`

**Comment by alexdruhet** [comment]
In my opinion, if the case exposed in #39928 can be solved by manipulating transaction within migration, it would be right to revert #40055 to avoid breaking backwards compatibility.

**Comment by baiiko** [comment]
Hi people, i've this problem too.

If you don't use auto setup, you app need a migration, or if you use auto setup, juste apply messenger:setup-transports with the first fix https://github.com/symfony/symfony/pull/38136.

**Comment by alexdruhet** [comment]
> If you don't use auto setup, you app need a migration, or if you use auto setup, juste apply messenger:setup-transports to with the first fix #38136.

I agree with auto setup case. Indeed #40055 override #38136 and cause this issue.

**Comment by baiiko** [comment]
yes but with auto setup, this case https://github.com/symfony/symfony/pull/40055 does not work

**Comment by alexdruhet** [comment]
> yes but with auto setup, this case #40055 does not work

we agree, that's what I meant

**Comment by Nyholm** [comment]
Hey @alexdruhet
Do you have a suggestion how to fix this issue?

**Comment by alexdruhet** [comment]
Hi @Nyholm, 
my initial suggestion would be to revert #40055 as #38136 worked very fine with my setup. But it depends on the edge case exposed by #39928. Considering that last can be resolved by starting/closing the transaction "manually"  in the generated migration, this may be a compromise we can be satisfied with.

**Comment by Nyholm** [comment]
I agree with you. I started a PR and I will work to fix  #39928 in a different way. 
I'll also add some tests to make sure this is happening again.

**Comment by alexdruhet** [comment]
I just see that, thanks for helping!
