### ISSUE TITLE
fabbot.io tries to apply a patch for #[\Attribute

### ISSUE THREAD

**Issue by wkania** [symfony/symfony#40149]
**Symfony version(s) affected**: 5.x

**Description**  
fabbot is using  [PHP CS Fixer 2.18](https://github.com/symfony/symfony/pull/39868#issuecomment-762688825), so this should not be a problem. The leading backslash is [recommended](https://github.com/symfony/symfony-docs/pull/14865#discussion_r562537865).

[Current code](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php#L24)
[Patch](https://fabbot.io/patch/symfony/symfony/38662/2015ad9295cf98eb340dfc67874e69c3460978c2/cs.diff)
```
diff -ru src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php
--- src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php	2021-02-10 21:32:14.283031188 +0000
+++ src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php	2021-02-10 21:32:15.265010897 +0000
@@ -21,7 +21,7 @@
  *
  * @author Benjamin Eberlei <kontakt@beberlei.de>
  */
-#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
+#[Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
 class UniqueEntity extends Constraint
 {
     public const NOT_UNIQUE_ERROR = '23bd9dbf-6b9b-41cd-a99e-4844bcf3077f';
```

**How to reproduce**  

**Possible Solution**  

**Additional context**  
Checks were not successful in the [PR](https://github.com/symfony/symfony/pull/38662).

I checked it locally and there was no problem:
```
composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer:2.18.0
tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php 
Loaded config default from ".php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.

Fixed all files in 0.097 seconds, 12.000 MB memory used
```

**Comment by stof** [comment]
which PHP version are you using locally ? PHP 7 or PHP 8 ? As php-cs-fixer relies on the token parsed by PHP, the behavior when encountering attributes might differ (on PHP 7, php-cs-fixer will see a comment, not an attribute)

**Comment by wkania** [comment]
I retested it locally with PHP 8.0.2 and it applied the patch.
Then a bug in CSFixer.

**Comment by wkania** [comment]
I opened the [issue](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5497) so closing.
