### ISSUE TITLE
Impossible to use '!x-forwarded-host' in framework.trusted_headers

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#40156]
**Symfony version(s) affected**: 5.2

**Description**
I'm trying to configure trusted proxies and trusted hosts but I receive an error:

> The value "!x-forwarded-host" is not allowed for path "framework.trusted_headers.1". Permissible values: "forwarded", "x-forwarded-for", "x-forwarded-host", "x-forwarded-proto", "x-forwarded-port"

**How to reproduce**  

Simply use this configuration:

```yaml
# config/packages/framework.yaml
framework:
    trusted_headers: ['forwarded', '!x-forwarded-host', '!x-forwarded-prefix']
```

**Additional context**  

Before using the config file, I configured trusted proxies and hosts directly in the `index.php` file and all worked as expected:

```php
<?php

// public/index.php

...

if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}

if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? false) {
    Request::setTrustedHosts([$trustedHosts]);
}
...
```

Using `!x-forwarded-host` in the configuration is suggested also by the documentation: https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

```php
# config/packages/framework.yaml
framework:
    # ...
    // the IP address (or range) of your proxy
    trusted_proxies: '192.0.0.1,10.0.0.0/8'
    // trust *all* "X-Forwarded-*" headers (the ! prefix means to not trust those headers)
    trusted_headers: ['x-forwarded-all', '!x-forwarded-host', '!x-forwarded-prefix']
    // or, if your proxy instead uses the "Forwarded" header
    trusted_headers: ['forwarded', '!x-forwarded-host', '!x-forwarded-prefix']
    // or, if you're using a wellknown proxy
    trusted_headers: [!php/const Symfony\\Component\\HttpFoundation\\Request::HEADER_X_FORWARDED_AWS_ELB, '!x-forwarded-host', '!x-forwarded-prefix']
    trusted_headers: [!php/const Symfony\\Component\\HttpFoundation\\Request::HEADER_X_FORWARDED_TRAEFIK, '!x-forwarded-host', '!x-forwarded-prefix']

```

**Comment by stof** [comment]
support for negated values in the semantic config was removed before the 5.2 stable release, when deprecating the `*_ALL` constant. that's a documentation issue.

**Comment by Aerendir** [comment]
@stof , ok...

So, how can I reproduce the configuration I had with PHP?

**Comment by stof** [comment]
`x-forwarded-port, x-forwarded-ip, x-forwarded-protocol` (i.e. the same combination you would do it in PHP if you cannot use the `HEADER_X_FORWARDED_ALL` constant anymore for that)

**Comment by stof** [comment]
I reported the documentation issue at https://github.com/symfony/symfony-docs/issues/14961

**Comment by xabbuh** [comment]
closing in favour of the documentation issue
