### ISSUE TITLE
[Form] Submit buttons in form_div_layout get Bootstrap classses

### ISSUE THREAD

**Issue by I-Valchev** [symfony/symfony#40151]
**Symfony version(s) affected**: 5.1 (and possibly other)

**Description**  
Using the `form_div_layout.html.twig`, I do not expect any `col-2`, `form-group` and other Bootstrap classes to be added to the `submit` button type. But the rendered HTML includes those.

**How to reproduce**  
Set up a form using the `form_div_layout` with a `submit` button.

**Possible Solution**  
The issue is probably happening because the `form_div_layout.html.twig` does not have a `submit_row` block, hence it fallbacks to something else that does (one of the bootstrap templates).

Take a look: https://github.com/symfony/symfony/search?q=submit_row

By including a `{% block submit_row -%}` with proper HTML to render the submit button in `form_div_layout.html.twig`, the issue is resolved.

**Additional context**  
I'm happy to work on a PR that fixes it, if I'm given green lights that this is the right solution. (And some guidance about what branch to checkout the PR against)

Special thanks goes to @nestordedios for discovering the issue and working through a solution with me. 🙌

**Comment by stof** [comment]
Can you share a reproducing case ? I don't see how `form_div_layout.html.twig` would fallback to the bootstrap theme block as it never references the bootstrap template to import it.

**Comment by I-Valchev** [comment]
@stof not sure how I'd share the entire thing in fairness, but it did add `form-group`, `col-2`, `col-6` classes, and after adding the `submit_row` block with proper twig and html, it worked fine.

That's why I mentioned to reproduce this you'd need to setup a form using the layout with a submit button.

**Comment by ro0NL** [comment]
can you confirm it's not a global theming issue or so in your app? see also https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by xabbuh** [comment]
Closing here as I think that's a configuration issue. Please feel free to provide a reproducer application if you don't agree and we can consider to reopen.
