### ISSUE TITLE
Adding a script to the head node add it to the body instead

### ISSUE THREAD

**Issue by CrochetFeve0251** [symfony/symfony#40164]
**Symfony version(s) affected**: x.y.z

**Description**  

While trying to add a facebook pixel on a client page to serve it later. I got an issue while adding a node script to the head.
It added it to the body instead.
**How to reproduce**  

https://gist.github.com/CrochetFeve0251/e08db8e2499340dccd5e7feca749a722
**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
I cannot reproduce this. Can you please create a small example application that allows to reproduce your issue?

**Comment by CrochetFeve0251** [comment]
I tried with a simple example and it works perfectly fine:
```<html><head></head><body></body></html>```
However when I use it on a real client page it doesn't work anymore:
https://gist.github.com/CrochetFeve0251/85261844a556784f506624c06492752d

Btw this is the versions I use of the librairy:
- "symfony/css-selector": "^5.2",
- "symfony/dom-crawler": "^5.2"

**Comment by xabbuh** [comment]
For me it even works with that HTML document.
