### ISSUE TITLE
[Workflow] Dumper for Mermaid.js Flowcharts

### ISSUE THREAD

**Issue by eFrane** [symfony/symfony#40165]
**Description**  

While PlantUML and Graphviz are already two solid options for dumping workflows, I found myself wishing for a [Mermaid](https://mermaid-js.github.io/mermaid/#/)-compatible flowchart output the other day. 

I already wrote this dumper, but before opening a pull request I thought it better to create this issue first and gather general interest or need. It is very possible that this is a niche feature request and should better live as a separate composer package.

**Example**  

Using the [simple test workflow](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Workflow/Tests/WorkflowBuilderTrait.php#L46), the dumper generates:

```plain
graph TD
a([a])
b[b]
c[c]
style c fill:DeepSkyBlue
a-->|t1|b
b-->|t2|c
```

which in turn renders to

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbmEoW2FdKVxuYltiXVxuY1tjXVxuc3R5bGUgYyBmaWxsOkRlZXBTa3lCbHVlXG5hLS0-fHQxfGJcbmItLT58dDJ8YyIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmEoW2FdKVxuYltiXVxuY1tjXVxuc3R5bGUgYyBmaWxsOkRlZXBTa3lCbHVlXG5hLS0-fHQxfGJcbmItLT58dDJ8YyIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

It works exactly as the existing dumpers. Feature wise, it supports place background colors, but doesn't support arrow styling.

**Comment by stof** [comment]
If the dumper does not depend on external dependencies and is simple enough, I would be OK to have it in the component alongside existing ones. This would allow adding this format in the `workflow:dump` command of FrameworkBundle (if the dumper is third-party, it would require creating a separate third-party command to use it)

**Comment by eFrane** [comment]
It is just a straight-forward conversion to text, I will go ahead and open the PR. I am a bit unsure as to how to modify the Docs as it doesn't quite fit into the current "download one of these tools"-wording but even if this lands in 5.3, there should be more than enough time to figure that part out.
