### ISSUE TITLE
issue with pack dependencies using *

### ISSUE THREAD

**Issue by mpoiriert** [symfony/symfony#40177]
**Symfony version(s) affected**: pack package

**Description**  
pack system (e.g. symfony/orm-pack, symfony/debug-pack, etc.) are configure with dependencies with "**" that might case chain update causing problem. This have already been raise with the orm pack on a doctrine migration bundle (I think) and now I have the same kind of is issue with symfony/monolog-bundle -> monolog/monolog that have a version 2.* release that have compatibility break with formatter and group logger.
 
**How to reproduce**  

**Possible Solution**  
- Stop using * in pack
- Stop recommending Pack (Make package pack deprecated)
- Change the pack "feature" to have a tools that install/update "pack dependencies" instead of having a composer pack package.

**Additional context**

**Comment by nicolas-grekas** [comment]
Thanks for the report. Packs are now auto-unpacked for this reason. Unpack them if you didn't already.
