### ISSUE TITLE
error 500 symfony serve

### ISSUE THREAD

**Issue by hrobben** [symfony/symfony#40189]
![Screenshot_20210214_211354](https://user-images.githubusercontent.com/12062316/107887906-b7902c80-6f09-11eb-9768-d0735813f53e.png)
**Symfony version(s) affected**: 5.2.*

**Description**  
Symfony serve does work, but when reload or change to next page error 500, and empty pages, debug is not loaded, give error.

**How to reproduce**  
make simple code websceleton --full and after starting symfony serve you can load basic page, make a controller and load it, problem will show 

**Possible Solution**  
 thinking about ip v4 versus ipv 6

**Additional context**  
Feb 14 21:06:10 |ERROR  | SERVER GET  (500) /_wdt/20ce2e 
[PHP        ] [Sun Feb 14 21:06:10 2021] 127.0.0.1:39304 Accepted
[PHP        ] [Sun Feb 14 21:06:10 2021] PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInit57d6e1cbe1a92df2127054116dce2109::getLoader() in /home/hrobben/html/jonseniorenzm/vendor/autoload.php:12
[PHP        ] Stack trace:
[PHP        ] #0 /home/hrobben/html/jonseniorenzm/public/index.php(8): require()
[Web Server ] Feb 14 21:06:10 |INFO   | SERVER GET  (200) /favicon.ico?v=2 ip="::1"
[Web Server ] Feb 14 21:06:10 |ERROR  | SERVER GET  (500) /img/favicon.png 
[PHP        ] #1 /home/hrobben/.symfony/php/33eb51ce268680abcf2ce1a96ed035729e283b99-router.php(33): require('/home/hrobben/h...')
[PHP        ] #2 {main}
[PHP        ]   thrown in /home/hrobben/html/jonseniorenzm/vendor/autoload.php on line 12
[PHP        ] [Sun Feb 14 21:06:10 2021] 127.0.0.1:39304 Closing

**Comment by a1812** [comment]
do it
$ symfony check:requirements
$ composer valid

https://symfony.com/doc/current/setup.html

**Comment by hrobben** [comment]
symfony check:requirements:
Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
/etc/php/7.4/cli/php.ini

> Checking Symfony requirements:

......................................

                                              
 [OK]                                         
 Your system is ready to run Symfony projects 
                                              

Note  The command console can use a different php.ini file
~~~~  than the one used by your web server.
      Please check that both the console and the web server
      are using the same PHP version and configuration.


and 
Composer valid:
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
name : The property name is required
description : The property description is required
require.composer/package-versions-deprecated : exact version constraints (1.11.99.1) should be avoided if the package follows semantic versioning

Thanks

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions about using Symfony, please use StackOverflow.

Thanks!
