### ISSUE TITLE
Bootstrap 5 form theme

### ISSUE THREAD

**Issue by garak** [symfony/symfony#40185]
**Description**  
Bootstrap 5 is currently in beta, and it will be likely stable for May (when Symfony 5.3 is planned to be released).
I think it would be nice to add a theme for it, along with currently supported Bootstrap 3 and Bootstrap 4.

**Comment by jderusse** [comment]
see https://github.com/symfony/symfony/pull/39157

**Comment by garak** [comment]
Why closing? Related PR is not merged yet...

**Comment by fabpot** [comment]
There is no need to keep an issue as there is a pre-existing PR.
