### ISSUE TITLE
[DoctrineBridge] Ulid is not converted when deleting a ManyToMany Relation

### ISSUE THREAD

**Issue by nuil** [symfony/symfony#40199]
**Symfony version(s) affected**: 5.2.3 (PHP7.4.13 MySQL: 8.0.22)

**Description**  
When deleting an Entity with a Many-To-Many relation the entry of the join table won't be deleted correctly. The ulid object will be converted to a string, instead to binary. (See attached screenshot)

**How to reproduce**  
Entity:
```php
/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\EntityListeners({"App\EventListener\CampaignListener"})
 */
class Campaign
{
    /**
     * @ORM\Id
     * @ORM\Column(type="ulid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UlidGenerator::class)
     */
    public $id;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Gallery", mappedBy="campaigns")
     */
    public $galleries;
...
}

/**
 * @ORM\Entity
 */
class Gallery
{
    /**
     * @ORM\Id
     * @ORM\Column(type="ulid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UlidGenerator::class)
     */
    public $id;
    
    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Campaign", inversedBy="galleries")
     * @ORM\JoinTable(name="gallery_has_campaign",
     *     joinColumns={@ORM\JoinColumn(name="gallery_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="campaign_id", referencedColumnName="id")
     * })
     */
    public $campaigns;

   ...
}
```
Code to Delete:
```php
        $entity = $this->entityManager->getRepository('App:Campaign')->findOneBy(['id' => Ulid::fromString('01EXEV28NSPPW7PMGRKHG5SEWH')]);

        $this->entityManager->remove($entity);
        $this->entityManager->flush();
```

**Additional context**  
![Screenshot 2021-02-15 at 12 40 34](https://user-images.githubusercontent.com/2334194/107942630-cd463600-6f8b-11eb-960e-bdf9885f4057.png)

**Comment by stof** [comment]
I suspect that this is an issue in doctrine/orm regarding the usage of custom types for id fields, where the ORM is not properly applying the custom type in some places.

**Comment by nuil** [comment]
Yep, that's my guess too. #39135 somewhat goes into the topic, but it is only suitable for custom code.

**Comment by nicolas-grekas** [comment]
@nuil would you mind investigating where a patch would be needed, please?

**Comment by nuil** [comment]
So if i'm getting this correctly. (I'm not a doctrine nor a symfony expert) 

The deletion of the relations of the entity, happens in 
```\Doctrine\ORM\Persisters\Entity\BasicEntityPersister::deleteJoinTableRecords```. 

The information will be directed to ```\Doctrine\DBAL\Connection::delete``` but without the types-argument.
Thus ```\Doctrine\DBAL\Connection::_bindTypedValues``` won't be called, and the object will not be converted correctly to binary.

So, doctrine doesn't have the information that the class needs to be converted. Or am I on the wrong track?

**Comment by OskarStark** [comment]
friendly ping @greg0ire

**Comment by greg0ire** [comment]
I don't know anything about this, but let's add links:

https://github.com/doctrine/orm/blob/40f392558931f7c8686e9298a667e1d78a403da5/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L568
https://github.com/doctrine/dbal/blob/f77e73135f631934293126b68119d12962180d33/src/Connection.php#L600

@nuil it looks like you're right. If you want to be sure, you could try editing BasicEntityPersister and temporarily hardcode the right type information here, then check your Sf inspector to see if it does fix the issue. If that's the case, please open an issue on `doctrine/orm`.

**Comment by nuil** [comment]
Doctrine/orm 2.8.2 fixes the issue. Details here: https://github.com/doctrine/orm/pull/8401
