### ISSUE TITLE
Coding standard violations in protected branches

### ISSUE THREAD

**Issue by localheinz** [symfony/symfony#40196]
**Symfony version(s) affected**: `4.4.19`, `5.2.3`

**Description**  

When I check out any branch, e.g., 

- `4.4` 
- `5.2`
- `5.x`

and - following https://symfony.com/doc/current/contributing/code/standards.html#making-your-code-follow-the-coding-standards - run

```sh
$ php-cs-fixer fix
```

then all of these branches contain coding standard violations.

**How to reproduce**  

Run

```sh
$ git clone git@github.com:symfony/symfony.git
$ composer global require friendsofphp/php-cs-fixer
$ php-cs-fixer fix --dry-run
```

When opening a pull request, I have also repeatedly observed that `fabbot.io` complains about coding standard violations that are unrelated to the changes proposed in a pull request. However, `fabbot.io` also only complains about a subset of the the errors reported by running `friendsofphp/php-cs-fixer` locally.

To me, that looks like a broken process. 

As a contributor, when I check out any of the protected branches and run 

```sh
$ php-cs-fixer fix --dry-run
```

I would not expect the process to complete with a non-zero exit code.

Additionally, running

```sh
$ php-cs-fixer fix --dry-run
```

also proposes fixes in some components that should not be fixed, for example, when running it in `src/Symfony/Bridge/PhpUnit`, references to class names from `phpunit/phpunit` that use pseudo-class names are adjusted to namespaced class names.

```diff
--- Original
+++ New
@@ @@

-if (class_exists(\PHPUnit_Runner_Version::class) && version_compare(\PHPUnit_Runner_Version::id(), '6.0.0', '<')) {
+if (class_exists(\PHPUnit\Runner\Version::class) && version_compare(\PHPUnit\Runner\Version::id(), '6.0.0', '<')) {
@@ @@
 // Detect if we're loaded by an actual run of phpunit
-if (!defined('PHPUNIT_COMPOSER_INSTALL') && !class_exists(\PHPUnit_TextUI_Command::class, false) && !class_exists(\PHPUnit\TextUI\Command::class, false)) {
+if (!defined('PHPUNIT_COMPOSER_INSTALL') && !class_exists(\PHPUnit\TextUI\Command::class, false) && !class_exists(\PHPUnit\TextUI\Command::class, false)) {
     return;
 }
```

**Possible Solution**  

- Allow components to declare their own configuration.
- Give developers simple tools (a `Makefile` or `composer` scripts ) to run `php-cs-fixer` against all components, with their corresponding configurations
- Run fabbot.io against all code, not only against a subset. 
- Do not merge pull requests where `fabbot.io` reports coding standard violations.
- Keep all protected branches in a green state.

**Additional context**  

For examples, see the following pull requests, and when available, additional error messages reported by `fabbot.io`:

- https://github.com/symfony/symfony/pull/40180 (https://fabbot.io/report/symfony/symfony/40180/34b320ba97acc919d16170d1ff95c47a7c195352)
- https://github.com/symfony/symfony/pull/40181
- https://github.com/symfony/symfony/pull/40182
- https://github.com/symfony/symfony/pull/40195
- https://github.com/symfony/symfony/pull/40197 (https://fabbot.io/report/symfony/symfony/40197/cf559f7a77bfae023fff0189ed9200274c0387f0)

**Comment by nicolas-grekas** [comment]
Thanks for the report.
I would be happy to be able to have no changes when running php-cs-fixer, but as I wrote in https://github.com/symfony/symfony/pull/40197#issuecomment-779103541, I personally never felt the urgency to make this a high enough priority to spend my time on it.
E.g. [space-at-end-of-line](https://github.com/symfony/symfony/pull/40197/files#diff-a5a5638c8a617d2d54ce131c6ee7989ee88d485aad4c9b6b9d2da31bccf111d7L216) violations, compat with [non-namespaced phpunit](https://github.com/symfony/symfony/pull/40197/files#diff-58d86701ef8bee2dc8f810453f5d1f75e07cf0fab7a6faff858cb8187620ff91L22), etc.

There are many situations where php-cs-fixer reports violations as it is programmed to do, but where we, with a human brain, know better than it.

On my side, I never allow tools to have the final say. Here, I deal with these false positives by ignoring them and that doesn't cost me much time - even if I'd appreciate if there weren't any of course.

**Comment by wouterj** [comment]
Btw, I think having fabbot failures on the first push is fine. It provides an easy to use command line code for you to automatically fix them on the second push.

Of course, if this is important for you as a contributor, you're more than welcome to contribute a working PHP CS Fixer config (but be warned that fixing CS in the code is usually rejected due to the amount of work it generates for maintainers - I would recommend making sure the config doesn't report false positives instead. That way, a maintainer can fix the CS across all branches in one go).

**Comment by stof** [comment]
Well, we already have the PHP-CS-Fixer config in the repo.

What happened is that based on a request from @nicolas-grekas, the `@Symfony:risky` ruleset of PHP-CS-Fixer was updated to prefix all constants rather than only a few ones.
When fabbot updated its php-cs-fixer version, it got the new rule. But this new rule has not been run on all the existing code yet.

that's a case of changing our CS config without fixing the existing code...
