### ISSUE TITLE
Kernel attempts to write to Kernel->getBuildDir() at runtime

### ISSUE THREAD

**Issue by Lacoz** [symfony/symfony#40207]
**Symfony version(s) affected**: 5.2.3

**Description**  
Iam trying to install blank symfony app with helloworld controller to Google app engine standard php74 runtime.
To have cache warmup + opcache preload performance benefits iam using getBuildDir() to point to /workspace/buildcache directory. When app engine install vendor/ libs and generates cache all looks ok, container files are generated, cache is writen.
But when i open the deployed application with browser i see 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
With 
APP_DEBUG=1
Warning: file_put_contents(/workspace/buildcache/App_KernelDevDebugContainerDeprecations.log): failed to open stream: Read-only file system
 in /workspace/vendor/symfony/http-kernel/Kernel.php (line 546)

                $container->compile();
            } finally {
                if ($collectDeprecations) {
                    restore_error_handler();
                    file_put_contents($buildDir.'/'.$class.'Deprecations.log', serialize(array_values($collectedLogs)));

**Comment by Lacoz** [comment]
It seems the latest version of symfony has fixed this https://github.com/symfony/http-kernel/commit/cde9ee85487932a1c8064ae685e5d0488c3ae12b#diff-1cec0a95a77d07f3d4119759be23a06cee7b06c7827ed6d3306e4395613fdbab

**Comment by stof** [comment]
Well, if you run the kernel in debug mode, it will check whether the cached container needs to be rebuilt.

The code you linked is not part of the runtime of the kernel but of the build time. But the debug mode is precisely about rebuilding automatically (instead of forcing to clear the cache manually)

**Comment by stof** [comment]
Also, make sure you ran `cache:warmup` as part of your build. Otherwise, the kernel will still need to do it on the first request to build the cache.
