### ISSUE TITLE
Call to mb_* functions on a null string (PHP8.1-incompatible)

### ISSUE THREAD

**Issue by Yopai** [symfony/symfony#40200]
**Symfony version(s) affected**: (at least) 4.4.19

**Description**  
`Symfony\Component\Console\Helper::strlen` calls `mb_detect_encoding`
`$string` argument is typed as string in phpdoc, but this function is sometimes called with a null argument (in the "reproduce" case, it's the getShortcut() of a command definition option)

In the mbstring polyfill, `mb_detect_encoding` requires first argument to be string.

But in fact, despite what is said the documentation, in the real mbstring implementation, `mb_detect_encoding` accepts a first argument which is null.

**How to reproduce**  
With a php8.0 binary **with php8.0-mbstring NOT installed**, run `bin/console help`.

> Description:
>   Displays help for a command
> 
> Usage:
>   help [options] [--] <command> [<command_name>]
> 
> [error] Error thrown while running command "help". Message: "mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54"
> 
> [critical] Uncaught Error: mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54
> 
> 
> **In bootstrap80.php line 48:**
>                                                                                                                                                                            
> **mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54 **
>                                                                                                                                                                            
> 
> help [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<command_name>]

**Proposed solution (part 1) : Fix the polyfill**
In bootstrap80.php, don't typehint the first argument, so has to have the same behaviour than the mbstring php extension.

**Proposed solution (part 2) : Workaround for the use of a null argument**
In Symfony\Component\Console\Helper::strlen, test if `$string` is null, and if so return 0 (or set `$string = ''`, but it's not really necessary)

**Proposed solution (part 3) : Deprecate the use of a null argument**
- Mark calls with a null argument as deprecated, and check calls in Symfony code
- For next major version, hard type `$string` as string, and remove test added in part 2.

**Additional context**  
Can't be reproduced in online sandbox testers, as they've got installed mbstring.
Must be checked in other php versions.

**Comment by derrabus** [comment]
See symfony/polyfill#329

**Comment by Yopai** [comment]
Hi @derrabus,
Sorry for not have seen there was a separate project for polyfill (in fact, when I started writing the issue I thought it was php8-related)

Still, is that normal that symfony code calls mb functions with null argument ? Would'nt it be worth changing these calls ?
https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
If I understood everything right, php8.1 will deprecate such calls, and enforce real string arguments on these functions.

**Comment by nicolas-grekas** [comment]
@Yopai you're right. Would you mind sending a PR to fix this, branch 4.4. Can you also check if there are more places in the codebase where this could happen and fix them?

**Comment by derrabus** [comment]
I agree, reopened. 😃

**Comment by Yopai** [comment]
I'll try to do that when I get some time.
Thanks !
