### ISSUE TITLE
conflict with AnnotationFileLoader and PHP8 attributes

### ISSUE THREAD

**Issue by nlhommet** [symfony/symfony#40225]
**Symfony version(s) affected**: 5.2.x

**PHP version**: 8.x

**Description**  
When an attribute has a parameter named class before the class declaration, the script tries to load the content of that parameter.

```
...
#[ParamConverter(
    'availability',
    class: Table\Availability::class,
    options: ['id' => 'ida']
)]
...
class EditController
{
...
```

**How to reproduce**  
See issue https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/713 for more detail

**Possible Solution**  
See here https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/713#issuecomment-780669307

**Comment by nicolas-grekas** [comment]
Could you please send a PR with some tests so that we can discuss the fix?
