### ISSUE TITLE
Allow framework.disallow_search_engine_index to be set as an env var

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#40220]
**Description**  
The `framework.disallow_search_engine_index` configuration does not currently accept an env var in its value. In our case this prevents us to use the same container image to be used in production and pre-production environments without modifications.

Currently we working around the problem setting the value to `true` in all the environments, decorating the listener with a custom one with an injected env var and doing an early return when the indexing is not disabled.

**Example**  
```yaml
framework:
  disallow_search_engine_index: '%env(bool:DISALLOW_SEARCH_INDEX)%'
```

**Comment by acantepie** [comment]
https://github.com/symfony/symfony/issues/38412

**Comment by Nyholm** [comment]
This is a duplicate of #38412 as @acantepie says. 

In that issue it says that `disallow_search_engine_index` does not support environment variables. I assume this is a feature request.

**Comment by alekitto** [comment]
> I assume this is a feature request.

Yes, it is. I saw that the `FrameworkExtension` does not resolve the env var on that configuration key, but a non-env container parameter is not an option in our use case as the pre-production and production are using the same container image with `APP_ENV` set to `prod` to test new features and bug fixes in a production-like environment.

**Comment by nicolas-grekas** [comment]
Closing as duplicate of #41704 (which is more recent but has some useful comments.)
