### ISSUE TITLE
[Translation] Overridden translations are not used

### ISSUE THREAD

**Issue by mikaelcom** [symfony/symfony#40226]
**Symfony version(s) affected**: 4.4.19

**Description**  
As indicated in this [comment ](https://github.com/symfony/symfony/commit/8389310983f821ca2fa58dd80cb18a7aa8211706#commitcomment-47234811), I can't override a Bundle translations using a file at `translations/{filename}`.

**How to reproduce**  
- Use Symfony components 4.4.19
- Require [SonataAdminBundle](https://github.com/sonata-project/SonataAdminBundle)
- Create the translation file `translations/SonataAdminBundle.fr.xlf`
- Add this translation for example:
```xml
            <trans-unit id="action_delete">
                <source>action_delete</source>
                <target></target>
            </trans-unit>
```
- Display a entity list with the action delete
- Delete button text is still `Supprimer` in French and not an empty text

**Possible Solution**  
Possible origin of the issue is detailed in this [comment ](https://github.com/symfony/symfony/commit/8389310983f821ca2fa58dd80cb18a7aa8211706#commitcomment-47234811)

**Comment by stof** [comment]
the commit on which you commented is **not** part of 4.4.19. It is precisely the commit fixing the bug, which will be part of the 4.4.20 (and 5.2.3) release at the end of the month.

**Comment by stof** [comment]
For reference, the bug affecting the 4.4.19 release was reported at https://github.com/symfony/symfony/issues/40014

**Comment by mikaelcom** [comment]
> the commit on which you commented is **not** part of 4.4.19. It is precisely the commit fixing the bug, which will be part of the 4.4.20 release at the end of the month.

Ok, I had upgraded to 5.2.3 when I first encountered the issue. Thanks for the quick reply!
