### ISSUE TITLE
Support for enums in existence checks

### ISSUE THREAD

**Issue by stof** [symfony/symfony#40232]
We have several places in the framework checking for existence of arbitrary class names, allowing classes, interfaces or traits (see https://github.com/symfony/symfony/pull/40140 for instance which adds such a usage, but I'm almost sure we have others elsewhere).
As PHP 8.1 will introduce the support of enums (the RFC has been accepted), these places should be updated to also check `enum_exists`

https://github.com/symfony/polyfill/issues/335 might help here to avoid checking for the availability of `enum_exists`|

**Comment by nicolas-grekas** [comment]
Do we really have to do anything here?
Enums are classes - `class_exists()` reports `true` for them.

```php

enum Suit {
  case Hearts;
  case Diamonds;
  case Clubs;
  case Spades;
}

echo (int) class_exists(Suit::class); // 1

echo new ReflectionClass(Suit::class); // works too
```

**Comment by stof** [comment]
hmm, I forgot that `class_exists` returns `true` for them (which is not consistent with the way interfaces and traits are handled there, while they are also special kind of classes in the engine and `new ReflectionClass(MyInterface::class)` works for them)

**Comment by stof** [comment]
@Crell is that inconsistency an intended design of the enum RFC or something forgotten ?

**Comment by Crell** [comment]
Effectively, enums are classes with slightly different syntax.  At runtime, they are classes and their enumerated values are objects.  The rest is just syntactic sugar.  `Suit::Clubs` will pass an `object` type check, for instance, and enums share the class namespace.

So, intended-ish.  Our general stance was "they're classes, so don't vary from what classes do/look like/work like unless there's a reason to."  So far no one offered a reason that `class_exists(Suit::class)` shouldn't return true.

**Comment by nicolas-grekas** [comment]
Thanks for the feedback. We can close then here 😊
