### ISSUE TITLE
translation for security cannot be overwritten 

### ISSUE THREAD

**Issue by axzx** [symfony/symfony#40236]
**Symfony version(s) affected**: 4.4.18, 4.4.19

**Description**  

In version 4.4.17 I overwritten the translation of the phrase `Username could not be found.` in the domain` security`.
In version 4.4.18 and 4.4.19, you cannot overwrite, the original translation appears. 

**How to reproduce**  
Create a file `translations/security.en.yaml` and insert the contents into it 
`Username could not be found.: 'The login or password is incorrect.'`

**Comment by xabbuh** [comment]
This has been fixed by #40116 and will be part of the next release.
