### ISSUE TITLE
Empty line starting with dash under "access_control" causes all rules to be skipped

### ISSUE THREAD

**Issue by rvdbogerd** [symfony/symfony#40235]
**Symfony version(s) affected**: 4.4.16

**Description**  
In my security.yaml, I had added a comment under the access_control entries. My editor automatically prepended the line with a dash, which I didn't notice. Suddenly my acceptance tests started failing and my application started to behave weirdly.

After hours of debugging and figuring out why the AccessListener wasn't throwing an AccessDenied exception anymore when logged out, I finally found the problematic line in the security.yml.

I think this is a big issue, because this tiny typo opened up my entire application to the public. I think there should be some kind of validation on the access_control lines, it should at least have an object with a path on the line, or something like that. See below for an easy reproduction:

**How to reproduce**  
```yaml
access_control:
    # This makes the logout route available during two-factor authentication, allows the user to cancel
    - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }

    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - # some comment about what is happening here
    - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
    - { path: ^/login_check, role: IS_AUTHENTICATED_FULLY }
    - { path: ^/admin, roles: ROLE_ADMIN_MENU }
    - { path: ^/support, roles: ROLE_NO_ACCESS }
    - { path: ^/bewind, role: ROLE_SOMEROLE }
    - { path: ^/(meldingen|profile), roles: ROLE_USER}
    - { path: ^/(?!login|logout|login_check|api), roles: ROLE_SOMEOTHERROLE }
 ```
If you now logout, the security listeners will not throw an access denied exception and will not redirect you to /login, therefore all security lines AFTER the comment will not be adhered to and are fully accessible by an anonymous user.

**Possible Solution**  
Validation on the access_control lines, it should at least contain an object with the "path" key (I guess?)

**Comment by monteiro** [comment]
The issue is here: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L217

Following @rvdbogerd idea, we can maybe throw an exception here if we find an empty array there?

To reproduce the issue:
- I cloned [symfony-demo](https://github.com/symfony/demo) and did the same as @rvdbogerd

```
    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - # some comment about what is happening here
        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }
```

In this specific case we have a voter, that verifies the roles, so it will not break security in this case.
But you can see the attributes he sets as valid following the `access_control`:

<img width="267" alt="Captura de ecrã 2021-02-23, às 09 10 20" src="https://user-images.githubusercontent.com/74459/108822782-76f27c00-75b7-11eb-8cd8-dafb276d15aa.png">


## Potential fix

In https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L217

```php
foreach ($config['access_control'] as $access) {
            $matcher = $this->createRequestMatcher(
                $container,
                $access['path'],
                $access['host'],
                $access['port'],
                $access['methods'],
                $access['ips']
            );

            $attributes = $access['roles'];
            if ($access['allow_if']) {
                $attributes[] = $this->createExpression($container, $access['allow_if']);
            }

            // added:
            if (count($attributes) === 0) {
                throw new InvalidConfigurationException('There is an empty access control set.');
            }

            $container->getDefinition('security.access_map')
                      ->addMethodCall('add', [$matcher, $attributes, $access['requires_channel']]);
        }
```

**Comment by monteiro** [comment]
Don't mind creating the PR, if we all agree on a possible solution and if there is something that needs to be fixed here.

**Comment by wouterj** [comment]
Yes, please create a PR :) (we always favor discussing changes on PRs rather than in issues). I think such a change makes sense.

Btw, in Symfony we always use `if (!$attributes)` instead of calling `count()` to check for empty arrays.

**Comment by monteiro** [comment]
@wouterj created the PR and a sample project to mimic the issue: https://github.com/symfony/symfony/pull/40330

**Comment by rvdbogerd** [comment]
Thanks @wouterj! Looks good to me

**Comment by rvdbogerd** [comment]
Thanks @monteiro! looks good to me
