### ISSUE TITLE
[http client]  Syntax error for ...

### ISSUE THREAD

**Issue by rpayanm** [symfony/symfony#40230]
**http client version(s) affected**: 5.2.0

**Description**  
I'm doing a request, for example to this URL:
`https://example.com/api/file/add?key=dke9gfu27fgvltkj4mws&name=test&server=https%3A%2F2Fc13.example.com%2Fflv%2Fapi%2Factions%2Ffile_uploader.php&server_id=20&file_name=1613614544gk9yf&folder_id=74341`
Method: `POST`
And I got this error:
```
Syntax error for "https://example.com/api/file/add?key=dke9gfu27fgvltkj4mws&name=test&server=https%3A%2F2Fc13.example.com%2Fflv%2Fapi%2Factions%2Ffile_uploader.php&server_id=20&file_name=1613614544gk9yf&folder_id=74341"
```
I tried with the same URL on Postman and works fine.

Of course, it is not example.com the domain, but even with this, it gives an error.

**Comment by nicolas-grekas** [comment]
Can you please provide a full reproducing script?
I don't reproduce (I get a 404)

**Comment by rpayanm** [comment]
I think the response is the problem, I was testing a little more, and the problem shows up in this code:
```
file: vendor/http-client/Response/CommonResponseTrait.php

try {
            $content = json_decode($content, true, 512, \JSON_BIGINT_AS_STRING | (\PHP_VERSION_ID >= 70300 ? \JSON_THROW_ON_ERROR : 0));
        } catch (\JsonException $e) {
--->        throw new JsonException($e->getMessage().sprintf(' for "%s".', $this->getInfo('url')), $e->getCode());
        }
```

When I call `$response->toArray();`.

How can I see the response content without using the `toArray()` function? I tried `json_encode($response)` without success, it shows me `{}`.

**Comment by nicolas-grekas** [comment]
Call getContent() instead.

**Comment by rpayanm** [comment]
Yes, the response is the problem:
`<br \/>\n<b>Notice<\/b>:  Undefined variable: newTags in <b>\/var\/www\/user\/data\/www\/site\/includes\/functions.php<\/b> on line <b>1277<\/b><br \/>\n{\"status\":200,\"msg\":\"OK\",\"result\":{\"file_code\":\"SHXMloJha3TH\",\"folder_id\":\"74341\"}}`

**Comment by rpayanm** [comment]
Thank you so much for the support. I am closing this.
