### ISSUE TITLE
[Serializer] Support for PHP 8.1 enums

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#40241]
**Description**  

https://wiki.php.net/rfc/enumerations#backed_enums

Backed enums have scalar equivalents. The Serializer should be able to normalize and denormalize such enums. 

**Example**  

```php
class Foo {
    public Suit $suit;
}

$foo = new Foo();
$foo->suit = Suit::Diamonds;
$serialized = $this->serializer->serialize($foo, 'json')
// expected: '{ "suit": "D" }'

$this->serializer->deserialize($serialized, Foo::class);
// expected: Foo->suit === Suit::Diamonds
```

Should pure enums (no scalar equivalent) be supported as well, by relying on the name property? (`Suit::Spades->name`)

**Comment by stof** [comment]
IMO, only backed enums should be supported by default.

If you want to use a pure enum while still serializing it, requiring a custom normalizer seems better to me. The name property is specifically meant as a debugging tool in the Enum RFC. Exposing it in your API looks wrong to me.

**Comment by stof** [comment]
regarding the implementation, this should be done by building a `BackedEnumNormalizer`

**Comment by Neirda24** [comment]
But enums can also implement Interfaces and expose public functions maybe in the ObjectNormalizer ?

**Comment by ogizanagi** [comment]
@Neirda24 : Hmm. 🤔  We might leverage #39399 to choose between serializing the enum as its simple scalar equivalent, or whether to serialize it as an object with serialized methods.
To me, the scalar normalization by `BackedEnumNormalizer` should be the default, but could be opt-out with the context to let the ObjectNormalizer do its job.

**Comment by stof** [comment]
@Neirda24 the `BackedEnumNormalizer` normalizer should be registered with a low priority, so that registering a custom normalizer can override the normalization easily.

**Comment by Neirda24** [comment]
@stof : sure. I was talking about the public methods that can automagically be serialized when serializing an object. I agree that enums should be kept simple objects. But this could be a use case as the gap between enums and objects is quite thin. Just making sure to explictly says that BackedEnum is not treated as other objects and will by default only dump the current value.

**Comment by stof** [comment]
Only one normalizer will run (the first supporting the type)

**Comment by rzeczkowskip** [comment]
I might try to write the normalizer if You choose me ;)

I think that public methods shouldn't be serialized automatically. It's custom normalizer's job.

**Comment by derrabus** [comment]
I guess we need to wait for php/php-src#6489 to be merged first. :-)

**Comment by rzeczkowskip** [comment]
Yes. I'm just can't wait for enums and offer my help asap

**Comment by iluuu1994** [comment]
> I guess we need to wait for php/php-src#6489 to be merged first. :-)

Done!
