### ISSUE TITLE
symfony phpunit bridge installing phpunit dependencies to bin/.phpunit folder

### ISSUE THREAD

**Issue by bogdan-dubyk** [symfony/symfony#40252]
Hey, I do not create a bug report because I'm not sure it's a bug and maybe it's expected behaviour. When I install `symfony/phpunit-bridge` package and run `vedor/bin phpunit tests/` by the first time, I see message like "No composer.json found in the current directory, showing available packages from packagist.org" and brirdge installing phpunit directly to `bin` folder  not to the `vendor` folder. And at the end it leads to few issues: 

- IDE do not see phpunit dependencies and you need manually tell that not all dependencies is in vendor folder
- also in project I'm running linters when commiting some changes to git, and `phpstan`, one of linterers I use showing error, because it also see unexisting phpunit dependencies in the code

So it's a bit weird to see some dependencies not in the vendor folder (as vendor folder is a standard place to store all the project dependencies), and for me it's easier to not user bridge at all instead of making workarounds to make it work with IDE or other packages like `phpstan`. 

Is it a bug, can I use the bridge and have phpunit installed in the vendor folder?

**Comment by stephen-lewis** [comment]
I believe this is expected behaviour. I don't fully know or understand the specifics, but I think it has something to do with preventing conflicts with a pure phpunit install (as installed to vendor/).

**Comment by scriptibus** [comment]
The phpstan error can be avoided including the bootstrap file to our phpstan config. 

```
parameters:
    bootstrapFiles:
        - bin/.phpunit/phpunit/vendor/autoload.php
```

**Comment by nicolas-grekas** [comment]
The default recipe and test-pack have changed, this should have fixed this issue.
