### ISSUE TITLE
102 response code doesn't return to the client

### ISSUE THREAD

**Issue by Daisuke-sama** [symfony/symfony#40255]
**Symfony version(s) affected**: 5.2.3

**Description**  
In my project requirements, I am implementing a simple rest api (without any extra bundle, lib, platform) and returning the JsonResponse from the HttpFoundation. The required response code is 102 (Processing — httpstatuses.com - Status Codes). Not 200 or 100 or any other. And when I call for that controller the entire system hangs! Always hangs. Like the script is still processing. But the actual state of the script is finished. Why? I went through it with xdebug and dumped it from the code. And the termination finishes, script exits, but the client is still waiting for the response.
Note: it works well with any code, or shows in the wrong case the correct message, like “The HTTP status code “100500" is not valid.”
Any thoughts, guys?

**How to reproduce**  
in the controller
```php
return $this->json($result, 102);
```

**Possible Solution**  
I am not sure that this is framework-related, please, share your thoughts.

**Additional context**  
running php7.4, server integrated into the PHP with symfony serve.

**Comment by nicolas-grekas** [comment]
1xx status code cannot be used as final status codes. They are informational status that can be sent before a final status is reached.
From the spec: "The server MUST send a final response after the request has been completed."
