### ISSUE TITLE
Invalid version dependence

### ISSUE THREAD

**Issue by smile1980** [symfony/symfony#40263]
**Symfony version(s) affected**: 4.4.19

**Description**  
Invalid version dependence with symfony/console 4.4.9 + symfony/translation 4.4.19 + php7.4

Error:
"Compile Error: Type of Symfony\Component\Translation\Command\XliffLintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)"

Property type is required in Symfony\Component\Console\Command\Command::$defaulName

**How to reproduce**  
Install indicated versions of components

**Possible Solution**  
Check and change dependency versions PHP. Or modify in class XliffLintCommand:
FROM: protected static $defaultName = 'lint:xliff';
TO: protected static string $defaultName = 'lint:xliff';

**Comment by xabbuh** [comment]
Are you sure that you really use 4.4.19 of both components? There is no type declaration in neither of these class (see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/Command/XliffLintCommand.php#L33 and https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Console/Command/Command.php#L35).

**Comment by smile1980** [comment]
# composer info
symfony/console                      v4.4.19            Eases the creation of beautiful and testable command line interfaces
symfony/translation                  v4.4.19            Provides tools to internationalize your application

Analogue problem in all components with Command:

 Compile Error: Type of Symfony\Component\Yaml\Command\LintCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)

Compile Error: Type of Symfony\Bridge\Monolog\Command\ServerLogCommand::$defaultName must be string (as in class Symfony\Component\Console\Command\Command)

**Comment by smile1980** [comment]
I'm delete vendor folder and reinstall composer packages. No mistake.
