### ISSUE TITLE
Incorrect generation CSRF token

### ISSUE THREAD

**Issue by StasToken** [symfony/symfony#40265]
**Symfony version(s) affected**: 5.2.2

**Description**  
Incorrect generation CSRF token
**How to reproduce**  
Register by [this instruction ](https://symfony.com/doc/current/security/form_login_setup.html)
As a login form, follow the rules symfony 
_src/Form/LoginType.php_

```php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class LoginType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('email',null,array('label' => false,'attr' => ['class' => 'register-form-input','autocomplete' => 'off']));
        $builder->add('password',PasswordType::class,array('label' => false,'attr' => ['class' => 'register-form-input','autocomplete' => 'off']));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}
```

_TWIG_

```twig
                    {{ form_start(login_form) }}
                    <b>Email:</b><br />
                    {{ form_row(login_form.email) }}
                    <b>Password:</b><br />
                    {{ form_row(login_form.password) }}
                    <div class="text-center"><button type="submit" class="site-btn">ENTER</button></div>
                    {{ form_row(login_form._token) }}
                    {{ form_end(login_form) }}
```

**Possible Solution**  
I was poking around for a long time, but besides, how to do it incorrectly (not to use standard forms symfony I didn't think of anything) 

**Additional context**  
In general, I made the login form according to the instructions, I decided to make the form itself as a standard component, when I send the form I constantly get an error: **Invalid CSRF token**

After a long trial, I realized that the forms are generated by the wrong one CSRF token...

Example: 

```twig
                    {{ form_row(login_form._token) }}
                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >
```

I added an example to twig as written in the recipe and for comparison CSRF token which the form itself generates 
html output 

```html
<input type="hidden" name="_csrf_token" value="Xtnmxi4Pn_N95067wjxYEMh3t7vhf4FiPJCxYNUnWqA">
<input type="hidden" id="login__token" name="login[_token]" value="ZtVwBzXtPbbnZp-5D4RysR7eDDt1z3Tr5WvBCv7C1VU" /></form>
```

You can observe that the tokens that are generated for the same form are different, which causes a validation error. 
I asked a question on [other resources](https://qna.habr.com/q/942737), until I managed to find out that I'm not the only one facing this problem. 

_> "Also came across, I could not find a solution. As a result, also - 2 tokens, one native and one manual."_ 

I would like to get an official answer from the developers, how to live with this is not clear, it looks more like some kind of inconsistency of components in the code ...

**Comment by derrabus** [comment]
I'm sorry, but I don't really understand this bug report. Can you please do the following?

* Create a small Symfony app that I can run to reproduce your problem.
* Describe the incorrect behavior that you observe.
* Describe the behavior that you would have expected instead.

**Comment by StasToken** [comment]
Hello! [https://github.com/StasToken/bugdemo](https://github.com/StasToken/bugdemo) 
`git clone https://github.com/StasToken/bugdemo.git`
and
`composer install`
master contains a ready-made example with an error, in order to help you understand, I made 3 demo branches
_You can always switch to the master branch to see the end result of the problem...._

Please note that the project already has a demo user

- Login: demo@example.com 
- Password: 123456 

Switch to the step-1 branch
`git checkout origin/step-1`
Start your local server: php -S localhost:8000
Go to the page http://localhost:8000/login
Log in:

- Login: demo@example.com
- Password: 123456

You should see the "Welcome" messages!
Pay attention to what the file looks like now
`./templates/security/login.html.twig `

Log out by going to: http://localhost:8000/logout

Switch to the step-2 branch
`git checkout origin/step-2`

Please note that the login form is now designed according to the rules via the form object
`./src/Form/LoginType.php `
And the template itself now has a different look
`./templates/security/login.html.twig`
It was also changed. 
`/src/Controller/SecurityController.php`
Please note that I took into account the fact that the form with the csrf token is now called differently ( in the file 
`./src/Security/LoginFormAuthenticator.php` ) the lines were replaced
`bin/console cache:clear`

Go to the authorization page
http://localhost:8000/login
Log in:

- Login: demo@example.com
- Password: 123456

You will get the **Invalid CSRF token error**. This error occurs in this condition as I understand it…

I tried for a long time to understand what is going on, and I realized that the CSRF tokens that are generated in the example and the token that is generated by the form itself are different... go to the step-3 branch
`git checkout origin/step-3`
`bin/console cache:clear`
 http://localhost:8000/login → CTRL+F5 
Note how the file
`./templates/security/login.html.twig` has changed
For the demonstration, I added 2 CSRF tokens, one from the documentation example and the second generated by the form. Please view the html source code in the browser for the page
http://localhost:8000/login
You will see that the tokens do not match, which is why authorization via standard forms does not work. But why?


```
<input type="hidden" name="_csrf_token" value="Y3BQASoBQ9uNsxVPoXu-fZ0FLgH7BJE0z8LrQW4a9IM">
<div class="text-center"><button type="submit" class="site-btn">Sign in</button></div>
<input type="hidden" id="login__token" name="login[_token]" value="k7IgVbFXHuTVAh87c2YytA0FI5eRDw8GL11oj8w2G1M" />
```

**Comment by wouterj** [comment]
CSRF tokens are created based on a CSRF token id. A CSRF with another token id will never match other token ids.

In your Twig code, you're using `authenticate` as the token id. The form CSRF extension defaults to the form name as token id: https://github.com/symfony/symfony/blob/858dca485d267fa8bc7592d1471e78517d802c3f/src/Symfony/Component/Form/Extension/Csrf/Type/FormTypeCsrfExtension.php#L60 So they will indeed never match.

Btw, if you're using the Form component with CSRF integration, the CSRF token is already validated by the form. There is no need to pass the generate CSRF token to the security component for validation.

To conclude, I don't see anything unexpectedly here. If you need help setting up login with the form component, please use any of the support channels mentioned on https://symfony.com/support (e.g. StackOverflow or Slack). If there is a bug, feel free to comment, we can always reopen issues :)

**Comment by StasToken** [comment]
Hmm, I didn't really understand, but I can somehow then tell the standard form which authenticate to use for login forms?
PS: I have already asked this question [here](https://qna.habr.com/q/942737?e=10841753) - But I didn't get any help there... 

Can you then tell me how best to do it right now so that it doesn't look like a crutch?

**Comment by stof** [comment]
@wouterj the issue here is that the Form component is used only for the rendering of the form, not for the processing, as the form is submitted to the firewall.

**Comment by StasToken** [comment]
That is, you also can not say how to do it in a human way?

**Comment by wouterj** [comment]
Ah, good catch @stof. In that case, make sure you set the `csrf_token_id` form option to match the token ID that is used in your `LoginFormAuthenticator`.

>  PS: I have already asked this question here - But I didn't get any help there...

From a quick google translate, I see you asked it yesterday. Please be a bit more patient, everyone is doing this in their free time. If you need paid support, that's also available (see the right side of the support page I referenced in my previous comment).
