### ISSUE TITLE
Overwriting translations of bundles does not work

### ISSUE THREAD

**Issue by sormes** [symfony/symfony#40264]
**Symfony version(s) affected**: 4.4.19

**Description**  

Overwriting translations of bundles does not work

**How to reproduce**  

try override translation from bundle in app.

more info in https://github.com/sonata-project/SonataAdminBundle/issues/6881

**Possible Solution**  

I don't know exactly why it is sorted by name here. But this is where the order of the files changes.
https://github.com/symfony/framework-bundle/blob/4.4/DependencyInjection/FrameworkExtension.php#L1248

**Additional context**  

This has arisen from this other issue in sonata project

https://github.com/sonata-project/SonataAdminBundle/issues/6881

**Comment by wouterj** [comment]
Hi! Thanks for creating a bug report. However, this bug has been reported multiple times already and is now fixed in the 4.4.x. See https://github.com/symfony/symfony/issues/40014 for the original bug report. You can revert back to 4.4.18 and wait for a 4.4.20 release to work around this bug.

**Comment by sormes** [comment]
@wouterj 

Thanks  and sorry I have only searched the open issues. My fault . ^^
