### ISSUE TITLE
Deprecated function libxml_disable_entity_loader() in PHP 8.X

### ISSUE THREAD

**Issue by jonny827** [symfony/symfony#40277]
**Symfony version(s) affected**: x.y.z
Symfony version 5.2.3 but affects all versions using PHP 8.X I believe

**Description**
Received error in profiler about deprecated function.

Function libxml_disable_entity_loader() is deprecated    

Trace:
vendor\symfony\dependency-injection\Loader\XmlFileLoader.php line 630
vendor\symfony\config\Util\XmlUtils.php line 89

**How to reproduce**
I have Symfony 5.2.3, PHP 8.0.2, and Apache 2.4.46 64-bit and running locally on Windows 10.

**Possible Solution**
No longer needed according to [https://www.php.net/manual/en/migration80.deprecated.php](https://www.php.net/manual/en/migration80.deprecated.php)

**Additional context**

**Comment by jderusse** [comment]
Symfony calls the `libxml_disable_entity_loader` method ONLY if something else disabled the `entity_load` before.

Could you please provide a reproducer?

**Comment by jonny827** [comment]
I am unable to provide one.  I do not remember how I resolved the error. I think I may have disabled part of the application but have written too much code to remember the details. I can update if issue comes back.  I thought you would want to know about the deprecated function or I would have written more details \about why it was even called in the first place when the issue was fresh.

**Comment by garak** [comment]
I'm getting same problem with a travis run. See https://travis-ci.org/github/liuggio/fastest/jobs/760430242

**Comment by stof** [comment]
@garak you are getting that in a `--prefer-lowest` job installing 4.4.0. That's a release before the fix was done in Symfony. A `--prefer-lowest` job should not forbid hitting deprecations.

**Comment by garak** [comment]
You're right @stof, but even forcing symfony/config 4.4.12 I'm hitting deprecation (despite such version claims to fix it). See https://travis-ci.org/github/liuggio/fastest/jobs/760436759

**Comment by jonny827** [comment]
Why was this closed? The function is deprecated for PHP 8.x, would that not then require a patch to support PHP 8.x?

**Comment by garak** [comment]
@jonny827 because it's already patched. You just need to use a more recent version of Symfony.

**Comment by TheDevilOnLine** [comment]
The issue still seems to happen with latest stable: Symfony 5.3.4.

`Deprecated: Function libxml_disable_entity_loader() is deprecated in <symfony project path>\vendor\symfony\dependency-injection\Loader\XmlFileLoader.php on line 657`
`Deprecated: Function libxml_disable_entity_loader() is deprecated in <symfony project path>\vendor\symfony\dependency-injection\Loader\XmlFileLoader.php on line 659`

https://www.php.net/manual/en/migration80.deprecated.php mentions that if the function is really needed (which is only the case when LIBXML_NOENT is used) "it is recommended to refactor the code using libxml_set_external_entity_loader() to suppress loading of external entities."

**Comment by jderusse** [comment]
same comment: https://github.com/symfony/symfony/issues/40277#issuecomment-784124226

**Comment by TheDevilOnLine** [comment]
The shortest path to reproduce for me is the following.

Execute the following commands:
```
symfony new symfony-deprecated
cd symfony-deprecated
composer req phpunit doctrine ormfixtures
```

Edit `.env`, set `DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"`

Create file `tests/DatabasePrimer.php` with contents

```
<?php
declare(strict_types=1);
namespace App\Tests;

use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;
use Symfony\Component\HttpKernel\KernelInterface;

class DatabasePrimer
{
    public static function prime(KernelInterface $kernel):void
    {
        // Make sure we are in the test environment
        if ('test' !== $kernel->getEnvironment()) {
            throw new \LogicException('Primer must be executed in the test environment');
        }

        // Get the entity manager from the service container
        $entityManager = $kernel->getContainer()->get('doctrine.orm.entity_manager');

        // Run the schema update tool using our entity metadata
        $metadata = $entityManager->getMetadataFactory()->getAllMetadata();
        $schemaTool = new SchemaTool($entityManager);
        $schemaTool->updateSchema($metadata);

        // Run Doctrine Fixtures Bundle
        $application = new Application($kernel);
        $command = $application->find("doctrine:fixtures:load");

        $commandTester = new CommandTester($command);
        $commandTester->execute(['--append' => true]);
    }
}

```

Create file `tests/DatabaseTest.php` with contents

```
<?php
declare(strict_types=1);
namespace App\Tests;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class DatabaseTest extends KernelTestCase {

    protected ?EntityManagerInterface $entityManager;

    function setUp(): void
    {
        $kernel = $this->bootKernel();
        DatabasePrimer::prime($kernel);

        $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();

        parent::setUp();
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        $this->entityManager->close();
        $this->entityManager = null;
    }


    public function testTemporary() : void {
        $this->assertTrue(true);
    }
}
```

Run `symfony php vendor/bin/phpunit`

My `php -v` reports the following:
```
PHP 8.0.8 (cli) (built: Jun 29 2021 16:03:59) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by TheDevilOnLine** [comment]
> Symfony calls the `libxml_disable_entity_loader` method ONLY if something else disabled the `entity_load` before.

Even if this is the case, Symfony shouldn't call `libxml_disable_entity_loader` but should use `libxml_set_external_entity_loader` instead

**Comment by jderusse** [comment]
I followed your reproducer, but no deprecation is triggered.
```
php -v
PHP 8.0.9 (cli) (built: Jul 30 2021 13:09:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.62.0~linux-x64-non_zts80, https://blackfire.io, by Blackfire
```

```
symfony php vendor/bin/phpunit
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.

Testing 
.                                                                   1 / 1 (100%)

Time: 00:00.116, Memory: 18.00 MB

OK (1 test, 1 assertion)
```

If your code reached `dendency-injection\Loader\XmlFileLoader.php on line 657`, it means Symfony has detected that the entityLoader has been disabled by something else before. This is not the case for your reproducer. I suspect you have another dependency or a PHP extension that did it.

> Even if this is the case, Symfony shouldn't call libxml_disable_entity_loader but should use libxml_set_external_entity_loader instead

If you have a better solution, PR is welcome
