### ISSUE TITLE
Form error badge background not displaying

### ISSUE THREAD

**Issue by noe-ts** [symfony/symfony#40279]
**Symfony version(s) affected**: 5

**Description**
With bootstrap 5, the class for form error badges is now ```.badge bg-danger``` instead of ```.badge badge-danger```

Bootstrap 4 :
![with bg](https://user-images.githubusercontent.com/71312608/108851948-4cb7b300-75e5-11eb-9983-f45d5b332e20.PNG)

Bootstrap 5 :
![no bg](https://user-images.githubusercontent.com/71312608/108851965-504b3a00-75e5-11eb-9297-23e55633ddcd.PNG)

**Quick fix :**
```
.badge-danger{
  background-color: #dc3545;
}
```

**Comment by noniagriconomie** [comment]
related to https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
maybe you have to create one for bootstrap5 and thus include this one instead of the symfony one

**Comment by Nyholm** [comment]
Thank you for this issue and the quickfix. 

Correct. There is no official bootstrap 5 support yet.

**Comment by xabbuh** [comment]
I am going to close here as there is nothing to fix in the currently available themes. Thank you for understanding.
