### ISSUE TITLE
Submitting UUIDs as EnityType fails for uppercase

### ISSUE THREAD

**Issue by mgluesenkamp** [symfony/symfony#40295]
**Symfony version(s) affected:** 5.2.1 with symfony/form

**Description:**
Hi, I found a problem in submitting of UUIDs as EntityType. I've got the following setup:

- I use a UUID as primary key for a entity A
- The FormType of an other entity B references by the EntityType form type to this entity A
- If I send data (for example JSON) with a valid UUID in lowercase, the new object of B with reference to an object of A is created successfully
- If I send data with a valid UUID in uppercase, I get an error: `This value is not valid.`

**How to reproduce:**
See above.

**Possible solution:**
I found out that the problem can be solved by changing `Symfony\Bridge\Doctrine\Form\ChoiceList\DoctrineChoiceLoader`. In line 109 and 110 the objects of the database are filled in the object array. The ID of the array is in uppercase (it comes from the request) but the ID of the database is lowercase (it's generated by Doctrine and come from the database). So there IDs are different for PHP.
So it would be possible to change the code like this:

    foreach ($values as $i => $id) {
        if (isset($objectsById[strtolower($id)])) {
            $objects[$i] = $objectsById[strtolower($id)];
        }
    }

**Comment by stof** [comment]
If you want to accept case insensitive values for the submitted data, I suggest you to add a form listener lowercasing the submitted data on `PRE_SUBMIT`.

Adding this `strtolower` in the DoctrineChoiceLoader itself does not make sense. Choice values in the `ChoiceList` API are not case insensitive.

**Comment by mgluesenkamp** [comment]
Ok, my solution would not fix the problem.
But UUIDs are defined to be case insensitive in input. So I think that the doctrine bridge should work for all valid UUIDs and not only the lower cased. What's your opinion?

**Comment by nicolas-grekas** [comment]
I agree with @stof, you should normalize your input.
