### ISSUE TITLE
[FrameworkBundle] ide configuration via xdebug.file_link_format adds redundant slash

### ISSUE THREAD

**Issue by markwatney2016** [symfony/symfony#40292]
**Symfony version(s) affected**: 4.4.16

**Description**

Setting the `framework.ide` configuration via `xdebug.file_link_format` (recommended on https://symfony.com/doc/current/reference/configuration/framework.html#ide) adds a redundant slash at the beginning of the file path. This prevents e.g. PhpStorm zu open the particular file.

**How to reproduce**

1. Set this configuration in `php.ini` file:

`xdebug.file_link_format="phpstorm://open?url=file:%f&line=%l"`

2. Klick e.g. on the link to the Controller class in Symfony's toolbar.

**Comment by Nyholm** [comment]
Thank you for reporting this. Im not sure about the redundant slash. But you are correct that the `php.ini` settings in the docs does not work. 

```
# My current php.ini setting
xdebug.file_link_format="phpstorm://open?file=%f&line=%l"
phpstorm://open?file=/Users/tobias/Workspace/PHPStorm/project/src/Controller/StartpageController.php&line=15

# Docs example (does not work)
xdebug.file_link_format="phpstorm://open?url=file:%f&line=%l"
phpstorm://open?url=file:/Users/tobias/Workspace/PHPStorm/project/src/Controller/StartpageController.php&line=15
```

The docs are correct but it does not clearly show the format to use for PHPStorm. I've updated the docs in this PR: https://github.com/symfony/symfony-docs/pull/15025

**Comment by Nyholm** [comment]
Closed by https://github.com/symfony/symfony-docs/pull/15025
