### ISSUE TITLE
PdoSessionHandler::buildDsnFromUrl not compatible with Doctrine Connection URL

### ISSUE THREAD

**Issue by bcremer** [symfony/symfony#40290]
**Symfony version(s) affected**: All Versions
**Description**
The Connection URL support in `PdoSessionHandler` does not support the `unix_socket` connection options like the doctrine connection factory does.

**How to reproduce**

`.env`

````
DATABASE_URL=mysql://myusername:mypassword@localhost/mydb?unix_socket=/run/proxysql/proxysql.sock
````

`config/packages/doctrine.yaml`
```yaml
doctrine:
  dbal:
    driver:   "pdo_mysql"
    url: '%env(resolve:DATABASE_URL)%'
```

`config/services.yaml`
```yaml
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
      - { db_table: 'Session' }
```

The doctrine connection and components direly using the PDO Connection will work. Setup of the Session Handler will fail because the unix_socket part will be discarded.

**Possible Solution**
Add support for `unix_socket` in [PdoSessionHandler::buildDsnFromUrl](
https://github.com/symfony/http-foundation/blob/933b4cba7ab9abdb2472c406c433f3f78e3f9bbd/Session/Storage/Handler/PdoSessionHandler.php#L492)

Would you accept a PR adding `unix_socket` support to `buildDsnFromUrl`?

**Comment by Nyholm** [comment]
The `DATABASE_URL` you pass to `PdoSessionHandler` will be rebuilt to a "pdo DSN" in `PdoSessionHandler::buildDsnFromUrl()`. That will then be passed as a first argument to `new \PDO()`. For mysql there are an option for `unix_socket` as described [in the manual](https://www.php.net/manual/en/ref.pdo-mysql.connection.php). 

I think it make sense to add that, yes. But the manual also says that it "shouldn't be used with host or port". 

Feel free to submit a PR to include this new feature.
