### ISSUE TITLE
[ExpressionLanguage] Arrow functions

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#40326]
**Description**
It would be good if expression language allows arrow functions, just like Twig do.

**Example**
Example use-case: If expression language is used as business engine rule and user needs to define condition like following 

# Promote article to the homepage when
`count(filter(article.comments, (comment) => not comment.spam)) > 100 and not contains(article.categories, (category) => category in ["misc"])`

**Comment by wouterj** [comment]
Hi @Warxcell! Thanks for your proposal.

However, I'm personally -1 on this proposal. The scope of expression language is deliberately kept very small. There is no need for yet another programming language. Imho, ExpressionLanguage's scope is to have a safe sub-language, that can be written and understood by non-developers (and as such, should be small enough to make it safe to run expressions defined by non-developers).

**Comment by fabpot** [comment]
I agree with @wouterj, that's out of the scope of ExpressionLanguage.

**Comment by Warxcell** [comment]
At least make it extendable, so anyone can add this after-market?

**Comment by hafezdivandari** [comment]
Hi @Warxcell Could you find any solution/workaround for this?

**Comment by Warxcell** [comment]
> Hi @Warxcell Could you find any solution/workaround for this?

https://github.com/Warxcell/expression-language-arrowfunc
