### ISSUE TITLE
[LOCK] - The lock component fails under PCNTL. Better docs needed.

### ISSUE THREAD

**Issue by twisted1919** [symfony/symfony#40325]
**Symfony version(s) affected**: ALL

**Description**
When using the Lock component under a regular scenario, it works just fine because the lock is, by default, released when the lock instance is destroyed.  
Things get interesting, however, when using the lock component under PCNTL.  
I believe that, because of the way PCNTL works, the locks are released when the first child process finishes, thus future access to the resources by other processes is allowed while it shouldn't.

**How to reproduce**
Given following code:  
```php
<?php 

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Lock\Exception\LockAcquiringException;
use Symfony\Component\Lock\Exception\LockConflictedException;
use Symfony\Component\Lock\Exception\LockReleasingException;
use Symfony\Component\Lock\Lock;
use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\Store\FlockStore;

$factory = new LockFactory(new FlockStore('/tmp/lock/data'));
$lock = $factory->createLock(__FILE__, 86400, true);

echo 'Acquiring lock...' . PHP_EOL;

if ($lock->isAcquired()) {
	exit('Lock acquired already...' . PHP_EOL);
}

if (!$lock->acquire()) {
	exit('Cannot acquire lock!' . PHP_EOL);
}

echo 'Lock acquired!' . PHP_EOL;

process();

$lock->release();
exit('Lock released...' . PHP_EOL);
```

If the `process` function is just:  
```php 
function process() {
	sleep(30);
}
```
And we run the above script from two terminal sessions, we can see that we cannot access the resources from the second terminal till the first one finishes. This is the expected behavior.   
When PCNTL is involved, and `process` becomes:  
```php

function process() {
	$children = [];
    for ($i = 1; $i <= 10; $i++) {

        $pid = pcntl_fork();
        if ($pid == -1) {
            continue;
        }

        // Parent
        if ($pid) {
            $children[] = $pid;
        }

        // Child
        if (!$pid) {
        	echo 'Child #' . $i . ' started working!' . PHP_EOL;
            sleep(rand(0, 30));
            exit('Child #' . $i . ' finished!' . PHP_EOL);
        }
    }

    while (count($children) > 0) {
        foreach ($children as $key => $pid) {
            $res = pcntl_waitpid($pid, $status, WNOHANG);
            if ($res == -1 || $res > 0) {
                unset($children[$key]);
            }
        }
        usleep(100000);
    }
}
```
If we start the process in a terminal, then in the second one we run it several times, eventually we will start processing in the same terminal as well, this is because one of the processes from the first terminal released the lock. 

This is of course an unexpected behavior.  If you read that far I believe you figured out by now that the solution is to not auto-release the lock, because otherwise, as I said, one of the processes will do it prematurely.

**Possible Solution**
Update the documentation to specify this behavior under PCNTL. I was caught a bit off-guard by it, I am sure others will as well.  

**Additional context**
I currently don't use the framework, just this component.

**Comment by jderusse** [comment]
Hello, 

I believe this is because of auto-release.

Technically, the lock is not released on "instance destroyed", it is release when the method `release` is called, and this method is automatically called on variable destruct, unless you disable auto-release.
(well, flock and semaphore are also release by the kernel on process destroy, but given the main is still alive, I believe this should not happen in your case)

Try passing `false` as 3rd argument to the factory::createLock` method

**Comment by twisted1919** [comment]
@jderusse - Yes, that's what i also pointed out as well above:
> If you read that far I believe you figured out by now that the solution is to not auto-release the lock, because otherwise, as I said, one of the processes will do it prematurely. 

Maybe just update the docs to explain this behavior, since it isn't really specified anywhere and people could get issues because of it?

**Comment by jderusse** [comment]
Yeah undead, documentation could be improved. UP for a pull request ?

**Comment by Nyholm** [comment]
I agree with both of you. It is not related to PCNTL. The issue can be solved with some improved documentation about auto-release. 

@twisted1919, do you want to make a PR to the docs or are you happy with just writing this issue? (Either is fine)

**Comment by stof** [comment]
Well, the relation to pcntl is that forking the process with pcntl brings you in a case where a lock key is shared between multiple PHP processes/threads. And any kind of key sharing is incompatible with auto-releasing (that also applies when using the advanced mode of the lock component to pass a Key object to another process)

**Comment by twisted1919** [comment]
@Nyholm - I personally have almost zero experience with symfony and the pull request process here, so i'll skip doing the pull request, sorry.

**Comment by Nyholm** [comment]
No worries. 
I'll make a PR to the docs. I'll ping you for a review. If you are able to have a look that would be great.
