### ISSUE TITLE
[Console] Initiative: rework the console component

### ISSUE THREAD

**Issue by dbrekelmans** [symfony/symfony#40320]
**Description**
The console component is widely used and loved by many.
It does a lot of work and makes adding console commands quite easy for developers if you stick to the documentation.

However, if you want to do some more niche things with commands, you start running into problems.
The initial commit is from 2010, making this component 11 years old already.
Given the recent rework of the security component, I propose a similar initiative for the console component.

I would love to hear the opinion of the symfony core team on this topic.
If you are in favor of a rework, maybe we can put together a working group and discuss the direction this should take.
Of course we have to consider backwards compatibility, clear updated documentation and an easy upgrade path.

With the experience of the security component rework, I would love to get input from @wouterj and @weaverryan 

Related: https://github.com/symfony/symfony/issues/34907#issuecomment-563932422

**Comment by wouterj** [comment]
Age is not a good reason to rebuild something completely. Especially for components that are used as much as the Console component, rewriting something from the ground up has a massive impact on the PHP ecosystem. As such, I consider rewriting Console almost a no-go.

That said, if there is a real scenario that doesn't yet work with Console component, it's good to tackle that specific issue. Rebuilding Security was never the goal, the goal was improving the Guard interface and making sure internals was using Guards. The means to achieve that goal was a rewrite of the authentication manager.

I do not understand the use-cases in  #34907. Or more specifically: instead of decoration, can't these usecases be fixed by using the console events? Note that current Console component is quite flexible. E.g. Behat has implemented its own "cli controller" concept on top of the Console component: https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Cli/Command.php

**Comment by jkufner** [comment]
For a library, being 11 years old is a mark of quality.

**Comment by dbrekelmans** [comment]
Sorry I was not clear in my description.

Age is not the argument I want to present for reworking the component. I merely mentioned it to indicate the component might not have kept up with newer Symfony features (like decorating) and does not leverage newer and better tools (like the String component).

With "rework", I also do not mean a complete rewrite of the component. The base of the component is very solid. What I mean is that certain improvements can be made that will make it less coupled and easier to modify to the user's needs (without breaking contract).

Examples include:
- Adding an interface to the Command class
- Decouple from symfony magic (like adding a help option)
- Utilize String component to better deal with emojis and non-latin characters

It seems unnecessary and restricting to have to extend a 657-line Command class in order to add a command to your console application. Implementing an interface should be all that's needed to add a command to your console application. Maybe you don't want to have to use all the code inside to Command class.

The reason I suggest a "rework" initiative, is because previous PRs and Issues have been shut down due to the high impact they would have. Maybe a consolidated "rework" with a good upgrade-path and thought-out backwards-compatibility may overcome this.

**Comment by Nyholm** [comment]
> Maybe a consolidated "rework" with a good upgrade-path and thought-out backwards-compatibility may overcome this.

That is always a requirement for any changes =)

Im happy to rewrite things and do all kinds of changes. Age or popularity should not matter. But every change should always be carefully considered if the win is larger than the negative impact. (This is also always a requirement, no matter component.) 

Feel free to open issue to discuss the features you want to include, Ie to support emojis non-latin characters etc.

**Comment by wouterj** [comment]
In open source communities, it's often hard to judge whether a change is needed or not. Please show some real life problems and proposed fixes when you propose a change (such like this one). That makes it easier to judge whether changes are needed.

For now, and forgive me to be a bit holding back here, I see mostly ideological arguments for change (I've never found a problem with extending the - somewhat large - `Command` class in my applications). Imho, ideological ideas are not worth changing a component that has such a large popularity.

On the other hand, "Utilize String component to better deal with emojis and non-latin characters" seems like a real use-case. In my opinion, this continues the work that has been put on true color support in the 5.2 console component. Making sure Console can deal with special characters/emojis can be great 5.x feature (that is, I don't know what the current problems are with emojis in the Console component and if String can fix those, but that's worth a more specialized issue).

**Comment by dbrekelmans** [comment]
Fair enough. Thanks for the feedback.

Reading existing (some closed) issues, I sensed a reluctance to change regarding the console component.
My motivation in opening this issue was to see if there's some way to work around that.

Your reactions indicate that the reluctance was not to do with the console component, but rather a lack of substantiation in the issues at hand.
Adding use-cases and extra motivation to existing and new issue descriptions seems like an easy fix.

Thanks 👍

**Comment by wouterj** [comment]
@dbrekelmans I saw a PR was merged is merged today that fixed at least one emoji issue: https://github.com/symfony/symfony/pull/40524
