### ISSUE TITLE
Selecting multiple but successive values for a select with the Form Crawler

### ISSUE THREAD

**Issue by DrMickArtisan** [symfony/symfony#40345]
**Symfony domCrawler version(s) affected**: 5.2.0

**Description**
I have form with a ChoiceType field (multiple choices allowed). This ChoiceType accepts theses values : 
`['HC','HDJ','CON'].`
During functional tests, I want to choose only first and third value (which work fine on the website).
So in my test I  send data with only  ['HC','CON'] (using the $form->form($data);)
And I get 
`InvalidArgumentException: Input "formulaire[admissionMotifs][]" cannot take "CON" as a value (possible values: "HDJ").`
As If I needed to use all data, not just only  the ones I want.
Note that if I send the first and second values (thus respecting the array order), it works.
And note that it is not a validation constraint problem, as the corresponding website works well.

**How to reproduce**
Just have a form with a multiple ChoiceType field, and select only two non subsequent values
**Possible Solution**
Absolutely no idea :)

**Additional context**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by DrMickArtisan** [comment]
I got it, how do I sent it  ?

Mike

**Comment by xabbuh** [comment]
You can push a git repository to GitHub and link to it here.

**Comment by DrMickArtisan** [comment]
here it is : 
https://github.com/DrMickArtisan/testcrawler

**Comment by xabbuh** [comment]
This looks expected to me. I don't see where you ever configure `HC` as a value to be chosen.

**Comment by DrMickArtisan** [comment]
Yhea sorry, I push the wrong test version. 
The nOk test is meant to generate an error (as hc is not to be chosen).
I just corrected the ToutOk one : by onnly choosing two values, it generate the error :
InvalidArgumentException: Input "formulaire[myArray][]" cannot take "hdj" as a value (possible values: "con").

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
I looked at this again and I think that though being confusing the current behavior can be considered expected. The single checkboxes do have distinct names and you need to pass them like this:

```php
$form->form([
    'formulaire[myArray]'  => [
        '0' => 'hs', 
        '2' => 'hdj',
    ]
]);
```

**Comment by DrMickArtisan** [comment]
Hmm ok, it's not really intuitive, but that's ok for me.
Thanks !

**Comment by stof** [comment]
@DrMickArtisan that's also how the browser will submit the data. (well, as `formulaire[myArray][0]` and `formulaire[myArray][2]` actually, but that's how it is parsed then)
