### ISSUE TITLE
[FrameworkBundle] cache:clear fails with doctrine annotations

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony#40353]
**Symfony version(s) affected**: 5.x

**Description**
Command fails due to

```
Class "Doctrine\Common\Cache\CacheProvider" not found while loading "".
```

**How to reproduce**
In a minimal Symfony 5.x app with `dev` dependencies either run `bin/console cache:clear` || `composer require doctrine/annotations` (triggers auto scripts in recipe)

**Possible Solution**
Unknown

**Additional context**
Bug discovered in MakerBundles `dev` CI on PHP 7.4 && 8. Appears to be related to https://github.com/doctrine/annotations/pull/404

**Comment by Nyholm** [comment]
This must be because if #40338 

You don't have `doctrine/annotations` installed, right?

**Comment by Nyholm** [comment]
Hm.. I've tested with and without `doctrine/annotations`. I fail to reproduce this issue. Can you help me on this repo https://github.com/Nyholm/sf-issue-40353?

**Comment by jrushlow** [comment]
> Hm.. I've tested with and without `doctrine/annotations`. I fail to reproduce this issue. Can you help me on this repo

Sure thing! reproducing this is a difficult because of how we do the tests over in maker. I'll shoot up a pr to that repo with the conditions that cause the error.
