### ISSUE TITLE
Bootstrap 5 Form Theme

### ISSUE THREAD

**Issue by herbyxxx** [symfony/symfony#40358]
Not sure if this counts as feature request or where to put it.

**Description**
Form theme layout for (upcoming - currently in beta) [bootstrap 5](https://getbootstrap.com/docs/5.0/getting-started/introduction/) like the previous versions: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig

**Comment by fabpot** [comment]
Closing as there is already a PR about this: #39157 
If you can test it and report any problems, that would help a lot getting it merged sooner.
