### ISSUE TITLE
new routing anotation fail after clear cache

### ISSUE THREAD

**Issue by Xbirdfr** [symfony/symfony#40362]
**Symfony version(s) affected**: 5.2

**Description**
On dev local environement php 8.0.2, the routing work fine, but on server with same php version, i have this issue :
On my controller, I have this :
`#[Route('/guilds', name: 'guilds')]`

after a cache:clear, i got this:  

"Unable to generate a URL for the named route "guilds" as such route does not exist"
but if i change this with : 

```
/**
   * @Route("/guilds", name="guilds")
   */
```

i'm looking if it can be a server side issue, but so far I found nothing

**Comment by xabbuh** [comment]
Are you sure that the cache on the server was built using PHP 8?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
