### ISSUE TITLE
Provide "dump-env" as regular Symfony command

### ISSUE THREAD

**Issue by mbrodala** [symfony/symfony#40381]
Symfony Flex provides a `dump-env` command which must be invoked using Composer. At [its introduction](https://symfony.com/blog/new-in-symfony-flex-1-2) it was suggested to use this in deployment workflows to generate optimized PHP versions of `.env`.

However, this assumes that Composer exists and is executed on remote servers. At least for us this is impossible since our deployment workflows dictate that releases are prepared locally (installing Composer dependencies, etc.) before being uploaded to the remote server. Thus we don't need/have Composer on the remote server.

Since I assume that we are not alone I would suggest to provide `dump-env` also as regular Symfony command which can be invoked using `bin/console`.

**Comment by stof** [comment]
@mbrodala done

**Comment by abdielcs** [comment]
Should be kept the DumpEnvCommand in symfony/flex as duplicated, or should be removed?

**Comment by mbrodala** [comment]
@abdielcs Once this is re-implemented in the framework, the command from Flex can be deprecated and removed.

**Comment by nicolas-grekas** [comment]
> this assumes that Composer exists and is executed on remote servers

since that's the motivation for this PR, let me challenge this: can't you run the command on the same machine that runs `composer install`?

**Comment by mbrodala** [comment]
@nicolas-grekas Sure I can but that would be the CI server in our case. And obviously the `.env` from the production server is not present on our CI server. So dumping a PHP version of that is not possible this way. We'd need to invoke Composer/Flex on the production server for this.

**Comment by nicolas-grekas** [comment]
OK, thanks for the details. Works for me.
