### ISSUE TITLE
[rfc][translation] add `getDefaultLocale` to `TranslatorInterface`

### ISSUE THREAD

**Issue by gggeek** [symfony/symfony#40380]
**Description**
given the fact that the only method defined by `TranslatorInterface` allows the user to request that translation be executed using a 'default' target locale, it stands to reason that every concrete implementation of this interface has to define a default locale.
This default locale can be set up via configuration, DI injection and arbitrarily complex logic.
In some scenarios, it would be useful for end-user code, which usually has only access to a single translator instance, to be able to retrieve the current default locale without having to interact with the configuration logic.

**Example**
When building an app on top of an arbitrary framework based itself on symfony, it is quite common to write code that gets injected a Translator instance.
In some cases, that code will have to interact with an external system which can provide data in a locale-aware manner. Internalizing the translation of said data into the application is not desirable, as it is not in the ownership of the app itself.
In such scenario, it would be quite nice for the code to be able to do something like:

```
$this->getRemoteData($this->translator->getDefaultLocale();
```

without having to find out how the default locale is configured and managed by the specific framework in use.

**Comment by gggeek** [comment]
ps: I know that the existing `TranslatorTrait` implements `getLocale`, but that method is not in the interface, which forces users to check for its presence before using it, if they typehint against the interface and not the implementation...

**Comment by ro0NL** [comment]
i think currently `LocaleAwareInterface` is the answer (see also https://github.com/symfony/symfony/pull/37946)

so we have a default vs. current locale issue, however if the current locale fits your usecase im not sure `getDefaultLocale` is really worth it (for a value you already know).

**Comment by gggeek** [comment]
Indeed, I had not seen #37946, I definitely should hone my find-old-issues-in-github skills...
At first sight, it looks 99% like the same need, with an implementation proposal that is 75% the same :-) 

I agree with the remark of @nicolas-grekas in it, that `LocaleAwareInterface` is useful for the wiring layer, but a Translator implementation should not necessarily allow the end user to set the locale.
That's why I proposed to go with an extension of `TranslatorInterface` instead.
It is true that there would be quite some overlap sith `LocaleAwareInterface` though...

**Comment by ro0NL** [comment]
note i do agree with 

>  it stands to reason that every concrete implementation of this interface has to define a default locale

but initially the current locale will be the default one. Hence i asked if it fits. If so i think we should avoid getLocale vs getDefaultLocale generally spoken yes.

**Comment by gggeek** [comment]
Agree that there can be some naming confusion.
Atm 'default locale' is only used in a comment in the interface's php code, so it could be changed without BC concerns.
The most correct name that I can think of for the new method is probably `getCurrentDefaultLocale`, but `getLocale` is probably preferable for consistency with `LocaleAwareInterface::getLocale`

**Comment by nicolas-grekas** [comment]
I think I'm OK with the RFC. I don't see a drawback and the arguments make sense to me.
Naming the method `getDefaultLocale()` might be confusing given that translators can also implement `LocaleAwareInterface`. For them, this would mean having two methods (add `getLocale()`) that do exactly the same.

Maybe this method should be named `getLocale` for this reason?

PR welcome so that we can discuss it (to not break BC, this should be added via an `@method` annotation on the interface.)

**Comment by ro0NL** [comment]
from the implementation POV getLocale() is already the default one, when none is given to `trans()`

so im also 👍🏻 for TranslatorInterface::getLocale

this docblock: https://github.com/symfony/symfony/blob/f8e2cff9ba0a213a265fe3cd281531de20e95603/src/Symfony/Contracts/Translation/LocaleAwareInterface.php#L26 will be conflicting, but im not sure we care really.

**Comment by gggeek** [comment]
> to not break BC, this should be added via an `@method` annotation on the interface.

Not 100% sure how to do that.
Does this mean simply adding an annotation in the docblock for the interface?
Should it state that this method will become 'enforced' as part of the interface in a major version in the future?

**Comment by nicolas-grekas** [comment]
Just add the annotation: `DebugClassLoader` will turn this into a deprecation when needed.

**Comment by nicolas-grekas** [comment]
OH, and don't forget about the changelog file of course

**Comment by nicolas-grekas** [comment]
See #40554

**Comment by gggeek** [comment]
@nicolas-grekas sorry for not having been able to follow through - busy times. Thanks for your effort!

**Comment by nicolas-grekas** [comment]
No worries :)
