### ISSUE TITLE
Interface error in depedency injection component

### ISSUE THREAD

**Issue by akeemphilbert** [symfony/symfony#40382]
**Symfony version(s) affected**: 4.4.20

**Description**
Getting an error "interface cannot extend previously implemented interface" in Symfony\Component\DependencyInjection\Exception\ExceptionInterface

This seems to be happening because Psr\Container\ContainerExceptionInterface now implements Throwable (v1.1)

**How to reproduce**
Upgrade psr/container to 1.1 and do a composer update on any symfony project (or upgrade to 4.4.20)

**Possible Solution**
Stop extending Throwable in Symfony\Component\DependencyInjection\Exception\ExceptionInterface 

**Additional context**
Noticed this when upgrading to 4.4.20

**Comment by domhaas** [comment]
Can reproduce it by doing "symfony new project --full".

**Comment by axzx** [comment]
related https://github.com/symfony/symfony/issues/40383
related https://github.com/php-fig/container/issues/30

**Comment by derrabus** [comment]
PR: php-fig/container#31

**Comment by stof** [comment]
`psr/container` 1.1.1 has been released with a fix.
