### ISSUE TITLE
Regression in phpunit-bridge 5.2.4: fatal error instead of deprecation notice for Debug\DebugClassLoader

### ISSUE THREAD

**Issue by MalteWunsch** [symfony/symfony#40390]
**Symfony version(s) affected**: 5.2.4

**Description**

While in symfony/phpunit-bridge 5.2.3 I get the nice deprecation notice `The "Symfony\Component\Debug\DebugClassLoader" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\DebugClassLoader" instead.`, in symfony/phpunit-bridge 5.2.4 I get a fatal error like this:

```
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Deprecation.php:121
Stack trace:
#0 /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php(134): Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Deprecation->__construct('The "Symfony\\Co...', Array, '/var/www/Webfac...')
#1 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(16384, 'The "Symfony\\Co...', '/var/www/Webfac...', 16, Array)
#2 /var/www/WebfactoryDownloadBundle/vendor/symfony/debug/DebugClassLoader.php(16): trigger_error('The "Symfony\\Co...', 16384)
#3 /var/www/WebfactoryDownloadBundle/vendor/composer/ClassLoader.php(478): include('/var/www/Webfac...')
#4 /var/www/WebfactoryDownloadBundle/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/var/www/Webfac...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#6 [internal function]: spl_autoload_call('Symfony\\Compone...')
#7 /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php(64): class_exists('Symfony\\Compone...')
#8 /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(34): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->__construct(Array)
#9 /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(1124): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->__construct()
#10 /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(161): PHPUnit\TextUI\TestRunner->handleConfiguration(Array)
#11 /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#12 /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#13 /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#14 {main}
  thrown in /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Deprecation.php on line 121

Fatal error: Uncaught Error: Call to a member function getName() on null in /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Deprecation.php on line 121

Error: Call to a member function getName() on null in /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Deprecation.php on line 121

Call Stack:
    0.0003     395160   1. {main}() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/phpunit:0
    0.0161    1077728   2. PHPUnit\TextUI\Command::main() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/phpunit:61
    0.0162    1077840   3. PHPUnit\TextUI\Command->run() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/Command.php:162
    0.0825    2959616   4. PHPUnit\TextUI\TestRunner->doRun() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/Command.php:206
    0.0825    2959640   5. PHPUnit\TextUI\TestRunner->handleConfiguration() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:161
    0.0849    2994632   6. Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->__construct() /var/www/WebfactoryDownloadBundle/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:1124
    0.0858    3065528   7. Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->__construct() /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php:34
    0.0864    3074336   8. class_exists() /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:64
    0.0864    3074416   9. spl_autoload_call() /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:64
    0.0864    3074496  10. Composer\Autoload\ClassLoader->loadClass() /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:64
    0.0866    3074608  11. Composer\Autoload\includeFile() /var/www/WebfactoryDownloadBundle/vendor/composer/ClassLoader.php:346
    0.0878    3187520  12. include('/var/www/WebfactoryDownloadBundle/vendor/symfony/debug/DebugClassLoader.php') /var/www/WebfactoryDownloadBundle/vendor/composer/ClassLoader.php:478
    0.0878    3187840  13. trigger_error() /var/www/WebfactoryDownloadBundle/vendor/symfony/debug/DebugClassLoader.php:16
    0.0878    3188904  14. Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError() /var/www/WebfactoryDownloadBundle/vendor/symfony/debug/DebugClassLoader.php:16
    0.0893    3305280  15. Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Deprecation->__construct() /var/www/WebfactoryDownloadBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:134
```

**How to reproduce**

Run phpunit tests with symfony/phpunit-bridge 5.2.4 and the deprecated symfony/debug 4.4 instead of the newer symfony/error-handler (i.e. in any symfony < 4.4).

This leads to [`Legacy/SymfonyTestsListenerTrait.php:64`](https://github.com/symfony/phpunit-bridge/blob/v5.2.4/Legacy/SymfonyTestsListenerTrait.php#L64) trying to class load `LegacyDebugClassLoader` = `Symfony\Component\Debug\DebugClassLoader`, which `trigger_error`s in [`DebugClassLoader.php:16`](https://github.com/symfony/debug/blob/4.4/DebugClassLoader.php#L16) with a stack trace that [`DeprecationErrorHandler\Deprecation::__construct`](https://github.com/symfony/phpunit-bridge/blob/v5.2.4/DeprecationErrorHandler/Deprecation.php#L121) does not handle well.

**Possible Solution**

It seems to me \Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Deprecation::__construct should be improved to handle such a stack trace. https://github.com/symfony/phpunit-bridge/commit/d0eb698b1167bfdf2bca8f1e49993ebff8d9687b already adresses this or a similar issue, but seemingly not for all legacy cases. I'll try a PR.

**Comment by MalteWunsch** [comment]
I'm struggling to create a PR for two reasons:

First, I don't understand https://github.com/symfony/phpunit-bridge/blob/v5.2.4/DeprecationErrorHandler/Deprecation.php#L119-L124.

Is L120: `$this->originClass = \get_class($line['args'][0]);` correct? With my stack trace from above, it sets `$this->originClass = null`, as `args` is an empty array in `$line`.

Can L121: `$this->originMethod = $line['args'][0]->getName();` be correct? `args` should only contain strings, shouldn't it? If so, calling a `->getName()` on a string seems like an error to me.

Depending on what `originClass` and `originMethod` are for, I could imagine either `Symfony\Component\Debug\DebugClassLoader`/`null` (as this [trigger_error](https://github.com/symfony/debug/blob/4.4/DebugClassLoader.php#L16) is outside of any method) or `Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait`/` __construct` (as the cause for loading the deprecated class) to be the correct values?


Second, I wanted to write a unit test demonstrating the successful behaviour in phpunit-bridge 5.2.3, the fatal error in phpunit-bridge 5.2.4 and the suggested fix. But as this execution path is only reached with symfony/debug and the current symfony uses symfony/error-handler, I do not see an easy way to demonstrate that.

Any suggestions?

**Comment by derrabus** [comment]
Can you produce a reproducer for this problem?

@nicolas-grekas, I think you have worked on the deprecation reporting recently (#40067). Could this issue be caused by your changes?

**Comment by MalteWunsch** [comment]
Quick status update: I'm trying to produce the reproducer and will get back to you. Thanks.

**Comment by MalteWunsch** [comment]
Does https://github.com/MalteWunsch/symfony_issue_40390 work as a reproducer? After installing, `php bin/phpunit` should raise the fatal error.

I started with `composer create-project symfony/skeleton: ^3.4` instead of `composer create-project symfony/skeleton` as suggested in the [reproducer documentation](https://symfony.com/doc/current/contributing/code/reproducer.html), as this error occurs only with a deprecated version of `symfony/debug` instead of the newer `symfony/error-handler`. I stumbled upon this issue in a GitHub Actions workflow which tests a bundle for symfony 3.4.* backwards compatibility. Tests with symfony 4.4.* are green, as they install the newer `symfony/error-handler`.

If this does not work or you need more specifics, please let me know!

**Comment by Chi-teck** [comment]
Confirm. Deprecation notices trigger fatal error in  5.2.4.

**Comment by nicolas-grekas** [comment]
Would anyone be able to have a look? I can't until next week personally.

**Comment by MalteWunsch** [comment]
I'd be happy to work on a PR, but I would definitely need help with that. My first question would be how to properly execute the unit tests of phpunit-bridge?

`bin/simple-phpunit` in a seperate checkout of phpunit-bridge does not work for me:

```
phpunit-bridge$ bin/simple-phpunit
PHP Warning:  chdir(): No such file or directory (errno 2) in /var/www/phpunit-bridge/bin/simple-phpunit.php on line 186
PHP Stack trace:
PHP   1. {main}() /var/www/phpunit-bridge/bin/simple-phpunit:0
PHP   2. require() /var/www/phpunit-bridge/bin/simple-phpunit:13
PHP   3. chdir() /var/www/phpunit-bridge/bin/simple-phpunit.php:186
Creating a "phpunit/phpunit" project at "./phpunit-8.3-0"
Installing phpunit/phpunit (8.3.5)
Plugins have been disabled.
  - Installing phpunit/phpunit (8.3.5): Extracting archive
Created project in /var/www/phpunit-bridge/phpunit-8.3-0
composer.json has been updated


  [InvalidArgumentException]
  Could not find a matching version of package ChangeLog-8.3.md. Check the package spelling, your version constraint and that the package is available in a stability which
   matches your minimum-stability (stable).
```

`bin/phpunit` in a checkout of the reproducer from above runs the tests, but even with phpunit-bridge 5.2.3 this gives me 9 failing tests, so I'm not sure if that's the correct way and the failures have a deeper meaning.

Maybe phpunit-bridge 5.x is not even meant to work with older Symfony components like symfony/debug (deprecated in Symfony 4.4)? If so, maybe a `conflict` in `composer.json` could be appropriate?

With running tests I should be able to add a test case for my fatal error stacktrace, but I'm still unsure what a meaningful fix would look like, as I don't know the meaning of `originClass` and `originMethod` and in which cases an object is expected in Deprecation.php:121 for `->getName()` to be called on.

If this sttempt is not helping, please feel free to dismiss it :-)

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, it helped a lot.

**Comment by ste93cry** [comment]
@nicolas-grekas can we expect a release of this bugfix soon?
