### ISSUE TITLE
Regex constraint not working

### ISSUE THREAD

**Issue by StevenCarre** [symfony/symfony#40413]
**Symfony version(s) affected**: 4.4

**Description**
I tried to add a Regex constraint on a TextType field in a form, and it is letting invalid strings through. The pattern is supposed to be: only digits or a comma.

**How to reproduce**
```
        ->add('ids', TextType::class, array(
            'label' => 'Id :',
            'constraints' => [
                new Regex([
                    'pattern'=>'/^[,0-9]+$/',
                    'message' => 'Veuillez entrer un ou plusieurs chiffres séparés par des virgules',
                    'match' => true,
                ])
            ],
            'required' => false
        ))
```

**Possible Solution**

**Additional context**
The form submits the value "32 33" and I get an exception, "SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "32 33""

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by StevenCarre** [comment]
xadbuh hi, thanks for your comment.
I finally found my mistake, the controller was missing a $form->isValid() condition.
Thanks for your time, have a nice day
