### ISSUE TITLE
Yaml parser incorrectly parses some yaml block sequences

### ISSUE THREAD

**Issue by andris-sevcenko** [symfony/symfony#40438]
**Symfony version(s) affected**: 5.x-dev

**Description**
Symfony Yaml parser incorrectly parses some block sequences.
In particular, if using [this test data](https://github.com/yaml/yaml-test-suite/blob/115c4ac2b9b2e7929632da1444fd069b48f7a31f/test/3ALJ.tml), the output produced is

```json
[
  "- s1_i1 - s1_i2",
  "s2"
]
```

which is not the expected output as per the test.

**How to reproduce**
```php
<?php
require_once '../vendor/autoload.php';

$yaml = <<<Y
- - s1_i1
  - s1_i2
- s2
Y;


echo(json_encode(\Symfony\Component\Yaml\Yaml::parse($yaml)));
```

**Additional context**
Related issues:
* https://github.com/craftcms/cms/issues/5777
* https://github.com/prettier/prettier/issues/10506

**Comment by xabbuh** [comment]
Status: Reviewed
