### ISSUE TITLE
5.2.5 regression on sending email Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#40445]
**Symfony version(s) affected**: 5.2.5

**Description**
On a normally working Symfony project, we send an email on user login
After upgrading to Symfony 5.2.5 this now creates an error

<img width="1219" alt="Screenshot 2021-03-11 at 12 46 44" src="https://user-images.githubusercontent.com/400092/110790002-68b78780-8268-11eb-99a2-a4705fe29b76.png">

**How to reproduce**

I think the cause is passing in Entities and Objects to the context, which might have closures in them.

Im passing into the context the User object and the LoginSuccessEvent event in my live app. 

You can replicate this by changing the UnitTest to have a closure in the context of the templated email as follows, this will result in the broken unit test with the same error Im experiencing. 

```
// changing the testRenderedOnce test you can replicate this 

 $closure = function ($name){
            return $name;
        };

        $email = (new TemplatedEmail())
            ->to('fabien@symfony.com')
            ->from('helene@symfony.com')
            ->context(['event'=>$closure])
        ;
```

<img width="771" alt="Screenshot 2021-03-11 at 13 12 15" src="https://user-images.githubusercontent.com/400092/110792516-6c004280-826b-11eb-8ab9-1b6afbb21e85.png">

**Possible Solution**
re-review of https://github.com/symfony/symfony/pull/39733/ which was added in 5.2.5 and the error message relates to.

**Additional context**
Transport is a standard SMTP.

**Comment by PhilETaylor** [comment]
I have ruled out my User Object, so this means that its the passing of the LoginSuccessEvent object to the context that is causing this.

**Comment by PhilETaylor** [comment]
Thanks @fabpot - much appreciated, hope the report helped.

**Comment by derrabus** [comment]
It did, thank you. ❤️
