### ISSUE TITLE
[Messenger][MonologBridge] Reset logs between jobs

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#40451]
**Description**
Long running processes using fingers crossed handler can be problematic. See https://github.com/symfony/symfony-docs/issues/15086 for details.

A possible solution could be resetting them between jobs via the `WorkerMessageHandledEvent` (similar to doctrine em resets). [Perhaps before](https://github.com/symfony/symfony-docs/issues/15086#issuecomment-797056171) processing the first job as well.

**Comment by greg0ire** [comment]
This is how it is done for Swarrot, BTW: https://github.com/swarrot/swarrot/pull/215/files

**Comment by kbond** [comment]
Could resetting the container be an option here as well? Does resetting the container clear the Doctrine em's (if so, `DoctrineClearEntityManagerWorkerSubscriber` could be removed)?

**Comment by kbond** [comment]
I believe #40761 solves?

**Comment by fabpot** [comment]
Closing then.
