### ISSUE TITLE
[Form] IntegerType, IntegerToLocalizedStringTransformer

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#40456]
**Symfony version(s) affected**: 4.4.20 but I guess all versions.

**Description**
When having arabian language, `IntegerType` converts numbers to their language form (am I expressing myself correctly?)
so we have ٣٤٤٣ which is 3443. 
This is ok in Firefox, but not ok in Chrome. Chrome expects `value` in `input type="number` to be `3443` and it does the conversion to `٣٤٤٣`.

**How to reproduce**
In Chrome: Create simple IntegerType form in Arabian language, persist 3443, then reload form - it will disappear. 

**Possible Solution**
remove `IntegerToLocalizedStringTransformer` from `IntegerType` ?

**Additional context**

This is the actual error from Chrome: 

`<input type="number"  value="١٢٣٤٩">`

results in 

`The specified value "\u0661\u0662\u0663\u0664\u0669" cannot be parsed, or is out of range.`
and rendered input is empty, so it submits empty value.
![image](https://user-images.githubusercontent.com/3340882/110953541-27020c00-8350-11eb-8135-08d2b7a1a0ca.png)

if we have 
`<input type="number" value="12349">`
It works as expected:

![image](https://user-images.githubusercontent.com/3340882/110953463-105bb500-8350-11eb-9ff8-5b644e9a889a.png)

**Comment by stof** [comment]
When we render the input as a HTML5 `<input type="number">`, we should indeed not apply ICU formatting on the number, as that's not valid in HTML 5.

**Comment by stof** [comment]
NumberType has a `html5` option forcing the usage of the `en` format. We need the same in IntegerType IMO.

**Comment by Warxcell** [comment]
> When we render the input as a HTML5 `<input type="number">`, we should indeed not apply ICU formatting on the number, as that's not valid in HTML 5.

Why not remove the transformer? Isn't it used to apply correct separator? But in this case it's integer, so basically no separator?

**Comment by Warxcell** [comment]
Or maybe add option `html5` option indeed, if yes => do not add transformer and render as number, otherwise render as text and add transformer?
