### ISSUE TITLE
Allow to bind inline services by type and name

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#40469]
```php
return function(ContainerConfigurator $configurator) {
    $services = $configurator->services()
        ->defaults()
        ->bind(Foo::class.' $foo', inline_service(Foo::class))
    ;
};
```

Currently it throws `Invalid binding for service "": named arguments must start with a "$", and FQCN must map to references. Neither applies to binding "Foo $foo"`, while binding inline service just by name works.

**Comment by nicolas-grekas** [comment]
We might improve the error message, but what it says is that only references are allowed when binding services, and this looks legit to me. Otherwise, there is some non-intuitive issue that is going to happen, eg: should all inline services lead to different instances or should they all refer to the same one ? (note: this would need a ... reference).

**Comment by vudaltsov** [comment]
@nicolas-grekas, I understand your reasoning, but as a developer I face the following inconsistency. I can bind an inline service by name only, but cannot bind by type and name. So it would be more logical to forbid binding inline services completely, or allow to bind them both ways.

**Comment by nicolas-grekas** [comment]
Would you mind investigating in the code where this difference happens? I'm surprised that binding by name-only works with inline services.

**Comment by vudaltsov** [comment]
https://github.com/symfony/symfony/blob/2dcf313a87368eed43a8296c153cf216bc7f25c0/src/Symfony/Component/DependencyInjection/Loader/Configurator/Traits/BindTrait.php#L37-L39

The first matching group in the regexp is optional. Thus, during a call `->bind('$name', inline_service())`, `preg_match` evaluates to `true` and `!preg_match` evaluates to `false`, which immediately prevents exception from being thrown.

**Comment by nicolas-grekas** [comment]
PR welcome @vudaltsov, let's make this consistent.
