### ISSUE TITLE
Could not create a project using Composer for Symfony 4.0 and 4.1

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#40478]
**Symfony version(s) affected**: `4.0` and `4.1`

**Tested with:** `3.3`, `3.4`, `4.0`, `4.1`, `4.2`, `4.3`, `4.4`, `5.0`, `5.1` and `5.2`

**Description**
`composer create-project` with Symfony `4.0` or `4.1` end with this error:
`Unrecognized option "cookie_samesite" under "framework.session"`

**How to reproduce**
Use Composer 1.9 to have PHP7 and not PHP8:
`docker run --rm -it composer:1.9 composer create-project symfony/skeleton:4.0.* /tmp/symfony`

**Comment by derrabus** [comment]
Thank you for your report, but the 4.0 and 4.1 branches of Symfony have reached their end of life a long time ago. We don't patch or provide support for them anymore.
