### ISSUE TITLE
[amazon-mailer] AWS Signature V3 is not supported anymore

### ISSUE THREAD

**Issue by hyde1** [symfony/symfony#40480]
**Symfony version(s) affected**: 5.2.4

[symfony/amazon-mailer](https://github.com/symfony/amazon-mailer) still uses AWS Signature Version 3 (signature starting with AWS3-HTTPS) while it is not supported anymore. 
As mentioned in the aws documentation (https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html) :

> Beginning October 1st, 2020, Amazon SES will only support requests signed using Signature Version 4. If you use an older version of the AWS Signature, you must adopt AWS Signature Version 4 prior to that date.

**Comment by fabpot** [comment]
see https://github.com/symfony/symfony/issues/36956#issuecomment-785678737

**Comment by jderusse** [comment]
You can run `composer require async-aws/ses` to fix that.

**Comment by hyde1** [comment]
> You can run `composer require async-aws/ses` to fix that.

Thanks a lot! I think it could be a good idea to add this in the [mailer documentation](https://symfony.com/doc/current/mailer.html).
