### ISSUE TITLE
Allow to set CURLOPT_FORBID_REUSE when constructing http curl client

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#40482]
**Description**

Currently, `CurlHttpClient` has a set of allowed options that can be passed on construction and then they're converted to curl opts internally.

However, the `CURLOPT_FORBID_REUSE` is not mapped to any option and therefore it's impossible to use when relying on PSR interfaces.  
Symfony `request()` method allows to pass options through 3rd arg via `extra.curl` but I don't want to use that option nor interface as it exposes implementation details.

I'm making http requests to devices that has unreliably implemented HTTP. Therefore it is required to force TCP connection to close in order to enforce some stability. And that's done using `CURLOPT_FORBID_REUSE`.

**Example**

Would it make sense to add `forbid_reuse: true|false` option that can be passed into `new CurlHttpClient(['forbid_reuse': false])`? I don't see any other way to do so.

**Comment by nicolas-grekas** [comment]
As allowed by #38026?

**Comment by nicolas-grekas** [comment]
> I don't want to use that option nor interface as it exposes implementation details.

Oh, I read to fast your description. Still, this extra entry is the way IMHO.

**Comment by nicolas-grekas** [comment]
You could use an HttpClientFactory service to achieve what you describe - this would effectively prevent connections from being reused, by creating a new client instance when needed.

**Comment by simPod** [comment]
I checked the construction source code before but did not find explicit use of `extra.curl` there so it confused me. You are right, I can use that, thank you. I guess this is solved then.

I did not find any `HttpClientFactory` class though. However, I have an experience that even though I created a new Client instance before every request, it was still reusing connections (in long running php processes).

**Comment by nicolas-grekas** [comment]
> I did not find any HttpClientFactory class though

There is none, that would be yours to create :)

> even though I created a new Client instance before every request, it was still reusing connections

That'd be strange, I don't know how this can happen, knowing the code.

Closing as solved then.

**Comment by simPod** [comment]
Ah, ok, I get what you mean. I have a factory service.

Anyway, it's different problem, different code. 

Thanks ;)
