### ISSUE TITLE
[RFC] Move PassportInterface::checkIfCompletelyResolved to service layer?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#40491]
I fail to see why

https://github.com/symfony/symfony/blob/21d4c09a1c8a9b291f83573fcd251064a25604e2/src/Symfony/Component/Security/Http/Authenticator/Passport/PassportTrait.php#L46-L53

should be part of the PassportInterface contract, instead of leveraging eg. AuthenticatorManagerInterface 🤔 

can a passport really be self-checking in that regard? is it an implementation detail of the manager?

**Comment by chalasr** [comment]
I agree 👍 See #40567
