### ISSUE TITLE
ServerDumpPlaceholderCommand produces warning

### ISSUE THREAD

**Issue by DemigodCode** [symfony/symfony#40495]
**Symfony version(s) affected**: 5.2.5

**Description**
All console commands in dev-environment show a warning regarding the ServerDumpPlaceholderCommand.

**How to reproduce**
Run any console command with configuration variable dump_destination is not set.

**Possible Solution**

**Additional context**
```
[WARNING] Some commands could not be registered:                               

In Application.php line 496:
                                                                               
  [Symfony\Component\Console\Exception\LogicException]                         
  The command defined in "Symfony\Bundle\DebugBundle\Command\ServerDumpPlaceh  
  olderCommand" cannot have an empty name.    
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by DemigodCode** [comment]
Don't really know what you want me to do.

Install symfony with debug-bundle and console.

Run "php bin/console list" works in each of my projects.

**Comment by DemigodCode** [comment]
Ah, found a possible Solution.

Add a name for that console command e.g. "server:dump-placeholder"
And return true in isHidden()

So the command will not raise any warnings and is also hidden in "php bin/console list"

If it's okay for you, I will do a PR.

**Comment by xabbuh** [comment]
this affects the upcoming 5.3 release
