### ISSUE TITLE
Missing translation commands for Symfony 5.1

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#40509]
**Symfony version(s) affected**: 5.1.11

**Description**
The file “composer.json” contains [the following specification](https://symfony.com/doc/current/translation.html#installation "Installation of a software component") on my development system.

```json
{
    "require": {
…
        "symfony/translation": "^5.2"
    }
}
```

The corresponding software documentation mentions [the command “translation:update”](https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically "Extracting translation contents and updating catalogs automatically").

I wonder at the moment why it is not listed here by the command “`php app/bin/console | grep translation`” (while it can be determined that other commands are available as expected).  
[How can such system dependencies be fixed?](https://stackoverflow.com/questions/66691197/checking-availability-of-symfony-translation-commands "Checking availability of Symfony translation commands")

**Comment by xabbuh** [comment]
Symfony 5.1 is not supported anymore. Do you experience the same after updating to 5.2?

**Comment by elfring** [comment]
I got the same impression for a questionable dependency for this software library.

Do you find it appropriate that the Symfony console displays still the information “Symfony 5.1.11 (env: dev, debug: true)” despite of the following specifications in the configuration file.

composer.json:
```json
{
    "require": {
…
        "symfony/console": "^5.2",
        "symfony/framework-bundle": "^5.2",
        "symfony/translation": "^5.2"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^5.2"
        }
    }
}
```

**Comment by xabbuh** [comment]
What is the output of `composer show`?

**Comment by elfring** [comment]
```
…
symfony/console                    v5.2.5  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection       v5.2.5  Allows you to standardize and centralize the way objects are constructed in your application
…
```

**Comment by stof** [comment]
the Symfony version displayed in the about command corresponds to the value of the http-kernel component

**Comment by xabbuh** [comment]
Please do not shorten the output and please also show the output of `bin/console debug:config framework`.

**Comment by elfring** [comment]
@stof: Thanks for your background information.

```
…> composer show | grep http-kernel
…
symfony/http-kernel                v5.2.5  Provides a structured process for converting a Request into a Response
```

-----

Would you like to point [any PHP console implementation](https://symfony.com/doc/current/components/console.html#creating-a-console-application "Creating a console application") out which would be customised for translation purposes?

**Comment by xabbuh** [comment]
@elfring Can you please answer to https://github.com/symfony/symfony/issues/40509#issuecomment-802060719?

**Comment by elfring** [comment]
:thinking: I guess that you will find another answer questionable because my evolving directory structure does not contain the executable script “`bin/console`” for this clarification attempt so far.

**Comment by xabbuh** [comment]
Should we close then?

**Comment by elfring** [comment]
I have found out in the meantime that a command variant like “`composer create-project symfony/skeleton my_test3 && cd my_test3 && composer require symfony/translation symfony/console && php bin/console | grep translation`” can provide useful data.
Now I am still looking for guidance to resolve the remaining system dependencies if I would copy the executable script “`bin/console`” into another software development directory.

**Comment by xabbuh** [comment]
I am closing here for now. We can consider to reopen once we are able to reproduce the issue.

**Comment by elfring** [comment]
:thinking: How do you think about to reproduce this issue by deleting the directory “bin” from a software development version?
(The main source files were stored in the directory “app” for a while before I came along the need to extend the affected application also at other places.)

**Comment by xabbuh** [comment]
I don't know what you are doing in your application and I am not motivated to play guess games.

**Comment by elfring** [comment]
:crystal_ball: I hope then that other PHP developers can get into the mood to clarify corresponding implementation details a bit more.
