### ISSUE TITLE
[amazon-mailer] AWS Session Token is ignored

### ISSUE THREAD

**Issue by salvatore-pollaci** [symfony/symfony#40512]
**Symfony version(s) affected**: 5.2.5
**symfony/mailer**: 5.2.5
**symfony/amazon-mailer**: 5.2.4
**async-aws/ses**: 1.4.0

**Description**
I have noticed that other than the `accessKeyId` and `accessKeySecret` options, also the `sessionToken` option should be used to sign the AWS ses request, otherwise the following error will be thrown: `Unable to send an email: The security token included in the request is invalid. (code 403)`.

**How to reproduce**
Configure mailer with the 'ses+api' transport schema:
```
framework:
    mailer:
        dsn: 'ses+api://%env(AWS_ACCESS_KEY_ID)%:%env(urlencode:AWS_SECRET_ACCESS_KEY)%@default?region=env(AWS_REGION)'
```
Call Symfony's Mailer `send()` method.

Notice that the following exception is thrown:
`Unable to send an email: The security token included in the request is invalid. (code 403)`

**Possible Solution**
In symfony/amazon-mailer's Transport/SesTransportFactory.php create() method, pass the `sessionToken` option to the SesClient Configuration argument:
```
switch ($scheme) {
                case 'ses+api':
                    $class = SesApiAsyncAwsTransport::class;
                    // no break
                case 'ses':
                case 'ses+https':
                    $class = $class ?? SesHttpAsyncAwsTransport::class;
                    $options = [
                        'region' => $dsn->getOption('region') ?: 'eu-west-1',
                        'accessKeyId' => $dsn->getUser(),
                        'accessKeySecret' => $dsn->getPassword(),
                        'sessionToken' => '<AWS_SESSION_TOKEN_VALUE>'
                    ] + (
                        'default' === $dsn->getHost() ? [] : ['endpoint' => 'https://'.$dsn->getHost().($dsn->getPort() ? ':'.$dsn->getPort() : '')]
                    );

                    return new $class(new SesClient(Configuration::create($options), null, $this->client, $this->logger), $this->dispatcher, $this->logger);
            }
```

**Alternative Possibile Solution**
Fix `async-aws/core`'s Configuration fallback algorithm.
Currently, it has a fallback algorithm(src/Configuration.php [parseEnvironmentVariables())](https://github.com/async-aws/core/blob/master/src/Configuration.php#L158) that implies that if the 'accessKeyId' configuration option is given, there is no need to populate the `accessKeyId`, `accessKeySecret` and `sessionToken` configuration options with their fallback values, i.e. their respective environment variable values(`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`).
Instead the algorithm should insert the fallback value for each required config option that isn't given(e.g. populate `sessionToken` with the value stored in `AWS_SESSION_TOKEN` if such config option is not given).

**Comment by Nyholm** [comment]
Thank you for this issue. 

The absolutely best way to authenticate with AWS is to use some fallback. That means either environment variables or config files in their default AWS locations. If you run your code on Lambda, ECS or even EC2 (I think) there are already environment variables or config files defined for you. Basically, everything will work out of the box. 

If you are not running your code on AWS (or if you want to override) you can pass credentials in the DSN. Note that you cannot pass a `accessKeyId` in the DSN and assume it will use the secret from the environment. (ie what I think you suggest in the "alternative solution") That will cause all kind of nasty side-effects and unexpected unauthorised errors. 

But hm... Looking at the code and at your error message. It seams like it suggest that you do provide a security token... 

Are you running your code on AWS? 
Will it work if you remove the credentials for the DSN? (ie you will get an error that user/XXX_profile is not authenticated)

Btw, I do like your first solution. But it may be a small bug in AsyncAws.

**Comment by jderusse** [comment]
> also the sessionToken option should be used to sign the AWS ses request

This assumption is wrong, the sessionToken is only required when you provide **temporary** credentials. 

As you noticed, AsyncAws also prevent mixing credentials from several sources because providing a tuple of data from several sources does not make sense and would lead to unwanted errors (ie. People use 2 clients with 2 different accounts: 1 that rely on env variables (key/secret/session), and a second with key/secret injected via DSN, the second client must not use the session defined for the first client)

If you expect AsyncAws to use the env variables, then you can remove the user/password from the DSN:
```diff
 framework:
     mailer:
-        dsn: 'ses+api://%env(AWS_ACCESS_KEY_ID)%:%env(urlencode:AWS_SECRET_ACCESS_KEY)%@default?region=env(AWS_REGION)'
+        dsn: 'ses+api://default'
```

With such configuration, Symfony should leave the credentials empty, and AsyncAws will fallback to the env variables.

A last note: Symfony does not provide a way to authenticate with sessionToken **via the DSN**, and IMHO it should not do it, because the credentials are ephemeral (we are talking about 15 minutes to 1 hour max), use a DSN with such ephemeral credentials does not make sense IMHO.

**Comment by salvatore-pollaci** [comment]
> This assumption is wrong, the sessionToken is only required when you provide temporary credentials.

That explains a lot. In fact recently we installed aws-vault, which sets temporary credentials. I wasn't aware that the session token was required only when using temporary credentials.


> If you expect AsyncAws to use the env variables, then you can remove the user/password from the DSN:

Perfect. This solution works great for me.

**Comment by stof** [comment]
@jderusse this probably deserve improving the documentation about that.
