### ISSUE TITLE
Allow AbstractNormalizer to use null for nullable constructor parameters without default value

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#40511]
**Symfony version(s) affected**: All versions until 5.1 (but I guess 5.2 is too)

**Description**

Serializer component AbstractNormalizer attemps to guess constructor parameters, and falls back using default values when possible, which is good. Yet, it misses one use case: when you specify nullable non-optional parameter, case in which null is a valid value, not the default one, yet still valid.

It's a matter a choice, either we consider that the incoming data should explicitly set null here, or we consider that it might come from a dynamic language such as JavaScript that may remove undefined values from sent JSON: case in which we might want to fix that and consider that undefined is null.

**How to reproduce**

Simply write a class with a constructor as such:

```php
class Foo
{
    public function __construct(string $foo, ?string $bar)
    {
    }
}
```

And attempt to denormalize using this incoming array:

```php
$input = [
    'foo' => 'any value',
];
```

In this specific case, `null` is an allowed value for `$bar`, and value is not set in `$input`, why not simply give it null ? Actual behaviour is that the exception for missing constructor argument is raised and prevents the object from being denormalized.

**Possible Solution**

Easy two-line fix, in `AbstractNormalizer::instantiateObject()` as such:

Replace:

```php
                } elseif (\array_key_exists($key, $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class] ?? [])) {
                    $params[] = $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class][$key];
                } elseif ($constructorParameter->isDefaultValueAvailable()) {
                    $params[] = $constructorParameter->getDefaultValue();
                } else {
                    throw new MissingConstructorArgumentsException(sprintf('Cannot create an instance of "%s" from serialized data because its constructor requires parameter "%s" to be present.', $class, $constructorParameter->name));
                }
```

Using:

```php
                } elseif (\array_key_exists($key, $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class] ?? [])) {
                    $params[] = $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class][$key];
                } elseif ($constructorParameter->isDefaultValueAvailable()) {
                    $params[] = $constructorParameter->getDefaultValue();
                } elseif ($constructorParameter->hasType() && $constructorParameter->getType()->allowsNull()) {
                    $params[] = null;
                } else {
                    throw new MissingConstructorArgumentsException(sprintf('Cannot create an instance of "%s" from serialized data because its constructor requires parameter "%s" to be present.', $class, $constructorParameter->name));
                }
```

I just added those two lines:

```php
                } elseif ($constructorParameter->hasType() && $constructorParameter->getType()->allowsNull()) {
                    $params[] = null;
```

Compatible for all PHP version from 7.0 if I read correctly https://www.php.net/manual/en/reflectiontype.allowsnull.php

**Comment by pounard** [comment]
I'm sorry if I misclassified this, it could be either a bug or a feature request, in my opinion it's a bug, but it would be legit for you to downgrade to a feature request.

I have no strong feeling about this, but since there's no easy other workaround than writing a custom normalizer for each class (and I basically have hundreds that matches this behaviour in my current project) then I consider the fact that working around being not easy as a bug :)

**Comment by pounard** [comment]
OK, I see that @ro0NL seems to like the idea, I'll try to add a PR within the week, as always, lot of work to do, not much spare time for open source :/

**Comment by ro0NL** [comment]
ive no strong opinion on ` ?string $bar` vs ` ?string $bar = null`, respectively translating to `{"bar": null}` vs. `{}`. IMHO the proposal is legit.
