### ISSUE TITLE
[Cache] ApcuAdapter cache adapter does not support customizing the marshaller

### ISSUE THREAD

**Issue by ste93cry** [symfony/symfony#40523]
In my application I'm using the `firebase/php-jwt` package to parse a set of JWK keys. I want to cache those keys, however, unfortunately, the library returns them as instances of the `OpenSSL Key` resource. This is not a problem as long as I use a cache adapter (e.g. Redis) that supports having a custom marshaller as it allows me to serialize the data into a string and deserialize it back as a resource when I get the value from the cache, however I found out that the `ApcuAdapter` does not support this feature. I could imagine that maybe this hasn't been done because APCu is able to store almost everything without the need of serialization, so it makes little sense to have the ability to choose a custom marshaller. However, if this is not the reason and it makes sense to provide this feature I would be open to contribute it 😄

**Comment by nicolas-grekas** [comment]
I'd be fine adding support for an optional marshaller to ApcuAdapter.
We didn't add one yet because as you noticed Apcu handles serialization on its own just fine.
PR welcome :)

**Comment by ste93cry** [comment]
I see two choices for the default marshaller:

- We use the [`DefaultMarshaller`](https://github.com/symfony/symfony/blob/1b937403255c9f841d6597b2bcefc0e93fe51545/src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php) marshaller, regardless of the fact that it's unnecessary for the most cases with APCu
- We do not provide any default marshaller, therefore the default value will be `null` and nothing will be used

What do we prefer?

**Comment by nicolas-grekas** [comment]
I think the 2nd approach is the most appropriate one.
