### ISSUE TITLE
[HttpClient] StreamWrapper fails to copy stream for responses without content length

### ISSUE THREAD

**Issue by rmikalkenas** [symfony/symfony#40574]
**Symfony version(s) affected**: not sure at which version StreamWrapper was introduced

**Description**
While requesting unknown content length streamed responses, I noticed that such responses converted to php resources (using `StreamWrapper::createResource`) cannot be copied using `stream_copy_to_stream`. My guessing is that `StreamWrapper::stream_stat` method returns `size` argument as zero which results to `stream_copy_to_stream` not work

**How to reproduce**
```
$client = HttpClient::create();
$response = $client->request('GET', 'https://someUrlWithUnknownContentLengthResponse');
$resource = StreamWrapper::createResource($response, $client);
$outputStream = fopen('php://output', 'wb');
$bytesCopied = stream_copy_to_stream($resource, $outputStream);
// $bytesCopied === 0
```

My final result is to restream it again, but due to stream_copy_to_stream failure the response is empty:
```
return new StreamedResponse(
    static function () use ($resource): void {
        $outputStream = fopen('php://output', 'wb');

        stream_copy_to_stream($resource, $outputStream);
    }
);
```

**Possible Solution**
Unfortunately have no idea how to fix it, but I would gladly help with PR if anyone suggest a possible fix.

**Comment by nicolas-grekas** [comment]
Interesting, can you check the source code of stream_copy_to_stream() to verify how it behaves in relation to the size?
FYI,if you just want to stream to a file, you'd better use the buffer option with a stream resource. But that's doesn't invalidate your report at all.

**Comment by rmikalkenas** [comment]
@nicolas-grekas sorry, I'm not familiar with C to investigate stream_copy_to_stream() implementation (maybe @nikic could help and elaborate more as documentation does not provide enough information). 
Other than that I have found some interesting insights:
- if I return empty array from `Symfony\Component\HttpClient\Response\StreamWrapper::stream_stat()`, then stream_copy_to_stream() works as expected.
- as an alternative solution to my problem I changed stream_copy_to_stream() to fread/fwrite and it works fine!
```
return new StreamedResponse(
    static function () use ($resource): void {
        $outputStream = fopen('php://output', 'wb');
        rewind($resource);
        while (!feof($resource)) {
            fwrite($outputStream, fread($resource, 4096));
        }
        // stream_copy_to_stream($resource, $outputStream);
    }
);
```

**Comment by nikic** [comment]
Relevant code: https://github.com/php/php-src/blob/2f3538c2150eb2698fb024f97ff049bbb20642d7/main/streams/streams.c#L1557-L1566 If stat() succeeds, size is zero and mode reports a regular file, then no copy is performed. Not sure what mode symfony is setting here (it's a hardcoded 33060 value...)

**Comment by nikic** [comment]
Though to be honest, I have no idea why that check is even there... seems pretty dubious to optimize zero-size copies based on a stat, if that stat isn't used for anything else.

**Comment by nicolas-grekas** [comment]
I figured that 33060 means "regular file" + r--r--r-- permissions, which looks accurate.
But the size stat should return -1 instead of 0 here.

**Comment by rmikalkenas** [comment]
@nikic thanks for explanation and both of you for fixes! :tada: @nicolas-grekas
