### ISSUE TITLE
Serializer @Ignore not working

### ISSUE THREAD

**Issue by mj-jackson** [symfony/symfony#40581]
**Symfony version(s) affected**: 
php bin/console --version
Symfony 5.2.5

composer show:
symfony/serializer v5.2.4
symfony/property-access v5.2.4

**Description**
Just installed symfony yesterday and can not get Ignore() to work as expected.

**How to reproduce**
Did a fresh symfony installation with doctrine, symfony/serializer and symfony/property-access.
I created a new Entity Class with make:entity User
```
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @Ignore()
     * @ORM\Column(type="string", length=255)
     */
    private $password;
}
```
I tried making password public as in the example. Also tried to set the Ignore annotation at the getter. Password will always be transferred.
Serializer will be used when outputting via AbstractController
```
public function index(): JsonResponse {
        $user = new User();
        $user->setCreated(new \DateTime());
        $user->setEmail('asd');
        $user->setFirstName('asd1');
        $user->setLastName('asd2');
        $user->setPassword('12');

        $serializerService->toJson($user);
        return $this->json($user); // outputs everything, including password, which is annotated with @Ignore()
    }
```
I also tried with a self made serializer Service.
```
class SerializerService
{
    private $encoders;
    private $normalizers;
    private $serializer;

    public function __construct()
    {
        $this->encoders = [new JsonEncoder()];
        $this->normalizers = [new ObjectNormalizer()];
        $this->serializer = new Serializer($this->normalizers, $this->encoders);
    }

    public function toJson(object $object): string
    {
        return $this->serializeObjectTo($object);
    }

    private function serializeObjectTo(object $object, string $format = 'json'): string
    {
        $test = $this->serializer->normalize($object);
        var_dump($test);
        return $this->serializer->serialize($object, $format, ['json_encode_options' => JsonResponse::DEFAULT_ENCODING_OPTIONS,]);
    }
}
```
var_dump also includes password. Also tried different attributes like lastName etc. Did not work.

**Possible Solution**
Did not look into the problem and therefore don't have a solution

Am I doing something wrong or can someone reproduce the problem?

**Comment by mj-jackson** [comment]
I'm sorry, I made a mistake with the Annotationloader. Works as expected.

**Comment by taivn** [comment]
@mj-jackson 
Hello, I'm facing the same issue with you. Could you please share how to fix it ?
Thank you.

**Comment by mj-jackson** [comment]
@taivn 
Sure. I did not load the AnnotationLoader. See https://symfony.com/doc/current/components/serializer.html#attributes-groups
Basically create a new ClassMetadataFactory with the wanted AnnotationLoader and pass it to the ObjectNormalizer. In my Code example
```
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$this->encoders = [new JsonEncoder()];
$this->normalizers = [new ObjectNormalizer($classMetadataFactory)];
$this->serializer = new Serializer($this->normalizers, $this->encoders);
```

This should fix it.

**Comment by taivn** [comment]
@mj-jackson 
It worked perfectly. Thanks so much :)

**Comment by herbertamukhuma** [comment]
> @taivn Sure. I did not load the AnnotationLoader. See https://symfony.com/doc/current/components/serializer.html#attributes-groups Basically create a new ClassMetadataFactory with the wanted AnnotationLoader and pass it to the ObjectNormalizer. In my Code example
> 
> ```
> $classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
> $this->encoders = [new JsonEncoder()];
> $this->normalizers = [new ObjectNormalizer($classMetadataFactory)];
> $this->serializer = new Serializer($this->normalizers, $this->encoders);
> ```
> 
> This should fix it.

Works for me as well

**Comment by simaotwx** [comment]
Now that the Doctrine Annotations are not maintained anymore in favor of the PHP 8 attributes, how does this work now?

Following line does not work because `AnnotationReader` is from `Doctrine\Common\Annotations\AnnotationReader`.

```
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
```

**Comment by derrabus** [comment]
> Now that the Doctrine Annotations are not maintained anymore in favor of the PHP 8 attributes, how does this work now?

Use attributes. ✌️ 

> Following line does not work because `AnnotationReader` is from `Doctrine\Common\Annotations\AnnotationReader`.

So don't pass an annotation reader. We don't need it for attributes.

**Comment by simaotwx** [comment]
> So don't pass an annotation reader. We don't need it for attributes.

Thanks for letting me know.

So is this what I need?

```php
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader());
```

**Comment by derrabus** [comment]
Yes.

**Comment by simaotwx** [comment]
Thank you, @derrabus!

**Comment by softmasters** [comment]
Hello, I have the same problem with attributes: the #[Ignore] attribute is not working in my Entities.
I'm using ObjectNormalizer without passing the ClassMetaDataFactory instance.
If i pass the metaData, I get the following error:

`User Notice: Undefined property: Proxies\\__CG__\\App\\Entity\\Provincia::$lazyObjectState in C:\\lavori\\ammedica\\rnpm\\rnpm_manager\\vendor\\symfony\\property-access\\PropertyAccessor.php on line 431`

If  I uncomment the line:

`AbstractNormalizer::IGNORED_ATTRIBUTES => ['comuni', 'province'],`

the properties specified in the array are correctly ignored, but I'd like to specify the attribute in each entity.

This is my Entity:

```
namespace App\Entity;

use App\Repository\ProvinciaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: ProvinciaRepository::class)]
class Provincia extends CrudEntity
{
    #[ORM\OneToMany(mappedBy: 'provincia', targetEntity: Comune::class, orphanRemoval: true)]
    #[Ignore]
    private Collection $comuni;

    #[ORM\ManyToOne(inversedBy: 'province')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Regione $regione = null;

    #[ORM\Column(length: 2)]
    private ?string $sigla = null;

    public function __construct()
    {
        $this->comuni = new ArrayCollection();
    }

    // #[ORM\Id]
    // #[ORM\GeneratedValue]
    // #[ORM\Column]
    // private ?int $id = null;

    // public function getId(): ?int
    // {
    //     return $this->id;
    // }

    /**
     * @return Collection<int, Comune>
     */
    #[Ignore]
    public function getComuni(): Collection
    {
        return $this->comuni;
    }

    public function addComuni(Comune $comuni): static
    {
        if (!$this->comuni->contains($comuni)) {
            $this->comuni->add($comuni);
            $comuni->setProvincia($this);
        }

        return $this;
    }

    public function removeComuni(Comune $comuni): static
    {
        if ($this->comuni->removeElement($comuni)) {
            // set the owning side to null (unless already changed)
            if ($comuni->getProvincia() === $this) {
                $comuni->setProvincia(null);
            }
        }

        return $this;
    }

    public function getRegione(): ?Regione
    {
        return $this->regione;
    }

    public function setRegione(?Regione $regione): static
    {
        $this->regione = $regione;

        return $this;
    }

    #[Ignore]
    public function getReadable() {
        return (string) $this->getDescription();
    }

    public function getSigla(): ?string
    {
        return $this->sigla;
    }

    public function setSigla(string $sigla): static
    {
        $this->sigla = $sigla;

        return $this;
    }
}

```

and this is the code I'm using in the controller:
```
$queryBuilder = $ownerRepo->createQueryBuilder('e');
            $queryBuilder->where('e.deleted = :deleted OR e.deleted IS NULL')
                ->setParameter('deleted', false);
            $owners = $queryBuilder->getQuery()->getResult();

            $encoder = new JsonEncoder();

            $metaFactory = new ClassMetadataFactory(new AnnotationLoader());

            $defaultContext = [
                AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function (object $object, string $format, array $context): string {
                    //echo(memory_get_usage(true));echo "<br>";
                    return $object->getId();
                },
                //AbstractNormalizer::IGNORED_ATTRIBUTES => ['comuni', 'province'],
                DateTimeNormalizer::FORMAT_KEY => 'd/m/Y',
            ];
            $normalizer = new ObjectNormalizer($metaFactory, null, null, null, null, null, $defaultContext);
            $dateNormalizer = new DateTimeNormalizer([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d H:i:s']);

            $serializer = new Serializer([$dateNormalizer, $normalizer], [$encoder]);

            $ownersJson = $serializer->serialize($owners, 'json');
```

**Comment by xabbuh** [comment]
@softmasters Please open a new issue and provide a small example application that allows to reproduce it.
