### ISSUE TITLE
Support a configurable data directory for console applications

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#40594]
The software library “Symfony” supports [console applications](https://symfony.com/doc/current/console.html "Description for console commands").
Some of them can work with data in directory hierarchies which are different from the directories where source files are stored for a running console command.
:thinking: But they need to know a base directory for the desired data processing.

Thus I suggest to configure this system setting by corresponding command parameters on demand.
* [Path argument](https://symfony.com/doc/current/console/input.html#using-command-arguments "Using command arguments")
* [Variable in a system configuration file](https://symfony.com/doc/current/components/config/definition.html "Defining and processing configuration values")

**Comment by xabbuh** [comment]
Which commands do you have in mind?

**Comment by elfring** [comment]
I would like to achieve another software extension for console applications which require the information of a base directory.

**Comment by xabbuh** [comment]
Well, that's not really helping. Can you be a bit more precise please about what and where you would like to see changed?

**Comment by elfring** [comment]
:thinking: I imagine that categories can be distinguished for console applications.
They would support a different amount of functionality by default.

* How do you think about [the usage of a corresponding inheritance hierarchy](https://www.php.net/manual/en/language.oop5.inheritance.php "Using inheritance")?
* How would you like to pass a path (as an argument or system setting) to a customised console command?

**Comment by xabbuh** [comment]
I think I wrote that before in one of your previous tickets. If you see the need for new features or improvements in the Symfony code, please describe some real world use cases that you have in mind or provide concrete steps that need to be done.

I am closing here for now as the requested changes are too vague and are not actionable. Keep in mind that nobody knows your application and/or your use cases and we cannot guess what needs to be done.

**Comment by elfring** [comment]
>… please describe some real world use cases …

[I did that already](https://github.com/symfony/symfony/issues/40577 "Support the specification of an application instance for the translation tool").


>… as the requested changes are too vague and are not actionable.

Are you used to functionality distinctions for console applications?


>Keep in mind that nobody knows your application and/or your use cases and we cannot guess what needs to be done.

Would you like to improve data processing for selected directory hierarchies anyhow?

**Comment by elfring** [comment]
Would you find it easier to compare the software development situation with [a standard tool like “`find`”](https://en.wikipedia.org/wiki/Find_(Unix)#Find_syntax "Searching for files") according to design possibilties for console applications?

**Comment by elfring** [comment]
I am still curious [how the desired clarification will evolve further](https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1617971310332800 "Support request").
