### ISSUE TITLE
[Security] Add event subscriber aliases for DeauthenticatedEvent and LogoutEvent in SecurityEvents

### ISSUE THREAD

**Issue by Adambean** [symfony/symfony#40596]
I noticed that `Symfony\Component\Security\Http\SecurityEvents` only supports the `InteractiveLoginEvent` and `SwitchUserEvent` events.

It would be rather splendid if support could be added to `DeauthenticatedEvent` and `LogoutEvent` (with suggested aliases "security.deauthenticate" and "security.logout" respectively) so they could be picked up by an event subscriber instead of needing separate event listeners.

I could happily submit a PR for this, but I'd have thought there must be a reason for not including these events to date? (Seems like it would have been obvious to have included at the time of building `SecurityEvents`.)

**Comment by chalasr** [comment]
You can use an event subscriber for those. For that, you need to use the event FQCN (e.g. `LogoutEvent::class`) when it is not a named event.

**Comment by Adambean** [comment]
You're right, that does work. It just looks strange from the outside not having an alias available for it or being documented.
_(I'd have not known about this without your feedback.)_

For example when compared with the others:
```
AuthenticationEvents::AUTHENTICATION_SUCCESS => [
    ["userAuthenticationSuccessful", self::PRIORITY],
],
AuthenticationEvents::AUTHENTICATION_FAILURE => [
    ["userAuthenticationFailed", self::PRIORITY],
],
SecurityEvents::INTERACTIVE_LOGIN => [
    ["userAuthenticatedInteractively", self::PRIORITY],
],
SecurityEvents::SWITCH_USER => [
    ["userSwitched", self::PRIORITY],
],
DeauthenticatedEvent::class => [
    ["userDeAuthenticated", self::PRIORITY],
],
LogoutEvent::class => [
    ["userDeAuthentication", self::PRIORITY],
],
```

If aliases aren't needed for `DeauthenticatedEvent` and `LogoutEvent` why would they need to exist for `INTERACTIVE_LOGIN` and `SWITCH_USER`? (E.g. why not remove them and make us subscribe to `InteractiveLoginEvent::class` and `SwitchUserEvent::class` respectively.)

**Comment by chalasr** [comment]
I get your point. The `*Events` class are pretty useful as a reference documenting the events that you can subscribe/listen to. Not having all events referenced might feel disrupting or inconsistent. 

> If aliases aren't needed for DeauthenticatedEvent and LogoutEvent why would they need to exist for INTERACTIVE_LOGIN and SWITCH_USER? (E.g. why not remove them and make us subscribe to InteractiveLoginEvent::class and SwitchUserEvent::class respectively.)

Mainly for backward compatibility. We could have deprecated those and removed them at some point, but we decided not to do so when the event name was made optional (in  4.x), probably because we didn't think it's worth the hassle.

I would be 👍 for a PR adding references for the missing events (maybe just `DEAUTHENTICATED_EVENT =  DeauthenticatedEvent::class`?).

**Comment by wouterj** [comment]
I'm :-1: for such change personally. As far as I know, FQCN based event names are the way to go in 5.0+. If I'm correctly, the other method couldn't be deprecated in 4.x, so it was decided to keep both of them in 5.x (but probably, we can remove them in 6.0).

**Comment by chalasr** [comment]
> As far as I know, FQCN based event names are the way to go in 5.0+

This might be true for userland events, as for service ids. But AFAIK no clear decision was taken regarding the core and distributed packages/bundles. It just happened that some events have been introduced without name and nobody noticed.
Let's see what others think.

**Comment by chalasr** [comment]
It was briefly discussed in https://github.com/symfony/symfony/pull/30955#issuecomment-480795768 with no clear consensus.

**Comment by Nyholm** [comment]
Besides from that it ["looks strange"](https://github.com/symfony/symfony/issues/40596#issuecomment-812697967), is there any reason to add the suggested aliases? What is the added value?

**Comment by Adambean** [comment]
Thanks for all this feedback.

> What is the added value?

The value is consistency in implementation and documentation.

Looking at the documentation for [event subscribers](https://symfony.com/doc/current/event_dispatcher.html#creating-an-event-subscriber) and [authentication events](https://symfony.com/doc/current/components/security/authentication.html#authentication-events) there is an unexplained mix and match between using classes with event aliases and specific FQCNs. It starts off displaying the event alias classes but finishes up with _"oh hey btw you can use FQCNs too"_. The way it's written has encouraged me to use event alias classes when in fact by what's been discussed here they only exist for backwards compatibility, with the intention of removing them at a later stage.

My point would be offer one or the other. Particularly if the `AuthenticationEvents` and `SecurityEvents` are intentionally deprecated (which is fine as FQCNs can be used) they should no longer be written in documentation (replace for the FQCNs instead) ASAP, even if they can't be marked as deprecated from a programmatic point of view. I am completely fine with using FQCNs to subscribe to events, and it won't take me long to adjust my application, but for the benefit of others I think the documentation should also be adjusted to discourage event alias classes now in 5.x. (Particularly someone new to Symfony, why preach them deprecated constants.)

It just lead me down a bad rabbit hole, that's all. :)

**Comment by Adambean** [comment]
> As far as I know, FQCN based event names are the way to go in 5.0+. If I'm correctly, the other method couldn't be deprecated in 4.x, so it was decided to keep both of them in 5.x (but probably, we can remove them in 6.0).

_(This would also further my reasoning that the 5.x documentation should no longer present event alias classes, but instead teach readers the FQCNs in all example snippets.)_

**Comment by wouterj** [comment]
For reference, I'm not 100% confident I'm correct. I just asked the core team to consider this issue and define if FQCN or event aliases are the way to go for Symfony. I agree with you that if FQCN are the way to go, we do need to update the docs to show it as much as possible (instead of event aliases).

**Comment by fabpot** [comment]
I would be in favor of deprecating/removing the aliases and only support FQCN. That's a trend we've been following in other part of the framework and Twig since the introduction of the `::class` notation in PHP.

**Comment by Adambean** [comment]
> For reference, I'm not 100% confident I'm correct. I just asked the core team to consider this issue and define if FQCN or event aliases are the way to go for Symfony. I agree with you that if FQCN are the way to go, we do need to update the docs to show it as much as possible (instead of event aliases).

> I would be in favor of deprecating/removing the aliases and only support FQCN. That's a trend we've been following in other part of the framework and Twig since the introduction of the `::class` notation in PHP.

I would be happy with that. Took literally 3 minutes to swap event aliases for FQCNs and worked perfectly on first attempt.

Thank you all for your input to this discussion. 👍

**Comment by Nyholm** [comment]
Im closing this in favour of #40692.
