### ISSUE TITLE
Form DateType accepts random strings as valid value and converts it to 1970-01-01

### ISSUE THREAD

**Issue by kamil-jakubowski** [symfony/symfony#40597]
**Symfony version(s) affected**:5.2

**Description**
\Symfony\Component\Form\Extension\Core\Type\DateType when using widget "single_text" accepts incorrect date string for example "dsfsdfds" and transform it before mapping to form-data (data_class object) to 1970-01-01. It should give an error that date is invalid. Even adding constraint \Symfony\Component\Validator\Constraints\Date to the date field is not working, because the field validator checks value after transforming (1970-01-01), so the value is valid.

**How to reproduce**

1. Create a form with DateType|BirthdayType field:
`$builder->add('birthDate', BirthdayType::class, [
                'label' => "Birthdate",
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'yyyy-MM-dd',
                'input' => 'string',
                'input_format' => 'Y-m-d',
                'constraints' => [
                    new NotBlank(),
                    new Date()
                ]
            ])`
2. Submit form with some incorrect value in the field
![image](https://user-images.githubusercontent.com/4580210/112701418-e3032100-8e90-11eb-92db-c57c2ed52526.png)

3. After submitting form and rendering it again you can see value 1970-01-01 and no error
![image](https://user-images.githubusercontent.com/4580210/112701476-0a59ee00-8e91-11eb-8ea1-c950f5549b63.png)

Here are dump of form array input from the Request object after submit:
`array:1 [▼
  "birthDate" => "dsfsdfdsdsdsfdsf"
]`

and dump of associated form-data object after form->handleSubmit():
`App\UI\Web\Form\Profile\ProfileCreateRequest {#548 ▼
  +birthDate: "1970-01-01"
}`

**Possible Solution**
My research showed that \Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer does that incorrect transition without any error.

It uses \IntlDateFormatter, which converts every incorrect date string to timestamp=false in:
symfony/form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:123
line 123: `$timestamp = @$dateFormatter->parse($value);`

XDebug output:
![image](https://user-images.githubusercontent.com/4580210/112702117-c23bcb00-8e92-11eb-9c63-f5ec45be9c48.png)

I've added some test var $someTestVar to the DateTimeToLocalizedStringTransformer, only to show in xdebug output of int_get_error_code().
As you can see dateFormatter has errorCode => 9 and U_PARSE_ERROR, but whole function is run using silent mode with "@" so there is no exception thrown. Another strange thing that **intl_get_error_code()** gives 0 code, so also condition in line 130 is not TRUE, and an exception in line 131 is not thrown.

![image](https://user-images.githubusercontent.com/4580210/112702231-0fb83800-8e93-11eb-839f-27a52ee00d3b.png)

After that **$timestamp** var is false, which is converting to 0, when DateTime object is creating after that, so it gives a date with 1970-01-01 :) 
![image](https://user-images.githubusercontent.com/4580210/112702719-cec12300-8e94-11eb-9d12-f3aa7bbe6291.png)

**Additional context**
The same problem occurs when you're using, but `   'input' => 'string',
                'input_format' => 'Y-m-d',`
it transforms incorrect value to DateTime('1970-01-01') object then.

**Comment by xabbuh** [comment]
Do you have the intl extension installed or are you using the Symfony Intl polyfill?

**Comment by xabbuh** [comment]
Can you try #40598?

**Comment by kamil-jakubowski** [comment]
@xabbuh I hadn't intl extension installed, so it was using Symfony Intl polyfill.
After instalation of intl, it works fine. Thanks!
![image](https://user-images.githubusercontent.com/4580210/112732448-514fee00-8f3a-11eb-98a6-c4846bb51ae8.png)

#40598 should fix it also for Symfony Intl polyfill usage. 

Although it is only workaround in Symfony-Form. The basic bug is in Symfony Intl polyfill :)

**Comment by kamil-jakubowski** [comment]
#40598 approved, I've tested with intl uninstalled 👍
