### ISSUE TITLE
[Notifier] Extend FakeSms & FakeChat notifier

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#40625]
Based on [this comment](https://github.com/symfony/symfony/pull/39949#issuecomment-774135022)

* [x] `fakesms+email` should receive a mailer service id ✅ see initial PR https://github.com/symfony/symfony/pull/39949
* [ ] `fakesms+logger` should receive a logger service id + an optional channel ?? 🤔
* [ ] `fakesms+database` should receive an entity manager service id + options ?? 🤔

And we end up with one Factory (like https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php) and 6 transports

As another follow up we could create a `symfony/fake-chat-notifier`:
* [x] `fakechat+email` ✅  https://github.com/symfony/symfony/pull/40647
* [ ] `fakechat+logger`
* [ ] `fakechat+database`

@JamesHemery @noniagriconomie @ke20 anybody? 😄

**Comment by noniagriconomie** [comment]
@OskarStark are/should those transport only for `dev|test` env?
related to https://github.com/symfony/symfony/pull/39949/files#r564443227
👍 to leverage more "storage" for those fake notifier :)

**Comment by JamesHemery** [comment]
@OskarStark Instead of having two separate Notifiers, wouldn't it be more interesting to have a `fake` Notifier that supports chat and sms?

**Comment by OskarStark** [comment]
We can, but what would be the benefit? We need 2 dedicated transport factories anyway which are registered in the framework bundle plus the package is already named `symfony/fake-sms-notifier`

**Comment by OskarStark** [comment]
> @OskarStark are/should those transport only for dev|test env?

Yes

**Comment by JamesHemery** [comment]
> We can, but what would be the benefit? We need 2 dedicated transport factories anyway which are registered in the framework bundle plus the package is already named `symfony/fake-sms-notifier`

Yes indeed, no significant advantage, let's keep it that way.

**Comment by ke20** [comment]
Sorry @OskarStark I didn't follow last subjects since last time.

You're looking for someone to get and handle one subject above ?

If so, I check if I can take the subject `fakesms+database` and I've back to you asap for the answer.

**Comment by OskarStark** [comment]
@ke20 glad to hear that 🤞🏻👌🏻
Go ahead with the database 🔥

**Comment by JamesHemery** [comment]
I'll try to submit a PR for the logger channel next week.

**Comment by OskarStark** [comment]
any progress here @JamesHemery @ke20 ? 😃

**Comment by ke20** [comment]
> any progress here @JamesHemery @ke20 ? smiley

Hi @OskarStark !

Not really again... I've start a first little approach but when I wanted to test that I had some errors, but I don't know why at the moment.

My error is :
```
In FakeSmsTransportFactory.php line 30:
                                                                                                                                                                                                                   
  Argument 2 passed to Symfony\Component\Notifier\Bridge\FakeSms\FakeSmsTransportFactory::__construct() must implement interface Doctrine\ORM\EntityManagerInterface, instance of Symfony\Component\HttpClient\Cu  
  rlHttpClient given, called in /home/kevin/Workspaces/web/perso/contributions/test_5x/var/cache/dev/ContainerMSXxNgh/getNotifier_TransportFactory_FakesmsService.php on line 34 
 ``` 
 
 I don't understand why `EntityManagerInterface` is not injected into the class `FakeSmsTransportFactory` automatically when the `MailerInterface` is...
 
 Someone know if an explicit configuration is required ?
 
 **Edit**: An extract of my changements : 
 ```php
 final class FakeSmsTransportFactory extends AbstractTransportFactory
{
    protected $mailer;
    protected $entityManager;

    public function __construct(MailerInterface $mailer, EntityManagerInterface $entityManager)
    {
        parent::__construct();

        $this->mailer = $mailer;
        $this->entityManager = $entityManager;
    }

 ```

**Comment by OskarStark** [comment]
Check FrameworkExtension.php

**Comment by ke20** [comment]
Ok thank you I'll look that !

**Comment by OskarStark** [comment]
Any news?

**Comment by JamesHemery** [comment]
@OskarStark No I can't right now, maybe later :/

**Comment by noniagriconomie** [comment]
@OskarStark I'll be glad to work on the `fakesms+logger` + `fakesms+database` ones as I use an sms notifier

For the database, how can/should we configure the storage?

Will provide a PR soon

**Comment by OskarStark** [comment]
> For the database, how can/should we configure the storage?

To be honest I am not really sure about the way to go, proposals?

**Comment by noniagriconomie** [comment]
> To be honest I am not really sure about the way to go, proposals?

clone the messenger database doctrine logic? but it seems huge :s

**Comment by OskarStark** [comment]
Too big 😄 

I think we should not implement it for now logger and email is very helpful
