### ISSUE TITLE
[HttpClient] Allow MockHttpClient $responseFactory to be modifiable though accessors

### ISSUE THREAD

**Issue by rrajkomar** [symfony/symfony#40620]
**Description**
What I'm trying to achieve is the following : dynamically setting up a MockHttpClient replacement for the HttpClientInterface typehint inside my service when running Behat tests.  
The idea is to be able to run a scenarii that will span the entire call stack (from the controller, all the way down to the HttpClient call and back) by setting the HttpClientInterface alias to a MockHttpClient service.  
Each test should be able to define its own set of responses to be returned by the MockHttpClient upon call.

At the moment, this does not seem to be possible as the responseFactory needs to be injected into the MockHttpClient constructor and there are no accessors to change it afterwards.

It would be nice to be able to call a setResponseFactory from within a Behat test (or any other test type) to set the specific list of responses expected for the current test like this : 
```php
$mockHttpClient->setResponseFactory({My array of ResponseInterfaces});
```

[Note] 
I try using in test environment the following without success
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
```

And in the behat test context
```php
$this->kernel
            ->getContainer()
            ->set(HttpClientInterface::class, new MockHttpClient({My array of ResponseInterfaces}));
```

If there is a way to achieve this, without having to create specific classes for test purposes only, please share.

**Comment by nicolas-grekas** [comment]
Can't you achieve that by injecting your own, mutable, response factory?

**Comment by rrajkomar** [comment]
I could but that would require a separate class for that and considering this is likely to be used on multiple projects, that wouldn't be very DRY-like.
Truth be told, currently I can achieve that using 8pGuzzleBundle (with Guzzle's MockHandler which allows to manipulate the list of responses by appending to and/or resetting the list)
I was hoping to migrate to HttpClient instead.

**Comment by GaryPEGEOT** [comment]
@rrajkomar, you can already achieve this:


```php
class MockClientCallback
{
private 
    public function __invoke(string $method, string $url, array $options = []): ResponseInterface
    {
        // load a fixture file or generate data
        // ...
        return new MockResponse($data);
    }
}
```

```yaml
# config/services_test.yaml
services:
    # ...
    App\Tests\MockClientCallback: ~

# config/packages/test/framework.yaml
framework:
    http_client:
        mock_response_factory: App\Tests\MockClientCallback
```

From personal experience, an array of response replayed in order is sometimes a PIA to maintain.. The most user-friendly approach was to store responses in fixtures files and replay them based on url / method

**Comment by rrajkomar** [comment]
@GaryPEGEOT : That would only work with symfony 5.2+. I'm on the latest LTS.
Plus this configuration would not allow defining different sets of response depending on the test case.

Note : in the end I tried doing what I wanted with Guzzle's Mock Handler but since the container used in the behat context and the one used in the actual code called by the test aren't the same it's not working either.

I may have to take a look at a CsaGuzzle implementation to wrk around that issue.

**Comment by stof** [comment]
@rrajkomar any new feature would be added only in the next minor version anyway, and so would not be available in the LTS.

**Comment by nicolas-grekas** [comment]
I wouldn't mind adding `MockHttpClient::setResponseFactory()` if that makes things more convenient.

**Comment by GaryPEGEOT** [comment]
I think it would make functional testing easier.

**Comment by Rainrider** [comment]
@rrajkomar maybe [this](https://symfony.com/doc/current/service_container/synthetic_services.html) helps.

```yaml
# config/packages/test/services.yaml
services:
    Symfony\Contracts\HttpClient\HttpClientInterface:
        synthetic: true
```

```php
// src/Controller/MyConstroller.php

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;

final class MyController extends AbstractController
{
    private HttpClientInterface $client;

    public function __construct(HttpClientInterface $client)
    {
        $this->client = $client;
    }

    /**
     * @Route("/test", methods={"POST"})
     */
    public function test(): Response
    {
        $response = $this->client->request('POST', 'http://somewhere', [
            'json' => json_encode("I ain't going nowhere"),
        ]);

        return new Response(
            $response->getContent(),
            $response->getStatusCode(),
            $response->getHeaders()
        );
    }
}
```

```php
// tests/Controller/MyControllerTest.php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpClient\MockHttpClient;
use Symfony\Component\HttpClient\Response\MockResponse;
use Symfony\Contracts\HttpClient\HttpClientInterface;

final class MyControllerTest extends WebTestCase
{
    public function testWorks(): void
    {
        $mock = new MockHttpClient([
            new MockResponse('Mocked success', ['http_code' => 200]),
        ]);
        $client = self::createClient();
        $client->getContainer()->set(HttpClientInterface::class, $mock);

        $client->request('POST', '/test');

        $this->assertResponseIsSuccessful();
        $this->assertSame('Mocked success', $client->getResponse()->getContent());
    }
}
```
