### ISSUE TITLE
5.2.6 [HttpCache] Cannot access container

### ISSUE THREAD

**Issue by katchmk** [symfony/symfony#40637]
**Symfony version(s) affected**: 5.2.6

**Description**
[This](https://github.com/symfony/symfony/pull/40497/files#diff-3a028c16d0eb2894184bd79064ac5b9256777c282e8bf0e05e53c9a15a049128R68) handle method tries to access the container which is not booted/available yet.

**How to reproduce**
```
// Enable the cache kernel to reproduce
$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel = new CacheKernel($kernel);
```

**Comment by jvasseur** [comment]
This has already been fixed by https://github.com/symfony/symfony/pull/40619
