### ISSUE TITLE
'invalid_message' has no more effect on 'ChoiceType' with option 'multiple'

### ISSUE THREAD

**Issue by jochen-jung** [symfony/symfony#40636]
**Symfony version(s) affected**: symfony/form >=5.2.4

**Description**
Since symfony/form 5.2.4 our custom error message provided with 'invalid_message' has no more effect.

**How to reproduce**
Bug reproducer: https://github.com/jochen-jung/invalid_message_bug
Call endpoint https://127.0.0.1:8000/bug after checking out.

What I would expect in the second dump is:
"platforms: ERROR: Invalid Platform selected."

What you see instead is:
"platforms: ERROR: The value array is not valid."

**Possible Solution**
It works fine, when downgrading to "symfony/form": "^5.2.3".
However I would expect it in current versions work as well.

**Comment by Nyholm** [comment]
Great news! 

This is fixed by #40660. It will be released in the next patch version. 
Thank you for reporting this and for creating the reproducer.

**Comment by wjzijderveld** [comment]
As there is already a fix, I didn't want to open a new issue. 
But I was wondering when the next patch release is planned, as not only was the `invalid_message` option ignored, the default `invalid_message` was also changed, which I would argue is a BC break from 5.2.3 to 5.2.4, as people depend on these messages in tests and translation files for example.
I made an isolated test case here: [wjzijderveld/symfony-form-bc-break](https://github.com/wjzijderveld/symfony-form-bc-break) with [failing builds](https://www.travis-ci.com/github/wjzijderveld/symfony-form-bc-break/builds/224494894)

**Comment by Nyholm** [comment]
Symfony does a patch release about once per month (usually the end of the month). So soon, real soon. Most likely within the next few days.
