### ISSUE TITLE
[console] Table grid offset bug

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#40634]
**Symfony version(s) affected**: 5.2.6

**Description**
Seems like console table has offset issue with latest Symfony;

symfony/console 5.2.5:
![image](https://user-images.githubusercontent.com/595561/112869553-f8ad5c00-90c5-11eb-92c2-463360a84cfc.png)

symfony/console 5.2.6:
![image](https://user-images.githubusercontent.com/595561/112869637-0fec4980-90c6-11eb-8bbb-da5b456b5ba5.png)

It seems like to be related to custom styles inside table.

I created simple example repository to demonstrate this bug - https://github.com/tarlepp/symfony-console-bug

**Comment by Nyholm** [comment]
Lovely. Thank you for this issue and the reproducer. 

The error comes form this PR: https://github.com/symfony/symfony/pull/40524

When the cell is splitted on multiple rows, the first row is:

<img width="635" alt="Screenshot 2021-03-31 at 22 59 12" src="https://user-images.githubusercontent.com/1275206/113210645-bfffb500-9274-11eb-9116-2645a76e10ff.png">

The `<0x1b>` is the escape character (`ESC`)

```php
$string = '[31msome text [39m<fg=default;bg=default>';
strlen(string); // 43
(new UnicodeString($string))->width(false); // 41
```

I dont know why, It might be an issue in the string component.

**Comment by Nyholm** [comment]
Could it be related to #40635?
