### ISSUE TITLE
DebugClassLoader is reporting deprecation about final classes coming out of the test code.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#40651]
**Symfony version(s) affected**: 5.2.6 (and related 4.4 release)

**Description**
@nicolas-grekas fixed a lot of our deprecation with https://github.com/symfony/symfony/pull/40508
But we still having one:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1382

The message
```
Remaining self deprecation notices (1)

  1x: The "Sonata\DoctrineORMAdminBundle\Filter\NullFilter" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Sonata\DoctrineORMAdminBundle\Filter\EmptyFilter".
    1x in FieldDescriptionTest::testOptions from Sonata\DoctrineORMAdminBundle\Tests\Admin
```
Is thrown in the first executed test.

We're thinking it's because of our bootstrap files running
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/be010e282956d29a6392f2051f7b06f7feb590d2/tests/custom_bootstrap.php#L19 
and https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/be010e282956d29a6392f2051f7b06f7feb590d2/tests/App/AppKernel.php#L53
And loading every class is triggering the issue for the EmptyFilter
which extends a `@final` class.

It feel wrong having to add a `@group legacy` annotation to the first test just to avoid this deprecation.
Shouldn't the `DebugClassLoader` just reporting `@final` class used INSIDE the test ?

**Comment by nicolas-grekas** [comment]
`EmptyFilter` is deprecated from what I can see, so that adding `@group legacy` is legit, isn't it?
I suppose we could skip the deprecation about `@final` when a `@deprecated` class/method extends it.
PR welcome.

**Comment by VincentLanglet** [comment]
> `EmptyFilter` is deprecated from what I can see, so that adding `@group legacy` is legit, isn't it?

I agree that when I'm writing a test 
```
public function testEmptyFilter() {
     new EmptyFilter();
     //
}
```
Adding a `@group legacy` is required.

But here, the test which is triggering the deprecation is this one:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/tests/Admin/FieldDescriptionTest.php#L26
The test is not using the `EmptyFilter`.

But there is a deprecation coming from this tests, because of what is done in the `bootstrap.php` file and because this test is the first one of our test suite.

I shouldn't have to add a `@group legacy` to this test. What if I write a test before this one ? I would have to change the place of `@group legacy`...

**Comment by nicolas-grekas** [comment]
The deprecation is still legit. The logic that loads all classes should be changed to me.

**Comment by VincentLanglet** [comment]
> The deprecation is still legit.

I not fully agree with this, but let's say it's legit.
Don't you think that the fact it's reported in the first test of the test suite is not the best solution ?

> The logic that loads all classes should be changed to me.

What is your recommendation ?

**Comment by spipu** [comment]
hello,

i see that lots of deprecated message are concerning deprecated in the same vendor that the source of the deprecated definition. for example, doctrine on doctrine, or facebook on facebook. but normally, the deprecated system in symfony must ignore the deprecated in the same vendor.

example: The "Facebook\WebDriver\Local\LocalWebDriver::createBySessionID()" method will require a new "bool $isW3cCompliant" argument in the next major version of its parent class "Facebook\WebDriver\Remote\RemoteWebDriver", not defining it is deprecated.

and also : Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::setCacheDriver is deprecated. Use setCache() with a PSR-6 cache instead.

(it is in the last last version of SF 4.4.x + doctrine)

Maybe we have a more global pb on fact to ignore deprecated when they are in the same vendor ?

**Comment by spipu** [comment]
example: 
![image](https://user-images.githubusercontent.com/10595905/118764868-772eaa80-b87a-11eb-943e-8ca5fd85aa9e.png)

**Comment by stof** [comment]
@spipu `doctrine/persistence` and `doctrine/orm` are not the same package (side note: this one has been fixed in doctrine/orm and the patch will be part of the next release)

**Comment by spipu** [comment]
yes, but they are in the same vendor

**Comment by spipu** [comment]
i have another example : 

`The "Facebook\WebDriver\Local\LocalWebDriver::createBySessionID()" method will require a new "bool $isW3cCompliant" argument in the next major version of its parent class "Facebook\WebDriver\Remote\RemoteWebDriver", not defining it is deprecated.`

**Comment by spipu** [comment]
FYI, i have always the pb with the last version of SF5.3

**Comment by nicolas-grekas** [comment]
Closing as this stalled and went out of topic.

> I suppose we could skip the deprecation about @final when a @deprecated class/method extends it. PR welcome.

This still holds true ;)
