### ISSUE TITLE
[Bug][RateLimiter] sleep/usleep typo

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#40656]
**Symfony version(s) affected**: 5.x

**Description**
https://github.com/symfony/rate-limiter/blob/5.x/RateLimit.php#L70

Probably a typo and there should be `usleep`? (or remove `1e6` )

```
    public function wait(): void
    {
        sleep(($this->retryAfter->getTimestamp() - time()) * 1e6);
    }
```

**Comment by Nyholm** [comment]
Great. Thank you for this issue. 

There is a patch at #40658 that will resolve this.
