### ISSUE TITLE
[HttpClient] use CurlHttpClient on Windows if cafile or capath is set in default options

### ISSUE THREAD

**Issue by n0rbyt3** [symfony/symfony#40676]
**Symfony version(s) affected**: 5.2.6

**Description**
I get the following warning and notice:
> User Warning: Configure the "curl.cainfo", "openssl.cafile" or "openssl.capath" php.ini setting to enable the CurlHttpClient
> User Notice: Upgrade the curl extension or run "composer require amphp/http-client" to perform async HTTP operations, including full HTTP/2 support

I am on Windows and don't have these options set in my ```php.ini```, but I have set ```cafile``` 

**How to reproduce**
- on Windows, enable the curl PHP extension. Don't set any options in ```php.ini```.
- create a symfony app, add ```symfony/http-client```
- get a valid certificate in PEM format
- edit ```app/config/packages/framework.yaml```, set ```http_client``` -> ```default_options``` -> ```cafile: <path to PEM file>```
- inject ```HttpClientInterface```, perform a request

**Possible Solution**
I guess this check in ```HttpClient::create``` is faulty:
```if ('\\' !== \DIRECTORY_SEPARATOR || ini_get('curl.cainfo') || ini_get('openssl.cafile') || ini_get('openssl.capath'))```

Extending it with ```isset($defaultOptions['cafile']) || isset($defaultOptions['capath'])``` fixes both log messages.
However, ```CurlHttpClient``` can also be used if you set ```cafile``` or ```capath``` on options for scoped clients, but these options aren't available in the factory.

Why is this check present anyway? ```CurlHttpClient``` works great on Windows without any of these options.

**Additional context**

**Comment by nicolas-grekas** [comment]
> Extending it with isset($defaultOptions['cafile']) || isset($defaultOptions['capath'])

That is certainly a good idea, PR welcome.

> CurlHttpClient can also be used if you set cafile or capath on options for scoped clients, but these options aren't available in the factory.

I'm not sure what you mean. Options on scoped clients are meant to override the default options - but the default client still has to work on its own.

> CurlHttpClient works great on Windows without any of these options

I added these checks in #32022, but I don't remember exactly how/when I experienced the issue...

**Comment by n0rbyt3** [comment]
> I added these checks in #32022, but I don't remember exactly how/when I experienced the issue...

That is really interesting. Without having these options set on Windows, curl will not be able to get certificate information.

> When the "capture_peer_cert_chain" option is true, the "peer_certificate_chain" attribute SHOULD list the peer certificates as an array of OpenSSL X.509 resources.

However, the ```ResponseInterface``` contract allows empty information. I don't see any valid reasons for these messages to exist.

**Comment by fancyweb** [comment]
This issue can be closed.
