### ISSUE TITLE
Please Stop Doctrine 3 Breaking Change.

### ISSUE THREAD

**Issue by NetworkDevHead** [symfony/symfony#40686]
Doctrine maintainers have decided to abandon DBAL's  fetch()   fetchAll() and fetchColumn() (PDO syntax) in favor of clumsy, custom methods that provide little benefit.  The change is going to break millions of lines of code in the Symfony community, and make it more difficult for new programmers to learn to use Symfony.

Especially in the early days, Doctrine EntityManager was inadequate (only a couple methods, very cumbersome to do advanced queries) and QueryBuilder is extremely difficult to use. Also there are many Symfony scenarios where data is not stored in an entity at all. PDO and its syntax are familiar to PHP developers so using DBAL fetch() and fetchAll() is a very natural solution. The "upside" of this breaking change is not a net gain for Doctrine and a disaster for Symfony. The new methods are less understandable than PDO and create yet another hurdle to adopting Symfony. 

On behalf of the Symfony community, please encourage Doctrine to rollback this major breaking change.

**Comment by fabpot** [comment]
You should probably report this to the Doctrine org.

**Comment by NetworkDevHead** [comment]
I have, and thank you for your work and response.  I'm a long-time Symfony fan!!

**Comment by chalasr** [comment]
As said, this discussion should happen on the Doctrine side. Thank you.

**Comment by stof** [comment]
I don't understand why you say it is a disaster for Symfony.

The migration to DBAL 3 has a cost indeed (but that should be discussed with the DBAL team, ands it is not worse for Symfony users than other users of Doctrine).

**Comment by NetworkDevHead** [comment]
I think many Symfony devs use DBAL as a proxy for PDO, I know I have, heavily, for more than a decade.  The only reason anyone uses Doctrine is Symfony.
