### ISSUE TITLE
Maybe a bug related to symfony/uuid while using QueryBuilder ?

### ISSUE THREAD

**Issue by pink6440** [symfony/symfony#40687]
**Symfony version(s) affected**: 5.2

**Description**
While using uuid from the uuid symfony component ;
Using a OneToMany between to entities and having insert two children
When making count($mainEntity->getChildren()), the results is excpected
When making the query with the QueryBuilder it failed (0 results)

Keeping the same entity model :
- i replace with id as integer => it works
- i replace with id as ramsey/uuid => it works

**How to reproduce**
- symfony new --full myproj
- composer require symfony/uuid
- create two entities with a ManyToOne relationship
- insert values
```
$root = new Chapter();
$child = new Chapter();
$root->addChildren($child);

$em->persist($root);
$em->persist($child);

$em->flush();
// at this point, in the database, all is good
```

```
$root = $em->find(...);
dump(count($root->getChildren()); // return the correct number

// 
 $qb = $em
            ->createQueryBuilder()
            ->select('c')
            ->from(Chapter::class,'c')
            ->where('c.root = :root')
            ->setParameter('root',$root);

dump(count($qb->getQuery()->execute()); // will does not return the correct value
```

**Possible Solution**
Maybe the way the Uuid object is converted for being used in the query builder

**Additional context**
I first hit the problem when using the tree from Gedmo Extensions with StofDoctrineExtensionsBundle : i realized that path, left and right field were not updated.

Looking in the logs, the queries looking good but failed to update the correct entities because of the way the id value was convert to dbal (by the query builder ?).

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
if you are using the UuidType of the symfony package, you need to pass the type in the third argument of `setParameter` for things to work fine. If you don't, the ORM will cast the parameter as string (due to using the default type) and the UuidType of Symfony does not use the string representation of the Uuid object as the database representation.

> I first hit the problem when using the tree from Gedmo Extensions with StofDoctrineExtensionsBundle : i realized that path, left and right field were not updated.

This might indicate that the Gedmo extensions don't work well with custom field types, which should be reported there (to the extensions, not to the bundle)

**Comment by pink6440** [comment]
@stof 
Thanks for your answer (and by the way, thanks for all your work too !)

My fault on the third parameter and shame on me, i never even noticed it was here :confounded: 

That made me thought that a lot of extensions will potentially met the same problem unless they have code to automaticaly analyse the type of the parameter being used.

I will report to Gedmo ; i started report here at the beginning because it worked fine with another uuid implementation.

**Comment by pink6440** [comment]
@xabbuh  
I think stof had pointed the origin of the problem and I just report the issue to Gedmo, let me know if you need the application sample anyway.

**Comment by xabbuh** [comment]
If passing the type as the third argument solves the issue, I don't think we need a reproducer. But we can close here then as there is no bug, right?

**Comment by stof** [comment]
well, there is a bug (or a missing feature), but not in Symfony

**Comment by maidmaid** [comment]
> there is a bug (or a missing feature), but not in Symfony

Should `->setParameter('root', $root)` be smarter by understanding that root property is a relation whose id is an ulid and then implicitly set the type in the 3rd argument ? Is the bug in Doctrine side ? Wdyt @stof ?
