### ISSUE TITLE
Maybe it's time to remove references to "Silex" ?

### ISSUE THREAD

**Issue by a1812** [symfony/symfony#40681]
**Symfony version(s) affected**: 4.4

**Description**
I think we needlessly mention 'Silex' because it is not supported, or better replace to "Silex" to "micro-framework"

"Silex" mentioned:
- src/Symfony/Component/HttpKernel/README.md
- src/Symfony/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php
 

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by fabpot** [comment]
I agree, can you work on a PR on the 4.4 branch?
