### ISSUE TITLE
[HTTP Client] Should getInfo() return more request info

### ISSUE THREAD

**Issue by Glideh** [symfony/symfony#40683]
Currently using the HTTP Client with Symfony 5.2, I need to get the request header or params after running a request.

I'm not seeing them in `getInfo()` is it on purpose since it's a `$response` method ?

Anyway I need them headers, params, body so I can debug things.

How can I get those info ?

[Related SO question](https://stackoverflow.com/questions/66918665)

**Comment by n0rbyt3** [comment]
You could create your own ```HttpClientException``` class as wrapper.

```php
use Symfony\Contracts\HttpClient\ExceptionInterface;

class HttpClientException extends \RuntimeException implements ExceptionInterface
{
    private $httpClientException;

    private $requestHeaders;

    public function __construct(ExceptionInterface $httpClientException, array $requestHeaders)
    {
          parent::__construct(/* ... */);
          // ...
    }

    // implement ExceptionInterface, return everything from $this->httpClientException
}
```

Then, in your class using the client:

```php
$requestHeaders = [/* ... */]
try {
    $response = $httpClient->request(/* ... */);
} catch (TransportExceptionInterface $ex) {
    throw new HttpClientException($ex, $requestHeaders);
}

// for $response->get*($throw = true) wrap the exceptions you want to handle
```

However, if you are using Symfony as framework, you cannot access the default request headers set in ```framework.yaml``` (which are passed to ```*HttpClient::__construct```).

**Comment by nicolas-grekas** [comment]
Doesn't $response->getInfo('debug') display the info?
Note that you should call it after headers arrived, otherwise you'll get the info too early to display anything useful.

**Comment by Glideh** [comment]
@nicolas-grekas I need the request headers.

@n0rbyt3 that's the issue indeed, the aim is to get the whole request headers, params & body, those can be added not only in the yml config but also at any "layer" of the application.

**Comment by nicolas-grekas** [comment]
If you need the request headers for debugging purpose, getInfo('debug') shows them.
If you need them in a structured way, that's what TraceableHttpClient does, you should have a look.

**Comment by Glideh** [comment]
Sorry I didn't wait enough to get the request headers, I can see them now in `getInfo('debug')`, I'll check `TraceableHttpClient` also.
