### ISSUE TITLE
twig-bundle BC-break from 4.3 to 4.4 due to incorrectly defined dependency constraints

### ISSUE THREAD

**Issue by akomm** [symfony/symfony#40714]
**Symfony version(s) affected**: 4.4.*

**Description**
`framework.templating` is deprecated in 4.3 and should be removed in 5.0. 

However, the feature is de-facto "removed" in 4.4 already.

As can be seen in dependencies here:
https://packagist.org/packages/symfony/twig-bundle#v4.3.11 -> symfony/twig-bridge: ^4.3
https://packagist.org/packages/symfony/twig-bundle#v4.4.20 -> symfony/twig-bridge: ^4.4|**^5.0**

Updating twig-bundle to 4.4.* also updates twig-bridge to **^5.0**. This is a breakage, because it removes the `TwigEngine` (implementation of `Symfony\Component\Templating\EngineInterface`) even if you have symfony/* version 4.4.*.

**How to reproduce**
mkdir test && cd test
composer init
composer require symfony/templating:4.4.* symfony/twig-bundle:4.4.*

verify twig-bridge is ^5.0 and there is no `Symfony\Component\Templating\EngineInterface`-implementation.

You can also do the same with flex-recipe constrained to symfony 4.4.*. It neither defines the twig-bridge dependency explicitly, hence gets it updated to the breaking version.

**Comment by xabbuh** [comment]
If you depend on Twig bridge 4, you need to require it explicitly in your `composer.json` file. The `require` section in the Twig bundle only states that the bundle works with both versions.

**Comment by akomm** [comment]
I do not depend on twig-bridge. The twig-bundle depends on it. If the twig-bundled wanted to delegate this dependency to me, it should not have defined it as its own dependency. Since it has it defined itself, introducing changes to it that break features over minor updates is a BC-Break.

**Comment by akomm** [comment]
I do not depend on twig-bridge. The twig-bundle depends on it. If it wants to delegate this dependency to me, it should not declare it itself first place. I never `use` any of the twig-bridge classes in my App's code. In fact I only depend on `EngineInterface` of the templating component, which has the purpose of me not depending the implementation (=twig-bridge in this case). 

ps. adding twig-bridge in root is actually the way I workarouned this BC-break, but anyway...

**Comment by fabpot** [comment]
As you mention @akomm (which is was @xabbuh suggested), you need to explicitly add `twig-bridge` in your root `composer.json` file.

**Comment by akomm** [comment]
But you do realize, that this is a workaround and not a fix?

**Comment by xabbuh** [comment]
This is the fix. If you depend on the `TwigEngine` class, you should require the package that provides it explicitly.

**Comment by akomm** [comment]
> This is the fix. If you depend on the `TwigEngine` class, you should require the package that provides it explicitly.

Did you just ignore my post? I do not depend on TwigEngine. I do depend on FrameworkBundle and TwigBundle. I also do depend on the EngineInterface from the templating component.

- FrameworkBundle utilizes the templating component to load an implementation (compiler pass)
- TwigBundle provides the implementation via TwigEngine class. It does depend on twig-bridge by extending the TwigEngine class from the bridge
- My app never messes with TwigEngine class of the twig-bridge. It even does not mess with the TwigEngine from the twig-bundle, but it depends on the bundle due to implementation provided

If twig-bundle assumes itself not a provider of the EngineInterface implementation, it should not depend on twig-bridge and delegate this to the consumer...

**Comment by derrabus** [comment]
I don't think, we're getting anywhere here. As mentioned already, there isn't much we can do for you. You have been provided with an explanation of and a solution to your problem.

I'm locking this thread now. Thank you for understanding.
