### ISSUE TITLE
installation of the symfony framework

### ISSUE THREAD

**Issue by clyde237** [symfony/symfony#40720]
hello I am CLYDE indeed I just started with the symfony framework I installed the environment without problem but when I run the symfony server for the first time with: symfony server: start I get an error like this one
**[Web Server ] [07-Apr-2021 06:27:42 Europe/Berlin] 2021-04-07T06:27:42+02:00 [critical] Uncaught Error: syntax error, unexpected '|', expecting variable (T_VARIABLE)**
I do not know what to do

Thanks!

**Comment by a1812** [comment]
Hi, you need reade https://symfony.com/doc/current/setup.html

Questions not related to components are not welcome here

**Comment by noniagriconomie** [comment]
@clyde237 hey i would suggest you use instead the official symfony slack to ask question/support (see https://symfony.com/community)
your issue here will not get much attention as it is indeed not code related

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
