### ISSUE TITLE
 Failed to remove file   Permission denied    clean  cache            

### ISSUE THREAD

**Issue by jbrunetext** [symfony/symfony#40723]
**Symfony version(s) affected**: 4.4.X
symfony/console": "4.4.*"

**Description**
We faced the issue with permission system when we clean the cache.
# Base stage
FROM php:7.4.15-fpm-alpine
USER www-data
CMD ["php-fpm"]

entrypoint --> bin/console cache:clear

**How to reproduce**
Change the owner of container ROOT --> www-data
run bin/console cache:clear in entrypoint

**Possible Solution**
i try this command in my docker file but nothing work , i don't want to use chmod 777 or umask 000 instead

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by jbrunetext** [comment]
thanks for your helps . The symfony users fix my issue
