### ISSUE TITLE
Block /public on production

### ISSUE THREAD

**Issue by adsazad** [symfony/symfony#40725]
project working on /public and / also. which is messing up google indexing. how do I stop /public from working?
my htaccess is below

```
RewriteEngine on
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ /public/$1 [L,QSA]
````

**Comment by stof** [comment]
Well, you should make the public folder your document root. that's the clean fix.

anyway, this is not the right place to ask for support. Use one of the support channels: https://symfony.com/support
