### ISSUE TITLE
Broken FakeSmsTransportFactory

### ISSUE THREAD

**Issue by StaffNowa** [symfony/symfony#40731]
**Symfony version(s) affected**: 5.x

**Description**
Broken constructor
Argument 1 passed to Symfony\Component\Notifier\Bridge\FakeSms\FakeSmsTransportFactory::__construct() must implement interface Symfony\Contracts\Service\ServiceProviderInterface, instance of Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher given, called in /var/www/project/var/cache/dev/Container5Ymhxuy/App_KernelDevDebugContainer.php on line 5578

**How to reproduce**
git clone https://github.com/symfony/symfony
Enable texter - sms notifier. Try to use and get this error.

**Possible Solution**
Not found.

**Additional context**

**Comment by chalasr** [comment]
Confirmed. The factory expects a mailer service locator as constructor arg, but it is not configured anywhere.

**Comment by StaffNowa** [comment]
@chalasr thanks for help understand :)
