### ISSUE TITLE
Service cannot be found "security.command.user_password_hash"

### ISSUE THREAD

**Issue by StaffNowa** [symfony/symfony#40732]
**Symfony version(s) affected**: 5.x

**Description**
Class "Symfony\Component\PasswordHasher\Command\UserPasswordHashCommand" used for service "security.command.user_password_hash" cannot be found.

**How to reproduce**
Just copied 5.x version from git

**Possible Solution**
No solution or disable it

**Additional context**

**Comment by chalasr** [comment]
I can't reproduce.
> Just copied 5.x version from git

What does that mean? Are you testing a Symfony project (created with flex or the like)? Or is it the symfony/symfony repository you use to contribute? Please create a reproducer or provide the exact steps needed to reproduce your issue (from scratch).

**Comment by StaffNowa** [comment]
Sorry. It is false alarm. I had on my composer 5.0 and I linked with 5.x version
