### ISSUE TITLE
Missing $context parameter in Workflow GuardEvent constructor

### ISSUE THREAD

**Issue by DenisVorobyov** [symfony/symfony#40742]
**Symfony version(s) affected**: 5.2.6

**Description**
Missing $context parameter in Workflow GuardEvent 

**How to reproduce**

**Possible Solution**
Change constructor

public function __construct(object $subject, Marking $marking, Transition $transition = null, WorkflowInterface $workflow = null, array $context = [])
    {
        parent::__construct($subject, $marking, $transition, $workflow, $context);

        $this->transitionBlockerList = new TransitionBlockerList();
    }

**Additional context**

**Comment by xabbuh** [comment]
In #37539 the context was not added to the `GuardEvent` on purpose (see https://github.com/symfony/symfony/pull/37539#issuecomment-656176051). Do you have a concrete use case in mind where you need the context here?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by kocou-yTko** [comment]
@xabbuh

meanwhile, official documentation says `The context is accessible in all events:` and the guard ones are just in place with others (bottom of https://symfony.com/doc/current/workflow.html#using-events)

confusing

**Comment by xabbuh** [comment]
@kocou-yTko That's a valid concern you are raising here. It will hopefully be fixed with symfony/symfony-docs#16709.
