### ISSUE TITLE
Yaml dumper and parser TaggedValue should be extensible

### ISSUE THREAD

**Issue by goodevilgenius** [symfony/symfony#40743]
**Description**

Currently, the yaml parser allows custom tags, such as these:

```yaml
!bar some-text
```

When `Yaml::parse` is called on this, with the `Yaml::PARSE_CUSTOM_TAGS` flag, it will return a `Symfony\Component\Yaml\Tag\TaggedValue` that has a `tag` of "bar", and a `value` of "some-text".

I believe it would be useful if custom classes could be used, by creating a factory class that an application can hook into to add custom classes that implement a `TaggedValueInterface`. And the factory should be used to create new instances when parsing. If there's no available class to use for a given tag, `TaggedValue` would still be used.

Additionally, when dumping, if a value implements `TaggedValueInterface`, it would dump it as a custom tag, rather than a dictionary.

**Implementation**

I would be happy to write the implementation, and submit a PR. I wanted to see if there was interest in such a feature before I went to the work.

Additionally, I was thinking that an additional flag might be necessary to enable this behavior in the parser to preserve backwards compatibility.

**Example**

```php
# In application bootstrap

use App\Models\User; // Implements TaggedValueInterface
use Symfony\Component\Yaml\Tag\TagFactory;

TagFactory::addTaggedClass(User::class);
// This will call a static `getYamlTags` method, which should
// return an array of tags that this class can be used, and
// add it to an array of classes on the factory.

# Alternate bootstrap

use App\Models\User; // Implements TaggedValueInterface
use Symfony\Component\Yaml\Yaml;

Yaml::addCustomTag(User::class);

# To dump yaml

use App\Models\User;
use Symfony\Component\Yaml\Yaml;

$user = User::find($id); // Will fetch a user from the database
return Yaml::dump(['user' => $user]);

// Will return something like 'user: !user <id>',
// depending on the implementation in the User class

# To parse this yaml

use App\Models\User;
use Symfony\Component\Yaml\Yaml;
use Symfony\Component\Yaml\Tag\TaggedValue;

$yaml = "user: !user 5\ntagged: !other-tag text";

// Yaml::PARSE_CUSTOM_TAG_OBJECTS would be a new flag necessary to enable the behavior and preserve backwards compatibility
$userData = Yaml::parse($yaml, Yaml::PARSE_CUSTOM_TAGS | Yaml::PARSE_CUSTOM_TAG_OBJECTS);

// Since !user is a known tag, a static method will be called
// on the User class, passing the tag and value in, same as
// the TaggedValue constructor, and this method will handle
// fetching from the database and returning an instance of User

/** @var User $user */
$user = $userData['user'];

/** @var TaggedValue */
$tagged = $userData['tagged']
```

**Comment by nicolas-grekas** [comment]
Hi, thanks for the RFC.
This has been discussed and somehow rejected in the original issue and PR, see #21185 and #21194

The reason is to keep the complexity, low.
What you describe can be achieved by another class (unrelated to the Yaml component) that would iterate over the resulting tree and turn TaggedValue objects into something else.

I still think this is the correct design.

**Comment by goodevilgenius** [comment]
@nicolas-grekas 

Understandable. I can appreciate the desire to keep the core code more simple.

I do think it's unfortunate, because it increases the complexity of application code, and requires a performance hit, since you have to iterate over a parsed value to find any `TaggedValue`. It also requires additional complexity when dumping, since you'd have to construct a `TaggedValue` for each custom tag you want to use.

If this is the decision, I'll probably just create a separate library that can handle the conversion to/from `TaggedValue`. Still requires a performance hit, but would reduce complexity for those people that need this kind of functionality.

**Comment by stof** [comment]
Well, to me, it looks like you want to turn the Yaml dumper into a serializer and unserializer for your own domain objects. This increases the scope of the Yaml component by a non-negligeable margin to me. And we already have a Serializer component for such use cases (where you could have a Normalizer converting a User object into a TaggedValue for the yaml format.

Btw, your proposal requires that fetching a user from the DB can be done by calling a static method on the User class, which is most of the time not possible in Symfony projects (as that relies on having a global state accessible statically, which is something that we actively avoid when designing our APIs)

**Comment by goodevilgenius** [comment]
> Well, to me, it looks like you want to turn the Yaml dumper into a serializer and unserializer for your own domain objects.

Yeah, that's the basic idea, I suppose.

> This increases the scope of the Yaml component by a non-negligeable margin to me.

That makes sense. Totally understandable.

> And we already have a Serializer component for such use cases

Good point. That actually may be much more reasonable.
