### ISSUE TITLE
NullAdapter save() method behavior

### ISSUE THREAD

**Issue by roukmoute** [symfony/symfony#40753]
**Symfony version(s) affected**: 4 and 5

**Description**

I would like to discuss the `save()` method in [`NullAdapter`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Cache/Adapter/NullAdapter.php).
I find it strange that the `save()` method returns `false`.
If we have a condition that verifies that the `save()` happened and the NullAdapter is used for testing, it should not return false.
It should work as if it had no cache, and then it will create it.
In my opinion, the NullAdapter should not default to a reaction that should be transparent.

I would like to know what you think about changing this method to return `true`.

**How to reproduce**

```php
$adapter = new NullAdapter();
$item = new CacheItem();
$item->set('FooBar');
if (!$adapter->save($item)) {
    throw new Exception('Uoh oh');
}
```

**Comment by ro0NL** [comment]
im not sure we should make NullAdapter a MockAdapter essentially. Both purposes are different, mocking state vs. NullAdapter being stateless by design.

**Comment by roukmoute** [comment]
The Null Object is introduced to allow to not have a specific condition in a code like :

```
if (someObject != null)
    someObject.doSomething();
else
    performAlternativeBehavior();
```

Such duplicated code reveals a lack of object-orientation and a missed opportunity to rely on the elegance of polymorphism.
The interest of the NullAdapter here is the same as the NullLogger.
So it should not be a problem on some methods.

And there is a problem with the NullAdapter if I have to add an expression in my first example for it to work:

```php
$adapter = new NullAdapter();
$item = new CacheItem();
$item->set('FooBar');
if (!$adapter->save($item) && !($adapter instanceof NullAdapter)) {
    throw new Exception('Uoh oh');
}
```

**Comment by nicolas-grekas** [comment]
The reasoning makes sense to me. This would apply to commit() also.
Could you please submit a PR so that we can discuss this on actual code?
/cc @Nyholm also, I'd be happy to have your opinion on this.
