### ISSUE TITLE
TraceableAccessDecisionManager.php and opcache.preload

### ISSUE THREAD

**Issue by omgmashina** [symfony/symfony#40752]
**Symfony version(s) affected**: 5.2.6

**Description**
When preload is enabled, ErrorException is thrown.
```Warning: Cannot declare class Symfony\Component\Security\Core\Authorization\DebugAccessDecisionManager, because the name is already in use```
https://github.com/symfony/symfony/blob/0f96ac74847d114c9d9679655bcf3e94b6ba69d1/src/Symfony/Component/Security/Core/Authorization/TraceableAccessDecisionManager.php#L110

**How to reproduce**
Install current version of symfony/security-bundle and enable preload.

**Possible Solution**
Something like this, maybe:
```php
if (!class_exists(DebugAccessDecisionManager::class)) {
    class_alias(TraceableAccessDecisionManager::class, DebugAccessDecisionManager::class);
}
```

**Comment by Nyholm** [comment]
What PHP version are you running?

**Comment by omgmashina** [comment]
@Nyholm 
8.0.3

**Comment by omgmashina** [comment]
I've found the reason, this line
```php
$container->setParameter('container.dumper.inline_class_loader', true);
```
Issue can be closed.
