### ISSUE TITLE
Why CurlResponse doesn't implement getStatusCode

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#40756]
Hi,

https://github.com/symfony/http-client/blob/5.x/Response/CurlResponse.php  implements ResponseInterface
Why The getStatusCode is not implemented ?
If I call an url which doesn't exist I have an error when I use $response->getStatusCode()
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Couldn't resolve host name for \"https://..../api/agent/...\".",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/..../public/vendor/symfony/http-client/Chunk/ErrorChunk.php",
      "line": 64,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\HttpClient\\Chunk",
      "short_class": "ErrorChunk",
      "class": "Symfony\\Component\\HttpClient\\Chunk\\ErrorChunk",
      "type": "->",
      "function": "isFirst",
      "file": "/..../public/vendor/symfony/http-client/Response/ResponseTrait.php",
      "line": 245,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\HttpClient\\Response",
      "short_class": "CurlResponse",
      "class": "Symfony\\Component\\HttpClient\\Response\\CurlResponse",
      "type": "::",
      "function": "initialize",
      "file": "/.../public/vendor/symfony/http-client/Response/ResponseTrait.php",
      "line": 71,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpClient\\Response\\CurlResponse"
        ]
      ]
    },

Thanks
Thomas

**Comment by jderusse** [comment]
it is implemented in the trait https://github.com/symfony/http-client/blob/a408c485b61874e77b678ffb5c2d0fc30377c6eb/Response/TransportResponseTrait.php#L50


The error you had is because the host you use (https://..../) could not be resolved.

**Comment by ghost** [comment]
I know why I have the erreur.
I juste want to be able to trap this error to display a custom message.

Thanks
Thomas

**Comment by stof** [comment]
Well, add a `try/catch` for `Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface` around your `getStatusCode` call if you want to catch it and so something special. `\Symfony\Contracts\HttpClient\ResponseInterface` documents that exception as part of the contract of the component, so that's something you can rely on.
