### ISSUE TITLE
[HttpFoundation] Regression in using the session in kernel.terminate

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#40778]
**Symfony version(s) affected**: 5.x

**Description**

I was testing one of our main apps in 5.x and discovered a regression with the new session logic when using the token storage, causing "There is currently no session available." (related change: https://github.com/symfony/symfony/pull/38616)

We use a listener on `kernel.terminate` to log some information (including the current username). However, `RequestStack::getSession()` only works when there is a main request (which is not the case in the `kernel.terminate` event). Before 5.3, the `session` service was usable outside a main request.
The fix on our side was quite easy: use the `security.untracked_token_storage` service. Yet, I do believe there should be no hard breaks

**How to reproduce**

1. Create a listener on `kernel.terminate`
2. Try to use the session

**Possible Solution**

Maybe store the main `$request->getSession()` (in `RequestStack::push()`) in a variable and use it when there is no main request anymore? (and immediately deprecate this behavior) This way, there is no hard break between the version upgrade and there is a way to direct the user into the right debugging path.

**Comment by jderusse** [comment]
The `kernel.terminate` event is dispatched after `finishRequest` which removes the request from the RequestStack.

If I'm not wrong, there is no BC-Break here: people that use the session service will still get the session from the container (with a deprecation now). This is "just" about people migrating from `session` service to the new `RequestStack->getSession`

I'm :-1: for adding the lat previous request' session in the requestStack. This would defeat the the point of removing the state from services.

People willing to fixing the deprecation should stop using state from service, including session, including session from an empty RequestStack.
Instead, I suggesst to use the `Request` object in the `KernelTerminate` event.

**Comment by wouterj** [comment]
@jderusse then we should fix this in the `UsageTrackingTokenStorage`: https://github.com/symfony/symfony/blob/9092d5b035263706a385e355339401fdf8699c78/src/Symfony/Component/Security/Core/Authentication/Token/Storage/UsageTrackingTokenStorage.php#L89

We're not using the session directly in our listeners, the token storage is. If I understand you correctly, you propose to fix the usage tracking token storage to not use the session if there is no main requests (anymore)?
