### ISSUE TITLE
Ulid not converted to good format Base32 in place of Rfc4122

### ISSUE THREAD

**Issue by AllanFousse** [symfony/symfony#40771]
**Symfony version(s) affected**: 5.2.6

**Description**
with Ulid, and 2 fetch="EAGER" we have a bug : id pass to database is the base32 value and not Rfc4122.

replace Ulid by Uuid and it's functional, same if i delete one of the fetch="EAGER".

**How to reproduce**
symfony new test; composer req orm; composer req uid;

    #[Route("test")]
    public function test(): Response
    {
        $all = $this->getDoctrine()->getManager()->getRepository(C::class)->findAll();

        return new Response('ok');
    }

and the 3 entities : 

    class A
    {
        /**
         * @ORM\Id()
         * @ORM\Column(name="id", type="ulid")
         */
        public Ulid $id;
    }

    class B
    {
        /**
         * @ORM\Id()
         * @ORM\Column(name="id", type="ulid")
         */
        public Ulid $id;
    
        /**
         * @ORM\ManyToOne(targetEntity=A::class, fetch="EAGER")
         */
        public A $a;
    }

    class C
    {
        /**
         * @ORM\Id()
         * @ORM\Column(name="id", type="ulid")
         */
        public Ulid $id;
    
        /**
         * @ORM\ManyToOne(targetEntity=B::class, fetch="EAGER")
         */
        public B $b;
    }

**Comment by fancyweb** [comment]
Status: reviewed

IMO, there is nothing we can do in Symfony, the root problem seems to be in the Doctrine ORM eager loading feature.

Foreign key identifiers (`B->$a` in your case) are collected and then used as a criteria for `EntityPersister::loadAll()` directly. There is not processing of the type to convert it to its database value. The Ulid object end up being casted to a string, in its canonical Base32 format, which is not compatible with the database uuid type.

**Comment by nicolas-grekas** [comment]
Should be reported to doctrine.

**Comment by VincentChalnot** [comment]
See doctrine/dbal#4660
