### ISSUE TITLE
Fatal error when passing a string to Route allowed methods

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#40796]
**Symfony version(s) affected**: 5.x

**Description**
In a Symfony app, I had this route definition:

```php
/**
 * @Route("/some-path", methods="GET", name="some_name")
 */
public function someMethod()
{
    // ...
}
```

This is wrong, because `methods="GET"` should be `methods={"GET"}`

In Symfony 5.2 this works fine, and I can't see any deprecation/warning message (I might be missing them myself).

However, after upgrading to Symfony 5.x, I see a fatal error in the application related to this:

```
2021-04-13T10:16:23+00:00 [critical] Uncaught Error: 
Symfony\Component\Routing\Annotation\Route::__construct():
Argument #8 ($methods) must be of type array, string given, called in vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 944
```

If I use `methods={"GET"}`, the error is gone. Hopefully this transition should be smoother to avoid the fatal error in Symfony 5.3. Thanks!

**Comment by fancyweb** [comment]
Status: reviewed

I always use `methods="GET"` when there is one method. It's a feature to me. I hope we can keep that behavior :smile:

I bisected the issue to https://github.com/symfony/symfony/pull/40266/commits/29b0f96046b54f9517df7991933d2ffa0d3b33e4 (adding `@NamedArgumentConstructor` to the `Route` annotation).
