### ISSUE TITLE
[Form]: Add option `choice_html` to allow HTML content in ChoiceType labels

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#40806]
**Description**
Similar to [`label_html`](https://symfony.com/doc/current/reference/forms/types/form.html#label-html), add an option to allow HTML content in radio button labels. Suggested name: `choice_html`

**Example**
```php
$builder->add('foo', ChoiceType::class, ['choices' => $foos, 'expanded' => true, 'multiple' => false, 'choice_html' => true]);

**Comment by alexandre-daubois** [comment]
I wanted to say that form themes could solve this problem but given that `label_html` has been implemented in 5.1, I would say it seems a good idea in my opinion.

**Comment by alexandre-daubois** [comment]
Hey, tried a little something. Here is my code:

```php
$form = $this->createFormBuilder()
    ->add('choice', ChoiceType::class, [
        'label_html' => true,
        'label' => '<h3>Hello &gt;</h3>',
        'choices' => [
            '<h2 style="color: red">Choix 1</h2>' => 0,
            '<h2 style="color: green">Choix 2</h2>' => 1,
            '<h2 style="color: chartreuse">Choix 3</h2>' => 2,
        ],
        'expanded' => true
    ]);

return $this->render('task/new.html.twig', [
    'form' => $form->getForm()->createView()
]);
```

Actually, putting `label_html` also escapes choices labels. Choices appeared in color. Does it solve your suggestion?

**Comment by ThomasLandauer** [comment]
Yes, indeed, https://github.com/symfony/symfony/pull/31375 fixed it - thanks!
I opened an issue since it's not documented yet: https://github.com/symfony/symfony-docs/issues/15291

BTW: I had hacked support for this into a custom form theme some time ago, so I was missing that PR's improvement. That's why I don't like custom form themes ;-) What about adding a caution box at https://symfony.com/doc/current/form/form_themes.html#creating-your-own-form-theme, warning people that they will lose future updates due to this "decoupling"?

**Comment by r-ant-2468** [comment]
Hmm, for me it works as long as 'expanded' => true. As soon as this is false (drop down menu), I lose the html rendering of the option.

**Comment by stof** [comment]
@r-ant-2468 `<option>` does not allow rich content in HTML. So there is no way you can use HTML choices in a `<select>` because you would have to first update the HTML spec to allow such feature and update browsers to implement it

**Comment by r-ant-2468** [comment]
> @r-ant-2468 `<option>` does not allow rich content in HTML. So there is no way you can use HTML choices in a `<select>` because you would have to first update the HTML spec to allow such feature and update browsers to implement it

Ah yes good point, thanks
