### ISSUE TITLE
Crashing the graphical interface of the operating system Pop Os 20.10 

### ISSUE THREAD

**Issue by alvarengacarlos** [symfony/symfony#40812]
**Symfony version(s) affected**: 5.2.6

**Description**
When running Symfony on php -S localhost: 8080 I'm having a freeze on my Linux PopOS 20.10 graphical interface on my operating system. The operating system continues to run on the cli, but the graphical interface must be restarted or the process related to the php -S command in terminal of VSCode must be terminated. Freezing is not instantaneous happens after about 2 hours of programming. This happens with all frameworks that use Symfony bundles like Lumen or Laravel. I believe that the problem is on the route despite not having performed a test due to the fact of little experience with programming (only 2 years).

**How to reproduce**
Just run Symfony with php -S localhost: 8080 -t public in terminal of VScode and test the routes on the Linux PopOs 20.10 operating system.

**Comment by OskarStark** [comment]
Which PHP Version are you using?

**Comment by chalasr** [comment]
Hello,

We use Github issues for tracking bugs and feature requests, and this is not a Symfony bug but an issue in your setup. 
If you are looking for support, you should use one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more options.

Thanks.

**Comment by alvarengacarlos** [comment]
> Which PHP Version are you using?

php 7.4.9
