### ISSUE TITLE
[Semaphore] Cache lua files in memory. Minify lua files

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#40820]
**Symfony version(s) affected**: 5.x

**Description**

***1. Excessive and unnecessary IO***

`RedisStore.save`, `RedisStore.delete`, `RedisStore.putOffExpiration` every time calls `file_get_contents(luaFile)`.
It may result in excessive and unnecessary IO usage. 

```php
    public function save(Key $key, float $ttlInSecond)
    ...
        $script = file_get_contents(__DIR__.'/Resources/redis_save.lua');
```

Is there any reason against caching lua scripts in memory? For example like this
```php
static $script;
$script ??= file_get_contents(__DIR__.'/Resources/redis_save.lua');
```

Or like in Lock Component version of `RedisStore` - inline lua scripts (https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Lock/Store/RedisStore.php#L110)

***2. Minify lua files***
File size of https://github.com/symfony/semaphore/blob/5.x/Store/Resources/redis_save.lua is `1125` bytes. This could be minified twice (for example using minifer by Mathias Bynens https://github.com/mathiasbynens/luamin). And thus minify network load 2x times). What do you think about attaching minified script versions at least for prod environments?

**Comment by OskarStark** [comment]
About 2.

This could be part of our CI while merging it into a stable branch. Could be done with GithubActions if the file is touched. 

Would you accept a PR @nicolas-grekas?

@sirian would you be able to create the PR on your own or could you provide me the needed steps to Minify?

About 1.

@alexander-schranz @jderusse would be great to get your 2 cents in this topic. Thanks

**Comment by jderusse** [comment]
I think caching script is doable. PR welcome (same for lock and cache if it's not already the case)

About minify, I'm not sure it worth the complexity. 
We are talking about 500 bytes transmitted in 99% case in local Network.

**Comment by alexander-schranz** [comment]
I also would avoid the `file_get_contents` I would go here with the same way as it is in the [Redis Store](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Lock/Store/RedisStore.php#L110) and inlining the scripts to avoid to read them.

I would not minify the script they are not big and there are better alternatives by redis using `evalsha` to avoid transmitting big scripts. https://redis.io/commands/eval#bandwidth-and-evalsha but I don't see this scripts as big.

**Comment by sirian** [comment]
> About minify, I'm not sure it worth the complexity.
> We are talking about 500 bytes transmitted in 99% case in local Network.

Agree with you. I'm just used to high-load projects, but unlikely anyone will use this for >10k rps

**Comment by sirian** [comment]
I could make a PR with inlined LUA

**Comment by sirian** [comment]
> I also would avoid the `file_get_contents` I would go here with the same way as it is in the [Redis Store](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Lock/Store/RedisStore.php#L110) and inlining the scripts to avoid to read them.
> 
> I would not minify the script they are not big and there are better alternatives by redis using `evalsha` to avoid transmitting big scripts. https://redis.io/commands/eval#bandwidth-and-evalsha but I don't see this scripts as big.

@alexander-schranz  BTW, maybe at first try to call `EVALSHA`, and if redis returns `NOSCRIPT` error - then call `EVAL`?  Smth like this. kill two birds with one stone - save bandwidth and no need to minify LUA

```php
protected function evaluate($lua, $args, $numKeys)
{
    $sha = sha1($lua);

    $result = $this->redis->evalSha($sha, $args, $numKeys);

    if (false === $result && 0 === strpos($redis->getLastError(), 'NOSCRIPT')) {
        $result = $this->redis->eval($lua, $args, $numKeys);
    }

    return $result;
}
```

**Comment by alexander-schranz** [comment]
@sirian Think it should be internal private function but from my side it sounds good to implement this for cacheable scripts.
