### ISSUE TITLE
You cannot refresh a user from the EntityUserProvider that does not contain an identifier.

### ISSUE THREAD

**Issue by Cartman34** [symfony/symfony#40822]
**Symfony version(s) affected**: 5.2.6

**Description**
You cannot refresh a user from the EntityUserProvider that does not contain an identifier. The user object has to be serialized with its own identifier mapped by Doctrine.

**How to reproduce**
Calling getUser from controller or security service being logged in.

**Additional context**
My user is \App\Entity\User and this class inherits from \App\Entity\AbstractEntity that is declaring id field and some others.
The last change about user is that I added a key field but there is no serialization method in this class.
It was working in this context from one year with regular symfony updates.

When It's failing, the user is a \Proxies\__CG__\App\Entity\User, id is not present in class.
The bug is appearing only for 1 of 2 requests, it's working one times, failing then, working one time...
After a cache:clear, it's always failing.

**Solution**
I don't know why it's happening now but the inherited id field must have a **protected visiblity**.
A private visibility is excluding it from serialization.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Cartman34** [comment]
I am working on it, I will be back soon with a github project.

**Comment by xabbuh** [comment]
@Cartman34 Do you have any news for us?

**Comment by Cartman34** [comment]
I created a test project but I am unable to reproduce this issue on it.
But I am able to reproduce en 2 real projects, it seems there is another factor producing this issue.

**Comment by xabbuh** [comment]
Okay, thanks for the feedback. Let's close here then for now and we can consider to reopen when there is a reproducer.
