### ISSUE TITLE
UniqueEntity failing on 2nd submission

### ISSUE THREAD

**Issue by herbyxxx** [symfony/symfony#40832]
**Symfony version(s) affected**: tested on 5.2.6

**Description**
Hard to describe, I will try my best.

I have one Entity called `ArticleTranslation` which has two fields called `article` (ManyToOne to Entity Article) and `locale` (language for the translation e.g. 'en' or 'de'). Those fields are unique together (only one translation per language) using `@UniqueEntity(fields={"content", "locale"})`. My `ArticleTranslations` are persisted by using `cascade={"persist"}` on the `Article` class (my article form has 1 default translation which needs to be added - so there is atleast 1 translation available).

So what I did notice is, that on `dev` mode everything works like a charm. No issues at all. But whenever I switch to `prod` mode the first form submission is ok. However on the 2nd submission the `@UniqueEntity(fields={"content", "locale"})` fails. When you clear the cache after that `php bin/console cache:clear` it suddenly works for **one time**. The 2nd one fails again.

I did debug the `UniqueEntityValidator` and did indeed notice some strange behavior. The data itself is always the same:
- One ArticleTranslation class with id = NULL (because it is a new object), locale = 'de' and the Article from the relation
- The Article itself also has id = NULL (because it is also new, they are both created at the same time)

However the `findBy` method (used by the validator) seems to be different at the 2nd submission. I logged my SQL queries and did notice the following:
```
//First submission = OK
SELECT t0.id AS id_1, t0.title AS title_2, t0.body AS body_3, t0.locale AS locale_4, t0.created_at AS created_at_5, t0.updated_at AS updated_at_6, t0.article_id AS article_id_7, t0.created_by_id AS created_by_id_8, t0.updated_by_id AS updated_by_id_9 FROM article_translation t0 WHERE t0.article_id = NULL AND t0.locale = 'de'
```
Here we notice that the WHERE is correct `WHERE t0.article_id = NULL AND t0.locale = 'de'` (no result found => Unique passes)
This changes on the second submission though.

```
//Second submission = FAIL
SELECT t0.id AS id_1, t0.title AS title_2, t0.body AS body_3, t0.locale AS locale_4, t0.created_at AS created_at_5, t0.updated_at AS updated_at_6, t0.article_id AS article_id_7, t0.created_by_id AS created_by_id_8, t0.updated_by_id AS updated_by_id_9 FROM article_translation t0 WHERE t0.article_id = 1 AND t0.locale = 'de'
```
with the WHERE beeing suddenly `WHERE t0.article_id = 1 AND t0.locale = 'de'` (even though the Article ID is still NULL in the data).

Again, after clearing the cache it works once. I really have no idea whats causing that and have a hard time to find the issue. Also as mentioned before in `dev` mode everything works correct (so maybe it is a cache related?)

**How to reproduce**
Reproduce example: https://github.com/herbyxxx/issue_40832

**Possible Solution**
Temporary solution would be to use a custom repositoryMethod using that option in the UniqueEntity. And provide your own method to check uniqueness.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by herbyxxx** [comment]
@xabbuh thanks for your answer, I was able to reproduce it in a small application: https://github.com/herbyxxx/issue_40832

it seems to be related to the `InhertianceMapping` it was working fine before adding it

**Comment by herbyxxx** [comment]
@xabbuh Hi, I already provided my feedback. Can you please remove the label and have a look into it? Thanks.

**Comment by xabbuh** [comment]
Thank you for providing the example application. I looked into it and this looks related to what happens under the hood in Doctrine. The input that is passed to it is the same in both environments. But as you already noticed the executed query is different. This seems to be related to the difference in how class metadata are handled in these environments. I don't know how easy it would be to fix this in Doctrine itself, but I guess I would work around this in your application by not applying the `UniqueEntity` constraint when it's input is not yet persisted in the database.

In any case, there is nothing we can do in Symfony about this. That's why I am going to close here. Thank you for understanding.
