### ISSUE TITLE
Bootstrap 5 Form Theme Release Date

### ISSUE THREAD

**Issue by dd2424** [symfony/symfony#40847]
Hi all,
Is there a release date for the new Bootstrap 5 form theme with Symfony?
Usually how long does it take to appear in the Symfony doc after a new Bootstrap version?
(sorry for my English)
[https://symfony.com/doc/current/form/form_themes.html#symfony-built-in-form-themes](https://symfony.com/doc/current/form/form_themes.html#symfony-built-in-form-themes)

**Comment by maxhelias** [comment]
See : https://github.com/symfony/symfony/pull/39157

**Comment by dd2424** [comment]
thx
