### ISSUE TITLE
Cannot autowire argument $authenticationUtils of "App\Controller\UserAuthSecurityController::login()": it references class "Symfony\Component\Security\Http\Authentication\AuthenticationUtils" but no such service exists.

### ISSUE THREAD

**Issue by alva2409** [symfony/symfony#40854]
**Symfony version(s) affected**: 5.2.6

AuthenticationUtils exists, but not show in services list

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
