### ISSUE TITLE
[5.3 beta1][Routing] Unknown property on i18n routes (@Route)

### ISSUE THREAD

**Issue by COil** [symfony/symfony#40860]
**Symfony version(s) affected**: 5.3.0 beta1

**Description**

I tried to update my blog to 5.3 beta1 (current version 5.2.6) and I get the following error : 

> Unknown property "en" on annotation "Symfony\Component\Routing\Annotation\Route" in /Users/coil/Sites/strangebuzz.com/config/routes/../../src/Controller/ (which is being imported from "/Users/coil/Sites/strangebuzz.com/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled.

**How to reproduce**

The error seems to come from my i18n routes, for example:

     use Symfony\Component\Routing\Annotation\Route;
    
    /**
     * App generic actions and locales root handling.
     */
    final class AppController extends AbstractController
    {
        /**
         * @Route({"en": "/en", "fr": "/fr"}, name="homepage")
         *
         * @param array<string,int> $goals
         */
    public function homepage(string $_locale, array $goals, ArticleRepository $articleRepository): Response
    {

Where we have the "en" parameter that is pointed out by the error message.

**Possible Solution**

**Additional context**

* PHP 7.4.13

Route.php
```
    if (!method_exists($this, $method)) {
                throw new \BadMethodCallException(sprintf('Unknown property "%s" on annotation "%s".', $key, static::class));
    }
```

**Comment by derrabus** [comment]
Can you test #40767 please?

**Comment by COil** [comment]
> Can you test #40767 please?

Hello @derrabus, it's OK. 👍

**Comment by COil** [comment]
I had to fix one of my controller : 

> [Syntax Error] Expected Positional arguments after named arguments is not allowed, got end of string in class App\Controller\GameController in /Users/coil/Sites/strangebuzz.com/config/routes/../../src/Controller/ (which is being imported from "/Users/coil/Sites/strangebuzz.com/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled.

```
/**
 * @Route(name="game_", {"en": "/{_locale}/games", "fr": "/{_locale}/jeux"}, requirements={"_locale"="%locales_requirements%"})
 */
```

to put `name="game_"` after the i18n parameters and now it's OK.

**Comment by COil** [comment]
Hello, I am closing this. This OK with 5.3 beta3. Thanks.
