### ISSUE TITLE
Login throttling: error message is not translated

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony#40863]
**Symfony version(s) affected**: 5.3.0@beta1

**Description**
When logging in with `fr` locale, I'm getting the following error message:

> Too many failed login attempts, please try again in 1 minute.

While I'm expecting a translated error message.

**How to reproduce**
Add rate limiter to security.yaml & login using a different locale than `en`.

**Possible Solution**
Add translations in security translation files.

**Additional context**
I think the error message comes from here: https://github.com/symfony/symfony/blob/v5.3.0-BETA1/src/Symfony/Component/Security/Core/Exception/TooManyLoginAttemptsAuthenticationException.php#L44

The "later" part seems already translated, so I think messages handling "minute" & "minutes" should be added.

**Comment by ro0NL** [comment]
Variables should be extracted to getMessageData IIUC

edit: no my bad, actual variable values arent included, the translations are missing: https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/Security/Core/Resources/translations/security.en.xlf#L65-L67

**Comment by chalasr** [comment]
Thanks for the report. PR welcome.

**Comment by derrabus** [comment]
I think this is not just about a missing translation. The problem is that a message key is generated that makes assumptions on pluralizations. Instead, we should use a message key like this one:

https://github.com/symfony/symfony/blob/be384cf221d7915a6768d0dd81630fa42cb141d0/src/Symfony/Component/Validator/Constraints/Choice.php#L43-L44

**Comment by wouterj** [comment]
Contrary to the Validator component, we do not require the Translation component to be registered and enabled in Security. So the translation keys must be human readable without message formatter.

**Comment by derrabus** [comment]
Thanks for the explanation, @wouterj. In that case it's really just about adding the translations.

**Comment by javiereguiluz** [comment]
Maybe we can't translate these messages then. They would only be correct for languages with same pluralization rules as English, right?

**Comment by stof** [comment]
The translator does not care about the content of the key to decide whether it should apply pluralization or no.

**Comment by fabpot** [comment]
Note that we will have issues with languages where plural is more complex.

**Comment by mhujer** [comment]
It is also problem in Czech (discovered it when working on https://github.com/symfony/symfony/issues/41040)
