### ISSUE TITLE
AbstractGuardAuthenticator not implementing the right interface (AuthenticatorInterface) causing AuthenticatorManager::executeAuthenticator() to throw an error ?!

### ISSUE THREAD

**Issue by pierrejeunejean** [symfony/symfony#40869]
**Symfony version(s) affected**: 5.2.6

**Description**
Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator(): Argument #1 ($authenticator) must be of type Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface
but Symfony\Component\Security\Guard\AbstractGuardAuthenticator implements Symfony\Component\Security\Guard\AuthenticatorInterface. 

The class AbstractGuardAuthenticator is extended used by TokenAuthenticator as explained here https://symfony.com/doc/current/security/guard_authentication.html#manually-authenticating-a-user or by LoginFormAuthenticator as described here https://symfony.com/doc/current/security/form_login_setup.html.

So when using - extending - the class AbstractGuardAuthenticator to create an Authentication System with Guard, an error is throned during the login or registration since implementations of AbstractGuardAuthenticator does not implement the correct AuthenticatorInterface.

We get an error such as : 

Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator(): Argument #1 ($authenticator) must be of type Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface, App\Security\LoginFormAuthenticator given, called in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-http/Authentication/AuthenticatorManager.php on line 145

TypeError
in vendor/symfony/security-http/Authentication/AuthenticatorManager.php (line 158)
in vendor/symfony/security-http/Authentication/AuthenticatorManager.php -> executeAuthenticator (line 145)
in vendor/symfony/security-http/Authentication/AuthenticatorManager.php -> executeAuthenticators (line 125)
in vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php -> authenticateRequest (line 42)
in vendor/symfony/security-bundle/Debug/WrappedLazyListener.php -> authenticate (line 49)
in vendor/symfony/security-http/Firewall/AbstractListener.php -> authenticate (line 26)
in vendor/symfony/security-bundle/Security/LazyFirewallContext.php -> __invoke (line 60)
in vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php -> __invoke (line 59)
in vendor/symfony/security-http/Firewall.php -> callListeners (line 86)
in vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 117)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 230)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 59)
in vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 151)
in vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 133)
in vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 79)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 195)
Kernel->handle(object(Request))
in public/index.php (line 25)
    Request::setTrustedHosts([$trustedHosts]);}$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);$request = Request::createFromGlobals();$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);

**How to reproduce**
See https://symfony.com/doc/current/security/guard_authentication.html#manually-authenticating-a-user 
or see https://symfony.com/doc/current/security/form_login_setup.html
or use command : php bin/console make:auth

**Possible Solution**

**Additional context**

**Comment by pierrejeunejean** [comment]
As I said previously on this post, I had yesterday a similar error throwed in my RegistrationController, that I can't reproduce today, maybe since I made a composer update in between.

But it was in that method call:

            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $authenticator,
                'main' // firewall name in security.yaml
            );

with var $authenticator being of class LoginFormAuthenticator that extends AbstractFormLoginAuthenticator  that extends AbstractGuardAuthenticator that implements Symfony\Component\Security\Guard\AuthenticatorInterface

The authenticateUserAndHandleSuccess was expecting $authenticator argument to implements Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface and not Symfony\Component\Security\Guard\AuthenticatorInterface.

<?php

namespace App\Controller;

use App\Entity\GardenOwner;
use App\Entity\Gardener;
use App\Entity\KitchenGarden;
use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Security\LoginFormAuthenticator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;

class RegistrationController extends AbstractController
{
    /**
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @param GuardAuthenticatorHandler $guardHandler
     * @param LoginFormAuthenticator $authenticator
     * @return Response
     * @todo move the logic to a service & add translation for the setting of the garden name
     * @Route("/register", name="app_register")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $authenticator): Response
    {
        $form = $this->createForm(RegistrationFormType::class);
        $form->handleRequest($request);

        //dd($form->all());

        if ($form->isSubmitted() && $form->isValid()) {
            $user = new User();
            $userForm = $form->get('user');
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $userForm->get('password')->getData()
                )
            );
            $user->setEmail($userForm->get('email')->getData());
            $user->setRoles([User::GARDENER_ROLE, User::GARDEN_OWNER_ROLE]);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);

            // Custom code here

            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $authenticator,
                'main' // firewall name in security.yaml
            );
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}

**Comment by pierrejeunejean** [comment]
As I said previously on this post, I had yesterday a similar error throwed in my RegistrationController, that I can't reproduce today, maybe since I made a composer update in between.

But it was in that method call:

        return $guardHandler->authenticateUserAndHandleSuccess(
            $user,
            $request,
            $authenticator,
            'main' // firewall name in security.yaml
        );
with var $authenticator being of class LoginFormAuthenticator that extends AbstractFormLoginAuthenticator that extends AbstractGuardAuthenticator that implements Symfony\Component\Security\Guard\AuthenticatorInterface

The authenticateUserAndHandleSuccess was expecting $authenticator argument to implements Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface and not Symfony\Component\Security\Guard\AuthenticatorInterface.

That seems to be fixed.

```
<?php

namespace App\Controller;

use App\Entity\GardenOwner;
use App\Entity\Gardener;
use App\Entity\KitchenGarden;
use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Security\LoginFormAuthenticator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;

class RegistrationController extends AbstractController
{
    /**
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @param GuardAuthenticatorHandler $guardHandler
     * @param LoginFormAuthenticator $authenticator
     * @return Response
     * @todo move the logic to a service & add translation for the setting of the garden name
     * @Route("/register", name="app_register")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $authenticator): Response
    {
        $form = $this->createForm(RegistrationFormType::class);
        $form->handleRequest($request);

        //dd($form->all());

        if ($form->isSubmitted() && $form->isValid()) {
            $user = new User();
            $userForm = $form->get('user');
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $userForm->get('password')->getData()
                )
            );
            $user->setEmail($userForm->get('email')->getData());
            $user->setRoles([User::GARDENER_ROLE, User::GARDEN_OWNER_ROLE]);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);

            // Custom code here

            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $authenticator,
                'main' // firewall name in security.yaml
            );
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}

```

**Comment by pierrejeunejean** [comment]
config/packages/security.yaml
```
security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            custom_authenticator: App\Security\LoginFormAuthenticator
                # where to redirect after logout
                # target: app_any_route
            login_throttling:
                max_attempts: 3

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

```

App\Security\LoginFormAuthenticator

```
<?php

// src/Security/LoginFormAuthenticator.php
namespace App\Security;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\CustomUserMessageAuthenticationException;
use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Csrf\CsrfToken;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator;
use Symfony\Component\Security\Guard\PasswordAuthenticatedInterface;
use Symfony\Component\Security\Http\Util\TargetPathTrait;

class LoginFormAuthenticator extends AbstractFormLoginAuthenticator implements PasswordAuthenticatedInterface
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';

    private $entityManager;
    private $urlGenerator;
    private $csrfTokenManager;
    private $passwordEncoder;

    public function __construct(EntityManagerInterface $entityManager, UrlGeneratorInterface $urlGenerator, CsrfTokenManagerInterface $csrfTokenManager, UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->entityManager = $entityManager;
        $this->urlGenerator = $urlGenerator;
        $this->csrfTokenManager = $csrfTokenManager;
        $this->passwordEncoder = $passwordEncoder;
    }

    public function supports(Request $request)
    {
        return self::LOGIN_ROUTE === $request->attributes->get('_route')
            && $request->isMethod('POST');
    }

    public function getCredentials(Request $request)
{
    $credentials = [
        'email' => $request->request->get('email'),
        'password' => $request->request->get('password'),
        'csrf_token' => $request->request->get('_csrf_token'),
    ];
    $request->getSession()->set(
        Security::LAST_USERNAME,
        $credentials['email']
    );

    return $credentials;
}

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $token = new CsrfToken('authenticate', $credentials['csrf_token']);
        if (!$this->csrfTokenManager->isTokenValid($token)) {
            throw new InvalidCsrfTokenException();
        }

        $user = $this->entityManager->getRepository(User::class)->findOneBy(['email' => $credentials['email']]);

        if (!$user) {
            // fail authentication with a custom error
            throw new CustomUserMessageAuthenticationException('Email could not be found.');
        }

        return $user;
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
        return $this->passwordEncoder->isPasswordValid($user, $credentials['password']);
    }

    /**
     * Used to upgrade (rehash) the user's password automatically over time.
     */
    public function getPassword($credentials): ?string
    {
        return $credentials['password'];
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
            return new RedirectResponse($targetPath);
        }

        // For example : return new RedirectResponse($this->urlGenerator->generate('some_route'));
        return new RedirectResponse($this->urlGenerator->generate('homepage'));
    }

    protected function getLoginUrl()
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}

```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by pierrejeunejean** [comment]
This fixes the login form. (but not the registration controller yet)
The classe LoginFormAuthenticator extend Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator
and not Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator anymore.
The authenticate(Request $request): PassportInterface method is implemented 

And the following methods are removed: public function getCredentials(Request $request), public function getUser($credentials, UserProviderInterface $userProvider), public function checkCredentials($credentials, UserInterface $user)

```

// src/Security/LoginFormAuthenticator.php

namespace App\Security;

use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\PasswordAuthenticatedInterface;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;
use Symfony\Component\Security\Http\Util\TargetPathTrait;

class LoginFormAuthenticator extends AbstractLoginFormAuthenticator implements PasswordAuthenticatedInterface
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';

    private UrlGeneratorInterface $urlGenerator;
    private UserPasswordEncoderInterface $passwordEncoder;
    private UserRepository $userRepository;

    public function __construct(UrlGeneratorInterface $urlGenerator, UserRepository $userRepository)
    {
        $this->urlGenerator = $urlGenerator;
        $this->userRepository = $userRepository;
    }

    public function supports(Request $request): bool
    {
        return self::LOGIN_ROUTE === $request->attributes->get('_route')
            && $request->isMethod('POST');
    }

    /**
     * Create a passport for the current request. Here a passport containing the user, the
     * presented password and the CSRF token value.
     * @param Request $request
     * @return PassportInterface
     */
    public function authenticate(Request $request): PassportInterface
    {
        return new Passport(
            new UserBadge($request->request->get('email'), function ($userIdentifier) {
                return $this->userRepository->findOneBy(['email' => $userIdentifier]);
            }),
            new PasswordCredentials($request->request->get('password'))
        );
    }

    /**
     * Used to upgrade (rehash) the user's password automatically over time.
     */
    public function getPassword($credentials): ?string
    {
        return $credentials['password'];
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?RedirectResponse {
        if ($targetPath = $this->getTargetPath($request->getSession(), $firewallName)) {
            return new RedirectResponse($targetPath);
        }
        return new RedirectResponse($this->urlGenerator->generate('homepage'));
    }

    protected function getLoginUrl(Request $request): string
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}

```

**Comment by pierrejeunejean** [comment]
In doc https://symfony.com/doc/current/security/guard_authentication.html we have : 

```

class RegistrationController extends AbstractController
{
    public function register(LoginFormAuthenticator $authenticator, GuardAuthenticatorHandler $guardHandler, Request $request)
    {
        // ...

        // after validating the user and saving them to the database
        // authenticate the user and use onAuthenticationSuccess on the authenticator
        return $guardHandler->authenticateUserAndHandleSuccess(
            $user,          // the User object you just created
            $request,
            $authenticator, // authenticator whose onAuthenticationSuccess you want to use
            'main'          // the name of your firewall in security.yaml
        );
    }
}


```

This cause the error : 

Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator::createAuthenticatedToken(): Argument #1 ($passport) must be of type Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface, App\Entity\User given, called in /Users/pierrejeunejean/PhpstormProjects/cropside.com/src/Controller/RegistrationController.php on line 48

The method : public function handleAuthenticationSuccess(TokenInterface $token, Request $request, AuthenticatorInterface $guardAuthenticator, string $providerKey): ?Response of the class: Symfony\Component\Security\Guard\GuardAuthenticatorHandler still expects its third argument to implements Symfony\Component\Security\Guard\AuthenticatorInterface. Here the the guardAuthenticator is a LoginFormAuthenticator object. 

But since App\Security\LoginFormAuthenticator extends now Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator it also implements Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface

We have 2 interfaces called AuthenticatorInterface, one in the domain Symfony\Component\Security\Http and one in the domain Symfony\Component\Security\Guard.

**Comment by pierrejeunejean** [comment]
@xabbuh here is the code
[code-example.zip](https://github.com/symfony/symfony/files/6344742/code-example.zip)

**Comment by pierrejeunejean** [comment]
@xabbuh here is the code (the example)
code-example.zip
see App\Security\LoginFormAuthenticator.php and App\Controller\RegistrationController.php
[Uploading code-example.zip…]()

**Comment by pierrejeunejean** [comment]
I also thought that setting enable_authenticator_manager to false in config\security.yaml  

```
security:
    enable_authenticator_manager: false
```
would provide a backward compatibility for the security bundle ?!
-> It feels like now I'm force to use the new Authenticator-based Security, since the error is not clear ?
Though, I don't know if this remark is relevant ?!

But when I set enable_authenticator_manager: false, I get the following error : 
```

Custom authenticators are not supported when "security.enable_authenticator_manager" is not set to true.
Exception Stack Trace
LogicException
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-bundle/DependencyInjection/Security/Factory/CustomAuthenticatorFactory.php (line 28)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php -> create (line 571)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php -> createAuthenticationListeners (line 455)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php -> createFirewall (line 271)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php -> createFirewalls (line 162)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php -> load (line 76)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php -> process (line 39)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/dependency-injection/Compiler/Compiler.php -> process (line 91)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/dependency-injection/ContainerBuilder.php -> compile (line 736)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/http-kernel/Kernel.php -> compile (line 541)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/http-kernel/Kernel.php -> initializeContainer (line 780)
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/vendor/symfony/http-kernel/Kernel.php -> preBoot (line 183)
Kernel->handle(object(Request))
in /Users/pierrejeunejean/PhpstormProjects/cropside.com/public/index.php (line 25)
    Request::setTrustedHosts([$trustedHosts]);}$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);$request = Request::createFromGlobals();$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);
```

**Comment by wouterj** [comment]
You are confusing the [new authenticators supported by `enable_authenticator_manager`](https://symfony.com/doc/current/security/experimental_authenticators.html), with [Guard authenticators](https://symfony.com/doc/current/security/guard_authentication.html) (which is a concept of the legacy manager).

So you either have to use the `Symfony\Component\Security\Guard\...` classes/interfaces with `guard` (supported for both `enable_authenticator_manager` `true`/`false`), or you have to use the `Symfony\Component\Security\Http\...` classes/interfaces with `custom_authenticators` (only supported by `enable_authenticator_manager: true`).

I'm sorry for this confusion, we just couldn't come up with a better name than "authenticator" for this concept.

**Comment by nicosapp** [comment]
Hello, 
I try to implement a custom "checkCredentials" for the AbstractLoginFormAuthenticator but as mentionned above, it is no longer in this class.

How can I do?

Thanks!

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* GitHub Discussions: https://github.com/symfony/symfony/discussions
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
