### ISSUE TITLE
Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id)

### ISSUE THREAD

**Issue by williamdes** [symfony/symfony#40870]
Update log for today
```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 3 updates, 0 removals
  - Upgrading symfony/cache-contracts (v2.2.0 => v2.4.0)
  - Upgrading symfony/service-contracts (v2.2.0 => v2.4.0)
  - Upgrading symfony/translation-contracts (v2.3.0 => v2.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Downloading symfony/service-contracts (v2.4.0)
  - Downloading symfony/cache-contracts (v2.4.0)
  - Downloading symfony/translation-contracts (v2.4.0)
  - Upgrading symfony/service-contracts (v2.2.0 => v2.4.0): Extracting archive
  - Upgrading symfony/cache-contracts (v2.2.0 => v2.4.0): Extracting archive
  - Upgrading symfony/translation-contracts (v2.3.0 => v2.4.0): Extracting archive
```

```
Fatal error: Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in vendor/symfony/dependency-injection/ServiceLocator.php on line 46
```

**Possible Workaround**
Use a lower version: `composer require symfony/service-contracts:2.2.0`

**Additional context**
breaks phpMyAdmin

**Comment by stof** [comment]
which versions of PHP, `symfony/service-contracts`, `symfony/dependency-injection` and `psr/container` do you have in your project ?

**Comment by williamdes** [comment]
> which versions of PHP, `symfony/service-contracts`, `symfony/dependency-injection` and `psr/container` do you have in your project ?

As shown above  `symfony/service-contracts` is at `v2.4.0`
And `symfony/dependency-injection` is at `v4.4.21`
and `psr/container` is at `1.1.1`

All deps: https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/composer.json

**Comment by stof** [comment]
@williamdes there's definitely something wrong in your setup, because `psr/container` 1.1.1 has a string typehint in the argument while your error message does not mention it: https://github.com/php-fig/container/blob/8622567409010282b7aeebe4bb841fe98b58dcaf/src/ContainerInterface.php#L35

could it be that you have ext-psr installed on your system ? then, that would be the one defining the interface rather than loading the one installed through composer (and ext-psr is outdated, shipping the 1.0 interfaces)

**Comment by williamdes** [comment]
Well one thing I do not understand is, I removed my composer folder and this is the log and the error seems to be in your lib:
```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading symfony/service-contracts (v2.2.0 => v2.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 91 installs, 0 updates, 0 removals
  - Downloading psr/cache (1.0.1)
  - Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
  - Installing squizlabs/php_codesniffer (3.6.0): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.1): Extracting archive
  - Installing phpstan/phpstan (0.12.83): Extracting archive
  - Installing phpstan/extension-installer (1.1.0): Extracting archive
  - Installing dasprid/enum (1.0.3): Extracting archive
  - Installing google/recaptcha (1.2.4): Extracting archive
  - Installing nikic/fast-route (v1.3.0): Extracting archive
  - Installing paragonie/constant_time_encoding (v2.4.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.22.1): Extracting archive
  - Installing symfony/process (v5.2.4): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.22.1): Extracting archive
  - Installing php-webdriver/webdriver (1.10.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing phpstan/phpdoc-parser (0.4.9): Extracting archive
  - Installing slevomat/coding-standard (6.4.1): Extracting archive
  - Installing doctrine/coding-standard (8.2.1): Extracting archive
  - Installing phpmyadmin/coding-standard (2.1.1): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing symfony/service-contracts (v2.4.0): Extracting archive
  - Installing symfony/var-exporter (v5.2.4): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/cache-contracts (v2.4.0): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/cache (v5.2.6): Extracting archive
  - Installing symfony/expression-language (v4.4.20): Extracting archive
  - Installing phpmyadmin/motranslator (5.2.0): Extracting archive
  - Installing phpmyadmin/shapefile (2.1): Extracting archive
  - Installing phpmyadmin/sql-parser (5.4.2): Extracting archive
  - Installing twig/twig (v3.3.0): Extracting archive
  - Installing phpmyadmin/twig-i18n-extension (v3.0.0): Extracting archive
  - Installing phpseclib/phpseclib (2.0.31): Extracting archive
  - Installing phpstan/phpstan-phpunit (0.12.18): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.2): Extracting archive
  - Installing sebastian/exporter (4.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing nikic/php-parser (v4.10.4): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.6): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.13.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.1): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.5.4): Extracting archive
  - Installing pragmarx/google2fa (8.0.0): Extracting archive
  - Installing bacon/bacon-qr-code (2.0.3): Extracting archive
  - Installing pragmarx/google2fa-qrcode (v1.0.3): Extracting archive
  - Installing samyoul/u2f-php-server (v1.1.4): Extracting archive
  - Installing symfony/filesystem (v5.2.6): Extracting archive
  - Installing symfony/config (v4.4.20): Extracting archive
  - Installing symfony/dependency-injection (v4.4.21): Extracting archive
  - Installing symfony/finder (v4.4.20): Extracting archive
  - Installing symfony/polyfill-php73 (v1.22.1): Extracting archive
  - Installing symfony/translation-contracts (v2.4.0): Extracting archive
  - Installing symfony/twig-bridge (v4.4.21): Extracting archive
  - Installing tecnickcom/tcpdf (6.4.1): Extracting archive
  - Installing webmozart/path-util (2.3.0): Extracting archive
  - Installing symfony/console (v4.4.21): Extracting archive
  - Installing openlss/lib-array2xml (1.0.0): Extracting archive
  - Installing netresearch/jsonmapper (v2.1.0): Extracting archive
  - Installing felixfbecker/language-server-protocol (1.5.1): Extracting archive
  - Installing felixfbecker/advanced-json-rpc (v3.2.0): Extracting archive
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
  - Installing composer/xdebug-handler (1.4.6): Extracting archive
  - Installing composer/semver (3.2.4): Extracting archive
  - Installing amphp/amp (v2.5.2): Extracting archive
  - Installing amphp/byte-stream (v1.8.1): Extracting archive
  - Installing vimeo/psalm (4.7.0): Extracting archive
  - Installing williamdes/mariadb-mysql-kbs (1.2.12): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
52 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../phpmyadmin/coding-standard,../../slevomat/coding-standard
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-phpunit: installed
```

```
cat vendor/psr/container/src/ContainerInterface.php 
<?php

declare(strict_types=1);

namespace Psr\Container;

/**
 * Describes the interface of a container that exposes methods to read its entries.
 */
interface ContainerInterface
{
    /**
     * Finds an entry of the container by its identifier and returns it.
     *
     * @param string $id Identifier of the entry to look for.
     *
     * @throws NotFoundExceptionInterface  No entry was found for **this** identifier.
     * @throws ContainerExceptionInterface Error while retrieving the entry.
     *
     * @return mixed Entry.
     */
    public function get(string $id);

    /**
     * Returns true if the container can return an entry for the given identifier.
     * Returns false otherwise.
     *
     * `has($id)` returning true does not mean that `get($id)` will not throw an exception.
     * It does however mean that `get($id)` will not throw a `NotFoundExceptionInterface`.
     *
     * @param string $id Identifier of the entry to look for.
     *
     * @return bool
     */
    public function has(string $id);
}
```
And: `cat vendor/symfony/dependency-injection/ServiceLocator.php | grep -F "function get("`

The error still is:
`Fatal error: Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in vendor/symfony/dependency-injection/ServiceLocator.php on line 46`

But from the code is seems to be the other way around

**Comment by stof** [comment]
@williamdes see my comment about ext-psr. I strongly suspect that the definition of the `Psr\Container\ContainerInterface` on your system is **not** the one from `vendor/psr/container/src/ContainerInterface.php`

Side note, the implementation of the `Symfony\Component\DependencyInjection\ServiceLocator::has` is in `vendor/symfony/service-contracts/ServiceLocatorTrait.php`

**Comment by williamdes** [comment]
> Side note, the implementation of the Symfony\Component\DependencyInjection\ServiceLocator::has is in vendor/symfony/service-contracts/ServiceLocatorTrait.php

yeah, the signature has the right type in this trait file

> see my comment about ext-psr. I strongly suspect that the definition of the Psr\Container\ContainerInterface on your system is not the one from vendor/psr/container/src/ContainerInterface.php

You can see the contents on my message posted above seem to be the right one


> could it be that you have ext-psr installed on your system ? then, that would be the one defining the interface rather than loading the one installed through composer (and ext-psr is outdated, shipping the 1.0 interfaces)

How could I check that ?
The apt `php-psr` is not installed
And I upgraded my global composer installation

I am very puzzled because I see no way that could happen 🤔 

But that seems just like: https://github.com/sebastianbergmann/phpunit/issues/4097#issuecomment-633319112

We require the autoload like everybody does: https://github.com/phpmyadmin/phpmyadmin/blob/90778eecf723a20ec8f42fbfe3ea6891fe9f97c9/libraries/common.inc.php#L96

**Comment by stof** [comment]
@williamdes if PHP reports `Psr\Container\ContainerInterface::has($id)` in the error message, it means that this interface is **not** loaded from your `vendor/psr/container/src/ContainerInterface.php` file (as that one has the right typehint).

So try debugging where the interface is defined (with `(new ReflectionClass('Psr\Container\ContainerInterface'))->getFilename()` for instance).

Other idea: maybe your PHP-FPM uses preloading, while sharing the same config for multiple projects (and so preloading the interface from a different project installed on your system) ?

**Comment by williamdes** [comment]
Hey have a look to https://github.com/symfony/dependency-injection/blob/v4.4.21/ContainerInterface.php#L63

The code is right, no?

**Comment by stof** [comment]
This is **not** the interface that your error message complains about.

ServiceLocator does not even implement that interface.

**Comment by williamdes** [comment]
> This is **not** the interface that your error message complains about.
> 
> ServiceLocator does not even implement that interface.

Sorry, I got distracted.

`the filename of the file in which the class has been defined. If the class is defined in the PHP core or in a PHP extension, FALSE is returned.`

It returns false: `(new ReflectionClass('Psr\Container\ContainerInterface'))->getFilename()`

About FPM I have configured nothing and use docker: https://github.com/wdesportes/phpmyadmin-local-setup/blob/8c9570b613702e6b6b93860505bc9e9c063180ff/docker-compose.yml#L324

**Comment by derrabus** [comment]
👀 

https://github.com/devilbox/docker-php-fpm/blob/282c019eb37dda7a85aa21bee532f736383d0901/Dockerfiles/mods/Dockerfile-8.0#L417-L425

**Comment by stof** [comment]
if it returns false, it means that the class comes from an extension

**Comment by williamdes** [comment]
> https://github.com/devilbox/docker-php-fpm/blob/282c019eb37dda7a85aa21bee532f736383d0901/Dockerfiles/mods/Dockerfile-8.0#L417-L425

Thank you @derrabus !!
`rm /usr/local/etc/php/conf.d/docker-php-ext-psr.ini` in the fpm container and restarted the fpm container

Now, how can this be fixed without having to remove the PSR installed extension ?

**Comment by derrabus** [comment]
> Now, how can this be fixed without having to remove the PSR installed extension ?

It cannot. This is the fix. Don't use that extension.

**Comment by derrabus** [comment]
Closing as this is not a Symfony issue.

**Comment by williamdes** [comment]
Thank you for the support !

The alternative fix is `pecl install psr` that will update the extension, then restart fpm
https://pecl.php.net/package/psr was updated to 1.1.0 the 10th of this month so the next docker builds will have it into it.

**Comment by derrabus** [comment]
@williamdes The package was updated to match `psr/container` 1.1.1 all right, but my recommendation is still to not use that extension at all. You don't gain anything from using it but hard-to-debug problems like this one.

**Comment by nicolas-grekas** [comment]
What about making a package of ours "conflict" with "ext-psr"?
Eg all contracts that have a corresponding PSR?

**Comment by williamdes** [comment]
> @williamdes The package was updated to match `psr/container` 1.1.1 all right, but my recommendation is still to not use that extension at all. You don't gain anything from using it but hard-to-debug problems like this one.

For sure, but I am not the one building the massive and perfectly working devilbox images

I learned today that there is some possibility that an extension provides the classes you are auto-loading and that it creates more bugs

Conclusion: be an alpine linux user, have nothing installed 😄 

> What about making a package of ours "conflict" with "ext-psr"?
Eg all contracts that have a corresponding PSR?

Could be a good idea, that will help some people
Not be because I have a local composer and a local php different from the container one, bad idea but 🤫

**Comment by nicolas-grekas** [comment]
@williamdes can you maybe open an issue or a PR to remove the extension from devilbox' images?

**Comment by williamdes** [comment]
> @williamdes can you maybe open an issue or a PR to remove the extension from devilbox' images?

Done: https://github.com/devilbox/docker-php-fpm/issues/201

**Comment by jbboehr** [comment]
As the author of the PSR extension, I would like to apologize for the bit of trouble my extension has caused. At the time I first authored it, I expected that B/C breaks to the PSRs would be published under a new PSR in a different namespace. It appears PHP-FIG has recently amended their bylaws and allowed PSRs to be upgraded in place. This is a huge compatibility nightmare for me.

It is meant as a specialized extension and not intended to be used in general. For example, it allows the phalcon framework to use the PSR interfaces.

I will contact distributions and request they not enable it by default, unless phalcon is also enabled, when I become aware of them doing so.
