### ISSUE TITLE
Error in psr/cache interface

### ISSUE THREAD

**Issue by AleksandrGoriachev** [symfony/symfony#40873]
**Symfony version(s) affected**: 5.2.2

**Description**
We use PHP 7.4.15
During Symfony kernel intialization I receive a "syntax error, unexpected '|', expecting variable (T_VARIABLE)" error in the 
vendor/psr/cache/src/CacheItemInterface.php (line 104).
It looks like the interface is oriented on PHP8 only, because method signature is following:
 public function expiresAfter(int|\DateInterval|null $time);

**How to reproduce**
It's imposible to reproduce the due to kernel error.

**Possible Solution**
Please, check if the interface takes into account not only PHP8 version
![2021-04-19 19_17_29-Postman](https://user-images.githubusercontent.com/31987632/115269401-f3cb4d80-a143-11eb-8ae6-996ed9772124.png)

**Additional context**

**Comment by derrabus** [comment]
You have installed `psr/cache` 2 which requires PHP 8: https://packagist.org/packages/psr/cache#2.0.0

Closing as this is not a Symfony issue.
