### ISSUE TITLE
Fatal error: Interface 'Stringable' not found in vendor/symfony/string/AbstractString.php on line 28

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony#40871]
**Symfony version(s) affected**: 5.2.6

**Description**

Builds for one of my projects started to fail on PHP 7.3 and 7.4 with:

```
Fatal error: Interface 'Stringable' not found in vendor/symfony/string/AbstractString.php on line 28
```

Only `symfony/console` is explicitly included in `composer.json`. It's a command line application and it crashes with the above fatal error when trying to run any command.

**How to reproduce**

Download the following phar and run it on PHP 7.3: https://github.com/jakzal/toolbox/releases/download/v1.45.3/toolbox.phar

**Comment by stof** [comment]
@jakzal are you generating a scoped phar with PHP-Scoper ? If yes, make sure that the scoping logic does not break the polyfill packages.

**Comment by jakzal** [comment]
I have no scoping Logic: https://github.com/jakzal/toolbox/blob/master/scoper.inc.php

**Comment by jakzal** [comment]
I will double check if it isn’t scoped out of the box

**Comment by stof** [comment]
@jakzal that might be the issue: the default logic is "scope everything" IIRC. And so, this might change the Stringable polyfill to a mangled while the usage is kept intact (due to Stringable being detected as a core interface when building the phar).

**Comment by jakzal** [comment]
Indeed, `\Stringable` is scoped by php-scoper. It doesn't seem to be possible to not scope it, but that's not a bug in Symfony. Closing here.

**Comment by stof** [comment]
@jakzal see https://github.com/infection/infection/pull/1471
