### ISSUE TITLE
[RFC] Branching in Symfony 6

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#40887]
### Status Quo

Following the discussion in #37331 we have decided to rename our `master` branch to `5.x`. The main argument was that this model has been tried out successfully on the Twig repository and in fact it has served us well. However, with 5.4 being the last minor version of the 5.x series, the end of the `5.x` branch is approaching and I'd like to take the opportunity to revisit that decision.

### Problems with `5.x`

The `5.x` strategy had one big drawback: We were unable to target 5.3 in version constraints.

* Composer was unable to resolve version constraints like `~5.3.0` and `5.3.*`. Especially when introducing experimental components, we sometimes need the ability to pin a minor version.

  https://github.com/symfony/symfony/blob/d4844ef28f79bec9fe4e2306e4cfc52e219b0cf5/src/Symfony/Component/Notifier/Bridge/Slack/composer.json#L22

* Flex allows us an application to pin all Symfony packages to a certain branch:

  https://github.com/symfony/skeleton/blob/5215ec9738586590ae5ffa62f13aa823e3d090d7/composer.json#L57-L62

  If a developer wanted to try out their application with the latest 5.3 snapshots, the obvious eay to do that would be to change `"symfony": "5.2.*"` into `"symfony": "5.3.*"`. But that did not work for the same reason. A workaround was to use `>=5.3` instead.

### Twig Vs. Symfony

Twig's development process works differently than Symfony's. A new minor releas is tagged when one or more new features have been merged. For bugfixes, a patch release is tagged. Once a new minor version is tagged, the previous minor version is obsolete. The minor version changes often and irregularly. And there is (at least in theory) no upper boundary for the minor version number.

I can totally understand that the `1.x`/`2.x`/`3.x` branches work so well for Twig.

In Symfony however, it's a different story. We do have one branch where we develop the features for the next biannual minor release. And we pretty much know, what the version number will be. The minor version is bumped twice a year only and after a minor release has been tagged, it is maintained in a dedicated branch while the development for the next minor release continues.

To put it in a nutshell: I don't think that the current branching model matches our development model well.

### Proposal

* Next month (exact date is TDB), we will branch out `5.3` to prepare and stabilize the 5.3.0 release.
* Shortly after, we rename `5.x` to `5.4`. Since there won't be a 5.5 release, we don't need a `5.x` branch anymore.
* For Symfony 6, we create a `6.0` branch.
* Around 7 months from now, when 5.4 and 6.0 enter the stabilization phase, we create a `6.1` branch.
* And so on. There won't be a `6.x` branch.

### Advantages

* An upcoming minor release can be targeted properly again.
* When visiting a merged feature PR, GitHub will tell us in which branch it has been merged into, which will match the target version of the feature. Currently, we only see that it was some 5.x version:

  <img width="502" alt="Bildschirmfoto 2021-04-21 um 00 36 38" src="https://user-images.githubusercontent.com/1506493/115472265-d24c8d80-a239-11eb-9e92-212ac924f5ce.png">

* **All** branch names match a version that people can look up on https://symfony.com/releases

**Comment by nicolas-grekas** [comment]
In order to make this happen, we need to make the CI independent from the `.x`-suffix convention.
Right now, we have a few `$TRAVIS_BRANCH = *.x` (or similar) checks there. We might rely on the existing API instead, see either https://flex.symfony.com/versions.json, https://symfony.com/all-versions.json, https://symfony.com/versions.json or https://symfony.com/maintained-versions.json
PR welcome :)

There is another thing we must validate before: retargetting PRs.

Now that GitHub allows renaming branches, creating a new branch might be:
1. merge all PRs that are really for 5.3 into 5.3
2. rename 5.3 to 5.4
2. create branch 5.3

We might also need to decide how we'll use milestones. Using `5.x` as a milestone has the advantage to make it clearer that the PR might not be merged in the very next feature set, but maybe in the one after. If we go with 5.4 instead of 5.x, step 1. above will also require the milestone to be updated. Maybe something for carsonbot? PR welcome also :)

Then, I agree that `5.x` not being compatible with `5.3.*` is a pain that I'd like to remove from our processes.

**Comment by wouterj** [comment]
I fully agree. However, this does require some sort of automation to retarget PRs to the new feature branch. I believe that was one of the reasons to use the 5.x naming last year. However, this automation doesn't have to be very difficult, we might be able to borrow the implementation from https://github.com/laminas/automatic-releases . Optionally, we can also let GitHub do all the work by renaming the branch (https://github.com/github/renaming#renaming-existing-branches), which is arguably a bit more hacky.

Anyway, :100: for `6.0`

**Comment by wouterj** [comment]
>  Right now, we have a few $TRAVIS_BRANCH = *.x (or similar) checks there. We might rely on the existing API instead, see either https://flex.symfony.com/versions.json, https://symfony.com/all-versions.json, https://symfony.com/versions.json or https://symfony.com/maintained-versions.json
PR welcome :)

Let me, based on https://github.com/laminas/automatic-releases, make another suggestion: Use `6.0.x` as the naming strategy
