### ISSUE TITLE
Discussion: Is PHP config in Symfony 6 really the way to go?

### ISSUE THREAD

**Issue by Eydamos** [symfony/symfony#40880]
First of all if this is not the correct place for this discussion please point me to the correct place and I will open the discussion there.

During the Symfony Live Germany event there was a really brief discussion that the core team plans on using php for the configuration. If I also got this correctly it is planned to, over time, remove all other configuration options like xml and yaml. Even though it was mentioned that this is still being discussed in the core team I already found issue #37186 which doesn't look like this is being discussed but this being already decided and actively being worked on. If I didn't get any of this correctly please correct my assumptions.
I'm aware that the core team needs to make decisions on behalf of the community but I think making a breaking change that will affect every single bundle should be discussed with the community.

Let me quickly list the pros and cons that come to my mind based on personal experience and issue #37186. I will then further elaborate on the individual points:

**PHP config:**  
Pros:
* auto-completion
* one less thing to learn

Cons:
* hard to read
* easy to fall into bad habits

**Yaml/XML config:**  
Pros:
* auto-completion
* already familiar with
* high readability
* specifically designed to hold data (config)

Cons:
* less auto-completion possible
* additional resolvers needed to add functionality

Auto completion is also possible for yaml via json-schema and for xml via xsd. Sure classes can not be auto completed but all keys can be and for values that only have fixed set of values this is also possible. json-schema and xsd could be generated by a symfony command based on all active modules and then written into `var/cache/{env}/`. The needed information for this can be gathered by the classes implementing the ConfigurationInterface. Modern IDEs like PhpStorm and Visual Studio Code are capable of reading these files and using them with just a few clicks.

"One less thing to learn" is a poor reason in my opinion as I think that every php developer at some point will come into contact with xml and/or yaml as these are two most common formats for configuration nowadays so most programmers should already be familiar with them. Also the complexity of yaml and xml is very low so "learning" them is not really an issue.

The strongest point in my opinion is the readability. Config is written by humans so it only makes sense that it should be written in a format that is also easy to read for humans. Let's compare php, xml and yaml here:

PHP:
```php
return static function (ContainerConfigurator $container) {
    $container->services()
              ->set('chatter.transport_factory', Transport::class)
                  ->args([tagged_iterator('chatter.transport_factory')])
              ->set('chatter.messenger.chat_handler', MessageHandler::class)
                  ->args([service('chatter.transports')])
              ->tag('messenger.message_handler', ['handles' => ChatMessage::class]);
}
```

XML:
```xml
<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="chatter.transport_factory" class="Symfony\Component\Notifier\Transport">
            <argument type="tagged_iterator" tag="chatter.transport_factory"/>
        </service>

        <service id="chatter.messenger.chat_handler" class="Symfony\Component\Notifier\Messenger\MessageHandler">
            <argument type="service" id="chatter.transports"/>
            <tag name="messenger.message_handler" handles="Symfony\Component\Notifier\Message\ChatMessage"/>
        </service>
    </services>
</container>
```

YAML:
```yaml
services:
    chatter.transport_factory:
        class: Symfony\Component\Notifier\Transport
        arguments:
            - !tagged_iterator chatter.transport_factory

    chatter.messenger.chat_handler:
        class: Symfony\Component\Notifier\Messenger\MessageHandler
        arguments:
            - '@chatter.transports'
        tags:
            -
                name: messenger.message_handler
                handles: Symfony\Component\Notifier\Message\ChatMessage
```

In my opinion xml and php add too much noise around the actual content. Yaml is the currently promoted standard for a good reason. In case of PHP all the `->` as well as all the parenthesis and needed quotes make it much harder to gather information on a quick look. 
Also I think the cheer fact that you add extra indention to the args method call to try to make it more readable is already showing how bad of an idea php config is. Also you have to specifically tell your IDE to not format this file as otherwise the additional indention would be removed.

Last but not least if people start doing config in php they will sooner than later fall into bad habits. If there is an easy and dirty way to do something people will use the easy way. In xml or yaml there is no workaround, people can't programm hacks into config files. Also php config gives opportunity to errors. While xml and yaml rely on the env resolver to get environment variables people might use $_ENV in php config instead of $_SERVER and wonder why part of their values are not filled with the values they are expecting.

To finish this up I don't think it is a good idea to remove functionality from symfony. I would have expected that you would support even more config types like e.g. TOML instead of removing support for widely used formats that have even be promoted for years as the goto standard. Yaml is already a very good standard and forcing every symfony developer to drop a standard to use something else that is less fitting for the task sounds like a bad idea to me.

**Comment by fabpot** [comment]
I would be the first to not support removing YAML/XML options. The PR you are referring to is purely a core choice for a reason: it removes the need for the XML extension.

**Comment by wouterj** [comment]
I'm not aware of any plans to remove any configuration format. https://github.com/symfony/symfony/issues/37186 is about changing the format used in the FrameworkBundle. This doesn't influence any app or third party bundle configuration. In fact, that issue is already applied to Symfony 5.1, released a year ago.

On the other hand, I strongly believe PHP configuration has more benefits than Yaml/XML. The fact that any editor that understands and autocompletes PHP can lint and autocomplete your config is a big one to me. Yes, there are ways to do this in Yaml or XML, but that requires more tools/plugins than the basic PHP editor.

Anyway, that's not a matter of debate, as removing format support is not on any roadmap. And if, and really if, Symfony removes any format in the future, there is always a possibility to maintain the other formats as a community library.

----

Btw, with the introduction of the PHP "configurator" classes for routing, dependency injection and (as of 5.3) extension configuration, I think readability of the PHP format is no longer "hard to read".

**Comment by Eydamos** [comment]
Ok then this was a misunderstanding during the event. It sounded like support for other config formats would be removed over time.

Thanks for the clarification even though I'm sad that symfony components (just like before with xml config) are not following their own recommendations

**Comment by Eydamos** [comment]
> Btw, with the introduction of the PHP "configurator" classes for routing, dependency injection and (as of 5.3) extension configuration, I think readability of the PHP format is no longer "hard to read".

I haven't seen the configurator classes so I don't know how readable this is. I just still have nightmares looking at implementations of ConfigurationInterface which is pretty similar to the php config I have seen so far and I don't think that this configuration definition is readable at all. The indention makes it bearable but still it is very hard to read this and to understand what the definition should consider valid or not.

**Comment by wouterj** [comment]
I'm happy we could resolve the confusion (and thanks a lot for publicly sharing your thoughts!). I think we can safely close this issue then.

> I'm sad that symfony components (just like before with xml config) are not following their own recommendations

Everything has advantages and disadvantages. And their weights unfortunately differ for applications or libraries (like Symfony). E.g. compatibility with as much platforms as possible (i.e. not depending on too many PHP extensions) is important for the Symfony code, but not so much for your application (as your probably also the one managing your platform).

---

> I haven't seen the configurator classes so I don't know how readable this is.

Some examples as a little teaser :wink: 

Routing
```php
// config/routes.php
use App\Controller\BlogApiController;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return function (RoutingConfigurator $routes) {
    $routes->add('api_post_show', '/api/posts/{id}')
        ->controller([BlogApiController::class, 'show'])
        ->methods(['GET', 'HEAD'])
    ;
    $routes->add('api_post_edit', '/api/posts/{id}')
        ->controller([BlogApiController::class, 'edit'])
        ->methods(['PUT'])
    ;
};
```

DI
```php
return static function (ContainerConfigurator $container) {
    $container->services()
        ->set('mailer.mailer', Mailer::class)
            ->args([
                service('mailer.transports'),
                abstract_arg('message bus'),
                service('event_dispatcher')->ignoreOnInvalid(),
            ])
        ->alias('mailer', 'mailer.mailer')
        ->alias(MailerInterface::class, 'mailer.mailer')
    ;
};
```

Extension config
```php
// config/packages/framework.php
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $framework
        ->session()
            // ...
            ->handlerId('session.handler.native_file')
            ->savePath('%kernel.project_dir%/var/sessions/%kernel.environment%')
    ;
};
