### ISSUE TITLE
[Notifier] FailoverTransport does not always pick the first transport

### ISSUE THREAD

**Issue by ngrie** [symfony/symfony#40895]
**Symfony version(s) affected**: >= 5.0

**Description**
Since the `FailoverTransport` extends the `RoundRobinTransport` where the next transport is randomly chosen, this behaviour also applies when configuring failover when sending chat or text messages. The expected behaviour would be: The first transport is always used unless sending fails.

**How to reproduce**
Configure failover transports as stated in the docs: https://symfony.com/doc/current/notifier.html#configure-to-use-failover-or-round-robin-transports

**Possible Solution**
Apply a similar fix as for the Mailer failover transport in #37611

**Comment by jschaedl** [comment]
I can take a look, add some tests first and try to fix this bug.
