### ISSUE TITLE
[Depreciation] CurlHttpClient should implement method HttpClientInterface::withOptions(array $options)

### ISSUE THREAD

**Issue by bastien70** [symfony/symfony#40893]
**Symfony version(s) affected**: 5.2.6

**Description**
On all my pages, I now have the following depreciation: 

> Class "**Symfony\Component\HttpClient\CurlHttpClient**" should implement method "**Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options)**": Returns a new instance of the client with new default options.

![image](https://user-images.githubusercontent.com/53140475/115529272-0dc77600-a293-11eb-87e4-92b5abc927a7.png)

It seems to come from vendor '**symfony/error-handler/DebugClassLoader.php**", line 357

Is it going to be fixed?

**Comment by nicolas-grekas** [comment]
Yes, this is fixed in 5.3, due in 6 weeks.

**Comment by lostfocus** [comment]
Happens in 4.4, too.

**Comment by spipu** [comment]
and also in the TraceableHttpClient too in 4.4

1x: Class "Symfony\Component\HttpClient\TraceableHttpClient" should implement method "Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options)": Returns a new instance of the client with new default options
