### ISSUE TITLE
SMTP is uppercase in Windows php.ini directive

### ISSUE THREAD

**Issue by widhold** [symfony/symfony#40899]
**Symfony version(s) affected**: 5.2, symfony/mailer (v5.2.6)

**Description**
In 
vendor\symfony\mailer\Transport\NativeTransportFactory.php line 42

$host = ini_get('smtp'); ... requests the php.ini SMTP environment variable, which is uppercase under windows:
SMTP string
https://www.php.net/manual/en/mail.configuration.php#ini.smtp
... and throws exception!

**How to reproduce**

**Possible Solution**
check for uppercase SMTP variable name

**Additional context**

**Comment by xabbuh** [comment]
see #40919
