### ISSUE TITLE
Login throttling also takes into action when login in successful several times

### ISSUE THREAD

**Issue by jeroen-hoekstra** [symfony/symfony#40890]
**Symfony version(s) affected**: 5.2.6

**Description**
So we use `login_throttling` with a `max_attempts` set to 3 in our `security.firewalls`. When we login successful and logout again 3 times in 1 minute, the 4th time we want to login again we get the `login_throttling` error message saying "Too many failed login attempts, please try again in 1 minute". We saw this happen in our UI tests using Cypress where we login many times.

According to the docs it says: "One of the best countermeasures to these attacks is called “login throttling”, which denies a user from attempting logins after a certain **number of failed attempts**". In our case they are not failed attempts but still `login_throttling` is taking action.

Is this the expected behavior of `login_throttling`? If so, is there a way that we could make it work only for failed attempts?

**How to reproduce**
See Description

**Comment by MatTheCat** [comment]
@wouterj I see you removed the `onSuccessfulLogin` callback in https://github.com/symfony/symfony/pull/38308 was it intentional?

**Comment by petermanders89** [comment]
As a work around we adjusted the `login_throttling` parameter to a higher number specifically in the test environment.

**Comment by wouterj** [comment]
> @wouterj I see you removed the onSuccessfulLogin callback in #38308 was it intentional?

I think it was not intentional (I think I would have added it to the PR description if such a removal was intentional).

**Comment by MatTheCat** [comment]
Well I found https://github.com/symfony/symfony/pull/38308#discussion_r495497150 but if a limiter takes the username into account, creating a new account won’t reset it.

**Comment by wouterj** [comment]
Ah, now I remember. Good find!

Hmm, I feel like the drawbacks (this issue) are much higher than the advantages of not resetting. I'm happy reviewing a PR readding it

**Comment by MatTheCat** [comment]
I can do it. Would this be considered a bugfix or a new feature?

**Comment by wouterj** [comment]
I would say a bugfix (let's see what other core team members think when the PR is created).

**Comment by MatTheCat** [comment]
Would it be possible to only reset the local limiter on successful login? :thinking:

**Comment by OskarStark** [comment]
👍🏻 bugfix
