### ISSUE TITLE
Improve error messages of the BrowserKitAssertionsTrait

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#40904]
**Description**
When using 
```
$this->assertSame(Response::HTTP_OK, $grcPremium->getResponse()->getStatusCode());
```
I get
```
Failing to assert that 500 is same than 200
```
When using `assertResponseIsSuccessful`, I get a message
```
Failing to assert that the response is successful
```
then I get a huge error page with one hundred of lines like that
![image](https://user-images.githubusercontent.com/9052536/115687420-72013d00-a35a-11eb-8bfa-605951cb73ad.png)

When I use my custom method
```
protected function debug(Crawler $crawler): void
    {
        $exceptionMessage = $crawler->filter('.exception-message');
        if ($exceptionMessage->count() > 0) {
            echo $exceptionMessage->text();
        }
    }
```
I get directly the error message `No secret provided`.

What about using something similar in order to get a better error message instead of displaying the whole response content ?

**Comment by xabbuh** [comment]
Same as #40837?

**Comment by VincentLanglet** [comment]
Indeed.
