### ISSUE TITLE
Profiler not taking port into account behind reverse proxy

### ISSUE THREAD

**Issue by ploegsteert** [symfony/symfony#40909]
**Symfony version(s) affected**: 5.2.6

**Description**

When accessing symfony app through a reverse proxy on custom port (1291), the _wdt ressource is not fetched via this port, but via 443.

**How to reproduce**

Symfony 5.2.6 on docker php 8 image with apache accessible on the 32771 port

Reverse proxy on Synology NAS : source 1291 (https) -> destination localhost:32771 (http)

**Additional context**

Chrome console : 

Access to XMLHttpRequest at 'https://domain.com/_wdt/738e9b' from origin 'https://domain.com:1291' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I configured Symfony according to this doc : https://symfony.com/doc/current/deployment/proxies.html

**Comment by stof** [comment]
Is your proxy setting the `X-Forwarded-Port` header properly ? and have your properly marked it as a trusted proxy trusting that header ?

**Comment by ploegsteert** [comment]
Thank you for your answer, I had a conf problem on my reverse proxy !

Everything is working fine now.
