### ISSUE TITLE
[Config] Missing namespace in generated config classes constructor

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#40921]
**Symfony version(s) affected**: 5.3.0-BETA1

**Description**
When a config class is generated, config classes in their constructor are missing their namespace. This is because in https://github.com/symfony/symfony/blob/abeb8e4ca9adfcc1494df22af9fd9a1c0181b532/src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php#L374 `getType` does not include it.

**How to reproduce**
See https://github.com/symfony/symfony/issues/40921#issuecomment-825781643

In my `cache.php` config file

```php
$config->cache(['pools' => [[
    'adapters' => 'my.dedicated.cache',
]]]);
```

calls `Symfony\Config\Framework\CacheConfig` constructor, which contains

```php
if (isset($value["pools"])) {
    $this->pools = array_map(function($v) { return new PoolConfig($v); }, $value["pools"]);;
    unset($value["pools"]);
}
```

`PoolConfig` is in the `Symfony\Config\Framework\Cache` namespace so it results in

> Attempted to load class "PoolConfig" from namespace "Symfony\Config\Framework".
> Did you forget a "use" statement for another namespace?

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by MatTheCat** [comment]
Here you go: https://github.com/MatTheCat/reproducer

A cache warmup will trigger the error so you’ll see it as soon as you `composer install`.
