### ISSUE TITLE
CurlHttpClient does not necessarily close curl handles when collected

### ISSUE THREAD

**Issue by marcbp** [symfony/symfony#40922]
**Symfony version(s) affected**: 5.1.5

**Description**
`CurlHttpClient` creates curl handles but does not close them properly. In case of a long running PHP process which creates and destroys lots of HTTP clients, this may lead to a crash of type "Too many open files".

**How to reproduce**
This code creates a new scoped client every second. The process has a number of open files that keeps increasing until crash. I monitor number of open file descriptors with `ls -l /proc/<PID>/fd | wc -l`.
```
<?php

use Symfony\Component\HttpClient\CurlHttpClient;

function request() {
  $client = new CurlHttpClient();
  $response = $client->request('GET', 'http://localhost');
  print($response->getStatusCode()."\n");
}

print("PID: " . getmypid() . "\n");

while (true) {
  request();
  sleep(1);
}
```

**Possible Solution**
I grep'ed http-client repository looking for curl close handle functions and I found only one call to `curl_multi_close` in a very specific scenario (see `CurlHttpClient::request`). I guess that `CurlHttpClient` or `CurlResponse` are not properly clean the handles created by `curl_init` or `curl_multi_init`.

**Comment by nicolas-grekas** [comment]
Thanks for the simple reproducer.

The client is supposed to be used as a service, that is, you should create and reuse the same instance.
That will fix the issue.

The root cause is not that we don't explicitly close handles, but that the client references itself internally. That prevents it from being destructed until the garbage collector run.

Adding `gc_collect_cycle()` in your loop fixes the issue.

Apparently, there is only one circular loop in `CurlHttpClient`, created by the call to this in the constructor:
`curl_multi_setopt($this->multi->handle, \CURLMOPT_PUSHFUNCTION, function (...`

I suppose there is a way to write this code that would make it free from circular refs.

PR welcome.

**Comment by stof** [comment]
@nicolas-grekas the only usages of `$this` in `CurlHttpClient::handlePush` are to access the logger and `$this->multi`. Maybe those 2 could be passed to the closure instead (and then passed as argument to a `private static function handlePush` instead). but this would not solve the issue entirely on its own, as `$this->multi` is the one storing the curl handle so we would still have a circular reference there.

**Comment by marcbp** [comment]
@nicolas-grekas Thank you for pointing me the garbage collecting. I tried forcing a collect cycle but it does not fix the issue. Actually, I tried before opening the issue an explicit unset of the objects, and I did not notice any improvement neither. Are you using PHP 8 ? I have just noticed that it introduced a new CurlHandle class. I guess it follows a RAII pattern. That may explain why internal curl ressources are correctly closed when PHP objects are collected.

**Comment by nicolas-grekas** [comment]
On PHP8 yes. Can you try adding a destructor to CurlClientState to explicitly close the handles maybe?
I'll let you investigate on this one if you don't mind :)

**Comment by marcbp** [comment]
I found that registering a push function in `curl_multi_setopt($this->multi->handle, \CURLMOPT_PUSHFUNCTION, ...)` prevent the GC from collecting the instance of `CurlHttpClient`, at least on PHP 7.4 + curl 7.68. Even if I break the circular reference. A manual call to `reset` empties this push function, allowing the object to be correctly collected. And I'm glad to see that curl handles are then also correctly closed, without a manual call to an explicit close.

Some people may have a resource leak, but the workaround is easy and it seems to be fixed in PHP8+. You can close the issue, thanks for your help !
