### ISSUE TITLE
[Form] Allow custom "LabelGuesser"

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#40939]
**Description**
Right now, all form `<label>`s are generated by applying [FormRenderer::humanize()](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Form/FormRenderer.php#L283) to the field name. If the rules being applied there don't match your use case, there's no other way than to pass each single label string manually, right?

So I'm suggesting to allow creating something like a custom "LabelGuesser", to apply your own rules. In my case, I'd be looking for a way to just take the very field name as label - a "NullGuesser" so to say ;-)

**Comment by javiereguiluz** [comment]
Sorry for the nitpick, but should it be a "LabelFormatter" (or "LabelGenerator", etc.) instead of "LabelGuesser" ?  The "label guessing" is what Symfony does because there's no label, so it needs to "guess" it. But this formatter would receive the form type and/or other information to generate/format/process the label, so strictly speaking there's no guessing.

**Comment by ro0NL** [comment]
App\Form\LabelProviderExtension? :sweat_smile:

**Comment by xabbuh** [comment]
You can always write a custom form type extension that adds a label according to your project's convention if the label formatting rules that are applied by default do not match your requirements. I think we don't need another way to achieve this.

**Comment by ThomasLandauer** [comment]
Cool, thanks - it's indeed quite easy - here's what I did right now, following https://symfony.com/doc/current/form/create_form_type_extension.html
```php
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\Extension\Core\Type\FormType;

class LabelExtension extends AbstractTypeExtension
{
    public function finishView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['label'] = $view->vars['name'];
    }

    public static function getExtendedTypes(): iterable
    {
        return [FormType::class];
    }
}
```
EDIT: I now changed the last line to:
```php
return [TextType::class, ChoiceType::class, CheckboxType::class];
```
...which isn't perfect either cause `CheckboxType::class` kills radiobuttons (i.e. only "0", "1" shown as label) - so this might need some more tweaking...

**Comment by javiereguiluz** [comment]
Let's close as "won't fix" then. Cheers!
