### ISSUE TITLE
[RFC] Container linting using psalm

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#40937]
Hi,

I ran psalm on the compiled var/cache/dev/ContainerXXXXX directory :D

Im wondering what the general consensus around such topic is? As it practically gives us free container linting:

```
ERROR: NullArgument - App_KernelDevDebugContainer.php:289:149 - Argument 3 of Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::__construct cannot be null, null value provided to parameter with type array<array-key, mixed>|int (see https://psalm.dev/057)
        return $this->privates['debug.debug_handlers_listener'] = new \Symfony\Component\HttpKernel\EventListener\DebugHandlersListener(NULL, NULL, NULL, -1, true, ($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), true, NULL);

ERROR: InvalidArgument - getContainer_EnvVarProcessorService.php:23:141 - Argument 2 of Symfony\Component\DependencyInjection\EnvVarProcessor::__construct expects array<array-key, Symfony\Component\DependencyInjection\EnvVarLoaderInterface>|null, Symfony\Component\DependencyInjection\Argument\RewindableGenerator provided (see https://psalm.dev/004)
        return $container->privates['container.env_var_processor'] = new \Symfony\Component\DependencyInjection\EnvVarProcessor($container, new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['secrets.vault'] ?? $container->load('getSecrets_VaultService'));
        }, 1));
```

The possibilities kinda seem interesting, e.g. a more optimized container in dev for such tools (or less optimized for prod =)), generated psalm.xml (i suppressed a bunch of nonsense :)) etc.

**Comment by wouterj** [comment]
I'm really conflicted on this one. On the one hand, I like the idea of "free linting" by tools that are very good at this. On the other hand, all generated PHP code is especially vulnerable for many false-positives, as their goal is "code performance" and not "code quality".

**Comment by ro0NL** [comment]
At this point i think code is code, and thus can be linted.

The case for "true-positives only" is a general concern, maybe we'll get there some day. Symfony owning the generated code allows us to improve as we go. The false-positives will pave the way for fixing tools, phpdoc, or for us to reason why we ignore it.

Ideally i'd like this to be simple as `compile_phpdoc=%kernel.debug%`, to still benefit from language optimizations for not using real types IIUC.

I forgot to mention, but i considered this from the [`lint:container`](https://symfony.com/blog/new-in-symfony-4-4-service-container-linter) POV. I feel like it's re-inventing the wheel at the definition level, whereas the wheel already exists for the compilation artifact we generate.

**Comment by javiereguiluz** [comment]
In my opinion, all the generated code related to the container should be optimized for maximum performance in `prod`. That means not only ignoring all these Psalm recommendations but also aggressively optimizing everything (e.g. removing typehints makes things noticeable faster).

Please, note that I agree on doing/adding all this for the generated code in `dev`, so you can spot any errors before hitting production.

**Comment by zmitic** [comment]
I don't think it would be a good use of time. Compiled container is not using typehints so Symfony would have to generate ``@var`` and ``@returns`` annotations for psalm to be happy.

It would be even bigger problem when generics are used like ``Generator<array-key, MyInterface, MyReturn>``. 

But the real question is: what would we get with it? 
Users never work with container any way, and if something goes wrong, we still get Exception. Psalm would just have scan more things that users don't care about, nor see.

---

Note that I **really** love psalm, I think it is the best thing in PHP world after Symfony and Doctrine, I would really like for Symfony to go full static analysis... but just not for container.

**Comment by nicolas-grekas** [comment]
I'm :-1: on this one, this is generated code, it wouldn't benefit from static analyses.

**Comment by wouterj** [comment]
In that case, let's close this issue. I would be -1 on adding PHPdocs (even option based) - that's a huge effort to accomplish.

As always, feel free to continue this thought experiment by running Psalm on the compiled files and let us know if you found a working use-case :)
