### ISSUE TITLE
[UID] Add UUID/ULID Environment Variable Processor

### ISSUE THREAD

**Issue by kadet1090** [symfony/symfony#40938]
**Description**
It'd be nice to be able to pass UUID/ULIDs in environment variables and transform them into UUID/ULIDs using [Environment Variable Processor] to make code cleaner. Currently this is possible by implementing [custom processor], however it'd be nice for it to be builtin in the library.

Similar case could be implementing [Parameter Converter] for usage in route attributes, but I think that this should be tracked in separate issue.

**Example**
Before:
```
// services.yml
App\Service\FooService:
    arguments: ['%env(SOME_UUID)%']
    
// FooService.php
class FooService
{
    private ?Uuid $uuid;
    
    public function __construct(string $uuid) 
    {
        $this->uuid = $uuid ? Uuid::fromString($uuid) : null;
    }
}
```

After:
```
// services.yml
App\Service\FooService:
    arguments: ['%env(uuid:SOME_UUID)%']
    
// FooService.php
class FooService
{
    public function __construct(private ?Uuid $uuid) 
    {
    }
}
```
**Unsolved issues/questions**
- [ ] Where this should be implemented? `symfony/uid` seems like the most reasonable place, but then component would be dependent on the `EnvVarProcessorInterface` which does not seem good. Maybe `EnvVarProcessor` from `Symfony\Component\DependencyInjection` with conditional checks would be better place?

I could make PR with implementation when above issues will be resolved. 

[Parameter Converter]: https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html
[Environment Variable Processor]: https://symfony.com/doc/current/configuration/env_var_processors.html
[custom processor]: https://symfony.com/doc/current/configuration/env_var_processors.html#custom-environment-variable-processors

**Comment by ro0NL** [comment]
See also https://github.com/symfony/symfony/pull/34652#pullrequestreview-323874644 and #34634

coupling the object creation to env processing feels edgy IMHO, esp. in scope of DI.

I do agree being able to get the value object from outside is wanted design-wise. But defining a non-shared service as such is already really flexible.

**Comment by nicolas-grekas** [comment]
Closing as explained (see links). Thanks for proposing.
