### ISSUE TITLE
[Validator] Url validator is not validating special characters

### ISSUE THREAD

**Issue by gurodrigues** [symfony/symfony#40935]
**Symfony version(s) affected**: 5.1.11

**Description**
When typing domains with an accent on the form, symfony is not returning invalid.

**How to reproduce**
Create a form with a field with the [Url validator](https://symfony.com/doc/current/reference/constraints/Url.html).

Enter a domain with an accent, e.g. http://domínio.com

**Comment by monteiro** [comment]
Bom dia @gurodrigues ,

Domains with special accent are valid.
In Portugal for example, the PT DNS authority (FCCN) supports domains with accents: 
- https://www.dns.pt/pt/dominios/?site=av%C3%B4 
- https://www.dns.pt/pt/dominios/?site=for%C3%A7aa%C3%A9rea

So URL Validator should not return invalid.

**Comment by gurodrigues** [comment]
Bom dia 😃 

I see, thanks for the info.

I wasn’t aware that domains with special accent are valid.
