### ISSUE TITLE
[Runtime] Shebang is printed in the output when bin/console is used

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#40949]
**Symfony version(s) affected**: 5.3.0-dev
**PHP version(s) affected**: <8

**Description**
When running `bin/console` the shebang is printed in the output:
![image](https://user-images.githubusercontent.com/2445045/116074508-26b89880-a692-11eb-8111-15d4154e8ef7.png)

This happens cause the `bin/console` file is required in the [autoload runtime file](https://github.com/symfony/symfony/blob/896f4a6eb6a986cc29e096dfe1f3f7042b03126f/src/Symfony/Component/Runtime/Internal/autoload_runtime.template#L9).

**Comment by Nyholm** [comment]
Thank you for testing beta versions. 

I cannot reproduce on osx. Are you running Windows?

<img width="512" alt="Screenshot 2021-04-26 at 18 08 23" src="https://user-images.githubusercontent.com/1275206/116115188-6d21ed80-a6ba-11eb-9f17-e6455195be0e.png">

**Comment by HypeMC** [comment]
@Nyholm Nope, Linux, Ubuntu 18.04 to be precise.

**Comment by wouterj** [comment]
I can also not reproduce this (Linux Debian Unstable, PHP 8):

```
$ symfony new --version=next sf-next
$ cd sf-next
$ bin/console -V
Symfony 5.3.0-DEV (env: dev, debug: true)

$ cat bin/console
#!/usr/bin/env php
<?php

....
```

Can you maybe share a [reproducer application](https://symfony.com/doc/current/contributing/code/reproducer.html) were you can reproduce it?

Status: works for me

**Comment by HypeMC** [comment]
@wouterj It's a clean Symfony 5.3 install, just like yours. I'll do some more testing to try to figure it out. PHP 7.4.16 in my case since I forgot to mention it earlier.

**Comment by HypeMC** [comment]
@wouterj Just tested it on PHP 8.0.3 & the problem is not present there, so it seems to be a PHP < 8 problem.

**Comment by derrabus** [comment]
* I **can** confirm the bug on macOS with PHP 7.4.16.
* I **cannot** reproduce it with PHP 8.0.3 on the same machine.

**Comment by HypeMC** [comment]
@derrabus Tnx, I updated the description.

**Comment by a1812** [comment]
maybe it will solve

```patch
diff --git a/src/Symfony/Component/Runtime/Internal/autoload_runtime.template b/src/Symfony/Component/Runtime/Internal/autoload_runtime.template
index e6acb1eed6..77c7df27be 100644
--- a/src/Symfony/Component/Runtime/Internal/autoload_runtime.template
+++ b/src/Symfony/Component/Runtime/Internal/autoload_runtime.template
@@ -6,7 +6,7 @@ if (true === (require_once __DIR__.'/autoload.php') || empty($_SERVER['SCRIPT_FI
     return;
 }
 
-if (!is_object($app = require $_SERVER['SCRIPT_FILENAME'])) {
+if (!is_object($app = include $_SERVER['SCRIPT_FILENAME'])) {
     throw new \TypeError(sprintf('Invalid return value: callable object expected, "%s" returned from "%s".', get_debug_type($app), $_SERVER['SCRIPT_FILENAME']));
 }
 ```

**Comment by MatTheCat** [comment]
Looks like https://bugs.php.net/bug.php?id=77561

It is indeed fixed since PHP 8.0.0RC2: https://github.com/php/php-src/commit/896dad4c794f7826812bcfdbaaa9f0b3518d9385

**Comment by nicolas-grekas** [comment]
For 7.4, see https://github.com/php/php-src/pull/6934
For 7.3/7.2, dunno what to do...

**Comment by HypeMC** [comment]
@nicolas-grekas It could work by adding output buffering to `autoload_runtime.php` around `require $_SERVER['SCRIPT_FILENAME']`. Don't know if that's an option.
