### ISSUE TITLE
[DependencyInjection] Unused bind arguments shouldn't throw in production

### ISSUE THREAD

**Issue by Baptouuuu** [symfony/symfony#40959]
**Symfony version(s) affected**: 5.2.3

**Description**
Unused bind variables (`services._defaults.bind.$variable`) shouldn't throw an exception in `prod` environment as this is not an error that prevents the app from running.

**How to reproduce**
In `services.yml` I have a bound argument `services._defaults.bind.$token` initialized with `null` as I want to make sure it never has a value in the dev/test envs, but the variable is still used by one of my services.

In `services_prod.yml` I have the same bound argument but with the value `%env(TOKEN)%` to make sure there is a value only in production (but the service is not redeclared in `services_prod.yml`).

This results in the following error : 

```
In ResolveBindingsPass.php line 83:
  A binding is configured for an argument named "$token" under "_def
  aults" in file "/home/user/api/config/services_prod.yml", but no corres
  ponding argument has been found. It may be unused and should be r
  emoved, or it may have a typo.
```

**Possible Solution**
This case should not raise an exception as it doesn't prevent the app from running. Instead a dev command to validate that all the config is ok should be used.

**Additional context**
This error appeared when deploying a new server for our app, but never appeared when deploying (with the same workflow) our integration server. I don't think the detection is random but I can't find a difference between the 2 deployments.

**Comment by stof** [comment]
> In `services_prod.yml` I have the same bound argument but with the value `%env(TOKEN)%` to make sure there is a value only in production (but the service is not redeclared in `services_prod.yml`).

this won't actually do anything, as defaults are scoped per files, so your services won't use the `%env(TOKEN)%` value in prod. They will keep using `null`

**Comment by Baptouuuu** [comment]
🤔 I thought the files were merged like for the rest of the config

**Comment by stof** [comment]
Config *files* are never merged. Importing them impacts the same ContainerBuilder, but they are loaded separately in turn. And so file-scoped features like the defaults apply only to service definitions of that file. The file-level scoping of defaults is what makes them safe to use (other config files cannot impact the default settings, so you stay in control of your service definition).

For your use case, the right solution is to use a DI parameter to store the value you want to use (either `null` or `%env(TOKEN)%` depending on the environment) and make your binding (which will only exist in `services.yaml`) use that parameter.

**Comment by Baptouuuu** [comment]
Ok, thank you
