### ISSUE TITLE
symfony 3 , Variable "form" does not exist when including form into a seperate twig

### ISSUE THREAD

**Issue by Redawolf** [symfony/symfony#40958]
hello devs , so i'am using a contact form , into multiple twigs , and i had to seperate it , now the twig that i included the form 
in does not recognize the form variable , this is my code  {% include "contact/new.html.twig" %} if you can help i would be gratefull
and thank you

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
