### ISSUE TITLE
[DoctrineBridge] EntityType memory leak in functional tests

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#40965]
**Symfony version(s) affected**: 5.2 (also 5.1)

**Description**
When running multiple functional tests that request pages that include forms using an `EntityType`, there is a memory leak. Does not occur with `symfony/doctrine-bridge` 5.0.x.

**How to reproduce**
[Reproducer](https://github.com/kbond/entity-type-memory-leak) (readme has instructions).

**Possible Solution**
I'm looking for help tracking down the problem. I think it's caused by https://github.com/symfony/symfony/pull/34550 and/or https://github.com/symfony/symfony/pull/30994 but I'm not positive.

I _think_, in your tests, when browsing multiple pages, one or more of which has a form that includes an `EntityType`, it is not cleaned up/reset between requests.

**Additional context**
- [Blackfire comparison](https://blackfire.io/profiles/compare/69ee93c6-b93e-41ac-886a-01228453a3ca/graph) of the reproducer between `symfony/doctrine-bridge` 5.0 and 5.2. Nothing jumped out at me but I don't have any experience with blackfire.
- https://github.com/symfony/symfony/issues/38890 seems very related.

**Comment by kbond** [comment]
FYI, _disabling reboot_ on your `KernelBrowser` seems to fix but I don't think this should be the _solution_.

**Comment by kbond** [comment]
@HeahDude, @xabbuh sorry for the ping but any thoughts on this?

**Comment by xabbuh** [comment]
Sorry for not commenting earlier. This issue is on my list, but I am a bit busy currently. I hope to be able to look into it soon.

**Comment by kbond** [comment]
I just gave this another look and I'm still stumped... My reproducer uses [zenstruck/foundry](https://github.com/zenstruck/foundry) & [zenstruck/browser](https://github.com/zenstruck/browser) (I shouldn't have done that) so I thought one of them was maybe the culprit but it was not. I added a [branch](https://github.com/kbond/entity-type-memory-leak/tree/without-foundry-browser) to my reproducer that uses _pure_ Symfony functional tests and the issue still exists.

The fact that disabling reboot on your KernelBrowser fixes the problem is telling I think. _Something_ isn't being cleaned up... I just can't figure out what. My guess is an doctrine entity manager is being left open.

This is really impeding my ability to upgrade a large app to Symfony 5.3 as I have a lot of tests that hit an endpoint using the `EntityType`. My test suite chews through all my available memory.

**Comment by xabbuh** [comment]
Thank you for the application Kevin. This really helps a lot understanding the issue. I spent quite some time on this debugging what's going on. One thing that I noticed is that the `reset()` method is never called though I do not have any idea how to fix that yet.

**Comment by kbond** [comment]
I've also discovered some things about the `reset()`:
1. Adding the `kernel.reset` tag to the `form.type.entity` service still does not trigger the reset
2. Adding `self::$container->get('form.type.entity')->reset();` to my test case's tearDown() doesn't solve the issue (it executes the method but doesn't fix the memory leak)

**Comment by kbond** [comment]
While `reset()` not being called is strange, I don't think it is the cause of the memory leak. When I bypass the cache in [`DoctrineType::getCachedEntityLoader()`](https://github.com/symfony/symfony/blob/b1115f9f71b0dea7a63aa4b4fb3a43a0e529c3f0/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L267) and [`DoctrineType::getCachedIdReader()`](https://github.com/symfony/symfony/blob/b1115f9f71b0dea7a63aa4b4fb3a43a0e529c3f0/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L253), I still experience the leak.

**Comment by kbond** [comment]
Taking another look at this. Confirmed that #30994 caused the issue and found the culprit:

`Symfony\Component\Form\ChoiceList\Factory\Cache\AbstractStaticOption` statically caches choice type options. In the case of `EntityType`, one of the options is the entity manager so these just pile up for each test.

`Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator` has a `kernel.reset` tag that resets this cache but as discussed above, some/all `kernel.reset`'s aren't being called in tests. ~I need to look further into why this is (maybe this is intentional).~ _Edit: I believe it's because this service isn't instantiated so no chance for reset to be called._

The current user land solution is to call `Symfony\Component\Form\ChoiceList\Factory\Cache\AbstractStaticOption::reset()` or `self::getContainer()->get('form.choice_list_factory')->reset()` in your test's `tearDown()` method.

Still investigating a solution but wanted to share my current findings.

**Comment by stof** [comment]
the `kernel.reset` tag is indeed not meant to handle cases where a service is responsible for resetting a state hold *elsewhere*, where that state could exist even when the tagged service was not used.

**Comment by nicolas-grekas** [comment]
Can you please try #45471 @kbond, on PHP8?

**Comment by kbond** [comment]
https://github.com/symfony/symfony/pull/45471 did not fix the issue for me.

**Comment by kbond** [comment]
FYI, I've updated my reproducer to 5.4 to help testing possible solutions: https://github.com/kbond/entity-type-memory-leak/tree/5.4

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer. I tried the following patch, which didn't fix the leak, but might still be needed for the final fix.

While debugging the issue, I realized that the `CachingFactoryDecorator::reset()` method is never called, despite the added call to the `service_resetter`. The reason is that the container that is reset is not the one used by your test case. Instead, `zendor/zenstruck`'s `HasBrowser::browser()` creates another container that is never reset. There's thus no chance that anything is reset (as a reminder, services are reset if and only it they have been instantiated.)

At this point, I think there is something missing in `zendor/zenstruck` that should be understood and fixed first.
The ball is in your court :)

```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php b/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php
index 25e057cc49..9058fadb03 100644
--- a/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php
+++ b/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php
@@ -160,6 +160,9 @@ abstract class KernelTestCase extends TestCase
         }
 
         if (self::$kernelContainer instanceof ResetInterface) {
+            if (self::$kernelContainer->has('services_resetter')) {
+                self::$kernelContainer->get('services_resetter')->reset();
+            }
             self::$kernelContainer->reset();
         }
```

**Comment by kbond** [comment]
Here's the reproducer w/o zenstruck/* libraries - pure Symfony/Doctrine: https://github.com/kbond/entity-type-memory-leak/tree/5.4-no-zenstruck

Still experiences the same problem.

**Comment by nicolas-grekas** [comment]
Zenstruck should still be fixed I suppose. 
Did you try my patch?

**Comment by kbond** [comment]
> Zenstruck should still be fixed I suppose.

Yep, I'll look into this.

> Did you try my patch?

I tried https://github.com/symfony/symfony/issues/40965#issuecomment-1044829311, https://github.com/symfony/symfony/pull/45471 and https://github.com/symfony/symfony/pull/44497#discussion_r809963877. None worked.

Only thing that has worked so far is https://github.com/symfony/symfony/issues/40965#issuecomment-988079028 (calling `AbstractStaticOption::reset()` in my test's `tearDown()`) and https://github.com/symfony/symfony/pull/44497.

**Comment by nicolas-grekas** [comment]
Found it! See #45479
