### ISSUE TITLE
[DX] Unexpected behaviour due to symfony package as a transitive dependency

### ISSUE THREAD

**Issue by Baptouuuu** [symfony/symfony#40961]
**Symfony version(s) affected**: 5.2.3

**Description**
When requiring a composer package that itself requires a symfony package then it may change the behaviour of the framework without the developer knowing.

**How to reproduce**
- I have guzzle installed 
- I run `composer require sentry/sentry-symfony` 
- I run my tests and they now fail (reason unknown)

I didn't configured the sentry bundle yet and my tests fail because `sentry/sentry-symfony` require `sentry/sdk` that itself require `symfony/http-client` that automatically enable a section of the framework config.

**Possible Solution**
Add a way to opt-out of automatically enabling sections of the framework config when adding a new package. 

**Additional context**
I understand that it can ease the process for some developers when directly requiring a symfony package but in the case of a transitive dependency the developer may not even know the framework config changed.

In my case I saw that the sentry bundle needed a psr implementation and since I already had guzzle installed I wasn't expecting that another dependency would change my app behaviour.

**Comment by stof** [comment]
> Add a way to opt-out of automatically enabling sections of the framework config when adding a new package.

Well, there is an opt-out: add an explicit `enabled: false` config for the http_client config (the default is to auto-detect based on the installed packages because that's what works for most cases.

**Comment by nicolas-grekas** [comment]
I would also recommend you to "replace" "sentry/sdk" in your composer.json file as advised in this readme:
https://github.com/getsentry/sentry-symfony#optional-use-custom-http-factorytransport

The design of the Sentry packages is weird, better opt-out from it.
