### ISSUE TITLE
Issue when submiting form in symfony

### ISSUE THREAD

**Issue by kiakahaDZ** [symfony/symfony#40977]
i have the follow form that contain the ChoiceType bellow and in the choices i have the value and the translation, like this "'-- الاختيار--' =>'app.ui.no_order'", but every time that i submit the form it appeare to me an error
```

->add('type', ChoiceType::class, [
                'choices' =>  $choices = [
                    '-- الاختيار--' =>'app.ui.no_order',
                    'In Stock' => true,
                    'Out of Stock' => false,
                ],
                'invalid_message' => '"{{ value }}" is not valid. Valid choices: {{ choices }}.',
                'invalid_message_parameters' => [
                        '{{ choices }}' => implode(', ', $choices),
                ],
            ])
``` 
Eror: {{ value }}" is not valid. Valid choices: {{ choices }}, "-- الاختيار--" is not valid. Valid choices: app.ui.no_order, 1, .

are there any othhers way to asseignd to choicetype an translation text and submit it without error.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by kiakahaDZ** [comment]
but if you investigate the problem maybe you will see a bug.

**Comment by xabbuh** [comment]
If you think that there is a bug, please provide a small example application that allows to reproduce it and we can consider to reopen.
