### ISSUE TITLE
SF4.4 - should implement method HttpClientInterface::withOptions(array $options) 

### ISSUE THREAD

**Issue by spipu** [symfony/symfony#40975]
**Symfony version(s) affected**: 4.4.21

**Description**
when executing my Functional tests:

1x: Class "Symfony\Component\HttpClient\TraceableHttpClient" should implement method "Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options)": Returns a new instance of the client with new default options

**How to reproduce**
instance any http client in sf 4.4.21

**Possible Solution**
back port the fix that has be done in 5.3

**Additional context**
https://github.com/symfony/symfony/issues/40893

**Comment by jderusse** [comment]
Dupplicate of #40893

**Comment by jderusse** [comment]
This is a new feature that will be implemented in symfony 5.3.

The `4.4` version of `symfony/http-client` requires contract 2.x which DOES NOT have this method.
BUT, but to provide a migration path for contract 2.x to 3.x we use an annotation on the interface to tell maintainers they have to implement this method if they want to be compatible with contract 3.x this is why you have the deprecation.

You should use "direct deprecation" flag (https://symfony.com/doc/current/components/phpunit_bridge.html#direct-and-indirect-deprecations) to only deal with deprecations triggered by your code.

**Comment by stof** [comment]
@jderusse the webprofiler will still show such deprecation in all projects using 4.4

**Comment by spipu** [comment]
maybe the pb is more in the sf detection of deprecated, here : 
https://github.com/symfony/error-handler/blob/5.x/DebugClassLoader.php#L473

normally it may ignore deprecation for the same vendor, but it does not seems to work

**Comment by dspiegel** [comment]
Seeing same issue with new project create with --version=LTS and existing 4.4 LTS applications. I would not expect to see any deprecation's from base LTS project. This same warning is now causing Jenkins build errors for our 4.4 LTS production builds but we are unable to fix as issue is with symphony packages.  IMHO Symfony 5.x changes or updates should never affect current LTS code set. 5.x is development/Beta, not LTS.
Kind regards, Dave Spiegel

**Comment by chalasr** [comment]
Fixed in #41075.
