### ISSUE TITLE
[Form] Passing a reference date causes the DateTimeToArrayTransformer to set minutes/hours when the stored value is 0

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#40999]
**Symfony version(s) affected**: 5.2.6 (probably others)

**Description**
If you pass a reference time to a TimeType field with input type array it will assume the time properties of the reference date when the field value was 0

**How to reproduce**
1. Get a TimeType form field
2. Set input to array
3. Add a reference_date
4. Try to set it to 0

**Possible Solution**
It's caused by https://github.com/symfony/form/blob/8822890bdb6267f8d1c027f697db4bd83c2afc55/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php#L170 cause empty views 0 as empty value and will thus take the value of the reference date

**Comment by Nyholm** [comment]
Could you help me understand why you would set the `reference_date` to 0? Im not familiar with that feature.

**Comment by KDederichs** [comment]
Not the reference_date, the minutes or hours, but it's related to this: https://github.com/symfony/symfony/pull/40998
So all of this only happens if you set a reference_date with differentiating input and model timezones in array mode.
As I described in that issue though I'm not 100% sure if it should be a thing you can do anyways.

**Comment by xabbuh** [comment]
I think adding a test for a use case that would currently fail in #40998 would help understanding and judging this issue.

**Comment by KDederichs** [comment]
I did add a test case to both of them that would fail without the fix, took me a while to get to it sorry.
