### ISSUE TITLE
Using console commands in controller 

### ISSUE THREAD

**Issue by major200322** [symfony/symfony#40995]
Hi community, 

Why using console commands in controller if I can use directly a normal controller?

I can't find any reason for uses console commands in controller :) is there any advance using this feature ?

thanks :)

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by Taminoful** [comment]
> You may have the need to call some function that is only available in a console command. Usually, you should refactor the command and move some logic into a service that can be reused in the controller. However, when the command is part of a third-party library, you don’t want to modify or duplicate their code. Instead, you can run the command directly from the controller.

From the Symfony documentation where you can read more about this use case: https://symfony.com/doc/current/console/command_in_controller.html
