### ISSUE TITLE
[FrameworkBundle] Reboot kernel on warmup is needed for ConfigBuilderGenerator

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/symfony#41011]
When I run `cache:warmup` command with existing cache, `\Symfony\Component\Config\Builder\ConfigBuilderGenerator` build SecurityConfig without any listeners configs (e.g. `\Symfony\Config\Security\FirewallConfig\FormLoginConfig`). This is because `ConfigBuilderGenerator` call `SecurityExtension::getConfiguration` without first execute `SecurityExtension::addSecurityListenerFactory` (that only executed in `Bundle::build`).

It seems like a bug and `CacheWarmupCommand` should call kernel `reboot` method before calling `CacheWarmerAggregate::warmUp`. The same thing actual for `CacheClearCommand` and case when cache is fresh.

**Comment by Nyholm** [comment]
Hm. Im not sure why the security listeners are loaded only on Kernel reboot. Maybe @wouterj knows if calling `reboot()` in the acheWarmupCommand makes sense?

**Comment by Nyholm** [comment]
I see that the description of `cache:warmup` says: 

> Before running this command, the cache must be empty.

@a-menshchikov, can you confirm that this error does not happen if the cache is empty?

------

I would appreciate if other people knowledge about the `cache:warmup` and container builder to have a look at this issue.

**Comment by a-menshchikov** [comment]
At the moment I see that error don't reproducing (regardless of the cache state).
But when I run `cache:warmup` with empty cache, I have a sequence of warnings that I described in #41128.

**Comment by nicolas-grekas** [comment]
Can you please provide us with a simple reproducer?

**Comment by nicolas-grekas** [comment]
OK, got one, just run `APP_ENV=prod bin/console c:c` :)
