### ISSUE TITLE
Generated release notes on blog are missing characters

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/symfony#41021]
More specifically, one character before every underscore is being dropped. 

For example, the latest line of the [5.2.7](https://symfony.com/blog/symfony-5-2-7-released) release notes mention "htt _cache" instead of "http_cache".

**Comment by derrabus** [comment]
In #41018, the generated release notes are fine. So something must have happened when posting them to the blog. @javiereguiluz, can you have a look?

**Comment by javiereguiluz** [comment]
Thanks for reporting! Sadly this is a well-known issue. There's a pending fix in the private symfony.com repository ... but we haven't merged it yet. Sorry!

**Comment by stof** [comment]
@nicolas-grekas @fabpot could you review that pending fix ?
