### ISSUE TITLE
[3.0] [Form] Ensure that the input of basic fields is a string

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#4102]
The PR #2421 tries to fix the case where the browser sends an array for a text field. Before this change, the Form framework did not check the data and passed it through to the model layer.

The idea is correct, but the implementation is not. Data fixing is no transformation. Furthermore, the transformer needs to be removed every time someone wants to add a custom transformer.

Thus #2421 should be reverted and replaced by an `EnsureStringInputListener`, that simply casts the data to string or leaves it null (happens if the field was not submitted). This listener should be connected with the BIND_CLIENT_DATA event of all types that expect a string as input (for example by waiting for #4046 to be merged and adding the listener in FormType if "primitive" is set to true).

**Comment by nicolas-grekas** [comment]
\o/
