### ISSUE TITLE
Missing translations for Catalan (ca)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#41036]
Hello,

There are some missing translation for Catalan (ca). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.ca.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.ca.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.ca.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.ca.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by bllibre** [comment]
Hi, if anyone is working on this, i can take the work

**Comment by Nyholm** [comment]
Hey.
I would be great if you worked on this. Thank you.

**Comment by bllibre** [comment]
#42992
It's my first PR, if I made some mistake or can improve anyting feedback would be nice! Thank you.

**Comment by Nyholm** [comment]
Awesome!
It looks good. I’ll review it shortly.
