### ISSUE TITLE
[Session] Not possible to set prefix/ttl in RedisSessionHandler settings via DSN

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#41071]
**Symfony version(s) affected**: 5.2.x

**Description**
The `RedisSessionHandler` allows to set two options: `prefix` and `ttl`.
Unfortunately, it looks like these settings are not properly based in the calling code:

https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php#L53-L62

Instead, only the options `["lazy" => true]` are passed. The options from the DSN are not parsed for setting up the symfony-side of the config (they are only parsed to configure the redis client itself).

**How to reproduce**
Use the following DSN to configure your session client: `redis://localhost:6379?prefix=ohai_` and it will still use the default prefix `sf_s`.

The `SessionHandlerFactory` uses the redis parsing code from `symfony/cache`, so only the connection is set up with these settings and not the session handler itself.

**Possible Solution**
The only solution I see right now is to parse the query twice: once for setting up the session handler, once for creating the connection.

**Additional context**
n/a

**Comment by makraz** [comment]
Hi @derrabus and @apfelbox, I have the same use case. I'm working on a PR to fix this issue.

**Comment by makraz** [comment]
@derrabus, do you think we can create a Trait for parsing DSN to use it in RedisTrait.php and SessionHandlerFactory.php, DsnParserTrait looks like this:
```
trait DsnParserTrait
{
    /**
     * Creates a Redis connection using a DSN configuration.
     *
     * Example DSN:
     *   - redis://localhost
     *   - redis://example.com:1234
     *   - redis://secret@example.com/13
     *   - redis:///var/run/redis.sock
     *   - redis://secret@/var/run/redis.sock/13
     *   - memcached://user:pass@localhost?weight=33
     *
     * @param string $dsn
     *
     * @throws InvalidArgumentException when the DSN is invalid
     *
     * @return array first item is \Redis|\RedisCluster|RedisClusterProxy|RedisProxy|\Predis\ClientInterface According to the "class" option and second is array of params
     */
    public static function parseDsn($dsn)
    {
        if (0 === strpos($dsn, 'redis:')) {
            $scheme = 'redis';
        } elseif (0 === strpos($dsn, 'rediss:')) {
            $scheme = 'rediss';
        } elseif (0 === strpos($dsn, 'memcached:')) {
            $scheme = 'memcached';
        } elseif (0 === strpos($dsn, 'file:')) {
            $scheme = 'file';
        }

        $params = preg_replace_callback('#^'.$scheme.':(//)?(?:(?:[^:@]*+:)?([^@]*+)@)?#', function ($m) use (&$auth) {
            if (isset($m[2])) {
                $auth = $m[2];

                if ('' === $auth) {
                    $auth = null;
                }
            }

            return 'file:'.($m[1] ?? '');
        }, $dsn);

        if (false === $params = parse_url($params)) {
            throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s".', $dsn));
        }

        if (isset($params['query'])) {
            parse_str($params['query'], $query);
            $params += $query;
        }

        return [$params, $auth];
    }
}
```
