### ISSUE TITLE
Missing translations for Uzbek (uz)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#41089]
Hello,

There are some missing translation for Uzbek (uz). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by shokhaa** [comment]
https://github.com/symfony/symfony/pull/41939

**Comment by fabpot** [comment]
@shokhaa Can you have a look at `src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf` as well, translations for id 19 and 20 are missing there. Thank you for your help.

**Comment by shokhaa** [comment]
@fabpot in all branches?

**Comment by fabpot** [comment]
We just need a PR on the 4.4 branch as the translations are the same on all branches.

**Comment by stof** [comment]
@fabpot is the `en` file the same on all branches too, or should the reference be taken in the 5.4 branch ?
