### ISSUE TITLE
Missing translations for Ukrainian (uk)

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#41088]
Hello,

There are some missing translation for Ukrainian (uk). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

**Comment by andrii-bodnar** [comment]
Hello @Nyholm,

I want to add these missing translations for the Ukrainian language.

**Comment by Nyholm** [comment]
Great. Please do
