### ISSUE TITLE
[VarDumper] dump function already defined by "Tracy"

### ISSUE THREAD

**Issue by jvancoillie** [symfony/symfony#41095]
The `dump` function was not created because it already defined by the tracy library installed as a dependency of rector.

I'm guessing this is due to the autoload order which calls tracy's function file before the var-dumper dump.php file.

```php
// autoload_static.php @generated by Composer

namespace Composer\Autoload;

    public static $files = array (
        //...
        'd507e002f7fce7f0c6dbf1f22edcb902' => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/functions.php',
        '7e9bd612cc444b3eed788ebbe46263a0' => __DIR__ . '/..' . '/laminas/laminas-zendframework-bridge/src/autoload.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
        //...
    );
```
is there a way to prioritize var-dumper functions file ?

**Comment by bezin** [comment]
I run in a similar issue: I try to integrate VarDumper into another non-symfony system. This system defines its own `dump()` function, which I need to stay like it is. Unfortunately, the VarDumper functions file is included before the systems function file.

Is there a way to *lower* the priority of var-dumper functions file 😂 ?

**Comment by nicolas-grekas** [comment]
> The dump function was not created because it already defined by the tracy library installed as a dependency of rector

Then this issue should be opened on the Rector repo I suppose.

> Is there a way to lower the priority of var-dumper functions file?

Maybe by listing this file in your own app? Or by copy/pasting the function somewhere?

Anyway, I'm closing here as there is no bug to keep track of.
