### ISSUE TITLE
Phase out Serializable

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#41094]
**Description**
Due to its broken behavior, PHP is phasing out the `Serializable` interface currently.

See:
* https://wiki.php.net/rfc/custom_object_serialization
* https://wiki.php.net/rfc/phase_out_serializable

The replacement are the magic methods `__serialize()` and `__unserialize()` that have been introduced with PHP 7.4. As long as our implementations of `Serializable` also implement those methods, PHP 8.1 won't throw deprecation notices at us. As far as I can tell, we're safe here.

For Symfony 6, we decided to not provide support for PHP 7 anymore. This also means that we don't need `Serializable` as a BC layer for PHP 7.3 and below anymore. Because of that, I'd like to propose to remove that interface from all Symfony classes in 6.0.

Affected by this change:

* Mime: `RawMessage` (the implementation of the interface is finalized and flagged `@internal`)
* Routing: `CompiledRoute` and `Route` both implement the interface with `@internal` and `final`.
* Security Core:
    * `TokenInterface` extends `Serializable` but also requires `__serialize()` and `__unserialize()` to be implemented.
    * `AbstractToken` provides an implementation that is again `@internal` and `final`.
    * `NullToken` implements `Serializable` *without* `@internal` and `final`.

Question now is: Do we need any additional deprecation layer for 5.4 or would it be okay to simply unannounce the interface and remove the implementations?

**Comment by stof** [comment]
For routing, I suggest we also tag the serializable methods as `@internal`, which will allow us to migrate to `__serialize`

**Comment by derrabus** [comment]
> For routing, I suggest we also tag the serializable methods as `@internal`, which will allow us to migrate to `__serialize`

They are already `@internal` and `final`. Sorry, I missed that. 😓

**Comment by nicolas-grekas** [comment]
> would it be okay to simply unannounce the interface and remove the implementations?

That was my plan yes!

> NullToken implements Serializable without @internal and final.

This should be fixed!

**Comment by derrabus** [comment]
> This should be fixed!

#41096

**Comment by jderusse** [comment]
note we might already remove the Interface from internal/final method by using `__sleep` and `__wakeup` as a workaround for 7.1 like we do for `AuthenticationException`

edit: nvm, none of the class are internal/final

**Comment by derrabus** [comment]
I think, we don't need a workaround here. If we implement `__serialize()` and `__unserialize()` (which is what we do), recent versions of PHP ignore `Serializable` and the deprecation will not be triggered. On Symfony 6, we can drop `Serializable` completely.

**Comment by nicolas-grekas** [comment]
The more I think about, the more I think we should keep the `Serializable` interface on *implementations*. At least for tokens and routes.
We should then make the corresponding methods final and internal.
Of course, we should remove the interface from any interfaces.

**Comment by derrabus** [comment]
`Serializable` is legacy and we should get rid of it eventually, especially since PHP itself is in the progress of phasing it out already. But if keeping the interface on the implementations for two more years makes the whole process easier for everyone, I can live with that.

What we could do already maybe is trigger a deprecation in all `serialize()` implementations if we're on PHP 7.4 and throw on Symfony 6. Because on PHP 7.4 and above, PHP itself will never call that method if we also implement `__serialize()`. All we need is `unserialize()` because that method makes sure, we can unserialize data that was serialized on PHP 7.3 or below.

**Comment by nicolas-grekas** [comment]
Let's do that! And in 6.0 we could even throw

**Comment by nicolas-grekas** [comment]
(we don't need the deprecation on 7.4, everything is already internal)

**Comment by nicolas-grekas** [comment]
Just to complete the plan: in a few years, when PHP 9 will be out, we might be able to remove the interface in the 6.x branch that will be the current one at the time. We'll want to do so to provide compat with PHP 9, which will remove the interface altogether. We'll be able to because our implementation is `@internal` and because enough years might have passed to discard older serialized payloads.

Alternatively, we might want to provide a polyfill for `Serializable`.

Future will tell :)

Closing as this is now resolved.
