### ISSUE TITLE
Method isAllowedProperty on ReflectionExtractor class can return int type 

### ISSUE THREAD

**Issue by Tomanhez** [symfony/symfony#41103]
**Symfony version(s) affected**: 5.2.4

**Description**
Method `isAllowedProperty` on `ReflectionExtractor` class should returns  `bool` type, but returns `int`: 
<img width="1440" alt="Screenshot 2021-05-04 at 10 01 24" src="https://user-images.githubusercontent.com/39232096/116985272-87685680-accc-11eb-85c3-1da5e90bc485.png">

It occurred in in Sylius

**Comment by xabbuh** [comment]
In Sylius this was an issue as they are using strict types. That doesn't apply to the Symfony code so the current implementation will work as expected (see also https://3v4l.org/hQuFcd).
