### ISSUE TITLE
[symfony/cache] Older versions of redis are not supported

### ISSUE THREAD

**Issue by pelikan7** [symfony/symfony#41110]
**Symfony version(s) affected**: symfony/cache v4.4.22

**Description**
After updating from symfony/cache v4.4.21 to v4.4.22, Redis suddenly stopped working. It doesn't show any message other than "Redis connection "HERE_IS_CONNECTION_STRING" failed" (it should add an error message in the end of this message).

After debugging I found out that our version of php-redis (which is 4.2.0-1) accepts 6 parameters in connect() function, while symfony/cache v4.4.22 passes 7 parameters (added TLS support). 7th parameter was added with php-redis 5.3.0 around 1 year ago.

With this change in Symfony\Component\Cache\Traits\RedisTrait, backward compability is gone. 

For example, the stable version of php-redis for Debian is set to 4.2.0-1.

**How to reproduce**
1. Install php-redis in version less than 5.3.0.
2. Run RedisAdapter::createConnection($dsn)

**Possible Solution**
Maybe we should check for php-redis version before adding 7th argument into $redis->connect()?

**Comment by nicolas-grekas** [comment]
Should be fixed by #41099

**Comment by spipu** [comment]
i have exactly the same pb, and i also have the same conclusion about this commit https://github.com/symfony/symfony/commit/a1e0408d08a793aab1e14fb1c50ab901d3354583
