### ISSUE TITLE
Debug bar erroring with 404

### ISSUE THREAD

**Issue by loevgaard** [symfony/symfony#41112]
**Symfony version(s) affected**: 5.2

**Description**
When I launch a freshly installed Sylius installation the debug bar doesn't show up. It seems that it errors with a 404, but when I try to open the URL it's trying to fetch, there is no 404. I have made a video showing the error:

https://www.youtube.com/watch?v=yupDNtIQryg

**Comment by derrabus** [comment]
Can you please report this to Sylius instead? The output in the video says that processing the request took 12 seconds which is a lot for a fresh installation. And this also explains why fetching the toolbar times out at first and why can be fetched manually afterwards.

**Comment by loevgaard** [comment]
Hi @derrabus. I absolutely see your point, but I still believe it would make sense if the retrying of the toolbar used some kind of backoff strategy instead of just retrying every second or whatever it does now. What do you think about such an idea? Then I will make a PR to fix it.

**Comment by derrabus** [comment]
Sure, go ahead. 😃

**Comment by loevgaard** [comment]
There you go, have a great evening and thanks for your swift response!
