### ISSUE TITLE
[Validator] Add shortcut to create a new ConstraintViolationList with one Constraint

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#41111]
**Description**
It's very common to do that in Symfony Application:

```php
$violations = new ConstraintViolationList();
$violations->add(new ConstraintViolation('A publish is already running.', '', [], null, '', null));

// use ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException;
throw new ValidationException($violations);
```

Note: The last line is not related, but will help to better undertand

As you can see, it's a bit boring and really not straightforward to create this piece of code E_TOO_MANY_PARAMETER

What do you thing about something like:

```php
$violations = ConstraintViolationList::createSingleConstraint('A publish is already running.');

throw new ValidationException($violations);
```

---

If it's OK for you, I'll do the PR

**Comment by ro0NL** [comment]
IMHO `createSingleConstraint('...')` implies the same as `new ConstraintViolation('...')`, and then `new ConstraintViolationList([new ConstraintViolation('..')])` isnt that bad.
