### ISSUE TITLE
[String] wrong plural form of "conspectus"

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony#41124]
**Symfony version(s) affected**: 5.2.6

**Description**
Pluralize method of EnglishInflector said plural of conspectus is conspecti.
As you can see the correct plural form is conspectuses:
https://en.wiktionary.org/wiki/conspectus

**How to reproduce**
```
<?php

// composer require symfony/string

require 'vendor/autoload.php';

use Symfony\Component\String\Inflector\EnglishInflector;

$inf = new EnglishInflector();

var_dump($inf->pluralize('conspectus')[0] === 'conspectuses'); // false
var_dump(count($inf->pluralize('conspectus'))); // 1
```

**Comment by derrabus** [comment]
PR welcome, against the Inflector component on 4.4.
