### ISSUE TITLE
`bin/console debug:config XXXX` does't work when the config is not defined in the **application**

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#41121]
**Symfony version(s) affected**: 4.4.*

**Description**

```
root /app bin/console debug:config JMSSerializerBundle

In ConfigDebugCommand.php line 92:
                                                                          
  The extension with alias "jms_serializer" does not have configuration.  
                                                                          

debug:config [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name> [<path>]]
```

**How to reproduce**

Drop all the configuration of a bundle

**Possible Solution**

Dump the real configuration, even if the app definition does not exists.

**Additional context**

```
root /app bin/console debug:config --help
Description:
  Dumps the current configuration for an extension
```

The help says it dump the **current**configuration, it means the configuration defined in the application merged with the default one (I know it, I made this feature).

This line cause the issue: https://github.com/symfony/symfony/blob/18e6e2d1599a2a7b7e24dcec64f0aeee67f235aa/src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php#L73

I can submit a PR to remove it if you are OK

**Comment by ro0NL** [comment]
i think i broke this unintendedly in #30648

ideally we'd solve this from the debug command somehow, or put different im not sure we should start processing empty config to get a default for this purpose :thinking:

**Comment by chalasr** [comment]
The command could fallback to the old way of getting the default config

**Comment by lyrixx** [comment]
Do someone want to work on it?
