### ISSUE TITLE
Console not loading environment from files

### ISSUE THREAD

**Issue by rmbl** [symfony/symfony#41140]
**Symfony version(s) affected**: 5.3.0-BETA2

**Description**

bin/console does not load env variables from .env.local when being run. This leads to errors when trying to `composer install --no-dev` in a production environment.

**How to reproduce**

Use 5.3.0-BETA2, add `APP_ENV=prod` to .env.local and run `bin/console cache:clear`. On 5.3.0-BETA2 this displays the following:

` [OK] Cache for the "dev" environment (debug=true) was successfully cleared.`

When running in 5.2.0 the output is correct:

` [OK] Cache for the "prod" environment (debug=false) was successfully cleared.`

**Possible Solution**
Load .env files when starting bin/console

**Comment by nicolas-grekas** [comment]
Thanks for the report.
The issue will be fixed by #41148

**Comment by rmbl** [comment]
I applied the patch manually and it worked great!

Thanks!
