### ISSUE TITLE
Form getData function give default data instead of posted data

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#41153]
**Symfony version(s) affected**: 5.2.7

**Description**
When you create a form with default values from an data array (not entity) and you change some values in te value and submit the form it will return the default data not the form posted data.

**How to reproduce**
```php
        $form = $this->createForm($someFormType::class, ['field' => 'defaultValue']);
        $form->handleRequest($request);

        if ($request->getMethod() === 'POST' && $form->isSubmitted() && $form->isValid()) {
            $formData = $form->getData();
       }
```
The result of ``` $formData['field'] = 'defaultValue' ``` instead of the value i have filled in the form on the website.

**Possible Solution**
Form getData function should already return the form post data first and as fallback the default data

Post data
![image](https://user-images.githubusercontent.com/6288313/117631525-9d6a9100-b17c-11eb-8dc5-5c448e85d34c.png)

Form getData array
![image](https://user-images.githubusercontent.com/6288313/117631598-b115f780-b17c-11eb-96f6-ee5c7690346e.png)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
