### ISSUE TITLE
Command "make:test" is not defined.

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#41158]
**Symfony version(s) affected**: 5.2.x

**Description**
According to [The docs](https://symfony.com/doc/current/testing.html#application-tests), after installing symfony/test-pack i am able to use the maker to create a application test with `bin/console make:test`. This command does not exist and `bin/console list make` does not show `make:test` . `make:unit-test` and `make:functional-test` does work.

**How to reproduce**
I think this is a general problem, so installing Symfony 5.2 will reproduce this bug. In my case, i was using Symfony 4.4 and was upgrading to 5.2 with 
```json
"extra": {
    "symfony": {
      "allow-contrib": false,
      "require": "5.2.*"
    }
  }
```

**Comment by stof** [comment]
The various `make:*` commands are part of the MakerBundle, not of Symfony itself. To use `make:test`, make sure you use at least version 1.29 of the bundle. Older versions indeed don't have it.

**Comment by dsentker** [comment]
Thanks, upgrading the composer.json entry from 1.21.1 to 1.29.* has done the job.

**Comment by stof** [comment]
@dsentker you should really use `^1.29` rather than `1.29.*` to let composer update to the latest version of the bundle (1.29 is *not* the latest version)
