### ISSUE TITLE
symfony/dependency-injection has a hard dependency on symfony/config under PHP 8

### ISSUE THREAD

**Issue by longwave** [symfony/symfony#41169]
**Symfony version(s) affected**: 5.3.0-beta3

**Description**
symfony/dependency-injection now appears to have a hard dependency on symfony/config when running under PHP 8.

**How to reproduce**
```
$ composer init
...
$ composer require symfony/dependency-injection:^5.3@beta
...
$ cat test.php 
<?php

require 'vendor/autoload.php';

new Symfony\Component\DependencyInjection\Compiler\PassConfig();

$ php8.0 test.php
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Config\Loader\FileLoader" not found in vendor/symfony/dependency-injection/Loader/FileLoader.php:32
```

This is because `PassConfig::__construct()` calls `new RegisterAutoconfigureAttributesPass()`, where the constructor instantiates `YamlFileLoader` via reflection - and `YamlFileLoader` is a subclass of `Symfony\Component\Config\Loader\FileLoader`. 

Cross-posting this from Drupal core, where we are working on upgrading to the latest release of Symfony in https://www.drupal.org/project/drupal/issues/3161889#comment-14098238 - we use the DI component including ContainerBuilder and PassConfig, but don't use the Config component.

**Possible Solution**
Move `YamlFileLoader::parseDefinition()` to a trait or helper class? This would also avoid the use of reflection in RegisterAutoconfigureAttributesPass to use a private method on YamlFileLoader.

**Comment by nicolas-grekas** [comment]
Does Drupal use autoconfiguration? A simple solution here might be to skip this pass when the config component is not found.

**Comment by nicolas-grekas** [comment]
See #41170 if not.

**Comment by longwave** [comment]
Drupal doesn't use autoconfiguration, so #41170 works for us :+1:
