### ISSUE TITLE
Receiving a HTTP/2 400 Bad Request when trying to pass a body to CurlHTTPClient

### ISSUE THREAD

**Issue by PedroFTW** [symfony/symfony#41219]
When trying to pass a body to a Symfony HttpClient, wich I've verified to be a CurlHttpClient, I get a HTTP/2 400 Bad Request response.

It doesn't happen when I pass an empty body array.

Here's the example code:
```
$response = $this->createClient()->request(
            $this->getMethod(),
            $this->getUrl(),
            [
                'body' => ['some' => 'value']
            ]
        );
```

Any ideas?

-- Edit --

I this case, my getMethod is returning POST and my getUrl is returning a valid URI, wich I won't share due to company policy issues. But it is a valid URI wich has been tested both using curl trough a command line, a php request and a Postman request.

**Comment by PedroFTW** [comment]
Adding information.

While testing, I swapped out the HttpClient::create() method with a new instance of the NativeHttpClient. Using the Native client the requests worked alright.

Now I would like to understand why doesn't it work properly when the HttpClient returns an istance of the CurlHttpClient. This is my curl -V

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

```

**Comment by nicolas-grekas** [comment]
Please have a look at the output of `$response->getInfo('debug')` in both cases to compare them, this might give you a clue. Eg maybe the remote server requires a Content-Length header on the request.

**Comment by PedroFTW** [comment]
I'm closing the issue. As it happens, there was a block of code being executed that was defaulting the Content-Length to 0, and thus it didn't matched the payload's lenght.
