### ISSUE TITLE
Incorrect ContainerInterface deprecation warning

### ISSUE THREAD

**Issue by mewejo** [symfony/symfony#41215]
**Symfony version(s) affected**: 5.2.8

**Description**
On a new application, I have a service which is using a [service subscriber](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-subscriber), implementing `Symfony\Contracts\Service\ServiceSubscriberInterface` and depending on `Psr\Container\ContainerInterface` in its constructor.

When running tests, the following deprecation warning is incorrectly shown:

```
Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "TestApp\MySubscriberService" service.
```

**How to reproduce**
Create a service subscriber and use it in a test.

**Possible Solution**
The deprecation trigger should check if the service is implementing `Symfony\Contracts\Service\ServiceSubscriberInterface`

**Additional context**
If I run the web app, and then re-run my tests, the deprecation doesn't show up in the tests.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by fancyweb** [comment]
I am not able to reproduce the issue.

**Comment by mewejo** [comment]
I'll try and setup a test repo this weekend, it's been a busy week

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by mewejo** [comment]
No problem, my apologies.

**Comment by mewejo** [comment]
I tried to reproduce in new 5.3 and 5.2.9 apps and I couldn't trigger the error.

It did happen though, but it isn't happening in my private app anymore, which is currently on 5.2.9, started on 5.2.7.

The fact I saw this error at all confirms something went wrong, as I've never been on <= 5.1. How does Symfony check for the deprecation? What could of tripped it to think;

1) It wasn't using the `Symfony\Contracts\Service\ServiceSubscriberInterface` interface?
2) Thinking it was previously running code from <= 5.1?

It's not a serious issue and the error has gone now, I'm just quite interested in how it happened. I took a look at the container but couldn't see anything obvious.

Thanks again @xabbuh

**Comment by mewejo** [comment]
I've narrowed this down a bit more, it only happens when the container is freshly rebuilt before a test. Subsequent test runs do not trigger the warning.

I also get this, which behaves the same:

```
Since symfony/framework-bundle 5.3: The "Symfony\Component\HttpFoundation\Session\SessionInterface" and "SessionInterface" aliases are deprecated, use "$requestStack->getSession()" instead.
```

Being called in a test `setUp()`, I believe by calling `\Symfony\Bundle\FrameworkBundle\Test\WebTestCase::createClient()`
