### ISSUE TITLE
[Framework] Service "http_cache" only accepts 4 parameters, 5 provided.

### ISSUE THREAD

**Issue by dbrekelmans** [symfony/symfony#41225]
**Symfony version(s) affected**: 5.2

**Description**
We wrote our own container validation command that does some sanity checks and enforces some custom rules in our CI.

The command has discovered that there are 5 parameters provided to `http_cache`, while the class constructor only accepts 4.
The following code is the culprit in `FrameworkExtension.php`.

```php
if ($httpMethodOverride) {
    $container->getDefinition('http_cache')
        ->addArgument((new Definition('void'))
        ->setFactory([Request::class, 'enableHttpMethodParameterOverride'])
    );
}
```

It looks like this was a workaround introduced in https://github.com/symfony/symfony/commit/8aa681832273083247afb9dae51269bc0b17ed41.

It's not a bug in the sense that it doesn't break anything, but it's also not really correct and might be confusing for people reading the internal code.

**How to reproduce**
Check the allowed amount of constructor parameters through Reflection and compare it to the amount of constructor parameters provided by the container.

**Possible Solution**
Some other way to trigger `Request::enableHttpMethodParameterOverride()` without adding an argument to the `http_cache` service.

**Comment by dbrekelmans** [comment]
By the way, I understand if this gets a "won't fix". Just wanted to raise awareness in case this is something you want to change.

**Comment by nicolas-grekas** [comment]
That's a "won't fix" indeed, as that's on purpose.
