### ISSUE TITLE
Symfony/finder no longer handles patterns like **/vendor/**

### ISSUE THREAD

**Issue by lindelius** [symfony/symfony#41223]
**Symfony version(s) affected**: 5.2.8

**Description**
The gitignore pattern parsing no longer handles patterns like `**/vendor/**`, which are respected by `.gitignore` and have also been working perfectly fine with the `symfony/finder` component up until now.

**Possible Solution**
Revert and rethink the "fix" that rewrote the gitignore parsing in `symfony/finder` ([this commit](https://github.com/symfony/finder/commit/67b77716f517e3f864759232e1201e7aa2ab0e82)).

**Additional context**
We're using this component via PHP CS Fixer.

**Comment by OskarStark** [comment]
cc @mvorisek

**Comment by mvorisek** [comment]
I can confirm the issue, I will try to adjust the code to pass the tests.

**Comment by OskarStark** [comment]
Thank you

**Comment by lindelius** [comment]
Thanks!
