### ISSUE TITLE
[Security] Patch change in `UserAuthenticationProvider` is breaking BC

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#41237]
**Symfony version(s) affected**: 4.4.23

**Description**

Prior to https://github.com/symfony/symfony/commit/7e1a5269333d0d5a4844f03e11e4c41299e71f26, I was able to extend `AccountStatusException` and override the `getMessageKey()` in order to provide a specific message related to my app's business logic.
After this commit, I'm always receiving the generic "Invalid credentials." message from the `BadCredentialsException` exception.
I know a CVE is able to break BC if required, but I just want to expose the issues this change is generating in order to see if we could find a way to provide the CVE fix without affecting existing apps.

**How to reproduce**

Declare a custom exception extending `AccountStatusException`:
```php
class MissingCompanyException extends \Symfony\Component\Security\Core\Exception\AccountStatusException
{
    public function getMessageKey()
    {
        return 'Account isn\'t associated to any company.';
    }
}
```
Declare a custom user checker:
```php
class UserChecker implements \Symfony\Component\Security\Core\User\UserCheckerInterface
{
    public function checkPostAuth(UserInterface $user)
    {
        assert($user instanceof \App\Entity\User);

        if (!$user->hasCompanies()) {
            $exception = new MissingCompanyException('User is not associated to a company.');
            $exception->setUser($user);

            throw $exception;
        }
}
```
Perform the authentication process with a user that is not compliant with the business rule.
**Possible Solution**

In my case, I can resolve the issue by inheriting `AuthenticationException` and declaring in my custom class (`MissingCompanyException`) the logic I was extending from `AccountStatusException`.

**Additional context**

This change is also producing different response codes (412 => 401) in my app when the users haven't finished the account verification process. I can't provide more details in this topic right now because I need to debug the involved components in order to check how this change is related. I even don't know if the change in this behavior is originated in my own code or if it comes from a dependency.

**Comment by derrabus** [comment]
Did you set `hide_user_not_found` to `false` in your security.yaml?

**Comment by phansys** [comment]
>Did you set hide_user_not_found to false in your security.yaml?

I wasn't aware about that setting. I can confirm using `false` in this option only solves the issue about the status code.
Thank you so much.

**Comment by phansys** [comment]
Running my test suite, I see that setting `hide_user_not_found` is producing other changes that I'd like to avoid:
```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Invalid credentials.'
+'Username could not be found.'
```
Note that this message is exposing the existence of a user, while in my use case the status code (412) was shown only when the user is found and the verification process was not complete.

**Comment by derrabus** [comment]
> Note that this message is exposing the existence of a user, while in my use case the status code (412) was shown only when the user is found and the verification process was not complete.

… which is also giving away information about registered users. The problem is that the framework can't possibly know where those exceptions to the rule are acceptable for you. The options that you have are:

* Set `hide_user_not_found` to `true` which means that the error message of a login failure is generic and does disclose *why* the authentication failed.
* Set `hide_user_not_found` to `false` and handle the produced authentication exception yourself. You are in full control over which details are disclosed to the client.

I think the second option is what you want. Taking the first option and relying on the user enumeration protection to be incomplete is rather brittle.

**Comment by phansys** [comment]
>I think the second option is what you want. Taking the first option and relying on the user enumeration protection to be incomplete is rather brittle.

Yes, I think it will be the better choice I have.
We could close this issue, unless you think there is a way to make these changes explicit in the documentation.

**Comment by chalasr** [comment]
Issue/PR welcome on symfony-docs to explain the behavior of this option if it is not already.
Thank you.
