### ISSUE TITLE
Functional Testing Collection Form Fields

### ISSUE THREAD

**Issue by gzankevich** [symfony/symfony#4124]
With form collections, we use Javascript to add the new fields and Symfony handles the rest.

In the following example, Office has a many-to-many with Contact.

When attempting the same approach in functional tests, e.g. by doing:

``` php
    $form = $buttonCrawlerNode->form(array(
            'company_whateverbundle_officetype[office_contacts][0][contact]' => '1'
    ));
```

The actual result is:

```
InvalidArgumentException: The form field "company_whateverbundle_officetype[office_contacts][0][contact]" does not exist.
```

The expected result is that a new contact is added.

Steps to reproduce:
1. Create a couple of entities with a many-to-many association between them.
2. Create a form with a collection field to edit the associations.
3. Create a functional test and try to create a new association with it.

**Comment by jakzal** [comment]
re #3824

**Comment by placid2000** [comment]
I've faced the same a few times now and ignored it ill now.. Still no solution there? The workarounds don't seem to work for me neither

**Comment by sstok** [comment]
```
properties[0].value
properties[1].value
```

Are property-paths, a property-path cannot be used for the DOMCrawler.

fnagel's solution works as it doesn't actually use the DOMCrawler but creates the request directly instead.

**Comment by alexislefebvre** [comment]
The [idea](https://github.com/symfony/symfony/issues/4124#issuecomment-13229362) from @sstok is nice. Is there a new way to do the same thing?

I'm looking for a way to get a form through `Client`, add data by using the `$form` array and in the same request add some fields not present in the DOM.

Here is a convenient way to submit a form with data (it works with Symfony 2.8):

    $crawler = $client->request('GET', '/');
    $form = $crawler->filter('input[type=submit]')->form();
    $form['form_name[value]'] = 'foo';
    $crawler = $client->submit($form);

It would be really nice to be able to use something like this:

    $crawler = $client->request('GET', '/');
    $form = $crawler->filter('input[type=submit]')->form();
    $form['form_name[value]'] = 'foo';
    // Set some values for fields generated by Javascript:
    $myNewValues = array(
        'form_name' => array(
            'collection' => array(
                0 =>
                    'name' => 'foo'
                )
            )
        )
    );
    );
    $crawler = $client->submit($form, $myNewValues);

With Symfony 2.8, this code will throw an error if the `form_name[collection][0][name]` field is not in the DOM, which is the case when items of a collection are added dynamically.

If I had a way to disable this check (with a third argument of `submit()` function for example), I may submit a form with supplementary fields in order to tests my forms which have collections.

**Comment by fabpot** [comment]
Closing as the pull request was closed in favor of some documentation in symfony/symfony-docs#6427

**Comment by lordelph** [comment]
I've got an alternative approach which perhaps better mirrors what really happens - before obtaining the `Symfony\Component\DomCrawler\Form` modify the retrieved DOM to insert dynamically created form fields. Here's a helper function which illustrates the approach
~~~~
    protected function addFormField(Crawler $crawler, $formName, $inputName, $inputType='text')
    {
        //create input element in same document
        $doc = $crawler->getNode(0)->ownerDocument;
        $input=$doc->createElement('input');
        $input->setAttribute('type', $inputType);
        $input->setAttribute('name', $inputName);

        //add input to form
        $formNode=$crawler->filter('form[name="'.$formName.'"]')->getNode(0);
        $formNode->appendChild($input);
    }
~~~~
Then a functional test just needs to add any dynamic form elements it needs before calling `form()`
~~~~
//add a dynamic collection field for a file upload
$this->addFormField($crawler, 'my_entity', 'my_entity[images][0][newImage]', 'file');

//get the form as normal
$form = $crawler->selectButton('Update')->form();

//this will now work!
$form['product_type[images][0][newImage]']->upload($filename);
~~~~

**Comment by alexislefebvre** [comment]
@lordelph This is interesting, you could add it in the documentation as an alternative to to the same as in https://github.com/symfony/symfony-docs/pull/6427

**Comment by lordelph** [comment]
Added a PR here https://github.com/symfony/symfony-docs/pull/10527
