### ISSUE TITLE
[HttpClient] Add self-signed certificate authority (CA)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#41255]
**Description**
For development, the best practice is to become your own CA, add it to the browser's list of trusted CA's, and then create certificates for your localhost address, isn't it? See https://stackoverflow.com/a/60516812/1668200

So I'm suggesting to create a way to add that CA to HttpClient's CA list.

The currently available solutions/workarounds each have their drawbacks:

* Disabling `verify_peer` and `verify_host` might not be a good idea in production, so you'd need an entry in `.env.local` for this to set it per environment.
* When setting a `cafile` or `capath`, this is going to *replace* the default CA's, right? (If no, the docs at https://symfony.com/doc/current/reference/configuration/framework.html#cafile are wrong). So this needs to be changed per environment too.

Somewhat related: https://github.com/symfony/symfony-docs/issues/13763

**Comment by stof** [comment]
Well, if you add them to your system list of trusted CA's, this should work out of the box as PHP relies on the system CA store (since 5.6+)

**Comment by n0rbyt3** [comment]
@ThomasLandauer For me this is not related to Symfony but Curl. The HttpClient component is built on top. You can either use the ```cafile``` **or** ```capath``` option and yes, **it will replace** the default options in php.ini (like ```curl_setopt``` does).

If the HttpClient wants to be more clever, it has to copy all certificates from preconfigured capath to a temporary (cache) directory. Then, it has to copy a preconfigured cafile to the same directory. Then all certificates from a given capath have to be copied and finally a given cafile. The temporary path can be used with ```curl_setopt(CURLOPT_CAPATH, <path>)``` then.  And everything needs to be done multiple times when using scoped clients.

Also the HttpClient component is not only Curl but also sockets. The SSL context also have options to **override** cafile and capth. Tricky, isn't it?

In my project, we use scoped clients and we have specified one certificate file (which can contain multiple certificates) per host. Best would be to use environment variables to specify different files for different environments.

**Comment by nicolas-grekas** [comment]
I agree we cannot do this in HttpClient. There is no way to add to the list of certs from there.
This should be handled at the OS level.

**Comment by ThomasLandauer** [comment]
Thanks guys, the information I was missing is that HttpClient uses the system's CA store. I opened a PR to add this to the docs: https://github.com/symfony/symfony-docs/pull/15362

**Comment by stof** [comment]
@ThomasLandauer HttpClient uses whatever PHP uses. And as of PHP 5.6, PHP uses the system CA store by default.
