### ISSUE TITLE
[OptionsResolver] Add function arguments to options resolver to improve usability with bigger configuration

### ISSUE THREAD

**Issue by johnkrovitch** [symfony/symfony#41250]
**Description**
Hi,

I wanted to know if it is acceptable to change the signature of the `setDefault` and `setRequired` methods in the options resolver component. I'm using it a lot, and when the configuration is quite huge, the resolver can be not very readable.

I propose to add an allowed types options and a normalizer options (default to null) to the `setDefault` and `setRequired` methods to avoid repetition in the code (especially with the option name).

**Example**
For example, I think its a good practice to always add the allowed types when declaring an option. So with a normalizer, it is look like :

```php
$resolver = new OptionsResolver();
$resolver
    ->setRequired('title')
    ->setAllowedTypes('title', 'string')
    ->setNormalizer('title', function () { ... })

    ->setDefault('description', null)
    ->setAllowedTypes('description', ['string', 'null'])
    ->setNormalizer('description', function () { ... })
    
   // ...
;
```

I propose to allow declaring the configuration like this :

```php
$resolver = new OptionsResolver();
$resolver
    ->setRequired('title', 'string', function () { ... })
    ->setDefault('description', null, ['string', 'null'], function () { ... })
    
    // ...
;
```

Which is more readable in my opinion, especially if the config grows.

I can make a PR if this is acceptable for you.

Thank you very much !

**Comment by ro0NL** [comment]
the new fluent interface should be preferred IMHO

https://symfony.com/blog/new-in-symfony-5-1-optionsresolver-improvements#fluent-interface

**Comment by chalasr** [comment]
I agree with @ro0NL here.

**Comment by johnkrovitch** [comment]
Ok thanks !
