### ISSUE TITLE
Error when I use 'Composer update' : cache:clear failed

### ISSUE THREAD

**Issue by armanddebesse** [symfony/symfony#41260]
Hi,
In a symfony project, I have this error when I use 'composer update' :   
![image](https://user-images.githubusercontent.com/73818074/118610070-afbb7f00-b7bb-11eb-8d42-e167faa35663.png)  
  
I'm using a single command application so I think that the problem is `bin/console` can't run other command than the command I have specified.  
But I really have no ideas to solve this problem.  
If someone know how to resolve it, I'm listening.  
Thanks, Armand

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
