### ISSUE TITLE
Debug toolbar not showing on Symfony exception pages

### ISSUE THREAD

**Issue by berkut1** [symfony/symfony#41305]
**Symfony version(s) affected**: 4.4.22-24 (or 4.4.21-24)

**Description**
After upgrading to Symfony 4.4.24, the Symfony Exception pages no longer have the Debug Toolbar.
![4 4 24](https://user-images.githubusercontent.com/13355990/118912167-08138d80-b930-11eb-8b07-78b098a9413a.png)

How it was in 4.4.19

![4 4 19](https://user-images.githubusercontent.com/13355990/118912200-1497e600-b930-11eb-8a0e-cd9ee6c45999.png)

Maybe a new configuration has been added that I missed?
Thanks.

**Comment by mhujer** [comment]
Same for me - toolbar is not loading and I'm getting `Uncaught TypeError: Sfjs.loadToolbar is not a function` in Chrome Dev Tools console (on 5.2.8).

EDIT: I guess it may be related to https://github.com/symfony/symfony/pull/41168

**Comment by derrabus** [comment]
cc @weaverryan

**Comment by derrabus** [comment]
Can you please test #41346?

**Comment by weaverryan** [comment]
> Can you please test #41346?

Yes, I would VERY much appreciate some people validating #41346. I have tested it - but I would like to make sure the bug is definitely fixed :)

**Comment by berkut1** [comment]
@derrabus @weaverryan the problem was fixed with changes in the base_js.html.twig
Thanks.

**Comment by nacesprin** [comment]
What is this icon for, and How can I enable it?
![image](https://user-images.githubusercontent.com/295375/213455945-a1a4917d-df7f-4030-9c6f-91fc4b695517.png)

**Comment by berkut1** [comment]
@nacesprin it appears automatically when you use the `dump()` function
