### ISSUE TITLE
[Console] Use class names as canonical name for Helpers by default

### ISSUE THREAD

**Issue by Slamdunk** [symfony/symfony#41310]
```diff
--- a/vendor/symfony/console/Helper/FormatterHelper.php
+++ b/vendor/symfony/console/Helper/FormatterHelper.php
 class FormatterHelper extends Helper
 {
     // [...]
     
     /**
      * {@inheritdoc}
      */
     public function getName()
     {
-        return 'formatter';
+        return self::class;
     }
 }

--- a/MyCommand.php
+++ b/MyCommand.php
 use Symfony\Component\Console\Command\Command;
+use Symfony\Component\Console\Helper\FormatterHelper;

 class MyCommand extends Command
 {
     // [...]
     
     protected function execute(InputInterface $input, OutputInterface $output)
     {
-        $formatter = $this->getHelper('formatter');
+        $formatter = $this->getHelper(FormatterHelper::class);
     }
 }
```

## Why

1. Less typing thanks to IDE autocompletion, immediate understanding and reference on the actual helper in use
2. To ease static analysis tools, which could infer the `$formatter` type to be the Helper name without additional maps to be maintained (or dynamically gathered by an additional `getName()` call or other calls to HelperSet)
3. To ease further `$formatter` IDE autocompletion without additional plugins

**Comment by stof** [comment]
the diff you suggest would be a BC break

**Comment by Slamdunk** [comment]
Indeed: I'd like to propose this for Symfony 6, with a Forward Compatibility added here in v5:

https://github.com/symfony/symfony/blob/a2c8e84b7e8618c814458d7c64e56d8b9b779639/src/Symfony/Component/Console/Helper/HelperSet.php#L40-L48

Which would add `\get_class($helper)` as an additional `$alias` by default.

**Comment by xabbuh** [comment]
The advantage of the current approach is that you can replace a particular helper without having to rewrite the consuming code (of which you might not be in control). This won't work anymore if helpers are referred to by the class name.

**Comment by chalasr** [comment]
IMHO The HelperSet is an outdated, unnecessary concept that was only useful at the time where using proper dependency injection in console commands was not possible (ref https://github.com/symfony/symfony/issues/21417).

For this specific case:
```diff
- $formatter = $this->getHelper('formatter');
+ $formatter = new FormatterHelper();
```
Just my 2cents.

**Comment by stof** [comment]
@chalasr if you instantiate it directly, you don't have an extension point anymore
