### ISSUE TITLE
[VAR-DUMPER] syntax error in 5.2.8 using php 7.2

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#41320]
**Symfony version(s) affected**: 5.2.8

**Description**
using symfony/var-dumper on php 7.2 triggers a php syntax error

```
<b>Fatal error</b>:  Uncaught ParseError: syntax error, unexpected '=' in /cluster/www/www/www/apps/mbw/releases/836/vendor/symfony/var-dumper/Cloner/AbstractCloner.php:316
```

per https://packagist.org/packages/symfony/var-dumper#v5.2.8  it should support php 7.2

it seems there is some array-destructuring used which requires php 7.4 in https://github.com/symfony/var-dumper/blob/d693200a73fae179d27f8f1b16b4faf3e8569eba/Cloner/AbstractCloner.php#L316

**Comment by nicolas-grekas** [comment]
This file is perfectly fine on 7.2, see eg https://3v4l.org/ROube

**Comment by nicolas-grekas** [comment]
Output for 7.0.0 - 7.0.33
    Parse error: syntax error, unexpected '=' in /in/ROube on line 316

**Comment by staabm** [comment]
ohh my.. you are right.. the code is invoked via php 7.0 - thx for the headsup
(because someone uses an old url)
