### ISSUE TITLE
Unable to set environment for the dev server

### ISSUE THREAD

**Issue by sd-obermeyer** [symfony/symfony#41337]
**Symfony version(s) affected**: 4.4.13

**Description**
I'm unable to set the environment for the Symfony dev server. When running `bin/console server:run --env prod`, I get this error message:                                                     
```
  There are no commands defined in the "server" namespace.  
                                                            
  Did you mean this?                                        
      fos:oauth-server                                                                                             
```
When I run above command without the `--env` parameter though, everything works as expected.

**How to reproduce**
See above.

**Comment by xabbuh** [comment]
This is expected. The WebServerBundle is not registered in the `prod` environment.
