### ISSUE TITLE
[Security] Allow to use voteOnAttribute() with priority strategy

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/symfony#41340]
**Description**
When using `priority` strategy for `access_decision_manager` and implementing `Symfony\Component\Security\Core\Authorization\Voter\Voter` and using the method `voteOnAttribute()` and returning `ACCESS_ABSTAIN` (which is 0) Symfony turns it into `ACCESS_DENIED` in L51 in https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Core/Authorization/Voter/Voter.php.

It would be nice to return `ACCESS_ABSTAIN` in `voteOnAttribute()` and continue to the next voter when using `priority`.

**Example**
```php
namespace App\Security\Voter;

use Symfony\Component\Security\Core\Authorization\Voter\Voter;

class AdminVoter extends Voter
{
    // ...

    protected function voteOnAttribute(string $attribute, $subject, TokenInterface $token)
    {
        if($this->security->isGranted('ROLE_ADMIN')) {
            return self::ACCESS_GRANTED;
        }

        return self::ACCESS_ABSTAIN;
    }
}
```

**Comment by stof** [comment]
`voteOnAttribute` is typehinted to return a boolean, not a vote decision. abstaining is controlled by the `supports` method.

If you want to return a decision directly, use the `vote()` method directly
