### ISSUE TITLE
[Feature] Share Preload files among Symfony Apps

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#41341]
My setup has multiple websites/web apps running on exactly the same code base (same locations) with:
1. Different parameters per website
2. Different template per website
3. Different database per website

As a result, each website instance has its own local/cache folder, but share the same app and vendor folder.

With this setting, it's impossible to set opcache.preload (since each project has its own preload file). I could put each website inside its own container which share the same app volume, but I think that setup is over-complicated. Since they share the exact same code base, it should be possible to use the exact same file for preloading. 

I peeked into the .....Container.preload.php file:
1. This file links to the autoload file which is shared among all the website instances
2. This file includes a list of classes which is also shared among all the website instances
3. This file includes the ...KernelProdContainer.php file. the code inside the KernelProdContainer.php is ALMOST the same for all website instances (except the parameters which are different).

Perhaps if there is a way to split the parameters and other codes then it should be able to have the exact same preload file that can be used across projects in this case?

**Comment by stof** [comment]
Well, preloading the container is the way the Symfony preloader is architectured. note that the preload script can also include things from the cache in case of code generation (compiled Twig templates for instance)
If you have custom preloading needs, generate your own preload script instead.

**Comment by yellow1912** [comment]
@stof Thank you for your very quick reply. From what I understand, I can preload everything but the container?

So something like this should work I guess?
```

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require '/var/www/sites/2.0.0/vendor/autoload.php';
// no preloading of container

$classes = [];
$classes[] = 'Oneup\FlysystemBundle\OneupFlysystemBundle';
// tons of classes

Preloader::preload($classes);

```

I guess I won't have the benefits of preloading the container in this case, but assuming this works then I will at least get some benefits from preloading commonly used classes. If I make any wrong assumption please let me know, I'm really new to this preload thing.

**Comment by yellow1912** [comment]
Thank you, it works, I removed the container include for now. I think I will copy the code in the PhpDumper to use  👯‍♂️
