### ISSUE TITLE
Multiple choices (not array) in ChoiceType

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#41356]
**Symfony version(s) affected**: 5.2.4

**Description**
Before 5.2.4 update you can create a ChoiceType field with multiple selectable choices that has not neccessary to be an array, i.e an ArrayCollection 

https://github.com/symfony/symfony/blob/cbc7c5dc6d4c2f4c8a177eac81f2022ddecc223c/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L137

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by suleimankelany** [comment]
How can your problem be reproduced?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
