### ISSUE TITLE
No Metadata cache driver is configured on given EntityManager

### ISSUE THREAD

**Issue by garak** [symfony/symfony#41397]
**Symfony version(s) affected**: 5.3.0-RC1

**Description**
When running command `console doctrine:cache:clear-metadata` with latest Doctrine (doctrine/orm:2.9.0) you get the following error (In MetadataCommand.php line 68):

>No Metadata cache driver is configured on given EntityManager.

**Comment by garak** [comment]
Sorry, I just realized that this needs to be reported to DoctrineBundle instead.

**Comment by talalong** [comment]
It is deprecated on v2.9.0
see https://github.com/doctrine/orm/blob/2.9.x/UPGRADE.md#removed-flushing-metadata-cache
