### ISSUE TITLE
[PhpUnit] XML configuration validates against a deprecated schema

### ISSUE THREAD

**Issue by n0rbyt3** [symfony/symfony#41409]
**Symfony version(s) affected**: >= 4.4

**Description**
The receipe for phpunit >= 4.7 cannot be used with PHPUnit 9 as it violates its XML schema. The filter section needs to get replaced with a coverage section.

**How to reproduce**
```
composer require --dev phpunit/phpunit "^9.5"
```

**Possible Solution**
A new receipe may be required for PHPUnit 9 which replaces
```xml
<filter>
    <whitelist processUncoveredFilesFromWhitelist="true">
        <directory suffix=".php">src</directory>
    </whitelist>
</filter>
```
with
```xml
<coverage processUncoveredFiles="true">
    <include>
        <directory suffix=".php">src</directory>
    </include>
</coverage>
```

**Additional context**
Running PHPUnit with the old configuration will show this warning:
```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```

**Comment by nicolas-grekas** [comment]
Thanks for the report, will be fixed by symfony/recipes#952
