### ISSUE TITLE
[Security] ChainUserProvider::loadUserByIdentifier can throw TypeError

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#41417]
**Symfony version(s) affected**: 5.3.0-RC1

**Description**
If you have a custom provider that return a null value with method loadUserByUsername() or loadUserByIdentifier() chained by ChainUserProvider, ChainUserProvider::loadUserByidentifier() will throw a TypeError :

`Return value of Symfony\Component\Security\Core\User\ChainUserProvider::loadUserByIdentifier() must implement interface Symfony\Component\Security\Core\User\UserInterface, null returned`

I think this exception should be prevented or return a more comprehensive exception instead.

**Comment by wouterj** [comment]
Hi! Thank you for creating the issue!

I'm not sure if I understand the problem correctly though. The method signature (in PHPdoc) does not allow returning `null`. In Symfony 6, this method will be defined in PHP code as `loadUserByIdentifier(string $userIdentifier): UserInterface`. This will also give you a `TypeError` if you try to return `null`.

**Comment by chalasr** [comment]
The user provider must throw a UserNotFoundException when it cannot return a UserInterface instance.
