### ISSUE TITLE
Option to specify TLS version in HttpClientInterface

### ISSUE THREAD

**Issue by RonnieRocket147** [symfony/symfony#41436]
**Description**
TLS versions 1.0 and 1.1 are deprecated. It would be great to have an option to specify the minimum TLS version that should be used by the HttpClientInterface, specifically the CurlHttpClient using `CURLOPT_SSLVERSION = CURL_SSLVERSION_TLSv1_2`. Maybe even enabling TLS 1.2+ by default?

**Comment by RonnieRocket147** [comment]
Also, we would like an option to prevent IPv6 lookups because our stack only supports IPv4. Therefore the following curl option can be used: `CURLOPT_RESOLVE = CURL_IPRESOLVE_V4`

**Comment by stof** [comment]
When instantiating the HttpClient, you can pass it default options. Among those, CurlHttpClient supports passing arbitrary curl options (except the ones that are used by Symfony to implement client options, in which case an error will be thrown asking you to use the proper option instead):

```php
$client = new CurlHttpClient([
    'extra' => [
        'curl' => [ \CURLOPT_SSLVERSION => \CURL_SSLVERSION_TLSv1_2],
    ],
]);
```

**Comment by RonnieRocket147** [comment]
Amazing, thank you!
