### ISSUE TITLE
Missing Symfony 3.x versions in Packagist 

### ISSUE THREAD

**Issue by seamuslee001** [symfony/symfony#41445]
Hi there

In CiviCRM we use a number of symfony packages and were just looking at upgrading to use the latest in the 3.4 series. Looking at https://symfony.com/releases/3.4 it says the latest version is 3.4.49 but for example looking at symfony/filesystem the last 3.4 release that is present there https://packagist.org/packages/symfony/filesystem is 3.4.47

Just wondering if someone can help out with getting the versions pushed into packagist

**Comment by jderusse** [comment]
package without change are not tagged. https://symfony.com/blog/symfony-packages-are-not-tagged-anymore-when-nothing-changes-between-versions
