### ISSUE TITLE
\Symfony\Component\Process\Process::escapeArgument as a service class

### ISSUE THREAD

**Issue by tdgroot** [symfony/symfony#41447]
**Description**
Extract `\Symfony\Component\Process\Process::escapeArgument` to a separate service class, so that external classes can make use of the shell argument escaping.

Commands like `\Symfony\Component\Process\Process::fromShellCommandline` accept raw input, but sometimes the client wants to make sure the arguments passed to that method are actually escaped. Or is argument binding the only preferred way to achieve this?

**Example**
``` php
<?php

use Symfony\Component\Process\ArgumentEscaper;
use Symfony\Component\Process\Process;

function test_piped_command(string $param): void
{
    $escaper = new ArgumentEscaper();
    
    $command = [];
    $command[] = 'echo ' . $escaper->escapeArgument($param);
    $command[] = 'md5sum';

    $shellCommand = implode('|', $command);

    $process = Process::fromShellCommandline($command);
    $process->run();
}

```

**Comment by nicolas-grekas** [comment]
It's not possible to correctly escape arguments in a portable way. That's why the API of the Process component doesn't provide a way to escape arguments, and also why you should never do so. Instead, use prepared command lines.

**Comment by stof** [comment]
> Instead, use prepared command lines.

@nicolas-grekas do you mean the syntax passing an array to the Process constructor ? If yes, that's not a solution here, as it does not support using shell features like piping the output of a command to another one (which is done here). If no, you will need to provide more details about your solution.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/34848

**Comment by nicolas-grekas** [comment]
Apparently, the doc has it wrong. See https://github.com/symfony/symfony-docs/pull/15387

**Comment by nicolas-grekas** [comment]
Closing as explained. TLDR: never escape argument, always use prepared command lines (for the exact same reasons as escaping SQL arguments in a no-go, as it's neither reliable/portable.)
