### ISSUE TITLE
[HttpFoundation] custom attribute/flash bag registration

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#41443]
**Description**
With the deprecation of the `session` service, I'm trying to figure out how to register custom attribute/flash bags (via `SessionInterface::registerBag()`) in 5.3+.

I'm not sure if this is the best practice but the common way of doing this pre-5.3 seems to be a compiler pass with the following:
```php
$container->getDefinition('session')
    ->addMethodCall('registerBag', [new Reference('my_custom_bag_service')])
;
```
I thought about a request listener to run right after the `SessionListener` (to ensure the session isn't yet started) but that would trigger the [`Request::$session`](https://github.com/symfony/symfony/blob/cfb1016a7c1fac23fb8bbe95f7737ecbdffa3b5e/src/Symfony/Component/HttpFoundation/Request.php#L733) callback perhaps unnecessarily...

If there is currently a better way that works in 5.3, I can add this to the docs.

**Comment by kbond** [comment]
Ping @jderusse

**Comment by jderusse** [comment]
I think decorating the `session.factory` is the best way for this: This factory creates the `session` service in 5.3. And, in 6.0 it'll also create the instances of Session injected in requests.

note: we removed the state from the container (session, sessionStorage, attributeBag, metadataBag, ...), beware of not re-adding a new stateful data service (`my_custom_bag_service`)

**Comment by kbond** [comment]
Thanks! I'll look into this.

**Comment by craigh** [comment]
Greetings!

@kbond I am wondering if you found an adequate solution to this problem?

I am wondering if instead of this:
```php
$container->getDefinition('session')
    ->addMethodCall('registerBag', [new Reference('my_custom_bag_service')])
;
```

we simply do this:
```php
$container->getDefinition('session.storage')
    ->addMethodCall('registerBag', [new Reference('my_custom_bag')])
;
```

would this work instead?

**Comment by kbond** [comment]
Hey @craigh, have you looked into decorating the `session.factory` as @jderusse suggested above (I haven't investigated this method yet).

Also, how do we avoid adding the stateful service (`my_custom_bag`)?

**Comment by sstok** [comment]
You could use a custom event (in the decorated factory) like `SessionInitialize` to perform some special operations when a new session is being initialized.

**Comment by craigh** [comment]
> have you looked into decorating the `session.factory` 

I have not. To me, this seems like a 'kludgy' solution. Also, I may be reading it wrong, but the session factory seems [immediately deprecated](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Session/ServiceSessionFactory.php#L22) and also marked as internal, so this seems like a bad idea.

I've not fully understood stateful vs stateless yet, so I cannot comment fully on that issue. @jderusse suggested reading [this](https://github.com/symfony/symfony/issues/41120#issuecomment-833488097) but I'm not any more certain having read it. Since the purpose of the bags is to carry data from one session to the next, that seems inherently stateful, but I am probably misunderstanding.

**Comment by craigh** [comment]
perhaps [this is the session factory](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Session/SessionFactory.php) I should have been looking at...

**Comment by kbond** [comment]
> but the session factory seems immediately deprecated and also marked as internal, so this seems like a bad idea.

I think [this is](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Session/SessionFactory.php) the session factory to decorate.

I'm not sure how decorating would work though - there is no `SessionFactoryInterface`. How could it be decorated multiple times (by different bundles for instance)?

**Comment by timwsuqld** [comment]
I too have hit this issue upgrading to 5.3/5.4. I assume we'll need to start implementing our own class that uses the `SessionFactoryInterface` to add our own custom bags? @kbond @craigh Did either of you end up with a code example that works with the new `SessionFactoryInterface`? (And how do we tell Symfony to use our SessionFactory?)

**Comment by kbond** [comment]
Yes, basically something like this:

```php
$container->register(MyFormSessionFactory::class)
    ->setDecoratedService('session.factory')
    ->setArguments([new Reference('.inner')])
;
```

**Comment by craigh** [comment]
(updated since initial response)

This is what I am using now. Using the service declaration eliminates the need to use the compiler pass. Symfony uses the decorated session factory automatically.

    // config/services.yaml
    App\HttpFoundation\Session\DecoratedSessionFactory:
        decorates: 'session.factory'

    // src/HttpFoundation/Session/DecoratedSessionFactory.php

    /**
     * Decorates the SessionFactory to add our own custom bag.
     */
    class DecoratedSessionFactory implements SessionFactoryInterface
    {
        private SessionFactoryInterface $inner;
    
        /**
         * @param SessionFactoryInterface $inner
         */
        public function __construct(SessionFactoryInterface $inner)
        {
            $this->inner = $inner;
        }
    
        /**
         * @return SessionInterface
         */
        public function createSession(): SessionInterface
        {
            $session = $this->inner->createSession();
            $bag = new MyCustomBag();
            $session->registerBag($bag);
    
            return $session;
        }
    }

**Comment by timwsuqld** [comment]
@craigh Thanks for that, it works perfectly and is a great example of how to move forward from this change.
