### ISSUE TITLE
Question mark in password : Malformed parameter "url".

### ISSUE THREAD

**Issue by Xbirdfr** [symfony/symfony#41450]
**Symfony version(s) affected**: 5.2.9

**Description**
When a question mark is in a Datablse password, I got this error : 

`In DriverManager.php line 355:

  Malformed parameter "url".  `

**How to reproduce**
1) install symfony
2) create a mysql user with a '?' in the password
3) set the DATABASE_URL in .env 
`DATABASE_URL="mysql://user:pa$$wordWithAn?@mysql/database?charset=utf8"`

**Comment by chalasr** [comment]
`DriverManager` is from Doctrine, not Symfony.  Consider reporting this to https://github.com/doctrine/dbal instead.

**Comment by stof** [comment]
Well, to put a question mark in a password in a URL, you need to URL-encode it. Otherwise, this question mark is considered as being the delimiter for the query string. That's not a bug in Symfony or Doctrine but in the value you write.
