### ISSUE TITLE
Improve support for primary language selection (according to header field “Accept-Language”)

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#41455]
Preferences can be configured also for the header field “Accept-Language”.
I would like to achieve that [the primary language can be accordingly selected as a standard functionality of this software library](https://app.slack.com/client/T39U3FUKV/C3EQ7S3MJ/thread/C3EQ7S3MJ-1622205760.474600 "Clarification request from 2021-05-28").

**Comment by YaFou** [comment]
👍🏻 for me because it provides a simple way to detect automatically the user language and adapt the page render.

**Comment by nicolas-grekas** [comment]
Likely related to #36507.

**Comment by maxhelias** [comment]
Fixed in https://github.com/symfony/symfony/pull/43108

**Comment by chalasr** [comment]
Indeed, thanks Maxime.
