### ISSUE TITLE
Wrong end-of-maintenance date for Symfony 5.3 shown in profiler

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#41465]
**Symfony version(s) affected**: 5.3.0

**Description**
After just upgrading from Symfony 5.2 to 5.3, the version in the web debug toolbar is yellow and the profiler says:
> Symfony Status: MAINTENANCE ENDED
> Bugs were fixed until: May 2021

**Comment by javiereguiluz** [comment]
You are right ... but this was fixed in #41461. Thanks!
