### ISSUE TITLE
Documentation: UID

### ISSUE THREAD

**Issue by parijke** [symfony/symfony#41467]
**Symfony version(s) affected**: 5.3.0

**Description**
The documentation uses the "old" UuidVxGenerator, which is gone in 5.3

**How to reproduce**
```
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true, options={"fixed" = true})
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidV6Generator::class)
     */
    protected $id;
```
**Possible Solution**
```
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true, options={"fixed" = true})
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;
```

**Additional context**
The documentation needs to be update how to use the new UuidGenerator syntax

**Comment by YaFou** [comment]
Your issue is about the documentation: there is a repository for this - [symfony/symfony-docs](https://github.com/symfony/symfony-docs). I think it is related to https://github.com/symfony/symfony-docs/issues/14960. Thank you 😄

**Comment by parijke** [comment]
Yes it is exactly that issue. Thank you
