### ISSUE TITLE
[Notifier] undeclared dependency on Messenger component?

### ISSUE THREAD

**Issue by craigh** [symfony/symfony#41464]
**Symfony version(s) affected**: x.y.z

**Description**
Isn't this an undeclared dependency on the Messenger component?

https://github.com/symfony/symfony/blob/cfb1016a7c1fac23fb8bbe95f7737ecbdffa3b5e/src/Symfony/Component/Notifier/Channel/AbstractChannel.php#L14

nothing here: https://github.com/symfony/symfony/blob/cfb1016a7c1fac23fb8bbe95f7737ecbdffa3b5e/src/Symfony/Component/Notifier/composer.json#L18-L22

**Comment by stof** [comment]
The dependency is optional. The channel needs either a transport or a message bus
