### ISSUE TITLE
[Notifier] Rocket Chat not released as 5.3.0

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#41462]
**Symfony version(s) affected**: 5.3.0

**Description**
Rocket Chat Notifier component is not released with 5.3.0 version.

**How to reproduce**
See https://packagist.org/packages/symfony/rocket-chat-notifier

**Possible Solution**

**Additional context**

**Comment by YaFou** [comment]
Other packages seam not to be updated too.

**Comment by fabpot** [comment]
Fixed
