### ISSUE TITLE
bin/phpunit doesn't work with the new recipe

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#41471]
**Symfony version(s) affected**: 5.3.*

**Description**
I've already posted this at the recipes repo a month ago, but didn't got any attention.
https://github.com/symfony/recipes/issues/936

**How to reproduce**
Using symfony 5.3 with phpunit 9.5. bin/phpunit tries to require vendor/phpunit/phpunit/phpunit.

https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/5.3/bin/phpunit#L4

But that fails with:

    Fatal error: strict_types declaration must be the very first statement in the script in /var/www/html/vendor/phpunit/phpunit/phpunit on line 2

looks like importing a file which has booth declare() AND an interpreter (#!/usr/bin/env ) fatals out.
might be a php bug idk

https://github.com/sebastianbergmann/phpunit/blob/9.5/phpunit#L1

**Comment by nicolas-grekas** [comment]
I suppose this doesn't happen anymore on PHP8, isn't it?
I see no solution but using `vendor/bin/phpunit` instead of `bin/phpunit`.

**Comment by mmarton** [comment]
Yeah, I forgot to mention that I used php7.4.

**Comment by BeyerJC** [comment]
I have the same problem, im also on php 7.4.

Does the solution with using vendor/bin/phpunit also work with older versions ? Im using this in a pipeline for many projects and was relying on bin/phpunit.

**Comment by nicolas-grekas** [comment]
A solution might be to set the composer bin-dir to bin/.
Anyone up to give it a try?

**Comment by nicolas-grekas** [comment]
Thanks for the report, will be fixed by symfony/recipes#952
