### ISSUE TITLE
[Runtime] insecure defaults

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#41479]
**Symfony version(s) affected**: 5.3.0

**Description**

If unset in env, Runtime chooses `env: dev, debug: true` by default. While this is likely a DX feature, it's a security concern where a misconfiguration by the ops team exposes the app's internals.

**How to reproduce**

Run Symfony 5.3 in an environment without DotEnv or `APP_ENV`, `APP_DEBUG` set. It comes out as

```
  Environment          dev                                
  Debug                true  
  ```

**Possible Solution**

Pick `prod` with debug off by default. Additionally, can detect if dev reqs are installed so `vendor/autoload_runtime.php` can choose to set the DX friendly defaults there?

**Comment by nicolas-grekas** [comment]
Starting with `dev` has always been the defaults in Symfony. I don't think we should change that personally.

**Comment by dkarlovi** [comment]
Feel free to close if the behavior is intentional.

**Comment by nicolas-grekas** [comment]
Thanks for opening.
