### ISSUE TITLE
BC break in Symfony\Component\Form\DataMapperInterface method signatures

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#41492]
**Symfony version(s) affected**: 5.3.0

**Description**

The following signatures in `Symfony\Component\Form\DataMapperInterface` changed from:
```php
public function mapDataToForms($viewData, iterable $forms);
public function mapFormsToData(iterable $forms, &$viewData);
```

To:
```php
public function mapDataToForms($viewData, \Traversable $forms);
public function mapFormsToData(\Traversable $forms, &$viewData);
```

This way it does not accept `array` anymore as it did in Symfony <5.3.

**Comment by xabbuh** [comment]
Looking at the related issue there have been some thoughts about it (see https://github.com/symfony/symfony/issues/39311#issuecomment-739077408). Did this change cause any real issues for you?

**Comment by nicolas-grekas** [comment]
A test case apparently:
https://github.com/Sylius/Sylius/blob/fa4c1d30dd9f94f4c8bb4e80b8fb3208fdf38c62/src/Sylius/Bundle/OrderBundle/spec/Form/DataMapper/OrderItemQuantityDataMapperSpec.php

**Comment by nicolas-grekas** [comment]
@pamil can you please try patching Sylius to make it work with 5.3 and let us know about the patch?

**Comment by pamil** [comment]
That's correct, no application BC breaks found yet, tests fixed and passing. Thanks, will reopen if something related shows up in real application usage.
