### ISSUE TITLE
symfony 1.4 version

### ISSUE THREAD

**Issue by priyankasinghabes** [symfony/symfony#41499]
multiple database connection requirement

error  -

500 | Internal Server Error | Doctrine_Manager_Exception
Could not parse dsn

n SF_ROOT_DIR/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Manager.php line 420 ...
        }

        if (count($parts) == 0 || ! isset($parts['scheme'])) {

            throw new Doctrine_Manager_Exception('Could not parse dsn');

        }

        return $parts;

**Comment by priyankasinghabes** [comment]
Please help someone.

**Comment by stof** [comment]
This is the github repository for the development of Symfony 5 and the maintenance of Symfony 4.4, not a support channel for the long unmaintained symfony 1.4 (which was never developed in this repo btw). And even for maintained version, the github issue tracker is not the place where support is provided.
See https://symfony.com/support for the support channels, but I doubt you will get an answer about symfony 1.4 on slack, unless you are very lucky.
