### ISSUE TITLE
The documentation confuses the project and the product

### ISSUE THREAD

**Issue by ericmorand** [symfony/symfony#41517]
Reading the configuration of one of the application maintained by my company, I was very surprised to find a configuration key named `kernel.project_dir`: the configuration being used by the application (the product), at runtime, I thought that the name `kernel.project_dir` was a mistake by one of our developers.

It looks like it is not: the Symfony documentation confuses the concepts of project and product, like for example here:

> This returns the absolute path of the root directory of your Symfony project, which is used by applications to perform operations with file paths relative to the project’s root directory.

https://symfony.com/doc/current/reference/configuration/kernel.html#project-directory

The key should be named `kernel.application_dir` or `kernel.product_dir` and the documentation should read:

> This returns the absolute path of the root directory of your Symfony application, which is used by applications to perform operations with file paths relative to the application's root directory.

**Comment by ro0NL** [comment]
im not sure renaming is worth it

I see we may have some sementical preference for product_dir or so, but IMHO product development is in scope of a project. That is, the project of developing and running a website/product.

**Comment by ericmorand** [comment]
The point is the path of the product is not the path of the project. It is confusing if the product is built into `www/my-app` to have some config files there that reference the project path that is `/home/me/project/my-app`. Plus, the documentation clearly says that `%kernel.project_dir` is the path where `composer.json` is located. But there is no `composer.json` file in the final product.

It just adds to the confusion: what exactly is `%kernel.project_dir` for the product?

**Comment by ro0NL** [comment]
i think this is going to be a bit bikeshedding things  =)

note we came from kernel.root_dir, but it was implemented like kernel.kernel_dir (eg. `src/`). However it was perhaps a more declarative name.

So now project_dir is the dir where your software project mounts, typically where composer.json is located also.

See also https://symfony.com/doc/current/reference/configuration/kernel.html#project-directory which mentions the absence of composer.json as well.

So actually product_dir and project_dir a both not declarative, whereas root_dir, base_dir, app_dir are.

**Comment by ericmorand** [comment]
That part makes even less sense:

> If you don’t use Composer, or have moved the composer.json file location or have deleted it entirely (for example in the production servers), you can override the getProjectDir() method to return the right project directory:

A server hosts products, not project. Still Symfony expects us to provide to a production server the path to the project. This path doesn't exist.

Symfony probably expect us to provide the path to the root of the product but it uses an incorrect and confusing wording here.

**Comment by ro0NL** [comment]
well IMHO any software product is a software project, but not any project is a product. Maybe technically we have N products in a single project.

As long as the website is online, its project lives.

**Comment by chalasr** [comment]
> A server hosts products, not project.

A server can host a product, a website, a web application, a console one, a tool, a platform... All those are projects. 

One creates a new project when using `symfony new` or `composer create-project`, versions a project using git, hosts the code of a project on github etc... From beginning to end, you manage and work on a project. 
Using this generic term prevents Symfony from making any assumption regarding the type of the project, and is used widely (at least by all the tools mentioned above).

There is no reason to use another wording here, 👎  for me.
Thanks for proposing.

**Comment by derrabus** [comment]
I agree with @chalasr here. The wording Symfony chose here might not match your expectation, but it is certainly not an exotic one. Let‘s close.

**Comment by ericmorand** [comment]
@chalasr 

> All those are projects.

Sorry but you are wrong. All those are products.

Here is what a project is:

https://dictionary.cambridge.org/dictionary/english/project?q=Project

I am conscious that most people confuse these two concepts but it doesn't mean than Symfony has to.

**Comment by nicolas-grekas** [comment]
Reading https://dictionary.cambridge.org/dictionary/english/product, project is definitely more accurate to me.
I don't know why you have these expectations, but this ship has sailed, "project" is clearly the consensus we're using since years now, and honestly, it's the first time I hear the term "product" in the situation.
