### ISSUE TITLE
[DI] Migrate to named arguments without $

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#41513]
Since PHP 8.0 we have named arguments with dollarless syntax. At the same time Symfony DI requires `$` when declaring service arguments by name. I think that this is not only an inconsistency, but also a restriction for future API elaboration.

For example, with dollarless arguments we can later come with something like this:

```php
inline_service(Service::class, orm: service('orm'), param: '%param%');
// instead of
inline_service(Service::class)->args(['$orm' => service('orm'), '$param' => '%param%']);
```

**Comment by stof** [comment]
@vudaltsov your suggested implementation won't ever work. The `inline_service` function won't have an argument named `orm` to be able to use PHP 8 named arguments on it.

**Comment by vudaltsov** [comment]
@stof, why not?

```php
function inline_service(string $class = null, mixed ...$args): InlineServiceConfigurator
{
    return (new InlineServiceConfigurator(new Definition($class)))->args($args);
}
```

See https://wiki.php.net/rfc/named_params#variadic_functions_and_argument_unpacking.
Proof: https://3v4l.org/WLpiS.

**Comment by stof** [comment]
But you won't gain any IDE support for the name of the parameters either, so I don't see how it is better than the current API (and it would forbid some parameter names like `class` due to conflicts with the actual function signature).

Regarding the explicit dollar, that was required when introducing the feature to avoid breaking BC with people defining args as an associative array before because we were not validating the keys. I don't remember whether we now trigger an error for that case or no.

**Comment by derrabus** [comment]
Also, the forced dollar prefix has nothing to to with the suggested named arguments notation. We could implement the syntax you've proposed while still requiring the dollar if all arguments are passed as a single array.

**Comment by vudaltsov** [comment]
The API example is just an idea of how this might be useful in the future and not the main point of this issue. 

I only suggest enabling dollarless argument names. We have PHP 8.0 at work, use named arguments a lot and `->arg('$arg', ...)` starts to look off.

@stof , the `$` sign is checked here: https://github.com/symfony/symfony/blob/2f29a3dd24759697681b8d3c3a386433d31e74d6/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php#L65

**Comment by stof** [comment]
@vudaltsov but this same code tells me that we also support alternative keys using the type of the argument instead of the name, and that the `$` prefix is used to distinguish both features. this means we cannot remove the `$` prefix in those places.

**Comment by derrabus** [comment]
So we would have quite some migration effort for current Symfony apps to get rid of the dollar here. And we would end up with an API that is potentially ambiguous as @stof points out. I really don't think that this is a good idea, sorry.

**Comment by vudaltsov** [comment]
Agree, thank you for the discussion!
