### ISSUE TITLE
UserInterface and PasswordAuthenticatedUserInterface::getPassword has different signatures

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#41519]
**Symfony version(s) affected**: 5.3.1

**PHP version(s) affected**: 7.4

**Description**
~~After https://github.com/symfony/symfony/pull/41493~~ it is not possible to implement both UserInteface and PasswordAuthenticatedUserInterface

> Fatal error: Declaration of Symfony\Component\Security\Core\User\UserInterface::getPassword() must be compatible with Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface::getPassword(): ?string

**Comment by wouterj** [comment]
Hi!

I'm not sure if I can reproduce this: https://3v4l.org/t2VWh
```php
interface UserInterface
{
    public function getPassword();
}

interface PasswordAuthenticatedUserInterface
{
    public function getPassword(): ?string;
}

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    public function getPassword(): ?string
    {
    }
}
```

Can you please share a reproducer?

(btw, #41493 didn't do anything with `getPassword()` methods. So it's unlikely to be caused by that PR)

**Comment by mmarton** [comment]
This might be on my side. I have a middle interface like this:

https://3v4l.org/qPqpa

**Comment by stof** [comment]
@mmarton changing the order of interfaces in the extend clause of your intermediate interface fixes it: https://3v4l.org/qqEV0

That's because your interface first get the signature with the return type, which is then indeed compatible with the second signature

**Comment by mmarton** [comment]
@stof thank you that fixed it. I didn't know interface order matters. :)
