### ISSUE TITLE
Problems deploying my Symfony 5 project to a host

### ISSUE THREAD

**Issue by Ariane99** [symfony/symfony#41524]
Hi, I am trying to upload my project developed in Symfony 5 to a shared server ... I followed the documentation for deployment but I get the following error. 
![Screenshot_3](https://user-images.githubusercontent.com/32330793/120594593-2dfc6000-c40f-11eb-85eb-2abf18d1e691.png)

When I check the logs it shows me the following: 
![Screenshot_1-2](https://user-images.githubusercontent.com/32330793/120594622-394f8b80-c40f-11eb-9ff2-ac9093cbcaa8.png)

by the way when I am in production environment I get the 404 error but if I change it to dev and go to my controller it works "fine", at least it doesn't show me that 404 error. 
![Screenshot_2](https://user-images.githubusercontent.com/32330793/120594684-51bfa600-c40f-11eb-8112-f2d3a3c64538.png)

![Screenshot_1-1](https://user-images.githubusercontent.com/32330793/120594707-5b490e00-c40f-11eb-8e29-b63bc6ed66a5.png)

I don't understand what the problem is. If you could help me I would appreciate it

**Comment by monteiro** [comment]
Is the routes in the right file? There are routes just for development.
You can run bin/console debug:routes --env=dev or --env=prod and compare.

**Comment by ro0NL** [comment]
For support, see https://symfony.com/support

**Comment by Ariane99** [comment]
@monteiro hi, thanks for de reply, I tried the command and returned this:
![IMG-20210604-WA0000](https://user-images.githubusercontent.com/32330793/120751031-52bb0b00-c4d5-11eb-99b8-197e76962f5f.jpg)

searched info of this but... I not sure what to do next

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
