### ISSUE TITLE
[Security] Memory leaks due to new Security System

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#41528]
**Symfony version(s) affected**: 5.2.10, 5.3.0 (not tested in 5.1)

**Description**
When setting `enable_authenticator_manager: true` under the security configuration, phpunits starts consuming 1-2MB extra memory in each WebTestCase and it does not free up on tearDown, which leads to a "out of memory" error. When leaving it to false the memory usage is (almost) constant.

I have been trying to profile this issue (using blackfire, xdebug, php-meminfo and some more), even tried to disable all Traceable listeners/firewalls/adapters but I cannot find where this memory is going, yet Blackfire suggests the increased memory is significant in the EventDispatcher (which makes sense since the new auth uses EventDispatcher)

<img width="1044" alt="Screenshot 2021-06-02 at 15 22 12" src="https://user-images.githubusercontent.com/1309544/120620693-822e3100-c45d-11eb-8c78-743289a0d580.png">

**Additional context**
- the issue occurs when using multiple `$client->request` in the same test
- the issue does not occur when using `$client->disableReboot()`
- this issue does not seem to occur (or less significantly) when removing all doctrine relations from my User class.

yet, I haven't been able to find a reproducer yet

I run `bin/phpunit --filter=someTest --repeat 100` on a complex project and compare the memory usage between `enable_authenticator_manager` true and false

**Comment by wouterj** [comment]
Hi! Thanks for your research! Memory leaks are hard things to find...

I've been trying to replicate this in a fresh project, but I can't reproduce it: https://github.com/wouterj/sf-reproducer/tree/issue-41528 (not with a custom user provider, nor with a doctrine user provider).

<details><summary>New system</summary>

```
§ SYMFONY_DEPRECATIONS_HELPER=disabled=1 phpunit --filter=testMemory --repeat 100
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing
...............................................................  63 / 100 ( 63%)
.....................................                           100 / 100 (100%)

Time: 00:00.687, Memory: 20.00 MB

OK (100 tests, 200 assertions)

§ SYMFONY_DEPRECATIONS_HELPER=disabled=1 phpunit --filter=testDoctrine --repeat 100
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing
...............................................................  63 / 100 ( 63%)
.....................................                           100 / 100 (100%)

Time: 00:01.098, Memory: 26.00 MB

OK (100 tests, 200 assertions)
```

</details>
<details><summary>Old system</summary>

```
§ SYMFONY_DEPRECATIONS_HELPER=disabled=1 phpunit --filter=testMemory --repeat 100
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing
...............................................................  63 / 100 ( 63%)
.....................................                           100 / 100 (100%)

Time: 00:00.776, Memory: 22.00 MB

OK (100 tests, 200 assertions)

§ SYMFONY_DEPRECATIONS_HELPER=disabled=1 phpunit --filter=testDoctrine --repeat 100
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing
...............................................................  63 / 100 ( 63%)
.....................................                           100 / 100 (100%)

Time: 00:01.172, Memory: 28.00 MB

OK (100 tests, 200 assertions)
```

</details>

**Comment by guillaumesmo** [comment]
Thank you for looking at this @wouterj 

I have pushed a project that reproduces the issue over here: https://github.com/guillaumesmo/symfony-issue-41528

```
Testing
^ 25.050827026367
.^ 27.23560333252
.^ 27.748840332031
.^ 28.290855407715
.^ 28.801010131836
.^ 29.311164855957
.^ 29.821319580078
.^ 30.331474304199
.^ 30.84162902832
.^ 31.414283752441
.^ 31.924438476562
.^ 32.435813903809
.^ 32.94596862793
.^ 33.456123352051
.^ 33.966278076172
.^ 34.476432800293
.^ 34.986587524414
.^ 35.496742248535
.^ 36.006896972656
.^ 36.517051696777
.^ 37.027206420898
.^ 37.53736114502
.^ 38.172515869141
.^ 38.682670593262
.^ 39.192825317383
.^ 39.702980041504
.^ 40.213134765625
.^ 40.728660583496
.^ 41.238815307617
.^ 41.748970031738
.^ 42.259124755859
.^ 42.76927947998
.^ 43.279434204102
.^ 43.789588928223
.^ 44.299743652344
.^ 44.809898376465
.^ 45.320053100586
.^ 45.830207824707
.^ 46.340362548828
.^ 46.850517272949
.^ 47.36067199707
.^ 47.870826721191
.^ 48.380981445312
.^ 48.891136169434
.^ 49.401290893555
.^ 49.911445617676
.^ 50.671600341797
.^ 51.181755065918
.^ 51.691909790039
.^ 52.20206451416
.                50 / 50 (100%)

Time: 4.42 seconds, Memory: 54.00 MB
```

**Comment by wouterj** [comment]
@guillaumesmo thank you for the reproducer! However, if I check it out locally and follow the instructions in the README, I don't see any memory leak: :confused: 

```
$ symfony run bin/phpunit --repeat 50

PHPUnit 8.5.16 by Sebastian Bergmann and contributors.

Testing
^ 23.016098022461
.^ 25.171684265137
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.^ 25.17537689209
.                50 / 50 (100%)

Time: 949 ms, Memory: 28.00 MB

OK (50 tests, 100 assertions)
```

**Comment by sstok** [comment]
FYI. PHP isn't run through Docker, so it might be related to one more extensions or how your set-up is configured.
Anything from Opcache to a different PHP version (with a bug itself) might be the culprit here.

**Comment by guillaumesmo** [comment]
Indeed, I just tested with PHP 8.0.7 and cannot reproduce it either, while the same causes memory leaks in PHP 7.4.20, so I guess we can assume this is a PHP issue instead

it was misleading that the issue was only happening for `enable_authenticator_manager: true`

in the meantime, I was able to reduce memory usage of the tests by using the new KernelBrowser::loginUser helper

**Comment by fabpot** [comment]
Let’s close then

**Comment by wouterj** [comment]
Thanks for checking @guillaumesmo! If you still have the memory leak, maybe you can try to replicate your environment (php version and modules) in a docker container. That would give us the biggest chance to have a reproducible memory leak
