### ISSUE TITLE
[DoctrineBridge] Ulid types are not supported in eager loaded entities (in Postgres)

### ISSUE THREAD

**Issue by VincentChalnot** [symfony/symfony#41526]
**Symfony version(s) affected**: 5.3.0

**Description**
When entities with Ulid identifiers get eager loaded, the Ulid object is never resolved back to it's original database representation. 

**How to reproduce**
Create an entity A with a relation to entity B identified by a Ulid, set relation to fetch: eager, query the entity A with findAll(), watch Doctrine crash.

**Additional context**
Database is Postgres 13
Other UUID types are probably affected as well, I don't have time to investigate further.

The thing is: When Ulid are fetched during the first query that loads the list of identifiers to eager load, the method `Symfony\Bridge\Doctrine\Types\AbstractUidType::convertToPHPValue` is called to convert the database type to the PHP type, but when the UnitOfWork calls triggerEagerLoads, these PHP types are never converted back to their database representation so the method `Symfony\Component\Uid\AbstractUid::__toString` is called and doesn't returns a compatible value.

At some point the system should call `Symfony\Bridge\Doctrine\Types\AbstractUidType::convertToDatabaseValue` but it's never called.

![image](https://user-images.githubusercontent.com/1535893/120610442-72115400-c453-11eb-8962-b79c4d578448.png)

**Comment by nicolas-grekas** [comment]
Shouldn't this be reported to the doctrine/dbal repository instead?
Can you figure out a fix?

**Comment by VincentChalnot** [comment]
I was wondering the same thing, this might well be an issue with doctrine/dbal and not with the Symfony bridge you're right.
The fix was to disable eager loading for now because I don't have much time to deal with this right now, sorry.

However, from what I could gather by reading Doctrine code, there seems to be an issue at some point where the parameter type of the query seems to be resolved to an integer instead of a Type object:

![image](https://user-images.githubusercontent.com/1535893/120616117-3d080000-c459-11eb-9795-3dde6dba36fa.png)

And later on the value doesn't get converted because it's not a propery Type object:

![image](https://user-images.githubusercontent.com/1535893/120616546-9f610080-c459-11eb-9202-3e5bdae1133b.png)

Feel free to close this issue if you feel like this is definitely a Doctrine problem.

**Comment by fancyweb** [comment]
Duplicate of https://github.com/symfony/symfony/issues/40771?

**Comment by VincentChalnot** [comment]
@fancyweb indeed!

**Comment by VincentChalnot** [comment]
The `Doctrine\DBAL\Connection::getBindingInfo` method doesn't seems to support array parameters so even if the proper object type is passed, it can't resolved an array of values.

This is definitely a Doctrine issues, I'm closing this and reopening it in doctrine/dbal.

**Comment by VincentChalnot** [comment]
And to be even more precise, this issue seems to span across doctrine/dbal and doctrine/orm.

**Comment by nicolas-grekas** [comment]
Please link back here and on #40771 when you've opened the issue on the doctrine repo!

**Comment by VincentChalnot** [comment]
See https://github.com/doctrine/dbal/issues/4660
