### ISSUE TITLE
Please release symfony/runtime 5.3.1

### ISSUE THREAD

**Issue by scheb** [symfony/symfony#41521]
**Symfony version(s) affected**: 5.3.1

**Description**

`symfony/symfony` requires `symfony/runtime` in `self.version`, so when I want to install e.g. Symfony 5.3.1, there *has* to be a respective `symfony/runtime` package tagged with `5.3.1`, but it isn't. I think this is because you're no longer releasing packages that don't have any changes, right?

**How to reproduce**

Run: `composer require symfony/symfony:5.3.1`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/symfony 5.3.1 -> satisfiable by symfony/symfony[v5.3.1].
    - symfony/symfony v5.3.1 requires symfony/runtime v5.3.1 -> found symfony/runtime[v5.3.0-BETA1, ..., 5.4.x-dev, 6.0.x-dev] but it does not match the constraint.
```

**Possible Solution**
Tag all releases for `symfony/runtime` :)

**Additional Context**
Yes, I know, I could (and should) just install the components that I need and then I wouldn't have that problem, but I'm using `symfony/symfony` as a shortcut in my builds and it's an official package that people do use, so I think this should work.

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/symfony/pull/41512, wait for 5.3.2

**Comment by scheb** [comment]
Thanks Nicolas!
