### ISSUE TITLE
[Meta] Introduce an abstraction for PHP I/O function calls.

### ISSUE THREAD

**Issue by azjezz** [symfony/symfony#41520]
**Description**

Symfony uses a lot of PHP builtin I/O functions both at runtime, and build-time, these functions are usually blocking, which stops Symfony from reaching it's full potential when used in a long running process server such as AmPHP, or ReactPHP.

This issue suggest introducing more abstractions around I/O calls ( filesystem, sleep, I/O handles, .. etc ), that would allow swapping implementations with their non-blocking equivalent for better performance when running in a long running process server.

An example would be to add an interface to the Filesystem component, and register it as a service, allowing users to override that service with a non-blocking implementation.

**Comment by azjezz** [comment]
And in the process, there needs to be a careful review about how things now work, as you cannot trust a method call to be blocking, and that nothing else will run concurrently.

Assuming we have the following:

```php
public function getData(): array {
  if ($this->cache) { 
    return $this->cache;
  }

  if ($this->filesystem->exists('cache.json')) {
    return $this->cache = $this->filesystem->readFile('cache.json');
  }

  $this->cache = $this->fetchData();
  $this->filesystem->write('cache.json', $this->cache);

  return $this->cache;
}

public function reset(): void
{
  $this->cache = null;
}
```

This method now has the potential to fail, since `$this->filesystem->write` is non-blocking, and we might be handling multiple requests concurrently, there's no guarantee that `reset` method wasn't called.

Therefore, it should be written as follow:

```php
public function getData(): array {
  if ($this->cache) { 
    return $this->cache;
  }

  if ($this->filesystem->exists('cache.json')) {
    return $this->cache = $this->filesystem->readFile('cache.json');
  }

  $this->cache = $cache = $this->fetchData();
  $this->filesystem->write('cache.json', $cache);

  return $cache;
}

public function reset(): void
{
  $this->cache = null;
}
```

**Comment by stof** [comment]
you cannot just swap a non-blocking implementation into a blocking one. A non-blocking IO API requires an async API. And async APIs are contagious.
So doing async IO would require changing all callers to be async APIs as well. To me, that's a no-go.

**Comment by azjezz** [comment]
no it doesn't.

since Symfony 6 requires PHP 8.0, a  non-blocking implementation can ( and already has been, see amphp/file:v3 ) be built on top of ext-fiber with PHP-8, which would provide a sync looking API, but it is actually non-blocking.

ref: https://github.com/amphp/file/tree/v3
ref: https://github.com/amphp/file/tree/v3-revolt
ref: https://github.com/azjezz/psl/blob/asio/async-examples/files.php

**Comment by azjezz** [comment]
> And async APIs are contagious.

I think you mean promises? 😅

**Comment by stof** [comment]
@azjezz well, for Promise-based APIs, this is very visible because it is reflected in the method signature.

For Fiber-based APIs, this is still potentially true because it will still change the function caller to be suspended and resumed later, while other code could have been executed on that class in the meantime (your example above about loosing the guarantee on `$this->cache`). The difference is that static analysis won't be able to warn you because the API signature still looks synchronous while the execution is not anymore (and so you still loose all the guarantees brought by the synchronicity).

**Comment by azjezz** [comment]
there's already an option in psalm that can be enabled which would warn you about such errors, we can start by fixing these issues first, then moving into introducing the abstraction.

see: https://psalm.dev/docs/running_psalm/configuration/#rememberpropertyassignmentsaftercall

Note: this is already true now as we can have an Async doctrine driver, or a cache adapter, it wasn't much of an issue before because all Async APIs used Promise/Generator as a  return type, but now, any object you use can be executing things in an async matter.

**Comment by Nyholm** [comment]
I believe it is a good idea to include such abstractions. But I don't know how they should look or if it is technically possible. But making those abstractions will allow people way more talented than I to create implementations that can make sure your application is non-blocking.

**Comment by azjezz** [comment]
Symfony doesn't have to provide a non-blocking filesystem, or a non-blocking timer ... etc.

The only thing Symfony needs to provide is an interface that would be used across all the framework, and recommended over PHP builtin functions, later we can have Amphp bundle or ReactPHP Bundle that provides non blocking implementations :)

**Comment by stof** [comment]
but if we provide an interface that looks synchronous and that only has a synchronous implementation, even recommending using it over PHP functions won't ensure that packages using it will use it in a way that is safe for the alternative non-blocking implementations.

**Comment by azjezz** [comment]
again, i wanted to note that everything in Symfony right now can be non-blocking, so we can't really protect everyone from doing a mistake.

The minimum would be to use this new API internally, so people that use servers such as Amphp don't suffer from Symfony blocking their application.

**Comment by azjezz** [comment]
Here's some areas that currently block in Symfony, and would need improving:

- Filesystem:

we can look at Amphp for inspiration, current, Amphp\File\Filesystem class takes a Driver ( https://github.com/amphp/file/blob/v3/src/Driver.php ) as a first argument in which it uses, this driver can be either blocking ( https://github.com/amphp/file/blob/v3/src/Driver/BlockingDriver.php ), or non-blocking ( https://github.com/amphp/file/blob/v3/src/Driver/UvDriver.php )

- Time:

we could  introduce a small new component, that would basically do the following:

```php
namespace Symfony\Component\Time;

interface TimeInterface {
  public function sleep(int $seconds): void;
  public function usleep(int $ms): void;
}

final class BlockingTime implements TimeInterface {
  public function sleep(int $seconds): void
  {
    \sleep($seconds);
  }

  ...
}
```

- Process:

This is a difficult one, since you can't really run anything while the process is waiting to finish ( when `$process->run()`  is used ).

for example, if used with Amphp and one request handler decided to run a process using `run()`, it will block the whole program, unless there's a way to register a callable on all processes, that will be executed repeatedly while the process is waiting to finish.

The way i see  this done is by providing a new `ProcessFactory` class, which can be used to create process instead of using the ctor, but can also be used to register callbacks ( or "tick handlers" ) for every process it creates, If we have let's say a AmphpBundle, that bundle can register a callback that will trigger a tick in the event loop every time it's called.
 
- Console:

Console already has an interface for input and output, this allows people to inject non-blocking implementations wrapping another library that deals with I/O handles ( e.g: https://github.com/azjezz/psl/blob/asio/async-examples/line.php )

**Comment by azjezz** [comment]
I would like to note, that when using swoole with Symfony, you will get a better performance than any other long running process server, not just for the fact that it is implemented in C, but also because Swoole converts all PHP builtin functions ( fread, fwrite, file_put_content, curl_*, sleep ... etc ), to be non blocking, so it was *never* considered safe to use swoole with Symfony.

**Comment by azjezz** [comment]
For the past month a lot of libraries have adopted PHP 8.1 fibers ( which are used in PHP 8.0 with the ext-fiber ).

e.g:
 - Amphp ( https://github.com/amphp/amp/tree/v3 )
 - PSL ( https://github.com/azjezz/psl )
 - ReactPHP ( github.com/reactphp/async )

And a new low-level event-loop package that is used by both Amphp, and PSL has been released: https://github.com/revoltphp/event-loop

This allows for us to write non-blocking code, that looks like synchronous code.

e.g:

```php
namespace Symfony\Component\Time;

interface TimeInterface {
  public function sleep(float $seconds): void;
}

final class BlockingTime implements TimeInterface {
  public function sleep(float $seconds): void
  {
    \sleep((int) $seconds);
  }
}

final class RevoltTime implements TimeInterface {
  public function sleep(float $seconds): void
  {
    $suspension = EventLoop::createSuspension();
    EventLoop::delay($seconds, function() use($suspension): void {
      $suspension->resume(null);
    });
    

    // waits until resume is called.
    // meanwhile, other callbacks in the event loop will continue execution.
    $suspension->suspend();
  }
}
```

I think the discussion about this can be resumed, as now there's multiple options to provide non-blocking implementations for every abstraction related to I/O within Symfony, which Symfony itself doesn't need to do initially.

**Comment by nicolas-grekas** [comment]
> it was never considered safe to use swoole with Symfony

Do you have example of when this went wrong already?
Because I was wondering if there shouldn't be an effort to make php core functions compatible with a main event loop.
Are you aware of anyone working on this?

**Comment by azjezz** [comment]
> Do you have example of when this went wrong already?

I can't give you a specific example, but i had this discussion with Swoole maintainers before.

ref: https://twitter.com/azjezz/status/1379529197035655169?s=20

---

Because I was wondering if there shouldn't be an effort to make php core functions compatible with a main event loop.

PHP doesn't have an event-loop, so this can't happen, unless there's a builtin Event Loop in PHP.

The only way to do this currently from userland is to disable all I/O functions in php.ini, and re-declare them in PHP using another library ( PSL, Amp, React ).

however, replacement the behavior of internal functions will still be a bad idea, see: https://twitter.com/another_clue/status/1409230120297111553?s=20

**Comment by azjezz** [comment]
also to note, my "it was never considered safe to use swoole with Symfony" comment was a response to:  https://github.com/symfony/symfony/issues/41520#issuecomment-853324798

**Comment by azjezz** [comment]
I did an experiment tonight, where i tried to make `symfony/templating` safe to use concurrently.

previously, if you use `azjezz/psl:2.0.x`, and write the following code:

```php
[$index, $contact] = Async\parallel([
  static fn() => $engine->render('index.php'),
  static fn() => $engine->render('contact.php'),
]);
```

where `index.php` contains:

```php
<?= $this->extend('layout.php') ?>

<?= $this->get('slots')->set('title', 'Home') ?>

<div>
    <?php
        // simulate some non-blocking I/O opeartion.
        Psl\Async\sleep(0.6);
    ?>

    <h1>Hello, World!</h1>
</div>
```

and `contact.php` contains:

```php
<?= $this->extend('layout.php') ?>

<?= $this->get('slots')->set('title', 'Contact') ?>

<div>
    <?php
        // simulate some non-blocking I/O opeartion.
        Psl\Async\sleep(0.5);
    ?>
    <h1>Contact us</h1>
</div>
```

You won't get the result you are expecting, Symfony will fail at rendering the `index.php`, but will successfully render `contact.php`, as it uses properties to store information about the currently being rendered templates, and uses the same slots instance between all templates.

This in turn, make symfony/templating completely useless in a long-running process, as it can't work.

So i went ahead a did a fork of symfony/templating to fix this, since this component is no longer used by the symfony community, i decided to do a hard fork, and i will be releasing it as a new library, being the only template engine i know of ( in PHP ), which can handle concurrent template rendering.

hype branch: https://github.com/azjezz/templating/tree/hype

Here's an example comparing the output of both `azjezz/hype` and `symfony/templating`: https://github.com/azjezz/templating/blob/hype/example/main.php

Both engines take 0.6 seconds to render, as that's how much time `index.php` sleeps, and finish with no errors, but the result is what is interesting:

```
Hype: rendered "index.php", and "contact.php" twice, in 0.602531 second(s).

<html>
    <head>
        <title>Home</title>
    </head>
    <body>


<div>

    <h1>Hello, World!</h1>
</div>
    </body>
</html>

Symfony: rendered "index.php", and "contact.php" twice, in 0.602467 second(s).

<html>
    <head>
        <title>Contact</title>
    </head>
    <body>


<div>

    <h1>Hello, World!</h1>
</div>
    </body>
</html>


```

did you spot it? Symfony rendered the wrong title for the index.php template! 

This is of course a small template, so you can only imagine the amount of mistakes that can happen when rendering more complex templates.

the commit which fixes this issue is: https://github.com/azjezz/templating/commit/07020d4fd015d1b969d3a10222429facfc672aa3, and here's what it does:

1. isolate template rendering, so that every template has it's own context object, without mutating the engine.
2. ensure that helpers are unique, meaning we need to create a clone of every helper when rendering the template, to ensure that when the state of the helper is changed, it doesn't effect other templates being rendered.

on (2) the commit actually only clones the slots helper, but this technically needs to be done on every helper that is stateful ( it's state - properties - can be changed from the template ).

Note: that's not the final `azjezz/hype` API, I'm planning on changing too much stuff on there, but this gives an idea on how things can break, the best way to ensure code runs safely in a concurrent system is to make sure things are stateless, or have isolated state, immutability is important. 

--- 

Note: next, i would like to do this experiment with twig, but send a PR to twig to fix this issue instead, twig has a larger ecosystem, and is more complex than symfony/templating, hence why i started with templating.


---

After a bit of tweaking, i realized that both Hype ( in its current state ), and templating fail in another case, that is if the extended template does non-blocking I/O.

This is caused by the `ob_start`/`ob_end_clean` nested calls, and there's no way to avoid this except by:

1. not using ob_ and trying to find a way to get the content ( should be much easier for twig, since the generated template can - maybe it already does, didn't look - store the output in a variable instead, and return it ), otherwise, the templates could be rendered in a sub-process.
so what to take from this: avoid ob_* functions.

**Comment by azjezz** [comment]
updated: personally i decide I'm not going to spend more time on this, aside from I/O problems in Symfony that make it incompatible with long running process server, there's multiple other issues.

Symfony was designed to run in a traditional PHP FPM/CGI environment, where all objects are destroyed at the end of the request, and things don't run concurrently, and i think that's okay.

to name few of the issues that are not I/O related:

 - lazy loading services: this is something that shouldn't be done in a long running server architecture, as it only slows initial requests down, while building all services could be done in the "build" step ( which doesn't need to be cached! ).
 - cached DI/routing doesn't make sense in such an environment, as they can be stored in memory, and it would be faster to access them this way
 - Symfony cache, while declaring the interface `CacheInterface` ( from contracts ) as atomic, doesn't actually implement atomic cache, or have any mention of the feature; an example of atomic cache: https://github.com/neutomic/neu/tree/main/src/Cache
 - Symfony event dispatcher is not atomic
 - Twig doesn't support concurrent template rendering
 - Doctrine doesn't have a connection poll
 - Symfony Lock block event loop ( this is I/O related somehow since it uses usleep )
 - A lot of Symfony services are statefull, and would break when used concurrently
 - RequestStack won't work
 - The feature of sub requests doesn't work properly ( at least not in the way symfony does it ) in such an environment 


Unless a completely rewrite is made for Symfony to use an event loop ( e.g: revolt ), Symfony can't, and shouldn't be used in a long running process server.

**Comment by fabpot** [comment]
I disagree with most of the listed items you have.

**Comment by azjezz** [comment]
what are the reasons?

taking any real world symfony application that uses all of symfony recommendations, adding `Psl\Async\sleep(0.001);` in every controller - and other random places - to simulate a non blocking call, and doing the following will show that it is indeed broken:

```php
$responses = Psl\Async\concurrently([
  fn() => $kernel->handle($request1),
  fn() => $kernel->handle($request2),
  fn() => $kernel->handle($request3),
]);
```

The way i have seen people try and work around this is by creating a new kernel for every request, and having a different DI containers, while that might work on small scale, in reality it is an expensive ( and still broken - e.g: twig ), and proves that Symfony wasn't designed with this use case in mind - which is okay, there's no other PHP framework designed with this use case in mind -

Symfony cache being non atomic will lead to cache items being computed multiple items, which is a waste or resource, hence why having an atomic cache is necessary, but not possible unless symfony uses an event loop ( though, can be implemented using Symfony Lock component, but then that is blocking I/O )

**Comment by osbre** [comment]
I find it interesting that [OpenSwoole Coroutine Hooks](https://openswoole.com/docs/modules/swoole-runtime-flags) take a different approach by intercepting all internal PHP calls and making them non-blocking, without having to modify any code.
