### ISSUE TITLE
Problem in Symfony console - make:user

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#41538]
-- Symfony version: 5.3.1
-- Symfony CLI version: 4.25.2

I create a user that use `mobile` property for `unique "display" name`.

`symfony console make:user User`

at the end of this command show this warning:

 

> Next Steps:
>    - Review your new App\Entity\User class.
>    - Use make:entity to add more fields to your User entity and then run make:migration.
>    - Create a way to authenticate! See https://symfony.com/doc/current/security.html
> 2021-06-04T08:50:27+02:00 [info] User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\NativePasswordEncoder" class is deprecated, use "Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher" instead.
> 2021-06-04T08:50:27+02:00 [info] User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface" class is deprecated, use "Symfony\Component\PasswordHasher\PasswordHasherInterface" instead.
> 2021-06-04T08:50:27+02:00 [info] User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\SelfSaltingEncoderInterface" interface is deprecated, use "Symfony\Component\PasswordHasher\LegacyPasswordHasherInterface" on hasher implementations that deal with salts instead.

And in my page show this error:

> Fatal error: Class App\Entity\User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Security\Core\User\UserInterface::getUsername) in C:\My-Site\src\Entity\Admin.php on line 13
> 
> Error: Class App\Entity\Admin contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Security\Core\User\UserInterface::getUsername)

How can I fix this problem?

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/maker-bundle/pull/890
