### ISSUE TITLE
[TestPack] Symfony Test Pack 1.0.8 requires PhpUnit

### ISSUE THREAD

**Issue by raress96** [symfony/symfony#41536]
**Symfony version(s) affected**: 4.4.25

**Description**
The Symfony Test Pack 1.0.8 now requires phpunit:
https://packagist.org/packages/symfony/test-pack#v1.0.8

But the Test Pack 1.0.7 didn't require it. This breaks tests running in a Symfony 4.4 application using the symfony/phpunit-bridge, since the version from the Composer vendor directory of Phpunit will be used instead of the one patched by symfony/phpunit-bridge.

**How to reproduce**
Add to Composer require-dev symfony/test-pack and symfony/phpunit-bridge

**Possible Solution**
Remove phpunit as a dependency to symfony/test-pack

**Additional context**

**Comment by nicolas-grekas** [comment]
The solution is to unpack packs so that you then have precise control over the deps you have.
