### ISSUE TITLE
[Command]Configure a command only available for specific environment

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony#41546]
**Description**

Classify the lot of command available/activable by specific environment. 

**Example**

With Lazy configuration of Command, we can add option of environment who it's possible to hide/disable this command.

**Comment by nicolas-grekas** [comment]
Should be already doable thanks to https://github.com/symfony/symfony/pull/40782
Please give it a try and confirm.
And if you can please provide a doc PR :)

**Comment by TheGarious** [comment]
Oh sorry, i didn't see this #40782

I test this and I take a moment for write this in Symfony doc.
