### ISSUE TITLE
[WebLink] Canonical Link builder

### ISSUE THREAD

**Issue by loevgaard** [symfony/symfony#41579]
I find myself implementing [canonical link tags](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) in all apps. The thing about canonical link tags is that [Google recommend](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) having them on each page. 

A suggestion for implementation:

1. Create a `CanonicalLinkBuilder` service that is initialized with sane defaults, but also have methods for manipulating the final canonical URL obviously.
2. Just like the listener that adds an no index header to responses if you are in dev mode, we could make a listener that adds a canonical link header to responses automatically.

Obviously I could make this in a bundle, but I am just asking here to hear your opinion about having something like this directly in Symfony?

### FAQ
**What about people who have already implemented a canonical tag somehow?**
The default could be to disable the `CanonicalLinkBuilder` functionality, so it would be opt-in instead of opt-out.

**What about URLs where the link canonical header doesn't make sense**
As far as I can see, the only downside to this is the size of the response, i.e. the responses on these pages would be 60-100 bytes bigger.

**What are the advantages of having this directly in Symfony?**
Multiple!
- It pushes developers to take a stance on SEO which a great percentage of websites could benefit from and just by enabling the `CanonicalLinkBuilder` the website would in general benefit from such a tag (in a SEO perspective).
- It creates a single place of truth for the canonical link tag, so developers doesn't screw up canonical tags, i.e. by creating multiple tags on a page
- As a follow up to the previous point it also creates a simple way for bundle developers to handle canonical tags. I work with [Sylius](https://sylius.com/) on a daily basis which is an ecommerce platform based on Symfony. In an ecommerce context, canonical URLs are especially important and different bundles in the Sylius universe implement ways to handle this which sometimes ends up in multiple canonical tags on a single page. With a core feature like the `CanonicalLinkBuilder` this would be a problem of the past.

**Comment by YaFou** [comment]
I don't think that this feature should be in the Symfony core. In my opinion, Symfony should not manage SEO features but should be managed by bundles. Perhaps, you can have a look at [this](https://packagist.org/packages/camelot/canonical-url-bundle) 😄

**Comment by loevgaard** [comment]
Hi, @YaFou. Yeah, I probably agree now that I have given it some more thought. With regards to your comment: 

> In my opinion, Symfony should not manage SEO features
This is what I would call a very small SEO feature, and they already do that with the mentioned no index header being applied on dev sites.

The bundle you mention has extra functionality and frankly doesn't focus on the canonical link tag, but the more general concept of canonical urls.
