### ISSUE TITLE
Invalid value passed to fclose()

### ISSUE THREAD

**Issue by bch36** [symfony/symfony#41619]
**Symfony version(s) affected**: 5.4.0

**Description**
WindowsPipes.php:74:

`if (!fclose(fopen($file, 'w')) || !$h = fopen($file, 'r')) {`

In the above line of code, fclose() should ONLY be passed a parameter of type resource, but fopen() can return a value of type bool (if the fopen() fails).  This results in a fatal error under PHP 8:  

`Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in C:\Users\[...]\vendor\symfony\process\Pipes\WindowsPipes.php:74
`

**How to reproduce**
Using the Windows Process Explorer, I found that a couple Chrome processes and a CMD process had a lock on the file, preventing fopen($file, 'w') from working.  Note that fopen($file, 'r') worked fine.  I'm not sure how to reproduce the problem by locking that file using an external program in such a way that the fopen() fails, but the problem should be straightforward simply from the definition of the allowable parameter type to fclose(), and the possible return types from fopen().

**Possible Solution**
```
$fopen_result = fopen($file, 'w');
if ($fopen_result === false || !fclose($fopen_result) || !$h = fopen($file, 'r')) {
```

**Additional context**
I'm assuming the problem has existed for a while, but only became apparent under PHP 8's stricter rules when it became a Fatal Error.

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR on branch 4.4?
