### ISSUE TITLE
[ErrorHandler] Debug mode never passed through to the ErrorRenderer

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#41623]
**Symfony version(s) affected**: 4.4 & 5.x

**Description**
In this line:
https://github.com/symfony/symfony/blob/6eb7f28ebb23f78915abe345c258b64a0810f485/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L118-L120

You can see that an `ErrorHandler` is being created if none is passed in. However, this object creation is missing the constructor parameters, and especially an important one: `$debug`.
That's why, even in debug mode, `$debug = true` is never passed through, no matter in which mode you are running your app.

This leads to you having the "Oops, an error ocurred" error message, even if you are running in debug mode.

**How to reproduce**

I encountered this issue most of the time in any Shopware installation – but they are using the base bundle, as far as I can see, so that seems to be an issue in Symfony itself.

Not sure if Symfony does any trickery with setting up the renderers differently, but the result is the same: the debug error page doesn't work, it only ever shows the production error page.

Happy to look deeper, if anybody has a hint on what to look for.

**Possible Solution**

Add an argument to `::register()` and pass `$debug` explicitly through.

**Additional context**

**Comment by xabbuh** [comment]
I am not sure I fully understand the issue. Could you create a small example that allows to reproduce it?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by apfelbox** [comment]
Hi @xabbuh,

sorry I was on parental leave.

I have the issue that the error handler is registered in non-debug mode, when the app itself is running in debug mode.
I try to reproduce it and will come back if I find anything.

Thanks
