### ISSUE TITLE
NativeHttpClient thows `Invalid IP Address: 0` on PHP 8.1

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#41622]
Blocks #41552

**Symfony version(s) affected**: 4.4-dev

**Description**
Making a request with `NativeHttpClient` on PHP 8.1 will yield a `TransportException` with the following error message:

> fopen(): Invalid IP Address: 0

When I switch to `CurlHttpClient`, the error is gone.

**How to reproduce**
```php
$client = new NativeHttpClient();
$client->request('GET', 'https://www.symfony.com')->getInfo();
```

**Comment by nicolas-grekas** [comment]
Related to #38086

**Comment by derrabus** [comment]
Indeed. #41624
