### ISSUE TITLE
resetViewTransformers()

### ISSUE THREAD

**Issue by baetensc** [symfony/symfony#41631]
**Symfony version(s) affected**: 5.3

**Description**
When putting $builder->get('child')->resetViewTransformers(); the form is still validated and gives error 
"The choices "101", "102", "103", "110" do not exist in the choice list."
**How to reproduce**
add this in the end of 
$builder->get('child')->resetViewTransformers();
    public function buildForm(FormBuilderInterface $builder, array $options)

**Possible Solution**
revert to symfony 4.4 
**Additional context**

**Comment by baetensc** [comment]
When the multiple option is set to false resetViewTransformers() is still working

**Comment by stof** [comment]
Please give a complete reproducer. You say we should put `$builder->get('child')->resetViewTransformers()`, but you don't say where and with which definition of `child`, so there is not enough info

Status: Waiting feedback

**Comment by baetensc** [comment]
Yes Sorry 
here you are:
class Myform extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
->add('from_to', ChoiceType::class, array(
                'label' => false,
                'required' => false,
                'multiple' => true,
                'mapped' => false,
                'attr' => array(
                    'size' => '20'
                ),
                'choice_translation_domain' => false,
                'choices' => [],
            ));

        $builder->get('from_to')->resetViewTransformers();

    }

}

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by baetensc** [comment]
Hello, I ve created 3 apps just saw that it was already broke in symfony 4.4 
3 links 
http://109.230.199.23/4.3/public/index.php
http://109.230.199.23/4.4/public/index.php
http://109.230.199.23/5.3/public/index.php

Left box is 2 files in it if u take one or 2 to the right box and submit will only work in symfony 4.3

The 3 different files are for each version are here
http://109.230.199.23/4.3/vendor/symfony/form/Extension/Core/Type/ChoiceType.php.txt
http://109.230.199.23/4.4/vendor/symfony/form/Extension/Core/Type/ChoiceType.php.txt
http://109.230.199.23/5.3/vendor/symfony/form/Extension/Core/Type/ChoiceType.php.txt

When in my 4.4 app i replace the ChoiceType file it is again working....

**Comment by xabbuh** [comment]
Can you please make your example application available via git?

**Comment by baetensc** [comment]
https://github.com/baetensc/symfo4.4
https://github.com/baetensc/symfo4.3

Here u are ...

**Comment by kopeckyales** [comment]
Broken in version 4.4.20 here: https://github.com/symfony/symfony/blob/v4.4.20/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
Line 169 to 185, added POST_SUBMIT eventListener.

My use case:
I have dynamic select element, one can add or remove items dynamically. I use ChoiceType. Only possible solution to this was to disable default view transformer (resetViewTransformers) as it fails with "do not exists in choice list" and then use my custom made view transformer to convert choice list to entities and vice versa.

**Comment by baetensc** [comment]
any news on this ?

**Comment by Schyzophrenic** [comment]
Could this be linked to #42021?

**Comment by xabbuh** [comment]
@baetensc I now managed to look at your example code. Resetting the view transformers is not the best solution. You should rather go with adding the second choice type dynamically based on the submitted data:

```php
        $possibleChoices = ["1" => "1", "2" => "2"];
        $builder
            ->add('from', ChoiceType::class, array(
                'mapped' => false,
                'choices' => $possibleChoices,
                'multiple' => true,
                'required' => false,
                'attr' => array("size" => 20, "style" => "min-width: 20px;")
            ))
            ->add('from_to', ChoiceType::class, array(
                'label' => false,
                'required' => false,
                'multiple' => true,
                'mapped' => false,
                'attr' => array(
                    'size' => '20'
                ),
                'choice_translation_domain' => false,
                'choices' => [],
            ));

        $builder->addEventListener(FormEvents::PRE_SUBMIT, static function (FormEvent $event) use ($possibleChoices): void {
            $choices = [];

            foreach ($possibleChoices as $label => $value) {
                if (in_array($value, $event->getData()['from_to'] ?? [], true)) {
                    $choices[$label] = $value;
                }
            }

            $event->getForm()->add('from_to', ChoiceType::class, [
                'label' => false,
                'required' => false,
                'multiple' => true,
                'mapped' => false,
                'attr' => array(
                    'size' => '20'
                ),
                'choice_translation_domain' => false,
                'choices' => $choices,
            ]);
        });
```

I am closing here as this is not something that we will change in the Form component. Thank you for understanding.
