### ISSUE TITLE
Use absolute path instead of relative path

### ISSUE THREAD

**Issue by utkarsh2102** [symfony/symfony#41637]
Hello,

Thanks for your work so far!

However, whilst running tests in Debian & Ubuntu, I found that the following lines in the tests are using relative path instead of what can be an absolute one, instead.

https://github.com/symfony/symfony/blob/d1b81fbc324cf5703f44276021ee98f6c74f4b93/src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php#L992-L1002

Rationale: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#require-relative-hardcoding-lib-rationale
(this doc is for Ruby stuff but the "rationale" is generic enough to give you an idea behind this issue).

Please let me know if I can help make things more clearer or whatever. Thanks, again! 🎉

**Comment by stof** [comment]
I don't understand what you mean. Those path are absolute paths

**Comment by xabbuh** [comment]
closing as explained by @stof
