### ISSUE TITLE
Custom Translation Loader not working

### ISSUE THREAD

**Issue by PascalBieske-Dynalinq** [symfony/symfony#41648]
**Symfony version(s) affected**: 5.2.10

**Description**
I want to run a multi tenant Symfony applications and for it I want to implement a custom translation file loader.

According to the documentation it should be very easy: https://symfony.com/doc/current/reference/dic_tags.html#dic-tags-translation-loader

But my custom Translation Loader is never called.

**How to reproduce**
services.yaml
```
services:
  App\Translation\ProjectYamlLoader:
      tags:
        - { name: translation.loader, alias: yaml }
```

src/Translation/ProjectYamlLoader.php
```
<?php

namespace App\Translation;

use Symfony\Component\Translation\Exception\InvalidResourceException;
use Symfony\Component\Translation\Exception\LogicException;
use Symfony\Component\Translation\Loader\FileLoader;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Parser as YamlParser;
use Symfony\Component\Yaml\Yaml;

/**
 * YamlFileLoader loads translations from Yaml files.
 *
 */
class ProjectYamlLoader extends FileLoader
{
    private $yamlParser;

    /**
     * {@inheritdoc}
     */
    protected function loadResource($resource)
    {
        if (null === $this->yamlParser) {
            if (!class_exists(\Symfony\Component\Yaml\Parser::class)) {
                throw new LogicException('Loading translations from the YAML format requires the Symfony Yaml component.');
            }

            $this->yamlParser = new YamlParser();
        }

        try {
            $messages = $this->yamlParser->parseFile($resource, Yaml::PARSE_CONSTANT);
        } catch (ParseException $e) {
            throw new InvalidResourceException(sprintf('The file "%s" does not contain valid YAML: ', $resource).$e->getMessage(), 0, $e);
        }

        if (null !== $messages && !\is_array($messages)) {
            throw new InvalidResourceException(sprintf('Unable to load file "%s".', $resource));
        }

        return $messages ?: [];
    }
}
```

I am sure the class and function `loadResource` is not called. I added for example a breaking function `$die->here()` in `loadResource`, but no error is thrown.

**Comment by Seb33300** [comment]
Did you clear the cache after creating this class?

**Comment by PascalBieske-Dynalinq** [comment]
> Did you clear the cache after creating this class?

Yes, I have cleared the cache multiple times.

**Comment by yoannrenard** [comment]
I don't think you can do that as the translation file loader for 'yaml' has already been defined [here](https://github.com/symfony/framework-bundle/blob/5.3/Resources/config/translation.php#L81)

If your willing is to override it, you can, as a workaround, alias the 'translation.loader.yml' service.
This should work by adding the following snippet to your service definition
```yaml
translation.loader.yml:
        alias: App\Translation\ProjectYamlLoader
```

Hope that helps

**Comment by PascalBieske-Dynalinq** [comment]
That helped a lot. With this I got it working now. Thanks!
