### ISSUE TITLE
[FrameworkBundle] Denormalization doesn't read phpDoc to guess type

### ISSUE THREAD

**Issue by wuchen90** [symfony/symfony#41642]
**Symfony version(s) affected**: 5.3.0

**Description**
When I try to denormalize to a class with properties that are typed with phpDoc, the properties of the resulting object are not denormalized.

**How to reproduce**

```PHP
class Foo {
    /**
     * @var \DateTimeInterface
     */
    public $date;
}

$data = [
    'date' => '2021-01-01 00:00:00',
];

$result = $serializer->denormalize($data, Foo::class);

// $result->date === '2021-01-01 00:00:00' instead of instance of \DateTimeImmutable
```

**Possible Solution**

The bug is created by this PR https://github.com/symfony/symfony/pull/40140.
https://github.com/symfony/symfony/blob/d1b81fbc324cf5703f44276021ee98f6c74f4b93/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1804
`ContainerBuilder::willBeAvailable` returns `false` when we have `$parentPackages` that is installed in dev requirements AND in no-dev requirements.

If I have `symfony/framework-bundle` explicitly in my dev requirements and `doctrine/mongodb-odm-bundle` which requires `symfony/framework-bundle` in my no-dev requirements, the `Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor` service won't be loaded and serialization with phpDoc typehint will fail.

**Comment by nicolas-grekas** [comment]
Can you please share a small reproducing app?

**Comment by nicolas-grekas** [comment]
I think the issue is because `symfony/framework-bundle` is a non-dev dependency, transitively.

**Comment by wuchen90** [comment]
@nicolas-grekas 
Here it is https://github.com/wuchen90/issue/tree/symfony-41642 and the test class https://github.com/wuchen90/issue/blob/symfony-41642/tests/src/GH41642Test.php.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer. I confirm my diagnostic: `doctrine/mongodb-odm-bundle` requires `symfony/framework-bundle`, so that `symfony/framework-bundle` is not a dev dep, while `phpdocumentor/reflection-docblock` is a dev-dep, thus it's not available in non-dev mode.
