### ISSUE TITLE
There is currently no session available.

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#41654]
I migrate symfony 5.2.x to symfony 5.3.1

I want to fix deprecated message : 

```
Since symfony/framework-bundle 5.3: The "Symfony\Component\HttpFoundation\Session\SessionInterface" and "SessionInterface" aliases are deprecated, use "$requestStack-&gt;getSession()" instead. It is being referenced by the

```

I change on my service

```php

 public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

```

to 

```php

 public function __construct(RequestStack $requestStack)
    {
        $this->session = $requestStack->getSession();
    }

```

my service is a listener call on **kernel.event_listener**

```php

tags:
    - { name: kernel.event_listener, priority: -10 }
   
```
the result is a 

![image](https://user-images.githubusercontent.com/10476280/121528885-28e57500-c9fc-11eb-8712-e245042306f0.png)

I read similary issue #40778 but can't understand how to resolve that on my listener.
Problem's is the listener ? priority ?

I callback to SessionInterface temporarily

@jderusse do you have idea ?

**Comment by jderusse** [comment]
You should not store state in your service and should not call `$requestStack->getSession()` in the constructor.

Instead, call it when you need the session
```
    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function onFoo()
    {
        $session = $this->requestStack->getSession();
        // ....
    }
````

**Comment by thewalkingcoder** [comment]
Thanks you solve my problem ;-)

**Comment by thewalkingcoder** [comment]
Work's fine but Functionnal test failed with same message "There is currently no session available."

Before my functionnal test i call service (who use requestStack) to force/simulate saving context with 

```php

 static::getContainer()->get(myservice)

```
my test/framework.yaml
```
framework:
    test: true
    session:
        storage_id: session.storage.mock_file

```

i must change logic ?

**Comment by jderusse** [comment]
You need to set a session in you  request when unint testing your service, or running you test in a request/response context.  maybe similar to #41590

**Comment by thewalkingcoder** [comment]
ok i explain the application logic.

After authenticated, user must select a workspace (the listener check if  specific session exist, and redirect to select form is not, after select, session is created and user redirect to homepage). Work's fine.

When create functionnal test , i authenticate user with `client->loginUser` and util now, pre-save session workspace to test other functionality.
Work's fine when call my service and use `SessionInterface`

```php

$workspaceSelectedRepository = static::getContainer()->get(WorkspaceSelectedRepository::class);
$workspaceSelectedRepository->save($workspace)
```

```php

declare(strict_types=1);

namespace App\Account\Infrastructure\Persistence;

use App\Account\Domain\Interfaces\WorkspaceSelectedRepositoryInterface;
use App\Account\Domain\WorkspaceSelected;
use Symfony\Component\HttpFoundation\RequestStack;

class WorkspaceSelectedRepository implements WorkspaceSelectedRepositoryInterface
{
    /**
     * @var RequestStack
     */
    private $requestStack;

    public const WORKSPACE_SELECTED = 'ssWorkspaceSelected';

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function getSession()
    {
        return $this->requestStack->getSession();
    }

    public function has(): bool
    {
        return $this->getSession()->has(self::WORKSPACE_SELECTED);
    }

    public function save(WorkspaceSelected $workspaceSelected): void
    {
        $this->getSession()->set(self::WORKSPACE_SELECTED, $workspaceSelected);
    }

    public function get(): ?WorkspaceSelected
    {
        return $this->getSession()->get(self::WORKSPACE_SELECTED);
    }

    public function delete(): void
    {
        $this->getSession()->remove(self::WORKSPACE_SELECTED);
    }
}
```
I try like `$this->client->loginUser` to create directly session

```php

$session = static::getContainer()->get('test.service_container')->get('session.factory')->createSession();
$session->set(WorkspaceSelectedRepository ::WORKSPACE_SELECTED, $workpace);
$session->save();
```
When try that i don't have ```SessionNotFound``` but when i read $client->response i have the form listener who ask to select workspace (specific session is like empty).

What's wrong ? i must had session to the client after ?

**Comment by thewalkingcoder** [comment]
i try with symfony/framework-bundle 5.3.x-dev` 5548342` same result

**Comment by thewalkingcoder** [comment]
Instead of create session before request, i try with your recommandations to set with client request/response context and works fine .

```php

$crawler = $this->client->request('GET', self::HOST.'workspace-select');
$validateButton = $crawler->selectButton('Valider');
$form = $validateButton->form([], 'POST');
$form['account_workspace[workspace]']->disableValidation()->select($idworkspace);
$this->client->submit($form);

```

Thanks @jderusse
