### ISSUE TITLE
Getting exception in serializer from PropertyAccessor when reading is.... method with no obvious property

### ISSUE THREAD

**Issue by AntonioCS** [symfony/symfony#41652]
**Symfony version(s) affected**: v5.2.6
symfony/property-access              v5.2.4

**Description**
I am trying to serialize a `User` object. The original class is from `nucleos/user-bundle`  (v1.9.0) https://github.com/nucleos/NucleosUserBundle/blob/1.10.x/src/Model/User.php

This class has a method called `isPasswordRequestNonExpired` https://github.com/nucleos/NucleosUserBundle/blob/1.10.x/src/Model/User.php#L364

So when I try to serialize the `User` class I get the following error:

![image](https://user-images.githubusercontent.com/1086401/121509202-4efc1c80-c9de-11eb-8e0c-dbebb1a488d0.png)

Where this is happening I am passing the `Serializer` via DI so it has all the defaults.
I thought the job of the `PropertyAccessor` was to access properties and not methods. As you can see from the code that method does not have a corresponding property. There seems to be a way in the `PropertyAccessor` to silence this exception but I have no way to access it from the `Serializer`.

**How to reproduce**
Get the  `nucleos/user-bundle` and try to serialize the `User` class

**Possible Solution**

**Additional context**

**Comment by AntonioCS** [comment]
To quickly fix this I added this in the `User` class:

```
use Symfony\Component\Serializer\Annotation\Ignore;

.....
    /**
     * @Ignore
     */
    private $passwordRequestNonExpired;

    /**
     * @Ignore
     */
    private $group;

    /**
     * @Ignore  
     */
    private $equalTo;
.....
   ```
I wish there was a way to not have to do this but as things need to progress, this is what had to do to quite the exception.

**Comment by alexandre-daubois** [comment]
Hi! You're trying to serialize your attribute with a method that takes one argument, `$ttl`. I may be wrong, but I think the Serializer can't use your method, because it simply doesn't know how to treat the argument `$ttl`.

As you can see, all other `is...` methods takes no argument.
I'd say it's a problem from your code, and not a Symfony's bug.

**Comment by AntonioCS** [comment]
But why is the `PropertyAccessor` looking at methods? This is just a convenience method, it is not attached to a property. Why is this default behaviour?

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
