### ISSUE TITLE
[Runtime] Command with "e" option fails

### ISSUE THREAD

**Issue by JakeFr** [symfony/symfony#41658]
**Symfony version(s) affected**: 5.3

**Description**
In a standalone console application, one of the command defines an option with a shorcut "e".
With the runtime component, the command fails with the error message
**An option with shortcut "e" already exists.**

**How to reproduce**
Here a minimum code to reproduce
https://gist.github.com/JakeFr/8d3641ac2e7043dc3eba2a497da65494
Application and included commands work fine
`./test.php`
`./test.php list`
`./test.php help`
but the command returns the error
`./test.php test`
`./test.php test -e`
`./test.php help test`

**Possible Solution**
It looks related to
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Runtime/Runner/Symfony/ConsoleApplicationRunner.php#L48
This test doesn't detect the option

**Comment by alexandre-daubois** [comment]
Hi! The line you're pointing out is executed way before your command actually runs.
This line seems to try to add `env` option to your application, globally. Before your command is even executed. @nicolas-grekas, who wrote this code will surely correct me if I'm wrong :smile: 

I would say that this option is simply reserved and you cannot use `e` shortcut. Which make sense.

**Comment by JakeFr** [comment]
Yes, the error comes with the command, not the application, so too late.

I deal with an legacy application which doesn't respect symfony convention.
If I add the env to the options, it works fine.
`$_SERVER['APP_RUNTIME_OPTIONS'] = ['env' => 'prod'];`
and the options are not added.

I could also create my own runner.

**Comment by nicolas-grekas** [comment]
This will be fixed by #41675
But you'll have to update your code to return the command, not the application:
```php
return function () {
     return new \TestCommand();
};
```
