### ISSUE TITLE
In debug mode, the cache component could throw when save() fails

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#41685]
In debug mode, the cache component could throw when save() fails

This would not be compliant with PSR-6, but in debug mode, that's fine really.

This might help spot situations where eg a Closure is (not) cached.

**Comment by rvanlaak** [comment]
@nicolas-grekas can you use my help with this? Sounds helpful to me! 

I've taken a look into the `CachePoolPass` to determine whether a decorator-strategy would be an option to address this issue.

As preparation for this issue I've made an attempt to refactor the `CachePoolPass` by isolating behavior in several private methods. But, commit 33a095dbf6f7333346f625f36770e8678b68f6bb on branch 6.0 makes it hard to write a "refactor PR" for branch 5.4 that could later get merged upwards. For now just created PR #42192 to add test coverage on an exception, and rename an internal variable to prevent future bugs.

**Comment by nicolas-grekas** [comment]
Your help would be welcomed! No worries for 33a095d, we'll handle the conflict resolution.
