### ISSUE TITLE
Problem after Upgrade to 5.3.1

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#41699]
Hi I make an entity user and use username for login ( Username must be 8 digits ):

src\Entity\User.php
```
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Error: Fill username field!")
     * @Assert\Regex(
     *   pattern="/^\d{8}$/",
     *   message="Error: Username invalid!"
     * )
     */
    private $username;
```
	
But when I hack codes and add `novalidate `to `<form>` and with empty username field, submit the form, this error show for me:

`Expected argument of type "string", "null" given at property path "username".`

When I use Symfony 5.2 this codes worked but when I upgrade to Symfony 5.3 this error show!

How can I fix this problem?

**Comment by xabbuh** [comment]
Can you please show the code of your setter method in the `User` class?

**Comment by karaka200** [comment]
```
    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

```

`@Assert\NotBlank` and `@Assert\Regex` are not worked!

**Comment by xabbuh** [comment]
Your setter method does not allow `$username` to be `null`. You need to adapt it like this:

```php
public function setUsername(?string $username): self
{
    $this->username = $username;

    return $this;
}
```

Alternatively, you can set the `empty_data` option to the empty string to let the Form component pass a string instead of `null`.

In any case, this is not an issue in the Form component, but in the code using it. Therefore, I am going to close here. Thank you for understanding.

**Comment by karaka200** [comment]
Thanks @xabbuh 

But `@Assert\Regex` not worked and form valid!

**Comment by xabbuh** [comment]
Please create a small example application that allows to reproduce your issue.
