### ISSUE TITLE
Javascripts block position in base.html.twig 

### ISSUE THREAD

**Issue by adam314315** [symfony/symfony#41694]
The default base.html.twig Twig file currently includes the javascripts block in the title section  of the page. Shouldn't it be move at the bottom of the page as Google recommandation load JavaScript last as much as possible
https://developers.google.com/apps-script/guides/html/best-practices 

So moving from this version 
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>
```

to this one 

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </body>
```
</html>

**Comment by wouterj** [comment]
Hi! Thanks for taking the time to create an issue about this topic, @adam314315 !

However, we've recently moved the script tag from the end of the `<body>` to the `<head>`. This change is explained by this blogpost (including some examples): https://symfony.com/blog/moving-script-inside-head-and-the-defer-attribute

**Comment by adam314315** [comment]
Thanks for the change which corresponds to the bug mentioned. Yet when you create a new project with `symfony new --full myproject` , the base.html.twig file still looks as the file below. Just start a new symfony project to retest.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

```

**Comment by stof** [comment]
@adam314315 I don't understand why you say `it still looks`. The right sentence is `it now looks`. We moved script *to the head*, not away from it. So this template looks exactly as expected.

**Comment by adam314315** [comment]
@stof  Just repoduce these steps from terminal:
1. symfony new --full myproject
2. cat myproject/templates/base.html.twig
3. and you will get this with javascripts block style in title block instead of at the bottom of body
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>
```

**Comment by wouterj** [comment]
Yes, that's expected. The javascript block *should be in the `<head>`*. See the blogpost for the details about this change

**Comment by adam314315** [comment]
Ok. Just saw and read again the full details. It sounds a bit strange to me to heavily recommend the use of defer for all script rather than positioning at the bottom as there is no guarantee the defer wouldn't impact the script execution, specially when you have to include several scripts in some projects. 

But if it was decided and is assumed as it is I am fine. I will then either follow this rule or reposition at the bottom for my own projects.

**Comment by stof** [comment]
>  as there is no guarantee the defer wouldn't impact the script execution, specially when you have to include several scripts in some projects.

`defer` actually guarantees that script gets executed in the order in which they appear (unless the browser does not respect the HTML spec, but then it is their issue).
