### ISSUE TITLE
Built-in ArgumentValueResolver for UIDs

### ISSUE THREAD

**Issue by logarytm** [symfony/symfony#41690]
**Description**
I use UUIDs (provided by the excellent Symfony UID component) as entity IDs in my project. Because of this, I also have UUID parameters in my routes. To keep the code clean from explicit conversions, I would like to be able to receive the parameter value as a `Uuid` instance in a controller action:

```php
use Symfony\Component\Uid\Uuid;

/**
 * @Route("/frog/{id}")
 */
public function get(Uuid $id)
{
    return $this->render('frog.html.twig', ['frog' => $this->frogs->find($id)]);
}
```

instead of:

```php
use Symfony\Component\Uid\Uuid;

/**
 * @Route("/frog/{id}")
 */
public function get(string $id)
{
    $id = Uuid::fromString($id);

    return $this->render('frog.html.twig', ['frog' => $this->frogs->find($id)]);
}
```

**Example**
For now, I use the following implementation of `ArgumentValueResolverInterface`:

```php
namespace App\ArgumentResolver;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface;
use Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadata;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;

class UuidArgumentResolver implements ArgumentValueResolverInterface
{
    public function supports(Request $request, ArgumentMetadata $argument): bool
    {
        return (
            !$argument->isVariadic()
            && is_a($argument->getType(), Uuid::class, /* allow_strings */ true)
            && $request->attributes->has($argument->getName())
        );
    }

    public function resolve(Request $request, ArgumentMetadata $argument): iterable
    {
        try {
            yield Uuid::fromString($request->attributes->get($argument->getName()));
        } catch (\InvalidArgumentException $e) {
            throw new BadRequestHttpException();
        }
    }
}
```

Perhaps this could one day be handled by default?

**Comment by OskarStark** [comment]
cc @fancyweb

**Comment by fancyweb** [comment]
I can agree on the idea but I am not sure about the execution because I think we would need at least one option: to be able to restrict the accepted input format(s) (eg: accept `/frog/017a0a11-838f-41b1-fa7e-5b5566f08cbd` but not `/frog/1BaRufbM9LrGKdQGfoKu4G`).
Also, IIRC @OskarStark you extend Symfony's ULIDs with your own domain class (eg: `class ProductId extends Ulid`), so we would also need an option to choose the class we instantiate? That's something we should add in `UidNormalizer` too btw? Or it would not be usable by everyone.
`ArgumentValueResolver` don't have options but a `ParamConverter` could do the job.

**Comment by jvasseur** [comment]
@fancyweb Argument value resolvers can have options since https://github.com/symfony/symfony/pull/37829 I think the long term goal is to completely remove param converters in favor of argument resolvers, we just have a bit more work to do to be there.

**Comment by fancyweb** [comment]
But can we make a feature that works only with PHP8 on 5.4?

**Comment by stof** [comment]
The case of custom child classes does not require an attribute-based configuration: argument resolvers have access to the typehint to choose the class.

**Comment by derrabus** [comment]
> But can we make a feature that works only with PHP8 on 5.4?

Yes!

**Comment by fancyweb** [comment]
@logarytm Do you want to work on it?

**Comment by logarytm** [comment]
Yes, absolutely.
