### ISSUE TITLE
HTML form rendering

### ISSUE THREAD

**Issue by adam314315** [symfony/symfony#41691]
According to Boostrap documentation best practice for form creation is the following
```
  <div class="form-group">
    <label for="formGroupFirstNameInput">First name</label>
    <input type="text" class="form-control" id="formGroupFirstNameInput" placeholder="First name input">
  </div>

```
Whereas the Symfony forms component using form_row 
```
<div class="form-group">
    {{ form_row(form.firstName) }}
</div>
```

will translate  into HTML with an extra `<div>...</div>` around label and input tags as follows :
```
<div class="form-group">
  <div>
  <label for="user_form_firstName">First Name</label>
  <input type="text" id="user_form_firstName" name="user_form[firstName]" class="form-control mt-1 mb-4"></div>
</div> 
</div> 
```

I think this extra extra `<div>...</div>`  should be then removed as it is not needed and this will help to remain inline with Bootstrap guidelines.

**Comment by xabbuh** [comment]
Which one of the Bootstrap form themes are you using?

**Comment by adam314315** [comment]
I am using the default built-in form themes from Symfony and didn't add any external css. The extra div mention can be found in both Boostrap 4 and 4 form_row definition. Let me know if you want me to submit a pull request with sugggestion of fix. 


Boostrap 4 form_row
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
``
```
{% block form_row -%}
    {%- if compound is defined and compound -%}
        {%- set element = 'fieldset' -%}
    {%- endif -%}
    {%- set widget_attr = {} -%}
    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
    {%- endif -%}
    <{{ element|default('div') }}{% with {attr: row_attr|merge({class: (row_attr.class|default('') ~ ' form-group')|trim})} %}{{ block('attributes') }}{% endwith %}>
        {{- form_label(form) -}}
        {{- form_widget(form, widget_attr) -}}
        {{- form_help(form) -}}
    </{{ element|default('div') }}>
{%- endblock form_row %}
```


Boostrap 5 form row 
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_5_layout.html.twig
```
{%- block form_row -%}
    {%- if compound is defined and compound -%}
        {%- set element = 'fieldset' -%}
    {%- endif -%}
    {%- set widget_attr = {} -%}
    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
    {%- endif -%}
    {%- set row_class = row_class|default(row_attr.class|default('mb-3')|trim) -%}
    <{{ element|default('div') }}{% with {attr: row_attr|merge({class: row_class})} %}{{ block('attributes') }}{% endwith %}>
        {%- if 'form-floating' in row_class -%}
            {{- form_widget(form, widget_attr) -}}
            {{- form_label(form) -}}
        {%- else -%}
            {{- form_label(form) -}}
            {{- form_widget(form, widget_attr) -}}
        {%- endif -%}
        {{- form_help(form) -}}
        {{- form_errors(form) -}}
    </{{ element|default('div') }}>
{%- endblock form_row %}
```

**Comment by xabbuh** [comment]
So, are you using the Bootstrap 4 or Bootstrap 5 form theme?

**Comment by adam314315** [comment]
The 2 have the same extra div. So using 4 or 5 doesn't change the bug reported.

**Comment by xabbuh** [comment]
The code is a bit different. The Bootstrap 4 template should already render the `form-group` class when using the `form_row()` function. That's the reason it would be interesting to find out why it isn't rendered in your case.

Can you create a small example application that allows us to reproduce the class not being rendered with the Bootstrap 4 theme?

**Comment by adam314315** [comment]
You can find the test online at this URL with simple contact form with name and message fields : http://94.23.252.41:8004/contact

Twig file 
```
{{ form_start(form) }}
<div class="form-group col-md-4">
    {{ form_row(form.name) }}
</div>
<div class="form-group col-md-4">
    {{ form_row(form.message) }}
</div>
{{ form_end(form) }}
```

Will generate generate the following HTML code with extra div
```
<div class="form-group col-md-4">
    <div>
        <label for="contact_form_name">Name</label>
        <input type="text" id="contact_form_name" name="contact_form[name]" class="form-control" placeholder="">
    </div>
</div>
```

instead of the following according to Boostrap recommandation
```
<div class="form-group col-md-4">
    <label for="contact_form_name">Name</label>
    <input type="text" id="contact_form_name" name="contact_form[name]" class="form-control" placeholder="">
</div>
```

**Comment by xabbuh** [comment]
Please add the code somewhere to make it available through git. Without looking at the code we are not able to inspect what is going wrong.

**Comment by adam314315** [comment]
Code available here : https://github.com/adam314315/sf0

**Comment by xabbuh** [comment]
I may be missing something, but where do you configure the form theme to be used?

**Comment by stof** [comment]
This project is **not** using the built-in Symfony form themes based on Bootstrap. It does its own rendering of forms. So this is not an issue in Symfony but in the project (you should be using the `row_attr` option to put the `form-group` class on the div rendered by `form_row` instead of adding a wrapper div manually)

**Comment by adam314315** [comment]
@stof You are right. row_attr is the correct attribute to use and it fixed my issue. Thanks.

**Comment by stof** [comment]
@adam314315 you should also consider using the built-in Bootstrap themes, as the Symfony community already took care of the work.

**Comment by adam314315** [comment]
Ok. Can you share the link to start looking at the built-in Bootstrap themes? 
Are you referring to this documentation : https://symfony.com/doc/current/form/bootstrap4.html

**Comment by xabbuh** [comment]
Yes, that document should help you getting things running.
