### ISSUE TITLE
Symfony 5.3:  the csrf token is invalid on all form protected by CSRF when using "remember me" 

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#41707]
**Symfony version(s) affected**: 5.3.1

**Description**

I've upgraded from Symfony 5.2 to 5.3.1 and since then, in production submitting any form protected by CSRF fail with

the csrf token is invalid. please try to resubmit the form

Even form not handle by me (for example I have EasyAdminBundle and they fail too)

**How to reproduce**

1. Install Symfony + EasyAdminBundle 
2. for session I use 

```
framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
```

3.login in EasyAdmin
4. try to submit a form -> you got the error 

**Possible Solution**

**Additional context**

Is it related to https://github.com/symfony/symfony/pull/39919 ?

it happens only in production

**Comment by derrabus** [comment]
Are you able to provide a reproducer application for us?

**Comment by enzobrigati** [comment]
Same things for me and I'm not using EasyAdminBundle...

**Comment by derrabus** [comment]
@Brigat0 Same question for you then. 🙃

**Comment by enzobrigati** [comment]
I found what is going on.
It happens when the prod is in HTTP, if you're using HTTPS CSRF are working

**Comment by allan-simon** [comment]
interesting on my side  the production is in https, but it's true my dev environment is not

**Comment by allan-simon** [comment]
@derrabus  I will try to make one

**Comment by xabbuh** [comment]
Let's close here for now. We can consider to reopen once we are able to reproduce this.

**Comment by allan-simon** [comment]
I will post today a reproductible repository but here basically what is needed  (can reproduce with 5.3.3)

   * a firewall protected form  ( I created a Smurf entity with simply a 'name' attribute,  and a crud with `make:crud` ) 
   * a firewall with remember-me activated 

adding/removing the remember part in the yaml trigger or remove the bug 

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        admins:
            entity:
                class: 'App\Entity\Admin'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admins:
            pattern: ^/
            provider: admins
-            remember_me:
-                secret: '%kernel.secret'
-                lifetime: 604800 # 1 week in seconds
-                path: /
-                always_remember_me: true

            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path: logout
                target: login
            # configure the form authentication as the entry point for unauthenticated users
            entry_point: form_login
    encoders:
        # use your user class name here
        App\Entity\Admin:
            algorithm: auto


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ADMIN}

```

**Comment by allan-simon** [comment]
https://github.com/allan-simon/symfony_reproduce_bug_41707
@xabbuh  here's the repository reproducing the issue , with the explanation in the above comment, can we reopen this issue ? :) 

seems to be due to the remember-me feature, which would not be surprising as it has been revamped in 5.3 if my understanding is correct   @wouterj  ?

**Comment by allan-simon** [comment]
note: i reproduce it when on https

**Comment by allan-simon** [comment]
@xabbuh ping ?  it's blocking me from upgrading to 5.3 :)

**Comment by ovidals** [comment]
Same here, CRSF not working when trying to update to 5.3. 

{"message":"Invalid CSRF token."}

**Comment by ibanson** [comment]
Same here !  But I do not use a "Remember me".
But on Symfony docs, I can read :

> For example, you may see an “Invalid CSRF token” error because two requests were made in parallel and only the first one stored the CSRF token in the session.
 
Source => https://symfony.com/doc/current/session/database.html

Maybe that info can be useful.

**Comment by wouterj** [comment]
Hi there! So this is obviously a bug, given many people can confirm it. There is no need to add more "same here" comments.

There is a reproducer application - and you all have reproducer applications - who is up to debug what is going on here? Some pointers:
- the [`FormTypeCsrfExtension`](https://github.com/symfony/symfony/blob/d642f76b55e4b116b899f2e55c63f623e1380db5/src/Symfony/Component/Form/Extension/Csrf/Type/FormTypeCsrfExtension.php) handles creating the token in forms and the [`CsrfValidationListener`](https://github.com/symfony/symfony/blob/d642f76b55e4b116b899f2e55c63f623e1380db5/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php) validates the token for forms. Does something in these classes change incorrectly if you enable remember me (e.g. the `tokenManager` or `tokenId`)?
- the remember me system was rewritten in 5.3: https://github.com/symfony/symfony/pull/40145 Maybe, if you know what difference caused Form CSRF to no longer work, you can see what change caused CSRF to mess up?

**Comment by wouterj** [comment]
This might also be related to https://github.com/symfony/symfony/pull/39919

**Comment by cmmata** [comment]
@ovidals and I were able to fix our error, we are finally not receiving the CSRF invalid token. We defined a custom authenticator, [like in the official documentation](https://symfony.com/doc/current/security/authenticator_manager.html#passport-badges), and the login process was returning that CSRF error. Then debugging we found that the CSRF ID was wrong, so in `LoginAuthenticator:authenticate` method instead of having

```
return new Passport(
            new UserBadge($username),
            new PasswordCredentials($password),
            [new CsrfTokenBadge('login', $csrfToken)]
        );
```

We replaced to
```
return new Passport(
            $user,
            new PasswordCredentials($password),
            [new CsrfTokenBadge('authenticate', $csrfToken)]
        );
```

And now it's working. Maybe it's only our particular case, but I came to explain it here just in case someone else had the same error.

**Comment by allan-simon** [comment]
@ovidals , is the problem still fixed if you put `            [new CsrfTokenBadge('login', $csrfToken)]`  like in your first code ?

**Comment by ovidals** [comment]
@allan-simon, @cmmata was who fixed the issue with his last comment approach. With 'login' the CSRF token does not work but it does with 'authenticate'.

**Comment by wouterj** [comment]
The CSRF token id must be equal in order to verify the token correctly. So make sure that the CSRF token id in `CsrfTokenBadge` (the 1st argument) equals the CSRF token id used in the login form (e.g. using `{{ csrf_token(...) }}` in Twig or `csrf_token_id` form option)

**Comment by wouterj** [comment]
@allan-simon I just tried your reproducer app and it works as expected for me. From scratch, I'm able to login and post a valid form submissions to create new smurfs. If I add the remember me snippet you showed here, I can still login and post valid form submissions.

Are you sure this exact application reproduces it on your side? If that's the case, I think you'll have to try to debug this on your side

**Comment by allan-simon** [comment]
@wouterj  have you tried in https (on my side I was only able to reproduce it on production-ish environment) ? ,  I will try to recheck on my side to see if I missed something while creating the repo

**Comment by wouterj** [comment]
Yes, I used the Symfony CLI server with https enabled. (I also removed my session, to force authentication through remember me, but I somehow still wasn't able to reproduce).

**Comment by S-Tian86** [comment]
Hi,
I have the same error and I'm not using remember me

@wouterj Here is my application, you will have to set up a mysql/mariadb database and run the migrations and datafixtures if you want to test with data.

[S-Tian86/symfony_reproduce_bug_41707](https://github.com/S-Tian86/symfony_reproduce_bug_41707)

I hope you can use it to debug what happens.

Here the discussion where I tried to debug something.

https://github.com/symfony/symfony/discussions/42606#discussioncomment-1203963

Edit: I run the app in IIS in http://localhost:81

**Comment by allan-simon** [comment]
note that I reproduce it  while using persisted remember token too

**Comment by allan-simon** [comment]
so I tried again to upgrade to symfony 5.3  and here some more observation  ( I still have the issue in our staging and not locally)

1.  it is not a http vs https issue,   if i deactivate https I still have the issue
2.  it is not a  APP_ENV=prod  vs APP_DEV=dev issue ,   switching from one to the other still show the issue

however  if I deploy the very same code on a EC2  I  don't have the issue
if I deploy it on AWS Lambda using the bref.sh layer,  i have the issue ,  though both use the very same version of php  

I will try to dig more now that I have a lambda with dev mode activated that reproduce the issue, to add more dump here and there.

**Comment by allan-simon** [comment]
ok I'm making progress,  I've activated the web profiler in lambda in "prod" setting and so I'm able to add `dump` here and there

so first finding ,  the  token is considered invalid because of this test fail 

https://github.com/symfony/security-csrf/blob/5.3/CsrfTokenManager.php#L111

```
    public function isTokenValid(CsrfToken $token)
    {
        $namespacedId = $this->getNamespace().$token->getId();
        if (!$this->storage->hasToken($namespacedId)) {
            return false;
        }
```

the hasToken returns false

the namespaceid  variable value 

```
https-CompanyAdmin
```
(it's the name of the entity of the form)

and the `storage` being an instance of `symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage`

**Comment by allan-simon** [comment]
The session itself  has the following property key

`_csrf/https-CompanyAdmin`  ,  so this is weird because the check done is this 

https://github.com/symfony/security-csrf/blob/5.3/TokenStorage/SessionTokenStorage.php#L101

**Comment by allan-simon** [comment]
ok it seems the problem is because it does create a new session before doing the  check,   i  think the problem is here "why does it start a new session" :thinking:

**Comment by allan-simon** [comment]
other weird things is that I don't see in doctrine any call to  the table `session` even though I use the PDOSessionHandler 
Edit : ok PDOSessionHandler does not use doctrine, hence why the query are not logged

(I use it because otherwise , on AWS Lambda,  there's some chance that a new request will start on a completly new instance, and hence I can't rely on local storage/memory for session keeping)

**Comment by allan-simon** [comment]
ok after digging even deeper  , it seems the session id  use to write in the GET is not the same as the one used to read in the POST :scream:

**Comment by allan-simon** [comment]
in my cookie I indeed don't get any  PHPSESSID , only REMEMBERME , so I think PHPSESSID get erased somehow

**Comment by allan-simon** [comment]
if I comment the following line  in AbstractRememberMeHandle https://github.com/symfony/security-http/blob/5.3/RememberMe/AbstractRememberMeHandler.php#L117-L127  ,  I don't have the issue  , i'm getting close

**Comment by allan-simon** [comment]
I will stop for now  because I've deleted the REMEMBERME token and now I can't login anymore regardless of what i do (i see the POST  is actually login me , but then the redirect GET  logs me out :shrug , I think it's because of all the dump I've added here and there) I will start fresh tomorrow but my current understanding of the original problem is : 

   I see the CSRF token  because I don't get php session id set, so at each request a new session is started, so the csrf token is lost in a previous session,
     BUT due to the rememberme  cookie, i'm still considered as logged ,  so i'm not redirected to the login even though i have an empty session

**Comment by allan-simon** [comment]
which mean that currently the remember me cookie is set at every Response, is it expected @wouterj  ?

**Comment by allan-simon** [comment]
now the weird things is that  I don't have a set cookie for REMEMBERME when in local environment :thinking:   (even though i have 'APP_ENV=prod' in local environment )

**Comment by allan-simon** [comment]
ok I think it's due me being login from before the activation of rememberme/symfony5.3,  but now I hit an other issue , if logged out, I can't login anymore ... because the session id is regenerated during the POST /login by symfony due to a "MIGRATE" session strategy..... 

ok i see , it regenerates an id  to avoid a "session fixation" attack, but somehow the new session is not communicated back to the browser

**Comment by allan-simon** [comment]
ok I think i found out , that it was a ALB issue with bref.sh (actually the fact that  I was using lambda) 
by default ALB with a Lambda target group will only keep the last http header  if there are  some duplicate ones , but `Set-Cookie`  in my case was duplicated 
   * with REMEMBERME (as it was setting the phpsessionid and the rememberme, so rememberme was overwriting the php session id  cookie, causing the issue )
   *  with rememberme deactivated but the debug toolbar activated,   a post on login is doing a redirect, and a redirect with the debug toolbar activated  cause a setcookie , hence why i was having the issue only when re-loggin , because my other forms were not redirecting ...

so here the issue was only triggered by symfony.53 and the way it handle remember me  rather than caused by symfony5.3 directly

I just do one last test to be sure  that now everything is ok and I will close this ticket 

EDIT  , yes it was that

**Comment by allan-simon** [comment]
so just if you run in a similar issue , try the following 

1.  edit your public/index.php  to only put 2 setcookie call (no symfony no nothing, just pure php)
2.   if you see only 1 set cookie,  it's because you have something in the middle of your stack that prevent multiple http header with the same name from being set.

**Comment by wouterj** [comment]
Thanks for all the debugging work here @allan-simon ! Really happy you managed to find the issue and share the fix :)

**Comment by Adi-18** [comment]
I am on Symfony 6.0.0 and have this error.

I see both setcoockies from public/index.php

I cannot use https  because of internal local access without certificate

What have I to do to solve this problem? I am not much familiar with symfony.

**Comment by scorpioniz** [comment]
I'm having same issue on Symfony 5.4. (actually started to get, after update from 5.3 to 5.4) But I notice that when I open prod, I instantly have PHPSESSID cookie set :) 
when I open my dev env site, I have no cookies at all. 
```
framework:
    session:
        handler_id: null # or session.handler.native_file is the same.
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
```

**Comment by dennned** [comment]
Hello, I am Symfony 5.4.1, i don't have {"message":"Invalid CSRF token."} on my dev env but on prod i reproduced it
ps : @allan-simon  hey

**Comment by WalkWeb** [comment]
Similar problem. No solution?

**Comment by allan-simon** [comment]
@dennned  @WalkWeb  have you checked if the issue is similar to mine ? i.e the load balancer or some piece of infrastracture in front of your code  "eat"  one of the "set cookie" ?

**Comment by TeLiXj** [comment]
I think that my case not is directly related but I come here after search the problem with CSRF.
For me, the problem appear after upgrading to 5.4 or 6.0. Then I saw the deprecation message _The "session.storage.factory.service" service is deprecated_ and added to `framework.yaml` the required configuration but I used `storage_factory_id: session.storage.factory.php_bridge` for some reason instead of the correct `storage_factory_id: session.storage.factory.native`. I hope it helps someone.

**Comment by antedom** [comment]
if you are on dev env and using base http for request then you should define cookie_secure: false. For https usage then cookie_secure should be set to true, because auto would not change properly to true (which is done with SessionListener)

**Comment by momox-maxim** [comment]
For `symfony 4.4.50` this helped to fix the bug that's only happening in localhost/dev environment using redis
`config/packages/dev/framework.yaml`
```
framework:
    session:
        handler_id: null
```


The official docs say it's a redis issue, https://symfony.com/doc/current/session.html#session-database
`Symfony will now use your Redis server ... For example, you may see an "Invalid CSRF token" error because two requests were made in parallel and only the first one stored the CSRF token in the session.
`
