### ISSUE TITLE
[yaml] !!timestamp tag leads to ParserException

### ISSUE THREAD

**Issue by chaosben** [symfony/symfony#41718]
**Symfony version(s) affected**: "symfony/yaml": "^5.3"

**Description**
Using the tag "!!timestamp" produces ```Symfony\Component\Yaml\Exception\ParseException```

**How to reproduce**
```php
<?php
use Symfony\Component\Yaml\Yaml;
require 'vendor/autoload.php';

$parsed = Yaml::parse("query_time: !!timestamp 2021-06-15T17:59:34.244Z");
/**
 * PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: 
 * The string "!!timestamp 2021-06-15T17:59:34.244Z" could not be parsed as it uses an unsupported built-in tag at line 1 
 * (near "query_time: !!timestamp 2021-06-15T17:59:34.244Z").
 */
```

**Comment by xabbuh** [comment]
Where did you find the `!!timestamp` tag?

**Comment by chaosben** [comment]
In the output of the dig-command:
```bash
$ dig +yaml symfony.org
-
  type: MESSAGE
  message:
    type: RECURSIVE_RESPONSE
    query_time: !!timestamp 2021-06-15T18:36:45.747Z
    response_time: !!timestamp 2021-06-15T18:36:45.782Z
    message_size: 56b
    socket_family: INET
    socket_protocol: UDP
```

**Comment by ro0NL** [comment]
@xabbuh see https://yaml.org/type/index.html

**Comment by xabbuh** [comment]
That's the 1.1 spec, but the Yaml component targets 1.2.

**Comment by ro0NL** [comment]
You're right. I'm confusing types and schemas.

IIUC it currently hits https://github.com/symfony/symfony/blob/2fe4442a1a28ea0d78bfe8d00476229e84ccf19c/src/Symfony/Component/Yaml/Inline.php#L723-L724 whereas it shoult hit https://github.com/symfony/symfony/blob/2fe4442a1a28ea0d78bfe8d00476229e84ccf19c/src/Symfony/Component/Yaml/Inline.php#L742

**Comment by xabbuh** [comment]
The second code block is for custom tags. Those must be prefixed with one `!`.

The current behaviour indeed is the right one according to the 1.2 spec. Maybe you can tell thee command to export YAML 1.2 compliant output. But there is nothing we can do here. So I'm closing this issue. Thank you for understanding.
