### ISSUE TITLE
Crawler removes document type definition (doctype)

### ISSUE THREAD

**Issue by Abdull** [symfony/symfony#41725]
**Symfony version(s) affected**:
`symfony/dom-crawler v5.3.0`.

Maybe relevant: `masterminds/html5 2.7.4` is also installed.

**Description**
Parsing an HTML document with `Crawler`, then retrieving the result, removes the leading document type definition, e.g. removes `<!DOCTYPE html>`.

**How to reproduce**

Taken from [`Crawler`'s own documentation](https://symfony.com/doc/current/components/dom_crawler.html#usage): 
```
use Symfony\Component\DomCrawler\Crawler;

$html = <<<'HTML'
<!DOCTYPE html>
<html>
    <body>
        <p class="message">Hello World!</p>
        <p>Hello Crawler!</p>
    </body>
</html>
HTML;

$crawler = new Crawler($html);

$htmlResult = $crawler->outerHtml();

/* $htmlResult will be missing <!DOCTYPE html>:

<html>
    <body>
        <p class="message">Hello World!</p>
        <p>Hello Crawler!</p>
    </body>
</html>

*/
```

**Comment by stof** [comment]
Well, getting the `outerHTML` of `document.documentElement` in your browser also does the same. A Crawler is a wrapper around a list of nodes (see what happens when using `->filter()` and so on) and the initial crawler when building from HTML is wrapping a list with a single element (the root node, i.e. `document.documentElement` in JS).
so I would not consider that a bug.

**Comment by Abdull** [comment]
> Well, getting the `outerHTML` of `document.documentElement` in your browser also does the same. A Crawler is a wrapper around a list of nodes (see what happens when using `->filter()` and so on) and the initial crawler when building from HTML is wrapping a list with a single element (the root node, i.e. `document.documentElement` in JS).
> so I would not consider that a bug.

Then what is the correct API of loading an HTML document, possibly manipulating it, then exporting it again, leaving doctype intact?

**Comment by stof** [comment]
Well, the DomCrawler use case was not actually to perform manipulation (which is why the Crawler API does not have any manipulation method btw). DomCrawler does not have an API to export the whole document.

**Comment by Abdull** [comment]
That wasn't clear to me from reading the current Crawler documentation and API. I expected `html()` and `outerHtml()` to output [either a valid XHTML or HTML5 document](https://softwareengineering.stackexchange.com/a/272220/50363), or at least to keep the output as close to the original input document as possible (compare https://github.com/symfony/symfony/issues/40502#issuecomment-862422261 ).

What about expanding the documentation and API source comments with this information?

**Comment by stof** [comment]
those methods are outputting the HTML of the node being selected in the crawler object.
