### ISSUE TITLE
Symfony 5.3: autoloader error with DoctrineTransportFactory

### ISSUE THREAD

**Issue by craue** [symfony/symfony#41727]
**Symfony version(s) affected**: >= 5.3.0 (just tested 5.3.0, 5.3.1, 5.3.2-dev#9485292)

**Description**
While running tests with Symfony 5.3 I'm getting [this error](https://travis-ci.org/github/craue/CraueGeoBundle/jobs/774461271#L609):
`RuntimeException: The autoloader expected class "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory" to be defined in file "/home/travis/build/craue/CraueGeoBundle/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php". The file was found but the class was not in it, the class name or namespace probably has a typo.`

I'm not actively using the Messenger component.

**How to reproduce**
Run the test suite of that bundle with latest dependencies.

**Possible Solution**
I _could_ work around the issue by removing `symfony/symfony` from the `require-dev` section in `composer.json` and explicitly defining the needed deps instead, but that would require further modifications to my test setup (to work with a range of Symfony versions) I'd like to avoid.

**Comment by Warxcell** [comment]
Got something similar here: https://travis-ci.org/github/Warxcell/files/jobs/773978302 

`ReflectionException: Class Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceivedStamp does not exist`

Not sure if it's connected.

**Comment by nicolas-grekas** [comment]
@Warxcell unrelated indeed, and already reported as #41748 and fixed by #41751

@craue you need to require `symfony/doctrine-messenger`, which is not "replaced" by `symfony/symfony`.

**Comment by craue** [comment]
@nicolas-grekas, I'm not using the messenger. So why would I need to add it as a dependency?

**Comment by nicolas-grekas** [comment]
I don't know honeslty. I just can tell you that for some reason, the test suite is trying to load this class, and that the failure can be worked around by adding this dependency...

**Comment by craue** [comment]
[This line](https://github.com/doctrine/DoctrineBundle/blob/2.4.2/DependencyInjection/DoctrineExtension.php#L1030) seems to trigger loading it.

**Comment by nicolas-grekas** [comment]
Thanks for investigating.
I'd suggest replacing this `class_exists()` check by `if (!$container->getReflectionClass(the-class, false)) {`.
PR welcome on DoctrineBundle

**Comment by craue** [comment]
@nicolas-grekas, thank you. This change would indeed fix the issue.
