### ISSUE TITLE
[RFC][Lock] Metadata aware locks

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#41730]
Hi,

WDYT about using a cache or metadata aware store to create metadata aware locks?

The use case we have is to store a username along with the lock, to be leveraged in case the lock is acquired.

**Comment by stof** [comment]
to be leveraged for what ?

**Comment by ro0NL** [comment]
as far as i can see now, it's for displaying purpose mostly. To show if an item is locked yes/no and by who.

Theoretically we could store it in ORM,  but ideally we bind to a specific lock context (given an item can have many locks for various purposes).

**Comment by ro0NL** [comment]
a cache aware lock something will work for us, i think.
