### ISSUE TITLE
getRootAliases can be null in ORMQueryBuilderLoader

### ISSUE THREAD

**Issue by Matts** [symfony/symfony#41731]
**Symfony version(s) affected**: 4.4.25

https://github.com/symfony/doctrine-bridge/blob/6.0/Form/ChoiceList/ORMQueryBuilderLoader.php#L72

**Description**
**Somehow**, getRootAliases can return null. This causes issues on the line shown above in the ORMQueryBuilderLoader. 
"current() expects parameter 1 to be array, null given"

This issue lays in symfony/form:4.4.25, in 4.4.19 this issue does not exist https://github.com/symfony/form/compare/v4.4.19...v4.4.25

**Possible Solution**

**Additional context**

**Comment by stof** [comment]
how is it related to the doctrine-bundle version ? It is not the one defining `QueryBuilder::getRootAliases`

**Comment by Matts** [comment]
Euh derp. I was still researching and accidently pressed Submit Issue.

**Comment by xabbuh** [comment]
Looking at the code (https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/QueryBuilder.php#L460-L476) I do not really see how that method can return `null`.

**Comment by Matts** [comment]
Me neither. I have been breaking my head over this for the past 2 days! Some how it is possible, because otherwise I would not be getting this error. Just cannot pinpoint WHERE. This happened after runnning composer update. These are my updates:

-snip-

**Comment by Matts** [comment]
Attempting to rollback doctrine dependencies, did not fix the issue

composer require "doctrine/doctrine-bundle:2.2.3" "doctrine/doctrine-migrations-bundle:3.0.2" "doctrine/migrations:3.1.0" "symfony/doctrine-bridge:4.4.19" "doctrine/dbal:2.12.1" "doctrine/inflector:1.4.3" "doctrine/cache:1.10.2" "doctrine/annotations:1.12.1" "symfony/security-acl:3.1.1" -W

- snip -

**Comment by Matts** [comment]
After reverting symfony/config symfony/form and uninstalling the php81 polyfill it works. Gonna do a little more research

**Comment by Matts** [comment]
The issue lays in symfony/form:4.4.25. When reverting that to 4.4.19 this issue does not occur.

https://github.com/symfony/form/compare/v4.4.19...v4.4.25

current() expects parameter 1 to be array, null given
 /var/www/vendor/symfony/doctrine-bridge/Form/ChoiceList/ORMQueryBuilderLoader.php:69
 /var/www/vendor/symfony/doctrine-bridge/Form/ChoiceList/DoctrineChoiceLoader.php:140
 /var/www/vendor/symfony/form/ChoiceList/LazyChoiceList.php:93
 /var/www/vendor/symfony/form/Extension/Core/DataTransformer/ChoicesToValuesTransformer.php:65
 /var/www/vendor/symfony/form/Form.php:1131
 /var/www/vendor/symfony/form/Form.php:638
 /var/www/vendor/symfony/form/Form.php:579

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
Let's close here for now. We can still reopen once we are able to reproduce.

**Comment by Matts** [comment]
yeah sorry few busy sprints for me. don't have too much time to create a
reproduction scenario atm. For now have just downgraded and locked
symfony/form to 4.4.19.

Will open once I have more time
