### ISSUE TITLE
Class incompatiblity between symfony/proxy-manager-bridge and laminas/laminas-code

### ISSUE THREAD

**Issue by gaetan-petit** [symfony/symfony#41742]
**Symfony version(s) affected**: 3.4.49

**Description**
Updating dependencies through composer cause incompability with laminas/laminas-code

**How to reproduce**
Running `composer update` with package requiring `ocramius/proxy-manager` like `symfony/proxy-manager-bridge`

**Possible Solution**
As discussed with @Ocramius in https://github.com/laminas/laminas-code/issues/89

> `Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator`
seems to use `zendframework/zend-code`, but it doesn't declare a
dependency to it, hence why the class didn't get installed, and a
crash occurs.
>
>
>The correct fix would be to declare a dependency there, and perhaps
plan a migration to `laminas/laminas-code` too

**Additional context**

```
composer update 
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "3.4.*"
Updating dependencies
Lock file operations: 0 installs, 5 updates, 2 removals
  - Removing laminas/laminas-eventmanager (3.3.1)
  - Removing laminas/laminas-zendframework-bridge (1.2.0)
  - Upgrading laminas/laminas-code (4.3.0 => 4.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 5 updates, 2 removals
  - Downloading laminas/laminas-code (4.4.0)
  - Downloading phpstan/phpstan (0.12.90)
  - Removing laminas/laminas-zendframework-bridge (1.2.0)
  - Removing laminas/laminas-eventmanager (3.3.1)
  - Upgrading laminas/laminas-code (4.3.0 => 4.4.0): Extracting archive
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class

Symfony operations: 2 recipes (5471d04139cfeb8c88ad90ba4a997ba1)
  - Unconfiguring laminas/laminas-zendframework-bridge (>=1.2.0): From auto-generated recipe
  - Unconfiguring laminas/laminas-eventmanager (>=3.3.1): From auto-generated recipe
Executing script cache:clear --no-warmup [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 255
!!  PHP Fatal error:  Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /var/www/marketplace/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 25
```

Requiring `laminas/laminas-zendframework-bridge` seems to fix the problem.

**Comment by Ocramius** [comment]
Also relevant:

 * Installing `laminas/laminas-zendframework-bridge`, at the cost of a
performance penalty
 * Adding `maglnet/composer-require-checker` to CI runs: catches these
relatively standard issues

**Comment by nicolas-grekas** [comment]
Thanks for the report.
3.4 is not maintained anymore so I'm going to close.
This issue has been fixed in 4.4 by using `friendsofphp/proxy-manager-lts` instead of `ocramius/proxy-manager`.
You should be able to do so in a 3.4 app also.

**Comment by Ocramius** [comment]
The problem exists also in mainline:

https://github.com/symfony/symfony/blob/c71c8727cc665c9e9b56e299fcfcc0adfbf02bac/src/Symfony/Bridge/ProxyManager/composer.json
https://github.com/symfony/symfony/blob/c71c8727cc665c9e9b56e299fcfcc0adfbf02bac/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php

The dependency to `laminas/laminas-code` is not declared.

I know you like touting your fork as if it were the solution to all
humanitarian problems, but it has nothing to do with that, and frankly it's
really just irritating.

**Comment by gaetan-petit** [comment]
> This issue has been fixed in 4.4 by using `friendsofphp/proxy-manager-lts` instead of `ocramius/proxy-manager`.
> You should be able to do so in a 3.4 app also.

No you can't as several dependencies are directly requiring on `ocramius/proxy-manager`.
I know that 3.4 is approaching EOL, but if it's has simple as updating dependencies could you consider it?

**Comment by nicolas-grekas** [comment]
> you can't as several dependencies are directly requiring on ocramius/proxy-manager.

actually `friendsofphp/proxy-manager-lts` "replaces" `ocramius/proxy-manager` from a composer pov, so it really works even if deps directly require it.

> I know that 3.4 is approaching EOL, but if it's has simple as updating dependencies could you consider it?

We have to draw a line and stick to it, that's been annouced years ahead...

**Comment by gaetan-petit** [comment]
> actually `friendsofphp/proxy-manager-lts` "replaces" `ocramius/proxy-manager` from a composer pov, so it really works even if deps directly require it.

Can't do that either it requires `symfony/filesystem ^4.4.17|^5.0|^6.0` and it's incompatible with a 3.4 application.

> We have to draw a line and stick to it, that's been annouced years ahead...

I understand, we're actually just a step from switching to 4.4. It's just that it'll clearly break many 3.4 from updating dependencies (including possible security update).

**Comment by wouterj** [comment]
That's the risk of using a version that reached end of life 8 months ago. There is not much we can do I'm afraid (apart from fixing the bug in currently maintained versions if it's there).

**Comment by nicolas-grekas** [comment]
@gaetan-petit indeed, good luck with the upgrade! I realized there is one more thing you can do, which is to stick to laminas/laminas-code < 4.4, which is the version that introduced the change you're seeing.

**Comment by gaetan-petit** [comment]
> That's the risk of using a version that reached end of life 8 months ago. There is not much we can do I'm afraid (apart from fixing the bug in currently maintained versions if it's there).

Thanks @wouterj (I guess) but in my previous post I said that we're actually finishing the migration.

**Comment by beberlei** [comment]
@gaetan-petit You can fix that yourself by adding `class_alias` calls for laminas code to zend code.

I used this temporary fix:

```php
require_once __DIR__ . '/vendor/laminas/laminas-code/src/Generator/GeneratorInterface.php';
require_once __DIR__ . '/vendor/laminas/laminas-code/src/Generator/AbstractGenerator.php';
require_once __DIR__ . '/vendor/laminas/laminas-code/src/Generator/TraitUsageInterface.php';
require_once __DIR__ . '/vendor/laminas/laminas-code/src/Generator/ClassGenerator.php';

    class_alias("Laminas\Code\Generator\GeneratorInterface",
        "Zend\Code\Generator\GeneratorInterface");
    class_alias("Laminas\Code\Generator\AbstractGenerator",
        "Zend\Code\Generator\AbstractGenerator",);
    class_alias("Laminas\Code\Generator\TraitUsageInterface",
        "Zend\Code\Generator\TraitUsageInterface",);
    class_alias("Laminas\Code\Generator\ClassGenerator",
        "Zend\Code\Generator\ClassGenerator",);
```

**Comment by Thykof** [comment]
Hello,

I am working with symfony 5.0 and had the this error: `Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator): void and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /home/nathan/dev/plateforme/facturation/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 33`

Running this fixed the problem: `composer require laminas/laminas-zendframework-bridge`, thanks to https://github.com/laminas/laminas-code/issues/37#issuecomment-578321299 but this is not the ideal solution.

Upgrading to symfony 5.3 fixed the problem.

**Comment by nicogit2001** [comment]
Worked for me. Thanks.

**Comment by RomuloHe4rt** [comment]
When I try to install ``laminas / laminas-zend framework-bridge``, it gives me an error saying ``Class "1\ApiContentController"`` does not exist. 

How do I solve this?

**Comment by rohlacanna** [comment]
> 
> 
> **Symfony version(s) affected**: 3.4.49
> 
> **Description** Updating dependencies through composer cause incompability with laminas/laminas-code
> 
> **How to reproduce** Running `composer update` with package requiring `ocramius/proxy-manager` like `symfony/proxy-manager-bridge`
> 
> **Possible Solution** As discussed with @Ocramius in [laminas/laminas-code#89](https://github.com/laminas/laminas-code/issues/89)
> 
> > `Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator`
> > seems to use `zendframework/zend-code`, but it doesn't declare a
> > dependency to it, hence why the class didn't get installed, and a
> > crash occurs.
> > The correct fix would be to declare a dependency there, and perhaps
> > plan a migration to `laminas/laminas-code` too
> 
> **Additional context**
> 
> ```
> composer update 
> Loading composer repositories with package information
> Restricting packages listed in "symfony/symfony" to "3.4.*"
> Updating dependencies
> Lock file operations: 0 installs, 5 updates, 2 removals
>   - Removing laminas/laminas-eventmanager (3.3.1)
>   - Removing laminas/laminas-zendframework-bridge (1.2.0)
>   - Upgrading laminas/laminas-code (4.3.0 => 4.4.0)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 0 installs, 5 updates, 2 removals
>   - Downloading laminas/laminas-code (4.4.0)
>   - Downloading phpstan/phpstan (0.12.90)
>   - Removing laminas/laminas-zendframework-bridge (1.2.0)
>   - Removing laminas/laminas-eventmanager (3.3.1)
>   - Upgrading laminas/laminas-code (4.3.0 => 4.4.0): Extracting archive
> Generating autoload files
> composer/package-versions-deprecated: Generating version class...
> composer/package-versions-deprecated: ...done generating version class
> 
> Symfony operations: 2 recipes (5471d04139cfeb8c88ad90ba4a997ba1)
>   - Unconfiguring laminas/laminas-zendframework-bridge (>=1.2.0): From auto-generated recipe
>   - Unconfiguring laminas/laminas-eventmanager (>=3.3.1): From auto-generated recipe
> Executing script cache:clear --no-warmup [KO]
>  [KO]
> Script cache:clear --no-warmup returned with error code 255
> !!  PHP Fatal error:  Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /var/www/marketplace/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 25
> ```
> 
> Requiring `laminas/laminas-zendframework-bridge` seems to fix the problem.

When I try to install laminas / laminas-zend framework-bridge, it gives me an error saying Class "1\ApiContentController" does not exist.

How do I solve this?

**Comment by Saoussene-Toubal** [comment]
hiii symfony 3.4 worked for me
by execute : composer require laminas/laminas-zendframework-bridge
