### ISSUE TITLE
Authentication dosent keep user

### ISSUE THREAD

**Issue by mojtaba-nematpour** [symfony/symfony#41752]
So the point is I wanna create a login for my admin so I create it entity \App\Entity\Admin, controller AdminController, and authenticator AdminLoginAuthentication, and it guard and access-point in security config.

When I log in via 'admin.1@yahoo.com' the login success and redirects to admin_dashboard but the point is authenticator doesn't keep the credentials and the access-point redirect back the admin to login.

**The full question and more information is on my Stakowerlfow** _https://stackoverflow.com/questions/68053262/symfony-authenticator-dosnt-authenticat-properly_****

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
