### ISSUE TITLE
Missing implementation in symfony/amqp-messenger

### ISSUE THREAD

**Issue by giudicelli** [symfony/symfony#41756]
**Symfony version(s) affected**: 5.3.0

**Description**

Missing implementation in symfony/amqp-messenger.

Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransport  should implement Symfony\Component\Messenger\Transport\Receiver\QueueReceiverInterface since its receiver actually implements it...

Right now the new "--queues" option is not usage with "messenger:consume" when using AMQP...

**Comment by OskarStark** [comment]
cc @lyrixx IIRc you provided this feature?

**Comment by giudicelli** [comment]
https://github.com/symfony/amqp-messenger/pull/3

**Comment by lyrixx** [comment]
@OskarStark Unfortunately, I did not work on this :/

**Comment by OskarStark** [comment]
Oh I thought the QueueReceiverInterface was made by you 😃

**Comment by xabbuh** [comment]
Hm, I do not really understand why the transport would have to implement this interface. This interface must be present on the receiver instead, right? And the `AmqpReceiver` does implement it.

@dbu As you contributed the `QueueReceiverInterface` in #38973 what do you think about this?

**Comment by dbu** [comment]
yep, that change was introduced by me in 81d6a49750fd2734bbb5fcb7efcbc34e22639641

my understanding was that the thing that is put into Worker::receivers is the amqp receiver. then https://github.com/symfony/symfony/commit/81d6a49750fd2734bbb5fcb7efcbc34e22639641#diff-50e65343e6cdefbf7f7153c5200bfbc5a5f7edd6a921065d50a9de531d2fd6ebR75 would work.

is the AmqpTransport injected into the worker? or did i misunderstand how this works in some other way?

**Comment by Nyholm** [comment]
A "Transport" is a sender and receiver combined. 
`interface TransportInterface extends ReceiverInterface, SenderInterface`

So technically, we have two AmqpReceivers. Only one of them implement `QueueReceiverInterface`. This is fine as long as you configured that you want to use `AmqpReceiver`. But @giudicelli has configured his application to use `AmqpTransport`. That is why the `--queues` option does not work. 

I agree with @giudicelli's solution. Do you mind submitting a PR?

**Comment by dbu** [comment]
oh, i did not realize that. thanks for the explanation tobias!

yeah then it makes sense that it should implement it. looking at https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpTransport.php the transport explicitly instantiates the AmqpReceiver, so there is no problem in it implementing the interface and forwarding the information to the nested receiver.

can this be considered a bugfix? its a bit of borderline, but seems unexpected and unnecessary to not work. a DX bug?
i would suggest doing the pull request against 5.3, but not sure if the maintainers agree...

(i am away next week, so i won't be the one doing a PR for it)

**Comment by xabbuh** [comment]
see #42060
