### ISSUE TITLE
[HttpFoundation] Add getString to ParameterBag

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#41764]
**Description**
After upgrade to 5.3 I have soo many PhpStan issues like 
```
Parameter #1 $customerId of method Shopware\Administration\Controller\AdministrationController::isEmailValid() expects string, bool|float|int|string|null given.      
```
The ParameterBag has already methods like getBoolean / getInt. But not a getString. This would help to fix those issues really fast.

**Example**
```php
$email = $request->request->getString('email');
```

**Comment by ro0NL** [comment]
See https://github.com/symfony/symfony/pull/37229 

and https://github.com/symfony/symfony/issues/40680#issuecomment-812469598
