### ISSUE TITLE
DateTime constraint does not accept null and empty values but doc says that it does

### ISSUE THREAD

**Issue by sabat24** [symfony/symfony#41778]
**Symfony version(s) affected**: 5.3.2

**Description**

According to [doc](https://symfony.com/doc/current/reference/constraints/DateTime.html): "As with most of the other constraints, null and empty strings are considered valid values." 

I created following constructor

```php
public function __construct(
    #[DateTime]
    private ?\DateTimeImmutable $publishedAt,
) {
}
```

Then I tried to send following data in request:

```json
{
  "title": "title",
  "author": "author",
  "publishedAt": null
}
```

And I received following message:

```json
{
  "errors": {
    "message": "request_violations",
    "violations": {
      "publishedAt": "This value should be of type string."
    }
  }
}
```

Since Symfony 5.1(?) I should use `Constraints/Type("\DateTimeInterface")` instead of DateTime constraint.
However it still doesn't seems to work correctly as I can pass any non-date formatted value and it will pass the validation:

```json
{
  "title": "title",
  "author": "author",
  "publishedAt": "gdfgdfgdfgdfgdfgd"
}
```

Response:
```
DateTimeImmutable::__construct(): Failed to parse time string (gdfgdfgdfgdfgdfgd) at position 0 (g): The timezone could not be found in the database
```

Side question: how can I now validate date time string providing some valid date formats and allow null values as well?

**Comment by stof** [comment]
@sabat24 if you apply your validation on your object expecting a `DateTimeImmutable` while receiving a string, it means that the construction of the DateTimeImmutable object (which is the one triggering the error you get) happens *before* validating the input. and so it means you need to handle invalid values in your conversion layer.
If you want to rely on the validator to validate the input string, your object on which you run the validation should contain that input string, and the conversion to DateTimeImmutable should be done only after validation (when the validation succeeds).

**Comment by sabat24** [comment]
@stof Yes, you were right about the source of that error. My mistake.
