### ISSUE TITLE
Enable to generate UuidV4 for Doctrine Ids with symfony 5.3

### ISSUE THREAD

**Issue by jeckel** [symfony/symfony#41772]
**Symfony version(s) affected**: 5.3.1

**Description**
I'm upgrading a project which was using `UuidGeneratorV4`, I replaced with the new `UuidGenerator` service but it always generate UuidV6, even if I configure the default uuid format to v4

**How to reproduce**
Configuration `config/packages/framework.yml`:
```yaml
framework:
    uid:
        default_uuid_version: 4
```

My entity:
```php
/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @Vich\Uploadable
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true, name="client_id")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @var UuidV4|null
     */
    private ?UuidV4 $id = null;

    /* ... */
}
```

When I try to insert new entity, I get this error:
```
Cannot assign Symfony\Component\Uid\UuidV6 to property App\Infrastructure\Persistence\Doctrine\Entity\Client::$id of type ?Symfony\Component\Uid\UuidV4
```

It looks like the default configuration `default_uuid_version` has no effect here...

**Comment by OskarStark** [comment]
Remove the generator and to the following in the constructor:

$this->id = new Uuid();

No need to be nullable on the property

**Comment by jeckel** [comment]
> Remove the generator and to the following in the constructor:
> 
> $this->id = new Uuid();
> 
> No need to be nullable on the property

This is a workaround, not a solution. The purpose of the generator is to generate a new Uuid only when required (inserting new entity). En generating a new Uuid is not free

**Comment by nicolas-grekas** [comment]
I'm closing because this is not a Symfony issue but a Doctrine issue. The root issue is that there is no simple way to use services in generators. I've implemented a fix in https://github.com/doctrine/DoctrineBundle/pull/1295, but the discussion has led to the conclusion that patching ORM first would be a better approach.
I did not follow up on this. Please do so if you can. Help wanted.

**Comment by WolfgangDrescher** [comment]
Maybe not the best solution, but creating a custom IdGenerator did help me out for this one:

```php
<?php

namespace App\Doctrine;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Id\AbstractIdGenerator;
use Symfony\Component\Uid\Uuid;

class UuidGenerator extends AbstractIdGenerator
{
    public function generate(EntityManager $em, $entity)
    {
        return Uuid::v4();
    }
}
```

This was you actually can use it in a `EntityIdTrait` without the workaround of setting the id in the constructor but still using symfonys uid component without having to fallback to `ramsey/uuid-doctrine`. 

```php
<?php

namespace App\Entity;

use App\Doctrine\UuidGenerator;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\AbstractUid;

trait EntityIdTrait
{
    #[ORM\Id]
    #[ORM\Column(type: "uuid", unique: true)]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?AbstractUid $id;

    public function getId(): ?AbstractUid
    {
        return $this->id;
    }

    public function setId(AbstractUid $uuid): void
    {
        $this->id = $uuid;
    }
}
```
