### ISSUE TITLE
[PhpunitBridge] Can't set the composer binary

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#41774]
**Symfony version(s) affected**: Since 3.4.0 it seems ?

**Description**
If you have let's say composer 1 and composer 2 both installed with different binary paths, you before had the possibility to tell phpunit-bridge what executable it should use.

This is not the case anymore, so it will always fallback (or try to find) a `composer` binary... which can be 1.0, when there can be another binary such as `composer2` available.

**How to reproduce**
Install both versions of composer, let's say `composer` and `composer2`. `composer` will always be used, even if you set the `COMPOSER_BINARY` variable as it should be.

**Possible Solution**
Reintroduce the `COMPOSER_BINARY` env var in the simple-phpunit bridge since 4.4.

**Comment by Taluu** [comment]
Unless there was a specific reason on why this was removed ? @nicolas-grekas

**Comment by nicolas-grekas** [comment]
When has it been removed? I'm don't remember anything like that (I don't remember it worked either btw.)

**Comment by Taluu** [comment]
On 3.4, there was that : https://github.com/symfony/phpunit-bridge/blob/3.4/bin/simple-phpunit#L68-L74

And since at least 4.0 : https://github.com/symfony/phpunit-bridge/blob/4.0/bin/simple-phpunit#L50-L52

As you can see, the if is now gone, assuming it seems it must look for the composer binary itself.

(Yeah I'm kinda stuck on 3.4 for now :cry: )

**Comment by nicolas-grekas** [comment]
Can you find the commit where it's been removed? That might help get the background of the change.

**Comment by stof** [comment]
support for `COMPOSER_BINARY` was added in 3.4.40 in https://github.com/symfony/phpunit-bridge/commit/0b83e8ad3247d1ebac4797ce90a0c56a0140be44 (in https://github.com/symfony/symfony/pull/36566)
That's why it is not there in 4.0 (4.0 was already EOMed at that point).
As the code moved to a separate file in 4.3, this new feature was probably lost when merging up in the 4.4 branch.

**Comment by Taluu** [comment]
Yep, I pinpointed 4.0 as it was gone from there. but yeah it seems it was added way afterwards and lost after a while.

Here is the commit : https://github.com/symfony/symfony/commit/6dce90d47bc8ff944d670f6b6d418efb1506fa33 and the PR : https://github.com/symfony/symfony/pull/36566
