### ISSUE TITLE
Symfony 5.2 Form Prototype Fields not following the form type builder order!!

### ISSUE THREAD

**Issue by abelncm** [symfony/symfony#41788]
Symfony 5.2.1

I'm using data prototype for  embedded forms (CollectionType).
Everything is working as expected, i followed the official documentations.

But data prototype doesn't render the fields according to the order defined in the class form type.

This is my view

```
<ul style="list-style:none" class="surfaces col-sm-12" data-prototype="{{ form_widget(form.surfaces.vars.prototype)|e('html_attr') }}">
  {% for item in form.surfaces %}
  <li>{{ form_widget(item) }}</li>
  
  {% endfor %}
</ul>
```

This is included in the parent form type

```
->add('surfaces', CollectionType::class, [
    'entry_type' => SurfaceType::class,
    'label' => false,
    'allow_add' => true,
    'allow_delete' => true,
    'by_reference' => false,
])
```

And this in the child form (embedded form collection)

```
->add('description', null)
->add('value', null)
```

Symfony is rendering the field value before the description value

Can somebody help !!

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
