### ISSUE TITLE
ServiceLocatorTest depends on PHPUnit

### ISSUE THREAD

**Issue by Firtzberg** [symfony/symfony#41783]
**Symfony version(s) affected**: 5.2.7

**Description**
I noticed that [service-contracts](https://github.com/symfony/service-contracts) has [ServiceLocatorTest](https://github.com/symfony/service-contracts/blob/main/Test/ServiceLocatorTest.php) which extends PHPUnit TestCase. The class is autoloaded since all the content is considered source code.
So you have a source code class extending a class from a testing library, but your package isn't used as a testing package.

**Possible Solutions**

Extract testing utilities into separate package and add it as development dependency to dependents.

**Additional context**
Fatal error:
Unknown parent PHPUnit\Framework\TestCase in .../vendor/symfony/service-contracts/Test/ServiceLocatorTest.php:18

**Comment by stof** [comment]
> The class is autoloaded since all the content is considered source code.

it is autoloaded only in case something uses it (that's how autoloading works). What is the context in which you get the bug ?

We have many components providing a `Test` namespace with some testing utilities for users of that component.

**Comment by Firtzberg** [comment]
@stof , thank you for the quick response and valuable feedback.
I got the error while running opcache_compile_file() over all the PHP files in vendor/symfony.
For the time being I will skip this particular file.

**Comment by stof** [comment]
@Firtzberg but then, you won't only have issues for test base classes but also for other classes relying on optional dependencies

**Comment by Firtzberg** [comment]
Yes, I'm facing that right now. You might see few more suggestion from my side during the day.

Feel free to close them as you see fit.

**Comment by derrabus** [comment]
@Firtzberg If you did that to collect classes for preloading, note that there is a nicer way to do that: https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading

Closing as this is not a Symfony bug.

**Comment by Firtzberg** [comment]
@derrabus Thanks, this is what I'm looking for
