### ISSUE TITLE
MAILER_DSN gets changed to https://ses/v2/email/outbound-emails

### ISSUE THREAD

**Issue by jvr-wfs** [symfony/symfony#41799]
Hi

I've been configuring MAILER_DNS using this format:

MAILER_DSN=ses+https://${AWS_ACCESS_KEY}:${AWS_SECRET_KEY}@'ses'?region=eu-west-1

I'm usign Amazon SQS for queuing, so when I run the consumer all my messages fail to be sent because the code is converting the host into 'https://ses', as shown here:

`11:02:58 INFO      [http_client] Request: "POST https://ses/v2/email/outbound-emails"  
11:02:58 ERROR     [app] Could not contact remote server. ["exception" => AsyncAws\Core\Exception\Http\NetworkException^ { …}]
`

I've tried setting up DSN in multiple different ways to see if there was a format that would create the correct URL to post the messages to Amazon SES but nothing was successful.

I decided to add this line:
`
if ('https://ses' === $options['endpoint']) unset($options['endpoint']);`

before [this](https://github.com/symfony/amazon-mailer/blob/d311d253808ff894df30d1a014526cea0822489c/Transport/SesTransportFactory.php#L51) and suddenly the URL was correctly set as shown here:

`11:03:13 INFO      [http_client] Request: "POST https://email.eu-west-1.amazonaws.com/v2/email/outbound-emails"
11:03:14 INFO      [http_client] Response: "200 https://email.eu-west-1.amazonaws.com/v2/email/outbound-emails"
`

Is there a different 'correct' way to set the MAILER_DSN for it to work with the current code? Or have I found a bug?

Thanks

**Comment by stof** [comment]
if you want to use the default endpoint, it should be `@default`, not `@ses`

**Comment by jvr-wfs** [comment]
Hi Stof

I did try `@default`, but it has the same effect as `@ses`.

Is there anything else I could try?

Thanks

**Comment by stof** [comment]
Can you show what you have when using `default` as host ?

**Comment by jvr-wfs** [comment]
Hi Stof

I have to apologise, I've been testing this many times with different MAILER_DSN values. 

I must've used an existing docker container which still thought MAILER_DSN had 'ses' as host when I replaced it with 'default'. I've tried again and 'default' works correctly.

Thanks very much
