### ISSUE TITLE
[DoctrineBridge] DoctrineLoader relies on AutoMappingTrait

### ISSUE THREAD

**Issue by m-vo** [symfony/symfony#41796]
**Symfony version(s) affected**: >= 4.4

**Description**
`DoctrineExtension#loadValidatorLoader` registers the `DoctrineLoader` as a service. This class uses the `Symfony\Component\Validator\Mapping\Loader\AutoMappingTrait` which might not be available.

As soon as this service gets autloaded at container build time* this will produce a fatal error under PHP8.1:

```
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "Symfony\Component\Validator\Mapping\Loader\AutoMappingTrait" not found while loading "Symfony\Bridge\Doctrine\Validator\DoctrineLoader`
```

*) one scenario is for instance reading class annotations/attributes and thereby calling `$container->getReflectionClass()` 

**How to reproduce**
1. Set up a Sf application with doctrine-bundle installed.
1. Add a compiler pass that does the following:
    ```php
    foreach ($container->getDefinitions() as $definition) {
      $container->getReflectionClass($definition->getClass(), false);
    }
    ```
1. Build the container.

----
This reminded me a bit of https://github.com/symfony/symfony/issues/32395. :slightly_smiling_face:  Maybe we could mark the service as synthetic if the `AutoMappingTrait` is not available or register a dummy instead?

**Comment by derrabus** [comment]
Registering a service with a class that cannot be autoloaded is fine in general, as long as you don't wire it. If you think that this service should not be registered at all, please open an issue here: https://github.com/doctrine/DoctrineBundle/issues

If you think that this is a bug of the DependencyInjection component, you're in the right place, however. 🙂

**Comment by m-vo** [comment]
You're right I guess. :slightly_smiling_face:  My brain was probably assuming that the extension was part of the `symfony/doctrine-bridge` as well. 
I'm going to open up an issue over at `DoctrineBundle`.

Though you could argue that the bridge then should either require its dependencies or tolerate missing them? (Not easy with traits, unfortunately.)

**Comment by derrabus** [comment]
> Though you could argue that the bridge then should either require its dependencies or tolerate missing them?

The latter is the case. The bridge is a collection of glue code for various Symfony components. If we made all dependencies mandatory, the bridge would pull a lot of components that you probably don't use. The alternative would be that we have a `symfony/form-doctrine-bridge`, a `symfony/validator-doctrine-bridge`, a `symfony/uid-doctrine-bridge` and so on. We would end up micro-managing tiny packages.

**Comment by m-vo** [comment]
To me it looks like `symfony/validator` does not seem to be needed for the `DoctrineLoader` class - other than for the trait.

It's just a few lines. Wdyt about pulling the code in to make it more resilient?
https://github.com/symfony/symfony/blob/e1b81e39dbc7f581cd6e76ba93bae2c23f1484fd/src/Symfony/Component/Validator/Mapping/Loader/AutoMappingTrait.php#L24-L33

**Comment by derrabus** [comment]
> To me it looks like `symfony/validator` does not seem to be needed for the `DoctrineLoader` class - other than for the trait.

That is not correct. The class implements `LoaderInterface` which also comes from this package. And honestly, without the validator, the whole class is pretty much useless.

**Comment by m-vo** [comment]
Let's fix this over at `DoctrineBundle` then.

**Comment by brzuchal** [comment]
I don't use Validator component in my project but this issue hits me, looks like the loader is loaded anyway.

---

Bumping up `doctrine/doctrine-bundle` to v2.4.3 helped me.
