### ISSUE TITLE
Recipes override existing configurations on update

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#41805]
**Symfony version(s) affected**: 5.3.*

**Description**
Im currently migrating from symfony 4.3 to 5.3.
While doing so I get notified by composer to update my recipes using `composer recipes:install symfony/any-package-name --force -v` for example.
When running this code all configuration is just overriden and one has to check each configuration file for changes.

**How to reproduce**
`composer recipes:install symfony/package-name --force -v`
Example: Upgrading the `symfony/framework` recipe just overrides all configuration in `config/packages/framework.yaml` with default symfony configuration.

**Possible Solution**
- Config should be merged or
- Copied to a diffrent file or
- Added to same file at the end of the file for devs to resolve

In any case the recipe shouldnt just override existing configurations with symfonys defaults.

**Comment by derrabus** [comment]
> When running this code all configuration is just overriden and one has to check each configuration file for changes.

Yes, that is the intended workflow. Usually, you would have some kind of version control system in place (git for example) that produces a diff of the changes Flex has made.

**Comment by xabbuh** [comment]
I am closing here as the observed behaviour is expected as @derrabus explained. Thank you for understanding.
