### ISSUE TITLE
Form prototype not using custom theme

### ISSUE THREAD

**Issue by henrypenny** [symfony/symfony#41809]
**Symfony version(s) affected**: 4.4

**Description**
I am trying to create a prototype for a form collection using a field level theme customisation.

This link contains other people's experiences with this:
[https://stackoverflow.com/questions/7555702/how-to-customize-the-data-prototype-attribute-in-symfony-2-forms](url)

The form field causing me problems looks like this:

```
class RequestType extends AbstractPartRequestType
{
    ...
        $builder->add('parts', CollectionType::class, [
            'entry_type' => RequestPartType::class,
            'entry_options' => ['label' => false],
            'allow_add' => true,
            'prototype' => true,
        ]);
```

I can do a custom theme for my form collection:

```
{% form_theme form _self %}

{% block _request_parts_row %}
     <!-- custom form templating -->
{% endblock %}

{% block content %}
{{ form_row(form.parts) }}
{% endblock content %}
```

This part works fine.
But if I want to create a prototype it doesn't apply my custom theme.

`{{ form_row(form.parts.vars.prototype)|e }}`

This code ^^ produced non-customised markup.

It seems the block prefixes in the prototype form view are different.
The prefix has `_entry` appended to it: `_request_parts_entry` vs `_request_parts` in the main field.

I've found a few work arounds.

1. Alias my custom theme block `_request_parts_row`:
```
{% block _request_parts_entry_row %}
    {{ block_render(_self, '_request_parts_row', _context ) }}
{% endblock %}
```

2. Use a listener to add an additional block prefix:

```
public function finishView(FormView $view, FormInterface $form, array $options)
{
    $view->children['parts']->vars['prototype']->vars['block_prefixes'][] = '_request_parts';
    parent::finishView($view, $form, $options);
}
```

**Possible Solution**

These solutions both seem like hacks... 
Shouldn't the block prefixes be the same? Or shouldn't the main field's most specific prefix at least be included in the prototypes block_prefix hierarchy?
Or perhaps I'm doing something wrong to start with?
Thanks in advance.

**Comment by sstok** [comment]
You can configure the block-name of your type using the `block_name` option, so you don't have to alias the actual block.

https://symfony.com/doc/current/reference/forms/types/form.html#block-name
https://symfony.com/doc/current/form/form_themes.html#fragment-naming-for-individual-fields

As this isn't really a bug I'd suggest you use the [Slack `#support` channel](https://symfony.com/slack) for further assistance.

**Comment by afkernohan** [comment]
I was sure I had found a bug, but I can see this is not the case now.

What I've learned is that `_<collection>_row `  is the block for the collection. Whereas `_<collection>_entry_row` is the block for a single item within the collection. If you theme `_<collection>_row` it will work in your form, but the prototype will continue to use the default markup. The correct approach would be to theme `_<collection>_entry_row` first, and only theme `_<collection>_row` if you have to.

This can be quite confusing and the documentation doesn't point out the distinction. There seems to be a fair number of people getting tipped up by this.

**Comment by henrypenny** [comment]
I was sure I had found a bug, but I can see this is not the case now.

What I've learned is that `_<collection>_row` is the block for the collection. Whereas `_<collection>_entry_row` is the block for a single item within the collection. If you theme `_<collection>_row` it will work in your form, but the prototype will continue to use the default markup. The correct approach would be to theme `_<collection>_entry_row` first, and only theme `_<collection>_row` if you have to.

This can be quite confusing and the documentation doesn't point out the distinction. There seems to be a fair number of people getting tipped up by this.
