### ISSUE TITLE
[symfony/security] compatibility with symfony 5?

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#41844]
Hello,

I have 2 questions:

1. If I already use the framework, do I still need to require security component? 
2. The current security component requires kernel component v4 "symfony/http-kernel": "^4.4"(https://github.com/symfony/security/blob/4.4/composer.json)
The latest version of http-kernel for symfony 5 is already 5.3: https://github.com/symfony/http-kernel

**Comment by stof** [comment]
The `symfony/security` package is not available for Symfony 5+, because it has been split into several `symfony/security-*` since years (which are the ones that should be used) and we stopped shipping the bigger package.
