### ISSUE TITLE
[Workflow] Intention-revealing methods as MarkingStore

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#41840]
**Description**
Eric Evans recommends using intention-revealing interfaces in his Domain-Driven Design book.

Right now, the only MarkingStore implementation is the `MethodMarkingStore`  which uses a setter like `setCurrentPlace()` which doesn't reveal anything about the business.

I'm wondering if an `IntentionRevealingMethodMarkingStore` would be accepted as a PR?

This marking store would use the transition's name to infer the method: `"wait_for_review"` => `waitForReview()`.

It would also make room for some business logic within the method so the underlying entity is not an anemic one.

@lyrixx I'm curious about your opinion on this one as it looks like you contributed a lot to this component.

**Comment by TristanPouliquen** [comment]
You could either infer the method name or offer a new configuration key under the workflow step configuration to explicitly define the method you want to have executed for each step of the workflow.

**Comment by lyrixx** [comment]
Exposing all transition in your final entity breaks the concept of the separation of concern: you'll have to code twice the logic:

* in the workflow configuration
* in the entity / DTO

So IMHO, this is a bad idea to do that, so I'm against to put in the code ATM.

But I'm not totally close to the idea. Let's wait a bit to get other feedback before closing this issue.

Any awyway, thanks for trying to make the component a better one.

**Comment by sylfabre** [comment]
@lyrixx @TristanPouliquen Thank you for your feedbacks.

If I'm getting this right, there are two ways to implement a workflow logic:
1. Without the component: the entity is the interface, it exposes intention-revealing methods like `waitForReview()`, `reviewed()`, ... and these methods embed as much business logic as desired (including validation on possible or impossible transition)
2. With the component: the workflow component becomes the interface, it is in charge of the validation, and the entity becomes anemic and is just a data store.

=> The real question is then where does one place the boundary? And thus where the interface should lie?

**Comment by stof** [comment]
@sylfabre putting everything in the entity would mean that the entity needs to be able to use validation, security checks and dispatch the logic (or at least events) when transitioning. But this would require injecting services into the entity, which is generally quite harder. That's why the component has a Workflow service responsible for that.

**Comment by sylfabre** [comment]
@stof Yes I totally get it, I was just stating that the real question is the place of the boundary: if the entity is the only thing within the boundary then it has to handle everything which is quite harder.

The Workflow component helps with the following consequences:
- The component implementation becomes part of the domain context
- The boundary moves away from the entity
- The component becomes the interface
=> The entity doesn't need any more intention-revealing methods because it is no longer the interface.
