### ISSUE TITLE
Validator auto_mapping not working properly on joined properties

### ISSUE THREAD

**Issue by hracik** [symfony/symfony#41859]
**Symfony version(s) affected**: 4.4.24

**Description**
Validator auto_mapping is too slow on entity with OneToMany/ManyToMany relations. Probably it want to automatically validate all joined objects. I see Doctrine makes additional (and more imporantly not needed) queries for all joined objects (queries are rather slow because database is huge). No reason to validate existing/unchanged objects.

**How to reproduce**
I have simple entity, with some Column, OneToMany/ManyToMany fields, like this
```
/**
 * @ORM\Entity(repositoryClass=NicheRepository::class)
 * @ORM\Table(name="niche")
 */
class Niche 
{
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Product::class, mappedBy="niches")
     */
    private $products;

    /**
     * @ORM\OneToMany(targetEntity=Campaign::class, mappedBy="niche")
     */
    private $campaigns;

    /**
     * @ORM\OneToMany(targetEntity=Website::class, mappedBy="niche")
     */
    private $websites;
```
In simple form, where I edit only "Column" property, automatic validation validate object correctly, but there is huge difference in speed compared to
```
    /**
     * @Assert\DisableAutoMapping
     * @ORM\ManyToMany(targetEntity=Product::class, mappedBy="niches")
     */
    private $products;

    /**
     * @Assert\DisableAutoMapping
     * @ORM\OneToMany(targetEntity=Campaign::class, mappedBy="niche")
     */
    private $campaigns;

    /**
     * @Assert\DisableAutoMapping
     * @ORM\OneToMany(targetEntity=Website::class, mappedBy="niche")
     */
    private $websites;
```
I have problem to find anything in documentation, even in debug process what exactly is being executed, what is different. I suspect it somehow want to validate joined objects as well, because I see that doctrine make auto-query for them, e.g. select * from products where products.niche_id = ?.  I did not use `@Assert\Valid` directly and it is a problem because there can be thousands of joined object, I did not found why/where this was added, I found only this [https://symfony.com/blog/new-in-symfony-4-3-automatic-validation](https://symfony.com/blog/new-in-symfony-4-3-automatic-validation) where this behaviour is not mentioned.

**Possible Solution**
Is the solution really write on each relation `@Assert\DisableAutoMapping`? Usually relations are not created within the same form, they are already created and only linked together so I would prefer default behaviour to not validate all relations automatically, but only if used `@Assert\Valid` on relation.

**Additional context**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
