### ISSUE TITLE
UserLoaderInterface interface still use deprecated method loadUserByUsername

### ISSUE THREAD

**Issue by abdulrahman19** [symfony/symfony#41856]
**Symfony version(s) affected**: 5.3.*

**Description**
The documentation referrers to use [loadUserByIdentifier](https://symfony.com/doc/current/security/user_provider.html#using-a-custom-query-to-load-the-user) method, but the interface force you to implement old `loadUserByUsername` method.

**How to reproduce**
Use `UserLoaderInterface` interface inside `UserRepository` it'll force you to implement `loadUserByUsername` instead of `loadUserByIdentifier`

**Possible Solution**
Rename `loadUserByUsername` to `loadUserByIdentifier` inside `UserLoaderInterface` interface

**Comment by stof** [comment]
Well, *removing* the old method from the interface can only be done in a major version, so it will be done in 6.0

**Comment by abdulrahman19** [comment]
> you can do that by making your `UserRepository` implement the `Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface`. This interface only requires one method: `loadUserByIdentifier($identifier)`:

This is so weird for me that the documentation suggests feature does not exist in the code!
I think this is making a huge confusing, I think documentation need to edit

**Comment by stof** [comment]
the new name *is* used (and you get a deprecation warning if you don't implement it).

What is missing in the doc is that the old name must still be implemented too until 6.0 (renaming methods in an interface is a 2-step process)
