### ISSUE TITLE
[Validator] Use same validation pattern for `Assert\Email` as Mailer is using for `new Address()`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#41850]
**Description**
When entering `foo..bar@example.com` into a form field with `@Assert\Email()`, this is considered valid.
However, `new Address('foo..bar@example.com');` results in the `RfcComplianceException`:
> Email "foo..bar@example.com" does not comply with addr-spec of RFC 2822.

I know that email validation is a difficult topic ;-) But it cannot (or rather should not) be that one part of Symfony is accepting something, and another part is refusing it.

So I'm suggesting:
* Add the same pattern that `Address()` is using as [mode](https://symfony.com/doc/current/reference/constraints/Email.html#mode) for `Assert\Email`.
* And set this new mode as the default.

**Comment by xabbuh** [comment]
Do you experience the same when setting the `mode` option of the `Email` constraint to `strict`?

**Comment by ThomasLandauer** [comment]
No. So Symfony Mailer is using `egulias/email-validator`? If yes, I'll mention this at https://symfony.com/doc/current/reference/constraints/Email.html#strict and open a new issue to suggest making this the default.

**Comment by stof** [comment]
@ThomasLandauer yes, `egulias/email-validator` is used

**Comment by ThomasLandauer** [comment]
Closing in favor of https://github.com/symfony/symfony/issues/41855
