### ISSUE TITLE
[Security] Password encoder factory backward compatibility

### ISSUE THREAD

**Issue by dvesh3** [symfony/symfony#41877]
**Symfony version(s) affected**: 5.3.x

**Description**
We have a custom password encoder factory that decorates the Symfony encoder factory and allows to delegate building the encoder to a type specific factory which then is able to create a dedicated encoder for a user object.

Until 5.2.x it worked as expected, but on ver. 5.3.x it started throwing exception "No password hasher has been configured for account...". After digging the issue, we found out, with https://github.com/symfony/symfony/pull/39802 password encoder has been deprecated and new password hasher factory has been introduced to replace it. This new factory is being used everywhere e.g. https://github.com/symfony/symfony/blob/d679ac56503c54724515044551b61279bf23f0ef/src/Symfony/Bundle/SecurityBundle/Resources/config/security.php#L274

So this old encoder factory is **deprecated** and **not used anywhere anymore except in** `security.command.user_password_encoder`. how does this follow backward compatibility?

The problem is, we would like to support Symfony ver. 5.2 or higher, so if we switch to new password hasher factory then it will not be backward compatible and overriding the Symfony services to use old password encoder factory is not forward compatible.

Any help would be greatly appreciated. thanks!

**Additional context**
Issue described here: https://github.com/pimcore/pimcore/issues/9489

**Comment by wouterj** [comment]
> The problem is, we would like to support Symfony ver. 5.2 or higher, so if we switch to new password hasher factory then it will not be backward compatible and overriding the Symfony services to use old password encoder factory is not forward compatible.

I think you need to write a custom compiler pass and modify your decorator service definition to use `security.password_hasher_factory` or `security.encoder_factory` depending on which service exists.

**Comment by chalasr** [comment]
Note that the BC layer in place wires `security.password_hasher_factory` *and* `security.encoder_factory` the same way no matter if you configure `encoders` or `password_hashers`, precisely to avoid such issues.
Also the issue mentions that apart from the validator constraint, everything keeps working as expected. 
I suspect there is some special service wiring on your side. I'll have a look asap, any additional input are welcome meawhile.

edit: Wouter is right here.

**Comment by stof** [comment]
@chalasr the fact that both services are wired does not enforce that decorators keep working (if the decorated service is not the one being used)

**Comment by dvesh3** [comment]
> Also the issue mentions that apart from the validator constraint, everything keeps working as expected.

@chalasr not really...we use form login for frontend authentication, which in turn uses `security.authentication.provider.dao` service and this was broken too, so we had to override the service to use old encoder factory https://github.com/pimcore/pimcore/pull/9397/files#diff-712497e7295c9c1ab780fe0fbd9fde99837ddee1cb451f776d31e7b8395b1e1dR47

> I suspect there is some special service wiring on your side. 

Nope. we just decorate the core service https://github.com/pimcore/pimcore/blob/10.x/bundles/CoreBundle/Resources/config/services.yml#L35

**Comment by chalasr** [comment]
Yes, I misread the beginning of your issue, sorry.
What @wouterj suggests is the way to go for supporting both versions, so I'm going to close this issue. 
If you need some guidance on the implementation, I invite you to ping me on the [symfony-devs slack](https://symfony.com/support).
