### ISSUE TITLE
add one more choice field CountryCallingCodeType

### ISSUE THREAD

**Issue by lxregistry** [symfony/symfony#41880]
**Description**

Is there a way to have one more Choice Field CountryCallingCodeType like existing CountryType?
Could you add this form type?
**Example**

the same like existing CountryType just adjust it for Country Dialing Code List

**Comment by ro0NL** [comment]
https://github.com/odolbeau/phone-number-bundle :)

**Comment by lxregistry** [comment]
> 
> 
> https://github.com/odolbeau/phone-number-bundle :)

Prefer a native instead an unmaintained bundle

**Comment by ro0NL** [comment]
last commit is 2021-06-28T15:48:50Z. To me that means it's maintained.

my point is this is not an easy topic, see eg. also https://github.com/symfony/symfony/issues/32356

i may agree all this ideally lives under eg. symfony/intl umbrella, but fact is there's lot of existing infrastructure already (AFAIK phonenumber-bundle is heavily spread). As such any potential migration should be proposed upstream first IMHO.

**Comment by OskarStark** [comment]
The bundle is well maintained 👍 

Feel free to open a PR and contribute the proposed FormType.

I am closing here, thank you
