### ISSUE TITLE
Refreshed RememberMe cookie contains invalid data

### ISSUE THREAD

**Issue by qurben** [symfony/symfony#41891]
**Symfony version(s) affected**: 5.3.2 (with symfony/security-http 5.3.x-dev 81c183fd1527a2d09bd3b5c69bca3fc24ce18527 for another fix in rememberme)

**Description**

The rememberme cookie returned when a rememberme session is renewed is not properly formatted. This causes it to be rejected when it is used again.

**How to reproduce**

1. Given a setup with rememberme enabled
2. Login with remember me
3. Remove session cookie
4. Refresh
5. Remove session cookie again
6. There is no new session

**Possible Solution**

I pulled two cookies from my installation (a development version, see Additional context), the first one is the original REMEMBERME cookie and the second one is the one received after refreshing. In the first one the last value is base64 encoded and in the second one it isn't.

(originally I had these two mixed up)
 

**Additional context**

```
REMEMBERME=Q3NyRGVsZnRcZW50aXR5XHNlY3VyaXR5XEFjY291bnQ6TVRNME5RPT06MTYyNjEyNjUzOTpVUzNCS2lhNUpsV2hpT2hPSmZ2UWExWGxSNmRNMWJtR2NHRThuZzhQalRsYWFuMDNhM0ZISU9hOXVVYmo5VkVlbWptemVMTlU1cXA4SGVLSFYxVng0UT09Ojc0OWRjN2VkZTU3MzFhODRiZmVmMzIxYzQyZjgxNDI0ZDY2MDAzNTRkNTljMzI2MDQyNTA1ZGY2OTA4NTUyMTA%3D
url & base64 decoded: CsrDelft\entity\security\Account:MTM0NQ==:1626126539:US3BKia5JlWhiOhOJfvQa1XlR6dM1bmGcGE8ng8PjTlaan03a3FHIOa9uUbj9VEemjmzeLNU5qp8HeKHV1Vx4Q==:749dc7ede5731a84bfef321c42f81424d6600354d59c326042505df690855210

REMEMBERME=Q3NyRGVsZnRcZW50aXR5XHNlY3VyaXR5XEFjY291bnQ6TVRNME5RPT06MTYyNjEyNjUzOTpVUzNCS2lhNUpsV2hpT2hPSmZ2UWExWGxSNmRNMWJtR2NHRThuZzhQalRsYWFuMDNhM0ZISU9hOXVVYmo5VkVlbWptemVMTlU1cXA4SGVLSFYxVng0UT09OnFVWHRIVWJHR01QQXBwbVdmSkFGWjRlS1QyRElOY0VLRHhvaDFHM2JmVUxtMmhGSExDdVcwT1dGd0FrcExUdlloTzFLaGora2dadmltQ01XL0xPYzB3PT0%3D
url & base64 decoded: CsrDelft\entity\security\Account:MTM0NQ==:1626126539:US3BKia5JlWhiOhOJfvQa1XlR6dM1bmGcGE8ng8PjTlaan03a3FHIOa9uUbj9VEemjmzeLNU5qp8HeKHV1Vx4Q==:qUXtHUbGGMPAppmWfJAFZ4eKT2DINcEKDxoh1G3bfULm2hFHLCuW0OWFwAkpLTvYhO1Khj+kgZvimCMW/LOc0w==
```

**Comment by jderusse** [comment]
Could you check if #41741 fixes your issue?

**Comment by qurben** [comment]
With #41741 this issue  is still there.

**Comment by qurben** [comment]
It seems that in `\Symfony\Component\Security\Http\RememberMe\PersistentRememberMeHandler::processRememberMe` the `$tokenValue` variable is normally not base64 encoded, but when the timestamp block is triggered it is. But it might be that it should always be base64 encoded, but that this goes wrong somewhere else. 

(or this might not be relevant at all)

**Comment by qurben** [comment]
I think I found the culprit, in `PersistentRememberMeHandler` the tokenValue is set on line 92, but this should be the hashed version of the tokenValue as is done in the createRememberMeCookie method. This creates an invalid cookie.

https://github.com/symfony/symfony/blob/1eb5b354dea1ddf27690d994baa579d47ee1936f/src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php#L91-L101

https://github.com/symfony/symfony/blob/1eb5b354dea1ddf27690d994baa579d47ee1936f/src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php#L56-L58

**Comment by qurben** [comment]
I can provide a patch for this.
