### ISSUE TITLE
Attributes Route does not work with PHP8 in fresh install of 5.3

### ISSUE THREAD

**Issue by nlhommet** [symfony/symfony#41927]
**Symfony version(s) affected**: 5.3

**Description**
I have started a new project with the version 5.3 on PHP8.0 and I have nothing more to install.
I create my first test controller:

```
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/test')]
class TestController
{

    public function __invoke(): Response
    {
        return new Response('test');
    }
}

```
And when I use the command `symfony console debug:route`, my route is missing in debug

```
 ---------------- -------- -------- ------ --------------------------
  Name             Method   Scheme   Host   Path                     
 ---------------- -------- -------- ------ --------------------------
  _preview_error   ANY      ANY      ANY    /_error/{code}.{_format}
 ---------------- -------- -------- ------ --------------------------
```
In the doc, nothing must be installed to use the route with attributes.
But after research, I had to create the file `annotations.yaml` with this content: 
```
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
```
and after that when I run the command `symfony console debug:route` my route is present
```
 ------------------ -------- -------- ------ --------------------------
  Name               Method   Scheme   Host   Path                     
 ------------------ -------- -------- ------ --------------------------
  app_test__invoke   ANY      ANY      ANY    /test
  _preview_error     ANY      ANY      ANY    /_error/{code}.{_format}
 ------------------ -------- -------- ------ --------------------------
```
While in the documentation it says :
> On PHP 8, you can use native attributes to configure routes right away. On PHP 7, where attributes are not available, you can use annotations instead, provided by the Doctrine Annotations library.
> In case you want to use annotations instead of attributes, run this command once in your application to enable them:
> `composer require doctrine/annotations`

`annotations.yaml`  is a part of recipes of `doctrine/annotations`.
But I don't want to use annotations.

I think a default config file should be present in recipes of a fresh install.

**Comment by Tobion** [comment]
Looks like this issue should be reported in https://github.com/symfony/recipes than here

**Comment by nlhommet** [comment]
oh yes sorry, I don't have the reflex to check here
I close this issue because it is duplicated with this one this issue https://github.com/symfony/recipes/pull/916
