### ISSUE TITLE
[Console] `lint:command` command or `list --no-lazy` option

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#41931]
**Description**
As part of my CI build process, I run `bin/console list` as a quick lint to ensure all my commands are configured correctly. In 5.3+, the list command is lazy and doesn't actually instantiate each command. I think this is a great feature but, had I not noticed, would have given me a false sense of security.

The work-around for me was to add `bin/console list --format=xml`. Adding the format option triggers all the commands to be fully loaded.

Would there be any interest `lint:command` or just a `--no-lazy` option for the `ListCommand`?

**Comment by javiereguiluz** [comment]
@kbond if you only need to check if the command exists and it's correctly registered in the app, you can use something like this: https://github.com/EasyCorp/EasyAdminBundle/blob/master/tests/DependencyInjection/ServicesTest.php

If you need to check if the command actually executes as expected, you could run `command --help` and check if the process exited with an error.

**Comment by chalasr** [comment]
@javiereguiluz Note that calling `getName()` like in the test you linked does not actually instantiate your command if it is fully lazy (ie. if it declares its description via the `$defaultDescription` static prop or the `AsCommand` attribute), because it is wrapped in a `LazyCommand` instance. 
You need to call another method such as `getHelp()`) to actually load the command (see LazyCommand internals).

About the issue itself, I still wonder if the need is common enough as you can test them independently. But I'm not against adding a dedicated command for this.

**Comment by nicolas-grekas** [comment]
This seems like testing that a service can be created. I'm not sure this makes much sense to have this for commands specifically.

Can you explain why it would?

**Comment by wouterj** [comment]
An example Kevin mentioned on Slack was defining a non array default for an array option. The service definition is OK (so `lint:container` is green), but the command will produce an error when you try to initialize it.

If there are more things like this, I'm not opposed to add a `lint:commands` command. I don't think the flag makes sense.

**Comment by nicolas-grekas** [comment]
We're trying to not grow the list of default commands too much. Since `bin/console list --format=xml` does the job, I don't think it's worth adding a dedicated command.

**Comment by javiereguiluz** [comment]
I don't like the proposed flag much either. Wouter's solution seems nice to me.

I think this is important as a quality check. If you are e.g. a third-party bundle and include commands, it's critical to ensure that those commands exist, are registered, can be run, etc.

**Comment by kbond** [comment]
No worries, I'll use my workaround.

If anyone ever stumbles upon this issue, my full workaround is `bin/console list --format=xml > /dev/null`. This hides the stdout from my CI logs but allows any errors to show.
