### ISSUE TITLE
Collection Filtering to specific key

### ISSUE THREAD

**Issue by andimg93** [symfony/symfony#41971]
Hello,

to get a specific element of a collection we have to iterate it with "filter", but the filter method doesnt stop while finding a matching element.
So while i only want to find one item, that match my criteria and then instantly return it i have no possibility for it.

Laravel has the method "only" https://laravel.com/docs/8.x/collections#method-only for it - So this is a feature request for it.

**Comment by andimg93** [comment]
"only" is a method with fetching by however identifier, of the related element, u need.
While u only want a specific item by using one info, u could index the collection by a specific criteria and then use a simple get on it.

**Comment by OskarStark** [comment]
Which Collection do you refer to?
Can you share some example code? Thanks

**Comment by andimg93** [comment]
No need for an example code, cause this relates to any PersistentCollection - So just imagine e.g. a Event where u have a PersistentCollection of Invitations, not my use case but a simple imaginable application example.

**Comment by OskarStark** [comment]
Ok exactly that's why I am asking because the `PersistentCollection` is part of Doctrine, not Symfony 🤔

**Comment by andimg93** [comment]
ok, sorry then this is not the right place to ask for a feature request - I guess.
