### ISSUE TITLE
Mailer: Unable to connect with STARTTLS without encryption

### ISSUE THREAD

**Issue by kw-pr** [symfony/symfony#41997]
**Symfony version(s) affected**: symfony/mailer v5.2.10

**Description**
I have TLS disabled but the mailer is complaining about TLS. Because it it doing a TLS peer verification.

**How to reproduce**
My connect string:

> smtp://localhost:25?encryption=&auth_mode=

Returns this error:

> Unable to connect with STARTTLS without encryption

**Possible Solution**
It works if I add `verify_peer=0`

> smtp://localhost:25?encryption=&auth_mode=&verify_peer=0

I think without TLS encryption there should be no TLS peer verification.

**Comment by sstok** [comment]
According to the changelog the in 4.4:

 * [BC BREAK] removed the `auth_mode` DSN option (it is now always determined automatically)
 * STARTTLS cannot be enabled anymore (it is used automatically if TLS is disabled and the server supports STARTTLS)
 * [BC BREAK] Removed the `encryption` DSN option (use `smtps` instead)

**Comment by stof** [comment]
could it be that the server advocates starttls (and so it is used automatically) but does not have a trusted certificate ?

**Comment by kw-pr** [comment]
> could it be that the server advocates starttls (and so it is used automatically) but does not have a trusted certificate ?

I am not able to test this but I sure you are right. Thanks. Together with the change log this does not look a bug after all. Sorry for the noise.

**Comment by jonnott** [comment]
With symfony/mailer ^5.4, I'm finding that whenever connecting via port 587, I always get an error like this, *unless* I add `?verify_peer=0`..

```
Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

Example DSN would be something like `smtp://username:password@smtp.server.com:587?verify_peer=0`

Until my recent switch to symfony/mailer I was using Swift Mailer with auth_mode=login, port 587 and never had any problems sending, on the very same servers.

Am I doing something wrong?

@kw-pr @fabpot @sstok

**Comment by brightdev0404** [comment]
Now I am still getting this issue with Symfony Mailer 5.3.*.

Expected response code "220" but got code "454", with message "454 4.3.5 unable to start TLS: no certificate configured".

MAILER_URL=smtp://smtp.domain.com:2526?encryption=&auth_mode=login&username=my_username&password=my_password&verify_peer=0

The OS is Ubuntu and I've just installed the postfix and I am not sure that the mailer is connecting to the postfix.
How can I solve this issue?

**Comment by Heivor** [comment]
> Now I am still getting this issue with Symfony Mailer 5.3.*.
> 
> Expected response code "220" but got code "454", with message "454 4.3.5 unable to start TLS: no certificate configured".
> 
> MAILER_URL=smtp://smtp.domain.com:2526?encryption=&auth_mode=login&username=my_username&password=my_password&verify_peer=0
> 
> The OS is Ubuntu and I've just installed the postfix and I am not sure that the mailer is connecting to the postfix. How can I solve this issue?

Same here
