### ISSUE TITLE
[Messenger] Filesystem-Transport for tests

### ISSUE THREAD

**Issue by dbrumann** [symfony/symfony#42002]
**Description**
The provided [InMemoryTransport](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Transport/InMemoryTransport.php) is great for making sure messages are sent via an async transport, instead of being handled directly, and for inspecting the messages. It has the downside, that it is hard to write tests that consume the sent messages. While I can work around this by testing a handler with a custom built message, this will not actually test deserializing the message and passing it through the message bus with its middleware, which might miss bugs.

Enqueue provides a [Filesystem transport](https://php-enqueue.github.io/transport/filesystem/), which I have used in the past for end 2 end-tests that dispatch a message and then run the worker-command in a Symfony Process to check the output/return code to see if the queued message can be handled.

Admittedly, the use case for this is rather limited and other substitutes like [elliotchance/mocksqs](https://github.com/elliotchance/mocksqs) can already cover this with an existing transport, but this requires additional setup.

Would it make sense to provide a Filesystem-Transport  for Symfony Messenger?

**Comment by OskarStark** [comment]
Great idea 👍 

Not sure if you know https://github.com/zenstruck/messenger-test

**Comment by dbrumann** [comment]
I didn't know that library. It looks great for what I need. Thanks :+1:

**Comment by OskarStark** [comment]
Are you still planing to implement this feature @dbrumann ?
Otherwise I suggest to close this issue, thank you 👍

**Comment by dbrumann** [comment]
The library you suggested works great for me as an alternative. Thanks again.
