### ISSUE TITLE
RedeliveryStamp loses exception message in SendFailedMessageForRetryListener

### ISSUE THREAD

**Issue by garak** [symfony/symfony#42017]
**Symfony version(s) affected**: 5.0 - 5.4

**Description**
In `onMessageFailed` method of `SendFailedMessageForRetryListener`, precisely in [line 89](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/EventListener/SendFailedMessageForRetryListener.php#L89), the `RedeliveryStamp` constructor is only called with retry count, and message is lost.

**How to reproduce**
Have a message fails with an error and retry. Log the tries. Instead of getting the error message, you get null.

**Possible Solution**
The constructor of `RedeliveryStamp` should be called with the second argument, too.

Current call: `new RedeliveryStamp($retryCount)`
New call:  `new RedeliveryStamp($retryCount, $throwable->getMessage())`

**Comment by Jean85** [comment]
That info should come from the new `ErrorDetailsStamp`, implemented in #32904 (5.2.0).
In our case that stamp is absent, so the information is simply lost. ~We need to dig deeper to understand why that stamp is not attached to our failed messages.~
The reason it doesn't work for us is that we're on 5.1, maybe the deprecation was erroneously backported there, dropping the info?

Also, we need to check if the listener works correctly on 5.2+. We'll update the app to at least 5.2 to check it.

**Comment by garak** [comment]
Never mind, I didn't notice the deprecation

**Comment by Jean85** [comment]
FTR, the bug seems present in 5.1, but since it's EOL it can't be fixed now.
