### ISSUE TITLE
[Cache] Using instanceof to identify DBAL driver is no longer reliable with DBAL v3

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#42022]
**Symfony version(s) affected**: 3.4.43+, 4.4.11+, 5.0.11+, 5.1.3+ and onward

**Description**
Due to #37342, when using the PDOAdapter for cache, the driver detection switched to an `instanceof` approach. This is pretty unstable, due to the fact that wrapping the DBAL driver with your own implementation should be a fine approach, and it's even encouraged by the [`Middleware` interface](https://github.com/doctrine/dbal/blob/3.1.x/src/Driver/Middleware.php) introduced in DBAL 3: https://github.com/doctrine/dbal/blob/3.1.x/src/Portability/Middleware.php#L24-L31

**How to reproduce**
See https://github.com/getsentry/sentry-symfony/issues/530, which was the original reported issue.

**Possible Solution**
Use `$this->conn->getDatabasePlatform()->getName()` as a way to punch through the possible layers of wrapping middlewares and obtain a reliable platform name.
 
**Additional context**
I don't know the original reason for doing the original PR, since it's dubbed "fix compat for DBAL v3". @nicolas-grekas can you share some insights on that? Is there any reason to NOT take this approach?

**Comment by nicolas-grekas** [comment]
No reason I can think of.
See https://github.com/symfony/symfony/pull/42011

**Comment by derrabus** [comment]
Can we close this issue?

**Comment by xabbuh** [comment]
looks fixed to me

@Jean85 Please give me a hint if I missed something and I will reopen.

**Comment by Jean85** [comment]
I'm not able to test it out, but #42011 seems to contain the right fix :+1:
