### ISSUE TITLE
[Form] Validations are run on non-mapped ChoiceType, producing unwanted form errors

### ISSUE THREAD

**Issue by Schyzophrenic** [symfony/symfony#42021]
**Symfony version(s) affected**: 4.4, 5.3

**Description**
Submitting a form with a non-mapped ChoiceTypeField produces the form error "This value is not valid."

The ChoiceTypeField's options are dynamically set via javascript.

**How to reproduce**
I created a repo to demonstrate the issue: https://github.com/Schyzophrenic/BugMappedChoiceField.
Install and select any test value in the last dropdown on the page: https://127.0.0.1:8000/test

The form is defined as:
```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('simpleText')
            ->add('extraFieldText', TextType::class, [
                'mapped' => false,
                'required' => true,
            ])
            ->add('extraFieldChoice', ChoiceType::class, [
                'choices' => ['Nothing matches! :/' => 0],
                'constraints' => [
                    new NotBlank(),
                ],
                'mapped' => false,
                'required' => true,
            ])
            ->add('submit', SubmitType::class)
        ;
    }
```

**Comment by xabbuh** [comment]
This is expected, but not related to the `mapped` option. The `ChoiceType` expects that the submitted value is one of the configured choices which is not the case here. Either use another form type or add the choice dynamically when the field is submitted. I am going to close here though as the observed behaviour is expected. Thank you for understanding.
