### ISSUE TITLE
PR for 4.4 branch are tested on 3.4 branch

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#42024]
I think something is going wrong with PR tests.

For example, [my PR](https://github.com/symfony/symfony/pull/42010) is targeting branch 4.4, but [here](https://github.com/symfony/symfony/pull/42010/checks?check_run_id=3015399182#step:8:5454), we can read:

> Checking out Symfony 3.4 and running tests with patched components as deps

Then, tests are failing on [this test](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Tests/AbstractLayoutTest.php#L1933) which is the test from the branch 3.4 => looking for `[@pattern="foo"]`

When [the same test](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Tests/AbstractLayoutTest.php#L2066) in branch 4.4 which should be used is `[not(@pattern)]`

See the failing test: https://github.com/symfony/symfony/pull/42010/checks?check_run_id=3015399182#step:8:5851

> 1) Symfony\Bridge\Twig\Tests\Extension\FormExtensionBootstrap3HorizontalLayoutTest::testTextarea
> Failed asserting that 
> 
> ```
> /textarea
>     [@name="name"]
>     [@pattern="foo"]
>     [@class="my&class form-control"]
>     [.="foo&bar"]
>     [@id="my&id"]
> ```
> 
> matches exactly once. Matches 0 times in 
> 
> ```
><textarea id="my&amp;id" name="name" required="required" class="my&amp;class form-control">foo&amp;bar</textarea>
>```
> 
> /home/runner/work/symfony/symfony/src/Symfony/Bridge/Twig/vendor/symfony/form/Tests/AbstractLayoutTest.php:93
> /home/runner/work/symfony/symfony/src/Symfony/Bridge/Twig/vendor/symfony/form/Tests/AbstractLayoutTest.php:118
> /home/runner/work/symfony/symfony/src/Symfony/Bridge/Twig/Tests/Extension/AbstractBootstrap3LayoutTest.php:2143

**Comment by jderusse** [comment]
made on purpose to asserts that PR wont break other components that are compatible with 4.4.

More information in the upcoming documentation: https://github.com/symfony/symfony-docs/pull/15491/files

**Comment by Seb33300** [comment]
So, this is normal that tests unrelated to my changes are failing?

**Comment by jderusse** [comment]
> So, this is normal that tests unrelated to my changes are failing?

when `libraryA` calls `libraryB->foo()` and libraryA `3.4` says being compatible with libraryB `4.0`, then, changes on `libraryB` are tested against `libraryA 3.4`

So this is expected to run tests from branch 3.4 of libraryA.

But, it happens that some tests are false-positive and failed even before your change. In that case, it's not related to your PR and you can ignore it.

In short:
- If you revert your changes and it still fails => ignore the failure
- If you it worked before your PR, then it means your PR break compatibility with lower versions of symfony.
