### ISSUE TITLE
[Translation] Symfony Contracts' `TranslatorTrait` Does not Handle the `en_US_POSIX` Locale Pluralization Correctly

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#42036]
**Symfony version(s) affected**: 4.4, 5.X

**Description**
When the default locale ends up as `en_US_POSIX` (which happens on Alpine), it seems that plurarlization stuff does not get correctly handled.

Seems to be traced to this line: https://github.com/symfony/symfony/blob/479919d4d5cbc17710d16a04ff9728d1519afb8e/src/Symfony/Contracts/Translation/TranslatorTrait.php#L145

Specifically: ` substr($locale, 0, strrpos($locale, '_'))` which is going to yield `en_US` instead of just `en` when the local is `en_US_POSIX`

**How to reproduce**
```php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Translation\IdentityTranslator;

foreach (['en_US', 'en_US_POSIX'] as $locale) {
    Locale::setDefault($locale);
    $translator = new IdentityTranslator();
    // or can fake it with $translator->setLocale($locale);

    echo $locale, PHP_EOL;
    echo '----------', PHP_EOL;
    foreach (range(1, 2) as $i) {
        echo $translator->trans('singular|plural', ['%count%' => $i]), PHP_EOL;
    }
}
```

**Possible Solution**
Split on underscores instead of using `strrpos` on [this line](https://github.com/symfony/symfony/blob/479919d4d5cbc17710d16a04ff9728d1519afb8e/src/Symfony/Contracts/Translation/TranslatorTrait.php#L145)

**Additional context**

I'm not even sure this is a bug or if it matters, but I hit this when a locale environment (OSX) had a default locale of `en_US` but prod (alpine linux) had a locale of `en_US_POSIX`. A custom constraint with a pluralized message was correctly rendering on my locale but not on production/staging.

Of note: the translator component is disabled on my app, but I would bet that the real translator does not have these issues? Possible that this only impacts `IdentityTranslator` and places that use the `TranslatorTrait` from contracts. Symfony [4.4 might be impacted more broadly](https://github.com/symfony/symfony/blob/09814d5548dada9c731d6ba3d76fd9fe3a4d7955/src/Symfony/Component/Translation/PluralizationRules.php#L47).

Seems like `en_US_POSIX` is [an alias for `LC_ALL=C`](https://superuser.com/a/1644097).

**Comment by nicolas-grekas** [comment]
We could add a special check for `en_US_POSIX`. Would you mind sending a PR, branch 4.4 please?

**Comment by chrisguitarguy** [comment]
@nicolas-grekas should there also be a special case for `C` as the default locale too? Or does that exist already?

**Comment by stof** [comment]
Which default locale are you talking about ? The default logic in the library is to take the default locale of ext-intl or `en` if ext-intl is not there: https://github.com/symfony/symfony/blob/1c6a2f0de3c2a70ec25ebe1842c5b717867ad1b9/src/Symfony/Contracts/Translation/TranslatorTrait.php#L40
And `C` is not a valid locale in ICU.

**Comment by chrisguitarguy** [comment]
From `Locale::getDefault()`.

Minimal Dockerfile:

```dockerfile
ARG PHP_VERSION=7.4
FROM php:$PHP_VERSION-alpine

RUN apk add --no-cache icu-dev \
    && docker-php-ext-install intl
```

```
docker build --tag intl-test-74 .
docker build --tag intl-test-80 --build-arg 8.0 .
docker run --rm -it intl-test-74 php -r 'var_dump(Locale::getDefault());'
docker run --rm -it intl-test-80 php -r 'var_dump(Locale::getDefault());'
```

![Screen Shot 2021-07-12 at 9 16 33 AM](https://user-images.githubusercontent.com/1010392/125302875-f926d700-e2f1-11eb-8f77-8cde4b04b9b0.png)
