### ISSUE TITLE
Symfony form constraint "Required"

### ISSUE THREAD

**Issue by AugustinasJet** [symfony/symfony#42030]
I can't find the documentations for `new Required()` constraint.
Also, what is the difference between this and `new NotBlank()` constraint ?

I submit form with this form type without name parameter and `$form->isValid()` still returns true
```
$builder
        ->add('name', TextType::class, [
            'constraints' => [
                new Required(),
            ]
        ]);
```

**Comment by norkunas** [comment]
`Required` constraint purpose is to require fields for `Collection` constraint.

**Comment by stof** [comment]
`Required` is meant to be used in the `Collection` constraint, to mark that key of the array as being required to exist (with any value, including `null`)

**Comment by AugustinasJet** [comment]
Thanks a lot!

**Comment by xabbuh** [comment]
You can read more about it here: https://symfony.com/doc/current/reference/constraints/Collection.html#required-and-optional-field-constraints
