### ISSUE TITLE
[Messenger] Consumer breaks on using "queues" parameter and AmqpTransport.

### ISSUE THREAD

**Issue by mrjingles** [symfony/symfony#42045]
**Symfony version(s) affected**: 5.3.*

**Description**

Message consumer breaks on using "queues" parameter. It looks like the Symfony\Component\Messenger::$receivers holds an array of transports, not receivers.

**How to reproduce**

Call the ConsumeMessagesCommand using the new paramter "--queues".

**Possible Solution**

-

**Additional context**

![image](https://user-images.githubusercontent.com/622928/125145037-2f146180-e120-11eb-8a26-37d09616ff59.png)
![image](https://user-images.githubusercontent.com/622928/125145401-4f90eb80-e121-11eb-95aa-63493100496d.png)

**Comment by xabbuh** [comment]
Is this related to #41756?

**Comment by xabbuh** [comment]
should be fixed by #42060
