### ISSUE TITLE
[Console] Running `bin/console missing-command` shows deprecation warnings

### ISSUE THREAD

**Issue by I-Valchev** [symfony/symfony#42041]
**Symfony version(s) affected**: 4.x & 5.x

**Description**
In a Symfony 4.x or 5.x project, running `bin/console missing-command` (or anything else when a command name does _not_ exist) shows deprecation warnings.

**How to reproduce**

Reproduction is for 4.4, due to easier deprecation warning, but it happens on both 4.x and 5.x

1. Create a symfony skeleton with `symfony new my_project_name --version=4.4`
2. `cd new_project_name && php bin/console missing-command` outputs `Command "missing-command" is not defined.` So far, so good.
3. Introduce a deprecation (for example, `composer req symfony/web-server-bundle`)
4. Now running `php bin/console missing-command` outputs:  

``` 
Command "missing" is not defined.

2021-07-09T13:17:25+00:00 [info] User Deprecated: Using the WebserverBundle is deprecated since Symfony 4.4. The new Symfony local server has more features, you can use it instead.
```

However, running a command that _does exist_, e.g. `php bin/console cache:clear` does _NOT_ show deprecations.

**Possible Solution**
Don't show deprecation warnings if a command is missing. Or, at least, have consistent behaviour between existing vs missing commands.

**Additional context**
N/A

**Comment by Nyholm** [comment]
This deprecation is triggered when you boot the WebserverBundle. The deprecation is always logged, it does not matter if the command is found or not. 

However, when you try to execute a missing command, an exception is thrown. That will trigger the error handler and it will print the last few logs (ie the deprecation notice). 

So this is the feature: Show the logs on exception. 

I hope my explanation make sense. I suggest closing this issue.

**Comment by OskarStark** [comment]
Closing as explained, thank you Tobias.

@I-Valchev feel free to reopen this issue if you don't agree 👍
