### ISSUE TITLE
Would it be possible to remove @internal from `AbstractController::setContainer` ?

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#42052]
**Description**

Hi @nicolas-grekas, when you introduce the AbstractController class, you made the `setContainer` method internal
https://github.com/symfony/symfony/commit/a93f05987850b0f63dc0ca79a720d176ddf7215e

In the Sonata tests, we're often instantiating Controller and passing a container with mocked services
https://github.com/sonata-project/SonataAdminBundle/blob/master/tests/Controller/CRUDControllerTest.php

In a general way, every method marked as `@required` has to be manually called when the class is instantiated manually. As a comparaison, the `ServiceSubscriberTrait` also has a `@required` `setContainer` method but this one is not marked as internal.

When using psalm level 2, internal methods are reported as an error (which is a good thing because internal methods are supposed to stay internal, by definition). Would it be possible to remove the internal annotation to this method ? If so, I can do the pr. Which branch should I target for such a change ?

**Comment by nicolas-grekas** [comment]
No pb, PR welcome. Please add a return type to the method while doing so.
For 5.4!
