### ISSUE TITLE
[HttpClient] CurlHttpClient throws Undefined constant `CURLOPT_PINNEDPUBLICKEY`

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#42061]
**Symfony version(s) affected**: 5.3, 5.4

**Description**
Some CURL constants could be not defined depending on libcurl version. 
Thus private `CurlHttpClient::validateExtraCurlOptions` throws `Undefined constant "CURLOPT_PINNEDPUBLICKEY"` even though user code doesn't use this constant. https://github.com/symfony/symfony/blob/1fc489f1f08ef60b2453ad71de83bec1e3512542/src/Symfony/Component/HttpClient/CurlHttpClient.php#L519 

For example CURLOPT_PINNEDPUBLICKEY requires `libcurl 7.39.0`

**How to reproduce**

You could try `Centos 7` with `remi PHP`. 

```
PHP 8.0.8
cURL support => enabled
cURL Information => 7.29.0
```

```php
$client = new CurlHttpClient();
$response = $client->request('GET', 'https://download.geonames.org/export/dump/alternatenames/RU.zip', [
    'extra' => [
        'curl' => [
            CURLOPT_MAX_RECV_SPEED_LARGE => 1024
        ]
    ]
]);
var_dump(strlen($response->getContent()));
```

**Possible Solution**
Check that constant is `defined(...)` or add polyfill

**Comment by nicolas-grekas** [comment]
It's very hard to know what can and cannot be defined.
Please submit a PR adding the `defined()` checks if you have a setup that allows producing such an error.
There are already similar checks in the source, you can take inspiration from them.
