### ISSUE TITLE
[Messenger] [Redis] Can not consume messages published by third party in Redis

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony#42072]
**Symfony version(s) affected**: 5.2

**Description**
I try to consume messages from a Redis Stream which are published by a third party, but messages do not follow the expected structure from the Redis Bridge.

Accordingly to the code https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L398-L408

Messages have to be structured like: 
```json
{
    "message": {
        "body": {},
        "headers": []
    }
}
```

However, my messages doesn't look like this, but more like:

```json
{
    "field1": "value1",
    "field2": "value2"
}
```

**How to reproduce**
Use Redis Insight to push a message like 
```json
{
    "field1": "value1",
    "field2": "value2"
}
```

into a Stream, then consume this stream with symfony/redis-messenger.

Catch this error:

```
messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--] [<receivers>...]


 [OK] Consuming messages from transports "catalog_import".

 // The worker will automatically exit once it has exceeded 128M of memory or
 // received a stop signal via the messenger:stop-workers command.

 // Quit the worker with CONTROL-C.

 // Re-run the command with a -vv option to see logs about consumed messages.


In Connection.php line 399:

  Notice: Undefined index: message


messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--] [<receivers>...]
```

**Possible Solution**
A possible solution could be to determine the existence of the key `message` in `$message` array, and if not exists, return the raw message, which could be decoded by a custom serializer.

cc @lyrixx @sroze

**Comment by welcoMattic** [comment]
There is also an issue with the re-add behaviour of a message in the `get` function: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L353-L357
It assumes that the JSON of the message has `body` and `headers` keys, which can't be guaranteed if the message comes from a third party and does not follow this structure.

**Comment by welcoMattic** [comment]
cc @chalasr @nicolas-grekas, WDYT?

**Comment by chalasr** [comment]
I agree it's an issue as the current behavior seems inconsistent with other transports.
The proposed fix sounds good and backwards compatible to me. /cc @alexander-schranz in case you see any cons

**Comment by alexander-schranz** [comment]
If I'm looking at the [`Amqp`](https://github.com/symfony/symfony/blob/839d1acc55aaa2eda4c8373376bb5779e75bec19/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpReceiver.php#L72-L75),  [`Doctrine`](https://github.com/symfony/symfony/blob/839d1acc55aaa2eda4c8373376bb5779e75bec19/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L130-L131), [`Beanstalkd`](https://github.com/symfony/symfony/blob/839d1acc55aaa2eda4c8373376bb5779e75bec19/src/Symfony/Component/Messenger/Bridge/Beanstalkd/Transport/Connection.php#L149-L150), [`AmazonSQS`](https://github.com/symfony/symfony/blob/839d1acc55aaa2eda4c8373376bb5779e75bec19/src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php#L257-L258) Transport they also have headers and body in it or atleast return such a format with 'body'  and 'headers'. So I think currently this structure is used by every Transport and so is not Redis related, think other transports would run into the same problem currently.

If we want to support messages like above we should convert the message and the return of the `Connection::get` should stay the same with `body` and `headers` we should just fallback and use the whole message then as `body`. If there was no body explicit set, in Transports like `beanstalkd` we should then do the same to be consistent.

@welcoMattic I would still recommend for your third party messages to use some kind of rootKey like we did with `message`. Else the read and write of message could end into an unexpected type with single field values.

**Comment by lyrixx** [comment]
@alexander-schranz It's possible to write really inte-operable consumer / publisher AMQP. I did it in the past, and I [blogged](https://jolicode.com/blog/symfony-messenger-et-linteroperabilite) (🇫🇷 ) about it.

As you can see in the link you posted, body and header come from two different sources except for `Beanstalkd` and `Redis`.
Almost all provider have a feature to store a header alongside the body, but not `Beanstalkd` and `Redis`. That why (I guess) you put the (messenger) body and the (messenger)  header in the same place : the (redis) message (== messenger body).

I do think forcing a "message" key in a bad idea in Redis. The solution @welcoMattic propose it nice, BC, and simple and move toward better interoperability.

**Comment by welcoMattic** [comment]
Concretely, what I propose, is to allow users deserialize the "raw" message (in the Redis case, the array resulting from the Redis deserialization). By default, Symfony will look for `message` and `message.(body|headers)` keys. But actually this is done in `Connection::get`, my point is to move this in the serializer part.

**Comment by chalasr** [comment]
PR welcome I guess.

**Comment by alexander-schranz** [comment]
@welcoMattic if it make easier to understand and return it directly in the `get` the raw message its fine, the Connection class is `@internal` so there no BC promise need to keep in mind, just message format with message{body, headers} should still work as before.

**Comment by welcoMattic** [comment]
PR is ready to be reviewed. I add tests for `RedisReceiver` and update tests for existing classes.
