### ISSUE TITLE
Console run commands when they are SignalableCommandInterface and don´t have signalsToDispatchEvent

### ISSUE THREAD

**Issue by PaolaRuby** [symfony/symfony#42076]
**Description**
When a command extends a class wich implements `SignalableCommandInterface` but the command has empty signals to dispatch, it still can be executed, It can be useful when the extension is not available and the command is necessary.
Also, it can be used like a workaround for support other environments, for example windows servers, they don't have `pcntl` extension

**Example**
If change this 
https://github.com/symfony/symfony/blob/39e9d75c95598d6e09428f201f6f1921a40503f5/src/Symfony/Component/Console/Application.php#L950-L956
for this
```php
if ($command instanceof SignalableCommandInterface) {
    if (!$this->signalRegistry && !(empty($this->signalsToDispatchEvent) && empty($command->getSubscribedSignals()))) {
        throw new RuntimeException('Unable to subscribe to signal events. Make sure that the `pcntl` extension is installed and that "pcntl_*" functions are not disabled by your php.ini\'s "disable_functions" directive.');
    }
```
Now when `signalsToDispatchEvent` has signals still throws RuntimeException, but when it don't has, it continues, maybe i can make a PR

**Comment by chalasr** [comment]
👍 Looks like a bug to me. PR welcome on branch 5.2, with test case.

**Comment by wouterj** [comment]
I'm not sure about the logic in the current code.

`$this->signalsToDispatchEvent` doesn't hold the events from the command, but the available signals. https://github.com/symfony/symfony/blob/39e9d75c95598d6e09428f201f6f1921a40503f5/src/Symfony/Component/Console/Application.php#L93-L96

I'm unsure how this (the depatching of signal events) is related to which interface the command implements. That looks wrong to me in the current code.

The piece of code that should depend on this interface, should have this check and should have your proposed fix is a couple lines below: https://github.com/symfony/symfony/blob/39e9d75c95598d6e09428f201f6f1921a40503f5/src/Symfony/Component/Console/Application.php#L972-L974

**Comment by PaolaRuby** [comment]
@wouterj but the `throw` stops execution, and this piece of code is after that
https://github.com/symfony/symfony/blob/39e9d75c95598d6e09428f201f6f1921a40503f5/src/Symfony/Component/Console/Application.php#L972-L974
Changing the `if` of the `throw` make command works, I tested with a third party package
https://github.com/symfony/symfony/blob/39e9d75c95598d6e09428f201f6f1921a40503f5/src/Symfony/Component/Console/Application.php#L950-L956
