### ISSUE TITLE
[Messenger] [DX] Redis default configuration lead to fill server

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony#42122]
**Description**
Currently, the default redis configuration with lead to fill the redis server because messages are never deleted.

The documentation has a  little warning :
![image](https://user-images.githubusercontent.com/345029/125749133-a881ac0b-5ab5-4db6-8dc0-9709d80dd223.png)
(This warning should maybe red as it will lead to break production at some point)

It seems to me that the default configuration can be improved so acked message are deleted by default.

WDYT ?

**Comment by chalasr** [comment]
I agree here, with messenger this option makes sense as a default.
/cc @Seldaek @alexander-schranz

**Comment by alexander-schranz** [comment]
@chalasr  was thinking the same in the past that for Symfony 6 it will make sense to make `delete_after_ack=true` as default value as the other transports like doctrine behave the same way. So the once which use redis then as real stream can set it then to false with `delete_after_ack=false`. But think the most people use redis just as an alternative to doctrine transport and don't need to stream feature with groups and multiple receivers where the messages need to be stay.

**Comment by Seldaek** [comment]
I fully agree, the default is currently harmful and surprising, if you don't read the fine print you'll shoot yourself in the foot.

**Comment by chalasr** [comment]
See #42163

**Comment by magnetik** [comment]
Awesome ! Ton of thanks 🥇
