### ISSUE TITLE
[WebProfilerBundle] Ability to view all logs together

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#42155]
I am not sure if it's maybe just me, but it's annoying me almost every time I look at logs via the profiler that I can only see debug OR info/error, but not all at once. And given the timestamps only have seconds I cannot exactly tell which log happened first, and where the error occurs exactly amongst the debug logs.

I would find it very valuable to have a "All" tab or having checkboxes to include/exclude logs instead of a tabbed view.

**Comment by javiereguiluz** [comment]
Yes, I think this makes sense.

I'd like to introduce some changes in the entire WebProfilerBundle (not a redesign, only some minor modernization and some modest changes). This proposal could fit that set of changes.

**Comment by Seldaek** [comment]
Oh I missed the ongoing PR. Thanks a lot @javiereguiluz it looks like a great improvement!
