### ISSUE TITLE
Guard Authentication Factory doesnt work with new authenticator system

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#42170]
**Symfony version(s) affected**: 5.3.3

**Description**
I wanted to upgrade to the 'new authenticator system' but this isn't working because the GuardAuthenticationFactory isn't checking if it's using the 'new authenticator system' or not which conflicts because it's expecting the deprecated authenticator interface

**How to reproduce**
Setup an authenticator as on https://symfony.com/doc/current/security/authenticator_manager.html#creating-a-custom-authenticator this will result in error
`Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator::__construct(): Argument #1 ($guard) must be of type Symfony\Component\Security\Guard\AuthenticatorInterface, App\Security\LoginAuthenticator given`

**Possible Solution**
In [vendor/symfony/security-bundle/DependencyInjection/Security/Factory/GuardAuthenticationFactory.php:110](https://github.com/symfony/security-bundle/blob/5.3/DependencyInjection/Security/Factory/GuardAuthenticationFactory.php#L111)
Check which interface $guardAuthenticatorId is using and then use the correct one as definition class

**Comment by chalasr** [comment]
The guard bridge is meant to support configuring authenticators implementing the *guard* `AuthenticatorInterface` when using the new system, not the opposite. 
If `LoginAuthenticator` is not a guard authenticator, you cannot use the following config:
```yaml
guard:
    authenticators: ['App\Security\LoginAuthenticator']
```
Please paste your firewall configuration.

**Comment by dvdknaap** [comment]
> ```yaml
> authenticators
> ```

It was en guard authenticator class that extents `Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator`

for the new authenticator system i had to use
 `Symfony\Component\Security\Http\Authenticator\AbstractFormLoginAuthenticator`

My security.yaml config does have the guard authenticators setting like you have describe

**Comment by chalasr** [comment]
If you migrated your authenticator to make it use the new interface, then this is how it should be configured:

```yaml
your_firewall:
    # ...
    custom_authenticators:
        - 'App\Security\LoginAuthenticator'
```

As shown in the docs you linked, so you don't need the guard authenticator bridge.

**Comment by dvdknaap** [comment]
> If you migrated your authenticator to make it use the new interface, then this is how it should be configured:
> 
> ```yaml
> your_firewall:
>     # ...
>     custom_authenticators:
>         - 'App\Security\LoginAuthenticator'
> ```
> 
> As shown in the docs you linked, so you don't need the guard authenticator bridge.

Your right i overlooked this. thanks!
