### ISSUE TITLE
[RateLimiter] SlidingWindow to use microtime() instead of time()

### ISSUE THREAD

**Issue by jlekowski** [symfony/symfony#42194]
**Description**
`RateLimiter` uses usually full seconds:
* `time()`,
* `sleep()`,
* `\DateTimeImmutable::createFromFormat('U', [time])`.

Sometimes however, it goes with microseconds:
* `microtime(true)`,
* `usleep()`

and could use them even more widely:
* `\DateTimeImmutable::createFromFormat('U.u', [microtime])`,
* `return (float) $interval->format('%f') / 1e6   // microseconds...`,
* `public function getExpirationTime(): ?float;`.

Using `float` gives an option to set interval in milliseconds:
```php
var_dump(\DateInterval::createFromDateString('200ms')->format('%f'));
// string(6) "200000"
```
and also to shorten wait time (e.g. 1.8s instead of 2.0s).

**Example**
`SlidingWindow` uses `time()` which means that after running `->wait()` it is still considered as not expired.
```php
<?php

use Symfony\Component\RateLimiter\Policy\SlidingWindow;

require_once './vendor/autoload.php';

$window = new SlidingWindow('some_id', 2);
sleep(2); // mimic $limit->wait();
var_dump($window->isExpired()); // false - same second

$window = new class ('some_id', 2) {
    public function __construct(string $id, int $intervalInSeconds)
    {
        $this->windowEndAt = microtime(true) + $intervalInSeconds;
    }

    public function isExpired(): bool
    {
        return microtime(true) > $this->windowEndAt;
    }
};
sleep(2); // mimic $limit->wait();
var_dump($window->isExpired()); // true
```

**Summary**
Before I go with a PR I would like to know if this change/improvement sounds like something you might merge in (i.e. using integers for time is not set in stone). It works for me locally.

**Comment by Nyholm** [comment]
@wouterj Is there some specific reason we are using seconds? 
What about using microseconds everywhere in version 6.0? (ie still using integers)

**Comment by wouterj** [comment]
I don't personally see a use-case of limiting that requires microsecond precision. Are there such use-cases?

**Comment by Nyholm** [comment]
Not so much for limiting a user's login attempts but for API requests. I think it make sense. Sure, API authors can have the attitude of "just wait a bit longer", but it seams non-optimal for a library to use seconds. 

Changing to microseconds would also line up with messenger and their delay/retry. 

------

So Im on the fence, but Im leaning towards microseconds because it gives more freedom to the super cool "edge case users" with millions of requests per minute.

**Comment by jlekowski** [comment]
@wouterj, @Nyholm, thanks a mill for your time and having a look at this. I will prepare a PR with the changes.

**Comment by wouterj** [comment]
> So Im on the fence, but Im leaning towards microseconds because it gives more freedom to the super cool "edge case users" with millions of requests per minute.

Those users should not at all rely on a rate limiter build in php and requiring a full Symfony kernel boot 😅 (as also lined out in the docs, such tooling should be done as close to the edge as possible).


In any case, I guess adding it doesn't hurt much and if @jlekowski wants to put some time into making it like that, I guess there is nothing left to really  
"reject" a feature like this.

**Comment by Nyholm** [comment]
@jlekowski please ping me in the pr
