### ISSUE TITLE
[Console] PHP 8.1 deprecation notice for HelperSet::getIterator()

### ISSUE THREAD

**Issue by sebastianbergmann** [symfony/symfony#42199]
From https://github.com/sebastianbergmann/phpunit/runs/3111696987:

```
PHP Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in phar:///home/runner/work/phpunit/phpunit/tools/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
```

**Comment by derrabus** [comment]
Blocks #41552

**Comment by derrabus** [comment]
PR: #42260

**Comment by digitall-it** [comment]
Stumbled upon the same problem while starting Laravel Valet. The steps I followed where
`
brew install php
composer global require laravel/valet
valet install
`

result was

`
Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/[...]/.composer/vendor/symfony/console/Helper/HelperSet.php on line 104
`

**Comment by nicolas-grekas** [comment]
@digitall-it likely because you have an outdated version of symfony/console

**Comment by digitall-it** [comment]
Ok, so after investigating that in depth enough, it seems like that's not a local installation problem. So as this issue was old enough and has received fixes, I'll just have to bark to the Valet tree to double check their dependancies. Thank you for being so fast @nicolas-grekas !

**Comment by wawanneutron** [comment]
I have the same problem like this in php version 8.0 up, when i type composer in terminal there is a problem like that. https://github.com/symfony/symfony/issues/42199#issue-948390713

I solved this problem by updating composer to the latest version, update composer really solves this problem.

Hope it helps

**Comment by digitall-it** [comment]
By elaborating on @nicolas-grekas comment, after further inspection, it indeed was a local installation problem. Using `composer why-not symfony/console 4.0` I did manage to find which package prevented global installation of a more recent version of console, so after cleaning up a bit the global composer installation it solved itself.

**Comment by pierresilva** [comment]
`composer selfupdate`

**Comment by Chimiste** [comment]
Hello, 

I have the same issue when upgrade to ubuntu 22:04 and php8.1. by running this command, i got this error : 

root@vmi155065:~# composer self-update
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119

PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

**Comment by stof** [comment]
@Chimiste those warnings have already been solved in composer. But if you run `composer self-update` with an old version of composer that you have locally (to get a newer version), that version might not have the fix yet.

**Comment by Chimiste** [comment]
@stof , thanks for your reply but I am not able to update composer again.  what can I do to fix ? Can I remove and reininstall composer ?   

root@vmi155065:~# composer update
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /root
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
root@vmi155065:~#

**Comment by stof** [comment]
The last line says `Composer could not find a composer.json file in /root`. You cannot run `composer update` in a file that does not have a composer.json (as there is nothing to update then)

**Comment by Chimiste** [comment]
Yes but even where composer.json is i got another error. 
root@vmi155065:/var/www/amberdali.com# composer update
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 119
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:42
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:52
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:61
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:71
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:81
Deprecation Notice: Return type of JsonSchema\Iterator\ObjectIterator::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:90
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:51
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///usr/local/bin/composer/src/Composer/Repository/RepositoryManager.php:129
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///usr/local/bin/composer/src/Composer/Repository/RepositoryManager.php:129
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\CompositeRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/CompositeRepository.php:139
Loading composer repositories with package information
Deprecation Notice: Return type of Composer\DependencyResolver\Pool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:166

PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Deprecated:  iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

Deprecated: iconv(): Passing null to parameter #3 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113

  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo for packagist.org failed: Temporary failure in name resolution
  Failed to open stream: php_network_getaddresses: getaddrinfo for packagist.org failed: Temporary failure in name resolution


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by digitall-it** [comment]
I would like to add that I discovered that global installed composer packages share the same dependencies, and that I have shared in a previous message the way I discovered what prevented symfony/console from upgrading to a version that incorporates the fixes.

**Comment by Chimiste** [comment]
@digitall-it can you share how you fixed it ?

**Comment by digitall-it** [comment]
> Using composer why-not symfony/console 4.0 I did manage to find which package prevented global installation of a more recent version of console, so after cleaning up a bit the global composer installation it solved itself.

**Comment by Chimiste** [comment]
@digitall-it running composer why-not symphony/console 4.0 return :
[InvalidArgumentException]
  Could not find package "symphony/console" in your project

**Comment by digitall-it** [comment]
@Chimiste common error is to spell out the symfony framework's name wrong. Try again, with an f instead of a ph.

**Comment by wouterj** [comment]
Please use one of the support channels to get help instead of responding to a closed bug report: https://symfony.com/support This bug is fixed
