### ISSUE TITLE
The default "throw" configuration in prod env is a bit odd

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#42205]
## Default configuration for "throw" in prod env

I notice something strange. In prod env, a PHP notice or PHP warning is silently ignored. 
IMHO, this is wrong. WDYT?

---

## Code grooming about the default values

More over, I looked at the code, and we have some strangeness:

1. we [load](https://github.com/symfony/symfony/blob/d642f76b55e4b116b899f2e55c63f623e1380db5/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L934) the "debug_prod.php" file;
2. this [file defines](https://github.com/symfony/symfony/blob/d642f76b55e4b116b899f2e55c63f623e1380db5/src/Symfony/Bundle/FrameworkBundle/Resources/config/debug_prod.php#L18) `debug.error_handler.throw_at` to `-1`:
    ```php
    $container->parameters()->set('debug.error_handler.throw_at', -1);
    ```
3. If the `framework.php_errors.throw` config is not defined, we [set](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1147-L1151) it to `false` (this is the default value in prod env)
4. Finally, if the `framework.php_errors.throw` config is not defined, we override 2/ with `0`.

To me the code is a bit awkward because we define something in debug_PROD, but this is not the default value for the prod, but for the dev env.

If the decide to keep the default configuration for throw to `false`, I think it would be more clear to

* use 0 in `debug_prod.php`.
* force -1, when the config tell it so. 

Or don't use a default value in debug_prod.php and only set the value in the extension.

**Comment by lyrixx** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
> In prod env, a PHP notice or PHP warning is silently ignored

This is the case since always, and I don't see why we should change this.

About the way config works, I'm sure this is the result of so many changes on the topic.
I would welcome a cleanup there (that'd preserve the overall behavior).

**Comment by lyrixx** [comment]
> This is the case since always, and I don't see why we should change this.

OK, let's close this one.

About a refactoring: I have no bandwidth ATM for working on it, and IMHO this is really not the priority since it works.

**Comment by php4fan** [comment]
> In prod env, a PHP notice or PHP warning is silently ignored.

How silently? Are they logged? Is it possible to have them logged while still not throwing?

The answer to the last question MUST be yes.

**Comment by lyrixx** [comment]
>How silently? 

like really silent

> Are they logged? Is it possible to have them logged while still not throwing?

not by default, you must add the following code in your config to update log level:

```
framework:
    php_errors:                                                                                                                                                                                                    
        log:                                                                                                                                                                                                       
            !php/const \E_DEPRECATED: !php/const Psr\Log\LogLevel::WARNING                                                                                                                                         
            !php/const \E_USER_DEPRECATED: !php/const Psr\Log\LogLevel::WARNING                                                                                                                                    
            !php/const \E_NOTICE: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                               
            !php/const \E_USER_NOTICE: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                          
            !php/const \E_STRICT: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                               
            !php/const \E_WARNING: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                              
            !php/const \E_USER_WARNING: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                         
            !php/const \E_COMPILE_WARNING: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                      
            !php/const \E_CORE_WARNING: !php/const Psr\Log\LogLevel::ERROR                                                                                                                                         
            !php/const \E_USER_ERROR: !php/const Psr\Log\LogLevel::CRITICAL                                                                                                                                        
            !php/const \E_RECOVERABLE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL                                                                                                                                 
            !php/const \E_COMPILE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL                                                                                                                                     
            !php/const \E_PARSE: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_CORE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
```

> The answer to the last question MUST be yes.

I agree with you, by default, symfony should log notice ! 

see https://github.com/symfony/symfony/issues/54036
