### ISSUE TITLE
Exim defaults all ports with TLS capability, including port 25, So can not send a non TLS email via port 25.

### ISSUE THREAD

**Issue by samuelvi** [symfony/symfony#42200]
**Symfony version(s) affected**: x.y.z
Symfony/Mailer Component v5.3.3

**Description**

The use case is: Being able to send an e-mail locally, which will be routed to a custom e-mail server. For that reason the sysadmin guy asks me to send an e-mail to localhost with NO TLS. 

- Port 465 can not be used, mailer component source code forces TLS even though parameter verify_peer is set to 0

- Port 25 can not be used, when verify_peer=0, $stream TLS i set to false, so $stream->isTLS() is false but there is an extra check that bypasses that value: array_key_exists('STARTTLS', $capabilities)

There is a comment in the code warning to check consistency between verify_peer and email server configuration, but as far as EXIM has changed its default behaviour (port 25 is by default considered TLS) an TLS connection is always started so can not send e-mails.

Error gotten:

Expected response code "220" but got code "454", with message "454 TLS currently unavailable"

**How to reproduce**

using this Email Transport DSN:  'smtp://email:password@localhost:25?verify_peer=0'

**Possible Solution**

1) adding a kind of verify_peer force parameter
2) Removing the "!" in the condition !$stream->isTLS() .... in the file EsmtpTransport.php line 122
    I am aware about the comment above, just because of the exim behaviour, in my case does not work.

   So this line: 
    if (!$stream->isTLS() && \defined('OPENSSL_VERSION_NUMBER') && \array_key_exists('STARTTLS', $capabilities)) {
   Would be
   if ($stream->isTLS() && \defined('OPENSSL_VERSION_NUMBER') && \array_key_exists('STARTTLS', $capabilities)) {
 
In other case there is some kind of contradiction.

   Manually removing that "!" in the vendors file, works in my case. But that is not the solution :)

**Additional context**

Thanks a lot!

**Comment by samuelvi** [comment]
Hi,
The sysadmin guy had a deeper check to the e-mail server configuration and realized that the certification was misconfigured (a missing end of line).
So after fixing the cert issue, the Mailer worked properly.
Thanks a lot and so sorry about that.
Regards!

  Samuel

**Comment by xabbuh** [comment]
Let's close here then. Thank you for the feedback!
