### ISSUE TITLE
[DependencyInjection] `ServiceSubscriberTrait` does not allow non-service "getter" methods

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#42217]
**Symfony version(s) affected**: 4.2+

**Description**
When using the `ServiceSubscriberTrait`, you cannot have methods with no arguments and a class return type that cannot be created as a service. Memoization of a value object/model is a common use-case that would create this problem.

This issue was brought to my attention by @weaverryan who had this issue in a _real app_.

**How to reproduce**
https://github.com/kbond/subscriber-trait-bug-reproducer is a reproducer. Clone and run `composer install && bin/console lint:container` to see the exception. [This](https://github.com/kbond/subscriber-trait-bug-reproducer/blob/dc8ed379f90739c1029ba729018f7216906817c6/src/ServiceWithSubscriberTrait.php#L23) is the method that causes the problem.

**Possible Solution**
My [initial proposal](https://github.com/symfony/symfony/issues/23898#issuecomment-345007281) for [this feature](https://github.com/symfony/symfony/pull/27077) required users tag methods they want as services with a `@service` docblock tag. This was ultimately rejected but perhaps we could bring this idea back with attributes?

```php
#[SubscribedService]
private function service1(): Service1
{
    return $this->container->get(__METHOD__);
}

#[SubscribedService('custom_name')]
private function service2(): Service2
{
    return $this->container->get('custom_name');
}
```

I'd suggest deprecating the current usage (no attribute) in 5.4 and requiring attributes in 6.0. I don't know how/if this would work with Symfony's BC policy seeing as attributes are PHP8+ and Symfony 5 requires 7.2...

Any other ideas?

**Comment by stof** [comment]
> I don't know how/if this would work with Symfony's BC policy seeing as attributes are PHP8+ and Symfony 5 requires 7.2...

We could trigger the deprecation when running on PHP 8+ (projects have to migrate to PHP 8 *before* migrating to Symfony 6 anyway as Symfony 6 cannot run on PHP 7.x)
