### ISSUE TITLE
Symfony DebugToolBar does not appear

### ISSUE THREAD

**Issue by anca007** [symfony/symfony#42224]
**Symfony version(s) affected**: Symfony 5.2.11/5.3.3

**Description**
The debugToolBar is not working. When i check how the container working, i see that : 

bin/console debug:container web_profiler.debug_toolbar --show-arguments

Information for Service "web_profiler.debug_toolbar"
====================================================

 WebDebugToolbarListener injects the Web Debug Toolbar.

 ---------------- ------------------------------------------------------------------------
  Option           Value
 ---------------- ------------------------------------------------------------------------
  Service ID       web_profiler.debug_toolbar
  Class            Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener
  Tags             kernel.event_subscriber
                   container.hot_path
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
  Arguments        Service(twig)

                   2
                   Service(router.default)
                   ^/((index|app(_[\w]+)?)\.php/)?_wdt
                   Service(web_profiler.csp.handler)
                   Service(data_collector.dump)
 ---------------- ------------------------------------------------------------------------

 **! [NOTE] The "web_profiler.debug_toolbar" service or alias has been removed or inlined when the container was compiled.**

This note kill me. I tried on new project in 5.2 and 5.3 and it's the same result

**How to reproduce**
Just install a new website-skeleton project, and add the apache-pack

Or maybe this problem is just for me ?

Thanks,

**Comment by stof** [comment]
> This note kill me.

Well, the listener being inlined is totally expected.

**Comment by xabbuh** [comment]
Does your Apache virtual host config allow to configure anything through a `.htaccess` file?

**Comment by anca007** [comment]
I create a  new project a week ago, and there is no problem. I have access to the debugToolBar on all old projects. Except very recent projects. I didn't change the config on Apache. 

It's working fine for you ? If you tell me it's working fine so it comes from me

**Comment by xabbuh** [comment]
Can you share your virtual host config?

**Comment by anca007** [comment]
I'm on WampServer

`# Virtual Hosts
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot "${INSTALL_DIR}/www"
  <Directory "${INSTALL_DIR}/www/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>`

**Comment by anca007** [comment]
the problem was me, sorry, thank you for your help !
