### ISSUE TITLE
Region set in MAILER_DSN not being used

### ISSUE THREAD

**Issue by sterichards** [symfony/symfony#42222]
**Symfony version(s) affected**: 5.3

**Description**

I have set `MAILER_DSN=ses+api://<key>:<secret key>@default?region=eu-west-2` but the mailer is attempting eu-west-1

**How to reproduce**

`$email = (new Email())
            ->from(new Address('someone@somewhere.com', 'Info'))
            ->to($user->getEmail())
            ->subject('Your password reset request')
             ->text('password reset')
            ->html('<p>password reset</p>')
        ;`

**Possible Solution**

**Additional context**

Log:

[21-Jul-2021 13:56:22 UTC] [error] HTTP 400 returned for "https://email.eu-west-1.amazonaws.com/v2/email/outbound-emails".

[21-Jul-2021 13:56:22 UTC] [critical] Uncaught PHP Exception Symfony\Component\Mailer\Exception\HttpTransportException: "Unable to send an email: Email address is not verified. The following identities failed the check in region EU-WEST-1: someone@somewhere.com (code MessageRejected)." at /var/www/html/vendor/symfony/amazon-mailer/Transport/SesHttpAsyncAwsTransport.php line 62

**Comment by sterichards** [comment]
This was meant to be on the symfony/amazon-mailer project

**Comment by Nyholm** [comment]
Are you sure about this?

There is a test case for this already: https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Mailer/Bridge/Amazon/Tests/Transport/SesTransportFactoryTest.php#L77

**Comment by sterichards** [comment]
> Are you sure about this?
> 
> There is a test case for this already: https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Mailer/Bridge/Amazon/Tests/Transport/SesTransportFactoryTest.php#L77

It seemed so. I have since been granted SES permission to the IAM user on eu-west-1 so I didn't look further

mailer.yaml:

`framework:

    mailer:

        dsn: '%env(MAILER_DSN)%'`

And the MAILER_DSN value in .env was posted above. If you want me to try something further I can do that. Let me know please

**Comment by xabbuh** [comment]
I fail to see how this does not work. Let's close here for now until we are able to reproduce and debug the issue.
