### ISSUE TITLE
[Yaml] Reserved keywords are preserved

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#42232]
**Symfony version(s) affected**: tested 5.4

Given

```yaml
YES: NO
NO: YES
```

(and other related reserved keywords) i expected quotation was needed.

symfony/yaml however seems to preserve as-is:

```
array(2) {
  ["YES"]=>
  string(2) "NO"
  ["NO"]=>
  string(3) "YES"
}
```

but YAML considers this canonically as

```yaml
!!map {
  ? !!bool "false"
  : !!bool "true",
  ? !!bool "true"
  : !!bool "false",
}
```

**Comment by stof** [comment]
`yes` and `no` are not boolean keywords anymore in Yaml 1.2 AFAIK

**Comment by ro0NL** [comment]
🤦‍♂️ i think you're right. That is great news actually.

https://stackoverflow.com/questions/42283732/are-on-and-off-supposed-to-be-interpreted-as-true-or-false-in-yaml-1-2
