### ISSUE TITLE
"Backport type fixes" BC break

### ISSUE THREAD

**Issue by antonioribeiro** [symfony/symfony#42272]
**Symfony version(s) affected**: 5.3.4

**Description**
By type hinting a series of (before untyped) methods, this ["Backport type fixes" commit](https://github.com/symfony/symfony/commit/6f6c1a1661a3861a4f0dbd07ac03f62dcd153fba) is breaking backward compatibility to other packages.

**How to reproduce**
Breaks [DebugBar](https://github.com/barryvdh/laravel-debugbar), for example: https://github.com/maximebf/php-debugbar/issues/474

**Comment by rrpadilla** [comment]
The function "**setDumpHeader**" should allow null value. 
**String** value is required now. See [here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component

```php
    /**
     * Sets an HTML header that will be dumped once in the output stream.
     */
    public function setDumpHeader(?string $header)
    {
        $this->dumpHeader = $header;
    }
```

Submit a PR #42274
