### ISSUE TITLE
[Serializer] preserving empty object breaks current array lists

### ISSUE THREAD

**Issue by Foxprodev** [symfony/symfony#42282]
**Symfony version(s) affected**: 5.4

**Description**
PR #42240 silently breaks BC.

**How to reproduce**
```
class Foo {
    public ArrayObject $object;

    public array $list = [];

    public function __construct()
    {
        $this->object = new ArrayObject();
    }
}
$serializer = new Serializer([new ObjectNormalizer()], ['json' => new JsonEncoder()]);
$serializer->serialize(new Foo(), 'json', [AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true]);
```
**At 5.3**  
`{"object":{},"list":[]}
`
**At 5.4**  
`{"object":{},"list":{}}
`

**Possible Solution**
Create a new context option like `ARRAY_FORCE_OBJECT`. This option should apply only for current property and do not propagate deeper. This option also should transform plain array to ArrayObject always.

**Additional context**
Current solution produces many complications with empty array normalization too (described here https://github.com/symfony/symfony/pull/42240#issuecomment-887064245)

**Comment by lyrixx** [comment]
The pr actually fix the initial issue: Setting `AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true` will also affect property of object.

Also, the context is passed recursively,  that's why I did not want to set it globally like you did. I [answered that](https://github.com/symfony/symfony/issues/38192#issuecomment-692720938) to another comment in the initial issue.

That's why, in your case, you see modifications. IMHO, you should put the annotation only where you want it and not globally.

Finally, In your case, you don't even need to pass the option because you are using ArrayObject, and `ArrayObject` when empty, are always serialized as `{}`.

But if you think this is a BC break, we could create another option like you suggested

**Comment by Foxprodev** [comment]
> Finally, In your case, you don't even need to pass the option because you are using ArrayObject, and `ArrayObject` when empty, are always serialized as `{}`.

It doesn't. Thats why PRESERVE_EMPTY_OBJECTS was introduced

**Comment by lyrixx** [comment]
Oh, Indeed there is something I did not know:

1. ```
    php > dump(json_encode(new \ArrayObject()));
    ^ "{}"
   ```
2. In symfony, we use `ArrayObject()` to serialized empty collection to `{}`. [ref](https://github.com/symfony/symfony/blob/7ece48f2144ee5fd39059e6f8bd4419340379262/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L210-L212)
3. But I tested the following code, and indeed the output is `[]`
    ```php
    $serializer = new Serializer(
        [
            new ObjectNormalizer(),
        ],
        [
            'json' => new JsonEncoder(),
        ]
    );
    
    
    $data = [
        'ArrayObject' => new \ArrayObject(),
    ];
    
    dump($serializer->normalize($data, 'json'));
    ```

---

So I think you are right, and thanks a lot for taking time of testing new version. This is very much appreciated.

I'll open a new PR and I will introduce a new key to ensure we don't break anything.

**Comment by Foxprodev** [comment]
> I'll open a new PR and I will introduce a new key to ensure we don't break anything.

Thank you :smile: 
But still it could be better to introduce local property-only context somehow. What do you think? 
Pretty sure I am not the only one who use serializer for serializing nested resources and it will be annoying to always control new option propagation.

**Comment by lyrixx** [comment]
I think it's safer to create a new option, that reflect much more what is actually does.
I opened a new [PR](https://github.com/symfony/symfony/pull/42297) and added much more tests.

Thanks for your issue, The code is not better IMHO! 

If you can test it, it would be awesome

**Comment by Foxprodev** [comment]
> If you can test it, it would be awesome

Yes, of course, I'll do it tomorrow
