### ISSUE TITLE
Compiled container calls `EventDispatcherInterface::addListener()` with non-callable listener 

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#42283]
**Symfony version(s) affected**: 5.3.4, 5.2.12

**Description**
The ["Backport Type Fixes" commit](https://github.com/symfony/symfony/commit/6f6c1a1661a3861a4f0dbd07ac03f62dcd153fba) added a callable type declaration to the `$listener` parameter of `EventDispatcherInterface::addListener()`. Adding that type declaration to implementations will break when using the dependency-injection container. The reason is that the dependency-injection container will generate code that calls `addListener` with an array as listener where at index 0 an closure is passed that will resolve to the object that should be called and at index 1 the method name that should be called is passed. According to the [official documentation](https://www.php.net/manual/en/language.types.callable.php) an array is only considered callable if at index 0 of the array the instantiated object is passed, it seems like passing a closure there is not considered to be callable.

**How to reproduce**

Add a custom EventDispatcher decorater that uses the `addListener()` method signature from the interface:
```php
    public function addListener(string $eventName, callable $listener, int $priority = 0): void
```
Or add that native type declaration to the EventDispatcher implementation.

Configure some event subscriber in the service configuration.

After that the dependency-injection container is broken:
```
Argument 2 passed to EventDispatcher::addListener() must be callable, array given
```

**Possible Solution**
Remove the type declaration from the EventDispatcherInterface again. 

Or rework the dependency-injection to call `EventDispatcherInterface::addListener()` in a way that is compatible with that type declaration.

**Additional context**
The generated code for the dependency injection container looks like this:
```php
$instance->addListener('kernel.request', [0 => function () {
    return ($this->privates['serviceId'] ?? $this->getService());
}, 1 => 'onKernelRequest'], 0);
```
That seems to not pass the native callable type declaration.

**Comment by xabbuh** [comment]
I am not sure if I really got all the steps that are required to reproduce this. Can you please create a small example application that allows to debug this?

**Comment by keulinho** [comment]
Please take a look at following [phpsandbox notebook](https://phpsandbox.io/n/morning-tree-ngyy-34gsl?files=%2Fsrc%2FEventDispatcherDecorator.php), the interesting change is the `App\EventDispatcherDecorator`, that decorates the `event_dispatcher` service and uses the native type decalrations of the  `EventDispatcherInterface` for the `addListener()` method.

The notebook uses Symfony Web Skeleton, which already uses the dependency-injection component and has some EventSubscribers configured.

**Comment by derrabus** [comment]
Symfony's own implementations don't have the `callable` parameter type declaration. It has only been added to the interface. If you removed `callable` from your implementation as well, you should be good.

That being said, should we remove `callable` type declarations from the interface again? If all of our own implementations ignore it anyway, why does the interface declare it? /cc @nicolas-grekas

**Comment by keulinho** [comment]
Yes removing the type declaration on the implementation resolves the issue. But IMHO the interface should not use type declarations that can not be used in the implementations.

So removing the type declaration on the interface makes sense to me.

**Comment by derrabus** [comment]
PR: #42319

**Comment by nicolas-grekas** [comment]
PR has been rejected, see https://github.com/symfony/symfony/pull/42319#issuecomment-894772436 for the reason why.
