### ISSUE TITLE
Get direct descendent text only when calling text() on a node.

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#42294]
**Description**
Get direct descendent text only when calling `text()` on a node.

**Example**
When an HTML node contains mixed text and element nodes, it is difficult to get just the text of the current node, since the `text()` call will also recursively parse all descendents.

```xml
<foo>
    foo
    <bar>bar</bar>
</foo>
```

When we have a `Crawler` instance pointing at `<foo>`, calling `text()` will return `foo bar`. There is no way to get just the direct descendent text node, `foo`.

**Comment by xabbuh** [comment]
`$crawler->filterXPath('//foo/text()')->text()` does what you need, doesn't it?

**Comment by Bilge** [comment]
And what if you don't know XPath and rely on `filter()` to navigate deep and complex structures? Is there a CSS equivalent?

**Comment by xabbuh** [comment]
Not that I am aware of. In any case, there's nothing we can do here in the codebase about it. So I am closing here. Thank you for understanding.

**Comment by Bilge** [comment]
But I don't understand. Why is there nothing that can be done?

**Comment by xabbuh** [comment]
What solution do you see if CSS doesn't allow to filter the particular node exclusively?

**Comment by Bilge** [comment]
Either a parameter or method that only returns the direct decedent text node, e.g. `text($ownTextOnly = false)` (I believe this is not possible because `text()` already takes a parameter for some other purpose), or `ownText()`, for example. The implementation of `ownText()` would be free to use XPath or CSS as it wishes since it would be internal.
