### ISSUE TITLE
[HttpFoundation] Add litespeed_finish_request to Response

### ISSUE THREAD

**Issue by thomas2411** [symfony/symfony#42293]
For now Litespeed has dropped support for `fastcgi_finish_request` function due to some problems: https://github.com/php/php-src/commit/ccf051c317e606c2a4d9099c6e79a5c42bfdb298 so when Litespeed is being used on a server instead of Apache, then there is no possibility to use `fastcgi_finish_request` function as the alias for `litespeed_finish_request` is turned off.

So in `Symfony\Component\HttpFoundation\Response` in line 398 https://github.com/symfony/symfony/blob/ff545130e0e16caee772633f6ea1ef8fef3aa04c/src/Symfony/Component/HttpFoundation/Response.php#L397 I would like to add a new if statement to support it:

        if (\function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        } elseif (\function_exists('litespeed_finish_request')) {
            litespeed_finish_request();
        } elseif (!\in_array(\PHP_SAPI, ['cli', 'phpdbg'], true)) {
            static::closeOutputBuffers(0, true);
        }

I have forked the symfony/symfony repository and added the code, tested on a server. If you agree to add it I can make a PullRequest.

**Comment by OskarStark** [comment]
Can you please open a PR, so we can discuss about the code? Thanks

**Comment by thomas2411** [comment]
> Can you please open a PR, so we can discuss about the code? Thanks

Done
