### ISSUE TITLE
Deprecate and eventually remove global functions that are not polyfills

### ISSUE THREAD

**Issue by helhum** [symfony/symfony#42309]
**Description**
This is more a "request for comments" and or a suggestion than a feature request, but did not see another way to get in touch than creating a ticket here.

As surfaced in some issues #40203 #42280, declaring global functions using the Composer autoload "includes" section can be problematic in some cases and initially was even considered more of a [hack](https://github.com/composer/composer/issues/10024#issuecomment-888270023).

My suggestion therefore is, to not introduce global functions any more, which are purely convenience 
[shortcuts for other functionality](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/String/Resources/functions.php) and deprecate the existing ones.

What do you think?

**Comment by derrabus** [comment]
Those "global functions" (`str_contains()` and friends) have been introduced by PHP itself. If you want them removed, this is the wrong issue tracker.

**Comment by chalasr** [comment]
We know that the string related functions you linked are appreciated by some people, and we never got any issue about those so they don't seem to harm in any way. 
About #40203 and #42280, these are bugs in our polyfills which have been fixed or are going to be, not an issue with global helper functions on their own. 
Thanks for the proposal, but I'm personally against it.

**Comment by helhum** [comment]
To clarify: I'm not here to fight for anything. 
Yet I'm a bit disappointed by the response.

Of course I'm aware that new php versions come with new global functions and I see and understand how polyfilling these for older PHP versions seem to come at little cost, but in fact these costs are higher than one might see at first glance. But this RFC isn't about these polyfills, as they become obsolete anyway with using newer PHP versions. 

This RFC was not about polyfilling functions that are introduced in newer PHP versions, but about introducing global functions as "shortcuts" for existing class based functionality, basically as a matter of style. 

I wanted to raise awareness that the cost of these shortcuts do not outweigh their cost.

Seeing such suggestion voted down and commented ironically without fully reading what was suggested, demotivates me for further contributions.

**Comment by xabbuh** [comment]
I honestly do not really understand your request then. Can you give a concrete example of such a shortcut that we have in the Symfony codebase that you have in mind?

**Comment by helhum** [comment]
Aren't these [functions](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/String/Resources/functions.php) just convenience shorthands for writing `new ClassName($string)`

I would also consider the `trigger_deprecation` function a shorthand for writing `trigger_error`.

In both cases I would rather go for static methods on classes or for just skipping the function declaration completely. 

I personally see more dept than benefit with such functions at least until PHP will be capable to autoload functions.

**Comment by faizanakram99** [comment]
> Aren't these functions just convenience shorthands for writing new ClassName($string)

These are namepsaced functions, not global
