### ISSUE TITLE
SendGrid Mailer stopped working after latest update

### ISSUE THREAD

**Issue by rubanooo** [symfony/symfony#42306]
**Symfony version(s) affected**: 5.3

**Description**
Sending e-mails via de Sendgrid mailer API transport stopped working after the latest update, I have done some digging in the commits and it seems like the following commit: https://github.com/symfony/sendgrid-mailer/commit/e6f0e4313def1a4def569b38bb06b6f7c422879b breaks sending emails.

The sendgrid API does not return a response body when sending the email has been successful, see documentation [here](https://docs.sendgrid.com/api-reference/mail-send/mail-send#responses). This causes an exception when decoding the response.

**How to reproduce**

Setup the sendgrid mailer per documentation and send an email with a 202 response

**Possible Solution**

Check that the response code before decoding the response.

* If the response code is 202, do nothing
* If the response code is an error code, decode the response and use it in the exceptions for a clear error message

**Comment by fabpot** [comment]
Can you work on a fix?
