### ISSUE TITLE
Submitting ChoiceType with more than 998 selected  choices fails

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#42311]
**Symfony version(s) affected**: 5.2.8

**Description**
I am experiencing a weird problem

If I submit a form that has a ChoiceType with more than 998 choices selected, I get a CSRF error.

**How to reproduce**
See this test case:
```
/**
     * @Route("/formtest/{num}", name="formtest")
     */
    public function formTestAction(Request $request, $num)
    {
        $choices = [];
        for($i = 0; $i < $num ; $i++)
            $choices['c'.$i] = $i;
        $builder = $this->createFormBuilder(['choice' => array_values($choices), 'text' => 'Ein Test']);
        $builder->add('choice', ChoiceType::class, ['choices' => $choices, 'multiple' => true]);
        $builder->add('text', TextType::class, ['label' => 'Text']);
        $builder->add('save', SubmitType::class, array('label' => 'Ja', 'attr' => ['class' => 'btn btn-success']));
        $form = $builder->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            dump($data);
        }
        return $this->render('default/form.html.twig', array(
            'form' => $form->createView()
        ));
    }
```
If I execute this action and just submit with `http://localhost/formtest/998`, it works.

With `http://localhost/formtest/999` it fails.

In the latter case, if I deselect one choice to hat 998 selected choices, if works again.

Is there a limit?

**Additional context**
I am working with PHP 7.4 FPM and nginx. My max_upload_size and max_post_size is at 60MB so this should not be the reason.

**Comment by xabbuh** [comment]
Can you please create a fully functional application that allows us to reproduce the issue you experience?

**Comment by flaushi** [comment]
you mean forking a demo-application? Which one?

**Comment by jvasseur** [comment]
My guess would be that you hit the [max_input_vars](https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars) PHP limit. Since it's 1000 by default and you have 2 fields (the text field and the CSRF hidden field) in addition to your choice field it makes 998 the maximum number of choice you can submit.

The solution is to increase this value in your php.ini.

**Comment by flaushi** [comment]
I created this  https://phpsandbox.io/e/x/n2rve?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=

**Comment by flaushi** [comment]
Oh yeah, thanks @jvasseur, thank you very much! I did not know about this config. You're great!
