### ISSUE TITLE
[Security] EncoderFactoryInterface is deprecated, but it is still used in the UserPasswordEncoderCommand

### ISSUE THREAD

**Issue by dhaarbrink** [symfony/symfony#42325]
**Symfony version(s) affected**: 5.3.x

**Description**
In the `CHANGELOG.md` of the 5.3 branch there is this line:

> Deprecate the `security.encoder_factory.generic` service, the `security.encoder_factory` and `Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface` aliases, use `security.password_hasher_factory` and `Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface` instead

But it is still used in the [UserPasswordEncoderCommand](https://github.com/symfony/security-bundle/blob/5.3/Command/UserPasswordEncoderCommand.php#L45)

**How to reproduce**

**Possible Solution**
Use the `PasswordHasherFactoryInterface` instead

**Additional context**

**Comment by wouterj** [comment]
Hi!

The `security:encode-password` command is also deprecated for the same reasons: https://github.com/symfony/symfony/blob/e43725f5572c10be58f38dbb9073959ffcff4f27/src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php#L113

You should use "security:hash-password" instead.
