### ISSUE TITLE
[messenger] log ConsumeMessagesCommand informational notices to stdout instead of stderr

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#42327]
Not sure if it's a bug, a feature request or just a question. Probably something in between. Why does `ConsumeMessagesCommand` use stderr instead of stdout for messages like `Consuming messages from transport...` introduced in https://github.com/symfony/symfony/pull/29303? I know i can disable the messages entirely using `-q`. Wouldn't stdout be more appropriate? Thank you.

**Comment by chalasr** [comment]
Stdout is about regular, processable output (as in reusable for further processing). It's usually the result of the command.
Any additional/exceptional output such as notices, errors, logs... should go to stderr. 

Also, while the core command might not output anything useful to stdout, the command might be extended in userland. Hence we prefer outputting everything to stderr in that case.

**Comment by maryo** [comment]
I always considered stderr suitable only for errors / warning / exceptions. I am surprised but looks like Symfony's approach is quite common after more googling. I should have googled more before asking here. Sorry and thank you.
