### ISSUE TITLE
Symfony\Component\Validator\Constraints\EmailValidator expects constraint of type User..?!

### ISSUE THREAD

**Issue by koredalin** [symfony/symfony#42339]
Hello All,
I think that this issue is more like a bug. But I'm not sure.
The expected constraint should be of type "Symfony\Component\Validator\Constraint\Email".
So, ...

![SymfonyValidationComposerJson](https://user-images.githubusercontent.com/6977867/127770596-a67a4534-cbf9-4e04-84ea-2dc34903c9db.png)

![SymfonyValidationEmailValidator](https://user-images.githubusercontent.com/6977867/127770606-39fd1122-8466-4676-8532-4559f18bbd74.png)

1.) There is no class "User" in namespace "Symfony\Component\Validator\Constraints".
2.) Other validators, such as DateTimeValidator expects constraint of type DateTime.
![image](https://user-images.githubusercontent.com/6977867/127770679-b708c1e7-1cbc-4c47-ad41-31fddba28b35.png)

Please, have a look and add some feedback here.

Thank you
Hristo

**Comment by OskarStark** [comment]
Checking our `5.3` codebase, everything looks correct:
https://github.com/symfony/symfony/blob/e39ee06d524f1429e116efb9822aabd4097a0b73/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L49-L57

**Comment by xabbuh** [comment]
Do you still experience this message with the latest 5.3 release? IIRC this was fixed at some point.

**Comment by koredalin** [comment]
I have started "composer update".
Now - all looks good.

Thank you.
