### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#42351]
**Description**
Did Symfony considered enabling the GitHub Discussions feature? It can be used to ask questions and share knowledge right from with-in GitHub. 

Currently https://symfony.com/community offers Slack and Stackoverflow.

Slack: since this is a free plan, only the most recent 10,000 messages can be viewed and searched. This is such a waste of spread knowledge. Also, using a Chat to ask questions is not really handy. Most of the time somebody else puts in another question after you and yours is lost.
Stackoverflow: I never used it and don't have an account. However, I'm super active on GitHub and this is where I search for issues and pull requests. Having discussions also in the same place would be a big win for me.

Example on how Laraval is doing it: https://github.com/laravel/framework/discussions

**Comment by OskarStark** [comment]
I brought this to the table in the past, but it was declined by the team.

Maybe some minds changed 😋

I think it has more pros than cons 👍🏻

cc @tarlepp

**Comment by fabpot** [comment]
I think we can do an experiment and see how it goes. WDYT @symfony/mergers?

**Comment by javiereguiluz** [comment]
I'm 👍  to try this and see how it goes.

**Comment by Nyholm** [comment]
Im always happy to try new things :+1:

**Comment by derrabus** [comment]
👍🏻 for trying out GitHub discussions as a support channel

**Comment by fabpot** [comment]
I've just enabled Discussions. I've added a quick first post here: https://github.com/symfony/symfony/discussions/42363
Feel free to comment there.
@javiereguiluz Can you draft a blog post to make the announcement?

**Comment by javiereguiluz** [comment]
@fabpot the blog post draft is ready for review at symfony.com backend. Thanks!
