### ISSUE TITLE
[DotEnv] [Doctrine] Issue with environment variables in quotes from .env* files

### ISSUE THREAD

**Issue by OleksiiBulba** [symfony/symfony#42367]
**Symfony version(s) affected**: 5.3.3

**Description**
Symfony creates .env file with an example variables, particularly
```
DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7"
```
All these example variables are quoted: `VAR="..."`. When I start request with step debugger, all these variables automatically are populated "as is":
```
$_SERVER = [
    'DATABASE_URL' => "\"mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7\""
];
```
Notice that the `DATABASE_URL` contains quotes in it. This is how bash env variables works, they do not need quotes, so the nginx/php/whatever populates server variables with quotes "as is".
On the contrary, Symfony parses env variables and considers quotes to distinguish env variables.
The issue is becoming worse because DotEnv skipps env variable overriding when server variable with same name exists.
So in my case when I keep quotes in my env variable, Doctrine is unable to parse database url (here: `vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php:351`), it gets only two parts:
```
$url = [
    'path' => "\"mysql://db_user:db_password@127.0.0.1:3306/db_name",
    'query' => "serverVersion=5.7\""
];
```

**How to reproduce**
Create minimum Symfony project, make sure that nginx/php/docker populates .env into php server envs
Check in step debugger that if variable from .env* contains quotes, it will have quotes in the server env, which is not good

**Possible Solution**
* Include example without quotes (if DotEnv allows it);
* Detect quotes in existing server envs by DotEnv and remove them;
* Detect quotes in existing server envs by Doctrine before parsing and remove them;

**Additional information**
One week ago I setup another similar project with Symfony 5.3.3 and I hadn't this issue.
P.S. I have checked and I did not included .env* files in my docker-compose containers, so env files were not populated to nginx/php server.

**Comment by xabbuh** [comment]
I am not sure I understand. How exactly do you populate the environment variables?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by OleksiiBulba** [comment]
@xabbuh sorry for a delay with answer. But the issue is still occurse.
I have an .env file with database variable DATABASE_URL with quotes:
```
<... other variables...>
DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7"
<... other variables...>
```
And I mention this file in my docker-compose.yaml file: 
```
services:
  nginx:
    # other stuff
    env_file:
      - ./.env
    # other stuff

  php:
    # other stuff
    env_file:
      - ./.env
    # other stuff
```
Because of that, Docker-compose exports all variables into the containers and they are added to the php global variable `$_SERVER`. The bash variable contains quotes, so the php and Symfony get the variable content with quotes too. Do when Doctrine parses variable as url, it gets incorrect result because of quotes.

On the other side, if variables are parsed by Symfony's DotEnv class, they will be without quotes, and Doctrine works well.

**Comment by xabbuh** [comment]
This looks like an issue with Docker to me then if it doesn't properly parse env files.

**Comment by OleksiiBulba** [comment]
@xabbuh thanks for the advise, I have created an issue for docker-compose repo: https://github.com/docker/compose/issues/8479
