### ISSUE TITLE
Remove preloading of `LegacyEventDispatcherProxy` in `HttpKernel`

### ISSUE THREAD

**Issue by UlrichThomasGabor** [symfony/symfony#42366]
This line can be removed:
https://github.com/symfony/http-kernel/blob/5.3/HttpKernel.php#L36

It's not working because `LegacyEventDispatcherProxy` is in a different namespace and the class is deprecated anyway.

**Comment by derrabus** [comment]
... and it's not used in that file anyway. Do you want to open a PR?

**Comment by UlrichThomasGabor** [comment]
I can open one if you don't have time, but if you have the code base open feel free to remove the line

**Comment by derrabus** [comment]
Please, go ahead. 🙂

**Comment by OskarStark** [comment]
I created a PR: https://github.com/symfony/symfony/pull/42377
