### ISSUE TITLE
[Cache] `NullAdapter` configuration in framework - Cannot replace arguments if none have been configured yet

### ISSUE THREAD

**Issue by olsavmic** [symfony/symfony#42364]
**Symfony version(s) affected**: 5.\*, 4.\*

**Description**

Defining custom adapter cache.adapter.null as a service and then using it as an adapter for cache pool fails with error 
`Cannot replace arguments if none have been configured yet.`

The error occurs due to CachePoolPass adding a namespace argument to the child definition tagged with `cache.pool` tag.

```
    ./vendor/symfony/dependency-injection/Definition.php:268 { …}
    ./vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:176 { …}
    ./vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:62 { …}
    ./vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:45 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81 { …}
    ./vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:36 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46 { …}
    ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:749 { …}
    ./vendor/symfony/http-kernel/Kernel.php:545 { …}
    ./vendor/symfony/http-kernel/Kernel.php:786 { …}
    ./vendor/symfony/http-kernel/Kernel.php:125 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:167 { …}

```

**services.yaml**
```yaml
cache.adapter.null:
    class: Symfony\Component\Cache\Adapter\NullAdapter
```

**config.yaml**
```yaml
framework:
  cache:
    pools:
      cache.pool.doctrine.orm.result:
        adapter: cache.adapter.null
```

**Possible Solution**
Quick fix:
```yaml
  cache.adapter.null:
    class: Symfony\Component\Cache\Adapter\NullAdapter
    arguments: [~]
```
-> Add artificial null argument that will be replaced (and not used during construction) in definition.

**Solution:**
Patch CachePoolPass for NullAdapter the same way it handles namespace argument for ArrayAdapter.

**Comment by n0rbyt3** [comment]
Why would you use a non-caching implementation as a cache? I assume the ```NullAdapter``` is designed to be used in functional tests only. If you need a non persistent in memory cache, ```ArrayAdapter``` should be the way to go.

**Comment by olsavmic** [comment]
@n0rbyt3
The use case is, as you stated, in functional tests. We do not want to have the caching behaviour enabled for some of our cache pools in **test** environment (the cache adapter and related configuration is test only). 

We were using Doctrine\Cache\VoidCache previously which has been removed in doctrine/cache:^2.0.

It's not a production related bug and it can be indeed replaced by ArrayAdapter that's cleared between test cases but I expect the NullAdapter should be configurable as long as it's in the codebase.
