### ISSUE TITLE
[Form] / Composer install incomplete

### ISSUE THREAD

**Issue by LL-actemedia** [symfony/symfony#42372]
**Symfony version(s) affected**: 4.4.11,  4.4.26,  4.4.27

**Description**
Since a week, we can't composer install the library symfony/form. There are only a few directories and some files. The main error when we launch the web site is FormInterface doesn't exist.

![Image Pasted at 2021-8-4 16-44](https://user-images.githubusercontent.com/88445448/128202039-ca731b1d-7eff-449a-974b-09d3484b0ee5.png)

List of downloaded files :
![Image Pasted at 2021-8-4 16-43](https://user-images.githubusercontent.com/88445448/128201993-6258c4d5-34cd-4cbd-be7a-b6051cdbe353.png)

Did i miss some new library reworking ?

**How to reproduce**
`composer require symfony/form:4.4.26 --ignore-platform-reqs`

**Comment by derrabus** [comment]
The files are definitely there: https://github.com/symfony/form/tree/v4.4.26

**Comment by javiereguiluz** [comment]
I've just created a new project, run the command you showed (`composer require symfony/form:4.4.26 --ignore-platform-reqs`) and the `FormInterface` class was there (with all the other expected files).

**Comment by LL-actemedia** [comment]
We know, we see them. Another information, we use composer 1.10.9.
We tried on different computers with the same result. It's strange :/

**Comment by LL-actemedia** [comment]
It seems ok with composer 2.1.3

**Comment by derrabus** [comment]
Let's close then.

**Comment by vasilvestre** [comment]
As an additional note, this just worked fine with skeleton and composer 1.10.
