### ISSUE TITLE
Language list is incomplete (doesn't include dialects)

### ISSUE THREAD

**Issue by someonewithpc** [symfony/symfony#42374]
**Symfony version(s) affected**: 5.*

**Description**

The current language list as provided by using a `LanguageType` form field doesn't provide options for picking language "dialects", some of which are rather different. For instance, there's a single 'English', a single 'Spanish' and a single 'Portuguese', but these languages are all spoken in a variety of regions. 

**How to reproduce**

Create a form with a `LanguageType` field.

**Possible Solution**

Include the same languages supported in the `Accept-Language` header, that is, all languages as specified by [RFC 7231 5.3.5](https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.5). See [this SO answer](https://stackoverflow.com/a/37062190/3212948) for an explanation of the values allowed in the `Accept-Language`

**Additional context**

I'm working on GNU social and in v2 we had and plan to continuing having in v3 support for different languages like `pt_PT` and `pt_BR`, based on the Accept-Language header and on the user settings

**Comment by someonewithpc** [comment]
Partially related to #41455

**Comment by ro0NL** [comment]
IIUC for this usecase a "locale" should be used instead.

> A language tag (which is sometimes referred to as a "locale identifier"). 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

Symfony provides LocaleType as such.

**Comment by someonewithpc** [comment]
@ro0NL My bad, I didn't know about that class. Thanks a lot for the help. Perhaps something in the doc is missing?

**Comment by ro0NL** [comment]
We cannot rename Accept-Language to Accept-Locale :)

We follow language codes per ISO-639
