### ISSUE TITLE
"(...) has no container set, did you forget to define it as a service subscriber?"

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#42383]
**Symfony version(s) affected**: latest

**Description**

When the namespace of a controller is changed to any other name, the following error appears:

Uncaught PHP Exception LogicException: ""New\Controller\Namespace" has no container set, did you forget to define it as a service subscriber?

This message is absolutely meaningless for most developers. Search engines or Symphony docs don't return anything meaningful about what would a "container set" or a "service subscriber" be or why I need this. Also, the actual error seems to be that Symfony demands a specific namespacing convention, but it also does not describe what this convention would be in the docs. I can only get things to work if the namespace describes the whole path to the file, but I don't even know why, and nothing in the docs address this.

At the very least, the error message should be improved.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by fd6130** [comment]
Since that message related with services, perhaps you just need to modify the`App\Controller` in `services.yaml` ?

```yaml

   App\Controller\: # change this to your new namespace
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

```

For some extra info: https://symfony.com/doc/current/service_container.html#multiple-service-definitions-using-the-same-namespace

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
