### ISSUE TITLE
var dumper error:

### ISSUE THREAD

**Issue by remco-pc** [symfony/symfony#42393]
<br />
<b>Fatal error</b>:  Class symfony\component\vardumper\caster\conststub wasn't preloaded in <b>/mnt/c/Repository/.../vendor/symfony/var-dumper/Caster/ConstStub.php</b> on line <b>21</b><br />

**Comment by derrabus** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* GitHub Discussions: https://github.com/symfony/symfony/discussions
* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
