### ISSUE TITLE
[Cache] Async cache recomputing

### ISSUE THREAD

**Issue by next-sentence** [symfony/symfony#42408]
**Symfony version(s) affected**: 5.2 or above

**Description**
[this feature](https://symfony.com/blog/new-in-symfony-5-2-async-cache-recomputing) doesn't work with symfony debug-pack
**How to reproduce**

- clone the [demo](https://github.com/nicolas-grekas/cache-bus) repository
- remove composer.lock
- run composer install
- configure messenger routing dns
- start symfony server
- open http://localhost/demo

at this point it should work as expected, but if you add symfony debug-pack
`composer require debug`

you will get an exception like this

`Attempted to call an undefined method named "setCallbackWrapper" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".`

**Possible Solution**
maybe add  `\Symfony\Component\Cache\Traits\ContractsTrait` in `\Symfony\Component\Cache\Adapter\TraceableAdapter` also?

**Comment by next-sentence** [comment]
@nicolas-grekas

**Comment by nicolas-grekas** [comment]
Thanks for the issue. See #42445 for the fix.
