### ISSUE TITLE
[Mailer] Signing email is not working with templated email

### ISSUE THREAD

**Issue by kriskoch** [symfony/symfony#42407]
Hello, 
I am using the templated Email, and if I try to sign the message with DKIM, I receive the error 'A message must have a text or an HTML part or attachments.'

It seems like BodyRenderer isnt called until you send. Is there an event listener or something I need to tap into to sign it after the bodyrenderer is called?
If so then the documentation should be updated as I dont see anything on there.

Here is an example: 
```php
    $email = (new TemplatedEmail())
            ->to(new Address('example@example.org', 'Mr. Example' ))
            ->from(new Address('example@example.org', 'Ms. Example'))
            ->subject('Test Signed Email')
            ->htmlTemplate('email-templates/test.html.twig');


        $signer = new DkimSigner('file://'.$keyFile, $domain, $selector);
        $signed = $signer->sign($email);
        $mailer->send($signed);
```

**Comment by OskarStark** [comment]
Is this the same as https://github.com/symfony/symfony/issues/41935 or https://github.com/symfony/symfony/issues/40131 ?

**Comment by kriskoch** [comment]
No, this would be different. The issue for this one is that there is an event listener that renders the template. This is called at some point during the $mailer->send().  SO at the point that you $signer->sign the body has not been rendered and is empty. 
I think the $signer->sign method needs to trigger the event to render,  or the render function needs to trigger an event we can hook into to sign it.

It looks like it might be the same as https://github.com/symfony/symfony/issues/39354

**Comment by OskarStark** [comment]
friendly ping @sstok

**Comment by sstok** [comment]
I have no experience with DKIM, but does #42416 fix this issue? and possible the other ones mentioned.

**Comment by kriskoch** [comment]
> I have no experience with DKIM, but does #42416 fix this issue? and possible the other ones mentioned.

No, that resolved a different issue. I made a comment over here https://github.com/symfony/symfony/issues/39354#issuecomment-894379296 as a potential solution.

I ended up using a different solutuon - 
 I used the base Email class set ->html to ($twig->render), which passes DKIM but then I lose access to the special 'email' variable.  So I copied the WrappedTemplatedEmail class, changed the type hint on the 2nd paramterer in the constructor to be Email instead of TemplatedEmail. Then pass into the template the email variable as new WrappedTemplatedEmail($twig, $email), so I could still use that functionality.

**Comment by David-51** [comment]
i had the same problem. Impossible to send mail with TemplatedEmail using DkimSigner
Thanks to @kriskoch , his solution work fine.
Im on symfony 6.0

This is my example code :
```php
class SendMailController extends AbstractController
{
    #[Route('/mail', name: 'send_mail')]

    public function index(MailerInterface $mailer, Environment $twig): Response
    {                
        $email = (new TemplatedEmail())        
            ->from(Address::create('firstname NAME <from@example.fr>'))   
            ->to(Address::create('firstname NAME <tomail@example.com>'))
            ->replyTo('from@example.com')
            ->subject('My awesome Mail');   
            
        $html = $this->render('mail.html.twig',[
                        'email' => new WrappedTemplatedEmail($twig, $email),                        
                        ])
                    ->getContent();
        $email->html($html);
                            
        $pathToPrivateKey = 'file://'.__DIR__.'/private.pem';    
        $signer = new DkimSigner($pathToPrivateKey, 'domain.fr', 'sf');
    
       $signedEmail = $signer->sign($email);       
       $mailer->send($signedEmail);
    
        return new Response('E-mail sent ...');        
    }
}
```

**Comment by twisted1919** [comment]
Sorry to bump this, but https://github.com/symfony/symfony/issues/40131 is still an issue and it's been closed when it should not.

**Comment by nicolas-grekas** [comment]
Bumping is not enough apparently.
Could anyone investigate the root of the issue?

**Comment by BrokenSourceCode** [comment]
I guess this issue and #40131 are related, but absolutely not sure. The problem seems to occur when there are multiple parts in the email (`Content-Type: multipart/alternative;`). With one part, all is working perfectly.

If anyone wants to investigate to find the problem, it seems that [this workaround](https://github.com/symfony/symfony/issues/40131#issuecomment-776114555) works great, for some reason.

```php
// It doesn't work.
$signedEmail = $signer->sign($email);
```

```php
// It works again.
$emailForSign = new Message($email->getPreparedHeaders(), $email->getBody());
$signedEmail = $signer->sign($emailForSign);
```

**Comment by xgrimaldi** [comment]
Hello everyone,
I've experienced the same thing on Symfony 5.4.6 today.

## PROBLEM ENCOUNTERED
I struggled today on the same kind of behavior. I couldn't make DKIM test pass because i was using html() & text() on Email object.
When i decided to analyse through some DKIM email validator website, i've got this message : "DKIM : failed. Body has been altered"

## SOLUTION  
- The above workaround work perfectly : https://github.com/symfony/symfony/issues/42407#issuecomment-1047164220 
- Full example at the bottom of this comment.

## WHAT'S NEXT ?!
- It should be at least indicated in the Symfony's documentation of Mailer, on DKIM part (as a note for example), since it's not working otherwise.

## FULL EXAMPLE
Here is a full example that is working on my side with html, text and embedding image in email:
```
   // Récupération du chemin du logo
    $logoPath = '<myLogoPath>'
    // Création de l'email
    $email = (new Email())
    ->from(new Address($_ENV['MAIL_SENDER'], 'CustomName'))
    ->to($data->getEmail())
    ->subject('TITLE EMAIL')
    ->embedFromPath($logoPath, 'logo')
    ->text($this->twig->render(
        '<path/to/text.twig>',
        [
            'user' => $userDataObject,
        ]
    ))
    ->html($this->twig->render(
        '<path/to/html.twig>',
        [
            'user' => $data,
        ]
    ));

    // DKIM Signer
    $key_path = join(DIRECTORY_SEPARATOR, array($this->projectDir,'<myPrivateKey>.pem')); 
    $signer = new DkimSigner('file://' . $key_path, '<myDomainName>', '<mySelector>');
    $emailForSign  = new Message($email->getPreparedHeaders(), $email->getBody());
    $signedEmail = $signer->sign($emailForSign);

    // Sending
    if (0 === $this->mailer->send($signedEmail)) {
        $this->logger->error('Unable to send mail');
    }
```

**Comment by ghost** [comment]
I suggested a PR to fix the issue: https://github.com/symfony/symfony/pull/46863.
