### ISSUE TITLE
[Console] Support with PHP8.1

### ISSUE THREAD

**Issue by Jeckerson** [symfony/symfony#42415]
**Description**
By using `symfony/console` package inside Zephir, we are having fatal error:
> Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/symfony/console/Helper/HelperSet.php:94

**Example**
Code example can be found here
https://github.com/zephir-lang/zephir/blob/7315f84929e04a0f52b276edd65cfd3673327f4a/Library/Console/Command/FullCleanCommand.php#L39

**Comment by wouterj** [comment]
Thanks for the report! This is however already fixed by #42260 . Please use dev versions when testing dev PHP versions.
