### ISSUE TITLE
Use universal interface for Redis, or remove @internal from `RedisProxy`

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#42428]
**Description**

At this moment all of Symfony Redis adapters/handlers tightly bound to `\Redis | \RedisArray | \RedisCluster | RedisProxy | RedisClusterProxy | \Predis\ClientInterface`

```php
Symfony\Component\Lock\Store\RedisStore
Symfony\Component\Cache\Adapter\RedisAdapter
Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
```

I want to log/profile redis commands (phpredis), but there is no right way to use decorated Redis class with Symfony components.

- [ ]  Attempt 1 - Simple decoration - won't bypass instanceof checks inside Symfony classes. 
```php
/** @mixin Redis */
class RedisClient
{
    public function __construct(
        private Redis $redis;
        private LoggerInterface $logger;
    ) {}

    public function call(string $name, array $arguments)
    {
            $this->logger->debug('...');
            return $this->redis->{$name}(...$arguments);
    }
}

new Symfony\Component\Lock\Store\RedisStore(new RedisClient(...)); // throws InvalidArgumentException
```

- [ ]  Attempt 2 - extend `\Redis` 
This requires to override all Redis methods and this is ridiculous. Look at this 1500+ lines example:
https://github.com/snc/SncRedisBundle/blob/d7718cd75166bb256380cf428cbde54402be149e/Client/Phpredis/Client.php#L189

- [ ]  Attempt 3 (dirty) - extend `Symfony\Component\Cache\Traits\RedisProxy`.
This works, but `RedisProxy` marked as `@internal` so you will get deprecation errors. And since it's internal - there is no guarantee that this class will not be silently changed. 

- [ ] Attempt 4 (dirty+monkeypatching) - copy `RedisProxy` to `src`. Configure `autoload` and `exclude-from-classmap` in composer.json. But let's leave monkeypatching for javascript community!

**Final thoughts**
Please either remove `@internal` from `Symfony\Component\Cache\Traits\RedisProxy` or add another way to solve this problem

**Comment by ro0NL** [comment]
i also concluded `RedisProxy` was our main extension point, see https://github.com/symfony/symfony/pull/42087

im :+1: given `RedisProxy` symbol seems gerally more useful than `Redis`

**Comment by sirian** [comment]
@nicolas-grekas https://github.com/symfony/symfony/pull/42087#issuecomment-879017121
> We can keep the symbol internal as you don't reference it directly.

You wrong. At this moment `RedisProxy` is the only one way to use decorated Redis with Symfony components like
```php
Symfony\Component\Lock\Store\RedisStore
Symfony\Component\Cache\Adapter\RedisAdapter
Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
```

because all of them has strict instanceof checks like
```php
if (
            !$redis instanceof \Redis &&
            !$redis instanceof \RedisArray &&
            !$redis instanceof \RedisCluster &&
            !$redis instanceof \Predis\ClientInterface &&
            !$redis instanceof RedisProxy &&
            !$redis instanceof RedisClusterProxy
        ) {
            throw new \InvalidArgumentException(sprintf('"%s()" expects parameter 1 to be Redis, RedisArray, RedisCluster or Predis\ClientInterface, "%s" given.', __METHOD__, get_debug_type($redis)));
        }
```

**Comment by ro0NL** [comment]
@nicolas-grekas pls reconsider :) im depending on it for a [`RedisClientInterface`](https://github.com/palicao/phpRedisTimeSeries/blob/master/src/Client/RedisClientInterface.php) implementation.

**Comment by nicolas-grekas** [comment]
I'm sorry but as I explained in #42087 I don't have a solution better than telling you to extend `RedisProxy` despite it being `@internal`. Or to find another way to add profiling instrumentation on your side.

**Comment by ro0NL** [comment]
Now im wondering, if good old `lazy: true` on the service definition (with proxy-manager) would work actually :sweat_smile:

**Comment by nicolas-grekas** [comment]
Could be! :)
Closing meanwhile.
