### ISSUE TITLE
Multi-Node support for amqp in symfony messenger

### ISSUE THREAD

**Issue by poojabaghelsendinblue** [symfony/symfony#42456]
**Description**
Multi-Node support for amqp in symfony messenger

**Example**
 may be we can add support here for handling multiple dsn connection https://github.com/symfony/symfony/blob/e34cd7dd2c6d0b30d24cad443b8f964daa841d71/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L485

**Comment by arnowest** [comment]
Symfony Messenger supports multiple DSN by setting up different transports as described here:
https://symfony.com/doc/current/messenger.html#transport-configuration

**Comment by poojabaghelsendinblue** [comment]
Thanks  for answering @arnowest .
Here I am asking for amqp multi node support while creating connection.
Please tell me If you have any question 🔢

**Comment by arnowest** [comment]
Can you provide some more information on what you want to achieve? If you want to route messages to different servers you can use the transports. If you're using a cluster setup with RabbitMQ it doesn't matter which node you connect to: https://www.rabbitmq.com/clustering.html#peer-equality

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
