### ISSUE TITLE
[uid] UUIDs stored as CHAR(36)

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#42462]
I'm taking a look at the native UID component: https://symfony.com/doc/current/components/uid.html

In "Storing UUIDs in Databases", it shows only one way to do that, by using `@ORM\Column(type="uuid")`, which translates to: `CHAR(36) NOT NULL COMMENT '(DC2Type:uuid)';`

It goes without saying that this is not the proper way to store UUIDs, a BINARY(16) should be used instead, this method uses 36 bytes instead of 16 (+125%), it's highly ineffective.

At least an alternative type should be provided (like "uuid_binary") so the user can choose which one to use.

**Comment by mbabker** [comment]
It already does this.

The [UidType SQL declaration](https://github.com/symfony/symfony/blob/v5.3.6/src/Symfony/Bridge/Doctrine/Types/AbstractUidType.php#L26-L36) is based on whether the DBAL platform has a native GUID type.  If it does, then the column uses whatever the DBAL platform configures (which is [by default](https://github.com/doctrine/dbal/blob/2.13.2/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L328-L334) a `CHAR(36)` field).  If it doesn't, then a `BINARY(16)` field is used.

**Comment by fmonts** [comment]
> It already does this.
> 
> The [UidType SQL declaration](https://github.com/symfony/symfony/blob/v5.3.6/src/Symfony/Bridge/Doctrine/Types/AbstractUidType.php#L26-L36) is based on whether the DBAL platform has a native GUID type. If it does, then the column uses whatever the DBAL platform configures (which is [by default](https://github.com/doctrine/dbal/blob/2.13.2/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L328-L334) a `CHAR(36)` field). If it doesn't, then a `BINARY(16)` field is used.

Sorry but I'm trying to understand the sense.
"If the platform has native GUID, then use a CHAR(36)"? 

The platform I'm using is MySQL 8.0, it hasn't native GUID type but it has BINARY. In my case it creates a char(36) field. I think something is wrong here...

$this->getDoctrine()->getConnection()->getDatabasePlatform()->hasNativeGuidType()
returns false

**Comment by fmonts** [comment]
Ok so it looks like a Doctrine DBAL issue, not a Symfony one

**Comment by lyrixx** [comment]
Hello,

Something is strange here. according to [the code](https://github.com/symfony/symfony/blob/v5.3.6/src/Symfony/Bridge/Doctrine/Types/AbstractUidType.php#L26-L36) if the platform does not support native UUID, it should use a binary column of length 16.

It looks like you are using the uuid type from [doctrine](https://github.com/doctrine/dbal/blob/e974d4deca8c430d9eba0975f441538145a5a8f1/src/Platforms/AbstractPlatform.php#L272-L278), and not the one from Symfony.

Can you double check ?

**Comment by fmonts** [comment]
I'm sorry, I had another library (Ramsey/uuid) that was creating conflict (even if the type was not registered in doctrine.yaml). Sorry again

**Comment by qdequippe** [comment]
Could it be interesting that both `uuid` and `uuid_binary` will be available in Symfony? 

I am open to make a PR about this if it makes sense :)
