### ISSUE TITLE
$request->query->get() can return array, but PHPDoc doesn't include array

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#42478]
**Symfony version(s) affected**:  5.3.6

**Description**
According to the documentation here:
https://symfony.com/doc/current/components/http_foundation.html#accessing-request-data

````
// the query string is '?foo[bar]=baz'

$request->query->get('foo');
// returns ['bar' => 'baz']
````
$request->query->get() can return arrays, but PHPDoc in InputBag for method get() says

````
@return string|int|float|bool|null
````

**Possible Solution**
In my assumption it should be save to add array to the return annotation?
If so, I'm happy to prepare a pull request.

**Comment by wouterj** [comment]
Hi! It seems like the docs are wrong here. In Symfony 5.1, the `InputBag` was introduced to avoid having the array return type: #34363 (as that makes it quite easy to break applications by adding `[]` to the URL).

Are you willing to submit a fix for the docs? :)

**Comment by ThomasTr** [comment]
Ah ok, thanks for the hint. Will head over to the docs :)
