### ISSUE TITLE
Translation fallback order error

### ISSUE THREAD

**Issue by mboeck001** [symfony/symfony#42480]
### Discussed in https://github.com/symfony/symfony/discussions/42479

<div type='discussions-op-text'>

<sup>Originally posted by **mboeck001** August 11, 2021</sup>
Hi!

There seems to be a bug in Symfony\Component\Translation computing the fallbacks in method computeFallbackLocales. Perhapes someone can confirm or correct me?

- We use a valid ICU language selector e.g de_AT_VIENNA and we have a message file for de, de_AT and de_AT_VIENNA containing a valid translation
- locale is de_AT_VIENNA
- the lookup ID is missing in de_AT_VIENNA, so fallback is triggered
- the fallback is computed in the order first de, then de_AT, what is imo wrong, it has to be de_AT followed by de corresponding to ICU usage

I would just change the array_unshift to a normal append operation

Did I miss something? This seams to be since a long time ...

changed line arround line 441  of Translator.php to:

            if (null !== $locale) {
                // m.boeck: wrong order in fallback - bug in symfony
                $locales[] = $locale;
            }

removing the array_unshift operation. For me it works.

Thats also in the 4.x branch.

Martin</div>

**Comment by ro0NL** [comment]
this looks odd. Can you invalidate this test? https://github.com/symfony/symfony/blob/2e10dd502d7d328d288c5921e78aec5470887346/src/Symfony/Component/Translation/Tests/TranslatorTest.php#L300

my guess is nobody noticed yet :)

**Comment by mboeck001** [comment]
this test is partly correct, but is missing the point a translation non-existing primary and is existing in all subsequent parts. I would rewrite this test by:

    public function testTransWithIcuVariantFallbackLocale()
    {
        $translator = new Translator('en_GB_scouse');
        $translator->addLoader('array', new ArrayLoader());
        $translator->addResource('array', ['foo' => 'foofoo'], 'en_GB_scouse');
        $translator->addResource('array', ['bar' => 'foobar'], 'en_GB');
        $translator->addResource('array', ['baz' => 'foobaz'], 'en_001');
        $translator->addResource('array', ['qux' => 'fooqux'], 'en');
        // added
        $translator->addResource('array', ['fb' => 'foofbgb'], 'en_GB');
        $translator->addResource('array', ['fb' => 'foofb001'], 'en_001');
        $translator->addResource('array', ['fb' => 'foofben'], 'en');**
        // --
        $this->assertSame('foofoo', $translator->trans('foo'));
        $this->assertSame('foobar', $translator->trans('bar'));
        $this->assertSame('foobaz', $translator->trans('baz'));
        $this->assertSame('fooqux', $translator->trans('qux'));
        // added
        $this->assertSame('fb', $translator->trans('foofbgb'));
        // --
    }

**Comment by shyim** [comment]
Hey,

after this change, we have an issue with our application and we don't know if that new order is correct 🤔 

That's like our current code:

```php
$translator = new Translator('en_GB');
$translator->setFallbackLocales(['en_GB', 'en']);
$catalogue = $translator->getCatalogue('en_GB');

$this->assertEquals('en', $catalogue->getFallbackCatalogue()->getLocale());
```

After this issue en_001 (taken from ICU) is preferred over the configured fallback locales. I am not very experienced with the translation stuff and ICU. Is that correct so? I would expect that the ICU stuff is appended to the locales **at end** and not to the beginning.
