### ISSUE TITLE
symfony/console ^5.3.0 doesn`t work with php 7.x

### ISSUE THREAD

**Issue by bavprimary** [symfony/symfony#42498]
symfony/console:^5.3.0 

**Description**
After updating symfony\console from v5.2.6 to v5.3.6 in my project I cought php error:
"<b>Parse error</b>:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in <b>/var/www/shop-2.0/vendor/symfony/console/Attribute/AsCommand.php</b> on line <b>21"
We are using php 7.4 and scripts preloading in our project. This error I cought when I try preloading vendor scripts. 
 I thing declaring properties in the constructor is feature of php8, and doesn`t work in php 7.x.

**How to reproduce**
Install symfony\console ^5.3.0, on project with php 7.x

**Possible Solution**
Set right dependencies in composer.json

**Comment by derrabus** [comment]
`AsCommand` is a class that is not supposed to be used on PHP 7. Please provide steps to reproduce your problem.

**Comment by bavprimary** [comment]
> is a class that is not supposed to be used on PHP 7. Please provide steps to reproduce your problem.

Hello, @derrabus, we have php script which recursive preloading some directories of vendor (using opcache_compile_file()). Most likely I need to ignore this file in my preloading flow.

**Comment by nicolas-grekas** [comment]
Absolutely!

**Comment by bavprimary** [comment]
@derrabus @nicolas-grekas  thanks!

**Comment by derrabus** [comment]
Also, preloading the entire vendor folder is probably not a good idea. You will continue to hit issues like this one and also preload way too much code that you'll never use.

Related: https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading
