### ISSUE TITLE
Use attributes already formatted in form_*

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#42616]
Hi,

It would be cool to use attributes that are already formatted.

**Description**
For instance use `stimulus_action` and `stimulus_target` in `form_*` is not possible.

**Example**
Currently I have this:
```twig
{{ form_widget(form.email, {attr: {class: 'field', 'data-action': 'form#change', 'data-form-target': 'field'}}) }}
```

Why not do this:
```twig
{{ form_widget(form.email, {attr: {class: 'field'}, attributes: stimulus_action('form', 'change') ~ stimulus_target('form', 'field') }) }}
```

**Comment by xabbuh** [comment]
As someone who is not familiar with Stimulus can you explain to me what those `stimulus_action()` and `stimulus_target()` functions return and how they would be used outside the Symfony form theme context?

**Comment by seb-jean** [comment]
> As someone who is not familiar with Stimulus can you explain to me what those `stimulus_action()` and `stimulus_target()` functions return and how they would be used outside the Symfony form theme context?

`stimulus_action('form', 'change')` render `data-action="form#change"`
`stimulus_target('form', 'field')` render `data-form-target="field"`

Outside the Symfony form theme context:

**stimulus_action**

```html
<div {{ stimulus_action('controller', 'method') }}>Hello</div>
<div {{ stimulus_action('controller', 'method', 'click') }}>Hello</div>

<!-- would render -->
<div data-action="controller#method">Hello</div>
<div data-action="click->controller#method">Hello</div>
```

**stimulus_target**

```html
<div {{ stimulus_target('controller', 'a-target') }}>Hello</div>
<div {{ stimulus_target('controller', 'a-target second-target') }}>Hello</div>

<!-- would render -->
<div data-controller-target="a-target">Hello</div>
<div data-controller-target="a-target second-target">Hello</div>
```

Exemples from: https://github.com/symfony/webpack-encore-bundle#stimulus--symfony-ux-helper

**Comment by k0d3r1s** [comment]
form_widget has nothing to do with stimulus as it is a different bundle. i don't think this could TwigBridge feature, but probably encore bundle or some ux pack feature cause these stimulus_ functions are part of those.  
for now, if you need, you can write your own twig extension to use this

**Comment by seb-jean** [comment]
> form_widget has nothing to do with stimulus as it is a different bundle. i don't think this could TwigBridge feature, but probably encore bundle or some ux pack feature cause these stimulus_ functions are part of those.
> for now, if you need, you can write your own twig extension to use this

I was talking about stimulus here but it could be something else that generates attributes already formatted:
`my-attr="my-value"`

Stimulus was an example :)

**Comment by seb-jean** [comment]
The idea is to be able to do this:

```twig
{{ form_widget(form.email, {attr: {class: 'field'}, attributes: 'my-attr="my-value" my-attr_2="my-value_2"' }) }}
```

`my-attr="my-value" my-attr_2="my-value_2"'` are attributes already formatted
