### ISSUE TITLE
Cannot autowire service when load Service Configuration inside a Bundle

### ISSUE THREAD

**Issue by huuthinh47** [symfony/symfony#42612]
**I load my service config in bundle like this**:
```php
class AbcSalesOrderExtension extends Extension
{
    /**
     * {@inheritDoc}
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.yaml');
    }
}
```

**Service function**
```php
class ClpProvider
{
    public function __construct(Client $elasticaClient, string $clpIndex, string $clpType)
    {
        $this->elasticaClient = $elasticaClient;
        $this->clpIndex = $clpIndex;
        $this->clpType = $clpType;
    }
```

**My service config**:
```php
Abc\SalesOrderBundle\Helper\ClpProvider:
        arguments:
            $elasticaClient: '@elastica_client'
            $clpIndex: '%elasticsearch.clp.index.name%'
            $clpType: '%elasticsearch.clp.type.revenue%'
```

It works when i put above config into **config/services.yaml** but i get the following error when i put above config into **src/Abc/SalesOrderBundle/Resources/config/services.yaml**

```html
Cannot autowire service "Abc\SalesOrderBundle\Helper\ClpProvider": argument "$clpIndex" of method "__construct()" is type-hinted "string", you should configure its value explicitly.
```
How to resolve this error ? I use PHP 8.0.8 and Symfony 5.3.
Thank all,

**Comment by ro0NL** [comment]
can you create a bug reproducer? https://symfony.com/doc/current/contributing/code/reproducer.html

otherwise it should be discussed IMHO =>  https://github.com/symfony/symfony/discussions

**Comment by huuthinh47** [comment]
hi @ro0NL ,
i have created a repository for this bug. It is [https://github.com/huuthinh47/symfony_issue_42612](https://github.com/huuthinh47/symfony_issue_42612)
i think i did something wrong, but i don't know where is it. 
Could you help me to have a look at it ?
Thank you

**Comment by HypeMC** [comment]
@huuthinh47 The problem is in `config/services.yaml` where you have:

```yaml
    App\:
        resource: '../src/Abc/*'
        exclude:
            - '../src/Abc/**Bundle/{DependencyInjection,Model,Entity,Migrations,Tests,Form}'
```

This will import `ClpProvider` with no arguments, so when `src/Abc/JobBundle/Resources/config/services.yaml` gets loaded the service already exists. Try excluding `JobBundle` from your main services file.

**Comment by huuthinh47** [comment]
@HypeMC Yes, you are right. i have to add **Helper** folder into **exclude** and it works.
Thank you so so much,
Thank @ro0NL
