### ISSUE TITLE
SF6 - toolbar debug

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#42652]
**Symfony version(s) affected**: 6.0

**Description**
Hi,

After installing the security bundle, the debug bar => bug! To summarize, it is no longer functional and if we remove the bundle, it becomes functional again.

**How to reproduce**
Before, install security bundle

![sfbar](https://user-images.githubusercontent.com/89082510/130178837-b9698326-3af5-4dd8-89d3-1ba6e69beefe.png)

After a ```composer req security```

![sfnobar](https://user-images.githubusercontent.com/89082510/130178911-49429220-d6eb-47fc-8ead-62676b8fad23.png)

**Possible Solution**
I don't no ... No security ? XD 
remove : composer rem security
![sfbar](https://user-images.githubusercontent.com/89082510/130178837-b9698326-3af5-4dd8-89d3-1ba6e69beefe.png)
**Additional context**
Composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=8.0.2",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.13",
        "doctrine/doctrine-bundle": "^2.4",
        "doctrine/orm": "^2.9",
        "predis/predis": "^1.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "6.0.*",
        "symfony/console": "6.0.*",
        "symfony/dotenv": "6.0.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "6.0.*",
        "symfony/framework-bundle": "6.0.*",
        "symfony/mailer": "6.0.*",
        "symfony/notifier": "6.0.*",
        "symfony/runtime": "6.0.*",
        "symfony/stopwatch": "6.0.x-dev",
        "symfony/translation": "6.0.*",
        "symfony/twig-bundle": "6.0.*",
        "symfony/uid": "6.0.*",
        "symfony/validator": "6.0.*",
        "symfony/web-profiler-bundle": "6.0.x-dev",
        "symfony/yaml": "6.0.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.0.*"
        }
    },
    "require-dev": {
        "phpstan/phpstan-doctrine": "^0.12.43",
        "phpstan/phpstan-symfony": "^0.12.42",
        "phpunit/phpunit": "^9.5",
        "symfony/debug-bundle": "6.0.*"
    }
}
```

**Comment by ghost** [comment]
Last note, impossible install profiler
![consolenoprofiler](https://user-images.githubusercontent.com/89082510/130181060-00cb2696-a0b6-4b3a-99c4-c5816b0f4fc5.png)

On 5.4, I do not encounter any of these problems.

**Comment by sstok** [comment]
You should be able to see the actual profiler-url in the development console (Network) of your browser. 
Which should give more information what's wrong.

Does this happen with a clean new Symfony installation?

**Comment by ghost** [comment]
Hi,

YES this happens with a clean install, even using symfony's --full function the bug is present. So, I organized my project differently, I will start from the base on 5.4, the debug bar still has a problem!
The timing in ```ms == n/a``` (Look first screen shoot left bottom) no longer calculates anything, we only have the branch time. Moreover when we click on it we come across an error, you have to modify the code, line 112 of LoggerDataCollector is apparently not very appreciated:

```
'timestamp' => $rawLogData['timestamp_rfc3339']->getValue(),
```
For fix suggestion
```
'timestamp' => $rawLogData['timestamp']->getValue(),
```


The funny thing is that now on 5.4, the bar is displayed when there is a problem but if the code is 200 then it is not displayed ...

Edit Add:

I stopped using version 6, because with each annotation modification etc ... I found myself with a server error, the connection was not successful ... I had to do a ```c:c``` to get the site. I searched all the corners etc ... I never had this before ...

**Comment by fabpot** [comment]
Can you confirm that #42600 fixes your issue?

**Comment by ghost** [comment]
Hi Fabien,

I do various tests and I come back ... For me intl is active by default because I use it for intl-icu in translations.

**Comment by ghost** [comment]
I did the tests on 5.2 - 5.3 - 5.4 - 6.0.
I did not screen 5.2 because it was to check the last point which is the same for everyone ...
After a new installation, add:
```
composer req apache-pack
composer req debug-bundle profiler --dev
```
![sf53](https://user-images.githubusercontent.com/89082510/130468805-76e39b91-a9a4-4020-871a-9096c986319c.jpg)
![sf54](https://user-images.githubusercontent.com/89082510/130468829-5ca7312a-1b35-4921-9090-556c849d6e13.jpg)
![sf60](https://user-images.githubusercontent.com/89082510/130468857-063cb270-53c6-475c-81bb-585f73098f12.jpg)

Now add : 
```
composer req security
```

![sf53sec](https://user-images.githubusercontent.com/89082510/130469418-c317a0c5-bfd8-45ed-ba64-327bdc89b4d1.jpg)
![sf54sec](https://user-images.githubusercontent.com/89082510/130469436-5716637b-e3a2-4bcf-afd0-e867e3d77d3d.jpg)
![sf60sec](https://user-images.githubusercontent.com/89082510/130469467-a4001ac7-dc36-465d-ba63-71da516e0d47.jpg)

Now MS : 
![sf53ms](https://user-images.githubusercontent.com/89082510/130469717-600ba525-857f-4b2b-a4ad-aaca4daf0004.jpg)
![sf54ms](https://user-images.githubusercontent.com/89082510/130469739-c3726575-931d-45ec-b4ec-84c9923f0f75.jpg)
### SF60 HS

Now add : 
```
composer req annotation
```

Add a little make controller with template : 
```
    #[Route('/', name: 'home')]
    public function index(): Response
    {
        //$test = $this->getParameter('app');
        return $this->render('home/index.html.twig', [
            'controller_name' => 'Youkoulélé',
        ]);
    }
```

On this last point and for all the versions, if there is no error the bar disappears, I have to make a bogus link to force an error to obtain the bar. With and without security-bundle.

![sf53contprof](https://user-images.githubusercontent.com/89082510/130470895-9b5bc6a9-aeb7-47c4-b3a9-e4cfce8a06e1.jpg)
![sf54contprof](https://user-images.githubusercontent.com/89082510/130470916-d342c5f8-86b8-4440-926d-1234ec6e2860.jpg)
![sf60contprof](https://user-images.githubusercontent.com/89082510/130470936-1a8bd2c5-3862-4b16-b13a-8dc78bc648b6.jpg)

Add my php config
[PHP 8.0.7 - phpinfo().html.zip](https://github.com/symfony/symfony/files/7032927/PHP.8.0.7.-.phpinfo.html.zip)

**Comment by ghost** [comment]
Add note: 
Although the bar is not displayed, the profiler information for successful requests can be found in the cache.

**Comment by ghost** [comment]
@fabpot Sorry for my question if it looks stupid ... I am the only one with this problem or did you get the same bug?

**Comment by carlcasbolt** [comment]
@Bazarcor - does that PR fix your issue as it does for me https://github.com/symfony/symfony/pull/42755
