### ISSUE TITLE
symfony/maker-bundle → "Your requirements could not be resolved to an installable set of packages" @ Symfony 6.0

### ISSUE THREAD

**Issue by mehov** [symfony/symfony#42669]
**Symfony version(s) affected**: 6.0

**Description**

```
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/maker-bundle[dev-main, v1.30.0, ..., v1.33.0] require symfony/config ^4.0|^5.0 -> found symfony/config[v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - symfony/maker-bundle[1.0.0, ..., v1.22.0] require php ^7.1.3 -> your php version (8.0.9) does not satisfy that requirement.
    - symfony/maker-bundle[v1.0.1, ..., v1.16.0] require php ^7.0.8 -> your php version (8.0.9) does not satisfy that requirement.
    - symfony/maker-bundle[v1.23.0, ..., v1.29.2] require symfony/config ^3.4|^4.0|^5.0 -> found symfony/config[v3.4.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - symfony/maker-bundle 1.0.x-dev is an alias of symfony/maker-bundle dev-main and thus requires it to be installed too.
    - Root composer.json requires symfony/maker-bundle ^1.0 -> satisfiable by symfony/maker-bundle[1.0.0, ..., v1.33.0].
```

**How to reproduce**

Follow [*Installing & Setting up the Symfony Framework* → *Creating Symfony Applications*](https://github.com/symfony/symfony-docs/blob/89c3b6bc4f5017c666f79fac4a71a733300e1a66/setup.rst#creating-symfony-applications) and run:

```
composer create-project symfony/website-skeleton:"6.0.x@dev" exampleproject
```

**Additional context**

- Debian 10.10
- PHP 8.0.9 (php-fpm)
- `composer.json`:

        {
            "name": "symfony/website-skeleton",
            "type": "project",
            "license": "MIT",
            "description": "A skeleton to start a new Symfony website",
            "minimum-stability": "dev",
            "prefer-stable": true,
            "require": {
                "php": ">=8.0.2",
                "ext-ctype": "*",
                "ext-iconv": "*",
                "sensio/framework-extra-bundle": "^6.1",
                "symfony/asset": "*",
                "symfony/console": "*",
                "symfony/dotenv": "*",
                "symfony/expression-language": "*",
                "symfony/flex": "^1.3.1",
                "symfony/form": "*",
                "symfony/framework-bundle": "*",
                "symfony/http-client": "*",
                "symfony/intl": "*",
                "symfony/mailer": "*",
                "symfony/mime": "*",
                "symfony/monolog-bundle": "^3.1",
                "symfony/notifier": "*",
                "symfony/orm-pack": "*",
                "symfony/process": "*",
                "symfony/runtime": "*",
                "symfony/security-bundle": "*",
                "symfony/serializer-pack": "*",
                "symfony/string": "*",
                "symfony/translation": "*",
                "symfony/twig-pack": "*",
                "symfony/validator": "*",
                "symfony/web-link": "*",
                "symfony/yaml": "*"
            },
            "require-dev": {
                "symfony/debug-pack": "*",
                "symfony/maker-bundle": "^1.0",
                "symfony/profiler-pack": "*",
                "symfony/test-pack": "*"
            },
            "config": {
                "optimize-autoloader": true,
                "preferred-install": {
                    "*": "dist"
                },
                "sort-packages": true
            },
            "autoload": {
                "psr-4": {
                    "App\\": "src/"
                }
            },
            "autoload-dev": {
                "psr-4": {
                    "App\\Tests\\": "tests/"
                }
            },
            "replace": {
                "symfony/polyfill-ctype": "*",
                "symfony/polyfill-iconv": "*",
                "symfony/polyfill-php72": "*"
            },
            "scripts": {
                "auto-scripts": [
                ],
                "post-install-cmd": [
                    "@auto-scripts"
                ],
                "post-update-cmd": [
                    "@auto-scripts"
                ]
            },
            "conflict": {
                "symfony/symfony": "*"
            },
            "extra": {
                "symfony": {
                    "allow-contrib": false,
                    "require": "6.0.*"
                }
            }
        }

**Comment by MatTheCat** [comment]
See https://github.com/symfony/maker-bundle/issues/907

**Comment by mehov** [comment]
@derrabus Hi, please clarify if you are closing the issue because the answer is we're not supposed to try Symfony 6 this early, and if we choose to, we're on our own?

(I have tried several changes from the linked issue but that didn't help in my case.)

**Comment by derrabus** [comment]
I have closed the issue because we don't need two issues to discuss the same thing. Please continue the discussion on the linked issue.
