### ISSUE TITLE
Invalid CSRF token as a result of session cookie not being set when visiting login form directly

### ISSUE THREAD

**Issue by LushawnDev** [symfony/symfony#42691]
### My Environment
I am running:
- Symfony 5.3.6
- PHP version 7.3
- Debian 10 running on WSL2
- Symfony development server on localhost, accessed via Chrome on the same machine

### Description & What I'm Trying to Achieve
- I am trying to implement a secure login form by following the Symfony tutorial (https://symfony.com/doc/current/security/form_login_setup.html).
- I get the error message "Invalid CSRF token." on the first login attempt but not subsequent login attempts.
- Following debugging (using Xdebug 3) it appears Symfony is not creating a session to link a CSRF token to.

### Steps to Reproduce
- Created a new Symfony project using `symfony new test_project`
- Installed the maker bundle using `composer require symfony/maker-bundle --dev`
- Followed the security set-up guide (https://symfony.com/doc/current/security.html) sections 1-2
- Generated a login form using `make:auth` command following this guide https://symfony.com/doc/current/security/form_login_setup.html
- Accessed https://localhost:8000/login 
- Submit the login form with a valid username and password pair, along with the hidden pre-generated CSRF token

### The Outcome I Was Expecting
- A registered user being able to login at https://localhost:8000/login

### The Actual Outcome
- When accessing https://localhost:8000/login, no cookie is set
- When submitting the login form including the CSRF token, as there is no cookie with this request, Symfony finds no session, and so naturally finds no CSRF token
- As there is no CSRF token Symfony throwns an exception "Invalid CSRF token.". The response headers of this include a cookie that represents a session (assuming automatically, as I have followed the Symfony tutorial)
- When submitting the login form for the second time, as there is a cookie sent in the request headers, Symfony "finds" the CSRF token on the session and so the login works as expected

**Comment by gnito-org** [comment]
Unfortunately I was unable to reproduce the problem. Please see https://github.com/gnito-org/symfony-web-5-3/tree/issue-42691 for the setup.

When I visit https://localhost:8000/login for the first time the cookie is set, and the login is successful, as expected.

Status: Reviewed

**Comment by LushawnDev** [comment]
Hi @gnito-org 
Thanks so much for your response, you helped me uncover what the issue was.
### What I did
- Cloned your repositroy using `git clone --branch issue-42691 https://github.com/gnito-org/symfony-web-5-3.git gnito-solution`
- Installed your project dependencies using `composer install`
- Got the following error when attempting a login: `syntax error, unexpected 'Request' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`
- Realised you were using typed properties in your `LoginFormAuthenticator.php`, which are a feature of PHP 7.4, whereas I was running PHP 7.3 (which I did not realise has reached its end of life)
- Upgraded to PHP 8.0.10

### The outcome
- Your Symfony project now worked as expected with no errors
- I no longer get the CSRF error and my login functionality all works as expected on my own Symfony project.  

Therefore, it appears the issue was that I was using PHP 7.3 which has reached its end of life, because I managed to keep all my original configurations settings (in security.yaml and framework.yaml) unchanged and get my own Symfony project to now work. However, there was nothing in Symfony that alerted me that PHP 7.3 would be incompatible.

Thanks so much for your help!

**Comment by dragu** [comment]
This is still an unfixed bug in Symfony 5.4.28 and PHP 7.4.

**Comment by xabbuh** [comment]
@dragu Please open a new issue with a small example application that allows to reproduce your issue.
