### ISSUE TITLE
https://github.com/symfony/webpack-encore-pack not available anymore

### ISSUE THREAD

**Issue by gewooneendeveloper** [symfony/symfony#42706]
### Discussed in https://github.com/symfony/symfony/discussions/42700

<div type='discussions-op-text'>

<sup>Originally posted by **andreaswarnaar** August 24, 2021</sup>
Currently we are moving to SF 4.4, but just before we finish the current build is failing because the repo 
https://github.com/symfony/webpack-encore-pack is not available anymore.

Suggested fix, republish the https://github.com/symfony/webpack-encore-pack and source so SF 3 with webpack-encore-pack can be updated.

best regards,
Andreas</div>

**Comment by 537mfb** [comment]
that should be https://github.com/symfony/webpack-encore-bundle
change from pack to bundle and it should work

**Comment by fabpot** [comment]
The pack should not be used anymore, and Flex now forces all packs to be unpacked. So, @537mfb is correct.
