### ISSUE TITLE
[Validator] DateValidator, DateTimeValidator should accept \DateTimeInterface

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#42705]
**Symfony version(s) affected**: 5.3.6

**Description**
If passing a `\DateTimeInterface` value to `DateValidator` and `DateTimeValidator`, by default it treats it as invalid.

This is ironic since `DateTimeValidator` actually uses the fact an instance of `\DateTime` was successfully created as a signal the value is valid.

**How to reproduce**

Pass a valid instance of `\DateTimeInterface` to either `DateValidator` or `\DateTimeValidator`, they will validate it as invalid.

**Possible Solution**

Allow `\DateTimeInterface` values as valid.

**Additional context**

Using some tools to read Excel files already converts the values in cells to `\DateTimeInterface` instances (based on Excel cell value format hints). Passing the to the validation process fails it since it's not a string.

**Comment by derrabus** [comment]
You can use a `TypeValidator` for that, can't you?

**Comment by OskarStark** [comment]
I think he can, while I agree that this is a bit ironic 😄

**Comment by dkarlovi** [comment]
Talked to @stof on Slack. He says the behavior is intentional so I'm closing here.

**Comment by derrabus** [comment]
@OskarStark We've had that behavior and deprecated/removed it, see #25015.
