### ISSUE TITLE
AbstractToken's getUserIdentifier return type forced to be string

### ISSUE THREAD

**Issue by beastafk** [symfony/symfony#42704]
**Symfony version(s) affected**: 5.3.6

**Description**
My App allows certain type of users to be anonymous (not fully registered). My User's class implements the UserInterface, but **without** the new `getUserIdentifier` method. For some of the users their `getUsername()` method will return `null`. 

This works fine for Symfony 5.2, but in Symfony 5.3.6, this causes a TypeError:

`Return value of Symfony\Component\Security\Core\Authentication\Token\AbstractToken::getUserIdentifier() must be of the type string, null returned`

This happens because the return type of `getUserIdentifier` in AbstractToken.php (vendor/symfony/security-core/Authentication/Token/AbstractToken.php)  is set to be `: string` and for the users without an Username, it returns null.

```php
public function getUserIdentifier(): string
{
    // ....
    if ($this->user instanceof UserInterface) {
            // @deprecated since 5.3, change to $user->getUserIdentifier() in 6.0
            return method_exists($this->user, 'getUserIdentifier') ? $this->user->getUserIdentifier() : $this->user->getUsername();
    }
    // ...
}
```

**How to reproduce**
1. Setup a basic GuardAuthentication which authenticates users with Symfony 5.3
2. Have User class without implementing the getUserIdentifier() method
2. Load a User with a `null` Username
3. Try to make an authenticated request

**Possible Solution**
In symfony/security-core/Authentication/Token/AbstractToken.php make the return type to be string|null or mark this change as a [BC break] when updating from Symfony 5.2

```php 
public function getUserIdentifier(): ?string
```

**Comment by chalasr** [comment]
Returning `null` from `getUsername()` has never been supported:
https://github.com/symfony/symfony/blob/7fa617d4175e08a3d8e1cb5d67aa4523ad034dd8/src/Symfony/Component/Security/Core/User/UserInterface.php#L71-L73
The added return type declaration only enforces the documented one, this is not a BC break.

**Comment by sellrock-de** [comment]
Have the same error, since the update. Maybe it was not supported, but it was working before. Add Username works now.
