### ISSUE TITLE
Google-mailer (and certainly other) are not detected if they are in the require-dev section

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#42724]
### Discussed in https://github.com/symfony/symfony/discussions/42711

When using `MAILER_DSN=gmail://password@default`, I suddently got the message
```
The "gmail" scheme is not supported.
```
It happen when bumping some debian/php/node version and updated some non-mailer-related libraries, I strictly don't know if it related.

After multiple try, It was related to the fact I added the `symfony/google-mailer` to the require-dev instead of require section.
When adding it to the require section, it works fine.

But, when installing this mailer there is a message saying it should not be used in production ; and I'm using something else. So I don't need to install the symfony/google-mailer in production, only locally, on dev environment. So it makes sens to me to put it in the require-dev section.

Any reason that 
```
composer remove `symfony/google-mailer`
composer require --dev `symfony/google-mailer`
```
break my application ? Can the mailers in the dev section be detected too ?

**Comment by derrabus** [comment]
See #40140 if you want to know why this happens. /cc @nicolas-grekas

**Comment by VincentLanglet** [comment]
> See #40140 if you want to know why this happens.

Yeah, I understood it was happening because of this.
When bumping my dev environment, I also changed the composer version from 2.0.9 to 2.1.6, and the flag used by @nicolas-grekas in his PR was declared in composer 2.1. So it was working well before with a require-dev.

I understand the idea of the PR, but my dev-env use gmail when my prod-env use smtp. I have no reason to require google-mailer for my production then. 
On one side the `InstalledVersion` check should accept dev dependencies in dev environment (at least the one I have in my require-dev section) since I have access to them. On the other side, it would mean dev en prod environment won't have the same check ; but the config is different too so it's not absurd.

**Comment by nicolas-grekas** [comment]
Can you try enabling the gmail transport explicitly in the dev config?

**Comment by VincentLanglet** [comment]
> Can you try enabling the gmail transport explicitly in the dev config?

How ?
