### ISSUE TITLE
invalid_message not translatable

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#42725]
Hi,

I thought the parameter for the form type "invalid_message" was translatable.

I tried this and it didn't work:

```php
'invalid_message' => 'conferences.invalid_message'
```

With this it works:
```php
'invalid_message' => $this->translator->trans('conferences.invalid_message', [], 'validators')
```

I think it would be good not to specify the translation domain :).

Here is my complete form class:
```php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class CommentFormType extends AbstractType
{
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $choices = [...];

        $builder
            ->add('conferences', ChoiceType::class, [
                'choices' => $choices,
                'multiple' => true,
                'expanded' => true,
                'invalid_message' => $this->translator->trans('conferences.invalid_message', [], 'validators')
            ])
            ...
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        ...
    }
}
```

**Comment by alexandre-daubois** [comment]
[translation_domain](https://teams.microsoft.com/l/meetup-join/19%3Ameeting_NjY0ZmFlZDUtNWExMS00NjU0LWJkODAtNGRhOWI5MTk5ZWE1%40thread.v2/0?context=%7B%22Tid%22%3A%224c1d9e0f-5c27-4228-a35a-de7b4083ff7b%22%2C%22Oid%22%3A%22ba7edb14-bce5-4653-aaf7-5ae37ddfe7bb%22%2C%22MessageId%22%3A%220%22%7D) should do the trick :+1:

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by wbrinkman** [comment]
Recently came across this as well, but found the answer in an older issue:
https://github.com/symfony/symfony/issues/6763#issuecomment-12333528

While the form docs do not explicitly mention it, the validation docs do:
https://symfony.com/doc/current/validation/translations.html

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
