### ISSUE TITLE
[Notifier] Access to MessageId from AbstractTransport

### ISSUE THREAD

**Issue by benr77** [symfony/symfony#42747]
I would like to be able to access the message ID as provided by a notifier transport when sending a message. This is so that I can store it, and then use this ID to look up the message when receiving subsequent push notifications from the provider about delivery status etc.

However, using the Notifier component instead of e.g. the `TexterInterface` directly means we have to listen to `MessageEvent` which does not hold the `SentMessage` object.

E.g. the Esendex SMS transport actually returns the unique SMS message ID in the response to the HTTP request. We should be able to add this via `SentMessage::setMessageId()` but then also have `SentMessage` available via `MessageEvent`.

Currently, in `Symfony\Component\Notifier\Transport\AbstractTransport` the `MessageEvent` is dispatched BEFORE the message is actually sent, so we cannot access the message ID from the provider.

```
public function send(MessageInterface $message): SentMessage
{
    // Message is dispatched before we actually do the sending
    if (null !== $this->dispatcher) {
        $this->dispatcher->dispatch(new MessageEvent($message));
    }

    // In the doSend() method, we can extract the message ID returned by the provider
    return $this->doSend($message);
}
```

What is the best way to deal with this. It's easy enough to modify the transport to add the message ID to the `SentMessage` class (in cases where the transport provider actually returns an ID for the sent message). But we then need to make this available in the dispatched `MessageEvent`.

**Comment by OskarStark** [comment]
IIRC there is a new SentMessageEvent starting with 5.4.

cc @ismail1432

**Comment by ismail1432** [comment]
Yes, from 5.4 you'll be able to listen the `SentMessageEvent` which contains the MessageId.
I opened a PR with documentation https://github.com/symfony/symfony-docs/pull/15597/files

**Comment by fabpot** [comment]
Closing then.
