### ISSUE TITLE
InvalidArgumentException show Smtp password

### ISSUE THREAD

**Issue by jmbianca** [symfony/symfony#42750]
**Symfony version(s) affected**: 5.3.6

**Description**
An exception show some privacy info (smtp password) which can be logged

**How to reproduce**
In vendor/symfony/mailer/Transport.php, if the InvalidArgumentException is thrown (in method fromString() ), it shows all the dsn info to log to a SMTP account (login, password, host, port). These infos, as for every exceptions, can be logged in a file or any other "Exception manager" like Sentry.

(was found in my Sentry, cannot reproduce because I didn't find yet why it is happening)

**Possible Solution**
Possible solution is to hide some info (at least, password)

**Additional context**
```
Symfony\Component\Mailer\Exception\InvalidArgumentException
The DSN has some garbage at the end: "<mypassword>@ssl0.ovh.net:465"
```

Thanks!

**Comment by OskarStark** [comment]
Which mailer bridge do you use?

**Comment by jmbianca** [comment]
I'm using the SMTP Transport
```
$transport = Transport::fromDsn('smtp://'.$user.':'.$pwd.'@'.$host.':'.$port);
$mailer = new Mailer($transport);
```

**Comment by Iyadhfaleh** [comment]
@jmbianca , I tried to reproduce the issue with **"symfony/mailer": "5.3.4"** but any exception wasn't thrown .

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/smtp", name="smtp")
     */
    public function index(): Response
    {
        $user ="username";
        $pwd ="password";
        $host = "ssl0.ovh.net";
        $port = "465";
        $transport = Transport::fromDsn('smtp://'.$user.':'.$pwd.'@'.$host.':'.$port);
        $mailer = new Mailer($transport);
        dd($mailer);
    }
}
?>

**Comment by Iyadhfaleh** [comment]
![screenshot_6](https://user-images.githubusercontent.com/3882551/131254131-2053ffb1-9499-44db-8256-3e0d48a0c87b.png)

**Comment by jmbianca** [comment]
Hi,
As I said before, I wasn't able to reproduce it yet, sorry. But maybe, it come from the password itself (maybe some unauthorized character in it, need more investigation but I am on hollyday right now). In all case, the Exception thrown will write the login and password of the user in the logs/sentry/etc.

**Comment by jmbianca** [comment]
The password which was in use when the error was thrown have characters like ")", "*", "\"

**Comment by Iyadhfaleh** [comment]
@derrabus Hi , I reproduced the issue and I created my first PR , can you check it please .

![issue](https://user-images.githubusercontent.com/3882551/131507166-087f3c81-35d6-4616-b30c-4319fec749af.png)
