### ISSUE TITLE
[RFC][Validator] Deprecate argument for ExecutionContextInterface::getPropertyPath()

### ISSUE THREAD

**Issue by scyzoryck** [symfony/symfony#42767]
**Description**
Hello!
I was looking how we can improve performance of validator. One of the suspicious call seems to be `ExecutionContextInterface::getPropertyPath()`. Under the hood it calls `PropertyPath::append()` to apply optional subpath, what was hard to understand, why this geter requires `string $subPath`. 
I would propose to deprecate usage of `$subPath` argument to make the function simpler and improve performance by around 2%. 

**Example**
[Blackfire profile with Symfony 4.4](https://blackfire.io/profiles/690d807a-32c4-4f10-9396-572c110983fc/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=Symfony%5CComponent%5CValidator%5CContext%5CExecutionContext%3A%3AgetPropertyPath&callname=main())

To make it backward compatible I would propose to change body of `getPropertyPath` method to:
```
public function getPropertyPath(string $subPath = ''): string
{
    return $subPath === '' ?  $this->propertyPath : PropertyPath::append($this->propertyPath, $subPath);
}
```
The function with argument is used once in `RecursiveContextualValidator`:

```
public function atPath(string $path)
{
    $this->defaultPropertyPath = $this->context->getPropertyPath($path);

    return $this;
}
```
Where it can be easily replaced to 
```
public function atPath(string $path)
{
    $this->defaultPropertyPath = PropertyPath::append($this->context->getPropertyPath(), $path);

    return $this;
}
```

**Comment by derrabus** [comment]
Do you want to open a PR with our change for 5.4?

**Comment by scyzoryck** [comment]
If it sounds reasonable for you - yes, of course :)
