### ISSUE TITLE
Option to disable check for unused environment variables

### ISSUE THREAD

**Issue by malteschlueter** [symfony/symfony#42760]
**Description**
It would be nice to have the option to disable the check for unused environment variables.

The reason is that we have problems to switch from YAML configuration to PHP configuration to use the new Config Builder classes which has been introduced in 5.3. After switching to the PHP configuration only in the `test` environment we are now getting the message `Environment variables "REDIS_HOST" are never used. Please, check your container's configuration.`. The `dev` and `prod` environment works well. I've created a example project where you can see the configuration https://github.com/malteschlueter/symfony-reproducers/blob/bugfix/misssing-env-variables-in-php-configuration/config/packages/artprima_prometheus_metrics.php and the error message https://github.com/malteschlueter/symfony-reproducers/runs/3442504098.

Maybe the configuration implementation of `artprima/prometheus-metrics-bundle` is "responsible" for it but in my opinion it should not stop the development of an project to use a bundle in a single environment.

I don't know if this issue is a feature request or bug report.

WDYT?

**Comment by nicolas-grekas** [comment]
I'm :-1:. Being strict on this topic helps spot mistakes as early as possible.
