### ISSUE TITLE
[Passoword hasher] Make MessageDigestPasswordHasher::mergePasswordAndSalt protected

### ISSUE THREAD

**Issue by TomaszGasior** [symfony/symfony#42781]
**Description**
Make MessageDigestPasswordHasher::mergePasswordAndSalt() method protected instead of private to make it possible to create custom password hasher based on MessageDigestPasswordHasher but just with different  mergePasswordAndSalt() mechanism.

**Example**
It was possible to create this kind of custom hasher in Sf 5.2, using (currently deprecated) MessageDigestPasswordEncoder: 
https://github.com/TomaszGasior/RadioLista-v3/blob/096c05f48c24b6aaa6799372e28a45defc9cc832/src/Security/Encoder/RLv1Encoder.php#L14

In Sf 5.3 I have to reimplement the whole logic:
https://github.com/TomaszGasior/RadioLista-v3/blob/839c8175d253adaf43746aad6101195c56f28a06/src/Security/Hasher/RLv1PasswordHasher.php

It's not that hard, at least in my example, but I think making MessageDigestPasswordHasher reusable may be useful for someone. What do you think?

**Comment by derrabus** [comment]
IIRC, we've explicitly decided against this because we don't want to maintain this extension point anymore.

**Comment by TomaszGasior** [comment]
Okay, makes sense. :) Thanks.
