### ISSUE TITLE
[RateLimiter] It does not work with long intervals (1 month, 1 year)

### ISSUE THREAD

**Issue by Barvoj** [symfony/symfony#42784]
**Symfony version(s) affected**: 5.3, but seems that it does not work in any newer version (5.4, 6.0).

**Description**
Rate limit does not work with long intervals (1 month, 1 year). 1 year is transformed to 0 seconds so it basically does not limit anything.

**How to reproduce**
Set rate limit 1 and interval 1 year. Send multiple requests - none of them is stopped.

```yaml
framework:
    rate_limiter:
        anonymous_api:
            policy: 'fixed_window'
            limit: 1
            interval: '1 year'
```

```php
// src/Controller/ApiController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;
use Symfony\Component\RateLimiter\RateLimiterFactory;

class ApiController extends AbstractController
{
    public function index(Request $request, RateLimiterFactory $anonymousApiLimiter)
    {
        $limiter = $anonymousApiLimiter->create($request->getClientIp());
        if (false === $limiter->consume(1)->isAccepted()) {
            throw new TooManyRequestsHttpException();
        }
    }
}
```

**Possible Solution**

It is caused by https://github.com/symfony/rate-limiter/blob/d00d756e2c9f9c8cc7964c19e619bfe19702559a/Util/TimeUtil.php#L21-L28 because it uses only seconds, minutes, hours and days to compute number of seconds from DateInterval. It ignores months and years.

I suggest to deduct timestamps to compute number of seconds:
```php
public static function dateIntervalToSeconds(\DateInterval $interval): int
{
    $now = new DateTimeImmutable();

    return $now->add($interval)->getTimestamp() - $now->getTimestamp();
}
```

**Comment by derrabus** [comment]
I think the component was not designed with intervals in mind that are as long as yours. Also, months and years have variable length and cannot be translated to seconds. Allowing them would make the component more complex and I'm unsure if it's worth it.

On the other hand, simply ignoring month and year components of the interval might be rather surprising to developers. Maybe the solution is to detect that case and throw a proper error instead.

**Comment by derrabus** [comment]
cc @wouterj

**Comment by Barvoj** [comment]
Problem is variable length of month/year or long interval in general? Because I am ok with interval `30 days` or `365 days` (I dont need month/year unit). I even tried it, but somewhere in process `30 days` is converted to `\DateInterval` with 1 month inside and `365 days` is converted to `\DateInterval` with 1 year inside it. And for months and years it does not work...

**Comment by derrabus** [comment]
I guess we need to find a solution without `DateInterval` then. But I'd like to hear @wouterj's opinion on this.

**Comment by wouterj** [comment]
I have no strong opinion here.

This component is created as an abstraction of the login throttling feature, as rate limiting was found to be usable in other situations as well. That's where the original limit of day comes from (I don't think long intervals for login throttling make any sense).

However, the component as it is now is perfectly usable for e.g. paid API requests. In these cases, having licenses for x requests per month is perfectly reasonable. So :+1: to support long intervals.

**Comment by derrabus** [comment]
> but somewhere in process `30 days` is converted to `\DateInterval` with 1 month inside and `365 days` is converted to `\DateInterval` with 1 year inside it

Did find out why this happens? Because `DateInterval` itself should convert between days and months:

https://3v4l.org/858Wf

**Comment by Barvoj** [comment]
`DateInterval` is created via `DateTimeImmutable::diff` https://github.com/symfony/rate-limiter/blob/d00d756e2c9f9c8cc7964c19e619bfe19702559a/RateLimiterFactory.php#L74 and its behaviour is slightly different:

https://3v4l.org/IL9O2
