### ISSUE TITLE
[Translation] Can not use PhpExtractor standalone (missing symfony/finder)

### ISSUE THREAD

**Issue by dakur** [symfony/symfony#42788]
**Symfony version(s) affected**: N/A

**Description**
`PhpExtractor#extractFromDirectory()` uses `Symfony\Component\Finder\Finder` class which is not present if `symfony/translation` is used standalone and no other dependency requires `symfony/finder`. That's because `symfony/finder` is only a dev dependency of `symfony/translation`.

**How to reproduce**
Install `symfony/translation` and try to use `PhpExtractor#extract()`.

**Possible Solution**
Move `symfony/finder` from `require-dev` to `require` in `composer.json`.

**Workaround**

Require `symfony/finder` in my application.

**Comment by derrabus** [comment]
The Finder component is only required for a non-essential subset of the features the Translation component provides. This is why Finder is not a mandatory dependency. We could certainly improve the error message here, but I would not make the dependency mandatory.

**Comment by dakur** [comment]
@derrabus OK, improved error message would be great. Possible solution included will be useful as well, something like `symfony/finder is not installed, please run composer require symfony/finder`, so that I as a developer know what was the author's intention to solve the situation. Thank you!

**Comment by derrabus** [comment]
Sounds good. Do you want to create the PR?

**Comment by dakur** [comment]
I'm sorry, I have never worked in Symfony so I have no idea about coding styles, exception types etc.

But as it is basically only one `\class_exists()` check + throwing an exception before `new Finder()`, I guess it should be not a big deal for anyone more familiar with Symfony. 🙂

Something like this:
```php
if ( ! \class_exists(Finder::class)) {
    throw new MissingDependency('You\'re missing symfony/finder package. Please install it with your package manager.');
}
```

**Comment by derrabus** [comment]
All right, I've added a "Help wanted" label. Let's see if someone picks it up.

And in case you change your mind: PR welcome, I guess. 🙂

**Comment by dakur** [comment]
Well, if you write me here correct exception class name and if the above snippet is OK about code style, I can do it, it's task like for two minutes I guess. I just thought it would be quicker to do it on your own. 🙂

**Comment by ro0NL** [comment]
take this: https://github.com/symfony/symfony/search?q=%22Try+running+%22

**Comment by dakur** [comment]
@ro0NL Great, I didn!t had such idea to search for it. 🙂

I've made PR #42808 but I'm not sure which branch I should target. See https://github.com/symfony/symfony/pull/42808#issuecomment-909148560 please

cc @derrabus
