### ISSUE TITLE
[DSN] password or username contains parentheses throw exception

### ISSUE THREAD

**Issue by Iyadhfaleh** [symfony/symfony#42813]
version : 5.4

**Description**

Transport dsn parser throw exception when the username or password contains parentheses "pass(word)_example".

**How to reproduce**
---php
 $user ="username";
        $pwd ="pass(word)";
        $host = "ssl0.ovh.net";
        $port = "465";
        $transport = Transport::fromDsn('smtp://'.$user.':'.$pwd.'@'.$host.':'.$port);
        $mailer = new Mailer($transport);

**Possible Solution**
PR  #42814

**Comment by jderusse** [comment]
See documentation: https://symfony.com/doc/current/mailer.html#transport-setup

> If the username, password or host contain any character considered special in a URI (such as +, @, $, #, /, :, *, !), you must encode them. See RFC 3986 for the full list of reserved characters or use the urlencode function to encode them.

And the RFC says:

>       reserved    = gen-delims / sub-delims
>
>      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
>
>      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
