### ISSUE TITLE
[Messenger] Dispatching the message inside a handler causes a socket error sometimes

### ISSUE THREAD

**Issue by vuras** [symfony/symfony#42825]
**Symfony version(s) affected**: 5.3.6

**Description**
Hello,

I have a system that needs to dispatch message after handling another message and sometimes not every time I get an error: **Library error: a socket error occurred** when messenger is trying to dispatch it. After throwing the exception message that was handled is being marked as failed and is retried which is spamming my database because everything was handled successfully up until the messenger trying to dispatch a message after successfully handling it.
I tried to play with AMQP options but with no success. Is it a bug or am I missing something? Maybe someone has any suggestions on how to workaround it?

**How to reproduce**
Dispatch a message inside a handler.

**Comment by Tobion** [comment]
See #32357.  don't think there is a good solution that works in every case.

**Comment by brzuchal** [comment]
@Tobion I've spent all my day investigating the issue, and I think there is a real bug at line https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L555

A small [test script](https://gist.github.com/brzuchal/2999645af9ab63ca13b76b89e38bb0da) shows that in case of using AmqpTransport as a sender on the environment with more than one Transport (whatever kind it is) for pulling but the AmqpTransport INSTANCE only occasionally publishing may cause a connection to be dropped silently by a broker which on above-mentioned line gives false positive. 
A solution might be to call the `AMQPConnection::(p)?reconnect` method and instead of checking `isConnect` on a channel (which still gives a false positive after reconnecting) check the `isConnect` on the channel's connection!! (IMPORTANT) which should then give `false`.

This affects many Symfony versions I guess. Please ping me for more details if you have any doubts.

---

Ofc executing `AMQPConnection::(p)?reconnect` is an additional cost but I guess this has to be concerned when the transport is used only occasionally in senders mode. There could be a calculation of heartbeat considered or ask for help the maintainers of [php-amqp](https://github.com/php-amqp/php-amqp) as there are also some issues similar https://github.com/php-amqp/php-amqp/issues/305

Hope I'm on the right track.

**Comment by brzuchal** [comment]
For me this worked in `Connection` class:
```
    private function clearWhenDisconnected(): void
    {
        $connection = $this->channel()->getConnection();
        if ($this->amqpChannel) {
            if ($connection->isPersistent()) {
                $connection->preconnect();
            } else {
                $connection->reconnect();
            }
            $this->amqpChannel = null;
            $this->amqpQueues = [];
            $this->amqpExchange = null;
            $this->amqpDelayExchange = null;

            return;
        }

        if (!($connection->isConnected())) {
            $this->amqpChannel = null;
            $this->amqpQueues = [];
            $this->amqpExchange = null;
            $this->amqpDelayExchange = null;
        }
    }
```

> *Note!* I'm aware this is an ugly hack, presenting it here only to show that it might work to reconnect especially when only the sender is used.

**Comment by nikophil** [comment]
nice to see this fix
on our side we've fixed by forcing the connection to disconnect when a `TransportException` occurs in `AMQPTransport`

```php
    public function send(Envelope $envelope): Envelope
    {
        try {
            return $this->decorated->send($envelope);
        } catch (TransportException $e) {
            /** @var RetryAfterAMQPExceptionStamp|null $stamp */
            $stamp = $envelope->last(RetryAfterAMQPExceptionStamp::class);

            if (null === $stamp) {
                $stamp = new RetryAfterAMQPExceptionStamp();
                $envelope = $envelope->with($stamp);
            } else {
                $stamp->increaseRetryAttempts();
            }

            if ($stamp->getRetryAttempts() < 3) {
                /*
                 * We only disconnect: the Connection object will be cleaned and AmqpConnection reconnected afterwards
                 * @see \Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::clearWhenDisconnected()
                 */
                $this->connection->channel()->getConnection()->disconnect();

                return $this->send($envelope);
            }

            throw $e;
        }
    }
```

but I think @brzuchal  is cleaner

**Comment by klewi1983** [comment]
> For me this worked in `Connection` class:
> 
> ```
>     private function clearWhenDisconnected(): void
>     {
>         $connection = $this->channel()->getConnection();
>         if ($this->amqpChannel) {
>             if ($connection->isPersistent()) {
>                 $connection->preconnect();
>             } else {
>                 $connection->reconnect();
>             }
>             $this->amqpChannel = null;
>             $this->amqpQueues = [];
>             $this->amqpExchange = null;
>             $this->amqpDelayExchange = null;
> 
>             return;
>         }
> 
>         if (!($connection->isConnected())) {
>             $this->amqpChannel = null;
>             $this->amqpQueues = [];
>             $this->amqpExchange = null;
>             $this->amqpDelayExchange = null;
>         }
>     }
> ```
> 
> > _Note!_ I'm aware this is an ugly hack, presenting it here only to show that it might work to reconnect especially when only the sender is used.

@brzuchal for me, your code works on symfony 5.4 too. Can you do a pull request for this code?

**Comment by brzuchal** [comment]
> > For me this worked in `Connection` class:
> > ```
> >     private function clearWhenDisconnected(): void
> >     {
> >         $connection = $this->channel()->getConnection();
> >         if ($this->amqpChannel) {
> >             if ($connection->isPersistent()) {
> >                 $connection->preconnect();
> >             } else {
> >                 $connection->reconnect();
> >             }
> >             $this->amqpChannel = null;
> >             $this->amqpQueues = [];
> >             $this->amqpExchange = null;
> >             $this->amqpDelayExchange = null;
> > 
> >             return;
> >         }
> > 
> >         if (!($connection->isConnected())) {
> >             $this->amqpChannel = null;
> >             $this->amqpQueues = [];
> >             $this->amqpExchange = null;
> >             $this->amqpDelayExchange = null;
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > _Note!_ I'm aware this is an ugly hack, presenting it here only to show that it might work to reconnect especially when only the sender is used.
> 
> @brzuchal for me, your code works on symfony 5.4 too. Can you do a pull request for this code?

I'll see if I find the time to od so next week.

**Comment by dmitryuk** [comment]
Any updates on issue? I got the same bug
