### ISSUE TITLE
Compile Error: Declaration of ContainerPfn5F6x\DibiConnection_5a906da::__isset($name) must be compatible with eip\CoreBundle\Dao\MySQL\DibiConnection::__isset(string $name): bool

### ISSUE THREAD

**Issue by ok2cqr** [symfony/symfony#42826]
**Symfony version(s) affected**: newer than 5.2.1, php 7.3., it works on 5.2.1

**Description**
After update to newer version of Symfony in my project, I always get this error message:

Compile Error: Declaration of ContainerPfn5F6x\DibiConnection_5a906da::__isset($name) must be compatible with eip\CoreBundle\Dao\MySQL\DibiConnection::__isset(string $name): bool

**Additional context**
Everything works fine with version 5.2.1 and older. The issue appeard only on newer versions.

**Comment by derrabus** [comment]
Can you provide a small application that allows us to reproduce your problem?

**Comment by ok2cqr** [comment]
Unfortunately I can't reproduce it with a simple application :(. it seems is somehow related to the source of the application.

**Comment by derrabus** [comment]
Without reproducing your problem, there isn't much we can do for you here, I'm afraid. 😕

**Comment by Nyholm** [comment]
Hm.. did you clear the cache directory and the same thing happens?

It is really hard to debug this issue without a reproducer app or a failing test case.

**Comment by ok2cqr** [comment]
Yes, I cleared the cache many times. When I create a new Symfony project, install the dependencies, it works. Maybe it's somehow related to the project, it's originally built with Symfony 3.1 and upgraded to 5.2, the directory structure of the project didn't change. Maybe there is a problem, I don't know :(. Maybe some parameter is missing?  The error is very strange.

**Comment by Nyholm** [comment]
I think it is something in your service definition. And yes, it is most likely one of two cases: 
A) You have a service definition or combination of classes that is an edge case that nobody found before
B) You are doing something wrong somehow and the error message is not helpful

It is super hard to find the bug (in symfony or your app) if we cannot see a reproducer. 

--------

I could also be wrong, it could be: 
C) Something else

But that makes it even harder to know. =)

**Comment by ok2cqr** [comment]
I just found out that the error is related to this line in Dibi:

https://github.com/dg/dibi/blob/7e288d92008800d8506072468ce0ca8bb9f0cfb6/src/Dibi/Connection.php#L23

When I remove that line, it helps. I see another error but it seems the container is compiled successfully. 

Very strange is that 5.2.1 works fine but after upgrade to a higher release number, it's broken :(.

**Comment by nicolas-grekas** [comment]
The root issue is that the declaration of `__isset()` is breaking LSP in the Dibi lib: the method must accept `mixed`, not `string`. This will be enforced in PHP 8.1 I think.
I guess that the behavior you see here is because the proxy-manager lib that is generating the proxy class hardcodes this (missing) type for `__isset()`.

You should report this to the Dibi lib.
