### ISSUE TITLE
Insufficient error handling in vendor/symfony/firebase-notifier/FirebaseTransport.php

### ISSUE THREAD

**Issue by fabbaumgartner** [symfony/symfony#42841]
**Symfony version(s) affected**: 5.3.4
**Symfony/firebase-notifier version(s) affected**: 5.3.4

**Description**
Insufficient error handling in doSend() method in vendor/symfony/firebase-notifier/FirebaseTransport.php

**How to reproduce**
Send a firebase request with an timed out token

**Possible Solution**
Correct error verification to catch errors, also take return values failure/success into account

**Additional context**
The error catching part:
`        if ($jsonContents && isset($jsonContents['results']['error'])) {
            throw new TransportException('Unable to post the Firebase message: '.$jsonContents['error'], $response);
        }`
        
Does not catch errors returned by firebase:
`array:5 [
  "multicast_id" => 0101010101010101010
  "success" => 0
  "failure" => 1
  "canonical_ids" => 0
  "results" => array:1 [
    0 => array:1 [
      "error" => "NotRegistered"
    ]
  ]
]`

**Comment by OskarStark** [comment]
Looks like this can be improved.

Open for a PR? 😃

**Comment by fabbaumgartner** [comment]
Honestly.. I don't know the Symfony coding or PR guidelines

**Comment by dmaicher** [comment]
> Honestly.. I don't know the Symfony coding or PR guidelines

Its not that complicated :wink: 

Just have a look at https://symfony.com/doc/current/contributing/code/pull_requests.html and start contributing :sunglasses:

**Comment by Nyholm** [comment]
Just send a "normal PR" and we are happy to help you if something is missing. 

If you feel like you want to try sending a PR to Symfony another time, then just let this thread know so someone else can work on a fix.

**Comment by villfa** [comment]
It's related to #42690, but I think there is still an issue (`['results']['error']` instead of `['results'][0]['error']`): https://github.com/symfony/symfony/blob/b9ab0ad73fcd432c577f33e06da55df6def8ba06/src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php#L88
