### ISSUE TITLE
Adding custom form_themes via Bundles

### ISSUE THREAD

**Issue by MichaelBrauner** [symfony/symfony#42859]
In symfony form_themes can be registered by pushing a flex recipe to the flex contrib repo. 
And in case of overwritten files (like `twig.yaml`) it has to be manually syncronized with git commands.

For some cases this might be a good approach but in fact for extensible software systems it's not that well suited.  
As I can see its actually impossible for bundles to extend the existing system with custom form themes just by installing it via composer. 

In my oppinion - in order to use symfony as an extensible system it should be the goal to enable bundles to add every important part of an application without the need of a human perfoming manual steps. 

Maybe everything can stay as it is, just that for example the twig bridge fires some events to hook in (to enable custom form_themes) this would help a lot.

**Comment by lyrixx** [comment]
What about using container::prependConfiguration from your bundle extension ?

**Comment by yceruto** [comment]
> As I can see its actually impossible for bundles to extend the existing system with custom form themes just by installing it via composer.

It's actually possible by loading bundle config on your DI extension class:
```php
class MyBundle extends Extension implements PrependExtensionInterface
{
    public function prepend(ContainerBuilder $container): void
    {
        $container->prependExtensionConfig('twig', [
            'form_themes' => ['@MyBundle/form_themes/fields.html.twig'],
        ]);
    }
}
```
The order of the themes in the `twig.form_themes` option is important. Each theme overrides all the previous themes, so you must put the most important themes at the end of the list. 

You also can use`$container->loadFromExtension()` to append config.

> In my opinion - in order to use Symfony as an extensible system it should be the goal to enable bundles to add every important part of an application without the need of a human performing manual steps.

Bundles have to do this task quite often to plug-&-play optional features, in some big projects, I opted to add a bundle convention and auto-prepend config files from `AnyBundle/Resources/config/packages/` directory (as Symfony does for `<root>/config/packages/`). This way, I can write them in any format (Yaml preferably) rather than implementing `PrependExtensionInterface` on each bundle.

I'm not sure that such a global convention would be useful enough to be included in Symfony. What do you think?

**Comment by MichaelBrauner** [comment]
Hey! Thank you for your comments. 

> What about using container::prependConfiguration from your bundle extension?

This way it is not possible to build plugin systems:

<img width="400" alt="Bildschirmfoto 2021-09-03 um 07 45 04" src="https://user-images.githubusercontent.com/4937572/131956359-f26bb98d-108a-41d3-9476-84e6e1ab9ccc.png">

Imagine a plugin marketplace where the first plugin selected can register a new field-type or something like that - and the next ones have to show an error: "It is not possible to install multiple Fieldtype plugins because of ...." - ya - because of what?

> You also can use `$container->loadFromExtension()` to append config.

Is this a solution without limitations? 
For form_types the order is important.  And in general the most common use case is bundles want to append custom configuration.  If this works for multiple bundles, it maybe would solve the problem...

> I'm not sure that such a global convention would be useful enough to be included in Symfony. What do you think?

It would be much more easy to just mimic the correct structure inside the bundles and easily add additional configuration. I mean, why not? 
When I think about extensible systems this would be huge win. 

In case of form_themes - at the moment you have to [write a documentation](https://github.com/froala/KMSFroalaEditorBundle#step-4-load-twig-form-widget), the installing person has to read it - go to config/packages/twig.yaml,  add for example: 

```
form_themes:
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'
```

In my opinion it would be better for extensible software systems to not have these hurdles.

**Comment by lyrixx** [comment]
> Imagine a plugin marketplace where the first plugin selected can register a new field-type or something like that - and the next ones have to show an error: "It is not possible to install multiple Fieldtype plugins because of ...." - ya - because of what?

Why would it be the case?

> In case of form_themes - at the moment you have to [write a documentation](https://github.com/froala/KMSFroalaEditorBundle#step-4-load-twig-form-widget), the installing person has to read it - go to config/packages/twig.yaml, add for example:

You can create a symfony recipice to automatise that

**Comment by MichaelBrauner** [comment]
As far as I know, you can write a flex recipe that overwrites twig.yaml.

After that someone has to sync it manually with `git add -p` and `git checkout` in order to not commit the deletion lines of that file.
Or are there other options that I haven't seen yet?

In my opinion, having to constantly write Flex recipes for every little plugin is a bit too much.

When I look at the Sylius Ecosystem - the installation instructions for plugins are often pages long.

As for the data structure with Doctrine, I can understand that you have to work manually with traits and interfaces there.
Flex also makes good sense for completely new files (config/packages/mybundle.yaml).

But as far as the extension of configuration is concerned, I think it would be wonderful to have some kind of event system that bundles could hook into or the global convention mentioned by @yceruto .

**Comment by lyrixx** [comment]
I was thinking of adding a file like this

```yaml
# yourpackage.yaml (not twig here)
twig:
  form_themes:
    -  '@KMSFroalaEditor/Form/froala_widget.html.twig'
```

**Comment by MichaelBrauner** [comment]
Oh, thank you! 

I tested it and it works. 
I did not know that it is possible to reference the same configuration tree multiple times and symfony merges it.

I also tested `$container->loadFromExtension` suggested by @yceruto. 
This also got merged! 

In both ways I was able to programmatically add multiple form themes from multiple bundles.

> Bundles have to do this task quite often to plug-&-play optional features, in some big projects, I opted to add a bundle convention and auto-prepend config files from AnyBundle/Resources/config/packages/ directory (as Symfony does for <root>/config/packages/). This way, I can write them in any format (Yaml preferably) rather than implementing PrependExtensionInterface on each bundle.

It would be nice to see how you implemented it. Would be great if you would have a link to an implemention for sharing. 

In any case, I would like to thank you for the quick answers and your patience with my ignorance :).

**Comment by yceruto** [comment]
> It would be nice to see how you implemented it. Would be great if you would have a link to an implemention for sharing.

Yes sure, here is a sample:
```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function configureContainer(ContainerConfigurator $container): void
    {
        // ...

        foreach ($this->container->getParameter('kernel.bundles_metadata') as $bundle) {
            if (is_dir($dir = $bundle['path'].'/Resources/config/packages') || is_dir($dir = $bundle['path'].'/config/packages')) {
                $container->import($dir.'/*.yaml');
            }
        }
    }
}
```

**Comment by MichaelBrauner** [comment]
Thats great. Thank you so much!
