### ISSUE TITLE
4.4.30: Performance Metrics in Symfony profiler are not working

### ISSUE THREAD

**Issue by janwebdev** [symfony/symfony#42884]
**Symfony version(s) affected**: 4.4.30

**Description**
Performance Metrics in Symfony profiler are not working 
**How to reproduce**
Just update to latest LTS version (4.4.30 at the moment) and enter the Symfony profiler -> Performance metrics in DEV environment. In symfony toolbar its shown "n/a" for the timing

**Possible Solution**

**Additional context**
PHP 8.0.9

**Comment by fabpot** [comment]
Already reporter and fixed, will be part of the next version.

**Comment by fabpot** [comment]
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases
