### ISSUE TITLE
Sessions are not saved when using runtime + bref/swoole/roadrunner

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#42890]
Im not sure if this is a bug report or a missing feature. But I do need some help. 

**Symfony version(s) affected**: 5.4

**Description**
Using the Runtime component and non-standard HTTP server, ie Bref, Swoole or RoadRunner seams to have an issue with sessions. I know @alexander-schranz have done some great work on that already. He also added #41390. 

The sessions are not saved. I am not sure why. I assume it is because the PHP process handles multiple requests and Symfony does not really know when one session/request ends and the other start. 

**How to reproduce**

I did spend some time to create a reproducer: https://github.com/Nyholm/sf-bref-session-issue
I also deployed it here: https://hb74khn5fk.execute-api.eu-central-1.amazonaws.com/
(it will be open for a few days)

You will see the issue as you cannot login. 

**Possible Solution**
Not sure. I need some help finding the solution. 

**Additional context**

This might be an issue in runtime/bref, or in a Symfony component. It might also require some changes in Symfony to make sure runtime/bref works perfectly.

**Comment by Nyholm** [comment]
Oh. Interesting. PR #41390 will solve the problem for me.

**Comment by fabpot** [comment]
So, we can probably close this issue?
