### ISSUE TITLE
No timing events have been recorded in Profiler Performance Execution timeline

### ISSUE THREAD

**Issue by blzk-dev** [symfony/symfony#42895]
**Symfony version(s) affected**: 5.3.7

**Description**
Performance is not profiled as it should be, because symfony/stopwatch is installed and debugging enabled. See attached screenshots and logs.

**How to reproduce**
Open console terminal and run symfony new my_project_name --full and then create some Controller with template and check it out in browser.

**Additional context**
Screenshots
<img width="325" alt="Snímek obrazovky 2021-09-06 v 11 17 50" src="https://user-images.githubusercontent.com/80812633/132194417-ef834b60-35db-412c-933f-7c6da0a43a2a.png">

<img width="610" alt="Snímek obrazovky 2021-09-06 v 11 18 16" src="https://user-images.githubusercontent.com/80812633/132194469-5cc7408f-ac99-4fdc-b248-ac7e1d90e503.png">

<img width="1086" alt="Snímek obrazovky 2021-09-06 v 11 18 43" src="https://user-images.githubusercontent.com/80812633/132194539-782f2f4a-93f1-4e4d-8319-2c917b9d0629.png">

<img width="384" alt="Snímek obrazovky 2021-09-06 v 11 19 14" src="https://user-images.githubusercontent.com/80812633/132194617-49ab453b-f116-44f4-b3c5-f43c36bbb255.png">

Logs
[2021-09-06T09:32:07.365693+00:00] request.INFO: Matched route "app.site.default.index". {"route":"app.site.default.index","route_parameters":{"_route":"app.site.default.index","_controller":"App\\Controller\\SiteDefaultController::index"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2021-09-06T09:32:07.599864+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"df3b42"},"request_uri":"https://localhost:8000/_wdt/df3b42","method":"GET"} []

**Comment by fabpot** [comment]
Will be fixed in the next version.

**Comment by fabpot** [comment]
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases

**Comment by uncaught** [comment]
I have the same issue with Symfony 4.4.30. I've just migrated from 3.4 so I could be missing something, but the profiler is enabled, Stopwatch is definitely installed and debug ist true.

@fabpot would you know by any chance if 4.4.30 could be affected by the same bug? Thanks

**Comment by pbek** [comment]
I can report that the `Performance metrics` are working again on 5.3.9. Thank you very much!
