### ISSUE TITLE
The debug toolbar performance section stopped working after a Symfony 5.3 upgrade

### ISSUE THREAD

**Issue by jerhome** [symfony/symfony#42910]
**Symfony version(s) affected**: 5.3.X

**Description**
After upgrading my Symfony stable version to the latest, the performance section of the debug toolbar was down.
I've been asked to install stopwatch and enable debug in the Kernel.
After checking this two points and clearing all caches, the debug toolbar performance/time section is still not working without producing any error.

**How to reproduce**
Upgrade to the latest 5.3 version.

**Possible Solution**
Upgrading to 5.4 (dev/beta) version fixes the issue but I don't wan't to use it in production.

**Additional context**
Dev env : Server MacOS PHP8 + Clients Safari, Firefox
Prod env : Server Linux PHP8 + Clients Safari, Firefox

**Comment by wouterj** [comment]
Already reported in https://github.com/symfony/symfony/issues/42895, https://github.com/symfony/symfony/issues/42884, https://github.com/symfony/symfony/issues/42882 and https://github.com/symfony/symfony/issues/42804 and will be fixed in the next release.

**Comment by stof** [comment]
Note that it is already fixed in the dev version of 5.3.x-dev, not only in 5.4.x-dev

**Comment by jerhome** [comment]
Thank you.

**Comment by fabpot** [comment]
I'm very sorry that this release has some issues.

Let me take this opportunity to actually ask you for some help. Ensuring that new versions have no issues (regressions, BC breaks, ...) is where we need help from the community. If you can, please test dev versions before we make releases (as a rule of thumb, at the end of each month).

More information about how you can do it:
https://wouterj.nl/2021/06/stabilizing-symfony-test-out-pre-releases

**Comment by jerhome** [comment]
> Note that it is already fixed in the dev version of 5.3.x-dev, not only in 5.4.x-dev
@stof Upgrading to 5.3.x-dev did not work for me.
