### ISSUE TITLE
Mime: Email::embed doesn't work for background images

### ISSUE THREAD

**Issue by flack** [symfony/symfony#42921]
**Symfony version(s) affected**: 5.3.4

**Description**

I have an email template which sets a background image on a `td` element like this:

```html
<td background="bgimage.png">
```
This used to work fine in Swiftmailer with more or less the following code:

```php
$cid = $message->embed(Swift_Image::fromPath($path));
$html_body = str_replace($path, $cid, $html_body);
```

**How to reproduce**

In Symfony Mailer, I have the code from the documentation:

```php
$name = basename($path);
$message->embed(fopen($path, 'r'), $name);
$html_body = str_replace($path, 'cid:' . $name, $html_body);
```

Which works fine for `img` tags and `src` attributes, but it completely ignores the `background` attribute, because the regex is only looking at `img` tags:

https://github.com/symfony/symfony/blob/5ccf5ad00f9d5095ca842240e0cf26c060e4afb4/src/Symfony/Component/Mime/Email.php#L469

The HTML in the email looks like this in the end:

```html
<td background="cid:bgimage.png">
```

The image gets attached, but is missing a Content-ID:

```
Content-Type: application/octet-stream; name=bgimage.png
Content-Transfer-Encoding: base64
Content-Disposition: inline; name=bgimage.png; filename=bgimage.png
```

**Possible Solution**

I'm not a 100% sure, but one thing that could help is if Symfony could make sure that each (inline) attachment always gets a Content-ID, then I could work around the regex problem on my end.

An alternative would be to make the regex a bit more loose, basically to have it find anything that looks like `"cid:xxxx"`. Not sure if that would be a 100% safe, but there's still a matching of found CIDs to attachment names, so it should work, no?

**Additional context**

I know that the `background` attribute has probably been deprecated for well over a decade now, and in the normal web context I wouldn't bother trying to support it, but this is email we're talking about, and to this day Outlook (on Windows) uses an HTML rendering engine from 2007, so you have to get pretty old school to get decent looking mails. I guess if you look long and hard enough, there will be some other way to get background images on Outlook, but I also really don't want to re-do (and re-test) all the email templates I have, just because Swiftmailer is EOL.

**Comment by flack** [comment]
P.S.: btw, I also find the API for `embed` a bit unfortunate. There is the unstated assumption that `$name` must be unique (because how else would the matching work), so you can't really use the user-supplied filename (email can have multiple distinct attachments with the same name), but if you generate a unique identifier, it also gets used as the filename in the list of attachments. So I have to choose between unreadable filenames and inline attachments potentially overriding each other

**Comment by flack** [comment]
as a workaround, I've tried to change the embed code to look like this:

```php
$name = basename($uri);
$part = (new DataPart(fopen($uri, 'r'), $name, find_out_mimetype_somehow()))
    ->asInline();
$message->attachPart($part);
$html_body = str_replace($html_body, 'cid:' . $part->getContentId(), $html_body);
```

That almost works, at least like this the attachments all have a Content-ID which matches what I put in the html_body. The only problem is that now the attachment ends up in `$attachmentParts` instead of in `$inlineParts` because of the check in line 476:

https://github.com/symfony/symfony/blob/7c531f575e7e14636378787271c29b094205e147/src/Symfony/Component/Mime/Email.php#L475-L491

So an instantiated `DataPart` can never end up in `$inlineParts`. Shoudn't there be some check in this case so that it gets added to either `$attachmentParts` or `$inlineParts`, depending on Content-Disposition? 
(also, `isset($attachment['part'])` doesn't really have to be in the inner loop, it won't change between iterations)

**Comment by flack** [comment]
Anyone?

Composer now warns me that

```
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
```

and I would like to use symfony/mailer instead, but it just doesn't seem to have the featureset required

**Comment by flack** [comment]
The issue in comment 2 seems to be the same as #43255

**Comment by Guite** [comment]
I just had a quite similar requirement as I needed to create a multipart payload (that is not a mail).

At the moment I am using a workaround like this:

```php
/** @var FileEntity $attachment */
foreach ($attachments as $attachment) {
    $dataPart = new DataPart($attachment->getContent(), $attachment->getName(), $attachment->getMimeType());

    $refObject = new ReflectionObject($dataPart);
    $refProperty = $refObject->getProperty('cid');
    $refProperty->setAccessible(true);
    $refProperty->setValue($dataPart, $attachment->getContentIdAsUrl());

    $requestParts[] = $dataPart;
}
```

Would it be possible to provide a `setContentId()` method for such explicite use cases?
