### ISSUE TITLE
Determining languages for information sources

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#42955]
We are using several languages also for our software developments.
They influence [the selection of identifiers in the evolving source code](https://github.com/symfony/symfony/issues/40473 "Translating PHP classes (and their contents)").
Such source code is an important information source for further data processing.
One data processing area where I got keen on corresponding solutions is also [the handling of translations](https://symfony.com/doc/current/translation#using-real-or-keyword-messages "Using real or keyword messages").
The applied mixture of languages triggers some recurring challenges, doesn't it?

:thinking: I imagine that there is a need to determine the kind of source language in structured ways so that translation approaches can be accordingly adjusted.
I would appreciate further advices.

**Comment by xabbuh** [comment]
As I told you many times before we cannot do anything with just vague suggestions and I am tired of guessing what you want. That's why I am going to close this issue.

**Comment by elfring** [comment]
I am trying again to improve the software development situation.
I guess that you understand [the general translation process](https://symfony.com/doc/current/translation "Support for translations") already.
I came along places which seem to indicate remaining open issues.

Thus I stumbled on probably known technical difficulties, didn't I?

**Comment by elfring** [comment]
:eyes: See also related clarification attempts:
[Translation: Specify the source language](https://github.com/symfony/symfony/issues/37502#issue-651365031 "Suggestion from 2020-07-06")
