### ISSUE TITLE
Split PDO and DBAL adapters

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#42962]
**Description**

In the cache and lock components, we have adapter classes that are able to operate on PDO and DBAL connections:

* `Symfony\Component\Cache\Adapter\PdoAdapter`
* `Symfony\Component\Lock\Store\PdoStore`
* `Symfony\Component\Lock\Store\PostgreSqlStore`

This made sense in the past because DBAL implemented PDO interfaces and remained mostly compatible. However, DBAL has moved away from extending PDO and provides its own interfaces now. And it will probably deprecate more PDO-like methods in the future. Because of that, we have to bloat those classes with if/else blocks.

Would it make sense to split the DBAL logik off those adapters? For instance, we would split `PdoAdapter` into `PdoAdapter` and `DbalAdapter`, maybe with an internal `DatabaseAdapterTrait` that contains common SQL generation logic. I would expect that in the long run, those classes become more maintainable that way.

**Comment by nicolas-grekas** [comment]
Works for me. Would be great to do this in 5.4 to free 6.0 from having to maintain any BC layer.

**Comment by stof** [comment]
:+1: from me

**Comment by fabpot** [comment]
LGTM

**Comment by GromNaN** [comment]
Hi! If not too late, I can take this subject. Here is how I plan to proceed.

I will create a distinct PR for each class. In the following description, `PdoStore` stands for `Symfony\Component\Cache\Adapter\PdoAdapter`, `Symfony\Component\Lock\Store\PdoStore` and `Symfony\Component\Lock\Store\PostgreSqlStore`.

Step 1, in Symfony 5.4 : 
- Create `DbalStore` by duplication of `PdoStore` and removing all code not related to Dbal.
- Add deprecation message in `PdoStore` constructor when using a `DBAL\Connection`. The rest of the class is not modified.

Step 2, in Symfony 6.0 :
- Clean `PdoStore` from code related to DBAL
- Move duplicate code into a trait, when appropriate.

**Comment by fabpot** [comment]
LGTM, but note that we are running out of time for 5.4, so do you think you can work on this very very soon?

**Comment by derrabus** [comment]
Nice work, @GromNaN. Do you have time to look into the cache component as well?

**Comment by GromNaN** [comment]
I'm on the cache component.

**Comment by GromNaN** [comment]
Maintainability being the 1st goal of this split, I wonder if we get real benefits while we introduce code duplication.

I made the split on both components, but there is several parts of duplicate code (SQL queries [1](https://github.com/symfony/symfony/pull/43362/files#diff-6f3ed9629adec15a83efcec6c83826296acb7e55159a0b0ca4289dd9cdab27dcR240-R266) [2](https://github.com/symfony/symfony/pull/43332/files#diff-ba8822764444a76cf5118226689b0e4fdfaac7c8dec3d3084d7c6fe0436aef02R114), algorithm).
A trait has been created for the lock component, the same can be done (later ?) for cache component.

If we had a shared facade class (like DBAL is) it could be used everywhere Symfony interact with a database and we would have only 1 `Lock\Store\DatabaseStore` and `Cache\Adapter\DatabaseAdapter`.

Note: Some other components supports only 1 from both methods : `PdoSessionHandler` use PDO, `symfony/doctrine-messenger` uses DBAL ; and could also profit from this layer.

**Comment by derrabus** [comment]
> If we had a shared facade class (like DBAL is) it could be used everywhere Symfony interact with a database and we would have only 1 `Lock\Store\DatabaseStore` and `Cache\Adapter\DatabaseAdapter`.

That would mean that either DBAL would become our only official way to connect to a database or with that shared façade class you have in mind, we would build our own abstraction layer over database abstraction layers. I think neither is a good idea

**Comment by derrabus** [comment]
@GromNaN Both PRs have been merged up to the 6.0 branch, in case you want to take care of removing the deprecation layers.

**Comment by GromNaN** [comment]
I'm going to do the clean.
