### ISSUE TITLE
[Firewall dispatcher] Traceable Event Dispatcher 

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#42973]
**Symfony version(s) affected**: 5.3.7

**Description**
I was using in the past the general TraceableEventDispatcher in debug mode to track my user actions during dev.
It is not fully possible anymore since version 5.3.7.
The security dispatcher is only a EventDispatcher class.

NB: Therefore, the profiler is pretending security events are not triggered

**How to reproduce**
```
<?php 

// SecuritySubscriber.php
namespace xKzl\MyBundle\Subscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;

use Symfony\Component\DependencyInjection\Argument\ServiceLocator;
use Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher;

class SecuritySubscriber implements EventSubscriberInterface
{
    /**
     * @var array[TraceableEventDispatcher]
     */
    private $dispatchers = [];

    public function __construct(
        ServiceLocator $dispatcherLocator) {

        $this->dispatcherLocator = $dispatcherLocator;
        foreach($this->dispatcherLocator->getProvidedServices() as $dispatcherId => $_) {

            $dispatcher = $this->dispatcherLocator->get($dispatcherId);
            if (!$dispatcher instanceof TraceableEventDispatcher) continue;

            $dispatchers[] = $this->dispatcherLocator->get($dispatcherId);
        }

        dump($dispatchers);
    }

    public static function getSubscribedEvents()
    {
        return [];
    }
}
```

I declared my subscriber as following:
```
        <service id="xKzl\MyBundle\Subscriber\SecuritySubscriber">
            <tag name="kernel.event_subscriber" />
            <argument type="tagged_locator" tag="event_dispatcher.dispatcher" index-by="name"/>
        </service>
```

**Comment by meiyasan** [comment]
Any feedback ?

**Comment by xabbuh** [comment]
Do you mean that when the debug mode is enabled the event dispatcher used by the firewall is not decorated by the `TraceableEventDispatcher` class? If so, would you like to try finding out which commit changes that?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by meiyasan** [comment]
Dear @xabbuh,

Sorry for my late reply. I couldn't spent time on that before. 
I can confirm the issue is persisting in 5.3.9.

Following up with you previous comment, I don't think we can really find a commit for this issue.
The point is that the "main" dispatcher has been split into two parts, while before there was only one dispatcher..
So I can still go back to a previous version, but the problematic dispatcher (that is not decorated) would not exist yet.

I am in the process to find where the service is decorated, but this is quite new to me.. So I am not sure I will trace back this issue quickly. Please find attached the result of dumping the `$dispatcher = $this->dispatcherLocator->get($dispatcherId);` variable running SF 5.3.9
```
SecuritySubscriber.php on line 96:
Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher {#117 ▼
  #logger: Symfony\Bridge\Monolog\Logger {#110 …6}
  #stopwatch: Symfony\Component\Stopwatch\Stopwatch {#266 ▶}
  -callStack: SplObjectStorage {#1010 ▶}
  -dispatcher: Symfony\Component\EventDispatcher\EventDispatcher {#105 …3}
  -wrappedListeners: []
  -orphanedEvents: []
  -requestStack: Symfony\Component\HttpFoundation\RequestStack {#298 ▶}
  -currentRequestHash: "0000000029e59e16000000003be70944"
}
SecuritySubscriber.php on line 96:
Symfony\Component\EventDispatcher\EventDispatcher {#66 ▼
  -listeners: array:7 [▼
    "Symfony\Component\Security\Http\Event\CheckPassportEvent" => array:5 [▶]
    "Symfony\Component\Security\Http\Event\LoginSuccessEvent" => array:4 [▶]
    "Symfony\Component\Security\Http\Event\LogoutEvent" => array:2 [▶]
    "Symfony\Component\Security\Http\Event\AuthenticationTokenCreatedEvent" => array:1 [▶]
    "Symfony\Component\Security\Http\Event\LoginFailureEvent" => array:1 [▶]
    "Symfony\Component\Security\Http\Event\TokenDeauthenticatedEvent" => array:1 [▶]
    "security.authentication.success" => array:3 [▶]
  ]
  -sorted: []
  -optimized: []
```

**Comment by meiyasan** [comment]
I just found the origin of the security event dispatcher for my "main" firewall :
`./vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php(392)`

**Comment by meiyasan** [comment]
Printing the `$this->dispatcherLocator`, I can observe that serviceTypes if somehow casting the security dispatcher to be `Symfony\Component\EventDispatcher\EventDispatcher` :
```
SecuritySubscriber.php on line 93:
Symfony\Component\DependencyInjection\Argument\ServiceLocator {#408 ▼
  -factory: Symfony\Component\DependencyInjection\Container::getService($registry, string $id, ?string $method, $load) {#97 ▶}
  -serviceMap: array:2 [▼
    "event_dispatcher" => array:4 [▼
      0 => "services"
      1 => "event_dispatcher"
      2 => "getEventDispatcherService"
      3 => false
    ]
    "security.event_dispatcher.main" => array:4 [▼
      0 => "privates"
      1 => "security.event_dispatcher.main"
      2 => "getSecurity_EventDispatcher_MainService"
      3 => false
    ]
  ]
  -serviceTypes: array:2 [▼
    "event_dispatcher" => "?"
    "security.event_dispatcher.main" => "Symfony\Component\EventDispatcher\EventDispatcher"
  ]
  -externalId: null
  -container: null
  -factories: array:2 [▶]
  -loading: []
  -providedTypes: null
}```

**Comment by meiyasan** [comment]
I could eventually find that the dispatcher is called in `vendor/symfony/security-bundle/DependencyInjection/Compiler/RegisterGlobalSecurityEventListenersPass.php`, but 
```
 $firewallDispatchers[] = $container->findDefinition('security.event_dispatcher.'.$firewallName);
```

This guy is already returning an EventDispatcher instead of a TraceableEventDispatcher, but therefore not tracing the called listener..

**Comment by chalasr** [comment]
@xKZL Are you wiling to send a PR fixing this?

**Comment by meiyasan** [comment]
Yes, but I am lacking knowledges about internal Symfony architecture.. if I can find where the global event dispatcher gets decorated and where is called the security one I could surely do something.

**Comment by chalasr** [comment]
Got it, event listeners registered on core security events are not traceable anymore. 
To reproduce, register an event listener on e.g. `security.interactive_login`. With authenticator manager disabled, the listener is listed in the `Called listeners` profiler panel but with authenticator manager enabled, it is part of `Non called listeners` although it's actually called.

This qualifies as a bug to me. Any event dispatcher (`event_dispatcher.dispatcher` tagged service) should be decorated as traceable IMHO, but currently only the main `event_dispatcher` service is decorated. The EventDataCollector should then be updated to collect listeners from all those dispatchers instead.
I'll send a PR.

**Comment by meiyasan** [comment]
@chalasr Thank you so much for confirming the bug and your investigation.
I am very interested in understanding how you will fix this in your PR.
I will surely look at it :)

**Comment by chalasr** [comment]
For the record, I started working on a patch for this. The tricky part is that the per-firewall dispatcher services are created at a stage where we cannot use decoration (runs after DecoratorPass), I need to figure out how to make them traceable. 
I will be back on it asap.

**Comment by meiyasan** [comment]
Hi @chalasr, did you make some progress ?
Let me know if I can help in anyway.

**Comment by MatTheCat** [comment]
I had a quick look and the SecurityBundle may be way simpler now than it was when the issue was opened. I should be able to come up with a PR soon.

**Comment by chalasr** [comment]
Awesome.
