### ISSUE TITLE
The regex taken from Symfony being used in `UrlValidator.php` is not correct

### ISSUE THREAD

**Issue by summercms** [symfony/symfony#42987]
**Symfony version(s) affected**: all versions

**Description**

This is not correct and doesn't bother to check the IANA standards which lists the URI scheme formats.

### Steps To Reproduce:

If you look at the regex it just gives a list of protocols followed by `://` on code line: https://github.com/symfony/symfony/blob/2085ff856545c74cee5493c60831491584159660/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L25

The trouble with this is that half of the protocols listed in IANA do not use `://`

Here's an example:

The protocol `bitcoin` found here: https://www.iana.org/assignments/uri-schemes/prov/bitcoin

Scheme syntax:

```
bitcoin:<address>[?[amount=<size>][&][label=<label>][&][message=<message>]]
```

Above says it's using `:` and not `://` after the protocol name `bitcoin`

This page gives even more examples: https://en.bitcoin.it/wiki/BIP_0021

Notice none have `://` and all use `:` after the protocol name `bitcoin`

e.g.

```
bitcoin:<address>
```

not

```
bitcoin://<address>
```

**How to reproduce**

```php
$uri = 'bitcoin://34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo';
```

Outputs the result of `bool(true)` which is incorrect.

```php
$uri= 'bitcoin:34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo';
```

Outputs the result of `bool(false)` which is incorrect.

**Possible Solution**

Half of the IANA URI Schemes use `:` and not `://` you need to go through and update your regex whitelists.

**Additional context**

I opened an issue over in the Laravel repo as they are using your code, found here: https://github.com/laravel/framework/issues/38761

**Comment by ro0NL** [comment]
Note this is a URL validator, not a URI one. AFAIK the `//` is required in URLs.

**Comment by summercms** [comment]
@ro0NL Thanks, I originally opened this up from Laravel side. I think the issue is that they have added a list of URI and URL in their regex.
