### ISSUE TITLE
Local server with transfer-encoding give blank array

### ISSUE THREAD

**Issue by richardkouame** [symfony/symfony#43024]
**Symfony version(s) affected**: 5.3

**Description**
When I make a POST request with the transfer-encoding header, the server return a blank array.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
