### ISSUE TITLE
UrlValidator component fails with one-char subdomain

### ISSUE THREAD

**Issue by MimoBerlino** [symfony/symfony#43038]
**Symfony version(s) affected**: 4.4.30

**Description**
The UrlValidator is failing when the url contains multiple subdomains, and when one of the subdomains is a one-char subdomain. Example: "http://subdom1.subdom2.r.suddom3.domain.tld"
The "**r**" subdomain here makes the validator fail.
Please note that it only happens when the one-char subdomain is positioned between other subdomains.

**How to reproduce**
```
/**
     * @Assert\NotBlank
     * @Assert\Url(protocols = {"https"})
     * @ORM\Column(type="string", length=255)
     */
```

**Possible Solution**
Review the regex modified 2 weeks ago to allow one-char subdomain.

**Additional context**
I could see the regex validator was modified around 2 weeks ago, that introduced this failure.
Here is the commit: https://github.com/symfony/symfony/commit/074539d3c9b889f8b33b30d09633f86de1247c03

**Comment by xabbuh** [comment]
@MimoBerlino Would you like to give it a try?

**Comment by MimoBerlino** [comment]
@xabbuh do you mean the regex has been adapted and ready to be tested/tried?

**Comment by xabbuh** [comment]
No, sorry, I meant if you would like to try fixing the regex in a pull request.

**Comment by MimoBerlino** [comment]
@xabbuh sure. I'll get the time to look at it.

**Comment by DfKimera** [comment]
We're also seeing this same problem.
Do you think you'll be able to pick it up @MimoBerlino? We can help out if you don't have the time!

**Comment by MimoBerlino** [comment]
@DfKimera Sure, any help is much appreciated :)
I have it on the list but still didn't get to it.
Cheers
