### ISSUE TITLE
TraceableFirewallListener very slow with multiple concurrent ajax request on same user

### ISSUE THREAD

**Issue by moebiusband73** [symfony/symfony#43049]
**Symfony version(s) affected**:  5.3.7, 5.4.0-dev

**Description**
On multiple concurrent request authenticating within the session of the same user more and more time is spent in `TraceableFirewallListener`. At the end it is more than 2s per request. The actual doctrine query for the user object happens at the end and only takes around 2ms.

Authentication is done using a custom LoginFormAuthenticator based on the new Authenticator system.
The issue is severely worsened if doing additional queries on the user object as seen here:
```
    public function authenticate(Request $request): PassportInterface
    {
        $credentials = $this->getCredentials($request);

        $user = $this->userProvider->loadUserByIdentifier($credentials['username']);
        $dbPassword = $user->getPassword();
        $passport = new Passport(
            new UserBadge($credentials['username'], [$this->userProvider, 'loadUserByIdentifier']),
            new PasswordCredentials($credentials['password'])
        );

        if ( empty($dbPassword) ) {
            $configuration = new Configuration($this->_em);
            $dnString = $configuration->getValue('ldap_user_bind');
            $passport->addBadge(new LdapBadge('app.ldap', $dnString));
        }
        $passport->addBadge(new CsrfTokenBadge('authenticate', $credentials['csrf_token']));

        return $passport;
    }
```
Now the time spent in `TraceableFirewallListener` is even longer.
Here a screenshot from the timeline profile of one Ajax request:
<img width="1091" alt="Screen Shot 2021-09-16 at 11 41 12" src="https://user-images.githubusercontent.com/11572749/133589752-40bfe897-aee8-43f3-a7ba-7d36a68786dd.png">

The application counts on concurrent execution of asynchronous Ajax queries against various API endpoints. Due to this issue those queries get almost serialized and the application is very slow.
The slowdown was reproduced in dev and prod App environments.

**How to reproduce**
The source code of the complete project is available here: https://github.com/ClusterCockpit/ClusterCockpit/tree/develop
There is a docker compose setup to test it:  https://github.com/ClusterCockpit/cc-docker

You have to copy adapted `composer.json` to enable 5.4.0-dev as profiling in 5.3.7 is defunct.
[composer.json.zip](https://github.com/symfony/symfony/files/7176478/composer.json.zip)
Then log into the php-fpm container, update and rebuild assets:
```
$ docker exec -it cc-php  /bin/bash
$ composer -W  update
$ yarn encore dev
```

**Possible Solution**
Without digging deeper from outside it appears as something locks the user object on DB level for the duration of the query. Still this can not be seen in the profiler or doctrine profiling. I did not yet check the mysql log.
From a technical point of view it should be possible to bypass fetching of the user object and use the session only. Especially for API requests. Maybe this is already possible?

**Additional context**
I will dig deeper what happens within `TraceableFirewallListener`. Maybe I can find out more.

There was a ticket on this issue before:
https://github.com/symfony/symfony/issues/35232

But it was not further investigated at this point.

**Comment by chalasr** [comment]
> I will dig deeper what happens within TraceableFirewallListener. Maybe I can find out more.

That'd be great, https://blackfire.io might help :)

**Comment by ghost** [comment]
Did not understand your description fully but remember that PHP session allows to process only one request at the time per user session. The second and following requests get stucked in one of the very first listeners related to auth.

P.S. in the timeline profile change 1ms to 0ms and you will get more information.

**Comment by moebiusband73** [comment]
Thank you for your quick comment.
I did not think about this before, but now as you mention this  the behavior makes perfect sense if taking into account that the PHP session is the serializing part here.
This means for anything asynchronous and concurrent you always need a separate stateless firewall with a token based authentication?

**Comment by moebiusband73** [comment]
We added a firewall with stateless JWT authentication for all API accesses. This completely solved our problems.
It may help to add a comment in the security documentation about the serializing nature of a PHP session especially with many asynchronous request. This is a pattern that gets more common in modern web applications.
Now where I know it the behavior is clear, but I guess like me a lot of people will trap into this issue.

So this is how it should look like. Most of the runtime is consumed by the controller:
<img width="1317" alt="Screen Shot 2021-09-17 at 10 56 20" src="https://user-images.githubusercontent.com/11572749/133817493-8d164a3a-9588-4e4b-84dc-351538e6cda0.png">

Anyway, from my side this issue is resolved and the ticket can be closed.
Thank you for your help!

**Comment by ghost** [comment]
> Thank you for your quick comment.
> I did not think about this before, but now as you mention this the behavior makes perfect sense if taking into account that the PHP session is the serializing part here.
> This means for anything asynchronous and concurrent you always need a separate stateless firewall with a token based authentication?

Yes, stateless firewalls do not have this problem. As a workaround for the current problem you can register listener on `kernel.request` event with a high priority that will close session. I do this for GET requests and some configured routes. You can also use RedisHandler that allows to disable session locking.

**Comment by Warxcell** [comment]
> As a workaround for the current problem you can register listener on `kernel.request` event with a high priority that will close session. I do this for GET requests and some configured routes. 

But you should be careful, not to use session on these requests anymore.

>You can also use RedisHandler that allows to disable session locking.

Also be careful, because you can lose data which is written in session.

**Comment by chalasr** [comment]
Thanks for investigating, closing then.

**Comment by ghost** [comment]
> But you should be careful, not to use session on these requests anymore.
> Also be careful, because you can lose data which is written in session.

Of course. This is a trade off one has to be aware of.

**Comment by smehdux** [comment]
> We added a firewall with stateless JWT authentication for all API accesses. This completely solved our problems. It may help to add a comment in the security documentation about the serializing nature of a PHP session especially with many asynchronous request. This is a pattern that gets more common in modern web applications. Now where I know it the behavior is clear, but I guess like me a lot of people will trap into this issue.
> 
> So this is how it should look like. Most of the runtime is consumed by the controller: <img alt="Screen Shot 2021-09-17 at 10 56 20" width="1317" src="https://user-images.githubusercontent.com/11572749/133817493-8d164a3a-9588-4e4b-84dc-351538e6cda0.png">
> 
> Anyway, from my side this issue is resolved and the ticket can be closed. Thank you for your help!

Hello, I'm facing the same problem as you with TraceableFirewallListener, despite I'm using JWT in stateless manner, secured requests that embed a Bearer in the HTTP headr (Authorization) take 20 sec !

How did you manage your configuration to solve the problem ?

I've created a ticket in the LexikJWTAuthenticationBundle project as I was suspecting the bundle => [https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1162](url)

Thanks in advance.
Mehdi
