### ISSUE TITLE
UsageTrackingTokenStorage deprecation is Security.php

### ISSUE THREAD

**Issue by r3dge** [symfony/symfony#43042]
**Symfony version(s) affected**: 5.3.7

**Description**
After using $security->getUser() in a service as mentioned in the documentation ([https://symfony.com/doc/5.4/security.html#a-fetching-the-user-object](url)) i get a deprecation warning : 

"Since symfony/security-core 5.3: Using "Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage" (service ID: "security.token_storage") outside the request-response cycle is deprecated, use the "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage" class (service ID: "security.untracked_token_storage") instead or disable usage tracking using "disableUsageTracking()""

**How to reproduce**

To reproduce this issue, create a service that use Security and call $security->getUser() : 

`use Symfony\Component\Security\Core\Security;

class MyService{

    private $security;

    public function __construct(Security $security){
        $this->security=$security;
    }

    public function myFunction(){
        $user = $this->security->getUser();
    }

}`

**Possible Solution**

I find out that Security.php of the core security component is using a deprecated service : 

`
public function getToken(): ?TokenInterface
    {
        return $this->container->get('security.token_storage')->getToken();
    }
`

As mentioned in the deprecation notice it seems that the service "security.token_storage" should be replaced by "security.untracked_token_storage".

Thanks for your feedback !

**Comment by mbabker** [comment]
When are you calling this helper?  Looking at the deprecation, it only gets triggered if `$container->get('request_stack')->getMainRequest()` returns null, which would mean something is calling the token storage before a request is set in the stack.

**Comment by r3dge** [comment]
This service is basically called in a controller before to create a view.

**Comment by chalasr** [comment]
Can you provide [a reproducer](https://symfony.com/doc/current/contributing/code/reproducer#reproducing-complex-bugs)? We will need that to help.

**Comment by r3dge** [comment]
I guess i have found the issue. The Security service is called from a kernel event listener (kernel.terminate) and not only from a simple service.
The purpose of this listener is to save informations from user-agent request header (browser, os etc...) for each request. Is there a best practice to do that ?

**Comment by stof** [comment]
use the untracked storage in that listener

**Comment by r3dge** [comment]
could you please provide some details to do that ? thank u

**Comment by stof** [comment]
Use the `security.untracked_token_storage` service, as explained in the error message that you pasted in your issue.

**Comment by r3dge** [comment]
The container is not injected in this listener. So i can't access to security.untracked_token_storage from this listener.
I don't see how to do that.

**Comment by r3dge** [comment]
Workaround found.

1. Inject TokenStorageInterface in the listener constructor : 

`    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }`

2. Disable Usage Tracking before to get token

`public function onKernelTerminate(TerminateEvent $event)
    {
            $this->tokenStorage->disableUsageTracking();
            $token = $this->tokenStorage->getToken();
}`

3. Get user

`$user = $token->getUser();`

Many thanks !

**Comment by jderusse** [comment]
I've got similar deprecation triggered when using the `Symfony\Component\Security\Core\Security` helper outside a request (ie, in a Monolog Processor)

```php
/**
 * Adds user information to a record.
*/
class UserProcessor implements ProcessorInterface
{
    public function __construct(private Security $security) {}

    public function __invoke(array $record): array
    {
        $user = $this->security->getUser();
        if (!$user) {
            return $record;
        }

        if (method_exists($user, 'getUserIdentifier')) {
            $record['username'] = $user->getUserIdentifier();
        } else {
            $record['username'] = $user->getUsername();
        }

        return $record;
    }
}
```

We can not call `disableUsageTracking` because we won't be able to restore the previous state (we don't have `isUsageTracked` method).

The only solution is to inject `security.untracked_token_storage` instead of `security` but this is sad to
- not be able to use the Helper
- having to configure the services manually (no autowire)

**Comment by chalasr** [comment]
I think the helper should handle this case internally: #43235

**Comment by stof** [comment]
I'm wondering whether the helper should handle this, or whether UsageTrackingTokenStorage should instead accept getting a token from it outside request contexts.

**Comment by jderusse** [comment]
> I'm wondering whether the helper should handle this, or whether UsageTrackingTokenStorage should instead accept getting a token from it outside request contexts.

Same feeling for me.. Removing the deprecation (and let the method returning `null`) would work for me

**Comment by chalasr** [comment]
If we can get rid of that notice while keeping the BC layer efficient enough, I'm all for removing it. I'm going to investigate
