### ISSUE TITLE
Form trying to validate null entity from OneToOne relation

### ISSUE THREAD

**Issue by BlueSkunka** [symfony/symfony#43044]
Hello,
I'm not sure if this behaviour is a bug or not but I feel like this is not correct. Hope it's relevant !

**Symfony version(s) affected**: 5.3.*

**Description**
Symfony form trying to validate null object from OneToOne relation. 

I have a parent entity called 'Patient' which contain a property 'Person' which is a non required OneToOne relation with the child entity 'Person'. In PersonType, name property come along with NotBlank constraints. So, i expect that symfony validate my person entity IF person is not null. IF person is null object, validation shouldn't occurs. 
When I try to submit with a null person, symfony return the error message from NotBlank constraint while person entity is null. 

**How to reproduce**
https://github.com/BlueSkunka/SF_TEST
Clone this repository or initiate a new project --full with 2 entities:
Patient [string $name, Person person] (Person relation is OneToOne and can be null)
Person [string $name]

Then create form for both entities. Add a NotBlank constraints on Person.name. In PatientType, define person with PersonType::class. 

Little plus, person should be oprhanRemoval if patient.person is set to null.

Create or edit a patient. Before submit, remove person. Symfony will return form with error message. 

**Possible Solution**
I think about 3 possible solutions:
- New feature which tell symfony to not validate a null object (my favorite solution)
- Modifying OneToOne relation to OneToMany relation with 'allow_add' & 'allow_delete' set as true (solution I'll use in my context)
- Using an hidden field which with dynamic value set by js script when I click on a "Remove person" button  (I think it's not the best way as it force to add logic in controller)

In my opinion, symfony should not try to validate a null object if it can be null.

I hope this issue is relevant, 
thanks for any feedback !

**Comment by yceruto** [comment]
> New feature which tell symfony to not validate a null object (my favorite solution)

Setting `'allowNull' => true` in your [`NotBlank` constraint](https://github.com/BlueSkunka/SF_TEST/blob/main/src/Form/PersonType.php#L21) does solve the issue?

**Comment by BlueSkunka** [comment]
#

> Setting `'allowNull' => true` in your [`NotBlank` constraint](https://github.com/BlueSkunka/SF_TEST/blob/main/src/Form/PersonType.php#L21) does solve the issue?

I added `'allowNull' => true` which dosen't trigger the NotBlank constraint but $patient->person is not set to null so I got an SQL error telling me that 'name' field can't be null in person table. 

> An exception occurred while executing 'UPDATE person SET name = ? WHERE id = ?' with params [null, 1]:

As Person fields are not submitted in form data, shoudn't be Patient->Person set to null ? 

If I create a new patient without person relation, it save my patient in db with a relation to a new and empty person entity while Patient->Person should be null and empty Person statement shouldn't be created. Same thing when I edit a patient, the relation is kept but person entity is empty and should be removed. 

`'allowNull' => true`  does not the trick :/

**Comment by xabbuh** [comment]
The issue is that you define the constraints on your form fields. If you move them to your entities, everything works as expected as far as I can see. I am going to close here as I don't see anything wrong, but please feel free to comment if you do not agree and we can reconsider.

**Comment by BlueSkunka** [comment]
It's maybe roughly stated but here how I see my problem and why I think it's, maybe not a bug but at least something that could evolve. 

Symfony trying to validate a null object from oneToOne relation which can be null. 

Even if I can put the person properties into my patient entity, I can't do that for every person relation that my patient may have (doctor, guardianship, wife/husband, ....).

Since the relation is nullable, why Symfony try to validate the person entity if it is null ? 

To me, if the person form fields are not sent in request, no validation should be done on the object (as it is defined as nullable=true), even remove the person in database if cascade"remove" is set, but should validate it only if the fields are sent in request even if they're all null.

Finally, maybe my request is not a bug but a new feature ? Idon't know !

I hope my english is good enough to be understood. 
Thanks.

**Comment by xabbuh** [comment]
You don't need to move properties around. It's sufficient enough to not use the `constraints` option in the form types, but to define the constraints on your model instead.
