### ISSUE TITLE
PostgreSqlStore breaks Sentry usage due to hard-coded instanceof checks.

### ISSUE THREAD

**Issue by FractalizeR** [symfony/symfony#43048]
PostgreSqlStore of any version up to 6.0 has a hard-coded switch in it's code [here](https://github.com/symfony/lock/blob/5.3/Store/PostgreSqlStore.php#L260):
```switch (true) {
                case $driver instanceof \Doctrine\DBAL\Driver\PDOPgSql\Driver:
                case $driver instanceof \Doctrine\DBAL\Driver\PDO\PgSQL\Driver:
                    break;
                default:
                    throw new InvalidArgumentException(sprintf('The adapter "%s" does not support the "%s" driver.', __CLASS__, \get_class($driver)));
            }
```

So you just get an exception "The adapter "Symfony\Component\Lock\Store\PostgreSqlStore" does not support the "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" driver." when using Sentry with PostgreSqlStore.

There is a similar issue with Symfony cache [here](https://github.com/symfony/symfony/pull/42011). Filed Sentry issue here also: https://github.com/getsentry/sentry-symfony/issues/558

**Comment by Jean85** [comment]
Confirmed. This is a general problem when relying on DBAL drivers. To be forward compatible with DBAL 3 and to support driver decoration, we should always rely on `getDatabasePlatform()` as in https://github.com/symfony/symfony/pull/42011/files#diff-a508f4ce64bb6d2ab3c496c220fb866aade4e777a464817576f4be0bed306b4dR451-R458

**Comment by chalasr** [comment]
PR welcome

**Comment by Jean85** [comment]
Opened #43281.
