### ISSUE TITLE
Make function existence deterministic in Twig `AppExtension`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#43067]
**Description**
I'm just forwarding what @ondrejmirtes told me at https://github.com/phpstan/phpstan/issues/5640#issuecomment-921238545:

Calling `twig_date_format_filter()` in `App\Twig\AppExtension` *sometimes* leads to phpstan reporting

> Function twig_date_format_filter not found

... and sometimes it doesn't ;-)

**Comment by ondrejmirtes** [comment]
This can usually be solved by separating functions into their own files and putting those files into Composer's `autoload.files` section.

**Comment by fabpot** [comment]
Looks like it should be discussed in the Twig repository.
