### ISSUE TITLE
[Yaml] PAD(\xc2\x80) is not  escaped when Yaml::dump

### ISSUE THREAD

**Issue by sen-higa** [symfony/symfony#43102]
**Symfony version(s) affected**: 5.2.1

**Description**

PAD(\xc2\x80) was not escaped when execute Yaml::dump.
According to [yaml specifications](https://yaml.org/spec/1.2/spec.html), PAD should be escaped.

**How to reproduce**

```php
use Symfony\Component\Yaml;
// give PAD character to Yaml::dump param
file_put_contents('x80.yml', Yaml::dump(""));
```

x80.yml contains unescaped PAD character.

**Possible Solution**

Add "PAD"(\xc2\x80) to escape characters list, and escape when Yaml::dump.

**Comment by xabbuh** [comment]
Can you please fork the Symfony code and create a failing test case? I will happily look into how to fix it then.

**Comment by sen-higa** [comment]
I added PAD to escape sequences pattern.
`testEscapedEscapeSequencesInQuotedScalar()` is fail by this change.
https://github.com/sen-higa/symfony/compare/5.4...ebae00aa3c0e59cc26a7c95c96ef904845df2279

```
% ./phpunit src/Symfony/Component/Yaml/Tests/DumperTest.php --filter testEscapedEscapeSequencesInQuotedScalar
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing Symfony\Component\Yaml\Tests\DumperTest
...............F.....                                             21 / 21 (100%)

Time: 00:00.042, Memory: 10.00 MB

There was 1 failure:

1) Symfony\Component\Yaml\Tests\DumperTest::testEscapedEscapeSequencesInQuotedScalar with data set "pad" ('', '"\x80"')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'"\x80"'
+''
```

I wrote "\x80" but to exact, PAD character was "\xc2\x80".

**Comment by xabbuh** [comment]
I have checked this back and forth but I cannot find the part of the specs that demands the pad to be escaped. Can you point me to that specific part of the specs?
