### ISSUE TITLE
Warning: ob_end_flush(): Session ini settings cannot be changed after headers have already been sent

### ISSUE THREAD

**Issue by yoshiakiokuma** [symfony/symfony#43131]
**Symfony version(s) affected**: 4.4

**Description**
Warning: ob_end_flush(): Session ini settings cannot be changed after headers have already been sent in /usr/local/rms/agency/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Response.php on line 1239

**How to reproduce**
php.ini is untouched after installed. Nothing is changed.  We are now seeing this warning on all symfony pages.

**Possible Solution**
no ideas.  We have tried all versions of Component/HttpFoundation without security issues.

**Additional context**

**Comment by GromNaN** [comment]
Can you get the stack trace of the warning ?
This may happen if an other error occurs early in the app run.
