### ISSUE TITLE
Problems with \Symfony\Component\Cache\Adapter\ApcuAdapter in cli

### ISSUE THREAD

**Issue by melihovv** [symfony/symfony#43130]
**Symfony version(s) affected**: >=4.4 and even some versions <4.4

**Description**
In our environment we have apcu enabled only in web, in cli it is disabled. Corresponding ini values
```
apc.enable_cli => Off => Off
apc.enabled => On => On
```
But \Symfony\Component\Cache\Adapter\ApcuAdapter returns true from isSupported method in this case. That leads to problem that \Symfony\Component\PropertyAccess\PropertyAccessor::createCache returns ApcuCache instead of NullAdapter. In result we have ApcuAdapter and PropertyAccessor, that work in web but don't work in cli.

**How to reproduce**
See previous section

**Possible Solution**
Change this
```php
    public static function isSupported()
    {
        return \function_exists('apcu_fetch') && filter_var(ini_get('apc.enabled'), \FILTER_VALIDATE_BOOLEAN);
    }
```
to this
```php
    public static function isSupported()
    {
        if (PHP_SAPI === 'cli' && !filter_var(ini_get('apc.enable_cli'), \FILTER_VALIDATE_BOOLEAN)) {
            return false;
        }

        return \function_exists('apcu_fetch') && filter_var(ini_get('apc.enabled'), \FILTER_VALIDATE_BOOLEAN);        
    }
```
But after I've written it I realized that it will break usage of apcu in web too, because container is built in cli.
The only possible solution for us is `ini_set('apc.enabled', 0)` in bin/console, isn't it? No, ***, it will break web too, because `php bin/console cache:warmup` will be affected too.

The only solution is not to use PropertyAccessor in cli, am I right?
Or another idea is to call \Symfony\Component\PropertyAccess\PropertyAccessor::createCache dynamically by demand, not when container is built.

**Additional context**
-

**Comment by nicolas-grekas** [comment]
Why is this an issue? In your setup, on the CLI, `ApcuAdapter` should be functionally equivalent to `NullAdapter`, so that all this won't matter.

**Comment by melihovv** [comment]
@nicolas-grekas yeah, it does not hurt our app, because PropertyAccessor or ApcuAdapter is not used anywhere in our app. In symfony PropertyAccessor is used only symfony/security-http component, which is usually run in web, if I'm right.

The only case in which we have problem is in our healthcheck cli command, which we wrote ourselves. We take all services with tag cache.pool and for each we try to save dummy data to cache.
```php
                $item = $this->connection->getItem(static::CACHE_SERVICE_CELL);
                $item->set(time());
                $this->processResult($event, $this->connection->save($item));
```
And $this->connection->save() in cli returns false but in web returns true when $this->connection is ApcuAdapter.

I think we should patch this bug in our healthcheck command, because I don't see good solution how to fix this in symfony. Maybe do you see? :)

**Comment by nicolas-grekas** [comment]
In Symfony, things are working as expected :)
The way we work around this issue is by wrapping the `ApcuAdapter` in a `ChainAdapter`
See eg `AbstractAdapter::createSystemCache()`
I'm closing here since there is no bug.
