### ISSUE TITLE
AuthorizationChecker has no way configuring $exceptionOnNoToken parameter

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#43141]
**Symfony version(s) affected**: 5.3.7

**Description**
AuthorizationChecker.php has a constructor parameter $exceptionOnNoToken. This is not configurable via security.yaml

I found this issue by having a Guard authenticator and wanted to call isGranted('X', $obj); because at this stage of the guard no token exists it fails. I wanted to set that to false but can't seem to.

**How to reproduce**

Not sure, its a lack of an option in security-bundle/Resources/config/security.php

```
    $container->services()
        ->set('security.authorization_checker', AuthorizationChecker::class)
            ->public()
            ->args([
                service('security.token_storage'),
                service('security.authentication.manager'),
                service('security.access.decision_manager'),
                param('security.access.always_authenticate_before_granting'),
            ])
```

**Possible Solution**

If this is legit oversight, I'm happy to submit a PR adding a parameter/config and passing it through. I  was just surprised  so not sure if its intentional

**Comment by chalasr** [comment]
Not making it configurable is on purpose. 
This parameter is part of a compatibility layer between Guard and the new authenticator system. 
When using the new authenticator system, the argument value is set to `false` by some compiler pass or SecurityBundle DI extension. And it will take `false` as default and only accepted value in 6.0. 

Guard is deprecated in favor of that new system in 5.3 and removed in 6.0, you should consider migrating your authenticators. 
As a nice side effect you won't get the exception once they have been migrated, though I don't know if calling `isGranted() from your authenticator makes sense :)

**Comment by gnat42** [comment]
Thanks @chalasr I figured there was a reason but wanted to make sure but couldn't find any. Thanks for the explanation
