### ISSUE TITLE
Add Attribute::IS_REPEATABLE to Security PHP attribute

### ISSUE THREAD

**Issue by bastien70** [symfony/symfony#43186]
It would be nice to be able to add the '`Attribute :: IS_REPEATABLE`' flag to the PHP attribute **Security**.

This is useful when we have several cases to deal with different error messages.

**Comment by xabbuh** [comment]
Should this be reported to the SensioFrameworkExtraBundle which provides [this attribute](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/src/Configuration/Security.php)?

**Comment by stof** [comment]
Indeed, this is the wrong issue tracker.

@bastien70 this suggestion makes sense (the annotation can be used multiple times), so I suggest you to open a PR on the bundle.
