### ISSUE TITLE
Add test cases for checking of concrete translations according to labels

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#43182]
[The function “testLabel” is provided](https://github.com/symfony/symfony/blob/0e133be367bd479534127a5ab1675553e173f75c/src/Symfony/Component/Form/Tests/AbstractLayoutTest.php#L145 "Function implementation") by the class “AbstractLayoutTest”.
I suggest to add corresponding test classes which will check the concrete application of translations for known labels.
Will these system checks [improve the software quality](https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1632397750230500?thread_ts=1632394218.225500&cid=C3EQ7S3MJ "Clarification attempt from 2021-09-23") then?

**Comment by xabbuh** [comment]
I am not sure I understand what concrete changes you have in mind. Would you mind opening a PR with a draft of your idea?

**Comment by elfring** [comment]
I just propose to distinguish better between abstract and concrete test cases (also for data processing according to translations).
:crystal_ball: How do the possibilities look then for the discovery of unexpected software behaviour?

**Comment by xabbuh** [comment]
I am closing here as you still refuse to give concrete examples or answer our questions.

Frankly spoken: If you do not stop waisting our time, I will close your future tickets without any comments. We have better things to do.

**Comment by elfring** [comment]
>… you still refuse to give concrete examples …

I referenced previous application examples.
:point_right: Would you find [a contribution](https://github.com/liarco/markus-test/commit/ac14bdc4c4c5351b0254cb5ce0bdee2ab824069e#diff-6c5e425fddffe6daa34474ada97db61c49149dc5cd0a89227ebd70675ae740c6R11 "Basic form translation test") from @liarco helpful for this issue?
