### ISSUE TITLE
audit-trail workflow configuration in xml not working

### ISSUE THREAD

**Issue by temp** [symfony/symfony#43194]
**Symfony version(s) affected**: 5.3.7

**Description**
Using the xml-example from https://symfony.com/doc/current/workflow.html#creating-a-workflow throws errors.
```
 Unable to parse file "/app/config/packages/workflow.xml": [ERROR 1871] Element '{http://symfony.com/schema/dic/symfony}audit-trail': This element is not expected. Expected is one of ( {http://symfony.com/schema/dic/symfony}initial-marking, {http:
  //symfony.com/schema/dic/symfony}marking-store, {http://symfony.com/schema/dic/symfony}support, {http://symfony.com/schema/dic/symfony}event-to-dispatch, {http://symfony.com/schema/dic/symfony}place, {http://symfony.com/schema/dic/symfony}transit
  ion, {http://symfony.com/schema/dic/symfony}metadata ). (in /app/ - line 11, column 0) in /app/config/packages/workflow.xml (which is being imported from "/app/src/Kernel.php").
```

**How to reproduce**
Use the xml-example workflow.xml from https://symfony.com/doc/current/workflow.html#creating-a-workflow

**Possible Solution**
-

**Additional context**
Maybe the audit-trail config is simply missing from the xsd?

**Comment by stof** [comment]
@temp it is indeed missing in the XSD. Do you want to submit a PR adding it ?

**Comment by temp** [comment]
@stof Yes, can do!

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue. Please guide me further on what needs to be done ^_^

**Comment by temp** [comment]
> Hi, I would like to work on this issue. Please guide me further on what needs to be done ^_^

Oh, sorry, did see your comment only after I submitted the PR.
