### ISSUE TITLE
[Validator] Custom Validation Constraint

### ISSUE THREAD

**Issue by marcoiosif** [symfony/symfony#43192]
Hello

https://symfony.com/doc/5.2/validation/custom_constraint.html#creating-the-validator-itself

I have followed the steps of the documentation for creating a custom validation constraint, but i give the next error:

`Argument 2 passed to Symfony\Component\Validator\Mapping\ClassMetadata::addPropertyConstraint() must be an instance of Symfony\Component\Validator\Constraint, instance of App\Validator\HelloValidator given, called in...`

My Validator:

```
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class HelloValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        
    }
}
```

My Entity

```
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use App\Validator\HelloValidator;
..................
class User {
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

..................
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('email', new HelloValidator());
    }
}
.............
```

Thanks

**Comment by norkunas** [comment]
You should pass the `Hello` constraint not the validator itself as the HelloValidator should handle constraint and build violations :)

**Comment by marcoiosif** [comment]
Thanks, my mistake. I should have created a constraint before.
