### ISSUE TITLE
Upgrade from v4.4.30 to v4.4.31 fails

### ISSUE THREAD

**Issue by lowwa132** [symfony/symfony#43216]
**Symfony version(s) affected**: 4.4.31

**Description**

**How to reproduce**
Execute `./composer.phar update symfony/*`
Output:
Script cache:clear returned with error code 255

**Additional context**
![image](https://user-images.githubusercontent.com/3715048/135059504-9599c4d7-b791-432b-be8a-ca3937bb777c.png)

**Comment by derrabus** [comment]
Duplicate of #43212
