### ISSUE TITLE
Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony#43218]
**Symfony version(s) affected**: 5.3.8

**Description**

After upgrading from v5.3.7 to v5.3.8 the following errors occurs:

    Class "Symfony\Component\Mailer\EventListener\EnvelopeListener" used for service "mailer.envelope_listener" cannot be found.

called from **RegisterListenersPass.php (line 143)** 

**Possible Solution**
EnvelopeListener.php file should be moved to EventListener folder.

**Comment by gjuric** [comment]
It looks like we posted at the same time, duplicate of #43217 but since this one proposes a solution I am not going to close it.

**Comment by derrabus** [comment]
Duplicate of #43212
