### ISSUE TITLE
symfony/messeger - wrong namespace - Symfony\Component\Messenger\Middleware\MiddlewareInterface

### ISSUE THREAD

**Issue by szepczynski** [symfony/symfony#43221]
**Symfony version(s) affected**: 5.3.8

**Description**
Hi,

After upgrade to 5.3.8 from 5.3.7 I'm started getting an error:

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#54
!!    #message: """
!!      Attempted to load interface "MiddlewareInterface" from namespace "Symfony\Component\Messenger\Middleware".\n
!!      Did you forget a "use" statement for "Sentry\SentryBundle\Tracing\Doctrine\DBAL\Compatibility\MiddlewareInterface"?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php"
```

I checked and found that MiddlewareInterface is located in ./vendor/symfony/messenger/MiddlewareInterface.php but the namespace is "Symfony\Component\Messenger\Middleware". I guess that this middleware should be moved into Middleware subdirectory

**Comment by icanhazstring** [comment]
Duplicate to #43212

**Comment by derrabus** [comment]
Duplicate of #43212
