### ISSUE TITLE
Composer install or update not working anymore   Class "Symfony\Component\Translation\Loader\ArrayLoader" not found

### ISSUE THREAD

**Issue by naifalshaye** [symfony/symfony#43226]
**Symfony version(s) affected**: 

**Description**

Composer install or update not working anymore   Class "Symfony\Component\Translation\Loader\ArrayLoader" not found

**How to reproduce**
composer install or composer update

**Possible Solution**

**Additional context**

**Comment by tseho** [comment]
Already reported here: https://github.com/symfony/symfony/issues/43212

**Comment by derrabus** [comment]
Duplicate of #43212

**Comment by phil-davis** [comment]
See comment https://github.com/symfony/symfony/issues/43212#issuecomment-929029937

They know about the problem and a fix is coming.
