### ISSUE TITLE
[DoctrineBridge] [Validator] UniqueEntityValidator should limit the retrieved entities to `2` to avoid potential memory issues with `broad` queries

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#43254]
**Symfony version(s) affected**: 4.4.* and 5.3.*

**Description**
It isn't that huge an issue because the validator isn't supposed to be use in this way but in theory it would be possible to check uniqueness against a property that isn't strictly unique, e.g. due to old imported data.

This means that the validator could retrieve all those entities. However, in order to determine uniqueness it is enough to retrieve at max `2` as there are only these scenarios possible:

- Count `> 1`: Definitely not unique
- Count `< 1` (`= 0`): Definitely unique
- Count `= 1`: Check if fetched entity is equivalent to current.

So there is no reason to retrieve more than `2` and as it is a simple change, I think it should be added.

**Comment by xabbuh** [comment]
Sounds reasonable to me. As this looks like a performance improvement to me a PR should be opened against the `5.4` branch.

@AndreasA Up to give it a try?

**Comment by AndreasA** [comment]
@xabbuh I can't guarantee that I will find the time but I will try to create a PR next week. It should be rather straight forward.
Testing the performance/memory improvement might be more tricky though. However, I guess as long as the existing tests still work as they do currently, it should be fine?

**Comment by fabpot** [comment]
No need to test the performance change for this change IMHO.

**Comment by AndreasA** [comment]
OK. Great. I hope I will find time this week but can't guarantee it. Sadly, I didn't find time the last two weeks.

**Comment by AndreasA** [comment]
@fabpot @xabbuh 

One remaining question though. How dynamic does it need to be? because supporting it for the `findBy` method is simple but if one uses a custom method, it will be more tricky as we do not know which parameter is the limit parameter.

I could only add the limit parameter, if the default method `findBy` is used and if another is used, they should implement it accordingly? Or I could add an option: `additionalParameters` that are added to the function call ?

**Comment by fabpot** [comment]
Let's optimize for the simple and default `findBy` method. If someone uses a custom method, then they should optimize the query themselves (we might add a note in the docs about it though).

**Comment by xabbuh** [comment]
I agree with @fabpot.

**Comment by AndreasA** [comment]
Created a PR now (for docs and symfony). Hopefully I did everything correctly, first symfony PR. However, one integration test is failing but it shouldn't be related to my PR at all (MemcacheAdapter)?
