### ISSUE TITLE
[Bug][PhPUnit] Memory leak since 4.4.20

### ISSUE THREAD

**Issue by joshlopes** [symfony/symfony#43274]
**Symfony version(s) affected**: 4.4.20...4.4.32

**Description**
I'm having a problem with 4.4.20 up to the latest version, since version 4.4.20 that my tests stopped running completely due to memory leak. It works on 4.4.19 but not on 4.4.20. Do you have any idea what might be causing this?

**How to reproduce**
Not sure what is causing the issue.

**Possible Solution**
Not sure.

**Additional context**

> PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 2013265952 bytes) in /var/www/vendor/phpspec/prophecy/src/Prophecy/Util/ExportUtil.php on line 178

**Comment by wouterj** [comment]
Hi! The description as it is isn't really helpful for debugging the issue unfortunately. I would say there are many applications using 4.4.20 without issues, so there probably is something different for your application that causes issues.

Please try to find what is causing the issue, for instance by using a PHP profiler (e.g. https://www.blackfire.io/) and by creating a [minimal reproducible example](https://symfony.com/doc/current/contributing/code/reproducer.html).

**Comment by joshlopes** [comment]
@wouterj we could put in other words, is something my application might be doing (maybe because is a monolith and we have massive tests!) and something has changed in that version that is causing the memory leak. I guess I was hoping that looking at the versioning someone could point me the culprit... 

Maybe this: https://github.com/symfony/symfony/pull/40067/files  ? But is a fix deprecation warning could that be a reason?

Sorry for the ping @nicolas-grekas -- but could this be the problem for me ?

**Comment by nicolas-grekas** [comment]
Maybe, or maybe not... I'm sorry but there is nothing actionable here.

**Comment by wouterj** [comment]
E.g. you  can try reverting that code locally in your vendor directly and run your tests again. If the memory issue is fixed, you know that's where you need to debug for the memory leak. If the memory issue isn't fixed, it was not the issue causing the memory leak.

**Comment by joshlopes** [comment]
@wouterj @nicolas-grekas i found the issue, it was a `->shouldBeCalled()` on the logger, the console now throws a `->critical()` and i was expecting a `->error()` not really sure why it goes on madness and eats all the memory. Anyway I guess it changed somewhere the console / logger using ->critical instead error, and I guess it's a Prophecy issue not really Symfony's, as instead being able to handle the test / error properly it goes on loop and eats all memory. 

Many thanks both of you for fast reply.
