### ISSUE TITLE
[HttpFoundation] Deprecate session.upload_progress.* and url_rewriter.tags as valid configuration options.

### ISSUE THREAD

**Issue by kafene** [symfony/symfony#43284]
**Description**
While perusing the source of HttpFoundation on this beautiful Friday evening, I noticed that it permits configuration of the `session.upload_progress.*` and `url_rewriter.tags` ini settings.

In the case of `session.upload_progress.*` - [these are `PHP_INI_PERDIR` options](https://www.php.net/manual/en/session.configuration.php) and can not be configured at runtime with `ini_set`. Future Symfony versions should drop them as valid session options.

In the case of `url_rewriter.tags` - [the PHP docs note](https://www.php.net/manual/en/outcontrol.configuration.php#ini.url-rewriter.tags) that as of PHP 7.1.0, it is no longer used for session configuration and that setting is now `session.trans_sid_tags`.

Both the upload_progress and url_rewriter.tags options are [still present in the 6.0 branch](https://github.com/symfony/http-foundation/blob/f246732cbd2c0296d86db7e1d652864e31b1d1b1/Session/Storage/NativeSessionStorage.php#L346), so I'm suggesting that they be deprecated.

**Example**

    > php -n -d'extension=readline.so' -d'session.upload_progress.enabled=On' -a
    Interactive mode enabled

    php > var_dump(ini_get('session.upload_progress.enabled'));
    string(1) "1"
    php > var_dump(ini_set('session.upload_progress.enabled', '0'));
    bool(false)
    php > var_dump(ini_get('session.upload_progress.enabled'));
    string(1) "1"

**Comment by fabpot** [comment]
@kafene Would you like to work on a PR deprecating these settings in 5.4 so that we can remove them in 6.0?

**Comment by kafene** [comment]
@fabpot I would be happy to.
