### ISSUE TITLE
Include blocks

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#43288]
**Description**
This is a proposal to pass Twig content inline via **blocks** embedded inside the **include** tag. The goal is to promote component architecture and code reuse by passing rich Twig-enabled markup to included templates inline, without having to produce concrete variants using separate files and the _extends_ tag.

Twig's current handling of reuse is a bit confused given that it provides both an [include tag](https://twig.symfony.com/doc/3.x/tags/include.html) and an [include function](https://twig.symfony.com/doc/3.x/functions/include.html). The presence of the latter seems to obviate the need for the former, and as such, the include tag documentation already recommends just using the include function instead. This proposal seeks to take this one step further and immediately deprecate the include tag and repurpose it for Twig v4 according to following specification.

The include tag will now be paired with a closing _endinclude_ tag, akin to most other tags, and its content may only be blocks, similar to a [child template](https://twig.symfony.com/doc/3.x/tags/extends.html#child-template).

**Example**
```twig
{% include 'component/tier.twig' with {active: is_granted('tier1')} only %}
    {% block title -%}
        <h2 class="tier1">Initiate</h2>
    {%- endblock %}
{% endinclude %}
```

**Current solutions**
To see why this proposal is better than the current solutions, consider how this could be implemented today.

1. Passing template content via variables.
```twig
{% include 'component/tier.twig' with {active: is_granted('tier1'), title: '<h2 class="tier1">Initiate</h2>'} only %}
```

This only looks feasible because the markup is short and free from interpolation, but we should imagine the markup could grow to be quite complex, with many substitutions and template function calls, in which case passing markup this way is neither practical nor safe (with respect to escaping).

2. Capturing markup with *set*.
```twig
{% set title -%}
    <h2 class="tier1">Initiate</h2>
{%- endset %}
{% include 'component/tier.twig' with {active: is_granted('tier1'), title: title} only %}
```

This approach is most analogous to what we're trying to achieve, but comes with the caveat that we must declare variables in the wrong (parent) scope in order to forward them to the include scope. Moreover, the code layout with respect to ordering and nesting does not clearly convey what we are trying to achieve compared with this proposal.

**Future extensions**
This proposal is quite similar to [named slots](https://svelte.dev/docs#slot_name) in Svelte. Svelte also provides the [anonymous slot](https://svelte.dev/docs#slot) for components exposing just one markup block. This could also be implemented in Twig by simply omitting the block name, however it is suggested this would be treated as a separate issue since it could be introduced in a backwards-compatible manner at any point in the future after this proposal is accepted.

**Comment by wouterj** [comment]
Hi! This is the issue tracker for the Symfony framework, not for the development of Twig. Please open this issue in https://github.com/twigphp/Twig
