### ISSUE TITLE
HTTP Status message changes in www.iana.org result in failed tests

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#43292]
Affected Symfony Versions: All (?)

Two HTTP Status messages have been changed in:

https://www.iana.org/assignments/http-status-codes/http-status-codes.xml

which is dynamically loaded in tests and results in 2 failed ones:

- 413 from `Payload Too Large` to `Content Too Large`
- 422 from `Unprocessable Entity` to `Unprocessable Content`

How is this handled? Will there be a change to the tests or the message?

**Comment by simonberger** [comment]
Changes applied in draft 14
https://www.ietf.org/rfcdiff?url2=draft-ietf-httpbis-semantics-14.txt&url1=draft-ietf-httpbis-semantics-13.txt

**Comment by nicolas-grekas** [comment]
PR welcome :)

**Comment by simonberger** [comment]
I can do that I just don't know what. Can the status messages be changed? Isn't that part of BC?
