### ISSUE TITLE
[Profiler] Show number of hydrated Doctrine entities

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony#43307]
**Description**

In a current project, we try to enhance the database performance by lowering the number of hydrated entities (besides other optimizations). To quickly see whether this worked or not, we would like to see the number of hydrated entities in the Profiler, just like the number of queries and their execution time is gathered.

I'd love to hear your opinion about this. Did I configure something wrong, such that it is already implemented somewhere? Is this too complex to be handled? Or did nobody think about this before?

**Comment by stof** [comment]
This is related to this ticket in DoctrineBundle: https://github.com/doctrine/DoctrineBundle/issues/109 (it is about collecting timing for hydration, not counting the entities, but both need the same kind of extension points in the ORM). The ORM does not have the necessary extension point to hook the Symfony toolbar into the ORM hydration.

I'm closing this ticket as symfony/symfony is the wrong issue tracker for the Doctrine integration.
