### ISSUE TITLE
[Preloading] Multiple "can't preload already declared class"

### ISSUE THREAD

**Issue by melkamar** [symfony/symfony#43308]
**Symfony version(s) affected**: 5.3.6

**Description**

After enabling [preloading](https://symfony.com/blog/new-in-symfony-4-4-preloading-symfony-applications-in-php-7-4) PHP-FPM throws warnings on startup and crashes on request processing:

```
[04-Oct-2021 14:46:17] NOTICE: PHP message: PHP Warning:  Can't preload already declared class Symfony\Component\Security\Core\User\UserChecker in /xxx/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserChecker.php on line 26

[04-Oct-2021 14:46:17] NOTICE: PHP message: PHP Warning:  Can't preload already declared class Twig_Extension_StringLoader in /xxx/vendor/twig/twig/lib/Twig/Extension/StringLoader.php on line 11

NOTICE: PHP message: PHP Warning:  Cannot declare class Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatement, because the name is already in use in /xxx/vendor/sentry/sentry-symfony/src/aliases.php on line 93

NOTICE: PHP message: PHP Fatal error:  Cannot redeclare Amp\Process\escapeArguments() (previously declared in /home/rohea/pace-qa/vendor/amphp/process/lib/functions.php:30) in /xxx/vendor/amphp/process/lib/functions.php on line 30
```

**Additional context**

I have checked the internet for suggestions and saw [this issue](https://github.com/symfony/symfony/issues/39961) - judging by the state of it and the version of Symfony we are using, I thought this should be fixed, but I'm still encountering issues.

We are still using the pre-Flex Symfony directory structure (and depend on the `symfony/symfony` package). From the issue above it sounds it's _recommended_ to refactor, but not _required_.  Is my understanding correct, or do we have to refactor in order to get preloading to work?

Additionally, for the notices/errors about non-Symfony classes - are those errors caused by some Symfony or PHP configuration, or do they need to be fixed in the libs themselves (and thus are blockers for using preloading)?

**Comment by nicolas-grekas** [comment]
Such preloading notices can be ignored, they're only informative.
