### ISSUE TITLE
BC Break when using Redis transport with an empty username

### ISSUE THREAD

**Issue by alexsegura** [symfony/symfony#43306]
**Symfony version(s) affected**: 5.3.8

**Description**

I'm using Symfony Messenger with Redis transport (it's Redis 5.x), and when upgrading `symfony/redis-messenger` 5.3.8, my current setup is broken. 

The errors are: 

```
Symfony\Component\Messenger\Exception\InvalidArgumentException
Redis connection failed: ERR wrong number of arguments for 'auth' command
```

```
ErrorException
Warning: Redis::auth() expects parameter 1 to be string, array given
```

---

It **used to work** with the following configuration:

```
MESSENGER_TRANSPORT_DSN="redis://:password@host/messages/symfony/consumer"
```

There are some changes between 5.3.7 and 5.3.8 that might explain the bug 

https://github.com/symfony/redis-messenger/compare/v5.3.7...v5.3.8

**How to reproduce**

Configure Redis transport with the following env var: 

```
MESSENGER_TRANSPORT_DSN="redis://:password@host/messages/symfony/consumer"
```

**Comment by alexsegura** [comment]
I confirm that downgrading `symfony/redis-messenger` to 5.3.7 fixes my issue

https://github.com/coopcycle/coopcycle-web/commit/b02ba7a6db20d8e8f1bf90127e7cc6a822f24916

**Comment by n0rbyt3** [comment]
@alexsegura There has been a bug where user AND password authentication was not possible. You only need to remove the colon in your dsn string to fix your problem.

But it's indeed a BC break.
