### ISSUE TITLE
[Serializer] Add a more global interface with all method implement by the implemantation

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#43325]
It's very common in a service to inject the normalizer, and to use `normalize()` or `denormalize()`
However, theses methods does not exist on [`SerializerInterface`](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Serializer/SerializerInterface.php#L17-L38). 

So, if we want to use `normalize()`, `denormalize()`, and `serializer`,we need to inject 3 services: NormalizerInterface, DenormalizerInterface, and SerializerInterface. Not really handy !

To be honest, I always inject the SerializerInterface, because I know methods exists on the implementations. But on every projects, I have to ignore error reported by static analysis. 

So, what do you think of creating an interface that embrace all three others?

---

Side question, with PHP 8.1 we have intersection types, how does behave the containers with the following signature

```php
public function __construct(NormalizerInterface&DenormalizerInterface&SerializerInterface $serializer) ? 
```

**Comment by ro0NL** [comment]
What's the usecase?

**Comment by lyrixx** [comment]
> So, if we want to use normalize(), denormalize(), and serializer,we need to inject 3 services: NormalizerInterface, DenormalizerInterface, and SerializerInterface. Not really handy !

avoid this (or avoid ignoring phpstan error)

**Comment by ro0NL** [comment]
Understood. I meant what usecase requires all 3 services?

Generally I'd prefer wiring an intersection type, rather than introducing a new one.

**Comment by stof** [comment]
> Side question, with PHP 8.1 we have intersection types, how does behave the containers with the following signature

I don't think the DI component supports intersection types yet for autowiring. @nicolas-grekas can you confirm ?

**Comment by nicolas-grekas** [comment]
it doesn't, we never thought about it yet

**Comment by lyrixx** [comment]
> Understood. I meant what usecase requires all 3 services?

you are right, it's not common for all interfaces, but normalizer + denormalizer is common to me. Think about the layer between your data (POPO) and Elasticsearch. You want to normalizer before sending to ES, then denormalize when getting the data back.

We can generalize the use case: it occurs when you want to use the serializer to format the data you send / get from a database (or API, you get the point:) )

You could say: Why not using serialize / deserialize directly: some time, the lib does the json_encode / json_decode on his side.

**Comment by ro0NL** [comment]
+1 for combining normalizers with its counter denormalize part

AFAIK it's the common case: `AbstractNormalizer implements NormalizerInterface, DenormalizerInterface`

**Comment by lyrixx** [comment]
What would be the name of the interface ?

**Comment by ro0NL** [comment]
i'd opt for deprecating DenormalizerInterface, favoring NormalizerInterface. But `NormalizerInterface&DenormalizerInterface` is a valid type also :}, if not cumbersome.

Maybe intersection support in DI is sufficient ...

**Comment by lyrixx** [comment]
Actually, I don't what to do

* :a: wait for PHP 8.1 (`NormalizerInterface&DenormalizerInterface` and support in the DIC)
* :b: make a PR to symfony to deprecate an interface, and add more method to another one. I don't really like it because it will annoy many people.

**Comment by ro0NL** [comment]
Then a new type 🤷

**Comment by lyrixx** [comment]
But I can not find a name :/

**Comment by ro0NL** [comment]
to me normalization comes with de-normalization, hence i think `NormalizerInterface` is the best name. Or both separate as currently :D

NormalizerDenormalizeInterface
Normalizer2Interface

i've no opinion what would be more annoying, a new symbol vs a new method. The latter seems better to discover :shrug:

**Comment by nicolas-grekas** [comment]
I propose #43479 to fix this issue.

**Comment by jdreesen** [comment]
@nicolas-grekas you linked this very issue ;)

**Comment by ogizanagi** [comment]
#43479 is merged, agree to close this one?

**Comment by lyrixx** [comment]
Sure 👍🏼  it'll totally fix my issue. thanks @nicolas-grekas
