### ISSUE TITLE
[BrowserKit] Source nodes are considered as parents in <picture> context

### ISSUE THREAD

**Issue by FabienLegouge** [symfony/symfony#43337]
Hello !

**Symfony version(s) affected**: 5.2.6

**Description**

The parent node of an ```<img>``` tag set at the end of a ```<picture>``` tag is considered to be the previous ```<source>``` node if it was not closed using ```/>```

**How to reproduce**
- This should work :
```html
<picture>
    <source srcset="{{ asset('/test1.webp') }}" type="image/webp" media="(min-width:1000px)">
    <source srcset="{{ asset('/test1.jpg') }}" type="image/jpeg" media="(min-width:1000px)">
    <img src="{{ asset('/test.jpg') }}" alt="test">
</picture>
```
- But the result actually is : 
```php
dd($node->parentNode->nodeName); // => displays "source"
```

**Current fix**
- In order to fix this issue, we currently must close the ```<source>``` by using ```/>```, which should not be the case since the ```<source>``` tag is a tag that is not supposed to contain any child.
```html
<picture>
    <source srcset="{{ asset('/test1.webp') }}" type="image/webp" media="(min-width:1000px)" />
    <source srcset="{{ asset('/test1.jpg') }}" type="image/jpeg" media="(min-width:1000px)" />
    <img src="{{ asset('/test.jpg') }}" alt="test">
</picture>
```
```php
dd($node->parentNode->nodeName); // => displays "picture"
```

**Possible Solution**

A solution would be to handle the ```<source>``` tag as an orphan tag since I guess that the current issue.

**Comment by stof** [comment]
Parsing the HTML is not implemented in BrowserKit. So this is an issue of the underlying parser.

Are you using the PHP native DOM parsing or the [`masterminds/html5`](https://packagist.org/packages/masterminds/html5) parser ? The HTML5 parser is used at 2 conditions:

- the library is installed
- the HTML has the HTML5 doctype

The native PHP parsing using libxml is known to produce issues when writing HTML that relies on HTML5 rules regarding automatic closing of nodes (or omitted nodes)

**Comment by FabienLegouge** [comment]
Hello !

I am using the Browser Kit's default parser which is ```masterminds/html5``` as we can see in the constructor of the ```Symfony\Component\DomCrawler\Crawler``` class : 
```php
// ...
use Masterminds\HTML5;

public function __construct($node = null, string $uri = null, string $baseHref = null)
{
    // ...
    $this->html5Parser = class_exists(HTML5::class) ? new HTML5(['disable_html_ns' => true]) : null;
}
```

Does that mean that it is an issue to report to the ```masterminds/html5``` repository ?

**Comment by xabbuh** [comment]
What about the other two requirements? Do you have `masterminds/html5` installed and does the document being parsed have an HTML5 doctype?

**Comment by stof** [comment]
@FabienLegouge the parsing behavior of the DomCrawler component is not to use `masterminds/html5` all the time. It is only used in some specific conditions, as described in my previous comment.

**Comment by FabienLegouge** [comment]
Yeah alright my bad I didn't read properly.

Since PHP Storm was not highlighting the HTML5 class as non-existant I thought it was but that was not the case.

I successfully installed the ```masterminds/html5``` package and it seems to be working properly now ! Looks like the default parser was the problem as you mentioned (also my HTML was indeed declaring the HTML5 doctype).

My bad for not having searched deep enough before writing this ticket and thanks for fast answering :)

I guess we can close now
