### ISSUE TITLE
[Messenger] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by huzineczerik** [symfony/symfony#43339]
**Symfony version(s) affected**: 3.5.3

**Description**
Hi all!
We have a problem with messenger working. We dont know how to reproduce this because we dont know what causes.
Our sentry reports this error 122 times:
``` 
An exception occurred while executing 'DELETE FROM messenger_messages WHERE id = ?' with params ["432471"]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
```
Ofcourse this id _432471_ is different in every events.

How can I FIX it?

**Comment by lljaworski** [comment]
First of all, try to run on MySQL database command:
`SHOW ENGINE INNODB STATUS;`
The output will contain the section "LATEST DETECTED DEADLOCK", try to catch deadlock with this table (messenger_messages) and check what causing this issue.

**Comment by huzineczerik** [comment]
> First of all, try to run on MySQL database command: `SHOW ENGINE INNODB STATUS;` The output will contain the section "LATEST DETECTED DEADLOCK", try to catch deadlock with this table (messenger_messages) and check what causing this issue.

The LATEST DETECTED DEADLOCK contains:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2021-10-05 19:19:47 0x7f4846a24700
*** (1) TRANSACTION:
TRANSACTION 474857878, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 1090990, OS thread handle 139948388046592, query id 279320219 cloudsqlproxy~[myip] root Creating sort index
SELECT m.* FROM messenger_messages m WHERE (m.delivered_at is null OR m.delivered_at < '2021-10-05 20:19:47') AND (m.available_at <= '2021-10-05 21:19:47') AND (m.queue_name = 'ad') ORDER BY available_at ASC LIMIT 1 FOR UPDATE
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 610 page no 3 n bits 96 index PRIMARY of table `[mydb]`.`messenger_messages` trx id 474857878 lock_mode X locks rec but not gap waiting
Record lock, heap no 23 PHYSICAL RECORD: n_fields 9; compact format; info bits 32
 0: len 8; hex 800000000006f0c1; asc         ;;
 1: len 6; hex 00001c4dc197; asc    M  ;;
 2: len 7; hex 68000001c50531; asc h     1;;
 3: len 30; hex 4f3a33363a5c2253796d666f6e795c5c436f6d706f6e656e745c5c4d6573; asc O:36:\"Symfony\\Component\\Mes; (total 1060 bytes);
 4: len 2; hex 5b5d; asc [];;
 5: len 2; hex 6164; asc ad;;
 6: len 5; hex 99aacb54ee; asc    T ;;
 7: len 5; hex 99aacb54ee; asc    T ;;
 8: len 5; hex 99aacb54ef; asc    T ;;

*** (2) TRANSACTION:
TRANSACTION 474857879, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 1091346, OS thread handle 139948399412992, query id 279320220 cloudsqlproxy~[myip] root updating
DELETE FROM messenger_messages WHERE id = '454849'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 610 page no 3 n bits 96 index PRIMARY of table `[mydb]`.`messenger_messages` trx id 474857879 lock_mode X locks rec but not gap
Record lock, heap no 23 PHYSICAL RECORD: n_fields 9; compact format; info bits 32
 0: len 8; hex 800000000006f0c1; asc         ;;
 1: len 6; hex 00001c4dc197; asc    M  ;;
 2: len 7; hex 68000001c50531; asc h     1;;
 3: len 30; hex 4f3a33363a5c2253796d666f6e795c5c436f6d706f6e656e745c5c4d6573; asc O:36:\"Symfony\\Component\\Mes; (total 1060 bytes);
 4: len 2; hex 5b5d; asc [];;
 5: len 2; hex 6164; asc ad;;
 6: len 5; hex 99aacb54ee; asc    T ;;
 7: len 5; hex 99aacb54ee; asc    T ;;
 8: len 5; hex 99aacb54ef; asc    T ;;
```

**More information**
This project is running in Google App Engine and 2 instances are running currently and theese instances connected to a Google Cloud SQL database.
Supervisor config per instance:

``` 
[program:messenger-worker-ad]
command=php /app/bin/console messenger:consume ad --limit=10 --time-limit=3600 --memory-limit=128M
user=nginx
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
numprocs=5
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
```

What should I try to change?

**Comment by lljaworski** [comment]
check also tip from docs:
"The datetime property of the messages stored in the database uses the timezone of the current system. This may cause issues if multiple machines with different timezone configuration use the same storage."

**Comment by lljaworski** [comment]
Additionally, In my position I will consider using for ex. Rabbit as a transport for concurrent consumers. The database is not a good place to keep complex queues, it is more for simpler usage of Symfony messenger.

**Comment by huzineczerik** [comment]
@lljaworski 
 
Thank you for your idea. We installed the [RabbitMq](https://www.rabbitmq.com/) and changed the messenger transport to amqp and it seems it is working! 

Sorry for the late answer.

**Comment by huzineczerik** [comment]
@lljaworski Now we have other problem with Messenger AMQP transport:

```
Symfony\Component\Messenger\Exception\RejectRedeliveredMessageException
Redelivered message from AMQP detected that will be rejected and trigger the retry logic.
```

This is our messenger.yaml file:
```
framework:
    messenger:
        failure_transport: failed
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            cron:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # queue_name is specific to the doctrine transport
                    queue_name: cron

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async

            ad:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: ad

            smartsync:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: smartsync

            transaction:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: transaction

            failed: 'doctrine://default?queue_name=failed'
```

Do you have any idea how to solve this problem?

**Comment by bertrandseurot** [comment]
Found in RejectRedeliveredMessageMiddleware :

 AMQP redelivers messages when they do not get acknowledged or rejected. This can happen when the connection times out  or an exception is thrown before acknowledging or rejecting. When such errors happen again while handling the  redelivered message, the message would get redelivered again and again. The purpose of this middleware is to prevent  infinite redelivery loops and to unblock the queue by republishing the redelivered messages as retries with a retry  limit and potential delay.

Good luck !

**Comment by huzineczerik** [comment]
Thank you! 
We found the problem and it was not because of the messenger. 
It caused a task which is create some different-size versions from an image. This task uses 100% CPU for a few minutes and it is not friendly for Google App Enginge. We have to find an another way to solve this problem.
