### ISSUE TITLE
[RFC] Make masterminds/html5 a required dependency of dom-crawler

### ISSUE THREAD

**Issue by stof** [symfony/symfony#43341]
**Description**
The DomCrawler has an optional integration with `masterminds/html5` to provide a better parsing of HTML5 (the `DOMDocument::loadHTML` method is based on the HTML4 spec, not the HTML5 one, and so has many issues when using HTML5 features) when the library is available.
Given the frequency of bug reports we get about broken parsing in dom-crawler, I'm wondering whether we should make `masterminds/html5` a required dependency instead of an optional one, so that any HTML using the HTML5 doctype is always parsed using the HTML5 parser.
If the decision is a yes, the next question is which version should do that switch.

What do you think about that ?

**Comment by fabpot** [comment]
If we were to do that, that would be for 5.4.
Another possibility is to keep it optional and throw an exception when not available and parsing an HTML5 content.

**Comment by stof** [comment]
> Another possibility is to keep it optional and throw an exception when not available and parsing an HTML5 content.

that would be worse DX IMO, as I expect most projects are using HTML5 now rather than HTML4 (and we cannot throw the exception only when the DOMDocument parsing is wrong, as that would require detecting that, which would involve parsing things...)

**Comment by nicolas-grekas** [comment]
Do you have commit access to masterminds/html5 @stof? Would it be possible you gain them if not? Before adding a new dependency to a core Symfony component, we need to check if the dep is compatible with our policies.

**Comment by nicolas-grekas** [comment]
Also, won't that make things way slower? Is there a way to take the slow path only when needed? (eg when libxml fails?)

**Comment by fabpot** [comment]
IIRC, @tgalopin also contributed a bit to this lib.

**Comment by lyrixx** [comment]
I confirm the PHP implementation is (was) much slower than the native one. That's why I disabled it in the crawler I built.

However I did not test it with JIT

So if we do that, we must have an option to disable the integration

**Comment by stof** [comment]
> Is there a way to take the slow path only when needed? (eg when libxml fails?)

That's the whole point. libxml does not fail. It still produces a DOM, but not the expected one (see #43337 for the latest issue linked to that, I let you search the issue tracker for more if you want).
A few libxml bugs are easy to detect (libxml stops parsing on `\0` for instance), but most of them are not detectable without parsing AFAICT.

> Do you have commit access to masterminds/html5 @stof? Would it be possible you gain them if not?

I don't have commit access. And if the goal is to have a Symfony core member as a maintainer of that lib to ensure maintenance, I suggest looking for someone else than me. I'm already maintainer on way too many packages to be able to provide proper maintenance level on all of them.

> IIRC, @tgalopin also contributed a bit to this lib.

he did. And he was the one integrating it in DomCrawler.
Note: both of us contributed performance optimization (related to the work integrating it in Symfony). More usage of blackfire on the library might yield more optimizations.

**Comment by stof** [comment]
If the performance difference justifies keeping it opt-in, maybe we need to find a way to make the solution for visible for projects that need to parse HTML5 code using new features, to reduce the need to report issues here to discover it.
Currently, the doc has a small note about it in https://symfony.com/doc/current/components/dom_crawler.html, but I suspect many people use the DomCrawler without reading that page, but only the [testing chapter](https://symfony.com/doc/current/testing.html#application-tests) /cc @symfony/team-symfony-docs

**Comment by ro0NL** [comment]
What if we require the HTML5 parser in runtime, if the doctype tell us so ...

Then we could already start deprecating.

Similar as https://github.com/symfony/symfony/issues/43341#issuecomment-935867089 actually :}

**Comment by stof** [comment]
@ro0NL if the mere presence of the HTML5 doctype requires using the HTML5 library, we would probably make the dependency required for 95% of our users, given that the HTML5 doctype is the recommended doctype since a decade. Forcing users to install the library themselves in such situation instead of requiring it directly would mean annoying 95% of users.

**Comment by ro0NL** [comment]
yet, it's still less annoying than bugs because of an implicit wrong parser.

Im not sure about stats, in that sense we need to account for any non-HTML5 page on the web. I can imagine typically legacy webpages are crawled, due lack of proper APIs.

**Comment by stof** [comment]
@ro0NL the thing is, not all pages using the HTML5 doctype are broken when being parsed with the libxml parser. And @nicolas-grekas's performance concern is related to those cases.

> I can imagine typically legacy webpages are crawled, due lack of proper APIs.

Indeed, in the case of crawling external pages, non-HTML5 doctypes might be more common. When guessing my 95%, I was thinking only about the usage of DomCrawler in the context of tests (alongside BrowserKit), where the tested pages are the ones from the project (and if a project is using Symfony 5.4, there is a low chance that it generates HTML 4 IMO)

**Comment by ro0NL** [comment]
perhaps allow users to opt-out, if they suffer some performance impact. Or opt-in if our guessing is poor :)

**Comment by stof** [comment]
Well, currently, we do the opt-in based on the fact that they installed the library or no.

The hard part about doing an explicit opt-in is the usage with BrowserKit. There, the BrowserKit browser is the one instantiating the Crawler and giving it HTML, which means we would need the opt-in API in BrowserKit too (or we need to refactor the Crawler class entirely so that `addHTML` does not parse the HTML immediately, but only on the first access to the DOM, to give a chance to do a config change before that)

**Comment by ro0NL** [comment]
To me opt-in (either explicitly, or by guessing) means the library is required in runtime. Configuring Crawler thru BrowserKit sounds reasonable IMHO.

```
html5 = config ?? guess_from_doctype();
if html5 and not library then throw
```

**Comment by javiereguiluz** [comment]
Minor comment for your consideration: we shouldn't focus the discussion on slow/fast, because that would only matter if both solutions were equally good. But, apparently, one solution is bad and full of bugs and the other is correct.

**Comment by fabpot** [comment]
I agree with @javiereguiluz.

I think we should prefer correctness over speed.

**Comment by tgalopin** [comment]
Given that HtmlSanitizer [seems to be an interesting new component](https://github.com/symfony/symfony/issues/44144) and that the component rely on this package, I think it makes sense to require this dependency. If we don't, it would mean installing the HtmlSanitizer component may unexpectedly break tests due to the change of parsing behavior.

I guess we could do this in Symfony 6.1?

EDIT: I opened a PR for that, https://github.com/symfony/symfony/pull/44170

**Comment by fabpot** [comment]
Thank you for the PR @tgalopin (6.1 is the right target), closing here.
