### ISSUE TITLE
[HttpFoundation] Invalid phpdoc type

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#43349]
**Symfony version(s) affected**: 5.3.9

**Description**
On class Symfony\Component\HttpFoundation\InputBag,
the return type "array" on phpdoc is missing for function get()

**Comment by nicolas-grekas** [comment]
returning array is deprecated, that's why it's not documented

**Comment by acantepie** [comment]
Thanks for reply, but why its deprecated ? Is this feature will be removed on future ?

**Comment by nicolas-grekas** [comment]
yes: you need to call `->all('the-param')` instead
