### ISSUE TITLE
[HttpFoundation] PHP 8.1 deprecation notice in IpUtils::checkIp()

### ISSUE THREAD

**Issue by W0rma** [symfony/symfony#43350]
**Symfony version(s) affected**: 5.3

**Description**
I stumbled upon the method [`IpUtils::checkIp()`](https://github.com/symfony/symfony/blob/808977847fa40f8323c4c850f8ae6f58cffad754/src/Symfony/Component/HttpFoundation/IpUtils.php#L37):

```php
    /**
     * Checks if an IPv4 or IPv6 address is contained in the list of given IPs or subnets.
     *
     * @param string|array $ips List of IPs or subnets (can be a string if only a single one)
     *
     * @return bool Whether the IP is valid
     */
    public static function checkIp(?string $requestIp, $ips)
    {
        if (!\is_array($ips)) {
            $ips = [$ips];
        }

        $method = substr_count($requestIp, ':') > 1 ? 'checkIp6' : 'checkIp4';

        foreach ($ips as $ip) {
            if (self::$method($requestIp, $ip)) {
                return true;
            }
        }

        return false;
    }
```

`substr_count()` is called even if `$requestIp === null` which causes a warning in PHP 8.1 ("substr_count(): Passing null to parameter #1 ($haystack) of type string is deprecated").

**How to reproduce**

**Possible Solution**
I guess we could just avoid calling `substr_count()` if the request ip is `null`.

**Additional context**

**Comment by W0rma** [comment]
Related to https://github.com/symfony/symfony/issues/41552

**Comment by stof** [comment]
We should also deprecate passing `null` IMO. Before https://github.com/symfony/symfony/pull/33088, it was documented as `@param string $ip`

**Comment by derrabus** [comment]
Would you like to contribute a fix, @W0rma?

**Comment by W0rma** [comment]
Sure, I've just created #43357 to fix the deprecation warning and I will create additional PRs to deprecate/remove the possibility to pass `null` to various methods of `IpUtils`.
