### ISSUE TITLE
Profiler not shown when installing a new symfony full project

### ISSUE THREAD

**Issue by abdounikarim** [symfony/symfony#43365]
**Symfony version(s) affected**: 5.3.9

**Description**
When installing a new project with the next command : 
```bash
symfony new --full my-great-project
```

We don't show the profiler on the home page.

**How to reproduce**
Create a new Symfony Full project and launch the web server.
Even if you install manually the profiler, we don't show it.

**Possible Solution**

**Additional context**

**Comment by javiereguiluz** [comment]
I can confirm this error. It happens because of this bug:

```
[2021-10-11T14:41:35.439431+00:00] request.CRITICAL: Exception thrown when handling an exception
Doctrine\DBAL\Exception\ConnectionException:

An exception occurred in driver: SQLSTATE[08006] [7]
FATAL:  role "db_user" does not exist at my-great-project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 88)
{
  "exception": "[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0):An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  role \"db_user\" does not exist at my-great-project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] FATAL:  role \"db_user\" does not exist at my-great-project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] FATAL:  role \"db_user\" does not exist at my-great-project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)"
  } []
```

Which is caused by this Symfony Flex recipe which is installed by default when creating the project with `--full` and which assumes that you already have a database:

![doctrine-recipe](https://user-images.githubusercontent.com/73419/136810120-23848f0d-1109-4a3c-9785-52bb8bea13af.png)

**Comment by tomrummet** [comment]
What kind of environment are you running?

I have tested with two different environments, one using docker compose and one running Symfony Local Web Server (https://symfony.com/doc/current/setup/symfony_server.html) and profiler is showing up.

**Comment by nicolas-grekas** [comment]
Looks like this is fixed.
