### ISSUE TITLE
PHP 8.0 polyfill: CurlHandle

### ISSUE THREAD

**Issue by dereuromark** [symfony/symfony#43377]
**Description**
When running phpstan over code that is 7.4+, you get
```
        ^Parameter \$ch of method ...\\Http\\Client\\Adapter\\Curl\:\:exec\(\) has        
         invalid typehint type CurlHandle\.$
```         
For
```php
    /**
     * Execute the curl handle.
     *
     * @param resource|\CurlHandle $ch Curl Resource handle
     * @return string|bool
     */
    protected function exec($ch)
    {
```  

I checked https://github.com/symfony/polyfill-php80
but it does not contain yet CurlHandle

We could probably add this stub:
```php
/**
 * @since 8.0
 */
final class CurlHandle
{
    /**
     * Cannot directly construct CurlHandle, use curl_init() instead
     * @see curl_init()
     */
    private function __construct() {}
}
```
maybe with Exception if we cannot make it work as in 8.0, but then 7.x would also allow running phpstan/psalm on that code.

**Comment by derrabus** [comment]
How would this actually help? On PHP 7, you could not use an instance of the "polyfilled" class for any cURL functions.

**Comment by dereuromark** [comment]
As mentioned above this makes tools like PHPStan/Psalm pass without errors.
When the code is PHP8 aware, but the execution happens in the version still supported and 7.x. And therefore those classes do not yet exist.

By adding polyfill we were also able to remove some other issues like
https://github.com/cakephp/cakephp/pull/16015

**Comment by ro0NL** [comment]
Ideally the tool solves it for us :/

https://3v4l.org/odjkY#v7.4.24

**Comment by derrabus** [comment]
Making static analysis tools happy is not the purpose of Symfony's polyfills. This is a false positive of your SA tool.
