### ISSUE TITLE
[Mime] Base64ContentEncoder does not work for streams opened with php://temp

### ISSUE THREAD

**Issue by tomme87** [symfony/symfony#43373]
**Symfony version(s) affected**: 5.3.8

**Description**
`Symfony\Component\Mime\Encoder\Base64ContentEncoder::encodeByteStream` does not create the correct base64 of streams that is created with `\fopen('php://temp', 'r+')` and the content is longer than 3 chars. The last char is always missing.

**How to reproduce**
```php
$txt = '1234';
$resource = \fopen('php://temp', 'r+');
fwrite($resource, $txt);
\rewind($resource);
$base64 = '';
foreach ((new Base64ContentEncoder())->encodeByteStream($resource) as $chunk) {
  $base64 .= $chunk;
}
\rewind($resource);
$decodedTxt = \base64_decode($base64);
echo \var_export($decodedTxt === $txt, true); // "false" (should be "true")
echo $decodedTxt; // "123" (should be "1234") 
echo \stream_get_contents($resource); // "1234" (correct)
```

**Additional context**
If I use something else than `\fopen('php://temp', 'r+')` it works as expected, like `\fopen(\tempnam(\sys_get_temp_dir(), 'xd'), 'r+')` or `\tmpfile()`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by tomme87** [comment]
For some reason I was running an old version of PHP (7.4.11) and was (probably) hit by this bug: https://bugs.php.net/bug.php?id=77069

Closing this issue.
