### ISSUE TITLE
[HttpClient] RetryableHttpClient + streamed responses fails to cancel responses properly

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#43391]
**Symfony version(s) affected**: 5.3.4

**Description**
When streaming responses and a response times out and gets canceled, it should then not throw anymore on __destruct. This works well without RetryableHttpClient, but when that wrapper is used it somehow still throws on __destruct.

**How to reproduce**
```php
<?php

include 'vendor/autoload.php';

ini_set('error_reporting', -1);
ini_set('display_errors', true);

$client = Symfony\Component\HttpClient\HttpClient::create();
$client = new Symfony\Component\HttpClient\RetryableHttpClient($client);

$client = $client->withOptions([
    'timeout' => 0.1,
]);

$resp[] = $client->request('GET', 'http://api.github.com/repos/symfony/symfony');

foreach ($client->stream($resp) as $response => $chunk) {
    try {
        if ($chunk->isTimeout()) {
            $response->cancel();
            var_dump('RESP CANCELLED');
        }
    } catch (Symfony\Contracts\HttpClient\Exception\ExceptionInterface $e) {
        var_dump('CAUGHT', $e);
        die;
    }
}

var_dump('END, NOTHING CAUGHT, SHOULD NOT THROW');
```

Running this outputs:

```
string(14) "RESP CANCELLED"
./test.php:30:
string(37) "END, NOTHING CAUGHT, SHOULD NOT THROW"
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TimeoutException: Idle timeout reached for "http://api.github.com/repos/symfony/symfony". in ./vendor/symfony/http-client/Chunk/ErrorChunk.php:65
```

The fatal error here is not expected, and commenting out the `RetryableHttpClient` fixes it.

**Comment by miguelantoniosantos** [comment]
As tested on [HttpClientTestCase.php:838](https://github.com/symfony/symfony/blob/5.3/src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php#L838) if you add the following code after the foreach it will work without errors:
```php
while ($response = array_shift($resp)) {
    try {
        unset($response);
    } catch (TransportExceptionInterface $e) {
    }
}
```

So, I believe, this is intended, if not the following code on [TransportResponseTrait.php:140](https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L140) and adjusting the unit tests should resolve this issue:

```php
try {
    self::initialize($this, -0.0);
    $this->checkStatusCode();
} catch (TimeoutExceptionInterface $exception) {
    // ignore any timeout errors as we are destructing
}
```
