### ISSUE TITLE
[http-foundation][HTTP Cache] not work with Etag and LastModified

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#43415]
**Symfony version(s) affected**: 4.4.30

**Description**
I've been using Symfony HTTP Cache for a long time and it has always worked fine, until I updated to version 4.4.30 of `htttp-foundation`, then it stopped working, it doesn't clean the cache directory. It always shows the same content, I have to delete the complete `var/cache/prod|dev/http_cache` folder.

**How to reproduce**

```
	$page     = $em->getRepository(Page::class)->find($id);
	$response = new Response();
    $response->headers->set(AbstractSessionListener::NO_AUTO_CACHE_CONTROL_HEADER, 'true');
    $response->setLastModified($page->getUpdatedAt());
    $response->setEtag(md5('myetag-'.$id));
    $response->setPublic();
	if($response->isNotModified($request)){
	   return $response;
	}
 	return $this->render($template, ['page' => $page], $response);
```

**Possible Solution**
`"symfony/http-foundation": "4.4.29",` I upgraded to a previous version and it worked again.

**Comment by Nek-** [comment]
I managed to [make a reproducer](https://gist.github.com/Nek-/24ec6a4e1bd50f202b66695e852f08af) with your code and can confirm this is a regression. This usage is documented here and should work but stopped working starting with Symfony 4.4.30, 4.4.31 is also impacted. https://symfony.com/doc/current/http_cache/validation.html#validation-with-the-last-modified-header

The problem is located here: https://github.com/symfony/symfony/commit/77bd21adfcb89b8c41154f4367089beb365ae150#diff-e0235307ea07cd74b290a19132ba3dcde20880d369799c2df492cd09a64c5c65R1101

**Comment by Nek-** [comment]
To me the problem is not located in Symfony. They actually made a real fix for some situations. You should consider to use the following code:

```php
$response->setEtag(md5('myetag-'.$id.$page->getUpdatedAt()->getTimestamp()));
```

What do you think?

The point is to choose between the date or the etag but both are not compatible (anymore, because of the RFC say so).

**Comment by chiqui3d** [comment]
It doesn't cost me anything to change the code, I have to modify very little code, but the previous code made more sense. I don't know how it works internally, but this way in the `http_cache ` folder will be left the rest of each modification of the `ETAG`, not substituting the current cache. I need to check

**Comment by chiqui3d** [comment]
I have just tried it and it works that way. That means that in Symfony 5, you also have to use the ETAG based on the Timestamp?

I have seen examples based on content, but I can see that this is very heavy. 

I've also noticed that the cache system doesn't clean itself automatically, I'll have to find a solution when the `http_cache `directory grows, like deleting it directly.

Thanks @Nek-
