### ISSUE TITLE
[Validator] `Assert\Url` Allow forbidding the `@` character

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#43506]
**Description**
The following does pass as valid URL (just had a real user entering something like this):
```
http://me@example.com
```
In reality, the user just entered their email address. Symfony's `UrlType::class` prefixed `http://`, and the `Url` constraint accepts this by treating `me` as the "userinfo" part of the URL (see [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1)).

So I'm suggesting an option to forbid "email-like" URL's, i.e. don't accept usename/password before the doman, i.e. forbid any `@` character. This is somewhat related to https://github.com/symfony/symfony/issues/39986, in the sense that an option named `public_url` could solve both issues.

**Comment by nicolas-grekas** [comment]
I would personally be in favor of never accepting any userinfo in URLs. Or at least not accepting userinfo by default.

**Comment by aless673** [comment]
> I would personally be in favor of never accepting any userinfo in URLs. Or at least not accepting userinfo by default.

should be an option

**Comment by stof** [comment]
When configuring webhooks, it is useful to allow specifying the userinfo for auth. So it should not be forbidden all the time. Forbidding it must be configurable.

**Comment by GromNaN** [comment]
`me@example.com` is invalid for the `UrlValidator` constraint. 

The `UrlType` has an option `default_protocol` that can be reset to `null` to avoid auto-prepending `http://` to the value.

The `UrlType` could be fixed to not alter values that looks like email address. If one needs to set an url with the userinfo, they would have to type the scheme part.

**Comment by GromNaN** [comment]
Hi @ThomasLandauer, what do you think of this fix? https://github.com/symfony/symfony/pull/43707

**Comment by ThomasLandauer** [comment]
I think it's an excellent idea to address this in the `UrlType` form field, and not (as I wrote above) in the validator! After all, it's the form field that "creates" the problem by prefixing "http://".

Plus:

> If one needs to set an url with the userinfo, they would have to type the scheme part.

Perfect solution - can't be easier!
