### ISSUE TITLE
 Undefined class constant 'JSON_ARRAY' when make:entity

### ISSUE THREAD

**Issue by murphy-nzl** [symfony/symfony#43536]
**Symfony version(s) affected**: 5.3.9

**Description**

when I indicate the name of a property, I get this error "Undefined class constant 'JSON_ARRAY'" but the entity and the repository are created

So I declare my properties by hand and then do a make:entity --regenerate and my getters and setters are created

**How to reproduce**

php bin/console make:entity
adding new property name

**Possible Solution**

**Additional context**

**Comment by wouterj** [comment]
Hi there! Thanks for reporting the issue.

This is an issue with the MakerBundle. Other users already reported the bug and a fix has been merged (but not yet released) in https://github.com/symfony/maker-bundle/pull/991

**Comment by murphy-nzl** [comment]
oh thanks

**Comment by the-conqueror-97** [comment]
Hi, i just got the same issue. 
I get this issue on the registration page after doing make:registration-form

I'm sure, the problem comes from $roles property that returns json data.

I have no way to fix it. Any temporary solution until the fix release ?

**Comment by derrabus** [comment]
> Hi, i just got the same issue. 

Please read the previous posts or use GitHub discussions if you need further assistance.
