### ISSUE TITLE
[Console,HttpKernel] Missing support for Psr/Log ^3.0 on 5.3,5.4

### ISSUE THREAD

**Issue by fredsal** [symfony/symfony#43570]
It's seems a really small fix on commit https://github.com/symfony/symfony/commit/95029e560d8805efaac9399496028c2ccdac6c24

https://github.com/symfony/symfony/blob/abb9a19f0c1895f50ddf58eacc7643e44febe609/src/Symfony/Component/Console/composer.json#L32
https://github.com/symfony/symfony/blob/abb9a19f0c1895f50ddf58eacc7643e44febe609/src/Symfony/Component/HttpKernel/composer.json#L27

do you accept PR for this?

**Comment by derrabus** [comment]
No, we don't. That's a BC break we won't make in a bugfix release. Thanks for understanding.

**Comment by fredsal** [comment]
@derrabus 5.4 still In development and LTS
![image](https://user-images.githubusercontent.com/79155632/137802445-1e82206a-e12a-47c1-8143-6475e46fa0c9.png)

**Comment by derrabus** [comment]
… and has to remain backwards-compatible to apps build against Symfony 5.0. This change would break backwards compatibility for no gain.

Symfony 6 will ship compatibility for psr/log 3. That ought to be soon enough, sorry.

**Comment by wouterj** [comment]
See also https://github.com/symfony/symfony/issues/42683#issuecomment-929959359 (and the other comments in that issue) and the many more psr/log & psr/container related issues in this issue tracker. A backwards compatibility break is a backwards compatibility break and those must be dealt with according to our release process.
