### ISSUE TITLE
syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by PHPTCloud** [symfony/symfony#43597]
**Symfony version(s) affected**: 5.4.*

**Description**
/vendor/laminas/laminas-code/src/Generator/ClassGenerator.php (line 36)

**How to reproduce**
after `composer i` (PHP 7.4.21)

**Comment by derrabus** [comment]
This is the Symfony bug tracker. Issues for Laminas Code are tracked here: https://github.com/laminas/laminas-code
