### ISSUE TITLE
[Console] Add completion for fish

### ISSUE THREAD

**Issue by stof** [symfony/symfony#43602]
Bash completion was implemented in #42251

It would be great to have support for fish as well.

**Comment by dkarlovi** [comment]
fish support should have fish equivalents:
- this template file: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/Resources/completion.bash
- this output class: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/Completion/Output/BashCompletionOutput.php

**Comment by guillaume-a** [comment]
[Fish custom completion doc](https://fishshell.com/docs/current/completions.html)
