### ISSUE TITLE
[Console] Implementing bash completion in a forward-compatible way

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#43620]
If I were to enable commands in 3rd party packages to provide completion, is there a good way to do that if that package should remain compatible with Symfony 4.4? After all, the interface I need to implement does not exist there.

_Originally posted by @derrabus in https://github.com/symfony/symfony/issues/43594#issuecomment-947843844_

**Comment by derrabus** [comment]
Brainstorming: Maybe this is just a documentation issue. Or maybe we can move the interface into a contract package to unblock forward-compatibility.

**Comment by derrabus** [comment]
cc @wouterj

**Comment by dkarlovi** [comment]
A a cludge solution, you can conditionally are the interface to the commands if it exists, maybe?

Something like

```
trait CommandTrait {}

if interface_exists {
    class Command implements CompletionI terface {
        use CommandTrait;
    }
} else {
    class Command {
        use CommandTrait;
    }
}
```

Not pretty, but works.
```

**Comment by derrabus** [comment]
Yes, I was thinking about something similar: Create a dummy interface that conditionally extends the real interface:

```php
namespace Acme\MyLib\Console;

use Symfony\Component\Console\Completion\CompletionInterface as SymfonyCompletionInterface;

if (interface_exists(SymfonyCompletionInterface::class)) {
    interface CompletionInterface extends SymfonyCompletionInterface {}
} else {
    interface CompletionInterface {}
}
```

That gives me an interface that I can always implement. Maybe that's the solution already.

**Comment by dkarlovi** [comment]
Yours is better! 👌

**Comment by wouterj** [comment]
A contracts package is not easily possible I think, as `CompletionInterface` relies on `CompletionInput` and `CompletionSuggestions`.

One thing that I won't reject (it was also discussed shortly on the PR): Drop the `CompletionInterface` and add a no-op `complete(...)` method to the `Command` class - which can be overridden by the child when desired.
This might also open up the possibility of using completion for single-command apps (that use `Command` directly).

**Comment by derrabus** [comment]
> Drop the `CompletionInterface` and add a no-op `complete(...)` method to the `Command` class - which can be overridden by the child when desired.

🤔 💡 Like this? #43628

**Comment by dsentker** [comment]
Sorry for asking, but I would like to get to know the update policy better. I don't understand why we can't include the `complete()` method against an interface. Adding a `CompletionInterface` wouldn't cause a BC break for 4.4 after all? And those who use the Symfony/Command Package would have the interface anyway.

// Update: nevermind, my question [just got answered](https://symfony.com/blog/new-in-symfony-5-4-console-autocompletion#comment-24720).
