### ISSUE TITLE
Requiring HTTP Kernel package doesn't install the Config package

### ISSUE THREAD

**Issue by ericmorand** [symfony/symfony#43636]
**Symfony version(s) affected**: 5.3.9

**Description**

The `symfony/http-kernel` package depends on `symfony/config` - for example here:

```php
$cache = new ConfigCache($buildDir.'/'.$class.'.php', $this->debug);
```

But requiring `symfony/http-kernel` doesn't install `symfony/config`.

**Steps to reproduce**

`composer require symfony/http-kernel`

The directory `vendor/symfony` doesn't contain `config`.

**Comment by ericmorand** [comment]
It seems like `symfony/config` is a dev dependency of `symfony/http-kernel`.

**Comment by ericmorand** [comment]
Actually, it seems that most of the package dependencies are declared as dev dependencies, preventing them from being installed alongside `symfony/http-kernel`.

**Comment by stof** [comment]
symfony/config is an optional dependency of symfony/http-kernel, because is is necessary only when using the Kernel class, but not when using only the HttpKernel one (note that the Kernel class also depends on `symfony/dependency-injection`, which is also an optional dependency of the component for the same reason)

**Comment by ericmorand** [comment]
So, the Kernel class is provided by `symfony/http-kernel` but can't be used except by requiring an _optional_ dependency? Is this a valid pattern? Config is not optional since it is required by _at least one_ part exposed by the HTTP Kernel component. Would it be optional, the HTTP Kernel would work even when the config component is not installed.

Having to install it to use one of the classes exposed by the HTTP Kernel component makes Config a required depencency, by definition.

**Comment by stof** [comment]
@ericmorand optional dependencies are dependencies required by optional features of a component. You can totally use `symfony/http-kernel` without using the Kernel class (that's exactly what Silex was doing).

**Comment by ericmorand** [comment]
Fair point. Can you please provide the link to the documentation with the list of optional features of the HTTP Kernel component?

**Comment by stof** [comment]
I don't think the documentation has a list of those (especially given that the doc tends to focus on the usage of components in the context of the framework, and so may not even have docs about the standalone usage of symfony/http-kernel).

The composer.json of `symfony/http-kernel` lists the optional dependencies as package suggestions. But currently, it misses the explanation about why they are suggested (an empty string is used). That's probably what should be fixed.

**Comment by nicolas-grekas** [comment]
Closing as there is no bug here.

**Comment by ericmorand** [comment]
@nicolas-grekas, the HttpKernel class doesn't work, plain and simple. You can pretend that it is by design but, well, you have to admit that you could use the "by design" excuse to disqualify any bug into a feature.

The truth is that HttpKernel class can't be used after installing the composer package that provides it. You can call it whatever you want, the rest of the world calls it a bug.

**Comment by stof** [comment]
@ericmorand the HttpKernel class works out of the box with required dependencies. The Kernel one relies on the optional dependencies.

Not relying on optional dependencies in Symfony components would force us to split existing components into a lot more components (and some of them would be very small, as the YamlFileLoader of the DI component would have to become its own component for instance), which has both a higher maintenance cost and a huge migration cost for the ecosystem.
