### ISSUE TITLE
Error messages don't show service causing the issue

### ISSUE THREAD

**Issue by htuscher** [symfony/symfony#43645]
If you get a new project and the first thing you encounter executing `bin/console` is:

```
In Definition.php line 276:
                                   
  The argument "6" doesn't exist.
```
it doesn't help you very much.

I would suggest that the DI component always tells you in which service you're having an issue.

In my case I had to start xdebug to see which definition caused the issue (which was in my case a compilerpass from a third party bundle).

**Comment by stof** [comment]
the issue is that the Definition object does not know the id under which it is registered in the ContainerBuilder, and so cannot put it in the messages (and a Definition is not always registered under an id, as you can nest anonymous definitions inline in arguments of other services)

**Comment by htuscher** [comment]
OK, then at least the classname so you can search for at least something in your project
