### ISSUE TITLE
AutowireRequiredMethodsPass::processValue infinite loop

### ISSUE THREAD

**Issue by Justinas-Jurciukonis** [symfony/symfony#43681]
**Symfony version(s) affected**: 5.3.7

**Description**
In `symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php@77` there is _final break_ from infinite loop. If it fails with any other error than `\ReflectionException` it will stay in infinite loop 

**Possible Solution**
Make catch be more generic, to catch any `Throwable` to break from loop:

```
74.           try {
75.                 $r = $r->getPrototype();
76.           } catch (\ReflectionException $e) {
77.                 break; // method has no prototype
78.           } catch (\Throwable $e) {
79.                throw $e;
80.           }
```

**Additional context**
This is _very_ complicated project where I join Yii1 with Symfony 5.3. Problem arises from Yii1 side when trying to use  Symfony service. And that service is injected into Yii1 only after kernel boot stage (don't even know how to properly describe scenario).

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by nicolas-grekas** [comment]
> Make catch be more generic, to catch any Throwable to break from loop

That's already what happens, there is no need to write any code to have this behavior.

A reproducer would definitely be nice as I don't see how this loop can be infinite right now.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
