### ISSUE TITLE
attribute #[isGranted] behaviour with associated array in subject

### ISSUE THREAD

**Issue by phillamarmotte** [symfony/symfony#43686]
**Symfony version(s) affected**: 5.3.0

**Description**

when i use isgranted by injecting the security component i can pass an associative array as subject and get the same keys in the voter.
When i do the same with the #[IsGranted] attribute keys always have the name of the parameters.

**How to reproduce**

```
   // In a controller
  #[IsGranted('CUSTOM_VOTER', subject: ['foo' => 'structure', 'bar' => 'theme'])]
    public function delete(Structure $structure, Theme $theme): Reponse
      {
         ...
      }
```  

```
  // In the voter
 protected function supports($attribute, $subject): bool
    {
        dd($subject);
    }

```
subject looks like [structure => ... , theme => ...] instead of [foo => ..., bar => ...].

if i use : $this->security->isGranted('CUSTOM_VOTER', ['foo' => 'structure', 'bar' => 'theme']) 
i get [foo => ..., bar => ...].

**Possible Solution**

this is behaviour is cause by  `Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments`

```
...
if (\is_array($subjectRef)) {
      foreach ($subjectRef as $ref) {
            if (!\array_key_exists($ref, $arguments)) {
                 throw $this->createMissingSubjectException($ref);
             }
             $subject[$ref] = $arguments[$ref];
      }
}
...
```

it sets the subjectName ref as key instead of the real key. 

it shoud do be like this.

```
...
if (\is_array($subjectRef)) {
      foreach ($subjectRef as $key => $ref) {
            if (!\array_key_exists($ref, $arguments)) {
                 throw $this->createMissingSubjectException($ref);
             }
             $subject[$key] = $arguments[$ref];
      }
}
...
```

**Comment by gnito-org** [comment]
It appears that the code of [IsGrantedListener](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blame/7fd1d54c1b27f094a68ae15a99b7fc815857255f/src/EventListener/IsGrantedListener.php) has been like that for the past three years.

A very quick work-around is to make the array key the same as the name of the array value. That produces the same array structure from both `#IsGranted` and `$security->isGranted`.

Please see the code in TestController at https://github.com/gnito-org/replicate-issue-43686.

**Comment by wouterj** [comment]
Hi! This is the issue tracker for `symfony/symfony`. The `IsGranted` attribute lives in the SensioFrameworkExtraBundle. Please continue this report by creating an issue at https://github.com/sensiolabs/SensioFrameworkExtraBundle. Thanks!
