### ISSUE TITLE
[Doctrine][Bug]Create extra files when install symfony/orm-pack

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#43800]
When I want to install `composer require symfony/orm-pack`, both `docker-compose.override.yml` and `docker-compose.yml` files are created in the root path. This was not the case before, but it has been around since I installed and uninstalled `Docker Desktop` for Windows 10. Does this cause a problem?

_Originally posted by @karaka200 in https://github.com/symfony/symfony/discussions/43795_

**Comment by karaka200** [comment]
@fabpot 
@dunglas 
Is it a `bug`?

**Comment by nicolas-grekas** [comment]
that's on purpose, see https://github.com/symfony/flex/pull/821

you can opt-out by setting extra.symfony.docker to false in your composer.json file
