### ISSUE TITLE
[Mailer] TemplatedEmail not properly rendered when template uses inline_css 

### ISSUE THREAD

**Issue by ovgray** [symfony/symfony#43845]
### Symfony version(s) affected

5.3.10

### Description

When sending TemplatedEmail with template:

`{% apply inline_css(source("test_email.css")) %}`
    `<p>First line.</p>`
    `<p>Second line.</p>`
    `<p>Third line.</p>`
`{% endapply %}`

and test_email.css:

`p {`
    `line-height: 1.42857143;`
`}`

The body of the email message that is sent is:

`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">`
`<html><body>`
`<p style="line-height: 142857143;">First line.</p>`
    `<p style="line-height: 1.42857143;">Second line.</p>`
    `<p style="line-height: 1.42857143;">Third line.</p>`
`</body></html>`

**Note that the line-height value in the style of the first `<p>` tag has lost its decimal point.**

This behavior occurs with env=prod but not with env=dev.

In case it is relevant, my php version is 7.3.5. This also occurs with php 7.3.29.

### How to reproduce

see above

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ovgray** [comment]
Sorry.

On further investigation this is not a bug in Mailer, it is a bug in MS Outlook 2016. If the html portion of the raw message has a "=" immediately before a ".", Outlook seems to remove the '.' before rendering the message.

Closing this issue.
