### ISSUE TITLE
Symfony 4.4.33 release on composer / packagist

### ISSUE THREAD

**Issue by LPodolski** [symfony/symfony#43853]
### Symfony version(s) affected

4.4.33,4.4.32

### Description

Symfony versions 4.4.33, 4.4.32 seems not to be released on composer/packagist, despite being released on symfony news

https://symfony.com/blog/symfony-4-4-33-released

https://symfony.com/blog/symfony-4-4-32-released (this release doesn't have any changes in it's release news too)

### How to reproduce

try to update older project to symfony 4.4.33

or go to https://packagist.org/packages/symfony/framework-bundle

and on releases list see that last release of 4.4 branch is v4.4.31

### Possible Solution

release those versions to composer

**Comment by derrabus** [comment]
We only tag a new release on packages that have been changed since the previous one. 4.4.33 is alive an well, see https://packagist.org/packages/symfony/http-kernel#v4.4.33 for instance.

**Comment by stof** [comment]
To be exact, the comment of @derrabus only applies to patch releases.
