### ISSUE TITLE
[Validator] After update to 5.3.10 before valid urls are now marked as invalid

### ISSUE THREAD

**Issue by MiroCillik** [symfony/symfony#43868]
### Symfony version(s) affected

5.3.10

### Description

After update to symfony/validator 5.3.10 https://github.com/symfony/symfony/pull/43388 the Url Validator marks urls like `http://internal-api` as invalid. This url was fine in version 5.3.8 and the PR seems to be fixing a different issue, so it seems like unwanted consequence. The hyphen seems to be the problem. Urls like this one are commonly used for  docker-compose services.

### How to reproduce

```php
$validator = Symfony\Component\Validator\Validation::createValidator();
$errors = $validator->validate('http://internal-api', [new Url()]);
var_dump($errors);
```

**Comment by derrabus** [comment]
Confirmed. @DfKimera, can you have a look please?

**Comment by valkars** [comment]
We have another issue, after update urls http://a, http://aa marked as valid, they were invalid earlier, our tests are broken now. This commit I think:
https://github.com/symfony/symfony/commit/27b1153cc4950028be26ab3ba0749655f0e21baf

**Comment by derrabus** [comment]
> after update urls http://a, http://aa marked as valid, they were invalid earlier

Yes, this is the problem that #43388 attempted to solve. Those two URLs of yours are valid URLs, aren't they?

**Comment by valkars** [comment]
They don't have a domain part and any reserved word (localhost), so they are invalid, am I wrong?

**Comment by derrabus** [comment]
> They don't have a domain part

They don't need to. `a` is a valid hostname. If you want to try it out for yourself, edit your `/etc/hosts` file and bind `a` to a valid IP address (e.g. `127.0.0.1`). Your browser will happily open `http://a` if a web server listens on the machine that belongs to that IP address.

As mentioned by @MiroCillik, hostnames without a domain part are common in Docker setups.

**Comment by valkars** [comment]
So we have form with company url and now user can enter http://a, useless validator, thanks for this "feature".

**Comment by derrabus** [comment]
> So we have form with company url and now user can enter http://a, useless validator, thanks for this "feature".

Before the change, the user could enter `http://a-a` or `http://localhost` to pass validation. The `Url` constraint has never checked if the URL contained a top level domain.
