### ISSUE TITLE
simple-phpunit.php: Uncaught ValueError: substr_count(): Argument #3... with custom SYMFONY_ROOT_DIR

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#43877]
### Symfony version(s) affected

4.4

### Description

Hi!

On Symfony UX, we are seeing an error in `substr_count()` from `simple=phpunit.php` - https://github.com/symfony/ux/runs/4072355007?check_suite_focus=true 

The issue originates from #43799 and is because we set `SYMFONY_PHPUNIT_DIR: '/tmp/.phpunit'` - so, a path that is outside of the project :).

Cheers!

### How to reproduce

Run:

```
SYMFONY_PHPUNIT_DIR='/tmp/.phpunit' php vendor/symfony/phpunit-bridge/bin/simple-phpunit.php
```

**Comment by vincentchalamon** [comment]
Can confirm I have the same issue with the following configuration in my phpunit.xml.dist:
```
<server name="SYMFONY_PHPUNIT_DIR" value="vendor/bin/.phpunit" />
```
Removing this parameter from phpunit.xml.dist solved the issue. Thanks for the tip @weaverryan

**Comment by nicolas-grekas** [comment]
What's the full error message? Can you maybe submit a fix?

**Comment by vincentchalamon** [comment]
> PHP Fatal error:  Uncaught ValueError: substr_count(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /path/to/project/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:242
Stack trace:
#0 /path/to/project/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(242): substr_count()
#1 /path/to/project/vendor/symfony/phpunit-bridge/bin/simple-phpunit(13): require('...')
#2 {main}
  thrown in /path/to/project/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 242
