### ISSUE TITLE
[Workflow] Unable to get transition definition by its name

### ISSUE THREAD

**Issue by smilesrg** [symfony/symfony#43919]
### Description

In the documentation:

```php
 $aTransition = $blogPublishingWorkflow->getDefinition()->getTransitions()[0];

    $priority = $blogPublishingWorkflow
        ->getMetadataStore()
        ->getTransitionMetadata($aTransition)['priority'] ?? 0
```

but to get specific transitions, I need to get them all and iterate over the array. Would be super nice to get transition and transition metadata by its name.

### Getting transition by name

Before:
```php
$transitions = $this->stateMachine->getDefinition()->getTransitions();
foreach ($transitions as $item) {
     if ($item->getName() === 'transition_name') {
        // ...
     }
}
```

After:
```php
$aTransition = $blogPublishingWorkflow->getDefinition()->getTransition('transition_name');
```

### Getting transition metadata by name

Before:
```php
$transitions = $this->stateMachine->getDefinition()->getTransitions();
foreach ($transitions as $item) {
     if ($item->getName() === 'transition_name') {
        $value = $blogPublishingWorkflow
            ->getMetadataStore()
            ->getTransitionMetadata($item)['metadata_field'] ?? 0;
     }
}
    
```

After:
```php
    $priority = $blogPublishingWorkflow
        ->getMetadataStore()
        ->getTransitionMetadataByTransitionName('transition_name')['priority'] ?? 0;
```

**Comment by lyrixx** [comment]
> but to get specific transitions, I need to get them all and iterate over the array. Would be super nice to get transition and transition metadata by its name.

There is one issue with that : Many transition can have the same name.

So I think this is not possible. The only solution would be to return the transition if there is no conflict, and throw an exception in other case. WDYT?

**Comment by lyrixx** [comment]
I'm closing this issue due to the lack of feedback
