### ISSUE TITLE
[Cache] Memory leak when using the cache

### ISSUE THREAD

**Issue by Jeroeny** [symfony/symfony#43918]
### Symfony version(s) affected

symfony/framework-bundle:  
`5.3.10`, `5.2.14`, `5.1.11`, `5.4.x-dev@24649c622776b36158f80b81b9455987b8129793` , `6.0.x-dev@5284b7f8419f9ed224d8d00d6c945d566343cd83`, `4.4.31`, and I assume every version in between.

PHP: `7.4.15`, `8.0.11`, `8.0.12`, `PHP 8.1.0RC5`

### Description

When using the Symfony cache in a certain way (e.g. calling the cache within a closure that is resolving another cache value), there is a memory leak. 

It's quite a strange bug and I don't know what is causing it. I was able to reproduce it (more info in the reproducer's readme). I'm not sure if this could be a PHP bug either.

In the reproducer the memory increase is not that high. However, in our own application the memory increase is ~10 MB per call to the method that does a bunch of caching. This is especially a problem in our message consumers.

I'll test the reproducer against some other Symfony versions too.

### How to reproduce

Reproducer: https://github.com/Jeroeny/reproduce/tree/cache

### Possible Solution

In our own application `gc_collect_cycles()` mitigated the problem. But not in the reproducer.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, I also see the memory increase, but I didn't find any obvious reason yet.

The leak is around this stack:
![image](https://user-images.githubusercontent.com/243674/141122389-4c9b8129-4e4b-496c-88d4-98e17cc52bd9.png)

But I don't know where. Help wanted.

**Comment by Jeroeny** [comment]
Could this be related https://bugs.php.net/bug.php?id=76982  ?

**Comment by nicolas-grekas** [comment]
It used to be an issue but now the code should not hit this bug, so I don't think that would the issue (but I might be wrong of course, that's just my memory speaking.)

**Comment by a1812** [comment]
> But I don't know where. Help wanted.

hardcode solution

https://github.com/symfony/symfony/blob/07a891f6c57d9da513d75402f2aa2da73d897044/src/Symfony/Component/Cache/Traits/AbstractAdapterTrait.php#L397
 insert  before return
```php
unset($this->ids)
````

**Comment by nicolas-grekas** [comment]
@a1812 thanks for the idea but that doesn't remove the leak.

**Comment by a1812** [comment]
@nicolas-grekas 
![image](https://user-images.githubusercontent.com/42714329/141166687-64ccf146-9824-4654-a130-7d03b5d4aee7.png)

**Comment by nicolas-grekas** [comment]
Oh, that's not what I have. Which version of PHP do you use? Same with the prod env?

**Comment by a1812** [comment]
i tested so:

PHP 8.0.12

```
framework:
    cache:
        app: cache.adapter.memcached

```

**Comment by Jeroeny** [comment]
> insert before return
> ```
> unset($this->ids)
> ```

In my reproducer, the return statement on line 389 is hit, because `maxIdLength` is null: https://github.com/symfony/symfony/blob/07a891f6c57d9da513d75402f2aa2da73d897044/src/Symfony/Component/Cache/Traits/AbstractAdapterTrait.php#L389

However, it indeed seems to fix the memory leak. When I add this add line 387 in that same Trait:
`echo 'ids ' . count($this->ids) . PHP_EOL;`
It shows that number of `ids` increases with hundreds per second, without ever decreasing. So it makes sense that unsetting those IDs would fix the memory leak. I've tested this with `prod` app_env, but the behaviour appears the same on `dev`.

What is the usecase of this array? Is it to cache the result of the hash of the key when `maxIdLength` is set?
