### ISSUE TITLE
[DependencyInjection] PhpDumper generate non-valid code for container cache

### ISSUE THREAD

**Issue by ScaryDonetskiy** [symfony/symfony#43926]
### Symfony version(s) affected

5.3.10

### Description

PHP Version: 8.0.12
Symfony Version: 5.3.10

According to documentation (https://symfony.com/doc/current/service_container/definitions.html#constructor-arguments), I'm try to set argument for the service inside the bundle. 
`$container->getDefinition('enqueue.transport.'.$name.'.log_extension')->setClass(LogExtension::class)->setArgument('$debug', $container->getParameter('messagebus.debug'));`

But I got syntax error in generated containers cache 
`In getEnqueue_Transport_Default_QueueConsumerService.php line 38:
  syntax error, unexpected token ":", expecting ")"  `
  
  As I saw in generated class, Symfony try to use named arguments from PHP8, but set name of variables with '$' sign. 

### How to reproduce

1. Use 'setArgument' method for containers service definition class according to documentation (https://symfony.com/doc/current/service_container/definitions.html#constructor-arguments). Example `$definition->setArgument('$debug', true)`
2. Run any console command for generating container cache
3. See syntax error in generated service cache class.

### Possible Solution

I'm trying to make a patch for current issue in \Symfony\Component\DependencyInjection\Dumper\PhpDumper
But you might help me to make it correctly. I think, that I can trim '$' sign from argument name (\Symfony\Component\DependencyInjection\Dumper\PhpDumper:1139) or research how this string will be used later and fix it in putting to fileTemplate. 

### Additional Context

<img width="461" alt="image" src="https://user-images.githubusercontent.com/12470079/140299703-aab61fc9-d0c9-45d9-81ce-c0ccb2c21fa0.png">

**Comment by ScaryDonetskiy** [comment]
Also I can attach example of generated code with error

`return $container->privates['enqueue.transport.default.queue_consumer'] = new \Enqueue\Consumption\QueueConsumer(($container->privates['enqueue.transport.default.context'] ?? $container->load('getEnqueue_Transport_Default_ContextService')), new \Enqueue\Consumption\ChainExtension([0 => ($container->services['App\\MessageProcessor\\PushEventProcessor'] ?? $container->load('getPushEventProcessorService')), 1 => ($container->privates['enqueue.consumption.signal_extension'] ?? ($container->privates['enqueue.consumption.signal_extension'] = new \Enqueue\Consumption\Extension\SignalExtension())), 2 => ($container->privates['enqueue.consumption.reply_extension'] ?? ($container->privates['enqueue.consumption.reply_extension'] = new \Enqueue\Consumption\Extension\ReplyExtension())), 3 => new \MessageBusBundle\Enqueue\LogExtension($debug: false)]), [], ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), 1000);`

**Comment by nicolas-grekas** [comment]
Can you please provide a reproducer? Eg a simple app that hits this?

**Comment by ScaryDonetskiy** [comment]
I can provide a ConfigurationPass class from my bundle. It it ok for you?

**Comment by nicolas-grekas** [comment]
If your pass runs before `ResolveNamedArgumentsPass` (which is the default) then the named arg should be supported.
If it runs after optimization passes, then named args are not supported anymore.
That could be the reason.

**Comment by ScaryDonetskiy** [comment]
We found the reason. Our CompilerPass was added with `TYPE_OPTIMIZE `and runs after `ResolveNamesArgumentsPass`. Now we use default `TYPE_BEFORE_OPTIMIZATION ` type and error is not reproducing. Thanks @nicolas-grekas
