### ISSUE TITLE
[Workflow] Command workflow:dump not working

### ISSUE THREAD

**Issue by ch2877** [symfony/symfony#43938]
### Symfony version(s) affected

5.4

### Description

I tryed to dump a workflow in Symfony 5.4 and kept getting the Message 

`No service found for "workflow.xyz" nor "state_machine.xyr".`

I tryed to reproduce it in Symfony 5.3 and found that it is working, but got the following warning:

`User Deprecated: Since symfony/framework-bundle 5.3: Accessing the "workflow.xyz" service directly from the container is deprecated, use dependency injection instead.`

### How to reproduce

Create a Workflow in Symfony 5.4 and try to dump it:
https://github.com/ch2877/symfony_issue_43938

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ch2877** [comment]
Here it is:
https://github.com/ch2877/symfony_issue_43938

**Comment by noniagriconomie** [comment]
I see the problem, when discussing with @StaffNowa on PR https://github.com/symfony/symfony/pull/43848 we may have misunderstood ourselves, between workflowNames and workflowIds (with prefix `workflow.` and `state_machine.`)
I will provide a fix for v5.4

**Comment by StaffNowa** [comment]
> I see the problem, when discussing with @StaffNowa on PR #43848 we may have misunderstood ourselves, between workflowNames and workflowIds (with prefix `workflow.` and `state_machine.`) I will provide a fix for v5.4

Yes, we had before prefixes validation in the switch case.
