### ISSUE TITLE
[Secrets] Renaming a secret doesn't work

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#43941]
### Symfony version(s) affected

5.4.0

### Description

I have some secrets in my codebase.
When I rename a file let's say `dev.ALGOLIA_API_KEY.b46f8f` to `dev.ALGOLIA_API_KEY_ADMIN.b46f8f` then the file is not loaded anymore by the SodiumVault.

The issue is because of the MD5 hash at the end of the filename `b46f8f`.

This hash comes from the secret's name `ALGOLIA_API_KEY` so if the name changes then the hash must change too.

### How to reproduce

Rename an existing secret

### Possible Solution

I can't figure out why this hash is needed.

So I identify these solutions as potential fixes:
1. Comment in SodiumVault.php why there is a hash & Update the doc to state that secrets can't be renamed
2. Remove the use of the hash (with a deprecation notice & co to preserve BC)

**Comment by nicolas-grekas** [comment]
I don't remember why we have the hash...
But you should use the commands to do this operation: first create the new secret then delete the old one.

**Comment by sylfabre** [comment]
@nicolas-grekas  I _now_ know this but:
- it's not documented
- the hash seems to be just counter-productive

That's why I opened this issue

**Comment by noniagriconomie** [comment]
@sylfabre @nicolas-grekas Hi :)

I've opened https://github.com/symfony/symfony-docs/pull/16083 for doc purpose

Do you think it could be valuable to add a new command/ or a new argument/option on existing command to handle the renaming logic?

Cheers!

**Comment by nicolas-grekas** [comment]
Could someone look at git history to see if it contains something interesting about the hash?

**Comment by sylfabre** [comment]
@nicolas-grekas I think it's a left-over from https://github.com/symfony/symfony/commit/c4653e1f65c1df24bd5e73bc5118a5506834f3a4 

The now-deleted file `src/Symfony/Bundle/FrameworkBundle/Secret/Storage/CachedSecretStorage.php` uses the MD5 hash as a cache key but it doesn't make sense anymore now. So I think it can be removed

**Comment by nicolas-grekas** [comment]
Oh now I remember: it allows making secrets case sensitive. The filename is not enough on Windows

**Comment by nicolas-grekas** [comment]
Closing then. We could maybe consider a command to rename.

**Comment by sylfabre** [comment]
@nicolas-grekas Would you accept a PR to comment this decision in the code?

**Comment by nicolas-grekas** [comment]
Always :)

**Comment by sylfabre** [comment]
@nicolas-grekas Here you are!
https://github.com/symfony/symfony/pull/44027
