### ISSUE TITLE
FlattenException , HtmlErrorRenderer , MS Outlook

### ISSUE THREAD

**Issue by jschlies** [symfony/symfony#43957]
I'm using Symfony\Component\ErrorHandler\Exception\FlattenException and Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer to generate emails to MS Outlook. These emails however, not not 'play well' with the Outlook Client and, per Mailtrap.io, many issue across several clients. Can these be addressed or can someone suggest alternatives?  Thanks

```php
$e = FlattenException::createFromThrowable($throwable);

$handler = new HtmlErrorRenderer(true); // boolean, true raises debug flag...
$css = $handler->getStylesheet();
$content = $handler->getBody($e);
 \Mail::send('email_templates.Common.html.ExceptionEmail', compact('css','content'), function ($message) {
                $message
                    ->to('james.xxx@whereIwork.com')
                    ->subject('Exception: ' . \Request::fullUrl())
                ;
            });
```

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta charset="UTF-8" />
<title>Exception Email</title>
    <style type="css">{!! $css ?? '' !!}</style>
</head>
<body style="background-color: white">
{!! $content ?? '' !!}
</body>
</html>
```

**Comment by xabbuh** [comment]
> These emails however, not not 'play well' with the Outlook Client and, per Mailtrap.io, many issue across several clients.

Can you clarify which issues you are talking about?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
