### ISSUE TITLE
UserProviderInterface includes the wrong method

### ISSUE THREAD

**Issue by NotionCommotion** [symfony/symfony#43968]
### Symfony version(s) affected

5.3.10

### Description

Symfony\Component\Security\Core\User\UserProviderInterface should include:

    public function loadUserByIdentifier(string $identifier);

and not:

    public function loadUserByUsername(string $username);

Reference:

- https://symfony.com/doc/current/security/user_providers.html#creating-a-custom-user-provider
- https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Core/User/UserProviderInterface.php

### How to reproduce

N/A

**Comment by chalasr** [comment]
It's on purpose. The `loadUserByUsername()` has been deprecated in 5.3 and is removed in 6.0. Classes implementing this interface will be able to remove the `loadUserByUsername()` when upgrading to 6.0 or later, not before.

**Comment by xabbuh** [comment]
Did you run into any issues that you experienced with the method not being defined in the interface?

**Comment by wouterj** [comment]
Closing as this is the expected BC path as explained by @chalasr.

In 5.3, user providers must implement the old method to be backwards compatible with libraries supporting <5.3. A deprecation will be triggered automatically when you don't implement the new method as well.
In 6.0, we removed the old method and added the new method.

**Comment by NotionCommotion** [comment]
Thank you for your response and sorry for the false positive.
