### ISSUE TITLE
[doctrine-bridge] Undefined constant Doctrine\DBAL\Types\Types::JSON_ARRAY at PropertyInfo/DoctrineExtractor.php:169

### ISSUE THREAD

**Issue by li0n12** [symfony/symfony#43975]
### Symfony version(s) affected

5.2.12

### Description

symfony/doctrine-bridge 5.2.12 is not compatible with doctrine/dbal 3.0
there is a usage of Doctrine\DBAL\Types\Types::JSON_ARRAY in
https://github.com/symfony/doctrine-bridge/blob/v5.2.12/PropertyInfo/DoctrineExtractor.php#L169

but in doctrine/dbal v3.0 its removed
so symfony/doctrine-bridge gives:
Error : Undefined constant Doctrine\DBAL\Types\Types::JSON_ARRAY

### How to reproduce

install symfony 5.2 project with doctrine-bridge and doctrine/dbal v3.0

### Possible Solution

replace Doctrine\DBAL\Types\Types::JSON_ARRAY with Doctrine\DBAL\Types\Types::JSON
as described here: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json-array

**Comment by stof** [comment]
Replacing it is not an option, otherwise we would break support for projects using the deprecated `json_array` type in their mapping.
`Doctrine\DBAL\Types\Types::JSON` should be added in the switch separately.

**Comment by li0n12** [comment]
So there should be added an alias for Doctrine\DBAL\Types\Types::JSON_ARRAY 
because in dbal 3.0 its not exists

**Comment by xabbuh** [comment]
Symfony 5.2 is not supported anymore and a fix has been shipped with 5.3.8 (see symfony/symfony@6faae75102751b9550ed767b7afe5a544e35d5ee). You will need to update to it. That's why I am going to close here. Thank you for understanding.
