### ISSUE TITLE
[Routing] override defaults/requirements defined in yaml via annotation

### ISSUE THREAD

**Issue by gimler** [symfony/symfony#43974]
### Symfony version(s) affected

5.3.10

### Description

I try to add a host default to all my routes and only on some controllers i need to override it.
https://symfony.com/doc/current/routing.html#sub-domain-routing

It is not possible to override the defaults and requirements from annoations.yaml with a route annotation in the controller.

### How to reproduce

```
# annotations.yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
    defaults:
        test: yaml
```
controller
 ```
/**
 * @Route(defaults={"test": "annotation"})
 */
class WebsiteController extends AbstractController
{
    /**
     * @Route("/", name="get_website", methods={"GET"}, defaults={"test": "annotation"})
     */
    public function information(Request $request, Connection $connection)
    {
    }
}
 ```
console debug:router get_website
```
+--------------+----------------------------------------------------------+
| Property     | Value                                                    |
+--------------+----------------------------------------------------------+
| Route Name   | get_website                                              |
| Path         | /                                                        |
| Path Regex   | {^/$}sDu                                                 |
| Host         | ANY                                                      |
| Host Regex   |                                                          |
| Scheme       | ANY                                                      |
| Method       | GET                                                      |
| Requirements | NO CUSTOM                                                |
| Class        | Symfony\Component\Routing\Route                          |
| Defaults     | _controller: App\Controller\WebsiteController::website() |
|              | _locale: de                                              |
|              | test: yaml                                               |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler  |
|              | utf8: true                                               |
+--------------+----------------------------------------------------------+
```

**Comment by derrabus** [comment]
I'm a bit confused by the `Requirements` row in your output. You never set those in your configuration examples. Where is this coming from? Anyhow, what would be the result you expect?

**Comment by gimler** [comment]
@derrabus sorry my fail i have test booth values but try to keep the example as small as possible i have correct the output

**Comment by derrabus** [comment]
The current implementation of loading config via `resource` works the other way round.

You apparently expected that the settings you make in the YAML file next to the `resource` key is used as a fallback that can be overridden on a per-route basis. But in fact, you provide a setting that overrides the corresponding setting of the loaded routes.

So, as a bug ticket I have to render this issue invalid. But if you need this functionality as a feature, would you be willing to work on it for 6.1?

**Comment by gimler** [comment]
@derrabus thanks for clarification i have open a feature request for that. Actually i can use a workaround and put the controller in different folders and duplicate the config ;(
