### ISSUE TITLE
.env file with APP_SECRET triggers GitGuardian

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony#43986]
* when using `symfony new` it does create an .env file with an APP_SECRET variable.
* then symfony cli does make the first commit with all files commited. (this already includes the .env file)
* then when you push it like i did with for reporting another error in a bundle, the .env gets pushed too.
* this will trigger GitGuardian because pushing the APP_SECRET might be a security risk. (sensitive file + generic high entropy secret)

should the  APP_SECRET be in .env or wouldn't the .env.local be better? or shouldn't the .env file be added to git at all?

**Comment by Hanmac** [comment]
@fabpot can you comment on what the "symfony cli" should do with the APP_SECRET ? should it be commited or not?

currently the cli is doing the first commit which does include the secret, and changing the commit again is ugly

**Comment by nicolas-grekas** [comment]
Closing is duplicate of #38021
See there for discussion on the topic.
