### ISSUE TITLE
[Serializer] Pass a key property to NotNormalizableValueException

### ISSUE THREAD

**Issue by shude** [symfony/symfony#43999]
### Description

When we try to denormalize an object with type-hinted property with builtin type and it does not match we get an NotNormalizableValueException with message that contains a field name. Sometimes we want to get key of that field.
I suggest adding a property ```key```  to NotNormalizableValueException and just set it in ArrayDenormalizer.

**Comment by xabbuh** [comment]
Would you like to give it a try?

**Comment by shude** [comment]
It just solved in #42502
