### ISSUE TITLE
Empty profiler log deprecation

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#44017]
### Symfony version(s) affected

5.4.0-beta1

### Description

I am in a process of upgrading a v4.4 to v5.4 app

When checking the profiler > logs > deprecations, I am seeing a line like this, without any explanation in the log:
![Capture d’écran 2021-11-11 à 22 57 26](https://user-images.githubusercontent.com/1358361/141374967-edb904c3-aec5-4f49-8fc2-8e019ff6da2b.jpg)

edit: if I add some dump inside the compiler class before the `trigger_deprecation`, I got this:

```
^ "symfony/framework-bundle"
^ "5.4"
^ "The "Symfony\Component\Cache\Adapter\AdapterInterface" alias is deprecated, use "%s" instead. It is being referenced by the "%s" service."
^ "App\Services\Cache\CacheClearer"
```

### How to reproduce

~I do not know if it is related to my app or~ symfony related

### Possible Solution

unknown for now

### Additional Context

- Symfony 5.4.0-BETA1
- PHP 7.4.25

**Comment by xabbuh** [comment]
Does #43993 fix this?

**Comment by 94noni** [comment]
@xabbuh thanks for checking this, and yes indeed it fixes the log display
lets close!
