### ISSUE TITLE
ExpressionLanguage unable to parse decimal numbers without leading zeros

### ISSUE THREAD

**Issue by epixian** [symfony/symfony#44014]
### Symfony version(s) affected

5.3.7

### Description

ExpressionLanguage is unable to parse decimal numbers without leading zeros.

Invalid expressions:
"-.1"
"0-.1"
"0+.1"
".1"

Valid expressions:
"-0.1"
"0-0.1"
"0+0.1"

### How to reproduce

```
>>> $el = new ExpressionLanguage;
=> Symfony\Component\ExpressionLanguage {#4544}
>>> $el->parse('-0.1', [])->getNodes()->dump();
=> "(- 0.1)"
>>> $el->parse('-.1', [])->getNodes()->dump();
Symfony\Component\ExpressionLanguage\SyntaxError with message 'Unexpected token "punctuation" of value "." around position 2 for expression `-.1`.'
>>> $el->parse('0-.1', [])->getNodes()->dump()
Symfony\Component\ExpressionLanguage\SyntaxError with message 'Unexpected token "punctuation" of value "." around position 3 for expression `0-.1`.'
>>> $el->parse('0+.1', [])->getNodes()->dump()
Symfony\Component\ExpressionLanguage\SyntaxError with message 'Unexpected token "punctuation" of value "." around position 3 for expression `0+.1`.'
>>> $el->parse('0+0.1', [])->getNodes()->dump()
=> "(0 + 0.1)"
>>> $el->parse('.1', [])->getNodes()->dump()
Symfony\Component\ExpressionLanguage\SyntaxError with message 'Unexpected token "punctuation" of value "." around position 1 for expression `.1`.'
```

**Comment by fancyweb** [comment]
Status: reviewed

I looked at this. IMO the problem is on the lexer side. The regex used to detect numbers is not in sync with how PHP can currently cast strings to floats. I recomputed the following regex from https://github.com/php/php-src/blob/ddaf64b56c88f0ae223b1aca25293dd7fec77fc0/Zend/zend_language_scanner.l#L1359:
`/((?:[0-9]+(?:_[0-9]+)*|(?:(?:[0-9]+(?:_[0-9]+)*)?\.[0-9]+(?:_[0-9]+)*|[0-9]+(?:_[0-9]+)*\.(?:[0-9]+(?:_[0-9]+)*)?))[eE][+-]?[0-9]+(?:_[0-9]+)*|(?:(?:[0-9]+(?:_[0-9]+)*)?\.[0-9]+(?:_[0-9]+)*|[0-9]+(?:_[0-9]+)*\.(?:[0-9]+(?:_[0-9]+)*)?)|[0-9]+(?:_[0-9]+)*)/A`

It seems to fix everything and also other cases such as having underscores in the number.

@nicolas-grekas @derrabus Do we consider this a bugfix on 4.4 and craft the regex pattern depending of the PHP version (the underscores were not allowed before 7.4) or do we consider supporting all those new cases as a feature on 6.1?

**Comment by nicolas-grekas** [comment]
I consider this a feature, there's no bug here, the syntax is clear: the leading zero is required :)
Why should we support with no leading zero in the first place?

**Comment by stof** [comment]
The ExpressionLanguage lexer is responsible for supporting the ExpressionLanguage syntax, not the PHP one. So there is indeed no bug here. This is more a feature request.

**Comment by epixian** [comment]
Thank you for looking into this and for the discussion.

> the syntax is clear: the leading zero is required :) Why should we support with no leading zero in the first place?

I'm not sure that the syntax is clear.  The [documentation](https://symfony.com/doc/current/components/expression_language/syntax.html#supported-literals) indeed lists the various supported literals, including "numbers - e.g. 103" but without any caveats that says that these literals are not interpreted/treated the same as PHP.  (Perhaps this is mentioned in the code, but that's not the same and I had not gone that deep yet.)

The main argument for supporting no leading zeros is that it seems odd not to.  `.1` for example is an entirely valid numeric value.  On its own or as part of a simple arithmetic expression directly inputted to PHP, it would be (correctly) interpreted as such.
```
>>> .1
=> 0.1
>>> 1 + .1
=> 1.1
```
Additionally I think developers would generally expect similar (if not exact) behavior, and as the main reason we started using ExpressionLanguage was to validate/parse user input, not to support an otherwise valid input requires a need to pre-validate/parse the entire input just to insert the missing leading zeros, the very task we wanted to avoid.

In the meantime, should we update the documentation to reflect this?  I would be happy to submit a PR over there.

**Comment by stof** [comment]
Well, the ExpressionLanguage lexer was originally created based on the Twig lexer (the syntax to access properties and methods is inspired by Twig, with the magic of `twig_get_attribute()` removed to allow compiling the code to a runtime-free expression). And the supported number literals are the same in ExpressionLanguage and Twig. Both require a leading digit.

**Comment by fancyweb** [comment]
I opened https://github.com/symfony/symfony/pull/44073 since I had already made the "work". Let's see where it goes there :smile:
