### ISSUE TITLE
 [root@localhost ____]# symfony console make:migration  In AbstractPlatform.php line 398:    Unknown database type interval day(3) to second(2) requested, Doctrine\DBAL\Platforms\OraclePlatform may not support it.

### ISSUE THREAD

**Issue by belkanoiv2** [symfony/symfony#44026]
Buenas tardes.
Alguien a tenido este mensaje de error ?
Estoy armando un proyecto  con centos 7, php 8, symfony 5.3 y oracle 19C.

El erro ocurre al ejecutar esto:
[root@localhost ____]# symfony console make:migration

In AbstractPlatform.php line 398:

  Unknown database type interval day(3) to second(2) requested, Doctrine\DBAL\Platforms\OraclePlatform may not sup
  port it.

Saludos.

//

Buenas tardes.
Has anyone had this error message?
I am building a project with centos 7, php 8, symfony 5.3 and oracle 19C.

The error occurs when running this:
[root @ localhost ____] # Symfony console flag: migration

In AbstractPlatform.php line 398:

Unknown database type range from day (3) to second (2) requested, Doctrine \ DBAL \ Platforms \ OraclePlatform may not be supported
carry it.

Greetings.//

Update/actualización
solucionado:
Cambiar el nombre de usuario que se conecta a la base de datos, no usas system. Crear uno nuevo. Ta simple y fueron horas de sueño luchando.
fixed:
Change the username that connects to the database, you don't use system. Create a new one. Ta simple and it was hours of sleep fighting.

**Comment by xabbuh** [comment]
Please describe your issue in English so that not only people speaking the same language as you understand it.

**Comment by belkanoiv2** [comment]
Describe your problem in English so that not only people who speak the same language as you understand it.

Thank you for your comment, I did not realize. Corrected. @xabbuh
