### ISSUE TITLE
[Session] PdoSessionStorageHandler visibility

### ISSUE THREAD

**Issue by gimler** [symfony/symfony#44039]
### Description

We have the user_id as separate field in the database table for our sessions. So we need to override the `PdoSessionHandler::getMergeStatement` to set it when insert.

Is there any reason why the methods are private?
* `PdoSessionHandler::getMergeStatement`
* `PdoSessionHandler::getUpdateStatement`
* `PdoSessionHandler::getInsertStatement`

**Comment by xabbuh** [comment]
We do not declare methods as protected by design as maintaining them beckmessert nightmare as soon as we need/want  to do changes to these methods.

Can you please show the code that you would have added in your implementation if the methods were protected?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
