### ISSUE TITLE
[loco-translation-provider] Improper content type of http request

### ISSUE THREAD

**Issue by tomasz-kusy** [symfony/symfony#44031]
### Symfony version(s) affected

5.3

### Description

When using Loco provider is impossible to send single word "data" as a translation.

```POST /translations/tpl.patients.data/pl HTTP/1.1
Host: localize.biz
Authorization: ****
Accept: */*
User-Agent: Symfony HttpClient/Curl
Accept-Encoding: gzip
Content-Length: 4
Content-Type: application/x-www-form-urlencoded

data
```
When set `Content-Type: text/plain` it works.

### How to reproduce

Tested with symfony/http-client v5.3.10

Push source asset translation: data

### Possible Solution

Workaround:
new CurlHttpClient(['headers' => ['Content-type' => 'text/plain']])

Solution:
Force http client  to use 'Content-type' => 'text/plain'

**Comment by welcoMattic** [comment]
Hello @tomasz-kusy, to be sure to understand well the issue, did you run `bin/console translation:push loco` with only `data` in your translation file?

**Comment by tomasz-kusy** [comment]
Hi!
At the first thank you for the work.
No I'm use this package on my own implementation. The library has/had its shortcomings and flaws (like only auto generated Id's - I see it is avilalble now). Also reported [this]( https://github.com/symfony/symfony/issues/44185)
I have encountered the problem I am reporting. It didn't know what is a problem until an analysis on the loco.biz documentation page. Therefore, I decided to share it.

My fix looks like that:
```
    private function translateAssets(array $translations, string $locale): void
    {
        $responses = [];

        foreach ($translations as $id => $message) {
            $responses[$id] = $this->client->request('POST', sprintf('translations/%s/%s', \rawurlencode($id), $locale), [
                'body' => $message,
                'headers' => ['Content-Type' => 'text/plain']
            ]);
        }

        foreach ($responses as $id => $response) {
            if (200 !== $response->getStatusCode()) {
                $this->logger->error(sprintf('Unable to add translation for key "%s" in locale "%s" to Loco: "%s".', $id, $locale, $response->getContent(false)));
            }
        }
    }
```

**Comment by tomasz-kusy** [comment]
When you call translateAssets() with parameter like:
```$translations = ['assetKey' => 'data']``` and 'Content-Type' will be wrong it will fail.

**Comment by nicolas-grekas** [comment]
@tomasz-kusy can you provide a fix for this?

**Comment by tomasz-kusy** [comment]
@nicolas-grekas Fix is waiting :)
