### ISSUE TITLE
[Process] defaultEnv not properly generated in PHP build-in webserver

### ISSUE THREAD

**Issue by lukas-staab** [symfony/symfony#44066]
### Symfony version(s) affected

process 5.3.7

### Description

The php-doc says 
https://github.com/symfony/symfony/blob/f7d70f1ab4be3bd98432cf9eccc4fa53f9fd36c4/src/Symfony/Component/Process/Process.php#L137
With `$env = null` it will take the Enviroment of the current process. This is not allways true. 
Using the [PHP Build-In Webserver](https://www.php.net/manual/en/features.commandline.webserver.php) (`php -S localhost:80`) `$_ENV` is empty (but `getenv()` is not), so 
https://github.com/symfony/symfony/blob/f7d70f1ab4be3bd98432cf9eccc4fa53f9fd36c4/src/Symfony/Component/Process/Process.php#L1672 
gives unexpected result. Especially the PATH variable remains unset, which leads to unfound binaries 

### How to reproduce

Use php build in webserver (see above) and use e.g
```php
$p = new Process(['pdflatex'], __DIR__, null)
```
(set `$env = null`)
-> PATH Variable is not set in `$_ENV` only in `getenv()`

### Possible Solution

Use `getEnv()` instead of `$_ENV` or check for
```php 
if (php_sapi_name() === 'cli-server') {
```

### Additional Context

`php -S` is (often) used in local development environments. Missing PATH Variables can be a big issue there.

**Comment by lukas-staab** [comment]
This might be the cause of the issue of the empty `$_ENV`. Quote from (my) default `/etc/php.ini` (php 8.0 on Fedora 35)
```
; This directive determines which super global arrays are registered when PHP
; starts up. G,P,C,E & S are abbreviations for the following respective super
; globals: GET, POST, COOKIE, ENV and SERVER. There is a performance penalty
; paid for the registration of these arrays and because ENV is not as commonly
; used as the others, ENV is not recommended on productions servers. You
; can still get access to the environment variables through getenv() should you
; need to.
; Default Value: "EGPCS"
; Development Value: "GPCS"
; Production Value: "GPCS";
; http://php.net/variables-order
variables_order = "GPCS"
```
So this might even effect other tools, not only the build-in webserver. For me `php -f` worked, where the build-in webserver did not with the same files, due to unpopulated `$_ENV` (E)

**Comment by lukas-staab** [comment]
Thanks for the quick commit f608f0b7241a84f7893a621f7993aff4988306b3 @nicolas-grekas but I do not think this solves the issue. e.g. `'PATH'` is neither in  `$_SERVER` nor in `$_ENV` for me, only in `getenv()` (Server is not empty, as ENV is, but does not hold the PATH variable by [my]  default)

**Comment by nicolas-grekas** [comment]
Is that a guess or did you give it a try? To me it should fix the issue... :)

**Comment by lukas-staab** [comment]
I reimplemented it, you are right, it works like a charm. I did not expect that the intersection is empty. Thanks for the quick response!
