### ISSUE TITLE
Serializer Groups not working with Attribute

### ISSUE THREAD

**Issue by aakashtushar** [symfony/symfony#44067]
### Symfony version(s) affected

5.4.0-BETA2

### Description

Serializer Groups Attribute is being ignored or not working whiling serializing object.

### How to reproduce

```php
// src/Entity/Product.php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;

#[ORM\Entity]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Serializer\Groups(['show_product', 'list_product'])]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Serializer\Groups(['show_product', 'list_product'])]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    #[Serializer\Groups(['show_product'])]
    private $description;
}
```

```php
// src/Controller/ProductController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    public function index(ProductRepository $productRepository)
    {
        $products = $productRepository->findAll();
        return $this->json($products, 200, [], ['groups' => 'list_product']);
    }
}
```

**Response:**
```json
[
  {
    "id": 1,
    "name": "Product 1",
    "description": "Product 1 description"
  },
  {
    "id": 2,
    "name": "Product 2",
    "description": "Product 2 description"
  }
]
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by aakashtushar** [comment]
@xabbuh I figured the issue was with the configuration. I had registered GetSetMethodNormalizer as service.

```yaml
services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags: [serializer.normalizer]
```

Removing this fixes the issue.

**Comment by grambas** [comment]
> @xabbuh I figured the issue was with the configuration. I had registered GetSetMethodNormalizer as service.
> 
> ```yaml
> services:
>     get_set_method_normalizer:
>         class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
>         tags: [serializer.normalizer]
> ```
> 
> Removing this fixes the issue.

I had same issue too by upgrading symfony 5.4 to 6.4. A lot of keys in response were missing . Registering  GetSetMethodNormalizer as service as a service resolved my problem too
