### ISSUE TITLE
[DependencyInjection] Preload file fatal error

### ISSUE THREAD

**Issue by ovrflo** [symfony/symfony#44074]
### Symfony version(s) affected

5.4.0-BETA2, 6.0.0-BETA2

### Description

Tested beta2 with preloading and got

```
PHP Fatal error:  Uncaught Error: Call to a member function set() on int in var/cache/prod/App_KernelProdContainer.preload.php:13
Stack trace:
#0 config/preload.php(4): require()
#1 {main}
  thrown in var/cache/prod/App_KernelProdContainer.preload.php on line 13
```

It ends up including the main container class file and treating it like it returns an instance of the Container.

### How to reproduce

Generate the cache with preloading. The error will be in `var/cache/prod/App_KernelProdContainer.preload.php` line 4.

### Possible Solution

I would gladly help fix this issue, but I don't feel comfortable messing with the Dependency Injection Container.

**Comment by nicolas-grekas** [comment]
Can you provide a reproducer? Doesn't the included file return the container?

**Comment by ovrflo** [comment]
I really thought I could get away without the reproducer 😁
I'm pretty sure it happens with a vanilla install. Give me a few minutes to try to put it together.

**Comment by ovrflo** [comment]
I could reproduce the bug by:
- installing a fresh skeleton -- `symfony new --version=next sf54`
- configuring my local fpm with preload path `opcache.preload=/path/to/sf54/var/cache/dev/App_KernelDevDebugContainer.preload.php`

Got the same error:
```
[16-Nov-2021 12:40:00] NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on int in sf54/var/cache/dev/App_KernelDevDebugContainer.preload.php:13
Stack trace:
#0 {main}
  thrown in sf54/var/cache/dev/App_KernelDevDebugContainer.preload.php on line 13
```

There is one interesting thing though... If you manually run it (e.g: `php var/cache/dev/App_KernelDevDebugContainer.preload.php`) it doesn't throw anything.

**Edit:** do you want me to push a repo? I figured it's easier for both of us without a reproducer-repo.
