### ISSUE TITLE
controller file response add a line break at the begin of the file

### ISSUE THREAD

**Issue by idriss-code** [symfony/symfony#44071]
### Symfony version(s) affected

5.3

### Description

controller file response add a line break at the begin of the file

same bug with

new Response($fileContent);

new BinaryFileResponse('/test');

### How to reproduce

$file = new File('/home/tmp/test.tgz');

return $this->file($file);

### Possible Solution

use ob_clean

thx to Jarek Jakubowski
https://stackoverflow.com/questions/39717669/symfony-binaryfileresponse-cuts-off-end-of-file

### Additional Context

apache2                          2.4.25-3+deb9u10 

debian 9

php 7.4

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
