### ISSUE TITLE
Cannot declare EntityManager & other lazy loaded classes

### ISSUE THREAD

**Issue by michaelHottomali** [symfony/symfony#44093]
### Symfony version(s) affected

5.4.0

### Description

![Screen Shot 2021-11-15 at 4 10 48 PM](https://user-images.githubusercontent.com/62905218/142075615-291f78eb-c4ac-4e77-9884-3c852f3992e4.png)

### How to reproduce

Rebuild schema or perform any API call.

**Comment by xabbuh** [comment]
I think we merged something around this recently. Can you check if the issue still persists?

And if so, can you then create a small example application that allows to reproduce it?

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/44063
