### ISSUE TITLE
Serious problem in error reporting

### ISSUE THREAD

**Issue by fazliddin** [symfony/symfony#44107]
### Symfony version(s) affected

5.3

### Description

I have installed `EasyAdmin` and created some class and since I did not like it I deleted it via composer. After that symfony app stoped working giving following weird error:

![Screenshot 2021-11-17 at 17-26-41 Class App Controller CRM ClientsCrudController does not exist in var www vhosts oqila_eap](https://user-images.githubusercontent.com/5574503/142200544-e81ad94b-9c1f-4402-982c-19dd0a68d38b.png)

which states that `App\Controller\CRM\ClientsCrudController` class is missing and it is imported from `/var/www/vhosts/oqila_eap/config/routes/annotations.yaml`. But class exists and yaml file has nothing related with it.

It turns out `ClientsCrudController` extends some `EasyAdmin` class and now it does not exist.

So I think, true php error must be
```
Error: ClientsCrudController.php file, Line: 6
EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController does not exists
```

### How to reproduce

```
<?php

namespace App\Controller\CRM;

use App\Entity\CRM\Clients;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class ClientsCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Clients::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            'id', 'assigned_user_id', 'status', 'level', 'legal_company_name', 'brand_name', 'person_full_name', 'phone_number', 'email', 'website', 'address', 'notes', 'due_date'
        ];
    }
}

```

**Comment by stof** [comment]
Regarding the non-existent parent class, a PHP class cannot be defined if its parent class is missing. So the `ClientsCrudController` indeed cannot exist in the PHP process (forcing to load it would trigger a fatal error due to the missing AbstractCrudController).

Regarding the weird error page, `highlight_file` is a core PHP function available since PHP 5: https://www.php.net/highlight_file. So there is something weird in your setup.

**Comment by fazliddin** [comment]
Sorry, it turns out `highlight_file` function was disabled by my settings
