### ISSUE TITLE
Mailers should not depend on Symfony's HttpClientInterface

### ISSUE THREAD

**Issue by SamMousa** [symfony/symfony#44124]
### Description

Currently the mailer implementations all have an optional dependency on (among other things) an instance of `HttpClientInterface`.

This is suboptimal for several reasons:
- It hides the fact that some transports actually have a required dependency.
- It forces users of this component to also use Symfony Http Client.

Since anyone using the Symfony HttpClient will also have the PSR-18 client that it provides, it makes sense to have the transport implementations for this component require a PSR-18 instead.

### Example

Current code that creates the http client if it is not passed in:
```php
public function __construct(HttpClientInterface $client = null, EventDispatcherInterface $dispatcher = null, LoggerInterface $logger = null)
    {
        $this->client = $client;
        if (null === $client) {
            if (!class_exists(HttpClient::class)) {
                throw new \LogicException(sprintf('You cannot use "%s" as the HttpClient component is not installed. Try running "composer require symfony/http-client".', __CLASS__));
            }

            $this->client = HttpClient::create();
        }

        parent::__construct($dispatcher, $logger);
    }
```

New code would look something like this:
```php
public function __construct(Psr18ClientInterface $client = null, EventDispatcherInterface $dispatcher = null, LoggerInterface $logger = null)
    {
        $this->client = $client;
        if (null === $client) {
            if (!class_exists(Psr18Client::class)) {
                throw new \LogicException(sprintf('You cannot use "%s" as the HttpClient component is not installed. Try running "composer require symfony/http-client". Or alternatively pass in your own PSR-18 implementation', __CLASS__));
            }

            $this->client = new Psr18Client();
        }

        parent::__construct($dispatcher, $logger);
    }
```

**Comment by stof** [comment]
well, this would force us to  implement the code against the PSR-18 interface (which then also requires injecting PSR-17 factories) instead of the simpler `symfony/http-client-contracts` interface.

**Comment by SamMousa** [comment]
Sure, there will be some changes required; alternatively you could add the http client as a normal dependency to extensions like https://packagist.org/packages/symfony/sendgrid-mailer (currently it is just a dev dependency).

By the way note that the `Psr18Client` class implements those as well: https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/HttpClient/Psr18Client.php

So the constructor of the transport(s) might get some more arguments, but for the autowiring part in the case of full symfony you'd just pass the same `Psr18Client` object.

**Comment by nicolas-grekas** [comment]
What @stof is telling is that this in turn would require lasagna layers of psr7+17 dependencies.
Clearly that won't happen.
Thanks for proposing.

**Comment by stof** [comment]
> * It forces users of this component to also use Symfony Http Client.

Not exactly. It forces to use `symfony/http-client-contracts`. You could build a different implementation of those interfaces if you don't like `symfony/http-client`.

**Comment by SamMousa** [comment]
> You could build a different implementation of those interfaces if you don't like `symfony/http-client`.

Yeah, I'm aware. It's what I'm doing right now, building an adapter that provides the Symfony interface given some PSR implementations. 

(This is where it'll live, for future googlers: https://github.com/SAM-IT/symfony-http-psr18)
