### ISSUE TITLE
Method base64Encode missing in Symfony\Component\Mailer\DataCollector\MessageDataCollector

### ISSUE THREAD

**Issue by Xesau** [symfony/symfony#44127]
### Symfony version(s) affected

5.4.0-BETA2

### Description

When opening the Emails tab in the Profiler and you have sent at least 1 email, the following error pops up:

```Neither the property "base64Encode" nor one of the methods "base64Encode()", "getbase64Encode()"/"isbase64Encode()"/"hasbase64Encode()" or "__call()" exist and have public access in class "Symfony\Component\Mailer\DataCollector\MessageDataCollector".```

### How to reproduce

1. Send one email with an HTML body using Symfony Mailer
2. Open the Emails tab in the Profiler for the appropriate Request

### Possible Solution

Add the following code to src/Symfony/Component/Mailer/DataCollector/MessageDataCollector.php:

```php
    public function base64Encode(string $body)
    {
        return base64_encode($body);
    }
```

**Comment by stof** [comment]
could it be that you updated WebProfilerBundle without updating symfony/mailer ?

@javiereguiluz we might miss a conflict rule in WebProfilerBundle 5.4 to forbid older versions of symfony/mailer

**Comment by Xesau** [comment]
It was indeed the case that mailer was not updated to 5.4 yet. My bad.

**Comment by xabbuh** [comment]
Please do not work on this issue. I have someone whom I will guide through the contribution process tomorrow and this looks like a good issue to start with.
