### ISSUE TITLE
[Cache] Failed to save key of type array

### ISSUE THREAD

**Issue by adrienfr** [symfony/symfony#44138]
### Symfony version(s) affected

5.4.0-BETA3

### Description

When testing SF 5.4, the following warning occurs on entities with `Assert` annotations and `PhpFilesAdapter` cache.

`Failed to save key "App%5CEntity%5CPartner%24name" of type array: Cache key "App%5CEntity%5CPartner%24name" has non-serializable "array" value.`

### How to reproduce

```php
class Partner
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_partner", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $idPartner;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=50)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min=2,
     *     max=50,
     *     minMessage="partner.name.min_size",
     *     maxMessage="partner.name.max_size"
     * )
     */
    private $name;
...
}
```

### Additional Context

```php
[
  "key" => "App%5CEntity%5CPartner%24name"
  "exception" => Symfony\Component\Cache\Exception\InvalidArgumentException {#3436 ▼
    #message: "Cache key "App%5CEntity%5CPartner%24name" has non-serializable "array" value."
    #code: 0
    #file: "/var/www/morningcroissant/symfony/vendor/symfony/cache/Adapter/PhpFilesAdapter.php"
    #line: 229
    -previous: ErrorException {#3429 …}
    trace: {▶}
  }
  "cache-adapter" => "Symfony\Component\Cache\Adapter\PhpFilesAdapter"
]
```

**Comment by nicolas-grekas** [comment]
Can you please share a small reproducing app?

**Comment by adrienfr** [comment]
> Can you please share a small reproducing app?

[Here](https://github.com/adrienfr/sf-cache-entities-with-assert-annotations) is a small reproducer. 
Steps to reproduce :
- `composer install`
- `symfony server:start`
- `php bin/console doctrine:migrations:migrate`
- Go to http://127.0.0.1:8000/index
- Open DebugBar and see Warnings
<img width="1048" alt="Capture d’écran 2021-11-19 à 11 58 06" src="https://user-images.githubusercontent.com/4313077/142611735-52fa86e4-757b-43fb-abae-9002ad1550d5.png">

**Comment by nicolas-grekas** [comment]
I mean an app that I could install myself on my local machine please?

**Comment by nicolas-grekas** [comment]
OH I missed the link, let me try it now!

**Comment by nicolas-grekas** [comment]
I'm not able to reproduce the issue, I see no warning here :(

**Comment by adrienfr** [comment]
> I'm not able to reproduce the issue, I see no warning here :(

Could you try with PHP 7.3? 
```bash
php -v
```

```
PHP 7.3.29-to-be-removed-in-future-macOS (cli) (built: Sep  6 2021 05:14:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by nicolas-grekas** [comment]
Same with this, no issue:
PHP 7.3.31-2+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Oct 22 2021 12:34:45) ( NTS )

**Comment by adrienfr** [comment]
That was my only lead that could have explained the difference :/

**Comment by nicolas-grekas** [comment]
You might want to debug/dump the value that fails to be serialized and figure out where it comes from...

**Comment by adrienfr** [comment]
Already tried but couldn't trace why this can't be serialized :
```php
PhpFilesAdapter.php on line 229:
array:3 [▼
  0 => Doctrine\ORM\Mapping\Column {#468 ▼
    +name: "name"
    +type: "string"
    +length: 50
    +precision: null
    +scale: null
    +unique: false
    +nullable: false
    +options: []
    +columnDefinition: null
  }
  1 => Symfony\Component\Validator\Constraints\NotBlank {#469 ▼
    +message: "This value should not be blank."
    +allowNull: false
    +normalizer: null
    +payload: null
    +groups: array:1 [▶]
  }
  2 => Symfony\Component\Validator\Constraints\Length {#499 ▼
    +maxMessage: "partner.name.max_size"
    +minMessage: "partner.name.min_size"
    +exactMessage: "This value should have exactly {{ limit }} character.|This value should have exactly {{ limit }} characters."
    +charsetMessage: "This value does not match the expected {{ charset }} charset."
    +max: 50
    +min: 2
    +charset: "UTF-8"
    +normalizer: null
    +allowEmptyString: false
    +payload: null
  }
]
```

**Comment by adrienfr** [comment]
It somehow seems like this is related to `groups` not explicitly defined in `@Assert`. With the following code, there is no more issues:
```php
/**
* @var string
*
* @ORM\Column(name="name", type="string", length=50)
* 
* @Assert\NotBlank(groups="Default")
* @Assert\Length(groups="Default",
*     min=2,
*     max=50,
*     minMessage="partner.name.min_size",
*     maxMessage="partner.name.max_size"
* )
*/
```

**Comment by adrienfr** [comment]
@nicolas-grekas just to double-check, you don't have any warnings at all?
<img width="132" alt="Capture d’écran 2021-11-19 à 14 33 30" src="https://user-images.githubusercontent.com/4313077/142631293-8150edf4-312d-4043-a0af-f81bb6dbf15b.png">

Because with new Profiler re-design, warning are not displayed on main page:
<img width="1223" alt="Capture d’écran 2021-11-19 à 14 33 36" src="https://user-images.githubusercontent.com/4313077/142631377-bbcdf013-60e3-41c5-b648-781f725304d0.png">

I have to click on "All messages" to display warnings:
<img width="1223" alt="Capture d’écran 2021-11-19 à 14 33 43" src="https://user-images.githubusercontent.com/4313077/142631414-31ba0be5-52cd-49b4-960a-4cc07b0b701e.png">

**Comment by stof** [comment]
@nicolas-grekas could it be related to https://github.com/symfony/symfony/commit/aa4fb0c2c4c3a5ef135ea671c7c6cd03ece56d9e#diff-eadef5e494fbfb85346e70992f4b18994df0b999b7d336c9cece5ab9e9a4a18a unsetting the property ?

**Comment by adrienfr** [comment]
Thanks @stof for this lead! 
I confirm that there is no more warnings when I comment `//unset($this->groups)`; and re-add `$knownOptions['groups'] = true;` in `Constraint.php` on both my reproducer and my app

<img width="711" alt="Capture d’écran 2021-11-19 à 15 00 13" src="https://user-images.githubusercontent.com/4313077/142634829-88e80841-1947-4c34-b568-bf489f891181.png">


<img width="131" alt="Capture d’écran 2021-11-19 à 14 55 16" src="https://user-images.githubusercontent.com/4313077/142634364-f936d231-78da-46cc-a54d-acab03d503db.png">

**Comment by nicolas-grekas** [comment]
> @nicolas-grekas just to double-check, you don't have any warnings at all?

I confirm I have nothing like that. Anyone else reproducing?

@adrienfr can you please debug the situation a bit more, at least show us the details of the previous `ErrorException`?

**Comment by adrienfr** [comment]
@nicolas-grekas could this be helpful?

<img width="1048" alt="Capture d’écran 2021-11-19 à 16 12 51" src="https://user-images.githubusercontent.com/4313077/142645718-b942c8e7-0afb-4b75-87b0-58174273fe18.png">

I'm available on Slack (Symfony Devs), username `adrienfr` if you need

**Comment by nicolas-grekas** [comment]
I would really need the "previous" exception.

**Comment by adrienfr** [comment]
> I would really need the "previous" exception.

"User Notice: serialize(): "groups" returned as member variable from __sleep() but does not exist"

**Comment by adrienfr** [comment]
Found this related issue but you might remember :) https://github.com/symfony/symfony/issues/28352

**Comment by nicolas-grekas** [comment]
OK, I now am able to reproduce. I need to run `bin/console c:c --no-warmup` before refreshing the browser.

**Comment by PhilETaylor** [comment]
Tagging my stack trace https://github.com/symfony/symfony/issues/44182 as it seems to be relevant

**Comment by nicolas-grekas** [comment]
Thanks for the details.

**Comment by adrienfr** [comment]
Thanks @nicolas-grekas
