### ISSUE TITLE
Can't create symfony app with composer

### ISSUE THREAD

**Issue by fabifont** [symfony/symfony#44148]
Command: `composer create-project symfony/website-skeleton first-symfony-app`

Output: 
```
Creating a "symfony/website-skeleton" project at "./first-symfony-app"

[InvalidArgumentException]
Could not find package symfony/website-skeleton with stability stable in a version installable using your PHP version, PHP extensions and Composer version.
```

PHP version: `PHP 8.0.12 (cli) (built: Nov 13 2021 20:25:00) ( NTS )`
Composer version: `Composer version 2.1.12 2021-11-09 16:02:04`
OS: `Linux arch 5.15.2-arch1-1 symfony/website-skeleton#1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux`

**Comment by stof** [comment]
@fabifont do you have the iconv and ctype extensions in your PHP setup ?

**Comment by fabifont** [comment]
@stof I should have them. I saw on Google that on Arch Linux I should uncomment a line in php.ini to enable it. I will check later and give you an answer.

**Comment by fabifont** [comment]
`iconv` extension is disabled by default on Arch. After uncommenting it in `php.ini` I can run `composer create-project symfony/website-skeleton first-symfony-app` without errors.
