### ISSUE TITLE
[RFC] New component HtmlSanitizer

### ISSUE THREAD

**Issue by tgalopin** [symfony/symfony#44144]
### Description

Following discussions with @DocFX and @nicolas-grekas, I'm opening this PR to request for comments on the idea of creating a new HtmlSanitizer component for Symfony 6.1, based on a package I developed: [html-sanitizer](https://github.com/tgalopin/html-sanitizer).

**Presentation**

html-sanitizer is a package I developed in 2018 as I needed a way to clean HTML while controlling precisely the resulting output. The alternatives at the time were limited, the biggest one being HTMLPurifier but it doesn't fit the same need (see [the comparison](https://github.com/tgalopin/html-sanitizer/blob/master/docs/4-comparison-with-htmlpurifier.md)).

html-sanitizer aims at cleaning user-provided HTML to safely display it in a web page. It has two main roles:

* preventing security attacks based on XSS or other technologies relying on execution of malicious code on the visitors browsers
* generating HTML that always respect a certain format (only certain tags/attributes/hosts/... allowed) to be able to consistently style the resulting output with CSS

**Proposal to integrate it to Symfony**

I would like to propose the integration of this package under the Symfony namespace. I have several reasons why I think it would make sense:

* HTML sanitation is a very common issue when dealing with content provided by users. In most of these cases, a WYSIWYG editor is required, and when using such editor, it is important for security purposes to filter the input before displaying it ;
* This package works well (it is used [in the symfony/demo application](https://github.com/symfony/demo/blob/main/composer.json#L41)), is well used ([installed 469k+ times](https://packagist.org/packages/tgalopin/html-sanitizer)) and is extensively tested (a lot of tests inspired from OWASP, Drupal and other key actors in this area) ;
* While it's a stable and used package, keeping in under my personal namespace probably prevents some people to use it, as it means I'm the only one maintaining it ;
* Integrating this package in Symfony would help when we will address the problem of WYSIWYG editors in Symfony UX (it'll happen for sure at some point) as we will be able to more safely rely on it to provide security ;
* The package already follows most (all?) Symfony best practices, is based on Symfony BC promise and had a complete integration with Symfony through [its bundle](https://github.com/tgalopin/html-sanitizer-bundle) ;

### Example

See the bundle README for an example of usage in Symfony:

https://github.com/tgalopin/html-sanitizer-bundle

**Comment by fabpot** [comment]
That sounds like a great idea :) As you've already mentioned, we should be very clear about the use cases we cover and the problems we don't want to solve (and will never solve). Having the boundaries well defined is key to the success of such a component.

**Comment by javiereguiluz** [comment]
I like this proposal a lot.

I have a question about the naming. What if we call it `Sanitizer` (and a method like `sanitizeHtml()`) instead of `HtmlSanitizer` (and a method like `sanitize()`) ?

My reasoning is that we could slightly increase the target of this component to not only sanitize HTML.

For example, as https://www.trojansource.codes/ showed recently, in source code files we should always sanitize these characters:

```
    'LRE (Left-to-Right Embedding) U+202A' => "\u{202A}",
    'RLE (Right-to-Left Embedding) U+202B' => "\u{202B}",
    'LRO (Left-to-Right Override) U+202D' => "\u{202D}",
    'RLO (Right-to-Left Override) U+202E' => "\u{202E}",
    'LRI (Left-to-Right Isolate) U+2066' => "\u{2066}",
    'RLI (Right-to-Left Isolate) U+2067' => "\u{2067}",
    'FSI (First Strong Isolate) U+2068' => "\u{2068}",
    'PDF (Pop Directional Formatting) U+202C' => "\u{202C}",
    'PDI (Pop Directional Isolate) U+2069' => "\u{2069}",
```

And maybe we could also "sanitize" contents for CLI apps (to not output non-printable chars for example).

-----

The analogy would be Twig's Escaper extension (https://github.com/twigphp/Twig/blob/3.x/src/Extension/EscaperExtension.php) which can escape HTML and other useful and related things.

**Comment by DocFX** [comment]
+1 @javiereguiluz that's something I raised too. Decoupling the component from potential connectors (YAML, XML, JSON, etc.) in addition to HTML content would be great (and open to extension).

I think the name could be sth like `WebSanitizer`, `ContentSanitizer` or else.

**Comment by tgalopin** [comment]
I'm fine with opening the package to other languages/formats if we find it useful, especially by just calling it Sanitizer instead of HtmlSanitizer for instance.

However before adding genericity I think it'd be useful to see if we have an actual need for another format, by having an example of another sanitation process that isn't just a function call (str_replace works well in most cases). Do you have an example in mind that would require a package with extensibility?

**Comment by nicolas-grekas** [comment]
On my side I'm not sure it make sense to have something else than html.
We don't want to build another validator/filter/normalizer component.
Filtering/normalizing HTML is a very specific task.
It's very not like yaml (which can be validated with Config) nor XML (see XSD).
Filtering unicode strings is useful, but I'm also not sure there is anything in common, from an API pov, with filtering HTML.

**Comment by tgalopin** [comment]
I tend to agree with Nicolas, especially because most other "sanitation" use cases I can think of are basically a series of smart search and replace.

**Comment by DocFX** [comment]
It's true this is clearly aimed at untrusted user-generated content, which is normally exclusively HTML (especially as long as you're dealing with web applications, which we are).

The only case I would think of is API I/O streams, while importing products and data being exchanged with non-webapps content -usually Java apps with heavy clients- (exporting would mean... "from your app", which is a SF app, so you're mostly back on HTML again).

As for CLI... I mean... What could be the use case of asking for long, potentially harmful input? I don't know.

So yeah, maybe this should be narrowed to HTML only as a promise. My head went too far on this idea. 😄

**Comment by stof** [comment]
I would keep the component focused only on HTML

**Comment by welcoMattic** [comment]
I like the idea, but as @fabpot says we need to be very clear and strict about the aim of such a component (i.e: it will not be a firewall against all XSS breaches.).

I would also keep it focused on HTML first, but designing it as `Sanitizer` with only one `HtmlSanitizer` and check later if it is legitimate to write `XmlSanitizer`, etc.

**Comment by tgalopin** [comment]
> I would keep the component focused only on HTML

I agree, let's stick to HTML. Should we name it HtmlSanitizer or Sanitizer though? Sanitizer is shorter but less precise, I prefer HtmlSanitizer (like CssSelector).

> We need to be very clear and strict about the aim of such a component (i.e: it will not be a firewall against all XSS breaches.)

I actually think it is indeed supposed to be a protection against all XSS breaches, that's the role of the component. It builds an entirely new HTML tree and only populate valid and safe elements from the original HTML. If we detect filtering issues regarding XSS or other frontend attacks, I would argue we should consider them as security issues.

What this package **isn't** is a "purifier": it's not made to keep the design intact. It will remove all CSS, scripts, data-attributes that aren't trusted, etc. It's focused on building an HTML string that will never contain unexpected tags/attributes.

I think its aim can be defined as: a component to ensure a user-provided HTML string can be safely displayed in a browser, keeping the structure and trusted attributes but removing everything else, usually used in combination with a WYIWYG editor.

**Comment by fabpot** [comment]
HtmlSanitizer seems better.

**Comment by OskarStark** [comment]
Yes HtmlSanitizer 😃

**Comment by dunglas** [comment]
For the record, there is now an experimental web standard for sanitizing HTML: https://wicg.github.io/sanitizer-api/
It defines the algorithm to apply as well as a set of interfaces for the web platform: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API

It would be nice to have such component in Symfony, and especially it if follows the standard.

**Comment by tgalopin** [comment]
Interesting, I never heard of this standard before. Do you know how likely it is that this standard is accepted and implemented in browsers?

**Comment by stof** [comment]
Well, this web standard returns DOM nodes. I don't think this is a good idea in our case. In the backend, you will store the HTML not the `DOMElement` instances.
And given that the HTML5 library requires using `$htmlParser->saveHTML($node)` instead of `$node->ownerDocument->saveHTML($node)` for proper formatting, we would even leak our parsing implementation if we don't serialize the DOMElement to HTML ourselves.
Also, the `serializeFor('div', unsanitized_string)` API returning a HTMLDivElement (which is what the `div` argument is about) cannot be replicated in PHP with ext-dom as the PHP API does not have HTMLElement at all. So it would not provide the same safety benefits IMO.

So my vote would be for keeping a `string` return type

> Do you know how likely it is that this standard is accepted and implemented in browsers?

According to https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API#browser_compatibility, both Chromium and Firefox already have implementations behing a flag.

**Comment by dunglas** [comment]
@stof sure, the public API doesn't fit very well in PHP, but we could adapt it to use strings and stay as close as possible from the standard for everything else, especially the [sanitization algorithms](https://wicg.github.io/sanitizer-api/#sanitizer-algorithms).
Having the ability to provide a context (the parent element) looks very useful.

**Comment by stof** [comment]
@dunglas I totally agree on that part.

**Comment by tgalopin** [comment]
Nice, I'll have to dig into the details of the standard to see what's feasible

**Comment by tgalopin** [comment]
> stay as close as possible from the standard for everything else, especially the sanitization algorithms.

With a quick look over the algorithms, it seems very close to what the html-sanitizer already does, in terms of algorithms. I'll have to check in details but implementing the algorithms doesn't seem too complicated.

> Having the ability to provide a context (the parent element) looks very useful.

I'm not sure what would be the use-case in PHP, do you have an example in mind? I can understand that in the browser, providing a parent node would help build the structure properly (inline vs block node, whether you can have a link or not in the content, etc), but what's the use case in PHP?

**Comment by dunglas** [comment]
You may want to store a block of HTML in DB that you will inject in a Twig template. Then you have the exact same constraints as in browsers: the sanitization will depend on the context.

**Comment by tgalopin** [comment]
What is the context you have in mind? In the standard, I seem to understand "context" as "parent node": it will be displayed in a div, in a section, etc. I'm not sure how that would affect a backend server: what would change in the sanitizer depending on this context?

**Comment by stof** [comment]
@tgalopin aren't they describing the rules that apply for each context ?
I guess that `div` and `section` probably use the same rules. The example in the spec uses `textarea` as the parent.

**Comment by stof** [comment]
According to https://wicg.github.io/sanitizer-api/#builtins-justification, this is mostly for cases where the element has special parsing.

**Comment by stof** [comment]
@tgalopin maybe https://checkmarx.com/blog/vulnerabilities-discovered-in-mozilla-bleach/ ([bleach](https://github.com/mozilla/bleach) is basically the python equivalent of the suggested HTMLSanitizer component) and the [spec biblio about mutated XSS](https://wicg.github.io/sanitizer-api/#biblio-mxss) can help you

**Comment by tgalopin** [comment]
For the record, I'm working on the improved component based on the standard here: https://github.com/tgalopin/symfony/tree/html-sanitizer/src/Symfony/Component/HtmlSanitizer

You can find a README with usage example. Feel free to send me feedback :) !

**Comment by stof** [comment]
@tgalopin having a mutable Config object seems weird to me. We tried to avoid that in recent components, as it makes things harder to reason about (the config could be mutated at runtime). You should have an immutable config object, with either cloning mutators or a mutable builder object create that config at the end.
Also having the config based on method calls is nice for standalone usage. But I fear it will be harder for the DI integration in FrameworkBundle (once immutable). We might need a `Config::fromArray()` method or something like that (depending on the solution chosen for the immutable config).

And you should add phpdoc describing the type of arrays in places using them.

And finally, you should avoid using `league/uri-parser` as dependency, as it is in maintenance mode since October 2019. You should use `league/uri` 6+ instead.

**Comment by tgalopin** [comment]
I applied the updates and opened https://github.com/symfony/symfony/pull/44681
