### ISSUE TITLE
Symfony console, bugs diplaying special characters [32->47m....

### ISSUE THREAD

**Issue by karastras** [symfony/symfony#44189]
### Symfony version(s) affected

4.26.9

### Description

Hello

When i use the Symfony/console in my projects, i have some display bugs in my VScode Terminal or in a Git Bash out of VScode. 

Some Specials caracters appears and its diffcult to read easly all the text from symfony/console.
As u can see on this picture, it's all right when i use my terminal, but if i use the Symfony console the issue is coming...

![example](https://user-images.githubusercontent.com/64403587/142843120-c8fc47e6-d806-4c15-b149-cdf229839414.JPG)

![exemple2](https://user-images.githubusercontent.com/64403587/142843854-695a899f-ddbd-4595-aca6-2ee40f16ffa8.JPG)

I' working on Win10, php 8, symfony Cli v4.26.9, "symfony/console": "5.3.*"

### How to reproduce

Just use "symfony -v" or 
"php/bin console create:entity" the bug comes after filling the first field
and all others commands from symfony console

**Comment by BahmanMehrdad** [comment]
This problem is when you use `PHP` command, it is better to download `Symfony binary` and use `symfony console make:entity` command.
This problem is not related to the Symfony.

**Comment by karastras** [comment]
You're right, when i use `symfony console make:entity` there is no problem....
So i will look with the `PHP` command issues.
Thanks to you!

**Comment by stof** [comment]
The weird character you see are control characters for ANSI colors. It looks like the core logic detecting color support fails in your case sometimes.
