### ISSUE TITLE
[Process] argv array in env resulting in "Array to string conversion" error

### ISSUE THREAD

**Issue by plandolt** [symfony/symfony#44197]
### Symfony version(s) affected

5.3.11

### Description

After upgrading the process component from 5.3.7 to 5.3.11 I sometimes get the following error:
`Notice: Array to string conversion` on https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Process/Process.php#L344

A simple `dump($k, $v)` showed `"argv"` and `[]`.

### How to reproduce

not sure (yet) but version 5.3.11 required.

**Comment by nicolas-grekas** [comment]
Can you please provide a reproduder for this? I fail to see how this can happen.

**Comment by rmj-s** [comment]
I'm also facing this issue. `is_string` check was removed for `$_SERVER` values in #44070, resulting in `argv = []` to be passed here:
https://github.com/symfony/symfony/blob/a8fc556267f7118d1f6922fbb712ff19b8fb956b/src/Symfony/Component/Process/Process.php#L344

**Comment by mpiecko** [comment]
I'm having exact the same Exception "Notice: Array to string conversion" after the update when using `Process::fromShellCommandline()` ... will try to narrow the issue.

![image](https://user-images.githubusercontent.com/209899/142939186-b1811543-e0f4-4078-88eb-33e0dd69a47c.png)

**Comment by nicolas-grekas** [comment]
Thank you all but there is no question whether some of you experience this or not.
The question is rather: how do *I* reproduce so that I could fix it?
Alternatively, could you please debug where this `argv` array comes from?
E.g. what does `var_dump($env)` show for you right before the call to `array_intersect_key()` in `getDefaultEnv()`? And just after it?

**Comment by mpiecko** [comment]
Ok, I dumped the $env array in the loop. and it seems this is the item which fails: 
`"argv" => []`

**Comment by nicolas-grekas** [comment]
At which line did you dump this please?

**Comment by mpiecko** [comment]
Yes, sorry:
https://github.com/symfony/symfony/blob/a8fc556267f7118d1f6922fbb712ff19b8fb956b/src/Symfony/Component/Process/Process.php#L344

![image](https://user-images.githubusercontent.com/209899/142941716-423c26c3-1eae-4a37-9ab3-fc757c806987.png)

**Comment by nicolas-grekas** [comment]
OK thanks. Can you please try dumping as I suggested in https://github.com/symfony/symfony/issues/44197#issuecomment-975948285?

**Comment by mpiecko** [comment]
This is the only array value from the `$env` variable:

![image](https://user-images.githubusercontent.com/209899/142941900-6139db21-da1d-486d-8e8b-498a029ce18a.png)

**Comment by nicolas-grekas** [comment]
Can you please try #44208?

**Comment by mpiecko** [comment]
Yes, that fixed it 🎉. Just FYI: both items `argv` and `argc` where available in an $env dump before and after `array_intersect_key()` Comment: [#44197](https://github.com/symfony/symfony/issues/44197#issuecomment-975948285)

**Comment by nicolas-grekas** [comment]
Thanks for the help debugging this!

**Comment by pks0268** [comment]
Notice: Array to string conversion coming on before response from the version 4.4

**Comment by ghnp5** [comment]
Hey. I'm using v7.3, and I'm getting this same problem.
Any ideas of what I can do?
Thanks!

Is there a way to just not pass the envs from PHP to the command being run?
Looking at the code, it doesn't seem to be possible.
