### ISSUE TITLE
Validator not installable with "enable_annotations" error in 6.0 beta3

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#44195]
### Symfony version(s) affected

6.0.0-BETA3

### Description

Hi!

On 6.0 only (I'm not sure if this is new to beta 3 or not), you get an error when installing the `validator` component using PHP 8.0. This was caught by the MakerBundle test suite.

### How to reproduce

Using PHP 8.0:

```
composer create-project symfony/skeleton:6.0.x-dev sf6_validator
cd sf6_validator
composer require validator
```

Result: 

```
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In FrameworkExtension.php line 1443:
!!                                                                                 
!!    "enable_annotations" on the validator cannot be set as the PHP version is l  
!!    ower than 8 and Doctrine Annotations support is disabled. Consider upgradin  
!!    g PHP.                                                                       
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by stof** [comment]
the message can only be a lie: you cannot install Symfony 6 on PHP lower than 8, as it requires PHP 8. there is a bug somewhere (probably a bad merge-up or a bad removal of the PHP version check)

**Comment by fancyweb** [comment]
https://github.com/symfony/symfony/pull/44196 should fix it

**Comment by weaverryan** [comment]
Merged! Woh that was fast!
