### ISSUE TITLE
ClockMock requires runInSeparateProcess to take effect

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#44217]
### Symfony version(s) affected

5.3.11

### Description

When using `ClockMock` to mock time in a test, `time()` is mocked in the test all the time, but not always in the SUT.

I found 2 workarounds:
- putting the time-sensitive test first in the test class
- using `@runInSeparateProcess`

### How to reproduce

Clone https://github.com/greg0ire/clock-mock-reproducer
Run `vendor/bin/phpunit`

**Comment by nicolas-grekas** [comment]
Not sure we can do anything about it see this for how to work around this limitation:
https://github.com/symfony/symfony/blob/a5aaf2c9dc9cc04e472af32d3427a98c5ecebcb8/src/Symfony/Component/HttpKernel/phpunit.xml.dist#L35

**Comment by greg0ire** [comment]
@nicolas-grekas thanks

Given the number of workarounds, I think it's fine, but IMO they should be documented at https://symfony.com/doc/current/components/phpunit_bridge.html#clock-mocking

Also, I tried applying your suggestion, it does not seem to have an effect.

**Comment by stof** [comment]
@greg0ire have you used the right namespace ?

Also, this is already mentioned in the `Troubleshooting` section of the doc: https://symfony.com/doc/current/components/phpunit_bridge.html#troubleshooting

**Comment by greg0ire** [comment]
Thanks @stof, @nicolas-grekas ' workaround does work, I made 2 careless mistakes:
- I used a class name instead of a namespace
- I copied the class name of the project where I experienced the bug
