### ISSUE TITLE
Define template in Form Type?

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/symfony#44218]
### Description

Even with many years of Symfony experience, I'm still struggling with custom form types. Over the years I've spent many hours on debugging forms because I forgot to define the new template in `config/packages/twig.php` or having a typo in the block names.

Why can't the template not be set in the form type itself?

### Example

```
final class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) : void
    {
        $builder
            ->add('username');
        // ...
    }
    
    public function getTemplate() : string
    {
        return 'User/form.html.twig';
    }
}

```

**Comment by stof** [comment]
form types don't have a template each. The rendering is done with form themes.
In my projects, all my custom types have their theme-based rendering defined in the same form theme, not in one per type.

**Comment by yceruto** [comment]
I agree with @stof. Also, a form type is reusable and can be rendered in different ways depending on the form theme where it's used.

**Comment by stephanvierkant** [comment]
I love Symfony because it's very easy to start with and at the same time highly configurable for the advanced user. I think custom form types are the exception.

While it's very easy to change a template in the controller with `->render($templateName)`, changing the template of a form is quite hard. I think this should be made easier.

**Comment by stof** [comment]
@stephanvierkant the point is that form types are not responsible for choosing the template at all. The form rendering layer chooses blocks in the form theme for each FormView based on the type. but if each type can reconfigure the form theme, it becomes a huge mess (a form theme would then impact other fields too).

I'm not even sure using the `{% form_theme %}` Twig with anything else than the root FormView works without bugs, and what you ask here relies on this working (and on more complexity)

**Comment by xabbuh** [comment]
I am closing here as I also do not see this happening based on what @stof explained.
