### ISSUE TITLE
Invalid Redis socket DSN, the "dbindex" parameter must be a number.

### ISSUE THREAD

**Issue by mathielen** [symfony/symfony#44215]
### Symfony version(s) affected

4.4.34

### Description

When the Cache component is configured with a Redis DSN pointing to a socket (eg. `redis:///var/run/redis/redis-server.sock`), an error is thrown: `Invalid Redis DSN: "redis:///var/run/redis/redis-server.sock", the "dbindex" parameter must be a number.`

This is probably due to #43359 with fix #44043 and an incorrect `preg_match` in [L151](https://github.com/a1812/symfony/blob/4.4/src/Symfony/Component/Cache/Traits/RedisTrait.php#L151).

### How to reproduce
 
```php
<?php
// config/packages/cache.php

use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $cache = $framework->cache();

    $cache->app('cache.adapter.redis')
        ->defaultRedisProvider('redis:///var/run/redis/redis-server.sock');

    $cache->pool('my_pool.cache')->adapters(['cache.app']);
};
```

### Possible Solution

Skip the `preg_match` check if `$params['host']` is not set?

**Comment by stof** [comment]
Looks like the code wants to use the URL path both for the unix scoket path and the DB index at the same time

**Comment by UBERPHP** [comment]
I have the same issue, my env parameter: `REDIS_DSN=redis://superpass@/run/redis/domain.local.sock?persistent=1`
I was following https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html
v5.3.11 has this issue as well.

**Comment by nicolas-grekas** [comment]
Anyone up for a PR fixing this?

**Comment by stof** [comment]
I think the fix for the dbindex would be to look for it only if we have `isset($params['host']) && isset($params['path'])`. Also, the `!isset($params['dbindex']` looks weird to me, as `$params` is the output of `parse_url`

**Comment by UBERPHP** [comment]
if we are talking about format like this `redis://password@domain.com?path=/another/socket/domain.sock?dbindex=5&persistent=1&something=else`, 
vendor/symfony/cache/Traits/RedisTrait.php 
should be something like this:
![image](https://user-images.githubusercontent.com/17860283/143021711-015076d7-4709-4e58-9da2-ef407db26008.png)
and the final result would be:
![image](https://user-images.githubusercontent.com/17860283/143022216-8c712aba-e08e-4c9d-b5d7-187d647b11f8.png)

However, I think this might be more complicated, need to test all other parameters and other variations
p.s. as @stof mentioned, some parts looks weird to me as well

**Comment by UBERPHP** [comment]
based on  https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html
![image](https://user-images.githubusercontent.com/17860283/143024901-324544f5-a1cd-4aba-b667-49fca163712b.png)

and using format `'REDIS_DSN' => 'redis://superpass@/run/redis/domain.local.sock?persistent=1&anything=else/db-index=9',`

![image](https://user-images.githubusercontent.com/17860283/143025135-01e31f34-cabd-4eeb-b774-8c271deab0ea.png)
looks like correct (uses 'pconnect' and follows documentation)

**Comment by UBERPHP** [comment]
apologies for spamming (the previous example was wrongly interpreted by me), this should follow the documentation:
![image](https://user-images.githubusercontent.com/17860283/143026007-a5de5172-7ba8-4907-a953-0c971c1fb406.png)
however, it's not covering situation when 'db-index' is not set

**Comment by quazardous** [comment]
5.3.11 broken for `redis://localhost:6379/` (OK with `redis://localhost:6379` -> no ending slash)
was OK in 5.3.10

```
Invalid Redis DSN: "redis://localhost:6379/", the "dbindex" parameter must be a number.
```

**Comment by loevgaard** [comment]
We get the error in 5.3.12. Hasn't this been merged into the 5.3 branch?

**Comment by nicolas-grekas** [comment]
The patch is in 5.3.12 I confirm.
Looks like #44232 might not be enough?
Please send a PR if you're affected and can figure out the proper fix.

**Comment by loevgaard** [comment]
Hi, @nicolas-grekas 

This is the diff between 5.3.10 and 5.3.11 (5.3.10 works):

```diff
- if (!isset($params['dbindex']) && isset($params['path']) && preg_match('#/(\d+)$#', $params['path'], $m)) {	
-                $params['dbindex'] = $m[1];	
-                $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+ if (!isset($params['dbindex']) && isset($params['path'])) {
+                if (preg_match('#/(\d+)$#', $params['path'], $m)) {
+                    $params['dbindex'] = $m[1];
+                    $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+                } else {
+                    throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s", the "dbindex" parameter must be a + number.', $dsn));
+                }
```

What was the reason for this change?

**Comment by nicolas-grekas** [comment]
What is linked in this issue: see #43359

**Comment by loevgaard** [comment]
Okay. Could we reopen this issue?

**Comment by thomas2411** [comment]
I have the same problem as @loevgaard with 5.3.12 What is weird in one project it works OK, in another one it doesn't work, while on both of them I have symfony/cache 5.3.12
I use REDIS locally with MAMP PRO: `CACHE_DSN='redis:///Applications/MAMP/tmp/redis.sock'`

**Comment by mathielen** [comment]
(removed)

The new problem is addressed here: https://github.com/symfony/symfony/issues/45277#issuecomment-1027794029

**Comment by nicolas-grekas** [comment]
@thomas2411 @mathielen you're affected by #45277, not by this issue.

@loevgaard do you have more insights about your issue about dbindex, or does #45281 also fix you issue?

**Comment by loevgaard** [comment]
I am not experiencing this problem anymore, however, can't be quite sure because I don't quite remember how I triggered the problem (forgot to jot it down :()

**Comment by nicolas-grekas** [comment]
OK, please report back with details when you can.

**Comment by loevgaard** [comment]
Okay, just got this error again: `Invalid Redis DSN: "redis://127.0.0.1:51148/", the "dbindex" parameter must be a number.`.

It happens in here: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Cache/Traits/RedisTrait.php#L153.

The `$dsn` inputted in line 85 (https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Cache/Traits/RedisTrait.php#L85) has this value: `redis://127.0.0.1:51148/`. An important thing to notice is that the environment variable is`REDIS_URL=redis://127.0.0.1:51148` (notice the missing trailing slash) and just as a test I added this `$dsn = trim($dsn, '/');` as the first line in the method and then everything works.

**Comment by nicolas-grekas** [comment]
Can you send a PR if you have the fix please?

**Comment by loevgaard** [comment]
Yes, I will, @nicolas-grekas. Thanks!

**Comment by loevgaard** [comment]
There you have it, @nicolas-grekas. I tested it on the application that gave the error :)
