### ISSUE TITLE
symfony/validation 4.4.31 -> 4.4.33 - Broke validation for URL without TLD

### ISSUE THREAD

**Issue by sazo** [symfony/symfony#44252]
### Symfony version(s) affected

4.4.33

### Description

URL validation changed between `symfony/validation:4.4.31` and `symfony/validation:4.4.33`. (4.4.32 does not exists) 
```
http://vat-rates/graphql/internal (Works with 4.4.31)
http://vat-rates/graphql/internal (Rejected with 4.4.33)
```

Seems like its the changes in https://github.com/symfony/symfony/pull/43388 that broke it.

### How to reproduce

```
<?php

declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Validation;

$wrongUrl = 'http://vat-rates/graphql/internal';
$urlValidator = Validation::createValidator();
$urlConstraint = new Constraints\Url();

var_dump($urlValidator->validate($wrongUrl, $urlConstraint)->count());
```

Outputs
```
4.4.31
php test.php                  
int(0)

4.4.33
php test.php
int(1)
```

### Possible Solution

Revert of https://github.com/symfony/symfony/pull/43388? maybe :)

**Comment by f2r** [comment]
I confirm this issue. My URL validators are broken now with some internal URL (docker) : "http://some-internal-domain:8080/api" : KO, but it work without "-": http://nginx:8080/api": OK

**Comment by OskarStark** [comment]
Friendly ping @DfKimera as you contributed
