### ISSUE TITLE
Error with cache PhpFilesAdapter.php

### ISSUE THREAD

**Issue by xenatis** [symfony/symfony#44256]
### Symfony version(s) affected

5.3.11

### Description

Hello,
I am having an issue with symfony cache, triggering the firewall of my host (infomaniak.com). The bug appends in PhpFilesAdapter.php, at line 145 `} elseif (\is_array($expiresAt = include $file)) {`.

This bug occure only in prod environnement , not in dev.

 server error log contains these two lines:
`dev2.mtrestauration.ch [Wed Nov 24 17:31:07.895529 2021] [fastcgi:error] [pid 28937:tid 140261951948544] (104)Connection reset by peer: [client 185.89.252.62:0] FastCGI: comm with server "/home/clients/7573ef37723d942376be65f1b4365d88/.config/apache/my.domain.ch/.fpm/php5.external" aborted: read failed: "Connection reset by peer"`

`dev2.mtrestauration.ch [Wed Nov 24 17:31:07.895597 2021] [fastcgi:error] [pid 28937:tid 140261951948544] [client 185.89.252.62:0] FastCGI: incomplete headers (0 bytes) received from server "/home/clients/7573ef37723d942376be65f1b4365d88/.config/apache/my.domain.ch/.fpm/php5.external"
`

### How to reproduce

Here we are.

I don't know how te reproduce this issue outside my host (Infomaniak) environnement. 

### Additional Context

Content of the cache file issuing the error:
[AEgM13ZzWZDKCG0XaHuQ.txt](https://github.com/symfony/symfony/files/7597488/AEgM13ZzWZDKCG0XaHuQ.txt)

**Comment by nicolas-grekas** [comment]
> The bug appends in PhpFilesAdapter.php, at line 145

How do you know that the issue happens at this line? Do you see any message that mentions it? If yes can you share it also, with any stack trace if you have one?

**Comment by xenatis** [comment]
I know this because I went through the function calls and logged each one until I found this one line.

Here is the result of `debug_backtrack(2)` :
```
array (
  0 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfony/cache/Traits/AbstractAdapterTrait.php',
    'line' => 227,
    'function' => 'doFetch',
    'class' => 'Symfony\\Component\\Cache\\Adapter\\PhpFilesAdapter',
    'type' => '->',
  ),
  1 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php',
    'line' => 260,
    'function' => 'getItem',
    'class' => 'Symfony\\Component\\Cache\\Adapter\\AbstractAdapter',
    'type' => '->',
  ),
  2 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php',
    'line' => 292,
    'function' => 'parse',
    'class' => 'Doctrine\\ORM\\Query',
    'type' => '->',
  ),
  3 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php',
    'line' => 1164,
    'function' => '_doExecute',
    'class' => 'Doctrine\\ORM\\Query',
    'type' => '->',
  ),
  4 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php',
    'line' => 1115,
    'function' => 'executeIgnoreQueryCache',
    'class' => 'Doctrine\\ORM\\AbstractQuery',
    'type' => '->',
  ),
  5 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfonycasts/reset-password-bundle/src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php',
    'line' => 106,
    'function' => 'execute',
    'class' => 'Doctrine\\ORM\\AbstractQuery',
    'type' => '->',
  ),
  6 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfonycasts/reset-password-bundle/src/Util/ResetPasswordCleaner.php',
    'line' => 46,
    'function' => 'removeExpiredResetPasswordRequests',
    'class' => 'App\\Repository\\ResetPasswordRequestRepository',
    'type' => '->',
  ),
  7 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfonycasts/reset-password-bundle/src/ResetPasswordHelper.php',
    'line' => 104,
    'function' => 'handleGarbageCollection',
    'class' => 'SymfonyCasts\\Bundle\\ResetPassword\\Util\\ResetPasswordCleaner',
    'type' => '->',
  ),
  8 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/src/Controller/ResetPasswordController.php',
    'line' => 98,
    'function' => 'validateTokenAndFetchUser',
    'class' => 'SymfonyCasts\\Bundle\\ResetPassword\\ResetPasswordHelper',
    'type' => '->',
  ),
  9 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfony/http-kernel/HttpKernel.php',
    'line' => 156,
    'function' => 'reset',
    'class' => 'App\\Controller\\ResetPasswordController',
    'type' => '->',
  ),
  10 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfony/http-kernel/HttpKernel.php',
    'line' => 78,
    'function' => 'handleRaw',
    'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel',
    'type' => '->',
  ),
  11 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/vendor/symfony/http-kernel/Kernel.php',
    'line' => 199,
    'function' => 'handle',
    'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel',
    'type' => '->',
  ),
  12 => 
  array (
    'file' => '/home/clients/123123123/sites/my.domain.ch/public/index.php',
    'line' => 20,
    'function' => 'handle',
    'class' => 'Symfony\\Component\\HttpKernel\\Kernel',
    'type' => '->',
  ),
)

```

Is any other data useful?

**Comment by nicolas-grekas** [comment]
Do you catch any exception thrown on those lines? What does it say?
On my side, I'm able to create the object from the file you shared above.
Without more detailed info, there's nothing we could do here unfortunately.

![image](https://user-images.githubusercontent.com/243674/143462534-ccca5d03-0502-45e6-a9d0-6a022df5f8ab.png)

**Comment by xenatis** [comment]
Unfortunately, the only info I can give you are the two lines from my host log, on the first post.

If the error do not come from Symfony, that means that it comes from my host and the php interpreter.
I will investigate in this direction.

Thanks for your time.

**Comment by xenatis** [comment]
After some further testing on my host, it seems that a PHP 7.4.25 error occurs when reading these strings. Weird...
  
No issue with php 8.0 or 7.3

**Comment by sdespont** [comment]
Same error today with Symfony 4.4.35 and PHP 7.4.25 at Infomaniak webhost.

**Comment by nicolas-grekas** [comment]
@sdespont please provide a reproducer so we can investigate.
