### ISSUE TITLE
symfony/process throwing error

### ISSUE THREAD

**Issue by ngoyal16** [symfony/symfony#44263]
### Symfony version(s) affected

4.4.35

### Description

Fix has been made in the branch but it is not released yet on packgist causing issue when new build is created using CI/CD.

https://github.com/symfony/symfony/pull/44208/files

### How to reproduce

NA

### Possible Solution

Already fixed have to release the version on packgist.

**Comment by fancyweb** [comment]
Hello, symfony/process v4.4.35 has been released yesterday and it includes the patch from https://github.com/symfony/symfony/pull/44208/files. It is available on packagist (https://packagist.org/packages/symfony/process#v4.4.35). What issue are you facing exactly?
