### ISSUE TITLE
Declaration of Symfony\Component\String\Slugger\AsciiSlugger::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#44275]
### Symfony version(s) affected

5.4.0-RC1

### Description

```
PHP Fatal error:  Declaration of Symfony\Component\String\Slugger\AsciiSlugger::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale()
```

### How to reproduce

Checking the source code, they seem to be incompatible currently?

### Additional Context

Versions installed

```
symfony/string                       v5.4.0-RC1 Provides an object-oriented...
symfony/translation-contracts        v3.0.0     Generic abstractions relate...
```

**Comment by fancyweb** [comment]
Hello, thank you for your report. This issue has already been resolved by https://github.com/symfony/symfony/pull/44246.

**Comment by dkarlovi** [comment]
Thanks @fancyweb I did check issues, but didn't consider PRs, sorry for the noise.
