### ISSUE TITLE
[Http Client] Sending Binary file data

### ISSUE THREAD

**Issue by arudolph-cxt** [symfony/symfony#44289]
Background:

An API i need to send to accepts binary file data through a POST endpoint. The recommended curl command looks like this: `curl --request POST --data-binary "@file.csv" https://api`

Approach:

Using the new http-client, I am trying the naive approach and pass a file handle resource to the body field:

```php
        $body = fopen('php://temp', 'wb+');
        // write stuff in it
        rewind($body);

        $response = $this->httpClient->request(
            'POST',
            $url,
            [
                'headers' => ['Content-Disposition' => "attachment; filename=$filename"],
                'body' => $body,
            ],
        );
```

Problem:

The API responds with a 500 Error because it does not accept this data.

On Stackoverflow a solution is suggested with curl, pretending it to be a PUT request and setting the custom method to POST: https://stackoverflow.com/questions/32627346/how-to-post-a-large-amount-of-data-within-php-curl-without-memory-overhead

this _works_ by just using curl functions:

```php
        $ch = curl_init();
        $options = array(
            CURLOPT_URL => $url,
            CURLOPT_PUT => 1,
            CURLOPT_INFILESIZE => filesize($fileName),
            CURLOPT_INFILE => ($in = fopen($fileName, 'r')),
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_HTTPHEADER => array(
                'Authorization: Bearer ' . $token,
                'Content-Type: text/csv',
                'Accept: text/plain',
                'Expect:'
            ),
            CURLOPT_RETURNTRANSFER => 1
        );
        curl_setopt_array($ch, $options);
        $result = strval(curl_exec($ch));
```

Now i try to make this work with the http-client:

```php
        $size = fstat($body)['size'] ?? null;

        $response = $this->httpClient->request(
            'PUT', // 'POST' tried as well
            $url,
            [
                'headers' => ['Content-Disposition' => "attachment; filename=$filename"],
                'extra' => [
                    'curl' => [
                        CURLOPT_PUT => 1,
                        CURLOPT_INFILE => $body,
                        CURLOPT_INFILESIZE => $size,
                        CURLOPT_CUSTOMREQUEST => 'POST',
                    ]
                ]
            ],
        );
```

But i get the exception `InvalidArgumentException('The HTTP method cannot be overridden using "extra.curl".');` in `\Symfony\Component\HttpClient\CurlHttpClient::validateExtraCurlOptions`

How can i accomplish this?

**Comment by nicolas-grekas** [comment]
you need to rewind $body, otherwise the stream is reading from the end, which means you're not sending anything

**Comment by arudolph-cxt** [comment]
> you need to rewind $body, otherwise the stream is reading from the end, which means you're not sending anything

Thats what i did, altough not inside the sample code. (added it now)

If i use an api-mock service like beeceptor.com i can see the expected data being sent.

**Comment by nicolas-grekas** [comment]
Oh, then you might want to declare the `Content-Length` explicitly as a header. It might be that the remote server doesn't handle chunked body requests?

**Comment by arudolph-cxt** [comment]
I tried that, for this attempt my code looks like:

```php
        $filename = \sprintf('sales_items_%s.csv', (new DateTimeImmutable())->format('d_m_Y__H_i_s'));
        rewind($body);
        $size = fstat($body)['size'] ?? null;
        $response = $this->httpClient->request(
            'POST',
            $url,
            [
                'body' => $body,
                'headers' => [
                    'Content-Disposition' => "attachment; filename=$filename",
                    'Content-Length' => $size,
                ],
            ],
        );
```
the response was a 500 with debug string:
```
*   Trying ************:443...
* Connected to **************** (****************) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.***************
*  start date: Oct 24 00:00:00 2021 GMT
*  expire date: Nov 21 23:59:59 2022 GMT
*  subjectAltName: host "**************" matched cert's "*.***************"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> POST /************************/sales-data/api?live=false HTTP/1.1
Host: *********************
Transfer-Encoding: chunked
Content-Disposition: attachment; filename=sales_items_26_11_2021__15_24_49.csv
Content-Length: 9001
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Type: text/csv
Accept: text/plain
User-Agent: Symfony HttpClient/Curl
Accept-Encoding: gzip

* Signaling end of chunked upload via terminating chunk.
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain
< Content-Length: 106
< Connection: keep-alive
< 
* Connection #0 to host ******************* left intact
```
any idea what else to try with the http-client instead of switching to curl method calls?

**Comment by nicolas-grekas** [comment]
The question that we should solve is why `Transfer-Encoding: chunked` is sent.
If you look at the code in CurlHttpClient, `CURLOPT_INFILESIZE` is set if you pass a `Content-Length`.
Can you try debugging the situation and figure out which code path is taken by the code and why `Transfer-Encoding` is sent?

**Comment by arudolph-cxt** [comment]
it doesnt let me set any of the CURL parameters that help me otherwise unfortunately, for example I get `Cannot set "CURLOPT_INFILE" with "extra.curl", use option "body" instead.` but i dont understand why this client is so restrictive. Can i set some flag "i know what im doing, let me write my own code"?

investigating what you mentioned...

**Comment by arudolph-cxt** [comment]
So regarding the chunked transfer-encoding, this seems to be an immutable characteristic of the initializer that is called as soon as i access the statuscode or content of the response, because its lazy.
this initializer immediately passes the response chunks through an iterator in \Symfony\Component\HttpClient\Response\CommonResponseTrait::initialize L156 and this seems to internally add the chunked http header.

Up until the end of the method \Symfony\Component\HttpClient\CurlHttpClient::request i dont see the Transfer-Encoding header being set, so the way i constructed the request is not the issue.

I wonder if this behavior can be disabled.

**Comment by stof** [comment]
The client does not let you set your own values for any curl option it uses internally, because options cannot have 2 values.

**Comment by nicolas-grekas** [comment]
I ran this and I don't see the transfer-encoding header:

```php
<?php
  
use Symfony\Component\HttpClient\HttpClient;

require __DIR__.'/vendor/autoload.php';

$client = HttpClient::create();

$body = fopen(__FILE__, 'r');
$size = dump(fstat($body)['size'] ?? null);
$response = $client->request(
    'POST',
    'https://symfony.com',
    [
        'body' => $body,
        'headers' => [
            'Content-Disposition' => "attachment; filename=file",
            'Content-Length' => $size,
        ],
    ],
);

dump($response->getStatusCode());
dump($response->getInfo('debug'));
```

Please ensure $size is not null in your case, and debug why the header faulty is sent...

**Comment by nicolas-grekas** [comment]
I'm especially interested in knowing if you hit this line:
https://github.com/symfony/symfony/blob/4e7e429b0cc82fc28278486505601ff2c225eb49/src/Symfony/Component/HttpClient/CurlHttpClient.php#L254

or this one:
https://github.com/symfony/symfony/blob/4e7e429b0cc82fc28278486505601ff2c225eb49/src/Symfony/Component/HttpClient/CurlHttpClient.php#L252

or none of them?

**Comment by nicolas-grekas** [comment]
@arudolph-cxt I'd be happy to gather your feedback here, I'm really not understanding why you experience this behavior and would be happy to figure it out. :pray:

**Comment by nicolas-grekas** [comment]
Closing here as we didn't spot any issue in the component so this might be related to another part of your stack.
Please provide more info if you can and we can reopen.
