### ISSUE TITLE
PHP 8.2: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#44281]
### Symfony version(s) affected

4.4, 5.3, 5.4, 6.0

### Description

Using the mbstring "encoding" `HTML-ENTITIES` is deprecated since PHP 8.2: https://github.com/php/php-src/pull/7177

> mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead

These occurrences should be replaced: https://github.com/symfony/symfony/search?q=html-entities

### How to reproduce

Use HtmlDumper from var-dumper component in php 8.2.

**Comment by derrabus** [comment]
Confirmed.

**Comment by nicolas-grekas** [comment]
@gharlan would you be able to work on a PR to get rid of this deprecation? It should target branch 4.4

**Comment by derrabus** [comment]
@nicolas-grekas Why did you close the issue?

**Comment by nicolas-grekas** [comment]
Bad button :)
But now that I think about it, we don't need an issue about that.
We already have a deprecation log in the CI.

**Comment by aleblanc** [comment]
Possible Solution:

```php
$string = "<div><p>tèé Заматеріалами \"&'+</p></div>";

echo "Original:".mb_convert_encoding($string, 'HTML-ENTITIES', 'UTF-8');
echo "\n";
echo "Solution:".mb_encode_numericentity(
    htmlspecialchars_decode(
        htmlentities($string, ENT_NOQUOTES, 'UTF-8', false)
        ,ENT_NOQUOTES
    ), [0x80, 0x10FFFF, 0, ~0],
    'UTF-8'
);
echo "\n";

```
