### ISSUE TITLE
symfony/mailer multipart structure looks odd

### ISSUE THREAD

**Issue by ampaze** [symfony/symfony#44290]
### Symfony version(s) affected

5.x.x

### Description

In Email.php there is a nice ASCII Chart showing how `symfony/mailer` composes multipart emails:

```php
/*
 * multipart/mixed
 *         |
 *         |------------> multipart/related
 *         |                      |
 *         |                      |------------> multipart/alternative
 *         |                      |                      |
 *         |                      |                       ------------> text/plain (with content)
 *         |                      |                      |
 *         |                      |                       ------------> text/html (with content)
 *         |                      |
 *         |                       ------------> image/png (with content)
 *         |
 *          ------------> application/pdf (with content)
````

May I ask how this was chosen? I find it odd, that the inline image for the html content is "related" to the whole "alternative" part, instead of only the html content. So maybe the chart should look something like this:

```php
/*
 * multipart/mixed
 *         |
 *         |------------> multipart/alternative
 *         |                      |
 *         |                      |------------> text/plain (with content)
 *         |                      |
 *         |                      |------------> multipart/related
 *         |                                             |
 *         |                                              ------------> text/html (with content)
 *         |                                             |
 *         |                                              ------------> image/png (with content)
 *         |
 *          ------------> application/pdf (with content)
````

### How to reproduce

Send an email with both html and text content and also have an inline image in the html content.

**Comment by nicolas-grekas** [comment]
I think that's what most email clients accept.
Trying to diverge from the habits usually means breaking some email clients out there.
What would be the motivation to do the change when we know the current structure just works?

**Comment by fabpot** [comment]
I agree with Nicolas. I spent a lot of time figuring out what works out there and that's what I came up with. I'm not opposed in fixing what does not work, but it should be well documented.

**Comment by ampaze** [comment]
My intention is to have the best compatibility with email clients out there, thats why I was asking how and why you chose this structure. How do you know that this structure "just works"? How did you figure out what works? Which email clients and email providers where tested?

We have been using the structure I outlined for many years (with Swiftmailer and a custom message) and have send millions of emails. When changing to Symfony Mailer I don't want to just switch over to a different structure without knowing if it works as good.

**Comment by ampaze** [comment]
Any news on this?

**Comment by nicolas-grekas** [comment]
Nothing to add on my side, I don't have the answers to your questions.

**Comment by ampaze** [comment]
Okay, so can maybe @fabpot answer my question from [two month ago](https://github.com/symfony/symfony/issues/44290#issuecomment-982497674)?

**Comment by stof** [comment]
Things that might help to move forward for a decision: investigating how Gmail, MS Outlook, Thunderbird and potentially other email clients are structuring the multipart messages they are sending, to compare.

**Comment by ampaze** [comment]
> Things that might help to move forward for a decision: investigating how Gmail, MS Outlook, Thunderbird and potentially other email clients are structuring the multipart messages they are sending, to compare.

Maybe @fabpot already did that? I just want to know how the current structure was decided.

A quick test shows that Thunderbird uses the second structure (so not the one Symfony uses).

**Comment by fabpot** [comment]
Took me a while, but I finally found what I used for reference :)

It's here: https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa563064(v=exchg.140)

**Comment by fabpot** [comment]
And just found the initial discussion on Swiftmailer about the same: https://github.com/swiftmailer/swiftmailer/issues/434
Hope this helps.

**Comment by ampaze** [comment]
For future historians:

I still think the current structure is wrong and it works only because email in general is a field of workarounds and supporting faulty implementations of all kinds for compatibility reasons.

Additionally, IMHO, one link to microsoft does not match your statement:

> I spent a lot of time figuring out what works out there and that's what I came up with.

My plan was to look for the best resource when I have a little more time, but as you already closed this issue maybe these will suffice for now:

* https://commons.apache.org/proper/commons-email/jacoco/org.apache.commons.mail/HtmlEmail.java.html (build method)
* http://www.mimekit.net/docs/html/Working-With-Messages.htm

**Comment by fabpot** [comment]
> Additionally, IMHO, one link to microsoft does not match your statement:
> 
> > I spent a lot of time figuring out what works out there and that's what I came up with.

I don't see how that does not match my statement. You ask for some more explanations about the source of the current structure and I gave you the reference of the diagram. That was the end of my investigation.

Anyway, I'm open to change things, but only with some solid background. As you said, email clients are full of bugs and workarounds.

**Comment by ampaze** [comment]
I asked for more details because I thought you actually tested your implementation in a wide array of email clients and therefore had more knowledge what works and what not. This was what I inferred from your statement I took issue with.

What kind of solid background would you need? I think that Thunderbird and Apache are some good references that implement it the way I recommend.
