### ISSUE TITLE
default installation on windows 10 not add .htaccess file

### ISSUE THREAD

**Issue by wnunezc** [symfony/symfony#44302]
### Symfony version(s) affected

5.3.7

### Description

after installing, and creating a project I have tried to create a controller.

```
symfony console make:controller
```

get error 404... in testing from browser

the problem is that `.htaccess` file has not deploit to public directory on creation of the project via command line with `--full` argument.

it was necessary for me to execute the following commands:

```
composer require symfony/apache-pack
git add composer.json composer.lock symfony.lock public/.htaccess
git commit -m "apache-pack"
```

Is this correct??? It is not in the documentation ...

### How to reproduce

Follow the Description...

**Comment by fd6130** [comment]
I think yeah? You need to `composer require symfony/apache-pack` to install the additional .htaccess .

**Comment by wnunezc** [comment]
> I think yeah? You need to `composer require symfony/apache-pack` to install the additional .htaccess .

And why does the installation not do this by default if it is a requirement for the Controller system to function correctly ...?

it is assumed that if I used the `--full` argument it was so that everything would be ready and not have to touch things ... and if not, this should be in the documentation !!! **data that I did not find in that place**

**Comment by xabbuh** [comment]
Well, the documentation assumes that you are using the web server provided by the Symfony CLI to serve your application (see https://symfony.com/doc/current/setup.html#running-symfony-applications). If you are using another web server instead, you need to configure it which we cover in https://symfony.com/doc/current/setup/web_server_configuration.html (that chapter is linked at the end of the introduction chapter).

I am closing here as there is nothing in the code that we need to change. Thank you for understanding.
