### ISSUE TITLE
Remaining indirect deprecation notices

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#44313]
When I run `php ./vendor/bin/phpunit` command, test is ok but display `Remaining indirect deprecation notices`

```
Testing started at 12:18 PM ...
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Testing C:\projects\karaka\tests\Controller


Time: 00:00.619, Memory: 28.00 MB

OK (1 test, 1 assertion)

Remaining indirect deprecation notices (1)

  1x: The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@link \Doctrine\DBAL\Logging\Middleware} or implement {@link \Doctrine\DBAL\Driver\Middleware} instead.
    1x in ProductControllerTest::testProduct from App\Tests\Controller

Process finished with exit code 0
```

ProductControllerTest.php
```
<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ProductControllerTest extends WebTestCase
{
    public function testProduct(): void
    {
        $client = static::createClient();
        $crawler = $client->request('POST', '/product');

        $this->assertResponseIsSuccessful();
    }
}
```
@nicolas-grekas  How can I fix this warning?

**Comment by derrabus** [comment]
You cannot. This has to be fixed by DoctrineBundle, see doctrine/DoctrineBundle#1429

**Comment by OskarStark** [comment]
You only need to take care of "direct deprecation notices"

**Comment by nicolas-grekas** [comment]
The deprecation we had in the Symfony codebase has been fixed in https://github.com/symfony/symfony/pull/44319
For inspiration maybe.

**Comment by wnunezc** [comment]
> The deprecation we had in the Symfony codebase has been fixed in #44319 For inspiration maybe.

status of it???

**Comment by wouterj** [comment]
It clearly says "has been fixed", in case you really want a status (which I think you do, because you just typed a comment containing an incomplete sentence followed by 3 question marks to indicate that you really need these people to do more free work for you).

**Comment by wnunezc** [comment]
I wonder why it says fixed; but when updating the package it is not updated and in the current version the notice continues to appear ...

![image](https://user-images.githubusercontent.com/1207306/145883288-6f8e96f0-6d41-489e-8471-11e884628bed.png)

![image](https://user-images.githubusercontent.com/1207306/145883323-00f89044-8c11-4a10-8f7d-d1c2f8beb1fa.png)

![image](https://user-images.githubusercontent.com/1207306/145883416-bdaf7bad-b9f5-4d18-9117-e7b74b8c46cf.png)

**Comment by evertharmeling** [comment]
> I wonder why it says fixed; but when updating the package it is not updated and in the current version the notice continues to appear ...
> 

As stated in this comment https://github.com/symfony/symfony/issues/44313#issuecomment-980803836 the deprecation message comes from a 'third-party-bundle' (not symfony), for the status check the referenced issue ;)
