### ISSUE TITLE
Introduce the concept of "current" and "future" sessions

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#44315]
Session is known to be a stateful service/object.

Therefore, if anyone depends on the content of the Session, it means that there will be big differences if you depend on the **current session** or the **future session**.

This means that if **any** app layer modifies the Session, you don't have any way of determining if this corresponds to the current session or the future session.

Also, an app might have different behaviors depending on the current session or the future session, like when session is cleared/migrated by Security or other tools.

As suggested in the title of this issue, the concept of current & future session helps making sure we have a trustable source of information when **reading** the session data, and also to make sure this session data is **unmodified** by any app layer, something that would make it untrustable in some cases.

Another advantage, maybe, is that this would help in making a differential of the current&future session in order to avoid saving it on each request if it hasn't changed.

There are possibly several ways to implement this, but the most BC ones I'm thinking about are the following:

* Replace the current `Session` service by a wrapper that would contain two different `Session` objects, one for the current one, and another for the future one.
* Implement it directly in the `Session` service, using a special AttributeBag for that purpose, and modifying the behavior of the Session.

IMO, both solutions should implement behavioral changes:

* Make sure all calls to accessors (like `get()`, `has()` and `all()`) are made to the **current** session
* Make sure all calls to mutators (like `set()`, `remove()`, `clear()` or `replace()`, or `invalidate()`) are made to the **future** session
* Add deprecation logs to warn users that the behavior will change in the next major

The first proposal would probably need changes to SessionFactory, and a `ImmutableSession` class, while the second one might need more work on the Session class, and use a new `ImmutableAttributeBag` class.

WDYT?

**Comment by stof** [comment]
The proposed API is confusing IMO. Not being able to read from the session in which you write means you cannot check whether a change is necessary or no (as you cannot check the state of the future session).

**Comment by Pierstoval** [comment]
@stof Then, it could be highly simplified by not applying the "behavioral changes" in the last second list.

Using the second proposal and a `$session->getCurrentImmutableSessionBag()` (or a better naming) would be backwards compatible with all past and future versions, since it would only add one method, and still make the feature available to everyone. It wouldn't even be part of the interface (just like `$session->getFlashBag()`).

This is a proposal, so making changes to the initial suggestion is definitely good to make it more consistent, thanks for your feedback :)

**Comment by ro0NL** [comment]
IIUC we could track all mutator calls, to then create a new accessor, eg. `hasCurrent`
