### ISSUE TITLE
[TwigBridge] label_attr not work

### ISSUE THREAD

**Issue by 123ValentinM** [symfony/symfony#44332]
### Symfony version(s) affected

5.3.11

### Description

Hi everebody.

Since symfony version 5.3.11 and more specifically twig-bridge version 5.3.11 https://github.com/symfony/twig-bridge/releases/tag/v5.3.11 the label_attr of my symfony form no longer works.

If I go back to twig-bridge 5.3.7 it works normally.

My symfony code : 
```

->add('type', ChoiceType::class, [

                'choices' => array(
                    "choice1" => 8,
                    "choice2" => 4,
                    "choice3" => 9,
                ),
                'attr' => [ 'class' => 'd-flex justify-content-between flex-wrap  custom-control custom-radio  pl-0 ml-2  mt-0 mt-lg-4'],
                // Label
                'choice_label' => function ($choice, $key, $value) {
                    return ucfirst($key);
                },
                "label_attr" => ["class" => "custom-control-label pl-1 mb-4 mr-3"],
                // Input
                'choice_attr' => function ($choice, $key, $value) {
                    return ['class' => 'custom-control-input'];
                },

                'data' => 8, 
                'label' => false, 
                'multiple' => false, 
                'expanded' => true 
            ]

```

My Twig code : 

`{{ form_widget(form.type) }}`

### How to reproduce

Use bootstrap 4 form theme with symfony form ChoiceType and twig-bridge 5.3.11.

### Possible Solution

I think the code for version 5.3.11 fixes some problem but apparently it creates more, or am I doing something wrong ?

### Additional Context

Thank for the help !

**Comment by stof** [comment]
@123ValentinM it looks like you were intentionally relying on the behavior fixed in #42323. and the reason it could be used for you case is that you were not rendering `form_label(form.type)` (or that you were expecting the same classes on that label).

@xabbuh we might need a `choice_label_attr` option to allow configuring the `label_attr` option of each choice in expanded mode (and maybe `choice_row_attr` too), similar to how we have `choice_attr`.

**Comment by xabbuh** [comment]
@stof see #18318 and #16834

**Comment by nspyke** [comment]
Hi @stof and @xabbuh 
I've hit this same issue. 
I was using `label_attr` to add the `radio-inline` class. 
e.g.
```
{{ form_row(form.foo, {'label_attr':{'class':'radio-inline'}}) }}
```
To work around I've had to copy the `checkbox_radio_label` block in my own form templates and put the removed code back.

Do you have another suggestion as how I can achieve this same result without having to maintain a copy of checkbox_radio_label?

**Comment by xabbuh** [comment]
closing here in favor of #18318
