### ISSUE TITLE
Upd symfony from 4.4 to 5.4

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#44337]
`The service "security.authorization_checker" has a dependency on a non-existent service "security.authentication_manager". Did you mean one of these: "security.authorization_checker", "security.authentication_utils", "security.authentication.manager", "security.authentication.guard_handler"?
`

Any ideas how to fix this?

**Comment by stof** [comment]
@wouterj could we have a bug when the new authentication system is not enabled ?

**Comment by wouterj** [comment]
At least not in all cases, as I've tested RC1 on our apps (which also still use the old system).

Can you provide a minimal reproducer @andreybolonin ?

**Comment by yceruto** [comment]
I see on 5.4 still a reference to `security.authentication_manager`:
https://github.com/symfony/symfony/blob/a12336a7cd5df9c2723eee62073bb9dd795a14d1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L125
while the service id is `security.authentication.manager`:
https://github.com/symfony/symfony/blob/a12336a7cd5df9c2723eee62073bb9dd795a14d1/src/Symfony/Bundle/SecurityBundle/Resources/config/security_legacy.php#L31
and I don't see any alias.

**Comment by andreybolonin** [comment]
@stof yes, I using old auth system

I am only upgrade 4.4 version to 5.4 and run the app :)

**Comment by andreybolonin** [comment]
<img width="456" alt="Screenshot 2021-11-29 at 21 57 36" src="https://user-images.githubusercontent.com/2576509/143934174-9b4096b6-5005-425f-ac17-442bd66608d6.png">

I am comment this param and all is ok
