### ISSUE TITLE
Could we add an options to summarize deprecations in phpunit bridge?

### ISSUE THREAD

**Issue by garak** [symfony/symfony#44348]
### Description

Situation: I prefer to stay on LTS versions of Symfony, so today I tried to upgrade a couple of projects from 4.4 to 5.4
The upgrade worked, my tests are green, but now I'm getting 68 direct deprecation notices + 2324  indirect deprecation notices + 10178 other deprecation notices, for a total of (A LOT OF DEPRECATIONS THAT I CAN'T EVEN COUNT).

This is making really hard to look at the actual results of tests, since my terminal is literally flooded with super-detailed messages about deprecations. Such messages are, for sure, super useful when you need to work on removing deprecations themselves, but maybe a little too much when you start.
So, can we consider adding some options to control this verbosity?

**Comment by fancyweb** [comment]
Hello, you can disable the verbose output with the verbose option, please check https://symfony.com/doc/current/components/phpunit_bridge.html#disabling-the-verbose-output. You will still see the total deprecations count but not the messages. Please close the issue if it's what you requested, thanks.

**Comment by nicolas-grekas** [comment]
We could also limit the number of test cases displayed in the report. There is not point in listing them all, eg only the 10 most triggering ones could be displayed (per deprecation message, since I suppose the number of unique deprecation messages is quite low, isn't it @garak?)

**Comment by garak** [comment]
> I suppose the number of unique deprecation messages is quite low, isn't it @garak?)

You're right, a lot of them are repeated

**Comment by garak** [comment]
> Hello, you can disable the verbose output with the verbose option, please check https://symfony.com/doc/current/components/phpunit_bridge.html#disabling-the-verbose-output. You will still see the total deprecations count but not the messages. Please close the issue if it's what you requested, thanks.

Well, I tried to change my value in PHPUnit config from `<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0"/>` to `<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0&amp;verbose=0"/>`, it changed nothing

**Comment by fancyweb** [comment]
I tried the option this morning and it worked for me. Is it maybe overridden in `.env.test`?

**Comment by garak** [comment]
> I tried the option this morning and it worked for me. Is it maybe overridden in `.env.test`?

I don't use Dotenv component nor any .env file. I just put my variables in the environment.

**Comment by alexislefebvre** [comment]
> Well, I tried to change my value in PHPUnit config from `<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0"/>` to `<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0&amp;verbose=0"/>`, it changed nothing

Did the `&amp;` comes from a copy paste? The documentation shows usage with `&`, not `&amp;`: https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail

**Comment by nicolas-grekas** [comment]
See #45346
