### ISSUE TITLE
Upgrade to 5.4 failed:  Invalid service the class is not set.

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony#44342]
### Symfony version(s) affected

5.4.0

### Description

I've just tried updating from latest 5.3.11 to 5.4.0 and after the packages have been updated the container can not be built with complaints about my custom repositories not having a class set.

### How to reproduce

I've created a reproducer here: https://github.com/gjuric/symfony_5_4_bug/

The repositories are defined like this:

```xml
    <service id="Namespace\MyCustomDoctrineRepository">
        <factory service="doctrine.orm.default_entity_manager" method="getRepository"/>
        <argument>FQCN_of_my_entity</argument>
    </service>
```

I've tried adding the `class` attribute to the `<service>` tag but it doesn't help.

### Additional Context

When compiler is trying to build this server it sees it has a factory and tries to fetch the Class here: https://github.com/symfony/symfony/blob/a12336a7cd5df9c2723eee62073bb9dd795a14d1/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php#L132

`$this->container->findDefinition((string) $class)` returns and instance of `Symfony\Component\DependencyInjection\ChildDefinition` where `parent` is set to `doctrine.orm.entity_manager.abstract` and the `class` property is set to `null`. This null is then passed to `return $this->getReflectionMethod(new Definition($class), $method);` where it is of course not possible to build a definition since `$class` is `null`.

**Comment by wouterj** [comment]
Hi @gjuric!

Can you provide a [minimal reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) that shows this error? That'll help someone (or you 😉) to debug this error.

**Comment by gjuric** [comment]
Sure, I will take a look at it tomorrow, I've tried setting up the skeleton app from the linked documentation but it installs v6, after manually downgrading to 5.4 I wasn't able to install the maker bundle because of dependencies and downgrading to 5.3 to get the maker bundle broke the skeleton app because of a missing method in the MicroKernelTrait so I need to take care of that first :)

**Comment by signor-pedro** [comment]
Hi, at our company we're experiencing the same :) thanks @gjuric for the minimal reproducer :)

**Comment by gjuric** [comment]
I am having trouble generating a minimal reproducer since there using a factory to get the Entity Repository works :(

If I downgrade the `symfony/framework-bundle` package to v5.3.11 and leave all other packages upgraded everything works. The debug output when running `bin/console` is:

```In AbstractRecursivePass.php line 178:

  [Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Invalid service "Namespace\DoctrineOrmMyEntityRepository": the class is not set.


Exception trace:
  at vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:178
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->getReflectionMethod() at vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:143
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->getConstructor() at vendor/symfony/dependency-injection/Compiler/AttributeAutoconfigurationPass.php:102
 Symfony\Component\DependencyInjection\Compiler\AttributeAutoconfigurationPass->processValue() at vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at vendor/symfony/dependency-injection/Compiler/AttributeAutoconfigurationPass.php:88
 Symfony\Component\DependencyInjection\Compiler\AttributeAutoconfigurationPass->processValue() at vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at vendor/symfony/dependency-injection/Compiler/AttributeAutoconfigurationPass.php:77
 Symfony\Component\DependencyInjection\Compiler\AttributeAutoconfigurationPass->process() at vendor/symfony/dependency-injection/Compiler/Compiler.php:82
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at vendor/symfony/dependency-injection/ContainerBuilder.php:757
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at vendor/symfony/http-kernel/Kernel.php:548
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor/symfony/http-kernel/Kernel.php:789
 Symfony\Component\HttpKernel\Kernel->preBoot() at vendor/symfony/http-kernel/Kernel.php:128
 Symfony\Component\HttpKernel\Kernel->boot() at vendor/symfony/framework-bundle/Console/Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at vendor/autoload_runtime.php:35
 require_once() at bin/console:10
```


Couple of things to add:

* we are using multiple entity managers
* bundles that define these repositories add a DoctrineOrmMappingsPass::createXmlMappingDriver() compiler Pass to the container so entites from the bundle are registered with Doctrine

**Comment by gjuric** [comment]
I've managed to create a [reproducer](https://github.com/gjuric/symfony_5_4_bug/) and I've updated the issue with additional context.

**Comment by wouterj** [comment]
Thanks a lot @gjuric!

The lines you mention in the PR description haven't been changed for years. However, if I use Symfony 5.3 I get `$class = 'Doctrine\ORM\EntityManager';`, whereas it's `null` in Symfony 5.4.

Would be cool if someone can dig deeper into this :)

**Comment by fancyweb** [comment]
Looks like a bug on 4.4 here https://github.com/symfony/symfony/blob/382cde28c1206d357ef717ac4f254194aa0b6062/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php#L137. `$class` can be null, even with `$required = false`, `getConstructor()` ends up throwing.

`getConstructor()` is called here https://github.com/symfony/symfony/blob/a12336a7cd5df9c2723eee62073bb9dd795a14d1/src/Symfony/Component/DependencyInjection/Compiler/AttributeAutoconfigurationPass.php#L102.

I guess if there is no class in the definition with `$required = false`, `getConstructor()` should return null.

**Comment by fancyweb** [comment]
Actually, let's catch the exception, that's what we do everywhere else, I'll submit a patch.

**Comment by gjuric** [comment]
@nicolas-grekas @fancyweb any chance of 5.4.1 being released with this fix in it?

**Comment by xabbuh** [comment]
Patch releases are usually done regularly once a month.
