### ISSUE TITLE
5.4.0: `SessionListener::onKernelResponse` listener is registered twice in test env

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#44345]
### Symfony version(s) affected

5.4.0

### Description

`Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()` listener is registered twice in `test` environment.

Our tests for controllers where we set `NO_AUTO_CACHE_CONTROL_HEADER` flag started failing, because the flag is reset on the first call of `onKernelResponse` and the subsequent call overwrites the previously set headers.

### How to reproduce

It works fine on 5.3:

```bash
$ symfony new symfonysessionlistenertest53 --version="5.3.x@dev" --full
$ cd symfonysessionlistenertest53 
$ symfony console debug:event --env=test

"kernel.response" event
-----------------------
....
  #11     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
...
``` 

But is registered twice on 5.4:

```bash
$ symfony new symfonysessionlistenertest54 --version="5.4.x@dev" --full
$ cd symfonysessionlistenertest54 
$ symfony console debug:event --env=test

"kernel.response" event
-----------------------
...
  #10     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
  #11     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
...
```

### Additional Context

Note: The listener is set only once in `dev` and `prod` envs.

I guess that the issue may be related to #41390.

**Comment by OskarStark** [comment]
Friendly ping @alexander-schranz

**Comment by alexander-schranz** [comment]
We did replace the `TestSessionListener` with the new `SessionListener` this actually causing now that the event seems to be registered multiple times.

https://github.com/symfony/symfony/pull/41390/files#diff-2b07ed6c629fe7c7a6ed6a82c36f039b0af6ad1be83d5656787082dd281e6e48R38

A workaround maybe would here that we replace the `SessionListener` with the `TestSessionListener` instead adding a new service, but would be interested if all works correctly in your case if there is only 1 SessionListener. Or just alias the session listener service.

@mhujer can you check if you comment the following lines out and so avoid the additional SessionListener. If then work all correctly?: https://github.com/alexander-schranz/symfony/blob/b3e4f6657c0c47e1b5ba85e4554a3c273ee61066/src/Symfony/Bundle/FrameworkBundle/Resources/config/test.php#L38-L46

**Comment by mhujer** [comment]
@alexander-schranz yes, commenting out the suggested lines fixes the issue (the listener is registered only once).

If anyone else is facing the similar issue, I added this as a workaround to my Kernel class and the tests are now passing:

```php

...
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
...

class Kernel extends BaseKernel implements CompilerPassInterface
{
    ...

    public function process(ContainerBuilder $container): void
    {
        if ($this->environment !== 'test') {
            return;
        }

        // fix https://github.com/symfony/symfony/issues/44345
        $container->removeDefinition('test.session.listener');
    }
```

**Comment by alexander-schranz** [comment]
@mhujer Thank you for testing this out. So we should make sure that only one session listener is registered.

@jderusse What do you think that we alias `session_listener` to `test.session.listener` then there should only be one listener? Maybe doing it after here: https://github.com/symfony/symfony/blob/60ce5a3dfbd90fad60cd39fcb3d7bf7888a48659/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L341

```php
            if (!empty($config['test'])) {
                // test listener will replace the exist session listener
                // we are aliasing to avoid duplicated registered events
                $container->setAlias('session_listener', 'test.session.listener');
            }
```

**Comment by alexander-schranz** [comment]
@mhujer Can you give https://github.com/symfony/symfony/pull/44359 a try?
