### ISSUE TITLE
[EventDispatcher] add and dispatch built-in event_dispatcher.pre_dispatch event

### ISSUE THREAD

**Issue by dimiceli** [symfony/symfony#44357]
### Description

Hello,

I think it would be useful if the EventDispatcher itself dispatch an event of type event_disaptcher.pre_dispatch so that services can have the possibility to add or remove listeners from the list depending on the context.

For example I would like to restrict listeners to certain routes in an application. For that it would be useful to listen to an event_disaptcher.pre_dispatch event and to remove the listener from the list if we are not on a suitable route.

I would like to hear your opinion on this and work on a pull request if the idea sounds good to you.

Regards

**Comment by ro0NL** [comment]
Checking the route from a listener directly sounds more intuitive to me.

**Comment by stof** [comment]
And this is probably better for performance, as it allows to keep the pre-sorted list of listeners (sorted at build time) instead of having to sort the list again when dispatching the event due to mutating the list.
Also, dispatching another event before each event might also have a performance impact due to doing more work.

**Comment by dimiceli** [comment]
Ok @ro0NL @stof , you've convinced me that's a bad idea. Mainly for performance reasons.  

I think the event dispatcher is very powerful to separate responsibilities but sometimes can be a bit dangerous. Because when we add a route there can be a lot of things done by a listener without the developer being aware of it. 
I had this experience professionally.

**Comment by ro0NL** [comment]
> a lot of things done by a listener without the developer being aware of it

it's the cost of event-driven development. I dont think `event_disaptcher.pre_dispatch` improves that in any way.

**Comment by stof** [comment]
to me, it even makes this worse, as it makes it harder to find listeners registered for an event (as that list would be dynamic)

**Comment by dimiceli** [comment]
@ro0NL @stof  good arguments, i closed the ticket without regreats, thanks for your time.
