### ISSUE TITLE
Split KernelInterface of HttpKernel

### ISSUE THREAD

**Issue by yann-eugone** [symfony/symfony#44352]
### Description

We recently had a debate on whether injecting the kernel into a service to access some information it carries is a good idea or not.
I totally agree that a service should rely on the minimum information it requires, and thus not depending on something like a container to extract service, or kernel to access environment.

When we were required to inject all arguments manually, this was not a problem.
We were doing it naturally, because we had to provide a value for each arg.

Now, Symfony supports autowiring, and we tend to have all parameters this way.

Of course, there is still the possibility to specify an argument of a service individually

```yaml
services:
  App\FooService:
    arguments:
      $env: '%kernel.environment%'
```

Or globally

```yaml
services:
  _bind:
    string $env: '%kernel.environment%'
```

I'm fine with the first option, but it is efficient for parameter injected once in app.
I'm not fine with the second one, because I dislike relying on a name for injecting the proper value.

This is why I rather prefer injecting a service containing these parameters instead.

But `KernelInterface` gives access to way more than environment : `Kernel::boot`, `Kernel::shutdown`...
Following SOLID principle, this interface could be split in (at least) 2 others.

### Example

```diff
-interface KernelInterface extends HttpKernelInterface
+interface KernelInterface extends HttpKernelInterface, KernelEnvironmentInterface, KernelDirectoriesInterface
{
-    public function getEnvironment(): string;
-    public function isDebug(): bool;
-    public function getProjectDir(): string;
-    public function getCacheDir(): string;
-    public function getBuildDir(): string;
-    public function getLogDir(): string;
}

+interface KernelEnvironmentInterface
+{
+    public function getEnvironment(): string;
+    public function isDebug(): bool;
+}

+interface KernelDirectoriesInterface
+{
+    public function getProjectDir(): string;
+    public function getCacheDir(): string;
+    public function getBuildDir(): string;
+    public function getLogDir(): string;
+}
```

**Comment by derrabus** [comment]
Injecting the environment as a string is the way to go here. I'm not convinced that we should provide a second solution to achieve the same thing. Neither do I want to encourage anyone to inject the kernel just to extract the environment, no matter how fine-grained we cut the interfaces.

A clear 👎🏻 from my side, sorry.

**Comment by nicolas-grekas** [comment]
You can already inject `ParameterBagInterface`, which achieves most of what you describe.
But injecting only the very info that you need as a scalar looks way better from a design pov imho.

**Comment by yann-eugone** [comment]
So you both recommand usage of named bindings for these needs ?

**Comment by nicolas-grekas** [comment]
Absolutely :)

**Comment by yann-eugone** [comment]
Fine, will find another way to achieve this on my own.

Thank you anyway for your recommandations.

**Comment by derrabus** [comment]
Building a service in userland that fulfills your `KernelEnvironmentInterface` should be trivial, if this is really the way you want to go. But I doubt that you gain anything from that.

**Comment by yann-eugone** [comment]
I have no issue with the implementation (it's already done).

I understand that you see no benefit on this feature.
This is why I closed the issue.
Again, I don't like named bindings, this is the only benefit for me, but this is enough IMO.
