### ISSUE TITLE
Symfony config load PHP config

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#44374]
### Symfony version(s) affected

5.*

### Description

I move my configuration to PHP format instead of YAML.

for now all the routes with php ext working fine.

but when I create for examples:

config/packages/webpack_encore.php:

with the content:

```
<?php

use Symfony\Config\WebpackEncoreConfig;

return static function (WebpackEncoreConfig $webpack): void {
    $webpack
        ->outputPath('%kernel.project_dir%/public/build')
        ->scriptAttributes('defer', true)
        ->crossorigin(false)
        ->preload(false)
        ->strictMode(true)
        ->cache(false);
};

```
I'm getting error:

`The child config "output_path" under "webpack_encore" must be configured: The path where Encore is building the assets - i.e. Encore.setOutputPath()`

### How to reproduce

Try to load PHP config file.

### Possible Solution

As I see here:

https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/src/Kernel.php#L14

and examples of config according to docs.

https://symfony.com/doc/current/reference/configuration/framework.html#ide

it's the same format.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ben29** [comment]
it will take time...
you can just create php config file with some config and see it's not loading the file.

**Comment by tacman** [comment]
I think this might be relevant:

>> By default Symfony only loads the configuration files defined in YAML format. If you define configuration in XML and/or PHP formats, update the src/Kernel.php file to add support for the .xml and .php file extensions.

From https://symfony.com/doc/current/configuration.html

I changed src/Kernel.php to

```php
        $container->import('../config/{packages}/*.yaml');
        $container->import('../config/{packages}/*.php');
        $container->import('../config/{packages}/'.$this->environment.'/*.yaml');
        $container->import('../config/{packages}/'.$this->environment.'/*.php');
```

and it is now working for me.

**Comment by ben29** [comment]
@tacman yes this why I do to make it work.
but it should be loaded. without override the fie

**Comment by xabbuh** [comment]
closing here as that's the expected behaviour as explained in https://github.com/symfony/symfony/issues/44374#issuecomment-983674652
