### ISSUE TITLE
Routes configured with native PHP attributes do not work without the doctrine/annotations bundle.

### ISSUE THREAD

**Issue by victortodoran** [symfony/symfony#44373]
### Symfony version(s) affected

5.4.0

### Description

Routes configured with native PHP attributes do not work without the doctrine/annotations bundle.

By looking at the docs I would expect routes configured using PHP attributes to work without the need to install the doctrine annotations bundle.
> On PHP 8, you can use native attributes to configure routes right away.

### How to reproduce

Machine details:
-
- Ubuntu 20.04
- PHP cli 8.0.13
- Symfony 5.4.0 (skeleton)
- Local server using Symfony CLI

Steps to reproduce
-
1. Clean Symfony skeleton install
2. Add a new TestController
```
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    #[Route('/', name: 'some_name')]
    public function test(): Response
    {
        return new Response("<h1>It works!</h1>");
    }
}
```
3. Access localhost:8000

Expected Result:
-
See the It works heading.

Actual Result:
-
The Symfony default page is displayed.

### Additional Context

- Configuring a different (than root) path, e.g. /somepath has the same result.

- After installing the doctrine/annotations bundle everything works as expected.

![image](https://user-images.githubusercontent.com/25669334/144102589-0e24ef5d-af41-4c5f-8a7c-778ea26301f4.png)

![image](https://user-images.githubusercontent.com/25669334/144102673-c8f40b42-f7c2-4b5d-9a7a-935c2dd6a7ad.png)

**Comment by mbabker** [comment]
What's your routing configuration look like?  I know there are some changes in the Flex recipe for 6.0 to make this work, but I think the 5.x recipe might still be based on the annotations package (since 5.x supports PHP 7).

**Comment by derrabus** [comment]
Correct, you have to enable attribute-based routing yourself on 5.4.

**Comment by 0505andres** [comment]
I was have the same proble but not its a bug, we just need install the apache pack in this link can find the information 
https://symfony.com/doc/5.4/setup/web_server_configuration.html
