### ISSUE TITLE
Session config with redis url broken after update to 5.4.0

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#44372]
### Symfony version(s) affected

5.4

### Description

Configured session handler_id as `handler_id: 'redis://localhost/2'`. This worked for me until i updated to 5.4.0. Now i get this error:
```
parse_url(): Argument #1 ($url) must be of type string, Symfony\Component\Cache\Traits\RedisProxy given
```

### How to reproduce

Use this config in framework.yaml with symfony 5.4.0
```
framework:
    session:
        handler_id: 'redis://localhost/2'
```

**Comment by nicolas-grekas** [comment]
On which file+line is this error triggered?

**Comment by ThomasTr** [comment]
Triggered here:

symfony/http-foundation/Session/Storage/Handler/SessionHandlerFactory.php (line 33)

**Comment by dmaicher** [comment]
Seems this is caused by https://github.com/symfony/symfony/pull/41268/files#diff-8d7580406c9830c020792bbbb6841e34724efbc106a13ac1bf85cec39d9c75eeR33

`$connection` might be an object there as the phpdoc suggests

**Comment by gnito-org** [comment]
Shouldn't it be configured as follows?

```
framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
```

**Comment by chalasr** [comment]
See #44739

**Comment by ThomasTr** [comment]
@gnito-org this is one way. The other way via url is not very well documented as i see. Fabien is doing it in his book: https://symfony.com/doc/current/the-fast-track/de/31-redis.html

I think we should include this possibility in the documentation? If ok i will open issue in doc.
