### ISSUE TITLE
Undefined constant AccessDecisionManager::STRATEGY_UNANIMOUS

### ISSUE THREAD

**Issue by davidblack007** [symfony/symfony#44384]
### Symfony version(s) affected
6.0

### Description
`Undefined constant Symfony\Component\Security\Core\Authorization\AccessDecisionManager::STRATEGY_UNANIMOUS`
When i logged in, i clicked to profiler security tab and it crashed.

security-bundle/Resources/views/Collector/security.html.twig:line 395

![s1](https://user-images.githubusercontent.com/8114447/144198262-423a12c4-c778-4574-ae52-c01e17210a9e.png)

![s2](https://user-images.githubusercontent.com/8114447/144198571-82703cb1-7081-41f3-ac7a-c682a37166d9.png)

**Comment by dvdknaap** [comment]
I got the same issue in 6.0

on vendor/symfony/security-bundle/Resources/views/Collector/security.html.twig:395 
```twig
{% if collector.voterStrategy == constant('Symfony\\Component\\Security\\Core\\Authorization\\AccessDecisionManager::STRATEGY_UNANIMOUS') %}
```

it's checking for a constant which doesn't exist anymore and php is throwing the exception

The twig constant function is using twig_constant in 
vendor/twig/twig/src/Extension/CoreExtension.php:1304
```php
function twig_constant($constant, $object = null)
{
    if (null !== $object) {
        $constant = \get_class($object).'::'.$constant;
    }

    return \constant($constant);
}
```
Below this twig functing (which is not in the documentation) to check if a constant is defined.
would be a good idea to use this functiong first before using the twig constant function ?

vendor/twig/twig/src/Extension/CoreExtension.php:1321
```php

/**
 * Checks if a constant exists.
 *
 * @param string      $constant The name of the constant
 * @param object|null $object   The object to get the constant from
 *
 * @return bool
 */
function twig_constant_is_defined($constant, $object = null)
{
    if (null !== $object) {
        $constant = \get_class($object).'::'.$constant;
    }

    return \defined($constant);
}
```

**Comment by derrabus** [comment]
see #44424
