### ISSUE TITLE
Http Client unable to connect from docker container to another container 

### ISSUE THREAD

**Issue by AndrewStarkov** [symfony/symfony#44387]
### Symfony version(s) affected

5.3

### Description

Hello, maybe curl set up in client has something broken. Or requires specific configuration for docker containers.
This bug occured after updating old code from native curl to symfony http client.

Executing curl from terminal or browser results in response 200.

```
curl http://127.0.0.1:8983/solr/index_name/select
<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">1</int><lst name="params"/></lst><result name="response" numFound="0" start="0"/>
</response>
```

executing with symfony http client return  error
```
$chunk = {Symfony\Component\HttpClient\Chunk\ErrorChunk} [4]
 didThrow = true
 offset = {int} 0
 errorMessage = "Couldn't connect to server for "http://127.0.0.1:8983/solr/index_name/select"."
 error = {Symfony\Component\HttpClient\Exception\TransportException} [7]
  message = "Couldn't connect to server for "http://127.0.0.1:8983/solr/index_name/select"."
  *Exception*string = ""
  code = {int} 0
  file = "/var/www/html/vendor/symfony/http-client/Response/CurlResponse.php"
  line = {int} 317
  *Exception*trace = {array} [44]
   0 = {array} [6]
    file = "/var/www/html/vendor/symfony/http-client/Response/TransportResponseTrait.php"
    line = {int} 170
    function = "perform"
    class = "Symfony\Component\HttpClient\Response\CurlResponse"
    type = "::"
    args = {array} [2]
   1 = {array} [6]
    file = "/var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php"
    line = {int} 156
    function = "stream"
    class = "Symfony\Component\HttpClient\Response\CurlResponse"
    type = "::"
    args = {array} [1]
   2 = {array} [6]
    file = "/var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php"
    line = {int} 44
    function = "initialize"
    class = "Symfony\Component\HttpClient\Response\CurlResponse"
    type = "::"
    args = {array} [1]
   3 = {array} [6]
    file = "/var/www/html/vendor/symfony/http-client/Response/CurlResponse.php"
```
solr is in docker container

$response->getInfo('debug')
```
*   Trying 127.0.0.1:8983...
* connect to 127.0.0.1 port 8983 failed: Connection refused
* Failed to connect to 127.0.0.1 port 8983: Connection refused
* Closing connection 0
```
solr has no authentication.
Http client with app placed in one container and tries to connect to solr which is in tomcat
```
TOMCAT_SERVER_PORT=8983
...
  tomcat:
    build: images/tomcat
    volumes:
       - ./data/solr:/opt/solr/cores:delegated
       - ./data/solr_bridge:/opt/solr_bridge/cores:delegated
    ports:
      - "${TOMCAT_SERVER_PORT}:8080"
    depends_on:
      - mysql
      - mongo
```
Solr accessible on localhost:8983/solr + 127.0.0.1:8983/solr + 0.0.0.0:8983/solr
But not on https://tomcat:8983/solr

Excepted result: http client should return xml response.

### How to reproduce

Still figuring out the cause. But maybe easier will be just revert updates with migration to symfony http client. 

### Possible Solution

Still do not know.

**Comment by stof** [comment]
When you say that executing the request with curl or the browser works, are you talking about doing that inside your container or on the host ?
Exposing a container port to the host does not automatically expose it to other containers. Trying to reach `127.0.0.1:8983` inside your container tries to use the port 8983 of that container, not of the host.

**Comment by AndrewStarkov** [comment]
@stof  outside / inside app container

```
andrew-starkov@pf1emg93 app-docker % curl http://127.0.0.1:8983/solr/index/select
<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">1</int><lst name="params"/></lst><result name="response" numFound="0" start="0"/>
</response>

andrew-starkov@pf1emg93 app-docker % docker compose exec app bash
root@f5596ae6aa12:/var/www/html# curl http://127.0.0.1:8983/solr/index/select
curl: (7) Failed to connect to 127.0.0.1 port 8983: Connection refused
```
browser I mean the google chrome, webkit, which we use to open websites :)

question now, why native curl was working executing localhost solr, but http client  vendor/symfony/http-client/CurlHttpClient.php line 110  
refused to connect. 
What the cause of it? Could it be related how curl http client executes in async curl_multi_setopt / curl_multi_exec / curl_multi_info_read?

**Comment by AndrewStarkov** [comment]
@stof  yup, this issue occurs only in http client, here is working code executed inside docker "app" container

   ```
     $sh = curl_init($url);
        curl_setopt($sh, CURLOPT_HEADER, 0);
        curl_setopt($sh, CURLOPT_POST, true);
        curl_setopt($sh, CURLOPT_POSTFIELDS, $postFields);
        curl_setopt($sh, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt( $sh, CURLOPT_FOLLOWLOCATION, true );
        $output = curl_exec($sh);
        $output = json_decode($output,true);
```

**Comment by AndrewStarkov** [comment]
So its definetely related to how http client handles multi connection to host or smth. 
```
    http_client:
        default_options:
            max_duration: 600
            timeout: 300
            http_version: '2.0'
        scoped_clients:
            solr.client:
                scope: '%app.solr_base_url%'
```
and composer.json of used http client package
```
{
    "name": "symfony/http-client",
    "type": "library",
    "description": "Provides powerful methods to fetch HTTP resources synchronously or asynchronously",
    "homepage": "https://symfony.com",
    "license": "MIT",
    "authors": [
        {
            "name": "Nicolas Grekas",
            "email": "p@tchwork.com"
        },
        {
            "name": "Symfony Community",
            "homepage": "https://symfony.com/contributors"
        }
    ],
    "provide": {
        "php-http/async-client-implementation": "*",
        "php-http/client-implementation": "*",
        "psr/http-client-implementation": "1.0",
        "symfony/http-client-implementation": "2.4"
    },
    "require": {
        "php": ">=7.2.5",
        "psr/log": "^1|^2|^3",
        "symfony/deprecation-contracts": "^2.1",
        "symfony/http-client-contracts": "^2.4",
        "symfony/polyfill-php73": "^1.11",
        "symfony/polyfill-php80": "^1.16",
        "symfony/service-contracts": "^1.0|^2"
    },
    "require-dev": {
        "amphp/amp": "^2.5",
        "amphp/http-client": "^4.2.1",
        "amphp/http-tunnel": "^1.0",
        "amphp/socket": "^1.1",
        "guzzlehttp/promises": "^1.4",
        "nyholm/psr7": "^1.0",
        "php-http/httplug": "^1.0|^2.0",
        "psr/http-client": "^1.0",
        "symfony/dependency-injection": "^4.4|^5.0",
        "symfony/http-kernel": "^4.4.13|^5.1.5",
        "symfony/process": "^4.4|^5.0",
        "symfony/stopwatch": "^4.4|^5.0"
    },
    "autoload": {
        "psr-4": { "Symfony\\Component\\HttpClient\\": "" },
        "exclude-from-classmap": [
            "/Tests/"
        ]
    },
    "minimum-stability": "dev"
}
``` 
we use:
- PHP 7.4 
- http2
- cURL
```
 curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

```
I recall there were some issues in some tickets related to http version 2 and curl version. 

Note: all outer requests from the container with HTTP client seem to work properly. Eg calling dev/prod solr instance works fine. So I will temporarily connect to remote solr to fix the search issue. 
For localhost container, maybe need to configure proxy or smth in docker https://docs.docker.com/compose/networking/ to make http client working. 
Also, that would be nice to mention such case in docs, eg "VM (Docker) set up / configuration" and explain what should be done to handle such case. Because as I see call to remote with package and native curl work fine.

**Comment by ghost** [comment]
Please limit the chaos in your comments. It's hard to understand where you are in your talk.

As stof mentioned, when you are inside a container then 127.0.0.1 is the container's scope, not your host (your computer).
Tomcat exposes port 8983 to your host, not to "everyone" outside tomcat's container.

I recommend putting containers that talk one to another in the same docker network. Then instead of 127.0.0.1 one can use a container alias inside network. If you use docker-compose then a created container gets an alias that is equal to the service name in compose file. Then the base url to this container is `http://<alias_here>`. You can see what aliases the container has with `docker inspect <container_name>`.

**Comment by stof** [comment]
Your comment https://github.com/symfony/symfony/issues/44387#issuecomment-983579842 proves that this is not an issue with the Symfony HttpClient. Using curl inside your container also fails to access your solr. This is an issue in your understanding of how docker networking works, and @javaDeveloperKid and I already explained it in comments.

I'm closing this issue as there is no issue to be solved in Symfony.

**Comment by AndrewStarkov** [comment]
@javaDeveloperKid can you please add a configuration refference? Calling tomcat:8983/sorl fails even though its configured as you mentioned
 ```
 tomcat:
    build: images/tomcat
    container_name: tomcat
    volumes:
       - ./data/solr:/opt/solr/cores:delegated
       - ./data/solr_bridge:/opt/solr_bridge/cores:delegated
    ports:
      - "8983:8080"
    depends_on:
      - mysql
      - mongo
```


@stof but this code **works** fine from the same app, just replaced client code lines with curl 
```
  $sh = curl_init($url);
     curl_setopt($sh, CURLOPT_HEADER, 0);
     curl_setopt($sh, CURLOPT_POST, true);
     curl_setopt($sh, CURLOPT_POSTFIELDS, $postFields);
     curl_setopt($sh, CURLOPT_RETURNTRANSFER, 1);
     curl_setopt( $sh, CURLOPT_FOLLOWLOCATION, true );
     $output = curl_exec($sh);
     $output = json_decode($output,true);
```
     
that one is broken. 
This issue occured after replacing old code(curl) with symfony http client. Reverting changes to curl() solves "connection refused' issue to Solr calls. 
     
```$symfonyCurlHttpCient->request('GET', $url)```
  not sure why simple  $sh = curl_init($url); works but http client fails.  There is some key difference which is missed.

**Comment by AndrewStarkov** [comment]
Anyway, anyone who still struggles with issue of containers availablity from another container try links:
https://docs.docker.com/compose/networking/#links
 ```
 version: '3.7'

services:

  app:
    build: images/application
    init: true
    container_name: app
    ...
 solr:
    container_name: solr
    build: images/solr
    links:
        - 'app'
  ...
```
even though 
`by default, any service can reach any other service at that service’s name. `
