### ISSUE TITLE
[FrameworkBundle / SecurityBundle] Symfony 6.0: `isGranted` unable to access `security.authorization_checker` service

### ISSUE THREAD

**Issue by ljack-adista** [symfony/symfony#44391]
### Symfony version(s) affected

6.0+

### Description

The `Symfony\Bundle\FrameworkBundle\Controller\AbstractController::isGranted` method checks if the container has the `security.authorization_checker` service before using it (https://github.com/symfony/framework-bundle/blob/6.0/Controller/AbstractController.php#L189)

The problem is that this service has been made private in Symfony 6.0: https://github.com/symfony/symfony/blob/6.1/UPGRADE-6.0.md#securitybundle

> The `security.authorization_checker` and `security.token_storage` services are now private

So, any controllers attempting to call `isGranted` throw the following LogicException: 

> The SecurityBundle is not registered in your application. Try running "composer require symfony/security-bundle".

### How to reproduce

Call the `isGranted` method from any controller in a Symfony 6.0+ project

### Possible solution

Make the `security.authorization_checker` service public again ?

### Additional context

None

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ljack-adista** [comment]
Unable to reproduce on a new Symfony 6 project, must be something I missed in the upgrade process...

**Comment by xabbuh** [comment]
Thank you for the feedback. Let's close here for now then.

**Comment by gmateevsgalinski** [comment]
@ljack-adista did you manage to solve it? I ran into the same issue

**Comment by gmateevsgalinski** [comment]
Ok I have found the issue and sovled it. In 5.4 we had ran into this issue https://github.com/symfony/symfony/issues/23200 and had set the service container into the controller. That container didn't have this service. It was a different service across the different controllers.

So whoever runs into this issue - check your services.yaml for manual injecting of the service container into the controllers

**Comment by herman-aka-wouter** [comment]
here the same random error. all controllers are working, except 1 api controller

**Comment by emodric** [comment]
Hi @xabbuh,

I have the same issue and it happens when manually defining a controller as a service, without using autowiring and autoconfiguration, something like this:

```
    App\Controller\Hello:
        calls:
            - [setContainer, ["@service_container"]]
```

Here's the reproducer app: https://github.com/emodric/symfony-issue-44391

Install it and visit `/hello` to get the exception. This worked fine in Symfony 5.4

**Comment by xabbuh** [comment]
@emodric This looks expected to me. Since Symfony 4 services are private by default. So you can no longer retrieve them from the global service container.

**Comment by emodric** [comment]
So how do I access the services defined in `AbstractController::getSubscribedServices` if I don't use autowiring and autoconfiguration?

**Comment by stof** [comment]
When you manually configure a service being a service subscribe, the `setContainer` call must inject the `Psr\Container\ContainerInterface` service (that will be properly bound by the compiler pass resolving the `container.service_subscriber` tag), not the `service_container` id (which is the main container)

**Comment by emodric** [comment]
@stof Alright, thanks for that!

**Comment by Phocacius** [comment]
For anyone who just wants to copy a working solution: Here's what @stof s answer means in code:

XML Config:
```xml
<service id="..." name="...">
    <tag name="container.service_subscriber" />
    <call method="setContainer">
        <argument type="service" id="Psr\Container\ContainerInterface" />
    </call>
</service>
```

YAML config:
```yaml
Bundle\Controller\YourController:
    class: ...
    tags: ['container.service_subscriber'] 
    calls:
        - ['setContainer', ['@Psr\Container\ContainerInterface']]
```
