### ISSUE TITLE
Document changes to PreAuthenticatedToken in 5.4

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony#44396]
### Description

`Symfony\Component\Security\Core\Authentication\Token\PreAuthenticatedToken` changed it's signature from [v5.3](https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Security/Core/Authentication/Token/PreAuthenticatedToken.php#L31)

```php
    public function __construct($user, $credentials, string $firewallName, array $roles = [])
```

to this in [v5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Core/Authentication/Token/PreAuthenticatedToken.php#L31)

```php
    public function __construct($user, /*string*/ $firewallName, /*array*/ $roles = [])
```

I believe this should be mentioned in UPGRADE-5.4.md. I am opening this here instead of the documentation repository since this repository is where the upgrade document is located.

**Comment by derrabus** [comment]
PR welcome.
