### ISSUE TITLE
Upgrade to Symfony 5.4 - the web profiler does not work

### ISSUE THREAD

**Issue by lgeorgiev** [symfony/symfony#44397]
### Symfony version(s) affected

5.4.0

### Description

Return value of Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector::getMemoryLimit() must be of the type int, float returned
  
php.ini - memory_limit = 2G
OS: Windows
PHP: 7.4.16

### How to reproduce

```
public function getMemoryLimit(): int 
{
    dd(convertToBytes$this->data['memory_limit']);
    return $this->data['memory_limit'];
}
```

2147483648.0

**Comment by derrabus** [comment]
Are you using a 32bit PHP binary?

**Comment by lgeorgiev** [comment]
32bit - PHP_INT_SIZE = 4

**Comment by derrabus** [comment]
That explains it. We can certainly remove the return type here, but then again, you cannot actually allocate 2 GiB of memory on a 32bit system, can you?

**Comment by lgeorgiev** [comment]
I'm not sure if I can. 

Thanks for the reply!

**Comment by ad3n** [comment]
https://github.com/php-runtime/runtime/issues/106

We use Macbook Pro and also get error for profiler, i use swoole runtime

**Comment by nicolas-grekas** [comment]
I think we need to fix the return type, it should be `int|float`.
Can you please submit a PR?
