### ISSUE TITLE
[symfony/dependency-injection] It only supports psr/container:^2

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#44392]
### Symfony version(s) affected

6.0.0

### Description

> PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ContainerInterface::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /home/runner/work/bundle-features/bundle-features/vendor/symfony/dependency-injection/ContainerInterface.php on line 63
Fatal error: Declaration of Symfony\Component\DependencyInjection\ContainerInterface::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /home/runner/work/bundle-features/bundle-features/vendor/symfony/dependency-injection/ContainerInterface.php on line 63

This error seems to happen due to a different signature of the method.

As [pointed out](https://github.com/laminas/laminas-validator/issues/70#issuecomment-983574485) by @Ocramius , I'm opening this issue.

### How to reproduce

See https://github.com/Aerendir/bundle-features/runs/4362660359?check_suite_focus=true

### Possible Solution

Declare `symfony/dependency-injection` only supports `psr/container:^2`.

https://github.com/symfony/dependency-injection/blob/4dae086ee9bda1e2d0fdbc19a4a30ea49b0e3c7c/composer.json#L20

### Additional Context

This issue is linked to this one: https://github.com/laminas/laminas-validator/issues/70

**Comment by xabbuh** [comment]
According to https://github.com/Aerendir/bundle-features/runs/4362660359?check_suite_focus=true#step:8:57 the error happens on version 4.4.9 but not 6.0.

**Comment by xabbuh** [comment]
But I fail to see why you get `psr/container` in version 2 installed. The DI component was only compatible with 1.x: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/composer.json#L20

**Comment by stof** [comment]
The GitHub Actions output linked above seems to run 2 composer updates one after the other (the second one probably triggered by a plugin or a script AFAICT).
The first one properly installs `psr/container` 1.0. The second one installs `psr/container` 2.0.2, probably in a different vendor folder and it looks like those versions get loaded instead of the one from the project.

**Comment by nicolas-grekas** [comment]
The first one installs symfony/dependency-injection with psr/container v1
The second one installs phpunit with psr/container v2
Then, loading autoload.php of both runs won't work.
Closing as there is no issue in our deps.

**Comment by Aerendir** [comment]
Thank you: I will investigate it further...
