### ISSUE TITLE
The relative file path is generated incorrectly

### ISSUE THREAD

**Issue by laraveladmin-cn** [symfony/symfony#44406]
### Symfony version(s) affected

5.4

### Description

[2021-12-02 13:18:15] local.ERROR: symlink(): No such file or directory {"exception":"[object] (ErrorException(code: 0): symlink(): No such file or directory at /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:315)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'symlink(): No s...', '/var/www/larave...', 315, Array)
#1 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(315): symlink('../../../node_m...', '/var/www/larave...')
#2 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(340): Illuminate\\Filesystem\\Filesystem->link('../../../node_m...', '/var/www/larave...')
#3 /var/www/laravel/laraveladmin/app/Console/Commands/LinksInit.php(57): Illuminate\\Filesystem\\Filesystem->relativeLink('/var/www/larave...', '/var/www/larave...')
#4 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): App\\Console\\Commands\\LinksInit->App\\Console\\Commands\\{closure}('/var/www/larave...', '/var/www/larave...')
#5 /var/www/laravel/laraveladmin/app/Console/Commands/LinksInit.php(74): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\LinksInit->handle()
#7 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#9 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#12 /var/www/laravel/laraveladmin/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/laravel/laraveladmin/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/laravel/laraveladmin/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\LinksInit), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/laravel/laraveladmin/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/laravel/laraveladmin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/laravel/laraveladmin/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 

### How to reproduce

vendor/symfony/filesystem/Filesystem.php
line:511   $relativePath = $traverser.('' !== $endPathRemainder ? (is_dir($endPath)?$endPathRemainder.'/':$endPathRemainder) : '');
![image](https://user-images.githubusercontent.com/76767270/144362565-48778052-39b9-42ad-8d38-ee1c4399c906.png)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
