### ISSUE TITLE
Where are the default error page templates?

### ISSUE THREAD

**Issue by chen-gloria** [symfony/symfony#44407]
In this documentation: https://symfony.com/doc/current/controller/error_pages.html I was looking for the templates of the default error page. I installed the TwigBundle `composer require symfony/twig-pack`, but I couldn't find the `error.html.twig` or any other exception/error twigs according to this documentation.

I tried to create `templates/bundles/TwigBundle/Exception/` directory to overwrite the `error.html.twig` or `error404.html.twig` or `exception.html.twig`. None of them work.

Is there an issue with the documentation or should I look for some other directories?

**Comment by noniagriconomie** [comment]
the default source files are here https://github.com/symfony/error-handler/tree/5.4/Resources/views
it should work with twig override, `None of them work.` can you be more precise?
