### ISSUE TITLE
composer bug with symfony

### ISSUE THREAD

**Issue by grosfaignan** [symfony/symfony#44408]
### Symfony version(s) affected

4.25.5

### Description

when using composer command like `composer -v` : 

```
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in C:\xampp\htdocs\symfony\ImmoTuto\maSuperAgence\vendor\symfony\flex\src\Command\DumpEnvCommand.php on line 82       

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in C:\xampp\htdocs\symfony\ImmoTuto\maSuperAgence\vendor\symfony\flex\src\Command\DumpEnvCommand.php on line 82

```
### How to reproduce

don't know how to reproduce it but i have this config : 
-php 7.0.0 ts
-xdebug php_xdebug-2.7.0beta1-7.0-vc14-x86_64 (for php 7 ts)
-Composer version 2.1.12
-mysql 8

it seems to don't have this issues with php 8

### Possible Solution
remove `?` before `string ` in concerned file doesn't matter 
(other bug comes after)
like :

```
Parse error: syntax error, unexpected 'Lock' (T_STRING), expecting variable (T_VARIABLE) in C:\xampp\htdocs\symfony\ImmoTuto\maSuperAgence\vendor\symfony\flex\src\Command\RecipesCommand.php on line 
33
```

**Comment by nicolas-grekas** [comment]
Flex requires PHP 7.1 minimum, you cannot use it on PHP 7.0

**Comment by grosfaignan** [comment]
ok thanks :)

**Comment by derrabus** [comment]
Please use GitHub discussions for support questions. Thanks.

**Comment by grosfaignan** [comment]
ok
