### ISSUE TITLE
EventDispatcher addListener union type inconsistency

### ISSUE THREAD

**Issue by StuTheBearded** [symfony/symfony#44403]
### Symfony version(s) affected

6.0.0

### Description

I've noticed in the latest version of EventDispatcher that the addListener method has picked up a union type for the $listener parameter. This causes me a bit of an issue with my reflection based dependency injection container as ReflectionUnionType doesn't have a getName() method which it needs to determine type, now I realise this that bit is my problem, however I did notice the following that the Interface only expects callable.

EventDispatcherInterface defines the method thus:
public function addListener(string $eventName, callable $listener, int $priority = 0)

EventDispatcher defines it as:
public function addListener(string $eventName, callable|array $listener, int $priority = 0)

Considering how PHP will treat an array with [$obj, 'someMethod'] as a callable I can't help but think the addition of the array type to this parameter doesn't add anything useful.

### How to reproduce

n/a

### Possible Solution

My proposed changed is simply remove the array type from $listener parameter as callable covers that anyway and then its inconsistent with the interface definition. It also means I don't have to write a decorator to work around this.

**Comment by nicolas-grekas** [comment]
It's by design:
`array` is required because the `EventDispatcher` implementation
is able to deal with lazy callables that look like: `[Closure, 'method']`
