### ISSUE TITLE
[PropertyInfo] Namespace use s

### ISSUE THREAD

**Issue by ivansrdic** [symfony/symfony#44417]
### Symfony version(s) affected

5.4.0,6.0.0

### Description

If we have a class which has `use` statements which use a namespace instead of a class/interface, `\Symfony\Component\PropertyInfo\PhpStan\NameScope::resolveStringName` throws an exception.

### How to reproduce

```
namespace App\Test\SomeNamespace;

class MyNamespacedClass
{
}

```

```
namespace App\Entity;

use App\Test\SomeNamespace as TestSomeNamespace;

class MyClass
{
    public function __construct()
    {
        $object = new TestSomeNamespace\MyNamespacedClass();
    }
}

```

run `bin/console cache:clear` and you will get an exception like this

```
In NameScope.php line 50:
  [ErrorException]                                    
  Warning: Undefined array key "MyNamespacedClass"
```

### Possible Solution

I think there is a mistake in logic in `\Symfony\Component\PropertyInfo\PhpStan\NameScope::resolveStringName`, lines 48 and 50. The `array_shift` call is correct, but we need it's output because that's the value by which the uses are indexed in `$this->uses`

Changing those two lines to
```
    public function resolveStringName(string $name): string
    {
        if (0 === strpos($name, '\\')) {
            return ltrim($name, '\\');
        }

        $nameParts = explode('\\', $name);
        if (isset($this->uses[$nameParts[0]])) {
            if (1 === \count($nameParts)) {
                return $this->uses[$nameParts[0]];
            }
            array_shift($nameParts);

            return sprintf('%s\\%s', $this->uses[$nameParts[0]], implode('\\', $nameParts));
        }

        if (null !== $this->namespace) {
            return sprintf('%s\\%s', $this->namespace, $name);
        }

        return $name;
    }
```

```
    public function resolveStringName(string $name): string
    {
        if (0 === strpos($name, '\\')) {
            return ltrim($name, '\\');
        }

        $nameParts = explode('\\', $name);
        if (isset($this->uses[$nameParts[0]])) {
            if (1 === \count($nameParts)) {
                return $this->uses[$nameParts[0]];
            }
            $use = array_shift($nameParts);

            return sprintf('%s\\%s', $use, implode('\\', $nameParts));
        }

        if (null !== $this->namespace) {
            return sprintf('%s\\%s', $this->namespace, $name);
        }

        return $name;
    }
```

**Comment by nicolas-grekas** [comment]
Must be related to #40457 /cc @Korbeil WDYT?

**Comment by Korbeil** [comment]
Thanks for your report @ivansrdic and your ping @nicolas-grekas.
I made a reproducer: https://github.com/Korbeil/symfony/commit/33f8d1758e1b8e3167d784c2fe3da3972ae1fef9 and will try to find a fix as soon as I can :pray: 
I tried with your suggestion but it doesn't seem to fix the issue.

**Comment by ivansrdic** [comment]
@Korbeil 
Any update to this? Is the PR intentionally left with the failing test for the return type patch until someone reviews it, or are the reviewers waiting for that test to be fixed?
Can I help somehow maybe?

**Comment by Korbeil** [comment]
The failing test is not related to the PR, I'm just waiting for someone to review / merge the pull request.
