### ISSUE TITLE
[Translation][Loco] Consider sending `If-Modified-Since` or `If-None-Match` header when pulling translations

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#44414]
### Description

In [their documentation](https://localise.biz/help/developers/api-rate#etag), Loco recommends to send header `If-Modified-Since` (with the previous value of `Last-Modified` response header) or header `If-None-Match` (with the previous value of `ETag` response header), if you need to download changes very regularly (which can be the case in local or CI). 

By implementing this, we can reduce the work load on their side and maybe on our side too.

WDYT?

**Comment by fabpot** [comment]
Looks like a good idea to me. Up for a PR?

**Comment by welcoMattic** [comment]
Looks good to me too @Kocal, go ahead for a PR

**Comment by Kocal** [comment]
I will try to open a PR ASAP. Should `Last-Modified` be stored inside the `.xlf` file? 

Should I target branch 5.3 or 6.1? To me that's a new _internal_ feature that won't be visible to the end user, so I'm more in favor of 5.3.

**Comment by fabpot** [comment]
Not a bug, do 6.1.
