### ISSUE TITLE
[HttpKernel] Wrong template is rendered when configuring an exception status code

### ISSUE THREAD

**Issue by micheh** [symfony/symfony#44433]
### Symfony version(s) affected

5.4.0

### Description

@lyrixx added a way to configure the status code of an exception (in #42244). When configuring the status code of an exception, the HTTP status code of the response is set as expected. However, the rendered HTML template does not seem to take the configured status code in account and Symfony will render the template as if the status code was not set.

### How to reproduce

Use the config:
```
framework:
    exceptions:
        Doctrine\ORM\EntityNotFoundException:
            status_code: 404
```

Then throw an `EntityNotFoundException`. The HTTP status code will be 404, but the rendered template (both in the debug exception template and the production template) will show 500 Internal Server Error.

### Possible Solution

Maybe the exceptions Mapping should also be used in the `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer`?

### Additional Context

The status code of `Symfony\Component\ErrorHandler\Exception\FlattenException::createFromThrowable` is used.

**Comment by lyrixx** [comment]
Thanks for the feedback. I'll have a look this weekend

**Comment by aderiyenko** [comment]
Hi @lyrixx and @micheh!

Not sure I did it correctly, but tried to fix it in [here](https://github.com/symfony/symfony/pull/44456). Could you have a look if and when you have a moment?

**Comment by yceruto** [comment]
We should also take care of `SerializerErrorRenderer` for API exceptions response body.

**Comment by yceruto** [comment]
What if we wrap the original exception (if it's mapped) into a `HttpException` with the mapped status code before handling the exception subrequest in `ErrorListener`? Thus, no change is needed on any ErrorRenderer implementation.

Otherwise, even the custom error renderers will have to worry about this exception mapping strategy on their own to fix the response body info.

**Comment by aderiyenko** [comment]
Thanks for the idea, @yceruto . Let me think of it and try to do. But not sure if I should do it as a separate PR and then we select which one to merge? Just to have both ideas side-by-side. Give me some time, I'll try to come up with something and thanks for the idea!

**Comment by GromNaN** [comment]
> What if we wrap the original exception (if it's mapped) into a `HttpException` with the mapped status code before handling the exception subrequest in `ErrorListener`? Thus, no change is needed on any ErrorRenderer implementation.

@yceruto That would be a breaking change. If any `ErrorRenderer` uses the class of the exception, it would receive an `HttpException`.

Current behavior:
![image](https://user-images.githubusercontent.com/400034/144727465-9dc5c52e-7cfa-4176-8d76-d00102b45dd8.png)

Your suggestion:
![image](https://user-images.githubusercontent.com/400034/144727468-8191ff34-a2a8-4032-8ede-d2f8959ba236.png)

**Comment by yceruto** [comment]
@GromNaN Yes, that's exactly what I meant :) and I think it's fine, the exception class is debugging information, and as we can see in the 2nd screenshot the original exception is still displayed, and it will also be included in the FlattenException as the previous exception.

To be more accurate we could even create a specific HTTP exception for this mapping strategy, something like `MappedHttpException`? thus custom error renderers and devs will know what to do.
