### ISSUE TITLE
[Console] Default command `DumpCompletionCommand` referring to possibly-empty $_SERVER["PHP_SELF"]

### ISSUE THREAD

**Issue by BusterNeece** [symfony/symfony#44457]
### Symfony version(s) affected

5.4.0

### Description

The `DumpCompletionCommand`, one of the commands registered by default when initializing the Symfony Console, appears to now have a check in version 5.4.0 for `$_SERVER["PHP_SELF"]`, with no fallback if that value is empty or not set.

This causes strict tests to fail in CLI environments, where that variable often _isn't_ set. Per the PHP documentation, the `$_SERVER` superglobals are unpredictable at best when invoking commands via a CLI environment, and given that the Symfony Console is almost always doing so, it's even more likely in this scenario.

It's possible that Symfony itself is instantiating this variable in its own bootstrap, but my code uses the Symfony Console component independent of the framework itself, which caused the issue to become apparent quickly.

### How to reproduce

Initialize the default commands via a CLI instance that does not have the `$_SERVER["PHP_SELF"]` variable set:

```php
<?php
error_reporting(E_ALL);

$console = new \Symfony\Component\Console\Application();
```

The resulting error is:

```
Undefined array key "PHP_SELF" at vendor/symfony/console/Command/DumpCompletionCommand.php:42 {"file":"/var/azuracast/www/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php","line":84,"code":2}
```

### Possible Solution

Check for an empty or unset value on the "PHP_SELF" key and avoid using it if absent.

**Comment by n0rbyt3** [comment]
The value always exists. Quoting the PHP docs (https://www.php.net/manual/en/reserved.variables.server.php):
> 'PHP_SELF': [...] If PHP is running as a command-line processor this variable contains the script name.

Even if I run code via ```php -r``` command line, the value is set as ```Standard input code```.

**Comment by GromNaN** [comment]
`$_SERVER["PHP_SELF"]` is also required to show the help of any command.

https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/Console/Command/Command.php#L597

How do you get with an environment without this variable set? Can you provide more context?

**Comment by BusterNeece** [comment]
I looked into it, and the place I'm getting a `$_SERVER` superglobal with no "PHP_SELF" in it is by calling `getServer` on a `Symfony\Component\BrowserKit\Request`. A workaround to this issue in my case is just to supply that value, but it's interesting that it isn't present there.

**Comment by GromNaN** [comment]
Great finding. I understand that you are running `Console\Application`, especially the `DumpCompletionCommand` in the context of a HTTP request, and it fails when you test it with `BrowserKit`.

**Comment by GromNaN** [comment]
Closing, since the issue occurs in a very specific usage and can be fixed by setting de var.
