### ISSUE TITLE
[PhpUnitBridge] Remove return type of MockeryTestCase

### ISSUE THREAD

**Issue by villfa** [symfony/symfony#44450]
### Description

Hi,

When the `SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT` env variable is set to *true* the code of the PHPUnit's TestCase is altered.

It would be great to do the same with MockeryTestCase if present.
`setUp()` and `tearDown()` are overridden in [a trait](https://github.com/mockery/mockery/blob/7a02141/library/Mockery/Adapter/Phpunit/MockeryTestCaseSetUp.php).

That way PHPUnit-Bridge and Mockery would be fully compatible.

I'll could work on a PR if the idea is accepted.

**Comment by nicolas-grekas** [comment]
That's a bit later to resist adding `void` to those methods :)
Can't you fix your codebase instead?

**Comment by villfa** [comment]
Thanks for your answer.

To give you more context I've encountered this issue by helping a library to be compatible with PHP 7.0 up to 8.1: https://github.com/Adldap2/Adldap2/pull/795
I ended up dropping MockeryTestCase entirely.

I'm closing this issue since I'm not even convinced it's worth to be treated.
