### ISSUE TITLE
Preloading problems in Symfony 6

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#44465]
### Symfony version(s) affected

6.0.0

### Description

Context: I have no `symfony/expression-language` package, because I don't need it. 

Nevertheless, PHP preloading fails, because `ExpressionLanguage` is explicitly used in `ExpressionValidator` (`validator.expression` service) and in `ContainerBuilder`. To solve the first problem I can tag `validator.expression` with `container.no_preload` or completely remove it via a compiler pass. The second problem cannot be solved without installing `symfony/expression-language`.

Same thing happens with `doctrine.uuid_generator` and `doctrine.ulid_generator` services. Their classes cannot be preloaded, since I don't have `symfony/uid` component. I have to tag or remove them via a compiler pass.

### How to reproduce

Install symfony without `ulid` and `expression-language` components and try to enable preloading.

**Comment by derrabus** [comment]
Related to #44364?

**Comment by vudaltsov** [comment]
@derrabus, yes, thank you!
