### ISSUE TITLE
Accept @return string[] annotation for array return type

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/symfony#44471]
See https://github.com/doctrine-extensions/DoctrineExtensions/issues/2362 for an example.

A `@return string[]` annotation has been added to the `getSubscribedEvents` method, but we still get this message:

> Method "Doctrine\Common\EventSubscriber::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Gedmo\Uploadable\UploadableListener" now to avoid errors or add an explicit `@return` annotation to suppress this message.

It is possible to accept `@return string[]` instead of `@return array` to suppress this message?

**Comment by fancyweb** [comment]
Any `@return` PHPDoc should suppress the message. I think your issue has been fixed in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2355. Can you close if it's the case, thanks.

**Comment by stephanvierkant** [comment]
I'm sorry, you're right!
