### ISSUE TITLE
[Controller] Convenience method `redirectToCurrentRoute()`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#44485]
### Description

What's the best practice for redirecting to the *current* route (e.g. when following the Post/Redirect/Get pattern)? I'm using
```php
return $this->redirectToRoute($request->get('_route'));
```
...but since https://github.com/symfony/symfony/pull/42392, `Request::get()` is marked `@internal`.

So what about a new convenience method `AbstractController::redirectToCurrentRoute(int $status = 302/303)`?

Or am I missing something and there is another (better) way already? => Then it should be mentioned in https://symfony.com/index.php/doc/current/controller.html#redirecting

**Comment by norkunas** [comment]
`$request->attributes->get('_route')` ?

**Comment by youssefsaoubou** [comment]
if the _route is on the attribute you can fetch it directly from $request->attributes

**Comment by alexislefebvre** [comment]
> Or am I missing something and there is another (better) way already? => Then it should be mentioned in https://symfony.com/index.php/doc/current/controller.html#redirecting

The doc is managed on another repo: https://github.com/symfony/symfony-docs

---

Update: My bad, I didn't saw the link above.

**Comment by derrabus** [comment]
Does @norkunas' answer work for you? I don't feel like we should add the proposed method.

**Comment by ThomasLandauer** [comment]
Yeah, thanks, works - see my docs PR: https://github.com/symfony/symfony-docs/pull/16211

Convenience method: My point is that this is a little lengthy, given how often people are needing it:
```php
return $this->redirectToRoute($request->attributes->get('_route'));
```
This would just be shorter:
```php
return $this->redirectToCurrentRoute();
```
But if you don't think it's worth it, you can close this :-)

**Comment by derrabus** [comment]
Okay, let's close. Thanks for the docs PR!
