### ISSUE TITLE
[DependencyInjection] Support first-class callable syntax for factory service configuration

### ISSUE THREAD

**Issue by marforon** [symfony/symfony#44492]
### Description

It would be nice if we could use a closure for factory definition.

### Example

```php
return function (ContainerConfigurator $configurator): void {
    $services = $configurator->services();

    $services
        ->set(Client::class)
        ->factory(ClientBuilder::fromConfig(...))
        ->arg('$config', []);
};
```
instead of:
```php
return function (ContainerConfigurator $configurator): void {
    $services = $configurator->services();

    $services
        ->set(Client::class)
        ->factory([ClientBuilder::class, 'fromConfig'])
        ->arg('$config', []);
};
```

**Comment by xabbuh** [comment]
Wouldn’t this mean that your factory method would be executed when the container is compiled instead of at runtime only when the service is actually needed?

**Comment by marforon** [comment]
Maybe using ReflectionFunction to covert it into array?
```php
$reflection = new \ReflectionFunction($closure);
$value = [$reflection->getClosureScopeClass()->getName(), $reflection->getName()]
```
We would get rid of string methods references this way.

**Comment by GromNaN** [comment]
This is a [new syntax of PHP 8.1](https://www.php.net/releases/8.1/en.php#first_class_callable_syntax) that we should try to support in 6.1

Do you want to open a PR @marforon?

**Comment by marforon** [comment]
@GromNaN I will give it a try, thanks :)

**Comment by stof** [comment]
The hard part about using a closure is that we cannot support arbitrary closures there (as we cannot dump them in the compiled code).
So we would have to find a way to detect cases corresponding to first-class callables for a static method or a function, and extract the original callable from them. I fear that the proposal of @marforon is incomplete, as I think you would get a similar result when inspecting `$configBuilder->fromConfig(...)`

**Comment by marforon** [comment]
@stof You are right. I think there is no way to detect a first-class callable. The only thing we can do is to detect if Closure is calling a static method or not and ignore possible instance call. The downside is it could confuse someone. Feel free to close it.

**Comment by nicolas-grekas** [comment]
That's not possible as explained by @stof
