### ISSUE TITLE
[PropertyInfo] PhpStanTypeHelper doesn't support ConstTypeNode

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#44491]
### Description

After updating from Symfony 5.3 to Symfony 5.4, our code started to crash. This is because new PhpStanExtractor was introduced that was prioritized above older extractors. This extractor started to return `null` type and hence serializer failed to denormalize our objects.

It returns null, because this is a UnionTypeNode containing ConstTypeNode and IdentifierTypeNode (null). However PhpStanTypeHelper doesn't handle ConstTypeNode and hence symfony/property-info will return `null` only.

### Example

```php
class Foo
{
   /**
     * @return PageType::*|null
     */
    public function getDynamicPageType(): ?string
    {
        return rand(0, 1) ? PageType::FOO : null;
    }
}

class PageType {
    const FOO = 'foo';
}
```
On Symfony 5.3, this returns string|null. On Symfony 5.4, because PhpStanExtractor was added which doesn't correctly handle unions, it returns null.

**Comment by ostrolucky** [comment]
Similar issue is for `@var non-empty-array<int, string>` with error like
```
Symfony\Component\Serializer\Exception\NotNormalizableValueException : The type of the "slugs" attribute for class "Haushalt\Bl\DomainBundle\Domain\Routing\Entity\RouteInformation" must be one of "Haushalt\Bl\DomainBundle\Domain\Routing\Entity\non-empty-array" ("array" given).
```

**Comment by milikamel** [comment]
no one seems to be interested to reply here!
