### ISSUE TITLE
Profiler show `Deprecations` in all pages

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony#44495]
### Symfony version(s) affected

6.0.0

### Description

I Use Symfony 6.0 and profiler show `Deprecations` in all pages:

```
The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@link \Doctrine\DBAL\Logging\Middleware} or implement {@link \Doctrine\DBAL\Driver\Middleware} instead.

[
  "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext {#680
    +count: 1
    -severity: E_USER_DEPRECATED
    trace: {
      C:\prj\sym6\vendor\symfony\error-handler\DebugClassLoader.php:328 {
        class_exists(string $class, bool $autoload = true): bool …
        › foreach ($deprecations as $message) {
        ›     @trigger_error($message, \E_USER_DEPRECATED);
        › }
      }
      C:\prj\sym6\vendor\symfony\config\Resource\ClassExistenceResource.php:78 {
        › try {
        ›     $exists[0] = class_exists($this->resource) || interface_exists($this->resource, false) || trait_exists($this->resource, false);
        › } catch (\Exception $e) {
      }
    }
  }
]
```

### How to reproduce

Read description ...

**Comment by stof** [comment]
This is a new deprecation in Doctrine DBAL 3.2+ (released a few days ago).
Work is in progress in DoctrineBundle to migrate to the new way. See https://github.com/doctrine/DoctrineBundle/issues/1431 and https://github.com/doctrine/DoctrineBundle/issues/1429 for the work to migrate away from the SQLLogger interface (the DbalLogger class itself won't be changed to stop using the interface, but it will be deprecated in the future once dropping support for older DBAL versions)
