### ISSUE TITLE
preg_match PHP 8.1 deprecation in getProtocolVersion call on request from trusted proxy

### ISSUE THREAD

**Issue by Guuzen** [symfony/symfony#44498]
### Description

If there is no "Via" header then call will be deprecated because of null parameter for preg_match
This code branch executed (and deprecation triggered) only for requests from trusted proxies.

Deprecation message
`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in vendor/symfony/http-foundation/Request.php on line 1518`

**Comment by GromNaN** [comment]
Hello @Guuzen, thanks for reporting this issue. Can you provide a reproducer, ideally with a test case in `RequestTest`.

**Comment by Guuzen** [comment]
Sorry, maybe later. I am too lazy
But for anyone who more interested it is probably not very hard. You can try to add something like
`'trusted with null via' => ['HTTP/2.0', true, null, 'HTTP/2.0'],` dataset to `protocolVersionProvider` in `RequestTest`
