### ISSUE TITLE
[DependencyInjection] Introduce caching to AbstractRecursivePass

### ISSUE THREAD

**Issue by dochne** [symfony/symfony#44507]
### Description

I'm looking at upgrading one of our larger projects to be built entirely on the back of Symfony rather than the more flakey foundations it's currently on.

As the documentation notes, with larger projects, the Autowirer struggles on dev (this one has 5000 classes to chew through).

Looking at the flame graph [1], the bulk of the time seems to be spent chewing through the `AbstractRecursivePass` for every auto-wired class, even if only a constructor argument on a single Controller has changed.

There would of course be some annoying complexity involved (cache invalidation for inherited classes etc), but is this something that would be worth me putting some hours into fleshing out or is it a case where the added complexity (for a niche use-case) would make it unlikely to get upstreamed?

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/1678803/145227559-0d923100-ec3b-441f-9339-1fb0681172d6.png">

**Comment by nicolas-grekas** [comment]
Caching/partial updates is not possible because a minor change in a file can spread to many files with eg compiler passes and tracking those dependencies is too heavy.

I'm afraid we won't be able to do anything here.

Maybe disabling autowiring could help in your case, but I get that would break some part of the DX...

**Comment by nicolas-grekas** [comment]
You might want to use blackfire.io to find possible optimizations btw.

**Comment by dochne** [comment]
Was worth a try! Thanks for getting back to me!
