### ISSUE TITLE
Issue with lint command and cache.adapter.redis after upgrade to 5.4.0

### ISSUE THREAD

**Issue by lugosium** [symfony/symfony#44515]
### Symfony version(s) affected

6.0.0

### Description

After upgrading to 5.4.0, everything is working fine except the lint command which gives:

```
 [ERROR] Invalid definition for service "cache.app": argument 1 of
         "Symfony\Component\Cache\Adapter\RedisAdapter::__construct()" accepts
         "Redis|RedisArray|RedisCluster|Predis\ClientInterface|Symfony\Component\Cache\Traits\RedisProxy|Symfony\Compone
         nt\Cache\Traits\RedisClusterProxy", "Symfony\Component\Cache\Adapter\AbstractAdapter" passed.
```

### How to reproduce

Use redis as cache for system and app:

```
framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: 'redis://localhost'
```

Launch lint command:

`./bin/console --env dev lint:container`

### Additional Context

If i comment app and system keys, it's OK with the default values.

**Comment by chalasr** [comment]
I'm on it.

**Comment by lugosium** [comment]
My bad @chalasr, it's only on v6.0.0 that the problem occurs.

**Comment by chalasr** [comment]
@lugosium No worries, I guessed it as the real type declaration has only been introduced on 6.0.

**Comment by Philosoft** [comment]
Does it affect only `lint:container` command (so only CI step should be disabled for me) or it will shoot me in the ~a~ back in the most inconvenient time possible? That thing is really frightening to me on a way to 6.0 upgrade

**Comment by lugosium** [comment]
> Does it affect only `lint:container` command (so only CI step should be disabled for me) or it will shoot me in the ~a~ back in the most inconvenient time possible? That thing is really frightening to me on a way to 6.0 upgrade

It's only the lint command, everything else work correctly.

**Comment by lugosium** [comment]
Thank you everybody.
