### ISSUE TITLE
`$request->query->get()` should support arrays

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#44524]
### Symfony version(s) affected

5.4.0

### Description

`InputBag::get` has typed @return as `string|int|float|bool|null` but it can return array as well.

### How to reproduce

`/run/route/?query[]=1.1.1.1&query[]=2.2.2.2` and in controller inspect the Request object.

`$request->query->get('query')` returns `list<string>`

### Possible Solution

Add `array` type to return and `$default` types for `InputBag::get()`

**Comment by stof** [comment]
Returning array is deprecated (see the deprecation message). You should use `all()`

**Comment by simPod** [comment]
Ah ok. I expected the information to be in a signature/doc, did no read the method implementation.

Is there any way this could be fixed in a feature, I mean to be documented in method doc?

Thanks
