### ISSUE TITLE
[Lock] Too few arguments to function Symfony\Component\Lock\Store\DoctrineDbalPostgreSqlStore::putOffExpiration()

### ISSUE THREAD

**Issue by metaer** [symfony/symfony#44535]
### Symfony version(s) affected

5.4.1

### Description

`\Symfony\Component\Lock\Store\PostgreSqlStore::putOffExpiration` calls `\Symfony\Component\Lock\Store\DoctrineDbalPostgreSqlStore::putOffExpiration` and passes only one argument, but two arguments are required.

```php
if (isset($this->dbalStore)) {
    $this->dbalStore->putOffExpiration($key);

    return;
}
```

```php
public function putOffExpiration(Key $key, float $ttl)
```

### How to reproduce

Use PostgreSqlStore and call `$lock->acquire(true);`

### Additional Context

```
    "class": "ArgumentCountError",
    "message": "Too few arguments to function Symfony\\Component\\Lock\\Store\\DoctrineDbalPostgreSqlStore::putOffExpiration(), 1 passed in vendor/symfony/lock/Store/PostgreSqlStore.php on line 146 and exactly 2 expected",
    "code": 0,
    "file": "vendor/symfony/lock/Store/DoctrineDbalPostgreSqlStore.php:104",
    "trace": [
        "vendor/symfony/lock/Store/PostgreSqlStore.php:146",
        "vendor/symfony/lock/Lock.php:205",
        "vendor/symfony/lock/Lock.php:102",
```

**Comment by metaer** [comment]
This commit seems to be related to the issue: https://github.com/symfony/lock/commit/97215a91#diff-c3cff1d4763c5a1e1dd7e76a0759db5e2005126c9027c1f2daa5015aa1f579c8R146 @GromNaN

**Comment by GromNaN** [comment]
Thank you for reporting this bug; here is a fix: #44539.

As a workaround, you should switch to `DoctrineDbalPostgreSqlStore`. Using `PostgreSqlStore` with a DBAL connection is deprecated.

**Comment by metaer** [comment]
> Using PostgreSqlStore with a DBAL connection is deprecated.

Actually I use `PostgreSqlStore` with DSN (according to documentation). `DoctrineDbalPostgreSqlStore` requires _"A Connection instance or Doctrine URL"_

**Comment by stof** [comment]
well, are you using a PDO DSN or a URL ? If you reach this code, it probably means you were actually using a URL rather than a PDO DSN, and so relying on doctrine (check your deprecation warnings).

**Comment by metaer** [comment]
I use such format of string: `'postgresql://user:password@host:port/dbname'`

There is example in 6.0 documentation: https://symfony.com/doc/current/components/lock.html#postgresqlstore
Is that example correct?

```php
use Symfony\Component\Lock\Store\PostgreSqlStore;

// a PDO, a Doctrine DBAL connection or DSN for lazy connecting through PDO
$databaseConnectionOrDSN = 'postgresql://myuser:mypassword@localhost:5634/lock';
$store = new PostgreSqlStore($databaseConnectionOrDSN);
```

**Comment by stof** [comment]
Well, this is a case where the documentation has not been updated yet. Those URLs rely on DBAL to support them. They are not PDO DSNs.

**Comment by metaer** [comment]
So, I should use `DoctrineDbalPostgreSqlStore` with such kind of string, right?

**Comment by stof** [comment]
yes

**Comment by metaer** [comment]
Thank you
