### ISSUE TITLE
Session is not being created after upgrade to 5.4.1

### ISSUE THREAD

**Issue by verng95** [symfony/symfony#44546]
### Symfony version(s) affected

5.4.1 or 6.0.1

### Description

After upgrading to version 5.4.1/6.0.1, the session stopped working. As a result of the search, I realized that the problem was with this [https://github.com/symfony/symfony/pull/44437](https://github.com/symfony/symfony/pull/44437), if you roll it back, it became normal.

### How to reproduce

if `framework.session.cookie_secure: auto` is set, then:

- `https `connections will create a session
- `http `connections will not create a session

### Possible Solution

File `src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php` Line 32:

If you replace this:

`$sessionCookieWithId = sprintf('%s%s;', $sessionCookiePrefix, urlencode($sessionId));`

On

`$sessionCookieWithId = sprintf(' %s%s;', $sessionCookiePrefix, urlencode($sessionId));`

That works correctly.

**Comment by nicolas-grekas** [comment]
Thanks for the details. Would you like sending a PR with the fix and a test case?

**Comment by verng95** [comment]
> Thanks for the details. Would you like sending a PR with the fix and a test case?

Ok, I guess I'll do it.

**Comment by fritzmg** [comment]
@verng95 can you confirm, that this currently only affects `http` connections and not secure connection via `https` (assuming you use `framework.session.cookie_secure: auto`)?

**Comment by verng95** [comment]
> @verng95 can you confirm, that this currently only affects `http` connections and not secure connection via `https` (assuming you use `framework.session.cookie_secure: auto`)?

@fritzmg Yes, indeed. Now I turned off `framework.session.cookie_secure` and it worked. So the problem is in `auto`.

**Comment by fritzmg** [comment]
Just to clarify - what we observe is the following:

if `framework.session.cookie_secure: auto` is set, then:

* `https` connections will create a session
* `http` connections will not create a session

**Comment by alexander-schranz** [comment]
@verng95 Thank you for the report. It seems currently `auto` is not correctly handled here: https://github.com/symfony/symfony/blob/3a1f34ae4b9c3b637ff26ef90b97269a9401f919/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L140

If `$sessionCookieSecure` would be `auto` we need to handle that. I need first check where `cookie_secure: auto` was handled before. But I'm definetly sure that, that line is causing the issue as `auto` is now interperted as `true`.

**Comment by alexander-schranz** [comment]
Can you try out #44518 this should fix the issue with `cookie_secure` not being handled.

**Comment by fritzmg** [comment]
I can confirm that #44518 would fix the problem for us.
