### ISSUE TITLE
Collection Validation Bug by reindexing related Keys

### ISSUE THREAD

**Issue by andimg93** [symfony/symfony#44540]
### Symfony version(s) affected

x, 5.3.X, 5.4.0 - I just tested some 5.3 versions and 5.4.0, where the bug still exists

### Description

If you use the collection type in Forms and want to make the elements manageable for the user (via allow_add/allow_delete each to true) you get a prototype on the element, as you know.
This must now be added for new elements via Javascript. By default, the respective index/key locations are marked by __name__.
These are now replaced via Javascript with a unique key - So far everything is known, now I come to the actual problem.

If you replace them with a unique alphanumeric key, validations are no longer possible for any of the elements in the collection.
The validation itself works, visible via form_errors to output all errors of all collection elements.
However, the errors can no longer be assigned to the individual elements of the collection.
This is due to the fact that the transmitted keys, from the request, are not observed by Symfony. 
Symfony however reindexes the elements of the collection.
If you transfer the following elements, for example:
A1 => CollectionItemObj1,
A2 => CollectionItemObj2,
A3 => CollectionItemObj3
the Ax keys are ignored and the elements are present in the collection as follows:
0 => CollectionItemObj1,
1 => CollectionItemObj2,
2 => CollectionItemObj3
Based on this format, the validations are then also assigned.
Collection[Index].ElementName

Even if you do now completely without alphanumeric keys, this does not change the error.
Why?
Simply because if the index/key of the first element is 0 and for the second logically 1 - The user now deletes the first element, index/key 1 is the first element. Thus 1, 2, 3, n is transferred instead of 0,1,2, n - The validations therefore refer to 0, 1, 2 which leads to validation errors for some elements not being displayed at all or incorrectly because they belong to another element.

### How to reproduce

Just create a Form with a CollectionType, which allows the user to add/remove elements - Just as I have told/described in the description field.

### Possible Solution

Solution would be that Symfony does not reindex the elements of the collection, but takes the transferred array (from the request) - Here the keys are correct.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by andimg93** [comment]
I see no need for that, its very simple to reproduce as I described and I have just seen that the problem has been reported since 2013 again and again in different ways, see for example here https://github.com/symfony/symfony/issues/7468

You can link my report with that problem, but please put more priority on this problem which has been going on for over 8 years now 😖

**Comment by xabbuh** [comment]
This is open source. I am happy to review your contribution around this problem that takes all the concerns raised in the related issues into account.

**Comment by andimg93** [comment]
@xabbuh check https://github.com/symfony/symfony/pull/39438 - There is already an open contribution, don't know why it is added and removed from the Symfony releases as you can see.
