### ISSUE TITLE
[Security] PasswordAuthenticatedUserInterface and UserInterface are not compatible

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#44542]
### Symfony version(s) affected

5.4

### Description

I am unable to implement both the UserInterface here:
https://github.com/symfony/security-core/blob/5.4/User/UserInterface.php

And the PasswordAuthenticatedUserInterface interface here:
https://github.com/symfony/security-core/blob/5.4/User/PasswordAuthenticatedUserInterface.php

The getPassword signatures will not match because PasswordAuthenticatedUserInterface declares the return type so I get the error:
```
Compile Error: Declaration of Symfony\Component\Security\Core\User\UserInterface::getPassword() must be compatible with Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface::getPassword(): ?string
```

### How to reproduce

Implement both interfaces on a User entity.

### Possible Solution

Declare the `?string` return type in UserInterface.

**Comment by chalasr** [comment]
Can you please show your User class? I suspect this is the same issue as https://github.com/symfony/symfony/issues/41519.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by silverbackdan** [comment]
Hi, I'm sorry to take so long to reply! It was indeed the same issue. Thank you for your prompt response.
