### ISSUE TITLE
[Validator] Allow PHP 8.1 enums as `Assert\Choice`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#44564]
### Description

Allow using a backed enum as `choices` for the `Choice` assertion.

### Example

```php
#[Assert\Choice(choices: MyEnum::class)]
```
Or as in [EnumType](https://symfony.com/doc/current/reference/forms/types/enum.html#class)
```php
#[Assert\Choice(class: MyEnum::class)]
```

**Comment by derrabus** [comment]
Duplicate of #43047.
