### ISSUE TITLE
[Routing] Support PHP 8.1 enums as route `name`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#44563]
### Description

I'm trying to avoid strings as Route `name`, so I've created a `Page` class that holds `const`s for it:

```php
abstract class Page
{
    public const HOME = 'SomeUselessStringThatNobodyNeeds';
}
```
Controller:
```php
#[Route(path: '/', name: Page::HOME)]
```
I think this would be a perfect use-case for a **pure enum:**
```php
enum Page
{
    case Home;
}
```
Controller:
```php
#[Route(path: '/', name: Page::Home)]
```
Right now, this leads to:
> Symfony\Component\Routing\Annotation\Route::__construct(): Argument # 2 ($name) must be of type ?string, App\Enum\Page given

**Comment by nicolas-grekas** [comment]
Why? I feel like there would be no benefits to use an enum here personally. At least I don't see any yet.

**Comment by GromNaN** [comment]
The purpose might be to remove this "SomeUselessStringThatNobodyNeeds".

If route name can be enum values, the UrlGenerator will have to support them. And that add a new challenge to generate a URL in Twig.

**Comment by ThomasLandauer** [comment]
Benefits:
1. Gut feeling :-) From my understanding, enums were invented for cases like this; while having a class that contains just `const`s feels like misusing the class idea.
2. Indeed, getting rid of the overhead of having to define some string value (which the user doesn't need).
3. Built-in check for uniqueness: Duplicate values might happen with `const`s:
    ```php
    const HOME    = 'foo';
    const CONTACT = 'foo';
    ```
    ... but are forbidden in enums.

**Comment by stof** [comment]
The URL generator uses route names as array keys in the dumped cache code, allowing to get the route info in `O(1)` when generating URLs. So supporting enums there will be hard.

**Comment by nicolas-grekas** [comment]
To me, enums are useful to restrict possibilities to a range of limited values. Route names don't fall in this category.
Using enums here would look like a hack to me and given the technical complication (eg what should `debug:router`, etc), I'm not convinced we should do it.

**Comment by derrabus** [comment]
As much as I'd like to explore the possible uses of enums further: I agree with @nicolas-grekas that enums are not useful here. I wouldn't store route names in constants either, btw. The proposed changed would introduce complexity for now real benefit.

**Comment by derrabus** [comment]
Let's close because we aready have downvotes from several core team members. Thanks for the proposal though.

**Comment by ThomasLandauer** [comment]
Yeah, closing is OK. Just one more question: How do you guys manage your route names then? I was thinking the `const`s are a good idea, they're also mentioned at https://tomasvotruba.com/blog/2020/12/21/5-new-combos-opened-by-symfony-52-and-php-80/#2-Route-Names-Can-be-Constants

**Comment by nicolas-grekas** [comment]
https://github.com/php/php-src/pull/8825 could be a solution here, allowing seamless compatibility between enumerated routes and the routing component.

**Comment by ThomasLandauer** [comment]
An even better idea would be to allow getting rid of the `name` completely: https://github.com/symfony/symfony/issues/49981
