### ISSUE TITLE
[RFC] Make Log dir nullable

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#44579]
### Description

In context of containers - one of best practices is to write logs in stdout and stderr, rather than in files. 
unfortunately - log dir is required - even if not used.

Proposal is to either add new interface like `LoggableKernel` which requires `getLogDir` or make `getLogDir` nullable. In both cases: disable checks on logs dir.

**Comment by ro0NL** [comment]
You could throw an exception also isnt it, that should spot any call. AFAIK `%kernel.logs_dir%`is a widespread semantic in bundles, recipes, everywhere :) making it nullable/optional has a cost.

**Comment by Warxcell** [comment]
But why? The aim here is to be able to remove usage of it, rather than hacking it with **/dev/null** or **/dev/stdout** or **/dev/stderr**. And isn't it used internally by symfony only? Why would bundle use it? 

In our case - we just set it to some random string anyway, because we know it's not used anywhere. And in symfony I see only one usage of it - as default path of Monolog path configuration.

And still - recipe by default can generate Kernel with default implementation of `getLogsDir()` and opt-in removal of the interface and method.

**Comment by derrabus** [comment]
I think, this is a reasonable proposal. Logging should not default to the filesystem anymore, so a mandatory log dir setting does not feel right anymore.

**Comment by Warxcell** [comment]
It's totally ok to keep current behaviour as default - I'm just asking to be able to remove the current behaviour afterwards. 
The problem is in the Kernel::buildContainer: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpKernel/Kernel.php#L625

as it requires folder to be writeable at the time of **cache:clear**, which even is not a guarantee to be writable afterwards - for example we use read-only filesystem at runtime.

So that fragment will become

```
$folders = ['cache' => $this->getCacheDir(), 'build' => $this->warmupDir ?: $this->getBuildDir()];

if ($this instanceof LoggableKernel) {
   $folders['logs'] = $this->getLogDir();
}

foreach ($folders as $name => $dir) {
```

**Comment by nicolas-grekas** [comment]
Would you like to work on a PR for this @Warxcell?

**Comment by Warxcell** [comment]
Yes, sorry for the delay. I will try to implement this till the end of the week. I should target 6.1, right?

**Comment by GromNaN** [comment]
The log dir is defined with a default value (`%kernel.project_dir%/var/log`). This directory must exist and be writable **only when the DIC is built** (like the `cache` dir).
At runtime, this directory can be missing.

The only benefit I see of removing this config is to remove [`var/log/.gitkeep`](https://github.com/symfony/demo/blob/main/var/log/.gitkeep). While we would have to disable the log dir in the config.

Alternative proposition: remove the [check](https://github.com/symfony/symfony/blob/791ee7d1466f189357b9e17f6880f695f0a5f595/src/Symfony/Component/HttpKernel/Kernel.php#L625-L632) on build time; and assume the users check if the directory exist and is writable before using it.
