### ISSUE TITLE
Unsetting Constraint::$groups in constructor is a bit hacky

### ISSUE THREAD

**Issue by stlrnz** [symfony/symfony#44594]
### Symfony version(s) affected

6.0.1

### Description

In https://github.com/symfony/symfony/commit/aa4fb0c2c4c3a5ef135ea671c7c6cd03ece56d9e you removed the usage of dynamic properties in Symfony.
While I'm a huge fan of this the new behaviour of the `$groups` property in `Constraint` seems a bit hacky (and confusing) to me. It is
* declared as public -> part of the API of this class
* typed as `string[]` -> seems not to be optional
* removed in the constructor by calling `unset($this->groups);` (and only re-set optionally) -> seems to be optional

So while beeing declared as non-optional this property in fact is optional. This not only seems confusing for me, when declaring custom constraints Psalms reports an error, too:

> ERROR: PropertyNotSetInConstructor - MyConstraint.php:12:7 - Property MyConstraint::$groups is not defined in constructor of MyConstraint or in any methods called in the constructor (see https://psalm.dev/074)

### How to reproduce

Declare a custom Constraint and run psalm.

```php
<?php

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class MyConstraint extends Constraint
{
    public string $message = 'Invalid value.';
}
```

### Possible Solution

Maybe it is an option to declare the property as nullable and set it to null in constructor?

**Comment by nicolas-grekas** [comment]
See #44037, which links to https://wiki.php.net/rfc/deprecate_dynamic_properties, which explains that this is the way to go.
