### ISSUE TITLE
[Translation][Loco] Consider handling the special status "blank translation"

### ISSUE THREAD

**Issue by kgonella** [symfony/symfony#44595]
### Description

Currently, the adapter only handles the status "translated" when pulling translations. In loco, there is a special status "blank translation" which allows to say that this key is translated but empty. This status is useful because you cannot save an empty key with the status "translated". The export API allows you to combine the statuses if you separate them with "," like in the example

### Example

The method read of LocoProvider will look like this : 
```
$response = $this->client->request('GET', sprintf('export/locale/%s.xlf', rawurlencode($locale)), [
    'query' => [
        'filter' => $domain,
        'status' => 'translated, blank-translation',
    ],
]);
```

**Comment by kgonella** [comment]
I forgot to ping the right guy => @welcoMattic

**Comment by welcoMattic** [comment]
Hi @kgonella. Good catch, I guess you can open a PR to add the status in the HTTP parameters of the export request

**Comment by kgonella** [comment]
Done @welcoMattic. I wasn't sure if I need to handle some tests as well because there is no real call to the api, everything is mocked.
