### ISSUE TITLE
Maker bundle write deprecated and not working code.

### ISSUE THREAD

**Issue by snipershady** [symfony/symfony#44610]
### Symfony version(s) affected

5.4.1, 6.0.1

### Description

Creating a new project from basic starting steps will produce a not working code.
Registration doesn't works. It reports invalid CSFR token so the $form->isValid() method returns "false".

This issue involves both the latest versions of Symfony.

Moreover, the **Security/Authenticator** 
is still using `$request->request->get()` instead of `$request->get();`

`namespace App\Security;
...
...
class Authenticator extends AbstractLoginFormAuthenticator`

that's the method created by **"make:auth"**

```
public function authenticate(Request $request): Passport
    {
        $email = $request->request->get('email', '');

        $request->getSession()->set(Security::LAST_USERNAME, $email);

        return new Passport(
            new UserBadge($email),
            new PasswordCredentials($request->request->get('password', '')),
            [
                new CsrfTokenBadge('authenticate', $request->request->get('_csrf_token')),
            ]
        );
    }
```

### How to reproduce

composer create-project symfony/website-skeleton my_project_name

enable sqlite in .env

make:user
make:controller Default
make:auth
make:registration-form

try to register a user. It doesn't work. 

then try to remove $form->isValid() to force the registration without csfr validation

now try to log in. it doesn't work too.

### PHP version
PHP 8.1.0

### Possible Solution

I hadn't found a clean solution yet.

**Comment by stof** [comment]
Using `$request->request->get()` is not deprecated at all. It is even *recommended* over `$request->get()` when we specifically want to read from the POST values instead of allowing multiple sources.

and the authenticator has nothing to do with the CSRF validation on the user registration, so I don't understand your report.

**Comment by snipershady** [comment]
@stof  login doesn't work, too.
That's why I've reported information about Authenticator and Registration.

Please, try to reproduce all steps and let me know if you are able to understand

**Comment by xabbuh** [comment]
> Registration doesn't works. It reports invalid CSFR token so the $form->isValid() method returns "false".

This looks like a duplicate of #44541.

**Comment by snipershady** [comment]
I was just posting that, watching https://github.com/symfony/symfony/issues/44541
registration problem is because CSRF cannot access "session" because of cookies in the local environment.

Login and Authentication, too

**Comment by xabbuh** [comment]
Does that mean we can close this one as a duplicate of #44541?
