### ISSUE TITLE
[Messenger] Support Google Pub/Sub transport

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#44635]
### Description

[Pub/Sub](https://cloud.google.com/pubsub/docs/overview) is a queueing service of Google Cloud.

> Pub/Sub combines the horizontal scalability of Apache Kafka and Pulsar with features found in traditional messaging middleware like Apache ActiveMQ and RabbitMQ, such as dead-letter queues and filtering.

It should use the official [google/cloud-pubsub](https://github.com/googleapis/google-cloud-php-pubsub).

**This issue is waiting for a contributor.**

**Comment by GromNaN** [comment]
Existing enqueue provider: https://github.com/php-enqueue/gps

**Comment by Guikingone** [comment]
Hi 👋🏻 

If I'm right, this idea was discussed back in the days but discarded as Google use a "all-in-one" package that force Symfony to use the OAuth authentication (and searching for the credentials file, not to mention that Sf cannot use HttpClient here as the internal client is built within the library), the solution was to use the REST API: https://cloud.google.com/pubsub/docs/reference/rest.

But it forces Sf to maintain and ensure that the API can be used without breaking the Sf API.

PS: There was a PR back in the days but didn't retrieve it 🙁 

EDIT:

Found it: https://github.com/symfony/symfony/pull/38624

**Comment by GromNaN** [comment]
Thank you for the pointer @Guikingone, I did't found the closed PR. 
Since the situation did not change since 2019, I close the issue.

Could be re-open if a libary for Google API of created, on top of `symfony/http-client`.

**Comment by pulzarraider** [comment]
For anyone looking for a Pub/Sub Symfony bundle, check out [gps-messenger-bundle](https://github.com/petitpress/gps-messenger-bundle).
