### ISSUE TITLE
Setting session causes 'cannot modify header information' warning

### ISSUE THREAD

**Issue by bjornpost** [symfony/symfony#44654]
### Symfony version(s) affected

5.4.1

### Description

When I call `$session->set()`, I get a "Cannot modify header information" warning.

### How to reproduce

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;

class IssueController extends AbstractController
{
    public function issue(RequestStack $requestStack): Response
    {
        $session = $requestStack->getSession();
        $session->set('foo', 'bar');

        $response = new Response('hello');

        return $response->send();
    }
}
```

### Possible Solution

The warning disappears when I remove [L52-55 in SessionUtils.php](https://github.com/symfony/symfony/blob/v5.4.1/src/Symfony/Component/HttpFoundation/Session/SessionUtils.php#L52-55), but that's probably not the way to solve this.

### Additional Context

I'm on PHP 8.1.0, the issue appears both in development mode (with `symfony serve`) and production. I cannot reproduce the issue in Symfony 5.3.x.

Exact log message:
> [PHP-FPM    ] [15-Dec-2021 19:42:50 Europe/Amsterdam] [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse".
> [PHP-FPM    ] [15-Dec-2021 19:42:50 Europe/Amsterdam] [critical] Uncaught PHP Exception ErrorException: "Warning: Cannot modify header information - headers already sent by (output started at /redacted/vendor/symfony/http-foundation/Response.php:397)" at /redacted/vendor/symfony/http-foundation/Session/SessionUtils.php line 52

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by cs278** [comment]
`return $response->send();` should just be `return $response;` which should fix the problem?

**Comment by bjornpost** [comment]
@cs278 Oof, you're totally right! Stupid oversight-- sorry for the noise.
