### ISSUE TITLE
[Dotenv] Failure tolerant env loading

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#44662]
### Description

It is pretty stupid to set up a dotenv loading as template base to work in all situations

- .env exists
- .env.dist exists and .env not
- .env.local.php exists but .env not
- no file exists as docker container env

Idea: Add a mode to NOT throw an exception if a file does not exists

**Comment by nicolas-grekas** [comment]
I'm not sure what you mean here.

I don't know about others, but note that when an issue starts with "It is pretty stupid" and continues with what I read as some cryptic description, it usually doesn't encourage me to put much willingness into it.

Feel free to submit a PR if you want. Code is always explicit.

**Comment by shyim** [comment]
When you use in your index.php the Dotenv library like so

```
(new Dotenv())->usePutenv()->bootEnv(dirname(__DIR__) . '/.env');
```

And you don't have a `.env` file in the project. Currently there is a Exception thrown. When the project should run also out of the box for Docker (where normally nobody use .env files), you need to add a file_exists check if there is a .env file.

Due there are so many ways how the filename can be you need to do uggly if checks before using this library like:

```
 if (class_exists(Dotenv::class) && (file_exists($projectRoot . '/.env.local.php') || file_exists($projectRoot . '/.env') || file_exists($projectRoot . '/.env.dist'))) {
 ```

So the idea would be to have a new option like `->ignoreIfNotFound()` which doesn't throw a exception 😅 

Edit:// nevermind I will migrate it to Symfony flex and this should avoid this stuff
