### ISSUE TITLE
Symfony v4.4.35 is not compatible with Twig v2.13.0

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#44663]
### Symfony version(s) affected

4.4.35

### Description

The problematic line of code is https://github.com/symfony/symfony/blob/v4.4.35/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L210 where `Twig\Environment::supports()` is called, but it's not defined in https://github.com/twigphp/Twig/blob/v2.13.0/src/Environment.php.

https://github.com/symfony/symfony/blob/v4.4.35/composer.json#L40 says `v4.4.35` is compatible with Twig `v2.13.0`, but because of this undefined call, it seems like it has problems with it, or it's caused by some old configuration that's no longer valid in `4.4.35`.

### How to reproduce

Just run any app that uses twig with Symfony v4.4.35 and Twig v2.13.0.

For me it happened when I upgraded:

```
  - Upgrading symfony/symfony (v4.4.11 => v4.4.35)
  - Upgrading twig/twig (v2.12.2 => v2.14.8)
```

**Comment by stof** [comment]
This line is calling the `supports` method on the `templating` service, not on the `twig` service. So please provide an actual reproducer.

**Comment by umpirsky** [comment]
Sorry, I had a bad unit test, please ignore.
