### ISSUE TITLE
[Session] issue with the visibility of properties in SessionFactory class

### ISSUE THREAD

**Issue by deepika-maj** [symfony/symfony#44675]
### Description

On 5.4 branch, I think the properties of `Symfony\Component\HttpFoundation\Session\SessionFactory` class should be set to `protected` in order to write our own `SessionFactory` class by extending it and without re-writing everything.

**Comment by alexander-schranz** [comment]
You can just overwrite the construct and so get the sessionFactory in your own instance:

```php
    private $storageFactory;

    public function __construct(RequestStack $requestStack, SessionStorageFactoryInterface $storageFactory, callable $usageReporter = null)
    {
        $this->storageFactory = $storageFactory;
        parent::__construct($requestStack, $storageFactory, callable $usageReporter))
    }
```

So you define which service you require and so you don't have some hidden protected dependencies from a parent class. Think this is very common that services are always private and not protected.

**Comment by derrabus** [comment]
> On 5.4 branch, I think the properties of `Symfony\Component\HttpFoundation\Session\SessionFactory` class should be set to `protected` in order to write our own `SessionFactory` class by extending it and without re-writing everything.

The class we're talking about has 40 LoC and only a single method. You don't gain anything by extending it, just provide your own implementation of `SessionFactoryInterface`.
