### ISSUE TITLE
Hard wired FieldVote in Twig extension isGranted

### ISSUE THREAD

**Issue by amigian74** [symfony/symfony#44689]
### Symfony version(s) affected

5.4.0

### Description

I wanted to create a complex authorization system using voters for my symfony project. This system is is similar to ACL but I dind'nt want to use the acl package. Unfortunately the SecurityExtension for twig needs the FieldVote class (which is only available in the acl package). In my opinion this is not a very good design decision, because of many reasons, Why ist this hardwired and not reswolved using the voter chain?

### How to reproduce

Just use the isGranted extension with a field.

### Possible Solution

Remove the FieldVote in the SecurityExtension and solve this with a special voter registered with the acl package.

**Comment by xabbuh** [comment]
Can you explain what concrete issue you experience? The `FieldVote` class should only be used when you pass more than two arguments to the `is_granted()` function in your Twig templates which shouldn't be necessary when you do not want to leverage ACLs.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
