### ISSUE TITLE
[FrameworkBundle] validator.auto_mapping always applies something

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#44693]
### Symfony version(s) affected

4.4.31

### Description

I have `framework.validation.auto_mapping` set to an empty array (default), yet `AddAutoMappingConfigurationPass` always reaches. 

`doctrine.orm.default_entity_manager.validator_loader` is the first ID found, which seems to explain why a random UniqueEnitty validation is triggering on our side. Which is the bug im bumping into :)

### How to reproduce

unqiqe contraint on the entity without auto_mapping, then validate it (using sf/form in our case).

**Comment by nicolas-grekas** [comment]
Can you please have a look at why and submit a fix?
