### ISSUE TITLE
[Profiler] HTML email preview ko

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#44696]
### Symfony version(s) affected

6.0.1

### Description

Hi,

I am playing with Symfony 6 + PHP 8 on the Symfony Demo app, and wanted to test
https://symfony.com/blog/new-in-symfony-5-4-profiler-improvements#html-email-preview
(https://github.com/symfony/symfony/pull/43751)

I got this: 
<img width="1295" alt="Capture d’écran 2021-12-17 à 19 16 35" src="https://user-images.githubusercontent.com/1358361/146590126-b79ae131-9a69-4c16-ade0-04c7980645ad.png">

### How to reproduce

1. Pull and boot https://github.com/symfony/demo app
2. Log in, go to a public blog post page at the bottom, and comment
3. See in the profiler > E-mails tab > HTML preview

### Possible Solution

.

### Additional Context

.

**Comment by Art4** [comment]
This seems to be caused by #44703.

**Comment by 94noni** [comment]
@Art4 hum unsure as my $html is filled [here](https://github.com/symfony/demo/blob/ba7109e4a7023c1080d20a67051e9bbd950f7d96/src/EventSubscriber/CommentNotificationSubscriber.php#L64)

for your error, maybe an `{% if message.htmlBody is not null %}` condition should be added around the `HTML Preview`

**Comment by Art4** [comment]
> @Art4 hum unsure as my $html is filled [here](https://github.com/symfony/demo/blob/ba7109e4a7023c1080d20a67051e9bbd950f7d96/src/EventSubscriber/CommentNotificationSubscriber.php#L64)
> 
> for your error, maybe an `{% if message.htmlBody is not null %}` condition should be added around the `HTML Preview`

@94noni you are right, the demo app uses a HTML email, #44703 is about raw text.

**Comment by 94noni** [comment]
friendly ping @lyrixx could you have a look at the related PR if it is ok? thank you :)
