### ISSUE TITLE
Symfony\Component\Finder\Finder::getIterator return type annotation removed

### ISSUE THREAD

**Issue by kubawerlos** [symfony/symfony#44697]
### Symfony version(s) affected

6.0.0

### Description

During one of the [Merge branch '5.4' into 6.0](https://github.com/symfony/symfony/commit/3cdca3da7cef1b1cdff368c86150d23c78aea7e2#diff-2bc950b86f14d810335e527fea65a68f1f718f6038ef1ce44febc1a59aa9d905L604) the PHPDoc return annotation (`@return \Iterator<SplFileInfo>`) got removed from `Symfony\Component\Finder\Finder::getIterator` method.

It results with static analysis tools such as [Psalm](https://github.com/vimeo/psalm) falsely reporting issue:
```
ERROR: MixedAssignment - [path] - Unable to determine the type that $fileInfo is being assigned to (see https://psalm.dev/032)
        foreach ($finder as $fileInfo) {
```
(where `$finder` is obviously instance of `Symfony\Component\Finder\Finder`)

### How to reproduce

Run Psalm with totally typed mode on code iterating on `Finder`'s object.

Or, take a look here: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/714/commits
- 1st commit simply adds `symfony/finder:5.4.0` for Git to track - nothing special, CI still green
- 2nd commit is upgrading to `symfony/finder:6.0.0` (it's removing constraint in `composer.json`, see `composer.lock` to confirm), where PHPDoc return annotation for `getIterator` method is gone - CI is failing with Psalm's analysis
- 3rd commit is adding only that annotation back to prove it is the reason of failing CI

### Possible Solution

- restore removed annotation
- `Finder` class has in PHPDoc `@implements \IteratorAggregate<string, SplFileInfo>`, so maybe Psalm is to update, not PHPdoc for `getIterator` (although for me it looks like the annotation was removed unintentionally)

### Additional Context

@derrabus do you remember it removing that annotation was intentional?

**Comment by derrabus** [comment]
The annotation was removed because I believed it to be redundant after the native return types had been added. The `@implements` should be enough imho, but apparently Psalm thinks otherwise. PR welcome to restore the return types to `getIterator()` and friends where necessary.

**Comment by nicolas-grekas** [comment]
It'd be great to know if psalm is buggy or not before adding the annotation.

**Comment by derrabus** [comment]
Let's find out: vimeo/psalm#7187

**Comment by derrabus** [comment]
Apparently, the problem is that we used a covariant return type here. The return type enforced by PHP is `Traversable`, but we narrowed that down to `Iterator`. Both, Psalm and PHPStan are confused by that and need the annotated return type. I'd be in favor of adding back the annotations.

Related: phpstan/phpstan#6217

**Comment by nicolas-grekas** [comment]
@kubawerlos can you please send a PR, branch 5.4?

**Comment by kubawerlos** [comment]
@nicolas-grekas it's missing only o 6.0 branch, it's present in 5.4: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Finder/Finder.php#L606

**Comment by derrabus** [comment]
6.0 is the correct target.
