### ISSUE TITLE
[VarExporter] export to primitive array

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#44724]
### Description

I have this quirky piece of PHP code running in prod, to serialize any arbitrary PHP value, for logging purposes.

```
    /**
     * @param mixed $value
     *
     * @return mixed
     */
    protected static function serialize($value)
    {
        $stripInternalKeys = false;
        if ($value instanceof \Traversable) {
            $value = iterator_to_array($value);
        }

        if (is_object($value)) {
            $stripInternalKeys = true;
            $value = (array) $value;
        }

        if (is_array($value)) {
            $result = [];
            foreach ($value as $k => $v) {
                if ($stripInternalKeys && false !== $pos = strrpos($k, "\0")) {
                    $k = substr($k, $pos + 1);
                }

                $result[$k] = self::serialize($v);
            }

            $value = $result;
        }

        return $value;
    }
```

I'd like to replace this with something like `VarExporter::toPrimitive($value)` (naming TBD).

WDYT?

**Comment by nicolas-grekas** [comment]
This looks like a very custom type of serialization. It also looks a lot like json-encode. I'm not sure this makes sense in VarExporter. Maybe in monolog since this is for logs? Or as a custom processor of your own I guess...

**Comment by ro0NL** [comment]
please help :crying_cat_face: https://3v4l.org/gdPWl#v8.1.1

**Comment by ro0NL** [comment]
The goal is we'd know how to reconstruct a class its properties.

**Comment by stof** [comment]
@ro0NL reconstructing a class with its properties is quite complex to handle all cases, which is why both `var_export` and the VarExporter component are generating PHP code doing that, not an associative array.

**Comment by ro0NL** [comment]
Understood, i mean we humans could infer the context further from say typed properties.

I understand this is maybe out of scope, unless we consider it a certain export format. But seeing VarExporter actually obtain the values of interest made me think it could be shared logic perhaps.

**Comment by stof** [comment]
@ro0NL I would say that what you are looking for is rather the normalizer part of symfony/serializer

**Comment by ro0NL** [comment]
@stof you are absolutely right. My goal was to not rely on global state, config et al, but never realised i could leverage ObjectNormalizer actually :100: 

```php
$s = new Serializer([$n = new ObjectNormalizer()]);
$n->setSerializer($s);
```

Works :rocket:
