### ISSUE TITLE
[Cache] Psr16Cache not compatible with psr/simple-cache 3.0 in older Symfony versions

### ISSUE THREAD

**Issue by colinodell** [symfony/symfony#44738]
### Symfony version(s) affected

<6.0.0

### Description

On older, supported versions of Symfony (4.4, 5.3, and 5.4) the `Psr16Cache` class is not compatible with `psr/simple-cache:3.0.0`. Trying to use those versions together results in this error:

> PHP Fatal error:  Declaration of Symfony\Component\Cache\Psr16Cache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed

Users must either upgrade to Symfony 6.0 or downgrade `psr/simple-cache` to 1.x or 2.x.

Composer does not currently prevent users from installing these conflicting versions.  This causes application errors for users who aren't fixing transitive dependencies like `psr/simple-cache` to a specific version and use tools like `composer update` or Dependabot to upgrade those transitive dependencies.

### How to reproduce

Create a `composer.json` file like this:

```json
{
    "require": {
        "psr/simple-cache": "^3.0",
        "symfony/cache": "5.4.*"
    }
}
```

And then try running this simple PHP script:

```php
<?php

use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Symfony\Component\Cache\Psr16Cache;

require_once 'vendor/autoload.php';

$cache = new Psr16Cache(new ArrayAdapter());
```

The issue also occurs with `symfony/cache` constraints of `5.3.*` and `4.4.*`.

### Possible Solution

I see two possible solutions:

1. Add `psr/simple-cache` as a non-dev dependency containing the supported version ranges; or
2. Add `psr/simple-cache` to the `conflict` section for versions >=3.0.0

Either approach would ensure that users aren't able to install incompatible versions.

**Comment by nicolas-grekas** [comment]
Or leave as is...
Adding a conflict won't work because older versions don't have it and composer will install then instead. And moving to require is no go since this is an optional dep.
Leaving as is is fine IMHO. Throwing an explanatory exception would be better. Maybe with a condition before the class declaration?

**Comment by colinodell** [comment]
> Adding a conflict won't work because older versions don't have it and composer will install then instead.

This is certainly true in many cases, but thankfully not in mine.  Let me provide some more context here (I probably should have done that originally - my apologies!)

My company maintains an internal package (that provides custom `CachePoolInterface` implementations) used by other internal projects.  Our cache package uses these requirements:

```json5
"require": {
    // ...
    "symfony/cache": "^4.4 || ^5.0",
    "psr/simple-cache": "^1.0 || ^2.0", 
    // ...
}
```

We would like to allow `psr/simple-cache` 3.0 and `symfony/cache` 6.0:

```json5
"require": {
    // ...
    "symfony/cache": "^4.4 || ^5.0 || ^6.0",
    "psr/simple-cache": "^1.0 || ^2.0 || ^3.0", 
    // ...
}
```

Unfortunately, we can't do this today, because users sticking on `^4.4` or `^5.0` (due to constraints in their projects) may get the incompatible `^3.0` version installed due to this compatibility issue.

But if a `conflict` were added we could safely set our requirements to something like this:

```json5
"require": {
    // ...
    "symfony/cache": "^6.1.xx || ~6.0.xx || ^5.4.xx || ~5.3.xx || ~4.4.xx",
    "psr/simple-cache": "^1.0 || ^2.0 || ^3.0", 
    // ...
}
```

Where `xx` is a patch version containing that new `conflict`. This would ensure our users never get conflicting versions.

There are two other possibilities:

1. **We add the `conflict` on our end.** This is probably what we'd do if Symfony's composer.json is not updated. But if other people might also benefit from this, then why not place that directive in Symfony's instead?
2. **Only allow symfony/cache ^6.0 in our library.** Though this would avoid the issue, it's not viable for us since we still need to support Symfony LTS versions and we unfortunately don't have the bandwidth to maintain multiple version branches at once.

So in this particular case, while defining the `conflict` may not help everyone, I do think it would help people who are currently locked on `"psr/simple-cache": "^1.0 || ^2.0"` due to other dependencies in their projects who may get bitten by this bug later.

> And moving to require is no go since this is an optional dep.

Gotcha, that's fair, and I do think that `conflict` would be more appropriate for an optional dep.

> Leaving as is is fine IMHO. Throwing an explanatory exception would be better. Maybe with a condition before the class declaration?

As much as I do feel that `conflict` would be a better solution, an explanatory exception would certainly help other users who encounter this issue in the future.  I'd still end up adding my own `conflict` to my library anyway, though 😛

**Comment by colinodell** [comment]
Sorry for the wall of text above :P To summarize:

> Adding a conflict won't work because older versions don't have it and composer will install then instead.
> ...
> Throwing an explanatory exception would be better. Maybe with a condition before the class declaration?

I think both have the same downside where the user must upgrade to a newer version of `symfony/cache` to get the "fix". So to me, the question is whether it's better to prevent the **installation** of conflicting versions or prevent their **execution**. The former approach seems more "pure", but I can also see how developers may not realize the need to downgrade `psr/simple-cache`; they might not even notice how/why they aren't getting newer versions of `symfony/cache`. A friendly exception would avoid that problem.

So upon further reflection, I'm fine with the exception approach, since I can always add my own `conflict` with older versions of `symfony/cache` (lacking the new explanatory exception) if I really need to.

**Comment by nicolas-grekas** [comment]
Ok, let's give it a try :) can you please send a PR?

**Comment by stof** [comment]
Well, if they want to understand why they don't get a newer version of `symfony/cache` after adding the conflict rule, `composer why-not` is here precisely to give the explanation.

And once the conflict is there, composer will have 2 equally valid solutions at first (depending on which package gets its latest version selected), and that gets forced by changing your requirement: if you require `symfony/cache ^4.4.37` (assuming that `4.4.37` has the conflict rule), composer will be forced to choose the solution downgrading `psr/simple-cache` (until you upgrade to a version of `symfony/cache` supporting newer versions).

So I would still be in favor of letting the solver know about the issue instead of forcing the dev to resolve conflicts manually.

**Comment by colinodell** [comment]
I think that approach is completely reasonable and is still my top preference.

But here's a different perspective to consider: what if somebody is using both `symfony/cache <6.0.0` and `psr/simple-cache ^3.0`, but **not** Symfony's `Psr16Cache` class? They wouldn't be affected by this compatibility issue, but if we add a `conflict` they'd be forced to downgrade `psr/simple-cache`, which might cause further dependency headaches for them.  Is that a reasonable thing to do, especially for LTS versions?  Maybe this is okay, maybe it's not.

I'm happy to submit a PR either way, I'd just like to know which implementation to submit 🙃

**Comment by nicolas-grekas** [comment]
Friendly ping @colinodell

**Comment by colinodell** [comment]
Thanks for the reminder! An explanatory exception has been added via PR #45096.
