### ISSUE TITLE
[BrowserKit][DOMCrawler] Crawler's html() method does not return HTML with the original <html> tag

### ISSUE THREAD

**Issue by Fabrn** [symfony/symfony#44744]
### Symfony version(s) affected

5.4.0

### Description

Having an original HTML containing an ```html``` tag wrapping the rest of the HTML will result in an HTML without this ```html``` tag after going through the ```Crawler``` service, particularly the ```html``` method

### 1/ Get a simple HTML
```html
<html lang="fr">
    <head></head>
    <body></body>
</html>
```

### 2/ Feed the Crawler with the HTML
```php
$crawler = new Crawler();
$crawler->addContent($html);
```

### 3/ Get back the HTML through the ```Crawler::html``` method
```php
$html = $crawler->html();
dd($html);
```

Will result in : 
```html
<head></head>
<body></body>
```

### Possible Solution

This bug (if it is one) is clearly caused by the fact that the ```Crawler::html``` method iterates through the original node's children.

```php
// Line 673 to 676 in Crawler.php
$html = '';

foreach ($node->childNodes as $child) {
    $html .= $owner->saveHTML($child);
 }
```

**Comment by dmaicher** [comment]
I guess `Crawler::outerHtml()` is what you are looking for?

**Comment by stof** [comment]
indeed. The `html()` method is the equivalent of `.innerHTML` in JS.

**Comment by Fabrn** [comment]
Alright ! My bad about that didn't check it properly, wrote the ticket way too fast, sorry !

Thank you guys for fast answers
