### ISSUE TITLE
UniqueEntity message with html tag is not rendering

### ISSUE THREAD

**Issue by wnunezc** [symfony/symfony#44755]
### Symfony version(s) affected

5.4.0 i dont know if other have the same problem that me

### Description

hello guys i have implement UniqueEntity Constraints and Constraints Assert; in my code it look like this:

```php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(indexes={@ORM\Index(name="user",columns={"id","credential","nickname","email","status"})})
 * @UniqueEntity(
 *     fields={"email"},
 *     message="este Correo ya esta en Uso; Dirigete a la Activacion de Cuentas! <a href='/account_activation'>Activate</a>"
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     * @Assert\NotBlank(
     *     message = "Email cannot be empty"
     * )
     */
    private $email;

```

the main idea is that email be unique; if it already exist show and error and the error must show a link to Activate the Account in `/account_activation` route

this is that i have in my template:

```twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_errors(registration_form) }}
    {{ form(registration_form) }}
{% endblock %}

```

and i have try use raw filter:

```twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_errors(registration_form)|raw }}
    {{ form(registration_form) }}
{% endblock %}
```
but my output is not rendering the anchor (link) tag:

![image](https://user-images.githubusercontent.com/1207306/146976585-132307a0-d8a1-43f4-8799-f15ded3377bb.png)

I don't know what is wrong; I've been looking for 3 days to solve this error.

Render HTML:

![image](https://user-images.githubusercontent.com/1207306/146979714-0c23e9c0-4b3f-4ba1-a373-ac2fd1d4b738.png)

### How to reproduce

I don't know how to reproduce this problem on another pc; I have not tried; The only thing I have done is the synfony installation in version 5.4.0 and the packages are the following:

![image](https://user-images.githubusercontent.com/1207306/146977007-592ff6d6-5c35-43d8-94b9-7fb15d005823.png)

**Comment by acantepie** [comment]
I think its not a bug, text displayed (errors, labels, ...) is always escaped on symfony form theme, you can define your own form theme to avoid this behaviour : 
```twig
{% extends 'base.html.twig' %}

{% form_theme registration_form _self %}
{% block form_errors %}
    {%- for error in errors -%}
        {{ error.message | raw }}
    {%- endfor -%}
{% endblock %}

{% block body %}
    {{ form_errors(registration_form) }}
    {{ form(registration_form) }}
{% endblock %}
```

**Comment by wnunezc** [comment]
@acantepie thanks for your help, and yes, I need to implement a custom bug reader and something that exposes them ... actually here is something like that very complex for something that should be simple ...

**Comment by stof** [comment]
Well, not escaping validation error in the form theme would be a security risk as it would allow XSS. Applying HTML escaping in the validator mapping when defining annotations does not make sense (validation errors might be used for something else than HTML, for instance a JSON API response) and would be bad for DX.

**Comment by xabbuh** [comment]
closing here for the reasons explained by @stof
