### ISSUE TITLE
Constraints on the properties of an entity are not respected when used as an entry type in a collectionfield

### ISSUE THREAD

**Issue by sxsws** [symfony/symfony#44750]
### Symfony version(s) affected

6.0.1

### Description

When creating a form for an entity, validation occurs when the form is submitted according to any validation constraints on properties defined in the entity.

when using an entity as an entry_type in a collection field, any constraint attributes / annotations placed on the properties are ignored when submitting the parent form

### How to reproduce

- Have doctrine-managed entity with constraints placed as attributes or annotations on properties
- use a form with data_class to that entity, and use as the entry type for a CollectionField in another form
- enter invalid data in the sub forms, and submit the form
- none of the constraints (such as greater than 0, notblank, not null) are respected

**Comment by Matth--** [comment]
Hi @sxsws 

Have you tried using the [Valid](https://symfony.com/doc/current/reference/constraints/Valid.html) constraint?

If you want to validate entries in a CollectionField, you can enable validation for each of those subforms with the Valid constraint.

**Comment by sxsws** [comment]
@Matth-- yes, thanks. It's a gotcha that I didn't realise. I think it should be added to the collectiontype docs!

**Comment by stof** [comment]
Well, CollectionType is about documenting the form type, not the behavior of the validator component. And this behavior is not specific to CollectionType. The need for the `Valid` constraint exist anytimes you want to validate nested objects in your object graph

**Comment by sxsws** [comment]
> The need for the Valid constraint exist anytimes you want to validate nested objects in your object graph

Which would make the CollectionType the perfect place to document that as an aside, a note.
