### ISSUE TITLE
[RFC][Console] Making $defaultName of Symfony\Component\Console\Command public

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#44757]
### Description

Will it have any adverse impact if ``protected static $defaultName;`` were to be changed to ``public static $defaultName;`` in ``Symfony\Component\Console\Command``?

That will give one access to the name via ``AcmeCommand::$defaultName`` without overwriting the property visibility in ``AcmeCommand`` and giving ingrown toenails to PHPStorm inspections and PHPStan.

If one can do that, then in ``AcmeCommandTest`` you can have: ``Application::find(AcmeCommand::$defaultName);``.

**Comment by derrabus** [comment]
A clear no from my side. I'd rather sunset that property completely. But exposing that property in userland with a public method would be trivial.

**Comment by wouterj** [comment]
A slightly unrelated note: I recommend hardcoding the command name in at least one test. If they all dynamically rely on the name in the property, you will not catch errors when someone accidentally changes the name.
