### ISSUE TITLE
Why `InputBag` in parameters shouldn't support array as value?

### ISSUE THREAD

**Issue by atlance** [symfony/symfony#44788]
### Description

Definition:
> InputBag is a container for user input values such as $_GET, $_POST, $_REQUEST, and $_COOKIE.

For api (via json), value-array in parameter is simple case ... why override parent `get` in InputBag?
Array of `ids` in `$_POST`\ `$_GET` is this a problem?
Or what to do in this case?

**Comment by wouterj** [comment]
See https://github.com/symfony/symfony/pull/34363 for an explanation. Allowing scalar and non-scalar return values leads to 500's (unless you explicitly check the return type every time you fetch a value from the bag). The input values (get, post, request, cookie) only support scalar values in the HTTP spec if I recall correctly.

Other related issues about this topic: https://github.com/symfony/symfony/pull/41766 https://github.com/symfony/symfony/pull/40315 https://github.com/symfony/symfony/pull/37265 https://github.com/symfony/symfony/issues/37100

I've opened https://github.com/symfony/symfony/pull/44789 as I believe we missed something in this long list of issues/PRs. Other than that, I feel like there is little to do here. If you have any more questions on how to use Request with JSON bodies, please use one of the support channels (e.g. Slack or GitHub Discussions): https://symfony.com/support

**Comment by GregOriol** [comment]
@wouterj There is an incoherence with the fact that `$inputbag->all()` provides the array
```
array(1) {
  ["someparam"]=>
  array(4) {
    [0]=>
    string(1) "a"
    [1]=>
    string(1) "b"
    [2]=>
    string(1) "c"
  }
}
```
while `$inputbag->get('someparam')` throws `BadRequestException` when passing `?someparam[]=a&someparam[]=b&someparam[]=c`
