### ISSUE TITLE
[mailer] urlencode() on the password results in "You have requested a non-existent parameter"

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#44817]
### Symfony version(s) affected

5.3.12

### Description

https://symfony.com/doc/current/mailer.html#transport-setup

You suggest to use urlencode on the password. However doing this makes the application crash if a password contains at least 2 special characters, in any position. 

Not encoding is not a solution because it will not work if the user contains a @, for example `user@domain.com`, `domain.com` will be interpreted as the mailer host.

### How to reproduce

Replicating this issue is easy, just add in messenger.yaml the following:

    async: 'smtp://user:%23abc%23de@host:465'

The password is the result of urlencode('#abc#de').

This error will be returned:

    You have requested a non-existent parameter "23abc".

### Possible Solution

IMHO more ways to provide authentication credentials should be provided.

Now hardcoding the DSN in the .env is the only available way, which is often not suitable (for example one may want to store the credentials in the database, to allow the admin to set them in their control panel, so more flexibility would be useful, like the possibility to use a Service to retrieve them)

**Comment by fmonts** [comment]
Maybe this is a non-issue, to fix it you need to escape the percent with another percent, so in case you need an advanced configuration with ContainerConfigurator (only way I found to set the DSN dynamically) it will be:

    $containerConfigurator->extension('framework', [
        'mailer' => [
            'dsn' => 'smtp://' . $username . ':' . str_replace('%', '%%', urlencode($password)) . '@' . $host . ':' . $port
        ],
    ]);

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by miljanbrakocevic** [comment]
hello, this one appears not to be fixed yet ? I have same issue when using aws ses, with password having special chars that we need to encode like "/" contained in pass, after encoding it error appears "You have requested a non-existent parameter : "20BLsx"

**Comment by stof** [comment]
@miljanbrakocevic see the comment of @xabbuh before closing: it was closed due to lack of feedback when requesting more details.
If you are affected, please open a new issue, making sure to provide the info.

**Comment by fmonts** [comment]
I don't think I can provide much more feedback, this is how configurations are parsed by design, if a string contains two percent sign ('%') what's between them it's interpreted as a parameter. You need to escape the percent with another percent, as I wrote above

**Comment by DavidPetrasek** [comment]
Also had the same problem. Escaping % didn't work. Also tried removing `resolve:` in the config. Alternative solution was to use a longer password withouth special characters.
