### ISSUE TITLE
[Notifier] [expo-notifier] Wrong service tag applied via framework bundle to ExpoTransportFactory

### ISSUE THREAD

**Issue by ahoendgen** [symfony/symfony#44833]
### Symfony version(s) affected

6.0.0

### Description

The expo-notifier transport factory is tagged with `chatter.transport_factory` but must be tagged with `texter.transport_factory` to work properly.

https://github.com/symfony/symfony/blob/60ce5a3dfbd90fad60cd39fcb3d7bf7888a48659/src/Symfony/Bundle/FrameworkBundle/Resources/config/notifier_transports.php#L243

### How to reproduce

- install only expo-notifier bundle
- configure it via .env
- try to send a message via autowired TexterInterface
- see exception because NullTransportFactory won't pickup the expo schema

### Possible Solution

change `chatter.transport_factory` to `texter.transport_factory` in https://github.com/symfony/symfony/blob/60ce5a3dfbd90fad60cd39fcb3d7bf7888a48659/src/Symfony/Bundle/FrameworkBundle/Resources/config/notifier_transports.php#L243

**Comment by OskarStark** [comment]
It looks like you are right

![image](https://user-images.githubusercontent.com/995707/148166564-43b41ec9-7281-4e85-86ed-c0ad0ec036e5.png)

Open for a bugfix PR?

Thanks
