### ISSUE TITLE
[Validator]BC break between 5.3.10 and 5.3.11 with custom Constraint and constructor promotion

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#44846]
### Symfony version(s) affected

5.3.11

### Description

```php
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

#[\Attribute(\Attribute::TARGET_CLASS)]
class Foobar extends Constraint
{
    public function __construct(
        public bool $something,
    ) {
    }

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }
}
```

* With SF 5.3.10, the following code works property
* With SF 5.3.11, it fails
  *  error:
  ``` >…home/gregoire/dev/tmp/custom-validator(master) php reproducer.php 
  TypeError {#83
    #message: "in_array(): Argument #2 ($haystack) must be of type array, null given"
    #code: 0
    #file: "./vendor/symfony/validator/Constraint.php"
    #line: 238
    trace: {
      ./vendor/symfony/validator/Constraint.php:238 { …}
      ./vendor/symfony/validator/Mapping/ClassMetadata.php:222 { …}
      ./vendor/symfony/validator/Mapping/Loader/AnnotationLoader.php:52 { …}
      ./vendor/symfony/validator/Mapping/Loader/LoaderChain.php:54 { …}
      ./vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php:101 { …}
      ./vendor/symfony/validator/Validator/RecursiveContextualValidator.php:306 { …}
      ./vendor/symfony/validator/Validator/RecursiveContextualValidator.php:138 { …}
      ./vendor/symfony/validator/Validator/RecursiveValidator.php:93 { …}
      ./vendor/symfony/validator/Validator/TraceableValidator.php:66 { …}
      ./reproducer.php:18 {
        › $v = $k->getContainer()->get('validator');
        › $error = $v->validate(new Dto());
        › 
      }
    }
  }
  ```
  * to make it work, I have to call the parent constructor

### How to reproduce

I made a full reproducer here: https://github.com/lyrixx/test/commits/custom-validator

**Comment by lyrixx** [comment]
It's broken because of https://github.com/symfony/symfony/commit/aa4fb0c2c4c3a5ef135ea671c7c6cd03ece56d9e#diff-eadef5e494fbfb85346e70992f4b18994df0b999b7d336c9cece5ab9e9a4a18aR64

I'll submit a PR

**Comment by nicolas-grekas** [comment]
You must call the parent constructor, or at least `unset($this->groups)`

**Comment by stof** [comment]
your constraint won't allow configuring its groups as you don't call the parent constructor...

**Comment by lyrixx** [comment]
@stof indeed, but I don't need it :)

**Comment by nicolas-grekas** [comment]
You don't need it, but this is still incorrect. Only your present self knows that you don't need. In the future, you/someone else might need it but will have a hard time figuring out why groups don't work. I think we shouldn't support this use case. I propose #44854 to throw a LogicException when this happens (it's not like calling the parent constructor is a big deal, and this is detected at compile-time most of the time).

**Comment by lyrixx** [comment]
wep
