### ISSUE TITLE
unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by Sawaya-ui** [symfony/symfony#44883]
### Symfony version(s) affected

^4.8

### Description

Good day / evening I have just published my website and wanted to test everything for its functionality and when I want to log into my login system I got the following error message...
Parse error: syntax error, unexpected 'static' (T_STATIC) in /home/www/satowa-network.at/vendor/symfony/options-resolver/OptionsResolver.php on line 194

Can I please who quickly help....

### How to reproduce

I dont know how you could reproduce that I never changed anything or so it was from the one day to the other day there

**Comment by GromNaN** [comment]
It looks like you are using Symfony 6.0 (which requires PHP 8.0+) with an older PHP version. You should downgrade to Symfony 5.4 or upgrade PHP on your server.

The return `static` type was added in Symfony 6.0, and is not in the previous version.
https://github.com/symfony/symfony/blob/46dd8818ce5bd848d23bed4fba520547b7f6f911/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L194

**Comment by SagarNaliyapara** [comment]
I had outdated global composer and running following command fix the issue,

```composer global update```

**Comment by HorselessName** [comment]
> It looks like you are using Symfony 6.0 (which requires PHP 8.0+) with an older PHP version. You should downgrade to Symfony 5.4 or upgrade PHP on your server.
> 
> The return `static` type was added in Symfony 6.0, and is not in the previous version.
> 
> https://github.com/symfony/symfony/blob/46dd8818ce5bd848d23bed4fba520547b7f6f911/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L194

Hello. How can i downgrade to Symfony 5.4?

**Comment by derrabus** [comment]
Please use GitHub discussions for support questions, thank you.

https://github.com/symfony/symfony/discussions
