### ISSUE TITLE
[VarExporter] Support for Closure

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#44889]
### Description

Currently, I have a configuration of an API that is done by a simple callback that is called in twig with ID of the current entity. And I have not found another way to do it.  This is cached with `VarExporter:export()`, and I get the following error:

`Type "Closure" is not instantiable.`

### Example

```
$closure = function (string $bar) {
	return  $bar;
}

VarExporter:export($closure);
```

**Comment by derrabus** [comment]
What would you expect to happen if you export a closure?

**Comment by chiqui3d** [comment]
The same closure, in order to be able to use it. I am using the cache system based on resources https://symfony.com/doc/current/components/config/caching.html

**Comment by chiqui3d** [comment]
This library supports it https://github.com/brick/varexporter

**Comment by derrabus** [comment]
Exporting a closure is really not trivial. A closure is an executable piece of code that might have dependencies. There is no runtime API that allows us to reconstruct a closure in a portable way. A closure is simply not meant to be exported.

The library you mention uses a userland PHP parser to scrape the PHP code behind a closure. This is a pretty complex thing to do and the resulting code won't be easy to maintain.

Can you elaborate why…

* … you need to export closures?
* … you cannot use that library you mentioned if it works for you?

**Comment by chiqui3d** [comment]
I didn't know it was so complicated, the truth is strange for me that PHP doesn't like `closures `or doesn't know how to export internal PHP stuff, the same with `serialize`, it doesn't support Closure either, in Javascript I use Closure constantly, it seems that PHP doesn't like it.

But I'll come to the point.:

I am building a `LayoutBundle` that has configuration based class. These classes have a `LayoutBuildInterface`, there can be 20 classes. And I want to use the cache to save requests, obviously. It took me a lot of learning, but I have managed to apply the cache system based on resources and using the library I mentioned before (I can continue using it). But my example of why I need this is because of the following:
```
public function build(LayoutBuildInterface $layoutBuild): LayoutBuildInterface
    {

        return $layoutBuild
           ->setSingularTitle('Bloque')
           ->setPluralTitle('Bloques')
           ->setButtons([
                Button::add('Export button', 'far fa-export', function (Ads $entity) {
                    return '/admin/ads/'.$entity->getId().'/export';
                }),
            ]);
}
```
This call is made in Twig by passing the current entity.

I could remove the `Closure`, but it would leave the user using the Bundle quite short to add buttons. And of course the cache I want to use.

**Comment by chiqui3d** [comment]
As I said before, I can also try to remove the Closure, although it can be complicated. 

Also, I have made the Closure request here, even though I use the previous library, because Symfony has a module for that specifically and I have seen that it does not work.

**Comment by derrabus** [comment]
> in Javascript I use Closure constantly, it seems that PHP doesn't like it.

You cannot export or serialize arbitrary closures in JavaScript either, for very much the same reasons. And I would really recommend to not use closures in datastructures that you to serialize in some form.

> Also, I have made the Closure request here, even though I use the previous library, because Symfony has a module for that specifically and I have seen that it does not work.

If that other library works for you, just use it.

I'm closing this issue because I don't think we want to implement this feature.
