### ISSUE TITLE
[Process] CHANGELOG.md out-of-date

### ISSUE THREAD

**Issue by insign** [symfony/symfony#44885]
### Description

There is no clue about changes from 5 to 6 on https://github.com/symfony/process/blob/v6.0.2/CHANGELOG.md

**Comment by derrabus** [comment]
That's because there are no relevant changes in 6.0.

**Comment by insign** [comment]
At least inform that in the changelog.

BTW, why a jump from 5.4 to 6 if there is no relevant changes?

**Comment by derrabus** [comment]
> BTW, why a jump from 5.4 to 6 if there is no relevant changes?

Because we keep the version numbers of all components in sync.
