### ISSUE TITLE
AbstractLoginFormAuthenticator::supports() always returns false if application lives under a directory

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#44893]
### Discussed in https://github.com/symfony/symfony/discussions/44329

<div type='discussions-op-text'>

<sup>Originally posted by **php4fan** November 28, 2021</sup>
### Symfony version(s) affected

5.4.0

### Description

Say you have an application deployed to `https://somedomain.com/my/path`, as opposed to just `https://somedomain.com/`.
I think you usually call that an application that "lives under a subdirectory" (or directory, or folder).

I expect EVERYTHING in the framework to work out of the box with ZERO configuration in that scenario. Generally, Symfony does know how to handle that.

Out-of-the-box login authentication however seems to be one of those things that do not work as expected in the under-a-directory scenario.

I think that's due to the `AbstractLoginFormAuthenticator::supports()` method whose current implementation is:
```
    return $request->isMethod('POST') && $this->getLoginUrl($request) === $request->getPathInfo();
```

In this scenario, `$this->getLoginUrl($request)` returns `/my/path/login`, while `$request->getPathInfo()` returns just `/login` when the url being requested is `/my/path/info`.

### How to reproduce

Deploy a Symfony application under a directory. 
Make a `LoginFormAuthenticator` with `make:auth`
Try to log in.

### Additional Context

_No response_</div>

**Comment by weaverryan** [comment]
This was originally #44318. I've re-reopened it because, to me, it does indeed look like an issue. It's fairly simple: if you deploy your site to a sub-directory (e.g. `https://example.com/cool-app`), then the `AbstractLoginFormAuthenticator` will always return false:

```php
return $request->isMethod('POST') && $this->getLoginUrl($request) === $request->getPathInfo();
```

> In this scenario, `$this->getLoginUrl($request)` returns `/my/path/login`, while
`$request->getPathInfo()` returns just `/login` when the url being requested is `/my/path/info`.

Let me know if I'm mistaken about this being an issue :).

**Comment by Crell** [comment]
A closely related issue: The same incorrect behavior happens if the site is not using clean URLs, vis, `example.com/index.php/login`.

The root problem seems to be the use of `UrlGenerator` to make the path in `getLoginUrl()` (the default generated version).  The `generate()` method, by design, creates a link to the specified route as a browser would need it.  However, that's not the value you want when comparing against an internal path.  You instead want just the path equivalent of it.

There doesn't see to be any obvious way to get that, other than simply hard coding the login path, rather than login route name.  But that is the fix that would be needed.

**Comment by a-r-m-i-n** [comment]
I can confirm this issue. When Symfony is running in a sub-directory (in my case an apache alias) the `supports()` always returns false, because `/login` does not match with `/sub/login`.

As workaround, I've overwritten the supports method like this:
```
    public function supports(Request $request): bool
    {
        return parent::supports($request) || ($request->isMethod('POST') && $this->getLoginUrl($request) === '/sub' . $request->getPathInfo());
    }
```

That works.

**Comment by weaverryan** [comment]
It would need some testing, but the solution might be a more generic version of what @a-r-m-i-n suggests:

```php
public function supports(Request $request): bool
    {
    return parent::supports($request) || ($request->isMethod('POST') && $this->getLoginUrl($request) === $request->getBaseUrl() . $request->getPathInfo());
}
```

Basically, leverage `$request->getBaseUrl()` to "re-add" any subdirectory or `index.php` prefix before doing the comparison.

**Comment by sgehrig** [comment]
@weaverryan Is there anything new on this issue? If not, I'd try to prepare a PR. We just stumbled upon the same issue and it cost us quite some time until we realised that this one line causes issues.

**Comment by wouterj** [comment]
@sgehrig it would be great if you can submit a PR to 5.4 if you've verified that the code works :)
(and maybe somehow write a test, but I think that will be a tricky one)

**Comment by sgehrig** [comment]
@wouterj Done. See #47317.
