### ISSUE TITLE
[Filesystem] Backport Path class to Symfony 4

### ISSUE THREAD

**Issue by danepowell** [symfony/symfony#44897]
### Description

webmozart/path-util was recently [marked as abandoned](https://packagist.org/packages/webmozart/path-util), and its functionality was ported to the Path class in Symfony 5 in https://github.com/symfony/filesystem/commit/d5ca5f7080a759dcb65300a55d5ee42f1ee7ef59#diff-895ef7083b1680f1d1bac193c8218da6a6ce31e409e6b7b3f952ef9e428d2e02

The problem is that a great many projects (see https://github.com/drush-ops/drush/issues/4935, https://github.com/typhonius/acquia-php-sdk-v2/pull/219) need that Path functionality, and _also_ need to support Symfony 4 as the latest Symfony LTS release. Currently, projects like Drush are stuck between a rock and a hard place, facing the options of dropping support for Symfony 4, copying the Path class into their own project, creating a shim class, continuing to use an abandoned package, or other ugliness.

The easiest solution I think would be to backport the Path class to Symfony 4. Alternatively, maybe someone from the Symfony team could take ownership of webmozart/path-util and maintain it minimally just until Symfony 4 is EOL?

**Comment by derrabus** [comment]
The webmozart package won't suddenly cease to exist, will it? We usually don't backport features to old branches and I'm not convinced we should do so now.

**Comment by chalasr** [comment]
Also note that the package didn't get any bugfix for more than five years https://github.com/webmozart/path-util/commits/master. Copying that class in the dependent projects until Symfony 4 is EOL seems to be the most sensible option to me.

**Comment by danepowell** [comment]
> The webmozart package won't suddenly cease to exist, will it?

It certainly might. That's the nature of abandoned packages.

**Comment by fabpot** [comment]
I agree with @chalasr, the best option is to copy the code. We cannot add any new feature to Symfony 4.
