### ISSUE TITLE
$token->getUser() should return null instead of empty string when there is no user

### ISSUE THREAD

**Issue by jellynoone** [symfony/symfony#44909]
### Symfony version(s) affected

5.4.*

### Description

When using voters and accessing the user through `TokenInterface` and there is no user logged in, the function returns an empty string `''` instead of `null`. Failing a strict comparison test `null === $user`.

### How to reproduce

```php
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\Voter\CacheableVoterInterface;
use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;

class AuthenticationVoter implements CacheableVoterInterface
{
    public function supportsAttribute(string $attribute): bool
    {
        return \in_array($attribute, [
            'IS_AUTHENTICATED_NOT',
        ], true);
    }

    public function supportsType(string $subjectType): bool
    {
        return 'null' === $subjectType;
    }

    public function vote(TokenInterface $token, $subject, array $attributes): int
    {
        \assert(null === $subject);
        $vote = VoterInterface::ACCESS_ABSTAIN;
        $user = $token->getUser();

        foreach ($attributes as $attr) {
            if ($attr !== 'IS_AUTHENTICATED_NOT') continue;

            $vote = VoterInterface::ACCESS_DENIED;

            if (null === $user) return VoterInterface::ACCESS_GRANTED;
        }

        return $vote;
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Security;

class LoginController
{
    #[Route('/sign-in')]
    public function signIn(Request $request, Security $security): Response
    {
        if ($security->isGranted('IS_AUTHENTICATED_NOT')) {
            return new Response('Login');
        }

        return new Response('Only logged out users can login.');
    }
}
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by jellynoone** [comment]
Hi, @xabbuh . I was able to take a look at the source. Putting `\dump($token)` in the function call showed `$token`was of type `\Symfony\Component\Security\Core\Authentication\Token\NullToken`. 

Checking it's implementation I see it returns an empty string instead of `null` for the `getUser` method. Going against the signature in the docblocks. This seems to be the problem. 

Could you confirm? Or do you still need an example?

**Comment by jellynoone** [comment]
OK, never mind. Looking at the v [`6.0` branch this was fixed](https://github.com/symfony/symfony/blob/137aa3ba3c73e823e8259352beaae66d25f13def/src/Symfony/Component/Security/Core/Authentication/Token/NullToken.php#L33).

But [the 5.4 wasn't](https://github.com/symfony/symfony/blob/32c4050114ef07a46113db69bdaddbe7aa5f894a/src/Symfony/Component/Security/Core/Authentication/Token/NullToken.php#L36)?

I thought, 5.4 still receives bug fixes or am I wrong?

**Comment by jellynoone** [comment]
Hi, @xabbuh . Was this enough information?

**Comment by BernardA** [comment]
I used it like so:

       if (!is_object($user = $token->getUser())) {
            return;
        }

**Comment by chalasr** [comment]
See #45697
