### ISSUE TITLE
BC break: Form 4.4 not fully compatible with property access 5.4.0

### ISSUE THREAD

**Issue by yourithielen** [symfony/symfony#44914]
### Symfony version(s) affected

4.4.34

### Description

Despite the claim of `symfony/form` `4.4.34` being compatible with `symfony/property-access` `^5.0.8`, when using `symfony/property-access` `^5.0.8` I get the following error:

**Symfony\Component\Form\Exception\UnexpectedTypeException**

`/var/www/XXX/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:43`

`Expected argument of type "object, array or empty", "string" given`

When I change back to `symfony/property-access` `^4.4.36` everything works fine.

The problem seems to occur in `PropertyPathMapper` where the `data_class` is used to set the data. `$this->getPropertyValue($data, $propertyPath)` on line 51 returns false instead of the actual data.

I don't see any breaking changes for PropertyAcces 4 -> 5: https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#propertyaccess.

The issue might be related to an incorrect usage of the Symfony Form component but at this moment I don't have enough knowledge to find out if this is the case.

### How to reproduce

I will do my best to create a reproducible bug (https://symfony.com/doc/current/contributing/code/reproducer.html) ASAP.

**Comment by derrabus** [comment]
A reproducer would be nice indeed. 🙂

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
