### ISSUE TITLE
Syntax error in service-contracts package

### ISSUE THREAD

**Issue by N3rdP1um23** [symfony/symfony#44924]
### Symfony version(s) affected

service-contracts - 2.5 service tag

### Description

I had an issue with one of my projects where this file was causing [laravel-opcache](https://github.com/appstract/laravel-opcache) to throw a 500 error.

> syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) {"url":"/opcache-api/compile","exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) at vendor/symfony/service-contracts/Attribute/SubscribedService.php:30)

There's no way to create an issue on the service-contracts repo and was directed here to submit a bug report here. I apologize if this isn't the correct way, I've tried to follow the rules the best I can.

### How to reproduce

- Create new Laravel v6 project
  - This will require the symfony/console which then requires the symfony/service-contracts package
- Install the [laravel-opcache](https://github.com/appstract/laravel-opcache) package
- Cache the project using the following artisan command `php artisan opcache:compile --force`

### Possible Solution

Remove "public" from the function definition and the issue goes away.

Will submit a PR with the correction and link it below.

### Additional Context

Stack trace when running the cache artisan command

> syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) {"url":"/opcache-api/compile","exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) at vendor/symfony/service-contracts/Attribute/SubscribedService.php:30)

**Comment by derrabus** [comment]
appstract/laravel-opcache#123
