### ISSUE TITLE
[WebProfilerBundle][TwigBundle] Error when cache:clear for prod on a fresh Symfony project with profiler-pack installed

### ISSUE THREAD

**Issue by apetitpa** [symfony/symfony#44928]
### Symfony version(s) affected

tested on 5.4 and 6.0 but probably all maintained versions

### Description

Hi,

I noticed something weird yesterday while working on a project for a client. I installed the profiler-pack to use the WebProfilerBundle. The profiler-pack is fairly simple and only adds symfony/stop-watch and symfony/web-profiler-bundle to composer.json but then symfony/flex runs two recipes, one for the web-profiler-bundle and one for the twig-bundle which enables this very bundle in `bundles.php` for all environments and that feels odd to me.

`Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],`

Please note that the project doesn't require any twig related dependency in the `composer.json`

As you can imagine then when you want to clear cache for prod environment with no dev dependencies installed, you get the following error :

`Fatal error: Uncaught Error: Class "Symfony\Bundle\TwigBundle\TwigBundle" not found in /var/www/loire/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:132`

### How to reproduce

Create a new Symfony project (tested on 5.4 and 6.0)

`symfony new test`

Require profiler pack

`composer require symfony/profiler-pack`

Try to remove dev dependencies (which runs cache:clear afterward)

`composer install --no-dev`

### Possible Solution

For now the workaround for me is to manually set TwigBundle only for dev and test environment in `bundles.php`

`Symfony\Bundle\TwigBundle\TwigBundle::class => ['dev' => true, 'test' => true],`

Another solution is to require the TwigBundle in your composer.json but that feels wrong too.

I don't really know what could be the best solution for this. Maybe finding a way to enable TwigBundle for dev and test envs in this edge case from the recipe but I wonder if this TwigBundle should really be in the `bundles.php` in the first place.

**Comment by fabpot** [comment]
What you did is indeed the solution.
