### ISSUE TITLE
Deprecation message is produced even with [#\ReturnTypeWillChange]

### ISSUE THREAD

**Issue by jokaorgua** [symfony/symfony#44929]
### Symfony version(s) affected

5.4.2

### Description

If the class implements \Countable interface and method "count" has no return type we have a deprecation notice even with [#\ReturnTypeWillChange] attribute

Implementation example which causes the deprecation message is here https://github.com/aws/aws-sdk-php/blob/master/src/HandlerList.php#L308 (official AWS SDK for PHP)

the deprecation message 

```
Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Aws\HandlerList" now to avoid errors or add an explicit @return annotation to suppress this message.
```

### How to reproduce

1. Use symfony 5.4.2
2. Install aws/aws-sdk-php 3.208.9
3. Run any unittest that will include aws files

You will get

```
Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Aws\HandlerList" now to avoid errors or add an explicit @return annotation to suppress this message.
```

The code can be found here https://github.com/aws/aws-sdk-php/blob/master/src/HandlerList.php#L308

**Comment by nicolas-grekas** [comment]
Adding the attribute is not enough, you should also tell what is the tentative return type going to be. On that method, that means adding `@return int` as annotation.
Same logic for all methods that have the attribute of course.
