### ISSUE TITLE
Run php bin/phpunit

### ISSUE THREAD

**Issue by benblub** [symfony/symfony#44933]
### Symfony version(s) affected

5.4.1

### Description

Since 2022-01-04 evening without any code changes when i run php bin/phpunit it failed in Github actions. I checked the dir where the command is executed and its in root dir where composer.json is listed and phpunit is allready installed. And before it was working.
Error Output
```
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.5-0"
Installing phpunit/phpunit (9.5.11)
Plugins have been disabled.
  - Installing phpunit/phpunit (9.5.11): Extracting archive
Created project in /home/runner/work/XXX/bin/.phpunit/phpunit-9.5-0
```

php bin/phpunit execute the phpunit script provided by symfony. And it installs phpunit in bin folder and not in "vendor".

And with that in an Symfony App where other Symfony Services are running fatal error can happen. Looks like loader cant resolve then correct -> eg uses autoload from that new vendor in bin folder then from vendor.

A fix is running instead `php vendor/bin/phpunit`

Error
```
PHP Fatal error:  Class phpDocumentor\Reflection\PseudoTypes\List_ cannot extend final class phpDocumentor\Reflection\Types\Array_ in /home/runner/work/XXX/bin/.phpunit/phpunit-9.5-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27
..............................Symfony\Component\Config\Exception\LoaderLoadException {#45501
  #message: "Cannot load resource "kernel::loadRoutes". Make sure there is a loader supporting the "service" type."
  #code: 0
  #file: "./vendor/symfony/framework-bundle/Routing/DelegatingLoader.php"
  #line: 65
  -previous: Symfony\Component\ErrorHandler\Error\FatalError {#62469
    #message: "Compile Error: Class phpDocumentor\Reflection\PseudoTypes\List_ cannot extend final class phpDocumentor\Reflection\Types\Array_"
    #code: 0
    #file: "./bin/.phpunit/phpunit-9.5-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php"
    #line: 27
    -error: array:4 [
      "type" => 64
      "message" => "Class phpDocumentor\Reflection\PseudoTypes\List_ cannot extend final class phpDocumentor\Reflection\Types\Array_"
      "file" => "/home/runner/work/XXX/bin/.phpunit/phpunit-9.5-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php"
      "line" => 27
    ]
  }
```

### How to reproduce

Here you can see in in Workflow its installed phpunit in the bin folder.

https://github.com/benblub/workflow-phpunit-bug-reproducer/pull/1

### Possible Solution

A Quickfix is running instead `php vendor/bin/phpunit`

**Comment by LoicBoursin** [comment]
I can confirm the exact same issue, except the proposed fix still gets me this error.

**Comment by derrabus** [comment]
I checkout out your repository, switched to the `test` branch and ran `bin/phpunit`. The test passes without error.

If you still encounter the problem locally, can you try to delete the hidden directory `bin/.phpunit` (mind the dot before `phpunit`) and tell me if that makes your problem go away?

**Comment by khallouki** [comment]
I can confirm that I experience the same issue, except on Bitbucket Pipelines instead of Github. Locally it works fine. This is the error I get:

`Fatal error: Class phpDocumentor\Reflection\PseudoTypes\List_ may not inherit from final class (phpDocumentor\Reflection\Types\Array_) in /opt/atlassian/pipelines/agent/build/bin/.phpunit/phpunit-9.3-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27`

The command I'm running is just `bin/phpunit`

**Comment by HaukeHa** [comment]
Experiencing the same issue, deleting `bin/.phpunit` did not solve it. 

Edit:  `composer update phpdocumentor/type-resolver` as proposed in [this issue](https://github.com/phpDocumentor/TypeResolver/issues/148#issuecomment-1005639647) fixes it for me

**Comment by derrabus** [comment]
Closing then as there isn't much else we can do here. You either need to keep the phpDocumentor packages up to date or apply the fix suggested in https://github.com/phpDocumentor/TypeResolver/issues/148#issuecomment-1005635163 to avoid such issues, I'm afraid.

**Comment by drzraf** [comment]
For me it's just a warning (and not blocking), but I found that the strange output is triggered by that line:

`foreach (explode("\n", $COMPOSER info --no-ansi -a -n phpunit/phpunit "$PHPUNIT_VERSION.*") as $line) {`
which calls `composer info  --no-ansi -a -n phpunit/phpunit 9.5.28.*` within `vendor/bin/.phpunit`

What happens is the following:
```
No composer.json in current directory, do you want to use the one at <MY PROJECT DIRECTORY>? [Y,n]? n
No composer.json found in the current directory, showing available packages from <ONE LEVEL UP UNRELATED DIR>
```

It sounds like under some (unknown) circumstances, `-n` is keeping search prompt from considering the first parent's composer.json found, like if it answered `no` to the `use-parent-dir` option.

And `composer config --global use-parent-dir true` doesn't make it better.
