### ISSUE TITLE
[HttpClient] "Idle timeout reached" error when streaming response

### ISSUE THREAD

**Issue by vyshkant** [symfony/symfony#44934]
### Symfony version(s) affected

5.3.13

### Description

I have  `default_socket_timeout` set to `-1` (which is supposed to mean some big timeout). I noticed a bug, which appears when I'm trying to stream response: I have "Idle timeout reached" error.

### How to reproduce

```php
$response = $httpClient->request('GET', 'https://example.org');
$stream = $response->toStream();
```

which gets us the next call chain
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L112
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L116
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L64
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L67
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L141
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L149
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L151
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L193

where at the last point `$timeoutMax` equals `0`, so any elapsed time will exceed this value.

### Possible Solution

`$timeoutMax` value should be set to some big number instead of zero.

### Additional Context

Relevant issues are: #44477 #44878

**Comment by nicolas-grekas** [comment]
I'm not sure I understand why this is different than #44477. Did you try the patch in #44878? Does it fix the issue for you?
Note that the fix has not been released and will be part of 5.3.14.

**Comment by vyshkant** [comment]
>  I'm not sure I understand why this is different than #44477. Did you try the patch in #44878? Does it fix the issue for you?
Note that the fix has not been released and will be part of 5.3.14.

No, I didn't try that patch. But as far as I see, the patch is about setting the correct `timeout` value to the `$options` object during `request` method execution, while my problem is about interpreting `-0.0` value (which is hardcoded to be this value regardless of `default_socket_timeout` value) during response streaming.

**Comment by nicolas-grekas** [comment]
Can you please try the patch?

**Comment by vyshkant** [comment]
> Can you please try the patch?

Yep! I'll try it after it's released, will let you know the results.
