### ISSUE TITLE
[Translator] Literal and (HTML) safe translatables

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#44937]
### Description

Inspired by #44911 

To work with translatable strings in a uniform way, currently 2 features are missing still IMHO.

1) bypass the translator for literal text, and avoid if/else based on eg. `string|Translatable` input

```php
$t = TranslatableMessage::literal('should not be translated')->trans(...);
```

2) a bit more controversial; bypass (HTML) escaping

this is arguably already a first-class concept to regognize: https://symfony.com/doc/current/reference/forms/types/form.html#label-html

```php
$t = TranslatableMessage::safe('should be translated, but not escaped when rendered')->trans(...);
```

This would generalize the case of bypass-escaping in whatever context ...

This could combine 3) `safeLiteral()`

WDYT?

**Comment by ro0NL** [comment]
i figured `{{ var|t|raw }}` is the fastest way to bypas escaping, currently possible (rather than just `var|t` with a "safe translatable")

considering parameters can be translatables too, this would become an extremely complex goal :) (eg. an unsafe message, with (some) safe parameters)

closing as such (ive no usecase for literal(:-))

**Comment by sylfabre** [comment]
@ro0NL another use-case I don't know how to properly handle: translate this where firstname is a user input so should be escaped but the string contains safe HTML

`"Hello <strong>{ firstname }</strong>"`

**Comment by ro0NL** [comment]
> considering parameters can be translatables too, this would become an extremely complex goal

for a safe translatable each param could be escaped still, unless some param is wrapped with `T::safe` also
