### ISSUE TITLE
[Process] arrays in `$env` result in `Array to string conversion`

### ISSUE THREAD

**Issue by doobry-systemli** [symfony/symfony#44940]
### Symfony version(s) affected

4.4.35, 4.4.36

### Description

Since https://github.com/symfony/symfony/commit/11ccbcd24c2e2d3f4e5897f159d1c1d23fc62a67, `Process->run()` prints errors "Array to string conversion" when `$env` contains array.

Before this commit, `$env` was cleaned of arrays, but this got removed. In particular [this removed `array_filter()` on `$env`](https://github.com/symfony/symfony/commit/11ccbcd24c2e2d3f4e5897f159d1c1d23fc62a67#diff-edd51b05bf438c7cdca442e25d68f41dd0a51952a69fa0c5fa912dc31d833ef4L1189-L1191) introduces the bug.

Similar issues were reported e.g. in https://github.com/symfony/symfony/issues/44197, but there only `$argv`/`$argc` were discussed and handled.

What's the reason for removing the `array_filter()` that cleaned `$env` from arrays?

Below you find an example of `$env` (dumped [here in `Process.php`](https://github.com/symfony/symfony/blob/v4.4.35/src/Symfony/Component/Process/Process.php#L342) that causes the described bug. The dump is from [userli's checkpassword symfony command](https://github.com/systemli/userli/blob/main/src/Command/CheckPasswordCommand.php). Also see https://github.com/systemli/userli/issues/341 for details.

<details>
<summary>
Fold/Collapse var_dump($env)
</summary>

<pre>
/vagrant/vendor/symfony/process/Process.php:342:
array(52) {
  [0] =>
  array(27) {
    'SHELL' =>
    string(9) "/bin/bash"
    'SSH_AUTH_SOCK' =>
    string(31) "/tmp/ssh-BHtDglisnt/agent.29483"
    'PWD' =>
    string(8) "/vagrant"
    'LOGNAME' =>
    string(7) "vagrant"
    'XDG_SESSION_TYPE' =>
    string(3) "tty"
    'MOTD_SHOWN' =>
    string(3) "pam"
    'HOME' =>
    string(13) "/home/vagrant"
    'LANG' =>
    string(7) "C.UTF-8"
    'LS_COLORS' =>
    string(1508) "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01"...
    'SSH_CONNECTION' =>
    string(38) "192.168.121.1 36092 192.168.121.169 22"
    'NPM_CONFIG_PREFIX' =>
    string(18) "/usr/local/lib/npm"
    'XDG_SESSION_CLASS' =>
    string(4) "user"
    'TERM' =>
    string(11) "xterm-kitty"
    'USER' =>
    string(7) "vagrant"
    'SHLVL' =>
    string(1) "0"
    'XDG_SESSION_ID' =>
    string(2) "11"
    'XDG_RUNTIME_DIR' =>
    string(14) "/run/user/1000"
    'NODE_PATH' =>
    string(36) ":/usr/local/lib/npm/lib/node_modules"
    'SSH_CLIENT' =>
    string(22) "192.168.121.1 36092 22"
    'LC_ALL' =>
    string(11) "en_US.UTF-8"
    'PATH' =>
    string(79) "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/lib/npm/bin"
    'SSH_TTY' =>
    string(10) "/dev/pts/1"
    'OLDPWD' =>
    string(13) "/home/vagrant"
    '_' =>
    string(11) "bin/console"
    'LINES' =>
    string(2) "50"
    'COLUMNS' =>
    string(2) "80"
    'SHELL_VERBOSITY' =>
    string(1) "0"
  }
  'USER' =>
  string(17) "admin@example.org"
  'HOME' =>
  string(28) "/var/vmail/example.org/admin"
  'userdb_uid' =>
  int(5000)
  'userdb_gid' =>
  int(5000)
  'EXTRA' =>
  string(21) "userdb_uid userdb_gid"
  'APP_NAME' =>
  string(6) "Userli"
  'APP_URL' =>
  string(25) "https://users.example.org"
  'PROJECT_NAME' =>
  string(11) "example.org"
  'PROJECT_URL' =>
  string(23) "https://www.example.org"
  'SENDER_ADDRESS' =>
  string(17) "admin@example.org"
  'NOTIFICATION_ADDRESS' =>
  string(22) "monitoring@example.org"
  'SEND_MAIL' =>
  string(1) "1"
  'LOCALE' =>
  string(2) "en"
  'HAS_SINA_BOX' =>
  string(1) "0"
  'MAIL_CRYPT' =>
  string(1) "2"
  'DOVECOT_MAIL_LOCATION' =>
  string(10) "/var/vmail"
  'DOVECOT_MAIL_UID' =>
  string(4) "5000"
  'DOVECOT_MAIL_GID' =>
  string(4) "5000"
  'WEBMAIL_URL' =>
  string(0) ""
  'WKD_DIRECTORY' =>
  string(36) "/var/www/html/.well-known/openpgpkey"
  'WKD_FORMAT' =>
  string(8) "advanced"
  'APP_ENV' =>
  string(3) "dev"
  'APP_SECRET' =>
  string(32) "165e25e3846534bb4665d7078a851c0b"
  'MAILER_URL' =>
  string(42) "smtp://localhost:25?encryption=&auth_mode="
  'MAILER_DELIVERY_ADDRESS' =>
  string(17) "admin@example.org"
  'DATABASE_URL' =>
  string(71) "mysql://mail:password@127.0.0.1:3306/mail?serverVersion=mariadb-10.3.23"
  'SYMFONY_DOTENV_VARS' =>
  string(278) "APP_NAME,APP_URL,PROJECT_NAME,PROJECT_URL,SENDER_ADDRESS,NOTIFICATION_ADDRESS,SEND_MAIL,LOCALE,HAS_SINA_BOX,MAIL_CRYPT,DOVECOT_MAIL_LOCATION,DOVECOT_MAIL_UID,DOVECOT_MAIL_GID,WEBMAIL_URL,WKD_DIRECTORY,WKD_FORMAT,APP_ENV,APP_SECRET,MAILER_URL,MAILER_DELIVERY_ADDRESS,DATABASE_URL"
  'APP_DEBUG' =>
  string(1) "1"
  'SHELL_VERBOSITY' =>
  int(0)
  'SHELL' =>
  string(9) "/bin/bash"
  'SSH_AUTH_SOCK' =>
  string(31) "/tmp/ssh-BHtDglisnt/agent.29483"
  'PWD' =>
  string(8) "/vagrant"
  'LOGNAME' =>
  string(7) "vagrant"
  'XDG_SESSION_TYPE' =>
  string(3) "tty"
  'MOTD_SHOWN' =>
  string(3) "pam"
  'LANG' =>
  string(7) "C.UTF-8"
  'LS_COLORS' =>
  string(1508) "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01"...
  'SSH_CONNECTION' =>
  string(38) "192.168.121.1 36092 192.168.121.169 22"
  'NPM_CONFIG_PREFIX' =>
  string(18) "/usr/local/lib/npm"
  'XDG_SESSION_CLASS' =>
  string(4) "user"
  'TERM' =>
  string(11) "xterm-kitty"
  'SHLVL' =>
  string(1) "0"
  'XDG_SESSION_ID' =>
  string(2) "11"
  'XDG_RUNTIME_DIR' =>
  string(14) "/run/user/1000"
  'NODE_PATH' =>
  string(36) ":/usr/local/lib/npm/lib/node_modules"
  'SSH_CLIENT' =>
  string(22) "192.168.121.1 36092 22"
  'LC_ALL' =>
  string(11) "en_US.UTF-8"
  'PATH' =>
  string(79) "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/lib/npm/bin"
  'SSH_TTY' =>
  string(10) "/dev/pts/1"
  'OLDPWD' =>
  string(13) "/home/vagrant"
  '_' =>
  string(11) "bin/console"
}
</pre>
</details>

### How to reproduce

Run `Process->run()` with `$env` as pasted above.

**Comment by nicolas-grekas** [comment]
Filtering out arrays was added by mistake as it makes no sense. Fixing https://github.com/systemli/userli/issues/341 is the way to go IMHO here.

**Comment by doobry-systemli** [comment]
Agreed, was to late yesterday. The changes in `symfony/process` just revealed a bug in userli: https://github.com/systemli/userli/blob/main/src/Command/CheckPasswordCommand.php#L230 is wrong.
