### ISSUE TITLE
Read receipt in mailer component

### ISSUE THREAD

**Issue by lourdas** [symfony/symfony#44956]
### Description

Coming from SwiftMailer, I was a bit surprised to see that symfony-mailer does not have a request read receipt method. Is it possible that I missed something? swiftmailer included the `setReadReceiptTo()` method for this.

**Comment by fabpot** [comment]
When porting, I've removed features that are rarely needed. As read receipts are blocked by many mailers anyway, I did not add it to Symfony Mailer. You can add it anyway by adding a `Disposition-Notification-To` header, so there is no need for a specific method IMHO.

**Comment by lourdas** [comment]
Thank you @fabpot for the explanation, I will try the method you mentioned.
