### ISSUE TITLE
[DependencyInjection] `lint:container` fails if kernel implements interface registered for autoconfiguration

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#44972]
### Symfony version(s) affected

5.4+

### Description

When your Kernel implements an interface that is registered for auto-configuration, the following error occurs when running `lint:container`:

```
[ERROR] Invalid definition for service "kernel": Symfony\Component\HttpKernel\Kernel::__construct()" requires 2 arguments, 0 passed.
```

This only appears to be a problem for the lint command. The kernel is auto-configured correctly and behaves as expected.

### How to reproduce

```
git clone git@github.com:kbond/lint-container-reproducer.git
cd lint-container-reproducer
composer install
bin/console lint:container # throws exception
```

### Possible Solution

#44972.

### Additional Context

Seems similar to #40868.

Commit on my reproducer that causes the failure: https://github.com/kbond/lint-container-reproducer/commit/8676d5f93bbbf0a952aef01ae327b676efb41ceb

**Comment by nicolas-grekas** [comment]
We should skip synthetic services. Up for a PR?

**Comment by kbond** [comment]
You mean in `CheckTypeDeclarationsPass`? This was my first thought as well but the `kernel` service definition isn't marked as synthetic at the point it's checked.

**Comment by kbond** [comment]
I found @shiftby's proposed solution [here](https://github.com/symfony/symfony/issues/40868#issuecomment-822608622) looks to fix the issue. But.. if I understand @stof's comment correctly, he's saying the correct solution is for the kernel service to not be a child definition at all. It looks like `ContainerBuilder::registerForAutoconfiguration()` is what sets the kernel as a `ChildDefinition` (when it implements the autoconfiguration interface) so I don't think that's avoidable?

**Comment by stof** [comment]
Synthetic services should not be autoconfigured either (as the container is not responsible for instantiating them)

**Comment by nicolas-grekas** [comment]
Actually yes they should, that's how the kernel is registered as an event listener/etc depending on what it implements, isn't it?

**Comment by kbond** [comment]
The microkernel has been autoconfigurable for some time (https://github.com/symfony/symfony/pull/34881)

**Comment by stof** [comment]
hmm, yeah. For autoconfiguration that adds tags, it might indeed still make sense. but the synthetic status should indeed be preserved
