### ISSUE TITLE
showing warning symfony failed messenger show command

### ISSUE THREAD

**Issue by saifulferoz** [symfony/symfony#44988]
### Symfony version(s) affected

4.4.35

### Description

 Warning: Undefined array key "headers"  
                                          

Exception trace:
  at /var/www/html/epathshala/vendor/symfony/messenger/Transport/Doctrine/Connection.php:411

When trying to retrieve failed message from Doctrine transport using database Oracle

### How to reproduce

execute command  bin/console messenger:failed:show

**Comment by rjd22** [comment]
@nicolas-grekas I'm just seeing this issue after looking for more Oracle issues and I would guess my PR fixes this issue:

https://github.com/symfony/symfony/pull/46121

**Comment by fabpot** [comment]
Closing then, thank you.
