### ISSUE TITLE
HTML Sanitizer: Error Installing via Composer

### ISSUE THREAD

**Issue by Menelion** [symfony/symfony#45005]
### Symfony version(s) affected

6.0.2

### Description

Whenever I try to install the new HTML sanitizer component with `composer require symfony/html-sanitizer`, I get:

```shell
  [InvalidArgumentException]
  Could not find package symfony/html-sanitizer in a version matching "6.0.*" and a stability matching "dev". 
```

### How to reproduce

1. Create a fresh Symfony project or just open a folder in your terminal.
2. Type `composer require symfony/html-sanitizer`.

### Possible Solution

Something is definitely wrong with the version on Packagist. If this is done intentionally, please tell about it and I'll be happy to send a PR to add the corresponding info to the component's Readme.

**Comment by derrabus** [comment]
> in a version matching "6.0.*" and a stability matching "dev".

There is no 6.0 version of that component. The first stable release will be 6.1.0.

**Comment by abelardolg** [comment]
Hi there,

`composer require symfony/html-sanitizer@6.1.0`

Is right or how should I install it?
"php": "^7.4",
Symfony 5.4
Best regards.

**Comment by xabbuh** [comment]
@abelardolg `composer require symfony/html-sanitizer:^6.1`

**Comment by abelardolg** [comment]
Aps, when I upgrade my PHP to 8.0, then I am going to install it. Thanks, Christian :)  @xabbuh
