### ISSUE TITLE
[Mailer] HTML/Text template from string

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#45009]
### Description

Twig has a [`template_from_string`](https://twig.symfony.com/doc/2.x/functions/template_from_string.html) utility

It would be great if we can integrate it somehow when sending one-off templated e-mails.

### Example

```php
(new TemplatedEmail())->htmlStringTemplate('Hello <em>{{ name }}</em>');
(new TemplatedEmail())->textStringTemplate('Hello {{ name }}');
```

**Comment by n0rbyt3** [comment]
You can register twigs string loader as a service, tag it as ```twig.loader``` service and give it a priority < 0. The filesystem loader is replaced by a chained loader then which will register the filesystem loader first, then the string loader. If the filesystem loader cannot find the template, the string loader will do the job.

**Comment by ro0NL** [comment]
sounds reasonable, as say a doc chapter

maybe i should build something around `->htmlTemplate(template_from_string(...))` in userland ... :thinking:

**Comment by n0rbyt3** [comment]
If you have only few occurences of this code, create a little helper or inject twigs ```Environment``` class directly. Then use:

```php
$template = $twig->createTemplate(<your Twig string>);
$html = $template->render($params);
```

And instead of ```TemplatedEmail``` use ```Email```.

The downfall of this method is, that you will bypass the BodyRenderer which has some magic stuff inside (create text content from html).

On the other hand, ```Twig_Loader_String``` is deprecated.

Or create your own loader and prefix your template code with ```twig://``` so your loader will only accept this string syntax, not every string.

**Comment by stof** [comment]
Registering Twig_Loader_String in the loader chain is a very bad idea, as it breaks any kind of validation of which templates exist or no (as Twig_Loader_String was using the template name as the source code, and so accepting any string)

**Comment by ro0NL** [comment]
im not generally fond of having to rely on global twig env for it to work yes/no, wheres composition takes away such compatibilty issues

i'll try to play a bit with email+template_from_string in userland soonish, to see how well it plays vs. some first-class support in core.

**Comment by ro0NL** [comment]
```
 Unable to find template "__string_template__f2351587bb5b97dc6477b03a6a289c614edd44b33ebd3cd7c118efe407a9206f"
```
