### ISSUE TITLE
Serializer Groups attribute silently skips additional arguments

### ISSUE THREAD

**Issue by mbrodala** [symfony/symfony#45027]
### Symfony version(s) affected

v5.4.2

### Description

The `Groups` attribute silently skips additional arguments.

Natively supported is a single group as string or multiple groups as array:

```php
use Symfony\Component\Serializer\Annotation\Groups;

#[Groups(
    'first'
)]

#[Groups([
    'first',
    'second',
])]
```

However, the following will silently drop the 2nd and following groups without any warning or error:

```php
#[Groups(
    'first',
    'second',
)]
```

This can be very hard to spot and can lead to many subtle bugs in the application.

### How to reproduce

Create an object with a `Groups` attribute having multiple serialization groups without a wrapping array.

### Possible Solution

I see at least two options:

1. Fail hard with an exception if there is more than one argument
2. Add support for variadic group arguments

**Comment by stof** [comment]
PHP itself does not throw an error when you pass additional arguments to a method, which is why it is silently ignored. We don't have safeguard in all our methods to change that behavior in Symfony, and we won't do it.

That's a job for static analysis (both phpstan and psalm can report cases where you pass unknown arguments, but I'm not sure they do it for attributes yet).

**Comment by mbrodala** [comment]
I understand the reasoning here and that Symfony is not required to fix shortcomings or "features" of PHP.

Still this little thingy did cost me at least an hour so I'm interested if something could be done about the runtime behavior. Of course, I'll also check for static analysis options to avoid this.

**Comment by mbrodala** [comment]
Just a notice: PHPStan indeed reports this:

https://phpstan.org/r/d5b2c963-4a2c-4515-a7e1-8cf9c7af3460

> Attribute class FooAttribute constructor invoked with 2 parameters, 1 required.

**Comment by stof** [comment]
> so I'm interested if something could be done about the runtime behavior.

not without adding hacks in the codebase to not actually make those additional arguments (which would then maybe also mean that static analysers would not detect the mistake anymore, as for them, the constructor would accept 2 arguments). and why would we do it for a single class in our codebase ? If we start adding such hack, it would have to be consistent, and I'm clearly against the fact of adding that in all methods of the codebase (not even counting the performance impact of running such extra check for all method calls).
Please use a static analyser instead, which already detects this, and without any performance impact.

**Comment by mbrodala** [comment]
Fine with me, I just wanted to be sure to ask about this. :-)

In fact, if I had executed PHPStan while working on this, I would have noticed the error right away. So yes, static analysis is the way to go as this is [unlikely to enter PHP](https://wiki.php.net/rfc/strict_argcount) for the time being.
