### ISSUE TITLE
[Redis-Messenger] Exits with error when Messenger starts consuming messages 

### ISSUE THREAD

**Issue by nicoalonso** [symfony/symfony#45022]
### Symfony version(s) affected

5.4

### Description

Container exits with this error when starts consuming messages:

```php
In RedisReceiver.php line 50:
                                                                            
[TypeError]                                                                 
array_key_exists(): Argument #2 ($array) must be of type array, null given
```

When we debug the code in line 50 of RedisReceiver.php
```php
    /**
     * {@inheritdoc}
     */
    public function get(): iterable
    {
        $message = $this->connection->get();

        if (null === $message) {
            return [];
        }
        dump($message);

        $redisEnvelope = json_decode($message['data']['message'] ?? '', true);

        try {
            if (\array_key_exists('body', $redisEnvelope) && \array_key_exists('headers', $redisEnvelope)) {
                $envelope = $this->serializer->decode([
                    'body' => $redisEnvelope['body'],
                    'headers' => $redisEnvelope['headers'],
                ]);
            } else {
                $envelope = $this->serializer->decode($redisEnvelope);
            }
        } catch (MessageDecodingFailedException $exception) {
            $this->connection->reject($message['id']);

            throw $exception;
        }

        return [$envelope->with(new RedisReceivedStamp($message['id']))];
    }
```

In message we have:
```php
$message = [
    "id" => "1641827007019-0"
    "data" => null
]
```

In this case when decode empty string the variable `$redisEnvelope` is **null**.

### How to reproduce

This error does not always occur, in some cases, this type of message is not received.

In our case, we create a docker image from `php:8.0.13-cli-alpine3.13` and install the pecl extension redis-5.3.5

When launch the command like that:

```bash
php bin/console messenger:consume async_queue -vv
```

### Possible Solution

```php
    /**
     * {@inheritdoc}
     */
    public function get(): iterable
    {
        $message = $this->connection->get();

        if (null === $message) {
            return [];
        }

        $redisEnvelope = json_decode($message['data']['message'] ?? '', true);

        if (null === $redisEnvelope) {
            return [];
        }

        try {
            if (\array_key_exists('body', $redisEnvelope) && \array_key_exists('headers', $redisEnvelope)) {
                $envelope = $this->serializer->decode([
                    'body' => $redisEnvelope['body'],
                    'headers' => $redisEnvelope['headers'],
                ]);
            } else {
                $envelope = $this->serializer->decode($redisEnvelope);
            }
        } catch (MessageDecodingFailedException $exception) {
            $this->connection->reject($message['id']);

            throw $exception;
        }

        return [$envelope->with(new RedisReceivedStamp($message['id']))];
    }
```

### Additional Context

* Symfony 5.4
* PHP-cli 8.0.13
* ext-redis 5.3.5
* Redis 6.2.4

**Comment by ghost** [comment]
> When we debug the code in line 50 of RedisReceiver.php

When referencing a line in a file please use a GitHub permalink.

> Possible Solution

Please do not past a code snipped with a modified function but point out explicitly what is the possible solution. We don't have a git diff in our eyes.

**Comment by nicoalonso** [comment]
Hi,

In case it can be of help: [Fork with possible solution](https://github.com/nicoalonso/redis-messenger/blob/a3b0e37baf7356419cad8e0ba184915ddeb3b006/Transport/RedisReceiver.php#L49)

And [Git diff](https://github.com/nicoalonso/redis-messenger/commit/a3b0e37baf7356419cad8e0ba184915ddeb3b006)

If you need I can create a Merge Request.

Thanks and Regards

**Comment by chalasr** [comment]
PR welcome :) Should target the lowest maintained branch where the bug exists.

**Comment by nicoalonso** [comment]
PR Created !!

[45279](https://github.com/symfony/symfony/pull/45279)

Thanks and regards

**Comment by nicoalonso** [comment]
I found another problem, when the message is wrong, like so:

```php
$message = [
    "id" => "1641827007019-0"
    "data" => null
]
```

Symfony messenger gets stuck handle the same wrong message

So, I think that the best way to solve this is to reject the message.
I update the PR

Thanks and Regards
