### ISSUE TITLE
[MIME] email.image() not working with src in single quotes

### ISSUE THREAD

**Issue by Rogos** [symfony/symfony#45031]
### Symfony version(s) affected

5.4.*

### Description

Embedded images not working when src is written in single quotes.

### How to reproduce

this works:
`<img src="{{ email.image('@images/mail1/img1.jpg') }}">`
but this not:
`<img src='{{ email.image("@images/mail1/img1.jpg") }}'>`

### Possible Solution

vendor/symfony/mime/Email.php:469
I think it should be something like this:
```
preg_match_all('(<img\s+[^>]*src\s*=\s*(?:"cid:([^"]+)"|\'cid:([^\']+)\'|cid:([^>\s]+)))i', $html, $names);
$names = array_filter(array_unique(array_merge($names[1], $names[2], $names[3])));
```
instead this:
```
preg_match_all('(<img\s+[^>]*src\s*=\s*(?:([\'"])cid:([^"]+)\\1|cid:([^>\s]+)))i', $html, $names);
$names = array_filter(array_unique(array_merge($names[2], $names[3])));
```

**Comment by htmlshaman1** [comment]
status: works for me on 6.0.4
I used symfony 6.0.4, and single quotes to embed an image worked for me.

**Comment by xabbuh** [comment]
@Rogos Can you create a small example application that allows to reproduce your issue?

**Comment by Rogos** [comment]
> @Rogos Can you create a small example application that allows to reproduce your issue?

sorry, I don't have time for creating example app, but pls take a look at the regex, this part:
`([\'"])cid:([^"]+)\\1`
it allows to start with single or double quote but cid name includes only non-double-quote characters, it will also catch closing single quote
