### ISSUE TITLE
[HttpFoundation] Add support for remaining response cache control directives

### ISSUE THREAD

**Issue by nandi95** [symfony/symfony#45036]
### Description

Tried to use `stale-while-revalidate` in a laravel app and found that it isn't supported.
The directives were introduced by this commit: https://github.com/symfony/symfony/commit/402909ff7b20608ce2296a244abc29924e826793 by @fabpot based on this issue: https://github.com/symfony/symfony/issues/35720
It seems there are missing directives. Would it be possible to add the remaining directives? [MDN Docs - Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)

**Comment by nandi95** [comment]
At the time of adding the above headers `stale-while-revalidate` was already available.
Wayback machine failed me, to check the mdn docs but this google blog was dated before the commit: https://web.dev/stale-while-revalidate/

**Comment by remilemonnier** [comment]
Hi  @nandi95,
+1
I do have the same problem.
On top of that stale-while-revalidate and stale-if-error are part of the RFC 5861
https://httpwg.org/specs/rfc5861.html

**Comment by nicolas-grekas** [comment]
Please send a PR, that's the best way to move forward.

**Comment by remilemonnier** [comment]
Hi Nicolas,
Thanks for your answer.
I'm working on the PR. Currently adding unit tests.

**Comment by remilemonnier** [comment]
Hi @nandi95, Hi @nicolas-grekas,

Please find the Pull Request:
https://github.com/symfony/http-foundation/pull/78

It's my first PR to symfony don't hesitate to tell me if I'm wrong on something.
I have carrefully read the pull request documentation.
Hopefully I don't waste time of anybody.

**Comment by remilemonnier** [comment]
Hi @nandi95, Hi @nicolas-grekas,

Please find the correct one:
https://github.com/symfony/symfony/pull/45166
