### ISSUE TITLE
Accessing array values in $request->request->get() throws error

### ISSUE THREAD

**Issue by fun2life** [symfony/symfony#45030]
### Symfony version(s) affected

6.0.2

### Description

When accessing a POST variable containing an array initiated by a checkbox via `$request->request->get('mycheckbox');` the error `Input value "mycheckbox" contains a non-scalar value`. is thrown.

Symfony Server as well as on Apache
PHP 8.0.12

### How to reproduce

Form:
```
<form method="post" action="/merge">
 <input type="checkbox" name="mycheckbox[]" value="1" />
 <input type="checkbox" name="mycheckbox[]" value="2" />
 <input type="submit" value="Send">
</form>
```

Controller
`dump($request->request->get('mycheckbox'));`

### Additional Context

request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Input value "mycheckbox" contains a non-scalar value." at [...]\vendor\symfony\http-kernel\HttpKernel.php line 77 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Input value \"mycheckbox\" contains a non-scalar value. at [...]\\vendor\\symfony\\http-kernel\\HttpKernel.php:77)\n[previous exception] [object] (Symfony\\Component\\HttpFoundation\\Exception\\BadRequestException(code: 0): Input value \"mycheckbox\" contains a non-scalar value. at [...]\\vendor\\symfony\\http-foundation\\InputBag.php:37)"} []

**Comment by nicolas-grekas** [comment]
You need to use `$request->request->all('mycheckbox')`
