### ISSUE TITLE
[String]: `->match()` with flag PREG_OFFSET_CAPTURE giving wrong results (i.e. ignoring Unicode)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#45032]
### Symfony version(s) affected

5.4.2

### Description

When using the flag `PREG_OFFSET_CAPTURE` with `$string->match()` on a `UnicodeString`, the position of the matched characters is given in *bytes*, not in characters (graphemes).

This is in fact an issue of PHP's `preg_match_all()`; I reported it at https://bugs.php.net/bug.php?id=80166 => Outcome: They didn't change anything, but at least documented the status-quo ;-)
So I was hoping that Symfony's String Component "fixed" it...

### How to reproduce

```php
$string = new UnicodeString('öa');
$result = $string->match('/a/', \PREG_PATTERN_ORDER|\PREG_OFFSET_CAPTURE); // PREG_PATTERN_ORDER is only there to make Symfony use `preg_match_all()` instead of `preg_match()`
dd($result);
```

Actual result (in the innermost array):
```
1 => 2 // `ö` is counted as 2 bytes, therefore `a` is at index-position 2
```
Expected result:
```
1 => 1 // `ö` should be counted as 1 Unicode character (grapheme), then `a` would be at index-position 1
```

**Comment by nicolas-grekas** [comment]
Unfortunately that'd be super expensive to fix, performance wise. That's why it's the way it is now...

**Comment by ThomasLandauer** [comment]
Well, then what about at least expanding the docs a little? Right now, there's only 1 short example of `match()` at https://symfony.com/doc/current/components/string.html#methods-to-search-and-replace. I'd move the regexp search into a dedicated code block and explain:
* How to switch between `preg_match()` and `preg_match_all()`
* The limitation of this issue.

Good idea?

**Comment by stof** [comment]
Note that the `$offset` of `AbstractUnicodeString::match()` is also a byte offset and not a character offset, as it is the offset passed to `preg_match` and `preg_match_all`.

> This is in fact an issue of PHP's `preg_match_all()`; I reported it at https://bugs.php.net/bug.php?id=80166 => Outcome: They didn't change anything, but at least documented the status-quo ;-)
> So I was hoping that Symfony's String Component "fixed" it...

Well, they haven't fixed it because PCRE returns byte offsets and turning a byte offset into a character offset is a `O(n)` operation (and for `preg_match_all` with offset capturing, we have multiple offsets to convert). In the context of PHP, their decision is totally expected (PHP also has all the string functions working with byte offsets, so you **don't** need to convert offsets to split the string).

In symfony/string, dealing with byte offsets in `match` while all other methods deal with character offsets is indeed confusing to me.

**Comment by nicolas-grekas** [comment]
I agree it's confusing, but like said, changing the unit here means adding O(n) complexity.

We could maybe deprecate passing the `PREG_OFFSET_CAPTURE` flag with `AbstractUnicodeString`?

**Comment by stof** [comment]
@nicolas-grekas we would also have to deprecate passing the `$offset` argument

**Comment by nicolas-grekas** [comment]
@stof right, maybe not the best idea.
@ThomasLandauer feel free to send a PR to improve the phpdoc. I think that's the best way to move forward here.

**Comment by ThomasLandauer** [comment]
Please take a look at https://github.com/symfony/symfony-docs/pull/16424

`PREG_OFFSET_CAPTURE` is still missing there, so what's the bottom line now?
* Symfony's `$string->slice()` needs the *character* position, so it's not compatible with the output of `PREG_OFFSET_CAPTURE`?
* But PHP's native `substr()` does work:
    ```php
    $string = new UnicodeString('öa');
    $string->match('/a/', \PREG_PATTERN_ORDER|\PREG_OFFSET_CAPTURE); // gives 2
    dd(substr('öa', 2)); // gives "a" => OK!
    ```
* But PHP's `mb_*` functions don't? `mb_substr('öa', 2);` gives `''`
* So using the String Component doesn't really bring an advantage in this case (since you have to switch to PHP's native functions anyway). Cause the above example is probably better written as:
    ```php
    preg_match_all('/a/', 'öa', $matches);
    ```
Right?

**Comment by nicolas-grekas** [comment]
@ThomasLandauer correct. This is the tradeoff. Using `substr()` might be appropriate when dealing with capture offsets.
