### ISSUE TITLE
[Translation] Entity constraints are not taken into account in the translation:extract

### ISSUE THREAD

**Issue by geoffroyp** [symfony/symfony#45039]
### Description

In the current symfony documentation ( [https://symfony.com/doc/current/validation/translations.html](url) ), it says that we can translate validation constraints by simply adding a translation key in "message" property, then adding this key in a "validators" catalog file.

Nice. But it would be soooo much better, easier and safer it we could generate this file by using the `translation:extract` command like for any other translation. 

However, according to the translator documentation: https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically

```
The translation:extract command looks for missing translations in:

Templates stored in the templates/ directory (or any other directory defined in the twig.default_path and twig.paths config options);
Any PHP file/class that injects or autowires the translator service and makes calls to the trans() method.
Any PHP file/class stored in the src/ directory that creates Translations using the constructor or the t() method or calls the trans() method.
```

Therefore, since validator in entities 
- are not in `/templates/`
- do not inject translator service
- do not call trans() or t()

then these keys are never extracted by the `translation:extract` command. And indeed, after trying it in my project, I can confirm they are not.

Could we get a fix for that?

**Comment by ro0NL** [comment]
ref https://github.com/symfony/symfony/pull/44911#issuecomment-1006529786

**Comment by nicolas-grekas** [comment]
@geoffroyp, @ro0NL or anyone else, would you like to work on this?

**Comment by welcoMattic** [comment]
There is a workaround to "force" entity constraint messages to be extracted:

```php
#[ORM\Entity(repositoryClass: FooRepository::class)]
class Foo
{
    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank([], new TranslatableMessage('foo.name.not_blank.message', [], 'validators'))]
    private string $name;
```

As `PhpExtractor` is looking for `TranslatableMessage` occurences, and `TranslatableMessage` implements a `__toString` method, it can be extracted.

However, it needs PHP >= 8.1, as instanciation in expression are not allowed before PHP 8.1.

I think this issue can join the reasons list to write a new `PhpExtractor` (see https://github.com/symfony/symfony/issues/45972).

cc @victou
