### ISSUE TITLE
Parse error: syntax error, unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by sidbenac** [symfony/symfony#45049]
### Symfony version(s) affected

6.0.2

### Description

Parse error: syntax error, unexpected 'static' (T_STATIC) in /data/app/vendor/symfony/string/UnicodeString.php on line 44

is this related to php version ?, I am still using php 7.3, I tried to lock composer to php 7.3, but it doesn't work. all my app is down due to this error, any idea ?

### How to reproduce

calling /string

**Comment by stof** [comment]
Symfony 6.0 requires PHP 8+

Make sure you run composer using the same PHP version than when running your app, or configure composer to override the platform version: https://getcomposer.org/doc/06-config.md#platform

**Comment by MaxDecoder28** [comment]
In drupal its shows this error "syntax error 'static' (T_STATIC)" have an idea what i do please help me
