### ISSUE TITLE
Why is symfony/http-client only require-dev and not require in symfony/mailgun-mailer ?

### ISSUE THREAD

**Issue by jonnott** [symfony/symfony#45046]
### Symfony version(s) affected

6.x

### Description

The constructors for `Symfony\Component\Mailer\Bridge\Mailgun\Transport\AbstractApiTransport` and `MailgunHttpTransport` both have a `HttpClientInterface $client` argument, so therefore I don't understand why `symfony/http-client` is in require-dev, as it will always be needed, even in production, won't it? Shouldn't it be in the require section of composer.json instead?

[I'm coming from the context of Laravel 9.x (currently in beta) by the way, where symfony/mailer is a standard dependency, but if you need to use Mailgun transports, you have to `composer require symfony/mailgun-mailer` (just like in Symfony), but unless you also manually require the HTTP Client, it won't work without it.]

### How to reproduce

Try to use mailgun-mailer in Laravel 9.x without also requiring HTTP Client (as it's require-dev).

**Comment by stof** [comment]
@jonnott because of MailgunSmtpTransport, which is the third transport available in the package. `symfony/http-client` is only needed by 2 or the 3 transports

**Comment by stof** [comment]
@fabpot maybe the `mailgun` scheme should fallback to SMTP rather than API if the transport factory does not have an HTTPClient (while `mailgun+api` would always force using the API) ?

**Comment by jonnott** [comment]
> @jonnott because of MailgunSmtpTransport, which is the third transport available in the package. `symfony/http-client` is only needed by 2 or the 3 transports

Understand, but that doesn't make having it as require-dev make sense still.

Should it not therefore use a composer 'suggest' line, explaining that http-client is needed if you're using certain transports?

**Comment by jonnott** [comment]
> @fabpot maybe the `mailgun` scheme should fallback to SMTP rather than API if the transport factory does not have an HTTPClient (while `mailgun+api` would always force using the API) ?

I don't think that would be a sensible change.

**Comment by stof** [comment]
The suggest line makes sense (but I would add it in `symfony/mailer` rather than each mailer bridge, as it applies to any API-based or HTTP-based transport)

**Comment by nicolas-grekas** [comment]
I think the deps are fine according to our policies.
Instead of adding `suggest` line, we usually prefer throwing a LogicException telling that the component is missing.
Looks like this would be a nice idea here (and maybe in other bridges)
PR welcome!

**Comment by jonnott** [comment]
> The suggest line makes sense (but I would add it in `symfony/mailer` rather than each mailer bridge, as it applies to any API-based or HTTP-based transport)

Indeed, I was about to say exactly that .. the pattern is repeated in all the 3rd-party/API transports.

**Comment by jonnott** [comment]
> I think the deps are fine according to our policies. Instead of adding `suggest` line, we usually prefer throwing a LogicException telling that the component is missing. Looks like this would be a nice idea here (and maybe in other bridges) PR welcome!

Oh, I think it did throw a LogicException .. but I didn't see it until I checked my logs, as something odd was happening with the new `spatie/laravel-ignition` package around shutdown errors and sessions :(

Was just flagging this up, as there might be a number of similar requests from Laravel + Mailgun users when Laravel 9.0 finally releases..

**Comment by jonnott** [comment]
Here's the exception.

https://github.com/symfony/mailer/blob/5.4/Transport/AbstractHttpTransport.php#L36

Guess that's good enough..

**Comment by jonnott** [comment]
@nicolas-grekas Feel free to close!

**Comment by nicolas-grekas** [comment]
> something odd was happening with the new spatie/laravel-ignition package around shutdown errors and sessions :(

this might be the place to look at next

thanks for the discussion

**Comment by jonnott** [comment]
> this might be the place to look at next

Yeah, whatever `spatie/laravel-ignition` was getting wrong wasn't a problem for me once I'd seen the LogicException and installed HttpClient, but I'm sure it's a) tangental to this, and b) Spatie will get it fixed in time ;)
