### ISSUE TITLE
[Messenger (Redis transport)] Connection should use custom Redis instance

### ISSUE THREAD

**Issue by OO00O0O** [symfony/symfony#45057]
### Description

If I provide custom Redis instance to `Symfony\Component\Messenger\Bridge\Redis\Transport\Connection` and it's already connected, Redis goes "Server went away". Thats because(probably) its already connected.

Problem is in `symfony/redis-messenger/Transport/Connection.php:76`. There should be another elseif with `elseif ($redis && $redis->isConnected()) { $this->connection = $redis; }`

### Example

```
class MessengerTransportFactory extends RedisTransportFactory
{
    public function createTransport(string $dsn, array $options, SerializerInterface $serializer): TransportInterface
    {
         return new RedisTransport(
            new Connection([], [], [], $CUSTOM_REDIS_INSTANCE),
            $serializer
        );
    }
}
```

**Comment by chalasr** [comment]
Sounds like a bug. PR with test case welcome. Please target the lowest branch where it applies.

**Comment by nicolas-grekas** [comment]
PR welcome indeed @OO00O0O. Closing meanwhile.
