### ISSUE TITLE
"Circular reference detected for service" - autowiring interfaces

### ISSUE THREAD

**Issue by constup** [symfony/symfony#45066]
### Symfony version(s) affected

5.4.1

### Description

Having a class which implements two interfaces and which has a property type-hinted as one of the interfaces will throw the `ServiceCircularReferenceException` ("_Circular reference detected for service..._"). Creating another class which implements one of these interfaces will remove the issue.

### How to reproduce

Sample repository to show the bug and workarounds: https://github.com/constup/symfony-circular-reference-bug . The README.md file of the repository contains all details about the bug, reproduction steps, workarounds and stack trace.

**Comment by derrabus** [comment]
What would be the behavior that you would expect in this case?

**Comment by constup** [comment]
I have added the `expected` branch to the sample repository and updated the `README.md` to describe it. Here's the copy:

## Expected behavior

When a class is implementing two interfaces, with one of them being the parent of the other, only the last one should be
autowired to point to our class.

In the example (on the `bugged` branch), `TwoDimensionsInterface` is extending `MathShapeInterface`. PHP does not allow
classes to implement interfaces which are already implemented, so the header of the class must be:

```php
class Circle implements MathShapeInterface, TwoDimensionsInterface
```

PHP will throw an exception if it's the other way around:

```php
class Circle implements TwoDimensionsInterface, MathShapeInterface
```

This is why the second interface in our example is considered to be the defining interface of the class. The first 
interface is merely there for better classification purposes and to help with abstraction between different class types.

The `expected` branch of this repository contains an example of how the dependency injection compiler should behave. In
the example on the `expected` branch, the property type of the `neighborobject` is changed to a new `SampleInterface`.
There are no classes which implement the `SampleInterface`, but the compiler run is still successful. Thus, the expected
behavior for processing `MathShapeInterface` on the `bugged` branch should be the same as for `SampleInterface` in the
`expected` branch - the `MathShapeInterface` should not be autowired to the `Circle` class if a child interface of 
`MathShapeInterface` is present and the `Circle` class is implementing the child interface.

**Comment by derrabus** [comment]
> When a class is implementing two interfaces, with one of them being the parent of the other, only the last one should be autowired to point to our class.

Okay, first of all, it does not matter if you implement the parent interface directly or transitively. You class will always implemen both interfaces: https://3v4l.org/Du9MK

Secondly: no, why? Registering an autowiring alias for both interfaces is a perfectly valid thing to do. And we will break a lot of existing apps that rely on that.

> This is why the second interface in our example is considered to be the defining interface of the class.

There is no such thing as a "defining interface".

> The first interface is merely there for better classification purposes and to help with abstraction between different class types.

It's fine if you have defined those sematics for your project, but the DI component cannot make those assumptions.

And even if we did what you're suggesting, the DI component would still not be able to fulfill the dependencies of the `Circle` class. The error message would be a different one, that's all.

**Comment by constup** [comment]
@derrabus Thank you for the feedback. 

I understand that my example and explanation might not be perfectly describing the issue and that the expected behavior might be different from what I've suggested. Your suggestion to throw a different error message is completely valid as well.

My logic here is that there is an issue with the autowiring, because the issue can be resolved by simply adding a new class which implements the first interface - without changing any existing code. At least for me, this is a sign that the issue is not in user's code, but in how the autowiring works.

**Comment by derrabus** [comment]
> My logic here is that there is an issue with the autowiring, because the issue can be resolved by simply adding a new class which implements the first interface - without changing any existing code. At least for me, this is a sign that the issue is not in user's code, but in how the autowiring works.

No, that's how the service auto-discovery works. If it finds two implementations of an interface, it does not register an autowiring alias for that interface. Sorry for the nit-picking, but I believe this detail to be important if we want to discuss a solution here.

Other options for you would be to define the autowiring alias for that interface yourself or to wire the dependency of the `Circle` class explicitly. The problem is that in your code, there is no way to create a valid dependency tree for the `Circle` class. There is no implementation of the `MathShapeInterface` interface that we can wire here.

**Comment by stof** [comment]
The behavior of the PSR-4 discovery (not of the autowiring) is to register an autowiring alias for interfaces when the discovery finds both the interface definition and a single implementation of that interface. This is done to make it easier to use the discovery mechanism to register services while following the best practices of type-hinting interfaces rather than implementation. when the discovery mechanism finds multiple implementations, it cannot add the autowiring alias as it does not know which alias to add.

**Comment by constup** [comment]
Ok. I see your points.

Can you, please, leave the issue open for a couple of days? I'd like to spend some time to dig deeper into this, propose a better error message and get your feedback about it.
