### ISSUE TITLE
 Failed to extract symfony/redis-messenger

### ISSUE THREAD

**Issue by GinoPane** [symfony/symfony#45089]
### Symfony version(s) affected

5.4.2

### Description

We started getting such error during composer install after upgrading to Symfony 5.4.2

![image](https://user-images.githubusercontent.com/3897579/150328889-29caeded-7679-4390-8948-ac21fcfdb419.png)

The only plugin listed is Symfony\Flex\Flex

Symfony\Flex version is 1.18.1

Weirdly enough that running `composer install` twice seems to fix the problem

### How to reproduce

Run `composer install` for the symfony 5.4.2 project with symfony/messenger on board

**Comment by nicolas-grekas** [comment]
Can you pleas past the error message here as plain text so that we can open the link to the suggested fix?
Can you please also provide us with a reproducer we could run ourselves?

**Comment by derrabus** [comment]
Does this still happen if you remove Flex? If so, you should seek support at https://github.com/composer/composer/ instead.

**Comment by M1ke** [comment]
Possible solution for this here: https://github.com/composer/composer/issues/10379#issuecomment-1021096505

I experienced this with different Symfony packages but the error looks similar; issues with zip files appearing corrupted.

**Comment by LBT76240** [comment]
Hello. I've got the same issue and this fixed it https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb#commitcomment-64720571

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
