### ISSUE TITLE
Process/ExecutableFinder doesn't consult PATH when open_basedir is set

### ISSUE THREAD

**Issue by timwhitlock** [symfony/symfony#45082]
### Symfony version(s) affected

6.1

### Description

When searching for executables the `open_basedir` setting is assumed to contain all executable roots. As such it is consulted **instead** of `PATH`. 

This only works if you've explicitly added executable roots to `open_basedir`. It won't work if you've added a higher level directory, even if you've added the enclosed directories to your `PATH`.

Related code: https://github.com/symfony/process/blob/6.1/ExecutableFinder.php#L49-L67 

### How to reproduce

Set `open_basedir` to any directory that would require a recursive search in order to find an executable under a `PATH` location like `/usr/local/bin`; e.g. (1) `open_basedir=/` or (2) `open_basedir=/usr/local`.

This might be non-standard, but I was caught out by (1). For whatever reason "/" was in my php.ini. 

The latter (2) would allow execution under `PATH=/usr/local/bin` but the environment variable is not consulted, so executables there will never be found.

### Possible Solution

Merging the `PATH` locations AND the `open_basedir` locations would produce a fuller list of search paths. I see no reason to exclude `PATH`. Anything not under `open_basedir` would simply be discarded due to lack of permissions.

**Comment by stof** [comment]
See the discussion on https://github.com/symfony/symfony/issues/41006 in which I suggest the correct solution.

`open_basedir` should not be used to provide search paths but to *filter* them

If you can work on the fix, contributions are welcome

**Comment by timwhitlock** [comment]
Thanks for the link. I don't have time to contribute. I've closed my issue, but feel free to re-open if appropriate.

As an aside for anyone searching for the same problem: I encountered this when Composer was failing to find the `unzip` command. This produces warnings that the PHP Zip extension will be used as a fallback. My workaround was to set an empty `open_basedir`.
