### ISSUE TITLE
[Form] Add inputmode=email/numeric/search/tel to form types

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#45099]
### Description

`inputmode` is an HTML atttibute for `<input>` tag that improve the UX on mobile by displaying an appropriate virtual keyboard based on the expected input. [Reference on MDN](https://developer.mozilla.org/docs/Web/HTML/Global_attributes/inputmode)

![image](https://user-images.githubusercontent.com/400034/150431488-f90e8a3f-8cf2-4951-b7b1-cb2e91b115bd.png)

This attribute is already set on `UrlType`, only when `default_protocol` is configured (why?).

It should be added to other:
- `EmailType`
- `NumberType`
- `SearchType`
- `TelType`

**Comment by stof** [comment]
That's done because `<input type="email">` does **not** need an explicit `inputmode=email`. Browsers already do it.

When `default_protocol` is set, the UrlType renders as a `<input type=text>`, which is why we add `inputmode`.

**Comment by stof** [comment]
See https://github.com/symfony/symfony/pull/36869 which reverted precisely the PR you are doing here (which is the same than https://github.com/symfony/symfony/pull/34986)

**Comment by welcoMattic** [comment]
Ok for `email`, `search` and `tel` types, but it's still relevant for `NumberType` for which the `inputmode` must be explicitly set, right?

**Comment by stof** [comment]
For a NumberType with the `html5` option set to false, this might indeed be useful.
