### ISSUE TITLE
[Mime] Improve or document `In-Reply-To` and `References` headers

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#45097]
### Description

As @micheh reports, since https://github.com/symfony/symfony/pull/44732 it's more complicated to add an `In-Reply-To` or `References` header, since you have to take care of the brackets `<...>` yourself, see https://github.com/symfony/symfony/pull/44732#issuecomment-1003340733

* I could try to create a PR for something like `->addRelaxedIdHeader()` that adds the brackets, but doesn't validate the content
* Or I could just document the status-quo and tell people to add the brackets themselves: https://symfony.com/doc/current/mailer.html#message-headers

What do you think?

**Comment by ThomasLandauer** [comment]
Better idea if it's going to be the PR: Add an optional third argument `bool $validate=true` to [`addIdHeader()`](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Mime/Header/Headers.php#L98)

**Comment by fabpot** [comment]
@ThomasLandauer I think you can go with the validate argument on addIdHeader().
