### ISSUE TITLE
Default `Kernel.php` is not loading framework.yaml

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#45100]
### Symfony version(s) affected

6.0.2

### Description

After installing Symfony like explained at https://symfony.com/doc/current/setup.html#creating-symfony-applications
```bash
composer create-project symfony/skeleton my_project_directory
```
... my `Kernel.php` looked like this:
```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;
}
```
But my `framework.yaml/.php` was completely ignored, and I had to include this (copied from a previous Symfony project):
```php
private function configureContainer(ContainerConfigurator $container): void
{
    $container->import('../config/{packages}/*.yaml');
    $container->import('../config/{packages}/'.$this->environment.'/*.yaml');

    $container->import('../config/{packages}/*.php');
    $container->import('../config/{packages}/'.$this->environment.'/*.php');

    if (is_file(\dirname(__DIR__).'/config/services.yaml')) {
        $container->import('../config/services.yaml');
        $container->import('../config/{services}_'.$this->environment.'.yaml');
    } elseif (is_file($path = \dirname(__DIR__).'/config/services.php')) {
        (require $path)($container->withPath($path), $this);
    }
}
```
Is this the expected behavior?

### How to reproduce

See above.

**Comment by kbond** [comment]
It makes sense framework.php isn't being loaded as the [method in micro kernel](https://github.com/symfony/symfony/blob/2c91390bce5e1eeb7dc3e3d24166c4d2cb9de971/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L49) doesn't load Php package config files. I can't see why framework.yaml isn't being loaded for you though.

**Comment by ThomasLandauer** [comment]
Ping @javiereguiluz It's in fact a documentation problem. At https://symfony.com/doc/current/configuration.html#configuration-formats it says:

> By default Symfony only loads the configuration files defined in YAML format. If you define configuration in XML and/or PHP formats, update the src/Kernel.php file to add support for the .xml and .php file extensions.

* This needs to be a caution box (not just some note). That's probably the reason why I missed it yesterday ;-) 
* More important: *How* to update the Kernel? => There should be a copy-pastable code.

---

Here's step-by-step reproducer (not very interesting anymore, but I've already written it, so I'm posting it ;-)

```bash
composer create-project symfony/skeleton symfony-issue-45100
cd symfony-issue-45100
```
Add this to `services.yaml`:
```yaml
        bind:
            $secret: '%kernel.secret%'
```
Reduce `framework.yaml` to:
```yaml
framework:
    secret: '%env(APP_SECRET)%'
```
Now some simple Command:
```php
<?php declare(strict_types = 1);
namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MyCommand extends Command
{
    protected static $defaultName = 'app:my_command';

    public function __construct(private string $secret)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        echo $this->secret;
        return 0;
    }
}
```
This now works as expected. But then replace `framework.yaml` with `framework.php`:
```php
<?php
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $framework->secret('%env(APP_SECRET)%');
};
```
Now:
```bash
php bin/console app:my_command
```
Output:

> In DefinitionErrorExceptionPass.php line 54:
> You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"?

**Comment by stof** [comment]
> * More important: _How_ to update the Kernel? => There should be a copy-pastable code.

this doc has been written before the changes done in MicroKernelTrait in 5.4 or 6.0, when the code to update was part of the kernel added by the recipe.

**Comment by ThomasLandauer** [comment]
Continuing in a separate issue: https://github.com/symfony/symfony/issues/45116
