### ISSUE TITLE
PHP Session Cookie gets set despite setting use_cookies = false

### ISSUE THREAD

**Issue by hoebelix** [symfony/symfony#45105]
### Symfony version(s) affected

5.4

### Description

Similar as in https://github.com/symfony/symfony/issues/13668, I have a small AP and I need to maintain a session without using cookies. In my case, the client passes the session ID in a custom HTTP header.

The PR https://github.com/symfony/symfony/pull/15123 added support for this use case. But despite the setting use_cookies: false, Symfony sets a PHP session cookie. This seems to be the case at least since commit https://github.com/symfony/symfony/commit/b3e4f6657c0c47e1b5ba85e4554a3c273ee61066

This commit also seems to always read the session id from the cookies - independently of use_cookies = false.

### How to reproduce

In framework.yaml set

```yaml
framework:
    session:
        use_cookies: false
```

and somewhere in a controller read the session via

```
$request->getSession()->all()
```

**Comment by sergnik1995** [comment]
Experiencing this bug too

**Comment by alexander-schranz** [comment]
Think a simple check in the listener should fix it. Can you give #45964 a try?
