### ISSUE TITLE
Messenger should not have hard-coded dependencies on any implementations

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#45121]
### Description

Installing `symfony/messenger` carries with it obligatory dependencies on all of the following:

* `symfony/redis-messenger`
* `symfony/doctrine-messenger`
* `symfony/amqp-messenger`

This is true even for my application which uses beanstalkd and thus needs none of the above. These dependencies should be optional.

**Comment by ghost** [comment]
Please take a look at the composer.json file for Symfony Messenger on the master branch.

**Comment by Bilge** [comment]
OK, so what you mean is it's fixed in v6.
