### ISSUE TITLE
Thick double-row WDT toolbar covers bottom of page, unreachable by scrolling

### ISSUE THREAD

**Issue by php4fan** [symfony/symfony#45136]
### Symfony version(s) affected

5.4.0

### Description

Normally, the WDT doesn't cover the bottom of the page.
Somehow it adds to the height of the body, so that you can always scroll to the bottom and see every last bit of html content in the page _above_ the WDT. That's the expected behavior.

However, this breaks when the available width becomes too small and the WDT starts occupying two rows (e.g. on mobile devices).
Note that, regardless of bug 45135, where sometimes the WDT _unnecessarily_ splits into two rows, it will still _legitimately_ occupy two rows sometimes.

When it does, the body height seems to be somehow only adjusted for one of the two rows. The additional one row of space taken up by the WDT covers up page content at the bottom of the page and you cannot scroll further down to make that content visible.

Here are some screenshots:

![image](https://user-images.githubusercontent.com/13969584/150691362-52120bff-3ccc-45d8-b64a-74379437c425.png)

![image](https://user-images.githubusercontent.com/13969584/150691387-518ad485-e4b1-4d1f-8d8d-9d0e8e008aae.png)

### How to reproduce

- have a long enough page
- enable the WDT
- shrink the window until the WDT occupies two rows

**Comment by stof** [comment]
I don't see any easy fix for that. As the toolbar is extendable, we cannot know at which screen width the toolbar will overflow its line, to increase the size of the spacer element added in the flow to make the scroll big enough to show the content above the WDT..

**Comment by fabpot** [comment]
Closing as a won’t fix then. Thanks for reporting.

**Comment by php4fan** [comment]
You give up just because it's not easy??

If there really isn't a possible solution (which I find hard to believe - I mean at the very worst you would have to use javascript), then I'd suggest you double the height of the spacer. It's certainly better to have unnecessary extra space at the bottom, than to be unable to see the content at the bottom (and I'm pretty sure it'll only get to three rows in very extreme cases).

**Comment by nicolas-grekas** [comment]
Please send a PR if you can, that's going to be the most effective. (same on the other issue)
