### ISSUE TITLE
Web debug toolbar unnecessarily switches back and forth between one and two rows height as window width shrinks

### ISSUE THREAD

**Issue by php4fan** [symfony/symfony#45135]
### Symfony version(s) affected

5.4.0

### Description

Here are a series of screenshots of the Web Debug Toolbar at **decreasing window widths**.

There's definitely some unnecessary switching back and forth between one and two rows.
If everything can fit in a row both in the first and third screenshot, there's no reason it cannot fit in one row in screenshot 2 which is an intermediate size.

Also, at screenshot 4 it seems unnecessary to move the Server item to the next row, given that the username item could shrink more (and screenshot 5 proves it can).

Additionally, it could be argued that it's unnecessary to *ever* split the two rightmost items into two separate rows, because, if you need one additional row, you might as well move both of them to the second row together (that is, make the {server, version} pair unbreakable). But that might be subject to taste.

Yoy may also notice that, when it occupies two rows, it covers page content making the bottom of the page unreachable by scrolling, but I'll report that as a separate issue.

![image](https://user-images.githubusercontent.com/13969584/150690361-454eba1f-02d2-42cf-bc9a-7e7f80e9ea80.png)

![image](https://user-images.githubusercontent.com/13969584/150690369-e4a3d1e7-9759-404c-89b9-c1a3efcba5e1.png)

![image](https://user-images.githubusercontent.com/13969584/150690377-ddbe4541-b504-4219-8dbb-cfdca82d8e32.png)

![image](https://user-images.githubusercontent.com/13969584/150690403-f1809b55-ca34-4f02-a62d-3d71f5089ec7.png)

![image](https://user-images.githubusercontent.com/13969584/150690410-427dc3e2-d740-4cfc-8113-9d5a2842d4e9.png)

![image](https://user-images.githubusercontent.com/13969584/150690417-cd57995d-d281-450f-bc7a-27c49073d6b2.png)

### How to reproduce

Enable the Web Debug Toolbar.
Gradually shrink window width and watch.

**Comment by fabpot** [comment]
Closing for the same reason as your issue on the same topic

**Comment by php4fan** [comment]
This is a completely different issue than the other one and this one definitely can be fixed.

**Comment by stof** [comment]
this looks related to the server block being injected for the symfony-cli, that was not taken into account when building the responsive behavior of the toolbar.

**Comment by stof** [comment]
or maybe it is indeed just the same kind of issue than #45136 where this jump would depend on the number of items in the toolbar
