### ISSUE TITLE
[Console] @usage full command examples

### ISSUE THREAD

**Issue by Sweetchuck** [symfony/symfony#45132]
### Description

Currently every `@usage` example is automatically prefixed with the command name and the executable is left out from the output.
```php
$c = new Command('my:cmd:01');
$c->addUsage('--foo');
```

`$ my-app help my:cmd:01`
```
Usage:
  my:cmd:01 --foo
```

I would like to add more complex examples, which are:

1. copy-paste ready. Which means the executable (`my-app`) is also included.
2. `my-app my:cmd:01` is not the first part of the full command.
    For example: `cat x.txt | my-app my:cmd:01 --how-to-handle-the-stdinput=bar`
3. or `my-app my:cmd:01 | xargs ...`
4. or `echo "prefix $(my-app my:cmd:01) suffix"`

### Example

I don't know how to achieve all of the above with backward compatibility, but maybe the same way as [Git alias](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases) uses the leading `!` exclamation mark.
```php
$c = new Command('my:cmd:01');
$c->addUsage('!echo "prefix $({{ executable }} my:cmd:01) suffix"');
```
`$ my-app help my:cmd:01`

```
Usage:
  echo "prefix $(my-app my:cmd:01) suffix"
```

**Comment by Sweetchuck** [comment]
Related Issues:

* #45050

**Comment by wouterj** [comment]
Hi! For reference (what I also said in the other issue), we're trying to follow [docopt standards](http://docopt.org/) in the help output.

Whereas I can see the use of adding short descriptions to usage, I'm leaning more towards :-1: for this feature request. The usage part is meant to show commonly used arguments or combinations of options *for the current program*.

Information like how you can combine this with other methods is meant to be placed in the help message, together with maybe a nice explanation. You can find many examples of this in Symfony's own commands, e.g. https://github.com/symfony/symfony/blob/1ebb5d9605ffecf23124413ea6bde729a223e610/src/Symfony/Bridge/Twig/Command/LintCommand.php#L58-L75
