### ISSUE TITLE
[TwigBridge] Make `dump()` a no-op if DebugBundle is unavailable

### ISSUE THREAD

**Issue by m-vo** [symfony/symfony#45141]
### Description

Twig's `dump()` function is only available if the `DebugBundle` is loaded. As this isn't the case in `prod`, a leftover (or intentionally left in) `dump()` will make the template fail for no directly obvious reason.

For reference see https://github.com/symfony/symfony-docs/issues/7937 where @weaverryan commented on an old version of the docs that seemed to suggest this was possible and would just not output anything.

Would you be up for going in this direction again? We could for instance handle this case gracefully in the `UndefinedCallableHandler` and make it a no-op rather than throwing a `SyntaxError`. IMHO this would make for a better DX.

### Example

```twig
Looks like nothing should go wrong in prod.
{{ dump('foo') }}
```

**Comment by derrabus** [comment]
I'm not sure if this is the right way. Ideally, you should not have `debug()` calls in templates you deploy to production. Maybe the better approach would be tooling that detects those calls and could let a CI build fail?

**Comment by m-vo** [comment]
Yes, I would consider that for my projects, but there are IMHO use cases where this would be over the top. For example, over at @contao, templates are edited by people that are no developers. 

Also, this makes toggling between `dev` and `prod` (locally during development) harder than it should, no? :slightly_smiling_face: And I think, errors that only appear in `prod` are to be avoided in general.

**Comment by derrabus** [comment]
> templates are edited by people that are no developers.

Okay, but I believe that you can explain to those non-developers that they can use `dump()` as a local debugging tool but should remove them before merging to the main branch.

Keep in mind, that you can still define a `my_dump()` function that behaves the way you want. And if for your codebase, committing debug code is acceptable, this is completely your decision.

But I still don't feel like we should actively allow this.

> errors that only appear in `prod` are to be avoided in general.

I agree, that's why I brought up detecting those calls in CI. Silent deactivation of functionality on the other hand is also a problem. If a (non-)developer used that function in a template without any effect or feedback on why the dump feature is disabled, they might get pretty frustrated soon.

**Comment by fritzmg** [comment]
> Okay, but I believe that you can explain to those non-developers that they can use `dump()` as a local debugging tool but should remove them before merging to the main branch.

It's not about that. These non-developers need to be able to use the function in `prod` mode. In the Contao Content Management System users can use a specific function in their Contao PHP templates in order to view the available template variables they can use. This function then uses Symfony VarDumper internally and this works regardless of `dev` or `prod`. Since Contao now supports Twig templates for everything we need an equivalent function for that - which would be `{{ dump() }}`.

**Comment by derrabus** [comment]
> In the Contao Content Management System users can use a specific function in their Contao PHP templates in order to view the available template variables they can use. This function then uses Symfony VarDumper internally and this works regardless of `dev` or `prod`.

Okay, but that sounds to me like your "specific function" has a slightly different purpose than our `dump()` function. And it also sounds like a no-op dump function as suggested initially is not desired in your context.

My suggestion would be that Contao provides its own Twig extension with an equivalent of the function that you used to have for your PHP templates.

**Comment by fritzmg** [comment]
> your "specific function"

There is also `dump()` which Symfony VarDumper provides and also works anywhere, independent from `dev` or `prod`.

**Comment by derrabus** [comment]
> There is also `dump()` which Symfony VarDumper provides and also works anywhere, independent from `dev` or `prod`.

Yes, and it actually dumps. It's not a no-op.

**Comment by fritzmg** [comment]
Yes, and I would argue `{{ dump() }}` in Twig should behave no different than `<?php dump(…) ?>` in PHP. At least I see no reason why it should.

**Comment by m-vo** [comment]
For Contao, we can sure register our own no-op `dump()` function in our managed edition in `prod`. I opened this issue to get a discussion going if we want to change this behavior in Symfony in general, because - to me - this would be favorable anyway. 

IMHO which debug function is registered or whether it should output something in `prod` is a different topic. I was primarily concerned about not throwing an exception in this case. But no hard feelings. @derrabus, feel free to close this issue if you think that's not in line with what Symfony developers should expect.

**Comment by derrabus** [comment]
> Yes, and I would argue `{{ dump() }}` in Twig should behave no different than `<?php dump(…) ?>` in PHP. At least I see no reason why it should.

My point exactly. If the dump function is registered, it should really dump. So we agree that we don't want the suggested no-op solution. Next question then: If you want the function to be registered in Prod, why don't you register DebugBundle in prod?

**Comment by fritzmg** [comment]
> If you want the function to be registered in Prod, why don't you register DebugBundle in prod?

`prod` should not register things like `DumpDataCollectorPass`, `RemoveWebServerBundleLoggerPass`. The problem is that the presence of the `dump()` twig function is currently tied to the `DebugBundle`, while Symfony VarDumper's dump() shim is not for example.

**Comment by wouterj** [comment]
There is a significant difference between enabling `debug` mode in a Symfony application (which is a kernel setting) and enabling the DebugBundle (which is a bundle).

As you can see in https://github.com/symfony/debug-bundle , the bundle really has one function: integrating VarDumper in the Symfony framework (i.e. twig, monolog, profiler, etc).

Btw, the classes you mention are compile passes. Among other things, these classes determine whether or not services should be registered (e.g. they register all sorts of debug features when debug is enabled). It is no issue that these are enabled, as these will not be used during runtime.
