### ISSUE TITLE
[Form] Testing a collection of forms fails with InvalidArgumentException : Unreachable field

### ISSUE THREAD

**Issue by steve-todorov** [symfony/symfony#45150]
### Symfony version(s) affected

2.4+, including latest 6.1

### Description

I seem to have stumbled upon a bug in the [FormFieldRegistry](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/DomCrawler/FormFieldRegistry.php#L79) which prevents me from doing functional form tests. 

In my case, I have a `CollectionType` field (i.e. `payments`) which contains another `form type`. 
When you use the `crawler` to fetch the form and then do `$form->setValues($formDataArray)` you will get :

```
InvalidArgumentException: Unreachable field 'payments'
```

This is happening, because the `FormFieldRegistry#get()` method throws an exception when the field you are trying to fetch doesn't exist. In this particular situation the field **WILL NOT** exist when you have `allow_add: true` set for the `payments` field. It will be missing on new entries as well (i.e. creating a new invoice payment).

### How to reproduce

Consider the following form types:

```php
class InvoiceFormType extends Symfony\Component\Form\AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('client', NumberType::class, array('label' => 'Client ID', 'required' => true))
            ->add('transactionNumber')
            ->add('payments', CollectionType::class, [
                'entry_type' => PaymentFormType::class,
                'entry_options' => [ 'label' => false ],
                'allow_add' => true,
                'allow_delete' => true,
                'delete_empty' => true,
                'error_bubbling' => false,
                'constraints' => [
                    new Constraints\Count(['min' => 1]),
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([ 'data_class' => null, 'error_bubbling' => false ]));
    }

    public function getBlockPrefix()
    {
        return 'invoice_form';
    }
}


class PaymentFormType extends Symfony\Component\Form\AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('amount', NumberType::class, ['constraints' => [new Constraints\Required()]])
                ->add('note', TextareaType::class, ['required' => false ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Payment::class,
            'error_bubbling' => false,
            'constraints' => [new Constraints\Valid()],
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'payment_form';
    }
}

```

And the following code for the unit test:

```php
private function createPaymentViaForm()
{

        $createPaymentLink = $this->generateUrl('invoice_payments_create');
        $crawler = $this->authenticatedClient->request('GET', $createPaymentLink);

        $form = $crawler->filter('form')->form();

        $paymentData = [];
        $paymentData['invoice_form[client]'] = 1234;
        $paymentData['invoice_form[transactionNumber]'] = "12346";

        $i = 0;
        foreach ($invoices as $invoice) {
            $paymentData["invoice_form[payments][$i][amount]"] = $invoice['amount'];
            $paymentData["invoice_form[payments][$i][note]"] = $invoice['note'];
            $i++;
        }

        $form->setValues($paymentData);

        $this->authenticatedClient->submit($form);
}

public function testCreateAndShow()
{

        $invoicePayments = [
            [ 'amount' => 101, 'note' => 'Node 1'],
            [ 'amount' => 102, 'note' => 'Note 2'],
            [ 'amount' => 103, 'note' => 'Note 3'],
        ];

        $this->createPaymentViaForm($invoices);

        $route = $this->generateUrl('finance_payments');
        $crawler = $this->authenticatedClient->request('GET', $route);
        $tableRows = $crawler->filter('#paymentRecords tr');
        static::assertGreaterThanOrEqual(count($invoicePayments), $tableRows->count());
}
```

### Possible Solution

The [`FormFieldRegistry#set`](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/DomCrawler/FormFieldRegistry.php#L126) method should not be throwing an exception when the field is not initialized.

Right now it's using the `get()` method, which is causing the problem, because it throws an exception when the field is missing.
However, as I mentioned above, the field might not have been initialized yet which is a valid case for dynamic forms where you have `allow_add / allow_delete`. In this case, calling [`FormFieldRegistry#set`](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/DomCrawler/FormFieldRegistry.php#L126) should initialize the field instead of throwing an exception.

**Comment by alexislefebvre** [comment]
Did you try to modify the raw values? See https://github.com/symfony/symfony/issues/4124#issuecomment-13229362 or https://github.com/symfony/symfony-docs/pull/6427/files

**Comment by steve-todorov** [comment]
Does not really work - will fail with `Form must not contain additional data` due to the `CSRF` token. When you remove it then it'll complain `Invalid CSRF token`. Also for some weird reason the form decides to validate `Entity` fields which are not even part of the form (not included at all).

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by steve-todorov** [comment]
Hey @xabbuh ,

Sorry for the late reply - been a busy week.
I've added an example repository ([steve-todorov/symfony-45150](https://github.com/steve-todorov/symfony-45150)) and a test which replicates the issue above. You can use the docker-compose in Idea to provide the exact environment as mine. There's also a [github action job](https://github.com/steve-todorov/symfony-45150/runs/5084890741?check_suite_focus=true) which reproduces the issue as well.

Running the test will result in the mentioned exception:
![image](https://user-images.githubusercontent.com/2303663/152692281-e518d7ea-5eff-4b55-80f9-f31fa3934247.png)

If you need to run the code in the browser -- you can use the `/example` endpoint which has some js for doing the test (it works fine there)

Note: I'm using an older version of Symofony, because I took the code from an existing application. I'm pretty sure this issue has been around since Symfony 2.2 and is present in latest versions, because the code in `FormFieldRegistry` hasn't changed (as mentioned in the issue description).

**Comment by steve-todorov** [comment]
@xabbuh ping, I was just wondering if you had a chance to check this out? :)

**Comment by xabbuh** [comment]
Sorry for the late response. I now managed to look into your example application. Thanks for that. It made it quite easy to understand your issue. 👍  What happens here looks correct to me. The `FormFieldRegistry` from the `DomCrawler` component does not know anything about the inner structure of your form types. It only inspects the rendered DOM. And here there is no `payments` field as that's not rendered by the form theme. You probably have some JavaScript code that would be executed by a real browser to dynamically add more HTML forms. There is no way to achieve that with pure DomCrawler/BrowserKit related code. You will either have to simulate the request that is sent by a real client (thus not using the form-related interface provided by the Crawler) or switch to a test client that is capable to interact with a real (headless) browser and thus being able to execute some client-side JavaScript.

In any case,  there is nothing we can do here on Symfony's side. So I am going to close here. Thank you for understanding.

**Comment by steve-todorov** [comment]
@xabbuh thanks for your reply. I cannot agree that this is "correct" or "expected" behavior. 

While the form in the front-end is indeed dynamic and you can use JavaScript to add/remove in the missing  on demand -- that is not possible when you are running test cases. 

What you suggest is the same as what @alexislefebvre mentioned a few comments above ([here](https://github.com/symfony/symfony/issues/45150#issuecomment-1022306807)):

```
// taken from https://github.com/symfony/symfony/issues/4124#issuecomment-13229362

$form = $crawler->selectButton('save')->form();
$form->setValues(array(
    'customer_invoice_form[customer]' => 'C0001',
    'customer_invoice_form[address]'  => "274 Rose avenue US\n212-35 OKMontgomery",

    'customer_invoice_form[items][0][number]'        => 1,
    'customer_invoice_form[items][0][label]'         => 'Domainreg bar-foo.com',
    'customer_invoice_form[items][0][period][start]' => '01-01-2013',
    'customer_invoice_form[items][0][period][end]'   => '01-12-2013',
    'customer_invoice_form[items][0][price]'         => '20,00',
    'customer_invoice_form[items][0][taxPercent]'    => '21,10',
));

// Now do what ever you want with the $values.
$values = $form->getPhpValues();
unset($values['customer_invoice_form']['items'][1]);

$client->request($form->getMethod(), $form->getUri(), $values, $form->getPhpFiles());
//$client->submit($form);
```

This, whoever does not work as I have already mentioned in my comment [here](https://github.com/symfony/symfony/issues/45150#issuecomment-1024347207). 


Please revisit your decision to close this ticket or if you know a workaround let me know? 
Maybe use the code from my example repo? I might be missing something..

**Comment by stof** [comment]
@steve-todorov it is possible to execute JS in tests if you use a tool that supports that. So if you use Panther (or another Selenium-based tool), you will be able to have the JS executed, to simulate the click on your `add` button.

**Comment by PabloKowalczyk** [comment]
@xabbuh using JS does not solve the problem (not using `FormFieldRegistry` would solve), https://symfony.com/doc/current/reference/forms/types/collection.html#adding-and-removing-items just add new field, but new field doesn't exist in original response so `FormFieldRegistry` still throws. Is there any way to test collection with `allow_add` or maybe it is a bug in `FormFieldRegistry`?

**Comment by damienalexandre** [comment]
Agreeing with @PabloKowalczyk & @steve-todorov - this is a real issue from my point of view. Using a "real browser" is not really helpful - it means adding a huge complexity to the project testing when we rely on phpunit only.

Symfony provides the CollectionType, the Crawler and the Form testing utilities in browser-kit, so we should find a way to test forms with `allow_add` via those included tools. I'm not saying it's possible / easy, just that in a perfect world the framework should allow us to add the fields / collection entries like that in our tests:

```php
 $form->setValues(array(
    'customer_invoice_form[customer]' => 'C0001',
    'customer_invoice_form[address]'  => "274 Rose avenue US\n212-35 OKMontgomery",

    'customer_invoice_form[items][0][number]'        => 1,
    'customer_invoice_form[items][0][label]'         => 'Domainreg bar-foo.com',
    'customer_invoice_form[items][0][period][start]' => '01-01-2013',
    'customer_invoice_form[items][0][period][end]'   => '01-12-2013',
    'customer_invoice_form[items][0][price]'         => '20,00',
    'customer_invoice_form[items][0][taxPercent]'    => '21,10',
));
```

Hope this can be re-opened / considered. Thanks!

## Workaround

Here is an updated workaround that works for me. You have to build your "collection entries" in the PHP Values array. Not in the Form Values.

```php
$form = $crawler->selectButton('save')->form();
$form->setValues(array(
    'customer_invoice_form[customer]' => 'C0001',
    'customer_invoice_form[address]'  => "274 Rose avenue US\n212-35 OKMontgomery",
));

$values = $form->getPhpValues();

$values['customer_invoice_form']['items'][] = [
  'number' => 1,
  'label' => 'Test',
  'price' => '20,0',
];

$crawler = $client->request($form->getMethod(), $form->getUri(), $values, $form->getPhpFiles());
```
