### ISSUE TITLE
[Dotenv] Allow swapping out defaults with real env var values for dump-env

### ISSUE THREAD

**Issue by adioe3** [symfony/symfony#45169]
### Description

Provide a flag which would make the `dump-env` command check if the environment variable exists in the current environment and use that value instead of the default value provided in `.env`.

The practical use case here is values composed of other values, for example a DSN might be defined as so:

```ini
# .env
DB_USER=root
DB_PASS=root
DB_HOST=localhost
DB_PORT=3306

DSN="mysql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT"
```

Now say we have the host and user in the env:

```sh
export DB_USER=mysql
export DB_HOST=192.168.0.25
```

Dumping the vars we get;

```sh
$ composer dump-env -- prod
Successfully dumped .env files in .env.local.php

$ cat .env.local.php
<?php

// This file was generated by running "composer dump-env prod"

return array (
  'DB_USER' => 'root',
  'DB_HOST' => 'localhost',
// ...
```

which would now break database connections since the DSN isn't using the environment values.

Since `.env` is easier for configuring multiple environments as opposed to having multiple files in `config/packages/<env>/<bundle>.yml` this would be a really nice convenience.

### Example

Simple `--with-env-values` or `--use-env-values` flag would be great so that given the above configuration we can:

```sh
composer dump-env --with-env-values -- prod
```

and end up with 

```sh
$ cat .env.local.php
<?php

// This file was generated by running "composer dump-env prod"

return array (
  'DB_USER' => 'mysql',
  'DB_HOST' => '192.168.0.25',
// ...
```

**Comment by nicolas-grekas** [comment]
Real env vars already override .env vars.
The issue here is that DSN references other env vars, and dump-env resolves .env vars from .env files only.
Dumping the values from the env would defeat the purpose of env vars.

There are two ways forward here:
- create a real DSN env var
- remove the DSN var and do the interpolation in a parameter in config/services.yaml.
