### ISSUE TITLE
[Console] `PHP 8.1` PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#45179]
### Symfony version(s) affected

6.0.2

### Description

Hi,

With **Symfony/Console 6.0.2** and **PHP 8.1**, there is a depreciation on the method [Symfony\Component\Console\Question\ChoiceQuestion::getDefaultValidator()](https://github.com/symfony/console/blob/v6.0.2/Question/ChoiceQuestion.php#L133) (click on the link to see the line of the issue) : 

```
PHP Deprecated : trim() : Passing null to parameter #1 ($string) of type string is deprecated.
```

This happens when the default value for the question is `null`.

### How to reproduce

```php
// Method definition : https://github.com/symfony/console/blob/v6.0.2/Style/SymfonyStyle.php#L277
$io->choice('Select the queue to analyze', ['queue1', 'queue2', 'queue3']); // The 3rd argument must be `null`.
```

### Possible Solution

We can simply cast the variable to string to fix the issue. Just like this [at this line](https://github.com/symfony/console/blob/v6.0.2/Question/ChoiceQuestion.php#L133):
```diff
-$selectedChoices[$k] = trim($v);
+$selectedChoices[$k] = trim((string) $v);
```

**Comment by chalasr** [comment]
Hi, can you send a PR on ~~6.0~~ 4.4 with test case?

**Comment by ghost** [comment]
> Hi, can you send a PR on 6.0 with test case?

@chalasr This my first contribution for Symfony, did I forget something? 
[Link to the PR](https://github.com/symfony/symfony/pull/45181)

Regards

**Comment by mathmul** [comment]
> ### Possible Solution
> We can simply cast the variable to string to fix the issue. Just like this [at this line](https://github.com/symfony/console/blob/v6.0.2/Question/ChoiceQuestion.php#L133):
> 
> ```diff
> -$selectedChoices[$k] = trim($v);
> +$selectedChoices[$k] = trim((string) $v);
> ```

Or `trim($v ?? '')`
