### ISSUE TITLE
[TwigBridge] Make usage of TranslatableInterface even simpler

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#45180]
### Description

The introduction of `TranslatableInterface` and the `TranslatableMessage` implementation is amazing but it can be improved :)

Right now you have to use it like this as per https://symfony.com/blog/new-in-symfony-5-2-translatable-objects

```
<?php
use Symfony\Component\Translation\TranslatableMessage;

return $this->render('...', [
    'order_status' => new TranslatableMessage(
        'order.status_message',
        ['%status%' => $order->getStatus(), '%order_id%' => $order->getId()],
        'admin'
    ),
]);
```

And with Twig
```
{{ order_status|trans }}
```

There are 2 issues with this usage with Twig:
1. `|trans` is required so the `TranslatableExtension` calls the `TranslatableInterface::trans()` method but this piece of code doesn't add any value: there is no point to use a `TranslatableInterface` without actually translating it in the template
2. There is no exception/warning/error message if you forget to add `|trans` as Twig will silently call the `TranslatableInterface::__toString()` method: this can lead to a software bug quite difficult to detect with automated tests

### Example

The Twig bridge should make it possible to just use `{{ order_status }}` and still get the `TranslatableInterface` translated.

I'm no Twig expert but I think that the `EscaperExtension` responsible to call the `TranslatableInterface::__toString()` within the `twig_escape_filter()` function can be somehow decorated by the Twig bridge.

What do you think?

**Comment by ro0NL** [comment]
I tend to like explict `|trans` in templates, but i agree it could be an optional no-op :)

Im not sure how this should be integrated in twig, but we may have a look at #44937 while at it :angel: (the html-safe case that is)

**Comment by stof** [comment]
The issue with making it optional is that the only way to implement this is to wrap **all** Twig PrintNode (the `{{ }}` in the template) into a function call detecting the usage of a TranslatableInterface as the printed value and eventually call the translator. There is no way to do this detection at compile time, as Twig variables are not strongly typed (and never will). This would add overhead on **all** printed element. This is not justified IMO. It would have a benefit only if the vast majority of your print nodes are about printing a TranslatableInterface instance (where you would add a `|trans` anyway without that auto-translation).

**Comment by sylfabre** [comment]
Thank you @stof for the explanation, and I agree that this overhead is not justified.

I'm just looking for ways to prevent dev from making mistakes :)

**Comment by stof** [comment]
Well, trying to do `{{ order_status }}` where `order_status` is a TranslatableInterface will probably report an error about the object not being castable to string. This will tell them that they did a mistake.

**Comment by sylfabre** [comment]
@stof actually this works as TranslatableMessage implements a __toString() method that is used by twig.
So it silently fails hence this issue...

**Comment by fabpot** [comment]
Let's close as there is no way I can think of to do something that won't slow things down too much.

**Comment by sylfabre** [comment]
Thank you @fabpot @ro0NL@stof for looking into it!

**Comment by stof** [comment]
hmm, maybe TranslatableMessage should not be stringable.

**Comment by sylfabre** [comment]
@stof That would help as it would trigger this exception
> Object of class Symfony\Component\Translation\TranslatableMessage could not be converted to string

Would you accept a PR to remove this method from TranslatableMessage?
But it may break BC so it should wait for SF 7: do you have a way to log it somewhere?

**Comment by ro0NL** [comment]
Im not sure that's worth it for just this twig issue. Being able to pass around translatable objects where stringables are supported is generally useul, to then act upon _certain_ stringables.
