### ISSUE TITLE
[HttpClient] Improve PSR logger integration

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#45194]
### Description

For Symfony's http-client it would be nice to have log levels based on response, as well as custom message formatting. As a follow up of #30537

We currently rely on it in other frameworks, but i like to have SF-everything :)

- https://github.com/php-http/logger-plugin/blob/665b13e726ffe8a17ab04d4b940e4a32bd54b38b/src/LoggerPlugin.php#L32-L74
- https://github.com/guzzle/guzzle/blob/de6f1e58e735754b888649495ed4cb9ae3b19589/src/Middleware.php#L192-L216

**Comment by nicolas-grekas** [comment]
Please send a PR :)

**Comment by ro0NL** [comment]
Any specific design in mind?

**Comment by nicolas-grekas** [comment]
None, because right now I'm not sure what you mean exactly :)
