### ISSUE TITLE
[PropertyAccessor] Missing TypeError catch

### ISSUE THREAD

**Issue by b1rdex** [symfony/symfony#45199]
### Symfony version(s) affected

6.0.2

### Description

I stumbled upon a TypeError: `Cannot assign string to property App\Api\Model\Request\CoordsCheckerRequest::$latitude of type float`.

Browsing the code, I see there is a TypeError -> InvalidArgumentException wrapper:
https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L206-L217

Looks like another one should be added there.

### How to reproduce

```php
class CoordsCheckerRequest {
    public float $longitude;
}

$accessor = new PropertyAccessor();
$request = new CoordsCheckerRequest();
$accessor->setValue($request, 'longitude', 'foo');
```

### Possible Solution

```php
if (preg_match('/^Cannot assign (\S+) to property \S+::\$\S+ of type (\S+)$/', $message, $matches)) {
    [, $actualType, $expectedType] = $matches;

    throw new InvalidArgumentException(sprintf('Expected argument of type "%s", "%s" given at property path "%s".', $expectedType, 'NULL' === $actualType ? 'null' : $actualType, $propertyPath), 0, $previous);
}
```

**Comment by fancyweb** [comment]
Can you open a PR on 4.4 with your possible solution plz? I think it makes sense.

**Comment by b1rdex** [comment]
@fancyweb Sure! Please see https://github.com/symfony/symfony/pull/45306
