### ISSUE TITLE
[TwigBridge] Form option is settable only for first created form

### ISSUE THREAD

**Issue by maxkain** [symfony/symfony#45229]
### Symfony version(s) affected

5.4.2

### Description

The problem appears when running symfony as a daemon with swoole web server. The option **block_prefix** is settable once. In other requests it is impossible to set this option to another value. Twig renders form as the **block_prefix** is not changed, although each time new form instance is created.

### How to reproduce

Example is from **EasyCorp\Bundle\EasyAdminBundle\Factory**:

```php
$this->symfonyFormFactory->createNamedBuilder($entityDto->getName(), CrudFormType::class, $entityDto->getInstance(), $formOptions->all());
```
If set first parameter to something random value the problem disappears.

And in controller set option like this:
```php
if ($someCondition) {
    $field->getAsDto()->setFormTypeOption('block_prefix',  'some_prefix');
}
```

### Possible Solution

I have decorated **twig.form.engine** (**Symfony\Bridge\Twig\Form\TwigRendererEngine**) with function, which is called on **kernel.request** event:
```php
    public function init()
    {
        $this->resources = [];
    }
```
It works, but I am not sure it is the right solution.

**Comment by xabbuh** [comment]
Can you investigate which properties would need to be reset after handling a request?

**Comment by maxkain** [comment]
> Can you investigate which properties would need to be reset after handling a request?

I needed to reset only **block_prefix** property. But I think all properties should be reset.

**Comment by xabbuh** [comment]
@maxkain Can you try out #45909?

**Comment by maxkain** [comment]
> @maxkain Can you try out #45909?

if this works:
$this->resources = [];
I think this will work too:
$this->defaultThemes = [];
$this->themes = [];
$this->useDefaultThemes = [];
$this->resources = [];
$this->resourceHierarchyLevels = [];

**Comment by nicolas-grekas** [comment]
It'd still be great if you could confirm please, we never know how bugs happen :)
