### ISSUE TITLE
[ChoiceType] Form processing issue

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#45236]
### Symfony version(s) affected

6.0.2

### Description

There is an issue with handling form request with ChoiceType and property accessor in some specific cases.
This results in the wrong update of entity property.

### How to reproduce

I have designed a User entity as following:
```php
<?php

namespace App\Entity;
// [...]
class User 
{
     /**
     * @ORM\Column(type="array")
     * @Assert\NotBlank(groups={"new", "edit"})
     * @OrderColumn
     */
    protected $roles;

    public function getRoles(): array
    { 
        if(empty($roles))
            $roles[] = "ROLE_USER";

        return $this->roles;
    }

    // public function setRoles(array $roles): self
    // {
    //     if(empty($roles))
    //         $roles[] = "ROLE_USER";
    //      
    //     $this->roles = array_unique($roles);
    //
    //     return $this;
    // }

    // ISSUE WHEN ADDING ROLE.....
    public function addRole(string $role): self
    {
        if (!in_array($role, $this->roles))
            $this->roles[] = $role;
        return $this;
    }

    public function removeRole(string $role): self
    {
        if ( ($pos = array_search($role, $this->roles)) )
            unset($this->roles[$pos]);

        if(empty($this->roles))
            $this->roles[] = "ROLE_USER";

        return $this;
    }
}
```

In my example my entity has before submission the following roles:
```
#roles: array:2 [▼
    0 => "ROLE_MERCHANT"
    3 => "ROLE_ADMIN"
  ]
```

Processing a form using ChoiceType and choosing for a third entry such as "ROLE_SUPERADMIN", and removing the two first one "ROLE_MERCHANT", "ROLE_ADMIN", results in the following roles array:
```
#roles: array:2 [▼
    0 => "ROLE_MERCHANT"
    4 => "ROLE_SUPERADMIN"
  ]
```
while I would have expected 
```
#roles: array:2 [▼
    0 => "ROLE_SUPERADMIN"
  ]
```

This is not happening removing methods addRole/removeRole (having or not the setter setRoles doesn't matter)
So to my understanding the issue comes from addRole/removeRole or the way property is accessed/modified.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
