### ISSUE TITLE
Callable validator errors are not translated.

### ISSUE THREAD

**Issue by olger01** [symfony/symfony#45247]
### Symfony version(s) affected

6.0.*

### Description

I have a console command in which I ask some questions using the QuestionHelper and applying a Validator and Constraints on to the Questions. However when validation fails for an answer and an error is displayed in the console it does not seem to be translated. Both for errors displayed inline (because maxAttempts has not run out yet) and in the ConstraintViolationList thrown when there are no more attempts left.

I have changed my default locale to `nl`. I have cleared my cache. I am adding the default Translator to the ValidatorBuilder that I am using to create the Validator which I then in turn pass to the `Validation::createCallable()` function. When debugging I can see the Translator `trans()` function is being called, however I see that the `$domain` passed to the function seems to be incorrect. It seems to always be `'messages'`, while the validation error translations live in the `'validators'` domain.

The reason I see this as a bug is because for validation that happens in the "regular" way, through attributes set on an object properties, the translation seems to always happen correctly. In that case when debugging the value of `$domain` in the `trans()` function I can see it is correctly set to `'validators'` and the translations are found in their respective files, and the ConstraintViolation's messages are correctly translated as well. I expect this same behaviour to happen when using validators as callables for the purpose of using them on Questions.

### How to reproduce

Provided all relevant bundles (see context) are installed.

`translation.yaml` contents: 

```yaml
framework:
    default_locale: nl # Changed from en
    translator:
        default_path: '%kernel.project_dir%/translations'
```

`ExampleCommand.php` contents:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\ValidatorBuilder;
use Symfony\Contracts\Translation\TranslatorInterface;

#[AsCommand(
    name: 'example:command',
    description: 'Example command.',
)]
class ExampleCommand extends Command
{
    public function __construct(private TranslatorInterface $translator)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $questionHelper = $this->getHelper('question');
        $question = new Question('What is your email address?');
        $emailConstraint = new Email();
        $validatorBuilder = new ValidatorBuilder();
        $validatorBuilder->setTranslator($this->translator);
        $validator = $validatorBuilder->getValidator();
        $callableValidator = Validation::createCallable($validator, $emailConstraint);
        $question->setValidator($callableValidator);
        $questionHelper->ask($input, $output, $question);
        return Command::SUCCESS;
    }
}

```

Now when executing this command and enter an invalid e-mail address I get the following output:

```cli
What is your email address? not-an-email
 not-an-email:
    This value is not a valid email address. (code bd79c0ab-ddba-46cc-a703-a7a4b08de310)
 
What is your email address?
```

I expect to see the dutch translation of the "This value is not a valid email address." error at this point.

### Possible Solution

As noted in the question, through some debugging I noticed that the `trans()` function in the `Translator` class is not being called with the correct domain. The value of `$domain` is always `'messages'` while it should be `'validators'`. However I am unsure where this function is being called during the execution of a Question so I can not specify what exactly should be fixed.

### Additional Context

symfony/framework-bundle: 6.0.4
symfony/translation: 6.0.3
symfony/console: 6.0.3
symfony/translation: 6.0.3
PHP 8.1.1

**Comment by fancyweb** [comment]
You've got to hook the translation domain yourself:
```php
$validatorBuilder->setTranslationDomain('validators');
```

You could also use the app validator service directly:
```php
    public function __construct(private ValidatorInterface $validator)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $questionHelper = $this->getHelper('question');
        $question = new Question('What is your email address?');
        $emailConstraint = new Email();
        $callableValidator = Validation::createCallable($this->validator, $emailConstraint);
        $question->setValidator($callableValidator);
        $questionHelper->ask($input, $output, $question);
        return Command::SUCCESS;
    }
```

Please close the issue if it helps.

**Comment by olger01** [comment]
@fancyweb The first solution works. The second however does not as I don't have the Validator service available in the Command it seems. That might just be me misinterpreting your proposed solution.

As the first solution does solve my problem I will close this issue. I searched for a good few hours and was not able to find a solution myself, hence considering it a bug. So for anyone else encountering this issue I think this could be a valuable addition to the documentation, specifically [the page where validating Command questions is explained.](https://symfony.com/doc/current/components/console/helpers/questionhelper.html#validating-the-answer)

In any case, many thanks for the solution and quick reply!
