### ISSUE TITLE
#[CurrentUser]: `Cannot autowire argument $user of "App\Controller\FooController::method()": it references class "App\Entity\User" but no such service exists` if user isn't logged in

### ISSUE THREAD

**Issue by fluffycondor** [symfony/symfony#45257]
### Symfony version(s) affected

5.4, 6.0

### Description

If I try to autowire \App\Entity\User to a non-nullable variable using `#[CurrentUser]` attribute in a controller method and I'm not logged in, Symfony crashes with a RuntimeException `$user references class "App\Entity\User" but no such service exists`. 
It works like a charm if I logged in or the variable is nullable.

I'd expect it throws \Symfony\Component\Security\Core\Exception\AccessDeniedException instead, because if a programmer requests a non-null $user for a method then I think there's is an implication this method is accessible only if a user is logged in (as if there's a `$this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');` line in the beginning).

### How to reproduce

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

class FooController extends AbstractController
{
    #[Route('/foo', name: 'foo')]
    public function foo(#[CurrentUser] User $user): Response
    {
        return new Response('', Response::HTTP_NO_CONTENT);
    }
}
```

**Comment by stefan-sandberg** [comment]
Yeah, no replies. This is why no one likes Symfony. Dead framework, dead community, always errors.

**Comment by nicolas-grekas** [comment]
What a superficial comment @stefan-sandberg!
This issue didn't get any comment but it received a pull request to improve the situation at the time. Just above your comment you'll see a link to #45761

**Comment by stefan-sandberg** [comment]
> What a superficial comment @stefan-sandberg!
> This issue didn't get any comment but it received a pull request to improve the situation at the time. Just above your comment you'll see a link to #45761

Sorry to come off as rude. But it is frustrating to come from Laravel where answers are 10 sec away and error messages are clear to spend nights trying to find answers for simple errors in Symfony where you experience issues someone did 2 years ago without answers. 

The linked thread does not describe why “$user references class "App\Entity\User" but no such service exists.” It is actually not related at all. And this is what takes a lot of time to figure out issues in Symfony.

**Comment by nicolas-grekas** [comment]
You might want to join the #support channel on [our slack](https://symfony.com/slack), or check [github discussions](https://github.com/symfony/symfony/discussions) to see if this has been answered previously.
