### ISSUE TITLE
[HttpKernel] Error handling

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#45301]
In our app I noticed that some errors that happened in our API weren't correctly handled to return some error json. After some digging I found that HttpKernel only catches `\Exception` but not `\Throwable`:

https://github.com/symfony/symfony/blob/fac306002a631a03fe188fe5c824a891b16dbdb4/src/Symfony/Component/HttpKernel/HttpKernel.php#L75

I'm wondering whether this is intentional for some reason or if it is just a remnant of the past and should have been changed when Throwable was introduced. As you can see a few lines below you're calling `$this->handleThrowable($e, $request, $type);` but it's only called for Exception and not other Throwable.

**Comment by derrabus** [comment]
> I'm wondering whether this is intentional

I did so as well, a long time ago. 🧐 

#26514
