### ISSUE TITLE
[Cache] Support for cache miss

### ISSUE THREAD

**Issue by n0rbyt3** [symfony/symfony#45327]
### Description

Currently, if ```Symfony\Contracts\Cache\CacheInterface::get($key, $callback, ...)``` is used, the value returned from ```$callback``` is **always** used as new cache item value. It's a feature to allow ```false``` and ```null``` as valid cache values.

https://github.com/symfony/symfony/blob/0758e5929d536bd5abcd2e69b07da7218edc49aa/src/Symfony/Contracts/Cache/CacheTrait.php#L70

The documentation of the ```$callback``` parameter is a bit misleading as it uses the term "should" instead of "has to".
> On cache misses, a callback is called that **should** return the missing value. This callback is given a PSR-6 CacheItemInterface instance corresponding to the requested key, that could be used e.g. for expiration control. It could also be an ItemInterface instance when its additional features are needed.

In my case the callback cannot compute the value in every case and the cache key has to stay in a miss state. There seems to be a (hidden?) feature, because the callback also gets a second parameter ```$save``` passed as reference which allows to by-pass the ```save()``` call which is great for a cache miss. I'd like to have the feature made public and documented.

### Example

**Before (without knowledge of the feature):**
This will request the cache 3 times:
1. get the value of key
2. marshall the ```CacheMiss``` object and save the value
3. delete the value again

```php
class CacheMiss
{
}
$cache = new \Symfony\Component\Cache\Adapter\PhpArrayAdapter();
$value = $cache->get('key', function() {
  return new CacheMiss();
});
if ($value instanceof CacheMiss) {
  $cache->delete('key');
  $value = null;
}
```

**After:**
This will request the cache only once to get the value of the key.

```php
$cache = new \Symfony\Component\Cache\Adapter\PhpArrayAdapter();
$value = $cache->get('key', function(\Symfony\Contracts\Cache\ItemInterface $item, &$save) {
  $save = false;
});
```

**Comment by nicolas-grekas** [comment]
The $save argument is described at https://github.com/symfony/contracts/blob/main/Cache/CallbackInterface.php
You can rely on it, it's part of the contracts.
