### ISSUE TITLE
Possible bug in 'Filesystem' method 'isAbsolutePath()'

### ISSUE THREAD

**Issue by odil-io** [symfony/symfony#45334]
### Symfony version(s) affected

4.4.5

### Description

When working on a project, I stumbled upon the following error:

(obfuscation: realname replaced with username, project related names)
> Error: Command failed: /Users/odil-io/.composer/vendor/bin/php-cs-fixer fix /Users/odil-io/Local Sites/project/app/public/wp-content/themes/project/includes/filename.php --using-cache=no --path-mode=override

[Complete error message (gist)](https://gist.github.com/odil-io/5f7487fb04775528f1f5636810a547d2)

Assumed location origin of error: [Symfony/Component/Filesystem/Filesystem.php#L594](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Filesystem/Filesystem.php#L594)

### How to reproduce

1. Run `$ /absolute/path/to/.composer/vendor/bin/php-cs-fixer fix /absolute/path/to/file/with/a/space in/the/path/to/file.php --using-cache=no --path-mode=override`
2. Observe error `$ The path "/absolute/path/to/file/with/a/space" is not readable.`

### Possible Solution

It feels really dump and I'm sure this is already done but: check for spaces in path.

### Additional Context

[Output `$ composer show` (gist)](https://gist.github.com/odil-io/5f7487fb04775528f1f5636810a547d2#file-composer-show-md)

I succesfully installed PHP-CS-Fixer, and successfully integrated it in VS Code using [higoka.php-cs-fixer (external)](https://marketplace.visualstudio.com/items?itemName=higoka.php-cs-fixer) only to find out that either Symfony or the plugin are not parsing the path correctly using quotes or something.

**Comment by derrabus** [comment]
You need to escape the space when calling the `php-cs-fixer` binary. Otherwise the shell will treat your path as two separate arguments.

**Comment by odil-io** [comment]
Yeah I understood that, it's probably somewhere else down the line. The thing was, I didn't had any influence in the proces. I'll go'll more in-dept to find out what is causing this.

Thank you for your reply.

**Comment by odil-io** [comment]
For anyone returning here, sorry but I couldn't find the underlying problem. I fixed it by renaming that particular folder.
