### ISSUE TITLE
[Workflow] 

### ISSUE THREAD

**Issue by klimenttoshkov** [symfony/symfony#45352]
### Symfony version(s) affected

5.4.3

### Description

Workflow is defined as "type: state_machine" with "marking_store type: multiple_state".
Places available are A, B, C and D.
I have defined a transition T1 from place A to places B and C.
When applied transition T1 the workflow goes in both places B and C.

Having a state machine should not be allowed to:
Be defined with multiple state marking.
Define transition to multiple places.
Transition to two places at the same time and be in two places at the same time.

Attached is dump of the state machine.
![straight](https://user-images.githubusercontent.com/59835221/153004603-340f544f-0e51-4a2b-93eb-19c9c4088799.png)

### How to reproduce

I have defined a transition T1 from place A to places B and C.
When applied transition T1 the workflow goes in both places B and C.

### Possible Solution

Do not allow multiple state marking store when having state machine.

### Additional Context

n/a

**Comment by wouterj** [comment]
Hi!

The `type: multiple_state` and `type: single_state` values were removed in Symfony 4. It is no longer a valid configuration option and it nows uses the workflow/state machine type directly: https://github.com/symfony/symfony/blob/0fc8f7aa9e5e4f3423b11c2d42d3905c12b49bd1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L914-L921

Furthermore, the [docs mention](https://symfony.com/doc/current/workflow/#creating-a-workflow) already that both options had to be in sync: "This means a "workflow" must use a "multiple_state" marking store and a "state_machine" must use a "single_state" marking store. Feel free to submit a PR to the docs to change this node, giving multiple_state and single_state are no longer possible.
