### ISSUE TITLE
[Console] A change between v5.4.2 and v5.4.3 is not BC, breaks laravel 9.0.0 tinker (a psysh repl)

### ISSUE THREAD

**Issue by grota** [symfony/symfony#45359]
### Symfony version(s) affected

5.4.3

### Description

As described here https://github.com/laravel/tinker/issues/142 there has been a breaking change in symfony/console between 5.4.2 and 5.4.3 that made tinker (a php repl based on psysh) break on laravel 9, see "How to reproduce" for more info.

### How to reproduce

Following the steps detailed here https://github.com/laravel/tinker/issues/142 you will have a new laravel 9 project with `symfony/console` in version `^6`.

As the original report states, default psysh commands like `help` or `ls` are broken.

Forcing an alias dep like `"symfony/console": "5.4.2 as 6.0.2"` resolves the issue, while even 1 patch version up, i.e. using `5.4.3` results in a broken tinker.

So it's definitely something here https://github.com/symfony/console/compare/v5.4.2...v5.4.3

**Comment by nicolas-grekas** [comment]
Does https://github.com/symfony/symfony/pull/45240 fix the issue?

**Comment by grota** [comment]
Yes, I confirm it fixes it.
