### ISSUE TITLE
[workflow] Doubled transition and extra event emitted

### ISSUE THREAD

**Issue by klimenttoshkov** [symfony/symfony#45367]
### Symfony version(s) affected

5.4.3

### Description

Workflow is defined with 4 places: a, b, c, d
There are two transitions: t1 from a to [b,c] and t4 from [b,c] to d
![straight](https://user-images.githubusercontent.com/59835221/153164612-35fbcf79-6bd9-4d3f-8746-6e8cb95e5ade.png)

Dump shows two transitions t4 instead of one.

Also when running transition T4 we see that there is extra event `entered.c` emitted in error.

```
Apply T1
string(26) "workflow.straight.guard.t1"
string(25) "workflow.straight.leave.a"
string(31) "workflow.straight.transition.t1"
string(25) "workflow.straight.enter.b"
string(25) "workflow.straight.enter.c"
string(27) "workflow.straight.entered.b"
string(27) "workflow.straight.entered.c"
string(30) "workflow.straight.completed.t1"
string(26) "workflow.straight.guard.t4"
string(26) "workflow.straight.guard.t4"
string(29) "workflow.straight.announce.t4"
string(29) "workflow.straight.announce.t4"
Array
(
    [b] => 1
    [c] => 1
)

Apply T4
string(26) "workflow.straight.guard.t4"
string(26) "workflow.straight.guard.t4"
string(25) "workflow.straight.leave.b"
string(31) "workflow.straight.transition.t4"
string(25) "workflow.straight.enter.d"
string(27) "workflow.straight.entered.c"
string(27) "workflow.straight.entered.d"
string(30) "workflow.straight.completed.t4"
string(26) "workflow.straight.guard.t4"
string(29) "workflow.straight.announce.t4"
string(25) "workflow.straight.leave.c"
string(31) "workflow.straight.transition.t4"
string(25) "workflow.straight.enter.d"
string(27) "workflow.straight.entered.d"
string(30) "workflow.straight.completed.t4"
Array
(
    [d] => 1
)
```
### How to reproduce

Define the workflow as stated above. Dump the workflow image.
Run transition T4.

### Possible Solution

I think that there should be one t4 transition with two arrows joining from places b and c to the box with t4 and then one arrow from t4 to d.

**Comment by klimenttoshkov** [comment]
I did some debugging and found out that "entered" events are fired for all places that the subject is in, not only for the new places we are entering.

So in above example when moving from `B` to `D`, when subject enters `D` then event `entered.C` is fired because the subject is still in place `C`. This is wrong IMHO.

**Comment by lyrixx** [comment]
Thanks for this bug report. It's very detailed. I'll have a look at it

**Comment by klimenttoshkov** [comment]
Actually the problem was in my configuration. Even though I have paid double and triple attention, transition from `[b,c]` was not encoded in double array, resulting in separate transitions from `b` and `c` to `d` instead of one (as I expected to be).

It is pretty obvious by the code snippets above and the dump, but somehow I overlooked it.

Here is a dump of the properly defined workflow and then transitions and events are fired just as expected:
```
Apply T1
workflow.straight.entered.a
workflow.straight.guard.t1
workflow.straight.leave.a
workflow.straight.transition.t1
workflow.straight.enter.b
workflow.straight.enter.c
workflow.straight.entered.b
workflow.straight.entered.c
workflow.straight.completed.t1
workflow.straight.guard.t4
workflow.straight.announce.t4
Apply T4
workflow.straight.guard.t4
workflow.straight.leave.b
workflow.straight.leave.c
workflow.straight.transition.t4
workflow.straight.enter.d
workflow.straight.entered.d
workflow.straight.completed.t4
```

![straight](https://user-images.githubusercontent.com/59835221/155295027-df35baae-2055-4ba6-99e9-b3eb4b0fc778.png)

You may safely close the issue. Thank you
