### ISSUE TITLE
Request::createFromGlobals doesn't define session

### ISSUE THREAD

**Issue by indapublic** [symfony/symfony#45369]
### Symfony version(s) affected

6.0.3

### Description

```
public function __invoke(Request $request1): Response
{
	$request2 = Request::createFromGlobals();

	dd(
		$request1->hasSession(),
		$request2->hasSession(),
		$request1->getSession(),
		$request2->getSession()
	);
}
```

`$request1` has session and `$request1->getSession()` will return `Session` object.

`$request2` hasn't session and `$request2->getSession()` will throw exception `Session has not been set.`

Because no session is defined [here](https://github.com/symfony/http-foundation/blob/5.4/Request.php#L276).

Is it expected behaviour?

Thank you.

### How to reproduce

```
public function __invoke(Request $request1): Response
{
	$request2 = Request::createFromGlobals();

	dd(
		$request1->hasSession(),
		$request2->hasSession(),
		$request1->getSession(),
		$request2->getSession()
	);
}
```

**Comment by derrabus** [comment]
> Is it expected behaviour?

Yes. 🙂

**Comment by derrabus** [comment]
You can read more about how session management works in the HttpFoundation component in our documentation: https://symfony.com/doc/current/components/http_foundation/sessions.html

If you need further assistence, please ask for support by opening a discussion: https://github.com/symfony/symfony/discussions

**Comment by indapublic** [comment]
Thank you @derrabus I'm opened discussion but believe that provided documentation not answers on my question
