### ISSUE TITLE
Possibly skipped result check in AbstractAdapterTrait.php::getId

### ISSUE THREAD

**Issue by developer-av** [symfony/symfony#45387]
### Description

Hi, if our "namespaceVersion" has not been saved, will our cache be silently lost?
Might be worth adding a log

Traits/AbstractAdapterTrait.php
```
try {
...
    $this->doSave([static::NS_SEPARATOR.$this->namespace => $this->namespaceVersion], 0);
...
} catch (\Exception $e) {
}
```

**Comment by nicolas-grekas** [comment]
Can you be more precise? This should be logged already.

**Comment by developer-av** [comment]
I think we need something like this:

```
try {
...
    $e = $this->doSave([static::NS_SEPARATOR.$this->namespace => $this->namespaceVersion], 0);
...
} catch (\Exception $e) {
}
if ($e !== true && $e !== []){
    CacheItem::log($this->logger, 'Failed to save namespaceVersion'.$e->getMessage(), ['exception' => $e instanceof \Exception ? $e : null, 'cache-adapter' => get_debug_type($this)]);
}
```

**Comment by developer-av** [comment]
> Can you be more precise? This should be logged already.

I can't find a place where we log it

**Comment by nicolas-grekas** [comment]
Got it, this is here:
https://github.com/symfony/symfony/blob/224712bdb9da5afc4f235c463076ce467c132a9f/src/Symfony/Component/Cache/Traits/AbstractTrait.php#L124

Would you mind sending a PR to add the log, branch 4.4, by taking inspiration from other calls to doSave()?

**Comment by developer-av** [comment]
I'd love to

**Comment by developer-av** [comment]
hi @nicolas-grekas, how can I re-run unit tests?

Failed Component/Process/Tests/ProcessTest
But I didn't change it

And continuous-integration/appveyor/pr failed by timout

**Comment by nicolas-grekas** [comment]
No need to, we'll ignore the failure if it's irrelevant.

**Comment by developer-av** [comment]
Okay thank you
