### ISSUE TITLE
PHPSESSID is changed on each request

### ISSUE THREAD

**Issue by indapublic** [symfony/symfony#45382]
### Symfony version(s) affected

6.0.3

### Description

Session id is overwritten on every request

### How to reproduce

**Controller**

```
#[Route("/test", name: self::class)]
public function __invoke(Request $request): Response
{
    $session = $request->getSession();

    echo $session->getId() . "\n";

    $session->set("foo", "bar");

    echo $session->getId() . "\n";

    return new Response();
}
```

**Request**

```
curl "http://192.168.0.12:10000/test" \
     -H 'Cookie: PHPSESSID=hello'
```

**Response**

<img width="257" alt="image" src="https://user-images.githubusercontent.com/856260/153308272-ef64823b-8ee2-4086-a84c-95bb3b4de5c6.png">

**Sessions folder**

<img width="748" alt="image" src="https://user-images.githubusercontent.com/856260/153308317-be172ae3-72d2-40c2-9fe3-1a984cd03c0a.png">

**dev.log**

```
[2022-02-09T23:32:56.419560+00:00] request.INFO: Matched route "App\Controller\TestController". {"route":"App\\Controller\\TestController","route_parameters":{"_route":"App\\Controller\\TestController","_controller":"App\\Controller\\TestController"},"request_uri":"http://192.168.0.12:10000/test","method":"GET"} []
[2022-02-09T23:32:56.465918+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-02-09T23:32:56.864696+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2022-02-09T23:32:56.899536+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
```

**framework.yaml**

```
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
```

**Comment by xabbuh** [comment]
Does the session id change again when you send the correct session id with the following request?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by lbcd** [comment]
Hello,

I had the same issue. I have understand that Symfony didn't recognise the user but I don't know why.
As it is a basic authentification every request contains header to authenticate the user. So it seems like there is no issue. But in fact session is changed and a new authentication is done every request. So session is a new one each request.

I don't know why SF think it is a different user. But I solved it by adding this method to my user entity and implement my own user change detection
```
    public function isEqualTo(UserInterface $user): bool {
        if ($this->id !== $user->getId()) {
            return false;
        }

        return true;
    }
```

You have to implement `EquatableInterface` in your user entity
```
use Symfony\Component\Security\Core\User\EquatableInterface;

class User implements AdvancedUserInterface, \Serializable, EquatableInterface
```

And my session stays the same in each request.
