### ISSUE TITLE
[phpunit-bridge] Multiple definitions exist for class 'MockObject' 

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony#45408]
### Symfony version(s) affected

4.4.37

### Description

When using `phpunit-bridge` to handle unit testing, along with `<env force="true" name="SYMFONY_PHPUNIT_VERSION" value="9"/>` in `phpunit.xml`, `composer install` creates:

```
vendor/
    bin/
        .phpunit/
            phpunit -> phpunit-9-0
            phpunit-9-0
```

This means that, for example, when including `PHPUnit\Framework\MockObject\MockObject` in my unit test, PHPStorm complains that `Multiple definitions exist for class 'MockObject'` due to the duplication caused by the symbolic link.

It doesn't break anything, but wondering if there is another approach.

### How to reproduce

`composer require --dev symfony/phpunit-bridge`

explicitly declare phpunit version in `phpunit.xml` like: `<env force="true" name="SYMFONY_PHPUNIT_VERSION" value="9"/>`

then in a test, type hint or include, for example, `PHPUnit\Framework\MockObject\MockObject`

PHPStorm will underline `MockObject` with hover warning "Multiple definitions exist for class 'MockObject' "

### Possible Solution

don't use symbolic linking in `vendor/bin/.phpunit`, just overwrite `vendor/bin/.phpunit/phpunit` with the specified version (in my example `phpuni-9-0`

**Comment by derrabus** [comment]
Right-click the symlink, "Mark Directory as" -> "Excluded". Done. 😎

**Comment by arderyp** [comment]
wow, that was obvious, sorry I missed the easy fix, thanks @derrabus !
