### ISSUE TITLE
[workflow]   Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by klimenttoshkov** [symfony/symfony#45406]
### Symfony version(s) affected

5.4.3

### Description

I want to process some of the events generated by symfony/workflow in a queue. However the events cannot be serialized and passed to the queue because they contain closures.

### How to reproduce

Create event subscriber. Mark the subscriber as queuable which requires it to be serialized.

### Possible Solution

don't know how to fix it.

**Comment by ghost** [comment]
Serializing closures?

**Comment by klimenttoshkov** [comment]
Exactly. We do not want to. But the symfony code is written with closures and we cannot queue the events.

**Comment by nicolas-grekas** [comment]
You need to decouple from the event objects dispatched by Workflow and implement your own logic.
I'm closing because dispatched events are not meant to be forward as is on message buses.
