### ISSUE TITLE
Expression Language package: doesn't handle the absence of the property and an error displays

### ISSUE THREAD

**Issue by abeer93** [symfony/symfony#45411]
### Symfony version(s) affected

^6.0

### Description

I'm using [Expression Language Package](https://github.com/symfony/expression-language) with [Laravel Framework](https://laravel.com/docs/8.x)
and I'm sending the rules object and data object to the package as mentioned in the [documentation](https://symfony.com/doc/current/components/expression_language.html#expression-syntax).

The issue is if the rules object checks property which does not exist in the data object the package displays an error.
` 
"message": "Undefined property: App\\RulesEngine\\Conditions\\DataConditions::$scores", 
"exception": "ErrorException",
 `
The idea is that I'm receiving the data object from an API and the object has different properties which not of it is required but I need to evaluate the properties in case of its existence.

I checked the package's code and I found that the code is calling the property directly without checking the existence of the property.

As example,
Rules object => 
`
data.scores = 20 || data.name = "abeer"
`
data object 
`
data['name'] = "abeer";
`
and error will appear `" Undefined property data.scores"`

### How to reproduce

**My rules engine class**
`

        class RulesEngine implements RulesEngineInterface
        {
            /** @var array<string> */
            private array $rules = [];

            public function __construct(public ExpressionLanguage $expressionLanguage)
            {
            }

            /**
            * @inheritdoc
            */
            public function addRules(array $expressions, bool $reset = false): void
            {
                $this->rules = $reset ?  [...$expressions] : [...$this->rules, ...$expressions];
            }

            /**
            * @inheritdoc
            */
            public function validateData(array $data): mixed
            {
                foreach ($this->rules as $rule) {
                    $evaluated = $this->expressionLanguage->evaluate($rule, $data);
                    if (! $evaluated) {
                        return false;
                    }
                }

                return true;
            }
        }
`
**Calling the class to handle rules evaluation**

`

        public function evaluateRules(RulesEngineInterface $rulesEngine, Game $game, array $data): bool
        {
            $rulesEngine->addRules([$game->conditions], true);

            return $rulesEngine->validateData($data);
        }
`

### Possible Solution

instead of return direct access to the property in the object [return line in Evaluate function in call GetAttrNode](https://github.com/symfony/expression-language/blob/7adc90f7f09659606996f78de22830b5a2db5be4/Node/GetAttrNode.php#L78)
check the existence of the property `object_get($obj, $property) !== null` and return false to drop only one rules without stoping the code and keep evaluating the rest of the rules.

**Comment by nicolas-grekas** [comment]
I think we should keep the generated code as simple as possible. Adding the check you suggest here would make the generated code really clumsy.

Instead, what about adding support for the [nullsafe operator](https://wiki.php.net/rfc/nullsafe_operator) and the [null coalescing](https://wiki.php.net/rfc/isset_ternary) one?
If that makes sense to you, would you like working on a PR?

**Comment by nicolas-grekas** [comment]
Actually, I just found #21691 which is describing the same issue.
Closing as duplicate. My previous comment still holds appropriate :)
