### ISSUE TITLE
[symfony/mailjet-mailer] Error message is not processed correctly

### ISSUE THREAD

**Issue by EmanuelOster** [symfony/symfony#45420]
### Symfony version(s) affected

5.4.4

### Description

When sending a mail via the mailjet api, the transport checks if the response code is 200. If it is not, it tries to fetch the error message from the response and throws an exception. At the moment, the code looks for `$result['Message']` which does not exist.

Instead, `$result` has a Messages (plural) array which is structured as follows:
![image](https://user-images.githubusercontent.com/23719567/153865864-018ebab3-01f9-4c58-ab74-0a1222534a74.png)

I am not sure if this is a change in the api or if both variants can occur depending on the situation.

### How to reproduce

Simply send an invalid mail to the api. For example we tried to send a mail with a "from" header (lowercase).

### Possible Solution

Probably just grab the first error in the array.

**Comment by fancyweb** [comment]
Friendly ping to @tcheymol since you contributed this bridge.
