### ISSUE TITLE
[DependencyInjection] `Target` attribute should be allowed on properties

### ISSUE THREAD

**Issue by snroki** [symfony/symfony#45448]
### Symfony version(s) affected

5.3+

### Description

Just ran into an issue using Psalm on a service : `This attribute can not be used on a property` when I checked my code I saw that I was only using the `Target` attribute on a property in a constructor.

### How to reproduce

```php
public function __construct(#[Target('someLogger')] LoggerInterface $logger)
```

### Possible Solution

Add `|Attribute::TARGET_PROPERTY` to the `Target` attribute [on line 21](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/DependencyInjection/Attribute/Target.php#L21)

**Comment by nicolas-grekas** [comment]
That's an issue with psalm. The attribute should not be allowed on properties.
