### ISSUE TITLE
Wrong offset for Timezones

### ISSUE THREAD

**Issue by Lenny4** [symfony/symfony#45451]
### Symfony version(s) affected

6.0.3

### Description

I'm using [Timezones](https://symfony.com/doc/current/components/intl.html#timezones) like this:

```php
Timezones::getGmtOffset('Europe/Paris', (new DateTime('2022-02-16 00:00:00'))->getTimestamp()); // result: GMT+02:00
```
But when I'm looking on google I got this:
![image](https://user-images.githubusercontent.com/25544892/154347521-a5407f02-91dd-4d25-953e-77f15af0138f.png)

It's not the same GMT.

In the documentation example it take the "time change" correctly for Madrid:
> ```php
> $offset = Timezones::getGmtOffset('Europe/Madrid', strtotime('October 27, 2019')); // $offset = 'GMT+02:00'
> $offset = Timezones::getGmtOffset('Europe/Madrid', strtotime('October 28, 2019')); // $offset = 'GMT+01:00'
> ```

But when I try it I got:
```php
$offset = Timezones::getGmtOffset('Europe/Madrid', strtotime('October 27, 2019')); // $offset = 'GMT+02:00'
$offset = Timezones::getGmtOffset('Europe/Madrid', strtotime('October 28, 2019')); // $offset = 'GMT+02:00'
```

### How to reproduce

```php
<?php

use Symfony\Component\Intl\Timezones;

class OffsetClass
{
    public static function getOffsetGmt(): bool
    {
        return
            Timezones::getGmtOffset('Europe/Madrid', strtotime('October 27, 2019'))
            !==
            Timezones::getGmtOffset('Europe/Madrid', strtotime('October 28, 2019'));
    }
}

OffsetClass::getOffsetGmt();
```

### Additional Context

I'm running my symfony application in a docker `FROM php:8.1-fpm-alpine`

**Comment by ro0NL** [comment]
This is odd ...

PHP 7.4

```
^ "GMT+01:00"
root@a5e41dd4773c:/app# php -i | grep -i timezone
"Olson" Timezone Database Version => 2021.5
Timezone Database => internal
Default timezone => UTC
date.timezone => no value => no value
```
PHP 8.1

```
^ "GMT+02:00"
root@a838caa14794:/app# php -i | grep -i timezone
"Olson" Timezone Database Version => 2021.5
Timezone Database => internal
Default timezone => UTC
date.timezone => no value => no value
```

**Comment by Lenny4** [comment]
Closing since it's not related to symfony.

I created this issue.

https://github.com/php/php-src/issues/8108

**Comment by Lenny4** [comment]
Maybe implement the @[heiglandreas](https://github.com/heiglandreas) solution provided here: https://github.com/php/php-src/issues/8108

**Comment by nicolas-grekas** [comment]
Up for sending a PR @Lenny4?
