### ISSUE TITLE
Requiring Twig Bundle package doesn't install symfony/depdency-injection package

### ISSUE THREAD

**Issue by ericmorand** [symfony/symfony#45465]
### Symfony version(s) affected

5.4

### Description

The symfony/twig-bundle package depends on symfony/dependency-injection - for example here:

```php
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Bundle.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class TwigBundle extends Bundle
```
`Symfony\Component\HttpKernel\Bundle\Bundle`  implements `Symfony\Component\HttpKernel\Bundle\BundleInterface` which in turn extends `Symfony\Component\DependencyInjection\ContainerAwareInterface`.

It makes Twig Bundle dependent of symfony/dependency-injection, but requiring symfony/twig-bundle doesn't install symfony/dependency-injection.

### How to reproduce

`composer require symfony/twig-bundle`

The directory vendor/symfony doesn't contain symfony/dependency-injection.

**Comment by fabpot** [comment]
That's a soft dependency. You can use the bundle without the Symfony DI (Silex used to do that for instance).

**Comment by ericmorand** [comment]
@fabpot, I wasn't able to instanciate the bundle without getting en error:

`new \Symfony\Bundle\TwigBundle\TwigBundle()` crashes because `TwingBundle` inherits from `Symfony\Component\HttpKernel\Bundle` that use a trait provided by the Dependency Injection bundle.

It is even in the description of `Symfony\Component\HttpKernel\Bundle`:

```php
/**
 * An implementation of BundleInterface that adds a few conventions for DependencyInjection extensions.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
abstract class Bundle implements BundleInterface
```

Am I missing something?

**Comment by fabpot** [comment]
Sorry, I read too fast. I was thinking **bridge** here. In practice, I don't think this is too much of an issue, but I agree we can be explicit here: see #45504
