### ISSUE TITLE
[HttpFoundation] ReturnTypeWillChange attribute missing in RedisSessionHandler::updateTimestamp()

### ISSUE THREAD

**Issue by luxemate** [symfony/symfony#45483]
### Symfony version(s) affected

4.4.37

### Description

Greetings,

In this commit https://github.com/symfony/symfony/commit/f7abdecd641b7c721b7a52c56874c8838c54c91b#diff-41ab8decc1c9a80a9eddc61fb2c29602aaf1a82c80d0a0dfe45bab694a56b9ae the attribute was added, but it didn't land to 4.4 branch, while this one https://github.com/symfony/symfony/commit/1261a4139d629f65846afb06291c478c17d222cd#diff-41ab8decc1c9a80a9eddc61fb2c29602aaf1a82c80d0a0dfe45bab694a56b9ae fixing the `RedisSessionHandler::gc()` has landed to 4.4.

Was it a mistake or it was done intentionally? Shall I open a PR to fix just `updateTimestamp()` method, or there is a possibility the missing commit will be merged into 4.4?

In PHP 8.1 it causes:

Deprecated: Return type of Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler::updateTimestamp($sessionId, $data) should either be compatible with SessionUpdateTimestampHandlerInterface::updateTimestamp(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/symfony/http-foundation/Session/Storage/Handler/RedisSessionHandler.php on line 119

### How to reproduce

Nothing to reproduce.

**Comment by nicolas-grekas** [comment]
It look like we also missed adding the annotation to MongoDbSessionHandler.
Would you mind sending a PR on branch 4.4 to add the missing attributes, as we did on other handlers?

**Comment by luxemate** [comment]
Will do.
