### ISSUE TITLE
Allow enum type for validation groups

### ISSUE THREAD

**Issue by Guuzen** [symfony/symfony#45494]
### Description

Validation groups is often predefined set of strings. Seems like it make sense to use enum for this. Probably backed string enums.
Right now there is an error if you try to use enums for groups.

```
TypeError : Illegal offset type
vendor/symfony/validator/Mapping/GenericMetadata.php:167
```

### Example

```PHP
enum MyEnum: string
{
    case CASE_ONE = 'CASE_ONE';
    case CASE_TWO = 'CASE_TWO';
}

#[Assert\Callback(groups: [MyEnum::CASE_ONE])]
class Foo
{    
}
```

**Comment by nicolas-grekas** [comment]
Closing as explained in the linked PR: this is an engine-level consideration that should be fixed either by https://wiki.php.net/rfc/fetch_property_in_const_expressions or https://wiki.php.net/rfc/auto-implement_stringable_for_string_backed_enums

**Comment by ThomasLandauer** [comment]
@nicolas-grekas I think this should be reconsidered. Is there a reason for the Enum to be Backed? What about making **Pure Enums** possible as validation group?:
```php
enum Group
{
    case Foo;
    case Bar;
}

#[Assert\Callback(groups: [Group::Foo])]
class Whatever
{    
}
```

**Comment by derrabus** [comment]
A group is a string and we cannot guess the string representation of a non-backed enum.

**Comment by ThomasLandauer** [comment]
Yes, but the question is if it would be possible to also allow the enum type (besides `string`) as group.

**Comment by derrabus** [comment]
Why? What's the use case?

**Comment by ThomasLandauer** [comment]
Getting rid of strings - this looks like the "natural" use case for all enums to me :-)
If you have many validation groups, you can easily mistype one. With enums, static analysis would report errors immediately.

**Comment by derrabus** [comment]
What happened to constants for that matter?
