### ISSUE TITLE
Naming convention for enumerations

### ISSUE THREAD

**Issue by 0x6d6c** [symfony/symfony#45516]
### Description

According to [coding standards](https://symfony.com/doc/current/contributing/code/standards.html#naming-conventions), PHP classes of type Interface and Trait should have a suffix: `Trait` and `Interface` respectively:

> - Suffix interfaces with `Interface`;
> - Suffix traits with `Trait`;

PHP 8.1 introduced [enumerations](https://www.php.net/manual/en/language.types.enumerations.php) that are also some kind of a PHP class so I think that for consistency reasons `Enum` suffixes should be added as a new naming convention:

### Example

- Suffix enumerations with `Enum`.

**Comment by nicolas-grekas** [comment]
Closing because this is the code repo and it looks like you want to update the doc.
Please send a PR to https://github.com/symfony/symfony-docs/ so that this can be discussed there!

**Comment by wouterj** [comment]
Btw, I would suggest waiting till we have the first enum in the Symfony code. It's hard to argue about these conventions without real use-cases (e.g. we decided not to add the "Attribute" suffix for PHP 8 attributes when implementing them).

**Comment by nicolas-grekas** [comment]
About attributes, we could document they need a dedicated `Attribute` namespace!

**Comment by derrabus** [comment]
> Btw, I would suggest waiting till we have the first enum in the Symfony code. It's hard to argue about these conventions without real use-cases

The downside is that you would have the argument on the first PR that introduces an enum. That would be an unnecessary distraction during the code review.

**Comment by 0x6d6c** [comment]
Moved to symfony/symfony-docs#16538.

**Comment by derrabus** [comment]
This would be my proposal. Note that I disagree with @mi6th's suggestion: symfony/symfony-docs#16537
