### ISSUE TITLE
[PropertyInfo] Phpstan extractor may return errored property types

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#45517]
### Symfony version(s) affected

5.4+

### Description

The NameScopeFactory method build a "NameScope" in the current namespace of the object, but if the type is `Collection` (or any object out of the current namespace), then the result generated by the following line of code will be wrong:

https://github.com/symfony/symfony/blob/a4241f3f3219c17ac75d44d29bab4e5eb6e9f8a1/src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php#L194

This is a severe issue combined with API Platform because API P makes a lot of use of the property info (and for example, it doesn't allow to print the documentation of issued objects (a lot)).

### How to reproduce

Here is the reproducer : https://asciinema.org/a/qQ1xOVKdrNiEdxBNQIPeD96dn

### Additional Context

The original error I hit was the following on the documentation of API P while upgrading to Symfony 5.4 :

```
ReflectionException:
Class Sylius\Component\Core\Model\Collection does not exist

  at vendor/api-platform/core/src/JsonSchema/SchemaFactory.php:246
  at ReflectionClass->__construct('Sylius\\Component\\Core\\Model\\Collection')
     (vendor/api-platform/core/src/JsonSchema/SchemaFactory.php:246)
```

### Workaround

The following compiler pass is a workaround that simply disable phpstan type extractor:

```php
<?php

declare(strict_types=1);

namespace App\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Argument\IteratorArgument;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * @see https://github.com/symfony/symfony/issues/45517
 */
class DisablePhpstanPropertyExtractorPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        if ($container->hasDefinition('property_info.phpstan_extractor')) {
            $container->removeDefinition('property_info.phpstan_extractor');
            $def = $container->getDefinition('property_info');
            /** @var IteratorArgument $typeExtractors */
            $typeExtractors = $def->getArgument(1);
            $newExtractors = [];

            foreach ($typeExtractors->getValues() as $extractor) {
                $extractorId = (string) $extractor;
                if ('property_info.phpstan_extractor' !== $extractorId) {
                    $newExtractors[] = $extractor;
                }
            }

            $def->setArgument(1, new IteratorArgument($newExtractors));
        }
    }
}

```

**Comment by vvasiloi** [comment]
I can confirm the issue. I reproduced it with https://github.com/Setono/SyliusPluginSkeleton.
Here's one example when it fails:
Given the class `Sylius\Component\Core\Model\PaymentMethod` extending `Sylius\Component\Payment\Model\PaymentMethod` where the latter has the following method:
```php
    /**
     * @return PaymentMethodTranslationInterface
     */
    public function getTranslation(?string $locale = null): TranslationInterface
```
and where `PaymentMethodTranslationInterface` doesn't have an FQCN in imports because it's in the same namespace `Sylius\Component\Payment\Model`.
The resulting class name for property `translation` of `Sylius\Component\Core\Model\PaymentMethod` will be `Sylius\Component\Core\Model\TaxonTranslationInterface`, which doesn't exist.

**Comment by vvasiloi** [comment]
I added a test to reproduce the issue: https://github.com/symfony/symfony/pull/45633

**Comment by Nek-** [comment]
@vvasiloi just for information, your issue is definitely connected to mine, but the cases are actually different, and fixing your test will not fix the issue I reported here.

But thanks for making it anyway!

**Comment by vvasiloi** [comment]
@Nek- I understand that, but I think the underlaying issue is the same.
I just don't yet know how to test it to cover both cases.
Perhaps it needs different tests for different cases.

**Comment by Nek-** [comment]
> Perhaps it needs different tests for different cases.

I think so yes. I have no fix for It though.

**Comment by vvasiloi** [comment]
I will work on the issue next week.
Maybe you can add a test for your case in the meantime.

**Comment by SirDomin** [comment]
Hey, some of us have the same issue with Sylius/Sylius while loading swagger documentation, workaround provided by @Nek- seems to be solving the issue for us. Is there any chance to fix that on symfony side?

**Comment by vvasiloi** [comment]
I didn't have time to work on it. 😞

**Comment by Nek-** [comment]
Fixed by https://github.com/symfony/symfony/commit/d46b6764eb781154ae325ccffce4d6d9e3c920b3

It was same as https://github.com/symfony/symfony/issues/44431
