### ISSUE TITLE
Automatic cache:warmup in development broken on later versions of PHP (>8.0.3)

### ISSUE THREAD

**Issue by smadaman** [symfony/symfony#45556]
### Symfony version(s) affected

5.4.*

### Description

When developing in Symfony, it will automatically run a cache:warmup when required (eg. changing class property, annotation etc). This has always worked, the latest version that it has worked on successfully on for me is PHP8.0.3 using Bitnami WAMP.

Recently I installed Bitnami WAMP PHP8.0.15. With this installation, when I make a change like the above or even just remove everything within the var/cache directory, upon the next refresh the cache will attempt to build starting with a "App_KernelDevDebugContainer.php.lock" file in the cache directory but never get farther than that and the browser reads "This site can't be reached". I can't determine any logged error messages anywhere.

I have already reached out to Bitnami about this and they believe they have not changed any configurations between the versions, simply PHP which apparently means it's the framework I am using and should enquire with the framework developers about fixing the problem.

I have also tried with Bitnami WAMP 8.0.11 and it still does not work.

*EDIT - I have also tried with XAMPP PHP8.0.15 and this is still a problem

I have since reverted back to the 8.0.3 installation of Bitnami WAMP and it is working fine again.

![image](https://user-images.githubusercontent.com/12181026/155684502-d2588ecb-b42b-47c3-9ba0-a6f3bb387312.png)

### How to reproduce

1. Install a fresh installation of Bitnami WAMP PHP8.0.15
2. Install a new Symfony skeleton via composer including the "composer require webapp" command within the apps folder
3. Delete everything within the var/cache folder
4. Run the app in whatever way (I am using vhost files)
5. Attempt to refresh the homepage and the cache will not build.

*If I was to run a php bin/console cache:warmup command manually it will work fine

**Comment by xabbuh** [comment]
I fear that you will have to debug this a bit yourself to find out what is going on.
