### ISSUE TITLE
symfony/messenger in 5.4 requires symfony/amqp-messenger and symfony/redis-messenger?

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#45598]
### Symfony version(s) affected

5.4.5

### Description

The symfony/messneger requires symfony/amqp-messenger in 5.4.5 which also means that the PHP extension amqp is required, even if a different transport is used. Same for redis. With 6.x this dependency seems to be gone alrady.

As 5.4.5 can require both in 6.x this might install amqp-messenger in 6.x which also requires the ext-amqp (which makes sense) but as amqp might not even be used it is an unnecessary dependency.

### How to reproduce

composer require symfony/messenger:^5.4

### Possible Solution

ensure symfony messnger does not require redis/amqp messenger in 5.4 as is already the case for 6.x or disallow installing 6.x amqp / redis messenger.

**Comment by AndreasA** [comment]
Not 100% sure this is a bug or it is by design for 5.4.x

**Comment by ghost** [comment]
This is not a bug. See https://github.com/symfony/symfony/pull/35422

**Comment by AndreasA** [comment]
@javaDeveloperKid Ah. Great. Wasn't sure. That explains why they are required with 5.4 but not 6.x
