### ISSUE TITLE
[Cache] MemcachedAdapter asks to update to nonexistent memcached version

### ISSUE THREAD

**Issue by flack** [symfony/symfony#45601]
### Symfony version(s) affected

6.0.5

### Description

Since updating symfony/cache from 6.0.3 to 6.0.5 today, I get the following exception in my unittests under PHP 8.1:

```
In MemcachedAdapter.php line 59:
 Memcached > 3.1.5 is required.  
```

The problem with that is, at least according to 

https://github.com/php-memcached-dev/php-memcached/releases

3.1.5 is the latest version. There is nothing to update to.

### How to reproduce

Just instantiate `MemcachedAdapter` on PHP 8.1. I reproduced on macOS with memcached installed from PECL.

### Possible Solution

At the very least, it's a very misleading error message. It looks like effectively, MemcachedAdapter can't run under PHP 8.1, except maybe if you self-compile memcached. Maybe this can be made a bit clearer 

In 4b9692ca96005739b30c5a0f0dfb1f4d780f7a1b it is mentioned that "conflict" was added due to https://github.com/php-memcached-dev/php-memcached/issues/496, and I remember seeing those errors in my PHP 8.1 env before, but I found some way to work around it (i.e. with symfony/cache <6.0.5, my test suite completes successfully), so it seems a bit harsh to completely break `MemcachedAdapter` under 8.1 in a point release. So another solution would be to just revert that commit? It's not like Symfony can do anything about it, and it's just a memcached bug, it's not like Symfony uses some API that only exists in versions > 3.1.5, which is what I assume the original intention for `isSupported` was.

**Comment by nicolas-grekas** [comment]
IMHO there should be only one fix, and it should be a new release of php-memcached.

**Comment by flack** [comment]
Yes, I agree. That is why IMHO https://github.com/symfony/symfony/commit/4b9692ca96005739b30c5a0f0dfb1f4d780f7a1b does not add any value. It only turns a problem I worked around into a different problem I need a different workaround for.

**Comment by ruudk** [comment]
Same issue here, everything was working fine until we upgraded to latest 6.0.x release. It asks me to bump to an unreleased version.

The PHP Memcached extension is pretty dead:
- https://github.com/php-memcached-dev/php-memcached/issues/495

Don't expect a tagged release anytime soon.

As everything was working fine before the patch release, I would also suggest to revert that fix.

**Comment by nicolas-grekas** [comment]
Everything was *not* working fine before the change: our CI was failing when testing with memcached.
Reverting is not an option *unless* someone finds a way to make the CI green.
PR welcome.

**Comment by ruudk** [comment]
To be clear, I mean everything was working fine for us, as a component user. I understand that you had your reasonings.

**Comment by remicollet** [comment]
> IMHO there should be only one fix, and it should be a new release of php-memcached.

Yes a Memcached released is really needed, but "some" repository already provides a patch version 3.1.5, so which is working fine with PHP 8.0 and 8.1.

**Comment by nicolas-grekas** [comment]
Hi @remicollet 
How could we use your repo in our CI?
That'd be the best I think!

**Comment by remicollet** [comment]
> How could we use your repo in our CI?

You probably have to run some docker image (using Fedora / RHEL or CentOS as base)
btw, I have no experience on github actions

**Comment by withinboredom** [comment]
It was working 100% fine using https://github.com/mlocati/docker-php-extension-installer. This totally broke everything for me as well...

**Comment by nicolas-grekas** [comment]
> Version 3.2.0RC1 is released

Thanks @remicollet !

**Comment by Vinorcola** [comment]
Hello

@nicolas-grekas 

> Everything was _not_ working fine before the change: our CI was failing when testing with memcached.  
> Reverting is not an option _unless_ someone finds a way to make the CI green.

Understand that upgrading from sf 6.0.3 to 6.0.6 make our app completely unable to run anymore. We have no choice but to block version 6.0.3 and won't be able to apply security fixes anymore. How is that an acceptable option from Symfony quality point of view?

How is it possible that your CI was failling before, and not failling with an unexisting dependency??? Are you sure the failling tests keeps executing? How can you execute tests with no dependency installed?

Thanks for clarifications.

**Comment by nicolas-grekas** [comment]
> How is it possible that your CI was failling before, and not failling with an unexisting dependency???

We didn't run the tests for memcached on PHP 8.1 until recently. When we did so, we saw the failures.

> Are you sure the failling tests keeps executing? How can you execute tests with no dependency installed?

They're on php < 8.1. They're obviously not on PHP 8.1, until ext-memcached 3.2 is made available.

**Comment by ninsky** [comment]
I have the same problem with Symfony 4.4.41. Could someone also please provide a fix for the 4.4.x stream or advise how to fix it?

**Comment by ruudk** [comment]
Install the latest version of the Memcached extension. 

https://pecl.php.net/package/memcached/3.2.0

**Comment by ninsky** [comment]
@ruudk , is this the only way how to fix it? I'm locked on the versions the Ubuntu image of my hoster provides.... It there's no other workaround I have to rework my caching strategy as hoster updates can take some time.

**Comment by ruudk** [comment]
Yes, or downgrade to the previous patch release of the symfony component

**Comment by ninsky** [comment]
Alright, thanks @ruudk. So I will downgrade an wait till my hoster will provide the update to v3.1.6. In case someone need to know how to check the version of the installed memcached extension. Here we go: `php --ri memcached`

**Comment by Lot-Art** [comment]
The latest good release is v6.0.1 `composer update symfony/cache:6.0.1`

**Comment by milanmadar** [comment]
The latest good release is v6.0.1 `composer update symfony/cache:6.0.1`
