### ISSUE TITLE
[DependencyInjection] Renaming ExtensionInterface::getNamespace to avoid conflict with BundleInterface::getNamespace

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#45607]
### Description

The [`BundleInterface`](https://github.com/symfony/symfony/blob/88497f2bfd0272b0a57b78db894306a9ef5bf272/src/Symfony/Component/HttpKernel/Bundle/BundleInterface.php#L55) and the [`ExtensionInterface`](https://github.com/symfony/symfony/blob/88497f2bfd0272b0a57b78db894306a9ef5bf272/src/Symfony/Component/DependencyInjection/Extension/ExtensionInterface.php#L35) both requires a `getNamespace` method. But where the Bundle returns the Bundle Namespace, the extension return thing is the [xml namespace](https://github.com/symfony/symfony/blob/88497f2bfd0272b0a57b78db894306a9ef5bf272/src/Symfony/Component/DependencyInjection/Extension/Extension.php#L42-L45) of the configuration.

As I'm experemting by merging `Bundle`/`Extension`/`Configuration` into a single instance. See example [here](https://github.com/alexander-schranz/single-class-symfony-integraton-class). It would be great that this would make possible without any conflicts by deprecating the `getNamespace` on `ExtensionInterface` and use in future the `getXmlNamespace` method.

What would you think about this change? Are you open for a PR here?

### Example

```php
class MyLibraryBundle extends Bundle implements ExtensionInterface, ConfigurationExtensionInterface, ConfigurationInterface
{
    public function getNamespace(): string
    {
       // returns bundle namespace
    }
    
    public function getXMLNamespace(): string
    {
       // returns xml namespace
    }
}
```

See also [here](https://github.com/alexander-schranz/single-class-symfony-integraton-class).

**Comment by nicolas-grekas** [comment]
A bundle class is loaded 100% of the time. A DI extension is loaded only at compile time.
Merging the DI extension into the bundle class blurs these lines.
I'm not sure why this would be desired.

**Comment by alexander-schranz** [comment]
@nicolas-grekas to have a single class which responsibility is to integrate a library into symfony ecosystem and don't need to switch between Bundle, Extension, Configuration to build the integration.

**Comment by nicolas-grekas** [comment]
You could return an anonymous class if you really want to achieve this I suppose.
But I don't think this proposal is worth the cost of the deprecation.

Side note: if a recipe is enough, better save writing a bundle. That's already the case for many packages.

**Comment by alexander-schranz** [comment]
Anonymous class would feel a little bit strange here for me. But I understand your point. I still think be more specific with getXMLNamespace would not hurt as it more reflects what type of namespace it returns here. 

But still if you think it doesn't make any sense to change it. I will not be angry if you close it. In that case I still thank you for your time, work and your insights!

> A DI extension is loaded only at compile time.

Would need to check that if it would hurt in performance but as it is not executed I don't think it should have a lot of effects here.

> Side note: if a recipe is enough, better save writing a bundle. That's already the case for many packages.

Yeah already use that for https://github.com/sulu/web-twig. If it are just some services its just fine. Currently mostly work on project packages where we do not have recipes for them. I already thought about to just provide the `services.php` file for packages without any configuration.

**Comment by stof** [comment]
> I still think be more specific with getXMLNamespace would not hurt as it more reflects what type of namespace it returns here.

if we were writing that interface now, that might be a valid reason to choose a different name. But **renaming** it has a cost for the whole ecosystem.
I agree with @nicolas-grekas that the cost of the deprecation outweights the benefit by far, so I vote for closing this as "won't do".

**Comment by derrabus** [comment]
Same here. We shouldn't rename the method.

**Comment by xabbuh** [comment]
I agree as well.

**Comment by alexander-schranz** [comment]
Still thank you all for the discussion and feedback 👍
