### ISSUE TITLE
PhpExecutableFinder may return directory instead of binary

### ISSUE THREAD

**Issue by mglaman** [symfony/symfony#45620]
### Symfony version(s) affected

3.4 | 4.4

### Description

We're using \Symfony\Component\Process\PhpExecutableFinder in Drupal's Upgrade Status module to execute PHPStan from a UI. In different environments leveraging Plesk or ISPConfig, the returned path from \Symfony\Component\Process\PhpExecutableFinder::find is a directory.

### How to reproduce

I haven't been able to reproduce since I do not have access to a Plesk server. But directories are technically executable.

### Possible Solution

The checks for `is_exectuable` may need a `!is_dir` check?

**Comment by mglaman** [comment]
From these comments, it looks like an issue on Plesk based shared hosting.

* https://www.drupal.org/project/upgrade_status/issues/3241362#comment-14417885
* https://www.drupal.org/project/upgrade_status/issues/3245521

**Comment by stof** [comment]
Based on the Drupal discussion, this looks like one more side-effect of our wrong handling of `open_basedir` in the PhpExecutableFinder

**Comment by mglaman** [comment]
Correct, I haven't tried to reproduce yet. But when `open_basedir` is set up the result is a directory for some reason.

**Comment by mglaman** [comment]
Thanks, everyone!
