### ISSUE TITLE
symfony/cache package "symfony/service-contracts produces error due to lack of php 7.4. compatibility 

### ISSUE THREAD

**Issue by chriwen** [symfony/symfony#45642]
### Symfony version(s) affected

5.4

### Description

we using symfony/cache in a wordpress plugin and including it via composer
with "symfony/cache": "^5.4"

this loads the dependency package:
"symfony/service-contracts": "^1.1|^2|^3",

unfortunately if we are try to load this to the wordpress plugin directory we get an fatal error in:
service-contracts/Attribute/SubscribedService.php in line 30

Here the constructor property promotion is used which was implemented in PHP 8. 

So it seems that symfony/service-contracts uses this in all versions from version 2.x

How can we use this in PHP 7.4.x enivroments?

### How to reproduce

Using composer:
```
  "require": {
    "php": ">=7.3",
    "symfony/cache": "^5.4"
```
Then trying to upload or check the included depencies to PHP 7.3. compatibility. It leads to error:
```
PHP error in: vendor/symfony/service-contracts/Attribute/SubscribedService.php:
Parse error: syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in Standard input code on line 30
```

### Possible Solution

Rewrite the class constructor to be compatible with php 7.3

**Comment by derrabus** [comment]
As you can see on packagist, cache-contracts 3 requires PHP 8:

https://packagist.org/packages/symfony/cache-contracts

This is not a Symfony bug. Your Composer setup is broken.

**Comment by derrabus** [comment]
Sorry, forget my previous comment.

The class that you are mentioning is part of a feature that is exclusive to PHP 8. It is not meant to be loaded on PHP 7.

**Comment by chriwen** [comment]
@derrabus Thanks for your reply. Could you give me a hint how I can avoid the class beeing loaded in PHP 7? Can i just delete / ignore this file in PHP 7 enviroments without breaking the functionality?

**Comment by derrabus** [comment]
I cannot because I don't know why this class is being loaded in the first place.

I'm sorry, but I have to close this bug report. If you need further support, please use GitHub discussions.

**Comment by jpmarcotte** [comment]
Ran into this issue as well. `SubscribedService` uses a promoted constructor pattern, but `composer.json` says that version 2.5 only requires `"php": ">=7.2.5",`. Even if it's only supposed to be used in PHP 8, pre-compiling the Opcache will load this and it will break.
