### ISSUE TITLE
Symfony kernel.view event was never triggered

### ISSUE THREAD

**Issue by agazzi** [symfony/symfony#45646]
### Symfony version(s) affected

6.0.4, 6.0.5

### Description

Hello,

Yesterday i try to add a kernel.view event to a recent project end it's never triggered, i try to edit config and nothing happen.
I  move to kernel.controller and it's work, i rollback to kernel.view and with all priority, no priority event was never triggered.

I decide to create a fresh new Symfony 6.0.5 project only for check if the problem persist and yes.

3 way:
- Usage of this event is now different
- Symfony have an issue with kernel.view event
- I'm stupid

Thank you for your help
Regards

### How to reproduce

- symfony new acme
- cd acme/
- composer require --dev symfony/maker-bundle
- composer require doctrine/annotations
- php bin/console make:controller acme
- php bin/console make:subscriber acme kernel.view **(Write some code you like for testing like die(), dd() in method)**
- php bin/console debug:event-dispatcher kernel.view (subscriber is active on the correct event)
- symfony serve (go to <your-host>/acme and see result, listener/subscriber was never triggered/fired)

**Comment by sormes** [comment]
Your controller returns a response? the documentation indicates that the event is only triggered when the controller does not return a Response

**Comment by derrabus** [comment]
> 3 way:
> - Usage of this event is now different
> - Symfony have an issue with kernel.view event
> - I'm stupid

You put me in a very tough spot. On the one hand, I don't want to insult you, on the other hand I think I can rule out options 1 and 2, so…

The controller that you've generated returns a response. The `kernel.view` event is only triggered if the controller doesn't do so. And well… it has always been this way.

**Comment by agazzi** [comment]
Thank you for your answer, 

@sormes i use this process in more than 200 Symfony project over last 10 years and i'm sure this is possible.
After a good night's sleep, finally the real problem is not to work too late i remember why.

This feature need usage of "sensio/framework-extra-bundle" after that, every controller action (with response included)
trigger kernel.view event.

Now i have a question for @derrabus after reading your comment:
what is the interest of kernel.view if we cannot trigger before final rendering ? For me, this in one of the superpower of the kernel.view event.

Thank you for your help, you can close ticket
have a good day ;)

**Comment by derrabus** [comment]
FrameworkExtraBundle provides functionality that uses the `kernel.view` event (like the infamous `@Template` annotation), but it does not change how it's being triggered. The purpose of the event is to turn the return value of the controller into a response.

https://github.com/symfony/symfony/blob/1df76df444add6fe1b4291c0ede5a524f4d14940/src/Symfony/Component/HttpKernel/HttpKernel.php#L151-L157

Its propagation is stopped when a reponse is set. Triggering the event when you already have a response is thus pointless.

https://github.com/symfony/symfony/blob/1df76df444add6fe1b4291c0ede5a524f4d14940/src/Symfony/Component/HttpKernel/Event/RequestEvent.php#L37-L45

I don't know what you mean by "trigger before final rendering", but if you need a way to modify the response returned by a controller before it's being sent to the client, there's the `kernel.response` event for that.

**Comment by agazzi** [comment]
ok i understand you say, 

line 155, when is not a Response instance trigger view event, i need to access view event with a response event for custom twig injection globally, so when i use @template annotation, i return array for only property controller needed and link to twig view, so in this case i can use view event with final response instance.

When i use response event, i can't access dynamically to controllers properties.
This solution work fine since many years for me, but maybe you have a better "symfony compliance" solution for do that.

Regards

**Comment by derrabus** [comment]
I don't really get your question, I'm afraid. That being said, this is a bug tracker, not a support forum. If you have more questions, please feel free to open up a thread on https://github.com/symfony/symfony/discussions

**Comment by agazzi** [comment]
I think we don't understand from the beginning, the most important thing is that I was able to solve my problem and that it can certainly help other people ;)

Thanks again for your time
