### ISSUE TITLE
[FrameworkBundle] Memory leak in PHPUnit when testing forms on entities

### ISSUE THREAD

**Issue by adrienfr** [symfony/symfony#45668]
### Symfony version(s) affected

5.4.6

### Description

Hi,

Since SF 5.4.6 on PHP 7.4.26, I have a memory leak on PHPUnit and my large tests suite (4981 tests, 33361 assertions) fails with this error : 

> PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted

I tried to debug it and it seems to origin from https://github.com/symfony/symfony/pull/45595.

cc @nicolas-grekas

### How to reproduce

I created a reproducer to compare SF 5.4.5 and 5.4.6, accessible [here](https://github.com/adrienfr/sf-reproducer-memory-leak).
The memory leak seems to happen on Form tests with entities having relationship/association type properties. 

### Additional Context

The reproducer entity only contains 1 `ManyToOne` property and used memory is x2, in my project (with 1Gb of RAM dedicated to PHPUnit tests) here is the result when testing a single Form on an entity with 10+ relationship properties :

SF 5.4.5 :
```
Testing 
.Memory usage: 146 MB
.Memory usage: 161 MB
.Memory usage: 171 MB
.Memory usage: 152 MB
.Memory usage: 161 MB
.Memory usage: 151 MB
.Memory usage: 151 MB
.Memory usage: 151 MB
.Memory usage: 160 MB
.Memory usage: 151 MB
.Memory usage: 151 MB
.Memory usage: 152 MB
.Memory usage: 162 MB
.Memory usage: 152 MB
.Memory usage: 152 MB
.Memory usage: 151 MB
.Memory usage: 161 MB
.Memory usage: 151 MB
.Memory usage: 151 MB
.Memory usage: 151 MB
.Memory usage: 160 MB
21 / 21 (100%)

Time: 00:09.343, Memory: 207.00 MB
```

SF 5.4.6:
```
Testing 
.Memory usage: 147 MB
.Memory usage: 163 MB
.Memory usage: 173 MB
.Memory usage: 184 MB
.Memory usage: 193 MB
.Memory usage: 202 MB
.Memory usage: 212 MB
.Memory usage: 222 MB
.Memory usage: 231 MB
.Memory usage: 240 MB
.Memory usage: 249 MB
.Memory usage: 260 MB
.Memory usage: 271 MB
.Memory usage: 281 MB
.Memory usage: 292 MB
.Memory usage: 302 MB
.Memory usage: 311 MB
.Memory usage: 322 MB
.Memory usage: 332 MB
.Memory usage: 341 MB
.Memory usage: 350 MB
21 / 21 (100%)

Time: 00:09.034, Memory: 373.00 MB
```

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, will be fixed by #45671

**Comment by adrienfr** [comment]
Hi @nicolas-grekas,

Thanks for the PR!

I tried to apply the patch on my project but the result is the same, `PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 36864 bytes)` :

<img width="721" alt="Capture d’écran 2022-03-08 à 12 46 17" src="https://user-images.githubusercontent.com/4313077/157232406-5cdb2022-b9ec-4a0e-98aa-1bfb0a469b00.png">

**Comment by nicolas-grekas** [comment]
Does your code enter the added "if"?

Does `if ($container instanceof ResetInterface)` work better (as removed in https://github.com/symfony/symfony/pull/45595/files)?

**Comment by adrienfr** [comment]
> Does your code enter the added "if"?
> 
> Does `if ($container instanceof ResetInterface)` work better (as removed in https://github.com/symfony/symfony/pull/45595/files)?

Yes it does enter the "if ($container->has('services_resetter')) {...}".

This time the memory leak seems to origin from my Entity validator and no more the Form validator. Do you want me to try to update the reproducer?

**Comment by nicolas-grekas** [comment]
First please answer my 2nd question.

**Comment by adrienfr** [comment]
> First please answer my 2nd question.

I tried this but it doesn't fix the issue :
```php
use Symfony\Contracts\Service\ResetInterface;
...
protected static function ensureKernelShutdown()
{
    if (null !== static::$kernel) {
        static::$kernel->boot();
        $container = static::$kernel->getContainer();
        static::$kernel->shutdown();
        static::$booted = false;

        if ($container instanceof ResetInterface){
            $container->get('services_resetter')->reset();
        }
    }

    static::$container = null;
}
```

**Comment by nicolas-grekas** [comment]
What about `$container->reset();`?

**Comment by adrienfr** [comment]
> What about `$container->reset();`?

Nice catch, the following code seems to work, let me double-check before confirmation :
```php
protected static function ensureKernelShutdown()
{
    if (null !== static::$kernel) {
        static::$kernel->boot();
        $container = static::$kernel->getContainer();
        static::$kernel->shutdown();
        static::$booted = false;

        if ($container instanceof ResetInterface){
            $container->reset();
        }
    }

    static::$container = null;
}
```

**Comment by adrienfr** [comment]
I can confirm that the following patch applied on 5.4.6 works fine, not more memory leak during tests, thanks! 🙏 
```patch
--- /dev/null
+++ ../Test/KernelTestCase.php
@@ -15,6 +15,7 @@
 use Symfony\Component\DependencyInjection\ContainerInterface;
 use Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException;
 use Symfony\Component\HttpKernel\KernelInterface;
+use Symfony\Contracts\Service\ResetInterface;
 
 /**
  * KernelTestCase is the base class for tests needing a Kernel.
@@ -149,14 +150,19 @@
     }
 

     protected static function ensureKernelShutdown()
     {
         if (null !== static::$kernel) {
             static::$kernel->boot();
+            $container = static::$kernel->getContainer();
             static::$kernel->shutdown();
             static::$booted = false;
+
+            if ($container instanceof ResetInterface){
+                $container->reset();
+            }
         }
 
         static::$container = null;

```

**Comment by Oliboy50** [comment]
👋 Could you please confirm that this issue was the same as the following:

going from `"symfony/framework-bundle": "4.4.38"` to `"symfony/framework-bundle": "4.4.39"` introduce a memory leak in a test suite of functional tests

<img width="1440" alt="Capture d’écran 2022-03-21 à 11 36 42" src="https://user-images.githubusercontent.com/2571084/159245129-7affc80e-7125-44c2-be4a-a2a40ce67b86.png">

**Comment by adrienfr** [comment]
@Oliboy50 it might be the same issue, could you try the [provided patch on branch 4.4](https://github.com/symfony/symfony/commit/608b1ddf6c74a4a300a8c06e8a34af78a2bdb019) (not released yet but merged) and see if it fixes your issue?

**Comment by Oliboy50** [comment]
@adrienfr yep, this patch fixes my issue, thanks

so I just have to wait for a release 👌
