### ISSUE TITLE
[Cache] Use Lock-Component when locking the recomputation of cache items

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#45663]
### Description

Currently when the recomputation of a cache item is locked it used a hard coded Filesystem/flock based implementation in `\Symfony\Component\Cache\LockRegistry`. This makes the locking mechanism unsuitable for mutli-server setups, where you have a fleet of web-servers handling requests, as the lock would only work on a single server.

The lock implementation should be based on the `symfony/lock` component, as you can configure a remote lock storage, that will work consistently in such a multi server setup.

**Comment by nicolas-grekas** [comment]
The lock that is in place right now is only meant to prevent a single host from exhausting its resources when the cache is cold. It is expected that when a cluster is warming up, having each node in the cluster recompute the same item will provide the same end-user experience, compared to having one node compute the item and all the other ones waiting for it.

This is a compromise of course, and this compromise it also geared towards making the lock mechanism as fast as possible. Thus the current direct access to `flock()`.

There *could* be another locking mechanism built next to it, that could swap to the lock component for ppl that need it. It shouldn't be the default to me, unless there's realworld proof (benchs+use cases) that this is worth it.

**Comment by keulinho** [comment]
The current implementation works well if the bottleneck and the resource heavy operations happens on the web-servers itself, but in our cases (and i think it is a quite common case) the bottleneck lies on the DB-server. So the current implementation does not guard against heavy loads on all downstream services (either DBs, or even other (micro-)services that are called etc.).

**Comment by nicolas-grekas** [comment]
That's true, yet I think the DB should be sized so that it can handle the load of its front-end php server.
We'd be happy to review a PR that provides an alternative to the default locking mechanism.
Closing meanwhile.
