### ISSUE TITLE
SES+api Transport should also stringify from address

### ISSUE THREAD

**Issue by everyx** [symfony/symfony#45660]
### Symfony version(s) affected

6.1

### Description

When I set from address something like `"中文" <admin@example.com>`,  the from name `中文` does not display correctly. 

The reason is 

> There are non-ASCII characters in the email address—The email address string must be 7-bit ASCII. If you want to send to or from email addresses that contain Unicode characters in the domain part of an address, you must encode the domain using Punycode. Punycode is not permitted in the local part of the email address (the part before the @ sign) nor in the "friendly from" name. If you want to use Unicode characters in the "friendly from" name, you must encode the "friendly from" name using MIME encoded-word syntax, as described in [Sending raw email using the Amazon SES API](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html). For more information about Punycode, see [RFC 3492](http://tools.ietf.org/html/rfc3492).

\- from [Amazon SES email sending errors](https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-error-messages.html)

We have already stringify to addresses, and we should also stringify the from address.

```
        $request = [
            'FromEmailAddress' => $envelope->getSender()->toString(),
            'Destination' => [
                'ToAddresses' => $this->stringifyAddresses($this->getRecipients($email, $envelope)),
            ],
```
\- from https://github.com/symfony/amazon-mailer/blob/8ffe8053a854ca376b126eecd0e3a55f5b4ae8bf/Transport/SesApiAsyncAwsTransport.php#L55-L59

### How to reproduce

send a email with from address name contain any non-ASCII chars, and the email will show a broken from name.

### Possible Solution

stringify the from address

**Comment by everyx** [comment]
I have submit a PR, but @[symfony-bot](https://github.com/apps/symfony-bot) notify me 

> If you want to contribute, you should instead open a pull request on the main repository:

Am I submitting this RP incorrectly? Thanks

**Comment by xabbuh** [comment]
@everyx You need to send PRs to this (https://github.com/symfony/symfony) repository.

**Comment by everyx** [comment]
@xabbuh  I just create PR for `6.0` branch, should I also create a PR to `5.4` branch?

**Comment by xabbuh** [comment]
We only need one PR. We always merge them into the lowest affected branch. From there we regularly merge branches up into all maintained branches.

**Comment by everyx** [comment]
> We only need one PR. We always merge them into the lowest affected branch. From there we regularly merge branches up into all maintained branches.

So, I should create new PR base on `5.4` branch, and close the current one? and it will merge up into all maintained branches like `6.x`?
