### ISSUE TITLE
DkimOptions -> algorithm typehint wrong 

### ISSUE THREAD

**Issue by markusramsak** [symfony/symfony#45685]
### Symfony version(s) affected

5.4

### Description

(new DkimOptions())->algorithm(DkimSigner::ALGO_SHA256)
causes error because method algorithm has "int" als datatype but DkimSigner::ALGO_SHA256 is of type string

### How to reproduce

(new DkimOptions())->algorithm(DkimSigner::ALGO_SHA256)

### Possible Solution

change typehint from int to string

**Comment by fancyweb** [comment]
Can you send a PR targetting 5.4 plz?

**Comment by markusramsak** [comment]
I open a pull request #45719 to solve this issue
