### ISSUE TITLE
Post with redirected response in HttpClient 5.4.5 throws a 408 error (worked properly on HttpClient 5.4.3)

### ISSUE THREAD

**Issue by samuelvi** [symfony/symfony#45709]
### Symfony version(s) affected

5.4.5

### Description

When an HttpClient post request is made, and the response returns a redirection, a 408 error is thrown by HttpClient.
This works properly until 5.4.3 version but not in version 5.4.5

### How to reproduce

// $url is a vble like http://my.domain1:8000
// $headers[] = 'Content-Type: application/x-www-form-urlencoded';
// $params is an array form
$client->request('POST', $url, ['headers' => $headers, 'body' => $params]);

Error given: 
HTTP/1.1 408 Request Timeout returned for "..." . (Symfony\Component\HttpClient\Exception\ClientException)

Note the post will be made to an http scheme and redirected to another url, with a different subdomain (http scheme as well), but that is not the issue because works properly in 5.4.3

**Comment by nicolas-grekas** [comment]
Regression likely introduced in #45261
