### ISSUE TITLE
[Translation] False negative in `debug:translation` fallback detection

### ISSUE THREAD

**Issue by noemi-salaun** [symfony/symfony#45712]
### Symfony version(s) affected

6.0.6

### Description

The `debug:translation` command fails with error code 2 (`MESSAGE_EQUALS_FALLBACK`) when checking all my translations. But the translation for `CANCER` is present in the fr_FR catalogue, it's just the same as the en_US translation.

```
$ ./bin/console debug:translation --all fr_FR
 ------------ ---------- ------------------------------- ------------------------------------------ ------------------------------------------ 
  State        Domain     Id                              Message Preview (fr_FR)                    Fallback Message Preview (en_US)          
 ------------ ---------- ------------------------------- ------------------------------------------ ------------------------------------------ 
               names      AQUARIUS                        Verseau                                    Aquarius                                  
               names      ARIES                           Bélier                                     Aries                                     
   fallback    names      CANCER                          Cancer                                     Cancer                                    
               names      CAPRICORN                       Capricorne                                 Capricorn                                 
               names      GEMINI                          Gémeaux                                    Gemini                                    
```

### How to reproduce

Define a translator with a fallback

```yml
framework:
    translator:
        fallbacks: ['en_US']
```

Define the same translation in both catalogue (en_US and fr_FR).

Run `./bin/console debug:translation --all fr_FR` 

### Possible Solution

In `TranslationDebugCommand` on line 233

```php
foreach ($fallbackCatalogues as $fallbackCatalogue) {
    if ($fallbackCatalogue->defines($messageId, $domain) && $value === $fallbackCatalogue->get($messageId, $domain)) {
        $states[] = self::MESSAGE_EQUALS_FALLBACK;

        $exitCode = $exitCode | self::EXIT_CODE_FALLBACK;

        break;
    }
}
```

It should check if `$currentCatalogue->defines($messageId, $domain)` before marking the entry as `fallback`

**Comment by welcoMattic** [comment]
Hi @noemi-salaun, thanks for reporting this issue. I guess your possible solution is fine, can you open a PR for this? Thank you

**Comment by noemi-salaun** [comment]
After looking a little more carefully at the code and [the tests](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Bundle/FrameworkBundle/Tests/Command/TranslationDebugCommandTest.php#L52), I think the current behavior is as expected. The exit code EXIT_CODE_FALLBACK is literally only for this use case, so I guess that's fine.
