### ISSUE TITLE
dependency injection arguments  duplication in controller constructor / method

### ISSUE THREAD

**Issue by hdimo** [symfony/symfony#45736]
### Description

Hi,
I noticed that the code below works, but the same service is injected multiple times in the same controller (in constructor and method), so I think it will be better to aware a developer throught  a setting in framework.yaml like 'prevent_inject_same_dependecies' or else then throw related exception like 'ServiceAlreadyInjectedException'.

### Example

```php
class ArticleController extends AbstractController
{
    private ArticleRepository $repository;
    public function __construct(ArticleRepository $repository)
    {
        $this->repository = $repository;
    }
    public function action(ArticleRepository $repository)
    {
        $articles = $this->repository->findOneBy();
        $foo = $this->repository->findBy([]);   
    }
   public function action2(ArticleRepository $repository, ArticleRepository $articleRepository)
    {
        $articles = $this->repository->findOneBy();
        $foo = $this->repository->findBy([]);   
    }
}
```

**Comment by xabbuh** [comment]
From my point of view this does not sound like a use case that is common enough to justify a setting and thus increasing complexity.

**Comment by stof** [comment]
I would say this is rather something for a linter or a static analyzer rather than adding some runtime overhead to add a warning for something that works fine anyway.

**Comment by nicolas-grekas** [comment]
I agree with @xabbuh and @stof, thanks for proposing.
