### ISSUE TITLE
Filesystem: typehints prevent resources from being passed

### ISSUE THREAD

**Issue by tvdijen** [symfony/symfony#45749]
### Symfony version(s) affected

^5.0

### Description

The type-hints that were added in 5.x for the methods in Filesystem prevent us from passing resources because the `file`-parameter is now type-hinted as string. It used to deal with resources before this change and even the phpdoc for the methods still mention the possibility to pass resources.

Support for resources was added in https://github.com/symfony/symfony/pull/29661

### How to reproduce

```php
    $fs = new Filesystem();
    $fs->appendToFile(
        fopen('php://stderr', 'w'),
        "We're logging an error!" . \PHP_EOL,
        false,
    );
```

### Additional Context

My initial goal was to 'appendToFile' to file `php://stderr`, but on Windows that breaks on the call to mkdir().
As an alternative I tried to pass `fopen('php://stderr', 'w')` as a file, but then I hit the typehint restriction.

It's basically two different issues:
1. Stuff breaking when file is `php://stderr`. I should probably be able to pass this as a file.
2. Typehints preventing us from passing resources

**Comment by dbrumann** [comment]
Are you sure, you are using it properly? From what I can see the 2nd argument (`$content`) can be a stream, so the content being added. The filename was always supposed to be a string, i.e. a file to write to, and not a stream.

**Comment by xabbuh** [comment]
closing as explained before
