### ISSUE TITLE
[Mailer] Lost of information in Debug compared to SwiftMailer

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#45747]
### Description

Using Swiftmailer we can see the Headers and it's important to note that the original receiver (X-Swift-To: thomas.lallement@9online.fr) have been replaced by the receiver provided in dev env (To: tlallement@incert.lu).

![image](https://user-images.githubusercontent.com/652505/158398273-d1aad1f4-be7d-4fa2-91ae-20175eae2db2.png)

Using Symfony Mailer we don't have the headers displayed on first tab, even if the title appears. We can think that the mail is really sent to the To: thomas.lallement@9online.fr even if in fact it have been really sent to tlallement@incert.lu (using the RCPT TO header).

![image](https://user-images.githubusercontent.com/652505/158398736-fe5678e4-0e94-496d-9a97-fda51dfcf27f.png)

Even in the Raw tab we are not able to see the real receiver. Is it normal? 

![image](https://user-images.githubusercontent.com/652505/158400086-b82f3d4d-fe93-4a56-ac2c-15e3f0cc6e06.png)

**Comment by fabpot** [comment]
I don't have enough details, but maybe because we don't display the envelope in the profiler? If so, that would make sense to add it.

**Comment by raziel057** [comment]
From https://github.com/symfony/web-profiler-bundle/blob/5.4/Resources/views/Collector/mailer.html.twig

```twig
<pre class="prewrap">{% for header in message.headers.all|filter(header => (header.name ?? '') not in ['Subject', 'From', 'To']) %}
    {{- header.toString }}
{%~ endfor %}</pre>
```

We exclude 'Subject', 'From' and 'To' from headers, but there is no other headers in the Email object. 

![image](https://user-images.githubusercontent.com/652505/158431621-253f8d96-c50e-4588-8372-092858bb7b18.png)

We don't have specific headers attached to the envelope:

![image](https://user-images.githubusercontent.com/652505/158439364-e53a1fe4-12af-49f0-99e6-5512d918df98.png)

**Comment by raziel057** [comment]
Using ``message.preparedHeaders.all`` rather than ``message.headers.all`` seems to offer missing information.

![image](https://user-images.githubusercontent.com/652505/158440512-cf8a327b-5a2e-4515-8b84-6e3c5374eee7.png)
