### ISSUE TITLE
[Mailer] Incorrect Header in profiler

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#45758]
### Symfony version(s) affected

4.4.x

### Description

The header data (Date, Message-ID, Content-Type) displayed in the Profiler is not the one of the sent message, but is refreshed each time the profiler page is reloaded. 

You can see here each time I refresh the profiler page, the Header data is modified. It's not the case with Swiftmailer profile.

Ex for same email:
![image](https://user-images.githubusercontent.com/652505/158558362-11c2cf8f-e5b0-4be5-842b-e415d555a407.png)

After page refresh the profiler tab:
![image](https://user-images.githubusercontent.com/652505/158558474-692ed989-859d-4669-94cd-03fe4016f330.png)

The issue is related to the following code (getPreparedHeaders):

```twig
<div class="tab">
    <h3 class="tab-title">Raw</h3>
    <div class="tab-content">
        <pre class="prewrap" style="max-height: 600px">{{ message.toString() }}</pre>
    </div>
</div>
```

```php
public function toString(): string
{
   if (null === $body = $this->getBody()) {
       $body = new TextPart('');
   }

   return $this->getPreparedHeaders()->toString().$body->toString();
}
```

### How to reproduce

Send an email, go to the profiler page and refresh the profiler.

Check that headers change (Date takes the current datetime)

**Comment by fabpot** [comment]
Are you using a queue? If yes, it's expected.

**Comment by raziel057** [comment]
No I don’t use a queue in this sample.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
