### ISSUE TITLE
Consistency issue between the framework-bundle and the http-foundation component

### ISSUE THREAD

**Issue by ecourtial** [symfony/symfony#45750]
### Symfony version(s) affected

5.4.6

### Description

When migrating from Symfony 4.4 to Symfony 5.4, we get the following error:

>Argument 3 passed to Symfony\Component\HttpFoundation\Session\SessionFactory::__construct() must be callable or null, array given

After some research, we found it to be related to the two following parts.

1- In the _http-foundation_ component, we indeed see that the session factory expects a callable as a third argument of the constructor: https://github.com/symfony/http-foundation/blob/34e89bc147633c0f9dd6caaaf56da3b806a21465/Session/SessionFactory.php#L29

2- But in the framework-bundle, we see that it injects an array:
https://github.com/symfony/framework-bundle/blob/a5add2526f6d8c021592443ab2b55416443d6c9e/Resources/config/session.php#L48

This call seems to be triggered by this line of the framework-bundle: https://github.com/symfony/framework-bundle/blob/a5add2526f6d8c021592443ab2b55416443d6c9e/DependencyInjection/FrameworkExtension.php#L434

### How to reproduce

A project with the following dependencies:
* "symfony/http-foundation": "^5.4",
* "symfony/framework-bundle": "^5.4"

And in your _app/config/config_test.yml_, add the following entry:

    test.session.listener:
        class: xxx\xx\xx\Test\TestSessionListener

**Comment by GromNaN** [comment]
The array `[service('session_listener'), 'onSessionUsage']` should be a valid callable. The method was added in Symfony 5.1 https://github.com/symfony/symfony/pull/36129.

Have you redeclared `session_listener` service?

**Comment by ecourtial** [comment]
>Have you redeclared session_listener service?

No.
Below is what we see in the generated container (_AppKernelTestDebugContainer.php_):

```
 protected function getSession_FactoryService()
    {
        return $this->privates['session.factory'] = new \Symfony\Component\HttpFoundation\Session\SessionFactory(
            ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), 
            ($this->privates['session.storage.factory.service'] ?? $this->load('getSession_Storage_Factory_ServiceService')), 
            [0 => ($this->privates['test.session.listener'] ?? ($this->privates['test.session.listener'] = new \MyCompany\Bridge\Symfony\Test\TestSessionListener($this))), 1 => 'onSessionUsage']
        );
    }
```

**Comment by GromNaN** [comment]
Hum, it looks like the class `MyCompany\Bridge\Symfony\Test\TestSessionListener` have not the method `onSessionUsage`.

**Comment by ecourtial** [comment]
Indeed. Problem solved. Thanks!
