### ISSUE TITLE
Add various return-typed getters to ParameterBag

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony#45775]
### Description

right now, `ParameterBag` has only a few getter options for fetching values:

```
get(): mixed
getAlpha(): string
getAlnum(): string
getDigits(): string
getInt(): int
getBoolean(): bool
```

For those of us using static analyzers like PHPStan, we often find ourselves having to add a bunch of manual type checking code to ensure that the parameter we are fetching is of a specified type.  I see two main problems/annoyances here:

1. In terms of fetching configuration parameters, this often means implementing type checks to ensure that the returned value is indeed the type that we already know it to be.
2. In terms of fetching Request and Query parameters, we have to contend with the fact that forms cast everything to strings, which means fetching a mixed result from `get()`, type checking it as a string, then casting it to the actual type it should be. 
 
The two exclusions here are `getInt()` and `getBoolean()`. Furthermore, `getInt()` is potentially dangerous with it's naked cast, as you may be fetching `5.5` or `"5.5"` and it will return `5` instead of throwing an exception.

### Example

Would the community find it valuable to have many more typed getters along the lines of `getInt()` and `getBoolean()` that return *validated* parameters returned as their proper type? I'm thinking things along the lines of:

```
getArray(): array
getArrayOrNull(): ?array
getBoolean(): bool
getBooleanOrNull(): ?bool
getInt(): int
getIntOrNull(): ?int
getFloat(): float
getFloatOrNull(): ?float
getString(): string
getStringOrNull(): ?string
```

here are some quick examples, including an improvement of `getInt()`:

```php
protected function getInt(string $key, int $default = 0): int
{
    if (is_int($value = $this->get($key, $default))) {
        return $value;
    }
    throw $this->getException("int", $value);
}

protected function getIntOrNull(string $key, int $default = 0): ?int
{
    $value = $this->get($key, $default)
    if (is_int($value) || is_null($value)) {
        return $value;
    }
    throw $this->getException("int|null", $value);
}

protected function getString(string $key, string $default = ""): string
{
    if (is_string($value = $this->get($key, $default))) {
        return $value;
    }
    throw $this->getException("string", $value);
}

protected function getStringOrNull(string $key, string $default = ""): ?string
{
    $value = $this->get($key, $default)
    if (is_string($value) || is_null($value)) {
        return $value;
    }
    throw $this->getException("string|null", $value);
}

/** @param mixed $value */
private function getException(string $expected, $value): TypeException
{
    return new TypeException("expected parameter of type $expected but found " . gettype($value));
}
```

If the Symfony developers think this is a good idea and/or community members want it, I can work on a PR.  I just didn't want to do the work only to find that this discussion has already been had, or there's something I'm missing, or such a feature wouldn't be accepted by Symfony.

And perhaps this logic shouldn't live in `ParameterBag`.  Maybe it warrants a new `Typer` object that can be recycled all over the place.  I currently have this type of logic implemented on a Trait that I include as needed.

**Comment by nicolas-grekas** [comment]
Related to https://github.com/symfony/symfony/pull/44787

**Comment by arderyp** [comment]
What do you think @nicolas-grekas? What I'm proposing here is more expansive than #44787

**Comment by nosilentesdblog** [comment]
We are running into the same/similar problems.
Especially some implementations just strip invalid parts (e.g.  `getAlpha`) and return whatever is left (in terms of valid parts).  Another example is casting of `int`. This would return 0 for invalid inputs.

Practical example: Getting a user with an invalid ID (let's say `a1`). The `getInt()` method would return `0`. Imagine having a superuser with ID `0`.

Which is not how parsing types should work?

So having these checks in the actual `get` methods would make sense. We also specifically ran into this issue while using static code analysis.

Edit: Functions, such as `ctype_alnum()`, `ctype_alpha` and `ctype_digit` would be good to use to make sure the values are actually as expected.

**Comment by arderyp** [comment]
I agree @nosilentesdblog.  Methods like getAlpha could be misleading, especially when there is a getInt, which might lead some to assume getAlpha is getString. And yes, int casting is dangerous and WILL lead to bugs, some potentially critical, like the example you provided.

It's also generally weird that such an edge case has an explicit getter (getAlpha), but the much more common use cases (float, int, bool, string, array, etc) don't have explicit typed getters

**Comment by Growiel** [comment]
I'd like to throw my +1 here, what we do at the moment is the following:

```php
$page = ctype_digit($request->query->get('page')) ? $request->query->getInt('page') : 1;
```

We feel like this is the only acceptable way of handling it. Let's take an example of `foo23bar14` as the value in `page`:

```php
get: foo23bar14
getInt: 0
getAlnum: foo23bar14
getDigits: 2314
getAlpha: foobar
```

None of those are correct. We don't have a valid input and we would like to know so instead of trying to be smart and figure out a "valid" ("0" from getInt, "2314" from getDigits are not, in fact, valid) input for the invalid one.

Using `ctype_digit` each time is annoying, but the only safe way to go. 

Plus, we get a lot of deprecation errors now though, since as of PHP 8.1, `ctype_digit` only accepts `string` and the return value of `get()` is `mixed`.

I'm willing to work on this if there's a chance it can be approved.

**Comment by arderyp** [comment]
> Plus, we get a lot of deprecation errors now though, since as of PHP 8.1, `ctype_digit` only accepts `string` and the return value of `get()` is `mixed`.

This is my main inspiration for this issue.  If you use high level phpstan, you will see these mixed errors all over the place.  Most instances were related to getting values from `ParameterBag` and `InpurBag`.

We were using a common trait for type validating mixed variables from `ParameterBag` and `InputBag` and elsewhere. Now we use a common `Type` object with static methods like `toInt()`, `toString()`, etc, which each take mixed arguments and use explicit return types. So we pass variables through these functions when necessary to validate their types before passing them on other functions that require strict types, like `ctype_digit()`.

**Comment by nicolas-grekas** [comment]
To me we can close this issue after #48525.
(I wouldn't add the `OrNull()` methods variants)
