### ISSUE TITLE
Yaml imports ignores int keys for maps

### ISSUE THREAD

**Issue by rk-mxp** [symfony/symfony#45797]
### Symfony version(s) affected

5.2.14

### Description

If Yaml files are imported via `imports` and both import files define a value with an int key (e.g., `100: value1` and `200: value2`), the resulting merged map has keys `0` and `1`, effectively dropping the indexes defined in the imported files.

This only happens with int indexes and only if merged by `imports`

### How to reproduce

Write 3 Yaml files: a main Yaml file which imports 2 others with `imports`
In the imported element define a custom property and add values with int indexes, e.g.

Imported file 1:
```
MyValues:
  100: value1
```
Imported file 2:
```
MyValues:
  200: value2
```

The resulting Yaml will be
```
MyValues:
  0: value1
  1: value2
```

instead of 
```
MyValues:
  100: value1
  200: value2
```

If the key is not an int, e.g., 100a, the merge is as expected. This only happens with int keys.

### Additional Context

I noticed this problem when I tried to add custom form elements in Typo3 10. The form config is defined in Yaml and Typo3 10 uses Symfony 5.2.

I defined my Form Elements in their own Yaml files and merged the config using `imports` but my custom ViewModules were added with index `0` and `1`, disregarding my defined indexes.

**Comment by stof** [comment]
Are you talking about some bundle semantic configuration, about parameters or about other things ? Your description does not allow reproducing things for now.

**Comment by rk-mxp** [comment]
I tried to build a minimal example but at closer inspection I noticed this is actually a Typo3 Core Bug.

The Symfony framework uses imports in Yaml files for the `services.yaml` (https://symfony.com/doc/current/service_container/import.html) so I though this functionality is used by Typo3.

But actually Typo3 uses its own code to parse `imports` statements (which I found now in the core code) which triggers the bug.

Sorry for the confusion, you can close the ticket.
Never assume anything, I should have known better.
