### ISSUE TITLE
Serializer do not works properly in 5.4

### ISSUE THREAD

**Issue by pcholewa** [symfony/symfony#45796]
### Symfony version(s) affected

5.4.*

### Description

Serializer do not serialize an array of objects. In 5.2.* all works ok. After update to 5.4.* do not works. I using api platform 2.6.

### How to reproduce

```
class A {
    public int $number;
}

class ParentDTO {
    /**
     * @var A[]|array
     */
    public array $a;
}
```

example input: 
```
{
  "a": [
    {
      "number": 1
    },
    {
      "number": 2
    }
  ]
}
```

Symfony 5.2.* output:
"a" is an array of objects - correct

Symfony 5.4.* output:
"a" is an array of array - not correct

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by pcholewa** [comment]
It's becouse of named arguments. From Symfony 5.3 should using "named arguments", but how should looks the above code using named arguments?

**Comment by xabbuh** [comment]
I have no idea what you mean. But as I said having an application that allows to reproduce your issue would maybe allow us to help you.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
