### ISSUE TITLE
Validator Cache not Working 

### ISSUE THREAD

**Issue by progmancod** [symfony/symfony#45807]
### Symfony version(s) affected

5.4.6

### Description

Following docs https://symfony.com/doc/current/reference/configuration/framework.html#reference-validation-cache I have my validator.yaml as following:

framework:
  validation:
    enabled: true
    email_validation_mode: html5
    cache: cache.default_redis_provider
  cache:
    app: cache.adapter.filesystem
    default_redis_provider: '%env(REDIS_CACHE_URL)%'

But cache is not being written in my redis. I dig in and find out that Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory is being used for this. So I put some debug there and see that it is getting $cache = null from DI. I override it manually with

$cache = new RedisAdapter(new Client('redis://redis:6379?database=1'));
and my tests are working fast and cache is written and read.

The problem seems to affect only LazyLoadingMetadataFactory.

### How to reproduce

no

### Possible Solution

no

### Additional Context

no

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
