### ISSUE TITLE
[BC-Break] Changes to KernelTestCase in #45595 broke our test suite

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#45800]
### Symfony version(s) affected

4.4.39

### Description

Hi,

we're running our tests with a modified version of the WebTestCase to not shut down the kernel after each test (long story short: We're running on a service based legacy auth which cannot be mocked away and it quite costy.). To achieve this we changed these 2 methods in the class:

~~~php
    public static function tearDownAfterClass(): void
    {
        static::ensureKernelShutdown();
    }

    protected function tearDown(): void
    {
        // Drop kernel shutdown after each single test
    }
~~~

This worked flawlessly until the Symfony 4.4.39 version of the FrameworkBundle: https://github.com/symfony/symfony/pull/45595

I understand the changes, but is there an easy solution to recover the piror behaviour?

Kind regards
Matthias

### How to reproduce

See description.

**Comment by nicolas-grekas** [comment]
Call disableReboot()?

**Comment by althaus** [comment]
You mean on the client? We already tried this and with this change some other tests broke as those seem to rely on some nifty side effect which keeps the container or parts of the container alive? I've already made an internal ticket to check this out.

This is the current solution we're trying out:

~~~php
    public static function setUpBeforeClass(): void
    {
        self::$client = static::createClient();
        self::$client->disableReboot();

        self::$authenticated = false;
    }
~~~

Should this be enough to keep the kernel alive? Any idea what leads to our current zombie container?

**Comment by althaus** [comment]
I did some more digging into our issue and I finally had to rollback to 4.4.37 of the FrameworkBundle to get our tests back to work. In the history of the KernelTestCase are several changes between .37 and .39... something of those has this serious impact for us.

I won't say that our functional tests are well built, but they worked for the last couple of years. :D

**Comment by nicolas-grekas** [comment]
Does https://github.com/symfony/symfony/pull/45671 fix the issue?

**Comment by igordeveloper** [comment]
> Does #45671 fix the issue?

I had a similar problem as Mathias, and for me this fix works. I'm waiting just for a new 5.4 .* release, i did a test local with 5.4dev.

tks.

**Comment by igordeveloper** [comment]
> Does #45671 fix the issue?

I had the same problem as Matthias, and this fix the issue for me. I'm waiting a new release.

Thank you.
