### ISSUE TITLE
[Routing] Route::$env not initialized PHP 8

### ISSUE THREAD

**Issue by ricohumme** [symfony/symfony#45802]
### Symfony version(s) affected

6.0.5

### Description

When using this branch I can see that some variables are not initialized when the cache is cleared.
I did however see that these class variables are present (but not all initialized) in the 5.4 branch.
In the 6.0 and 6.1 branch, the class variables are no longer present.

The specific error I got
```
In Route.php line 196:
                                                                                                              
  Typed property Symfony\Component\Routing\Annotation\Route::$env must not be accessed before initialization  
                                                                                                              
```

### How to reproduce

Checkout latest version of symfony/routing and run this with PHP 8 with strict variables.

### Possible Solution

Add the class variables and initialize these

**Comment by xabbuh** [comment]
What does „run this“ mean? Can you please create a small application that  allows to reproduce your issue?

**Comment by jukuan** [comment]
I have same issue on php8.1.3 for symfony/routing v.6.0.5.
The `private ?string $env` property is Uninitialized for some reasons. 
But when manually copy-pasted files from v.6.0 to the vendor/symfony/routing directory, then everything works fine again.
So, it's hard to say what's wrong here. Probably it is because of reflection?

```
├ Error: Typed property Symfony\Component\Routing\Annotation\Route::$schemes must not be accessed before initialization
   │
   ╵ vendor/symfony/routing/Annotation/Route.php:160
   ╵ vendor/symfony/routing/Loader/AnnotationClassLoader.php:170
   ╵ vendor/symfony/routing/Loader/AnnotationClassLoader.php:130
   ╵ vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php:60
   ╵ vendor/symfony/config/Loader/FileLoader.php:157
   ╵ vendor/symfony/config/Loader/FileLoader.php:96
   ╵ vendor/symfony/routing/Loader/YamlFileLoader.php:211
   ╵ vendor/symfony/routing/Loader/YamlFileLoader.php:99
   ╵ vendor/symfony/config/Loader/FileLoader.php:157
   ╵ vendor/symfony/config/Loader/FileLoader.php:85
   ╵ vendor/symfony/routing/Loader/Configurator/RoutingConfigurator.php:45
   ╵ src/Kernel.php:52
 
```
UPD:
Updating the version php helped me. I upgraded it to the php8.1.4 (from 8.1.3). And it works fine. 
It's really strange, because as I can see the `symfony/routing` package has differences only in syntax, especially in that file: vendor/symfony/routing/Annotation/Route.php.

**Comment by jukuan** [comment]
@ricohumme  what version of php do you have? 
and check please if you have some polyfills installed (i.e. symfony/polyfill-php72) and try to remove them.

**Comment by ricohumme** [comment]
Hi, I have 8.1.3 as well. Installed polyfill's on this project are for 7.3, 8.0 and 8.1

**Comment by nicolas-grekas** [comment]
If you are experiencing the issue, no need to say so, this report is already saying there *is* an issue to understand.

Please provide a reproducer instead as we won't be able to fix anything without reproducing first.

**Comment by ricohumme** [comment]
Oke I narrowed this down to a cache issue when upgrading from symfony/routing 5.4.3 to 6.0.5.
Right after you run composer update the cache gets cleared and that's when the error hits.
When performing another cache:clear the issue is no longer present.

Can anyone confirm this?
I don't feel like an example project is justified in this case as this only happens (to me at least) when updating to a new major version.

**Comment by fabpot** [comment]
Just had the same issue while upgrading, clearing the cache was enough to get rid of it. So, not sure we need to do anything here.

**Comment by ricohumme** [comment]
I think just the fact that it has been noticed and it "auto-resolves" should be enough :)

**Comment by v-radev** [comment]
Cache clear was throwing this error for me so I did `rm -rf var/cache/dev/` and it was fixed. Happened while updating from 5 to 6.
