### ISSUE TITLE
RFC Add a method to HttpClient to get the first response as soon as it is received

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#45806]
### Description

HttpClient is perfect to run requests in parallel in a "sync" context. I think we can improve it for use-cases when we want to do something as soon as a response is received.

Use-cases:
- Wait for the next response, in an event-loop.
- Limit concurrency when a lot of HTTP requests have to be sent, by starting a new request each time a request is completed.

The `stream` methods allows to process responses as soon as they are received (thanks to functions `curl_multi_select` and `stream_select`). But they do a lot more to provide each data chunk (read the stream, uncompress, handle errors).

This code shows how to get the first response as soon as it is completed.
```php
$responses = [
    $httpClient->request('GET', $url1),
    $httpClient->request('GET', $url2),
    //...
];

foreach($httpClient->stream($responses) as $response => $chunk) {
    if ($chunk->isLast()) {
        break;
    }
}
$firstResponse = $response;
```

Proposition: 

```php
/**
 * Returns the first response as soon as it is completed.
 *
 * @param iterable<array-key, ResponseInterface> $responses Responses created by the current HTTP client
 * @param float $timeout|null 
 * @return ResponseInterface The first completed response
 * @throws \Symfony\Contracts\HttpClient\Exception\TimeoutExceptionInterface
 */
public function race(iterable $responses, float $timeout = null): ResponseInterface;
```

Method name can be discussed `race` ([JS](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)),  `any` ([JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)) or `first`.

### Example

Exemple of implementation of an async HttpClient with Revolt Event-Loop. Thanks to Fiber, the interface is the same, but it can be used efficiently in concurrent fibers. https://gist.github.com/GromNaN/a9014a9c69c9a5cc08ac8c30677408f4

**Comment by nicolas-grekas** [comment]
All those use cases are possible to implement without too much hassle. I don't think we should add new methods on HttpClient objects, but why not on a helper class? This would make it easy to use. PR welcome if you're up to.

**Comment by GromNaN** [comment]
Yes, a helper would be perfect. I'm not sure where to start.
`$response->multi->handle` is a private property. Then I think we need a new method in `CurlResponse`; maybe a new interface like `StreamableInterface` is.

**Comment by nicolas-grekas** [comment]
I don't understand. Why would you need that? The client is already async.

**Comment by GromNaN** [comment]
The HttpClient is async, but blocking when you get the response.

The purpose is to allow concurrent execution flows (Fibers). This requires an event loop (I'm using [Revolt](https://github.com/revoltphp/event-loop/blob/main/README.md)). In each iteration of this loop, it calls queued callbacks and it waits for the next completed response using `curl_multi_select` or `stream_select`.

Unless there is already a public abstraction around this "select" operation, access to the raw handle is necessary.
