### ISSUE TITLE
Request redirect resets InMemoryTransport

### ISSUE THREAD

**Issue by alexeytashmatov** [symfony/symfony#45826]
### Symfony version(s) affected

5.4.6

### Description

Request redirect resets InMemoryTransport and this example doesnt work: https://symfony.com/doc/current/messenger.html#in-memory-transport.

I have a test:
```
    public function testGenerateReport(): void
    {
        $client = self::createClient();

        /** @var InMemoryTransport $transport */
        $transport = static::getContainer()->get('messenger.transport.report.generate');

        $client->request('GET', '/report/generate');

        $this->assertCount(1, $transport->getSent());
    }
```

Redirect response returned at the end of my action `'/report/generate'`:
```
    public function generateReport(): RedirectResponse
    {
        $message = new GenerateReport();
        $this->messageBus->dispatch($message);

        return $this->redirect('/');
    }
```
This redirect resets InMemoryTransport and $transport->getSent() returns empty array [ ].

### How to reproduce

1. Create test:
```
    public function testExample(): void
    {
        $client = self::createClient();

        /** @var InMemoryTransport $transport */
        $transport = static::getContainer()->get('messenger.transport');

        $client->request('GET', '/example');

        $this->assertCount(1, $transport->getSent());
    }
```

2. Create action with redirect respone
```
    public function example(): RedirectResponse
    {
        $message = new TestMessage();
        $this->messageBus->dispatch($message);

        return $this->redirect('/');
    }
```

### Possible Solution

Separate transport and request tests

**Comment by n0rbyt3** [comment]
The transport holds messages for a single request as described in the documentation. A redirect finishes the current request, which also releases all resources and performs a new request with a new empty memory.

**Comment by fabpot** [comment]
As explained by @n0rbyt3, that's by design.
If you don't follow the redirect, you should have access to the message though.
