### ISSUE TITLE
[MAILER] Having a non breaking space after the domain cause wrong encoded address

### ISSUE THREAD

**Issue by kodoa-dev** [symfony/symfony#45832]
### Symfony version(s) affected

5.4

### Description

If for some reason the mail address you set when sending an e-mail using Symfony Mailer contains a non-breaking space after the domain, `IdnAddressEncoder` detects that he has to fix it but wrongly encodes it resulting in an address without the  domain altogether.

### How to reproduce

Just try to send an a-mail with an address that contains a non-breaking space after the domain.

```
(new Email())
                ->from(new Address('John Doe', 'john@doe.com '))
                ->to(new Address('Jane Doe', 'jane@doe.com '))
                ->subject($subject)
                ->html($html)
```

### Possible Solution

Fix the encoding in `Symfony\Component\Mime\Encoder\IdnAddressEncoder`, line 38 that seems the culprit.

**Comment by fabpot** [comment]
But is it a valid email address? If not, you should validate the email before using it in Mailer.

**Comment by kodoa-dev** [comment]
It is not because there's a whitespace acter the domain, but even in this case shouldnt mailer be throwing an error instead of silently trying to send an email to an address without anything after the "@"?
