### ISSUE TITLE
[Form] FormErrorIterator create recursion problem using analyzer

### ISSUE THREAD

**Issue by Ciloe** [symfony/symfony#45847]
### Symfony version(s) affected

5.4

### Description

When using phpstan and rector on my project in SF 5.4 (working well in SF 5.3), I have a memory limit with phpstan and rector is kill. See related issue in phpstan : https://github.com/phpstan/phpstan/issues/6911

### How to reproduce

I reproduce the error in my project, but it can't shared it....

**Comment by Ciloe** [comment]
Hi, I replaced the file with this content : https://github.com/symfony/form/blob/18f4f8209d2db06fc3cf5ba3b2eb8e4706b34aac/FormErrorIterator.php

And it works fine. So the problem come from this commit : https://github.com/symfony/form/commit/f5e3a0f5b2a85f61551a55596a0d948cda50f033

**Comment by herndlm** [comment]
Hi, we started debugging something similar in https://github.com/phpstan/phpstan/issues/6896. I think this is a bug in phpstan itself. I'll report back if I know more.

**Comment by Ciloe** [comment]
Hi, it's not only PHPStan, I have this problem with Rector too

**Comment by herndlm** [comment]
Rector also uses PHPStan as non-dev dependency, might still be related, but we'll see :)

**Comment by herndlm** [comment]
This was most likely fixed in PHPStan by https://github.com/phpstan/phpstan-src/pull/1137
You should be able to test by requiring 1.5.x-dev :)
