### ISSUE TITLE
[Form] Return value must be of type Symfony\Component\Form\FormError|Symfony\Component\Form\FormErrorIterator, bool returned

### ISSUE THREAD

**Issue by ProteanCode** [symfony/symfony#45867]
### Symfony version(s) affected

6.0.6

### Description

When I do create a Form and execute the following code:

```
$parsedErrors = [];

$errors = $form->getErrors(true);
while($errors->current() !== null) {
  $parsedErrors[] = $errors->current();
  $errors->next();
}
```

It crashes with following message

**Return value must be of type Symfony\Component\Form\FormError|Symfony\Component\Form\FormErrorIterator, bool returned**

### How to reproduce

Aside note: my project is an API

Inside a project create a Form and send to it an invalid data with a POST request so the error bad will be filled and the ```$form->getErrors(true)``` should not be empty.

Then run code that looks like this:

```
$parsedErrors = [];

$errors = $form->getErrors(true);
while($errors->current() !== null) {
  $parsedErrors[] = $errors->current();
  $errors->next();
}
```
And web server will throw a 502 http code with critical log at PHP FPM container (I do use docker)

### Possible Solution

For newer version of PHP there are union types, in PHP8 they works like that

```
    public function x(): int|float
    {
        return [
            5, 1.2
        ][rand(0,1)];
    }
```

So adding an bool to the return type of Symfony\Component\Form\FormErrorIterator::current() should be sufficient

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by laurentcacho** [comment]
Is it the same problem as here https://github.com/symfony/symfony/pull/45696 ?

**Comment by stof** [comment]
No. the issue here is that `->current()` gets called on the iterator without checking `->valid()`, which is a misuse of the PHP iteration API. there is no guarantee about how `->current()` behaves when called on an invalid iterator (and here, it breaks).

Btw, instead of rewriting the iteration manually, I strongly suggest using a `foreach` loop that does it for you.

**Comment by stof** [comment]
if not wanting to use `foreach`, the right loop would be `while ($errors->valid())`

**Comment by xabbuh** [comment]
closing then as explained by @stof
