### ISSUE TITLE
Boolean Environment Variable Processor Not Working

### ISSUE THREAD

**Issue by NeuralFramework** [symfony/symfony#45868]
### Symfony version(s) affected

6.0.4

### Description

It is not possible to add boolean values in symfony through the environment variables in the .env file or through the environment variables of the server operating system. Within yaml configuration files it is not possible to assign a string value and be converted to boolean

I have a system generated in kubernetes, in which depending on certain conditions and the different load balancers, values must be assigned to the environment variables to the PODS, in this case some variables are assigned a value "true" or "false" . Internal symfony configurations and some installed bundles require boolean values in the configuration files located in the "config/packages" path.

According to the symfony documentation https://symfony.com/doc/current/configuration/env_var_processors.html it is possible to get the environment variable and give it boolean format

![image](https://user-images.githubusercontent.com/2681400/160338295-e0c9d7a7-34c2-4a8c-aee2-28bd155fcdfb.png)

Now values have been assigned in the symfony .env file with these parameters and it generates the following error message

![image](https://user-images.githubusercontent.com/2681400/160337256-6ded1041-bc06-4a49-82a3-bda5487de0d3.png)

now we generate several options in the configuration file as shown in the image

![image](https://user-images.githubusercontent.com/2681400/160339710-5873c6ba-4281-4fef-85cd-60aaf233b5fa.png)

![image](https://user-images.githubusercontent.com/2681400/160338083-276d9b55-284e-469b-bf35-aaae3a02cda8.png)

### How to reproduce

I have a system generated in kubernetes, in which depending on certain conditions and the different load balancers, values must be assigned to the environment variables to the PODS, in this case some variables are assigned a value "true" or "false" . Internal symfony configurations and some installed bundles require boolean values in the configuration files located in the "config/packages" path.

According to the symfony documentation https://symfony.com/doc/current/configuration/env_var_processors.html it is possible to get the environment variable and give it boolean format

![image](https://user-images.githubusercontent.com/2681400/160338295-e0c9d7a7-34c2-4a8c-aee2-28bd155fcdfb.png)

Now values have been assigned in the symfony .env file with these parameters and it generates the following error message

![image](https://user-images.githubusercontent.com/2681400/160337256-6ded1041-bc06-4a49-82a3-bda5487de0d3.png)

now we generate several options in the configuration file as shown in the image

![image](https://user-images.githubusercontent.com/2681400/160339710-5873c6ba-4281-4fef-85cd-60aaf233b5fa.png)

![image](https://user-images.githubusercontent.com/2681400/160338083-276d9b55-284e-469b-bf35-aaae3a02cda8.png)

**Comment by GromNaN** [comment]
The `bool` processor actually works. But during config processing and container build, environment variables are converted to a "magic" string that is converted back the code that actually read env vars at runtime.
Env var cannot be read at build time. I suspect your issue to come from this trap.

**Comment by NeuralFramework** [comment]
I appreciate your response

I think it is a fairly complex process, but being a complex process they have generated an error because if the treebuilder configures the node in boolean and env(bool:) is used in the yaml files, it should convert the value to boolean and this does not work , converting to "Magic" string and then outputting to boolean precisely at that point is where it causes the problem. I have tried to generate multiple ways to take the format, but none of them have worked for me.

I think it's a bug, because it should generate the format to boolean, but it doesn't, it's completely a bug, the problem shouldn't occur during the process of reading, validating, converting and reversing the internal conversion generated by symfony.

**Comment by nicolas-grekas** [comment]
The error message is not informative enough and this should be improved if possible. But the underlying reason won't change: env vars cannot control what is enabled/disabled/configured *at compile time*. Eg turning the graphiql node on/off at runtime is not possible, while this is what you're asking for by using an env var at this place.

**Comment by NeuralFramework** [comment]
I agree, the error message is not very specific, but we have the information that it is a problem at runtime. Now we must take into account that the configuration values ​​in the yaml files many times cannot be modified by any service or other type of process, many of these configurations are from third-party bundles since only through the yaml configuration file should assign the corresponding value, since it would be necessary for production scenarios in kubernetes to be modifying the source code in the vendors path for the different pods (This is my case).

I have generated the test with several scenarios both of the application located in "src" modifying values ​​stored in the "services" yaml file as well as in the yaml configuration files of api platform, symfony messenger, doctrine, routing, framework and other libraries of third parties.

We must think that if we manage container systems like kubernetes and it is required to manage configuration files with boolean values ​​on, off, true, false, they should work.

We are observing that the flow of the application is reading the configuration files of the framework, which apparently reads the values ​​and handles them as string, int, then converts it into a "Magic" string to then generate the format and conversion of data where the problem occurs.

I reiterate my point of view, from the beginning the data type must be detected to avoid problems when converting from "Magic" string to the values ​​required by symfony and third-party bundles.

**Comment by nicolas-grekas** [comment]
I don't understand what behavior you expect here, but if you're expecting to be able to use an env var at this config node, you must change your expectation as that won't ever be possible. You might want to use static DI parameters instead.

**Comment by NeuralFramework** [comment]
Thanks for your answer

But apparently you have not followed the child of the conversation, fixed values ​​are handled in the configuration files, the image that I added shows true and false text values ​​very well, as well as on and off values, these values ​​according to the documentation are they transform into boolean values, but that conversion is not being generated, at this point you are out of context.

The primary reason is that environment variables stored in the .env file with boolean values ​​('true', 'on', 'yes') are not being converted to their boolean values, according to your solution.

Your solution is like saying: "instead of configuring the database connection data in the .env file, we should then add that data directly in the config/package/doctrine.yaml file".

I think in case you think it's convenient to change the flag to "Feature Request", please do it.

I apologize if there has been any confusion with my request or generated any kind of conflict.

![image](https://user-images.githubusercontent.com/2681400/161035928-76ef7941-651f-47bf-aa99-e40c7d5c0fd8.png)

**Comment by nicolas-grekas** [comment]
> The primary reason is that environment variables stored in the .env file with boolean values ​​('true', 'on', 'yes') are not being converted to their boolean values, according to your solution.

That's correct: env vars are converted to a runtime function call (something like `getenv()`). That means their value is not read at compile time when building the app, but only at runtime. Here, I don't think you want to enable this feature conditionally *at runtime* (aka without rebuilding). If you do, then yes, that's a feat request, and I doubt this is possible (at least not without a significant amount of work). If what you care about is configuring the build itself, you need to provide a static value - not an env var.

I understand this creates confusion for you, you're not the first. See #40794 which opened a discussion on the topic (without much traction/conviction yet, we're still looking for the best approach to this.)

**Comment by GromNaN** [comment]
There is solutions. You can use `env()` in route `condition` to disable a route at runtime. 
You can also inject the env var in the controller to throw a 404 when disabled...

That may require some changes in the bundle you are using.

**Comment by xabbuh** [comment]
Closing here as the behaviour is expected, but we should improve the error message for which we already have an open issue.
