### ISSUE TITLE
 [Notification] You have requested a non-existent service "texter".

### ISSUE THREAD

**Issue by kevintoshi0208** [symfony/symfony#45880]
### Symfony version(s) affected

5.4

### Description

When I try to use the SMS Messenger , it throws the Exception to me.

![image](https://user-images.githubusercontent.com/37921257/160599155-43daf6cd-358d-46a6-8848-039b2bd1fc4c.png)

![image](https://user-images.githubusercontent.com/37921257/160600170-9ad91caa-70cc-461e-9e4b-5032f6ea590b.png)

### How to reproduce

Create a pure symfony project ( I tried the version 5.2 and 5.4 ) and install the notification compoents.

`symfony new my_project_name --version=5.4 --full`

`composer require symfony/notifier
`
execute the command : 

` php bin\console debug:container TexterInterface`

or follow the example of [official website](https://symfony.com/doc/current/notifier/texters.html)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by HypeMC** [comment]
The `texter` service is removed when you have no `texter_transports` set:
https://github.com/symfony/symfony/blob/45d0023f989fbaf1959882d03eab93a5f77ce4e0/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2488-L2494

Did you set up an [SMS Channel](https://symfony.com/doc/5.4/notifier.html#sms-channel)?

**Comment by kevintoshi0208** [comment]
Ok.. after I added texter_transports correctly it was fine.

My ide didn't change the configuration because of some permissions issue.

thank you for yours assistance
