### ISSUE TITLE
[PHPUnitBridge] When only ignoreFile is passed in SYMFONY_DEPRECATIONS_HELPER, deprecations no longer fail tests

### ISSUE THREAD

**Issue by mondrake** [symfony/symfony#45919]
### Symfony version(s) affected

6.1.0

### Description

When only `ignoreFile` is passed in `SYMFONY_DEPRECATIONS_HELPER`, deprecations no longer fail tests, unless you also specifically set `max[total]=0`

### How to reproduce

Use an env var like (from phpunit.xml)

`<env name="SYMFONY_DEPRECATIONS_HELPER" value="ignoreFile=/var/www/d10/core/deprecation-ignore.txt"/>`

Run tests that have unignored deprecations reported;

The exit code of PHPUnit is 0, not 1 as you would expect.

Add `max[total]=0`

`<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[total]=0&ignoreFile=/var/www/d10/core/deprecation-ignore.txt"/>`

Rerun tests;

The exit code of PHPUnit is  1.

**Comment by nicolas-grekas** [comment]
Doesn't #45921 also fix this?

**Comment by mondrake** [comment]
Actually, this could well be working as designed.

When you do not set any SYMFONY_DEPRECATIONS_HELPER variable, the bridge ends up configured by

https://github.com/symfony/symfony/blob/cfd44fbc65c0155ca96273819e301c044c8f18d1/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L268-L270

which is essentially as if configuring with `SYMFONY_DEPRECATIONS_HELPER='strict'` that sets `max[total]=0`

But when you pass a `SYMFONY_DEPRECATIONS_HELPER='ignoreFile=xxx'`, the configuration is by

https://github.com/symfony/symfony/blob/cfd44fbc65c0155ca96273819e301c044c8f18d1/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L272

which in turn sets the thresholds to 999999 in

https://github.com/symfony/symfony/blob/f97db87d0608ebeeff2d7c46b90d3b9c4ec54bae/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Configuration.php#L97-L101

So, either we change the default threshold from 999999 to 0 to make 'strict' reporting the default when SYMFONY_DEPRECATIONS_HELPER is set but does not specifically set thresholds (but that will impact live testing, potentially), or we document that if you move from no use of SYMFONY_DEPRECATIONS_HELPER to using it to indicate the ignoreFile, then you also need to specifically set the `max['whatever']=xx` thresholds.

**Comment by nicolas-grekas** [comment]
Good catch. That's a bug to me. Not setting any `max` should be the same as not setting SYMFONY_DEPRECATIONS_HELPER at all.

**Comment by mondrake** [comment]
OK then, let's change the default.
