### ISSUE TITLE
[ExpressionLanguage] Matches throws error for null values

### ISSUE THREAD

**Issue by ausi** [symfony/symfony#45926]
### Symfony version(s) affected

5.4.7

### Description

In #45875 a behavior change was introduced.

### How to reproduce

Previously the following code worked as expected:

```php
(new ExpressionLanguage)->evaluate('foo matches "/bar/"', ['foo' => null]);
```

Since version 5.4.7 this now throws a `TypeError: Symfony\Component\ExpressionLanguage\Node\BinaryNode::evaluateMatches(): Argument #2 ($str) must be of type string, null given`

### Possible Solution

If this is considered a bug or a BC break I’m happy to create a pull request to fix this (including a deprecation notice for non-string values I’d assume).

**Comment by xabbuh** [comment]
To me it looks sensible to return early if the token to match is null but not a string.

**Comment by nicolas-grekas** [comment]
Up for a PR @ausi? We should just accept null next to string and handle it as the empty string, since that's always been the behavior.

**Comment by ausi** [comment]
> Up for a PR @ausi?

Yes, will do.

**Comment by ausi** [comment]
Done: #45928
