### ISSUE TITLE
[Translation] Push and pull translations commands say OK even no translations were transmitted

### ISSUE THREAD

**Issue by ossinkine** [symfony/symfony#45920]
### Symfony version(s) affected

>=5.4

### Description

I looked at the providers behavior and noticed that in some cases, if the provider API did not respond with a 200 HTTP code, an exception is thrown, and in other cases, it just add the record in the log.

This means that if the provider API responded with for example 503 code (was under maintenance) or any other 5xx code when creating translations, no translations will be pushed, but the `translation:push` command says `[OK] New local translations has been sent`.

We use Crowdin, but looks like other providers have the same behavior.

### How to reproduce

You need to fake the provider API response, like if [there](https://github.com/symfony/symfony/blob/cfd44fbc65c0155ca96273819e301c044c8f18d1/src/Symfony/Component/Translation/Bridge/Crowdin/CrowdinProvider.php#L98) was a 500 response here. No translations will be uploaded but command ends successfully.

### Possible Solution

I suggest to throw an provider exception every time when HTTP request ends unexpected and action is not performed.

**Comment by welcoMattic** [comment]
@ossinkine Thanks for reporting this issue. Actually yes, we should throw an exception if any 5xx error code is returned for any HTTP request in any Provider. 

Feel free to open a PR to fix the problem. If you need help, don't hesitate to ask for it

**Comment by d47081** [comment]
I have same issue, just debug returns 200 code in my case

```
php bin/console translation:push crowdin -vvv
02:46:14 INFO      [http_client] Request: "GET https://api.crowdin.com/api/v2/projects/..."
02:46:15 INFO      [http_client] Response: "200 https://api.crowdin.com/api/v2/projects/..."
02:46:15 INFO      [http_client] Request: "GET https://api.crowdin.com/api/v2/languages?limit=500"
02:46:15 INFO      [http_client] Response: "200 https://api.crowdin.com/api/v2/languages?limit=500"
02:46:15 INFO      [http_client] Request: "GET https://api.crowdin.com/api/v2/projects/..."
02:46:15 INFO      [http_client] Response: "200 https://api.crowdin.com/api/v2/projects/..."
```
