### ISSUE TITLE
Symfony\Component\Cache\Adapter\PdoAdapter::__construct() 1st param DocBlock Comment type should be Connection|\PDO|string

### ISSUE THREAD

**Issue by milanmadar** [symfony/symfony#45956]
### Symfony version(s) affected

5.4.7

### Description

\Symfony\Component\Cache\Adapter\PdoAdapter::__construct() 1st param is `$connOrDsn`.
The DocBlock Comment currently section says:
`@param \PDO|string $connOrDsn`, however it can also be of type `\Doctrine\DBAL\Connection`.

Because of the DocBlock Comment is currently missing the `Connection` type, some static analyzers (phpstan) fails when we provide a `Connection` object.

### How to reproduce

```
use Doctrine\DBAL\DriverManager;
use Symfony\Component\Cache\Adapter\PdoAdapter;

$connUrl = 'mysql://user:passsword@127.0.0.1/db_name';
$conn = DriverManager::getConnection( [ 'url' => $connUrl ]);
new PdoAdapter( $conn, 'mycache', 3600 );
```

Then run phpstan on it

### Possible Solution

in `vendor/symfony/cache/Adapter/PdoAdapter.php` [Link to GitHub line](https://github.com/symfony/cache/blob/5.4/Adapter/PdoAdapter.php#L59) change line 59 to this:

`     * @param \PDO|Connection|string $connOrDsn`

### Additional Context

static analyzer

**Comment by milanmadar** [comment]
I just saw the deprecated note, sorry.

**Comment by GromNaN** [comment]
Since 5.4, `Symfony\Component\Cache\Adapter\DoctrineDbalAdapter` replaced `PdoAdapter` for Doctrine DBAL Connections. https://github.com/symfony/symfony/pull/43362
