### ISSUE TITLE
[Messenger] PHP version required in composer.json isn't supported

### ISSUE THREAD

**Issue by afederau** [symfony/symfony#45955]
### Symfony version(s) affected

5.4.x

### Description

As tried to use the symfony/messenger component in a legacy PHP project I encountered the problem with PHP compatibility. Installed it using composer and according to my PHP 7.3.27 the symfony/messenger (v5.4.3) was installed.
```
$ php -v     
PHP 7.3.27 (cli) (built: Mar 31 2021 10:51:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
```

Although in symfony/messenger comoser.json exists the requirement:
```
    "require": {
        "php": ">=7.2.5",
```
looks like in the component version 5.4.3 the **PHP 8: Constructor property promotion** is used. :(
I tried to downgrade to symfony/messenger (v5.3.x) but encountered the same in symfony/event-dispatcher component (5.4.3) which was added as dependency from other component.

Please check.

### How to reproduce

Autowired the component in the console app I got the error:
```
$ bin/console
[06-Apr-2022 11:34:46 Europe/Berlin] PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in /var/www/html/web/vendor/symfony/messenger/Attribute/AsMessageHandler.php on line 23

Parse error: syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in /var/www/html/web/vendor/symfony/messenger/Attribute/AsMessageHandler.php on line 23
```

**Comment by GromNaN** [comment]
Hello, thanks for your complete report. The class `AsMessageHandler` is for attributes; which can be used starting PHP 8.0+.
Can you clear the cache and run `bin/console -vvv` to get the full error stack trace?

**Comment by stof** [comment]
The requirement in the root package.json is **not** what determine the target platform.

By default, composer resolves dependencies for the PHP version used to run composer, unless you configure a different platform version: https://getcomposer.org/doc/06-config.md#platform

**Comment by afederau** [comment]
> The class AsMessageHandler is for attributes; which can be used starting PHP 8.0+.

It is strange when the class created for PHP 8.0+ is used in component, which requires the PHP>=7.2.5
As mentioned in issue's description it is a legacy app. The autowire is configured only for some selected components. And the console is very simple:
```
#!/usr/bin/env php
<?php
/**
 * basic console
 */
$baseDir = realpath(__DIR__.DIRECTORY_SEPARATOR.'..');
$currDir = getcwd();
// not sure what is best to use: is it application_top.php or application_top_export.php?
//chdir($baseDir);
//require_once 'includes/application_top.php';
chdir(__DIR__);
require_once '../includes/application_top_export.php';

use Xxxxxx\Console\App;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleSignalEvent;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\PhpFileLoader;
use Symfony\Component\EventDispatcher\EventDispatcher;

$dispatcher = new EventDispatcher();
$dispatcher->addListener(ConsoleEvents::SIGNAL, function (ConsoleSignalEvent $event) {
    // gets the signal number
    $signal = $event->getHandlingSignal();

    if (\SIGINT === $signal) {
        echo "User pressed Ctrl-C";
    }
});
$container = new ContainerBuilder();

//(new YamlFileLoader($container, new FileLocator($baseDir . '/config')))
//    ->load('services.yaml');
// in symfony php becomes preferred config language, see this @link https://github.com/symfony/symfony/issues/37186
(new PhpFileLoader($container, new FileLocator($baseDir . '/config')))
    ->load('services.php');

$container->compile();

// App autowire the services and commands
/** @var Application */
$application = $container->get(App::class);
$application->setDispatcher($dispatcher);
// run Application
$application->run();
chdir($currDir);
```
The cache is not used and `bin/console -vvv` outputs the same as in description.

**Comment by afederau** [comment]
> The requirement in the root package.json is **not** what determine the target platform.
> 
> By default, composer resolves dependencies for the PHP version used to run composer, unless you configure a different platform version: https://getcomposer.org/doc/06-config.md#platform

@stof, not sure about package.json, guess You mean composer.json. The root composer.json doesn't have platform settings, and the composer was executed on PHP 7.3.27

**Comment by xabbuh** [comment]
The `AsMessageHandler` shouldn't be loaded by the Messenger component when PHP 8 isn't used. If you think that this is an issue in the Symfony code though, please provide a small example application that allows to reproduce.

**Comment by derrabus** [comment]
We've closed discussions like this multiple times already. The fact that we indicate compatibility with PHP 7.2 does not forbid us to leverage features of newer PHP versions if they're available. You can very well use the messenger component without using the `AsMessageHandler` attribute. Just don't load that class.
