### ISSUE TITLE
[HttpClient] Header Content-Length missing when using callback as request-body

### ISSUE THREAD

**Issue by SiebelsTim** [symfony/symfony#45965]
### Symfony version(s) affected

5.4.7

### Description

In https://github.com/symfony/symfony/pull/45814 the HTTP-Client was changed to *only* set the content-length via the `CURLOPT_INFILE` option. However, that option is not used for `CURLOPT_READFUNCTION`. For that we would need `CURLOPT_POSTFIELDSIZE` which is not exposed in PHP (see https://github.com/php/php-src/issues/8165).

As a result, when using a callback for the request's body, we cannot set the Content-Length header anymore.

In combination with resetting the Transfer-Encoding header to get curl to *not* send a chunked request, we cannot send a request with a body.

### How to reproduce

```php
<?php

use Symfony\Component\HttpClient\CurlHttpClient;

require_once __DIR__ . '/vendor/autoload.php';

$client = new CurlHttpClient([]);

$counter = 0;
$response = $client->request('POST', 'http://localhost:982/iserv/helloworld', [
    'headers' => ['Content-Length' => [10000], 'Transfer-Encoding' => [' ']],
    'body' => static function (int $length) use(&$counter){
        if ($counter++ > 0) {
            return "";
        }

        return str_repeat("A", 10000);
    },
]);

echo $response->getContent();
```

**Comment by sihagen** [comment]
I can report a similar issue (also Symfony 5.4.7): When using a file for the body the Content-Length Header is set, but it
1.  is always set to 0 (propably not or wrong calculated) and
2. cannot be overwritten manually.

```php
$client = new CurlHttpClient();
$response = $client->request('POST', 'https://something', [
    'auth_bearer' => 'xxxxx',
    'headers' => [
        'User-Agent' => 'Custom Agent',
        'Content-Length' => [123456], // without this line the result below stays the same
        'body' => fopen('file', 'r'),
    ],
]);
dump($response);
```
...results in...
```
...
body: Resource id #1176
Accept: */*
Authorization: Bearer xxxxx[ ▶]()
User-Agent: Custom Agent
Accept-Encoding: gzip
Content-Length: 0
...
```
