### ISSUE TITLE
Accept-Language string parsed incorrectly

### ISSUE THREAD

**Issue by Gielovic** [symfony/symfony#45971]
### Symfony version(s) affected

5.4.6

### Description

When using the Accept-Language header value as a local (either by using https://symfony.com/blog/new-in-symfony-5-4-language-negotiation or by listening for a kernel event and using the header to set the Request's locale), the Locale is not correctly determined in case the browser is configured to accept multiple locales.

This value 
`Accept-Language | nl,en-US;q=0.7,en;q=0.3`
Is produced by Firefox when setting Dutch, English (US) and English as browser language.

the BundleEntryReader **Symfony\Component\Intl\Data\Bundle\Reader\BundleEntryReader**

will not extract the locale to be nl.

It uses `Locale::getFallback(string locale)`. In the first iteration it will seems to split on de dash '-' and then try to make sense of "nl,en". Obviously, this is not recognized as a valid locale.

Issues arise when using for instance MoneyField  in EasyAdminBundle. The currency that is being set (f.i. 'EUR') will not be recognized.

### How to reproduce

Configure your browser to use multiple languages.

Use the Accept-Language Header as local, f.i. by using a KernelRequest event
```
    public function onKernelRequest(KernelEvent $event){
        $request = $event->getRequest();
        $lang = $request->headers->get('accept-language');
        if($lang){
            $request->setLocale($lang);
        }
    }

```

Create an EasyAdminCrudController for an entity with a numeric field, and configure the field to be of type [MoneyField](https://symfony.com/doc/current/EasyAdminBundle/fields/MoneyField.html) with setCurrency('EUR').

Expect the following error
**The argument of the "EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField::setCurrency()" method must be a valid currency code according to ICU data ("EUR" given).**

### Additional Context

Running the symfony dev server on ubuntu (20 | 21)

**Comment by stof** [comment]
`Locale::getFallback` and `Request::setLocale` expect a locale, not a `Accept-language header.

**Comment by stof** [comment]
Note that the blog post you linked does not use the header **as** locale. It uses it to determine the locale to be set. Your code snippet is not equivalent to it.

**Comment by Gielovic** [comment]
Tnx for the swift reply. I retried the settings from the blogpost, and indeed it seems to correctly handle the Accept-Language header. 
I somehow misconfigured it I guess, as at first I saw the complete header appearing.
