### ISSUE TITLE
RFC: Filesystem abstraction / Storage abstraction

### ISSUE THREAD

**Issue by sebheitzmann** [symfony/symfony#45986]
### Description

In some application we write files to disk ( upload / export storage / etc ). We can write directly to disk but maybe a more abstract system could be used. 
On docker hosting all these files should be in declared volume and if you simply use file on disk without configure a right volume on the next restart your file are lost ( real story ! ).

I've seen some good library that's abstract some storage.

- Laravel file storage ( https://laravel.com/docs/9.x/filesystem )
- Flysystem lib and bundle ( https://github.com/thephpleague/flysystem )

Maybe the flysystem bundle is the right solution. 

Centralize all the filsystem use could also help to identify all non database data used by the application ( to help backup for exemple )

That's my first Symfony issue so feel free to tell me if i'm not doing things right.

**Comment by shyim** [comment]
A bundle with Flysystem + Symfony Asset URL generation would be nice. We have built something by own in Shopware

**Comment by mathela59** [comment]
Hello, after a short verification, Laravel use the flysystem lib to manage the file system. So you just want an integration of flysystem in Symfony ...

**Comment by sebheitzmann** [comment]
A flysystem bundle already exist. I will try it on a project to see if it cover all my use. The public asset is not covered for exemple.

**Comment by stof** [comment]
To me, Flysystem already solves this properly. I don't see any reason to duplicate that work in Symfony.

**Comment by derrabus** [comment]
I agree with @stof. Symfony itself does not need a storage abstraction and Flysystem should solve your problem.
