### ISSUE TITLE
Symfony not working on SMB

### ISSUE THREAD

**Issue by qinshuze** [symfony/symfony#45990]
### Symfony version(s) affected

6

### Description

Hi I am using Symfony 6 and PHP 8.1.4
I share the project over SMB on Windows and mount the project on Linux, but I run into a problem when running the project, accessing the project keeps waiting until it times out; this only happens on SMB shared directories, running locally when everything works.
How can I get the project to work properly on an SMB shared folder?
English is not my native language; please excuse typing errors.

### How to reproduce

**Share the project folder via SMB on Windows10, mount the shared folder in Linux (Debian11) and run it**
Mount command: `mount -o uid=1000,gid=1000,username=qsz,password=123456,rsize=1048576,wsize=1048576 -t cifs //192.1
68.100.1/Web/mnt/web/`

### Possible Solution

**After investigation, it is found that when the program executes this code under the vendor\symfony\http-kernel\Kernel.php file, it will always get stuck**
![image](https://user-images.githubusercontent.com/22045080/162688820-8fdee041-3aeb-4ee3-9af2-b1cbde1d68b1.png)
Try adding `flock($lock, \LOCK_UN);` before `if (!flock($lock, $wouldBlock ? \LOCK_SH : \LOCK_EX)) {` and the program works fine
![image](https://user-images.githubusercontent.com/22045080/162690194-2207252f-da34-4361-80a7-124f3c1f332c.png)

**Comment by nicolas-grekas** [comment]
Can you try this patch? Does it work around the issue on SMB?
```diff
--- a/src/Symfony/Component/HttpKernel/Kernel.php
+++ b/src/Symfony/Component/HttpKernel/Kernel.php
@@ -528,9 +528,7 @@ abstract class Kernel implements KernelInterface, RebootableInterface, Terminabl
             is_dir($cacheDir) ?: mkdir($cacheDir, 0777, true);
 
             if ($lock = fopen($cachePath.'.lock', 'w')) {
-                flock($lock, \LOCK_EX | \LOCK_NB, $wouldBlock);
-
-                if (!flock($lock, $wouldBlock ? \LOCK_SH : \LOCK_EX)) {
+                if (!flock($lock, \LOCK_EX | \LOCK_NB, $wouldBlock) && !flock($lock, $wouldBlock ? \LOCK_SH : \LOCK_EX)) {
                     fclose($lock);
                     $lock = null;
                 } elseif (!is_file($cachePath) || !\is_object($this->container = include $cachePath)) {
```

**Comment by nicolas-grekas** [comment]
(please send a PR on branch 4.4 if that works)

**Comment by qinshuze** [comment]
Yes this solves my problem with SMB

> Can you try this patch? Does it work around the issue on SMB?
> 
> ```diff
> --- a/src/Symfony/Component/HttpKernel/Kernel.php 
> +++ b/src/Symfony/Component/HttpKernel/Kernel.php 
> @@ -528,9 +528,7 @@ abstract class Kernel implements KernelInterface, RebootableInterface, Terminabl
>              is_dir($cacheDir) ?: mkdir($cacheDir, 0777, true);
>  
>              if ($lock = fopen($cachePath.'.lock', 'w')) {
> -                flock($lock, \LOCK_EX | \LOCK_NB, $wouldBlock);
> - 
> -                 if (!flock($lock, $wouldBlock ? \LOCK_SH : \LOCK_EX)) { 
> +                 if (!flock($lock, \LOCK_EX | \LOCK_NB, $wouldBlock) && !flock($lock, $wouldBlock ? \ LOCK_SH : \LOCK_EX)) {
>                      fclose($lock);
>                      $lock = null;
>                  } elseif (!is_file($cachePath) || !\is_object($this->container = include $cachePath)) {
> ```
