### ISSUE TITLE
traits not being mapped properly by the ORM

### ISSUE THREAD

**Issue by ArturVRSampaio** [symfony/symfony#46003]
### Symfony version(s) affected

6.0.*

### Description

i just created a new symfony 6 project with a TimestampableEntity but the doctrineORM doesnt map the trait variables

### How to reproduce

create a entity and use a trait with private variables just like its shown on this symfonyCast
https://symfonycasts.com/screencast/symfony2-ep3/timestampable

### Additional Context

here it is my timestampableEntity:
![Screenshot_20220411_202032](https://user-images.githubusercontent.com/35453597/162848687-fc4ab6c9-f6d0-4e00-a066-73fe88bd85ad.png)
and here it is an example entity using this trait
![Screenshot_20220411_202418](https://user-images.githubusercontent.com/35453597/162849018-ac3ba879-3719-4ce4-8f93-78f4b089d1a6.png)

**Comment by fabpot** [comment]
If I understand correctly, this is a question/issue for Doctrine, not Symfony. Please, discuss it there.

**Comment by derrabus** [comment]
You're mixing annotations and attributes. Doctrine ORM does not support that.

**Comment by ArturVRSampaio** [comment]
i just solved the problem... the trait anotation was on the old style
here is the fixed trait
![Screenshot_20220412_114447](https://user-images.githubusercontent.com/35453597/162989137-506b7f0b-7d31-4cf6-aa51-d96bd2b81d43.png)

**Comment by e-vural** [comment]
> i just solved the problem... the trait anotation was on the old style here is the fixed trait ![Screenshot_20220412_114447](https://user-images.githubusercontent.com/35453597/162989137-506b7f0b-7d31-4cf6-aa51-d96bd2b81d43.png)

I still have problem. 

<img width="811" alt="image" src="https://user-images.githubusercontent.com/11753784/201603637-0b5fc32a-989c-41e1-b00b-a1d5d05d811e.png">

**Comment by e-vural** [comment]
I found the problem. You have to import classes in trait.

<img width="778" alt="Ekran Resmi 2022-11-14 10 49 29" src="https://user-images.githubusercontent.com/11753784/201604280-ed5a9c39-737f-4c66-a894-aeda14104837.png">
