### ISSUE TITLE
DoctrineExtractor can't return metadata #[ORM\Column(type: 'text', nullable: true)]

### ISSUE THREAD

**Issue by chrisVdd** [symfony/symfony#46029]
### Symfony version(s) affected

6.0.7

### Description

I'm trying to render the Doctrine ORM metadata with the DoctrineExtractor.
The result is null, maybe due to the new format #[ORM\Column(type: 'text', nullable: true)] ?

### How to reproduce

**- I have an entity:**
```php
    // ...
    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private string $subtitle;

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255)]
    #[Gedmo\Slug(fields: ['title'])]
    private string $slug;

    /**
     * @var string
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private string $summary;
```
    
And here a function to retrieve the PropertyInformations:

```php
    public function getPropertyInfo($className)
    {
        $doctrineExtractor = new DoctrineExtractor($this->entityManager);
        $phpDocExtractor        = new PhpDocExtractor();
        $reflectionExtractor    = new ReflectionExtractor();

        return new PropertyInfoExtractor(
            [$reflectionExtractor, $doctrineExtractor],
            [$doctrineExtractor, $phpDocExtractor, $reflectionExtractor],
        );
    }
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by chrisVdd** [comment]
I can provide you the code of what I'm trying to do later this morning.
@xabbuh Just post it here ?

**Comment by xabbuh** [comment]
The best way is to create a new application and then push it to a GitHub repository in your account. You can then link to it here.

**Comment by chrisVdd** [comment]
Here it is @xabbuh

[https://github.com/chrisVdd/test_project](https://github.com/chrisVdd/test_project)

A real quick one, best I can do right now

**Comment by xabbuh** [comment]
Sorry that it took me so late to respond. The information that I see with your app is that the `$title` property is of type `string` and not nullable. What would be the expected result from your point of view?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
