### ISSUE TITLE
Double Kernel boot is possible

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#46039]
### Symfony version(s) affected

6.1

### Description

https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpKernel/Kernel.php#L197

On this line the Kernel is booted when handle() is called. If a Kernel is pre booted by manually firing boot() and then later handling the request, this will result in a double boot.

Should the $this->boot() actually only be fired if the kernel isn't already booted?

### How to reproduce

See above

**Comment by stof** [comment]
The `boot()` method already handles the case where you call it on an already booted kernel

**Comment by trsteel88** [comment]
> The `boot()` method already handles the case where you call it on an already booted kernel

It still iterates over the bundles and then attempts to boot them again though. Seems like unnecessary work?

**Comment by stof** [comment]
No it does not. For a booted kernel, this is the executed code:
https://github.com/symfony/symfony/blob/f1ce8411e89906194df2771082c39f1fb27b5b32/src/Symfony/Component/HttpKernel/Kernel.php#L113-L125

**Comment by trsteel88** [comment]
Oh you're right. Sorry about that! Been staring at code too long today 😬
