### ISSUE TITLE
[phpunit] PHP Fatal error:  Declaration (...) must be compatible with Symfony\Contracts\HttpClient\HttpClientInterface::stream($responses, ?float $timeout = null)

### ISSUE THREAD

**Issue by sunflowerbofh** [symfony/symfony#46032]
### Symfony version(s) affected

6.0.7

### Description

For a project I want to build a debian package from a recent version of symfony. Unfortunately the unittests of Symfony/Component/Notifier fail with the following error:
KO src/Symfony/Component/Notifier
PHP Fatal error:  Declaration of Symfony\Component\HttpClient\CurlHttpClient::stream(Symfony\Contracts\HttpClient\ResponseInterface|iterable $responses, ?float $timeout = null): Symfony\Contracts\HttpClient\ResponseStreamInterface must be compatible with Symfony\Contracts\HttpClient\HttpClientInterface::stream($responses, ?float $timeout = null): Symfony\Contracts\HttpClient\ResponseStreamInterface in /home/kdrexel/build/symfony/src/Symfony/Component/HttpClient/CurlHttpClient.php on line 310

I tried to replace 
`public function stream(ResponseInterface|iterable $responses, float $timeout = null): ResponseStreamInterface`
by
`public function stream(ResponseInterface|iterable $responses, ?float $timeout = null): ResponseStreamInterface`
in both files src/Symfony/Component/HttpClient/CurlHttpClient.php and src/Symfony/Contracts/HttpClient/HttpClientInterface.php, but no effect.

### How to reproduce

Pull the actual 6.0 branch from git, then execute:
```
components="src/Symfony/Component/Notifier"
echo "$components" | parallel --gnu --keep-order 'echo -e "\\nRunning {} tests"; SYMFONY_DEPRECATIONS_HELPER=weak phpunit --colors=always --exclude-group network,tty,benchmark,intl-data,functional,composer {} || (echo -e "\\e[41mKO\\e[0m {}" && $(exit 1));'
```

### Additional Context

Testing environment is debian/sid.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
Rereading the error message I'd guess that you somehow ended up with an incompatible set of dependencies (e.g. using `symfony/http-client` 6 with `symfony/http-client-contracts` < 3.0).

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by sunflowerbofh** [comment]
Thanks for the hint, that was probably part of the problem. I rebuilt (where
necessary) and installed more actual versions of all relevant dependencies, among
others php-symfony-http-client-contracts which has version 3.0.0 now.
Now the error message has changed, I get:

-----------------------%<------------------------------
1) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextDateTime
null does not match expected type "object".

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:106

2) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextDateTimeImmutable
Failed asserting that null is an instance of class "DateTimeImmutable".

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:128

3) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextString
Failed asserting that null matches expected '2010-06-02'.

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:151

4) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextTimestamp
Failed asserting that null matches expected '1275436800'.

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:175

5) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextRaw
null does not match expected type "array".

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:203

6) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextDateTime
null does not match expected type "object".

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:106

7) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextDateTimeImmutable

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:128

8) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextString
Failed asserting that null matches expected '2010-06-02'.

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:151

9) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextTimestamp
Failed asserting that null matches expected '1275436800'.

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:175

10) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextRaw
null does not match expected type "array".

src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php:203
------------------->%------------------------------------

This can be reproduced within the 6.0 branch by doing:

$ component=src/Symfony/Component/Form
$ echo "$component" | parallel --gnu --keep-order '/bin/echo -e "\\nRunning {} tests"; SYMFONY_DEPRECATIONS_HELPER=weak phpunit -v --colors=always --exclude-group network,tty,benchmark,intl-data,functional,composer {} || (/bin/echo -e "\\e[41mKO\\e[0m {}" && $(exit 1));'

Any ideas how to avoid that?


On Wednesday, 2022-04-13, 08:17:18 (GMT -0700), Christian Flothmann wrote:
> Rereading the error message I'd guess that you somehow ended up with an incompatible set of dependencies (e.g. using `symfony/http-client` 6 with `symfony/http-client-contracts` < 3.0).
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/symfony/symfony/issues/46032#issuecomment-1098178891
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

--
