### ISSUE TITLE
[Config] GlobResource causes out of memory errors

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#46046]
### Symfony version(s) affected

^5 || ^6

### Description

There are multiple ways to cause out of memory error while iterating over enough files through a `GlobResource`.

### How to reproduce

Using one of them (assuming there is enough files under `/`).

`$resource = new GlobResource('/', '**');`
`$resource = new GlobResource('/', '/**/');`

`foreach ($resource as $_);`

**Comment by bikalbasnet** [comment]
Hi Alex, As this is related to PHP's "PHP fatal Error: Out Of Memory" error, it depends on `memory_limit` of PHP so increasing that value might help imo.

I tested with about `13667` files (the root of symfony repo) and had and the memory usages was only about 7 MB but may be you tested more?
![image](https://user-images.githubusercontent.com/7262965/164152690-df3d21a9-6422-4c90-b098-6fbd64e17cc4.png)
![image](https://user-images.githubusercontent.com/7262965/164152719-205ab88f-2a39-4828-81f2-479c5c2a35f1.png)

May be you could avoid loading huge files if possible. IMO this is not related to symfony.

**Comment by alex-dev** [comment]
While increasing memory_limit or reducing the file count in base pattern might help, `GlobResource` is an `Iterator`. Out of memory happens only when sorting the files before iterating them in memory. Removing any sort from the GlobResource iteration would remove the risk of running out of memory.

I could trigger out of memory with 100 MB and about 100k files. But numbers should not matter if `GlobResource` was actually yielding results rather than accumulating them in an array before yielding them.

**Comment by stof** [comment]
Removing the sort would mean that if the glob returns the same files in a different order, the computed hash would be different and the resource would be invalidated

**Comment by alex-dev** [comment]
Ok And delaying the sort until filtering is done?
It would require that the final result fit into memory, but not that all files metadata iterated during glob does.

Also, this case would only be hit when using the `Finder` such as with `new GlobResource('/', '/**/*-some-filter/**/*.php')`.
The other code paths all delay sorting as long as possible.

**Comment by alex-dev** [comment]
It would require that the final result fit into memory, but not that all files metadata iterated during glob does.

**Comment by nicolas-grekas** [comment]
Please send a PR if you want to have a look!
