### ISSUE TITLE
[Translation] Add possibility to extends a domain translations

### ISSUE THREAD

**Issue by PululuK** [symfony/symfony#46058]
### Description

Add possibility to extends a domain translations

Consider this case : 

- MyDomainPT = Portuguese trans (contains all PT trans)
- MyDomainAO = Angolan Portuguese trans  (is the same that **MyDomainBase**, but with some specific angolan words)
- MyDomainBR = Brazilian Portuguese trans  (is the same that **MyDomainBase**, but with some specific  brazilian words)

**MyDomainAO** and **MyDomainBR** extends **MyDomainPT**, so if no trans found in these sub trans, it will return the parent trans by default.

### Example

```php

$translator->subTrans('Amor é nutrição pra o espirito', [], 'MyDomainAO', 'MyDomainPT');

```

or 

```php
$translator->trans(
    'Amor é nutrição pra o espirito', 
    [
        'default_trans_domain' =>  'MyDomainPT'
    ], 
   'MyDomainAO'
);

**Comment by stof** [comment]
I think you are confusing domains with locales. Falling back from Brazilian Portuguese to Portuguese is **already** supported (since Symfony 2.0).But that's what the locale is for, not the domain.
