### ISSUE TITLE
[Messenger] RedisTransport can not use MESSENGER_TRANSPORT_DSN with 'redis_cluster=1' as query parameter

### ISSUE THREAD

**Issue by medy36** [symfony/symfony#46055]
### Symfony version(s) affected

6.0

### Description

Trying to configure redis transport in messenger component in AWS Cluster to consume **ASYNC** messages.

### How to reproduce

Setting Redis provider with query param:

`REDIS_PROVIDER=redis://xxx.cache.amazonaws.com:6379?redis_cluster=1` _the query param redis_cluster is mendatory

But when setting `MESSENGER_TRANSPORT_DSN='%env(REDIS_PROVIDER)%/messages'` the validation options method triggers a `Invalid option(s) "redis_cluster" passed to the Redis Messenger transport. Passing invalid options is deprecated` 

https://github.com/symfony/redis-messenger/blob/6b14778e0a6295af023fec637c7b38f918c1a08d/Transport/Connection.php#L288

The only way i managed to handle it so far is by setting explicitly all the nodes to `MESSENGER_TRANSPORT_DSN`

`MESSENGER_TRANSPORT_DSN=redis://xx-cache-0001-xxx.cache.amazonaws.com:6379/messages,redis://xx-cache-0002-xxx.cache.amazonaws.com:6379/messages,redis://xx-cache-0003-xxx.cache.amazonaws.com:6379/messages  `

AM i missing something to handle the redis cluster param or is there an other way to handle this case ?

**Comment by chalasr** [comment]
How would you expect the transport to discover your different nodes if you don't list them explicitly (real question)? 
Unless I'm mistaken, `\RedisCluster` from php-redis (which is what the transport uses under the hood) does not have such discovery feature, it just requires the endpoints of all nodes at construct/connect time in order to interact with them.

**Comment by medy36** [comment]
I don't see any other way than listing them explicitly,  perhaps using RedisArray would be more effective in my case as there is no use of persisting.

@chalasr i am closing the subject, thanks

ps: The discovery feature would have been magic indeed

**Comment by xergio** [comment]
Sorry for reopen this, but someone is missing something here.

Redis Cache Adapter has exactly the feature @medy36 has mentioned and documented here https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

So, why don't we have the same behavior for the Messenger?

Thank you!
