### ISSUE TITLE
JsonLoginAuthenticator::getCredentials() should not allow blank username or password

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony#46100]
### Symfony version(s) affected

All currently supported versions

### Description

When JsonLoginAuthenticator does its job, among other things, it checks that the username passed in the request is a string and that it is not longer than 4096 characters: https://github.com/symfony/symfony/blob/f99f54ab713fbcf285d48bce1e45d7d46420b13c/src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php#L147-L159

Further down below it makes sure that the supplied password is also a string:
https://github.com/symfony/symfony/blob/f99f54ab713fbcf285d48bce1e45d7d46420b13c/src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php#L161-L171

I propose to additionally check that both username and password consist of at least one character each, so that attempts to login with an empty username or password are refused without making attempts to load the user.

### How to reproduce

Enable debugging, add a breakpoint in https://github.com/symfony/symfony/blob/f99f54ab713fbcf285d48bce1e45d7d46420b13c/src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php#L82 and attempt to trigger a JSON login with blank username and password. You will see that no BadRequestHttpException will be caught here and that the logic will proceed creating a Passport object with two useless badges, one for blank username and another for blank password:
https://github.com/symfony/symfony/blob/f99f54ab713fbcf285d48bce1e45d7d46420b13c/src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php#L79-L98

**Comment by bikalbasnet** [comment]
@rimas-kudelis Do you want to open the PR otherwise I can create one right away.

**Comment by rimas-kudelis** [comment]
@bikalbasnet please do, if you don't mind.
