### ISSUE TITLE
[Form] `TimeType` with a `reference_date`, `view_timezone` and `model_timezone` with a `widget` to `single_text` is not displaying correctly with `HTML5` enabled.

### ISSUE THREAD

**Issue by RSickenberg** [symfony/symfony#46137]
### Symfony version(s) affected

6.0.0 - 6.0.8

### Description

Hello folks!

When creating a `TimeType` form field with the `widget` as `single_text` and timezones the displayed value is not properly formatted for the browser.

```php
$fakeEntity = new \stdClass();
$fakeEntity->time = new \DateTime();

// Create the form field
->add('time', TimeType::class, [
    'html5' => true,
    'widget' => 'single_text',
    'view_timezone' => 'Europe/Paris',
    'model_timezone' => 'UTC',
    'reference_date' => new \DateTime('now', new \DateTimeZone('UTC')),
])
```

is outputting in HTML:
```html
<input type="time" id="form_time" name="form[time]" required="required" class="shadow-sm focus:ring-blue focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md" value="2022-04-21 14:49">
```

### How to reproduce

```php
$fakeEntity = new \stdClass();
$fakeEntity->time = new \DateTime();

// Create the form field
->add('time', TimeType::class, [
    'html5' => true,
    'widget' => 'single_text',
    'view_timezone' => 'Europe/Paris',
    'model_timezone' => 'UTC',
    'reference_date' => new \DateTime('now', new \DateTimeZone('UTC')),
])
```

is outputting in HTML:
```html
<input type="time" id="form_time" name="form[time]" required="required" class="" value="2022-04-21 14:49">
```

### Possible Solution

My guess is here: `form/Extension/Core/Type/TimeType.php:84`

We are dealing with the `reference_date` on the `PRE_SUBMIT` event but it's maybe too soon? The date shouldn't be displayed yet with the option `HTML5` enabled.

### Additional Context

![image](https://user-images.githubusercontent.com/16922548/164462692-ab8fb0c3-0c39-425c-9104-b9da3843b25e.png)
> Here a result from my project with the reproduced step.

![image](https://user-images.githubusercontent.com/16922548/164462803-311a3629-6a56-4e91-acc7-d3e569d6e0bd.png)
> And the result if I remove the date from the `value` field.

![image](https://user-images.githubusercontent.com/16922548/164463489-7562d7be-4585-4c0a-80a6-cbde5838101c.png)
> And the result if I set `HTML5` to false.

Many thanks & best regards 😊

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by RSickenberg** [comment]
Hello @xabbuh! 

Sure thing, here for you: https://github.com/RSickenberg/Symfony_bug_46137
You just need to have to get the `/demo` URI.

Regards

**Comment by RSickenberg** [comment]
Sorry for the spam @xabbuh, did you get my notification?

**Comment by xabbuh** [comment]
Yes, but I didn't have the time yet to look into this issue.

**Comment by RSickenberg** [comment]
Sure, no problem :)

**Comment by xabbuh** [comment]
Can you confirm that #46216 fixes it for you?
