### ISSUE TITLE
Dont throw exception when no bundle was found to load a configuration file

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#46135]
### Description

Currently when deactivating a bundle in `config/bundle.php` symfony will throw an exception if the config file are not deleted accordingly like:
```
There is no extension able to load the configuration for "doctrine"
```

This prevents the app from running even if the bundle is not used.

If no extension is able to load configurations the configurations should be ignored and not throw an exception.
Optionally a warning message is logged/printed.

**Comment by wouterj** [comment]
Instead, Symfony recommends to only load the configuration of a specific package in the environment it is enabled in. E.g. you can move `config/packages/doctrine.yaml` to `config/packages/prod/doctrine.yaml` to only enable the DoctrineBundle in production. Or you can use the new `when@prod` feature.

Hiding this error message doesn't seem like a good idea to me.

**Comment by crtl** [comment]
Im not talking about hiding it but converting it to a warning or notice.
Basically I am unable to run the app because I have unused variables (config files).
If there is no extension for them its non of symfonys business because they shouldnt be loaded by it anyways.

**Comment by wouterj** [comment]
Move the configuration to a place where it is not loaded when the bundle is not enabled. This is e.g. how all Symfony applications manage to configure the WebProfilerBundle (which is only enabled in dev).

If you need any help with this, use one of the support channels mentioned at https://symfony.com/support
