### ISSUE TITLE
[Form] Files upload is broken for PHP 8.1 because of new key full_path is added

### ISSUE THREAD

**Issue by p-golovin** [symfony/symfony#46146]
### Symfony version(s) affected

5.4.7, 6.0.7, 6.1

### Description

There is hardcoded array of keys for $_FILES in https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/NativeRequestHandler.php.

It is checked against posted data in two cases:
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/NativeRequestHandler.php#L204
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/NativeRequestHandler.php#L240

In PHP 8.1 was added new key full_path (https://php.watch/versions/8.1/$_FILES-full-path). As a result check is broken and we get incorrect format of image's array at https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/NativeRequestHandler.php#L93 and error that form contains not allowed extra fields.

![image](https://user-images.githubusercontent.com/7702213/164686038-cdb8c598-dda9-406a-96b9-ad2e869fdce1.png)

### How to reproduce

We use Form component as standalone without entire framework but within our cms. Problem looks obvious, but if it will be needed, I'll try to create code for reproduce problem.

### Possible Solution

I've found that such problem was already fixed in HttpFoundation component: https://github.com/symfony/symfony/pull/42112

**Comment by stof** [comment]
Do you want to submit a PR fixing the check ?

**Comment by p-golovin** [comment]
@stof I'll try to make a PR. Will it be good solution to just duplicate unset from HttpFoundation component fix to keep functions logic the same?
