### ISSUE TITLE
[Console] Docblocks in 6.1 are wrongly formatted

### ISSUE THREAD

**Issue by Zarthus** [symfony/symfony#46140]
### Symfony version(s) affected

6.1, 6.0

### Description

https://github.com/symfony/console/blob/6.1/Command/Command.php#L434-L479
https://github.com/symfony/console/blob/6.0/Command/Command.php#L431-L450

In PhpStorm the following docblock is picked up as "The" class rather than, for instance in $mode, a `nullable int`

### How to reproduce

1. in PHPStorm with symfony/console >= 6.1
2. Try the following code snippet
```php
class SfCommand extends \Symfony\Component\Console\Command\Command
{
    protected function configure()
    {
        $this->addOption('foo', 'bar', 'baz', 'desc', 'default',);
    }
}
```

https://github.com/symfony/console/blob/6.1/Command/Command.php#L434-L479

### Possible Solution

The way it looks in 5.4 is fine:

https://github.com/symfony/console/blob/5.4/Command/Command.php#L446-L465

### Additional Context

![image](https://user-images.githubusercontent.com/3660408/164502773-68edc760-e39c-458b-a127-8d9ebd3ce220.png)

**Comment by chalasr** [comment]
Closing for the reason given in https://github.com/symfony/symfony/pull/46218#issuecomment-1113670440 (tldr: not a Symfony bug but a PHPStorm one). Thanks
