### ISSUE TITLE
AbstractSurrogateFragmentRenderer does not detect non-scalar attributes reliably

### ISSUE THREAD

**Issue by m-vo** [symfony/symfony#46152]
### Symfony version(s) affected

4.4 - current

### Description

The `AbstractSurrogateFragmentRenderer` throws an exception if non-scalar values are passed as attributes, but the detection has an early returns in case an attribute's `$value` is an array:

https://github.com/symfony/symfony/blob/f0ffa4742cfd00953e414617b184a7256ab8b45b/src/Symfony/Component/HttpKernel/Fragment/AbstractSurrogateFragmentRenderer.php#L96-L107

### How to reproduce

Pass on attributes in the form `[[], <non-scalar>]`, `containsNonScalars` will return `false` instead of `true`.

### Possible Solution

Something like this:
```php
private function containsNonScalars(array $values): bool
{
    foreach ($values as $value) {
        if (\is_array($value) && $this->containsNonScalars($value)) {
            return true;
        }

        if (!is_scalar($value) && null !== $value) {
            return true;
        }
    }
}
```

**Comment by chalasr** [comment]
Would you mind opening a PR?

**Comment by aschempp** [comment]
see https://github.com/symfony/symfony/pull/47073
