### ISSUE TITLE
AbstractDumper: decimalPoint fails for pt-BR

### ISSUE THREAD

**Issue by rentalhost** [symfony/symfony#46156]
### Symfony version(s) affected

6.0.6

### Description

When I `dd(12.5)`, for instance, it is presented like `float 12.5,0`.

### How to reproduce

`dd(12.5)`

### Possible Solution

I can't help with a definitive solution, but I research where the problem is started, and is basically from `AbstractDumper` constructor, that depends on `localeconv()` information. The float to string conversion occur in `CliDumper::dumpScalar()`.

For me, it returns:

```
array (size=18)
  'decimal_point' => string ',' (length=1)
  ...
```

The float dumper is something like:

```php
            case 'double':
                $style = 'num';

                if (isset($this->styles['float'])) {
                    $style = 'float';
                }

                switch (true) {
                    case \INF === $value:  $value = 'INF'; break;
                    case -\INF === $value: $value = '-INF'; break;
                    case is_nan($value):  $value = 'NAN'; break;
                    default:
                        $value = (string) $value;
                        if (!str_contains($value, $this->decimalPoint)) {
                            $value .= $this->decimalPoint.'0';
                        }
                        break;
                }
                break;
```

But `(string) $value` returns `string '12.5'`, that is incompatible to `localeconv()` info.

My suggestion is detect separator based on a float info directly. For instance:

```php
$this->decimalPoint = str_replace('1', '', (string) 1.1); // => "."
```

**Comment by rentalhost** [comment]
![image](https://user-images.githubusercontent.com/421851/164995037-8727141b-6a82-40d7-a3d8-37cdecfe9985.png)

**Comment by stof** [comment]
Which version of PHP are you using ?

**Comment by stof** [comment]
And which locale is configured on your system ? (the PHP locale as set through `setlocale`, not the Symfony locale).
You can do `dump(setlocale( LC_NUMERIC, '0'));` to get it.

**Comment by rentalhost** [comment]
@stof I am running PHP 8.1.1, Windows 11. The locale is `Portuguese_Brazil.1252`.

**Comment by rentalhost** [comment]
@stof while you asked, I remembered that PHP 8 performs _float to string cast_ with _locale-independent_. So the `.` (dot) will always be used as separator. Then the rule can be even simpler:

```php
$this->decimalPoint = PHP_VERSION_ID >= 80000
    ? '.'
    : str_replace('1', '', (string) 1.1);
```

https://wiki.php.net/rfc/locale_independent_float_to_string
https://php.watch/versions/8.0/float-to-string-locale-independent

**Comment by nicolas-grekas** [comment]
Good call, can you please send a PR on branch 4.4?

**Comment by nicolas-grekas** [comment]
To be independent from the float precision, the check should use substr instead of str_replace, see https://3v4l.org/fkpmo

**Comment by stof** [comment]
Well, for PHP 7, the usage of `localeconv` can be kept instead of trying to do a hack to find it from the string representation of `1.1`. The rule is simple: on PHP 8+ it is always the `.` and on PHP 7- it is always the value provided by `localeconv`

**Comment by nicolas-grekas** [comment]
`$this->decimalPoint = \PHP_VERSION_ID >= 80000 ? '.' : localeconv()['decimal_point'];`

**Comment by rentalhost** [comment]
@stof @nicolas-grekas If it's possible for any of you, please do a PR. I don't have the project here.

**Comment by rentalhost** [comment]
Checked! Now all is working fine.
