### ISSUE TITLE
symfony/console deprecated return type

### ISSUE THREAD

**Issue by s1lver** [symfony/symfony#46163]
### Symfony version(s) affected

6.0.7

### Description

I use to PHP 8.1.5  and when i run the testswith codeception i get the error

```
Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vendor/symfony/console/Helper/HelperSet.php on line 94
```

All composer packages updated

```
php -v

PHP 8.1.5 (cli) (built: Apr 20 2022 11:40:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

### How to reproduce

Run 

```
./vendor/bin/codecept run
```

or

```
./vendor/bin/codecept clean
```

**Comment by wouterj** [comment]
As the issue mentions 6.0.7, I think this is the version of `symfony/console` that you are using. This version already comes with [the traversable return type](https://github.com/symfony/console/blob/v6.0.7/Helper/HelperSet.php#L70-L73).

Please check (e.g. using `composer show symfony/console`) that you indeed installed this version.

**Comment by s1lver** [comment]
Codeception version four do not support symfony/console 6.0.7 (
