### ISSUE TITLE
[RFC][Messenger] Support Redis Pub/Sub

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#46175]
### Description

Where https://github.com/symfony/symfony/pull/30958 relates to introducing more extensive pub/sub capabilities on the AMQP exchanges, the Redis adapter currently does not support pub/sub yet. 

When looking into the other issues that mention pub/sub, it seems AMQP or an external Google Pub/Sub adapter seems to be the only way to support this: https://github.com/symfony/symfony/issues?q=is%3Aissue+pub%2Fsub

In other words, when solely using Redis transports (e.g. due to an infra SLA not allowing RabbitMQ), there is no way to let a single consumer (e.g. one on supervisor) notify all other consumers about an event that happened.

What would it take to introduce [Redis Pub/Sub](https://redis.io/docs/manual/pubsub/) on the [Redis Messenger integration](https://github.com/symfony/redis-messenger)?

### Example

1. Let a K8S scheduled cronjob dispatch generation of a huge xml file, by putting one message per chunk on the Redis Messenger transport 
2. Let 10 background worker containers do the processing of these chunks (100k messages)
3. Let the "finalization" event handler wait until all processing is done and double check everything (1 message)
4. Let that same finalization handler notify a "frontend" transport to which all publicly facing containers have subscribed.
5. The frontend containers should then all fetch the updated version of the huge xml file from the shared storage (a S3 bucket)

Currently, the Redis transport does not support step 5.

**Comment by lyrixx** [comment]
Hello,

I don't think messenger can work with redis / PUB SUB.

Redis PUB SUB is really useful for **notifying**.

So:

* if no subscribers are connected, message is lost
* if the subscriber crash, the message is lost (there is no ack/noack concept)

Messenger is build on top of a "one to one" model not a "one to many". We can bend messenger to achieve it, but that's not a good idea.

so I'm 👎🏼 with this RFC.

---

For your 5th point, I already coded that in my application by using https://github.com/phpredis/phpredis directly. It's really straightforward (pub was in PHP -> sub was in GO)

Another solution would be to use https://mercure.rocks/

**Comment by rvanlaak** [comment]
All valid points, thanks for the response!
