### ISSUE TITLE
Query parameters in UrlGenerator are not url encoded

### ISSUE THREAD

**Issue by Tofandel** [symfony/symfony#46184]
### Symfony version(s) affected

6.0.6

### Description

Generating a url using the UrlGenerator does not urlencode query parameters

### How to reproduce

```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class Demo extends AbstractController
{
    public function __construct(
        protected UrlGeneratorInterface $urlGenerator,
    ) {
    }
    
    #[Route('/auth/login', name: 'login')]
    public function login() {
       return new Response($this->getLoginUrl());
    }
    

    protected function getLoginUrl(): string {
        return $this->urlGenerator->generate('login', ['redirect' => '/abcd/foo']);
    }
}
 ```
 
Assuming you have a route named `login`
`$demo->getLoginUrl()` will return `https://example.com/login?redirect=/abcd/foo`

This url is not spec compliant and the query parameter cannot be read if going to url `https://example.com/login?redirect=/abcd/foo` (Eg `$_GET['redirect']` will not be defined)

### Possible Solution

Query parameters should always be url encoded by default

### Additional Context

Maybe related to #45114

**Comment by stof** [comment]
What do you mean by "this URL is not spec compliant" ? The `/` character does not require escaping in the query string (it has no special meaning there)

**Comment by Tofandel** [comment]
Well that's weird for some reason when I was going to https://example.com/login?redirect=/abcd/foo `$_GET['redirect']` was undefined, it's seems now it is, for some reason, NVM
