### ISSUE TITLE
[DoctrineBridge] Custom UserLoaderInterface: use the same query for loadUserByIdentifier and refreshUser methods

### ISSUE THREAD

**Issue by xavismeh** [symfony/symfony#46187]
### Description

In security component, it is possible to use a custom query when using `Symfony\Bridge\Doctrine\Security\User\EntityUserProvider` (see [related documentation](https://symfony.com/doc/current/security/user_providers.html#using-a-custom-query-to-load-the-user)) and it works fine.
However, this same custom query won't be applied in the `refreshUser` method as it will internally relay on the repository's `find` method.

My suggestion would be to add a custom (and optional — using annotations) method in the `Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface` and then update the `Symfony\Bridge\Doctrine\Security\User\EntityUserProvider::refreshUser` to check if the repository is an instance of `UserLoaderInterface` and has that new optional method declared.

The sample below give more insights on the goal (coded on the fly and has not been tested!) and could be improved (refactoring can go further by, for example, providing a more generic `queryBuilderMethod`)
I could take care of the corresponding PR if that would make sense

### Example

UserLoader
```php
<?php

namespace Symfony\Bridge\Doctrine\Security\User;

/**
 * @method UserInterface|null refreshUser($id)
 */
interface UserLoaderInterface
{ //...
}
````

EntityUserProvider
```php
<?php

namespace Symfony\Bridge\Doctrine\Security\User;

class EntityUserProvider implements UserProviderInterface, PasswordUpgraderInterface
{
    // ...
   // current line 92 where changes need to be applied:
   public function refreshUser(UserInterface $user)
        $class = $this->getClass();
        if (!$user instanceof $class) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_debug_type($user)));
        }

        $repository = $this->getRepository();
        if ($repository instanceof UserProviderInterface) {
            $refreshedUser = $repository->refreshUser($user);
        } else {
            // The user must be reloaded via the primary key as all other data
            // might have changed without proper persistence in the database.
            // That's the case when the user has been changed by a form with
            // validation errors.
            if (!$id = $this->getClassMetadata()->getIdentifierValues($user)) {
                throw new \InvalidArgumentException('You cannot refresh a user from the EntityUserProvider that does not contain an identifier. The user object has to be serialized with its own identifier mapped by Doctrine.');
            }

            if ($repository instanceof UserLoaderInterface && method_exists($repository, 'refreshUser')) {
               $refreshedUser = $repository->refreshUser($id);
            } else {
                $refreshedUser = $repository->find($id);
            }

            if (null === $refreshedUser) {
                $e = new UserNotFoundException('User with id '.json_encode($id).' not found.');
                $e->setUserIdentifier(json_encode($id));

                throw $e;
            }
        }

        return $refreshedUser;
    }
}
```

My custom repository
```php
<?php

namespace App\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

class UserRepository extends ServiceEntityRepository implements UserLoaderInterface
{
    // ...

    /**
     * @inheritDoc
     */
    public function loadUserByIdentifier(string $username): ?User
    {
        return $this->createQueryBuilderForUserProvider()
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }


    /**
     * @inheritDoc
     */
    public function refreshUser($id): ?User
    {
        return $this->createQueryBuilderForUserProvider()
            ->where('u.id = :user_id')
            ->setParameter('user_id', $id)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    private function createQueryBuilderForUserProvider(): QueryBuilder
    {
        return $this->createQueryBuilder('u'); // Additional criteria
    }
}
```

**Comment by stof** [comment]
if you need to customize both finding the user by identifier and refreshing it, it solution is to implement the UserProviderInterface instead of relying on the EntityUserProvider. there is no point allowing EntityUserProvider to proxy all the APIs of UserProviderInterface

**Comment by xavismeh** [comment]
This is what I did originally but thought about it. It's always a pain for me to rewrite something that already does 90% of the work and benefit from a better testing quality. Feel free to close this feature request

**Comment by stof** [comment]
Well, if you forward all the logic to your own implementation, the testing quality won't matter, because it would be testing code that you don't use (as the logic that runs would be your own one).

If you do both the user loading and the user refreshing in your own code, the remaining logic in the provider is only doing 1% of the work (the `supportsClass` method)

**Comment by stof** [comment]
So this gets a -1 from me. Let's see what other members of the core team think about it though.

**Comment by xavismeh** [comment]
I get your point regarding the "remaining logic in the provider is only doing 1%" and that's exactly why I immediately suggested to go further in the implementation.
However, regardless the decision making outcome, I'll create a PR in the doc anyway as it does not mention this "limitation" and might lead the reader to conclude that the same query will be used

**Comment by xabbuh** [comment]
I agree with @stof here. So I am closing this issue. But thank you for the suggestion anyway @xavismeh. Looking forward to review your docs PR.
