### ISSUE TITLE
Allow extension of bin/console about

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#46186]
### Description

It would be nice for third parties to add content to the "about" command output, for example when developing a content management system on top of symfony. This way developers that are familiar with symfony can use "bin/console about" to get _all_ information about the system including not only the symfony/kernel/php things but also the information about third-party bundles that are installed.

I thought about using the event dispatcher which should work since symfony/framework-bundle already depends symfony/event-dispatcher.

There may also be a way by overwriting `Symfony\Bundle\FrameworkBundle\Command\AboutCommand`... but I think this would not work when more than one bundle tries to overwrite this class (ignoring the fact that the class would be pretty update incompatible anyway then).

Any ideas on this? :-)

### Example

```php
<?php

namespace Symfony\Bundle\FrameworkBundle\Command;

class AboutCommand extends Command
{

    // (...)

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        /** @var KernelInterface $kernel */
        $kernel = $this->getApplication()->getKernel();

        if (method_exists($kernel, 'getBuildDir')) {
            $buildDir = $kernel->getBuildDir();
        } else {
            $buildDir = $kernel->getCacheDir();
        }

        $info = [
            'symfony' => [
                'label' => 'Symfony',
                'rows' => [
                    ['Version', Kernel::VERSION],
                    ['Long-Term Support', 4 === Kernel::MINOR_VERSION ? 'Yes' : 'No'],
                    ['End of maintenance', Kernel::END_OF_MAINTENANCE.(self::isExpired(Kernel::END_OF_MAINTENANCE) ? ' <error>Expired</>' : ' (<comment>'.self::daysBeforeExpiration(Kernel::END_OF_MAINTENANCE).'</>)')],
                    ['End of life', Kernel::END_OF_LIFE.(self::isExpired(Kernel::END_OF_LIFE) ? ' <error>Expired</>' : ' (<comment>'.self::daysBeforeExpiration(Kernel::END_OF_LIFE).'</>)')],
                ],
            ],
            'kernel' => [
                'label' => 'Kernel',
                'rows' => [
                    ['Type', \get_class($kernel)],
                    ['Environment', $kernel->getEnvironment()],
                    ['Debug', $kernel->isDebug() ? 'true' : 'false'],
                    ['Charset', $kernel->getCharset()],
                    ['Cache directory', self::formatPath($kernel->getCacheDir(), $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($kernel->getCacheDir()).'</>)'],
                    ['Build directory', self::formatPath($buildDir, $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($buildDir).'</>)'],
                    ['Log directory', self::formatPath($kernel->getLogDir(), $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($kernel->getLogDir()).'</>)'],
                ],
            ],
            'php' => [
                'label' => 'PHP',
                'rows' => [
                    ['Version', \PHP_VERSION],
                    ['Architecture', (\PHP_INT_SIZE * 8).' bits'],
                    ['Intl locale', class_exists(\Locale::class, false) && \Locale::getDefault() ? \Locale::getDefault() : 'n/a'],
                    ['Timezone', date_default_timezone_get().' (<comment>'.(new \DateTime())->format(\DateTime::W3C).'</>)'],
                    ['OPcache', \extension_loaded('Zend OPcache') && filter_var(ini_get('opcache.enable'), \FILTER_VALIDATE_BOOLEAN) ? 'true' : 'false'],
                    ['APCu', \extension_loaded('apcu') && filter_var(ini_get('apc.enabled'), \FILTER_VALIDATE_BOOLEAN) ? 'true' : 'false'],
                    ['Xdebug', \extension_loaded('xdebug') ? 'true' : 'false'],
                ],
            ],
        ];

        /** @var EventDispatcher $eventDispatcher */
        $eventDispatcher = $kernel->getContainer()->get('event_dispatcher');

        $event = $eventDispatcher->dispatch(
            new AboutCommandAdditionalInformationEvent($info),
            AboutCommandAdditionalDataEvent::NAME,
        );

        $firstId = array_key_first($info);
        foreach ($event->getInfo() as $id => $data) {
            if ($id !== $firstId) {
                $rows[] = new TableSeparator();
            }
            $rows[] = ['<info>' . $data['label'] . '</>'];
            $rows[] = new TableSeparator();
            foreach ($data['rows'] as $row) {
                $rows[] = $row;
            }
        }

        $io->table([], $rows);

        return 0;
    }

    // (...)

}
```

**Comment by 94noni** [comment]
The event system could be great yes
Would like to have such option like we can add our own profiler collector for example

**Comment by javiereguiluz** [comment]
With the proposed system, some third-party app could change the `symfony` section (e.g. replacing "Symfony" by their own name, misleading users) or even removing some sections entirely (e.g.  the whole Symfony section).

I'm not saying that we shouldn't allow that ... but we should think carefully if we want to allow that. Thanks!

**Comment by ghost** [comment]
Yeah, a couple days ago I spend a second thought on the example implementation and that's what came to my mind as well. We should definitely make sure that third parties cannot change the default output.
Maybe using the event as a collection of third party content that can be appended to the existing output or something like that.

**Comment by kl7197519** [comment]
> ### Description
> 
> It would be nice for third parties to add content to the "about" command output, for example when developing a content management system on top of symfony. This way developers that are familiar with symfony can use "bin/console about" to get _all_ information about the system including not only the symfony/kernel/php things but also the information about third-party bundles that are installed.
> 
> I thought about using the event dispatcher which should work since symfony/framework-bundle already depends symfony/event-dispatcher.
> 
> There may also be a way by overwriting `Symfony\Bundle\FrameworkBundle\Command\AboutCommand`... but I think this would not work when more than one bundle tries to overwrite this class (ignoring the fact that the class would be pretty update incompatible anyway then).
> 
> Any ideas on this? :-)
> 
> ### Example
> 
> ```php
> <?php
> 
> namespace Symfony\Bundle\FrameworkBundle\Command;
> 
> class AboutCommand extends Command
> {
> 
>     // (...)
> 
>     protected function execute(InputInterface $input, OutputInterface $output): int
>     {
>         $io = new SymfonyStyle($input, $output);
> 
>         /** @var KernelInterface $kernel */
>         $kernel = $this->getApplication()->getKernel();
> 
>         if (method_exists($kernel, 'getBuildDir')) {
>             $buildDir = $kernel->getBuildDir();
>         } else {
>             $buildDir = $kernel->getCacheDir();
>         }
> 
>         $info = [
>             'symfony' => [
>                 'label' => 'Symfony',
>                 'rows' => [
>                     ['Version', Kernel::VERSION],
>                     ['Long-Term Support', 4 === Kernel::MINOR_VERSION ? 'Yes' : 'No'],
>                     ['End of maintenance', Kernel::END_OF_MAINTENANCE.(self::isExpired(Kernel::END_OF_MAINTENANCE) ? ' <error>Expired</>' : ' (<comment>'.self::daysBeforeExpiration(Kernel::END_OF_MAINTENANCE).'</>)')],
>                     ['End of life', Kernel::END_OF_LIFE.(self::isExpired(Kernel::END_OF_LIFE) ? ' <error>Expired</>' : ' (<comment>'.self::daysBeforeExpiration(Kernel::END_OF_LIFE).'</>)')],
>                 ],
>             ],
>             'kernel' => [
>                 'label' => 'Kernel',
>                 'rows' => [
>                     ['Type', \get_class($kernel)],
>                     ['Environment', $kernel->getEnvironment()],
>                     ['Debug', $kernel->isDebug() ? 'true' : 'false'],
>                     ['Charset', $kernel->getCharset()],
>                     ['Cache directory', self::formatPath($kernel->getCacheDir(), $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($kernel->getCacheDir()).'</>)'],
>                     ['Build directory', self::formatPath($buildDir, $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($buildDir).'</>)'],
>                     ['Log directory', self::formatPath($kernel->getLogDir(), $kernel->getProjectDir()).' (<comment>'.self::formatFileSize($kernel->getLogDir()).'</>)'],
>                 ],
>             ],
>             'php' => [
>                 'label' => 'PHP',
>                 'rows' => [
>                     ['Version', \PHP_VERSION],
>                     ['Architecture', (\PHP_INT_SIZE * 8).' bits'],
>                     ['Intl locale', class_exists(\Locale::class, false) && \Locale::getDefault() ? \Locale::getDefault() : 'n/a'],
>                     ['Timezone', date_default_timezone_get().' (<comment>'.(new \DateTime())->format(\DateTime::W3C).'</>)'],
>                     ['OPcache', \extension_loaded('Zend OPcache') && filter_var(ini_get('opcache.enable'), \FILTER_VALIDATE_BOOLEAN) ? 'true' : 'false'],
>                     ['APCu', \extension_loaded('apcu') && filter_var(ini_get('apc.enabled'), \FILTER_VALIDATE_BOOLEAN) ? 'true' : 'false'],
>                     ['Xdebug', \extension_loaded('xdebug') ? 'true' : 'false'],
>                 ],
>             ],
>         ];
> 
>         /** @var EventDispatcher $eventDispatcher */
>         $eventDispatcher = $kernel->getContainer()->get('event_dispatcher');
> 
>         $event = $eventDispatcher->dispatch(
>             new AboutCommandAdditionalInformationEvent($info),
>             AboutCommandAdditionalDataEvent::NAME,
>         );
> 
>         $firstId = array_key_first($info);
>         foreach ($event->getInfo() as $id => $data) {
>             if ($id !== $firstId) {
>                 $rows[] = new TableSeparator();
>             }
>             $rows[] = ['<info>' . $data['label'] . '</>'];
>             $rows[] = new TableSeparator();
>             foreach ($data['rows'] as $row) {
>                 $rows[] = $row;
>             }
>         }
> 
>         $io->table([], $rows);
> 
>         return 0;
>     }
> 
>     // (...)
> 
> }
> ```

**Comment by Tobion** [comment]
Does not seem worth to me. You could just add your own about command or unregister the AboutCommand and replace it with your own if you want in your app.

**Comment by fabpot** [comment]
I agree with @Tobion.
