### ISSUE TITLE
Non-standard inheritDoc tag

### ISSUE THREAD

**Issue by neclimdul** [symfony/symfony#46196]
### Symfony version(s) affected

6.1

### Description

Poking through some documentation I noticed most of the usage of the inheritDoc tag in the symfony code base use the non-standard all lowercase `{@inheritdoc}` version instead of the standard camel case `{@inheritDoc}`. There is some usage of the later but it is uncommon in comparison.

Both the [phpdoc documentation](https://docs.phpdoc.org/guide/guides/inheritance.html#the-inheritdoc-tag) and the proposed [psr standard](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#42-using-the-inheritdoc-inline-tag-to-augment-a-description) use the camel case version of the tag.

### How to reproduce

```
neclimdul:symfony/ (6.1✗) $ git grep inheritdoc | wc -l
2952
neclimdul:symfony/ (6.1✗) $ git grep inheritDoc | wc -l
20
```

### Possible Solution

I started to open a pull request to just fix this but it touches so many files across so many components I figured open a discuss to see if it would be easier for maintainers to have some sort of split version or all at once or if there was just no interest in fixing it.

### Additional Context

you can see the changes here: https://github.com/neclimdul/symfony/commit/753e4747f5521480780f81c1a2ef0afb76108c3c

**Comment by derrabus** [comment]
Unless this "non-standard" usage causes actual problems, I guess we have no interest in fixing it.

**Comment by neclimdul** [comment]
I'm not sure I understand. Well its wrong, it causes confusion, and its being used inconsistently. That 3, albeit small, problems. It can't really cause a functional problem because its documentation.

**Comment by wouterj** [comment]
I agree with @derrabus. "Small" changes like this one result in a non proportional merge cost (given merge conflicts when merging from 4.4 -> 5.4 -> 6.0 -> 6.1 and having to repeat this for each version to fix new occurrences). As such, the "problems" must be functional in order to be worth the costs.

I have not seen issues with tools parsing PHPdoc (PHPstorm, static analysers, phpDocumentor). Unless they have a functional error with inheritDoc, I'm :-1: on fixing this.

**Comment by neclimdul** [comment]
makes me uncomfortable for the other documentation improvements I've been writing but ok.

**Comment by nicolas-grekas** [comment]
I think the correct approach here would be to update these pages on phpdocumentor+php-fig to say this annotation is case insensitive, since it's always been so.

**Comment by fabpot** [comment]
I would support removing these annotations when they are not needed (probably 99% of the current usages).

**Comment by stof** [comment]
Especially given that most of our usages of the inline `{@inheritdoc}` tag are wrong, as they were expecting a behavior corresponding to the block `@inheritdoc` (that was not yet a thing when we started Symfony 2, as they added it based on our usage).
And given that phpdoc is inherited by default, the block-level `@inheritdoc` is equivalent to removing the phpdoc entirely.

**Comment by ro0NL** [comment]
see also https://youtrack.jetbrains.com/issue/WI-23586, AFAIK phpstorm isnt fixed still

**Comment by neclimdul** [comment]
So removal is technically an option. For me, I dislike that because as someone currently reviewing a component and trying to add documentation for confusing or complicated pieces of code it tells me explicitly without any need for understanding what interfaces exist or anything else that the method has some parent with all the needed documentation. There's often plenty enough to trying to figure out so being explicit is very helpful.

As stof pointed out, that was the intention of @inheritdoc but unfortunately any implementation and adoption of that has stalled. Which means, unless you're running the phpdoc runtime where I guess its broken, the effective/de facto standard today is the use of {@inheritDoc} as acknowledged by the phpdoc documentation.
