### ISSUE TITLE
Component/Notifier/Bridge directory missing in 6.8.0 tarball?

### ISSUE THREAD

**Issue by sunflowerbofh** [symfony/symfony#46204]
### Symfony version(s) affected

6.8.0

### Description

While building a debian package from the symfony v6.0.8.tar.gz I found that the directory src/Symfony/Component/Notifier/Bridge is missing. But there are scripts which source this directory, e.g. src/Symfony/Component/Notifier/Transport.php:
`use Symfony\Component\Notifier\Bridge\Yunpian\YunpianTransportFactory;`
Is there a special reason why this directory is not there although there are some references to it?

### How to reproduce

Download the 6.8.0 tarball (https://github.com/symfony/symfony/archive/refs/tags/v6.0.8.tar.gz) and unpack it.
Grep for a bridge component through src/symfony, e.g. Yunpian
`$ grep -r Yunpian src/Symfony/`
Open the scripts which are found, e.g.
`vi src/Symfony/Component/Notifier/Transport.php`
and look for Yunpian.

### Possible Solution

Add the Bridge directory src/Symfony/Component/Notifier/Bridge to the tar archive.

**Comment by fabpot** [comment]
That's expected as this is the way we are handling bridges.
You should **never** use symfony/symfony, but the individual components instead.
