### ISSUE TITLE
Cache key contains reserved characters

### ISSUE THREAD

**Issue by blackarcanis** [symfony/symfony#46201]
### Symfony version(s) affected

5.4.8

### Description

Hi!
I have upgraded our project today from 5.4.7 to 5.4.8 and got this error while trying to load our app immediately:
`Cache key "XXXXCoreBundle:EntityName__CLASSMETADATA__" contains reserved characters "{}()/\@:".`

Not sure why getting this error while doing a minor version upgrade. I'm using the "bundle" name convention since 2013 and don't want to change that for now. It was working perfectly in 5.4.7 and before; why this sudden change?

How can I roll back to use specifically Symfony 5.4.7 while you are working on this?

Thank you!

### How to reproduce

Upgrade from 5.4.7 to 5.4.8 while using the old bundle convention name for Repository/Entity naming ORM.

**Comment by blackarcanis** [comment]
Double checked and it was an issue with the new version of "doctrine/persistence" from 2.5 to 3. Closed.

**Comment by junowilderness** [comment]
@blackarcanis What you wrote [is true](https://github.com/doctrine/persistence/issues/184). doctrine/persistence 3.0 drops its dependency on doctrine/cache, which I assume means that the Symfony cache implementation takes over. That implementation does not like the cache key. But, how do we set a compatible cache key in Symfony apps?

**Comment by junowilderness** [comment]
By passing FQCNs to `getRepository`, this is fixed for us:

```diff
-        $staff = $em->getRepository('App:User')->findAll();
+        $staff = $em->getRepository(User::class)->findAll();
```

**Comment by stof** [comment]
Well, doctrine/persistence dropped support for the `App:User` notation, which also means that it dropped support for converting those to a valid cache key (that string was never passed to the cache layer in doctrine/persistence 2 as it was resolved to the actual class name first).

**Comment by junowilderness** [comment]
I probably had been ignoring deprecation messages.

**Comment by blackarcanis** [comment]
> By passing FQCNs to `getRepository`, this is fixed for us:
> 
> ```diff
> -        $staff = $em->getRepository('App:User')->findAll();
> +        $staff = $em->getRepository(User::class)->findAll();
> ```

Yes, it's exactly what I did after taking care to read the changelog of doctrine/persistence.
