### ISSUE TITLE
it is not possible getUser from Service

### ISSUE THREAD

**Issue by eerison** [symfony/symfony#46215]
### Symfony version(s) affected

5.4.8

### Description

I'm trying to [fetch a user from a service](https://symfony.com/doc/5.4/security.html#fetching-the-user-from-a-service), but always it comes null, I'm using `form_login`, any idea why?

security version

```
symfony/security-bundle            v5.4.8  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.4.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.3  Symfony Security Component - Guard
symfony/security-http              v5.4.8  Symfony Security Component - HTTP Integration
``` 

php -v

```
PHP 8.1.4 (cli) (built: Mar 18 2022 18:25:47) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
```

### How to reproduce

create a service and add Security class as dependency

```php
public function __construct(private readonly Security $security)
``` 

and try to get the user

```
$this->security->getUser();
```

it should return the user authenticated!

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by eerison** [comment]
Hi @xabbuh 

I'm doing this in a public project and you can see the example that I'll post here


I created this service: https://github.com/eerison/myprofile/pull/604/files#diff-941bf5054b6e05d462b68fb39a6380da440b1ea1a521895efa37e27a8f287d5aR9

That was used for this EventSubscriber: https://github.com/eerison/myprofile/pull/604/files#diff-7719ef5279f4742a6d682c4c85dbdf15366ad38c795d36cceddab1e8ef0bfa25R13


it's the security.yaml changes: https://github.com/eerison/myprofile/pull/604/files#diff-19446c4b69407952b20ae26dbd032cdad8dcc487db081a5cb17261831e80a4ccR2

But I don't know if there is something missing here!


@xabbuh does it help you some how?

**Comment by xabbuh** [comment]
Are you sure that your event listener isn’t simply triggered before Symfony‘s security listener being executed?

**Comment by eerison** [comment]
> Are you sure that your event listener isn’t simply triggered before Symfony‘s security listener being executed?

I don't know :/  I didn't change any priority! But in theory it should work after **I login** and **refresh the page**, Because when I refresh the page the user is already authenticated and the order should not be important! I guess 😄

**Comment by wouterj** [comment]
> the order should not be important

There is always an authentication process. After logging in, the token is stored in the session. A listener (`ContextListener`) is responsible for reading the session and re-authenticating the token. This listener runs as early as possible, but it is still possible to have listeners that run before this (e.g. the routing listener runs before the context listener by design).

**Comment by eerison** [comment]
Hey @wouterj Thanks for your answer :) 

> e.g. the routing listener runs before the context listener by design

then is it possible I change the priority of my Listener to run after `ContextListener`? I didn't find in the doc what is the priority number for `ContextListener` 👀 

**Edit 1:** or change the priority can't help me 👀 ?

**Edit 2:** I saw that `ContextListener` run in `kernel.response` with priority `0`, But the I didn't see any Doctrine event in profile debug ....

**Comment by chalasr** [comment]
> But the I didn't see any Doctrine event in profile debug ....

Can you elaborate? 
This can be solved with a note in the docs if I understand correctly?

**Comment by eerison** [comment]
Hi @chalasr 

> This can be solved with a note in the docs if I understand correctly?

I guess it can't be solved by add some docs!

> Can you elaborate?

Ok, we were thinking that my event listener was called before initialise `ContextListener` or `SecurityListener`, But I looked in the profile page and I didn't see any Event listener regarding **DoctrineEvents** as you can see in this screenshot

<img width="1792" alt="Screenshot 2022-05-04 at 11 32 18" src="https://user-images.githubusercontent.com/6358755/166657036-16ea5b3f-18c7-4576-a0bd-13da222fded9.png">


Then I don't now what  I should do to solve this issue!

**Comment by stof** [comment]
Doctrine listeners are a totally different thing than Symfony listeners.

And a postLoad event of the ORM can totally happen before the Symfony authentication is complete if the ORM is used before that (and it **will** happen with 100% certainty if your user provider is loading the user using the ORM)

**Comment by eerison** [comment]
Hey @stof 

Yeah you are right! I tested getting others users and I can get the user logged, then It's related with order that it's executed!

I can confirm that getUser from service is working!

Thank you for replay!
