### ISSUE TITLE
[BC Break] UniqueEntity constraint in embedded forms

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#46219]
### Symfony version(s) affected

6.0.8

### Description

Using a UniqueEntity constraint in an embedded form gives me this error:
Unable to find the object manager associated with an entity of class "Proxies\__CG__\App\Entity\User".

Where User is the entity that imposes the constraint.

This happens only in embedded forms (works in stanalone forms) and only when entity is updated. (create works)

### How to reproduce

Reproducer: https://github.com/Shoplifter/symfony_issue_46219

### Additional Context

I stumbled upon this bug after I have upgraded a project by 3 or 4 pacth version numbers to 6.0.8 
and I also switched from annotations to php8 attributes in my entity configuration.
So maybe this happens only when you use attributes, I have not tested this with annotations.

I reproduced this at Windows 11 / Apache 2.4 / MySQL 8.0.11 / PHP 8.1.1 / Symfony 6.0.8
But it also occured in a real world project  at Ubuntu 18.04 and MySQL 5.7.37

dev.log says:
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\ConstraintDefinitionException: "Unable to find the object manager associated with an entity of class "Proxies\__CG__\App\Entity\User"." at C:\app\Symfony.Reproducer\vendor\symfony\doctrine-bridge\Validator\Constraints\UniqueEntityValidator.php line 81 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\ConstraintDefinitionException(code: 0): Unable to find the object manager associated with an entity of class \"Proxies\\__CG__\\App\\Entity\\User\". at C:\\app\\Symfony.Reproducer\\vendor\\symfony\\doctrine-bridge\\Validator\\Constraints\\UniqueEntityValidator.php:81)"} []

running in prod env no log is written but in the browser window it says:
Notice: fwrite(): Write of 457 bytes failed with errno=9 Bad file descriptor in C:\app\Symfony.Reproducer\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 178

Notice: fwrite(): Write of 457 bytes failed with errno=9 Bad file descriptor in C:\app\Symfony.Reproducer\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 178

**Comment by Shoplifter** [comment]
I also tried with annotations now instead of attributes, but that does not change a thing

**Comment by Shoplifter** [comment]
Just verified that this worked until 6.0.3.

**Comment by jdelaune** [comment]
I'm also seeing this in a lot of places now after upgrading Symfony. I'm not even using embedded forms. Looks to be an issue with related entities.

**Comment by jdelaune** [comment]
```
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "<=5.4.7"
        }
    },
```

This works for me as a temporary solution. Need to figure out which symfony package has introduced the issue now.

**Comment by jdelaune** [comment]
For me the issue stemmed from the `doctrine/persistence` package (namely version 3.)

@Shoplifter `"doctrine/persistence": "^2.5",` Does adding this to your composer.json and updating work in your scenario as well?

**Comment by Shoplifter** [comment]
@jdelaune  that might be a different bug. The one I reported occurs beginning with version 6.0.4.
anyway, you're right. I did
    
    "conflict": {
        "symfony/symfony": "*",
        "doctrine/persistence": ">=3.0"
    },
    
... and it worked.

**Comment by stof** [comment]
If `getEntityManagerForClass` does not work anymore when passing the name of the proxy class, this is a bug in doctrine/persistence 3.0 and should be reported there. It was not expected to be removed.

**Comment by stof** [comment]
@Shoplifter that's probably because symfony/doctrine-bridge 6.0.3 was not compatible with doctrine/persistence 3, and so you were using doctrine/persistence 2 as well at that time.

**Comment by Shoplifter** [comment]
@stof Yup - doctrine/persistence 2.5.2
Anyway: I installed all that very strightforward doing` composer require symfony/orm-pack`

`composer why doctrine/persistence` gives me:

```
doctrine/common           3.3.0   requires   doctrine/persistence (^2.0 || ^3.0)
doctrine/doctrine-bundle  2.6.3   requires   doctrine/persistence (^2.2|^3)
doctrine/orm              2.12.2  requires   doctrine/persistence (^2.4 || ^3)
symfony/doctrine-bridge   v6.0.8  requires   doctrine/persistence (^2|^3)
symfony/framework-bundle  v6.0.8  conflicts  doctrine/persistence (<1.3)
```
    
so maybe additional version constraints in symfony/doctrine-bridge?

**Comment by stof** [comment]
Well, symfony/doctrine-bridge **intentionally* supports version 3. If that version has a bug, that's something to report to them so that they fix it. That's not a reason for Symfony to change its requirements (where the change of requirements might reach a release after the upstream fix is available anyway)

**Comment by Shoplifter** [comment]
closing this in favour of https://github.com/doctrine/persistence/issues/293
