### ISSUE TITLE
[Intl component] Can't get alpha2 language code

### ISSUE THREAD

**Issue by Forticas** [symfony/symfony#46213]
### Symfony version(s) affected

6.0.7

### Description

When trying to get all alpha 2 Languages codes with this code: 

```php
use Symfony\Component\Intl\Languages;
\Locale::setDefault('en');
       
$languages = Languages::getAlpha3Codes();

foreach ($languages as $alpha3Code) {
    if(Languages::alpha3CodeExists($alpha3Code))
    dump(Languages::getAlpha2Code($alpha3Code));

}
```

i got this error :

> Couldn't read the indices [Alpha3ToAlpha2][ace] for the locale "meta" in "C:\XXX\vendor\symfony\intl/Resources/data/languages".

also when I tested with an existing alpha3code `Languages::getAlpha2Code("ace")` i got the same error

### How to reproduce

```php
use Symfony\Component\Intl\Languages;
\Locale::setDefault('en');
       
$languages = Languages::getAlpha3Codes();

foreach ($languages as $alpha3Code) {
    dump(Languages::getAlpha2Code($alpha3Code));
}
```

**Comment by ro0NL** [comment]
use `getLanguageCodes`, there's no alpha2 mapping for `ace`: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

**Comment by Forticas** [comment]
> use `getLanguageCodes`, there's no alpha2 mapping for `ace`: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

@ro0NL thank you very much, I didn't know it
