### ISSUE TITLE
[RFC][Validator] Phone number validation

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#46234]
### Description

The docs about the form field TelType ()https://symfony.com/doc/current/reference/forms/types/tel.html say: 
"Following the recommended HTML5 behavior, the value of this type is not validated in any way, because formats for telephone numbers vary too much depending on each country." 

Imho [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) offers great functionality in validating phone numbers. I installed it in many a project now and made use of this in custom validators. Would be fine to have this available symfony's validators - maybe comparable to the strict email validation using [egulias/email-validator](https://packagist.org/packages/egulias/email-validator)

### Example

`#[Assert\Tel(options: ["defaultRegion" => "FR",  "onlyMobile" => true, "onlyEURoaming" => true])]`

**Comment by stof** [comment]
There is already a bundle integrating [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) with the Symfony validator. See at the end of their readme where they list framework integrations.

**Comment by Shoplifter** [comment]
@stof Oh - sorry, I should have read that before. Thank you. As far as I am concerned, this can be closed, unless @derrabus considers this as a feature that should be part of symfony/validator and symfony/form directly.

**Comment by derrabus** [comment]
Let's close. I don't think we need to duplicate the work that library has done already.
