### ISSUE TITLE
[Windows Command Line] Simfony/Process::prepareWindowsCommandLine() method doesn't properly replace double quotes with triple quotes

### ISSUE THREAD

**Issue by MarcelloDM** [symfony/symfony#46231]
### Symfony version(s) affected

5.4.8

### Description

Hi to everyone, 

I noticed that the Simfony/Process::prepareWindowsCommandLine() does not perperly work in case of presence of double quotes in command line: they are incorrectly replace or indifferently replaced by empty string to avoid  to fail.

In fact, Windows command line expects three double quotes (""") if command contains double quotes, it does not work otherwise.
i.e. The command as follows fails:

`copy "C:\user\file.txt" "C:\user\folder1\file.txt"` --> `copy C:\user\file.txt C:\user\folder1\file.txt` 

Did anyone have observed that yet? 

### How to reproduce

Call the function run() or mustRun() command using double quotes.  

### Possible Solution

Changing properly the prepareWindowsCommandLine() method on its inner 

` function ($m) use (&$env, &$varCache, &$varCount, $uid)`

**Comment by nicolas-grekas** [comment]
Please provide a reproducer or better: a failing test case.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
