### ISSUE TITLE
[Profiler] The string to escape is not a valid UTF-8 string.

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#46250]
### Symfony version(s) affected

6.0.8

### Description

It seems like sometimes the RateLimiter in combination with Redis (snc redis bundle) causes the Profiler (the Performance tab to be more specific) to crash since it seems to try and display the serialized version of the `SlidingWindow` which contains non UTF-8 Values.

I'm not exactly sure what's responsible for this, the profiler or SNC Redis but I thought I'd bring it up here first.

### How to reproduce

The problem is it doesn't seem to happen consistantly cause sometimes that page works and sometimes it does not.
It might be connected to the `SlidingWindow` sometimes being present and sometimes not?

### Additional Context

![Screenshot 2022-05-04 at 15 31 41](https://user-images.githubusercontent.com/24696606/166691874-ee8fa8f0-187c-40a9-9b45-c515d1c2b7af.png)
![Screenshot 2022-05-04 at 15 30 48](https://user-images.githubusercontent.com/24696606/166691899-4a7cc03e-0535-4143-83d7-e5b05d1ac778.png)

**Comment by KDederichs** [comment]
Also here's a reproducer:

https://github.com/KDederichs/profiler_reproducer

Just start the Symfony server, go to localhost:8000/ and spam refresh the site (you need to refresh it like 120 times or something, that sliding window counts up something that turns into non UTF-8 eventually)

(This assumes you have phpredis installed)

**Comment by nicolas-grekas** [comment]
The code that emits the buggy section name should be fixed instead.
