### ISSUE TITLE
[HttpClient] memory leak

### ISSUE THREAD

**Issue by Gounlaf** [symfony/symfony#46256]
### Symfony version(s) affected

6.0.8

### Description

Hi,

I'm hunting a memory leak since few days and finally found where it might be.
Context: I've a loop that do some work. Some metrics are collected, and pushed via a http request to a prometheus pushgateway.

When the Psr18Client is handling the response body, the leak happens.

### How to reproduce

Here you can find a MRE: https://github.com/Gounlaf/sf-http-client-memory-leak

It rely on docker & docker-compose; `up` the service debug and then check your processes. You will find that memory of php process is increasing with `$psr18Client = new Psr18Client(new \Symfony\Component\HttpClient\NativeHttpClient());`
or `$psr18Client = new Psr18Client(new \Symfony\Component\HttpClient\CurlHttpClient());`
It doesn't with another (not symfony) implementation `$psr18Client = new \Http\Client\Curl\Client($psr17factory, $psr17factory);`

If this MRE is not enough, please let me know.

Regards.

**Comment by manueldimmler** [comment]
I was able to trace the memory leak to the following line:
https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpClient/Response/StreamWrapper.php#L72

To me it looks like it's a problem with fopen in conjunction with a stream wrapper. The memory usage does not increase continuously, but jumps sometimes to a high value and then falls back again. The distances between the jumps are getting bigger each time:

**Comment by manueldimmler** [comment]
[memory_usage.txt](https://github.com/symfony/symfony/files/8681074/memory_usage.txt)

**Comment by manueldimmler** [comment]
It doesn't look like an error in the HttpClient to me, but in the PHP source code. So I opened a ticket there.

**Comment by nicolas-grekas** [comment]
This should be fixed by https://github.com/symfony/symfony/pull/47143
