### ISSUE TITLE
symfony/mercure-notifier dependency lock

### ISSUE THREAD

**Issue by jorge-ruukfy** [symfony/symfony#46270]
### Symfony version(s) affected

5.4.x

### Description

Cannot install symfony/mercure-notifier  on Symfony 5.4.x with mercure-bundle 0.6.1

```
 Problem 1
    - Root composer.json requires symfony/mercure-notifier 5.4.* -> satisfiable by symfony/mercure-notifier[v5.4.0, v5.4.2, v5.4.3].
    - symfony/mercure-notifier[v5.4.0, ..., v5.4.3] require symfony/mercure ^0.5.2 -> found symfony/mercure[v0.5.2, v0.5.3] but the package is fixed to v0.6.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

### How to reproduce

Install symfony version 5.4

composer.json
...
"symfony/notifier": "5.4.*",
"symfony/mercure-bundle": "^0.3.4",
...

then
`composer require symfony/mercure-notifier`

### Additional Context

https://github.com/symfony/mercure-bundle/blob/v0.3.4/composer.json

https://github.com/symfony/mercure/releases

Version 0.5.3 of Mercure is missing mercure() twig function stated in the docs (https://symfony.com/doc/5.4/mercure.html#subscribing)

**Comment by chalasr** [comment]
Thanks for the report. See #46273
