### ISSUE TITLE
Mailer: Embedding images using "cid:" stops working, when files get attached

### ISSUE THREAD

**Issue by a-r-m-i-n** [symfony/symfony#46298]
### Symfony version(s) affected

6.0.8

### Description

I try to send mails with an embedded logo and an attached PDF file. The embedded image is missing in sent mail, when also attaching files.

### How to reproduce

When I use `$mail->embed()` and e.g. `cid:logo` the image is being displayed:
![image](https://user-images.githubusercontent.com/1275298/167473376-f9bc8bbd-7016-4401-a9f9-9ecc46cd578d.png)

Now, when I also call `->attach()` the desired file is being displayed, but the inline image, has been dropped:
![image](https://user-images.githubusercontent.com/1275298/167473505-8765ae21-8dc0-4ad5-8a51-4490bba12d7a.png)

Instead of the image, the HTML part only shows the placeholder icon (tested in mailhog & outlook). Using fromFile (for embed or attach) does not make a different. Also different order (attach first, them embed) does not make a difference.

### Additional Context

PHP 8.1.3

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by a-r-m-i-n** [comment]
Sure.

```php
<?php
namespace App\Controller;

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    #[Route(path: '/mailer/attach-embed', name: 'mailer_demo_attach_embed')]
    public function mailerDemoAttachAndEmbed(Kernel $kernel, MailerInterface $mailer)
    {
        $email = (new Email())
            ->from(new Address('example@domain.com', 'Example sender'))
            ->to('recipient@domain.com')
            ->subject('Attach and embed does not work')
            ->html('Working image expected: <br><img src="cid:logo" />')
        ;

        $email->attach('Example text file, as attachment', 'attachment.txt');
        $email->embedFromPath($kernel->getProjectDir() . '/public/assets/logo.svg', 'logo');

        $mailer->send($email);

        return new Response('Demo mail sent');
    }
}
```
You need to make sure, that the logo image file is actually existing. 

In Mailhog you will get this result:
![inline image with attachment](https://user-images.githubusercontent.com/1275298/167613464-45aac3e0-5d86-4038-a017-f8d7946d7cd0.png)

When comment the line starting with ``$email->attach`` out, it works but the attachment is missing:
![inline image without attachment](https://user-images.githubusercontent.com/1275298/167613576-10dfe4a0-ef53-401f-b3a5-04130b988737.png)

**Comment by a-r-m-i-n** [comment]
Oh okay. I've redirected the mail where the inline image worked in Mailhog. In Outlook and Gmail, an attached image appears like that:
![image](https://user-images.githubusercontent.com/1275298/167616317-e0aa6df9-ff47-4c8a-b43c-9ca1967b4aba.png)

😞

**Comment by a-r-m-i-n** [comment]
I realized, that SVG images does not work properly in many mail clients. But with PNG image the issue also still occure, when you attach a file.

**Comment by a-r-m-i-n** [comment]
Ehm. Okay, after replacing SVG with PNG it still does not work in Mailhog... but in any other Mail client I've tested now (Gmail, Outlook). So this issue, seems to be a mailhog issue only. Sorry for bothering.

Gmail:
![image](https://user-images.githubusercontent.com/1275298/167617723-2e42aa64-bfb4-401f-9092-da4cbe4b1810.png)

Outlook:
![image](https://user-images.githubusercontent.com/1275298/167617772-eb836406-e37f-4037-852a-5e565287d971.png)
