### ISSUE TITLE
Make `Mime\BodyRenderer` markdown conversion configurable

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#46295]
### Description

Symfony can already automatically generate a text version of an e-mail in `\Symfony\Bridge\Twig\Mime\BodyRenderer` using [league/html-to-markdown](https://github.com/thephpleague/html-to-markdown) (see https://symfony.com/doc/current/mailer.html#text-content)

But there is no way to configure the conversion options (e.g. we would like to remove the `img` tags as well). The instantiation is hardcoded in the constructor and the `BodyRenderer` itself is marked as final:
https://github.com/symfony/symfony/blob/1ac98fc9c619a1202e38018e7c578869ad7174d0/src/Symfony/Bridge/Twig/Mime/BodyRenderer.php#L23-L37
(The only way I see as an extension option is to copy the `BodyRenderer` to `MyBodyRenderer`, modify it and try to keep up with the changes in Symfony)

I suggest that the `League\HTMLToMarkdown\HtmlConverter` is wrapped behind some `HtmlToTextConverter` interface, so it would be possible to either replace it with other convertor or at least configure it differently.

**Comment by fabpot** [comment]
See #47201

**Comment by mhujer** [comment]
@fabpot awesome, thanks! 🌞
