### ISSUE TITLE
Not possible to decorate Router

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#46319]
### Symfony version(s) affected

6.0.* (deprecation in 5.4.*)

### Description

Before a URL is generated from a route and it's parameters, in my application I need to modify those name and parameters in some cases. Until Symfony 5.4 it was possible to decorate the Router and in such way do some evaluations before running the original `generate()` method.
From a certain point in time, deprecation warnings where generated, telling that injecting 'ContainerInterface' in 'router.inner' would be impossible starting Symfony 6.0. I thought, since it was the inner service, it would be fixed as soon as I was able to upgrade to Symfony 6. However, now I've started testing it, this is not the case. The error is `The service "App\Router\Router.inner" has a dependency on a non-existent service "Psr\Container\ContainerInterface".`.

I've done some research, but was not succesfull in finding a way to 'extend' the `generate()` method, neither by decorating the UrlGeneratorInterface, nor by decorating the Router. I have found some references telling that extending the Router is the way to go. Altogether, my conclusion is that the inability to decorate the Router is a bug.

### How to reproduce

Checkout https://github.com/tjveldhuizen/symfony-router-decorator-reproduction, composer install, symfony serve and load the page.

**Comment by mhujer** [comment]
@tjveldhuizen Hi! I'm using a decorated router in our app without any issues and I can see two difference with your reproducer:

```php
final class FancyUrlRouter implements RouterInterface, WarmableInterface
{

    private Router $router;

    public function __construct(
        Router $router // <----- the type hint here
    )
    {
        $this->router = $router;
    }

```

In services.yaml:
```yaml
    App\Infra\FancyUrl\FancyUrlRouter:
        decorates: 'router'  # <---- the 'router' here
```

**Comment by derrabus** [comment]
So tl;dr: Decorating `router.default` fails, but decorating `router` works?

**Comment by mhujer** [comment]
Yes. If I change it in my app from `router` to `router.default` I get a similar exception as @tjveldhuizen

**Comment by tjveldhuizen** [comment]
I can confirm that this works, thanks for the suggestion!
