### ISSUE TITLE
Max_duration is not respected when retry_count > 1 (http-client)

### ISSUE THREAD

**Issue by r-martins** [symfony/symfony#46316]
### Symfony version(s) affected

5.4.8

### Description

Let's say you have an API endpoint that always fails on the first request, and succeed on the second attempt.
Every request takes 30 seconds to be returned by the API.

If you make a Retryable HttpRequest, you can define `timeout` and `max_duration` to 40 seconds.
But it will not be respected, because when doing the second attempt, symfony still waits up to 40 seconds to get a response.

So you can expect this part of code to take 60 seconds to respond with no issues, instead of having a timeout error.

### How to reproduce

1. Create the following `sleep.php` file:
```php
<?php
sleep(30);
$count = (int)@file_get_contents('.count') == 0 ? 1 : (int)@file_get_contents('.count');
if ($count >= 2) {
    unlink('.count');
    echo '2nd attempt. SUCCESS!';
    exit;
}
$count++;
http_response_code(502);
echo 'Failed. ' . $count-1 . ' attempt;';
file_put_contents('.count', (string)$count);
```
2. Run `php -S localhost:8888` in the folder of the file above
3. Create a Command to test it:
```php
<?php
#src/TestCommand.php
namespace App;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class TestCommand extends \Symfony\Component\Console\Command\Command
{
    protected static $defaultName = 'app:test';
    
    public function __construct(protected HttpClientInterface $httpClient, string $name = null)
    {
        parent::__construct($name);
    }
    
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->writeln('Start: ' . date('H:i:s'));
        $start = time();
        $url = 'http://localhost:8888/sleep.php';
        $client = $this->httpClient;
        $response = $client->request('GET', $url, [
            'timeout' => 40,
            'max_duration' => 40
        ]);


        try {
            $output->writeln($response->getStatusCode().': '.$response->getContent(false));
        } catch (ClientExceptionInterface $e) {
            $output->writeln(get_class($e) . ': ' . $e->getMessage());
        } catch (RedirectionExceptionInterface $e) {
            $output->writeln(get_class($e) . ': ' . $e->getMessage());
        } catch (ServerExceptionInterface $e) {
            $output->writeln(get_class($e) . ': ' . $e->getMessage());
        } catch (TransportExceptionInterface $e) {
            $output->writeln(get_class($e) . ': ' . $e->getMessage());
        }
        $output->writeln('Retry coint: ' . (int)$response->getInfo('retry_count'));
        $output->writeln('End: ' . date('H:i:s'));
        $output->writeln('Total time: ' . time()-$start . 's');
        return 1;
    }
}
```

4. Run the test comand with `bin/console app:test` and note that it will succeed on the second attempt after 60 seconds.

### Possible Solution

We may need to work on AmpHttpClient or RetryableHttpClient to use the time left on the other requests.

I posted a half solution [here](https://stackoverflow.com/questions/72194696/symfony-retryable-httpclient-and-timeout-option-how-it-works-when-used-together/72197256#72197256) that may be useful to get the total time of the request, including the waiting time between the attempts.

But it's far from the ideal solution.

### Additional Context

In my case, I have a controller that makes http requests to another endpoint.
The users that call this controller, expect it to return a response in 45 seconds. However, after implementing the RetryableHttpClient, I'm having cases where the request is processed by the other endpoint in the second or third attempt, but my users get a timeout exception.

It happens because the first request to the other endpoint takes less than 45 seconds, but both calls take more than that.

**Comment by nicolas-grekas** [comment]
I'm not sure the behavior you describe is the expected one. To me, it's not obvious that a group of retries should respect a single max duration. Max duration is defined as applicable to one request and it's never been defined to a series of request.

I think you'd better achieve what you want by implementing the control of the duration on your side, in loop like:
```php
foreach ($client->stream($response, $idleTimeout) as $chunk) {
    // measure total duration here and exit when you want
}
```

**Comment by r-martins** [comment]
Thanks for your precious time in responding to me @nicolas-grekas.
As per the [documentation](https://symfony.com/doc/current/http_client.html), I understood that `max_duration` is supposed to limit the whole request/response including it's retries.

Quoting...
> Timeouts control how long one is willing to wait while the HTTP transaction is idle. Big responses can last as long as needed to complete, provided they remain active during the transfer and never pause for longer than specified.
>
> Use the `max_duration` option to limit the time a full request/response can last.

But I never worked with the stream method.. I will definitively give it a try tomorrow and update the topic here.
I loved the new RetryableHttpClient, but it was very unexpected to see some requests taking more than 60 seconds even when the timeout and max_duration were specified with a lower value.

Maybe I didn't understood the docs properly. 
But thanks one more time for responding. ;)

**Comment by jderusse** [comment]
> /cc @jderusse any opinion on this? We could patch RetryableHttpClient so that is reduces the max_duration of retries by the duration of the failed requests.

Technically, that means the `RetryableHttpClient` should know the original `maxDuration`.
That's doable if the option is part of the request, but not if it's part of the client's default options.
That could be fixed by either:
- expose an internal `getDefaultOptions` method in clients => but won't work with 3rd party decorated client
- add a new `start_time` option that could be take into account by the client to compute the duration `$duration -= microtome(true) - $option['start_time']`

**Comment by nicolas-grekas** [comment]
For the start time, it exists already: `$response->getInfo('start_time')`
We could provide the option back via eg `$response->getInfo('max_duration')`
Then make RetryableHttpClient use that info when it exists.

**Comment by r-martins** [comment]
> I'm not sure the behavior you describe is the expected one. To me, it's not obvious that a group of retries should respect a single max duration. Max duration is defined as applicable to one request and it's never been defined to a series of request.
> 
> I think you'd better achieve what you want by implementing the control of the duration on your side, in loop like:
> 
> ```
> foreach ($client->stream($response, $idleTimeout) as $chunk) {
>     // measure total duration here and exit when you want
> }
> ```

Hi @nicolas-grekas. I played the last 2 hours with the `stream` method... It's very nice in many aspects.
It in fact can help me with cancelling the request if a timeout happens.
But if I want to retry a timed-out request, I can't. Or at least, I could not figure out a way of doing that in any other way, unless I call the request method again with the remaining time.

I did something like this..

```
        $idleTimeout = 3;
        $maxDuration = 7;
        foreach ($client->stream($response, $idleTimeout) as $response => $chunk) {
            $elapsed = time() - $startTime;
            try {
                $content = $chunk->getContent();
            } catch (TransportExceptionInterface $e) {
                $output->writeln('error: ' . $e->getMessage());
                if ($chunk->isTimeout() && $elapsed < $maxDuration) {
                    $response->cancel();
                    continue;
                }
                break;
            }
...
```

My test case scenario is:

- [ ] 1st attempt get timeout / 2nd attempt succeeds
- [ ] 1st attempt get error / 2nd attempt time out / 3rd attempt succeeds

Because this is a "place order" request and involves credit card capture, I may need to send a $response->cancel() if one of the attempts times out in order to avoid duplicated orders/charges.

Is there a way to retry the request within the foreach you mentioned?
I'm still wondering if the new RetryableHttpClient would be enough, if the `max_duration` worked...

Thank you one more time.

**Comment by nicolas-grekas** [comment]
See #46382
