### ISSUE TITLE
CheckPassportEvent is not an event, it is a command.

### ISSUE THREAD

**Issue by SoftwareMensch** [symfony/symfony#46318]
### Description

Today we figured out, that `Symfony\Component\Security\Http\Event\CheckPassportEvent` is used as event, but it is obviously a command. Events should only describe what happened in past, not what has to be in the future.

I suggest to have a look at the common **Command Pattern**. A quick overview is available [here](https://en.wikipedia.org/wiki/Command_pattern). Commands must be like events async dispatchable/executable. However, to keep the implementation simple, it is not necessary to implement the dispatching logic in that way. It is just important that a command handler is not allowed to return something.

### Example

An example in PHP is [here](https://sourcemaking.com/design_patterns/command/php) available.

**Comment by derrabus** [comment]
Thank you for enlightening us on this topic. Can you elaborate how this issue affects you and what you'd like to change in Symfony?

**Comment by ro0NL** [comment]
> but it is obviously a command

except it's really an event to check passports :) `PassportCheckEvent` conveys the same IMHO

**Comment by SoftwareMensch** [comment]
> > but it is obviously a command
> 
> except it's really an event to check passports :) `PassportCheckEvent` conveys the same IMHO

An events can't check anything, a possible event could be that is was checked, e.g. `PassportWasCheckedEvent` or `PassportCheckedEvent`.

That is the simple differents between commands and events.

**Comment by ro0NL** [comment]
i think you are confusing sf/event-dispatcher vs sf/messenger being different patterns.

switching the pattern is not a goal on itself IMHO

**Comment by SoftwareMensch** [comment]
> i think you are confusing sf/event-dispatcher vs sf/messenger being different patterns.
> 
> switching the pattern is not a goal on itself IMHO

I don't think so, I just said that `PassportCheckEvent` is not a name for an event, it's a name for a command. It's all about naming. Saying that `PassportCheckEvent` is an event, is mixing up pattern and confuses less experienced developers. I see such things every day. It's simply not a good design.

**Comment by SoftwareMensch** [comment]
> Thank you for enlightening us on this topic. Can you elaborate how this issue affects you and what you'd like to change in Symfony?

Such issues affect our less experienced developers and confuses them, to distingish what are events and what not. I would like that Symfony uses a better separation of the naming of things. `PassportCheckEvent` does not say that something happened, but this is what events should do. Here it says "do something", which is in this case "check the passort" and that is a command and not an event.

**Comment by ro0NL** [comment]
so, how would you name the event when users 'check passports'?

**Comment by wouterj** [comment]
Theory aside, what is the practical limitations of the event and how do you envision the command?

At the current state, this issue seems purely theoritical. For an issue to be actionable, it should be clear what should be changed and - more importantly - what issues it fixes (in order to judge if the costs of change are worth it).

**Comment by SoftwareMensch** [comment]
> so, how would you name the event when users 'check passports'?

Well, it's not an event agein :). A simple name would be `CheckPassportCommand`.

**Comment by ro0NL** [comment]
from the current implemenation POV it's an event, dispatched by sf/event-dispatcher. It's valid design.

**Comment by SoftwareMensch** [comment]
> Theory aside, what is the practical limitations of the event and how do you envision the command?
> 
> At the current state, this issue seems purely theoritical. For an issue to be actionable, it should be clear what should be changed and - more importantly - what issues it fixes (in order to judge if the costs of change are worth it).

You are right, I expected the a Symfony dev is able to figure out, how to implement it. Sorry that this was not clear. A good design would be to implement a `CommandBus`similar to the `EventDispatcher`. With a method named `execute`. For example

```
public function execute(CommandInterface $command)
{
     // command bus should know which handler is required for which command
     $commandHandler = [COMMAND HANDLER INSTANCE]
     
     // return value has to be ignored
     $commandHandler($command); // invoke for better type safety
}
```

It is similar to an event dispatcher, but the business use case is another. However, a command can only only have one handler, not like events which can have multiple subscriber or listener.

**Comment by SoftwareMensch** [comment]
> from the current implemenation POV it's an event, dispatched by sf/event-dispatcher. It's valid design.

Does it notify your system that something happened? If not, it's not an event, it's simple misused as one.

**Comment by wouterj** [comment]
I'm still missing the "what problem does this solve?" answer :)

> However, a command can only only have one handler, not like events which can have multiple subscriber or listener.

This is a major blocker btw. The whole idea of CheckPasswordEvent is to have a "hook" that allows to plug in custom checks.

**Comment by derrabus** [comment]
Sorry, but I'm closing this issue as non-actionable now. Symfony does not have that kind of command bus that you're suggesting and I don't see us implementing one. Symfony does not make a difference between what you call and event and what you call a command. That might not be a textbook-perfect architecture, but it's one that works pretty well for us.

**Comment by SoftwareMensch** [comment]
> I'm still missing the "what problem does this solve?" answer :)
The problem what is solved is a better software design :)

> > However, a command can only only have one handler, not like events which can have multiple subscriber or listener.
> This is a major blocker btw. The whole idea of CheckPasswordEvent is to have a "hook" that allows to plug in custom checks.

Well, that is a problem, sure. But you already already said, it can't be an event, it's a hook. I understand that this is a big blocker and if I've seen such implementation in a lot of system. But it is simply wrong software design. If you wanna have a hook, call it hook, not event.

**Comment by ro0NL** [comment]
> event, noun, "a thing that happens or takes place"

**Comment by SoftwareMensch** [comment]
> Sorry, but I'm closing this issue as non-actionable now. Symfony does not have that kind of command bus that you're suggesting and I don't see us implementing one. Symfony does not make a difference between what you call and event and what you call a command. That might not be a textbook-perfect architecture, but it's one that works pretty well for us.

I understand, but it's not what I call a command and an event, it comes from more experienced devs like Martin Fowler.

I didn't expect that Symfony is changing it's core, because of this issue. I just wanted to draw attention to it, for future implementations.

**Comment by SoftwareMensch** [comment]
> > event, noun, "a thing that happens or takes place"

Well, that's true, but in software architecture it can be confusing and leads to missusing of concepts. Symfony seems to use it more "traditional" with simple distinguishing between events and messages, but than Symfony should be so strict to distingish also between event notification and events which also can takes place.

· Tradiditional architecture is explained [here](https://www.redhat.com/en/topics/integration/what-is-event-driven-architecture)
· A more modern architecture (it is also more than 20 years old), is explained [here](https://medium.com/ingeniouslysimple/command-vs-event-in-domain-driven-design-be6c45be52a9) in short.

However, the topic is closed. Whish you all a nice week! :)
