### ISSUE TITLE
"failed to find an authenticator supported by SMTP server" Supported are gssapi ntlm

### ISSUE THREAD

**Issue by michalwoz** [symfony/symfony#46337]
### Symfony version(s) affected

6.0.5

### Description

We've switched from Swiftmailer to Symfony/mailer and lost support for NTLM authentication. Swiftmailer supported NTLM. Is it possible to use NTLM or GSSAPI with Symfony/mailer?

### How to reproduce

I cannot authenticate with server which supports NTLM and GSSAPI only.

**Comment by fabpot** [comment]
Would you like to port the code from Swiftmailer to Symfony Mailer?

**Comment by fabpot** [comment]
You == anyone willing to work on this issue :)

**Comment by fabpot** [comment]
I'm going to close this issue. Of course, anyone can still submit a PR for add support.

**Comment by Smoggert** [comment]
I wrote a port for this authenticator.
https://gist.github.com/Smoggert/11feb64b9eae55e78d70e0ca93953077
You can provide it to your Transport during boot or you can work further on this to create a pull in symfony mailer.

**Comment by jawira** [comment]
Sadly PR https://github.com/symfony/symfony/pull/48267 was closed without merging.
An idea, Symfony's HttpClient already supports NTLM authentication, maybe that code can be reused in Mailer?
