### ISSUE TITLE
symfony/cache/Traits/FilesystemCommonTrait.php write function, the file being write "disappeared"

### ISSUE THREAD

**Issue by Nomia** [symfony/symfony#46332]
### Symfony version(s) affected

4.1

### Description

hello, I'm currently facing a situation that 

when I set cache in the linux console(`root` user) with the `write` function, the data will be saved to `/tmp/symfony-cache/W/8/xxxxxxxxxxx`, this file will always exist
and when I set the cache via the browser get request(`www-data` user), the data will be saved to `/tmp/symfony-cache/Y/G/xxxxxxxxxxxxx` and this file cannot be found under the `tmp` directory

I tried to log something, as shown in the img below. the `file_exists` log is true, but when I go to that `tmp` dir, the file is not there, and I double checked that the `expiresAt` is correct, means `expiresAt` > current time, 10 more minutes, you can see that in another screenshot(`log result`)

`log`
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1707818/168038242-d7a78c35-fb91-4486-b239-3d2ec97f0348.png">

`log result`
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1707818/168039521-583de35d-7bc6-4b4f-9d08-c50b7182ff18.png">

I don't know what is happening, can anybody help, thx
I wanna that two different user can share the same cache file, or at least tell me why the cache file will disappear, and where can i keep that or find it so I can read it with another linux user

I'm using Symfony in Laravel

### How to reproduce

execute the `write` function in the `symfony/cache/Traits/FilesystemCommonTrait.php` file with two different linux users. you'll find that the symfony cache data in different file for these two users, and one of the file will disappear wierdly

**Comment by Nomia** [comment]
I did some research, found that `different key` will be saved to the file with the `same name or path`. one confusion solved

but, here is another wired thing, 
I tried `file_get_contents` the file(`e.g /tmp/symfony-cache/Y/G/q8fHhHpXaCegVVyMlCf4`) inside the `write` function of the `symfony/cache/Traits/FilesystemCommonTrait.php` file, and I get `conent A`
`log screenshot`
<img width="556" alt="image" src="https://user-images.githubusercontent.com/1707818/168202745-ba47e13a-7516-4b5a-a875-bbfacc82489e.png">
`result screenshot`
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1707818/168202812-3a8547f4-0e25-4d98-92c2-bda939902e7f.png">

I tried `file_get_contents` in a very simple php file(`e.g <?php file_get_contents('/tmp/symfony-cache/Y/G/q8fHhHpXaCegVVyMlCf4'); ?>`) and I get `content B`
`log screenshot`
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1707818/168202965-d3fed932-b72e-452e-b5f4-31aa5a9db498.png">

`result screenshot`
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1707818/168203062-a56af8f1-9c85-452a-ad9a-eda0b52db019.png">

How could this happen?
`file_get_contents` a same file within different context, I get different result?

**Comment by Nomia** [comment]
when I restart `php-fpm`, the `file_get_contents` in the `FilesystemCommonTrait.php` file throws an error, saying that the file tried to read is not exist
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1707818/168204285-6faa65e0-82d8-4d22-a9d8-0ccb57a5ed9e.png">

but actually the file is still there, I still can `file_get_contents` the same file in the `test.php`
<img width="563" alt="image" src="https://user-images.githubusercontent.com/1707818/168204335-124cf789-72a8-4b23-bcc4-8f0eb4ab0435.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1707818/168204371-a128c2b6-5438-4b2d-bf14-dccd0027841b.png">

the filename or path are the same(`/tmp/symfony-cache/Y/G/q8fHhHpXaCegVVyMlCf4`), as u can see from all the screenshots above

can anybody help me fix this?
or tell me what happened? why operation on the same file get different result?

is this a problem of `file_get_contents` or a problem of `symfony`?

**Comment by xabbuh** [comment]
Symfony 4.1 is not supported anymore. Can you provide a small example application that allows to reproduce your issue with one of the supported (4.4, 5.4, or 6.0) versions?

**Comment by Nomia** [comment]
the problem was caused by the `PrivateTmp` feature of `nginx.service`, if set to `true`, every process will have its own /tmp dir, so different process write/read different folder, so they cannot share data(e.g. request from the web browser and function call from console will not have a shared cache folder).
that's really a painful hidden setting

I tried to set custom `tmp` folder for my application with `putenv` function, problem solved
```php
putenv('TMPDIR='.__DIR__.'/../storage/app/custom_tmp');
```
