### ISSUE TITLE
Issue when calling dump() in WebTestCase

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#46342]
### Symfony version(s) affected

4.4 or >

### Description

To fix the following issue https://github.com/symfony/symfony/issues/33312, ``DebugBundle`` is not enabled anymore in ``test`` env. A PR have been merged to change the Flex receipe here: https://github.com/symfony/recipes/pull/940

But as described here https://github.com/symfony/symfony/issues/33312#issuecomment-1118526609, calling ``dump()`` now result in ``call to undefined function``.

### How to reproduce

If I call dump('TEST');, it doesn't works.

![image](https://user-images.githubusercontent.com/652505/166925780-fa11b5a2-4f5e-4749-b52b-57e4a850ca81.png)

If I call using VarDumper::dump('TEST');, it works.

![image](https://user-images.githubusercontent.com/652505/166926183-b8efb93a-6167-4b07-b07e-4d87dc96dbcd.png)

### Possible Solution

The dump function is loaded via DebugBundle -> VarDumper -> require

To trigger the registration of dump() and dd() global functions, when we don't load the DebugBundle (in test env) I explicitly create a VarDumper object. Not sure it's the best way to fix the issue but it works fine.

As a possible solution, we can trigger the VarDumper() to register the ``dump()`` global function:
```php
if (in_array($this->getEnvironment(), array('dev', 'test'))) {
    $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
    //$bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
}
if ($this->getEnvironment() === 'test') {
    new Symfony\Component\VarDumper\VarDumper();
}
```

Seems a bit uggly as VarDumper is not a bundle and the Kernel should only register bundles. It's also possible to use a specific bootstrap for tests but not the best option as simple solution. Maybe the best would be to keep the Debug bundle but check if the dump have to be stored in the profiler or flushed in CLI.

**Comment by stof** [comment]
Are you using the `symfony/symfony` mono-repo or individual packages ?
When using individual packages, the `dump` function should always exist as soon as `symfony/var-dumper` is installed in your package (as it registers the file defining it to be loaded by the composer autoloader)

**Comment by raziel057** [comment]
I use individual packages but not flex and I kept my AppKernel.

While testing using Symfony 6 & PHP 8.1 I don't have any issue by just disabling the ``DebugBundle``.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
