### ISSUE TITLE
Error encoutered in Process when a custom array value is registered in $_ENV superglobal

### ISSUE THREAD

**Issue by websealevel** [symfony/symfony#46348]
### Symfony version(s) affected

6.0.8

### Description

The `symfony/process` `Process` entity (`Process.php`, ligne `293`) encounters an unexpected error when a custom array value is registered in super global `$_ENV.` This custom array value is parsed and an error is generated.

### How to reproduce

Register an array in `$_ENV` , for example

`$_ENV['foo'] = array('bar');`

Then when the method `start()` of `Process.php` (ligne `293`) iterates over the local variable `$env` in the `for loop` an error occurs.

### Additional Context

I've encountered this bug while using the [PHP-FFMpeg/PHP-FFMpeg](https://github.com/PHP-FFMpeg/) package.

**Comment by nicolas-grekas** [comment]
I suppose [PHP-FFMpeg](https://github.com/PHP-FFMpeg/) should be fixed instead. This array is not supposed to contain arrays.

**Comment by websealevel** [comment]
Ok, thank your for your reply. I was wondering if it was considered as a bad practice to register an array value in `$_ENV`. It's the first time I submit issues on official repositories, I originally published this issue on the PHP-FFMpeg repo but then I noticed the bug lies in the symfony dependency so I wasn't sure where to submit the issue.
