### ISSUE TITLE
[Console] Lazy commands with symfony/proxy-manager-bridge error

### ISSUE THREAD

**Issue by mrsuh** [symfony/symfony#46350]
### Symfony version(s) affected

6.0.8

### Description

Hi!
I know that the correct way to make a command lazy is:
```php
    protected static $defaultName        = 'app:test';
    protected static $defaultDescription = 'description';
```
but if we want to use `lazy` attribute with command in service.yaml
```yaml
    App\Command\:
        resource: '../src/Command'
        lazy: true
```
there will be the an error:
```bash
php bin/console app:test
TypeError {#96
  #message: "ContainerLegSm4V\TestCommand_d286c1a::setName(): Return value must be of type ContainerLegSm4V\TestCommand_d286c1a, App\Command\TestCommand returned"
  #code: 0
  #file: "./var/cache/dev/ContainerLegSm4V/TestCommand_d286c1a.php"
  #line: 143
  trace: {
    ./var/cache/dev/ContainerLegSm4V/TestCommand_d286c1a.php:143 {
      ContainerLegSm4V\TestCommand_d286c1a->setName(string $name): static
      › 
      ›     return $this->valueHolder1624a->setName($name);
      › }
    }
    ./vendor/symfony/console/Command/LazyCommand.php:184 { …}
    ./vendor/symfony/console/Application.php:295 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:80 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:29 { …}
    ./bin/console:11 { …}
  }
}
2022-05-14T10:41:08+00:00 [critical] Uncaught Error: ContainerLegSm4V\TestCommand_d286c1a::setName(): Return value must be of type ContainerLegSm4V\TestCommand_d286c1a, App\Command\TestCommand returned
```

The error started appearing after this [commit](https://github.com/symfony/console/commit/a1ee9d3cdcb41e70f7dc83b4e43fa5af0106de3f) which added `: static` return type to `setName()` function in [Symfony\Component\Console\Command\Command.php](https://github.com/symfony/console/blob/042e4104bdbff41e03f46d6c00c4b6ce255ab85b/Command/Command.php#L464)
```php
public function setName(string $name): static
```

### How to reproduce

```bash
git clone git@github.com:mrsuh/issue-symfony-console.git && cd issue-symfony-console

composer install

php bin/console app:test
```

### Possible Solution

I think 
* it's wrong to add `lazy` attribute to an already lazy command, but it's worked before and we need to fix it. Maybe we can replace `static` return type with `self`? 
* we need to add a note to [documentation](https://symfony.com/doc/current/service_container/lazy_services.html) not to use `static` return type in `lazy` services

**Comment by nicolas-grekas** [comment]
I'd rather see this as a bug in proxy-manager, not in console.

**Comment by chalasr** [comment]
> it's wrong to add lazy attribute to an already lazy command

Yes, it basically means proxying an already proxied object.

> but it's worked before and we need to fix it

I'm not sure actually. The docs could eventually mention the uselessness of using the lazy attribute for a console command.

**Comment by mrsuh** [comment]
@nicolas-grekas 
The error occurs in proxy object:
```
class TestCommand_d286c1a extends \App\Command\TestCommand implements \ProxyManager\Proxy\VirtualProxyInterface {
    
    public function setName(string $name) : static
    {
        $this->initializer6b55c && ($this->initializer6b55c->__invoke($valueHolder1624a, $this, 'setName', array('name' => $name), $this->initializer6b55c) || 1) && $this->valueHolder1624a = $valueHolder1624a;

        return $this->valueHolder1624a->setName($name); // <-- error
    }
}    
```
The proxy manager simply repeats the API of the original class.
I don't know how to fix this without breaking the original and proxy class API.
Made issue about it [here](https://github.com/Ocramius/ProxyManager/issues/760).

@chalasr I thought about it. Maybe we need to add a note to [lazy command documentation](https://symfony.com/doc/current/console/lazy_commands.html) and close this issue?

**Comment by nicolas-grekas** [comment]
Closing in favor of https://github.com/symfony/symfony/issues/35345, thank for reporting and digging the issue.
