### ISSUE TITLE
[Serializer] Snake Case entity properties are ignored  in ::ATTRIBUTES

### ISSUE THREAD

**Issue by Mausino** [symfony/symfony#46355]
### Symfony version(s) affected

6.0.8

### Description

Hello :) i am newby.. and i am not for 100% sure if this is issue or i missed some context from https://symfony.com/doc/current/components/serializer.html#selecting-specific-attributes

The issue is that if property in Entity call: name_first and i write it as attributes is ignored.. i must convert it to camel case. More in How to reproduce

Here are dump($getObjects); from my example code in How to reproduce section.

There are 3 types as my property names in Entities: normal (without any _ or capital letter), snake case properties (in my case for more words properties), camel case properties (in my case for naming of relationships)

![Snímka obrazovky z 2022-05-14 23-31-09](https://user-images.githubusercontent.com/5773777/168448739-63b9bc30-a55b-4c94-b7f9-94ffa8eb57e2.png)

### How to reproduce

In $json1 are used Entity property as i have "name_first" and this was ignored by serializer
In $json2 are used instead of "name_first" the camel case version "nameFirst" and it worked

I don't understand if my issue (i didn't understand something) or it is real issue.

```
$getObjects = $manager->getRepository(SystemContacts::class)->findAll();

$encoder = new JsonEncoder();
$defaultContext = [
        AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object, $format, $context) {
            return $object->getId();
        },
   ];
$normalizer = new ObjectNormalizer(null, null, null, null, null, null, $defaultContext);
$serializer = new Serializer([$normalizer], [$encoder]);

 $json1 = $serializer->serialize($getObjects, 'json', [AbstractNormalizer::ATTRIBUTES => ['id', 'name_first', 'SystemModuleAdresses']]);
dump($json1);
// $json1 = [{"id":2,"SystemModuleAddresses":null},{"id":5,"SystemModuleAddresses":null},{"id":6,"SystemModuleAdresses":null},{"id":3,"SystemModuleAdresses":null},{"id":4,"SystemModuleAdresses":null}]

$json2 = $serializer->serialize($getObjects, 'json', [AbstractNormalizer::ATTRIBUTES => ['id', 'nameFirst', 'SystemModuleAdresses']]);
dump($json2);
// json2 = [{"id":2,"nameFirst":null,"SystemModuleAdresses":null},{"id":5,"nameFirst":null,"SystemModuleAdresses":null},{"id":6,"nameFirst":null,"SystemModuleAdresses":null},{"id":3,"nameFirst":"Frau","SystemModuleAdresses":null},{"id":4,"nameFirst":"Miky","SystemModuleAdresses":null}]

```

### Additional Context

If found some other issue with ATTRIBUTES option in issue #45995 but i thing is different as my bug.

If i used  Symfony\Component\PropertyInfo\PropertyInfoExtractor for info about entity properties i got:
`dump($propertyInfo->getProperties(SystemContacts::class));`

![Snímka obrazovky z 2022-05-15 15-37-11](https://user-images.githubusercontent.com/5773777/168475729-ff42e3fe-6563-4ff4-8537-fcc74e703249.png)

but i think it should be possible to use snake case properties as was defined in Entity class in ::ATTRIBUTES

![Snímka obrazovky z 2022-05-15 15-38-59](https://user-images.githubusercontent.com/5773777/168475804-3010fb42-e7cc-4d94-a631-c98f9f2d781d.png)

**Comment by mtarld** [comment]
Hi! @Mausino!

I think that the issue isn't specifically related to the `ATTRIBUTES` option, but rather because the `PropertyAccessor` isn't able to retrieve the `name_first` value because it's snake-cased. (which is a known issue: https://github.com/symfony/symfony/issues/29933)

Can you confirm that even without the `ATTRIBUTES` context value it doesn't work with snake case properties in your case?

**Comment by Mausino** [comment]
Hi @mtarld  i can confirm that the snake case are ignored everywhere where i wanted use them... in ATTRIBUTES or PropertyAccess or PropertyInfo... 
...  that reason, why i  am changing all Entities to Camel Case that i will not necessary fight/think with/about it.

**Comment by mtarld** [comment]
Therefore, I think that we can close that issue.

Thanks, @Mausino :slightly_smiling_face:
