### ISSUE TITLE
Symfony\Component\HttpKernel\EventListener\ErrorListener first argument also can be null

### ISSUE THREAD

**Issue by eimkua1** [symfony/symfony#46375]
### Symfony version(s) affected

6.0.*

### Description

Backward compatibility was broken since commit - 574d651f55c3d7af445ebd2c6b336719dd6a9263
\Symfony\Component\HttpKernel\EventListener\ErrorListener::__construct - first argument can be null, just look at \Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException method

### How to reproduce

Pass null as first argument

### Possible Solution

Add possibility to pass null value as first constructor argument

**Comment by chalasr** [comment]
Thanks for the report. See #46377
