### ISSUE TITLE
MonologBridge does not support monolog 2.x

### ISSUE THREAD

**Issue by eerison** [symfony/symfony#46378]
### Symfony version(s) affected

4.4.37

### Description

I was looking the packages outdated and I saw that monolog is stuck in the version 1.x because of [monolog bridge](https://github.com/symfony/monolog-bridge/blob/4.4/composer.json#L20), is there any reason for this code be locked in version `1.25.1` or the code definitely doesn't support monolog 2.x?

### How to reproduce

run

```
composer depends monolog/monolog
```

and you will see that "monolog bridge" is blocking upgrade "monolog"

```
symfony/monolog-bridge  v4.4.37  requires  monolog/monolog (^1.25.1)                
symfony/monolog-bundle  v3.8.0   requires  monolog/monolog (^1.22 || ^2.0 || ^3.0) 
```

**Comment by stof** [comment]
Support for Monolog 2 was added in Symfony 5, because it implied BC breaks in case you were extending the handlers provided by the bridge.
