### ISSUE TITLE
[RFC][WebpackEncore]  Ability to define absolute url for `output_path` 

### ISSUE THREAD

**Issue by marphi** [symfony/symfony#46393]
### Description

To improve ci/cd I want to achieve the possibility to prepare a task building front assets independent from “backend build”.

My idea to improve ci/cd :
 * task to build backend: prepare symfony app, composer install, warmup cache, docker image etc. full working application without knowledge about `manifest.json` and `entrypoint.json` . Application will be configured with 
 ```
 framework.assets.base_urls: ['https://cdn.url/%build_hash%/']
 framework.assets.json_manifest_path: 'https://cdn.url/%build_hash%/manifest.json'
 webpack_encore.output_path: 'https://cdn.url/%build_hash%/'
 ```
 * **concurrent independent** frontend build with commands like: npm/yarn install, build with encore and copy results to cdn accessible via `https://cdn.url/%build_hash%/`

I found small blockers. Right now we can set up `framework.assets.json_manifest_path` as absolute url, which is nice and helps me with this, but this file is fetched every request which is not so good options. 
And I can not set up webpack_encore to fetch `entrypoint.json` from absolute url.

My RFC:
 - ability to define absolute url for `webpack_encore.output_path` and for multiple builds.
 - add cache to `Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy` to limit the number of requests for manifest.json file.

What do you think? I will prepare PR if this rfc be accepted.

**Comment by lyrixx** [comment]
Hello, I think I missed something here.

It looks like you have two application :  backend in SF, and a frontend. 

So I don't understand why the backend needs some information coming from the frontend? The frontend is in charge of building the HTML, and it's the one who deal with the manifest.json.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
