### ISSUE TITLE
Mailgun multi domain support

### ISSUE THREAD

**Issue by joelharkes** [symfony/symfony#46404]
### Description

currently sending mails via mailgun via different domains is not supported because the `domain` is hardcoded.

as a SaaS application we would like to send from different domains for our different brands.
I have a solution but sadly the property needed `domain` is private instead of `protected`.

### Example

code below could work as an adaption if not the `domain` property was private.

alternatively add this to the 
```php

class MailgunMultiDomainHttpTransport extends MailgunHttpTransport {
    protected function doSendHttp(SentMessage $message): ResponseInterface
    {
        $sender = $message->getEnvelope()->getSender();
        $fromEmail = $sender->getAddress();
        if ($fromEmail) {
            $this->domain = substr($fromEmail, strpos($fromEmail, '@') + 1);
        }
        return parent::doSendHttp($message);
    }
}

```

**Comment by fabpot** [comment]
Instead of changing the property to protected, I think we could have a flag in the DSN that would enable this behavior? Would that work?

**Comment by joelharkes** [comment]
We found this was our best solution for Laravel adding a listener:
```php
public function handle(MessageSending $event): void
    {
        if (!$this->isUsingMailgun()) {
            return;
        }

        $domain = $this->domainNameFrom(...$event->message->getFrom());
        if (empty($domain)) {
            return;
        }

        Mail::mailer(self::MAILER)->setSymfonyTransport(
            (new MailgunApiTransport(
                config('services.mailgun.secret'),
                $domain
            ))->setHost(config('services.mailgun.endpoint')),
        );
    }
```

**Comment by faizanakram99** [comment]
> Instead of changing the property to protected, I think we could have a flag in the DSN that would enable this behavior? Would that work?

Yes definitely it'll help, I've had a similar use cases and now we create Transport manually from the domain, where domain is guessed from the from or sender header. It's non intuitive as we can't benefit from symfony DI.
