### ISSUE TITLE
Get TypeError when composer install 

### ISSUE THREAD

**Issue by SilvaQ** [symfony/symfony#46402]
### Symfony version(s) affected

laravel 9.x

### Description

I am getting symlink fileSystem error when I developing laravel pacakge,
more info i am putting here:

https://github.com/composer/composer/issues/10786 

### How to reproduce

https://github.com/composer/composer/issues/10786

### Possible Solution

https://github.com/composer/composer/issues/10786

### Additional Context

https://github.com/composer/composer/issues/10786

error detail:

![image](https://user-images.githubusercontent.com/46706370/169264867-f6f90035-028c-40e3-9927-6dbe810ee465.png)

result: 
> it is happend because I dont know symlink is in the  disable function list.

**Comment by xabbuh** [comment]
Can you check if the `symlink()` function does exist on your PHP installation and/or is listed under the disabled functions?

**Comment by SilvaQ** [comment]
@xabbuh 

Ah, that's why Symlink is disabled, thank you

**Comment by xabbuh** [comment]
I am going to reopen as I think we should be able to improve the error around this.

**Comment by SilvaQ** [comment]
When I installed Laravel it warned me and stopped the installation if there was a function in disable function, which I didn't know was on the disable list. I thought I had to do some kind of detection procedure to avoid this, so I hope to give a friendly reminder that SymLink may be disabled, which is very good for me as a newcomer

**Comment by derrabus** [comment]
Quick and dirty, would #46407 help? Or did you have a more detailled error message in mind, @xabbuh?

**Comment by xabbuh** [comment]
@derrabus looks good to me
