### ISSUE TITLE
[ExpressionLanguage] New "contains" operator conflict with custom function 

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#46406]
### Symfony version(s) affected

6.1

### Description

As of [Symfony 6.1](https://symfony.com/blog/new-in-symfony-6-1-improved-expressionlanguage-syntax#new-operators), a new `contains` operator is available, which is great.

However, when a custom `contains` function was already added in userland, trying to use an expression like:

```php
contains(article.slug, "foo")
```

would produce an error:

> Symfony\Component\ExpressionLanguage\SyntaxError: Unexpected token "operator" of value "contains" around position 1 for expression `contains(article.slug, "foo")`.

### How to reproduce

Adding a custom function in an `ExpressionLanguageProvider`:

```php
ExpressionFunction::fromPhp('str_contains', 'contains')
```

### Possible Solution

Updating this line:

https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/ExpressionLanguage/Lexer.php#L72

to:

```diff
- } elseif (preg_match('/(?<=^|[\s(])starts with(?=[\s(])|(?<=^|[\s(])ends with(?=[\s(])|(?<=^|[\s(])contains(?=[\s(])|(?<=^|[\s(])matches(?=[\s(])|(?<=^|[\s(])not in(?=[\s(])|(?<=^|[\s(])not(?=[\s(])|(?<=^|[\s(])and(?=[\s(])|\=\=\=|\!\=\=|(?<=^|[\s(])or(?=[\s(])|\|\||&&|\=\=|\!\=|\>\=|\<\=|(?<=^|[\s(])in(?=[\s(])|\.\.|\*\*|\!|\||\^|&|\<|\>|\+|\-|~|\*|\/|%/A', $expression, $match, 0, $cursor)) {
+ } elseif (preg_match('/(?<=^|[\s(])starts with(?=[\s(])|(?<=^|[\s(])ends with(?=[\s(])|(?<=^|[\s(])contains(?=[\s])|(?<=^|[\s(])matches(?=[\s(])|(?<=^|[\s(])not in(?=[\s(])|(?<=^|[\s(])not(?=[\s(])|(?<=^|[\s(])and(?=[\s(])|\=\=\=|\!\=\=|(?<=^|[\s(])or(?=[\s(])|\|\||&&|\=\=|\!\=|\>\=|\<\=|(?<=^|[\s(])in(?=[\s(])|\.\.|\*\*|\!|\||\^|&|\<|\>|\+|\-|~|\*|\/|%/A', $expression, $match, 0, $cursor)) {
```

(in short:

```diff
- [\s(])contains(?=[\s(])
+ [\s(])contains(?=[\s])
```
)

would avoid the operator to conflict with a function. But, there was probably a reason I'm missing for allowing a `(` directly after when using the operator? Shouldn't we differentiate `contains(expr)` and `contains (expr)`?

### Additional Context

This is very specific, so perhaps we should just consider this as an acceptable BC break and won't fix.

**Comment by nicolas-grekas** [comment]
> This is very specific, so perhaps we should just consider this as an acceptable BC break and won't fix.

I confirm this :)
