### ISSUE TITLE
Fast Track book project can't be installed through `symfony new`, due to GitHub not allowing HTTPS clone anymore

### ISSUE THREAD

**Issue by titanioverde** [symfony/symfony#46431]
### Symfony version(s) affected

5.4.1

### Description

Greetings.

I was trying the Fast Track book for version 5.4, and couldn't continue from the project installation step.
https://symfony.com/doc/5.4/the-fast-track/en/2-project.html#getting-the-project-source-code

`symfony new` is trying to clone the repo through HTTPS. It seems GitHub doesn't allow this since last year, in favor of SSH.

### How to reproduce

Executing `symfony new --version=5.4.1 --book guestbook` in the terminal.

I couldn't tested other versions.

### Possible Solution

Change the command to use SSH instead of HTTPS, or include alternative ways in the book.

### Additional Context

Result screenshot: https://www.imgpaste.net/image/KvwF4z

**Comment by gizmola** [comment]
Did you try a personal access token?

**Comment by nicolas-grekas** [comment]
Works for me. Setting a token is the way to go. Composer needs one also.
Closing as this is unrelated to this repo.
Please submit to https://github.com/symfony-cli/symfony-cli if there is anything to fix (but please try setting a token first)

**Comment by titanioverde** [comment]
Ok, I'm sorry. I didn't know this "personal token" feature yet. I thought it was the same as the SSH key.
I'll try it soon.

**Comment by titanioverde** [comment]
I confirm that the command works perfectly fine if I generate a Personal Access Token on GitHub and use it as my password during the HTTPS authentication.

Also, I wrote a typo in the version number. It is `5.4-1`, not `5.4.1`.

Thank you for your attention.
