### ISSUE TITLE
Singleton Curl initializing for running PHP apps as a daemon 

### ISSUE THREAD

**Issue by mertingen** [symfony/symfony#46439]
### Description

I've got the following design. Symfony App is run in Swoole Worker. It means it's alive permanently and runs as a daemon.

Clients -> Symfony App with HTTP Client -> external services

When we got a request from clients, we send a POST HTTP request to the external services. These external services support "Connection: keep-alive" but Symfony HTTP Client creates Curl Handler for each request. Therefore I cannot refer to "keep-alive connection" because it creates a TCP Connection always but I'd like to use created one previously.

In the "CurlHTTPClient" file, this code is run for each request.

```
if (!$pushedResponse) {
    $ch = curl_init();
    $this->logger && $this->logger->info(sprintf('Request: "%s %s"', $method, $url));
    $curlopts += [\CURLOPT_SHARE => $this->multi->share];
}
```

Is there an option to keep this curl handler for the next requests from clients in Symfony HTTP Client?

**Comment by nicolas-grekas** [comment]
This is already the case if you reuse the same instance of HttpClient and if you  *do not* call its `reset()` method  between requests. By default, this method is called. It might be possible to prevent it from being called by removing the `kernel.reset` tag on the corresponding service definition - or by definiting your own http_client service btw. Please confirm what you manage to do.

**Comment by mertingen** [comment]
Thanks for the quick reply @nicolas-grekas ,

I've got the following Symfony service.

```
class HttpService
{

    public function __construct(private HttpClientInterface $client)
    {
    }

    public function executeRequest(string $method, string $url, array $options = []): WalletHttpResponse
    {
            $response = $this->client->request($method, $url, $options);
    }
}
```

If I request multiple times for one client request, as you said it's re-using the same curl handler. But, when I got the second request from the client, it creates a new curl handler. It means when I got the 100 requests from clients, my Symfony app creates 100 curl handlers. 

Clients -> Symfony App with HTTP Client -> external services

For instance, I solved this situation by Curl like the following. Thus "curl_init" initializes for once.

```
class HttpService
{
    private $curlHandler;

public function __construct(HttpClientInterface $client)
    {
        if (empty($this->curlHandler)) {
            $this->curlHandler = curl_init();
        }
    }

public function executeRequestByCurl(string $method, string $url, array $options = [])
    {
        curl_setopt($this->curlHandler, CURLOPT_URL, $url);
        $response = curl_exec($this->curlHandler);
    }
}
```

**Comment by nicolas-grekas** [comment]
Creating new curl handlers doesn't mean connections aren't reused. The way to know if connections are reused is by calling getInfo('debug') once when responses are processed. What does it say if you do that?

**Comment by mertingen** [comment]
**I always see this output for the new requests. (I replaced domains and IP information with ///)**
**When my app got a new request from the client and if my app sends multiple requests, it's reusing and does not create a new connection. But, when the client sent the next request, my app creates a new connection to external services. It doesn't use the current curl handler.**

Trying ///...
Connected to /// port 80 (#0)
POST ** HTTP/1.1
Host:///
Connection: Keep-Alive
Accept: */*
User-Agent: Symfony HttpClient/Curl
Accept-Encoding: gzip
Content-Length: 244
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 244 out of 244 bytes
Mark bundle as not supporting multiuse
HTTP/1.1 200 OK
Date: Sun, 22 May 2022 20:59:59 GMT
Server: Apache/2.2.15 (Red Hat)
X-Powered-By: Servlet 2.5; JBoss-5.0/JBossWeb-2.1
Content-Length: 32
Cache-Control: max-age=0
Expires: Sun, 22 May 2022 20:59:59 GMT
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: text/plain;charset=ISO-8859-1

**Let's point here: "Keep-Alive: timeout=15, max=100" This max value is reduced for the same client request but it's being 100 after a new request. Check out not initializing "curl_init" for each request and the "max" value is decreased as expected**

Found bundle for host ///: 0x5607b85661c0 [serially]
Re-using existing connection! (# 42) with host ///
Connected to  /// port 80 (# 42)
POST /// HTTP/1.1
Host: ///
Accept: */*
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 250

upload completely sent off: 250 out of 250 bytes
Mark bundle as not supporting multiuse
HTTP/1.1 200 OK
Date: Mon, 23 May 2022 19:58:56 GMT
Server: Apache/2.2.15 (Red Hat)
X-Powered-By: Servlet 2.5; JBoss-5.0/JBossWeb-2.1
Content-Length: 30
Cache-Control: max-age=0
Expires: Mon, 23 May 2022 19:58:56 GMT
Keep-Alive: timeout=15, max=89
Connection: Keep-Alive
Content-Type: text/plain;charset=ISO-8859-1

**Comment by nicolas-grekas** [comment]
Can you provide us with a reproducer, eg a docker container that I could hit with a simple local script?

**Comment by mertingen** [comment]
Hi @nicolas-grekas ,

I'm unable to manage Docker image but I think Symfony initializes "HttpClientInterface" for each request again. It's not shared and it might be my configuration, I'm not sure. I've got this essential service.

Let's say the client sends 1 request and my app needs 3 requests to another external app. These 3 requests are used same TCP connection by HTTP Client. But. if the same client sends another request, my Symfony app initializes a new TCP connection, it doesn't use the previous one and I think initializing HttpClientInterface causes this.

```
<?php

namespace App\Service;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Throwable;

class HttpService
{
    private $client;

    public function __construct(HttpClientInterface $client)
    {
        $this->client = $client->withOptions([
            'verify_host' => false,
            'verify_peer' => false,
        ]);
    }

    /**
     * @param string $method
     * @param string $url
     * @param array $options
     * @return array
     */
    public function executeExternalRequest(string $method, string $url, array $options = []): array
    {
        try {
            $response = $this->client->request($method, $url, $options);

            return [
                'status' => true,
                'data' => $response->toArray(),
                'message' => '',
            ];
        } catch (Exception $e) {
            return [
                'status' => false,
                'data' => [],
                'message' => $e->getMessage(),
            ];
        }
    }
}
```

**Comment by nicolas-grekas** [comment]
> Let's say the client sends 1 request and my app needs 3 requests to another external app. These 3 requests are used same TCP connection by HTTP Client. But. if the same client sends another request, my Symfony app initializes a new TCP connection, it doesn't use the previous one and I think initializing HttpClientInterface causes this.

I'm sorry but I don't understand this sentence, especially this: "These 3 requests are used same TCP connection by HTTP Client. But. if the same client sends another request"

If the same connection is used for 3 requests, why doesn't it work for the 4th?

**Comment by mertingen** [comment]
Let me clarify. The structure is like the following;

Client -> 1 HTTP request -> My App -> 3 HTTP requests -> External App

The client sent 1 request and My App sent 3 requests to External App for that client's 1 request. In this way, these 3 requests are used for the same TCP connection. Everything is ok until this time.

But if the client sends a new request, that HttpClient initializes again for the Symfony Runtime. It shouldn't be created again because URL and PORT are the same. And, My App is working as a daemon so it's built and always it's live. 

How could I solve this situation? I modified that HttpService like the following. I initialize curl at once and it doesn't initialize for the new client requests. When the keep-alive is closed, it'll be created because there is no TCP connection to use.

```
<?php

namespace App\Service;

use Throwable;

class HttpService
{
    private $curlHandler;

    public function __construct()
    {
        if (empty($this->curlHandler)) {
            $this->curlHandler = curl_init();
        }
    }

    /**
     * @param string $method
     * @param string $url
     * @param array $options
     * @return array
     */
    public function executeExternalRequest(string $method, string $url, array $options = []): array
    {
        try {
            // curl is used for the external app requests
        } catch (Exception $e) {
            return [
                'status' => false,
                'data' => [],
                'message' => $e->getMessage(),
            ];
        }
    }
}
```

**Comment by nicolas-grekas** [comment]
> My App is working as a daemon so it's built and always it's live.

OK, that's the part that breaks. HttpClient is reusing connections, but the code that runs it as a daemon must reset/recreate the instance between requests. That's were what you should look for to understand the behavior your see.

Nothing to change in HttpClient itself IMHO. I'm closing therefore.
