### ISSUE TITLE
[symfony/messenger 5.4.8] Attempted to call an undefined method named "pgsqlGetNotify" of class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection

### ISSUE THREAD

**Issue by FractalizeR** [symfony/symfony#46436]
### Symfony version(s) affected

5.4

### Expected Result
It works, consuming messages...

### Actual Result
In PostgreSqlConnection.php line 82:
                                                                                                                                                             
```
Attempted to call an undefined method named "pgsqlGetNotify" of class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection".  
```

Original report is here: https://github.com/getsentry/sentry-symfony/issues/626

### How to reproduce

Run Symfony Messenger with the bin/console messenger:consume command to consume messages from PostgreSQL.

### Possible Solution

Downgrade symfony/doctrine-messenger to version 5.4.7.
The error seems to be related to https://github.com/symfony/doctrine-messenger/commit/7e03e21dfe36fa58d646f181d34dd889c8e5f38f

### Additional Context

```
doctrine/dbal 2.13.8
sentry/sentry-symfony 4.2.9
symfony/messenger 5.4.8
symfony/doctrine-messenger 5.4.8
```

**Comment by derrabus** [comment]
If you can, please consider upgrading to DBAL 3.3 or later. Fixing this kind of issue on DBAL 2 is a real PITA.

In `PostgreSqlConnection`, can you please locate this block:

```php
$wrappedConnection = $this->driverConnection->getWrappedConnection();
if (!$wrappedConnection instanceof \PDO && $wrappedConnection instanceof DoctrinePdoConnection) {
    $wrappedConnection = $wrappedConnection->getWrappedConnection();
}
```

Can you please change it into this:

```php
$wrappedConnection = $this->driverConnection;
while (\method_exists($wrappedConnection, 'getWrappedConnection')) {
    $wrappedConnection = $wrappedConnection->getWrappedConnection();
}
```

Does this solve your problem?

**Comment by Hadrien45** [comment]
Hi @derrabus,

The problem is solved with your change.  

Since my original issue in sentry repository, I had also upgrade the dependencies of my project to 
```txt
doctrine/dbal 2.13.9
sentry/sentry-symfony 4.3.0
```
and it works.

**Comment by xabbuh** [comment]
see #46610
