### ISSUE TITLE
Private method registered with AsEventListener attribute does not throw an exception

### ISSUE THREAD

**Issue by ju1ius** [symfony/symfony#46455]
### Symfony version(s) affected

6.0.8

### Description

When an event listener is registered using the `AsEventListener` attribute _on a method_ and the method visibility is not public, the DIC compilation does not fail and the method is never called.

When registered _on a class_, the DIC compilation does not fail, but the method is called and fails (obvioulsy).

### How to reproduce

Given the following service:
```php
namespace App;

use Symfony\Component\EventDispatcher\Attribute\AsEventListener;

final class MyListener
{
    #[AsEventListener('kernel.request')]
    private function test(): void
    {
    }
}
```

The expected behaviour would be either:
1. An exception thrown at runtime (to match the behaviour when the attribute is registered on the class):
  ```
  Error: Call to private method App\MyListener::test() from scope Symfony\Component\EventDispatcher\Debug\WrappedListener
  ```
 2. An exception during the container compilation process

### Additional Context

Note that this behaviour is reproducible for any attribute registered for autoconfiguration.

**Comment by derrabus** [comment]
In order to "fix" this, we would need to scan all methods for attributes, not just the public ones. Not sure, we want that.

**Comment by ju1ius** [comment]
> In order to "fix" this, we would beed to scan all methods for attributes, not just the public ones.

I see, that would be overkill indeed.
Feel free to close if this is something that can't be addressed, then.

Thanks.

**Comment by ghost** [comment]
This could be handled by static analysis, e.g. in [phpstan/phpstan-symfony](https://github.com/phpstan/phpstan-symfony).

**Comment by wouterj** [comment]
Yes, I would favor such a rule in e.g. static analyzers. Imho, it's not worth the costs of checking all private/protected methods when compiling the container to improve an error message.

In the future, if we find that adding an attribute to a non-public method is a common source for support questions, we might revisit the ideas in this issue. So thank you for bringing it up :)
