### ISSUE TITLE
Laravel Application breaks when upgrading Symphony to 6.1

### ISSUE THREAD

**Issue by siddiquiazam** [symfony/symfony#46479]
### Symfony version(s) affected

6.1

### Description

I recently updated my Laravel application. I ran composer update which updated the symfony version to 6.1. As I am using php 8.0.x version on my forge development server, I started getting  compatibility errors as the latest symfony version require php 8.1.

### How to reproduce

Create a new Laravel Application and set it up on Laravel Forge with php 8.0.

### Possible Solution

I think changing the php version in a MINOR version change of a package is not correct as it introduces breaking changes.

### Additional Context

`composer.lock | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - symfony/css-selector is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/css-selector v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 2
    - symfony/deprecation-contracts is locked to version v3.1.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 3
    - symfony/event-dispatcher is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/event-dispatcher v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 4
    - symfony/event-dispatcher-contracts is locked to version v3.1.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 5
    - symfony/filesystem is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/filesystem v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 6
    - symfony/http-client is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/http-client v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 7
    - symfony/http-client-contracts is locked to version v3.1.0 and an update of this package was not requested.
    - symfony/http-client-contracts v3.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 8
    - symfony/options-resolver is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/options-resolver v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 9
    - symfony/string is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/string v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 10
    - symfony/translation is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/translation v6.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 11
    - symfony/translation-contracts is locked to version v3.1.0 and an update of this package was not requested.
    - symfony/translation-contracts v3.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
  Problem 12
    - symfony/deprecation-contracts v3.1.0 requires php >=8.1 -> your php version (8.0.17) does not satisfy that requirement.
    - fakerphp/faker v1.19.0 requires symfony/deprecation-contracts ^2.2 || ^3.0 -> satisfiable by symfony/deprecation-contracts[v3.1.0].
    - fakerphp/faker is locked to version v1.19.0 and an update of this package was not requested.`

**Comment by chalasr** [comment]
You have to restrict Symfony packages installations to the 6.0 version as we won’t reconsider this change. See https://symfony.com/blog/symfony-6-1-will-require-php-8-1. Thanks for your understanding.

**Comment by stof** [comment]
The solution is to run composer on PHP 8.0 or to use the `platform` config to override the PHP version used by composer when solving dependencies if your local environment does not use your target PHP version.

**Comment by stof** [comment]
Changing the min PHP version in a minor release is fine in the composer ecosystem, precisely because composer takes the platform requirements into account when solving dependencies. But this indeed relies on you using composer in a way that tell it about the correct platform version if you have special needs.

**Comment by siddiquiazam** [comment]
Thank you for the solutions.
