### ISSUE TITLE
symfony/event-dispatcher 6.1.0 and php-cs-fixer

### ISSUE THREAD

**Issue by andreisusanu** [symfony/symfony#46473]
### Symfony version(s) affected

6.1.0

### Description

Parse error: syntax error, unexpected token ")" in vendor/symfony/event-dispatcher/EventDispatcher.php on line 270

### How to reproduce

php:8.0-cli-alpine `vendor/bin/php-cs-fixer fix`

**Comment by xabbuh** [comment]
Symfony 6.1 requires PHP 8.1 (see #45377).
