### ISSUE TITLE
[HttpKernel] [6.1] Bundle path is parent directory instead of bundle directory when using new `AbstractBundle`

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#46482]
### Symfony version(s) affected

6.1.0

### Description

When using the new `AbstractBundle` introduced in Symfony 6.1, the path of the bundle is that of the parent directory which doesn't make any sense to me.

### How to reproduce

* Create `src/Shared/Infrastructure/GraphQL` directory
* Create `GraphQLBundle.php` file in that directory that implements `AbstractBundle`
* Try to import routes using `@GraphQLBundle/Controller/` and see that it fails

This is because the bundle is registered like this in the Kernel:
```
  "GraphQLBundle" => Shared\Infrastructure\GraphQL\GraphQLBundle^ {#142
    #name: "GraphQLBundle"
    #extension: Symfony\Component\HttpKernel\Bundle\BundleExtension^ {#6812
      -processedConfigs: []
      -subject: Shared\Infrastructure\GraphQL\GraphQLBundle^ {#142}
      -alias: "graphql"
    }
    #path: "/Volumes/CS/www/website/src/Shared/Infrastructure"
    -namespace: "Shared\Infrastructure\GraphQL"
    #container: null
    #extensionAlias: "graphql"
  }
```

As you can see, the `path` property of the bundle is the parent directory `src/Shared/Infrastructure`

### Possible Solution

I think the solution merged in https://github.com/symfony/symfony/pull/46385 needs thought.

For now, I need to manually override the `path` property to fix this. But shouldn't the bundle's path always be the location that specifies the bundle file? 

### Additional Context

https://github.com/symfony/symfony/pull/43701
https://github.com/symfony/symfony/pull/46385

**Comment by wouterj** [comment]
The `AbstractBundle` follows the directory structure that was introduced in Symfony 5 and is recommended for all bundles (when they don't need to be compatible with Symfony <5 anymore). As a result, it was decided that the `AbstractBundle` follows this new convention and you need to override the method if you want the old convention (as opposed to the `Bundle` class, where you need to override the method if you want the new convention).

You can find more about this in the bundle documentation: https://symfony.com/doc/current/bundles.html#bundle-directory-structure

Btw, it looks like the application you are working on is still using application bundles. In that case, I would recommend just sticking to the old convention. There are no plans to deprecate it in the near future.

**Comment by yceruto** [comment]
As explained by @wouterj this is the expected result when AbstractBundle is used, so it assumes you'll use the new directory structure. Otherwise, you have to update the bundle path location. Closing as there is no issue here. Thanks for your understanding!

**Comment by ruudk** [comment]
I understand that bundles are no longer needed, but very often, for large applications, they are perfect way to organize code and keep responsibilities together. 

Isn't this [new bundle structure](https://symfony.com/doc/current/bundles.html#bundle-directory-structure) only for vendored bundles? 

That would mean that everybody that is using bundles in their application (in src) is now going to get hit by this problem that is not very clear. 

Can't Symfony detect that a given bundle is loaded from `vendor` directory and then apply the new directory structure?

**Comment by wouterj** [comment]
You can also organize the src in different "domains" without using bundles. The Symfony recommendation is to not use bundles to organize application code and to use the new structures for bundles. So to me, it makes sense that the default is the new structure and you'll have to override one method to opt-in to the old structure. If you think the docs can be clearer on this, I'm happy to review your suggestion :)

Btw, you don't have to use the new `AbstractBundle`, the `Bundle` class is not deprecated.
