### ISSUE TITLE
[Bundle System] Broken service tagging in new AbstractBundle::loadExtension()

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#46488]
### Symfony version(s) affected

6.1.0

### Description

In `AbstractBundle::loadExtension()`, calling `$builder->registerForAutoconfiguration(MyInterface::class)->addTag('my_tag')` does not work because the classes that implement `MyInterface` are not executed.

When calling `$container->registerForAutoconfiguration(MyInterface::class)->addTag('my_tag')` in `Symfony\Component\HttpKernel\DependencyInjection\Extension::load()`, the classes that implement `MyInterface` are executed.

This might be related to the other [issue](https://github.com/symfony/symfony/issues/46486) that I opened, because in my PHPUnit testing I'm now running into issues with getting services from the test container when using `AbstractBundle`, and I did not have those issues previously.

At the surface it appears as if bundle service registration is handled differently between the old `Extension` approach and the new `AbstractBundle` approach.

### How to reproduce

See Description above.

**Comment by wouterj** [comment]
Fyi, I've edited both issue titles. This is not a BC break, as you explicitly opt in to use the new feature (by extending a different class).

**Comment by gnito-org** [comment]
Ok, but one certainly does not expect things to break just because you opt in to a new directory structure. There's no documentation on what else must be changed, and nothing was deprecated.

**Comment by gnito-org** [comment]
Here is an example of the testing issues.

```php
class MyTest extends KernelTestCase
{
    public function testSomething(): void {
        self::bootKernel();
        static::getContainer()->get(MyService::class);
    }
}
```

With the old `Extension` approach the code works. With the new `AbstractBundle` approach, Symfony complains about `MyService` having been removed and not being public.

**Comment by yceruto** [comment]
This seems to be related to the other issue https://github.com/symfony/symfony/issues/46486 that you created. Please check my comment to confirm this issue.
