### ISSUE TITLE
TestContainer should not be `@internal`

### ISSUE THREAD

**Issue by ddeboer** [symfony/symfony#46483]
### Symfony version(s) affected

6.1.0

### Description

#44695 added `@return TestContainer` to `KernelTestCase::getContainer()`. However, `TestContainer` is marked `@internal`, which makes any calls `static::getContainer()->get(MyService::class)` invalid, for example to Psalm (and possibly also to IDEs):

```
ERROR: InternalMethod - MyTest.php:16:49 - The method Symfony\Bundle\FrameworkBundle\Test\TestContainer::get is internal to Symfony but called from MyTest (see https://psalm.dev/175)
        $this->client = static::getContainer()->get(MyService::class);
```

### How to reproduce

```php
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class MyTest extends KernelTestCase
{
    public function test_container_get(): void
    {
        static::getContainer()->get(MyService::class);
    }
}
```

### Possible Solution

Remove `@internal` from `TestContainer`.

**Comment by wouterj** [comment]
For reference, this was also discussed shortly on Symfony Slack yesterday:

> [tarlepp](https://app.slack.com/team/U3RGAJ0JH)  [2:39 PM](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653655185515999)
> hmm, after update to Symfony 6.1.0 I'm seeing quite lot errors like:
> 
> ```psalm: InternalMethod: The method Symfony\Bundle\FrameworkBundle\Test\TestContainer::get is internal to Symfony but called from ...```
> 
> that TestContainer is marked as @internal any ideas how to fix this?
>
> [wouterj](https://app.slack.com/team/U39FQ276C)  [2:55 PM](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653656126972349)
> I feel like @internal is a mistake there, it should be @final at most
> [2:55](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653656140531609)
> But it has been there since 4 years, interesting that this comes up now
>
> [stof](https://app.slack.com/team/U3MGMS1HN)  [2:57 PM](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653656268628449)
> maybe it has been added in a return type somewhere in 6.1
> [2:58](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653656299108479)
> btw, maybe having it as internal is actually the good thing, but the return type should be the ContainerInterface rather than the internal implementation
>
> [tarlepp](https://app.slack.com/team/U3RGAJ0JH)  [3:01 PM](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1653656483134249)
> yep, that getContainer method has
> 
> ```@return TestContainer```
> 
> annotation if that is removed there aren't those errors anymore

**Comment by xabbuh** [comment]
Can you confirm that the change I propose in #46496 works as well for you?

**Comment by ddeboer** [comment]
@xabbuh Confirmed!
