### ISSUE TITLE
Dump issue

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#46490]
### Symfony version(s) affected

6.1

### Description

Hello,

I have been facing some issue using `dump();`, it returns unclosed entries.. 
`FileService.php on line 164:
array:13 [
  0 => array:7 [`

### How to reproduce

Not sure how to share or make reproducable steps. 
I used `dump(debug_backtrace());` in a service class I designed and the returned string is as it.

**Comment by meiyasan** [comment]
Perhaps I should also mention that in that case I terminate the execution using
`exit(1);`

**Comment by wouterj** [comment]
This sounds more like a display issue to me. Assuming we're talking about the HTML dumper here, can you check the page's source code in the browser to see if the full dump is in there? If so, can you check using the dev tools whether somehow the CSS of the page breaks the dump styles?

**Comment by meiyasan** [comment]
Sorry about that, I changed browser (I was using Safari 15.4) and the problem is not showing anymore.
I don't know the reason why.. but I will surely post again if this reproduce again

**Comment by wouterj** [comment]
No worries. I'm happy the issue seems resolved :)
