### ISSUE TITLE
[HttpKernel] [6.1] AbstractBundle: Document how to load routes

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#46501]
### Description

I'd like to add routes to my Symfony 6.1 bundle, and am following the instructions at https://symfony.com/doc/current/routing.html

```php
// config/routes.php at bundle root
use Acme\FooBundle\Controller\BlogController;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return function (RoutingConfigurator $routes) {
    $routes->add('blog_list', '/blog')
        ->controller([BlogController::class, 'list'])
    ;
};
```

I was following @yceruto 's example at https://github.com/symfony/symfony/issues/46492#issuecomment-1140477877 to load the routing configuration, but that's not working:
```php
class AcmeFooBundle extends AbstractBundle
{
    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/services.xml'); // works
        $container->import('../config/routes.php'); 
  // ERROR Could not resolve argument "Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator $routes"
    }
    public function configure(DefinitionConfigurator $definition): void
    {
        $definition->import(__DIR__ . '/../config/routes.php');// or without __DIR__, 
       // ERROR: Unhandled match case '...'
     }

}
```

Where and how are routes set in the bundle config?

**Comment by wouterj** [comment]
A bundle cannot (directly) configure/load routes. This is a deliberate choice, as the order of routes is important during the matching process, so this must be defined explicitly in the application.

The `configure()` method introduced in the `AbstractBundle` is there to configure the service container (e.g. add services, parameters, autoconfigures, etc.).

The common approach is to define a routing configuration file in the bundle (like you show here), and instruct the user to [import this one in their application's routing configuration file](https://symfony.com/doc/current/routing/custom_route_loader.html#built-in-route-loaders). You can also use a Flex recipe to do this automatically during installation.
