### ISSUE TITLE
[Form] Bool Form Type Fields inconsistent format true vs 1, false vs nothing

### ISSUE THREAD

**Issue by Mausino** [symfony/symfony#46512]
### Symfony version(s) affected

6.1

### Description

Hi, this is only my point of view.. and also i am newbie, that i am missing something, please close my ticket.

1. Whole point of this  small "bug" that form return true/false and Request 1/nothing of bool Form Types Fields

In class ContactFormType  in public function if i create $builder by FormBuilderInterface class

->add('termAgreement', CheckboxType::class) which is bool return type 

in controller if i do

$contactForm = $this->createForm(ContactFormType::class);
$contactForm->handleRequest($request);

if( $contactForm->isSubmitted() && $contactForm->isValid() )
{
dump($request);
![Snímka obrazovky z 2022-05-30 21-18-55](https://user-images.githubusercontent.com/5773777/171049989-fb1f93ec-895f-426c-a9db-3c15f44785aa.png)

dump($contactForm->getData());
![Snímka obrazovky z 2022-05-30 21-20-50](https://user-images.githubusercontent.com/5773777/171050075-08956546-a1d7-4659-b6f3-4c3d62a30e59.png)

}

2. Why Request doesn't return in array of form 0 or false, but return that this bool field is not there if validation is false. Other fields if not meet the validation are in Request form array but bool Form Type Fields not.
![Snímka obrazovky z 2022-05-30 21-30-46](https://user-images.githubusercontent.com/5773777/171050954-1fd3b550-faef-45d3-b880-da0f72478f45.png)

You can see that see that  termAgreement is true vs 1. I understand that 1 is "true" in computer language but only asking why this inconsistent and why if form is not valid other fields are in Request form array but bool fields not.

Sorry if i miss something and annoyed you by this.

### How to reproduce

....

**Comment by xabbuh** [comment]
I am not sure if correctly understood what you are asking for. So if my comment does not completely answer your question, your nay have to go a bit deeper. :) The fact that you do not see true or false when dumping the request is that this class is built around HTTP requests which do not have the concept of boolean values. This is where the Form component steps in which has form types that know how the final model data should look like and deal with model and view transformers to convert the request data into other data types. In this case transforming a string into a boolean value. Similar things happen in date types for example where string or array input from the request can be transformed into e.g. `DateTime` objects.

**Comment by Mausino** [comment]
@xabbuh thank you for clarification HTTP request.. and your time :)

Should i ask why is not this 'termAgreement' in Request if is also 'mapped' => true in FormBuilderInterface if form is not valid ? Others fields which are not boolen type are still there if form is not valid.  (datetime type i doesn't tried yet)

**Comment by xabbuh** [comment]
Does „not valid“ in this case mean that the corresponding checkbox was not ticked by the user?

**Comment by Mausino** [comment]
@xabbuh yes, it means that stay empty and not ticked by the user.

**Comment by derrabus** [comment]
If the user does not tick the checkbox, the browser won't include it in the request payload. This is the protocol and we can't do anything about it. When processing the request, the form component will correctly parse that payload and give you the booloan values you want. Bridging the gap between the raw (and sometimes obscure) protocol and well-defined data structures is essentially what the form component does.

I'm closing this issue because there is no bug to be fixed.

**Comment by Mausino** [comment]
@derrabus thank you for answer, now i am little bit smarter about this. Sorry if i spam by this issue which was not the issue.
