### ISSUE TITLE
[Serializer] TraceableNormalizer - SerializerDataCollector does not fallback gracefully if expected properties to be collected are missing

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#46522]
### Symfony version(s) affected

6.1.0

### Description

The `lateCollect` method looks to have been introduced. I'm not sure why, but currently some of the data is not collected. Perhaps the issue could be there, or perhaps we can fallback gracefully if some data is missing.

### How to reproduce

I am using API Platform and it is in a Behat test where some invalid data has been submitted where a property submitted is not the correct variable type (a null value instead of a boolean).

So the serialization is probably started and then a validation process is triggered which stops the process. Therefore some data is not collected in the new TraceableNormalizer.

While I can raise an issue there - I'm first checking whether for BC breaking purposes, it should be addressed at this level.

API Platform will throw `Symfony\Component\ErrorHandler\Exception\FlattenException` from `Serializer/AbstractItemNormalizer` line 554 : https://github.com/api-platform/core/blob/main/src/Serializer/AbstractItemNormalizer.php#L554

### Possible Solution

These changes to allow fallbacks would resolve the issue for me.

```php
    /**
     * {@inheritDoc}
     */
    public function lateCollect(): void
    {
        $this->data = [
            'serialize' => [],
            'deserialize' => [],
            'normalize' => [],
            'denormalize' => [],
            'encode' => [],
            'decode' => [],
        ];

        foreach ($this->collected as $collected) {
            $collectedData = $collected['data'] ?? null;
            $data = [
                'data' => $this->cloneVar($collectedData),
                'dataType' => get_debug_type($collectedData),
                'type' => $collected['type'] ?? null,
                'format' => $collected['format'] ?? null,
                'time' => $collected['time'] ?? null,
                'context' => $this->cloneVar($collected['context'] ?? null),
                'normalization' => [],
                'encoding' => [],
            ];

            if (isset($collected['normalization'])) {
                $mainNormalization = array_pop($collected['normalization']);

                $data['normalizer'] = ['time' => $mainNormalization['time']] + $this->getMethodLocation($mainNormalization['normalizer'], $mainNormalization['method']);

                foreach ($collected['normalization'] as $normalization) {
                    if (!isset($data['normalization'][$normalization['normalizer']])) {
                        $data['normalization'][$normalization['normalizer']] = ['time' => 0, 'calls' => 0] + $this->getMethodLocation($normalization['normalizer'], $normalization['method']);
                    }

                    ++$data['normalization'][$normalization['normalizer']]['calls'];
                    $data['normalization'][$normalization['normalizer']]['time'] += $normalization['time'];
                }
            }

            if (isset($collected['encoding'])) {
                $mainEncoding = array_pop($collected['encoding']);

                $data['encoder'] = ['time' => $mainEncoding['time']] + $this->getMethodLocation($mainEncoding['encoder'], $mainEncoding['method']);

                foreach ($collected['encoding'] as $encoding) {
                    if (!isset($data['encoding'][$encoding['encoder']])) {
                        $data['encoding'][$encoding['encoder']] = ['time' => 0, 'calls' => 0] + $this->getMethodLocation($encoding['encoder'], $encoding['method']);
                    }

                    ++$data['encoding'][$encoding['encoder']]['calls'];
                    $data['encoding'][$encoding['encoder']]['time'] += $encoding['time'];
                }
            }

            $this->data[$collected['method'] ?? 'unknown'][] = $data;
        }
    }
```

**Comment by chalasr** [comment]
Thanks for the report. /cc @mtarld

**Comment by mtarld** [comment]
Hi @silverbackdan, thanks for the report!

It is weird to me that we can have a partially collected trace.
Here the trace is created because a nested normalizer have been triggered (therefore the trace began to be filled)
But IMHO, if that fails, the trace must not stay (and shouldn't be shown in the profiler panel)

Instead, I would have ignored that trace in the late collect:
```php
foreach ($this->collected as $collected) {
  if (!isset($collected['data'])) {
    continue;
  }

  // ...
}
```

WDYT?

**Comment by silverbackdan** [comment]
Yes I think that would make sense, there's not really any useful information in the data that was collected - the useful part is the exception being thrown in this case :)

**Comment by silverbackdan** [comment]
You guys acted super fast on this, thanks.
