### ISSUE TITLE
Redirect URLs not starting with '/' get dropped

### ISSUE THREAD

**Issue by martinmaehlmannchefkoch** [symfony/symfony#46533]
### Symfony version(s) affected

4.4.42

### Description

By fixing bug #46317 a new bug was introduced. If a _target_path starts with 'http' or 'https' it gets dropped and the default location is returned. Using the Referer should still work.

### How to reproduce

In a login form allowing _target_path, modify the value to send a value which starts with http or https.

### Possible Solution

Simply modify the check to see, if it is a valid URL. Something like this could work:

``` php
if (\is_string($targetUrl) && (str_starts_with($targetUrl, '/') || filter_var($url, FILTER_VALIDATE_URL) )) {
    return $targetUrl;
}
```

**Comment by xabbuh** [comment]
Would you like to give this a try and send a PR fixing this?

**Comment by nicolas-grekas** [comment]
Given [the check in `HttpUtils::generateUri()`](https://github.com/symfony/symfony/blob/051f5a43cb0cd9110cf2939440454b873327f626/src/Symfony/Component/Security/Http/HttpUtils.php#L152), I would go with a simple `str_starts_with($targetUrl, '/') || str_starts_with($targetUrl, 'http')`, in both `DefaultAuthenticationFailureHandler` and `DefaultAuthenticationSuccessHandler`.

PR welcome indeed.
