### ISSUE TITLE
FormValidator in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by rvadym** [symfony/symfony#46536]
### Symfony version(s) affected

v5.3.11+

### Description

Until version `v5.3.10` Constructor of `Constraint` class didn't contain the line 
`unset($this->groups);`

https://github.com/symfony/symfony/blob/v5.3.10/src/Symfony/Component/Validator/Constraint.php#L106-L117

Starting from version `v5.3.11` that line appeared

https://github.com/symfony/symfony/blob/v5.3.11/src/Symfony/Component/Validator/Constraint.php#L113

```php
    public function __construct($options = null, array $groups = null, $payload = null)
    {
        unset($this->groups); // enable lazy initialization

        $options = $this->normalizeOptions($options);
        if (null !== $groups) {
            $options['groups'] = $groups;
        }
        $options['payload'] = $payload ?? $options['payload'] ?? null;

        foreach ($options as $name => $value) {
            $this->$name = $value;
        }
    }
```

However the property `Constraint::$groups` is not expected to contain a `null`, it should contain `string[]` instead. 

```php
    /**
     * The groups that the constraint belongs to.
     *
     * @var string[]
     */
    public $groups;
```

The "magic" setter from the same class also suggest that `Constraint::$groups` is meant to be an array of something, but not a `null`. 

https://github.com/symfony/symfony/blob/v5.3.11/src/Symfony/Component/Validator/Constraint.php#L190-L199

As a result we might end up in a situation when we have `null` in line `\in_array($group, $constraint->groups)`

https://github.com/symfony/symfony/blob/v5.3.11/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L123

### How to reproduce

There is nothing to reproduce here tbh

### Possible Solution

I believe the constructor should default groups to an empty array instead of `null`

```php
    public function __construct($options = null, array $groups = null, $payload = null)
    {
        $this->groups = []; // enable lazy initialization

        // ......
    }
```

**Comment by xabbuh** [comment]
I do not see where this can lead to am issue as the magic getter ensures that the groups are returned as an array.

**Comment by rvadym** [comment]
@xabbuh Magic getter is not used [here](https://github.com/symfony/symfony/blob/v5.3.11/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L123), it calls public property directly 

```php
                    foreach ($groups as $group) {
                        if (\in_array($group, $constraint->groups)) {
                            $groupedConstraints[$group][] = $constraint;

                            // Prevent duplicate validation
                            if (!$constraint instanceof Composite) {
                                continue 2;
                            }
                        }
                    }
```

**Comment by xabbuh** [comment]
Can you then please create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
@rvadym `__get` will be called by PHP, not directly by our code. That's why it is a *magic* getter.

In the past, we saw similar bugs when you create a custom Constraint subclass without calling the parent constructor. Not calling the parent constructor is not a supported use case, as it means that the class is not properly initialized.

**Comment by vrtulip** [comment]
@stof 

Well, PHP won't call magic method in the case if property `$this->groups` exists, and property exists if `unset` inside a constructor was not called. Which leads to the part `not calling the parent constructor is not a supported`, this is exactly what happened - the code I am working with does not call parent constructor. 

Thanks for clarifying! This issue is invalid and can be closed.

**Comment by rvadym** [comment]
@stof

Well, PHP won't call magic method in the case if property `$this->groups exists`, and property exists if unset inside a constructor was not called. Which leads to the part "not calling the parent constructor is not a supported", this is exactly what happened - the code I am working with does not call parent constructor.

Thanks for clarifying! This issue is invalid and can be closed.
