### ISSUE TITLE
[WebProfilerBundle] undefined "normalizer"

### ISSUE THREAD

**Issue by kor3k** [symfony/symfony#46537]
### Symfony version(s) affected

6.1.0

### Description

in web profiler's "Serializer" panel, i get error

```
Key "normalizer" for array with keys "data, dataType, type, format, time, context, normalization, encoding, encoder" does not exist.
```
in 
```
vendor/symfony/web-profiler-bundle/Resources/views/Collector/serializer.html.twig:191
```

for some reason, the "normalizer" is not set.
the data supplied to the response is an object/entity which indeed gets normalized & serialized. i am not using any custom normalizers, but i am using custom circular reference handler.

### How to reproduce

not really sure

### Possible Solution

check for key existence
```
{% if item.normalizer is defined %}
<span class="nowrap"><a href="{{ item.normalizer.file|file_link(item.normalizer.line) }}" title="{{ item.normalizer.file }}">{{ item.normalizer.class }}</a> ({{ '%.2f'|format(item.normalizer.time * 1000) }} ms)</span>
{% endif %}
```
but this solves the effect, but not the cause.

**Comment by kor3k** [comment]
![image](https://user-images.githubusercontent.com/888273/171313335-e3d9b289-b545-45de-9c97-5d0d12d74cdf.png)

so at the cursor's location should be "ArrayNormalizer" i suppose. it's blank with that existence check, throws mentioned error without it.

**Comment by 94noni** [comment]
according to https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Serializer/DataCollector/SerializerDataCollector.php#L197
the `normalizer` will be here only if there is `normalization` so it can be checked in that way no?

or we can always define this entry with empty data

(perhaps could be good to check as well `encoder` which is same as far as I can see)

**Comment by kor3k** [comment]
well in that case this should be sufficient

```
vendor/symfony/web-profiler-bundle/Resources/views/Collector/serializer.html.twig
```

191
```
  {% if item.normalizer is defined %}
  <span class="nowrap"><a href="{{ item.normalizer.file|file_link(item.normalizer.line) }}" title="{{ item.normalizer.file }}">{{ item.normalizer.class }}</a> ({{ '%.2f'|format(item.normalizer.time * 1000) }} ms)</span>
  {% endif %}
```

212
```
  {% if item.encoder is defined %}
  <span class="nowrap"><a href="{{ item.encoder.file|file_link(item.encoder.line) }}" title="{{ item.encoder.file }}">{{ item.encoder.class }}</a> ({{ '%.2f'|format(item.encoder.time * 1000) }} ms)</span>
  {% endif %}
```

**Comment by 94noni** [comment]
Can you open a PR? Perhaps yes this is enough :)
