### ISSUE TITLE
FrameworkConfig methods not found by PHPStan and psalm

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#46546]
### Symfony version(s) affected

5.4.9

### Description

Similar problem as in https://github.com/symfony/symfony/issues/42342

With a `framework.php` similar to the example shown at https://symfony.com/doc/current/http_client.html#scoping-client
```php
// config/packages/framework.php
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $framework->httpClient()->scopedClient('github.client')
        ->scope('https://api\.github\.com')
        ->header('Accept', 'application/vnd.github.v3+json')
        ->header('Authorization', 'token %env(GITHUB_API_TOKEN)%')
    ;
};
```
...psalm is reporting:

> PossiblyUndefinedMethod - config/packages/framework.php - Method Symfony\Config\FrameworkConfig::scopedClient does not exist

and PHPStan:

> Call to an undefined method Symfony\Config\Framework\HttpClientConfig|Symfony\Config\FrameworkConfig::scopedClient().

Even though I do have `public function scopedClient(string $name, $value = [])` in my `var/cache/dev/Symfony/Config/Framework/HttpClientConfig.php`

So it looks like adding this to `phpstan.neon` isn't enough anymore:
```yaml
scanDirectories:
    - var/cache/dev/Symfony/Config
```

The same error is raised for other packages, e.g.:
* Call to an undefined method Symfony\Config\Twig\GlobalConfig|Symfony\Config\TwigConfig::value().
* Call to an undefined method Symfony\Config\Monolog\HandlerConfig|Symfony\Config\MonologConfig::type().

Was there a change recently?

### How to reproduce

See above

**Comment by wouterj** [comment]
Seems like they don't like the unions added on e.g. `FrameworkConfig::httpClient()` by https://github.com/symfony/symfony/pull/46328

This can be improved by using conditional types, but that would make things unnecessary bloated imho. I think the best recommendation is to not static analyze the configuration.

**Comment by fabpot** [comment]
Closing then.

**Comment by wouterj** [comment]
On second thought, I think this might be worth reconsidering (given that one of the main benefits of PHP config is the ability to use industry tools for validating and autocompletion). I've submitted a fix: https://github.com/symfony/symfony/pull/46581

**Comment by Tofandel** [comment]
I might be missing something but I don't have or see a `Symfony\Config\FrameworkConfig` class anywhere in the source of symfony and in my project it's just in the cache, it makes for a bad development experience because of the missing autocompletion as the cache folder should not be indexed, maybe there should be a real file in symfony that gets overriden in the cache to help with this

**Comment by tacman** [comment]
It's not a great solution, but you can at least hide it by ignoring it in phpstan.neon:

```yaml
    ignoreErrors:
            -
                message: '#FrameworkConfig not found#'
                path: packages/

```

**Comment by stof** [comment]
@Tofandel those classes are generated on the fly for each bundle in your project. We cannot force each bundle to ship the generated code with their code (and that would be a maintenance nightmare as the generated code might depend on the version of the DI component). And we definitely cannot ship them all in Symfony.

**Comment by Tofandel** [comment]
Yes I figured as much, in the end I set my ide to index the `var/cache/local/Symfony` directory (I use local env for local dev, test for unit tests, dev for staging and prod for production, so in my case it's local and not dev) so that autocompletion works correctly

For psalm I added to psalm.xml
```xml
  <extraFiles>
    <directory name="var/cache/*/Symfony/Config"/>
  </extraFiles>
 ```

**Comment by ThomasLandauer** [comment]
Implemented in Symfony 6.2 through https://github.com/symfony/symfony/pull/44166

For PHPStan, see https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies
```neon
parameters:
    scanDirectories:
	- var/cache/dev/Symfony/Config
```

**Comment by atakchidi** [comment]
> Implemented in Symfony 6.2 through [#44166](https://github.com/symfony/symfony/pull/44166)
> 
> For PHPStan, see https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies
> 
> parameters:
>     scanDirectories:
> 	- var/cache/dev/Symfony/Config

Provided solution does not consider very important detail: var/cache/dev might not exist. For example in ci pipeline where everything works in test env. Setting this to var/cache/test is also not an option since this is also missing on the first run on the dev machine. So stan would fail with 
  [PHPStan\File\PathNotFoundException]                                     
  Path /home/www-data/project/var/cache/dev/Symfony/Config does not exist  

I did not find any solution to this at least in PhpStan docs. E.g. to make scanDirectories optional

**Comment by umulmrum** [comment]
I have the same problem with `dev` vs. `test`, so I wrote a simple autoloader specifically for PHPStan:

```php
spl_autoload_register(static function (string $class): void {
    if (!str_starts_with($class, 'Symfony\\Config\\')) {
        return;
    }
    $relativeFilePath = str_replace('\\', '/', $class) . '.php';
    foreach (['dev', 'test'] as $env) {
        $absoluteFilePath = __DIR__ . '/var/cache/' . $env . '/' . $relativeFilePath;
        if (file_exists($absoluteFilePath)) {
            include $absoluteFilePath;

            break;
        }
    }
});
```
And added this to the PHPStan config:

```yaml
    bootstrapFiles:
        - config/autoload_phpstan.php
```

This works well so far and I don't need to ignore errors.

**Comment by Tofandel** [comment]
@atakchidi 

Even if you made the directory optional, then it would fail because of missing methods or classes. The fail early in this case is a good behaviour, you should just warm up the cache before launching phpstan in ci

`php bin/console cache:warmup --env=test`
