### ISSUE TITLE
[Console] `%` signs in command's `description` leads to error on `bin/console list`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#46560]
### Symfony version(s) affected

6.1.0

### Description

Not a big deal, but I'm reporting it anyway:

When using the new `#AsCommand()` attribute, and the `description` contains a "parameter-like" substring (i.e. something between two `%` signs), then running `php bin/console list` results in:

> [critical] Error thrown while running command "list". Message: "The parameter "a\\" must be defined."
> In App_KernelDevDebugContainer.php line 370:                                   
> The parameter "a\\" must be defined.

### How to reproduce

```php
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;

#[AsCommand(name: 'app:foo', description: '%a%')]
final class FooCommand extends Command
{
}
```

### Possible Solution

Don't parse the `description` at all (i.e. output it as-is), or provide some escaping mechanism.

**Comment by HypeMC** [comment]
Have you tried escaping it with [another `%`](https://symfony.com/doc/6.1/configuration.html#configuration-parameters):
> If some parameter value includes the % character, you need to escape it by adding another % so Symfony doesn't consider it a reference to a parameter name

**Comment by ogizanagi** [comment]
Parameters parsing was probably unexpected in the description in the first place when introducing the `AsCommand` attribute, so it should be fixed to escape using `%%` automatically, I guess.

**Comment by ogizanagi** [comment]
Suggesting a fix: https://github.com/symfony/symfony/pull/46574
