### ISSUE TITLE
Container Parameters set via CompilerPass can not be used as Twig Globals

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#46615]
### Symfony version(s) affected

5.4.8, 6.1.0 (think versions before also)

### Description

It seems currently that the twig globals configuration doesn't use parameters from a compilerpass. It seems to be resolved before.

I was trying something like: 

```yaml
twig:
    globals:
        EXAMPLE_GLOBAL: '%app.twig_global%'
```

And:

```php
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel implements CompilerPassInterface
{
    use MicroKernelTrait;

    public function process(ContainerBuilder $container)
    {
        $container->setParameter('app.twig_global', 'Hello World');
    }
}
```

It errors that `app.twig_global` is not available.

### How to reproduce

Reproducer: https://github.com/alexander-schranz/symfony-reproducer-twig-global-compilerpass

```bash
git clone git@github.com:alexander-schranz/symfony-reproducer-twig-global-compilerpass.git reproducer-twig-global
cd reproducer-twig-global
composer install
bin/console cache:clear
```

### Possible Solution

Not sure how to fix this.

### Additional Context

I tried to create a `app.twig_global` parameter in the yaml and did then try to override the value in the compilerpass. But also this way it did not work and I did just get the value from the yaml not the one from the container.

**Comment by dmaicher** [comment]
I guess this is a matter of priorities. If the kernel itself implements `CompilerPassInterface` its added very late (probably after the pass that processes the twig config or resolves parameters?):

https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpKernel/Kernel.php#L685

This diff seems to be working:

```diff
--- a/src/Kernel.php
+++ b/src/Kernel.php
@@ -3,16 +3,18 @@
 namespace App;
 
 use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
-use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
 use Symfony\Component\HttpKernel\Kernel as BaseKernel;
 
-class Kernel extends BaseKernel implements CompilerPassInterface
+class Kernel extends BaseKernel
 {
     use MicroKernelTrait;
 
-    public function process(ContainerBuilder $container)
+    protected function getContainerBuilder(): ContainerBuilder
     {
-        $container->setParameter('app.twig_global', 'Hello World');
+        $builder = parent::getContainerBuilder();
+        $builder->setParameter('app.twig_global', 'Hello World');
+
+        return $builder;
     }
 }

**Comment by alexander-schranz** [comment]
@dmaicher you are right that works, thank you.

If I understand you correctly if we move in symfony this part: https://github.com/symfony/symfony/blob/527e085868b1f36f0fed275a003cb0e362973cbe/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L132-L139
Also to a compilerpass with a lower priority then 0 the compilerpass in Kernel.php should also work? So we could avoid this problem in future this way?

**Comment by dmaicher** [comment]
In this case the error comes from `MergeExtensionConfigurationPass` which is always the first pass... so not sure this can be easily fixed.

Maybe parameters should not be defined in compiler passes? :man_shrugging:

**Comment by alexander-schranz** [comment]
@dmaicher It is more complicated then not be defined in compilerpasses. We have a parameter which is a tree configuration. And for twig we are creating a easier accessable parameter based on the exist parameter. To avoid that the parameter need be written twice in different formats we use a compilerpass to provide this different representations of the parameter for different use cases.

**Comment by stof** [comment]
Parameters used in the semantic configuration of bundles are resolved before processing that semantic config. So you indeed cannot use parameters set by compiler passes in the semantic config of any bundle.

In your case, you should probably register the Twig global variable from a Twig extension instead of from the semantic configuration, to let you inject your parameter in your service instead.
And maybe you should not use a global variable if that value is a big tree configuration to avoid injecting it in all template rendering, exposing a Twig function to load it instead.

**Comment by alexander-schranz** [comment]
Sounds reasonable and the way to go with a twig extension I like. I think so we can close it as all parameters in the configs seems to work the same.

Thank you both for your help and view on this issue.
