### ISSUE TITLE
[DotEnv] Move DumpEnvCommand from Flex to DotEnv

### ISSUE THREAD

**Issue by chr-hertel** [symfony/symfony#46635]
### Description

While working with the DotEnv component it is beneficial to run `composer dump-env prod` for production installations in case you can't/don't use env vars. This is only possible though if you have also `symfony/flex` installed.

I would argue that this should be bundled with the DotEnv component instead as this tightly coupled to the usage of the component. So my proposal would be to migrate that command.

WDYT?

### Example

```
# before
composer dump-env prod

# after
bin/console dotenv:dump prod
````

**Comment by HypeMC** [comment]
Has already been done, see #42610.

**Comment by chr-hertel** [comment]
Ha, next time I double check! Thanks!
