### ISSUE TITLE
[RateLimiter] final class Factory does not implement an interface

### ISSUE THREAD

**Issue by nathansalter** [symfony/symfony#46644]
### Description

A fairly small issue, but when using the RateLimiter component, it's impossible to build UnitTests as the `Symfony\Component\RateLimiter\RateLimiterFactory` class is marked as `final` but doesn't implement an interface. This *can* be mitigated with reflection, but causes a poor developer experience. As there is also no way to inject a new type of limiter into this factory, this becomes non-trivial to implement a unit test, as you have to mock both the `StorageInterface` and `LockFactory` classes, inspecting how they are used in the standard implementations.

Simple fix: Add a `RateLimiterFactoryInterface`
More complete fix: Add a method in which to inject new types of rate limiter into the Factory. This would allow for alternative rate limiting strategies such as the [Leaky Bucket](https://en.wikipedia.org/wiki/Leaky_bucket) which currently doesn't have an implementation.

### Example

Running this code:
```
<?php
class RateLimitFactoryTest extends TestCase
{
    /** @var RateLimiterFactory|MockObject */
    private RateLimiterFactory $globalLimiter;
    protected function testLimitFactory()
    {
        $this->createMock(RateLimiterFactory::class);
    }
}
```
Throws an exception because the class is `final`.

**Comment by nathansalter** [comment]
See https://github.com/symfony/symfony/pull/46645

**Comment by lowwa132** [comment]
RateLimiterFactoryInterface has been added since Symfony 7.3 https://github.com/symfony/symfony/commit/619c0eb1800f0ae49e7cb42f0c6e6c696fafbcfd
