### ISSUE TITLE
Unable to add own classes. Error: Illegal offset type

### ISSUE THREAD

**Issue by Asmitta-01** [symfony/symfony#46659]
### Symfony version(s) affected

^5.4

### Description

I cannot add my own class in my project. If i have src\{folderName}\myclass.php and inside  `namespace App\{folderName}`, my app doesn't work again. I have an error message in the console or in the browser : 
>TypeError:
>Illegal offset type
>
>at C:\Users\tiwab\Documents\appName\vendor\symfony\config\Resource\ReflectionClassResource.php:142
>at ReflectionClass->getDefaultProperties()

I have created 3 new projects with 
```shell
symfony new --demo testapp1
symfony new testapp2
symfony new testapp3 --version=5.4
```
All of them also display the error when i added a new custom class. I can avoid this error by changing the namespace value (e.g `namespace App\Extension` for src\Helper\myClass) it works only if the namespace value doesn't make us reach the class. So it is still a problem, without the appropriate namespace i can't use my class. What should i do then please ? 

### How to reproduce

In my case i simply need to add my own class, it will gives me **Illegal offset type** if i write the good namespace.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Asmitta-01** [comment]
> Can you create a small example application that allows to reproduce your issue?

Creating a new project version >=5.4 (i don;t try the previous one)
After creating i launch the project `symfony serve`
If it is the demo i will have a beautiful demo website otherwise just the default homepage in the browser. 
I add my class, traditionnally in src\Helper and in my class i have `namespace App\Helper;`
I refresh the page in the browser and i get the error. A screenshot may help, i precise that it is the same message, same stack trace : 
![image](https://user-images.githubusercontent.com/69441849/173339909-9b3d9351-405c-4088-810c-91109471c109.png)

**Comment by derrabus** [comment]
What version of PHP is this?

**Comment by Asmitta-01** [comment]
**8.1.6**
It was 8.0.2, i changed saturday 13th

**Comment by Asmitta-01** [comment]
I have create a [discussion ](https://github.com/symfony/symfony/discussions/46653)for it and we found the solution.
It is not a bug but a problem with the class i wanted to use.
