### ISSUE TITLE
FormInterface is reported as `\Traversable<string, FormInterface>` but can return int as key.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#46698]
### Symfony version(s) affected

5.0.0 and more

### Description

Because the formBuilder use name as key, and because php is casting int-string like `'0'` to int, we sometimes ends with form name which is integer and this cannot be directly used by method like `FormInterface::remove`.

### How to reproduce

The following code 
```
foreach ($form as $name => $child) {
     $form->remove($name);
}
```
is not working when the form was build this way
```
$formBuilder->add('0', ...)
```
Because the name is casted to an int when used as an array key here:
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Form/FormBuilder.php#L71-L72

There are some situation  in the Symfony code where the form names can be int and passed to method expecting string. One of them is the `ChoiceType` with expanded option.
https://github.com/symfony/form/blob/6.1/Extension/Core/Type/ChoiceType.php#L407-L419

So far this code is working because `declare(strict_types=1);` is not used.

But for my first example
```
foreach ($form as $name => $child) {
     $form->remove($name);
}
```
if it's written in the userland with strict_types, it won't work even if all the phpdoc make believe it will:
- FormInterface is a `\Traversable<string, FormInterface>`
- remove accepts `string`

### Possible Solution

I see at least four solutions here:
- Changing some of the typehint in https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Form/FormInterface.php to accepts `int|string` (since it's a BC-break, this might wait for 7.0)
- Changing the phpdoc to `\Traversable<int|string, FormInterface>` with some comments; at least static-analysis user will be warned.
- Deprecating passing an integer-as-string as a form name ; this might be the smoother solution. Instead of `$formBuilder->add('0')` it should be `$formBuilder->add('prefix_0')`. And in SF 7.0, this will throw an exception.
- Doing nothing

**Comment by stof** [comment]
Note that if you don't turn on strict types in your file, the key implicitly casted as int by PHP will also be implicitly casted to string by the argument typehint.

Deprecating numeric strings would break CollectionType for instance.

**Comment by VincentLanglet** [comment]
> Note that if you don't turn on strict types in your file, the key implicitly casted as int by PHP will also be implicitly casted to string by the argument typehint.

Yes, I agree ; the issue only exists with strict_types. But I'm not sure the answer should be "We recommend to every Symfony user to not use strict_types".
 
> Deprecating numeric strings would break CollectionType for instance.

This is with this formType I had the issue when trying to reproduce a similar ResizeFormListener.
If one day Symfony decide to use strict_types, this file wouldn't work anymore https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php#L68

**Comment by VincentLanglet** [comment]
Any recommendation on this issue @nicolas-grekas or @xabbuh ?
I'm voluntary to contribute, but I don't know which solution you would prefer.

**Comment by derrabus** [comment]
Option 5: Make sure integer keys are being cast back to string in our `Traversable` implementations?

**Comment by VincentLanglet** [comment]
> Option 5: Make sure integer keys are being cast back to string in our `Traversable` implementations?

Seems like a nice idea @derrabus.

We're using a OrderedHashMap for childrens
https://github.com/symfony/symfony/blob/870eeb975feb1abb4b8a1722e1fd57beeab2b230/src/Symfony/Component/Form/Form.php#L155
The `getIterator` method is returning an OrderedHashMapIterator
https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/Form/Util/OrderedHashMap.php#L155
And we could change the `key` method here:
https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/Form/Util/OrderedHashMapIterator.php#L110-L119

Should I
- cast the key to string ? Because it's only used for string keys so far and the class is internal.
- create another iterator which extends this one ?

Also, which branch should I target

**Comment by derrabus** [comment]
Dunno, like this?

```php
public function getIterator(): \Traversable
{
    foreach ($this->children as $key => $value) {
        yield (string) $key => $value;
    }
}
```

> which branch should I target

Good question. Maybe we should play it safe and target 6.2.
