### ISSUE TITLE
[Cache] allow enabling \Redis::OPT_COMPRESSION and \Redis::OPT_COMPRESSION_LEVEL via connection string

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#46694]
### Description

Currently, `\Symfony\Component\Cache\Traits\RedisTrait::createConnection` doesn't seem to provide a way to pass compression options. In my tests, I'm seeing up to 80% reduction in memory usage with just passing 

```php
$redis->setOption(\Redis::OPT_COMPRESSION, \Redis::COMPRESSION_ZSTD);
```

### Example

Use

```
rediss://password@host/?compression=zstd # boolean defaults to something, string enables a specific one
```

**Comment by nicolas-grekas** [comment]
You can enable compression using DeflateMarshaller, see https://github.com/symfony/symfony/pull/34133 for background on this.
Doc PR welcome :)

**Comment by dkarlovi** [comment]
@nicolas-grekas thanks, I can see it was heavily discussed, I've searched issues for this, but I guess I should always start with PRs. :)

**Comment by dkarlovi** [comment]
@nicolas-grekas reading the reasoning again:

> It's not enabled by default because that might break pools that are shared between different apps.

This applies to igbinary too though, right?

**Comment by nicolas-grekas** [comment]
True. It's a bit less a problem with igbinary because there is support for graceful fallbacks. But we could think about a path forward to enable this by defaut. Eg via a recipe?

**Comment by dkarlovi** [comment]
I think it would be valuable to promote this as a default indeed. :+1: The difference with and without compression is very substantial (up to 80% difference in our case), translating to very real benefits with it being enabled. :money_with_wings:
