### ISSUE TITLE
Symfony Amazon SES Mailer Without ACCESS_KEY and SECRET_KEY

### ISSUE THREAD

**Issue by excelwebzone** [symfony/symfony#46706]
### Symfony version(s) affected

5.4.4

### Description

I'm trying to send emails using AWS SES using **IAM instance profile** defined under Elastic Beanstalk environment.

I configured in my `.env.local`:

```
MAILER_DSN='ses+api://default?region=us-west-2'
```

> Note: Had to add to my **VirtualHost** `SetEnv HOME /Users/xxxxxxx`

This configuration works nicely on my local machine (code is pulling credentials from `~/.aws/credentials` file. But on the Elastic Beanstalk environment it fails to pull from the defined IAM instance profile.

Error message received:

`
Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to send an email: Missing Authentication Token (code MissingAuthenticationTokenException).
`

### How to reproduce

```php
// First, run "composer require symfony/amazon-mailer"
// Then, execute this file:
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Mailer\Transport;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mime\Email;

try {
    $transport = Transport::fromDsn('ses+api://default?region=us-west-2');
    $mailer = new Mailer($transport);

    $email = (new Email())
        ->from('hello@example.com')
        ->to('you@example.com')
        ->subject('Time for Symfony Mailer!')
        ->text('Sending emails is fun again!')
        ->html('<p>See Twig integration for better HTML integration!</p>');

    $mailer->send($email);
} catch (\Exception $e) {
    var_dump($e->getMessage());
}
```

**Comment by franckranaivo** [comment]
It seems that it is not related to Symfony nor the Amazon mailer itself but rather the configuration files which is not present on the machine. I could reproduce your issue on an Elastic Beanstalk environment. Anyway, once I **added my local credentials** by creating file `~/.aws/credentials` on the EC2 instance I didn't get any errors at all. Have you tried to check if file is present on your Elastic beanstalk environment ?

I checked into the Amazon mailer bridge code, if it doesn't find the credentials in the DSN then it would look for credentials file (which is your case with the local machine) as a fallback option. If it runs out of option then it triggers this exception.

Maybe a better solution is to add a more explicit error message ?

**Comment by excelwebzone** [comment]
It's unnecessary to generate `~/.aws/credentials` in AWS EC2 instance as it already connected to an IAM profile contains access to the `ses:SendRawEmail` and/or `ses:SendEmail`.

I believe the issue is that mailer transport is using the `async-aws/ses` which seems to force the use of of the **accessKeyId** and **accessKeySecret** (https://async-aws.com/configuration.html).

> Note: might need to create a custom transport to handle it.

**Comment by stof** [comment]
According to https://async-aws.com/authentication/ec2-metadata.html, async-aws should be able to use the credentials from the role of the instance

**Comment by stof** [comment]
However, the SesTransportFactory of symfony/amazon-mailer does not allow configuring the authentication of the client when it creates it.

**Comment by excelwebzone** [comment]
> According to https://async-aws.com/authentication/ec2-metadata.html, async-aws should be able to use the credentials from the role of the instance

Correct. The issue is how to use the assigned profile (role), not a user (using credentials). In my Elastic Beanstalk environment the instance points to `aws-elasticbeanstalk-ec2-role` role. So when I try (for example) upload a file to S3, when using the AWS\S3Client it automatically check the role and give me access. but not here.

**Comment by jderusse** [comment]
Async AWS should pick the instance's credentials. I just give a try with `MAILER_DSN='ses+api://default?region=us-west-2'`

Could you help troubleshoot the issue?

in your logs (level info) you should see calls like
```
23:20:55 INFO      [http_client] Request: "GET http://169.254.169.254/latest/meta-data/iam/security-credentials"
```

If the fetch failed, you should notice errors like 
```
23:20:56 INFO      [mailer] Failed to fetch Profile from Instance Metadata. ["exception" => Symfony\Component\HttpClient\Exception\TransportException^ { …}]
```

But if the fetch works, AsyncAWS should have downloaded the credentials, in that case
in `vendor/async-aws/core/src/Credentials/InstanceProvider.php` try to add debug traces in the `getCredentials` method. Asserts that the method is called, check the content of the various $response

**Comment by excelwebzone** [comment]
@jderusse I run a test on the server and got the following error:

`
HTTP/1.1 401 Unauthorized returned for "http://169.254.169.254/latest/meta-data/iam/security-credentials"
`

**Comment by excelwebzone** [comment]
**FIX:** Under `instances` in Elastic Beanstalk configuration you have to enable support for IMDSv1 which fix the issue. See [Instance metadata service (IMDS)](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-ec2-imds.html?icmpid=docs_elasticbeanstalk_console) for more details.

**Comment by stof** [comment]
async-aws indeed does not support IMDSv2 yet. There is an open issue about it at https://github.com/async-aws/aws/issues/1163 but nobody worked on it yet.
