### ISSUE TITLE
Indicate invalid fields in a form before submitting

### ISSUE THREAD

**Issue by Trkzi-Omar** [symfony/symfony#46712]
### Context
Using some forms where the user experience is trivial, since the potential user isn't used to online form filling. For example, he might not pay attention to the fact that the data submitted isn't saved (stored in the DB) if the values entered are invalid.  Hence, the importance of checking the validity of fields before submitting.

- Form validation is based on constraints like:

` 
   @Assert\LessThanOrEqual(value="4",message="This value must be less than or equal to 4")
`
### Current behavior
Not checking for validity of fields **before** the submit:
![image](https://user-images.githubusercontent.com/81875005/174458167-ae1ccd63-3968-436b-af0a-c0b1a4c251a5.png)

Only checking for validity of fields **after** the submit:
![image](https://user-images.githubusercontent.com/81875005/174458030-fe71eed5-e297-41cc-88c7-e0a97efe8bbc.png)

### Suggested feature
Checking validation of forms before `submit`, is achievable using `onChange` and `onKeyUp` with Vanilla JS. It would be a great win for Symfony if some equivalent feature was available.

**Comment by ghost** [comment]
Symfony is a backend PHP framework that uses server side rendering. What you ask for requires writing JavaScript and this is the part you have to take care on your own.

**Comment by Trkzi-Omar** [comment]
>  What you ask for requires writing JavaScript and this is the part you have to take care on your own.

I understand that.
The requested feature is some kind of an interceptor that translates each `@Assert` into a regular JS validation-constraint. 
I can imagine it would work just like [client side html validation](https://symfony.com/doc/current/forms.html#client-side-html-validation).

**Comment by norkunas** [comment]
You could use live component from [Symfony UX](https://ux.symfony.com)

**Comment by Trkzi-Omar** [comment]
Thank you @norkunas .
[This](https://ux.symfony.com/live-component#demos) solves my issue.
