### ISSUE TITLE
Use the validators without context

### ISSUE THREAD

**Issue by sgoranov** [symfony/symfony#46736]
### Symfony version(s) affected

4.4.40

### Description

It looks like it's not possible to use the validators without a context but it would be very useful if possible. Currently an error is thrown when a validator is used without context:

`Fatal error: Uncaught Error: Call to a member function buildViolation() on null in /project/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/UrlValidator.php on line 79`

### How to reproduce

```
<?php

use Symfony\Component\Validator\Constraints\Url;
use Symfony\Component\Validator\Constraints\UrlValidator;

require __DIR__.'/../vendor/autoload.php';

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$url = new UrlValidator();
$url->validate('httpsA://example.com', new Url(['protocols' => ['https']]));
```

**Comment by stof** [comment]
Constraint validators are indeed not supporting to call validate without initializing the context.

but note that they are not expected to be called directly either, but by the main Validator class.

**Comment by sgoranov** [comment]
> Constraint validators are indeed not supporting to call validate without initializing the context.
> 
> but note that they are not expected to be called directly either, but by the main Validator class.

It would be very helpful if possible. For example, in case someone wants to validate a configuration parameter or application option. I think that in this particular case, the translation of the error message is an unwanted feature.
On the other hand, I understand that the validators are not intended to be used as in the example, but even so it seems strange that the error that is returned is _Fatal error: Uncaught Error: Call to a member function buildViolation() on null_ instead to throw an exception with _Missing context_ or similar.

**Comment by stof** [comment]
Using the main Validator class can still be done with an IdentityTranslator if you don't want to translate messages. The main purpose of the Validator class is not to translate error messages but to orchestrate all the constraint validators.

> instead to throw an exception with _Missing context_ or similar.

That would require adding checks everywhere in the code of constraint validator, for something that will never be reached when using the component in the documented way.
