### ISSUE TITLE
Enum as keys doesn't work in yaml with !php/const

### ISSUE THREAD

**Issue by xlaussel** [symfony/symfony#46764]
### Symfony version(s) affected

6.1

### Description

Enums work in yaml when they define a value but not as a key.
For example:

```
enum Status {
  OK;
  NOK;
}

Following yaml works:

statuses:
  okcode: !php/const Status:OK
  nokcode: !php/const Status::NOK

But this one not:

statuses:
  labels:
    !php/const Status::OK: It is OK
    !php/const Status::NOK: It is not OK
```

Note that it It works as key with regular PHP const.
So it keep using regular const but I prefer enums...

### How to reproduce

```
enum Status {
  OK;
  NOK;
}

statuses:
  labels:
    !php/const Status::OK: It is OK
    !php/const Status:NOK: It is not OK
```

**Comment by stof** [comment]
This is because enums cannot be used as array keys in PHP. So we cannot parse a Yaml file in a way that would produce such array.

**Comment by SirTomme** [comment]
Could this be made possible in case of a backed enum of type string? Tried to do this with 6.4 but it doesn't work.
A public const on the enum works, though (as expected)

**Comment by derrabus** [comment]
Possibly, but we should noch abuse the `!php/const` syntax for this. An enum is not a collection of constants.

**Comment by xabbuh** [comment]
see #61082

**Comment by RafaelKr** [comment]
It actually works in my Symfony 7.2 project for StringBackedEnum if you use `->value`:

```php
enum Status: string {
  case OK = 'ok';
  case NOK = 'nok';
}
```

```yaml
statuses:
  labels:
    !php/enum Status::OK->value: It is OK
    !php/enum Status::NOK->value: It is not OK
```
