### ISSUE TITLE
Datapart fails when parsing png file types

### ISSUE THREAD

**Issue by turbo124** [symfony/symfony#46770]
### Symfony version(s) affected

6.1

### Description

I am seeing an issue in Symfony\Component\Mime\Part\Datapart where if the filetype is a png the mime being returned is a single word png rather than the expected image/png this causes the constructor to fail due to the following

```
[$this->mediaType, $subtype] = explode('/', $contentType);
```

This returns an error

```
error failed with Undefined array key 1  
```

### How to reproduce

This was picked up when iterating through an array of attachments in Symfony\Component\Mime\Email the output is below:

```
            [attachments:Symfony\Component\Mime\Email:private] => Array
                (
                    [0] => Array
                        (
                            [path] => /path/to/0014.pdf
                            [name] => 
                            [content-type] => 
                            [inline] => 
                        )

                    [1] => Array
                        (
                            [path] => http://url/to//bPmGOA0KmDLbbRfyjsKxCxRO2hiDx2CsIbC0CKrB.png
                            [name] => unnamed.png
                            [content-type] => png
                            [inline] => 
```

### Possible Solution

If no trailing slash in $contentType, perhaps use MimeTypes guesser to infer the correct type?

**Comment by stof** [comment]
`png` is not a valid content type

**Comment by willbrowningme** [comment]
I also ran into this issue when forwarding messages some of which have an invalid content type for attachments. Updating the `DataPart.php` constructor to the following seems to be a decent fix for me at least:

```php
public function __construct($body, string $filename = null, string $contentType = null, string $encoding = null)
{
    unset($this->_parent);

    if (null === $contentType) {
        $contentType = 'application/octet-stream';
    }

    if (! str_contains($contentType, '/')) {
        self::$mimeTypes = new MimeTypes();
        $contentType = self::$mimeTypes->getMimeTypes($contentType)[0] ?? 'application/octet-stream';
    }

    [$this->mediaType, $subtype] = explode('/', $contentType);

    parent::__construct($body, null, $subtype, $encoding);

    if (null !== $filename) {
        $this->filename = $filename;
        $this->setName($filename);
    }
    $this->setDisposition('attachment');
}
```

Edit: I've set the above Content-Type check in the app files now, so no need to change vendor file.

**Comment by Mitcal** [comment]
It seems like this can also fail if the $body is null.

**Comment by xabbuh** [comment]
@Mitcal The `$body` parameter of the `DataPart` class must not be `null` (it must either be `resource`, `string` or a `File` object).

**Comment by Mitcal** [comment]
Thanks @xabbuh , I think the problem that I was experiencing was because the $body was a File object but the file did not exist in the file system. So the content of the File object was null although $body itself was not null. If that makes sense?
