### ISSUE TITLE
[HttpFoundation] PHP Warning:  `SessionHandler::read()`: Session ID is too long or contains illegal characters.

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#46777]
### Symfony version(s) affected

6.1.0

### Description

Hi,

When I cheat on the front-end and manually change the session cookie length with the dev console, this emits a warning on the back-end:
```log
[25-Jun-2022 20:54:15 UTC] PHP Warning:  SessionHandler::read(): Session ID is too long or contains illegal characters. Only the A-Z, a-z, 0-9, &quot;-&quot;, and &quot;,&quot; characters are allowed in C:\app\vendor\symfony\http-foundation\Session\Storage\Handler\StrictSessionHandler.php on line 45
```

Therefore, malicious users can generate warning messages.

### How to reproduce

You just need to manually change the session cookie in the front-end and put more than 256 characters.

### Possible Solution

I guess that the regular expression on this line should check the max length too:
https://github.com/symfony/symfony/blob/6597825972e0c9f881717261860415dc360c7dd0/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L139

Maybe like this: `'/^[a-zA-Z0-9,-]{22,256}$/'`. According to the [PHP doc](https://www.php.net/manual/en/session.configuration.php#ini.session.sid-length) : 

> session.sid_length int
> session.sid_length allows you to specify the length of session ID string. Session ID length can be between 22 to 256. The default is 32. If you need compatibility you may specify 32, 40, etc. Longer session ID is harder to guess. At least 32 chars are recommended.

### Additional Context

Related PR: https://github.com/symfony/symfony/pull/46249.

_No response_

**Comment by xabbuh** [comment]
Would you like to send a PR with your suggested solution?

**Comment by ghost** [comment]
> Would you like to send a PR with your suggested solution?

@xabbuh Done https://github.com/symfony/symfony/pull/46790
