### ISSUE TITLE
Needless email when using monolog + mail + fingers_crossed

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#46801]
### Symfony version(s) affected

6.1.0

### Description

Hi,

I have configured error mails for my project:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50

        grouped:
            type: group
            members: [nested, deduplicated]
        
        deduplicated:
            type: deduplication
            handler: symfony_mailer

        symfony_mailer:
            type:       symfony_mailer
            from_email: '...'
            to_email:   '...'
            subject:    '[Error] %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
```

and now I always get 2 (!) mails:

one with the actual error log and then this one immediately afterwards:
![CleanShot 2022-06-29 at 12 30 52](https://user-images.githubusercontent.com/1032411/176416525-24274e0c-bac2-4a9b-b931-bfc3139d0c31.png)

Can I disable the second mail, as it provides no value to me. 😅 

### How to reproduce

See config above

**Comment by raziel057** [comment]
Yes it’s a known issue. See https://github.com/symfony/monolog-bundle/issues/405

Aa a workaround can exclude the mailer channel as explained here https://github.com/symfony/monolog-bundle/issues/405#issuecomment-1069040234

**Comment by xabbuh** [comment]
closing in favor of symfony/monolog-bundle#405 then
