### ISSUE TITLE
SEO and optimizations in the symfony webprofiler

### ISSUE THREAD

**Issue by vinceAmstoutz** [symfony/symfony#46818]
### Description

Goal : helps you improve the accessibility and SEO of your pages with some simple optimization insights.

Shape (purpose) : like the deprecation part of the web profiler, this tool can be used to identify SEO or performance improvements on each page, a bit like [PageSpeed Insights](https://pagespeed.web.dev/) or [GTMetrix](https://gtmetrix.com/). 

Today it has become essential for a lot of business (optimization and SEO) !

**Comment by stof** [comment]
To me, this is something that is best provided as a bundle than as part of the core

**Comment by vinceAmstoutz** [comment]
> To me, this is something that is best provided as a bundle than as part of the core

Yes but it is possible to provide it in a bundle and integrate it to the webprofiler only
 if someone adds the bundle no ?

**Comment by stof** [comment]
yes. the web profiler is extensible. Bundles can add panels in it.

**Comment by vinceAmstoutz** [comment]
> yes. the web profiler is extensible. Bundles can add panels in it.

So this can be perfect ! 😄

**Comment by lyrixx** [comment]
> To me, this is something that is best provided as a bundle than as part of the core

👍🏼 I agree with @stof

**Comment by vinceAmstoutz** [comment]
And otherwise, it seems to you @lyrixx @stof  interesting and realizable?

**Comment by stof** [comment]
Well, I for sure won't work on it. And I don't think this is something for which the core team has an interest maintaining it instead of letting some SEO-minded people maintain it (this sentence is my opinion only, maybe some core team members will disagree).

**Comment by fabpot** [comment]
I agree that this is not something we should have in core as it needs some good SEO understanding. Anyway, doing that in a bundle would not limit the ability to develop something on this topic. Let's close.

**Comment by vinceAmstoutz** [comment]
Thank you all for your constructive feedback. I completely understand your point of view and I wish you courage for the future :)!
