### ISSUE TITLE
[VarExporter] Handle readonly properties

### ISSUE THREAD

**Issue by fmata** [symfony/symfony#46841]
### Symfony version(s) affected

6.1

### Description

As described in #46840, VarExporter doesn't seem to handle readonly properties correctly.

### How to reproduce

[See https://github.com/symfony/symfony/pull/46840#issuecomment-1173854345](https://github.com/symfony/symfony/pull/46840#issuecomment-1173854345)

**Comment by nicolas-grekas** [comment]
Looking at the code, this should work, and there are tests about readonly properties.
Does this happen with a non-empty cache only or does it happen all the time?
Can you figure out a reproducing app please? The copy/pasted code in the linked PR are not enough to easily reproduce.
Thanks

**Comment by fmata** [comment]
I was making the reproducer when I realize my version of symfony/var-exporter was v6.0.6 because it's a transitive dependency of my project. I updated it to v6.1.1 and it works fine. Sorry for the noise :)
