### ISSUE TITLE
Create `HttpFoundation\Request->toObject()` Function

### ISSUE THREAD

**Issue by TheDevick** [symfony/symfony#46864]
### Description

Create a function, similar to `toArray()`, but instead to return an ***Array***, return an ***Object***

### Example

When the client send an **Json** to the Request, we manipulate the values, right? Image an scenario where we have to **Tranform** these values into an **Object:**
```php
$DataArray = $request->toArray();
$DataObject = (object) $DataArray;

$DataObject ->name;
$DataObject ->website;
```

So, the Feature Request is to create an `toObject` function, where will return an **Object**.
With the new function, we reduce the code:
```php
$Data = $request->toObject();

$Data->name;
$Data->website;
```

**Comment by chalasr** [comment]
Closing as explained in the linked PR. Thank you for proposing and going through the contribution process.
