### ISSUE TITLE
[HttpClient] and assumption about var_dump with PHP8.x

### ISSUE THREAD

**Issue by mentalstring** [symfony/symfony#46881]
### Symfony version(s) affected

5.4 & others

### Description

Some production setups set `disable_functions` to include `var_dump` (and `exec`, `shell_exec`, `phpinfo`, etc) for security purposes. This means that `var_dump()` may not be always be callable. This becomes relevant here:

https://github.com/symfony/symfony/blob/26338772ed47afd38d7fa7b53cafd6c8af3aba9c/src/Symfony/Component/HttpClient/HttpClientTrait.php#L123-L126

The most common case is that `on_progress` is not set, so `is_callable('var_dump')` is the most common pattern.

This is a problem from PHP 8.0+ because the behaviour changed for `is_callable('var_dump')` when the function is disabled.

### How to reproduce

```
$ # PHP 7.4
$ php -d'disable_functions=var_dump' -r 'var_export(is_callable("var_dump"));'
true
```

```
$ # PHP 8.0
$ php -d'disable_functions=var_dump' -r 'var_export(is_callable("var_dump"));'
false
```

### Possible Solution

Perhaps switch `var_dump` to something innocuous like `is_int`?

**Comment by guilliamxavier** [comment]
If `'var_dump'` is only used as a "dummy" for `is_callable()`, why not do the boring but straightforward

```diff
-        if (!\is_callable($onProgress = $options['on_progress'] ?? 'var_dump')) {
+        if (null !== ($onProgress = $options['on_progress'] ?? null) && !\is_callable($onProgress)) {
```

?
