### ISSUE TITLE
non ICU syntax translation pluralization is not working in symfony 6+

### ISSUE THREAD

**Issue by janwebdev** [symfony/symfony#46894]
### Symfony version(s) affected

6.1

### Description

It is said in the docs, that we may NOT use ICU MessageFormat syntax https://symfony.com/doc/current/translation.html#message-format,
however, using the "old-style" translation file format seems not to work

### How to reproduce

1. Install the full version of symfony 6.1 (with twig and translations)
2. create file in `./translations` folder `messages+intl-icu.en.yaml` with the following content:
```
replies.trans.var: '{0}%reply% replies|{1}%reply% reply|[1,Inf]%reply% replies'
```
3. In any twig template add variable with translation filter:
```
{% set amount = random([0,1,2,3,4,5]) %}
<div>{{ 'replies.trans.var'|trans({'%reply%': amount}) }}</div>
```
4. refresh the page

Then you'll see, that translation with pluralization is not working :/
it is shown `{0}1 replies|{1}1reply|[1,Inf]1 replies`

5. Also try to rename the file `messages+intl-icu.en.yaml` to `messages.en.yaml` - the same result

**Comment by danielburger1337** [comment]
From the docs:

> The message variable must include all the different versions of this message **based on the value of the count** parameter.

You have to use the `%count%` translation parameter instead of your custom `%reply%`. Otherwise the translator does not know which parameter it should use to find the correct pluralization.

You can take a look at the actual implementation in [Symfony\Contracts\Translation\TranslatorTrait](https://github.com/symfony/contracts/blob/main/Translation/TranslatorTrait.php#L50-L129).

You also can submit a documentation PR to clarify this behaviour if you think it is not clear enough.

**Comment by janwebdev** [comment]
> From the docs:
> 
> > The message variable must include all the different versions of this message **based on the value of the count** parameter.
> 
> You have to use the `%count%` translation parameter instead of your custom `%reply%`. Otherwise the translator does not know which parameter it should use to find the correct pluralization.
> 
> You can take a look at the actual implementation in [Symfony\Contracts\Translation\TranslatorTrait](https://github.com/symfony/contracts/blob/main/Translation/TranslatorTrait.php#L50-L129).
> 
> You also can submit a documentation PR to clarify this behaviour if you think it is not clear enough.

@xabbuh, Thank you very much for your help and explanation.
Now I understand, that it is not a bug, but I incorrectly understood documentation and how to use syntax

**Comment by xabbuh** [comment]
I think you need to thank @danielburger1337 :)
