### ISSUE TITLE
Symfony 6.1.2 : infinite loading of the web debug toolbar with 404 errors

### ISSUE THREAD

**Issue by eved42** [symfony/symfony#46890]
### Symfony version(s) affected

6.1.2

### Description

I created a new Symfony 6.1.2 project in the htdocs directory of Xampp 8.1.6 (Windows 11) and when I open http://localhost/my-project/public/ the web debug toolbar has an infinite loading because of a 404 error.

`symfony new my-project --webapp`

![error 404](https://user-images.githubusercontent.com/12841417/177968992-672a04d5-871d-4427-9652-d89024c59236.png)

I configured the database connection in the .env file (not sure about the version parameter) :
`DATABASE_URL="mysql://myuser:mypwd@127.0.0.1:3306/mydb?serverVersion=10.4.24-MariaDB&charset=utf8mb4"`

I created a controller : 
```
symfony console make:controller
IndexController
```
And I changed the route :
`#[Route('/', name: 'app_index')]`

According to `symfony check:requirements` , I updated the `realpath_cache_size` in the php.ini used by Xampp, I enabled the intl extension and I put `post_max_size` to 45M (greater than `upload_max_filesize`).

Both Symfony CLI and Git Basch use the same php 8.1.6 (C:\xampp\php).

### How to reproduce

- Windows 11 Entreprise x64
- Xampp 8.1.6
- php 8.1.6
- Symfony CLI 5.4.12

### Additional Context

I also tried to do the same with the last version of wampserver (3.2.6), I needed to install separetely PhpMyAdmin 5.2.0 because the included version (5.1.1) wasn't compatible with php 8.1.

And I have the same error as with Xampp, the debug toolbare (profiler) is showing 404 errors in a loop.

I also have this error with Symfony 6.0.

**Comment by eved42** [comment]
Problem solved with Apache pack : 

`composer require symfony/apache-pack`

**Comment by francwalter** [comment]
I have this issue, when I run symfony (8) with Apache but without FastCGI, mod_proxy and mod_proxy_fcgi.
With the symfony webserver it works. Took me a while to discover that symfony has its own webserver 😏
