### ISSUE TITLE
[HttpKernel] HttpCache Store cache key algorithm speed improvement

### ISSUE THREAD

**Issue by pascalwoerde** [symfony/symfony#46893]
### Description

The current store generates a `sha256` cache key for every item. For a few requests this is fine. In particular when many requests are executed in a process, we can easily improve the total execution time by replacing this with a faster algorithm. 

### Possible Solution

https://github.com/symfony/http-kernel/blob/6.1/HttpCache/Store.php#L229

Replace `sha256` with `xxh3`

**Comment by nicolas-grekas** [comment]
Can you please send a PR? This should be used only when available of course (I didn't check its availability.)
