### ISSUE TITLE
Doctrine related error is thrown in `prod` environment only

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#46934]
### Symfony version(s) affected

4, 5, 6

### Description

Doctrine related errors, for example:
- `No identifier/primary key specified for Entity "EntityClass". Every Entity must have an identifier/primary key`
- `Unable to create a proxy for a final class "EntityClass"`
are thrown in `prod` environment only.

We can't detect this error until we are ready to deploy the code.

### How to reproduce

Add empty entity (without property `id`) and then run
```
bin/console cache:warmup --env=dev
bin/console cache:warmup --env=prod
```

### Additional Context

![](https://user-images.githubusercontent.com/79239132/178889999-5480aaf7-3338-4758-a628-b04b709bc223.png)

**Comment by norkunas** [comment]
That's because proxy generation is enabled only in prod mode. You should not make your entities final
