### ISSUE TITLE
Add support for setting custom CID for image attachment

### ISSUE THREAD

**Issue by arxeiss** [symfony/symfony#46959]
### Description

In SwiftMailer this was supported, and I was able to set custom CID for inline image attachments.

The reason, why I need this is, that I have prepared templates for an email with CID already in place. However, attachment is generated and added on the fly. This is what I have in my HTML template:

`<img src="cid:qrpayment@sunapp.generated" alt="QR Payment" width="200" height="200" style="width: 200px;height: 200px;" >`

### Example

My current solution includes custom DataPart class, which overrides the Symfony one. However, I think this one could be implemented directly in DataPart class.

```php
$image = new DataPart($qrCode->toPngText(), 'QR Payment.png', 'image/png');
$image->setContentId('qrpayment@sunapp.generated');
$symfonyMessage->attachPart($image);
```

```php
<?php

declare(strict_types=1);

namespace SunApp\Mail\Symfony;

use Symfony\Component\Mime\Header\Headers;
use Symfony\Component\Mime\Part\DataPart as SymfonyDataPart;

class DataPart extends SymfonyDataPart
{
    private ?string $contentId;

    public function setContentId(string $cid): void
    {
        $this->contentId = $cid;
    }

    public function getContentId(): string
    {
        return $this->contentId ?: $this->contentId = $this->generateMyContentId();
    }

    public function hasContentId(): bool
    {
        return null !== $this->contentId;
    }

    public function getPreparedHeaders(): Headers
    {
        $headers = parent::getPreparedHeaders();

        if (null !== $this->contentId) {
            $headers->setHeaderBody('Id', 'Content-ID', $this->contentId);
        }

        if (null !== $this->getFilename()) {
            $headers->setHeaderParameter('Content-Disposition', 'filename', $this->getFilename());
        }

        return $headers;
    }

    private function generateMyContentId(): string
    {
        return \bin2hex(\random_bytes(16)) . '@sunapp.generated';
    }
}

```

**Comment by arxeiss** [comment]
@fabpot why this issue is closed, as the PR was not merged? @derrabus closed PR in https://github.com/symfony/symfony/commit/52a2eab76ea8ec8355c2f3560831d07995b65b8a but I don't see any changes related to this issue.

**Comment by fabpot** [comment]
@arxeiss Not sure why. Can you create a new one?

**Comment by arxeiss** [comment]
Cannot we reopen this? If not, I will create new one and PR as well.
