### ISSUE TITLE
UserInterface::getUsername(), UserInterface::getUserIdentifier(), UserInterface::getUsername(), and UserInterface::getUserIdentifier() should be type hinted as int|string

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony#46954]
### Description

Right now, they are all type hinted or docblock hinted to string.  I have a common use case where a user's unique identifier is an integer UID.  I can obviously do string to int conversions to get around this, but it seems like a common enough use case for the API to not require the janky workaround, especially given the improvement of renaming "username" to "identifier"

**Comment by derrabus** [comment]
`UserInterface::getUserIdentifier()` is a contract consumed by the security component. And that component requires the identifier to be string. Bringing the identifier into the required format is your responsibility. You don't have to call the `getUserIdentifier()` method yourself and you're also free to add additional methods that return the user identifier in any shape or form you want it to be.

I don't think we should change the contract here.

**Comment by chalasr** [comment]
Same here. If it supports integers, then why not floats.
Any user identfier can be cast to string, which makes it a sensible type for the UserInterface expectations. It might not reflect the type your domain user needs, but it's the one your security layer needs. 
Thanks.

**Comment by wouterj** [comment]
It is important to add that `getUserIdentifier` is *not* meant to return the ID of the user (I see you mention UUID) - but instead the identifier used to login (in a traditional website, this often is the "username" field).

**Comment by arderyp** [comment]
Okay, fair enough points.  I just assumed it was an extremely common use case to use int (maybe it actually is not and I am biased), but I could see how it would be a ton of work to restructure things.  Thanks for the infight.

**Comment by arderyp** [comment]
> It is important to add that `getUserIdentifier` is _not_ meant to return the ID of the user (I see you mention UUID) - but instead the identifier used to login (in a traditional website, this often is the "username" field).

Yes, maybe what I typed was misleading.  I'm not talking about the user entity's incremental ID (doctrine field). I'm bound to an SSO that all hinged on an int "uid" shared across the enterprise.
