### ISSUE TITLE
Add a setPort method to MailerInterface or port field in mailer.yaml

### ISSUE THREAD

**Issue by Asmitta-01** [symfony/symfony#46979]
### Description

I use symfony/mailgun and i always get this error: 
```
Connection could not be established with host "ssl://smtp.mailgun.org:465": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```
I specify the port in the dsn(my .env file): 
```
###> symfony/mailgun-mailer ###
# MAILER_DSN=mailgun://2b11***394f-18e06deb-0a142a30:sand***8f06b.mailgun.org@default?region=us
MAILER_DSN=mailgun+smtp://postmaster%40sandbox5fa7d0740602***b.mailgun.org:631***18e06deb-5bfc616f@smtp.mailgun.org:587?verify_peer=0
###< symfony/mailgun-mailer ###
```
But nothing, the port is always 465 but i have to use the 587 as given in my configuration(given by mailgun at the subscription). I think i way to resolve it could be modify directly the `SocketStream->initialize()` function but it is not the best way.
Is there a way to set the port in our own files ? Without editing composer files

### Example

We can have a think like that?
```yaml
// config/packages/mailer.yaml
framework:
    mailer:
        port: 587 // or whatever
```

**Comment by norkunas** [comment]
Use:
```
MAILER_DSN=mailgun+smtp://postmaster%40sandbox5fa7d0740602***b.mailgun.org:631***18e06deb-5bfc616f@default
```

**Comment by xabbuh** [comment]
According to https://www.mailgun.com/blog/email/which-smtp-port-understanding-ports-25-465-587/#chapter-3 Mailgun indeed recommends using port 587 instead of 465. Right now that's not configurable.

@fabpot Do you remember why you chose port 465 back then when writing the first version of the Mailer component?

**Comment by Asmitta-01** [comment]
> According to https://www.mailgun.com/blog/email/which-smtp-port-understanding-ports-25-465-587/#chapter-3 Mailgun indeed recommends using port 587 instead of 465. Right now that's not configurable.

So i can't use Mailgun with Symfony/Mailer ? or there's an alternative please

**Comment by fabpot** [comment]
I'm using the Mailgun provider in many projects and it works fine for me. Are you using the provider or an SMTP transport directly?

**Comment by Asmitta-01** [comment]
The provider i think. Here is a discussion with my code: https://github.com/symfony/symfony/discussions/46966#discussion-4224124

**Comment by fabpot** [comment]
Closing here as there is nothing to fix in Symfony. I see you have a 401, so I suppose that maybe the credentials are not the correct one?

**Comment by Asmitta-01** [comment]
> Closing here as there is nothing to fix in Symfony. I see you have a 401, so I suppose that maybe the credentials are not the correct one?

As said in the [discussion](https://github.com/symfony/symfony/discussions/46966#discussioncomment-3176230) i was getting the error with dsn = mailgun but with mailgun+smtp i am getting the "Connection could not be established..."

**Comment by dmaicher** [comment]
@Asmitta-01 port 465 is still supported by mailgun. They recommend using 587 but 465 does also work.

This error `error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed` seems somehow related to your host and the ssl handshake.

You can try using the default `smtp` transport (DSN `smtp://...`) without any mailgun specific config. Then you can try port 587 but my guess is that this will also fail with the same error.

**Comment by Asmitta-01** [comment]
Mailgun gave me this informations: 
![image](https://user-images.githubusercontent.com/69441849/179975552-ba24c01f-21cf-401b-b2cd-0fa8a95d2406.png)
In my .env file i write `MAILER_DSN=mailgun+smtp://MAILER_SMTP_LOGIN:MAILER_SMTP_PASSWORD@default?region=us` but same error even if i replace `default` by the value of `MAILER_SMTP_SERVER:MAILER_SMTP_PORT` nothing. So where or how should i use these vars to stop getting this error ? please
> You can try using the default smtp transport (DSN smtp://...) without any mailgun specific config. Then you can try port 587 but my guess is that this will also fail with the same error.

I will try but i can't change the port, it is always 465

**Comment by Asmitta-01** [comment]
> I'm using the Mailgun provider in many projects and it works fine for me. Are you using the provider or an SMTP transport directly?

Can i have an example please, since it could be a problem with my code i want to see a good one

**Comment by fabpot** [comment]
I don't have any "code"; I'm just configuring the DSN, everything else just works out of the box.

**Comment by Asmitta-01** [comment]
I changed my mailer.yaml file:
```yaml
framework:
    mailer:
        # dsn: '%env(MAILER_DSN)%'
        dsn: 'smtp://%env(MAILGUN_SMTP_LOGIN)%:%env(MAILGUN_SMTP_PASSWORD)%@%env(MAILGUN_SMTP_SERVER)%:%env(MAILGUN_SMTP_PORT)%?verify_peer=0&region=us'
        envelope:
            sender: '%env(MAILGUN_SMTP_LOGIN)%'
        headers:
            From: '%env(APP_NAME)% <%env(MAILGUN_SMTP_LOGIN)%>'
```
I don't know what "really" changed but it works know, my mails are sucessfully sent

**Comment by derrabus** [comment]
Okay, but the `verify_peer=0` part should scare you because it makes you vulnerable to MITM attacks. The fact that you need it tells me that something's odd with your SSL setup. That's also what @dmaicher has already told you.
