### ISSUE TITLE
Access ManyToOne recursivly in form

### ISSUE THREAD

**Issue by FlorentMedoucine** [symfony/symfony#47006]
### Description

The form builder should accept child like 'client.user.gender' where client is a ManyToOne relationship of appointment, user is a ManyToOne relationship of Client, and gender is an attribute of User.

It is a big feature, but not impossible: loop over the splitting 'client.user.gender' and manage to populate data from database with it, and manage to update data in database from the form.
The '.' is not a valid charactere actually and throw an exception, which mean there would be no regression from old version.

### Example

The form builder should accept child like 'client.user.gender' where client is a ManyToOne relationship of appointment, user is a ManyToOne relationship of Client, and gender is an attribute of User.

```
$builder->add(
                'client.user.gender',
                ChoiceType::class,
                [
                    'mapped' => false,
                    'choices' => [
                        'Male' => 0,
                        'Female' => 1,
                    ]
                ]
            );
```

**Comment by dbrumann** [comment]
I might be wrong, but isn't this already possible with the `property_path` option?

**Comment by stof** [comment]
The *name* of a Form does not allow `.` due to how it is used later (the name is used as part of the Twig block name for customizations of the rendering for instance, where dots are forbidden). But your use case is indeed what the `property_path` option is for.

**Comment by xabbuh** [comment]
closing as explained
