### ISSUE TITLE
[RFC] EventSubscriber attribute

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#47015]
## RFC - Feature Request - EventSubscriber attribute

Opening this issue to gather feedbacks

Adding a new attribute AsEventSubscriber (mimic of [AsCommand](https://github.com/symfony/console/blob/6.1/Attribute/AsCommand.php)) for configuring [EventSubscriber](https://symfony.com/doc/current/event_dispatcher.html#creating-an-event-subscriber) classes/methodes

### Example

Before:

```php
final class ProductSyncSubscriber implements EventSubscriberInterface
{
    public function __construct(private readonly Manager $manager) {}

    public static function getSubscribedEvents(): array
    {
        return [
            ProductUpdatedEvent::class => 'onProductUpdated',
        ];
    }

    public function onProductUpdated(ProductUpdatedEvent $productUpdatedEvent): void
    {
        $this->manager->sync($productUpdatedEvent->getProductId());
    }
}
```

After:

```php
final class ProductSyncSubscriber
{
    public function __construct(private readonly Manager $manager) {}
    
    #[AsEventSubscriber(event: ProductUpdatedEvent, priority: 11)]
    public function onProductUpdated(ProductUpdatedEvent $productUpdatedEvent): void
    {
        $this->manager->sync($productUpdatedEvent->getProductId());
    }
}
```

---

- Then either implement new empty interface or extends empty class to autoconfigure
- Or register like [controller as service](https://symfony.com/doc/current/controller/service.html)

**Comment by stof** [comment]
Well, your use case is defining an event listener, not an event subscriber (by the definitions of the component), and we already have `AsEventListener` doing exactly what you areasking

**Comment by 94noni** [comment]
@stof great, I did not find any doc that is why I've created this, 

https://github.com/symfony/symfony-docs/search?q=AsEventListener
https://github.com/symfony/symfony-docs/search?q=AsCommand

may I ask you a link to PR to check that? thank you :) 

edit: found https://github.com/symfony/symfony/commit/4f1318963a961a164dfce38e8ba726e64c2823aa will see if I can provide doc for that
