### ISSUE TITLE
BinaryFileResponse fails on Azure when running under Nginx on Linux (but works correctly on Windows/IIS)

### ISSUE THREAD

**Issue by aokrasavin** [symfony/symfony#47024]
### Symfony version(s) affected

6.0.0

### Description

A fairly simple controller which picks form input, chooses image from the disk and then returns it to webbrowser. The code works absolutely perfectly on local development instance of Laravel (Windows 10) or Azure Windows-based PHP service, but corrupts data when deployed on Azure PHP App Service  on Linux (under nginx).

1. All headers are delivered correctly with code 200
2. The binary payload for actual image has first 117 bytes stripped out. Eg after the headers, the binary data starts at byte 118, where byte 0 should have been. The rest of the bytes arrive correctly and at the end there are 117 empty bytes (filled with 0x00), so the total size is correct.
3. The issue exists for any files (not just images), for different types of images, for different security (eg HTTP or HTTPS)
6. The amount of bytes missing at start seems to be always the same and unrelated to image content (eg no magic byte sequence)

### How to reproduce

- Laravel Version: 9.10.1
- PHP Version: 8.0.17 (cli) (built: Mar 25 2022 18:59:25) ( NTS )

$img = .... <get data object describing image>

        $response = response()->file(Storage::disk('public')->path($img->filename));
        $response->headers->set('Content-Type', $img->mime);
        $response->headers->set("Cache-Control", "max-age=86400");
        return $response;

### Possible Solution

The following fix works for me, but I do not fully understand the reason for the problem or possible implications, so would prefer someone with better in-depth knowledge to review prior to submitting pull request

namespace Symfony\Component\HttpFoundation;
......
class BinaryFileResponse extends Response
.....
    public function sendContent(): static
{
......
   stream_copy_to_stream($file, $out, $read);
......
}

to fix, I implemented the following - eg PHP native function stream_copy_to_stream is replaced with a custom function, which does (as far as I could tell) the same thing.

  function pipe_streams($in, $out)
    {
        $size = 0;
        while (!feof($in)) $size += fwrite($out,fread($in,8192));
        return $size;
    }

    public function sendContent(): static
{
......
   $this->pipe_streams($file, $out);
......
}

### Additional Context

I attached two versions of the same image returned by the SAME code running under Windows IIS (correct) and Linux (nginx) (corrupted
![172258214-12490c51-6769-43b7-a2ae-ca0b507bea2b](https://user-images.githubusercontent.com/54442217/180430982-34a03ac0-6f5b-472c-b35c-eeebb80bb620.png)
<img width="80" alt="172258194-9c888fb4-6543-4648-b097-6ceb5fce4fa8" src="https://user-images.githubusercontent.com/54442217/180430984-005f98f4-3bfc-47da-a540-9e15b05d8091.png">
)

**Comment by michaelLoeffelmann** [comment]
i can confirm this behavior. i have exactly the same issue.

**Comment by MatTheCat** [comment]
The code does not look like Symfony :thinking: 

Anyways did you check if the request to the image includes a `Range` header?
