### ISSUE TITLE
[CurlHttpClient] Syntax error in constructor

### ISSUE THREAD

**Issue by Wande-cole** [symfony/symfony#47042]
### Symfony version(s) affected

6.2

### Description

I use the [Mailgun PHP library](https://github.com/mailgun/mailgun-php) which in turn depends on symfony.
I kept getting `ParseError
syntax error, unexpected token ")"` exception. Digging through the stack trace, I bumped into symfony and the syntax error here:

https://github.com/symfony/symfony/blob/9b6dba14b73a5fefda2a9ab1335aef6fb38a00ed/src/Symfony/Component/HttpClient/CurlHttpClient.php#L68

![syntax error image](https://user-images.githubusercontent.com/32799119/180629672-3e7592ad-3a4d-415d-b765-def07bca6de4.png)

### How to reproduce

I did not use symfony directly, so reproducing my issue will require working with the [Mailgun php library](https://github.com/mailgun/mailgun-php) to send an email.
Something like this:
```
public function sendTestMail()
{
    $domain = config('mail.mailers.mailgun.domain');
    $host = config('mail.mailers.mailgun.host');
    $key = config('mail.mailers.mailgun.secret');
    $mgClient = Mailgun::create($key, $host);
    $params = array(
        'from'    => 'sample@sample.com',
        'to'      => 'example@example.com',
        'subject' => 'Hello',
        'text'    => 'Testing some Mailgun awesomness!'
    );
    return $mgClient->messages()->send($domain, $params);
}
```

### Possible Solution

I assume, what the author of the method is trying to achieve is to use the [PHP spread operator](https://wiki.php.net/rfc/spread_operator_for_array) which would require the variable after the operator.
Anyways, I changed it locally, and that fixed my issue.
```
$this->defaultOptions['buffer'] ??= self::shouldBuffer(...$defaultOptions);
```

**Comment by derrabus** [comment]
The syntax is perfectly fine on PHP 8.1. Please downgrade HttpClient to 6.0 if you need to run it on PHP 8.0.

**Comment by lamtd** [comment]
Thanks [derrabus]
