### ISSUE TITLE
zsh autocompletion

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#47047]
### Description

while playing arround with the latest composer 2.4 RC1 I tried setting up the bash completion in zsh.

turns out the completion script does not work on zsh (yet?):
see https://github.com/composer/composer/issues/10966

maybe there is something we can do about that: https://docs.haskellstack.org/en/stable/shell_autocompletion/#for-zsh-users

btw: I am a zsh newbee myself and use it just for 2 days. maybe I am completly wrong.

### Example

see https://github.com/composer/composer/issues/10966

**Comment by HypeMC** [comment]
Zsh support was only added [a few days ago](https://github.com/symfony/symfony/pull/47018), it'll be released with Symfony 6.2.

**Comment by staabm** [comment]
Perfect, will give it a try - Thanks
