### ISSUE TITLE
Wrong conversion to snake case from upper snake case

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#47054]
### Symfony version(s) affected

6.1.2

### Description

Symfony String converts `X_Y` into `xy` while I expect it to do `X_Y`. `X_Y` is in upper-snake case, the underscore should not be thrown away.

### How to reproduce

```php
\Symfony\Component\String\u('X_Y')->snake()
```

**Comment by derrabus** [comment]
Thank you. Can you work on a PR?

**Comment by RePrete** [comment]
I think I got the issue, in `AbstractUnicodeString::snake` the first thing done is 
```php
$str = $this->camel()->title();
```

Inside `AbstractUnicodeString::camel` there is a replace of all the non-letter or non-digit chars with a space (inner `preg_replace`) and then replace the space with empty string.
So this is why the underscore is gone.

I am trying to understand if the camel call is correct in this case.

**Comment by RePrete** [comment]
After some other investigations, it looks like it's an extreme edge case.
Currently, it's happening only with strings ending with an underscore followed by all (one or more) capital letters.
Basically:
```
A_A  => aa    //wrong
A_Aa => a_aa  //correct
A_AA => aaa   //wrong
```

To be honest I don't know how and if it's worth to change the implementation.

**Comment by simPod** [comment]
No, it's a bug. snakecase should convert all strings to snakecase not just some.
