### ISSUE TITLE
Request::create can trigger deprecated array conversion in 8.1 with bad values

### ISSUE THREAD

**Issue by neclimdul** [symfony/symfony#47084]
### Symfony version(s) affected

<=6.2

### Description

If you provide a bad value to Request::create, its possible parse_url will fail to parse it settings $components to false. Later code doesn't handle the false condition which "works" because the last bit assigns a value to the variable converting it to an array. In PHP 8.1+ however this conversion behavior is deprecated.

### How to reproduce

Request::create('/foo:123');

Outputs something like:
```
Deprecated function: Automatic conversion of false to array is deprecated in Symfony\Component\HttpFoundation\Request::create() (line 372 of /app/vendor/symfony/http-foundation/Request.php).
Symfony\Component\HttpFoundation\Request::create('/foo:123') ....
```

### Possible Solution

The url isn't valid so it would probably be good to provide developer feedback but throwing an exception would be pretty disruptive. 

Seems like the best approach might be:
1) Explicitly handle the false condition preserving the current behavior. Include deprecation.
2) Throw a InvalidArgument exception or similar in some future version.

**Comment by derrabus** [comment]
Would you like to work on a PR?

**Comment by neclimdul** [comment]
If the suggested solution sounds good I think I can make that happen.

**Comment by xabbuh** [comment]
The suggested solution sounds good to me. The first step without the deprecation should be done on the `4.4` branch.

**Comment by hkirsman** [comment]
+1

**Comment by cherouvim** [comment]
> The url isn't valid so it would probably be good to provide developer feedback

A URL containing colons is perfectly valid.

**Comment by neclimdul** [comment]
@cherouvim you're sort of correct. depending on the location, a colon can be valid in a URL(technically a URI per documentation but the distinction isn't important here). 

However, the provided example is _not_ a valid URI. A URI is formatted such that everything before the first colon is the scheme. Schemes can be any combination of letter handful of special characters but `/` is not a valid schema character so the parsing fails.  Since `'/foo:123'` has an invalid character in the scheme component of the URL PHP refuses to parse it. 

The confusion mostly around this mostly comes from the fact that parse_url is actually incredibly permissive and treats `/path` as a valid url even if it technically isn't, only populating the path component. This is a feature of the method and one often used in applications but it is also a weird one that can lead to problems like this if your path is say the request path and so also user input.

**Comment by cherouvim** [comment]
I came here through Drupal 9. A fresh Drupal 9 installation throws an error when visiting https://localhost/a:1/b
```
Deprecated function: Automatic conversion of false to array is deprecated in Symfony\Component\HttpFoundation\Request::create() (line 372 of /home/me/project/vendor/symfony/http-foundation/Request.php).
Symfony\Component\HttpFoundation\Request::create('/a:1') (Line: 212)
Drupal\system\PathBasedBreadcrumbBuilder->getRequestForPath('/a:1', Array) (Line: 171)
Drupal\system\PathBasedBreadcrumbBuilder->build(Object) (Line: 83)
Drupal\Core\Breadcrumb\BreadcrumbManager->build(Object) (Line: 72)
...
```

I understand though that this may not be an issue of Symfony but rather how Drupal uses Symfony.

**Comment by neclimdul** [comment]
This is definitely a bug somewhere in Drupal. A bug in one of Drupal's modules actually lead me here so that tracks. I reached out in the Drupal slack and we can maybe figure the root of your problem.
