### ISSUE TITLE
[Serializer] Unexpected normalization with custom Encoder happens when APP_DEBUG=1

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#47085]
### Symfony version(s) affected

6.1.2

### Description

If custom encoder is used, rules when normalization is hit are different apparently. We expect no normalization happens in either environment (because our encoder doesn't need normalization).

### How to reproduce

Have this encoder
```php
final class PhpEncoder implements EncoderInterface, DecoderInterface, NormalizationAwareInterface
{
    public function encode(mixed $data, string $format, array $context = []): string
    {
        return serialize($data);
    }

    public function decode(string $data, string $format, array $context = []): mixed
    {
        return unserialize($data);
    }

    public function supportsEncoding(string $format, array $context = []): bool
    {
        return true;
    }

    public function supportsDecoding(string $format, array $context = []): bool
    {
        return true;
    }
}
```

then try to serialize object. In APP_ENV=prod we get serialized object as expected (starting with `O:`)
`O:56:"`. In APP_ENV=dev we get serialized array (unexpected) (starting with `a:1:{s:`)

### Possible Solution

Adjust condition at https://github.com/symfony/symfony/blob/e89f0ff762bca887ced642d737a0994999c8483f/src/Symfony/Component/Serializer/Debug/TraceableEncoder.php#L114-L114

### Additional Context

We were struggling to understand why output of serialization was different between APP_ENV=dev and APP_ENV=prod. Looks like issue is that in dev environment, TraceableEncoder is used. TraceableEncoder has this defined https://github.com/symfony/symfony/blob/e89f0ff762bca887ced642d737a0994999c8483f/src/Symfony/Component/Serializer/Debug/TraceableEncoder.php#L114-L114

In APP_ENV=prod TraceableEncoder is not used, so this condition is triggered instead https://github.com/symfony/symfony/blob/e89f0ff762bca887ced642d737a0994999c8483f/src/Symfony/Component/Serializer/Encoder/ChainEncoder.php#L77-L77

**Comment by chalasr** [comment]
Thanks. Would you be ok to submit a PR?
