### ISSUE TITLE
3 forks() just to get column widths and row height

### ISSUE THREAD

**Issue by wdoekes** [symfony/symfony#47109]
### Description

In this code:
https://github.com/symfony/symfony/blob/6c8c93d542103656a37b8cda1d293c29d083ed51/src/Symfony/Component/Console/Terminal.php#L174-L180

The Terminal class calls `stty -a | grep columns` which results in:
- `fork()` + `execve()` of `sh`
- `fork()` + `execve()` of `stty`
- `fork()` + `execve()` of `grep`

In reality we're only interested in 1 `ioctl(..., TIOCGWINSZ, ...)` call:
```
$ strace -e ioctl stty -a
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=73, ws_col=372, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=73, ws_col=372, ws_xpixel=0, ws_ypixel=0}) = 0
```
But I understand that calling `ioctl()` from php is hard, so we won't go there.

I would suggest going back to 1 `fork() + execve()` though. The following should be sufficient:
```diff
--- Terminal.php.orig	2022-07-29 11:32:25.427119251 +0200
+++ Terminal.php	2022-07-29 11:32:29.335098803 +0200
@@ -143,10 +143,18 @@ class Terminal
      */
     private static function getSttyColumns(): ?string
     {
-        return self::readFromProcess('stty -a | grep columns');
+        // from PHP 7.4+ we can pass an array to proc_popen() and bypass
+        // the excess /bin/sh call:
+        if (array(PHP_MAJOR_VERSION, PHP_MINOR_VERSION) >= array(7, 4)) {
+            $output = self::readFromProcess(array('stty', '-a'));
+        } else {
+            $output = self::readFromProcess('stty -a');
+        }
+        // simplify the extraction of rows/columns later on
+        return str_replace("\n", " ", $output);
     }
 
-    private static function readFromProcess(string $command): ?string
+    private static function readFromProcess($command): ?string
     {
         if (!\function_exists('proc_open')) {
             return null;
```

### Example

Why do I care?

(1) When clean code doesn't conflict with performance, I prefer performance.

(2) When monitoring what applications do -- for instance with [Falco](https://github.com/falcosecurity/falco) -- I don't want to have to create lots of exclude rules: allowing `stty` makes sense, but allowing `sh -c` calls makes less sense.

Does it work?

```console
$ php -v
PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
```
```console
$ tail -n3 Terminal.php
$t = new Terminal();
print $t->getWidth(). "\n";
print $t->getHeight(). "\n";
```
```console
$ php Terminal.php.orig 
185
73
```
```console
$ php Terminal.php
185
73
```

Cheers, :beers: 
Walter Doekes
OSSO B.V.

**Comment by fabpot** [comment]
Do you want to work on a PR? You should target version 6.2, where we support PHP 8.1+.

**Comment by wdoekes** [comment]
I can file a PR if you like.

8.1+ only then?

Then I'll do `string|array` and remove the PHP_VERSION check.

**Comment by fabpot** [comment]
Yes, a PR on 6.2 can only support PHP 8.1+.
