### ISSUE TITLE
[RFC][Forms] Make getParent static.

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#47124]
### Description

tl;dr this will reduce possible bugs by discourage following code:

```
public function getParent()
{
    return $this->tokenStorage->getUser() instanceof User ? ChoiceType::class : TextType::class;
}
```

because the result of this method is cached, so in long-running process (like roadrunner, reactphp, amphp) - the first user that hits that form - will cache the result of `getParent` and all other forms will use that cached results - which will result in bugs.

```
$form = $this->createForm(Form::class);

// simulate login.
$user = $em->find(User::class, 1);
$tokenStorage->setToken(new UsernamePasswordToken($user, 'main'));

$form2 = $this->createForm(Form::class); <- this form still have TextType parent, not ChoiceType.
```
### Example

```
public static function getParent()
{
    return $this->tokenStorage->getUser() instanceof User ? ChoiceType::class : TextType::class;
}
```

because its static it cannot access object props - so technically this code is not possible anymore.

**Comment by derrabus** [comment]
How would the upgrade path look like? You cannot change the `static` flag when overriding a method.

**Comment by Warxcell** [comment]
No idea, really. Can we do it at once? E.g. version 7 it will just become static and that's it ? Till then - we will throw deprecation errors that it will become static in SF 7.

Something like `getUsername` vs `getUserIdentifier` - you cannot really migrate (because you cannot remove `getUsername` its required by Interface) till next version.

**Comment by derrabus** [comment]
> version 7 it will just become static and that's it ?

That means you cannot write a form type that works with Symfony 6 and 7.

> Till then - we will throw deprecation errors that it will become static in SF 7.

Even worse: There would be nothing I could do to get rid of the deprecation. It would be impossible to run a deprecation-free app on Symfony 6.

**Comment by Warxcell** [comment]
Then we could remove cache here: https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Form/FormRegistry.php#L84
and always resolve without cache. That will make sense when having `getParent` non-static.

I'm open to other ideas. Make `public function static getParentType` and deprecate `public function getParent` ?

**Comment by Warxcell** [comment]
Btw same problem exists in `configureOptions`

If you do:

```
$resolver->setDefaults([
    'start_date' => new DateTime('tomorrow')
]);
````

`start_date` will be cached for all forms.

You should do:
```
$resolver->setDefaults([
    'start_date' => static fn (Options $options): DateTime => new DateTime('tomorrow'),
]);
```

Its not really obviously

**Comment by wouterj** [comment]
Hi! Thanks for creating this issue.

My personal opinion on this is that it is not yet worth all the hassle (this is a complex BC path to maintain and one that impacts almost every Symfony application and bundle). The architecture of Symfony has not been designed with servers using long-running processes in mind. #41520 describes a lot more shortcomings in Symfony's architecture for something like this.
At the moment, this means that you can use Symfony with roadrunner/reactphp/amphp, but you need to be careful about what you do (e.g. don't conditionally change the parent type).

I feel like it's not worth changing anything about this, unless we start a big initiative with a complete roadmap. It's quite hard to judge the benefit of changes like this if the bigger picture is missing.
