### ISSUE TITLE
You have requested a non-existent service "chatter"

### ISSUE THREAD

**Issue by maxtor3569** [symfony/symfony#47122]
### Symfony version(s) affected

5.4.10

### Description

When injecting (autowiring) Chatter Service in a controller method 
You have requested a non-existent service "chatter"

### How to reproduce

Install Notify component, create simple controller and try to inject ChatterInterface in a controller method

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by maxtor3569** [comment]
> Can you create a small example application that allows to reproduce your issue?

`<?php

namespace App\Controller;


use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Notifier\ChatterInterface;


class BasicController extends AbstractController
{


	#[Route('/test')]
	public function create(ChatterInterface  $chatter): Response
	{

		return new Response();
	}



}
`

**Comment by xabbuh** [comment]
This is not a full application. Please create a GitHub repository containing a fully runnable application that exposes the reported issue.

**Comment by maxtor3569** [comment]
> This is not a full application. Please create a GitHub repository containing a fully runnable application that exposes the reported issue.
Here is the full application. 
https://github.com/maxtor3569/bug-chatter

**Comment by xabbuh** [comment]
The error message is indeed misleading (I submitted #47129 for that), but overall your issue is that you did not configure any transports (read https://symfony.com/doc/current/notifier.html#chat-channel for the supported chat channels).

**Comment by maxtor3569** [comment]
Thanks you @xabbuh
