### ISSUE TITLE
[HttpFoundation] PHP Warning:  `SessionHandler::read()`: Session ID is too long or contains illegal characters.

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#47126]
### Symfony version(s) affected

6.1.3

### Description

Hi, the error is similar to https://github.com/symfony/symfony/issues/46777, except that now the issue comes from another reason. Or maybe I misunderstood how Symfony sessions work...

Look at this condition:

https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L169

When i'm using [`NativeSessionStorage`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php) class, `$this->saveHandler->getSaveHandlerName()` returns `user` but should return `files`. Therefore, the whole condition is never `true` and the following warning persists:

```log
[25-Jun-2022 20:54:15 UTC] PHP Warning:  SessionHandler::read(): Session ID is too long or contains illegal characters. Only the A-Z, a-z, 0-9, &quot;-&quot;, and &quot;,&quot; characters are allowed in C:\app\vendor\symfony\http-foundation\Session\Storage\Handler\StrictSessionHandler.php on line 45
```

### How to reproduce

```php
use Symfony\Component\HttpFoundation\Session\Session;

require __DIR__ . '/vendor/autoload.php';

$_COOKIE[session_name()] = str_repeat('A', 230) . '.:%*$!@`'; // Bad session ID provided by a malicious user.
$session = new Session(); // Using `Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage` storage class.
$session->start();
```

### Possible Solution

Below, the code defines `$this->saveHandlerName` to `\ini_get('session.save_handler')` when `$handler instanceof \SessionHandler`.
https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php#L24-L25

But here, the code instantiates `new StrictSessionHandler(new \SessionHandler())` that is not an instance of [`\SessionHandler`](https://www.php.net/manual/en/class.sessionhandler.php).
https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L422-L424

So, I'm really not sure, but a possible solution could be as below:
```diff
- $this->wrapper = $handler instanceof \SessionHandler; 
+ $this->wrapper = $handler instanceof \SessionHandlerInterface; 
```

Because both [`StrictSessionHandler`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php) and [`\SessionHandler`](https://www.php.net/manual/en/class.sessionhandler.php) implements [`\SessionHandlerInterface`](https://www.php.net/manual/en/class.sessionhandlerinterface.php).

**Comment by xabbuh** [comment]
Same as #46993?

**Comment by ghost** [comment]
> Same as #46993?

@xabbuh Yes, that's the same, sorry for duplicate! I think that my solution could work. What do you think about this?

**Comment by xabbuh** [comment]
@BrokenSourceCode I don't know. I think it's best if you open a PR with your idea to gather some feedback. I close here meanwhile as we still have the other issue.

**Comment by ghost** [comment]
@xabbuh The solution I suggested in my previous comments is meaningless, I thought wrong. I suggest another one here: https://github.com/symfony/symfony/pull/47130
