### ISSUE TITLE
Mailer is encoding char = as =3D

### ISSUE THREAD

**Issue by bernardo-campos** [symfony/symfony#47133]
### Symfony version(s) affected

6.0.8

### Description

When sending an email, the result contains the chars **=3D** where it should only appear **=**. It is a problem when sending HTML emails since its URLs and images are not rendered properly

### How to reproduce

1. clone repository (or install a fresh laravel 9 app)
2. php composer.phar install
3. copy .env and set MAIL_MAILER=log
4. php artisan key:generate
5. Open php artisan tinker and paste

`Mail::raw('Hello=hola', function ($message) { $message->to('a@example.com')->subject('english=spanish');});`

At laravel.log file should see

> [2022-07-29 23:33:49] local.DEBUG: Laravel [hello@example.com](mailto:hello@example.com)
> To: [a@example.com](mailto:a@example.com)
> Subject: english=spanish
> MIME-Version: 1.0
> Date: Fri, 29 Jul 2022 23:33:49 -0300
> Message-ID: [9641d97296a4ea13e386dae4de0a9431@example.com](mailto:9641d97296a4ea13e386dae4de0a9431@example.com)
> Content-Type: text/plain; charset=utf-8
> Content-Transfer-Encoding: quoted-printable
> 
> Hello=3Dhola

One repo example:

https://github.com/bernardo-campos/testing-laravel-packages

**Comment by xabbuh** [comment]
This format is called quoted printable encoding (as indicated by the `Content-Transfer-Encoding: quoted-printable` header). Did you experience any other issues besides how the data is present in the logs (e.g. are some clients not able to display the e-mail properly)?

**Comment by bernardo-campos** [comment]
Image with base64 was not rendered, but was a email client restriction. Sorry for the inconvenience, it was my bad
