### ISSUE TITLE
[FORM] `SubmitType` label is not translatable

### ISSUE THREAD

**Issue by RSickenberg** [symfony/symfony#47178]
### Symfony version(s) affected

6.0.11

### Description

As I'm using a lot of the form types a bit everywhere, I do not always inject the `TranslatorInterface` to my form since every labels or placeholder, helpers, and whatsoever doesn't need it.

If I put my translation key, it's automatically translated except for the `SubmitType`.

### How to reproduce

Create a form with some `TextType` and a submit type button.

All the labels are translated into messages.yml and the keys are given into the form array label.

The TextType label is translated.
The submitType button is not.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by RSickenberg** [comment]
@xabbuh Sure. https://github.com/RSickenberg/bug_47178

Go to `/bug` to constat the issue, it's linked to the fact I'm also using a form template.

**Comment by xabbuh** [comment]
Your form theme overrides the `button_widget` block and does not translate the label which is done in the form themes provided by Symfony: https://github.com/symfony/symfony/blob/f9d5e24e4b4c9aac20b3081d90ccf61e7549ddef/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L224-L250

**Comment by RSickenberg** [comment]
omg, thank you. 🤦🏻‍♂️

Sorry for the disturbance.
