### ISSUE TITLE
[RFC] Automatic Stopwatch profiling via an attribute

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#47184]
### Description

Hello,

I am thinking/asking if we can automatically profile (in `dev` env) some code execution via an attribute?
Reference [this documentation](https://symfony.com/doc/current/performance.html#profiling-with-symfony-stopwatch)

The main idea is to not have to alter business code "just to profile"

### Example

Given the code on documentation link, here could be a replacement:

```php
use Symfony\Component\Stopwatch\Attribute\AsStopwatchProfile;

class DataExporter
{
    #[AsStopwatchProfile]
    public function export()
    {
        // ...do things to export data...
    }
}
```

The `export()` code execution would be automatically measured with stopwatch
and named for example `DataExporter::export` and displayed in the profiler

**Comment by lyrixx** [comment]
I like it! How would do achieve it? 
Search for all services that have this attribute, and add a decorator on top of it?

**Comment by 94noni** [comment]
@lyrixx hey, thx for commenting

> How would do achieve it?

The idea of a traceable decorator can be used indeed.
As we are talking of dev env, the container while being rebuilt can check method having such attribute, and automatically create a traceable decorator wrapping the method tagged with the stopwatch start/stop before/after it?

Can it be feasible? I am just writing idea here, I really do not know if it is even doable

**Comment by lyrixx** [comment]
yes, this is what I had in mind. I guess It's doable.

**Comment by wouterj** [comment]
I don't think we should want this. If you want features like this, you should use an APM instead of the stopwatch imho.

As far as I know, we do not accept features that check configuration (i.e. attributes) of classes in an opt-out way. We only check attributes in opt-in ways (e.g. `#[AsEventListener]` only works with `autoconfigure: true` IIRC).
Besides that, creating a "decorator" for any arbitrary method seems complex. Creating proxy objects in PHP isn't the easiest thing, as proofed by ProxyManager.

**Comment by fabpot** [comment]
I agree with Wouter. The StopWatch component is "just" a timer, nothing more. A "real" profiler like Blackfire seems way more appropriate.
Closing as I don't think we want to add this to core.

**Comment by 94noni** [comment]
@wouterj @fabpot I got your point for both

Let me just write that there is a gap between apm/full profiling and the ease of « just profiling faster »

injecting stopwatch by modifying business internal code / or needing to defined a decorator to wrap it ce be done differently
In order to have such data automatically inside the webprofiler performance timelaps panel, i wanted to rfc here

Anyway, thanks for your time and responses

**Comment by fabpot** [comment]
I think that my main concern is not giving some wrong expectations: using StopWatch is far from being close to what one calls "profiling".

**Comment by 94noni** [comment]
Indeed the goal here was just to make it faster to display such time/memory usage of temporary defined part of code into the web profiler performance panel
Nothing more :)
