### ISSUE TITLE
KerneltestCase: Discrepancy between `self::$kernel` and `static::$kernel`

### ISSUE THREAD

**Issue by flack** [symfony/symfony#47186]
### Symfony version(s) affected

4.4.39

### Description

I just updated an ancient Symfony 4.4 app and noticed that in release 4.4.39 out unit tests break due to https://github.com/symfony/framework-bundle/commit/cd5273725d4dc32190566051df536e68ceb60be9

After debugging I noticed that this happens because `bootKernel` assigns the new kernel to `self::$kernel`, but a few lines down, the container is read from `static::$kernel`, which in my case is a different class (i.e. my test class extending `KernelTestcase`):

https://github.com/symfony/framework-bundle/blob/3cbca8f6b93681102cab0fe0e3c23d16e4d0ded3/Test/KernelTestCase.php#L80-L83

### How to reproduce
```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MyTest extends WebTestCase
{
    protected static $kernel;

    public function testUserlist()
    {
        static::createClient();
   }
}
```

### Possible Solution

change all occurences to either `self` or `static`

**Comment by xabbuh** [comment]
see #47195

**Comment by nicolas-grekas** [comment]
Note that redeclaring `protected static $kernel;` is deprecated. We did so in order to be able to add types to properties in 7.0.
You should also remove this duplicate declaration.

**Comment by flack** [comment]
@nicolas-grekas thanks, noted! TBH I can't even remember why we had the redeclared `$kernel` property, probably it was just for typehinting purposes, or maybe it was required in some older Sf version (the app started out with 2.0). But yes, it's redundant now and I'll remove it in the future
