### ISSUE TITLE
[Messenger] #[AsMessageHandler] with union type doesn't compile

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#47206]
### Symfony version(s) affected

6.0

### Description

Having a `#[AsMessageHandler]` on a method (except `__invoke`) taking a union will prevent compilation.

### How to reproduce

```
#[AsMessageHandler]
public function method(A|B $message): void {}
```

### Possible Solution

In the `MessengerPass::guessHandledClasses()` method, every path except the one dealing with union types return if method is known `array<class-string, method>` else `array<int, class-string>`. Code path dealing with unions does not.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ArchitectNate** [comment]
I've replicated the bug here: https://github.com/ArchitectNate/symfony-47206

I'll start digging into a fix

Status: Needs Work

**Comment by magikid** [comment]
Status: Needs Review

**Comment by ArchitectNate** [comment]
@xabbuh is the example application and subsequent PR sufficient? Thoughts?
