### ISSUE TITLE
[Notifier][Telegram] Add the ability to use `answerCallbackQuery` API method

### ISSUE THREAD

**Issue by BaHeK1994** [symfony/symfony#47213]
### Description

I use inline keyboard in a telegram bot and send messages asynchronously via messenger:consume async, after the user has pressed a key, it is necessary to send another method "answerCallbackQuery" instead of "sendMessage" to hide the loader icon.

https://user-images.githubusercontent.com/18642618/183297334-2c5b88bd-6c5f-4dc3-ab55-ddd3a773a218.mp4

**Comment by alexsoft** [comment]
I could think of following API. Provided that notification that is used to answer the callback implements `ChatNotificationInterface`, inside `asChatMessage` method we would provide options in following way:
```
$options = new TelegramOptions();
$options->answerCallbackQuery('123456', $showAlert = true, $cacheTime = 1);

$chatMessage->options($options);
```
And answerCallbackQuery method has following signature:
```
public function answerCallbackQuery(string $callbackQueryId, bool $showAlert = false, int $cacheTime = 0): static
```

This will allow provide additional options for answering callback query use case. Note that I am omitting `url` parameter as that would only work in case of game which does not fit into notifier use case.

What do you think?
