### ISSUE TITLE
[Validator] Issue when using groups with composite constraints

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#47229]
### Symfony version(s) affected

4.4

### Description

First reported by @nesk as a possible doc issue in https://github.com/symfony/symfony-docs/pull/14259 but this could be a code bug, so we're reporting here too.

### How to reproduce

Consider the following code:

```php
class User
{
    /**
     * @var string[]
     *
     * @Assert\All({
     *     @Assert\NotBlank,
     *     @Assert\Sequentially({
     *         @Assert\Type("string"),
     *         @AppAssert\ValidPermission,
     *     }, groups={"permissions"}),
     * }, groups={"permissions"})
     */
    private $permissions = [];
}
```

The `Sequentially` composite constraint doesn't inherit the groups of the `All` composite constraint.

If I try to validate my entity with the `permissions` group, only the `All` and `NotBlank` constraints are applied.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I fail to see how that's actually an issue. Let's close here for now until someone comes up with an example application that allows to reproduce it.
