### ISSUE TITLE
Serializer 6.x: can't distinguish between empty list and empty object

### ISSUE THREAD

**Issue by gronostajo** [symfony/symfony#47220]
### Symfony version(s) affected

6.*

### Description

I have to handle arbitrary JSON-like data in PHP and serialize it to JSON. It's required to preserve the distinction between empty lists and empty objects. With Serializer 5.x I did this by representing lists as `[]` and objects as `new stdClass()`.

Since 6.0 my custom normalizer doesn't work due to [this change](https://github.com/symfony/serializer/commit/7d2f07bffadfae9bef59471515f1165094758e8c#diff-c94a90956271b5071448a6db4cadce1442c5072dbfdc6481130152d09d7fda49R156) which doesn't allow for objects (like `stdClass`) to be returned.

### How to reproduce

Requires `symfony/serializer`.

Works with 5.x, fails with 6.0.\* and 6.1.\* (tested with 6.0.11 and 6.1.3).

```php
<?php

declare(strict_types=1);

require 'vendor/autoload.php';

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Serializer;

class JsonData
{
    public function __construct(
        public readonly mixed $data,
    ) {}
}

class JsonDataNormalizer implements NormalizerInterface
{
    /**
     * @param JsonData $object
     */
    public function normalize(mixed $object, ?string $format = null, array $context = [])
    {
        return $object->data;
    }

    public function supportsNormalization($data, string $format = null): bool
    {
        return $data instanceof JsonData;
    }
}

$serializer = new Serializer(
    normalizers: [new JsonDataNormalizer()],
);

$result = $serializer->normalize(new JsonData([]), 'json');
assert('$result === []');
// this will crash with 6.x due to typing issues:
$result = $serializer->normalize(new JsonData(new \stdClass()), 'json');
assert('$result instanceof \stdClass');
```

Result on v6.*:
```
Fatal error: Uncaught TypeError: Symfony\Component\Serializer\Serializer::normalize(): Return value must be of type ArrayObject|array|string|int|float|bool|null, stdClass returned in /src/vendor/symfony/serializer/Serializer.php:161
Stack trace:
#0 /src/test.php(40): Symfony\Component\Serializer\Serializer->normalize(Object(JsonData), 'json')
#1 {main}
  thrown in /src/vendor/symfony/serializer/Serializer.php on line 161
```

### Possible Solution

Extend the returned union type of `NormalizerInterface::normalize` to include `stdClass`. Same with `Serializer\Serializer::normalize`.

Currently it's `array|string|int|float|bool|\ArrayObject|null`. \
With proposed changes it would be `array|string|int|float|bool|\ArrayObject|\stdClass|null`.

I think this may affect encoders which will now have to support `stdClass` input (this was the case in 5.x at least with the JsonEncoder).

**Comment by derrabus** [comment]
Can you try to have your custom normalizer return `ArrayObject` instead of `stdClass` intstances?

**Comment by gronostajo** [comment]
@derrabus It appears to work as expected, thank you.
