### ISSUE TITLE
Logout response includes two Set-Cookie headers for PHPSESSID

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#47228]
### Symfony version(s) affected

5.4.11, 6.1

### Description

When investigating the headers sent upon logout in our application, I noticed that two Set-Cookie headers are included for `PHPSESSID`, e.g.:
```
PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly; SameSite=lax
PHPSESSID=deleted; expires=Sun, 08 Aug 2021 15:55:14 GMT; Max-Age=0; path=/; httponly; samesite=lax
```

We have our own UserProvider and Authenticator, but as you can see from the example application below this issue seems to be unrelated to that. It arises with `json_login` as well.

### How to reproduce

To reproduce this I created a sample project and added a test that successfully runs through if upon logout two Set-Cookie headers with `PHPSESSID=delete` are sent: https://github.com/GiGaJKlein/symfony_two_cookies_issue

To run the test: `./bin/phpunit tests/TestForBug.php`

Note: You may have to adjust the hashed hardcoded password in `/config/pckages/security.yaml`

**Comment by xabbuh** [comment]
maybe related to #44316

**Comment by MatTheCat** [comment]
I found one is created by https://github.com/symfony/symfony/blob/001cbe71a3132e255a26046a5ff12bddea60f123/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php#L105 ([PHP changes empty cookies value to `deleted`](https://github.com/php/php-src/blob/3a843f953bb2197b8647953271372f8213ac2c54/ext/standard/head.c#L115-L124)) and the other by https://github.com/symfony/symfony/blob/001cbe71a3132e255a26046a5ff12bddea60f123/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L156

@alexander-schranz may know something about this :eyes:

**Comment by alexander-schranz** [comment]
@MatTheCat Interesting. Looks for me like the AbstractSessionHandler is called after the AbstractSessionListener instead of the other way around.

Can you debug on which `Events` they are listening, which priority they have and check which one is called first/second?

**Comment by MatTheCat** [comment]
First one called is `AbstractSessionHandler`’s `setcookie`

1. by `SessionLogoutListener` on `LogoutEvent`
2. by `AbstractSessionListener` on `KernelEvents::RESPONSE` (because of `session_write_close` called by `$session->save()`)

Then   `AbstractSessionListener`’s `$response->headers->clearCookie` is called in the same method.

I don’t think `setcookie` integrates with Symfony’s `Response` so the order should not matter :thinking:

**Comment by alexander-schranz** [comment]
The `setcookie` should not be the problem, that is correct for the http foundation standalone component. But the AbstractSessionListener should it remove it here again from the headers:

https://github.com/symfony/symfony/blob/001cbe71a3132e255a26046a5ff12bddea60f123/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L148

And set manually the clear cookie (required for roadrunner, swoole which run in CLI context and do not support so setcookie).

Could you debug what is happening in the `AbstractSessionListener` `SessionUtils::popSessionCookie` why the setcookie of the `AbstractSessionHandler.php` is not removed there? I'm not yet sure when I have time to have a look at it myself.

**Comment by MatTheCat** [comment]
Okay so we are actually entering https://github.com/symfony/symfony/blob/082090adc1f97b5d1cd098ef6981abd628da6a97/src/Symfony/Component/HttpFoundation/Session/SessionUtils.php#L41-L43 called by `AbstractSessionListener::onKernelResponse`.

`$h` being

> Set-Cookie: PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly; SameSite=lax

and `$sessionCookieWithId` being ` PHPSESSID=7f6a7c8087649aae1aeddb66143cc76f;` in my case.

That means the header is removed by https://github.com/symfony/symfony/blob/082090adc1f97b5d1cd098ef6981abd628da6a97/src/Symfony/Component/HttpFoundation/Session/SessionUtils.php#L52 but then added again by https://github.com/symfony/symfony/blob/082090adc1f97b5d1cd098ef6981abd628da6a97/src/Symfony/Component/HttpFoundation/Session/SessionUtils.php#L54

I hope you’ll be able to do something with this :sweat_smile:

**Comment by X-Coder264** [comment]
@GiGaJKlein @MatTheCat  I've sent in a fix for this -> https://github.com/symfony/symfony/pull/47273

If you could apply this fix locally and confirm that everything works as expected that'd be great.

**Comment by ghost** [comment]
Thank you @X-Coder264. It works as expected, only one header is sent in our application with you fix applied.

**Comment by alexander-schranz** [comment]
@X-Coder264 good work thx for having a look at it 👍
