### ISSUE TITLE
[HttpKernel] Deprecation of using `null` on `trim()` method in LoggerDataCollector

### ISSUE THREAD

**Issue by SVillette** [symfony/symfony#47235]
### Symfony version(s) affected

">= 5.4"

### Description

The bug is a deprecation that is triggered because the usage of a `null` argument to `\trim()` method in `\Symfony\Component\HttpKernel\DataCollector\LoggerDataCollector`. (L147)

This bug appears in dev environment because I added a monolog handler that logs every deprecation in a file.

### How to reproduce

I created a [reproducer](https://github.com/SVillette/SymfonyTrimDeprecationReproducer) that explain step by step how to reproduce this bug and what is the cause.

### Possible Solution

This bug can be fixed in `vendor/symfony/http-kernel/DataCollector/LoggerDataCollector.php:147` by checking if `$log['channel']` is not null before using the `\trim()` method.

**Comment by alamirault** [comment]
Do you want make a PR targeting 5.4 (as 4.4 is not affected)?

**Comment by SVillette** [comment]
Yes of course, I can give it a try !
