### ISSUE TITLE
[Security] Adding a Flash Message still not working in Logout Subscriber

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#47247]
### Symfony version(s) affected

5.4.11

### Description

It looks like the problem described in https://github.com/symfony/symfony/issues/37292 wasn't solved completely in https://github.com/symfony/symfony/pull/37368.

I have a `LogoutSubscriber` that adds a flash message, and this gets lost.

### How to reproduce

LogoutSubscriber:
```php
public static function getSubscribedEvents(): array
{
    return [
        LogoutEvent::class => ['logout', 0],
    ];
}
```
Workaround: Setting the priority to `-1`, solves it, as suggested in https://github.com/symfony/symfony/issues/37292#issuecomment-646992227

### Possible Solution

If this can't be fixed, I'd come up with a PR for https://symfony.com/doc/5.4/security.html#customizing-logout - something like "Due to Symfony internals, when using an event subscriber to add a flash message, you need to set a negative priority, as shown here:..."

**Comment by ThomasLandauer** [comment]
I'm not observing this anymore in 6.1.7, so it looks like it has been fixed already.

**Comment by xabbuh** [comment]
👍 thanks for the feedback
