### ISSUE TITLE
Bug profiler doctrine request

### ISSUE THREAD

**Issue by hayusama** [symfony/symfony#47275]
### Symfony version(s) affected

6.1.3

### Description

Hello,

I have a concern only on this version when I use
{{ render(controller("App\\Controller\\BlogController::menu")) }}
This generates about ten queries in the profiler, yet my method menu does not contain any queries.
This happens to every user of render(controller)) this does not happen on symfony version 3/4/5

### How to reproduce

`public function menu()
    {
      $listMenu = array(
        array('title' => 'Mon blog','texte'=>'Accueil','url'=>$this->generateUrl('homepage',[])),
        array('title' => 'Connexion','texte'=>'Connexion','url'=>$this->generateUrl('app_login',[]), 'user'=>false),
        array('title' => 'Création de compte','texte'=>'Création de compte','url'=>$this->generateUrl('app_register',[]), 'user'=>false),
        array('title' => 'Déconnexion','texte'=>'Déconnexion','url'=>$this->generateUrl('app_logout',[]), 'user'=>true)
      );
      return $this->render("parts/menu.html.twig", array(
        'listMenu' => $listMenu
      ));
    }`

![Sans-titre-2](https://user-images.githubusercontent.com/16785654/184552866-19c9808f-44fe-4c58-a2d3-6c5801a5d40b.jpg)
![Sans-titre-3](https://user-images.githubusercontent.com/16785654/184552902-51ad6749-7129-425a-9e09-27dfdd506687.jpg)
![Sans-titre-4](https://user-images.githubusercontent.com/16785654/184552903-fce20b5e-3a76-4341-8db8-d489352605c0.jpg)

I made a simple example so that you can easily understand the problem

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by hayusama** [comment]
Hi, yes i have create a repo :
https://github.com/hayusama/bugsf6/
for install : https://github.com/hayusama/bugsf6/blob/main/README.md


I don't know if this is intended, however when I used the render(controller) on sf2/3/4/5 I didn't have this problem.
There is normally no interré to check the database during an inclusion.
Maybe there is an option to disable this?
![Sans-titre-1](https://user-images.githubusercontent.com/16785654/184657784-daae783a-c6c3-4dd7-b494-7949f26f1bf5.jpg)

in my project (prod) if I have migrations and I make a render(controller()) I have not 3 requests but more than 10
![Sans-titre-2](https://user-images.githubusercontent.com/16785654/184660476-559532af-c23b-45cf-a838-6abfd4450802.jpg)

**Comment by MatTheCat** [comment]
You probably have the `doctrine_migrations.enable_profiler` configuration to `true`. The documentation does say it adds some overhead: https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#configuration

**Comment by 94noni** [comment]
Indeed it sure is
That s why i’ve opened https://github.com/doctrine/DoctrineMigrationsBundle/pull/471 for it

**Comment by hayusama** [comment]
Oh thank you . this is added automatically but not obvious to change this because the documentation is not necessarily very precise on this subject.
