### ISSUE TITLE
Sending ICal emails (Symfony Mailer)

### ISSUE THREAD

**Issue by cbutton74** [symfony/symfony#47279]
### Description

An extra option like html or text but with ICal, so email invites can be sent from Symfony Mailer based application.

### Example

 $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            ->subject('Time for Symfony Mailer!')
            ->ical($icalcontent)
        $mailer->send($email);

**Comment by fabpot** [comment]
Do we really need that abstraction?
I suppose you would use https://github.com/spatie/calendar-links to generate the files. So, then, that's just about adding the file with the right content type. Maybe that would be a great addition to the docs?

**Comment by cbutton74** [comment]
If I am understanding spatie/calendar-links it just attaches a file or creates a link to a calendar, the email body itself does not become an email invite (accept/decline buttons in outlook should show on the email itself), please correct me if I am wrong. 

If I am wrong, this would be a great help to anyone looking for a way to create invites as information online in general is pretty sparse about it.

**Comment by stof** [comment]
@cbutton74 in this library, you need to use the ics format and attach that file as an attachment. Then the accept/decline buttons are managed by Outlook based on the presence of the attachment, not based on the text body.

Note that there is also https://packagist.org/packages/jsvrcek/ics as another library for that.

**Comment by cbutton74** [comment]
> @cbutton74 in this library, you need to use the ics format and attach that file as an attachment. Then the accept/decline buttons are managed by Outlook based on the presence of the attachment, not based on the text body.
> 
> Note that there is also https://packagist.org/packages/jsvrcek/ics as another library for that.

Unfortunately Outlook doesn't work that way (GMail and other email software does), Outlook requires the message body to be the ics, it doesn't pickup the ics attachment as an invite until the attachment is opened. 

Try sending a message with just an ics file attached. The message will be blank with the attachment, when you open the attachment that's when the accept or decline options appear.

For an outlook to see a message as a invite, its body must have a 'part' with text\calendar and the correctly ical as the body (Outlook is extremely picky with this). This will produce the same invite you would get if you invited someone using the outlook calendar.

**Comment by gisostallenberg** [comment]
Can't you use an inline attachment? Won't it produce a text\calendar part?

**Comment by peterreichenbach** [comment]
till mime 5.4.10 this was possible with an inline attachment (and resulting overall Content-Type: multipart/mixed;).
```
$attachment = new DataPart($iCal, 'event.ics', 'text/calendar', 'quoted-printable');
$attachment->asInline();
$attachment->getHeaders()->addParameterizedHeader('Content-Type', 'text/calendar', ['charset'=>'utf-8', 'method'=>'REQUEST']);
$mailMessage->attachPart($attachment);
```
with version 5.4.11 this results in an ordinary attached file (and overall Content-Type: multipart/related;) and does not work anymore.

**Comment by fabpot** [comment]
@peterreichenbach I'm going to investigate this change. It was probably introduced in #46963.

**Comment by fabpot** [comment]
@peterreichenbach #47437 should fix the regression.

**Comment by fabpot** [comment]
@cbutton74 

Based on suggestions above, here is what I use to test (not tested on Outlook on Windows as I don't have a Windows machine):

```php
// an email without text/html
$email = (new TemplatedEmail())
    ->from('xxx@example.org')
    ->to('xxx@example.com')
    ->subject('Test inline ICS')
;

// inline an ICS file (uses jsvrcek/ics)
$event = new CalendarEvent();
$event->setStart(new \DateTime())->setSummary('Dentist Appointment')->setUid('event-uid');
$calendar = new Calendar();
$calendar->setProdId('-//My Company//Cool Calendar App//EN')->addEvent($event);
$calendar->setMethod('REQUEST'); // or PUBLISH
$calendarExport = new CalendarExport(new CalendarStream(), new Formatter());
$calendarExport->addCalendar($calendar);
$ics = $calendarExport->getStream();

// inline it
$attachment = new DataPart($ics, 'inline.ics', 'text/calendar', 'quoted-printable');
$attachment->asInline();
$attachment->getHeaders()->addParameterizedHeader('Content-Type', 'text/calendar', ['charset' => 'utf-8', 'method' => 'REQUEST']);
$email->attachPart($attachment);

// send the email
$mailer->send($email);
```

If it works well for you, the next question would be if we want to make it easier or if we should just add something similar in the documentation.

**Comment by peterreichenbach** [comment]
works on outlook on windows. thanks.
