### ISSUE TITLE
[Notifier] Allow to update Slack messages using the same transport

### ISSUE THREAD

**Issue by maxim-dovydenok** [symfony/symfony#47274]
### Description

Current SlackTransport implementation has API method hardcoded: `chat.postMessage`
```
        $response = $this->client->request('POST', 'https://'.$this->getEndpoint().'/api/chat.postMessage', [
            'json' => array_filter($options),
            'auth_bearer' => $this->accessToken,
            'headers' => [
                'Content-Type' => 'application/json; charset=utf-8',
            ],
        ]);
```
`chat.update` API method requires 2 parameters: `transport` (already available in SlackOptions) and `ts` (should be added).
Then based on these options API method can be selected.

This feature can be used to update slack messages on entity status updates, etc. For example SentMessage id can be saved in the database when message is first sent to the slack, and later can be used to update the same message.

WDYT?

**Comment by fabpot** [comment]
Do you want to work on an implementation?

**Comment by maxim-dovydenok** [comment]
I investigated it a little bit and found out that `chat.postMessage` works with both channel names and channel ids (and I assume users of Symfony Notifier are using channel names), but `chat.update` supports only channel ids (I guess because channel names are editable, but you need unique uneditable id to update messages).

So unfortunately I don't think there's any way to implement it without breaking existing integrations:
- Option 1 - require users to use Channel Ids to configure Slack notifier - breaking change
- Option 2 - change sent message ids from just timestamp to channel id and timestamp, for example, `C123456:1660941547.955569` - that's what I implemented on my project. It's a breaking change though - if users use existing message ids to use Slack API directly, or something else

Actually, we can probably create SlackSentMessage and allow users to save id from it:
```
// Post
/** @var SlackSentMessage $sentMessage */
$sentMessage = $this->chatter->send(new ChatMessage('Send new message'));

// Update v1
$updateOptions = new SlackOptions([
    'ts' => $sentMessage->getMessageId(),
    'channelId' => $sentMessage->getSlackChannelId(),
]);
$this->chatter->send(new ChatMessage('Update this message', $updateOptions));

// Update v2
$updateOptions = new UpdateMessageSlackOptions($sentMessage->getMessageId(), $sentMessage->getSlackChannelId());
$this->chatter->send(new ChatMessage('Update this message', $updateOptions));

// Update v3
$updateOptions = new UpdateMessageSlackOptions($sentMessage->getFullMessageId());
$this->chatter->send(new ChatMessage('Update this message', $updateOptions));
```

What update version should I implement? I think I prefer v3
