### ISSUE TITLE
[Serializer] Using `CsvEncoder::NO_HEADERS_KEY` does not work as expected

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#47302]
### Symfony version(s) affected

4.4

### Description

Hi 👋🏻 

While encoding an array to `csv`, it seems that using the `CsvEncoder::NO_HEADERS_KEY` const does not trigger the desired output, instead, I must use `no_header` as the configuration option to effectively disable the headers in the encoded output.

The main issue is that both the source code and the documentation mentions `CsvEncoder::NO_HEADERS_KEY` and the `no_headers` key rather than `no_header` 🤔 

### How to reproduce

Well, just serializing an array using the serializer is enough to trigger the invalid case:

```php
// ...


// Invalid, it will output the headers based on the array keys
$foo = $this->serializer->serialize($array, 'csv', [
    CsvEncoder::DELIMITER_KEY => ';',
    'no_headers' => true,
]);

// Valid, it will not output the headers
$foo = $this->serializer->serialize($array, 'csv', [
    CsvEncoder::DELIMITER_KEY => ';',
    'no_header' => true,
]);
```

### Possible Solution

Maybe just change the const value or adapt the documentation, this seems weird as the current `6.2` branch mention `CsvEncoder::NO_HEADERS_KEY` 🤔

**Comment by MatTheCat** [comment]
I don’t reproduce (using symfony/serializer v6.1.3) and cannot see any instance of `no_header` in Symfony’s source code. Are you sure you didn’t inadvertently edit your vendors’ `CsvEncoder`? [Its `NO_HEADERS_KEY` never changed](https://github.com/symfony/symfony/pull/29283/files#diff-e3754e3175fa2f2830913e6d53759947ca8db58d3e7b1c1b61157997536e4e91R32).

**Comment by Guikingone** [comment]
Hi @MatTheCat 👋🏻 

Nope, the vendor are not edited, the packagist version is fixed using the official tag: `1b2ae02cb1b923987947e013688c51954a80b751` and the current class display the key value as the source code: 

```php
<?php

// ...

/**
 * Encodes CSV data.
 *
 * @author Kévin Dunglas <dunglas@gmail.com>
 * @author Oliver Hoff <oliver@hofff.com>
 */
class CsvEncoder implements EncoderInterface, DecoderInterface
{
    public const FORMAT = 'csv';
    public const DELIMITER_KEY = 'csv_delimiter';
    public const ENCLOSURE_KEY = 'csv_enclosure';
    public const ESCAPE_CHAR_KEY = 'csv_escape_char';
    public const KEY_SEPARATOR_KEY = 'csv_key_separator';
    public const HEADERS_KEY = 'csv_headers';
    public const ESCAPE_FORMULAS_KEY = 'csv_escape_formulas';
    public const AS_COLLECTION_KEY = 'as_collection';
    public const NO_HEADERS_KEY = 'no_headers';
    public const OUTPUT_UTF8_BOM_KEY = 'output_utf8_bom';

// ...
}
```

That's really weird 🤔

**Comment by MatTheCat** [comment]
Do you observe the same behavior whatever your `$array` is?

Could you provide a minimal reproducer?

**Comment by xabbuh** [comment]
@Guikingone Do you have something for us that we could look into?

**Comment by Guikingone** [comment]
Hi @xabbuh 👋🏻 

I tried to reproduce it locally using `4.4`, the `CsvEncoder:: NO_HEADERS_KEY` seems to work perfectly, I don't explain why locally it doesn't work even with a fixed version and no edit in the vendors, very strange 🙁 

Well, that's not the end goal here, as I can't reproduce it in a fresh installation, the issue can be closed, sorry for the wasted time 🙁
