### ISSUE TITLE
framework.enabled_locales does not behave as documented

### ISSUE THREAD

**Issue by lazka** [symfony/symfony#47355]
### Symfony version(s) affected

5.4.11

### Description

https://symfony.com/doc/5.4/reference/configuration/framework.html#enabled-locales states that "empty array = enable all locales", but if I set an empty array then [set_locale_from_accept_language](https://symfony.com/doc/5.4/reference/configuration/framework.html#set-locale-from-accept-language) will not set the locale. I have to fill `enabled_locales` for it to work.

Here is the code doing this: https://github.com/symfony/symfony/blob/e1581a0937c7e0c8d8420808ebc60418a63892c4/src/Symfony/Component/HttpKernel/EventListener/LocaleListener.php#L71 which was added in #43108 (`$this->enabledLocales` is checked to be non-empty)

@chalasr is this logic on purpose? Or does the documentation need adjustment that empty means no locale is enabled?

### How to reproduce

Run the following I guess: https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/HttpKernel/Tests/EventListener/LocaleListenerTest.php#L172

which tests that no locale is set if `enabled_locales` isn't set

**Comment by chalasr** [comment]
IIRC this has been done consciously, but at a point in time where the feature was not fully opt-in yet.
So I personally don't see any blocker for changing this. PR welcome

**Comment by lazka** [comment]
thanks @MatTheCat !
