### ISSUE TITLE
Impersonation exit logs out user

### ISSUE THREAD

**Issue by simonsolutions** [symfony/symfony#47356]
### Symfony version(s) affected

6.1.3

### Description

Exact the same behaviour as described in PR https://github.com/symfony/symfony/pull/46748 is in the current 6.1.3. 

The files changed in the PR seems not to be available in 6.1 branch, so the merging in this branch might have not fixed the issue.

### How to reproduce

Same as in PR described

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

The `UserAuthenticationProvider` class that was fixed in #46748 does not exist in 6.0+ anymore. So the fix provided there cannot be the solution for your issue.

**Comment by chalasr** [comment]
Also a similar piece of code meant to workaround the very same issue exists in https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L309 (where "deauthentication on user change" happens)

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by simonsolutions** [comment]
After much testing, I have set up a new project with just 2 controller - 1 with login required and 1 with no login and sure security controller and all needed for login.
The sample works but with comparing it to the existing 2 projects I can't find the problem. in the sample it works in the projects not.

As far as I could find out. the session data of the main firewall ("_security_main") is still there but the fields of the serialised data are empty. therefore the refresh user fails because the users are different (null vs data).

Directly before calling exit impersonation:
![image](https://user-images.githubusercontent.com/20499623/194913337-73b95615-1668-425a-aa0f-22c8e8376512.png)

After Exit impersonation:
![image](https://user-images.githubusercontent.com/20499623/194913253-031e83fd-cfdc-4966-9caf-3ed386a13116.png)

Does anyone have an idea where to look further? Thanks in advance.
