### ISSUE TITLE
[Security][RememberMe] Undefined array key 1

### ISSUE THREAD

**Issue by dannyvw** [symfony/symfony#47362]
### Symfony version(s) affected

6.1

### Description

With PHP 8.1 this line is triggering an error and deprecation https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Security/Http/RememberMe/RememberMeDetails.php#L40

Warning: Undefined array key 1
Deprecated: base64_decode(): Passing null to parameter #1 ($string) of type string is deprecated

### How to reproduce

`base64_decode(null, true)`

**Comment by xabbuh** [comment]
Can you create a small example application that allows us to reproduce how we can end up with `null` here?

**Comment by MatTheCat** [comment]
I guess a cookie whose value does not contain the delimiter will trigger this as we try to get `$cookieParts[1]` **before** counting `$cookieParts`.
