### ISSUE TITLE
var_dumper

### ISSUE THREAD

**Issue by remco-pc** [symfony/symfony#47385]
### Description

You guys did a terrific job for the var_dumper, it dumps well and in combination with doctrine (there i got it from) it can dump the objects. (My own dumper (dd & d)  functions get loaded by the class loader later so they won't be used but have a file & line nr in the output. 
What i miss in your var_dumper is the file & line nr where the dump takes place. can you add this to your var_dumper ? because i dump a lot in different files and loose sometimes the focus on certain dumps.
this will help debugging a lot because now i have to use my d (dump) function to show where it took place.

### Example

/Application/Host/Api/Service/Entity.php:635
string(4) "test"
^ {#678
  +"profile_id": "1"
}

**Comment by nicolas-grekas** [comment]
Please hover that caret `^` in the output, it contains the link to the source, including the line number;

**Comment by remco-pc** [comment]
if i try that in postman (view preview) i don't get that hover

**Comment by remco-pc** [comment]
and also in cli it is missing !

**Comment by chalasr** [comment]
You may want to use the [dump-server](https://symfony.com/doc/current/components/var_dumper.html#the-dump-server) for such contexts.

**Comment by remco-pc** [comment]
dump-server is a symfony thing, i am using it throught doctrine and does it dump where the file & line nr is of the dd command

**Comment by chalasr** [comment]
> dump-server is a symfony thing

Not more than the rest of the Symfony VarDumper component (including the `dump()` and `dd()` functions you're already using). This is all from Symfony, but it doesn't mean you have to use the whole framework.
Please read the docs, the console command can be used standalone.

**Comment by remco-pc** [comment]
i've found this: https://github.com/symfony/symfony/issues/24852 from 2017, 5 years later... does it still work ?

**Comment by remco-pc** [comment]
anyway i decided to create another function ddd which basically adds the file & line nr to dd
