### ISSUE TITLE
`MailerAssertionsTrait::getMailerMessage` returns messages that aren't rendered (BC break)

### ISSUE THREAD

**Issue by nesl247** [symfony/symfony#47383]
### Symfony version(s) affected

6.2.0

### Description

Prior to 6.2.0, a call to `self::getMailerMessage(0)` would return the only message that was sent. After https://github.com/symfony/symfony/pull/47191 was merged, this returns a message from the `QueueingMessageEvent`, which means it hasn't been rendered via `MessageListener` yet.

Given this is just in tests, it's not a critical BC break, but it is a BC break. I'm not sure if `getMailerMessage` and `getMailerMessages` is really intended to be returning `RawMessage`s from `QueueingMessageEvent` or not.

### How to reproduce

Create `templates/test_email.html.twig`

```
<?php

use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Mailer\MailerInterface;

class TestCase extends KernelTestCase
{
    public function testItSendsAnEmail(): void
    {
        $mailer = self::getContainer()->get(MailerInterface::class);

        $email = (new TemplatedEmail())
            ->from('from@example.com')
            ->to('user@example.com')
            ->htmlTemplate('test_email.html.twig');

        $mailer->send($email);

        $email = self::getMailerMessage(0);
        self::assertNotNull($email->getHtmlBody());
    }
}
```

### Possible Solution

Change `getMailerMessage` and `getMailerMessages` to filter the events to remove `QueueingMessageEvent`.

**Comment by PhilETaylor** [comment]
Confirmed today in 6.2.0-Beta1

This was the ONLY breaking change in my unit tests going from 6.1 to 6.2 

My test case was

```php
public function testEmailHeaders()
    {
        $kernel = static::createKernel();
        $kernel->boot();

        // get our own Mailer Service, which decorates the mailer
        $mailer = $this->getContainer()->get(MailerInterface::class);

        $message = (new Email())
            ->from('phil@phil-taylor.com')
            ->to('phil@phil-taylor.com')
            ->text('Unit Test Message')
            ->subject('Unit Test Message');

        $mailer->send($message);

        $email = $this->getMailerMessage();
        $this->assertEmailCount(1);
        $this->assertEmailHeaderSame($email, 'To', 'phil@phil-taylor.com');
        $this->assertEmailHeaderSame($email, 'Subject', 'Unit Test Message');

        // Ensure custom headers are present (This fails in 6.2)
        $this->assertEmailHasHeader($email, 'List-Unsubscribe');
        $this->assertEmailHasHeader($email, 'X-Report-Abuse');
        $this->assertEmailHasHeader($email, 'X-About');
        $this->assertEmailHasHeader($email, 'X-Auto-Response-Suppress');

        $this->assertEmailTextBodyContains($email, 'Unit Test Message');
        $this->assertEmailAttachmentCount($email, 0);
    }
```

The headers are added in framework.mailer.headers configuration and not per email, this unit test passes in 6.1 and fails in 6.2 as `  $email = $this->getMailerMessage()` returns the `QueueingMessageEvent` and not the real message sent.

**Comment by chalasr** [comment]
See #47992
