### ISSUE TITLE
[HttpKernel] Outdated DebugLoggerInterface::getLogs PHPDoc

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#47396]
### Symfony version(s) affected

5.4, 6

### Description

While trying to implement a `DebugLoggerInterface` around HttpKernel’s `Logger` I read the following:

https://github.com/symfony/symfony/blob/cdd1c08bf862055a361428293c1f6237ce572569/src/Symfony/Component/HttpKernel/Log/DebugLoggerInterface.php#L26-L28

But it seems that since https://github.com/symfony/symfony/pull/42195 the `LoggerDataCollector` will expect the keys

- `channel`
- `context`
- `message`
- `priority`
- `priorityName`
- `timestamp_rfc3339`

So

- `timestamp` is not needed
- `context` is not optional
- `timestamp_rfc3339`and `channel` are mandatory

It seems to me `DebugLoggerInterface` is almost exclusively used by the `LoggerDataCollector` so I guess the keys should match.

### How to reproduce

Decorate HttpKernel’s logger to implement `DebugLoggerInterface`:

```php
<?php

namespace App\Log;

use Psr\Log\LoggerInterface;
use Psr\Log\LoggerTrait;
use Psr\Log\LogLevel;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Log\DebugLoggerInterface;

#[AsDecorator('logger')]
class DebugLogger implements LoggerInterface, DebugLoggerInterface
{
    use LoggerTrait;
    
    private array $logsByRequest = [];
    
    public function __construct(
        private readonly LoggerInterface $logger,
        private readonly RequestStack $requestStack,
    ) {}

    public function log($level, $message, array $context = []): void
    {
        $this->logger->log($level, $message, $context);
        
        $request = $this->requestStack->getCurrentRequest();

        $this->logsByRequest[$request ? spl_object_hash($request) : ''][] = [
            'context' => $context,
            'message' => $message,
            'priority' => [
                LogLevel::DEBUG => 0,
                LogLevel::INFO => 1,
                LogLevel::NOTICE => 2,
                LogLevel::WARNING => 3,
                LogLevel::ERROR => 4,
                LogLevel::CRITICAL => 5,
                LogLevel::ALERT => 6,
                LogLevel::EMERGENCY => 7,
            ][$level],
            'priorityName' => $level,
            'timestamp' => time(),
        ];
    }

    public function getLogs(Request $request = null): array
    {
        if ($request) {
            return $this->logsByRequest[spl_object_hash($request)] ?? [];
        }
        
        return array_merge(...array_values($this->logsByRequest));
    }

    public function countErrors(Request $request = null): int
    {
        $errorCount = 0;
        foreach ($this->getLogs($request) as $log) {
            if ($log['priority'] >= 4) {
                ++$errorCount;
            }
        }
        return $errorCount;
    }

    public function clear()
    {
        $this->logsByRequest = [];
    }
}

```

then access the profiler’s logger panel. It will crash.

### Possible Solution

Update mandatory keys to be used by the `LoggerDataCollector`.

**Comment by stof** [comment]
I guess we forgot to update the phpdoc of the interface at some point.

**Comment by MatTheCat** [comment]
Okay I can submit a PR against 5.4 then :+1:

**Comment by stof** [comment]
@MatTheCat please do

**Comment by MatTheCat** [comment]
Just saw `timestamp` is in fact used by the `HtmlErrorRenderer` (in the `logs.html.php` template). I will have to dig some more.

**Comment by MatTheCat** [comment]
Hm at this point I have three questions about `DebugLoggerInterface::getLogs` expected return values:

1. why is a key named `timestamp_rfc3339`? `DateTimeInterface::RFC3339_EXTENDED` is the only format including milliseconds, but it is not a timestamp (neither is `DateTimeInterface::RFC3339` which is not used). Then the `LoggerDataCollector` stores it under a `timestamp` key :dizzy_face: 
2. why was the `timestamp` key kept? It is redundant with `timestamp_rfc3339`.
3. could `DebugLoggerInterface::getLogs` return POPOs instead of maps?

Poke @javiereguiluz :wave:
