### ISSUE TITLE
Password not working with an unix socket for Messenger redis transport

### ISSUE THREAD

**Issue by Arakmar** [symfony/symfony#47393]
### Symfony version(s) affected

6.1.3, 5.4.11

### Description

When a messenger async transport is configured with Redis (unix socket with a password), it gives DSN parsing errors.
After looking at the code, the password is properly parsed only when a host is used.
It's also the same for the password option, it's not used in case of a socket.

The redis cache adapter doesn't seem to be affected by this problem. It allows DSN like that :
`redis[s]://[pass@][ip|host|socket[:port]][/db-index]`

### How to reproduce

Use a DSN like that for an async messenger queue :
`redis://password@/var/run/redis.sock`

It gives the following error :

> The given Redis DSN is invalid

### Possible Solution

Add support for passwords with redis socket in the same way the redis cache adapter does.

I can propose a PR for that.

**Comment by xabbuh** [comment]
If you want to, please give it a try. 👍

**Comment by PhilETaylor** [comment]
Does this work for you @Arakmar

**Comment by PhilETaylor** [comment]
Does this work for you @Arakmar

https://github.com/symfony/symfony/pull/47475

**Comment by Arakmar** [comment]
I tested it with different scenarios (socket, host, user / password or not) and it works just fine. Thanks for taking care of that !

**Comment by nico89700** [comment]
brulindsay@gmail.com
