### ISSUE TITLE
Service decoration resolution should mark the alias it creates a wanna-be-private for services tagged as `container.private`

### ISSUE THREAD

**Issue by stof** [symfony/symfony#47408]
### Symfony version(s) affected

5.4

### Description

Accessing the `validator` service from the TestContainer triggers a deprecation while it should still be allowed.

### How to reproduce

Create a test that accesses the `validator` service from the TestContainer.

This triggers a deprecation that accessing `validator` from the container is deprecated and DI should be used instead. But TestContainer is precisely meant to allow allow accessing private services.

The issue is that `validator` has the tag `container.private` which would add it in the test service locator, but it is decorated by `debug.validator` (the TraceableValidator), which looses that condition. And so the `validator` id is not added in the private test locator.

However, as this wanna-be-private is now handled with tags, I'm not sure we actually have a way to mark an alias as becoming private in the future.

**Comment by nicolas-grekas** [comment]
Is this still a thing? I cannot reproduce with a 6.3 app. If yes, can you please provide my with a small reproducer?

**Comment by stof** [comment]
Well, to reproduce this on 6.3, you need to find a wanna-be-private service that is decorated.
The `validator` service is not affected anymore in 6.x because it became fully private. But I'm quite sure that the issue still exists in the DI component, waiting for the next service that will be marked as wanna-be-private.
