### ISSUE TITLE
Proxy method parameter issue with 6.1.4

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#47404]
### Symfony version(s) affected

6.1.4

### Description

I have an entity named `Product` and `Sample` with 'public const' parameters used as arguments in both classes.
The issue appear when dealing with Proxies.

### How to reproduce

```
<?php

namespace App\Entity;
class Product
{
    public const MYCONST  = 512;
    public function foo($myparam = Product:: MYCONST): { /*...*/}
} 

namespace App\Entity\Extra;

use App\Entity\Product;
class Sample
{
    public function foo($myparam = Product:: MYCONST): { /*...*/}
} 

```

It results into this error message from Sample class:
```
Class "App\Entity\Extra\App\Entity\Product" does not exist
```

### Possible Solution

Looking at the proxy file.. it seems that Product class is extended but a backslash is missing !

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by meiyasan** [comment]
what do you mean by application ?

**Comment by stof** [comment]
Anyway, this is something to report to doctrine/common (which is where the Doctrine proxy implementation is), not to Symfony.
