### ISSUE TITLE
[Console] Question helper is behaving differently when inside a Section

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#47411]
### Symfony version(s) affected

6.1.4

### Description

The question helper is going onto a new line when used inside a Section, therefore section cannot rewrite correctly

### How to reproduce

# Question helper only
<details>
  <summary>Code</summary>
  
  ```php
        $io = new SymfonyStyle($input, $output);

        $countdown = 3;
        while ($countdown > 0) {
            $io->write('Lorem ipsum ' . $countdown);
            $random = $io->ask('Press random key');
            $countdown--;
        }
  ```
</details>
<a href="https://asciinema.org/a/517552" target="_blank"><img src="https://asciinema.org/a/517552.svg" /></a>

# Section helper only
<details>
  <summary>Code</summary>
  
  ```php
        $section = $output->section();

        $countdown = 3;
        while ($countdown > 0) {
            $section->clear();
            $section->write('Lorem ipsum ' . $countdown);
            $countdown--;
            sleep(1);
        }
  ```
</details>
<a href="https://asciinema.org/a/517554" target="_blank"><img src="https://asciinema.org/a/517554.svg" /></a>

# Both combined
<details>
  <summary>Code</summary>
  
  ```php
        $section = $output->section();
        $io = new SymfonyStyle($input, $section);

        $countdown = 3;
        while ($countdown > 0) {
            $section->clear();
            $section->write('Lorem ipsum ' . $countdown);

            $random = $io->ask('Press random key');
            $countdown--;
        }
  ```
</details>
<a href="https://asciinema.org/a/517555" target="_blank"><img src="https://asciinema.org/a/517555.svg" /></a>

### Expected
Final output should be
```
Lorem ipsum 1

 Press random key:
 > something

```

**Comment by chalasr** [comment]
Thanks for the report, looks like a bug indeed. Are you wiling to investigate and try to send a fix?

**Comment by bigfoot90** [comment]
I can try

**Comment by bigfoot90** [comment]
Sorry I didn't had time to work on this yet. :-(

**Comment by maxbeckers** [comment]
@bigfoot90 just a question, did you have this problems on a unix or on a windows environment? I can only reproduce this on windows.

/cc @chalasr what I saw on windows is again a lineending bug:
https://github.com/symfony/symfony/blob/1f83ce771cc9d20c430342c88cd4291d8f4f96ef/src/Symfony/Component/Console/Style/SymfonyStyle.php#L302
Changing this php `PHP_EOL` would fix it (for windows env)

And affected versions are then symfony 4.4+

**Comment by bigfoot90** [comment]
@maxbeckers I'm on Ubuntu system

**Comment by maxbeckers** [comment]
@bigfoot90 you're right, there was sth wrong in my vendors. And the enter of the input is the problem you mentioned.

**Comment by nicolas-grekas** [comment]
#48089 has been reverted in #48681

**Comment by maxbeckers** [comment]
I figured out that the behavior in symfony 6.2 changed here. That's the reason, why it was not possible to merge the fix into 6.2. But the behaviod didn't become better with symfony 6.2 in this cases:
![47411-img](https://user-images.githubusercontent.com/11738128/210209517-91347b4f-dffc-4432-ac4a-3de38d318e88.png)
Now there are empty lines as well. I'll try to find out, what's happening here.

**Comment by chalasr** [comment]
Thank you 🙏

**Comment by maxbeckers** [comment]
The new changes of the behavior seem to be related to #37304 ... `write('test'.\PHP_EOL)` (result: "test\n\n") and `writeln('test')` (result: "test\n") have now different behavior. 

This seems to be related to
https://github.com/symfony/symfony/blob/4cf9855debc26e4323429ac8d87f02df582e2893/src/Symfony/Component/Console/Output/ConsoleSectionOutput.php#L181
Because there is for newline always `true` ... setting this to the parameter `$newline` seems to fix most of the problem. I could set it to `$newline` and create a PR, But I don't know the effects of this change, because it will have any reason that it's not `$newline` for now I guess.

@chalasr do you have any Idea, why it's not `$newline` there?
