### ISSUE TITLE
[String] Snakecase breaked 

### ISSUE THREAD

**Issue by mpiot** [symfony/symfony#47421]
### Symfony version(s) affected

6.1.4

### Description

Since #47185, when using `u('GREAT')->snake()->toString()` it return us `g_reat` instead of `great`.

### How to reproduce

```php
u('GREAT')->snake()->toString();
```

**Comment by mpiot** [comment]
ping @simPod

**Comment by simPod** [comment]
I'd say it's correct. Same as `camel()` will give you `gREAT`.

**Comment by mpiot** [comment]
I think we need to keep a single word not separated (lowercase or _),  to have something like:

* CamelCase
SYMFONY => symfony
Symfony is GREAT => symfonyIsGREAT

* SnakeCase
SYMFONY => symfony
Symfony is GREAT => symfony_is_great

I've proposed a PR to fix the `->camel()` method.
