### ISSUE TITLE
[DependencyInjection] Wrong behaviour in Functionnal test after submit form

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/symfony#47429]
### Symfony version(s) affected

5.4.12

### Description

When you want to test (functional test) that contains external calls, one method is to overwrite the external repositories.

You can decide to hard code  your FakeRepository like that

```php
class FakePostApiRepository implements PostRepositoryInterface
{

    public function find(int $id): Post
    {

        return new Post(
            1,
            'Fake data post'
        );
    }

}
```
Or more flexible, allow inject data before test

```php
class FakePostApiRepository implements PostRepositoryInterface
{
    /**
     * @var array
     */
    private $fakeDataResponse;

    public function __construct(array $fakeDataResponse = [])
    {
        $this->fakeDataResponse = $fakeDataResponse;
    }

    public function find(int $id): Post
    {

        return new Post(
            $this->fakeDataResponse[0]['id'],
            $this->fakeDataResponse[0]['name']
        );
    }

}
```
```php
public function testBehaviourApi()
    {
        $client = static::createClient();

        $client->getContainer()->set(
            FakePostApiRepository::class,
            new FakePostApiRepository(
                [['id' => 2, 'name' => 'Fake post']]
            )
        );

        $client->request('GET', '/');

        $this->assertStringContainsString(
            'Fake post',
            $client->getResponse()->getContent()
        );
    }
```

@ismail1432 explain this approach in
https://smaine-milianni.medium.com/mock-the-symfony-httpclient-a1b2451430ef

But the same approach after submit form don't have same behaviour, Fake Repository is injected (after submit) with initial data define on when@test

### How to reproduce

Download

https://github.com/thewalkingcoder/tf-dynamic-container

launch

```
bin/phpunit tests/Fonctionnal/PostApiTest.php --filter=testBehaviourApi
```
Work's fine
![image](https://user-images.githubusercontent.com/10476280/187443568-78937111-5f28-4df7-abcc-fd8ae441aae8.png)

Launch with form
```php
bin/phpunit tests/Fonctionnal/PostApiTest.php --filter=testBehaviourWithForm
```
![image](https://user-images.githubusercontent.com/10476280/187444624-55c7eb70-f731-4e64-921c-0f4f615af37c.png)

First call use overwriting class inside test

```php
 $client->getContainer()->set(
            FakePostApiRepository::class,
            new FakePostApiRepository(
                [['id' => 2, 'name' => 'Fake post with form']]
            )
        );
```
but after submit container return initial object

![image](https://user-images.githubusercontent.com/10476280/187449279-e9aa4bad-dd20-4c6e-86cc-3c7bb9d8d1c2.png)

I missed something ?

**Comment by stof** [comment]
well, here, your repository returns a *new* object each time you call `find` on it. It does not keep an identity map to return the same instance when asking multiple times for the same id (allowing it to keep track of mutations done in the object returned in the first call). This means that your fake repository does not behave the same than a Doctrine repository and so is not a suitable replacement.

There is no bug in the DependencyInjection component. The bug is in your own code (either in the implementation of your FakeRepository if you intend it to behave like a Doctrine repository, or in your logic if you expect repositories to work in a different way, where it should keep using the original `$post` object if the repository does not guarantee the identity map).

I'm closing this issue as there is nothing to change or fix in Symfony.

**Comment by thewalkingcoder** [comment]
After many times, I found solution to use this approach.

Just disable reboot kernel after createClient

```php
  $client = static::createClient();
  $client->disableReboot();

```

```php
public function testBehaviourWithForm()
{
        $client = static::createClient();
        $client->disableReboot();

        $client->getContainer()->set(
            FakePostApiRepository::class,
            new FakePostApiRepository(
                [['id' => 2, 'name' => 'Fake data']]
            )
        );

        $crawler = $client->request('GET', '/form');
        $buttonCrawlerNode = $crawler->selectButton('launch');

        $form = $buttonCrawlerNode->form([], 'POST');
        $form['post[id]']->setValue('2');
        $client->submit($form);

       $this->assertStringContainsString(
            'Fake data',
            $client->getResponse()->getContent()
        );

}
```
