### ISSUE TITLE
[HttpClientBundle] RetryableHttpClient invalid delay 

### ISSUE THREAD

**Issue by martkop26** [symfony/symfony#47430]
### Symfony version(s) affected

6.1.4

### Description

The Symfony RetryableHttpClient defines the $delay variable by calling ` $this->getDelayFromHeader($context->getHeaders())`.
According to the [RFC](https://docs.w3cub.com/http/status/429) this header should be _A non-negative decimal integer indicating the seconds to delay after the response is received_.  By directly casting the value to integer, we lose the decimal value, resulting in an invalid delay.

### How to reproduce

Use the Symfony HTTP Client package.
Use the RetryableHttpClient in combination with an API which returns a HTTP code causing the RetryableHttpClient to retry.
Make sure the API returns the header 'retry-after' with a decimal value, e.g. `0.63`.

The expected result will be the $delay variable to be `630`.
The actual result is the $delay variable to be `0`

### Possible Solution

Rewrite line 141 of the Symfony\Component\HttpClient\RetryableHttpClient
from `return (int) $after * 1000;` to `return (int) ($after * 1000);`

### Additional Context

Test showing the issue

![http_client_original](https://user-images.githubusercontent.com/112486711/187447683-5a145c69-4527-4a61-9783-f5000f1208fd.png)

The same test with the changed line in the RetryableHttpClient

![http_client_fix](https://user-images.githubusercontent.com/112486711/187447646-60e6a7af-62cf-4a75-af03-7608ed11dcd0.png)

In both cases, the header _retry-after_ returned a value of `0.70`

**Comment by nicolas-grekas** [comment]
Up for sending a PR, with a test case?

**Comment by martkop26** [comment]
Yes, however I haven't forked the Symfony project yet. I just used the web IDE for now.
Hopefully I will have added a PR and unit test this week. After that, I shall update the issue with the PR and send you an update
