### ISSUE TITLE
[Router][FrameworkBundle] Class loading exceptions hidden by the DelegatingLoader

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#4743]
We just spent a nice debugging session only to find that there was a typo in the namespace of the class (inside the file), which meant the class couldn't be loaded, and it did not appear as valid in the routes.

The reason is that the [ControllerNameParser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php#L54) is checking class_exists, which throws an exception on this particular case, so all is well, but the [DelegatingLoader](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php#L63) catches the exceptions and discards it all.

I'm not sure how to fix this, because I suppose the DelegatingLoader has a good reason for ignoring exceptions. I don't see what that would be though? Surely if a controller can not be resolved, the developers should be warned?

**Comment by stof** [comment]
@Seldaek I think this should be closed. The router never advocates that ``_controller`` will contain a resolved class name in the controller string reference (hint: it cannot make such promise, for instance for controllers defined as services where the ``_controller`` string needs to contain the service id, not a class name).
the proper solution for NelmioApiDocBundle would be to use the ControllerResolver to resolve the string

**Comment by Seldaek** [comment]
Fine by me.
