### ISSUE TITLE
Add ability to get/resolve parameter with PhpFileLoader

### ISSUE THREAD

**Issue by xorik** [symfony/symfony#47479]
### Description

Hi!
I use `PhpFileLoader` to add services in DI, and I need a way to resolve an env variable from parameter. Currently conditional services definitions are possible with `$configurator->env()`.

But sometimes I need to check condition based on parameter, e.g.:
```yaml
parameters:
      push_notifications_enabled: '%env(bool:PUSH_NOTIFICATIONS_ENABLED)%'
```

So I can do this with the `ContainerBuilder` class, e.g.:
```php
$builder = new ContainerBuilder();
$pushEnabled = $builder->resolveEnvPlaceholders($builder->getParameter('push_notifications_enabled'), true);

if ($pushEnabled) {
    // ... define real service
} else {
    // ... define stub service
}
```

This is a bit dirty, because 95% of services are defined in a one place, but some of the services are defined with totally different syntax in a separate place.

But I cannot do it when I use `PhpFileLoader` because there is no access to those methods inside `ContainerConfigurator`

### Example

It might look something like that:
```php
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return function (ContainerConfigurator $configurator) {
    if ($configurator->resolveParam('push_notifications_enabled')) {
        $services->set(PushProviderInterface::class, RealPushProvider::class);
    } else {
        $services->set(PushProviderInterface::class, FakePushProvider::class);
    }
};
```

**Comment by MatTheCat** [comment]
Hi!

I don’t think this is supported whatever the config format?

I would use a compiler pass in your case.

**Comment by xorik** [comment]
It would be nice if all services are defined in the same place. I think it's okay to access properties during service configuration. It's strange that `env` is exposed, but parameters are not

**Comment by xorik** [comment]
Actually I've just found that it's possible to pass `ContainerBuilder` inside the PHP DI definition.

```php
return function (ContainerConfigurator $configurator, ContainerBuilder $builder) {
   $enabled = $builder->resolveEnvPlaceholders($builder->getParameter('push_notifications_enabled'), true);
};
```

So I guess my question is now solved
