### ISSUE TITLE
AbstractController::json recursive call context

### ISSUE THREAD

**Issue by web-fu** [symfony/symfony#47506]
### Symfony version(s) affected

5.4

### Description

When you call `$this->json` in a controller, this function is called:

```
/**
 * Returns a JsonResponse that uses the serializer component if enabled, or json_encode.
 */
protected function json($data, int $status = 200, array $headers = [], array $context = []): JsonResponse
{
    if ($this->container->has('serializer')) {
        $json = $this->container->get('serializer')->serialize($data, 'json', array_merge([
            'json_encode_options' => JsonResponse::DEFAULT_ENCODING_OPTIONS,
        ], $context));

        return $this->json($json, $status, $headers, true);
    }

    return $this->json($data, $status, $headers);
}
```

The recursive call require an array as context, but a boolean is given

### How to reproduce

Create a controller and return a serializable entity

```
public function genericRoute(Request $request): JsonResponse
{
    $data = new Entity();

    return $this->json($data);
}
```

**Comment by stof** [comment]
This is **not** the code being called: 
https://github.com/symfony/symfony/blob/af1ab9e515739e8536e6b9925296ed5c554f8ff3/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L176-L189

**Comment by web-fu** [comment]
After some hour of debugging I discovered that my vendor dir was corrupted.
Sorry for the wrong bug submission
