### ISSUE TITLE
[VarDumper] Display BOM characters

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#47519]
Hello,

We had a very strange issue, and it was a bit hard to debug (Mind the `!==`) : 

![image](https://user-images.githubusercontent.com/408368/189096454-9f9f2048-b460-4e6e-8d95-9e1e0c800d67.png)

---

TL;DR: there was a [BOM](https://www.compart.com/en/unicode/U+FEFF) (`U+FEFF`) character in front of the string.

---

I would be very cool to have the vardumper displaying such characters.
I made a reproducer if it can help:

https://gist.github.com/lyrixx/8fe4a205864855bd23f1c0ec44b6d72d

![image](https://user-images.githubusercontent.com/408368/189097292-daca6e32-32f2-45f0-8c82-9afffb0be6f6.png)

---

BTW, my IDE warns me about that:
![image](https://user-images.githubusercontent.com/408368/189097753-eff584ed-273e-4c6a-b403-d75c1d92988a.png)

**Comment by damienalexandre** [comment]
All invisible Unicode characters could shown like that. There is already a ![image](https://user-images.githubusercontent.com/225704/189117841-66befafd-5e08-4a00-ab26-74145c63a38d.png) to display newline, we could have the same thing.


See this reference: https://invisible-characters.com/

**Comment by nicolas-grekas** [comment]
That'd make sense to me, we should display them as we do for `\n`, as eg `\u{feff}`

**Comment by lyrixx** [comment]
I think it's a good idea, yes 💛
