### ISSUE TITLE
var_dumper needs file of dd & line nr in cli & postman

### ISSUE THREAD

**Issue by remco-pc** [symfony/symfony#47517]
### Description

Description
You guys did a terrific job for the var_dumper, it dumps well and in combination with doctrine (there i got it from) it can dump the objects. (My own dumper (dd & d) functions get loaded by the class loader later so they won't be used but have a file & line nr in the output.
What i miss in your var_dumper is the file & line nr where the dump takes place. can you add this to your var_dumper ? because i dump a lot in different files and loose sometimes the focus on certain dumps.
this will help debugging a lot because now i have to use my d (dump) function to show where it took place.

Example
/Application/Host/Api/Service/Entity.php:635
string(4) "test"
^ {https://github.com/symfony/symfony/pull/678
+"profile_id": "1"
}

**Comment by chalasr** [comment]
Please don't duplicate a closed discussion and ask someone to reopen the first one instead.
