### ISSUE TITLE
Symfony\Component\Validator\Mapping\PropertyMetadata::newReflectionMember returns a ReflectionProperty which is not accessible anymore

### ISSUE THREAD

**Issue by Sandritsch91** [symfony/symfony#47514]
### Symfony version(s) affected

6.1, 6.2

### Description

```php
$member = new \ReflectionProperty($objectOrClassName, $this->getName());
$member->setAccessible(true);

return $member;
```

got replaced with 

```php
return new \ReflectionProperty($objectOrClassName, $this->getName());
```

in commit b0217c600f078d58d6c3bd9895d6a015d1f24c14.

So private an protected properties cannot be validated anymore

### How to reproduce

Just try to validate a private property of a class

### Possible Solution

Switch

```php
return new \ReflectionProperty($objectOrClassName, $this->getName());
```

and

```php
$member = new \ReflectionProperty($objectOrClassName, $this->getName());
$member->setAccessible(true);

return $member;
```
again

**Comment by nicolas-grekas** [comment]
Per https://wiki.php.net/rfc/make-reflection-setaccessible-no-op this should not be needed anymore (SF6.1 requires PHP >= 8.1)

**Comment by xabbuh** [comment]
There should also be tests covering this. That’s why I am closing here. But please comment if you experience any real issues with this change.
