### ISSUE TITLE
Symfony CLI doesn't find all the php versions on my system

### ISSUE THREAD

**Issue by eved42** [symfony/symfony#47531]
### Symfony version(s) affected

6.0, 6.1

### Description

I created a Symfony 6 project locally on my PC (Windows 11 Entreprise v.21H2) and I want to use a specific version of PHP. I know that we can use different versions by creating a `.php-version` file in the project root.

So I did this command `symfony local:php:list` to see the choices I have and it only shows Wamp64 and Xampp php that **I don't want to use**. I have many other versions inside `C:/php/` folder and I would like to select one of them.

Why Symfony CLI doesn't show them in the list ? And how to fix that ?

For info, I work with a non-admin user account on my PC but I have another admin account for installing programs.

![php versions](https://user-images.githubusercontent.com/12841417/189350671-d2452b15-53eb-4ca9-b5ff-09990ccc6b55.png)

![2022-09-08 10_28_07-php](https://user-images.githubusercontent.com/12841417/189350696-d7fdb8de-a147-44e4-b30a-aed419ca06d8.png)

### How to reproduce

Windows 11 Entreprise version 21H2
Install Symfony CLI version 5.4.13

**Comment by stof** [comment]
The Symfony CLI lives at https://github.com/symfony-cli/symfony-cli

**Comment by stof** [comment]
And the Windows discovery logic is implemented in https://github.com/symfony-cli/phpstore/blob/main/discovery_windows.go

**Comment by eved42** [comment]
Ok thank you @stof . Sorry for the inconvenience.
