### ISSUE TITLE
Firewall - add info which firewall and acl has been hit

### ISSUE THREAD

**Issue by devhelp** [symfony/symfony#4753]
Could you add information in the debug toolbar which firewall has been hit during the request and which acl has been invoked ? 
I am having  a problem when debugging it and I think this will be helpfull during development.

**Comment by javiereguiluz** [comment]
I've tried to fix this and show the firewall name in the toolbar. Sadly I couldn't. Getting the `providerKey` is easy, but sometimes it's different from the firewall name. Getting the real firewall name is "impossible" (in [this comment](https://github.com/symfony/symfony/issues/14435#issuecomment-110922402) you can see the code some people use to get it).

I would close this as "won't fix".
