### ISSUE TITLE
[mailer] AwsSes using the wrong endpoint

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#47540]
### Symfony version(s) affected

5.4.*

### Description

I'm trying to send emails on a new project using AWS SeS, and I can't use the correct endpoint.
I've setup `MAILER_DSN` as per instructions found [here](https://symfony.com/doc/current/mailer.html#transport-setup)
Am I doing something wrong ?

### How to reproduce

I've installed `symfony/amazon-mailer` and I have configured in `.env`  `MAILER_DSN="ses+api://private:stuff@default?region=eu-west-2"`
and yet when I do try and send an email I will get an `Exception`

```sh
AsyncAws\Ses\Exception\MessageRejectedException:
HTTP 400 returned for "https://email.eu-west-1.amazonaws.com/v2/email/outbound-emails".

Code:    MessageRejected
Message: Email address is not verified. The following identities failed the check in region EU-WEST-1: MAiL Bot <noreply@domain.tld>
```

please notice that I want to use `eu-west-2` but the mailer is trying to use `eu-west-1`

I've also tried using `MAILER_DSN="ses+api://private:stuff@eu-west-2"` but got the same result

### Additional Context

I've had a look at amazon-mailer bundle and I think the problem resides here

[SesApiAsyncAwsTransport.php](https://github.com/symfony/amazon-mailer/blob/ec56f447a003dd903a90b41c68fc6eb599ae0e6a/Transport/SesApiAsyncAwsTransport.php#L29)

```php
class SesApiAsyncAwsTransport extends SesHttpAsyncAwsTransport
{
    public function __toString(): string
    {
        $configuration = $this->sesClient->getConfiguration();
        if (!$configuration->isDefault('endpoint')) {
            $endpoint = parse_url($configuration->get('endpoint'));
            $host = $endpoint['host'].($endpoint['port'] ?? null ? ':'.$endpoint['port'] : '');
        } else {
            $host = $configuration->get('region');
        }

        return sprintf('ses+api://%s@%s', $configuration->get('accessKeyId'), $host);
    }
```

to my understanding after reading [this](https://async-aws.com/integration/symfony-bundle.html)

`AsyncAws\Ses\SesClient` needs to be setup with a region value, which I've done so, in services.yaml, but got the same result

```yaml
    AsyncAws\Ses\SesClient:
            arguments:
            - region: eu-west-2
 ```

**Comment by xabbuh** [comment]
This should be handled inside the `SesTransportFactory` (https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php#L50). Can you debug what's in `$options` when it's being passed to `Configuration` in your case?

**Comment by cybernet** [comment]
unfortunately I don't know how to do it

I can share some screenshots from `_profiler`

<img width="1680" alt="Screenshot 2022-09-13 at 08 45 53" src="https://user-images.githubusercontent.com/125879/189844152-aa5356c3-c8f9-432e-af60-a3cdfeeeb85a.png">

<img width="1119" alt="Screenshot 2022-09-13 at 08 48 55" src="https://user-images.githubusercontent.com/125879/189844218-f955913b-d44a-4367-aeff-f9b9eda96b8c.png">

<img width="1680" alt="Screenshot 2022-09-13 at 08 47 24" src="https://user-images.githubusercontent.com/125879/189844271-0e4dd59b-97c0-4167-b0b9-316ffe81cbf5.png">


i'm using `.env.local` not `.env` if that matters, and I have `ses+api://` set, not just `ses`
<img width="634" alt="Screenshot 2022-09-13 at 08 51 59" src="https://user-images.githubusercontent.com/125879/189844312-d53cb90d-85f0-4f07-b282-38b1fe756658.png">

I know this may not be of much help, but hopefully it's gonna offer some insight

**Comment by cybernet** [comment]
I found the issue and it's my fault.
my IDE wasn't configured to delete remote files if I delete from local ... 🥹 sorry for the trouble

I had `.env.dev` on remote but not on local

**Comment by xabbuh** [comment]
No worries, thanks for the feedback and for closing the issue. 👍
