### ISSUE TITLE
symfony mailer wants to load class

### ISSUE THREAD

**Issue by remco-pc** [symfony/symfony#47546]
### Symfony version(s) affected

symfony mailer 5.4

### Description

in Transport.php on line 192 it is trying to do a class_exist, i am using the smtp variant not the gmail variant. which tries to be loaded in my project. my project is in development mode and will not silent ignore failed loaded classes (because its in dev mode it shows a list where it tries to locate the files. My thoughts are that failed loaded classes is a bad practice.

it tries to load GmailTransportFactory.php among the others i don't know where these files should exist. 

```php

 [2]=>
    array(1) {
      ["function"]=>
      string(17) "spl_autoload_call"
    }
    [3]=>
    array(3) {
      ["file"]=>
      string(48) "/Application/vendor/symfony/mailer/Transport.php"
      ["line"]=>
      int(193)
      ["function"]=>
      string(12) "class_exists"
    }
    [4]=>
    array(3) {
      ["function"]=>
      string(19) "getDefaultFactories"
      ["class"]=>
      string(34) "Symfony\Component\Mailer\Transport"
      ["type"]=>
      string(2) "::"
    }
    [5]=>
    array(3) {
      ["file"]=>
      string(48) "/Application/vendor/symfony/mailer/Transport.php"
      ["line"]=>
      int(72)
      ["function"]=>
      string(17) "iterator_to_array"
    }
    [6]=>
    array(5) {
      ["file"]=>
      string(58) "/Application/Host/Api/Workandtravel/World/Service/Mail.php"
      ["line"]=>
      int(97)
      ["function"]=>
      string(7) "fromDsn"
      ["class"]=>
      string(34) "Symfony\Component\Mailer\Transport"
      ["type"]=>
      string(2) "::"
```

### How to reproduce

check the autoload on missing files when sending a mail through smtp transport loaded from dsn:
```php
dsn =
            'smtp://' .
            $config->get('username') .
            ':' .
            $config->get('password') .
            '@' .
            $config->get('hostname') .
            ':' .
            $config->get('port');
        $transport = Transport::fromDsn($dsn);
```
triggers it

### Possible Solution

include those transports in the default version or give an extra parameter to fromDsn with false to not autoload classes

instead of

```php
foreach (self::FACTORY_CLASSES as $factoryClass) {
            if (class_exists($factoryClass)) {
                yield new $factoryClass($dispatcher, $client, $logger);
            }
        }
```

```php
foreach (self::FACTORY_CLASSES as $factoryClass) {
            if (class_exists($factoryClass, false)) {
                yield new $factoryClass($dispatcher, $client, $logger);
            }
        }
```

### Additional Context

I am running a docker image (debian) with php and uses the package manager of debian so i could not use the latest mailer because i am still stuck at 7.4.30 (still no php 8.1 on debian...)

**Comment by derrabus** [comment]
> My thoughts are that failed loaded classes is a bad practice.

This is probably the part where we will have a major disagreement. A `class_exists()` check is a perfectly normal thing to do and it should be allowed to fail.

**Comment by fabpot** [comment]
And we are using `class_exists()` a lot for feature discovery in Symfony. So, I don't think this is something we can "fix".

**Comment by xabbuh** [comment]
closing as explained by @derrabus and @fabpot

**Comment by stof** [comment]
Btw, using `class_exists($factoryClass, false)` would break that code entirely, as that would check whether the class has already been loaded in the currently running process, not whether it exists in the project. So unless you eagerly load all files from your vendor folder, such check would be broken.

**Comment by remco-pc** [comment]
i can solve this by running 2 instances of my own framework which i am using, one for the mail (in production mode) & one in development mode, I saw this also in Doctrine. I created empty classes for that and it worked. but my list is handy in development mode and I have my list because I also use it to put files in certain places (where it should be). discovery should be an option in Transport and then use 
```php
class_exists($factoryClass, false)
```

when discovery is false:

```php
 $transport = Transport::fromDsn($dsn, $discovery=false);
```

is this an option ?

**Comment by remco-pc** [comment]
It might also be fixable with empty classes since i am not using them it will not touch them:
for doctrine for example src/ORM/Entity.php did the trick togheter with HasLifecycleCallbacks & Table
```php
<?php

namespace ORM;

class Entity {

    public function __construct(){
    }

}
````
btw, feature discover should be on composer.json / composer,lock so you have feature / version available and determine on that, because in which package are those files then located ?

i tried empty classes but it failed because it hits support method.

```php
Error: Call to undefined method Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory::supports() in /Application/vendor/symfony/mailer/Transport.php on line 171
```

You could do method_exist there and on create...

I added support method to the empty classes which returns false so it skips them.,

And created these files:
```
/src/Symfony/Component/EventDispatcher/Event.php (empty class)
/src/Symfony/Component/Mailer/Bridge/Amazon/SesTransportFactory.php (supprts method returns false)
/src/Symfony/Component/Mailer/Bridge/Google/GmailTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Mailchimp/MandrillTransportFactory.php  (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Mailgun/MailgunTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Mailjet/MailjetTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/OhMySmtp/OhMySmtpTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Postmark/PostmarktTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Sendgrid/SendgridTransportFactory.php (supports method returns false)
/src/Symfony/Component/Mailer/Bridge/Sendinblue/SendinblueTransportFacytory.php (supports method returns false)
```

**Comment by stof** [comment]
Creating an empty class does not make sense. `class_exists($factoryClass, false)` would still return `false` for them, because that empty class would not be loaded yet either.
Your requirement of triggering the autoloading only for classes that exist is simply impossible to support from a framework point of view, because the only way to be sure whether a class exist or no is to try loading it.

**Comment by remco-pc** [comment]
what i want to know is the following:

Where can i get those transport factories ? (will solve my issue in development mode in my framework, in production mode it will ignore it)
In my framework i've added those classes, some with the supports method returning false (this will solve the issue). 
You could do this on line 168 of Transport.php: 
```
public function fromDsnObject(Dsn $dsn): TransportInterface
    {
        foreach ($this->factories as $factory) {
            if (method_exists($factory, 'supports') && $factory->supports($dsn)) {
                return $factory->create($dsn);
            }
        }
        throw new UnsupportedSchemeException($dsn);
    }
```
and the classes could be empty (like doctrine does work in development mode due to hijack empty classes for 3 annotations (discovery)). I am thinking of a change in my development state. i could do a log write instead of a thrown exception and implement failed classes like you guys do. (for feature discovery). class_exists($factoryClass, false) is not needed with empty classes. 
from a debugging point of view i've fixed it now with those empty classes. in a way you should / could autoload those classes them from a default directory within the email branch, and if you install them the autoload priority will load the appropriate location then discovery can happen without failures but 2 autoload locations with different priority.
