### ISSUE TITLE
Request not available anymore in custom error page

### ISSUE THREAD

**Issue by bastien-effetb** [symfony/symfony#47553]
### Symfony version(s) affected

4.4

### Description

We override error pages in our projects to show a nicely formated error page to end users, but since the update of symfony/http-kernel to 4.4.45, the request is not available anymore in our twig template, causing some errors and preventing the display of our custom error template.

### How to reproduce

Update symfony/http-kernel to 4.4.45, create an error in any controler, the error page displayed is now the symfony default instead of custom template that needs to access the original request.

### Possible Solution

This commit https://github.com/symfony/http-kernel/commit/15baea58ba30612f3a72fb9da05883c18ee9a078 has made some changes to HttpKernel.php, maybe it should be changed.

### Additional Context

This change to the request management is also referenced in this recent issue : https://github.com/symfony/symfony/issues/47405

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by bastien-effetb** [comment]
I tried to reproduce the problem in a new symfony 4.4 app with no luck, looks like the problem is coming from the way we manage errors in our project (custom Error Listener). I close this issue as the problem is not from symfony
