### ISSUE TITLE
[Console] PHP attributes for arguments and options

### ISSUE THREAD

**Issue by SpiGAndromeda** [symfony/symfony#47554]
### Description

Currently, adding options and arguments can be done in the `configure()` method. The method overrides the base method in the `Command` class. To my mind, this can become ugly.

There already is the `AsCommand` attribute which can be used to register the the class as a command. My suggestion is to implement attributes for arguments and options as well, so they can be used as class attributes.

The attribute itself could be a simple data holder or it could implement the method to add the argument or option to the input itself.
If it's a simple data holder, the arguments and options could be added in the base `configure()` method of the command class.

If there is positive feedback to this suggestion, I will write the code and PR my self.

### Example

The attributes would look like this.
```php
#[AsCommand('the-command-space:some-command')]
#[ConsoleArgument('argument1', InputArgument::REQUIRED, default: 1337)]
#[ConsoleOptiont('option1', null, InputOption::VALUE_REQUIRED, default: 'blub')]
final class SomeCommand extends Command 
{
}
```

**Comment by stof** [comment]
This would force the command to rely on Reflection to read those at runtime, while this metadata is not used outside the class. So I don't really see the improvement over the `configure` method. And I don't see how you would support the completion callback with such attribute-based API.

**Comment by SpiGAndromeda** [comment]
@stof I don't see the point why using reflection is bad. It's already used in the `setCode` method of the `Command` class.
Regarding the completion callback ... I didn't had that in mind. I will look into this.

One benefit is the improved readability. Attributes at the top of a class separate (not logically but in the file structure) actual logic from metadata. It's no functional improvement.

**Comment by SpiGAndromeda** [comment]
@stof The only way to allow callbacks, would be to use non-anonymous methods, to my mind. I see the downside of this, but I still think it would be a nice-to-have feature.

In order to avoid changing the `Command` class code at all, a trait could be used. It's easier to maintain in the Symfony repository because existing code isn't touched. That the attribute can not be used with anonymous callbacks should be obvious for any developer knowing attributes.

**Comment by derrabus** [comment]
I think, the attributes you are proposing could become interesting if we wanted to allow to create commands that don't extend the `Command` base class. But I don't think we have plans to do that at the moment.

**Comment by SpiGAndromeda** [comment]
@derrabus I agree. So this issue can be closed?

**Comment by stof** [comment]
> The only way to allow callbacks, would be to use non-anonymous methods, to my mind. I see the downside of this, but I still think it would be a nice-to-have feature.

the issue is not about anonymous methods or no (nothing forces you to use an anonymous function for the callback btw). The issue is that a callback defined in the attribute cannot depend on the command instance, and so cannot have access to its dependencies.

**Comment by SpiGAndromeda** [comment]
@stof Ok I was a little unprecise. With non-anonymous, I meant to call a method as a callback internally by its name with `call_user_func` for example. Only anonymous functions wouldn't be possible. Or do I get something wrong?

**Comment by stof** [comment]
@SpiGAndromeda to me, this looks a lot more ugly than using a `configure` method to configure the command.

**Comment by SpiGAndromeda** [comment]
@stof Ok than we have a different sense of beauty :sweat_smile:
