### ISSUE TITLE
Command Injection

### ISSUE THREAD

**Issue by Dark-Samurai** [symfony/symfony#47569]
Command Injection

Unsanitized input from an HTTP header flows into shell_exec, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

$dirs = $_SERVER['argv'];
array_shift($dirs);
$mergeBase = trim(shell_exec(sprintf('git merge-base %s HEAD', array_shift($dirs))));

Unsanitized input from an HTTP header flows into system, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

$dirs = $_SERVER['argv'];
array_shift($dirs);
$mergeBase = trim(shell_exec(sprintf('git merge-base %s HEAD', array_shift($dirs))));

$packages = array();
$flags = PHP_VERSION_ID >= 50400 ? JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE : 0;

foreach ($dirs as $k => $dir) {
    if (!system("git diff --name-only $mergeBase -- $dir", $exitStatus)) {
    
Unsanitized input from an HTTP header flows into passthru, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

  }
    echo "$dir\n";

    $json = ltrim(file_get_contents($dir.'/composer.json'));
    if (null === $package = json_decode($json)) {
        passthru("composer validate $dir/composer.json");
        exit(1);
    }
   
.github/build-packages.php 
   
           file_put_contents($dir.'/composer.json', $json);
    }
    passthru("cd $dir && tar -cf package.tar --exclude='package.tar' *");

### How to reproduce

Command Injection

Unsanitized input from an HTTP header flows into shell_exec, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

$dirs = $_SERVER['argv'];
array_shift($dirs);
$mergeBase = trim(shell_exec(sprintf('git merge-base %s HEAD', array_shift($dirs))));

Unsanitized input from an HTTP header flows into system, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

$dirs = $_SERVER['argv'];
array_shift($dirs);
$mergeBase = trim(shell_exec(sprintf('git merge-base %s HEAD', array_shift($dirs))));

$packages = array();
$flags = PHP_VERSION_ID >= 50400 ? JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE : 0;

foreach ($dirs as $k => $dir) {
    if (!system("git diff --name-only $mergeBase -- $dir", $exitStatus)) {
    
Unsanitized input from an HTTP header flows into passthru, where it is used to build a shell command. This may result in a Command Injection vulnerability.

.github/build-packages.php

  }
    echo "$dir\n";

    $json = ltrim(file_get_contents($dir.'/composer.json'));
    if (null === $package = json_decode($json)) {
        passthru("composer validate $dir/composer.json");
        exit(1);
    }
   
.github/build-packages.php 
   
           file_put_contents($dir.'/composer.json', $json);
    }
    passthru("cd $dir && tar -cf package.tar --exclude='package.tar' *");

**Comment by nicolas-grekas** [comment]
Despite the warning before opening the issue, you might have missed our security policy document, so here it is:
https://symfony.com/doc/current/contributing/code/security.html

Please review it and follow the recommendations it contains for your next reports.
TL;DR, publicly reporting a security issue should be avoided. Send them to security@symfony.com instead.

Anyway, I'm closing here because tests are not covered by the security policy. Also, this report misses a vulnerability scenario. Not all calls to eval/etc are dangerous.
