### ISSUE TITLE
Cannot generate lazy proxy for service "knp_paginator" 

### ISSUE THREAD

**Issue by topwebstudio** [symfony/symfony#47563]
### Symfony version(s) affected

6.2

### Description

When using Symfony 6.2-dev branch I've started getting this error, been OK before a week or so.

In LazyServiceDumper.php line 140:

Cannot generate lazy proxy for service "knp_paginator".

and

In ProxyHelper.php line 92:

Cannot generate lazy proxy: class "Knp\Component\Pager\Paginator" is final.

### How to reproduce

Install Knp Paginator bundle with latest 6.2 dev branch of Symfony

### Additional Context

https://github.com/KnpLabs/KnpPaginatorBundle/issues/745

**Comment by nicolas-grekas** [comment]
Fixed in #47564, thanks for the report.

**Comment by topwebstudio** [comment]
It works, thanks!
