### ISSUE TITLE
security-http (LogoutUrlGenerator) error

### ISSUE THREAD

**Issue by krzyc** [symfony/symfony#47577]
### Symfony version(s) affected

4.4.44

### Description

Method generateLogoutUrl of LogoutUrlGenerator throws "Call to a member function getBaseUrl() on null" error.
It can be reproduced by generating error after authenticating as a user. Error is not present after logging out.
Similar issue is described on https://github.com/symfony/symfony/issues/27174
On Symfony 6.1 this problem does not occur on same setup.
Tested using PHP 8.1 (Ubuntu supplied) with built in server.

### How to reproduce

Install symfony/website-skeleton:"^4.4" with dev environment
Add db based authentication
Login
Generate error

### Possible Solution

Checking for null request in LogoutUrlGenerator - there was previously supplied PR which fixes this problem:
https://github.com/symfony/symfony/pull/27175
It was rejected because problem was not reproduced (or should not exist).
But I think that in any case if called function can return null then it should be checked against null before calling its methods.

### Additional Context

Call to a member function getBaseUrl() on null
Exception Stack Trace 
Error
in vendor/symfony/security-http/Logout/LogoutUrlGenerator.php (line 110)
in vendor/symfony/security-http/Logout/LogoutUrlGenerator.php -> generateLogoutUrl (line 64)
in vendor/symfony/security-bundle/DataCollector/SecurityDataCollector.php -> getLogoutPath (line 136)
in vendor/symfony/http-kernel/Profiler/Profiler.php -> collect (line 178)
in vendor/symfony/http-kernel/EventListener/ProfilerListener.php -> collect (line 100)
in vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelResponse (line 126)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 264)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> doDispatch (line 239)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 73)
in vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 168)
in vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 192)
in vendor/symfony/http-kernel/HttpKernel.php -> filterResponse (line 245)
in vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 115)
in vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 129)
in vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 601)
ErrorHandler->handleException()

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by krzyc** [comment]
@xabbuh I have created minimal app to show issue:
https://github.com/krzyc/symfony-issue-47577
Commited with SQLite db - username: admin password: admin

**Comment by specky-rum** [comment]
Hi, fwiw we're getting this error too. I'm getting the exact same error trace as the OP whenever there is a 500 error. 

Some observations:
- It only happens on our development version, not on production. I presume this is because we're not displaying the error pages on production. They are reported correctly to our error log though.
- When this happens on our development version the original error is not logged. 
- It has been happening since we updated Symfony from 4.4.40 to 4.4.44.

**Comment by krzyc** [comment]
@specky-rum Yes, this error happens in process of collecting data for displaying actual error in dev (Web Profiler) environment. SecurityDataCollector tries to get logout URL, but generator throws error because of no request in RequestStack. So there are two problems: why there is no request in RequestStack at this point (some time ago this problem did not exist so maybe it was introduced in some latest versions of Symfony), and why generateLogoutUrl is not checking for null value which is legal return value for getCurrentRequest so it should be handled in my opinion - then SecurityDataCollector will silently fetch thrown Exception as described in comments (fail silently when the logout URL cannot be generated), but only Exceptions are catched, not errors.

**Comment by fnagel** [comment]
Can confirm this issue with symfony/symfony 4.4.45 too.

**Comment by mfreimann** [comment]
I too am experiencing the problem whenever an exception occurs.

**Comment by wouterj** [comment]
Thanks to @krzyc's reproducer and git-bisect, I've been able to track this down to this change: https://github.com/symfony/symfony/pull/47358

This has been identified in another profiler related issue as well: https://github.com/symfony/symfony/issues/47405#issuecomment-1231572367

**Comment by Padam87** [comment]
Also having this issue with 6.1.5

6.1.3 works, thanks @wouterj 

```json
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "<=6.1.3"
        }
    }
```

**Comment by dehy** [comment]
Having this exception in 5.4.13

```
Error:
Call to a member function getBaseUrl() on null

  at /home/adcnx/app-vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:104
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->generateLogoutUrl()
     (/home/adcnx/app-vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:65)
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->getLogoutPath()
     (/home/adcnx/app-vendor/symfony/security-bundle/DataCollector/SecurityDataCollector.php:122)
  at Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector->collect()
     (/home/adcnx/app-vendor/symfony/http-kernel/Profiler/Profiler.php:161)
  at Symfony\Component\HttpKernel\Profiler\Profiler->collect()
     (/home/adcnx/app-vendor/symfony/http-kernel/EventListener/ProfilerListener.php:108)
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:186)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:239)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:109)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException()
     (/home/adcnx/app-vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:131)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}()
     (/home/adcnx/app-vendor/symfony/error-handler/ErrorHandler.php:607)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException()                
```

**Comment by dehy** [comment]
On 6.0.13

```
Error:
Call to a member function getBaseUrl() on null

  at /home/adcnx/app-vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:97
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->generateLogoutUrl()
     (/home/adcnx/app-vendor/symfony/security-http/Logout/LogoutUrlGenerator.php:60)
  at Symfony\Component\Security\Http\Logout\LogoutUrlGenerator->getLogoutPath()
     (/home/adcnx/app-vendor/symfony/security-bundle/DataCollector/SecurityDataCollector.php:114)
  at Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector->collect()
     (/home/adcnx/app-vendor/symfony/http-kernel/Profiler/Profiler.php:151)
  at Symfony\Component\HttpKernel\Profiler\Profiler->collect()
     (/home/adcnx/app-vendor/symfony/http-kernel/EventListener/ProfilerListener.php:108)
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/Debug/WrappedListener.php:111)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/home/adcnx/app-vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:152)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:186)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:239)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
     (/home/adcnx/app-vendor/symfony/http-kernel/HttpKernel.php:109)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException()
     (/home/adcnx/app-vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:125)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}()
     (/home/adcnx/app-vendor/symfony/error-handler/ErrorHandler.php:541)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException()
     (/home/adcnx/app-vendor/sentry/sentry/src/ErrorHandler.php:357)
  at Sentry\ErrorHandler->handleException()   
```

**Comment by SimonVanacco** [comment]
For those on the 5.4.x branch, restricting to 5.4.12 works !

```yaml
  "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "<=5.4.12"
        }
    }
```

(thanks @Padam87 for the idea)

**Comment by wouterj** [comment]
Great to see so many people have found this issue, it means we have many candidates to work on a fix :)

In the other issue, a more in-depth search has been done and the root cause has been found: https://github.com/symfony/symfony/issues/47405#issuecomment-1236095745 (the root cause being that there is no request while collecting data).

Anyone up for a PR to fix the issue?

**Comment by andyexeter** [comment]
@wouterj the SecurityDataCollector already wraps the call to `getLogoutPath` in a try/catch for any `Exception`:

https://github.com/symfony/symfony/blob/8713873fb088e3601b6b58f75129062cd46cd377/src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php#L108-L113

Changing this to catch any `Throwable` resolves the issue for me:

```php
$logoutUrl = null;
try {
    $logoutUrl = $this->logoutUrlGenerator?->getLogoutPath();
} catch (\Throwable) {
    // fail silently when the logout URL cannot be generated
}
```

Would this suffice as a PR if I submitted it?

**Comment by krzyc** [comment]
@wouterj Personally I think that generating proper exception is cleaner then intercepting error - there is a PR already submitted: https://github.com/symfony/symfony/pull/27175/files
For me not checking for null value, which is legal return value (even if it should not be null at that time), is not correct independently from a problem why there is no request - but this PR was rejected.
@xabbuh What do you think about it? Why we should not check for null request value in generateLogoutUrl? Throwing LogicException looks good to me.

**Comment by xabbuh** [comment]
Adding the `null` check works as a first step to me. But we should IMO still fix the underlying issue as currently if I understand this correctly the collector cannot collect all data that it is supposed to be able to collect.

**Comment by curry684** [comment]
For those that, like me, end up in a situation where this is hiding exceptions but you cannot downgrade without breaking other features, just add some code directly in `vendor/symfony/security-http/Logout/LogoutUrlGenerator` at line 97 (for 6.1.5):
```
            $request = $this->requestStack->getCurrentRequest();

            // These lines fix it until your next Composer update
            if (!$request) {
                return 'nobody cares';
            }
            $url = UrlGeneratorInterface::ABSOLUTE_URL === $referenceType ? $request->getUriForPath($logoutPath) : $request->getBaseUrl().$logoutPath;
```

**Comment by krzyc** [comment]
> Adding the `null` check works as a first step to me. But we should IMO still fix the underlying issue as currently if I understand this correctly the collector cannot collect all data that it is supposed to be able to collect.

This problem originates in terminateWithException of HttpKernel. Pushing request to requestStack before calling handleThrowable (https://github.com/symfony/http-kernel/blob/6.1/HttpKernel.php#L109) in terminateWithException function fixes problem. @xabbuh Do you think this is correct solution? (I have submitted a PR). It is called by exceptionHandler from DebugHandlersListener.

Before cited commit #47358 requestStack was not empty because it was popped in finishRequest.

**Comment by fnagel** [comment]
For those on the 4.4.x branch, restricting to 4.4.44 works!

```
  "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "<=4.4.44"
        }
    }
```
