### ISSUE TITLE
AbstractFormLoginAuthenticator::start return type is too restrictive

### ISSUE THREAD

**Issue by AndrolGenhald** [symfony/symfony#47571]
### Symfony version(s) affected

5.4

### Description

When a user is not logged in I want to respond with a 401 response rather than redirecting to the login page for certain AJAX endpoints, but the docblock for `AbstractFormLoginAuthenticator::start` specifies that it must return a `RedirectResponse`. This causes false-positives for static analysis tools.

### How to reproduce

 1. Create a class extending `AbstractFormLoginAuthenticator`, implement `start`, return `new Response("Test", 401)`;
 2. Run Psalm
 3. Psalm reports `MoreSpecificReturnType - src/Security/FormLoginAuthenticator.php:148:94 - The declared return type 'Symfony\Component\HttpFoundation\RedirectResponse' for App\Security\FormLoginAuthenticator::start is more specific than the inferred return type 'Symfony\Component\HttpFoundation\Response'`

### Possible Solution

Update the signature on `AbstractFormLoginAuthenticator::start` to indicate that the return type is `Response` rather than `RedirectResponse`.

**Comment by raziel057** [comment]
It’s the case using the new Authenticator that is available since 5.2 : https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Http/Authenticator/AbstractLoginFormAuthenticator.php

**Comment by wouterj** [comment]
Would you be able to submit a PR changing the return type? Given it doesn't break anything, I'm fine with changing it.

**Comment by AndrolGenhald** [comment]
> It’s the case using the new Authenticator that is available since 5.2 : https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Http/Authenticator/AbstractLoginFormAuthenticator.php

Huh, so it is, I wonder what the relationship is between `AbstractFormLoginAuthenticator` and `AbstractLoginFormAuthenticator`? Looks like one is in security-guard and the other is in security-http, but they seem pretty similar.

> Would you be able to submit a PR changing the return type? Given it doesn't break anything, I'm fine with changing it.

Will do, I'll try to get around to it tomorrow!

**Comment by wouterj** [comment]
> Huh, so it is, I wonder what the relationship is between AbstractFormLoginAuthenticator and AbstractLoginFormAuthenticator? Looks like one is in security-guard and the other is in security-http, but they seem pretty similar.

During Symfony 5.x, the authentication features of the Security component were refactored. This new class must be used when using the new system, the older class must be used when using the legacy system (which is removed from Symfony 6). Some more resources on the new system:

https://symfony.com/blog/new-in-symfony-5-1-updated-security-system
http://wouterj.nl/2020/04/authenticators-new-symfony-security
https://symfony.com/doc/current/security.html
