### ISSUE TITLE
[HttpClient] curl DNS cache (needlessly ?) desactivated 

### ISSUE THREAD

**Issue by yched** [symfony/symfony#47576]
### Symfony version(s) affected

5.4, 6.2

### Description

Curl's DNS cache is explicitly disabled in CurlHttpClient.

```
        if (!\ZEND_THREAD_SAFE) {
            $curlopts[\CURLOPT_DNS_USE_GLOBAL_CACHE] = false;
        }
```

This code has been around since the very first commit in the repo and I could not find a discussion or a rationale for explicitly preventing a DNS cache.

So i'm (naively ?) thinking that maybe the "if" is simply backwards ? The [doc for CURLOPT_DNS_USE_GLOBAL_CACHE](https://www.php.net/manual/en/function.curl-setopt.php) states that the option is not thread safe, so I get why it should not be used when php was compiled for thread-safety and ZEND_THREAD_SAFE is true.
But when ZEND_THREAD_SAFE is false, CURLOPT_DNS_USE_GLOBAL_CACHE should be ok ?

### How to reproduce

with ext-curl enabled, 

```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\HttpClient\HttpClient;

// Each request performs a DNS lookup
$client = HttpClient::create();
$client->request('GET', 'https://example.com/1')->getInfo();
$client->request('GET', 'https://example.com/2')->getInfo();

// Trying to use CURLOPT_DNS_USE_GLOBAL_CACHE is forbidden
$client2 = HttpClient::create([
    'extra' => [
        'curl' => [CURLOPT_DNS_USE_GLOBAL_CACHE => true],
    ],
]);
$client2->request('GET', 'https://example.com/1')->getInfo();
// -> Exception\InvalidArgumentException 'Cannot set "CURLOPT_DNS_USE_GLOBAL_CACHE" with "extra.curl".'
```

### Additional Context

This is an app whos job is to perform HTTP requests in a long-running `messenger:consume` handler.

I'm migrating to a new (cloud) infrastructure where DNS lookup times appear to increase problematically under charge as the # of outgoing request grow - doing the same amount of requests using target server IPs rather than hostnames performs just fine.  We're investigating the platform to find out why DNS lookups do not scale, meanwhile I need to use a DNS cache (I'm querying a limited set of 10-ish targets several times per second, so a lookup on each request is overkill)

php_curl comes with a DNS cache, so I'd much rather use it rather than setting up dnsmasq or the like

**Comment by nicolas-grekas** [comment]
This code exists to always disable the global cache. As stated in the doc:

>  It is conditionally enabled by default if PHP is built for non-threaded

And we don't want this conditional enabling, so we conditionally disable it :)

As stated in [curl's doc](https://curl.se/libcurl/c/CURLOPT_DNS_USE_GLOBAL_CACHE.html), using this option is deprecated and "has no function since 7.62.0. Do not use!", so we'd better remove those lines one day.

Instead, the DNS cache is managed by a curl_share handle, see CurlClientState. This cache lasts for as long as the client instance is used and *not* `reset()`.

This should allow you to build what you want I guess.
I'm closing because the curl doc gives little options IMHO.
Thanks for submitting.

**Comment by yched** [comment]
Thanks a lot for the fast reply @nicolas-grekas

> using this option is deprecated and "has no function since 7.62.0. Do not use!"

Hah ! Ok, thanks for the clarification :-D

The reason for the long lookup times I was seeing in my message consumer was indeed caused by reset_on_message defaulting to true, thus cleaning curl's DNS cache after each message. Setting the --no-reset option for messenger:consume solved the issue :grimacing:
