### ISSUE TITLE
[Routing] Exception/default value required when navigating to route with a optional parameter with "!" character 

### ISSUE THREAD

**Issue by MichaelBelgium** [symfony/symfony#47583]
### Symfony version(s) affected

5.4.8

### Description

This is odd and I'm sure this is not the way to go.

When navigating to a route with an optional parameter that has the "!" character (which means the default value will always be included in the generate function) you're required to pass that default parameter when navigating to it.

Which means the optional parameter doesn't have any purpose. As you're required to type it or it throws a _ResourceNotFoundException_

### How to reproduce

Using the example from the [announcement blogpost](https://symfony.com/blog/new-in-symfony-4-3-always-include-route-default-values)

1. Define the route

```
/**
 * @Route("/blog/{!page}", name="blog_list")
 */
public function list($page = 1)
{
    // ...
}
```

2. Go to /blog
3. Have a ResourceNotFoundException
4. /blog/1 does work but default parameter loses its purpose

**Comment by Tobion** [comment]
I don't think this is a bug. The `!` declarares the parameter as non-optional for matching. So the default value is only used for generating URLs but not for matching.
The reason is explained in https://github.com/symfony/symfony/pull/29599#issuecomment-449748376
