### ISSUE TITLE
QuestionHelper input truncated at 4095 byte

### ISSUE THREAD

**Issue by pbek** [symfony/symfony#47586]
### Symfony version(s) affected

6.2

### Description

When you ask for input with QuestionHelper the input is truncated at 4096 byte.
The maximum line length in unix terminals is 4096. QuestionHelper additionally only reads the first 4096 byte of the input in:

https://github.com/symfony/symfony/blob/1159d133130c1474f16c3a5f44b6c54a0a81e6d6/src/Symfony/Component/Console/Helper/QuestionHelper.php#L431

### How to reproduce

```bash
# Enter a very long string here
php bin/console secrets:set CERT_P12
```

```php
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $errOutput = $output instanceof ConsoleOutputInterface ? $output->getErrorOutput() : $output;
        $io = new SymfonyStyle($input, $errOutput);

        $value = $io->askHidden('Please type the secret value');
    }
```

See:
https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Bundle/FrameworkBundle/Command/SecretsSetCommand.php#L99

The content of `$value` is truncated to 4095 byte when you enter a text longer than that.

### Possible Solution

Maybe a warning should be printed when an input has exactly 4095 characters to alert the user that there is the possibility that something was truncated.

### Additional Context

**Use case:**
We use the Symfony CLI to set secrets (SecretsSetCommand, `secret:set`). We have very long strings, like base64 encoded certificates in our secrets.

**Comment by pbek** [comment]
https://github.com/symfony/symfony/pull/47587 would add a warning in `SecretsSetCommand`.

**Comment by pbek** [comment]
https://github.com/symfony/symfony/pull/47588 would add a warning in `QuestionHelper`.

**Comment by pbek** [comment]
Just a note: If #47588 would get accepted, #47587 is redundant and can be ignored.

**Comment by fabpot** [comment]
@pbek Can you do everything in the same PR? That would help with the reviews and ensure that it's all consistent. Thank you.

**Comment by pbek** [comment]
@fabpot, #47588 is the one PR that would solve the matter at the source of the problem. If it's ok to solve the matter at the source and not only in SecretsSetCommand, I'd close #47587.
