### ISSUE TITLE
[Security][DX] Deprecate/warn having the security bundle loaded, but not having any config

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#47593]
### Symfony version(s) affected

5.4.11

### Description

Currently, if you don't have any security config, the Security bundle skips loading any of its conifg:

https://github.com/symfony/symfony/blob/308edb55684f7afb3670414a6a69443551bf2e4d/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L90-L92

This can lead to weird errors like:
```
Did you forget to run "composer require symfony/twig-bundle"? Unknown function "is_granted" in "template.html.twig".
```

The developer is left to debug why Twig bundle is not being loaded, why the Security bundle is not loaded (they both are) (I'd argue that this itself is a bug).

### How to reproduce

1. Create a new symfony project
2. don't define any security
3. try to use some security related feature (like the mentioned Twig function) and see the error message

### Possible Solution

- warn about security not having any config (AFAIK it needs at least one firewall)
- load some (most) services into the container even without the config

### Additional Context

This happens if you're setting up a tiny Symfony app for functional tests where you need the smallest working config, you might omit things you're not directly interested in, but that can have unintended consequences which are hard to debug.

**Comment by chalasr** [comment]
👍 I can't recall any decision regarding this and I can't find anything in the history that justifies it.
Making it throw is likely to break some setups at least in test, which is not desired on a LTS version. I would handle this as a DX enhancement and trigger a deprecation notice at first.
