### ISSUE TITLE
Symfony Rout Requirements not working as expected for Requirement::DATE_YMD

### ISSUE THREAD

**Issue by josep11** [symfony/symfony#47599]
### Symfony version(s) affected

6.1.4

### Description

I am using the parameter from the route and trying to build a `DateTimeImmutable` object.

`Failed to parse time string (2022-09-019) at position 10 (9): Unexpected character`

This is because the Route requirements are not working as expected.

The expected result is that it should fail when we provide a date in an invalid format with the expected regex validation. More precisely, If we provide these values for the querystring parameter it doesn't fail and it should:

- 2022-09-0          
- 2022-09-019     

### How to reproduce

Inside a controller add the following method:

```php


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Requirement\Requirement;

class HitCounterController extends AbstractController
{

#[Route(
        '/hit-counter',
        name: 'hitcounter_detail',
        requirements: [
        'logDate' => Requirement::DATE_YMD,
        'domain' => '.+',
    ],
        methods: 'GET'
    )]
    public function getExceedAtcHits(Request $request): JsonResponse
    {
         $logDateStr = $request->query->get('logDate');
         new DateTimeImmutable($logDateStr);
     }
   
}
```

Then try the following requests:

GET https://local.co/api/v1/hit-counter/exceed-atc?logDate=2022-09-0&domain=google.com

GET https://local.co/api/v1/hit-counter/exceed-atc?logDate=2022-09-019&domain=google.com

GET https://local.co/api/v1/hit-counter/exceed-atc?logDate=2022-09-01&domain=google.com

The latter is the only one that should work.

**Comment by stof** [comment]
You are getting the logDate from the query string, not from an attribute matched in the path. So requirements don't apply at all in your case.

**Comment by raziel057** [comment]
For this use case, or to get values from request params, it would be great to have a ``getForRequirement`` method like suggested here: https://github.com/symfony/symfony/issues/47575

So you could just write:
```php
$logDateStr = $request->query->getForRequirement('logDate', Requirement::DATE_YMD);
```

If it doesn't matches the requirement, a 400 Bad Request is thrown. What do you think about this idea?

**Comment by stof** [comment]
Closing this as there is no bug in the requirements, but a misunderstanding of what route requirements are for.
