### ISSUE TITLE
 Authenticator does not support the request. when using reverse proxy path

### ISSUE THREAD

**Issue by novotnicek** [symfony/symfony#47633]
### Symfony version(s) affected

6.1.4

### Description

Authenticator does not support the request. when using reverse proxy path

I'm not sure, if is really bug. I thinking about some improvement.

### How to reproduce

apache2 VirtualHost configuration:
```
<VirtualHost *:443>
  ServerName example.local
  DocumentRoot /var/www/html/app/static

  Alias /app /var/www/html/app/public
  <Directory /var/www/html/app/public>
    DirectoryIndex index.php
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  SSLEngine on
  SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
  SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

  <FilesMatch "\.(cgi|shtml|phtml|php)$">
    SSLOptions +StdEnvVars
  </FilesMatch>
  <Directory /usr/lib/cgi-bin>
    SSLOptions +StdEnvVars
  </Directory>
</VirtualHost>
```

`config/services.yaml`:
```
parameters:
  router.request_context.host: '%env(APP_DOMAIN)%'
  router.request_context.base_url: '%env(APP_BASE_URL)%'
```

my `.env` file:
```
APP_DOMAIN=example.local
APP_BASE_URL=app
```

### Possible Solution

possible solution is make my own supports() function in my own Authenticator
```
    public function supports(Request $request): bool
    {
        dump($this->getLoginUrl($request)); // return "/app/login"
        dump($request->getPathInfo());      // return "/login"

        // return $request->isMethod('POST') && $this->getLoginUrl($request) === $request->getPathInfo();
        return $request->isMethod('POST');
    }
```

original function is here: https://github.com/symfony/security-http/blob/c2d2e1b388c241992f50d7468bc4a3000b4a44cd/Authenticator/AbstractLoginFormAuthenticator.php#L42

### Additional Context

![image](https://user-images.githubusercontent.com/4188470/191308969-8fdf4d55-92eb-4d7b-8892-13f62da8fc29.png)

**Comment by wouterj** [comment]
This is a duplicate of #44893
