### ISSUE TITLE
[RFC] $request->body->get

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#47646]
### Description

Hi,

I'd like to propose `$request->body->get()` (an `InputBag`) to provide uniform access to a structured request body payload, regardless of content-type.

`$request->request` always looked weird to me, and is bound to `$_POST`, thus `application/x-form-urlencoded`:

https://github.com/symfony/symfony/blob/ed1b002bacf60b003a2ffcdd07e78f1d1bf0773f/src/Symfony/Component/HttpFoundation/Request.php#L293

Then for `application/json` one needs `toArray()`:
https://github.com/symfony/symfony/blob/ed1b002bacf60b003a2ffcdd07e78f1d1bf0773f/src/Symfony/Component/HttpFoundation/Request.php#L1502

### Example

```php
$request->body = new InputBag($_POST ?: $request->toArray());
```

**Comment by ro0NL** [comment]
this is not about adding support for XML, YAML, etc. though i'd fundamentally agree it should be possible to add later

ideally the parsing happens in a lazy manner, thus a LazyInputBag or so

**Comment by rvanlaak** [comment]
I also remember this being quite confusing when I started working with Symfony back then, especially as the variable itself most often is named `$request` already.

**Comment by kbond** [comment]
@symfony/mergers any thoughts on this. I really like the idea. I think it's common to want to get the array of data from a request and not care if it's a form request or json.

My only hesitation is the name `body` - it doesn't necessarily imply this will be a structured array.

One idea @ro0NL had is to perhaps deprecate `Request::getContent()` in favour of `Request::getRawBody()`. I've often looked for a `Request::getBody()` to get the raw body before finding it's actually `Request::getContent()`. Additionally, maybe `Request::$request` could be deprecated in favour of `Request::$form`?

**Comment by welcoMattic** [comment]
I would love to clarify the `$request->request` thing, it was confusing to me when I started to code with Symfony too :+1:

**Comment by chalasr** [comment]
I agree as well that it’s worth renaming.

**Comment by OskarStark** [comment]
> I agree as well that it’s worth renaming.

Me too 👍

**Comment by maxbeckers** [comment]
I like the idea of renaming `$request->request`. But why form? This sounds to me as well confusing, because its maybe formdata, but not the form. I'd prefer to name it `body` or maybe `data`, because it's the posted data of the request.

**Comment by kbond** [comment]
This issue has sort of morphed into three things.

1. A new property (`$body`) that represents either the `$_POST` data or json request body (the initial part of this issue).
2. Renaming the `$request` property (which is a wrapper for `$_POST`) to something else (#47938). I chose `$form` because this is what `$_POST` represents, [the _form data_](https://www.php.net/manual/en/reserved.variables.post.php). I'm not completely convinced that `$form` is the best term (it's better than `$request` IMO) - maybe `$post` would be better?
3. Renaming `Request::getContent()` to `getRawBody()`.

**Comment by maxbeckers** [comment]
Yes, you are absolutely right. There are exactly these 3 topics here in this issue. Thanks for clarifying.
And yes you are right, from the naming point of view body doesn't really fit well then either. `$post(Data)` also sounds a bit strange to me, but yeah, maybe it's best to name it that way.
Better than request it is in any case.

**Comment by chalasr** [comment]
> I'm not completely convinced that $form is the best term (it's better than $request IMO) - maybe $post would be better?

My preference goes for ` body`, I think it's the the most consistent with PHP and HTTP terms:

**Comment by kbond** [comment]
> My preference goes for body, I think it's the the most consistent with PHP and HTTP terms:

Now, do you think `$body` should be `new InputBag($_POST ?: $this->toArray())` as initially described by this issue or a straight up rename of `$request`?

**Comment by GromNaN** [comment]
> Now, do you think `$body` should be `new InputBag($_POST ?: $this->toArray())` as initially described by this issue or a straight up rename of `$request`?

I would love if `$request->body` could be populated equally from `x-www-form-urlencoded` or `application/json` requests. Adding a new property is the right opportunity to do so.

For backward-compatibility, we cannot do the same for `$request->request`. Thus, they needs to be distinct objects.

**Comment by ro0NL** [comment]
i understand if this is too disruptive

also i realized for us the better path is to deserialize requests into dedicated (message) DTOs, and dispatch from there

**Comment by wouterj** [comment]
I think we should keep this issue open, or at least close as completed.

We have an open PR about this (#47938) that we should continue, we can do this in a non disruptive way.
