### ISSUE TITLE
[Uid] Make AbstractUid::__toString() return non-empty-string

### ISSUE THREAD

**Issue by webignition** [symfony/symfony#47645]
### Description

I like where possible to use the `non-empty-string` pseudo-type (understood by phpstan and psalm) when dealing with strings that should never be empty.

Casting `AbstractUid`-derived instances to a string will always result in a non-empty string, however there is nothing to indicate that this is so.

I feel it should be safe to annotate `AbstractUid::__toString()` to indicate that it always returns a non-empty string:

```php
/**
 * @return non-empty-string
 */
public function __toString(): string
{
    return $this->uid;
}
```

Doing so would not change anything (a non-empty string is always returned) and would allow me to remove redundant string emptiness checks after casting to string.

I'm happy to create a PR for this, mostly I want to check that this is a suitable change as I'm not sure how widespread within the codebase is the use of the `non-empty-string` pseudo-type.

**Comment by chalasr** [comment]
👍 for me

**Comment by chalasr** [comment]
Closing as explained in #47648.
