### ISSUE TITLE
[Dotenv] Dotenv::resolveCommands may create Process instance using wrong parameter type for first argument (string vs. array)

### ISSUE THREAD

**Issue by k00ni** [symfony/symfony#47664]
### Symfony version(s) affected

6.1.4, 6.2

### Description

In some cases method `resolveCommands` of `Dotenv.php` may [try to create an instance](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Dotenv/Dotenv.php#L449) of `Process` with a string as first argument, but constructor of `Process` [requires an array](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Process/Process.php#L143).

I didn't run into any error messages, only noticed it after VS Code reported this problem. Might worth to take a deeper look?

### How to reproduce

Because I didn't run into any problems, I have no example code. Based on the code from https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Dotenv/Dotenv.php#L436 it could be triggered with commands in an ENV file, but I am not sure. I never use such functionality.

In my opinion its a clear case, because argument types don't match and PHP will throw an exception, most likely.

**Comment by xabbuh** [comment]
The code itself is fully functional. On versions of the Process component where the `fromShellCommandline()` method does not exist, the constructor itself supports passing the command to be executed as a string. #47748 however will clean things up a bit when being merged.
