### ISSUE TITLE
Integrate Plivo Transport for SMS into Notifier

### ISSUE THREAD

**Issue by paulferrett** [symfony/symfony#47671]
### Description

Hi there! I've written a [Plivo Transport](https://github.com/RentBetter/plivo-notifier) for the Notifier component for integrating into <https://www.plivo.com/>.

If you'd be interested in including in the core, I'd be happy to make any changes you'd like to see before inclusion.

**Comment by Seb33300** [comment]
Hello @paulferrett 

You are welcome to open a pull request if you want this feature to be integrated to the next Symfony version.
If any change is required, it will be suggested during the PR review.

See https://symfony.com/doc/current/contributing/code/pull_requests.html

**Comment by fabpot** [comment]
@paulferrett Feel free to contribute support as a PR.
Closing in the meantime.
