### ISSUE TITLE
Filesystem::doRemove() $isRecursive parameter has no purpose

### ISSUE THREAD

**Issue by tiller1010** [symfony/symfony#47670]
### Symfony version(s) affected

v5.4.12 - 6.x

### Description

When using the Filesystem `remove` method on a directory, `doRemove` always gets called with `$isRecursive` set to "false", but the entire directory is deleted anyway, regardless of what is passed in.

The issue **is not** that the entire directory is deleted, that much makes sense, but that the parameter seemingly does nothing.

In fact, when "false" is passed in for `$isRecursive`, the directory is temporarily renamed, and it cannot be deleted without an error. `$lastError` gives "Text file busy" after the rename: https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Filesystem/Filesystem.php#L191
This error **does not** show if I [manually set the argument to "true"](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Filesystem/Filesystem.php#L150).

### How to reproduce

- Change the second argument to true https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Filesystem/Filesystem.php#L150

- Delete some directory with files
```
$fs = new Filesystem();
$fs->remove('somedirectory');
```
- Notice all files are deleted

### Possible Solution

Remove the parameter and the code that listens to it https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Filesystem/Filesystem.php#L163

### Additional Context

<img width="583" alt="stack-trace" src="https://user-images.githubusercontent.com/42498429/191853078-514a2009-39b1-45aa-ae16-cd530732344b.PNG">

**Comment by domthomas-dev** [comment]
Hi,

Codebase is correct. `$isRecursive` is an internal parameter to know how we use this method

The parameter `$isRecursive` is not use to say : "Do it recursively", but it's use to say "I'm in a recursive call".

Cc @nicolas-grekas in afup :)

**Comment by stof** [comment]
@thomasdominic is right here.
