### ISSUE TITLE
egulias/email-validator not being installed when installing symfony/symfony by "composer require symfony/synfony:^5.4"

### ISSUE THREAD

**Issue by rafa0805** [symfony/symfony#47689]
### Symfony version(s) affected

5.4.*

### Description

egulias/email-validator, which is a package required by [symfony/mailer](https://packagist.org/packages/symfony/mailer#v5.4.12), is not installed when installing symfony components via next command:

`composer require symfony/symfony:^5.4`

Thus next error is being arised when trying to send email using symfony/mailer:

> The "Symfony\Component\Mime\Address" class cannot be used as it needs "Egulias\EmailValidator\EmailValidator"; try running "composer require egulias/email-validator".

### How to reproduce

1. install symfony components: `composer require "symfony/symfony:^5.4"`
2. then you can notice there is no directory named egulias installed under vendor/

**Comment by derrabus** [comment]
Yes, you have to install this package yourself. Also, please don't use the monorepo as a dependency anymore. Use e.g. `symfony/mime` as a dependency if you want to use the MIME component.

**Comment by rafa0805** [comment]
@derrabus , thanks a lot for taking time to check the problem I'm facing!
When you say monorepo in this context, do you mean symfony/symfony, in which lot of  symfony components is bundled together?

Being my understanding correct, is it possible to inform us from which version of symfon that way of installation is not supported? This information will be very useful to us, because we have several projects running with different symfony versions.

**Comment by stof** [comment]
Using standalone component packages is the recommended way to use Symfony since 4.0.

**Comment by rafa0805** [comment]
> Also, please don't use the monorepo as a dependency anymore. Use e.g. symfony/mime as a dependency if you want to use the MIME component.

> Using standalone component packages is the recommended way to use Symfony since 4.0.

Well understood.
Thanks a lot gents for your help!
