### ISSUE TITLE
[Notifier] [Discord] 400 HTTP response due to embed length

### ISSUE THREAD

**Issue by ToshY** [symfony/symfony#47688]
### Symfony version(s) affected

6.1.4

### Description

Currently the Discord chatter only checks length of message based on the [subject length](https://github.com/symfony/discord-notifier/blob/0410309979e9fa2bcdd711c9a67acfc9d70c06ab/DiscordTransport.php#L70). This not completely correct, as it is valid to provide an empty string as subject and instead use embeds.

Currently if one would use embeds, and does not take into consideration the (vague) limits of Discords message lengths, you will get a 400 status code, with very unclear exception:

```
Handling "Symfony\Component\Notifier\Message\ChatMessage" failed: Unable to post the Discord message: "" (embeds: 0).
```

### How to reproduce

Example error transport.

```php
/**
 * @param string $transport
 * @param DiscordFieldEmbedObject $discordFieldEmbedObject
 * @param Exception|null $exception
 * @return void
 * @throws TransportExceptionInterface
 */
protected function errorTransport(string $transport, DiscordFieldEmbedObject $discordFieldEmbedObject, ?Exception $exception = null): void
{
    $chatMessage = new ChatMessage('');
    $discordOptions = (new DiscordOptions())
        ->addEmbed(
            (new DiscordEmbed())
                ->color(hexdec('f44336'))
                ->title(sprintf('Transport error on `%s`', $transport))
                ->addField(
                    $discordFieldEmbedObject
                        ->name(ucfirst('error'))
                )
                ->addField(
                    (new DiscordFieldEmbedObject())
                        ->name('Exception')
                        ->value(
                            $exception !== null ? $exception->getMessage() : 'No error message available.'
                        )
                )
                ->addField(
                    (new DiscordFieldEmbedObject())
                        ->name('Trace')
                        ->value(
                            $exception !== null ? $exception->getTraceAsString() : 'No trace available.'
                        )
                )
                ->timestamp(new DateTime())
        );


    $chatMessage->options($discordOptions)->transport(self::EXCEPTION_TRANSPORT);
    $this->chatter->send($chatMessage);
}
```

Where `$exception->getMessage()` has well over 1024 characters.

### Possible Solution

1. This [documentation](https://www.pythondiscord.com/pages/guides/python-guides/discord-embed-limits/) shows the limits for the embed fields:

* Embed title is limited to 256 characters
* Embed description is limited to 4096 characters
* An embed can contain a maximum of 25 fields
* A field name/title is limited to 256 character and the value of the field is limited to 1024 characters
* Embed footer is limited to 2048 characters
* Embed author name is limited to 256 characters
* The total of characters allowed in an embed is 6000

Validation for character length on embeds should be added. An exception should be thrown if a specific field of the embed is too long.

2. There also should be an option or flag to cut-off the text to `X` characters instead of throwing an exception. This makes sure that the message is always delivered.
3. Update the documentation for [symfony/discord-notifier](https://github.com/symfony/discord-notifier), clearly stating the character limits.

### Additional Context

A current workaround for me at the moment is adding a truncate method and use that on every field value.

```php
private function truncate(string $text, int $cutoff = 1024)
{
    return mb_strimwidth($text, 0, $cutoff, "...");
}
```

**Comment by alamirault** [comment]
Thanks for your great reporting and possible solutions !

I created PR https://github.com/symfony/symfony/pull/47859  based on proposition one (Check and throw exception)
