### ISSUE TITLE
[Validator] EmailValidator in html5 mode does not match actual html validator

### ISSUE THREAD

**Issue by Sajito** [symfony/symfony#47712]
### Symfony version(s) affected

6.1.4, but actually every version since html5 mode introduction

### Description

There is a small mismatch between the html5 regex in symfony/validator and the example regex listed on MDN (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#basic_validation) or whatwg (https://html.spec.whatwg.org/dev/input.html#email-state-(type=email)).

https://github.com/symfony/validator/blob/14ec426b9c8ca8cf02bd863a645fb0cc0d73db79/Constraints/EmailValidator.php#L27

It's only the last quantifier. While MDN and whatwg both use an asterisk (*) as last quantifier, the EmailValidator uses a plus (+).
This causes html to allow email addresses without a tld, while the EmailValidator disallows them.

### How to reproduce

Just compare the tests of both regexes:
https://3v4l.org/aRdqA#v8.1.10

The mdn regex allowed email addresses without a tld, such as "test@localhost". The one in the EmailValidator disallows them.

### Possible Solution

Since email addresses with a tld-less domain are actually valid, I propose to update the regex for the html5 validator.

I have not created a PR yet, but might create one. Reasoning for not creating it yet is, I'm unsure about the target version.
In my opinion this would be a bugfix, but it's also a breaking change, since it would allow email addresses which were disallowed until now.
Also I would propose to allow domains without tld for loose mode, but I'd like to discuss that first.

So my questions are:
Which branch should a PR target?
Is anyone against allowing tld-less domains when using "loose" mode?

**Comment by guillemfondin** [comment]
Hi @Sajito 

After discussion with @nicolas-grekas, it's a difficult choice :
* The official specification [see here](https://www.w3.org/TR/2012/WD-html-markup-20120329/input.email.html#input.email.attrs.value.single) agrees with you, and I think it's good to follow standards.
* But, in general, for public common usage, developers may not need to give users this liberty. (Except for specific use case, (internal email for eg) in companies) 
* A solution could be to add an option for accept or not tld ?

**Comment by Sajito** [comment]
I do understand there might be little common usage for email addresses without tld, I can even imagine (still just a feeling though), that a lot of developers actually intend to block email addresses without a tld.
Yet I think that shouldn't be part of this validator. In my opinion that's why there are different modes for email validation.

There is "loose" mode, which just checks if there is an "@" and even checks for a dot in the domain, therefore also disallowing domains without tld.
Then there is the "strict" mode, which actually checks if the email address matches RFC5322 and might even check if the address actually exists.
And there is the "html5" mode, which claims to use the same regular expression as the browser and even contains a link to that expression (https://symfony.com/doc/current/reference/constraints/Email.html#mode), but in fact does not use the same regular expression (since there is a small change) and therefore does not make the backend validation consistent with the browser.

That last point is what this report is about. At the moment the check does not match the name and description, of what it should do.
So I think either the description of that mode should be updated and have a note on that change, or the default behaviour should change. Honestly in the former case I think the name should be changed.

To be clear, I'm not against having options. It's just that I think having something claim it's the same as something else, but then not doing exactly does same, feels a bit off.

**Comment by guillemfondin** [comment]
Totaly agree with you. 

But, if we change the name of the mode (and the const), it will break the BC promise...

I'm working on a DOC PR, to improve and detail different modes.

Also, "loose" mode is deprecated in v6.2

**Comment by Sajito** [comment]
I know about the BC implication, that's why I didn't start with a PR. Although one might argue, that a bug (which this totally is, at least in my opinion) should not be covered by the BC promise.

I was going to create a PR, but have seen you created one a few minutes ago, so I'd share another suggestion here first.

Instead of adding a new mode and keeping the "faulty" "html5"-mode, we might introduce an additional boolean flag to the Email-Annotation.
Based on that flag either the current or the correct regular expression would be used.
The flag will be nullable. If the flag is null, which it would be by default, the current behaviour is used and a deprecation notice would be triggered.
This way with the default behaviour could be changed to actually match the browser validation in the next feasible release, without breaking the BC promise.

I could send a PR with my proposed changes, I just don't want to do this without discussion, as I have seen you already opened a PR.

**Comment by guillemfondin** [comment]
It's another approach, but why not :)

I'm currious to have other points of view (cc @nicolas-grekas) ?

**Comment by Sajito** [comment]
I tried to implement my suggestion and realized it's not as easy as I thought, without removing the EMAIL_PATTERNS const.

I've got another idea to allow transitioning the html5 mode to actual mode, but it involves adding a parameter which would immediately be marked as deprecated, as it's only purpose would be to allow suppressing the deprecation warning, if the new behaviour is intended.

Before implementing that, I'd also like to have another point of view :)

**Comment by guillemfondin** [comment]
@Sajito just created PR for docs, do you have some suggestion ? 

See also [here](https://github.com/symfony/symfony/pull/47872#pullrequestreview-1144401154) to have another point of view :)
