### ISSUE TITLE
UUIDs and ULIDs return different formats when typecast as a string

### ISSUE THREAD

**Issue by NotionCommotion** [symfony/symfony#47717]
### Symfony version(s) affected

6.1.4

### Description

UUIDs and ULIDs have identical methods for converting to string and each method returns the same format for both UUIDs and ULIDs, however, when typecast as a string, UUIDs return RFC4122 and ULIDs return Base 32.  Not sure whether this should be considered a bug or a feature request, however, regardless believe they should return the same format (probably RFC4122).

### How to reproduce

```php
use Symfony\Component\Uid\Ulid;
use Symfony\Component\Uid\Uuid;

$uid = $context['filters']['uid'];
$uuid = Uuid::fromString($uid);
$ulid = Ulid::fromString($uid);

printf('%-20s %s'.PHP_EOL.PHP_EOL, 'Provided', $uid);

printf('%-20s %-50s %s'.PHP_EOL, 'Format', 'UUID', 'ULID');
printf('%-20s %-50s %s'.PHP_EOL, 'toBinary()', bin2hex($uuid->toBinary()), bin2hex($ulid->toBinary()));
printf('%-20s %-50s %s'.PHP_EOL, 'toBase32()', $uuid->toBase32(), $ulid->toBase32());
printf('%-20s %-50s %s'.PHP_EOL, 'toBase58()', $uuid->toBase58(), $ulid->toBase58());
printf('%-20s %-50s %s'.PHP_EOL, 'toRfc4122()', $uuid->toRfc4122(), $ulid->toRfc4122());
printf('%-20s %-50s %s'.PHP_EOL, '(string)', (string) $uuid, (string) $ulid);
```
```
Provided             01GE2EV7Y39WWQ6HEPCHGHCDHX

Format               UUID                                               ULID
toBinary()           018384ed9fc34f397345d6646116363d                   018384ed9fc34f397345d6646116363d
toBase32()           01GE2EV7Y39WWQ6HEPCHGHCDHX                         01GE2EV7Y39WWQ6HEPCHGHCDHX
toBase58()           1Bqp73W7R7b34PWenSQnSx                             1Bqp73W7R7b34PWenSQnSx
toRfc4122()          018384ed-9fc3-4f39-7345-d6646116363d               018384ed-9fc3-4f39-7345-d6646116363d
(string)             018384ed-9fc3-4f39-7345-d6646116363d               01GE2EV7Y39WWQ6HEPCHGHCDHX
```

**Comment by wouterj** [comment]
I would say this is intentional (and thus not a bug nor a feature).

The [formal representation of a ULID](https://github.com/ulid/spec#specification) is base32:

> ```
>  01AN4Z07BY      79KA1307SR9X4MV3
> 
> |----------|    |----------------|
>  Timestamp          Randomness
>    48bits             80bits
> ```
>
> [...] Crockford's Base32 is used as shown. This alphabet excludes the letters I, L, O, and U to avoid confusion and abuse.

Whereas it is RFC4122 for UUID, as per [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122):

> The formal definition of the UUID string representation is provided by the following ABNF [7]:
> 
>     UUID                   = time-low "-" time-mid "-"
>                            time-high-and-version "-"
>                            clock-seq-and-reserved
>                            clock-seq-low "-" node
>     time-low               = 4hexOctet
>     time-mid               = 2hexOctet
>     time-high-and-version  = 2hexOctet
>     clock-seq-and-reserved = hexOctet
>     clock-seq-low          = hexOctet
>     node                   = 6hexOctet
>     hexOctet               = hexDigit hexDigit
>     hexDigit =
>         "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9" /
>         "a" / "b" / "c" / "d" / "e" / "f" /
>         "A" / "B" / "C" / "D" / "E" / "F"
> 
> The following is an example of the string representation of a UUID as a URN:
> 
>     urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6

---

If you need a specific format (or just as a general remark), I would not rely on a string cast but call the method for that specific format explicitly (e.g. `->toRfc4122()`).

**Comment by NotionCommotion** [comment]
@wouterj I see your point and expect you are correct.  My objective was related to https://github.com/api-platform/core/issues/5021, and now feel this is not the answer.  Appreciate your comment.

**Comment by NotionCommotion** [comment]
It appears that wouterj is correct and there is no bug or needed feature enhancement.
