### ISSUE TITLE
Add constants for RFC 8631 to WebLink component

### ISSUE THREAD

**Issue by someniatko** [symfony/symfony#47716]
### Description

[RFC 8631 - Link Relation Types for Web Services](https://www.rfc-editor.org/rfc/rfc8631) introduces `service-doc`, `service-desc`, `service-meta`, `status` rel types, which could be added as constants to the [Link](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/WebLink/Link.php) class.

### Example

`service-desc`, for instance, is useful for providing a link to the OpenAPI documentation of a web service.

**Comment by nicolas-grekas** [comment]
Good idea. Up to end a PR to add them?
