### ISSUE TITLE
The file <class> doesn't exist in services.yaml.

### ISSUE THREAD

**Issue by abelardolg** [symfony/symfony#47725]
### Symfony version(s) affected

5.4

### Description

I have this code:
https://github.com/abelardolg/ipglobal

When I run it in local, this message is showed:
![image](https://user-images.githubusercontent.com/22522883/193014795-5a3de7dd-6fdd-4ba6-9573-499ac63f6bf0.png)

I don't understand why it is showed when my controller (BlogListController) is placed under the rigth directory.

A clue: when I click here:
![image](https://user-images.githubusercontent.com/22522883/193015045-6086f86e-d1f0-47d3-b503-dec4612a0d31.png)
PHPStorm shows this class

### How to reproduce

Please, git clone my above repo and follow the steps indicated in the README.md file.

### Additional Context

Screenshots are included inside the explanation section along with the text to give you more context about this issue.

**Comment by stof** [comment]
there is no file `../src/BlogList/Infrastructure/Http/BlogListController`. The file is `../src/BlogList/Infrastructure/Http/BlogListController.php`

**Comment by stof** [comment]
based on your  provided base namespace, I think the resource should actually be either `../src/BlogList/Infrastructure/Http/` (to import the whole folder) or `../src/BlogList/Infrastructure/Http/BlogListController.*` (to import only that file as a glob) or you should not use a class-discovery mechanism at all but define the service for that class directly.

**Comment by abelardolg** [comment]
If I would change to ....php", this message is showed:
![image](https://user-images.githubusercontent.com/22522883/193018096-9a7393fa-82e8-452c-9113-2946775884a4.png)

![image](https://user-images.githubusercontent.com/22522883/193018146-951072de-b374-4448-b216-035ae86df18e.png)

Why does Symfony tell me "is not callable"?

**Comment by abelardolg** [comment]
Thanks, the first option was successfully.
