### ISSUE TITLE
Serializer thrown exception when property have "class-string<>" annotation 

### ISSUE THREAD

**Issue by tygygydyk** [symfony/symfony#47736]
### Symfony version(s) affected

5.4

### Description

When a class have a property annotated with `class-string<>` or `string&class-string<>` serializer throws an exception:

 `Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "..." attribute for class "..." must be one of "class-string<...>" ("string" given).`
 

### How to reproduce

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader;
use Doctrine\Common\Annotations\AnnotationReader;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

interface SomeInterface {
    public function get(): void;
}
class SomeClass implements SomeInterface {
    public function get(): void {}
}
class FooBar {
    /**
     * @var class-string<SomeInterface>
     */
    private $foo;

    /**
     * @param class-string<SomeInterface> $foo
     */
    public function __construct(string $foo) {
        $this->foo = $foo;
    }

    /**
     * @return class-string<SomeInterface>
     */
    public function getFoo(): string
    {
        return $this->foo;
    }
}

$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$serializer = new Serializer([
    new DateTimeNormalizer(),
    new ArrayDenormalizer(),
    new ObjectNormalizer($classMetadataFactory, null, null, new PhpDocExtractor()),
], [new JsonEncoder()]);

$serializer->deserialize('{"foo": "'.SomeClass::class.'"}', FooBar::class, 'json', [AbstractObjectNormalizer::SKIP_NULL_VALUES => true]);
```

**Comment by derrabus** [comment]
Does it work if you use `PhpStanExtractor` instead of `PhpDocExtractor`?

**Comment by astronom** [comment]
> Does it work if you use `PhpStanExtractor` instead of `PhpDocExtractor`?

It does not matter of extractor because both `PhpDocTypeHelper` and `PhpStanTypeHelper` from symfony/property-info did not recognize `class-string` as `string` and fallback to `object`

**Comment by xabbuh** [comment]
I think the reason for that is that support for the pseudo-types was introduced with #44451 in 6.1.

**Comment by astronom** [comment]
> I think the reason for that is that support for the pseudo-types was introduced with #44451 in 6.1.

and seems there is no plans to backport it to 5.4 branch?

**Comment by derrabus** [comment]
No, we don't do that. You'll have to upgrade or write your own extractor.
