### ISSUE TITLE
Using Infection for Mutation Testing

### ISSUE THREAD

**Issue by y4roc** [symfony/symfony#47743]
### Description

I would use Mutation Testing to see if all tests cover all eventualities. This also helps us to increase the code quality of Symfony.

What are your thoughts on this topic?

**Comment by maxbeckers** [comment]
Sounds useful to me to improve the tests and possibly also identify bugs faster.

Maybe https://github.com/infection/infection is a tool to implement this.

**Comment by wouterj** [comment]
My vote would be :-1: here.

It may be useful for some very specific cases, but this is best to be kept locally when creating a critically important contribution. Enabling the metric globally in the Symfony repository means that we'll probably be flooded by contributions that add tests to only "please" Infection, which significantly increase the workload of maintainers (reviewing, merging, maintaining) while not adding much (if any) value. The limited time of maintainers is better spent on contributions that fix a real world issue or add a feature to help a real world use-case. This may sound a bit unfortunate, but it is the practical limitation of any open source big project.

Besides that, with a project as big as this one, and the complexity of our test suite, it will be of no use to get a report of a million mutation issues. It takes months to sort out which issue is actually relevant.

At last, I believe a project with lots of downloads is covered by more than just the tests in the repository. Some components have barely changed over the past 15 years (e.g. HttpFoundation) and are thus battle tested by production applications for 15 years. 
And this works 2 ways: the component has served all use-cases for 15 years - meaning that it is unlikely to need major refactoring in the next 15 years as well, and as it works for 15 years, it is unlikely that there are major bugs to be found even if there isn't a really good mutation coverage. That's the benefit of working on matured code :)

**Comment by maxbeckers** [comment]
@wouterj yes, you're right. My thoughts were more to use it for new code and not for all the existing code. But yes, probably it makes more sense to use this only locally when working on critical issues.

**Comment by fabpot** [comment]
Let's close then.
