### ISSUE TITLE
[PropertyInfo] read-only property is marked as writeable

### ISSUE THREAD

**Issue by MartkCz** [symfony/symfony#47756]
### Symfony version(s) affected

6.1.*

### Description

Read-only property is marked as writeable.

### How to reproduce

```php
<?php

use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;

require __DIR__ . '/vendor/autoload.php';

$extractor = new ReflectionExtractor();

class Foo {

	public readonly string $name;

}

var_dump($extractor->isWritable(Foo::class, 'name'));
```

output `bool(true)`

**Comment by xabbuh** [comment]
Thank you for the report @MartkCz. Can you confirm that #47763 fixes it?

**Comment by MatTheCat** [comment]
I was wondering why readonly properties were ignored when denormalizing and this led me to this issue.

~Do we agree the `$name` property is actually writable in the reproducer?~

Okay so I learned public readonly properties are not publicly writable 😅
