### ISSUE TITLE
Using inline_css causes emoji's to render defective

### ISSUE THREAD

**Issue by parijke** [symfony/symfony#47783]
### Symfony version(s) affected

6.1.5 with twig/cssinliner-extra 3.4.0

### Description

```
{% apply inline_css %}
    <html>
    <head>
        <style>
            p { color: red; }
        </style>
    </head>
    <body>
    <p>👇👇👇👇👇👇👇</p>
    </body>
    </html>
{% endapply %}
```
renders the hands as `ððððððð`

### How to reproduce

Here's a small repo to reproduce. go to /test/bug and see the mail. I use the mailcatcher docker instance to see the sent email

https://github.com/parijke/inlincecss-bug

**Comment by stof** [comment]
Have you tried adding the `<meta charset="UTF-8">` in your `<head>` to check whether it fixes it ? UTF-8 is not the default charset in HTML (for historical reasons).

**Comment by parijke** [comment]
Indeed that works... but the strange thing is, that without the `{% apply inline_css %}` it also works.

**Comment by stof** [comment]
Well, inlining the CSS parses the HTML and re-dumps it. So it might be affected by the missing charset.

**Comment by parijke** [comment]
Thanks for explaining.

**Comment by nicolas-grekas** [comment]
I guess we should default to UTF-8 when the tag is missing but the content is UTF-8. Up for a PR?

**Comment by parijke** [comment]
Sure, if you guide me to the process (never done it before)

**Comment by xabbuh** [comment]
FTR: updating `tijsverkoyen/css-to-inline-styles` to a version that contains tijsverkoyen/CssToInlineStyles#238 (i.e. 2.2.6 or higher) fixes the reported issue
