### ISSUE TITLE
Display a file, such as an image or PDF, directly in the user's browser

### ISSUE THREAD

**Issue by alexbog8** [symfony/symfony#47784]
### Symfony version(s) affected

6.0.13, 6.1.5

### Description

Laravel official documentation says that to display a file in a user browser a simple return response()->file($filePath) will suffice. Since the current version, 6.0.13 this command will show the binary content of the file, not the file itself!

<img width="2347" alt="Screenshot 2022-10-04 at 15 37 34" src="https://user-images.githubusercontent.com/19467114/193834275-233a3e7d-3c81-4658-8d04-ba9375ca2a11.png">

### How to reproduce

return response()->file($pathToFile);

**Comment by wouterj** [comment]
A fix for this bug has been merged: https://github.com/symfony/symfony/pull/47746
