### ISSUE TITLE
`AbstactController::file()` with `ResponseHeaderBag::DISPOSITION_INLINE` and `symfony/http-foundation` version `6.1.5` sets content type incorrect

### ISSUE THREAD

**Issue by mivoelcker** [symfony/symfony#47787]
### Symfony version(s) affected

6.1.5

### Description

After updating the `symfony/http-foundation` package to version `6.1.5` (from version `6.1.2`) the inline-display of an pdf fails when using the `file()` method of the `AbstractController`. 
Instead the pdf is interpreted as text (see image).
![grafik](https://user-images.githubusercontent.com/115065629/194000551-cfd25177-6b0a-4c59-8a23-19a13ae4636d.png)

The problem seems to be a wrong content type header: `text/html; charset=UTF-8` instead of `application/pdf`. 

### How to reproduce

I used the `file()` method of the `AbstractController` by following the [docs](https://symfony.com/doc/current/controller.html#streaming-file-responses). 
```php
#[Route('/download/pdf')]
public function download_pdf(): BinaryFileResponse
{
    $pdfPath = '/my/absolute/path.pdf'
    $pdfFile = new File($pdfPath);
    return $this->file($pdfFile, 'name.pdf', ResponseHeaderBag::DISPOSITION_INLINE); // Wrong content type

    // return $this->file($pdfPath, 'name.pdf', ResponseHeaderBag::DISPOSITION_INLINE); // No different with path instad of SplFileInfo

    // With ResponseHeaderBag::DISPOSITION_ATTACHMENT the content type is still wrong, but doesn't matter here
    // return $this->file($pdfPath, 'name.pdf', ResponseHeaderBag::DISPOSITION_ATTACHMENT);
}
```

### Possible Solution

Simple solution by setting the content type manual:
```php
#[Route('/download/pdf')]
public function download_pdf(): BinaryFileResponse
{
    $pdfPath = '/my/absolute/path.pdf'
    $pdfFile = new File($pdfPath);

    $response = new BinaryFileResponse($pdfPath);
    $response->headers->set('Content-Type', 'application/pdf');
    $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_INLINE, 'name.pdf');
    return $response;
}
```

### Additional Context

I'm using symfony with php8.1-fpm with nginx as server (both as alpine docker). 

I could not find an issue with a similar problem.

**Comment by derrabus** [comment]
Duplicate of #47786
