### ISSUE TITLE
[Messenger] decode URL-encoded characters in DSN's usernames/passwords breaks authentication in case of + used

### ISSUE THREAD

**Issue by sidz** [symfony/symfony#47788]
### Symfony version(s) affected

4.4.

### Description

Looks like https://github.com/symfony/symfony/pull/47533 breaks AMQP authentication (I suppose redis is affected as well) in case password contains _+_ sign.

[urldecode](https://www.php.net/manual/en/function.urldecode) documentations says: "Decodes any %## encoding in the given string. **Plus symbols ('+') are decoded to a space character.**"

Also I suppose that password may have any of _%##_ characters.

### How to reproduce

Set + sign as part of password and it will be replaced with space.

### Possible Solution

Remove urldecode at least from password option

**Comment by xabbuh** [comment]
Did you encode the `+` character in your DSN?

**Comment by sidz** [comment]
@xabbuh Nope. env variable looks like: `MESSENGER_TRANSPORT_DSN=amqp://guest:gu+est@localhost:5672/%2f/messages`

Should password be encoded since 6.1.5 (4.4.46) ?

**Comment by stof** [comment]
Well, a `+` must be encoded to respect the URI spec. Otherwise, it means being a ` `

**Comment by sidz** [comment]
well in this case it need to improve documentation just to let people now what they need to do to avoid unpredictable behavior.

Thanks. Closed then

**Comment by sidz** [comment]
Think that it would be useful to have _urlencode_ EnvVarProcessor out of the box. WDYT @xabbuh , @stof ?
