### ISSUE TITLE
[HttpFoundation] InputBag::set() no longer accepts objects as second argument

### ISSUE THREAD

**Issue by Syloq** [symfony/symfony#47806]
### Symfony version(s) affected

6.1.5

### Description

Previously the set() method accepted almost any type as the second argument. This was ultimately helpful when needing to set an object to be passed somewhere else within the application.

### How to reproduce

Pass an object , of any kind, to the second parameter of the set() method.  It will throw an error 

>Expected a scalar, or an array as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::set()", "stdClass" given.

### Possible Solution

https://github.com/symfony/symfony/blob/14f2066a089102ac884a015836759b1a2a915365/src/Symfony/Component/HttpFoundation/InputBag.php#L69

Include: `&& !\is_object($value)` check to above line.

**Comment by ro0NL** [comment]
this is intended, as user input is scalar-ish.

you can use custom request attributes to pass data along the application lifecycle.
