### ISSUE TITLE
[Console] Commands aren't able to fully gracefully exit by themselves

### ISSUE THREAD

**Issue by lcobucci** [symfony/symfony#47809]
### Symfony version(s) affected

5.2.0+

### Description

Since https://github.com/symfony/symfony/commit/df57119884f62c2c29e8a9232b56a287196dad32 symfony/console is reacting to signals, dispatching events, and exiting right away.

My main issue here is the `exit()` inside of the signal handler, as it imposes a specific application design for graceful shutdowns and prevents the dispatch of `console.terminate` event.

### How to reproduce

A command like this should suffice:

```php
<?php

declare(strict_types=1);

namespace MyApp;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Command\SignalableCommandInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function sleep;
use const SIGINT;
use const SIGTERM;

#[AsCommand('testing')]
final class Testing extends Command implements SignalableCommandInterface
{
    private bool $shouldContinue = true;

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        while ($this->shouldContinue) {
            $output->writeln('Still processing...');
            sleep(1);
        }

        $output->writeln('Wrapping up, wait a sec...'); // this message is never shown (unless we remove the `exit()` call)

        return self::SUCCESS;
    }

    public function getSubscribedSignals(): array
    {
        return [SIGINT, SIGTERM];
    }

    public function handleSignal(int $signal): void
    {
        $this->shouldContinue = false;
    }
}
```

### Possible Solution

I believe Symfony should not auto exit on that situation or at least provide a way to skip it.

### Additional Context

Execution of the sample command with the `exit()`:

```sh
$ bin/console testing
{"message":"Notified event \"console.command\" to listener \"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure\".","context":{"event":"console.command","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:12:24.056+00:00"}
{"message":"Notified event \"console.command\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand\".","context":{"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:12:24.056+00:00"}
Still processing...
Still processing...
Still processing...
Still processing...
^C $ 
```

Execution of the sample command without the `exit()`:

```sh
$ bin/console testing
{"message":"Notified event \"console.command\" to listener \"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure\".","context":{"event":"console.command","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:39.000+00:00"}
{"message":"Notified event \"console.command\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand\".","context":{"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:39.000+00:00"}
Still processing...
Still processing...
Still processing...
^CWrapping up, wait a sec...
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:41.554+00:00"}
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:41.554+00:00"}
$
```

**Comment by lcobucci** [comment]
We can workaround to this behaviour by setting `$app->setSignalsToDispatchEvent();` but that removes the dispatching of `ConsoleSignalEvent` or by implementing a custom `Application` class.

I don't think these are ideal solutions, though 😄

**Comment by chalasr** [comment]
👍 To fix this. I think we can rely on the Application's `autoExit` flag

**Comment by lcobucci** [comment]
> +1 To fix this. I think we can rely on the Application's `autoExit` flag

I'm not sure if that's the way to go... we'd still want the application to exit with the code provided by the command's return.

**Comment by lcobucci** [comment]
@lyrixx perhaps you would have ideas here?

**Comment by akuzia** [comment]
Stumbled across this too (https://github.com/symfony/symfony/discussions/48024)
How about not exit at all? Many of signals can be ignored, this is [intended behavior](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGTERM). Just call all of the handlers with `handleSignals` as last one and leave it to the developer to decide what to do next. For outside integrations there is SIGKILL that most of process managers sends after SIGTERM anyway, as it cannot be ignored and always result in process termination. (Yes, i know there is TASK_UNINTERRUPTIBLE kernel state in linux. But it is outside of the application scope)

**Comment by lcobucci** [comment]
@akuzia that's definitely the perfect idea. @lyrixx added that exit instruction, which got approved by @fabpot.

I'd gladly send a PR if that's the direction we want to go.

**Comment by lyrixx** [comment]
I added the exit instructions to mimic how php handle a sigterm.

With previous version of symfony, a sigterm does the same thing : it kills the application, isn't?

But maybe the list of signal we filter is not big enough?

Maybe I didn't understand your use case correctly.

**Comment by akuzia** [comment]
> a sigterm does the same thing : it kills the application, isn't?

No. It signals application to exit. In which case developer can decide to gracefully exit or ignore this signal.
I've provided some code samples [here](https://github.com/symfony/symfony/discussions/48024#discussioncomment-3996082)

**Comment by lyrixx** [comment]
Ohh I think I understand. You are indeed listening to the signal but after your custom code it exists anyway but way too fast without calling other regular events. 

Did I understand correctly?

Dou you want to work on a PR? I can if you cannot, this is perfectly fine.

**Comment by lcobucci** [comment]
> > a sigterm does the same thing : it kills the application, isn't?
> 
> No. It signals application to exit. In which case developer can decide to gracefully exit or ignore this signal.

100% that!

The application should be the one in control here, not Symfony.

**Comment by akuzia** [comment]
> You are indeed listening to the signal but after your custom code it exists anyway but way too fast without calling other regular events

Yes, but not way to fast, it did not meant to exit at all at this state. Console need to call all of the handlers and proceed with `execute`. It's the signal handler responsibility to interrupt execution.

@lcobucci called dibs on that PR already.

**Comment by lcobucci** [comment]
Just to make sure we're aligned, the goal of the PR is to remove the exit call, right?

Although I completely agree with that decision, it's a behavioural BC-break. Is Symfony alright with it?

**Comment by lyrixx** [comment]
as a user what would you except for each use cases?

1. **No** signal handler has been registered for SIGINT => the program exit as soon as possible

1. A signal handler has been been registered for SIGINT => Symfony execute your handler, and then do nothing, it means it'll resume your code "normally"

I agree this should be the default behavior. I added the exit because I wanted the mimic the default PHP behavior, but now I think I was wrong. Your [example](https://github.com/symfony/symfony/discussions/48024#discussioncomment-3996082) is really clear, and it should work as in the second case.

About 

> Although I completely agree with that decision, it's a behavioural BC-break. Is Symfony alright with it?

I don't know! cc @nicolas-grekas

**Comment by akuzia** [comment]
Seems reasonable for any signal, not only SIGINT or SIGTERM (or any other one). I've used SIGHUP and SIGSTOP/SIGCONT several times with symfony.

> A signal handler has been been registered for SIGINT => Symfony execute your handler, and then do nothing, it means it'll resume your code "normally"

Yep, so `SignalableCommandInterface` becomes more of a convenience for registering async signal handlers and not the last signal handler.

**Comment by HypeMC** [comment]
> I added the exit because I wanted the mimic the default PHP behavior

Hi, I'm not sure this is entirely true. I've noticed that when PHP has a PID of 1 (when there's no init process, like in a docker container) nothing seems to happen when I send a `SIGINT` or `SIGTERM`, eg take the following code:

```php
#!/usr/bin/env php
<?php

while (true) {
    echo time().PHP_EOL;
    sleep(1);
}

echo 'Bye';
```

and try running it with the following image:

```Dockerfile
FROM php:8.1.3-fpm-bullseye

RUN docker-php-ext-install pcntl

RUN echo '\
<?php\n\n\
while (true) {\n\
  echo time().PHP_EOL;\n\
  sleep(1);\n\
}\n\n\
echo "Bye";\
' > /my-script.php
```

```sh
docker build -t my-image .
docker run --rm --name my-container my-image php /my-script.php
```

Pressing `Ctrl + C` doesn't do anything & neither does sending a `SIGINT` or `SIGTERM` with `docker kill`:

```sh
docker kill --signal=SIGINT my-container
docker kill --signal=SIGTERM my-container
```

However, when starting the container [with an init process](https://docs.docker.com/engine/reference/run/#specify-an-init-process), everything works as expected:

```sh
docker run --init --rm --name my-container my-image php /my-script.php
```

I'm not sure if this means PHP's default behavior is to do nothing?

**Comment by akuzia** [comment]
>  I've noticed that when PHP has a PID of 1 (when there's no init process, like in a docker container)

@HypeMC it is [ok for pid 1 processes](https://docs.docker.com/engine/reference/run/#foreground)

**Comment by HypeMC** [comment]
@akuzia Thank you for clarifying, I wasn't aware of this fact.

**Comment by lcobucci** [comment]
> as a user what would you except for each use cases?

@lyrixx I'd expect that Symfony would **only** propagate the signals down to my application. No exiting whatsoever, regardless of having registered listeners.

Specially because there might be other components/libraries that are handling the signals and allowing the application to gracefully shutdown.

**Comment by lyrixx** [comment]
yes, you are right.

**Comment by lcobucci** [comment]
Alright, so are you okay with the BC-break? If so, I can send a PR (just mind that I'll be unavailable for the next couple of months)

**Comment by lyrixx** [comment]
I was agree [6 days](https://github.com/symfony/symfony/issues/47809#issuecomment-1308541634) ago.

And it still don't know about the bc break. Sorry

**Comment by GromNaN** [comment]
I reverted to the expected behaviour in this MR: https://github.com/symfony/symfony/pull/48210, but this is still inconsistent whenever event listeners or signal handlers are used.

I think we need a `preventDefault()` method on the SignalEvent to skip the exit and handle shutdown gracefully.

**Comment by lcobucci** [comment]
> I reverted to the expected behaviour in this MR: https://github.com/symfony/symfony/pull/48210, but this is still inconsistent whenever event listeners or signal handlers are used.
> 
> I think we need a `preventDefault()` method on the SignalEvent to skip the exit and handle shutdown gracefully.

@GromNaN the problem isn't with dispatching/reacting to events. There's an `exit` call that IMHO shouldn't exist. We basically need to remove the following lines: https://github.com/symfony/symfony/blob/ac88f9a72bd0980ebff2bf4a24a11bdbc2aa6735/src/Symfony/Component/Console/Application.php#L1008-L1013

I think that having a `preventDefault()` would only make things more complicated...

**Comment by lcobucci** [comment]
> I was agree [6 days](https://github.com/symfony/symfony/issues/47809#issuecomment-1308541634) ago.
> 
> And it still don't know about the bc break. Sorry 

@lyrixx I'm sorry if it sounded like I was putting pressure on you, just wanted to make you folks aware that I won't be able to follow up with the discussion soon. This is OSS.

@akuzia feel free to push a PR while I'm away.

**Comment by dkarlovi** [comment]
One more example why SIGTERM shouldn't immediately exit: when working with Messenger on k8s, your worker could be working for a while, say 10min.

If an rolling update comes in, the pod with the worker will receive a SIGTERM to "please shutdown". It's [not expected to **immediately** exit](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace):
> At this point, Kubernetes will send a SIGTERM signal to the containers in the pod. This signal lets the containers know that they are going to be shut down soon.
> Your code should listen for this event and start shutting down cleanly at this point. This may include stopping any long-lived connections (like a database connection or WebSocket stream), saving the current state, or anything like that.

K8s will wait for a `terminationGracePeriodSeconds` before killing the pod. What the Messenger consume command should do is accept the signal and mark itself as "not accepting any new messages", but try to complete the current one, if any.
