### ISSUE TITLE
InvalidArgumentException: Class "" used for service "security.listener.session.main" cannot be found

### ISSUE THREAD

**Issue by andrea-daru** [symfony/symfony#47814]
### Symfony version(s) affected

5.4.13

### Description

I just updated libraries due to php upgrade from 7.4 to 8.1.
The following exception occurs and it seems to be related to the SecurityBundle:

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Class "" used for service "security.listener.session.main" cannot be found. in /shared/httpd/myapp/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php:122
Stack trace:
#0 /shared/httpd/myapp/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /shared/httpd/myapp/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(787): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(190): Symfony\Component\HttpKernel\Kernel->preBoot()
#5 /shared/httpd/myapp/web/app.php(20): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main}
  thrown in /shared/httpd/myapp/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php on line 122
[08-Oct-2022 14:34:52 Europe/Rome] PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Class "" used for service "security.listener.session.main" cannot be found. in /shared/httpd/myapp/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php:122
Stack trace:
#0 /shared/httpd/myapp/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /shared/httpd/myapp/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(787): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /shared/httpd/myapp/vendor/symfony/http-kernel/Kernel.php(190): Symfony\Component\HttpKernel\Kernel->preBoot()
#5 /shared/httpd/myapp/web/app.php(20): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main}
  thrown in /shared/httpd/myapp/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php on line 122
```
These are the versions of the installed libraries:
symfony/security-bundle            v6.1.3 
symfony/security-core                v6.1.5 
symfony/security-csrf                 v6.1.0 
symfony/security-http                 v6.0.13

Does someone know the reason? I'm struggling trying to found a solution.
Thank. you in advance

### How to reproduce

symfony/framework-bundle        v5.4.13
symfony/security-bundle            v6.1.3 
symfony/security-core                v6.1.5 
symfony/security-csrf                 v6.1.0 
symfony/security-http                 v6.0.13

**Comment by chalasr** [comment]
Your report does not provide enough information to make us able to reproduce the issue. Please create a reproducer as described in https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by NikolaStar** [comment]
Проблема связана с тем, что не настроен конфиг security.yml. Компилятор пытается взять из блока firewalls назначенный для main провайдер из блока provider, в котором уже в свою очередь заполняется id, т.е. класс. Но у меня, к примеру, там было заполнено лишь, соответственно класс оказался null:
```
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
```
![Screenshot_20231112_144143](https://github.com/symfony/symfony/assets/25660421/37b65585-f01e-4979-8936-aea8853d96ba)


Место, где регистрируется этот слушатель:
![Screenshot_20231112_144016](https://github.com/symfony/symfony/assets/25660421/bb1d7a74-7a89-42c6-83d2-5767319bb4c9)

Проблему решил так:
![Screenshot_20231112_144235](https://github.com/symfony/symfony/assets/25660421/59035ee7-1557-4321-b119-e31be157610c)

**Comment by derrabus** [comment]
Please use the English language on this repository.
