### ISSUE TITLE
Want to add Urdu Language Translation in Form Component, Security Core and in Validator Component

### ISSUE THREAD

**Issue by MuhammadAakash** [symfony/symfony#47819]
### Description

I would love to do the translations for the Urdu language in the Symfony Translations.
Urdu is a language that is spoken in Pakistan. And Urdu language is my mother tongue.
Adding this Language in Symfony Translations would help developers from Pakistan.

Thanks,  would love to work on this when it's accepted.

**Comment by stof** [comment]
Please open a PR with your contribution. And ideally, please try to find another Urdu native speaker to review your proposed translations.

**Comment by MuhammadAakash** [comment]
@stof  Sure Sir.
I will start working on it.

**Comment by MuhammadAakash** [comment]
Hi @stof.
I have made the changes locally. So, before submitting my PR should I have to follow all of these steps?
https://symfony.com/doc/current/contributing/code/pull_requests.html#step-4-submit-your-pull-request 

Please guide me on what should I do.
