### ISSUE TITLE
How can I set 8bit encoding Laravel 9.x?

### ISSUE THREAD

**Issue by hiteshsamcom** [symfony/symfony#47810]
### Symfony version(s) affected

6.0

### Description

How can I set the `8bit` encoder in notification?

Because in the `quoted-printable` encoder 3D tag is added to email logs and Gmail markup can't validate the schema.org.

```
return (new MailMessage)
            ->subject('8bit encoder subject)
            ->markdown('mails.booking', [
                'booking' => $this->booking
            ]);
```

### How to reproduce

It's produced into Laravel 9.x and Symfony 6.0

**Comment by xabbuh** [comment]
I am not sure I understand your issue. Can you elaborate a bit what’s happening and what you did expect instead?
