### ISSUE TITLE
Warning: session_id(): Session ID cannot be changed after headers have already been sent

### ISSUE THREAD

**Issue by AntoineTesson** [symfony/symfony#47820]
### Symfony version(s) affected

5.4.11

### Description

My service App\EventListener\UserAction\ActivityListener  return 

Warning: session_id(): Session ID cannot be changed after headers have already been sent  or
Failed to start the session because headers have already been sent by

  $user = $this->security->getUser();   => Cause of this.

### How to reproduce

This configuration of service

`    App\EventListener\UserAction\ActivityListener:
        tags:
            - { name: 'kernel.event_listener', event: kernel.terminate, method: refresh }`

And this service :

`use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpKernel\Event\TerminateEvent;
use ErrorException;
use RuntimeException;

class ActivityListener {
    
    

    private $entityManager;
    private $security;

	
	public function __construct(EntityManagerInterface $entityManager,Security $security)
	{
	    $this->em = $entityManager;
	    $this->security = $security;

	}
	

	public function refresh(TerminateEvent $event): void {
	    
	   
			$delay = new \DateTime();
			$delay->setTimestamp(strtotime('2 minutes ago'));
		
			
			if ($this->security->getUser()) {
			    $user = $this->security->getUser();
			
			    if (isset ( $user) && $user instanceof UserInterface && $user->getLastActivity() < $delay ) {
			        $user->setLastActivity ( new \DateTime () );
			        $ip= $this->getIp();
			        $user->setIp($ip);
			        $em = $this->em;
			        $em->persist ( $user );
			        $em->flush ();
			    }
			}
			
			
				
	}
	
	private function getIp() :string
	{
	    if (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['HTTP_X_FORWARDED_FOR']) {
	        // Behind balancer
	        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
	    } else if (isset($_SERVER['REMOTE_ADDR']) && $_SERVER['REMOTE_ADDR']) {
	        // Universal PHP headers
	        $ip = $_SERVER['REMOTE_ADDR'];
	    } else {
	        // Unusual headers
	        $ip = "exotique";
	    }
	    
	    return $ip;
	    
	    
	}
}`

And sometimes i have en error due of this line :

`$this->security->getUser()`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by mangelsnc** [comment]
Can you ensure you haven't have any character printed outside of the PHP tags (even a whitespace) or you aren't using any print function (`var_dump`, `dump`, `print_r`, `echo`...)?

**Comment by AntoineTesson** [comment]
Hi, nop no one blankspace or print function in my file. 
I have the impression that this happens when the user refreshes his page and he has been disconnected in the meantime
Its complicated to reproduce, because with the volumetrie this problem appear sometimes ~~5 times by hours on my logs, and this function its used to check if the user is connected or not, so each time new request of the user (TerminateEvent), but when u have sentry  or board 200 errors of the same problem by days its borring

**Comment by xabbuh** [comment]
Without being able to reproduce there's unfortunately nothing we can do about this. Are you able to provide such an application?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
