### ISSUE TITLE
Content-Type header is not set based on file mime type anymore

### ISSUE THREAD

**Issue by IntoTheCodeIO** [symfony/symfony#47823]
### Symfony version(s) affected

6.1.5

### Description

[This commit](https://github.com/symfony/http-foundation/commit/7acdc97f28a48b96def93af1efd77cfc5e8776dd) introduce a regression : content-type header is not set based on file mime type anymore (see comments added on the commit).

### How to reproduce

1. Create a BinaryFileResponse with a specific file type (tested with excel file) and no headers
2. Call the prepare methode
3. The content-type header is `text/html; charset=UTF-8` (was `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` before)

**Comment by adrienprioul** [comment]
Duplicate of #47824

**Comment by adrienprioul** [comment]
Duplicate of #47824

**Comment by IntoTheCodeIO** [comment]
Duplicate of #47824

**Comment by malsieb** [comment]
v4.4.46 is also affected. Probably all of the following: v6.0.13, v5.4.13, v4.4.46
