### ISSUE TITLE
[FrameworkBundle] `WebTestCaseTest::assertCheckboxChecked/assertCheckboxNotChecked` does not work with html5

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#47830]
### Symfony version(s) affected

6.1, sort of

### Description

The [`WebTestCaseTest::assertCheckboxChecked/assertCheckboxNotChecked`](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Test/DomCrawlerAssertionsTrait.php#L88-L102) assertions do not work with html5 content.

They are only [tested with html 4 content](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php#L233-L246).

If the html tag in these tests with `<!DOCTYPE html>`, the tests fail.

This is because, in html5, `checked` is a [boolean attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes), 
i.e this is valid:
`<input type="checkbox" name="rememberMe" checked>`
while this is not:
`<input type="checkbox" name="rememberMe" checked="checked">`

so the `new CrawlerSelectorAttributeValueSame("input[name=\"$fieldName\"]", 'checked', 'checked')` check fails.

`masterminds/html5` will parse `<input type="checkbox" name="rememberMe" checked="checked">` as  `<input type="checkbox" name="rememberMe" checked>`.

### How to reproduce

They are only [tested with html 4 content](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php#L233-L246)

Replace the html tag in these tests with `<!DOCTYPE html>`.

### Possible Solution

not sure, maybe modify the assertion so it works with html4 and 5 parsers
```php
LogicalOr(new CrawlerSelectorAttributeValueSame(...), new CrawlerSelectorAttributeExists(...))
```
where `CrawlerSelectorAttributeExists` is a new Constraint.

### Additional Context

We discoverd this issue while upgrading from symfony 5.4 to 6.1, because `masterminds/html5` became a mandatory dependency in 6.1: https://github.com/symfony/symfony/pull/44170, so previously on 5.4, our html in functional tests was not parsed as html5.

it should be noted that html5 is used in a default symfony project:
https://github.com/symfony/recipes/blob/f54b694258dfcb356f6c59e2ce1a4c49f3cceae9/symfony/twig-bundle/5.4/templates/base.html.twig#L1

**Comment by MatTheCat** [comment]
`<input type="checkbox" name="rememberMe" checked="checked">` is valid:

> If the attribute is present, its value must either be the empty string or **a value that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the attribute's canonical name**

**Comment by bendavies** [comment]
> `<input type="checkbox" name="rememberMe" checked="checked">` is valid:
> 
> > If the attribute is present, its value must either be the empty string or **a value that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the attribute's canonical name**

fair enough,  but we also need to deal with just the case of:
```html
<input type="checkbox" name="rememberMe" checked>
```

**Comment by maxbeckers** [comment]
I guess we only have to validate that there is the attribute `checked` on the `input` or even not.

More details see here: https://stackoverflow.com/a/4613192

**Comment by maxbeckers** [comment]
I took a quick look inside.

For mee this is working (with the unit tests) and valid:
`<input type="checkbox" name="rememberMe" checked>`
and this too:
`<input type="checkbox" name="rememberMe" checked="checked">`.

But the checked value seems to be case sensitive, the following tests are invalid:
`<input type="checkbox" name="rememberMe" checked="CHECKED">`
`<input type="checkbox" name="rememberMe" checked="on">`.

But this is handled by the php function https://www.php.net/manual/en/domelement.getattribute.php so for me it seems not to be a symfony bug.

**Comment by MatTheCat** [comment]
Invalid or not, boolean attributes are `true` when present, whatever their value. This is reflected by the CssSelector’s `HtmlExtension`: https://github.com/symfony/symfony/blob/d7fe6a06576369237c2192abdd56570113109206/src/Symfony/Component/CssSelector/XPath/Extension/HtmlExtension.php#L60-L67

I opened a PR to use it.
