### ISSUE TITLE
Missing translations for Hindi language

### ISSUE THREAD

**Issue by Arpit-Gulgulia** [symfony/symfony#47846]
### Description

Hi @fabpot,
I see the symphony has added translation of texts for many languages but missing the Hindi language(My native language). If it is in the plan, then I can contribute and provide the translation for  these files:

1. Form Component - src/Symfony/Component/Form/Resources/translations
2. Security Core - src/Symfony/Component/Security/Core/Resources/translations
3. Validator Component - src/Symfony/Component/Validator/Resources/translations

Let me know if I can help.
Thanks!

**Comment by stof** [comment]
Contributions for new locales are welcome.

Ideally, we would need another native speaker to review those translations too.

**Comment by Arpit-Gulgulia** [comment]
Sure @stof, can you assign it to me? I will create a PR for this enhancement.
