### ISSUE TITLE
Attributes declared as "TARGET_METHOD" on "__invoke" methods not working for PHP 8.1.6 - PHP 8.1.9 and Symfony 6.2.x-dev

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#47851]
### Symfony version(s) affected

6.2.x-dev

### Description

According to changes implemented in https://github.com/symfony/symfony/pull/46001 after bumping from Symfony 6.1 to 6.2.x-dev in my private project I got new unexpected error about using `Route` attribute on `__invoke` method.

I wrote example: https://3v4l.org/jpWc5 and it looks like there was a PHP bug in according versions.

Edit: seems this issue was occurred already: https://github.com/symfony/symfony/issues/46916 but was not fixed yet.
```
root@a08e989193a2:/var/www/internal# php -v 
PHP 8.1.9 (cli) (built: Aug 23 2022 14:03:17) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans
    with blackfire v1.81.0~linux-x64-non_zts81, https://blackfire.io, by Blackfire
```

Actually I don't test it on newest version of PHP, but on 3v4l.org looks like that was actually fixed.

### How to reproduce

https://3v4l.org/jpWc5

### Possible Solution

Let's extends definition of flags in all attributes contains `Attribute::TARGET_METHOD` to `Attribute::TARGET_METHOD | Attribute::TARGET_FUNCTION` ?

Or shall we block installing Symfony when end-user has PHP 8.1.6 - PHP 8.1.9?

### Additional Context

![obraz](https://user-images.githubusercontent.com/16488888/195552554-2937c7ed-8b01-4452-a1a6-0f34c3ba8a45.png)

**Comment by stof** [comment]
this looks like a bug in PHP to me. `__invoke` is a method.

**Comment by michaljusiega** [comment]
> this looks like a bug in PHP to me. `__invoke` is a method.

Yes, It was actually fixed: https://github.com/php/php-src/issues/8982 https://github.com/php/php-src/pull/9173 (8.1.10) but not every user has the newest version of PHP.

**Comment by derrabus** [comment]
> Yes, It was actually fixed

So, there's nothing to do here.

> but not every user has the newest version of PHP.

Not our problem really. If you are affected by a PHP bug that can be solved simply by upgrading to a newer patch release, you should do that.

**Comment by michaljusiega** [comment]
> > Yes, It was actually fixed
> 
> So, there's nothing to do here.
> 
> > but not every user has the newest version of PHP.
> 
> Not our problem really. If you are affected by a PHP bug that can be solved simply by upgrading to a newer patch release, you should do that.

Thank you for answer. I will do it. However I just wondering that we can warning users about this issue.

**Comment by MatTheCat** [comment]
Just hit that so thanks for the report :+1:
