### ISSUE TITLE
symfony/console: the error message is displayed strangely

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [symfony/symfony#47862]
### Symfony version(s) affected

6.1.6

### Description

When a completely wrong command is entered, the error message is displayed correctly(as block).

When a command is entered with an error in the one letter and the console offers its own version of the command, the error message is displayed strangely, it seems that instead of
`formatBlock($errorMessages, 'error', true);`
you call some wrong code, so that the red color instead of a block spreads over the entire terminal.
![ss_2022_10_14__13_59_52](https://user-images.githubusercontent.com/25248634/195823004-fd536fe2-31fc-44b2-a15a-18e8404fc4c9.png)

### How to reproduce

1.register one command 'clear-cache'
2.run with error 'console clear-ca**s**he'

**Comment by chalasr** [comment]
Help welcome to fix this, as it seems to be specific to your (Windows?) setup.

**Comment by wouterj** [comment]
To illustrate what @chalasr means, I just tried your example in a new 6.1 project and this is the result: ![image](https://user-images.githubusercontent.com/749025/196060097-23ab6ac4-875f-4466-b9d3-18e3783590c5.png)


(`clear-cache` is not a command in Symfony by default, I expect this is your own console utility?)

**Comment by aleksandr-shevchenko** [comment]
> To illustrate what @chalasr means, I just tried your example in a new 6.1 project and this is the result: ![image](https://user-images.githubusercontent.com/749025/196060097-23ab6ac4-875f-4466-b9d3-18e3783590c5.png)
> 
> (`clear-cache` is not a command in Symfony by default, I expect this is your own console utility?)

'clear-cache' - my own test command
if made mistake in one letter, for example as 'clear-ca**S**he', then print invalid colored error block

(or try 'hello-wordd Sam' instead 'hello-world Sam')
[test_console.zip](https://github.com/symfony/symfony/files/9797075/test_console.zip)

Another two bugs for symfony/console:
1. App name with unicode symbols displayed incorrect in Win10 console, but 'echo' print unicode text fine

2. Show version (console -V) not print version if not set name

If you want see apps version you must set name
'$app->setName("bla-bla-bla");
$app->setVersion("1.0.585");'

**Comment by maxbeckers** [comment]
I can reproduce the bug on windows (using gitbash) as well with the current 6.1 symfony version.

![2022_10_17_09_44_07_test_console_bug](https://user-images.githubusercontent.com/11738128/196118598-5ba03014-5ba2-4b6c-a6e7-72c599ce9dff.png)

I'll try a fix for that problem.

**Comment by aleksandr-shevchenko** [comment]
<img width="614" alt="196060097-23ab6ac4-875f-4466-b9d3-18e3783590c5" src="https://user-images.githubusercontent.com/25248634/196344755-353936e1-269e-4d10-874f-606dc27cb396.png">
instead of
<img width="614" alt="true_error" src="https://user-images.githubusercontent.com/25248634/196344252-5602e0fb-693d-4337-9b01-174fe7c5b45a.png">

**Comment by aleksandr-shevchenko** [comment]
Why did you close? After all, there are more questions...

**Comment by nicolas-grekas** [comment]
Didn't #47883 solve the issue?

**Comment by aleksandr-shevchenko** [comment]
> Didn't #47883 solve the issue?

See my post above (about paint entire width of terminal) and about other 2 bugs in symfony/console

Another two bugs for symfony/console:

1. App name with unicode symbols displayed incorrect in Win10 console, but 'echo' print unicode text fine

2. Show version (console -V) not print version if not set name

If you want see apps version you must set name
'$app->setName("bla-bla-bla");
$app->setVersion("1.0.585");'

**Comment by nicolas-grekas** [comment]
OK, at least the behavior described in the issue is fixed. Would you like to send PRs for the other behaviors you spotted?

**Comment by aleksandr-shevchenko** [comment]
not work on Win10 (missing red line under error message)
![image](https://user-images.githubusercontent.com/25248634/196368077-5c3e8aa6-cdf8-49a4-a839-9142c45e1288.png)

**Comment by maxbeckers** [comment]
Okay ?! For me (Windows 10 as well) was it working, see the screenshots in the pr.

And i tries to reproduce the unicode problem you mentoined:

_bin/console_:
```
#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

if (!is_file(dirname(__DIR__).'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    echo "printed by echo - Test symfony/console эЮя öĞıƏşÜ \u{2713}" . PHP_EOL;

    $app =  new Application($kernel);
    $app->setName("Test symfony/console эЮя öĞıƏşÜ \u{2713}");
    $app->setVersion("1.0.585");

    return $app;
};
```

And then i get this output:
![Screenshot 2022-10-18 095344](https://user-images.githubusercontent.com/11738128/196370343-bc078e3b-a77a-422e-9751-373a195138cc.png)

So for me it seems to work on windows 10 (using gitbash cli)

**Comment by aleksandr-shevchenko** [comment]
echo print unicode fine in win console, and in cmder
symfony/console only in cmder, but in console - not
![image](https://user-images.githubusercontent.com/25248634/196371668-0af2e233-2f93-4059-83a7-45f9cd934b40.png)

**Comment by maxbeckers** [comment]
I also tried the cmd:
![Screenshot 2022-10-18 100302](https://user-images.githubusercontent.com/11738128/196372423-261a666a-e7f1-4196-b9c3-3ea06890bd33.png)

and by the way the bug of the ticket works as well for me on cmd:
![Screenshot 2022-10-18 100446](https://user-images.githubusercontent.com/11738128/196372777-fd083ddd-7d66-4f37-b637-fbf8e3fa8a1e.png)

So I can't reproduce that. As @nicolas-grekas mentioned, maybe you could try a fix?

**Comment by aleksandr-shevchenko** [comment]
Can you give me your sample project?

**Comment by maxbeckers** [comment]
I just used a clean `symfony new my_project_directory --version="6.1.*" --webapp` installation for the tests. And then only modified the _bin/console_ mentioned a few comments before.

But my fix was merged to 4.4 so maybe you should use the 4.4 base.

**Comment by aleksandr-shevchenko** [comment]
[test_console.zip](https://github.com/symfony/symfony/files/9809293/test_console.zip)
Please check for yourself, I do not have a lower red line if there is a typo in the command...

**Comment by wouterj** [comment]
The bugfix has not yet been merged up to 6.2. This will be done before the release of a patch version, after which this bug is fixed.

For now, you can test the patch by manually applying it in your vendor directory.

Feel free to submit contributions if you think other things might need to be improved.

**Comment by aleksandr-shevchenko** [comment]
Yes, fix work!

But I suggest replace
`$style->block(sprintf('Command "%s" is not defined.', $name), null, 'error', ' ', true);`
by
```
$output->writeln('');
$formattedBlock = (new FormatterHelper())->formatBlock(sprintf('Command "%s" is not defined.', $name), 'error', true);
$output->writeln($formattedBlock);
```
![image](https://user-images.githubusercontent.com/25248634/196410135-3dec036c-7ecd-4771-8336-a2180cc36010.png)

**Comment by maxbeckers** [comment]
When we don't want to use the `SymfonyStyle` for the output here, then it could be a possible was to do that. But you should use `$this->getHelperSet()->get('formatter')` instead of `(new FormatterHelper())`.

But IMHO it could be helpful to fix the `SymfonyStyle::block` method for windows usage instead of finding a workarount.

**Comment by chalasr** [comment]
> $this->getHelperSet()->get('formatter') instead of (new FormatterHelper()).

Please no :) `new FormatterHelper()` is fine here and avoids an unnecessary service locator usage that should hopefully be deprecated at some point (ref https://github.com/symfony/symfony/issues/21417#issuecomment-275388348)
