### ISSUE TITLE
[DotEnv] $_SERVER environment variables are not overloading the .env values

### ISSUE THREAD

**Issue by asuri0n** [symfony/symfony#47871]
### Symfony version(s) affected

6.1.2

### Description

I'm using Clevercloud as a PaaS for symfony application. They inject all environment into $_SERVER variable.
I'm also using dot-env to dump all env into .env.local.php, but the $_SERVER are overwritten with .env default value.
Is it the expected behavior ? I don't think so because as the doc say :

"The .env file is read and parsed on every request and its env vars are added to the $_ENV & $_SERVER PHP variables. Any existing env vars are never overwritten by the values defined in .env, so you can combine both."
-- https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-env-files

### How to reproduce

adding a dump line 187 `dump("putting $_SERVER[$name] in \$_ENV");`
and adding a dump line 199 `dump("and putting $value in \$_ENV");`
gives the following result :
```
"putting mysql://my_prod_user@my_prod_secret:3306/symfony in $_ENV"
"and putting mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8&charset=utf8mb4 in $_ENV"
```
We can see that the value is overriding with .env value

### Possible Solution

https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Dotenv/Dotenv.php#L198
adding continue; in line 187 fix the issue but i don't know if it's the best solution

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by asuri0n** [comment]
First time i'm creating an issue, i really don't know if you want something like this : 
```
<?php
$_SERVER['FOO'] = 'bar';

file_put_contents('.env', "FOO=foo", \LOCK_EX);

// composer require symfony/flex
exec('composer dump-env prod');
```
This is creating a .env.local.php with this content : 
```
<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'FOO' => 'foo',
);
```
but it should be `'FOO' => 'bar'` right ?

**Comment by 94noni** [comment]
just a question, why do you want `to dump all env into .env.local.php` if env var are handled via the server?

**Comment by asuri0n** [comment]
It's a performance optimization, even if the majority of env var are handled via the server, symfony still spend time parsing the .env files if no .env.local.php file.

**Comment by 94noni** [comment]
ha ok so you are using server vars via clevercloud but also deploy a .env file thus need to dump it
I've never used both (server envs or file envs), only one or the other :s 

obvious question, is the .env needed? can you not get rid of it ?
regarding the issue, it may be that the doc is in contradiction with the actual source code, the [doc is 3y old](https://github.com/symfony/symfony-docs/commit/75e5ae65e9d75c78a7de931c71101f81a4a3ad5f)

**Comment by asuri0n** [comment]
It's what i'm doing to get around this issue.
But I want to know if there really is a problem with doc/code or I'm misunderstanding something

**Comment by nicolas-grekas** [comment]
This is the expected behavior of `composer dump env`: this command is independent of the env vars that are loaded into `$_SERVER`. The reason is that its job is to compile the contents of the .env files - not the real env vars.

Can you provide a reproducer of the issue you're having (right now, I feel like you're sharing some symptoms, not the real thing you're experiencing)
