### ISSUE TITLE
[Form] EnumType contains null in choice_filter callback

### ISSUE THREAD

**Issue by pavol-tuka** [symfony/symfony#47885]
### Symfony version(s) affected

6.1.6

### Description

If you use `EnumType` with `choice_filter` option and callback function, first value passed to callback is `null`. Option `required` is `true` by default, so `null` should not be there.

### How to reproduce

`src/Enum/TestEnum.php`
```
<?php

declare(strict_types=1);

namespace App\Enum;

enum TestEnum: string
{
    case A = 'A';
    case B = 'B';
    case C = 'C';
}
```
`src/Controller/TestController.php`
```
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Enum\TestEnum;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function dump;

class TestController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    #[Route('/test')]
    public function __invoke(): Response
    {
        $builder = $this->createFormBuilder();

        $builder->add('test', EnumType::class, [
            'class' => TestEnum::class,
            'choice_filter' => function ($x) {
                dump($x);
                return true;
            },
        ]);

        return $this->render('test.html.twig', ['form' => $builder->getForm()->createView()]);
    }
}
```
`templates/test.html.twig`
```
<body>
    {{ form(form) }}
</body>
```

### Additional Context

![image](https://user-images.githubusercontent.com/30590523/196145991-45c4c70e-220d-461c-a148-ec814667cdef.png)

**Comment by maxbeckers** [comment]
@pavol-tuka yes, in the `choice_filter` you have the null value.

But did you checkout the view?

When you try it the way you said, with required by default:
```
    #[Route('/test')]
    public function __invoke(): Response
    {
        $builder = $this->createFormBuilder();

        $builder->add('test', EnumType::class, [
            'class' => TestEnum::class,
            'choice_filter' => function ($x) {
                dump($x);
                return true;
            },
        ]);

        return $this->render('test/index.html.twig', ['form' => $builder->getForm()->createView()]);
    }
```
Then you have this select:
```
<select id="form_test" name="form[test]" required>
  <option value="A">A</option>
  <option value="B">B</option>
  <option value="C">C</option>
</select>
```

When you try it with `required=false`:
```
    #[Route('/test')]
    public function __invoke(): Response
    {
        $builder = $this->createFormBuilder();

        $builder->add('test', EnumType::class, [
            'class' => TestEnum::class,
            'required' => false,
            'choice_filter' => function ($x) {
                dump($x);
                return true;
            },
        ]);

        return $this->render('test/index.html.twig', ['form' => $builder->getForm()->createView()]);
    }
```
Then you have this select:
```
<select id="form_test" name="form[test]">
  <option value=""></option>
  <option value="A">A</option>
  <option value="B">B</option>
  <option value="C">C</option>
</select>
```

For me it seems to work as expected.

But yes, in both ways you have in the dump the `null` value.

**Comment by pavol-tuka** [comment]
IMHO it is unexpected behavior when required option is `true`. `choice_filter` should filter only existing choices, not the magic `null`. There is information that all choices are instances of enum, I would expect to safely use `TestEnum` typehint in `choice_filter` callback, without null/question mark.

**Comment by yceruto** [comment]
In this case, the null value is probably related to the data bound to the form. If you don't pass any value, it is null by default, and then the choice loader mechanism will go through the filtering process to check if it is in the list as well.

You can avoid it by setting the proper enum value as the default, e.g.:
```php
$builder = $this->createFormBuilder(['test' => TestEnum::A]);
```

**Comment by yceruto** [comment]
This is not a bug.
