### ISSUE TITLE
Cannot see Recipients(from Envelope) on Email during development - symfony/web-profiler-bundle

### ISSUE THREAD

**Issue by Anastasios89** [symfony/symfony#47889]
### Symfony version(s) affected

4.4

### Description

    mailer:
        envelope:
            recipients:
During development recipients from envelope cannot be seen.

### How to reproduce

    mailer:
        envelope:
            recipients: ['%env(DEV_EMAILS_REDIRECT_TO)%']

### Possible Solution

                                                {% if event.envelope.recipients|length > 0 %}
                                                    <span class="label">Recipients</span>
                                                    {% for recipient in event.envelope.recipients %}
                                                        <pre class="prewrap">{{ recipient.address }}</pre>
                                                    {% endfor %}
                                                {% endif %}
after line 132:                                                 <pre class="prewrap">{{ (message.headers.get('to').bodyAsString() ?? '(empty)')|replace({'To:': ''}) }}</pre>

**Comment by Anastasios89** [comment]
Possible solution on vendor/symfony/web-profiler-bundle/Resources/views/Collector/mailer.html.twig file

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
By the way, the `To` header and the envelope are two different things.

**Comment by raziel057** [comment]
It have been added in 6.1: https://github.com/symfony/symfony/pull/45765

**Comment by xabbuh** [comment]
Oh, I did not notice the 4.4. Thanks for the heads up. Let’s close here then.
