### ISSUE TITLE
Enable Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [symfony/symfony#47892]
### Description

Hi, I am Joyce from Google and I'm working on behalf of the [Open Source Security Foundation][ossf] (OpenSSF) to help essential open-source projects improve their supply-chain security. The symfony project is used by thousands of web applications and also in many popular web projects too, reason why the OpenSSF has identified it as one of the 100 most critical open source projects.

I would like to suggest for you the adoption of an OpenSSF tool called [Scorecard][sc], which runs dozens of automated security [checks][checks] to help maintainer understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

To simplify the Scorecard use, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha], which runs the scorecard's check on every push on the main branch and make the result avaiable in the [security dashboard](https://github.com/symfony/symfony/security).

The action has been adopted by 1800+ projects already, having some prominent users like [Tensorflow][tensorflow], [Angular][angular], [Flutter][flutter], [sos.dev][sos-dev] and [deps.dev][deps-dev].

Considering that Symfony project already follows many security best practices, you've already gone through half of the path to the best security posture, and the Scorecard Github Action can help you to track what are the next steps and to guarantee the stability of the already followed ones.

Would you be interested in a PR that enables this Action? Optionally it can also include the [badge][badge] to the  README file, if you want.

In case of doubts or concerns you can try to check [Scorecards FAQ][FAQ]. Anyway, feel free to reach me out.

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[checks]: https://github.com/ossf/scorecard#scorecard-checks
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[FAQ]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions

[tensorflow]: https://github.com/tensorflow/tensorflow
[Angular]: https://github.com/angular/angular  
[Flutter]: https://github.com/flutter/flutter 
[sos-dev]: https://sos.dev/ 
[deps-dev]: https://deps.dev/ 

### Example

Here are some examples of the [security dashboard](https://github.com/symfony/symfony/security) with the scorecard results.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by chalasr** [comment]
Hi, I think it's already enabled:
https://github.com/symfony/symfony/blob/6.2/.github/workflows/scorecards.yml
https://github.com/symfony/symfony/security/code-scanning

Or is there something missing?

**Comment by joycebrum** [comment]
Geez you are right! I may missed it when I openned the github folder, I'm very sorry 😥.

Thanks for the return anyway, I'll close the issue
