### ISSUE TITLE
Make trigger_deprecation namespaced

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#47904]
### Description

The `trigger_deprecation` provided by `symfony/deprecation-contracts` is registered in the global namespace. I really don't think it's a good practice to register functions in the global namespace for a variety of reasons, neither is there any drawbacks not to.

Would you be open to this change?

Alternatively it would also not be a bad idea to provide a static function instead as function autoloading in PHP is a bit meh:

`Symfony\Deprecation::trigger(...)`

**Comment by ro0NL** [comment]
I believe it was intended to be a 1st class symbol, potentially to be adapted in core.

Autoloading functions is a php/composer concern IMHO

**Comment by wouterj** [comment]
Can you please share what issue this function in the global namespace has caused for you? I would love to know the practical benefits of this change, rather than the theoretical ones :)

**Comment by theofidry** [comment]
>I believe it was intended to be a 1st class symbol, potentially to be adapted in core.

I still don't see the point: if it makes it to the core you can make this function an alias and deprecate it's usage. I get there is a tiny benefit, but I really don't think it trumps encouraging people to register symbols to the global namespace.

>Autoloading functions is a php/composer concern IMHO

But declaring a symbol to the global namespace is a maintainer & user concern. PHP introduced namespaces to solve conflicts, introducing a new symbol to the global namespace just increases this conflict risk again.

If one comes with his/her own package with a function with the same name but an incompatible signature, this would make any combination including those two packages not working (silently if `conflict` is not properly documented, runtime otherwise).

>Can you please share what issue this function in the global namespace has caused for you? I would love to know the practical benefits of this change, rather than the theoretical ones :)

A practical once is it is yet another symbol [PHP-Scoper](https://github.com/humbug/php-scoper) needs to deal with. There is currently a feature lacking to make it easy, but even when once implemented, it means any user having this library will have to not forget to add it to its config.

This is not a new problem, Symfony already has a few ones such as `dd()`, but at the very least there it is justified by its practicality.

<hr/>

To carry on on the theoretic side though as I did not really felt the need to extend on it previously:

- There is no such thing as function autoloading, so whilst sure Composer can deal with it, in practice it means it's another file necessarily autoloaded (even if not needed)
- Due to the function autoloading fallback mechanism, when you come across the symbol `trigger_deprecation`, you do not know if it's a namespaced or globally registered function, which makes any SA (regardless of the purpose) always more fragile

And again: there is just _not any drawback_ to have your functions namespaced in any way except if you feel that importing a symbol is a pain (but in that case you picked the wrong language because you need one for any class).

**Comment by ro0NL** [comment]
>  encouraging people to register symbols to the global namespace

im not encouraging it generally :sweat_smile: 

but in this case i believe `\trigger_error` vs. `\trigger_deprecation` align perfectly

the community was already used to the first global function, thus making the latter mostly complementary to it.

> If one comes with his/her own package with a function with the same name but an incompatible signature,

then we'll compete who has the better implementation for this specifc concept

ideally PHP solves this and we have composer in core, but that's a different topic also ;)

**Comment by theofidry** [comment]
>but in this case i believe \trigger_error vs. \trigger_deprecation align perfectly

There is really no difference if you import it: `trigger_error` vs `trigger_deprecation`. The only case you can really make here is if importing a symbol is a PITA which I really don't think is unless you are using a plain text editor but in that case I don't think that it's one more symbol that will make it more miserable.

>then we'll compete who has the better implementation for this specifc concept

I _really_ don't think this is the point here. Neither does it solve the problem.

>ideally PHP solves this and we have composer in core, but that's a different topic also ;)

I am not short of workarounds, as mentioned this is not a new problem, but none are good and they all contribute to make a variety of tools more fragile. And it's a case where I fail to see why keeping the problem around when there is a very simple solution.

**Comment by ro0NL** [comment]
> There is really no difference if you import it:

except you have to import it

i agree with your POV, but im surprised SF apparently cant/shouldnt extend PHPs global functions (for the better), like it does :cry: 

> > then we'll compete who has the better implementation for this specifc concept

> I really don't think this is the point here

it's my point tho :) we only need 1 function to "trigger a deprecation"

**Comment by wouterj** [comment]
> And again: there is just not any drawback to have your functions namespaced in any way except if you feel that importing a symbol is a pain (but in that case you picked the wrong language because you need one for any class).

There is a cost (i.e. drawback), any deprecation is a cost for the eco-system to handle issues from users about triggered deprecation notices, fix the function call, release new versions, etc. To illustrate the extend of this cost: there are almost [200,000 hits on GitHub](https://github.com/search?q=trigger_deprecation+-path%3Avendor+language%3APHP+language%3APHP&type=Code) for `trigger_deprecation` in PHP scripts (excluding `vendor/`).

Theory is important for new features, but near irrelevant for changes in existing code :)

**Comment by derrabus** [comment]
One idea behind making that method a global symbol was in fact making that function replaceable. Applications could register their own implementation of `trigger_deprecation()` ahead of Composer's autoloader if they wanted a different way to collect deprecations. No everyone what happy with the silenced `trigger_error()` at that time.

**Comment by theofidry** [comment]
>One idea behind making that method a global symbol was in fact making that function replaceable

It's still as easy with a namespaced function, even a class FWIW.

>There is a cost (i.e. drawback), any deprecation is a cost for the eco-system to handle issues from users about triggered deprecation notices, fix the function call, release new versions, etc. To illustrate the extend of this cost: there are almost [200,000 hits on GitHub](https://github.com/search?q=trigger_deprecation+-path%3Avendor+language%3APHP+language%3APHP&type=Code) for trigger_deprecation in PHP scripts (excluding vendor/).

And it will only get worse. FWIW the migration is also dead simple and does not need to be fixed as tightly as other packages neither, i.e. can stay around for another major version as well it's not a big deal.

**Comment by theofidry** [comment]
Another example, ESC & Refactor were affected, just like previously PHP-Scoper itself, Box, Infection and PHPStan.

But if there is no interest despite the clear drawbacks of this approach there is nothing I can do.
