### ISSUE TITLE
symfony/doctrine-messenger bug on doctrine:migration:diff with auto_setup: false (duplicated lines)

### ISSUE THREAD

**Issue by florianajir** [symfony/symfony#47912]
### Symfony version(s) affected

6.*

### Description

`doctrine:migration:diff` is not working well when used to generate schema for `symfony/doctrine-messenger` package when `framework.messenger.transports.async.options.auto_setup: false`

example of file content generated: 

```php
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
```

### How to reproduce

1. require `symfony/doctrine-messenger` to in a project (api-platform for me)
2. set  `framework.messenger.transports.async.options.auto_setup: false` in `config/package/messenenger.yaml`
```yaml
framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
        routing:
            App\Message\AsyncMessageInterface: async

```
4. exec `doctrine:migration:diff --from-empty-schema`
5. open the generated migration file

### Additional Context

My project is using api-platform (can be reproduce from scratch api project)

**Comment by MatTheCat** [comment]
I followed the steps but could not reproduce: the migration creates the `messenger_messages` table only once.

I’ve got
- symfony/doctrine-messenger v6.1.4
- doctrine/doctrine-migrations-bundle v3.2.2
- doctrine/migrations v3.5.2.

**Comment by xabbuh** [comment]
@florianajir Can you create a small example application that allows to reproduce your issue?

**Comment by florianajir** [comment]
After some searches (trying to create a reproductible bug repo) I just figured that this behaviour is caused by the presence of the `jsor/doctrine-postgis` package, I think I should close this ticket and open another on their repository.
Sorry for the confusion and thank you for your time
