### ISSUE TITLE
Always has this error "Call to a member function getBaseUrl() on null"

### ISSUE THREAD

**Issue by wehostadm** [symfony/symfony#47945]
### Symfony version(s) affected

5.4.14

### Description

Hi,

I always have this error in the file LogoutUrlGenerator.php (line 104) and not the real error in my development environnent.
![symfony_error](https://user-images.githubusercontent.com/42274060/197227028-7dde74b2-35d1-44de-be03-adf1910d72ee.png)

I don't know which upgrade has broken this but before I had the good error message and not this generic error.

How to fix it ?

Thanks,

### How to reproduce

Just create a dummy error in a Symfony controller like : 
$a = new Class1(); // Class1 does not exist

**Comment by derrabus** [comment]
see #47932

**Comment by wehostadm** [comment]
@derrabus Note that this error is always here in the Symfony 5.4.X version. 

Thanks, it is indeed the same error as I described

**Comment by stof** [comment]
@wehostadm the fix has been merged in the 4.4 branch yesterday. It has not yet propagated to newer maintained branches.

**Comment by dompie** [comment]
I encountered the same issue in my code. After applying the patch from https://github.com/symfony/symfony/pull/47932 manually I could track down the error to a forgotten logout handler.
Inside the logout handler function a method was called on a service that did not exist anymore. After removing that line, the logout worked again and the error disappeared in symfony 5.4.14
