### ISSUE TITLE
[ParamConverter]

### ISSUE THREAD

**Issue by Ciloe** [symfony/symfony#47944]
### Symfony version(s) affected

6.2.0

### Description

Hi there, I managed to update SF 6.1 to SF 6.2. and I have an error about my ParamConverter :
```
Binding entities to query parameters only allowed for entities that have an identifier.
Class "App\Entity\Event" does not have an identifier.
```

### How to reproduce

I did this in my ParamConverter :
```php
                $request->attributes->set(
                    $configuration->getName(),
                    $parent->getOccurrence($date)
                );
                return true;
```
and the entity Event has no id because it does not exist in database. But I don't want doctrine going to work on my paramConverter. What's the matter ?

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?
