### ISSUE TITLE
[Http-Client] "Failure when receiving data from the peer" / "Proxy CONNECT aborted" with v4.4.38+, OK with 4.4.37

### ISSUE THREAD

**Issue by cpetit-sigma-fr** [symfony/symfony#47973]
### Symfony version(s) affected

4.4.38+

### Description

With http-client:4.4.38 and above (up to http-client:4.4.46), I don't manage to connect to an external API through our proxy:

```
$ php bin/console myapp:test-xxx
^ """
* About to connect() to proxy proxy.xxx.yyy.zzz port 8080 (#0)\n
*   Trying 1.2.3.4...\n
* TCP_NODELAY set\n
* Connected to proxy.xxx.yyy.zzz (1.2.3.4) port 8080 (#0)\n
* Establish HTTP proxy tunnel to api.provider.com:443\n
> CONNECT api.provider.com:443 HTTP/1.1\r\n
Host: api.provider.com:443\r\n
Proxy-Connection: Keep-Alive\r\n
Content-Type: application/json\r\n
Accept: application/json\r\n
Content-Length: 75\r\n
User-Agent: Symfony HttpClient/Curl\r\n
Accept-Encoding: gzip\r\n
\r\n
* Proxy CONNECT aborted\n
* Connection #0 to host proxy.xxx.yyy.zzz left intact\n
"""
14:10:48 ERROR     [app] XXX: post('') Failure when receiving data from the peer for "https://api.provider.com/". ["exception" => Symfony\Component\HttpClient\Exception\TransportException^ { …}]


 [ERROR] XXX : Failure when receiving data from the peer for
         "https://api.provider.com/".
```

### How to reproduce

Sorry, I didn't write any reproduction script, my use of CurlHttpClient seems to be completely standard and I manage to use other APIs within my application, the only thing that changes is HttpClient version.

### Possible Solution

If i downgrade to http-client:4.4.37, it does work:

$ php bin/console myapp:test-xxx

```
 [OK] XXX : OK
```

If i use directly curl_init(), curl_setopt() and curl_exec(), it does work, too.

If don't see what introduced this behaviour between the two releases looking at <https://github.com/symfony/http-client/compare/v4.4.37...v4.4.38>.

### Additional Context

NB: seems the same as #46499, I hope I can help resolving this regression.

**Comment by cpetit-sigma-fr** [comment]
I forgot to say that is specific to a new API provider I want to connect to, another works with v4.4.41.

Even if the API is public, I'd prefer to keep his name private, please contact me.

**Comment by cpetit-sigma-fr** [comment]
After migration to Symfony 5.4, as expected, the first external API doesn't work any more. I had to use bare curl_xxxx() calls to get my data.

The problem is that now the other external API I use and that was fine before exhibits the same behaviour.

I'm investigating around the proxy used on this VLAN...

**Comment by cpetit-sigma-fr** [comment]
We took a moment to analyze the traffic coming to the proxy with WireShark.

The base cURL version (that works) capture looks like this, it seems to be a standard HTTPS request:

![image](https://user-images.githubusercontent.com/31703571/211052285-61a54db7-bb1b-458e-bcec-0eb7a7ad7d3e.png)

The CurlHttpClient version (that does not work) capture does not, and the proxy closes the connection:

![image](https://user-images.githubusercontent.com/31703571/211053014-e0a75388-dc7e-49f5-89ec-f1662eef13a6.png)

I didn't manage to extract the exact cURL options CurlHttpClient uses.

PS: symfony/http-client is now v5.4.16

**Comment by nicolas-grekas** [comment]
Could you please send me the output of `$response->getStatusCode() && dump($response->getInfo('debug'));` on a version that works + doesn't work? You can send them to me privately on Symfony-dev's Slack if you need.

**Comment by cpetit-sigma-fr** [comment]
Discussing with Nicolas in a private Slack conversation, feedback provided.

**Comment by nicolas-grekas** [comment]
Thanks for the details. Can you please try #48966 and report back if it fixes the issue for you?
