### ISSUE TITLE
[Mailer] 6.2 dev - MessageEvent listener not called

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#47989]
### Symfony version(s) affected

6.2-dev

### Description

Working fine on current 6.2 branch.

I define an event listener like this:
```
$services
        ->set(MessageEventListener::class)
        ->tag('kernel.event_listener', ['event' => MessageEvent::class])
        ->args(
            [
                '%env(MAILER_EMAIL)%',
            ]
        );
```
However the handler is no longer being called.

### How to reproduce

I'm trying to work out why the `AbstractTransport::send` method does not appear to be called anymore and why the `MessageEvent` event listener would not be fired.

**Comment by chalasr** [comment]
Thanks for the report. I suspect this is due to https://github.com/symfony/symfony/pull/47191 changing the dispatched event name when extending `MessageEvent`. Could you confirm?

**Comment by silverbackdan** [comment]
Previously this would work. But now in my tests the event that is fired is `QueuingMessageEvent` that I'd need to listen to in my case.
In my tests I am disabling the mailer DSN `null://null`
So in a real world scenario, this probably wouldn't be a break.
But during tests I think the transports are being skipped and therefore the event not fire to populate the `from` email header in my case which is what I'm testing is being populated.

**Comment by silverbackdan** [comment]
I do think that's the case - previously I guess this event would have been called and should be ignored because it was a queued event. But it's better to have this separate I agree.
So now the event would only be fired if the transport is called, so during tests, there is no transport being called, and so my tests fail.

**Comment by silverbackdan** [comment]
Would you have any recommendation on how to ensure during tests, when I have disabled transports that I am testing for listening to the event properly? Is it worth in the component, when transport is disabled, still emitting that event?

Looking at the `NullTransport`, I'd have thought `send` should still be called though and the event emitted, so I'll do some more digging.

**Comment by chalasr** [comment]
I do think this is a BC break we should fix. /cc @fabpot

**Comment by silverbackdan** [comment]
Also to do with messenger being installed, even is I set to disable the bus. I'm working through to see what I can find though :)
```
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: ~
```

**Comment by chalasr** [comment]
No worry, thanks for testing the beta! 
May I ask you to keep this one focus on the event name change and open another one (or more) with the information/code needed to reproduce?

**Comment by silverbackdan** [comment]
Sure thing. I'll delete other comments here and open one for this other issue.

**Comment by chalasr** [comment]
Should be fixed by https://github.com/symfony/symfony/pull/47992

**Comment by silverbackdan** [comment]
Thanks, shame to revert the change but appreciate your fast response and fix time!

**Comment by silverbackdan** [comment]
This was 1 of 3 issues found unfortunately, but happy to be running tests on the beta branches and able to give you all a heads up :)

**Comment by chalasr** [comment]
>  Thanks, shame to revert the change but appreciate your fast response and fix time!

No big deal, the new feature keeps working despite reverting that part.

> This was 1 of 3 issues found unfortunately, but happy to be running tests on the beta branches and able to give you all a heads up :)

Thanks to you!

**Comment by nesl247** [comment]
This seems related to #47383.
