### ISSUE TITLE
[Mime][Mailer][Profiler] 6.2-dev Cannot unserialize Symfony\Component\Mime\Part\DataPart

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#47991]
### Symfony version(s) affected

6.2-dev

### Description

I am sending a message with Mailer. And when the profile data is being collected I get an error. Stack strace to relevant parents.

I get an error, full stack trace:
```
Scenario: I can change my password                             # features/user/change_password_form.feature:12
      And I should get a "change_password_notification" email sent # features/user/change_password_form.feature:27
        BadMethodCallException: Cannot unserialize Symfony\Component\Mime\Part\DataPart in vendor/symfony/mime/Part/DataPart.php:162
        Stack trace:
        #0 [internal function]: Symfony\Component\Mime\Part\DataPart->__wakeup()
```

### How to reproduce

Send an email message with a file attached and profiler enabled.

### Possible Solution

The DataPart parent is...
```
array:6 [
  "body" => Symfony\Component\Mime\Part\BodyFile {#11584
    -path: "xxx/_CWA/api-components-bundle/src/Resources/views/assets/images/email_logo.png"
  }
  "charset" => null
  "subtype" => "png"
  "disposition" => "inline"
  "name" => "@SilverbackApiComponents/assets/images/email_logo.png"
  "encoding" => "base64"
]
```
As body is not a string, it causes this error.

For this perhaps... Symfony\Component\Mime\Part\BodyFile::__toString could be implemented
https://github.com/symfony/mime/blob/6.2/Part/BodyFile.php

and try to cast as a string in Symfony\Component\Mime\Part\DataPart::__wakeup
https://github.com/symfony/mime/blob/6.2/Part/DataPart.php#L161

**Comment by silverbackdan** [comment]
This hack fix would seem to work, but then there's another issue in mailer so I'll open another issue
(implementing `__toString` and type casting as a string in `__wakeup()`
```
public function __wakeup()
    {
        $r = new \ReflectionProperty(AbstractPart::class, 'headers');
        $r->setValue($this, $this->_headers);
        unset($this->_headers);

        if (!\is_array($this->_parent)) {
            throw new \BadMethodCallException('Cannot unserialize '.__CLASS__);
        }
        foreach (['body', 'charset', 'subtype', 'disposition', 'name', 'encoding'] as $name) {
            if (null !== $this->_parent[$name] && !\is_string((string) $this->_parent[$name])) {
                throw new \BadMethodCallException('Cannot unserialize '.__CLASS__);
            }
            $r = new \ReflectionProperty(TextPart::class, $name);
            $r->setValue($this, $this->_parent[$name]);
        }
        unset($this->_parent);
    }
```

```
class BodyFile
{
    private static $mimeTypes;

    public function __construct(
        private string $path,
    ) {
    }

    public function getPath(): string
    {
        return $this->path;
    }

    public function getContentType(): string
    {
        $ext = strtolower(pathinfo($this->path, \PATHINFO_EXTENSION));
        if (null === self::$mimeTypes) {
            self::$mimeTypes = new MimeTypes();
        }

        return self::$mimeTypes->getMimeTypes($ext)[0] ?? 'application/octet-stream';
    }
    
    public function __toString() {
        return $this->getPath();
    }
}
```

**Comment by ovrflo** [comment]
Guys, any news on this?
I'm having the same issue with 6.2.

**Comment by xabbuh** [comment]
Does this happen on 6.1 too or is 6.2 the only affected version?

**Comment by ovrflo** [comment]
Happens only on 6.2. Downgraded to 6.1, deployed and then all the stuck messages in the queue got sent instantly.

**Comment by silverbackdan** [comment]
Yes, I can also say this is a 6.2 issue only. I'm testing on upcoming releases for my application to prevent future breaking changes which is where this has occurred, whereas current versions are fine.

**Comment by fabpot** [comment]
Anyone willing to investigate the issue and maybe suggest a fix?

**Comment by silverbackdan** [comment]
> This hack fix would seem to work, but then there's another issue in mailer so I'll open another issue (implementing `__toString` and type casting as a string in `__wakeup()`
> 
> ```
> public function __wakeup()
>     {
>         $r = new \ReflectionProperty(AbstractPart::class, 'headers');
>         $r->setValue($this, $this->_headers);
>         unset($this->_headers);
> 
>         if (!\is_array($this->_parent)) {
>             throw new \BadMethodCallException('Cannot unserialize '.__CLASS__);
>         }
>         foreach (['body', 'charset', 'subtype', 'disposition', 'name', 'encoding'] as $name) {
>             if (null !== $this->_parent[$name] && !\is_string((string) $this->_parent[$name])) {
>                 throw new \BadMethodCallException('Cannot unserialize '.__CLASS__);
>             }
>             $r = new \ReflectionProperty(TextPart::class, $name);
>             $r->setValue($this, $this->_parent[$name]);
>         }
>         unset($this->_parent);
>     }
> ```
> 
> ```
> class BodyFile
> {
>     private static $mimeTypes;
> 
>     public function __construct(
>         private string $path,
>     ) {
>     }
> 
>     public function getPath(): string
>     {
>         return $this->path;
>     }
> 
>     public function getContentType(): string
>     {
>         $ext = strtolower(pathinfo($this->path, \PATHINFO_EXTENSION));
>         if (null === self::$mimeTypes) {
>             self::$mimeTypes = new MimeTypes();
>         }
> 
>         return self::$mimeTypes->getMimeTypes($ext)[0] ?? 'application/octet-stream';
>     }
>     
>     public function __toString() {
>         return $this->getPath();
>     }
> }
> ```

It would be good to find out what changes were made to make this break here and what the purpose of those changes were. This hacky fix above would work, but we are just forcing the BodyFile to a string.. and perhaps there would be more to the body than just a file. I will do my best to look into this more but quite pushed at work right now so if someone could take it up quicker then I'd appreciate it. Will do my best though.

**Comment by xabbuh** [comment]
The new class was introduced in #47462. The code to serialize attachments before 6.2 looked like this: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Mime/Email.php#L612-L616
