### ISSUE TITLE
Yaml: dump numeric keys as strings instead of numbers

### ISSUE THREAD

**Issue by mabar** [symfony/symfony#48061]
### Description

The OpenAPI specification currently requires all keys in Responses Object to be strings, as decribed here https://github.com/OAI/OpenAPI-Specification/blob/157a4c81ae537ef793b2bee368bc00d88b461de8/versions/3.0.2.md#patterned-fields-1

This includes values like `'200'`, which are type-casted to int by PHP.

For further info see https://github.com/OAI/OpenAPI-Specification/issues/3068

To work around that I would like to add a flag to encode numeric keys as strings in YAML. This solution should probably skip keys of auto-indexed arrays (with keys starting from 0)

### Example

Instead of calling

```php
use Symfony\Component\Yaml\Yaml;
Yaml::dump([200 => 'foo']);
```

and producing

```yaml
200: 'foo'
```

Call

```php
use Symfony\Component\Yaml\Yaml;
Yaml::dump([200 => 'foo'], flags: Yaml::DUMP_NUMERIC_KEY_AS_STRING);
```

and produce

```yaml
'200': 'foo'
```

**Comment by derrabus** [comment]
Out of curiosity: Wouldn't it make sense to use JSON instead to export an OpenAPI document?

**Comment by mabar** [comment]
Yes, I do that personally. But I am also working on a complete implementation of OpenAPI in PHP and would like to fix all incompatibilities with the schema. OpenAPI explicitly states that json and yaml are supported.
