### ISSUE TITLE
Provide same variables for IsGranted attribute as for SecurityAttribute

### ISSUE THREAD

**Issue by bastien70** [symfony/symfony#48071]
### Description

According to https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/security.html#security 

We can use something like this : 

```php
#[Security("is_granted('my_voter_item', request)")] // subject can be internal parameter like request, token, user, roles
#[Route(path: '/someRoute', name: 'some_route')]
public function action(): Response
{}
```

But we can't do this : 

```php
#[IsGranted(data: ExtraVoter::MY_VOTER_ITEM, subject: 'request')]
#[Route(path: '/someRoute', name: 'some_route')]
public function action(): Response
{}
```
We'll have this error : `Could not find the subject "request" for the @IsGranted annotation. Try adding a "$request" argument to your controller method.`

We will be able to use the IsGranted only if we add the parameter in the constructor of the action, like this : 

```php
#[IsGranted(data: ExtraVoter::MY_VOTER_ITEM, subject: 'request')]
#[Route(path: '/someRoute', name: 'some_route')]
public function action(Request $request): Response
{}
```

But it is possible that the variable is not used in the action, which can lead to its automatic deletion by tools such as Rector. And in general, I think doing this kind of thing is not good.

It would therefore be interesting to be able to use the same internal Symfony parameters that we use for the Security attribute, for the IsGranted attribute

**Comment by derrabus** [comment]
SensioFrameworkExtraBundle is maintained in a separate repository. Please open an issue there.

https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues

**Comment by stof** [comment]
Not reproducing the `@Security` attribute of SensioFrameworkExtraBundle was actually done on purpose, because that annotation was not relying on the Symfony authorization system but rebuilding its own layer (which caused lots of compatibility issues when building the new authentication system in Symfony).

However, currently, the expressions usable in the subject don't have access to the `request` variable. This might be added.

**Comment by stof** [comment]
My answer assumes that your `IsGranted` is the core attribute, not the `IsGranted` attribute of SensioFrameworkExtraBundle

**Comment by HypeMC** [comment]
> However, currently, the expressions usable in the subject don't have access to the `request` variable. This might be added.

Actually, the expressions usable in the subject have access to all controller arguments, so if the request is one of them they have access to it as well. Maybe you meant the request should always be present, even when not an argument?

**Comment by stof** [comment]
Those expressions have access to a `args` variable with the controller arguments. They don't have access to a `request` variable.
