### ISSUE TITLE
The "Monolog\Logger" class is considered final

### ISSUE THREAD

**Issue by trickeyone** [symfony/symfony#48086]
Minor issue: Deprecation warnings are being displayed for the Symfony Monolog Logger extending Monolog Logger in PHP 8.1, due to `Monolog/Logger` has the `@final` annotation in the the class docblock

```text
The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger".
```

Obviously not a blocker, and can be circumvented by using the allowed deprecation warnings for tests, but wanted to raise it.

**Comment by stof** [comment]
I transferred this issue as the child class is in the bridge, not in the bundle

**Comment by derrabus** [comment]
Duplicate of #47096
