### ISSUE TITLE
[HttpClient] HttplugClient sets option http_version to null for any version except 1.0

### ISSUE THREAD

**Issue by Tetragramat** [symfony/symfony#48087]
### Symfony version(s) affected

4.4.47

### Description

`\Symfony\Component\HttpClient\HttplugClient::sendPsr7Request` overrides protocol version for any version other than 1.0 and sets http_version option as null. Where HttpClient chooses highest version available.

It is problem when target server does not support http2 and request fails.

### How to reproduce

On server that supports http2 create request with version 1.1 and send it using `\Symfony\Component\HttpClient\HttplugClient`. The request will be made using http version 2.0 instead of requested 1.1.

### Possible Solution

Stop overriding protocol version in `\Symfony\Component\HttpClient\HttplugClient::sendPsr7Request`

**Comment by MatTheCat** [comment]
This is also the case in https://github.com/symfony/symfony/blob/ff56fe80de77f4019d28cbe105ce1973b09b580a/src/Symfony/Component/HttpClient/Psr18Client.php#L105

Did not find the rationale in https://github.com/symfony/symfony/pull/30413 or https://github.com/symfony/symfony/pull/33743 :thinking:

**Comment by nicolas-grekas** [comment]
That is on purpose: PSR-7 forces `getProtocolVersion` to return something, which means it forbids ALPN-based protocol negotiation. Since all implementations defaults to '1.1', the only way to do opportunistic-'2.0' is to ignore '1.1'.

>It is problem when target server does not support http2 and request fails.

Why does a server that advertises '2.0' not support it?

**Comment by Tetragramat** [comment]
> Why does a server that advertises '2.0' not support it?

I have no idea. It's Raiffeisen Bank test api https://developers.rb.cz/premium/documentation/02rbczpremiumapi_sandbox

We are getting `Stream error in the HTTP/2 framing layer for` when 2.0 is being used.

**Comment by nicolas-grekas** [comment]
Can you try configuring the client passed to `HttplugClient` with option `http_version` set to `1.1`?

**Comment by Tetragramat** [comment]
Already tried that. Option `http_version` is not overridden by default value if its already set even if it's `null`.

**Comment by nicolas-grekas** [comment]
Then let's change that: can you please send a PR to NOT set the http_version in HttplugClient+Psr18Client instead of setting it to null?

**Comment by Tetragramat** [comment]
on branch 4.4?

**Comment by nicolas-grekas** [comment]
yes please

**Comment by Tetragramat** [comment]
done
