### ISSUE TITLE
[Notifier] Migrate to new Linkedin API

### ISSUE THREAD

**Issue by qdequippe** [symfony/symfony#48094]
### Description

Current implementation of Linkedin Notifier uses a legacy API [ugcPosts API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api?view=li-lms-2022-10). You can find the related code here https://github.com/symfony/linked-in-notifier/blob/6.1/LinkedInTransport.php#L76

Linkedin documentation [recommends](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/contentapi-migration-guide?view=li-lms-2022-10) to migrate to the new API [Posts API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api?view=li-lms-2022-10).

I would like to implement this new API but due to BC policy, could you give me the right way to do this? Add new Notifier component with a different name? Add triggers for deprecations?

Best regards

**Comment by stof** [comment]
The BC policy does not cover which endpoint is used. It covers the usage of the PHP class (and the resulting post created on Linkedin for a given usage).
If we can use the new API to create a similar post with the same input, there is no need for any deprecation.
We might need a deprecation in the `LinkedInOptions` class as its constructor accepts raw options, which might need to be converted between the structure of the old API and the one of the new API when providing a non-empty array.

If the usage cannot stay the same, we might need to provide a separate transport (or another way to opt-in for the new API).
Contributions are welcome to have such changes in 6.3 (it is too late for 6.2 as we are in the stabilization phase)

**Comment by qdequippe** [comment]
@stof thank you for these very clear explanations. I will try to contribute on this point.
