### ISSUE TITLE
Dumping `TraceableHttpClient` fails with Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by PabloKowalczyk** [symfony/symfony#48096]
### Symfony version(s) affected

6.1.7

### Description

Hello,
after some debugging I find out that calling `dump($httpClient);` with `\Symfony\Component\HttpClient\TraceableHttpClient` (inner client's `logger` and `stopwatch` are not null) fails with message `Serialization of 'Closure' is not allowed`.

Is there anything I can do to avoid this issue other than "do not call dump with TraceableHttpClient"? :)

### How to reproduce

```php
dump($httpClient);
```

**Comment by fancyweb** [comment]
Hello, can you please create a small project that allows to reproduce the issue?

**Comment by PabloKowalczyk** [comment]
Can't reproduce it in isolated env, looks like something specific to our app. Sorry for mess.
