### ISSUE TITLE
[security.yaml] Unrecognized option "form_login"

### ISSUE THREAD

**Issue by integrapp** [symfony/symfony#48090]
### Symfony version(s) affected

6.1.7

### Description

You can't make use of form_login under firewalls main (for instance). Error shows:

```
Unrecognized option "form_login" under "security.firewalls.main". Available  
!!     options are "access_denied_handler", "access_denied_url", "context", "cust  
!!    om_authenticators", "entry_point", "form_loginbak", "form_loginbak_ldap", "  
!!    host", [...]
```
Please pay attention to: bak suffix.

### How to reproduce

Just add form_login under security.yaml firewalls main

### Possible Solution

Remove bak suffix in the class is generating

### Additional Context

Auto generated class FirewallConfig under cache is including bak suffix.

**Comment by MatTheCat** [comment]
I’m pretty sure Symfony does not provide a `form_loginbak` authentication..!

Try removing your `vendor` directory and reinstalling your dependencies with `composer install`.

If it still isn’t working, please provide [a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html).
