### ISSUE TITLE
Help wanted: enable CodeQL in GHA

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#48114]
### Description

All is explained in https://github.com/github/codeql-action#usage

This is encouraged by https://github.com/symfony/symfony/security/code-scanning/6

Help wanted to:
- decide if this is relevant for Symfony
- enable this in the CI

**Comment by stof** [comment]
According to https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed, CodeQL does not support analyzing PHP yet. So I would say that it is not yet relevant for us (at least not in symfony itself, maybe symfony-ux may benefit from it to analyze its typescript code).
