### ISSUE TITLE
[DependencyInjection]  Optimized autowiring breaks existing installations

### ISSUE THREAD

**Issue by brusch** [symfony/symfony#48138]
### Symfony version(s) affected

6.2-dev

### Description

Regression caused by #46279 

Registering `Response` as an abstract service [here](https://github.com/symfony/symfony/blob/739789f384cca3b06a3b5f35793e116fff337473/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.php#L229), causes the following error message: 

```
The definition ".service_locator.Fz2ZPLc" has a reference to an abstract definition "Symfony\Component\HttpFoundation\Response". Abstract definitions cannot be the target of references.
```

### How to reproduce

Just use an existing Symfony project with `6.2-dev` and build the container. 
See also https://github.com/pimcore/pimcore/actions/runs/3408995937/jobs/5670226500#step:7:702

### Possible Solution

Removing the following line fixes the issue for me: 

https://github.com/symfony/symfony/blob/739789f384cca3b06a3b5f35793e116fff337473/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.php#L229

**Comment by MatTheCat** [comment]
> Just use an existing Symfony project with `6.2-dev` and build the container.

Nope. This happens when a controller method has a nullable `Response` argument (like `Pimcore\Controller\FrontendController::renderTemplate`).

**Comment by brusch** [comment]
@MatTheCat Thanks for the info, but still, it works with `6.1` and breaks with `6.2`, right?

**Comment by nicolas-grekas** [comment]
Would you be able to submit a failing test case maybe? There must be a compiler pass to fix that should skip registering, likely `RegisterControllerArgumentLocatorsPass`.

**Comment by MatTheCat** [comment]
@brusch yep.

**Comment by brusch** [comment]
Unfortunately I'm not into all details of that topic, but I'll have a look 😉

**Comment by MatTheCat** [comment]
I guess https://github.com/symfony/symfony/blob/f3a180b40683fb7e37c8f103159d2f981deb2db3/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterControllerArgumentLocatorsPass.php#L154-L156 should also check for `Response` :thinking:

**Comment by nicolas-grekas** [comment]
@MatTheCat absolutely, that'd do it!

**Comment by MatTheCat** [comment]
Are you up for a pull request @brusch? I think you can use [`RegisterControllerArgumentLocatorsPassTest::testEnumArgumentIsIgnored`](https://github.com/symfony/symfony/blob/f3a180b40683fb7e37c8f103159d2f981deb2db3/src/Symfony/Component/HttpKernel/Tests/DependencyInjection/RegisterControllerArgumentLocatorsPassTest.php#L405-L419) as a model for the new test case (since we want to ignore `Response`).

**Comment by brusch** [comment]
@MatTheCat unfortunately not within a reasonable time I guess, maybe next week 😳

**Comment by MatTheCat** [comment]
No problem: I opened #48172 for you!

**Comment by brusch** [comment]
@MatTheCat Thank you very much! 💜
