### ISSUE TITLE
HttpClient uses Amp even if it's incompatible (with fibers)

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#48143]
### Symfony version(s) affected

5.4.15

### Description

The `HttpClient` implementation only cares if `ConnectionLimitingPool` is defined: https://github.com/symfony/symfony/blob/f3a180b40683fb7e37c8f103159d2f981deb2db3/src/Symfony/Component/HttpClient/HttpClient.php#L33

However, this tells nothing of whether this is a version of Amp using coroutines (v1-4) or fibers (v5+). Both versions declare `ConnectionLimitingPool`, so this doesn't distinguish between versions and if the user has installed [Amp HTTP client v5](https://github.com/amphp/http-client/tree/v5), it will fail.

### How to reproduce

Try to send a request using `HttpClient` with `amphp/http-client:^5@beta` installed.

### Possible Solution

Either directly support Amp HTTP client v5 or find a better detection method that rejects such version.

**Comment by stof** [comment]
is there an easy way to detect `amphp/http-client` 5+ ?
For me, the right change in Symfony 5.4 is to keep support only for `amphp/http-client` < 5. Adding support for `amphp/http-client` 5+ would be a new feature given the incompatibility and would be done in a new minor version (so Symfony 6.3 or later depending on when it is worked on).

**Comment by nicolas-grekas** [comment]
It looks like v5 introduced `Amp\Http\Client\Body\StreamBody` so we can check for its existence.
Up for a PR @Bilge ?

**Comment by kelunik** [comment]
The best check will be whether `Amp\Promise` exists, which will indicate Amp v2 instead of v3.

**Comment by Bilge** [comment]
@kelunik But that doesn't indicate whether any HTTP client is installed, does it? Unless you mean to combine it with the existing check.

**Comment by stof** [comment]
this should be in addition to the `class_exists(ConnectionLimitingPool::class)` check, not in replacement of it.

**Comment by Bilge** [comment]
> Up for a PR @Bilge ?

I'm afraid probably not. I discovered this bug in production and my response, after an hour of live debugging, was to just rip it out when I discovered the reason the issue only happens on live is because of cURL version differences. And, considering I could not get it to spit out an error even after modifying vendor files in production, I doubt I will be looking back any time soon; the closest I could get to an error message was _promise has been rejected_ or something like that. However, to be clear, since I was never able to get an actual error message out of this library, I do not even know for sure that the error report in this issue is accurate; I've had to make a lot of assumptions by examining the source and a bit of local step debugging.

I offer that anecdote without judgement as I'm convinced there are very good reasons why this component switches the underlying implementation the way it does, I just don't want to deal with that headache again. This was actually discovered via Sentry, and Sentry failing means this issue also caused any and all production issues to be unreported, so it's far too risky to revert even if this issue gets fixed.

**Comment by fancyweb** [comment]
I'll look at it.

**Comment by nicolas-grekas** [comment]
> The best check will be whether Amp\Promise exists, which will indicate Amp v2 instead of v3.

can't Promise v2 be installed while Amp v3 is also used?

**Comment by kelunik** [comment]
> can't Promise v2 be installed while Amp v3 is also used?

No, `Amp\Promise` is defined in `amphp/amp` `^2` and replaced by `Amp\Future` defined in `amphp/amp` `^3`.
