### ISSUE TITLE
[Messenger][Redis] Worker stops handling messages on first empty message

### ISSUE THREAD

**Issue by rafal-tobola** [symfony/symfony#48166]
### Symfony version(s) affected

5.4, 6.* and probably others

### Description

We're using messenger with redis transport in one of our projects. On one of our staging environments, we trimmed one queue (probably in parallel, the consumer of that queue failed). This led us to a strange situation, having a message in `XPENDING` while not having it in the corresponding stream. As only IDs are being stored in `XPENDING`, while consuming, messenger can't decode the body. The whole problem is of course our fault and most probably should not happen, anyway the way messenger behaves is weird – it is returning an empty array, like there are no messages in the queue, while not `XACK`-ing that message, so it hangs in a strange loop. In my opinion, it should either `XACK` that message or throw an exception with enough information so that someone using the library can handle it manually. It took us a long time to discover what was going on, while messenger was hung in a strange situation, not consuming messages from the queue – because there are no errors being logged anywhere.

### How to reproduce

I don't have a quick way to reproduce, but the problem lies in [RedisReceiver.php](https://github.com/symfony/redis-messenger/blob/5.4/Transport/RedisReceiver.php):

```php
    public function get(): iterable
    {
        $message = $this->connection->get();

        if (null === $message) {
            return [];
        }

        $redisEnvelope = json_decode($message['data']['message'] ?? '', true);

        if (null === $redisEnvelope) {
            return [];
        }
```
In my opinion, when `$redisEnvelope` is null, the library should either throw an exception with message ID or ACK this message, so it won't be handled any more.

**Comment by kayue** [comment]
I ran into the same issue as well. 

Basically Symfony uses `XREADGROUP` command to ensure the same message won't consume by more than one consumer

```
XREADGROUP GROUP symfony consumer COUNT 1 STREAMS messages 1 
```

If this command return `null` then it will completely block Symfony's queue due to this issue. Solution is to manually `XACK` it.

```
XACK messages symfony 1671011783792-0
```

**Comment by kayue** [comment]
This is what the nil message look like

```
XREADGROUP GROUP symfony consumer COUNT 1 STREAMS messages 1 
```

```
1) 1) "messages"
   2) 1) 1) "1672049648252-0"
         2) (nil)
```

**Comment by alexander-schranz** [comment]
That is an interesting case. If the message really does not longer exist but returns no content I think its fine to do a `xdel` on it, strange that redis still has a reference to it if xtrim did remove it, so it also could be a upstream issue of Redis itself.

@jvmanji Can you create a reproducable test case I think it should be possible inside the `RedisExtIntegrationTest` to create there a reproducer for the issue: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php. There you can put messages into it, put it into pending state and do a xtrim what you did tell us did cause your issue.

**Comment by rafal-tobola** [comment]
@alexander-schranz, I added new test and also simple fix. If you'd comment out changes I did in `src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php` then the test will fail. Please let me know in the PR if you'd change anything.
