### ISSUE TITLE
invalid_message is not translated 

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#48184]
### Symfony version(s) affected

6.1.3

### Description

Closed issue: https://github.com/symfony/symfony/issues/42725

### How to reproduce

- Create RepeatedType and defined invalid_message as "translation key"
- Enter two different value into it.
- It should trigger `invalid_message`
- User will see translation key, instead of "translated text"
- Right now only {{ label }} is translated.

### Possible Solution

Take into account `translation_domain` (\Symfony\Component\Form\Extension\Validator\ViolationMapper\ViolationMapper::mapViolation)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
