### ISSUE TITLE
messenger:consume async --time-limit=# always rise an error

### ISSUE THREAD

**Issue by circulosmeos** [symfony/symfony#48196]
### Symfony version(s) affected

4.4.49-DEV

### Description

969f19b16e55f01598ed540c7a83e0259e155dda commit (or maybe other?) makes --time-limit=# to always rise an error.
4.4.47 is checked as fine.

### How to reproduce

php bin/console messenger:consume async -t 3600

**Comment by alamirault** [comment]
Hi @circulosmeos 

Thank you for your report, I created PR #48198 in order to fix it.
