### ISSUE TITLE
WebTestCase Unittest not possible to assert FlashBag

### ISSUE THREAD

**Issue by holema** [symfony/symfony#48199]
### Symfony version(s) affected

6.0.15

### Description

I upgraded from 5.4.15 to 6.0.15. Everythin works great, but in my unittests I have some Problems.

In the old Version I made same asserts to ckeck messages in the session flash bag.

```
        $session = $this->client->getContainer()->get('session');
        $flash = $session->getBag('flashes')->all();
        self::assertEquals($flash['success'][0], 'Die Konferenz wurde erfolgreich erstellt.');
```
Since the session service got deprecated I tried it this way:
```
        $this->session = new Session(new MockFileSessionStorage());
        $this->session->start();
        $flash = $this->session->getBag('flashes')->all();
        self::assertEquals($flash['success'][0], 'Test-String');
```

Here get now all the time the error, that the flash array is empty which is in the debugger correct, but a flash is definitly set.
The documentation is also not realy helpfull in the session topic.

### How to reproduce

src/Contoller/SessionBugController.php
```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SessionBugController extends AbstractController
{
    #[Route('/session/bug', name: 'app_session_bug')]
    public function index(): Response
    {
        $this->addFlash('testTopic', 'test');

        return $this->render('session_bug/index.html.twig', [
            'controller_name' => 'SessionBugController',
        ]);
    }
}

```
#templates/session_bug/index.php
```
{% for flash in app.flashes('testTopic') %}
{{ flash }}

{% endfor %}
```

#tests/SessionBugControllerTest
```
<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage;

class SessionBugControllerTest extends WebTestCase
{
    public function testSomething(): void
    {
        $session = new Session(new MockFileSessionStorage());
        $session->start();
        $client = static::createClient();
        $crawler = $client->request('GET', '/session/bug');
        $flash = $session->getBag('flashes')->all();

        $this->assertEquals($flash['testTopic'][0],'test');

    }
}

```

**Comment by n0rbyt3** [comment]
The ```session``` service has been deprecated. Since you're doing some application tests, you should not rely on internals but the response itself. Your controller displays the flash messages somewhere inside the rendered template. If you have a container which holds the flash messages, f.ex. a ```<div>``` element with an unique id, you can use the ```DOM Crawler``` component to verify the existence of the container and the inner text. See https://symfony.com/doc/current/testing.html#crawler-assertions for some useful functions to test the response.

```php
$crawler = $client->request('GET', '/session/bug');
$flashMessage = $crawler->filter('#idOrSelectorForTheContainer')->text();
self::assertEquals($flashMessage, 'Die Konferenz wurde erfolgreich erstellt.');
```

**Comment by holema** [comment]
Helo @n0rbyt3,

Thanks for the idea. But up to now it was possible, so I thougt there might be a way to enter the flashbag during tests.

**Comment by holema** [comment]
I have to reopen this issue.
In the past I used the service to generate different templates. In these Templates I used flashes which were set in this service before the template got renderes. Now this is not possible at all, because when I want to test this Service which renders the template needs the Flash to render the template correctly.

Since I´m in the real request this all works as expected, but in the case I want to test the service in  a unittest there is no session and no flashes.
Up to now it is not possible to simulate any Rqauest Stack or Session which is then used in my Service under Test.

**Comment by janopae** [comment]
I have a form that can redirect to any other route inside the app and would not like the test to make assumptions about what the route will be. For the success message, it should add a flash. Testing if a flash had been set (without rendering a specific route) would be pretty handy for situations like this.
