### ISSUE TITLE
ext-iconv * error when running symfony new --webapp 

### ISSUE THREAD

**Issue by enfrte** [symfony/symfony#48204]
### Symfony version(s) affected

Symfony CLI version 5.4.18 Symfony SAS (2022-11-09T16:06:39Z - stable)

### Description

Hi, I hope this counts as an error. 

I had an issue when creating a new web project. Report comes with solution

       

### How to reproduce

    [noel@family-desktop ~]$ wget https://get.symfony.com/cli/installer -O - | bash
    --2022-11-12 16:41:00--  https://get.symfony.com/cli/installer
    Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
    Resolving get.symfony.com (get.symfony.com)... 2600:9000:21c3:5000:2:31b:afc0:93a1, 2600:9000:21c3:d600:2:31b:afc0:93a1, 2600:9000:21c3:cc00:2:31b:afc0:93a1, ...
    Connecting to get.symfony.com (get.symfony.com)|2600:9000:21c3:5000:2:31b:afc0:93a1|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 6100 (6,0K) [binary/octet-stream]
    Saving to: ‘STDOUT’

    -                    100%[====================>]   5,96K  --.-KB/s    in 0,009s  

    2022-11-12 16:41:01 (699 KB/s) - written to stdout [6100/6100]

    Symfony CLI installer

    Environment check
      [*] cURL is installed
      [*] Tar is installed
      [*] Git is installed
      [*] Your architecture (amd64) is supported

    Download
      Downloading https://github.com/symfony-cli/symfony-cli/releases/latest/download/symfony-cli_linux_amd64.tar.gz...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100 5227k  100 5227k    0     0   906k      0  0:00:05  0:00:05 --:--:-- 1144k
      Uncompress binary...
      Installing the binary into your home directory...
      The binary was saved to: /home/noel/.symfony5/bin/symfony

    The Symfony CLI was installed successfully!

    Use it as a local file:
      /home/noel/.symfony5/bin/symfony

    Or add the following line to your shell configuration file:
      export PATH="$HOME/.symfony5/bin:$PATH"

    Or install it globally on your system:
      mv /home/noel/.symfony5/bin/symfony /usr/local/bin/symfony

    Then start a new shell and run 'symfony'

    [noel@family-desktop ~]$ source .bashrc 
    [noel@family-desktop ~]$ cd dev
    [noel@family-desktop dev]$ mkdir symfony
    [noel@family-desktop dev]$ cd symfony/
    [noel@family-desktop symfony]$ symfony new --webapp pendular
    * Creating a new Symfony project with Composer
      (running /usr/bin/composer create-project symfony/skeleton /home/noel/dev/symfony/pendular  --no-interaction)

    Creating a "symfony/skeleton" project at "./pendular"
    Info from https://repo.packagist.org: #StandWithUkraine
    Cannot use symfony/skeleton's latest version v6.1.99 as it requires ext-iconv * which is missing from your platform.

    In CreateProjectCommand.php line 421:
                                                                                    
      Could not find package symfony/skeleton with stability stable in a version in  
      stallable using your PHP version, PHP extensions and Composer version.         
                                                                                    

    create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

                                                                                      
      unable to run /usr/bin/composer create-project symfony/skeleton /home/noel/dev  
      /symfony/pendular  --no-interaction

### Possible Solution

Open /etc/php/php.ini and uncomment `extension=iconv.so`

Then run again 

    [noel@family-desktop symfony]$ symfony new --webapp pendular
    * Creating a new Symfony project with Composer
      (running /usr/bin/composer create-project symfony/skeleton /home/noel/dev/symfony/pendular  --no-interaction)

    * Setting up the project under Git version control
      (running git init /home/noel/dev/symfony/pendular)

      (running /usr/bin/composer require webapp --no-interaction)

                                                                                      
    [OK] Your project is now ready in /home/noel/dev/symfony/pendular         

### Additional Context

My info 

OS: Manjaro 21.3 

PHP 8.1.12

Symfony CLI version 5.4.18 Symfony SAS (2022-11-09T16:06:39Z - stable)

**Comment by derrabus** [comment]
This should be reported to https://github.com/symfony-cli/symfony-cli instead.

**Comment by enfrte** [comment]
Reported to the link suggested, thanks.
