### ISSUE TITLE
Symfony-Validator: Strict-Mode does allow emails, which are invalid with RFC 5322

### ISSUE THREAD

**Issue by YellowPhoenix18** [symfony/symfony#48237]
### Symfony version(s) affected

4.4.41

### Description

The symfony-validator is offering a email-validation option with Email, which should in strict-mode only allow RCF 5322-valid email-addresses.

Sadly some which should be invalid when checking for RFC 5322 does not get flagged by the validator as invalid.

In my testings I have found following to be false-valid:
- あいうえお@example.com

### How to reproduce

- Create Entity with email and add Email-Validation to that entity.
- Create form with EmailType for the email-value and add data_class in OptionsResolver to the given Entity
- Test with html-validation disabled and the given email is beeing validated as valid

**Comment by xabbuh** [comment]
In strict mode Symfony uses the `NoRFCWarningsValidation` provided by the `egulias/email-validator` library. If it accepts some invalid e-mail addresses, those will need to be reported in their issue tracker: https://github.com/egulias/EmailValidator
