### ISSUE TITLE
Random Email Transports

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony#48258]
### Description

It's possible to have [Multiple Email Transports](https://symfony.com/doc/current/mailer.html#multiple-email-transports) but only first is picked when  `X-Transport` header is not added.

We send emails via multiple emails provider in order to see if stats are different or just for not be locked on provider or balancing.

WDYT about adding native transport balancing ?

It could be a default_transport_strategy parameter in FrameworkExtension with value "first" (default), "random" or a specific `X-Transport`

**Comment by MatTheCat** [comment]
Would [`roundrobin`](https://symfony.com/doc/current/mailer.html#load-balancing) fit your use-case?

Else I guess a similar keyword could be implemented.

**Comment by alamirault** [comment]
I didn't see it ! 

I expected this in [Multiple Email Transports](https://symfony.com/doc/current/mailer.html#multiple-email-transports) section

**Comment by derrabus** [comment]
@alamirault Feel free to submit a PR to the docs repository with a change that would've helped you.
