### ISSUE TITLE
[FrameworkBundle][RateLimiter] `no_limit` policy requires a limit to be configured

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#48268]
### Symfony version(s) affected

From v5.2.0-BETA3

### Description

#38665 exposed the `no_limit` policy to the configuration without taking its singularity into account. As such it requires the lock component to be installed and enabled, but also a `limit` to be configured (it would be ignored).

### How to reproduce

Configure a limiter with the `no_limit` policy:

```yaml
framework:
    rate_limiter:
        no_limit:
            policy: no_limit
```
and you will get an `InvalidConfigurationException`:

> The child config "limit" under "framework.rate_limiter.limiters.no_limit" must be configured: The maximum allowed hits in a fixed interval or burst

### Possible Solution

Do not mark `limit` as required and validate it’s set only for policies other than `no_limit`.

### Additional Context

I don’t think needing to enable the lock component to configure a `no_limit` limiter really is an issue, because you would not use only this policy.

**Comment by alexandre-daubois** [comment]
I gave it a try! :slightly_smiling_face: I definitely think this is a welcome improvement for the DX.
