### ISSUE TITLE
[DI] BC break in SF 6.2 ?

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#48286]
### Symfony version(s) affected

6.2.*

### Description

I have a [test](https://gist.github.com/lyrixx/0adb8fd414451596557871d2d9af5695) in my application that ensure all tests can boot. And now this test fails.

It's because ignored file / path are still in the `var/cache/test/AppKernelTestDebugContainer.xml`

For exemple :
```xml
    <service id="AppBundle\ActivityLogger\Messenger\Message\PushInfluxMetric" class="AppBundle\ActivityLogger\Messenger\Message\PushInfluxMetric" abstract="true">
      <tag name="container.excluded" source="in &quot;services/activity_logger.yml&quot;"/>
    </service>
```

I don't know if it's a BC break or not, but having these entry in the XML seems wrong to me anyway: 

1. some external tools rely on the container.xml to propose code completion
2. obviously, some classes are not services

### How to reproduce

Ignore some file in `service.yaml`, and constat they are listed in the dumped `container.xml`

**Comment by stof** [comment]
Maybe the XML dumping should skip all the `container.excluded` services.

**Comment by nicolas-grekas** [comment]
What's the failure like? These services are abstract anyway so they should likely be ignored in your test?

**Comment by lyrixx** [comment]
> Maybe the XML dumping should skip all the `container.excluded` services.

I agree 👍🏼 

> What's the failure like?

It tells me the service does not exist anymore, or has been inlined when I try to get it.

>  These services are abstract anyway so they should likely be ignored in your test?

Indeed, I didn't handle that case previously because I don't use abstract service in `src/`

**Comment by nicolas-grekas** [comment]
I'd prefer considering this as a bug in your test. Skiping abstract services is just the right thing to do. And hardcoding `container.excluded` looks like coupling to external concerns to me. It could also remove some info that readers of the xml might find useful (as phpstorm-plugin/etc).

**Comment by lyrixx** [comment]
I updated my test 👍🏼 

But the concern about external tools remain, isn't?

Theses "services" could be located in another section to avoid some issues I guess.

**Comment by nicolas-grekas** [comment]
The tools should adapt IMHO, no need to invent something else :shrug:

**Comment by lyrixx** [comment]
Let's close this one. I fixed my test quite easily, so it's fine for me.
