### ISSUE TITLE
The uid component should not be using __toString

### ISSUE THREAD

**Issue by Legion112** [symfony/symfony#48290]
### Description

Here is a [discussion](https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial/pull/3#issuecomment-460441229) of why it is terrible to have to __toSting for automatic casting.

It's better to remove it and ask people to use explicit converting it to string.
```
$uuid->toRfc4122();
```
instead of 
```
(string)$uuid
```

This is a BC break that would require a major release.

**Comment by wouterj** [comment]
Hi!

The referenced comment starts with "I prefer not to use ...". So this is more a subjective guideline than an objective rule.

The Uid component provides both methods for explicit string casting and the `__toString()` method, so you can use whatever fits the guidelines of your project.

I'm going to close this issue, as this is not worth a backwards compatibility break (BC breaks costs the ecosystem a lot, so we must limit the number of breaks as much as possible).

**Comment by nicolas-grekas** [comment]
I agree with @wouterj 
Also, this is a drawback of abusing explicit casts to work around strict mode. This is well described in this gist:
https://github.com/Girgias/unify-typing-modes-rfc#unintended-consequences-of-strict_type-mode
