### ISSUE TITLE
[symfony/browser-kit] The Request instance converted parameters with boolean value 'false' to the empty string

### ISSUE THREAD

**Issue by barmax** [symfony/symfony#48309]
### Symfony version(s) affected

6.1.3

### Description

Hello!

I have found not correct behaviour when we use the package `symfony/browser-kit`.

When we try send a request with a parameter with the boolean `false` value , the package transform the `false`-parameter to [an empty string](https://github.com/symfony/browser-kit/blob/6.1/Request.php#L42). 
It is the standard PHP behaviour, but the package breaks a logic of the http-requests.

### How to reproduce

Send a request with `false`-value of the paramenter by `symfony/browser-kit`.

Create the `Symfony\Component\BrowserKit\Request` with parameters that contains `false`-value:
```
$request = new Symfony\Component\BrowserKit\Request('test', 'test', ['test' => false]);
var_dump($request->getParameters());
```
Output:
```
array(1) { 
    ["test"]=> string(0) "" 
}
```

### Possible Solution

[Instead](https://github.com/symfony/browser-kit/blob/6.1/Request.php#L42):
```
array_walk_recursive($parameters, static function (&$value) {
    $value = (string) $value;
});
```

Do this:
```
array_walk_recursive($parameters, static function (&$value) {
    $value = is_bool($value) ? $value : (string) $value;
});
```

**Comment by stof** [comment]
Query-string parameters must be strings, not booleans. It is impossible for your app to receive an actual request containing a boolean there, so there is no reason to allow your tests to emulate it.

**Comment by barmax** [comment]
> Query-string parameters must be strings, not booleans. It is impossible for your app to receive an actual request containing a boolean there, so there is no reason to allow your tests to emulate it.

But we can send a `POST`-request with json contains boolean values and the request instance converted a `false`-value to the empty string.

**Comment by stof** [comment]
But when you send a JSON request, you need to use the dedicated BrowserKit method that does that, which does **not** store the non-encoded JSON body in this field of the Request.
And the test you added in your PR is *not* about submitting a POST request with a JSON body.

**Comment by xabbuh** [comment]
closing here since the current behaviour is the expected one (see also the comments in the linked pull request)
