### ISSUE TITLE
[DI] TestContainer method get breaks when requesting the service debug.file_link_formatter.url_format

### ISSUE THREAD

**Issue by sidux** [symfony/symfony#48311]
### Symfony version(s) affected

5.5

### Description

When using `TestContainer` (`test.service_container`) to request the service `debug.file_link_formatter.url_format` the `get` method breaks because it's typed `?object` and the service `debug.file_link_formatter.url_format` is string.

### How to reproduce

Create a Test that inherit from `KernelTestCase` and use the code bellow :

```php
  $kernel = self::bootKernel();
  $container = $kernel->getContainer()->get('test.service_container');
  $container->get('debug.file_link_formatter.url_format');
```

**Comment by MatTheCat** [comment]
It seems like `debug.file_link_formatter.url_format` is the only case of string service. I don’t think `ContainerInterface::get` signature will change so I guess we should use a value object instead of a string :thinking:

**Comment by nicolas-grekas** [comment]
$container->get() must return objects because services are objects, but private services don't have this limitation.
The test container exposes private services for convenience's need, and this creates this situation.
Just don't request that service from the test container :shrug:
