### ISSUE TITLE
[HttpClient] should not encode best-practice characters in query-parameters (@:!;,*)

### ISSUE THREAD

**Issue by kohlerdominik** [symfony/symfony#48315]
### Symfony version(s) affected

6.1.7

### Description

The http client currently uses [http_build_query](https://www.php.net/manual/en/function.http-build-query.php), which encodes way to many characters. More and more URLs use special characters like [ @ : ! ; , * ], as they are not http-relevant. I saw, that this characters are accepted by the Symfony Routing Component, for example: [UrlGenerator::30](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L30)

### Real world example
I'm currently working with an API, that expects [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) DateTime strings in the URL. 

RFC3339 states, that

> [[ISO8601](https://www.rfc-editor.org/rfc/rfc3339#ref-ISO8601)] dates SHOULD be used in new protocols on the Internet

So usage of ISO8601 is defintively encouraged.

But as the `:` characters is encoded by the HttpClient, the parameter looking like `2022-11-24T18:00:00` is getting encoded, and therefore not accepted by the backend.

### How to reproduce

```php
HttpClient::create()->request('GET', 'your-url', [
    'query' => [
        'dateTime' => '2022-11-24T18:00:00'
    ]
]);


```

### Possible Solution

Instead of using http_build_query, use a similar implementation like `Symfony\Component\Routing\Generator\UrlGenerator `

### Comparisions:

Browsers: Neither Microsoft Edge nor Firefox encode the characters above in URLs.
[Postman ](https://www.postman.com/)also sends them without encoding.

**Comment by nicolas-grekas** [comment]
That'd work for me. Up for giving a PR a try?

**Comment by adioe3** [comment]
Ran into this today: an API doesn't accept

```
fieldset%5B%5D=GUEST_DETAILS
```
but does
```
fieldset[]=GUEST_DETAILS
```

and this is for WIX.com APIs so basically can't use the client with any of their APIs :disappointed:

**Comment by nicolas-grekas** [comment]
Please give #49299 a try
