### ISSUE TITLE
[TraceableHttpClient] Timing issues with "fire & forget" requests

### ISSUE THREAD

**Issue by cleptric** [symfony/symfony#48326]
### Symfony version(s) affected

v6.1.7

### Description

While adding HTTP client tracing in the Sentry Symfony Bundle, I noticed an issue when tracing "fire & forget" requests.

As far as I can tell, there is no reliable way to determine if the request is completed without explicitly calling `$response->getContent()` or `$response->toArray()`.

In this case, the `StopwatchEvent` will only be stopped during `TraceableResponse::__destruct`

### How to reproduce

```php
$response = $this->client->request('GET',
    'https://google.com'
);
```

### Additional Context

https://github.com/getsentry/sentry-symfony/pull/606#issuecomment-1326494095

**Comment by stof** [comment]
If you intend to forget the request (without actually forgetting the Response object so it is not destructed yet), there is indeed no PHP code that will run at the exact time the last network packet is received. That's a direct consequence of the design of the HttpClient API meant to support concurrency.

**Comment by cleptric** [comment]
Interesting, this is definitely a good observation.

```
$this->client->request('GET',
    'http://google.com'
);
```

Not assigning the response to a variable does indeed give me the correct timing.
I'll point this out in our docs.

Thanks!

**Comment by stof** [comment]
Note however that doing 2 requests like that in your code will make them sequential and not concurrent (as the destructor forces waiting until the status code to enforce that failed requests are handled and the destructor is called immediately in such code)
