### ISSUE TITLE
addMethodCall() with a static method as target won't produce any effect

### ISSUE THREAD

**Issue by inmarelibero** [symfony/symfony#48355]
### Symfony version(s) affected

5.4.15

### Description

While running a cli command, calling `addMethodCall()` in a Compiler Pass with a static method as target won't produce any effect unless the target service is a dependency of the cli command.

The bug seems to appear also without using static properties and method, but couldn't reproduce it easily.

### How to reproduce

Clone https://github.com/inmarelibero/symfony-addMethodCall-bug and follow instructions in `README.md` to reproduce the issue

**Comment by MatTheCat** [comment]
Yes this is expected: `addMethodCall` will run against an instance when it’s required, which is not the case when you reference directly the class’ property.

If you need an instance, you have to inject it.

**Comment by GromNaN** [comment]
Yes, this is the expected behaviour. Services are instanced when requested.
You can use the Kernel::boot method to execute init code.

**Comment by inmarelibero** [comment]
> Yes this is expected: you can change an **instance**’s static property at runtime, but not a **class**’.
> 
> If you need an instance, you have to inject it.

@MatTheCat  if it behaves like that, why does it work only when the service is a direct dependence of the command?
I mean, the Compiler Pass should populate both services, or no one

**Comment by GromNaN** [comment]
If you look at the compiled container in var/cache, you will see the method is called only when the service is injected at runtime. 
In the BuggedCommand, the service is not injected by the DIC at all.

**Comment by inmarelibero** [comment]
> If you look at the compiled container, you will see the the method is called only when the service is injected at runtime. In the BuggedCommand, the service is not injected by the DIC at all.

@GromNaN correct, and I'm aware about the fact that a service is only instantiated when needed

I gave for grant that `addMethodCall()` would call anyway the static method no matter what, and I didn't consider that is the service is not used through the container, it's never instantiated and `addMethodCall()` does not participate at all

**Comment by inmarelibero** [comment]
thanks @GromNaN @MatTheCat it's a bit subtle but you clarified me, I think this is not a bug but just a little unexpected (to me)

I'll try with working on `Kernel::boot()` as suggested by @GromNaN , thanks!
