### ISSUE TITLE
[HttpFoundation] setContent missing in Request class

### ISSUE THREAD

**Issue by luxferoo** [symfony/symfony#48357]
### Description

I'm currently implementing an event subscriber to sanitize http inputs but I'm not able to access to $content because it's protected while $request is public. Is it possible to add a setter ? otherwise anyone with the same need is forced to use Request::initialize like the following :

```php
  $event->getRequest()->initialize(
            $request->query->getIterator()->getArrayCopy(),
            $sanitizedRequest,
            $request->attributes->getIterator()->getArrayCopy(),
            $request->cookies->getIterator()->getArrayCopy(),
            $request->files->getIterator()->getArrayCopy(),
            $request->server->getIterator()->getArrayCopy(),
            $sanitizedContent,
        );
```

**Comment by chalasr** [comment]
I'm not sure overwriting the "raw" request content is something we want to support.

**Comment by luxferoo** [comment]
@chalasr I think we should consider $content as $request so we can apply middleware logics to it

**Comment by luxferoo** [comment]
Hi @chalasr ,

1. It's already possible to override it using using initialize
2. what I'm asking is to be able to write to $content and not 'php://input'

**Comment by nicolas-grekas** [comment]
This looks like a rare use case. As there is a way to do it, I don't thing we need to make it simpler.

**Comment by luxferoo** [comment]
@nicolas-grekas in my opinion it's the opposite, nowadays the majority of web APIs are consumed by sending raw json payloads, and for example if I want to trim all received string properties using Node/Express I just need to create a middleware to do so. But in the case of Symfony I can only perform the same objectif for formData payloads otherwise I'll need to handle each API by itself.

**Comment by GromNaN** [comment]
The `$request->request` contains the form data and we plan to add `$request->payload` (see https://github.com/symfony/symfony/pull/47938) to contain any data extracted from the request contents, especially the JSON requests. This new `payload` property being a `ParameterBag`, it will be possible to alter the data. 
Would it satisfy your need?

**Comment by luxferoo** [comment]
@GromNaN yes that's perfect for me and everyone in the the same need 🙏 thank you very much

**Comment by luxferoo** [comment]
@GromNaN when do you think it would be available please ?

**Comment by WebMamba** [comment]
If we look at the PR @GromNaN mentions it should be available in 6.3, but nothing official yet 😁

**Comment by chalasr** [comment]
As said, we don't really want to promote altering raw user inputs at this level. If some on-going improvements make that easier as a side effect that's fine, but we won't add a dedicated method for this purpose. Thanks

**Comment by luxferoo** [comment]
Hi everyone, I'm sorry to reopen this issue but maybe I wasn't clear with the problem I'm facing.

**Comment by luxferoo** [comment]
@chalasr  Maybe I wasn't clear enough but what I was looking for is done in this PR : https://github.com/symfony/symfony/pull/49614

Thanks for the good job SF 👌
