### ISSUE TITLE
[String] Slugger with Emoji throws IntlException for not supported locale

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#48364]
### Symfony version(s) affected

6.2.0

### Description

In @sulu we try to add the Slugger with Emoji support. Currently the Slugger will hardly fail when the locale is not found with `IntlException`: https://github.com/sulu/sulu/actions/runs/3554459366/jobs/5970575754#step:10:578

### How to reproduce

```php
$slugger = new \Symfony\Component\String\Slugger\AsciiSlugger();
$slugger = $slugger->withEmoji();
$slugger->slug('Menus with 🍕 or 🍝', '-', 'de-at');
```

### Possible Solution

Catch exception in fallback to normal slug for not supported locale.

### Additional Context

We currently don't know which locales are supported by `withEmoji` and which ones not. Which ends up in strange code if we need to handle that ourselves:

```php
try {
    $slug = $this->sluggerWithEmojiSupport->slug($part, '-', $languageCode);
} catch (\IntlException $e) {
    $slug = $this->sluggerWithoutEmojiSupport->slug($part, '-', $languageCode);
}
```

------

/cc @lyrixx What do you think?

**Comment by lyrixx** [comment]
Indeed, this is not really DX friendly! 

@nicolas-grekas any recommendation here?

**Comment by nicolas-grekas** [comment]
> Catch exception in fallback to normal slug for not supported locale.

I suppose this is the way?

Alternatively, we might want to use a fallback locale?

Another option would be to *remove* the emojis from the slug. I know @fancyweb is considering this. But maybe that'd be solved by the fallback-locale option, by specifying a special `skip` locale?

**Comment by nicolas-grekas** [comment]
Let's make `withEmoji()` final if we anticipate that we might need to change its signature?
6.2.0 is around the corner.

**Comment by fancyweb** [comment]
I think we expect a locale with `_` and not with `-`. Shouldn't we first fall back to the "parent locale" `de`?

**Comment by alexander-schranz** [comment]
I think we will need todo also the `str_replace('-', '_', 'de-at')` that the fallback works. I need to recheck sometime the whole locale handling and how it works in symfony.

Mostly we have urls like `/de-at` and but I think a normalizer would make sense here translator and other kind of services get it as `de_AT` which I think is the more standardized format. Symfony does I think not do any normalization with the request locale? 

PS: Thx for the quick fix 👍
