### ISSUE TITLE
Dotenv is not working

### ISSUE THREAD

**Issue by madanzes** [symfony/symfony#48377]
### Symfony version(s) affected

4.4.45

### Description

The dotenv loads well but before 1 week the same code breaks the website and doesnt throw any error in logs
use Symfony\Component\Dotenv\Dotenv;
$dotenv = new Dotenv();

### How to reproduce

use Symfony\Component\Dotenv\Dotenv;
$dotenv = new Dotenv();

use this code in any php file

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
