### ISSUE TITLE
Memory leak with functional tests (Behat) 

### ISSUE THREAD

**Issue by yobrx** [symfony/symfony#48382]
### Symfony version(s) affected

6.2-RC2

### Description

I have a massive memory leak with my behat tests on a big application : 
- **713MB** after 10 scenarios with **6.2-RC2** _vs_ **250MB** with **6.1**, and crash after around 50 scenarios (limit of **2GB** memory)
- Time executions are equals.

There is an improvement compared to the 6.2-rc1 which crashes after 20 scenarios.

Screenshot from Blackfire :

[Symfony 6.1](https://user-images.githubusercontent.com/292402/204493877-a54aadd6-0cc5-4987-a95e-931439a85525.png)

[Symfony 6.2-RC2](https://user-images.githubusercontent.com/292402/204493882-b2a27952-ee2e-416d-b499-7d38ba0e1c2d.png)

### How to reproduce

I dont' have facility to reproduce the bug, run a lot of functional tests on a big project...

**Comment by guillaumesmo** [comment]
I also notice memory leaks in functional tests in Symfony 6.2 RC1/RC2, I'm not using Behat though, just phpunit bridge with Symfony functional tests (WebTestCase)

I was not able to identify which part of my test is causing the memory leak yet

**Comment by guillaumesmo** [comment]
After some more digging I found out that the memory leak appears since #46752

@yobrx could you try the following (from your clean working 6.1 composer install) to see if you have the same issue?

```
composer require 'symfony/dependency-injection:6.2.x-dev#24f9ec3e342e31bc3d332da5b84919f05ab1144e' 'symfony/var-exporter:6.2.x-dev#0802d1ad23bc5a0c7349f48ad647694670d8aed7'
# run tests, should work fine
composer require 'symfony/dependency-injection:6.2.x-dev#2db1a30537871a49dc3372e89ef6e8c6e0b656c0'
# run tests, should have memory issue
```

also the advantage of Blackfire is that you can compare the 2 profiles if I'm not mistaken, so you should be able to see where the memory differences are located

**Comment by yobrx** [comment]
Hmm sorry, it doesn't work because i have a dependency with `symfony/proxy-manager-bridge` and `friends-of-behat/symfony-extension`.

I made a comparaison with my two profilings on my first message, and it is much more readable...

![blackfire io_profiles_compare_a74aecbb-af95-46eb-8126-b20cbc4bbae1 56ac5ef9-a916-45a9-b572-1f14e166675f_graph_settings%5Bdimension%5D=pmu settings%5Bdisplay%5D=landscape settings%5BtabPane%5D=nodes selected= callname=main() constraintDoc=](https://user-images.githubusercontent.com/292402/204759197-7f79855f-b203-4a25-a9da-4fe0ade2d402.png)

**Comment by nicolas-grekas** [comment]
I'd love to have a reproducer to play with. Could anyone provide one?

**Comment by u03c1** [comment]
I notice the same thing today on a side project. Upgrading from 6.1.6 to 6.2.0 No behat, only WebTestCase. 

Before upgrade phpunit reports max memory usage to ~180Mo. After upgrade it failed with Exhausted memory.  Using MEMORY_LIMIT=-1, all tests run smoothly, but max memory usage show ~800Mo. 

For now I failed to isolate it as a simple reproducer.

**Comment by nicolas-grekas** [comment]
I also take full apps :)

**Comment by guillaumesmo** [comment]
@nicolas-grekas, thanks for your help on this. I was able to reproduce with just the following (also pushed to a github repo, see bottom):

```shell
symfony new test-project
cd test-project
composer require orm test
```

```php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    public function __construct(private EntityManagerInterface $entityManager)
    {
    }

    #[Route('/test')]
    public function index(): JsonResponse
    {
        return $this->json(['test']);
    }
}
```

```php
<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class TestControllerTest extends WebTestCase {
    public function test()
    {
        $client = self::createClient();
        $client->request('GET', '/test');
        self::assertResponseIsSuccessful();
        $client->request('GET', '/test');
        self::assertResponseIsSuccessful();

        gc_collect_cycles();
        dump(memory_get_usage()/1024/1024);
    }
}
```

I'm using "PHP 8.1.13 (cli) (built: Nov 24 2022 20:36:17) (NTS)" on MacOS. When running  `bin/phpunit --repeat 100` on **Symfony 6.1** (with a warm cache) the output remains stable at around **16MB**. When running the same on Symfony 6.2, the memory usage increases at every iteration from 16MB to **25MB**. 

Of course this is an unrealistic small project, so the memory increase on every test is relatively small, but on one of my customers' project memory goes up 25MB in each test and it doesn't "go down" like it did in Symfony 6.1

For you convenience I have pushed this reproducer to a [github repo](https://github.com/guillaumesmo/symfony-issue-48382)

```shell
git clone git@github.com:guillaumesmo/symfony-issue-48382.git
cd symfony-issue-48382
composer install
bin/phpunit --repeat 100 # memory leak visible in output
git revert --no-commit HEAD # reverts update to Symfony 6.2
composer update
bin/phpunit --repeat 100 # memory leak NOT visible in output

composer remove symfony/proxy-manager-bridge
composer require 'symfony/dependency-injection:6.2.x-dev#24f9ec3e342e31bc3d332da5b84919f05ab1144e' 'symfony/var-exporter:6.2.x-dev#0802d1ad23bc5a0c7349f48ad647694670d8aed7'
bin/phpunit --repeat 100 # memory leak NOT visible in output
composer require 'symfony/dependency-injection:6.2.x-dev#2db1a30537871a49dc3372e89ef6e8c6e0b656c0'
bin/phpunit --repeat 100 # memory leak visible in output
```

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, it's perfect to work on this.
I figured out that the way lazy-initializers are stored currently prevents gargage collection of lazy services.
I'm on it, blocked by https://github.com/php/php-src/issues/10043 for now, but on it :crossed_fingers:

**Comment by gnito-org** [comment]
Not sure if it's related to this issue, but since upgrading to 6.2 my PHPUnit tests randomly fail with an error that some PHP file could not be loaded because there are too many files open.

This is on Linux.

It happens when PHPUnit steps through many PHP files, such as the Controller directory tests.

`ulimit -n` is 1024 by default. The error goes away when one increases the limit to 4096.

This error never happened with 6.1.

Same application, same PHPUnit tests. Version 6.1 works with ulimit = 1024, 6.2 crashes with "too many files open".

**Comment by nicolas-grekas** [comment]
@gnito-org please try the patch in https://github.com/symfony/symfony/pull/48461 to know if this is related or not.

**Comment by yobrx** [comment]
@nicolas-grekas Thanks a lot ! All my tests are OK and no longer exceeds 250MB :tada:

**Comment by gnito-org** [comment]
@nicolas-grekas Unfortunately this fix did not fix the [file limit problem](https://github.com/symfony/symfony/issues/48382#issuecomment-1336400157).

**Comment by nicolas-grekas** [comment]
Then it's likely unrelated. Please open a dedicated issue and provide a reproducer :pray:
