### ISSUE TITLE
[6.2] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Console\Command\Command" not found in mailer/Command/MailerTestCommand.php:27

### ISSUE THREAD

**Issue by featuriz** [symfony/symfony#48415]
### Symfony version(s) affected

6.2

### Description

After composer update. When I run I get error as follows,
```sh
[Thu Dec  1 10:01:10 2022] PHP 8.1.6 Development Server (http://localhost:8091) started
[Thu Dec  1 10:01:12 2022] 127.0.0.1:58590 Accepted
[Thu Dec  1 10:01:13 2022] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Console\Command\Command" not found in /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/mailer/Command/MailerTestCommand.php:27
Stack trace:
#0 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/composer/ClassLoader.php(571): include()
#1 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/sudhakar/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php(392): class_exists('Symfony\\Compone...')
#4 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(73): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#5 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/dependency-injection/ContainerBuilder.php(721): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#8 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/http-kernel/Kernel.php(487): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#9 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/http-kernel/Kernel.php(709): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#10 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/http-kernel/Kernel.php(172): Symfony\Component\HttpKernel\Kernel->preBoot()
#11 /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/public_html/index.php(20): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
  thrown in /home/sudhakar/SudhakarK/NB/2022/MFW/FZMFW/vendor/symfony/mailer/Command/MailerTestCommand.php on line 27
```

### How to reproduce

```json
"require": {
        "doctrine/annotations": "^1.13",
        "google/recaptcha": "* 1.2.4",
        "symfony/config": "^6.2",
        "symfony/dependency-injection": "^6.2",
        "symfony/form": "^6.2",
        "symfony/framework-bundle": "^6.2",
        "symfony/http-foundation": "^6.2",
        "symfony/http-kernel": "^6.2",
        "symfony/mailer": "6.1", // To run now stay in 6.1
        "symfony/routing": "^6.2",
        "symfony/security-csrf": "^6.2",
        "symfony/twig-bundle": "^6.2",
        "symfony/validator": "^6.2",
        "symfony/yaml": "^6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "^6.2",
        "symfony/css-selector": "^6.2",
        "symfony/web-profiler-bundle": "^6.2",
        "twbs/bootstrap": "^5.2"
    },
```

### Possible Solution

"symfony/mailer": "6.1"

**Comment by xabbuh** [comment]
see #48416

**Comment by featuriz** [comment]
Hay guys, https://github.com/symfony/symfony/commit/40731aa9b6508bb803d1ce02db88ca5f0badb050
not fixed my issue. The error is still the same.

To be clear that **I'M NOT USING SYMFONY/CONSOLE** in my project.

If I install symfony/console it works. I don't need that for my project. Is it highly required to install symfony/console to install mailer v6.2?

**Comment by fancyweb** [comment]
The patch has been merged but is not released yet. Did you test it manually and it still doesn't work for you?

**Comment by featuriz** [comment]
@fancyweb Do you mean https://github.com/symfony/symfony/commit/40731aa9b6508bb803d1ce02db88ca5f0badb050 ?
Yes I do test manually. It has only one change 
` if (!class_exists(MailerTestCommand::class) || !$this->hasConsole()) {` right?
I mentioned it in my previous comment https://github.com/symfony/symfony/issues/48415#issuecomment-1334777940

**Comment by featuriz** [comment]
@xabbuh  and @fabpot : Please read this issues title. I have mentioned it clearly **Class "Symfony\Component\Console\Command\Command" not found in mailer/Command/MailerTestCommand.php** .

Lookup: **https://github.com/symfony/symfony/pull/48416** this one. Because 48416 says **don't register the MailerTestCommand class if there is no symfony/console installed** So the priority must goes to console.

Proper solution is: 

```php
if (!$this->hasConsole() || !class_exists(MailerTestCommand::class)) {
    $container->removeDefinition('console.command.mailer_test');
}
```
I have pointed this in https://github.com/symfony/symfony/commit/40731aa9b6508bb803d1ce02db88ca5f0badb050#commitcomment-92000787

If we do class_exists check on MailerTestCommand class. On line 27 `final class MailerTestCommand extends Command`. The file MailerTestCommand depends on Console.

**To be noted:-** I'm working on [Building your own Framework with the MicroKernelTrait](https://symfony.com/doc/current/configuration/micro_kernel_trait.html)

**Comment by xabbuh** [comment]
If the issue still isn’t fixed for you, please create a small example application that allows us to reproduce it. Currently I do not see how this could still happen, but I may be missing something.

**Comment by kbond** [comment]
@xabbuh see https://github.com/zenstruck/messenger-test/pull/53 - test suite fails on 6.2 (even 6.2.1)

@featuriz's solution above solves. We also have this issue with the new messenger StatsCommand.

[I'll create a PR](https://github.com/symfony/symfony/pull/48521)

**Comment by featuriz** [comment]
> [PR](https://github.com/symfony/symfony/pull/48521)

Thanks. Finally done 👍
