### ISSUE TITLE
[6.2] [Profiler] Unable to find template "@WebProfiler/Icon/no-gray.svg"

### ISSUE THREAD

**Issue by jdelaune** [symfony/symfony#48412]
### Symfony version(s) affected

6.2.0

### Description

Get this error:

```
Unable to find template "@WebProfiler/Icon/no-gray.svg" (looked into: /var/www/auth/vendor/symfony/web-profiler-bundle/Resources/views).
```

When going to to the configuration page in the profiler `/_profiler/{token}?panel=config`

### How to reproduce

Open the profiler and go to the configuration page.

### Possible Solution

Include the asset

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by aurelienk** [comment]
Same issue after upgrade.
After clean vendor/cache folders it's works fine.

**Comment by javiereguiluz** [comment]
I can't find any reference to `no-gray.svg` file in the Symfony 6.2 code. Try cleaning `cache/` directory and if the error persists, please create a reproducer like @xabbuh suggested. Thanks.

**Comment by jdelaune** [comment]
Ah yes after another clear cache it goes away. This was after an upgrade as well.
