### ISSUE TITLE
Mailer message has empty context in 6.2

### ISSUE THREAD

**Issue by darthf1** [symfony/symfony#48423]
### Symfony version(s) affected

6.2.0

### Description

When upgrading to SF 6.2.0, a few of my tests start to fail because the `$message->getContext()` is empty.

### How to reproduce

```php
public function testSomething(): void
{
    ....

    self::assertQueuedEmailCount(1);

    /** @var MessageEvent $messageEvent */
    $messageEvent = self::getMailerEvents()[0];
    $message = $messageEvent->getMessage();
    self::assertInstanceOf(TemplatedEmail::class, $message);

   <-- so far so good -->

    $signedUrl = $message->getContext()['url']; <-- this errors, context is empty.
}
```

![image](https://user-images.githubusercontent.com/17253332/205044963-0c9bfef7-b4b8-4642-be50-023bf3b4491c.png)

On 6.1, the context is not empty:

![image](https://user-images.githubusercontent.com/17253332/205045310-b6d9a2c6-8dd7-4a75-b08d-17f2752812f1.png)

Comparing the screenshot; also the `htmlVariable` template is different.

I send emails, by creating a `Symfony\Bridge\Twig\Mime\TemplatedEmail` and sending it via `Symfony\Component\Mailer\MailerInterface::send()`. I inject the context as a key value array pair via `Symfony\Bridge\Twig\Mime\TemplatedEmail::context()` method.

**Comment by COil** [comment]
May be related : https://github.com/symfony/mailer/commit/7b355fca167fa5302c77bccdfa0af4d7abc6bd8c#r91656004

**Comment by stephanvierkant** [comment]
See #47993
