### ISSUE TITLE
ZSH autocomplete error without suggestions

### ISSUE THREAD

**Issue by WarriorXK** [symfony/symfony#48426]
### Symfony version(s) affected

6.2

### Description

If using the ZSH autocomplete feature, an error is thrown if no values are provided for autocompletion.

`<application> <command> Warning:\ Undefined\ variable\ \$values\ in\ /Users/kevinmeijer/BFUtils/vendor/symfony/console/Completion/Output/ZshCompletionOutput.php\ on\ line\ 33`

### How to reproduce

Enable autcompletion for a ZSH shell, press TAB to autocomplete an argument and/or option while not providing any suggestions.

### Possible Solution

This should be an easy fix by simply defining `$values = [];` at the start of `write()` in Completion/Output/ZshCompletionOutput.php

**Comment by stof** [comment]
Can you send a PR with your fix ? It seems legit

**Comment by WarriorXK** [comment]
> Can you send a PR with your fix ? It seems legit

Done. Please let me know if anything else is required.
