### ISSUE TITLE
[6.2] \Symfony\Bundle\SecurityBundle\Security constants show deprecation warnings

### ISSUE THREAD

**Issue by bazo** [symfony/symfony#48425]
### Symfony version(s) affected

6.2

### Description

after upgrading to 6.2 i got deprecation errors from phpstan that since Symfony 6.2, use \Symfony\Bundle\SecurityBundle\Security::LAST_USERNAME instead

so i changed all usages of Symfony\Component\Security\Core\Security to Symfony\Bundle\SecurityBundle\Security
but these errors still persist as \Symfony\Bundle\SecurityBundle\Security extends LegacySecurity which is Symfony\Component\Security\Core\Security that has the deprecations annotations :)

### How to reproduce

use any constant from \Symfony\Bundle\SecurityBundle\Security

### Possible Solution

don't extend the old class :)

**Comment by gndk** [comment]
The constants moved to [Symfony\Component\Security\Http\SecurityRequestAttributes\Security](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Security/Http/SecurityRequestAttributes.php#L23). See https://github.com/symfony/symfony/pull/48414

**Comment by OskarStark** [comment]
To remove the deprecations, you should, as already mentioned by @gndk, the new constants.

**Comment by xabbuh** [comment]
the upgrade files have been improved around this in #48414
