### ISSUE TITLE
[Mime] BC Break: BodyRenderer destroys Message::context - upgrade show-stopper

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#48439]
### Symfony version(s) affected

6.2.0

### Description

The [BodyRenderer](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Bridge/Twig/Mime/BodyRenderer.php) resets the `Message::context([])`, which was introduced by this [commit](https://github.com/symfony/symfony/commit/cc3b87189dbd99afd82a77f4986eeacabbacc276#diff-0453738cc0896c4fc41a7e2d05b61e69b839241d5bbb0b889d77c706db1e4152R73).

This is a BC break and it is highly problematic (show-stopper for upgrading to V6.2), because apps (mine included) use the `Message::context` to carry meta data that is inspected and used by message event subscribers. For example, "What is the ID of the category in which this particular email must be logged as having been successfully sent?" 

### How to reproduce

Add something to the context array during message creation and sending, and then inspect the message context in a message event subscriber that fires after the message has been sent. The context is empty.

### Possible Solution

Do not reset the context in `BodyRenderer`, or unset only the array contents that would cause problems (duplicate message sending) further downstream. But, don't empty the context array completely.

**Comment by fabpot** [comment]
It looks a wrong usage of the context, which is there only for the Twig templates.
Anyway, what about having your listener being triggered early on and before the body renderer?

**Comment by gnito-org** [comment]
How would I know that the email was successfully sent before the body renders?

**Comment by stof** [comment]
Then don't abuse the rendering context to perform this logic.

**Comment by gnito-org** [comment]
If you want context to be exclusively for Symfony internal use, please add a comment to that property. It's public and it's very generally named, so it's easy to assume that it can be used by apps.

I could extend Email or TemplatedEmail and add my own custom meta data property.

**Comment by gnito-org** [comment]
> Then don't abuse the rendering context to perform this logic.

Abuse is a very strong word, given how generally the propery is named.

**Comment by gnito-org** [comment]
Seeing that I have an alternative solution, and that you folks are extremely defensive on this issue, I'll close the issue and implement the alternate solution.
