### ISSUE TITLE
MicroKernelTrait

### ISSUE THREAD

**Issue by ramazantufekci** [symfony/symfony#48436]
### Symfony version(s) affected

6.1

### Description

Creating your own Framework with MicroKernelTrait How do we add doctrine

### How to reproduce

composer require orm-pack 
Cannot autowire argument $doc of "App\Controller\MicroController::randomNumber()": it references class "Symfony\Bridge\Doctrine\ManagerRegistry" but no such service exists.

composer.json content
```json
{
    "require": {
        "symfony/config": "^6.2",
        "symfony/http-kernel": "^6.2",
        "symfony/http-foundation": "^6.2",
        "symfony/routing": "^6.2",
        "symfony/dependency-injection": "^6.2",
        "symfony/framework-bundle": "^6.2",
        "symfony/yaml": "^6.2",
        "symfony/twig-bundle": "^6.2",
        "symfony/web-profiler-bundle": "^6.2",
        "doctrine/annotations": "^1.13",
		"doctrine/orm": "^2.11.0",
        "symfony/orm-pack": "^2.2",
        "sensio/framework-extra-bundle": "^6.2"
    },
	"autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    }
}
```

**Comment by nicolas-grekas** [comment]
Packs are supposed to be used together with symfony/flex, which I don't see in your deps.

Which makes me wonder BTW: should we add flex as an explicit deps to all packs? /cc @symfony/mergers

**Comment by lyrixx** [comment]
It makes sens to me. But does composer plugin work even for a transitive deps?

**Comment by nicolas-grekas** [comment]
Closing as this is an unsupported use case.
