### ISSUE TITLE
[6.2] [Profiler] Toggler bug and search empty

### ISSUE THREAD

**Issue by youlead-bow** [symfony/symfony#48437]
### Symfony version(s) affected

6.2

### Description

Using the new profiler, I encountered 2 issues:

1. In the Forms tab of the profiler, the form tree no longer works. Nothing happens if you click on the plus pictograms.
It does not display what it should and the picto does not change.

2. When you want to display the last 10 urls, the list is always empty. The profiler search doesn't work.

For information, I emptied all the Symfony and browser cache, reinstalled the package but nothing changed.

### How to reproduce

Open the profiler and go to the forms page or the last 10.

### Possible Solution

1. Add line in form.html.twig: toggler.initButtons(document.querySelectorAll('a.toggle-button'));
For the picto I don't know what's wrong

2. I don't know

### Additional Context

![toggler](https://user-images.githubusercontent.com/31312163/205253874-92c3c447-39cf-4d9a-9a25-a6d5e839423b.jpg)
![empty_search](https://user-images.githubusercontent.com/31312163/205253877-49cfc943-5c4e-4d22-90fb-0dbde5d75e94.jpg)

**Comment by MatTheCat** [comment]
Good catch :+1:  `Toggler.initButtons` is never called in `Collector/form.html.twig`

Not able to reproduce the issue about the empty URL list though. Do you have a `profiler/index.csv` file in your cache folder?
