### ISSUE TITLE
[6.2] [doctrine-bridge] EntityValueResolver priority is too high and there is no way to be skipped by a custom ParamCoverter

### ISSUE THREAD

**Issue by marforon** [symfony/symfony#48433]
### Symfony version(s) affected

6.2

### Description

[EntityValueResolver](https://github.com/symfony/doctrine-bridge/blob/6.2/ArgumentResolver/EntityValueResolver.php) introduced in Symfony 6.2 priority (110) is higher than [RequestAttributeValueResolver ](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestAttributeValueResolver.php) priority (100) which makes ParamConverter unusable in some cases. Only UserValueResolver has a higher priority.

### How to reproduce

Consider this controller action:
```php
    #[Route('/asset-file/{assetFile}/distribute', name: 'distribute', methods: [Request::METHOD_POST])]
    #[ParamConverter('jwDistribution', converter: SerializerParamConverter::class)]
    public function distribute(AssetFile $assetFile, JwDistribution $jwDistribution): JsonResponse
    {
           return new JsonResponse();
    }
```
In this case, `AssetFile` and `JwDistribution` represent Doctrine's entities, but `JwDistribution` doesn't exist in repository and should be converted by a custom converter (serializer). Instead, `EntityValueResolver` is used also for `JwDistribution` and it obviously fails to convert (because it's entity object without identifier). That must be at least some kind of regression. Could we do something about it?

### Possible Solution

At least 
RequestAttributeValueResolver should has a higher priority than EntityValueResolver.

**Comment by nicolas-grekas** [comment]
Thanks for the report. Can you please confirm that #48489 would fix the issue?

**Comment by marforon** [comment]
@nicolas-grekas thanks for the response. Unfortunately, it won't help. The problem is it will continue to execute a find method in EntityManager https://github.com/symfony/symfony/blob/6780b02407ce02d0c2b5302f071dffd6a533c0f9/src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php#L59 and in my case, the identifier from API is null (new entity). It will throw this exception https://github.com/doctrine/orm/blob/2.13.x/lib/Doctrine/ORM/EntityManager.php#L452

It would help if the EntityValueResolver would be skipped if the identifier is null.

EDIT: `getIdentifier()` method returns `JwDistribution` object from the request, because `ParamConverter` already set the attribute in SerializerParamConverter, so this doesn't help https://github.com/symfony/symfony/blob/6780b02407ce02d0c2b5302f071dffd6a533c0f9/src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php#L104...

**Comment by nicolas-grekas** [comment]
OK thanks. Can you provide a small reproducing app that I could play with locally to work on this?

**Comment by stof** [comment]
having higher priority than RequestAttributeValueResolver is the intended purpose, as this supports essential features when using only the value resolver system.

But we should indeed add a condition to skip this `find()` when the attribute is already an object, to improve support for the case of mixing those value resolvers with the legacy ParamConverter system of SensioFrameworkExtraBundle.
Side note: you should convert your SerializerParamConverter to an argument resolver instead.

**Comment by marforon** [comment]
> OK thanks. Can you provide a small reproducing app that I could play with locally to work on this?

I will do so later today or tomorrow. 

> having higher priority than RequestAttributeValueResolver is the intended purpose, as this supports essential features when using only the value resolver system.
> 
> But we should indeed add a condition to skip this `find()` when the attribute is already an object, to improve support for the case of mixing those value resolvers with the legacy ParamConverter system of SensioFrameworkExtraBundle. Side note: you should convert your SerializerParamConverter to an argument resolver instead.

Skipping the EntityValueResolver if the attribute is already an object would help. We are going to migrate to an argument resolver sooner or later, but to be honest I miss some option to skip this visitor pattern which iterates the whole stack of arguments resolvers (it's also not the best thing to do for performance reasons). It would be cool to add some attribute for parameters which would allow to define a specific argument resolver right away and skip the whole process with priority.

**Comment by nicolas-grekas** [comment]
>  But we should indeed add a condition to skip this find() when the attribute is already an object

I updated #48489 to follow this idea, does that work for you?

**Comment by marforon** [comment]
> > But we should indeed add a condition to skip this find() when the attribute is already an object
> 
> I updated #48489 to follow this idea, does that work for you?

Thank you! I tested it and it works for me.
