### ISSUE TITLE
[6.2] [DI] Node Value ignored in XMLFileLoader

### ISSUE THREAD

**Issue by BrandonlinU** [symfony/symfony#48445]
### Symfony version(s) affected

6.2.0

### Description

After update to Symfony 6.2, the new changes to support the array tag attributes introduced in #47364 throw an exception when it load a service tag with the name in the inner content of the tag.

### How to reproduce

1. Create a new project with `symfony/dependency-injection` and `symfony/config` dependencies.
2. Create a `index.php` file with the following content:
```php
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;

$containerBuilder = new ContainerBuilder();
$loader = new XmlFileLoader($containerBuilder, new FileLocator(__DIR__));
$loader->load('services.xml');
```
3. Generate a `service.xml` with a service description with a tag, as the following.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services">
    <services>
        <service id="dummy_service" class="App\Service\DummyService">
            <tag>dummy_tag</tag>
        </service>
    </services>
</container>
```
4. Try to run the `index.php` script.

### Possible Solution

It looks like that in the XmlFileLoader tries to extract the tagName incorrectly, because the `$tag->hasChildNodes()` return a boolean, and not an string, and when tries to extract the `nodeValue`, it extracts the attribute name instead, causing the error. 
https://github.com/symfony/symfony/blob/3444c1e0da8f1641624a92a77882b6a7f280a722/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php#L339-L341

I think that with the following code, that tries to extract the nodeValue and if it is not possible tries to get the attribute name from the XML tag, should solve the error.
```php
if ('' === $tagName = $tag->nodeValue ?: $tag->getAttribute('name')) {
    throw new InvalidArgumentException(sprintf('The tag name for service "%s" in "%s" must be a non-empty string.', (string) $service->getAttribute('id'), $file));
}
```

### Additional Context

The exception throw is the following:
```
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException : The tag name for service "instacar.extra_filters.security_expression_value_provider" in "/home/bantonio/PhpstormProjects/FilterBundle/src/DependencyInjection/../Resources/config/security.xml" must be a non-empty string.
```

**Comment by stof** [comment]
I guess that code misses parenthesis around the `||` in the condition of the ternary to have the right precedence.
And it probably also misses a test covering that case...

**Comment by nicolas-grekas** [comment]
Can you please implement what @stof suggests @BrandonlinU and submit it as a PR on 6.2?

**Comment by BrandonlinU** [comment]
Sure, give me a moment to make the pull request...

**Comment by BrandonlinU** [comment]
Well... I have bad news: After update the code with the following code
```php
if ('' === $tagName = ($tag->hasChildNodes() || '' === $tag->nodeValue) ? $tag->getAttribute('name') : $tag->nodeValue) {
    throw new InvalidArgumentException(sprintf('The tag name for service "%s" in "%s" must be a non-empty string.', (string) $service->getAttribute('id'), $file));
}
```
still does not pass the tests, because `hasChildNodes()` return "true" if it is a text node or an attribute tag, returning the "name" attribute. I think that you tried to check if the childen are elements, and not text nodes, but I am not sure.
