### ISSUE TITLE
Why `fake-sms-notifier` factory requires MailerInterface when this feature is not required?

### ISSUE THREAD

**Issue by roquie** [symfony/symfony#48441]
### Description

https://github.com/symfony/fake-sms-notifier/blob/6.2/FakeSmsTransportFactory.php#L30

If I want to use only `fakesms+logger` dsn why I should install mailer or implement fake class for it?

My suggestions: 
1. BC: replace `MailerInterface` with `LoggerInterface` and make `$mailer` `null` by default and `?` sign
2. Non-BC: Add a `?` sign before `MailerInterface`

**Comment by n0rbyt3** [comment]
It's because the whole package offers two options: get notified by email or by using a logger. You may also ask: "Why is there a logger dependency? I only want to use ```fakesms+email```."

So the ```MailerInterface``` is required by design.

**Comment by roquie** [comment]
Yeah. We can do both arguments as nullable and then use \assert() with a or b check.

**Comment by chalasr** [comment]
PR welcome to make both optional.
