### ISSUE TITLE
[Notifier] RocketChat notifier bridge did not get a 6.2 version

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#48456]
### Symfony version(s) affected

6.2.0

### Description

Upgrading to `^6.2` of the bridge causes error:

```
Problem 1
    - Root composer.json requires symfony/rocket-chat-notifier 6.2.*, found symfony/rocket-chat-notifier[v6.2.0-BETA1, v6.2.0-RC1, 6.2.x-dev] but it does not match your minimum-stability.
 ```

As far as I can see, all other bridges have a `6.2` version.

### How to reproduce

`composer require symfony/rocket-chat-notifier:6.2.*`

**Comment by MatTheCat** [comment]
Thanks for the ping :+1: FYI you can trigger an update on packagist.org if you are logged in (I did it myself this time).

See the “Update Now” control at the bottom:

![](https://user-images.githubusercontent.com/1898254/205452868-1bb03cd4-d2ca-4aaa-a6bd-e9c92989df8d.png)
