### ISSUE TITLE
[Routing] Attribute do not work for __invoke

### ISSUE THREAD

**Issue by ThemePoint** [symfony/symfony#48470]
### Symfony version(s) affected

6.2.0

### Description

Before updating to Symfony 6.2.0 controller looks like this (was latest 6.1.x Version before):

```php
final class MyController extends AbstractController
{
    #[Route('/', name: 'default', methods: ['GET'])]
    public function __invoke(): HttpFoundation\Response
    {
        // ....
    }
}
```

When upgrading to 6.2 this is not working anymore because framework throws an attribute error:
`Attribute \"Symfony\\Component\\Routing\\Annotation\\Route\" cannot target function (allowed targets: class, method)`

When switching the `__invoke` method to another name (as exmaple `index`) it works again.

Error is thrown in `/vendor/symfony/http-kernel/Event/ControllerEvent.php:101`.

### How to reproduce

Create a controller which looks like this

```php
final class MyController extends AbstractController
{
    #[Route('/', name: 'default', methods: ['GET'])]
    public function __invoke(): HttpFoundation\Response
    {
        // ....
    }
}
```

in version `6.2.0` and try to call it.

**Comment by xabbuh** [comment]
same as #48438 I guess

**Comment by nicolas-grekas** [comment]
Closing as duplicate. Tl;DR, upgrade your version of PHP

**Comment by ThemePoint** [comment]
@xabbuh @nicolas-grekas Sorry, have not seen that issue before. Thank you for mentioning!
