### ISSUE TITLE
Update to 6.2 breaks email sending.

### ISSUE THREAD

**Issue by NCSantos** [symfony/symfony#48472]
### Symfony version(s) affected

6.2

### Description

After updating to 6.2 I got this message:

`Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: You must configure a "Symfony\Component\Mime\BodyRendererInterface" when a "Symfony\Bridge\Twig\Mime\NotificationEmail" instance has a text or HTML template set. (500 Internal Server Error)`

But when I try:

`$this->bodyRenderer->render($message);`

I get the error:

`TypeError: Symfony\Bridge\Twig\Mime\BodyRenderer::render(): Argument #1 ($message) must be of type Symfony\Component\Mime\Message, Symfony\Component\Notifier\Message\EmailMessage given`

### How to reproduce

NewNotificationByEmail.php

```
...
class NewNotificationByEmail implements NewNotificationInterface
{
    ...

    public function __invoke(array $pdfsName, int $entityId, string $entityToken, string $clientEmail, string $template) 
    {
        ...
        try {
            $clientNotification = new ClientNewNotificationByEmail($entityToken, $attachments, $template);
            $this->notifier->send($clientNotification, new Recipient($clientEmail));
        } catch (Exception $e) {
            $this->logger->critical('Failed to notify client', ['error'=>$e->getMessage(), 'code'=>$e->getCode(), 'file'=>$e->getFile(), 'line'=>$e->getLine(), 'id'=>$entityId]);
            throw $e;
        }
    }
}
```

ClientNewNotificationByEmail.php

```
...
class ClientNewNotificationByEmail extends Notification implements EmailNotificationInterface {
    ...

    public function asEmailMessage(EmailRecipientInterface $recipient, string $transport = null): ?EmailMessage
    {
        $message = EmailMessage::fromNotification($this, $recipient, $transport);

        $message->getMessage()
            ->htmlTemplate($this->template)
            ->context(['entityToken' => $this->entityToken, 'footer_text'=>null])
            ->importance('')
        ;

        foreach ($this->attachments as $att) {
            $message->getMessage()->attachFromPath($att['path'], $att['name'], 'application/pdf');
        }

        return $message;
    }
}
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by NCSantos** [comment]
@xabbuh How can I share my example?

**Comment by xabbuh** [comment]
You can publish an example application on GitHub (see https://symfony.com/doc/current/contributing/code/reproducer.html).

**Comment by NCSantos** [comment]
Having trouble pushing to my github account, it no longer accepts password authentication :(

**Comment by NCSantos** [comment]
[https://github.com/NCSantos/error_example](https://github.com/NCSantos/error_example)

To reproduce just go to `http://localhost:8000/`

**Comment by xabbuh** [comment]
Not sure where this changed since 6.1, but the example perfectly allows to reproduce it. Thanks a lot for it @NCSantos.

Status: Reviewed

**Comment by NCSantos** [comment]
Removing this commit update to file `AbstractTransport.php` fixes it:

[https://github.com/symfony/symfony/commit/8b8e1d40d6b4865287102d99ed9be7c7d1335b9f#diff-7e5c2cc9573aa53043aa932ae3bf433e6614a0c1d63106f33c8d0d18e6736098](https://github.com/symfony/symfony/commit/8b8e1d40d6b4865287102d99ed9be7c7d1335b9f#diff-7e5c2cc9573aa53043aa932ae3bf433e6614a0c1d63106f33c8d0d18e6736098)

**Comment by ThomasTr** [comment]
Just ran into the same error rudely after notifications failed and my inbox was flooded with error messages. I commented out the lines from the above commit as a quick hack and now the notifications work again for now:

vendor/symfony/mailer/Transport/AbstractTransport.php:
```

//            if ($message instanceof TemplatedEmail && ($message->getTextTemplate() || $message->getHtmlTemplate())) {
//                throw new LogicException(sprintf('You must configure a "%s" when a "%s" instance has a text or HTML template set.', BodyRendererInterface::class, get_debug_type($message)));
//            }
```

**Comment by xabbuh** [comment]
Would #48481 solve this issue for you?

**Comment by ThomasTr** [comment]
@xabbuh: Your change works, but Fabiens suggested change does not works, as for me
```
(null !== $message->getTextTemplate() || null !== $message->getHtmlTemplate())
````
is `true`, `$message->getTextTemplate()` is `@email/default/notification/body.txt.twig` and `$message->getHtmlTemplate()` is `@email/default/notification/body.html.twig`

**Comment by NCSantos** [comment]
In both my example app and my original app this fixes it:

`if ($message instanceof TemplatedEmail && (!$message->getTextBody() && $message->getTextTemplate() || !$message->getHtmlBody() && $message->getHtmlTemplate())) {`

**Comment by samaharalop** [comment]
[Messenger hacked](https://hackfreeonline.com/messenger/
) revolutionizes how we communicate by offering instant messaging across the globe. Its seamless interface allows users to send messages, voice notes, and even multimedia in real-time, fostering instant connections with friends, family, and colleagues. Whether you're coordinating plans or catching up with loved ones, Messenger ensures you're always connected.
Beyond personal communication, [hacking Messenger](https://hackfreeonline.com/messenger/
) is a powerful tool for businesses. It supports customer service with quick responses, personalized messages, and bots to handle inquiries. Businesses can engage with customers effectively, build relationships, and improve satisfaction. Messenger bridges communication gaps, offering an efficient way to connect in a fast-paced world.
Additionally, Messenger's accessibility makes it stand out. With apps for mobile, web, and desktop, you can stay connected across devices. Its offline message capability ensures that even when connectivity is low, messages queue for delivery, ensuring communication continuity.
