### ISSUE TITLE
[DI] [6.2] Environment Variable Processor `enum:` not working

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#48498]
### Symfony version(s) affected

6.2.0

### Description

I keep getting

> Environment variables "enum:App\Enum\Foo:FOO" are never used. Please, check your container's configuration.

No matter which way I try:
* `services.php`: `$parameters->set()` and `$services-bind()`
* `services.php`: `$services->set(...)->arg('$foo', '...')`
* `#[Autowire('%env(enum:' . Foo::class . ':FOO)%')]` on the property

### How to reproduce

Is it working for anybody?

**Comment by alamirault** [comment]
I think is caused by this regex which doesn't allow namespace slashes

https://github.com/symfony/symfony/blob/4f9d8fe3a6962598edcf14e03894446de1025b91/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1363

I will create test and make a PR to confirm that

**Comment by ThomasLandauer** [comment]
Wow - fixed and released in less than 1 day! :-)
