### ISSUE TITLE
[2.2] [Routing] Re-generating the current URL

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#4849]
(Derived from #2951)

Generating the current URL is sometimes useful, one common example is to create links to the same page with a different locale, but there are other use cases like multi-parameterized routes where you want to change one while keeping the rest intact.

I would like to propose the following alternatives (in twig helpers, but the same should be added to the UrlGenerator obviously):

- `{{ path(null, {foo:"bar"}) }}`: `null` would generate the current route, and automatically merge the second arg with the current requests's `_route_params`.
- `{{ self({foo: "bar"}) }}`: a new helper for this behavior instead of hackish `null` behavior.

**Comment by marcojanssen** [comment]
@Tobion @Seldaek This issue is almost 3 years old, is this still relevant?

**Comment by Seldaek** [comment]
I guess not.. At least I haven't had such need that I can remember because
it's easy enough to get the current url from Request.

**Comment by marcojanssen** [comment]
@Tobion @Seldaek So we can close it right?
