### ISSUE TITLE
Composer require webapp fails, package conflicts with framework-bundle package. 

### ISSUE THREAD

**Issue by allartdo** [symfony/symfony#48508]
### Symfony version(s) affected

5.4

### Description

I tried installing a new symfony 5.4 project following this: https://symfony.com/doc/5.4/setup.html. I started with `composer create-project symfony/skeleton:"^5.4" my_project_directory`, which works fine. After that I try `composer require webapp` (in correct directory ofc) but this fails. My console says the following:

> Info from https://repo.packagist.org: #StandWithUkraine
> Using version ^1.2 for symfony/webapp-pack
> ./composer.json has been updated
> Running composer update symfony/webapp-pack
> Loading composer repositories with package information
> Restricting packages listed in "symfony/symfony" to "5.4.*"
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - symfony/framework-bundle is locked to version v5.4.16 and an update of this package was not requested.
>     - symfony/webapp-pack v1.2.0 conflicts with symfony/framework-bundle <6.2.
>     - Root composer.json requires symfony/webapp-pack ^1.2 -> satisfiable by symfony/webapp-pack[v1.2.0].
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require symfony/webapp-pack:*" to figure out if any version is installable, or "composer require symfony/webapp-pack:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

It asks me to run a explicit version, but I do not see which version it would like to have. This is my composer.json:

```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "5.4.*",
        "symfony/dotenv": "5.4.*",
        "symfony/flex": "^1.17|^2",
        "symfony/framework-bundle": "5.4.*",
        "symfony/runtime": "5.4.*",
        "symfony/yaml": "5.4.*"
    },
    "require-dev": {
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.4.*"
        }
    }
}
```

I am using composer v2.2.6, yarn v1.22.19, php v7.4.9 and nodejs v14.16.0 (in case it matters).

### How to reproduce

Create a new Symfony 5.4 project: `composer create-project symfony/skeleton:"^5.4" my_project_directory`.
Do: `cd my_project_directory`.
Then: `composer require webapp`.
It should now show the problem.

**Comment by stof** [comment]
You need to require an older version of the webapp pack for Symfony 5.4. The constraint guessing of `composer require` (when passing only the package name and not the constraint) uses the latest version of the package compatible with your **platform** packages, but it does not check compat with all other installed packages as part of the guessing (as that would require running the solver for each candidate, which is far too slow)

**Comment by allartdo** [comment]
Tnx @stof! I tried to go down 1 version, v1.1.1. This seems to have worked. No errors or anything.
In ran this `composer require webapp:1.1.1` instead of this `composer require webapp`.

**Comment by nicolas-grekas** [comment]
That's a bit unfortunate, many will experience this bad DX when starting with the skeleton.
This is the same as https://github.com/symfony/orm-pack/issues/37, which is worked around by removing the conflict: https://github.com/symfony/orm-pack/pull/39

https://github.com/composer/composer/pull/11160 will fix the issue on composer's side, but we need to wait for v2.5

Maybe we should revert the change on the pack for now?

**Comment by nicolas-grekas** [comment]
I removed the tag and reverted the conflict in https://github.com/symfony/webapp-pack/commit/124fb85d004a1ab32de7af86f0d73b9e8fd1136f

This means extra-bundle is still going to be installed with 6.2, but I don't see a better way for now.

**Comment by kissifrot** [comment]
@nicolas-grekas Could you also tag this change please? As currently problem arises with 6.1 too :sweat_smile:

**Comment by nicolas-grekas** [comment]
@kissifrot fixed
