### ISSUE TITLE
[Serializer] Normalizing Object containing BackedEnum fails when using Attributes Groups

### ISSUE THREAD

**Issue by floriankapaun** [symfony/symfony#48517]
### Symfony version(s) affected

6.2.0

### Description

Normalizing objects containing enums works fine.

But if I'm adding [groups](https://symfony.com/doc/current/components/serializer.html#attributes-groups) to normalize only a subset of properties, the enums are returned as empty arrays (`[]`) instead their normal representations (`["name" => "...", "value" => "..."]`).

### How to reproduce

I set up a Serializer like explained in the [Symfony docs](https://symfony.com/doc/current/components/serializer.html#serializing-an-object):

```php
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$normalizer = new ObjectNormalizer($classMetadataFactory);
$serializer = new Serializer([$normalizer]);
```

In the next step I'm using that Serializer to successfully normalize an object that contains a PHP 8.1 ENUM like this:
```php
class MyObj
{
    public Color $color;
}

enum Color: string
{
    case RED = 'red';
    case GREEN = 'green';
    case BLUE = 'blue';
}


$obj = new MyObj();
$obj->color = Color::RED;

$serializer->normalize($obj, null, [])
```

This works.

But if I add Groups to the code, the enum normalization breaks:

```php
class MyObj
{
    #[Groups(['test'])]
    public Color $color;
}

// ...

$serializer->normalize($obj, null, [
    AbstractNormalizer::GROUPS => ['test']
])
```

See [this Repository](https://github.com/floriankapaun/symfony-serializer-normalization-group-enum-bug-reproduction) for a detailed reproduction.

### Possible Solution

A workaround is to filter the normalized properties using attributes instead of groups like that:

```php
$serializer->normalize($obj, null, [
    AbstractNormalizer::ATTRIBUTES => ['title', 'color']
])
```

**Comment by alamirault** [comment]
Thank you @floriankapaun  for your reproduction repository.

> the enums are returned as empty arrays ([]) instead their normal representations (["name" => "...", "value" => "..."]).

I think normal representation it's just value.

You need to add `BackedEnumNormalizer` before ObjectNormalizer
```
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$normalizer = new ObjectNormalizer($classMetadataFactory);
$serializer = new Serializer([new BackedEnumNormalizer(), $normalizer]);
```

Now output should be


```php
[
  'color' => 'red'
]
```

**Comment by floriankapaun** [comment]
Thanks @alamirault for providing a way better solution than my workaround!

That being said, I still believe the current behaviour of not normalizing enums when using groups is at least unexpected if not a bug. Please correct me if I'm wrong.

**Comment by stof** [comment]
@floriankapaun if you don't add the BackedEnumNormalizer, the enums will be serialized by the ObjectNormalizer as objects with properties. And when you filter properties with groups, the properties of the `BackedEnum` won't be part of that filter unless you add some mapping to make them part of the group. That's actually totally expected (once you remember that PHP enums are actually objects).

**Comment by floriankapaun** [comment]
Okay, I see, sounds reasonable @stof. 👍
