### ISSUE TITLE
[FrameworkBundle] `debug:container --tag x` doesn't show priority defined with `AsTaggedItem`

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#48532]
### Symfony version(s) affected

5.4+

### Description

If a service uses `AsTaggedItem` to set the priority, this priority isn't displayed when running `debug:container --tag x`.

### How to reproduce

https://github.com/symfony/symfony/pull/47406#issuecomment-1339927187

**Comment by nicolas-grekas** [comment]
Same as in https://github.com/symfony/symfony/pull/47406#pullrequestreview-1217064167:

`AsTaggedItem` is supposed to work together with `TaggedIteratorArgument`. That's what the word "Tagged" means in the name of the attribute. When not requesting for "tagged" items, the returned array should be a regular list.

 `#[AutoconfigureTag('some_tag', ['priority' => 10])]` is what you might want to add to set the priority for this tag.

If we were to implement something like you expected, I'd suggest doing it via a tag, eg
`['default_attributes', ['priority' => 10]]`, and we could of course add a dedicated attribute to make it easier to define this tag.

Or maybe `['default_attributes', ['some_tag' => ['priority' => 10]]]` for more specificity?

Or something else? I'm just thinking loud here :)

**Comment by kbond** [comment]
> #[AutoconfigureTag('some_tag', ['priority' => 10])]

This works just fine for me.

I'm still not quite understanding when/why I would use `AsTaggedItem` over this though. Most of these attributes aren't documented so that could probably be the place to explain.
