### ISSUE TITLE
[Validator] Since symfony/validator 6.2: The "loose" mode is deprecated. The default mode will be changed to "html5" in 7.0.

### ISSUE THREAD

**Issue by oojacoboo** [symfony/symfony#48541]
### Symfony version(s) affected

6.2.0

### Description

Getting the following error:

>Since symfony/validator 6.2: The "loose" mode is deprecated. The default mode will be changed to "html5" in 7.0.

I'm unable to locate anywhere `VALIDATION_MODE_LOOSE` is being used in our code.  Looking at the stack-traces, I keep running into the following:

```
/srv/www/vendor/symfony/deprecation-contracts/function.php:25
/srv/www/vendor/symfony/validator/Constraints/EmailValidator.php:46
/srv/www/vendor/symfony/validator/ConstraintValidatorFactory.php:40
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:735
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:588
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:502
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:299
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:647
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:502
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:299
/srv/www/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:133
/srv/www/vendor/symfony/validator/Validator/RecursiveValidator.php:82
```

It's also erroring out on files that aren't even calling the Email constraint.  It seems like a faulty check, or there is missing documentation on BC breaks with regards to this.

### How to reproduce

So, the Validator is initialized like so:

```php
$builder = Validation::createValidatorBuilder();
$validator = $builder->enableAnnotationMapping(true)->getValidator();
```

Other than this, I'm getting errors on files that don't even use the Email assertion.

### Possible Solution

Downgrade to symfony/validator 6.1.7

**Comment by mmarton** [comment]
It's an email validator
https://github.com/symfony/symfony/blob/6.3/UPGRADE-6.2.md#validator
`#[Assert\Email]` => `#[Assert\Email(mode: 'html5')]`

**Comment by oojacoboo** [comment]
@mmarton yes.  But that's the thing, nowhere can I find the `mode` or `"loose"` being defined on any `Email` constraint.  Looking at the `Constraints\Email` class, if it wasn't explicitly set in the constructor, it should be evaluating as `null`, and not throwing this error.

**Comment by mbabker** [comment]
https://github.com/symfony/symfony/blob/v6.2.1/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L39-L50

The validator class' constructor defaults to the deprecated loose mode, and changing the default value here would be a big behavior change so that can't be changed until 7.0 either.

**Comment by oojacoboo** [comment]
@mbabker thanks.  So, if someone isn't using the `EmailValidator` directly and not instantiating that object.  What is the recommended way of changing the default?  Is there a global config to pass in this mode value through the primary validator?

**Comment by mbabker** [comment]
In the context of a Symfony app, the `framework.validation.email_validation_mode` config key would do the trick.  In standalone use of the validator component, I wouldn't have a clue.

**Comment by oojacoboo** [comment]
Yea, we don't use the Symfony framework.

**Comment by fancyweb** [comment]
If you don't use the full framework and if you don't instantiate `EmailValidator` yourself directly, you have to find what instantiates it and change the `$defaultMode` constructor argument value.

I can't reproduce your issue by just requiring `symfony/validator` and copy-pasting the two lines of code you provided. So there must be some of your code or other vendor code doing it. Could you maybe try to reproduce the problem in a small project?

**Comment by oojacoboo** [comment]
Am I right in assuming that, if you're using the `ValidatorBuilder`, via `Symfony\Component\ValidatorValidation::createValidatorBuilder()`, the following code is called, instantiating all necessary validators without any arguments, thereby defaulting to "loose" mode?

https://github.com/symfony/validator/blob/6.2/ConstraintValidatorFactory.php#L40

It seems this error is unavoidable when using the builder.

**Comment by ro0NL** [comment]
this is intentional: https://github.com/symfony/symfony/pull/43505#discussion_r737484531

however it should be possible to opt-in to a new mode, maybe ValidatorBuilder needs a patch

the default will be flipped in 7.0 IIUC

**Comment by oojacoboo** [comment]
I understand the desire to add the deprecation error prior to a BC break.  But, it seems in haste, or maybe overlooked, to default to a deprecation error that cannot be resolved.  Looking over the `ValidatorBuilder`, there are multiple abstraction layers before the instantiation of the `EmailValidator`.  Maybe there is a way to pass this `mode` through to it somehow.  But, I'm not familiar enough with the internals to submit a PR.  It looks like maybe the contextFactory or metadataFactory could be suitable proxies...

@ThomasLandauer @nicolas-grekas How do we go about opting in to html5|strict in v6 with the `ValidationBuilder`?

**Comment by nicolas-grekas** [comment]
I propose #48644 to fix this issue.
