### ISSUE TITLE
[VarDumper] Expand // Collapse is broken

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#48545]
### Symfony version(s) affected

6.2.1

### Description

With a very fresh Symfony 6.2 the HTML dump does not work well.
When I click on ` ▶` it does not expand / collapse anymore, and the dump is always expanded.

### How to reproduce

```
symfony new --webapp  symfony-62
cd symfony-62
bin/console make:controller Homepage
symfony serve -d
code src/Controller/HomepageController.php
```

⬇️ 

```php
#[Route('/', name: 'app_homepage')]
    public function index(): Response
    {
        dd([
            'a' => [
                'b' => [
                    'c' => [
                        '' => range(1, 10),
                    ]
                ]
            ]
        ]);
```

![image](https://user-images.githubusercontent.com/408368/206427932-2e029e54-3940-40fd-b0fd-5bc431506f0b.png)

**Comment by ViMZ** [comment]
Hi, i can't reproduce this with your instructions, neither on Firefox nor on Chromium. 
Are you using something else ?

**Comment by andaril** [comment]
I have this issue too. 
My setup is: macos arm ventura 13.0.1 - google chrome 108.0.5359.98

This happens because somehow js that adds css to dumper page not triggers.
Safari is fine btw. I think this is chrome bug, but it's annoying. 

For local env I added 
```
pre.sf-dump .sf-dump-compact, .sf-dump-str-collapse .sf-dump-str-collapse, .sf-dump-str-expand .sf-dump-str-expand { display: none; }
``` 
before this line https://github.com/symfony/var-dumper/blob/6.2/Dumper/HtmlDumper.php#L641

and this code is not invoking or working properly:
https://github.com/symfony/var-dumper/blob/6.2/Dumper/HtmlDumper.php#L160

why - idk

**Comment by OskarStark** [comment]
We are experiencing this issue on Chrome too

**Comment by nicolas-grekas** [comment]
Looks like something changed in Chrome? Could anyone figure out a fix please?

**Comment by javiereguiluz** [comment]
I can't reproduce this with my setup: macOS + latest stable Chrome. Tested in both 6.2.0 and 6.2.1.

Collapse/expand words on all nodes and even the recursive expand-all/collapse-all works when pressing the Command key.

**Comment by andaril** [comment]
maybe arch of the chrome matters?

CHROME VERSION  - 108.0.5359.124
chrome arch - arm64
OS VERSION  -  Mac OS X: 13.0.1
cpu_arc - arm64

still reproducible on my dev env.

**Comment by MatTheCat** [comment]
Wasn’t able to reproduce with Google Chrome or Chromium on Arch Linux (x86_64). Tested from 108.0.5359.71 to 108.0.5359.124.

**Comment by javiereguiluz** [comment]
for those of you who can reproduce ... can you please try to temporarily disable all browser extensions and see if the error persists? Thanks!

**Comment by lyrixx** [comment]
OK, I found the culprit: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

With this extension, it does not work. Without it works

**edit**: I also checked, and VarDumper 5.4.* is also affected. 

---

I don't know if we need to fix that on our side, But I'm going to open a ticket there

**Comment by OskarStark** [comment]
IIRC my colleague @igst does not use this extension, uses Chrome and does not has the problem on 5.4 🤷‍♂️

**Comment by nicolas-grekas** [comment]
Did anyone figure out the issue? Could anyone try to understand what's conflicting?

**Comment by MatTheCat** [comment]
Wasn’t able to reproduce (neither Firefox nor Chrome) even after installing React DevTools.

**Comment by lyrixx** [comment]
I tried, but the extension seems weird :/ There are too many error in the web worker console. So I cannot understand where is the issue :(

**Comment by CreepPork** [comment]
Seems like React and Livewire devtools break the expand / collapse behavior. After disabling the extensions, it works correctly.

**Comment by MatTheCat** [comment]
If https://github.com/facebook/react/issues/25897#issuecomment-1379553104 is right then the problem is from Symfony.

Could someone try it?
