### ISSUE TITLE
[Cache] Redis6Proxy::command($opt, $arg): mixed must be compatible with Redis::command(...$args)

### ISSUE THREAD

**Issue by gdbrown** [symfony/symfony#48558]
### Symfony version(s) affected

6.2.x

### Description

When using symfony cache with redis the Redis6Proxy fails with the following stack trace:

```
Symfony\Component\ErrorHandler\Error\FatalError:
Compile Error: Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::command($opt, $arg): mixed must be compatible with Redis::command(...$args)

  at /app/vendor/symfony/cache/Traits/Redis6Proxy.php:177       
```

### How to reproduce

Load a symfony 6.2.x project on php 8.1.x with redis enabled, e.g.
```
framework:
  cache:
    app: cache.adapter.app_redis
```

The Redis6Proxy should throw the fatal error.

### Possible Solution

Adjust the function signature to match the php redis class which it is proxying.

**Comment by nicolas-grekas** [comment]
Are you use ext-redis unstable? This class is internal and phpredis v6 is stil in active dev.

**Comment by gdbrown** [comment]
stable redis... `pecl install redis`.  default install/config for redis.

**Comment by gdbrown** [comment]
can replicate error with a symfony project by putting this into index.php (to replicate the error)
```
$r = Redis6Proxy::createLazyProxy(fn () => new \Redis);
$r->initializeLazyObject();
```

**Comment by nicolas-grekas** [comment]
I've synced the code with upstream in https://github.com/symfony/symfony/pull/48561, but that won't fix the issue on your side.
You must be doing something wrong while installing ext-redis: v6 is not released yet so you're not supposed to use it (unless you really want to, in which case you know why.)

Check the version you're using. You'll see v6, but you should be using v5 instead.

**Comment by gdbrown** [comment]
hi @nicolas-grekas thank you so much for looking into it.  i did check the version installed...

```
php > echo phpversion('redis');
5.3.7
```

odd issue, i can wait until v6 is official though.  thanks again for reviewing this ticket!  appreciate it.
