### ISSUE TITLE
symfony string default string missing 0 I O

### ISSUE THREAD

**Issue by ELGUEROUEL** [symfony/symfony#48563]
### Description

why default symfony string (ByteString)  does not contain 0 I O  ?
 private const ALPHABET_ALPHANUMERIC = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
we are missing 0 I O in this string 

### Example

this actual const 
 private const ALPHABET_ALPHANUMERIC = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
we are missing 0 I O in this string

**Comment by nicolas-grekas** [comment]
That's on purpose, see https://github.com/symfony/symfony/pull/36991
