### ISSUE TITLE
Container cache exposes SensitiveParameter

### ISSUE THREAD

**Issue by glye** [symfony/symfony#48581]
### Symfony version(s) affected

5.4.x

### Description

(The Symfony security team says this should be reported as a regular bug.)

The [SensitiveParameter feature (new in PHP 8.2)](https://www.php.net/manual/en/class.sensitive-parameter.php) prevents sensitive data like passwords from showing up in stacktraces, when argument output is enabled. However, it has to be set in every part of the call stack, it is not "inherited".

The autogenerated code in the Symfony container cache does not set SensitiveParameter, thus it exposes sensitive data. That means afaik that the container builder does not recognise that SensitiveParameter is set. It should recognise it and make sure it is used in the cache, for the same parameters. Doing this has no bad effect on older PHP versions, as they will simply interpret it as a code comment.

Stack traces are normally only seen on screen in dev mode, but they can end up in log files even in prod mode, which might enable devops etc to snoop on end-user passwords, for example. Those credentials might be used on other sites as well, thus there is a non-zero risk of breaches.

Workaround: Set the php.ini setting `zend.exception_ignore_args` to 1, and no arguments will be shown in stack traces. This is the default in some distros, but not in PHP itself.

I tested this with PHP 8.2 and Symfony 5.4.

### How to reproduce

- In php.ini, set `zend.exception_ignore_args = 0` and `zend.exception_string_param_max_len = 10`.
- Use the [SensitiveParameter feature](https://www.php.net/manual/en/class.sensitive-parameter.php) for a parameter in a method in a service in your Symfony-based code.
- Throw an unhandled exception in this method, so that a stacktrace is generated.
- Run this code with PHP 8.2.

Expected result: The parameter marked as sensitive is shown as Object(SensitiveParameterValue) in every involved part of the stack trace.

Actual result: The parameter is shown in cleartext in the relevant method call in the generated container cache, while it's shown as Object(SensitiveParameterValue) in your own code.

### Possible Solution

The container (cache) builder should detect when SensitiveParameter is used, and apply it in the cache for the same parameters.

**Comment by stof** [comment]
We need a reproducer case to now *which* generated is impacted by that (as the place needing to be updated might not be in Symfony itself)

**Comment by glye** [comment]
I tested it in Ibexa DXP, in a service decorator. This screenshot shows the stacktrace and the cleartext secret in the container cache. Before and after that you see SensitiveParameterValue. Does that help?
![image](https://user-images.githubusercontent.com/289744/206749995-5b1ca108-62f3-444b-8522-30b7b613355e.png)

**Comment by stof** [comment]
Can you share the method definition for the `UserService_886f81a` class to see the generated code ?

side note: copy-pasting the plain-text version of the stack trace into a code snippet is better than posting a screenshot of that plain-text stack trace.

**Comment by nicolas-grekas** [comment]
This proxy is generated by this package: https://github.com/Ocramius/ProxyManager/
In Symfony 6.2, they are generated by https://github.com/symfony/var-exporter which already handles this.
There's nothing more we can do here.
Closing therefor. Thanks for reporting.

**Comment by glye** [comment]
Thanks! I'll consider reporting it with Ocramius. Great that it's fixed in Symfony 6.2, which we'll be using in v5 of our Ibexa DXP.
