### ISSUE TITLE
Symfony does not use validatio group on specific child form

### ISSUE THREAD

**Issue by Guervyl** [symfony/symfony#48598]
### Symfony version(s) affected

6.0.0

### Description

I have a collection of child form in my main form. I want to use validation group on a specific child formType. Setting validation_groups on the resolver in a specific child formType, Symfony ignore the validation group. 

It only validate it when I set the validation group on the main form. But, this is not what I want. Because setting the validation group on the main FormType validate all the children. But I just want to validate some in the collection based on submitted data.

### How to reproduce

Create a FormType and add a collection of child FormType. Set the validation_groups to a sepecif child FormType (*Not on the main form*).

**Comment by Guervyl** [comment]
My solution right now is using form event `$builder->addEventListener(FormEvents::SUBMIT,...` and change the data. But changing the validation group would be better.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
