### ISSUE TITLE
Using Enum objects in expression language

### ISSUE THREAD

**Issue by igst** [symfony/symfony#48593]
### Description

Hi,

would be nice if it would be possible to use native enum objects in expression language context similar to constants. 
See expression option of "When" Constraint in the following example.

cc @mvhirsch 

### Example

    #[When(
        expression: 'this.type.equalsOneOf([
            enum(App\Type::CAR),
            enum(App\Type::BICYCLE),
        ])',
        constraints: [
            new NotBlank(),
            new GreaterThan(value: 0),
        ]
    )]
    public ?int $wheelAmount;

**Comment by alexandre-daubois** [comment]
This is a good idea in my opinion! I would like to give it a try. Unless you'd like to try it! :smile:

**Comment by OskarStark** [comment]
Go ahead @alexandre-daubois 👌🏻 thank you
