### ISSUE TITLE
Lazy firewall not working

### ISSUE THREAD

**Issue by LeamasRein** [symfony/symfony#48600]
### Symfony version(s) affected

6.2.1

### Description

Continuation of this thread:
https://github.com/symfony/symfony/issues/48595#issuecomment-1345405049

> If that is not the case, please [create a minimal reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) as it does sound unexpected to me (but please open a new issue in that case, it's a different bug than the DX improvement that this issue is about).

I don't know if this is a bug or a feature.
From docs: https://symfony.com/doc/current/security.html

> [The Firewall](https://symfony.com/doc/current/security.html#the-firewall) & [Authenticating Users](https://symfony.com/doc/current/security.html#authenticating-users) (firewalls)
The firewall is the core of securing your application. Every request within the firewall is checked if it needs an authenticated user. The firewall also takes care of authenticating this user (e.g. using a login form);

By default config, the firewall affects all routes on the site (except the dev section). I.e all requests go through the firewall.

If specifying lazy true means that firewall authenticators will be loaded ONLY request route within the rules from access_control and for routes marked with isGranted - then lazy does not work correctly.

I created new webapp project, added route without granted attribute. Added base authenticator with exception in supports method. Added the authentication to main firewall (section already have lazy attribute).

When opening the main page, a 500 error occurs from an exception in the supports method.

### How to reproduce

1. Clone repo https://github.com/LeamasRein/symfony-lazy-test
2. Run composer install
3. Run symfony server:start
4. Open main page

**Comment by chalasr** [comment]
It is expected that `supports()` gets called: https://github.com/symfony/symfony/blob/c7f82deb196e41473e331aa1f0e629b21f78c20c/src/Symfony/Component/Security/Http/Authenticator/AuthenticatorInterface.php#L34-L36

Returning null from it enables `authenticate()` to be called lazily, when access control checks happen.

**Comment by LeamasRein** [comment]
Ok, changed - the method now returns null. But the authenticate method is called on any value other than false.
```
    public function supports(Request $request): ?bool
    {
        return null;
    }

    public function authenticate(Request $request): Passport
    {
        throw new Exception("Lazy not working");
    }
```

**Comment by LeamasRein** [comment]
But still strange that the authenticator instance is initialized on lazy.

**Comment by chalasr** [comment]
Well, that's how it works. We need some marker indicating whether laziness is supported or not at the authenticator level, using `supports()` makes it possible to opt-in to laziness conditionally.

**Comment by chalasr** [comment]
I'm going to close here as this is the expected behavior. Feel free to comment if you think otherwise so we can consider to reopen. Thanks

**Comment by LeamasRein** [comment]
> We need some marker indicating whether laziness is supported or not at the authenticator level, using supports() makes it possible to opt-in to laziness conditionally.

Why not use attributes/annotations like in other modules?
And what for then the lazy conf on a firewall is necessary? Allow this behavior by authenticators?

> I'm going to close here as this is the expected behavior. Feel free to comment if you think otherwise so we can consider to reopen. Thanks

Calling the authenticate method when supports returns null, is this the expected behavior?
