### ISSUE TITLE
Memcached session handler issue with clock skew

### ISSUE THREAD

**Issue by tvlooy** [symfony/symfony#48619]
### Symfony version(s) affected

All versions

### Description

In https://github.com/symfony/symfony/commit/0216e056051a6304cab01defc107fb583f3f5efa the TTL values switch from relative time to absolute timestamps. I wonder why this change was made.

"Memcached implements a monotonic clock to ensure it always goes forward generally when time goes forward for the computer."
https://github.com/memcached/memcached/issues/278

But the internal clock can have skew in some environments. I encountered a Debian system running on VMware ESX host that actually has this. So while the OS clock is correct, the internal memcached clock is not (can be checked with the memcached stats command).

If the time drifts too far, memcached will see that entries are expired at the point you are adding them, and not add them to the store. So, your sessions are not created, logins will fail, carts can not be created, ...

As suggested here https://github.com/memcached/memcached/issues/486 it "relative expiration will still work as advertised since the drift is slow".

So while this seems like an edge case and maybe should be checked on the the infrastructure level instead of in this code, it does feel like this would fix it in all situations.

### How to reproduce

Only reproducible on a system that has clock skew on the memcached monotonic timer.

```
$ date
Mon 12 Dec 2022 08:18:37 PM CET

$ echo stats | nc 127.0.0.1 11211 | grep time
STAT time 1670876432

$ date -d @1670876432
Mon 12 Dec 2022 09:20:32 PM CET
```

### Possible Solution

If the time() calls are removed from the MemcachedSessionHandler that would result in relative TTL's and clock skew will no longer be an issue. I'll do a MR if we agree to fix this.

**Comment by derrabus** [comment]
> In 0216e056051a6304cab01defc107fb583f3f5efa the TTL values switch from relative time to absolute timestamps. I wonder why this change was made.

At first, your issue description sounded to me like a recent change broke your application. For the record: That commit you're talking about is ten years old. 😅

**Comment by tvlooy** [comment]
> At first, your issue description sounded to me like a recent change broke your application. For the record: That commit you're talking about is ten years old. sweat_smile

Yes, I am aware of that. :joy: I do think it's a bit an edge case, but I think switching to relative TTL would fix it in all circumstances. I also can't comment on how much the memcached session handler is actually being used, ...

**Comment by derrabus** [comment]
Yeah, I think you have a point. The current code requires the clocks of your webserver and your memcached server to be in sync, which is close to impossible to ensure unless they're the same machine.

**Comment by nicolas-grekas** [comment]
How can this be a problem in real world use case? The drift is slow and the expiration date of sessions is far away in the future (weeks if not months.) Even a few hours of drifts shouldn't make a difference, isn't it?
I can't tell why this went from relative to absolute though. Maybe @vicb knows since he authored #4227? (but 10 years ago... :) )

**Comment by tvlooy** [comment]
In Shopware e-commerce the session TTL is only 1 hour by default for visitors. The clock of memcached keeps going too fast, while the OS clock is being corrected. So after a week or so, memcached is living an hour in the future. If an entry is added that only has 1 hour TTL it's expired when it is being added and memcached will just not add it anymore.
This is actually a real world problem I encounter (luckily not in production). I can find various VMware reports of people that say that the guest clock running too fast under ESX. So this must be a thing other people experience too.

**Comment by nicolas-grekas** [comment]
Could you submit a PR to do relative TTLs?
