### ISSUE TITLE
[Validator] add the getConstraint() to the ConstraintViolationInterface

### ISSUE THREAD

**Issue by syl20b** [symfony/symfony#48626]
### Description

Hi,

is there a reason for the `getConstraint()` method not to be declared in the `ConstraintViolationInterface` ?

If not, could it be possible to add it to the interface ? (I could work on it if you want)

Regards

**Comment by xabbuh** [comment]
IIRC the method was added to the `ConstraintViolation` class after the interface was part of a release. Given that adding a method to an interface is a BC break we would have to add a method to the docblock of the interface first (similar to what we did in #47734) before being able to add the real method in 7.0.

**Comment by xabbuh** [comment]
PR welcome by the way :)
