### ISSUE TITLE
[VarExporter] PHP8.2 Deprecated dynamic properties created in LazyGhostTrait::__set()

### ISSUE THREAD

**Issue by emteknetnz** [symfony/symfony#48637]
### Symfony version(s) affected

6.2.x

### Description

var-exporter [LazyGhostTrait::__set()](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/VarExporter/LazyGhostTrait.php#L256) contains `$this->$name = $value;` when `$scope` is `null` - use of [dynamic properties is deprecated](https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties) in PHP 8.2

This will probably also affect other methods in LazyGhostTrait that use dynamic properties such as `__get()`, `__isset()`, `__unset()`

### How to reproduce

```php
<?php

use Symfony\Component\VarExporter\LazyGhostTrait;

class MyObj
{
    use LazyGhostTrait;
}
```
You can replicate the deprecation warning with the following code in PHP 8.2:

```php
$obj = new MyObj();
$obj->abc = 123;
```

```
[Deprecated] Creation of dynamic property MyObj::$abc is deprecated
GET /

Line 236 in /var/www/vendor/symfony/var-exporter/LazyGhostTrait.php
```

### Possible Solution

Adding `#[\AllowDynamicProperties]` to LazyGhostTrait will NOT work - instead it will trigger the warning 
`[Alert] Cannot apply #[AllowDynamicProperties] to trait`

**Comment by nicolas-grekas** [comment]
The deprecation is legit: you cannot add a dynamic property to MyObj.

**Comment by emteknetnz** [comment]
It is a legit deprecation notice, however the notice is being triggered from `Line 236 in /var/www/vendor/symfony/var-exporter/LazyGhostTrait.php` inside `__set()` - this to me says that some of the logic in `LazyGhostTrait` is no longer viable?

To be fair, I really don't understand how `LazyGhostTrait` works or what it's even used for.

However `LazyGhostTrait` wants to add dynamic properties directly to an object via `$this->$name = $value;` on line 236.  `__set()` is still supported in PHP 8.2 so you could normally do something like

```php
private array $data = [];

public function __set($name, $value)
{
    // ...
    $this->data[$name] = $value;
}
```

I did attempt to create a PR along these lines, however `LazyGhostTrait` is very particular and I got endless unit test failures.

**Comment by nicolas-grekas** [comment]
The trait simulates what native PHP would do. Because you access the dynamic property, __set sets the property, and triggers the notice. This is the expected simulated behavior.

Then why are you trying to use it? What goal do you have?

LazyGhostTrait provides lazy-loading to a class. If you want this class to also have magic setters, the easiest way is to use inheritance, where the class that uses the trait extends the one with the magic methods.
