### ISSUE TITLE
Unable to parse JSON/YAML with tabs

### ISSUE THREAD

**Issue by mxr576** [symfony/symfony#48647]
### Symfony version(s) affected

6.2.0

### Description

Is it an expected behavior or not? Is it a bad idea using the YAML component to parse a JSON?

Maybe this is an expected behavior for YAML: http://yaml.org/faq.html >>> Why does YAML forbid tabs?

Does it mean that it also make impossible to parse JSON with tabs?

### How to reproduce

Try to parse the following examples like

```
$parser = \Symfony\Component\Yaml\Yaml::parse($json);
var_export($parser);
```

```
{
	"openapi": "3.0.0",
	"info": {
		"title": "Quality Assurance",
		"version": "0.1",
		"description": "<p>The Quality Assurance<em> should ensure that a previously working OAS file still works the same way after a product upgrade. As the very minimum, such a message should be displayed for the end-user that helps fixing the issue in the OAS file."
	},
	"servers": [
		{
			"url": "https://example.com/v1"
		}
	],
	"paths": {
		"/QualityAssurance": {
			"get": {
				"summary": "Get entities",
				"responses": {
					"200": {
						"description": "Retrieved comma-separated list of entities",
						"content": {
							"application/json": {
								"schema": {
									"title": "List",
									"type": "string"
								}
							}
						}
					}
				}
			}
		}
	}
}
```

or 

```
openapi: 3.0.0
info:
	title: Quality Assurance
	version: '0.1'
	description: >-
		<p>The Quality Assurance<em> should ensure that a previously working OAS
		file still works the same way after a product upgrade. As the very minimum,
		such a message should be displayed for the end-user that helps fixing the
		issue in the OAS file.
servers:
	- url: https://example.com/v1
paths:
	/QualityAssurance:
		get:
			summary: Get entities
			responses:
				'200':
					description: Retrieved comma-separated list of entities
					content:
						application/json:
							schema:
								title: List
								type: string
```

**Comment by mxr576** [comment]
>There is one important thing you need to remember when using indentation in a YAML file: Indentation must be done with one or more spaces, but never with tabulators.

https://symfony.com/doc/current/components/yaml/yaml_format.html

Maybe I have answered the YAML related question

**Comment by derrabus** [comment]
> Is it an expected behavior or not?

Yes.

> Is it a bad idea using the YAML component to parse a JSON?

Yes. 🙂

**Comment by mxr576** [comment]
> >    Is it a bad idea using the YAML component to parse a JSON?

> Yes. slightly_smiling_face

Can you elaborate a bit more on this? I mean other than the issue discussed here, Symfony YAML component can parse JSON fine... which is not surprising since:

> The YAML 1.2[3](https://yaml.org/spec/1.2.2/#fn:1-2-spec) specification was published in 2009. Its primary focus was making YAML a strict superset of JSON. It also removed many of the problematic implicit typing recommendations.

https://yaml.org/spec/1.2.2/

So I guess I am not the only one who have tried to use that to parse JSON as well, not just because an AsyncAPI/OpenAPI can be both JSON or YAML.

**Comment by derrabus** [comment]
> Can you elaborate a bit more on this? I mean other than the issue discussed here, Symfony YAML component can parse JSON fine...

Just because you can doesn't mean you should. PHP has `json_decode()` which is an awesome and complete JSON parser. Symfony does not aspire to duplicate that work. If you're holding JSON in your hand and you know that you're holding JSON in your hand, then yes, it's a bad idea not to use a JSON parser for that.

The YAML component on the other hand is an implementation of the YAML standard all right. But given the complexity of that standard, it's far from being complete and I don't think we'll ever cover the whole spec. That being said, we're always open for PRs that cover previously uncovered parts of the spec. Regarding tabs in JSON however, I personally doubt that it's worth it.
