### ISSUE TITLE
Unable to create custom normalizer after deprecation of ObjectNormalizer

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#48645]
### Symfony version(s) affected

6.2

### Description

Using this example: https://symfony.com/doc/current/serializer/custom_normalizer.html leads to deprecation message: "ObjectNormalizer" service alias is deprecated. Replacing them with NormalizerInterface causes circular reference exception.

### How to reproduce

Implement custom normalizer as shown in doc here: https://symfony.com/doc/current/serializer/custom_normalizer.html

### Possible Solution

Fix doc or revert deprecation of ObjectNormalizer.

**Comment by chalasr** [comment]
See https://github.com/symfony/symfony-docs/pull/16826 and https://github.com/symfony/maker-bundle/issues/1252.

**Comment by ThomasTr** [comment]
Sorry, missed that out.
