### ISSUE TITLE
[Mailer] Expected response code "250" but got code "550", with message "550 MIME message is missing 'From' header since 5.4.15

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#48643]
### Symfony version(s) affected

5.4.15

### Description

When bumping Symfony mailer from `5.4.13` to `5.4.15` (and `5.4.16` doesn't solve the issue), I get the error
```
Expected response code "250" but got code "550", with message "550 MIME message is missing 'From' header".
```
when trying to send a mail with Sengrid integration.

I can confirm it's related to symfony/mailer since I fixed absolutely every other dependencies when swapping between 5.4.13 and 5.4.15.

### How to reproduce

We have code like this
```
       $message = (new Email())
            ->to($recipient)
            ->from(new Address($senderEmail, $senderName))
            ->subject($subject);

        $envelope = new Envelope(new Address($senderEmail), [new Address($recipient)]);

        $body = $this->templatingService->render($mailTemplate, $data);
        $message->html($body);

        $this->mailer->send($message, $envelope);
```
which was working fine with older version.

The mailer was defined this way
```
$apiKey = $parameterBag->get('mailer_password');
$transport = new SendgridSmtpTransport($apiKey, $eventDispatcher);
$this->mailer = new Mailer($transport);
```

**Comment by VincentLanglet** [comment]
Reverting https://github.com/symfony/symfony/pull/47822 solve my issue cc @rogamoore

**Comment by RobertIacoveciuc** [comment]
Issue still present.
`
{"message":"Send Mail Fail. \\r\\nError Code: 550 \\r\\nMessage: Expected response code \"250\" but got code \"550\", with message \"550 \"envelope sender not allowed someemail@yahoo.com\"\".","context":{},"level":600,"level_name":"EMERGENCY","channel":"app","datetime":"2023-01-31T15:07:34.046563+01:00","extra":{}}
`
