### ISSUE TITLE
[Validator] Compound Constraints didn´t allow groups or payload

### ISSUE THREAD

**Issue by benjaminfunk** [symfony/symfony#48659]
### Symfony version(s) affected

6.2

### Description

The abstract class Symfony\Component\Validator\Constraints\Compound has the wrong constructor and did not accept group or payload parameter

https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/Compound.php

According to the instructions this should be possible

https://symfony.com/doc/current/reference/constraints/Compound.html

### How to reproduce

Copy the example of the documentation and set a group or payload parameter

https://symfony.com/doc/current/reference/constraints/Compound.html

```php
// src/Validator/Constraints/PasswordRequirements.php
namespace App\Validator\Constraints;

use Symfony\Component\Validator\Constraints\Compound;
use Symfony\Component\Validator\Constraints as Assert;

#[\Attribute]
class PasswordRequirements extends Compound
{
    protected function getConstraints(array $options): array
    {
        return [
            new Assert\NotBlank(),
            new Assert\Type('string'),
            new Assert\Length(['min' => 12]),
            new Assert\NotCompromisedPassword(),
        ];
    }
}
```

```php
// src/Entity/User.php
namespace App\Entity\User;

use App\Validator\Constraints as Assert;

class User
{
    #[Assert\PasswordRequirements(groups: ['group'])]
    public $plainPassword;
}
```

### Possible Solution

Adjust the constructor (and parent call) to allow groups und payload

```php
public function __construct(mixed $options = null, array $groups = null, mixed $payload = null)
{
        // ...

	parent::__construct($options, $groups, $payload);
}
```

**Comment by algorun77** [comment]
Hello,

I'm still having this bug in Symfony 6.4 with the exact same example. Why has this issue been marked as completed?

Using the "Possible solution" code fixed the Exception but the groups still doesn't work.

Thanks,

**Comment by xabbuh** [comment]
Comments on closed issues are likely to get lost. Please open a new issue and provide a small example application that allows to reproduce what you experience.
