### ISSUE TITLE
[Controller] Automatically Fetching Objects with MapEntity not working 6.2

### ISSUE THREAD

**Issue by ytilotti** [symfony/symfony#48662]
### Symfony version(s) affected

6.2

### Description

I'm working on migration 6.1 to 6.2 and I refactor `ParamConverter` to `MapEntity` like [this post](https://symfony.com/blog/new-in-symfony-6-2-built-in-cache-security-template-and-doctrine-attributes) and [this doc](https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-entityvalueresolver).

But `MapEntity` seems not working. Miss something?

### How to reproduce

Run this route:

```php
<?php
namespace App\Controller;

use App\Entity\Test;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;

class TestController extends AbstractController
{
    #[Route('/mapentity1/{tid}/', name: 'mapentity_test1', requirements: ['tid' => '\d+'])]
    public function mapentity_test1(#[MapEntity(id: 'tid')] Test $test): Response
    {
        dd($test);
    }
    
    #[Route('/mapentity2/{tid}/', name: 'mapentity_test2', requirements: ['tid' => '\d+'])]
    public function mapentity_test2(#[MapEntity(mapping: ['id' => 'tid'])] Test $test): Response
    {
        dd($test);
    }
}
```

I have create a small application on [phpsandbox](https://phpsandbox.io/e/x/roxnh?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=) to test that. Need to call [https://ovkrp.ciroue.com/mapentity1/1](https://ovkrp.ciroue.com/mapentity1/1) or [https://ovkrp.ciroue.com/mapentity2/1](https://ovkrp.ciroue.com/mapentity2/1).
The route with a `ParamConverter`  is working: [https://ovkrp.ciroue.com/paramconvertor/1](https://ovkrp.ciroue.com/paramconvertor/1) is working.

You can download with this zip: [ovkrp.zip](https://github.com/symfony/symfony/files/10236892/ovkrp.zip)

### Additional Context

```
LogicException:
Unable to guess how to get a Doctrine instance from the request information for parameter "test".

  at vendor/sensio/framework-extra-bundle/src/Request/ParamConverter/DoctrineParamConverter.php:97
  at Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter->apply(object(Request), object(ParamConverter))
     (vendor/sensio/framework-extra-bundle/src/Request/ParamConverter/ParamConverterManager.php:84)
  at Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterManager->applyConverter(object(Request), object(ParamConverter))
     (vendor/sensio/framework-extra-bundle/src/Request/ParamConverter/ParamConverterManager.php:48)
  at Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterManager->apply(object(Request), array('test' => object(ParamConverter)))
     (vendor/sensio/framework-extra-bundle/src/EventListener/ParamConverterListener.php:72)
  at Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener->onKernelController(object(ControllerEvent), 'kernel.controller', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ControllerEvent), 'kernel.controller', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.controller', object(ControllerEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ControllerEvent), 'kernel.controller')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:127)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ControllerEvent), 'kernel.controller')
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:184)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/vendor/autoload_runtime.php')
     (public/index.php:5)
```

**Comment by HypeMC** [comment]
The problem is that the `DoctrineParamConverter` runs before the new `EntityValueResolver`, so it's trying to resolve the entity instead of the resolver and fails. Try removing the SensioFrameworkExtraBundle, that should fix the problem.

Or you could [disable the param converter](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/index.html#configuration):

```yaml
sensio_framework_extra:
    request: { converters: false }
```

**Comment by ytilotti** [comment]
Ok need to remove completely the composer package `sensio/framework-extra-bundle` or disable like your exemple.
Conclusion, we cannot use both at the same time. There is a conflict. I think this needs to be documented.

And if I'm right, `MapEntity` can't be used on class like `ParamConverter`:
```php
#[Route('/admin/', requirements: ['tid' => '\d+'])]
#[ParamConverter('test', options: ['id' => 'tid'])]
#[IsGranted('ROLE_SUPER_ADMIN', statusCode: 403)]
class AdminTestController extends AbstractController {
}
```

**Comment by HypeMC** [comment]
> And if I'm right, `MapEntity` can't be used on class like `ParamConverter`:

No, the `#[MapEntity]` attribute is meant to be used on a parameter.

**Comment by PhilETaylor** [comment]
> The problem is that the DoctrineParamConverter runs before the new EntityValueResolver, so it's trying to resolve the entity instead of the resolver and fails. Try removing the SensioFrameworkExtraBundle, that should fix the problem.

Time lost today... 2 hours... 

Nothing to alert me in the docs https://symfony.com/doc/current/doctrine.html#mapentity-options or the announcing blogpost :(

**Comment by Chris53897** [comment]
+1 for adding this info to the Docs. Could save many hours of developers, searching for this info in the migration process.

**Comment by javiereguiluz** [comment]
👍 This bite me today too.

@nicolas-grekas to me, the ideal solution would be to update this exception message:

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/2f886f4b31f23c76496901acaedfedb6936ba61f/src/Request/ParamConverter/DoctrineParamConverter.php#L97

We could add the typical Symfony question `Did you ... ?` and ask the users if they are trying to use MapEntity attributes with the FwExtra bundle too. Or add an error message in `MapEntity` attributes if FwExtra bundle is enabled.

I know that the repository is archived and unarchiving it momentarily is a hassle ... but we'd also like to update a bit the docs of that repository to add more and better warnings about the migration to the built-in attributes. So, could we unarchive, do these changes quickly, and archive again? Thanks.

**Comment by Dev-Clair** [comment]
I am also having this problem. If i disable my param converter or remove the sensio-framework bundle entirely. How do i get the param-converter functionality for other methods of my controller needing this functionality?

**Comment by mindaugasvcs** [comment]
If you have this route #[Route(path: '/{id}/items/{item_id}', #[MapEntity(id: 'item_id')] will ALWAYS take the {id} instead of {item_id}, congrats!
