### ISSUE TITLE
https://symfony.com/releases.json is not maintened

### ISSUE THREAD

**Issue by aqueos** [symfony/symfony#48660]
### Symfony version(s) affected

4.4

### Description

hi,

Just wanted to poitn out that the url https://symfony.com/releases.json is publicized as reference for versions maintened but the page is abandonned and do not show 4.4 in security fix for exemple.

### How to reproduce

go to https://symfony.com/releases.json and search 4.4 version, it is on https://symfony.com/releases but not on the json "version"

### Possible Solution

make the json version generated by the same system that generates the https://symfony.com/releases page.

or deprecate the json page so it do not add confusion in the support of symfony.

### Additional Context

Thanks for your work and have a nice day ! :)

**Comment by derrabus** [comment]
The JSON looks accurate to me. 4.4 is missing because it's not maintained anymore. We only apply security fixes to that branch.
