### ISSUE TITLE
TemplatedEmail doesn't load the twig html template

### ISSUE THREAD

**Issue by TomaIvanovTomov** [symfony/symfony#48689]
### Symfony version(s) affected

6.0

### Description

I have this piece of code to send email:

```
$email = (new TemplatedEmail())
            ->from(new Address('sender@example.com', 'Support'))
            ->to('reciever@example.com')
            ->subject('Your password reset request')
            ->htmlTemplate('reset_password/email.html.twig')
            ->context([
                'resetToken' => '12312321',
            ]);
```

When I try to send it `$mailer->send($email);` I getting this error:
`A message must have a text or an HTML part or attachments`

I found how to resolve it via these lines before sending :
```
$loader = new FilesystemLoader($this->kernel->getProjectDir().'/templates');
        $twigEnv = new Environment($loader);
        $twigBodyRenderer = new BodyRenderer($twigEnv);
        $twigBodyRenderer->render($email);
```
But I am 100% sure that this can't be the correct approach. Do I really have to really put all these after every email ? Plus even adding these I am getting another error because of this line from the twig file:
`<a href="{{ url('app_reset_password', {token: resetToken.token}) }}">{{ url('app_reset_password', {token: resetToken.token}) }}</a>`

Obviously even the twig methods doesn't work when I am making TemplatedEmail or am I missing something ? None of the twig methods actually work in such approach. After googling I find out that other people have this problem as well, but obviously not everyone. So I am guessing that I might be missing something. Otherwise it seems like a bug to me. 
Thank you!

### How to reproduce

Install `"symfonycasts/reset-password-bundle": "^1.16"` and simply test with it. Without any other additional things. Just the base installation of the package.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
