### ISSUE TITLE
Enums cannot be tagged with ContainerBuilder::registerAttributeForAutoconfiguration

### ISSUE THREAD

**Issue by michnovka** [symfony/symfony#48699]
### Symfony version(s) affected

6.2.2

### Description

I can tag classes, but not enums.

### How to reproduce

```php
class Kernel extends BaseKernel implements CompilerPassInterface
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        $container->registerAttributeForAutoconfiguration(
            DBALSQLEnum::class,
            static function (ChildDefinition $definition, DBALSQLEnum $attribute, ReflectionClass $reflector): void {
                $definition->addTag('app.dbal_sql_enum_type');
            }
        );
    }
}
```
```php
#[Attribute(Attribute::TARGET_CLASS)]
class DBALSQLEnum
{
}
```
This file DOES get tagged properly:
```php
<?php
namespace App\Enum;

#[DBALSQLEnum]
class BalanceLogType
{}
```
this one does NOT:
```php
<?php
namespace App\Enum;

use App\DBAL\Types\DBALSQLEnum;

#[DBALSQLEnum]
enum BalanceLogType
{}
```

**Comment by derrabus** [comment]
Since enums cannot be services, what's the point?

**Comment by michnovka** [comment]
Since Symfony goes over all the files in the project, it would be great to allow tagging even enums, as the file is likely included and analyzed anyways during the Kernel build process. In my particular case, I want to auto-configure custom enum DBAL types inside `Kernel::process` so fetching the list of tagged enums makes this super convenient.
I can imagine multiple custom bundles can benefit from the fact that wed allow tagging of any class/enum or maybe even interface.
Currently, the only workaround I have is to open file by file inside a predefined filepath and check for enums present. Basically repeating the job that Symfony already does during autoconfiguration.
If there is no performance impact (which I dont think there is as the files get analyzed anyways) I see no reason to not allow this.

**Comment by derrabus** [comment]
But tags are not attached to classes, but to services. It's not the purpose of the DI component to collect an arbitrary list of classes.
