### ISSUE TITLE
[feature request] XMLHttpRequest2 file uploads

### ISSUE THREAD

**Issue by Sorien** [symfony/symfony#4870]
Add support for XHR2 file uploads 

reference: 
http://www.alexanderschnitzler.de/2011/06/howto-build-an-html5-file-uploader-with-ajax/
http://www.w3.org/TR/XMLHttpRequest/

expected result:
`Symfony\Component\HttpFoundation\Request` `FileBag` should contain uploaded file

**Comment by javiereguiluz** [comment]
I'm closing this issue because in 3 years it hasn't registered any activity. If this feature is still desired, a new issue can be created to discuss about including it in Symfony 3. Thank you!
