### ISSUE TITLE
[Web Profiler] Ubuntu Mono font looks blurry

### ISSUE THREAD

**Issue by yuuuusha** [symfony/symfony#48708]
### Symfony version(s) affected

6.2.2

### Description

Hi!

In the profiler, the font used in some tables (Ubuntu Mono) looks blurry.

It is redefined in `web-profiler-bundle/Resources/views/Profiler/fonts.css.twig` and replaces the system font.

If I comment out the font definition in the file, my browser then uses the system font which I downloaded on https://fonts.google.com/specimen/Ubuntu+Mono (TTF file).

### How to reproduce

* Access the web profiler
* Go to the Events tab, for example

### Additional Context

I use Chrome 108.0.5359.125 on Windows 10 (version 10.0.19045). The issue is a bit less noticeable on Firefox 108.0.1.

Both screenshots made with Chrome.

Blurry text from the events panel:

![image](https://user-images.githubusercontent.com/20849196/208539487-e613a7cf-9472-4707-8aed-58d3b6808c17.png)

Same text with the system font:

![image](https://user-images.githubusercontent.com/20849196/208539630-9328c0f3-3a24-4d3a-b458-c4996ffd26f8.png)

**Comment by javiereguiluz** [comment]
@yuuuusha thanks for reporting this. We'd need some more debugging to find the cause of the error:

(1) Open the `vendor/` directory of your project and locate this file: symfony/web-profiler-bundle/Resources/views/Profiler/profiler.css.twig`

(2) Comment or delete this line:

```
{{ include('@WebProfiler/Profiler/fonts.css.twig') }}
```

(3) In the same place of that line, add this instead:

```
@import url('https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap');
```

If it works better, then there's a problem in how we load the web font.

(4) If the error persists, change the previous line by these lines:

```
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap');

:root {
    --font-family-monospace: "JetBrains Mono";
}
```

Reload the page. you should see monospace text with a different font. If the blur problem persists, it might be an issue of your system (for possible solutions, see: https://www.askvg.com/fix-blurry-text-and-font-display-problems-in-google-chrome/)

If the blur problem solves, then the issue might be related to the other font.

Thanks!

**Comment by yuuuusha** [comment]
Hi @javiereguiluz, thanks for your answer. 

I followed your instructions and both Ubuntu Mono and Jetbrains Mono appear blurry (Jetbrains Mono less), even with the link you provided.

I also uninstalled my system fonts so the profiler would default to Consolas if I commented the fonts in the CSS file. Consolas was sharp.

I applied the same grey background and green color to Google's type tester. Results are, for the profiler :
![image](https://user-images.githubusercontent.com/20849196/209567695-f7e8dea9-acec-4d8a-9fbf-01b5ecc74a84.png)

and the type tester :
![image](https://user-images.githubusercontent.com/20849196/209568491-99680ec3-d8bd-4773-bc65-84b6eb0d3192.png)

**Comment by javiereguiluz** [comment]
Thanks for doing these additional tests. So far we know that native fonts look OK and all web fonts look not OK.

In the same Events panel that you showed before, try this. Right-click on any monospace text and look for this selector in the browser debug tools:

```
#collector-content pre.sf-dump,
#collector-content .sf-dump code,
#collector-content .sf-dump samp {
  ...
}
```

That's the place where we set `font-family: var(--font-family-monospace);` Add the following property to it: `-webkit-font-smoothing` and try, sequentially, all these different values to check if you see any difference:

```
-webkit-font-smoothing: auto;
-webkit-font-smoothing: none;
-webkit-font-smoothing: antialiased;
-webkit-font-smoothing: subpixel-antialiased;
-webkit-font-smoothing: grayscale;
```

In theory you shouldn't see any difference because that property only works on macOS ... but sometimes, browser behavior is very weird.

-----

If the above doesn't work, try to add the following property to the same selector as above. One property at a time:

Option 1:

```
-webkit-filter: blur(0);
filter: blur(0);
```

Option 2:

```
-webkit-transform: translateZ(0);
transform: translateZ(0);
```

Option 3:

```
-webkit-transform: translate3d(0,0,0);
transform: translate3d(0,0,0);
```

Thanks

**Comment by yuuuusha** [comment]
Thank you for your detailed guidance!

Base node screenshot, no filter:
![NO FILTER](https://user-images.githubusercontent.com/20849196/209687411-f684d257-8984-4624-a600-88e782f566ba.png)

Applying `-webkit-font-smoothing` had no effect, as you said. All the node screenshots I took had the same hash as the base image.

The 3 other options made the text slightly more blurry. They had the same effect. The difference is more visible on the grey text:
![blur 0](https://user-images.githubusercontent.com/20849196/209687553-7c85b7e1-c8e8-4001-82db-f5a9c2bb4b8a.png)

**Comment by Bersman** [comment]
Firefox: 108.0.1 (64-bit)
Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

![image](https://user-images.githubusercontent.com/1538239/209787568-d6d2b780-b31d-4727-b9d2-58c8c4092a0b.png)

**Comment by millnut** [comment]
Hi @javiereguiluz I think I've found the cause of the Blur on Windows by looking at my git log for the same issue on a non-related project.

Going through the CSS I discovered the rule `pre.sf-dump .sf-dump-str`, which is setting the font-weight as below;

```
pre.sf-dump .sf-dump-str {
font-weight: bold;
color: #56DB3A
}
```

As we are using Ubuntu Mono and it uses a font-weight of 400. So the class rule above needs changing to state the weight to use;

```
pre.sf-dump .sf-dump-str {
font-weight: 400;
color: #56DB3A
}
```

Added before and after screenshots on Windows 10;

Before:
![Screenshot 2022-12-28 at 14 40 20](https://user-images.githubusercontent.com/8024370/209828680-c2ed066e-f191-47f1-ade0-8254b4a02d83.png)

After:
![Screenshot 2022-12-28 at 14 40 38](https://user-images.githubusercontent.com/8024370/209828718-9ba35f56-1560-4c13-be3e-9ad48d7ceaa4.png)

Another possible solution would be including a higher weight version of the Ubuntu Mono font i.e `700` and using that font-weight for bold items.

**Comment by millnut** [comment]
Declaring a bold font for Ubuntu Mono (700) as well as keeping the regular 400 weight font, turns the bold to this;
![Screenshot 2022-12-28 at 14 53 53](https://user-images.githubusercontent.com/8024370/209830516-f53cf23a-1953-4b2e-b02a-4219b7014f3d.png)

This is with a bold version of the font included and font-weight left as bold;
`@import url('https://fonts.googleapis.com/css2?family=Ubuntu+Mono:wght@400;700&display=swap');`

**Comment by javiereguiluz** [comment]
Thanks @millnut and everybody who helped us debugging this issue. We now know the exact cause of the error, so I'm working on a fix for it. Thanks.

**Comment by javiereguiluz** [comment]
After thinking a lot about this, we've decided to change the web font used by the Symfony Profiler and use instead a "variable font" that allows us to use many different font weights. See #48822.
