### ISSUE TITLE
[Cache] RedisTrait::createConnection does not pass auth value from redis sentinel cluster DSN

### ISSUE THREAD

**Issue by evgkord** [symfony/symfony#48712]
### Symfony version(s) affected

5.4

### Description

When redis sentinel cluster with non-empty auth phrase used, we may pass it in DSN as [described](https://symfony.com/doc/5.4/components/cache/adapters/redis_adapter.html). However, param "_auth_" stay ignored and not passes properly while _RedisTrait::createConnection_.

### How to reproduce

1. Ensure the redis php extension is installed
2. Create a redis connection with multiple sentinel hosts and non-empty auth phrase: RedisAdapter::createConnection('redis:?host[sentinel1:26379]&host[sentinel2:26379]&host[sentinel3:26379]&redis_sentinel=mysentinel&auth=myauth')

**Expected Behaviour**
An instance of \Redis should be returned with a connection to the current redis master assigned by redis sentinel

**Current Behaviour**
After \RedisSentinel instance created without auth phrase, calling method ::getMasterAddrByName() is unable to get adress of master in cluster and it causes \Symfony\Component\Cache\Exception\InvalidArgumentException with message '_Failed to retrieve master information from sentinel "mysentinel" and dsn "redis:?host[sentinel1:26379]&host[sentinel2:26379]&host[sentinel3:26379]&redis_sentinel=mysentinel&auth=myauth"._'

### Possible Solution

[phpredis extension](https://github.com/phpredis/phpredis/blob/develop/sentinel.md#readme) supports passing _auth_ as argument of \RedisSentinel::__consruct(), so it probably should be passed if it present in DSN.

also param _auth_ should be passed in such trait while \Redis::connect(), as [described](https://github.com/phpredis/phpredis#connect-open) to avoid RedisException: NOAUTH Authentication required, for example when you later want some $redis->eval(...), 

### Additional Context

[PR 48711](https://github.com/symfony/symfony/pull/48711)

**Comment by zip-fa** [comment]
Ебучий гандон, из-за тебя у нас упал проект на 40 мин

**Comment by chalasr** [comment]
@zip-fa Please stay respectful or we will have to block you. Btw, you might not have anything in production without us and our work. Have a nice day.
