### ISSUE TITLE
HttpCache files getting too big

### ISSUE THREAD

**Issue by krispypen** [symfony/symfony#4871]
When using the HttpCache, there are files created in the app/cache/prod/http_cache/md for each url. Each time this url is accessed with a differente cookie, an entry is added (because we do vary on cookie). After some days or weeks this file is getting too big. The expired entries are not removed. I don't know if its best to create a command to remove old items, or to do it after lookup, or after write. Maybe just need to clear the cache every night :)

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/Store.php

**Comment by Toflar** [comment]
In case anyone else is still searching: https://github.com/Toflar/psr6-symfony-http-cache-store

**Comment by fabpot** [comment]
closing as explained in #6855
