### ISSUE TITLE
Attempted to call an undefined method named `registerLoader` of class `Doctrine\Common\Annotations\AnnotationRegistry`

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#48717]
In a Flex application, `composer require doctrine/annotations` throws this error:

>Attempted to call an undefined method named "registerLoader" of class "Doctrine\Common\Annotations\AnnotationRegistry"

* [Reproducible test case](https://github.com/ScriptFUSION/Porter/blob/master/.github/workflows/Quickstart%20Symfony.yaml)
* [Output](https://github.com/ScriptFUSION/Porter/actions/runs/3738051446/jobs/6347133717)

**Comment by derrabus** [comment]
This is not a recipe problem. I'm aware of the problem and already working on a fix. For now, please pin `doctrine/annotations` to `^1.14` because Symfony is not (yet) compatible with v2.

**Comment by Bilge** [comment]
So, it is a _what_ problem?

**Comment by derrabus** [comment]
> So, it is a _what_ problem?

👇🏻 

> Symfony is not (yet) compatible with v2.

**Comment by derrabus** [comment]
#48718
