### ISSUE TITLE
PasswordUpgraderInterface::upgradePassword has no `setPassword` method to rely on

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#48743]
### Description

Currently the PasswordUpgraderInterface is written this way
```
interface PasswordUpgraderInterface
{
    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void;
}
```
with
```
interface PasswordAuthenticatedUserInterface
{
    public function getPassword(): ?string;
}
```

But the purpose of this method is:
> This method should persist the new password in the user storage and update the $user object accordingly
so it the `PasswordAuthenticatedUserInterface` interface is missing one method `setPassword` to do this.

So it would make sens to introduce a 
```
interface UpgradablePasswordAuthenticatedUserInterface extends PasswordAuthenticatedUserInterface {
         public function setPassword(?string $password);
}
```
and either
- Change (in a BC way) to `public function upgradePassword(UpgradablePasswordAuthenticatedUserInterface $user, string $newHashedPassword)` because it maybe doesn't make sens to try to upgrade a non upgradable user.
- Or keep the old signature, because
> this method should be opportunistic: it's fine if it does nothing or if it fails without throwing any exception.

So people should write
```
public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void
{
    if (!$user instanceof UpgradablePasswordAuthenticatedUserInterface) {
        return;
    }

    // dothings.
}
```

Ping @nicolas-grekas since I saw you were the author of those interfaces.

**Comment by nicolas-grekas** [comment]
The way I see it, the details of upgrading the password is implementation-dependent.
There is thus no need for a setPassword abstraction.

**Comment by stof** [comment]
Well, this service is not responsible for setting it in the User instance. It is responsible for **persisting the new password hash**. Setting the value is not enough to make it persistent (and you could actually persist it without updating the User object itself, depending on how the project works).

**Comment by VincentLanglet** [comment]
> It is responsible for persisting the new password hash.

Not only, the phpdoc seems pretty clear to me @stof 
https://github.com/symfony/symfony/blob/be1dfc754c21f750d05c6bd9ef8e7e06fa785b90/src/Symfony/Component/Security/Core/User/PasswordUpgraderInterface.php#L22
It's said "and update the $user object accordingly".

So I expect the following behavior according to the PHPDoc.
```
$user->getPassword(); // Old password
$upgrader->upgradePassword($user, 'newPassword');
$user->getPassword(); // New password
```

Maybe the phpdoc should be updated then (?)

**Comment by nicolas-grekas** [comment]
The doc is correct. Setting the password is just implementation-dependent. Could be via a userland setPassword, or whatever, we don't care (and we also don't care if the storage is doctrine or anything else.)

**Comment by stof** [comment]
@VincentLanglet this method must make sure that `getPassword` will return the new hash, indeed. But *how* it ensures that is not defined (as how you *implement* `getPassword` in your User is not specified either). Depending on your implementation, `setPassword()` might not be necessary.

**Comment by VincentLanglet** [comment]
> @VincentLanglet this method must make sure that `getPassword` will return the new hash, indeed. But _how_ it ensures that is not defined (as how you _implement_ `getPassword` in your User is not specified either). Depending on your implementation, `setPassword()` might not be necessary.

Indeed.

**Comment by VincentLanglet** [comment]
Since the way the password is updated is implementation what do you think @nicolas-grekas / @stof about making the PasswordUpgraderInterface generics:
```
 * @template TUser of PasswordAuthenticatedUserInterface
 */
interface PasswordUpgraderInterface
{
    /**
     * @param TUser $user
     */
    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void;
}
```

This way, for static analysis, people could write
```
/**
 * @extends EntityRepository<User>
 * @implements PasswordUpgraderInterface<User>
 */
class UserRepository extends EntityRepository implements UserLoaderInterface, PasswordUpgraderInterface
{
}
```
And when using
```
$userRepository->upgradePassword($user);
```
static analysis tool will report an error if $user is not an User.

And when writing a PasswordUpgraderInterface which require more methods (like a setPassword method), this can be annotate with `@implements PasswordUpgraderInterface<MyExtendedInterface>`.

I opened https://github.com/symfony/symfony/pull/48750
