### ISSUE TITLE
Services registered via custom attribute are not seen by findTaggedServiceIds

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#48777]
### Symfony version(s) affected

5.4.16

### Description

Hi,

I'm trying to create a custom attribute to automatically register my services with a tag.

```php
#[AsMyService(identifier: 'foo')]
final class App\Foo
{
}
```

I register the class in service container:

```yml
app.foo:
    class: App\Foo
```

I create an attribute

```php
#[Attribute(Attribute::TARGET_CLASS)]
final class AsMyService
{
    public function __construct(public string $identifier)
    {
    }
}
```

and finally, in my DI extension:

```php
$container->registerAttributeForAutoconfiguration(
    AsMyService::class,
    static function (ChildDefinition $definition, AsMyService $attribute): void {
        $definition->addTag('my_service', get_object_vars($attribute));
    }
);
```

I would expect this would add a tag to my service definition, but this does not happen, so the definition is not seen by `ContainerBuilder::findTaggedServiceIds`.

I feel like I'm missing something, but it's not obvious to me.

Thanks!

### How to reproduce

No reproducer for now

**Comment by fancyweb** [comment]
Hello, can you create a small example application that allows reproducing your issue?

Is autoconfiguration enabled for the `app.foo` service?

**Comment by emodric** [comment]
Ugh, excuse my foolishness, I was missing `autoconfigure: true`. Closing as this is obviously invalid.
