### ISSUE TITLE
[Security]IsGranted - Denied message 6.2

### ISSUE THREAD

**Issue by boskos-q** [symfony/symfony#48789]
### Description

With the current changes and migration of `#[IsGranted]` from FrameworkExtraBundle in #44705 and with security in mind, having "bad/invalid credentials" message as `Access Denied by #[IsGranted(%s)] on controller` is all against any security policy. With this message, you're exposing your roles to the potential attacker that are required to access on specific route.
Because of that, I'm proposing/suggesting to change this default message as it was before (in FrameworkExtraBundle - which is generic one), `Access Denied`.

**Comment by nicolas-grekas** [comment]
Isn't this displayed only in dev mode?

**Comment by boskos-q** [comment]
> Isn't this displayed only in dev mode?

https://github.com/nicolas-grekas/symfony/blob/6.2/src/Symfony/Component/Security/Http/EventListener/IsGrantedAttributeListener.php#L63
@nicolas-grekas I don't see any checks for dev mode, or I missed something ?

**Comment by nicolas-grekas** [comment]
Exception rendering is not done by the listener. AFAIK, we don't display any messages unless the app runs in debug mode.
Just give your report a try :)

**Comment by chalasr** [comment]
Closing for now as it seems there is no issue, please comment if you think otherwise so we can consider to reopen. Thanks
