### ISSUE TITLE
Error static code analysis for WrappedListener

### ISSUE THREAD

**Issue by SiMoSiMo2** [symfony/symfony#48819]
### Symfony version(s) affected

6.2.2

### Description

I'm running sf 6.2.2 on PHP 8.2 and my PHPStorm reports an error on line 64 of the `Symfony\Component\EventDispatcher\Debug\WrappedListener.php` class:
```
            $this->callableRef = $listener::class.'::__invoke';
```

The error says:
```
'::class' is only allowed on objects
```

### How to reproduce

Just look at the code or at https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php#L64

### Possible Solution

Cast `$listener` to object:
```
$this->callableRef = ((object)$listener)::class.'::__invoke';
```

**Comment by derrabus** [comment]
`$listener` has to be an object at this point. If PhpStorm reports this error here, their type elimination is broken. Report this to JetBrains instead.
