### ISSUE TITLE
[Cache] Caching to a Redis server is broken in 6.2.3

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#48824]
### Symfony version(s) affected

6.2.3

### Description

Since 6.2.3, caching to a Redis server is not working.

I saw this with caching and with the lock component when using a Redis server in the lock dsn.

### How to reproduce

The clearest way to reproduce this is to configure the Lock component to use a Redis server.

1. Create a lock,
2. Acquire a lock.

Under 6.2.2, the lock is successfully acquired.

Under 6.2.3, the acquire lock throws an InvalidArgument exception, "Redis connection "redis://localhost" failed: Redis server went away."

Change the lock dsn to `semaphore`, and the lock is successfully acquired.

**Comment by chalasr** [comment]
Fixed in https://github.com/symfony/symfony/pull/48816
