### ISSUE TITLE
Extend #[MapEntity] to support ODM?

### ISSUE THREAD

**Issue by icvij** [symfony/symfony#48835]
### Description

I've been searching for solution to use #[MapEntity] with MongoDB after switching from 
**Sensio\Framework-Extra-Bundle #[ParamConverter]** 
but seems like there is no support for that currently? It would be nice to get that feature back.

Previously with #[ParamConverter] I would do something like this:
#[ParamConverter('slug', options: ['finder' => 'MyFinder', 'attributes' => ['id', 'email']])]

I have tried to use #[MapEntity] in a few ways to get this working but no luck.

### Example

It would be nice to have something like we had with #[ParamConverter]

#[MapEntity('slug', options:['finder' => 'MyFinder', 'id' => ['id', 'email'])] MyDocument $document

**Comment by derrabus** [comment]
Please open an issue here: https://github.com/doctrine/DoctrineMongoDBBundle

**Comment by shkabo** [comment]
@derrabus not sure about this. This was the feature of ExtraBundle which is being deprecated, and code is being moved to the SF 6.2+ itself. Why would you move paramconverter for ODM to doctrine package, and implement it for ORM with `#[MapEntity]` ?
Both of them should be supported in same "package" either in SF itself or in doctrine package.

**Comment by fabpot** [comment]
Maybe moving MapEntity to Doctrine is the best idea. We won’t support the ODM in Symfony core as there’s no support anywhere for the moment.

**Comment by shkabo** [comment]
This makes sense, as then we'll have `#[MapEntity]` in ORM and e.g. `#[MapDocument]` in ODM which will be alternative to `#[ParamConverter]` which is being deprecated
