### ISSUE TITLE
[Templating] Asset URLs in SSL

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#4883]
Our site is 100% SSL, so ideally, we would like only to set one relative path for the assets and let symfony do de work:

```yml
framework:
  templating:
    assets_base_url: /path/to/my/assets
```

and then in Twig:

```twig
<img src="{{ asset('logo.png') }}"/>
``` 

Which should render:

```html
<img src="/path/to/my/assets/logo.png"/>
```

But unfortunately, under SSL it renders:

```html
<img src="logo.png"/>
```

The documentation clearly states:

> If a URL starts with https:// or is protocol-relative (i.e. starts with //) it will be added to both collections. URL's starting with http:// will only be added to the http collection.

But that implies that relative paths (not starting with "https://" nor "//") won't be added to the ssl collection, which makes us do more work to configure the urls. Wouldn't it be better if ALL urls were copied to the SSL collection except the ones starting explicitely with the non-secure "http://"?

**Comment by fabpot** [comment]
I'm going to take care of this one.

**Comment by fabpot** [comment]
@acasademont Your solution is a hack and works by change. The only way to configure the assets right now is via URLs. Your use case is indeed interesting to support and I will try to make it happen in #13143.

**Comment by acasademont** [comment]
I'll give it a try soon! Yes I know, it's a hack that "just works", not the best solution.

**Comment by fabpot** [comment]
The new PR is #13234
