### ISSUE TITLE
IsGranted Enum Support

### ISSUE THREAD

**Issue by cesurapp** [symfony/symfony#48838]
### Description

Entitlements are stored as enums. It might be a good idea to add Enum support for 6.2 Isgranted.

### Example

    #[IsGranted(AccountPermissionEnum::ROLE_ACCOUNTS)]

**Comment by derrabus** [comment]
We've rejected those kind of requests for other attributes previously. This should work on PHP 8.2:

```
#[IsGranted(AccountPermissionEnum::ROLE_ACCOUNTS->value)]
```
