### ISSUE TITLE
[CssSelector] `Unfinished literal` error when value of attribute selector contains backslash

### ISSUE THREAD

**Issue by luke-** [symfony/symfony#48832]
### Symfony version(s) affected

CssSelector 5.4.17

### Description

Since upgrading CssSelector from `v5.4.11` to `v5.4.17` our Codeception tests throwing the error `DOMXPath::query(): Unfinished literal` when the value of an attribute selector contains a backslash.

### How to reproduce

Add following in a Codeception Test:

```php
$I->seeCheckboxIsChecked('[value="some\namespaced\class"]');
```

(Unfortunately, I couldn't test CssSelector standalone without Codeception yet.)

### Additional Context

Problem introduced here: 
https://github.com/symfony/css-selector/commit/052ef49b660f9ad2a3adb311c555c9bc11ba61f4

**Comment by fancyweb** [comment]
I think the proper CSS selector would be `[value="some\\namespaced\\class"]`. But I guess it won't work anyway.
`\` starts a CSS escape sequence. `\c` is interpreted as a Unicode escape sequence. Our Python upstream implementation has the same behavior. I'm not sure if those escape sequences can and should actually be escaped :man_shrugging:

**Comment by luke-** [comment]
Thanks for the prompt reply. Unfortunately this doesn't work either, I've already tried a few different variants.

Probably we should then try to switch to another selector without backslashes.

**Comment by MatTheCat** [comment]
You need to escape backslashes using PHP **and** [CSS syntax](https://www.w3.org/TR/css-syntax-3/#escaping) to avoid them being treated as an escape sequence’s start:

```php
$I->seeCheckboxIsChecked('[value="some\\\\5c namespaced\\\\5c class"]');
```

The space is only required when the following character could be part of the sequence, but I guess it is simpler to always include it.

(You need to double backslashes to make the [`TokenizerEscaping`](https://github.com/symfony/css-selector/blob/bf1b9d4ad8b1cf0dbde8b08e0135a2f6259b9ba1/Parser/Tokenizer/TokenizerEscaping.php#L37) keep one. I opened a PR to fix that.)

**Comment by MatTheCat** [comment]
I guess this issue can be closed: the remaining issue is somewhat different.
