### ISSUE TITLE
https://github.com/symfony/webpack-encore-pack has been deleted

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#48854]
### Symfony version(s) affected

4.1

### Description

https://github.com/symfony/webpack-encore-pack is gone, my Symfony 4.1 app no longer installs.

I understand this version is not maintained, but I don't understand at all the logic of removing the repository and the Packagist packages. Was there a huge security issue that required this drastic move?

### How to reproduce

Visit https://github.com/symfony/webpack-encore-pack

**Comment by xabbuh** [comment]
https://github.com/symfony/webpack-encore-bundle works for me

**Comment by mnapoli** [comment]
@xabbuh 🤦 my bad I wrote the new repo instead. I updated the issue, I'm talking about https://github.com/symfony/webpack-encore-pack

**Comment by derrabus** [comment]
Packs are meant to be unpacked by Flex. That means they should not be kept in your composer.json file.

**Comment by fabpot** [comment]
Packs are automatically unpacked nowadays, but that was not the case a few years ago. So, maybe that's an old project. You might want to update to the latest Flex version and unpack the packs.

**Comment by wouterj** [comment]
See also http://fabien.potencier.org/symfony4-unpack-the-packs.html and https://github.com/symfony/flex/pull/656

**Comment by mnapoli** [comment]
OK, thank you for providing an upgrade path 👍

What I'm worried about is the deletion of a packagist dependency and its repository. Was there a reason the repo was deleted? This ends up being a breaking change for older projects like mine (breaking not on a major upgrade I mean).

I know open-source resources are limited, I'm not trying to be annoying. It just feels weird knowing that parts of the Symfony ecosystem can disappear from GitHub and break existing projects. Maybe there's a specific reason here?

**Comment by stof** [comment]
Packs are unpacked since 5 years now, meaning that it has been 5 years that the repository is unnecessary during installs. As the pack was not necessary anymore (the `encore` alias was targetting the bundle since years as well), I guess a cleanup dropped the repository. Maybe a better move would have been to archive the repo instead of deleting it.

**Comment by fabpot** [comment]
I don't remember the specifics here, as deleting a repo is not something we're doing. Maybe @weaverryan remembers?
