### ISSUE TITLE
symfony server:start: command PHP-CGI exited, restarting it immediately

### ISSUE THREAD

**Issue by ppodgorskicrido** [symfony/symfony#48862]
### Symfony version(s) affected

6.2.3

### Description

Server crashing while running from `symfony server:start`. That is not a problem while running from Apache 2.4.
I'm completely sure that it's not fault of memory.
Do you have any ideas where to start searching for answers?

### How to reproduce

Server was started by `symfony server:start`
I was calling by curl one endopint multiple times one by one, to test connection with graylog server.
Suddenly server crashed. The only log were in cmd:
`{"level":"error","time":"2023-01-03T09:23:04+01:00","message":"command \"PHP-CGI\" exited, restarting it immediately"}
PHP server exited unexpectedly: unable to write pid file: Process is already running under PID 19052`

### Additional Context

There was no logs.

PHP Version:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies

OS: 
Windows 11

**Comment by ppodgorskicrido** [comment]
I was using two version of symfony cli: 5.4.13 and 5.4.20. It was no difference

**Comment by derrabus** [comment]
Please open an issue here: https://github.com/symfony-cli/symfony-cli/issues
