### ISSUE TITLE
Reduce skeleton

### ISSUE THREAD

**Issue by fabpico** [symfony/symfony#48861]
### Description

My goal was to set up a minimal Symfony codebase for an API application.

According to the [installation documentation](https://symfony.com/doc/current/setup.html#creating-symfony-applications) you can install an API skeleton with 

```
# run this if you are building a microservice, console application or API
composer create-project symfony/skeleton:"6.2.*" my_project_directory
```

In my perspective, this still creates too many files and contents:

```
│   .gitignore
│   composer.json
│   composer.lock
│   symfony.lock
│
├───bin
│       console
│
├───config
│   │   bundles.php
│   │   preload.php
│   │   routes.yaml
│   │   services.yaml
│   │
│   ├───packages
│   │       cache.yaml
│   │       framework.yaml
│   │       routing.yaml
│   │
│   └───routes
│           framework.yaml
│
├───public
│       index.php
│
└───src
    │   Kernel.php
    │
    └───Controller
            .gitignore

```
composer.json
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "6.2.*",
        "symfony/dotenv": "6.2.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.2.*",
        "symfony/runtime": "6.2.*",
        "symfony/yaml": "6.2.*"
    },
    "require-dev": {
    },
    "config": {
        "allow-plugins": {
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.2.*"
        }
    }
}

```

Then I removed following files entirely:
- `config/packages/cache.yaml` (basically just contained lots of commented examples)
- `config/packages/framework.yaml` (I needed none of that content)
- `config/packages/routing.yaml` (I needed none of that content)
- `config/routes/framework.yaml` (I needed none of that content)
- `src/Controller/.gitignore` (why does Symfony guess that I need controllers, I may only create a CLI app.)
- `symfony.lock` (Why do I need this anyways, I am already using composer with its own locking. If its for flex, I don't want to use flex anyways.)
- `bin/console` (why does Symfony guess that I need this, I may only create a REST API)
- `config/preload.php` (Not needed, API works in production without it)

Then I removed most content in `config/services.yaml` (Contains lots of documentation and unneeded excludings).

Reduced to:
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
```

At the end, my composer.json file of a working and integration-tested RPC&REST API looked like this:
```
{
    "require": {
        "php": ">=8.1",
        "doctrine/doctrine-bundle": "^2.7",
        "symfony/dotenv": "6.2.*",
        "symfony/framework-bundle": "6.2.*",
        "symfony/http-client": "6.2.*",
        "symfony/http-kernel": "6.2.*",
        "symfony/runtime": "6.2.*",
        "symfony/yaml": "6.2.*"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "config": {
        "allow-plugins": {
            "symfony/runtime": true
        }
    }
}

```

File structure
```
│   .gitignore
│   composer.json
│   composer.lock
│   phpunit.xml
│
├───config
│   │   bundles.php
│   │   routes.yaml
│   │   services.yaml
│   │
│   └───packages
│           doctrine.yaml
│
├───public
│       .htaccess
│       index.php
│
├───src
│   │   Kernel.php
│   │
│   ├───Controller
│   │       ApiController.php
│   │
│   └───Services (content hidden)
│
└───tests (content hidden)

```

I will create many other Symfony apps in the future, and I wish that the skeleton will be more reduced already by default.

Any chance to optimize in this direction?  
(The phpunit & doctrine dependency and config of course can be left out.)

**Comment by wouterj** [comment]
The great thing about using Composer is that you are free to create your own skeleton using the minimal config you've shown here and use it for your future projects.

All projects are different and it's impossible to predict what any user needs. The minimal skeleton provides a set of files that we believe are common across most of the Symfony applications out there (or otherwise highly recommended).

For instance, the `bin/console` file is extremely useful even if you don't create a CLI application. It allows you to show lots of debugging information, and e.g. clear and warmup the Symfony cache files.

I'm :-1: to make any of the suggested changes to the default skeleton, they all make sense to me the way they currently are (except maybe from `config/preload.php`).

**Comment by derrabus** [comment]
Same here.

**Comment by xabbuh** [comment]
I agree with Wouter and Alexander. Closing therefore, thank you for understanding.
