### ISSUE TITLE
Contracts folder missing in source directory

### ISSUE THREAD

**Issue by excitedbox** [symfony/symfony#48865]
### Symfony version(s) affected

6.2 and 6.3

### Description

I just tried installing symfony 6.2 using composer and got a bug that src/Symfony/Contracts was missing. The git repo shows the folder being there but when I download the zip of the symfony repo it is gone. The same happens with 6.3 as well. Github shows the file and contents on the website though which is why I am confused that it is not in the zip file.

The error is:
In PathRepository.php line 163:

  The `url` supplied for the path (src/Symfony/Contracts) repository does not exist

### How to reproduce

`composer create-project symfony/symfony:"6.2.*" my_project_directory`

**Comment by xabbuh** [comment]
This is expected. The files are excluded in https://github.com/symfony/symfony/blob/e4117121a7bd1f7e07961b12e25b72bd0c03db6c/.gitattributes#L1 and `symfony/contracts` will be installed with Composer: https://github.com/symfony/symfony/blob/e4117121a7bd1f7e07961b12e25b72bd0c03db6c/composer.json#L49

**Comment by wouterj** [comment]
You should no longer use the `symfony/symfony` package as a dependency, and it is not meant to be used with `create-project`. Use the Symfony skeleton in `create-project`, see also the installation documentation: https://symfony.com/doc/current/setup.html#creating-symfony-applications
