### ISSUE TITLE
[DomCrawler] text () function does not properly convert some character entities to text

### ISSUE THREAD

**Issue by Jammmmm** [symfony/symfony#48864]
### Symfony version(s) affected

6.2.4

### Description

I have found the text () function does not convert some character entities to their proper text equivalents, or adds bad characters to the output.

For example, the HTML:

`This&nbsp;is a test&quot;in quotes&quot; &amp; &apos; &lt; &gt; &copy;`

should convert to:

`This is a test"in quotes" & ' < > ©`

but instead converts to:

`ThisÂ is a test"in quotes" & ' < > Â©`

Note the addition of Â in the output.

I've tried explicitly setting the charset (both UTF-8 and ISO-8859-1) in code and in the HTML (with meta charset...) but I always get the same result.

Is this a bug or expected behavior?

### How to reproduce

A very simple example that reproduces it for me:

```
$html = "<html><body>This&nbsp;is a test&quot;in quotes&quot; &amp; &apos; &lt; &gt; &copy;</body></html>";			
try
{
	$crawler = new Crawler ($html);
	echo $crawler->text ();
}
catch (\Exception $e) { }
```

**Comment by fancyweb** [comment]
Copy-pasting your example gives the expected result to me:
```
This is a test"in quotes" & ' < > ©
```

**Comment by MatTheCat** [comment]
In your case the crawler will use UTF-8 so `©` will be encoded as `0xC2 0xA9`. I suspect your response somehow declares an encoding in which `0xC2` is `Â` and `0xA9` is `©`, like ISO-8859-1.

So if there is a bug, it is on your side!

**Comment by fancyweb** [comment]
Could it be related to https://github.com/symfony/symfony/issues/46822?

**Comment by MatTheCat** [comment]
@fancyweb I don’t think so: the string returned by `Crawler::text` is correct. It’s the way @Jammmmm displays it which is wrong.

You can reproduce if you force the response displaying the string to declare an ISO-8859-1 charset.

**Comment by Jammmmm** [comment]
Interesting! I suppose it's a limitation of the Windows command line that I'm using (Windows 8).

Thanks for the information everyone!

**Comment by stof** [comment]
On windows 8, the default terminal indeed does not support UTF-8
