### ISSUE TITLE
Make it possible to override DebugClassLoader settings through .env.local

### ISSUE THREAD

**Issue by TomaszGasior** [symfony/symfony#48872]
### Symfony version(s) affected

5.4

### Description

There is no way to set SYMFONY_PATCH_TYPE_DECLARATIONS used by DebugClassLoader in .env.local.

 I want to disable typing related deprecations because they make my work related to upgrading my app harder — I want to focus on real problems first, then on adding types to my code... From the other hand, I don't want to disable these deprecation for all developers by modifying index.php and keep them by default.

### How to reproduce

Add `SYMFONY_PATCH_TYPE_DECLARATIONS='deprecations=0'` to your `.env.local`. There is no effect, even after `bin/console cache:clear`. 

### Possible Solution

Using $_ENV instead of getenv() here? https://github.com/symfony/symfony/blob/c301d9a49a1562b39d8c28eee2b5f4791d51ab14/src/Symfony/Component/ErrorHandler/DebugClassLoader.php#L137

**Comment by nicolas-grekas** [comment]
`$_ENV['SYMFONY_PATCH_TYPE_DECLARATIONS'] ?? $_SERVER['SYMFONY_PATCH_TYPE_DECLARATIONS'] ?? getenv('SYMFONY_PATCH_TYPE_DECLARATIONS') ?: ''` would work for me, PR welcome.

**Comment by TomaszGasior** [comment]
@nicolas-grekas Could you please elaborate why these three ways of fetching the same env are needed?

**Comment by nicolas-grekas** [comment]
Because of EGPCS settings in php.ini + consistency with how we read env vars elsewhere.

**Comment by xabbuh** [comment]
see #48976
