### ISSUE TITLE
[String] Add `kebab` and `pascal` method similar to `snake` and `camel`.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#48883]
### Description

There is
```
kebab-case
snake_case
camelCase
PascalCase
```

But Symfony/string only provide a `snake` and a `camel` method.
What do you think about adding two `kebab` and `pascal` methods ?

Basically,
kebab would be a snake case with `str_replace('_', '-')`
pascal would be ucfirst°camel

Even if it's easy to implements on our side, I feel like a correctly named method would be better.

**Comment by benjaminfunk** [comment]
work in progress: https://github.com/symfony/symfony/issues/48780

**Comment by derrabus** [comment]
Closing as duplicate of #48780.
