### ISSUE TITLE
PHP ConfigBuilders of DEV-only bundles not working in PROD environment

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#48891]
### Symfony version(s) affected

6.2.4

### Description

Since some bundles are not loaded in PROD (e.g. `DebugBundle` or `WebProfilerBundle`), the dependency injection for their PHP config files is not working (since their `*Config` class is not generated).

### How to reproduce

`config/packages/debug.php`:
```php
<?php declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Config\DebugConfig;
use function Symfony\Component\DependencyInjection\Loader\Configurator\env;

return static function (DebugConfig $debugConfig, ContainerConfigurator $containerConfigurator): void {
    if ('dev' === $containerConfigurator->env()) {
        $debugConfig->dumpDestination('tcp://' . env('VAR_DUMPER_SERVER')->string());
    }
};
```
`config/bundles.php`:
```php
<?php declare(strict_types = 1);

return [
    // ...
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
];
```
Then running `APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear` results in this error:
> Could not resolve argument "Symfony\Config\DebugConfig $debugConfig"
> There is no extension able to load the configuration for "Symfony\Config\DebugConfig". Looked for namespace "debug", found "framework", "doctrine", ...

**Comment by xabbuh** [comment]
Not sure I completely understand what you are trying to achieve. Why are you trying to configure a bundle that is not enabled?

**Comment by ThomasLandauer** [comment]
Cause it's enabled in DEV environment ;-)
To me it looks like there is no PHP equivalent for YAML's `when@dev:`

**Comment by xabbuh** [comment]
Well, you can store the file in `config/packages/dev`.

**Comment by MatTheCat** [comment]
See https://symfony.com/blog/new-in-symfony-5-3-configure-multiple-environments-in-a-single-file (and https://github.com/symfony/symfony/pull/41182) 😉

**Comment by ThomasLandauer** [comment]
@MatTheCat 
Yeah, thanks, I wasn't aware of this!
Let's see if I can find a way to document this on https://symfony.com/doc/current/configuration.html

Is this the right syntax for *multiple* environments?:
```php
return #[When(env: 'dev')] #[When(env: 'test')] static function (WebProfilerConfig $webProfilerConfig,...)
```

@xabbuh
IMO, The old system with the separate directories is confusing; the new way with conditions *inside* the file (e.g. `if ('test' === $containerConfigurator->env()) { }`) is so much nicer. What about recommending this as the preferred way on the docs page?

**Comment by derrabus** [comment]
This is indeed a problem. If we want people to use generated config builders single config files for all environments, we need a solution for bundles that are missing in prod.

**Comment by MatTheCat** [comment]
@derrabus I believe #41182 is the solution, but it’s not (AFAICT) documented.

@ThomasLandauer I just tested and it seems you’re right about the multiple env syntax.

**Comment by derrabus** [comment]
symfony/symfony-docs#15333 was the corresponding docs issue, but it was closed although the PR linked there did not document that attributes can be attached to closures.

Can you open a new issue (or PR if you want) on the docs repo?

**Comment by ThomasLandauer** [comment]
Well, the `#[When]` attribute in fact *is* documented - just not where everybody(?) was expecting it, but on https://symfony.com/doc/current/service_container.html#limiting-services-to-a-specific-symfony-environment ;-)

According to https://github.com/symfony/symfony-docs/pull/16313#issuecomment-1013869556 this was done on purpose, and is about to be reorganized. So I'm not doing anything in the docs.

**Comment by derrabus** [comment]
That comment is > 1 year old. Don't if that should stop you from contributing to the docs.

cc @wouterj

**Comment by wouterj** [comment]
The trick with `#[When]` in configuration files was unknown to me (you can see the example only shows using `#[When]` on a class instead).

I'm +1 on using `#[When]` in configuration examples (at the place were we also document the `when@` syntax) and write one or two sentences about it (that it should be used instead of an if statement to avoid issues with unloaded bundles + that you can also use it on services, linking to the other section).

Are you ok to make those changes, @ThomasLandauer?

**Comment by MatTheCat** [comment]
FYI #41182 also injected an `$env` var in config files for people using PHP < 8.

**Comment by ThomasLandauer** [comment]
As a start, I went through https://symfony.com/doc/current/configuration.html and created some *minor* PR's:
* https://github.com/symfony/symfony-docs/pull/17671
* https://github.com/symfony/symfony-docs/pull/17672
* https://github.com/symfony/symfony-docs/pull/17673
* https://github.com/symfony/symfony-docs/pull/17674
* https://github.com/symfony/symfony-docs/pull/17675

For now, I stopped at this sentence:

> Take the framework package, installed by default, as an example:

Question: The `when@prod:` syntax was introduced in v5.3:

> The ability to defined different environments in a single file was introduced in Symfony 5.3.

But since when is it created by default? I.e. since which version is `config/packages/prod/framework.yaml` not created anymore upon installation?

My suggestion for the following paragraph would be: Show the `when` syntax as *the* way to do it. And only mention the old `config/packages/prod/...` system in some note box (like "In previous versions of Symfony there was another system for dealing with environments...")

Minor question: Can I delete `versionadded:: 5.3` (since 5.4 is now the lowest supported)? Or how long are such version notes usually kept?
