### ISSUE TITLE
[HttpClient] HttpClientDataCollector does not collect data of requests sent within StreamedResponse callback function

### ISSUE THREAD

**Issue by pforesi** [symfony/symfony#48894]
### Symfony version(s) affected

4.4.1 (https://github.com/symfony/symfony/blob/0f51da6ec7c3e905fcfebd49e99e0b4a12a3a733/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)

### Description

When Controller's action method is returning a StreamedResponse like following sample code:

`

    public function event(HttpClientInterface $client): StreamedResponse
    {
       $response = new StreamedResponse();
        $response->setCallback(function () use ($client) {
            $url = 'https://symfony.com';
            $response = $client->request('GET', $url);
        });
        return $response;
    }
`

And the callback method is sending an HTTP request thru the symfony HTTP Client.

The bug: The profiler's Http Client panel is empty.

According our investigation, this is due to the fact that kernel.response event is dispatched (and thus the call to HttpClientDataCollector::collect() method) before HttpClient send the request, so no data are yet collected.

HttpClientDataCollector is already implementing [LateDataCollectorInterface](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpKernel/DataCollector/LateDataCollectorInterface.php) but the lateCollect() is only resetting the client object.

### How to reproduce

1. Fork this github repo: [https://github.com/pforesi/HttpClientDataCollector_issue](https://github.com/pforesi/HttpClientDataCollector_issue)
2. Launch the app (symfony server:start)
4. Browse [https://127.0.0.1:8000/bug/reproducer](https://127.0.0.1:8000/bug/reproducer)
4. Follow the " Steps to check the bug" on the served page.

### Possible Solution

Do data collecting into the lateCollect() instead of the collect() method:

`

    public function collect(Request $request, Response $response, \Throwable $exception = null)
    {
        $this->reset();
    }

    public function lateCollect()
    {
        foreach ($this->clients as $name => $client) {
            [$errorCount, $traces] = $this->collectOnClient($client);

            $this->data['clients'][$name] = [
                'traces' => $traces,
                'error_count' => $errorCount,
            ];

            $this->data['request_count'] += \count($traces);
            $this->data['error_count'] += $errorCount;
        }
        foreach ($this->clients as $client) {
            $client->reset();
        }
    }
`

**Comment by OskarStark** [comment]
Hi, we do not support 4.4 anymore, except for security issues. You should consider upgrading and check if the bug is already fixed.

Thank you

**Comment by OskarStark** [comment]
Oh thanks for the PR against 5.4 👌🏻
