### ISSUE TITLE
[Router] Validate Request in Router

### ISSUE THREAD

**Issue by y4roc** [symfony/symfony#48908]
In the controller I use an attribute to which I pass as parameter the class of the RequestClass. A subscriber then loads the post content and validates it using the RequestClass. Subsequently, an instance of the RequestClass, with the values of the request, is passed as an argument to the controller method.

If the validation fails, the call throws a bad request exception.

Example:
```php
class IndexAction {
  #[RequestValidator(class: IndexRequest::class)]
  public function __invoke(IndexRequest $request) {
    ...
  }
}
```

```php
class IndexRequest {
  #[Assert\NotNull]
  #[Assert\Type(type: 'string')]
  public $username

  public function getUsername(): string {
    return $this->string;
  }
}
```

_Originally posted by @y4roc in https://github.com/symfony/symfony/issues/46991#issuecomment-1369147677_

**Comment by xabbuh** [comment]
How would a generic approach for this look like? Is there really much code that could be abstracted in a reusable way or doesn't this all come down in implementing a custom argument value resolver per use case?

**Comment by y4roc** [comment]
I would create a subscriber in the framework bundle which listens for a request. In the event is the controller function which is called. Using the argument before this function, the data from the request is loaded into the specified class. Then the Symfony validator validates this class. If the validator fails, an HttpBadRequest exception would be thrown.

So the router is not the right place for this, but the framework bundle is in my opinion.

**Comment by xabbuh** [comment]
Something like #47425?

**Comment by y4roc** [comment]
Yes, but will create an DTO-Klass for the request, and the listener will fill them and validate it.

**Comment by BASAKSemih** [comment]
I think we can close this issue through https://github.com/symfony/symfony/pull/49138
