### ISSUE TITLE
[RFC][DependencyInjection] Deprecate the “@required” annotation

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#48909]
### Description

Symfony (including 6.2) supports the `@required` annotation, see for example with Symfony 5.4: https://symfony.com/doc/5.4/service_container/autowiring.html

Tests have to cover a wide range of different cases: https://github.com/symfony/symfony/blob/bc5fea4e2190f00a207871115a83dd7df03d7637/src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/autowiring_classes.php#L244 https://github.com/symfony/symfony/blob/bc5fea4e2190f00a207871115a83dd7df03d7637/src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/autowiring_classes.php#L312

The proposal is to deprecate the `@required` annotation and suggest to replace it with `Symfony\Contracts\Service\Attribute\Required`.

This would simplify the codebase of Symfony at the next major release and encourage users to migrate from annotations to attributes.

See also:
- https://github.com/symfony/symfony-docs/pull/17654
- https://github.com/symfony/symfony-docs/pull/17655
- https://github.com/symfony/symfony/pull/48874

### Example

```diff
- /**
-  @required
- /
+ #[\Symfony\Contracts\Service\Attribute\Required]
```

**Comment by nicolas-grekas** [comment]
Let's do it. Can you please send a PR doing so?

**Comment by tacman** [comment]
On a related note, bumping to doctrine/annotations:^2.0 gives the following error:

  [Semantical Error] The class "Symfony\Contracts\Service\Attribute\Required" is not annotated with @Annotation.                                               
  Are you sure this class can be used as annotation?                                                                                                           
  If so, then you need to add @Annotation to the _class_ doc comment of "Symfony\Contracts\Service\Attribute\Required". 
                                      
  If it is indeed no annotation, then you need to add @IgnoreAnnotation("required") to the _class_ doc comment of method Symfony\Bundle\FrameworkBundle\Controller\AbstractController::setContainer().                                                                                                                    
                                                 `

**Comment by stof** [comment]
@tacman this is reported in https://github.com/symfony/symfony/issues/48792 and fixed in https://github.com/symfony/symfony/pull/48916 (not released yet). Please keep the current issue focused on its actual topic (which is not about a bug report).
