### ISSUE TITLE
[Dependency Injection] AutowirePass depends on symfony/config

### ISSUE THREAD

**Issue by mondrake** [symfony/symfony#48905]
### Symfony version(s) affected

6.2.2

### Description

This line of code in AutowirePass

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L14

makes so that in case a service cannot be determine in autowiring, a fatal error is thrown for missing class.

True it's a fatal anyway, but if symfony/config is installed, the error description is much more accurate.

See https://www.drupal.org/project/drupal/issues/3331324.

### How to reproduce

See https://www.drupal.org/project/drupal/issues/3331324

### Possible Solution

Make symfony/config a dependency in composer.json?

**Comment by derrabus** [comment]
> This line of code in AutowirePass
> 
> 
> 
> https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L14
> 
> 
> 
> makes so that in case a service cannot be determine in autowiring, a fatal error is thrown for missing class.

No, use statements for undefined classes are safe.

> Make symfony/config a dependency in composer.json?

No. But if you can improve the error message for this case, feel free to submit a PR.
