### ISSUE TITLE
[Config][RFC] EnumNode removes values based on loose comparison

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#48913]
### Symfony version(s) affected

v2.1.0+

### Description

In my use-case I have a node with `enabled` field, which can have 3 values:
 - `true`: always enable component
 - `false`: do not enable the component
 - `null`: enable if it's needed (dependent on rather complex logic, outside of the scope of config schema)

The issue is I cannot use `booleanNode()` as it is well... boolean.

### How to reproduce

```php
    ->children()
        ->enumNode('enabled')
            ->values([true, false, null])
            ->defaultNull()
    ->end()
```

While the code above "works", using `bin/console config:dump-reference` reveals that in fact the `null` is not an expected values:

```
 doctrine_changeset_marshaller:
     enabled:              null # One of true; false
```
 

### Possible Solution

The issue stems from usage of `array_unique()` in two places:

https://github.com/symfony/symfony/blob/8308aea9d17c3abb0d69e11fa9f8b5f600a564cd/src/Symfony/Component/Config/Definition/Builder/EnumNodeDefinition.php#L13-L19

https://github.com/symfony/symfony/blob/8308aea9d17c3abb0d69e11fa9f8b5f600a564cd/src/Symfony/Component/Config/Definition/EnumNode.php#L13-L19

The issue is, `\array_unique()` compares values according to their string representation. I believe this is less than idea in the case of `EnumNode`. The `\array_unique()`, unlike functions like `\in_array()` does not support `$strict` parameter ([and the discussion on that died in 2013](https://externals.io/message/68499)). Thus, to really solve this issue a custom strict function would need to be used:

However, this does not cover empty string case. Given the `EnumNode` usage of the array where keys in the array aren't important, I think the solution would be to replace `\array_unique()` call with a function like:
```php
function arrayUniqueStrict(array $values): array
{
    $unique = [];
    foreach($values as $k => $v) {
        if (!\in_array($v, $unique, true)) {
            $unique[$k] = $v;
        }
    }

    return $unique;
}
```

### Additional Context

If the intention of `EnumNode` to be type-loose, then my suggested fix is obviously a no-go. In such a case I think it should be noted in the docs.

**Comment by fancyweb** [comment]
We do use boolean and null values in our own core bundles (EnumNode values are therefore not restricted to scalar values) so I guess the case you describe should logically work. But since it never did for the past 10 years that would be a new feature I guess?

We could maybe simply remove the `array_unique` call and let the duplicated values be displayed several times in messages and configuration references dumps?

**Comment by stof** [comment]
I agree with @fancyweb here. Let's remove the `array_unique` call in 6.3
