### ISSUE TITLE
Fatal error: Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration)

### ISSUE THREAD

**Issue by GeneralFutz** [symfony/symfony#48934]
### Symfony version(s) affected

current

### Description

 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration) in C:\xampp\htdocs\my_project_directory\vendor\symfony\cache\CacheItem.php on line 65
!!  Symfony\Component\ErrorHandler\Error\FatalError {#57
!!    #message: "Compile Error: Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration)"
!!    #code: 0
!!    #file: "C:\xampp\htdocs\my_project_directory\vendor\symfony\cache\CacheItem.php"
!!    #line: 65
!!    -error: array:4 [
!!      "type" => 64
!!      "message" => "Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration)"
!!      "file" => "C:\xampp\htdocs\my_project_directory\vendor\symfony\cache\CacheItem.php"
!!      "line" => 65
!!    ]
!!  }
!!  PHP Fatal error:  Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration) in C:\xampp\htdocs\my_project_directory\vendor\symfony\cache\CacheItem.php on line 65
!!
Script @auto-scripts was called via post-update-cmd
PS C:\xampp\htdocs>

### How to reproduce

Attempted through PowerShell :
PS C:\xampp\htdocs> composer create-project symfony/skeleton:"6.2.*" my_project_directory

Also happened when trying to install the guestbook project through symfony cli.

**Comment by xabbuh** [comment]
It looks like you have https://github.com/jbboehr/php-psr installed and that that extension is not compatible with PSR Cache 2.

**Comment by GeneralFutz** [comment]
looks like that was my issue. Thank You! That was a requirement for the  the phalcon extension.

**Comment by g105b** [comment]
I noticed in my logs that I was seeing a lot of inheritance errors from the `PsrExt` namespace, and realised that I'd inadvertently installed the `php-psr` package via my OS's package manager. In my case `apt remove php8.1-psr` resolved my issue.
