### ISSUE TITLE
Massive performance regression in DomCrawler v6

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#48950]
### Symfony version(s) affected

6.2.3

### Description

The performance of the v6 DomCrawler component is somewhere in the region of 10x slower than that of v5, to do exactly the same work. I process in order of hundreds of thousands of pages per day so a 1000% slow-down is very obvious and also completely impractical (what should take 1 hour now takes 10). If I discovered DomCrawler today I would simply dismiss it as unfit for purpose, but since I've been using it for many years, I am aware simply downgrading to v5 will "fix" the issue.

### How to reproduce

Compare v5 to v6 performance for high volume page parsing. In case you want to use exactly the same parser I do, see: https://github.com/Provider/Steam/blob/master/src/Scrape/AppDetailsParser.php

**Comment by stof** [comment]
The only difference I can think of between v5 and v6 is that `masterminds/html5` is a required dependency in v6 so pages using the HTML5 doctype (i.e. `<!doctype html>`) are always parsed using this userland HTML5. In v5, this parsing was used only if `masterminds/html5` was available in your project, falling back to the parsing based on libxml that is available in ext-dom.

This was done because libxml is unable to parse HTML5 properly, leading to hundreds of bug reports in the past few years about DomCrawler not parsing pages properly.

**Comment by Bilge** [comment]
Unsurprisingly, switching a C++ parser for a PHP one is going to suffer performance issues. I don't know what hundreds of bugs exist with it, but I have yet to encounter any.

**Comment by stof** [comment]
@Bilge libxml is an XML parser. If you write your HTML using the HTML4 rules, the parsing will be correct. But the HML5 syntax has lots of cases that are parsed incorrectly when using libxml.

**Comment by stof** [comment]
Note that the "hundreds of bug reports" were not about having hundreds of bugs. They were mostly duplicate reports saying that DomCrawler was broken when using HTML5 (because of using a non-HTML5 parser)

**Comment by Bilge** [comment]
Seems like we need an HTML 5 parser PHP extension. But since nobody is going to write that, and even if they were, we cannot hold our breath for it, it seems to me the slow userland parser should at least be opt-out if it is no longer going to be opt-in.

**Comment by stof** [comment]
Due to the way the switch between HTML4 and HTML5 parsing is done, there is a way to workaround that: remove the HTML5 doctype before parsing (note that when `masterminds/html5` was installed in the project, symfony/dom-crawler has used the same logic to decide to use it since 4.3.0).

**Comment by Bilge** [comment]
Modifying the input string is a very unintuitive API. Previously, there was a constructor parameter to opt-in to the slow parser.

https://github.com/symfony/dom-crawler/commit/78de2ce2356add2a2317f8f8a95b6f08ea53c00a#diff-a441210c640c41751199b3dcb0610b4dce4020601dbca49bd11abb0657793b63R67-R69

Similarly, there should be a clear and simple mechanism to opt out.

**Comment by stof** [comment]
This constructor argument has never been part of a release. It was replaced in https://github.com/symfony/symfony/pull/30892 (due to my review of https://github.com/symfony/symfony/pull/29306#pullrequestreview-222291643 that happened after merging it), which was part of the same release.
From 4.3.0 to 5.4.x, the HTML5 parser has always been used when those conditions are met:
- the `masterminds/html5` library is available
- the HTML uses the HTML5 doctype

The only change in 6.0 is that the first condition is now always true.

> Modifying the input string is a very unintuitive API.

I called it a *workaround*, not an official API.

**Comment by nicolas-grekas** [comment]
Right now, the crawler instantiation is hardcoded in `src/Symfony/Component/BrowserKit/AbstractBrowser.php`, which is instantiated as service `test.client` declared in `src/Symfony/Bundle/FrameworkBundle/Resources/config/test.php`.

So we'd need a new constructor argument (or a setter) to `AbstractBrowser` (and its child classes) + to `Crawler`.

@Bilge would you like to submit a PR to move this proposal forward?

**Comment by Bilge** [comment]
I don't know what you're talking about. What does this have to do with `AbstractBrowser`, or any other part of Symfony, for that matter? This issue should be entirely isolated to the DomCrawler component.

**Comment by stof** [comment]
@Bilge any solution relying on a constructor argument of the Crawler class will be unusable for anyone using the browser-kit component (as that component instantiates a Crawler). If we implement an opt-out, we will need to find a way to expose it to usages of browser-kit as well, not only for standalone usages of dom-crawler.

**Comment by Bilge** [comment]
I'm still not sure why that has to be a problem to solve in this ticket. It sounds like either `AbstractBrowser` is poorly implemented or the way it is integrated into Symfony is. Why isn't `AbstractBrowser` a test service that the user can elect to override or otherwise modify to suit their needs?

**Comment by wouterj** [comment]
> Why isn't `AbstractBrowser` a test service that the user can elect to override or otherwise modify to suit their needs?

It is, as said in Nicolas' comment here.

But `Crawler` isn't, which is the class that you want to add the opt-out to. And as `Crawler` holds state, it can't be a service (it must be initialized at runtime). So if you want to add an opt-out to `Crawler`, this opt-out method/constructor arg should also be added to `AbstractBrowser`.

The only remaining question in this ticket is, does someone wants to make this actual change in a PR?

(and let's not talk about things like poor or good code, as we weren't directly involved in the 15 years of discussion and decision making that ended up in this implementation)
