### ISSUE TITLE
[DependencyInjection] incomplete support for arrays in tag attribute values

### ISSUE THREAD

**Issue by ju1ius** [symfony/symfony#48956]
### Symfony version(s) affected

6.2

### Description

PR #47364 introduced support for using arrays in tag attribute values.

However the feature is not currently usable because such values are rejected by the `CheckDefinitionValidityPass`.  

### How to reproduce

The following service configuration:
```php
$configurator->services()
  ->set(Foo::class)
  ->tag('foo', ['bar' => ['baz' => 42]);
```
throws:
```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]
at symfony/dependency-injection/Compiler/CheckDefinitionValidityPass.php line 67:
A "tags" attribute must be of a scalar-type for service "App\Foo", tag "foo", attribute "bar".
```

**Comment by ruudk** [comment]
Thanks for fixing/improving this @ju1ius 💙

**Comment by ju1ius** [comment]
@ruudk You're welcome!
And thanks to @aschempp who's done all the hard work !
