### ISSUE TITLE
Constraints\EmailValidator invalid LogicException namespace in VALIDATION_MODE_STRICT

### ISSUE THREAD

**Issue by 99hops** [symfony/symfony#48985]
### Symfony version(s) affected

6.2

### Description

Inside `EmailValidator` in case of `!class_exists(EguliasEmailValidator::class)` there is `throw new LogicException()` which results in:

``
Attempted to load class "LogicException" from namespace "Symfony\Component\Validator\Constraints".
Did you forget a "use" statement for e.g. "Symfony\Component\VarExporter\Exception\LogicException", "Symfony\Component\Validator\Exception\LogicException", "Symfony\Component\Translation\Exception\LogicException", "Symfony\Component\Serializer\Exception\LogicException", "Symfony\Component\Security\Core\Exception\LogicException", "Symfony\Component\PasswordHasher\Exception\LogicException", "Symfony\Component\Mime\Exception\LogicException", "Symfony\Component\Messenger\Exception\LogicException", "Symfony\Component\DependencyInjection\Exception\LogicException", "Symfony\Component\Console\Exception\LogicException", "Symfony\Component\Cache\Exception\LogicException" or "JMS\Serializer\Exception\LogicException"?
``

[https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L77](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L77)

### How to reproduce

Add `Constraints\Email` in `Email::VALIDATION_MODE_STRICT` without `"egulias/email-validator"` [Email](https://symfony.com/doc/current/reference/constraints/Email.html)

### Possible Solution

I suggest we add `use Symfony\Component\Validator\Exception\LogicException;`

**Comment by fabpot** [comment]
See #48986 for a fix (there were 2 problems in this line).
