### ISSUE TITLE
[Security] Up from 5.4 to 6.2 @Security attribute

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#48984]
### Description

I searched many links and PRs, but I dont understand how to replace on Symfony 6.2:
 
`#[Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_MANAGER')")]`

On Symfony 6.2 sensio/framework-extra-bundle is abandoned.

Thx

**Comment by n0rbyt3** [comment]
There is a new ```#[IsGranted()]``` attribute that can also be used with expressions. See the docs: https://symfony.com/doc/current/security/expressions.html

**Comment by W0rma** [comment]
Something like this should work:

```php
// src/Controller/MyController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class MyController extends AbstractController
{
    #[IsGranted(new Expression(
        'is_granted("ROLE_ADMIN") or is_granted("ROLE_MANAGER")'
    ))]
    public function index(): Response
    {
        // ...
    }
}
```

**Comment by javiereguiluz** [comment]
Closing as explained by the previous comments.

Here you have the official reference about using expressions in security access: https://symfony.com/doc/current/security/expressions.html
