### ISSUE TITLE
[PropertyAccess] PropertyAccessor::isReadable() method returns true on a non-existing object's property

### ISSUE THREAD

**Issue by tobalsan** [symfony/symfony#49008]
### Symfony version(s) affected

5.4.13

### Description

I'm using Symfony 5.4 and noticed that there seem to be an incoherent behavior of the [PropertyAccess component](https://symfony.com/doc/5.4/components/property_access.html).

When I test for a non-existing property of an object, it returns true.
I tried this with Doctrine entities, to make sure that I'm not trying to access non-existing properties.

### How to reproduce

Simply create any object and use the property accessor to test for a non existing property.

```php
use Symfony\Component\PropertyAccess\PropertyAccess;

$myObj = new \stdClass();
$my0bj->foo = 'existing property';

$propertyAccessor = PropertyAccess::createPropertyAccessor();

$test1 = $propertyAccessor->isReadable($myObj, 'foo'); // $test1 = true
$test2 = $propertyAccessor->isReadable($myObj, 'bar'); // $test2 = true, but should be false
```

### Additional Context

I find it odd this issue hasn't been reported already, maybe this behavior is intended.
For the moment I reverted to simply using the native php method `has_property`, honestly I don't know what's the advantage in using the PropertyAccess component when you just want to test the existence of a property.

**Comment by xabbuh** [comment]
I cannot reproduce your issue. With this code example `$test2` is `false` for me.

Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
