### ISSUE TITLE
[Security] [RFC] Update Events to retrieve the *real* Authenticator in local env (CheckPassportEvent for instance)

### ISSUE THREAD

**Issue by florentdestremau** [symfony/symfony#49010]
### Description

In local development, doing this will not return the real authenticator used but the [TraceableAuthenticator](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Http/Authenticator/Debug/TraceableAuthenticator.php) instead if you use the profiler:
```php
#[AsEventListener(event: CheckPassportEvent::class)]
public function onCheckPassport(CheckPassportEvent $checkPassportEvent): void
{
    $authenticator = $checkPassportEvent->getAuthenticator(); // TraceableAuthenticator
}
```

To get the real authenticator, you need to retrieve the nested one:
```php
#[AsEventListener(event: CheckPassportEvent::class)]
public function onCheckPassport(CheckPassportEvent $checkPassportEvent): void
{
    $authenticator = $checkPassportEvent->getAuthenticator(); //TraceableAuthenticator
    $realAuthenticator = $authenticator instanceof TraceableAuthenticator ?
        $authenticator->getAuthenticator() : // FormLoginAuthenticator
        $authenticator; 
}
```

I would like to include the ternary inside the event class, as well as in the other Events having this method:

- CheckPassportEvent.php
- InteractiveLoginEvent.php
- LoginFailureEvent.php
- LoginSuccessEvent.php

I'm pinging @wouterj for the idea, I can make a PR if it's something worth it :slightly_smiling_face: 

### Example

If this is accepted you will be able to call `->getAuthenticator()` in a more uniform way.

```php
#[AsEventListener(event: CheckPassportEvent::class)]
public function onCheckPassport(CheckPassportEvent $checkPassportEvent): void
{
    $authenticator = $checkPassportEvent->getAuthenticator(); // FormLoginAuthenticator event in dev environment
}
```

This is a simple version of possible PR:
https://github.com/symfony/symfony/compare/6.3...florentdestremau:symfony:feature/event-authenticator?expand=1

Questions:

- should this replace the existing `getAuthenticator`?
- should I create instead a `getRealAuthenticator` method to allow the existing method to return the TraceableAuthenticator?

**Comment by wouterj** [comment]
I think modifying the existing `getAuthenticator()` is safe as a feature on 6.3.

It won't break code that is currently using the mentioned workaround and I don't think it makes sense to do something specific with `TraceableAuthenticator` in a custom listener (listeners shouldn't directly interact with the authenticator).

Let's open the PR, it's often easier to see and discuss code (and its impact) in a PR.
