### ISSUE TITLE
[PHPUnit bridge] Support for PHPUnit 11.1+

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#49069]
### Description

PHPUnit 10 is around the corner (possibly released next month), and it contains a complete overhaul of its internals, particularly the new event system: https://github.com/sebastianbergmann/phpunit/issues/4676 

The new system also provides an easy way too hook into those events: https://github.com/sebastianbergmann/phpunit/blob/2a89c3c62c4d94fa92b72cb3693ca4fa057e4517/src/Event/Facade.php#L40
Among the events, there are even multiple dedicated to deprecations:
 * triggered by `E_USER_DEPRECATED`: https://github.com/sebastianbergmann/phpunit/blob/main/src/Event/Events/Test/Issue/DeprecationTriggered.php
 * triggered by `E_DEPRECATED`: https://github.com/sebastianbergmann/phpunit/blob/main/src/Event/Events/Test/Issue/PhpDeprecationTriggered.php
 * triggered manually by PHPUnit itself: https://github.com/sebastianbergmann/phpunit/blob/main/src/Event/Events/Test/Issue/PhpunitDeprecationTriggered.php

This maybe warrants a discussion here on how to tackle this new release, and how to leverage all this new features.

**Comment by Jean85** [comment]
I should add that those events are triggered through an [error handler](https://github.com/sebastianbergmann/phpunit/blob/main/src/Util/ErrorHandler.php), and that having the bridge installed actively breaks it.

Maybe we should disable (and later disband) that feature under PHPUnit 10+?

**Comment by stof** [comment]
Well, I don't think PHPUnit 10 contains the existing deprecation-related features of the bridge (at least not all of them).

However, we should look at rebuilding them on top of the PHPUnit events instead of replacing the error handler with our own for PHPUnit 10+.

**Comment by sebastianbergmann** [comment]
I discussed PHPUnit 10's event system with @nicolas-grekas at SymfonyCon in November. I think the way forward for Symfony is to no longer register its own error handler for the bridge, let PHPUnit's own error handle emit events for deprecations etc., and then have the bridge subscribe to the events it is interested in. **If** you want the bridge to produce different output for deprecations than what PHPUnit offers out of the box.

**Comment by dozer111** [comment]
Do u plan to fix it in 6.3?

**Comment by arderyp** [comment]
now that PHPUnit 10 is out, I'm giving this a shot.  I experience the same error noted here: https://github.com/symfony/recipes/issues/1173

@nicolas-grekas notes [here ](https://github.com/symfony/recipes/issues/1173#issuecomment-1419500774) that [this](https://github.com/symfony/test-pack/pull/19) should resolve the problem.

It looks like that was merged, so I'm wondering what the next step is here.

**Comment by Jean85** [comment]
Next step would be adding the PHPUnit 10 support to the deprecation handler; this probably means a nearly total rewrite of it, to be done side-by-side to the old one, since the versioning of the bridge is tied to the framework.

**Comment by arderyp** [comment]
Sounds pretty labor intensive.

Would you say this is a priority of the team, or consumers shouldn't expect to see 10 support for quite some time?

**Comment by stof** [comment]
Well, this indeed requires work. Whether this will be done in time for 6.3 depends of when someone works on it (however, it would be great to have it in 6.3 rather than waiting for 6.4 if possible, given that PHPUnit 10 is stable).
Help is welcome on that topic (but that's indeed not an easy task).

**Comment by Jean85** [comment]
Can we at least consider a quick patch were we completely disable the error handler if we detect PHPUnit 10? As of now, the simple presence of the `symfony/phpunit-bridge` is messing up my CI on https://github.com/facile-it/paraunit/pull/192, see:
 * green build on main branch: https://github.com/facile-it/paraunit/actions/runs/4134171677
 * red on PR: https://github.com/facile-it/paraunit/actions/runs/4207911964/jobs/7304460539
 * commit to remove the bridge: https://github.com/facile-it/paraunit/pull/192/commits/94874a65a2df134aeb287f68ab85c4bf9bd48bfa
 * then (nearly) all failures disappear, remaining are due to missing `ClockMock` class: https://github.com/facile-it/paraunit/actions/runs/4212928270/jobs/7312296419
 
I'm even setting [`SYMFONY_DEPRECATIONS_HELPER` to `disabled`](https://github.com/facile-it/paraunit/blob/94874a65a2df134aeb287f68ab85c4bf9bd48bfa/phpunit.xml.dist#L8) but it seems to not solve the issue. I'll try to set it in real env variables now, but IMO we should disable the whole flow under PHPUnit 10.

[EDIT] Using a real env var fixed it: https://github.com/facile-it/paraunit/actions/runs/4213058997/jobs/7312518640
So it's clear that we need that patch.

**Comment by arderyp** [comment]
@Jean85 I like your idea! I'd rather be able to stay on a neutered `phpunit-bridge` and let it stay silent until its ready rather than switching my project over to raw `phpunit/phpunit` temporarily and then remembering to switch back

**Comment by arderyp** [comment]
@Jean85 are you saying this can be worked around temporarily by setting ` SYMFONY_DEPRECATIONS_HELPER=false` at the core os/linux level, but setting the same var in `.env` or `phpuni.xml` won't work?

**Comment by Jean85** [comment]
Yes, exactly. 

The bootstrap of the bridge is loaded through the autoloader, so long before DotEnv or PHPUnit config can kick in. They can still influence the bridge behavior, but the error handler is already registered (and causing the issue) at that point.

**Comment by arderyp** [comment]
@Jean85 I am unable to reproduce your workaround.

I removed `phpunit/phpunit` (I was explicitly including `^10.0`). Then I did `composer require --dev symfony/test-pack`. It installed `bin/phpunit` and it also installed added `phpunit/phpunit:^9` to my composer.json.  So then I had to require `phpunit/phpunit:^10.0 --with-all-dependencies` to get phpunit back up to 10.

when I run `./bin/phpunit`
```
$ ./bin/phpunit --version
PHP Fatal error:  Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /home/arderyp/app/bin/phpunit:11
Stack trace:
#0 {main}
  thrown in /home/arderyp/app/bin/phpunit on line 1
```

Similar issues when I run  `./vendor/bin/phpunit` I get errors. 
```$ ./vendor/bin/phpunit 
PHP Fatal error:  Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /home/arderyp/app/vendor/symfony/phpunit-bridge/Legacy/CommandForV9.php:25
Stack trace:
#0 /home/arderyp/app/vendor/bin/.phpunit/phpunit-10.0-0/vendor/composer/ClassLoader.php(571): include()
#1 /home/arderyp/app/vendor/bin/.phpunit/phpunit-10.0-0/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/arderyp/app/vendor/symfony/phpunit-bridge/TextUI/Command.php(17): class_alias()
#4 /home/arderyp/app/vendor/bin/.phpunit/phpunit-10.0-0/vendor/composer/ClassLoader.php(571): include('...')
#5 /home/arderyp/app/vendor/bin/.phpunit/phpunit-10.0-0/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /home/arderyp/app/vendor/bin/.phpunit/phpunit-10.0-0/phpunit(22): Composer\Autoload\ClassLoader->loadClass()
#7 /home/arderyp/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(441): include('...')
#8 /home/arderyp/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit(13): require('...')
#9 /home/arderyp/app/vendor/bin/phpunit(120): include('...')
#10 {main}
  thrown in /home/arderyp/app/vendor/symfony/phpunit-bridge/Legacy/CommandForV9.php on line 25
```

Defining hard env var `SYMFONY_DEPRECATIONS_HELPER=disabled` doesn't change the ouput.  The error is occuring because both executables are looking for [this](https://github.com/sebastianbergmann/phpunit/blob/9.6/src/TextUI/Command.php#L94) PHPUnit 9 class/method, which doesn't exist in PHPUnit 10.

I'm wondering how you managed to get phpunit 10 working with `symfony/test-pack` at all.  Or are you just explicitly calling `/vendor/phpunit/phpunit/phpunit` to run your tests?

```
$ ./vendor/phpunit/phpunit/phpunit --version
PHPUnit 10.0.11 by Sebastian Bergmann and contributors.
```

**Comment by Jean85** [comment]
Yeah I'm not using the test pack, just plain PHPUnit + the bridge. I was using it just for the deprecation helper (and the clock mock).

**Comment by arderyp** [comment]
hmmm, okay.  Maybe I will try that. I was using `phpunit-bridge` previously, but it looks like the symfony official documentation has been updated to instruct us to install `symfony/test-pack` instead of `symfony/phpunit-bridge`, which is the only reason I was attempting to install that.  `test-pack` does install `phpunit-bridge`

**Comment by alexislefebvre** [comment]
Maybe this example will help:

- https://github.com/jakzal/phpunit-globals/pull/31

**Comment by arderyp** [comment]
@stof @nicolas-grekas @dunglas i can work on this and submit a PR if you all are interested and have time to review my work.  I've done so for symfony panther, though the work still isn't merged: https://github.com/symfony/panther/pull/589

The change log there could be reduced if we get this package phpunit 10 compliant first, as the work there currently requires a workaround the lack of compliance here.

Are you all interested?

**Comment by nicolas-grekas** [comment]
There are different tasks on the topic. One of them is ensuring test suites can run on phpunit 10. We've already merged some changes on this topic from @OskarStark and @alexandre-daubois mostly. The first step is running deprecation-free on 9.6.
Then, there is figuring out what to do with the bridge itself? I must admit I'm :see_no_evil: for now but sure, any help would be appreciated!

**Comment by arderyp** [comment]
Thanks for the info @nicolas-grekas. Would it be helpful for me to start work or hold off until those other items are addressed first?

Part of the question is whether we are merely adding support for 10, or also dropping support for some older versions(s) too

**Comment by alexandre-daubois** [comment]
I think we're almost done with deprecations brought by PHPUnit 9.6 on the Symfony code base 🙂 Once that's done, I'll have a look at the bridge if I can also do something to help. @arderyp I think that if you have ideas on how to bring support of PHPUnit 10, you should definitely go ahead! 😄

**Comment by arderyp** [comment]
Thanks for the insight @alexandre-daubois.  Is there a specific branch I should be working off of?

**Comment by arderyp** [comment]
@alexandre-daubois @nicolas-grekas will/should 5.4 support phpunit 10? If I work on this, should I be working off the 5.4 branch? I'd certainly like 5.4 to support it.

**Comment by wouterj** [comment]
Per [our release policy](https://symfony.com/doc/current/contributing/code/maintenance.html), adding support for major versions of composer dependencies is always considered a feature, so it must target 6.3 at this moment.

**Comment by manowark** [comment]
Lets switch from using annotations in the unit tests to attributes
Example: `#[DataProvider('...')]`

**Comment by OskarStark** [comment]
But will land in 6.4 because of feature freeze

**Comment by Jean85** [comment]
IIRC that's a non-issue, since the bridge is designed to be used even with an out-of-sync major (so you should be able to use 6.x even if you're using 5.x for the framework).

**Comment by arderyp** [comment]
Interesting. I find it all a bit confusing and I don't know where we are with this.  I see recent commits related to phpunit 10 compatibility, for example:

https://github.com/symfony/symfony/pull/50048

And yet, phpunit 10 and latest bridge still don't work for me.  I can't really figure out what's going on or what to expect.

**Comment by mondrake** [comment]
In the Drupal project, we need this to happen in https://www.drupal.org/project/drupal/issues/3217904 to migrate to using PHPUnit 10, as we are affectionate users of the deprecation bridge.

I know little of the code here, but analyzing how it works I ended up starting, well, 'something' to see if it can support PHPUnit 10. See #50371.

Anyone feel free to provide or get inspiration there, it's far from a PR though.

Key points IMHO:
1. The `SymfonyTestsListener` implementation needs to be dropped, given listeners are removed in PHPUnit10. So we need to replace it with an event collector and event subscribers.
2. Since PHPUnit10 now converts to events any error/warning/notice/deprecation triggered via its own error handler (that completely changed from previous versions), we need to see if we can only rely on events and therefore stop having an overriding error handler in the bridge. If that's attainable, I think it would be a win. If not, we need to ensure the overriding handler 'fits' with the new event system.
3. Personally, I hope we could reimplement in the bridge methods like `expectError*()`, `expectWarning*()`, etc. that were dropped from PHPUnit 10

**Comment by stof** [comment]
The deprecation tracking in the bridge is not yet re-implemented for PHPUnit 10. That's the current state.

**Comment by mondrake** [comment]
Filed a PR for discussion, #50371

**Comment by rvanlaak** [comment]
Although Wouter is [mostly right in his comment](https://github.com/symfony/symfony/issues/49069#issuecomment-1464364901), the policy clearly mentions **changing** the minimal version of a dependency, which is something that won't happen:

> Besides bug fixes, other minor changes might be accepted in a patch version on a case by case basis:
> * **Version updates for Composer dependencies:** Changing the minimal version of a dependency is possible, bumping to a major one or increasing PHP minimal version is not;
https://symfony.com/doc/current/contributing/code/maintenance.html

Adding forward support without bumping versions does seem acceptable, as long as changes don't break the test suite. The debatable section though:

> The following changes are **generally** not accepted in a patch version, except on a case by case basis (mostly when this is related to fixing a security issue):
> * **Adding new classes or non private methods:** While working on a bug fix, never introduce new classes or public/protected methods (or global functions).
https://symfony.com/doc/current/contributing/code/maintenance.html

So, to strictly stay within the scope of a patch, the question to ask is whether forward-compatibility can be added to the bridge without breaking existing tests, and ideally / potentially without introducing new classes.

From a different DX perspective; the deprecation helper is of huge help for everyone in upgrading their existing codebases. Adding forward support to the bridge (which can't live without Symfony nor PHPUnit, but isn't a hard dependency on both either) thereby would be a valid reason to allow to happen within the scope of a 6.3.x patch release.

**Comment by arderyp** [comment]
Thanks @rvanlaak 

I suspect forward support is doable without breaking the test suite.  Doing so without adding new classes may be a tall order, given the substantial API refactor phpunit introduced in 10 for listeners. But it really depends on how symfony implements it's bridge listener.  I haven't had time to dig in, but we got symfony/Panther to support 10 in a way that _could_ have been done without new classes.

**Comment by ili101** [comment]
Can someone tl;dr in what version of Symfony PHPUnit 10.x will be supported? thank you

**Comment by derrabus** [comment]
> Can someone tl;dr in what version of Symfony PHPUnit 10.x will be supported?

Assuming that nobody here can tell the future, the answer to your question is: no, nobody can do that.

**Comment by ili101** [comment]
> Assuming that nobody here can tell the future, the answer to your question is: no, nobody can do that.

I misunderstood the situation, I was under the impression that the code was already committed and is waiting for a major/minor version bump to be released ("But will land in 6.4 because of feature freeze").
But by your comment, I now understand that this is not the case and the feature is still being actively worked on and as such is not scheduled for any version yet?

**Comment by vinceAmstoutz** [comment]
Since I updated the recipe `symfony/phpunit-bridge` PHPUnit 10 works fine for me thanks to https://github.com/symfony/recipes/pull/1249!

**Comment by vkhramtsov** [comment]
@vinceAmstoutz what version of symfony and bridge do you use?

**Comment by tacman** [comment]
@vinceAmstoutz do you have a demo repository showing this, with a PHPUnit 10 test?  That's pretty exciting.

**Comment by vinceAmstoutz** [comment]
@vkhramtsov @tacman I am using the latest version of Symfony 6.4. After, make sure that your `symfony/phpunit-bridge recipe`  is up to date by running `composer recipes`. You can then upgrade your PHPUnit version by directly updating `phpunit/phpunit` with composer, and it will work great!

**Comment by hantsy** [comment]
```xml 
<listeners>
    <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
</listeners>
```
Listeners is not valid in phpunit 10 config.

**Comment by stof** [comment]
Well, the bridge itself has not yet been rewritten to support PHPUnit 10.x.
Fixing the fatal error of the recipe is not the same than adding support for 10.x (which is why this issue is still open)

**Comment by arderyp** [comment]
thanks for the clarification @stof, and for confirming my skepticism regarding the recipe "fix" :)

I look forward to proper PHPUnit 10 support sometime in the near future, hopefully in Symfony 6.4.x!

**Comment by dozer1412131** [comment]
the phpunit11 will released soon.

so, can we say that this library is for phpunit <10 only?(I mean that u as a contributors does not plan to update it)

**Comment by xabbuh** [comment]
@dozer111 There is nothing like "u as a contributors does not plan to update it". Symfony is an open-source project and anyone can contribute the needed changes. If nobody's gonna do that, then the bridge will not support PHPUnit 10+.

**Comment by garak** [comment]
@xabbuh that's fine. The problem is that the constraints expressed in the composer.json file of the bridge are currently allowing for PHPUnit 10 (and even 11), which seems wrong to me.
Maybe the conflict section should be updated.

**Comment by xabbuh** [comment]
@garak That's already too late. Composer will simply pick an older (already released) version of the that doesn't conflict with PHPUnit 10.

**Comment by garak** [comment]
@xabbuh I'm not sure to understand the situations where this could apply... an already installed project with PHPUnit 10 and the latest bridge?
Even if so, changing the conflicts now could solve the problem for new projects, I guess.

**Comment by wouterj** [comment]
@garak if you start a new project and run `composer req phpunit/phpunit:10.*` and then install the PHPunit bridge, it'll install an older version that (incorrectly) declared PHPunit 10 support if we conflict with PHPunit 10 in newer releases.

**Comment by ruudk** [comment]
💶 Putting a €100 bounty on this for anyone who can make the PHPUnit bridge compatible with PHPUnit 10 while keeping the deprecation detection features.

**Comment by stof** [comment]
Adding support for PHPUnit 10.x will probably not happen.

The current plan for the core team is to migrate to the native PHPUnit features to handle deprecations, thanks to Sebastian taking our feedback into account about which features are needed for that (basically, his talk at SymfonyCon about all the history of the new PHPUnit 10 error handler in the various minor version corresponds to Nicolas and me reaching out saying "there is still this feature of the bridge that has no equivalent"). But the last one in the list only made it to PHPUnit 11, not to 10.x (and actually, we still miss the distinction between direct and indirect deprecations which will likely end up in some 11.x minor version), so we will probably jump to PHPUnit 11.x directly.
We haven't yet defined the exact plan about how the support for PHPUnit 9 and 11 will work together.

Implementing our own error handling as was done until now is much harder in PHPUnit 10 than PHPUnit 9 and older due to the new architecture (and maybe not even possible), and would require a huge amount of work anyway (like, several weeks of full time work probably). I doubt 100€ will encourage someone to do such investment

**Comment by connorhu** [comment]
I don't know if @stof was referring to this, but here are Sebastian's slides on the subject: https://thephp.cc/presentations/phpunit-10-for-symfony-developers

**Comment by vinceAmstoutz** [comment]
> Adding support for PHPUnit 10.x will probably not happen.
> 
> The current plan for the core team is to migrate to the native PHPUnit features to handle deprecations, thanks to Sebastian taking our feedback into account about which features are needed for that (basically, his talk at SymfonyCon about all the history of the new PHPUnit 10 error handler in the various minor version corresponds to Nicolas and me reaching out saying "there is still this feature of the bridge that has no equivalent"). But the last one in the list only made it to PHPUnit 11, not to 10.x (and actually, we still miss the distinction between direct and indirect deprecations which will likely end up in some 11.x minor version), so we will probably jump to PHPUnit 11.x directly.
> We haven't yet defined the exact plan about how the support for PHPUnit 9 and 11 will work together.
> 
> Implementing our own error handling as was done until now is much harder in PHPUnit 10 than PHPUnit 9 and older due to the new architecture (and maybe not even possible), and would require a huge amount of work anyway (like, several weeks of full time work probably). I doubt 100€ will encourage someone to do such investment

Tanks for your update, an official post on this will be very cool to inform the community

**Comment by arderyp** [comment]
Thank you @stof for clarifying

I've been using 10 without the bridge for a year or so and it's been working fine with default PHPUnit 19 features. I'm glad you're working with Seb on rolling more into 11.  Your alls collaboration is much appreciated.

**Comment by arderyp** [comment]
hey @stof, I forgot to ask. Does this mean symfony is likely to deprecate `symfony/test-pack` altogether, or just `symfony/phpunit-bridge`?

**Comment by stof** [comment]
@arderyp we will keep `symfony/test-pack` as the target of the `test` alias in Flex. It already brings a bunch of dependencies, not just the bridge.
And we might not even deprecate the bridge at that point as the deprecation handling is not the only feature it provides. We will decide that based on the status of other features.

**Comment by uncaught** [comment]
Like ClockMock for example. I don't think there's a replacement,yet

**Comment by arderyp** [comment]
So then test-pack will be phpunit 10+ compatible eventually @stof ?

**Comment by stof** [comment]
at some point, yes (well, 10+ or 11+ is not clear yet for those other features). But we don't know when yet (we still have work to do)

**Comment by tacman** [comment]
An official post would be most welcome.  I'm confused about the bridge, I'd probably be happy just using PHPUnit itself, but so much of the testing documentation for Symfony uses the bridge that it's hard to separate.  Thanks for the link to the slideshow!

**Comment by derrabus** [comment]
To anyone requesting blog posts: as you can see, we don't know yet how a compatible bridge will look like, so there's nothing to blog about.

**Comment by vinceAmstoutz** [comment]
> To anyone requesting blog posts: as you can see, we don't know yet how a compatible bridge will look like, so there's nothing to blog about.

As soon as you know 😉 Many people are currently confused about the situation, hence my suggestion.

**Comment by vinceAmstoutz** [comment]
> An official post would be most welcome.  I'm confused about the bridge, I'd probably be happy just using PHPUnit itself, but so much of the testing documentation for Symfony uses the bridge that it's hard to separate.  Thanks for the link to the slideshow!

Yes, it's clear that it's not always very clear what role bridge, the test pack and the library play in relation to each other.

**Comment by mondrake** [comment]
Hi, thanks for the update.

In latest PHPUnit 11 I still do not find an alternative to the deprecation ignore file. We use it a lot in Drupal. I saw that the `@group legacy` annotations can be replaced by the `#[IgnoreDeprecations]` attribute, but nothing on the file.

Is that planned if you know?

FTR, I will close now the MR #50371

**Comment by stof** [comment]
PHPUnit also has a concept of baseline (in 10.4+): https://docs.phpunit.de/en/11.0/error-handling.html#ignoring-previously-reported-issues

**Comment by mondrake** [comment]
Yes I saw that, @stof, thanks. I was inquiring on the ignore file since in Drupal we did not implement the baseline, and it will be rather hard to do in our testing framework.

**Comment by stof** [comment]
The plan for the new version of the bridge is to drop all features related to the deprecations, by using the features of PHPUnit. If the current PHPUnit baseline feature is not usable for you, I would suggest discussing that with the PHPUnit team.

**Comment by soyuka** [comment]
I guess phpunit 11.2 now supports direct/indirect (https://docs.phpunit.de/en/11.2/error-handling.html#limiting-issues-to-your-code) and a baseline therefore we don't need the phpunit bridge anymore this should probably be closed in favor of #53812.

**Comment by arderyp** [comment]
So will the test-pack drop the bridge component? That would be nice

**Comment by upyx** [comment]
> So will the test-pack drop the bridge component? That would be nice

Bridge does many things, and PHPUnit isn't the only part of TestPack. If you'd like to install PHPUnit only, you can do it. You do not have to install the whole TestPack.

If I remember right, the original main goal of Bridge was compatibility between tests written atop different PHPUnit versions. Imagine you have a lot of legacy tests in PHPunit (6.x, 7.x, etc.). It would take a while to update them, and there is no guarantee that a bug wouldn't be added. So we need a way to run old tests alongside new ones.

**Comment by derrabus** [comment]
That is correct. You don't have to install PHPUnit through the bridge if you don't want to. Use PHPUnit 11 and be happy with it. Symfony's own test suite is stuck on PHPUnit 9.6 at the moment, but don't let this stop you.

**Comment by stof** [comment]
Also note that the PHPUnit bridge is not only about the deprecation reporting layer. Once we work on using the PHPUnit native deprecation reporting system on 11.2+, we should provide a version of the bridge supporting its *other* features on PHPunit 11

**Comment by soyuka** [comment]
> Also note that the PHPUnit bridge is not only about the deprecation reporting layer. Once we work on using the PHPUnit native deprecation reporting system on 11.2+, we should provide a version of the bridge supporting its other features on PHPunit 11

Let's see what can be done! Mocks should already work with phpunit 11, is there a repository where we could move these and avoid the phpunit 9 dependency lock? 

For other features I think that most are not useful to Symfony developers but let's see each documented feature.

1. Sets by default a consistent locale (C) for your tests (if you create locale-sensitive tests, use PHPUnit's setLocale() method);

`setLocale` is deprecated but anyways is not useful, just use the native `setlocale` if you really need this (https://github.com/sebastianbergmann/phpunit/issues/5200#issuecomment-1429873185)

2. Auto-register class_exists to load Doctrine annotations (when used); 

Not needed anymore, use attributes.

3. It displays the whole list of deprecated features used in the application;

`--display-deprecations` 

4. Displays the stack trace of a deprecation on-demand;

`--display-deprecations` outputs the stack trace

5. Provides a ClockMock, DnsMock and ClassExistsMock classes for tests sensitive to time, network or class existence;

Any idea where to move these?

6. Provides a modified version of PHPUnit that allows:
  a. separating the dependencies of your app from those of phpunit to prevent any unwanted constraints to apply;

Not sure why this is needed by Symfony users this should probably stay internal.

  b. running tests in parallel when a test suite is split in several phpunit.xml files;

If you need this you will probably prefer [ParaTest](https://github.com/paratestphp/paratest) or `--process-isolation`

  c. recording and replaying skipped tests;

I never needed this but there's no equivalent right now as far as I know. 

7. It allows to create tests that are compatible with multiple PHPUnit versions (because it provides polyfills for missing methods, namespaced aliases for non-namespaced classes, etc.).

Same as above I think that this is mostly for Symfony tests and it should probably stay internal.

**Comment by nikophil** [comment]
I don't think that `--display-deprecations` outputs the stack trace

**Comment by derrabus** [comment]
> is there a repository where we could move these and avoid the phpunit 9 dependency lock?

There is no dependency lock. You can install the PhpUnitBridge together with PHPUnit 11. Or am I missing something?

**Comment by AnjaLiebermann** [comment]
Is there any hope of symfony/phpunit-bridge supporting the newer phpunit versions? 
ClockMock is a fantastic feature, but with any of my projects, which doesn't need it I threw the bridge away and use phpunit 11.3 directly.

**Comment by derrabus** [comment]
> ClockMock is a fantastic feature

If you want to work on making ClockMock compatible with PHPUnit 11, please do so. It's not actively being worked on, as far as I know.
