### ISSUE TITLE
[http-client] trailing slash redirect not save header

### ISSUE THREAD

**Issue by AntonA46** [symfony/symfony#49099]
### Symfony version(s) affected

6.2.5

### Description

In the case when a redirect occurs with the presence / absence of a trailing slash, a redirect occurs, but the headers are not saved. If we had a "Content-Type" header, then it won't be there after the redirect

### How to reproduce

We make the route "issues/" send a request to "issues" with the header "Content-Type: json". It will redirect to "issues/". The "Content-Type" header will be missing

Header with redirect:
`{"user-agent":["PostmanRuntime\/7.28.4"],"accept":["*\/*"],"postman-token":["a194cf77-ed00-4a2b-82b1-09462b4f95d3"],"accept-encoding":["gzip, deflate, br"],"connection":["keep-alive"],"referer":["http:\/\/my-project-directory.ru\/test"],"host":["my-project-directory.ru"],"x-php-ob-level":["1"]}`

Header without redirect:
`{"content-type":["application\/json"],"user-agent":["PostmanRuntime\/7.28.4"],"accept":["*\/*"],"postman-token":["5070cc5d-80db-46ff-8dc5-77877cc88873"],"host":["my-project-directory.ru"],"accept-encoding":["gzip, deflate, br"],"connection":["keep-alive"],"x-php-ob-level":["1"]}`

**Comment by MatTheCat** [comment]
[The `fetch` specification](https://fetch.spec.whatwg.org/#http-redirect-fetch) says that a POST request will transform to GET (losing its body and `Content-Type`) after a 301 or 302 response. This is probably what is happening to you?

**Comment by AntonA46** [comment]
> [The `fetch` specification](https://fetch.spec.whatwg.org/#http-redirect-fetch) says that a POST request will transform to GET (losing its body and `Content-Type`) after a 301 or 302 response. This is probably what is happening to you?

No, in both cases GET requests are used

**Comment by MatTheCat** [comment]
What is the `HttpClientInterface` implementation in your case?

**Comment by AntonA46** [comment]
> What is the `HttpClientInterface` implementation in your case?

I used a clean version of Symfony: composer create-project symfony/skeleton:"6.2.*" my_project_directory

Haven't installed anything else to test this moment

**Comment by MatTheCat** [comment]
I mean, is your client a `AmpHttpClient`, a `CurlHttpClient`, `NativeHttpClient` or something else?

**Comment by AntonA46** [comment]
> I mean, is your client a `AmpHttpClient`, a `CurlHttpClient`, `NativeHttpClient` or something else?

I do not quite understand what is at stake. The request is sent using Postman.

Controller code:

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class Test extends AbstractController
{
     #[Route('/test/', name: 'test')]
     public function test(Request $request)
     {
         dd(json_encode($request->headers->all()));
     }
}

Composer.json:
     "require": {
         "php": ">=8.1",
         "ext-ctype": "*",
         "ext-iconv": "*",
         "symfony/apache-pack": "^1.0",
         "symfony/console": "6.2.*",
         "symfony/dotenv": "6.2.*",
         "symfony/flex": "^2",
         "symfony/framework-bundle": "6.2.*",
         "symfony/runtime": "6.2.*",
         "symfony/yaml": "6.2.*"
     },

**Comment by MatTheCat** [comment]
Well you tagged your issue `http-client` but if it concerns Postman it has nothing to do with Symfony 😅

**Comment by stof** [comment]
The `Content-Type` header does not make sense in a GET request as it has no body (and so no content that can have a type).

Anyway, it is not Symfony that does not include the header in the request done after the redirection but postman (as it is not Symfony doing the request). And I think that Postman is totally right when doing that, according to the HTTP specification.
