### ISSUE TITLE
[http-client] No longer showing requests in the http_client profiler

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#49096]
### Symfony version(s) affected

6.2.5

### Description

In 6.2.2 I was getting trace information in the http_client profiler to run tests on so I could check some requests were made. In 6.2.5, the profiler no longer has this data.

### How to reproduce

Using `$collector = $this->getProfile()->getCollector('http_client')` in my test, I loop through each client. The clients have an empty array in the `trace` property now.

### Possible Solution

Investigating

**Comment by silverbackdan** [comment]
I can confirm that `collectOnClient` in `HttpClientDataCollector` is returning the traced requests.
This is an interesting one. The function `collectOnClient` seems to be called twice in my tests. The first time I can see the trace, and in the second the trace has gone.
I'm running Behat tests, I'm curious if perhaps the way in which I get the profiler data may need to be changed.

**Comment by silverbackdan** [comment]
I can indeed see that for some reason, when I trace the calls to this function, it is being called from the behat test twice with the exact same stack trace. I assume that means in the most recent update, the trace is cleared once it has been read for the first time?

**Comment by silverbackdan** [comment]
The Behat test appears to just call `Symfony\Bundle\FrameworkBundle\KernelBrowser::request` once from `Behatch\HttpCall\Request\BrowserKit::send` but I can see that the `collectOnClient` is being called twice. Any ideas much appreciated.

**Comment by nicolas-grekas** [comment]
This was likely caused by #48898. /cc @pforesi is case you can have a look :pray:

**Comment by silverbackdan** [comment]
Appreciated :)

**Comment by silverbackdan** [comment]
This may only be a DELETE request issue. I don't think my GET request tests were failing.

To clarify, when I make a DELETE request to an endpoint, I am expecting an HTTP PURGE request to be made to a cache layer. When I create a PATCH request and expect that to result in a PURGE request to be sent to the cache layer, that test still works and I see the cache layer request in the http client traces.

But adding a conflict for the latest http client release does resolve the issue so that problem is somewhere in the http client component.

**Comment by Laulibrius** [comment]
Hi! I think this PR (https://github.com/symfony/symfony/pull/49104) broke something instead of fixing, since http_client requests was in profiler with v6.2.5 but not anymore with v6.2.6.
When i switch back http-client component to v6.2.5, it's working again.

**Comment by stof** [comment]
If late data is missing when using the profile in WebTestCase, the right fix would be to make sure that `lateCollect` works in those cases, not to do hacks in various collectors IMO.

**Comment by fpaterno** [comment]
> Hi! I think this PR (#49104) broke something instead of fixing, since http_client requests was in profiler with v6.2.5 but not anymore with v6.2.6. When i switch back http-client component to v6.2.5, it's working again.

Same problem here with 5.4.20 version.

**Comment by jvengeon** [comment]
Same problem here in 6.2.6, Http Client tab is empty in profiler. When revert in 2.6.5, everything is ok. @nicolas-grekas an idea of the problem ?

**Comment by fancyweb** [comment]
https://github.com/symfony/symfony/pull/49301 has been merged and fixed it.
Feel free to try the patch locally to confirm it works for you :-)

**Comment by jvengeon** [comment]
> 

I tried the patch and it fixes the problem. Thank you
