### ISSUE TITLE
Slow and resourse greedy autowire of classes with large number of interfaces

### ISSUE THREAD

**Issue by DimanKuskov** [symfony/symfony#49105]
### Symfony version(s) affected

5.4.0 and upper

### Description

When class implements multiple interfaces, AutowirePass generates combined aliases for any set of implemented interfaces. 
(see https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L585)

This means that the set of combined aliases will be 2^(number of interfaces implemented) for this class. This results in exponential growth of time and memory required for container generation, resulting in slow or impossible run of `cache:clear`

25 three-letter-named interfaces will result in >10GB memory usage for `cache:clear`.

Neither PHP standart nor Symfony documentation do limit a number of possible interface number in class. Interfaces may be used to tag class and may be auto-generated in some cases. This makes above discribed situation, though rare, but possible. Furthermore, it is generally a bad practice to use algorithms with exponential difficulty where more quick algorithms can be used.

### How to reproduce

* Create new symfony project.
* Create a reasonable amount of empty (marker) intefaces.
* Create a class, that implements these interfaces.
* Clear the cache.

These steps are done in https://github.com/DimanKuskov/symfony_issue

### Possible Solution

* Best solution is to completely rework handling of union types, searching for available implementation based on required union definition.
* Quick solution would be not to try to generate all possible sets for classes with large amount of interfaces and produce a warning or error.

**Comment by stof** [comment]
The autowiring is explicitly not based on searching available implementation. The old autowiring system (before Symfony 3.3) was based on such approach, and it was totally unreliable (adding a new class in the project could suddenly change what gets autowired in a surprising way). At that time, the official recommendations were not suggesting to use autowiring because of that. And it was also a lot slower to build the container, because it required search for all injection points (based on the number of available services in the container, which grows much more frequently than the max number of interfaces on a single class)

**Comment by DimanKuskov** [comment]
Current implemetation actually does not handle correctly Union types, only Intersection. Based on the current realisation, for correct Union handling class alliases must be combined with all possible other classes, not only interfaces of current class. 
Dependency `T1|T2` should be wired by any of `T1` and `T2`, but in current code it is can only be wired by `class T implements T1, T2` (wich is actualy `T1&T2`). Dependency `T1|NonImplementedClass` will never be wired, although `T1` might exist.

Implementation for Unions (https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L618) obviously can not be the same as for Intersections (https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L619)

This is actually a more serious bug than the one I initially reported.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, that made it easier for me to understand and fix the issue. See #49128
About the behavior itself, it's working as design in #43479 and it still makes the most sense to me.
As @stof already explained, playing a guess game with what services implement is a dead end.
Autowiring aliases are just plain string indexes.
