### ISSUE TITLE
[PropertyInfo] DoctrineExtractor makes it impossible to denormalize "null" onto nullable properties

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#49149]
### Symfony version(s) affected

6.2.0

### Description

The `DoctrineExtractor` (for the PropertyInfo component) uses the `nullable: true/false` information for the `ORM\Column` to determine whether or not a property is "nullable". This results in the denormalizer thinking that `null` is not a value value for these nullable properties.

### How to reproduce

Reproducer: https://github.com/weaverryan/entity_nullable_property_info_reproducer

It's dead simple. Consider this entity:

```php
#[ORM\Entity]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    public ?int $id = null;
}
```

Then you denormalize with this data:

```php
$denormalizer->denormalize(['id' => null], Product::class);
```

This will fail with a `NotNormalizableValueException`:

> The type of the "id" attribute for class "App\Entity\Product" must be one of "int" ("null" given).

The problem is that the `DoctrineExtractor` tells the `PropertyInfo` component (incorrectly) that `id` does NOT allow null. That is true for the database. But as far as PHP is concerned, this property IS nullable.

Is this a bug? Or am I doing something totally wrong?

### Possible Solution

We could... make `DoctrineExtractor` use reflection to determine the nullable value? But, this class is SUPER old... and it's been this way forever... and seemingly on purpose.

Am I missing some obvious work-around? Does API Platform work-around this somehow?

**Comment by stof** [comment]
Well, DoctrineExtractor is here to determine things based on the Doctrine mapping. If all you want is whether the php object accepts `null` (and not whether Doctrine will accept this object after that), use other extractors instead.
We already have extractors that use Reflection or the phpdoc.

**Comment by weaverryan** [comment]
But the extractor's job is to inform the PropertyInfo component. So it seems to me that saying that this property is "does not allow null" because the column in the database does not allow null is wrong. WDYT?

> use other extractors instead. We already have extractors that use Reflection or the phpdoc.

If you're using the framework, is this a realistic option? Is it possible to turn off some extractors? Even if you can, it'd be a shame to turn off this entire extractor because it's reporting one incorrect thing.

**Comment by derrabus** [comment]
`DoctrineExtractor` uses Doctrine's metadata to determine types, under the assumption that your entity model strictly follows the database model. And under that assumption, it is right in your case.

If your entities are really fully typed as in your example, I believe `DoctrineExtractor` is not the best source of type information anymore. Rather use reflection or the PHPStan extractor.

**Comment by weaverryan** [comment]
Thanks for both of your answers :).

For Live Components, I want to allow users to have the flexibility of setting not-yet-persisted entities on their properties, which would then be serialized and deserialized via the serializer. So, from a library level, I don't think I can rearrange or choose their extractor. 

I'm trying to think of some workaround. I suppose I could set the `DISABLE_TYPE_ENFORCEMENT = true` context to disable type-checks? If a non-persisted entity is being serialized/deserialized, it is read-only (protected by a checksum), so we are guaranteed that the user isn't modifying the data.

**Comment by weaverryan** [comment]
Closing - I've used the workaround described, and it works fine for my case :)
