### ISSUE TITLE
[DependencyInjection] Update from 6.2.2 not working

### ISSUE THREAD

**Issue by louismariegaborit** [symfony/symfony#49148]
### Symfony version(s) affected

6.2.5

### Description

When I update my project from 6.2.2 to 6.2.5, cache:clear doesn't work.
I identify that I can update to 6.2.5 all symfony components except symfony/dependency-injection which still in 6.2.2. After this version cache:clear doesn't work.
I have this error : 
```
Script cache:clear returned with error code 137
!!  Killed
```
![image](https://user-images.githubusercontent.com/15611563/215355091-71590354-3d8b-4ee2-a454-0ca2ec2274d8.png)

### How to reproduce

Update project symfony/dependency-injection from 6.2.2 to 6.2.5.

**Comment by nicolas-grekas** [comment]
Can you please provide a small app reproducing the issue?

**Comment by louismariegaborit** [comment]
I tried to initialize an new symfony project. I copied composer.json and composer.lock from my project to new project and I don't have problem.  
It seems that it's my project that have problem. How can I debug to find what service is causing the problem ?  
Do you have any idea about changes since 6.2.2 that could break the container ?

**Comment by GromNaN** [comment]
You can run `bin/console cache:clear -vvv` to get more details.

You can specify each bugfix version in your composer.json to find the exact version that causes this bug, and review the [changelog](https://github.com/symfony/symfony/blob/6.2/CHANGELOG-6.2.md).

**Comment by nicolas-grekas** [comment]
You might have a recursive loop. Try enabling xdebug's stack limit. Then I would look for a constructor that does too much, eg calling a method of one of its injected dependencies.

**Comment by louismariegaborit** [comment]
I found that it's this commit which cause the error.  
https://github.com/symfony/dependency-injection/commit/58f2988128d2d278280781db037677a32cf720db
@nicolas-grekas : In other word, you advise me to execute cache:clear with xdebug enable ? Because, without tool, find loop it's very hard in big project.

**Comment by timo002** [comment]
I'm running into the same issue, `segmentation fault`.

This only happens when I'm updating `symfony/dependency-injection` to version `5.4.19` or `5.4.20`. Version `5.4.17` is working without any problems.

To test this, use this gist and just run composer install.
https://gist.github.com/timo002/5a37e37ef65fd417991d6c32ea98e171

**Comment by nicolas-grekas** [comment]
> To test this, use this gist and just run composer install.

I just did but didn't reproduce the issue. Can you please have a look?

**Comment by timo002** [comment]
Hello Nicolas,

If I download my gist and unzip the file I get a folder. Then inside that folder I run `composer install`. This ends up with the error.

I'm running this on PHP 7.4.30 with composer 2.5.4. I get this error on my host machine (MacBook Pro with PHP 7.4.30) and on my Docker image (PHP 7.4.28).

<img width="738" alt="afbeelding" src="https://user-images.githubusercontent.com/6170938/224325263-05155a51-1cc0-42cd-9e34-5cf99662a510.png">

**Comment by xabbuh** [comment]
That's because your gist does not contain any other files of your Symfony application and so there is no Symfony console to run.

**Comment by xabbuh** [comment]
Let's close here for now as the issue as is is not reproducible. Though we can consider to reopen once we are able to do so. Thank you for understanding.
