### ISSUE TITLE
[Translation] Phrase translation provider

### ISSUE THREAD

**Issue by wickedOne** [symfony/symfony#49142]
hi,

i've written a [phrase](https://phrase.com/products/phrase-strings/) translation provider and was wondering whether symfony is willing to adopt it like they do with crowdin. loco and lokalise.

if so, please let me know how to proceed.

https://github.com/wickedOne/phrase-translation-provider

**Comment by chr-hertel** [comment]
Hey @wickedOne 

I'd say it would be great to move it into `Symfony\Component\Translation\Bridge\Phrase` and register it in framework bundle.

See PR #40927 for an example and make sure to add it to the docs as well:
https://github.com/symfony/symfony-docs/blob/6.3/translation.rst#installing-and-configuring-a-third-party-provider

**Comment by wickedOne** [comment]
https://github.com/symfony/symfony/pull/49231
