### ISSUE TITLE
[Messenger] Also listen to `SIGINT` in `StopWorkerOnSigtermSignalListener`

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#49156]
### Description

ATM, [StopWorkerOnSigtermSignalListener](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Messenger/EventListener/StopWorkerOnSigtermSignalListener.php#L32) listen only `SIGTERM`. 

IMHO, it should also listen SIGINT (CTR+C) for the following reasons:

* in dev, we can have the same behavior than in production
* in prod, when adding manually more consumers (yeah, SSH + `bin/console` 🧓🏼), it's boring to stop them cleanly. CTRL+C is easier
* I always found it weird it doesn't listen SIGINT - Okay, this is not a valid argument :) 

cc @Tobion 

---

I'll make the PR if accepted

**Comment by rmikalkenas** [comment]
What if make possible sygnals configurable via constructor? It could accept an array of posix signals which would stop the worker.

For example in my project, we terminate workers with `SIGQUIT` and for it to work I had to create a new listener

@lyrixx wdyt?

**Comment by lyrixx** [comment]
How Would you configure the subscriber ?

**Comment by rmikalkenas** [comment]
@lyrixx like this. Except `$signal` could be `int[]` instead, then `onWorkerStarted` would simply iterate and call `pcntl_signal`

```
final class StopWorkerOnPcntlSignalListener implements EventSubscriberInterface
{
    public function __construct(private readonly int $signal) {}

    public static function getSubscribedEvents(): array
    {
        return [WorkerStartedEvent::class => ['onWorkerStarted', 100]];
    }

    public function onWorkerStarted(WorkerStartedEvent $event): void
    {
        pcntl_signal(
            $this->signal,
            static function () use ($event): void {
                $event->getWorker()->stop();
            },
        );
    }
}
```

**Comment by lyrixx** [comment]
Sorry, I was not clear. With Symfony full stack, this service is not created by you, but by the framework. So how would you configure it? I think we can set some sane defaults, then if you want other signals, you replace the services arguments. Are you OK with this? I'll do the PR ASAP

**Comment by lyrixx** [comment]
I opened a PR ☝
