### ISSUE TITLE
`#[MapEntity]` expr doesn't work when fetching an entity with two ids

### ISSUE THREAD

**Issue by LucileDT** [symfony/symfony#49155]
### Symfony version(s) affected

6.2.5

### Description

According to [the MapEntity documentation](https://symfony.com/doc/current/doctrine.html#fetch-via-an-expression), I should be able to use a custom `expr` to find an entity. 

I tried to convert 
```php
#[Route('/bobulus/{id}/thethird', name: 'bobulus_thethird_')]
class BobulusSquireController extends AbstractController
{
    #[RouteBackoffice('/{squire_id<\d+>?0}', name: 'show', methods: ['GET', 'POST'])]
    #[Entity('bobulusSquire', expr: 'repository.findOneOrNullByIds(id, squire_id)')]
    public function show(
        Request $request,
        Bobulus $bobulus,
        ?BobulusSquire $bobulusSquire,
        EntityManagerInterface $em,
    ): Response {
```

to
```php
#[Route('/bobulus/{id}/thethird', name: 'bobulus_thethird_')]
class BobulusSquireController extends AbstractController
{
    #[RouteBackoffice('/{squire_id<\d+>?0}', name: 'show', methods: ['GET', 'POST'])]
    public function show(
        Request $request,
        Bobulus $bobulus,
        #[MapEntity(expr: 'repository.findOneOrNullByIds(id, squire_id)')] ?BobulusSquire $bobulusSquire,
        EntityManagerInterface $em,
    ): Response {
```

But Symfony throws an error `Binding an entity with a composite primary key to a query is not supported. You should split the parameter into the explicit fields and bind them separately.`. 

It seems the `MapEntity` does not do its job at evaluating the given `expr`, as the error is the same with or without a `MapEntity` annotation.
It also seems to occur with or without an existing `squire_id` passed in URL.

### How to reproduce

- create a Symfony project
- create 3 entities:
  - `Bobulus` (`id`, `label`)
  - `Squire` (`id`, `label`)
  - `BobulusSquire` (`bobulus`, `squire`, `description`), having as id a `Bobulus` and a `Squire`
- create their corresponding repositories
- in BobulusSquireRepository, add a method `findOneOrNullByIds($bobulusId, $squireId)`
- create a BobulusSquireController
  - with a `show` action, 
  - use `#[MapEntity(expr: 'repository.findOneOrNullByIds(id, squire_id)')]` to retrieve the BobulusSquire given in URL parameters 
  - and `dd()` the retrieved BobulusSquire in the `show` action body
- insert some valid dummy data in the database for Bobulus, Squire and BobulusSquire
- call the URL with parameters allowing to in theory retrieve an existing BobulusSquire

### Additional Context
I have `sensio/framework-extra-bundle` installed to generate CRUD controllers

**Comment by stof** [comment]
> I have `sensio/framework-extra-bundle` installed to generate CRUD controllers

I don't understand this sentence. `sensio/framework-extra-bundle` does not have a feature to generate CRUD controllers.

> But Symfony throws an error

Can you share the stack trace of the error ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
