### ISSUE TITLE
filesystem.html#remove

### ISSUE THREAD

**Issue by tguenneguez** [symfony/symfony#49157]
### Description

Is strange to not be able to specify that the remove fonction off filesystem is recursive ?
By default it will be disable, but some time it will be greate.

Thanks
Thomas

**Comment by xabbuh** [comment]
I am not sure I understand what you mean. Can you explain a bit more what you mean?

**Comment by tguenneguez** [comment]
There is a fonction remove
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Filesystem/Filesystem.php#method_remove
It will be great to use it like :
self::doRemove($files, true);

**Comment by xabbuh** [comment]
But the method Antrag does remove directories recursively. The argument you are referring to is only used to carry internal state.

**Comment by wouterj** [comment]
I think you are misunderstanding the `doRemove()` method. As far as I know, this method does remove recursively (as you can't non-recursively remove a directory).
