### ISSUE TITLE
[RFC][Workflow] Unused parameter $transitionId in styleStatemachineTransition: deprecate it?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#49175]
### Description

I came across an unused parameter, the `$transitionId` parameter is not used in the `styleStatemachineTransition` function:

https://github.com/symfony/symfony/blob/bc5fea4e2190f00a207871115a83dd7df03d7637/src/Symfony/Component/Workflow/Dumper/MermaidDumper.php#L211-L228

Removing this parameter would be a BC break.

Should this parameter be deprecated and throw a deprecation when it's used by some code that extend `MermaidDumper`? Is it worth the extra work?

On one hand, deprecation require work for Symfony maintainers, maintainers of bundles and end users. On the other hand, this code will continue to work if it's kept as is.

**Comment by xabbuh** [comment]
Since the method is private the argument can be removed ~with~ without the need to trigger a deprecation first (we are in control of all consumers of this method).

**Comment by alexisLefebvre** [comment]
@xabbuh Thanks for the feedback.

The `$transitionId` parameter is required so a deprecation would be triggered by every call to the method. I don't know what to do here.

**Comment by stof** [comment]
the sentence of @xabbuh has a typo. `with` should be `without`.

There is no need to make deprecations for private things. Private code (outside non-internal traits) does not have any BC implications as it cannot be used externally.

**Comment by alexisLefebvre** [comment]
My bad, I mixed up private and protected. I'll submit a PR.
