### ISSUE TITLE
[Serializer] Improve normalization performance?

### ISSUE THREAD

**Issue by 1ed** [symfony/symfony#49196]
### Description

Hi, currently the normalization process looks like this:

- getting a supported normalizer
- call normalization
- if the result is not an empty iterable recursively call normalize again with the array

If I have a custom normalizer, it usually looks like this:

https://symfony.com/doc/current/serializer/custom_normalizer.html#creating-a-new-normalizer

```php
// src/Serializer/TopicNormalizer.php
namespace App\Serializer;

use App\Entity\Topic;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

class TopicNormalizer implements NormalizerInterface
{
    private $router;
    private $normalizer;

    public function __construct(UrlGeneratorInterface $router, ObjectNormalizer $normalizer)
    {
        $this->router = $router;
        $this->normalizer = $normalizer;
    }

    public function normalize($topic, string $format = null, array $context = [])
    {
        $data = $this->normalizer->normalize($topic, $format, $context);

        // Here, add, edit, or delete some data:
        $data['href']['self'] = $this->router->generate('topic_show', [
            'id' => $topic->getId(),
        ], UrlGeneratorInterface::ABSOLUTE_URL);

        return $data;
    }

    public function supportsNormalization($data, string $format = null, array $context = [])
    {
        return $data instanceof Topic;
    }
}
```
The custom normalizer calls an inner normalizer to be able to use ObjectNormalizer and returns an array.

Because the return value is an array the Serializer will [iterate on it](https://github.com/symfony/symfony/blob/0383b067e947efb3570b2fda8259e582ef3d8f2d/src/Symfony/Component/Serializer/Serializer.php#L170), but at this point we already done that when we called 
`$data = $this->normalizer->normalize($topic, $format, $context);` in our custom normalizer.

Maybe we could improve performance if we could skip the iteration and return the array as is. Like adding a value to the context which the serializer could check.

What do you think? Am I missing something?

**Comment by 1ed** [comment]
I did a quick test

Before
![image](https://user-images.githubusercontent.com/162986/216302273-d7cf92a5-92f5-44ca-831f-0c01f08ea355.png)

After
![image](https://user-images.githubusercontent.com/162986/216302205-168eb3ea-cde5-4885-ba4b-ab9a11ba5534.png)

And the end result is the same.

**Comment by Jeroeny** [comment]
I can't quite see how the normalizer iterates on the result of your custom normalizer, shouldn't it return here? https://github.com/symfony/symfony/blob/0383b067e947efb3570b2fda8259e582ef3d8f2d/src/Symfony/Component/Serializer/Serializer.php#L152

**Comment by 1ed** [comment]
It can be recursive, as the serializer itself is a normalizer too and the default normalizer is the serializer. But maybe that's not enough, I need to check it again.

**Comment by 1ed** [comment]
You are right, the code actually returns before reaches the iteration, or some fields will be missing from the result, so this is useless. Thanks for the clarification, I totally missed the return part!

**Comment by Jeroeny** [comment]
Feel free to checkout this serializer performance related PR as well; https://github.com/symfony/symfony/pull/45779
