### ISSUE TITLE
[Router] Can't put a default Enum value in a controller action

### ISSUE THREAD

**Issue by florentdestremau** [symfony/symfony#49203]
### Symfony version(s) affected

6.2, possibly 6.1

### Description

When defining routes with enums, the only way to make a default parameter work is by defining it in the `#[Route]` attribute. You can't define it in PHP:

```php
#[Route('/nullable/{postEnum}')]
public function enumRouteNullable(?PostEnum $postEnum = null): Response
{
    // works without parameter, but no default value
    return $this->render('home/enumRoute.html.twig', ['enum' => $postEnum]);
}

#[Route('/default/{postEnum}')]
public function enumRouteDefault(PostEnum $postEnum = PostEnum::VLOG): Response
{
    // doesn't compile, `Symfony\Component\Routing\Route cannot contain objects.`
    return $this->render('home/enumRoute.html.twig', ['enum' => $postEnum]);
}

#[Route('/default/{postEnum}', defaults: ['postEnum' => PostEnum::VLOG->value])]
public function enumRouteDefaultString(PostEnum $postEnum): Response
{
    // works, with proper default value
    return $this->render('home/enumRoute.html.twig', ['enum' => $postEnum]);
}
```

The second solution is the most convenient one, but is not allowed, I get this error: `Symfony\Component\Routing\Route cannot contain objects.` (screenshot below)

### How to reproduce

I made a test project that crashes accordingly. One controller with the use case, and another controller checking that it's valid with a pure string parameter.

https://github.com/florentdestremau/enum-router-bug

### Possible Solution

It goes back to the fact that Backed Enum classes have no __toString() method and this makes the router compiling crash. There is some treatment for route generation that should detect enums and call the `->value` method.

### Additional Context

![image](https://user-images.githubusercontent.com/2852204/216381449-0ff58421-993a-4b4f-b998-22d07bc3e63f.png)

**Comment by stof** [comment]
Parameters passed to the url generator must be stringable, and that's true also for the defaults to be able to decide whether a parameter passed explicitly matches the default or no (to decide to omit it from the generated URL).
As enums cannot be stringable in PHP, allowing to pass them as defaults would break other things (and this default would not be consistent with the value of the request attribute which would be there when matching a non-default value, which will be a string). The default has to stay the backing value.

However, the second syntax could become possible if we improve the way the AnnotationLoader guesses the routing default based on the controller argument default value. When the PHP default value is a BackedEnum, the routing default should be the backing value.

Do you want to submit a PR to implement that new feature in 6.3 ?

**Comment by florentdestremau** [comment]
I'd like to try yes. My conclusion is the same as yours. I understand the `#Route` attribute needs strings only, but I'm going to try and find a way to ensure the php default is accepted.

**Comment by stof** [comment]
the code to update is here: https://github.com/symfony/symfony/blob/0383b067e947efb3570b2fda8259e582ef3d8f2d/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L208

**Comment by florentdestremau** [comment]
Oh i made the update further out in the code.

**Comment by florentdestremau** [comment]
I updated my PR to locate the condition where you pointed

**Comment by florentdestremau** [comment]
If this solution works I can set up some tests
