### ISSUE TITLE
ConstraintValidatorTestCase and PHPUnit 10

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony#49218]
### Symfony version(s) affected

all

### Description

When validating custom Constraints `Symfony\Component\Validator\Test\ConstraintValidatorTestCase` is used. 

During setup ConstraintValidatorTestCase is setting context by calling `MockBuilder::setMethods()` that was removed in PHPUnit 10 (see https://github.com/sebastianbergmann/phpunit/issues/3769 ).

### How to reproduce

Install PHPUnit 10 and write a custom validator test as explained in the [documentation](https://symfony.com/doc/current/validation/custom_constraint.html#testing-custom-constraints).

### Possible Solution

Check version of PHPUnit being used and replace a call to `MockBuilder::setMethods()` with `MockBuilder::onlyMethods()` if PHPUnit >= 10.0 is detected.

**Comment by derrabus** [comment]
PR welcome to fix that on the 5.4 branch. We cannot use PHPUnit 10 in our CI just yet, but all the methods you need should exist on PHPUnit 9.6 already.
