### ISSUE TITLE
PHP8.2 str_split function returns empty arrays for empty strings 

### ISSUE THREAD

**Issue by HuongNV13** [symfony/symfony#49213]
### Symfony version(s) affected

6.2.6

### Description

In PHP 8.2, the str_split function will returns empty arrays for empty strings.
See: https://php.watch/versions/8.2/str_split-empty-string-empty-array

### How to reproduce

No steps to replicate

### Possible Solution

We can use mb_str_split() instead

**Comment by derrabus** [comment]
The behavior of that function has changed all right: https://3v4l.org/mHMvb

But this alone is not an issue for Symfony. Do you encounter an actual problem using a Symfony component that is impacted by this change?

**Comment by xabbuh** [comment]
and here is the actual difference (the one I am talking about at https://github.com/symfony/symfony/pull/49212#issuecomment-1415444966) to be seen when switching to `mb_str_split()`: https://3v4l.org/S4vhW

**Comment by stof** [comment]
To me, it is a bad news that php.watch decided to showcase `mb_str_split` as the migration path for this PHP 8.2 behavior change. `mb_strsplit` is not a drop-in replacement for `str_split`. Their recommendation actually changes the behavior of the code.

And for most projects, the actual migration behavior will likely be to use the new behavior as it is a better one.

**Comment by derrabus** [comment]
> Do you encounter an actual problem using a Symfony component that is impacted by this change?

@HuongNV13 Can you please answer this question? Otherwise I'd assume that there's nothing to do for us here.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
