### ISSUE TITLE
phpunit-bridge - compatibility with phpunit 10.0.2

### ISSUE THREAD

**Issue by mazarini** [symfony/symfony#49237]
### Symfony version(s) affected

6.2.5

### Description

Message : PHP Fatal error:  Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /home/mazarini/Workspace/site/site/mazarini/tools-bundle/bin/phpunit:11

### How to reproduce

symfony new xxx
cd xxx
composer req phpunit --dev
bin/phpunit
=> KO

### Possible Solution

Change "phpunit/phpunit": "^10.0" to "phpunit/phpunit": "^9.5"
composer update
bin/phpunit
=> OK
Add conflict with 10.0

**Comment by xabbuh** [comment]
Thanks for reporting. I am going to close here nonetheless as we already have #49069 to keep track of this.
