### ISSUE TITLE
[EmailValidator] Unresolvable Deprecation

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#49258]
### Symfony version(s) affected

6.2.6

### Description

Using Symfony 6.2, I always get deprecation errors that seems not resolvable because of the check in __construct of ``EmailValidator``. When a Email constraint is created with a specific mode, it's taken in the validate method of EmailValidator, not in the constructor. Then in my mind the deprecation should be moved in validate method.

Related commit: https://github.com/symfony/symfony/pull/46518

```
Other deprecation notices (3)

  3x: Since symfony/validator 6.2: The "loose" mode is deprecated. The default mode will be changed to "html5" in 7.0.
    3x in MailSenderControllerTest::testSendMailAction from PTC\AdminBundle\Tests\Controller
```

### How to reproduce

Create a form using ``Email::VALIDATION_MODE_HTML5``:

```php
$form = $this->createFormBuilder($defaultData)
        ->add('email', EmailType::class, array(
            'label' => 'email',
            'constraints' => array(
                new NotBlank(), 
                new Email(['mode' => Email::VALIDATION_MODE_HTML5])
            ),
            'attr' => array('maxlength' => '255'),
        ))
        ->getForm();
```

In the profiler I can see that the ``Email`` constraint is created with right ``mode`` but the related ``EmailValidator`` is not.

![image](https://user-images.githubusercontent.com/652505/216948206-ebf05232-2d4a-4bbe-9372-893a9a7fd926.png)

### Possible Solution

Move the deprecation from ``__construct`` to ``validate`` method.

**Comment by chalasr** [comment]
Would you mind sending a PR (with test case)?

**Comment by dmaicher** [comment]
Isn't the "right" fix to get rid of the deprecation to change the default using the `framework.validation.email_validation_mode` config?

See https://symfony.com/doc/current/reference/configuration/framework.html#email-validation-mode

**Comment by stof** [comment]
the FrameworkBundle configuration has a configuration setting for the default mode of the EmailValidator. That's what you need to use to get rid of that deprecation.

**Comment by raziel057** [comment]
@dmaicher @stof Ok I didn't know this config. Thank you very much. 

But in any case the test for deprecation should also be done in ``validate`` method as the default mode can be overridden from the Email constraint.

**Comment by stof** [comment]
@raziel057 we already report deprecations when the constraint uses the `loose` mode.

But validating the the default mode does not use a deprecated value is intentional.

**Comment by raziel057** [comment]
Ok so I can close this one?
