### ISSUE TITLE
warning message on failed messenger show command

### ISSUE THREAD

**Issue by gstapinato** [symfony/symfony#49262]
### Symfony version(s) affected

5.4 - 6.3

### Description

Show warning message 'Undefined array key "headers"' when I'm trying to execute a command to show messages from the failure transport.
This error only can be reproduced from Doctrine transport using oracle database.

The reason for this exception is because most Oracle databases use UPPER CASE on tables and column identifiers. 

### How to reproduce

	Small example application that allows to reproduce this issue: https://github.com/gstapinato/symfony_messenger_oracle
	
	Command: bin/console messenger:failed:show

	$ bin/console messenger:failed:show
	There are xx messages pending in the failure transport.
	
	Exception message:  Undefined array key \"headers\" 
	
	/srv/app/vendor/symfony/doctrine-messenger/Transport/Connection.php:458
	/srv/app/vendor/symfony/doctrine-messenger/Transport/Connection.php:309
	/srv/app/vendor/symfony/doctrine-messenger/Transport/Connection.php:308
	/srv/app/vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php:113
	/srv/app/vendor/symfony/messenger/Command/FailedMessagesShowCommand.php:98
	/srv/app/vendor/symfony/messenger/Command/FailedMessagesShowCommand.php:83
	/srv/app/vendor/symfony/console/Command/Command.php:298
	/srv/app/vendor/symfony/console/Command/LazyCommand.php:71
	/srv/app/vendor/symfony/console/Tester/CommandTester.php:74
	/srv/app/tests/FailureIntegrationTest.php:41
	/srv/app/tests/FailureIntegrationTest.php:24

### Possible Solution

On File: "Symfony\Component\Messenger\Bridge\Doctrine\Tests\Transport\Connection.php" 

### Additional Context

Related to: https://github.com/symfony/symfony/issues/44988

**Comment by alamirault** [comment]
Thanks for your great reproducer.

In get method is ok

https://github.com/symfony/symfony/blob/aee6adfb2d743afedc29e8eaaf732dc14284aedf/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L210

```
^ array:7 [
  "id" => "24"
  "body" => "O:36:\"Symfony\\Component\\Messenger\\Envelope\":2:{s:44:\"\0Symfony\\Component\\Messenger\\Envelope\0stamps\";a:1:{s:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\";a:1:{i:0;O:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\":1:{s:55:\"\0Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\0busName\";s:21:\"messenger.bus.default\";}}}s:45:\"\0Symfony\\Component\\Messenger\\Envelope\0message\";O:22:\"App\\Message\\AppMessage\":0:{}}"
  "headers" => []
  "queue_name" => "async"
  "created_at" => "2023-02-07 20:09:03"
  "available_at" => "2023-02-07 20:09:03"
  "delivered_at" => null
]
```

However in findAll, keys are uppercases

https://github.com/symfony/symfony/blob/aee6adfb2d743afedc29e8eaaf732dc14284aedf/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L306

```
^ array:1 [
  0 => array:7 [
    "ID" => "25"
    "BODY" => """
      REMOVED
      """
    "HEADERS" => "[]"
    "QUEUE_NAME" => "failed"
    "CREATED_AT" => "2023-02-07 20:09:03"
    "AVAILABLE_AT" => "2023-02-07 20:09:03"
    "DELIVERED_AT" => null
  ]
]
```

I don't know how to fix it, but community will know

**Comment by gstapinato** [comment]
I'm going to create a PR to fix this bug

**Comment by gstapinato** [comment]
Thanks @alamirault for adding this relevant information.
I've created a PR based on this issue.
