### ISSUE TITLE
Symfony String Component require intl extension

### ISSUE THREAD

**Issue by Ferror** [symfony/symfony#49280]
### Symfony version(s) affected

6.2.5

### Description

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/String/AbstractUnicodeString.php#L31-L34

Hi! The String Component uses the Normalizer class (https://www.php.net/manual/en/class.normalizer.php) which is part of the intl extension, when I tried to use a library that has a dependency on Symfony String I had to install the intl because the "Normalizer" class was missing.

### How to reproduce

The Normalizer usage: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/String/AbstractUnicodeString.php#L31-L34

The Dependencies: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/String/composer.json

### Possible Solution

Adding to the String Component requirement for `ext-intl` extension

**Comment by nicolas-grekas** [comment]
ext-intl is not required: you can use [symfony/polyfill-intl-normalizer](https://packagist.org/packages/symfony/polyfill-intl-normalizer) instead.
That's why it's not in the composer.json
