### ISSUE TITLE
Random E_COMPILE_ERROR error when Symfony preload is enabled

### ISSUE THREAD

**Issue by B-Galati** [symfony/symfony#49296]
### Symfony version(s) affected

At least >=5.4.*

### Description

Hello,

I am getting some random errors with Symfony when the preload config is enabled.

Here is the stack trace.
```
E_COMPILE_ERROR: Cannot redeclare composerRequireDontChange() (previously declared in /opt/project/vendor/composer/autoload_real.php:51)
#0 /opt/project/vendor/autoload_runtime.php(5): require_once()
#1 /opt/project/public/index.php(5): require_once()
#2 {main}
```

FYI, the application is built this way in a docker image to optimize the build time:

```dockerfile
COPY ./composer.* ./symfony.lock ${PROJECT_ROOT}/
RUN \
    composer validate && \
    composer check-platform-reqs && \
    # No autoloader: it must be generated after copying sources to allow the autoloader to find existing classes.
    # No plugins : they are no needed to install dependencies.
    # No scripts : they must be run after copying sources to allow them to behave correctly.
    composer install --no-cache --no-autoloader --prefer-dist --no-interaction --no-scripts --no-plugins --no-dev

COPY ./public ${PROJECT_ROOT}/public
COPY ./bin ${PROJECT_ROOT}/bin
COPY ./assets ${PROJECT_ROOT}/assets
COPY ./templates ${PROJECT_ROOT}/templates
COPY ./translations ${PROJECT_ROOT}/translations
COPY ./migrations ${PROJECT_ROOT}/migrations
COPY ./config ${PROJECT_ROOT}/config
COPY ./src ${PROJECT_ROOT}/src

RUN \
    composer dump-autoload --optimize --classmap-authoritative && \
    \
    bin/console -v -n assets:install public/ && \
    bin/console -v -n lint:xliff translations && \
    \
    rm -rf ${PROJECT_ROOT}/var && \
    bin/console -v -n cache:warmup && \
    rm -rf ${PROJECT_ROOT}/var/log && \
    \
    # Clean-up environment variables to have something strict \
    rm ${PROJECT_ROOT}/.env && \
    echo '<?php return [];' > ${PROJECT_ROOT}/.env.local.php
```

### How to reproduce

I don't know how to reproduce, I am really sorry about that.

It looks totally random but I may be wrong of course.

Here is the number of occurrences I get recently:

![image](https://user-images.githubusercontent.com/895123/217559376-2d473b44-dc62-4471-994f-89ad6c0f4b50.png)

**Comment by B-Galati** [comment]
I edited the description with the application build process

**Comment by MatTheCat** [comment]
I guess you used `autoloader-suffix` in your composer.json because of https://github.com/composer/composer/issues/3701?

https://github.com/composer/composer/issues/3701#issuecomment-76188090 suggest you should remove it when using opcache.

Also you should not be able to run two versions of your production code; that may be the real issue here.

**Comment by B-Galati** [comment]
Thanks @MatTheCat, you nailed it! 

I will try that out :+1: as I don't need the suffix anymore.

What's weird is that I have only one version of my production code running so I don't really get what's the issue :see_no_evil:.

**Comment by MatTheCat** [comment]
Do you clear the opcache **before** making the new version live?

**Comment by B-Galati** [comment]
No because PHP is run within a container and upgrading the app = replacing the container with a new version.

**Comment by B-Galati** [comment]
I am still having the same issue after removing the suffix:

```
E_COMPILE_ERROR: Cannot redeclare composerRequireeea59ec2fd98d3f0d5a2cc619df0be93() (previously declared in /opt/project/vendor/composer/autoload_real.php:51)
#0 /opt/project/vendor/autoload_runtime.php(5): require_once()
#1 /opt/project/public/index.php(5): require_once()
#2 {main}
```

Any idea?

**Comment by B-Galati** [comment]
Here are the changes to try to fix the issue.

```diff
--- a/composer.json
+++ b/composer.json
@@ -103,7 +103,6 @@
             "*": "dist"
         },
         "sort-packages": true,
-        "autoloader-suffix": "DontChange",
         "allow-plugins": {
             "composer/package-versions-deprecated": true,
             "symfony/flex": true,

--- a/Dockerfile
+++ b/Dockerfile
@@ -62,9 +62,8 @@ RUN \
     composer validate && \
     composer check-platform-reqs && \
     # No autoloader: it must be generated after copying sources to allow the autoloader to find existing classes.
-    # No plugins : they are no needed to install dependencies.
     # No scripts : they must be run after copying sources to allow them to behave correctly.
-    composer install --no-cache --no-autoloader --prefer-dist --no-interaction --no-scripts --no-plugins --no-dev
+    composer install --no-cache --no-autoloader --prefer-dist --no-interaction --no-scripts --no-dev
```

**Comment by B-Galati** [comment]
@Seldaek Do you think that could a bug on composer side?

**Comment by Seldaek** [comment]
I don't think so.. But who knows. Seems to me more like either an opcache/preload/jit bug in php or some code path somewhere including autoload real again explicitly but that seems unlikely if it doesn't happen on every request. Random failures usually point to opcache

**Comment by B-Galati** [comment]
Thank you! I will try to investigate more then 🙏

**Comment by B-Galati** [comment]
Closing as it's not related to Symfony apparently
