### ISSUE TITLE
[Validator] Make Length() Constraint configurable which strlen()-variant its Validator uses

### ISSUE THREAD

**Issue by spackmat** [symfony/symfony#49309]
### Description

At the moment, a `Length` Validator checks the string length using `mb_strlen()`, which is fine in most cases. But in some contexts, it would be very helpful, when those Validators would be configurable in the way, how they determine the string length. The String component brought us the sweet taste of `ByteString`, `CodePointString` and `UnicodeString`, so configuring the used class for the Validator could be nice. Have a look at this code snippet to understand what I mean:

```` php
// where '🧚‍♀️' is the "Woman Fairy" Emoji
dump(mb_strlen('🧚‍♀️')); // => 4
dump((new ByteString('🧚‍♀️'))->length()); // => 13
dump((new CodePointString('🧚‍♀️'))->length()); // => 4
dump((new UnicodeString('🧚‍♀️'))->length()); // => 1
````

### Example

For example in a database context with a certain varchar length it is very important to control, how the max length of a string is determined. Or in a Twitter-like context with an arbitrarily chosen length restriction, Emojis should count as one "character" (meaning a Grapheme here) and the `Length` Validator should be able to reflect that. So wouldn't it be nice, if we could do something like this:

```` php
new \Symfony\Component\Validator\Constraints\Length(
    min: 1,
    max: 280,
    stringClass: \Symfony\Component\String\UnicodeString::class, // could be checked to be a subclass of \Symfony\Component\String\AbstractString::class 
);
````

With that the value would be checked using a length determined by `$length = (new $stringClass($value))->length();` with a default/fallback to `mb_strlen()`, when the String component is not installed.

At the moment, I use custom Validators implementing that, but that is not that fun to maintain as it sounds. I could submit a PR implementing that into the string-length-checking Constraints and Validators, if that would be appreciated. I see @webmozart as the author of the `Length` Constraint, what's your opinion on that?

**Comment by spackmat** [comment]
I saw that the `length()` methods of the different String-classes internally do no more magic than calling `\strlen()` (ByteString), `\mb_strlen()` (CodePointString) or`\grapheme_strlen()` (UnicodeString), so I built a simple implementation around this Enum:

```` php
enum LengthCountUnitEnum: string
{
    case BYTES = 'bytes';
    case CODEPOINTS = 'codepoints';
    case GRAPHEMES = 'graphemes';

    public function lengthCallable(): callable
    {
        return match($this)
        {
            self::BYTES => \strlen(...),
            self::CODEPOINTS => \mb_strlen(...),
            self::GRAPHEMES => \grapheme_strlen(...),
        };
    }
}
````

And the Length Constraints takes that LengthCountUnitEnum as a `$countUnit` parameter, defaulting to `LengthCountUnitEnum::CODEPOINTS`. With that, the `$length` determination looks like this:

```` php
if ('mb_strlen' === (new \ReflectionFunction($constraint->countUnit->lengthCallable()))->name) {
    $length = $constraint->countUnit->lengthCallable()($stringValue, $constraint->charset);
}
else {
    $length = $constraint->countUnit->lengthCallable()($stringValue);
}
````

So now, when I have a `Length()` Constraint that shall not use `mb_strlen()`, I can to that:

```` php
new Length(max: 280, countUnit: LengthCountUnitEnum::GRAPHEMES),
````

If some people are not down with Enums, I could allow to use the value-strings for configuration and the Constraint could try to cerate the Enum from the given string or throw an Exception otherwise.

Would that approach be welcomed as a PR? It has no BC break as it defaults to `LengthCountUnitEnum::CODEPOINTS` that uses `\mb_strlen()` like before.

**Comment by nicolas-grekas** [comment]
I'm not sure about the enum, but about making the unit system configurable sounds good to me, eg.:

```php
new Length(max: 280, countUnit: Length::COUNT_GRAPHEMES);
```

**Comment by spackmat** [comment]
Yes, that was my first approach on that and it fits the surrounding better as the whole Validator component seems that it hasn't adopted PHP 8.1 features yet. But maybe it could be time to start with those, even if it is a bit beneath the current way of implementation. In that case: Less string stuff, more strict typing for the cost of another `use` statement. As the `Length` Constraint is the only one with that problem, the Enum is indeed a bit complicated due to the need for another import, but when another Constraints has to deal with that differences, the Enum would be a more abstract solution. Maybe there is a need for a `strposCallable()` method in the future or for a `substrCallable()`.

In the end, a constant based implementation would also be okay for me to implement..

**Comment by nicolas-grekas** [comment]
We don't need the type safety of enums, so better keep things boring with a simple const IMHO.

**Comment by spackmat** [comment]
OK, PR without the Enum is committed.

**Comment by stof** [comment]
Thus, the XML loader for validation mapping does not support using constants (and so enums) so that would make the feature incompatible with XML mapping

**Comment by spackmat** [comment]
@stof that is a fairly good reason to stick to constants, didn't mind that.
