### ISSUE TITLE
[DependencyInjection] Attribute to define service aliases

### ISSUE THREAD

**Issue by fbourigault** [symfony/symfony#49323]
### Description

Defining services aliases is currently not possible using attributes.

This could be achieved by adding an `Alias` attribute to the DI component.

### Example

Before:
```yaml
services:
    App\Services\MyInterface: '@App\Services\MyService'
```

After:
```php
namespace App\Services;

use Symfony\Component\DependencyInjection\Attribute\Alias;

#[Alias(MyInterface::class)]
class MyService implements MyInterface
{

}
```

Is it something that could be in Symfony?

**Comment by nicolas-grekas** [comment]
Have a look at #49198
