### ISSUE TITLE
[DI] Cannot decorate lazy, final class using interface proxying

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#49333]
### Symfony version(s) affected

6.2.0

### Description

When trying, you get the following exception:

1. `Symfony\Component\DependencyInjection\Exception\InvalidArgumentException`: Cannot generate lazy proxy for service "App\Wrapper.inner".
2. `Symfony\Component\VarExporter\Exception\LogicException`: Cannot generate lazy proxy: class "App\Implementation" is final.

### How to reproduce

Reproducer: https://github.com/kbond/symfony-reproducer/tree/decorated-lazy-service

```php
interface Contract
{
}

#[Autoconfigure(lazy: Contract::class)]
final class Implementation implements Contract
{
}

#[AsDecorator(decorates: Implementation::class)]
final class Wrapper implements Contract
{
    public function __construct(private Contract $inner)
    {
    }
}
```

Then inject `Implementation` somewhere.

### Possible Solution

Removing `final` from the decorated class (`Implementation` above) solves the issue but this is not ideal.

**Comment by nicolas-grekas** [comment]
src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:            : ['container.do_not_inline', 'container.service_locator', 'container.service_subscriber', 'container.service_subscriber.locator'];

this should contain "lazy" I guess
up for a pr?

**Comment by kbond** [comment]
That looks to fix the problem! (adding `proxy`). I'll create a PR.
