### ISSUE TITLE
[DoctrineBridge] `UniqueEntityValidator` ignores Option `entityClass`

### ISSUE THREAD

**Issue by wiseguy1394** [symfony/symfony#49357]
### Symfony version(s) affected

6.2.6

### Description

I have the following entities:

```php

#[ORM\Entity(repositoryClass: EntityARepository::class)]
class EntityA {

  #[ORM\Id]
  #[ORM\Column(type: 'integer')]
  #[ORM\GeneratedValue(strategy: 'AUTO')]
  public int $id;

  #[ORM\ManyToOne(targetEntity: EntityB::class)]
  #[ORM\JoinColumn(name: 'entity_b_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
  private ?EntityB $entityB = null;

  #[ORM\OneToMany(mappedBy: 'entityA', targetEntity: EntityC::class, fetch: 'EXTRA_LAZY')]
  private Collection $entityC;
  /* ... */
}

#[ORM\Entity(repositoryClass: EntityBRepository::class)]
#[UniqueEntity('key', entityClass: EntityB::class)]
class EntityB {

  #[ORM\Id]
  #[ORM\Column(type: 'integer')]
  #[ORM\GeneratedValue(strategy: 'AUTO')]
  public int $id;

  #[ORM\Column(type: 'string', length: 10, unique: true, nullable: false)]
  private string $key;
  /* ... */
}

#[ORM\Entity(repositoryClass: EntityCRepository::class)]
class EntityC {

  #[ORM\Id]
  #[ORM\Column(type: 'integer')]
  #[ORM\GeneratedValue(strategy: 'AUTO')]
  public int $id;

  #[ORM\ManyToOne(targetEntity: EntityA::class, inversedBy: 'entityC')]
  #[ORM\JoinColumn(name: 'entity_a_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private EntityA $entityA;
  /* ... */
}

```

When I now try to update EntityC with a form we get the following error:
`Unable to find the object manager associated with an entity of class "Proxies\__CG__\App\Entity\EntityB".`

I would expect that the option **entityClass** of **UniqueEntity** Attribute prevent this error. https://symfony.com/doc/current/reference/constraints/UniqueEntity.html#entityclass

### How to reproduce

Detailed description above.

### Possible Solution

https://github.com/symfony/doctrine-bridge/blob/6.2/Validator/Constraints/UniqueEntityValidator.php#L78

If I change this line
`$em = $this->registry->getManagerForClass($entity::class);`
to
`$em = $this->registry->getManagerForClass($constraint->entityClass ?? $entity::class);`

Everything works as expected.

Do I understand the option right or is there another way to prevent this error? I don't want to change the fetch type.

**Comment by wiseguy1394** [comment]
@beberlei I saw your email in copyright. Can you have a look?

**Comment by xabbuh** [comment]
From my understanding after reading the code of the `ManagerRegistry` class I would have guessed that the registry should be able to handle proxy classes (see https://github.com/doctrine/persistence/blob/3.1.x/src/Persistence/AbstractManagerRegistry.php#L169-L195).

Can you please try to debug why that logic is not working in your case?

**Comment by wiseguy1394** [comment]
3 days ago I debugged it a hundred times. Today there error is gone and everything works fine.
I can't reproduce it anymore.
Sorry for any inconvenience...

**Comment by xabbuh** [comment]
Thanks for coming back and closing. :) We can reopen nevertheless when the error occurs again and we have more insights what's going on.
