### ISSUE TITLE
[Validator] Add an option to set a filename length limit 

### ISSUE THREAD

**Issue by ke20** [symfony/symfony#49359]
### Description

On this owasp [page](https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html) we can see `Set a filename length limit. Restrict the allowed characters if possible`.

I could be interesting to add an option in the [File Constraint](https://symfony.com/doc/current/reference/constraints/File.html) to check that ?

If yes, I can create a MR for that.

### Example

For example we can have : 
```php
// src/Entity/Author.php
namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class Author
{
    #[Assert\File(
        maxSize: '1024k',
        filenameMaxLength: 50,
        filenameMaxLengthMessage: 'The filename is too long. It should have 50 character or less.'
    )]
    protected $bioFile;
}
```

**Comment by Arman-Hosseini** [comment]
It makes sense to me.

**Comment by maciekpaprocki** [comment]
I can do that. 

#### edit

As in I can send PR for that :)
