### ISSUE TITLE
[Serializer][Profiler] InvalidArgumentException | APP_ENV=dev + autowire

### ISSUE THREAD

**Issue by eatae** [symfony/symfony#49352]
### Symfony version(s) affected

6.2

### Description

**Serializer v6.2.5**

When configuring **autowiring** - **Symfony\Component\Serializer\Serializer**, an **InvalidArgumentException** occurs only if you run the application in the **DEV** environment

**Exception messages:**
The controller for URI "/api/programmers" is not callable: The class "Symfony\Component\Serializer\Debug\TraceableEncoder" neither implements "Symfony\Component\Serializer\Normalizer\NormalizerInterface" nor "Symfony\Component\Serializer\Normalizer\DenormalizerInterface".

...

The class "Symfony\Component\Serializer\Debug\TraceableEncoder" neither implements "Symfony\Component\Serializer\Normalizer\NormalizerInterface" nor "Symfony\Component\Serializer\Normalizer\DenormalizerInterface".

### How to reproduce

**_services.yaml_**
>
>     app.encoder.json:
>         class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'
> 
>     # Serializer
>     app.serializer.json:
>         class: 'Symfony\Component\Serializer\Serializer'
>         arguments:
>             0:
>                 - '@serializer.normalizer.object'
>             1:
>                 - '@app.encoder.json'

**_ProgrammersController_**

```
public function createAction(
        SerializerInterface     $serializer,
        Request                 $request
): JsonResponse {
        dd($request);
}

```

### Possible Solution

Perhaps the solution is similar to this:

https://github.com/web-token/jwt-framework/issues/349

### Additional Context

**Debugger output (change extension to .html):**
[e.txt](https://github.com/symfony/symfony/files/10721471/e.txt)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by eatae** [comment]
I figured out what is throwing the Profiler-pack Exception
### **How to play:**
  **1. Create new Symfony Project** <br>
  **2. Install Serializer**  
     `composer require symfony/serializer`

  **3. Install PropertyAccess Component**
     `composer require symfony/property-access`

   **4. add to services.yaml**

```
app.encoder.json:
    class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

# Serializer
    app.serializer.json:
        class: 'Symfony\Component\Serializer\Serializer'
	arguments:
	    0:
	        - '@serializer.normalizer.object'
	    1:
	        - '@app.encoder.json'
```

   **5. Create SomeController**

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Routing\Annotation\Route;

class SomeController extends AbstractController
{
    #[Route('/show')]
    public function showAction(
        SerializerInterface     $serializer,
        Request                 $request
    ): Response {
        dd($request);
    }
}
```

  **6. Call the action controller**
`localhost/show`

!!! There are no exception!

  **7.Install Profiler**
    `composer require --dev symfony/profiler-pack`


  **8. Call the action controller**
`localhost/show`

!!! There is an exception!



### **Here is the finished assembly in the container:**

`git clone git@github.com:eatae/issue-49352.git ./issue`
`cd ./issue/docker`
`docker-compose up --build -d`
`docker exec -it issue-cli composer install`

Open in Browser:
`http://issue.localhost/show`

**Comment by mtarld** [comment]
Hi @eatae, I cannot reproduce the bug on a fresh 6.3 install:
```
bin/console deb:cont app.serializer.json --show-arguments

Information for Service "app.serializer.json"
=============================================

 Serializer serializes and deserializes data.

 ---------------- -------------------------------------------------- 
  Option           Value                                             
 ---------------- -------------------------------------------------- 
  Service ID       app.serializer.json                               
  Class            Symfony\Component\Serializer\Serializer           
  Tags             serializer.normalizer                             
                   serializer.encoder                                
  Public           no                                                
  Synthetic        no                                                
  Lazy             no                                                
  Shared           yes                                               
  Abstract         no                                                
  Autowired        yes                                               
  Autoconfigured   yes                                               
  Arguments        Array (1 element(s))                              
                   Array (1 element(s))                              
  Usages           .29_TraceableEncoder~fVwsoe1                      
                   .15_TraceableNormalizer~fVwsoe1                   
                   .debug.serializer.normalizer.app.serializer.json  
                   .debug.serializer.encoder.app.serializer.json     
 ---------------- --------------------------------------------------
```

Do you still have the issue?

**Comment by eatae** [comment]
Hi, Mathias

Thank you for your attention to this issue.
If it is not reproduced in the new version, then you can close it.

Sincerely, eatae
