### ISSUE TITLE
Sendinblue Transport should allow null subject

### ISSUE THREAD

**Issue by chriswait** [symfony/symfony#49365]
### Description

**My Setup**
I'm using Laravel Mailables to send Sendinblue transactional emails with templates using `symfony/sendinblue-mailer` (so apologies if this issue isn't suitable for this repo!)

In the `__construct` method of my Mailable class I call `$this->withSymfonyMessage()` to set up my email:
```
class MyEmail extends Mailable
{
  public function __construct()
  {
    $this->withSymfonyMessage(function (Email $message) {
      $message->getHeaders()
        ->addHeader('templateId', MY_TEMPLATE_ID)
        ->addParameterizedHeader('params', 'params', ['exampleparam' => 'examplevalue']);
    });
  }
}
```

**The Problem:**
This makes Sendinblue send emails with subject "My Email" (because if `$message->subject` is falsy, Mailable falls back to calling `$message->subject()` with a string based on the Mailable class name - [src](https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/Mailable.php#L418)).

Instead, I want to use Sendinblue template's default subject, which requires passing a `null` subject to their API (documented here in sendinblue [docs](https://developers.sendinblue.com/reference/sendtransacemail#:~:text=text.domain.com-,subject,-string), implemented [here](https://github.com/agence-webup/laravel-sendinblue/blob/master/src/SendinBlueTransport.php#L169) in the agence-webup/laravel-sendinblue package)

However, if I call `$message->subject(null)` I get the error:
`Symfony\Component\Mime\Email::subject(): Argument #1 ($subject) must be of type string, null given, called in ...MyEmail.php on line [whatever]`.

**Possible Solution**
Assuming subject shouldn't be null seems sensible - Sendinblue transactional templates with subjects are probably an edge case.

Perhaps laravel-sendinblue's solution of having a special string which sets the subject to null just before the API call seems least disruptive?

### Example

`$message->subject(SendinBlueApiTransport::USE_TEMPLATE_SUBJECT)` results in a null subject being sent to the Sendinblue API, allowing each template's subject line to be managed within Sendinblue.

Happy to have a go at putting together a PR if you like.

**Comment by MatTheCat** [comment]
> Assuming subject shouldn't be null seems sensible

This is not the case: in your example you did not call `subject` so the subject is indeed `null`. This matches the getter’s signature: https://github.com/symfony/symfony/blob/e16aea4e88bfecec4986bf7a693f84a86c074109/src/Symfony/Component/Mime/Email.php#L66

The only issue seems to be the `Mailable` class forcing one.

**Comment by chriswait** [comment]
Ah sorry, I left my call to `->subject()` this out of my example! But you are totally right: when I override Mailable's `buildSubject()` to do nothing, subject is indeed null and the sendinblue API behaves as expected. Thanks!
