### ISSUE TITLE
[RFC] Deprecate most of or all annotations?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#49369]
### Description

There is ongoing work about deprecating the usage of annotations:

- #49358
- #48990 

I didn't see a general discussion about this subject, so I created this issue to raise the question:

Should some or all annotations be deprecated in 6.3 and removed in 7.0?

Attributes are natively supported with Symfony 6.3+, because it requires PHP ≥ 8.1 and attributes were added in PHP 8.0. While annotations require to install `doctrine/annotations`.

On a side note, PHPUnit 10 allow to use attributes instead of annotations: https://github.com/sebastianbergmann/phpunit/issues/4502

### Example

```diff
-    /**
-     * @required
-     */
+    #[\Symfony\Contracts\Service\Attribute\Required]
     public function setFoo(Foo $foo)
     {
         // should be called
     }
```

**Comment by derrabus** [comment]
Yes. Let's kill Doctrine Annotations.

**Comment by stof** [comment]
Knowing that the Rector implementation of migrating annotations to attributes is currently broken (because their parsing of Doctrine annotations is broken, ignoring the fact that string literals are a thing in annotations and quotes are not just a parenthesis-like delimiter), there is no easy *working* migration path for now.

**Comment by yguedidi** [comment]
@stof there is a work in progress to fix that: https://github.com/rectorphp/rector-src/pull/3645

**Comment by derrabus** [comment]
Fixed by:

* #50888
* #49358
* #50982
* #50983
* #51050
* #51082
* #51085
* #51080

**Comment by alexisLefebvre** [comment]
@derrabus Thanks for the update! Is there still some annotations that are not (yet) deprecated?

**Comment by derrabus** [comment]
No, it's done.
