### ISSUE TITLE
[FrameworkBundle] PHP Kernel preload contains Twig templates

### ISSUE THREAD

**Issue by ymorocutti** [symfony/symfony#49360]
### Symfony version(s) affected

6.0

### Description

Hello,

Since Symfony 4.4, a new file named var/cache/prod/App_KernelProdContainer.preload.php allow us to preload classes into OPCache to improve performances.

But I have an issue with it and I'm not sure if this file is correctly created.
From what I've seen, this file includes bundles classes and then container services tagged with container.preload while removing services tagged with container.no_preload.

Basically, this stuff works fine and doesn't load a lot of classes, just what's needed.

But while running a cache:warmup command, I'm ending up having all twig templates loaded in this file as well, and I'm not sure if it's "normal". The thing I'm sure on the other hand is that when I start my fpm php process with opcache enabled, it just crash from a memory limit cause... Well, all twig templates are loaded in it and it's too much.

In the warmup command, there is the following code.
```
if (!$input->getOption('no-optional-warmers')) {
    $this->cacheWarmer->enableOptionalWarmers();
}

$preload = $this->cacheWarmer->warmUp($cacheDir = $kernel->getContainer()->getParameter('kernel.cache_dir'));

if ($preload && file_exists($preloadFile = $cacheDir.'/'.$kernel->getContainer()->getParameter('kernel.container_class').'.preload.php')) {
    Preloader::append($preloadFile, $preload);
}
```

From what I understand, when I'm warming up cache, every files generated are append to the OPCache file.
Since Twig is optional, I've used the command with the parameter no-optional-warmers which works fine for my preload file, it's better, but Twig files are not warmed up and I'm losing some performance on runtime.

### How to reproduce

To reproduce, you need to activate twig cache and use `bin/console c:w`
Once the command is done, you should have some twig templates in your preload file.

### Possible Solution

Best thing would be to have a tag could be added to the CacheWarmerInterface that would tell if files that you're generating can be added safely to the OPCache file.

The "simple" fix would be to remove optional warmer from the OPCache file and just keep what's necessary.

**Comment by stof** [comment]
This is expected. The Twig cache warmer returns the list of template classes to be added in the preloading so that compiled Twig templates are preloaded as well, making things faster.

**Comment by nicolas-grekas** [comment]
We could remove compiled twig files from the returned array. Since preloading doesn't benefit rarely used files, it might not have much impact if any.

**Comment by ymorocutti** [comment]
Preloading files is nice if mostly used. Tbh, I don't know how many twig templates are used on runtime, but I'm sure it's not 100% and I'm pretty sure it's far from that. Right now, we're loading a lot of classes in memory, while we know they are mostly not used in a single hit.

**Comment by nicolas-grekas** [comment]
Up for a PR @ymorocutti ?

**Comment by ymorocutti** [comment]
@nicolas-grekas Yeah, I'll do one tomorrow based on your answer, which is just removing twig files from preload. It that solution acceptable for you ?

**Comment by nicolas-grekas** [comment]
I think so yes, let's see on the PR. Thanks.
