### ISSUE TITLE
[DependencyInjection] Autowire attribute does not work for nullable parameters

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#49370]
### Symfony version(s) affected

6.2.6

### Description

If I try to autowire a parameter value into a service using the `#[Autowire]` attribute, autowiring fails if that parameter is `null`. The exception tells me to configure that constructor parameter explicitly. Changing the parameter to a value other than `null` makes the exception disappear.

### How to reproduce

```yaml
# services.yaml

parameters:
    my_parameter: null
```

```php
final class MyService
{
    public function __construct(
        #[Autowire('%my_parameter%')]
        private ?string $myParameter,
    ) {
    }
}
```

**Comment by nicolas-grekas** [comment]
Can you try using the empty string instead?

**Comment by alamirault** [comment]
I reproduced the bug and propose a patch https://github.com/symfony/symfony/pull/49379

**Comment by derrabus** [comment]
> Can you try using the empty string instead?

That certainly works, but I want `null` and not the empty string. 😤
