### ISSUE TITLE
[MonologBridge] FirePHPHandler::onKernelResponse throws PHP 8.1 deprecation when no user agent is set

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#49392]
### Symfony version(s) affected

5.4.20 and above

### Description

When no user agent is set `FirePHPHandler::onKernelResponse` throws 

`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`

in PHP 8.1 and above

https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/Monolog/Handler/FirePHPHandler.php#L44

### How to reproduce

I have no reproducer but it is an obvious potential problem because `HeaderBag::get` is allowed to return null.

**Comment by stof** [comment]
The condition should be updated to handle the case of not having a user agent. Do you want to send a PR ?

**Comment by simonberger** [comment]
No, anyone can pick up. This is an easy first PR.
