### ISSUE TITLE
Translation - Cannot extract some constraint attribute messages

### ISSUE THREAD

**Issue by nfragnet** [symfony/symfony#49397]
### Symfony version(s) affected

6.2.6

### Description

Hi,

When running `bin/console translation:extract --domain=validators en` on my local env most of the messages stored in constraints attributes are not extracted.

Some exceptions remains for `Assert/Email` or `Assert/Expression` for example.
Those ones are extracted. On the other hand a simple `GreaterThan` or `Length` with `message`, or `minMessage`/`maxMessage` option are not.

### How to reproduce

```php
#[Assert\Length(
    min: 1,
    max: 25,
    minMessage: 'transkey_min', // Those two are not extracted
    maxMessage: 'transkey_max', //
)]
#[Assert\Expression(
    expression: '1 === 1', 
    message: 'transkey_expression', // This one is extracted
)]
private string $foo;
```

Then run `bin/console translation:extract --domain=validators en` .
- `transkey_expression` is extracted
- `transkey_min` & `transkey_max` are not

### Additional Context

Expected behaviour => https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically

> The translation:extract command looks for missing translations in:
> - ...
> - Any PHP file/class stored in the src/ directory that uses [Constraints Attributes](https://symfony.com/doc/current/validation.html#validation-constraints) with *message named argument(s).

I checked the class `Symfony\Component\Translation\DependencyInjection\TranslatorPass` and noticed the way constraint class names are injected into ConstraintVisitor service.

```php
$constraintVisitorDefinition = $container->getDefinition('translation.extractor.visitor.constraint');
$constraintClassNames = [];

foreach ($container->findTaggedServiceIds('validator.constraint_validator', true) as $id => $attributes) {
    $serviceDefinition = $container->getDefinition($id);
    // Resolve constraint validator FQCN even if defined as %foo.validator.class% parameter
    $className = $container->getParameterBag()->resolveValue($serviceDefinition->getClass());
    // Extraction of the constraint class name from the Constraint Validator FQCN
    $constraintClassNames[] = str_replace('Validator', '', substr(strrchr($className, '\\'), 1));
}

$constraintVisitorDefinition->setArgument(0, $constraintClassNames);
```

By reading this I expect all symfony validator constraints to be in the `$constraintClassNames` but it's not the case. Only those EXPLICITLY tagged (and not the autoconfigured one) are present.

By adding manually and additional entry in `$constraintClassNames` array, I've been able to extract messages from this constraint.

The issue is IMO that `$container->findTaggedServiceIds('validator.constraint_validator', true)` does not return all the validators.

The result have been confirmed by executing `bin/console debug:container --tag=validator.constraint_validator`. It listed all my custom validators and the one having an explicit service definition from Symfony.

I have not been able to go further and now need help. 
I'd be glad to help and provide a PR :)

**Comment by nfragnet** [comment]
I provided a reproducer based on minimal [Symfony setup of Kevin Dunglas](https://github.com/dunglas/symfony-docker) above which I added `symfony/translation` & `symfony/validator`.

https://github.com/nfragnet/symfony_issue_49397

At this point, only the `TranslatableMessage` transkey was extracted but not the other one (including Expression & Email).

I had to `composer require --dev symfony/maker-bundle` so `nikic/php-parser` is added to the project and the first translation keys are extracted.

As not everyone include the MakerBundle in projects, maybe an extra-requirement of `nikic/php-parser` could be necessary.

**Comment by nfragnet** [comment]
At this point I discovered that Symfony built-in constraint validators have no service declaration (NotBlankValidator, LengthValidator and so on) except the following 4:

- `validator.email`: `Symfony\Component\Validator\Constraints\EmailValidator`
- `validator.expression`: `Symfony\Component\Validator\Constraints\ExpressionValidator`
- `validator.not_compromised_password`: `Symfony\Component\Validator\Constraints\NotCompromisedPasswordValidator`
- `validator.when`: `Symfony\Component\Validator\Constraints\WhenValidator`

As the other are not container services they cannot be tagged, and thus they are not injected in `ConstraintVisitor`.

At this point I can only see two options:
- validators should all be declared as services, so the auto configuration tag on `ConstraintValidatorInterface` add them the tag and they will all be injected in the visitor
- injecting all constraintClassNames of validator services having the tag `validator.constraint_validator` (in `TranslatorPass`) is not a valid way to guess if the current node is a constraint

`TranslatorPassTest` passes because the tested validators (length, notblank, isbn...) are container registered in the test.
https://github.com/symfony/symfony/blob/c965b032f648181a9e08ae3ee175af4ba4187f2b/src/Symfony/Component/Translation/Tests/DependencyInjection/TranslatorPassTest.php#L128-L149

**Comment by MatTheCat** [comment]
> Symfony built-in constraint validators have no service declaration (NotBlankValidator, LengthValidator and so on) except […] 4

Yes validators without dependencies do not need to be registered as services because their factory will try to instantiate them without arguments: https://github.com/symfony/symfony/blob/dcda61f55ceefc819cd77cb589801115306fdb9d/src/Symfony/Component/Validator/ContainerConstraintValidatorFactory.php#L50

Well, this is without taking this issue into account!

I’m not sure we want to maintain a hard-coded list of “simple” validators in the `AddConstraintValidatorsPass`. That would also mean that userland validators could still be ignored by `translation:extract`.

Could you try a PR to register and tag every validator?

**Comment by nfragnet** [comment]
> That would also mean that userland validators could still be ignored by translation:extract.

This is already the case for validators that are neither autowired/autoconfigured, nor explicitly declared.

> I’m not sure we want to maintain a hard-coded list of “simple” validators in the AddConstraintValidatorsPass

An alternative solution would be to extract validators constraint names using the same technique as the command `debug:validator`. That solution would even be able to get userland constraints. As an extract command, I wonder if the performance overhead could be considered acceptable.

> Could you try a PR to register and tag every validator?

Yes absolutely, I'll be able to look into it by March.
