### ISSUE TITLE
[Mailer][Mailjet] MailjetApiTransport Sandbox Mode

### ISSUE THREAD

**Issue by mdawart** [symfony/symfony#49410]
### Description

Mailjet introduced a Sandbox Mode https://dev.mailjet.com/email/guides/send-api-v31/#sandbox-mode that allows to use the API but not sending any email e.g. for debugging. 

https://github.com/symfony/mailjet-mailer/compare/5.4...mdawart:mailjet-mailer:sandbox

### Example

`MAILER_DSN=mailjet+api://$PUBLIC_KEY:$PRIVATE_KEY@default?sandbox=true`

**Comment by stof** [comment]
Please open a pull request to submit contributions.

**Comment by mdawart** [comment]
https://github.com/symfony/mailjet-mailer/pull/3

**Comment by mdawart** [comment]
https://github.com/symfony/mailjet-mailer/pull/4

**Comment by mdawart** [comment]
https://github.com/symfony/mailjet-mailer/pull/4
