### ISSUE TITLE
[Framework] cookie_secure default behavior does not match documentation

### ISSUE THREAD

**Issue by ristomcgehee** [symfony/symfony#49436]
### Symfony version(s) affected

6.2.5

### Description

In the [documentation](https://symfony.com/doc/current/reference/configuration/framework.html#cookie-secure), it states that the default behavior for the `cookie_secure` option is "auto", meaning that if the connection is HTTPS, the session cookie will have the 'Secure' flag set, and if the connection is HTTP, it will not have the 'Secure' flag set. However, when the `cookie_secure` option is not included in `config/packages/framework.yaml`, it acts as if the option is set to "false", that is when you connect via HTTPS, the 'Secure' flag is **not** set.

### How to reproduce

I've created a reproducer project for this: https://github.com/ristomcgehee/symfony-cookie-secure-default

Clone the repo, run these commands:
```sh
composer install
symfony server:ca:install
symfony serve
```
Then visit the https:// URL for the web server in your browser, ignore the certificate error, and follow the instructions on the homepage.

### Possible Solution

This could be fixed by updating the default behavior to act like "auto" or by updating the documentation. I'd personally prefer to see the default behavior updated.

**Comment by MatTheCat** [comment]
#31376 already reported the problem and was deemed a documentation issue, handled by https://github.com/symfony/symfony-docs/pull/11524, https://github.com/symfony/symfony-docs/pull/12049 and https://github.com/symfony/symfony-docs/pull/14999.

In fact the default value is not `false`: there is none, meaning that the `session.cookie_secure` directive will be used.

**Comment by nicolas-grekas** [comment]
Thanks for the PR on the doc.
At least the setting is correctly set to auto in the recipe:
https://github.com/symfony/recipes/blob/main/symfony/framework-bundle/6.2/config/packages/framework.yaml
