### ISSUE TITLE
[Security] `Security::login()` is ignoring argument `firewall`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#49444]
### Symfony version(s) affected

6.2.6

### Description

I'm just forwarding what @wouterj said at https://github.com/symfony/symfony-docs/pull/17922#issuecomment-1435963528

> This is a bug, `Security::login()` acts as if you can pass a firewall name, but internally `UserAuthenticator` always uses the current firewall (i.e. the code uses the authenticator of the set firewall, but saves the token in the session of the current firewall).
> We should fix this bug in the code (by using the correct `AuthenticatorManager::authenticateUser` directly instead of using `security.user_authenticator`).

### How to reproduce

See above

**Comment by chalasr** [comment]
See #49446
