### ISSUE TITLE
Fix benchmark implementation

### ISSUE THREAD

**Issue by kaznovac** [symfony/symfony#49447]
### Symfony version(s) affected

*

### Description

TechEmpower's Web framework benchmarks is well known and respected online resource for web framework performance information.

The symfony implementation has been failing for some time, see this comment:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7928#issuecomment-1435974987

This is a good first time issue

### How to reproduce

See TFB official documentation:
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Getting-Started
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview

**Comment by joanhey** [comment]
Fixed https://github.com/TechEmpower/FrameworkBenchmarks/pull/8324
