### ISSUE TITLE
When tring to run encore dev : ERROR in main Module not found: Error: Can't resolve './src' in /Users/myusername/documents/myprojectfile

### ISSUE THREAD

**Issue by ElFamosoWilli** [symfony/symfony#49445]
### Symfony version(s) affected

6.2.6

### Description

Here is my issue I created a docker environement  for my symfony app into it there is my container for php mysql and nginx , 
when starting the project into my Dockerfile there is commands to install yarn and npm , to install the packages needed to make webpack encore work , but here is the issue when I want to run ' yarn encore dev ' or ' yarn encore dev --watch ' 
it doesn't work and it shows me this error : 

Running webpack ...

assets by status 0 bytes [cached] 1 asset

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in main
Module not found: Error: Can't resolve './src' in '/Users/myusername/Documents/TpSymfonyEspadrilleVolante'
resolve './src' in '/Users/myusername/Documents/TpSymfonyEspadrilleVolante'
  using description file: /Users/myusername/Documents/TpSymfonyEspadrilleVolante/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/myusername/Documents/TpSymfonyEspadrilleVolante/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/myusername/Documents/TpSymfonyEspadrilleVolante/src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/myusername/Documents/TpSymfonyEspadrilleVolante/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/myusername/Documents/TpSymfonyEspadrilleVolante/src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Users/myusername/Documents/TpSymfonyEspadrilleVolante/src.wasm doesn't exist
      as directory
        /Users/myusername/Documents/TpSymfonyEspadrilleVolante/src doesn't exist

webpack 5.75.0 compiled with 1 error and 1 warning in 89 ms

i also tried numerous times to delete the composer package and the files related to webpack encore to reinstall it first running 

composer require symfony/webpack-encore-bundle

then running 

yarn install 

and then running yarn encore dev

I am checking my files and my dependencies everything seems fine to me ? 
What is the problem , underneath you'll find ressources  from my code , including my webpack config file. 

 

[yarn-error.log](https://github.com/symfony/symfony/files/10777038/yarn-error.log)
<img width="746" alt="Capture d’écran 2023-02-19 à 14 51 46" src="https://user-images.githubusercontent.com/85033829/219952667-3a358605-6894-4c6f-baa9-af281c650bca.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 52 29" src="https://user-images.githubusercontent.com/85033829/219952672-ceb336a7-e78c-4da0-951c-2a7a74f77e57.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 52 17" src="https://user-images.githubusercontent.com/85033829/219952674-9500a9c4-d565-4a29-9c6a-8043981b9d1f.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 52 07" src="https://user-images.githubusercontent.com/85033829/219952676-dda4b36b-41d2-40fb-8dd9-a23db5e29d99.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 51 32" src="https://user-images.githubusercontent.com/85033829/219952687-5d1be601-ea42-48f5-94cc-40bd51d02a94.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 51 26" src="https://user-images.githubusercontent.com/85033829/219952706-754676c7-378f-4a96-b677-c5bb8babdf81.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 51 11" src="https://user-images.githubusercontent.com/85033829/219952715-1f7ac443-ebc7-4a0e-bdfa-3cfefbea4d45.png">
<img width="746" alt="Capture d’écran 2023-02-19 à 14 50 54" src="https://user-images.githubusercontent.com/85033829/219952724-c8b8e2f3-7db4-490a-b921-7939ac6ac453.png">

### How to reproduce

To reproduce it you need first to install the composer package 
then run
then yarn install 
then run yarn encore dev

**Comment by alexisLefebvre** [comment]
Please [format the code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) properly.

**Comment by stof** [comment]
Also, please provide the code as markdown code blocks, not as screenshots (we cannot copy-paste code from a screenshot to actually have a reproducer)

And btw, we don't have the code of this `assets/app.js` file which is the entrypoint of the webpack build, so we cannot create a reproducer anyway even if we were rewriting all the code by hand by reading those screenshots.

**Comment by ElFamosoWilli** [comment]
thanks guys for the responses I found the issue , it was due to the fact that I needed to be in app folder in order to install webpack encore and run it properly , it was that stupid , sorry guys , and thanks again .
