### ISSUE TITLE
ip_pool_name in SendgridApiTransport.php

### ISSUE THREAD

**Issue by TheAFOGroup** [symfony/symfony#49460]
### Description

As the title suggest, this is a **very required feature**. 

Whilst you are considering adding this, if it will be added, how can get around it?

This is also related to: https://stackoverflow.com/questions/58450756/symfony-mailer-sendgrid-ip-poolswhich is **from 3 years ago**.

Thanks

**Comment by MatTheCat** [comment]
This won’t happen in Symfony as long as https://github.com/symfony/symfony/pull/41714#issuecomment-862965497 stands true (also see https://github.com/symfony/symfony/pull/42915#pullrequestreview-1028784758).

In the meantime you’ll have to implement your own transport.

**Comment by TheAFOGroup** [comment]
> This won’t happen in Symfony as long as [#41714 (comment)](https://github.com/symfony/symfony/pull/41714#issuecomment-862965497) stands true (also see [#42915 (review)](https://github.com/symfony/symfony/pull/42915#pullrequestreview-1028784758)).
> 
> In the meantime you’ll have to implement your own transport.

Thank you for your reply. Wow. Just disappointing. No comment.
