### ISSUE TITLE
The regions in the Intl component are not ISO 3166-1 compliant

### ISSUE THREAD

**Issue by jaggaer-mcosic** [symfony/symfony#49462]
### Description

Some of the regions in Intl component are not aligned with ISO 3166-1 list.
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Intl/Resources/data/regions/en.php

Some of the examples where name is not adapted:

TR	Türkiye	                                                        Previous ISO country name: Turkey
US	United States of America	                        Previous ISO country name: United States
VE	Venezuela (Bolivarian Republic of)	1974        Previous ISO country name: Venezuela

This should be adapted in all languages.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by stof** [comment]
The Intl component uses data from the CLDR project. We don't maintain those country names ourselves. If you want the data to be changed, you need to contribute upstream in the CLDR project: https://cldr.unicode.org/

**Comment by stof** [comment]
Note that using the ISO list as source of truth would not work, as they don't provide translated names.

Side node: the English name for TR is also `Turkey` in that data: https://github.com/symfony/symfony/blob/8c19af2346ed6ed4021d3efc024e0af138e69794/src/Symfony/Component/Intl/Resources/data/regions/en.php#L229
`Türkiye` is the name in the TR locale: https://github.com/symfony/symfony/blob/d2e64abc2771cd9615d4780850221f3d4a744613/src/Symfony/Component/Intl/Resources/data/regions/tr.php#L229

**Comment by jaggaer-mcosic** [comment]
Everything is clear, the case can be closed. Thanks for explaining.
