### ISSUE TITLE
[Twig-Bridge] Inconsistent function definition

### ISSUE THREAD

**Issue by FluffyDiscord** [symfony/symfony#49486]
### Symfony version(s) affected

6.2.*

### Description

In Symfony 6.2.* (did not test other versions) the `Symfony\Component\Routing\Generator\UrlGeneratorInterface` parameter `name` can no longer be `null`. This is inconsistent with the `Symfony\Bridge\Twig\Extension\RoutingExtension` function `path()` which can have nullable `name` parameter.

### How to reproduce

Using Twig-Bridge version: 6.2.5

1. Create dummy twig template
2. Put somewhere inside the template `{{ path(null) }}`
3. See error mentioned above

### Possible Solution

The backwards compatible version would be to simply return empty string from `RoutingExtension::path()` if `name` is `null`.

The other solution would be to make the `path` function parameter `name` string only and do not allow `null`.

**Comment by MatTheCat** [comment]
`RoutingExtension::getPath`’s `$name` is typed as `string` since Symfony 5 so I think I’m missing something?

**Comment by FluffyDiscord** [comment]
No you are not. That is indeed the case. I have reinstalled composer and now its typed as described. I am not sure why it was like that. I probably forgot to change it back when debugging something.
