### ISSUE TITLE
[Serializer] Support value resolvers?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#49498]
### Description

Inspired by #49138 

I't be great when submitting eg. `{"entity": 1}`, it be deserialized into `Entity` using existing value resolvers.

```php
class Dto {
 #[MapEntity]
 public Entity $entity;
}
```

**Comment by stof** [comment]
I don't think reusing value resolvers would make sense (that would require a bunch of hacks to satisfy their signature).

However, this kind of things can already be implemented through normalizers and denormalizers (except that it currently requires a custom normalizer for the Dto class, not the Entity class, to have access to attributes that are on the Dto properties)

**Comment by ro0NL** [comment]
i agree the signature/namespace is a mismatch, that's unfortunate

but that hack is the fastest route for code reusing :sweat_smile:
