### ISSUE TITLE
[RFC] dd + curl

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#49508]
### Description

I often use `curl` to debug routes in dev env, and I prefer using `dump/dd()` over xdebug and what not.

Currently it always produces plain HTML, which is a pain to digest in the terminal.

Then I noticed `user-agent: curl/7.81.0` in the request headers.

So the idea is to detect it and produce plain text instead (eg. good old var_dump/print_r).

Thoughts?

**Comment by cizordj** [comment]
Sounds good, it'd be awesome if it could print colorful characters in the terminal as well. Don't know how it would behave on Windows though

**Comment by derrabus** [comment]
> Then I noticed `user-agent: curl/7.81.0` in the request headers.
> 
> So the idea is to detect it and produce plain text instead (eg. good old var_dump/print_r).

I don't think we should build user-agent sniffing into Symfony's core. That being said, such a "feature" could easily be build in userland using an event listener on the response object, if you really want to have it.

**Comment by ro0NL** [comment]
`VAR_DUMPER_DETECT_CURL=1` maybe? it's a dev only thing also :shrug: 

> if your really want to have it

well yes, but i dont want to maintain it :D then i prefer existing solutions

**Comment by derrabus** [comment]
> i dont want to maintain it

Neither do I! 🙈

**Comment by wouterj** [comment]
We already provide a solution for this: The var dump server https://symfony.com/doc/current/components/var_dumper#the-dump-server This provides good colored output in the terminal for any requests and isn't bound to a userland specific user-agent.

**Comment by stof** [comment]
And its benefit is that the dump content is not part of the HTTP response (keeping a JSON or XML response valid for instance)

**Comment by ro0NL** [comment]
hm, i figured detecting curl out-of-the-box could conflict with dump server, which makes it more hassle to maintain

using dump server / grepping profiler link is more academic approach, i agree :+1: 

nevertheless here's a quick patch on a per-kernel basis:

```
public function boot(): void
{
    parent::boot();

    if ('dev' === $this->environment && str_starts_with($_SERVER['HTTP_USER_AGENT'] ?? '', 'curl/')) {
        VarDumper::setHandler(function ($var) {
            ob_start();
            var_dump($var);
            echo strip_tags(ob_get_clean());
        });
    }
}
```

i also tried being academic using CliDumper, but no cigar. So there's that :sweat_smile:
