### ISSUE TITLE
[DependencyInjection] Unable to inject parameters containing array of enums into service

### ISSUE THREAD

**Issue by imba28** [symfony/symfony#49505]
### Symfony version(s) affected

^6.2.0

### Description

Symfony 6.2 introduced enums as service parameters: https://symfony.com/blog/new-in-symfony-6-2-improved-enum-support
One of the examples includes defining an array of enums as a parameter:

```php
// config/services.php
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use App\Entity\BlogPost;

return static function (ContainerConfigurator $container) {
    $container->parameters()
        // ...

        ->set('app.some_parameter', SomeEnum::Foo)
        ->set('app.another_parameter', [SomeEnum::Foo, SomeEnum::Bar]);
};
```

Although, when you try to inject said parameter into a service, the container produces a warning when it's asked to instantiate the service:  

> Warning: Undefined array key "app.another_parameter"

### How to reproduce

1. Define an array of enum as a service parameter, as stated in the documentation.
```php
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use App\SomeEnum;

return static function (ContainerConfigurator $container) {
    $container->parameters()
        // ...

        ->set('app.some_parameter', SomeEnum::Foo)
        ->set('app.another_parameter', [SomeEnum::Foo, SomeEnum::Bar]);
};
```

3. Next, create a class and inject both of the parameters into the constructor method:

```php
namespace App\Service;

use App\SomeEnum;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final class DemoService
{
    public function __construct(
        #[Autowire('%app.some_parameter%')]
        private SomeEnum $enum,

        #[Autowire('%app.another_parameter%')]
        private array $enums
    )
    {
        dd($this->enum, $this->enums);
    }
}
```
4. Ask the container to instantiate `DemoService`.
5. While `app.some_parameter` can be resolved, the container will warn about the absence of `app.another_parameter`.

I created a repo demonstrating this issue: See https://github.com/imba28/symfony-enum-array-parameters-bug for a complete example

### Possible Solution

I think this is due to a bug in the class `PhpDumper`. Whenever a parameter contains an enum, it is marked as a dynamic parameter that must be resolved using `$container->getParameter()`: 

https://github.com/symfony/symfony/blob/1dcb0f919c7183a795e15805a34db709ce27388c/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1516-L1522

However, the routine dumping the parameters lacks an equivalent check: https://github.com/symfony/symfony/blob/1dcb0f919c7183a795e15805a34db709ce27388c/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1918-L1934

For that reason, the generated file `var/cache/dev/ContainerXYZ/getDemoServiceService.php` includes 

```php
return $container->privates['App\\Service\\DemoService'] = new \App\Service\DemoService(\App\SomeEnum::Foo, $container->parameters['app.another_parameter']);
```

instead of 

```php
return $container->privates['App\\Service\\DemoService'] = new \App\Service\DemoService(\App\SomeEnum::Foo, $container->getParameter('app.another_parameter'));
```

which eventually fails, since `app.another_parameter` has been previously marked as a dynamic parameter and thus is not part of `$container->parameters`.

#### Possible fix
Recursively traverse `$value` and determine if there's an enum hidden somewhere and place the check in this condition: https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1928 

If it does, dump `$this->getParameter(%s)` instead of `$this->parameters[%s]`.

**Comment by fancyweb** [comment]
Thanks for the great report.
Instead of trying to fix it, could we rechallenge https://github.com/symfony/symfony/pull/44868#discussion_r795990625 @nicolas-grekas and simplify the code?

**Comment by nicolas-grekas** [comment]
Challenge accepted: I asked to PHP core devs, and they confirmed listing enums in array prevents opcache from putting said array in shared memory. I still recommend splitting as advised on that comment.

**Comment by stof** [comment]
The issue is that https://github.com/symfony/symfony/pull/48045 added support for adding enums in parameters in loaders and configurators, without adding tests to ensure they work everywhere else in the component. So this was not caught when doing other refactorings.

**Comment by fancyweb** [comment]
Should we reuse `exportParameters()` in `dumpParameter()` just to check for enums then? Create a new private method? Just `foreach` recursively with a `goto` in `dumpParameter()`?
