### ISSUE TITLE
[RFC] [Console] typehint input as attribute?

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#49522]
### Description

Hello

RFC regarding to add more typehint on `Symfony/Component/Console/Input/Input` as attributes.

Can we imagine "mimicking" https://github.com/symfony/symfony/pull/49138 but for console in some way?

`bin/console` (**cli entry point**) can leverage attributes to validate/parse/transform user land inputs before command is really executed

(the same way `public/index.php` (**web entry point**) now leverage tons of new features since v6.3

- https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects
- https://symfony.com/blog/new-in-symfony-6-3-query-parameters-mapper
- (https://symfony.com/blog/new-in-symfony-6-3-targeted-value-resolvers)

Thanks!

### Example

- `MapQueryString` => `MapInputString`
- ... try to see what usage can be backported from the "web request" context

no example/no idea of better naming and related implementation

**Comment by 94noni** [comment]
Additional recent topic:

- https://speakerdeck.com/chalasr/reinvent-symfony-console?slide=26

Friendly ping @chalasr 
I would love to help contribute to this if you have a clear path/roadmap on the work to do
Perhaps after v6.3 is out :)

cheers!

**Comment by chalasr** [comment]
Oh sure, let me reach out to you on slack probably next week. I think this can be closed meanwhile so that nobody picks it, the work has started so there's some material already :)

**Comment by 94noni** [comment]
Issue description a bit completed with recent addition (blog post as reminder)

> I think this can be closed meanwhile so that nobody picks it, the work has started so there's some material already :)

closing here then

thank you :)

**Comment by 94noni** [comment]
@chalasr hello, may I ask you any news on that topics ?
regards

**Comment by chalasr** [comment]
My OSS capabilities have been limited lately but I'll be back :) that work will be my primary focus for the next coming months and will hopefully target 7.1

**Comment by 94noni** [comment]
copy that!
