### ISSUE TITLE
Returns the logged user null when debug mode is off

### ISSUE THREAD

**Issue by rasidk** [symfony/symfony#49562]
### Symfony version(s) affected

6.2

### Description

The user object return null when **APP_DEBUG=0**.  I have tried with  Symfony\Bundle\SecurityBundle\Security and Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

```
<?php 
namespace App\Classes;

use Symfony\Bundle\SecurityBundle\Security;

class TestClass
{

    public function __construct(
        private Security $security
    ) {
    }

    public  function getUserId()
    {
        $user = $this->security->getUser();
        return $user->getId();
       
    }

```

### How to reproduce

Set env config APP_DEBUG=0 and run the code

**Comment by rasidk** [comment]
* Set env config APP_DEBUG=0 and run the code

**Comment by derrabus** [comment]
Please provide [a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your issue.

**Comment by rasidk** [comment]
I have solved the issue by adding null condition checker, the issue was found when calling the class multiple times, anyways thank you
