### ISSUE TITLE
[DomCrawler] Return something 

### ISSUE THREAD

**Issue by rpayanm** [symfony/symfony#49560]
### Description

Can we return an empty string or NULL or FALSE or anything else when we try to get a value using the `DomCrawler` component?

For example, I have this code:
```
$v1 = $crawler->filter('.some-class')->eq(1)->text();
$v2 = $crawler->filter('.some-class')->eq(2)->attr('href');
$v3 = $crawler->filter('.some-class')->eq(3)->text();
$v4 = $crawler->filter('.some-class')->eq(4)->text();
// etc.
```

If the first line throws the error:
```
InvalidArgumentException: The current node list is empty. 
```
the script will stop.

I know I can use the `count` function or use a `try` block.
If we use the `count` function on every `->text()`, our code will look ugly.
If we use a `try` block then variables `$v2`, `$v3`, `$v4` won't have any value.

It would be great if these function `->text()` or `->href()` or any others, check if node list is empty and return empty value, NULL, FALSE or anything else.

**Comment by stof** [comment]
As those method return the text of the *first* node in the list (not something based on the whole list), failing when there is no such node seems better to me than silently treating it like an empty node.

**Comment by xabbuh** [comment]
I agree with @stof and I am going to close therefore.
