### ISSUE TITLE
[HttpClient] Profiler debug not working

### ISSUE THREAD

**Issue by N445** [symfony/symfony#49561]
### Symfony version(s) affected

6.2.6

### Description

Lorsque je fais une requète avec httpclient la requète se fais parfaitement bien, mais je n'ai aucun débug dans mon profiler, pourtant je fais le même code que dans la doc

here the code 

```php
    private                     $client;
    private HttpClientInterface $githubClient;

    public function __construct(HttpClientInterface $client, HttpClientInterface $githubClient)
    {
        $this->client = $client;
        $this->githubClient = $githubClient;
    }

    #[Route('/test', name: 'TEST')]
    public function test(): Response
    {
        $response = $this->client->request(
            'GET',
            'https://api.github.com/repos/symfony/symfony-docs'
        );

        dump($response->toArray());

        $response = $this->githubClient->request(
            'GET',
            '/repos/symfony/symfony-docs'
        );

        dump($response->toArray());

        return $this->render('default/test.html.twig');
    }
```

and here my profiler bar

![image](https://user-images.githubusercontent.com/25900291/221872782-a6a5e6ee-4e68-45f4-bf2c-b9df3766a0bf.png)

### How to reproduce

Create a fresh install of Symfony

1. symfony new test-http-client
2. add a controller and a view to see the profiler bar
3. add http client bundle
4. make the first query in the doc
5. don't have any debug in my profiler

**Comment by fancyweb** [comment]
Hello, try upgrading to Symfony 6.2.7 (it has just been released) and it should work.
