### ISSUE TITLE
[Cache] Allow opt-out of LockRegistry::compute when using TagAwareAdapter with ArrayAdapters

### ISSUE THREAD

**Issue by dorrogeray** [symfony/symfony#49577]
### Description

Hi, I have encountered an issue when combining `Symfony\Component\Cache\Adapter\TagAwareAdapter` with `Symfony\Component\Cache\Adapter\ArrayAdapter`. The use case is request-scoped in-memory cache - we have some sub-optimal legacy code which calls our document database unnecessarily multiple times during a single request, but refactoring to solve the root cause is a larger effort. In the meantime, we want to use the request-scoped in-memory cache. What we found out is that cache stampede protection via `Symfony\Component\Cache\LockRegistry::compute` is active with our configuration and there is no simple way to get around it. We don't need / want stampede protection for in-memory cache, as it makes no sense, but there seems to be no simple way how to disable it in the `Symfony\Component\Cache\Adapter\TagAwareAdapter`.

The way it works is that `Symfony\Component\Cache\Adapter\TagAwareAdapter` uses `Symfony\Component\Cache\Traits\ContractsTrait`, which force-wraps the callback in the `setCallbackWrapper` with `Symfony\Component\Cache\LockRegistry::compute`. This causes significant performance degradation.

The `Symfony\Component\Cache\Traits\ContractsTrait::$callbackWrapper` property is private, so extending the `Symfony\Component\Cache\Adapter\TagAwareAdapter` does not help without reflection or other hacky ways to set the wrapper without wrapping it with `Symfony\Component\Cache\LockRegistry::compute`.

This is the hacky workaround:
```php
<?php declare(strict_types=1);

namespace BE\Cache;

use Psr\Log\LoggerInterface;
use ReflectionClass;
use Symfony\Component\Cache\Adapter\AdapterInterface;
use Symfony\Component\Cache\Adapter\TagAwareAdapter;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Contracts\Cache\ItemInterface;

class InMemoryTagAwareAdapter extends TagAwareAdapter
{
    /** @noinspection PhpTooManyParametersInspection */
    public function __construct(AdapterInterface $itemsPool, AdapterInterface $tagsPool = null, float $knownTagVersionsTtl = 0.15)
    {
        parent::__construct($itemsPool, $tagsPool, $knownTagVersionsTtl);

        $ref = new ReflectionClass(TagAwareAdapter::class);

        // Prevent \Symfony\Component\Cache\Traits\ContractsTrait::setCallbackWrapper from adding LockRegistry::compute
        // wrapper around the callback, since we don't want to avoid a stampede when working in-memory
        $prop = $ref->getProperty("callbackWrapper");
        $prop->setAccessible(true);
        $prop->setValue($this, static function (callable $callback, ItemInterface $item, bool &$save, CacheInterface $pool, \Closure $setMetadata, ?LoggerInterface $logger) {
            return $callback($item, $save);
        });
    }
}
```

By setting the `Symfony\Component\Cache\Traits\ContractsTrait::$callbackWrapper`, the callback does not get wrapped with `Symfony\Component\Cache\LockRegistry::compute` since the `Symfony\Component\Cache\Traits\ContractsTrait::setCallbackWrapper` will not be called in `Symfony\Component\Cache\Traits\ContractsTrait::doGet`.

I would be happy to prepare a PR but I am not sure how to approach it. Should this be a fix on level of `Symfony\Component\Cache\Adapter\TagAwareAdapter`?

PS: Thanks for all the hard work on Symfony :heart: 

### Example

```php
$inMemoryCache = new \Symfony\Component\Cache\Adapter\TagAwareAdapter(
    \Symfony\Component\Cache\Adapter\ArrayAdapter(),
    \Symfony\Component\Cache\Adapter\ArrayAdapter(),
);

// Expected result is that this should NOT call \Symfony\Component\Cache\LockRegistry::compute
// Actual result is that it does
$value = $inMemoryCache->get('foo', function (\Symfony\Contracts\Cache\ItemInterface $item) {
    return 1;
});
```

**Comment by nicolas-grekas** [comment]
Can't you call `$inMemoryCache->setCallbackWrapper(null);` right after creating `$inMemoryCache`?

**Comment by dorrogeray** [comment]
@nicolas-grekas You are right, it works perfectly. :tada: Sorry, I misunderstood how the setter works, for some reason I thought it decorates the `$previousWrapper` with `$callbackWrapper`. Stupid oversight on my part - I am closing the issue, hopefully it will help someone if they encounter similar problem. :+1:
