### ISSUE TITLE
[Messenger] When using Messenger's Serializer for JSON: some stamps fail (e.g. TransportNamesStamp)

### ISSUE THREAD

**Issue by StephanMeijer** [symfony/symfony#49574]
### Symfony version(s) affected

6.2, 6.3

### Description

When using `Symfony\Component\Messenger\Transport\Serialization\Serializer`, serializing and then deserializing some stamps, such as `Symfony\Component\Messenger\Stamp\TransportNamesStamp` fail due to the name of the getter not matching the name in the constructor.

### How to reproduce

Use the serializer `Symfony\Component\Messenger\Transport\Serialization\Serializer` to serialize and deserialize this Stamp.

### Possible Solution

Rename the variable name `$transports` to `$transportNames` in the constructor.

### Additional Context

I will put out a PR myself.

**Comment by tsantos84** [comment]
Hi. For record purposes, I also was affected by this issue. Thanks for the PR.
