### ISSUE TITLE
[DoctrineBridge] Deprecate passing Doctrine subscribers to ContainerAwareEventManager

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#49586]
As spotted in https://github.com/symfony/symfony/issues/49387#issuecomment-1442179095, `Doctrine\Common\EventSubscriber` should be banned from the bridge because it forces instantiating the event listeners (and their deps) even if they are never called.

[`#[AsDoctrineListener]`](https://github.com/doctrine/DoctrineBundle/tree/2.8.x/Attribute/AsDoctrineListener.php) is a way better alternative anyway.

**Comment by realjjaveweb** [comment]
If people wonder how to do this for more events than just 1 - there's the `Attribute::IS_REPEATABLE` in the declaration of the `AsDoctrineListener` attribute, so this should work:
```
#[AsDoctrineListener(event: Events::preUpdate)]
#[AsDoctrineListener(event: Events::prePersist)]
#[AsDoctrineListener(event: Events::postPersist)]
```
