### ISSUE TITLE
[Security] add argument target support for #[IsGranted]

### ISSUE THREAD

**Issue by ninsuo** [symfony/symfony#49589]
### Description

Hi,

I am currently cleaning the `SensioFrameworkExtraBundle` from a project and noticed that attribute `#[Entity(argumentName, expression)]` (whose target was the action method) has been replaced by argument attribute `#[MapEntity]`. This removes the argument name from the argument's signature and that's good.

But I see that the `#[IsGranted]` attribute does not support argument targets yet, and it would be a nice addition.

Here's an example, before removing `SensioFrameworkBundle`, a controller looked like this:

```php
    #[Route(path: '/address/{addressId}', name: 'read_address')]
    #[IsGranted(UserRoles::USER_OWNS_RESOURCE, 'address')]
    #[Entity('address', 'repository.findOneByUuid(addressId)')]
    public function read(Address $address): Response
    {
        // ...
    }
```

After the `SensioFrameworkExtraBundle` removal, it looks like:

```php
    #[Route(path: '/address/{addressId}', name: 'read_address')]
    #[IsGranted(UserRoles::USER_OWNS_RESOURCE, 'address')]
    public function read(
         #[Entity(expr: 'repository.findOneByUuid(addressId)')]          
         Address $address
    ): Response {
        // ...
    }
```

It would be a good addition to also put `#[IsGranted]` inside arguments.

### Example

```php
    #[Route(path: '/address/{addressId}', name: 'read_address')]
    public function read(
         #[IsGranted(UserRoles::USER_OWNS_RESOURCE)]
         #[Entity(expr: 'repository.findOneByUuid(addressId)')]          
         Address $address
    ): Response {
        // ...
    }
```

**Comment by stof** [comment]
Given that the security check does not happen during the argument resolution but after it, this would be hard to implement (we don't have easy access to the argument metadata anymore at that point).
And it would require a separate implementation (as supporting expressions would not work the same if we have access to only one argument rather than all of them)

**Comment by stof** [comment]
Also, the security check applies on the whole action (it checks "are you allowed to access this action ?"), so semantically, this fits better as a method attribute than an argument attribute IMO.

**Comment by ninsuo** [comment]
> Given that the security check does not happen during the argument resolution but after it, this would be hard to implement (we don't have easy access to the argument metadata anymore at that point).

The [listener](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Http/EventListener/IsGrantedAttributeListener.php#L31) performs the security check just after the argument resolution, and it has almost all the context. We are missing a reflector for the argument itself, but nothing that really blocks:

If I draft the implementation, it looks like this:

```php
    public function onKernelControllerArguments(ControllerArgumentsEvent $event)
    {
        // currently private
        $controllerEvent = $event->getControllerEvent();
 
        foreach ($controllerEvent->getControllerReflector()->getParameters() as $argumentReflector) {
            $subject = $event->getNamedArguments()[$argumentReflector->getName()];
            foreach ($argumentReflector->getAttributes(IsGranted::class) as $attribute) {
                $instance = $attribute->newInstance();
                $instance->subject = $subject; // readonly but you get the point
                // ... performs same work as of today
            }
        }
```

> Also, the security check applies on the whole action (it checks "are you allowed to access this action ?"), so semantically, this fits better as a method attribute than an argument attribute IMO.

It doesn't seem to be a problem to me, used with a subject, it's more "are you allowed to access this resource ?"

**Comment by Neirda24** [comment]
At first I looked at it the same as @stof ... Then I thought: maybe with a different constructor where subject is automatically set as the argument value. Same semantic in the end.

**Comment by wouterj** [comment]
Hi!

I agree with @stof here. In language terms, the controller is always the subject for `#[IsGranted]`, the parameter is the object. For `#[MapEntity]`, the parameter is the subject (and the controller is nothing). This converts naturally to having a class target for `#[IsGranted]` and an parameter target for `#[MapEntity]`.

Considering that, and the fact that this is technically not straightforward, I don't think we should do this.

**Comment by ninsuo** [comment]
Alright, thank you for having a look anyway.

---

For people interested, here is an implementation:

`App\Attribute\IsGranted.php`:

```php
<?php

namespace App\Attribute;

use Symfony\Component\ExpressionLanguage\Expression;


#[\Attribute(\Attribute::TARGET_PARAMETER | \Attribute::IS_REPEATABLE)]
final readonly class IsGranted
{
    public function __construct(public string|Expression $attribute)
    {
    }
}
```

`App\EventSubscriber\IsGrantedEventSubscriber.php`:

```php
<?php

namespace App\EventSubscriber;

use App\Attribute\IsGranted;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class IsGrantedEventSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private readonly AuthorizationCheckerInterface $authChecker,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [KernelEvents::CONTROLLER_ARGUMENTS => ['onKernelControllerArguments', 20]];
    }

    public function onKernelControllerArguments(ControllerArgumentsEvent $event)
    {
        $controller = $event->getController();

        if (\is_array($controller) && method_exists(...$controller)) {
            $reflector = new \ReflectionMethod(...$controller);
        } elseif (\is_string($controller) && \str_contains($controller, '::')) {
            $reflector = new \ReflectionMethod($controller);
        } else {
            $reflector = new \ReflectionFunction($controller(...));
        }

        $arguments = $event->getNamedArguments();

        foreach ($reflector->getParameters() as $argumentReflector) {
            $subject = $arguments[$argumentReflector->getName()];

            foreach ($argumentReflector->getAttributes(IsGranted::class) as $attributeReflector) {
                /** @var IsGranted $attribute */
                $attribute = $attributeReflector->newInstance();

                if (!$this->authChecker->isGranted($attribute->attribute, $subject)) {
                    $message = sprintf('Access Denied by #[IsGranted(%s)] on controller', $attribute->attribute);

                    $accessDeniedException = new AccessDeniedException($message);
                    $accessDeniedException->setAttributes($attribute->attribute);
                    $accessDeniedException->setSubject($subject);

                    throw $accessDeniedException;
                }
            }
        }
    }
}
```

Usage example:

```php
    #[Route(path: '/{apiTokenId}', name: 'read', methods: [Request::METHOD_GET])]
    public function read(
        #[IsGranted(InternalRole::USER_RESOURCE)]
        #[MapEntity(expr: 'repository.findOneByUuid(apiTokenId)')]
        ApiToken $apiToken
    ): ApiTokenResponseFacade {
        return $this->apiTokenTransformer->expose($apiToken);
    }
```

Don't forget to test your implementation (in your own context), something like:

```php
    public function testIsGrantedAttribute()
    {
        $request = new ApiTokenRequestFacade();
        $request->setName('Hello, world!');
        $request->setPermissions([(new PermissionRequestFacade())->setName(UserRole::USER_DEVELOPER)]);

        $json = $this->endpoint(
            ApiTokenController::class,
            'create',
            $request,
            UserFixtures::BRUNO
        );

        $this->assertResponseIsSuccessful();
        $this->assertNotNull($id = $json['payload']['api_token_id'] ?? null);

        $this->endpoint(
            ApiTokenController::class,
            'read',
            user: UserFixtures::ALICE,
            parameters: [
                'apiTokenId' => $id,
            ]
        );

        $this->assertResponseStatusCodeSame(Response::HTTP_FORBIDDEN);
    }
```
