### ISSUE TITLE
Breaking change in 5.4.21 because of query parameter characters not being escaped anymore in `HttpClientTrait::mergeQueryString`

### ISSUE THREAD

**Issue by Levivb** [symfony/symfony#49582]
### Symfony version(s) affected

5.4.21

### Description

This issue is related to https://github.com/symfony/symfony/issues/49579

In symfony 5.4.21 a breaking change has been introduced causing some characters in the query part of urls to not be escaped anymore. https://github.com/symfony/http-client/compare/v5.4.20...v5.4.21 -> `HttpClientTrait::mergeQueryString`

To give some context, we're calling a third party service with a query parameters like this: 
```php
['query' => ['filter' => '{"publicationId":' . self::PUBLICATION_ID_TO_IMPORT . '}']]
```

Originally, the query would be escaped to this: `%7B%publicationId%22:1%7D`, but since the `{` and `}` are not escaped anymore, the query stays like this: `{%22publicationId%22:1}`

Which the third party doesn't handle very well and returns with a 500 status code.

An obvious fix on our side would be to escape `{` and `}` ourselves. But then the http client escapes `%`, which causes `%7B%publicationId%22:1%7D` to become `%257B%22publicationId%22:1%257D`

So what I'm left at is either not escaping, or to much escaping

### How to reproduce

Make `HttpClientTrait::mergeQueryString` public for easier access.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\HttpClient\CurlHttpClient;

$q = CurlHttpClient::mergeQueryString(null, ['filter' => '{"publicationId":1}'], true);
var_dump($q);
```

Result:
Pre 5.4.21: `filter=%7B%22publicationId%22%3A1%7D`
5.4.21: `filter={%22publicationId%22:1}`

**Comment by nicolas-grekas** [comment]
Fixed in #49580
Closing as duplicate of #49579

**Comment by Levivb** [comment]
Perhaps I'm missing something, but https://github.com/symfony/symfony/pull/49580 doesn't seem to fix this issue since I'm running into the issue with `{` and `}`. Not with `+`

**Comment by nicolas-grekas** [comment]
> query stays like this: `{%22publicationId%22:1}` Which the third party doesn't handle very well and returns with a 500 status code.

Arf, this is bad on their side. It looks like encoding of query parts is a mess. Browsers don't encode `{` nor `}` for example.

You can work around this by encoding the filter yourself when building the URL (not using the "query" option)

**Comment by Levivb** [comment]
Hehe, yea unfortunately I can't instruct them to fix this asap :)

Thanks for the tip to just build the full url ourselves. 
That seems to fix it. Not the most neat solution, but works.
So consider this issue resolved

Thanks for the quick help

**Comment by pbowyer** [comment]
After updating HttpClient I encountered this issue today with the Atlassian API, where JSON has to be passed in the query string. It no longer works in HttpClient's `['query' => [...]]` parameter and I've had to `urlencode` it and set it directly on the requested URL.

> Browsers don't encode { nor } for example.

I believe they do. [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) says the query string can contain `*( pchar / "/" / "?" )` which expands to `!`, `$`, `&`, `'`, `(`, `)`, `*`, `+`, `,`, `;`, `=`, something matching `%[0-9a-fA-F]{2}`, something matching `[a-zA-Z0-9]`, `-`, `.`, `_`, `~`, `:`, `@`, `/`, and `?`

This is borne out by JS:
```
encodeURIComponent('{"publicationId":1}')
'%7B%22publicationId%22%3A1%7D'
```
and PHP with `urlencode()` and `rawurlencode()`:
```
var_dump(urlencode('{"publicationId":1}'));
string(29) "%7B%22publicationId%22%3A1%7D"

var_dump(rawurlencode('{"publicationId":1}'));
string(29) "%7B%22publicationId%22%3A1%7D"
```

Both languages also encode the colon though not required by the RFC - I haven't tracked down the logic of that.

**Comment by nicolas-grekas** [comment]
I'm fine to encode curly braces. Up for a PR?

**Comment by pbowyer** [comment]
@nicolas-grekas Sure thing - against which branch should I make the change?

**Comment by nicolas-grekas** [comment]
5.4 please, see https://github.com/symfony/symfony/pull/49580/files for inspiration
