### ISSUE TITLE
[Console] A smiley is displayed when running Symfony's internal tests of Console

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#49584]
### Symfony version(s) affected

5.4

### Description

A smiley is shown when running the tests in `./phpunit src/Symfony/Component/Console/Tests/ApplicationTest.php`:

> ![image](https://user-images.githubusercontent.com/2071331/222465322-6866df92-3731-4a9e-b3d3-38e0c6189fca.png)

It comes from the `testSignalableRestoresStty` test.

### How to reproduce

Input:

```
php ./phpunit src/Symfony/Component/Console/Tests/ApplicationTest.php --filter="testSignalableRestoresStty"
```

Output:

```
PHPUnit 9.6.4 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing Symfony\Component\Console\Tests\ApplicationTest
😊
  [0] y
 > .                                                                   1 / 1 (100%)

Time: 00:00.118, Memory: 12.00 MB

OK (1 test, 2 assertions)
```

### Additional Context

Feel free to close this issue if it's not worth working on it.

**Comment by nicolas-grekas** [comment]
:smiley: 

Not a bug
