### ISSUE TITLE
Allow relevant attributes to be used with constructor property promotion (TARGET_PROPERTY in additiona to TARGET_PARAMETER)

### ISSUE THREAD

**Issue by AndreasA** [symfony/symfony#49605]
### Description

PHP itself does not have an issue with it as the TARGET part of the attribute is actually not verified to avoid class loading during compilation.

However, IDEs might not allow the use of such attributes through auto-completion and provied inspection errors as the attribute used on promoted properties is applied to the constructor and the property.

This is e.g. relevant for the Target attribute, but also taggediterator etc.

See also previous PR https://github.com/symfony/symfony/pull/42051
and comment https://github.com/symfony/symfony/pull/42051#issuecomment-1447710687

### Example

see https://3v4l.org/NvcWA

```php
<?php

#[\Attribute(\Attribute::TARGET_PARAMETER)]
class B {
}

class A {
    public function __construct(#[\B] public string $a)
    {
    }
}

$ins = new \A('abc');

$a = new ReflectionClass($ins);
var_dump(count($a->getConstructor()->getParameters()[0]->getAttributes(\B::class)));
var_dump(count($a->getProperty('a')->getAttributes(\B::class)));
var_dump($a->getProperty('a')->isPromoted());
```

**Comment by derrabus** [comment]
This would basically mean that we never use `\Attribute::TARGET_PARAMETER` or `\Attribute::TARGET_PROPERTY` on their own, but always as `\Attribute::TARGET_PARAMETER | \Attribute::TARGET_PROPERTY`.

Can you please take this topic to PhpStorm again? I understand that the IDE issues some kind of warning, but there should be an option to silence it on promoted properties. Also, autocompletion doesn't work in those cases currently, but it should imho.

**Comment by wouterj** [comment]
Reading https://externals.io/message/111942 , I think PHPstorm should update the message. The advise from PHP internals is to not use constructor property promotion together with attributes and revert to "traditional" parameter + property definitions for those.

In any case, forcing all library maintainers to update their target in user-land doesn't make much sense to me.

Besides that, it actively confuses the main purpose of attributes. E.g. validation constraints like `#[NotBlank]` would then be allowed on all parameters, but validation constraints won't ever be run on parameters.

So 👎 from me to update all attributes in Symfony (or any other library).

**Comment by AndreasA** [comment]
@wouterj There exists a corresponding issue that was created after the initial issue https://youtrack.jetbrains.com/issue/WI-59635/Suggest-to-convert-promoted-property-to-classic-and-move-attribute-to-the-property-in-case-of-applied-attribute-have-only-target

It still makes it a bit annoying to use for certain objects but I also understand your reluctance to change the bevhavior. Personally, I think PHP should adjust to allow property promotion with attributes and only apply them to the corresponding target, but that is probably way more complex to implement without performance impacts.

However, now that you mention NotBlank. I think it is actually more problematic for promoted properties, if property and parameter is supported as the attribute would then be supported by both, so its functionality might actually be applied twice.. But that can also be the expected behavior, which it has to be as that is how PHP is supposed to handle promoted properties in this case.

@derrabus From what I understand about PHP discussions and also as @wouterj mentioned not allowing such attributes on constructor property promotion is actually correct, as those should be converted to traditional parameter + property definitions.

However, I agree it could be an option to switch the corresponding behavior. Especially, as an attribute with target parameter, will only be used as parameter by the library, if it is defined this way. There is also this issue: https://youtrack.jetbrains.com/ssue/WI-55697/Non-applicable-attribute-target-declaration-TARGETPARAMETER-is-marked-as-invalid-for-attribute-for-promoted-property so maybe it will be revisited.

Though I think from how PHP expects it, the conversion option of the issue above makes more sense.

**Comment by AndreasA** [comment]
In any case, it probably makes more sense to wait for PHPstorm (and maybe other IDEs) to change this behavior here as changing the attribute targets in all libraries makes little sense. Personally, I think allowing them to be used in the constructor as long as the attribute targets either property or parameter makes the most sense from an IDE perspective, as the library will then use it for the correct type anyway. And if they only support non promoted properties, there is an option to check for that accordingly in the reflection api.

so I am going to close this issue. the corresponding tickets have been referenced already.
