### ISSUE TITLE
Improve error exception for unsubmitted form

### ISSUE THREAD

**Issue by garak** [symfony/symfony#49619]
### Description

I was helping another Symfony user in a community, he was stuck with a form and he posted the following screenshot

![image](https://user-images.githubusercontent.com/179866/223180904-57843dbb-b435-4135-866c-3d5bde0088bd.png)

So I explained to him the reason for this failure, but then I realized that indeed the exception message is misleading. As we know, it's not sufficient to call the `Form::isSubmitted()` method to ensure that the form is actually submitted.

The message should be changed to something like this: 

>Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() and ensure that it's true before calling Form::isValid().

**Comment by lyrixx** [comment]
You need to write the following code:

```
if ($form->isSubmitted() && $form->isValid());
```

Because it does not make sens to check if the form is valid if it's not submitted

**Comment by garak** [comment]
> You need to write the following code:
> 
> ```
> if ($form->isSubmitted() && $form->isValid());
> ```
> 
> Because it does not make sens to check if the form is valid if it's not submitted

That's exactly the point that the exception message fails to explain.

**Comment by achim7777** [comment]
thank you so much
