### ISSUE TITLE
[Console] Rename the SignalableCommandInterface to SupportsPosixSignalCommandInterface

### ISSUE THREAD

**Issue by nyamsprod** [symfony/symfony#49627]
### Description

Symfony 6.3 will chip with a new interface for handling Posix Signal in the console component.
Currently the new interface is called `SignalableCommandInterface` while I acknowledge that naming things in programming is difficult I find the current name not really DX friendly. 

As suggested by @lyrixx I would propose the following name instead `SupportsPosixSignalCommandInterface`.

```php
class PaymentCommand extends Command implements SignalableCommandInterface
{
}

//vs

class PaymentCommand extends Command implements SupportsPosixSignalCommandInterface
{
}
```

The following name convey clearly the intent of the interface and is easily readable and understandable by developers without having to ask the following question:

- What is a signal ?
- What kind of signal are we referring to ?
- Where can I use this interface ?

Last but not least it reduce the use of the (-able) suffixe which leads often to mistake in interpretation.

**Comment by lyrixx** [comment]
>Symfony 6.3 will chip with a new interface for handling Posix Signal in the console component.

Actually, The interface is here since [5.2](https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/Console/Command/SignalableCommandInterface.php)



And I suggested to contribute *sooner* 😁; Now it's harder to rename.

IMHO it's to late and it does not worth it. But let's wait to see what do others developer think.

**Comment by nyamsprod** [comment]
I understand that. If the ship has already sailed then do close the issue. It was merely a suggestion

**Comment by fabpot** [comment]
I also think it's too late with no big benefit anyway (the new name would be really long).
Let's close.
