### ISSUE TITLE
[Translator] Loading bundle translation from `Resources/translations/validator.nl.yaml` isn't working

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#49631]
### Symfony version(s) affected

5.4.21

### Description

We have a bundle with multiple translations in `Resources/translations/` it looks like the bundle translation is loaded `xBundle.nl.yaml` but the `validators.nl.yaml` isn't loaded. 

Is that because https://github.com/symfony/framework-bundle/blob/6.2/CHANGELOG.md#500 `Removed support to load translation resources from the legacy directories src/Resources/translations/ and src/Resources/<BundleName>/translations/`? (when i include the translation path under `translator ` it works correctly.)

Note in the project i also have a `validators.nl.yaml` but its in a sub folder `/translations/validators.nl.yaml`

Question:
https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations
```
the translations/ directory (at the root of the project);
the translations/ directory inside of any bundle (and also their Resources/translations/ directory, which is no longer recommended for bundles).
```
Isn't it always recommended to place translation in the `translations/` directory?

### How to reproduce

Have a bundle with at least 2 translations in `Resources/translations/` and use it in a project and see that a translation from `validators.nl.yaml` isn't loaded.

**Comment by ghost** [comment]
I confirmed renaming our bundle `validators.nl.yaml` to `xBundleValidators.nl.yaml` made it worked again. So i think the project `validators.nl.yaml` overwritten the bundle even if it was in different folder i dont think that is expected.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
