### ISSUE TITLE
Status of the HttplugClient / Lacking scoped clients integration

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#49644]
### Description

When investigating the usability of the HttpClient symfony package with promises I find myself in a confused spot. There is the HttplugClient which is looking pretty good and itself is not deprecated in any way since multiple major releases.
[Reading the HttpClient documentation ](https://symfony.com/doc/current/http_client.html#httplug) on the other hand indicates it should not be used and is superseded by the PSR18 client
`Http\Client\HttpClient` repeats this impression and points to the PSR18 client. Is the HttplugClient really meant to be replaceable (also out of Symfonys perspective) by the psr client which has no promise support?

I am sorry if this issue ends up in a sort of support case which I surely do not want to open here. I hope to find some clarification for the future of the HttplugClient and how it is intended to be used or not. I am also willing to contribute in documentation improvements if you agree it is in a confusing state.

While I can today just create an instance of the HttplugClient no matter of its future I expected to be able to receive a scoped client by its interface like I can do with Symfonys own HttpClient and also the PsrHttpClient.
It results in the default HttplugClient tho and a look into the output of `debug:container` as well as the FrameworkExtension shows that those are not meant to work together which I really would like to have as a third option.

**Comment by simonberger** [comment]
I tried to enable the missing `HttplugClient` scoped client services in a bundle extension, similar to how it is done with the psr18 client. It could be done surprisingly easy. This is what I wish would be part of Symfony if the promised based client is meant to stay an integrated part.

```php
public function prepend(ContainerBuilder $container): void
{
    $frameworkConfigs = $container->getExtensionConfig('framework');

    $processedScopedClients = [];
    foreach ($frameworkConfigs as $frameworkConfig) {
        if (!isset($frameworkConfig['http_client']['scoped_clients'])) {
            continue;
        }

        foreach($frameworkConfig['http_client']['scoped_clients'] as $scopedClientName => $scopedClient) {
            if (isset($processedScopedClients[$scopedClientName])) {
                continue;
            }
            $processedScopedClients[$scopedClientName] = true;

            $container->setDefinition('httplug.' . $scopedClientName, new ChildDefinition(HttpClient::class))
                ->replaceArgument(0, new Reference($scopedClientName));

            $container->registerAliasForArgument(
                'httplug.' . $scopedClientName,
                HttpAsyncClient::class,
                $scopedClientName
            );
        }
    }
}
```

**Comment by nicolas-grekas** [comment]
If you want to work with promises, `HttplugClient` is the way to go. We encourage using PSR-18 when using the synchronous API.

**Comment by stof** [comment]
Adding support for `HttpAsyncClient` for scoped client is something that could be contributed to FrameworkBundle to have it in 6.3 though.

**Comment by nicolas-grekas** [comment]
I missed that there is no named autowiring alias for them indeed! PR welcome then.

**Comment by simonberger** [comment]
Sounds great. I am happy to create a PR. Shall `HttpAsyncClient` also work as an alias for the existing default `Http\Client\HttpClient`? I was confused anyway just to be able to inject it by this Interface which just points to `ClientInterface` now.

**Comment by nicolas-grekas** [comment]
Would work for me yes.
