### ISSUE TITLE
Can the process component be mocked in version 6? 

### ISSUE THREAD

**Issue by nmeri17** [symfony/symfony#49641]
### Symfony version(s) affected

6.0

### Description

I was working with version 5.4. I had the following class returning a Process object https://github.com/nmeri17/suphle/blob/3a522da6818064f6dbbe4b3571c7a8ea6a2d7898/src/Server/VendorBin.php#L46

In my tests, that method was being mocked, thus phpunit returns a mock process object. All was fine until I upgraded to version 6 last night. Now, when the consumer invokes it, phpunit is simply unable to complete creation of a mock process. The generated class it tries to eval is incorrect so it runs into the syntax error "unexpected static. Expected identifier"

I ultimately got around the obstacle by stubbing setProcessArguments to return `new Process([]);` but I imagine I got away easy cuz the test doesn't actually execute the process ie doesn't require path, actual command. Is this behaviour deliberate? Is there a new alternative to mocking or test doubling the process class? 

### How to reproduce

This is the mocking helper method without my stub returning a fresh Process 

https://github.com/nmeri17/suphle/blob/3a522da6818064f6dbbe4b3571c7a8ea6a2d7898/tests/Integration/Production/ContributorCommandTest.php#L44

**Comment by derrabus** [comment]
> The generated class it tries to eval is incorrect so it runs into the syntax error "unexpected static. Expected identifier"

If PHPUnit generates broken code, we can't do much about it. Please report this issue to PHPUnit.

**Comment by nmeri17** [comment]
> > The generated class it tries to eval is incorrect so it runs into the syntax error "unexpected static. Expected identifier"
> 
> If PHPUnit generates broken code, we can't do much about it. Please report this issue to PHPUnit.

But I didn't update my phpunit. It's still 8.5 and it was able to evaluate process version 5.4. How do I raise a bug with them?

**Comment by derrabus** [comment]
> How do I raise a bug with them?

https://github.com/sebastianbergmann/phpunit/issues

**Comment by nmeri17** [comment]
That's hilarious. I obviously meant "why should I raise an issue with them?". We had two variables: process and phpunit. Of the two, process was updated and the previously stable system was thrown into chaos. If you're the maintainer of that project, will you listen to me? Anyway, it's OK if you aren't interested in looking into it. I hope I never have the need to mock parts of a process object

**Comment by derrabus** [comment]
PHPUnit's mock library is supposed to either generate valid mock code or emit an error that tells you why it isn't able to. Anything else is a bug in that library, it's as simple as that. It might be the case that a code change in Symfony has triggered that bug, but that does not change the fact that this bug has to be addressed in PHPUnit's codebase, not ours. And since you're using an outdated version of PHPUnit, chances are that the error already disappears when you upgrade PHPUnit.
