### ISSUE TITLE
[Console] Terminal::hasSttyAvailable() checks availability of exec but then all calls are made via shell_exec

### ISSUE THREAD

**Issue by Gappa** [symfony/symfony#49646]
### Symfony version(s) affected

6.2.7

### Description

Error message:
- `Error: Call to undefined function Symfony\Component\Console\shell_exec() in /{path_to_project}/vendor/symfony/console/Application.php:989 `
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Application.php#L989

`Terminal:hasSttyAvailable()` checks for availability of `exec`
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Terminal.php#L120-L134

However, all calls inside the condition are then run using `shell_exec` and that fails when it is disabled.
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Application.php#L988-L996

One might argue that it does not make much sense to have one function enabled and the other disabled, but apparently it can happen and then it fails.

Or am I missing something? :)

### How to reproduce

Have a system, that has:
- exec enabled
- shell_exec disabled
- symfony/console installed
- symfony/events installed (otherwise checks for dispatcher fail and a different route in the code is taken that will not manifest the problem)

Then try to run the symfony console from command line. 

### Possible Solution

Either check availability of `shell_exec` in `Terminal::hasSttyAvailable()` or change all calls to use `exec`.

### Additional Context

The check has been introduced here:
- https://github.com/symfony/symfony/pull/37466

**Comment by lyrixx** [comment]
> or change all calls to use `exec`.

But it's the same for `exec`, it can be disabled too, isn't?

**Comment by Gappa** [comment]
> > or change all calls to use `exec`.
> 
> But it's the same for `exec`, it can be disabled too, isn't?

Yes, but in that case `Terminal::hasSttyAvailable()` would not return true, so the subsequent calls would not be run and fail.

The problem with the current approach is that it is checked using `exec` and then actually run using `shell_exec` so it creates a false premise that it works while it ~doesn't~ might not.
