### ISSUE TITLE
Odd data in performance tab of the profiler

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#49677]
### Symfony version(s) affected

>= 5.4

### Description

This profile is strange (RouterListener should span that much). Maybe it's because the listener is throwing?

![image](https://user-images.githubusercontent.com/243674/224777379-1209dfde-8086-49e3-af56-147ceda3e6c9.png)

### How to reproduce

```sh
symfony new test-profiler --version=5.4
cd test-profiler/
composer req profiler
symfony serve
```

Go to https://127.0.0.1:8000/ and open the "Performance tab" in the Profiler Toolbar.

**Comment by MatTheCat** [comment]
Wrapping https://github.com/symfony/symfony/blob/c918829fc57d0e41c1cb0e069ca60aae90183ce4/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php#L115-L119 in `try`/`finally` seems to produce the expected output.

```php
try {
    ($this->optimizedListener ?? $this->listener)($event, $eventName, $dispatcher);
} finally {
    if ($e->isStarted()) {
        $e->stop();
    }
 }
```

![](https://user-images.githubusercontent.com/1898254/225371948-a21acf87-203c-49f9-b73a-4947e9a5092a.png)

**Comment by stof** [comment]
@MatTheCat can you send a PR ?
And maybe also fix other places using the Stopwatch to do the same.

**Comment by MatTheCat** [comment]
I also found https://github.com/symfony/symfony/blob/0362350a720e38df55531ab0cf726a082d3d34d4/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php#L36-L40 and https://github.com/symfony/symfony/blob/0362350a720e38df55531ab0cf726a082d3d34d4/src/Symfony/Component/HttpKernel/Controller/TraceableArgumentResolver.php#L36-L40
