### ISSUE TITLE
[RFC] Flowbite form theme

### ISSUE THREAD

**Issue by ker0x** [symfony/symfony#49698]
### Description

I am currently working on a form theme for [Flowbite](https://flowbite.com/) and I would like to know if you are interested in integrating it as an official theme in Symfony. 

WDYT?

**Comment by xabbuh** [comment]
I have no idea how wide-spread Flowbite is. Is this something that is commonly used nowadays?

**Comment by zoltanszogyenyi** [comment]
Hey @ker0x, @xabbuh,

Flowbite has been [downloaded over 2.5M times on NPM](https://www.npmjs.com/package/flowbite) and it is currently the most widely used UI component library based on Tailwind CSS - we are seeing growth in adoption on a monthly basis.

Cheers,
Zoltan

**Comment by ker0x** [comment]
I'm closing it, as I just release a [Bundle ](https://github.com/talesfromadev/flowbite-bundle) to provide the form theme!
