### ISSUE TITLE
[RFC] AbstractController::noContent(): Response

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#49751]
### Description

Hi,

in #49518 i realized we have 2 ways of handling `null` as a controller result

1) json encode as null + http 200
2) no content + http 204

i figured having a controller utility builtin creates better autocompletion due the use of `$this->...` already

considering #49518, this allows doing:

```php
#[Serialize(201)]
endpoint(): mixed {
    if ($someSpecialCase) {
        return $this->noContent(); // 204
    }

    return $someOtherSpecialCase ? ['data' => true] : null; // 201
}
```

**Comment by derrabus** [comment]
So, your request is basically to add this method to `AbstractController`?

```php
protected function noContent(): Response
{
    return new Response(status: Response::HTTP_NO_CONTENT);
}
```

**Comment by ro0NL** [comment]
correct

**Comment by OskarStark** [comment]
I think we should avoid adding more helpers to the AbstractController and rather document this one liner in the docs, as this is anyway the way to discover this new feature 🤷🏼‍♂️

**Comment by ro0NL** [comment]
well, the AbstractController is already a response factory in disguise, and 204 is a relatively common case :shrug: 

but i understand we're abusing AbstractController its purpose maybe? though i thought its purpose was to act as a HTTP DSL sort of speak

my idea was self-discovery mostly:

> a controller utility builtin creates better autocompletion due the use of $this->... already
