### ISSUE TITLE
In console Env file not loading correctly with 2 instances of the same project in docker

### ISSUE THREAD

**Issue by anthonyL05** [symfony/symfony#49767]
### Symfony version(s) affected

6.2

### Description

For a project i need to run 2 container for the same project with different environment.

But even if the .env is different in both container. The $_ENV in symfony is the same when it come from symfony console .
All work as except in http.

### How to reproduce

declare 2 service of the same symfony app in the docker-compose with different volume
first
    volumes:
      - ./:/var/www/html:rw,cached
second
    volumes:
      - ./:/var/www/html:rw,cached
      - ./.env.1:/var/www/html/.env:rw,cached
      - ./.var_site:/var/www/html/var

This make a different .env in each container and a different var folder for both.

When i look the file in the container the .env file is not the same

But when dump $_ENV in symfony by entering the application by console  i still get the first one in both container.
If you run in http all work as except.

**Comment by MatTheCat** [comment]
I guess the two containers share the same image. Are you sure it isn’t built with some environment variables? DotEnv wouldn’t override them.

If not, could you provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
