### ISSUE TITLE
slow when profiler is disabled

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#49766]
### Symfony version(s) affected

3.4.18

### Description

Hi everybody. Hoping you can help me.

For security reasons, I deactivated the profiler completely from my yml configuration file.
![image](https://user-images.githubusercontent.com/8798254/226904011-fb51bb4d-c6a3-4e45-a4b2-bf67ffd2a9cd.png)

Unfortunately, since I made this modification, my application has become very slow.

I added traces in my controller by noting execution times, with or without profiler.

For example for the construction of the form, I am at 738 ms with the profiler and 6616 ms without the profiler.

I thank you in advance.
Best regards

### How to reproduce

by activating or deactivating the profiler

**Comment by lyrixx** [comment]
Hello,

Symfony 3.4 is is [not maintained anymore](https://symfony.com/releases). I strongly suggest you to upgrade as soon as possible.

Then, the profiler should be used only in dev. It's disabled by default in production environment. IMHO disabling it in all environment doesn't increase the security but it decrease for sure the DX

**Comment by strauss69400** [comment]
I would like to update our application but it takes time to analyze all the impacts. We cannot do this in a few days.

On the other hand, I deactivated the profiler because I am well in a production environment.

Even if this version is no longer maintained, I think that this behavior is not normal and that other people have already encountered this problem.

maybe the profiler activates cache management by default which speeds up processing.

PS : I'm not English so I don't understand abbreviations ;)

**Comment by xabbuh** [comment]
I am going to close here nonetheless as Symfony 3.4 does not receive any fixes. Once you have updated your application to a maintained version and still experience the behaviour we can consider to reopen the issue. Thank you for understanding.
