### ISSUE TITLE
Add tag "container.exclude" to auto-discovered classes excluded wy #[Exclude] / #[When]

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#49764]
Since https://github.com/symfony/symfony/pull/46279, we add the "container.exclude" to auto-discovered classes that are excluded by manual config, but we forgot to add it to classes excluded by those attributes.

Help Wanted :pray:

**Comment by Tiriel** [comment]
Hi, I'd like to give it a try if it's ok!
Just looked through the component and got some ideas.
