### ISSUE TITLE
Fall back to the default completion for shell redirect operators

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#49761]
### Symfony version(s) affected

6.2.x

### Description

Once a Symfony console app gets custom completion it's no longer possible to use default file system completions for redirects. Note that this does not duplicate #43607 because completion for redirects should never be processed by Symfony.

### How to reproduce

```bash
bin/console CMD > # tab, tab
```

### Possible Solution

We can use the same approach as in Systemd project.
https://github.com/systemd/systemd/pull/12089

### Remaining tasks
- [x] Fix Bash completion - #49762
- [x] Fix ZSH completion (native support)
- [x] Fix Fish completion (native support)

**Comment by GromNaN** [comment]
I just tested, zsh and fish natively support this feature. Nothing to add, thanks for the subtasks.
