### ISSUE TITLE
Multi IsGranted

### ISSUE THREAD

**Issue by verticka** [symfony/symfony#49770]
### Description

With the depreciation of ExtraBundle on object security, I can't have several attributes

Example in my use I check that the user has the right role and also the right company

`#[Security('is_granted("ROLE_TECHNICIEN"), message: "Vous devez etre un tech")]`
`#[Security('client.getSociete() == societeService.getSociete()', message: "Ce client qui n'est pas dans votre societe.")]`

The main problem is that it cannot be multiple compared to the old one.

The workaround and to have a generic message.
Why not allow this attribute multiple times?

**Comment by stof** [comment]
the `IsGranted` attribute can be used multiple times
