### ISSUE TITLE
Togo iban validation fails

### ISSUE THREAD

**Issue by ah-ammar** [symfony/symfony#49773]
### Symfony version(s) affected

6.2

### Description

hi all,

i have a problem with the iban validation constraint. it fails to validate an iban from Togo with the following format: **TG**53**TG**0090604310346500400070

### How to reproduce

try to validate this iban: TG53TG0090604310346500400070 (I have a similar iban and I got this from here https://ibanapi.com/country/TG)

**Comment by alamirault** [comment]
In 6.2.7 a patch was merged (https://github.com/symfony/symfony/pull/48998) and now Togo IBAN are supported

https://github.com/symfony/symfony/blob/e95bbe7a73bf0317340766709029a920dd65d5f4/src/Symfony/Component/Validator/Constraints/IbanValidator.php#L154

Can you upgrade to this version if you are not ?

I checked your given IBAN and it is valid with this new version

**Comment by ah-ammar** [comment]
hi alamirault,

thank you for your replay.

I confirm the update has solved my problem.
