### ISSUE TITLE
Postmark Bridge new parameter

### ISSUE THREAD

**Issue by webBook-cz** [symfony/symfony#49777]
### Description

MessageStream is new parameter which supposed to be included for mass emails. Could anybody impement this new parameter to the API connector?
Thanks
https://postmarkapp.com/support/article/1207-how-to-create-and-send-through-message-streams

**Comment by fabpot** [comment]
That's the kind of work that can only be done by people with this need.
Nobody in the core team is maintaining these third-party bridges as it's impossible.

**Comment by PhilETaylor** [comment]
@webBook-cz you could just add the header per email (or [globally](https://symfony.com/doc/current/mailer.html#configuring-emails-globally))  ?

```php
$email = (new Email())
    ->getHeaders()
        ->addTextHeader('X-PM-Message-Stream', '<Your Broadcast Message Stream ID>');
```

**Comment by PhilETaylor** [comment]
@webBook-cz in fact there is already support for this header in the postmark bridge with SMTP

https://github.com/symfony/symfony/blob/83f79bd2f4439627757b7fd177824c1f7bea5763/src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkSmtpTransport.php#L71

And with the Postmark API you can specify the message_stream 

https://github.com/symfony/symfony/blob/83f79bd2f4439627757b7fd177824c1f7bea5763/src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php#L49

So the feature you are asking for is already there :)

**Comment by xabbuh** [comment]
Let's close here then. Thanks for investigating @PhilETaylor!
