### ISSUE TITLE
Edit documentation that splat operator can't be used along with autowiring.

### ISSUE THREAD

**Issue by yashrode774** [symfony/symfony#49780]
### Description

Currently autowiring is not supported for the packed list of arguments, so I have to disable autowiring in that case. Is there already any other way to do this .

### Example

```
public function __construct(protected ComposerInspector $composerInspector, mixed ...$arguments) {
    parent::__construct(...$arguments);
  }
```

For the example above, I used splat operator for `$arguments` which is not supported for autowiring.

**Comment by derrabus** [comment]
What is the result you're getting and what would be the result you're expecting?

**Comment by yashrode774** [comment]
Updater class extends Stage class and the error message is
`ArgumentCountError : Too few arguments to function Drupal\package_manager\Stage::__construct(), 0 passed in /Users/yash.rode/www/auto-updates/modules/contrib/automatic_updates/src/Updater.php on line 30 and exactly 10 expected` and I expect that, $argument should be able to pass on the parameters to Stage::__construct() with packed list of arguments but as autowiring is not supported for splat operator it is not doing that.

**Comment by wouterj** [comment]
Autowiring needs information to know what it has to wire. `mixed ...$arguments` doesn't hold any information (like, which types are expected, how many arguments are expected, etc). I can't see autowiring ever supporting something like that.

Please provide a full minimal reproducer of your use-case + what would be expected, as the current description is quite unclear about how this should actually work.

**Comment by yashrode774** [comment]
In that case it would be great to have that documented to something like: splat operator can't be used with autowiring.

**Comment by wouterj** [comment]
Auto wiring in Symfony is very scoped. In https://symfony.com/doc/current/service_container/autowiring.html, I think we explain quite explicitly in which cases it works, rather than listing all cases where it does not work.

Again, I also still do not understand what behavior would have been expected in your example. Knowing this can help us understanding if we can add it, if we should improve the documentation or if there is nothing to be done.

For example: Would you have expected Symfony to infer the value of `$arguments` based on the types in the parent constructor?

**Comment by ro0NL** [comment]
IIUC it should be possible to provide nothing for the variadic arg during autowiring :thinking: https://3v4l.org/rST30

i believe nullable args that cant be autowired are also skipped

**Comment by derrabus** [comment]
> In that case it would be great to have that documented to something like: splat operator can't be used with autowiring.

Feel free to contribute your proposal here: https://github.com/symfony/symfony-docs/

**Comment by ro0NL** [comment]
just tested 6.2.7 real quick, and i get empty array for variadic arg by default with autowiring ... as expected kinda.

so i believe it works actually :shrug:

**Comment by yashrode774** [comment]
> IIUC it should be possible to provide nothing for the variadic arg during autowiring 🤔 https://3v4l.org/rST30
> 
> i believe nullable args that cant be autowired are also skipped

This does not does not make sense as there is no DI. You just made ...$arg  there is no autowiring used in here unless I miss-understood something.



> `mixed ...$arguments` doesn't hold any information (like, which types are expected

This makes sense, so either this should be supported or documented and about not documenting all cases where it does not work the situation I encounter someone else will encounter again.

I just need to use autowiring and splat operator with mixed type which doesn't seem possible.

**Comment by ro0NL** [comment]
it's probably best to provide a reproducer: https://symfony.com/doc/current/contributing/code/reproducer.html
