### ISSUE TITLE
[Serializer] Support `readonly` classes or classes that use readonly for constructor property promotion

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#49808]
### Description

The Serializer is perfectly capable of deserializing the following object without configuration:
```php
final class CreateUserCommand
{
    private function __construct(
        public string $firstName,
        public string $lastName,
    ) {}
}
```

But as soon as you make the class `readonly` (PHP 8.2 feature) or make the constructor properties `readonly` (PHP 8.1) you'll get an error:

```
Error : Cannot initialize readonly property CreateUserCommand::$firstName from scope Symfony\Component\PropertyAccess\PropertyAccessor
 /Volumes/CS/www/cosmos/vendor/symfony/property-access/PropertyAccessor.php:530
```

```php
final readonly class CreateUserCommand
{
    private function __construct(
        public string $firstName,
        public string $lastName,
    ) {}
}
```

```php
final class CreateUserCommand
{
    private function __construct(
        public readonly string $firstName,
        public readonly string $lastName,
    ) {}
}
```

**Comment by ghost** [comment]
I'm on PHP 8.1 and I write commands that are (de)serialized with `public readonly` promoted constructor properties and it's working fine. Are you sure you somehow didn't mess with the serializer configuration?

**Comment by ruudk** [comment]
Thanks for your reply 😊
I'm not using any Serializer configuration at all. Do you? If so? What are you using? Do you maybe pass `$context`?

**Comment by ghost** [comment]
I've just created a symfony/skeleton:^5.4 project, added symfony/serializer and symfony/property-access and successfully (de)serialized class with readonly properties.

<details>
  <summary>See code</summary>

```php
<?php

namespace App;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Serializer\SerializerInterface;

#[AsCommand(name: 'my-command')]
class MyCommand extends Command
{
    function __construct(
        private SerializerInterface $serializer
    ){
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $a = new A('a', 1);
        $serialized = $this->serializer->serialize($a, 'json');
        dump($serialized);
        $deserialized = $this->serializer->deserialize($serialized, A::class, 'json');
        dump($deserialized);

        return 1;
    }
}

class A {
    function __construct(
        public readonly string $field1,
        public readonly int $field2,
    ) {}
}

```

Output:
```sh
^ "{"field1":"a","field2":1}"
^ App\A^ {#155
  +field1: "a"
  +field2: 1
}
```
</details>

**Comment by kaznovac** [comment]
@ruudk Have you used class inheritance and parent constructor call?

I've described a similar issue here https://github.com/symfony/symfony/issues/49450 (solved by having context ignore the problematic attribute - at not the most intuitive place, somewhere deep in deserialization service...)

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by wouterj** [comment]
For reference, I also encountered a different error using read-only CPP properties that was caused by a seemingly unrelated name converter bug: https://github.com/symfony/symfony/pull/50042

As the ObjectNormalizer falls back to properties when it can't correctly handle a constructor, such bugs went unnoticed until now.
