### ISSUE TITLE
[Tests] Improve the error message when submitForm() can't find the form

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#49826]
### Description

I was creating a test that uses the `submitForm()` method (https://symfony.com/doc/current/testing.html#submitting-forms):

```php
$client->submitForm('Save changes', [
    'form[foo]' => '...',
    'form[bar]' => '...',
]);
```

However, this form didn't have the `Save changes` button (it was a copy-paste mistake).

The problem is that tests showed this error:

```
1) App\Tests\Controller\FooControllerTest::testSomething
InvalidArgumentException: The current node list is empty.
```

I'd like to see a more useful error message. For example:

```
1) App\Tests\Controller\FooControllerTest::testSomething
InvalidArgumentException: The form doesn't contain any button with "Save changes" as its content, id, value or name.
```

**Comment by alamirault** [comment]
I already have this error, and need to dig for understand my problem !
I created #49839 (with your very clear sentence)
