### ISSUE TITLE
Invalid `validator.expression` registration

### ISSUE THREAD

**Issue by Rafikooo** [symfony/symfony#49886]
### Symfony version(s) affected

6.2.8

### Description

The way `validator.expression` is registered has changed, which causes ValidatorException when `Expression` constraint is used:
https://github.com/symfony/framework-bundle/compare/v6.2.7...v6.2.8#diff-51cca25b9f344e04d253bf67d646ddaf82a361541effdf554dce3f6d2080dc66R76-R78

### How to reproduce

1) Create an Expression constraint in the app
2) Perform an action to run validation logic
3) Exception is thrown

### Possible Solution

Remove this method:
https://github.com/symfony/symfony/blob/ff361c83c92b292887e11c7426726bae8b2b5995/src/Symfony/Component/Validator/Constraints/Expression.php#L86-L89

### Additional Context

![image](https://user-images.githubusercontent.com/40125720/229216861-6e345b9c-d05c-4464-91c6-86f25143f0db.png)

**Comment by MatTheCat** [comment]
Guess it comes from https://github.com/symfony/symfony/pull/49850/files#diff-914be488080e8bebbbbaa7acdda66db03c562bbe48c6a02a6d9df232ce8f3960L71

**Comment by parijke** [comment]
Got the same error on entities using expressions on validations. Downgraading to 6.2.7 solves it
