### ISSUE TITLE
Symfony cache conflict with Psr cache

### ISSUE THREAD

**Issue by DorianCoding** [symfony/symfony#49888]
### Symfony version(s) affected

5.4.21+dfsg-1

### Description

With 5.4.21+dfsg-1 version (Debian testing) and Psr cache from apt testing as well (1.0.1-3), I got the following error :

`Got error 'PHP message: PHP Fatal error:  Declaration of Symfony\\Component\\Cache\\CacheItem::get() must be compatible with Psr\\Cache\\CacheItemInterface::get(): mixed in /usr/share/php/Symfony/Component/Cache/CacheItem.php on line 49'`

It seems to be a some-week ago issue so I guess it is caused by one of the last update.

### How to reproduce

I got errors using phpMyAdmin which returns 500 error when accessing a database or editing value and the following error appears on php log. I don't know else to help to reproduce, nothing is my code or my config there.
Cf : https://github.com/phpmyadmin/phpmyadmin/issues/18305

### Possible Solution

Previous versions was not affected by the bug.

**Comment by wouterj** [comment]
We are not maintaining the apt packages. Please report this in the apt bug tracker instead.
