### ISSUE TITLE
[DoctrineBridge] Register multiple `EntityValueResolver`

### ISSUE THREAD

**Issue by franmomu** [symfony/symfony#49905]
### Symfony version(s) affected

6.3.0

### Description

Since [targeted value resolvers](https://github.com/symfony/symfony/pull/48992), [`#[MapEntity]` is associated to `EntityValueResolver`](https://github.com/symfony/symfony/blob/cc7cdf2246ee9a9ee3e9d965c7cf958395dd3bb5/src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php#LL33C2-L33C2).

There will be a conflict when registering multiple services with tag `controller.argument_value_resolver` and `EntityValueResolver` as name (using ORM + MongoDB) and I guess only one would apply.

Reference: https://github.com/doctrine/DoctrineMongoDBBundle/pull/773#discussion_r1148857747

### How to reproduce

Registering two services with tag `controller.argument_value_resolver` and `EntityValueResolver` as name.

**Comment by MatTheCat** [comment]
IIRC what the ORM calls “entities”, the ODM calls “documents” so I’m not sure it would be a good idea to call `EntityValueResolver` a resolver fetching documents :thinking:

**Comment by franmomu** [comment]
> IIRC what the ORM calls “entities”, the ODM calls “documents” 

that is right, but the "entity" name here was supposed to be because DDD: https://github.com/symfony/symfony/pull/43854#discussion_r772312383

**Comment by franmomu** [comment]
Following https://github.com/doctrine/DoctrineMongoDBBundle/pull/773#discussion_r1148886080, should `EntityValueResolver` allow an iterable of `ManagerRegistry` tagged somehow? 

https://github.com/symfony/symfony/blob/a0b1ddb938a32d2ae6008f6d2b5e04819f294caf/src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php#L35

I guess that would mean to register the service in the framework.
