### ISSUE TITLE
[Validator] Expression Constraint error

### ISSUE THREAD

**Issue by Erwui** [symfony/symfony#49910]
### Symfony version(s) affected

6.2.8

### Description

Since 6.2.8 version the constraint "Expression" throw this exception:

`
Symfony\Component\Validator\Exception\ValidatorException: Constraint validator "validator.expression" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Expression".
`

### How to reproduce

Use an `Assert\Expression` in an Entity.
Try to validate an entity with validator->validate()

**Comment by nicolas-grekas** [comment]
This has been fixed by https://github.com/symfony/symfony/pull/49889. You can either wait for 6.2.9 or downgrade symfony/framework-bundle to 6.2.7.

Duplicate of https://github.com/symfony/symfony/issues/49886
