### ISSUE TITLE
Expression validator is totally not funcion because of changes in Symfony\Component\Validator\ContainerConstraintValidatorFactory

### ISSUE THREAD

**Issue by zalesak** [symfony/symfony#49917]
### Symfony version(s) affected

6.2.8

### Description

When you use ExpressionValidator, exception "Constraint validator "validator.expression" does not exist or is not enabled. Check the "validatedBy" method in your constraint class "Symfony\Component\Validator\Constraints\Expression". is throw.

### How to reproduce

Just use ExpressionValidator

### Possible Solution

remove method 
    public function validatedBy(): string
    {
        return 'validator.expression';
    }

from Symfony\Component\Validator\Constraints\Expression

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/issues/49886

**Comment by xabbuh** [comment]
closing as fixed by #49889
