### ISSUE TITLE
[HttpClient] Undefined array key "http_method"

### ISSUE THREAD

**Issue by cleptric** [symfony/symfony#49925]
### Symfony version(s) affected

symfony/http-client v5.4.22 & v6.2.8

### Description

Changes made in https://github.com/symfony/symfony/pull/49796 somehow made our https://github.com/getsentry/sentry-symfony CI break.
Looking at our test setup, I'm not sure what we're missing, but `$this->info['http_method']` seems not to be set.

### How to reproduce

https://github.com/getsentry/sentry-symfony/blob/master/tests/Tracing/HttpClient/TraceableResponseTest.php#L104-L113 is failing with `symfony/http-client v5.4.22||v6.2.8`.

See https://github.com/getsentry/sentry-symfony/actions/runs/4605841353/jobs/8138399269

**Comment by fancyweb** [comment]
Hello @cleptric, thanks for your report. Could you test https://github.com/symfony/symfony/pull/49926 plz?

**Comment by cleptric** [comment]
Looks good to me, thanks!
