### ISSUE TITLE
Updating symfony/rate-limiter to 6.2 causing Not Found class FlockStore from symfony/lock

### ISSUE THREAD

**Issue by aborza** [symfony/symfony#49935]
### Symfony version(s) affected

^6.2

### Description

In **symfony/rate-limiter** 6.2 the dependency **symfony/lock** was moved to **require-dev**: https://github.com/symfony/rate-limiter/compare/v6.1.11...v6.2.0, even thought I have symfony/lock as a dependency on my project I get this error:

![image](https://user-images.githubusercontent.com/8749629/230025688-784b9c87-542e-4a91-a0fd-d6a7f1675aca.png)

The error persist even after I run the `composer require symfony/lock`

### How to reproduce

...

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
