### ISSUE TITLE
*redacted*

### ISSUE THREAD

**Issue by brokenbuddha** [symfony/symfony#49969]
### Symfony version(s) affected

https://symfony.com/doc/current/components/ldap.html

### Description

https://symfony.com/doc/current/components/ldap.html

### How to reproduce

https://symfony.com/doc/current/components/ldap.html

### Possible Solution

https://symfony.com/doc/current/components/ldap.html

### Additional Context

https://symfony.com/doc/current/components/ldap.html

**Comment by stof** [comment]
Closing this issue as this is no bug being reported.

And please stay polite. Interactions are subjects to the [Code of Conduct](https://symfony.com/doc/current/contributing/code_of_conduct/code_of_conduct.html)

**Comment by nicolas-grekas** [comment]
For the record, the user has been blocked from the Symfony organization.
