### ISSUE TITLE
[Cache] Interface "Psr\SimpleCache\CacheInterface" not found

### ISSUE THREAD

**Issue by antikirra** [symfony/symfony#49985]
### Symfony version(s) affected

6.2.8

### Description

When attempting to create an instance of the class Symfony\Component\Cache\Psr16Cache, a fatal error occurs - Psr\SimpleCache\CacheInterface cannot be found.

### How to reproduce

$ php -v
```
PHP 8.2.4 (cli) (built: Mar 16 2023 16:46:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies

```
cat composer.json
```json
{
    "require": {
        "php": "^8",
        "symfony/cache": "^6.2"
    }
}
```
cat index.php
```php
<?php

use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Component\Cache\Psr16Cache;

require __DIR__ . '/vendor/autoload.php';

$cache = new Psr16Cache(new FilesystemAdapter(directory: __DIR__));
```
ouptut:
```
PHP Fatal error:  Uncaught Error: Interface "Psr\SimpleCache\CacheInterface" not found in /Users/antikirra/PhpstormProjects/test/vendor/symfony/cache/Psr16Cache.php:27
Stack trace:
#0 /Users/antikirra/PhpstormProjects/test/vendor/composer/ClassLoader.php(582): include()
#1 /Users/antikirra/PhpstormProjects/test/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/antikirr...')
#2 /Users/antikirra/PhpstormProjects/test/inedx.php(8): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 {main}
  thrown in /Users/antikirra/PhpstormProjects/test/vendor/symfony/cache/Psr16Cache.php on line 27

```

### Possible Solution

In the Symfony\Component\Cache\Psr16Cache class, the Psr\SimpleCache\CacheInterface declaration is featured in the use section (https://github.com/symfony/cache/blob/6.2/Psr16Cache.php#L17). However, the Psr\SimpleCache\CacheInterface class is missing in the dependencies. According to community conventions (which I am not an expert in), it is necessary to explicitly declare psr/simple-cache as an explicit dependency of the package.

**Comment by wouterj** [comment]
Hi! 

`psr/cache` is a so-called optional dependency of the component. E.g. you can also use the cache component with the `symfony/cache-contracts` interface, which doesn't require PSR 16.

For these dependencies, we require users of the components to require the package if they would like to use the PSR 16 adapter.
