### ISSUE TITLE
Tag autoconfiguration does not work after calling load() method

### ISSUE THREAD

**Issue by jokaorgua** [symfony/symfony#49988]
### Symfony version(s) affected

6.2.7

### Description

https://symfony.com/doc/current/service_container/tags.html - here it is described how to autoconfigure tags.

In services.php we could have 

```php
$services->instanceof(CustomInterface::class)
        ->tag('app.custom_tag');
```

Everything is ok

But if before that code will be like this

```php
$services->load('\\App','../src/*');

$services->instanceof(CustomInterface::class)
        ->tag('app.custom_tag');
```

we will not see tagged classes through bin/console `debug:container --tag=app.custom_tag`

if this is an expected behavior this should be written in docs. I guess.

### How to reproduce

just call load before setting a tag
```
$services->load('\App','..//src/*');

$services->instanceof(CustomInterface::class)
        ->tag('app.custom_tag');
```

**Comment by nicolas-grekas** [comment]
This might be expected. Can you try this instead?

```php

$services = $services->instanceof(CustomInterface::class)
        ->tag('app.custom_tag');

$services->load('\App','..//src/*');
```

This would need a fix to the doc.

**Comment by jokaorgua** [comment]
@nicolas-grekas 

your example works without `$services =` because tags are applied before the load

and this does not fix the problem described in issue

**Comment by javiereguiluz** [comment]
Closing as fixed in the docs: https://github.com/symfony/symfony-docs/pull/18346
