### ISSUE TITLE
[Routing] Allow using invokable controller's FQCN (i.e. `::class`) to generate URLs (instead of route name)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#49981]
### Description

With the advent of invokable controllers, it would be possible to move away from using names (i.e. strings) as route idenfifiers, and use the controller's FQCN instead:
```php
#[Route(path: '/some')]
final class SomeController
{
    public function __invoke(): Response
    {
        // ...
    }
}
```
Then in any service:
```php
$this->router->generate(SomeController::class);
```
Twig:
```twig
{{ path('App\\Controller\\SomeController') }}
```

Advantage: No more strings! :-)

I got the idea from https://tomasvotruba.com/blog/to-route-or-to-action-thats-the-question which says that this is  possible in Laravel:
> It allows using the controller directly instead of a middleman string:
> +`<form action="{{ action(\App\Controllers\ProcessPhpFormController::class) }}" method="post">`

**Comment by derrabus** [comment]
I like the idea. However, we currently generate a name for routes already, if the name property is omitted. Silently changing the strategy how that name is generated would be a BC break.

**Comment by ro0NL** [comment]
https://symfony.com/blog/new-in-symfony-5-4-route-aliasing#deprecating-routes :eyes:

**Comment by nicolas-grekas** [comment]
Not sure I would deprecate the currently generated name, but why not create an alias indeed.
This would work only for invokable controllers.
