### ISSUE TITLE
[HttpClient] Allow configure a Mock Response Factory for a specific HTTPClient

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony#49995]
### Description

Following https://github.com/symfony/symfony/pull/35893, which brings the possibility to configure a Mock Response Factory for all HTTP Clients of an application at once, we could consider to allow to set a Response Factory by default on each HTTP Client, in `test` env only.

We could decorate every HTTP Client by default, with a `MockHttpClient`. Then, we will be able to do something like:

```php
self::getContainer->get('my.client')->setResponseFactory(fn () => new MockResponse);
self::getContainer->get('my.other.client')->setResponseFactory(fn () => new MockResponse);
self::getContainer->get('my.third.client')->request('GET', ....): // Here, we use the real client
```

It could be useful in case of need to mock only a particular HTTP Client, and leave the other ones making real HTTP requests. In my case, I use https://github.com/stoplightio/prism to serve mocked APIs, which are consumed by real HTTP Client in my app. But for some particular use cases, I need to mock the HTTP Client itself.

cc @lyrixx @nicolas-grekas

**Comment by tarjei** [comment]
I would like to point out that not having this feature actually is a regression from 5.4 where that is possible. 

From a description I wrote up for a question regarding this in the symfony slack channel:

Hi, I got two Symfony apps, one running 5.4 and one running 6.2.In the 5.4 app, I got a http client configured like this:
```

framework:
  http_client:
    scoped_clients:
      intercomhttpUsClient:
        base_uri: 'https://api.intercom.io/'


```

And in packages/test/http_clients.yaml

```
services:
  intercomhttpUsClient:
    class: Symfony\Component\HttpClient\MockHttpClient
```

This works very nicely. I can configure a response factory for this client without regarding the other clients:

```
$intercomUsClient = self::getContainer()->get('intercomhttpUsClient');
```

But,  if I ty this in the 6.2 app: the client I get back is not a MockHttpClient BUT a UriTemplateHttpClient which I cannot do anything with.So, what should I do to get the 5.4 behaviour?

**Comment by welcoMattic** [comment]
@tarjei thanks for your comment here. What you describe seems to be a real bug, can you open a dedicated issue about it?

About the feature I suggested, I think it's a very rare edge case, and it could be bypassed once the bug mentioned just above will be fixed.

I'm closing the issue until we have a real need to improve this part.
