### ISSUE TITLE
[messenger] sqs authentification fail 403 if secret key have special character

### ISSUE THREAD

**Issue by Spawnrad** [symfony/symfony#50014]
### Symfony version(s) affected

5.4.22

### Description

When you have a special character in the credidential of aws.
Example:  secret_key=xxxxxxxxxx+x

The authentification fail with a 403

### How to reproduce

Just add a special character on the secre_key 

### Possible Solution

bug come from : Connection.php File and the public static function fromDsn

```
        $query = [];
        if (isset($parsedUrl['query'])) {
            parse_str($parsedUrl['query'], $query);
        }
```

parse_str remove the special character on the query

**Comment by valtzu** [comment]
I don't think it's a bug. DSN is a URI so you should encode special characters. `+` is `%2B` so your example would be `secret_key=xxxxxxxxxx%2Bx`.

**Comment by xabbuh** [comment]
closing here as explained by @valtzu
