### ISSUE TITLE
Cache not cleared with some Redis client

### ISSUE THREAD

**Issue by Grafikart** [symfony/symfony#50026]
### Symfony version(s) affected

6.X

### Description

On my application the cache was not cleared when using the `cache:clear` console command or `clear()` method on the `CacheItemPoolInterface`.

When inspecting the problem a bit deeper I noticed that Redis was only clearing the first 1000 keys. I was able to track down the problem to these lines https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Cache/Traits/RedisTrait.php#L453-L467. 
In my case `$host` was an instance of [Redis5Proxy](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Cache/Traits/Redis5Proxy.php) (it seems to be injected automatically by Symfony) that returns the list of key when scan is called.

```php
// $keys when scan() is called on a PredisClient
$keys = [
    0 => '1234',
    1 => [
        'cache_key:1',
        'cache_key:2',
        'cache_key:3',
        'cache_key:4',
    ]
];

// $keys when scan() is called on a Redix5Proxy
$keys = [
    'cache_key:1',
    'cache_key:2',
    'cache_key:3',
    'cache_key:4',
]
``` 

Since the keys are not what is expected by the system, the `doClear()` method ends up cleaning only the first 1000 keys.

### How to reproduce

To reproduce the problem you would need a redis runing, where you insert more than 1000 keys (I did it using the Cache) 

In the cache.yaml

```php
framework:
  cache:
    app: app.cache.adapter.redis
    prefix_seed: mysite
    default_redis_provider: '%env(resolve:REDIS_URL)%'
    pools:
      view_cache_pool:
        default_lifetime: '7 days'

services:
  app.cache.adapter.redis:
    parent: 'cache.adapter.redis'
    arguments:
      $defaultLifetime: 604800
    tags:
      - { name: 'cache.pool', namespace: 'site_cache' }
```

Then a simple controller should work

```php
<?php

namespace App\Http\Admin\Controller;

use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\Routing\Annotation\Route;

class CacheController extends BaseController
{
    #[Route(path: '/cache/clean', name: 'cache_clean', methods: ['GET'])]
    public function clean(CacheItemPoolInterface $cache)
    {
       for ($i = 0; $i < 3000; $i++) {
          $item = $cache->getItem("demo{$i}");
          $item->set("demo{$i}");
          $cache->save($item);
       }
       $cache->clear(); // Will only clear 1000 first items
    }
}
````

### Possible Solution

I see 2 possible solution at the moment : 

- throw an error the host is Redis5Proxy or a class that doesn't work as expected
- Handle the case where we have no cursor. We could delete all the keys until keys array is empty ? But I don't know if there are possible side effects (risk of infinite loop)

**Comment by nicolas-grekas** [comment]
Can you please ensure that you're using the latest 6.2?
If yes, can you please try with the patch from PR #50086?

**Comment by Grafikart** [comment]
Sorry for the delay

- Yes it happened on the latest 6.2 (it seems to have appeared with the 6.2 version)
- With the patch, keys seems to be cleared correctly
- The patch doesn't seem to affect the dependency injection, I still end up with the Redis5Proxy instead of the Predis interface configured for "Redis".

```yaml
  Redis:
    class: \Predis\Client
    arguments:
      - '%env(REDIS_URL)%'
```

Maybe this happens cause the Proxy now extends \Redis and is considered a viable choice for the dependency injection.

**Comment by nicolas-grekas** [comment]
> With the patch, keys seems to be cleared correctly

Ok cool, so we can close this issue right?
The redis ext. is preferred when it's available yes.

**Comment by Grafikart** [comment]
Ok closing, injecting the service explicitly is preferable anyway
