### ISSUE TITLE
[Workflow] Custom service for Marking Store not taken into account for State Machine

### ISSUE THREAD

**Issue by kilianklein** [symfony/symfony#50021]
### Symfony version(s) affected

6.2

### Description

Hi everyone, thanks for the awesome component, just started playing with it and it actually made me happy, especially with the nice image dump functionality.

While playing with it, I have been trying to implement a way to use Backed enums instead of strings for Places as my Entity class is expecting those for its status property. (I have seen the feature request about using Enums and understand why this won't be officially implemented at least for now. However in my own project, I can make sure to follow certain rules that make this work for my particular case).

I am very close to making this work, however, when I try to apply a valid transition, I get stuck on MethodMarkingStore line 69:
`$marking = [(string) $marking => 1];`

This obviously breaks because a string cast on a backed enum case does not return its string value. To get around that, I created my own custom MarkingStore replacing this line to:
`$marking = [(string) $marking->value => 1];`

I changed the workflow configuration (I use PHP config to avoid handling textual references) to use my custom MarkingStore as such:
`$workflowConfig->markingStore()
            ->service(MethodMarkingStoreUsingBackedEnum::class)
            ->type('method')
            ->property($workflow->getEntityField());`

Surprisingly, the state machine does not use the custom MarkingStore but keeps on using the MethodMarkingStore as I get the exact same error pointing at the same line.

I also tried to define a service for it in services.yml and to call the alias in the service() method but without any luck.

Am I doing something wrong?

This is no emergency of course, I can always modify my entities to not use Enums, but I sort of love the idea of it. 

Thanks in advance!

PS: I saw a similar issue regarding the "property" value for state machines, but no mention of the  "service" value there, so I thought I'd raise a new issue with a similar name.

Kilian.

### How to reproduce

1- Define a state machine in the workflow config using the php config style
2- Create a CustomMarkingStore service implementing MarkingStoreInterface
3- Set the created state machine's marking store's service to "CustomMarkingStore::class"
4- Check which MarkingStore is being used

**Comment by lyrixx** [comment]
Hello. This is very strange, it should work. Can you create a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) ?

Thanks

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
