### ISSUE TITLE
[HttpClient] `HttplugClient` class implements `Http\Client\HttpClient` that is deprecated since version 2.4, use `Psr\Http\Client\ClientInterface` instead

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#50035]
### Symfony version(s) affected

6.2.7

### Description

After trying to upgrade the following:

| Prod Packages                                                           | Operation | Base   | Target | Link                                                                         |
|-------------------------------------------------------------------------|-----------|--------|--------|------------------------------------------------------------------------------|
| [php-http/client-common](https://github.com/php-http/client-common)     | Upgraded  | 2.6.0  | 2.6.1  | [Compare](https://github.com/php-http/client-common/compare/2.6.0..2.6.1)    |
| [php-http/httplug](https://github.com/php-http/httplug)                 | Upgraded  | 2.3.0  | 2.4.0  | [Compare](https://github.com/php-http/httplug/compare/2.3.0..2.4.0)          |
| [php-http/message](https://github.com/php-http/message)                 | Upgraded  | 1.13.0 | 1.14.0 | [Compare](https://github.com/php-http/message/compare/1.13.0..1.14.0)        |
| [php-http/message-factory](https://github.com/php-http/message-factory) | Upgraded  | v1.0.2 | 1.1.0  | [Compare](https://github.com/php-http/message-factory/compare/v1.0.2..1.1.0) |

I notice these deprecations in my tests:

```
  1x: The "Symfony\Component\HttpClient\HttplugClient" class implements "Http\Client\HttpClient" that is deprecated since version 2.4, use Psr\Http\Client\ClientInterface instead; see https://www.php-fig.org/psr/psr-18/.

  1x: The "Symfony\Component\HttpClient\HttplugClient" class implements "Http\Message\RequestFactory" that is deprecated since version 1.1, use Psr\Http\Message\RequestFactoryInterface instead.

  1x: The "Symfony\Component\HttpClient\HttplugClient" class implements "Http\Message\StreamFactory" that is deprecated since version 1.1, use Psr\Http\Message\StreamFactoryInterface instead.

  1x: The "Symfony\Component\HttpClient\HttplugClient" class implements "Http\Message\UriFactory" that is deprecated since version 1.1, use Psr\Http\Message\UriFactoryInterface instead.

```

### How to reproduce

See composer requirements above.

**Comment by simonberger** [comment]
Appreciated change by the php-http package. Thank you Nicolas.

To enable consumers to fix the deprecation warning in a BC free path while keeping the `HttpAsyncClient` ability of the `HttplugClient` (which I hope is a goal), the class would need to be  "duplicated" and cut by its interfaces, right?

As the services of `HttpAsyncClient` are not yet in any release, they could point to something like `HttplugAsyncClient`
