### ISSUE TITLE
The <bind> tag does not support inner collections

### ISSUE THREAD

**Issue by zerustech** [symfony/symfony#50046]
### Symfony version(s) affected

6.2.0

### Description

The inner collection in the following code snippet is ignored:
```xml
<bind key="$foo" type="collection">
    <bind key="inner-collection" type="collection">
       <argument>item-1</argument>
       <argument>item-2</argument>
    </bind>
</bind>
```

### How to reproduce

Bind a variable `$foo` with the following code snippet in a container configuration file, and try to dump this variable in a controller, the inner collection will be empty:

```xml
<bind key="$foo" type="collection">
    <bind key="inner-collection" type="collection">
       <argument>item-1</argument>
       <argument>item-2</argument>
    </bind>
</bind>
```

### Possible Solution

Change `Symfony\Component\DependencyInjection\Loader\XmlFileLoader` as follows:

```diff
                 case 'collection': 
-                    $arguments[$key] = $this->getArgumentsAsPhp($arg, $name, $file);
+                    $argumentName = 'bind' === $arg->parentNode->nodeName ? 'argument' : $name;
+                    $arguments[$key] = $this->getArgumentsAsPhp($arg, $argumentName, $file);
```

**Comment by nicolas-grekas** [comment]
Does it work if you go with this?

```xml
<bind key="$foo" type="collection">
    <bind key="inner-collection" type="collection">
       <bind>item-1</bind>
       <bind>item-2</bind>
    </bind>
</bind>
```

**Comment by zerustech** [comment]
> Does it work if you go with this?
> 
> ```
> <bind key="$foo" type="collection">
>     <bind key="inner-collection" type="collection">
>        <bind>item-1</bind>
>        <bind>item-2</bind>
>     </bind>
> </bind>
> ```

No, it won't work, because the second `bind` tag is an argument, so, it is not allowed to contain a `bind` tag.

**Comment by zerustech** [comment]
> Does it work if you go with this?
> 
> ```
> <bind key="$foo" type="collection">
>     <bind key="inner-collection" type="collection">
>        <bind>item-1</bind>
>        <bind>item-2</bind>
>     </bind>
> </bind>
> ```

You can check the node types of `bind`, and `argument` nodes in `services-1.0.xsd`

**Comment by nicolas-grekas** [comment]
OK, got it thanks.
That line is wrong to me:
`<xsd:element name="bind" type="argument" minOccurs="0" maxOccurs="unbounded" />`
it should be
`<xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />`

In order not to break BC, let's add the new line after the existing one and adapt the code to read from both tags, and include your fix?
Can you please send a PR doing so, with test cases?
