### ISSUE TITLE
Update the value of Symfony user agent identifiers

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#50052]
### Description

I was checking this PHP PR: https://github.com/php/php-src/pull/11093 and I realized that in Symfony we have the opposite problem. Instead of "server software", we define the "client software" via the User Agent in several components.

The User Agent format is defined in RFC 9110: https://www.rfc-editor.org/rfc/rfc9110.html#name-user-agent

```
User-Agent = product *( RWS ( product / comment ) )
```

And:

```
product         = token ["/" product-version]
product-version = token
```

And a `token` in this context is:

```
Tokens are short textual identifiers that do not include whitespace or delimiters.

  token          = 1*tchar

  tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                 / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                 / DIGIT / ALPHA
                 ; any VCHAR, except delimiters
```

So, user agents can omit the version if they want, but the identifier can't contain spaces.

-----

That's why I think we should update these user agents:

(1) Rename this one as `SymfonyBrowserKit` ?

https://github.com/symfony/symfony/blob/660ce127f3482ea1fe19a8c768b314f957f68c5a/src/Symfony/Component/BrowserKit/AbstractBrowser.php#L135

(2) Rename this one as `SymfonyHttpClient (Amp)` ?

https://github.com/symfony/symfony/blob/660ce127f3482ea1fe19a8c768b314f957f68c5a/src/Symfony/Component/HttpClient/AmpHttpClient.php#L101

(3) Rename this one as `SymfonyHttpClient (Curl)` ?

https://github.com/symfony/symfony/blob/660ce127f3482ea1fe19a8c768b314f957f68c5a/src/Symfony/Component/HttpClient/CurlHttpClient.php#L96

(4) Rename this one as `SymfonyHttpClient (Native)` ?

https://github.com/symfony/symfony/blob/660ce127f3482ea1fe19a8c768b314f957f68c5a/src/Symfony/Component/HttpClient/NativeHttpClient.php#L194

Thanks

**Comment by nicolas-grekas** [comment]
Yes, let's do these changes. Can you please send a PR?
