### ISSUE TITLE
[Process] STDIN/STDOUT/STDERR with PhpProcess

### ISSUE THREAD

**Issue by jhdxr** [symfony/symfony#50063]
### Symfony version(s) affected

6.3.x-dev

### Description

`PhpProcess` is using STDIN to feed the script, which makes STDIN/STDOUT/STDERR are not availble (see php/php-src#11104)

Note: it's tested with `6.3.x-dev` but it should be reproducible with old versions like `5.4.x` as well

### How to reproduce

```php
<?php

include './vendor/autoload.php';
use Symfony\Component\Process\PhpProcess;

$process = new PhpProcess(<<<PHP
<?php
var_dump(php_sapi_name());
var_dump(STDOUT);

PHP
);
```

### Possible Solution

Create a temporary script before running, just following what are done for phpdbg (https://github.com/symfony/process/blob/6.2/PhpProcess.php#L43-L47),

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/50545#issuecomment-1625003247
