### ISSUE TITLE
[Process] Process component unable to locate binary on Mac OS

### ISSUE THREAD

**Issue by nmeri17** [symfony/symfony#50100]
### Symfony version(s) affected

6.0

### Description

I have a command using Process under the hood. I tested on Windows both through the terminal and PHPUnit, everything runs successfully. After publishing, a friend reports the same command fails with `exec: psalter: not found`, `psalter` being the underlying binary the command is trying to execute.

We checked the paths received by the process component and all corresponds to file system. The psalter binary is physically there and executable manually on the mac. But for unknown reasons, it remains invisible to Process

### How to reproduce

Please see https://suphle.com/docs/v1/quick-start/#verifying-project-initialization. That command points to this class https://github.com/nmeri17/suphle/blob/b35335942b13ff004744c2599e4ec4a5713257f7/src/Server/PsalmWrapper.php. You can inspect paths and values passed to the process component through calls made to `$this->vendorBin` on that class

**Comment by nmeri17** [comment]
@derrabus @wouterj do you need any help reproducing?

**Comment by xabbuh** [comment]
Can you debug the actual command that is being executed by the Process component? Are you able to run that without the component?

**Comment by nmeri17** [comment]
> Can you debug the actual command that is being executed by the Process component?

From the terminal, yes. I noted that in the OP

**Comment by xabbuh** [comment]
So the actual command that is tried to be executed is simply `psalter`? No extra arguments etc.? What happens if you try to execute it using the `Process` component without any other code around? If that also does not work, can you please create a small example application that allows to reproduce the issue?

**Comment by nmeri17** [comment]
There's an extra argument. The psalter command needs a flag containing issues to fix

Sorry I wasn't able to respond earlier. The developer who reported the issue hasn't been disposed to test the process class in isolation. I also cannot write the script, as I have no mac. He says he will be available before the week runs out. But I wish issue was debugged from the framework code itself. Why does it work on Windows flawlessly but not on a mac? Will also help to determine whether it's just his or a general problem

**Comment by nmeri17** [comment]
@xabbuh I can confirm issue is consistent on Mac, without suphle. Steps to reproduce:

1. create a new project
1. Init composer 
1. install symfony process and vimeo/psalm
1. create a new file "save.php" and write the following contents

```php

require __DIR__. "/vendor/autoload.php";

use Symfony\Component\Process\{Process, Exception\ProcessFailedException;

$process = new Process(
            ["psalter"], 
            "./vendor/bin" 
        );

$process->run();

// executes after the command finishes
if (!$process->isSuccessful()) {
    throw new ProcessFailedException($process);
}

echo $process->getOutput();
```

It throws the same exception from the op

**Comment by xabbuh** [comment]
I don't know why that's the case, but after debugging this a bit it seems that `proc_open()` complete ignores the working directory being passed. You can work around this by passing the absolute path to `psalter` instead:

```php
$process = new Process([__DIR__ . "/vendor/bin/psalter"]);
```

**Comment by stof** [comment]
I think there is a confusion here between the working directory and the PATH. On unix system, executables are not resolved in the cwd (to run a local executable, you must use a relative path like `./psalter`). Executables like `psalter` are only resolved against $PATH.

**Comment by nmeri17** [comment]
OK, I will update and instruct him to check again @xabbuh

@stof is it possible to use one consistent across OSes? Because apparently, Windows doesn't discriminate between path and cwd

**Comment by xabbuh** [comment]
I guess we can close here since this works when the binary to be executed is located inside the `$PATH` or an absolute path is given?

**Comment by nmeri17** [comment]
I don't know whether he is still interested in testing my framework. I don't know anyone else running it mac. You can close it, I guess.
