### ISSUE TITLE
[ErrorHandler][WebProfilerBundle] Logs filter no longer appears on exception pages

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#50108]
### Symfony version(s) affected

≥ 5.4

### Description

Since #42195 the UI of logs changed between the profiler and the exception page so `createFilters` was removed from `base_js.html.twig`’s `Sfjs`.

`exception.js` also defines its own `Sfjs` with a `createFilters` method it calls on `DOMContentLoaded`.

Problem is, `base_js.html.twig`’s `Sfjs` overrides `exception.js`’ one because the latter does not define `loadToolbar`.

As a result, when `DOMContentLoaded` kicks in, `Sfjs.createFilters` is called while it does not exist anymore so an error is logged and filters don’t work.

> Uncaught TypeError: Sfjs.createFilters is not a function

Else, the UI would look like this on exception pages:

![](https://user-images.githubusercontent.com/1898254/233687571-5cb7fb67-c957-449e-ae6f-9059961d1e8e.png)

### How to reproduce

Display the `ErrorHandler`’s exception page with some logs and the profiler’s toolbar enabled.

### Possible Solution

Not sure about this. The fact the web profiler and error handler can override each other’s `Sfjs` seems weird.

---

Also, remnants of `Sfjs.createFilters` are still present in `translation.html.twig`.

**Comment by stof** [comment]
We should probably use a different variable for the JS code of the error page

**Comment by MatTheCat** [comment]
Wouldn’t that be a BC break?

**Comment by stof** [comment]
Well, renaming the one in the profiler would be. But the exception page is not extensible, so this one could be renamed without BC impact.

**Comment by MatTheCat** [comment]
> the exception page is not extensible

Nice! As it does not use `Sfjs` that means it does not need to be exposed.
