### ISSUE TITLE
[Routing] [RFC] Add content-type for Route class

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#50118]
### Description

Symfony >= 6.3

The idea is to add the possibility to check the content-type easily to match a route.

Currently, a route looks like this :

```php
#[Route('/blog', name: 'blog_list')]
public function list(): Response
{
    // ...
}
```

If we want to restrict to JSON format and keep the route "/blog", we can use the condition attribute of the Route class with something like this : 
```php
#[Route(
    '/blog', 
    name: 'blog_list', 
    condition: "request->getContentTypeFormat() === 'json'"
)
```

To facilitate the development for all and in particular with this type of condition that is increasingly used.

New implemented feature would look like this:

```php
#[Route('/blog', name: 'blog_list', content-types: ['json'])]
public function list(): Response
{
    // ...
}
```

Other content-type available with $request->getContentTypeFormat() will be available.

### Example

```php
#[Route('/blog', name: 'blog_list', content-types: ['json'])]
public function list(): Response
{
    // ...
}
```

I will post a PR if this RFC is accepted.

cc @nicolas-grekas @wouterj @fabpot @lyrixx

**Comment by ro0NL** [comment]
maybe call it `accept: ['json', 'my/cool-type']` to avoid confusion whether the route accepts or produces json

also, IIUC, this allows narrowing down a mounted route prefix?

**Comment by AurelienPillevesse** [comment]
Of course the name `content-types` is not final, the name can be changed to make it relevant for everyone. `accept` can be a good idea if people agree with that

**Comment by WebMamba** [comment]
And what about having different content types with different weights?

**Comment by wouterj** [comment]
You can already achieve this using [route expressions](https://symfony.com/doc/current/routing.html#matching-expressions):

```php
#[Route('/blog', name: 'blog_list', expression: 'request.getContentTypeFormat() == "json"')]
public function list(): Response
{
    // ...
}
```

I don't think this feature is common enough that we want to add an explicit option for it.

**Comment by AurelienPillevesse** [comment]
This is what I explained in my initial comment, it is possible to do it via the `symfony/expression-language` package.

But if we use this package only for this point, it removes the need to use this package for this simple case and opens the possibility in the future to cache this data for more speed in the matching route process (and configuration will be easier for everyone).

For me, the check on 'content-type' of the route is as important as controlling the HTTP verb (GET/POST) to democratize the security of applications developed with Symfony.

**Comment by AurelienPillevesse** [comment]
Can I submit a PR about this feature with `accept` parameter ? @nicolas-grekas

**Comment by mbabker** [comment]
I'm personally not convinced.  These are the types of checks I'd do in a controller and kick back a 4xx range response (i.e. the 415 code is meant for the exact scenario you're describing).  Having that type of condition in the router and sending back a 404 response IMO is the wrong way of handling this type of check.

**Comment by ro0NL** [comment]
It's still a form of routing IMHO; the router is free to throw any 4xx error

My main purpose would be to mass import json only routes, thus defined at the mount level
