### ISSUE TITLE
Use FormType::class for the AbstractController::createForm function.

### ISSUE THREAD

**Issue by laurentmuller** [symfony/symfony#50122]
### Description

The `AbstractController::createForm` has the following signature:

```php
protected function createForm(string $type, mixed $data = null, array $options = []): FormInterface
{
}
```

But if You go to the implementation, it use the `FormFactory::create` function with the following signature:.

```php
public function create(string $type = FormType::class, mixed $data = null, array $options = []): FormInterface
{
}
```

So we can maybe update the signature of the controller to use the same parameters:

```php
protected function createForm(string $type = FormType::class, mixed $data = null, array $options = []): FormInterface
{
}
```

### Example

We can now call this function without parameter:

```php
class MyController extends AbstractController
{
    public function edit()
    {
        $form = $this->createForm();
    }
}
```

**Comment by stof** [comment]
Creating a form with FormType::class without using the form builder does not seem like a common usage that would benefit from the argument optional. This would create an empty form (except the CSRF token that gets injected automatically).

**Comment by laurentmuller** [comment]
You are right. But I use, for example, the default value (`FormType::class`) when I want to display a confirmation message.

**Comment by stof** [comment]
But for that case, it is still fine to use an explicit argument IMO (which will also make the intent of the code clearer).

If we were to harmonize both APIs, I would rather deprecate calling `FormFactory::create` without arguments. But I don't think this deprecation is worth it (there is no maintenance cost about keeping the current code)

**Comment by laurentmuller** [comment]
Ok. So I will update my code and close this issue
Thank You for your prompt answer.
