### ISSUE TITLE
[Intl] nl language can be represented as dut and nld

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#50142]
### Symfony version(s) affected

6.1.4

### Description

Found an issue with ISO-3 alias

ER:
ISO-3 dut
ISO-2 nl

AR:
Couldn't read the indices [Alpha3ToAlpha2][dut] for the locale "meta" 

https://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=dut&SearchType=ALL
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

### How to reproduce

1. install symfony/intl
2. 
```
Languages::getAlpha2Code('dut')
```

**Comment by ro0NL** [comment]
the reverse mapping needs to be preserved in https://github.com/symfony/symfony/blob/55a38a8e5e129f5e46568d2b7e341a73d1abbcba/src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php#L161

**Comment by oleg-andreyev** [comment]
recently found one more case

```
Couldn't read the indices [Alpha3ToAlpha2][fre] for the locale "meta"
```

https://www.loc.gov/standards/iso639-2/php/English_list.php

and `fre` stand for French same as `fra`

**Comment by oleg-andreyev** [comment]
https://unicode-org.atlassian.net/browse/ICU-12660

**Comment by oleg-andreyev** [comment]
https://github.com/unicode-org/icu/blob/main/icu4c/source/data/misc/metadata.txt
https://unicode-org.atlassian.net/browse/CLDR-3413
