### ISSUE TITLE
Symfony/mailer makes invalid assumptions about SSL/TLS vs STARTTLS - unable to submit pull request

### ISSUE THREAD

**Issue by ShamimIslam** [symfony/symfony#50150]
### Symfony version(s) affected

master

### Description

Hi.

The current symfony/mailer assumes that encryption is the result of whether SSL/TLS has been selected or if the mailer supports STARTTLS. However, there is a scenario where NO ENCRYPTION is the requirement. I found the code and the files needing to be updated. But I am unable to find the same code to make the update in the main repo. When I create a PR in the other report (symfony/mailer), I get told that it is read only and I should make the PR in symfony/mailer.

Please let me know how to accomplish this.

Thanks.

### How to reproduce

1. Standard symfony.
2. Set up your mailer to advertise STARTTLS but set the parameters wrong since you do not want to use encryption (externally maintained by third party so you cannot get to it)
3. Request no encryption in the mailer on a custom port
4. The mailer uses STARTTLS if the mail server reports it is available even though what you want is no encryption
5. The mail attempt fails to login

### Possible Solution

Update the symfony mailer to make the SSL/TLS, STARTTLS, NONE explicit and not rely on capabilities to automatically turn on something that is not requested.

### Additional Context

Happy to create the PR, but I can't find where to make the PR. I submitted 2 but they got closed because the "repo is read-only."

**Comment by ghost** [comment]
> Happy to create the PR, but I can't find where to make the PR. I submitted 2 but they got closed because the "repo is read-only."

Symfony is a monorepo. All PRs should be created in symfony/symfony repository. Fork this repo and create PR here.

**Comment by derrabus** [comment]
Duplicate of #49114
