### ISSUE TITLE
Weird bug in http client

### ISSUE THREAD

**Issue by RikudouSage** [symfony/symfony#50151]
### Symfony version(s) affected

6.2.9

### Description

I stumbled upon this error in the logs:

`Uncaught PHP Exception TypeError: "Symfony\Component\HttpClient\Response\CurlResponse::initialize(): Argument #1 ($response) must be of type Symfony\Component\HttpClient\Response\CurlResponse, Symfony\Component\HttpClient\Response\CurlResponse given, called in /var/task/vendor/symfony/http-client/Response/CommonResponseTrait.php on line 41" at /var/task/vendor/symfony/http-client/Response/CommonResponseTrait.php line 132`

### How to reproduce

Sadly I have no idea.

**Comment by ghost** [comment]
Can you provide a reproducer? It's really awkward error.

**Comment by ghost** [comment]
> Can you provide a reproducer? It's really awkward error.

Sorry, I should have read not only the error message but the whole issue :laughing: 

> How to reproduce
Sadly I have no idea.
