### ISSUE TITLE
The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x4D2'

### ISSUE THREAD

**Issue by 1709abhishek** [symfony/symfony#50156]
### Symfony version(s) affected

all | latest

### Description

while migrating my code to php 8.1 on my legacy application, I ran my code through codesniffer and getting this error in symfony library. Please help me with the remedies. 

### How to reproduce

Run a codesniffer analysis on this project.

You can follow the below steps to run it in your local system. (also check attachment for the report)

```
Install squizlabs/php_codesniffer and phpcompatibility through composer.


composer require phpcompatibility/php-compatibility --dev --ignore-platform-reqs
composer require squizlabs/php_codesniffer --dev --ignore-platform-reqs
Add this script to composer.json


"sniffer:php8": "phpcs -d memory_limit=512M --ignore=*/vendor/* -p . --standard=vendor/phpcompatibility/php-compatibility/PHPCompatibility --runtime-set testVersion 8.1- --extensions=php "
and you need to add --report-full=/path/to/file.txt in the script to get the report.

Run composer sniffer:php8

If you’re getting an error wrt timeout, just add the below code into composer.json config section


"process-timeout": 0
```

error can be found in /symfony/yaml/Inline.php

### Possible Solution

use hexdec() but that would mean adding code to composer libraries

### Additional Context

Can we fix this issue to make it compatible to PHP 8.1

**Comment by derrabus** [comment]
If you find an actual issue that caused by whatever that tool claims to find, feel free to report that or contribute a failing test and a fix. But I don't think that this report is actionable for us.
