### ISSUE TITLE
[HtmlSanitizer] `<video>` element moved outside `<p>`

### ISSUE THREAD

**Issue by cedric-anne** [symfony/symfony#50154]
### Symfony version(s) affected

6.2.7

### Description

When sanitizing a content that have a `<video>` tag inside a `<p>` tag, the `<video>` tag is moved outside the `<p>` tag.

According to https://html.spec.whatwg.org/multipage/media.html#the-video-element, the `<video>` element is a `Phrasing content`, so it be kept inside the `<p>` element.

### How to reproduce

```php
<?php

use Symfony\Component\HtmlSanitizer\HtmlSanitizer;
use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;

$config = (new HtmlSanitizerConfig())->allowSafeElements()->allowRelativeMedias();
echo (new HtmlSanitizer($config))->sanitize('<p>Test: <video><source src="/path/to/video.mp4" type="video/mp4" /></video></p>');

// <p>Test: </p><video><source src="/path/to/video.mp4" type="video/mp4" /></video>
```

**Comment by HypeMC** [comment]
This is actually a bug in `masterminds/html5`, see https://github.com/Masterminds/html5-php/pull/232

**Comment by ghost** [comment]
Is is in release 2.8.0 https://github.com/Masterminds/html5-php/releases/tag/2.8.0 we should probably update the composer.json from `"masterminds/html5": "^2.7.2",` => `"masterminds/html5": "^2.8.0",`

**Comment by nicolas-grekas** [comment]
No need for bumping the min dep, just run composer up on your side.
Thanks for investigating the issue @HypeMC
