### ISSUE TITLE
[Webhook] Mailgun Webhook Converter - Special Mailgun code

### ISSUE THREAD

**Issue by TristanPouliquen** [symfony/symfony#50164]
### Description

Hello,

We rely on Mailgun to send some of our emails, and as such have developed a similar feature as the new Webhook component to handle their webhook calls.

In doing so, we found helpful to handle some Mailgun-specific error codes (6xx) for permanent fails.

Some might be relevant to handle in the default Symfony integration:
- 605 => Not delivering to a previously bounced address
- 606 => Not delivering to an unsubscribed address
- 607 => Not delivering to a user that already marked you as spam

These three error codes are linked to the Mailgun suppression listst, where they keep track of the users that already generated a hard bounce, unsubscribed or reported as spam.

In these cases, Mailgun blocks the email sending before it even reaches the email server.

In our opinion, these permanent fails might be better parsed to a `EmailDeliveryEvent::DROPPED` event than the `EmailDeliveryEvent::BOUNCE` that comes from simply parsing the event name & severity.

Might a PR on this topic be accepted?

**Comment by xabbuh** [comment]
PR welcome I guess :)
