### ISSUE TITLE
[Mailer] Sending to a blocked email address through Postmark

### ISSUE THREAD

**Issue by TristanPouliquen** [symfony/symfony#50165]
### Description

Hello,

When integrating Postmark to our stack to send emails, we noticed that if we send an email to an address that has been suppressed by Postmark (previous hard bounce, unsubscribe, spam...), the Postmark API throws an exception that is not catched by the Mailer component and comes from the PostmarkApiTransport through to the SendEmailHandler.

As of today, we decorated the SendEmailHandler to add a try/catch & dispatch a message as if we had received a webhook for a `EmailDeliveryEvent::DROPPED` event, but this seems hacky.

Is it an issue that would be interesting to solve in the Symfony code? If yes, do you have an idea on how to go at it in the best way?

**Comment by xabbuh** [comment]
@TristanPouliquen Do you have some resources to dig into the code and suggest a possible solution as a PR for the Postmark transport bridge?

**Comment by TristanPouliquen** [comment]
I haven't had time to find a more elegant solution than the one we use, I'll try & look into it, and see how I can modify the Postmark bridge accordingly without creating too much of a coupling between components.
