### ISSUE TITLE
[WebProfilerBundle] Log Messages Tab Buttons still radios

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#50179]
### Symfony version(s) affected

6.3.x-dev

### Description

Tabs are still radios
https://github.com/symfony/symfony/blob/94300a3081cbb917e1fd0c7dd1fed8753734bbdd/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/logger.html.twig#L275
<img width="1036" alt="ScreenShot-2023-04-27-22 08 02" src="https://user-images.githubusercontent.com/400092/234991548-6de13d1d-7420-40dd-80c9-c1a97d153137.png">

### How to reproduce

Visit the profiler -> Logs page when running 6.3.x-dev

### Possible Solution

migrate to tab-control's like the other pages 

<img width="915" alt="ScreenShot-2023-04-27-22 08 47" src="https://user-images.githubusercontent.com/400092/234991669-dbb0552c-ca33-442c-af6b-7460534b5a8a.png">

**Comment by fabpot** [comment]
@javiereguiluz

**Comment by javiereguiluz** [comment]
Yes, the exception page is also broken. I'll find some time to fix this soon. Thanks.

**Comment by javiereguiluz** [comment]
Closing as fixed in #50188.
