### ISSUE TITLE
[OptionsResolver] OptionResolver should handle null values and prevent defaults from being replaced by input parameters

### ISSUE THREAD

**Issue by rmed19** [symfony/symfony#50196]
### Symfony version(s) affected

v6.2.7

### Description

Hello,

I have encountered an issue with the OptionsResolver component when validating sorting options for a list page in my Symfony project. The problem occurs when the "sort" option has a null value, and the OptionsResolver throws an exception: "`The option "sort" with value null is invalid. Accepted values are: "name", "country", "balance".`"

It appears that the default values are being replaced by the input parameters passed to the resolve() method.

I believe that the OptionsResolver should handle the case of null values and prevent the default values from being replaced by the input parameters. This would make the component more flexible and easier to use in scenarios like this.

Thank you for considering this issue!

### How to reproduce

Here's the relevant code from my ListOptions class:

1. I create a controller action to list the teams:
``` php
    public function list(Request $request, TeamRepository $teamRepository): Response
    {
        $options = TeamListOptions::resolve([
            'sort' => $request->query->get('sort'),
            'order' => $request->query->get('order'),
        ]);

        $orderBy = [$options['sort'] => $options['order']];
        $teams = $teamRepository->findAllWithOrder($orderBy);

        return $this->render('team/list.html.twig', [
            'teams' => $teams,
            'sort' => $options['sort'],
            'order' => $options['order'],
        ]);
    }
```
2. I created the TeamListOptions class to handle the sorting options:

``` php
// src/Options/TeamListOptions.php

namespace App\Options;

use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamListOptions
{
    public static function resolve(array $options): array
    {
        $resolver = new OptionsResolver();

        $resolver->setDefaults([
            'sort' => 'name',
            'order' => 'ASC',
        ]);

        $resolver->setAllowedValues('sort', ['name', 'country', 'balance']);
        $resolver->setAllowedValues('order', ['ASC', 'DESC']);

        return $resolver->resolve($options);
    }
}
```

### Possible Solution

I checked the [`Symfony\Component\OptionsResolver\OptionsResolver#L877`](https://github.com/symfony/options-resolver/blob/aa0e85b53bbb2b4951960efd61d295907eacd629/OptionsResolver.php#L877),  it appears that the default values are being replaced by the input parameters directly. 

A possible solution would be to check if the input parameter value is null before replacing the default value.

I propose the following change to the code:

``` php
// Override options set by the user
foreach ($options as $option => $value) {
    $clone->given[$option] = true;

    // Only replace the default value if the input value is not null
    if ($value !== null) {
        $clone->defaults[$option] = $value;
    }

    unset($clone->resolved[$option], $clone->lazy[$option]);
}
``` 
With this change, the default values will only be replaced if the input value is not null. This should resolve the issue and allow the OptionsResolver to handle null values properly.

If the change it's OK for you I will create a pull request, or can you please tell me what I'm missing or if there's a better approach to handle this case with the OptionsResolver component?

**Comment by wouterj** [comment]
This does not work, as this will never allow setting an option to `null` (which can be a valid value for options).

If you want this behavior, you would have to handle this in your own code (e.g. by wrapping the array in an `array_filter()` call before passing it to `$resolver->resolve()`).
