### ISSUE TITLE
HttpClient doesn't correctly catch errors

### ISSUE THREAD

**Issue by garak** [symfony/symfony#50207]
### Symfony version(s) affected

from 5.4.x to 6.3.x

### Description

The logic in [this method](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpClient/Response/TraceableResponse.php#L205) looks wrong to me:

```php
private function checkStatusCode(int $code): void
{
    if (500 <= $code) {
        throw new ServerException($this);
    }

    if (400 <= $code) {
        throw new ClientException($this);
    }

    if (300 <= $code) {
        throw new RedirectionException($this);
    }
}

```

The order of ifs should be reversed, otherwise a higher status code is always returned early.

### How to reproduce

Use HTTP client to call a remote URL responding with a 401: instead of getting a ClientException, you get a ServerException.

### Possible Solution

Reverse the order mentioned above:

```php
private function checkStatusCode(int $code): void
{
    if (300 <= $code) {
        throw new RedirectionException($this);
    }

    if (400 <= $code) {
        throw new ClientException($this);
    }

    if (500 <= $code) {
        throw new ServerException($this);
    }
}

```

**Comment by nicolas-grekas** [comment]
I'm sorry but this doesn't make sense.
401 won't enter the `if (500 <= $code) {` code path, but should enter the next one.
Can you provide a test case or a reproducer?

**Comment by garak** [comment]
Yes, my bad, I then realized that I was fooled by ClientException being transformed into a 500 error.
Sorry for the noise.
