### ISSUE TITLE
[Messenger] `AsMessageHandler` attribute on methods do not work anymore

### ISSUE THREAD

**Issue by Korbeil** [symfony/symfony#50202]
### Symfony version(s) affected

6.3.0-BETA1

### Description

Hey :wave: 

My friend @welcoMattic told me Symfony 6.3.0-BETA1 got out and I had to test if there is some regression issues and found one with Messenger component.

When you make a Handler, if you do:
```php
#[AsMessageHandler]
class MessageHandler
{
    public function __invoke(SimpleMessage $message): void
    {
        // do stuff
    }
}
```
You can use it freely and it will work like a charm.

But if you do:
```php
class MessageHandler
{
    #[AsMessageHandler]
    public function batch(BatchMessage $batchMessage): void
    {
        // batch
    }

    #[AsMessageHandler]
    public function simple(SimpleMessage $message): void
    {
        // simple
    }
}
```
During cache warmup you will have the following error:
![image](https://user-images.githubusercontent.com/944409/235615527-dc5f51f4-a349-44f0-9237-003f6c96dd17.png)

### How to reproduce

See https://github.com/Korbeil/reproducer-63-messenger-handler/ for a simple reproducer.
And more specifically https://github.com/Korbeil/reproducer-63-messenger-handler/blob/main/src/Messenger/MessageHandler.php since it's where the issue is.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer.
