### ISSUE TITLE
[FrameworkBundle][Webhook] Services are missing when requiring Webhook component

### ISSUE THREAD

**Issue by Jean-Beru** [symfony/symfony#50211]
### Symfony version(s) affected

6.3.0-BETA1

### Description

When requiring `symfony/webhook` from a new Symfony project, 2 services depends on non-installed dependencies:

```
The service "webhook.transport" has a dependency on a non-existent service "http_client". 
```

```
The service "webhook.body_configurator.json" has a dependency on a non-existent service "serializer".
```

### How to reproduce

Create a projet from symfony/skeleton
```sh
composer require symfony/webhook
```

### Possible Solution

Should we throw an exception like `throw new LogicException('The webhook component cannot be enabled as these components are not installed. Try running "composer require symfony/http-client symfony/serializer".');` ?

**Comment by nicolas-grekas** [comment]
I'd suggest going with runtime errors as done in FrameworkExtension.
Can you send a PR that takes inspiration from the calls to addError in that class?

**Comment by Jean-Beru** [comment]
Sure !
