### ISSUE TITLE
[WebProfiler] dark mode on tab navigation list

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#50210]
### Symfony version(s) affected

6.2+

### Description

I just wanted to report a small UI issue on web profiler in dark mode: 2 tab list have not the same text color in dark mode

<img width="908" alt="rr" src="https://user-images.githubusercontent.com/1358361/235697743-00dee548-e3b4-4d69-bd1f-478442a04034.png">

<img width="661" alt="l" src="https://user-images.githubusercontent.com/1358361/235697729-5258aac8-51ab-4069-8359-c3a4ffa6cb69.png">

### How to reproduce

web profiler with dark mode enabled

### Possible Solution

I do not know if it is specific symfony profiler bundle asset or it is the Tabler asset itself
I can investigate further when in vacation but if someone find the clue faster, I opened this issue

**Comment by OskarStark** [comment]
Friendly ping @javiereguiluz

**Comment by MatTheCat** [comment]
I’m not able to reproduce on Symfony 6.2.10:

![](https://user-images.githubusercontent.com/1898254/236612120-a8ad000d-48bd-43a5-97a6-50bfc60f15fa.png)

Could you provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html)? I see your screenshots are missing a heading too.

**Comment by 94noni** [comment]
It is a profiler of a sf6.2 project i tested upgrading to sf6.3 with browser clear cache etc
When rollbacking to sf6.2 still same

put the issue in standby until i retry from scratch perhaps

**Comment by MatTheCat** [comment]
Okay this stems from https://github.com/symfony/symfony/pull/48762 (so, 6.3) because browsers’ buttons color takes precedence over the inherited one.
