### ISSUE TITLE
Allow multiple AsDecorator attributes on a decorating class

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#50228]
### Description

I have a situation in API Platform, in which I want to decorate the `api_platform.jsonld.normalizer.item` and `api_platform.hal.normalizer.item` with the same decorator. In short, that decorator adds a property to the normalized item.

In https://github.com/symfony/symfony/pull/45834, in addition to the configuration of a decorator in the service definition, it's made possible to do this using a PHP attribute `#[AsDecorator]`. Unfortunately, it's not possible to repeat this attribute.

I've done a quick test making the attribute repeatable, but this results in the decorator applied to the first service being overwritten by the second one, I think because of the same reason as described [here](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data): the name of the decorating service is reused. Therefore, this feature requires more work than just making the attribute repeatable: generating (or demanding configuration) unique service names is required.

### Example

```php
<?php

namespace App\ApiPlatform\Normalizer;

use App\ApiPlatform\Attribute\HateoasLink;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\SerializerAwareInterface;
use Symfony\Component\Serializer\SerializerInterface;

#[AsDecorator('api_platform.jsonld.normalizer.item')]
#[AsDecorator('api_platform.hal.normalizer.item')]
class HateoasLinkNormalizer implements NormalizerInterface, SerializerAwareInterface
{
    public function __construct(
        private readonly NormalizerInterface $decorated,
        private readonly RouterInterface $router,
    ) {
    }

    // ...
}

**Comment by stof** [comment]
A single service cannot decorate multiple other services. That's why the attribute cannot be repeated.

**Comment by stof** [comment]
Autoconfiguration features are about configuring the registered service, not creating new ones by duplicating it under a different id. So we cannot automatically register cloned definitions of the service to decorate multiple services (and trying to do that might cause issues in other layers, by registering those alternative definitions much later in the processing)

**Comment by tjveldhuizen** [comment]
A single service can not, but a single class can be used to instantiate multiple decorating services, isn't it? It looks like that is the way it works when I follow the [API Platform documentation](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data).

**Comment by nicolas-grekas** [comment]
Sure, but the attribute is about registering the service.
It looks like you need to register your class twice.
Closing as explained by @stof
