### ISSUE TITLE
[DependencyInjection] Generics support in autowiring

### ISSUE THREAD

**Issue by priyadi** [symfony/symfony#50220]
### Description

Now that generics annotations are well-established and practically all static analysis tools support the same syntax, it would be nice if DependencyInjection supports generics.

If everyone can agree on generics attributes or if PHP supports native generics, it should be easy to migrate using tools like Rector.

### Example

```php
<?php

class Post
{
}

class Comment
{
}

/**
 * @template T of object
 */
interface RepositoryInterface
{
    /**
     * @return ?T
     */
    public function find(mixed $id): ?object;
}

/**
 * @implements RepositoryInterface<Post>
 */
class PostRepository implements RepositoryInterface
{
    public function find(mixed $id): ?object
    {
        return new Post();
    }
}

/**
 * @implements RepositoryInterface<Comment>
 */
class CommentRepository implements RepositoryInterface
{
    public function find(mixed $id): ?object
    {
        return new Comment();
    }
}

class SomeService
{
    /**
     * @param RepositoryInterface<Post> $postRepository
     * @param RepositoryInterface<Comment> $commentRepository
     */
    public function __construct(
        private RepositoryInterface $postRepository,
        private RepositoryInterface $commentRepository,
    ) {
    }

    public function someMethod(): void
    {
        $post = $this->postRepository->find(1);
        $comment = $this->commentRepository->find(1);
    }
}
```

**Comment by nicolas-grekas** [comment]
Because we don't want the DI steps to rely on third party deps, and since we'd need one for parsing the annotation, I don't think we'll be able to implement this until PHP has a native syntax for this.

Meanwhile, you should use `#[Autowire(service: PostRepository::class)]` and `#[Autowire(service: CommentRepository::class)]`.

**Comment by derrabus** [comment]
Until now, PHPDoc blocks were completely irrelevant for the DI component. Before we can think about this feature, we would need to make DI aware of PHPDoc and I doubt that we want to go down that path.

In addition to Nicolas' example, named autowiring aliases could also solve the issue for you:

```php
#[AsAlias('YourNamespace\RepositoryInterface $postRepository')]
class PostRepository implements RepositoryInterface
{
    // …
}
```

It should even be possible to generate those aliases using a compiler pass.

**Comment by ro0NL** [comment]
i thought the current canonical way is using `#[Target]` :sweat_smile: 

https://symfony.com/blog/new-in-symfony-5-3-service-autowiring-with-attributes#selecting-autowire-alias-with-attributes

**Comment by nicolas-grekas** [comment]
`#[Target]` works well together with @derrabus comment yes.

**Comment by ro0NL** [comment]
right! i need to do the attrinbute migration still :angel: 

i wanted to say

```
RepositoryInterface<Post> $postRepository
```

isnt real language, whereas 

```
#[Target(Post::class)] RepositoryInterface $postRepository
```

is :)

but im not sure it should be solved in e.g. doctine bundle. It looks sane wiring IMHO

**Comment by derrabus** [comment]
Shall we close this issue? I still feel we don't need it and we have enough ways to support the presented use-case without parsing PHPDoc.
