### ISSUE TITLE
[AssetMapper] Add a Filesystem abstraction

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#50221]
### Description

[Right now the AssetMapper command directly writes into the public folder. ](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/AssetMapper/Command/AssetMapperCompileCommand.php#L88)

It would be nice if there would be an abstraction to the Filesystem so I could directly use Flysystem and upload it to S3/whatever. A workaround could be to let it copy to an temporary directory and from there to S3 (assuming the public folder is read-only).

**Comment by ro0NL** [comment]
We can argue the dumped (compile) artifacts should be dealt with by other means.

In our case a quick `s3cmd put` is sufficient yes.

**Comment by weaverryan** [comment]
I believe the filesystem is only used for writing in the 1 referenced place: [AssetMapperCompileCommand](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/Command/AssetMapperCompileCommand.php)

If someone is interested, a `AssetFilesystemInterface` + a `LocalAssetFilesystem` implementation (which uses the `Filesystem` class like now) could be added. That would give users the flexibility to decorate or replace this new, core "asset filesystem" service with their own implementation.

Who wants to create this? It's easy now, as we don't yet need to worry about changing constructor arguments of `AssetMapperCompileCommand` from a BC perspective. But it'll get harder after 6.4 ;).

**Comment by shyim** [comment]
It looks not so good to do right now. We need kinda a virtual filesystem. But this interface expects that you return a absolute path: https://github.com/symfony/symfony/blob/53e297db9232e72f3f920726a34d4cdd79206bdf/src/Symfony/Component/AssetMapper/Path/PublicAssetsPathResolverInterface.php#L24

Do we deprecate that and make an generic filesystem interface or what would be the idea?

**Comment by ro0NL** [comment]
> We need kinda a virtual filesystem

yes, aka flysystem ;)

**Comment by weaverryan** [comment]
@shyim WDYT about #51847? I think it'll give you the hook you need
