### ISSUE TITLE
[TwigBundle][TwigBridge] Wrong dependency version 

### ISSUE THREAD

**Issue by SVillette** [symfony/symfony#50245]
### Symfony version(s) affected

6.3

### Description

As @curry684 stated in [this comment](https://github.com/symfony/symfony/pull/49913#issuecomment-1533267166), if an application requires `TwigBundle:6.3` but `TwigBridge:6.2`, an error will be triggered when the container is compiled.

### How to reproduce

I reproduced this issue by only upgrading `symfony/twig-bundle` to `6.3`.

```json
{
        "symfony/twig-bridge": "6.2.*",
        "symfony/twig-bundle": "6.3.*-dev",
 }
```

And I get the following error

```
In App_KernelDevDebugContainer.php line 935:
                                                                                                               
  Attempted to call an undefined method named "setLocaleSwitcher" of class "Symfony\Bridge\Twig\AppVariable".
```

### Possible Solution

Set 6.3 as `symfony/twig-bridge` minimum version in `symfony/twig-bundle` dependencies seems to fix the issue.

### Additional Context

If core members agree with this fix, I can open a PR.

**Comment by stof** [comment]
This is indeed the right fix. Please open the PR.
