### ISSUE TITLE
[HttpKernel][FrameworkBundle] Service definition of RequestPayloadValueResolver fails on linting without Serializer component

### ISSUE THREAD

**Issue by chr-hertel** [symfony/symfony#50258]
### Symfony version(s) affected

6.3

### Description

When updating [an application](https://github.com/chr-hertel/oss-complexity-report) to Symfony 6.3 beta, without serializer component installed, the `lint:container` command throws following exception:

```
 [ERROR] Invalid definition for service "argument_resolver.request_payload": argument 1 of                              
         "Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver::__construct()" accepts  
         "Symfony\Component\Serializer\SerializerInterface&Symfony\Component\Serializer\Normalizer\DenormalizerInterface
         ", "Symfony\Component\Serializer\Serializer" passed.  
```

### How to reproduce

See https://github.com/chr-hertel/oss-complexity-report/pull/5

### Possible Solution

I guess the solution is somewhere around the service definition of RequestPayloadValueResolver

### Additional Context

Symfony version of `event-dispatcher` and `process` are on v5.4 in this case, but I don't think that this really matters here.

**Comment by nicolas-grekas** [comment]
Fixed in #50260, thanks for the reproducer!
