### ISSUE TITLE
error on signing a templated email

### ISSUE THREAD

**Issue by rcsofttech85** [symfony/symfony#50254]
### Symfony version(s) affected

6.2

### Description

If email is a templatedEmail on signing it throws an "A message must have a text or an HTML part or attachments." error. 

error comes from the below code:

$signer = new DkimSigner(pk: 'file://' . $privateKey, domainName: "domain", selector: "test");

when i switched back to regular email  it was working as expected 

### How to reproduce

    public function getEmail(): Email
    {
        return (new TemplatedEmail())
            ->subject("subscribed")
            ->to(new Address(address: $this->email))
            ->htmlTemplate('email/subscribe.html.twig')
            ->context([
                'movie_name' => $this->movieName
            ]);

    }

and in custom middleware when i receive this object, i am trying to sign the email.

**Comment by MatTheCat** [comment]
This issue is known but the documentation barely address it :confused: 

You’re supposed to sign your email in a late `MessageEvent` listener so that it has been rendered: https://symfony.com/doc/current/mailer.html#messageevent
