### ISSUE TITLE
[EnvVarProcessor] add default env to allow defaulting to an env var

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#50273]
### Description

Hello,

I wanted to leverage https://symfony.com/doc/current/configuration/env_var_processors.html > `default`.

But it is very linked to `parameter`; and I wanted to defaults to another env var.
(I did not found in the doc if I can do such behavior)
(Also I do not want to add another container parameter for this)

---

```.env
# .env
APP_SECRET=foo
BUNDLE_SECRET=bar        <- can be or not defined
```

```php
// services.php
return static function (ContainerConfigurator $container) {
$container->parameters()->set('my_bundle.token', '%env(default_env:APP_SECRET:BUNDLE_SECRET)%');
```

First question, is it possible already? if yes were can I read about it?
Second one if not, would [this commit](https://github.com/94noni/symfony/commit/666ab3555523354408fcb411f923aae0b014946e) be discussed as a PR?

Thank you,

**Comment by MatTheCat** [comment]
I recall you could write something like

```yaml
parameters:
    env(BUNDLE_SECRET): '%env(APP_SECRET)%'
```

Does it still work?

**Comment by 94noni** [comment]
@MatTheCat thx for stopping by, I will check this 
but doesnt this add a new parameter in the container?

**Comment by MatTheCat** [comment]
> doesnt this add a new parameter in the container?

It does. Shouldn’t cause any issue though?

**Comment by 94noni** [comment]
I wanted to not add any new param or env whatsoever
will see if this is legit or not, thx

**Comment by 94noni** [comment]
>**Note** Personal reminder to test https://symfony.com/blog/new-in-symfony-6-3-dx-improvements-part-2#build-parameters-in-service-container
add a build param defaulting to app_secret with prefix

**Comment by 94noni** [comment]
closing as I will use the v6.3 feature for tmp parameter
