### ISSUE TITLE
[Messenger] DoctrineIntegrationTest is not guaranteed to run in UTC

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#50327]
### Symfony version(s) affected

6.3

### Description

Regression due to #50287: Since tests could be run in non UTC, we have to ensure all dates are UTC.

**Comment by nicolas-grekas** [comment]
Any proof? As far as I tested, it works, but I may have missed something of course!

**Comment by alex-dev** [comment]
Failing tests: https://ci.appveyor.com/project/fabpot/symfony/builds/47048701
You are right. Just passing timezone info does work. Let me see why are the tests failing.

**Comment by alex-dev** [comment]
Found it I think. "Fixtures" as in message pre inserted during test are not guarantee to be in UTC. So if appveyor does not run on a UC container.... These tests will fail.
That's a bug, but a much less severe one. Just tests not being up to date.

**Comment by stof** [comment]
Can you send a PR updating those fixtures ?
