### ISSUE TITLE
[HttpKernel] #[MapQueryParameter] Problem with nullable parameters

### ISSUE THREAD

**Issue by szepczynski** [symfony/symfony#50339]
### Symfony version(s) affected

6.3.0-BETA3

### Description

Hi,

In documentation is an example with optional nullable string parameter (?string $theme = null).

> Symfony has allowed to map route parameters to controller arguments since its first version. In Symfony 6.3 you will also be able to map query string parameters to specific controller arguments. To do so, use the new #[MapQueryParameter] attribute:
> 
```#[Route(path: '/', name: 'admin_dashboard')]
public function indexAction(
    #[MapQueryParameter] array $ids,
    #[MapQueryParameter] string $firstName,
    #[MapQueryParameter] bool $required,
    #[MapQueryParameter] int $age,
    #[MapQueryParameter] string $category = '',
    #[MapQueryParameter] ?string $theme = null,
)
```
> If the query string of the incoming request is /?ids[]=1&ids[]=2&firstName=Ruud&required=3&age=123, this code will make the controller arguments to have these values:

```
$ids = ['1', '2']
$firstName = "Ruud"
$required = false
$age = 123
$category = ''
$theme = null
```

 

I test similar example on v6.3.0-BETA3 on my application but nullable query string parameter doesn't work.

```
    #[Route(path: '/')]
    public function indexAction(
        #[MapQueryParameter] ?string $theme = null
    ): Response {
        return new Response('test');
    }
```

1) `GET /?theme` works

2) `GET /` leads to RuntimeException (Controller "App\Controller\IndexController::indexAction" requires that you provide a value for the "$theme" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.)

### How to reproduce

Example: https://github.com/szepczynski/symfony-6.3-map-query-parameter-bug-reproduction/

**Comment by MatTheCat** [comment]
Indeed `QueryParameterValueResolver` is “targeted” so the `DefaultValueResolver` won’t kick in, good catch!

**Comment by szepczynski** [comment]
@MatTheCat shouldn't be the same behavior in case of use BackedEnumValueResolver?

Let's see on this example:

```
enum Theme: string { case DEFAULT = 'default'; }
```

```
    #[Route(path: '/')]
    public function indexAction(
        #[MapQueryParameter(resolver: BackedEnumValueResolver::class)] ?Theme $theme = null
    ): Response {
        return new Response('test');
    }
```

If I don't provide BackedEnum value in query I've got an exception like this:

```
Controller "App\Controller\IndexController::indexAction" requires that you provide a value for the "$theme" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.
```

I'm not sure is a correct behavior especially how to understand the part "argument is nullable and *no null value* provided"

**Comment by MatTheCat** [comment]
You're not supposed to change `MapQueryParameter`ʼs resolver.

Regarding the behavior difference, I tried to explain it in [the documentationʼs PR](https://github.com/symfony/symfony-docs/pull/17763) so feel free to give a look!

**Comment by szepczynski** [comment]
Thanks for fast response. At the beginning I started without modifying
resolver but then I received exception that only array, string, int, float
and boolean is supported by MapQueryParameter. Is it a correct behavior?

```
#[MapQueryParameter] cannot be used on controller argument "$theme" of type "App\Enum\Theme"; one of array, string, int, float or bool should be used.
```
