### ISSUE TITLE
Move towards single-attribute voters

### ISSUE THREAD

**Issue by justin-oh** [symfony/symfony#50348]
### Description

I came up with this idea / coding pattern as I was trying to build out a user role grid where each attribute string needed to be unique. I realized this can easily be achieved if each attribute corresponds to only one class. Hence the single-attribute voter.

I'm also keen on discouraging a `null` subject wherever possible. If you are voting on, say, a Post listing page, the developer should be encouraged to at least pass `Post::class` as the subject.

**Pros**

1. Better performance through finer-grained checking inside the `supportsAttribute` functions.
2. Attribute strings are unique. Unique attributes guarantee caching is optimal and also add clarity to the code. As opposed to every entity having the same CRUD attributes (ie. "create", "edit", "delete", etc.).
3. Permission logic is concise and well-organized. No if/else or switch structure to designate different attributes to different blocks of logic. Each attribute corresponds to one class with one function containing the logic.

**Cons**

1. More classes? Is that a con?
2. Using the Twig helper `is_granted` is more cumbersome. The attribute string being a class requires explicitly passing that class string to the template.
3. Sharing permission logic is also more cumbersome, but not impossible.

Again this is more of an idea at this point and could very well be specific to my needs. Curious to hear people's thoughts.

### Example

_**Full disclosure:** this code has not actually been run so it may not be complete / error free._

The abstract class could look something like this:

```php
<?php

namespace Symfony\Component\Security\Core\Authorization\Voter;

use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\User\UserInterface;

abstract class SingleAttributeVoter extends Voter
{
    abstract protected function getSubjectType(): string;
    abstract protected function voteOnSubject($subject, UserInterface $user): bool;

    final public function supportsAttribute(string $attribute): bool
    {
        return static::class === $attribute;
    }

    final protected function supports(string $attribute, $subject): bool
    {
        if (!$this->supportsAttribute($attribute)) {
            return false;
        }

        $subjectString = \is_object($subject)
            ? \get_class($subject)
            : \is_string($subject) ? $subject : get_debug_type($subject);

        return $this->getSubjectType() === $subjectString;
    }

    final protected function voteOnAttribute(string $attribute, $subject, TokenInterface $token): bool
    {
        $user = $token->getUser();

        if (!$user instanceof UserInterface) {
            return $this->voteOnSubjectNoUser($subject);
        }

        return $this->voteOnSubject($subject, $user);
    }

    // user login is usually required, but can be overridden
    protected function voteOnSubjectNoUser($subject): bool
    {
        return false;
    }
}
```

A voter extending this class would look like this:

```php
<?php

namespace App\Security\Voter;

use App\Entity\Post;
use Symfony\Component\Security\Core\Authorization\Voter\SingleAttributeVoter;
use Symfony\Component\Security\Core\User\UserInterface;

class PostEditVoter extends SingleAttributeVoter
{
    protected function getSubjectType(): string
    {
        return Post::class;
    }

    protected function voteOnSubject($post, UserInterface $user): bool
    {
        return !$post->isPublished();
    }
}
```

And checking for permissions would look like this:

```php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Security\Voter\PostEditVoter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class Controller extends AbstractController
{
    #[Route('/post/{id}/edit', name: 'post_edit', methods: ['GET', 'POST'])]
    public function edit(Post $post)
    {
        $this->denyAccessUnlessGranted(
            PostEditVoter::class,
            $post,
            'You cannot edit this post.'
        );
    }
}
```

Or like this:

```php
$this->render('post/view.html.twig', [
    'post_edit_attribute' => PostEditVoter::class,
    'post' => $post,
]);
```

```twig
{% if is_granted(post_edit_attribute, post) %}
    {# ... #}
{% endif %}
```

**Comment by stof** [comment]
Enforcing unique attribute names even when the type of subject is different would be a _huge_ BC break.

And trying strictly an attribute to a voter class would also force to remove features of the component. The authentication manager currently supports several strategies about what happens when multiple voters support the attribute.
Using the class name as as attribute would be a big WTF if you don't make the feature single-voter attributes as well in addition to being single-attribute voters.

So to me, I would not do that in core at all (of course, you are free to use such implementation in your project)

**Comment by stof** [comment]
Btw, most of the pros listed there are more about single-voter attributes than single-attribute voters (the component does not care at all if each of your voters supports only 1 attribute). and this would be a _huge_ BC break (and is incompatible with the concept of access decision strategy)

**Comment by justin-oh** [comment]
Thanks @stof for the replies. I'm already seeing issues in trying to implement this. It works, but it is limiting as you said.
