### ISSUE TITLE
message-id header issue with Mime/Header

### ISSUE THREAD

**Issue by web95-moon** [symfony/symfony#50366]
### Symfony version(s) affected

6.0

### Description

Getting error that 

The \"Message-ID\" header must be an instance of \"Symfony\\Component\\Mime\\Header\\IdentificationHeader\" (got \"Symfony\\Component\\Mime\\Header\\UnstructuredHeader\").

### How to reproduce

install 6.0 version
set header 

$headers = $this->symfonyEmail->getHeaders();
$headers->addTextHeader('Message-ID', '<CAJPmW_ZM-D8VbwN-mfojForYN30GsNm_Hi1QvmPjB2JKVbxAhw@mail.gmail.com>');

### Possible Solution

in symfony\mime\Header\Headers.php

HEADER_CLASS_MAP = message-id allow to set UnstructuredHeader::class
like below screenshot

![image](https://github.com/symfony/symfony/assets/125456979/cf4b9231-25d6-4fe6-b933-5700bc270ce3)

### Additional Context

if this is not right solution do let me know what is correct solution towards this issue

**Comment by alamirault** [comment]
You should use `addIdHeader` method in order to have an `IdentificationHeader` 

https://github.com/symfony/symfony/blob/b101b71ddacfa664485bb09ec6272971e458f49f/src/Symfony/Component/Mime/Header/Headers.php#L98

**Comment by xabbuh** [comment]
closing as explained by @alamirault
