### ISSUE TITLE
[Serializer] Discriminating on an Enum field leads to bad cache values being used

### ISSUE THREAD

**Issue by Aweptimum** [symfony/symfony#50370]
### Symfony version(s) affected

6.2

### Description

I'm getting weird behavior in the serializer's ObjectNormalizer where it's normalizing the value of an enum property using the cached value of a previous object's enum. I have an array containing two objects - they have an enumerated property that is also used as a discriminator for the serializer. When the second object is normalized, its property value is set the first object's value instead. 

It's happening in the ternary at the end of `ObjectNormalizer->getAttributeValue`, specifically this:

```php
return $attribute === $this->discriminatorCache[$cacheKey] ? $this->classDiscriminatorResolver->getTypeForMappedObject($object) :
$this->propertyAccessor->getValue($object, $attribute);
```
Which evaluates to: `"operator" === true ? "a" : "A"`
The `$cacheKey` is the FQCN of the object, there's no hash on the end to distinguish it from other instances of the object :/

### How to reproduce

I have an MRE reproducing the behavior here: https://github.com/Aweptimum/serializer-test

### Possible Solution

Have the object normalizer delegate to the BackedEnum normalizer instead of the PropertyAccessor?

**Comment by HypeMC** [comment]
You seem to have gotten two different things confused here, the `a` you keep getting is the value of the discriminator column, try changing it to something else, eg:

```diff
#[DiscriminatorMap(
    typeProperty: 'letter',
    mapping: [
-        'a' => A::class,
+        'x' => A::class,
-        'b' => B::class,
+        'y' => B::class,
    ]
)]
```

```
array:1 [
  "letters" => array:2 [
    0 => array:1 [
      "letter" => "x"
    ]
    1 => array:1 [
      "letter" => "x"
    ]
  ]
]
```

Also, if you want the value of the enum, you'll need to change the name of the `typeProperty` to something different, eg:

```diff
#[DiscriminatorMap(
-    typeProperty: 'letter',
+    typeProperty: 'letterType',
    mapping: [
        'x' => A::class,
        'y' => B::class,
    ]
)]
```

```
array:1 [
  "letters" => array:2 [
    0 => array:2 [
      "letterType" => "x"
      "letter" => array:2 [
        "name" => "A"
        "value" => "A"
      ]
    ]
    1 => array:2 [
      "letterType" => "x"
      "letter" => array:2 [
        "name" => "a"
        "value" => "a"
      ]
    ]
  ]
]
```

I don't think there's a bug here.

**Comment by Aweptimum** [comment]
Oops, I did mess up the discriminator. Fixed that, removed the B classes to reduce confusion. Still getting the same behavior though in the normalized form:
```php
$normalized = [
    [letters] => [
        [
                [letter] => 'a' // Should be 'A'
        ],
        [
                [letter] => 'a'
        ],
    ]
];

**Comment by HypeMC** [comment]
Your changes don't make sense as you now have two types mapping to the same class:

```php
#[DiscriminatorMap(
    typeProperty: 'letter',
    mapping: [
        'a' => A::class,
        'A' => A::class,
    ]
)]
```

Also, the result is ok since both objects in the `$letters` array are instances of `A`.

**Comment by Aweptimum** [comment]
Ah, fair. I guess there's not an alternative besides adding a flag. I had wanted to map two sets of enums to 1 of two corresponding classes that would handle them.

**Comment by Aweptimum** [comment]
My cat must've messed with my laptop on Saturday.

I'll close and ask for a feature request to allow mapping many values to one class since OpenAPI's discriminator supports it
