### ISSUE TITLE
[HttpKernel] Move UriSigner to Http Foundation

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#50384]
### Description

Based on [Symfony Docs](https://github.com/symfony/symfony-docs/issues/18330) discussion. I want to open a discussion here to maybe move the `UriSigner` class to the `http-foundation`. Think the `HttpKernel` is a little bit unexpected place for the Signer. Would have expected it to be part of the routing component or http foundation component. Atleast I would have searched there for its documentation.

I did stumble over the [UrlHelper](https://symfony.com/doc/current/components/http_foundation.html#generating-relative-and-absolute-urls) and would think the **UriSigner** could be side by side to it.

What do you think?

### Example

```diff
-Symfony\Component\HttpKernel\UriSigner;
+Symfony\Component\HttpFoundation\UriSigner;
```

Reference: [PR Introduction of UriSigner](https://github.com/symfony/symfony/pull/6459)

**Comment by ro0NL** [comment]
symfony/uri maybe :pleading_face:

**Comment by stof** [comment]
I think the reason is that UriSigner was added as helper for the ESI feature, which lives in HttpKernel.

**Comment by fabpot** [comment]
Moving it to HttpFoundation works for me.
