### ISSUE TITLE
Service Container no working "exclude"

### ISSUE THREAD

**Issue by Myks92** [symfony/symfony#50417]
### Symfony version(s) affected

6.2.8

### Description

In version `6.2.8` I get a Service Container error. Files and folders are not excluded. Instead, folders are added to the container as `Service ID`: [folder/filename] and `Class name`: [folder/filename]. At the same time, it works on version `6.1.*`

Example: https://drive.google.com/file/d/1AfmbLkxpFGtixKnATdKToJUa5x_inl8v/view?usp=share_link
For example, `Command`, `Query`, `Entity` are folders, but they are specified as services in the container. 

### How to reproduce

Configuration:

**src/Kernel.php**
```php
<?php

declare(strict_types=1);

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

final class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    private function configureContainer(ContainerConfigurator $container): void
    {
        $configDir = $this->getConfigDir();
        $container->import($configDir . '/{packages}/*.{php,yaml}');
        $container->import($configDir . '/{services}/*.{php,yaml}');
        $container->import('./**/config.{php,yaml}');// import config from module
    }
}
```

**src/Auth/config.php**
```php
<?php

declare(strict_types=1);

namespace App\Auth;

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

use function Symfony\Component\DependencyInjection\Loader\Configurator\service;

return static function (ContainerConfigurator $configurator): void {
    $services = $configurator
        ->services()
        ->defaults()
        ->autowire()
        ->autoconfigure();

    $services->load('App\\Auth\\', '.')->exclude([
        './config.php',
        './Command',
        './Entity',
        './Query',
        './Test',
        './Validator/Constraint',
    ]);

    $services->load('App\\Auth\\Command\\', './Command/**/Handler.php');
    $services->load('App\\Auth\\Entity\\', './Entity/**/*Repository.php');
    $services->load('App\\Auth\\Query\\', './Query/**/Handler.php');
};
```
**config**
Global file `services.yaml` not used.

Example App: https://github.com/Myks92/symfony-service-container/tree/master

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
@nicolas-grekas does the `debug:container` support the `container.excluded` tag properly or was this forgotten when changing the way exclude rules work ?

and do you have any idea why some services get created for names corresponding to folders rather than files ?

**Comment by nicolas-grekas** [comment]
we can exclude by folder, so we create placeholder container.exclude services for folders yes
debug:container should be aware of the tag yes (but I didn't check the code before answering)
a reproducer would definitely help

**Comment by Myks92** [comment]
@stof folder Information from Service (`php bin/console debug:container "App\Auth\Command»`)

```
 ---------------- --------------------------------------------------- 
  Option           Value                                              
 ---------------- --------------------------------------------------- 
  Service ID       App\Auth\Command                                   
  Class            App\Auth\Command                                   
  Tags             container.excluded (source: in "Auth/config.php")  
  Public           no                                                 
  Synthetic        no                                                 
  Lazy             no                                                 
  Shared           yes                                                
  Abstract         yes                                                
  Autowired        no                                                 
  Autoconfigured   no                                                 
  Usages           none                                               
 ---------------- --------------------------------------------------- 
```

@xabbuh example App: https://github.com/Myks92/symfony-service-container/tree/master

**Comment by Myks92** [comment]
> Can you create a small example application that allows to reproduce your issue?

Yes! App: https://github.com/Myks92/symfony-service-container/tree/master

**Comment by MatTheCat** [comment]
Your reproducer is broken because of wrong Doctrine types configuration.

I guess you were using Symfony 6.2.0 or 6.2.1 because one of the issues you mention (being able to describe a specific excluded service) has been fixed by #48606.

Remaining issue is excluded services appearing in the list, as mentioned in https://github.com/symfony/symfony/pull/48606#issuecomment-1352701327. As far as I can tell this would require updating descriptors’ `describeContainerServices` method to ignore definitions bearing the `container.excluded` tag ~if those are to be hidden~.

Are you up for a PR?

**Comment by Myks92** [comment]
@MatTheCat Yes, I will make PR.

**Comment by Myks92** [comment]
@MatTheCat PR: https://github.com/symfony/symfony/pull/50452

**Comment by xabbuh** [comment]
Can we close here now that #50452 has been merged or is here still work left to do?
