### ISSUE TITLE
[twig lint Error] when using the command composer require twig/markdown-ext Error to update it

### ISSUE THREAD

**Issue by mina20088** [symfony/symfony#50448]
### Symfony version(s) affected

6.2

### Description

 when i tried to use the symfony console lint:twig i got some errors regarding linting the twig template
most of them are solved while using composer require package name where this composer require twig/markdown-ext cant be updated and said that this package is compatible only with PHP 7.0
issue includes screen shots about what happens
![Screenshot 2023-05-27 020047](https://github.com/symfony/symfony/assets/39167278/c7754500-1a1a-4c80-aa8c-a519b10f95d6)
![Screenshot 2023-05-27 015303](https://github.com/symfony/symfony/assets/39167278/e72aa0f3-31e7-47e0-b549-745a8d8f9a4c)

### How to reproduce

Use an alternative package: If neither of the above options works, you can look for an alternative package that provides similar functionality and is compatible with PHP version 8.2.5. You can search for packages on the Packagist website or using the composer search command. 
there is no specific code for that

### Possible Solution

get an alternative to this package or upgrade the main package to be compatible with php 8

**Comment by HypeMC** [comment]
As mentioned on [Packagist](https://packagist.org/packages/twig/markdown-extension) the `twig/markdown-extension` package is abandoned and `twig/markdown-extra` should be used instead.

**Comment by mina20088** [comment]
> As mentioned on [Packagist](https://packagist.org/packages/twig/markdown-extension) the `twig/markdown-extension` package is abandoned and `twig/markdown-extra` should be used instead.

ok solved thank you very much

**Comment by mina20088** [comment]
solved
