### ISSUE TITLE
New Structure constraint for validating array structure

### ISSUE THREAD

**Issue by dwgebler** [symfony/symfony#50460]
### Description

Not to be confused with `Collection` to validate the individual elements of an array against arbitrary constraints, I wrote a `Structure` constraint for use in personal projects which is used to validate (optionally) the size and type structure of an array's keys and values.

I think it could potentially be a useful addition to Symfony Validator core, but I want to gauge the interest.

I've provided example usage below to illustrate how it works. If there's interest in a PR, I'll create a branch with the code and test cases.

```php
class SomeObject {
// This constraint says $address must have keys which are all strings, must have at most five elements, and all values must be strings.
#[Structure(keysType: 'string', valuesType: 'string', max: 5)]
private array $address;

// This constraint says all five of the specified keys must exist in the array. The array may optionally contain other keys.
#[Structure(keys: ['line1', 'line2', 'city', 'state', 'zipcode'])]
private array $address;

// This constraint mandates the keys are present and the value of the corresponding type. Fully qualified class or enums are permitted, as are recursively evaluated inner arrays. Type strings may use the pipe character to separate multiple permitted types.
#[Structure(structure: [
    'nickname' => 'string',
    'shareComments' => 'bool',
    'age' => 'int',
    'userType' => UserTypeEnum::class,
    'address' => [
        'line1' => 'string',
        'line2' => 'string',
        'postcode' => 'string',
        'allowPostalCommunication' => 'bool|null',
    ]
])]
private array $profile;
}
```

The supported options on the constraint are `min` and `max` for array size, `keysType` to specify all keys must be either ints or strings, `valuesType` to specify all values must be of a type (or one of a pipe-delimited set of types), `keys` to specify a list of keys which must all be present in the array, and `structure` to define a specific key => type structure, which can be nested (this is limited to the kind of structure shown above, so a limitation of this constraint is that you can't say in the above example, for instance, the inner "address" array must merely contain between 1 and 5 elements like you can on the root constraint, you do have to specify the full structure you expect).

Thoughts and feedback welcome, thanks.

### Example

```
$value = [
    'foo' => 1,
    'bar' => true,
    'baz' => 'symfony',
    'bip' => [
        'bap' => null,
    ],
];

$constraint = new Structure(
    min: 1,
    max: 3,
    keys: ['foo', 'bar', 'bop', 'fib']
);

$violations = $validator->validate($value, $constraint);

// Violations are:
// The array must have at most 3 elements
// The following keys are required: bop, fib.

$constraint = new Structure(
    structure: [
        'foo' => 'bool',
        'baz' => 'string|int',
        'bip' => [
            'bap' => 'int',
        ],
    ]
);

$violations = $validator->validate($value, $constraint);

// Violations are:
// The value "1" at key "foo" is not of type boolean.
// The value "null" at key "bap" is not of type integer.
```

**Comment by stof** [comment]
If you want to validate that all values match the same constraints, we already have the `All` constraint for that.
If you want to validate a specific shape (with dedicated constraints for each key of the array), we already have the `Collection` constraint.

**Comment by dwgebler** [comment]
@stof absolutely, but the use-case is different. This is for cases where you're interested in validating _structure_ as opposed to values.

**Comment by stof** [comment]
Well, your case of saying that the key `foo` must contain a bool is achieved by applying a `Type('bool')` constraint on the `foo` key with `Collection`.
Your proposal seems like a less powerful alternative that what we can already do.

Note that your code still validates that the _values_ are matching this structure. The `Collection` constraint does that as well, but allowing to validate more things than the _types_ of sub-values (it can validate any rule that can be validated by the component).

**Comment by dwgebler** [comment]
> Well, your case of saying that the key `foo` must contain a bool is achieved by applying a `Type('bool')` constraint on the `foo` key with `Collection`.

Yes, I appreciate this _can_ be done, but it's very verbose if all you want to do is validate the type structure of an array - it requires you to instantiate a new constraint object for each key. The very reason I developed this constraint is because I was getting tired of doing this when all I wanted was to say "this key should be a string, this key should be bool or null" etc. So this constraint achieves the desired behaviour in a single constraint with an easy to read mapping of strings.

Thank you for your feedback though - I'm trying to gauge the level of interest and that of course includes for and against. No point raising a PR if the weight of consensus in the community is "ehh, probably don't need it" so that's exactly what I'm here for.

**Comment by n0rbyt3** [comment]
For me this ```Structure``` constraint is not as flexible as the ```Collection``` in combination with ```All```, ```Required``` and ```Optional```. For example how can I define that the inner array ```bip``` must not contain extra keys or that the inner key ```bap``` must contain int values greater than zero?

```Structure``` has a lot limitations. Imagine your example and you need to define more validations for a key. The developer is forced to refactor the whole constraint in that situation. With Symfonys build-in constraints, these limitations do not exist.

The ```Structure``` constraint has only one advantage: it can check types on optional keys, whereas ```Collection``` only has the option whether optional keys are allowed or not. There is currently no way (I know of) to validate optional key types.

**Comment by dwgebler** [comment]
@n0rbyt3 thanks for your feedback. `Structure` is not intended as a replacement for `Collection`, rather it is intended for cases where the _only_ thing you want to validate is type structure of an array. If you later need to define more value-based validations for an array's elements, you should either combine `Structure` with other constraints, or use a more verbose `Collection` constraint with as many constraints inside as you need.

> For example how can I define that the inner array bip must not contain extra keys or that the inner key bap must contain int values greater than zero?

The option for (dis)allowing extra keys could be easily addressed in `Structure` if I were to go for a PR. Of course in the case of value-based validations, the above applies again.

The benefit I'm suggesting is basically one of convenience, readability and brevity. It's about being able to write:

```
new Structure([
    'foo' => 'int',
    'baz' => 'string|int',
    'bip' => [
        'bap' => 'int',
    ],
]);
```

rather than:

```
$constraint = new Collection(
    fields: [
        'foo' => [new NotNull(), new Type('int')],
        'baz' => [new NotNull(), new AtLeastOneOf([new Type('string'), new Type('int')])],
        'bip' => new Required([
            new NotNull(),
            new Type('array'),
            new Collection([
                'bap' => [new NotNull(), new Type('int')],
            ]),
        ])
    ],
    allowExtraFields: true,
    allowMissingFields: false,
);
```

when this type-based validation is all you want. So when you just want to say "an array should contain these keys, with these types", including class or enum types (which I don't think is supported by existing core constraints, either?)

If the general feeling is that the latter is preferred and there's no benefit to bringing the former in to core - I take no offence, it was just an idea that other people might benefit from something I wrote for myself that I've found useful. I just want to make sure the motivation behind what I'm proposing is clearly stated and understood. Thanks.

**Comment by ro0NL** [comment]
> The benefit I'm suggesting is basically one of convenience, readability and brevity.

But it's less scalable IMHO.

edit: `new Type('string|int', allowNull: false)` sounds reasonable BTW!

**Comment by stof** [comment]
> The `Structure` constraint has only one advantage: it can check types on optional keys, whereas `Collection` only has the option whether optional keys are allowed or not. There is currently no way (I know of) to validate optional key types.

`Collection` can do that thanks to `Optional` wrapping the constraints applied on that key.

**Comment by n0rbyt3** [comment]
> `Collection` can do that thanks to `Optional` wrapping the constraints applied on that key.

Sorry, I guess I used a wrong expression. ```Optional``` wrapped around a ```Type``` constraint  can check the type of a value for a specific key in a collection if that key is present. However, it is not possible to check that every key (not the value for that key!) is a string. In former projects I used ```Callback``` for that.

**Comment by stof** [comment]
@n0rbyt3 if you want to check that the same constraint applies on all items of an array, what you need is `All`, not `Collection`. `Collection` is about validating array shapes.

**Comment by n0rbyt3** [comment]
@stof ```All``` also validates values, not keys. I know these constraints very well.

**Comment by wouterj** [comment]
In a way this is related to #39372 and I still hold the same opinion about such a feature.

It is never too great to have two ways to achieve the same feature, except if there are clear cases where either is best. In this case, I don't really see this. I don't think we should maintain more or less the same code for both `Collection` and `Structure` constraints.

If you would like to achieve something like this, I would look at it purely as syntax sugar for the `Collection` constraint.
I don't think we should offer this custom string syntax sugar on top of the existing pure PHP one, given the latter benefits from the great ecosystem of IDE autocompletion and static analysis. However, you can of course maintain a bundle or package that adds this syntax sugar layer for the `Collection` constraint.

Given 2 core team members are not to fond of adding the proposed feature to Symfony, and the preceded rejected issue, I'm going to close this issue as I don't think there is an interest from the core team to maintain this.

**Comment by stof** [comment]
@n0rbyt3 Well, anyway, due to the behavior of PHP casting numeric strings to integer keys in an array, I'm not sure this validation makes sense.
