### ISSUE TITLE
[Intl] Unpack error on Windows

### ISSUE THREAD

**Issue by knallcharge** [symfony/symfony#50489]
### Symfony version(s) affected

6.3.0

### Description

Updating to Symfony 6.3 (from 6.2.11) will result in the following error when using symfony/intl on Windows:

Failed to extract symfony/intl: (2) "C:\Program Files\7-Zip\7z.EXE" x -bb0 -y C:\(...)\vendor\composer\tmp-a4106ccbdd1bc6d89799dcf02d3e78ee -oC:\(...)\vendor\composer\291efae8

ERROR: Data Error : intl-49c7d14fc0465813e85b7cbbda49844af208d95a\Resources\data\transliterator\emoji\emoji-dsb.php

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
Unzip with 7z command failed, falling back to ZipArchive class

### How to reproduce

Upgrade to Symfony 6.3 on Windows.

**Comment by nicolas-grekas** [comment]
Strange, I didn't spot any identical file names with different capitalization, did you?
Can you try opening the file on your own and see if this happens also, and if you can get more logs from 7zip?
https://github.com/symfony/intl/archive/refs/tags/v6.3.0.zip

**Comment by maxbeckers** [comment]
For me (using windows 10) it works fine using 7zip when i download the zip @nicolas-grekas mentioned.

``composer require symfony/intl`` is also successful.

**Comment by knallcharge** [comment]
I don't see any identical filenames, also I can open and extract the zip you linked to, so unfortunately I don't have any further information or error messages.
I thought maybe it was due to updating, so an older version of "intl" had a duplicate filename with other capitalization (e.g. old "file_AB.php", new "file_ab.php") which would confuse 7-zip, but also couldn't find any.
But still executing `composer require symfony/intl` in a project that was not using intl before will show the error.
Maybe it's something completely different (as the error message from 7-zip just seems to be a guess), but I'm out of ideas for now.

**Comment by maxbeckers** [comment]
Could you try to create a reproducer? Then I'd also have a look on that. For a clean symfony 6.3 inatallation i had no problems with it.

**Comment by knallcharge** [comment]
Tried and failed :) Created a new project via the symfony console-command, executed `composer require symfony/intl` and everything worked as expected.
Closing this as it seems to be some strange setup issue (maybe with XAMPP) that happens on all my symfony-projects but can't be reproduced. Also the intl-component seems to be running fine as composer itself is saying "falling back to ZipArchive class" which does not issue any error.
Sorry for the inconvenience.
