### ISSUE TITLE
using var-dumper as standalone, expand or collapse not working

### ISSUE THREAD

**Issue by anovsiradj** [symfony/symfony#50487]
### Symfony version(s) affected

n/a

### Description

after upgrading var-dumper to 6.3, when using `dump()` or `dd()`, expand or collapse for object/array/string suddenly not working.

<img width="371" alt="image" src="https://github.com/symfony/symfony/assets/6737021/f2596aeb-5c75-451f-99bf-bdbfdffd59d8">

https://github.com/symfony/symfony/assets/6737021/240856c0-3a7e-40c5-89c3-505115154cea

### How to reproduce

- `composer init` then install `symfony/var-dumper` v6.3
- open `index.php` in browser
- expand or collapse not working

[composer.json.txt](https://github.com/symfony/symfony/files/11607410/composer.json.txt)
[index.php.txt](https://github.com/symfony/symfony/files/11607411/index.php.txt)

### Additional Context

- browser: Chrome
- platform: Windows
- user agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

**Comment by nicolas-grekas** [comment]
This might be related to #49977. WDYT @ohader?

**Comment by ohader** [comment]
> This might be related to #49977. WDYT @ohader?

It is, since that change expected the generated markup to be embedded in `<html><body>...</body></html>`.

https://github.com/symfony/symfony/pull/49977/files#diff-0cc0f96ad1dd7b1ff438e1754a4cbc1020d242586ef3cb407f1523656230bd11R152-R154

**Comment by nicolas-grekas** [comment]
Any way to remove this expectation?

**Comment by MatTheCat** [comment]
I don’t know if `<body>` was chosen for a specific reason? If not you can add the `sf-js-enabled` class on `<html>` (using `doc.documentElement`).

**Comment by ohader** [comment]
This should do the trick...

```patch
diff --git a/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php b/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php
index 345a89cf72..8a2570b2c4 100644
--- a/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php
+++ b/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php
@@ -163,9 +163,7 @@ class HtmlDumper extends CliDumper
 <script>
 Sfdump = window.Sfdump || (function (doc) {

-if (doc.body instanceof HTMLElement) {
-    doc.body.classList.add('sf-js-enabled');
-}
+doc.documentElement.classList.add('sf-js-enabled');

 var rxEsc = /([.*+?^${}()|\[\]\/\\])/g,
     idRx = /\bsf-dump-\d+-ref[012]\w+\b/,
```

**Comment by anovsiradj** [comment]
based on previous comments, i came up with a temporary workaround.
by override the function and echo `<html><body>` on first run 😳

```php
function dump(...$vars)
{
	static $first = true;
	if ($first) {
		$first = false;
		echo '<html><body>';
	}
	foreach ($vars as $var) {
		\Symfony\Component\VarDumper\VarDumper::dump($var);
	}
}
function dd(...$vars)
{
	dump(...$vars);
	exit(1);
}
```

**Comment by MatTheCat** [comment]
@anovsiradj doesn’t https://github.com/symfony/symfony/issues/50487#issuecomment-1569633483 work for you?

**Comment by anovsiradj** [comment]
> @anovsiradj doesn’t [#50487 (comment)](https://github.com/symfony/symfony/issues/50487#issuecomment-1569633483) work for you?

i just try it, yes it is work.

**Comment by cryank** [comment]
Hi @nicolas-grekas  @ohader, 

I am not sure if this change brings back the JavaScript issue mentioned in #39394.
![image](https://github.com/symfony/symfony/assets/4370869/3c424db2-197d-49a7-b5f3-55e44e635939)

I noticed that the HTML was rendered with the CSS style `display: none`. I reverted the change below and was able to show the value of `#items` again.
```
-if (doc.body instanceof HTMLElement) {
-    doc.body.classList.add('sf-js-enabled');
-}

+doc.documentElement.classList.add('sf-js-enabled');
```

Since the issue mentioned was in v5.2, and the code changes in #39525 are very different in v6.3, would you mind taking a look to see if this is related?

Thank you so much.

**Comment by ohader** [comment]
@cryank Actually the CSS class `sf-js-enabled` is applied by JavaScript, and only then `display: none` would be applied (commit 53046a3bac55cbb9c4a1fbfa67739b2ee08cef36 was the corresponding change).

Can you please past the complete CSS rule that shows, why `display: none` was used?

**Comment by cryank** [comment]
@ohader 
did you mean this ? 
![image](https://github.com/symfony/symfony/assets/4370869/c49e15fa-573c-484a-9688-83c16825cc57)


I noticed that the expand/collapse arrow button is missing too.

**Comment by ohader** [comment]
That's strange. I was not able to reproduce that (using latest commit 9767270b34e97d1bbf340f9ab3358a0178dccb8a of the 6.4 branch).

<img width="1098" alt="Screenshot 2023-10-04 at 11 32 07" src="https://github.com/symfony/symfony/assets/402145/0d7bf12f-8528-4773-a3de-475999015494">

Can you share the created HTML markup and the PHP source that was used to create the output? Maybe referenced in a separate Gist to avoid blowing up this issue? Thx in advance!

**Comment by cryank** [comment]
I added dd() in an api call, and response like https://gist.github.com/cryank/b3ebe7d6af2406edd77344e49fe8e9f1

when the ajax call is 500, I checked if the response data includes `<script> Sfdump = window.Sfdump`  and emit a modal to display the dd response on the front-end  



However when I created a static page to dd the same array, everything just looks fine

**Comment by ohader** [comment]
I'm glad to hear, that it works on static pages (phew 😅). Thus, this seems to be an edge case with those modals, and how content is applied in your custom JavaScript.
