### ISSUE TITLE
You have requested a non-existent service "debug.error_handler_configurator".

### ISSUE THREAD

**Issue by TheNerka** [symfony/symfony#50504]
### Symfony version(s) affected

6.3.0

### Description

after upgrade symfony from 6.2 to 6.3 calls cache clear got error:

You have requested a non-existent service "debug.error_handler_configurator".

### How to reproduce

upgrade from 6.2 to 6.3

**Comment by stloyd** [comment]
Duplicate of https://github.com/symfony/symfony/issues/50491

**Comment by xabbuh** [comment]
Does #50498 fix this?

**Comment by OleksiiBulba** [comment]
Hello! Is there any possible workaround to fix this error message before the fix will be released?

**Comment by stof** [comment]
@OleksiiBulba you can use the dev version of the package.

Alternatively, you could remove the old cache (the one generated by the old version of Symfony) with `rm -rf var/cache/prod/*`

**Comment by OleksiiBulba** [comment]
Thanks @stof, updating to the dev package and downgrading back to release helped (I did it before seeing your answer) :)
