### ISSUE TITLE
[Cache] Issue with RedisTrait::createConnection miss processing redis_cluster value

### ISSUE THREAD

**Issue by darkanakin41** [symfony/symfony#50509]
### Symfony version(s) affected

6.3.0

### Description

When trying to initialize a redis cluster connection through symfony/cache RedisAdapter::createConnection, the method returns a RedisArray instead of a RedisCluster

With this issue, i have to manually set the class in the DSN to \RedisCluster in order for it to work.

### How to reproduce

Simply pass one of the following strings as DSN to the method : 

```php
RedisAdapter::createConnection('redis:?host[redis_cluster:7000]&host[redis_cluster:7001]&redis_cluster=1&timeout=1&read_timeout=2&persistent=1')

RedisAdapter::createConnection('redis:?host[redis_cluster:7000]&host[redis_cluster:7001]&redis_cluster=true&timeout=1&read_timeout=2&persistent=1')
```

You will get a RedisArray class.

### Possible Solution

In the RedisTrait class, starting from line 180 : 
```php
$class = $params['class'] ?? match (true) {
            (bool) $params['redis_cluster'] => \extension_loaded('redis') ? \RedisCluster::class : \Predis\Client::class,
            isset($params['redis_sentinel']) => match (true) {
                \extension_loaded('redis') => \Redis::class,
                \extension_loaded('relay') => Relay::class,
                default => \Predis\Client::class,
            },
            1 < \count($hosts) && \extension_loaded('redis') => 1 < \count($hosts) ? \RedisArray::class : \Redis::class,
            \extension_loaded('redis') => \Redis::class,
            \extension_loaded('relay') => Relay::class,
            default => \Predis\Client::class,
        };
```

**Comment by xabbuh** [comment]
Would you mind sending a pull request with what you have in mind?

**Comment by lugosium** [comment]
Hello,

After upgrading to Symfony 6.3 i have issue with the container, redis and the `lint:container`:

`First array member is not a valid class name or object`

In `\Symfony\Component\DependencyInjection\ContainerBuilder::createService:1120`

`$service = $factory(...$arguments);`

$factory:

```
^ array:2 [
  0 => null
  1 => "createConnection"
]
```

$arguments:

```
^ array:2 [
  0 => "redis://lugosium-redis"
  1 => array:1 [
    "lazy" => true
  ]
```

It does not seems to correctly determine the Redis adapter.
I am not using Redis cluster option.

Hope it helps.

**Comment by pkruithof** [comment]
We just got bit by this: we had some downtime because the application could not connect to our Redis cluster. Although it's a good opportunity for us to start thinking about smoke tests again, I wonder why Symfony 6.3 was shipped knowing about this bug. I understand that you cannot delay such a release because of some bug report, but maybe the change in this class could have been reverted before the 6.3 release?

I'm curious about the process here, and if this is something to review. To be clear: I fully understand these things can happen, but it decreases the trust with upgrading a minor release a bit.

**Comment by stof** [comment]
@pkruithof this bug was reported **after** the release

**Comment by pkruithof** [comment]
Ah crap, I should've checked that, I was thinking it was released about 3/4 days ago. Sorry about that.

**Comment by darkanakin41** [comment]
PR opened :)
