### ISSUE TITLE
MapEntity problem 

### ISSUE THREAD

**Issue by themark147** [symfony/symfony#50528]
### Symfony version(s) affected

6.3.0

### Description

Hi

Im tryin to use MapEntity attribute but I have a problem with error:
You have requested a non-existent resolver \"Symfony\\Bridge\\Doctrine\\ArgumentResolver\\EntityValueResolver\". Did you mean \"argument_resolver.not_tagged_controller\", \"doctrine.orm.entity_value_resolver\"?"

With version 6.3.0-BETA3 I had no problem with that and I cannot find why :thinking: its works well on 6.3-BETA3

### How to reproduce

probably set optional resolver for MapEntity attribute as doctrine.orm.entity_value_resolver instead of EntityValueResolver::class?

**Comment by nicolas-grekas** [comment]
please ensure that you have the latest version of doctrine-bundle
