### ISSUE TITLE
[HttpClient] CURLOPT_POSTREDIR not taken into account while redirecting

### ISSUE THREAD

**Issue by jrantwijk** [symfony/symfony#50520]
### Symfony version(s) affected

6.2

### Description

Currently the HttpClient allows setting the option `CURLOPT_POSTREDIR` that controls how libcurl acts on redirects after POSTs that get a 301, 302 or 303 response back. However, the CurlResponse does not seem to take into account this option and strictly redirects to HEAD or GET. 

### How to reproduce

Create a `POST` request with the `CurlHttpClient` to an HTTP endpoint that redirects with the status 301, 302 or 303. The next hop wil be done using `GET`. This is correct.

Now do the same using the `CURLOPT_POSTREDIR` option. The next hop (redirect) will be made using `GET`, while I expect `POST`.

### Possible Solution

This option should checked on `CurlResponse.php:415`. Second, we have to make sure that while using this option, the POST body will be included while redirecting. I didn't test this, but `CurlResponse.php:395` does seem to empty `CURLOPT_POSTFIELDS` when it is a POST redirect. Of course, this should only be done when the `CURLOPT_POSTREDIR` is present.

The curl [documentation](https://curl.se/libcurl/c/CURLOPT_POSTREDIR.html) states that this option has several flags to control the behaviour. 

> Pass a bitmask to control how libcurl acts on redirects after POSTs that get a 301, 302 or 303 response back. A parameter with bit 0 set (value CURL_REDIR_POST_301) tells the library to respect [RFC 7231](http://www.ietf.org/rfc/rfc7231.txt) (section 6.4.2 to 6.4.4) and not convert POST requests into GET requests when following a 301 redirection. Setting bit 1 (value CURL_REDIR_POST_302) makes libcurl maintain the request method after a 302 redirect whilst setting bit 2 (value CURL_REDIR_POST_303) makes libcurl maintain the request method after a 303 redirect. The value CURL_REDIR_POST_ALL is a convenience define that sets all three bits

**Comment by nicolas-grekas** [comment]
Using `CURLOPT_POSTREDIR` as described isn't supported, we should add it to the existing denylist (up for a PR?)

What you need to do instead is deal with the redirection logic on your own. For that, you need to set `max_redirects` option to 0 and check the status code and do your logic as fits. Note that `$response->getInfo('redirect_url')` will contain the resolved target of the redirection.

**Comment by jrantwijk** [comment]
May I ask why we shouldn't add support for this option? It is relatively easy to implement and does not seem to break backwards compatibility.

The CurlHttpClient is following what [RFC 7231 suggests](https://www.rfc-editor.org/rfc/rfc7231#section-6.4.2), which is the behaviour of most user-agents because of historical reasons. However, in my case this is not desirable and I do not have control over the endpoint, which is why the option `CURLOPT_POSTREDIR` exists.. 

Supporting `CURLOPT_POSTREDIR` in the CurlHttpClient, will save me and probably others quite some headache of writing custom redirect logic. This problem will occur every time a HTTP endpoint does not follow the **historical** redirect flow.

If preferred, I will create a PR for it.

**Comment by nicolas-grekas** [comment]
Reimplementing the logic to do what you want should be just a few lines away. Enabling the option means encouraging tight coupling to curl. Here, it's possible (and not that hard I believe) to implement this on your side.

A more technical reason is that we don't let curl handle redirections on its own, so just setting the option won't work.

**Comment by nicolas-grekas** [comment]
Closing as explained. The option is now going to be explicitly rejected after #50728. I hope you managed to implement the logic on your side.
