### ISSUE TITLE
[Validator] Return types change on ExecutionContextInterface break BC

### ISSUE THREAD

**Issue by upchuk** [symfony/symfony#50526]
### Symfony version(s) affected

6.3.0

### Description

Hello,

I noticed that in 6.3.0 version of the Validator, the ExecutionContextInterface got it's public method signatures updated to add  a return type: https://github.com/symfony/validator/commit/c2801bcde41f42c0fbaa9c64b4ad1e82f7199ad5.

This breaks any implementation of the ExecutionContextInterface. AFAIK, minors should not make changes to public APIs no? 

Thanks!

### How to reproduce

No real steps.

**Comment by nicolas-grekas** [comment]
Can you please send a PR to turn them into `@return void` annotations?

**Comment by wouterj** [comment]
We only added PHP return types to the `@internal` methods. This is expected, as per [BC promise](https://symfony.com/bc):

 > [Experimental Features](https://symfony.com/doc/current/contributing/code/experimental.html) and code marked with the `@internal` tags are excluded from our Backward Compatibility promise.

**Comment by wouterj** [comment]
Hi @upchuk. After a quick internal discussion, we've concluded that it was wrong to mark these methods as internal (as the interface is not internal). I've submitted a PR to remove the internal annotation: https://github.com/symfony/symfony/pull/50539

I see you started creating a PR for the return type already, can you finish that so we can give you credits for finding and reporting this issue? :)

**Comment by upchuk** [comment]
@wouterj Sure, opened https://github.com/symfony/symfony/pull/50540. Wasnt sure which branch to open against, I did it against 6.3

**Comment by upchuk** [comment]
@nicolas-grekas @stof Thanks for this. Do you plan on making a patch release to 6.3.0 to include this change? As it stands, we some problems in Drupal which implements this interface. Thanks!

**Comment by wouterj** [comment]
Yes, there will for sure be a 6.3.1 :)

Normally, we release patch releases once a month. After a new minor release, we sometimes release 6.3.1 a bit quicker, but we also want to gather as much bug fixes for the .1 release as possible. Given there are no big bugs in 6.3.0, I think you can expect a 6.3.1 release in 1 to 3 weeks.

**Comment by upchuk** [comment]
@wouterj ok, cool, thanks!
