### ISSUE TITLE
User Deprecated: The "url" connection parameter is deprecated

### ISSUE THREAD

**Issue by 99hops** [symfony/symfony#50559]
### Symfony version(s) affected

6.3.0

### Description

I see this deprecation in 6.3 and looking at [#doctrine-dbal-configuration](https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration) nothing changed, we still use the url parameter there.

`deprecation.INFO: User Deprecated: The "url" connection parameter is deprecated. Please use Doctrine\DBAL\Tools\DsnParser to parse a database url before calling Doctrine\DBAL\DriverManager. (DriverManager.php:256 called by DriverManager.php:172, https://github.com/doctrine/dbal/pull/5843, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"url\" connection parameter is deprecated. Please use Doctrine\\DBAL\\Tools\\DsnParser to parse a database url before calling Doctrine\\DBAL\\DriverManager. (DriverManager.php:256 called by DriverManager.php:172, https://github.com/doctrine/dbal/pull/5843, package doctrine/dbal) at /var/www/html/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:209)"} []`

`deprecation.INFO: User Deprecated: Doctrine\DBAL\Connection::getEventManager is deprecated. (Connection.php:296 called by EntityManager.php:167, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Doctrine\\DBAL\\Connection::getEventManager is deprecated. (Connection.php:296 called by EntityManager.php:167, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal) at /var/www/html/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:209)"} []`

### How to reproduce

```
"doctrine/orm": "^2.15",
"doctrine/annotations": "^2.0",
"doctrine/doctrine-bundle": "^2.9",
"doctrine/doctrine-migrations-bundle": "^3.2"
```

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
```

**Comment by dmaicher** [comment]
See https://github.com/doctrine/DoctrineBundle/issues/1665

This will be fixed on DoctrineBundle

**Comment by 99hops** [comment]
@dmaicher Thanks, Al (:
