### ISSUE TITLE
[Mailer] [Sendinblue template] A message must have a text or an HTML part or attachments (which is not true)

### ISSUE THREAD

**Issue by johndodev** [symfony/symfony#50557]
### Symfony version(s) affected

6.2.10

### Description

Hello,

I'd like to send email via sendinblue (brevo..), with the mailer as described there : https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Mailer/Bridge/Sendinblue/README.md

I want to use the template functionality : the content of the mail is set in a sendinblue template, IN Sendinblue.

Problem is, when I try to send an email without content specified in the code, exception from mailer : 
**A message must have a text or an HTML part or attachments**

It is the same problem with the from email, it is set in sendinblue but we can't send emails without "from" in the code.
**An email must have a "From" or a "Sender" header.**

It is actually working when I put fake content in the mail (and a real from email).

### How to reproduce

This is not working : 

```
$params = ['foo' => 'bar'];
$metaDatas = json_encode(['a' => 'b']);

$email = new Email();
$email->to('...');
$email
    ->getHeaders()
    ->add(new MetadataHeader('custom', $metaDatas))
    ->addTextHeader('templateId', '1')
    ->addParameterizedHeader('params', 'params', $params);
$mailer->send($email);
```

This is working (but it's confusing)

```
$params = ['foo' => 'bar'];
$metaDatas = json_encode(['a' => 'b']);

$email = new Email();
$email->to('...');
**$email->from('real@sender.com');** // used by sendinblue if sended (so unable to let the default one set in the template)
**$email->text('ignored text');** // totally ignored because we have set a "templateId" parameter (below)
$email
    ->getHeaders()
    ->add(new MetadataHeader('custom', $metaDatas))
    ->addTextHeader('templateId', '1')
    ->addParameterizedHeader('params', 'params', $params);
$mailer->send($email);
```

### Possible Solution

Maybe add a custom header to ask symfony to bypass its checks ?

I realize it's not a big bug, and a specific use case, but if it cannot be fixed, it should be documented in the sendinblue component (https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Mailer/Bridge/Sendinblue/README.md).

**Comment by stof** [comment]
The template feature is not supported by the sendinblue bridge because there is no way to create a non-leaky abstraction in the mailer component that would map to it.

If your goal is to use such feature of Sendinblue, you should use their API directly, not the mailer component.
