### ISSUE TITLE
[VarDumper] Expand // Collapse is broken (6.3)

### ISSUE THREAD

**Issue by ckamaury** [symfony/symfony#50553]
### Symfony version(s) affected

6.3.0

### Description

Hello,

Since my upgrade 6.2.11 --> 6.3.0 , the var dumper doesn't work on all my projects .. Exaclty like this old issue : 
[https://github.com/symfony/symfony/issues/48545]

**Collapse/Expand is broken, all data are expanded.**

Windows 11 with : 
- Chrome 114.0.5735.91
- Firefox 113.0.2

### How to reproduce

[https://github.com/symfony/symfony/issues/48545]

**Comment by xabbuh** [comment]
Could this be the same bug reported in #50487? And if so, does the fix done in #50493 fix your issue too?

**Comment by ckamaury** [comment]
Sry, I didn't see this issue .. And the temporary fix work #50493. Thx
