### ISSUE TITLE
[Mime] Allow not RFC-compliant addresses

### ISSUE THREAD

**Issue by takaram** [symfony/symfony#50592]
### Description

`Symfony\Component\Mime\Address` only accepts RFC-compliant addresses. Otherwise the constructor throws `RfcComplianceException`.

This works for most users, but I want to change this behavior.
Until several years ago, some cell-phone carriers in Japan used to allow users to create an RFC-incompliant email address, e.g. `foo..bar@example.com` (with two consecutive dots).
I would like to send an email to such addresses with mailer component.

One possible solution is to make `EmailValidation` configurable.
`Address` class uses `Egulias\EmailValidator\Validation\MessageIDValidation` or `Egulias\EmailValidator\Validation\RFCValidation`. These classes implements the rule of validation.
https://github.com/symfony/mime/blob/6.3/Address.php#L53
Introducing `Address::setEmailValidation(EmailValidation $emailValidation)` will allow users to employ their own validation rule.

### Example

```php
<?php
use Symfony\Component\Mime\Address;
use Egulias\EmailValidator\Validation\EmailValidation;

$customValidation = new class implements EmailValidation {
    public function isValid(string $email, EmailLexer $emailLexer): bool
    {
        // implement custom validation rule
    }

    // implement getErrors and getWarnings too
};
Address::setEmailValidation($customValidation);

Address::create('foo..bar@example.com'); // Validated by the custom rule
(new Email())->to('foo..bar@example.com'); // Validated by the custom rule too
```

**Comment by stof** [comment]
adding a global state for the email validation being used looks like a bad idea to me.

**Comment by gisostallenberg** [comment]
Wouldn't it be better if Address has an interface and is attainable and Symfony would just trust that string value?

**Comment by fabpot** [comment]
Support for such email addresses is something I added to Swiftmailer back then. Maybe it should be supported by `egulias/email-validator` package?
