### ISSUE TITLE
﻿﻿symfony/mailgun-mailer should require symfony/http-client

### ISSUE THREAD

**Issue by FlorianMoser** [symfony/symfony#50598]
### Symfony version(s) affected

6.3.0

### Description

symfony/mailgun-mailer has a dependency on symfony/http-client, but symfony/http-client is only present as "require-dev".

### How to reproduce

Require ﻿﻿symfony/mailgun-mailer in a project that doesn't use symfony/http-client.

### Possible Solution

Move the symfony/http-client dependency from "require-dev" to "require" in the composer.json file.

### Additional Context

We used symfony/mailgun-mailer in a Laravel installation. After upgrading Laravel (and no longer using symfony/http-client), form submission were no longer mailed. An issue that was only discovered after 2 month and caused severe troubles for our client.

It should be an easy fix for a quite severe problem (in some cases).

**Comment by derrabus** [comment]
You don't need the HTTP client if you interface with mailgun via SMTP. That's why it's optional.

Maybe this should be documented better.

**Comment by derrabus** [comment]
I've filed symfony/symfony-docs#18386 for that matter.

**Comment by xabbuh** [comment]
closing in favour of symfony/symfony-docs#18386 then

**Comment by FlorianMoser** [comment]
I see, that makes sense.

Thanks @derrabus !
