### ISSUE TITLE
Debug is permanently expanded 

### ISSUE THREAD

**Issue by Wordlesschunk** [symfony/symfony#50605]
### Symfony version(s) affected

6.3.*

### Description

I've recently started a new project within Symfony 6.3.* and It seems that everytime i go to dd($foo) the debug page is permanently expanded (see image below) and im **unable** to close the expanded elements. For note im using the symfony cli server to serve the webpage
![image](https://github.com/symfony/symfony/assets/22942020/838a0d9f-eb27-40d9-a773-80572bcc4a0c)

Debugging i've done:

- Disable any custom styling and javascript I have
- Uninstalled debug symfony/debug-bundle
- Uninstalled debug symfony/web-profiler-bundle
- Reinstalled both ^
- Downgraded my symfony version from 6.3.* -> 6.2.* **(This fixed the issue)**

### How to reproduce

Very simple, have an array of data, it can be anything objects, strings, ints. Use the dd() (dump die) command within any rendered class, the debug page should be fully expanded and user should not be able close the expanded elements

### Possible Solution

N/A

**Comment by HypeMC** [comment]
This has already been fixed in #50493 and will be available in 6.3.1.
