### ISSUE TITLE
Form PUT requests improperly handled by Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler::handleRequest

### ISSUE THREAD

**Issue by nbennett25** [symfony/symfony#50606]
### Symfony version(s) affected

6.2.1

### Description

When creating a form with a method of `PUT`, the form is rendered on the front end as a `POST` with a `_method` input of `PUT` - as expected. 

However the `HttpFoundationRequestHandler::handleRequest()` method checks the form configured method (`PUT`) against the `$request` method (`POST`) and fails to take any action:

`Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler::handleRequest:45:`
```
$method = $form->getConfig()->getMethod();

if ($method !== $request->getMethod()) {
     return;
 }
```

Github:
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L47

### How to reproduce

1. Using a FormBuilder class, create a form with a `PUT` method.
2. On the front end, render the form, add data and submit

Expected Result:
1. Data submitted is persisted

Actual Result:
1. No action is taken

### Possible Solution

Remove the check against the method types, or modify to allow a match between the `PUT` and `POST` methods.

### Additional Context

Notes: 
1. Removing the `return` statement allows the form to be submitted properly. 
2. Steps to reproduce are in an env which includes the `config.yaml` line: `http_method_override: true`

Even though it doesn't seem to be working, if the intention is to allow `http_method_override: true` to use the `_method` input to override the `PUT` to a `POST`, this is not intuitive and at a bare minimum should be noted in the doc block of the `HttpFoundationRequestHandler` class.

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

Also, please make sure you've tested with the latest bugfix release of the Symfony branch your app runs on. Your version 6.2.1 is a bit outdated, please test with 6.2.11 or 6.3.0.

**Comment by nbennett25** [comment]
Thx @derrabus  - I sorted it out - I had the `http_method_override` config setting being overridden in a different yaml file. This seems to be working as expected after updating `http_method_override` to `true` instead of `false`.
