### ISSUE TITLE
[StimulusBundle] Add stimulus_outlet() twig function

### ISSUE THREAD

**Issue by pmishev** [symfony/symfony#50601]
### Description

Do you have plans to add a `stimulus_outlet()` twig function in `symfony/stimulus-bundle`?

https://stimulus.hotwired.dev/reference/outlets

### Example

`{{ stimulus_outlet('controllerName', 'targetControllerName', 'cssSelector') }}`

**Comment by stof** [comment]
I would say that a Pr is welcome for that. However, StimulusBundle is part of the UX initiative maintained at https://github.com/symfony/ux

**Comment by pmishev** [comment]
ah, apologies, didn't know that, I opened the issue there.
https://github.com/symfony/ux/issues/933
