### ISSUE TITLE
[Validator] Validation failed: no DTD found !

### ISSUE THREAD

**Issue by Neirda24** [symfony/symfony#50618]
### Symfony version(s) affected

5.4.x

### Description

It seems there are typos in `.xlf` files in the validator component. See for example https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.en.xlf#L411 

```diff
- <target>The password strength is too low. Please use a stronger password.</source>
+ <target>The password strength is too low. Please use a stronger password.</target>
```

It seems to be present on several xlf files which prevent the clear cache from working.

### How to reproduce

Install the `5.x-dev` version of validator component and try to do `cache:clear`

**Comment by nicolas-grekas** [comment]
please send a PR, it should target branch 5.4 :pray:
