### ISSUE TITLE
Improve fileLinkFormat / SYMFONY_IDE configuration outside Symfony

### ISSUE THREAD

**Issue by nlemoine** [symfony/symfony#50619]
### Description

Hello,

I mostly use Symfony components in a standalone way (outside Symfony Framework) and sometimes find quite hard to handle the `fileLinkFormat` globally. 

## error-handler

https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php#L55-L58

Although it has been easier to setup since `SYMFONY_IDE` env var was introduced, this works perfectly if you don't use a container (Docker, etc.). But the [link format described here](https://symfony.com/doc/current/reference/configuration/framework.html#ide:~:text=When%20running%20your%20app%20in%20a%20container%20or%20in%20a%20virtual%20machine) to handle path mapping won't work with the only `SYMFONY_IDE` env var set. In such case, you will have to set a custom exception handler overriding the default one here:

https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L647-L662

Just to provide a default [`new FileLinkFormatter()`](https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php#L40) object to the `HtmlErrorRenderer` renderer.

```php
$handler->setExceptionHandler(function renderException(\Throwable $exception) use($debug): void
{
    $renderer = \in_array(\PHP_SAPI, ['cli', 'phpdbg'], true) ? new CliErrorRenderer() : new HtmlErrorRenderer(
        $debug, 
        null, 
        new FileLinkFormatter() // <-- HERE
    );

    $exception = $renderer->render($exception);

    if (!headers_sent()) {
        http_response_code($exception->getStatusCode());

        foreach ($exception->getHeaders() as $name => $value) {
            header($name.': '.$value, false);
        }
    }

    echo $exception->getAsString();
});
```

And this will only work for Html errors since the CliErrorRenderer will use the `var-dumper` component.

## var-dumper

In a non Symfony app, the `var-dumper` will almost always fall into the default case here: https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/VarDumper/VarDumper.php#L91-L92

If you  want your links to be fully functional (e.g. path mapping replacements working in a docker context), you'll have to override the handler:

```php
$cloner = new VarCloner();
$cloner->addCasters(ReflectionCaster::UNSET_CLOSURE_FILE_INFO);
$dumper = in_array(PHP_SAPI, array('cli', 'phpdbg'), true) ? new CliDumper() : new HtmlDumper();
$dumper->setDisplayOptions(['fileLinkFormat' => new FileLinkFormatter()]);

// Configure VarDumper
VarDumper::setHandler(function ($var, ?string $label = null) use ($cloner, $dumper): void {
    $var = $cloner->cloneVar($var);

    if (null !== $label) {
        $var = $var->withContext(['label' => $label]);
    }

    $dumper->dump($var);
});
``` 

It would nice to make fileLinkFormat more easily consistent/configurable when used outside Symfony.

**Comment by ro0NL** [comment]
> path mapping won't work with the only SYMFONY_IDE env var set

are you sure? it works for me in framework context, but it should work everywhere IMHO

we havent configured `framework.ide` either since #44575

**Comment by nlemoine** [comment]
Just tested and confirm path mapping won't work in standalone mode:

```php
<?php

$_ENV['SYMFONY_IDE'] = 'vscode://file/%f:%l&/user/name/sites/issue-50619/>/projects/my_project/'; # Don't work :(
// $_ENV['SYMFONY_IDE'] = 'vscode://file/%f:%l'; # Works fine :)
// $_ENV['SYMFONY_IDE'] = 'vscode'; # Works fine :)

use Symfony\Component\ErrorHandler\Debug;

require_once 'vendor/autoload.php';

Debug::enable();

trigger_error('This is an error', E_USER_ERROR);

// Getting link
// vscode://file//user/name/sites/issue-50619/index.php:13&/user/name/sites/issue-50619/>/projects/my_project/

```

> but it should work everywhere IMHO

That's what I think too 🙂

**Comment by ro0NL** [comment]
IIUC it's because we get a unconfigured SourceContextProvider: https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/VarDumper/VarDumper.php#L96

compared to eg. server format: https://github.com/symfony/symfony/blob/42d43b7ba563b0e9841faaa545289b423917de6d/src/Symfony/Component/VarDumper/VarDumper.php#L124

perhaps it's as simple to to initialize a default FileLinkFormatter in SourceContextProvider :thinking:

**Comment by ro0NL** [comment]
the issue is in `HtmlErrorRenderer`

fix:

```diff
- $fileLinkFormat ??= $_ENV['SYMFONY_IDE'] ?? $_SERVER['SYMFONY_IDE'] ?? null;
+ $fileLinkFormat ??= new FileLinkFormatter();
```

**Comment by nlemoine** [comment]
[This one](https://github.com/symfony/symfony/issues/50619#issuecomment-1584886005) resolves the issue with the `error-handler` in a non cli context only.

Maybe the same kind of logic could be applied to the `var-dumper` component?
