### ISSUE TITLE
Add $entityRepository->getNext() and $entityRepository->getPrevious()

### ISSUE THREAD

**Issue by nbennett25** [symfony/symfony#50616]
### Description

It'd be super nice to have methods to get the prev/next entity record built directly into the framework. The only solutions I've seen use raw sql to query for the next/prev available record table id. Given that most tables should have a unique identifier, we should be able to query the class metadata to determine which record to return.

### Example

```
$em = $this->getDoctrine()->getManager();

$entity = $em->getRepository(Entity::class)->find(3);

$previousEntity = $em->getRepository(Entity:class)->find($entity->getId())->getPrevious();
$nextEntity = $em->getRepository(Entity:class)->find($entity->getId())->getNext();
```

**Comment by ghost** [comment]
This should be reported to doctrine/orm, not symfony/symfony

**Comment by chalasr** [comment]
Indeed.

**Comment by xabbuh** [comment]
indeed, closing as explained by @javaDeveloperKid

**Comment by nbennett25** [comment]
Thx - I'll send it over to `doctrine/orm`

**Comment by stof** [comment]
Making the query aware of how to query the table would not fit at all in the doctrine/orm pattern btw. So I'm 99.999% sure they will reject it.
Side note: previous and next by which sorting ? And with which filtering applied ?

**Comment by ghost** [comment]
@stof "making query aware"? You mean entity, right? Yeah, I was thinking the same but left it for guys from doctrine to explain to thr OP. Doctrine uses data mapper pattern and what OP proposes would fit active record pattern.

> previous and next by which sorting

Exactly, identifiers are not sequential integers only but also uuids, custom ids etc.

**Comment by stof** [comment]
@javaDeveloperKid indeed, I meant "entity"
