### ISSUE TITLE
File upload fails due to PHP 8's additon of extra key during the request. (Similar issue:- https://github.com/symfony/symfony/issues/46146)

### ISSUE THREAD

**Issue by touhid1259** [symfony/symfony#50624]
### Symfony version(s) affected

may be all versions

### Description

I was upgrading one project from php 7 to php 8. After the upgrade the file upload failed due to the addition of extra key "full_path" during file upload request by php 8. When I debugged, I found that, in the "FileBag.php" file in symfony/http-foundation has miss match with this extra key "full_path".

![SymfonyBug](https://github.com/symfony/symfony/assets/15913101/dbebfb1d-9da8-491b-980e-9bd3c033be33)

So, due to that, instead of getting "UploadedFile" object, I am getting an array which breaks the code.

### How to reproduce

In any php 8 project, if the symfony/http-foundation is used, then during the file upload if someone tries to access the "UploadedFile" object's method, it throws an error. For example, in the controller, 

`
$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
$uploadedFileObject = $request->files->get('file_to_upload');`  suppose to give you the \HttpFoundation\File\UploadedFile(https://github.com/symfony/http-foundation/blob/6.0/File/UploadedFile.php) Object.

Now calling any accessible method of UploadedFile Class on this $uploadedFileObject variable should through the error.

`$ext = $uploadedFileObject->getClientOriginalExtension();`

**Comment by MatTheCat** [comment]
Seems this was fixed some time ago by #42112

Which version of `symfony/http-foundation` are you using?

**Comment by touhid1259** [comment]
Thanks for your reply. I was using very old version. But, I thought the solution (https://github.com/Largo/symfony-http-foundation/pull/1/commits/45e8d45a170f92e79fde915e8da71b8adc5471ba) was not officially accepted. But, I just checked the recent version of http-foundation and it is the official solution. Sorry, my bad.

Thanks again.

**Comment by MatTheCat** [comment]
Well the “official” solution came with the PR I linked, so you can close this issue!
