### ISSUE TITLE
Enable TaggedLocator extension in AutowirePass

### ISSUE THREAD

**Issue by KerianMM** [symfony/symfony#50630]
### Description

I want to create some collection of services like workflows, but I can't extend `TaggedLocator` to don't repeat the declaration everywhere.

The `AutowirePass::autowireMethod` filters on `TaggedIterator`, `TaggedLocator`, `Autowire` and `MapDecorated`, so my custom attribute is not processed.

I don't know the best way to address this, but without this filter, my `ServiceLocator` is correctly autowired.
Maybe an interface on attributes for autowiring ? Or modify this `AutowirePass::autowireMethod` filter ?

### Example

Attribute extension example

```php

use Symfony\Component\DependencyInjection\Attribute\TaggedLocator;

#[\Attribute(\Attribute::TARGET_PARAMETER)]
class WorkflowStateMachineLocator extends TaggedLocator
{
    public function __construct(array|string $exclude = [])
    {
        parent::__construct(
            tag: 'workflow.state_machine',
            indexAttribute: 'name',
            exclude: $exclude,
        );
    }
}

```

Usage

```php

use Symfony\Component\DependencyInjection\ServiceLocator;

final class MyClass
{
    public function __construct(
        #[WorkflowStateMachineLocator]
        private ServiceLocator $workflows,
    ) {
    }

    // ...
}

```

**Comment by ruudk** [comment]
If you find where it's used, you can maybe find `ReflectionClass::getAttributes` and pass a `ReflectionAttribute::IS_INSTANCEOF` flag. There are plenty of examples in the codebase already doing this, so you could create a PR to add it.

Example PR: https://github.com/symfony/symfony/pull/49433

**Comment by derrabus** [comment]
PR welcome, I guess. 🙂

**Comment by KerianMM** [comment]
After some tests, this issue is already the PR #49433
TaggedLocator now extends Autowire
I close this issue, thanks
