### ISSUE TITLE
[StimulusBundle] The asset "@symfony/stimulus-bundle/loader.js" [...] cannot be found in any asset map paths.

### ISSUE THREAD

**Issue by Spomky** [symfony/symfony#50639]
### Symfony version(s) affected

6.3.0

### Description

Hi,

I am facing an issue with Stimulus Bundle and Asset Map.

> An exception has been thrown during the rendering of a template ("The asset "@symfony/stimulus-bundle/loader.js" mentioned in "importmap.php" cannot be found in any asset map paths.").

The `importmap.php` file is defined as follows:

```php
<?php

/**
 * Returns the import map for this application.
 * ...
 */
return [
    'app' => [
        'path' => 'app.js',
        'preload' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
   // and other declarations
];
```

Ccommand `symfony console debug:config framework` output:

```yaml
Current configuration for extension with alias "framework"
==========================================================

framework:
    asset_mapper:
        paths:
            /home/florent/PhpstormProjects/skeleton-web/vendor/symfony/ux-typed/src/DependencyInjection/../../assets/dist: '@symfony/ux-typed'
            /home/florent/PhpstormProjects/skeleton-web/vendor/web-auth/webauthn-stimulus/src/DependencyInjection/../../assets/dist: '@web-auth/webauthn-stimulus'
            /home/florent/PhpstormProjects/skeleton-web/vendor/symfony/ux-turbo/src/DependencyInjection/../../assets/dist: '@symfony/ux-turbo'
            /home/florent/PhpstormProjects/skeleton-web/vendor/symfony/ux-live-component/src/DependencyInjection/../../assets/dist: '@symfony/ux-live-component'
            assets/: ''
    ...
```

`StimulusBundle` is present in the `bundles.php` file, but it looks like the extension does not prepend the framework config.

### How to reproduce

I just installed a brand new SF 6.3 full web application and called `composer require symfony/asset-mapper symfony/asset symfony/twig-pack`

### Possible Solution

If I manually change the framework configuration file, the issue is fixed :

```php
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->extension('framework', [
        'asset_mapper' => [
            'paths' => [
                'assets/',
                __DIR__.'/../../vendor/symfony/stimulus-bundle/assets/dist' => '@symfony/stimulus-bundle',
            ],
        ],
    ]);
};
```

**Comment by Spomky** [comment]
Ping @weaverryan

**Comment by weaverryan** [comment]
Hey @Spomky!

> StimulusBundle is present in the bundles.php file, but it looks like the extension does not prepend the framework config.

Agreed. THAT is strange... especially since some other ux packages ARE prepending their paths correctly.

So let's compare LiveComponentBundle (working) with StimulusBundle. Both prepend in the same way... with the same logic: 

* https://github.com/symfony/ux/blob/2.x/src/StimulusBundle/src/DependencyInjection/StimulusExtension.php#L48
* https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php#L58

Are you able to put some debugging logic into that `StimulusExtension` class to see if the correct code is getting hit?

**Comment by weaverryan** [comment]
Ping @Spomky are you still getting this? Or did it just "go away"?

**Comment by Spomky** [comment]
Hi,

Excuse me for the lack of feedback. I will be back home in a few days and try to debug and find where the issue comes from.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
