### ISSUE TITLE
[HttpFoundation] getPayload throws JsonException if request body is empty (again)

### ISSUE THREAD

**Issue by fmarchalemisys** [symfony/symfony#50647]
### Symfony version(s) affected

6.3.0

### Description

Calling `$request->request->get("param")` returns `null` if the body is empty

Replacing it with `$request->getPayload()->get("param")` throws a `JsonException` under the same condition.

This is a big BC just for a name change.

The issue was reported in https://github.com/symfony/symfony/issues/50490 but it got no answer except documenting that `getPayload()` throws a `JsonException`.

### How to reproduce

To reproduce, simply call `$request->getPayload()->get("param")` or `$request->getPayload()->all()` or even `$request->getPayload()->has("param")` to check if a parameter was passed in the body when none was in fact passed.

### Possible Solution

Unless we are supposed to keep using `$request->request` and only infrequently use `$request->getPayload()` for cases where we need to know the client failed to provide a body, I suggest to return an empty array.

```php
    public function toArray(): array
    {
        if ('' === $content = $this->getContent()) {
            return [];
        }
```

An exception should be used for exceptional events. An empty body is nothing but exceptional.

**Comment by ro0NL** [comment]
it's not really _just_ a name change :sweat_smile: 

i agree this looks pesky, though im not sure the client in this case should be updated to send a structured payload as expected (let it be an empty one)

**Comment by ro0NL** [comment]
btw if your content-type is not json, toArray should NOT be called!

if that does happen, then getPayload is bugged :)

**Comment by fmarchalemisys** [comment]
Thank you @ro0NL ,

> btw if your content-type is not json, toArray should NOT be called!

According to the server log, no `content-type` was sent and the request was a GET.

```js
  "request": {
    "remote_ip": "127.0.0.1",
    "remote_port": "52932",
    "proto": "HTTP/3.0",
    "method": "GET",
    "host": "localhost",
    "uri": "/pos/?terminal=TAB001",
    "headers": {
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "Sec-Fetch-Mode": [
        "navigate"
      ],
      "Sec-Fetch-Site": [
        "same-origin"
      ],
      "Sec-Fetch-User": [
        "?1"
      ],
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      ],
      "Accept-Language": [
        "en-US,en;q=0.7,fr;q=0.3"
      ],
      "Alt-Used": [
        "localhost"
      ],
      "Cookie": [],
      "Sec-Fetch-Dest": [
        "document"
      ],
      "Pragma": [
        "no-cache"
      ],
      "Priority": [
        "u=1"
      ],
      "Cache-Control": [
        "no-cache"
      ]
    },
```

And yet, `toArray()` was called by `getPayload()`.

**Comment by ro0NL** [comment]
in HTTP "payload" means the body, so for a GET request an error is expected i'd say

it could be improved by throwing 405 method not allowed in getPayload, for a better errror message

im not really sure what should happen for POST requests without content-type, we could assume form-data, but i tend to believe the client should be updated instead

**Comment by fmarchalemisys** [comment]
An empty `InputBag` is created by `Request` in its constructor. That's the reason why my listener never complained about `$request->request` being called on a GET method :roll_eyes:.  Not good but definitely very convenient :grin: 

@ro0NL  Can you please elaborate as to why you believe it is best to throw an error instead of returning an empty array?

From my point of view, the current code introduces two different behaviors for `getPayload()->get("param")` when `param` is missing depending on whether there are other parameters in the body or not. One just returns null when the other throws an exception. I fail to see the benefit for the developer.

**Comment by ro0NL** [comment]
> Can you please elaborate as to why you believe it is best to throw an error instead of returning an empty array

to spot issues like "$request->request being called on a GET method" :sweat_smile:

**Comment by ruudk** [comment]
I noticed the same today! I was using `Request::getPayload()` and received a DELETE request. That caused it to throw `Request body is empty.`.

To me, that doesn't make sense. Why wouldn't it return an empty `InputBag`?

Also, why would calling `Request::toArray()` throw when the `Request::getContent()` is empty? Wouldn't it make more sense to return an empty array in that case?

**Comment by ro0NL** [comment]
right, ive changed my mind i think :)

a body is not bound to a method nor a content-type, let's relax and return empty array :+1:
