### ISSUE TITLE
var_dumper exception

### ISSUE THREAD

**Issue by remco-pc** [symfony/symfony#50648]
### Symfony version(s) affected

6.3

### Description

ErrorException

iconv(): Detected an illegal character in input string
file: /Application/vendor/symfony/var-dumper/Dumper/AbstractDumper.php
line: 192

this happens when i want to dd() a gz compressed string:

```php

$url = $dir_name . $file_name . '.' . $page . $object->config('extension.json') . $object->config('extension.gz');
$data = Core::object($data->data(), Core::OBJECT_JSON);
$gz = gzencode($data, 9);
d(strlen($gz)); //same as dump => int 767
ddd($gz); //exception thrown



### How to reproduce

try to gzencode a custom json and probably it will throw this error

### Possible Solution

str_replace those illegal chars with a space or a * or [illegal-char]

### Additional Context

_No response_

**Comment by MatTheCat** [comment]
The dumper silences `iconv`’s notices so I guess you’re converting them to exceptions somehow?

**Comment by remco-pc** [comment]
i have not changed anything in the dumper, i have an exceptions_handler which is different then the one from symfony (the var dumper becomes available after installing doctrine). i have 2 functions, d & dd (dump & dd) and ddd (which is a wrapper to dd which allows line nr reporting of the dump) i think there needs to be a try catch block start at line 191 till 200. the @ sign is as follows:

from php documentation:

https://www.php.net/manual/en/language.operators.errorcontrol.php

PHP supports one error control operator: the at sign (@). When prepended to an expression in PHP, any diagnostic error that might be generated by that expression will be suppressed.

If a custom error handler function is set with [set_error_handler()](https://www.php.net/manual/en/function.set-error-handler.php), it will still be called even though the diagnostic has been suppressed.

so we need a try_catch around it i guess

**Comment by remco-pc** [comment]
little example of how i did it with mkdir and added the url so its clear where the error is:

```php
try {
                $mkdir = false;
                if(!File::exist($url)){
                    if(empty($chmod)){
                        $mkdir = @mkdir($url, Dir::CHMOD, true);
                    } else {
                        $mkdir = @mkdir($url, $chmod, true);
                    }
                }
                return $mkdir;
            }
            catch (Exception $exception){
                throw new DirectoryCreateException('Cannot create directory: ' . $url, 0, $exception);
            }
```

results in:

  | ErrorException: mkdir(): Permission denied in /Application/vendor/r3m/framework/src/Module/Dir.php:63
-- | --
  | Stack trace:
  | #0 [internal function]: exceptions_error_handler()
  | #1 /Application/vendor/r3m/framework/src/Module/Dir.php(63): mkdir()
  | #2 /Application/vendor/r3m/framework/src/Module/Route.php(1190): R3m\Io\Module\Dir::create()
  | #3 /Application/vendor/r3m/framework/src/Module/Route.php(1070): R3m\Io\Module\Route::cache_write()
  | #4 /Application/vendor/r3m/framework/src/App.php(157): R3m\Io\Module\Route::configure()
  | #5 /Application/Public/index.php(32): R3m\Io\App::run()
  | #6 {main}
  |  
  | Next R3m\Io\Exception\DirectoryCreateException: Cannot create directory: /tmp/r3m/io/33/Route in /Application/vendor/r3m/framework/src/Module/Dir.php:69
  | Stack trace:
  | #0 /Application/vendor/r3m/framework/src/Module/Route.php(1190): R3m\Io\Module\Dir::create()
  | #1 /Application/vendor/r3m/framework/src/Module/Route.php(1070): R3m\Io\Module\Route::cache_write()
  | #2 /Application/vendor/r3m/framework/src/App.php(157): R3m\Io\Module\Route::configure()
  | #3 /Application/Public/index.php(32): R3m\Io\App::run()
  | #4 {main}

**Comment by MatTheCat** [comment]
Okay so this is not a Symfony issue: you should fix your error handler so that it does not throw exceptions for errors (well, notices at least) whose diagnostic has been suppressed. As the page you linked says, you can use `error_reporting` for that.

**Comment by xabbuh** [comment]
closing as explained by @MatTheCat

**Comment by remco-pc** [comment]
why wouldn't i fix notices and be more stricter then symfony when it comes to ecxceptions, why should i make an exception for symfony var_dumper. By the way your var_dumper gets installed through doctrine overruling my dump function dd() i am glad you didn't used d because that is my dump function. I am not complaining but it would be nice to add as it is much simpeler to add it over there. and why should iconv be used anyway here is the fix and if i look there it cannot handle gz strings because of its wrong charset:

```php
 /**
     * Converts a non-UTF-8 string to UTF-8.
     */
    protected function utf8Encode(?string $s): ?string
    {
        try {
            if (null === $s || preg_match('//u', $s)) {
                return $s;
            }

            if (!\function_exists('iconv')) {
                throw new \RuntimeException('Unable to convert a non-UTF-8 string to UTF-8: required function iconv() does not exist. You should install ext-iconv or symfony/polyfill-iconv.');
            }

            if (false !== $c = @iconv($this->charset, 'UTF-8', $s)) {
                return $c;
            }
            if ('CP1252' !== $this->charset && false !== $c = @iconv('CP1252', 'UTF-8', $s)) {
                return $c;
            }

            return @iconv('CP850', 'UTF-8', $s);
        }
        catch (\Exception $e) {
            return '[exception: ' . $e->getMessage() . ']';
        }
    }
```

also note the @ difference on line 200... which get executed in my case, so its a bug

I am doing now 
```php
d($gzstring);
dd('die');
```

and that works for me... but if others would use my framework too it would be odd to explain why you won't at least add the @ sign at line 200 to get a suppression there or do you want it to throw an exception there ?
