### ISSUE TITLE
Message parameter not exists in PasswordStrength constraint attribute

### ISSUE THREAD

**Issue by 4d4ch4u32** [symfony/symfony#50651]
### Symfony version(s) affected

6.3.0

### Description

I just upgraded to Symfony 6.3 to use the new `PasswordStrength` constraint. In the docs I can see how to change the message that is issued when the password does not reach the minimum required score. But the parameter message is not existent for the attribute.

Link to documentation: https://symfony.com/doc/current/reference/constraints/PasswordStrength.html#message

### How to reproduce

Using the attribute as documented, e.g.

```php

use Symfony\Component\Validator\Constraints\PasswordStrength;

...

    #[PasswordStrength(
        minScore: PasswordStrength::STRENGTH_STRONG,
        message: 'A message for the user if the password is not strong enough.'
    )]
    private string $plainPassword;
```

### Possible Solution

Adding the parameter to the attribute.

### Additional Context

Just another point: the documentation about the requirements of each score (1-4) is a bit unclear in the current version of the documentation.

**Comment by alexandre-daubois** [comment]
~Adding a new parameter is qualified as a new feature and not a bug~. The PR is ready 🙂 

For the point about the documentation, I suggest directly creating an issue in https://github.com/symfony/symfony-docs

**Comment by 4d4ch4u32** [comment]
> Adding a new parameter is qualified as a new feature and not a bug.

The bug is in the documentation, not in the code 🙂 but IMHO it's better to add the parameter in the code instead of removing the part in the docs because it's a useful feature to change the message.

**Comment by ghost** [comment]
> The bug is in the documentation, not in the code

The bug is inside the code. `message` parameter must exists when a constraint is an attribute.
