### ISSUE TITLE
user impersonate Error: Exceeded maxRedirects

### ISSUE THREAD

**Issue by SakhriHoussem** [symfony/symfony#50657]
### Symfony version(s) affected

6.3.0

### Description

after upgrade from 6.2.11 (work fine on this version)
when i try to Impersonate a user but i get a 302 response

`Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://...
`
### How to reproduce

impersonate to a user following the [doc](https://symfony.com/doc/current/security/impersonating_user.html) 

### Possible Solution

set on security.yaml 
```yaml
            stateless: true
```

### Additional Context

but jwt login not work 

` Session was used while the request was declared stateless.`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
User impersonation is a stateful mechanism. It cannot be used in a stateless firewall where the authentication info is provided in each request (see the caution block at the beginning of the documentation page you linked)

**Comment by stof** [comment]
the difference with `$_POST` is that the form-url-encoded representation of an empty array of parameters *is* the empty string. so decoding an empty body for form-url-encoded makes sense

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
