### ISSUE TITLE
php-http/message-factory

### ISSUE THREAD

**Issue by vikingsurfeur** [symfony/symfony#50666]
### Description

Hi there!

I hope everyone is well!
I just wanted to know if you plan to implement psr17/http-factory instead of php-http/message-factory soon.

Thanks for your work.

**Comment by nicolas-grekas** [comment]
we already do, don't we? See v6.3

**Comment by vikingsurfeur** [comment]
> we already do, don't we? See v6.3

Hi Nicolas,

Ok I understand...
We already use the LTS version (5.4).

Thanks for your answer!
