### ISSUE TITLE
Scheduler doesn't store state

### ISSUE THREAD

**Issue by averatec1337** [symfony/symfony#50669]
### Symfony version(s) affected

6.3.0

### Description

I don't know if it's a bug or feature.
However if I'll put --time-limit in consumer command or I restart consumer during deployment it re-handles messages that shouldn't be re-handled (defined time has not yet passed) 

### How to reproduce

```
<?php

namespace App\Scheduler;

class TestMessage
{

}
```

```
<?php

namespace App\Scheduler;

use Psr\Log\LoggerInterface;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class TestHandler
{
    public function __construct(private LoggerInterface $logger)
    {
    }

    public function __invoke(TestMessage $message)
    {
        $this->logger->error('Handling message', ['time' => time()]);
    }
}
```

```
<?php

namespace App\Scheduler;

use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Scheduler\Attribute\AsSchedule;
use Symfony\Component\Scheduler\RecurringMessage;
use Symfony\Component\Scheduler\Schedule;
use Symfony\Component\Scheduler\ScheduleProviderInterface;
use Symfony\Contracts\Cache\CacheInterface;

#[AsSchedule('test')]
class ScheduleProvider implements ScheduleProviderInterface
{
    public function __construct(
        private LockFactory $lockFactory,
        private CacheInterface $cache,
    ) {

    }

    public function getSchedule(): Schedule
    {
        $schedule = new Schedule();
        $schedule->lock($this->lockFactory->createLock('scheduler'));
        $schedule->stateful($this->cache);
        return $schedule->add(
            RecurringMessage::every('30 seconds', new TestMessage()),
        );
    }
}
```
NOTE: in my local env lock and cache utilize redis

1. Run `bin/console messenger:consume scheduler_test --time-limit=10 -v`
2. Run it again

Output 1st run
```
14:01:59 ERROR     [app] Handling message ["time" => 1686830519]
```

Output 2nd run
```
14:02:11 ERROR     [app] Handling message ["time" => 1686830531]
```

Only 12 seconds of difference, and message is registered as "every 30 seconds"

### Additional Context

![obraz](https://github.com/symfony/symfony/assets/2456974/67797078-427e-4fc9-896b-77f9e461d48e)

**Comment by stof** [comment]
what is the configuration of your cache ? Do you have a persistent cache like Redis ? Or is it using an ArrayCache that only caches in memory (and so will start the new process with an empty cache) ?

**Comment by averatec1337** [comment]
As I mentioned in the issue, it's redis

```
$ bin/console debug:config framework cache

Current configuration for "framework.cache"
===========================================

app: cache.adapter.redis
default_redis_provider: '%env(REDIS_DSN)%'
pools:
    doctrine.result_cache_pool:
        adapters:
            - cache.app
        tags: null
        public: false
    doctrine.system_cache_pool:
        adapters:
            - cache.system
        tags: null
        public: false
    doctrine.second_level_cache_pool:
        adapters:
            - cache.app
        tags: null
        public: false
prefix_seed: _/var/www/application.App_KernelDevDebugContainer
system: cache.adapter.system
directory: /var/www/application/var/cache/dev/pools/app
default_memcached_provider: 'memcached://localhost'
default_doctrine_dbal_provider: database_connection
default_pdo_provider: null

```

**Comment by averatec1337** [comment]
![obraz](https://github.com/symfony/symfony/assets/2456974/6be113ac-3ff1-40fe-ac05-b603472aad93)

**Comment by StanJansen** [comment]
I'm having the same issue. Are there any solutions/workarounds for this?

**Comment by StanJansen** [comment]
Looked at the code; if you do not pass the `from` argument, it sets it at the current timestamp. If that one is bigger than the last run, it uses that instead. So when you pass a `from` in the past to the `RecurringMessage::every` method, it will work with caching.

Not sure if this is intended or not, but it is a (temporary) workaround...
