### ISSUE TITLE
Version v5.4.24 of symfony/property-info broke ArrayDenormalizer

### ISSUE THREAD

**Issue by Moghul** [symfony/symfony#50675]
### Symfony version(s) affected

v5.4.24

### Description

I have an array with numeric keys to denormalize, and the property the data will be assigned to is a [Doctrine ArrayCollection](https://github.com/doctrine/collections/blob/2.1.x/src/ArrayCollection.php). Previous to this release denormalization worked fine, but now this denormalization exception is collected:

```
Symfony\Component\Serializer\Exception\NotNormalizableValueException object
 currentType => string "int" (3)
 expectedTypes => array(1)
   integer 0 => string "string" (6)
 path => string "[0].answerOptions[0]" (20)
 useMessageForUser => true
 message => string "The type of the key "0" must be "string" ("int" given)." (55)
 code => integer 0
 file => string "path/to/symfony/serializer/Exception/NotNormalizableValueException.php" (98)
 line => integer 31
```

The exception is thrown in the ArrayDenormalizer class in line 58.

### How to reproduce

I can see that the [ArrayDenormalizerTest](https://github.com/symfony/symfony/blob/v5.4.24/src/Symfony/Component/Serializer/Tests/Normalizer/ArrayDenormalizerTest.php) class doesn't test arrays with numeric keys or no specified keys at all, so that might be the place to start.

The PhpDocExtractor does seem to extract both int and string correctly from the property but because they are passed individually to the ArrayDenormalizer, it fails when $context['key_type'] is 'string'.

### Possible Solution

The right solution is probably to update the type check in the ArrayDenormalizer class to check all possible types rather than just the key_type value.

**Comment by derrabus** [comment]
Can you turn the possible solution into a PR?

**Comment by Moghul** [comment]
Unfortunately no. The reason I said "probably" is that I have a hard time following the code. It genuinely took me a couple of hours to learn the information I've gathered and I don't understand the reasons behind most of the things that happen in the object and array (de)normalizers...

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Moghul** [comment]
Sorry for the late reply, I've had a busy week. I'm not sure when I'll get around to it but I do intend to make an example.

**Comment by Moghul** [comment]
Hi, I just forked the repo, added doctrine and wrote a test. I hope that's good enough https://github.com/Moghul/symfony-5.4.24-bug-reproduction/commit/d83acae304b2ea76bcf693090aa93361c00ccf68

Should be enough to just clone the branch, composer install, and run phpunit. I tried to reproduce it without doctrine's ArrayCollection but I couldn't get whatever the exact mix of code is causing this.

The test should fail like this:

```
1) Symfony\Component\Serializer\Tests\Normalizer\ArrayDenormalizerCollectionTest::testDoctrineCollection
Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the key "0" must be "string" ("int" given).

/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Exception/NotNormalizableValueException.php:31
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php:58
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Serializer.php:238
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:567
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:635
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php:384
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:281
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:363
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Serializer.php:238
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Serializer.php:151
/home/silviu/Documents/symfony-5.4.24-bug-reproduction/src/Symfony/Component/Serializer/Tests/Normalizer/ArrayDenormalizerCollectionTest.php:40
```
