### ISSUE TITLE
Allow specified bundles to override security.firewalls

### ISSUE THREAD

**Issue by JFO-SNPS** [symfony/symfony#50681]
### Description

Hi,

I'am coding a bundle/recipe for my firm and I need to add a default firewall configuration for the future projects.
But when I try to add a firewall configuration to my recipe I got an error saying that security.firewalls can't be defined in multiple files.

I understand that it is a security measure to avoid bundles to create security breaches in apps.

But I really need it. So, I think a solution would be creating a parameter in security.yaml or framework.yaml that would allow explicitly some named bundles to add security.firewalls rules in their files, or to add a mechanism to allow them to add rules directly in security.yaml.

Thx in advance, sorry for making your eyes bleeding, reading my poor English :p

**Comment by nicolas-grekas** [comment]
I think this can be solved by writing a recipe that leverages the new "add-lines" configurator https://github.com/symfony/flex/pull/975
