### ISSUE TITLE
[HttpKernel] #[MapQueryString] with an empty query string always returns null

### ISSUE THREAD

**Issue by DrLuke** [symfony/symfony#50690]
### Symfony version(s) affected

6.3.0

### Description

`RequestPayloadValueResolver` always [returns null](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L152-L154) when mapping query strings and query string is empty.

This is problematic when using a DTO where all arguments have default values, e.g.

```php
class MyDto {
    public function __construct(public string $foo = "bar")
    {}
}
```

### How to reproduce

Controller:

```php
class MyDto {
    public function __construct(public string $foo = "bar")
    {}
}

class FooController extends AbstractController
{
    #[Route("/foo", name: "foo", methods: ["GET"])]
    public function getPaginated(
        #[MapQueryString] MyDto $myDto,
    ): JsonResponse
    {
        return $this->json($myDto);
    }
}
```

`GET /foo` -> `404 HttpException`
`GET /foo?foo=baz` -> `200 {"foo": "baz"}`

### Possible Solution

Remove [this](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L152-L154) early return and let the serializer decide what to do with an empty query string.

**Comment by DrLuke** [comment]
Workaround for the time being:

```php
class MyDto {
    public function __construct(public string $foo = "bar")
    {}
}

class FooController extends AbstractController
{
    #[Route("/foo", name: "foo", methods: ["GET"])]
    public function getPaginated(
        #[MapQueryString] ?MyDto $myDto,
    ): JsonResponse
    {
        return $this->json($myDto ?? new MyDto());
    }
}
```

**Comment by mdeboer** [comment]
I don't think removing the early return is the right way to do it imho.

What if the argument is nullable and you want it to be null when no query parameters are present?

So instead of removing it, it should add a condition that checks if the parameter is nullable. If it is, it should return null. If it isn't it should just let the serialiser handle it.

**Comment by DrLuke** [comment]
@mdeboer I would let the serializer handle it first. If it can not deserialize, return `null` if nullable.

**Comment by mdeboer** [comment]
Oh no. You would never be able to handle other errors like you can now.

I don't see what good that would do. Can you elaborate?

**Comment by DrLuke** [comment]
@mdeboer If the serializer can turn an empty query into the requested object, it should get the chance to do that. With an early return you assume that an empty query should always result in a null, even though the serializer could produce valid output.

**Comment by mdeboer** [comment]
I don't think you understand what I meant, what I meant was this:

Current code:
```php
private function mapQueryString(Request $request, string $type, MapQueryString $attribute): ?object
{
    if (!$data = $request->query->all()) {
        return null;
    }

    return $this->serializer->denormalize($data, $type, null, self::CONTEXT_DENORMALIZE + $attribute->serializationContext);
}
```


My proposal:
```php
private function mapQueryString(Request $request, string $type, MapQueryString $attribute): ?object
{
    if (!$data = $request->query->all() && $attribute->metadata->isNullable()) { // THIS LINE
        return null;
    }

    return $this->serializer->denormalize($data, $type, null, self::CONTEXT_DENORMALIZE + $attribute->serializationContext);
}
```

This makes sure it only returns null when the argument is indeed nullable. In your case this means you should not set it as nullable and it will simply use the serializer to convert it into an empty object, as with your object that is possible.

Say that regardless of whether an object can be created without arguments, you want to know whether any query parameters are given. You simply make your argument nullable and it will be null when no query parameters are given.

Now in case you don't have an object that can be created without arguments, it will throw an exception by the serializer, allowing you to debug it or do whatever with it.

**Comment by DrLuke** [comment]
I understood what you mean, I am just of the opinion that the serializer should have the say what happens here. Otherwise you assume that nullable + empty query means you always want to get null. But that might now always be the case.

> Say that regardless of whether an object can be created without arguments, you want to know whether any query parameters are given. You simply make your argument nullable and it will be null when no query parameters are given.

Then you should model your DTO to not be creatable from an empty array, or configure the serializer accordingly to not accept this input. By returning null however the choice on how to handle this is taken away.

**Comment by nicolas-grekas** [comment]
I wouldn't let the serializer define the behavior to have when empty query-string or payload happens. This would be unexpected and too implicit.

Instead, I'd suggest to fallback to the default value of the argument (which can be an empty array, object or whatever).

Here is what I have in mind. Anyone to turn that into a PR with a test case?

```diff
--- a/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
+++ b/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
@@ -134,8 +134,12 @@ class RequestPayloadValueResolver implements ValueResolverInterface, EventSubscr
                 }
             }
 
-            if (null === $payload && !$argument->metadata->isNullable()) {
-                throw new HttpException($validationFailedCode);
+            if (null === $payload) {
+                $payload = match (true) {
+                    $argument->metadata->hasDefaultValue() => $argument->metadata->getDefaultValue(),
+                    $argument->metadata->isNullable() => null,
+                    default => throw new HttpException($validationFailedCode),
+                };
             }
 ```

**Comment by DrLuke** [comment]
> I wouldn't let the serializer define the behavior to have when empty query-string or payload happens. This would be unexpected and too implicit.

Why is that unexpected and too implicit? It would align with how the serializer works everywhere else. As per the [serializer component documentation](https://symfony.com/doc/current/components/serializer.html#skipping-uninitialized-properties), all you need to deserialize is:
>    * The information to be decoded
>    * The name of the class this information will be decoded to
>    * The encoder used to convert that information into an array

So the criteria would be fully met here when you have an empty array + a class with all default values, especially when adding [skipping of undefined properties](https://symfony.com/doc/current/components/serializer.html#skipping-uninitialized-properties) to the [default deserialization context](https://github.com/symfony/symfony/blob/d9eccd1f8b143bbdc9224a9a470763f0e05298bd/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L46).

And in my opinion, that is more explicit than having to remember the special case of having to add a default value to the controller arguments for when the query is empty.

**Comment by ro0NL** [comment]
> The information to be decoded

but no information was given :thinking: 

for non-nullable maybe opt-in to deserializing defaults via the attribute

>nullable + empty query means you always want to get null. But that might now always be the case.

IMHO it's 100% the case

**Comment by DrLuke** [comment]
> but no information was given 🤔

Not quite, an empty array is the information that no query parameters were given. No information would be `null`.

**Comment by ro0NL** [comment]
how woud an empty array in the query look like?

**Comment by nicolas-grekas** [comment]
The fact that there's a serializer behind the scene is an implementation detail. What matters is that this is a regular controller. Default values on controller arguments are used for that.

**Comment by ro0NL** [comment]
agree, i forgot `action(Dto $dto = new Dto())` is possible

**Comment by mdeboer** [comment]
> I wouldn't let the serializer define the behavior to have when empty query-string or payload happens. This would be unexpected and too implicit.
> 
> 
> 
> Instead, I'd suggest to fallback to the default value of the argument (which can be an empty array or whatever).
> 
> 
> 
> Here is what I have in mind. Anyone to turn that into a PR with a test case?
> 
> 
> 
> ```diff
> 
> --- a/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
> 
> +++ b/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
> 
> @@ -134,8 +134,12 @@ class RequestPayloadValueResolver implements ValueResolverInterface, EventSubscr
> 
>                  }
> 
>              }
> 
>  
> 
> -            if (null === $payload && !$argument->metadata->isNullable()) {
> 
> -                throw new HttpException($validationFailedCode);
> 
> +            if (null === $payload) {
> 
> +                $payload = match (true) {
> 
> +                    $argument->metadata->hasDefaultValue() => $argument->metadata->getDefaultValue(),
> 
> +                    $argument->metadata->isNullable() => null,
> 
> +                    default => throw new HttpException($validationFailedCode),
> 
> +                };
> 
>              }
> 
>  ```

I'd be happy to 👍🏻

> agree, i forgot `action(Dto $dto = new Dto())` is possible

It isn't though (if that is a method declaration you are referring to, e.g. a controller method). Default values can only be constants.

**Comment by ro0NL** [comment]
> Default values can only be constants.

future is now https://3v4l.org/TNWXC

but now im wondering how `?Dto $dto = new Dto()` should behave, does the user want null or defaults for an empty payload?perhaps it should be a compile error in this case :sweat_smile:

**Comment by nicolas-grekas** [comment]
> I'd be happy to 👍🏻

please go ahead :pray: 

> how ?Dto $dto = new Dto() should behave

DefaultValueResolver has the answer: it should take the default value.

**Comment by ro0NL** [comment]
sure, but it implies null can be given somehow, which never happens

**Comment by mdeboer** [comment]
I'll make a PR after work 👍🏻

**Comment by mdeboer** [comment]
There we go, took your implementation @nicolas-grekas and added some tests that should cover everything I think.

**Comment by blaugueux** [comment]
Hi and thanks for all your work here @mdeboer.
After experiencing the same issue it seams that the PR merge in 6.3.1 does not solve this issue for me. I've started a fresh new project and I always get a 404 when not query string is provided. I don't know what to provide to help solving this but I'll be glad to help!

**Comment by mdeboer** [comment]
> Hi and thanks for all your work here @mdeboer.
> 
> After experiencing the same issue it seams that the PR merge in 6.3.1 does not solve this issue for me. I've started a fresh new project and I always get a 404 when not query string is provided. I don't know what to provide to help solving this but I'll be glad to help!

Can you share a really simple controller where this happens (or link to repo with the problem isolated as much as possible)? I'd be happy to take a look!

**Comment by dddenisov** [comment]
#I have the same problem as @blaugueux [here](https://github.com/symfony/symfony/issues/50690#issuecomment-1634047130). 
Why is this happening? - Because if you have a request class with only optional parameters, then anyway you will get here **null** when call endpoint without parameters. 
```php
if (null === $payload) {
    $payload = match (true) {
        $argument->metadata->hasDefaultValue() => $argument->metadata->getDefaultValue(),
        $argument->metadata->isNullable() => null,
        default => throw new HttpException($validationFailedCode),
    };
}
```
A code example
```php
class ListRequest
{
    public function  #__construct(
        #[Assert\NotBlank]
        #[Assert\GreaterThanOrEqual(1)]
        public readonly int $page = 1,
        #[Assert\NotBlank]
        #[Assert\GreaterThanOrEqual(1)]
        public readonly int $pageSize = 15,
    ) {}
}

class CustomerController extends AbstractController
{
    #[Route('/list', name: 'list')]
    public function index(
        #[MapQueryString] ListRequest $listRequest,
    ): Response {
        ...
    }
}
```

I think the solution would be to try to initialise the request object if the payload is null. And if we can do it, then our object has a default value. For example like this 
```php
try {
    $payload = match (true) {
        $argument->metadata->hasDefaultValue() => $argument->metadata->getDefaultValue(),
        !$argument->metadata->hasDefaultValue() => new ($argument->metadata->getType())(),
        $argument->metadata->isNullable() => null,
        default => throw new HttpException($validationFailedCode),
     };
 } catch (\Throwable) {
    throw new HttpException($validationFailedCode);
}
```

**Comment by blaugueux** [comment]
@dddenisov I was feeling alone with this! Thanks for joining me.
I've tested your fix but the values are not updated when provided in the query string.

**Comment by dddenisov** [comment]
@blaugueux This is weird... My code is updating the values with this fix. Could you show your request class?

**Comment by blaugueux** [comment]
Something basic IMO.

```php
class OrganizationsController extends AbstractController
{
    #[Route('/organizations', methods:['GET'])]
    public function listOrganizations(
        OrganizationRepository $repository,
        #[MapQueryString] PaginationDTO $query
    ) {
        ...
    }
}

class PaginationDto
{
    public function __construct(
        #[Assert\Choice([5, 10, 15, 20, 25])]
        public readonly int $limit = 20,

        #[Assert\Positive]
        public readonly int $page = 1,
    ) {}
}
```

**Comment by dddenisov** [comment]
I tested it with your code and it works. Maybe you changed the code in the wrong place?
I changed this block https://github.com/symfony/http-kernel/blob/6.3/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L138

**Comment by blaugueux** [comment]
@dddenisov it's working fine with line 137 not deleted, my mistake :( Do you plan to propose a PR with this fix?

**Comment by dddenisov** [comment]
@blaugueux Yes, I will try =)

**Comment by nicolas-grekas** [comment]
Why don't you use the default value?
`#[MapQueryString] PaginationDTO $query = new PaginationDTO`

**Comment by dddenisov** [comment]
Because in this way we always must control the situation - Does our request class have only optional properties or not?
And when we add a new property without a default value, we won't be able to define that class as the default value in the controller.

**Comment by nicolas-grekas** [comment]
I'm sorry I don't understand the issue. Can you be more explicit please? What's the issue with relying on the default value?

**Comment by dddenisov** [comment]
@nicolas-grekas Of course.
We have class PaginationDTO with 2 properties **page** and **limit**. And we wanna use it as request object with validation constraints in Controller. Let's look at a few situations:

1.  _Properties page and limit don't have default values_
 -> the argument declaration in the controller looks like `#[MapQueryString] PaginationDTO $query` and we can't set default value for PaginationDTO because properties need values in constructor.
2. _Property page has default value and limit doesn't have default value_
 -> the argument declaration in the controller looks like `#[MapQueryString] PaginationDTO $query` and we can't set default value for PaginationDTO because property limit needs value in constructor.
3.  _Properties page and limit have default values_
-> the argument declaration in the controller looks like `#[MapQueryString] PaginationDTO $query = new PaginationDTO()` 

If we used PaginationDTO in many controllers, then in situation 3 we should set the default value everywhere. And if in the future we add a new property into PaginationDTO without default value, then we will have to remove the default value for PaginationDTO in all these controllers.

**Comment by nicolas-grekas** [comment]
I still don't understand sorry:

> Properties page and limit don't have default values
-> the argument declaration in the controller looks like #[MapQueryString] PaginationDTO $query and we can't set default value for PaginationDTO because properties need values in constructor.

use `#[MapQueryString] PaginationDTO $query = new PaginationDTO(page: 1, limit: 10)`

> Property page has default value and limit doesn't have default value
-> the argument declaration in the controller looks like #[MapQueryString] PaginationDTO $query and we can't set default value for PaginationDTO because property limit needs value in constructor.

use `#[MapQueryString] PaginationDTO $query = new PaginationDTO(limit: 10)`

> PaginationDTO in many controllers, then in situation 3 we should set the default value everywhere

Yes. That's the only issue that I understand from your description: the repetition. I'm not sure it deserves changing the way controllers work. Auto-creating a DTO as you describe would also make it more complex to express that providing a query string is mandatory.

**Comment by Skkay** [comment]
I think the confusion is due to `MapRequestPayload`.

As everyone has already said in this thread, with `MapQueryString` and the following:

```php
class TestDTO
{
    public function __construct(
        public readonly string $sort = 'DESC',
        public readonly int $limit = 10,
    ) {}
}

class TestController extends AbstractController
{
    #[Route('/get', methods:['GET'])]
    public function get(#[MapQueryString] TestDTO $dto): JsonResponse
    {
        return $this->json([ 'dto' => $dto ]);
    }
}
```

The request on `GET /get` will result in a `404 HttpException` error.

**But**, in case of a POST request with `MapRequestPayload` and the following:
```php
class TestDTO
{
    public function __construct(
        public readonly string $sort = 'DESC',
        public readonly int $limit = 10,
    ) {}
}

class TestController extends AbstractController
{
    #[Route('/post', methods: ['POST'])]
    public function post(#[MapRequestPayload] TestDTO $dto): JsonResponse
    {
        return $this->json([ 'dto' => $dto ]);
    }
}
```

The request on `POST /post` with an empty JSON object will correctly respond:
```sh
curl -X POST -H "Content-Type: application/json" -d '{}' http://localhost:8000/post

# => {"dto":{"sort":"DESC","limit":0}}
```

This different behavior between `MapQueryString` and `MapRequestPayload` is pretty confusing.

**Comment by TaPTaK** [comment]
> I think the confusion is due to `MapRequestPayload`.
> 
> As everyone has already said in this thread, with `MapQueryString` and the following:
> 
> ```
> class TestDTO
> {
>     public function __construct(
>         public readonly string $sort = 'DESC',
>         public readonly int $limit = 10,
>     ) {}
> }
> 
> class TestController extends AbstractController
> {
>     #[Route('/get', methods:['GET'])]
>     public function get(#[MapQueryString] TestDTO $dto): JsonResponse
>     {
>         return $this->json([ 'dto' => $dto ]);
>     }
> }
> ```
> 
> The request on `GET /get` will result in a `404 HttpException` error.
> 
> **But**, in case of a POST request with `MapRequestPayload` and the following:
> 
> ```
> class TestDTO
> {
>     public function __construct(
>         public readonly string $sort = 'DESC',
>         public readonly int $limit = 10,
>     ) {}
> }
> 
> class TestController extends AbstractController
> {
>     #[Route('/post', methods: ['POST'])]
>     public function post(#[MapRequestPayload] TestDTO $dto): JsonResponse
>     {
>         return $this->json([ 'dto' => $dto ]);
>     }
> }
> ```
> 
> The request on `POST /post` with an empty JSON object will correctly respond:
> 
> ```shell
> curl -X POST -H "Content-Type: application/json" -d '{}' http://localhost:8000/post
> 
> # => {"dto":{"sort":"DESC","limit":0}}
> ```
> 
> This different behavior between `MapQueryString` and `MapRequestPayload` is pretty confusing.
I agree, behaviour should be the same...

**Comment by i386-x86** [comment]
> This different behavior between `MapQueryString` and `MapRequestPayload` is pretty confusing.

I agree, behaviour should be the same... But...

**Comment by Gregman-js** [comment]
As the`MapQueryString` function description says: `[...] map the query string of the request to typed object and validate it.`
So I expect that the validator will run, and that I will get the appropriate violations based on asserts in DTO class.
But now asserts and custom validators don't run when there are no GET parameters.
