### ISSUE TITLE
[DependencyInjection] Add default value/nullable env vars

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#50700]
### Description

I think environment variables should be nullable or have a default value, rather than throwing a `EnvNotFoundException`, which cannot be caught in the controller. 

In my use case, I have 100+ clients that share the same source code, and there are cases when only one/two of them have a certain feature that requires some configuration parameters. 

It would be very useful to have something equivalent to `$_ENV['MY_VAR'] ?? false`, to keep the code simple without adding parameters that are useless in 99% of the cases. 

I tried the:
`#[Autowire('%env(MY_VAR)%')]`
But it throws the `EnvNotFoundException`

### Example

```
public function new(#[Autowire('%env(MY_VAR)%')] ?string $myVar): Response
{
    // It should not throw any exception, since $myVar is nullable. 
    // If it was instead typehinted as string, a TypeError should be thrown since I expect a string
}
```

**Comment by michaljusiega** [comment]
What about to use the default syntax?

**#[Autowire('%env(default::MY_VAR)%')**]

See https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors for more information

**Comment by fmonts** [comment]
Thanks @michaljusiega , didn't know about that, sorry
