### ISSUE TITLE
Built-in Maintenance mode

### ISSUE THREAD

**Issue by nbennett25** [symfony/symfony#50719]
### Description

When deploying changes to a server, it would be nice to have a feature to enable a maintenance mode, similar to [this gist](https://gist.github.com/jfcherng/2fa6cccd68ad4cc84a31b974066db293), but perhaps configured via a `secret` rather than an `ENV` variable, so that it could be set via the cli, and built into a deployment script rather than need to modify the `.env.local` directly.

### Example

`bin/console maintenance:enable`

Enables a maintenance page on the front end, code is deployed, db changes are made, etc.

`bin/console maintenance:disable`

Front end is visible

**Comment by nbennett25** [comment]
Just a thumbs down @chapterjason ? is this an unreasonable ask? other frameworks have this feature...

**Comment by ghost** [comment]
I'm neutral to the idea. 

However the maintenance mode should not boot the application under maintenance. In general this is configured at the HTTP server level or load balancer if in use. Another problem is a console command that turns it on/off - it doesn't scale with multiple instances.

**Comment by nbennett25** [comment]
@javaDeveloperKid - I agree about the multiple instances, but at that point your architecture is reasonably complex and I'd presume you'd have some kind of deployment strategy that a cli command like this wouldn't be appropriate for anyway; that said, I do think it could be useful for a single server instance.

**Comment by 94noni** [comment]
Reminds me this https://github.com/symfony/symfony/issues/31921

i am also +0 on this as either better implemented on webserver side before app boot or in your personal code app if needed as there are numerous ways of code to avoid your app to boot

**Comment by wouterj** [comment]
I agree with what was said in #31921 and here. As we need to boot the kernel to render any maintenance mode, this means we still need a big part of the application to be functioning. We can also not be sure other parts of the app already connect to external sources like a DB, reducing the relevancy even more.

We would be better of advocating doing this in your webserver config, or even before that (e.g. in a CloudFlare proxy). Besides that, the code to implement this if you want is very trivial as shown in the gist. There are also some community bundles implementing this feature.

As a result, I'm going to close here. If you have other arguments to add such a feature that bring anything new on top of what was said in https://github.com/symfony/symfony/issues/31921, please add them - we can always reopen here :)

**Comment by nicolas-grekas** [comment]
Wild idea: put this in symfony/runtime? This can save booting the kernel, and that's a new capability!

**Comment by ghost** [comment]
> Wild idea: put this in symfony/runtime? This can save booting the kernel, and that's a new capability!

symfony/runtime with maintenance mode managing? It doesn't fit for me. And still, at least symfony/runtime and symfony/dotenv (if it is the env var that controls that) deps must be working. Twig as well  if fancy maintenance page in use (this requires container boot to get Twig service). Even with static content, how would you return content or at least header with status code? Use plain PHP? What if this is PHP that is under maintenance?  
I still stick with the idea that requests should not reach the point of the application under maintenance.
