### ISSUE TITLE
ChoiceType with CallbackChoiceLoader getting OOM on large choice list

### ISSUE THREAD

**Issue by pagolubev** [symfony/symfony#50756]
### Symfony version(s) affected

5.4.19 up to latest

### Description

Hello!

I am trying to submit ~100 elements in `ChoiceType` with a `multiple` flag set and getting out of memory exception if there is a lot of choices (~150k) and `CallbackChoiceLoader` used.

### How to reproduce

run composer require symfony/form:5.4.19 and after this script:

```
<?php

ini_set('memory_limit', '1024M');

use Symfony\Component\Form\ChoiceList\Loader\CallbackChoiceLoader;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormFactory;
use Symfony\Component\Form\FormRegistry;
use Symfony\Component\Form\ResolvedFormTypeFactory;

require_once __DIR__.'/vendor/autoload.php';

// make an form with CallbackChoiceLoader which loads ~150k choices from database 
$formFactory = new FormFactory(new FormRegistry([], new ResolvedFormTypeFactory()));
$choiceForm = $formFactory->create(
    ChoiceType::class, null, [
        'choice_loader' => new CallbackChoiceLoader(fn() => loadChoices()),
        'multiple' => true,
    ],
);

// will throw "Allowed memory size of 1073741824 bytes exhausted"
$choiceForm->submit(range(0, 50));

// emulate loading 150k values from database in random order
function loadChoices(): array
{
    $result = [];
    $id = random_int(10000, 30000);
    for ($i = 1; $i < 150000; $i++) {
        $result[] = (string)$id;
        $id += random_int(1, 100);
    }
    shuffle($result);
    return $result;
}

```

### Possible Solution

In this iteration
https://github.com/symfony/symfony/blob/6c934e638b9b8cf22faf2cbf0855d8f0a219e385/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L168-L173

for every input item we make choices list flatten:
https://github.com/symfony/symfony/blob/6c934e638b9b8cf22faf2cbf0855d8f0a219e385/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L86-L90

so memory usage is growing.

Probably it's okay to replace iterator above with something like this:
```
foreach ($choiceList->getChoicesForValues($data) as $knownValue) {
    $knownValues[] = $knownValue;
    unset($unknownValues[$knownValue]);
}
```

**Comment by Aliance** [comment]
Btw, in the latest Symfony that was changed: https://github.com/symfony/symfony/blob/v6.3.1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L150-L154

Does the problem still exist in 6.3?

**Comment by Aliance** [comment]
@xabbuh can you see into this issue, please? Or let me know whom to ask for.

**Comment by pagolubev** [comment]
> Does the problem still exist in 6.3?

Yes, this applies to all versions

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
