### ISSUE TITLE
[Scheduler] Not working triggers with OS datetime different from PHP setting

### ISSUE THREAD

**Issue by davidromani** [symfony/symfony#50764]
### Symfony version(s) affected

6.3.0

### Description

I've prepared a scheduled every 2 minutes task with the following code:

```php
<?php

namespace App\Schedule\Provider;

use App\Message\UpdateGoogleAnalyticsVisitsMessage;
use Symfony\Component\Scheduler\Attribute\AsSchedule;
use Symfony\Component\Scheduler\RecurringMessage;
use Symfony\Component\Scheduler\Schedule;
use Symfony\Component\Scheduler\ScheduleProviderInterface;

#[AsSchedule('default')]
class DefaultScheduleProvider implements ScheduleProviderInterface
{
    public function getSchedule(): Schedule
    {
        return (new Schedule())->add(
            RecurringMessage::every(
                '120 seconds',
                new MyUpdateManagerMessage()
            )
        );
    }
}
```

Then I've opened a consumer with Supervisor but it seem that there is some divergenge between OS clock & PHP process clock that never fires the recurring message.

### How to reproduce

With the corresponding `MyUpdateManagerMessage` & `MyUpdateManagerMessageHandler` classes created. If you execute the console debug command:

```bash
# /usr/bin/php8.2 bin/console debug:scheduler --env=prod

Scheduler
=========

default
-------

 ------------------------------------ -------------------------------------- --------------------------- 
  Message                              Trigger                                Next Run                   
 ------------------------------------ -------------------------------------- --------------------------- 
  MyUpdateManagerMessage               PeriodicalTrigger: every 120 seconds   2023-06-24T07:11:34+00:00  
 ------------------------------------ -------------------------------------- --------------------------- 

```

Take a look at the "Next Run" date created. Then I've check my OS date & it seems that is configured 2 hours later (probably due to my timezone).

```bash
# date
Sat Jun 24 09:11:56 CEST 2023
```

If you open a foreground console process every thing works well, and I can see the message fired every 2 minutes as I expected.

```bash
# /usr/bin/php8.2 bin/console messenger:consume scheduler_default -vv
```

But If I decide to open it as a background process managed by Supervisor, the same command is never fired. May be is due to the timezone difference? The "Next Run" date is never achieved because is a 2 hours in past moment.

**Comment by davidromani** [comment]
After a few weeks doing investigations I can conclude that this is not a Symfony component bug.

It has been a combination of two (own) mistakes that confused me. First of all I didn't realized that it's possible to instantiate a schedule taking care about a timezone like this:

```php
        return (new Schedule())->add(
            RecurringMessage::every(
                '1 day',
                new MyUpdateManagerMessage(),
                from: new \DateTimeImmutable('13:47', new \DateTimeZone('Europe/Madrid'))
            )
        );
```

Finally I didn't realized that I was keeping alive this process with a Supervisor's child with a non www-data user (and privileges).

Sorry for my mistakes.

**Comment by xabbuh** [comment]
@davidromani Maybe #51674 still is of help for you.
