### ISSUE TITLE
Regression in validator

### ISSUE THREAD

**Issue by garak** [symfony/symfony#50780]
### Symfony version(s) affected

5.4.25, 6.2.12, 6.3.1

### Description

Upgrading symfony/validator from 5.4.34 to 5.4.35 breaks validation in a project of mine.
Some properties that have a NotBlank constraint applied are not detected as invalid when submitted without a value.
It seems that the regression was introduced in this change https://github.com/symfony/symfony/commit/6a3a4d7fb7b5b5358b46edbdfe89a80814e49a00#diff-50c23a0a9ba92c8fb19fa501720ad061da508e3ccfd98fbcdfff2b7c8c6e6499 but unfortunately I cannot understand how.

### How to reproduce

I'm sorry but it seems not so easy to provide a reproducer. In my project, I use XML validation and the problem appears on a property which is not directly defined in the validated object (it's defined in a parent object)

### Possible Solution

Sorry, no clue about this

### Additional Context

I isolated the problem during an upgrade, by requiring in my composer.json `"symfony/validator": "^5.4,<5.4.25"`. With this requirement, all my tests pass.
If I replace it with the simple `"symfony/validator": "^5.4"`, the tests break

**Comment by rmikalkenas** [comment]
Same with the upgrade of symfony/validator `v6.2.11` =>  `v6.2.12`

@nicolas-grekas looks like it's related with yours changes: https://github.com/symfony/validator/commit/81772c16452f67357c1a7afdbb6cc4f3985ae67b
once I restore Mapping/ClassMetadata.php to previous changes - everything works as expected

**Comment by nicolas-grekas** [comment]
Could anyone come up with a test case to prevent a regression?

**Comment by rmikalkenas** [comment]
@garak do you have a reproducer? I can try to extract from my project, but it will take some time

**Comment by garak** [comment]
Meanwhile I can confirm the same problem with validator 6.3.1 (while 6.3.0 works).
I found a simpler case, which maybe can be used as reproducer.

In the XML validation, I have:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping https://symfony.com/schema/dic/constraint-mapping/constraint-mapping-1.0.xsd"
>
    <class name="Application\Command\User\AbstractCommand">
        <property name="password">
            <constraint name="Length">
                <option name="min">8</option>
                <option name="max">255</option>
            </constraint>
        </property>
    </class
    <class name="Application\Command\User\CreateCommand">
        <property name="password">
            <constraint name="NotBlank"/>
        </property>
    </class>
</constraint-mapping>
```
So, when I validate `CreateCommand`, which extends `AbstractCommand`, the `NotBlank` constraint is not applied (while the original `Length` constraint is)

**Comment by toastedghost** [comment]
We have noticed the same behaviour in our project. 

We use the FOSUserBundle and have extended the user entity.  
Validation rules are defined in a "validation.yml" in our project and the FOSUserBundle itself provides validation rules in a "validation.xml". With version 5.4.25 of symfony/validator, only the rules from our file are taken into account for which there are no "property" definitions in the file from the FOSUserBundle. With version 5.4.24, on the other hand, it works correctly, so that the rules from our definition apply as well as those from the FOSUserBundle.
