### ISSUE TITLE
The option "sanitize_html" does not exist.

### ISSUE THREAD

**Issue by mataslib** [symfony/symfony#50785]
### Symfony version(s) affected

6.3.1

### Description

Form fields shall be able to become sanitized via option "sanitize_html".

Error: 

![image](https://github.com/symfony/symfony/assets/5154014/b6f76d63-87a4-4b91-83d6-2cf1b7411a02)

Breakpoints in Sanitizer Extension not being hit:

![image](https://github.com/symfony/symfony/assets/5154014/239170f0-256c-4ded-b6c8-4a1308420bc4)

`php bin/console debug:form` not listing `TextTypeHtmlSanitizerExtension`:

![image](https://github.com/symfony/symfony/assets/5154014/da53ad27-9818-4bf7-a774-46a80355c5ae)

### How to reproduce

Add this snippet via form builder.
```
$builder->add(
                    'scope', TextType::class, [
                        'label' => 'Rozsah spolupráce (počet hodin/týden)',
                        'required' => true,
                        'sanitize_html' => true,
                    ]
                )
```

**Comment by xabbuh** [comment]
Did you install the HtmlSanitizer component?

**Comment by mataslib** [comment]
@xabbuh Omg, my bad, I did not. Thank you. :+1: (did not even suspect such issue as it's present in vendor :X)
