### ISSUE TITLE
[Validator] `Type` constraint considers `NAN` and `INF` as floats

### ISSUE THREAD

**Issue by aprat84** [symfony/symfony#50782]
### Symfony version(s) affected

6.3

### Description

If a number is outside of `2.2250738585072014E-308` to `1.7976931348623158E+308` range, PHP converts it to `-INF` or `INF`.

Values `INF`, `-INF` and `NAN` are considered `float` in PHP as for the `is_float` function.

The `Type` constraint relies in this function to check for a valid float.

Now, are this valid float numbers? IMHO no.

FTR: this doesn't happen with integers, as PHP converts them to float once they go outside the `PHP_INT_MIN` and `PHP_INT_MAX` range...

### How to reproduce

```php
var_dump(is_float(INF));
var_dump(is_float(NAN));
```

### Possible Solution

Add an extra check for `is_finite`, when dealing with floats?

**Comment by xabbuh** [comment]
@aprat84 Sounds reasonable to me, can you open a PR with your suggestion (against the `5.4` branch)?

**Comment by aprat84** [comment]
Maybe the best solution would be to add a new constraint `Finite` (and its `FiniteValidator`), so we can combine it with `Type` constraint:
```
#[Assert\Type(['int', 'float'])]
#[Assert\Finite]
```

Instead of patching the `Type` constraint adding range validation...

**Comment by guillaume-a** [comment]
Hello, I made an attemps to create `Finite` validator. Hope that helps.

**Comment by magikid** [comment]
Both NaN and Inf are valid floats as defined in IEEE 754. It would be very strange to treat them as invalid values.
