### ISSUE TITLE
[Messenger] WorkerMessageReceivedEvent::setEnvelope was never added

### ISSUE THREAD

**Issue by bosam** [symfony/symfony#50799]
### Symfony version(s) affected

5.2 and above

### Description

Hi,

I've been experiencing with Symfony/Messenger for a bit and I noticed that when subscribing to `WorkerMessageReceivedEvent` the envelope was not mutable due to the fact that the parent class does not support `setEnvelope`.

You can see the changelog here stating that this method [was added here](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Messenger/CHANGELOG.md#520).

```
5.2.0
---
Added WorkerMessageReceivedEvent::setEnvelope() and made event mutable
```

When looking at [the commit responsible](https://github.com/symfony/messenger/commit/6d389f908d9120f5f71563387fda9950c203c710) for introducing this feature, you can see the work done on the worker to get the envelope back after the dispatch and the added `addStamp` method operating on the envelope itself but no code allowing for a redefinition of the aforementioned envelope.

I am betting on a mistake as we are indeed making the envelope mutable with `addStamp` and either the setter was planned and got removed but the changelog message was not changed?

### How to reproduce

Install any version of symfony/Messenger after 5.2

```php
$envelope = new \Symfony\Component\Messenger\Envelope::wrap(new \stdClass());
$event = new \Symfony\Component\Messenger\Event\WorkerMessageReceivedEvent($envelope, 'myReceiver');

$event->setEnvelope(); // This method does not exist
```

### Possible Solution

Implement `setEnvelope` in either `WorkerMessageReceivedEvent` or the parent class.

**Comment by HypeMC** [comment]
According to the PR that added the changelog entry, #36152, the method was intentionally removed / never added. It looks like the changelog entry was left by mistake.

**Comment by bosam** [comment]
Thank you @HypeMC for finding the actual reason for its removal.
Then it is expected behavior to not be able to set another envelope. There are still ways to change the message meaning the worker code would still pull the current envelope with the changed message - just no "easy" way to redefine it.

What would be the course of action here then: Do we update the changelog by removing this entry? Is making the envelope mutable a topic we can revisit?

**Comment by HypeMC** [comment]
I guess you could open a PR to fix the changelog, as for revisiting the subject of making the envelope mutable, you'll have to present your use case and see what the core team says.

**Comment by bosam** [comment]
My use case has workarounds, I don't think this should be reopened in that state. If it was indeed missing because of "reasons", it would be a different story but since it looks to be a discussed decision, there is no point going in that direction again.

As for making a PR only to change the changelog file, if anybody feels like doing it - be my guest 👍 

Closing this thread as it wasn't a bug but intentional.
