### ISSUE TITLE
symfony/security-bundle depends on symfony/validator

### ISSUE THREAD

**Issue by uncaught** [symfony/symfony#50808]
### Symfony version(s) affected

6.3

### Description

The package `symfony/security-bundle` does not require `symfony/validator` in its composer dependencies, but the configuration registers the `UserPasswordValidator`, which depends on `symfony/validator`.

### How to reproduce

Install `symfony/security-bundle` without `symfony/validator` and let the container build.

### Possible Solution

1. Only register `UserPasswordValidator` if `symfony/validator` is installed
2. Add `symfony/validator` to the requirements in the composer.json

**Comment by uncaught** [comment]
I've added https://github.com/symfony/security-bundle/pull/8

Not sure if there is a better way to detect the installed `symfony/validator` than checking for the class existance.

**Comment by uncaught** [comment]
I've opened https://github.com/symfony/symfony/pull/50809

Not sure if there is a better way to check whether `symfony/validator` is installed or not other than the class existance.

I also don't know what the [failed tests](https://github.com/symfony/symfony/actions/runs/5400681420/jobs/9809455730?pr=50809) means :(

**Comment by MatTheCat** [comment]
Are you experiencing a particular issue? Because not requiring `symfony/validator` won’t prevent the container being built.

If yes, please describe it in your report and include a stack trace.

**Comment by mbabker** [comment]
@MatTheCat It looks like that service is missing the usual conditional remove logic that most services have in the bundle extension classes.

@uncaught for your PR, usually services are either conditionally loaded or removed based on checks like [these](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L123-L143), so instead of changing the `Resources/config/security.php` file as your PR, it'd be better to check this in the `DependencyInjection/SecurityExtension.php` file in the same way as those checks I linked before.

**Comment by MatTheCat** [comment]
I can build the container just fine while requiring `symfony/security-bundle` and not `symfony/validator`. Do you really have an issue with this setup or is it just guesswork?

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by uncaught** [comment]
Okay, will try to get a reproducer and I'll also check into the SecurityExtension for a fix! 

I thought this was an obvious bug there because as soon as I uninstalled `symfony/validator`, I got this, which was fixed by the changes in the PR:

![image](https://github.com/symfony/symfony/assets/10322643/e7c27552-0e3f-480a-ad11-fe84988cf9d0)

**Comment by MatTheCat** [comment]
I don’t know what your `FixAbstractPass` is doing but it is the culprit: it is loading the `UserPasswordValidator` and thus triggering the error.

**Comment by uncaught** [comment]
Yes, thanks, my bad. That's definitely the pass that loads the broken class.

Sorry for the inconvenience
