### ISSUE TITLE
Non ASCII characters in response headers

### ISSUE THREAD

**Issue by TCM-dev** [symfony/symfony#50811]
### Symfony version(s) affected

6.3 (previous versions should be affected too)

### Description

When access token authentication fails, a response is sent with a WWW-Authenticate headers which sometimes contains non ASCII characters, which are invalid characters for a header value.

This is especially problematic when hosting our website on Azure appservices because the webserver on Azure side will fail to forward the response and return an empty 500 error response instead of a 401 for example. This is not a bug from Azure however, webservers should not support those characters, some do but not everyone of them.

Those non ASCII characters only appear for certain translations, for example in spanish, the WWW-Authenticate header will have this value 
`Bearer error="invalid_token",error_description="Credenciales no vÃ¡lidas."`
Containing the character `Ã` or `0x00C3`

I believe the error_description should not be translated and only return a translation key, or another way to return the translated value should be used (response body for example).

### How to reproduce

Throw an exception that will trigger this response (it may be required to throw this error inside a token_handler for an access_token firewall)

For example
```throw new BadCredentialsException('Invalid credentials.')```

You should see a WWW-Authenticate header in the given response, on some locale, for example es_ES, the header contains non ASCII characters.

### Possible Solution

Inside the AccessTokenAuthenticator file, the method `onAuthenticationFailure` should not attempt to translate the messageKey.

**Comment by nicolas-grekas** [comment]
Is there a way to encode those strings somehow? Do browsers support that? Can you please investigate these questions?

**Comment by derrabus** [comment]
> Is there a way to encode those strings somehow? Do browsers support that? Can you please investigate these questions

There is [RFC 8187](https://www.rfc-editor.org/rfc/rfc8187.html) which is mentioned by the current HTTP spec [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#section-5.5-4). No idea how well browsers support that for `WWW-Authenticate` though.

**Comment by MatTheCat** [comment]
Should the description really be translated? [RFC 6750](https://datatracker.ietf.org/doc/html/rfc6750#section-3) says

> the "error_description" attribute [provides] a human-readable explanation **that is not meant to be displayed to end-users**.

**Comment by MatTheCat** [comment]
That would mean `AccessTokenAuthenticator::$translator` does not serve any purpose anymore; in that case should its `setTranslator` method be no-op?

**Comment by nicolas-grekas** [comment]
~no-op +~ deprecate the method + unwire it yes
