### ISSUE TITLE
Add ISO-3166-1 Numeric codes to Intl component

### ISSUE THREAD

**Issue by benr77** [symfony/symfony#50860]
### Description

The Intl component is supporting access to 2 and 3 letter ISO codes for countries. 

However, there is a third, numeric type which is not currently supported. 
https://www.iso.org/obp/ui/#search/code/

Currently my requirement is to convert a 2 letter country code (FR) into a numeric equivalent (250) and it looks like I'm going to either have to install another package (https://github.com/thephpleague/iso3166) or hard-code a static list in my codebase.

Would it be acceptable to add these numeric codes to the Intl component?

Thanks!

**Comment by javiereguiluz** [comment]
I think it makes sense to add full support for ISO 3166 by adding these missing numeric codes for countries and territories.

**Comment by fabpot** [comment]
That makes sense to me. Would you like to submit a pull request ?

**Comment by benr77** [comment]
More than happy to do a PR but I've just had a look at the repo and I'm not clear on how it all gets generated so would need some help to get started if that's OK?

**Comment by ro0NL** [comment]
@benr77 the general idea is to compile a map first in `RegionDataGenerator::generateDataForMeta` which is written to resource files, then we need some API to read it, eg. `Countries::getNumericCodes`.

to update the resource files (and debug the data during generation) run `src/Symfony/Component/Intl/Resources/bin/compile`

the data from upstream should already be availble during generation in `$metadataBundle`: https://github.com/unicode-org/icu/blob/70d308731ae01a4187fe49f7ae1c8e1ad1570be6/icu4c/source/data/misc/metadata.txt#L2861-L2868

[withdrawn codes](https://en.wikipedia.org/wiki/ISO_3166-1_numeric#Withdrawn_codes) should be skipped

[deprecated codes](https://github.com/unicode-org/icu/blob/70d308731ae01a4187fe49f7ae1c8e1ad1570be6/icu4c/source/data/misc/metadata.txt#L2817-L2824) should be skipped

**Comment by benr77** [comment]
@ro0NL Thanks for this. I will try and get the PR moving over the weekend.
