### ISSUE TITLE
UrlType and Url constraint changes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#50871]
Recently I used `UrlType` and `Url` constraint and faced some issues:

-----

**(1)** The default value of the `default_protocol` option is `http`

This is problematic because:

**(1.1)** `http` is too legacy; it should be `https`

**(1.2)** If this option is different from `null`, the form field is rendered as `<input type="text" inputmode="url">` instead of `<input type="url">` So, the default behavior is not what you expect. Should we change the default value to `null`?

-----

**(2)** Minor but, first I used `https://` as the value of `default_protocol` (instead of `https`, which is the right value). This means that if you input `foo`, the value is updated as `https://://foo` instead of just `https://foo`

If this happened to others too, maybe we could validate the values passed to this option?

-----

**(3)** The `Url` constraint considers something like `aaa` as a valid URL. I guess this is correct according to some RFC, but it's not what most people would like to accept as a valid URL.

Should we add a config option to require the presence of at least one TLD? Note that I'm not thinking about validating that the TLD is correct, because there are too many TLDs and change often.

Thanks!

**Comment by stof** [comment]
I suggest changing the default value of `default_protocol` to `null` in 7.0 (with a configurable opt-in in 6.4).

Validating that the default protocol does not contain `://` is probably also a good idea (or maybe supporting both modes)

**Comment by Chris53897** [comment]
I guess 3) needs to be this way to allow values like `localhost`. I would assert that this should be allowed

**Comment by javiereguiluz** [comment]
Some of the issues reported here were solved. But the last issue remains: something like `aaa` or `foobar` is considered a valid URL.

As pointed by @Chris53897 maybe it's enough to only support `localhost` and then require other values to contain at least one `.` to ensure that looks like a URL?

**Comment by wouterj** [comment]
Any word is a valid url. You can see this often in local networks, e.g. in a container network you can reference other containers by their name (e.g. with Docker Compose).

I think we can introduce a `requireTld` option, defaulting to `false`, to make it easy for people to validate a string contains a URL with a TLD.

**Comment by xabbuh** [comment]
@wouterj's suggestion makes sense to me. We already have such an option in the `Hostname` constraint.

**Comment by wouterj** [comment]
Oh didn't know we already had such option with the same name on another constraint :smiley: The only issue I see is that an option with the same name has a different default on 2 related constraints (given it's opt-out for `Hostname`).

Should we also deprecate not setting this option, so we can change the default to `true` as well on the `Url` constraint?

**Comment by xabbuh** [comment]
would probably make sense indeed
