### ISSUE TITLE
[Form] EntityType in forms generates too many queries

### ISSUE THREAD

**Issue by passwebcakebat** [symfony/symfony#50898]
### Symfony version(s) affected

5.4.24

### Description

The EntityType field in forms generates too many queries in the POST action.

If field is multiple and user select about 15/20 options POST method add additional queries in each options.

I know that the EntityType want to check if selected option is in our database.
But why does it work in foreach and send query through each selected options.

In **ORMQueryBuilderLoader.php** there is a method called **getEntitiesByIds**.
But when we see how it works we can see that it works in foreach of our selected options.

When we add additional inserts and selections the database queries are too large.

### How to reproduce

`$builder->add('test', EntityType::class, [
            'label' => 'Label test',
            'class' => YourClass::class,
            'multiple' => true,
            'required' => false,
            'choice_label' => 'name',
            'choice_value' => 'id',
        ]);`

### Possible Solution

Maybe there is the chance to change this foreach to one request with all selected options with IN array.

**Comment by stof** [comment]
We will need a reproducer for that.

I strongly doubt that your suggestion of the cause is right. `getEntitiesByIds` loads all the entities for the list of values as a single query using `IN`

**Comment by passwebcakebat** [comment]
So the problem is in another place. Because when I debuging that function, variable method get only one parameter not whole array.

![image](https://github.com/symfony/symfony/assets/131235560/2e99e9f0-50a2-4878-be64-546e897fb4ba)
etc.

**Comment by stof** [comment]
again, please provide a reproducer.

**Comment by passwebcakebat** [comment]
Hi,
https://github.com/passwebcakebat/Symfony-5.4-EntityTypeBug
I'm sending repo with reproducer.

Symfony ver 5.4
database SQLLite

**Comment by xabbuh** [comment]
What does one have to in that application to reproduce what you experience?

**Comment by passwebcakebat** [comment]
Put debug mark in getEntitiesByIds method, next just add task in /tasks/new

getEntitiesByIds method get value by each and in last call this method get all values

**Comment by xabbuh** [comment]
I think I understand the issue now. It seems this is a regression caused by #39659. Can you please try if #50937 fixes this for you?

**Comment by passwebcakebat** [comment]
#50937 fixed this isssue, thanks
