### ISSUE TITLE
Support backed enums in `#[MapQueryParameter]`

### ISSUE THREAD

**Issue by kells64000** [symfony/symfony#50910]
### Symfony version(s) affected

6.3.1

### Description

If you use #[MapQueryParameter] and type the property with Enum, the QueryParameterValueResolver only accepts scalars.

If I change the resolver to BackedEnumValueResolver, it only looks at the attributes and not the query.
The enum is never resolved and the value is null.

### How to reproduce

Controller:

````php
#[Route('/', name: 'test_param_enum']
public function testParameterAction(#[MapQueryParameter] Status $status = null) 
{
        
}
````

OR

````php
#[Route('/', name: 'test_param_enum']
public function testParameterAction(#[MapQueryParameter(resolver: BackedEnumValueResolver::class)] Status $status = null) 
{
        
}
````

Enum:

````php
enum Status: string
{
    case New = 'new';
    case Published = 'published';
}
````

Query:

````
/?status=new
````

### Possible Solution

1.  Allow enum in QueryParameterValueResolver
2. Check for query parameters in BackedEnumValueResolver
3. Add a new resolver QueryParameterBackedEnumValueResolver
4. ???

**Comment by andersmateusz** [comment]
@kells64000 
Why do u consider this a bug? In documentation (https://symfony.com/blog/new-in-symfony-6-3-query-parameters-mapper) there is no non-scalar value usage example.  According to source code `Symfony\Component\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver` can resolve only `Symfony\Component\HttpFoundation\Request::attributes`. Considering another `Symfony\Component\HttpKernel\ControllerValueResolverInterface` implementation i.e. `Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver` there is also only support for attributes: 
``` php
 if (!is_a($argument->getType(), \DateTimeInterface::class, true) || !$request->attributes->has($argument->getName())) {
     return [];
 }
```
So I would consider this as feature, not as a bug. The question is whether this  feature is needed or not.

**Comment by derrabus** [comment]
I agree that this is a new feature. And it makes total sense to support enums here. Do you want to wirk on a PR?

**Comment by andersmateusz** [comment]
@derrabus 
Sure, I can work on this. I propose to change issue name to '#[MapQueryParameter] Add support for \BackedEnum'.

**Comment by kells64000** [comment]
It was a bug for me because why can I use any resolver if none of them looks at the query parameters?

**Comment by andersmateusz** [comment]
> It was a bug for me because why can I use any resolver if none of them looks at the query parameters?

Only `QueryParameterValueResolver` supports resolving query parameters, besides there are many implementations of `ArgumentResolverInterface`, but I agree that it is misleading that you can use any  `ArgumentResolverInterface` as argument for `#[MapQueryParameter]`. I guess authors aimed to allow for custom query parameter value resolver. There are annotations that suggest that you can use only `QueryParameterValueResolver` for resolving params, although it would be good to make  typing more precise e.i. by using intersection types how i described in my PR #51004.
