### ISSUE TITLE
Support translatable Enum in Forms

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#50919]
### Description

I found [this StackOverflow post](https://stackoverflow.com/a/74642943/1489264) showing how to make an Enum translatable using `TranslatableInterface`:

```php
enum NotifyType: int implements TranslatableInterface
{
    case EMAIL = 1;
    case WEBHOOK = 2;
    case PUNCH_OUT = 4;

    public function trans(TranslatorInterface $translator, string $locale = null): string
    {
        return match ($this) {
            self::EMAIL     => $translator->trans('supplier.notify.email', locale: $locale),
            self::WEBHOOK   => $translator->trans('supplier.notify.webhook', locale: $locale),
            self::PUNCH_OUT => $translator->trans('supplier.notify.punch_out', locale: $locale),
        };
    }
}
```

```
PHP usage
NotifyType::EMAIL->trans($this->translator)

Twig usage
{{ supplier.notifyType | trans }}
```

I would love to see this also supported by the Form component to automatically show the translated label when using an [`EnumType`](https://symfony.com/doc/current/reference/forms/types/enum.html) with an Enum implementing the `TranslatableInterface`.

This can be a good solution for https://github.com/symfony/symfony/issues/44596

**Comment by derrabus** [comment]
Sounds reasonable. Do you want to work on that?

**Comment by Seb33300** [comment]
Yes, I am planing to work on this but not sure when I will find the time 😅
If someone want to give a try, please let me know here.
Otherwise, I may start working on it in couple of weeks.

**Comment by Seb33300** [comment]
Just took a rapid look in the code and realized that this will be very easy to implement.
So here is the PR: https://github.com/symfony/symfony/pull/50931
