### ISSUE TITLE
[Security] Automatically create logout route if it does not exists

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#50920]
### Description

Ref https://github.com/symfony/symfony/issues/45827#issuecomment-1620148846:

When the value of `logout` is set to `true`(which is equivalent to `logout: { path: '/logout' }`) or is set to a path e.g.`logout: {  path: '/some-logout-path' }` and no such route exists, we could define it automatically from a compiler pass or any another way (ideally with no runtime overhead). 
That would remove the error-prone and odd need to declare that route explicitly. 
We'd need to make the docs super clear about when one actually needs to define that route explicitly with or without attached controller. Bonus if we can make that route publicly accessible by default, if it doesn't make it too much confusing of course.

**Comment by MatTheCat** [comment]
AFAICT there is currently no way to add routes at compile time, and it seems this is not something we want:

> we should make sure [not to] create a way for bundles to automatically register routes.
>
> — https://github.com/symfony/symfony/issues/37786#issuecomment-671819477

The SecurityBundle could come with a `routing.route_loader` service to create logout routes, but it would be the user’s responsibility to load it (could be included in a recipe though).

**Comment by wouterj** [comment]
I do like the route loader approach. We could easily implement the user configuration in the SecurityBundle recipe, and we don't break any of the core principles of the Routing component.
