### ISSUE TITLE
[Messenger] More verbose information about message being retried

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#50948]
### Description

When I retry several messages without `--force`, Symfony asks for confirmation. However, while asking to configrm the removal of a specific message, no context is given. That might be okay for a single message, but in the example below I don't know what I'm confirming. I think it should at the very least include the message ID in the confirmation question, but maybe the same info as shown in `bin/console messenger:failed:show` is even better?

```bash
tjv@ap1:~/prod$ bin/console messenger:failed:remove 31401 31402 31403 31429 31430 31431

 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31401 removed.


 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31402 removed.


 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31403 removed.


 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31429 removed.


 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31430 removed.


 Do you want to permanently remove this message? (yes/no) [no]:
 > y


 [OK] Message with id 31431 removed.

tjv@ap1:~/prod$ bin/console messenger:failed:show
There is 1 message pending in the failure transport.
 ------- ------------------------------------------------ --------------------- -----------------------------------------------------------------------
  Id      Class                                            Failed at             Error
 ------- ------------------------------------------------ --------------------- -----------------------------------------------------------------------
  31391   App\Message\Extern\SyncMessage                   2023-07-11 18:20:04   Backend not available
 ------- ------------------------------------------------ --------------------- -----------------------------------------------------------------------

 // Run messenger:failed:show {id} --transport=failed -vv to see message details.

```

**Comment by DEVizzent** [comment]
Have you tried to use the option `--show-messages`?

**Comment by tjveldhuizen** [comment]
@DEVizzent No, since that option is only available for `bin/console messenger:failed:remove` 😅

**Comment by DEVizzent** [comment]
But in your request you are talking about this command. `tjv@ap1:~/prod$ bin/console messenger:failed:remove 31401 31402 31403 31429 31430 31431`

> I think it should at the very least include the message ID in the confirmation question, but maybe the same info as shown in bin/console messenger:failed:show is even better?

I could add the message ID, I agree. But to show the same info that you have in `bin/console messenger:failed:show` you can use: `--show-message`.

**Comment by tjveldhuizen** [comment]
Ow wait, I was mixing two issues I posted 😅 Good suggestion, the message ID is already in the output! In my opinion this might be the default in interactive mode, but I can work with this addition in my command.
