### ISSUE TITLE
Web Profiler inconsistent error - Undefined array key 4

### ISSUE THREAD

**Issue by radar3301** [symfony/symfony#50942]
### Symfony version(s) affected

6.3.1

### Description

Very occassionally, when navigating '/logout' (302 redirect) '/' (302 redirect) '/login, I get the following errors:

```
ErrorException:
Warning: Undefined array key 4

  at symfony\http-kernel\Profiler\FileProfilerStorage.php:312
  at Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->removeExpiredProfiles()
  at Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write()
  at Symfony\Component\HttpKernel\Profiler\Profiler->saveProfile()
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate()
``` and ```
BadMethodCallException:
Symfony\Component\VarDumper\Cloner\Data objects are immutable.

in symfony\var-dumper\Cloner\Data.php (line 152)
Data->offsetSet() in symfony\http-kernel\DataCollector\EventDataCollector.php (line 92)
EventDataCollector->setCalledListeners() in symfony\http-kernel\DataCollector\EventDataCollector.php (line 74)
EventDataCollector->lateCollect() in symfony\http-kernel\Profiler\Profiler.php (line 100)
Profiler->saveProfile() in symfony\http-kernel\EventListener\ProfilerListener.php (line 135)
ProfilerListener->onKernelTerminate() in symfony\event-dispatcher\Debug\WrappedListener.php (line 116)
WrappedListener->__invoke() in symfony\event-dispatcher\EventDispatcher.php (line 220)
```

The interesting thing (maybe?) is that '/login' returns HTTP 200, but it looks like the AJAX request is failing? But I don't have any entries in the developer console for any ajax requests... And yet the page output looks like this:
![image](https://github.com/symfony/symfony/assets/767328/60c10915-8c60-46fc-9ffe-1823d7c436f7)

### How to reproduce

No idea how to reproduce, as it's inconsistent. I'm assuming it's a delay with the file system, maybe? I don't know.

**Comment by radar3301** [comment]
heh... I found these gems in the 'index.csv' file:

L364: `062a6b,404`
L726: `02`
L728: (empty line)

**Comment by MatTheCat** [comment]
Seems to be the same issue than in #50816 and #50913.

If you, @benjaminfunk or @Pelagoss ever manage to share a reproducer, feel free to do so!

**Comment by radar3301** [comment]
Is it even possible to mock concurrent file writes to the same file from two different requests?

**Comment by radar3301** [comment]
Closing in favor of #50947.
