### ISSUE TITLE
[Routing] Transform `Requirement` enum to interface

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#50959]
### Description

Hi everyone,

I would like to transform the class [`Symfony\Component\Routing\Requirement\Requirement`](
https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Routing/Requirement/Requirement.php) from a enum to an interface.

By doing this, it will allows people to create their `Requirement` implementation with their own requirements. 

They will be able to **only import** their own `Requirement` implementation, without having to sometimes import Symfony `Requirement`. One import of two.

### Example

The user `Requirement` implementation could looks like this:

```php
namespace App\Routing;

interface Requirement extends Symfony\Component\Routing\Requirement\Requirement
{
    public const MY_CUSTOM_REQUIREMENT = '...';
}
```

They can now use `Requirement::MY_CUSTOM_REQUIREMENT` and `Requirement::ASCII_SLUG` with a single import.

WDYT? Thanks!

**Comment by stof** [comment]
If you only want to have a single import, you can still define a constant in your own interface that references the Symfony constant.

By making the Symfony code define an interface, it means we have to support implementing and extending the interface, not just referencing the constant.

**Comment by derrabus** [comment]
> They will be able to **only import** their own `Requirement` implementation, without having to sometimes import Symfony `Requirement`. One import of two.

I fail to see how this is actually desirable. There is no shame in importing two classes with constants.

**Comment by Kocal** [comment]
I found this more convenient as we won't have to deal with import alias.

But I will go for the Stof solution, I didn't think about it and it seems good aswell.

Thanks!
