### ISSUE TITLE
[Form] Add "prototype_data" option to collection type

### ISSUE THREAD

**Issue by kgilden** [symfony/symfony#5095]
It is currently not possible to set default values for a `Collection` prototype. The default values specified in an entity are not passed to the prototype. However, setting the `data` option causes the prototype to have the value set.

**Comment by jrobeson** [comment]
@webmozart :  we don't have too much time before this freeze at this point though :)

**Comment by nifr** [comment]
any updates here ?

**Comment by webmozart** [comment]
Fixed in #12314.
