### ISSUE TITLE
[WebProfiler] Error "Deprecated: str_contains(): Passing null to parameter #1 ($haystack) of type string ..." in dev environment with no debug

### ISSUE THREAD

**Issue by alexbuyanow** [symfony/symfony#50977]
### Symfony version(s) affected

6.*

### Description

PHP version: >=8.1
Symfony version: (probably) any with dependes on PHP>=8.1

Sent HTTP request to my service with no header `Content-type`. Testing in **dev** (or **test**) mode with **debug** disabled. 

And have error `Deprecated: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/vendor/symfony/web-profiler-bundle/EventListener/WebDebugToolbarListener.php on line 124`

### How to reproduce

- Set environments:
```
APP_ENV=dev
APP_DEBUG=false
 ```
- `WebProfilerBundle` enabled and collects data 
- Send HTTP request to any endpoint with no `Content-type` header

### Possible Solution

Its working for me

```
--- a/vendor/symfony/web-profiler-bundle/EventListener/WebDebugToolbarListener.php	
+++ b/vendor/symfony/web-profiler-bundle/EventListener/WebDebugToolbarListener.php
@@ -121,7 +121,7 @@
         if (self::DISABLED === $this->mode
             || !$response->headers->has('X-Debug-Token')
             || $response->isRedirection()
-            || ($response->headers->has('Content-Type') && !str_contains($response->headers->get('Content-Type'), 'html'))
+            || ($response->headers->has('Content-Type') && !str_contains($response->headers->get('Content-Type') ?? '', 'html'))
             || 'html' !== $request->getRequestFormat()
             || false !== stripos($response->headers->get('Content-Disposition', ''), 'attachment;')
         ) {
```

But unfortunly not working
```
            || ($response->headers->has('Content-Type') && !str_contains($response->headers->get('Content-Type', ''), 'html'))
```

**Comment by derrabus** [comment]
> ```php
> || ($response->headers->has('Content-Type') && !str_contains($response->headers->get('Content-Type') ?? '', 'html'))
> ```

I don't understand why this fixes an issue for you. If `has()` returns `true`, why would `get()` return `null`?

Can you please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug?

**Comment by HypeMC** [comment]
> I don't understand why this fixes an issue for you. If `has()` returns `true`, why would `get()` return `null`?

@derrabus Actually, [`has()` uses `array_key_exists()`](https://github.com/symfony/symfony/blob/0be2622bc9c7969c4155be5f2c3f4ccdaaa0bd0d/src/Symfony/Component/HttpFoundation/HeaderBag.php#L160) and the `$values` argument of `set()` is [allowed to be `null`](https://github.com/symfony/symfony/blob/0be2622bc9c7969c4155be5f2c3f4ccdaaa0bd0d/src/Symfony/Component/HttpFoundation/HeaderBag.php#L130), so this could happen.

**Comment by derrabus** [comment]
I see. Someone send a PR please.
