### ISSUE TITLE
[symfony/http-client] CurlHttpClient::getInfo() throws an exception.

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony#50971]
### Symfony version(s) affected

6.3.1

### Description

Method `getInfo() ` from class `CurlHttpClient` throws an exception instead of returning current info.

### How to reproduce

Write this code in any Symfony Controller :
```
    $client = new CurlHttpClient();
    $response = $client->request('GET', 'https://dummyjson.com/users/filter', [
        'query' => ['foo' => 'bar']
    ]);
    dd($response->getInfo());
```
Result :
![image](https://github.com/symfony/symfony/assets/12775815/cd9e2300-2f1c-4c12-bd8c-ba71875ddb91)

### Additional Context

php : 8.1
```
curl_version()
  "version_number" => 475136
  "age" => 4
  "features" => 4179869
  "ssl_version_number" => 0
  "version" => "7.64.0"
  "host" => "x86_64-pc-linux-gnu"
  "ssl_version" => "OpenSSL/1.1.1d"
  "libz_version" => "1.2.11"
  "protocols" => array:23 [▶]
  "ares" => ""
  "ares_num" => 0
  "libidn" => "2.0.5"
  "iconv_ver_num" => 0
  "libssh_version" => "libssh2/1.8.0"
  "brotli_ver_num" => 0
  "brotli_version" => ""
```

Got same problem with NativeHttpClient.

**Comment by derrabus** [comment]
The exception tells you that the server answers with a HTTP 500 error response. We can't do much about that broken server.
