### ISSUE TITLE
Extend workflow component graph /debugger by event listener actions

### ISSUE THREAD

**Issue by kswzr** [symfony/symfony#50976]
### Description

When using the symfony workflow component, I have the issue, that I don't really can easily see, what happens before, on, after different transitions. 

It is only possible to see, what states can be reached and which transition can be applied.

I think it would be very helpful, to visualize in some way the different EventListeners which subscribes to the various transition events. Maybe in the Symfony Debugger, otherwise in the state machine graph. We could use here the EventListeners name (+ Method Name, if it does not have only an invoke method).

### Example

Imagine, we have a payment state machine with a transition "capture", from "processing" to "captured". 
When the state machine dispatches the "workflow.payment.completed.capture" event, I have an EventListener called "BookAccountingItemsListener::invoke", "PaymentNotificationListener::sendCapturedCustomerEmail".

Seeing that information in some way, could be helpful to understand and see the full process and business logic behind that.

**Comment by lyrixx** [comment]
I totally agree. I'm working on a new project where we'll use massively the Workflow component in complex situation (Same entity, different workflow depending on the context). I'm planning to add new features to it!

**Comment by lyrixx** [comment]
Small preview #teasing :D 
![image](https://github.com/symfony/symfony/assets/408368/75d751c8-efca-4b79-9bb2-82c93d747c95)

**Comment by kswzr** [comment]
@lyrixx thanks for that amazing work and progress! Looks really good and as I have expected it :)
