### ISSUE TITLE
[Form] Support simple hydration

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#5098]
`EntityChoiceList` should use a combination of array hydration and post-processing to generate a choices array as used by the "choice" type. Depending on the result size, this can be around 50ms faster than entity hydration. This hydration mode must be configurable through an option "hydration_mode".

The `getChoices()` and `getChoicesForValues()` methods should run separate queries to fetch real entities, should they be called.

**Comment by tgalopin** [comment]
This has been fixed by https://github.com/symfony/symfony/pull/14050 and should be closed IMO.
