### ISSUE TITLE
[HttpKernel] Allow customising HTTP status code on validation error of #[MapRequestPayload] objects

### ISSUE THREAD

**Issue by siketyan** [symfony/symfony#50992]
### Description

`#[MapRequestPayload]` attribute, introduced in Symfony 6.3, is an awesome feature for APIs that use JSON for requests. The attribute works with Serializer and Validator components, and returns `422 Unprocessable Entity` status code on Validator returned any violation(s). However, in API development, sometimes we want `400 Bad Request` instead of 422. So it would be great if we can customise the status code that MapRequestPayload returns on validation error.

### Option 1. Use attribute to customise for each endpoint

```php
#[Route('/pets', methods: ['POST'])]
public function createPet(
    #[MapRequestPayload(statusOnError: Response::HTTP_BAD_REQUEST) PetDto $pet,
): Response;
```

### Option 2. Use config to customise globally

```yaml
framework:
    map_request_payload:
        default_status_code_on_error: 400
```

**Comment by ro0NL** [comment]
does it matter much? it's a 4xx :shrug: 

edit: see #50767

**Comment by siketyan** [comment]
@ro0NL
Oh, I just submitted a duplicated PR 😓 
Thank you for the mentioning!

**Comment by siketyan** [comment]
#50767 does not have any issues to be fixed, so I'll reopen this and keep open for tracking.

**Comment by siketyan** [comment]
#50767 does not have any issues to be fixed, so I'll reopen this and keep open for tracking the issue.
