### ISSUE TITLE
[Routing] Adding Route to Abstract Class doesn't apply it to subclasses

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#51026]
### Symfony version(s) affected

6.3.1

### Description

Usually when you add a Route Annotation to the class it applies to all the routes within. This is not the case when you add the Route to a abstract class and its subclasses.

### How to reproduce

```php
#[Route('/foo')]
abstract class Foo {
}

class Bar extends Foo {
    #[Route('/bar')]
    public function bar() {
   }
}

```

I'd expect the url to be `/foo/bar` in this case, but it's just `/foo`

**Comment by derrabus** [comment]
This is not a bug. Route annotations are not inherited and that's by design.

**Comment by KDederichs** [comment]
Ah good to know, thanks!
