### ISSUE TITLE
[Form] Combination [html5 => false, widget => single_text] is not possible anymore in DateTimeType forms

### ISSUE THREAD

**Issue by faizanakram99** [symfony/symfony#51046]
### Symfony version(s) affected

6.3.x

### Description

#49588 breaks forms with this combination `['html5' => false, 'widget' => 'single_text']`. It is not possible to use `single_text` without html mode anymore.

We've custom form extensions built on top of this behaviour which rendered a single text field for dates and drop-downs for time, it doesn't work anymore.

### How to reproduce

I don't have a reproducer yet, I will see if I can provide one.

**Comment by xabbuh** [comment]
What does "it is not possible anymore" mean exactly? What behaviour did you expect? What happened instead? Can you please also share the code of your form type extension.

**Comment by xabbuh** [comment]
@faizanakram99 Do you have more information? With the current description the issue is not actionable.

**Comment by faizanakram99** [comment]
@xabbuh not yet, lets close this for now. I will reopen once (read if) i've a proper reproducer.
