### ISSUE TITLE
[HttpClient] Add more response exceptions

### ISSUE THREAD

**Issue by adpeyre** [symfony/symfony#51040]
### Description

Hello,

I think, it could be interesting to add more response exceptions for targeting ones easier.
It is common to react differently depending on the return code, for example a 404 error.

What do you think about that ?
I could create a PR if it's ok for you.

Ty

### Example

Today :

``` php
try {
     $content = $response->getContent();
} catch (ClientException $exception) {
    if (404 === $exception->getCode()) {
           return null;
    }

    throw $exception;
}
```

My suggestion :
``` php
try {
     $content = $response->getContent();
} catch (NotFoundClientException $exception) {
    return null;
}
```

**Comment by nicolas-grekas** [comment]
I would recommend not relying on exceptions instead:

```php
if (404 === $response->getStatusCode()) {
     return null; 
}
$content = $response->getContent();
```

**Comment by adpeyre** [comment]
My bad, you are right ! 
Try to answer faster next time !
