### ISSUE TITLE
[Scheduler] NPE in debug:scheduler command

### ISSUE THREAD

**Issue by faizanakram99** [symfony/symfony#51052]
### Symfony version(s) affected

6.3.1

### Description

https://github.com/symfony/symfony/blob/0458c9b5348289b4a45bee91d4475a59f1948b02/src/Symfony/Component/Scheduler/Command/DebugCommand.php#L120

This line causes an NPE since `getNextRunDate` can return null.

### How to reproduce

Return null from any trigger (e.g. `new CallbackTrigger(fn () => null)` and run `debug:scheduler` command

**Comment by kbond** [comment]
Closed via #51055
