### ISSUE TITLE
[Form] Fatal error on sending null in not-nullable DateTimeType field

### ISSUE THREAD

**Issue by superkozel** [symfony/symfony#51053]
### Symfony version(s) affected

6.3.1

### Description

Having NotBlank or NotNull validation rule and using data_class, you get fatal error instead of validation error with any request,
when DateTimeType field is null. Not reproducing in EntityType or scalar types.

### How to reproduce

Given:
Form with DateTimeType::class with NotBlank DateTimeType field

```
public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder
        ->add(
            'date',
            DateTimeType::class,
            [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'html5' => false,
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
```

using data_class with not-nullable DateTime property:

```
public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setDefaults(
        [
            'data_class' => DTO::class
        ]
    );
}
```
```
class DTO
{
    public DateTime $date;
}
```

When try to handle GET or POST request:

```
$form = $this->createForm(DTO::class, null, ['method' => Request::METHOD_POST]);
$form->handleRequest($request);
```

Then error: 

Expected argument of type "DateTime", "null" given at property path "date".

**Comment by xabbuh** [comment]
This is the expected behvaiour. The form first maps the data to your underlying model and only afterwards the validation constraints are evaluated (which of course will never happen if your application terminates with type errors when mapping the data).

Thus I'm closing here as there is no bug. Thank you for understanding.
