### ISSUE TITLE
Embedded CollectionType with custom FormType as entry_type field with no value

### ISSUE THREAD

**Issue by Pascal-Meinecke** [symfony/symfony#51066]
### Symfony version(s) affected

6.2.9

### Description

If I try to add a custom entity form type as data for a form type using the CollectionType, the EntityType field within the custom entity form type is always null even if I pass the corresponding data already to the form before the form handling. It seems like $form->handleRequest($request) is the cause that the value will be set to null again even if it was initialized differently.

### How to reproduce

For the example I will use pseudonyms and only code parts. 

1.  Create a custom FormType "MyParentFormType". 
2. Create another custom FormType "MyDocumentType" containing two fields like so:
```
$builder
            ->add('type', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'name',
                'label_attr' => [
                    'class' => 'text-uppercase text-sm mb-3',
                ],
                'required' => true,
            ])
            ->add('files', FileType::class, [
                'translation_domain' => 'security',
                'label' => false,
                'required' => true,
                'multiple' => true,
                'attr' => [
                    'class' => 'form-control',
                ],
                'row_attr' => ['class' => 'form-group'],
            ]);
```

3. The configure options for "MyDocumentType" should look something like this: 
```
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'class' => Document::class,
        ]);
    }
```

4. Create an entity "Document" and an entity "Type" referencing each other as a ManyToOne reference. Inside the Document entity file the attribute looks like this: 
`#[ORM\ManyToOne(targetEntity: Type::class, inversedBy: 'documents')]
    private ?Type $type = null;` 

Add coherent getters and setters and the Type side as OneToMany referencing the Document entity.

5. Now within the "MyParentType" add a CollectionType field like this: 
```
$builder->add('documents', CollectionType::class, [
            'entry_type' => MyDocumentType::class,
            'entry_options' => [
                'label' => false,
            ],
            'allow_add' => true,
        ])
```
        
6. For the controller there should be some preperatioj data. Create a controller rendering this form (coherently a template for rendering (twig) needs to be created aswell). Now "MyParentFormType" should get an object of a class "MyParentForm" (this is just example, these is not real data). One the entity is created it should have a Reference to the documents like so: 
```
#[ORM\OneToMany(mappedBy: 'myParentForm', targetEntity: Document::class, cascade: ['persist'])]
    private Collection $documents;
```
 
 The Document side should coherently contain the ManyToOne reference to MyParentForm.
 
7. Once that is setup call within your controller the form passing an object of MyParentForm. But before that, to preset multiple fields for the document and the type for the collection something like this should be called (HINT: partly pseudo code following): 
```
$myParentForm = new MyParentForm();

        foreach(<$types> as $documentTypes) {
            if($documentTypes instanceof Type) {
                $document = new Document();
                $document->setType($documentTypes);
                $this->entityManager->persist($document);
                $aircraft->addDocument($document); // TODO add / remove / has function should be added for collection handling
                $this->entityManager->persist($aircraft);
            }
        }
        
        // ... some additional handling ... 
        
        $form = $this-createForm(MyParentForm::class, $myParentForm, []);
        $form->handleRequest($request);
        
        // Following here is submit handling, persisting the data of the form to get the Document type and the document files for saving within the database. 
        
```
Once the form is rendered it should provide already an input for each type you've passed to the collection. But now if you try to access the form data after submit, the EntityType (information of type) is not set within the submitted form data. (Either trying to access it by something like `$form->getData()->getDocuments()[<documentIndex>]->getType()` or `$myParentForm->getDocuments(<documentIndex>)->getType()`.)

The type here in my case is always null after submit or concrete after the `$form->handleRequest($request)` call.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Pascal-Meinecke** [comment]
> Can you create a small example application that allows to reproduce your issue?

Sorry for the late response. Yes I can create an example application. I'll prepare a small example and post it as soon as I can. Thank you for your help!
