### ISSUE TITLE
[Command] Calling multiple time the same command from code adds required parameter

### ISSUE THREAD

**Issue by cavasinf** [symfony/symfony#51088]
### Symfony version(s) affected

5.4.25

### Description

When calling the same [command from code](https://symfony.com/doc/current/console/calling_commands.html) multiple time,
a required `command` param appears.

### How to reproduce

1. Create Command
```php
<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:test',
)]
class TestCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        for ($i = 0; $i < 2; $i++) {
            $commandToCall     = $this->getApplication()->find('d:m:m');
            $commandDefinition = $commandToCall->getDefinition();

            $commandInput = new ArrayInput([], $commandDefinition);
            $commandToCall->run(
                $commandInput,
                $output
            );
        }

        return Command::SUCCESS;
    }
}
```
2. Run it
3. First time OK ✔️ 
![image](https://github.com/symfony/symfony/assets/25293190/b4a52ad6-498b-4a29-a5de-cc264873bb1f)

5. Second time, new param `command` is required ❌ 
![image](https://github.com/symfony/symfony/assets/25293190/84d5250e-4059-405b-9c75-d27df7216b9f)
6. Error when exec command for the second time:
>  Not enough arguments (missing: "command").  

### Additional Context

For the purpose of this issue, all the logic behind the code has been removed.
We need to run the same command multiple times because we have multiple databases.

**Comment by MatTheCat** [comment]
A command’s definition is merged with its application’s when it is run. This is not supposed to be a problem; but here you
- get the command’s definition inside the loop
- pass this definition to `ArrayInput`

This is not part of the documentation you linked; have you a specific reason for doing so?

**Comment by cavasinf** [comment]
> have you a specific reason for doing so?
- For calling the same command multiple times, 
yes, we have a reason.

- For the "command definition" inside the loop:
I was "afraid" of what will be appended to all configs/params/... when running the command from code.
So to be sure there is no "artifact", redefining everything inside the loop seems more "safe" as all variables will be overridden.

But reading this,
> A command’s definition is merged with its application’s when it is run

makes me think that's not the case.

If I understand well, you are suggesting to have only the `run` function call inside the loop?

**Comment by MatTheCat** [comment]
> If I understand well, you are suggesting to have only the `run` function call inside the loop?

Yep.

Reading the documentation, you probably do not need to pass the command’s definition to `ArrayInput`? In which case you do not need to call `getDefinition` (this was my second point but you missed it :sweat_smile:).

**Comment by cavasinf** [comment]
`ArrayInput` is used BECAUSE it can have the targeted command definition.
If you have a missing/wrong argument/option, it will be checked with the `validate` function from Input

https://github.com/symfony/symfony/blob/8ec0d08d90950d111313fa017cd6ca490441baf9/src/Symfony/Component/Console/Input/Input.php#L36-L78 

I can give more application "context" to be clearer.

**Comment by MatTheCat** [comment]
The input is validated against the command’s definition when it is run (and it does handle the `command` argument oddity).

**Comment by cavasinf** [comment]
True... Removing the command definition from the ArrayInput works as it should.
Bit weird but if it works I'll use it.

But we still need it to convert the arguments/options from the first command to pass them to the command called from code.

Thank you very much @MatTheCat!
