### ISSUE TITLE
[RFC] Shrink recipes for v7

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#51097]
Over time, recipes grow in size. For example, the recipe for 6.2 added the `handle_all_throwables` option to turn it on by default.

It'd be great to shrink recipes by making v7 defaults to the values we have currently in the recipes.

Here is the current config file for framework-bundle v7:
https://github.com/symfony/recipes/blob/main/symfony/framework-bundle/7.0/config/packages/framework.yaml

Let's deprecate not setting all/most of those options and shrink the recipe.
Let's review the other recipes also as part of the same effort.

Feedback and Help Wanted for the implementations.

**Comment by derrabus** [comment]
Low-hanging fruit: symfony/recipes#1225 😇
