### ISSUE TITLE
Request::getPayload(): Return value must be of type Symfony\Component\HttpFoundation\InputBag, Symfony\Component\HttpFoundation\ParameterBag returned

### ISSUE THREAD

**Issue by pixopa** [symfony/symfony#51108]
### Symfony version(s) affected

symfony/http-foundation 6.3.1

### Description

ERROR: Symfony\Component\HttpFoundation\Request::getPayload(): Return value must be of type Symfony\Component\HttpFoundation\InputBag, Symfony\Component\HttpFoundation\ParameterBag returned {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\HttpFoundation\\Request::getPayload(): Return value must be of type Symfony\\Component\\HttpFoundation\\InputBag, Symfony\\Component\\HttpFoundation\\ParameterBag returned at /Users/amitshinde/dev/swagify/users-service/vendor/symfony/http-foundation/Request.php:1517)

### How to reproduce

Upgrade to latest version symfony/http-foundation and when trying to make a basic controller request, we are getting this error -

Symfony\Component\HttpFoundation\Request::getPayload(): Return value must be of type Symfony\Component\HttpFoundation\InputBag, Symfony\Component\HttpFoundation\ParameterBag returned {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\HttpFoundation\\Request::getPayload(): Return value must be of type Symfony\\Component\\HttpFoundation\\InputBag, Symfony\\Component\\HttpFoundation\\ParameterBag returned at ../vendor/symfony/http-foundation/Request.php:1517)

### Possible Solution

This section is causing the problem and returning ParameterBag instead of InputBag -

if ($this->request->count()) {
            return clone $this->request;
        }

**Comment by HypeMC** [comment]
Are you using Laravel by any chance? I'm asking because this exact bug was recently fixed on their side, see https://github.com/laravel/framework/pull/47838

**Comment by vaites** [comment]
Seems to be a Laravel issue. For now the solution is to [downgrade](https://github.com/laravel/framework/issues/47834#issuecomment-1650614590) `symfony/http-foundation`.

**Comment by xabbuh** [comment]
closing then
