### ISSUE TITLE
[Form] Translation of labels

### ISSUE THREAD

**Issue by andersmateusz** [symfony/symfony#51132]
### Description

When creating form and using translations we have to translate label for each field. I came up with idea to translate labels automatically using 'trans_label_prefix' and 'trans_domain' root config, so I've implemented project-specific form extension (shown  in example). I've noticed that in some cases this does not work as expected (e.i. in checkboxes) , but I think this could be imroved. Maybe using parent  config would be better option than using root config. What do you think about implementing such feature?

### Example

Example implementation:
``` php
<?php

declare(strict_types=1);

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Contracts\Translation\TranslatorInterface;

/** Enables automatic translation of form field label */
class LabelTranslationFormExt extends AbstractTypeExtension
{
    public function __construct(private readonly TranslatorInterface $translator)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->setAttribute('trans_label_prefix', $options['trans_label_prefix'])
            ->setAttribute('trans_domain', $options['trans_domain']);
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        if (
            null !== $form->getRoot()->getConfig()->getAttribute('trans_label_prefix')
            and (\array_key_exists('label', $view->vars) and false !== $view->vars['label'])
        ) {
            $transKey = $view->vars['label'] ?? $form->getName();
            $view->vars['label'] = new TranslatableMessage(
                "{$form->getRoot()->getConfig()->getAttribute('trans_label_prefix')}.$transKey",
                domain: $form->getRoot()->getConfig()->getAttribute('trans_domain'),
            );
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['trans_label_prefix' => null, 'trans_domain' => null]);
    }

    public static function getExtendedTypes(): iterable
    {
        return [FormType::class];
    }
}
```
Example usage:
``` php
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', options: ['label' => false])
            ->add('instalments', CollectionType::class,[
                'entry_type' => InstalmentType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'label' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PaymentSchedule::class,
            'trans_domain' => 'entity',
            'trans_label_prefix' => 'payment_schedule',
            'attr' => ['novalidate' => 'novalidate'],
        ]);
    }
```

**Comment by Seb33300** [comment]
Form labels are already automatically translated by Symfony.
Not sure to understand the issue you want to raise here?

**Comment by kevinpapst** [comment]
@Seb33300 Automatically translated ONLY if you follow the pattern: field name = translation key. Which doesn't work in larger apps, because field names repeat, while the translation should be entirely different. Or you want to prefix labels from certain packages under a certain prefix: which is a super common use-case IMO.

Not sure that this code should be part of the framework though, as it can already be solved easily as demonstrated above. You could also use different domain names for different forms. Both approaches have the downside that re-using translations is much more complicated (or not possible at all).

**Comment by andersmateusz** [comment]
I thought that the `translation_domain` option is not propagated to children. As I think about this now, there are three features that I wanted to introduce: using the name as the translation key if the label is not given, propagating the translation domain option to children, and using translation key prefixes. Propagating the translation domain option to children is already implemented. Explicitly declaring the translation key with the `label` option is not so much overhead, and if given, then adding the `translation_prefix` option  is less useful and might even lower code flexibility. @Seb33300 @kevinpapst Thank you for your responses. I close this issue because of the low level of interest and the lower level of possible advantages than I have previously assumed.
