### ISSUE TITLE
[RFC] Deprecate Command $name constructor argument

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#51143]
### Description

Hi,

Would it be considerable to deprecate `$name` in `Console\Command::__construct`? our migration resulted in `parent::__construct('...')` everywhere :sweat_smile:

**Comment by GromNaN** [comment]
👍🏻 I rarely had to rename a command. And `Command::setName()` can be used for this purpose.

**Comment by ro0NL** [comment]
Ideally I'd like to get rid of that too and perhaps the entire base constructor. IIUC it defacto breaks laziness.

**Comment by GromNaN** [comment]
We will always need a way to set the name to register commands without class. 
https://github.com/symfony/symfony/blob/510e51f4f3053339826b0d61ad9459dd1c56c91d/src/Symfony/Component/Console/Application.php#L517-L520

Lazyness is not always an issue with simple console applications.

**Comment by chalasr** [comment]
> We will always need a way to set the name to register commands without class.

Just like a controller doesn't know its route, a command shouldn't need to hold its name. 
Console already has most of the infrastructure needed to make it true:
 
```diff
 public function register(string $name): Command 
 { 
-     return $this->add(new Command($name)); 
+     return $this->commandLoader->add($name, new Command($name)); 
 }
 ```
 
 > Lazyness is not always an issue with simple console applications.
 
Laziness by default does not hurt either :)

**Comment by GromNaN** [comment]
The router analogy makes things clearer. If we can deport the naming of commands to `ConsoleApplication`, that's perfect. For backward compatibility, `Command::setName()` could make a call to `Application::setCommandName()` or something like that.
