### ISSUE TITLE
[Translator] Invalid setLocale method definition

### ISSUE THREAD

**Issue by veylib** [symfony/symfony#51154]
### Symfony version(s) affected

6.3.x

### Description

Class `Symfony\Component\Translation\Translator` implements `Symfony\Contracts\Translation\LocaleAwareInterface`, which has changed its contract in version 3.3.0 ([see](https://github.com/symfony/translation-contracts/commit/04d79e7690a79b7d9f62e150aef3b42ef1112d61)). The `symfony/translation` requires a version ^2.5|^3.0, and this change is causing an error:

`Fatal error: Declaration of Symfony\Component\Translation\Translator::setLocale(string $locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale): void in /var/www/vendor/symfony/translation/Translator.php on line 132."`

### How to reproduce

Install `symfony/translation` in version ^6.3 (`symfony/translation-contracts` will be installed in version 3.3 by the package dependency).

### Possible Solution

Fix contract of affected class:

```
class Translator implements TranslatorInterface, TranslatorBagInterface, LocaleAwareInterface
{
    // ...
    public function setLocale(string $locale): void
    // ...
}
```

**Comment by PhilETaylor** [comment]
This also affects 6.4-dev 

```
<snip>
  - Installing symfony/translation (6.4.x-dev 21b5d0c): Extracting archive
  - Installing symfony/translation-contracts (dev-main aab8519): Extracting archive
<snip>
!!
!!  Fatal error: Declaration of Symfony\Component\Translation\Translator::setLocale(string $locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale): void in /Users/phil/Sites/domain.com/vendor/symfony/translation/Translator.php on line 132
!!  PHP Fatal error:  Declaration of Symfony\Component\Translation\Translator::setLocale(string $locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale): void in /Users/phil/Sites/domain.com/vendor/symfony/translation/Translator.php on line 132
!!  Symfony\Component\ErrorHandler\Error\FatalError {#1430
!!    #message: "Compile Error: Declaration of Symfony\Component\Translation\Translator::setLocale(string $locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale): void"
!!    #code: 0
!!    #file: "./vendor/symfony/translation/Translator.php"
!!    #line: 132
!!    -error: array:4 [
!!      "type" => 64
!!      "message" => "Declaration of Symfony\Component\Translation\Translator::setLocale(string $locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale): void"
!!      "file" => "/Users/phil/Sites/domain.com/vendor/symfony/translation/Translator.php"
!!      "line" => 132
!!    ]
!!  }
!!
```

> which has changed its contract in version 3.3.0

I doubt it - that change was only made 3 weeks ago (Jul 5th) in https://github.com/symfony/translation-contracts/commit/04d79e7690a79b7d9f62e150aef3b42ef1112d61 by @nicolas-grekas @wouterj whereas the 3.3.0 tag is dated May 30

For you @veylib you should check you are really running 3.3.0 and not dev-main aab8519

For the rest of us using 6.4-dev, got to wait for the stability :) or test PR https://github.com/symfony/symfony/pull/51156

**Comment by fancyweb** [comment]
v3.3.0 of `symfony/translation-contracts` does not have this real return type :thinking:

Which version are you using exactly? (`composer show symfony/translation-contracts`)

**Comment by PhilETaylor** [comment]
this was all that was needed to get my dev platform up and running to be used today (with 6.4-dev) https://github.com/symfony/symfony/pull/51155

**Comment by veylib** [comment]
Before upgrade from 6.2.* to 6.3.*
![image](https://github.com/symfony/symfony/assets/22482223/da8bf6c8-e84d-4d90-bb04-7434d5dcdf10)

After upgrade to 6.3.*
![image](https://github.com/symfony/symfony/assets/22482223/ec3b9b85-444c-49ea-bfc5-0802874a5cf4)

**Comment by veylib** [comment]
My mistake - I have `symfony/translation` in dev stability 
![image](https://github.com/symfony/symfony/assets/22482223/1a701489-2fb2-40fa-8550-2f2839510e2c)
Which allow to install contract in dev stab (3.4.x-dev)
![image](https://github.com/symfony/symfony/assets/22482223/b1c829f9-6342-49ec-a936-6c468aa5a5b6)

However, `symfony/translation` in `6.3.0` allow to install `symfony/translation-contracts` in `3.4.X-dev`. Should symfony/translation has defined minimum-stability to dev (line 58 https://github.com/symfony/translation/blob/v6.3.0/composer.json) ?
