### ISSUE TITLE
Asset symlinks are failing

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#51183]
### Symfony version(s) affected

6.3.2

### Description

`bin/console assets:install public --symlink` is no longer working in 6.3.2.

Console output is fine and it says it has created absolute symlinks. However, the public/bundles folder is empty.

Reverting to 6.3.1 solves the problem

### How to reproduce

`bin/console assets:install public --symlink`

**Comment by xabbuh** [comment]
Can this also be caused by #50885?

**Comment by trsteel88** [comment]
The release of 6.3.3 solves this. Thanks.
