### ISSUE TITLE
6.3.3 release marked as EOL - was that meant to be the last 6.2.x release instead?

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/symfony#51187]
### Symfony version(s) affected

6.3.3

### Description

6.3.3 release marked as EOL - was that meant to be the last 6.2.x release instead?

### How to reproduce

<img width="956" alt="image" src="https://github.com/symfony/symfony/assets/2829600/9435ad78-7d36-4ead-900a-c8c5cf97f584">

**Comment by derrabus** [comment]
Yes, good catch. 👍🏻

**Comment by GrahamCampbell** [comment]
Should there be a 6.2.14 tagged today?

**Comment by fabpot** [comment]
@GrahamCampbell Done for 6.2.14

**Comment by GrahamCampbell** [comment]
🚀
