### ISSUE TITLE
Clock component breaks preload

### ISSUE THREAD

**Issue by andriusvo** [symfony/symfony#51180]
### Symfony version(s) affected

6.2 / 6.3

### Description

While using Symfony Clock component and using preload, this raises an issue:

PHP message: PHP Fatal error:  Cannot redeclare Symfony\\Component\\Clock\\now() (previously declared in vendor/symfony/clock/Resources/now.php:22

### How to reproduce

1. Install symfony/clock component
2. Use PHP opcache preload function
3. Reload the page, check the error

**Comment by xabbuh** [comment]
see #51190
