### ISSUE TITLE
[Scheduler] "dynamic" schedules

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#51206]
### Description

I've talked to a few users who keep their scheduled tasks in a database and want to use scheduler to run them. This is not easily possible now as the schedules are set when first running `messenger:consume scheduler_default`.

Within the current scheduler architecture, what would be required to achieve this? I'm don't have a great understanding of the deep scheduler internals (the trigger heap system).

### Example

```php
class MySchedule implements ScheduleProviderInterface
{
    public function getSchedule(): Schedule
    {
        $schedule = new Schedule();

        // fetch tasks from db and add to schedule as recurring messages

        return $schedule;
    }
}
```

**Comment by danielburger1337** [comment]
This would be a nice feature. 

A possible workaround though is to execute the `messenger:stop-workers` command everytime your schedule changes. 
Only downside is, that **EVERY** worker (even non-scheduler workers) will be restarted, but in most cases this shouldnt be a big problem.

You can excute Commands in Controllers very easily:
https://symfony.com/doc/current/console/command_in_controller.html

**Comment by daniels0056** [comment]
I'm no expert but isn't it more logical to be static in the scheduler?

In your message handler you could fire "new" messages to your normal queues, such as the default async queue, I think that would make it more logical from an entry point view. That way you don't have to restart your workers.

**Comment by danielburger1337** [comment]
Thats not that easy. The use case are dynamic schedules that should be able to be modified at runtime. 
For example whether a Message should be executed every 15 or 30 minutes.

The only way your suggestion would work (imo) is that the developer would have to create a single scheduled message and compute in its message handler whether a sub-message should be dispatched at this moment or not. The computing whether or not it should is of course possible, but not that simple and the scheduler actually does this internally already.

It would be nice to have the framework handle that for you (even though I have no idea right now how Symfony could make this feature in any way shape or form generic enough so most people could reuse it).

**Comment by stof** [comment]
The hard part for that is that Symfony currently reads the schedules when starting the long-running consumer. Reacting to dynamic configuration changes would require constantly reloading the configuration, which is hard to integrate in Symfony.

Maybe your case could be implemented using a custom implementation of the TriggerInterface that would read its config from your DB when `getNextRunDate` is called (so that it uses the latest config). You can then reuse an existing implementation of TriggerInterface inside your method to delegate the actual computation, once you know which trigger you need.

**Comment by valtzu** [comment]
Iterating on @danielburger1337's [workaround](https://github.com/symfony/symfony/issues/51206#issuecomment-1666952356), it's possible to eliminate the need of all workers stopped/restarted:

```php
#[AsSchedule('doctrine')]
class DoctrineScheduleProvider implements ScheduleProviderInterface
{
    private string $scheduleChecksum = '';

    public function __construct(
        private readonly ScheduledCommandRepository $scheduledMessageRepository,
        private readonly LoggerInterface $logger,
    ) {
    }

    #[AsEventListener]
    public function stopWorkerOnScheduleChange(WorkerRunningEvent $event): void
    {
        if (!in_array('scheduler_doctrine', $event->getWorker()->getMetadata()->getTransportNames()) || !$event->isWorkerIdle()) {
            return;
        }

        // Whatever logic to check if the schedule is up to date – findAll() is not the most efficient here
        $all = $this->scheduledMessageRepository->findAll();
        if (hash('crc32', serialize($all)) === $this->scheduleChecksum) {
            return;
        }

        $this->logger->info("The schedule has changed, stopping the worker...");
        $event->getWorker()->stop();
    }

    public function getSchedule(): Schedule
    {
        $all = $this->scheduledMessageRepository->findAll();
        $this->scheduleChecksum = hash('crc32', serialize($all));
        $schedule = new Schedule();
        foreach ($all as $task) {
            $schedule->add($task->toRecurringMessage());
        }

        return $schedule;
    }
}
```

This of course has the downside of adding one extra query to the messenger worker loop.

**Comment by danielburger1337** [comment]
I have not tested this workaround, but it looks promising!
