### ISSUE TITLE
Update sendinblue SMTP host

### ISSUE THREAD

**Issue by TLassalle** [symfony/symfony#51222]
### Description

As mentionned [here](https://developers.brevo.com/docs/changes-in-smtp-relay-address?utm_source=brevo&utm_medium=email&utm_campaign=FR-product-update-SMTP%20Relay%20-%2007%2023&utm_term=07+2023), sendinblue smtp host is being updated to match sendinblue new name: Brevo.

**Comment by fabpot** [comment]
Closing as there are some PRs about this. We just need help to finish the work.
