### ISSUE TITLE
[HttpFoundation] Introducing a ParameterBag::match method

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#51224]
### Description

Hi 👋🏻 

This issue is created following a use case I'm facing where I need to test that a route parameter match a specific regex, I currently use something like this: 

```php
$parameter = $request->attributes->get(key: 'foo');

if (!preg_match(REGEX, $parameter,)) {
    return;
}
```

I'm wondering if `HttpFoundation` couldn't handle this check using a method like `match`: 

```php
public function match(string $key, string $regexp): bool
{
    return preg_match($regexp, $this->get($key)) > 0;
}
```

This way, we could refactor the code to: 

```php
if (!$request->atttributes->match(key: 'foo', regexp: 'REGEX') {
    return;
}
```

This is just sugar for developers but IMHO it can improve code comprehension and reduce the cases where a variable is created just to check its value, any thoughts?

Thanks 🙂

**Comment by xabbuh** [comment]
closing here as the related code PR has been rejected
