### ISSUE TITLE
[HttpKernel] #[MapQueryString] does not handle string and arrays properly, returning an empty / invalid dto

### ISSUE THREAD

**Issue by pedrocasado** [symfony/symfony#51235]
### Symfony version(s) affected

6.3

### Description

`RequestPayloadValueResolver` does not handle string and arrays properly, returning an empty / invalid dto even with all default values set.

```php
class SearchDTO
{
    public function __construct(
        #[Assert\All([
            new Assert\NotBlank(),
            new Assert\Length(max: 50),
        ])]
        public readonly array $brands = [],

        #[Assert\All([
            new Assert\NotBlank(),
            new Assert\Length(max: 50),
        ])]
        public readonly array $colors = [],
    ) {
    }
}
```
    

### How to reproduce

https://github.com/pedrocasado/dto
    $ composer install
    $ symfony serve

http://localhost:8000
http://localhost:8000/?brands[]=foo
http://localhost:8000/?brands=foo

DTO 

```php
class SearchDTO
{
    public function __construct(
        #[Assert\All([
            new Assert\NotBlank(),
            new Assert\Length(max: 50),
        ])]
        public readonly array $brands = [],

        #[Assert\All([
            new Assert\NotBlank(),
            new Assert\Length(max: 50),
        ])]
        public readonly array $colors = [],
    ) {
    }
}
```

Controller:

```php
#[Route(path: '/', name: 'homepage')]
public function homepage(
    #[MapQueryString] SearchDTO $searchDTO = new SearchDTO()
): Response {
    dd($searchDTO);
}
```

Requests:

GET / (Ok, brands properly empty)
```
 App\DTO\SearchDTO {#22310 ▼
  +brands: []
  +colors: []
}
```

GET /?brands[]=foo (Ok, brands properly set)
```
 App\DTO\SearchDTO {#1053 ▼
  +brands: array:1 [▼
    0 => "foo"
  ]
  +colors: []
}
```

GET /?brands=foo (Nok, SearchDTO empty, not even initialized. It does only work when passing "brands[]")
```
App\DTO\SearchDTO {#1053}
```

### Possible Solution

Am i missing the serializer context?

**Comment by HypeMC** [comment]
The problem is caused by the `RequestPayloadValueResolver` passing the `disable_type_enforcement` option to the `denormalize()` method. Without that option an exception is thrown.

https://github.com/symfony/symfony/blob/2f8af44c8137076d7d90f431b9ce966691125b79/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L42-L49

https://github.com/symfony/symfony/blob/2f8af44c8137076d7d90f431b9ce966691125b79/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L589-L595

**Comment by pedrocasado** [comment]
You are right. But looks like the concatenation `self::CONTEXT_DENORMALIZE + $attribute->serializationContext` is not working properly here. Im using PHP 8.1.18

https://github.com/symfony/symfony/blob/2f8af44c8137076d7d90f431b9ce966691125b79/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L164

Debug:

self::CONTEXT_DENORMALIZE = {array} [2]
 disable_type_enforcement = true
 collect_denormalization_errors = true

$attribute->serializationContext = {array} [1]
 disable_type_enforcement = false

**self::CONTEXT_DENORMALIZE + $attribute->serializationContext = {array} [2]**
 disable_type_enforcement = true
 collect_denormalization_errors = true

**array_merge(self::CONTEXT_DENORMALIZE, $attribute->serializationContext) = {array} [2]**
 disable_type_enforcement = false
 collect_denormalization_errors = true

Should it be fixed with array_merge?

Updated code

```
#[Route(path: '/', name: 'homepage')]
public function homepage(
    #[MapQueryString(
        serializationContext: ['disable_type_enforcement' => false]
    )] SearchDTO $searchDTO = new SearchDTO()
): Response {
    dd($searchDTO);
}
```

https://github.com/pedrocasado/dto

**Comment by HypeMC** [comment]
Not sure, I'm wondering why the `disable_type_enforcement` option was added in the first place.

**Comment by nicolas-grekas** [comment]
@Koc can you share your insights on this issue?

**Comment by stof** [comment]
to me, the issue is also that `RequestPayloadValueResolver::CONTEXT_DENORMALIZE` wins over the context configured for a specific argument using the attribute due to the order of the merging.
