### ISSUE TITLE
[Yaml] Since YAML spec 1.2.0, merge operator << has been removed

### ISSUE THREAD

**Issue by Korbeil** [symfony/symfony#51232]
### Description

Since YAML spec 1.2 (released in 2009) the merge operator `<<` was removed.
Should we remove it from Yaml component too since it doesn't exists anymore in the YAML spec ?

See https://yaml.org/spec/1.2.2/ext/changes/ for YAML specification changelog.
Highlight of the part that is linked to this issue:
![image](https://github.com/symfony/symfony/assets/944409/402a2573-3fc0-4d92-88c1-743e7f936820)

**Comment by lyrixx** [comment]
It's super useful. I prefer to keep this feature, even if it's not in the spec anymore

**Comment by nicolassing** [comment]
It's never a good solution to not follow a specification. It will always end up being a problem. Especially with interoperability.

**Comment by Seb33300** [comment]
Looks like this operator has been removed in favor of [anchors and aliases](https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases) in 1.2 spec.

The support for anchors and aliases should be introduced (if not already supported) before removing the << operator IMO.

**Comment by Korbeil** [comment]
@Seb33300 Anchors (keyword `&my-anchor`) and aliases (keyword `*my-anchor`) are already supported in Yaml component.

**Comment by wouterj** [comment]
The merge operator must be used together with aliases and anchors. It allows merging the aliased sequence into the current one.

I can't see any alternative proposed. What is now the correct way to achieve this?

Besides, interoperability in Yaml is almost a no-go anyway as there is no clear versioning of files, and each parser implements a different version.
If there is no alternative, I also believe we should keep this as this is becoming a more common pattern in Symfony together with our new `when@...` syntax.

**Comment by lyrixx** [comment]
And we also use custom tag (for PHP constant) 

> It's never a good solution to not follow a specification

I agree, but in this situation, we have diverged from the spec 14 years ago! So bad things should have already happened.

And we support more features, not less. I'm in favor of keeping it

**Comment by javiereguiluz** [comment]
As explained in https://symfony.com/doc/current/reference/formats/yaml.html:

> The Symfony Yaml Component implements a selected subset of features defined in the YAML 1.2 version specification.

The goal of the component was never to create a spec-compliant parser. We only provide the features needed to use YAML inside a Symfony app (to define config, services, etc.)

So, I'd say we should ignore this removal in the spec and just leave the feature in the component. Thanks.

**Comment by derrabus** [comment]
All right, I think we can close this issue, given that multiple core team members have already expressed that they would like to keep this feature.
