### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) + SCRAM-SHA-512(-PLUS) + SCRAM-SHA3-512(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [symfony/symfony#51292]
### Description

Dear @symfony team,

Can you add supports of :
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS
- SCRAM-SHA-512
- SCRAM-SHA-512-PLUS
- SCRAM-SHA3-512
- SCRAM-SHA3-512-PLUS

You can add too:
- SCRAM-SHA-224
- SCRAM-SHA-224-PLUS
- SCRAM-SHA-384
- SCRAM-SHA-384-PLUS

-------------------

SCRAM-SHA-1(-PLUS):
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677 since 2015-11-02
- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

SCRAM-SHA-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

SCRAM-SHA3-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

-PLUS variants:
- RFC5056: On the Use of Channel Bindings to Secure Channels: https://tools.ietf.org/html/rfc5056
- RFC5929: Channel Bindings for TLS: https://tools.ietf.org/html/rfc5929
- Channel-Binding Types: https://www.iana.org/assignments/channel-binding-types/channel-binding-types.xhtml
- RFC9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

IMAP:
- RFC9051: Internet Message Access Protocol (IMAP) - Version 4rev2: https://tools.ietf.org/html/rfc9051

LDAP:
- RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803

HTTP:
- RFC7804: Salted Challenge Response HTTP Authentication Mechanism: https://tools.ietf.org/html/rfc7804

2FA:
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa

IANA:
- Simple Authentication and Security Layer (SASL) Mechanisms: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

Linked to:
- https://github.com/scram-sasl/info/issues/1

Thanks in advance.

**Comment by derrabus** [comment]
> Can you add SCRAM-SHA-*(-PLUS)?

add it… to what exactly?

**Comment by Neustradamus** [comment]
@derrabus: SCRAM secure mechanisms :)

**Comment by chalasr** [comment]
Let me try to reformulate, which part of the Symfony codebase should get `SCRAM-SHA-*(-PLUS)?`  support? 
We need more insights. What purpose does it serve? In which case is it relevant? And why?

**Comment by Neustradamus** [comment]
@derrabus, @chalasr: SMTP, HTTP to be secure.

**Comment by wouterj** [comment]
Hi!

This issue as-is is not really actionable unfortunately, unless you're deep in the matter. In the current state, I'm afraid nobody will take action on this and it'll be closed in 6 months by our issue cleanup bot.

We would need more details on what exactly we need to do to add support and where. But honestly, what this mostly needs is someone that is motivated enough to make the changes and an actual use-case.

**Comment by Neustradamus** [comment]
Hope that it will be added, server starts to remove old and unsecure mechanisms after several years, 15 years!

20 November 2008: https://tools.ietf.org/html/draft-ietf-sasl-crammd5-to-historic-00
29 June 2017: https://tools.ietf.org/html/draft-zeilenga-luis140219-crammd5-to-historic-00
July 2011: RFC6331: Moving DIGEST-MD5 to Historic: https://tools.ietf.org/html/rfc6331

SCRAM-SHA-*-(PLUS) replaces old unsecure SCRAM-MD5, DIGEST-MD5 and CRAM-MD5.
PLAIN replaces LOGIN but it is not really secure.

**Comment by derrabus** [comment]
This person has opened the exact same issue on more than 180 repositories. Moreover, they fail to explain how their issue applies to Symfony (or any other repository they opened that issue for).

Closing as not actionable.

**Comment by Neustradamus** [comment]
@derrabus: Thanks to follow my improvement request for the security of emails and more :)

It is in RFCs, SCRAM replaces old and unsecure CRAM-MD5, DIGEST-MD5, SCRAM-MD5 since a long time which have been depreciated.

It has been added in last IMAP RFC "Internet Message Access Protocol (IMAP) - Version 4rev2".

All links have been added previously.

Already supported by a lot of products, a partial list is here:
- https://github.com/scram-sasl/info/issues/1

**Comment by stof** [comment]
Note that CRAM-MD5 is *not* moved to historic based on the resources you provided. You only referenced drafts, not an accepted RFC.
and just providing a link to a dozen of IETF RFCs does not constitute an actionable issue. It might allow someone to spend time producing an actionable one by reading all those RFCs and figuring out things.

**Comment by Neustradamus** [comment]
@symfony team, @derrabus, @chalasr, @wouterj, @stof: In PHP there is:
- https://github.com/pear/Auth_SASL/blob/master/Auth/SASL/SCRAM.php

**Comment by derrabus** [comment]
> In PHP there is:
> 
> - https://github.com/pear/Auth_SASL/blob/master/Auth/SASL/SCRAM.php

We don't maintain that repository.

**Comment by Neustradamus** [comment]
The request is to add SCRAM supports in Symfony.

**Comment by nicolas-grekas** [comment]
Symfony is open for PR. That's how OSS works.
I'm locking this issue as there is nothing more to add on our side.
Thanks for your understanding.
