### ISSUE TITLE
Remove historic CRAM-MD5 mechanism

### ISSUE THREAD

**Issue by Neustradamus** [symfony/symfony#51294]
### Symfony version(s) affected

*.*

### Description

Dear @symfony team,

Can you remove CRAM-MD5 from the code?
- https://github.com/search?q=repo%3Asymfony%2Fsymfony+cram-md5&type=code

It is unsecure:
- https://tools.ietf.org/html/draft-ietf-sasl-crammd5-to-historic-00
- https://tools.ietf.org/html/draft-zeilenga-luis140219-crammd5-to-historic-00

Thanks in advance.

### How to reproduce

https://github.com/search?q=repo%3Asymfony%2Fsymfony+cram-md5&type=code

### Possible Solution

Remove all about it.

**Comment by derrabus** [comment]
See #51292. Closing as not actionable.
