### ISSUE TITLE
[AssetMapper] Allow importmap_polyfill to be an AssetMapper path

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#51302]
### Description

Hi!

A user requested to be able to avoid using a CDN for the `importmap_polyfill`. This is configurable via `framework.asset_mapper.importmap_polyfill`. However, that path is not processed through AssetMapper, which is a bit awkward: you need to put it directly into your public directory.

Overall, it'd be nice to provide an easier path to using a local importmap polyfill.

Cheers!

**Comment by Chris53897** [comment]
Maybe serving it local should be the default for legal reasons due to GDPR?

**Comment by nicolas-grekas** [comment]
An idea to solve this: we drop the `importmap_polyfill` config option and instead, we define a recipe that adds the `script` tag that loads the polyfill to `base.html.twig`.

This script tag will need the URL of the polyfill. To resolve it, we make the `importmap()` helper accept an argument: the name of the imported JS package. When used this way, the function would return the URL of the package as listed in the `importmap.php`. This might be useful on its own to load anything that isn't supported by native importmap while still using the mapping provided by `importmap.php`.

Of course, we would list the polyfill in the default `importmap.php` via a recipe also.

After the recipe is applied, the base.html.twig file would contain:
```html
{% block javascripts %}
    <script async src="{{ importmap('es-module-shims') }}"></script>
    {{ importmap() }}
{% endblock %}
```

WDYT?

**Comment by nicolas-grekas** [comment]
Alternatively, we could possible make the `asset()` function able to return the URL of a package listed in `importmap.php`?

**Comment by weaverryan** [comment]
It's a bit odd to put `es-module-shims` IN `importmap.php` because it will never be needed/used as a module. But, it would work well - and you could use `importmap:require es-module-shims --download` to download this file locally like any other file. We add a `internal => true` or `in_map => false` option for this entry, if we wanted to avoid it being dumped in the importmap (for purity reasons).

If we did this, WDYT about keeping the `importmap_polyfill` option - but it would now either be a full URL (like today) *or* a string like `es-module-shims`, which we would look for and resolve from your `importmap.php` (or maybe we drop the ability to have a full URL and force you to define it in your importmap)

**Comment by nicolas-grekas** [comment]
> keeping the importmap_polyfill option

we could but I don't see the drawback of keeping only the importmap.php way (having only one way is a plus actually to me)

> odd to put es-module-shims IN importmap.php because it will never be needed/used as a module

let's break some mental barriers, this is just a map, with useful tooling to either reference a CDN or download :)

**Comment by nicolas-grekas** [comment]
@Chris53897 about GDPR you might want to check https://github.com/jsdelivr/jsdelivr/issues/18067 and https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net

**Comment by Chris53897** [comment]
@nicolas-grekas Sorry for late response. Thanks for the links.
The Shim is loaded from here. 
https://ga.jspm.io/npm:es-module-shims@1.7.2/dist/es-module-shims.js

Updated: That `ga` probably stands for google analytics (wrong) => gamma.
I could not find any infos on data privacy on that web page.
In my eyes this could lead to legal trouble.

**Comment by stof** [comment]
Based on https://jspm.org/cdn/jspm-io, I would say that `ga` stands for `gamma`:

> The `jspm.io` CDN is fully versioned. The current version is version _gamma_: `https://ga.jspm.io/`.

**Comment by Chris53897** [comment]
Thanks. I updated my comment.
