### ISSUE TITLE
Deprecate `require_previous_session` firewall option

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#51318]
### Description

Since Symfony 6.0 and the new Authentication system, the firewall option `require_previous_session` is no longer used in Symfony code base.

Last usages were removed by @wouterj in that PR: https://github.com/symfony/symfony/pull/41613

But that option is still available and no more documented.

**Comment by alamirault** [comment]
Hello,

I created #51332 and #51333 to deprecate and remove it
