### ISSUE TITLE
polyfill-php83 causing error on production after minor upgrade

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/symfony#51334]
### Symfony version(s) affected

6.3.3

### Description

After upgrade from 6.2 to 6.3.3, the `vendor/symfony/polyfill-php83` folder was not uploaded to the production server according to this error it was giving me there:

```
Warning: 
require(/home/html/..../public_html/www/vendor/composer/../symfony/polyfill-php83/bootstrap.php): 
Failed to open stream: 
No such file or directory in 
/home/html/.../public_html/www/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: 
Failed opening required '/home/html/.../public_html/www/vendor/composer/../symfony/polyfill-php83/bootstrap.php' (include_path='.:/usr/share/php') 
in
/home/html/.../public_html/www/vendor/composer/autoload_real.php:41 

Stack trace: 
#0 
/home/html/.../public_html/www/vendor/composer/autoload_real.php(45): {closure}('662a729f963d39a...', '/home/html/...')
#1 
/home/html/.../public_html/www/vendor/autoload.php(25): ComposerAutoloaderInit381fa10d8c3ab25cbf6e0c69f2f59c4d::getLoader() 
#2
/home/html/.../public_html/www/vendor/autoload_runtime.php(5): require_once('/home/html/...')
#3
/home/html/.../public_html/www/public/index.php(8): require_once('/home/html/...')
#4
{main} thrown in /home/html/.../public_html/www/vendor/composer/autoload_real.php on line 41
```

### How to reproduce

Set up your git to track the `vendor` folder and then perform a minor upgrade according to the official guide (from 6.2 to 6.3.3) and also update all recipes. Then deploy to the production server using git-ftp.

**Comment by DavidPetrasek** [comment]
I found the solution to the problem: 
My git tracks the vendor folder and git was ignoring `vendor/symfony/polyfill-php83` folder because it contains a .git subfolder so I had to manually copy the `vendor/symfony/polyfill-php83` to the production server. 

Edit:
This issue can be closed.
Seems like the best way is to ignore the vendor folder as recommended and then update by running commands directly on a production server or if your hosting provider do not let you run commands, then you have to copy the whole folder via FTP.

**Comment by derrabus** [comment]
… but it's also clearly not a Symfony bug which is why I'm closing the issue.

Maybe you can ask your question over at https://github.com/composer/composer/discussions.
