### ISSUE TITLE
[HttpClient] Uploading files causes the data collector to crash

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#51366]
### Symfony version(s) affected

≥ 6.3.0

### Description

When investigating https://github.com/symfony/symfony/discussions/51360 I found out the `HttpClientTrait::normalizeBody` checks if upload streams have ended when they are nested in `body` (cf. #49911).

In that case, the `HttpClientDataCollector` will trigger an exception because it will call `normalizeBody` again when all streams have been read (to generate the cURL command).

### How to reproduce

```php
$stream = fopen('filepath', 'r');

$httpClient->request('POST', '/endpoint', [
    'body' => ['stream' => $stream],
]);
```
will trigger a `TransportException` if the profiler is enabled.

### Possible Solution

The `HttpClientDataCollector` does not generate a cURL command when the body is a stream, so I guess it shouldn’t either in this case.

**Comment by rskuipers** [comment]
I'm running into this issue right now, but I'm unsure as to how I can work around this? If it's even possible to workaround this right now...

**Comment by AlexaneTrubert** [comment]
Have same issue, is there any solution ?
