### ISSUE TITLE
[Form] Maintain order of "preferred_choices" option

### ISSUE THREAD

**Issue by lopsided** [symfony/symfony#5136]
I have a registration form with a country select. Most of the users are from the UK, and then a way behind them are from Ireland. The rest of the world together are a very small proportion at the moment. Therefore I would like to put UK and Ireland at the top, as preferred choices:

``` php
    ->add('country', 'choice', array(
        'choices' => Locale::getDisplayCountries(\Locale::getDefault()),
        'preferred_choices' => array('GB', 'IE')
    ))
```

This works ok, BUT "Ireland" appears above "United Kingdom" in the separated, preferred options.

Is there any way to set the order of these so that UK appears top of the list?

**Comment by ronanguilloux** [comment]
:+1: @vmattila, your solution does the trick.

**Comment by ScreamZ** [comment]
Any news about that ?

**Comment by IMM0rtalis** [comment]
+1 for implementing a solution

**Comment by sampart** [comment]
Another workaround is to reorder the array passed to `choices` - the "extracted" choices retain their order from there.  Here's an example:

```
$countries = Intl::getRegionBundle()->getCountryNames();

// Force UK to be first, so that it is first in preferred choices
$countries = ['GB' => 'United Kingdom'] + $countries;

$builder->add('country', 'country', [
    'choices' => $countries,
    'preferred_choices' => ['GB', 'FR', 'DE', 'ES'],
]);
```

**Comment by althaus** [comment]
Same happens nowadays with `group_by` callbacks. :(

**Comment by benr77** [comment]
Based on @vmattila's Form Type solution, I've created a Form Type Extension which will automatically enable this behaviour for all ChoiceType fields, with a single configuration option.

https://gist.github.com/benr77/085fe0ccd2f72f10bb0ad331508e81df

Once enabled you just need to add `'preferred_choices_unsorted' => true` to your form type as required.

It also works for compound form fields, where the choice field is a sub-form of the field you are configuring (I needed to sort the "preferred_country_choices" in the MisdPhoneNumberBundle form type).

Hope someone finds this useful.

**Comment by jakzal** [comment]
@benr77 what do you think we should do with this issue though? Merge your implementation of an extension or implement it in the form type(s)? Or perhaps only document your approach?

**Comment by benr77** [comment]
This issue has been open since 2012 so I'm not confident that getting it merged is very likely. Getting it in to the documentation as an example is also potentially difficult depending upon whether people view this as an edge case or not. 

For me it's simple - you are given the option to supply `preferred_choices`, Symfony should not sort them alphabetically for you. If you need alphabetically sorted choices it's trivial to do the sort yourself before assigning the `preferred_choices` option.
