### ISSUE TITLE
[Workflow] Undeprecate `Registry::get`

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#51400]
### Description

Hi,

Our system relies heavily on getting a workflow from a object, aka `Registry::get()`

It was deprecated in #46000

But this seems to defeat dealing with many workflows that have a different support strategy, aka `framework.workflows.N.supports`, aka `WorkflowSupportStrategyInterface`

At this point im wondering what the alternative way is, or why `supports` configuration still exists?

**Comment by derrabus** [comment]
cc @lyrixx

**Comment by ro0NL** [comment]
note, im not recommending registry usage per se, but getting a workflow dynamicly was in fact a 1st class feature

**Comment by lyrixx** [comment]
@ro0NL what kind of implementation of `WorkflowSupportStrategyInterface` do you have?

Can you inject all services tagged `workflow` and pick the right one directly?

**Comment by ro0NL** [comment]
we use default `InstanceOfSupportStrategy` thru `supports: [classA, B]` in semantic config

i can resolve it in userland, but then i agree one needs #51227, or maybe leverage the service locator keys

however, it feels weird to let users deal with supports configuration, whereas `Registry::get`, did and can do it for us

IMHO, if we take this route, both `framework.workflows.N.supports` and `WorkflowSupportStrategyInterface` should be deprecated as well

overall i just dont think it's really worth it :sweat_smile:

**Comment by lyrixx** [comment]
> IMHO, if we take this route, both `framework.workflows.N.supports` and `WorkflowSupportStrategyInterface` should be deprecated as well

I would like to do that indeed. But twig need it. But we could simplify too.

Since there are many report about this deprecation, I'm really thinking about reverting it! 

But honestly, this is sub-optimal IMHO. There is no lazy loading :(

**Comment by ro0NL** [comment]
right, it seems `WorkflowExtension` needs the registry for the same reasons 

what about injecting the workflows as a service locator in the registry, and a 2nd locator with only the corrresponding `WorkflowSupportStrategyInterface`

**Comment by ro0NL** [comment]
happy to see deprecation dissappear, or crash :popcorn:

**Comment by lyrixx** [comment]
see https://github.com/symfony/symfony/pull/51976
