### ISSUE TITLE
[importmap] Wrong url for js modulepreload with site not at root of domain

### ISSUE THREAD

**Issue by Foudtz** [symfony/symfony#51417]
### Symfony version(s) affected

6.3.3

### Description

Hi !

I've try to put somes CSS and JS files with the AssetMapper.
I've just installed the package with composer, and files are updated with asset() and importmap(), great.

CSS Files are OK and work well
JS Files can't be used atm, the generated URL is wrong and don't get the root directory of my project.
I've tryied severals options but can't get a correct URL after compilation.
Tryied to change base_url of framework : the only url changed are CSS with asset()

Example : 
```
#App on http//myserver/SymfES/

#CSS File genertaed with asset()
<link rel="stylesheet" href="[/SymfES/assets/styles/app-713d9828d7058036a44786836080554c.css]">

#JS File generated with importmap()
<link rel="modulepreload" href="[/assets/app-bbae9f648af22c8bdc294ce35f4a1e4c.js]">
#Should be : 
<link rel="modulepreload" href="[/SymfES/assets/app-bbae9f648af22c8bdc294ce35f4a1e4c.js]">
```

Actually, my configuration files are from scratch with no modification.

asset_mapper.yaml
```
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
```

importmap.php
```
return [
    'app' => [
        'path' => 'app.js',
        'preload' => true,
    ],
];
```

Did I miss something ?

Thanks

### How to reproduce

Just install AssetMapper from documentation, with a fresh SF6 install : 
`composer require symfony/asset-mapper symfony/asset symfony/twig-pack`

Apache with Alias configuration : 
```
# /etc/httpd/conf.d/SymfES.conf
Alias /SymfES /var/www/SymfES/public

<Directory "/var/www/SymfES/public/">
  AllowOverride All
  order deny,allow
  Allow from all
</Directory>


Options +FollowSymlinks
```

**Comment by weaverryan** [comment]
Hey! 

Yep - this looks like a bug to me related to the site not living at the root of the domain. The `asset()` function is working fine (proven by the CSS files), but the `modulepreload` is apparently missing that.  Does your `<script type="importmap">` URLs look correct in the HTML source?

Cheers!

**Comment by Foudtz** [comment]
Hi !
Yeah looks like that

The importmap is wrong too : 

<html>
<body>


```
<script type="importmap">
{
    "imports": {
        "app": "/assets/app-bbae9f648af22c8bdc294ce35f4a1e4c.js"
    }
}
</script>
```
