### ISSUE TITLE
PSALM issue when extended Constraint

### ISSUE THREAD

**Issue by chou666** [symfony/symfony#51410]
### Symfony version(s) affected

6.3.3

### Description

After migration to version 6.3.3, I have some error with PSALM.

https://github.com/vimeo/psalm/issues/10118

The suggested answer is to add annotation on your side, Is it possible to add the annotation ?

### How to reproduce

https://psalm.dev/r/f2796a7ced

### Possible Solution

Add  annotation in src/Symfony/Component/Validator/Constraint.php:50 on ERROR_NAMES

`/** @var array<string, string> */`

**Comment by derrabus** [comment]
I guess we can do that. Send a PR.
