### ISSUE TITLE
AbstractPlatform::getSequenceNext ValSQL is not supported by platform

### ISSUE THREAD

**Issue by UtechtDustin** [symfony/symfony#51411]
### Symfony version(s) affected

6.3.0

### Description

We got the issue (We already got that quite often) that we can't save new entities and got the following error in the log file.

```
[2023-08-17T06:47:34.378069+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception: "Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNext
ValSQL' is not supported by platform." at /var/www/gda/V1.2/vendor/doctrine/dbal/src/Exception.php line 21 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0):
Operation 'Doctrine\\DBAL\\Platforms\\AbstractPlatform::getSequenceNextValSQL' is not supported by platform. at /var/www/gda/V1.2/vendor/doctrine/dbal/src/Exception.ph
p:21)"} []
```

In our Entities we use the generated Strategy from the maker bundle, which is the default value `AUTO`.
```
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;
```

Our database configuration looks like this:
```
DATABASE_URL="mysql://xxx:xxx@127.0.0.1:3306/gda?serverVersion=mariadb-10.11.3&charset=utf8mb4"
```
In the [documenation](https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration) is an hint that in newer versions we should move `mariadb` to the end so we also tried
```
DATABASE_URL="mysql://xxx:xxx@127.0.0.1:3306/gda?serverVersion=10.11.3-mariadb&charset=utf8mb4"
```

I don't understand why it tries to use the  `SEQUENCE` if we configured `mariadb/mysql` which should be `IDENTITY` by default as [documentated](https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/basic-mapping.html#identifier-generation-strategies).

### How to reproduce

I'm not sure, it randomly starts to use the other strategy.

### Additional Context

Just another question, the symfony documentations says we should use `mariadb-x.x.x` and in newer versions `x.x.x-mariadb`. But in the doctrine documentation it says we should use the result of `SELECT VERSION();` e.g. `10.6.12-MariaDB-0ubuntu0.22.04.1`. What is the correct version we should use or does both work ?
Documentation: https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html#mariadb

**Comment by UtechtDustin** [comment]
We got this issue 5 times in the last few day's (on production systems)!   
As workaround we defined the strategy so hopfully symfony will not try to guess it and throw the exception.

It seems this issue is quite "old" already. ref #8614.

**Comment by derrabus** [comment]
This does not look like a Symfony bug. Please ask for help at https://github.com/doctrine/orm/discussions
