### ISSUE TITLE
It doesn't go in catch

### ISSUE THREAD

**Issue by lbcd** [symfony/symfony#51421]
### Symfony version(s) affected

5.4

### Description

Try catch display a Symfony error and doesn't go in catch
 
![image](https://github.com/symfony/symfony/assets/1815136/6bab502a-fe6a-41f8-83de-315e89db6292)

### How to reproduce

Here is the complet method 
```

#[Route('/bordereaux/{id}', methods: ['PATCH'])]
    public function patchBordereau(int $id, Request $request) : Response
    {
        $isUpdated = false;
        $data = json_decode($request->getContent(), true);

        $bordereau = $this->bordereauEntityManager->getRepository(Bordereau::class)->findOneById($id);
        if(!$bordereau) {
            return new Response('Bordereau non trouvé.', 204);
        }

        // Todo: couche de sécurité pour vérifier si le user peut patcher l'objet

        foreach ($data as $property => $value) {
            $propertyGetter = 'get' . ucfirst($property);
            $propertySetter = 'set' . ucfirst($property);

            try {
                if ($bordereau->$propertyGetter() != $value) {
                    $bordereau->$propertySetter($value);
                    $isUpdated = true;
                }
            } catch (\Symfony\Component\ErrorHandler\Error\UndefinedMethodError $exception) {
                return new Response(
                    sprintf("La propriété %s n'est pas une propriété de l'objet bordereau. L'objet n'a pas été mis à jour.", $property),
                    500
                );
            }
        }

        if ($isUpdated) {
            $this->bordereauEntityManager->persist($bordereau);
            $this->bordereauEntityManager->flush();
        }

        return new Response(
            '',
          $isUpdated ?  200 : 304
        );
    }
```

### Possible Solution

I tried to replace UndefinedMethodError by  \Exception I get the same issue.

**Comment by lbcd** [comment]
I could bypass this issue using this:

```
try {
    if ($bordereau->$propertyGetter() != $value) {
        $bordereau->$propertySetter($value);
        $isUpdated = true;
    }
} catch (\error $error) {
    return new Response(
        sprintf("La propriété '%s' n'est pas une propriété de l'objet bordereau. L'objet n'a pas été mis à jour.", $property),
        500
    );
}
```

But it is not logical cause it is an "UndefinedMethodError" and should go in the catch using UndefinedMethodError type.

**Comment by xabbuh** [comment]
The `UndefinedMethodError` object is created later on when the PHP error is being handled by the Symfony error handler. But that happens outside your controller.

**Comment by wouterj** [comment]
This is an normal PHP error, which Symfony transfers to a specific type if your application code doesn't catch it. You have to handle it like any other PHP error in your application. I would recommend to check method existence before catching it (`method_exists($borderau, $propertyGetter)`).

If you need more help, I would suggest using one of our community support channels: https://symfony.com/support
