### ISSUE TITLE
make PasswordStrength extends able

### ISSUE THREAD

**Issue by g089h515r806** [symfony/symfony#51439]
### Description

I try to support it in Drupal contrib module "Field validation", Drupal core's has own plugin system of symfony constraint, to make symfony constraint works at Drupal, we need extend the constraint and add plugin system info.

I got fatal error:
Drupal\field_validation\Plugin\Validation\Constraint\PasswordStrengthConstraint cannot extend final class Symfony\Component\Validator\Constraints\PasswordStrength in E:\xampp\htdocs\drupal10\modules\field_validation\src\Plugin\Validation\Constraint\PasswordStrengthConstraint.php

Please remove "final", make it extends able.

**Comment by nicolas-grekas** [comment]
Please submit a PR so that we can discuss this there, it will be more efficient. Thanks!
Branch 6.4 since that'd be a new feature.

**Comment by derrabus** [comment]
Closing, see #51507 for discussion.
