### ISSUE TITLE
[RFC][Scheduler] Simplify schedule usage 

### ISSUE THREAD

**Issue by vtsykun** [symfony/symfony#51432]
### Description

Currently, it takes a lot of effort to create a scheduled task.
- define schedule provider
- create a message class
- create a messenger handler. 

These steps look too redundant, if you need to create a couple of simple tasks such as cleaning archive dir, check users, etc.

### Proposal

To simplify using of the scheduled tasks, proposed add `AsPeriodicTask` and `AsCronTask` attributes. They can be added as class or method attributes to any symfony service or console command.

Additionally, it is need to allow the merging of scheduled tasks obtained from schedule providers with the same name.

```php
#[AsPeriodicTask('1 day')]

#[AsCronTask('35,45,55 */3 * * *', jitter: 60, arguments: ['level' => '500mb'])]

#[AsCronTask('@random 3600', schedule: 'default')]
```

### Example

```php
<?php declare(strict_types=1);

namespace App\Service;

#[AsCronTask('*/5 * * * *')]
class SyncAppWorker
{
    public function __invoke(array $arguments = []): void
    {
        // code
    }
}
```

**Comment by OskarStark** [comment]
cc @kbond

**Comment by kbond** [comment]
I agree, this would be useful. On vacation but here's some quick thoughts on how this could work:
1. Some kind of `AggregateScheduleProvider` that aggregates all the service schedule configs
2. Generic `ServiceCallMessage` to be dispatched by messenger
3. `ServiceCallMessageHandler` that locates the correct service and executes it

**Comment by Seb33300** [comment]
I though the scheduler will help for instance to easily setup a cron job on a command (something similar to [Laravel Task Scheduling](https://laravel.com/docs/10.x/scheduling)) but I was disappointed by the complexity to configure it.

The current implementation force us to use it with the messenger component
 Can't we optionally skip that for a minimal usage?

**Comment by valtzu** [comment]
I tried implementing this based on @kbond's ideas and the original suggestion by @vtsykun. 

I don't feel like creating tests or docs so not submitting a PR at least right now.

The changes are available here https://github.com/symfony/symfony/commit/989907237e5b14085117c1ea0ebe2ff01b3430ac


```php

namespace App;

use Psr\Log\LoggerInterface;
use Symfony\Component\Scheduler\Attribute\AsCronTask;
use Symfony\Component\Scheduler\Attribute\AsPeriodicTask;

class BusinessLogic
{
    public function __construct(private readonly LoggerInterface $logger)
    {
    }

    #[AsCronTask(expression: '* * * * *', arguments: ['Hello from cron trigger'])]
    #[AsPeriodicTask(frequency: 5, jitter: 1, arguments: ['Hello from periodic trigger'])]
    public function scheduledLog(string $message): void
    {
        $this->logger->alert("[{date}] $message\n", ['date' => new \DateTime()]);
    }
}
```

_(:point_up: no any extra config required)_

Then running `bin/console messenger:consume scheduler_default`

```
                                                                                                                       
 [OK] Consuming messages from transport "scheduler_default".                                                            
                                                                                                                       

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

 // Re-run the command with a -vv option to see logs about consumed messages.                                           

[alert] [2023-08-30T23:38:22+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:28+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:32+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:38+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:42+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:48+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:53+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:38:57+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:39:00+03:00] Hello from cron trigger
[alert] [2023-08-30T23:39:02+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:39:08+03:00] Hello from periodic trigger
[alert] [2023-08-30T23:39:13+03:00] Hello from periodic trigger
```

**Comment by fabpot** [comment]
@valtzu Even if you don't create tests or docs, can you still submit a PR? Someone will then take over to finish it and you will still get credits for your contribution.
