### ISSUE TITLE
Change private function isCorrectChecksum to "protected function isCorrectChecksum"

### ISSUE THREAD

**Issue by g089h515r806** [symfony/symfony#51440]
### Description

IsinValidator use following code in isCorrectChecksum function :

return 0 === $this->context->getValidator()->validate($number, new Luhn())->count();

it get fatal error, the reason is drupal has own typed data validator  base on symfony validator.  
Drupal use:
core\lib\Drupal\Core\TypedData\Validation\RecursiveContextualValidator

Instead of symfony's.

at here  $number is not a typed data. It throw a fatal exception.

I have to override isCorrectChecksum function, but it is private. it will be better to change it to protected, then i do not need to copy all code from IsinValidator.

**Comment by stof** [comment]
Do you mean that you replace the `validate` method entirely while wanting to reuse the private method ?

**Comment by stof** [comment]
or do you mean that Drupal's validator supports validating only TypedData objects and not scalars ? In that case, I suggest fixing that in Drupal instead of doing weird hacks forcing use to add extension points in every place calling a validator recursively.

**Comment by derrabus** [comment]
Can you please open a bug in Drupal's tracker?

**Comment by g089h515r806** [comment]
I report this issue to Drupal core also. Drupal's entity system and field system build on TypedData system, it is a little different from symfony.

I copy the whole code of IsinValidator to Drupal, and change the logic of isCorrectChecksum to make it works at Drupal.

**Comment by g089h515r806** [comment]
I know this is not a bug of symfony, this is also not a bug of Drupal core.
That is why I open a feature request.

**Comment by derrabus** [comment]
> I report this issue to Drupal core also.

Got a link for us?

**Comment by stof** [comment]
If Drupal replaces the RecursiveContextualValidator of Symfony by making accept _only_ TypedData instead of `mixed`, I would say this is a bug in Drupal as they extend a class without respecting the Liskov Substitution Principle.

**Comment by xabbuh** [comment]
I agree with @stof. Closing therefore, thank you for understanding.
