### ISSUE TITLE
Compatibility with php-amqp 2.0

### ISSUE THREAD

**Issue by stepozer** [symfony/symfony#51451]
### Symfony version(s) affected

6.3.0

### Description

My production was updated from php-amqp 1.11.0 to 2.0 and I get this error:

```
Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::nack(): Return value must be of type bool, null returned
```

As I can see from this commit methods ack and nack right now return void:

https://github.com/php-amqp/php-amqp/commit/6c98bf1a15dae87a709a38b59f5693c6d88f77aa

So this code in vendor/symfony/amqp-messenger/Transport/Connection.php should be changed into:

```
    public function ack(\AMQPEnvelope $message, string $queueName): void
    {
        $this->queue($queueName)->ack($message->getDeliveryTag());
    }

    public function nack(\AMQPEnvelope $message, string $queueName, int $flags = \AMQP_NOPARAM): void
    {
        $this->queue($queueName)->nack($message->getDeliveryTag(), $flags);
    }
 ```

### How to reproduce

Try to use php-amqp 2.0 extension

**Comment by lyrixx** [comment]
Duplicates of https://github.com/symfony/symfony/pull/51168

This will be fixed in the next release at the end of th month
