### ISSUE TITLE
Undefined constant "STDOUT" using Process and setTty

### ISSUE THREAD

**Issue by Adi-18** [symfony/symfony#51452]
### Symfony version(s) affected

6.2.11

### Description

Running on Debian 10 and PHP 8.1.

Code
```
            $process = new Process(['ping', '-c 20', 'www.google.com']);
            $process->setTty(true);

```
as described here: https://symfony.com/doc/current/components/process.html
Maybe description is outdated?

### How to reproduce

Create new Syfony project and follow description.

**Comment by wouterj** [comment]
This constant is defined by PHP when run from the CLI. This error indicates to me that you're trying to run this code in another context (e.g. from an HTTP request). In this context, using the TTY mode does not make sense. From the docs: "In TTY mode, you connect the input and output of the process to the input and output of your program"

If you have more questions, please try one of our community support channels: https://symfony.com/support
