### ISSUE TITLE
[Messenger] AMQP v2.0.0: ack() must be of the type bool, null returned

### ISSUE THREAD

**Issue by khal3d** [symfony/symfony#51460]
### Symfony version(s) affected

4.4.50

### Description

After the recent release of AMQP v2.0.0 on the 20th of Aug, 2023 (2 days ago), our app stopped working due to the following error:

```
Return value of Symfony\Component\Messenger\Transport\AmqpExt\Connection::ack() must be of the type bool, null returned
```

### Steps to reproduce:

- Install Symfony Messenger 4.4.50.
- Upgrade the AMQP transport to v2.0.0.
- Try to acknowledge a message.

### Expected behavior:

The `ack()` method of the `Symfony\Component\Messenger\Transport\AmqpExt\Connection` class should return a boolean value.

### Actual behavior:

The `ack()` method is returning null.

### Possible Solution

Downgrade to AMQP version 1.11.0
```
pecl install amqp-1.11.0
```

**Comment by GromNaN** [comment]
Duplicates of https://github.com/symfony/symfony/pull/51168

This will be fixed in the next release at the end of the month.

Note that [Symfony 4.4 will not be fixed](https://symfony.com/releases/4.4).
