### ISSUE TITLE
[VarExporter] Deconstructor/Dismantler/Disassembler class

### ISSUE THREAD

**Issue by priyadi** [symfony/symfony#51472]
### Description

Basically, the reverse of `Instantiator::instantiate()`. It takes an object, and outputs properties and scoped properties suitable as the input for `Instantiator::instantiate()`. Or, similar to `VarExporter::export()` but instead of returning PHP code, it would return an array data structure.

The idea is that we can use it together with `Instantiator::instantiate()` as a replacement for `serialize()`/`unserialize()`, but with more manageable underlying data for long-term storage (easier to migrate, etc.).

**Comment by ro0NL** [comment]
Duplicate https://github.com/symfony/symfony/issues/44724#issue-1084656641?

Using a serializer worked well for us

**Comment by priyadi** [comment]
> Using a serializer worked well for us

Actually, my intention is to use it as a backend for a normalizer. As far as I can tell, a normalizer for that purpose is yet to be written.

PropertyNormalizer can read private properties, but cannot distinguish private properties with the same name that belong to a different class in the hierarchy. Also, it does not bypass the constructor when building the object back.

I currently use `serialize()` if I need to store objects in a database field. But it is painful dealing with class renames and changes. If only there was something like `serialize()` but with a more manageable output.

[doctrine-json-odm](https://github.com/dunglas/doctrine-json-odm) works well, but by default, it uses ObjectNormalizer which works with getters and setters. That means we are mostly limited to plain getters and setters, and cannot have complex business logic in the methods. For this purpose, we want the serializer to work directly with the objects' properties, just like Doctrine.

I was about to write such a normalizer, but VarExporter does a lot of nice things like __serialize/__unserialize handling, ArrayIterator/ArrayObject handling, etc.

**Comment by ro0NL** [comment]
got ya, leveraging `VarExporter::export` for eg. `RawObjectNormalizer` sounds noble :+1:

**Comment by nicolas-grekas** [comment]
What you're asking for is in the `VarDumper` component: the `VarCloner::cloneVar()` method produces an array (wrapped in a `Data` class) that is an exact snapshot of the original one. Then, you could write a dumper that rebuilds the object from this description using whatever logic in there.

**Comment by nicolas-grekas** [comment]
Closing per my previous comment. Let us know if this is not covering what you want.
