### ISSUE TITLE
[Console] Unable to use suggestedValues with named arguments

### ISSUE THREAD

**Issue by arokettu** [symfony/symfony#51481]
### Symfony version(s) affected

6.1.0 and later

### Description

Unable to use suggestedValues in addOption and addArgument when using named params

### How to reproduce

```php
protected function configure(): void
{
    $this->addOption(
        name: 'letters',
        mode: InputOption::VALUE_REQUIRED,
        suggestedValues: ['a', 'b', 'c'],
    ); // Uncaught Error: Unknown named parameter $suggestedValues
}
```

### Possible Solution

Uncomment `/* array|\Closure $suggestedValues = [] */`

### Additional Context

What is the reason this param is discovered with func_num_args() instead of a proper declaration?

**Comment by wouterj** [comment]
This is expected. The parameter was introduced in a minor version in the 6.x series. Adding a parameter is a backwards compatibility break for classes overriding the method, which is not allowed in our minor releases.
In Symfony 7.0, we can transform the comment to a real definition if I'm correct.

**Comment by GromNaN** [comment]
It's been updated for 7.0 https://github.com/symfony/symfony/commit/7e81c9144a26fb4d0e2c2ab4fdd511163581c000#diff-af3c198cbbaa2b1b7075232bd660a286f94dafa023c362d0e67315369554c38fR446

**Comment by arokettu** [comment]
@wouterj Thanks for the explanation
