### ISSUE TITLE
[WebProfilerBundle] Add `target="_blank"` to the WebProfiler toolbar

### ISSUE THREAD

**Issue by MirakuSan** [symfony/symfony#51504]
### Description

Hello everyone,

I always asked myself why the web profiler was not opening in a new tab when clicking one of the link : 
![image](https://github.com/symfony/symfony/assets/80831148/806c6d50-eb20-4b00-a7b4-831303dbeb4e)

Si I would like to propose to add the `target="_blank"` attribute in the `<a>` tag.
I can do the feature myself.

I hope this as not be answer already, I did not find anything.

Thanks for reading this.

### Example

I think we should just have to modify `toolbar_item.html.twig` :

```diff
<div class="sf-toolbar-block sf-toolbar-block-{{ name }} sf-toolbar-status-{{ status|default('normal') }} {{ additional_classes|default('') }}" {{ block_attrs|default('')|raw }}>
-    {% if link is not defined or link %}<a href="{{ url('_profiler', { token: token, panel: name }) }}">{% endif %}
+    {% if link is not defined or link %}<a href="{{ url('_profiler', { token: token, panel: name }) }}" target="_blank">{% endif %}
        <div class="sf-toolbar-icon">{{ icon|default('') }}</div>
    {% if link|default(false) %}</a>{% endif %}
        <div class="sf-toolbar-info">{{ text|default('') }}</div>
</div>
```

**Comment by stof** [comment]
`target="_blank"` forces to open a new tab, while the default gives the choice to the user. So I would keep the existing behavior.
