### ISSUE TITLE
Suggestion for the Exception Rendering

### ISSUE THREAD

**Issue by schmittjoh** [symfony/symfony#5151]
Currently, while rendering the stack trace simply the first entry is displayed open on initial load.

Instead of this, I propose to open the first entry which originates not from within the exception class, or a sub-class of it. The reasoning behind this is simply not to show any "auxiliar" constructor code which just calls back into the regular constructor, but the actual place where the exception is created.

**Comment by fabpot** [comment]
This looks like a good idea (and we will need some good heuristic), but I don't think this is worth it. A human is going to be really fast in spotting his class name amongst the one in the stack trace. Indeed, nobody else ever asked for that. So, given that nobody ever worked on an implementation, I'm in favor of closing this one.
