### ISSUE TITLE
[HttpClient] `Psr18Client` can't get custom HTTP status messages

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony#51527]
### Symfony version(s) affected

5,4, 6.4

### Description

for example if some API i want to connect uses HTTP Status Codes like this:

```
HTTP/1.1 404 countryCodeNotFound
```

then when using Symfony HttpClient as its own Client, then the Exception sets the Message correct

but the Psr18Client doesn't parse the `response_headers` like the Exceptions do
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpClient/Exception/HttpExceptionTrait.php#L34

the Psr18Client sets the status code without trying to set the message too:
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpClient/Psr18Client.php#L108

### How to reproduce

have an API with custom status messages:

```
HTTP/1.1 404 countryCodeNotFound
```

### Possible Solution

Similar code that is done in the Exception Trait should also be done in the Psr18Client

**Comment by nicolas-grekas** [comment]
The HTTP status text is a thing of the past, HTTP/2 doesn't support it. I'd recommend not relying on this.

**Comment by Hanmac** [comment]
> The HTTP status text is a thing of the past, HTTP/2 doesn't support it. I'd recommend not relying on this.

and Symfony Client still supports that.

the problem its that this one API doesn't have a meaningful body to be parsed on exceptions.
so i can't parse the body myself.

**Comment by nicolas-grekas** [comment]
Up for sending a PR?

**Comment by Hanmac** [comment]
i will try to make a fix for Psr18Client next week

**Comment by nicolas-grekas** [comment]
Don't forget about this one @Hanmac ;

**Comment by Hanmac** [comment]
yeah! thanks for reminding me, i probably can work on this the next days
