### ISSUE TITLE
[DependencyInjection] Unable to override EnvPlaceholderParameterBag

### ISSUE THREAD

**Issue by kira0269** [symfony/symfony#51526]
### Symfony version(s) affected

6.*

### Description

Hello Symfony mates!

For a project with a custom way to inject environment variables, I need to customize the way I retrieve my env vars.
Instead of having dotenv files, we have some properties files on the servers. We use an other tool to manage and deploy these files on the servers.

In Symfony, we can use env(MY_ENV_VAR) to fetch vars from .env. On a php project, we added the Dependency Injection component (in a standalone usage). So I created a new EnvPlaceholderParameterBag (lets say CustomEnvPlaceholderParameterBag) and configured the container to use it. This CustomEnvPlaceholderParameterBag will load vars by parsing the properties files. It works like a charm.

But now, I try to use the same logic on a full Symfony app, and it didn't work. After analysis, I found that the EnvPlaceholderParameterBag used is not mine, neither the default one, but a MergeExtensionConfigurationParameterBag (which extends EnvPlaceholderParameterBag. This class is marked as internal and it looks like it is used for extensions loading.

Is this some unexpected behavior, or is it a bad idea to put a custom EnvPlaceholderResolver like I did?

Thanks a lot for your help!

### How to reproduce

There is how to modifiy the Kernel to customize the EnvPlaceholderResolver in the container.
```php
// src/Kernel.php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function getContainerBuilder(): ContainerBuilder
    {
        // I had to copy the content from the parent's method.
        // Then adapt the creation of the container.
        $customResolver = new CustomEnvPlaceholderResolver();
        $container = new ContainerBuilder($customResolver);
        $customResolver->setContainer($container);

        // The following lines are copied from parent::getContainerBuilder()
        $container->getParameterBag()->add($this->getKernelParameters());

        if ($this instanceof ExtensionInterface) {
            $container->registerExtension($this);
        }
        if ($this instanceof CompilerPassInterface) {
            $container->addCompilerPass($this, PassConfig::TYPE_BEFORE_OPTIMIZATION, -10000);
        }

        return $container;
    }
}
```

And my CustomEnvPlaceholderResolver
```php
// src/Config/CustomEnvPlaceholderResolver
namespace App\Config;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag;

class CustomEnvPlaceholderResolver extends EnvPlaceholderParameterBag implements ContainerAwareInterface
{
    private ContainerInterface $container;

    /**
     * This method load some vars using a CustomEnvLoader service when 'custom_env(var)' is found in config
     */
    public function get(string $name): array|bool|string|int|float|\UnitEnum|null
    {
        if (str_starts_with($name, 'custom_env(') && str_ends_with($name, ')') && 'custom_env()' !== $name) {
            [$resource, $key] = explode(',', substr($name, strlen('custom_env('), -1));

            if (is_null($resource) || is_null($key)) {
                throw new \Exception("Parsing custom_env with '$name' failed ! It does not respect the format %custom_env(resource_name,key)%");
            }

            return $this->container->get(CustomEnvLoader::class)->readKey($resource, $key);
        }

        return parent::get($name);
    }

    public function setContainer(?ContainerInterface $container): void
    {
        $this->container = $container;
    }
}
```

**Comment by ro0NL** [comment]
> customize the way I retrieve my env vars

IIUC it can be done using custom `EnvVarLoaderInterface` implementation

**Comment by kira0269** [comment]
> > customize the way I retrieve my env vars
> 
> IIUC it can be done using custom `EnvVarLoaderInterface` implementation

Thanks a lot !!

The first solution I found was to create env parameters in a `services.php` and force the Kernel to load both `services.yaml` and `services.php` by overriding the `configureContainer()` method from the `MicroKernelTrait`.

The documentation (Symfony and DI component) don't talk about the `EnvVarLoaderInterface`, only `EnvVarProcessorInterface`. Maybe it should be added ^^

Again, thank you for your help!

**Comment by kira0269** [comment]
> > customize the way I retrieve my env vars
> 
> IIUC it can be done using custom `EnvVarLoaderInterface` implementation

I tried your solution, but it seems like my new CustomEnvVarLoader is not taken in count.

There is my class:
```php
<?php

namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\EnvVarLoaderInterface;

class CustomEnvVarLoader implements EnvVarLoaderInterface
{
    public function __construct()
    {
    }

    public function loadEnvVars(): array
    {
        return ['MY_VAR' => 'test'];
    }
    
    //...
}
```

**Comment by kira0269** [comment]
My bad: I had the "default" configuration in my services.yaml, which exclude all classes in DependencyInjection folder to be loaded as services ^^

I solved that.
