### ISSUE TITLE
[Serializer] MaxDepth not working, despite copying and pasting the doc.

### ISSUE THREAD

**Issue by N445** [symfony/symfony#51531]
### Symfony version(s) affected

6.3.4

### Description

The max depth option not working, despite copying and pasting the doc.

https://symfony.com/doc/current/components/serializer.html#handling-serialization-depth

### How to reproduce

Make the same code as the document, and see the result

```php
<?php

namespace App\Model;

use Symfony\Component\Serializer\Annotation\MaxDepth;

class MyObj
{
    public string $foo;

    /**
     * @var self
     */
    #[MaxDepth(2)]
    public MyObj $child;
}
```

```php
     $level1      = new MyObj();
        $level1->foo = 'level1';

        $level2        = new MyObj();
        $level2->foo   = 'level2';
        $level1->child = $level2;

        $level3        = new MyObj();
        $level3->foo   = 'level3';
        $level2->child = $level3;

        $encoders    = [new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];

        $serializer = new Serializer($normalizers, $encoders);


        $result = $serializer->normalize($level1, null, [AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true]);
        dump($result);
```

expected result

```
$result = [
    'foo' => 'level1',
    'child' => [
        'foo' => 'level2',
        'child' => [
            'child' => null,
        ],
    ],
];
```

```
array:2 [▼
  "foo" => "level1"
  "child" => array:2 [▼
    "foo" => "level2"
    "child" => array:1 [▼
      "foo" => "level3"
    ]
  ]
]
```

**Comment by mtarld** [comment]
Hey @N445, thanks for the issue.

First, to make `MaxDepth` (and any other attribute) to work, you'll need to inject a `ClassMetadataFactory` in the `ObjectNormalizer` like so:
```php
$level1 = new Foo();
$level1->foo = 'level1';

$level2 = new Foo();
$level2->foo = 'level2';
$level1->child = $level2;

$level3 = new Foo();
$level3->foo = 'level3';
$level2->child = $level3;

$serializer = new Serializer([new ObjectNormalizer(new ClassMetadataFactory(new AnnotationLoader()))], []);

dump($serializer->normalize($level1, null, [AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true]));
```

Then, seems like there is a tiny issue in the documentation which is misleading. Indeed, a `MaxDepth` of `2` must result as:
```
^ array:2 [
  "foo" => "level1"
  "child" => array:2 [
    "foo" => "level2"
    "child" => array:1 [
      "foo" => "level3"
    ]
  ]
]
```

(note that the level 3 `foo` string is present, and the level 3 child is not `null` as it doesn't exist at all)

**Comment by stof** [comment]
Well, your object `$level1` is not inside the property that has the `MaxDepth` attribute. Inside the `child` key (where the MaxDepth is applied), you indeed only have at most a depth of 2 (`level2` being at a depth of 1 and `level3` at a depth of 2)

**Comment by N445** [comment]
Yes ! you right both of you ! thanks you 

with this line  `$serializer = new Serializer([new ObjectNormalizer(new ClassMetadataFactory(new AnnotationLoader()))], []);`  it's working good 

and change the `#[MaxDepth(2)]` to `#[MaxDepth(1)]` 

thank you
