### ISSUE TITLE
[Messenger] allow to decouple DelayStamp from system time

### ISSUE THREAD

**Issue by aegypius** [symfony/symfony#51557]
### Description

`DelayStamp` class uses builtin `time()` function in its `delayFor` and `delayUntil` method, is there any way to 
use `symfony\clock`  `now()` function ?

Are you willing to accept a pull-request for that ?

**Comment by stof** [comment]
I don't think this would work well. Most transports are using the timestamp to feed it to the message broker, which will still use its system time to process it and not the symfony clock.

**Comment by aegypius** [comment]
I understand the argument, maybe there is another way to achieve what I am trying to do. 

I try to write an integration test that heavily rely on calendar planing, unit tests passes because I can tweak data to "simulate"  the behavior but integration tests are based on real world data and I fail to find a way to complete my workflow and I am relunctant to duplicate the entire DelayStamp system to achieve that. 

Do you have any pointer ?

**Comment by stof** [comment]
The InMemoryTransport supports replacing its clock. If you use an in-memory transport with a MockClock, you will be able to make the clock sleep (which will move it forward without any waiting) after you send you message, to simulate being after the delay has elapsed.

**Comment by aegypius** [comment]
Thanks ! I will give it a try !
