### ISSUE TITLE
[DependencyInjection] Target parameter attribute does not work for Services

### ISSUE THREAD

**Issue by issamkhadiri1989** [symfony/symfony#51565]
### Symfony version(s) affected

6.3

### Description

Hello,

I am having  an issue with the `#[Target]` attribute when using it in services. 

According to https://symfony.com/doc/current/service_container/autowiring.html#dealing-with-multiple-implementations-of-the-same-type,

when I have 2 services implementing the same interface i have 2 choices:

- create an alias  from the Interface and use a default service and create a named alias for the other services

- use the Target attribute.

With the first choice, everything works fine. But with the 2nd choice, I have created a default alias from the interface, then I create another alias to the other service. When I use the alias in some service I got  an error 

`Cannot resolve argument $client of "App\Controller\TwitterController::index()": Cannot autowire service "App\Service\TwitterClient": "#[Target('appTransformerUpper')" on argument "$transformer" of method "__construct()"`

Am I doing something wrong ? 

### How to reproduce

1.  Create an interface 

```
interface TransformerInterface
{
    public function transform(string $input): string;
}
```

2. Create 2 services that implement the same interface 

```
class UppercaseTransformer implements TransformerInterface
{
    public function transform(string $input): string
    {
        return \strtoupper($input);
    }
}
```

```
class Rot13Transformer implements TransformerInterface
{
    public function transform(string $input): string
    {
        return \str_rot13($input);
    }
}
```

3. Create an alias from the interface in services.yaml

```
App\Utils\TransformerInterface: '@App\Utils\Transformer\Rot13Transformer'
```

And then, create another alias to the other service  (cf the doc)

```
app.transformer.upper: '@App\Utils\Transformer\UppercaseTransformer'
```

Use the Interface as a Type-hint in some service (eg.  TwitterClient service) like the following

```
use Symfony\Component\DependencyInjection\Attribute\Target;

class TwitterClient
{
    private TransformerInterface $transformer;

    public function __construct(
        #[Target('app.transformer.upper')]
        TransformerInterface $transformer
    ) {
        $this->transformer = $transformer;
    }
 ...
}
```

**Comment by HypeMC** [comment]
The `#[Target]` attribute doesn't work with service aliases, use the `#[Autowire]` attribute instead. See #50541.

**Comment by xabbuh** [comment]
closing as explained

**Comment by issamkhadiri1989** [comment]
Thank you @HypeMC 

It works  ! 

I added a `App\Utils\TransformerInterface $upperTransformer: '@App\Utils\Transformer\UppercaseTransformer'` and then used `#[Target('upperTransformer')]`.

However I should mention that in the doc, the statement

```
Another possibility is to use the #[Target] attribute. By using this attribute on the argument you want to autowire, you can define exactly which service to inject by using its alias.
```

could be confusing as there is no example explaining the idea. 

Thank you again for the explanation 

Best regards !

**Comment by stof** [comment]
the Target attribute works with named aliases, allowing to keep the argument name itself whather you want (so not always matching your named alias)

**Comment by eerison** [comment]
> Thank you @HypeMC
> 
> It works !
> 
> I added a `App\Utils\TransformerInterface $upperTransformer: '@App\Utils\Transformer\UppercaseTransformer'` and then used `#[Target('upperTransformer')]`.
> 
> However I should mention that in the doc, the statement
> 
> ```
> Another possibility is to use the #[Target] attribute. By using this attribute on the argument you want to autowire, you can define exactly which service to inject by using its alias.
> ```
> 
> could be confusing as there is no example explaining the idea.
> 
> Thank you again for the explanation
> 
> Best regards !

did you add this in your bind configs?

I do not know why the servers are not found in binds :/

**Comment by issamkhadiri1989** [comment]
Hi @eerison 

No i didn't have to add any bind config. You need to have a named alias and then you can report the name as Target's argument
