### ISSUE TITLE
Incorrect form input validation when using a data class with non-nullable properties

### ISSUE THREAD

**Issue by janklan** [symfony/symfony#51571]
### Symfony version(s) affected

6.x, possibly earlier

### Description

When using a form with a data class containing non-nullable properties, the form submission can fail when an empty value is submitted in a field that is not nullable, **if the corresponding property has been initialised**.

### How to reproduce

1. Check out https://github.com/janklan/symfony-bug-51571
2. Run it
3. Submit the form. You'll see it's working, and the first field shows a validation error
4. Now erase the value from the second field and submit again; you'll trip the problem

![2023-09-06 10 00 11](https://github.com/symfony/symfony/assets/5463371/15ed539d-6529-41a4-a88e-9b5de80d15a4)

### Additional Context

I think the problem is not in PropertyAccessor, but somewhere in the form. The reason I say so is because the following code throws the exception in both cases:

```php
$obj = new DataClass();
$accessor = new PropertyAccessor();
$accessor->setValue($obj, 'uninitialisedInteger', null);
$accessor->setValue($obj, 'integer', null);
```

This suggests the Form component is somehow aware of whether the value in the data class has been initialised or not, and is not even trying to set it if (1) it was not yet initialised and (2) the input field produces an empty. 

If the property **has** been initialised before and is about to be set empty, the Form component attempts to set the value **before** validation, coercing the PropertyAccessor into throwing this error.

**Comment by Seb33300** [comment]
Is your setter looking like:
```php
public function setInteger(int $integer)
```

If yes, you need to replace it by:
```php
public function setInteger(?int $integer)
```

**Comment by janklan** [comment]
There is no setter. See the reproducer for full detail.

**Comment by Seb33300** [comment]
Oh yes, sorry, didn't notice you shared the link to your code.

Your class properties doesn't accept null.
You need to allow them to be nullable with `?int`:

```php
class DataClass {
    #[Assert\NotBlank]
    public ?int $uninitialisedInteger;

    #[Assert\NotBlank]
    public ?int $integer = 1;
}
```

**Comment by janklan** [comment]
You're technically correct, but I say making the property nullable is a workaround for a behaviour that shouldn't exist. 

The data model declares validation constraints signalling to the Form component the value must not be null/empty.

The form component ignores this constraint and attempts to set a null value and only after that it attempts to run the validation (which would have correctly failed, but we don't get to that point now)

The behaviour is inconsistent between the declared/undeclared property: Undeclared not-nullable property behaves as expected, the form reports validation errors instead of attempting to set null. 

In contrast, when working with a declared nullable property, we get an InvalidArgumentExpection instead of a graceful validation error, which is the basis for this bug report.

--

If you work with the data class somewhere else and can't rely on the fact that the value is declared and not null, you always have to check the value to confirm it's not a null.

That's potentially a lot of code that wouldn't have to exist if you could depend on existing language-level not-nullable status.

**Comment by Seb33300** [comment]
I think you are misunderstanding the purpose of the Validator component.

> The Validator component provides tools to validate values
https://symfony.com/doc/current/components/validator.html

It doesn't prevent assigning invalid values.
It is just taking "a value" and validate it based on defined constraints.

So when using with the form component,  the form will assign the values submitted, and then, validate it.

**Comment by janklan** [comment]
Why does the validator&form work correctly (according to me) if the value has **not** previously been initialised?

Even if you submit an empty value and the property is not nullable, the form shows a validation error as expected.

**Comment by janklan** [comment]
I tried to add another use case to demonstrate a more realistic scenario in which making the property nullable makes no sense. In this case, I'm working with a property that is not nullable and must always exist: the `userIdentifier` needed by `UserInterface` (and the underlying database). 

Whether or not someone would want to submit an empty value in this scenario is irrelevant. The point is we get an exception when we clear a pre-existing value, instead of a form validation error. If we try to set an empty value for the first time, things work well.


Check it out in another branch: https://github.com/janklan/symfony-bug-51571/tree/another-example - I didn't want to make the most basic reproducer in the main branch more complex, hence the two different (albeit similar) versions. 

You'll see something like this:

![2023-09-06 15 15 25](https://github.com/symfony/symfony/assets/5463371/02f886a6-70ee-4a5d-9d61-4264d6501527)

--

Don't get me wrong, I know there are things that could be done to work around this - nullable properties, setters that ignore the null value, and possibly some other things. I'm not saying they won't work. I'm arguing that having to do them is wrong.

**Comment by xabbuh** [comment]
This is the expected behaviour. If a user omits a field on submission, it is interpreted as `null`. Your underlying data classes have to account for invalid user input as validation happens only after mapping the input data to your model. Possible solutions to your problem are [DTOs](https://blog.martinhujer.cz/symfony-forms-with-request-objects/) or using something like the [Rich Model Form Bundle](https://github.com/qossmic/rich-model-forms-bundle).

I am closing here as there is no bug in the code. Thank you for understanding.

**Comment by janklan** [comment]
Ok, one question.

>  If a user omits a field on submission, it is interpreted as `null`

Why does [this property](https://github.com/janklan/symfony-bug-51571/blob/main/src/Controller/DefaultController.php#L30) cause a different behaviour than [this property](https://github.com/janklan/symfony-bug-51571/blob/main/src/Controller/DefaultController.php#L33)? The only difference is that one of them initialised, and the other isn't.

**Comment by xabbuh** [comment]
From the Form component's POV, the value of the first property doesn't change. So it never tries to write data back to the model.

**Comment by janklan** [comment]
I accept that POV, thanks.

With that said, if the solution (one of them) is to add a setter just to ignore the null input PropertySetter attempts to pass to a non-nullable property, I am still convinced the intended behaviour is incorrect, probably based on some legacy context from time before type declaration became available, making the need for setters obsolete in many cases.

Anyway, I guess I'm alone in this view, so I will just keep adding workarounds for this behaviour.
