### ISSUE TITLE
Re-open Add an initialize method to workflows

### ISSUE THREAD

**Issue by yedprior** [symfony/symfony#51591]
### Description

Re-open https://github.com/symfony/symfony/issues/27925.
I do not agree with the solution of the Voter which closed the featur request because it s hide workflow path which can depends from application settings and not user rights.
For example if i want to allow to activate extra check page if application admin need it and set it in his backoffice application settings database table.
Yes this can be moved in the Voter, as all Workflow package guard,  but this has nothing to do with the Voter function (or need to set pure states conditions in it) . And it hides part of the workflow transitions independents of the connected user.

**Comment by stof** [comment]
I don't understand which feature you actually request. You are talking about a voter but the issue you reference had nothing to do with a voter.
Please explain the feature you are actually requesting.

**Comment by yedprior** [comment]
Sorry, wrong link. It's fixed.

**Comment by lyrixx** [comment]
Hello, even with the fixed link, I do not understand what is your issue. There is not "Voter" in the Workflow. Maybe you mean "Guard", But even with this, I don't understand

Can you explain what you need?

**Comment by yedprior** [comment]
https://github.com/symfony/symfony/issues/27925#issuecomment-539412762

> @SulivanDotEu you can handle your use case using custom Security Voter and 'guard' property of transition. Like that:
 transitions:
                start:
                    guard: "is_granted('ROLE_ADMIN', subject) or is_granted('ROLE_SUPERADMIN', subject)"
                    from: draft
                    to:     submitted
                make_an_offer:
                    guard: "is_granted('ALLOW_TO_BID', subject)"
                    from: started
                    to:     started`

For me this solution consists of putting transition logic in the voter which does not necessarily depend on the connected user, and calling it with is_granted().
Would it be possible to have $_ENV in the workflow.yaml for example or datas provided by a service, please?

**Comment by lyrixx** [comment]
`guard` was a shortcut to deal with security. Now it deals with too many things.

I think it's a bad idea to add even more things.

Instead, you can write your own guard listener, and put all the logic there.
You can even put some logic in the workflow.yaml, in all metadata options, and use it in the listener. 

* https://symfony.com/doc/current/workflow.html#guard-events
* https://symfony.com/doc/current/workflow.html#storing-metadata

**Comment by yedprior** [comment]
Yes that's what I did with a line of 
"# WARNING Event SUBSCRIBER WARNING Event SUBSCRIBER WARNING Event SUBSCRIBER WARNING Event SUBSCRIBER WARNING Event SUBSCRIBER" 
near the transition name for when I'll have forgotten the relationship between the .yaml and the eventSubscriber class. Thanks anyway for the response. Have a good day.
