### ISSUE TITLE
Sending through Mailgun mailer with a subdomain results in "on behalf of" in sender name

### ISSUE THREAD

**Issue by karensg** [symfony/symfony#51596]
### Symfony version(s) affected

6.3.2

### Description

I am using symfony/mailgun-mailer (latest 6.3.2).

I have a subdomain set up: mg.domain.com and I send emails from user@domain.com. This should work when all dkim and spf align. However, the headers are not set correctly.

There is [this issue](https://serverfault.com/questions/1097879/sender-and-from-header-domain-mismatch-causes-malformed-display-in-outlook) with exact description of the problem and this [solution](https://stackoverflow.com/a/45445015/397646)

Can we please add this header as well? 

### How to reproduce

* Create a subdomain in Mailgun like mg,domain.com
* Send an email to a Microsoft email from user@domain.com

### Possible Solution

https://stackoverflow.com/a/45445015/397646

**Comment by OskarStark** [comment]
Can you send a PR including a testcase?

**Comment by Romanavr** [comment]
> Can you send a PR including a testcase?

Check this PR https://github.com/symfony/symfony/pull/51773
