### ISSUE TITLE
[Serializer] Method `getSupportedTypes` is not aware of the context

### ISSUE THREAD

**Issue by Spomky** [symfony/symfony#51608]
### Symfony version(s) affected

6.3.x

### Description

Hi,

I have a custom Denormalizer that perform preprocessing before denormalization. As an example, a value is first base64 decoded.

### How to reproduce

Let say the denormalizer is as follows:

```php
<?php

declare(strict_types=1);

namespace Acme;

use Symfony\Component\Serializer\Exception\BadMethodCallException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

final class PublicKeyCredentialOptionsDenormalizer implements DenormalizerInterface, DenormalizerAwareInterface
{
    use DenormalizerAwareTrait;

    private const ALREADY_CALLED = 'PREPROCESS_ALREADY_CALLED';

    public function denormalize(mixed $data, string $type, string $format = null, array $context = [])
    {
        if ($this->denormalizer === null) {
            throw new BadMethodCallException('Please set a denormalizer before calling denormalize()!');
        }
        if (! array_key_exists('value', $data)) {
            return $data;
        }

        $data['value'] = base64_decode($data['value']);
        $context[self::ALREADY_CALLED] = true;

        return $this->denormalizer->denormalize($data, $type, $format, $context);
    }

    public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
    {
        if ($context[self::ALREADY_CALLED] ?? false) {
            return false;
        }

        return $type === Data::class;
    }
}
```

It is called a first time where the array key `value` is base64 decoded.
Then it sends the modified dataset to the denormalizer. It is called a second time bu skipped (`supportsDenormalization` returns false) because of the context.

When implementing the new `public function getSupportedTypes(?string $format): array` method , `supportsDenormalization` is not called called at all and the denormalization will fail.

### Possible Solution

The method `getSupportedTypes` should be aware of the context or the method `supportsDenormalization` should be called to make sure the context is taken into account

**Comment by valtzu** [comment]
> When implementing the new public function getSupportedTypes(?string $format): array method 

As I've understood the `bool` in the return value controls if the value of `supportsDenormalization` will be cached or not. So in your case it should be

```php
public function getSupportedTypes(?string $format): array
{
    return [Data::class => false];
}
```

`false` here means the value of `supportsDenormalization` shall not be cached.

If that is what you were doing, then we could have an issue indeed :thinking: 

---

I think making getSupportedTypes aware of context would defeat the whole purpose why it was introduced (=performance).

**Comment by Spomky** [comment]
Many thanks @valtzu.
I think you are right. I tried to reproduce on [PHP Sanddbox](https://phpsandbox.io/n/azure-roos-tarpals-orfhu) but it works fine here.
There is something else in my application that is causing this bug.
