### ISSUE TITLE
[Form] Constraints not considered when form type is readded in submit event.

### ISSUE THREAD

**Issue by jan-pintr** [symfony/symfony#51637]
### Symfony version(s) affected

6.3.4

### Description

When developing app which requires dynamically form addition/removal according to submitted data I encountered problem that when for example `TextType` nested in `CollectionType` is re-added in `SubmitEvent` then constraints are not applied.

```
public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addEventListener(FormEvents::PRE_SET_DATA, [$this, 'onPreSetData']);
        $builder->addEventListener(FormEvents::PRE_SUBMIT, [$this, 'onPreSubmit']);
        $builder->addEventListener(FormEvents::SUBMIT, [$this, 'onSubmit']);
    }

    public function onPreSetData(PreSetDataEvent $event): void
    {
        $form = $event->getForm();

        $this->formAddValue($form);
    }

    public function onPreSubmit(PreSubmitEvent $event): void
    {
        $form = $event->getForm();

        $this->formAddValue($form);
    }

    public function onSubmit(SubmitEvent $event): void
    {
        $form = $event->getForm();

        $this->formAddValue($form);
    }

    private function formAddValue(FormInterface $form): void
    {
        $form->add('value', TextType::class, [
            'required' => false,
            'constraints' => [  // when form is added in SubmitEvent constraints are not considered!
                new Assert\NotBlank(),  
                new Assert\Callback([
                    'callback' => [$this, 'validateValue'],
                ]),
            ],
        ]);
    }
```

### How to reproduce

To reproduce this behavior please take a look into this [repository](https://github.com/jan-pintr/symfony-form-collection-constraints-reporoducer) or [online-sandbox](https://phpsandbox.io/e/x/hjsgx?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=)

In case form is submitted with empty data it is considered as valid even when constraint `NotBlank` is defined. Then when you comment out `$builder->addEventListener(FormEvents::SUBMIT, [$this, 'onSubmit']);` In `CollectionType` and `ItemType` submitting empty data results in validation error which is expected.

**Comment by xabbuh** [comment]
This is the expected behaviour. The `FormValidator` which traverses the form tree will ignore forms that are not submitted. This is the case for forms that you add during the `SUBMIT` event as the data was submitted before. So you are effectively replacing a submitted form with an unsubmitted form.

Use the `PRE_SUBMIT` event if you need to modify the form tree.

I am closing here as there is nothing to fix inside the component. Thank you for understanding.
