### ISSUE TITLE
[String] Transliteration RU 

### ISSUE THREAD

**Issue by tpatartmajeur** [symfony/symfony#51643]
### Symfony version(s) affected

6.3.4

### Description

The current transliteration functionality is producing an incorrect output when transliterating the name "Татьяна". The expected result should be "Tatiana", but instead, the transliterated output is "Tat-ana".

### How to reproduce

```php
new AsciiSlugger())->slug('Татьяна');
// Tat-ana
```

**Comment by nicolas-grekas** [comment]
See discussion in #51644
