### ISSUE TITLE
Symfony server does not respect given port

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#51654]
### Symfony version(s) affected

5.4.28

### Description

```
» symfony server:start --no-tls --port=45431
Following Web Server log file (/home/flip111/.symfony5/log/e2c76d1e80d5e2314378f4c21b372bc1d048d92e.log)
Following PHP log file (/home/flip111/.symfony5/log/e2c76d1e80d5e2314378f4c21b372bc1d048d92e/7daf403c7589f4927632ed3b6af762a992f09b78.log)

 [WARNING] The local web server is optimized for local development and MUST never be used in a production setup.



 [OK] Web server listening
      The Web server is using PHP CLI 8.2.10
      http://127.0.0.1:45431


[Web Server ] Sep 14 14:33:46 |DEBUG  | PHP    Reloading PHP versions
[Web Server ] Sep 14 14:33:47 |DEBUG  | PHP    Using PHP version 8.2.10 (from default version in $PATH)
[Web Server ] Sep 14 14:33:47 |INFO   | PHP    listening path="/usr/bin/php8.2" php="8.2.10" port=45443
[PHP        ] [Thu Sep 14 14:33:47 2023] PHP 8.2.10 Development Server (http://127.0.0.1:45443) started
```

Notice that server says `[OK] Web server listening` with address `http://127.0.0.1:45431` but then on the last line PHP development server says it started on another address `http://127.0.0.1:45443`. The latter is the actual address the server was hosted on

### How to reproduce

```
symfony new project --version=lts
cd project
symfony server:start --no-tls --port=45431
```

**Comment by stof** [comment]
The webserver of the Symfony CLI (which supports HTTPS for instance) started on the specified port, and is the one that you should connect to.

When you have php-fpm installed, this webserver then uses a Unix socket to communicate with php-fpm through FastCGI. But if you only have the CLI SAPI installed on your system, the PHP built-in webserver is used as a fallback, and this one will listen to a port (to which the Symfony CLI webserver will proxy the request).
Note that installing php-fpm is recommended for better performance becayse the PHP built-in webserver does not support concurrent requests.

**Comment by flip111** [comment]
Technical explanation makes sense. Though UX wise it's not great. Every time you restart the symfony-cli tool you have to type the new port in the browser address bar. When you want to run a developer setting and the setup looks like this:

code -> symfony proxy -> php webserver -> browser

you want to be able to the port of the php webserver because that is where your browser will connect to. What would be cool is that instead of "find available port" you could configure the actual port you have to connect to with the browser. 

https://github.com/symfony-cli/symfony-cli/blob/aa0ebf21624ef7e262522f721b31ebc2baf8b397/local/php/php_server.go#L90

Can use a flag here instead of picking a random available port.

By the way, just as a curiosity what is the use case for configuring the proxy port when launching a local php dev server? it seems one could just use any available port for that as implementation detail.

**Comment by derrabus** [comment]
Please report this to https://github.com/symfony-cli/symfony-cli

**Comment by stof** [comment]
@flip111 the browser should not connect to the php webserver directly. This one will not support HTTPS and will not support the local domains. The public port is precisely the one from the proxy in this case.
