### ISSUE TITLE
[BrowserKit] Managing multiple CookieJar on the same HttpClient

### ISSUE THREAD

**Issue by paullallier** [symfony/symfony#51658]
### Description

I'd like to be able to test with BrowserKit HttpClient, simulating multiple users, but this means I need to swap the cookie jars around - at least if I want to avoid spawning lots of clients.

Would you consider allowing a setCookieJar() method or would this fundamentally break something?  Perhaps on AbstractBrowser?  It might even be easy enough for me to PR it!

**Comment by stof** [comment]
If you want to simulate multiple users, the right way is to instantiate multiple browsers (that's also how you would do it with actual browsers btw)

**Comment by paullallier** [comment]
That does seem more correct, but I'm struggling to see how I'd spawn extra clients in my test runner without breaking all the self::assert... calls, which look for the client with self::getClient().  But perhaps that's a discussion for Slack rather than here?
