### ISSUE TITLE
Doctrine left in non-operable state when used with Swoole/FrankenPHP

### ISSUE THREAD

**Issue by henderkes** [symfony/symfony#51661]
### Symfony version(s) affected

*

### Description

Running Symfony with a long-running runtime that leaves worker threads alive, such as swoole, roadrunner and frankenphp regularly leads to exceptions being thrown when fetching many entities (~100) with doctrine, every few requests.

The roadrunner bundle addresses this with a doctrine orm/odm middleware: https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22

and there's also a bundle specifically for this issue here: https://github.com/pixelfederation/doctrine-resettable-em-bundle (which doesn't appear to work for FrankenPHP).

I've brought this up in the [FrankenPHP repository](https://github.com/dunglas/frankenphp/issues/207#issuecomment-1720739553) but since Symfony tries to officially support these runtimes, it should probably be fixed here.

### How to reproduce

Unfortunately I do not have a minimal example to reproduce this issue yet, but it is well known about and a way to fix it has been linked above.

If necessary, I can create a reproducer next week.

### Possible Solution

https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22

**Comment by dunglas** [comment]
While discussing privately with @chalasr, I proposed a general strategy to deal with long-running application servers in Symfony while not coupling the code with a specific solution:

1. The runtime set `$_SERVER['LONG_RUNNING']` if in worker/long-running mode
2. A `kernel.long_running` parameter is set in the DI container if `$_SERVER['LONG_RUNNING']` is set
3. Specific code (like the listener needed to handle this case) if executed only if this parameter is set

This way, it's possible to have out-of-the-box support for long-running PHP servers while not coupling directly Symfony to FrnakenPHP, RoadRunner, and the like.

WDYT @symfony/mergers?

**Comment by nicolas-grekas** [comment]
You might want to check #51408 :)

**Comment by henderkes** [comment]
The proposed default would set this to 'web' for fcgi requests too, so this value should probably be set in the runtime to something different. We'd still need to distinguish between execute-and-die web processes and "long-running" ones kept in memory.

**Comment by dunglas** [comment]
For FrankenPHP, the runtime can inspect the if `$_SERVER['FRANKENPHP_WORKER']` is set. I'm sure Swoole and the like can also easily be detected. What we'll have to to is add the `worker` value in addition to `web` and `cli` in https://github.com/symfony/symfony/pull/51408.

**Comment by kbond** [comment]
I've come into a related issue: registering stuff in `register_shutdown_function()`. Could there be an equivalent generalized function for long running processes? Register something to happen after a _long running server_'s request is finished?

I know we can use `kernel.reset` (I think the container is reset using long running servers). I'm thinking more for code that isn't in a service (ie static state on a helper utility).

**Comment by henderkes** [comment]
> Register something to happen after a long running server's request is finished?

Kernel terminate event? That would work for both cgi requests as well as worker requests.

**Comment by kbond** [comment]
> Kernel terminate event?

That works for services. What I'm talking about is a global function for utility functions. For instance, I have a temp file creation utility that tracks all temp files created and deletes them with `register_shutdown_function()`. This doesn't happen (frequently enough) with long running servers.

**Comment by chalasr** [comment]
Yet another reason to prefer scoped services over global utils? :) Joke aside, worker-like web servers have different requirements than fire-and-forget ones we're used to and I think the code "just" needs to adapt. 
Perhaps Franken could provide some hook but I'd argue that most use cases - if not all - are better addressed otherwise.

**Comment by henderkes** [comment]
I think that "problem' isn't Symfony specific - when using Symfony you could register callbacks into a static collection of a kernel.terminate listener which cleans them up when the event is fired. The 'problem' is that users would have to come up with different solutions for different runtimes/frameworks.

FrankenPHP shouldn't provide any specific hooks because that just leads users in guessing lang again. It either has to be coordinated by all the worker implementation maintainers or integrated into a common package they all use (Runtime?).

**Comment by nicolas-grekas** [comment]
#52079 to the rescue. Help wanted to close this issue.

**Comment by alli83** [comment]
> #52079 to the rescue. Help wanted to close this issue.

I would be happy to deal with this issue

**Comment by KDederichs** [comment]
That's still an issue btw.
Not sure if #52079 was supposed to fix it (maybe in combination with the frankenphp runner?) but it's still happening.
