### ISSUE TITLE
[Workflow] Deprecated Registry how to deal with

### ISSUE THREAD

**Issue by mpiot** [symfony/symfony#51662]
### Description

Hi,
Our application heavily use `Workflow` and have many validators, custom Twig function, and services that use an Entity or collection of Entity as entry, and check it against its workflow, to do it we use the `Registry` and it `get` method that return us the good workflow.

Since the `Registry` injection is deprecated, we knw that from 7.0 all the application should break, we can use something like:
`#[TaggedLocator(tag: 'workflow')]` or `#[TaggedIterator(tag: 'workflow')]` to inject all Workflow, but it seems there is not way to use retrieve the `supports` attribute to do it (find the good Workflow).

That said, even if this were the case, it's a shame to perform this operation on many validators and many services when an existing class already does it.

**Comment by sgehrig** [comment]
Please see the discussion at [#49199](https://github.com/symfony/symfony/discussions/49199). I had the same reservations about the deprecation and the removal. As far as I can tell, regaining the same functionality will basically require you to reimplement the registry feature in your code. I still don't really understand how the removal should work together with the `WorkflowSupportStrategyInterface`.

**Comment by ro0NL** [comment]
ref #51400, #51227

**Comment by lyrixx** [comment]
okay, let's un-deprecate the deprecation

see https://github.com/symfony/symfony/pull/51976

**Comment by sgehrig** [comment]
@lyrixx This is much appreciated. Thanks so much for your efforts.
