### ISSUE TITLE
Serializer psalm/phpstan types support

### ISSUE THREAD

**Issue by KorDum** [symfony/symfony#51673]
### Description

Serializer (denormalization specifically) does not support `non-empty-list<>`.
I have to change to `list<>` and I'm forced to add in code that uses this data structure `non-empty-list<>`.

Can you add support please?

### Example

Now:
```php
// In Data Structure
/**
 * @var list<Payment> $payments
 */
public array $payments;

// I have to write phpDoc in code
/** @var non-empty-list<Payment> $payments */
$payments = $data->payments;
```

After adding support:
```php
// In Data Structure
/**
 * @var non-empty-list<Payment> $payments
 */
public array $payments;
```

**Comment by derrabus** [comment]
> Can you add support please?

Can you?

If you have this problem, you're probably the best person to solve it.

**Comment by Eydamos** [comment]
You could also use the psalm/phpstan prefix to fix this:
```
// In Data Structure
/**
 * @var list<Payment> $payments
 * @psalm-var non-empty-list<Payment> $payments
 */
public array $payments;
```
IDE's like PHPStorm as well as psalm and phpstan are usually clever enough to prioritise the prefixed version for their static analysis

**Comment by mtarld** [comment]
As soon as https://github.com/symfony/symfony/pull/52510 is merged (really hope it will), and when it'll be integrated in the serializer, the object normalizer will be able to read these PHPStan tags.

**Comment by EmilMassey** [comment]
It's already supported since Symfony 6.1 (see #44451). You just need to make sure that you have PhpStanExtractor enabled - you need to add `phpstan/phpdoc-parser` and `phpdocumentor/reflection-docblock` as a composer dependency if you haven't already.

**Comment by xabbuh** [comment]
let's close here then
