### ISSUE TITLE
AutowireCallable Doesn't Respect Non-Shared Services

### ISSUE THREAD

**Issue by miqrogroove** [symfony/symfony#51691]
### Symfony version(s) affected

6.3.3

### Description

Using the examples from [Generate Closures With Autowiring](https://symfony.com/doc/current/service_container/autowiring.html#generate-closures-with-autowiring), I found that the two different attributes don't work the same way.

AutowireServiceClosure returns a _new instance_ on every call when the encapsulated service is non-shared.

AutowireCallable returns the _same instance_ on every call when the encapsulated service is non-shared.

I couldn't figure out whether this is a documentation problem or an oversight in the design of these new attributes.  The docs for the Callable attribute literally said, "a service accepts a closure with a specific signature", and one of the options is named "service", so to me this means the closure should be aware of how services work.

### How to reproduce

Test case added here:

https://github.com/miqrogroove/symfony-bug-51691/tree/main/trunk

At your command line use:

`bin/console app:test`

Also note "Usages" under:

`bin/console debug:container MyService`

Whereas AutowireServiceClosure will show usage by a specific class like `App\Service\Neato`, the AutowireCallable usage shows up like `.1_Closure~lIx8M9C`

**Comment by OskarStark** [comment]
Friendly ping @nicolas-grekas @stof

**Comment by derrabus** [comment]
> AutowireCallable returns the _same instance_ on every call when the encapsulated service is non-shared.

Can you be a bit more specific here? `AutowireCallable` does not return anything. It's a marker that tells the container which dependency to wire into your service.

What is the Closure that you would expect to be wired and what closure did you actually get?

**Comment by miqrogroove** [comment]
@derrabus  Correct.  Let's say, at least for testing, I'm wiring a non-shared service method that returns itself, i.e. `return $this`.

Now, am I to expect repeated calls to the same AutowireCallable will call the specified method of the _same_ non-shared instance every time, or do I expect that each call will encapsulate a _new_ non-shared instance and call the specified method without reading or overwriting the state of any other object?

And the obvious follow-up:  How am I supposed to know which is what?  The documentation makes it sound like these two attributes are both Closures where one conveniently calls a method and the other doesn't.  But testing shows these two Closures don't do the same thing.

**Comment by derrabus** [comment]
> @derrabus Correct. Let's say, at least for testing, I'm wiring a non-shared service method that returns itself, i.e. `return $self`.

A method cannot return itself. 🤔 

> Now, am I to expect repeated calls to the same AutowireCallable will call the specified method of the _same_ non-shared instance every time, or do I expect that each call will encapsulate a _new_ non-shared instance and call the specified method without reading or overwriting the state of any other object?

I guess we've never really specified that. My expectation would be that is works as `Closure::fromCallable()` has worked previously. That means, it's equivalent to constructing your service like this:

```php
new MyService(
    \Closure::fromCallable([$container->get('non_shared_service'), 'someMethod']),
);
```

In other words, each call to that closure would go to the same instance, but two different services with the same `AutowireCallable` attribute will receive different instances of `non_shared_service`.

**Comment by miqrogroove** [comment]
> A method cannot return itself. 🤔

Please excuse my jargon.  I am a mere end user from your perspective.

Testcase added in top post.

**Comment by nicolas-grekas** [comment]
As described in https://github.com/symfony/symfony/pull/51695#issuecomment-1726076865, this is the expected behavior.
