### ISSUE TITLE
VarDumper returns inline <script> and <style> tags, which cause content security policy failures

### ISSUE THREAD

**Issue by Yannik** [symfony/symfony#51692]
### Symfony version(s) affected

latest

### Description

`Symfony\Component\VarDumper\Dumper\HtmlDumper` returns inline `<script>` tags in both `getDumpHeader()` and `dumpLine()` functions. On a site with a content security policy, this leads to csp errors.

### How to reproduce

```
<?php
use Symfony\Component\VarDumper\Dumper\HtmlDumper;

/**
 * We have to extend the base HtmlDumper class in order to get access to the protected-only
 * getDumpHeader function.
 */
class DebugBarHtmlDumper extends HtmlDumper
{
    public function getDumpHeaderByDebugBar() {
        // getDumpHeader is protected:
        return $this->getDumpHeader();
    }
}
```

```
$dumper = new DebugBarHtmlDumper;
echo $dumper->getDumpHeaderByDebugBar();
```

results in `<script> Sfdump = window.Sfdump || (function (doc) { doc.documentElement.classList.add('sf-js-enabled'); var rxEsc = /([.*+?^${}()|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/, keyHint = 0 <= navigator.platform.toUpperCase().indexOf('MAC') ? 'Cmd' : 'Ctrl', addEventListener.....`

### Possible Solution

To fix this, I can see two options (IMO, it makes sense to implement both)

- provide the `getDumpHeader()`  <script> and <style> elements as `.js` and `.css` files, so they can be included without triggering CSP errors (using <link> elements). For the individual `dumpLine()` elements, the <script> element is not really necessary, the Sfdump call can also be achieved by using the main javascript.
- allow to provide a nonce for the script/style elements

**Comment by javiereguiluz** [comment]
Yannik, thanks for reporting this issue. A few months ago, we received a report about the same error in #49068. So, we're closing this issue as a duplicate of the earlier issue. Thanks!

**Comment by Yannik** [comment]
Hi @javiereguiluz

The bug you mention is only about style-src violations due to inline css. My bug is also about script-src and <style> elements.

**Comment by javiereguiluz** [comment]
Thanks! I added a comment in #49068 to also include the two `script-src` and `<style>` elements that you mentioned.

**Comment by Yannik** [comment]
Thanks @javiereguiluz

**Comment by damienfa** [comment]
I noticed the same issue and we cannot use the VarDump with the common CSP rules… 😣
The js code generated by `{ dump(…) } is something like `<script>Sfdump("sf-dump-1795286044")</script>` but my browser do not execute this Javascript code because of the CSP-violation... 
The expand/collapse arrow on arrays variables in the sf-dump output is not working, for example.

It would be great to fix it and to be CSP compliant 😕
