### ISSUE TITLE
[DoctrineBridge] Passing the request object to the EntityValueResolver's expression

### ISSUE THREAD

**Issue by stollr** [symfony/symfony#51694]
### Description

I would like to suggest passing the request object to the expression evaluation of the `EntityValueResolver`. This would make it possible to use parameters of the request body which is useful in REST APIs.

In the resolver we only need to change the following line in the `findViaExpression` method:

```patch
-         $variables = array_merge($request->attributes->all(), ['repository' => $repository]);
+         $variables = array_merge($request->attributes->all(), [
+             'repository' => $repository,
+             'request' => $request,
+         ]); 
```

### Example

Now, one could use the expression like this:

```php
public function createAction(
    #[MapEntity(expr: 'repository.find(request.toArray()["userId"])')]
    User $user,
) {}
```

What do you think?

**Comment by yesdevnull** [comment]
I faced this problem just the other day trying to use a POST parameter in an expression. Would love to see this resolved in exactly the way you proposed.
