### ISSUE TITLE
Deprecated object normalizer replacement fails during normalization

### ISSUE THREAD

**Issue by hashbanged** [symfony/symfony#51707]
### Symfony version(s) affected

6.3.4

### Description

Normalizing an object using `NormalizerAwareInterface` as described in the [7.0 docs](https://symfony.com/doc/7.0/serializer/custom_normalizer.html) fails in a custom normalizer. Please see the reproducer project here: https://github.com/hashbanged/normalizer-bug

### Background

Injecting `ObjectNormalizer` in a custom normalizer works but is deprecated in 6.3 ([6.3 docs](https://symfony.com/doc/current/serializer/custom_normalizer.html)). 

> Since symfony/serializer 6.2: The "Symfony\Component\Serializer\Normalizer\ObjectNormalizer" service alias is deprecated, type-hint against "Symfony\Component\Serializer\Normalizer\NormalizerInterface" or implement "Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface" instead.

The 7.0 docs describe implementing `NormalizerInterface` and `NormalizerAwareInterface` with the use of a setter in `NormalizerAwareTrait`. Calling [normalize()](https://github.com/hashbanged/normalizer-bug/blob/b6a1b861062aa8afcd5ba7a1a706aa566129c7bf/src/Service/Serializer/BrokenNormalizer.php#L21C36-L21C36) causes an error and the method fails to return:

```
unable to fetch the response from the backend: unexpected EOF`
```

A breakpoint at the trait's [`setNormalizer()`](https://github.com/symfony/symfony/blob/f3c9644ada404febd4762fb3443bcb623e35bbfc/src/Symfony/Component/Serializer/Normalizer/NormalizerAwareTrait.php#L23C3-L23C41) shows the value as `Symfony\Component\Serializer\Serializer`. Is this correct? I would think that it should be an instance of a normalizer, e.g., `ObjectNormalizer`.

### How to reproduce

1. Clone the issue reproducer found at https://github.com/hashbanged/normalizer-bug: 
`git clone git@github.com:hashbanged/normalizer-bug.git`

2. Change to the project directory and Install dependencies:
`composer install`

3. Start the Symfony server (or otherwise configure the project for your environment):
`symfony server:start`

4. Navigate to https://127.0.0.1:8000 in your browser to view the error.

### Where to find the error

The error specifically seems to be in the call to the injected ("set") normalizer's `normalize()` method:

```php
class BrokenNormalizer implements NormalizerInterface, NormalizerAwareInterface
{
    use NormalizerAwareTrait;

    public function normalize($responseDto, string $format = null, array $context = [])
    {
        // Debugger shows that the normalizer class is Symfony\Component\Serializer\Serializer.
        // The following method call fails with the error:
        //
        //      "unable to fetch the response from the backend: unexpected EOF"

        $data = $this->normalizer->normalize($responseDto, $format, $context);

        // This line isn't reached, but we'd otherwise do something with the
        // data before returning a modified version.

        return $data;
    }
    // ...more...
}
```

### Additional Context

I may be misunderstanding the expected class for norrmalization, but the debugger shows these as instances of `Symfony\Component\Serializer\Serializer`.

![image](https://github.com/symfony/symfony/assets/53536018/90ee117c-3d2b-4183-a801-a90b7cabfa2a)
Figure 1. A breakpoint at `$this->normalizer->normalize()` shows a Serializer instance.

![image](https://github.com/symfony/symfony/assets/53536018/b687e7b4-7c4e-45ec-b717-cff69480b4ec)
Figure 2. A second breakpoint in the Symfony serializer's `normalize()` method also shows a Serializer instance.

**Comment by mtarld** [comment]
Hey @hashbanged! Thank you for reporting the issue with so much details.

I tried your reproducer locally and here is what I found.

It appears that you're triggering an infinite normalizer call loop. 
Indeed, the `BrokenNormalizer` calls the `Serializer`, which looks for a normalizer that can normalize the `ResponseDto` and find the `BrokenNormalizer` (endlessly).

To fix that issue, you must manipulate the context a bit:
```php
class BrokenNormalizer implements NormalizerInterface, NormalizerAwareInterface
{
    private const ALREADY_CALLED = 'broken_normalizer_already_called';

    use NormalizerAwareTrait;

    public function normalize($responseDto, string $format = null, array $context = [])
    {
        $context[self::ALREADY_CALLED] = true;

        return $this->normalizer->normalize($responseDto, $format, $context);
    }

    public function supportsNormalization($data, string $format = null, array $context = []): bool
    {
        return $data instanceof ResponseDto && false === (self::ALREADY_CALLED ?? false);
    }

    public function getSupportedTypes(?string $format): array
    {
        return [
            ResponseDto::class => true,
        ];
    }
}
```

But this is not enough, because we are relying on context to know if the normalizer is selectable, we must tell that the result of the supports is not cacheable anymore.
```diff
public function getSupportedTypes(?string $format): array
{
    return [
-        ResponseDto::class => true,
+        ResponseDto::class => false,
    ];
}
```

**Comment by hashbanged** [comment]
Thank you, @mtarld! This was super helpful. Yes, `normalize()` was being called on this class more times than I can count, and the reason made sense after reading your explanation and then working back through the normalizer class comments and docs with that info. All is working as needed!
