### ISSUE TITLE
RedisSessionHandler reported an error after upgrading phpredis to 6.0.0

### ISSUE THREAD

**Issue by TianLiangZhou** [symfony/symfony#51700]
### Symfony version(s) affected

6.3.0

### Description

deprecation.INFO: Deprecated: Redis::expire(): Passing null to parameter #3 ($mode) of type ?string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Redis::expire(): Passing null to parameter #3 ($mode) of type ?string is deprecated at

 snc_redis.DEBUG: Executing command "EXPIRE sess:dlrqcnojkf0e2l2nnr2ovg79rj 604800 <null>" [] []

request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: Redis::expire(): Unknown expiration modifier ''"

### How to reproduce

upgrading phpredis to 6.0.0

**Comment by nicolas-grekas** [comment]
Related to https://github.com/phpredis/phpredis/pull/2363
I guess either this fix isn't part of 6.0.0 or there are more arg info that need a fix.
Can you please check these possibilities?

**Comment by TianLiangZhou** [comment]
Ok , now  i need downgrade phpredis

**Comment by ahmed-bhs** [comment]
@TianLiangZhou @nicolas-grekas any idea please, how to force apt install php8.2-redis to install phpredis 5.3.7 extension instead of 6.0.0 ?

**Comment by dmaicher** [comment]
> @TianLiangZhou @nicolas-grekas any idea please, how to force apt install php8.2-redis to install phpredis 5.3.7 extension instead of 6.0.0 ?

Install `php-dev`, then run `pecl install redis-5.3.7` and enable the extension afterwards in your ini with `extension=redis.so`

**Comment by quentint** [comment]
Using Platform.sh? If so:
- Remove `redis` from `runtime.extensions`
- Add `curl -fsS https://raw.githubusercontent.com/platformsh/snippets/main/src/install-phpredis.sh | { bash /dev/fd/3 6.0.1 ; } 3<&0` to the build hook

This will use phpredis 6.0.1 where the bug is fixed. Using a custom phpredis version on Platform.sh [is documented here](https://docs.platform.sh/languages/php/redis.html).

I hope this helps (it fixed my project).

**Comment by TianLiangZhou** [comment]
> > @TianLiangZhou @nicolas-grekas any idea please, how to force apt install php8.2-redis to install phpredis 5.3.7 extension instead of 6.0.0 ?
> 
> Install `php-dev`, then run `pecl install redis-5.3.7` and enable the extension afterwards in your ini with `extension=redis.so`

Correct +1

**Comment by 99hops** [comment]
I also see this with [Redis](https://pecl.php.net/package/redis) `6.0.0/6.0.1` 

`deprecation.INFO: Deprecated: Redis::scan(): Passing null to parameter #4 ($type) of type ?string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Redis::scan(): Passing null to parameter #4 ($type) of type ?string is deprecated at /var/www/html/vendor/symfony/cache/Traits/Redis6Proxy.php:891)"} []`

while `5.3.7` doesn't

**Comment by 99hops** [comment]
> @TianLiangZhou @nicolas-grekas any idea please, how to force apt install php8.2-redis to install phpredis 5.3.7 extension instead of 6.0.0 ?

`apt search php8.2-redis`
`apt install php8.2-redis=5.3.7 (if available)`

or remove the apt package and install via pecl 

`pecl install redis-5.3.7` and enable module `docker-php-ext-enable redis` or make/link redis.ini

**Comment by nicolas-grekas** [comment]
If this persists despite https://github.com/phpredis/phpredis/pull/2363, this should be reported there, because an argument with type `?string` should accept null.

Closing since this is not on our side. Please link back here if you open the issue on phpredis.
