### ISSUE TITLE
[Messenger][Serializer] Support `ValidationFailedException` normalization

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#51739]
### Description

The `validation` middleware throws `Symfony\Component\Messenger\Exception\ValidationFailedException`s. You can map them to a 400 status code, but violations won’t be part of the response because [the `ProblemNormalizer` will only consider `Symfony\Component\Validator\Exception\ValidationFailedException`](https://github.com/symfony/symfony/blob/fbf6f56ca7321e28d9a4368e18b9da683c296046/src/Symfony/Component/Serializer/Normalizer/ProblemNormalizer.php#L87).

Would it be possible to handle `Symfony\Component\Messenger\Exception\ValidationFailedException` the same way, so that a conversion step isn’t needed? Or should the `ValidationMiddleware` throw `Symfony\Component\Validator\Exception\ValidationFailedException`s?

**Comment by ro0NL** [comment]
shouldnt it just throw the component exception? It already recives violations from its ValidatorInterface
