### ISSUE TITLE
[Console] Incorrectly aligned block

### ISSUE THREAD

**Issue by Blacksmoke16** [symfony/symfony#51734]
### Symfony version(s) affected

Tested as low as `4.4.x` and at latest commit on `7.0` branch.

### Description

When using the output formatter helper to format a block that has escaped content and in large mode, there are extra spaces on the first/last line.

### How to reproduce

```php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\FormatterHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

require './vendor/autoload.php';

class MyCommand extends Command
{
    protected static $defaultName = 'test';

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = new FormatterHelper();

          $output->write(
              $helper->formatBlock("<info>some info</info>", "error", true)
          );

        return 0;
    }
}

$app = new Application();
$app->add(new MyCommand());

$app->run();
```

### Additional Context

![image](https://github.com/symfony/symfony/assets/12136995/fcaafc3a-e2df-4e9c-b4ef-b2524d250f97)

**Comment by SzymonKaminski** [comment]
This test from source code shows that you need to escape every `<` and `>` manually with `\`: 
https://github.com/symfony/symfony/blob/fbf6f56ca7321e28d9a4368e18b9da683c296046/src/Symfony/Component/Console/Tests/Helper/FormatterHelperTest.php#L81-L92

**Comment by OskarStark** [comment]
Feel free to reopen if the proposed solution from @SzymonKaminski does not work
