### ISSUE TITLE
[HtmlSanitizer] HTML Sanitizer breaks GET parameters in urls

### ISSUE THREAD

**Issue by enl** [symfony/symfony#51753]
### Symfony version(s) affected

6.3.4

### Description

When sanitising links, get parameters are broken because of `=` being html-encoded to `&#61;`:

```
https://support.google.com/accounts/answer/61416?hl&#61;en
```

### How to reproduce

```
require_once __DIR__ . '/vendor/autoload.php';

$url = 'https://support.google.com/accounts/answer/61416?hl=en';

$config = (new \Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig())
->allowSafeElements()
->allowMediaSchemes(['http', 'https'])
->forceHttpsUrls();

$urlAttributeSanitizer = new \Symfony\Component\HtmlSanitizer\Visitor\AttributeSanitizer\UrlAttributeSanitizer();

var_dump($urlAttributeSanitizer->sanitizeAttribute('a', 'href', $url, $config));

$sanitizer = new \Symfony\Component\HtmlSanitizer\HtmlSanitizer($config);

var_dump($sanitizer->sanitize('<a href="' . $url .'">test</a>'));
```

**Expected output:**

```
"https://support.google.com/accounts/answer/61416?hl=en"
"<a href="https://support.google.com/accounts/answer/61416?hl=en">test</a>"
```

**Actual output:**

```
"https://support.google.com/accounts/answer/61416?hl=en"
"<a href="https://support.google.com/accounts/answer/61416?hl&#61;en">test</a>"
```

### Additional Context

It seems to be happening in \Symfony\Component\HtmlSanitizer\Visitor\Node\Node::renderAttributes method.

**Comment by stof** [comment]
What is broken exactly here ?

This escaping of `=` happens at the HTML level. the resolved value of the attribute is still a URL using `=` AFAICT (when using a proper HTML parser to find the value of the attribute and not a regexp)

**Comment by enl** [comment]
Thanks for pointing it out @stof, it actually works as expected indeed. Sorry for brain-fart :)
