### ISSUE TITLE
[symfony new ...] --> PHP Fatal error: Declaration of Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::execute must be compatible with Symfony\Component\Console\Command\Command::execute

### ISSUE THREAD

**Issue by krukiv-kut** [symfony/symfony#51758]
### Symfony version(s) affected

7.0.*@dev

### Description

Given environment:

- Symfony CLI version 5.5.9
- Composer version 2.6.3
- PHP 8.2.10 (cli)
- OS - macOS Ventura 13.5.2 (22G91)

I was just going to start, so.. simply launched the command:
`symfony new symfony7project --version="7.0.*@dev" --webapp`

Result:
`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Declaration of Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /Users/.../vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php on line 65
!!
!!  Fatal error: Declaration of Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /Users/.../vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php on line 65
!!  Symfony\Component\ErrorHandler\Error\FatalError {#5479
!!    -error: array:4 [
!!      "type" => 64
!!      "message" => "Declaration of Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int"
!!      "file" => "/Users/.../vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php"
!!      "line" => 65
!!    ]
!!    #message: "Compile Error: Declaration of Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int"
!!    #code: 0
!!    #file: "./vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php"
!!    #line: 65
!!  }
!!
Script @auto-scripts was called via post-update-cmd`

### How to reproduce

Run in terminal:
`symfony new symfony7project --version="7.0.*@dev" --webapp`

### Additional Context

**doctrine/dbal [version: 3.6.7]**

**Comment by derrabus** [comment]
see doctrine/dbal#6136

**Comment by krukiv-kut** [comment]
> see [doctrine/dbal#6136](https://github.com/doctrine/dbal/pull/6136)

Thanks. Didn't recognise it's same issue 🫠
