### ISSUE TITLE
IntlDateFormatter stub has invalid casing in constructor parameters

### ISSUE THREAD

**Issue by mrblur** [symfony/symfony#51752]
### Symfony version(s) affected

5.4

### Description

For PHP native `\IntlDateFormatter`, date and time type arguments are named `$dateType` and `$timeType` where on `symfony/intl` they are named `$datetype` and `$timetype`.

This leads to issues reported by phpstan checks when using named parameters.

### How to reproduce

Run phpstan checks on symfony application containing this fragment:

```php
$formatter = new \IntlDateFormatter(
    locale: 'en',
    dateType: \IntlDateFormatter::MEDIUM,
    timeType: \IntlDateFormatter::LONG,
);
```

### Possible Solution

Fix constructor argument letter casing in stub class :)

**Comment by stof** [comment]
@mrblur can you submit a PR with a fix ?

**Comment by stof** [comment]
Btw, those polyfills live in https://github.com/symfony/polyfill

**Comment by mrblur** [comment]
Yeah, that's first riddle part. I am not familiar with the whole package dividing mechanism. I recall the files are inside `symfony/intl` not `symfony/polyfill`, as I have no intl polyfills due to native `intl` extension in my projects. The fix is stupid easy, but the real question is where should I put it in? :sweat_smile:

**Comment by ro0NL** [comment]
start here https://github.com/search?q=org%3Asymfony%20%22class%20IntlDateFormatter%22&type=code ;)

**Comment by xabbuh** [comment]
I guess you need to update the polyfill package containing this class as there has been a fix for this nearly three years ago (see symfony/polyfill#317).

**Comment by xabbuh** [comment]
Closing therefore, but please leave a comment if you still experience the issue, provide a small example application that allows to reproduce it and we can consider to reopen. Thank you for understanding.
