### ISSUE TITLE
[AssetMapper] Handling 3rd party CSS downloads automatically

### ISSUE THREAD

**Issue by benr77** [symfony/symfony#51763]
### Description

I'm just starting out playing with the AssetMapper component. All is smooth, except for one thing - the handling of 3rd party CSS files.

Now I know the docs say it's a manual process etc, and to simply reference the CSS from a CDN etc. However, this has a few implications:

1) Tests that render HTML pages start making external network connections
2) I often work whilst travelling, and wifi on trains for example is terrible. Having all these external dependencies means sometimes my pages don't load as they are waiting for a connection.
3) I don't necessarily want to rely on JsDelivr or whatever - I want the CSS files to be local to my app, and then served by my own CDN on deployment (e.g. Cloudflare will automatically detect CSS file HTTP requests and serve them from the edge network instead of hitting the application server).

So, I started immediately looking at the download options for CSS files, in additional to the existing and documented way of downloading JS files. 

The docs suggest downloading the CSS file into the `assets/vendor` directory, but this makes no sense to me. Just like composer's `vendor` directory, the `assets/vendor` directory should be ephemeral surely?

I also don't want to download all these vendor CSS files and add them to my Git repo, which would solve the problem, but this feels dirty.

Obviously I could write a simply script that will take a list of 3rd party CSS dependency URLs and download them, e.g. during CI build or whatever, but it does feel like this should be part of the AssetMapper component.

I guess Ryan has already been thinking about this so hopefully there is a best practice already too???

Thanks!

**Comment by weaverryan** [comment]
Hey!

I match your thinking exactly :). AssetMapper 6.4 has support for CSS. In addition to that, all vendor assets (JS or CSS) are downloaded locally in all cases. No more CDN URLs ever.

Cheers!

**Comment by benr77** [comment]
Great stuff Ryan thanks very much!

**Comment by allan-simon** [comment]
@weaverryan  the documentation still references a manual procedure 

https://symfony.com/doc/6.4/frontend/asset_mapper.html#handling-3rd-party-css
