### ISSUE TITLE
Memory Leak in Symfony Mailer when sending many attachments of >5MB

### ISSUE THREAD

**Issue by asmafarhat2006** [symfony/symfony#51764]
### Symfony version(s) affected

5.4.22

### Description

Hi , 
I have encountered an issue where attaching several files each of size 5MB , sends Out Of Memory exception 
` Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 23079128 bytes)" at vendor/symfony/mime/RawMessage.php line 53 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 23079128 bytes) at vendor/symfony/mime/RawMessage.php:53)"} [`

Is that a known issue. or am I missing something ? 

I have already tried using attachPart, attach , but it produces the same results.

### How to reproduce

Attach numerous Files from form to be sent in email each of size 5MB .

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by asmafarhat2006** [comment]
Yep sure, will try to 
Does that means its not a known limitation when attaching attachments of size > 4MB in Symfony mailer ?

**Comment by asmafarhat2006** [comment]
I have replicated this issue in a separate app 
Following is the github link 
https://github.com/asmafarhat2006/email_attachment_issue/tree/main
You can see the issue if you use this command 
`php -d memory_limit=32M bin/console app:test-email`

Worth mentioning that you will be able to see the increase in memory usage when trying to send the email .
This issue occurs with Symfony version 6.1 as well

**Comment by maelanleborgne** [comment]
Hi, thank you for the reproduction project, I've managed to reproduce the issue and tried to find the source of the excessive memory consumption.
I'm not sure if that's correct, but it seems like the `RawMessage::toIterable`  method creates a variable to store the 'current string version' of the message : https://github.com/symfony/symfony/blob/a25732727de247f327f67952160717325be3b397/src/Symfony/Component/Mime/RawMessage.php#L48
We end up having two representation of the message in memory : the property and the variable. 

I'm not familiar with the internals of the `RawMessage` and the Mime component, could someone explain why we're keeping this copy ?

**Comment by james-manley** [comment]
I can reproduce this too, but it doesn't look like this was an issue in the previous Swiftmailer library.

**Comment by asmafarhat2006** [comment]
@xabbuh Can you please suggest if there will be a possible fix or any workaround we can adopt apart from increasing the php memory limit

**Comment by xabbuh** [comment]
Someone will have to look into it and yes to discover a possible fix. The reproducer app should be a good starting point.

**Comment by asmafarhat2006** [comment]
@xabbuh Are you referring to the code sample I provided as the reproducer app?

**Comment by xabbuh** [comment]
Yes

**Comment by asmafarhat2006** [comment]
@xabbuh Just submitted this PR https://github.com/symfony/symfony/pull/51870 
Would love to hear your feedback .
Worth mentioning. It works on my test environments

**Comment by asmafarhat2006** [comment]
@maelanleborgne I tried your fix on my test application . I didnt receive any attachment with those changes

**Comment by fabpot** [comment]
While trying to understand why I wrote the code, I realized we should never change the internal representation. So, #51872 looks like a slightly better fix.

**Comment by asmafarhat2006** [comment]
Thanks @fabpot , any estimate of when it will be merged?

**Comment by asmafarhat2006** [comment]
Oh just noticed, you have closed the PR

**Comment by OskarStark** [comment]
#51874 is the current open PR for this issue

**Comment by asmafarhat2006** [comment]
@fabpot Can I ask why its closed? Does it resolve the issue because I tried the PR but  it doesnt . And hits the same memory issue

**Comment by asmafarhat2006** [comment]
@fabpot
 It seems it does resolve the issue in 5.4 , Just tried this https://github.com/symfony/symfony/commit/d6c879747d19fabbf220ea58b915c3eadf121259

Although you mentioned it wont be able to, and have merged in 6.4.
Do you see any problems if we patch the fix in 5.4 ?

**Comment by fabpot** [comment]
@asmafarhat2006 That's correct. Fixing the bug means a change in behavior and as such, it cannot be part of 5.4. In any case, performance optimizations (CPU and memory) are not considered bugs and always merged in the next upcoming version.

**Comment by asmafarhat2006** [comment]
Hi @fabpot 
I have just tried this fix https://github.com/symfony/symfony/pull/51926 in my application https://github.com/asmafarhat2006/email_attachment_issue/tree/main  but it results in the same issue. 
The only change I made was using the 6.4 version of symfony/mime component which has the fix but it results in the same issue on the same line 
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Mime/RawMessage.php#L59

Can you advise if anything different we have to do or is it still an ongoing issue?

**Comment by bytestream** [comment]
I too am a bit bemused by https://github.com/symfony/symfony/pull/51874 & https://github.com/symfony/symfony/pull/51926. The second PR bypasses the memory fix of the first PR, by again loading the message into memory. It's easy to hit OOM if you just attach a single large file and do so using streams. When it's sending the message and writing to the smtp stream, it hit's OOM because of the code added by https://github.com/symfony/symfony/pull/51926

If someone has suggestions then I'm happy to look into implementing a fix. @fabpot ? Perhaps write to `php://temp` rather than storing in memory.
