### ISSUE TITLE
[VarDumper] Safari cannot render `dd` function in network preview window

### ISSUE THREAD

**Issue by timinigi** [symfony/symfony#51762]
### Symfony version(s) affected

6.3.0

### Description

Hello I have a similiar problem as discussed in issue #24688 but for the latest Safari version. The issue was closed but not fixed for the Safari on MacOS. 

Simply said, dd function cannot be rendered by safari network preview window. If used in page window dd funtion is rendered correctly.

### How to reproduce

- Execute a dd function
- Check the safari network preview window

**Comment by timinigi** [comment]
Any update? Thank you!

**Comment by wouterj** [comment]
I don't think this is in any way related to Symfony, just as #24688 wasn't. We return an HTML response, but Safari somehow doesn't render the HTML in the preview window.

If you find any way to make it work, a PR is welcome to fix this. But I doubt we can do anything here in the framework, so I'm closing this task for now.
