### ISSUE TITLE
[EventDispatcher] Listener argument resolver

### ISSUE THREAD

**Issue by KerianMM** [symfony/symfony#51781]
### Description

Hello,

I've noticed that in many listeners, we only use the event to get the subject, to which we apply our processing. Our tests check that the event contains our object, that it's of the right instance, and then we get to the heart of the function's actual behavior.

I think that if we could inject the subject directly, we'd gain a bit:
 - It respects the [law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) because it does not adds an extra layer (I agree it's debatable, the event isn't really an extra layer...)
- it reduces code but also tests
- business functions can become listeners by moving closer to the model

First, I thought of an ArgumentResolverInterface like the HttpKernel component, with the event, event name and dispatcher (the actual arguments) as the default resolver.
What makes me doubt this solution is the openness offered by an ArgumentResolverInterface. 

Ultimately, I just want a shortcut to event properties, not dependency injection.
Which leads me to think that an attribute on listener function parameters would be more appropriate.
An ArgumentResolverAttribute would itself determine what it wants to extract from the event and could be extended.

### Example

```php

class MyListener {
    public function preDummy(#[CustomSubjectResolver] Contract $subject /*, Event $event*/)
    {
        // This code is not necessary anymore 🔥
    	/*
        $subject = $event->getSubject();
        if (!$subject instanceof Contract) {
            throw new \RuntimeException('Not a contract');
        }
    	*/
    
        // Do my stuff
    }
}

```

**Comment by xabbuh** [comment]
closing as the related pull request has been rejected
