### ISSUE TITLE
[Messenger] Undefined constant "SIGTERM"

### ISSUE THREAD

**Issue by digilist** [symfony/symfony#51790]
### Symfony version(s) affected

6.3.5

### Description

PR #50787 introduced the usage of the \SIGTERM and \SIGINT constants in `src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php`, but these constants are only available when the pcntl extension is enabled.

So far the extension was not necessary to use the messenger (at least it worked in our environment without issues), but since upgrading to 6.3.5 the `messenger:consume` command is unable to start because of the undefined constant.

```
Exception trace:
 at /srv/www/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:261
Symfony\Component\Messenger\Command\ConsumeMessagesCommand->getSubscribedSignals() at /srv/www/vendor/symfony/console/Application.php:1003
Symfony\Component\Console\Application->doRunCommand() at /srv/www/vendor/symfony/framework-bundle/Console/Application.php:91
Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/www/vendor/symfony/console/Application.php:320
Symfony\Component\Console\Application->doRun() at /srv/www/vendor/symfony/framework-bundle/Console/Application.php:80
Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/www/vendor/symfony/console/Application.php:174
Symfony\Component\Console\Application->run() at /srv/www/bin/console:42
```

### How to reproduce

Make sure the pcntl extension is not enabled and run the `messenger:consume` command. It fails immediately.

**Comment by xorgxx** [comment]
Hi just update all Symfony and it since i having the same issue. 

php8.2 - SF6.3 - messenger6.3.5
- Upgrading symfony/messenger (v6.3.4 => v6.3.5)

Regards

**Comment by nicolas-grekas** [comment]
We need to make this line conditional, using `defined()`. We already to so in other parts but we forgot about it.

**Comment by nicolas-grekas** [comment]
PR welcome!

**Comment by HypeMC** [comment]
Sorry about this one, see #51791

**Comment by janklan** [comment]
In the meantime, adding PCNTL fixes the problem. On `php:8.2-fpm-alpine`, this worked for me:

```
RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install \
    pcntl
```

I wonder: Is there any reason to have or not have this extension present? I made it this far without ever needing it. Can the wider Symfony ecosystem benefit from it somehow?

**Comment by lordjancso** [comment]
> I wonder: Is there any reason to have or not have this extension present? I made it this far without ever needing it. Can the wider Symfony ecosystem benefit from it somehow?

That is a really good question. I hope someone will answer.

**Comment by stof** [comment]
On Linux, it is recommended to have it (it is the only way to support proper signals for commands, which is quite important for a long-running consumer).
However, we must keep it optional (which has been solved in the dev version for the upcoming release) because the pcntl extension does not exist on Windows.

**Comment by derrabus** [comment]
Symfony 6.3.6 should fix this issue.
