### ISSUE TITLE
[HttpFoundation] unset `Request` properties within `initialize()` will cause issue on any extended Request implementing `__isset()` and `__get()`

### ISSUE THREAD

**Issue by crynobone** [symfony/symfony#51792]
### Symfony version(s) affected

7.0.0

### Description

Laravel Framework is preparing support for Symfony 7 for the upcoming Laravel 11 (target release Q1 2024) and based on our existing tests the usage such as `protected string $baseUrl` and using `unset($this->baseUrl)` will cause issues for `Illuminate\Http\Request` as this class extends `Symfony\Component\HttpFoundation\Request` and also implements `__isset()` and `__get()`.

### How to reproduce

The issue can be seen via our GitHub Actions: https://github.com/laravel/framework/actions/runs/6361912914/job/17276631512

To make it easier to understand, here is a simplified version of the usage:

```php
class SymfonyRequest 
{
  protected string $baseUrl;

  public function __construct() 
  {
    unset($this->baseUrl);
  }

  public function getPathInfo()
  {
    if (null === ($baseUrl = $this->getBaseUrlReal())) {
      return 'http://localhost';
    }
    
    assert($baseUrl === 'foo', 'BaseURL should be `foo` from `prepareBaseUrl()` but instead is `'.$baseUrl.'`');

    return 'http://laravel.com';
  }

  private function getBaseUrlReal(): string
  {

    return $this->baseUrl ??= $this->prepareBaseUrl();
  }

  protected function prepareBaseUrl(): string
  {
    return 'foo';
  }
}

class LaravelRequest extends SymfonyRequest
{
    public function path() {
      return $this->getPathInfo();
    }

    public function __isset($key)
    {
      return ! is_null($this->__get($key));
    }
    
    public function __get($key)
    {
      if ($key === 'baseUrl') {
        return 'bar';
      }

      return null;
    }
}

$a = new LaravelRequest();

$a->path();
```

![CleanShot 2023-10-01 at 11 00 07](https://github.com/symfony/symfony/assets/172966/85ee5164-51ce-4f75-85ec-a89b46678292)

### Possible Solution

One possible solution is to opt for the following:

```diff
- protected string $baseUrl;
+protected ?string $baseUrl;
```

and set to null instead of unset.

```diff
-unset($this->baseUrl);
+$this->baseUrl = null;
```

### Additional Context

Without the above change, any extended Request class similar to Laravel would need to look into exposing Symfony Request via `__isset()` and `__get()` which might not be ideal.

**Comment by derrabus** [comment]
Please send a PR.

**Comment by stof** [comment]
The unset variable is there to lazy-load that variable on reading. Making that nullable will actually break things entirely because the lazy-loading won't happen.

**Comment by stof** [comment]
The child class needs to properly call the parent methods for `__isset` and `__get`

**Comment by crynobone** [comment]
> The child class needs to properly call the parent methods for __isset and __get

But wouldn't that expose Symfony's Request protected properties within child Request via `__isset` and `__get`? 

For example:

```php
$symfonyRequest = Request::create();

$laravelRequest = LaravelRequest::create();

$symfonyRequest->baseUrl // is not possible since it's protected property.
$laravelRequest->baseUrl // is possible since it's accessed via `__get()`
```

**Comment by stof** [comment]
hmm, looking at those, it seems like those properties are not actually lazy-loaded on reads on them.

@nicolas-grekas I think unsetting them (in https://github.com/symfony/symfony/pull/51121) instead of making them nullable was a mistake given that in 6.4, a child class would see them as `null` before the getter is called and as uninitialized in 7.0. Or maybe they should become private.

**Comment by nicolas-grekas** [comment]
Should be fixed by #51812

**Comment by driesvints** [comment]
Thanks for the swift response/action here all! 🙂

**Comment by crynobone** [comment]
Submit an additional PR: https://github.com/symfony/symfony/pull/51887

Failing Tests: 

![CleanShot 2023-10-08 at 09 50 15](https://github.com/symfony/symfony/assets/172966/84d103aa-c396-4974-bcd7-11ebd7ae0e43)
