### ISSUE TITLE
[Serializer] DateTimeNormalizer throws exception while working with Unix timestamp

### ISSUE THREAD

**Issue by DimDev** [symfony/symfony#51798]
### Symfony version(s) affected

6.2.10 and higher

### Description

The DateTimeNormalizer component throws NotNormalizableValueException if the target class contains the \DateTimeInterface property and json contains Unix timestamp.

`PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The data is either not an string, an empty string, or null; you should pass a string that can be parsed with the passed format or a valid DateTime string. in /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Exception/NotNormalizableValueException.php:31
Stack trace:
#0 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/DateTimeNormalizer.php(87): Symfony\Component\Serializer\Exception\NotNormalizableValueException::createForUnexpectedDataType()
#1 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Serializer.php(227): Symfony\Component\Serializer\Normalizer\DateTimeNormalizer->denormalize()
#2 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php(432): Symfony\Component\Serializer\Serializer->denormalize()
#3 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(598): Symfony\Component\Serializer\Normalizer\AbstractNormalizer->denormalizeParameter()
#4 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php(364): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalizeParameter()
#5 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(244): Symfony\Component\Serializer\Normalizer\AbstractNormalizer->instantiateObject()
#6 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(323): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->instantiateObject()
#7 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Serializer.php(227): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize()
#8 /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Serializer.php(145): Symfony\Component\Serializer\Serializer->denormalize()
#9 /home/developer/symfony/serilizer-bug/serilizer-bug.php(44): Symfony\Component\Serializer\Serializer->deserialize()
#10 {main}
  thrown in /home/developer/symfony/serilizer-bug/vendor/symfony/serializer/Exception/NotNormalizableValueException.php on line 31`

### How to reproduce

composer.json
```json
{
    "require": {
        "symfony/serializer": "6.2.10",
        "symfony/property-access": "6.2"
    }
}
```

Reproducer
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor;
use Symfony\Component\Serializer\Normalizer\PropertyNormalizer;

final class TestDto
{
    public function __construct(
        public readonly \DateTimeInterface $date,
    ) {
    }
}


$serilizer = new Serializer(
    normalizers: [
        new PropertyNormalizer(
            propertyTypeExtractor: new PropertyInfoExtractor(
                typeExtractors: [
                    new ConstructorExtractor()
                ]
            ),
        ),
        new DateTimeNormalizer(
            defaultContext: [
                DateTimeNormalizer::FORMAT_KEY => 'U',
            ]
        ),
    ],
    encoders: [
        new JsonEncoder()
    ]
);

$testDto = $serilizer->deserialize(
    '{"date": 1666369508}',
    TestDto::class,
    'json'
);

var_dump($testDto);

```

**Comment by xabbuh** [comment]
Symfony 6.2 is not maintained anymore. Do you still experience it with the latest 6.3 patch release?

**Comment by DimDev** [comment]
Hi @xabbuh 

Yes, my tests caught the issue after upgrading from ^6.2 to ^6.3

**Comment by xabbuh** [comment]
Looking at the code I don't see how this could ever have worked.

What you can do however is to pass the context to the `deserialize()` call like this:

```php
$testDto = $serilizer->deserialize(
    '{"date": 1666369508}',
    TestDto::class,
    'json',
    [
        DateTimeNormalizer::FORMAT_KEY => 'U',
    ]
);
```

**Comment by DimDev** [comment]
@xabbuh , thanks for the provided workaround.

Nevertheless, since the "DateTimeNormalizer::FORMAT_KEY => 'U'," has been already defined as defaultContext, it's expected it will be taken into consideration while denormalizing.

**Comment by mtarld** [comment]
Indeed, it is an actual bug here. I created a PR aiming to fixing it.
