### ISSUE TITLE
Symfony secrets override not working in case of empty and null value

### ISSUE THREAD

**Issue by hanishsingla** [symfony/symfony#51807]
### Symfony version(s) affected

6.3.0

### Description

Secrets can be overridden by environmental variables as mentioned in https://symfony.com/doc/current/configuration/secrets.html#referencing-secrets-in-configuration-files

If you need some different values on your local machine you can also create a local secret, which will in turn update .env.{env}.local file
https://symfony.com/doc/current/configuration/secrets.html#local-secrets-overriding-secrets-locally

But since 6.3 release, this behavior is broken if you are overriding a secret value with an empty value or null

### How to reproduce

1. Create a secret value with `php bin/console secrets:set DATABASE_PASSWORD`
2. Override this secret value with help of .env file, to a null or empty string value
3. Set this secret/env to a parameter as mentioned in https://symfony.com/doc/current/configuration/secrets.html#referencing-secrets-in-configuration-files
4. Check secret value `php bin/console secrets:list --reveal`
5. Check parameter value in controller

### Possible Solution

This bug is introduced by https://github.com/symfony/symfony/pull/48705/files

### Additional Context

Possible link to
https://github.com/symfony/symfony/issues/50094
https://github.com/symfony/symfony/pull/50101
https://github.com/symfony/symfony/pull/48705
https://github.com/symfony/symfony/pull/50301
https://github.com/symfony/symfony/pull/50712

**Comment by nicolas-grekas** [comment]
Yes, as described in #48705, this is the desired behavior. I'm sorry it breaks your workflow but I don't think we can revert this now. Can you find a way around (like using another value instead of the empty string?)

**Comment by hanishsingla** [comment]
Sure, I can find a workaround, but is there any reasoning why allowing empty/null values is a bad thing so that anyone else with such a case can also understand why it's a bad DX? IMHO, there should be a way to set such values for your local e.g. you don't have some third-party key for your local machine and you would want to skip process based on availability of key

**Comment by nicolas-grekas** [comment]
What's written in the PR description: we want empty env vars in .env files to be overrideable.
