### ISSUE TITLE
[Messenger] Requeue failed retries

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#51815]
### Description

Given `messenger:failed:retry`, it seems sane if a retry failure is put back on the failure queue, till either manually deleted or the retry succeeds.

I tried using a recursive failure transport:

```yaml
failed:
  dsn: ...
  failure_transport: failed
```

but it didnt make any changes.

**Comment by fabpot** [comment]
I fully agree!

**Comment by nicolas-grekas** [comment]
Eventually closed in #63275

**Comment by pmishev** [comment]
But that PR doesn't really solve the original issue, does it?

It only allows you to specify a different `failure_transport` to your `failure_transport`. I don't think this change stops you from doing recursive definitions, such as failed2 being the failure_transport for failed1 and failed1 being the one for failed2, does it?

I think https://github.com/symfony/symfony/pull/51848 was the correct fix and it should never have been reverted in https://github.com/symfony/symfony/issues/53216.

You should be able to have a recursive failure_transport definition if you want to.
If you get an infinite loop with no delay, that's rather a problem in how you handle your failed messages - if you're going to automate the handling of failed messages, then don't define recursive failure_transport, or have a better retry mechanism.
It should be the developer's decision on whether they want a recursive failure_transport or not.

In my case, I only handle failed messages manually and I never want to lose any message, unless I manually drop it - that should really be the most fundamental thing to be able to support out-of-the-box. But now it's only possible via complex workarounds involving custom middleware and subscribers.
