### ISSUE TITLE
[RFC][Uid] Add interface for Uuid

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#51820]
### Description

Currently, the top level class for Uuid in the ```symfony/uid``` component is ```AbstractUid``` (https://github.com/symfony/uid/blob/6.4/AbstractUid.php)

```php
abstract class AbstractUid implements \JsonSerializable, \Stringable
{
    ...
}
```

The idea would be to add an interface for this. It would become :

```php
abstract class AbstractUid implements UuidInterface
{
    ...
}
```

and

```php
interface UuidInterface extends \JsonSerializable, \Stringable
{
    ...
}
```

(I can create the PR if we agree for this change.)

**Comment by nicolas-grekas** [comment]
Can you expand on the expected benefits? Personally I usually don't see the point of interfaces for value objects.

**Comment by AurelienPillevesse** [comment]
The idea behind this change is to implement something similar to this : 

```php
class Foo {
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private UuidInterface|string $id;

    //...

    public function __construct(UuidInterface|string $id = null)
    {
        if (null === $id) {
            $id = Uuid::v4();
        }
    }
}
```

**Comment by derrabus** [comment]
All right, but that does not answer Nicolas' question, I guess. Why wouldn't I want to use the actual `Uuid` class in your scenario?

**Comment by AurelienPillevesse** [comment]
I used ```ramsey/uuid``` before and it was to have something similar. I will try with ```Uuid``` as suggested.
