### ISSUE TITLE
"State of Palestine" instead of "Palestinian Territories" as specified by UN

### ISSUE THREAD

**Issue by alexxandres** [symfony/symfony#51824]
### Symfony version(s) affected

4.4 / 5.4 / 6.3 at least

### Description

The official UN name of the country is "State of Palestine". It should be changed to this name instead of "Palestinian Territories".

### How to reproduce

In the vendor (4.4): vendor/symfony/intl/Resources/data/regions/en.json

### Possible Solution

Update the name

### Additional Context

https://www.un.org/en/about-us/non-member-states

**Comment by stof** [comment]
This data comes from the CLDR project: https://cldr.unicode.org/

That's where you should contribute a fix (if we edit the files manually in Symfony, the change would be lost on the next sync from upstream)

**Comment by alexxandres** [comment]
OK, thank you, I will open a ticket there.
