### ISSUE TITLE
Type "?array|string|null" is a union type, and therefore cannot be also marked nullable with the "?" prefix

### ISSUE THREAD

**Issue by glo71317** [symfony/symfony#51842]
### Symfony version(s) affected

v6.3.4

### Description

We are planning to update LTS Symfony version in adobe commerce in upcoming release, Hence we are updating 
latest dependency of symfony:6:3.x but after updating we are getting some issue.
**Issue** - Type "?array|string|null" is a union type, and therefore cannot be also marked nullable with the "?" prefix

After analysis we found the RCA and below method is causing the issue:
https://github.com/symfony/console/blob/6.3/Command/Command.php#L475-L497

As added union type for **shortcut and default**  in https://github.com/symfony/console/blob/6.3/Input/InputOption.php#L54 and using as method parameter for shortcut as `string|array $shortcut = null` and for default as `mixed $default = null`

As per devdoc - https://php.watch/versions/8.0/union-types, we can use Nullable types (?TYPE) and null must not be mixed.

### How to reproduce

Irrelevant

### Possible Solution

If change type of shortcut as mixed https://github.com/symfony/console/blob/6.3/Command/Command.php#L487 same as type default method parameter.
Orginal Code - 
> public function addOption(string $name, **string|array $shortcut = null**, int $mode = null, string $description = '', mixed $default = null /* array|\Closure $suggestedValues = [] */): static

Proposed:

> public function addOption(string $name, **mixed $shortcut = null,** int $mode = null, string $description = '', mixed $default = null /* array|\Closure $suggestedValues = [] */): static

**Comment by wouterj** [comment]
Hi! I can't find the type `?array|string|null` anywhere in the codebase, which is logical given it indeed is not a valid type. The error message doesn't also appear to be from PHP.

Broading the type to something less specific doesn't sound like a good solution, we know shortcut must be either null, an array or string (whereas default can be anything the user wants, which is why `mixed` is the only applicable solution).

Can you please create a [minimal reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) that shows this error?

**Comment by glo71317** [comment]
Hi @wouterj, As you may know in Adobe commerce, during compiling the code the files generated for magento performance with help of [laminas/laminas-code](https://github.com/laminas/laminas-code). 

During compilation it is finding the union Type issue  - https://github.com/laminas/laminas-code/blob/4.13.x/src/Generator/TypeGenerator.php#L104-L108
<img width="450" alt="Screenshot 2023-10-03 at 3 19 24 PM" src="https://github.com/symfony/symfony/assets/85922880/da8a2ba8-1f7d-4108-b4dc-9a49052b712e">
<img width="690" alt="Screenshot 2023-10-03 at 4 10 21 PM" src="https://github.com/symfony/symfony/assets/85922880/72f79dbf-ad2f-4695-994c-1bae46c5c1f1">
Will try to reproduce with custom sample code tomorrow and create [minimal reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) that shows this error?

**Comment by wouterj** [comment]
Hmm, it looks like this is then caused by code in the magento / Adobe commerce software (I don't know much about those tools btw). It is somehow converting `string|array $shortcut = null` to `?string|array|null`.

You might have better luck reporting this to the tool executing the code generation.

**Comment by glo71317** [comment]
@wouterj thanks i am closing the issue, Hence we are fixing the issue at our end.
