### ISSUE TITLE
Non-existent service "Symfony\Component\Cache\Marshaller\SodiumMarshaller.inner"

### ISSUE THREAD

**Issue by JFO-SNPS** [symfony/symfony#51856]
### Symfony version(s) affected

6.3.5

### Description

I followed the symfony online documentation to add session and cache encryption using sodium marshaller:
https://symfony.com/doc/current/session.html#encryption-of-session-data

But i get this error :
```
The service "App_Session_Crypt" has a dependency on a non-existent service   
"Symfony\Component\Cache\Marshaller\SodiumMarshaller.inner". 
```

Here is my service.yaml :
```
    App_Session_Crypt:
        class: Symfony\Component\Cache\Marshaller\SodiumMarshaller
        decorates : 'session.marshaller'
        arguments :
            - [ '%env(base64:SESSION_DECRYPTION_KEY)%' ]
            - '@Symfony\Component\Cache\Marshaller\SodiumMarshaller.inner'
            # Mettre à jour SESSION_DECRYPTION_KEY dans le fichier .env.{env} avec: php -r 'echo base64_encode(sodium_crypto_box_keypair());'
    App_Cache_Crypt:
        class: Symfony\Component\Cache\Marshaller\SodiumMarshaller
        decorates : 'cache.default_marshaller'
        arguments :
            - [ '%env(base64:CACHE_DECRYPTION_KEY)%' ]
            # Mettre à jour CACHE_DECRYPTION_KEY dans le fichier .env.{env} avec: php -r 'echo base64_encode(sodium_crypto_box_keypair());'
            - '@Symfony\Component\Cache\Marshaller\SodiumMarshaller.inner'
```

This method works until few hours ago, before i make console cache:clear.
The spécified class is present in my vendors.

Sincerely

### How to reproduce

I don't know ^^

**Comment by xabbuh** [comment]
The id of the decorated service to inject depends on the id of your decorating service. In your case you need to use `@ App_Session_Crypt.inner`.

**Comment by nicolas-grekas** [comment]
Or just `@.inner` :) Can you please send a PR to the doc to use this new syntax?

**Comment by JFO-SNPS** [comment]
Yes the two solutions works pretty well, but i'm not sure to really understand why.

**Comment by xabbuh** [comment]
@JFO-SNPS When you define a service decorating another service and you want to inject the decorated service you have two possibilities to reference that inner service:

* use the id of your own service definition and append `.inner` (that's the solution I mentionend in https://github.com/symfony/symfony/issues/51856#issuecomment-1748997563)
* simply use `.inner` as the id of the inner service, this is a special id that is indepentent from the id of the decorating service and more flexible (thus the best practice)
