### ISSUE TITLE
Broken link in stimulus-bundle repo

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#51883]
### Symfony version(s) affected

all

### Description

This link does not exist: https://symfony.com/bundles/stimulus-bundle

![image](https://github.com/symfony/symfony/assets/619585/042c8d1b-e979-4b72-915b-a65324540876)

Kudos on the adding the TwigComponent namespaces!

### How to reproduce

Go to https://github.com/symfony/stimulus-bundle

**Comment by magikid** [comment]
The URL should be https://symfony.com/bundles/StimulusBundle/

**Comment by nicolas-grekas** [comment]
Fixed!
