### ISSUE TITLE
[Validator] Url validator don't accept file scheme with empty hostname

### ISSUE THREAD

**Issue by miranovy** [symfony/symfony#51908]
### Symfony version(s) affected

6.3.4

### Description

Url validator don't accept file scheme with empty hostname.

### How to reproduce

```php
$this->getValidator()->validate(
   'file:///path',
   new Url(null, null, ['file'], false),
   null
)
```

return `ConstraintViolation` with message `This value is not a valid URL.` but value `file:///path` (empty hostname) is a valid uri (see https://en.wikipedia.org/wiki/File_URI_scheme)

**Comment by stof** [comment]
The constraint is named `Url`, not `Uri`. So I would not say that this is a bug.

**Comment by OskarStark** [comment]
> The constraint is named Url, not Uri. So I would not say that this is a bug.

The modified tests in the PR show, that we also support `ftp` and others
