### ISSUE TITLE
[HttpKernel] ErrorListener::onKernelException should ignore exception thrown after `kernel.terminate`

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#51912]
### Symfony version(s) affected

all

### Description

Related to https://github.com/symfony/symfony/issues/45205 issue, which was ignored...

When an exception is thrown in a `kernel.terminate` event,
- `kernel.exception` is thrown
- the Symfony ErrorListener::onKernelException handler the exception
- `$response = $event->getKernel()->handle($request, HttpKernelInterface::SUB_REQUEST, false);` is called
- this trigger the `ErrorController` and then the `TwigErrorRenderer`

1) The response rendered seems useless since the response was already sent before the terminate event. (cf https://symfony.com/doc/current/components/http_kernel.html#8-the-kernel-terminate-event) 
2) It can produce extra-useless exception, in my case I have a custom view `TwigBundle/Exception/error.html.twig`
which use the session and/or flashbag and I'm getting some `Failed to start the session because headers have already been sent`.

Introducing a `kernel.terminate_exception` and using it instead of `kernel.exception` could even appear as a BC break for `kernel.exception` listeners or a bugfix because according to the schema in the doc https://symfony.com/doc/current/components/http_kernel.html#handling-exceptions-the-kernel-exception-event, we can see the order `Exception -> Response -> Terminate`.

### How to reproduce

- Throw an exception in a `kernel.terminate` listener -> You'll get extra code executed for no reason
- Add `app.session.flashbag.get('success')` call in a custom `TwigBundle/Exception/error.html.twig` template. -> You'll get failed to start the session error in your logs.

### Possible Solution

Either throw a different event for exception thrown after the terminate exception

Either, at least provide a `ExceptionEvent::isTerminated` or `TerminableInterface::isTerminated`, which would allow to write
```
if ($thing->isTerminated()) {
     return;
}
```
at the beginning of some ExceptionListener like the ErrorListener

**Comment by fancyweb** [comment]
The current logic might actually be "OK" enough.
When `fastcgi_finish_request()` is not called, then the extra response and exception are actually output and are useful.
Also, I'm pretty sure some people rely on the current logic without knowing it :sweat_smile:

**Comment by VincentLanglet** [comment]
> The current logic might actually be "OK" enough. When `fastcgi_finish_request()` is not called, then the extra response and exception are actually output and are useful. 
> Also, I'm pretty sure some people rely on the current logic without knowing it 😅

That's why I proposed adding a `isTerminated` method and calling in the `ErrorListener` to early return in order to avoid BC break as much as possible. People customer listeners won't be impacted. Only the `ErrorListener` would be.

But maybe things should be thought differently:
If the `fastcgi_finish_request` call finish the request, there is no need to try rendering a view anymore no ?
What about an early return
```
if (headers_sent()) {
        return;
}
```
somewhere in the `ErrorListener` or `TwigErrorRenderer` ?

**Comment by nicolas-grekas** [comment]
On my side I think #52047 is the way to go.

> adding a isTerminated method and calling in the ErrorListener to early return

Why not, but then this creates an opportunity to hide errors, so at least the early return should also check if we're in debug mode, and skip the exception only if not.

> if (headers_sent()) {

nope, that's too hacky.

**Comment by VincentLanglet** [comment]
> On my side I think #52047 is the way to go.
> 
> > adding a isTerminated method and calling in the ErrorListener to early return
> 
> Why not, but then this creates an opportunity to hide errors, so at least the early return should also check if we're in debug mode, and skip the exception only if not.

Something like this https://github.com/symfony/symfony/pull/52128 ?
