### ISSUE TITLE
[PropertyAccess][VarExporter] `PropertyAccessor::isReadable()` triggers an error when called on a lazy object’s missing property

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#51919]
### Symfony version(s) affected

≥ 6.2

### Description

Calling `PropertyAccessor::isReadable()` on a lazy object’s missing property will trigger an error, even if the object is fully loaded.

This is because `PropertyAccessor::getReadInfo()` will return the property as public as its class has a `__get` method, and trying to access it will call `trigger_error`: https://github.com/symfony/symfony/blob/3147082e35faadd873a801a4011bc8cbb79807e0/src/Symfony/Component/VarExporter/LazyGhostTrait.php#L193
### How to reproduce

Call `PropertyAccessor::isReadable()` on a lazy object’s (like a Doctrine proxy) missing property. Instead of `false`, you’ll get an `ErrorException`.

**Comment by nicolas-grekas** [comment]
Could you please submit a PR with a failing test case? That'd help a lot here. :pray:

**Comment by nicolas-grekas** [comment]
Possibly fixed by #54194, please confirm if you can.

**Comment by MatTheCat** [comment]
I confirm your PR makes #54068’s test pass :tada:  Guess I can close it!
