### ISSUE TITLE
AssetMapper and serving  own assets uploaded to a private CDN (like cloudfont)

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#51980]
### Description

Context: 

currently we're on symfony 6.3 and we use symfony encore and we upload our assets on AWS's cloudfront on a separate domain. Our backend is running on AWS' lambda with Bref.sh 

As we have a very limited use of javascript, we're very excited to the idea of dropping Encore and simplify our build system, but one question remain: how do we use it with our CDN ?

https://symfony.com/doc/current/frontend/asset_mapper.html#mapping-assets the documentation seems to miss a way on how to configure the map to a external domain, is it a missing feature or a missing part in the documentation ?

### Example

I would like 

```
<img src="{{ asset('images/duck.png') }}">
```
to generate 

```
<img src="assets.example.com/assets/images/duck-3c16d9220694c0e56d8648f25e6035e9.png">
```

**Comment by allan-simon** [comment]
an alternative would be to use cloudflare instead of cloudfront (we actually also use it) but then I would need a production way to serve the assets from symfony (as there's no nginx running in lambda)  so that it then get cached by cloudflare with the right configuration ? (i.e each time the assets are updated, they are served once un-optimally by the php and then it gets in the long-expiration public cache of cloudflare ? )

**Comment by stof** [comment]
when using AssetMapper, you still serve assets through the Asset component (AssetMapper hooks in it). So it should work with the configuration to make it use a base URL: https://symfony.com/doc/current/reference/configuration/framework.html#reference-assets-base-urls

The build/deployment process would run `asset-map:compile` to generate the static files and upload them to your CDN.

**Comment by weaverryan** [comment]
Stof's approach is exactly what I was imagining. If this doesn't work for some reason, let us know. But perhaps we can document this :)

> an alternative would be to use cloudflare instead of cloudfront (we actually also use it) but then I would need a production way to serve the assets from symfony (as there's no nginx running in lambda) so that it then get cached by cloudflare with the right configuration ? (i.e each time the assets are updated, they are served once un-optimally by the php and then it gets in the long-expiration public cache of cloudflare ? )

That last part isn't quite true, fortunately :). When you deploy, you run an `assetmap:compile` command. This, like Encore, writes 100% of the files you'll need to a `public/assets/` directory. So, on production, there is no PHP involved at all to serve your assets. But you're right that something still needs to be able to serve these static files and I'm a lambad novice  :p.

**Comment by allan-simon** [comment]
> That last part isn't quite true, fortunately :). When you deploy, you run an assetmap:compile command.

Yes I do know that :)  hence my 

>  I would need a production way to serve the assets from symfony 


I.e I would need to have the way assets are served in dev mode, in production mode,  so that I limit the time taken during the Continuous Deployment phase (currently it takes two minutes to run both `encore` and the `aws s3 cp` , so having them served "just in time"  would decrease substantially our time to prod, and as we deploy 10 to 20 times a day, those minutes starts to add up )

**Comment by weaverryan** [comment]
Using the dev server on production isn’t the intended use, but it’s not dangerous. So, it could indeed work - you can activate it on production. Does that help?

**Comment by allan-simon** [comment]
yes that was my main concern, i.e "am I opening a pandora box by activating it in production ?" , thanks for the precision

**Comment by weaverryan** [comment]
I'm going to close this. If we have some concrete issues, let's open a new PR.

Cheers!

**Comment by allan-simon** [comment]
I've hit an issue there https://github.com/symfony/symfony/issues/52561
