### ISSUE TITLE
Cannot replace arguments for class "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener" if none have been configured yet.

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#52041]
### Symfony version(s) affected

6.4.dev

### Description

Bug after composer update

### How to reproduce

After update, 2 hours ago, this error message : 
```Cannot replace arguments for class "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener" if none have been configured yet.```
Search and look my files...

Create new app:  symfony new --version=dev test

Copy my file composer json and remove one by one, the components. 
Result :
[composer.json](https://github.com/symfony/symfony/files/12892230/composer.json)
And always error message
![Capture d’écran du 2023-10-13 11-58-13](https://github.com/symfony/symfony/assets/127077166/4c36ac43-a55d-4817-9dbe-d70dd0787ae3)
Solution ? please

**Comment by xabbuh** [comment]
Thank you for reporting. This has been fixed in #52023 which was merged into the `6.3` branch. I merged it up so 6.4 should be good now too.
