### ISSUE TITLE
BackedEnumValueResolver fails to resolve \IntBackedEnum when passing string

### ISSUE THREAD

**Issue by ozahorulia** [symfony/symfony#52053]
### Symfony version(s) affected

6.3.5

### Description

If I pass a string as the value for an `\IntBackedEnum` controller argument with `MapQueryParameter` attribute and `BackedEnumValueResolver` resolver, symfony generates a `\TypeError` exception.

### How to reproduce

Controller:
```php
#[Route('/category/{category}', name: 'list_category', methods: ['GET'])]
public function listAction(
    #[MapQueryParameter(resolver: BackedEnumValueResolver::class)] CategoryEnum $category = null,
): Response {
}
```

CategoryEnum:

```php
enum ArtistRank: int
{
    case FOO = 1;
    case BAR = 2;
}
```

### Possible Solution

Create separate resolvers for \IntBackedEnum and \StringBackedEnum

OR

Catch `\TypeError` along with the `\ValueError` in `BackedEnumValueResolver` and throw `NotFoundHttpException`

OR

Use `tryFrom` instead of `try` in `BackedEnumValueResolver` (probably a bad idea, because it will return null

### Additional Context

I can avoid this by using requirements in the router description like this:

```php
requirements: ['category' => new EnumRequirement(CategoryEnum::class)],
```

But this makes the route attribute unnecessary huge and less readable

**Comment by derrabus** [comment]
Please send a PR for option 2.

**Comment by ozahorulia** [comment]
I will do it in a few days, thanks.

**Comment by makmaoui** [comment]
Hi @ozahorulia,
If you are agree, i would like to work on PR to fix this issue

**Comment by ozahorulia** [comment]
@makmaoui Hi! I'm sorry, unfortunately, I didn't find spare time for this PR. You are welcome to take this one over :)
