### ISSUE TITLE
env variable is being overriden even when override is disabled

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#52073]
### Symfony version(s) affected

6.3.x

### Description

Faced issue that env. variables are being overridden by sequential files even if `$overrideExistingVars=false`

### How to reproduce

```
<?php

use Symfony\Component\Dotenv\Dotenv;

require_once './vendor/autoload.php';

$projectDir = __DIR__;

$files = array_reverse(array_filter([
    $projectDir.'/.env',
    $projectDir.'/.env.local'
], 'file_exists'));

dump($files); // order of loading .env.local -> .env
(new Dotenv())->load(...$files); // using doLoad with  $overrideExistingVars = false
dd($_SERVER['EMAIL_SENDER_MAIL'], $_ENV['EMAIL_SENDER_MAIL']);
// ER: `foobar` because .env.local has higher priority
// AR: <empty>
```

```
# .env
EMAIL_SENDER_MAIL=
```

```
# .env.local
EMAIL_SENDER_MAIL=foobar
```

### Possible Solution

Related task https://github.com/symfony/symfony/commit/08291b1665a96c77a6516ac52c4a100135e7061f

if stmt should be like:

```php
            if (
                !$overrideExistingVars // checking if opt-in into override
                && (isset($loadedVars[$name]) || isset($_ENV[$name])) // checking that variable exists
            ) {
                continue;
            }
```

**Comment by oleg-andreyev** [comment]
Related task https://github.com/symfony/symfony/commit/08291b1665a96c77a6516ac52c4a100135e7061f

if stmt should be like:

```php
            if (
                !$overrideExistingVars // checking if opt-in into override
                && (isset($loadedVars[$name]) || isset($_ENV[$name])) // checking that variable exists
            ) {
                continue;
            }
```

**Comment by nicolas-grekas** [comment]
Env vars defined in `.env.local` always win over ones declared in `.env`.
`$overrideExistingVars` is only about real env vars, not the ones defined in various `.env` files.

**Comment by oleg-andreyev** [comment]
I had this feeling that this parameter only applies for variables defined/declared in scope of current process.

Quite misleading name IMO or missing documentation.

**Comment by oleg-andreyev** [comment]
I'm not using all the logic with .local because we have multi-tenant application and we have:


```
.env
.env.local
.env.<env>
.env.<env>.local
.env.<application>
.env.<application>.local
.env.<application>.<env>
.env.<application>.<env>.local
```

Thus we start from most specific (last in list) to more generic (first in list)

And what was my surprise that variable is overridden by less-specific file.

**Comment by nicolas-grekas** [comment]
Closing then, things are as expected.
There are some hints in this file, which is made available to new Symfony projects:
https://github.com/symfony/recipes/blob/main/symfony/flex/1.0/.env

PR welcome to improve the doc!

**Comment by oleg-andreyev** [comment]
@nicolas-grekas created PR for README with a note.
