### ISSUE TITLE
[Cache] Temporary files not cleaned from filesystem

### ISSUE THREAD

**Issue by cedric-anne** [symfony/symfony#52092]
### Symfony version(s) affected

5.x, 6.x

### Description

On an open source PHP application I work on, we sometimes have issues reported by administrators related to unexpected filesystem saturation. The impacted cache namespace is supposed to contains only a dozen of items, but the directory contains 250k files located at its root. These files are temporary files generated when a cache entry is updated, and are supposed to be removed automatically.

The problem is that the target file is exists, contains stale information, but is not writable.

First, let's resume what is done by the Filesystem apadter when a cache entry is written:
1. a temporary file is created at the root of the cache directory;
2. content is written inside this file;
3. this file is renamed to its target path, using the PHP `rename()` function.

Related code: https://github.com/symfony/symfony/blob/d69ab75aa386f3135130bb7becf767c06dd067bf/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php#L88-L114

Now, let's see what the `rename()` function do:
1. the file is copied to its target path;
2. the ownership of the target file is updated;
3. the mod of the target file is updated;
4. the source file is deleted.

If any of the 3 first steps fails, the unlink is not done.

Related code: https://github.com/php/php-src/blob/221b4fe246e62c5d59f617ee4cbe6fd4c614fb5a/main/streams/plain_wrapper.c#L1272-L1371

### How to reproduce

1. Create a cache entry with a short lifetime (1s).
2. Make the corresponding file read-only on the filesystem.
3. Update the cache entry.

-> The temporary file created on the cache directory root is not deleted.

### Possible Solution

On Symfony 4.4, a cleaning operation was always done after the rename, see #39059. I think it could be simple to put back this cleaning operation, to prevent filesystem saturation.

**Comment by cedric-anne** [comment]
My bad, one of the target file was existing but was not writable. I thought an exception would be triggered, but it is in fact catched internally by Symfony.

I will update the main description.

**Comment by nicolas-grekas** [comment]
Could you please send a PR if you have a fix in mind?

**Comment by cedric-anne** [comment]
> Could you please send a PR if you have a fix in mind?

I will do.
