### ISSUE TITLE
How to drop `Mailer/Sendinblue` and `Notifier/Sendinblue`

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#52097]
Sendinblue was rebranded to Brevo and we already have bridge for them.

I would simply drop those bridges in 7.0 and abandon the packages on 6.4 with a replacement to the brevo bridge. It is a 1:1 drop-in replacement

WDYT @stof @fabpot @nicolas-grekas

**Comment by OskarStark** [comment]
I talked to Nicolas via Slack, and we do it the proposed way 👍

**Comment by stof** [comment]
The sendinblue bridges already trigger deprecations in 6.4 when the factories are used to create a transport. So marking the packages as abandoned on Packagist after the 6.4 stable release is the way to go, and those packages should not exist in 7.0

**Comment by OskarStark** [comment]
Already fixed in
* https://github.com/symfony/symfony/pull/50917
* https://github.com/symfony/symfony/pull/50916
