### ISSUE TITLE
Suggestion: Remove `v` from version numbers (e.g. `6.3.5` instead of `v6.3.5`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#52135]
### Description

IMO, this just adds noise to the output of `composer show`. And since it's always clear that these numbers denote the *version*, there's no need to "label" them with the `v` prefix.

**Comment by stof** [comment]
Having tags prefixed with `v` actually helps a lot when contributing to Symfony and relying on git completion to switch branch: writing `git checkout 6.` and then triggering completion will suggest me only the few branches and not 200 tags for all the 6.x releases.
So I would not remove the prefix from tag names.

If the `v` prefix bothers you in the `composer show` output, you might try to suggest a feature to composer to allow hiding it (as composer treats it as optional for tag names) but they might decide it is not worth it.

**Comment by derrabus** [comment]
I don't think that this bit of visual noise justifies a crusade against the `v` in all projects that use it in their tags. Normalizing version numbers in that output would be an easy thing for Composer. I agree that if this problem should be solved, it should be solved in Composer.

**Comment by ghost** [comment]
Even though the `v` prefix is not a part of SemVer specification it helps in daily work when working with git.

**Comment by lyrixx** [comment]
I totally agree with @stof, @derrabus and @javaDeveloperKid ; I prefer also to kept the `v` prefix.

**Comment by ThomasLandauer** [comment]
OK, thanks, I suggested it for composer: https://github.com/composer/composer/issues/11925
