### ISSUE TITLE
Symfony still loading secrets and decrypting even though .env.*.local (or .env.local.php) exists

### ISSUE THREAD

**Issue by 719media** [symfony/symfony#52146]
### Symfony version(s) affected

6.3.5 (tested again in 6.3.7, problem persists)

### Description

When upgrading from Symfony 5.4 to Symfony 6.3, my production environment experienced severe CPU load (x1000).

I traced it down to an issue regarding the secrets file being 'decoded' on every CLI command. I am following best practices of `secrets:decrypt-to-local` so that the secrets are not required to be loaded on every request/command.

Troubleshooting futher, I narrowed down the problem to the inclusion of twig. Specifically, if I have a service that autowires twig (`private Twig\Environment $twig`), this problem arises.

### How to reproduce

1) `composer create-project symfony/skeleton new_project/`
2) `composer install`
3) `composer require symfony/twig`
4) `./bin/console secrets:generate-keys`
5) `./bin/console secrets:set BLACK`
6) Create two commands, one of which extends twig, and the other which is configured to use the secret created in step 5 in the constructor
7) Problem - command which extends twig needlessly runs script decrypt

To explicitly see the error at this point:

1) Run `composer install`
2) Run `./bin/console secrets:decrypt-to-local` to create .env.dev.local, which should negate the need for secrets decryption
3) Run `./bin/console app:test`. Note lack of var_dump, even though a secret is being used in constructor. This is good!
4) Run `./bin/console app:test-twig`. var_dump! (No secrets even being used in constructor). This is bad!

**Comment by 719media** [comment]
I'm not very familiar with symfony internals, so someone else will need to take a look, but it appears the problem is this line:

https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L110

Which is used by this config:

https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/TwigBundle/Resources/config/twig.php#L113

Because I do not (and I assume most people would not) have a value defined in .env for `SYMFONY_IDE`, the configuration is written with an env() wrapper, which then requires production hits to try and look for the undefined value in "secrets".

I'd create a PR, but I'm outside of my familiarity with inner workings and reasoning of symfony internals. Maybe there's a "better" way to solve.

A workaround for now is to set a value for SYMFONY_IDE in .env, but this seems like it could be a bandaid for a a deeper issue.

Now, as far as WHY that is happening in symfony 6 with twig (why is SYMFONY_IDE for a production environment deploy even being requested anyway?) I'm not sure... that's probably more important

**Comment by nicolas-grekas** [comment]
Thank you for all the details.
