### ISSUE TITLE
Deprecated everything related to `*AnnotatedClassesToCompile*` 

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#52141]
We use to have this code infrastructure to warmup doctrine/annotations. This is useless now.

**Comment by nicolas-grekas** [comment]
the `cache.annotations` service should also be deprecated

**Comment by stof** [comment]
I suggest deprecating that in 7.1 as bundles supporting 6.4 might still support annotations and so use it.

The infrastructure can become no-op in 7.0 (as we won't have annotations anymore)

**Comment by alexandre-daubois** [comment]
I tried to have a look at this issue. A question comes to my mind: isn't it a BC break to make `AddAnnotatedClassesToCachePass::process()` no-op, as it is not marked as internal or whatsoever ?

Or maybe did you have something else in mind when talking about this code infrastructure?

**Comment by alexandre-daubois** [comment]
Isn't it a BC break to make the infrastructure become a no-op? Or is it actually just removing the `$container->addCompilerPass(new AddAnnotatedClassesToCachePass($this));` call from `Kernel` in 7.0?
