### ISSUE TITLE
[PHPUnit-Bridge] Installing PHPUnit bridge has side-effect on local even if it's not used

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#52185]
### Symfony version(s) affected

all

### Description

I personally don't require the Phpunit-bridge and don't use it in my phpunit.xml.
I run my tests with `vendor/bin/phpunit` and the bootstrap file is
```xml
bootstrap="tests/bootstrap.php"
```
which contains
```php
require dirname(__DIR__).'/vendor/autoload.php';

if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} else {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}

if ($_SERVER['APP_DEBUG']) {
    umask(0);
}
```

But, a lot of my dependencies have this bridge as dev-dependencies so this lib is in my vendor in development mode.

The issue is that when I run my tests the phpunit-bridge/bootstrap file is executed:
I tried to throw an exception in this bootstrap file to know when it's loaded, it's done this way:
```
/var/www/wg-app/vendor/symfony/phpunit-bridge/bootstrap.php:16
Stack trace:
#0 /var/www/wg-app/vendor/composer/autoload_real.php(41): require()
#1 /var/www/wg-app/vendor/composer/autoload_real.php(45): {closure}('92c8763cd6170fc...', '/var/www/wg-app...')
#2 /var/www/wg-app/vendor/autoload.php(25): ComposerAutoloaderInit25a424351a9b80b8bf375de5dee47df7::getLoader()
#3 /var/www/wg-app/vendor/phpunit/phpunit/phpunit(97): require('/var/www/wg-app...')
#4 {main}
```

In this bootstrap file there is the code 
```
setlocale(\LC_ALL, 'C');
```
which change the local.
Because of this I don't have a test environment which reproduce the same behavior than my local or prod environnement.

### How to reproduce

- Install phpunit,
- run `setlocale(\LC_ALL, 0);` in a test
- Install phpunit-bridge without using it (install doctrine/common for instance)
- run `setlocale(\LC_ALL, 0);` in a test
- the value won't be the same

### Possible Solution

I kinda disagree with @nicolas-grekas on https://github.com/symfony/symfony-docs/issues/11087#issuecomment-483230958 => test should be context dependent if your local/prod are. But that's another debate.

At least, phpunit-bridge shouldn't have any side effects on test if it's not used by the developer.

After some tries, I discover that was the goal of
```php
// Detect if we're loaded by an actual run of phpunit
if (!defined('PHPUNIT_COMPOSER_INSTALL') && !class_exists(\PHPUnit\TextUI\Command::class, false)) {
    return;
}
```
(The early return is executed when command/kernel is booted in developement mode)

But IMHO we should also pass in this early return when phpunit is used without using the bridge.
Not sure the best way to detect this.

**Comment by derrabus** [comment]
> a lot of my dependencies have this bridge as dev-dependencies so this lib is in my vendor in development mode.

This is not how Composer works. Your dependencies' dev dependencies are not installed in your project. If this package appears in your vendors folder, either one of your dependencies requires it (non-dev) or you yourself do.

**Comment by VincentLanglet** [comment]
> > a lot of my dependencies have this bridge as dev-dependencies so this lib is in my vendor in development mode.
> 
> 
> 
> This is not how Composer works. Your dependencies' dev dependencies are not installed in your project. If this package appears in your vendors folder, either one of your dependencies requires it (non-dev) or you yourself do.

Indeed, my bad. This wasn't installed for this reason.

Still, I'm not sure it should have such side effect when I don't use it explicitely.

**Comment by nicolas-grekas** [comment]
Isn't this because you reference its bootstrap.php file in your phpunit.xml.dist file?

**Comment by nicolas-grekas** [comment]
OK, I can answer, this is it, that's in your description.
That's unrelated to this repo. Recipes are defaults you can change if you're not happy with them also.

**Comment by VincentLanglet** [comment]
> OK, I can answer, this is it, that's in your description. That's unrelated to this repo. Recipes are defaults you can change if you're not happy with them also.

I don't understand why you're saying I'm referencing the phpunit-bridge bootstrap.php file my phpunit.xml.dist.

My phpunit.xml is referencing 
```xml
bootstrap="tests/bootstrap.php"
```
which is the file
```php
<?php

use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} else {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}

if ($_SERVER['APP_DEBUG']) {
    umask(0);
}
```

I never made reference to the `phpunit-bridge/bootstrap.php` by myself as far as I know @nicolas-grekas.
Did I miss something ?

**Comment by nicolas-grekas** [comment]
Ah, sorry, you're right, this is composer including this file.

>  Because of this I don't have a test environment which reproduce the same behavior than my local or prod environnement.

Isn't this the sign that your test cases should be improved? If they rely on the locale, your tests should set the expected locale explicitly.

**Comment by nicolas-grekas** [comment]
A way forward could be to add an env var to configure this behavior.
`SYMFONY_PHPUNIT_LOCALE=0` would keep the existing locale.

Up for a PR?

**Comment by VincentLanglet** [comment]
> A way forward could be to add an env var to configure this behavior. `SYMFONY_PHPUNIT_LOCALE=0` would keep the existing locale.
> 
> Up for a PR?

Sure, which branch should I target ?
Can it be considered as a bugfix (?) and done on current version or should it wait for the 7.1 release ?

**Comment by nicolas-grekas** [comment]
6.4 please

**Comment by VincentLanglet** [comment]
> A way forward could be to add an env var to configure this behavior. `SYMFONY_PHPUNIT_LOCALE=0` would keep the existing locale.
> 
> Up for a PR?

Seems like one issue is the fact that env variable are loaded after the autoload file, so
```
getenv('SYMFONY_PHPUNIT_LOCALE')
```
always returns `false` in the phpunit-bridge/bootstrap.php file.

If I look at how `SYMFONY_DEPRECATIONS_HELPER` work, it does
```
if ('disabled' !== getenv('SYMFONY_DEPRECATIONS_HELPER')) {
    DeprecationErrorHandler::register(getenv('SYMFONY_DEPRECATIONS_HELPER'));
}
```
and then there is
```
private function getConfiguration()
    {
        if (null !== $this->configuration) {
            return $this->configuration;
        }
        if (false === $mode = $this->mode) {
            $mode = $_SERVER['SYMFONY_DEPRECATIONS_HELPER'] ?? $_ENV['SYMFONY_DEPRECATIONS_HELPER'] ?? getenv('SYMFONY_DEPRECATIONS_HELPER');
        }
```
so
- When running phpunit, `getenv('SYMFONY_DEPRECATIONS_HELPER')` returns false and we register `DeprecationErrorHandler`.
- Then env are loaded
- Then the `DeprecationErrorHandler` configuration is loaded and `$mode = $_ENV['SYMFONY_DEPRECATIONS_HELPER'] = 'disabled'`.

It does work differently when using `simple-phpunit` directly because this tool use a custom `$getEnvVar` method and pre-set the env variable with things like
```
if ('disabled' === $getEnvVar('SYMFONY_DEPRECATIONS_HELPER')) {
    putenv('SYMFONY_DEPRECATIONS_HELPER=disabled');
}
```
before doing the autoload.

In order to be optionnal, the `setlocale(\LC_ALL, 0)` call should be moved:
- In the simple-phpunit binary
- Somewhere in the `SymfonyTestsListener` listener (to support both usage from https://symfony.com/doc/current/components/phpunit_bridge.html#usage)

Would it be ok to move the `setlocale(\LC_ALL, 0)` call to the `SymfonyTestsListener` constructor for instance @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
That'd be fine to me (but I'd still like to have this env var while at it :) )
