### ISSUE TITLE
Help Wanted: Fix failures on appveyor

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#52206]
Branch 7.0 has failures that look legit on appveyor:

https://ci.appveyor.com/project/fabpot/symfony/builds/48330699?fullLog=true

Note that apppveyor tests Windows, but not only. There, we also test running the test suite without any extensions (e.g. to check that we added all `@requires` annotations in test, and we test on x86 (32-bit arch).

**Comment by maxbeckers** [comment]
For the tests failed in the log with the date format:

>1) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextDateTime
null does not match expected type "object".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:108
>2) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextDateTimeImmutable
Failed asserting that null is an instance of class "DateTimeImmutable".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:130
>3) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextString
Failed asserting that null matches expected '2010-06-02'.
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:153
>4) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextTimestamp
Failed asserting that null matches expected '1275436800'.
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:177
>5) Symfony\Component\Form\Tests\Extension\Core\Type\BirthdayTypeTest::testSubmitFromSingleTextRaw
null does not match expected type "array".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:205
>6) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextDateTime
null does not match expected type "object".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:108
>7) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextDateTimeImmutable
Failed asserting that null is an instance of class "DateTimeImmutable".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:130
>8) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextString
Failed asserting that null matches expected '2010-06-02'.
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:153
>9) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextTimestamp
Failed asserting that null matches expected '1275436800'.
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:177
>10) Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest::testSubmitFromSingleTextRaw
null does not match expected type "array".
C:\projects\symfony\src\Symfony\Component\Form\Tests\Extension\Core\Type\DateTypeTest.php:205

It seems to be the problem, that `$form->submit('2.6.2010');` does not match with the given format. When you change it to `$form->submit('12.6.2010');` or change the format to `d.M.y` you don't get `NULL` here.
Tested on Windows.
