### ISSUE TITLE
Help Wanted: fix failure on WebProfilerBundle 5.4 loaded with higest deps

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#52210]
On 5.4, we have a failure to fix:
https://github.com/symfony/symfony/actions/runs/6590102626/job/17912208613#step:7:393

I can reproduce it by going into the `src/Symfony/Bundle/WebProfilerBundle` folder on branch 5.4, then running composer up and
`SYMFONY_DEPRECATIONS_HELPER=weak ../../../../phpunit --filter testPanelActionWithLatestToken$`

Help welcome to figure out the issue and fix it!

**Comment by smnandre** [comment]
```php
1) Symfony\Bundle\WebProfilerBundle\Tests\Controller\ProfilerControllerTest::testPanelActionWithLatestToken
UnexpectedValueException: The profiler template "@WebProfiler/Collector/command.html.twig" for data collector "command" does not exist.
```

Two choices:
* either the command profiler template is missing [in this folder](https://github.com/symfony/symfony/tree/5.4/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector)
* either the definition of the collector must be deleted

```
  ".data_collector.command" => array:2 [
    0 => "command"
    1 => "@WebProfiler/Collector/command.html.twig"
  ]
```

**Comment by nicolas-grekas** [comment]
The change should be done in 6.4 ideally /cc @HeahDude

**Comment by HeahDude** [comment]
It seems `WebProfilerBundle` 5.4 cannot be compatible with `FrameworkBundle` 6.4, the latter being responsible for configuring collectors.

I see tow options:
- add a compiler pass in `WebProfilerBundle` 5.4 to remove new data collectors introduced by 6.x (I guess we will have the same error with the Workflow data collector if we fix this only for the command data collector).
- add a conflict rule in `FrameworkBundle` 6.4 to not allow `WebProfilerBundle` < 6.4.

I would go for the second solution.

**Comment by nicolas-grekas** [comment]
Patching 5.4 to account for 6.4 would be wrong, so solution 2 would be the way. Ideally, I'd prefer FWB to not know about WPB. Is there no solution that doesn't involve adding any conflict line?

**Comment by HeahDude** [comment]
See #52218.

**Comment by HeahDude** [comment]
The conflict line was already there because I guess the problem was always there, adding collectors in FWB while adding templates in WebProfilerBundle.

**Comment by HeahDude** [comment]
So we can close here I guess.
