### ISSUE TITLE
[RFC][Security] CSRF Protection for stateless APIs

### ISSUE THREAD

**Issue by maxbeckers** [symfony/symfony#52244]
### Description

CSRF Protection is one piece of security for an application. Symfony forms support that by default. But for stateless backends like headless backends it works a bit different. There we don't render a form with twig in the frontend. We completely handle the logic in the frontend and just make api calls to the backend.

I came into contact with this last week in a Java / Spring Boot project. Here it is supported like this:  https://www.baeldung.com/spring-security-csrf#stateless-spring-api
There the backend sends a cookie to the frontend. In this cookie is a token. And then for each API Requests that modify anything (POST, PUT, DELETE and PATCH) you add this token to a header and then the backend verifies the header.

I think there are different ways possible to implement this Feature to support CSRF or sth CSRF alike for APIs in Symfony.
So there are the following 2 questions:
1. Do we want a feature like this?
2. If Yes: How do we want to implement that?

**Comment by stof** [comment]
The doc you linked says that you need CSRF protection only if your API uses session-based authentication. And in such case, the `symfony/security-csrf` component can already be used to provide CSRF protection (you could perform such check in a listener for the request event if you don't want to do the check in each controller)

**Comment by maxbeckers** [comment]
Yes for the page I linked this is correct, there the problem is when the authentication is based on the session cookie that is sent automatically by the browser. And good that this could already be handled with symfony with the solution you mentioned. I just was faced with this topic in a spring boot project and i didn't know that it's already possible with symfony.

On the linked page there are a few more examples that are not that often but could also be vulnerable to CSRF attacks.
> This is the case of [HTTP basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), [HTTP digest authentication](https://en.wikipedia.org/wiki/Digest_access_authentication), and [mTLS](https://en.wikipedia.org/wiki/Mutual_authentication).

But would be fine for me to close this issue and not focus on these cases.
