### ISSUE TITLE
Outdated Messenger documentation

### ISSUE THREAD

**Issue by rela589n** [symfony/symfony#52247]
### Symfony version(s) affected

6.2

### Description

Currently I'm struggling with dynamic message buses configuration (very specific task that requires different buses with the same middleware set, - since handlers are stateful because of batch processing). I thought using native php config (where I'd have access to my bundle config to create bunch of buses) would be a great idea, but can't find a working configuration sample.

On https://symfony.com/doc/6.2/messenger.html page, when selecting to use PHP config instead of YAML, there are code examples using `FrameworkConfig`. But this class does not seem to be present in the repository. 

For instance (copied from documentation):

```
// config/packages/messenger.php
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework): void {
    $messenger = $framework->messenger();

    $messenger->transport('async_priority_high')
        ->dsn(env('MESSENGER_TRANSPORT_DSN'))
        ->options(['queue_name' => 'high']);

    $messenger->transport('async_priority_low')
        ->dsn(env('MESSENGER_TRANSPORT_DSN'))
        ->options(['queue_name' => 'low']);

    $messenger->routing('App\Message\SmsNotification')->senders(['async_priority_low']);
    $messenger->routing('App\Message\NewUserWelcomeEmail')->senders(['async_priority_high']);
};
```

### How to reproduce

1. Visit https://symfony.com/doc/6.2/messenger.html#prioritized-transports;
2. Click PHP config example button instead of default YAML;
3. See outdated config.

### Possible Solution

It would be nice to provide up-to-date documentation for this config.

**Comment by xabbuh** [comment]
This class is generated when the Symfony cache is warmed up inside the cache directory. You need to make sure to not exclude this directory from being inspected for auto-completion in your IDE.

**Comment by rela589n** [comment]
Thanks you for your answer.
Surely it works, though I did not come across it in the documentation.

Thank you once again and have a nice day.
