### ISSUE TITLE
symfony5 not found autowire class

### ISSUE THREAD

**Issue by RubyKiss** [symfony/symfony#52256]
### Symfony version(s) affected

5.4.*

### Description

![image](https://github.com/symfony/symfony/assets/19652699/26b4b7e5-e3c3-4f7f-a7a5-93aa5e82ad40)

Why isn't there a class for this?

### How to reproduce

1. version: php 7.4.3
2. exec:  symfony new --webapp ***

**Comment by nicolas-grekas** [comment]
The class you're looking for is available since Symfony 6.1, which requires PHP 8.1 minimum. You should upgrade your version of PHP.

**Comment by RubyKiss** [comment]
so... and then now how can i get the services.yaml parameters setting at 5.4.* version?
look this

![image](https://github.com/symfony/symfony/assets/19652699/111fbf93-0d97-4dc6-a85c-c1e073339bc7)

**Comment by nicolas-grekas** [comment]
You should use bindings in v5.4

It looks like you're reading the book, here is the section that tells about in the book FOR V5.4:
https://symfony.com/doc/5.4/the-fast-track/en/14-form.html#uploading-files
