### ISSUE TITLE
Update sendinblue.com API to brevo.com in Mailer and Notifier on LTS

### ISSUE THREAD

**Issue by vicla31** [symfony/symfony#52264]
### Symfony version(s) affected

5.4

### Description

Sendinblue rebrands to Brevo, and it simultaneously  upgrade smtp and API servers.   
There are 2 distincts API currently : api.sendinblue.com (deprecated but still running) and api.brevo.com (the one to use)  
Sendinblue Mailer and Notifier are removed on 7.0 according to this issue https://github.com/symfony/symfony/issues/52097  
However API host are not changed on LTS 5.4 and 6.4 and are still set to api.sendinblue.com. I suggest to update them like that was done for smtp.brevo.com

### How to reproduce

Remplace api.sendinblue.com by api.brevo.com in Symfony\Component\Notifier\Bridge\Sendinblue\SendinblueTransport and Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueApiTransport

**Comment by xabbuh** [comment]
We did update the SMTP host (see #51119 and #51295). If the API transports require a similar change, we should do that too. PR welcome I guess.

**Comment by stof** [comment]
Note that in 6.4, you should migrate to the Brevo bridges.
