### ISSUE TITLE
[Form] Use an horizontal rule to separate preferred choices

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#52260]
### Description

Today, we use by default the following text-based separator for preferred choices in `ChoiceType`:

https://github.com/symfony/symfony/blob/fafbbfac181fda0850548317f342da354cf9bbf2/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L243

Some browsers just added support for adding `<hr>` as separators inside `<select>` elements, which looks much better. See https://developer.chrome.com/blog/hr-in-select/

If this proposal is accepted, it can only be implemented in a few months, when most browsers support this feature. Thanks!

**Comment by xabbuh** [comment]
👍 sounds good to me

**Comment by stof** [comment]
Already supported in Safari and now in Chrome. We're just missing Firefox there.

Note that we might need to make this configurable at first, as some projects might need to keep support for older browsers or they might do custom things with the separator.

**Comment by stof** [comment]
For reference, here is the ticket tracking this for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1830909

**Comment by javiereguiluz** [comment]
This has been implemented in Firefox 🎉 

It's available in the nightly release. See https://www.mozilla.org/en-US/firefox/122.0a1/releasenotes/ and will land in the next 122 stable release.

**Comment by nicolas-grekas** [comment]
Another option would be to use a unicode character to make a line (`─` => `──────`)
Both options (html / unicode) are doable in userland after #52447, but do we want to change the default?
PR welcome if yes. Can be closed otherwise.

**Comment by xabbuh** [comment]
I would not make the change by default to not break existing applications (or at least their tests). Being able to customise this is sufficient to me.
