### ISSUE TITLE
[FrameworkBundle][DebugBundle][Console] Non-existant service .virtual_request_stack

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#52280]
### Symfony version(s) affected

6.4.x-dev

### Description

On a freshly installed project, commands are not working when APP_DEBUG=false

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 88:
                                                                                                          
  The service "data_collector.dump" has a dependency on a non-existent service ".virtual_request_stack".  

### How to reproduce

```code
 symfony new --webapp --version=next  debug-console \
    && cd debug-console \
    && APP_DEBUG=false php bin/console about
```

### Details / explanation

In the DebugBundle / [services.php](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/DebugBundle/Resources/config/services.php)

```php
        ->set('data_collector.dump', DumpDataCollector::class)
            ->public()
            ->args([
                service('debug.stopwatch')->ignoreOnInvalid(),
                service('debug.file_link_formatter')->ignoreOnInvalid(),
                param('kernel.charset'),
                service('.virtual_request_stack'),
                null, // var_dumper.cli_dumper or var_dumper.server_connection when debug.dump_destination is set
            ])
            ->tag('data_collector', [
                'id' => 'dump',
                'template' => '@Debug/Profiler/dump.html.twig',
                'priority' => 240,
            ])
```

In the FrameworkBundle / debug.php

```php
->set('.virtual_request_stack', VirtualRequestStack::class)
    ->args([service('request_stack')])
    ->public()
```

**Comment by smnandre** [comment]
Update with details on the problem

**Comment by xabbuh** [comment]
Can you confirm that #52290 fixes the issue for you?

**Comment by smnandre** [comment]
Yes, thank you @xabbuh !  And sorry again

**Comment by xabbuh** [comment]
@smnandre Thanks to you for testing beta releases! That's much appreciated.

**Comment by curry684** [comment]
Just came here to report this, thanks for the swift fix   💯 

I'd like to request a new beta because of this as it's breaking multiple CI workflows for me: composer install triggers cache:clear which crashes because of this. I cannot continue development (and thus testing the beta) now.

**Comment by scheb** [comment]
Hey guys and @xabbuh

Thanks for addressing this issue! Though I'm still seeing it when running the console for the first time in my 2fa-bundle test application with 7.0.0-RC1 and 6.4.0-RC1 versions.

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 85:
  The service "debug.log_processor" has a dependency on a non-existent service ".virtual_request_stack".
```

Failing build for reference: https://github.com/scheb/2fa/actions/runs/6882260213/job/18720409786

It seems to be related by the `.virtual_request_stack` reference here: https://github.com/symfony/symfony/blob/c9e7809f045a1366afe2c2643bae15751ae7b500/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1156-L1164

because changing this Reference to

`$definition->addArgument(new Reference('.virtual_request_stack', ContainerInterface::NULL_ON_INVALID_REFERENCE));`

makes that exception go away.

**Comment by xabbuh** [comment]
@scheb Could you please check if #52604 solves that?

**Comment by scheb** [comment]
@xabbuh Yes, that works for me 👍. Thanks!

Though to be honest, I just copy & pasted changes from your fork into my vendor folder (with Symfony 6.4.0-RC1 packages installed). I couldn't figure out how to get Composer to install these packages from your fork, without ending in dependency hell 🙈
