### ISSUE TITLE
[Form] HoneypotType

### ISSUE THREAD

**Issue by maelanleborgne** [symfony/symfony#52291]
### Description

It is very common to add a honeypot field in publicly accessible forms to prevent bot to spam our websites.
What would you think if we added a `HoneypotType` to the Form component to quickly add a way for developers to handle honeypot catches and implement there own logic to decide what to do with the catch ?

I'm aware there is [bundle](https://github.com/eymengunay/EoHoneypotBundle) to add honeypot support to symfony, but it contains many features that are not essential for simple use-cases, and I think this feature could easily live in the component rather than in a bundle.

What are your thoughts on this ?

### Example

An easy way would be to check on `PRE-SUBMIT` if the field has been filled, and if so dispatch a `HoneypotEvent`.
This event would wrap the orignal `FormEvent` and have a `formError` flag that can be set by the listeners. Developers could set there own logic in the listener (log the event for example).
Then we would just need to check the returned event `formError` flag to decide whether to add an error to the form.

```php
// HoneypotType.php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // If a value was provided for the honeypot field, we dispatch an event
        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) use ($options) {
            $data = $event->getData();
            $messageTemplate = $options['invalid_message'];
            if ('' !== $data) {
                $honeypotEvent = $this->eventDispatcher->dispatch(new HoneypotEvent($event));
                if (!$honeypotEvent->isFormError()) {
                    return;
                }
                // Default message could be someting along those lines:
                $errorMessage = 'We detected an abnormal behavior and blocked the form submission. Make sure you are not using any automated form filler and try again.'
                $event->getForm()->addError(new FormError($errorMessage));
                // Reset the field to the correct value in case the user wants to re-submlt
                $event->setData('');
            }
        });
    }
```

**Comment by Seb33300** [comment]
Why not just using a `Blank` constraint?
https://symfony.com/doc/current/reference/constraints/Blank.html

**Comment by maelanleborgne** [comment]
> Why not just using a `Blank` constraint? https://symfony.com/doc/current/reference/constraints/Blank.html

Well the HoneypotType, though the default behavior would be very similar to the Blank constraint, would give you the ability to invalidate the form (+ run whatever code you'd see fit) using a custom logic via the EventListener. And also the Blank constraint is valid when the value is null, which is not wanted in a honeypot context because that could mean the field was removed before submission.
I understand that this behaviour is very easily set up without using a dedicated component, but if you end up having many forms using this feature, I think it's worth keeping the form configurations clean and have the custom logic separated in the listener or a dedicated service.

**Comment by Seb33300** [comment]
> the Blank constraint is valid when the value is null

You can combine the `Blank` constraint with a with a `NotNull` constraint.
Or just use an `EqualTo` constraint.

**Comment by maelanleborgne** [comment]
Another implementation could be:
At form generation, we set the honeypot field value with an encrypted timestamp (using a secret) representing the time at which the form was generated.
When submitted, we try to decrypt the value (if it fails, generate an error), and compare the timestamp to the server current time. We could set a minimum delay before submission (in form options), meaning that if the form was submitted in less time than what we consider reasonable, we generate an error.
The time option would default to 0 so no problem with very fast typers ;) 

This now looks more like a csrf validation with time constraint in an editable field.

**Comment by curry684** [comment]
What you're describing is far more complex than just having a honeypot field, you'd also want logic around timing as described above, have automatic integrations, sign values etc. This kind of disqualifies it as generic "out of the box" behavior and would be a better fit to have in a separate configurable bundle.

Which brings us to https://packagist.org/packages/isometriks/spam-bundle which has implemented all of this and is working fine   :)   you can just install it, set `global: true` in the recipe's config, and you're done for all forms in the application.

**Comment by maelanleborgne** [comment]
> What you're describing is far more complex than just having a honeypot field, you'd also want logic around timing as described above, have automatic integrations, sign values etc. This kind of disqualifies it as generic "out of the box" behavior and would be a better fit to have in a separate configurable bundle.
> 
> Which brings us to https://packagist.org/packages/isometriks/spam-bundle which has implemented all of this and is working fine :) you can just install it, set `global: true` in the recipe's config, and you're done for all forms in the application.

Wow, I didn't know this bundle but it's exactly what I had in mind when in wrote my last comment ! That looks great, I'll give it a try :) Thank you

**Comment by curry684** [comment]
Happy to help  😄   only thing to be wary of with that bundle is that it seems barely maintained, although the owners happily accept all compatibility PRs there doesn't seem to be anything happening to the code apart from that. Still works fine for now and will likely stay that way for some more years.

I may fork/rebuild it at some point as my company also has some clients with severe spam issues, we developed an [Akismet library](https://packagist.org/packages/omines/akismet) for that earlier this year which works really well. We use it in some places after the SpamBundle has filtered most crap and it catches all that remains reliably.

**Comment by curry684** [comment]
So ok I started a completely new bundle, if you are interested you can take https://github.com/omines/antispam-bundle for a test drive   :)  not all features are implemented, specifically stealth and passive mode, but it will already be more effective than Isometriks in current state as it can also filter scripts (like Cyrillic, which filters a lot in our experience) and markup (bots that attempt to inject HTML). The recipe isn't up yet so you do have to configure it yourself for now.
