### ISSUE TITLE
[http-foundation] Why is Request::getPayload() not checking content type

### ISSUE THREAD

**Issue by pjordaan** [symfony/symfony#52309]
### Symfony version(s) affected

6.3

### Description

I ran into an issue with my integration tests in combination with PSR requests and using Laravel, see https://github.com/laravel/framework/issues/48828

I have an integration test testing a form submit, so content type is application/x-www-form-urlencoded and not JSON. getPayload does not check any content type and will try to decode it as JSON throwing an error.

But I guess it could also be seen as a potential CSRF vulnerability as a Rest API is only vulnerable to CSRF if you ignore the content-type and use session cookies.

### How to reproduce

I found it in a laravel application that uses PSR ServerRequestInterface in a controller and wrote a small integration test that does a form submit with content type application/x-www-form-urlencoded and url encoded POST body. But the real bug is just making a form submit request and calling getPayload()

### Possible Solution

2 possible solutions:
- make getPayload check content type?
- parse the body if its valid url encoded.

**Comment by ro0NL** [comment]
> parse the body if its valid url encoded

It should do that already: https://github.com/symfony/symfony/blob/ce48fbe3de4734101d98a98615c0afbd6e88c7d4/src/Symfony/Component/HttpFoundation/Request.php#L1519-L1524

IIUC it's possible to send JSON with form-urlencoded content-type, and getPayload() happily parses. Or what payload are we talking about now?

See also https://github.com/symfony/symfony/issues/50118, the suggestion is to check in controller rather then routing :S

**Comment by pjordaan** [comment]
> > parse the body if its valid url encoded
> 
> It should do that already:
> 
> https://github.com/symfony/symfony/blob/ce48fbe3de4734101d98a98615c0afbd6e88c7d4/src/Symfony/Component/HttpFoundation/Request.php#L1519-L1524
> 
> IIUC it's possible to send JSON with form-urlencoded content-type, and getPayload() happily parses. Or what payload are we talking about now?
> 
> See also #50118, the suggestion is to check in controller rather then routing :S

Thank's I missed that $this->request should contain the parsed POST body. But for some reason $this->request is not filled in, but the body contains url encoded data instead. That will be hard to find out why $this->request is not filled in

My integration tests test if the library works in Laravel and Symfony and the test is using PSR requests internally and the library controllers are using PSR requests as well, but the side effect is that it does a lot of conversions from PSR request to the framework request object back to a PSR request. The Symfony integration tests work fine, but only the Laravel integration tests fail.

Laravel is extending the Symfony request object. Could it be possible that Laravel is not setting the $this->request property in all cases and that is breaking the getPayload() method?

**Comment by ro0NL** [comment]
> for some reason $this->request is not filled in, but the body contains url encoded data instead

> Laravel is extending the Symfony request object.

i'd debug there first yes :)

**Comment by pjordaan** [comment]
Thanks for your time. I have looked at it and found out the problem. The issue is that I started with a PSR request and converts this to a symfony request.
HttpFoundationFactory copies Request::$request from getParsedBody but my PSR request did not calculate this yet so the invalid request object could be created. You could have a PSR request object with content type application/x-www-form-urlencoded and no parsed body, but not sure this should be handled in http-foundation.
