### ISSUE TITLE
[PHPUNIT-BRIDGE][TEST-PACK] Phpunit version

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#52306]
### Symfony version(s) affected

6.3.6

### Description

Hello all,

Does `symfony/phpunit-bridge` now supports Phpunit version 10?

This commit from `symfony/test-pack` (https://github.com/symfony/test-pack/commit/7b708c588cb3e1c8f0281889f273b920cbddff9b) adds a condition in `composer.json` for the version to avoid issue with Phpunit version 10 since february.
Does someone know if now, Phpunit 10 is supported or still not ?

Best regards,

### How to reproduce

Install a new Symfony project.
Execute `composer require symfony/test-pack`: `phpunit/phpunit` will take the version `9.6.13`.

**Comment by xabbuh** [comment]
see #49069 and #50371

Thus, I am closing here as a duplicate. Thank you for understanding.
