### ISSUE TITLE
Form DateType bug on PHP 8.2.12

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#52315]
### Symfony version(s) affected

6.3.6

### Description

<img width="1440" alt="Screenshot 2023-10-27 at 11 31 12" src="https://github.com/symfony/symfony/assets/2576509/37cd4533-7bc3-4dbb-a494-121a34568e92">

<img width="1440" alt="Screenshot 2023-10-27 at 09 59 33" src="https://github.com/symfony/symfony/assets/2576509/1af918d8-eb00-4db1-99ed-c83dd3f9c9c0">

https://github.com/php/php-src/issues/12533

### How to reproduce

```class StatisticAppType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('date', DateType::class);
    }
}

### Possible Solution

_No response_

### Additional Context

_No response_

**Comment by xabbuh** [comment]
Can you please debug the actual value that is passed to  the `IntlDateFormatter` constructor in your case?

**Comment by andreybolonin** [comment]
<img width="341" alt="Screenshot 2023-10-27 at 12 15 36" src="https://github.com/symfony/symfony/assets/2576509/9da7a79d-3b89-4d53-93a4-737f5bac38e8">
<img width="615" alt="Screenshot 2023-10-27 at 12 16 00" src="https://github.com/symfony/symfony/assets/2576509/2f5b6778-7c7f-46a4-a78d-a7b9a228751b">

**Comment by xabbuh** [comment]
Why does `Locale::getDefault()` return `admin` in your case?

**Comment by andreybolonin** [comment]
@xabbuh I don't know, not item to set locale to value 'admin'
<img width="699" alt="Screenshot 2023-10-27 at 12 24 40" src="https://github.com/symfony/symfony/assets/2576509/11da4b15-9a16-4674-8bb0-7f3b86f398fe">

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue? Otherwise, we will not be able to investigate.

**Comment by andreybolonin** [comment]
https://github.com/andreybolonin/datetypebug

**Comment by andreybolonin** [comment]
I found the problem:
```#[Route(path: ['admin' => '/admin/statistic_app', 'player' => '/player/statistic_app'])]```
If comment this string, all is ok
@xabbuh thx

**Comment by stof** [comment]
passign an array to the `path` or a route is meant to support translating paths. The key in this array is the locale.

**Comment by mpdude** [comment]
Also see https://github.com/php/php-src/issues/12533 and the real issue here: https://github.com/php/php-src/issues/12282

PHP 8.1.25 throws an exception when an unknown `$locale` value is passed to `\IntlDateFormatter::__construct()`. In PHP 8.1.24 and before, invalid values were silently ignored.

Filed https://github.com/php/php-src/issues/12561
