### ISSUE TITLE
Profiler doesn't catch docker container launched with compose.yaml

### ISSUE THREAD

**Issue by julienbohy** [symfony/symfony#52320]
### Symfony version(s) affected

6.3.6

### Description

Web profiler doesn't catch running docker containers

![image](https://github.com/symfony/symfony/assets/5576245/ee3d8391-b23a-4db6-b11c-4fb8bd04f39d)

with default names : 
![image](https://github.com/symfony/symfony/assets/5576245/bd5aa6d0-f7b9-4d39-a1f7-f9ee33145e92)

![image](https://github.com/symfony/symfony/assets/5576245/5276ab86-d94c-493e-bc82-ad576155e383)

when i rename with old docker compose names
![image](https://github.com/symfony/symfony/assets/5576245/b5210656-3e63-4a91-ae7e-6a96eb9158af)
![image](https://github.com/symfony/symfony/assets/5576245/3a0a263b-5dfa-4253-9692-e92c6c33bcf7)

### How to reproduce

See description

**Comment by stof** [comment]
This panel is a special one injected by the symfony-cli project.

Are you using the latest version of it ? Support for the new docker compose file names has been released 2 days ago: https://github.com/symfony-cli/symfony-cli/releases/tag/v5.6.2

**Comment by julienbohy** [comment]
@stof : Thanks a lot for help.

it run ;).

The CLI doesn't tell me a new version is released

**Comment by DelphineLemire** [comment]
I work on Symfony 7.0.2 with Symfony CLI 5.8.6 and I have same issue.
