### ISSUE TITLE
symfony/yaml PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by timnolte** [symfony/symfony#52326]
### Symfony version(s) affected

6.3.3

### Description

The `trim()` method will no longer accept a null value.

https://github.com/symfony/yaml/blob/6.3/Inline.php#L62

Deprecation warnings are thrown when this method is used.

### How to reproduce

```php
Call `Inline::parse( null );
```

### Possible Solution

Need to validate that `$value` is not `null` before attempting to `trim()`.

**Comment by nicolas-grekas** [comment]
This class is internal.
Did you find a way to do this call while using only non-internal API?

**Comment by stof** [comment]
@nicolas-grekas we should still check why our argument has a default value being `null` though...

**Comment by timnolte** [comment]
@nicolas-grekas I think we probably need to dig in deeper to how we are using this method tbh. So I'll do some digging into this as well.

**Comment by ghost** [comment]
> This class is internal. Did you find a way to do this call while using only non-internal API?

I think the author reports deprecation warnings he wants to get rid of.

**Comment by stof** [comment]
@javaDeveloperKid but then, we still need to know which code path triggers that deprecation, to find where we end up passing null to this method.

**Comment by ghost** [comment]
@stof we can't rule out that someone violates `@internal` annotation

**Comment by timnolte** [comment]
@javaDeveloperKid & @stof if you look at the function the default value if none is supplied is `null`. https://github.com/symfony/yaml/blob/6.3/Inline.php#L58

```php
public static function parse(string $value = null, int $flags = 0, array &$references = []): mixed
```

**Comment by timnolte** [comment]
FYI, I patched this code using a `null` check with an early return before the `trim()` even happens.

**Comment by GromNaN** [comment]
The class is marked as `@internal`. This method must not be called outside of the Yaml component. Everywhere we call it with a string as first argument. There is no supported case of passing `null` as first argument.
If your code uses this function, you must fix it.
I submitted a PR for 6.4 to disallow `null` value https://github.com/symfony/symfony/pull/52334

**Comment by timnolte** [comment]
@GromNaN FYI, we are not calling that method directly actually. We are calling `Yaml::dump()` & `Yaml::parse()`. https://github.com/symfony/yaml/blob/6.3/Yaml.php#L91
https://github.com/symfony/yaml/blob/6.3/Yaml.php#L73

**Comment by GromNaN** [comment]
Could you provide an example? So that we can fix the `Yaml` class if necessary.

**Comment by timnolte** [comment]
@GromNaN our call is just this: https://github.com/forumone/wp-cfm/blob/develop/includes/class-readwrite.php#L204

I believe we can probably squash the deprecation warning by ensuring we aren't passing a `null` value into the `Yaml::parse()` method.

**Comment by GromNaN** [comment]
You are the [using `symfony/yaml: 3.3.6`](https://github.com/forumone/wp-cfm/blob/develop/composer.lock#L11). This explains why you don't have the type check when calling `Yaml::parse(null)`. You will have to fix the call on your side since this [unmaintained version](https://symfony.com/releases/3.3) will not be updated.

**Comment by timnolte** [comment]
@GromNaN actually I have an open PR to upgrade to v5. https://github.com/forumone/wp-cfm/blob/fix/135-php81-deprecations/composer.json#L29

**Comment by GromNaN** [comment]
👍🏻 In 5.4, only strings are accepted by [`Yaml::parse()`](https://github.com/symfony/yaml/blob/5.4/Yaml.php#L76).
