### ISSUE TITLE
Suggested a special feature to work with Svelte for JS

### ISSUE THREAD

**Issue by Gadrawingz** [symfony/symfony#52361]
### Description

Special feature to work with Svelte **frontend** framework highly needed!

**Comment by xabbuh** [comment]
Please be more precise. What is that special feature that you would like to see?

**Comment by wouterj** [comment]
Symfony UX provides integration with Svelte: https://ux.symfony.com/svelte

All other Symfony libraries are running server-side and agnostic of the stack used on the client-side. If you need help getting Svelte working with Symfony, you can ask for help in one of our [community support channels](https://symfony.com/support).

For now, I'm closing this issue, as it's not actionable as-is and I don't think there is anything needed.
