### ISSUE TITLE
[Messenger] Provide a way to consume all transports without specifying/knowing their names

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#52364]
### Description

When using https://github.com/php-enqueue/enqueue, a command:
```
enqueue:consume
```
is provided, in which there is no need to specify the consumers.

But when I run 
```
bin/console messenger:consume
```
I'm getting prompt about which transport I want to consume.

I saw in the code there was
```
$defaultReceiverName = 1 === \count($this->receiverNames) ? current($this->receiverNames) : null;
$defaultReceivers = $defaultReceiverName ? [$defaultReceiverName] : [];
```

What about something like --all in order to consume everything ? Would it be a good idea ?
Or maybe a commande should be added to list all the transports and then the output could be used for the consume command (or even to setup different supervisor with a foreach loop on the output ?)

I'd like to avoid updating my conf/commands
```
bin/console messenger:consume foo1,foo2,...
```
everytime.

### Example

_Originally posted by @VincentLanglet in https://github.com/symfony/symfony/discussions/51989_

**Comment by maelanleborgne** [comment]
I thought using `--no-interaction` allowed this, but it seems like it just starts a worker that doesn't consume any transport... IMO the default behaviour when not transport is specified should be "all" rather than "none". Any thoughts ?

**Comment by VincentLanglet** [comment]
> I thought using `--no-interaction` allowed this, but it seems like it just starts a worker that doesn't consume any transport... IMO the default behaviour when not transport is specified should be "all" rather than "none". Any thoughts ?

Currently the default is all only if there is one transports.
As soon as there are many transport, it will be none.
