### ISSUE TITLE
[Cache] `igbinary_serialize` is not compatible with `serialize` anymore

### ISSUE THREAD

**Issue by martijnc** [symfony/symfony#52391]
### Symfony version(s) affected

5.x, 6.x

### Description

As of PHP 7.4.6 (https://github.com/doctrine/common/issues/886#issuecomment-618263326), PHP's `serialize` function ignores uninitialized properties and no longer triggers an error. The same change was not (yet) made in igbinary's `igbinary_serialize`, there is a [ticket](https://github.com/igbinary/igbinary/issues/273) to change this though.

Symfony Cache `DefaultMarshaller` still treats `igbinary_serialize` as a drop-in replacement for `serialize` but this is no longer true. Trying to serialize entities with igbinary installed now results in the same error we used to get with `serialize`.

```
Typed property Proxies_CG_\App\Entity\EntityName::$ must not be accessed before initialization (in __sleep)
```

### How to reproduce

Serialize an object with an uninitialised property through Symfony cache with the default marshaller config.

### Possible Solution

It is possible to disable igbinary through the `cache.default_marshaller` service but Symfony may want to consider disabling it by default as it no longer is a drop-in replacement.

**Comment by nicolas-grekas** [comment]
Isn't the solution to provide a fix to https://github.com/igbinary/igbinary/issues/273?
A friendly ping there should help.
Meanwhile, we could skip using igbinary by default indeed when saving objects.
Can you please send a PR doing so?

**Comment by PegaseMarket** [comment]
Hello,
I have the same problem, but my php version is 7.4.33, igbinary is 3.2.7 and Symfony 5.4.38.
I don't understand why I always get this same error
