### ISSUE TITLE
[Intl] PHP Fatal error:  Uncaught IntlException: datefmt_create: invalid locale: U_ILLEGAL_ARGUMENT_ERROR after updating to PHP 8.1.25

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#52407]
### Symfony version(s) affected

6.3.7

### Description

After updating to PHP 8.1.25 (or PHP 8.2.12) an Exception is thrown

PHP Fatal error:  Uncaught IntlException: datefmt_create: invalid locale: U_ILLEGAL_ARGUMENT_ERROR

This is because of the bug fix
"Fixed bug [GH-12282](https://github.com/php/php-src/issues/12282) (IntlDateFormatter::construct should throw an exception on an invalid locale)."

=> https://github.com/php/php-src/issues/12282

### How to reproduce

1) After debugging
Symfony\Component\HttpFoundation\Request::setPhpDefaultLocale(string $locale)

I saw, that the value of $locale is 'default' sometimes.

2)
The error is then thrown in:
Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer::getIntlDateFormatter

$intlDateFormatter = new \IntlDateFormatter(\Locale::getDefault(), ... '');

because of 

\Locale::getDefault() is 'default'

----------------------------------

new IntlDateFormatter('default'); => PHP Fatal error
new IntlDateFormatter('de'); => OK
new IntlDateFormatter('en'); => OK

### Possible Solution

In
Symfony\Component\HttpFoundation\Request::setPhpDefaultLocale(string $locale)
the $locale cannot have the value "default"

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ghost** [comment]
Unfortunately, it won't be that easy. The error occurs for me in a project that renders a form with data coming from a database.
Specifically, the Doctrine Entity has a DateTime field which is output as an HTML datepicker.
That's why I can't imagine a small example application right now.

With PHP 8.1.24 no exception is thrown.

**Comment by ro0NL** [comment]
can you debug where string "default" comes from? Maybe it's an application issue.

**Comment by xabbuh** [comment]
Then you will need to debug yourself where `default` is passed to `Locale::setDefault()` (which is likely the cause for your issue).

**Comment by derrabus** [comment]
Related: php/php-src#12561

Given that this is a BC break in PHP itself, I'd like to see it resolved upstream first before we implement any workaround on our side.

**Comment by mpdude** [comment]
For completeness, this was also reported in #52315

**Comment by derrabus** [comment]
The issue should be gone with the next releases of PHP 8.1/8.2, but it'll bite you again when you upgrade to PHP 8.3.

Anyhow, I'd like to close the issue because this is probably not a bug in Symfony. At least I'm not aware that we use the string `'default'` as a locale anywhere.

**Comment by mpdude** [comment]
Does Symfony require that the locales you want  to use (e. g. parse from the request) be generated as locales on the system?

If I understand things correctly, setting a locale that is not available/generated on the system will cause an exception as soon as the IntlDateFormatter is used?

**Comment by xabbuh** [comment]
> Does Symfony require that the locales you want to use (e. g. parse from the request) be generated as locales on the system?

if the locale is never forwarded to classes that require valid locales, you could theoretically use arbitrary strings as locales if I am not mistaken

**Comment by ghost** [comment]
The "default" comes from a misconfigured routing setting in /config/routes/attributes.yaml

api_public:
  resource:
    path: ../../src/ApiPublic/Controller/
    namespace: App\ApiPublic\Controller
  type: attribute
  schemes: '%app.secure_scheme%'
  host:
    default: '%app.domain.api_pub%'    <=== there it is

after changing to a valid locale like 'en' the Exception was not thrown again

**Comment by filozofer** [comment]
For information, I post in the php related issue, the bug still exist in 8.2.12 which is the lastest at the moment : 
https://github.com/php/php-src/issues/12282

**Comment by Nayte91** [comment]
I can whitness that the issue is back with PHP 8.3.0, on a SF 7.0.1 project:
"An exception has been thrown during the rendering of a template ("Found unconstructed IntlDateFormatter").
I can whitness that the issue is still here with PHP 8.2.13 for me, but is not here (everything works accordingly) on previous version, example randomly given PHP 8.2.10.
My test: 
- localhostproject/en/index --> OK every time,
- localhostproject/jp/index --> problematic behavior.
