### ISSUE TITLE
Stimulus controllers no longer loading 

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#52405]
### Symfony version(s) affected

6.4

### Description

Until recently, installing a ux component with asset mapper setup everything so that stimulus controllers from bundles worked, and it no longer does.

### How to reproduce

```bash
symfony new stimulus-bug --webapp --version=next --php=8.2 && cd stimulus-bug
composer config minimum-stability dev
composer config extra.symfony.allow-contrib true
composer req symfony/asset-mapper:^6.4
composer req symfony/stimulus-bundle:2.x-dev
composer req symfony/ux-chartjs

bin/console make:controller Simple -i
cat > templates/simple.html.twig <<END
{% extends 'base.html.twig' %}

{% block body %}
     <div {{ stimulus_controller('hello') }}>Hello?</div>

     <div {{ stimulus_controller('@symfony/ux-chartjs') }}>
     chart will go here.
     </div>
{% endblock %}
END
symfony server:start -d
symfony open:local --path=/simple
```

Although the stimulus chart needs data, we should get something, even an error message an initialization, in the console, but nada.

### Possible Solution

Could it be an issue with recipes?  

### Additional Context

In the console, I used to see connect information from stimulus.

![image](https://github.com/symfony/symfony/assets/619585/14ab8b37-3437-4470-8e71-2a24ae1944d5)

**Comment by weaverryan** [comment]
Fixed at https://github.com/symfony/ux/pull/1240
