### ISSUE TITLE
[HttpFoundation][5.4.30] 

### ISSUE THREAD

**Issue by tsukasa-mixer** [symfony/symfony#52419]
### Symfony version(s) affected

5.4.30

### Description

https://github.com/symfony/http-foundation/commit/2213955e8653e84b84566bc3f952f4c43a30b71c

Create many warnings on php 7.2 and not identical work on php 7.2\8.1

 - Uninitialized string offset: 0 
   /HeaderUtils.php(266)
   
- $separators on 7.2 possible false

### How to reproduce

run on php 7.2-7.4

### Possible Solution

```php

    private static function groupParts(array $matches, string $separators, bool $first = true): array
    {
        $separator = $separators[0];
        $separators = substr($separators, 1) ?: '';
```

**Comment by xabbuh** [comment]
Do you have an example of a header that leads to this failure?

**Comment by tsukasa-mixer** [comment]
`new SymfonyResponse()`

```
#0 .../vendor/symfony/http-foundation/HeaderUtils.php(267): Uninitialized string offset: 0
#1 .../vendor/symfony/http-foundation/HeaderUtils.php(298): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], '', false)
#2 .../vendor/symfony/http-foundation/HeaderUtils.php(298): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], false, false)
#3 .../vendor/symfony/http-foundation/HeaderUtils.php(73): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], '=')
#4 .../vendor/symfony/http-foundation/HeaderBag.php(291): Symfony\\Component\\HttpFoundation\\HeaderUtils::split('no-cache, privat...', ',=')
#5 .../vendor/symfony/http-foundation/ResponseHeaderBag.php(135): Symfony\\Component\\HttpFoundation\\HeaderBag->parseCacheControl('no-cache, privat...')
#6 .../vendor/symfony/http-foundation/ResponseHeaderBag.php(36): Symfony\\Component\\HttpFoundation\\ResponseHeaderBag->set('Cache-Control', '')
#7 .../vendor/symfony/http-foundation/Response.php(217): Symfony\\Component\\HttpFoundation\\ResponseHeaderBag->__construct([])
#8 ...: Symfony\\Component\\HttpFoundation\\Response->__construct()

**Comment by xabbuh** [comment]
I tried to reproduce but failed to do so (see #52423). Also, the line numbers in your stack trace do not match the line numbers in the code. Can you debug a bit more yourself what is going on here?

**Comment by xabbuh** [comment]
Could it be that you accidentally ran the code using PHP 5 where `substr()` indeed returns `false` (see https://3v4l.org/VWoJS)?

**Comment by tsukasa-mixer** [comment]
Sorry, the lines are incorrect due to changes during the debugging process.

I was still debugging seeing your comments, and found out that this problem only appears with `mbstring.func_overload >= 2`

Correct stack trace:
```
#0 .../vendor/symfony/http-foundation/HeaderUtils.php(258): "Uninitialized string offset: 0"
#1 .../vendor/symfony/http-foundation/HeaderUtils.php(289): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], '', false)
#2 .../vendor/symfony/http-foundation/HeaderUtils.php(289): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], false, false)
#3 .../vendor/symfony/http-foundation/HeaderUtils.php(71): Symfony\\Component\\HttpFoundation\\HeaderUtils::groupParts([...], '=')
#4 .../vendor/symfony/http-foundation/HeaderBag.php(291): Symfony\\Component\\HttpFoundation\\HeaderUtils::split('no-cache, privat...', ',=')
#5 .../vendor/symfony/http-foundation/ResponseHeaderBag.php(135): Symfony\\Component\\HttpFoundation\\HeaderBag->parseCacheControl('no-cache, privat...')
#6 .../vendor/symfony/http-foundation/ResponseHeaderBag.php(36): Symfony\\Component\\HttpFoundation\\ResponseHeaderBag->set('Cache-Control', '')
#7 .../vendor/symfony/http-foundation/Response.php(217): Symfony\\Component\\HttpFoundation\\ResponseHeaderBag->__construct([])
#8 ...: Symfony\\Component\\HttpFoundation\\Response->__construct()
```

minimal case
```php

ini_set('display_errors', true);
error_reporting( E_ALL);


require_once '../vendor/autoload.php';

new \Symfony\Component\HttpFoundation\Response();
```

**Comment by tsukasa-mixer** [comment]
Perhaps the `mb_substr` function inherited behavior from php5

**Comment by tsukasa-mixer** [comment]
I also tested the `mb_substr` function, and it turned out that it behaves this way only with the `mbstring.fuc_overload` setting enabled, if the setting is turned off, then there are no problems with the `mb_substr` function

**Comment by stof** [comment]
You should not be using `mbstring.func_overload` (which is deprecated anyway) as this changes PHP functions in an incompatible  way.

**Comment by tsukasa-mixer** [comment]
Yes, I know.  We are now moving to php8.1, but for now we are forced to work in an environment compatible with previous versions.  And there were such conditions from the very beginning.  And this behavior was very unexpected.  In principle, this option greatly interferes with the project, but there is simply no way to turn it off everywhere.

**Comment by tsukasa-mixer** [comment]
As a solution, we have now frozen the dependency on 5.4.28.  And I reported the error initially without knowing about this feature of the behavior of this option.  I’m not even sure that at the moment this problem will appear at least for anyone, and of course it’s up to you to decide whether it’s worth filing a fix for such a potential problem.

**Comment by nicolas-grekas** [comment]
Please send a PR if you figure out a simple way (and non invasive way) to handle your case seamlessly.

**Comment by xabbuh** [comment]
#52474 should achieve that

@tsukasa-mixer Can you confirm?

**Comment by tsukasa-mixer** [comment]
> #52474 should achieve that
> 
> @tsukasa-mixer Can you confirm?

Yes, thanks, this completely solves the problem.
