### ISSUE TITLE
[Console] Cannot change input arguments on ConsoleCommandEvent

### ISSUE THREAD

**Issue by fschmtt** [symfony/symfony#52415]
### Symfony version(s) affected

* 6.3
* 5.4

### Description

When subscribing to the `console.command` and modifying the input arguments, the command receives the original, unmodified arguments.

### How to reproduce

Create a subscriber changing the input arguments, e.g.:

```php
class ConsumeMessagesSubscriber implements EventSubscriberInterface
{
    public const LOW_PRIORITY_QUEUE = 'low_priority';

    public static function getSubscribedEvents(): array
    {
        return [
            ConsoleEvents::COMMAND => 'onMessengerConsume',
        ];
    }

    public function onMessengerConsume(ConsoleCommandEvent $event): void
    {
        $command = $event->getCommand();

        if ($command === null) {
            return;
        }

        if ($command->getName() !== 'messenger:consume') {
            return;
        }

        $receivers = $event->getInput()->getArgument('receivers');

        if (!\in_array(self::LOW_PRIORITY_QUEUE, $receivers, true)) {
            $receivers[] = self::LOW_PRIORITY_QUEUE;
            $event->getInput()->setArgument('receivers', $receivers);
        }
    }
}
```

Run `bin/console messenger:consume async`. The subscriber should add `low_priority` as an additional `receiver`. The command receives the unmodified input argument, though:

```bash
❯ php bin/console messenger:consume async

 [OK] Consuming messages from transport "async".
```

### Possible Solution

Possibly the input arguments get bound too early. They are bound in both
* https://github.com/symfony/symfony/blob/6c3d3770c166711a9440778ae43f06999c668292/src/Symfony/Component/Console/Command/Command.php#L285
* https://github.com/symfony/symfony/blob/6c3d3770c166711a9440778ae43f06999c668292/src/Symfony/Component/Console/Application.php#L237

**Comment by OskarStark** [comment]
Can you confirm this bug is also present in 5.4?

**Comment by fschmtt** [comment]
Yes, just tested this, can confirm this bug exists in 5.4, too.

**Comment by chalasr** [comment]
This is a [known limitation](https://github.com/symfony/symfony/issues/19441). PR welcome if one wants to give it a try, but I'm going to close here since we already went back & forth without success on this one and concluded it was a won't fix.

**Comment by shyim** [comment]
Does it make sense then to mention this in the event class?

**Comment by chalasr** [comment]
Looks sensible to me yes

**Comment by Solutionsupersonic** [comment]
> Does it make sense then to mention this in the event class?





https://dissenting-document-body.github.io/Xvva3gPX0Yv6ZH1h3elKE96FGzvqjWcsa6VhWsKumhQul/
