### ISSUE TITLE
SensioFrameworkExtraBundle v6.2.10 shows deprecation error 

### ISSUE THREAD

**Issue by vivianmartinez** [symfony/symfony#52424]
### Symfony version(s) affected

6.3.7

### Description

SensioFrameworkExtraBundle class doesn´t specify the value return type on method build, this might lead to deprecation notices.

### How to reproduce

Manually add sensio/framework-extra-bundle ^6.2 to your composer dependencies. When a request is executed to the server check your logs, you'll get an error message that look like this:

_deprecation.INFO: User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Symfony\\Component\\HttpKernel\\Bundle\\Bundle::build()\" might add \"void\" as a native return type declaration in the future. Do the same in child class \"Sensio\\Bundle\\FrameworkExtraBundle\\SensioFrameworkExtraBundle\" now to avoid errors or add an explicit @return annotation to suppress this message._

Then, if you've installed before symfony/monolog-bundle, you can see the error message:

_deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\"._

### Possible Solution

Go to ` \vendor\sensio\framework-extra-bundle\src\SensioFrameworkExtraBundle.php` and add an annotation on method build of class SensioFrameworkExtraBundle to specify return type:

`

    class SensioFrameworkExtraBundle extends Bundle
    {
       /**
        * @return void
        */
        public function build(ContainerBuilder $container)
        {
           //...
        }
    }
`

**Comment by HypeMC** [comment]
The bundle is no longer maintained, see https://github.com/sensiolabs/SensioFrameworkExtraBundle
