### ISSUE TITLE
[HttpKernel] Uninitialized property in the abstract Bundle class

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#52436]
### Symfony version(s) affected

7.0

### Description

In a Symfony bundle (https://github.com/symfonycorp/connect) we have this:

```php
namespace SymfonyCorp\Connect;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class SymfonyConnectBundle extends Bundle
{
    public function getContainerExtension(): ?ExtensionInterface
    {
        if (null === $this->extension) {
            $this->extension = new SymfonyConnectExtension();
        }

        return $this->extension;
    }

    // ...
}
```

It works fine in all Symfony versions up to and including 6.4.

But, in 7.0 (beta2) we're seeing this error:

```
Typed property Symfony\Component\HttpKernel\Bundle\Bundle::$extension
must not be accessed before initialization.
```

The error happens because this line in 6.4:

https://github.com/symfony/symfony/blob/8a69f6766815bd457ce12ab6a04293207efcec52/src/Symfony/Component/HttpKernel/Bundle/Bundle.php#L28

Turned into this line in 7.0:

https://github.com/symfony/symfony/blob/fa590af43d297995b24511d04f805550ffcadc4a/src/Symfony/Component/HttpKernel/Bundle/Bundle.php#L28

If I make this change in Symfony code, everything works again:

```diff
-protected ExtensionInterface|false $extension;
+protected ExtensionInterface|false|null $extension = null;
```

So, what should we do here? Thanks!

### How to reproduce

Use this bundle https://github.com/symfonycorp/connect in a Symfony 7 application.

**Comment by stof** [comment]
Turning a protected property into one that may not be initialized is indeed a bad idea. It is very surprising for child classes to have to deal with the uninitialized state of a parent property.

@javiereguiluz can you send a PR with your patch ? We already did similar changes on other protected properties for which the initialization is delayed.
