### ISSUE TITLE
[Console][FrameworkBundle] `--profile` option might not be set on every command

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#52433]
### Symfony version(s) affected

6.4

### Description

With the new command profiling feature, a event listener was added that grabs the `profile` option from the command inputs:
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/EventListener/ConsoleProfilerListener.php#L62

Normaly that option is added to every command over the Application: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L47

However not every command is executed over the Application class, e.g. during unit tests with the `CommandTester` or by just dispatching the `ConsoleCommandEvent` directly.

In those cases the following error is thrown:
```
Symfony\Component\Console\Exception\InvalidArgumentException: The "profile" option does not exist.

/.../symfony/console/Input/Input.php:127
/.../symfony/framework-bundle/EventListener/ConsoleProfilerListener.php:62
/.../symfony/event-dispatcher/Debug/WrappedListener.php:116
/.../symfony/event-dispatcher/EventDispatcher.php:206
/.../symfony/event-dispatcher/EventDispatcher.php:56
```

### How to reproduce

Use the command tester to test a manually created command:

```php
$command = new MyCommandToTest();
$commandTester = new CommandTester($command);

$commandTester->run($input);
```

Note: this differs from how the command tester is documented: https://symfony.com/doc/current/console.html#testing-commands
As there the command is fetched from the application, however, to properly unit test commands without having the whole application booted up, I think the above code is valid for testing commands and should be supported.

### Possible Solution

Check if the option exists before accessing it -> PR incoming

**Comment by GromNaN** [comment]
Hello, I tried to reproduce the error, but the [`Symfony\Component\Console\Tester\CommandTester`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Console/Tester/CommandTester.php) class doesn't have a `run` method and it doesn't instantiate the `ConsoleProfilerListener`.
Could you provide more information on how to reproduce?

**Comment by BafS** [comment]
Same issue on 6.4 BETA 2

```
In Input.php line 141:

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "profile" option does not exist.


Exception trace:

 at .../api/vendor/symfony/console/Input/Input.php:141
 Symfony\Component\Console\Input\Input->getOption() at .../api/vendor/symfony/framework-bundle/EventListener/ConsoleProfilerListener.php:62
 Symfony\Bundle\FrameworkBundle\EventListener\ConsoleProfilerListener->initialize() at .../api/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116
...
```

---

To give more details:

We are overriding `Application` because we don't want to have the `-e` shortcut (which is typically use for "email").

We have something like that:

```php
final class Application extends SymfonyFrameworkApplication
{
    public function __construct(KernelInterface $kernel)
    {
        parent::__construct($kernel);

        $inputDefinition = $this->getDefaultInputDefinition();
        $inputDefinition->addOptions([
            new InputOption('--env', null, InputOption::VALUE_REQUIRED, 'The Environment name.', $kernel->getEnvironment()),
            new InputOption('--no-debug', null, InputOption::VALUE_NONE, 'Switches off debug mode.'),
        ]);

        $this->setDefinition($inputDefinition);
    }
}
```


 and the `InputOption` was not set with "profile". Easy to fix but it's still a BC in my opinion.
