### ISSUE TITLE
[HttpClient] Issues with debug panel 

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#52441]
### Symfony version(s) affected

6.3.latest

### Description

I used the profiler, and noticed many things that seems weird / wrong

### The copy as curl button

![image](https://github.com/symfony/symfony/assets/408368/6dca1992-ff29-4b6a-a5a8-d82271629247)

When I click on the button I got:

```bash
curl \
  --compressed \
  --header 'Due to a bug in curl 7.64.0, the debug log is disabled; use another version to work around the issue'```
```

1. the URL is missing
2. the method is missing - (occurs even if method != GET)
3. the headers are missing
4. the current header is wrong

### Duration

![image](https://github.com/symfony/symfony/assets/408368/c092b84e-729e-4d92-9449-0e1809c1a779)

I'm not sure which total I must read - It could be nice to display it in the profiler directly, like with doctrine query

**Comment by stof** [comment]
Building the curl command relies on being able to read the debug log.

I guess this weird header being reported is a weird way to report that it could not build the command (probably because it is actually the http client reporting a weird info instead)

**Comment by stof** [comment]
And with your curl CLI, you get 1.54ms, so is it really unlikely to get 1.47ms when doing that in Symfony ?

**Comment by lyrixx** [comment]
You are right about the timing, I'll edit my post

**Comment by stof** [comment]
I just opened a PR to remove this `Copy as cURL` when the command cannot be built due to using the version of curl that prevents collecting the debug info.

**Comment by lyrixx** [comment]
> Building the curl command relies on being able to read the debug log.

FTR:

```console
$ php --re curl | head
Extension [ <persistent> extension #24 curl version 8.1.20 ] {
```

But the message is:

> Due to a bug in curl 7.64.0, the debug log is disabled; use another version to work around the issue

Something looks wrong anyway

**Comment by stof** [comment]
@lyrixx this is the version of the php curl extension (which is the same than the PHP version when it is bundled in PHP), not of libcurl (there is no version 8.1.20 of curl anway).

Use `composer show -p |grep curl` as the easy way to see it as composer already extracts the version for you from the phpinfo.

**Comment by stof** [comment]
Alternatively, use `php -i |grep cURL`

**Comment by lyrixx** [comment]
ahhh, okay. Thanks 

```console
$ composer show -p |grep curl
ext-curl                8.1.20      The curl PHP extension
lib-curl                7.64.0      The curl library
lib-curl-libssh2        1.8.0       curl libssh2 version
lib-curl-openssl        1.1.1.14    curl OpenSSL version (1.1.1.14)
lib-curl-zlib           1.2.11      curl zlib version

$ php -i |grep cURL
cURL support => enabled
cURL Information => 7.64.0
```

Indeed, the curl version is ... the bad one!

**Comment by nicolas-grekas** [comment]
> curl version 7.64.0 was released on February 6 2019

it's time to update ;)
