### ISSUE TITLE
[AssetMapper] jQuery plugin fails locally but not remotely

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#52467]
### Symfony version(s) affected

Assetmapper 6.4

### Description

I'm trying to load a jquery plugin on datatables.  I'm able to get it to work if the libraries are loaded remotely, but not when assetmapper copies them to the local directory.  In throws a 404 related to jquery

![image](https://github.com/symfony/symfony/assets/619585/f3c46b8d-0c0d-4a7a-9766-019738ffc101)

### How to reproduce

```bash
symfony new bug --webapp --version=next && cd bug
composer req symfony/asset-mapper
bin/console importmap:require datatables.net-bs5  datatables.net-select-bs5
bin/console make:controller AppController
sed -i "s|Route('/app'|Route('/'|" src/Controller/AppController.php

cat > assets/app.js <<'END'
import jquery from 'jquery'
import DataTables from 'datatables.net-bs5'
import 'datatables.net-select-bs5';
END
symfony server:start -d 
symfony open:local
```
I originally thought it was an issue with the datatables library, so I created an example script to show the problem, using the esm urls instead of the local files that assetmapper create, but I couldn't recreate the bug.

```html
    <script type="importmap">
      {
    "imports": {
        "datatables.net-bs5": "https://cdn.jsdelivr.net/npm/datatables.net-bs5@1.13.7/+esm",
        "datatables.net-select-bs5": "https://cdn.jsdelivr.net/npm/datatables.net-select-bs5@1.7.0/+esm"

    }
}
</script>
    <script type="module">
      

      import DataTable from 'datatables.net-bs5'
        import 'datatables.net-select-bs5'
        console.log('datatables loaded.');
        let t = new DataTable('#example');
        /* console.log(t.id); */

    </script>
```

See https://jsfiddle.net/tacman1123/b2f3hj08/44/

I suspect this has something to do with the 'global' jquery, webpack had a autoProvideJquery() option to help with this.  I'll also ask the library author, but since I can't provide a jsfiddle example of it not working, I'm wondering if perhaps it's related to AssetMapper.

**Comment by monteiro** [comment]
Hi @tacman , you should import another package:

`bin/console importmap:require datatables.net`

and in your app.js:

```js
import DataTable from 'datatables.net';
console.log('datatables loaded.');
let t = new DataTable('#example');
console.log(t);
```

That special package imports jquery itself inside, according to their [docs](https://datatables.net/blog/2022-11-10-esm).

**Comment by tacman** [comment]
datatables.net is a dependency of datatables.net-bs5, so it automatically gets added to importmap.

Nonetheless, the error exists even when specifying it and removing jquery.

```
symfony new bug --webapp --version=next && cd bug
composer req symfony/asset-mapper
bin/console importmap:require datatables.net datatables.net-bs5  datatables.net-select datatables.net-select-bs5
bin/console make:controller AppController
sed -i "s|Route('/app'|Route('/'|" src/Controller/AppController.php

cat > assets/app.js <<'END'
import DataTable from 'datatables.net';
import 'datatables.net-bs5'
import 'datatables.net-select'
import 'datatables.net-select-bs5';
END
symfony server:start -d 
symfony open:local
```

This produces the error where it can't find jquery:

![image](https://github.com/symfony/symfony/assets/619585/c4e4d8d9-e356-406a-adc7-bfc6da47ac05)

So I explicitly add jquery, and the error still persists, although slightly different.

```bash
cat > assets/app.js <<'END'
import 'jquery';
import DataTable from 'datatables.net';
import 'datatables.net-bs5'
import 'datatables.net-select'
import 'datatables.net-select-bs5';
END
symfony open:local
```
I think there's an issue with the select module, but I can't tell if the problem is with assetmapper and the module being local, or a problem with the source library.

**Comment by tacman** [comment]
To be clear, this works with datatables.net, it's the select plugin that's causing the problem.

**Comment by monteiro** [comment]
@tacman what is this supposed to do besides select the column and order it?

<img width="488" alt="Captura de ecrã 2023-11-07, às 11 14 11" src="https://github.com/symfony/symfony/assets/74459/5c4fa588-33b7-47e2-b107-dfd7e8c5dbcb">

The only missing thing here is the bootstrap theme?

**Comment by tacman** [comment]
I had removed all the other code in the name of simplicity.  I just wanted to javascript modules to load.

SearchPanes is dependent on Select, so in my longer example, I have select and searchpanes and more data.   I'll add that as an example, but since importing Select was showing an error, I removed everything after it.

**Comment by tacman** [comment]
The "real" code is a stimulus controller inside a bundle, but all the plugins have been commented out because of the above error. 

https://github.com/survos/SurvosGridBundle/blob/main/assets/src/controllers/grid_controller.js

**Comment by monteiro** [comment]
I think the issue comes from the select plugin:
If you open the 404 error in the chrome dev console:
<img width="1312" alt="Captura de ecrã 2023-11-08, às 09 30 43" src="https://github.com/symfony/symfony/assets/74459/cb663e11-0076-437b-9cf5-c54fc489a0af">

You can see the file where the error comes:

```
/**
 * Bundled by jsDelivr using Rollup v2.79.1 and Terser v5.19.2.
 * Original file: /npm/datatables.net-select-bs5@1.7.0/js/select.bootstrap5.mjs
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
import"/npm/jquery@3.7.1/+esm";import e from"datatables.net-bs5";export{default}from"datatables.net-bs5";import"/npm/datatables.net-select@1.7.0/+esm";
/*! Bootstrap 5 styling wrapper for Select
 * © SpryMedia Ltd - datatables.net/license
 */
```

He is trying to import jquery/select plugin from an npm folder (which is not mapped from our side):

<img width="675" alt="Captura de ecrã 2023-11-08, às 09 32 02" src="https://github.com/symfony/symfony/assets/74459/239de25c-8b06-486d-bc08-1f34f35055b0">

<img width="470" alt="Captura de ecrã 2023-11-08, às 09 31 50" src="https://github.com/symfony/symfony/assets/74459/fd960e3d-6ae4-4f95-aea6-d2010c6451a0">


Not mapped from our side:

```
bin/console debug:asset-map
```

<img width="1352" alt="Captura de ecrã 2023-11-08, às 09 33 47" src="https://github.com/symfony/symfony/assets/74459/6e0a4d8d-8add-4250-bfc7-fc9bddddd729">

**Comment by monteiro** [comment]
Importing like this it does not give 404 error:

```
 bin/console importmap:require datatables.net-select
```

This is the good package, that does not have any require assuming the npm folder.
The issue also can come from wrappers on libraries that do require.

Maybe @weaverryan can help us here. On those libraries with those weird wrappers. We have to import the right lib, without the explicit requires.

**Comment by tacman** [comment]
Thanks.  I started to write a [bug report](https://datatables.net/forums/discussion/77563/importing-jquery-select-plugin-from-an-npm-folder#latest) on the datatables side, but couldn't reproduce the error outside of assetmapper, so maybe it is something that Ryan can fix or at least give guidance to the datatables author.

**Comment by tacman** [comment]
@weaverryan , can you take a quick peek at this and see if I should ask for the library author to research it more?  Or if it's something that AssetMapper can fix?  Thanks.

**Comment by weaverryan** [comment]
I'm on it - another new `import` syntax that the regex needs to support. I have it working locally - just need to finish the tests.
