### ISSUE TITLE
[Serializer] @method getSupportedTypes return type wrong place

### ISSUE THREAD

**Issue by darthf1** [symfony/symfony#52477]
### Symfony version(s) affected

6.3.0 and later

### Description

https://github.com/symfony/symfony/blob/d308e2cd064d6b73e075c278708b9eeb65bf0d35/src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php#L22

https://github.com/symfony/symfony/blob/d308e2cd064d6b73e075c278708b9eeb65bf0d35/src/Symfony/Component/Serializer/Normalizer/DenormalizerInterface.php#L25

On both these lines, the phpdoc return type is behind the method name, whilst it should be in front.

### How to reproduce

https://phpstan.org/r/af3fd1c7-38d4-4a3c-9f73-008c4e9d2f07

vs 

https://phpstan.org/r/d131e2fa-55e3-4d72-b14f-81f84c399d86

### Possible Solution

Change

```
* @method getSupportedTypes(?string $format): array 
```

to

```
* @method array getSupportedTypes(?string $format)
```

**Comment by nicolas-grekas** [comment]
Can you please send a PR to fix this?
