### ISSUE TITLE
[Mailer] Make RoundRobinTransport retryPeriod configurable

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#52551]
### Description

RoundRobinTransport constructor has `retryPeriod` set to 60 seconds. This cannot be configured right now.

Let's say all the transports fail (e.g. email address with domain that does not exist).
**Problems:** 
1. When sending more than one email synchronously we can't send emails following the one that failed. We have to `sleep(x)` where x >= 60sec. (of course we have to handle the TransportException thrown by invalid email but this is another topic)
2. When using Messenger and async emails we don't have to worry about handling TransportException because invalid message will be sent back to the queue **however** the worker cannot consume another messages for the next 60 seconds. Also logs will be flooded with exceptions because in this 60s window a lot of messages could be tried.

**Comment by alamirault** [comment]
If we want to support it in DSN, we should probably edit 
https://github.com/symfony/symfony/blob/b004c3c6d120c4d16988c97bf01268adfe960cb1/src/Symfony/Component/Mailer/Transport.php#L107-L152

Is there any RFC/good practice for good syntax ?

**Comment by ghost** [comment]
@alamirault Yes, this method would have to be updated. About the good practice, I think that this should be done in a standard way, i.e. option are added as after the question mark (`?`), so it would be `MAILER_DSN="roundrobin(postmark+api://ID@default sendgrid+smtp://KEY@default)?retry_period=15"`

**Comment by gaelreyrol** [comment]
This issue is a duplicate of #50981.

**Comment by xabbuh** [comment]
closing in favour of #50981 then
