### ISSUE TITLE
[String] Weird behaviour of `trimStart`: `Product[url]` returned as `l]` when `AbstractUnicodeString::trimStart('Product[')`

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#52552]
### Symfony version(s) affected

6.3

### Description

This is an extract of the method `AbstractUnicodeString::trimStart()`:

```php
$chars = preg_quote('Product[');
echo preg_replace("{^[$chars]++}uD", '', 'Product[url]');
```

I expect this to return `url]`, instead, it returns `l]`.

But, the even stranger thing is that this code correctly returns `url]`:

```php
$chars = preg_quote('Test[');
echo preg_replace("{^[$chars]++}uD", '', 'Test[url]');
```

### How to reproduce

- `Product[url]`: https://3v4l.org/49F7P
- `Test[url]`: https://3v4l.org/vu0Zb

### Possible Solution

I have no idea about why it behaves this way: it is completely not understandable to me 😅

### Additional Context

Full code I'm using:

```php
u($crawler->attr('name'))
    ->trimStart($formEntity . '[')
    ->trimEnd(']')
    ->toString()
```

**Comment by derrabus** [comment]
You're asking to remove the characters (!) `P`, `r`, `o`, `d`, `u`, `c`, `t` and `[` from the beginning of the string and that's what the method does.

**Comment by Aerendir** [comment]
You are right 🤦
