### ISSUE TITLE
AssetMapper equivalent of `yarn audit` ?

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#52554]
### Description

The premise of AssetMapper is to use as much modern web feature to avoid using build system.

It replaces a lot of `yarn` command but one is missing 

`yarn audit`

so currently by using assetmapper one may loose an important piece of proactive security

it would be great to have a command 

`php bin/console importmap:audit`

**Comment by derrabus** [comment]
Makes sense to me, WDYT @weaverryan?

@allan-simon Do you want to work on that feature?

**Comment by allan-simon** [comment]
@derrabus  I will explore these days how it could be implemented 

I will check the `importmap:update` as I think it contains a lot of primitive that will be common

**Comment by smnandre** [comment]
Something more than https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/Command/ImportMapAuditCommand.php ?

**Comment by allan-simon** [comment]
damn I only checked the 6.3 tag :facepalm:   sorry for the noise

and indeed it's now present in the 6.4 upcoming documentation https://symfony.com/doc/6.4/frontend/asset_mapper.html#run-security-audits-on-your-dependencies

**Comment by derrabus** [comment]
> Something more than https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/Command/ImportMapAuditCommand.php ?

Awesome! 🚀

**Comment by allan-simon** [comment]
here's go my weekend project haha I will need to find something to do in doctrine :P

**Comment by weaverryan** [comment]
Haha - sorry, but I always have more ideas if you’re ever searching ;)
