### ISSUE TITLE
Please remove  #StandWithUkraine CLi Message

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [symfony/symfony#52577]
### Description

Dear Team,

I try to make this as neutral as possible. While many have written already about how irritating it is to see one-sided political messages in open source software, even composer became now reasonable and removed it again. 

Can we please do the same here and get back to an approach that allows to use open source software without oversimplifying a complex geopolitical situation?

It would be much appreciated.
Many thx!

### Example

```
Symfony 6.2.14 (env: dev, debug: true) #StandWithUkraine https://sf.to/ukraine
```

Should become again

`Symfony 6.2.14 (env: dev, debug: true)`

**Comment by fabpot** [comment]
We did it last week.
See [52568](https://github.com/symfony-cli/symfony-cli/commit/7b1629faea560cc8b0c917872fae3ca62d13f250)
And https://symfony.com/blog/symfony-is-all-about-its-community

**Comment by Andreas-Schoenefeldt** [comment]
Thx a lot 👍

**Comment by symbioticphp** [comment]
The banner was removed, but the residue remained. Now you should use this framework with caution, and it's not far to the backdoors in your packages!
