### ISSUE TITLE
[doctrine-messenger] Error only Oracle database ORA-01008

### ISSUE THREAD

**Issue by javiercno** [symfony/symfony#52570]
### Symfony version(s) affected

6.3.0

### Description

When execute command php bin/console messenger:consume async, return error database ORA-01008

### How to reproduce

install symfony 6.3
configure symfony messenger with transport doctrine oracle

### Possible Solution

Variable $query is override in platform oracle.
https://github.com/symfony/doctrine-messenger/blob/6.3/Transport/Connection.php#L184

$query original contains parameters need.
https://github.com/symfony/doctrine-messenger/blob/6.3/Transport/Connection.php#L214

**Comment by xabbuh** [comment]
Thank you for the report. Can you please check if #52581 would fix your issue?

**Comment by javiercno** [comment]
Thanks, its correct.
https://github.com/symfony/symfony/pull/52581

**Comment by xabbuh** [comment]
Thank you for the feedback! 👍
