### ISSUE TITLE
[AssetMapper]  Allow bin/console importmap:require  --download  to take no argument

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#52573]
### Description

Currently (6.3) 

I can either

1. let the 3rd party dependencies to be delivered through a CDN
2. download them and commit them in my repository

It's not great because it feels a step backward on why all package manager let you add in `.gitignore` the `/vendor` , `node_modules` etc. 

I would be great to have a third option `bin/console importmap:require  --download `  that would read the information from importmap.php and download the version so that 

1. the version is pinned to the one in `importmap.php`
2. you don't have to commit them locally

currently I'm working around that by having in my CI a 

`bin/console importmap:require  foo@version  bar@1.2.4 etc.  --download`  as my list of dependencies is minimal (5 entries) but it's an additional burden.

**Comment by maxbeckers** [comment]
Wouldn't it be better for your case to have a new command like `bin/console importmap:install` or maybe  `bin/console importmap:download` (of course only downloading from urls, when a path is defined than ignoring it).

What do you think @weaverryan?

**Comment by allan-simon** [comment]
indeed, I'm just bad at naming :)

**Comment by weaverryan** [comment]
> I would be great to have a third option bin/console importmap:require  --download  that would read the information from importmap.php and download the version so that

This is fixed in 6.4 - it works almost exactly like this :). In fact, all files are downloaded locally (into an `assets/vendor/` directory, which you can then ignore). You run `importmap:install` to populate your `assets/vendor/` directory (identical to the `npm install` or `composer install` workflow).

Cheers!
