### ISSUE TITLE
pcntl PHP extension is required since v6.3.5 with test

### ISSUE THREAD

**Issue by SerheyDolgushev** [symfony/symfony#52586]
### Symfony version(s) affected

v6.3.5

### Description

After v6.3.5 the `messenger:consume` command fails if there is no `pcntl` extension installed/enabled:

```bash
$ php ./bin/console messenger:consume XXX
...
Unable to subscribe to signal events. Make sure that the "pcntl" extension is installed and that "pcntl_*" functions are not disabled by your php.ini's "disable_functions" directive.  
```

### How to reproduce

**Setup env**
```
# Change working directory
cd ~/Projects
# Create new symfony projecy
symfony new symfony63x --version="6.3.*"
# Change working directory
cd symfony63x
# Install symfony/messenger
composer require symfony/messenger
# Install phpunit
composer require --dev symfony/test-pack
```

**Create new tests/ConsumeMessagesCommandTest.php test:**
```php
<?php

declare(strict_types=1);

namespace App\Tests\Command;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\HelperSet;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\Messenger\Command\ConsumeMessagesCommand;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\RoutableMessageBus;
use Symfony\Component\Messenger\Stamp\BusNameStamp;
use Symfony\Component\Messenger\Tests\ResettableDummyReceiver;
use Symfony\Component\Messenger\Transport\Receiver\ReceiverInterface;

class ConsumeMessagesCommandTest extends TestCase
{
    public function testBasicApplicationRun()
    {
        $envelope = new Envelope(new \stdClass(), [new BusNameStamp('dummy-bus')]);

        $receiver = $this->createMock(ReceiverInterface::class);
        $receiver->expects($this->once())->method('get')->willReturn([$envelope]);

        $receiverLocator = $this->createMock(ContainerInterface::class);
        $receiverLocator->expects($this->once())->method('has')->with('dummy-receiver')->willReturn(true);
        $receiverLocator->expects($this->once())->method('get')->with('dummy-receiver')->willReturn($receiver);

        $bus = $this->createMock(MessageBusInterface::class);
        $bus->expects($this->once())->method('dispatch');

        $busLocator = $this->createMock(ContainerInterface::class);
        $busLocator->expects($this->once())->method('has')->with('dummy-bus')->willReturn(true);
        $busLocator->expects($this->once())->method('get')->with('dummy-bus')->willReturn($bus);

        $command = new ConsumeMessagesCommand(new RoutableMessageBus($busLocator), $receiverLocator, new EventDispatcher());
        $command->setHelperSet(new HelperSet());

        $application = new Application();
        $doRunCommand = (new \ReflectionClass($application))->getMethod('doRunCommand');

        $input = new ArrayInput([
            'receivers' => ['dummy-receiver'],
            '--limit' => 1,
        ]);
        $doRunCommand->invokeArgs($application, [$command, $input, new ConsoleOutput()]);
    }
}
```

**Reproduce the issue:**
1. Check the versions:
```bash
% composer show symfony/messenger | grep version
versions : * v6.3.7
% composer show symfony/console | grep version
versions : * v6.3.8
```

2. Run the new test **with** the disabled `pcntl_signal` function:
```
% php -d disable_functions=pcntl_signal ./bin/phpunit --filter testBasicApplicationRun tests/ConsumeMessagesCommandTest.php
...
There was 1 error:

1) App\Tests\Command\ConsumeMessagesCommandTest::testBasicApplicationRun
Symfony\Component\Console\Exception\RuntimeException: Unable to subscribe to signal events. Make sure that the "pcntl" extension is installed and that "pcntl_*" functions are not disabled by your php.ini's "disable_functions" directive.

/Users/sergiid/Projects/symfony-test/symfony63x/vendor/symfony/console/Application.php:1006
/Users/sergiid/Projects/symfony-test/symfony63x/tests/ConsumeMessagesCommandTest.php:52
/Users/sergiid/Projects/symfony-test/symfony63x/vendor/phpunit/phpunit/phpunit:107

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

3. Run the new test **without** disabled `pcntl_signal` function:
```bash
% php ./bin/phpunit --filter testBasicApplicationRun tests/ConsumeMessagesCommandTest.php 
...
OK (1 test, 4 assertions)
```

**Conclusion**
The test fails when `pcntl_signal` is disabled. Which means `pcntl` is required to run `ConsumeMessagesCommand`.

### Possible Solution

https://github.com/symfony/symfony/pull/52575

### Additional Context

1. Initially https://github.com/symfony/symfony/pull/52574 was submitted. But it was closed.
2. I added the test case that demonstrates the issue and submitted https://github.com/symfony/symfony/pull/52575. It was also closed and marked as spam.
3. I tried to reach out to the person who closed previous PRs over Symfony Slack, and was asked to submit an issue:
<img width="847" alt="Screenshot 2023-11-14 at 3 59 04 PM" src="https://github.com/symfony/symfony/assets/166894/506d5225-bc6b-468a-9327-3452f4e62b2e">

**Comment by SerheyDolgushev** [comment]
@stof I am unable to answer you at https://github.com/symfony/symfony/pull/52575#issuecomment-1810074060, because of:

<img width="997" alt="Screenshot 2023-11-14 at 4 01 38 PM" src="https://github.com/symfony/symfony/assets/166894/3170dc25-7a86-49bc-9a42-9adbc77a009c">

I am able to reproduce the issue following the "How to reproduce" steps with latest symfony. Can you please point out the fix in v6.3.6?

**Comment by stof** [comment]
Disabling a single function while still enabling the extension is not a use case we support in Symfony. We cannot guard all our code to check whether an extension is only partially enabled.
You should check without the extension enabled.

The fix done in 6.3.6 was about checking whether the pcntl extension is loaded before using the constants it defines.

**Comment by SerheyDolgushev** [comment]
> Disabling a single function while still enabling the extension is not a use case we support in Symfony. We cannot guard all our code to check whether an extension is only partially enabled. You should check without the extension enabled.
> 
> The fix done in 6.3.6 was about checking whether the pcntl extension is loaded before using the constants it defines.

By disabling `pcntl_signal` function I am emulating the case when `pcntl` extension is not installed so `pcntl_signal` function is not available. I am quite positive that `-d disable_functions=pcntl_signal` and "disabled `pcntl` extension" will lead to the same results in this case.

**Comment by stof** [comment]
No. you are not emulating it. by disabling this function, `extension_loaded('pcntl')` still returns true. And `\defined('SIGTERM')` will also return true.

**Comment by SerheyDolgushev** [comment]
Sorry, but in this context https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php#L40-L43 matters:
```
...
    public static function isSupported(): bool
    {
        return \function_exists('pcntl_signal');
    }
...
```

**Comment by stof** [comment]
@SerheyDolgushev that's not the only thing that matters: https://github.com/symfony/symfony/blob/8f7cb6301e15aa9406bda31ef5b828be3acaadaf/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php#L259-L262

**Comment by SerheyDolgushev** [comment]
So seems like currently the sources depend on the following assumption:

`SIGTERM` constant and `pcntl_signal` function are available only when `pcntl` is installed. If `pcntl` extension is disabled both `SIGTERM` and `pcntl_signal` are unavailable.

For our build we are using `php:8.2-fpm-alpine` and `pcntl` PHP extension was not installed. We were getting the error described in this issue. Installing `pcntl` fixed it. 

So is it possible that `SIGTERM` is defined in cases when `pcntl` PHP extension is not installed?

**Comment by wouterj** [comment]
This was fixed in 6.3.6 and a bug caused the extension to be required for 6.3.5 only. There is no need to investigate any deeper here.

**Comment by SerheyDolgushev** [comment]
Symfony assumes that `SIGTERM` constant is defined only when `pcntl` PHP extension is enabled. But `SIGTERM` constant is also set by [swoole](https://github.com/swoole/swoole-src).

So `SIGTERM` is **set** even if `pcntl` extension is not enabled, but if `swoole` is enabled:
```bash
$ cat tmp/test-pcntl.php 
<?php

var_dump(\defined('SIGTERM'));
var_dump(\extension_loaded('swoole'));
var_dump(\extension_loaded('pcntl'));

$ php tmp/test-pcntl.php 
/XXX/tmp/test-pcntl.php:3:
bool(true)
/XXX/tmp/test-pcntl.php:4:
bool(true)
/XXX/tmp/test-pcntl.php:5:
bool(false)
```

Tagging the author and reviewers of https://github.com/symfony/symfony/pull/51791 @HypeMC @fabian @xabbuh

**Comment by derrabus** [comment]
Thank you for pursuing this issue and sorry if I sounded a bit harsh on Slack. In general, it's a good first step to open an issue where you explain the problem that you're facing. Your initial PR did not do that, and as it turns out wouldn't have solved your problem at all. This discussion helped us understand the motivation behind your change and together we've come to a solution that works better for everyone. 🎉
