### ISSUE TITLE
BUG in DoctrineBridge or in DoctrineBundle ?

### ISSUE THREAD

**Issue by AllanFousse** [symfony/symfony#52614]
### Symfony version(s) affected

6.3

### Description

I call the same page twice.
First time no problem, i got this :
[{"id":1,"nom":"a"},{"id":2,"nom":"b"}]

second time I get an error message :
[critical] Uncaught PHP Exception TypeError: "Doctrine\DBAL\Connection::executeQuery(): Argument #1 ($sql) mu
st be of type string, null given, called in /home/allan/PROBLEME/BUG/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php on line 
33" at /home/allan/PROBLEME/BUG/vendor/doctrine/dbal/src/Connection.php line 1071

### How to reproduce

Create a new 6.3 project with orm

Create this 3 files:

My controller:
```php
class DevController extends AbstractController
{
    #[Route(path: '/')]
    public function dev(ManagerRegistry $managerRegistry): Response
    {
        //$t2 = $managerRegistry->getRepository(Table1::class)->findAll();
        $t2 = $managerRegistry->getRepository(Table1::class)->getAll();
        return new Response(json_encode($t2));
    }
}
```

My entity class:
```php
#[Entity(repositoryClass: Table1Repository::class)]
#[Table(name: "table1")]
class Table1
{
    #[Id]
    #[Column(name: 'id', type: 'integer')]
    public int $id;

    #[Column(name: 'nom', type: 'string')]
    public string $nom;
}
```

My Repository file :
```php
class Table1Repository extends EntityRepository
{
    public function getAll(): mixed
    {
        $query = $this->createQueryBuilder('t');
        return $query->getQuery()->getResult();
    }
}
```

### Possible Solution

No idea

**Comment by AllanFousse** [comment]
For information, problem occurs in prod not in dev

**Comment by xabbuh** [comment]
Which versions of doctrine/dbal and doctrine/orm do you use?

**Comment by mbabker** [comment]
You might be hitting https://github.com/doctrine/orm/issues/11063

**Comment by nicolas-grekas** [comment]
As discussed on https://github.com/doctrine/orm/issues/11063, the issue is that Doctrine relies on an undocumented behavior of `__sleep` that's not implemented in VarExporter.
We can fix that now that we spotted it.

**Comment by AllanFousse** [comment]
doctrine-bundle : 2.11.1 / orm : 2.17.0 / dbal : 3.7.1
