### ISSUE TITLE
[Cache] respect XDG_CACHE_HOME

### ISSUE THREAD

**Issue by danepowell** [symfony/symfony#52622]
### Description

Currently, filesystem caches are created by default in the system temporary directory. I propose instead that they respect the XDG spec, which says this:

> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

If maintainers approve of this, I'm happy to open a PR.

### Example

The default location would be `$HOME/.cache/symfony` instead of `/tmp/symfony-cache`.

**Comment by nicolas-grekas** [comment]
We already have APP_CACHE_DIR so I'm not sure. I'm also not sure this env var applies to apps.
