### ISSUE TITLE
[BCBreak][DomCrawler] UriResolver is broken with non-url format

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#52628]
### Symfony version(s) affected

not releases yet - but 6.4 - but 6.3.next

### Description

This PR introduced a BC break : https://github.com/symfony/symfony/pull/52579

script:
```php
#!/usr/bin/env php
<?php

require __DIR__ . '/src/Symfony/Component/DomCrawler/vendor/autoload.php';

$ret =  Symfony\Component\DomCrawler\UriResolver::resolve('https://', 'https://jolicode.com/');

echo "$ret\n";
```

#### Before:

On 0a30c9be8e (direct parent)

```console
php test.php 
https://
```

#### After

on 89009aa128879e79acee273bfcb96e7db491ee64:
```console
$ php test.php 
https://jolicode.com/https://
```

## How does a browser react?

Note: on a webpage, if I put `<a href="http://">test</a>`, and I click on it, I'll land on `about:blank#blocked` (at least in chrome), not on `https://jolicode.com/https://`

cc @vdauchy

## Some context

> On seriously malformed URLs, parse_url() may return false.
(from https://www.php.net/manual/en/function.parse-url.php)

and 
```php
$t = [
    'http://jolicode.com',
    'http://',
    'foobar',
    '/bar',
    '/bar:1',
];

foreach ($t as $uri) {
    $o[$uri] = parse_url($uri, \PHP_URL_SCHEME);
}

dump($o);
```
returns

```console 
$ ./test.php
^ array:5 [
  "http://jolicode.com" => "http"
  "http://" => false
  "foobar" => null
  "/bar" => null
  "/bar:1" => false
]
```

**Comment by lyrixx** [comment]
IMHO, the parsing of `/bar:1` in PHP returning `false` by PHP is a bug, and this bug should be fixed upstream. #52579 must be reverted. 

ATM, we try to perform URL operation on something that PHP was not able to parse. It does not make sens to me.

**Comment by nicolas-grekas** [comment]
> on a webpage, if I put <a href="http://">test</a>, and I click on it, I'll land on about:blank#blocked (at least in chrome),

what about ` /foo:1` ? maybe we could detect a single `/` at the begining?

but I'm fine reverting also!

**Comment by lyrixx** [comment]
If I put `/foo:1` on https://www.example.com/ and I click on the link I land on `https://www.example.com/foo:1`

**Comment by nicolas-grekas** [comment]
Let revert. @vdauchy please open a [bug report on php-src](https://github.com/php/php-src/issues) instead.

**Comment by vdauchy** [comment]
Issue opened here: https://github.com/php/php-src/issues/12703

@nicolas-grekas / @lyrixx Would you allow a more precise PR to support the case specifically on absolute path ?

**Comment by alexisLefebvre** [comment]
Out of curiosity, what is the expected result of `Symfony\Component\DomCrawler\UriResolver::resolve('https://', 'https://jolicode.com/')`? Should it return `https://jolicode.com/` because these 2 values yield no solution? (maybe this is a feature request and should go to another issue)

**Comment by lyrixx** [comment]
@alexislefebvre it should return what is passed: `http://` since it's not an URL. And it's right like this.
