### ISSUE TITLE
[AssetMapper] bootstrap icons works with direct link not with assetmapper require

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#52620]
### Symfony version(s) affected

6.4

### Description

```html
<link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.min.css">
```

works as expected, but 

```bash
bin/console importmap:require bootstrap-icons/font/bootstrap-icons.min.css
```

doesn't.

See https://bootstrap-icons-bug.survos.com/ for a working and non-working version.

### How to reproduce

```bash
symfony new bootstrap-icons-bug --webapp --version=next --php=8.2 && cd bootstrap-icons-bug
composer config minimum-stability beta
composer config extra.symfony.allow-contrib true
composer req symfony/asset-mapper:^6.4 
bin/console importmap:require bootstrap-icons/font/bootstrap-icons.min.css
echo "import 'bootstrap-icons/font/bootstrap-icons.min.css'" >> assets/app.js


bin/console make:controller App -i
sed -i "s|/app|/|" src/Controller/AppController.php 

cat > templates/app.html.twig <<'END'
{% extends 'base.html.twig' %}
{% set useAssetMap = app.request.get('useAssetMap', false) %}
{% block javascripts %}
    {{ useAssetMap ? parent() }}
{% endblock %}

{% block stylesheets %}
    {% if not useAssetMap %} <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.min.css">
    {% endif %}
{% endblock %}

{% block body %}
    {% for useAssetMap in [true, false] %}
    <p>
        <a href="{{ path('app_app', {useAssetMap:useAssetMap}) }}">{{ useAssetMap ? 'with downloaded assetmap file' : 'with link tag to stylesheet on jsdelivr' }} </a>
        </p>
    {% endfor %}
    
    icon: <span class="bi bi-github"></span>
{% endblock %}

END

symfony server:start -d
symfony open:local
```

### Possible Solution

There's something amiss with parsing out the fonts, the javascript console gives some warnings/errors.

**Comment by smnandre** [comment]
This package is not delivered as en ESM bundle, and the package.json does not list the woff / woff2 files so it may be something to digg

As stated in the documentation, when you need to deal with non ESM packages, sometimes it just works... and sometimes you have a bit of [manual work to do](https://symfony.com/doc/6.4/frontend/asset_mapper.html#handling-3rd-party-css) :)

**Comment by tacman** [comment]
@smnandre yes, but @weaverryan has done a lot of work to handle more cases in 6.4.  Given the ubiquity of bootstrap-icons, if it doesn't work out of the box, perhaps he could give guidance to the developer as to what's needed so that it does. There were issues with datatables.net that were resolved when the two of them looked at the problem together.

**Comment by tacman** [comment]
I can confirm that the above script now works with the -dev branch of 6.4.  THANKS!!  I'm guessing we'll see  RC2 very soon.
