### ISSUE TITLE
[ErrorHandler] xdebug_get_function_stack requires enabled xdebug

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#52634]
### Symfony version(s) affected

6.3

### Description

For background see https://github.com/sebastianbergmann/phpunit/issues/5565

Maybe this is just a first-side effect hiding my actual issue, but in Symfony here we produce an error: https://github.com/symfony/symfony/blob/4e944bed01e6627a4d10cf071b118fb7c7cef6de/src/Symfony/Component/ErrorHandler/Error/FatalError.php#L34

```
I have no name!@aa7eeb552c8e:/app$ php -r "var_dump(xdebug_get_function_stack());"
[17-Nov-2023 18:13:30 UTC] PHP Warning:  Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in Command line code on line 1

Warning: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in Command line code on line 1
array(0) {
}
```

But we're not going to enable xdebug as per https://github.com/symfony/flex/issues/936#issuecomment-1802513643

### How to reproduce

`php -r "var_dump(xdebug_get_function_stack());"`

**Comment by stof** [comment]
Well, the fact that the method can trigger a warning when it is not enabled is precisely why we use the silencing operator on that call. When it is disabled, it will always return an empty array and this is handled gracefully (doing nothing, like when the function does not exist at all)

**Comment by ro0NL** [comment]
Yeah, you're right. I tend to believe i landed in between some rabbit hole of error handling in PHP.

I solved the memory issues:
- switched to array cache globally in test env
- disabled profiling_collect_backtrace in test env

this reveals a new error ... :drum:

```
.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  63 / 205 ( 30%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 126 / 205 ( 61%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDbin/test: line 44:    60 Segmentation fault      (core dumped) phpunit
```

**Comment by stof** [comment]
`profiling_collect_backtrace` in DoctrineBundle is known to consume a bunch of memory. That's precisely why it is off by default in the bundle. And in tests, there is no reason to enable it.

**Comment by ro0NL** [comment]
im still trying to figure out what's causing the segault now :+1:

**Comment by ro0NL** [comment]
@stof i think the main issue here is Symfony producing a warning while already in a error handler, which generally seems like a bad idea.

it then triggers phpunit's error handler as an unwanted side-effect:


```
PHP Fatal error:  Uncaught PHPUnit\Event\Code\NoTestCaseObjectOnCallStackException: Cannot find TestCase object on call stack in phar:///usr/local/etc/tools/vendor/bin/phpunit.phar/phpunit/Event/Value/Test/TestMethodBuilder.php:51
  Stack trace:
  #0 phar:///usr/local/etc/tools/vendor/bin/phpunit.phar/phpunit/Runner/ErrorHandler.php(60): PHPUnit\Event\Code\TestMethodBuilder::fromCallStack()
  #1 [internal function]: PHPUnit\Runner\ErrorHandler->__invoke(2, 'Function must b...', '/app/vendor/sym...', 34)
  #2 /app/vendor/symfony/error-handler/Error/FatalError.php(34): xdebug_get_function_stack()
  #3 /app/vendor/symfony/error-handler/ErrorHandler.php(618): Symfony\Component\ErrorHandler\Error\FatalError->__construct('Error: Allowed ...', 0, Array, 2, false, NULL)
  #4 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler::handleFatalError()
  #5 {main}
    thrown in phar:///usr/local/etc/tools/vendor/bin/phpunit.phar/phpunit/Event/Value/Test/TestMethodBuilder.php on line 51
```

**Comment by ro0NL** [comment]
Gave up debugging error handlers :)

will continue with the segfault issue. Im not sure still it's caused by Symfony, PHPUnit, or perhaps our own code :scream:

**Comment by ro0NL** [comment]
ok, we did

```php
use Symfony\Component\Messenger\HandleTrait;

trait QueryBusTrait
{
    use HandleTrait {
        HandleTrait::handle as query;
    }
}
```

for the sake of better naming, but it segfaults ^^

Revised on our side.
