### ISSUE TITLE
[Messenger] Sync retry/delay

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#52647]
### Description

Hi,

The `Delay` stamp works by re-dispatching the message, enabling a so called `available_at` timestamp to be handled at transport level, eg. https://github.com/symfony/symfony/blob/19f52407d9e151e660dc15dc1fb2f2a0ca6af2de/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L122
However it changes the chronological order of things.

In our case we'd prefer a sync retry mechanism by default, using `sleep`.

If the transport doesnt handle `DelayStamp` the whole feature becomes a no-op without any warning, meh but OK.

**Comment by ro0NL** [comment]
Disabled retrying on our side.

**Comment by ghost** [comment]
@ro0NL you don't have to close isssues because you somehow solved a problem on your side. An issue can still be valid anyway.

**Comment by ro0NL** [comment]
understood, but it puts the bookkeeping on my end :)

i create these issues for internal reference mostly

**Comment by ghost** [comment]
> i create these issues for internal reference mostly

You use Symfony issues as your private notebook 😄?

**Comment by ro0NL** [comment]
it's not private :)

i just realized sync retry can be a problem with ack-wait timeouts, causing unexpected re-deliveries

maybe it's not the best solution, or more of a handler concern then
