### ISSUE TITLE
[Filesystem]: Add a Filesystem Interface for better decoupling and easier testing

### ISSUE THREAD

**Issue by tim-lappe** [symfony/symfony#52651]
### Description

Hi,

the Filesystem class in the Filesystem component is very useful, but in some cases I need the possibility to add an alternative implementation (e.g. in integration tests). What about to extend the Filesystem class with an Interface to decouple the classes who needed a filesystem from the direct implementation? https://github.com/symfony/filesystem/blob/6.3/Filesystem.php

### Example

E.g.:

```
/**
 * Provides basic utility to manipulate the file system.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class Filesystem implements FilesystemInterface
```

And in the Interface something like this:

```
interface FilesystemInterface
{
    /**
     * Copies a file.
     *
     * If the target file is older than the origin file, it's always overwritten.
     * If the target file is newer, it is overwritten only when the
     * $overwriteNewerFiles option is set to true.
     *
     * @return void
     *
     * @throws FileNotFoundException When originFile doesn't exist
     * @throws IOException           When copy fails
     */
    public function copy(string $originFile, string $targetFile, bool $overwriteNewerFiles = false)

    .....
}
```

In order to comply with Interface seggregation, there could be multiple Interfaces for that (e.g. for Read and Write operations)

**Comment by stof** [comment]
Given that our Filesystem class is not a full filesystem abstraction (and is not meant to be one), I don't think this is a good idea.
If you need a proper filesystem abstraction, use [Flysystem](https://packagist.org/packages/league/flysystem).
If you use `symfony/filesystem` and the PHP filesystem APIs, any mocking during tests would requiring mocking the filesystem itself (using [vfsstream](https://packagist.org/packages/mikey179/vfsstream)) or just writing your tests to operate on a temporary folder as root.

**Comment by Neirda24** [comment]
What about a MockFileSystem that instead of being abstract auto create the file if does not exists so it complies with what you are doing further down the code ?

**Comment by derrabus** [comment]
I think we can close this ticket. @stof's comment explains very well why the proposed interface is not a good idea.
