### ISSUE TITLE
[AssetMapper] MappedAsset->content on creation is null

### ISSUE THREAD

**Issue by evertharmeling** [symfony/symfony#52652]
### Symfony version(s) affected

6.4, 7.1

## Description

When a `MappedAsset` is created the contents are resolved in the `\Symfony\Component\AssetMapper\Factory\MappedAssetFactory::compileContent` function, this is recently changed with this [commit](https://github.com/symfony/symfony/commit/78ec570236cd0f696dbc6e3932dc937bb4e47493#diff-17d6502defa6119da88c327e198ae8d85473acc41002186bc83f01462e9d8c92R106-R109).

This change introduced a test failure in the `symfonycasts/sass-bundle` ([repo](https://github.com/SymfonyCasts/sass-bundle)) testsuite. Specifically the test `\Symfonycasts\SassBundle\Tests\FunctionalTest::testBuildCssIfUsed` ([code](https://github.com/SymfonyCasts/sass-bundle/blob/main/tests/FunctionalTest.php#L39-L48))

## How to reproduce

- `git clone git@github.com:SymfonyCasts/sass-bundle.git`

**Testsuite A** succeeds (on `PHP:8.1.25`):
- `composer update --prefer-lowest --prefer-stable`
- `vendor/bin/simple-phpunit`

**Testsuite B** fails (on `PHP:8.1.25`):
- `composer update`
- `vendor/bin/simple-phpunit`

**Testsuite C** fails:
- `echo "8.2" > .php-version` (using `symfony-cli` and given `php:8.2` is available)
- `symfony composer update`
- `symfony php vendor/bin/simple-phpunit`

When a `dd($asset)` is added in `\Symfonycasts\SassBundle\Tests\FunctionalTest` on line 48. You'll see that in testsuite A `$asset->content` is equal to the file contents of `/assets/app.css`. And in testsuite B and C `$asset->content` is `null`.

## Additional Context

Should we revise the way we create the `MappedAsset` 2 times in `\Symfony\Component\AssetMapper\Factory\MappedAssetFactory::createMappedAsset` and solve the `Memory bug` differently?

And it looks like currently [line 47](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Factory/MappedAssetFactory.php#L47) could be safely removed as `$this->assetsCache` isn't used until (re)assigned on [line 66](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Factory/MappedAssetFactory.php#L66)

Or should the `symfonycasts/sass-bundle`-testsuite be refactored?

**Comment by smnandre** [comment]
The line you pointed is something worth a look indeed, i'm guessing there is something related to the recursion.

As for the "content", i will stay null for many cases, and that's a good thing, as the previous behaviour had a memory usage impossible to support.

--

✅  Tests fixed in the SassBundle

**Comment by weaverryan** [comment]
> And it looks like currently [line 47](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Factory/MappedAssetFactory.php#L47) could be safely removed as $this->assetsCache isn't used until (re)assigned on [line 66](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Factory/MappedAssetFactory.php#L66)

It's there just in case you have a circular reference (app1.js is being created, but it depeneds on app2.js, so we ask the asset mapper for that `MappedAsset`... but it depends on app1.js). Setting this property early allows us to pass the "incomplete asset" to the `CircularAssetsException` - https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Factory/MappedAssetFactory.php#L40. It is complex, but fortunately, if you remove that line, a test fails :)
