### ISSUE TITLE
[Cache] \Redis::mget() can return bool, Redis6Proxy::mget() doesn't account for that

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#52668]
### Symfony version(s) affected

6.3.5

### Description

`Redis::mget` can return false when no keys are provided. https://github.com/phpredis/phpredis/issues/1810

This is annoying because the signature says `mget(): \Redis|array`, but it's actually `mget(): \Redis|array|false`.

Redis6Proxy::mget has the correct signature, but it doesn't handle the possible false.

### How to reproduce

Set up PHPRedis v6 and do `Redis6Proxy::mget([])`

### Possible Solution

Return [] if false.

### Additional Context

IMO this is a bug in the module, but it's a bug since 2020.

**Comment by alexandre-daubois** [comment]
May be closed by https://github.com/phpredis/phpredis/pull/2422

**Comment by sirian** [comment]
`false` also returned in case of errors like `noAUTH Authentication required`. Tested with phpredis 6.0.2

**Comment by xabbuh** [comment]
we now account for this in the proxy since #54410
