### ISSUE TITLE
[Cache][Messenger] Redis Sentinel configuration names are not streamlined even though they're doing exactly the same thing

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#52671]
### Symfony version(s) affected

6.3.5

### Description

For Messenger, [Redis Transport](https://symfony.com/doc/current/messenger.html#redis-transport) takes `sentinel_master`.

For Cache, [Redis Adapter](https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#configure-the-options) takes `redis_sentinel` for the same use.

This creates friction where developers should reasonably expect the same configuration to have the same names. This is made worse by Cache DSN parser not reporting invalid config, which Messenger does.

### How to reproduce

Check the docs.

### Possible Solution

Streamline the namings.

**Comment by nicolas-grekas** [comment]
Let's support both keys everywhere. Up for a PR?
