### ISSUE TITLE
[Runtime] Enable `date_default_timezone_set`

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#52692]
### Description

Would be nice if we can specify `time[_]zone = string|DateTimeZone` as option for `GenericRuntime`, and leverage `date_default_timezone_set`.

WDYT?

**Comment by nicolas-grekas** [comment]
This looks like a good idea actually, but I'd broaden it to all ini setting.
Together with #45535 why not.
/cc @alexandre-daubois

**Comment by alexandre-daubois** [comment]
@ro0NL do you want to submit a PR? I'd be happy to have a look at it if you don't/can't. Keep me updated 🙂

**Comment by nicolas-grekas** [comment]
Note that before adding more code, it might be nice to have a clear understanding of how PHP SAPIs load php.ini files

e.g. these page list many options, not all available depending on the SAPI:
https://www.php.net/manual/en/configuration.file.php
https://www.php.net/manual/en/configuration.file.per-user.php

Also https://symfony.com/doc/current/setup/symfony_server.html#overriding-php-config-options-per-project

Maybe it's only a matter of doc?

**Comment by ro0NL** [comment]
@alexandre-daubois sry, no real time :)

im also starting to consider php.ini per project now, even though that requires more code on our side :upside_down_face:

im not sure what's best, an application solution that works for all, or an infrastructural solution that dont control but does relate to projects.
