### ISSUE TITLE
Bug: Unable to send array on setParameter method

### ISSUE THREAD

**Issue by paoloLigsay** [symfony/symfony#52696]
### Symfony version(s) affected

6.3.*

### Description
When attempting to pass an array of objects an error is thrown that it should contain a string and not an array. Using json_encode() to encapsulate the array resolves the problem. However, Brevo expects the value to be an array, not a string.

### How to reproduce

1. Create a new email, set the sender and send email.

```php
$message = (new Email())
   ->From(...)
   // ...more code here
  
   ->getHeaders()
      ->addTextHeader('templateId', $template)
      ->addParameterizedHeader('params', 'params', $params);

$this->mailer->send($message);
```

2. Passing an array instead of string or null value.
```
$param_one = [];

$params = [
            ...more params here,
            'param_one' => $param_one,
        ];
``` 

### Expected Behavior
Allow an array to be passed in the parameter other than string and null value.

### Actual Behavior
Error is thrown when we passed an array on the parameter instead of string and null value.

### Possible Solution
Removing the type declaration for the $value to avoid the error being thrown. 
Reference solution: https://github.com/symfony/symfony/pull/52695

**Comment by xabbuh** [comment]
> However, Brevo expects the value to be an array, not a string.

Can you please clarify what that means?

**Comment by botjaeger** [comment]
> > However, Brevo expects the value to be an array, not a string.
> 
> Can you please clarify what that means?

We need to send an array as a parameter, but symfony/mime only expects nullable strings

**Comment by xabbuh** [comment]
Where do you need to send this? A header in a "real" e-mail always is a string. So we need to find out where exactly inside the code the header value is expected to be an array and how to deal with that.

**Comment by botjaeger** [comment]
> Where do you need to send this? A header in a "real" e-mail always is a string. So we need to find out where exactly inside the code the header value is expected to be an array and how to deal with that.

we're using this package https://github.com/symfony/brevo-mailer

and this is how we set the parameters

```
$email = new Email();
$email
    ->getHeaders()
    ->add(new MetadataHeader('custom', $json))
    ->add(new TagHeader('TagInHeaders1'))
    ->add(new TagHeader('TagInHeaders2'))
    ->addTextHeader('sender.ip', '1.2.3.4')
    ->addTextHeader('templateId', 1)
    ->addParameterizedHeader('params', 'params', $params)
    ->addTextHeader('foo', 'bar')
```

**Comment by xabbuh** [comment]
This does not explain yet where the value is expected to be an array. Can you please elaborate a bit more?

**Comment by nicolas-grekas** [comment]
As posted on #52695, this doesn't make sense to me. An array cannot be sent as is on the network. At some point, something needs to serialize it. The mime component doesn't know how to serialize this array. If you need to send many values for some header, you need to generate the serialized string on your side before passing it to setParameter.
IIUC.

**Comment by xabbuh** [comment]
closing as explained
