### ISSUE TITLE
[AssetMapper] Dotfiles exposed due to cache prefix

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#52697]
### Symfony version(s) affected

6.4,7.0,7.1

### Description

Any hidden / dotfile in the assets directory is deployed and publically accessible.

Assets files are versionned via a prefix inserted before the file extension.

The servers standard protection against dotfile access cannot work, as the mapped files are not "dotfiles"  anymore.

```
your-project/
├─ assets/
│  ├─ .DS_Store 
│  ├─ .cert
│  └─ ... 
```

```
your-project/
├─ public/
│  ├─ assets/
│  │   ├─ -XXXXX.DS_Store
│  │  └─ -YYYYY.cert
```

### How to reproduce

```
symfony new asset-mapper-dot-files --webapp --version="next" \
	&& cd asset-mapper-dot-files \
	&& composer req symfony/asset-mapper \
	&& touch assets/.FOO \
	&& APP_ENV=prod php bin/console asset-map:compile 
	
ls -la public/assets	
```

#### Exclude patterns

This behaviour can be prevented with a specific config directive 

```conf
# config/asset_mapper.yaml
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/

        excluded_patterns:
            - '*/.*'
```            

As of today this is neither documented or "default behaviour".

That could be a first move, but this is something risky, as the pattern is not self-explanatory 

### Fix asset collection

Another way would be to modify the assets collection (in the Repository) to ignore dotfiles

..

What do you think ?

**Comment by 94noni** [comment]
Or perhaps go with a list of default file extension (.js/.css/.png etc) allowed, this being possible to override ?

but indeed having all compiles to public may be risky in case of wrong/accidental commit on assets folders

**Comment by maelanleborgne** [comment]
It feels like a list of allowed files would be really long and hard to maintain, and it may be confusing for developers to see some files missing when compiling assets after an upgrade.
Maybe the easier path would be changing the default configuration of the asset mapper to use the `excluded_pattern: '*/.*'`, as well as adding it to the config file delivered by the recipe along with a comment on what this directive does and adding this to the docs ?
It could also be worth displaying a warning while compiling assets to suggest the user to check the content of the `public/assets` dir for any unwanted files and create exclusion rules accordingly.

wdyt ?

**Comment by smnandre** [comment]
What about an option "exclude_dotfiles" (default true) ?

**Comment by weaverryan** [comment]
> What about an option "exclude_dotfiles" (default true) ?

Yes, I like this option. I'd rather not bother at all - and make it clear that ALL files in your mapped assets/ directory are made publicly accessible (that's actually the whole point of AssetMapper), but it might be better to be on the safe side. But hiding dot files by default (but allowing it to be turned of) seems reasonable to me, and safe by default. Dot files, I think, are a special case.

Btw, for comparison, Propshaft from Ruby has the same behavior as AssetMapper and, as far as I know, doesn't exclude anything by default: https://github.com/rails/propshaft#usage

So, if we *are* going to do this, it's at #52712
