### ISSUE TITLE
Route attribute on a controller method is inherited, so the last alphabetically-order extending controller wins

### ISSUE THREAD

**Issue by ZaneCEO** [symfony/symfony#52708]
### Symfony version(s) affected

6.3

### Description

I understand from multiple sources ([for example](https://blog.shalvah.me/posts/php-8-attribute-quirks)) that PHP attributes are not inherited.

Yet, a controller extending another inherits its  `#[Route]` attribute. So we have multiple method binding on the same path, and the last one takes precedente.

### How to reproduce

````php
## src/Controller/MainController.php

<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;


class MainController extends AbstractController
{
    const MESSAGE = 'main';

    #[Route('/main', name: 'app_main')]
    public function index(): JsonResponse
    {
        return $this->json([
            'message' => static::MESSAGE,
        ]);
    }
}
````

````php
## src/Controller/ZextensionController.php

<?php
namespace App\Controller;

class ZextensionController extends MainController
{
    const MESSAGE = 'extension';
}
````

If we now open `/main`, we get `{"message":"extension"}`, because the extending controllers is the last one alphabetically.

**Comment by stof** [comment]
As you don't override the method, you inherit the whole method (and so its attributes).

In your case, the `Route` attribute is not applied on the class but on the method. And reading attributes on `ZextensionController::index` will see the attribute. That's just how PHP works.

**Comment by ZaneCEO** [comment]
Thanks for your reply. If this is the expected behavior and nobody chimes in, I'm gonna close the issue soon.

**Comment by stof** [comment]
There is simply nothing we can change about that: this is the way PHP itself works.

**Comment by ZaneCEO** [comment]
Got it, thanks
