### ISSUE TITLE
[Mailer] Add support for Azure Communication Services Email

### ISSUE THREAD

**Issue by davidbarratt** [symfony/symfony#52751]
### Description

You can send emails with Azure Communication Services now
https://learn.microsoft.com/en-us/azure/communication-services/concepts/email/email-overview

It could be helpful to merge in the MIT licensed https://github.com/hafael/azure-mailer-driver to make it easier to use this service.

**Comment by derrabus** [comment]
LGTM, if the author wants to contribute it.

**Comment by hafael** [comment]
This package was developed with this objective. I would love to see this merge happen! :)

**Comment by stof** [comment]
Well, feel free to open a PR submitting a new bridge (note that the part about the Laravel service provider should of course not be contributed here but either kept in your package or be submitted to Laravel).

**Comment by hafael** [comment]
OK! I will double-check the guidelines and submit the pull request as soon as possible.
