### ISSUE TITLE
[WebProfiler] Poorly formatted deprecation in toolbar

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#52757]
### Symfony version(s) affected

6.4-RC2

### Description

I'm seeing a deprecation error in the toolbar that is poorly formatted

![image](https://github.com/symfony/symfony/assets/619585/02598b05-44b2-4144-af8d-7f4f29c1ac2a)

Even in the profiler page, it looks wrong:

![image](https://github.com/symfony/symfony/assets/619585/02ef84c0-3fce-4502-82a9-0c4c8dd29bee)

The actual error is in vendor/symfony/ux-twig-component/src/DataCollector/TwigComponentDataCollector.php
on line 93, which I imagine will get fixed soon, but a related question is why this deprecation is showing up as it is.

### How to reproduce

I can provide a repo if that helps, but at the moment I haven't been able to reproduce it with a simple repo.

**Comment by smnandre** [comment]
It's a symfony UX issue, you may want to move your issue there.

I'll check / fix tonight.
