### ISSUE TITLE
Allow disabling exception rendering

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#52777]
### Description

When using Datadog and Docker, it is recommended to only ever print JSON (for Datadog) to the output (because the output of the main process is the output of the whole container). Datadog documents how to properly configure a Symfony application to fulfill that requirement: https://docs.datadoghq.com/logs/log_collection/php/?tab=phpmonolog

They don't mention it, but you should probably also use `--quiet` when running a command in production, so that only the json logs show up in the output.

There's one thing that you can't however prevent, and that is the exception rendering done by https://github.com/symfony/symfony/blob/c8b962a0bf4ec24ef405222d66f3ae8e9eea94f6/src/Symfony/Component/Console/Application.php#L820-L830

Because of it, what you will see on Datadog is:
- a properly formatted, CRITICAL datadog line thanks to the monolog configuration
- one INFO line for each line in the unformatted output. 

### Example

It might be nice to have something like 
```yaml
framework:
    render_errors: '%kernel.debug%'
```
to configure this.

**Comment by wouterj** [comment]
I'm facing this as well.

I've proposed a PR to use an env var to disable the output #53126 I think an env var is better for this as it's environment specific (e.g. I still want to see output when running a command locally or in CI)

**Comment by petrzivny** [comment]
I would be nice to have this functionality. I haven´t figured a way how to do it and not spoil the logs. It is not only connected to Datadog, but basically any native cloud provider too.

**Comment by greg0ire** [comment]
@wouterj thanks for working on this :pray:
