### ISSUE TITLE
Symfony\Bundle\MakerBundle\Util\MakerFileLinkFormatter::__construct(): Argument #1 ($fileLinkFormatter) must be of type ?Symfony\Component\HttpKernel\Debug\FileLinkFormatter, Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter given, called in E:\Ope nServer2\domains\shop\var\cache\dev\Container8hDhWSx\getMaker_FileLinkFormatterService.php on line 23

### ISSUE THREAD

**Issue by stayeronglass** [symfony/symfony#52799]
### Symfony version(s) affected

7.0.0

### Description

php bin/console make:entity pritn an error

PS E:\OpenServer2\domains\shop> php bin/console make:entity Product 
TypeError {#1749
  #message: "Symfony\Bundle\MakerBundle\Util\MakerFileLinkFormatter::__construct(): Argument #1 ($fileLinkFormatter) must be of type ?Symfony\Component\HttpKernel\Debug\FileLinkFormatter, Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter given, called in E:\Ope
nServer2\domains\shop\var\cache\dev\Container8hDhWSx\getMaker_FileLinkFormatterService.php on line 23"
  #code: 0
  #file: "E:\OpenServer2\domains\shop\vendor\symfony\maker-bundle\src\Util\MakerFileLinkFormatter.php"
  #line: 22
  trace: {
    E:\OpenServer2\domains\shop\vendor\symfony\maker-bundle\src\Util\MakerFileLinkFormatter.php:22 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\getMaker_FileLinkFormatterService.php:23 {
      Container8hDhWSx\getMaker_FileLinkFormatterService::do($container, $lazyLoad = true)
      › 
      ›     return $container->privates['maker.file_link_formatter'] = new \Symfony\Bundle\MakerBundle\Util\MakerFileLinkFormatter(($container->privates['debug.file_link_formatter'] ?? self::getDebug_FileLinkFormatterService($container)));
      › }
      arguments: {
        $fileLinkFormatter: Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter {#4127 …}
    }
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\App_KernelDevDebugContainer.php:478 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\getMaker_FileManagerService.php:26 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\App_KernelDevDebugContainer.php:478 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\getMaker_AutoCommand_MakeEntityService.php:29 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\App_KernelDevDebugContainer.php:478 { …}
    E:\OpenServer2\domains\shop\var\cache\dev\Container8hDhWSx\get_Maker_AutoCommand_MakeEntity_LazyService.php:24 { …}
    E:\OpenServer2\domains\shop\vendor\symfony\console\Command\LazyCommand.php:185 { …}
    E:\OpenServer2\domains\shop\vendor\symfony\console\Application.php:314 { …}
    E:\OpenServer2\domains\shop\vendor\symfony\framework-bundle\Console\Application.php:79 { …}
    E:\OpenServer2\domains\shop\vendor\symfony\console\Application.php:169 { …}
    E:\OpenServer2\domains\shop\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49 { …}
    E:\OpenServer2\domains\shop\vendor\autoload_runtime.php:29 { …}
    E:\OpenServer2\domains\shop\bin\console:11 { …}
  }
}

### How to reproduce

composer.phar create-project symfony-skeleton 
composer.phar req webapp
php bin/console make:entity (or make:controller)

### Additional Context

 -------------------- ------------------------------------------- 
  Symfony                                                         
 -------------------- -------------------------------------------
  Version              7.0.0
  Long-Term Support    No
  End of maintenance   07/2024 (in +245 days)
  End of life          07/2024 (in +245 days)
 -------------------- -------------------------------------------
  Kernel
 -------------------- -------------------------------------------
  Type                 App\Kernel
  Environment          dev
  Debug                true
  Charset              UTF-8
  Cache directory      ./var/cache/dev (9.1 MiB)
  Build directory      ./var/cache/dev (9.1 MiB)
  Log directory        ./var/log (12 KiB)
 -------------------- -------------------------------------------
  PHP
 -------------------- -------------------------------------------
  Version              8.2.7
  Architecture         64 bits
  Intl locale          n/a
  Timezone             Europe/Moscow (2023-11-29T17:01:16+03:00)
  OPcache              false
  APCu                 false
  Xdebug               false
 -------------------- -------------------------------------------

**Comment by GromNaN** [comment]
Thanks for the report. Compatibility with Symfony 7 was fixed by https://github.com/symfony/maker-bundle/pull/1383

This needs to be released.
