### ISSUE TITLE
[Routing] Prefix feature for i18n routes is broken

### ISSUE THREAD

**Issue by plandolt** [symfony/symfony#52802]
### Symfony version(s) affected

6.4.0

### Description

When trying to translate the url using the [router prefix feature](https://symfony.com/doc/current/routing.html#localized-routes-i18n) the following error occurs:
`Target route "app_your_route_name" for alias "App\Controller\YourController::index" does not exist.`

### How to reproduce

- Create a fresh installation of 6.4.0 (or upgrade a fresh installation from 6.3 to 6.4). 
- Create a dummy controller (e.g. with the maker bundle)
- Change `routes.yaml` (https://symfony.com/doc/current/routing.html#localized-routes-i18n):

```diff
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
+   prefix:
+       de: '/de'
+       fr: '/fr'
+       it: '/it'
```

- run `bin/console cache:clear`

**Comment by HypeMC** [comment]
The issue was introduced in https://github.com/symfony/symfony/pull/50084.

**Comment by HypeMC** [comment]
I think the problem is this line: https://github.com/symfony/symfony/blob/914496290fc8777edbb8e58db772b106c2d99c87/src/Symfony/Component/Routing/Loader/AttributeClassLoader.php#L145-L147

It seems to be missing the `$fqcnAlias && ` condition.

**Comment by plandolt** [comment]
> I think the problem is this line:
> 
> https://github.com/symfony/symfony/blob/914496290fc8777edbb8e58db772b106c2d99c87/src/Symfony/Component/Routing/Loader/AttributeClassLoader.php#L145-L147
> 
> It seems to be missing the `$fqcnAlias && ` condition.

This seems to solve the problem for Controller Actions that do not use `__invoke` as its method name. With __invoke the same error still occurs:
`Target route "app_dummy" for alias "App\Controller\DummyController::__invoke" does not exist.`

**Comment by HypeMC** [comment]
Yeah, it looks like the original [PR for aliases](https://github.com/symfony/symfony/pull/38464) never covered aliasing routes with prefixes.

**Comment by fancyweb** [comment]
Thank you for your report, I'll have a look.

**Comment by fancyweb** [comment]
I think it comes from an already existing bug on 5.4 :sweat_smile: Removing a route doesn't remove aliases pointing to it as expected.
