### ISSUE TITLE
EnglishInflector incorrectly singularizes "service" to "servouse"

### ISSUE THREAD

**Issue by kfrymire** [symfony/symfony#52807]
### Symfony version(s) affected

6.4.0

### Description

The EnglishInflector class incorrectly singularizes the word "service" (singular) to "servouse".  The singularize() method should instead return "services".

### How to reproduce

```php
require_once 'vendor/autoload.php';
use Symfony\Component\String\Inflector\EnglishInflector;

$inflector = new EnglishInflector();
print_r($inflector->singularize('service'));

```

### Possible Solution

Maybe remove "['secivres', 8, true, true, 'service']" from EnglishInflector::PLURAL_MAP, or add one for "services"?

 The simple presence or absence of the letter "s" at the end of "service" determines if it's plural or singular, respectively.

**Comment by stof** [comment]
`singularize` is meant to take a plural word and to return it in singular form. Passing a singular word to this function is not meant at all to return its plural.

**Comment by kfrymire** [comment]
The use case for this is if you pass a string that you don't know if it's already plural or singular.
For what it's worth this appears to apply to any string that ends with "vice"

**Comment by stof** [comment]
@kfrymire If you don't know what you have as input, you cannot know what you will get as output.

Symfony cannot know whether the word you pass as input is a valid plural or a valid singular, because it does not have a list of valid English words.
