### ISSUE TITLE
Upgrade asset mapper to 6.4 fails due to invalid entry "downloaded_to"

### ISSUE THREAD

**Issue by redflo** [symfony/symfony#52810]
### Symfony version(s) affected

6.4.0

### Description

My project uses the asset mapper and as here described:
https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages
i downloaded bootstrap with the --download option (which is not working either in 6.4. - documentation issue too).
This generates 
`'downloaded_to' => 'vendor/....'`
Entries in importmap.php which then cause a exception when calling `{{ importmap() }}` in twig or when trying to update importmaps.
Deleting these downloaded_to fixes the problem after running
`bin/console importmap:update`

### How to reproduce

Install symfony 6.3, add assetmapper, run
`php bin/console importmap:require bootstrap --download`
Upgrade to symfony 6.4 (including recipes updates)
run `bin/console importmap:update`
It gives a error:
`In ImportMapConfigReader.php line 46:
                                                                                                                                                                               
  The following keys are not valid for the importmap entry "bootstrap": "downloaded_to". Valid keys are: "path", "version", "type", "entrypoint", "url", "package_specifier".  
`

### Possible Solution

flex recipes should sanatize importmap.php or the importmap:update should handle the upgrade situation

**Comment by smnandre** [comment]
The upgrade path is not at smooth as it could have been .. but as every situation is different i'm not sure any command could really do the job. 

But if you have some ideas to implement it, please open a PR, it could help others !

> (which is not working either in 6.4. - documentation issue too)

The documentation has been updated very recently, it does not mention the download option anymore, as this is now the standard behaviour for every packages / assets : https://symfony.com/doc/6.4/frontend/asset_mapper.html#importing-3rd-party-javascript-packages

**Comment by stof** [comment]
@weaverryan is there a way to make the 6.4 version of the component accept a file generated with 6.3 by automatically removing the old `downloaded_to` key ?

**Comment by weaverryan** [comment]
I did try (without mucking up the code too much) to smooth the upgrade path - https://github.com/symfony/symfony/blob/d820d504ffc7c305241abe5e367d83c1da57ff0f/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L50-L52

But, I overlooked `downloaded_to`. So, if we want to smooth the path, I think we could:

1) Add `download_to` to this list - https://github.com/symfony/symfony/blob/d820d504ffc7c305241abe5e367d83c1da57ff0f/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L44

2) Add another `if` statement like this, but for `dowload_to` - https://github.com/symfony/symfony/blob/d820d504ffc7c305241abe5e367d83c1da57ff0f/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L49-L52

PR welcome :)
