### ISSUE TITLE
[Validator] Unable to solve "uses Doctrine Annotations to configure validation constraints, which is deprecated. Use PHP attributes instead." deprecation

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#52828]
### Symfony version(s) affected

6.4.0

### Description

We have entities where all the validation constraints have been converted to attributes, however symfony validator still complains about using validation constraints through annotations. This is because logic for detecting these is oversimplified and it throws deprecation whenever it detects _any_ attributes

https://github.com/symfony/symfony/blob/e3e3d5fb4ddcad3887a0d01c878ab9ff88cd06ff/src/Symfony/Component/Validator/Mapping/Loader/AnnotationLoader.php#L120-L122

Situation is made worse by being unable to disable annotations while having attributes on. Following config
```yml
framework:
    validation:
        enable_annotations: false
        enable_attributes: true
```

produces compilation error `The "enable_annotations" and "enable_attributes" options at path "framework.validation" must not be both set. Only the "enable_attributes" option must be used.`

### How to reproduce

Run validation in SF fullstack on following object
```php
/** @\ApiPlatform\Core\Annotation\ApiResource()) */
#[\Doctrine\ORM\MappingORM\Entity]
class ThirdParty {}
```

### Possible Solution

Allow turning off `enable_annotations` while having `enable_attributes` on, or improve deprecation detection so it complains only if it finds annotation _Constraint_

**Comment by ghost** [comment]
`framework.validation.enable_annotations`  is deprecated at removed in 7.0 

Yeah. It looks like the if `symfony/src/Symfony/Component/Validator/Mapping/Loader/AnnotationLoader.php:120 ` will be fulfilled when both attribute and annotation are on a property.

**Comment by stof** [comment]
It looks like the deprecation warning complains as soon as any annotation is found. It should filter them to care only about annotations being constraints.
