### ISSUE TITLE
[Form] `ChoiceType` is still calling the removed `PostSubmitEvent::setData()`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#52829]
### Symfony version(s) affected

7.0.0

### Description

@HeahDude in https://github.com/symfony/symfony/pull/51043 you removed `FormEvent::setData()`.

But `ChoiceType::buildForm()` still contains this line at https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L162
```php
$event->setData($knownValues);
```

But this will now lead to a `BadMethodCallException` in [`PostSetDataEvent`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Event/PostSetDataEvent.php#L25) and [`PostSubmitEvent`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Event/PostSubmitEvent.php#L25).

Did you overlook this? Or is this line never executed in fact (and thus could be deleted)?

### How to reproduce

See above.

**Comment by HypeMC** [comment]
The `setData()` method is called in a [pre-submit listener](https://github.com/symfony/symfony/blob/3330e550e08c45fbaeaae7808b36494317dbcc76/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L100C40-L100C62), how did you get a `PostSetDataEvent` or `PostSubmitEvent`?

**Comment by HeahDude** [comment]
Hello @ThomasLandauer, I don't understand, as said @HypeMC the line you link is handling a `PreSubmitEvent`, so it is not concerned by a bad method call.

Did you actually encounter the error or is it a theoretical question?

**Comment by ThomasLandauer** [comment]
I have a custom type which is pretty much the same as `ChoiceType`. And there psalm is reporting:

> ERROR: DeprecatedMethod - src/Form/Type/MyType.php:165:21 - The method Symfony\Component\Form\Event\PostSetDataEvent::setData has been marked as deprecated (see https://psalm.dev/001)
            $event->setData($knownValues);

> ERROR: DeprecatedMethod - src/Form/Type/MyType.php:165:21 - The method Symfony\Component\Form\Event\PostSubmitEvent::setData has been marked as deprecated (see https://psalm.dev/001)
            $event->setData($knownValues);

Thanks to your answers I now changed the type-hint of `$event` (in the callback function) from `FormEvent` to `PreSubmitEvent`.
So now I'm wondering if this should be changed in [`ChoiceType`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L100) too?

**Comment by HeahDude** [comment]
Changing the type hint of that callback listener in core would be a BC break even if it would be very unlikely to happen in real life.

Actually, `FormEvent::setData()` has not been deprecated in 6.4, only two of the subtypes have.
Although, from a static analyser perspective the current type hint is not a guarantee that we cannot pass another subtype, and such warning is legit. However, in practice, that *should* never happen here, so we could just ignore it.

IMHO it is not worth the trouble and would have to wait for 7.1 anyway.
@xabbuh @yceruto any thoughts?

**Comment by yceruto** [comment]
Having the typehint in core for the corresponding event class in the listener would make sense to me; it's more appropriate now that there are subtypes where calling `setData` is not allowed. But as you said, it's a breaking change to do that directly. Even if it would be a very weird use case, technically it's possible to dispatch a custom subtype using `$form->getConfig()->getEventDispatcher()` instance.

In my opinion, it isn't worth deprecating and changing the typehint in core. However, I think we should improve the documentation to typehint the correct form event in all examples, thus reducing this kind of static analyzer reporting in userland.

**Comment by ThomasLandauer** [comment]
1. See https://github.com/symfony/symfony-docs/pull/19206 for updating the docs - is this what you had in mind?
1. What about adding a phpdoc like `/** @var PreSubmitEvent $event */` (or whatever the syntax is) to [`ChoiceType`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L100) and [`TimeType`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php#L61) and [`FileType`](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L47) ?

**Comment by yceruto** [comment]
> What about adding a phpdoc like /** @var PreSubmitEvent $event */ (or whatever the syntax is) to [ChoiceType](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L100) and [TimeType](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php#L61) and [FileType](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L47) ?

It doesn't hurt anyone, so it's actually a good idea 👍

**Comment by ThomasLandauer** [comment]
See https://github.com/symfony/symfony/pull/52861 for adding the PHPDoc.
