### ISSUE TITLE
[DoctrineBridge] v6.4 only allows doctrine/persistence v3, while v6.3.8 also allows doctrine/persistence v2

### ISSUE THREAD

**Issue by 7ochem** [symfony/symfony#52834]
### Symfony version(s) affected

6.4.0

### Description

I had Symfony 6.3 running in one of my projects, with symfony/doctrine-bridge v6.3.8. Now with Symfony 6.4 I get a Composer conflict, forced by Symfony Flex which wants all packages listed in symfony/symfony on v6.4.*, but Composer cannot install symfony/doctrine-bridge v6.4. This is because I have various dependencies that require doctrine/persistence v2. And since symfony/doctrine-bridge v6.4 Doctrine Bridge requires doctrine/persistence v3.1. While symfony/doctrine-bridge v6.3.8 requires doctrine/persistence ^2|^3.

### How to reproduce

- Setup a Symfony project with Symfony v6.3, including Symfony Flex and Symfony Doctrine Bridge (and `extra.symfony.require` on `6.3.*` in composer.json).
- Add a hard requirement for doctrine/persistence `^2`
- Change `extra.symfony.require` in composer.json to `6.4.*`
- Try `composer update`

### Possible Solution

Keep allowing doctrine/persistence `^2` in symfony/doctrine-bridge v6.4 (and change it to `^3.1` only in Symfony v7)

### Additional Context

This commit introduced this break: https://github.com/symfony/symfony/commit/0d4e2b8dad6b526ed91fa17f9932f3c0642603b8

It's just a "bump". I don't see any additional code changes, so no specific behaviour was added/changed which would work on doctrine/persistence v3.1 only? So why force this change?

**Comment by derrabus** [comment]
> I have various dependencies that require doctrine/persistence v2.

Can you elaborate further? Persistence 2 should really be dead by now, so I'd prefer to fix those dependencies instead.

**Comment by 7ochem** [comment]
> Can you elaborate further? Persistence 2 should really be dead by now, so I'd prefer to fix those dependencies instead.

The answer seems to be indeed: doctrine/persistence v2 is EOL. But... My assumption would be that I could switch from 6.3 to 6.4 without any issues and as this is 1 minor version up, I wouldn't expect any changes that would require me to update my code.

Well, for now the work I've got to put into this is very minimal, luckily, so I'll just put in that work and close this issue 😄

**Comment by middlebrain** [comment]
The problem is that doctrine/persistence v3 has removed the annotation driver.

However, there are packages which do not yet have an attribute driver or which temporarily support attributes AND annotations and therefore still rely on doctrine/persistence v2. Such packages, e.g. the latest stable version of doctrine/phpcr-odm, can currently not be installed together with symfony/doctrine-bridge 6.4.

**Comment by derrabus** [comment]
Please report this to the PHPCR-ODM project instead.
