### ISSUE TITLE
Static analysis error in CollectionType.php - prototype is an object

### ISSUE THREAD

**Issue by mustanggb** [symfony/symfony#52841]
### Symfony version(s) affected

6.3.8

### Description

This is just my understanding so it may well be incorrect.

Slightly similar to #32205, but I believe the issue is that `FormView::$vars` is defined as:
```
    /**
     * The variables assigned to this view.
     */
    public $vars = [
        'value' => null,
        'attr' => [],
    ];
```

Therefore it is interpreted as `array<null|array>` due picking up the default values of `value` being `null` and `attr` being `array`.

However this is not complete, as `$vars['prototype']` is an `object`, and there is no default `object` declared so it's considered invalid.

I ran this with two different extensions, [PHP Intelephense](https://github.com/bmewburn/vscode-intelephense) and [PHP IntelliSense](https://github.com/zobo/vscode-php-intellisense), both said the same thing.

### How to reproduce

- Run static analysis
- See error shown in screenshot

### Possible Solution

Although a slightly different issue to #32205, I believe the solution is still the same.
```
      /**
       * The variables assigned to this view.
+      *
+      * @var array
       */
      public $vars = [
          'value' => null,
          'attr' => [],
      ];
```

### Additional Context

![image](https://github.com/symfony/symfony/assets/1636013/c9b0917e-2c0b-43c6-bf8f-834bcd6c2fc9)

**Comment by xabbuh** [comment]
We do add new docblocks to add information for static analysis tools only in new minor versions. Since in 7.1 the property already has a native `array` type-hint such a docblock wouldn't add any additional useful information. Thus I close here. Thank you for understanding.
