### ISSUE TITLE
[ProxyManager Bridge] Missing Symfony 7 tag

### ISSUE THREAD

**Issue by AmProsius** [symfony/symfony#52873]
### Symfony version(s) affected

7.0.*

### Description

Following the docs to [update Symfony](https://symfony.com/doc/current/setup/upgrade_major.html#2-update-to-the-new-major-version-via-composer) from 6.4.* to 7.0.*, I got this error message:
```
Root composer.json requires symfony/proxy-manager-bridge 7.0.*, found symfony/proxy-manager-bridge[v2.3.0, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev] but it does not match the constraint.
```

The `symfony/proxy-manager-bridge` project doesn't have a `7.0.0` tag yet.

### How to reproduce

Open a Symfony 6.4 application with the `symfony/proxy-manager-bridge` package in it and try to update all packages by increasing their version number to `7.0.*`.

### Possible Solution

Add a `7.0.0` tag to `symfony/proxy-manager-bridge`.

**Comment by wouterj** [comment]
See https://github.com/symfony/symfony/blob/7.1/UPGRADE-7.0.md#ProxyManagerBridge , the bridge is removed in 7.0
