### ISSUE TITLE
#[MapEntity] and render controller from twig

### ISSUE THREAD

**Issue by onEXHovia** [symfony/symfony#52875]
### Symfony version(s) affected

6.4

### Description

When updating project and replacing `ParamConverter` to `MapEntity`, when render controller from a template, it fails.
Exception example:

An exception has been thrown during the rendering of a template ("Controller "App\Controller\ListController" requires that you provide a value for the "$tag" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.").

When used `ParamConverter` two options worked: calling via http and via render(controller()), now only http.

### How to reproduce

Below there will be a simplified example, the controller is available by route and we want to call it in the template with a pre-selected entity.

Controller:
```php
<?php

namespace App\Controller;

use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class ListController
{
    #[Route('/list/{slug}', name: 'app_list', methods: ['GET'])]
    public function __invoke(Request $request, #[MapEntity] Tag $tag): Response
    {
        return new Response($tag->getId());
    }
}
```

Template:
```twig
{{ render(controller('App\\Controller\\ListController', {
    'tag': tag,
})) }}
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by onEXHovia** [comment]
> Can you create a small example application that allows to reproduce your issue?

Sure https://github.com/onEXHovia/mapentity-bug

After setup in homepage will current exception, but by route `/tag/1` its work.

**Comment by smnandre** [comment]
> An exception has been thrown during the rendering of a template ("Controller "App\Controller\ListController" requires that you provide a value for the "$tag" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.").

It seems to me this is not related to the Mapped / Param, but to your TagController route.

In the route, there is a {id} parameter, but you give a "tag" parameter... so it cannot generate the URL

**Comment by onEXHovia** [comment]
@xabbuh to be completely clear, the behavior before and after

`ParamConverter` (works)
```php
<?php

namespace App\Controller;

use App\Entity\Tag;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class TagController
{
    #[Route('/tag/{tagId}', name: 'tag', methods: ['GET'])]
    #[ParamConverter('tag', options: ['mapping' => ['tagId' => 'id']])]
    public function __invoke(Request $request, Tag $tag): Response
    {
        return new Response($tag->getId());
    }
}
```
```twig
{{ render(controller('App\\Controller\\TagController', {
    'tag': tag,
})) }}
```

`MapEntity` (not works)
```php
<?php

namespace App\Controller;

use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class TagController
{
    #[Route('/tag/{tagId}', name: 'tag', methods: ['GET'])]
    public function __invoke(Request $request, #[MapEntity(mapping: ['tagId' => 'id'])] Tag $tag): Response
    {
        return new Response($tag->getId());
    }
}
```
```twig
{{ render(controller('App\\Controller\\TagController', {
    'tag': tag,
})) }}
```

We use many similar techniques to display some forms. Maybe when create sub-request passed arguments  were replaced `EntityValueResolver` resolver

**Comment by xabbuh** [comment]
@onEXHovia Can you please check if adjusting your code as described in https://github.com/symfony/symfony/issues/52875#issuecomment-1837560467 helps?

**Comment by onEXHovia** [comment]
> @onEXHovia Can you please check if adjusting your code as described in [#52875 (comment)](https://github.com/symfony/symfony/issues/52875#issuecomment-1837560467) helps?

Yes, if used construction
```twig
{{ render(controller('App\\Controller\\TagController', {
    'tagId': tag.id,
})) }}
```

But this behavior that I described above works with the symfony version 3+ for sure.  We can pass the request to a sub request using the same logic

```twig
{{ render(controller('App\\Controller\\TagController', {
    'request': app.request,
    'tag': tag,
})) }}
```

And as an example, let's remove MapEntity from the controller, and will work as before without specifying routing parameters

```php
<?php

namespace App\Controller;

use App\Entity\Tag;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class TagController
{
    #[Route('/tag/{tagId}', name: 'tag', methods: ['GET'])]
    public function __invoke(Request $request, Tag $tag): Response
    {
        return new Response($tag->getId());
    }
}
```
```twig
{{ render(controller('App\\Controller\\TagController', {
    'tag': tag, {# wiil work without tagId parameter #}
})) }}
````

**Comment by onEXHovia** [comment]
Having looked at the differences between `ParamConvertor` and `ArgumentResolver` in this scenario, the first one skips the convertation if the value is already set and matches the type https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/src/Request/ParamConverter/ParamConverterManager.php#L62

**Comment by HypeMC** [comment]
@onEXHovia Could you see if #52891 fixes your issue?

**Comment by onEXHovia** [comment]
@HypeMC thank you, the patch solves the problem. Now pinned argument resolver works like param convertor and not ignored value in the request attributes.
