### ISSUE TITLE
[Bug][DoctrineBridge] Global query time always at 0.00 ms on profiler

### ISSUE THREAD

**Issue by maximethiry** [symfony/symfony#52880]
### Symfony version(s) affected

7.0

### Description

Since I updated a project from 6.3 to 7.0, the global query time for Doctrine queries is always at 0.00 ms on the profiler.

For the same http request :
![Screenshot from 2023-12-04 05-33-24](https://github.com/symfony/symfony/assets/55696133/25af4826-602b-4465-9913-1b332fc782af)
![Screenshot from 2023-12-04 05-33-39](https://github.com/symfony/symfony/assets/55696133/566fe8a8-904b-4072-b403-99dda0531d1a)

### How to reproduce

Do multiple doctrine calls on a same http request

### Possible Solution

After a few tests, it seems that the problem comes from the switch to native return types on `Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector` method.

For context :

```
public function getTime(): int
{
    $time = 0;
    foreach ($this->data['queries'] as $queries) {
        foreach ($queries as $query) {
            $time += $query['executionMS'];
        }
    }

    return $time;
}
```

Inside the `getTime` method, when I check what's inside `$time` before the return, I have a float smaller than 0 (something like 0.0015671253204346 for example)
So when returning, this value is casted to int and become 0.

After changing the return type of the `getTime` method to float, the calculation worked again.

Working on a PR.

**Comment by laurentmuller** [comment]
I have also the following deprecation with Symfony version 7.0.1:

`22.12.2023 08:28:11.410|php|INFO|Deprecated: Implicit conversion from float 0.10057234764099121 to int loses precision|{"exception":"[object] (ErrorException(code: 0): Deprecated: Implicit conversion from float 0.10057234764099121 to int loses precision at D:\\PhpStorm\\calculation\\vendor\\symfony\\doctrine-bridge\\DataCollector\\DoctrineDataCollector.php:97)"}|[]`
