### ISSUE TITLE
HttpClient tmpfile FormDataPart is not sending via bodyToIterable

### ISSUE THREAD

**Issue by AndriiMz** [symfony/symfony#52888]
### Symfony version(s) affected

6.3.7

### Description

In a previous version of http client 5.4.* we api client request
```
   $rows = [['test' => 1, 'next' => 2]]
   $csv = tmpfile();
   fputcsv($csv, array_keys($rows[0]));
   foreach ($rows as $row) {
            fputcsv($csv, array_values($row));
   }
  $fileName = stream_get_meta_data($csv)['uri'];

  $dataPart =  DataPart::fromPath($fileName);
  $formData = new FormDataPart(['data' => $dataPart]);
  $response = $this->client->request(
                'POST',
              "http://somedomain.com",
                [
                    'headers' => $formData->getPreparedHeaders()->toArray(),
                    'body' => $formData->bodyToIterable(), 
                ]
            );
```
After http client  have been updated to 6.3.7 we start getting errors like Unable to open path "/tmp/phpuU7Jgg".
Idea: since http client send a request in another process probably access to tmpfile is not available in neighbour process.

### How to reproduce

Create a project, install symfony http client dependency
Add to the file:
```
   require_once __DIR__ . '/vendor/autoload.php';

   $rows = [['test' => 1, 'next' => 2]]
   $csv = tmpfile();
   fputcsv($csv, array_keys($rows[0]));
   foreach ($rows as $row) {
            fputcsv($csv, array_values($row));
   }
  $fileName = stream_get_meta_data($csv)['uri'];

  $dataPart =  DataPart::fromPath($fileName);
  $formData = new FormDataPart(['data' => $dataPart]);
  $response = HttpClient::create()->request(
                'POST',
              "http://somedomain.com",
                [
                    'headers' => $formData->getPreparedHeaders()->toArray(),
                    'body' => $formData->bodyToIterable(), 
                ]
            );
```

**Comment by nicolas-grekas** [comment]
Can you figure out which PR introduced the issue?

**Comment by AndriiMz** [comment]
Solved, 
this part was placed in separate class and looks like file stream was closed when execution process left class 
``` 
 $csv = tmpfile();
   fputcsv($csv, array_keys($rows[0]));
   foreach ($rows as $row) {
            fputcsv($csv, array_values($row));
   }
  $fileName = stream_get_meta_data($csv)['uri'];
```
When i placed in same class it works, looks like gc issue

**Comment by AndriiMz** [comment]
Solved

**Comment by stof** [comment]
@AndriiMz this is because a stream created by `tmpfile` has a special behavior: when it gets destroyed, it also deletes the temporary file automatically: https://www.php.net/tmpfile
By moving the code in the same class, you made your temporary file stored in the `$csv` variable be destroyed only after the HTTP request (as the `$csv` variable was still in scope until the end of the function).
