### ISSUE TITLE
Return type of \Symfony\Component\Workflow\Registry::get() changed from Workflow to WorkflowInterface

### ISSUE THREAD

**Issue by fashxp** [symfony/symfony#52882]
### Symfony version(s) affected

6.4.0

### Description

Return type of `\Symfony\Component\Workflow\Registry::get()` changed from `Workflow` to `WorkflowInterface`. See commit https://github.com/symfony/symfony/commit/963cc7a40dab0f6a119a60db671e97b5aa1b643c

Is that a wanted change? It could be seen as BC break and for example breaks Pimcore code, see https://github.com/pimcore/pimcore/pull/16320. 

### How to reproduce

Try to install Pimcore with latest symfony releases.

**Comment by derrabus** [comment]
> Is that a wanted change?

Yes. We needed it for the profiler integration, see #51220.

> It could be seen as BC break and for example breaks Pimcore code, see [pimcore/pimcore#16320](https://github.com/pimcore/pimcore/pull/16320).

That PR is about fixing new errors reported by PHPStan. We don't see a failing static analysis as a breaking change. If you can elaborate how this change actually broke Pimcore at runtime, we can discuss a better migration strategy.

**Comment by derrabus** [comment]
cc @lyrixx

**Comment by fashxp** [comment]
Actually, I don't think it broke runtime, it just broke static analysis (see [actions run](https://github.com/pimcore/pimcore/actions/runs/7055216132/job/19246310867)) - which would require the signature changes of the [linked PR](https://github.com/pimcore/pimcore/pull/16320) on our end as the return type of `\Symfony\Component\Workflow\Registry::get()` is further delegated. 

I was just wondering and wanted to double check as the BC promise states no changes of return types. 
So, thank you for your answer and your clarification.
