### ISSUE TITLE
Cannot upgrade to Symfony 7.0 due to twig/cssinliner-extra conflict 

### ISSUE THREAD

**Issue by jsfgreen** [symfony/symfony#52890]
### Symfony version(s) affected

7.0.0

### Description

When I try to upgrade to Symfony 7.0 I get a bevy of composer conflicts:

```
  Problem 1
    - tijsverkoyen/css-to-inline-styles[2.0.0, ..., 2.1.0] require symfony/css-selector ^2.7|~3.0 -> found symfony/css-selector[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but it conflicts with your root composer.json require (^6.4|^7.0).
    - tijsverkoyen/css-to-inline-styles 2.2.0 requires php ^5.5 || ^7 -> your php version (8.2.10) does not satisfy that requirement.
    - tijsverkoyen/css-to-inline-styles[2.2.1, ..., 2.2.2] require php ^5.5 || ^7.0 -> your php version (8.2.10) does not satisfy that requirement.
    - tijsverkoyen/css-to-inline-styles 2.2.3 requires symfony/css-selector ^2.7 || ^3.0 || ^4.0 || ^5.0 -> found symfony/css-selector[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.26] but it conflicts with your root composer.json require (^6.4|^7.0).
    - tijsverkoyen/css-to-inline-styles[2.2.4, ..., 2.2.6] require symfony/css-selector ^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0 -> found symfony/css-selector[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.26, v6.0.0, ..., v6.4.0] but these were not loaded, likely because it conflicts with another require.
    - twig/cssinliner-extra v3.8.0 requires tijsverkoyen/css-to-inline-styles ^2.0 -> satisfiable by tijsverkoyen/css-to-inline-styles[2.0.0, ..., 2.2.6].
    - Root composer.json requires twig/cssinliner-extra ^3.8 -> satisfiable by twig/cssinliner-extra[v3.8.0].
```

I am able to upgrade if I remove `"twig/cssinliner-extra": "^3.8",` from _my own_ composer.json file but then the `LoginLinkNotification` feature because of the missing `inline_css` twig filter.

### How to reproduce

Simply install a fresh copy of Symfony 7 and then try to install twig/cssinliner-extra.

```
  symfony new my_project_directory --version="7.0.*" --webapp
  composer require twig/cssinliner-extra
```

### Additional Context

What's even weirder is that it seems like I shouldn't even have to have `twig/cssinliner-extra` included in my own composer.json being that it's already a part of the `twig/extra` internal composer.json file (in vendor/twig/extra-bundle/composer.json).  But that appears to be a whole other problem. Just thought I would include my observation of that here anyway in case it's useful.

**Comment by ghost** [comment]
`twig/cssinliner-extra` is fine. `tijsverkoyen/css-to-inline-styles` is the package that causes errors. You have to wait for it to be compatible with SF 7.0. 
https://github.com/tijsverkoyen/CssToInlineStyles/issues/244

**Comment by xabbuh** [comment]
closing as explained
