### ISSUE TITLE
[messenger] `\Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware` do not run retry logic as intended

### ISSUE THREAD

**Issue by itcodeOstrowski** [symfony/symfony#52903]
### Symfony version(s) affected

6.4

### Description

Hello,

If messages retrieved from the queue with `$amqpReceivedStamp->getAmqpEnvelope()->isRedelivery()` are true, the `RejectRedeliveredMessageException` will be thrown in [RejectRedeliveredMessageMiddleware](https://github.com/symfony/messenger/blob/6.4/Middleware/RejectRedeliveredMessageMiddleware.php). This should cause the default retry logic to run, but because [RejectRedeliveredMessageException](RejectRedeliveredMessageException) implements [UnrecoverableExceptionInterface](https://github.com/symfony/messenger/blob/6.4/Exception/UnrecoverableExceptionInterface.php), and because in the [SendFailedMessageForRetryListener](https://github.com/symfony/messenger/blob/6.4/EventListener/SendFailedMessageForRetryListener.php)`::shouldRetry()` logic we check for `UnrecoverableExceptionInterface`, the retry logic is not triggered. 

### How to reproduce

1. Consume message that has [Redelivered](https://www.rabbitmq.com/consumers.html#message-properties) [stamp](https://www.rabbitmq.com/reliability.html#consumer-side).
2. Message should be queued again with default retry logic, but instead it is gone.

### Possible Solution

Just revert that commit: https://github.com/symfony/messenger/commit/2479dc6b16fead8d90ba8bb7a28688e285694c4d (i don't understand intention of this commit, maybe just use `\Symfony\Component\Messenger\Exception\RecoverableExceptionInterface` instead) or change description of `\Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware` because it is misleading otherwise. 

### Additional Context

interesting classes:
`\Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware`
`\Symfony\Component\Messenger\Exception\RejectRedeliveredMessageException`
`\Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener::shouldRetry`

This bug makes usage of rabbitMQ much more difficult because now it is not possible to check messages in web interface, if the check is done, it would be not possible to use that message.

**Comment by mythxxx** [comment]
This is definitely a bug, redelivered messages should not be simply dropped, but retried as before. At this moment we are losing messages in production, we had to revert to v.6.3.12

**Comment by nikophil** [comment]
Hi, sorry for the late reply and for that bug :grimacing: 

I'm going to revert this very soon
