### ISSUE TITLE
[Profiler][HttpClient] „Copy as cURL” button missing in Symfony 6.4.0 — 6.4.1

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#52920]
### Symfony version(s) affected

6.4.0, 6.4.1

### Description

When using the `HttpClientInterface` in Symfony <=6.3.8, you had a nice little „Copy as cURL” button within the Profiler's „HTTP Client” section. This button is missing since Symfony 6.4.0 and still missing in 6.4.1.

This feature has been introduced in 6.1.0: https://symfony.com/blog/new-in-symfony-6-1-profiler-improvements-part-2#copying-http-client-requests-as-curl-commands

### How to reproduce

- Use the `HttpClientInterface` to make any request
- Open the web profiler, go the „HTTP Client” section
- See the missing button

### Possible Solution

I had a quick glimpse at the changed Twig templates and the `http_client.html.twig` template still contains the necessary button: https://github.com/symfony/web-profiler-bundle/blob/14752d3fb77c3c69b6cee7c03c06e2d6494a196b/Resources/views/Collector/http_client.html.twig#L132

The `curlCommand` trace is also present: https://github.com/symfony/http-client/blob/db714986d3b84330bb6196fdb201c9f79b3a8853/DataCollector/HttpClientDataCollector.php#L171

I can also confirm that I'm using a `Symfony\Component\HttpClient\TraceableHttpClient` to make my HTTP requests and that the `HttpClientDataCollector`'s logic is being called that generates the `curlCommand` information for the traces.

## Working in Symfony 6.3 (all dependencies at their latest ~6.3 version)

![CleanShot 2023-12-06 at 21 54 10@2x](https://github.com/symfony/symfony/assets/439899/a4d83e56-e320-4190-80e5-248c26e3dd0a)

## Missing in Symfony 6.4.0 / 6.4.1

![CleanShot 2023-12-06 at 21 55 11@2x](https://github.com/symfony/symfony/assets/439899/30604f38-c500-4e2e-af57-680bd4012809)

**Comment by keichinger** [comment]
On top of that bug report, I've had a little bit of a deeper dive and it looked like it's easier than anticipated. The button has the CSS class `hidden`.

<details>
<summary>navigator.clipboard / JS-based buttons</summary>

I'm not sure on the exact reasoning for why we want to initially hide clipboard-related buttons and show them using JS, as the browser support for `navigator.clipboard` is quite excellent when looking at MDN https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility, even though it says that the API is still limited.

However, that might be a different discussion for another day.
</details>

Since this class has been in 6.3 as well, I was wondering what the reason might be. The button itself is using the `navigator.clipboard` API and will be updated from a piece of JS within the `toolbar_js.html.twig`.

Setting some breakpoints and dumps within the logic that runs: Nothing was printed.

Digging a bit deeper and finding the actual point of insertion within the `WebDebugToolbarListener::onKernelResponse()`. One of its last calls is `$this->injectToolbar($response, $request, $nonces)`, which ultimately loads the `toolbar_js.html.twig` that includes the logic we're looking for.

The problem here is: This template is never included on my installation. It looks like that the `X-Debug-Token` is missing in the line above, which is why it's not injecting the template: https://github.com/symfony/web-profiler-bundle/blob/14752d3fb77c3c69b6cee7c03c06e2d6494a196b/EventListener/WebDebugToolbarListener.php#L121-L131

For tonight, I've stopped investigating as it's kind of late. I may continue tomorrow and see if I can figure it out so that I can file a PR. If someone wants to step in with deeper knowledge, who may already know what's happening, then please feel free :)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by HypeMC** [comment]
@keichinger Could you check if #52937 fixes your issue?

**Comment by keichinger** [comment]
@HypeMC great work! That indeed fixes my issue. I've left a small note on your PR. Other than that, it's excellent!
