### ISSUE TITLE
Issue with phpunit 8.5.35 and 8.5.36 

### ISSUE THREAD

**Issue by CedricYii** [symfony/symfony#52929]
### Symfony version(s) affected

4.4.50

### Description

Issue using phpunit since it was updated to 8.5.35 and 8.5.36
It was working fine until 8.5.34

### How to reproduce

Trying to run
`php vendor/bin/simple-phpunit` 
Will result in
```No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-8.5-0"
Installing phpunit/phpunit (8.5.36)
...  
Fatal error: Uncaught Error: Class 'Symfony\Bridge\PhpUnit\TextUI\Command' not found in (...)\vendor\bin\.phpunit\phpunit-8.5-0\phpunit:22
```

**Comment by xabbuh** [comment]
Which version of the PHPUnit bridge do you use?

**Comment by CedricYii** [comment]
>php composer.phar show symfony/phpunit-bridge
```

name     : symfony/phpunit-bridge
descrip. : Provides utilities for PHPUnit, especially user deprecation notices management
keywords :
versions : * v4.4.49
type     : symfony-bridge
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/phpunit-bridge.git b3378a7d305666a69e08457b65af8bca179fbbbb
dist     : [zip] https://api.github.com/repos/symfony/phpunit-bridge/zipball/b3378a7d305666a69e08457b65af8bca179fbbbb b3378a7d305666a69e08457b65af8bca179fbbbb
path     : ...\vendor\symfony\phpunit-bridge
names    : symfony/phpunit-bridge


```
Is this what you need?

**Comment by xabbuh** [comment]
You need to update your bridge to the latest patch release of one of the maintained branches or force an older PHPUnit version with the `SYMFONY_PHPUNIT_VERSION` env variable.

**Comment by CedricYii** [comment]
Thanks! 
Upgrading bridge to ^7.0 did the trick (I didn't want to limit SYMFONY_PHPUNIT_VERSION)

Would you know why package didn't update by itself with a global 'composer install' nor 'composer update'?
