### ISSUE TITLE
Profiler not showing

### ISSUE THREAD

**Issue by abdounikarim** [symfony/symfony#52931]
### Symfony version(s) affected

6.4.1

### Description

Hello Symfony team, it seems there is sometimes some troubles with the profiler not showing.

### How to reproduce

Create a new fresh symfony project : 
```bash
symfony new my_project --version=lts
```

Launch the Symfony webserver and open the URL. 

Add the profiler :
```bash
composer require --dev symfony/profiler-pack
```

Refresh your page many times, you'll see, sometimes, the profiler is not showing.

### Additional Context

Problem seen in PHP 8.2 and 8.3.

**Comment by GromNaN** [comment]
I could not reproduce with a fresh symfony project like you described. There may be an issue with your PHP setup.
When you run `symfony server:start`, what is logged to the output when you load the page?

**Comment by abdounikarim** [comment]
@GromNaN I added some informations. I work on a Mac.

It seems there is no error in the server log in error. But there is in the browser. For the same token, the server log a 200 response but in the browser, it's a 404.

<img width="1418" alt="Capture d’écran 2023-12-08 à 10 02 44" src="https://github.com/symfony/symfony/assets/15892761/1ab96f90-a034-4037-b470-e4fbe35f8d5e">

<img width="1439" alt="Capture d’écran 2023-12-08 à 10 00 37" src="https://github.com/symfony/symfony/assets/15892761/dbf221df-2d42-474e-bbbb-23e15d38204f">

<img width="1053" alt="Capture d’écran 2023-12-08 à 10 00 48" src="https://github.com/symfony/symfony/assets/15892761/4948643c-59bd-4dff-b44b-a4cf87bd1b1d">

**Comment by GromNaN** [comment]
The response for the wdt is actually correct (the 404 refers to the default home page). The problem may be in the browser that restrict AJAX calls. Do you have any Chrome extension that could block the request? Can you try in guest session?

**Comment by abdounikarim** [comment]
Same trouble in guest session.

**Comment by LinkingYou** [comment]
I am also working on a Mac (M1, macOS 14.2) with PHP8.3 and I have the same problems.

Tested with a blank project with Symfony 7.0.1 and Symfony 6.4.1, Safari 17.2 and Chrome Version 120.0.6099.109

The profiler is rarely loaded. Whenever it is not loaded, I get an entry from "symfony serve" that says "httputil: ReverseProxy read error during body copy: fcgi: invalid header version".

The Symfony CLI version is 5.7.5.

In the Safari browser console, I get "Failed to load resource: Die Netzwerkverbindung wurde unterbrochen." 
In the Chrome console, it says "Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR".

```
2023/12/14 14:40:18 httputil: ReverseProxy read error during body copy: fcgi: invalid header version
[Application] Dec 14 13:40:18 |ERROR  | REQUES Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://127.0.0.1:8000/"" at RouterListener.php line 127 
[Application] Dec 14 13:40:18 |INFO   | REQUES Matched route "_wdt". method="GET" request_uri="https://127.0.0.1:8000/_wdt/af44bb" route="_wdt" route_parameters={"_controller":"web_profiler.controller.profiler::toolbarAction","_route":"_wdt","token":"af44bb"}
[Web Server ] Dec 14 14:40:18 |WARN   | SERVER GET  (404) / ip="127.0.0.1"

```

**Comment by xabbuh** [comment]
Does the issue persist when updating to the latest version (5.7.7 right now) of the Symfony CLI?

**Comment by LinkingYou** [comment]
> Does the issue persist when updating to the latest version (5.7.7 right now) of the Symfony CLI?

With the current version 5.7.7 I no longer have any problems.

**Comment by nicolas-grekas** [comment]
Thanks for the feedback, closing then. Please upgrade if anyone has the issue.

**Comment by waneoone** [comment]
https://mywebside.com/_profiler/  
juste i add     **_profiler/**    to url of my website end i hit enter
i resolve my probleme
