### ISSUE TITLE
What about an `IsCsrfTokenValid` attribute?

### ISSUE THREAD

**Issue by yguedidi** [symfony/symfony#52947]
### Description

POST only actions like delete actions are likely to use such kind of code:
```php
if (!$this->isCsrfTokenValid('delete_example', $request->request->getString('_token'))) {
    throw new BadRequestHttpException('This token is invalid');
}
```
What about introducing a new `IsCsrfTokenValid` attribute that takes the id and optionally the token key to avoid repeating the `if` check.

If accepted I can try a PR during the Hackday 🙂

### Example

```php
#[IsCsrfTokenValid('delete_example')]
public function deleteAction(): Response
{
    /// ...
```

**Comment by wouterj** [comment]
Hi @yguedidi! I think it looks interesting.

I guess this can work similar to how the `#[IsGranted]` attribute is implemented. Happy to help if you want some pointers (find the guy with the gray Symfony hoodie :smile: )

**Comment by yguedidi** [comment]
Thank you! on it!
