### ISSUE TITLE
[Console] The profile option is missing some checks to ensure the required web context is present

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#52943]
### Symfony version(s) affected

6.4.0

### Description

Using the `--profile` option with the framework bundle but for a CLI (only) application, i.e. there is no web context.

### How to reproduce

Currently if one uses a CLI application with the framework bundle, when executing a command `--profile`, you might get:

```
 [WARNING] The "--profile" option needs the profiler integration. Try enabling the "framework.profiler" option.
```

Fair enough, you edit the configuration to do `framework.profiler: true`, and repeat, you will have:

```
  The service "console_profiler_listener" has a dependency on a non-existent service "router". Did you mean this: "data_collector.router"?
```

### Additional Context

I could reproduce this in https://github.com/theofidry/console:

- clone the project
- `bin/console app:foo --profile`
- The Symfony framework bundle application contained is in `tests/Integration`

**Comment by HeahDude** [comment]
@theofidry thanks for the report, #52963 should fix your issue, can you confirm?
