### ISSUE TITLE
Issue with Console::findExecutable() in symfony/process 6.4 breaking application

### ISSUE THREAD

**Issue by herpaderpaldent** [symfony/symfony#52953]
### Symfony version(s) affected

symfony/process 6.4

### Description
After updating to symfony/process version 6.4, our Laravel application that utilizes laravel/horizon has encountered a significant issue leading to a failure in the application's execution. This seems to be related to changes made in the `Console::findExecutable()` method in a recent update (link to the commit: [e66a68c](https://github.com/symfony/symfony/commit/e66a68c180c6d5baa5749e02e32467f0846d6a65#diff-23026195ab92334dfa62f08d7ad13fc3adefa57877e2768bac98cbbbf84685a1)).

### Error Log
Upon updating, the following error was encountered:

```
[2023-12-08 02:20:12] production.ERROR: is_executable(): open_basedir restriction in effect. File(/usr/bin/php) is not within the allowed path(s): (:/var/www/html:/dev/stdout:/tmp) {"exception":"[object] (ErrorException(code: 0): is_executable(): open_basedir restriction in effect. File(/usr/bin/php) is not within the allowed path(s): (:/var/www/html:/dev/stdout:/tmp) at /var/www/html/vendor/symfony/process/ExecutableFinder.php:76)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap{closure}()
#2 /var/www/html/vendor/symfony/process/ExecutableFinder.php(76): is_executable()
#3 /var/www/html/vendor/symfony/process/PhpExecutableFinder.php(84): Symfony\Component\Process\ExecutableFinder->find()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(87): Symfony\Component\Process\PhpExecutableFinder->find()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(108): Illuminate\Console\Application::phpBinary()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php(143): Illuminate\Console\Application::formatCommandString()
#7 /var/www/html/vendor/seatplus/eveapi/src/EveapiServiceProvider.php(182): Illuminate\Console\Scheduling\Schedule->command()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1071): Seatplus\Eveapi\EveapiServiceProvider->Seatplus\Eveapi{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1014): Illuminate\Foundation\Application->fireAppCallbacks()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(261): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#15 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#16 {main}
```

<img width="1334" alt="image" src="https://github.com/symfony/symfony/assets/6583519/69a0b3b7-05b8-407f-9b5e-20dd670297db">

### How to reproduce

You'll find a repository to recreate the issue here: https://github.com/herpaderpaldent/issue-52953 

it is a basic laravel app with a docker-compose to start the app.

Simply run `docker-compose up` and then open 127.0.0.1:8080 to access the app and reproduce the error

### Possible Solution

revert the commit

**Comment by herpaderpaldent** [comment]
i just added a repository to recreate the issue and attached an image with the error. 

Please let me know if you need anything else

**Comment by ChrisToxz** [comment]
Seems to be related to the docker image you use: https://github.com/serversideup/docker-php/issues/258

**Comment by herpaderpaldent** [comment]
> Seems to be related to the docker image you use: [serversideup/docker-php#258](https://github.com/serversideup/docker-php/issues/258)

No has nothing to do with each other.

among the things: the linked issue is about a pre-release version missing the configuration to allow modification of open_dir pathes. 

this issue is about symfony/process:6.4 breaking what worked before.
