### ISSUE TITLE
[TwigBridge] function `twig_test_empty` is deprecated in Twig 3.9

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#52987]
### Symfony version(s) affected

5.4.31, 6.4.0, 7.0.0, 7.1

### Description

The `twig_*` global functions are deprecated in Twig 3.9 https://github.com/twigphp/Twig/pull/3883, and removed in Twig 4.0 https://github.com/twigphp/Twig/pull/3937

The function `twig_test_empty` is used in `Symfony\Bridge\Twig\Node\SearchAndRenderBlockNode`:

https://github.com/symfony/symfony/blob/228a275ddcc1a4301fc8865945c0686b56658135/src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php#L53

https://github.com/symfony/symfony/blob/228a275ddcc1a4301fc8865945c0686b56658135/src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php#L100

### How to reproduce

```
composer create-project symfony/demo
composer require "twig/twig: 3.x-dev"
```

Go to `https://localhost:8000/fr/admin/post/1/edit`

Deprecation message:

```
Since twig/twig 3.9.0: Using the internal "twig_test_empty" function is deprecated.
```

### Possible Solution

Duplicate the function as a static method in `SearchAndRenderBlockNode`.

**Comment by xabbuh** [comment]
I'm on it

**Comment by TMWagner** [comment]
@GromNaN 
OK - so it is deprecated. Is there a replacement?

**Comment by GromNaN** [comment]
There is no replacement. This function is an implementation detail of the [`empty` test](https://twig.symfony.com/doc/3.x/tests/empty.html), that's why the new `CodeExtension::testEmpty()` is flagged as `@internal` and should not be used. It can be modified or removed in any minor version.

You should write your own function.
