### ISSUE TITLE
Missing File constraint translations

### ISSUE THREAD

**Issue by KamilPesek** [symfony/symfony#52995]
### Symfony version(s) affected

6.4

### Description

There is at least one translation missing for czech (cs locale) for `/vendor/symfony/validator/Constraints/File.php `

`The extension of the file is invalid ({{ extension }}). Allowed extensions are {{ extensions }}.`

I think it will be missing also in another languages and I think this won't be the only key which is missing. Not sure how these are generated but would be good to check this overall.

### How to reproduce

Submit invalid form with field with File constraint. In this case submit e.g. jpg file.

```
$builder
            ->add('files', FileType::class, [
                        'multiple' => true,
                        'constraints' => [
                    new All([
                        'constraints' => [
                            new File(['extensions' => ['pdf', ],]),
                        ],
                    ]),
                ],
            ]);
```

**Comment by xabbuh** [comment]
looks like this was forgotten in #47710
