### ISSUE TITLE
[HttpKernel] Cache Attribute case sensitivity / BC conventions

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#53010]
### Description

This one is more a question than an issue or a request... (no personal urgent need to change anything)

-> What is the BC policy on "case sensitivity" ? 

Currently in the [Cache Attribute](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpKernel/Attribute/Cache.php), we have

In lowercase:
* maxage
* smaxage

In camelCase:
* lastModified
* maxStale
* staleWhileRevalidate

To quote [MDM](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) (rewording the [RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-14.9))

> Caching directives are case-insensitive. However, lowercase is recommended because some implementations do not recognize uppercase directives.

So we could (and would probably) say it does not matter .. (even if one could argue that there is a reversible path between lastModified and last-modified, but none between smaxage and s-maxage)

But my real question is on the "how" more than the "why" ... 

_**If**_ we "wanted" to switch from "maxage" to maxAge and from smaxage to sMaxage (and i strongly insist on the _**If**_) ... 
* would it be possible before 8.0 ? 
* how could such a BC deprecation / layer work ?

**Comment by javiereguiluz** [comment]
In the RFC that you linked (https://datatracker.ietf.org/doc/html/rfc2616#section-14.9) the naming is also inconsistent:

```
| "max-age" "=" delta-seconds            ; [Section 14.9.3]
| "s-maxage" "=" delta-seconds           ; [Section 14.9.3
```

Either `max-age` should be `maxage` or `s-maxage` should be `s-max-age`.

Replying to your question, I think we should keep the current parameter names:

* `maxage` looks OK as a single word (`maxAge` also looks nice, but I'm not sure it's worth changing it and forcing the change in all apps)
* `sMaxage` doesn't look OK in my opinion; `sMaxAge` would look better ... but then it'd be inconsistent with `maxage` ... so, probably it's better to keep it as is.

**Comment by smnandre** [comment]
@javiereguiluz i agree this is a "no perfect solution" situation (as you said, even the RFC is far from ideal), and honestly a really minor subject.

What i'd like to understand is how we "would" / "could" handle such a change.. How is a BC layer possible with case-insensitive code ?

**Comment by wouterj** [comment]
We cannot provide a BC layer unless we have a method that *only* supports named parameters and not positioned parameters. We do not have such methods in Symfony atm (attribute constructors are the only ones where we care about named parameter BC, but we don't explicitly say that parameter position is not part of the BC promise).

This means that, besides have probably a low big impact, we also don't have a way to provide a smooth upgrade path. In such situations, we almost always reject changes until innovations in the landscape (or a brilliant idea) allows us to provide such path.

As I understand this issue more as a "what if", I'll close this know. Let me know if I misunderstood and we have to reopen it - it's only one click away :wink:

**Comment by wouterj** [comment]
Actually, I think we can provide a BC path for both:

```php
// current
public function __construct(int $maxage)
{

// BC
public function __construct(int $maxAge = null, int $maxage = null)
{
    if (null === $maxAge && null !== $maxage) {
        trigger_deprecation(...);
        $maxAge = $maxage;
    }

// next major
public function __construct(int $maxAge)
{
```

This should work for both, `Cache(120)` already uses the new name so doesn't trigger the deprecation and `Cache(maxage: 120)` uses the old name and does trigger the deprecation.

**Comment by smnandre** [comment]
Totally a « what if » and thank you for the explanation ! 

🤝

**Comment by smnandre** [comment]
> Actually, I think we can provide a BC path for both:
> 
> ```
> // current
> public function __construct(int $maxage)
> {
> 
> // BC
> public function __construct(int $maxAge = null, int $maxage = null)
> {
>     if (null === $maxAge && null !== $maxage) {
>         trigger_deprecation(...);
>         $maxAge = $maxage;
>     }
> 
> // next major
> public function __construct(int $maxAge)
> {
> ```
> 
> This should work for both, `Cache(120)` already uses the new name so doesn't trigger the deprecation and `Cache(maxage: 120)` uses the old name and does trigger the deprecation.

Wow that is smart !

(i insist, this was on an hypothetical level, let’s not bother everyone with a deprecation for that haha)
