### ISSUE TITLE
Integrate Native GraphQL Support in Symfony

### ISSUE THREAD

**Issue by aaj89** [symfony/symfony#53068]
### Overview
While Symfony supports RESTful API development, the increasing popularity and efficiency of GraphQL necessitate native support for GraphQL within Symfony.

#### I propose the integration of a GraphQL module in Symfony, enabling developers to:
- Define GraphQL schemas directly within Symfony.
- Automatically generate GraphQL types from existing Symfony entities.
- Provide an efficient querying interface for frontend applications.

### Benefits
- Modernization: Aligns Symfony with modern web development trends.
- Performance: Enables faster and more efficient data retrieval.
- Flexibility: Offers developers more options for API development.

### Implementation Considerations
- Ensure compatibility with existing RESTful services.
- Provide comprehensive documentation and examples.
- Consider a phased rollout, starting with basic query support, followed by mutations and subscriptions.

**Comment by GromNaN** [comment]
That feature requires an ORM, which is not provided by Symfony but by Doctrine. 

Have you tried API platform, it supports GraphQL very well. https://api-platform.com/docs/core/graphql/

**Comment by derrabus** [comment]
> While Symfony supports RESTful API development

It doesn't, actually. REST embraces the capabilities of the HTTP protocol which makes it easy to implements in any web framework. However, Symfony itself does not provide any tooling specific to REST. There are very good third-party bundles that provide this kind of functionality.

* API Platform
* NelmioApiDocBundle
* BazingaHateoasBundle
* FOSRestBundle

Symfony merely serves as an extensible foundation for those packages.

> the increasing popularity and efficiency of GraphQL necessitate native support for GraphQL within Symfony.

I don't think so. GraphQL can be implemented in third-party packages the same way as REST is. You might want to take a look at API platform. It might already provide what you need.

**Comment by wouterj** [comment]
I agree with the others. Symfony doesn't have anything related to models, we simply can't integrate REST nor GraphQL.

However, the community has support for both in well known and solid bundles and the API Platform. I suggest checking them out if you need a GraphQL application.
