### ISSUE TITLE
Default locale is ignored  when `set_locale_from_accept_language` is used

### ISSUE THREAD

**Issue by jkobus** [symfony/symfony#53086]
### Symfony version(s) affected

6.4.0

### Description

Default locale setting is ignored when "set_locale_from_accept_language" is used.

### How to reproduce

I have the following configuration:

```yaml
framework:
    default_locale: en
    set_locale_from_accept_language: true
    set_content_language_from_locale: false
    enabled_locales: ['pl', 'en']
```

Then, by issuing `curl https://localhost` which has following code:

```php
class IndexNoLocaleController extends AbstractController
{
    #[Route('/')]
    public function __invoke(Request $request): Response
    {
        return $this->redirectToRoute('app_default', ['_locale' => $request->getLocale()]);
    }
}
```

I am redirected to `/pl`.

I expect to be redirected to `/en` instead.

Note: changing order of `enabled_locales: ['en', 'pl']` will result in redirection to `/en` as the first value from the array is used as "default", yet still default from the "default_locale" is ignored.

### Possible Solution

The `\Symfony\Component\HttpFoundation\Request::getPreferredLanguage` accepts ['pl', 'en'] as input, as there are no languages set by curl it just falls into:

```php
if (!$preferredLanguages) {
    return $locales[0];
}
```

The call originates from `LocaleListener.php:72`:

```php
private function setLocale(Request $request): void
{
    if ($locale = $request->attributes->get('_locale')) {
        $request->setLocale($locale);
    } elseif ($this->useAcceptLanguageHeader) {
        if ($preferredLanguage = $request->getPreferredLanguage($this->enabledLocales)) {
            $request->setLocale($preferredLanguage);
        }
        $request->attributes->set('_vary_by_language', true);
    }
}
```

In that listener, there is `$defaultLocale` property available, as well as in the request, therefore maybe the solution is to use the default locale rather than picking "first entry" from enabled locales.

### Additional Context

This is an edge case, but can affect mostly Google Bots [as bots do not set accept language headers](https://developers.google.com/search/docs/specialty/international/locale-adaptive-pages?hl=en).

**Comment by smnandre** [comment]
**Update:** nope, better solution next comment.

I think the [Request::getPreferredLanguage()](https://github.com/symfony/http-foundation/blob/7.0/Request.php#L1527) should return `null` when client has no preferred language.

Updating (fixing? not sure) this would solve your problem, as the default locale would then be used as expected.

**Comment by smnandre** [comment]
After a bit of git archeology... this has been the behaviour of this method since 2010.

So we may not want to change it 😅 

Maybe one simple solution could be to do something like that in the [LocaleListener](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpKernel/EventListener/LocaleListener.php)

```diff 
private function setLocale(Request $request): void
    {
        if ($locale = $request->attributes->get('_locale')) {
            $request->setLocale($locale);
-        } elseif ($this->useAcceptLanguageHeader) {
+        } elseif ($this->useAcceptLanguageHeader && $request->getLanguages()) {
            if ($preferredLanguage = $request->getPreferredLanguage($this->enabledLocales)) {
                $request->setLocale($preferredLanguage);
            }
            $request->attributes->set('_vary_by_language', true);
        }
    }
 ```

Meaning we'd use the language headers ... only when they exists. Not a bad idea i guess.

**Comment by jkobus** [comment]
I was thinking about changing the Request, but as you saw, its pretty old, written by @fabpot back in the day and could have some unexpected side effects. 

I will check your solution.

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/issues/53086#issuecomment-1865363515 sounds good to me. 
PR welcome (with test case :)

**Comment by smnandre** [comment]
@chalasr should this be seen as feature or bugfix ? It is not obvious to me there

**Comment by chalasr** [comment]
I agree it's not obvious but yes, I'd call it a bugfix

**Comment by jkobus** [comment]
It is not working. I was writing test and it seems that the [Request sets by default the Accept-Language header](https://github.com/symfony/symfony/blob/e9748122f6da5b9fc95c0ff04be91bbe40bba545/src/Symfony/Component/HttpFoundation/Request.php#L288) to `en-us,en;q=0.5`. So `getLanguages` is never empty.

This fails with `lt` as a result:

```
    public function testRequestDefaultLocaleIfNoAcceptLanguageHeaderIsPresent()
    {
        $request = Request::create('/');
//        $request->headers->set('Accept-Language', 'fr-FR,fr;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6,es;q=0.5');

        $listener = new LocaleListener($this->requestStack, 'de', null, true, ['lt', 'fr']);
        $event = $this->getEvent($request);

        $listener->setDefaultLocale($event);
        $listener->onKernelRequest($event);
        $this->assertEquals('de', $request->getLocale());
    }
```

I was thinking about prepending `enabledLocales` with the default locale but it feels hacky:

```
    private function setLocale(Request $request): void
    {
        if ($locale = $request->attributes->get('_locale')) {
            $request->setLocale($locale);
        } elseif ($this->useAcceptLanguageHeader) {
            $enabledLocales = [$this->defaultLocale, ...$this->enabledLocales];
            if ($preferredLanguage = $request->getPreferredLanguage($enabledLocales)) {
                $request->setLocale($preferredLanguage);
            }
            $request->attributes->set('_vary_by_language', true);
        }
    }
```

My new test is ok with this change but it fails the [testRequestNoLocaleFromAcceptLanguageHeader](https://github.com/symfony/symfony/blob/e9748122f6da5b9fc95c0ff04be91bbe40bba545/src/Symfony/Component/HttpKernel/Tests/EventListener/LocaleListenerTest.php#L173) as it correctly uses defaultLocale rather than falling back to `fr-FR`. Its a bit odd that the test says "NoLocaleFromAcceptLanguageHeader" yet it still uses `fr`.

Let me know what do you think; eventually we can use the defaultLocale as provided in the request - it is also available. Or maybe you have some better idea.

Update: It seems that such fix could introduce a breaking change for most apps that do not use the updated `set_locale_from_accept_language` feature and are depending on the way `Request` worked before. I was also used to the fact, that the request did return the locale the browser used no matter what locale was defined in the config as default :grin:

**Comment by smnandre** [comment]
Your example uses the create() method... but a request in the framework created by the createFromGlobals factory, and there is no default there. 

The proof it happens is that it happened to you live :) 

You can also call directly the constructor : 

```
$request = new Request( ... )
```


So i still think it's the best way to implement what you need

**Comment by jkobus** [comment]
I was thinking about that, that it can depend on the way the request is created. Will test that.

Update: You are right - thank you!
