### ISSUE TITLE
translation:push with nested yaml

### ISSUE THREAD

**Issue by ganti** [symfony/symfony#53085]
### Symfony version(s) affected

6.4

### Description

Having a nested YAML translation in e.g. `foo+intl-icu.en.yaml` when pushing the translation to loco the newly created items the keys are created but the values are missing.

### How to reproduce

`php ./bin/console  app translation:push --force`

i use loco as translation provider, does this error occur also for other providers?

### Possible Solution

When looking what is sent by the `TranslationPushCommand`, all translations are there correctly. So this may happen a layer below.

https://github.com/symfony/symfony/blob/0d9562ff6cdda11c71f0eb2bce0076f0d3a8ea9f/src/Symfony/Component/Translation/Command/TranslationPushCommand.php#L165

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ganti** [comment]
here I created a minimal example from 6.4 skeleton.
https://github.com/ganti/symfony-translation-push-example

I found out that with big translations +500 keys, loco takes a moment to display the translations on the website. So all is working as it should, therefore I close the issue.
