### ISSUE TITLE
[Translator] Using variable in yaml translation file

### ISSUE THREAD

**Issue by szal1k** [symfony/symfony#53097]
### Symfony version(s) affected

6.4.1

### Description

Hi,
I have translation file in yaml format and problem is get translation with injected variable.

### How to reproduce

For sample in file i use verb with variable:
`test.sample_text: 'Hello, %name%'`

In template i use |trans filter to get verb and translate with variable:
`{{ 'test.sample_text'|trans({'%name%': 'Kamil'}) }}`

And the result is: Hello, %name%

When i use text in filter, eg. {{ 'Hello, %name%'|trans({'%name%': 'Kamil'}) }} result is good:
Hello, Kamil

It is a bug? What am I doing wrong?

### Additional Context

When i change tag from '%' to '{' and add space eg.:
`test.sample_text: 'Hello, { name }'`

And in template: {{ 'Hello, { name }'|trans({'%name%': 'Kamil'}) }} 

It works fine, and result is: Hello, Kamil

But sample on the top is from official documentation, that documentation need change?

**Comment by wouterj** [comment]
If the Yaml filename has an `+intl-icu` suffix, you should use the [ICU MessageFormat syntax](https://symfony.com/doc/current/reference/formats/message_format.html).

If you need more help to get this working, please use one of the community support channels (https://symfony.com/support). This issue tracker is used to report actual bugs.
