### ISSUE TITLE
[Feature Request] Tagged iterators without tags!

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#53090]
### Description

I use tagged iterators mostly to autowire implementations of a given interface as an iterable.

```php
#[AutoconfigureTag('app.some_tag')]
interface SomeInterface
{
    ...
}

class SomeService
{
    public function __construct(
        /** @var SomeInterface[] */
        #[TaggedIterator('app.some_tag')]
        protected iterable $somes
    ) {
    }
}
```

It works great 👍 
And I understand I have to provide a tag because this is how the system works today ✅ 
And I understand that the tag may be useful for other use cases ✅ 
However, from a developer's POV, I don't care about what this tag is 99% of the time so I would like it to be optional.

### Example

It would be amazing if this simpler code was working 🤩 

```php
class SomeService
{
    public function __construct(
        /** @var SomeInterface[] */
        #[InterfaceIterator(SomeInterface::class)]
        protected iterable $somes
    ) {
    }
}
```

Or if it makes it easier to implement

```php
#[AutoconfigureForIterable]
interface SomeInterface
{
    ...
}
class SomeService
{
    public function __construct(
        /** @var SomeInterface[] */
        #[InterfaceIterator(SomeInterface::class)]
        protected iterable $somes
    ) {
    }
}
```

**Comment by valtzu** [comment]
This seems to already be working, tested on 6.4:

```php
#[AutoconfigureTag]
interface SomeInterface
{
    ...
}

class SomeService
{
    public function __construct(
        /** @var SomeInterface[] */
        #[TaggedIterator(SomeInterface::class)]
        protected iterable $somes
    ) {
    }
}
```

---

From the original `#[AutoconfigureTag]` PR https://github.com/symfony/symfony/pull/39804:

> The name of the tag is optional and defaults to the name of the tagged type (typically the FQCN of an interface). This should ease with writing locators/iterators of tagged services.

**Comment by derrabus** [comment]
Closing as explained. :v:

**Comment by sylfabre** [comment]
Thanks @valtzu 

This is not documented, I'll try to work on a PR some day
