### ISSUE TITLE
[DX] Symfony logo in dark mode

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#53105]
I find the white square around the logo a bit rought, and would like to suggest a little modification that would improve the look of all the README pages

* on github.com
* in your IDE (phpstorm there)

And the good news is ... there is only one file to update :) 

## What it could render

![dark-mode](https://github.com/symfony/symfony/assets/1359581/c15260d6-2408-49ea-af29-eb685bda47b9)

### Github.com

| Before | After |
| - | - |
| ![before-readme](https://github.com/symfony/symfony/assets/1359581/986a7c78-2faa-4510-914a-7c54ea70d5e7) | ![after-readme](https://github.com/symfony/symfony/assets/1359581/54c73788-9bec-4d79-b114-9c3fbf2ad28f) |

### phpstorm

| Before | After |
| - | - |
| ![before-phpstorm](https://github.com/symfony/symfony/assets/1359581/1b53c40d-9da0-4d97-8b51-7f0d52cb5da4) | ![after-phpstorm](https://github.com/symfony/symfony/assets/1359581/80d69227-c7f9-404d-9e5a-a0a51029c276) |

## How can it be done

The good news is that you would just have to update the logo file which is linked in all those README : 

```md
<p align="center"><a href="https://symfony.com" target="_blank">
    <img src="https://symfony.com/logos/symfony_black_02.svg">
</a></p>
```

By adding a couple of lines of CSS in the SVG, the logo can be modified depending on the user dark/light mode

Let's use a simplified SVG code for the Symfony logo 

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

### Solution 1 : Filter Invert

If you want to get a quick win, you can simply invert the image via the invert filter

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <style>
    @media (prefers-color-scheme: dark) { 
      path { filter: invert(1) }
    }
  </style>
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

### Solution 2 : Manual override

Personnaly, i'd rather write things explicetly, so you could do it like that too (or in a dozen of other ways i guess... 😅 )

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <style>
    @media (prefers-color-scheme: dark) { 
      path { fill: #fff; }
      #sf { fill: #000; }
    }
  </style>
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

--- 

What do you think ?

**Comment by GromNaN** [comment]
Looks good. That's awesome if that CSS inside SVG tag works in GitHub, PHPStorm and other IDEs.

**Comment by wouterj** [comment]
Are you sure this works in GitHub README? I've tried something like this before, but GitHub has quite a strict XSS protection algorithm (for good reasons) which basically removed every trick I tried (IIRC, I tried using GitHub's own CSS foreground & background variables, but even that got filtered out).

**Comment by smnandre** [comment]
I just tested it ;) 

It seems to me it works:
* if the image is absolute and exterenal (i tested and you're right: it does not work with github hosted content)
* if the domain is a confirmed domain of the organisation

That's why i made my tests on an organisation repository (poke me on slack i'll share the link)

**Comment by smnandre** [comment]
I mean: all the captures are made "live", there is no photoshop work there.

**Comment by GromNaN** [comment]
@javiereguiluz can you publish this modified svg on symfony.com?

**Comment by javiereguiluz** [comment]
Yes, we've published a new dynamic logo in https://symfony.com/logo that we can use here. Thanks.
