### ISSUE TITLE
Symfony Process Failed While The Script Actually Succeeded

### ISSUE THREAD

**Issue by jiezhangaofl** [symfony/symfony#53164]
### Symfony version(s) affected

5.2.4

### Description

Hello,
I'm using symfony process to run script asynchronously in my micro service environment. I have a deamon script which fetches scheduled jobs from my task manager and run them with symfony process. I keep seeing failed job status in my datadog monitor. But those jobs actually run successfully. I tried to log the exit code and error details, but got nothing meaningful. 
The getErrorOutput method returns nothing and the getExitCode returns -1.

Not all of the jobs run through symfony process are failing. They just fail intermittently.
This is impacting our production system and now I'm stuck on how to fix this issue. Could anyone please help or just give me some hints?

### How to reproduce

Write a daemon php script which pulls a job from another system. Then run this job with Symfony process. something like this
```php
$objProcess = new Process(
  $command_parts,
  $homedir,
  $arg_env_vars,
  null,
  null
);

$objProcess->start();
```
Wait for those jobs to finish by checking the status `if($objProcess->isRunning() != true){...}`.

It's hard to replicate it with my local docker environment. So far I've only seen this on our cloud environment which is running on aws ec2.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by jiezhangaofl** [comment]
Hi @xabbuh , it's hard for me to give the sample application because of two reasons:
1. the app I keep seeing this issue is using a phar file as entrypoint, and that phar file includes a lot of sensitive code that I don't have time to clean and share
2. the issue is super hard to replicate if running with docker on a local computer. so far I've only seen it more often when running on AWS EC2.

But I think I found out why. We are running the process asynchronously. Here's the code snippet for starting the process:
``` 
    $objProcess = new Process(
            $command_parts,
            $homedir,
            $arg_env_vars,
            null,
            null
     );
     $objProcess->start(function ($type, $buffer) use ($jobObj){
            if($type == Process::ERR){
                $jobObj->errorCount++;
            }
            $jobObj->logLine($buffer, $type);
     });
```
We are intermittently checking the status of the job, without a strict or regular schedule because of the code logic. Here's the code for checking status
```
if($objProcess->isRunning() != true){
            if($objProcess->isSuccessful()){
                $jobObj->complete(JobStatus::JOB_COMPLETE);
            } else {
                $jobObj->complete(JobStatus::JOB_FAILED);
            }
        }
```

I noticed that the symfony process is using `proc_get_status` to get process info. And I saw this from php.net

> For clarification, the "exitcode" is only valid the FIRST TIME IT IS CALLED after the process exits.
> 
> If you have a method that polls a spawned process for its status, you *MUST* have that same method capture the exitcode: if the method is called a second time (after realizing the pid is dead) and it hasn't cached that exitcode, it will receive the -1 mentioned.

Here's the [link](https://www.php.net/manual/en/function.proc-get-status.php#92145)

I think it's because we have a delay on the job exited and reading process info, we are not getting the correct exit code.

But in the meantime, we don't want to wait for the asynchronous process to finish as we want to run multiple processes in the background. Do you have any clues on how to avoid this wrong status issue?

**Comment by jiezhangaofl** [comment]
Looks like there's no easy fix to this. I'll just close the issue.
