### ISSUE TITLE
[XLMLINT] Warning: DOMDocument::schemaValidate(): Invalid Schema

### ISSUE THREAD

**Issue by justpilot** [symfony/symfony#53175]
### Symfony version(s) affected

7.0.0

### Description

Executing `composer i` or `symfony console cache:clear` results in an Error.
I have 2 systems with the same project.

1. System:

`xmllint --version`
`xmllint: using libxml version 21004`

Result: No Error

2. System:

`xmllint --version`
`xmllint: using libxml version 21203-GITv2.12.3`

Result: Error

### How to reproduce

`symfony console cache:clear`

```
 // Clearing the cache for the dev environment with debug true                                                          


In XmlDriver.php line 1006:
                                                          
  Warning: DOMDocument::schemaValidate(): Invalid Schema  
                                                         
```

### Additional Context

libxml version 21203-GITv2.12.

**In XmlDriver.php line 1006:**

```
if (! $document->schemaValidate(__DIR__ . '/../../../../../doctrine-mapping.xsd')) {
                throw MappingException::fromLibXmlErrors(libxml_get_errors());
            }
```

`vendor/doctrine/orm/doctrine-mapping.xsd`

**Comment by mbabker** [comment]
See https://github.com/doctrine/orm/issues/11117

**Comment by justpilot** [comment]
> See [doctrine/orm#11117](https://github.com/doctrine/orm/issues/11117)

Thank you and sorry - failed finding existing topic.
This issue can be deleted.
