### ISSUE TITLE
[DIC] Decorator + TaggedLocator does not play well

### ISSUE THREAD

**Issue by jmuxfeldt** [symfony/symfony#53174]
### Symfony version(s) affected

6.4.x

### Description

according to the docs, you can use a serviceLocator to load a workflow using  a taggedlocater.
` #[TaggedLocator('workflow')]`, e.g.
The WorkflowDebugPass.php introduced in 6.4 however prefixes all the workflow keys with 'debug.' when `kernel->isDebug()` and this makes it unwieldy to get a workflow by key.

### How to reproduce

The following class allows me to load a workflow dynamically, without specifically injecting a certain workflow.  It avoids injecting the registry, as recommended in the Symfony docs. This still works in 6.3, but no longer in 6.4.

````php
#WorkflowLoader.php

WARNING: this no longer works as of Symfony 6.4

use Psr\Container\ContainerExceptionInterface;
use Psr\Container\ContainerInterface;
use Psr\Container\NotFoundExceptionInterface;
use Symfony\Component\DependencyInjection\Attribute\TaggedLocator;
use Symfony\Component\Workflow\WorkflowInterface;
use RuntimeException;

class WorkflowLoader
{
    public function __construct(
        #[TaggedLocator('workflow')] private readonly ContainerInterface $serviceLocator
    )
    {
    }

    public function getWorkflow($workflowName): WorkflowInterface
    {
        try {
            if (!$workflow = $this->serviceLocator->get('state_machine.' . $workflowName)) {
                $workflow = $this->serviceLocator->get('workflow.' . $workflowName);
            }
        } catch (NotFoundExceptionInterface|ContainerExceptionInterface $e) {
            throw new RuntimeException("Process Workflow $workflowName could not be loaded. \n" . $e->getMessage());
        }
        return $workflow;
    }
}
````

### Possible Solution

As a workaround, I can test for the environment in my class, but I think the WorkflowDebugPass should not be called automatically, but only by specific configuration. It is also should be documented.

In general, It would be great to be able to lazyload Workflows dynamically. If you don't know which workflow you need in advance, then a service can't know which one to inject.

**Comment by mbabker** [comment]
Do you need something in the concrete Workflow class that isn't available in the WorkflowInterface?  You'd be better off typehinting to the interface instead of a concrete implementation in general, especially as Symfony will decorate a number of services in the dev environment to make debug information available in the profiler (i.e. the serializer, the event dispatcher, workflows as of 6.4, etc.).

**Comment by jmuxfeldt** [comment]
@mbabker Yes, that is true. I should use the interface. But the real problem here is the 'debug.' prefix to  the workflow key, caused by WorkflowDebugPass.php. My current workaround is the following:
````php


use Symfony\Component\HttpKernel\KernelInterface;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\ContainerInterface;
use Psr\Container\NotFoundExceptionInterface;
use RuntimeException;
use Symfony\Component\DependencyInjection\Attribute\TaggedLocator;
use Symfony\Component\Workflow\WorkflowInterface;

class WorkflowLoader
{
    public function __construct(
        private readonly KernelInterface $kernel,
        #[TaggedLocator('workflow')] private readonly ContainerInterface $serviceLocator
    )
    {
    }

    public function getWorkflow($workflowName): WorkflowInterface
    {
        $prefix = '';
        if ($this->kernel->isDebug()) { 
            $prefix = 'debug.';
        }
        try {
            if (!$workflow = $this->serviceLocator->get($prefix . 'state_machine.' . $workflowName)) {
                $workflow = $this->serviceLocator->get($prefix . 'workflow.' . $workflowName);
            }
        } catch (NotFoundExceptionInterface|ContainerExceptionInterface $e) {
            throw new RuntimeException("Process Workflow $workflowName could not be loaded." . PHP_EOL . $e->getMessage());
        }
        return $workflow;
    }
}
````

And I don't really think this is ideal.

**Comment by ghost** [comment]
I have a deja vu there was similar problem with traceable decorator and DI in another component a few months ago. 

@mbabker WorkflowInterface or any other FQCN is just an alias inside the container pointing to the actual service id. This actual service id should always work, no matter how many decorators are applied.

**Comment by jmuxfeldt** [comment]
@javaDeveloperKid   Yes, I agree. I think there is nothing gained by adding the debug prefix. I also think that prefixing with the workflow type is doing things the wrong way around. The type should be suffixed, as it is is also a sub-field of the configuration. See the contortions I need to do in my examples above.  And if the workflows have unique keys anyway, why prefix or suffix them at all?

**Comment by ghost** [comment]
I forgot that when decorating services the id of a decorated service becomes an alias to the id of a decorating service. The tags are moved from the former to the latter. Then TaggedLocator looks for services with `workflow` tag and it finds `debug.xyz` instead of `xyz`. It makes sense but this behaviour also leads to the issue that service locator contains services other than a developer tagged by himself. Maybe service locator should also contain this aliases?

**Comment by jmuxfeldt** [comment]
As of 6.4,
````bash
php bin/console debug:autowiring workflow
````
Adds extra aliases. two for every workflow. e.g.
````bash
 Symfony\Component\Workflow\WorkflowInterface $membershipApplication - target:membership_application - alias:state_machine.membership_application
 Symfony\Component\Workflow\WorkflowInterface $membershipApplicationStateMachine - target:membership_application.state_machine - alias:state_machine.membership_application
 ````
 So it would indeed be great, if the _target_ key would work with the serviceLocator.  Then all the code contortions would be gone.

**Comment by lyrixx** [comment]
cc @nicolas-grekas ; this is common pattern here. The DIC should handle this use case directly, shouldn't ?

**Comment by lyrixx** [comment]
I'm changing the label on this issue. The issue is not related to the Workflow, but with the DIC

**Comment by jmuxfeldt** [comment]
@lyrixx I just update my 6.4, and workarounds are no longer needed. Thanks !
