### ISSUE TITLE
`translation:pull` does not contain `intl-icu` in filename

### ISSUE THREAD

**Issue by ganti** [symfony/symfony#53194]
### Symfony version(s) affected

6.4

### Description

when pulling a translation the written filename does not contain `+intl-icu` in the filename as it is written in the [docs](https://symfony.com/doc/current/reference/formats/message_format.html#using-the-icu-message-format).

### How to reproduce

given the following local translation files
```
/translations/foobar+intl-icu.en.yaml
/translations/foobar+intl-icu.fr.yaml
```

`php bin/console translation:pull --format yaml --as-tree 10 loco` will write this files:

```
/translations/foobar+intl-icu.en.yaml
/translations/foobar.fr.yaml
```

- the english translation file gets updated, 
- the other locales will be written without containing `+intl-icu` in the filename
- the same behaviour can also be found in other formats like `xlf` or `json`

Example:
you may use the example to reproduce https://github.com/ganti/symfony-translation-pull-multiline-example

### Possible Solution

if the main translation contains `+intl-icu` in the filename the others should too.

**Comment by smnandre** [comment]
Did you set the `--intl-icu` option ?

```
php bin/console translation:pull --help
```

**Comment by ganti** [comment]
🙏 yes, it works
