### ISSUE TITLE
[Messenger] Negative publisher confirm swallowed

### ISSUE THREAD

**Issue by Norbomat** [symfony/symfony#53229]
### Symfony version(s) affected

<=7

### Description

For reliable message publishing, RabbitMQ offers the possibility to enable [publisher confirms](https://www.rabbitmq.com/confirms.html#publisher-confirms) on a channel. If enabled, the success of processing a message will be confirmed by the broker. If the broker responds with `ack`, all is fine. In case of receiving `nack` however, the client is expected to re-publish the message.

Unfortunately, a `nack` seems to be swallowed by Messenger:
In [this line](https://github.com/symfony/amqp-messenger/blob/2ee5d2574b3f745078eb3836ec60d1530aac184b/Transport/Connection.php#L348), Messenger waits for the confirm. The [waitForConfirm() method](https://github.com/php-amqp/php-amqp/blob/4a4194300e5c1519b4a23dd33d3b37b9d0d9e7b8/amqp_channel.c#L1312) then invokes the callback for `ack` or `nack`. Both callbacks have been provided [here](https://github.com/symfony/amqp-messenger/blob/2ee5d2574b3f745078eb3836ec60d1530aac184b/Transport/Connection.php#L494). 

As both callbacks just return "false", no further handling of a `nack`-case is done. There's no way for code which sends a message to know if this has been successful or not.

The expectation would be that at least an exception is thrown in that case. An even better implementation would perform some retries before eventually throwing an exception.

### How to reproduce

When a queue is limited and rejects new messages, the publisher is informed by a `nack` response. This behavior could easily be provoked by creating an overflow scenario.

**messenger.yaml**
``` yaml
...
    myTransport:
        dsn: amqp://...
        options:
          confirm_timeout: 3 # enable publisher confirms
```

**Assigning a policy in RabbitMQ:**
Either assign a policy like explained [here](https://www.rabbitmq.com/maxlength.html). Or use the admin frontend, click "Admin/Policies/Add policy" and enter the values 
- Name: SomeName
- Definitions:
  - max-lenght=2
  - overflow=reject-publish 

**Start a SymfonyMessanger consumer**
``` bash
console messenger:consume myTransport
```

**Sending some messages**
``` php
class MyMessage
{
    public function __construct(readonly string $text){}
}

#[AsMessageHandler]
class MyMessageHandler
{
    public function __construct(private readonly LoggerInterface $logger)
    {
    }

    public function __invoke(MyMessage $message): void
    {
        $this->logger->info("Message received: " . $message->text);
    }
}

for ($i = 0; $i < 100; $i++) {
    $this->messageBus->dispatch(new MyMessage("Message Nr. $i"));
}
```

**Result**
-> Only some message are received. The publisher doesn't get any info that it should retry publishing.

**Comment by lermontex** [comment]
I have a similar issue, but I'm using Symfony 7.0 with RabbitMQ 3.12.12

It looks like everything is working fine, but in fact some messages are getting lost during processing

**Comment by kvrushifa** [comment]
@lermontex were you able to solve this problem somehow?

**Comment by lermontex** [comment]
@kvrushifa, no. Looks like this is a `symfony/amqp-messenger` bug, as @Norbomat wrote above
