### ISSUE TITLE
[Routing] Can active forward exception

### ISSUE THREAD

**Issue by ytilotti** [symfony/symfony#53228]
### Description

Why we can't define catch handle on `forward()` call?
I don't know if is a bug or a feature request (I can do the PR), but I don't understand why we can't. A specific reason?

Check if the response of forward is a 500 is a weird solution.
```php
$response = $this->forward('App\Controller\OtherController::fancy');
if (500 !== $response->getStatusCode()) {
    // do something else
}
```

### Example

A  solution is possible on this example.

Add a parameter to `forward()` to do:
```php
public function index($name): Response
{
    try {
        $response = $this->forward('App\Controller\OtherController::fancy', [
            'name'  => $name,
            'color' => 'green',
        ], [], false);
    } catch (\Exception $e) {
        // do something else
    }
    // ... further modify the response or return it directly

    return $response;
}
```

And update function on `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`:
```php
protected function forward(string $controller, array $path = [], array $query = [], $catch = true): Response
{
    $request = $this->container->get('request_stack')->getCurrentRequest();
    $path['_controller'] = $controller;
    $subRequest = $request->duplicate($query, null, $path);

    return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST, $catch);
}
```

**Comment by xabbuh** [comment]
Can you please explain your use case for which handling the exception in the main request is not sufficient?

**Comment by ytilotti** [comment]
> Can you please explain your use case for which handling the exception in the main request is not sufficient?

Sorry @xabbuh, I don't understand your question.
This exemple not working today:
```php
public function index($name): Response
{
    try {
        $response = $this->forward('App\Controller\OtherController::fancy', [
            'name'  => $name,
            'color' => 'green',
        ]);
    } catch (\Exception $e) {
        // do something else
    }
    // ... further modify the response or return it directly

    return $response;
}
```

**Comment by xabbuh** [comment]
The question is what is the reason that you have to implement exception handling in a controller that performs a sub-request?

**Comment by ytilotti** [comment]
The question is more, why we can do it with `handle()` but not with `forward()`?

In my case, it's for use with Turbo. I set up modal with my listings and with add buttons (including prototype form) to work with collectionType. But the context is not interesting in our case.

**Comment by xabbuh** [comment]
`handle()` is used for example inside the `ErrorListener` to generate the error response. This listener is triggered when an exception has been thrown. If we would catch exceptions again when rendering the error response yields an exception would create an infinite loop.

Without a clear and common use case that justifies adding this flag to `forward()` too my vote would be 👎 to add it.

**Comment by ytilotti** [comment]
@xabbuh no problem, but I don't understand the principe of use case (in this case).
`forward()` is a shortcut to call `handle()` but can't set all the parameters of `handle()`. It's weird, regardless of use.

**Comment by xabbuh** [comment]
`forward()` is a shortcut for a subset of the a feature provided by HttpKernel that is useful in a controller. So far I doubt that performing sub-requests with a different value for the `$catch` argument is commonly needed. We do not add switches just for the sake of it if there is no need for it.

**Comment by ytilotti** [comment]
Conclusion, the best way for you is this code?
```php
$response = $this->forward('App\Controller\OtherController::fancy');
if (500 !== $response->getStatusCode()) {
    // do something else
}
```

**Comment by xabbuh** [comment]
Without knowing more about your use case I would probably re-implement the `forward()` method in your own code somewhere with the changes you need.

**Comment by xabbuh** [comment]
closing as explained, thank you for understanding
