### ISSUE TITLE
[DoctrineBridge] MapEntity with multiple results

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#53236]
### Symfony version(s) affected

7.0.1

### Description

I use the following code but I meet an error

```php
#[Route('/product/{id}/comments')]
public function show(
    Product $product,
    #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
    iterable $comments
): Response {
}
```

Error is:
`Controller "App\Controller\ProductController" requires that you provide a value for the "$comments" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.`

### How to reproduce

```php
#[Route('/product/{id}/comments')]
public function show(
    Product $product,
    #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
    iterable $comments
): Response {
}
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by seb-jean** [comment]
@xabbuh Yes: https://github.com/symfony/demo/pull/1483

**Comment by xabbuh** [comment]
Hm, there are indeed several issues:

* the `class` option for the `MapEntity` attribute is missing
* the expression syntax is invalid (it would actually have to look like this: `repository.findBy({"author": user}, {"publishedAt": "DESC"})`)
* then, the `user` variable is not available inside the expression

Finally, I am also not sure that `MapEntity` should actually map to a collection of entities. Has this ever been a goal of the attribute?

**Comment by derrabus** [comment]
> Finally, I am also not sure that `MapEntity` should actually map to a collection of entities. Has this ever been a goal of the attribute?

No.

**Comment by seb-jean** [comment]
So the documentation is wrong? It's on the page https://symfony.com/doc/current/doctrine.html

![Capture d'écran 2023-12-30 183419](https://github.com/symfony/symfony/assets/12116264/2ccf5a9c-36ae-4bd9-919b-745a2a5fc09f)

It's this Pull Request: https://github.com/symfony/symfony-docs/pull/18991

**Comment by Jean-Beru** [comment]
Yes. The code given by the documentation throws an exception since the object syntax must use `{ ... }` and not `[ ... ]`. After that an other exception is thrown explaining that the expression must return a `?object`.
```
Symfony\Bridge\Doctrine\ArgumentResolver\EntityValueResolver::findViaExpression(): Return value must be of type ?object, array returned
```

I submitted a fix here: https://github.com/symfony/symfony-docs/pull/19367.

**Comment by seb-jean** [comment]
Thanks 👍

**Comment by mindaugasvcs** [comment]
> ### Symfony version(s) affected
> 7.0.1
> 
> ### Description
> I use the following code but I meet an error
> 
> ```
> #[Route('/product/{id}/comments')]
> public function show(
>     Product $product,
>     #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
>     iterable $comments
> ): Response {
> }
> ```
> 
> Error is: `Controller "App\Controller\ProductController" requires that you provide a value for the "$comments" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.`
> 
> ### How to reproduce
> ```
> #[Route('/product/{id}/comments')]
> public function show(
>     Product $product,
>     #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
>     iterable $comments
> ): Response {
> }
> ```
> 
> ### Possible Solution
> _No response_
> 
> ### Additional Context
> _No response_

This works for me:

#[Route('/product/{id}/comments')]
public function show(
Product $product,
#[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10))', class: 'App\Entity\Comment')]
iterable $comments
): Response {
}

**Comment by seb-jean** [comment]
> Hm, there are indeed several issues:
> 
> * the `class` option for the `MapEntity` attribute is missing
> * the expression syntax is invalid (it would actually have to look like this: `repository.findBy({"author": user}, {"publishedAt": "DESC"})`)
> * then, the `user` variable is not available inside the expression
> 
> Finally, I am also not sure that `MapEntity` should actually map to a collection of entities. Has this ever been a goal of the attribute?

But then, how could I get the current user in a `MapEntity` attribute?
