### ISSUE TITLE
missing folders during symfony bin installation

### ISSUE THREAD

**Issue by rudak** [symfony/symfony#53257]
### Symfony version(s) affected

7.0

### Description

hello, i'm trying to install a project following the 7.0 docs but some folders are missing, and not just any folders, `public` and `var` are missing!
![image](https://github.com/symfony/symfony/assets/604478/6e0b56b3-fddc-4a44-991c-f48361e14394)

Here's what I'm doing and the result.
![image](https://github.com/symfony/symfony-docs/assets/604478/4eaf2b49-5de7-495f-8f14-7a1cd4593fc6)
here's my environment if it helps you find a lead
![image](https://github.com/symfony/symfony-docs/assets/604478/a9855ce3-97fe-4b6e-8543-f4eecae0b94a)

### How to reproduce

the command to use is here https://symfony.com/doc/current/setup.html#symfony-lts-versions  
`symfony new my_project_directory --version="7.0.*" --webapp`

**Comment by derrabus** [comment]
Works for me… 🤷🏻‍♂️ 

<img width="464" alt="Bildschirmfoto 2023-12-28 um 15 09 14" src="https://github.com/symfony/symfony/assets/1506493/0f2b9193-a354-4d8c-a667-a162ca142b43">

**Comment by N445** [comment]
Same issue here

**Comment by smnandre** [comment]
Symfony Cli 5.7.7, could not reproduce, all working here. 

Just to be exhaustive, it seems you're also missing folder "assets" and file "importmap.php"

**Comment by xabbuh** [comment]
Which version of the Symfony CLI do you use?

**Comment by rudak** [comment]
It is writen on the capture image : `5.7.6`

**Comment by xabbuh** [comment]
Do you observe the same behaviour with 5.7.7?

**Comment by N445** [comment]
> Do you observe the same behaviour with 5.7.7?

yes it's working for me after update 5.7.6 to 5.7.7

**Comment by rudak** [comment]
Yes ! It works with 5.7.7 !!
![image](https://github.com/symfony/symfony/assets/604478/498efebb-8e68-403b-8d29-5e725d017d3e)

ty @N445

**Comment by acirulis** [comment]
With fresh install of Symfony Cli 5.7.7 (on Windows11/WSL2 Ubuntu) - src and other folders missing: 
available folders after install: `bin  composer.json  composer.lock  config  symfony.lock  vendor`

All good with `composer create-project symfony/skeleton:"7.0.*" my_project_directory`

**Comment by xabbuh** [comment]
If you experience any more issues with the Symfony CLI, please report them over in its dedicated repository: https://github.com/symfony-cli/symfony-cli
