### ISSUE TITLE
[Form] DateType converts invalid string to a -61410510000

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#53258]
### Symfony version(s) affected

5.4.*

### Description

Suppose, we have a form like this:
```php
            ->add('started_at', DateType::class, [
                'input' => 'timestamp',
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'html5' => false,
                'constraints' => [
                    new NotBlank(),
                ],
            ])
```

So, the valid input will look like this: `26/12/2023`. But if we try to pass `26/12/23` (looks pretty similar, everyone could try to pass this), the value will be transformed to `-61410510000` and will cause an unexcepted behavior.

<img width="800" alt="Снимок экрана 2023-12-28 в 3 15 47 PM" src="https://github.com/symfony/symfony/assets/7838144/d6c1629d-5b43-42db-8d93-bc71a1cd16d7">
<img width="942" alt="Снимок экрана 2023-12-28 в 3 16 45 PM" src="https://github.com/symfony/symfony/assets/7838144/3d64fdb7-9477-4dc6-b335-81d1d29f46be">

For sure I can add a regexp constraint, but it looks like is expected behavior by default without explicitly adding it.

Context: https://github.com/symfony/symfony/blob/v5.4.21/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L123

### How to reproduce

Pass `26/12/23` as a value for `DateType` form type.

**Comment by xabbuh** [comment]
23 is in fact a valid year. What however is an issue here is that `-61410510000` is less than `PHP_INT_MIN` and thus converted to a float by PHP. I guess what I would do in your case is a adding a `GreaterThan` constraint to ensure that a user cannot submit a date before a certain point in time.

Nonetheless, I am going to close here as the behaviour looks correct to me as explained. Thank you for understanding.

**Comment by Aliance** [comment]
Do not still sure, that the behaviour is correct. I as a framework user expect to get validation according to the format I configure to `DateType`. Adding extra constraints seems like something redundant for me.

> 23 is in fact a valid year. 

For sure it is, but for `yy` pattern, not for `yyyy`.

I did not expect to get any number below zero, by the way. I expect to get validation error, because the format passed was not expected.

**Comment by Aliance** [comment]
@xabbuh can you help me to understand again your point of view? I still think this is a relevant bug and not expected behavior.
