### ISSUE TITLE
Slack invite link has expired

### ISSUE THREAD

**Issue by mathroc** [symfony/symfony#53275]
### Symfony version(s) affected

0.0.0

### Description

On this page : https://symfony.com/community

### How to reproduce

.

### Additional Context

sorry, I didn't know where I should report that so I hijacked the bug report

**Comment by chalasr** [comment]
Telling @javiereguiluz on slack is usually enough :) Thanks for the report!

**Comment by javiereguiluz** [comment]
Thanks for reporting this. The link has just been updated.
