### ISSUE TITLE
[Messenger] Message loss on RejectRedeliveredMessageException

### ISSUE THREAD

**Issue by beermeat** [symfony/symfony#53311]
### Symfony version(s) affected

6.4.0

### Description

As described in `RejectRedeliveredMessageMiddleware` - `RejectRedeliveredMessageException` should trigger the retry logic:

```php
throw new RejectRedeliveredMessageException('Redelivered message from AMQP detected that will be rejected and trigger the retry logic.');
```

But after `RejectRedeliveredMessageException` started implement `UnrecoverableExceptionInterface` (https://github.com/symfony/symfony/pull/51756) no retry logic will occur and the message just will be removed from the queue (see `SendFailedMessageForRetryListener::shouldRetry`)

@nikophil 

> when a RejectRedeliveredMessageException is thrown once, it is actually retried because it does not implement UnrecoverableExceptionInterface but we know it will always because the stamp AmqpReceivedStamp will always be there

No, because `AmqpReceivedStamp` implements `NonSendableStampInterface`. And retry logic will publish new message to a queue (with delay), so second time there is will new instance AmqpReceivedStamp without redelivery flag.

### How to reproduce

no reproduce required

### Possible Solution

Rollback https://github.com/symfony/symfony/pull/51756

**Comment by beermeat** [comment]
Up

**Comment by lermontex** [comment]
It seems related #52903

**Comment by rela589n** [comment]
I've stumbled myself on this issue as well. Since `RejectRedeliveredMessageException` implements `UnrecoverableExceptionInterface`, method `SendFailedMessageForRetryListener::shouldRetry()` always returns `false`.

![image](https://github.com/symfony/symfony/assets/41589422/78943add-32aa-4e19-b9a3-427be70fbabd)
