### ISSUE TITLE
[uid] Please add ::toString() method to Symfony/Uid

### ISSUE THREAD

**Issue by sofigio** [symfony/symfony#53333]
### Description

Just like the Ramsey class, we just want to print that uid as a string. 
Currently, we must use `::toRfc4122()` which every time makes me wonder "what is rfc 4122? I have to google that" and I waste time because I'm not sure it's the proper method, or as an alternative:
- `->__toString()`
- `(string) cast`

which are aesthetically unpleasing. It would be a quality of life improvement to have a simple ->toString() method."

**Comment by xabbuh** [comment]
~~The `AbstractUid` class implements `__toString()`. Isn’t that what you are looking for?~~

never mind, I misread the issue

**Comment by yceruto** [comment]
Completely agree with you that `->toString()` is better than `->__toString()`, but that would mean having two methods with the same code just for aesthetics, which feels like a burden from the maintenance point of view.

---
Another alternative, as long as you don't `declare(strict_types=1)`, is that you can use the Uid instance as a string everywhere (directly).

**Comment by wouterj** [comment]
There are multiple ways you can visualize the UIDs implemented by the component as string. E.g. the `__toString()` method does not return RFC 4122 for ULIDs if I'm correct.

If you care about it being a string, it's probably also better to be explicit about which string format you want. If you don't care about its string visualization, but you just pass it to another domain expecting a string ID, you can either rely on PHP's type casting or use explicit casting using `(string) $uid`.

**Comment by fancyweb** [comment]
I think having `toString()` returning the canonical format makes sense DXwise.
The situation is not 100% comparable but we already have the 2 methods in `AbstractString` :man_shrugging:
