### ISSUE TITLE
[Serializer] Error when trying to deserialize an object with a constructor using a variadic parameter

### ISSUE THREAD

**Issue by thijsBreker** [symfony/symfony#53354]
### Symfony version(s) affected

6.4.2 (Other versions most likely as well)

### Description

For some reason the serializer doesn't seem to like variadic arguments in the constructor

### How to reproduce

When deserializing a json object like this
```json
{
    "requiredParameter": "required",
    "optionalParameter": "optional",
    "variadicParameter": [
        {"param": 1},
        {"param": 2}
    ]
}
```

into a PHP class like this
```php
class ChildExample {
    public function __construct(
        private int $param,
    ) {}
}

class Example {
    private array $variadicProperty;

    public function __construct(
        private string $requiredParameter,
        private string $optionalParameter = '',
        SomeClass ...$variadicParameter,
    ) {
        $this->variadicProperty = $variadicParameter;
    }
}
```
I get the PHP error `Error : Cannot use positional argument after named argument` on line 429 of `AbstractNormalizer.php`.

### Possible Solution

When I wrap the `$params` variable in an `array_values()` call the problem goes away. I'll try to create a pull request with my fix later.

**Comment by webmake** [comment]
Error occurs with 5.4.34 as well, after bumping from 5.4.31, so not sure which version broke exactly yet https://github.com/symfony/serializer/compare/v5.4.31...v5.4.34

**Comment by xabbuh** [comment]
@webmake Can you confirm that #53361 fixes this?

**Comment by webmake** [comment]
Yes, it looks like patch would help
