### ISSUE TITLE
[Translation] Translation Debug command doesn't work correctly with domain as constant

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#53356]
### Symfony version(s) affected

all

### Description

Currently both
```php
use App\Const\Domain;
$this->translator->trans('foo', Domain::CUSTOM);
```
in php and
```twig
{{ 'foo'|trans({}, constant('App\\Constant\\Domain::CUSTOM')) }};
```
in twig is misunderstood by translation extractor.

The first one thinks the domain is `'messages'`, the second one `'_undefined'`.

It would be nice to correctly support the domain.
If it's really not possible, it seems better to me to have `'_undefined'` in both case.

### How to reproduce

Running
```bash
bin/console debug:translation
```
with the previous code.

### Possible Solution

For the AbstractVisitor, I tried doing something with
```php
if ($node instanceof Node\Expr\ClassConstFetch) {
            try {
                $reflection = new \ReflectionClass($node->class->toString());
                $constant = $reflection->getReflectionConstant($node->name->toString());
                if (false !== $constant && \is_string($constant->getValue())) {
                    return $constant->getValue();
                }
            } catch (\ReflectionException) {}
        }
```
but this works only with full FQCN, and not when it's imported/aliased at the start of the file...

For twig, I tried https://github.com/symfony/symfony/pull/53357

**Comment by smnandre** [comment]
> ```
> {{ 'foo'|trans({}, constant('App\Constant\Domain::CUSTOM')) }};
> ```

Probably a typo but just to be sure, you used double backslashes instead of simple ones ' in your real code ? 

```
{{ 'foo'|trans({}, constant('App\\Constant\\Domain::CUSTOM')) }};
```

**Comment by VincentLanglet** [comment]
> > ```
> > {{ 'foo'|trans({}, constant('App\Constant\Domain::CUSTOM')) }};
> > ```
> 
> Probably a typo but just to be sure, you used double backslashes instead of simple ones ' in your real code ?
> 
> ```
> {{ 'foo'|trans({}, constant('App\\Constant\\Domain::CUSTOM')) }};
> ```

Yes indeed it was a typo, I edited the issue.

**Comment by VincentLanglet** [comment]
@welcoMattic you introduced the PhpAstExtractor in https://github.com/symfony/symfony/pull/46161
maybe you'll know how to support the syntax:
```
use App\Const\Domain;
$this->translator->trans('foo', Domain::CUSTOM);
```
?

**Comment by welcoMattic** [comment]
I will take a look on it next week. In the mean time, if you find a way to support it with FQCN, feel free to open a PR.

**Comment by VincentLanglet** [comment]
> I will take a look on it next week. In the mean time, if you find a way to support it with FQCN, feel free to open a PR.

I think I found a solution @welcoMattic ; by running the NameResolver before (I found this advice here https://github.com/nikic/PHP-Parser/issues/188#issuecomment-86158128) I get the full FQCN , cf https://github.com/symfony/symfony/pull/53624
