### ISSUE TITLE
[Serializer] Allow the mapped object in discriminator mapping to be other type than string.

### ISSUE THREAD

**Issue by pavemolc-circunomics** [symfony/symfony#53387]
### Description

We have an interface with a type-based discriminator map. In this implementation the types have integer types. Discriminator itself works correctly and in the output we receive the objects based on the discriminator mapping. What happens though is that the `type` property gets converted to string at the time of serialization. And after the object is serialized to JSON string - we receive:
`{"type":"1"}` instead of `{"type":1}`,
which is not correct.

The conversion itself happens in the serializer: `ClassDiscriminatorMapping::getMappedObjectType()`. The return type is `?string`, so integer values get casted to string.

Would it be possible to permit other types?

### Example

```
#[DiscriminatorMap(typeProperty: 'type', mapping: [
    self::TYPE_A => TypeA::class,
    self::TYPE_B => TypeB::class,
])]
interface ExampleInterface
{
    public const TYPE_A = 1;
    public const TYPE_B = 2;

    public function getType(): int;
}
```

**Comment by mtarld** [comment]
Hey @pavemolc-circunomics, thanks for your report!

Indeed, with the actual code, only strings are properly handled.

But, handling other types will require to change interfaces, and this will imply a lot of work because of the BC promise.
Therefore, my question is: does it really worth it? I mean, is the lack of that feature blocking you somehow?

Anyway, if we chose to keep it like that, I think that it could be great to specify in the documentation and in the code documentation that only strings are allowed as mapping types.

**Comment by pavemolc-circunomics** [comment]
Not exactly. The documentation though doesn't say anything about the type requirements, neither there were any exceptions, so I had to go through debugging session to understand the problem.

**Comment by mtarld** [comment]
I totally agree that it shouldn't fail silently.

At least, we must add a note about that in the documentation.

We could as well throw an exception in `getMappedObjectType` if the type is not a string nor a stringable to make sure that we don't do any implicit cast, but I'm afraid that other users are already relying on such implicit cast.

**Comment by pavemolc-circunomics** [comment]
Yes, it is understandable. The documentation update would give at least some clarification to this subject. Well, anyway - I wanted to create this issue, in case people in the future will have the same issue. So thanks!

**Comment by javiereguiluz** [comment]
Let's close this one as "fixed" because we've added a note about this in the docs (https://github.com/symfony/symfony-docs/pull/19426). Thanks.
