### ISSUE TITLE
symfony/routing: Update 6.4.0 to 7.0.0 "Make sure there is a loader supporting the "annotation" type."

### ISSUE THREAD

**Issue by Adi-18** [symfony/symfony#53426]
### Symfony version(s) affected

7.0.0

### Description

I updatet Symfony from 6.4.0 to 7.0.0 and use now attribute for controller.
Update like described here https://itnext.io/upgrade-to-symfony-v7-e9bc252b47ea

But I still get error while **composer install** "Make sure there is a loader supporting the "annotation" type."

### How to reproduce

1.  Project updated to 7.0.0
2. Remove config/routes/annotations.yaml.
3. Create a new file config/routes/attributes.yaml, fill with content.
4. Changed route as annotation to attribute
5. Run composer install

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Adi-18** [comment]
While reduce to basic example, I found the mistake in 3th party plugin. Sorry and thank you.

**Comment by Schrank** [comment]
@Adi-18 Just in case you remember - I have the same problem and would be great to hear what the mistake was :D

**Comment by Schrank** [comment]
While searching for an answer, found the bug myself 😂

Before:

    <import resource="../../../Controller" type="annotation"/>

After:

    <import resource="../../../Controller" type="attribute"/>

Although it were already attributes... Seems like I were dumb during last update.

**Comment by sellrock-de** [comment]
Deleting the old annotation folder fixed it for me

**Comment by annemiekebuijs** [comment]
I removed annotation.yaml
and in routes.yaml:

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

```
