### ISSUE TITLE
[Serializer] Denormalizer incorrectly handles objects with private properties

### ISSUE THREAD

**Issue by StriplThund** [symfony/symfony#53439]
### Symfony version(s) affected

7.0.2

### Description

Hi.

I am deserialising associative array with entity in its key into another entity. When all entity properties are marked as `private`, deserializer creates uninitialized copy of my nested entity.

Consider this code:

```
// OK
$res = $this->denormalizer->denormalize([
    'test' => 'i am test',
    'anotherTest' => [
        'nickname' => 'sdf'
    ]
], Test::class);

// NOT OK, private property
$initializedTest = new AnotherTest();
$initializedTest->setNickname('sdf');

$res1 = $this->denormalizer->denormalize([
    'test' => 'i am test',
    'anotherTest' => $initializedTest
], Test::class);

// OK
$initializedTest = new AnotherTestPublic();
$initializedTest->setNickname('public test');

$res2 = $this->denormalizer->denormalize([
    'test' => 'i am test',
    'anotherTest' => $initializedTest
], Test::class);
```

AnotherTest (this will not work):

```
class AnotherTest
{
    private ?string $nickname = null;

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(?string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }
}
```

AnotherTestPublic (this will work as expected):

```
class AnotherTestPublic
{
    public ?string $nickname = null;

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(?string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }
}
```

will give this result:

<img width="480" alt="image" src="https://github.com/symfony/symfony/assets/133571729/7150340f-528f-4051-b377-35496f5e14fa">

I tried GetSetMethodNormalizer, tried without it, tried ObjectNormalizer; tried adding Serializer\Groups & context to my deserialize without success.

### How to reproduce

https://github.com/StriplThund/symfony-denormalizer-bug

run `php bin/console app:test`

### Possible Solution

1) Expose all entity properties as public, which i can't accept as solution :(
2) Create custom denormalizer, call setters manually

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by StriplThund** [comment]
> Can you create a small example application that allows to reproduce your issue?

Hi, there is an example app in initial issue

How to reproduce
https://github.com/StriplThund/symfony-denormalizer-bug
run php bin/console app:test

**Comment by xabbuh** [comment]
ah, sorry, somehow missed that

**Comment by xabbuh** [comment]
What I don't understand in your second and third example: Why do you pass an object to `denormalize()` (with `initializedTest`)? `denormalize()` expects a (nested) array but not objects.

**Comment by StriplThund** [comment]
> What I don't understand in your second and third example: Why do you pass an object to `denormalize()` (with `initializedTest`)? `denormalize()` expects a (nested) array but not objects.

Hi. I use MapRequestPayload attribute & custom denormalizer logic to map entities coming from request.
Lets say i have this entity:

```php
#[ORM\Entity]
class Message
{
  #[ORM\Column]
  private User $user;

  #[ORM\Column]
  private string $text;
}
```

And i want to map user from this request:

```json
{
  "user": 1,
  "text": "hi!"
}
```

Coming from this controller:

```php
#[Route(...)]
sendMessage(
  #[MapRequestPayload] Message $message
) {
  dd($message->getUser());
}
```

Custom denormalizer:

```php
class MessageDenormalizer implements DenormalizerInterface
{
    public function __construct(
        #[Autowire(service: 'serializer.normalizer.object')]
        private readonly NormalizerInterface & DenormalizerInterface $normalizer,
    private readonly UserRepository $userRepository
    ) {
    }

    public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
    {
        return $type === Message::class;
    }

    public function denormalize(mixed $data, string $type, string $format = null, array $context = []): mixed
    {
       $data['user'] = $this->userRepository->find($data['user']);

        return $this->normalizer->denormalize($data, $type, $format, $context);
    }

    public function getSupportedTypes(?string $format): array
    {
        return [
            'object' => true
        ];
    }
}
```

So i fill user with User entity instead of int, and give modified data to denormalizer. I expect that denormalizer would not denormalize User entity again.

**Comment by mtarld** [comment]
I agree with @xabbuh here, the denormalization expects **normalized** data, which is for instance a (nested) arrays but not objects. IMHO, this is not a Serializer issue.

Instead, you could try to implement the following denormalizer:
```php
class MessageDenormalizer implements DenormalizerInterface
{
  public function __construct(
    #[Autowire(service: 'serializer.normalizer.object')]
    private readonly NormalizerInterface & DenormalizerInterface $normalizer,
    private readonly UserRepository $userRepository
  ) {
  }

  public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
  {
        return $type === Message::class;
  }

  public function denormalize(mixed $data, string $type, string $format = null, array $context = []): mixed
  {
    // this is the easiest way, but feels like going back and forth
    $user = $this->userRepository->find($data['user']);
    $data['user'] = $this->normalizer->normalize($user, $format, $context);

    // you can as well retrieve an array directly from doctrine
    $data['user'] = $this->userRepository->createQueryBuilder('u')
      ->andWhere('u.id = :id')
      ->setParameter('id', $data['user'])
      ->getQuery()
      ->getArrayResult()[0] ?? null;

    return $this->normalizer->denormalize($data, $type, $format, $context);
  }

  public function getSupportedTypes(?string $format): array
  {
    return [
        Message::class => true
    ];
  }
}
```

**Comment by xabbuh** [comment]
Closing here as this is indeed related to how the normalizer is used. Please use one of the [support channels](https://symfony.com/support) if you need more help. Thank you for understanding.
