### ISSUE TITLE
[Dotenv] `getenv` return false instead of the value in the file .env

### ISSUE THREAD

**Issue by makraz** [symfony/symfony#53461]
### Symfony version(s) affected

6.4.2

### Description

after migrating a Symfony project from 6.3.* to 6.4.2 I discovered that the function `getenv` always return `false` instead of the value in the file .env
also, I was able to have the same behavior with a new project (Symfony 6.4.2)

### How to reproduce

Create a new project Symfony 6.4.2
create a function in a controller that call `dd(getenv('APP_ENV'));` for example 
Observe the results (screenshot)
![image](https://github.com/symfony/symfony/assets/19323431/c2e6122c-f23f-4331-85c7-c57ecb71921a)

### Additional Context

tested in below PHP versions:

PHP 8.3.1 (cli) (built: Dec 20 2023 12:44:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.1, Copyright (c), by Zend Technologies

---- 

/usr/src/app # php --version
Cannot load Xdebug - it was already loaded
PHP 8.2.7 (cli) (built: Jun 15 2023 01:00:47) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

**Comment by stof** [comment]
See https://github.com/symfony/symfony/blob/9afd335a06286e5e2c56b746b39d001061810f92/src/Symfony/Component/Dotenv/Dotenv.php#L56-L68

**Comment by xabbuh** [comment]
closing as explained

**Comment by makraz** [comment]
thank you @stof, my question is that the change was in the version [5.0.0](https://github.com/symfony/symfony/blob/9afd335a06286e5e2c56b746b39d001061810f92/src/Symfony/Component/Dotenv/CHANGELOG.md#500), however, we didn't observe this behavior in Symfony 6.3, so I'm wondering if I've missed something or if I still don't fully understand it.
if the change was introduced in Symfony 6.4., wouldn't it be considered a BC breaking change? If so, wouldn't it have been more appropriate to include it in Symfony 7. instead of 6.4?"

thank you

CC: @derrabus @xabbuh

**Comment by derrabus** [comment]
The behavior change happened with #31957 in 5.0.0.

Can you produce a reproducer app for your issue, where we can observe the change of behavior you've described?

**Comment by xabbuh** [comment]
@makraz Did you by chance also update the recipes so that you now have other bootstrapping code in the front controller than you had before?

**Comment by makraz** [comment]
Yes, I updated the recipes, and all looks good in this part. I will share a reproducer app for the issue with more context 👌🏻

**Comment by xabbuh** [comment]
Can you share how your `index.php` file looked before you updated and how it is now?

**Comment by makraz** [comment]
Before (Symfony 6.3.2)

```
<?php

use App\Kernel;
use Symfony\Component\ErrorHandler\Debug;
use Symfony\Component\HttpFoundation\Request;

require dirname(__DIR__).'/config/bootstrap.php';

if ($_SERVER['APP_DEBUG']) {
    umask(0000);

    Debug::enable();
}

if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_PORT | Request::HEADER_X_FORWARDED_PROTO);
}

if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? false) {
    Request::setTrustedHosts([$trustedHosts]);
}

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```

Now (Symfony 6.4.2)
```
<?php

use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```

**Comment by nicolas-grekas** [comment]
That's why: recipes are opt-in piece of code that are on your side of responsibility: you don't have to adopt their updates, and adopting them means possibly changing some behavior (as in: reconfiguring some defaults of your app).
Closing therefor.

**Comment by makraz** [comment]
thank you all 🙏🏼 
I'm guessing that the last time we updated Symfony to 5.X or 6.X, we didn't update the recipes :sweat_smile:, but now I updated them too.

Before:

```
"symfony/framework-bundle": {
        "version": "4.4",
```

After:
```
    "symfony/framework-bundle": {
        "version": "6.4",
```
