### ISSUE TITLE
Create a common interface for Uuid classes

### ISSUE THREAD

**Issue by eerison** [symfony/symfony#53471]
### Description

Hello guys I was wondering if doens't make sense we create a CommonInterface for Uuid classes

### Example

For example

```php
interface UuidInterface
{
    public function generate(): string;
}
```

```php
interface UuidTimeBasedInterface
{
    public function generate(DatetimeInterface $time): string;
}
```

this way I could depends/inject of one of those interfaces and switch between Uuid versions, what do you think?

Note: maybe add these Interfaces on symfony contracts? then I could use in third part libs, what do you think?

**Comment by stof** [comment]
What would be the implementation of this interface ? The Uuid class cannot implement your suggested UuidInterface (meaning the suggested name is a total no-go IMO by being too confusing) given that a UUID instance is a value object representing the *result* of generating it.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/issues/51820

**Comment by stof** [comment]
@nicolas-grekas the common interface suggested here is not the one suggested in this old issue (as it is an interface that looks more like a factory)

**Comment by eerison** [comment]
for example

```php
class UuidV7TimeBased extends Uuid implements TimeBasedUidInterface, UuidTimeBasedInterface
{
    public static function generate(\DateTimeInterface $time): string
    {
        if (0 > $time = $time->format('Uv')) {
            throw new \InvalidArgumentException('The timestamp must be positive.');
        }
        
        // ...
    }
}

class UuidV7 extends Uuid implements TimeBasedUidInterface, UuidInterface
{
    public static function generate(): string
    {
        $time = microtime(false);
        $time = substr($time, 11).substr($time, 2, 3);

       //should be good have this injected, but as I can the usage of Uuid are with static methods.
        return UuidV7TimeBased::generate($time);
    }
}
```

```php
class MyService
{
    __construct(UuidInterface $uuid)
}
```

I was thinking something like this ☝🏼

**Comment by stof** [comment]
@eerison your snippet contains static methods (unlike your suggested interface) and injecting an instance would still require you to generate a uuid to inject it, which does not make sense.

**Comment by eerison** [comment]
> @eerison your snippet contains static methods (unlike your suggested interface) and injecting an instance would still require you to generate a uuid to inject it, which does not make sense.

Yeah that is true, we are injecting the UuidFactory and not the Uuid it self.

Well if I think something different I can reopen this issue ;)
