### ISSUE TITLE
[Form] Issue with some code in `MoneyType`

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#53488]
### Symfony version(s) affected

7.1

### Description

We're trying to document #51884 but we're having some problems when trying to understand this code:

https://github.com/garak/symfony/blob/881174157bc4a57863280d9033b416101725acb2/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php#L91-L93

None of us understands it ... and in the code review process there were also some doubts related to it.

So, please double check if this code is correct ... if it is, please explain it to us so we can document it. Thanks!

**Comment by stof** [comment]
When setting the model_type to integer, it means you don't want to store the money amount as a float but as an integer representing a number of a fraction of the currency. This `divisor` will be the division factor that should be applied on display.
For instance, a common setup when using Euros is to store amount in cents, which would imply a divisor of `100`. But some use cases might want to use a different division of 1€ as their base unit for the integer storage (for instance, in France, gasoline prices are generally given with 3 decimals, not 2, so cents would not be the base unit for that use case)

**Comment by javiereguiluz** [comment]
Yes. But as you said, there are many possible use cases so ... why crash the application when you store money as an integer and the divisor is `1` ?

```php
if ('integer' === $value && 1 === $options['divisor']) {
    throw new LogicException('When the "model_type" option is set to "integer", the "divisor" option should not be set to "1".');
}
```

An application could want to store the money as an integer and precisely use `1` as a divisor to not have a divisor. It's not the most common use case, but this Symfony restriction looks arbitrary to me.

**Comment by sstok** [comment]
`5 / 1` = 5, so it wouldn't make sense to devise by 1 (so it's properly a bug when used). Or 0 💀

**Comment by mdoutreluingne** [comment]
> `5 / 1` = 5, so it wouldn't make sense to devise by 1 (so it's properly a bug when used). Or 0 💀

I agree it doesn't make sense, but if the user wants to set `1` too bad for him, that shouldn't raise an exception. 

I'd like to point out that the default value for the `divisor` is `1`, so if the user wants to set the `model_type` option to an `integer` value, he will also have to modify the `divisor`, otherwise an exception will be thrown...

This Symfony restriction also seems arbitrary to me.

**Comment by yceruto** [comment]
The exception was suggested during implementation because the model_type = integer will work only when the divisor is different from 1. Not setting it properly will cause confusion for developers by receiving a float (instead of an integer as configured). Remember that there is a `scale` option, which is involved in the reverse transformation too, meaning you can end up with a float number even if the `divisor` is 1.

We definitely need to recheck this feature again; it's not completely clear on my side.

Perhaps @garak can enlighten us about this topic. 🙏

**Comment by teamflp** [comment]
Hello,
I have reviewed the fragment of code in `MoneyType` that you mentioned and would like to offer some clarifications.

```php
/**
 * Configures a view transformer for the monetary form field type.
 *
 * The MoneyToLocalizedStringTransformer is added to ensure precise and localized handling
 * of monetary values in forms. This transformer plays a crucial role in converting data
 * between the model (numeric) and the view (localized format).
 *
 * Parameters of the transformer:
 * - 'scale': The number of digits after the decimal point for monetary values.
 * - 'grouping': If enabled, applies thousand separators in the localized format.
 * - 'rounding_mode': Determines the rounding method for monetary values.
 * - 'divisor': A conversion factor to adjust values between storage and display.
 *   For example, a 'divisor' of 100 converts stored values from cents to euros.
 * - The locale is set to 'en' if the 'html5' option is enabled, to comply with
 *   the standard format for number types in HTML5 form elements.
 * - 'model_type': Indicates the data type in the model, such as 'float' or 'integer'.
 *
 * This transformer is essential for form fields dealing with monetary amounts,
 * ensuring both a user-friendly presentation and reliable conversion for server-side data processing.
 */
$builder
    ->addViewTransformer(new MoneyToLocalizedStringTransformer(
        $options['scale'],
        $options['grouping'],
        $options['rounding_mode'],
        $options['divisor'],
        $options['html5'] ? 'en' : null,
        $options['model_type'],
    ))
;
```

This code adds a view transformer to the form builder for the `MoneyType` field type. The transformer used is `MoneyToLocalizedStringTransformer`, which plays a key role in managing monetary values in Symfony forms. Here is an explanation of each parameter passed to the transformer:
- `scale`: Determines the number of digits after the decimal point for monetary values.
- `grouping`: Enables or disables the use of thousand separators in the localized format.
- `rounding_mode`: Specifies the rounding method to be used for amounts.
- `divisor`: A significant conversion factor for transforming values between storage (such as in cents) and display (such as in euros).
- `html5`: If this option is enabled, the format is set to 'en' to conform to the requirements of number type fields in HTML5.
- `model_type`: Indicates the type of data in the model (for example, 'float' or 'integer').

This transformer ensures that monetary values are correctly converted between their numeric representation in the model and a localized string representation in the view, thereby facilitating the precise and localized presentation of money amounts in the user interface while maintaining a reliable representation for server-side processing.

**Comment by xabbuh** [comment]
@teamflp Please use English for communication on GitHub.

**Comment by teamflp** [comment]
@xabbuh dans ce cas j'utiliserai Google Translate.

**Comment by xabbuh** [comment]
Thank you for updating your comment. :)

**Comment by xabbuh** [comment]
I guess we can indeed get rid of this (artificial) restriction: #54770
