### ISSUE TITLE
ConfigBuilderCacheWarmer is not executed when running cache:warmup

### ISSUE THREAD

**Issue by ArtemBrovko** [symfony/symfony#53496]
### Symfony version(s) affected

7.0.2

### Description

`\Symfony\Bundle\FrameworkBundle\CacheWarmer\ConfigBuilderCacheWarmer` is no longer executed when running `bin/console cache:warmup`

### How to reproduce

Create fresh Symfony 6.3 app, manually remove cache and execute `bin/console cache:warmup`. `var/cache/dev/Symfony/Config` folder is present in cache directory. This folder is created and populated by `ConfigBuilderCacheWarmer`

```
symfony new test-6.3 --version=6.3
cd test-6.3
rm -rf var/cache/dev/ && bin/console c:w && ls -al var/cache/dev/

$ rm -rf var/cache/dev/ && bin/console c:w && ls -al var/cache/dev/
...
drwxrwxrwx 4 artem artem  4096 Jan 11 01:04 .
drwxrwxrwx 3 artem artem  4096 Jan 11 01:04 ..
-rw-rw-rw- 1 artem artem    98 Jan 11 01:04 annotations.map
-rw-rw-rw- 1 artem artem 20832 Jan 11 01:04 App_KernelDevDebugContainerCompiler.log
-rw-rw-rw- 1 artem artem   689 Jan 11 01:04 App_KernelDevDebugContainerDeprecations.log
-rw-rw-rw- 1 artem artem   767 Jan 11 01:04 App_KernelDevDebugContainer.php
-rw-rw-rw- 1 artem artem     0 Jan 11 01:04 App_KernelDevDebugContainer.php.lock
-rw-rw-rw- 1 artem artem  7292 Jan 11 01:04 App_KernelDevDebugContainer.php.meta
-rw-rw-rw- 1 artem artem  8029 Jan 11 01:04 App_KernelDevDebugContainer.preload.php
-rw-rw-rw- 1 artem artem 96087 Jan 11 01:04 App_KernelDevDebugContainer.xml
-rw-rw-rw- 1 artem artem  7042 Jan 11 01:04 App_KernelDevDebugContainer.xml.meta
drwxrwxrwx 2 artem artem 12288 Jan 11 01:04 ContainerQ61v8jF
drwxrwxrwx 3 artem artem  4096 Jan 11 01:04 Symfony
-rw-rw-rw- 1 artem artem   349 Jan 11 01:04 url_generating_routes.php
-rw-rw-rw- 1 artem artem  1642 Jan 11 01:04 url_generating_routes.php.meta
-rw-rw-rw- 1 artem artem   594 Jan 11 01:04 url_matching_routes.php
-rw-rw-rw- 1 artem artem  1642 Jan 11 01:04 url_matching_routes.php.meta
```

Do the same thing but in newer version (6.4 or 7.0) and you will see that `var/cache/dev/Symfony` doesn't exist anymore.
```
$ symfony new test-7.0 --version=7.0
$ cd test-7.0

$ rm -rf var/cache/dev/ && bin/console c:w && ls -al var/cache/dev/
...
drwxrwxrwx 3 artem artem  4096 Jan 11 01:01 .
drwxrwxrwx 3 artem artem  4096 Jan 11 01:01 ..
-rw-rw-rw- 1 artem artem    23 Jan 11 01:01 annotations.map
-rw-rw-rw- 1 artem artem 20464 Jan 11 01:01 App_KernelDevDebugContainerCompiler.log
-rw-rw-rw- 1 artem artem     6 Jan 11 01:01 App_KernelDevDebugContainerDeprecations.log
-rw-rw-rw- 1 artem artem   875 Jan 11 01:01 App_KernelDevDebugContainer.php
-rw-rw-rw- 1 artem artem     0 Jan 11 01:01 App_KernelDevDebugContainer.php.lock
-rw-rw-rw- 1 artem artem  8564 Jan 11 01:01 App_KernelDevDebugContainer.php.meta
-rw-rw-rw- 1 artem artem  8046 Jan 11 01:01 App_KernelDevDebugContainer.preload.php
-rw-rw-rw- 1 artem artem 96050 Jan 11 01:01 App_KernelDevDebugContainer.xml
-rw-rw-rw- 1 artem artem  8314 Jan 11 01:01 App_KernelDevDebugContainer.xml.meta
drwxrwxrwx 2 artem artem 12288 Jan 11 01:01 Container7fJ0WCf
-rw-rw-rw- 1 artem artem   349 Jan 11 01:01 url_generating_routes.php
-rw-rw-rw- 1 artem artem  1642 Jan 11 01:01 url_generating_routes.php.meta
-rw-rw-rw- 1 artem artem   594 Jan 11 01:01 url_matching_routes.php
-rw-rw-rw- 1 artem artem  1642 Jan 11 01:01 url_matching_routes.php.meta
```

The same issue can also be reproduced with this command line
`bin/console c:c --no-warmup && bin/console c:w && ls -al var/cache/dev/`

### Possible Solution

This is most likely related to introduction of `build_dir` [New in Symfony 6.4: Build Dir Improvements](https://symfony.com/blog/new-in-symfony-6-4-build-dir-improvements)

### Additional Context

I'm attaching some more logs which compares behavior of different combination of `cache:clear [--no-warmup]` and `cache:warmup`
[history6.3.txt](https://github.com/symfony/symfony/files/13895510/history6.3.txt)
[history7.0.txt](https://github.com/symfony/symfony/files/13895511/history7.0.txt)

**Comment by ArtemBrovko** [comment]
I also made small PR with that fixes this issue, but I'm afraid I misunderstand the logic behind the change that caused this issue.
My initial thought was that the outcome of `bin/console cache:clear` and `bin/console cache:clear --no-warmup && bin/console cache:warmup` should be the same, as it was in 6.3 and prior

**Comment by xabbuh** [comment]
I cannot reproduce the issue. I created a new project based on the Symfony demo, created a file `config/packages/monolog.php` with the following contents:

```php
<?php

use Symfony\Config\MonologConfig;

return static function (MonologConfig $config): void {
};
```

The `MonologConfig` class was created afterwards when running `bin/console cache:clear`.

**Comment by ArtemBrovko** [comment]
yes, `bin/console cache:clear` is fine, but `bin/console cache:clear --no-warmup && bin/console cache:warmup` (or just `bin/console cache:warmup` with clean cache) is not

**Comment by xabbuh** [comment]
makes no difference for me, I can also remove the cache directory and run `cache:warmup` afterwards with getting the `MonologConfig` class generated

**Comment by ArtemBrovko** [comment]
That is really strange. This issue is reproducable for me and another developer in our project as well as in out ci pipeline and clean symfony application.
Even from looking at the code (i'm looking at 6.4), there are these pieces

symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheWarmupCommand.php:75
```
        $preload = $this->cacheWarmer->warmUp($cacheDir); // $buildDir param is not set
```

symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:108
```
                foreach ((array) $warmer->warmUp($cacheDir, $buildDir) as $item) { //  $buildDir is still null here
                    if (is_dir($item) || (str_starts_with($item, \dirname($cacheDir)) && !is_file($item)) || ($buildDir && str_starts_with($item, \dirname($buildDir)) && !is_file($item))) {
                        throw new \LogicException(sprintf('"%s::warmUp()" should return a list of files or classes but "%s" is none of them.', $warmer::class, $item));
                    }
                    $preload[] = $item;
                }

```

and here `ConfigBuilderCacheWarmer::warmUp` designed to skip warmer altogether if $buildDir is null
symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php:45
```
    public function warmUp(string $cacheDir /* , string $buildDir = null */): array
    {
        $buildDir = 1 < \func_num_args() ? func_get_arg(1) : null;

        if (!$buildDir) {
            return [];
        }
```

**Comment by xabbuh** [comment]
Ah, I can reproduce it. In my case the config class was not generated because of the cache warmup, but generating it happened  before because a PHP file making use of it was loaded by the container generation process.
