### ISSUE TITLE
AuthenticationUtils::getLastUsername(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by r3dge** [symfony/symfony#53503]
### Symfony version(s) affected

6.4.1

### Description

In production environment i get regularly this exception in logs : 

Uncaught PHP Exception TypeError: "Symfony\Component\Security\Http\Authentication\AuthenticationUtils::getLastUsername(): Return value must be of type string, null returned" at AuthenticationUtils.php

### How to reproduce

I don't know exactly what trigger this exception

### Possible Solution

Changing the return type of the method : 

public function getLastUsername(): ?string
    {
        $request = $this->getRequest();

        if ($request->attributes->has(SecurityRequestAttributes::LAST_USERNAME)) {
            return $request->attributes->get(SecurityRequestAttributes::LAST_USERNAME, '');
        }

        return $request->hasSession() ? $request->getSession()->get(SecurityRequestAttributes::LAST_USERNAME, '') : '';
    }

**Comment by xabbuh** [comment]
Looks like you need to investigate why `null` ends up as the value for the last username in the attributes bag or in the session.

Can you create a small example application that allows to reproduce your issue?

**Comment by r3dge** [comment]
This anomaly occurs randomly. I find it regularly in the production logs but I don't know how to reproduce it.

**Comment by r3dge** [comment]
I don't know why sometimes the return of the getlastUsername is null (return $request->hasSession() ? $request->getSession()->get(SecurityRequestAttributes::LAST_USERNAME, '') : '';)

I am trying to implement a workaround in my login controller like that : 

` if(($request->hasSession() ? $request->getSession()->get(SecurityRequestAttributes::LAST_USERNAME, '') : '') != null)
{
          $lastUsername = $authenticationUtils->getLastUsername(); 
}`
