### ISSUE TITLE
[Console] InputOption shortcut "-0" is not allowed

### ISSUE THREAD

**Issue by lawsonjl-ornl** [symfony/symfony#53514]
### Symfony version(s) affected

2.1-7.1

### Description

In the constructor of `Symfony\Component\Console\Input\InputOption` there is [some code](https://github.com/symfony/symfony/blob/efb9fa0b666d90f252fc7210c9d3c1392553a34d/src/Symfony/Component/Console/Input/InputOption.php#L90) to check for empty values of `$shortcut`:
#
```php
        if (empty($shortcut)) {
            $shortcut = null;
        }

        if (null !== $shortcut) {
            if (\is_array($shortcut)) {
                $shortcut = implode('|', $shortcut);
            }
            $shortcuts = preg_split('{(\|)-?}', ltrim($shortcut, '-'));
            $shortcuts = array_filter($shortcuts);
            $shortcut = implode('|', $shortcuts);

            if (empty($shortcut)) {
                throw new InvalidArgumentException('An option shortcut cannot be empty.');
            }
        }
```

Presumably the goal is to disallow empty strings as shortcut values.

But the use of `array_filter` with the default/empty callback here prevents using a shortcut like `-0`, because `'0'` evaluates to `false`.  (While uncommon, `-0` might be used in a command-line application to enable null-terminated output - see for example [xargs](https://www.gnu.org/software/findutils/manual/html_node/find_html/xargs-options.html) or [locate](https://www.gnu.org/software/findutils/manual/html_node/find_html/Invoking-locate.html))

### How to reproduce

Configure the following input option on any console command:

```php
new InputOption('null-terminated', '0', description: 'Print null-terminated output')
```

Observe the exception when executing the command:

```
 An option shortcut cannot be empty.
```

### Possible Solution

#53516

**Comment by dneykov** [comment]
Using symfony/console (v5.4.35) with Laravel 8 I still get the exception `An option shortcut cannot be empty.` when using php artisan.

Reverting back to symfony/console (v5.4.34) the exception is not thrown anymore. Any suggestions?

Thanks.

**Comment by vivdesign** [comment]
Same issue here

**Comment by dpetrovaliev** [comment]
Same issue here
