### ISSUE TITLE
EsmtpTransport does not honor tls false configuration

### ISSUE THREAD

**Issue by rvicinus** [symfony/symfony#53545]
### Symfony version(s) affected

7.0

### Description

The constructor of the EsmtpTransport offers the boolean parameter "tls", but even if configured to false, it switches to an encrypted connection if the server supports tls. This is an issue because if you try to connect to localhost, the certificate can not match and the connection fails with the exception: "SSL routines::certificate verify failed"

### How to reproduce

Test on a system which accepts mail on localhost port 25, and that support STARTTLS:
```
<?php
use Symfony\Component\Mime\Email;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;

require_once 'vendor/autoload.php';

$email = (new Email())
            ->from('test@example.com')
            ->to('test@example.com')
            ->subject('Test E-Mail')
            ->text('Test!');

$transport = new EsmtpTransport('localhost', 25, false);
$mailer = new Mailer($transport);
$mailer->send($email);
```

### Possible Solution

In my opinion, the correct solution would be to either honor the tls parameter or not to verify the certificate, if the host is localhost.

**Comment by xabbuh** [comment]
You can access the underlying stream through `getStream()`. With this when an instance of `SocketStream` you should be able to disable the verification using the standard [stream context options](https://www.php.net/manual/en/context.ssl.php).

**Comment by nicolas-grekas** [comment]
#53621 added an `auto_tls` option and a `setAutoTls` method that cover this use case.
