### ISSUE TITLE
[WebProfilerBundle] `ContentSecurityPolicyHandler` also sets `unsafe-inline` CSP directive

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#53552]
### Symfony version(s) affected

5.4, 6.4, 7.x

### Description

In Symfony 3.2.0 support for the `Content-Security-Policy` response header was introduced in `symfony/web-profiler-bundle` so that the debug toolbar still works when the current response has `default-src`, `script-src` and/or `style-src` directives.

However, the `ContentSecurityPolicyHandler` also adds the `unsafe-inline` directive to the response - but it is unclear why, as the debug toolbar's `<style>` and `<script>` tags uses nonces which are also added to the `Content-Security-Policy` header by the `ContentSecurityPolicyHandler`.

It's not really a big deal as this is just for the debug toolbar - but I think the `WebDebugToolbarListener` should either use nonces _or_ `unsafe-inline` (for simplicity), not both. Or is there a specific reason for adding both?

### How to reproduce

1. Install the website skeleton via `composer create-project symfony/website-skeleton`.
2. Create a basic controller rendering just the default `base.html.twig` template, but with a `Content-Security-Policy` header set - with e.g. `default-src 'self'`.
3. Open that controller's route and inspect the response headers. `unsafe-inline` will have been added to `style-src` and `script-src` - along with the generated nonces.

```
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'nonce-a631352a385b1d74534ca9417d86327e'; style-src 'self' 'unsafe-inline' 'nonce-9a693fce44878e2e61f407f39719588e'
```

Controller example:

```php
// src/Controller/ExampleController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/example')]
class ExampleController extends AbstractController
{
    public function __invoke(): Response
    {
        return $this->render('base.html.twig', response: new Response(headers: [
            'Content-Security-Policy' => "default-src 'self'",
        ]));
    }
}
```

**Comment by stof** [comment]
Setting `unsafe-inline` alongside nonces is about having a wider browser support. Browsers supporting nonces are ignoring `unsafe-inline` entirely when there is a nonce in the policy.

The Content-Security-Policy specification has 3 versions. nonces were added in v2, and this spec is designed to be able to have a fallback for browsers that might implement only the version 1 of the spec.

**Comment by TomaszGasior** [comment]
I think this should be reconsidered and reopened.

According to [Can I Use](https://caniuse.com/?search=Content+Security+Policy), CSP v1 is supported globally by 96.49% of web browsers and CSP v2 is supported by 96.37%. If you have other data proving this kind of backward compatibility is actually needed, it might be nice to include it here.

Also, currently at least in Mozilla Firefox the current logic of Symfony generates the following error in the console:

<img width="770" height="69" alt="Image" src="https://github.com/user-attachments/assets/b19b14dc-07bc-4340-8671-bbe974f30192" />

**Comment by stof** [comment]
I suggest reporting this to Firefox instead. Logging this at the warning level while it uses the feature **as intended by the spec** to cover the broader browser support seems overzealous for them in the direction of treating that as a developer making a mistake and not being aware of it vs a developer actually reading the documentation and understanding the feature properly.

The current implementation in WebProfilerBundle means that WebProfilerBundle does not reduce **at all** the kind of browser support your page has, which is better than reducing it.
