### ISSUE TITLE
UnrecoverableMessageHandlingException ended message still in failed transport

### ISSUE THREAD

**Issue by stefandoorn** [symfony/symfony#53561]
### Symfony version(s) affected

5.4.31 (messenger component)

### Description

In some of my message handlers, I throw a UnrecoverableMessageHandlingException, e.g. when on `staging` we have no API key set. It will never recover from that.

Based on the docs, I expect that message not to show up in the failed transport, but it seems to do:

```
bin/console messenger:failed:show 2543
> Loading messages from the global failure transport failed.
> To use a different failure transport, pass --transport=.
> Available failure transports are: failed


There is 1 message pending in the failure transport.

Failed Message Details
======================

 ------------- ----------------------------------------------------------------------------- 
  Class         Project\Message\SyncOrder                      
  Message Id    2543                                                                         
  Failed at     2024-01-17 12:11:20                                                          
  Error         API Key missing                                                             
  Error Code    0                                                                            
  Error Class   Symfony\Component\Messenger\Exception\UnrecoverableMessageHandlingException  
  Transport     async_low                                                                    
 ------------- ----------------------------------------------------------------------------- 

 Message history:
  * Message failed at 2024-01-17 12:11:20 and was redelivered

 Re-run command with -vv to see more message & error details.

 Run messenger:failed:retry 2543 --transport=failed to retry this message.
 Run messenger:failed:remove 2543 --transport=failed to delete it.
```

This way, the `failed` transport becomes pretty big, although based on the exception thrown it can be discarded. It's an expected output.

### How to reproduce

* Create a message & messagehandler
* Schedule it
* Let the messagehandler throw a UnrecoverableMessageHandlingException
* Check `bin/console messenger:failed:show` and it shows up

### Possible Solution

Possible solution suggested here: https://github.com/symfony/symfony/issues/35459#issuecomment-579679061

**Comment by valtzu** [comment]
As I see, this is expected behavior. `UnrecoverableMessageHandlingException` means the message won't be retried within the same transport, regardless of `retry_strategy`.

This seems to be answered many times before (f.e. in the issue you linked), it may be a documentation issue, or just that developers don't always read documentation, or it's just kinda complex thing to understand.

---

If your intention is to make the failed message disappear, then I would suggest, just don't throw any exception (catch `Throwable` in the handler or something). If you want still want to log the error, use logger directly.

**Comment by xabbuh** [comment]
@stefandoorn Does @valtzu's comment help?

**Comment by stefandoorn** [comment]
Hi @xabbuh & @valtzu - thanks for the explanation here. I think it's more of a documentation / understanding issue then from my end. 

<img width="734" alt="image" src="https://github.com/symfony/symfony/assets/4903082/c88fe6b8-c705-458e-8376-d9597aaa9b3a">

Because of the usage of `permanent and should not be retried`, suggests to me that it won't be regarded as a `failure`. But I can also see how it can still mean that. It might be useful there to specify it slightly more clear in the documentation.

I will make some adjustments on my end as per suggestion, thanks!

**Comment by xabbuh** [comment]
Would be great if you could click the edit button on that documentation page and rewrite the paragraph a bit as you do think it would be more. It may be confusing for others too. :)

**Comment by stefandoorn** [comment]
Sure - will see if I can find some time for it soon! :-)

**Comment by xabbuh** [comment]
Thanks! That's really appreciated. I close here for now as it seems to me that the code is behaving as expected. Thank you for understanding.

**Comment by stefandoorn** [comment]
@xabbuh Created a PR: https://github.com/symfony/symfony-docs/pull/19449
