### ISSUE TITLE
`HtmlErrorRenderer` loops near-infinite times during functional tests

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#53563]
### Symfony version(s) affected

6.4.2

### Description

My tests freeze and appear to completely lock up in an infinite or near-infinite loop. They just consumed over 6 hours of GitHub Actions minutes to do nothing or almost nothing. Locally I can reproduce the issue also.

### How to reproduce

I'm not sure there is a clear path to reproduction. In my case, there is a database constraint violation which causes a/most test(s) to fail. According to my trace output, this results in `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer` running in a near-infinite loop doing millions of `str_replace` calls searching for `'<br />'`, for some reason. However, it does eventually break out of this (extensive) loop and then gets stuck in another loop calling `Masterminds\HTML5\Parser\Tokenizer->consumeData()` (and a few descendent calls such as `current()`, `next()`, `position()`, `decodeCharacterReference()`, etc.) ad-infinitum.

I don't exactly know why `HtmlErrorRenderer` gets involved, I guess that's just a standard error listener that's part of the framework, but the HTML5 parser comes into play due to `Symfony\Component\BrowserKit\AbstractBrowser->createCrawlerFromContent()` getting called as part of using `WebTestCase` to make a (simulated) HTTP request using `WebTestCase::createClient()->request()`. 

Not sure if that's enough for someone very familiar with this system to figure out what could be going wrong.

### Possible Solution

Limiting the number of times `HtmlErrorRenderer` can loop may be possible. I think it is trying to render an exception trace stack that has somehow become catastrophically nested.

### Additional Context

It does not generally get stuck in an infinite loop when errors occur on a page, but for some reason it does when there's a database constraint violation.

* `HtmlErrorRenderer->fileExcerpt()` seems to have to do a lot of work for `vendor\\revolt\\event-loop\\src\\EventLoop\\Internal\\AbstractDriver.php` and other Amp/fiber-related sources, typically 114 KB.
* `Masterminds\HTML5\Parser\Tokenizer->consumeData()` has to process moderately large HTML sources, typically 367 KB.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Bilge** [comment]
I doubt it. Best I could do is upload the (gigantic) trace, but it would need redacting and I'm not sure I could do so reliably for such a big file (currently 318 MB).

**Comment by xabbuh** [comment]
I am afraid there is not much we can do then if not someone comes up with a wild guess about the potential reason for this (having something like a Blackfire profile may help though).

**Comment by Bilge** [comment]
>€33.25/month

Think I might have to pass on that one.

**Comment by xabbuh** [comment]
Let's close here for now as the issue as is is not actionable. Thank you for understanding.
