### ISSUE TITLE
Failed to start the session because headers have already been sent

### ISSUE THREAD

**Issue by ddziech** [symfony/symfony#53584]
### Symfony version(s) affected

6.4.2

### Description

When cookie `PHPSESSID` is set and i make `var_dump()` I get this error:
![image](https://github.com/symfony/symfony/assets/4982339/bbe58f76-8288-45b8-adb9-05d0d71ddb42)
![image](https://github.com/symfony/symfony/assets/4982339/a47b5caa-8cf1-4424-b6d4-19f053d12c23)

### How to reproduce

Create new project: 
- `symfony new symfony_webapp --version="6.4.*" --webapp`
- `cd symfony_webapp`

Create `StartController`
```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StartController extends AbstractController
{
    #[Route('/start', name: 'app_start')]
    public function index(): JsonResponse
    {
        var_dump('asdf');
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/StartController.php',
        ]);
    }

    #[Route('/session', name: 'app_session')]
    public function ses(RequestStack $requestStack): Response
    {
        $requestStack->getSession()->set('a', 'b');

        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/StartController.php',
        ]);
    }

}

```

Run server:
- `symfony server:start`

Go to:
 - first `http://127.0.0.1:8000/session`
   - cookie `PHPSESSID` is created
 - next `http://127.0.0.1:8000/start`
   - error

### Additional Context

```bash
❯ php -v
PHP 8.3.2 (cli) (built: Jan 19 2024 10:02:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
```

**Comment by xabbuh** [comment]
I cannot reproduce your issue with the steps that you provided. Can you please create a small example application that allows to reproduce your issue?

**Comment by ddziech** [comment]
@xabbuh Example app `https://github.com/ddziech/symfony_webapp`

`git clone git@github.com:ddziech/symfony_webapp.git`

**Comment by xabbuh** [comment]
works for me as well

**Comment by ddziech** [comment]
damn..., i added `docker compose` version, can you check this too?
`git pull && docker compose up` 
`http://localhost:8000/session` -> `http://localhost:8000/start`

**Comment by xabbuh** [comment]
@ddziech with your Docker setup I can reproduce it indeed 👍

**Comment by ddziech** [comment]
yeah, so, most likely the fault is in the php configuration
when output_buffering is set to 0, or OFF
![image](https://github.com/symfony/symfony/assets/4982339/4f8d2d5c-5fe8-4a8f-9e76-d22e1bfdcaf7)
then not working (my problem)
and when is set (4096, or ON)
![image](https://github.com/symfony/symfony/assets/4982339/a0ffc42d-042b-4531-9413-b7d7f1178aca)
everythink just working fine :)

**Comment by ddziech** [comment]
@xabbuh thanks for checking, it helped us find what the problem might be

**Comment by xabbuh** [comment]
👍 great, happy to see that you were able to resolve it
