### ISSUE TITLE
[RFC] [Doctrine Bridge] More modularity for Uuid/Ulid

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#53596]
### Description

Currently we have this for the `doctrine-bridge` : https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bridge/Doctrine/composer.json

It contains a lot of different bridges between doctrine and symfony components.

But in my case, I would like to have only the bridge between the `uid` component and Doctrine.

What do you think about adding here (https://github.com/symfony/symfony/tree/6.4/src/Symfony/Bridge/Doctrine/Types) a `composer.json` file for a package like `symfony/uid-doctrine-bridge`. 

With this, if I need to download the `uid` bridge, I will not delete the entire bridge but only this subpart.

Or a package outside of this folder, similar of this one : https://github.com/symfony/doctrine-messenger

**Comment by javiereguiluz** [comment]
Thanks for this proposal. Personally, I'm not sure it's worth it. Even if the Doctrine bridge contains a lot of things, it's a very lightweight package:

```
~/work/symfony/src/Symfony/Bridge/Doctrine [7.1]
$ du -sh ./* | sort -h
4.0K	./Attribute
4.0K	./CacheWarmer
4.0K	./LICENSE
4.0K	./ManagerRegistry.php
4.0K	./README.md
4.0K	./composer.json
4.0K	./phpunit.xml.dist
8.0K	./ArgumentResolver
8.0K	./CHANGELOG.md
8.0K	./ContainerAwareEventManager.php
8.0K	./IdGenerator
 12K	./DataCollector
 12K	./PropertyInfo
 12K	./Types
 24K	./Messenger
 24K	./SchemaListener
 28K	./Security
 28K	./Validator
 32K	./Middleware
 60K	./DependencyInjection
 60K	./Form
644K	./Tests
```

The bulk of the component are the `644k` of `Tests/` contents, but those should not be a problem because they are ignored in `.gitattributes`

**Comment by nicolas-grekas** [comment]
I agree with Javier, this is not worth it.
