### ISSUE TITLE
[Scheduler] bin/console debug:scheduler stuck indefinitely

### ISSUE THREAD

**Issue by faizanakram99** [symfony/symfony#53599]
### Symfony version(s) affected

6.4.0

### Description

bin/console debug:scheduler is stuck indefinitely schedule has state.

I can't provide a reproducer (at this point), but `bin/console debug:scheduler` was working fine until I added cache to it (`stateful($this->cache)`) and ever since I run the command, it is just stuck.

Regardless if it is a local or production environment.

![image](https://github.com/symfony/symfony/assets/10880992/afbabc5e-5874-44ee-bd1e-7ec9f466cf83)

It is worth mentioning that one of the periodic tasks (message) failed on last schedule and was supposed to run today (but didn't apparently or did it? IDK because I can't see when it is supposed to run next). The worker is up though.

### How to reproduce

I am not sure yet, but maybe add a simple schedule with state (stateful) and throw exception from the message handler (or the scheduled task once), run debug:scheduler, it will be stuck.

**Comment by xabbuh** [comment]
Can you please try to debug where exactly the process is hanging?

**Comment by faizanakram99** [comment]
I can't reproduce it anymore, will reopen if I can reproduce it.
