### ISSUE TITLE
[Cache] RedisAdapter::createConnection - RedisCluster context

### ISSUE THREAD

**Issue by vencakrecl** [symfony/symfony#53597]
### Symfony version(s) affected

7.0.2

### Description

The context values verify_peer and verify_peer_name must contain the boolean value. I don't know why there is the condition `...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []` in the last parameter, for me does not make any sense.

### How to reproduce

```php
RedisAdapter::createConnection('rediss://redis:6379?ssl[verify_peer]=false&ssl[verify_peer_name]=false&redis_cluster=true&auth[user]=root&auth[pass]=root')
```

### Possible Solution

```php
trait RedisTrait
{
...
    $context = [];
    foreach ($params['ssl'] ?? [] as $key => $value) {
        if(in_array($value, ['true', 'false'])) {
            $context[$key] = $value === "true" ? true : false;
        }else {
            $context[$key];
        }
    }

    try {
        $redis = new $class(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'], $params['auth'] ?? '', $context);
    } catch (\RedisClusterException $e) {
        throw new InvalidArgumentException('Redis connection failed: '.$e->getMessage());
    }
...
}
```

**Comment by xabbuh** [comment]
If I understand the description correctly, the values `true` and `false` are forwared to the Redis classes as strings which does not work and they have to be cast to booleans upfront. Is that correct?

The check was added in symfony/symfony#41099, but that's probably not related to the issue you describe here.

**Comment by vencakrecl** [comment]
Yes, it is. 
The condition `...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []` does not make any sense because it is `\RedisCluster` not `\Redis`.

**Comment by xabbuh** [comment]
What I mean is, both the context support for `Redis` as well as `RedisCluster` were added in version 5.3 of the PHP extension, right? So in previous version we must not pass the argument to prevent runtime errors (and thus reintroduce #41110).

But the real issue here is that we do not pass boolean values for some of the context options, isn't it?

**Comment by vencakrecl** [comment]
@xabbuh Ok, got it. This means that the condition is there for backward compatibility. Yes, exactly. Some context values need to be passed as boolean values.

**Comment by xabbuh** [comment]
Can you please check if #53975 fixes the issue for you?

**Comment by vencakrecl** [comment]
@xabbuh I just tested in Symfony 7.0.3 the changes and it works well, see code snippet. Thank you! Can you add an example of DSN to the documentation, it was really hard to find out how to pass auth (username+pass) and SSL parameters.
```php
$booleanStreamOptions = [
    'allow_self_signed',
    'capture_peer_cert',
    'capture_peer_cert_chain',
    'disable_compression',
    'SNI_enabled',
    'verify_peer',
    'verify_peer_name',
];

foreach ($params['ssl'] ?? [] as $streamOption => $value) {
    if (\in_array($streamOption, $booleanStreamOptions, true) && \is_string($value)) {
        $params['ssl'][$streamOption] = filter_var($value, \FILTER_VALIDATE_BOOL);
    }
}

try {
    $redis = new $class(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'], $params['auth'] ?? '', ...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []);
} catch (\RedisClusterException $e) {
    throw new InvalidArgumentException('Redis connection failed: '.$e->getMessage());
}
```

**Comment by xabbuh** [comment]
> Can you add an example of DSN to the documentation, it was really hard to find out how to pass auth (username+pass) and SSL parameters.

Do you have a place in the documentation in mind where you would have liked to see a bit more information?

**Comment by vencakrecl** [comment]
https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#configure-the-connection There is the section "Below are common examples of valid DSNs showing a combination of available values:" where is missing an example with username and password together and with SSL options, for example `RedisAdapter::createConnection('rediss://redis:6379?ssl[verify_peer]=false&ssl[verify_peer_name]=false&redis_cluster=true&auth[user]=root&auth[pass]=root')`
