### ISSUE TITLE
MapQueryString doesn't support string value for boolean type

### ISSUE THREAD

**Issue by mvanduijker** [symfony/symfony#53616]
### Symfony version(s) affected

6.3, 6.4, 7.0

### Description

MapQueryString attribute fails parsing string value for boolean type.

Problem is nicely described in this issue https://github.com/symfony/symfony/issues/42715 
But in this case we know for sure that it's a string (just like the CSV and XML types in [AbstractObjectNormalizer.php](https://github.com/symfony/symfony/blob/e34cd7dd2c6d0b30d24cad443b8f964daa841d71/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L432-L441)

Don't know if it's a bug or a feature.

### How to reproduce

I expect the following to be false, but true is returned.

Request Url
```
https://example.com?myBoolean=false
```
DTO
```
<?php

readonly class MyDTO 
{
    public function __construct(
        public bool $myBoolean
    )    
}
```
Controller
```
<?php

use Symfony\Component\HttpKernel\Attribute\MapQueryString;
use Symfony\Component\Routing\Annotation\Route;

class MyController
{
    #[Route('/')]
    public function __invoke(
        #[MapQueryString]
        MyDTO $dto
    ) {
        dd($dto->myBoolean);
    }
}
```

**Comment by andrashegedus** [comment]
I have this problem too.
I use Symfony 6.3.7.
![kép](https://github.com/symfony/symfony/assets/97115655/60d100f7-6c23-4a36-920f-e9f08ac14fea)
