### ISSUE TITLE
Impersonation events

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/symfony#53617]
### Description

According to [docs](https://symfony.com/doc/current/security/impersonating_user.html#events):
"security.switch_user event is dispatched just before the impersonation is fully completed."

Is this current behaviour intentional and why? If not, can we make this event fire only after the user was fully switched?
If not, then I would expect the docs to exactly define the meaning of "fully completed" and addition of a new event so we would have:
`security.switch_user_before`
`security.switch_user_after`

The code below demonstrates one specific situation in which the service returns `PostAuthenticationToken` and I would expect it to return `SwitchUserToken`.
Version used `6.3.8`

```
public function onSwitchUser(SwitchUserEvent $event): void
    {
        $token = $event->getToken();   dump($token); // This returns SwitchUserToken
        ...
        .... later ....
        $this->someService->someMethod();
    }
```

The service's method:
```
public function someMethod()
    {
        $token = $this->security->getToken();   dump($token);   // This returns PostAuthenticationToken
        if ($token instanceof SwitchUserToken) 
        {
            $impersonatorUser = $token->getOriginalToken()->getUser();
             ......
        }
    }
```

**Comment by xabbuh** [comment]
The event can be dispatched at two different times in the process of switching between users:

1. When you switch to another user, in this case the token will be a `SwitchUserToken`. Any listener to this event can replace the token. Afterwards the token is put into the token storage and the user is switched.
2. When you end your switched user session, the event will be fired again. This time the token is the original token (i.e. the token of the user that switched to the current user).

**Comment by DavidPetrasek** [comment]
>     1. When you switch to another user, in this case the token will be a `SwitchUserToken`.
Yes, you can see that my in my code example above where I precisely marked the `SwitchUserToken`, but as you can see it does not work as expected because it returns `PostAuthenticationToken` in a service. **Is this really the intended behaviour? If yes, why?**

>     2. When you end your switched user session, the event will be fired again. This time the token is the original token (i.e. the token of the user that switched to the current user).
I don't know if my issue is also related to switching back to the original user.

**Comment by xabbuh** [comment]
> Yes, you can see that my in my code example above where I precisely marked the SwitchUserToken, but as you can see it does not work as expected because it returns PostAuthenticationToken in a service. Is this really the intended behaviour? If yes, why?

THat's expected, if you want to access the token while the event is handled, you have to fetch it from the event. The token storage is not updated before the event handling has finished. That's what "before the impersonation is fully completed" refers to.

**Comment by stof** [comment]
Dispatching the event before or after solves different use cases. If we dispatch it after fully switching, listeners won't be able to modify the token anymore.

Reading from the token storage for logic running during the authentication process is not a supported use case. This is true for any of the authentication events.

**Comment by DavidPetrasek** [comment]
Thank you for explanation.
