### ISSUE TITLE
[symfony/http-client] It is not possible to get the upload file progress

### ISSUE THREAD

**Issue by BaHeK1994** [symfony/symfony#53610]
### Description

https://github.com/symfony/http-client/blob/db714986d3b84330bb6196fdb201c9f79b3a8853/Response/CurlResponse.php#L124

There are 5 methods in the CURLOPT_PROGRESSFUNCTION callback function:the fourth is the total number of bytes expected to be uploaded in this transfer, and the fifth is the number of bytes uploaded so far. You are transferring only 3, because of this it is impossible to get the progress of the upload file

**Comment by xabbuh** [comment]
Would you like to send a PR with the solution that you have in mind?

**Comment by nicolas-grekas** [comment]
Before doing any changes: the API is like that because that's the most portable signature (it provides compatibility with native PHP's progress function.)

But can't you use the `$info` argument to build the upload progress meter? It contains the raw curl stats, which might contain the needed data.

**Comment by BaHeK1994** [comment]
> But can't you use the `$info` argument to build the upload progress meter? It contains the raw curl stats, which might contain the needed data.

Thanks, $info['size_upload'] contains the data I need

**Comment by xabbuh** [comment]
Should we close here then?
