### ISSUE TITLE
[HttpClient] Run output through `idn_to_ascii()` to puny-decode IDNs?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#53635]
### Description

`$response->getInfo('url')` returns the "raw" (i.e. puny-encoded) URL, e.g. `https://www.xn--...`. But when working with Internationalized Domain Names (IDN), you usually use the "Umlaut"-domain (e.g. `https://www.dömäin.example`).

So maybe it would be a good idea to automatically do `idn_to_ascii()`?

**Comment by nicolas-grekas** [comment]
I'd need to be convinced. "url" is meant as the resolved URL so for now at least I'm fine with the current behavior.
More arguments needed for me :)

**Comment by ThomasLandauer** [comment]
My use case: I have the URL in the form `https://www.dömäin.example/`, and I want to check if the ultimate URL (i.e. after following all redirects) is the same.
* On one hand, I was surprised that HttpClient gave me the puny-encoded URL back.
* On the other hand, the fix is so easy (`$url === idn_to_utf8($response->getInfo('url'))`) that it might not be worth a change.

=> Let's wait for more feedback from others. Especially: Does anybody need the "raw" (i.e. puny-encoded) URL?

**Comment by stof** [comment]
@ThomasLandauer and then, someone gaving the punycode one as input (which is also valid) asks us to revert the change because we would have broken the equality check for _their_ case.

**Comment by stof** [comment]
Btw, I'm not even sure all implementations return the punycode representation in the info. It might depend on the implementation of the client.

**Comment by nicolas-grekas** [comment]
URL resolution is handled on our side so the value should be the same on all implementations (that use HttpClientTrait)
But it's true that this would be a BC break if we don't do it carefully.
Maybe not worth adding a new info if the alternative is so simple.

**Comment by nicolas-grekas** [comment]
idn_to_utf8 FTW ;)
