### ISSUE TITLE
[Yaml] Dumper for enums return !php/const instead of !php/enum

### ISSUE THREAD

**Issue by cobyl** [symfony/symfony#53636]
### Symfony version(s) affected

7.0.0

### Description

Dumper for enums return !php/const instead of !php/enum

### How to reproduce

```
        $dump  = Yaml::dump(Level::Debug, 256);
        var_dump($dump);
```
gives:
```
       "!php/const Monolog\Level::Debug"
```

### Possible Solution

The yaml component properly evolves php/const in such situations and returns an enum anyway, but this is confusing.

Replace in Inline.php this line
```
            case $value instanceof \UnitEnum:
                return sprintf('!php/const %s::%s', $value::class, $value->name);
```
and corresponding tests

**Comment by xabbuh** [comment]
Looks like we didn't consider the dumping part when adding support for parsing enums in #46771. Support for enums with the `!php/const` tag was added before in #40857.

I have openend #53680 to harmonise parsing and dumping.
