### ISSUE TITLE
[RFC][Security] Switch user redirection dynamic

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#53645]
### Description

I've in the past needed a generic user switch so [I implemented it](https://github.com/symfony/symfony/pull/46338) at config level
Now I find myself I need it at runtime level, specific per user switch execution

right now I have an hack solution, kind of making work it but not perfect

RFC: would it make sens to implement such logic in the Symfony core directly? (in event + listener)

For ex in https://github.com/symfony/symfony/blob/d621936e8c638247de4c5d1cd75cc5ff55b84c3e/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L127, adding in priority a method call that can read such new redirectPath from the switch user event for example

Of course I will contribute it if it is valuable

Thank you

---

Actual code I have/trying: maybe store data in session and catch it on user switch finish and redirect on it

**Comment by 94noni** [comment]
closing here as PR is implemented, waiting reviews

**Comment by stof** [comment]
We are only closing issues when the PR is merged (or rejected entirely)

**Comment by 94noni** [comment]
got it thx :)
