### ISSUE TITLE
Possible problems after release next versions of Doctrine DBAL in messenger transaction middleware.

### ISSUE THREAD

**Issue by ZhukV** [symfony/symfony#53642]
### Description

By default, doctrine not use savepoints, and if developer open transaction in opened transaction, doctrine dbal nothing to do (developer can change it, and work with savepoints).

It's very powerful, because I as developer can use `TransactionMiddleware` on message bus, and not think about flush entity managers and easy to use locks mechanism on db.

And, we must understand, that developer can execute message inside another message handler (nested calls). In this case, on `TransactionMiddelware` always calls `beginTransaction`, but `doctrine/dbal` control nested calls and don't execute any code on beginTransaction if transaction already opened (this setting can be configured, but only now).

Now, Doctrine/DBAL trigger deprecations if developer try begin new transaction inside opened transaction and will be use savepoints. (https://github.com/doctrine/dbal/pull/5383/files).

After next update of Doctrine/DBAL, developer can have any problems, because they can use nested message calls, and doctrine open multiple savepoints, which can be difficult for a developer (previosly doctrine/dbal open only root transaction, without savepoints).

I try to ask question https://github.com/doctrine/dbal/issues/6272 and describe possible problem, but not any response.

As result, to avoid possible problems, control nested transaction can be implemented on `TransactionalMiddelware`, and add possible to configure it for developer.

P.S. I understand, control nested calls inside TransactionMiddleware bad idea, but I doubt that doctrine/dbal will do anything to solve this problem.

**Comment by xabbuh** [comment]
I am not sure after (even after reading the linked discussion) if I understand the issue correctly. Maybe it's easier to grasp if you can showcase the issues you foresee by a small application that uses the next version of Doctrine DBAL and suffers from these issues.

**Comment by ZhukV** [comment]
@xabbuh , ok, not problem. Thank for fast response.

Test app here: https://github.com/ZhukV/TestSymfonyDbalSavepoint/tree/master

Please follow instructions in README

If savepoints disabled (by default, but deprecated), all OK, perfectly. Only one root transaction opened.

<img width="986" alt="Screenshot at Jan 26 12-56-41" src="https://github.com/symfony/symfony/assets/2256109/9b537e25-c5af-45c9-b59c-3982f93b468a">

But if savepoints enabled (use as default in future releases of doctrine/dbal), will be very difficult for understanding, why system opens many savepoints, when I want to open only one root transaction.

<img width="765" alt="Screenshot at Jan 26 13-12-29" src="https://github.com/symfony/symfony/assets/2256109/1b8560be-20d0-48cf-9773-43b0fff7426e">

Note: this very small logic for illustrate possible problem. As example, in our applications, depth of nested call can be 3 and more.

For small applications, who not use transactional layers, it's not problem. But for applications, who use symfony transaction middleware, or create custom middlewares it's maybe problem in future.

In linked discussion, I wanted to present only that system can have nested calls with opening transactions, and in some cases use savepoints can be wrongly (in test application as example: why we should open savepoints in nested calls?).

Thanks!

**Comment by ghost** [comment]
I was wrong :)

**Comment by ro0NL** [comment]
> developer can have any problems,

> to avoid possible problems

> it's maybe problem in future

please explain the problem :)

**Comment by ZhukV** [comment]
@ro0NL , save points can cause misunderstanding among the developer himself after update vendors. It doesn't change anything in how application work.

@javaDeveloperKid very well said:

> If a developer is misunderstood by savepoint then he should gain knowledge about what it is and how it works.

Sorry me, for maybe incorrect question ;)

**Comment by ro0NL** [comment]
> It doesn't change anything in how application work.

i'm not sure now :( 

```
Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_71 does not exist
```

**Comment by ghost** [comment]
@ro0NL please give more details

**Comment by ro0NL** [comment]
Working on it :)

i can only find logged CLI output in prod :(

```
CRITICAL  [messenger] Error thrown while handling message Some. Removing from transport after 0 retries. Error: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_116 does not exist" ["class" => "Some","retryCount" => 0,"error" => "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_116 does not exist","exception" => Doctrine\DBAL\Exception\DriverException { …}]
```

im pretty sure it happens at transaction middleware layer

for now we've disabled savepoints (`use_savepoints: false`)

**Comment by ro0NL** [comment]
Created #11230
