### ISSUE TITLE
[Form] Use self-closing `<input />` tags again

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#53649]
### Description

#47715 removed self-closing slashes from `<input>` elements in the various form themes, i.e. it changed `<input ... />` to `<input ...>`.

My request is to revert this change, or at least to make it configurable (either way opt-in/opt-out/opt-back-in).

The reasons given in #47715 were:

> Switching form template from XHTML to HTML5 syntax.
> https://validator.w3.org/nu/ says:
>> Warning: Self-closing tag syntax in text/html documents is [widely discouraged](https://google.github.io/styleguide/htmlcssguide.html#Document_Type); it’s unnecessary and [interacts badly with other HTML features](https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10809) (e.g., unquoted attribute values). If you’re using a tool that injects self-closing tag syntax into all void elements, https://github.com/prettier/prettier/issues/5246, then consider switching to a different tool.

The "widely discouraged" reference to https://google.github.io/styleguide/htmlcssguide.html#HTML_Style_Rules does, as of today, state nothing about self-closing tags anymore. And, as of today, the W3 validator merely writes:

> [Info] Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

That's a far less opinionated statement.

The referenced document at https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing goes on nit-picking that that for "void elements" (like `<hr>` or `<input>`), the trailing slash does not mark the start tag as self-closing, but instead...

> the standard states that you can use a trailing slash in a void-element start tag for literally any purpose except to mark the start tag as self-closing.
> So, for example, the following are all acceptable reasons for using a trailing slash in a void-element start tag —
> [...]
> ✅ I use a trailing slash because I run my HTML markup through a formatting tool that’s hardcoded to add trailing slashes to all void-element start tags, without any option for me to prevent the tool from doing that.

The other argument against the slash is a possible mis-interpretation when using unquoted attribute values. That, however, is not an issue for the case we're discussing here (the form themes all using quoted attribute notation).

This now brings me to my reason _why_ I'd like to keep the `<input />` style for now:

When you want to use the PHP DOM extension for parsing HTML5, doing DOM transformations and/or using XPath, you can do so under the requisite of writing [Polyglot HTML 5](https://www.w3.org/TR/html-polyglot/). Basically, this describes a set of extra rules to follow to write markup in a way that it has the same meaning to an HTML 5 and an XML parser. PHP DOM functions are based on `libxml2`, an XML parser.

Writing Polyglot HTML 5 allows to use PHP DOM extension functions to load, inspect, modify and dump HTML 5 documents. Polyglot HTML 5 requires [self-closing tags to be used for void elements](https://www.w3.org/TR/html-polyglot/#empty-elements). 

Removing the self-closing trailing slash as in #47715 takes this possibility from users, unless they completely override the form theme or do quirky string-replacements on the content. This is exactly what was made to get the tests green at https://github.com/symfony/symfony/pull/47715/files#r1280400076 - run a `preg_replace` to use the DOM functions afterwards.

The `/` may be superfluous and annyoing for purists, but it is officially OK and valid. It allows to keep the PHP DOM use case working.

#### Some more words on libxml2

The `libxml2` library powering the PHP DOM functions has been written 20 years ago, long before the advent of HTML 5. It has no HTML 5 support, and that's probably never going to change. To my knowledge, there is no established, proven, fast alternative available as of today. 

There is https://github.com/Masterminds/html5-php, but as a parser written in PHP it cannot compare with the C efficiency of `libxml2`. 

All the problems surrounding `libxml2` and its use on HTML 5 are neatly summarized in https://wiki.php.net/rfc/domdocument_html5_parser. That RFC lead to what seems to be HTML 5 support in the DOM extension – but [the implementation](https://github.com/php/php-src/pull/12111) has been merged into PHP only two months ago.

The [comment](https://github.com/symfony/symfony/pull/47715#issuecomment-1344254110) over at the disputed PR that points to `...loadHTML()` is a trap. `loadHTML` in `libxml2` implements logic that tries to recover non-well formed HTML 4 – a technology from the last millenium only the most seasoned among us might remember – into XHTML 1.0. This is not a sane thing to run on HTML 5 input, and the [php.net documentation](https://www.php.net/manual/de/domdocument.loadhtml.php) features a red warning box about this.

**Comment by mpdude** [comment]
Inviting @ThomasLandauer as the author of #47715 to the discussion. I'd like to learn more about your use cases and why it was important to you to change this?

**Comment by mmarton** [comment]
sidenote: php8.4 will come with proper html5 support
https://wiki.php.net/rfc/domdocument_html5_parser

**Comment by derrabus** [comment]
@mpdude Would the HTML5 parser that will be shipped with PHP 8.4 solve your problem?

**Comment by mpdude** [comment]
I haven't yet had the opportunity to try it. But after all I read about it and why it was written in the first place, I assume yes.

**Comment by mpdude** [comment]
Would it be an option to revert the change and postpone it to a Symfony version that requires PHP 8.4?

Could this be reverted as a bug fix, or in a feature release only (since it was added in feature release 6.4 as well)?

**Comment by ThomasLandauer** [comment]
I opened that PR just because `/>` looked like a forgotten leftover from the old days of XHTML to me. I posted the validator link cause I had it at hand - not cause it's the ultimate authority in this question.

**Comment by mpdude** [comment]
What would be an acceptable target branch for a PR that reverts the change?

**Comment by fabpot** [comment]
> What would be an acceptable target branch for a PR that reverts the change?

6.4 I suppose

**Comment by mpdude** [comment]
I will prepare a PR

**Comment by mpdude** [comment]
PR is at #53656

**Comment by mpdude** [comment]
Fixed by #53656

**Comment by ThomasLandauer** [comment]
@mpdude You suggested [above](#issuecomment-1913111156) to postpone this till Symfony requires PHP 8.4. With Symfony 8.0, this is now the case. So what do you think about removing `/>` again in Symfony 8.1? Can you confirm that this would work for you?

**Comment by mpdude** [comment]
Still I haven't yet had the opportunity to play with the new HTML 5 parser in 8.4. From what I read about it two years ago, it was supposed to be a drop-in replacement to read HTML 5, but map that to the existing DOM API internally, so that existing DOM/XPath code could be used as-is. But recently I also read other articles that suggest otherwise. Either way, I have no practical evidence yet to support the one or the other point.

Current code in some of the projects I maintain will stop working for sure when this would be changed, but that's a personal problem of mine.

So, why would you like to change it? Is it because it "looks more modern" or is "better HTML5 style"? To prevent validators from emitting notices that bash Symfony?

As I have pointed out above, potential problems with the unquoted attribute notation style are not an issue within the Symfony form themes, which do not use this style.

Update: 

Here's [the claim that the API turned out not to be feasible as a drop-in replacement](https://stitcher.io/blog/html-5-in-php-84#:~:text=The%20RFC%20originally%20aimed%20to%20keep%20these%20objects%20the%20same%20between%20the%20old%20and%20new%20implementation%2C%20but%20there%20turned%20out%20to%20be%20too%20many%20differences)

And from https://wiki.php.net/rfc/opt_in_dom_spec_compliance:

> Migration will unfortunately not be trivial for everyone because many users rely on behaviour that was not intended by spec, or rely on bugs. Furthermore, there are userland libraries that currently work with the old classes and won't be able to support the old and new classes at the same time easily because of type and behaviour differences. So I expect the migration of the ecosystem to take a long time. There's a high chance that the migration of all old code won't happen until PHP versions older than 8.4 are EOL. 

and

> Therefore, a conscious decision is to not deprecate the old DOM classes anytime soon. New code can use the new DOM classes, while old code can keep using the old classes and migrate at their own pace. 

... so there is even nothing _pushing_ users to use the new classes.

**Comment by ThomasLandauer** [comment]
> So, why would you like to change it? Is it because it "looks more modern" or is "better HTML5 style"? To prevent validators from emitting notices that bash Symfony?

Yeah, that's it :-)

**Comment by mpdude** [comment]
One more thought: since this might be a breaking change for people that have to process the resulting HTML with the XML/DOM extension, I would not do it in a minor release. ~Also, I have no idea what a sensible deprecation strategy might look like.~ So maybe it would need a flag to opt-in to the new mode, and switches in the Twig templates to omit the self-closing behavior.
