### ISSUE TITLE
[DependencyInjection] Add configuration option to disable autowiring of optional parameters

### ISSUE THREAD

**Issue by DaDeather** [symfony/symfony#53640]
### Description

In the current state when using autowiring the `AutowirePass` tries to resolve any argument/parameter that is being requested whether it's optional or not:

https://github.com/symfony/symfony/blob/d621936e8c638247de4c5d1cd75cc5ff55b84c3e/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L287-L299

This may lead to unexpected behavior. Lets take the `RateLimitFactory` as an example:
https://github.com/symfony/symfony/blob/d621936e8c638247de4c5d1cd75cc5ff55b84c3e/src/Symfony/Component/RateLimiter/RateLimiterFactory.php#L33-L42

Currently if we'd define this as a service like this:
```php
$servicesConfigurator
    ->defaults()
    ->autowire();

$servicesConfigurator
    ->set('someServiceName')
    ->class(RateLimiterFactory::class)
    ->args([
        '$config' => ...,
        '$storage' => ...,
    ])
    ->public();
```

This service would now be defined with the argument`$lockFactory` being passed as null (it's default value).

BUT if one would now also define a `LockFactory` service this service would be automatically injected without any change to the service definition of `RateLimiterFactory` causing most likely unexpected behaviour:
```php
$servicesConfigurator
    ->set(LockFactory::class)
    ->public();
```

So for this reason I'd like to introduce a new configuration flag for autowiring to disable the implicit autowiring of optional parameters.

This would then allow us to reduce unexpected side effects happening just because of if someone decides to define a service which may be a optional parameter of another autowired service.

**Comment by nicolas-grekas** [comment]
I've never hit this issue. Did you?
Can you try using `#[Autowire(null)]`? That might be enough to cover your need.

**Comment by DaDeather** [comment]
> I've never hit this issue. Did you? Can you try using `#[Autowire(null)]`? That might be enough to cover your need.

We did encounter this issue in our service container definitions. Right now we're on the transition from explicitly defined services to autowiring and that's where we encountered this.
So after applying the first step of activating `autowire()` on the service container configuration we encountered locking in our rate limiter due to the `LockFactory` which was defined as a service somewhere lead to an implicit injection into the `RateLimiterFactory`.

And yeah sure explicitly setting `null` would solve the issue as well (wether as an attribute or in the service definition) but right now we're not using attributes as well (as mentioned we're working towards these).

But not defining that explicitly leads to this unexpected side effect.

**Comment by derrabus** [comment]
> And yeah sure explicitly setting `null` would solve the issue as well

This would be my preferred way. If we're not happy with what is injected via autowiring, we set the constructor argument explicitly. Whether we want a _different_ service or just `null` at all does not make a difference to me in that regard.

> right now we're not using attributes as well

Okay, but that's a choice you've made. There's nothing stopping you from using an attribute for that particular case, right? And even if you don't use attributes, you can achieve the same thing by defining the service in your services.yaml (or whatever file you use to configure the DI).

The question is, does this problem occur on such a big scale in your case that an additional config parameter on Symfony's side (and the additional complexity that it brings) is justified? I'm not yet convinced we need this feature.

**Comment by DaDeather** [comment]
> > And yeah sure explicitly setting `null` would solve the issue as well
> 
> This would be my preferred way. If we're not happy with what is injected via autowiring, we set the constructor argument explicitly. Whether we want a _different_ service or just `null` at all does not make a difference to me in that regard.

I totally agree but shouldn't the default behavior rather say "hey you may have forgotten to define something here" instead of just "injecting" it then? So handling optional arguments as somewhat like a "unhandled autowiring" exception?

This way `null` or the class is automatically injected without the knowledge of the developer.

So from my POV using the default value as the value being injected unless specified otherwise would be rather expected instead of injecting the class that's specified IF available (which could change at any point of development).

> > right now we're not using attributes as well
> 
> Okay, but that's a choice you've made. There's nothing stopping you from using an attribute for that particular case, right? And even if you don't use attributes, you can achieve the same thing by defining the service in your services.yaml (or whatever file you use to configure the DI).
> 
> The question is, does this problem occur on such a big scale in your case that an additional config parameter on Symfony's side (and the additional complexity that it brings) is justified? I'm not yet convinced we need this feature.

In terms of the complexity I definitely agree and don't actually like what I'm trying to add here but the actual other possibility would be a BC break by changing the default behavior.

And yes from my POV this can cause issues on a big scale depending on the usage of optional object instance injections.

**Comment by DaDeather** [comment]
@derrabus let's take another example:

Let's take third party dependencies which may be used in the code base and which register services.

If we'd declare the `LockFactory` as a Service and someday why so ever a third party service (let's call it `SomeService`) adds a optional argument for `?LockFactory $lockfactory = null` as a dependency which wasn't there before.

Then this `LockFactory` would be injected without any notice of the developer leading to possible unexpected behavior right?

And we wouldn't be able to use attributes on the third party service but would have rather to define it somewhere else in the config files or whatever. But for this we would first have to know that this particular dependency was now added...

**Comment by nicolas-grekas** [comment]
IMHO we should do nothing on Symfony's side: the rule is clear, of course you need to learn it and deal with it.
In this case, I'd say the issue comes from defining this `LockFactory` . Remove it and everything is back to super-predictible behavior.
Or use explicit null values, but that'd be a workaround for an alias that shouldn't exist in the first place IMHO.

**Comment by nicolas-grekas** [comment]
My comment is a bit stupid - LockFactory is an alias provided by Symfony... :grimacing: 
I still think this looks like an edge case that doesn't need a change in Symfony because it's too rare to hit.

**Comment by DaDeather** [comment]
I understand the point and it's really probably an edge case right now and also defining things as services which may not be intended to be makes also sense.

But also I still think there's quite the risk of side effects whether in terms of unexpected injection to third party changes.

And as mentioned I find this change intrusive as well. But I also think reducing this unpredictable behavior should be taken into account for the future :see_no_evil:.

Until then I'll close this issue and pull request :+1:.

Thanks for looking into it and for your feedback though!
