### ISSUE TITLE
Missing scheme when generating path in twig with host in controller top annotation

### ISSUE THREAD

**Issue by changuelsami** [symfony/symfony#53662]
### Symfony version(s) affected

5.4.34

### Description

Hi,

I'm using Symfony 5.4.34 and Docker, I have a main domain and a sub-domain, each one have his own routes so in each controller I'm using this :
```php
/**
 * @Route("/", host="foo.bar", priority="1")
 */
final class FooController extends AbstractController
{
    /**
     * @Route("/url", name="url")
     */
    public function organismesAgrees(): Response
    { ...}
```
And...
```php
/**
 * @Route("/", host="sub.foo.bar", priority="1")
 */
final class SubFooController extends AbstractController
{
    /**
     * @Route("/url2", name="url2")
     */
    public function organismesAgrees(): Response
    { ...}
```

This is my services.yaml extract :
```yaml
parameters:
    router.request_context.scheme: 'https'
    ...
```

Today path() generates URLs without scheme ! Am I missing something ? It works fine if I remove host property from annotation.
I.e. in a twig file, {{path('url')}} generates  `/url`, what I need is `http://foo.bar/url` ! {{path('url2')}} generates `//sub.foo.bar/url2`, what I need is `http://sub.foo.bar/url` ! 

Adding schemes={"https"} in the top annotation of each controller works locally, but not on prod server :(

### How to reproduce

Create two controllers, define a top annotation and add host annotation : 
```php
/**
 * @Route("/", host="foo.bar", priority="1")
 */
final class FooController extends AbstractController
{
    /**
     * @Route("/url", name="url")
     */
    public function organismesAgrees(): Response
    { ...}
```
And...
```php
/**
 * @Route("/", host="sub.foo.bar", priority="1")
 */
final class SubFooController extends AbstractController
{
    /**
     * @Route("/url2", name="url2")
     */
    public function organismesAgrees(): Response
    { ...}
```

In the twig add links to each controller : 
```twig
<a href="path('url1')">Llink to URL 1 </a>
<a href="path('url2')">Llink to URL 2 </a>
```

### Possible Solution

Adding schemes={"https"} in the top annotation of each controller works locally, but not on prod server :(

**Comment by xabbuh** [comment]
What are the paths generated for your two examples? What is the host that you use to access your application?

**Comment by changuelsami** [comment]
@xabbuh I've updated the issue details : 
in a twig file, `{{path('url')}}` generates `/url`, what I need is `http://foo.bar/url` ! `{{path('url2')}}` generates `//sub.foo.bar/url2`, what I need is `http://sub.foo.bar/url` !

**Comment by xabbuh** [comment]
I guess what you in fact need to use is the `url()` function in your Twig templates instead of `path()` then.
