### ISSUE TITLE
Can't deserialize previously normalized empty Email

### ISSUE THREAD

**Issue by hunhejj** [symfony/symfony#53664]
### Symfony version(s) affected

6.4.0

### Description

When trying to deserialize an empty email I get the following exception:

> Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "message" attribute for class "Symfony\Component\Mime\Email" must be one of "iterable", "string" ("null" given).

The exception trace is: 
```
symfony/serializer/Exception/NotNormalizableValueException.php:32
symfony/serializer/Normalizer/AbstractObjectNormalizer.php:616
symfony/serializer/Normalizer/AbstractObjectNormalizer.php:382
symfony/serializer/Normalizer/MimeMessageNormalizer.php:107
symfony/serializer/Serializer.php:247
```

### How to reproduce

Normalized data:

```
[
    'text' => null,
    'textCharset' => null,
    'html' => null,
    'htmlCharset' => null,
    'attachments' => [],
    'cachedBody' => null,
    'headers' => [],
    'body' => null,
    'message' => null,
]
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?
