### ISSUE TITLE
[AssetMapper] Asset Mapper fail after deleting "assets" folder

### ISSUE THREAD

**Issue by Xbirdfr** [symfony/symfony#53669]
### Symfony version(s) affected

7.*

### Description

After compiling assets, if we delete the original assets folder (I don't want it on prod), symfony crash with :

An exception has been thrown during the rendering of a template ("The asset mapper directory "assets/" does not exist.").

`{% block importmap %}{{ importmap('app') }}{% endblock %}`

### How to reproduce

- Setup a new symfony project
- create a controller to display a page
- compile assets
- check your application (it's works)
- delete the assets folder
- check your application (it's don't work anymore)

```
symfony new --webapp assetmappertest .
symfony console make:controller home
symfony console assets:install public
symfony console importmap:install
symfony console asset-map:compile
```

**Comment by fracsi** [comment]
This also effects 6.4 as well. Currently you can use a simple workaround, just leave or create an empty assets directory.

**Comment by Xbirdfr** [comment]
assets folders + assets/controllers are needed at least (put a .empty do the trick)

**Comment by rynhndrcksn** [comment]
It looks like this error is thrown from `AssetMapperRepository.php`, specifically [line 164](https://github.com/symfony/symfony/blob/e00c12e6e878752e165817e99228d536299b087b/src/Symfony/Component/AssetMapper/AssetMapperRepository.php#L164).

I've verified the following check fixes this, I'm unsure if it's the solution that the core Symfony team would want though, or if they'd want a more thorough check (like if this condition is true and `public/assets/` exists or something):
```php
if ($_ENV['APP_ENV'] !== 'dev' && $path === 'assets/') {
    continue;
}
```

**Comment by nicolas-grekas** [comment]
I closed your PR a bit too quickly @rynhndrcksn, sorry about that. This cannot be the correct approach to me.
Maybe we could remove those exceptions in getDirectories? Or throw them only when $debug is on (the flag would be passed as a constructor argument).
WDYT @weaverryan?

**Comment by rynhndrcksn** [comment]
No problem @nicolas-grekas ! I didn't know that hard coded values weren't okay, my apologies. I'll be happy to make the necessary changes once we get feedback from Ryan and make a new PR if that's okay!

**Comment by weaverryan** [comment]
Indeed, you should be able to delete `assets/` if you've compiled everything. If that's not possible (obviously it's not yet!) we should make it possible! The exception exists to help users not do a typo and then have trouble figuring out what they did wrong. In the PR #53677, I would:

A) Add a new argument to `AssetMapperRepository` constructor: `$strictMode = true`. 
B) Add a new abstract arg after this one - https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php#L77 - called something like `strict mode`
C) Pass `%kernel.debug%` to this new argument here https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1329
D) Finally, back in `AssetMapperRepository`, use `$this->strictMode` to determine if the exception should be thrown.

Cheers!

**Comment by rynhndrcksn** [comment]
Ah okay, that makes a lot of sense, thank you Ryan! I'll get these modifications made and pushed later today!
