### ISSUE TITLE
Remove deprecation for the "doctrine.event_subscriber" tag

### ISSUE THREAD

**Issue by ludekbenedik** [symfony/symfony#53675]
### Description

Hi,
since symfony/doctrine-bridge 6.3: Registering "MySubscriber" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.

Is there a reason to deprecate the `doctrine.event_subscriber` tag? The `Doctrine\Common\EventSubscriber` class is not deprecated.

Motivation to keep the `doctrine.event_subscriber` tag:
1. The `doctrine.event_listener` tag is not deprecated.
2. Without the `doctrine.event_subscriber` tag, registering an event subscriber from a library requires the use of many `doctrine.event_listener` tags because the library does not depend on `DoctrineBundle`.

Please consider removing deprecation for the "doctrine.event_subscriber" tag.

Thanks

**Comment by nicolas-grekas** [comment]
Here is the issue with the rationale: https://github.com/symfony/symfony/issues/49586
Closing as we won't get back.
