### ISSUE TITLE
[MonologBridge] Backport support for Monolog 3 for Symfony 5.4

### ISSUE THREAD

**Issue by gaelreyrol** [symfony/symfony#53699]
### Description

Hi,

Would it be considerable to backport the support of Monolog `^3.0` for Symfony `^5.4` releases?

If yes, I will be happy to submit a PR based on these commits from the 6.4 branch:
- https://github.com/symfony/monolog-bridge/commit/5a83c267228bbddfb38258cb9d056b1c503a648a
- https://github.com/symfony/monolog-bridge/commit/40e8f8a2897f8c69c0b06bb60a7d6ecc7255470f
- https://github.com/symfony/monolog-bridge/commit/b9ec3108737c8c45a98f6970ee40214c01d4f2ed

**Comment by derrabus** [comment]
Can you upgrade your MonologBridge to 6.4 instead?

**Comment by gaelreyrol** [comment]
> Can you upgrade your MonologBridge to 6.4 instead?

@derrabus I tried but it conflicts with `symfony/security-core:<6.0`.

**Comment by derrabus** [comment]
Can you try to figure out why? Maybe we can widen that constraint.

**Comment by gaelreyrol** [comment]
@derrabus This conflict has been added with this commit: https://github.com/symfony/monolog-bridge/commit/b42815e2187599bdd3cf9375f0df1ad282bb9c3c which seems to come from the deprecation of `Symfony\Component\Security\Core\Authentication\Token\TokenInterface::getUsername()` method since Symfony 5.4 in favor of the method `getUserIdentifier()`. 

Maybe if we loosen the constraint to `symfony/security-core:<5.4` it could work.

**Comment by derrabus** [comment]
> Maybe if we loosen the constraint to `symfony/security-core:<5.4` it could work.

If we did that, we would need to take back parts of that change you've linked. Being compatible with Security Core 5.4 also means being compatible with `UnserInterface` implementations that don't implement `getUserIdentifier()` yet. That might still be the lesser evil compared to backporting Monolog 3 support to 5.4.

Can I get a second opinion on this. @nicolas-grekas or @wouterj maybe? 🙏🏻

**Comment by nicolas-grekas** [comment]
I'm fine with postponing https://github.com/symfony/monolog-bridge/commit/b42815e2187599bdd3cf9375f0df1ad282bb9c3c

**Comment by derrabus** [comment]
#53720
