### ISSUE TITLE
[console] ansi support detection is broken

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#53693]
### Symfony version(s) affected

v6.4.3

### Description

When running a symfony CLI app, the output is in black and white. I was in color before.

### How to reproduce

I updates symfony/console on [castor](https://github.com/jolicode/castor/commit/d6f4d57f84d9b311b4f0bf3dca53a869a7c77ac1) and now when I run `castor` is output is without colors 

Note: I use ubuntu 22.04.3 LTS, up to date + tmux. It's broken only in tmux or screen

### Possible Solution

#53576 is realated ? cc @theofidry

**Comment by theofidry** [comment]
It definitely is related to #53576. I however think the rational of it is still sound, so what I'm curious about is why with tmux or screen `stream_isatty($this->stream)` returns `false`

**Comment by chalasr** [comment]
@lyrixx Can you please confirm #53707 fixes the issue?

**Comment by lyrixx** [comment]
It works:

* in tmux
* in screen
* directly in my terminal

👏🏼

**Comment by melroy89** [comment]
> @lyrixx Can you please confirm #53707 fixes the issue?

That PR is delivered in branch 5.4? This will then also be synced to 6 / 7??
