### ISSUE TITLE
Using symfony/console (v5.4.35) with Laravel 8 I still get the exception `An option shortcut cannot be empty.` when using php artisan.

### ISSUE THREAD

**Issue by vivdesign** [symfony/symfony#53696]
Using symfony/console (v5.4.35) with Laravel 8 I still get the exception `An option shortcut cannot be empty.` when using php artisan.

Reverting back to symfony/console (v5.4.34) the exception is not thrown anymore. Any suggestions?

Thanks.

_Originally posted by @dneykov in https://github.com/symfony/symfony/issues/53514#issuecomment-1918768018_

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by vivdesign** [comment]
No time to do so I reverted to 5.4.34 and it is fine, as I see this issue is in all your version you will soon get a flood of issue about it so I guess it is in your best interest to try it yourselves.

**Comment by dneykov** [comment]
I just tried a fresh install of Laravel 8(it installs 5.4.35) and the issue is not present there but it's present on existing application.

**Comment by derrabus** [comment]
> No time to do so I reverted to 5.4.34 and it is fine, as I see this issue is in all your version you will soon get a flood of issue about it so I guess it is in your best interest to try it yourselves.

Reading this comment, I think it's in my best interest to close this issue.
