### ISSUE TITLE
[Mailer] Socket stream: Implict conversion from float 0.1 to int loses precision

### ISSUE THREAD

**Issue by aleksejs1** [symfony/symfony#53705]
### Symfony version(s) affected

6.4.2

### Description

Wrong parameter type for stream_set_timeout() [here](https://github.com/symfony/mailer/blob/7.0/Transport/Smtp/Stream/SocketStream.php#L163C9-L163C27).

[PHP docs](https://www.php.net/manual/en/function.stream-set-timeout.php)
`stream_set_timeout(resource $stream, int $seconds, int $microseconds = 0): bool`

### How to reproduce

Run `$mailer->getTransporter()->setTimeout(0.1);` with smtp configuration.

### Possible Solution

```
stream_set_timeout($this->stream, (int) $timeout, (int) ((float) $timeout - (int) $timeout) * 1000000);
```

**Comment by derrabus** [comment]
Please send a PR.

**Comment by aleksejs1** [comment]
https://github.com/symfony/mailer/pull/19
