### ISSUE TITLE
[AssetMapper] Give better error message if `importmap_polyfill` is set to `true`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#53725]
### Symfony version(s) affected

7.0.2

### Description

When setting the `importmap_polyfill` setting to `true` (instead of an entry point's name), the resulting error message reads:
> An exception has been thrown during the rendering of a template ("The JavaScript module polyfill was not found in your import map. Either disable the polyfill or run "php bin/console importmap:require "1"" to install it.").

Now, when actually doing `php bin/console importmap:require 1`, there is indeed something added called `1`.

It would be nice if the error message could be improved for this case.

### How to reproduce

See above.

### Possible Solution

If you think that it's not worth it, just close here :-)
The `importmap_polyfill` setting is properly documented at https://symfony.com/doc/current/frontend/asset_mapper.html#framework-asset-mapper-importmap-polyfill

**Comment by smnandre** [comment]
> Now, when actually doing php bin/console importmap:require 1, there is indeed something added called 1.

There are some packages resolved on jsdelivr / npm with the name "1" or "2" ... 
* https://cdn.jsdelivr.net/npm/1@0.1.2/
* https://cdn.jsdelivr.net/npm/2@3.0.0/

So nothing to do on this side...

Concenring the importmap_polyfill, it relates to your [other issue](https://github.com/symfony/symfony/issues/53726) i guess ?

**Comment by ThomasLandauer** [comment]
My scenario was: I copied the entire `config/packages/asset_mapper.php` file from another project. But this time I wanted to enable the polyfill, so I figured to change the `$assetMapperConfig->importmapPolyfill(false);` line to `true`, which apparently gets translated to `1`...

I thought this might be a trap into which other lazy developers could run too. So if there's an easy fix, you could maybe forbid `true` as value (or so...)
On the other hand, it's documented properly, so if you don't see any easy fix, just close here.

**Comment by javiereguiluz** [comment]
I agree this could be confusing. We could make `->importmapPolyfill(true)` throw a better error message ... or allow `->importmapPolyfill(true)` and make it use the default shim.

**Comment by smnandre** [comment]
To treat true / null / "not set" as default value, while still displaying the default in "sf debug:config framework asset_mapper" ..  

i will need a hand..  i can't find a way to do this without repeating the value in the config.

(poke @weaverryan  ? 👼 )

If we want to throw an error, it's easier.

**Comment by ThomasLandauer** [comment]
IMO: Then just throw the error! Anything that prevents people from actually doing `php bin/console importmap:require 1` is good enough :-)

**Comment by smnandre** [comment]
I wont preventing anyone from running `php bin/console importmap:require 1` manually.

What i can do is throw an error if someone set "true" as value for importmap_polyfill.

Is that ok for you ?

**Comment by ThomasLandauer** [comment]
Sure!
