### ISSUE TITLE
[AssetMapper] Setting a value for `importmap_polyfill` is breaking it

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#53726]
### Symfony version(s) affected

7.0.2

### Description

When *not* setting anything for `importmap_polyfill`, I'm getting:
```html
<script type="importmap">
{
    "imports": {
        "app": "/assets/app-3ef66d09e234f599444c949392af9194.js",
        // ...
    }
}
</script>
<!-- ES Module Shims: Import maps polyfill for modules browsers without import maps support -->
<script async src="/assets/vendor/es-module-shims/es-module-shims.index-c0782a61961901e7a6d0c0f3b5e61cb5.js"></script>
```
... which is fine.

But when setting `$assetMapperConfig->importmapPolyfill('app');`, the `app` entry is missing from my importmap and the second `<script>` changes to:
```html
<!-- ES Module Shims: Import maps polyfill for modules browsers without import maps support -->
<script async src="/assets/app-3ef66d09e234f599444c949392af9194.js"></script>
```
... which is not working. In the console, I'm getting:
> Uncaught SyntaxError: import declarations may only appear at top level of a module

### How to reproduce

See above.

### Additional Context

Besides, the documentation at https://symfony.com/doc/current/frontend/asset_mapper.html#framework-asset-mapper-importmap-polyfill is ambiguous:

> You can pass the key of an item in `importmap.php` or false to disable the polyfill loading.

... sounds like I need to put in something like `app`.

But the code sample just below:

```yaml
# importmap_polyfill: 'my_import_map' # ... or pass an importmap name
```
... looks like I need to put in the name of my `importmap.php` file, i.e. `importmap`.

**Comment by smnandre** [comment]
> But when setting `$assetMapperConfig->importmapPolyfill('app');`, the `app` entry is missing from my importmap and the second `<script>` changes to:
> 
> ```
> 
> <script async src="/assets/app-3ef66d09e234f599444c949392af9194.js"></script>
> ```

You cannot use your entrypoint as a polyfill, as the polyfill is mainly there to load your entrypoint and its depedencies when the browser is not compatible with importmap.

If you want to use a custom polyfill, you must import/require it locally via the command described [here](https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages).

And the name you used when you imported is the name you should set in the yaml configuration.

The sentense in the yaml example could be

```yaml

    importmap_polyfill: 'custom_polyfill' # ... or pass the name of the polyfill (used as key in your importmap.php file)
```

**Comment by ThomasLandauer** [comment]
OK, so not setting `importmap_polyfill` is the same as setting it to `es-module-shims`? Is that right? => I think that's the piece I was missing...

**Comment by smnandre** [comment]
Yes that's right

```bash
php bin/console config:dump framework asset_mapper
```

```yaml
    # The importmap name that will be used to load the polyfill. Set to false to disable.
    importmap_polyfill:   es-module-shims
```

**Comment by ThomasLandauer** [comment]
OK, thanks, I opened https://github.com/symfony/symfony-docs/pull/19475 for the docs.

So I'm closing here.
