### ISSUE TITLE
phpunit 11 incompatibility with symfony WebTestCase

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#53731]
### Symfony version(s) affected

6.4.*

### Description

Just tried out the new phpunit 11 and got the followiong fatal error:

> Fatal error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint

### How to reproduce

1. install phpunit11 in your project,
2. create a testcase extending WebTestCase
3. run test

**Comment by derrabus** [comment]
Which PHP version is this?

**Comment by mmarton** [comment]
PHP 8.2.15 (cli) (built: Jan 19 2024 23:39:18) (NTS)

**Comment by derrabus** [comment]
~~Do you have the possibility to try this on PHP 8.3?~~

edit: Nevermind, that shouldn't make a difference. 😞

**Comment by stof** [comment]
@sebastianbergmann turning classes as readonly class is a BC break that will make it impossible to support 2 versions of PHPunit easily, as it will require conditional class declarations for all custom constraints.

**Comment by derrabus** [comment]
I thought, PHP 8.3 would allow non-readonly classes to extend readonly ones, but that proposal was rejected apparently: https://wiki.php.net/rfc/readonly_amendments

**Comment by mmarton** [comment]
Tried it with PHP 8.3.2 (cli) (built: Feb  1 2024 02:00:33) (NTS)
result is the same

**Comment by stof** [comment]
As said, the RFC has been rejected, so this is not surprising.

I reported the undocumented BC break to phpunit. Let's see how phpunit handles it.

**Comment by sebastianbergmann** [comment]
[I handled it](https://github.com/sebastianbergmann/phpunit/issues/5690#issuecomment-1924264985), thank you for bringing this to my attention.

**Comment by mmarton** [comment]
closing as fixed. Thank you @sebastianbergmann
