### ISSUE TITLE
Doctrine ORM V3 Support 

### ISSUE THREAD

**Issue by hantsy** [symfony/symfony#53752]
### Description

There is a PR which tries to migrate to the latest Doctrine ORM V3.

But failed, it seems there are incompatibility with the existing Symfony Doctrine integration.

https://github.com/hantsy/symfony-rest-sample/actions/runs/7769233747/job/21188074338

```bash 
Run php ./bin/console doctrine:schema:create -n

In MappingException.php line 555:
                                                                               
  You have specified invalid cascade options for App\Entity\Post::$comments:   
  'merge'; available options: 'remove', 'persist', 'refresh', and 'detach'     
                                                                             
```

### Example

Check https://github.com/hantsy/symfony-rest-sample/pull/350

**Comment by xabbuh** [comment]
That’s not related to Symfony. The invalid `cascade` option Doctrine complains about is in your own code.
