### ISSUE TITLE
[AssetMapper] CSS files are not preloaded

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#53795]
### Symfony version(s) affected

6.4

### Description

As explained in the docs (https://symfony.com/doc/current/frontend/asset_mapper.html#performance-understanding-preloading) the `<link>` tag of CSS files should have the `rel="preload"` attribute.

But, I can't see that attribute. We need it in order for Cloudflare to turn those `<link>` into early hints. See https://developers.cloudflare.com/pages/configuration/early-hints/#2-automatic-link-header-generation

### How to reproduce

Visit any page of https://symfony.com and browse the source code of the page.

**Comment by smnandre** [comment]
The preload tag concern only JS files.

> Additionally, if the [WebLink Component](https://symfony.com/doc/current/web_link.html) is available in your application, Symfony will add a Link header in the response to preload the CSS files.

Do you have the WebLink component installed ?

**Comment by javiereguiluz** [comment]
I was missing the Weblink component. Thank you Simon and sorry for the noise!
