### ISSUE TITLE
[Framework bundle] Cleanup error and exception handlers on Kernel shutdown

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#53812]
### Symfony version(s) affected

7.0.0

### Description

PHPUnit 11 checks for any leftovers in error handlers https://github.com/sebastianbergmann/phpunit/pull/5619

### How to reproduce

Run `FrameworkBundle->boot()` in phpunit test.

https://github.com/symfony/symfony/blob/815df931dca4663a6375e205b0fdf6e546ebfa75/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L98

It results in `Test code or tested code did not remove its own exception handlers` thrown by phpunit.

### Possible Solution

Introduce `FrameworkBundle::shutdown()` that would cleanup error handler set in `boot()`. IMO it's reasonable to have some cleanup in shutdown() of things initiated in boot().

**Comment by derrabus** [comment]
Isn't this something that `WebTestCase` could handle?

**Comment by simPod** [comment]
IMO it should not be bound to a sf test case. Users usually extend their testcase and cannot extend another one.

It should be something that can be triggered via composition, not inheritance.

**Comment by derrabus** [comment]
This issue is a blocker for PHPUnit 11 in any Symfony project that uses `KernelTestCase` or `WebTestCase`. Given that PHPUnit comes with its own error handler, maybe the solution would be to opt out of Symfony's own error handler when booting the kernel for functional tests?

**Comment by simPod** [comment]
> that uses KernelTestCase or WebTestCase

this is not a root cause. I'd correct that to:

> This issue is a blocker for PHPUnit 11 in any Symfony project that uses Kernel in tests.

E.g. for me the test maintenance is much easier when I'm not relying on SF testcases so I can extend my own leaner testcase. I use Kernel via composition in tests.

So the root cause is that there's no way to cleanup after Kernel, not some test case.

**Comment by olifrieda** [comment]
Same issue "Test code or tested code did not remove its own exception handlers" here with

* PHP 8.2.15
* Symfony 6.4.3
* phpunit 11

**Comment by rubenrubiob** [comment]
I had the same problem with Symfony 6.4 and PHPUnit 11. I temporarily solved it by calling this method in the `tearDown` of my base test case (which extends from `KernelTestCase` or `WebTestCase`):

```php
protected function restoreExceptionHandler(): void
{
    while (true) {
        $previousHandler = set_exception_handler(static fn() => null);

        restore_exception_handler();

        if ($previousHandler === null) {
            break;
        }

        restore_exception_handler();
    }
}
```

The `tearDown` looks like this:

```php
protected function tearDown(): void
{
    parent::tearDown();

    $this->restoreExceptionHandler();
}
```

It is based on what Laravel did on their testsuite: https://github.com/laravel/framework/pull/49622/files

Maybe the solution is to call a similar method in the `tearDown` of `KernelTestCase` and `WebTestCase`?

**Comment by simPod** [comment]
Currently, I cleanup exceptions like this:

```php
        $res = [];

        while (true) {
            $previousHandler = set_exception_handler(static fn () => null);
            restore_exception_handler();

            if (
                is_array($previousHandler)
                && $previousHandler[0] instanceof \Symfony\Component\ErrorHandler\ErrorHandler
                && $previousHandler[1] === 'handleException'
            ) {
                restore_exception_handler();

                continue;
            }

            if ($previousHandler === null) {
                break;
            }

            $res[] = $previousHandler;
            restore_exception_handler();
        }

        $res = array_reverse($res);

        foreach ($res as $handler) {
            set_exception_handler($handler);
        }
```
The same for errors

**Comment by frankdekker** [comment]
A different workaround, seeing as the Symfony/Errorhandler is a singleton and will only register once, is to register the error handler _before_ phpunit memorizes all the existing error handlers. This way the error handler Symfony register's is not new.

Create (or modify) `/tests/bootstrap.php`:
```php
<?php
declare(strict_types=1);

use Symfony\Component\ErrorHandler\ErrorHandler;

ErrorHandler::register(null, false);
```

and in `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.0/phpunit.xsd"
         bootstrap="tests/bootstrap.php">
...
</phpunit>
```

**Comment by derrabus** [comment]
@frankdekker is right, the error handler registered by FrameworkBundle would not replace the active error handler. PHPUnit already registers its own error handler and that one is still active at the end of the test. So we're good here.

The problem which PHPUnit reports is about the _exception handler_. Yes, error handler and exception handler are two different things. And yes, it's super confusing that Symfony has a method called `ErrorHandler::register()` that registers an error handler **and** an exception handler. 😓 

PHPUnit on the other hand does not register an exception handler and even if it did, that handler would be wrapped by `ErrorHandler::register()` which PHPUnit would still rightfully complain about.

But. `ErrorHandler` won't replace the exception handler if `ErrorHandler`**already is** the current exception handler. This means, we can simplify @frankdekker's bootstrap script like this:

```php
<?php

declare(strict_types=1);

use Symfony\Component\ErrorHandler\ErrorHandler;

require dirname(__DIR__).'/vendor/autoload.php';

set_exception_handler([new ErrorHandler(), 'handleException']);
```

That being said, this feels like a hack. Maybe we should add a way to opt out of the exception handler. In situations where the kernel is executed within a huge try/catch block (which a PHPUnit test basically is), that exception handler does not serve any purpose anyway.

**Comment by arderyp** [comment]
Same on latest 6.4.x with phpunit 11.0.4

**Comment by arderyp** [comment]
thanks very much @derrabus, you're very simple addition to my pre-existing `tests/bootstrap.php` resolved the issue:

```
use Symfony\Component\ErrorHandler\ErrorHandler;
set_exception_handler([new ErrorHandler(), 'handleException']);
```

I agree with you that, while simple, it does seem somewhat like a hack. I am wondering if the symfony maintainers plan to take on your suggestion, perhaps by offering a new config option to opt out of the error handler that defaults to `true` in the test environment.

**Comment by JE4GLE** [comment]
Will this issue be resolved by symfony or is it expected to add @derrabus solution to every project?

**Comment by derrabus** [comment]
> Will this issue be resolved by symfony or is it expected to add @derrabus solution to every project?

This will be resolved by whomever resolves it. Could be you?

**Comment by derrabus** [comment]
What if we stopped registering error handlers, exception handlers or shutdown functions of any kind in FrameworkBundle?

We do need this stuff way before the framework is booted, so whatever FrameworkBundle registers here, it does it way too late. This applies especially to exception handlers: They are meant to handle uncaught exceptions. The kernel however runs in a big try/catch, so at the time FrameworkBundle is booted, the need for an exception handler is more or less over.

In modern Symfony applications, the error handling should be set up by the runtime already. All that FrameworkBundle does is connecting the logger properly. The logic that registers an error handler or exception handler is usually dormant and causes trouble because PHPUnit tests run outside of the runtime.

**Comment by stof** [comment]
This would require deprecating the FrameworkBundle configuration settings that allow configuring the error handler though

**Comment by derrabus** [comment]
> This would require deprecating the FrameworkBundle configuration settings that allow configuring the error handler though

Would it? I mean, FWB can still connect to the error handler registered by the runtime and reconfigure it.

**Comment by flashx4u** [comment]
Recently created a new Project with the Lumen Framework and wrote Tests for it and got this Warnings:

\* Test code or tested code did not remove its own error handlers
\* Test code or tested code did not remove its own exception handlers

- PHP  8.3.3
- PhpUnit 11.0.6
- Lumen 10.0.3

To overcome this Problem I needed to put this in the TestCase Class:

```php

    protected function restoreExceptionHandler(): void
    {
        while (true) {
            $previousHandler = set_exception_handler(static fn() => null);
            restore_exception_handler();
            if ($previousHandler === null) {
                break;
            }
            restore_exception_handler();
        }
    }

    protected function restoreErrorHandler(): void
    {
        while (true) {
            $previousHandler = set_error_handler(static fn() => null);
            restore_error_handler();
            $isPhpUnitErrorHandler = ($previousHandler instanceof \PHPUnit\Runner\ErrorHandler);
            if ($previousHandler === null || $isPhpUnitErrorHandler) {
                break;
            }
            restore_error_handler();
        }
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        $this->restoreErrorHandler();
        $this->restoreExceptionHandler();
    }
```
I hope this helps others, too.

**Comment by derrabus** [comment]
> To overcome this Problem I needed to put this in the TestCase Class:

So the bootstrap one-liner [I posted earlier](https://github.com/symfony/symfony/issues/53812#issuecomment-1962740145) did not help?

**Comment by RobertIacoveciuc** [comment]
I just set up a clean Symfony 7. Same issue here.

`Test code or tested code did not remove its own exception handlers`

**Comment by derrabus** [comment]
Please, no more me-toos here. We know the issue exists and a workaround has been posted. Let's focus on solutions.

**Comment by nikophil** [comment]
@derrabus what if `KernelTestCase::ensureKernelShutdown()` would restore PHPUnit exception handler as well?

It would at least prevent the problem to occur for user, which uses `KernelTestCase`, but still, the problem raised [here](https://github.com/symfony/symfony/issues/53812#issuecomment-1936237826) by @simPod would remain...

The main problem with the workaround with `set_exception_handler()` in `bootstrap.php` is that deprecation warnings do not bubble up in PHPUnit output...

**Comment by derrabus** [comment]
> @derrabus what if `KernelTestCase::ensureKernelShutdown()` would restore PHPUnit exception handler as well?

Please explore that idea if you like. But since you ask me, I believe that not fiddling with the exception handler at all should be the way to go. We should not need our own exception handler during tests.

> The main problem with the workaround with `set_exception_handler()` in `bootstrap.php` is that deprecation warnings do not bubble up in PHPUnit output...

That's weird. It's the error handler that deals with deprecations, not the exception handler.

**Comment by nikophil** [comment]
> That's weird. It's the error handler that deals with deprecations, not the exception handler.

I know, but as soon as you boot the kernel in a "before class" hook no deprecation shows up...

For instance, this code does not display any deprecation:

```php
final class SomeTest extends KernelTestCase
{
    public static function setUpBeforeClass(): void
    {
        self::bootKernel(); // <== if this line is removed, the deprecation is displayed
    }

    public function testWithDeprecation(): void
    {
        trigger_deprecation('some/package', '1.0', 'test deprecation.');
        self::assertTrue(true);
    }
}
```

**Comment by uncaught** [comment]
uh, that explains why we keep missing out on deprecation notices. We use a lot of static setups that use the kernel

**Comment by nikophil** [comment]
I don't know if both problems are related. If Symfony's error handler is registered too soon, it would mute PHPUnit's error handler :shrug:

**Comment by arderyp** [comment]
> uh, that explains why we keep missing out on deprecation notices. We use a lot of static setups that use the kernel

Damn, me too.  Have I been unknowingly squashing deprecation warning for years 😳

**Comment by soyuka** [comment]
Based on @nikophil research I found out that booting the kernel on `BeforeClass` (not `Before`) works just fine and I get deprecations:

```php
use PHPUnit\Framework\Attributes\BeforeClass;

abstract class ApiTestCase extends KernelTestCase
{
    #[BeforeClass]
    public static function setupBeforeClass(): void
    {
        static::bootKernel();
    }
}
```

I haven't checked but I guess that phpunit sets up its error handler, then in `BeforeClass` we boot the kernel registering symfony's error handler that gets properly removed as `KernelTestCase::tearDown` calls `ensureKernelShutdown`. 

Probably not ideal but as the error handler check is done after each test I don't see any better solution yet.

/edit: after testing in depth this is not the correct solution, I had the symfony phpunit bridge still active, in a weird way this allowed to not throw errors related to https://github.com/sebastianbergmann/phpunit/pull/5619 with the phpunit bridge working

**Comment by soyuka** [comment]
After discussing this with @nikophil I found out that (by looking at https://github.com/sebastianbergmann/phpunit/blob/489040f5a752a47b3236f5998ec18a46e025f3d1/src/Framework/TestCase.php#L1907), only the `exception_handler` is an issue here as error handlers are correctly handled. My configuration has `ignoreSuppressionOfDeprecations="true"` as the `trigger_deprecation` method from Symfony uses the `@` prefix.

I quite like the idea at https://github.com/symfony/symfony/pull/54266 but the code looks too complicated, basically what I did is:

```php
    public function registerBundles(): array
    {
        $bundles = [
            new ApiPlatformBundle(),
            new FrameworkBundle(),
            new class extends Bundle
            {
                public function shutdown(): void
                {
                    restore_exception_handler();
                }
            }
        ];
```

I have a few suggestions to mitigate this issue:

- add a `$_SERVER` variable `ERROR_HANDLER_CLASS` just as we have the `KERNEL_CLASS` allowing anyone to replace that if needed
- have a `ErrorHandler::unregister` or a `shutdown` function that just calls `restore_exception_handler` but this looks too easy, @nicolas-grekas probably has use cases where it won't work :D
- find out why the **exception** handler isn't unregistered properly (or is registered too soon ?), it looks like the **error** handler is correctly removed according to phpunit's code after each test
- suggest an option on phpunit `<source backupActiveExceptionListeners="false">` as IMO this should be de-activable on phpunit

**Comment by alexander-schranz** [comment]
I stumbled over one test in @sulu which uses `$client->disableReboot();` and the `$client` instanced is passed from one test to another in that case the `shutdown` is not called and so not cleaned up.

What I also tried is adding following to the KernelTestCase:

```php
    /**
     * @internal
     */
    #[\PHPUnit\Framework\Attributes\After]
    public function __internalDisableErrorHandler(): void
    {
        \restore_exception_handler();
    }
```

But still has some issues with dataproviders in it.

Best result I got yet by adding it to the `ensureKernelShutdown` method:

```php
    /**
     * Shuts the kernel down if it was used in the test - called by the tearDown method by default.
     */
    protected static function ensureKernelShutdown()
    {
        if (null !== static::$kernel) {
            static::$kernel->boot();
            $container = static::$kernel->getContainer();
            static::$kernel->shutdown();

            if ($container instanceof ResetInterface) {
                $container->reset();
            }
        }

        if (static::$booted) {
            static::$booted = false;
            \restore_exception_handler();
        }
    }
```

and in the WebTestCase:

```php
    /**
     * @internal
     */
    #[\PHPUnit\Framework\Attributes\After]
    public function __internalDisableErrorHandler(): void
    {
        \restore_exception_handler();
    }
```

Strange is doing the __internalDisableErrorHandler in KernelTestCase makes the DataProviders still fail. Not doing `__internalDisableErrorHandler` makes test fails depending on `$this->client->disableReboot();`

**Comment by filjoseph1989** [comment]
> I had the same problem with Symfony 6.4 and PHPUnit 11. I temporarily solved it by calling this method in the `tearDown` of my base test case (which extends from `KernelTestCase` or `WebTestCase`):
> 
> ```
> protected function restoreExceptionHandler(): void
> {
>     while (true) {
>         $previousHandler = set_exception_handler(static fn() => null);
> 
>         restore_exception_handler();
> 
>         if ($previousHandler === null) {
>             break;
>         }
> 
>         restore_exception_handler();
>     }
> }
> ```
> 
> The `tearDown` looks like this:
> 
> ```
> protected function tearDown(): void
> {
>     parent::tearDown();
> 
>     $this->restoreExceptionHandler();
> }
> ```
> 
> It is based on what Laravel did on their testsuite: https://github.com/laravel/framework/pull/49622/files
> 
> Maybe the solution is to call a similar method in the `tearDown` of `KernelTestCase` and `WebTestCase`?

This works for me

**Comment by PierreAntoineGuillaume** [comment]
> > I had the same problem with Symfony 6.4 and PHPUnit 11. I temporarily solved it by calling this method in the `tearDown` of my base test case (which extends from `KernelTestCase` or `WebTestCase`):
> > ```
> > protected function restoreExceptionHandler(): void
> > {
> >     while (true) {
> >         $previousHandler = set_exception_handler(static fn() => null);
> > 
> >         restore_exception_handler();
> > 
> >         if ($previousHandler === null) {
> >             break;
> >         }
> > 
> >         restore_exception_handler();
> >     }
> > }
> > ```
> >   
> > The `tearDown` looks like this:
> > ```
> > protected function tearDown(): void
> > {
> >     parent::tearDown();
> > 
> >     $this->restoreExceptionHandler();
> > }
> > ```
> >   
> > It is based on what Laravel did on their testsuite: https://github.com/laravel/framework/pull/49622/files
> > Maybe the solution is to call a similar method in the `tearDown` of `KernelTestCase` and `WebTestCase`?
> 
> This works for me

That's what I have been doing in the tests/bootstrap.php, to run it exactly once.

```
$phpunitsHandler = set_error_handler(static fn() => null);
restore_exception_handler();
ErrorHandler::register(null);
set_error_handler($phpunitsHandler);
```

**Comment by nickjbedford** [comment]
I'm using Laravel 11 and PHP Unit 11 and nothing fixes this issue. I can only run my tests on PHP Unit 10. Is anyone still experiencing this?

```text
Test code or tested code removed error handlers other than its own

Test code or tested code removed exception handlers other than its own
```

**Comment by derrabus** [comment]
Yes, the issue still exists. And the workaround is documented in this thread.

**Comment by nickjbedford** [comment]
> Yes, the issue still exists. And the workaround is documented in this thread.

I tried these fixes and they didn't fix the issue for me. I'm not sure why. Our codebase/test suite originates all the way from Laravel 5.8 so perhaps there's something there (though we've done our best to continuously modernise the codebase).

**Comment by arderyp** [comment]
@nicolas-grekas thanks for the merge, but I am somewhat confused.  The [commit](https://github.com/symfony/symfony/commit/de1a6ac184b6a804fc293e2014391f4f4d913985) mentions it was merged into 5.4 branch 2 weeks ago, but the latest 5.4 release is 3 weeks old (5.4.44).  And no indication as to whether the fix will also be merged into 6.4 and 7.x. Can you clarify, or am I by chance missing something? The latest `framework-bundle` 6.4.12 did not resolve this for me...

**Comment by xabbuh** [comment]
We regularly merge bugfixes up into all maintained branches which means that the fix will ship with the next patch releases of 5.4, 6.4 and 7.1.

**Comment by arderyp** [comment]
Ahh okay, thanks!!

**Comment by alexisLefebvre** [comment]
As xabbuh said, it has been merged to the 6.4 branch: https://github.com/symfony/symfony/commit/33050e310ca7484458f793ae41ca4db6891365cd

And the last release on `6.4.*` is older than this merge: https://github.com/symfony/symfony/releases?q=v6.4&expanded=true

So it's not yet available but it will come to 6.4 at some point, but I don't know the release process of the minor versions so I can't tell when.

**Comment by arderyp** [comment]
Thank you both for your patience with my silly question. I should have know, and think I did, but just forgot how the versioned branches work. Thanks again :)

**Comment by garak** [comment]
The patch is in the 6.4 branch now, but the problem remains.

**Comment by xabbuh** [comment]
@garak Can you then please create a small example application that allows to reproduce?

**Comment by mariusjp** [comment]
~~Can confirm @garak 's statement, just updated my project to Symfony 7.1.6;~~

~~After removing the hotfix:~~

```
require \dirname(__DIR__) . '/vendor/autoload.php';

// @todo: Remove temporary fix for the error handler for Symfony 7 in combination with PHPUnit 11
/* @see https://github.com/symfony/symfony/issues/53812 */
\set_exception_handler([new ErrorHandler(), 'handleException']);
```

~~I'm getting the same error again:~~
~~"Test code or tested code did not remove its own exception handlers"~~

~~I'm running PHPUnit 11.4.2.~~

I believe my statement here is not fair, it's very specific to my project, I can't seem to reproduce the problem, see:
https://github.com/symfony/symfony/issues/53812#issuecomment-2440802635

**Comment by xabbuh** [comment]
@mariusjp see https://github.com/symfony/symfony/issues/53812#issuecomment-2440102476

**Comment by mariusjp** [comment]
> @mariusjp see [#53812 (comment)](https://github.com/symfony/symfony/issues/53812#issuecomment-2440102476)

Fair point, I've tried a few different scenarios. All are working fine, so can only conclude it's a library that we are using that is interfering. Already tried a few, still can't reproduce. I'll let you know when I find something!

**Comment by alexander-schranz** [comment]
I did a short test by rebasing the @sulu [branch for PHPUnit 11](https://github.com/sulu/sulu/pull/7541) interesting is that currently in case of Sulu only the `@dev` versions seems to work so maybe something is not yet release on PHPUnit or may Symfony side:

 - `@dev`: https://github.com/sulu/sulu/actions/runs/11551062309/job/32147299859?pr=7541
 - `@stable`: https://github.com/sulu/sulu/actions/runs/11551062309/job/32147299604?pr=7541
 
**Update** Something seems to block the framework bundle upgrade. Intersting that I get on `@dev` still the `7.2.0-dev`:

<img width="435" alt="Bildschirmfoto 2024-10-28 um 10 36 38" src="https://github.com/user-attachments/assets/d4429f81-aad8-4123-97a4-3a8fc61ddf45">

> `symfony/framework-bundle v7.1.6 conflicts symfony/runtime (<6.4.13|>=7.0,<7.1.6)`

Found the issue in my case a update of `matthiasnoback/symfony-dependency-injection-test` was also needed it was downgrading some depndencies. `composer outdated` did help here. Maybe this helps others also.

**Comment by mmarton** [comment]
I've had similar issue that was caused by a workaround in zenstruck/foundry. Opened an issue there:
https://github.com/zenstruck/foundry/issues/711

**Comment by dozer111** [comment]
interesting.

this problem is absent on symfony 6.4, but exists in latest 7.2

**Comment by jmediatechnology** [comment]
I had the same problem. The project I was working on used some symfony components but not the symfony framework bundle. 
So I could solve the problem by installing `symfony/framework-bundle`. 

```
composer require symfony/framework-bundle:^7.3.3 -W
```
