### ISSUE TITLE
simple-phpunit does not install on new Symfony project

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#53841]
### Symfony version(s) affected

7.0

### Description

I'm running PHP 8.3 and can't install simple-phpunit

     Call to undefined method PHPUnit\Util\Xml\SchemaFinder::available()

### How to reproduce

```bash
symfony new phpunit-bug --webapp && cd phpunit-bug
composer require --dev symfony/phpunit-bridge
vendor/bin/simple-phpunit
```

```
4 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
24 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.
Call to undefined method PHPUnit\Util\Xml\SchemaFinder::available()

```

**Comment by tacman** [comment]
I'm confused.  Why do I want to use simple-phpunit and not phpunit?

I realize that installing 

      composer require --dev symfony/test-pack

works.  The Symfonycasts article on creating a reusable bundle references simple-phpunit, but maybe that's outdated.

**Comment by xabbuh** [comment]
I cannot reproduce. The steps above work for me.
