### ISSUE TITLE
JS import module fails

### ISSUE THREAD

**Issue by sQuarecoW** [symfony/symfony#53849]
### Symfony version(s) affected

6.4.3

### Description

When importing a module from a js file the import fails:

```javascript
import ThemeSwitcher from './js/themeSwitcher.js'
```

I get an error 404 and the file is missing from the importmap.

When I change the line to just import the file e.g. 
```javascript 
import './js/themeSwitcher.js'
```

it works, but then of course the source code doesn't work anymore.

### How to reproduce

In an entrypoint js file try to import a module from a different js file

**Comment by smnandre** [comment]
Could you share a little bit of your code/files there ? 

That could help to identify your problem and how to solve it.

**Comment by sQuarecoW** [comment]
Sure 😄

```/assets/admin/admin.js```:
```javascript
// base styles
import './styles/admin.scss'

// bootstrap's JS file
// require('bootstrap.js')
console.log('aaa')

// imports
import ThemeSwitcher from './js/themeSwitcher.js' //<<<
new ThemeSwitcher()

import './js/forms.ts' //<<< this works
// import './js/dashboard.ts'
```

```/assets/admin/js/themeSwitcher.js```:
```javascript
export default class ThemeSwitcher {
    // This is now a very simple file, just to test
    constructor() {
        console.log('themeswitcher');
    }
}
```




```/assets/admin/js/forms.ts```:
```typescript
// import the editor
import './editor.ts'
console.log('forms');
```


```/importmap.php```:
```php
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'admin' => [
        'path' => './assets/admin/admin.js',
        'entrypoint' => true,
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
];

```


<img width="419" alt="Untitled" src="https://github.com/symfony/symfony/assets/196524/3f09017c-fd08-4819-a03d-021117ac3660">


Edit: when I do ```php bin/console debug:asset``` the file shows up in the list:

```shell
 --------------------------------------------- ---------------------------------------------------- 
  Logical Path                                  Filesystem Path                                     
 --------------------------------------------- ---------------------------------------------------- 
  admin/js/themeSwitcher.js                     assets/admin/js/themeSwitcher.js                    
```

**Comment by smnandre** [comment]
@sQuarecoW If you remove the comment line just before the import, does it work ? (i think that should fix your problem)

@weaverryan i think there is a problem with the "isCommentedOut" method, as this code is detected as commented (i tried with the old and the new regexp, so it _should_ not be related)

```js
// imports
import ThemeSwitcher from './js/themeSwitcher.js'
```

**Comment by sQuarecoW** [comment]
Yes, this fixes the issue! Tnx for the fast action 😄
