### ISSUE TITLE
[HttpKernel] HttpKernel 5.4 is not compatibe with WebProfilerBundle 6.1

### ISSUE THREAD

**Issue by JoppeDC** [symfony/symfony#53883]
### Symfony version(s) affected

5.4

### Description

The 6.1 version of the profiler is not compatible with HttpKernel 5.4

In the 6.1 version of the profiler, the `hasXdebugInfo` function call was added to the [`config.html.twig` template](https://github.com/symfony/web-profiler-bundle/blob/7b5ee1e5e6118b77831caf6e34bd18014f0dd247/Resources/views/Collector/config.html.twig#L67C1-L73C28).

This is incomatible with the 5.4 version of the HttpKernel, since this does not have the `hasXdebugInfo` function available.
([5.4](https://github.com/symfony/http-kernel/blob/5.4/DataCollector/ConfigDataCollector.php) vs [6.1](https://github.com/symfony/http-kernel/blob/7.0/DataCollector/ConfigDataCollector.php))

### How to reproduce

Require HttpKernel 5.4 and WebProfilerBundle 6.1 in the same project.

### Possible Solution

There would be 2 solutions to this issue:

1. Add an extra `hasXdebugInfo is defined` check to the template.
The issue with this, is that 6.1 is no longer maintained, and therefore will not get this update.

2. Conflict HttpKernel 5.4 with version 6.1 of the profiler. Since the HttpKernel is still supported, this could be added there. 
We would only need to conflict 6.1 of the profiler, since 6.2 no longer supports HttpKernel 5.4

### Additional Info

I've created this issue, to validate that solution 2 is the correct solution in this case. Please feel free to leave any feedback or alternative options.

**Comment by xabbuh** [comment]
> Conflict HttpKernel 5.4 with version 6.1 of the profiler. Since the HttpKernel is still supported, this could be added there.
We would only need to conflict 6.1 of the profiler, since 6.2 no longer supports HttpKernel 5.4

This won't work as well as Composer will then just pick an older version of the HttpKernel component that doesn't have the conflict rule. I suggest to close this as a won't fix since Symfony 6.1 is not maintained anymore.

**Comment by JoppeDC** [comment]
Makes total sense, didnt think about the fact that it would just use 5.4.(x-1). Thanks for the info!
