### ISSUE TITLE
[Validator] `DateTimeValidator` fails for `DateTimeImmutable` object from `MapRequestPayload`

### ISSUE THREAD

**Issue by ToshY** [symfony/symfony#53896]
### Symfony version(s) affected

6.4.3

### Description

When using the `DateTime` constraint on a DTO property, in combination with `MapRequestPayload` to map request data to this DTO, the assertion fails as the `DateTimeValidator` does not take into consideration that the input value can be an instance of a datetime object.

### How to reproduce

1. Create a DTO

```php
<?php

declare(strict_types=1);

namespace App\DTO;

use DateTimeInterface;
use Symfony\Component\Validator\Constraints as Assert;

final class ExampleDTO
{
    public function __construct(
        #[Assert\NotBlank(allowNull: true)]
        #[Assert\DateTime]
        public readonly DateTimeInterface|null $createdAt = null,
    ) {
    }
}
```

2. In a controller use the `MapRequestPayload` attribute.

```php
    public function updateExample(
        #[MapRequestPayload] ExampleDTO $exampleDto,
    ): JsonResponse
    {
        // ...
    }
```

3. Submit the data.
  i. I've been using a format like `September 17, 2023` which (apparently) will be correctly converted to a `DateTimeImmutable` object.
4. Added a dump to see the violations better in [`RequestPayloadValueResolver`](https://github.com/symfony/http-kernel/blob/274223c474aaa325a5cc3177ef0f6737d8cacf89/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L131), and it shows the following violation:

![image](https://github.com/symfony/symfony/assets/31921460/e2d0a626-856d-4112-9000-ce2fdf097b40)

### Possible Solution

If the `$value` is already an instance of `DateTimeInterface`, then I think it's safe to assume that it's already a valid datetime object (?), so add an additional check:

```php
class DateTimeValidator extends DateValidator
{
    /**
     * @return void
     */
    public function validate(mixed $value, Constraint $constraint)
    {
        if (!$constraint instanceof DateTime) {
            throw new UnexpectedTypeException($constraint, DateTime::class);
        }

        if (null === $value || '' === $value) {
            return;
        }

        if ($value instanceof \DateTimeInterface) {
            return;
        }

        if (!\is_scalar($value) && !$value instanceof \Stringable) {
            throw new UnexpectedValueException($value, 'string');
        }
        // ...
}
```

---

I can provide a PR if desired.

### Additional Context

**Versions**

- `symfony/validator`: `6.4.3`
- `symfony/http-kernel`: `6.4.3`

**Comment by xabbuh** [comment]
We deliberately made the validator behave this way. In older Symfony versions it behaved exactly as you suggested, but we decided that it does not make sense to apply this validator on something of which you already know that it is a date. The solution is to not use the `DateTime` constraint on date objects.

**Comment by ToshY** [comment]
Thanks for the clarification @xabbuh !
