### ISSUE TITLE
No possibility to handle optional not nullable field with #[MapRequestPayload]

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#53917]
### Symfony version(s) affected

7.0 (at least this one)

### Description

In my case, I want to have a not nullable field in my JSON request body (with `#[MapRequestPayload]`). 

### How to reproduce

We will use `name` attribute for this example.

```php
class PatchMyEntityInput
{
    #[Assert\NotNull]
    #[Assert\Type('string')]
    public ?string $name = null;
    
    #[Assert\NotNull]
    #[Assert\NotBlank]
    public string $attribute2;
}
```

And the request I'm sending : 
```json
{
    "attribute2": "99999999999999"
}
```

In my use case, I need to need when it's updated (if it's or not in the payload) and if it's updated, with which value.

**Comment by xabbuh** [comment]
What do you mean with "it's not possible"? What happens? What did you expect to happen instead?

**Comment by AurelienPillevesse** [comment]
Currently, I have an exception from the validator telling me it can not be null.
What I would like : 
- Receiving `null` value throws an exception (because I don't want to receive null value for this field)
- Not receiving this value is OK, initialize the variable in the input to `null`for example because I didn't receive it but not throw an exception
- Receiving a `string` value is OK

**Comment by xabbuh** [comment]
I don't think there's much we can do about this. The validation happens after data has been mapped. So the Validator component does not know anything about whether the data was submitted or is `null` because of the default property value.

**Comment by xabbuh** [comment]
closing here as the behaviour is expected
