### ISSUE TITLE
[AssetMapper] Show import instructions after requiring *multiple* packages too

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#53958]
### Description

When doing `php bin/console importmap:require ...`, the message "Use the new package normally by importing" is only shown if just *one* package was installed: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Command/ImportMapRequireCommand.php#L130

The rationale probably was something like: "If somebody is able to install multiple packages at once, they will probably know how to include them in their JavaScript", right?

But this might not be true in all cases: If somebody installs just *one* package, but this has a CSS file associated, this counts as two.

So I'm suggesting to show the copy-pastable `import` instructions always, listing all packages.

### Example

> [OK] 2 new items (foo, foo/foo.min.css) added to the importmap.php!
> Add this to your JavaScript file:
> import 'foo';
> import 'foo/foo.min.css';

**Comment by smnandre** [comment]
There are many packages that brings dependencies / multiple JS modules with them...

Let's take a big one for the example:

```console
php bin/console importmap:require pixi.js
```

Currently, the console outputs this : 

<img width="847" alt="Capture d’écran 2024-02-16 à 06 06 27" src="https://github.com/symfony/symfony/assets/1359581/bde0ffc5-cb09-4f53-9301-20ef8c946676">

This is... informational.


What you suggest is to write this: 

```console
Add this your Javascript file:
import 'pixi.js';
import '@pixi/mixin-cache-as-bitmap';
import '@pixi/mixin-get-child-by-name';
...
40 more lines
```                                

That would be a wrong advice to give to the user, as they certainely do not need to do that.

There are so many different cases out there about assets that sometimes it's better to say less 😄

**Comment by ThomasLandauer** [comment]
Yeah, you're right! I only had the CSS files in mind. Cause having to "import" them into JavaScript feels so weird, that I think this deserves some extra attention. I guess this is also what @javiereguiluz meant at https://github.com/symfony/symfony-docs/pull/19453#issuecomment-1909780986

So what about adding some extra info just for CSS files?:
> [OK] 27 new items (...) added to the importmap.php!
> 2 of them are CSS files - to enable them, add this to your JavaScript file:
> import 'foo/foo.min.css';
> import 'foo/bar.min.css';

**Comment by weaverryan** [comment]
This last idea seems reasonable

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix". I've re-read the current AssetMapper docs and the handling of CSS files (both local and installed via `import-map:require`) is explained in detail and with examples about "importing" CSS files inside JS files, explaining how that "dones't work" but AssetMapper makes it work, etc. Thanks!
