### ISSUE TITLE
SQL syntax error when creating table for doctrine-messenger

### ISSUE THREAD

**Issue by jawira** [symfony/symfony#53952]
### Symfony version(s) affected

v6.4.*

### Description

After installing `symfony/doctrine-messenger` I created a diff file, the generated file (inside migrations dir) has SQL syntax errors.

### How to reproduce

Install `messenger` and `doctrine-messenger`:

```console
composer require symfony/messenger
composer require symfony/doctrine-messenger
```

Then set an async routing, in my case:

```ini
# .env
MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
```

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\DemoEmail': async
```

In order to update database and create `messenger_messages` tables I had to create a migration file, I use DoctrineMigration to do so:

```console
bin/console doctrine:migrations:diff --allow-empty-diff --no-interaction --formatted --ansi
```

Then I execute the new migration file:

```console
bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction --ansi
```

And finally I got the following error:

```txt
[error] Migration DoctrineMigrations\Version20240215094641 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ":"
LINE 3:           'messenger_messages', NEW.queue_name : $1
                                                       ^"
```

The offending line is:

```php
// migrations/Version20240215094641.php
$this->addSql('CREATE
        OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$ BEGIN PERFORM pg_notify(
          \'messenger_messages\', NEW.queue_name : :text
        ); RETURN NEW; END; $$ LANGUAGE plpgsql;');
```

### Possible Solution

The solution is to manually fix the syntax error. 

Change this: 

```sql
NEW.queue_name : :text
```

To this:

```sql
NEW.queue_name::text
```

### Additional Context

* I'm using a Postgresql 15 database
* I'm not sure where the error came from, if it's a "DoctrineMessenger" error or a "DoctrineMigration" error, but at least I wanted to report it.

**Comment by HypeMC** [comment]
This seems to be caused by an issue in Doctrine's SQL formatter: https://github.com/doctrine/sql-formatter/pull/88.

The bug was fixed 2 years ago, but it hasn't been released yet.

The SQL itself is ok: https://github.com/symfony/symfony/blob/d352e98804b06cd8c582379cfd8b2186e671685b/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L118-L137

**Comment by dbu** [comment]
the fix is only in sql-formatter 1.2.x but that did not get released.

however, i just ran migration generation for messenger-doctrine with postgres (with symfony 7), and for me the `::` has not been broken. does symfony implement some work around, or why does this not always happen?

**Comment by HypeMC** [comment]
@dbu The OP uses the `--formatted` option:

```bash
bin/console doctrine:migrations:diff --allow-empty-diff --no-interaction --formatted --ansi
```

This's what causes the bug to manifest.

**Comment by greg0ire** [comment]
Hope this helps: https://github.com/doctrine/sql-formatter/releases/tag/1.2.0

**Comment by jawira** [comment]
Hello guys, I have updated to `doctrine/sql-formatter v1.2` and sql syntax is valid :hugs: 
This issue can be closed.
