### ISSUE TITLE
[Messenger] Monitoring messages 

### ISSUE THREAD

**Issue by partulaj** [symfony/symfony#53954]
### Description

Hello,

Using symfony/messenger I encountered an issue due to a bug in my code that was always recreating a message in my queue preventing others messages from being process.

After fixing this bug I was wondering if there was a way to monitor that messages in the queue doesn't stack via the messenger ? 
If not is this something that could be implemented in the messenger ?

**Comment by ro0NL** [comment]
perhaps add transport+message count info to `debug:messenger`

but from my experience monitoring/alerting best happens at infrastructural level, not application level.

that said, yes we expose the current transport count in  our app too :) it's little effort in userland:

```
#[TaggedIterator(tag: 'messenger.receiver', indexAttribute: 'alias')]
private readonly iterable $receivers,
```

**Comment by partulaj** [comment]
Hi @ro0NL 

Thank you for your reply, after further thinking I think I didn't ask the right question.
The question should have been could we had some methods to facilitate monitoring ?

Maybe I'm missing something but today I don't see a way to check that messages doesn't stack.
With the receiver I can retrieve all the Enveloppe in my queue but then I can't check when the message was supposed to be processed.

I think a method to count the availabe messages in the queue and retrieve them is missing.
I was thinking of something like this for the Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection of course it would need to be made available at the receiver level.
```php

    public function getMessageAvailableCount(): int
    {
        $now = new \DateTimeImmutable('UTC');
        $queryBuilder = $this->createQueryBuilder()
            ->select('COUNT(m.id) AS message_count')
            ->where('m.queue_name = ?')
            ->andWhere('m.available_at <= ?')
            ->andWhere('m.delivered_at is null')
            ->setParameters([
                $this->configuration['queue_name'],
                $now
            ], [
                Types::STRING,
                Types::DATETIME_IMMUTABLE
            ])
            ->setMaxResults(1);

        $stmt = $this->executeQuery($queryBuilder->getSQL(), $queryBuilder->getParameters(), $queryBuilder->getParameterTypes());

        return $stmt instanceof Result ? $stmt->fetchOne() : $stmt->fetchColumn();
    }
```

**Comment by ro0NL** [comment]
isnt that what DoctrineTransport::getMessageCount currently does?

im not sure we can easily identify stacking queues from busy ones, unless we involve counting redeliveries or so

**Comment by partulaj** [comment]
Your right , sorry I must have misread the query that was made by getMessageCount.
