### ISSUE TITLE
add "save" and "remove" default methods to repository

### ISSUE THREAD

**Issue by VibroMatvey** [symfony/symfony#53973]
### Symfony version(s) affected

all

### Description

add "save" and "remove" default methods to repository please

### How to reproduce

add "save" and "remove" default methods to repository please

**Comment by GromNaN** [comment]
This issue lack of context. Please provide more details on your feature request next time.

If you are referring to Doctrine repository, the feature request must be addressed to Doctrine ORM project. But I don't think this will be accepted. The [ObjectManager](https://github.com/webmozart/doctrine-common/blob/master/lib/Doctrine/Common/Persistence/ObjectManager.php) has methods `persist` and `remove`.
