### ISSUE TITLE
FirewallConfig::customAuthenticators() method does not exist: cannot configure CustomAuthenticator via PHP

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony#53987]
### Symfony version(s) affected

5.4.x

### Description

The `customAuthenticators()` method does not exist on `FirewallConfig`. I can use yaml with `custom_authenticator`, but it seems impossible via PHP config using the `FirewallConfig` object. If you simply pass an array configuration to ContainerConfig with `custom_authenticators` it works, but there are benefits to using the config objects. I’ve tried the verbatim config from the documentation and it doesn’t work:

https://symfony.com/doc/5.x/security/custom_authenticator.html

I see no `customAuthebticators()` method anywhere in symfony core. The `FirewallConfig` I’m using is under `var/cache/dev/Symfony/Config/`

### How to reproduce

Use the exact code from documentation

```
use App\Security\ApiKeyAuthenticator;
use Symfony\Config\SecurityConfig;

return static function (SecurityConfig $security) {
    $security->enableAuthenticatorManager(true);
    // ....

    $security->firewall('main')
        ->customAuthenticators([ApiKeyAuthenticator::class])
    ;
};
```

**Comment by HypeMC** [comment]
@arderyp Hi, could you see if #53989 fixes your issue?

**Comment by arderyp** [comment]
hey @HypeMC thank you so much for working on it! I will test your commits now and get back to you ASAP

**Comment by arderyp** [comment]
thanks @HypeMC, I commented on the PR.  That solved the bug!

**Comment by arderyp** [comment]
@HypeMC do you know the procedure here for getting this merged? Should I @ certain people to review?

**Comment by HypeMC** [comment]
@arderyp No need, the best thing is to wait, in my experience it usually doesn't take to long. They release patch versions every month.

**Comment by arderyp** [comment]
Amazing. I will keep an eye out, again, thank you so much! The way I was trying to fix/patch it was definitely not the approach you followed as I wasn't fully understanding the bug. Your solution is much more proper and comprehensive.
