### ISSUE TITLE
Support for Apple's PKL configuration format

### ISSUE THREAD

**Issue by ksn135** [symfony/symfony#53990]
### Description

Just 2 weeks ago Apple published a very interesting open source product - [pkl](https://pkl-lang.org/) configuration description language, which looks like a worthy alternative to json and yaml. And here in [this video](https://www.youtube.com/watch?v=lAxXWYAIt4k) you can see a brief overview of all its features.

Github: https://github.com/apple/pkl

**Comment by derrabus** [comment]
Can you elaborate a bit more on what changes in Symfony you have in mind exactly?

**Comment by wouterj** [comment]
In the recent year(s), we're slowly migrating to a new [PHP](https://symfony.com/blog/new-in-symfony-3-4-php-based-configuration-for-services-and-routes) [config format](https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes). Nobody knows what the community will embrace in the future, but I don't think it's unlikely that the non-PHP formats are slowly phased out (from books, tutorials, screencasts, etc. until maybe some year from core). In this light, I don't think it's a good idea to add another non-PHP format to Symfony core.

Besides that, Symfony relies on rather traditional languages (YAML and XML). We've never jumped ship to newer syntaxes (like Neon). I'm not sure what PKL can offer us that would change this, especially given the complexity of the format (and thus significant introduction and maintenance cost of the parser).

Combining these two reasons, I'm 👎 on introducing PKL support in Symfony (for the time being).

At last, Symfony Core not supporting PKL does not have to stop you from writing Symfony config, routes and translation using the PKL format. Symfony uses loader abstractions (through the Config component) to support Yaml, XML and PHP for these. The community can always create a PKL package to provide loaders for the PKL format.

**Comment by javiereguiluz** [comment]
@ksn135 thanks for this proposal. PKL looks very promising and features like embedded validation seem very convenient.

However, I agree with Wouter and I don't think we should add support for it in Symfony as a built-in config format: we're slowly moving to PHP-only; PKL is too new to know if it will be adopted; it's very complex (feature rich) so it'd take a lot of resources to implement that; etc.
