### ISSUE TITLE
Allow render function to accept array of templates in AbstractController

### ISSUE THREAD

**Issue by maciekpaprocki** [symfony/symfony#54011]
### Description

When using traits for controller organisation I often find myself reimplementing the render method to accept an array of strings in addition to just a string. This way I can do template overloading/hierarchy. 

It's easy to wrap in something like renderMultiple, but since there's union types support in new PHP we could extend the render function to be back compatible. 

There are a few other "render" functions in AbstractController, it would be probably good to extend them too in that scenario. 

### Example

Allowing code like: 

```php
$this->render(['admin/view.html.twig',sprintf('admin/view/%s.html.twig',$entityName)])
```

For entityName equal to post It will first check if  admin/view/post.html.twig exists and if not it will check if generic admin/view.html.twig exists. 

If none of the templates exists it throws the error. 

-----------
Also, I am happy to implement it and add tests/docs.

**Comment by flohw** [comment]
Hi,

Maybe you can take advantages of namespaces and/or `paths` configuration of twig?
https://symfony.com/doc/current/templates.html#template-namespaces

**Comment by derrabus** [comment]
Widening the parameter type of the render method would be a breaking change.

Also, the `AbstractController` should remain a simple wrapper for commonly used services. I believe that the kind of logic that you're proposing should not live in that class.

I'm 👎🏻 on this proposal.

**Comment by yceruto** [comment]
Also, this feature already exists in Twig, you just need to create a 3rd twig template with the following code:
```twig
{% extends [
    'admin/view/' ~ entity_name ~ '.html.twig',
    'admin/view.html.twig'
] %}
```

**Comment by derrabus** [comment]
Let's close then. Thank you for your proposal.

**Comment by maciekpaprocki** [comment]
Thanks for a review. I thought maybe other people find this same issue as me, but I think I was mistaken :) Tbh, the only thing it's doing is not working great with phpstorm and extend block names, so it's not a big deal to have it in twig. 

While at it though, I am not sure why widening method arguments is breaking change. Seems like it will not actually break anything.

**Comment by stof** [comment]
it is a BC break for child classes overriding the method
