### ISSUE TITLE
Problem Upgrading symfony/var-dumper to 7.0.3

### ISSUE THREAD

**Issue by dev-bjwells** [symfony/symfony#54017]
### Symfony version(s) affected

^7.0

### Description

When upgrading from Symfony 6.4 to 7.0 I noticed that the toolbar utilized with the `symfony/debug-bundle` would initialize on first load but when I navigate to a secondary page within the site or refresh the screen the debug bar stops working and the bar display's, "An error occurred while loading the web debug toolbar. Open the web profiler." When clicking on the link to the profiler I received the error message below.

![image](https://github.com/symfony/symfony/assets/16748744/c9a9fffc-e116-47a1-b8b4-5d175b586d92)

```
An exception has been thrown during the rendering of a template ("Typed property Symfony\Component\VarDumper\Cloner\Stub::$value must not be accessed before initialization").
```

After downgrading the `symfony/var-dumper:6.4.0` the issue is resolved and I am able to utilize the debug toolbar like normal.

Is there something obvious that I am missing to prevent the error from occurring?

### How to reproduce

To reproduce this issue, please take the following steps:

1. As part of the symfony framework bundle using the provided `symfony/var-dumper:7.0.3` or `symfony/debug-bundle:7.0.3`
2. Go to a page on your site or local-dev to create a first load instance.
3. Hit refresh or navigate to a secondary page to force a second load of the debug toolbar.

**Comment by HypeMC** [comment]
This was possibly fixed in #53906.
