### ISSUE TITLE
Column precision is not specified

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#54028]
### Symfony version(s) affected

7.0.0

### Description

after update to
doctrine/orm: 3.0.0
doctrine/dbal: 4.0.0

getting error running 

`php bin/console doctrine:schema:update --force`

In InvalidColumnDeclaration.php line 17:
                                 
  Column "fee" has invalid type  
                                 

In ColumnPrecisionRequired.php line 18:
                                     
  Column precision is not specified  
                                     

### How to reproduce

```
    #[ORM\Column(name: 'fee', type: Types::DECIMAL, precision: 10, scale: 2, unique: false, nullable: false)]
    #[Assert\NotBlank]
    private string $fee;
```

**Comment by 94noni** [comment]
What does the major version changelog of those packages say? Perhaps there are some changes you need to handle

**Comment by sstok** [comment]
This issue/problem is related to [Doctrine ORM](https://github.com/doctrine/orm) which isn't part of this repository.

**Comment by xabbuh** [comment]
closing therefore, thank you for understanding
