### ISSUE TITLE
#[MapQueryString] unable to map query string variable starting with a number

### ISSUE THREAD

**Issue by pomporov** [symfony/symfony#54029]
### Symfony version(s) affected

7.*

### Description

Imagine you have 

https://localhost?3d=passed

this is valid but because it start with a number it cannot be mapped to 

```
class DummyDto {
    public function __construct(
        #[Assert\NotBlank]
        public readonly string $3d, <- this is not possible because variable start with number


```

a workaround ? 

thanks

### How to reproduce

Just any variable in query string or post starting with letter

### Possible Solution

HACK _GET or _POST via EVENTS but this is dirty

### Additional Context

none

**Comment by 94noni** [comment]
You want to map with a var name that can not be defined (as per php) like with another mapping?

**Comment by rafageist** [comment]
1. The URL `https://localhost/?3d=passed` is valid
2. PHP can get the parameter in `$_GET['3d']`
3. An object can have a property that starts with numbers: `$obj->{"3d"}` 
4. But Symfony does not consider it
5. Keywords cannot start with digits

If the URL cannot change and Symfony needs a change or is not going to make it, you will have to invent your specific solution.

**Comment by 94noni** [comment]
Ho i got it now oki

**Comment by pomporov** [comment]
We could add a conversionRule to remap these for example 

```
    #[Route('/dummy', name: 'app_legacy')]
    public function index(#[MapQueryString] DummyDto $dummyDto,['3d' => 'd3']): Response

```

then unmappable 3d becomes mappable d3 or whatever other way , but as external urls cannot change .

Or maybe some dirty trick with [kernel.request](https://symfony.com/doc/current/reference/events.html#kernel-request) event to tweak _GET or _POST before request is created to "normalize" them . But this look dirty.

**Comment by 94noni** [comment]
it can make sens to me, perhaps try to open a PR, generally it attracts reviewers more than an issue :)

**Comment by n0rbyt3** [comment]
The serializer component is used internally. Have you tried using the ```SerializedName``` attribute? https://symfony.com/doc/current/components/serializer.html#configure-name-conversion-using-metadata

```php
use Symfony\Component\Serializer\Annotation\SerializedName;

class DummyDto {
    public function __construct(
        #[Assert\NotBlank]
        #[SerializedName('3d')]
        public readonly string $threeD;
```

**Comment by pomporov** [comment]
thats a cool trick i did not thinked about it ! 
we should update documentation linking to serializer docs / options . 
thanks

**Comment by pomporov** [comment]
@n0rbyt3 saved the day with link to serializer
