### ISSUE TITLE
[Messenger] Wait for stopped workers

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#54037]
### Description

I believe `messenger:stop-workers` should be waiting by default (or optin `--wait`) for workers actually to be stopped (while true check if redis flag is cleared)

Currently a pre-deploy container can be finished before workers are stopped, causing the deploy to trigger while a worker job is processing still.

It's not ideal :)

**Comment by ro0NL** [comment]
Solved in userland. I can PR it once we run 7.1 :sweat_smile:

**Comment by ro0NL** [comment]
note to self; sometimes we also want to stop workers but keep the process alive, e.g. when updating the queue server. The workers should be resumed manually after upgrading.

**Comment by n0-m4d** [comment]
why closed?

**Comment by ro0NL** [comment]
We've put this this on our internal backlog :')
