### ISSUE TITLE
301 response when route ends with slash

### ISSUE THREAD

**Issue by yard-mschwartz** [symfony/symfony#54041]
### Symfony version(s) affected

6.3.12

### Description

I would expect that the following two definitions of the index route are equivalent:

```php
#[Route('/organizations')]
class OrganizationController extends AbstractController
{
    private OrganizationRepository $organizationRepository;

    public function __construct(OrganizationRepository $organizationRepository)
    {
        $this->organizationRepository = $organizationRepository;
    }

    #[Route('', name: 'organization_index', methods: ["GET"], format: 'json')]
    #[Route('/', name: 'organization_index', methods: ["GET"], format: 'json')]
    public function index(#[MapQueryString] OrganizationSearchDTO $searchDTO = new OrganizationSearchDTO()): JsonResponse
    {
        return $this->json($this->organizationRepository->findByPage($searchDTO), Response::HTTP_OK, ...);
    }
}
```

Note the difference in the route path, relative from `/organizations`

And in fact, both definitions suffice when I make a GET request to `/organizations` in Postman. However, when I test this route using a functional test, a difference comes up.

### How to reproduce

Consider the functional test below. The test succeeds with the upper route definition, but fails when I use the bottom route definition:

```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class OrganizationControllerIndexTest extends WebTestCase
{
    /** @test */
    public function it_fetches_organizations(): void
    {
        $client = static::createClient();

        $client->jsonRequest('GET', '/organizations');

        $this->assertResponseIsSuccessful();
    }
}
```

The response of the failed test (bottom route definition, ending in a slash):

```
Failed asserting that the Response is successful.
HTTP/1.1 301 Moved Permanently
Cache-Control: max-age=0, must-revalidate, private
Content-Type:  application/json
Date:          Fri, 23 Feb 2024 08:44:05 GMT
Expires:       Fri, 23 Feb 2024 08:44:05 GMT
Location:      http://localhost/organizations/
X-Robots-Tag:  noindex

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='http://localhost/organizations/'" />

        <title>Redirecting to http://localhost/organizations/</title>
    </head>
    <body>
        Redirecting to <a href="http://localhost/organizations/">http://localhost/organizations/</a>.
    </body>
</html>
```

Here's my definition of `OrganizationSearchDTO` in case it matters (probably not):

```php
readonly class OrganizationSearchDTO
{
    public function __construct(
        public int $pageNo = 1,
        public int $pageSize = 20,
        public int $id = 0,
        public string $name = '',
    ) {
    }
}
```

### Additional Context

At some point when I was working on this, I also got myself in a situation where Postman would give me the redirect response as well, but I can't seem to reproduce this anymore. I did clear the cache many times in the process (using `rm -rf var/cache/*`)

**Comment by n0rbyt3** [comment]
You don't need to specify both. The redirect is expected: https://symfony.com/doc/current/routing.html#redirecting-urls-with-trailing-slashes

If you really need to support both urls, you could try this: https://github.com/symfony/symfony/issues/39875#issuecomment-767423977

**Comment by yard-mschwartz** [comment]
Hmm, I wasn't aware of that piece of documentation, thanks!

I can't say however, that I agree with this convention. Serving different content based on the presence of a trailing slash seems very wrong to me. The question of course is whether it's the responsibility of the framework to avoid this. Also, the permanent redirect to the url you came from doesn't make sense to me in terms of error reporting. I'd prefer a route not found error instead.

I'll leave this open for a few days in case others will want to weigh in, but I suppose it can be closed if this convention was decided on by the community.

EDIT the redirect does make more sense now I realize no trailing slash redirects to trailing slash and vice versa, but it took me long to even notice that

**Comment by n0rbyt3** [comment]
> Serving different content based on the presence of a trailing slash seems very wrong to me.

Indeed it's wrong, but the term content is relevant. In case of SEO, you must not serve the same *user* content (=request body) in two different urls. In that case, either all other urls perform a 301 (permanent) redirect or the canonical (unique) url is set as meta tag.

I support the idea to include that into the framework, so any developer can choose whether they prefer a trailing slash without adding redirect code for SEO optimizations. If nearly all projects need to copy the same code to achieve the same logic, the core framework is a good place to add it.

> Also, the permanent redirect to the url you came from doesn't make sense to me in terms of error reporting.

You have only one url serving the content, so there's only one url that may cause a bug.

> I'd prefer a route not found error instead.

For websites, you'll loose many visitors with 404 error pages forever. They'll interpret this as buggy website and quit.
For APIs, the documentation should state the exact URL. Redirecting to another URL is a good hint for the client to update.

**Comment by yard-mschwartz** [comment]
I suppose this also explains why the url without the trailing slash seemed to work fine in Postman, but didn't work when used in my functional test. Postman just follows the redirect and shows me the result of the redirected url. The test fails, because the response was a 301 and not a 200.
