### ISSUE TITLE
PR template in Issues row should require to be more specific

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#54049]
### Description

PR template for Issues row is as follows:
`| Issues        | Fix #... <!-- prefix each issue number with "Fix #", no need to create an issue if none exists, explain below instead -->`

However not every PR is a **fix** so it might be misleading. I propose to use Fix for bug fixes and Close (or Resolve but Close sounds more familiar imo) for features.

**Comment by fabpot** [comment]
When creating a PR, you can use whatever you want. This is just a suggestion that has no consequences. Let's keep it simple.

**Comment by ghost** [comment]
I bet most people just leave the default `Fix #` and just replace `...` with an issue number.

**Comment by derrabus** [comment]
> I bet most people just leave the default `Fix #` and just replace `...` with an issue number.

And that's absolutely fine. 😌

**Comment by ghost** [comment]
> And that's absolutely fine. 😌

Then let's tell GitHub to remove close, closes, closed, fixes, fixed, resolve, resolves, resolved because using fix because is absolutely fine 😌 
Btw. It's semantically incorrect to fix a feature :smile:

**Comment by derrabus** [comment]
> > And that's absolutely fine. 😌
> 
> 
> 
> Then let's tell GitHub to remove close, closes, closed, fixes, fixed, resolve, resolves, resolved

Be my guest. I won't stop you. 🤷
