### ISSUE TITLE
[symfony/doctrine-bridge] Allow configuring TypedFieldMapper

### ISSUE THREAD

**Issue by klkvsk** [symfony/symfony#54065]
### Description

When using custom doctrine types, they need to be explicitly stated in entity's property declaration:
```
#[ORM\Column(type: 'uuid')]
protected UuidV4 $id;
```
Doctrine has a mechanism for guessing proper DBAL types from property types, e.g. for DateTime you can omit `type:`
It is called TypedFieldMapper: 
https://www.doctrine-project.org/projects/doctrine-orm/en/3.0/reference/typedfieldmapper.html#implementing-a-typedfieldmapper

But there is no way to configure this from Symfony's configuration.

By adding this ability, authors of custom types can provide better developer experience:
- eliminating need to refer to configs/docs or remember type names (was it a `bit_string` or `bitstring`?...)
- automatically register types from bundle initialization -- explain on that:

> Usually types are not registered automatically due to very common names (money, uuid, ...) which can conflict with other types, so it is actually better for developer to register them manually. But having two-way mapping allows for bundle author to preconfigure their own types with unique prefixes for a works-out-the-box experience, like so:
> 1) type registry: "some_lib.something" => \SomeLib\Doctrine\Type\SomethingType
> 2) typed field mapping: \SomeLib\Something => "some_lib.something"
>
> With this done from bundle's DI extension class, user of this lib is not required to add anything to doctrine.yaml and can simply start using this type as 

```php
#[ORM\Column]
protected Something $something;
```

### Example

Example configuration for [@tbbc/money-bundle](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle) might be:
```yaml
doctrine:
    dbal:
        types:
            money: Tbbc\MoneyBundle\Type\MoneyType
    orm:
        typed_field_mapping:
            Money\Money: money
```
This way it automatically adds types to the constructor of DefaultTypedFieldMapper (it allows passing additional types)

Another way might be providing list of custom services implementing TypedFieldMapper interface.

With this configuration the new type is simply used as:
```php
#[ORM\Column]
protected Money $price;
```

**Comment by xabbuh** [comment]
The configuration for Doctrine DBAL and ORM is managed by the [DoctrineBundle](https://github.com/doctrine/DoctrineBundle). You will have to request the feature over there. :)
