### ISSUE TITLE
[AssetMapper] Integrate minify for JS & CSS

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#54070]
### Description

It would be nice if `php bin/console asset-map:compile` could run some minification tool (that also removes all comments) over the created files.

There are tons of minifiers out there, but (as far as I can see):
* Any IDE plugins won't work since the created files aren't opened in the IDE anymore.
* Any JS scripts won't work since they're not getting executed.

So all that's left are CLI commands. And all that I could find operate on single files, not on entire folders. So the solution I just created for myself is the shell script from https://unix.stackexchange.com/a/412808/473748 which throws each file into [UglifyJS](https://github.com/mishoo/UglifyJS) and [UglifyCSS](https://github.com/fmarcia/uglifycss)

**Comment by weaverryan** [comment]
If someone wants to make a bundle that adds this, I think that would be perfectly fine. In general, I don't think people should worry about minification or removing comments and I don't want people to get the impression this is needed. However, enough people want it that, sure, having a bundle would be totally fine. I would probably implement this as an AssetMapper compiler - here's an example for Sass - https://github.com/SymfonyCasts/sass-bundle/blob/main/src/AssetMapper/SassCssCompiler.php - a minifier would take the `$content`, run it through some binary to minify, then return the minified content. You could do this in debug mode only if you want.

Cheers!
