### ISSUE TITLE
OneToOne mappings broken after upgrading to symfony/doctrine-bridge 7.0.4

### ISSUE THREAD

**Issue by weberdominik** [symfony/symfony#54077]
### Symfony version(s) affected

7.0.4

### Description

After upgrading to symfony/doctrine-bridge 7.0.4 I am receiving warnings for all my OneToOne mappings:

Warning: Undefined property: Doctrine\ORM\Mapping\OneToOneInverseSideMapping::$joinColumns

### How to reproduce

This warning occures for every OneToOne mapping in my project, even for most basic configurations. For example:

`#[ORM\OneToOne(targetEntity: Order::class)]`

### Possible Solution

Downgrading back to symfony/doctrine-bridge 7.0.3 fixed my issue.

### Additional Context

The warning is thrown in vendor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php:282

**Comment by derrabus** [comment]
The ORM version involved would be nice to know here.

**Comment by weberdominik** [comment]
> The ORM version involved would be nice to know here.

3.0.1 it is

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by derrabus** [comment]
Before #53754 the access to array keys of the mapping metadata was safeguarded with a `?? null`, but that's missing when dealing with the new metadata classes apparently.

**Comment by derrabus** [comment]
Does #54081 fix the issue for you?

**Comment by weberdominik** [comment]
> Does #54081 fix the issue for you?

Yes, that fixes it. Thanks.
