### ISSUE TITLE
[Mailer][BrevoMailer] BrevoRequestParser handles tags as mandatory parameter

### ISSUE THREAD

**Issue by palgalik** [symfony/symfony#54088]
### Symfony version(s) affected

7.0.3

### Description

BrevoRequesstParser handles 'tags' as a mandatory parameter, when it's not.
https://github.com/symfony/brevo-mailer/blob/7.0/Webhook/BrevoRequestParser.php#L52C1-L53C1

Brevo's documentation doesn't clarify, but 'tags' aren't mandatory parts of the request.

https://developers.brevo.com/docs/transactional-webhooks#sent

### How to reproduce

- setup webhook url in your Brevo settings
- click on "test" button
- the webhook API will reject all test requests with 406 (it's fails on the part `!isset($content['tags'])`)

![Screenshot 2024-02-27 at 17 07 48](https://github.com/symfony/symfony/assets/22448422/4dc415b7-3306-4801-be88-3a234b251441)
![Screenshot 2024-02-27 at 17 09 23](https://github.com/symfony/symfony/assets/22448422/09eba74c-beda-4086-af20-e8bb6b7a1201)

Also if you send any emails without adding some TagHeader to the email, all related webhook event will be rejected for the same reason.

### Possible Solution

Remove  `!isset($content['tags'])` condition from `doParse` method in `Symfony\Component\Mailer\Bridge\Brevo\Webhook\BrevoRequestParser`

**Comment by stof** [comment]
Can you send a PR with a fix ? Those mailer bridges are maintained based on community contributions.

**Comment by palgalik** [comment]
Sure. @stof. I did create a PR. Do you have any idea why CI pipeline fails?
