### ISSUE TITLE
allow recipes to work with php config files (instead of default yaml)

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony#54090]
### Description

I've recently migrated from yaml config files to PHP config files due to compelling arguments by @TomasVotruba: https://getrector.com/blog/modernize-symfony-configs

one consequence is that updating recipes seems to write yaml config files only (or am I missing something?). It owuld be helpful if we could configure it to work with systems using PHP configs.

**Comment by k0d3r1s** [comment]
this looks like flex thing: https://github.com/symfony/flex  
biggest problem here is to copy right config from recipe, adding .php config to recipe seems already doable. adding both .yaml and .php now would copy both files to project

**Comment by stof** [comment]
We don't maintain 2 variants of each recipe to use either Yaml or PHP config files. So if you want to rely on the Flex recipes, you need to stick to Yaml for now.

**Comment by xabbuh** [comment]
let's close here in favor of symfony/flex#970

**Comment by arderyp** [comment]
Thanks for the confirmation and the link to the other issue :)
