### ISSUE TITLE
[Validator] NotBlank constraint

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony#54101]
### Symfony version(s) affected

7.0 (at least this one)

### Description

When I receive `false` on a `#[Assert\NotBlank(allowNull: true)]`, a violation is thrown.
I don't understand why it's the case because `false` is not blank.

I can see this test for the `NotBlankValidator` : https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Validator/Tests/Constraints/NotBlankValidatorTest.php#L74

### How to reproduce

Something similar of this test case : https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Validator/Tests/Constraints/NotBlankValidatorTest.php#L74

### Possible Solution

Can I do a PR to authorize the `false` value all the time or doing something similar of `allowNull` but with `allowFalse`?

**Comment by derrabus** [comment]
> When I receive `false` on a `#[Assert\NotNull(allowNull: true)]`, a violation is thrown.

The `NotNull` constraint does not have a `allowNull` property.

```php
$validator = Validation::createValidator();
dump($validator->validate(false, new NotNull()));
```

Output:

```
Symfony\Component\Validator\ConstraintViolationList {#13
  -violations: []
}
```

Looks okay to me.

**Comment by AurelienPillevesse** [comment]
Sorry mistake in the first line, fixed.
All other lines mentionned `NotBlank` sorry

**Comment by stof** [comment]
What is the use case for using a NotBlank constraint on a boolean field ?

**Comment by derrabus** [comment]
I see.

Yes, `NotBlank` rejects `false`. This is the current behavior and as the test tells you, it's the documented one. I'm emphasizing that because you've filed this as a bug report.

> What is the use case for using a NotBlank constraint on a boolean field ?

That would've been my next question as well. 🙂

**Comment by AurelienPillevesse** [comment]
```php
class LuckyController
{
    #[Route('/lucky/number/{max}', name: 'app_lucky_number', methods: ['POST'])]
    public function number(#[MapRequestPayload] MyInput $input, int $max): Response
    {
        // use it like this : $input->myInputAttribute;
    }
}

class MyInput
{
    #[Assert\NotBlank(allowNull: true)]
    public ?bool $myBool = null;
}
```

When I receive : 
```json
{"myBool": true}
```
OR
```json
{"myBool": false}
```

I want to work with these two values. Maybe I'm missing something.

**Comment by stof** [comment]
Well, `?bool` only allows to store 3 values in the property: `true`, `false` and `null`. If you expect to accept `true` and `false` and you also intend to accept `null` (as suggesting by your usage of `allowNull: true`), you can remove your constraint entirely as it would never reject anything.

And I would still not consider that as a valid use case for adding a new `allowFalse` flag in NotBlank then.

**Comment by AurelienPillevesse** [comment]
Alright, seems good for me right now.
