### ISSUE TITLE
_fragment does not work with RedirectToRoute when turbo enabled

### ISSUE THREAD

**Issue by robert-hoffmann** [symfony/symfony#54117]
### Symfony version(s) affected

7.0.3

### Description

Fragments do not work with RedirectToRoute (or generate url, etc)
They do work in twig templates using the path()

I'd guess this is related to turbo being enabled

I have custom js listeners wired up to switch bootstrap tabs to the correct tab when entering a page ..it will work via twig templates, but never after editing a form, issuing a submit, that then uses a RedirectToRoute 🤔

### How to reproduce

Simply use symfony with turbo and then try to use something like

`return $this->redirectToRoute('admin_user_show', ['id' => $user->getId() ,'_fragment' => 'courses']);`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by robert-hoffmann** [comment]
Yeah, sorry, don't really have time to make a project from scratch and deploy, etc (finishing up some client work)

Don't you guys have a site like ux.symfony that already has turbo activated, where you can just slap a _fragment on an existing route (should take like 5 min to test on an existing site) ?

**Comment by xabbuh** [comment]
I don’t

**Comment by robert-hoffmann** [comment]
Doesn't the team have a dev site ?

Like even i were to make a project, it's not like your gonna have access to the source-code to check if i didn't do something stupid, or be able to debug it anyways
