### ISSUE TITLE
[AssetMapper] Remove unused method / BC break ?

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#54123]
### Symfony version(s) affected

7.0

### Description

This method ([ImportMapConfigReader::splitPackageNameAndFilePath](https://github.com/symfony/symfony/blob/f8611cf821f8ab19c3d5f1984473847ad774c45e/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L175)) is unused, is it OK to delete it or is it covered by BC ?

(i do believe it stayed here by accident)

### How to reproduce

The method has been moved to https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/AssetMapper/ImportMap/ImportMapEntry.php#L69

**Comment by fabpot** [comment]
Unfortunately, it would be considered a BC break :(
Let's deprecate it so that we can at least remove it in 8.0.
