### ISSUE TITLE
3rd party js library not found after install with asset mapper

### ISSUE THREAD

**Issue by vitoff34** [symfony/symfony#54128]
### Symfony version(s) affected

7.0

### Description

Hello,
I installed dropzone.js using
```
php bin/console importmap:require dropzone`

```
```
I import dropzone in my app.js file.
`import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import 'just-extend';
import 'dropzone';
import $ from 'jquery';

$("div#myId").dropzone({ url: "/file/post" });
console.log('This log comes from assets/app.js - welcome to AssetMapper! 🎉');

```

However when I try to initialize dropzone in a twig file I get Dropzone is not defined.
This is my importmap.php
```
<?php
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'bootstrap' => [
        'version' => '5.3.3',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.3',
        'type' => 'css',
    ],
    'bootstrap-icons/font/bootstrap-icons.min.css' => [
        'version' => '1.11.3',
        'type' => 'css',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'dropzone' => [
        'version' => '6.0.0-beta.2',
    ],
    'just-extend' => [
        'version' => '6.2.0',
    ],
    'jquery' => [
        'version' => '3.7.1',
    ],
];
```

### How to reproduce

I am on php 8.2 using symfony 7

**Comment by NeilPeyssard** [comment]
Hello,

I think you installed the wrong package. The Dropzone you installed is for [vanilla JavaScript](https://docs.dropzone.dev/getting-started/installation/npm-or-yarn#javascript).

The [jQuery plugin](https://www.npmjs.com/package/jquery.dropzone) exists, and can be install with:

```
$ php bin/console importmap:require jquery.dropzone
```

Anyway, it's probably not a Symfony issue

**Comment by vitoff34** [comment]
Nope, this didn't fix it.
I post the issue here because I follow the Symfony docs for 3rd party js libraries and I am not able to use them after installation.

**Comment by weaverryan** [comment]
I agree with @NeilPeyssard. I just ran `importmap:require dropzone`. And then I followed the docs to import it as they show - 

```
import { Dropzone } from 'dropzone';
console.log(Dropzone);
```

On the page, this logs the `Dropzone` instance. 

<img width="781" alt="Screenshot 2024-03-01 at 12 43 56 PM" src="https://github.com/symfony/symfony/assets/121003/ea3fe5d6-ed63-43bd-82a2-a3fc6c956786">

Also, running `importmap:require jquery.dropzone` also works:

```js
import 'jquery.dropzone';
$('.App').dropzone();
```

I can see the class being added to the target element when I drag a file over it. So I think everything is working as expected :)

**Comment by vitoff34** [comment]
How can I use Dropzone not from app.js but from script tag in an twig file?

**Comment by stof** [comment]
Well, if the script tag defines a global variable, use that global variable. But be careful about the order of files then to avoid accessing the global variable before the second file is evaluated to define it.

**Comment by weaverryan** [comment]
This is legal in Twig templates, though I'd recommend in general not inlining your scripts :) 

```html
<script type="module">
    import { Dropzone } from 'dropzone';

    // ... use it
</script>
```
