### ISSUE TITLE
[OptionsResolver] Fix allowed types not defined as string

### ISSUE THREAD

**Issue by symfonyaml** [symfony/symfony#54131]
### Symfony version(s) affected

5.4.x

### Description

Misuse of `addAllowedTypes()` and `setAllowedTypes()` with non-scalar definitions returns different PHP fatal errors, instead of some DX with a nice exception explaining the error.
#### The misuse :
```php
$resolver->setAllowedTypes('foo', [null/* <--- not scalar and invalid*/]);
```
return this error
```
TypeError: OptionsResolver::verifyTypes(): Argument #1 ($type) must be of type string, null given
```

### How to reproduce

```php
$resolver = new OptionsResolver();
$resolver->setDefault('foo', 'bar');
$resolver->setAllowedTypes('foo', [null]);
$resolver->resolve([]);
```

### Possible Solution

Should we just check if the allowed types provided are "_scalar_", otherwise throw an exception explaining the problem.

**Comment by yceruto** [comment]
I'm closing here too for the same reasons explained in the PR https://github.com/symfony/symfony/pull/54132#discussion_r1509416661
