### ISSUE TITLE
[DependencyInjection] Named argument might be unresolved in ChildDefinition

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#54138]
### Symfony version(s) affected

7.0.3, 7.1, maybe other versions too

### Description

Hi!

I think, I found a small possible bug with named argument in `ChildDefinition` class:

**Reference**: 
https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/DependencyInjection/ChildDefinition.php#L83
https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/DependencyInjection/Definition.php#L254

Looking at syntax of `replaceArgument` method, the second argument has different names, so PHP might unresolve named argument.

### How to reproduce

3v4l.org sample: https://3v4l.org/Zbjbl

```
<?php

declare(strict_types = 1);

namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class ReproducesPass implements CompilerPassInterface
{
    public function process(
        ContainerBuilder $container,
    ): void {
        $definition = $container->getDefinition(id: 'service_alias'); // getDefinition() may return Definition or ChildDefinition instances

        $definition->replaceArgument(index: 'int|string index', argument: new Reference(id: 'new_service_alias')); // Named argument (second argument) might be unresolved in ChildDefinition.replaceArgument
    }
}
```

### Possible Solution

I don't know nothing about policy of BC with named argument. Maybe Should I prepare PR with fixing `ChildDefinition::replaceArgument` signature of second argument targeting to 7.1 ?

### Additional Context

Bug found by PHPStorm (although PHPStan and other tool didn't detect it)

![obraz](https://github.com/symfony/symfony/assets/16488888/fdd49734-9d8d-4541-880d-b7c3e3dff5df)

**Comment by chalasr** [comment]
As documented in https://symfony.com/doc/current/contributing/code/bc.html:

> [10] Parameter names are only covered by the compatibility promise for constructors of Attribute classes. Using PHP named arguments might break your code when upgrading to newer Symfony versions.

So I'm going to close. Thanks
