### ISSUE TITLE
bin/console config:dump-reference dumps invalid yaml

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#54154]
### Symfony version(s) affected

7.0.4

### Description

The following yaml, created from config:dump-reference, is invalid, because it has ~ and a list

```yaml
        # Specifies the default link handling for the web app.
        handle_links:         ~

            # Examples:
            - auto
            - preferred
            - not-preferred
```

### How to reproduce

```bash
symfony new container-bug --webapp && cd container-bug
composer install
composer require spomky-labs/pwa-bundle
bin/console config:dump-reference  pwa > pwa.yaml
bin/console lint:yaml pwa.yaml
```

```
No security vulnerability advisories found
Using version ^1.0 for spomky-labs/phpwa
  ERROR  in pwa.yaml
  >> Unable to parse at line 8 (near "    - 1").
```
                                                                                                                        
 [WARNING] 0 YAML files have valid syntax and 1 contain errors.

**Comment by MatTheCat** [comment]
Similar to what #39336 fixed, but I don’t understand why array examples never are displayed as comments. Do you remember @Nyholm?

**Comment by tacman** [comment]
in YamlReferenceDumper.php, $message is Examples, and is prefixed by # to comment it out.

But the array is dumped normally, but its lines, too, should be commented out.

```php
            $this->writeLine('# '.$message.':', $depth * 4 + 4);
            $this->writeArray(array_map(Inline::dump(...), $example), $depth + 1);
```

The test behavior shows this, but it doesn't make much sense, it should be

```yaml
    variable:

        # Examples:
        # - foo
        # - bar
```

I'm not sure how to write writeArray to prefix everything with a #, any suggestions?

**Comment by MatTheCat** [comment]
You could add an optional boolean `$asComment` argument to `WriteArray`? If `true`, then prefix each line with `#`.

That being said I would have done the same instead of #39336 so maybe we’re missing something :thinking:

**Comment by tacman** [comment]
Thanks, I've submitted a PR: https://github.com/symfony/symfony/pull/54326
