### ISSUE TITLE
[YamlComponent] Dump enums with `!php/enum` instead of `!php/const`

### ISSUE THREAD

**Issue by Justinas-Jurciukonis** [symfony/symfony#54150]
### Description

Yaml Component allows reading new `!php/enum SomeEnum::FOO_BAR` into actual enum.
But same code is written back, this becomes constant: `!php/const SomeEnum::FOO_BAR`

---

Allow to write enums back instead of converting them to const

### Example

```
$yamlData = <<< YAML
parameters:
    foo_bar: !php/enum App\Constant\Enum\Foo::BAR
YAML;

$yaml = Yaml::parse($yamlData, Yaml::PARSE_CONSTANT);
$yaml['parameters']['bar'] = App\Constant\Enum\Foo::BAR;

echo Yaml::dump($yaml);
/*
parameters:
    foo_bar: !php/const App\Constant\Enum\Foo::BAR
    bar: !php/const App\Constant\Enum\Foo::BAR
*/
```

**Comment by xabbuh** [comment]
This will be the case with Symfony 7.1 (see #53680).
