### ISSUE TITLE
[Serializer] Add XmlEncoder::CDATA_WRAPPING_PATTERN context option

### ISSUE THREAD

**Issue by jimmyhayek** [symfony/symfony#54155]
### Description

With the release of version 6.4, the addition of CDATA wrapping context option was introduced, which is undoubtedly great and much appreciated! https://github.com/symfony/symfony/pull/49893

However, I frequently encounter 3rd party XML consumers that require CDATA wrapping for all content. Currently, I solve this requirement with a custom modified XML encoder that enforces CDATA wrapping everywhere. It would be nice if this functionality could be configured through context options of the default XML encoder. Some questions regarding this were already hinted at in the PR for the last feature: https://github.com/symfony/symfony/pull/49893

IMHO the most feasible solution appears to be the ability to define a custom pattern for the `needsCdataWrapping` function to have full control over the CDATA wrapping. It would make it possible to enforce wrapping always or only for specific characters beyond the default ones.

### Example

```php
$data = [
    'Hello' => 'John Doe',
];

return new Response(
    $this->serializer->serialize(
        $data,
        XmlEncoder::FORMAT,
        [
            XmlEncoder::CDATA_WRAPPING_PATTERN => '/.*/'
        ]
    ),
    headers: [
        'Content-Type' => 'application/xml'
    ]
);
```

will output

```xml
<?xml version="1.0"?>
<response><Hello><![CDATA[John Doe]]></Hello></response>
```

instead of

```xml
<?xml version="1.0"?>
<response><Hello>John Doe</Hello></response>
```

**Comment by AndoniLarz** [comment]
Hi ! Thanks for the feedback !

In the PR https://github.com/symfony/symfony/pull/49893 we mentioned this question :

> Should we allow for a callback function to be used in place of a boolean (`callable(string $val): bool`) ?

This could be a solution that covers your use case, and maybe more.
But at the moment I'm not confident such a PR would be accepted.
So maybe you should gather some more feedback and use cases that would justify to add such a feature and it's inherent complexity.
