### ISSUE TITLE
[Mailer] `DataPart#setContentId` requires `@`

### ISSUE THREAD

**Issue by boesing** [symfony/symfony#54162]
### Symfony version(s) affected

6.2.0  - 7.0.5

### Description

We are using `symfony/mailer` to partially forward messages with attachments as they were received i.e. from outlook, gmail, etc. accounts.

Some mail clients seem to create attachments with content-ids not containing `@` which led to issues when forwarding those messages via `symfony/mailer`.
We do now have to generate that `@`-Part **plus** replacing the `non-@`-content id within HTML bodies. Tho it does work to manually search/replace `cid:<contentIdWithout@>`, this feels kinda weird.

From what I can read from the RFC (mentioned in the PR referenced below), there is no requirement for an `@` and since there are clients out there which do generate mails without `@` which are properly displayed in other mail clients, etc. I wonder if this "validation" is really necessary.

Refs: https://github.com/symfony/symfony/pull/46962

### How to reproduce

Extracted from the `DataPartTest#testSetContentIdInvalid` of #46962 

```php
$part = new DataPart('foo');
$part->setContentId('test');
```

### Possible Solution

Maybe, allow passing a `strict` boolean flag via `__construct` which allows projects as ours to bypass this kind of validation.
I have no idea why it had to be implemented in the first place but as I am aware of the BC contract symfony is pushing, I'd be fine with opt-in for non-strict validation.

### Additional Context

```php
    /**
     * @return $this
     */
    public function setContentId(string $cid): static
    {
        if (!str_contains($cid, '@')) {
            throw new InvalidArgumentException(sprintf('Invalid cid "%s".', $cid));
        }

        $this->cid = $cid;

        return $this;
    }
```

```php
    public function testSetContentIdInvalid()
    {
        $this->expectException(InvalidArgumentException::class);

        $p = new DataPart('content');
        $p->setContentId('test');
    }
```

**Comment by dakujem** [comment]
Bump!

Confirmed for being present since 5.x till 7.x (at least till 7.2)
![image](https://github.com/symfony/symfony/assets/443067/1f0d131a-40da-4930-914b-85862d09a438)

I dare suggest **updating the documentation** as the fastest and non-breaking way to fix this issue, the underlined parts not being accurate:
![image](https://github.com/symfony/symfony/assets/443067/560fd816-e4d2-4a48-8d82-ef7dfa38db16)
Changing `footer-signature` to `footer-signature@my-app` would do.

**Comment by fabpot** [comment]
If having `@` is not a requirement in the spec, let's remove the check. That seems the most appropriate fix here.

**Comment by dakujem** [comment]
I don't know what the spec is, to be honest.
I followed the documentation and bumped into the issue. That's why I suggested correcting the documentation to be in line with the implementation as the least-effort solution.

I may try to prepare a PR for either of the possible solutions. Let me know.

**Comment by dakujem** [comment]
I found this [RFC 2392](https://datatracker.ietf.org/doc/html/rfc2392).

It refers to `addr-spec` from [RFC 822](https://datatracker.ietf.org/doc/html/rfc822#appendix-D), which does indeed specify the format as `local-part "@" domain`.

So provided the RFCs are in use, it would seem the CID has to contain at least one `@` character. What I'm not sure is whether Symfony should or should not restrict the choice of CID.

Also, I suggest adding the info to the restriction for further clarification. Something in the line of "This restriction is in place for CID to adhere to RFC 2392 which requires URL-encoded RFC 822 addr-spec string." If someone stumbles upon the restriction in code they can refer to the documents for reasoning.

**Comment by boesing** [comment]
The issue I faced when I opened this issue on github was, that I was passing a parsed content id from a mail Ive received. The Mail was properly displayed in a bunch of Mail clients (well I guess these have to deal with a lot of stuff) and thus I was expecting that there is no requirement for an @ 

That is why I suggested to have a `strict`-like flag one can toggle when dealing with mails not properly providing a proper content id.

For now, we are adding an `@` and then search/replace the HTML body of a mail since these do contain references to the image with "invalid" content id. 

Imho thats not a good solution but works for now (we are forwarding parsed mails and thats why we have to deal with it). So it would help if at least the strictness could be toggled off so that there is no need to replace HTML body as in our case.

**Comment by fabpot** [comment]
See #57295 for a better error message.
Regarding the toggle, we tend to avoid them as much as possible in general, especially for such a very specific behavior.

**Comment by dakujem** [comment]
So if it was agreed that the `@` sign restriction should be in place, the documentation should be updated not to be misleading.

**Comment by xabbuh** [comment]
PR welcome to improve the documentation

**Comment by boesing** [comment]
> Regarding the toggle, we tend to avoid them as much as possible in general, especially for such a very specific behavior.

Understood. Thanks for the feedback.

**Comment by dakujem** [comment]
Dox PR here: https://github.com/symfony/symfony-docs/pull/19946
