### ISSUE TITLE
ERROR_NAME missing in Costraints\File.php

### ISSUE THREAD

**Issue by LukasOcy** [symfony/symfony#54170]
### Symfony version(s) affected

7.0.5

### Description

In file src/Symfony/Component/Validator/Constraints/File.php are error codes and error names defined. But they are not matching: in ERROR_NAMES the error code INVALID_EXTENSION_ERROR is missing. There for the code runs into an error in src/Symfony/Component/Validator/Constraint.php line 77 -> InvalidArgumentException

### How to reproduce

Validate a file on file extensions. 

### Possible Solution

Add missing error name.

**Comment by thomasdcodes** [comment]
Hey!
I checked the code, and @LukasOcy  is completely right. I also searched within the test folder for any logic testing the FileExtensionConstraint but didn't find anything related to that.

**Comment by xabbuh** [comment]
The issue should be fixed by #54191. But you are right, that I should probably add a test covering this.
