### ISSUE TITLE
[HttpFoundation] Avoid Bad Request exceptions when getting query parameters with default values

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#54208]
### Description

If you have this code:

```php
$page = $request->query->getInt('page', 1);
```

If someone mangles with the URL param and passes e.g. `?page=foobar` you'll see this exception:

```
HTTP 400 Bad Request
Input value "page" is invalid and flag "FILTER_NULL_ON_FAILURE" was not set.
```

Would it make sense for `getInt()` (and similar methods) to just return the default value (`1`) that you defined?

Thanks

**Comment by smnandre** [comment]
You can call `$request->query->filter(...)` to customize the behaviour.

> If someone mangles with the URL param

This is something i _personaly_ like to know/control rather than it beeing "hidden".  

Maybe we could add a thrid parameter to pass \FILTER_* options ?

**Comment by VincentLanglet** [comment]
> Maybe we could add a thrid parameter to pass \FILTER_* options ?

This seems to be a nice idea and would solve PR like https://github.com/symfony/symfony/pull/53668 or issue like https://github.com/symfony/symfony/issues/45775

**Comment by javiereguiluz** [comment]
Let's close this. As Simon said, in this situation most people probably want to know/control what's happening. What I asked for was a shortcut for `$request->query->filter(...)` with the `FILTER_NULL_ON_FAILURE` option set ... but I can use that if needed. Thanks.

**Comment by VincentLanglet** [comment]
> What I asked for was a shortcut for `$request->query->filter(...)` with the `FILTER_NULL_ON_FAILURE` option set ... but I can use that if needed. 

The main advantage of the shortcut would be the return type, especially for the static analysis.

**Comment by quentint** [comment]
I understand why this issue was closed, and I respect @javiereguiluz's point of view, but from my personal experience after updating to Symfony 7, I see a bunch of errors that could be fixed easily with new methods and/or parameters.

What seems to fail the most is with `getBoolean` and `getInt`. And having calls like this all over the place seems odd to me:

```php
$isMuted = $request->request->filter('isMuted', false, \FILTER_VALIDATE_BOOL, ['flags' => \FILTER_REQUIRE_SCALAR | \FILTER_NULL_ON_FAILURE]) ?? false;
```

Don't you think?

**Comment by PromedPromed** [comment]
For me `getBoolean` is most confusing. It even says "Returns the parameter value converted to boolean." and i would expect it to behave like boolean typecast or PHP `filter_var` (which it uses internally) - e.g. if it gets truthy string, it returns `true`, else it returns `false`. Or at most return default value when it fails. Yet it throws exception on generic strings, which limits its usefullness on user supplied input where anything can happen.

**Comment by smnandre** [comment]
I still think this could be solved with a third method argument :)

**Comment by kergekacsa** [comment]
Sad to see that there is no option to handle this confusing working method (compared to the Symfony docs), not even with a third optional parameter. :(

**Comment by Evgeny1973** [comment]
Same problem. When user send _?page=sdcdsc_ in url, i've got a same error. When i use `$page = $request->query->filter('page', 1, FILTER_NULL_ON_FAILURE);` I've got a **Warning: filter_var(): Unknown filter with ID 134217728**
(Symfony 7.1.3, PHP 8.3).
What can I do to prevent this behavior?

**Comment by kov-lucas** [comment]
> FILTER_NULL_ON_FAILURE

the correct way is doing:

```
                    $request->query->filter(
                        'page',
                        1,
                        FILTER_VALIDATE_INT,
                        ['flags' => FILTER_NULL_ON_FAILURE]
                    ),
```

**Comment by Evgeny1973** [comment]
@kov-lucas  Not working.
`$page = $request->query->filter('page', 1, FILTER_VALIDATE_INT, ['flags' => FILTER_NULL_ON_FAILURE]);`
`/?page=retg`
`dump($page)`
Result - **NULL** instead of default value 1(
The working version is
`abs($request->query->filter(key: 'page', filter: FILTER_VALIDATE_INT, options: ['options' => ['flags' => FILTER_NULL_ON_FAILURE, 'default' => 1]]));`
