### ISSUE TITLE
Add getReachingRoleNames to RoleHierarchyInterface

### ISSUE THREAD

**Issue by philepsybo** [symfony/symfony#54202]
### Description

As of now `RoleHierarchyInterface` contains `getReachableRoleNames` as its only method.
When for example I am querying the DB with the goal to get all users that can reach a certain role, it would be nice to have something like `getReachingRoleNames(array $reachableRoles)` that basically returns a set of all role-names that I encounter when I walk up the role-hierachy tree starting from all given `reachableRoles`.

Are there any arguments against something like that?

**Comment by Jean-Beru** [comment]
It seems that you are talking about https://github.com/symfony/symfony/pull/53998 ?

**Comment by philepsybo** [comment]
> It seems that you are talking about #53998 ?

Good call! I didn't find that one in the existing issues when i was looking it up. My bad! Sorry!
