### ISSUE TITLE
[Security] Type error caused by `SecurityDataCollector::getVoters()` 

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#54225]
### Symfony version(s) affected

6.4.x, 7.x

### Description

`SecurityDataCollector::getVoters()` currently has the return type `array|Data`. However, the following type error can occur:

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector::getVoters(): Return value must be of type Symfony\Component\VarDumper\Cloner\Data|array, null returned").

  at vendor\symfony\security-bundle\Resources\views\Collector\security.html.twig:394
```

```
TypeError:
Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector::getVoters(): Return value must be of type Symfony\Component\VarDumper\Cloner\Data|array, null returned

  at vendor\symfony\security-bundle\DataCollector\SecurityDataCollector.php:310
  at Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector->getVoters()
     (vendor\twig\twig\src\Extension\CoreExtension.php:1635)
```

This is because the given `AccessDecisionManager` instance might be of type `TraceableAccessDecisionManager` - but not return any voters. In such a case `$this->data['voters']` will not be initialized at all and thus `SecurityDataCollector::getVoters()` would return `null`, which is not allowed by the return type. The Twig template for the Profiler also seems to assume the `getVoters()` can return `null` - which was actually the case in previous Symfony versions, as there was only a return type annotation.

That being said - the core reason why there are not voters collected in the first place is something else entirely. The `TraceableAccessDecisionManager` does not / cannot take a decorated `AccessDecisionManager` into account, as the `getVoters()` method is not part of an interface. Thus, when you decorate Symfony's default `AccessDecisionManager`, no voters will be retrieved from the new service - unless you happen to implement a `getVoters()` method as well (see reproduction below).

### How to reproduce

A simple reproduction is to decorate the default `security.access.decision_manager` like so:

```yaml
# config/services.yaml
services:
    App\Security\DecoratedAccessDecisionManager:
        decorates: security.access.decision_manager
```
```php
// src/Security/DecoratedAccessDecisionManager.php
namespace App\Security;

use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;

class DecoratedAccessDecisionManager implements AccessDecisionManagerInterface
{
    public function __construct(public readonly AccessDecisionManagerInterface $inner)
    {
    }

    public function decide(TokenInterface $token, array $attributes, mixed $object = null): bool
    {
        return $this->inner->decide($token, $attributes, $object);
    }
}
```

If you then open the profiler and go to the _Security_ tab, the aforementioned error will occur.

### Possible Solution

Either `null`  needs to be added as an allowed return type for `SecurityDataCollector::getVoters()` - or `$this->data['voters']` always needs to be initialized with data.

**Comment by fritzmg** [comment]
In addition to the changes proposed above, the `TraceableAccessDecisionManager` should may be also be changed to take decorated decision managers into account. Currently it uses:

https://github.com/symfony/symfony/blob/f9621d318c757698cce220de63e11220e6774a63/src/Symfony/Component/Security/Core/Authorization/TraceableAccessDecisionManager.php#L44-L47

This can never work for decorated access decision managers as they will not hold the `$voters` property themselves - and so you will never see voter traces when decorating the access decision manager.

Maybe introduce an interface instead? Or at least change it to a `method_exists($manager, 'getVoters')` so that decorators have at least the chance of returning the voters from the inner service. Though I think ultimately only an interface will be the clean choice. If such an interface is introduced as a bug fix, it would need to be targeted towards `5.4` too, as the issue already exists there - but does not cause a type error.

**Comment by chalasr** [comment]
Thank you for the clear report and the additional details.

> Either null needs to be added as an allowed return type for SecurityDataCollector::getVoters() - or $this->data['voters'] always needs to be initialized with data.

I'd be in favor of making `SecurityDataCollector::getVoters()` return an empty array instead of `null`.

>  Maybe introduce an interface instead? Or at least change it to a method_exists($manager, 'getVoters') so that decorators have at least the chance of returning the voters from the inner service. Though I think ultimately only an interface will be the clean choice. If such an interface is introduced as a bug fix, it would need to be targeted towards 5.4 too, as the issue already exists there - but does not cause a type error.

Introducing an interface + making `AccessDecisionManager` implement it cannot be done as a bugfix. Such change would need to target the development branch (currently 7.1).
We have to stick with a duck-typing-based approach to fix the bug on maintenance branches. Switching from `property_exists('voters')` to `method_exists('getVoters')` looks sensible to me.

Pull Request(s) welcome to further discuss the implementation details if needed.

**Comment by fritzmg** [comment]
> I'd be in favor of making `SecurityDataCollector::getVoters()` return an empty array instead of `null`.

Sounds good. Should I target the PR against `5.4`? While the error does not occur there (since there is no strict return type), the return type annotation currently would not allow `null`.

> Pull Request(s) welcome to further discuss the implementation details if needed.

I'll provide a separate PR for that as well (for `5.4`).

**Comment by chalasr** [comment]
>  Should I target the PR against 5.4? 

Yes 👍  
> I'll provide a separate PR for that as well (for 5.4). 

Sounds good, thanks!
