### ISSUE TITLE
[AssetMapper] Who decided that importmap.php should be in project root directory ?

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#54227]
### Description

Let's just make a shit in home/root dirs just because "I am the most important" or what ?

### Example

https://github.com/symfony/recipes/blob/main/symfony/asset-mapper/6.4/manifest.json#L5

Why we have `config` dir ? Just put it all in the root

**Comment by zorn-v** [comment]
`composer.json` in the root says run `composer install`
`package.json` says `npm i`
`CMakeFiles.txt` says `mkdir build && cd build && cmake .. && make`
etc.
What says `importmap.php` ? Just some junk php file it says.

**Comment by norkunas** [comment]
If it is a shit for you, then why do you use it?

**Comment by zorn-v** [comment]
I need auto hashing css file name on deploy with `asset-map:compile` and fuck browser cache for example.

**Comment by derrabus** [comment]
> Let's just make a shit in home/root dirs just because "I am the most important" or what ?

No, sorry.
