### ISSUE TITLE
PHPUnit 11 Fatal error: Non-readonly class Success cannot extend readonly class Known in Success.php on line 17

### ISSUE THREAD

**Issue by scorpion3dd** [symfony/symfony#54229]
### Symfony version(s) affected

7.0.4

### Description

**Installed:**
- PHP 8.2.7
- Symfony 7.0.4
- phpunit/phpunit 11.0.5
- Installation Method - Composer 

**Run:**
php bin/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always

**Result:**
PHPUnit 11.0.5 by Sebastian Bergmann and contributors.                                                      
Runtime:       PHP 8.2.7                              
Configuration: /var/www/back/phpunit.xml

_Fatal error:_ Non-readonly class PHPUnit\Framework\TestStatus\Success cannot extend reado
nly class PHPUnit\Framework\TestStatus\Known in /var/www/back/vendor/phpunit/phpunit/src
/Framework/TestStatus/Success.php on line 17

**Tracing:**
in PHPUnit Framework in class TestStatus:
public static function success(): self
    {
        return new Success;
    }
when this is executed (new Success;), an error is generated (Non-readonly class ...)
Class Hierarchy
final readonly class Success extends Known
abstract readonly class Known extends TestStatus
abstract readonly class TestStatus

**Request:**
Please help me figure out this problem, because all the tests in the project stopped working (all tests show this error) after updating PHPUnit to the version 11.0.5.

### How to reproduce

**Installed:**
- PHP 8.2.7
- Symfony 7.0.4
- phpunit/phpunit 11.0.5

Write any test, for example similar to this:
class ValidatorCommentUploadTest extends KernelTestCase

**Run:**
php bin/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always

**Comment by derrabus** [comment]
* PHPUnit issues are tracked here: https://github.com/sebastianbergmann/phpunit
* For Symfony support, please visit https://github.com/symfony/symfony/discussions
