### ISSUE TITLE
[Routing][Feature] add ability to mark optional parameters (when having a suffix or more than a single separator)

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#5424]
Currently an optional variable (that has a default and can be left out from matching and generating URLs) can only be specified without any text suffix, i.e. at the end of the pattern. This is quite limiting.

@laszlokorte and I propose to add the possibility to mark the optional parts with parentheses/curly brackets. 
This can be implemented BC and would allow several new, but common use-cases, e.g.:
- one can specify optional variables anywhere in the pattern (not only at the end),
- one can use more than one char as seperator,
- an optional part that depends on multiple variables,
- flexiblity of where, what and whether there is a (trailing) seperator (see #5918).

Examples: 
- `/products(-by-{criterion}).html` would either match `/products.html` with `criterion = default` or `/products-by-price.html` with `criterion = 'price'`
- `/products(/{category}(.{_format}))` would be equivalent to how we already handle `/products/{category}.{_format}` with defaults for both variables. It matches `/products`, `/products/shoes` and `/products/shoes.html`. But it does not match `/products.html`! Compare that to
- `/products((/{category}).{_format})` (only brackets changed) where the format would match without category, but the category does not match without the format. So the inner part requires the outer part to match.
- `/products(-in-{category})(-by-{criterion}).html` matches `/products.html` and `/products-in-shoes-by-prize.html` and `/products-in-shoes.html` and `/products-by-prize.html`.
- `/products(-in-{category1}-and-{category2}).html` only matches the optional part when both variables match, so `/products-in-shoes-and-suits.html` and `/products.html`, but not `/products-in-shoes.html`.
- `/products(-by-price).html` should either raise exception that there is no variable in it, or treat it as-is (with the parentheses). It must not match both `/products.html` and `/products-by-prize.html` (where you should usually specify 2 routes for it) because there would be no way to decide which URL to generate.
- `/products/({category})` would match `/products/` and `/products/...` whereas without the parentheses it would match `/products` and `/products/...` (see #5869)
- `/{product}((-by-{criterion}).{_format})` would need a default requirement for `product` to be `[^/-\.]++` (so as seperator both `/` (standard) and `-` and `.`.  Pretty hard to compile.

Also, it should raise an exception when you specify an optional part explicitly without adding a default for the variable in it.

This feature request is somewhat related to #5129 and also covers #5869 and #10217 and #9981

**Comment by WouterJ** [comment]
Any news on this PR, is it planned for 3.0? It would be very awesome!

**Comment by ste93cry** [comment]
+1 on this issue, I would love to see it in a new Symfony release

**Comment by loostro** [comment]
Seems like everyone would love this feature, but noone is actually working on implementing this. Am I wrong?

**Comment by ste93cry** [comment]
You're right. I would like to help but I don't know the framework so good to start implementing this feature

**Comment by Tobion** [comment]
I already started it in #7051 and will try to finish it for 3.0

**Comment by loostro** [comment]
@Tobion great, I'll have a look maybe I can help somehow 8-)

**Comment by zhil** [comment]
it would be nice to issue automate 301 redirect to "most short" url.

so, for route /products(-by-{criterion}).html (which would match /products.html with criterion = default or /products-by-price.html with criterion = 'price') when somebody request /products-by-default.html issue 301 redirect to /products.html, so no duplicate content would be generated
