### ISSUE TITLE
Self-referencing parameter for entity field

### ISSUE THREAD

**Issue by AyrxCore** [symfony/symfony#54282]
### Description

Add an optionnal "self-referencing" parameter for entity fields in case of you want an entity field wich self-refering himself in a OneToMany relationship for example.
It's to avoid having to create another unused field to satisfy the One to Many relationship

**Comment by xabbuh** [comment]
This looks like a feature request for Doctrine ORM. Please open an issue there.

**Comment by AyrxCore** [comment]
Ok thanks
