### ISSUE TITLE
Dotenv Component does not retrieve the APP_ENV correctly from the shell when invoking public/index.php

### ISSUE THREAD

**Issue by Mauriceu** [symfony/symfony#54289]
### Symfony version(s) affected

6.4.4

### Description

I run Symfony inside a Docker image and define the APP_ENV as a real envvar with value "prod".
The Dotenv component should load 2 .env files: .env and .env.prod
Neither of those files define a value for the APP_ENV variable, it should only come from the shell.

When executing a request against any endpoint the default value "dev" is used for the APP_ENV. This leads to errors like "Attempted to load ****Bundle. Did you forget a use statement?", where "****Bundle" is actually a dev-dependency. But as you probably guessed, these are not installed in prod-environments.

I tried adjusting the "variables_order" value in my php.ini to:
> variables_order = "GPCSE"

But without luck.

### How to reproduce

Do not define any APP_ENV variable inside your .env files.
Make sure your webserver injects the APP_ENV envvar into the php process invoking the Symfony runtime (eg. for apache add "SetEnv APP_ENV prod" to your vhost config).
Optional: execute "composer install --no-dev" to exclude dev-dependencies
Execute a request against any endpoint of your Symfony application.

Check your cache and log directories for a "dev" directory, this indicates the Symfony Runtime was invoked in dev-mode. Or, if you ran the composer install command, see your application run into a 500 error.

### Additional Context

I added the following print statements:

 Beginning of the **bin/console** file:
`
        print
            "Console.php: \n ".
            "Server: " . $_SERVER["APP_ENV"] . "\n " .
            "Env: " . $_ENV["APP_ENV"] . "\n";
`

Beginning of the **public/index.php** file:
`
        print
            "Index.php: \n ".
            "Server: " . $_SERVER["APP_ENV"] . "\n " .
            "Env: " . $_ENV["APP_ENV"] . "\n";
`

Line 111 in the **Dotenv.php file** (namespace Symfony\Component\Dotenv). Right before the Dotenv component checks if the APP_ENV key is set in either $_SERVER or $_ENV, and if neither is set, uses the default value "dev":
`
        print
            "Dotenv.php: \n ".
            "Server: " . $_SERVER["APP_ENV"] . "\n " .
            "Env: " . $_ENV["APP_ENV"] . "\n";
`

Executing a bin/console command works like a charm. The print statement outputs:

> Console.php: 
   Server: prod
   Env: prod

> Console.php: 
   Server: prod
   Env: prod

> Dotenv.php: 
   Server: prod
   Env: prod

Executing a request against any endpoint will output this:

> Index.php: 
 Server: 
 Env:  

> Index.php: 
 Server: 
 Env: 

> Dotenv.php: 
 Server:
 Env: 
 

I assume this is non-intended behaviour, but its not unlikely my ass just configured something incorrectly...
Help is appreciated!

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
If you define `APP_ENV` as a shell variable, check whether the webserver actually runs with with this env variable being set (it depends how you launch it). And depending on the webserver you use, you might also need to configure it to forward env variables to the processes handling requests (not all of them do it by default).

**Comment by Mauriceu** [comment]
Thank you both for the quick reaction.

@stof Yea the webserver runs with APP_ENV set to prod, checked that multiple times with the "env" command. The shell also provides secrets which are used correctly, so the php process should have access to it.



@xabbuh 
https://github.com/Mauriceu/symfony-6-4-dotenv-issue-54289.git

Edit: I edited this, because running "export APP_ENV=prod" is surely enough to reproduce the error, because the APP_ENV is then only scoped to the current shell... If you check the dockerfile, the APP_ENV is now defined as envvar that is accessible by the container, so I recommend reproducing this error by running "docker compose up".


Steps:
- composer install --no-dev
- docker compose up
If you access localhost:8000, you should see a 500 error with 'Attempted to load class "MakerBundle" from namespace "Symfony\Bundle\MakerBundle". Did you forget a "use" statement for another namespace?'

**Comment by Mauriceu** [comment]
Another weird issue: Setting an envvar, eg. REDIS_PASSWORD in .env.prod with an empty value, and also setting it as a real env, will lead to the Dotenv component using the value from .env.prod. I had multiple envvars that were initialized with an empty value (due to symfony checking if envvars used in config files exist), but the real envvar did not override it.
Running "php bin/console dotenv:dump" will create the .env.local.php file where the value for REDIS_PASSWORD is empty. 
Running "php bin/console debug:container --env-vars" shows the REDIS_PASSWORD variable with the non-empty real envvar value, which is correct. But when invoking a Route, the Predis component would throw a "No Auth" error, because REDIS_PASSWORD is empty.

I fixed this by removing all variables from my .env files that were also real envvars, which was kind of messy. But the Dotenv component is not supposed to override shell variables by default...I am kinda lost here.

If this issue is of interest, I could extend the public repo I posted earlier to include it.

**Comment by Mauriceu** [comment]
Of note is probably that I am running symfony within docker. 
Maybe setting "ENV APP_ENV=prod" in my dockerfile is not enough to expose this variable to the php process...but then again, setting "SetEnv APP_ENV prod" on my apache leads to the same result.

**Comment by MatTheCat** [comment]
FYI I have no problem with your reproducer: the inferred environment is `prod` as expected.

**Comment by Mauriceu** [comment]
> FYI I have no problem with your reproducer: the inferred environment is `prod` as expected.

Well, either its onset schizophrenia or my system wants to ef with me. The repo is working for me too. I will run another deployment with an identical configuration and see what happens...

**Comment by xabbuh** [comment]
Let's close here for now then as this does not look related to the Dotenv component.
