### ISSUE TITLE
Different type for empty Flash Messages

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/symfony#54295]
### Symfony version(s) affected

7.0.3

### Description

`app.flashes` in Twig returns an object `{...}`. But when there are no flashes it returns empty array `[]` which is confusing and causes error in Stimulus which expects an Object. It should return empty object `{}`.

### How to reproduce

use app.flashes in twig as usual

**Comment by NeilPeyssard** [comment]
Hello,

`app.flashes` always returns an array on the PHP side.

Because it's an associative array, if you encode `app.flashes` in json to send it in a stimulus controller, yes, his type can vary if it's empty.

If you want to always have an object, even if the array is empty, you can use:

```twig
{{ app.flashes|json_encode(constant('JSON_FORCE_OBJECT')) }}
```

**Comment by DavidPetrasek** [comment]
Thank you. I take it as a solution.
