### ISSUE TITLE
Unable to send a form

### ISSUE THREAD

**Issue by MathieuLePuil** [symfony/symfony#54300]
### Symfony version(s) affected

7.0.4

### Description

When I send a form, it will never be defined as submitted in my controller. So I can't retrieve data from it.

### How to reproduce

https://github.com/MathieuLePuil/SymfonyFormBug

To reproduce the bug, start the server, go to /test and fill in the form. The form will never be sent and the dump will not be displayed.

**Comment by stof** [comment]
you are missing the line `$form->handleRequest($request)` in your controller.
