### ISSUE TITLE
[DependencyInjection] Improve error message for missing extensions able to load config files

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#54336]
Related to https://github.com/symfony/symfony-docs/pull/19655

-----

When you have some bundle configuration file in your app and the bundle is not installed/enabled, you see an error message like this:

```
There is no extension able to load the configuration for "security"
(in (...)/config/packages/security.yaml). Looked for namespace "security",
found "framework", "web_server", "maker", "doctrine_cache", "doctrine",
"doctrine_migrations", "twig", "...", "knp_paginator" in
(...)/config/packages/security.yaml (which is loaded in
resource "(...)/config/packages/security.yaml").
```

This is generated in:

https://github.com/symfony/symfony/blob/9ba818e93c1d109102f8c333f935886918b7ce6b/src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php#L186

and

https://github.com/symfony/symfony/blob/9ba818e93c1d109102f8c333f935886918b7ce6b/src/Symfony/Component/DependencyInjection/Loader/Configurator/ContainerConfigurator.php#L61

-----

**Problem**: this error message is probably not perfectly clear for all developers, mostly newcomers. See e.g. https://stackoverflow.com/questions/55279011/there-is-no-extension-able-to-load-the-configuration-for-security

**Possible solution**: if we agree on improving this error message, we could do the same we do in other parts of Symfony, such as:

https://github.com/symfony/symfony/blob/9ba818e93c1d109102f8c333f935886918b7ce6b/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L2131-L2133

and:

https://github.com/symfony/symfony/blob/9ba818e93c1d109102f8c333f935886918b7ce6b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L287-L291

We could remind developers to install the related bundle of a missing extension. Just hardcoding a few of the popular first-party/second-party bundles (security, twig, doctrine, etc.) would be enough.

Thanks!

**Comment by lyrixx** [comment]
I like it 👍🏼

**Comment by nicolas-grekas** [comment]
I just wouldn't hardcode anything directly in loaders, but we could likely find a way to centralize this knowledge like we did for twig functions in UndefinedCallableHandler.

**Comment by lyrixx** [comment]
we can even try to call packagist API...
