### ISSUE TITLE
[Doctrine] Improve MySQL Keywords list

### ISSUE THREAD

**Issue by tcoch** [symfony/symfony#54373]
### Description

MySQL keyword list stops at 8.0, while MySQL 8.3 is out. The keyword list should be updated (see Doctrine\DBAL\Platforms\KeywordsMySQL80Keywords).
I will try and submit a PR for this.

**Comment by derrabus** [comment]
This is the Symfony repository, you're looking for Doctrine DBAL.

https://github.com/doctrine/dbal/
