### ISSUE TITLE
Chrome 123 breaks VarDumper

### ISSUE THREAD

**Issue by grzegorztomasiak** [symfony/symfony#54397]
### Symfony version(s) affected

3.4

### Description

Since Chrome v123 dump() is not working in network tab anymore, not parsing script.

![image](https://github.com/symfony/symfony/assets/5319920/65fbb0fc-92f6-4aba-a47c-c5868b3d6257)

Anyone knows the solution?

### How to reproduce

Get any rest API controller, and dump('not okay'); die;

### Additional Context

It works with Chrome 122. Updating to latest 123 breaks the dump().

**Comment by MatTheCat** [comment]
This is not a Symfony bug: see https://issues.chromium.org/issues/328471611

**Comment by nicolas-grekas** [comment]
Thanks for the link.
