### ISSUE TITLE
[DoctrineBridge] LockStoreSchemaListener not working properly

### ISSUE THREAD

**Issue by barton-webwings** [symfony/symfony#54406]
### Symfony version(s) affected

6.4.4

### Description

After installing `symfony/lock` and configuring it with `DoctrineDbalStore`, I noticed that invoking `doctrine:migrations:diff` command would generate a migration issuing a `DROP` of the autogenerated `lock_keys` table.

After investigating, I found out the issue is [line 33 of the listener](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Doctrine/SchemaListener/LockStoreSchemaListener.php#L33). The `$stores` property receives a `RewindableGenerator`, which is then passed directly to an `ArrayIterator`. This produces an invalid iterator, skipping the whole following `while` loop.

### How to reproduce

1. Configure `symfony/lock` with a `DoctrineDbalStore`.
2. Generate the `lock_keys` table, either by using the `LockFactory` or by any other means mentioned in the [docs](https://symfony.com/doc/current/components/lock.html#doctrinedbalstore).
3. Run the `doctrine:migrations:diff` command.
4. See that the the schema for the table is not properly configured, resulting in a migration instead of the expected `No changes detected in your mapping information.` message.

### Possible Solution

Since the `$stores` property is already typed as `iterable`, it would seem replacing the loop with a `foreach` iterating directly on the property would be the best solution.

**Comment by robwdwd** [comment]
Same issue in 7.0, seems the PR to fix a niche case use of the lock component has broken functionality.

**Comment by uwej711** [comment]
Just spent some time finding out why LockStoreSchemaListener does not work in 6.4 before coming here. Is there a chance the existing PR will get merged into 6.4 (or will the changes that cause this reverted for 6.4)?

**Comment by MatTheCat** [comment]
@uwej711 this seems unlikely given the confusion #50761 have caused: it broke the `LockStoreSchemaListener` passing a ”feature” for a bugfix, so maintainers don’t want to revert it because that would mean reintroducing the “bug”. But, as it was in fact a new feature you cannot implement it on the 6.4 branch. So it’s stuck like this.

**Comment by barton-webwings** [comment]
For anyone finding this issue until it is resolved, I can share one of the ways you can work around this.

https://gist.github.com/barton-webwings/4ddf9446d0c640d44fe41880202e0105
