### ISSUE TITLE
Typed property Symfony\Component\Serializer\Normalizer\AbstractNormalizer::$serializer must not be accessed before initialization

### ISSUE THREAD

**Issue by pnxzadrot** [symfony/symfony#54417]
### Symfony version(s) affected

7.0.3

### Description

Then I use class GetSetMethodNormalizer or ObjectNormalizer method normalize for get array I catch Typed property Symfony\Component\Serializer\Normalizer\AbstractNormalizer::$serializer must not be accessed before initialization problem. Maybe I need put something in Normalizer construct?

### How to reproduce

 $normalizer = new ObjectNormalizer();
$data = $normalizer->normalize($entity);

 $this->normalizer = new GetSetMethodNormalizer();
 $data = $ $this->normalizer->normalize($entity);

**Comment by mtarld** [comment]
Hey @pnxzadrot,

I cannot reproduce your issue, indeed I created the following test, and it does seem to work:
```php
/**
 * @group 7.0
 */
final class Issue54417Test extends TestCase
{
    public function testBug(): void
    {
        $object = new ExampleObject54417();
        $object->value = 'foo';

        $this->assertSame(['value' => 'foo'], (new ObjectNormalizer())->normalize($object));
        $this->assertSame(['value' => 'foo'], (new GetSetMethodNormalizer())->normalize($object));
    }
}

class ExampleObject54417
{
    public string $value;

    public function getValue(): string
    {
        return $this->value;
    }
}
```

Can you provide a more specific reproducer?

**Comment by pnxzadrot** [comment]
Thanks for answer @mtarld
Did you say, what you need from me to reproduce problem?
I use next code
```
    public function normalize(AbstractTask $entity): array
    {
        $normalizer = new ObjectNormalizer();
        $data = $normalizer->normalize($entity);
        $data["taskCreationTypeId"] = $data["taskProblemTypeId"];
        foreach ($data  as $key => $value) {
            $key = str_replace('Id', '', $key);
            $data[$key] = $value;
            $key = str_replace('task', '', $key);
            $key = lcfirst($key);
            $data[$key] = $value;
        }
        return $data;
    }
    ```
    
    ```
    abstract class AbstractTask
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['task:get', 'task:get_collection', 'task:update'])]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }
}
```

    /**
     * @param Task $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Task|null
    {

        if(is_null($data->getCreatedAt())){
            $data->setCreatedAt(new \DateTimeImmutable('now'));
        }
        if(is_null($data->getAuthorId())){
            $data->setAuthorId($this->security->getUser()->getId());
        }

        $task = new Entity();
        $task->setCreatedBy($data->getAuthorId())->setCreatedAt($data->getCreatedAt());
        $this->em->persist($task);
//        $this->em->flush();

        foreach ($this->builder->normalize($data) as $key => $value) {
            dump([$key, $value]);
            $this->create($this->properties[$key], $task, PropertyType::Entity, $value);
        }

        aaa;
        $this->createStatus($task, $this->createStatus);
        if(!is_null($data->getStatus()) && $data->getStatus() != $this->createStatus){
            $this->createStatus($task, $data->getStatus());
        }

        $this->createComment($task, $data->getComment());
        $this->em->flush();

        dump($data);
        if ($operation instanceof DeleteOperationInterface) {
            return $this->removeProcessor->process($data, $operation, $uriVariables, $context);
        }

        return $this->persistProcessor->process($data, $operation, $uriVariables, $context);
    }
    
    ```
    
    ```
    abstract class Task extends AbstractTask
{
//    #[ORM\Column]
    #[Context([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d H:i:s'])]
    #[Groups(['task:get', 'task:get_collection'])]
    #[ApiFilter(DateFilter::class)]
    private ?\DateTimeImmutable $createdAt = null;

//    #[ORM\Column(nullable: true)]
    #[Context([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d H:i:s'])]
    #[Groups(['task:get', 'task:get_collection', 'task:update'])]
    #[ApiFilter(DateFilter::class)]
    private ?\DateTimeImmutable $closedAt = null;

//    #[ORM\Column]
    #[Groups(['task:get', 'task:get_collection'])]
    private ?int $authorId = null;

//    #[ORM\Column(nullable: true)]
    #[Groups(['task:get', 'task:get_collection'])]
    private ?int $performerId = null;
//    #[ORM\OneToMany(mappedBy: 'task', targetEntity: TaskComment::class, orphanRemoval: true)]
    #[Groups(['task:get', 'task:get_collection'])]
    private Collection $taskComments;

//    #[ORM\OneToMany(mappedBy: 'task', targetEntity: TaskStatuses::class)]
    #[Groups(['task:get', 'task:get_collection'])]
    private Collection $taskStatuses;

//    #[ORM\Column(nullable: false)]
    #[Groups(['task:get', 'task:get_collection', 'task:create', 'task:update'])]
    private ?int $taskProblemTypeId = null;

//    #[ORM\Column(nullable: true)]
    #[Groups(['task:get', 'task:get_collection', 'task:create', 'task:update'])]
    private ?int $taskClosureTypeId = null;

//    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    #[Groups(['task:get', 'task:get_collection', 'task:create', 'task:update'])]
    private array $note = [];

//    #[ORM\Column(nullable: true)]
    #[Groups(['task:get', 'task:get_collection', 'task:create', 'task:update'])]
    private ?int $taskSolutionTypeId = null;

    #[Groups(['task:get', 'task:get_collection', 'task:create', 'task:update'])]
    private ?PropertyTaskInterface $solutionType = null;

    #[Groups(['task:create', 'task:update'])]
    private ?string $comment = null;

    #[Groups(['task:update'])]
    private ?int $status = null;

    public function __construct()
    {
        $this->taskComments = new ArrayCollection();
        $this->taskStatuses = new ArrayCollection();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getClosedAt(): ?\DateTimeImmutable
    {
        return $this->closedAt;
    }

    public function setClosedAt(?\DateTimeImmutable $closedAt): static
    {
        $this->closedAt = $closedAt;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->authorId;
    }

    public function setAuthorId(int $authorId): static
    {
        $this->authorId = $authorId;

        return $this;
    }

    public function getPerformerId(): ?int
    {
        return $this->performerId;
    }

    public function setPerformerId(?int $performerId): static
    {
        $this->performerId = $performerId;

        return $this;
    }

    /**
     * @return Collection<int, TaskComment>
     */
    public function getTaskComments(): Collection
    {
        return $this->taskComments;
    }

    public function addTaskComment(TaskComment $taskComment): static
    {
        if (!$this->taskComments->contains($taskComment)) {
            $this->taskComments->add($taskComment);
            $taskComment->setTask($this);
        }

        return $this;
    }

    public function removeTaskComment(TaskComment $taskComment): static
    {
        if ($this->taskComments->removeElement($taskComment)) {
            // set the owning side to null (unless already changed)
            if ($taskComment->getTask() === $this) {
                $taskComment->setTask(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TaskStatuses>
     */
    public function getTaskStatuses(): Collection
    {
        return $this->taskStatuses;
    }

    public function addTaskStatus(TaskStatuses $taskStatus): static
    {
        if (!$this->taskStatuses->contains($taskStatus)) {
            $this->taskStatuses->add($taskStatus);
            $taskStatus->setTask($this);
        }

        return $this;
    }

    public function removeTaskStatus(TaskStatuses $taskStatus): static
    {
        if ($this->taskStatuses->removeElement($taskStatus)) {
            // set the owning side to null (unless already changed)
            if ($taskStatus->getTask() === $this) {
                $taskStatus->setTask(null);
            }
        }

        return $this;
    }

    public function getTaskProblemTypeId(): ?int
    {
        return $this->taskProblemTypeId;
    }

    public function setTaskProblemTypeId(?int $taskProblemTypeId): static
    {
        $this->taskProblemTypeId = $taskProblemTypeId;

        return $this;
    }

    public function getTaskClosureTypeId(): ?int
    {
        return $this->taskClosureTypeId;
    }

    public function setTaskClosureTypeId(?int $taskClosureTypeId): static
    {
        $this->taskClosureTypeId = $taskClosureTypeId;

        return $this;
    }

    public function getNote(): array
    {
        return $this->note;
    }

    public function setNote(array $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getTaskSolutionTypeId(): ?int
    {
        return $this->taskSolutionTypeId;
    }

    public function setTaskSolutionTypeId(?int $taskSolutionTypeId): static
    {
        $this->taskSolutionTypeId = $taskSolutionTypeId;

        return $this;
    }

    public function getSolutionType(): ?PropertyTaskInterface
    {
        return $this->solutionType;
    }

    public function setSolutionType(PropertyTaskInterface $solutionType): self
    {
        $this->solutionType = $solutionType;
        $this->solutionType->setTask($this);

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;
        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;
        return $this;
    }

}

```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by pnxzadrot** [comment]
@xabbuh
I create small docker image for this problem
```
docker pull pnxzadrot/test:normalize_test
docker run pnxzadrot/test:normalize_test
docker exec -it CONTAINER ID bash
php bin/phpunit
```

Error: Typed property Symfony\Component\Serializer\Normalizer\AbstractNormalizer::$serializer must not be accessed before initialization

/var/www/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:204
/var/www/tests/Test.php:19
/var/www/tests/Test.php:13
/var/www/vendor/phpunit/phpunit/phpunit:107

**Comment by xabbuh** [comment]
@pnxzadrot Thank you 👍 Do you also have a repository where we can see the source code?

**Comment by pnxzadrot** [comment]
@xabbuh 
https://github.com/pnxzadrot/normalize_test

**Comment by xabbuh** [comment]
Great, I was able to reproduce the issue with your application. 👍 #54505 will fix it.
