### ISSUE TITLE
Cannot Make Entity Properly using make:entity with Sym5.4 with symfony/webapp-pack:*

### ISSUE THREAD

**Issue by l0r3nc335** [symfony/symfony#54438]
### Symfony version(s) affected

5.4

### Description

I am using Symfony 5.4 and installed the web app bundle by running the command "composer require symfony/webapp-pack:*",
However, when I tried to run bin/console make: entity, an error occurred, asking about the DisconnectedClassMetadataFactory (use Doctrine\ORM\Tools\DisconnectedClassMetadataFactory;) being forgotten to use 'use'?

**Steps to replicate:**
>composer create-project symfony/skeleton:"5.4.*" project   (older version)
>composer require symfony/webapp-pack:*
>bin/console make:entity

![image](https://github.com/symfony/symfony/assets/41465100/34025915-bcd6-4589-893f-13d2342e3524)

**DoctrineHelper.php line 177:
attempted to load class "DisconnectedClassMetadataFactory" from namespace "Doctrine\ORM\Tools".  
  Did you forget a "use" statement for another namespace?**
  

**CHECKING THE SAID FILE**
The DoctrineHelper.php is already using the said class,
use Doctrine\ORM\Tools\DisconnectedClassMetadataFactory;
But it is not found in Doctrine\ORM\Tools\
![image](https://github.com/symfony/symfony/assets/41465100/015ef3ed-b99d-4e14-800a-c4ab638a359b)

I still need to stick with Symfony 5.4 while using the compatible version of symfony/webapp-pack.

What is the solution to this bug?

### How to reproduce

**Steps to replicate:**
>composer create-project symfony/skeleton:"5.4.*" project   (older version)
>composer require symfony/webapp-pack:*
>bin/console make:entity

**Comment by MatTheCat** [comment]
This is not a Symfony bug; downgrade doctrine/orm to v2 and everything should work as expected.
