### ISSUE TITLE
DomCrawler encodes html entities inside script tags

### ISSUE THREAD

**Issue by ausi** [symfony/symfony#54437]
### Symfony version(s) affected

5.4.37

### Description

The `Crawler` encodes html entities before parsing it in https://github.com/symfony/symfony/blob/f28e58eef622a4524b8ada8ddf252130a39094fa/src/Symfony/Component/DomCrawler/Crawler.php#L1184 which causes the contents of script tags to be corrupt (because HTML entities have no meaning between `<script>` and `</script>`).

### How to reproduce

```php
$crawler = new Crawler();
$crawler->addContent('<!doctype html><html><script>var foo = "bär";</script></html>', 'text/html; charset=UTF-8');
echo $crawler->filterXPath('//script')->text();
// output: var foo = "b&#228;r";
// expected: var foo = "bär";
```

### Possible Solution

I’m not sure what’s the best way to fix it as `convertToHtmlEntities()` cannot distinguish between outside and inside `<script>`. But as it seems that `convertToHtmlEntities()` is only there to fix issues with the libxml parser, maybe it can be skipped if the `Masterminds\HTML5` is used?

**Comment by stof** [comment]
if `Masterminds\HTML5` does not need the conversion, skipping it is indeed a solution.
PRs are welcome to implement that.
