### ISSUE TITLE
SwitchUserToken::getOriginalToken returns user with different Id when ID is a UUID

### ISSUE THREAD

**Issue by Geolim4** [symfony/symfony#54446]
### Symfony version(s) affected

6.4.5

### Description

When you impersonate a user and try to access to the original impersonator user by calling `\Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken::getOriginalToken` the user ID returned is ok if its an integer.

However if your user ID is a Uuid Object like `Symfony\Component\Uid\Uuid` the returned ID is... Unknown, I mean, I looked for it in the database but I don't know where this UUID come from.

However the `\Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage::getToken` seems not to be impacted by this issue and is returning me the good User object with the right Uuid.

My guess us that `\Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken::getOriginalToken`  might be serialized because Doctrine does not recognize this entity so the UUID is corrupted somewhere during serialize/wakeup operations.

My workaround for now is to re-fetch  my User object from the repository using User#email since the Uuid ID is not reliable.

### How to reproduce

Create a user entity that use a `Symfony\Component\Uid\Uuid` as an ID.
- Impersonate a user
- Try to access `\Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken::getOriginalToken`
- User Uuid ID is different from the one stored in the database.

### Possible Solution

A penny on `\Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken::__unserialize` that might corrupt the Uuid during the serialization, but unsure atm.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Geolim4** [comment]
Everything is described above, there's no need for specific application, especially my code being private x)

**Comment by xabbuh** [comment]
Well, providing a small application that one can simply check out to debug the behaviour increases the likelihood that someone is actually trying to find out what is going on.

**Comment by chalasr** [comment]
Closing until we have a real reproducer as it makes it easy for anyone to confirm and/or fix the reported bug. Please comment here when you have one so we can consider reopening.

**Comment by Geolim4** [comment]
Nice way of managing bugs while everything is clearly explained above. You
clearly don't make anything in the right way to make people contributing to
OSS.

And I say that as a fellow colleague from Smile.

Disappointed (but not surprised).

**Comment by xabbuh** [comment]
Open source is not only about taking for free, but requires to give back. I tried to reproduce your issue with what you described, but that wasn’t an issue. That’s why I asked for a reproducer. If you are not motivated to put more effort into it, that’s fine, but don’t demand from others what you are not willing to invest. Have a nice day.

**Comment by Geolim4** [comment]
> **Open source is not only about taking for free, but requires to give back**

Yeah thanks, that's why I put almost an hour to write you a well-formatted and understandable issue and you just please yourself trashing contributors because they do not gave the ready-to-work sample of code that, in my case, will absolutely not give you better context than the first post. 🤨
But if you insist, there's is the contextualized issue so you won't blame me anymore for being an useless contributor:

![image](https://github.com/symfony/symfony/assets/1332071/b1d758df-f359-4433-acbb-9d560b543c90)
![image](https://github.com/symfony/symfony/assets/1332071/a2dad224-d742-4d92-90f9-3f9c2feb1aa9)

In commented line of the first screen, the Uuid binary/hex is completely different from the one stored in database.
Which is weird because the rest of the object is completely similar to the one provided by DC2.

**Comment by chalasr** [comment]
> Nice way of managing bugs while everything is clearly explained above. 

We've invited you to provide some runnable code that triggers **your** issue, just to allow us to investigate and fix it **for you**. That does not seem too expensive for something you didn't bother/manage to fix on your own yet. 

> You clearly don't make anything in the right way to make people contributing to OSS.

You're talking to some of the maintainers of a project whose code has been contributed by ~3000 people, mostly on their free time. I'm not sure it is fair for you to have such a bad and aggressive judgment.

> And I say that as a fellow colleague from Smile.

This is not a Smile project, but an open-source one.

> Disappointed (but not surprised).

Please keep respectful and avoid such negative statements to communicate within this project in the future, as required by its [Code of Conduct](https://symfony.com/doc/current/contributing/code_of_conduct/code_of_conduct.html)

> so you won't blame me anymore for being an useless contributor

Nobody did so.
