### ISSUE TITLE
Subscribed services does not work with inheritance

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#54452]
### Symfony version(s) affected

v6.4.4

### Description

I attempted to use an abstract service implementing `ServiceSubscriberInterface` with the trait `ServiceSubscriberTrait`. I am however running into the following error:

```
ServiceNotFoundException: Service "Acme\ConcreteService::subscribedServiceName" not found: the container inside "Acme\ConcreteService" is a smaller service locator that is empty...
```

Before going any deeper into this, is it a known/intended limitation? If not I'll work on getting a reproducer, provided I'm not the one doing anything weird.

### How to reproduce

To be provided.

### Possible Solution

To be discussed.

**Comment by ro0NL** [comment]
> When extending a class that also implements ServiceSubscriberInterface, it's your responsibility to call the parent when overriding the method (https://symfony.com/doc/current/service_container/service_subscribers_locators.html#including-services)

but im not sure why we'd ever need the possibility to NOT inherit parent services :shrug:

**Comment by stof** [comment]
Automatically inheriting the parent services would require the caller of the method to do reflection-based magic to identify parent method implementations to call them directly as well (and then dealing with cases where your implementation already merges its subscribed services with the parent). I don't think this is necessary.

**Comment by theofidry** [comment]
Thanks @ro0NL missed it as I was checking the trait section directly.

@stof that's fair, although not ideal as then can use the trait in an abstract class without any warning that it will actually not work. It's fine though, you may force to implement the interface without adding the trait to at least not confuse the implementor of your service.
