### ISSUE TITLE
symfony/http-client-contracts 3.4.1 (not tagged)

### ISSUE THREAD

**Issue by Chris53897** [symfony/symfony#54469]
### Symfony version(s) affected

7.0.6

### Description

While running `composer update` i get the following update.
_Upgrading symfony/http-client-contracts (v3.4.0 => dev-main 46a7e30)_

Reason:
`composer why "symfony/http-client-contracts"`
_symfony/http-client   v7.0.6 requires  symfony/http-client-contracts (^3.4.1)_ 

Problem:
No Tag available yet for 3.4.1

### How to reproduce

composer update

### Possible Solution

Create a Tag for 3.4.1 
https://github.com/symfony/http-client-contracts/tags

**Comment by fabpot** [comment]
Fixed now.
