### ISSUE TITLE
[VarExporter] Mapping Expception - Ignore can only be added on methods beginning with "get", "is", "has" or "set".`

### ISSUE THREAD

**Issue by sgloe** [symfony/symfony#54477]
### Symfony version(s) affected

6.4.6

### Description

After upgrading symfony/var-exporter from 6.4.4 to 6.4.6 I get an error during my serialization process.

`Ignore on "Proxies\__CG__\App\Entity\Artist::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".`

vendor/symfony/serializer/Mapping/Loader/AttributeLoader.php:172

### How to reproduce

Use Serializer and serialize some objects with relations and setting the context.

**Comment by nicolas-grekas** [comment]
Can you please send a PR to remove the annotation where it shouldn't be found?

**Comment by Gemorroj** [comment]
same issue. new release (7.0.6) completely broke website

**Comment by jkgroupe** [comment]
Same here, I was creating an issue but you were faster than me and you found the issue origin

I downgraded from Symfony 6.4.6 to 6.4.5 

**composer.json**
```
"symfony": {
      "allow-contrib": false,
      "require": "6.4.*, !=6.4.6"
}
```

**Comment by eisberg** [comment]
This PR breaks: https://github.com/symfony/symfony/pull/54224 

Ignore attribute in file src/Symfony/Component/VarExporter/LazyGhostTrait.php

```php
 #[Ignore]
    private function setLazyObjectAsInitialized(bool $initialized): void
    {
```

**Comment by xabbuh** [comment]
I fail to see why the `Ignore` attribute on `setLazyObjectAsInitialized()` should be the culprit as that method follows the pattern the `AttributeLoader` accepts for an accessor or mutator.

Can anyone affected by this bug please create a small example application that allows to reproduce it?

**Comment by nicolas-grekas** [comment]
That's because Doctrine is aliasing this method to another name.

**Comment by nicolas-grekas** [comment]
> setLazyObjectAsInitialized as public __setInitialized;

**Comment by 99hops** [comment]
I just saw the same issue 6.4.5 works fine.

**Comment by Josee9988** [comment]
Same here with symfony 7.0.6

**Comment by sebheitzmann** [comment]
I have the same problem in a MessageHandler. 
Why it this issue closed ?

**Comment by xabbuh** [comment]
@sebheitzmann The PR fixing this issue (#54485) has been merged and will be part of the next patch releases.
