### ISSUE TITLE
[Clock] DatePoint created with fixed date should be set at midnight

### ISSUE THREAD

**Issue by clement-michelet** [symfony/symfony#54497]
### Symfony version(s) affected

6.4.5

### Description

PHP: 8.1

> The DatePoint class extends DateTimeImmutable, so you can use it in your code anywhere a DateTimeImmutable or DateTimeInterface is expected.

I would expect that the behavior of DatePoint does not differ from DateTimeImmutable to use as a pure replacement. However, I cannot use it as it is everywhere (including in test cases) because creating a date with a fixed date keep the current time.

See the repro below.

### How to reproduce

```php
<?php

$datePoint = new \Symfony\Component\Clock\DatePoint('2024-01-01');
$immutableDate = new \DateTimeImmutable('2024-01-01');

\PHPUnit\Framework\Assert::assertEquals('2024-01-01 00:00:00', $immutableDate->format('Y-m-d H:i:s')); // Pass
\PHPUnit\Framework\Assert::assertEquals('2024-01-01 00:00:00', $datePoint->format('Y-m-d H:i:s')); // Fails
```

### Possible Solution

* Add documentation about the different behavior and that DatePoint differs from DateTimeImmutable (not a pure replacement)
* Or introduce a named constructor keep the different behavior and leave the native constructor

**Comment by stof** [comment]
Keeping the current type in that case looks like a bug to me.

/cc @nicolas-grekas

**Comment by smnandre** [comment]
In the meanwhile (as temporary solution), you can leverage `createFromFormat` with the `|`  special character.

```php
$datePoint =  DatePoint::createFromFormat('Y-m-d|', '2024-01-01');
$immutableDate = \DateTimeImmutable::createFromFormat('Y-m-d|', '2024-01-01');

self::assertEquals('2024-01-01 00:00:00', $datePoint->format('Y-m-d H:i:s')); // Pass
self::assertEquals('2024-01-01 00:00:00', $immutableDate->format('Y-m-d H:i:s')); // Pass
```

**Comment by OskarStark** [comment]
@stof you mean s/type/time ?

**Comment by xabbuh** [comment]
see #54530

**Comment by stof** [comment]
@OskarStark indeed.
