### ISSUE TITLE
[HtmlSanitizer] Processing instructions misinterpreted as elements

### ISSUE THREAD

**Issue by ndossche** [symfony/symfony#54492]
### Symfony version(s) affected

7.0, perhaps lower too

### Description

You're checking the node name in the node traversal, but not the node type.
So creating a processing instruction with the name of an allowed element results in a misinterpretation: the processing instruction will be considered as if it is an element. Fortunately, this has no security impact because we can only misinterpret nodes into an allowed element.

### How to reproduce

```php
<?php
require 'vendor/autoload.php';

use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;
use Symfony\Component\HtmlSanitizer\HtmlSanitizer;

$config = (new HtmlSanitizerConfig())->allowElement("div");

$sanitizer = new HtmlSanitizer($config);
echo $sanitizer->sanitize("<?div x?>"), "\n";
```

Results in:
```
<div></div>
```

### Possible Solution

Don't allow processing instructions, those aren't allowed by HTML5 anyway.

**Comment by smnandre** [comment]
If i'm reading this correctly, we could add some checks here, to discard some [DOMNode types](https://www.php.net/manual/fr/dom.constants.php): 
* DOMComment
* DOMProcessingInstruction

Any others ? 

```php
    private function visitChildren(\DOMNode $domNode, Cursor $cursor): void
    {
        foreach ($domNode->childNodes ?? [] as $child) {
            if ('#text' === $child->nodeName) {
                // Add text directly for performance
                $cursor->node->addChild(new TextNode($cursor->node, $child->nodeValue));
            } elseif (!$child instanceof \DOMText) {
                // Otherwise continue the visit recursively
                // Ignore comments for security reasons (interpreted differently by browsers)
                
                //  -- ？Add node type checks here ？--
                
                $this->visitNode($child, $cursor);
            }
        }
    }
```
[/src/Symfony/Component/HtmlSanitizer/Visitor/DomVisitor.php](https://github.com/symfony/symfony/blob/9549cc27635e24ae4c5f9db1ff69e50b6ee21573/src/Symfony/Component/HtmlSanitizer/Visitor/DomVisitor.php#L130)


Poke @tgalopin maybe ?

**Comment by ndossche** [comment]
As far as I can see, everything but processing instructions are already implicitly blocked because the other node types would start with a # symbol in their nodeName. PIs are the only cases where you can force a custom name (as shown in my OP example).

**Comment by smnandre** [comment]
Hey @nielsdos i tried to send a patch, could you check if that's OK for you ? :)

**Comment by tgalopin** [comment]
Interesting, thanks for the report, and thanks @smnandre for the PR, I'm having a look!

**Comment by smnandre** [comment]
Thank you @tgalopin !
