### ISSUE TITLE
symfony/console 5.4.* is not compatible with PHP 7.4 as declared

### ISSUE THREAD

**Issue by A-Shevchenko** [symfony/symfony#54498]
### Symfony version(s) affected

5.4.36

### Description

symfony/console is declared as compatible with PHP >= 7.2.5
https://github.com/symfony/console/blob/v5.4.36/composer.json#L19
However, it uses constructor property promotion:
https://github.com/symfony/console/blob/v5.4.36/Attribute/AsCommand.php#L20
which is available since PHP 8.0 only

### How to reproduce

just by looking into the code :)

**Comment by stof** [comment]
The only class using property promotion is an attribute class. PHP 7 won't read attributes as they are a PHP 8 feature. So there is no bug here.
