### ISSUE TITLE
Recieving "GET" instead of "POST"

### ISSUE THREAD

**Issue by treeindark** [symfony/symfony#54500]
### Symfony version(s) affected

7.0

### Description

Symfony receive GET instead of POST

upload with
 `curl -k -F file=@file.txt https://example.com`

LOG CURL
*   Trying 1.1.1.1:443...
* Connected to example.com (2.2.22.2) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /upload/datas/018e42c0-c05a-7441-84d0-68e6f983ee04 HTTP/1.1
> Host: example.com
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Length: 3561
> Content-Type: multipart/form-data; boundary=------------------------EQGwXcXS0VEzBfkay70vG6
>
* We are completely uploaded and fine
< HTTP/1.1 405 Method Not Allowed
< Date: Fri, 05 Apr 2024 09:58:41 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Allow: POST
< Cache-Control: no-cache, private
< Server: o2switch-PowerBoost-v3
<
<!DOCTYPE html>
<html lang="en">
<head>

ACCESS LOG SERVER :
2.22.2.2 - - [05/Apr/2024:11:25:07 +0200] "POST /upload/datas/018e42c0-c05a-7441-84d0-68e6f983ee04 HTTP/1.1" 405 1011 "-" "curl/8.4.0"

SYMFONY LOG:
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET https://example.com/download/datas/018e42c0-c05a-7441-84d0-68e6f983ee04": Method Not Allowed (Allow: POST)"

### How to reproduce

```
#[Route(path: '/upload/datas/{userUuid}', name: 'upload_data', methods: ['POST'])]
    public function upload(Request $request, $userUuid): \Symfony\Component\HttpFoundation\Response
    {
        $user = $this->userRepository->findOneBy(['uuid' => $userUuid]);
        if (!$user)
            return new Response('', 505);

        /** @var UploadedFile $uploadedFile */
        $journalFile = $request->files->get('journal');
....
```

### Additional Context

try with php  8.2 and 8.3

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by treeindark** [comment]
ModSecurity :-(

**Comment by stof** [comment]
Closing this then as it is not an issue in Symfony.
