### ISSUE TITLE
Ignore on \"Proxies\\__CG__\\App\\Entity\\XXX::__setInitialized()\" cannot be added.

### ISSUE THREAD

**Issue by Josee9988** [symfony/symfony#54514]
### Symfony version(s) affected

7.0.6

### Description

I upgraded from Symfony 6.4 to 7.0.6 and I got this error
Ignore on \"Proxies\\__CG__\\App\\Entity\\Categoria::__setInitialized()\" cannot be added. Ignore can only be added on methods beginning with \"get\", \"is\", \"has\" or \"set\".

### How to reproduce

I don't know. My Entity looks super normal. I can provide it if needed.

```php
#[ORM\Entity(repositoryClass: CategoriaRepository::class)]
class Categoria extends BaseEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['ids'])]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 32)]
    #[Groups(['evento', 'categoria'])]
    private $nombre;

    #[ORM\OneToMany(targetEntity: Evento::class, mappedBy: 'categoria')]
    private $eventos;

    #[ORM\Column(type: 'string', length: 255)]
    #[Groups(['categoria'])]
    private string $logotipo;
```

**Comment by derrabus** [comment]
Duplicate of #54477.
