### ISSUE TITLE
Validating database schema always produce an error

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#54511]
### Symfony version(s) affected

7.0

### Description

execute this command:
```bash
bin/console doctrine:schema:validate
```
will always produces an error
```txt
[OK] The mapping files are correct.

Database
--------
[ERROR] The database schema is not in sync with the current mapping file.
```

### How to reproduce

Please check https://github.com/pts-archive/db-validate-reproducer

**Comment by smnandre** [comment]
It seems to be a bug between DoctrineMigrationBundle and Doctrine : https://github.com/doctrine/migrations/issues/1406

Maybe one of the (temporary) solutions suggested in the thread will work for you !

**Comment by asispts** [comment]
Thanks. I'll close this issue.
