### ISSUE TITLE
[Workflow] Make `WorkflowInterface` extendable by depending on other interfaces

### ISSUE THREAD

**Issue by axel37** [symfony/symfony#54524]
### Description

The workflow component comes with 2 implementations : `Workflow` and `StateMachine`. It also provides a `WorkflowInterface`.

However, `WorkflowInterface` itself depends on some classes that *are not* interfaces, such as :
- `Marking`
- `Transition`
- `Definition`

It seems to me that providing interfaces for all pieces of a Workflow would allow for easier extensibility.

___

For instance, my use case would require having transitions and places be domain objects, which is currently not possible as they are expected to be `strings`. This use case may also require the introduction of an interface for places.

I'm not sure of how it would impact the behind-the-scenes working of this component, especially since I'm not using `yaml` files and instead create my workflow with code.

### Example

The new `WorkflowInterface` might have methods like this :

```php
public function can(object $subject, TransitionInterface $transition);
```

As opposed to :

```php
public function can(object $subject, string $transitionName);
```

___

An interface could be extracted from the `Definition` class, which may have methods like :

```php
/**
 * @return PlaceInterface[]
 */
public function getPlaces();
```

**Comment by stof** [comment]
I don't see how introducing interfaces for the value objects representing place and transitions would help making things more extendable. those are meant to be simple value objects with no behavior in them.

and introducing interfaces would actually make it much harder to add new methods in them if new features require them (it is much harder to introduce a new method in an interface than in a class, as this requires a BC break).

What is your use case for replacing those objects ?

**Comment by stof** [comment]
and the suggested change for the new WorkflowInterface would actually be a lot harder to use as it means code trying to execute a transition would need to have a reference to the object implementing TransitionInterface instead of only having to know the name of that transition (which then identifies it in the workflow definition). That's a totally different architecture for the component (and I don't see how a migration path could be provided btw)

**Comment by stof** [comment]
> For instance, my use case would require having transitions and places be domain objects, which is currently not possible as they are expected to be `strings`. This use case may also require the introduction of an interface for places.

Please actually describe your use case. Saying that it requires being able to replace those value objects does not give us a way to evaluate the use case (or to suggest a different solution for your use case that would be compatible with the existing architecture of the component)

**Comment by axel37** [comment]
My use case involved using objects as places / transitions which would themselves carry data that would influence the workflow, but after more thinking it seems the best way is to avoid the Workflow component altogether.

It seemed strange to me that an interface (extensible) would rely mostly on concrete objects (not so much extensible ?), so I wanted to make sure it wasn't an oversight ?
