### ISSUE TITLE
[Security] Symfony 6.x IsGranted attribute ignored at the controller class level

### ISSUE THREAD

**Issue by aless673** [symfony/symfony#54542]
### Symfony version(s) affected

6.x

### Description

The attribute `IsGranted` is ignored / not working when it is defined at the controller class level and when the controller service is lazy

Symfony doc about the feature at controller class level : https://symfony.com/doc/current/security.html#security-securing-controller-attributes

NB: at controller action level it works, this only happen when configured at the class level

### How to reproduce

In this example, the attribute IsGranted doesn't deny the access to any user

```php
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
class AdminController extends AbstractController
{
    public function adminDashboard(): Response
    {
        ...
    }
}
```

```yaml
    App\Controller\:
        resource: '../src/Controller/'
        lazy: true
```

**Comment by maximehardy** [comment]
https://github.com/symfony/symfony/issues/51361
This behavior is absolutely unexpected when migrating to SF6, a fix is badly needed!
I'm also impacted in many applications that already asked for a painstaking work of migration when moving from 5 to 6.
Thanks @aless673 for reporting it, otherwise I would not have noticed it!

**Comment by nicolas-grekas** [comment]
PR welcome :)

**Comment by smnandre** [comment]
@aless673  I'm not sure about your example / description of the problem, at least in LTS version.

Just created a reproducer with Symfony 6.4 and `IsGranted("ROLE_ADMIN")` works as expected.

-> https://github.com/smnandre/is-granted 

(`composer install` // `symfony serve`)

(i'm not negating there is a problem with expression / args, but simple ROLE_ cases seems to work)

| Homepage | Controller | Controller | Method |
| - | - | - | - |
| ![Capture d’écran 2024-04-10 à 17 16 51](https://github.com/symfony/symfony/assets/1359581/643d726e-62ea-4e41-a55a-0ab88a2cd546) | ![Capture d’écran 2024-04-10 à 17 16 57](https://github.com/symfony/symfony/assets/1359581/285451ec-6b94-4e1e-bdaf-3849787a1b96) | ![Capture d’écran 2024-04-10 à 17 17 03](https://github.com/symfony/symfony/assets/1359581/553bb58f-2eba-497f-9578-bf1c6e64581f) | ![Capture d’écran 2024-04-10 à 17 17 07](https://github.com/symfony/symfony/assets/1359581/5a314e82-f248-4505-a7b7-45fe410ab846) |

**Comment by maximehardy** [comment]
@smnandre thank you for taking the time to troubleshoot this issue!

Indeed your simplified reproduction of the case works as expected, it seems that the problem happens in more complex configurations. At the moment I can't find the minimal setup to reproduce the problem and of course I can't publish the whole codebase of the private company applications where the problem occurs.
I'll update this thread with more precise reproduction instructions asap.

Thanks again for your help!

**Comment by PhilETaylor** [comment]
I have a large application, and I was shocked to hear there may be an issue, so I went to test, and **I could not replicate the issue (Symfony 6.4.6) - phew.** We make use a lot of this type of restriction and it works well, in production, on a large code base. 

```php
#[IsGranted('ROLE_ADMIN')]
#[Route(path: '/admin/financials', methods: ['GET'])]
class FinancialsController extends AbstractController
{
```

**Comment by aless673** [comment]
I just found how to reproduce : marking controllers services as lazy

```
    App\Controller\:
        resource: '../src/Controller/'
        lazy: true
```

Without the lazy option, the IsGranted attribute will work as normal

@xabbuh can you confirm the issue

**Comment by maximehardy** [comment]
@aless673 that's it! same here
Most of our controllers are lazy as well.
Seems to be related to ProxyManager and the new Ghost objects.
@smnandre any clue about that?

**Comment by smnandre** [comment]
No clue about it no.. as I never considered making my controller lazy to be honest.

**Comment by derrabus** [comment]
This should be fixed, no question about that.

But I'm curious though: what is the reason for registering the controllers as lazy services?

**Comment by smnandre** [comment]
> Seems to be related to ProxyManager and the new Ghost objects.

Indeed.

| Lazy | Not lazy |
| - | - | 
| <img width="586" alt="lazy" src="https://github.com/symfony/symfony/assets/1359581/00be8e28-c70a-419f-b8ae-90ea5091aa92"> | <img width="698" alt="notlazy" src="https://github.com/symfony/symfony/assets/1359581/3a189119-57af-435e-9287-394323277c8a"> |

The attribute is not extracted in the [ControllerArgumentsEvent](https://github.com/symfony/http-kernel/blob/928b6b993debd8e3686d15f96a61cc7ee39e0140/HttpKernel.php#L172)

**Comment by nicolas-grekas** [comment]
To fix this, I'd ensure that services with the controller.service_arguments tag are setLazy(false).
No need for more imho. It makes no sense to make controllers lazy but it wouldn't be useful to throw an exception when they are. So let's just take over.

**Comment by MatTheCat** [comment]
> it wouldn't be useful to throw an exception when they are.

IMHO an exception would be more useful as it would teach it makes no sense. This would avoid reports about controllers not being lazy when they have been configured as such 🤔

**Comment by nicolas-grekas** [comment]
I'm waiting for such reports :) We already force public to true for them. Annoying people for that wouldn't be useful IMHO (and would be a needless BC break).
