### ISSUE TITLE
[PropertyInfo] PhpStanExtractor is not correctly resolving types declared in traits

### ISSUE THREAD

**Issue by alexandre-le-borgne** [symfony/symfony#54569]
### Symfony version(s) affected

7.0.6 (latest) and at least 6.4.3

### Description

When I denormalize an array to a class,
If this class has a property declared in a trait whose type described in phpDoc is a class in the same namespace as the trait but not in the same namespace as the class, then I get this error : 

![image](https://github.com/symfony/symfony/assets/10196942/786f18ba-14df-43c4-8303-a1b679c58144)

> PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "children" attribute for class "App\Example\Example" must be one of "App\Example\ExampleChild[]" ("array" given). in /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/vendor/symfony/serializer/Exception/NotNormalizableValueException.php:32
> Stack trace:
> #0 /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(589): Symfony\Component\Serializer\Exception\NotNormalizableValueException::createForUnexpectedDataType()
> #1 /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(358): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize()
> #2 /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/vendor/symfony/serializer/Serializer.php(238): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize()
> #3 /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/index.php(55): Symfony\Component\Serializer\Serializer->denormalize()
> #4 {main}
>   thrown in /home/aleborgne/Sites/bug-symfony-php-stan-extractor-traits/vendor/symfony/serializer/Exception/NotNormalizableValueException.php on line 32

### How to reproduce

Clone https://github.com/alexandre-le-borgne/bug-symfony-php-stan-extractor-traits
and run `php index.php`

Dependencies:

        "php": ">=8.3",
        "symfony/property-info": "^7.0",
        "phpdocumentor/reflection-docblock": "^5.3",
        "symfony/serializer": "^7.0",
        "symfony/property-access": "^7.0"

```
<?php

use App\Example\Example;
use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

require_once __DIR__ . '/vendor/autoload.php';

$phpDocExtractor = new PhpDocExtractor();
$phpStanExtractor = new PhpStanExtractor();
$reflectionExtractor = new ReflectionExtractor();

$listExtractors = [$reflectionExtractor];

$typeExtractors = [
    $phpStanExtractor, // Comment this line to avoid the bug
    $phpDocExtractor,
    $reflectionExtractor,
];

$descriptionExtractors = [$phpDocExtractor];
$accessExtractors = [$reflectionExtractor];
$propertyInitializableExtractors = [$reflectionExtractor];

$propertyInfo = new PropertyInfoExtractor(
    $listExtractors,
    $typeExtractors,
    $descriptionExtractors,
    $accessExtractors,
    $propertyInitializableExtractors
);

$properties = $propertyInfo->getTypes(Example::class, 'children');

// MUST returns ""App\Child\ExampleChild"" but it returns "App\Example\ExampleChild"
dump($properties[0]->getCollectionValueTypes()[0]->getClassName());

$normalizers = [
    new ArrayDenormalizer(),
    new ObjectNormalizer(propertyTypeExtractor: $propertyInfo),
];

$serializer = new Serializer($normalizers);

$result = $serializer->denormalize([
    'children' => [
        'testProperty' => '123',
    ],
], Example::class);

dump($result);
```

![image](https://github.com/symfony/symfony/assets/10196942/94395111-2f62-4fc6-a5c1-1deaa58f4c94)

### Possible Solution

Disable phpStanExtractor
Fix phpStanExtractor

### Additional Context

It works when using only PhpDocExtractor

I think this bug was fixed in the PhpDocExtractor and then reintroduced when phpDocExtractor was replaced by PhpStanExtractor

The fix of PhpDocExtractor: https://github.com/symfony/symfony/pull/40175

The replacement of PhpDocExtractor by PhpStanExtractor: https://github.com/symfony/symfony/pull/40457

**Comment by alexandre-le-borgne** [comment]
Workarround : 

```
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        $container->addCompilerPass(new ServicesOverridePass());
    }
}

class ServicesOverridePass implements CompilerPassInterface
{
    #[\Override]
    public function process(ContainerBuilder $container): void
    {
   
        $definition = $container->getDefinition('property_info');
        /** @var IteratorArgument $argument */
        $argument = $definition->getArgument(1);
        $argument->setValues(array_filter($argument->getValues(), function (Reference $reference) {
            return $reference->__toString() !== 'property_info.phpstan_extractor';
        }));
    }
}
```

**Comment by mtarld** [comment]
Thanks for that great issue description @alexandre-le-borgne, I just submitted a fix.
