### ISSUE TITLE
[DependencyInjection] Attribute #[Target()] does not work

### ISSUE THREAD

**Issue by lkolndeep** [symfony/symfony#54578]
### Symfony version(s) affected

6.4.6

### Description

Hello,

When I tested the `#[Target]` attribute feature that you can see in the docs here: [Target attribute docs](https://symfony.com/doc/current/service_container/autowiring.html#dealing-with-multiple-implementations-of-the-same-type), it does not work.

Thanks in advance,

### How to reproduce

I created a project which contains:
- two services which implements an interface
- one global service which takes the interface as a parameter to test the `Target` attribute feature
- a controller with a route which takes a string as a parameter

Here the link of the project: [bug_app](https://github.com/lkolndeep/bug_app) You will find some comments explaining the bug in the NotificationSender service.

**Comment by smnandre** [comment]
I think your service may not be defined as an alias but as a service.. Maybe try using "alias" instead of "class" in your services.yaml ? 

https://symfony.com/doc/current/service_container/alias_private.html#aliasing

**Comment by lkolndeep** [comment]
Hello @smnandre ,

I changed a little the service.yaml file as you advised and I also uncomment this line `App\Interface\MessageInterface $notification: '@app.message.message_second'` to test the second service without the Target feature.

```yaml
app.message.message_first: '@App\Service\MessageFirst'
app.message.message_second: '@App\Service\MessageSecond'

# Default used service
App\Interface\MessageInterface: '@app.message.message_first'

# Called service if we use the $notification variable (put here to compare with the Target attribute feature)
App\Interface\MessageInterface $notification: '@app.message.message_second'

App\Service\NotificationSender:
    autowire: true
```

In the NotificationSender class, I changed the variable for the parameter type `MessageInterface` to `$notification` to test if the second service is taking into account.

Without the Target attribute feature in the NotificationSender, everything works well. The two services are taking into account depending on commenting/uncommenting this line `App\Interface\MessageInterface $notification: '@app.message.message_second'` in the service.yaml.

So, our change in the services.yaml is OK. Now, I test the Target attribute feature:

**First case:**

Now, I suppose I comment this line in the yaml file: `# App\Interface\MessageInterface $notification: '@app.message.message_second'`

When I add the Target attribute in the NoficationSender class with the first service, it still doesn't work:

```php
class NotificationSender
{
    public function __construct(
        #[Target('app.message.message_first')]
        private MessageInterface $notification
    ){
    }

    public function send(string $word): string
    {
        $sentence = $this->notification->show($word);

        return $sentence;
    }
}
```

I have this error:

```text
Cannot resolve argument $notificationSender of "App\Controller\WelcomeController::showMessage()": Cannot autowire service "App\Service\NotificationSender": argument "$notification" of method "__construct()" has "#[Target('app.message.message_first')]" but no such target exists. You should maybe alias this interface to one of these existing services: "App\Service\MessageFirst", "App\Service\MessageSecond".
```

When I try the second service with: `#[Target('app.message.message_second')]`, it does not work too:

```text
Cannot resolve argument $notificationSender of "App\Controller\WelcomeController::showMessage()": Cannot autowire service "App\Service\NotificationSender": argument "$notification" of method "__construct()" has "#[Target('app.message.message_second')]" but no such target exists. You should maybe alias this interface to one of these existing services: "App\Service\MessageFirst", "App\Service\MessageSecond".
```

**Second case:**

I uncomment this line in the yaml file: `App\Interface\MessageInterface $notification: '@app.message.message_second'` and I test the first service with: `#[Target('app.message.message_first')]`. I does not work:

```text
Cannot resolve argument $notificationSender of "App\Controller\WelcomeController::showMessage()": Cannot autowire service "App\Service\NotificationSender": argument "$notification" of method "__construct()" has "#[Target('app.message.message_first')]" but no such target exists. Did you mean to target "notification" instead?
```

I tested the second service with `#[Target('app.message.message_second')]` and it does not work too:

```text
Cannot resolve argument $notificationSender of "App\Controller\WelcomeController::showMessage()": Cannot autowire service "App\Service\NotificationSender": argument "$notification" of method "__construct()" has "#[Target('app.message.message_second')]" but no such target exists. Did you mean to target "notification" instead?
```

Regards,

**Comment by smnandre** [comment]
Try with   `#[Autowire(service: 'app.message.message_second')]`  instead of Target(...)

**Comment by lkolndeep** [comment]
I tested `#[Autowire(service: 'app.message.message_second')]` and even `#[Autowire(service: 'app.message.message_first')]`. Both work well.

**Comment by HypeMC** [comment]
The `#[Target]` attribute doesn't work with service IDs or aliases, it expects the name of the parameter of the named alias. See https://symfony.com/blog/new-in-symfony-4-2-autowiring-by-type-and-name.

In your case, that would look something like this:

```yaml
services:
    App\Interface\MessageInterface $firstMessage: '@App\Service\MessageFirst'
    App\Interface\MessageInterface $secondMessage: '@App\Service\MessageSecond'
```

```php
public function __construct(
    #[Target('secondMessage')]
    private MessageInterface $message
) {
}
```

**Comment by lkolndeep** [comment]
@HypeMC Thank you very much. Now, it works!
