### ISSUE TITLE
Missing ? in symfony console make:entity

### ISSUE THREAD

**Issue by raffcioo** [symfony/symfony#54594]
### Description

I am using `symfony console make:entity`. Lets assume one field is **company** string, not nullable.

It generates:
```php
public function setCompany(string $company): static
{
    $this->company = $company;

    return $this;
}
```

Shouldn't it generate?:
```php
public function setCompany(?string $company): static
{
    $this->company = $company;

    return $this;
}
```

When user submits form with empty **company** I am getting:
*HTTP 500. InvalidArgumentException. Expected argument of type "string", "null" given at property path "company".*

I have validator on this field, in form, so it checks for NotBlank, but it just does not have oportunity to do its job.

If I forget about this validator I am getting:
*HTTP 500. An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'company' cannot be null*
so it is ok.

I just have to add this `?` every time everywhere when I am using this command above. Or I am doing as usual something wrong and against the design? :)

**Comment by derrabus** [comment]
Please open an issue at https://github.com/symfony/maker-bundle
