### ISSUE TITLE
[PropertyAccess] Regression when reading the __GET Magic method

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony#54605]
### Symfony version(s) affected

6.4.6

### Description

This example code does not work with 6.4.6 (NoSuchPropertyException thrown), with 6.4.4 it reads without problems.
PHP 8.3.0

### How to reproduce

```php
class demo
{
    privat $properties = [];
    public function __get(string $name): mixed
    {
        return $this->properties[$name] ?? null;
    }
}

$obj = new demo();

$propertyAccessor = new \Symfony\Component\PropertyAccess\PropertyAccessor(
    \Symfony\Component\PropertyAccess\PropertyAccessor::MAGIC_CALL | \Symfony\Component\PropertyAccess\PropertyAccessor::MAGIC_SET | \Symfony\Component\PropertyAccess\PropertyAccessor::MAGIC_GET
);

$propertyAccessor->getValue($obj, 'Wouter');
```

### Possible Solution

PropertyAccessorTest covers the __get magic method, it is unknown what is causing the error (or why the test passes). The workaround is to downgrade.

### Additional Context

In version 6.4.4, the part that causes the problem looks like this:
```php
                    if ($access->canBeReference() && !isset($object->$name) && !\array_key_exists($name, (array) $object) && !(new \ReflectionProperty($class, $name))->hasType()) {
                        throw new UninitializedPropertyException(sprintf('The property "%s::$%s" is not initialized.', $class, $name));
                    }
```

`$access->canBeReference()` is false, so the rest of the condition test does not run.

In version 6.4.6, the `canBeReference` call has been transferred so the [property reading](https://github.com/symfony/symfony/blob/05a8fcc9a9932a2dc36c846c844b4b96b210b4ca/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L416) cause exception.

**Comment by nicolas-grekas** [comment]
Thanks for the report.
The issue is that you didn't implement the `__isset` magic method, or if you did your implementation is broken.
Please fix that a this should go away.
You were relying on a side effect of PropertyAccess, which is broken in the generic case of how the php engine behaves with magic methods. E.g. the `??` operator was likely broken with your objects.

**Comment by connorhu** [comment]
I figured it out. The test is running because it is being tested on existing property. But my example code wants to read a property that doesn't physically exist. Which is possible, if the properties (or part of them) are dynamic or I store them in an array. Example updated.

**Comment by connorhu** [comment]
> Thanks for the report. The issue is that you didn't implement the `__isset` magic method, or if you did your implementation is broken. Please fix that a this should go away. You were relying on a side effect of PropertyAccess, which is broken in the generic case of how the php engine behaves with magic methods. E.g. the `??` operator was likely broken with your objects.

@nicolas-grekas Missing `__isset` was the issue here. Thank you!

**Comment by bglover-zz** [comment]
@nicolas-grekas - I realize this was closed, however there does seem to be a regression in 6.4.6. Take this test for example
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\PropertyAccess\PropertyAccess;
$propertyAccessor = PropertyAccess::createPropertyAccessor();

class A
{
    private array $children = [
        'MyKey' => null,
    ];

    public function __get($id): mixed
    {
        return $this->children[$id];
    }

    public function __isset($id): bool
    {
        return isset($this->children[$id]);
    }
}
$a = new A();
var_dump($propertyAccessor->getValue($a, 'MyKey'));
```

Under 6.4.4 the result is `NULL`, but under 6.4.6+ there's a fatal error:
```
PHP Fatal error:  Uncaught Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "MyKey" in class "A".
```

**Comment by xabbuh** [comment]
Your `__isset()` method will return `false`. Thus, `__get()` is never called. You probably want to use `array_key_exists()`.

**Comment by bglover-zz** [comment]
@xabbuh - So having `PropertyAccess` determine whether a property exists based on the return of `__isset` is the intended behavior?

If so, this is quite a big break for a patch-level change that had been functioning that way since (at least) v5.4.0

**Comment by xabbuh** [comment]
> So having PropertyAccess determine whether a property exists based on the return of `__isset` is the intended behavior?

yes

> If so, this is quite a big break for a patch-level change that had been functioning that way since (at least) v5.4.0

Unfortunately there's not much we can do about it but that's how things work if one (unintentionally) depends on a bug.

**Comment by nicolas-grekas** [comment]
The issue is that PropertyAccess is not the only way to access properties: PHP direct access is another perfectly valid one (and the most common we could say). Both should behave the same, and the correct behavior is defined by how the PHP engines behaves. Not PropertyAccess.

**Comment by bglover-zz** [comment]
Thanks for the explanation; we'll make changes accordingly to account for unintentionally relying on that bug.
