### ISSUE TITLE
[AssetMapper] Warning thrown when dependency version is within valid range

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#54610]
### Symfony version(s) affected

6.4

### Description

when installing a package, I'm getting

     [warning] datatables.net-scroller-bs5 requires datatables.net-bs5@1.11 - 2 but version 2.0.3 is installed.

but 1.11 - 2 includes 2.0.3

![image](https://github.com/symfony/symfony/assets/619585/598ff018-b3f3-46bf-9d8b-239fe211a08c)

Checking with [the npm SemVer Calculator](https://semver.npmjs.com/) appears to confirm this:

### How to reproduce

```bash
bin/console importmap:require datatables.net-scroller-bs5
bin/console importmap:update
```

```
[warning] datatables.net-scroller-bs5 requires datatables.net-bs5@1.11 - 2 but version 2.0.3 is installed.
[warning] datatables.net-scroller-bs5 requires datatables.net-bs5@1.11 - 2 but version 2.0.3 is installed.

 [OK] Updated all packages in importmap.php.                                                                            
```
                                                                                                                        

### Possible Solution

Perhaps the way the semver string is being parsed isn't including the minor / patch releases.  I had a different but similar issue with phar-io/version 

https://github.com/phar-io/version/issues/34

**Comment by Jean-Beru** [comment]
The [AssetMapper version checker](https://github.com/symfony/symfony/blob/ae0a783425b80b78376488619bf9106e69193fa4/src/Symfony/Component/AssetMapper/ImportMap/ImportMapVersionChecker.php#L120) converts `1.11 - 2` to `>=1.11 <=2` which is still valid.

![image](https://github.com/symfony/symfony/assets/6114779/826a206b-58b5-4c2c-bd3c-a886b9209954)

But `Semver::statisfies` from https://github.com/composer/semver returns `false` when comparing this range to `2.3.0`.

IMO, we can open an issue in this repository.

**Comment by tacman** [comment]
It looks like the tests don't cover a version range without a minor version.

https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/Tests/ImportMap/ImportMapVersionCheckerTest.php#L308-L311

```php
// Hyphen Ranges
        yield 'hyphen range simple' => [
            '1.0.0 - 2.0.0',
            '>=1.0.0 <=2.0.0',
        ];

        yield 'hyphen range with v prefix' => [
            'v1.0.0 - 2.0.0',
            '>=1.0.0 <=2.0.0',
        ];

        yield 'hyphen range without patch' => [
            '1.0 - 2.0',
            '>=1.0 <=2.0',
        ];

        yield 'hyphen range with no spaces' => [
            '1.0-v2.0',
            '>=1.0 <=2.0',
        ];
```

**Comment by stof** [comment]
`<=2`  does not have the same meaning in Composer and in npm. In Composer, `2`, `2.0` and `2.0.0` are the same version, even when using in constraint bounds.

**Comment by Jean-Beru** [comment]
An other solution may be to keep the `1.11 - 2` syntax, instead of converting it, since Composer supports it.
