### ISSUE TITLE
[String][EnglishInflector] Pluralize on words ending with -on mostly wrong

### ISSUE THREAD

**Issue by DesLynx** [symfony/symfony#54611]
### Symfony version(s) affected

5.4 +

### Description

When using the EnglishInflector of the String component to pluralize words ending with -on the results are mainly wrong because of the follwing rule in the SINGULAR_MAP:
```php
        // bacteria (bacterium), criteria (criterion), phenomena (phenomenon)
        ['no', 2, true, true, 'a'],
```

This -on rule is not valid in most of the cases. The rule works for foreign (mainly greek) words. This is an irregular case not a standard.

We can already see 3 other rules for words ending in -pon, -son and -con. 

### How to reproduce

```php
// First, run "composer require symfony/string"
// Then, execute this file:
<?php
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\String\Inflector\EnglishInflector;

// returns "butta" instead of "buttons"
echo (new EnglishInflector())->pluralize('button');
```

### Possible Solution

I'm not an english native-speaker nor an expert of english grammar but I think that it would be better to have a rule dedicated to the foreign word ending in -on, phenomenon and criterion (and maybe others) + a generic rule for words ending in -on.

**Comment by derrabus** [comment]
The inflector will never be perfect or complete. We fix such issues whenever someone comes up with a wrong pluralization. Please submit a PR that adds the words that you've found wrongly pluralized to our tests and that fixes the issue.
