### ISSUE TITLE
MapQueryString/MapRequestPayload skips validation when empty request is sent.

### ISSUE THREAD

**Issue by unixslayer** [symfony/symfony#54617]
### Symfony version(s) affected

6.4.6

### Description

It seems to be impossible to validate request properly when sent empty. For both query string and request payload mapper will return `null` and skip validation. Using default value makes callable being called with object which may be invalid.

### How to reproduce

```php
final class ApiDTO
{
    #[Assert\NotBlank]
    public string $foo = '';
}
```

```php
class FooController extends AbstractController
{
    #[Route("/foo", methods: ["GET"])]
    public function __invoke(#[MapQueryString(validationFailedStatusCode: 400)] ApiDTO $dto = new ApiDTO()): JsonResponse {
        dd($dto);
    }
}
```

```
expected behavior
GET /foo?foo= -> 400

validation skipped
GET /foo -> ApiDTO {
    +foo: ""
}
```

### Possible Solution

Possible solution would be to make mapper method return default value if defined instead of returning `null`

```php
// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:162
private function mapQueryString(Request $request, string $type, MapQueryString $attribute): ?object
{
    if (!$data = $request->query->all()) {
        return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
    }

    return $this->serializer->denormalize($data, $type, null, $attribute->serializationContext + self::CONTEXT_DENORMALIZE);
}

// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:185
if ('' === $data = $request->getContent()) {
    return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
}
```

```
GET /foo?foo= -> 400
GET /foo -> 400
```

**Comment by derrabus** [comment]
I'm not 100% convinced this is a bug, tbh. The validation is meant to be run on a paylod fetched from the request. Basically, you run the validation on user input.

But in your case, you specified a default value of which you already know that it won't pass the validation. That default is created programmatically. Why would I want to specify a default at all in that case?

On top of that, I could imagine that apps might rely on the current behavior, so enabling the validation for everyone might break code downstream.

**Comment by sztanpet** [comment]
The problem is getting a 404 when there is no input, instead of getting a validation error about missing mandatory parameters as specified in the validation annotations.

No input does not mean "everything must be fine, no need for validation"

On no input, any validation on the default value should still be run

**Comment by xabbuh** [comment]
Don’t you just have to remove the default value for the DTO to achieve this?

**Comment by derrabus** [comment]
> The problem is getting a 404 when there is no input

If the status code is not configurable, we should make it configurable, I suppose.

> No input does not mean "everything must be fine, no need for validation"

That's not what I said and I think you know that.

**Comment by sztanpet** [comment]
> Don’t you just have to remove the default value for the DTO to achieve this?

no sadly, if there is no input, there is no validation run at all

> If the status code is not configurable, we should make it configurable, I suppose.

it is configurable

> That's not what I said and I think you know that.

Sorry, did not mean to suggest that is what you said, it's me saying that is what happens currently, you get the default value as specified but with no validation errors

**Comment by unixslayer** [comment]
> Don’t you just have to remove the default value for the DTO to achieve this?

@xabbuh Removing default value for DTO results in expected status code however, there is no feedback for client what went wrong.

> The validation is meant to be run on a paylod fetched from the request. Basically, you run the validation on user input.

@derrabus empty input is still an input therefore validation may be required to run. 

> apps might rely on the current behavior, so enabling the validation for everyone might break code downstream

From Symfony 6.4 upwards, sending empty input to following code

```php
final class ApiDTO
{
    public string $foo = '';
}

class FooController extends AbstractController
{
    #[Route("/foo", methods: ["GET"])]
    public function __invoke(#[MapQueryString(validationFailedStatusCode: 400)] ApiDTO $dto): JsonResponse {
        dd($dto);
    }
}
```
client gets `400` without feedback about what went wrong. The same happens when empty input is sent and DTO has assertions.

Setting default value for controller parameter makes `$dto` to be a new instance of `ApiDTO`. Without any assertions this is expected behavior. The only thing that may change is when DTO has assertions. However, with default instance of DTO being invalid which can be declared with 

```php
final class ApiDTO
{
    #[Assert\NotBlank]
    public string $foo = '';
}
```

controller gets called with invalid parameter due no validation was executed. This require to run validation directly in controller which, in case of sending proper input, ends up executing the same validation on the same object twice which makes this feature redundant.

I can imagine people decide to use common `Form` instead of mapping for that case because it is simply not supported.

**Comment by asispts** [comment]
> 
> > The validation is meant to be run on a paylod fetched from the request. Basically, you run the validation on user input.
> 
> @derrabus empty input is still an input therefore validation may be required to run.
> 

I'm with @derrabus here. Since, you have an empty input, it should be assigned the default value. There's no point in validating the default value.

Notice the similarities between these code?
```php
#[Route("/foo", methods: ["GET"])]
public function __invoke(#[MapQueryString(validationFailedStatusCode: 400)] ApiDTO $dto = new ApiDTO()): JsonResponse {
    dd($dto);
}
```
```php
#[Route("/foo", methods: ["GET"])]
public function __invoke(#[MapQueryParameter] int $page = 1): JsonResponse
}
```

**Comment by derrabus** [comment]
> @derrabus empty input is still an input therefore validation may be required to run.

Empty input is still input, but your default value isn't. It's a value that you have created programmatically and which is not even remotely derived from the client's input.

Even worse, since you consider your default value to be invalid, you've created a method with an optional parameter and at the same time you expect that this parameter is never omitted when calling your method. That does not make much sense to me.

I understand that a request with an empty request body or query string is invalid in the context of your application and that you're looking either for a smart way to express that or a cheap way to produce human-readable error messages, but validating the default value is a dead-end from my PoV.

**Comment by yceruto** [comment]
I agree that the default value is already considered valid and changing it would be a breaking change for current projects. However, I also agree that this request is about improving the error message, which is missing in this scenario:
```php
default => throw HttpException::fromStatusCode($validationFailedCode),
```
Then, you're responsible for changing this behavior by setting `null` as the default value and throwing the exception in the controller with a custom message.

In that regard, I wonder if adding a new `validationFailedMessage` option for this case might be a better solution to fix this issue.

**Comment by yceruto** [comment]
By the way, this request reminds me of the [`empty_data` option from the `Form` component](https://symfony.com/doc/current/form/use_empty_data.html), which is used when no input is set. Whether it is valid or not, it passes through the validation process afterward. So, we could also consider adding a new option for it:
```php
public function __invoke(#[MapQueryString(emptyData: new ApiDto())] ApiDto $dto)
```

**Comment by yceruto** [comment]
I suggest the second solution as it enables all validator capabilities to provide a better error message.

**Comment by unixslayer** [comment]
If we look at it a a similarity to `Form` component, default value validation is a fact possible with `data_class` option which is default instance of DTO mapped from request payload and used for validation. With empty request, simply new instance is used.

By default, it may be invalid due it may contain assertions like `#[Assert\NotBlank]`.

I don't see much difference between

```php
public function __invoke(#[MapQueryString(emptyData: new ApiDto())] ApiDto $dto)
```
and
```php
public function __invoke(#[MapQueryString] ApiDto $dto = new ApiDto())
```
as long both have the same purpose but I understand that first one is more proper without indicatiion of invalid parameter being passed into a method.

Right now, `MapQueryString` and `MapRequestPayload` uses second version properly. The only problem which I see is that they're not preventing sending empty request where it may be forbidden due no validation is executed.

@derrabus my goal comes from my understanding of mapping as a substitute for request handling which normally would require a lot of boilerplate code that comes with `Form` component.

If there is a green light for `emptyData` parameter for `MapQueryString` and `MapRequestPayload` I'll be more than happy to contribute.

**Comment by yceruto** [comment]
>If we look at it a a similarity to Form component, default value validation is a fact possible with data_class option which is default instance of DTO mapped from request payload and used for validation. With empty request, simply new instance is used.

It's a good point. We don't need a default value to achieve the same result here. We can instantiate the object from the `$argument->getType()`. Well wait, that's what the serializer is currently doing with `$this->serializer->denormalize($data, $argument->getType())`.

Therefore, let the empty array `$data` continue if there is no default value set:
```php
private function mapQueryString(Request $request, ArgumentMetadata $argument, MapQueryString $attribute): ?object
{
    if (!($data = $request->query->all()) && $argument->hasDefaultValue()) { // <-- line changed
        return null;
    }

    return $this->serializer->denormalize($data, $argument->getType(), null, $attribute->serializationContext + self::CONTEXT_DENORMALIZE + ['filter_bool' => true]);
}
```
That's it! Denormalizing with `data = []` will initialize the object anyway, and the validation will provide a clear error message. There is no BC break, as we are currently getting an error under the same scenario but without a message.

**Comment by unixslayer** [comment]
@yceruto I rest my case :) 

@derrabus PR was changed according to @yceruto suggestion. Please let me know if you are ok with that and fix can be released.

**Comment by derrabus** [comment]
I'm fine with allowing to deserialize an empty request. However, this is a change of behavior and might break apps that rely on the current behavior. If the new behavior was opt-in, we could merge it as a feature for 7.2.

**Comment by unixslayer** [comment]
@derrabus there is no actual behavior change that seems to have any negative impact. The only thing that was added was proper error message in case where empty request/query is sent and validation should be performed.
