### ISSUE TITLE
[Serializer] Typo in name of AbstractNormalizerContextBuilder::withDefaultContructorArguments() method

### ISSUE THREAD

**Issue by mttsch** [symfony/symfony#54616]
### Symfony version(s) affected

6.4

### Description

In the name of `\Symfony\Component\Serializer\Context\Normalizer\AbstractNormalizerContextBuilder::withDefaultContructorArguments()`, `Contructor` (no `s`) is used instead of `Constructor`.

(Same issue for the parameter name)

### How to reproduce

Read method signature of

https://github.com/symfony/symfony/blob/05a8fcc9a9932a2dc36c846c844b4b96b210b4ca/src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php#L115

**Comment by mtarld** [comment]
I'm not sure if there is any issue here.
Indeed, the method name reflects the constant name, which is `DEFAULT_CONSTRUCTOR_ARGUMENTS`.

**Comment by nicolas-grekas** [comment]
I don't see any typo either...

**Comment by xabbuh** [comment]
The s in conStructor is missing. 😀

**Comment by mttsch** [comment]
@xabbuh Thank you :) Not sure how I could have been more explicit than writing 😅

> `Contructor` (no `s`) is used instead of `Constructor`.

**Comment by mtarld** [comment]
Indeed, nice catch 😅
