### ISSUE TITLE
[DI] Allow reseting of env vars loaded by EnvVarLoaderInterface implementations

### ISSUE THREAD

**Issue by faizanakram99** [symfony/symfony#54627]
### Description

Services tagged with [`container.env_var_loader`](https://github.com/symfony/symfony/blob/3fbfc9ca32b2393f9e3be19da0b271d88197afad/src/Symfony/Component/DependencyInjection/EnvVarLoaderInterface.php#L14-L19) are loaded by [EnvVarProcessor](https://github.com/symfony/symfony/blob/3fbfc9ca32b2393f9e3be19da0b271d88197afad/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php) to load env vars dynamically. Right now there is no way to reset such env vars once they're loaded mainly because [they're cached in memory once loaded](https://github.com/symfony/symfony/blob/3fbfc9ca32b2393f9e3be19da0b271d88197afad/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php#L191-L194) . This seems by design to improve performance, however, it limits the usage of EnvVarLoader in messenger context say with a multi-tenant app where a single worker can handle messages from various tenants.

This slack thread might give a bit more context https://symfony-devs.slack.com/archives/C8WHX21K7/p1713264333709759

**Possible solution:**
`EnvVarProcessor` can possibly implement reset interface and allow reseting some env vars (maybe via a config option?), especially the ones which are loaded by `EnvVarLoaderInterface` implementations, since the env vars loaded by EnvVarLoaderInterface aren't actual env vars and are dynamic (or runtime) by definition to begin with, it makes sense to allow resetting them.

This would allow using symfony messenger easily in a multi-tenant app where env vars are loaded based on tenant id.

**Comment by nicolas-grekas** [comment]
Looks like a good idea to me. Up for a PR?

**Comment by faizanakram99** [comment]
Yes, I can try. Thanks.

**Comment by tucksaun** [comment]
Would that work in the end?
It seems to me the env vars are cached higher in the stack (in the container) to cache across different processors (see https://github.com/symfony/symfony/blob/5ae5791af5b12657b03ad51147ba69d299a9e10f/src/Symfony/Component/DependencyInjection/Container.php#L339-L372)

**Comment by faizanakram99** [comment]
> Would that work in the end?
> It seems to me the env vars are cached higher in the stack (in the container) to cache across different processors (see https://github.com/symfony/symfony/blob/5ae5791af5b12657b03ad51147ba69d299a9e10f/src/Symfony/Component/DependencyInjection/Container.php#L339-L372)

Indeed, those would need to be reset as well, thanks I had missed that.
