### ISSUE TITLE
[YAML] Merge multiple arrays produces strange results

### ISSUE THREAD

**Issue by annuh** [symfony/symfony#54642]
### Symfony version(s) affected

6.4.6

### Description

Hi!

Merging multiple arrays in YAML configs produces strange results.

However, I'm not sure if this is a bug or a feature request, because later I found [that this isn't valid YAML](https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays/30683699#30683699). It would be nice if the container would complain about the invalid config.

### How to reproduce

```php
$yaml = Yaml::parse(<<<YAML
a: &lista
  - a1
b: &listb
  - b1
  - b2
combined:
    <<: *lista
    <<: *listb
YAML);

dump($yaml['combined']);
/*
array:2 [
  0 => "a1"
  1 => "b2"
]
*/
```

However, I expected that all array values were merged: 
```
array:2 [
  0 => "a1"
  1 => "b1"
  2 => "b2"
]
```

It looks like elements of the merged array try to override existing elements. Here are some other examples:
```php
$yaml = Yaml::parse(<<<YAML
a: &lista
  - a1
  - a2
b: &listb
  - b1
  - b2
combined:
    <<: *lista
    <<: *listb
YAML);

dump($yaml['combined']);
/*
array:2 [
  0 => "a1"
  1 => "a2"
]
*/
```

and

```php
$yaml = Yaml::parse(<<<YAML
a: &lista
  - a1
  - a2
b: &listb
  - b1
  - b2
  - b3
combined:
    <<: *lista
    <<: *listb
YAML);

dump($yaml['combined']);
/*
array:2 [
  0 => "a1"
  1 => "a2"
  2 => "b3"
]
*/
```

**Comment by stof** [comment]
This is because Yaml only supports merging maps, not sequences. Because `[0 => 'a1']` in PHP can be considered both as a map using a numeric key or as a list (because PHP does not have different types for those 2 things, using `array` in both cases), the Yaml component cannot throw an exception on this code. this is because it would look the same when using this valid Yaml source code using maps:

```yaml
a: &mapa
  0: a1
b: &mapb
  0: b1
  1: b2
combined:
    <<: *mapa
    <<: *mapb
```

**Comment by annuh** [comment]
Ah, that makes sense indeed.

Thanks for your reply, I will close this issue 🙂
