### ISSUE TITLE
Routing Component: extensible options?

### ISSUE THREAD

**Issue by ash-m** [symfony/symfony#54677]
### Description

I have a need for some routes to be strictly sub requests.

I could use auth, but I don't really want this portrayed as a public route (with access denied). I know I could alter the message with a listener, but it feel like it's the wrong tool.

I can't use expression language, because `KernelEvent::isMainRequest()` is not available in routing conditions.

I can use a listener, but there needs to be some disambiguation from public routes. Right now I solve this by specifying a route name prefix and the listener logic becomes:
```php
if ($event->isMainRequest() && str_starts_with($routeName, 'private_')) {
    throw new NotFoundHttpException();
}
```
But I'd rather not use route names this way. It got me thinking that maybe it'd be possible to extend the routing component to allow arbitrary data to be assigned to the route, perhaps as additional underscore-prefixed attribute so  
```yaml
some_route_name:
    path: /path/to/some/name
    attributes:
        # any misc data
        private: true
```
would  perform `$request->attribute->set('_private', true);` on any matching route. It seems like a flexible and reasonable enough feature to be useful in other contexts.

**Comment by stof** [comment]
Assigning things in attributes is already possible by using `defaults` (if the parameter does not exist in the path, the default value will always be used to assign the attribute)

**Comment by ash-m** [comment]
> Assigning things in attributes is already possible by using `defaults` (if the parameter does not exist in the path, the default value will always be used to assign the attribute)

Awesome, I thought that might be possible, but I didn't know if it was considered hacky.

**Comment by faizanakram99** [comment]
> > Assigning things in attributes is already possible by using `defaults` (if the parameter does not exist in the path, the default value will always be used to assign the attribute)
> 
> Awesome, I thought that might be possible, but I didn't know if it was considered hacky.

No it's not hacky, it's a documented feature, the name is misleading though. It's not just route parameter defaults, it's that + extra attributes.

**Comment by xabbuh** [comment]
Let's close here then. :)
