### ISSUE TITLE
When using twig `form_label` function to display custom label, the Symfony profiler report it as "missing" tanslation

### ISSUE THREAD

**Issue by talha-core** [symfony/symfony#54680]
### Symfony version(s) affected

7.06

### Description

I am using this official [guide](https://symfony.com/doc/current/form/form_customization.html#form-label-form-view-label-variables)

The symfony profiler say missing translation when I use form_lable function to show custom label instead.

### How to reproduce

 `{{ form_label(form.title, 'admin.cms.highlights.form_title'|trans, {'label_attr': {'class': 'form-label'}}) }`

**Comment by n0rbyt3** [comment]
Your code will translate the label twice. The ```trans``` filter is not used in the official guide.

This should work:
```twig
{{ form_label(form.title, 'admin.cms.highlights.form_title', {'label_attr': {'class': 'form-label'}}) }
```

**Comment by talha-core** [comment]
Thanks, @n0rbyt3, it works.

I think the documentation should be updated.
