### ISSUE TITLE
If PUT method in twig, form isn't submitted

### ISSUE THREAD

**Issue by unsiteavous** [symfony/symfony#54731]
### Symfony version(s) affected

7.0.6

### Description

If I attempt to change form method in twig, even if the route listens to the good method, it's like the form doesn't handle the request. 
With the same code, if I attempt to change the form method in the controller, it works. But not in the views, even though there is the field in the final HTML, in each case.

### How to reproduce

 This bug is easy to reproduce. 
create a project with symfony 7.0.6, make an entity Categorie, and the associated CRUD. 
In `config/packages/frameword.yaml`, add this line : 
```yaml
framework:
    # [...]
    http_method_override: true
``` 

In the CategorieController :
```php
#[Route('/{id}/edit', name:'edit', methods:['GET', 'PUT'])]
  public function edit(Categorie $categorie, Request $request, EntityManagerInterface $em) : Response 
  {
    
    $form = $this->createForm(CategorieType::class, $categorie);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $em->flush($categorie);

      $this->addFlash('success', 'Modification effectuée !');
      return $this->redirectToRoute('app_categorie_show', ['id'=> $categorie->getId()]);
    }

    return $this->render('categorie/form.html.twig', [
      'form' => $form,
      'categorie' => $categorie
    ]);
  }
```

and in the twig view : 
```twig
    {{ form(form, {method: 'PUT'}) }}
```
or 
```twig
    {{ form_start(form, {method: 'PUT'}) }}
         <input type="hidden" name="_method" value="PUT">
    {{ form_end(form) }}
```

Normally, after a successfull submission, we are redirected to another route. But in this case, this is not the case, we never satisfy the `isSubmitted()` condition.

Even if in the HTML, there is the hidden field.

The only way it works is to modify the edit method in the controller, with this line : 
```php
$form = $this->createForm(CategorieType::class, $categorie, ['method' => 'PUT']);
```
And in view, only display the form : 
```twig
 {{ form(form) }}
```

**Comment by xabbuh** [comment]
If you do not configure the method in your form, it will only consider itself to be submitted when the incoming request is a POST request. So the observed behaviour is expected.

**Comment by unsiteavous** [comment]
I think that is not true.

For example, there is the delete route :
```php
  #[Route('/{id}/delete', name: "delete", methods: ['DELETE'])]
  public function delete(Categorie $categorie, EntityManagerInterface $em): Response
  {
    $em->remove($categorie);
    $em->flush();

    $this->addFlash('success', "La catégorie a bien été supprimée.");
    return $this->redirectToRoute('app_categorie_index');
  }
```

And in the twig view : 
```twig
<form action="{{ path('app_categorie_delete', {id: categorie.id}) }}" method="POST">
	<input type="hidden" name="_method" value="DELETE">
	<input type="submit" class="btn btn-danger" value="Delete">
</form>
```

In this case, as you can see, the form is correctly sent with `POST` method, and thanks to the configuration of `framework.yaml` above, this works.

So I still think there is a bug here.

**Comment by unsiteavous** [comment]
And this is in the documentation, as you can see it here : https://symfony.com/doc/current/forms.html#changing-the-action-and-http-method : 
```twig
{# templates/task/new.html.twig #}
{{ form_start(form, {'action': path('target_route'), 'method': 'GET'}) }}
```
>If the form's method is not GET or POST, but PUT, PATCH or DELETE, Symfony will insert a hidden field with the name _method that stores this method. The form will be submitted in a normal POST request, but [Symfony's routing](https://symfony.com/doc/current/routing.html) is capable of detecting the _method parameter and will interpret it as a PUT, PATCH or DELETE request. The [Framework Configuration Reference (FrameworkBundle)](https://symfony.com/doc/current/reference/configuration/framework.html#configuration-framework-http_method_override) option must be enabled for this to work.

So, @xabbuh , can you please review your closed action ?

**Comment by xabbuh** [comment]
In your delete example there is no Symfony form involved. And the documentation excerpt that you quoted does not mean that the method does not have to be configured for the form. If you think that’s not clear enough, feel free to submit an issue or a PR in the docs repository to clarify that, but the bottom line still is that the observed behaviour is expected.

**Comment by unsiteavous** [comment]
Hello, 
Yes that is not clear at all, because in each case, the HTML is the same : 
```html
<form name="categorie" method="post">
    <input type="hidden" name="_method" value="PUT">
    [ ... ]
    <button type="submit" id="categorie_Enregistrer" name="categorie[Enregistrer]" class="btn-primary btn">Enregistrer</button>
</form>
```
So if each case, the HTML form calls the method with a `POST` method, and Symfony transforms the method if there is an input with `_method` name, I really don't understand why there is a preferentiel treatment for one form, the one who recieve its method from controller or FormType. 
If the HTML is similarly, why there is a different behaviour ?

**Comment by xabbuh** [comment]
The HTML does not change the form itself. It only affects the data that is sent by the browser. But your form also needs to know which HTTP method to react to.

**Comment by unsiteavous** [comment]
Oh, that is clearer, does it mean that the form listens to the method, even if the route does it too before ? In this case, I understand why it is necessary to specify the method to the form. 

I had not understood before that the method is listens to the route **AND** the form.
Thank you for the light !
May I ask one more question : what reasons made it possible to choose to force the form to listen to the method independently of the route ? is it for security reasons, or simply for more flexibility ?

**Comment by xabbuh** [comment]
> May I ask one more question : what reasons made it possible to choose to force the form to listen to the method independently of the route ? is it for security reasons, or simply for more flexibility ?

Forms are not aware of the controllers they are used in. Not sure if that answers your question though (and it's probably even a bit late).
