### ISSUE TITLE
symfony/property-access 6.4.6 breaks magic methods

### ISSUE THREAD

**Issue by boonkerz** [symfony/symfony#54739]
### Symfony version(s) affected

6.4.6

### Description

6.4.6 break magic methods. 

### How to reproduce

```
class test
{

    private array $tests = [];


    public function __get(string $name): mixed
    {
        return $this->tests[$name]?? null;
    }

    public function __set(string $name, mixed $value): void
    {
        $this->tests[$name] = $value;
    }
}


$test = new test();
$propertyAccessor = new PropertyAccessor();
var_dump($propertyAccessor->getValue($test, 'Wouter'));
```

6.4.4 return null
6.4.6 return Can't get a way to read the property "Wouter" in class "test"

**Comment by xabbuh** [comment]
Looks like your class is missing the implementation of the `__isset()` method:

```php
public function __isset(string $name): bool
{
    return null !== ($this->tests[$name] ?? null);
}
```

**Comment by boonkerz** [comment]
```
class test
{

    private array $tests = [];

    public function __get(string $name): mixed
    {
        return $this->tests[$name]?? null;
    }

    public function __set(string $name, mixed $value): void
    {
        $this->tests[$name] = $value;
    }

    public function __isset(string $name): bool
    {
        return null !== ($this->tests[$name]?? null);
    }
}


$test = new test();
$propertyAccessor = new PropertyAccessor();
var_dump($propertyAccessor->getValue($test, 'Wouter'));
```


this does not help to fix the behaviour.

returns the same error.

**Comment by boonkerz** [comment]
Here is the Code

https://phpsandbox.io/n/propertyaccess-fipnm

**Comment by bastien-effetb** [comment]
Same problem here

**Comment by n0rbyt3** [comment]
There is an updated check for non-initialized properties which causes the issue: https://github.com/symfony/symfony/blob/b7eb42e504de4f7bad9809ce67a2c672c5f5301c/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L414-L426

Your magic ```__get()``` method can handle uninitialized properties by returning ```null```. Adding this ```__isset()``` method resolves the issue:

```php
public function __isset(string $name): bool
{
  return true;
}
```

**Comment by boonkerz** [comment]
yea that works but this is not obvious.
the docs does not say anything about this new behaviour
https://symfony.com/doc/current/components/property_access.html#magic-get-method
and its differ from the previous version.

**Comment by n0rbyt3** [comment]
Indeed, it's just a workaround.

Friendly ping @nicolas-grekas who changed the implementation in commit 9610a7c2e81fe3060df04c5455a6e2f17c92eb21. An ```__isset()``` implementation has been added to the ```TestClassMagicGet``` fixture which is a BC break.

I don't see any reason why this additional check exists. IMO, it's part of the ```PropertyTypeExtractorInterface``` to detect if the property is accessible. The ```ReflectionExtractor``` inside the ```PropertyInfo``` component does all the reflection logic so there should be no need to reflect the property again - even if another ```PropertyTypeExtractorInterface``` implementation is used. Otherwise ```PropertyReadInfo``` should be extended to return more details for the ```PropertyAccessor```.

**Comment by k0d3r1s** [comment]
i will add this here:  
property-access 6.4.6 and 6.4.7 breaks doctrine migrations diff, going back to 6.4.4 fixes the issue

**Comment by derrabus** [comment]
@k0d3r1s Please open a new issue with a detailed reproducer.

**Comment by kodoa-dev** [comment]
Same problem here, it break my applications

**Comment by nicolas-grekas** [comment]
That's because you're missing an implementation for __isset. While property access was tolerant to this, this breaks the behavior of objects with the php engine.

**Comment by netsuo** [comment]
I have no problem with that, but maybe it needs some doc update

**Comment by nicolas-grekas** [comment]
Maybe a note in the UPGRADE-6.4.md file? Up for a PR?

**Comment by boonkerz** [comment]
@nicolas-grekas the examples on https://symfony.com/doc/current/components/property_access.html#magic-get-method should be fixed
