### ISSUE TITLE
Path is not readable - mime\Part\TextPart checks if a directory is a directory and then throws

### ISSUE THREAD

**Issue by KevsRepos** [symfony/symfony#54767]
### Symfony version(s) affected

6.3

### Description

Error is thrown that `/var/www/html/foo/bar` is not readable when trying to attach a file to an email.

### How to reproduce

Using symfonys mailer to create a mail and attach a file:
```php
		$mail = new Mail();

		$mail->from('hello@example.com');
		$mail->to('you@example.com');

		$mail->attach($myFileToAttach); //$myFileToAttach = \Component\Mime\Part\File
```
symfony will do as follows:
1. call `attach` method from `Symfony\Component\Mime`
2. call `$this->addPart` with `Symfony\Component\Mime\Part\DataPart` as its argument
3. causing the constructor of `DataPart`
4. `DataPart` constructs its parent `TextPart`
5. `TextPart` then does something confusing:

```php
        if ($body instanceof File) {
            $path = $body->getPath();
            if ((is_file($path) && !is_readable($path)) || is_dir($path)) {
                throw new InvalidArgumentException(sprintf('Path "%s" is not readable.', $path));
            }
        }
```
It gets the *containing directory* into `$path` and then checks if this path is a directory, which it just logically has to be and then the error is thrown.

### Possible Solution

Dont check if a directory is a directory, please check instead if a file is a directory.
```php
        if ($body instanceof File) {
            $path = $body->getPath() . $body->getFilename(); // getPath() will just return the path to the file, excluding the file itself.
            if ((is_file($path) && !is_readable($path)) || is_dir($path)) {
                throw new InvalidArgumentException(sprintf('Path "%s" is not readable.', $path));
            }
        }
```

**Comment by xabbuh** [comment]
Symfony 6.3 does not receive bugfixes anymore. If you still see the same behaviour with Symfony 6.4 or higher, please create a small example application that allows to reproduce it.

**Comment by KevsRepos** [comment]
> Symfony 6.3 does not receive bugfixes anymore. If you still see the same behaviour with Symfony 6.4 or higher, please create a small example application that allows to reproduce it.

It still behaves the same in the latest version. Here is a reproduction: https://github.com/KevsRepos/symfony-mime-bug-reproduction

I would really like to know if I am just doing something wrong, or if this really doesnt make any sense.

**Comment by xabbuh** [comment]
I think there is a misunderstanding. The file path must be the full path including the base filename. The (optional) filename argument is there to be able to use independent filenames for how the file is stored to what is presented to the recipient of the e-mail.

**Comment by KevsRepos** [comment]
That's very misleading, but you're right. Thanks. I think the class signature should clarify that it is expecting the full path *including the file name*.
```php
/**
 * @param string $fullPath must have file name included
 * @param ?string $newFileName name to use for e-mail attachments
 * /
```

**Comment by xabbuh** [comment]
PR welcome to clarify this
