### ISSUE TITLE
[Messenger] schema assets filter causes TypeError

### ISSUE THREAD

**Issue by glaubinix** [symfony/symfony#54769]
### Symfony version(s) affected

6.4.7

### Description

[This commit](https://github.com/symfony/doctrine-messenger/commit/43b8a9923c7faa7a6a6948b61d6dab2a1b77a415) introduced a new schema asset filter that filters anything that isn't the doctrine messenger table. However, the filter function can receive other types than string based on this [doctrine code](https://github.com/doctrine/DoctrineBundle/blob/2.12.x/src/Dbal/SchemaAssetsFilterManager.php#L21) the filter can be `string|AbstractAsset`. This can cause a type error in PostgreSQL and potentially other databases.

```
TypeError: Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(): Argument #1 ($tableName) must be of type string, Doctrine\DBAL\Schema\Sequence given
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/Connection.php:301
/home/runner/work/project/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:377
/home/runner/work/project/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:193
/home/runner/work/project/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:1648
/home/runner/work/project/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:1663
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/Connection.php:538
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/Connection.php:302
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/PostgreSqlConnection.php:97
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/Connection.php:434
/home/runner/work/project/vendor/symfony/doctrine-bridge/SchemaListener/AbstractSchemaListener.php:39
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/Connection.php:352
/home/runner/work/project/vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php:89
/home/runner/work/project/vendor/symfony/doctrine-bridge/SchemaListener/MessengerTransportDoctrineSchemaListener.php:43
/home/runner/work/project/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:63
/home/runner/work/project/vendor/doctrine/orm/src/Tools/SchemaTool.php:421
/home/runner/work/project/vendor/doctrine/orm/src/Tools/SchemaTool.php:123
/home/runner/work/project/vendor/doctrine/orm/src/Tools/SchemaTool.php:101
```

### How to reproduce

Have a Symfony doctrine messenger setup on a PostgreSQL database that uses sequences and call the MessengerTransportDoctrineSchemaListener

### Possible Solution

Change the typehint to `$configuration->setSchemaAssetsFilter(fn (string|AbstractAsset $tableName) => $tableName === $this->configuration['table_name']);`

**Comment by hhamon** [comment]
Looks like I'm facing a similar issue after just upgrading Symfony to 6.4.7 on one of my clients projects. Our CI fails and the following error got reported to our Sentry:

> Error thrown while running command "app:redacted-command-name --no-interaction". Message: "Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(): Argument #1 ($tableName) must be of type string, Doctrine\DBAL\Schema\Sequence given"

The new patch release introduced a BC break.

**Comment by nicolas-grekas** [comment]
A regression maybe, a BC break nope ;)

**Comment by hhamon** [comment]
> A regression maybe, a BC break nope ;)

You're right! It does sound to be more like a regression than a BC break here with a the callable accepting `string|AbstractAsset` depending on the configured DBAL context.

**Comment by xabbuh** [comment]
see #54775

**Comment by slappyslap** [comment]
Symfony 7.0 also affected

**Comment by 99hops** [comment]
Saw this after 6.4.7 `bin/console messenger:setup-transports`

```
console.CRITICAL: Error thrown while running command "messenger:setup-transports". 
Message: "Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(): Argument #1 ($tableName) must be of type string, Doctrine\DBAL\Schema\Sequence given" 
```

Should we wait for the next release?

**Comment by derrabus** [comment]
Yes, or try out the dev branch.
