### ISSUE TITLE
Filesystem requires symfony/process after 6.4.7./7.0.7

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#54777]
### Symfony version(s) affected

6.4.7.

### Description

Hi!

After upgrading to symfony/filesystem 6.4.7 it downloads symfony/process too.  
After some digging it looks like it was added by https://github.com/symfony/symfony/pull/54388/files 

Was this intentional? Because all I can find that needs it is tests, so it should be in the require-dev section.

tagging @xabbuh as author of the PR

### How to reproduce

upgrade symfony/filesystem to 6.4.7/7.0.7

### Possible Solution

move symfony/process to require-dev

**Comment by xabbuh** [comment]
that was indeed a mistake, #54778 will fix that
