### ISSUE TITLE
[Messenger] Argument #1 ($tableName) must be of type string

### ISSUE THREAD

**Issue by axzx** [symfony/symfony#54782]
### Symfony version(s) affected

6.4.7

### Description

related commit: https://github.com/symfony/symfony/commit/22dab6798f4ff3b67ec7e3bd67bc43ae9caa9dd1

### How to reproduce

`./bin/console messenger:setup-transports`

result:
```Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::Symfony\Component\Messenger\Bridge\Doctrine\Transport\{closure}(): Argument #1 ($tableName) must be of type string, Doctrine\DBAL\Schema\Sequence given```

vendor/symfony/doctrine-messenger/Transport/Connection.php
line 302

dump($tableName):
```
^ Doctrine\DBAL\Schema\Sequence^ {#1802
  #_name: "messenger_messages_id_seq"
  #_namespace: null
  #_quoted: false
  #allocationSize: 1
  #initialValue: 1
  #cache: null
}
```

**Comment by axzx** [comment]
@MatTheCat Maybe you have an idea how to solve it?

**Comment by xabbuh** [comment]
see #54769
