### ISSUE TITLE
BicValidator/IbanValidator value normalization

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#54822]
### Symfony version(s) affected

6.4.2

### Description

We use BicValidator and IbanValidator for validating IBAN/SWIFT and some times people enter everything in lower case and validation fails. because `fr != FR`

### How to reproduce

Just enter everything in lower-case

### Possible Solution

Normalize value with `strtoupper`

**Comment by ro0NL** [comment]
there was some previous debate on normalization vs. validation: https://github.com/symfony/symfony/issues/35316

i guess this constraint should be made more lenient
