### ISSUE TITLE
[Ldap] UpdateOperation toArray() function throws exception when using LDAP_MODIFY_BATCH_REMOVE_ALL operation type

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#54829]
### Symfony version(s) affected

7.0.7

### Description

Performing a batch operation using the `LDAP_MODIFY_BATCH_REMOVE_ALL` operation type produces an exception: _ldap_modify_batch(): If option modtype" is LDAP_MODIFY_BATCH_REMOVE_ALL, option "values" cannot be provided_

### How to reproduce

Apply a batch update operation with an `LDAP_MODIFY_BATCH_REMOVE_ALL` operation type.
e.g. using the example code from https://symfony.com/doc/current/components/ldap.html ...

```php
use Symfony\Component\Ldap\Adapter\ExtLdap\UpdateOperation;
use Symfony\Component\Ldap\Ldap;

$ldap = Ldap::create('ext_ldap', [
    'host' => 'my-server',
    'encryption' => 'ssl',
]);

$entryManager = $ldap->getEntryManager();
$entryManager->applyOperations('cn=Fabien Potencier,dc=symfony,dc=com', [
    new UpdateOperation(LDAP_MODIFY_BATCH_REMOVE_ALL , 'mail', NULL),
]);
```

### Possible Solution

For LDAP_MODIFY_BATCH_REMOVE_ALL operations, omit the `values` element from the [`toArray()`](https://github.com/symfony/ldap/blob/2439e5a1d15b28d56f78e70d4e6f6d00faa9d183/Adapter/ExtLdap/UpdateOperation.php#L49) return value, i.e. update `toArray` function:

```php
public function toArray(): array
{
  $op = [
      'attrib' => $this->attribute,
      'modtype' => $this->operationType,
  ];
  if (\LDAP_MODIFY_BATCH_REMOVE_ALL !== $this->operationType) {
      $op['values'] = $this->values;
  }
  return $op;
}
```

or (more concise/fewer changes):

```php
public function toArray(): array
{
  return [
    'attrib' => $this->attribute,
    'modtype' => $this->operationType,
    ...(\LDAP_MODIFY_BATCH_REMOVE_ALL !== $this->operationType ? ['values' => $this->values] : [])
  ];
}
```

**Comment by ghost** [comment]
It looks like tests need a local LDAP server, otherwise [they're skipped](https://github.com/symfony/ldap/blob/2439e5a1d15b28d56f78e70d4e6f6d00faa9d183/Tests/LdapTestCase.php#L24). I'll set up a VM with a local LDAP server to confirm the bug is fixed before submitting a PR.

**Comment by jerrac** [comment]
I'm running into this on Symfony 6.4.  The LDAP library is v6.4.7. 

If I manually modify the UpdateOperation toArray method to not return the values key when it's the LDAP_MODIFY_BATCH_REMOVE_ALL op, I can it to work, so I'm pretty sure this bug is what I'm running into.

My error message:

```
In EntryManager.php line 174:
                                                                                                                
  [ValueError]                                                                                                  
  ldap_modify_batch(): If option "modtype" is LDAP_MODIFY_BATCH_REMOVE_ALL, option "values" cannot be provided  

```

Is another issue or pull request needed?

**Comment by xabbuh** [comment]
The related PR has not been released yet. It will be part of the 6.4.8 patch release.

**Comment by jerrac** [comment]
Ah. I thought it was just on the 7.x branch. Thanks for letting me know I was wrong. :)
