### ISSUE TITLE
[Config] ParamConfigurator is not longer respected as scalar-string-value

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#54852]
### Symfony version(s) affected

7.1.0-BETA1

### Description

After update to BETA released version, I got an error for configuration, where `ParamConfigurator` is not anymore respected as `scalar` value.

I don't know what changes cause this issue.

### How to reproduce

One of: 

```php
use Symfony\Config\FrameworkConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;

return static function (FrameworkConfig $frameworkConfig): void {
    $frameworkConfig->phpErrors()
        ->log(value: param(name: 'kernel.debug'));
};
```

### Possible Solution
Cast `ParamConfigurator` to string anyway, when the configuration allows you to pass an object.
```php
use Symfony\Config\FrameworkConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;

return static function (FrameworkConfig $frameworkConfig): void {
    $frameworkConfig->phpErrors()
        ->log(value: (string) param(name: 'kernel.debug'));
};
```

### Additional Context

![obraz](https://github.com/symfony/symfony/assets/16488888/4976c146-934f-43e4-93af-d8fb3e203557)
![obraz](https://github.com/symfony/symfony/assets/16488888/dc96e749-927d-4b9d-a5d3-220d6df88765)

**Comment by nicolas-grekas** [comment]
Can you figure out which change trigger this regression?

**Comment by michaljusiega** [comment]
~~No, I cannot.~~

As far as I know is:

- `ParamConfigurator` should be resolved by https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/DependencyInjection/Loader/Configurator/AbstractConfigurator.php#L91
- Not all `ParamConfigurator` objects are passed to `AbstractConfigurator::processValue()`
- The difference is visible before calling `Extension::procesConfiguration()` with variable `$configs`

7.0:
![obraz](https://github.com/symfony/symfony/assets/16488888/6bb6c85f-8f04-4eb6-af48-a0f5f73ab858)
7.1
![obraz](https://github.com/symfony/symfony/assets/16488888/23af20b9-3aea-4580-aeda-4cd62e1fe1b6)

https://github.com/symfony/symfony/pull/52843 this change is the closest to regression, but I could be wrong.

**Edit: I think, I found something !**

In 7.0 (https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php#L150) each `ConfigBuilder` instance after callback is processed further by `ContainerConfigurator` which array result was wrapped by `AbstractConfigurator::processValue()` in https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/DependencyInjection/Loader/Configurator/ContainerConfigurator.php#L58

In 7.1 collected configs are loaded directly by https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php#L157 without processing values by using `AbstractConfigurator::processValue()`

My suggestion to fix this problem:
```diff
Subject: [PATCH] Fixed non-processed configs
diff --git a/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php b/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
--- a/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
+++ b/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
@@ -27,6 +27,7 @@
 use Symfony\Component\DependencyInjection\Definition;
 use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;
 use Symfony\Component\DependencyInjection\Exception\LogicException;
+use Symfony\Component\DependencyInjection\Loader\Configurator\AbstractConfigurator;
 
 /**
  * FileLoader is the abstract class used by all built-in loaders that are file based.
@@ -229,6 +230,8 @@
 
     final protected function loadExtensionConfig(string $namespace, array $config): void
     {
+        $config = AbstractConfigurator::processValue($config);
+
         if (!$this->prepend) {
             $this->container->loadFromExtension($namespace, $config);
```

**Comment by michaljusiega** [comment]
@nicolas-grekas Can We move further this issue ? I think it's important blocker, somebody who using PHP config.
