### ISSUE TITLE
[scheduler] support stateful option when defining recurring messages via #[AsPeriodicTask] / #[AsCronTask] attributes

### ISSUE THREAD

**Issue by JustDylan23** [symfony/symfony#54861]
### Description

Affected versions: 6.x, 7.x

According to the docs when using the scheduler via the `#[AsSchedule]` where you manually define recurring messages you can use the `stateful` method to define a cache pool. The docs say: "This allows the system to retain the state of the schedule, ensuring that when a worker is restarted, it resumes from the point it left off."

```php
#[AsSchedule('uptoyou')]
class SaleTaskProvider implements ScheduleProviderInterface
{
    public function getSchedule(): Schedule
    {
        $this->removeOldReports = RecurringMessage::cron('3 8 * * 1', new CleanUpOldSalesReport());

        return $this->schedule ??= (new Schedule())
            ->with(
                // ...
            )
            ->stateful($this->cache)
    }
}
```

I want to define a recurring message like this:
```php
#[AsCronTask('3 8 * * 1')]
class SaleTaskProvider
{
    public function __construct(
        private readonly MessageBusInterface $bus
    ) {
    }

    public function __invoke()
    {
        $this->bus->dispatch(new CleanUpOldSalesReport());
    }
}
```
The issue I am having is that this that I cannot configure which caching pool it should use. It currently does not use any cache pool at all via the latter code snippet.

From my digging through the source code I could not find any indication the cache pool can be configured when using the attributes in the title of this issue.

Can anyone confirm this is true and is this something that should be added?

**Comment by valtzu** [comment]
The autoconfigured schedule decorates the existing schedule provider definition, if found. This means you should have both – the schedule provider as the service (which configures cache and lock if needed) and then the task using `#[AsCronTask]` on any autoconfigured service.

With the DI configuration below you don't need a separate php class for the schedule provider and can just use the task attributes / tags.

```yaml
services:
  my_stateful_scheduler:
    class: Symfony\Component\Scheduler\Schedule
    calls:
      - stateful: ['@cache.app']
    tags:
      - scheduler.schedule_provider: { name: default }
```

**Comment by JustDylan23** [comment]
Thanks, the code snippet you provided did the job.
