### ISSUE TITLE
[Serializer] Performance degradation

### ISSUE THREAD

**Issue by mateuszsip** [symfony/symfony#54865]
### Symfony version(s) affected

7.0.7, 6.4.7

### Description

Recently after renovate upgrade bumping a few SF components (including serializer bump 6.4.6 -> 6.4.7) we noticed that our service started having performance problems on one endpoint. 

CPU usage went to 100%, service autoscaled up to the limit and we've noticed on traces that service is getting stuck on processing not related to any IO operations.

What's specific about this endpoint is that we receive large json strings that are at some point getting serialized/deserialized and that's what got slow after upgrade.

At some point I even upgraded service to SF 7.0.7 and problem didn't go away.
It looks that downgrading to 6.4.6 or 7.0.6 helps, so I believe that root cause is here:  https://github.com/symfony/serializer/compare/v7.0.6...v7.0.7

I don't have any profiles that would tell exactly where it uses so much CPU the problem.

### How to reproduce

I will do my best to prepare example repo later today.

### Additional Context

We denormalize payload to an object that uses attributes with serialization group and public getters/setters.
See that changes between tags are related to that.

To test fixes, I prepared a load test using example payload (~850kb)
![image](https://github.com/symfony/symfony/assets/1377075/38f78a95-ff39-4a2e-b3f8-6bf67369e92c)
And p95 went to above 15s on 7.0.7.

Where on revision with a simple serializer dowgrade to 7.0.6 and exactly the same test it's back to normal:
![image](https://github.com/symfony/symfony/assets/1377075/3a799895-be1e-4c6d-bfd3-ece20b77bd8f)

**Comment by stloyd** [comment]
I can confirm that this issue occurs on 7.0.7 but not on the previous one:
<img width="420" alt="Zrzut ekranu 2024-05-6 o 16 27 17" src="https://github.com/symfony/symfony/assets/67402/ae3a8cf8-af6b-48ca-8d33-ebfaba440a0c">
<img width="421" alt="Zrzut ekranu 2024-05-6 o 16 27 33" src="https://github.com/symfony/symfony/assets/67402/9144ac2e-da92-4328-8f29-dc54fe7b7d8b">

Most likely created after the merge of https://github.com/symfony/symfony/pull/52917, as you can see above, especially affected seems to be that method: https://github.com/symfony/symfony/pull/52917/files#diff-397b4689ce56cc95e54911f6d78639bb3258a9ee9b36bfa06ec719e9635e6b1dR195

**Comment by greg0ire** [comment]
Cc @mtarld

**Comment by mtarld** [comment]
Just created a PR caching the check whether a property is readable or writable. Could you try on your project @mateuszsip and @stloyd?
Thanks for the great detailed issue btw :slightly_smiling_face:
