### ISSUE TITLE
 #[MapUploadedFile] Missing or Invalid 'name' Parameter Causes Type Error

### ISSUE THREAD

**Issue by rcsofttech85** [symfony/symfony#54871]
### Symfony version(s) affected

7.1

### Description

In the changeUserPicture() function, if the 'name' parameter in the MapUploadedFile attribute is missing or invalid, it results in a type error being thrown. This behavior could lead to unexpected exceptions and is not clearly handled.

### How to reproduce

```php
    public function changeUserPicture(
        #[MapUploadedFile(
            constraints: new Assert\File(mimeTypes: ['image/png', 'image/jpeg']),

        )] ?UploadedFile $picture
    ): Response
    {
        //
    }
```

### Possible Solution

   ```php
 public function changeUserPicture(
        #[MapUploadedFile(
            constraints:
            new Assert\File(mimeTypes: ['image/png', 'image/jpeg']),
            name:
            'file'
        )] ?UploadedFile $picture
    ): Response
    {
       //
    }
```

### Additional Context

![Screenshot from 2024-05-09 18-38-44](https://github.com/symfony/symfony/assets/17738213/44f4d935-5fac-439c-8cf5-5fec9972fa46)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by rcsofttech85** [comment]
I had already mentioned in the description how to reproduce, but let me explain it again. If I understand the feature correctly, it converts the uploaded file to Symfony\Component\HttpFoundation\File\UploadedFile internally. However, the 'name' parameter is currently optional when it should be mandatory. If you omit the 'name' parameter, it will return an empty array instead of an UploadedFile, resulting in a type error [500].

```php
    #[Route(path:'/user/picture',name:'upload_route', methods: ['POST'])]
    public function changeUserPicture(
        #[MapUploadedFile(
        )] ?UploadedFile $picture
    ): Response
    {
       // type error
    }
```
```php
    #[Route(path:'/user/picture',name:'upload_route', methods: ['POST'])]
    public function changeUserPicture(
        #[MapUploadedFile(
           name: 'file'
        )] ?UploadedFile $picture
    ): Response
    {
       dd($picture); // it works
    }
```

```twig
<form action="{{ path('upload_route') }}" method="post" enctype="multipart/form-data">
    <input type="file" name="file" id="file">
    <button type="submit">Upload</button>
</form>
```

**Comment by asispts** [comment]
What @xabbuh means is that you create a new symfony project to reproduce the issue and then post the repo url here.

**Comment by rcsofttech85** [comment]
https://github.com/rcsofttech85/symfony-test

symfony server:start
http://localhost:8000/home

you should see form upload option.

**Comment by renedelima** [comment]
> ```
>     #[Route(path:'/user/picture',name:'upload_route', methods: ['POST'])]
>     public function changeUserPicture(
>         #[MapUploadedFile(
>         )] ?UploadedFile $picture
>     ): Response
>     {
>        // type error
>     }
> ```
> 
> ```
> <form action="{{ path('upload_route') }}" method="post" enctype="multipart/form-data">
>     <input type="file" name="file" id="file">
>     <button type="submit">Upload</button>
> </form>
> ```

Thanks for sharing it @rcsofttech85.

When you omit the attribute parameter `name`, the value resolver will try to fetch the uploaded file based on the variable name, which is `$picture` in this case. So the form field should be changed to `<input type="file" name="picture" id="file">` to match with the controller argument.

Alternatively,  you can also change the argument  to `#[MapUploadedFile] ?UploadedFile $file` to match with with the form field.

**Comment by rcsofttech85** [comment]
Ah, the value resolver..I feel a bit embarrassed,I've forgotten most of what I knew about it. Cheers!

**Comment by DarthLegiON** [comment]
@renedelima hi! Am I right, that if the form (or curl, or, in my case, tests) do not have 'picture' file inside the request, we will get 500 error in the result because the resolver returns an empty array by default?

I assume getting 500 as a result of malformed request isn't right. 400 or 422 would be much better.
