### ISSUE TITLE
Twig extension "constant" now forces the return value as string, while it can be anything including an array

### ISSUE THREAD

**Issue by Carla-DW** [symfony/symfony#54889]
### Symfony version(s) affected

7.0.7

### Description

When the constant is an array, an exception is now thrown: 

An exception has been thrown during the rendering of a template ("Twig\Extension\CoreExtension::constant(): Return value must be of type string, array returned").

### How to reproduce

Try with any constant defined as an array

### Possible Solution

Allow mixed as return value

**Comment by xabbuh** [comment]
see https://github.com/twigphp/Twig/pull/4085
