### ISSUE TITLE
[3.0] [Form] Expanded choice field does not display group headings

### ISSUE THREAD

**Issue by mlfrazier-xx** [symfony/symfony#5489]
When using `"expanded" => true` on a `choice` field that contains groups, the default form theme simply renders all radio buttons/checkboxes sequentially, without headings or any other indication of the group structure (at least under Twig).

From what I can tell, this issue stems from the fact that the choices in an expanded choice field are written directly from the `FormView`'s `choices` variable, which is structured into groups. By contrast, expanded choice fields are represented using a series of checkbox/radio button fields, which are treated as children of the choice field - the problem being that the children are not arranged in any hierarchical structure.

The `FormView` for an expanded choice field does still have a `choices` variable like that of a collapsed choice field, but currently there is no effective way to match up the `ChoiceView` object with the corresponding child `FormView` in the template, so rendering the fields from the `choices` variable as with a collapsed choice field is not a viable option.

**Comment by garak** [comment]
I see that this issue has been tagged with "[3.0]", even if it dates back to 2012, so I guess that this will be solved in Symfony 3.
Is there any solution for Symfony 2?

**Comment by JHGitty** [comment]
+1

**Comment by MaxEndter** [comment]
In Symfony 2.8 the following works for me:

``` php
{%- block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        {% for name, choices in form.vars.choices %}
            <label class="checkbox_category">
                <strong>
                    {{ translation_domain is same as(false) ? name : name|trans({}, translation_domain) }}
                </strong>
            </label>
            <div>
            {% for key,choice in choices %}
                {{ form_widget(form[key]) }}
                {{ form_label(form[key]) }}
            {% endfor %}
            </div>
        {% endfor %}
    </div>
{%- endblock choice_widget_expanded -%}
```

**Comment by walidjlidi** [comment]
Thanks a lot MaxE17677 it works for me after changing form theme to bootstrap3

**Comment by TerjeBr** [comment]
@webmozart Could this be solved in the templates like @MaxE17677 did? It seems a lot simpler than using groups of child nodes in the form. What do you think?

If the soulution of looping on `form.vars.choices` in the template, instead of looping on `form` is an acceptable solution, I could make a PR for you on this.

**Comment by HiImJulien** [comment]
This issue dates back to 2012. I am stuck with SF 3.3.
Are there any built-in solutions I missed out on?

**Comment by xabbuh** [comment]
closing here in favour of #19514
