### ISSUE TITLE
symfony/polyfill-php80 error logs

### ISSUE THREAD

**Issue by TheCartpenter** [symfony/symfony#54902]
### Symfony version(s) affected

v1.29.0

### Description

[symfony_polyfill_v129_0_logs.txt](https://github.com/symfony/symfony/files/15293087/symfony_polyfill_v129_0_logs.txt)

### How to reproduce

Ran with the ```composer``` . Package does get successfully installed but noticing this error message.

### Possible Solution

Follow the error logs report.

**Comment by xabbuh** [comment]
the reported class is internal, using `new static()` there is safe
