### ISSUE TITLE
symfony/translation-contracts

### ISSUE THREAD

**Issue by TheCartpenter** [symfony/symfony#54903]
### Symfony version(s) affected

v3.5.0

### Description

If it can help the community, followed are the error logs produced by PHPStan when successfully installing this package.
[symfony_translation_contracts_v3_5_0_logs.txt](https://github.com/symfony/symfony/files/15293119/symfony_translation_contracts_v3_5_0_logs.txt)

### How to reproduce

Installed with ```composer```. Package gets successfully installed but ending with these error messages with PHPStan.

### Possible Solution

Follow the provided error log messages.

**Comment by xabbuh** [comment]
these are false positives
