### ISSUE TITLE
[PropertyAccess] "Fix checking for missing properties" breaks magic __get method

### ISSUE THREAD

**Issue by Nicolas35** [symfony/symfony#54940]
### Symfony version(s) affected

6.4.7

### Description

Since this update : [Fix checking for missing properties](https://github.com/symfony/property-access/commit/e94ea5f13b3e426e8423a890717289b7db509a4f)

It is no longer possible to use the magic methods __get and __set of an entity inside a formtype.
It throws an error "Can't get a way to read the property "xxx" in class xxx"

It was working since a composer update this day : 

`Upgrading symfony/property-info (v6.4.3 => v6.4.7)`

### How to reproduce

FormType :

`class RetrocessionDemenagementDepartementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        foreach(RetrocessionDemenagementDepartement::LISTE_DEPARTEMENTS as $numero => $nom)
        {
            $builder->add('departement_'.$numero, NumberType::class, array(
                    'label' => $nom,
                    'required' => false,
                    'translation_domain' => false,
                    'attr' => [
                        'class' => 'form-control',
                    ]
                ));
        }`

Entity method :

`
    public function __get($propertyName)
    {
        $dept = str_replace('departement_', '', $propertyName);

        return array_key_exists($dept, $this->montantParDepartement) ? $this->montantParDepartement[$dept] : 0;
    }`

**Comment by nicolas-grekas** [comment]
This happens because you didn't implement the __isset method, which is required by the PHP engine for it to behave properly.

**Comment by Nicolas35** [comment]
It's ok ! 
Thanks so much :)

**Comment by kodoa-dev** [comment]
> This happens because you didn't implement the __isset method, which is required by the PHP engine for it to behave properly.

In my case, I have implemented the isset method and it dowsn't work since version 6.4.3

**Comment by xabbuh** [comment]
@aesislabs Please open a new issue with an example application that allows to reproduce it.
