### ISSUE TITLE
[AssetMapper] Add minification since deprecated by cloudflare

### ISSUE THREAD

**Issue by ChristianVermeulen** [symfony/symfony#54964]
### Description

Asset-Mapper has made a clear choice to not minify assets and move this responsibility to the webserver. Mainly referring to CloudFlare who can do this automatically.

Documentation: [Does the AssetMapper Component Minify Assets?](https://symfony.com/doc/current/frontend/asset_mapper.html#does-the-assetmapper-component-minify-assets)

Which refers to [Optimization](https://symfony.com/doc/current/frontend/asset_mapper.html#optimization).

Which states the following:

> In Cloudflare, assets are compressed by default and you can also enable [auto minify](https://developers.cloudflare.com/support/speed/optimization-file-size/using-cloudflare-auto-minify/) to further compress your assets (e.g. removing whitespace and comments from JavaScript and CSS files).

Going to those Cloudflare docs, it seems the auto-minify feature is deprecated:

> **Deprecation notice**
Auto Minify is deprecated and will be removed on 2024-08-05. After this date, Auto Minify will no longer be available via the Cloudflare dashboard, API, or Terraform.

> We recommend that you minify at the origin during the build phase. Minification is included in most modern web development frameworks.

Considering Cloudflare will no longer support it, ánd advises to do this at build-time, it might be worth reconsidering this and perhaps add minification to AssetMapper after all?

### Example

This could simply be toggled in config, though it would probably be best to have this behaviour by default.

```yml
when@dev:
    framework:
        asset_mapper:
            minify: false

when@prod:
    framework:
        asset_mapper:
            minify: true
```

**Comment by Nek-** [comment]
This looks like a duplicate of https://github.com/symfony/symfony/issues/54907

**Comment by derrabus** [comment]
> This looks like a duplicate of #54907

Indeed.
