### ISSUE TITLE
Simplify the definition of unique entity column names

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#55145]
### Description

Currently, when we need to define a unique column name, we'll write
```php
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User
{
    #[ORM\Column(length: 180)]
    private string $email;
}
```

It'll be much more intuitive if we can write
```php
class User
{
    #[ORM\Column(length: 180, unique: true, uniqueName:'UNIQ_IDENTIFIER_EMAIL')]
    private string $email;
}
```

We can still use `ORM\UniqueConstraint` for multiple fields though.

**Comment by berkut1** [comment]
I think one of the method used in SQL is more intuitive. When you also can add a CONSTRAINT next to the attribute.
```SQL
CREATE TABLE example_table (
    id INT PRIMARY KEY,
    email VARCHAR(100) CONSTRAINT unique_email UNIQUE
);
```


```php
class User
{
    #[ORM\Column(length: 180, unique: true)]
    #[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL')]
    private string $email;
}
```

**Comment by asispts** [comment]
> ```php
> class User
> {
>     #[ORM\Column(length: 180, unique: true)]
>     #[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL')]
>     private string $email;
> }
> ```

Then, there's no point to have `unique: true` in `ORM\Column`

**Comment by xabbuh** [comment]
You will have to report this feature request to the Doctrine project as that’s where the code for the ORM lives. Closing here therefore. Thank you for understanding.
