### ISSUE TITLE
[Form] generic choice block name

### ISSUE THREAD

**Issue by havvg** [symfony/symfony#5642]
Hi, 

it would be great to have an equivalent generic block name for choices like for collections, a block for `ChoiceType` to render the individual widgets for each choice entry (e.g. each radio button for an expanded choice), for example `_form_name_choice_widget`.

**Comment by javiereguiluz** [comment]
I'm closing this 3-year-old issue because is no longer active and because the form theme provides enough blocks for choice types: generic (`choice_widget`), specific (`choice_widget_expanded`, `choice_widget_collapsed`), for options (`choice_widget_options`), etc.
