### ISSUE TITLE
[Form] Support auto guessing for Form types when using property_path

### ISSUE THREAD

**Issue by fkrauthan** [symfony/symfony#5645]
If I have in my code something like that:

```
$builder->add('contributor_file', null, array('property_path' => 'contributor.file'));
```

While `contributor.file` has a Assert\Image attached which produces without property_path a file upload field and with property_path a text field. So it looks like that the form field guessing doesn't work correctly if you use `property_path`.

I have the issue with Symfony 2.1.2

**Comment by fabpot** [comment]
Closing this old issue as nobody ever worked on it and this looks complicated anyway.
