### ISSUE TITLE
memcache cluster support in doctrine bridge

### ISSUE THREAD

**Issue by dchi** [symfony/symfony#5682]
We are working w/ symfony 2.1 and attempting to use the memcached implementation for doctrine caching. Unfortunately, it seems that we can only set one server for memcached. 

I see the following code in [AbstractDoctrineExtension.php](http://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php)

```php
$memcachedHost = !empty($cacheDriver['host']) ? $cacheDriver['host'] : '%'.$this->getObjectManagerElementName('cache.memcached_host').'%';
$memcachedPort = !empty($cacheDriver['port']) ? $cacheDriver['port'] : '%'.$this->getObjectManagerElementName('cache.memcached_port').'%';
$cacheDef = new Definition($memcachedClass);
$memcachedInstance = new Definition($memcachedInstanceClass);
$memcachedInstance->addMethodCall('addServer', array(
                    $memcachedHost, $memcachedPort
                ));
```

It seems that the extension only only reads one host and port. Am I reading the code wrong or missing another area to setup memcached for doctrine?

**Comment by fabpot** [comment]
Closing this old issue, @dlsniper apparently submitted a PR on DoctrineBundle at some point.
