### ISSUE TITLE
[Serializer] Serializing empty class without properties serializes to `[]` when `preserve_empty_objects` is enabled

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#56875]
### Symfony version(s) affected

7.1-RC1

### Description

While testing 7.1-RC1 I noticed a change in behavior.

I have a test suite that serializes all commands (for a command bus) and confirms that they can be deserialized.

There is a command that does not have any properties:
```php
final class DoSomethingCommand {}
```

When this is serialized with Symfony 7.0, it produces `{}`.

But with Symfony 7.1-RC1 it becomes `[]`.

### How to reproduce

See above.

### Possible Solution

While debugging the situation, I notice that in 7.0 the empty object gets normalized into ArrayObject (empty). 
![Screenshot 2024-05-22 at 09 29 47@2x](https://github.com/symfony/symfony/assets/104180/35ee7d5d-0ba1-4a42-a0a2-115673ea8eaa)

But on 7.1-RC1 it becomes an empty array.
![Screenshot 2024-05-22 at 09 31 35@2x](https://github.com/symfony/symfony/assets/104180/3f3ff19c-c817-424a-84f2-1222bd9f98bf)

**Comment by ruudk** [comment]
I have enabled the feature in the default context in the Framework:
```php
            'serializer' => [
                'enabled' => true,
                'name_converter' => 'serializer.name_converter.camel_case_to_snake_case',
                'default_context' => [
                    AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true,
                    Serializer::EMPTY_ARRAY_AS_OBJECT => true,
                ],
            ],
```

It might be the case, that this default context is no longer used. Not sure.

**Comment by HypeMC** [comment]
@ruudk Could you see if #57186 fixes your issue?

**Comment by ruudk** [comment]
@HypeMC This does solve my issue indeed, thanks!

**Comment by HypeMC** [comment]
@ruudk After some feed back I realized that my initial fix was completely wrong. Even though it work, it was not the right place for it, so could you try #57273 instead.

**Comment by ruudk** [comment]
@HypeMC It does solve the issue! 🎉
