### ISSUE TITLE
[Serializer] Cannot get base type on `int|string` compound type

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#56874]
### Symfony version(s) affected

7.1-RC1

### Description

The Serializer component switched to the new TypeInfo component and now our serialization breaks:

> Symfony\Component\TypeInfo\Exception\LogicException : Cannot get base type on "int|string" compound type.

### How to reproduce

```php
final readonly class AddToCart
{
    /**
     * @param array<string, string|int> $metadata
     */
    public function __construct(
        public string $cartId,
        public array $metadata,
    ) {}
}
```

> Symfony\Component\TypeInfo\Exception\LogicException : Cannot get base type on "int|string" compound type.
>  /Volumes/CS/www/cosmos/vendor/symfony/type-info/Type/UnionType.php:48
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:705
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:830
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:371
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:239
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:335
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Serializer.php:238
>  /Volumes/CS/www/cosmos/vendor/symfony/serializer/Serializer.php:143

**Comment by MatTheCat** [comment]
Seeing #40474 I guess this is not supported? Couldn’t find any mention in the documentation though :thinking: 

Seems like when using the `PropertyInfo` it would only consider the “first” of the union’s types: https://github.com/symfony/symfony/blob/85db734e06e8cb32365810958326d48084bf48ba/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L447

**Comment by HypeMC** [comment]
@ruudk Could you see if #57197 fixes your issue?

**Comment by ruudk** [comment]
@HypeMC This solves my problem too! Great work 🎉
