### ISSUE TITLE
ChoiceType fails when there is `null` in array submitted

### ISSUE THREAD

**Issue by nikola-jovanovic-php** [symfony/symfony#56877]
### Symfony version(s) affected

7.0

### Description

Warning: array_flip(): Can only flip string and integer values, entry skipped

### How to reproduce

pass `null` value as an value of `ChoiceType` that has `multiple` option set to `true` (array of values).

```
{
    "choice": [null, ...]
}
```

### Possible Solution

filter `null` values from array or convert them to empty string

### Additional Context

failing line: https://github.com/symfony/form/blob/7.0/Extension/Core/Type/ChoiceType.php#L125

**Comment by xabbuh** [comment]
I fail to see how `null` can be part of the values submitted by a browser. Can you create a small example application that allows to reproduce the behaviour that you observe?

**Comment by nikola-jovanovic-php** [comment]
> I fail to see how `null` can be part of the values submitted by a browser. Can you create a small example application that allows to reproduce the behaviour that you observe?

it's submitted by API via JSON body:

```
$builder = $this->createFormBuilder();
$builder->add('choices', ChoiceType::class, [
    'choices' => ['a' => 1, 'b' => 2, 'c' => 3],
    'multiple' => true
]);
$form = $builder->getForm();
$form->submit(['choices' => [null, 1]]);
```

No matter how that input have had happened, it's not expected behavior for error to occur. it should have been probably converted to empty string and then `ChoiceType` would proceed as usual.

**Comment by xabbuh** [comment]
The Form component is designed to work with HTML forms where the submitted data always is a string or arrays of strings. If you use it for your API where types can differ, you have to take care of registering custom transformers yourself that take care of additional types. That said I am going to close here as the observed behaviour is not a bug in the component. Thank you for understanding.
