### ISSUE TITLE
Feature request: Direct connection to db via console

### ISSUE THREAD

**Issue by nbennett25** [symfony/symfony#56949]
### Description

It would be handy to have a direct connection to the database via the console, as sometimes `bin/console doctrine:query:sql` isn't sufficient:

`root@44c6f906c03c:/var/www/html# bin/console doc:query:sql "show tables";`
`[OK] 0 rows affected.`

### Example

`bin/console dbal:console` (or similar)

drops you into 
```
[db_engine] [database_name] > show tables;
+------------------------------+
| Tables_in_db_name |
+------------------------------+
| entity_1                     |
| entity_2                |
...
```

**Comment by k0d3r1s** [comment]
i would say that this belongs in doctrine ecosystem (like doctrine-bundle) and not here

**Comment by derrabus** [comment]
Closing as explained.
