### ISSUE TITLE
The assert.warning INI setting is deprecated with PHP 8.4

### ISSUE THREAD

**Issue by k0d3r1s** [symfony/symfony#56963]
### Symfony version(s) affected

7.2.0-DEV

### Description

Exactly the same issue as #51467, only now newer symfony and php versions.

```Deprecated: ini_set(): assert.warning INI setting is deprecated in /var/www/html/vendor/symfony/runtime/Internal/BasicErrorHandler.php on line 35```

### How to reproduce

Simple symfony installation on PHP 8.4

### Additional Context

Must be something new, as last week on 7.1 it did not trigger this. I know php 8.4 is not out yet but this looks more like symfony problem and not php

**Comment by xabbuh** [comment]
Can you figure out where this is called? I don't see anything related to this in the Symfony codebase.

**Comment by MatTheCat** [comment]
The line the log mentions was removed by #50994 which got merged months ago. Are you sure you’re running Symfony 7.2?

**Comment by k0d3r1s** [comment]
i have found my issue, so closing this.

on the other note, how can it be if i have constraint of 7.2.* in composer.json, composer update to downgrade symfony packages below 7.2, or even below 6?
