### ISSUE TITLE
[Config] Error accessing uninitialized $resolver in Loader

### ISSUE THREAD

**Issue by radar3301** [symfony/symfony#57066]
### Symfony version(s) affected

6.x, 7.x

### Description

I am receiving the following error:

```
Error {#2549
  #message: "Typed property Symfony\Component\Config\Loader\Loader::$resolver must not be accessed before initialization"
  #code: 0
  #file: "D:\inetroot\websites\demo\vendor\symfony\config\Loader\Loader.php"
  #line: 60
}
```

The line in question is: `$loader = null === $this->resolver ? false : $this->resolver->resolve($resource, $type);`, however, the defined property is `protected LoaderResolverInterface $resolver;` (line 35).

### How to reproduce

```
class MyBundle extends AbstractBundle
{
    public function configure(DefinitionConfigurator $definition): void
    {
        $definition->import(dirname(__DIR__) . '/config/*.yaml', 'yaml');
    }
}
```

Please disregard the fact that I'm attempting to load YAML in the below reproduction code. Apparently there isn't built-in support for loading YAML configuration in bundles...

### Possible Solution

I suggest the either of the following changes:
1. Symfony 6.x / 7.x : `$loader = isset($this->resolver) ? $this->resolver->resolve($resource, $type) : false;`
2. Symfony 7.x: `protected ?LoaderResolverInterface $resolver` and `public function getResolver(): ?LoaderResolverInterface`

**Comment by radar3301** [comment]
As an additional note, the following error also exists:

`Fatal error: Uncaught TypeError: Symfony\Component\Config\Loader::getResolver(): Return value must be of type LoaderResolverInterface, null returned`

**Comment by xabbuh** [comment]
see #57069
