### ISSUE TITLE
[Serializer] Call to undefined method PropertyInfoCacheExtractor::getWriteInfo()

### ISSUE THREAD

**Issue by maxkain** [symfony/symfony#57078]
### Symfony version(s) affected

6.4.7

### Description

Calling method, which does not exists. After update this error occurs. With version 6.4.6 it works.

### How to reproduce

```php
$denormalizer->denormalize($row, Some::class, null, [
    ObjectNormalizer::OBJECT_TO_POPULATE => $someObject,
    ObjectNormalizer::DISABLE_TYPE_ENFORCEMENT => true,
]);
```

### Additional Context

Call to undefined method Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor::getWriteInfo() /proj/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php 193
0 /proj/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php(247): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->isAllowedAttribute()
1 /proj/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(159): Symfony\Component\Serializer\Normalizer\AbstractNormalizer->getAllowedAttributes()
2 /proj/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(328): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAllowedAttributes()
3 /proj/vendor/symfony/serializer/Serializer.php(247): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize()

**Comment by HypeMC** [comment]
This was fixed in #54804, should be available in the next release.
