### ISSUE TITLE
[DoctrineBridge] issues with UniqueEntityValidator on 7.1-RC1

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#57075]
### Symfony version(s) affected

7.1 RC1

### Description

I just tested 7.1 RC1 on my biggest app and I noticed this error:

```
ReflectionException:
Property Proxies\__CG__\CA\Core\UserBundle\Entity\User::$email does not exist

  at vendor/symfony/doctrine-bridge/Validator/Constraints/UniqueEntityValidator.php:298
``` 

### How to reproduce

~~Unfortunately I cannot reproduce this issue yet on a smaller app like `symfony-demo`. Still looking into it :confused:~~
See https://github.com/symfony/symfony/issues/57075#issuecomment-2127108177

### Possible Solution

use `PropertyAccessor` to get the value [here](https://github.com/symfony/symfony/blob/46b9158159a1af12dfcd1aa0706fce75cce1c95d/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L300)?

### Additional Context

Downgrading DoctrineBridge and PropertyInfo to 7.0.7 solves the issue for me.

**Comment by dmaicher** [comment]
Ok I managed to reproduce it now on symfony-demo as well. See https://github.com/symfony/demo/compare/main...dmaicher:symfony-demo:reproduce_issue_57075?expand=1

```
$ vendor/bin/simple-phpunit 
PHPUnit 9.6.16 by Sebastian Bergmann and contributors.

Testing 
EEEE...............................................               51 / 51 (100%)

Time: 00:01.626, Memory: 64.50 MB

There were 4 errors:

1) App\Tests\Command\AddUserCommandTest::testCreateUserNonInteractive with data set #0 (false)
ReflectionException: Property Proxies\__CG__\App\Entity\User::$email does not exist
```

**Comment by dmaicher** [comment]
Seems to be caused by https://github.com/symfony/symfony/pull/38662 

ping @wkania

**Comment by dwalczyk** [comment]
same for me

**Comment by dmaicher** [comment]
Added a failing test case here: https://github.com/symfony/symfony/compare/7.2...dmaicher:symfony:issue_57075?expand=1

Will see if I find the time in the next days to take a look at fixing it

**Comment by wkania** [comment]
Good, you found it. I broke untested code.
