### ISSUE TITLE
Slack Notifier: unfurl_links and unfurl_media option are stripped by array_filter when they are set to false

### ISSUE THREAD

**Issue by TomCan** [symfony/symfony#57100]
### Symfony version(s) affected

7.x, 6.x, 5.x

### Description

unfurlLinks and unfurlMedia are boolean values that end up in the $options array. When setting the explicitly to false (to prevent unfurling), they are stripped in the SlackTransport class from the $options array by filter_array, as a boolean false is considdered empty. This results in the key/value not being present in the json that is sent to Slack.  

https://github.com/symfony/symfony/blob/1f90bc30c32b375ed2cdc3234f56d26b8b99cb53/src/Symfony/Component/Notifier/Bridge/Slack/SlackTransport.php#L81  

### How to reproduce

Send a message:
```
    $slack = new Symfony\Component\Notifier\Bridge\Slack\SlackTransport('xoxb-some-token', 'some-channel');
    $opts = new \Symfony\Component\Notifier\Bridge\Slack\SlackOptions(['unfurl_links' => false]);
    $message = new \Symfony\Component\Notifier\Message\ChatMessage('Test message with a link to https://www.github.com/', $opts);
    $slack->send($message);
```
var_dump($options, filter_array($options))
```
array(3) {
  ["unfurl_links"]=>
  bool(false)
  ["channel"]=>
  string(17) "some-channel"
  ["text"]=>
  string(35) "Test message with a link to https://www.github.com/'"
}
array(3) {
  ["channel"]=>
  string(17) "some-channel"
  ["text"]=>
  string(35) "Test message with a link to https://www.github.com/'"
}
```

### Possible Solution

Add custom callback to array_filter function that uses empty(), but explicitly keeps boolean false values

**Comment by TomCan** [comment]
Quick-fix would be
```
    'json' => array_filter($options, function($v){ return $v === false || !empty($v); }),
```
But I assume that this logic is used on other places as well (maybe even other Bridges), and that array_filter without callable might also remove other options (I could imagine there might be cases where you would set a field to a zero int or so).

**Comment by xabbuh** [comment]
Can you confirm that #57109 fixes this?
