### ISSUE TITLE
Missing dependency in "symfony/var-dumper"

### ISSUE THREAD

**Issue by FrankNagel** [symfony/symfony#57194]
### Symfony version(s) affected

7.0.7

### Description

[CliDumper](https://github.com/symfony/symfony/blob/ca995411a09f68ceabb548e9f05f776a64413d27/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L14) uses the ErrorHandler component, which isn't specified as an dependency in [composer.json](https://github.com/symfony/symfony/blob/v7.0.7/src/Symfony/Component/VarDumper/composer.json).

### How to reproduce

-/-

**Comment by nicolas-grekas** [comment]
It is an optional dependency (the class is used only if class_exists returns true), so this is not a *required* dependency.
