### ISSUE TITLE
Rename Symfony\Component\Serializer\Exception\ExceptionInterface to SerializerExceptionInterface

### ISSUE THREAD

**Issue by badmansan** [symfony/symfony#57203]
### Description

There are a lot of ExceptionInterface-s both in Symfony and in other packages. Renaming will allow:
- do not make a mistake with the exception that we catch
- will make it easier to read the code, because it is immediately clear what kind of exception we are catching

### Example

```php
try {
    // ...
} catch (ExceptionInterface $e) {
    // what we are catching?
}
```
instead
```php
try {
    // ...
} catch (SerializerExceptionInterface $e) {
    // now it is immediately clear what we are catching
}
```

**Comment by 94noni** [comment]
namespace is better for that, and you can `use ... as ...;` with a different name
changing this will be huge I think ^^

**Comment by derrabus** [comment]
Indeed, this is a code style issue on your side. Changing the interface name would produce a lot of busy work downstream for little to no gain.

**Comment by xabbuh** [comment]
I agree with @derrabus. Closing therefore, thank you for understanding.
