### ISSUE TITLE
[TypeInfo] Add support for `Uid`

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#57227]
### Description

  Symfony introduced a new `TypeInfo` component.

I wonder if it would be interesting to add support for `Uid` for `TypeInfo` component.

What do you think ?

**Comment by xabbuh** [comment]
Can you elaborate your idea a bit? What do imagine the component to ship around UIDs?

**Comment by seb-jean** [comment]
With support for the `U*id` type, it will then be easier to make a Pull Request for issue https://github.com/symfony/symfony/issues/51618 for example.

**Comment by xabbuh** [comment]
I still fail to see how that is connected. Could you share some concrete code example that you have in mind?

**Comment by MatTheCat** [comment]
Given the linked PRs, I think the feature request is to make the `QueryParameterValueResolver` able to deserialize UIDs?

**Comment by seb-jean** [comment]
I looked now that Symfony 7.1 is released. It's more complicated than I thought...

**Comment by xabbuh** [comment]
Should we close here then?
