### ISSUE TITLE
Cache Adapter PSR-16 ignores namespace in doClear

### ISSUE THREAD

**Issue by agustin-villalba** [symfony/symfony#57244]
### Symfony version(s) affected

7.0.*

### Description

In the Symfony Cache component the Psr16Adapter class, the method `doClear` accepts a `$namespace` as parameter which is never used, and the consequent call to `pool->clear()` removes ALL the keys from the cache, not only those prefixed by the `$namespace`.

### How to reproduce

1. set some keys in the cache store using the prefix 'mine'
2. Call the Psr16Adapter::doClear('mine')

**Comment by alexandre-daubois** [comment]
I'd say this is the normal behavior. Even if some adapter supports a namespace, it is clear, [in the PSR](https://www.php-fig.org/psr/psr-16/), that `clear()` should clear *everything*. From the PHP doc of the method:

> Wipes clean the entire cache's keys.

So I don't think this is a bug, just the PSR not supporting this feature, hence the `namespace` arg not being used.

**Comment by nicolas-grekas** [comment]
@alexandre-daubois is right: if you need per-namespace clearing, you should use another adapter.
