### ISSUE TITLE
AsPeriodicTask attribute : missing timezone parameter

### ISSUE THREAD

**Issue by hugofresnel** [symfony/symfony#57249]
### Description

Considering the following example in the [documentation](https://symfony.com/doc/current/scheduler.html#exploring-alternatives-for-crafting-your-recurring-messages) :
```php
// the frequency can be defined as an integer representing the number of seconds
#[AsPeriodicTask(frequency: 86400)]

// adds randomly up to 6 seconds to the trigger time to avoid load spikes
#[AsPeriodicTask(frequency: '1 day', jitter: 6)]

// defines the method name to call instead as well as the arguments to pass to it
#[AsPeriodicTask(frequency: '1 day', method: 'sendEmail', arguments: ['email' => 'admin@symfony.com'])]
class SendDailySalesReports
{
    public function sendEmail(string $email): void
    {
        // ...
    }
}

// defines the timezone to use
#[AsPeriodicTask(frequency: '1 day', timezone: 'Africa/Malabo')]
```

It looks like we can use a `timezone` parameter on `AsPeriodicTask` attribute to force a given timezone.

However, the attribute [does not implement](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Scheduler/Attribute/AsPeriodicTask.php) this feature (at least not through a `timezone` parameter) :
```php
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
class AsPeriodicTask
{
    /**
     * @param string|int                          $frequency  A string (i.e. "every hour") or an integer (the number of seconds) representing the frequency of the task
     * @param string|null                         $from       A string representing the start time of the periodic task (i.e. "08:00:00")
     * @param string|null                         $until      A string representing the end time of the periodic task (i.e. "20:00:00")
     * @param int|null                            $jitter     The cron jitter, in seconds; for example, if set to 60, the cron
     *                                                        will randomly wait for a number of seconds between 0 and 60 before
     *                                                        executing which allows to avoid load spikes that can happen when many tasks
     *                                                        run at the same time
     * @param array<array-key, mixed>|string|null $arguments  The arguments to pass to the cron task
     * @param string                              $schedule   The name of the schedule responsible for triggering the task
     * @param string|null                         $method     The method to run as the task when the attribute target is a class
     * @param string[]|string|null                $transports One or many transports through which the message scheduling the task will go
     */
    public function __construct(
        public readonly string|int $frequency,
        public readonly ?string $from = null,
        public readonly ?string $until = null,
        public readonly ?int $jitter = null,
        public readonly array|string|null $arguments = null,
        public readonly string $schedule = 'default',
        public readonly ?string $method = null,
        public readonly array|string|null $transports = null,
    ) {
    }
}
```

I think `AsPeriodicTask` attribute should implement this `timezone` parameter like `AsCronTask` attribute does in this example :
```php
// adds randomly up to 6 seconds to the trigger time to avoid load spikes
#[AsCronTask('0 0 * * *', jitter: 6)]

// defines the method name to call instead as well as the arguments to pass to it
#[AsCronTask('0 0 * * *', method: 'sendEmail', arguments: ['email' => 'admin@example.com'])]

// defines the timezone to use
#[AsCronTask('0 0 * * *', timezone: 'Africa/Malabo')]
```
This is [implemented for `AsCronTask`](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Scheduler/Attribute/AsCronTask.php).

**Comment by xabbuh** [comment]
That's a mistake in the documentation. symfony/symfony-docs#19931 will fix it.

**Comment by hugofresnel** [comment]
@xabbuh I'm sorry, but I think this issue should not be closed. Indeed, that's a mistake in the documentation. However, this feature is still missing as it is implemented in `AsCronTask` but not in `AsPeriodicTask`. We don't have the ability to force the timezone like we can with `AsCronTask`.

I think we can consider this issue as a feature request. Let me know if I'm wrong :slightly_smiling_face:

**Comment by xabbuh** [comment]
Here we go:)

**Comment by valtzu** [comment]
If  `#[AsPeriodicTask(frequency: 5, from: '00:00 +02:00')]` already works (didn't test), I'm not sure if theres a need for separate timezone param? 🤔

**Comment by hugofresnel** [comment]
> If `#[AsPeriodicTask(frequency: 5, from: '00:00 +02:00')]` already works (didn't test), I'm not sure if theres a need for separate timezone param? 🤔

Maybe it works but there are 2 problems with this :
1. `+02:00` isn't very explicit : let's say I want to develop an app based in France, then `Europe/Paris` is way more easy to understand. 
2. For example with France, `+02:00` is true only for a part of the year (in summer if I'm not wrong) but it's changing to `+01:00` for another part of the year (in winter). See [source](https://en.wikipedia.org/wiki/Time_in_France).

**Comment by valtzu** [comment]
It was just an example - `from: '00:00 Europe/Paris'` should work too. The string is fed to DateTime constructor.

**Comment by hugofresnel** [comment]
Indeed, it works. My bad.

Closing.
