### ISSUE TITLE
SecurityBundle 7.1: non-existent parameter "container.build_hash"

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/symfony#57257]
### Symfony version(s) affected

7.1.0

### Description

`bin/console cache:clear`

> In DefinitionErrorExceptionPass.php line 48:
>                                                                        
>   You have requested a non-existent parameter "container.build_hash".

### How to reproduce

I've tested v7.1.0-RC1 and this worked perfectly. After updating to v7.1.0 I get this error message.

### Additional Context

https://github.com/symfony/symfony/commit/574f573d4cdf89c232fbfe3e84b6ff1d55dd55f1

**Comment by spackmat** [comment]
I can confirm that, the `LoginThrottlingFactory` tries to use that parameter, even when I don't use the `login_throttling`:

```` php
$container->register($config['limiter'] = 'security.login_throttling.'.$firewallName.'.limiter', DefaultLoginRateLimiter::class)
    ->addArgument(new Reference('limiter.'.$globalId))
    ->addArgument(new Reference('limiter.'.$localId))
    ->addArgument('%container.build_hash%')
;
````

That was introduced 2 weeks ago with https://github.com/symfony/symfony/commit/574f573d4cdf89c232fbfe3e84b6ff1d55dd55f1

**Comment by garak** [comment]
I added this to my services config as a workaround:

```yaml
parameters:
    container.build_hash: '%kernel.secret%'
```

**Comment by xabbuh** [comment]
Can you confirm that #57263 fixes it?

**Comment by spackmat** [comment]
The change in #57263 works for me and fixes the error. 👍

**Comment by garak** [comment]
I can confirm too, the fix is good!
