### ISSUE TITLE
Changing cardinality validation

### ISSUE THREAD

**Issue by skyferix** [symfony/symfony#57259]
### Symfony version(s) affected

5.4.*

### Description

Let's imagine the dependency tree. Below

```
       A
    /      \
B[]         C[]
    \      /
       D
```
      
A is our main validation object. B[],C[] are the collection object validated as nested object used #[Valid] attribute on A object
The B[], C[] has nested dependency object D that is also validate using #[Valid] attribute.
On D we have single property that requires validation.

When building validation. Only one validation error is printed:
A.B[n].E.propertyPath
A.C[n].E.propertyPath

I have managed to solve this problem by writing custom constraint and putting them on B, and C objects. In that case all errors are printed.

### How to reproduce

```
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;

class A 
{
   #[Assert\Valid()
   private Collection $bCollection;

   #[Assert\Valid()
   private Collection $cCollection;
}

class B
{
   #[Assert\Valid()
   private D $d;
}

class C
{
   #[Assert\Valid()
   private D $d;
}

class D
{
   #[Assert\NotBlank()
   private ?string $exampleProperty;
}
```

Add single value to both collection with D object that hold invalid value.
I expect the result to be 2 violationPaths added to list.

Validate the top level object A (I am not setting the setters and getters, I just want to give you general idea about the structure where I spotted the problem)

**Comment by xabbuh** [comment]
This is by design. The validator remembers which constraint it already looked at to not evaluate it more than once. Given that we won't change that and you also find a workaround for your particular problem I am going to close here. Thank you for understanding.
