### ISSUE TITLE
Call to undefined method Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor::getWriteInfo()

### ISSUE THREAD

**Issue by LeikoDmitry** [symfony/symfony#57250]
### Symfony version(s) affected

7.0

### Description

I've updated symfony version from 6.4 to 7.0 and and run the tests via ```codeception``` getting the error below:

```Call to undefined method Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor::getWriteInfo()```

### How to reproduce

Upgrade symfony

**Comment by wouterj** [comment]
Hi! 

This method indeed is not defined, but that also [was the case in 6.4](https://github.com/symfony/symfony/blob/6.4/src%2FSymfony%2FComponent%2FPropertyInfo%2FPropertyInfoExtractor.php). Please find out who is calling this method and report the issue to that library instead.

**Comment by xabbuh** [comment]
This looks to be the same as #54787 which was fixed in #54804 and will be part of the next round of patch releases.
