### ISSUE TITLE
Error in Symfony Rate Limiter Component "You have requested a non-existent parameter "container.build_hash"

### ISSUE THREAD

**Issue by Hanhan1989** [symfony/symfony#57266]
### Symfony version(s) affected

7.1.0

### Description

"I've had an issue with the update involving the Symfony rate limiter component, and the error message is 'You have requested a non-existent parameter "container.build_hash"'. When running bin/console c:c, this error appears.

### How to reproduce

Add the following lines in security.yml file
```
            login_throttling:
                max_attempts: 3
                interval: 60 minutes
```
next execute bin/console c:c

**Comment by xabbuh** [comment]
see #57257, this has been fixed in #57263 and will be part of the first 7.1 bugfix release
