### ISSUE TITLE
IsGranted in nested object

### ISSUE THREAD

**Issue by devbysb** [symfony/symfony#57265]
### Description

Hi,

Is it possible to add the possibility to use nested object on IsGranted attribute ?

like this

`#[IsGranted(SomeVoter::CAN_DO_THIS, subject: 'objet.nested')]`

this will avoid adding unused parameters in the function and in the route

### Example

`#[IsGranted(SomeVoter::CAN_DO_THIS, subject: 'objet.nested')]`

**Comment by devbysb** [comment]
or object->nested for example

**Comment by eltharin** [comment]
you can try 
``
#[IsGranted(SomeVoter::CAN_DO_THIS, subject: new Expression('args["objet"].getNested()'))]
``

**Comment by stof** [comment]
@eltharin is right. This case is supported by using the ExpressionLanguage by passing an Expression object.
