### ISSUE TITLE
Issue with "symfony/serializer" component on a clean Symfony installation

### ISSUE THREAD

**Issue by alessandro-amos** [symfony/symfony#57294]
### Symfony version(s) affected

7.1, 7.0, 6.4

### Description

I have encountered an issue with the "symfony/serializer" component on a clean Symfony installation. After installing the component via Composer, an error is generated when clearing the cache. The error message is "You have requested a non-existent service "serializer.normalizer.object"."  

Interestingly, this error does not occur when the "symfony/security-bundle" package is installed.  

I am currently working on WSL with Ubuntu and Docker php:8.2-fpm.

### How to reproduce

I just installed Symfony using Composer and then the serializer component:

`composer create-project symfony/skeleton:"7.1.*" my_project_directory`

Followed by:

`composer require symfony/serializer`

### Additional Context

![image](https://github.com/symfony/symfony/assets/130871434/8dcf757b-c80d-4534-949f-d5a628aaaba7)

**Comment by xabbuh** [comment]
see #57297
