### ISSUE TITLE
[AssetMapper] Page specific javascript not working properly

### ISSUE THREAD

**Issue by filthyfane** [symfony/symfony#57330]
### Symfony version(s) affected

7.0.*

### Description

I have created a simple landing page that loads a Leaflet map.
The javascript code is loaded according to the documentation [here](https://symfony.com/doc/current/frontend/asset_mapper.html#page-specific-css-javascript):
`````
{% block importmap %}
    {{ importmap(['app', 'home']) }}
{% endblock %}
`````
where home contains the custom js code and is included in the importmap.php file as an entrypoint:

`````
'home' => [
        'path' => './assets/scripts/home/home.js',
        'entrypoint' => true,
    ],
`````

On the same page there are two links 
`````
<a href="/">HOME</a>
<a href="{{ path('list_hikes') }}">LIST DATA</a>
`````

when switching between pages everything works as expected. but if you click on the same link twice (for example on the HOME one) the map is not loading. And weird thing, a console log added in the body tag gets triggered twice.

![image](https://github.com/symfony/symfony/assets/39158522/b2efb3be-a595-4b1b-a9c4-f4375e6ccb84)

Is this the right behavior? 

### How to reproduce

`````
<body>
    <div class="container mx-auto">
        <script>
            console.log('test');
        </script>
        <a href="/">HOME</a>
        <a href="{{ path('list_hikes') }}">LIST DATA</a>
        <div class="flex flex-row flex-wrap py-4">
            <main role="main" class="w-auto grow items-start flex flex-row pt-1 px-2">
                {% block body %}{% endblock %}
            </main>
        </div>
    </div>
</body>
 `````

**Comment by smnandre** [comment]
This seems to me related to Turbo .. scripts should be in head, and they are not re-run if you do not change page.

**Comment by filthyfane** [comment]
Yes, you are right!
This is exactly what it's described in this video https://symfonycasts.com/screencast/turbo/javascript#play and you can find some solutions there, in case someone else is facing the same situation.
Thank you for putting me on the right track. I couldn't relate it to Turbo. Maybe it worth mentioning some kind of note in the documentation about this since Turbo is installed with Symfony.
