### ISSUE TITLE
[Finder] ignoreVCSIgnored not working as it should

### ISSUE THREAD

**Issue by par274** [symfony/symfony#57335]
### Symfony version(s) affected

7.1

### Description

Today I updated the Symfony/Finder component version in my project and noticed that the ignoreVCSIgnored function is not working as it should.

The problem is exactly this: it does not see the .gitignore file in the directory. So the function does not perform.

I found the solution, but since the solution contains a chunk of code that hasn't been updated, I don't know how effective it is.

### How to reproduce

The old code solves the problem.

### Possible Solution

Iterator\VcsIgnoredFilterIterator.php on line 40.

```php
foreach ([$this->baseDir, ...$this->parentDirectoriesUpwards($this->baseDir)] as $directory) {
            if (@is_dir("{$directory}/.git")) {
                $this->baseDir = $directory;
                break;
            }
        }
```

The old code removes the problem.

```php
foreach ($this->parentDirectoriesUpwards($this->baseDir) as $parentDirectory) {
            if (@is_dir("{$parentDirectory}/.git")) {
                $this->baseDir = $parentDirectory;
                break;
            }
        }
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by par274** [comment]
> Can you create a small example application that allows to reproduce your issue?

Will the patch file I created in my own project work for you?

https://github.com/mentionbb/mentionbb/blob/master/src/patches/symfony-finder-iterator-vcsignoredfilteriterator-php.patch

Or should I edit it myself and create a Pull Request?

**Comment by xabbuh** [comment]
If you create a pull request with the patch that you propose, we will additionally need a test that would fail without your patch to see if that really fixes the root cause.

**Comment by xabbuh** [comment]
I am closing here for now as we need more information to fix the reported issue. But we can consider to reopen once we are able to reproduce.
