### ISSUE TITLE
[Notifier] Use new Emoji Component

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#57351]
### Description

New Emoji component has recently been released.

Would there be any benefit in using shortcodes instead of the emoji directly for Notifier component?

So instead of putting this:
https://github.com/symfony/symfony/blob/63ef48feebf73484e5c9321fc9bf3fd3de787d6a/src/Symfony/Component/Notifier/Notification/Notification.php#L190-L193

Put this:

```php
self::IMPORTANCE_URGENT => ':cloud-lightning:',
self::IMPORTANCE_HIGH => 'cloud-rain',
self::IMPORTANCE_MEDIUM => ':sun-behind-rain-cloud:',
default => ':partly-sunny:',
```

And instead of putting this:
https://github.com/symfony/symfony/blob/63ef48feebf73484e5c9321fc9bf3fd3de787d6a/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/notifier.html.twig#L140

will become:

```twig
 {{- 'Emoji: ' ~ (notification.getEmoji() is empty ? '(empty)' : notification.getEmoji()|emojify) }}<br/> 
```

What do you think ?

**Comment by smnandre** [comment]
I'm not sure to follow.. the result would be the same right ?

**Comment by seb-jean** [comment]
Yes, the result would be the same. But is it better to use shortcode than directly emoji in the code? Is this a good practice? Or is it useless and we leave the emoji in the code?

**Comment by smnandre** [comment]
In my mind I really don't see why we would need some _back and forth_ with a library to... get the exact same data in the end 😅 

But instead using the Emoji component here would require multiple composer packages and a ....  _certain amount_ of emoji names translated in every possible variant ... 

---

Regarding "good practices" i have no idea, but.. I let you guess this comparaison before clicking on the results ;) 

```
<?php

echo mb_strlen('🐘') . PHP_EOL;
echo strlen('🐘') . PHP_EOL;
echo PHP_EOL;

echo mb_strlen(':elephant:') . PHP_EOL;
echo strlen(':elephant:') . PHP_EOL;
echo PHP_EOL;

```
Results: https://3v4l.org/dk4RV#v8.3.8

(note: i post this comparaison just for fun... IRL this difference makes in fact no impact here. and i don't mean "very few" i really mean "no")

**Comment by smnandre** [comment]
I checked by curiosity: these emojis are here since the component introduction

https://github.com/symfony/symfony/blob/7f97a3f11fcbe48cd6b9561e37023ba610fab21b/src/Symfony/Component/Notifier/Notification/Notification.php#L166

**Comment by ro0NL** [comment]
i think working with the UTF symbol directly is generally more logical, but you can use Emoji component already as an implementation detail for getDefaultEmoji

or maybe it should be a hybrid solution

**Comment by stof** [comment]
Changing the constant to use shortcodes would introduce a hard dependency on the symfony/emoji component, which is the biggest Symfony component (due to the data necessary to transliterate emojis to every locale). this is a total no-go.
It has only drawbacks compared to use the emoji string directly (which is what needs to be used in the end anyway).

this gets a big -1 vote from me, with no chance to make me change my vote.

**Comment by fabpot** [comment]
Closing for the reasons explained by @stof
