### ISSUE TITLE
BC Break when serializing an entity with an empty array in serializer_groups

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#57350]
### Symfony version(s) affected

7.1

### Description

I believe a BC Break has been introduced in #51514.

In Symfony <= 7.0, providing an empty array in `serializer_groups` returned "nothing".

In Symfony 7.1, the same `serializer_groups` returns all the properties of the object (the groups are ignored and is similar to providing `*`)

### How to reproduce

```php
$groups = [];
if ($isOwner) {
   $groups[] = 'OWNER'
}
if ($isAdmin) {
   $groups[] = 'ADMIN'
}

$propertyNameCollectionFactory = $this->container->get(ApiPlatform\Metadata\Property\Factory\PropertyNameCollectionFactoryInterface::clas);

dump($propertyNameCollectionFactory->create(MyObject::class, ['serializer_groups' => $groups]));
```

### Possible Solution

I believe the fix is to `return []` when `!$groupsHasBeenDefined`
in https://github.com/symfony/symfony/pull/51514/files#diff-8183be74478a13fcda2e17124d559a29013d10f119805a6623a8a396edb70c76R42

My workaround is to use:

```
$groups = ['DOES_NOT_USE_THIS_GROUP'];
if ($isOwner) {
   $groups[] = 'OWNER'
}
if ($isAdmin) {
   $groups[] = 'ADMIN'
}
```

**Comment by xabbuh** [comment]
Maybe related to #56875? Does the fix proposed for that one help here too?

**Comment by jderusse** [comment]
> Maybe related to #56875? Does the fix proposed for that one help here too?

This is not related.

Here is **simplified** change in the implementation: (I removed the logic about `isIgnored` and `wildcard` groups)

https://github.com/symfony/symfony/pull/51514/files#diff-8183be74478a13fcda2e17124d559a29013d10f119805a6623a8a396edb70c76R48

```
foreach ($properties as $property) {
  if (null === $groups || array_intersect($groups, $property->getGroups())) {
    yield $property;
  }
}
```

> note: `array_intersect([], $property->getGroups())` returns nothing, that's why in previous implementation the list of properties was empty when the groups was `[]`.

new implementation

```
$groups ??= [];
$groupsHasBeenDefined = [] !== $groups;

foreach ($properties as $property) {
  if (!$groupsHasBeenDefined || array_intersect($groups, $property->getGroups())) {
    yield $property;
  }
}
```

So all properties are included:
- before: When `groups` is null
- after: When `groups` is an empty `[]` (null is converted to `[]`)

I can open a PR, I was just wondering if the initial behavior was expected or a bug

**Comment by xabbuh** [comment]
> I can open a PR, I was just wondering if the initial behavior was expected or a bug

I am not sure. I suggest opening a PR, adding some tests and start the discussion on that base.

**Comment by Seldaek** [comment]
Related issue https://github.com/symfony/symfony/issues/58576

And some other issue I have experienced which may be related or not, I am not sure: When serializing with group `['read']` for example, we now get properties with a `#[Groups(['Default'])]` also returned after upgrading to 7.1.

So it seems to always include the Default group now, even if you pass a group, not quite the same root cause as OP perhaps but the effect is similar. Tagging @mtarld here too as he did the change.
