### ISSUE TITLE
MailerInterface is not working

### ISSUE THREAD

**Issue by harrydeboer** [symfony/symfony#57361]
### Symfony version(s) affected

7.0.8

### Description

I am sending mail using the MailerInterface. Sending mail gives no error but the mail is not delivered. When I am using the Mailer and Transport classes directly the mail is delivered. This behavior exists since I use Symfony 7.

### How to reproduce

.env.local
MAILER_DSN=smtp://USERNAME:APP_PASSWORD@smtp.example.com:000

`use Symfony\Component\Mailer\MailerInterface;`

`public function __construct(
private readonly MailerInterface $mailer,
) {
}`

`               $email = (new Email())
                    ->from(new Address('postmaster@example.com', strip_tags($form->get('name')->getData())))
                    ->replyTo($form->get('email')->getData())
                    ->to('info@example.com')
                    ->subject(strip_tags($form->get('subject')->getData()))
                    ->html($form->get('message')->getData());`

`$this->mailer->send($email);`

The send method of mailer gives no exception but the mail is not delivered.

### Possible Solution

When I explicitly set the transport to the mailer it mails correctly:

`use Symfony\Component\Mailer\Mailer;`
`use Symfony\Component\Mailer\Transport;`

                $transport = Transport::fromDsn($this->getParameter('mailer_dsn'));
                $mailer = new Mailer($transport);

`                $email = (new Email())
                    ->from(new Address('postmaster@example.com', strip_tags($form->get('name')->getData())))
                    ->replyTo($form->get('email')->getData())
                    ->to('info@example.com')
                    ->subject(strip_tags($form->get('subject')->getData()))
                    ->html($form->get('message')->getData());`

`$mailer->send($email);`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?
