### ISSUE TITLE
Unable to get ClockAwareTrait to inject the clock

### ISSUE THREAD

**Issue by toby-griffiths** [symfony/symfony#57383]
### Symfony version(s) affected

6.0.14

### Description

I've followed the Clock component instructions & added the  `ClockAwareTrait` to my service, however I'm now seeing the error…

```
!!    Cannot autowire service "App\Messenger\Command\Ticketing\LogTicketNumbersCo
!!    mmandHandler": argument "$clock" of method "setClock()" references interfac
!!    e "Psr\Clock\ClockInterface" but no such service exists. Did you create a c
!!    lass that implements this interface?
```

I appreciate that this is an old verson of Symfony, but I've installed `v7.1.1`, and am getting this error.

### How to reproduce

I'm not sure how to reproduce, but if someone can point me in the direction of the compiler pass, or other code that should be preparing the `Psr\Clock\ClockInterface` service, then I'm hoping I can work out what's up with this?

**Comment by alexandre-daubois** [comment]
Can you provide the minimal project to reproduce in a repo that we can clone please? I created a project from scratch, required the component and all went fine 🤔

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
