### ISSUE TITLE
Unsure about the similar locale selection

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#57386]
### Symfony version(s) affected

7.1.*

### Description

https://github.com/symfony/symfony/pull/52986 changed the way, the `Accept-Language` header is interpreted.
However, I'm not sure the exact match is always what you want.

Given I have the locales `['de', 'en']` available and I send `Accept-Language: de-de, en`, I would now get `en` as the result because `en` is an exact match. Previously it was `de` which imho was the better choice. Any German dialect would be better than English in this case. Even if I'd adjust factor weighting `Accept-Language: de-de,en;q=0.9`, Symfony would still pick `en`.

Are we sure this is the desired behavior?

/cc @Spomky 

### How to reproduce

The test in `RequestTest::providePreferredLanguage()` would be this:
```php
yield '"de" is selected as "de-de" is a better choice than "en"' => ['de', 'de-de, en', ['de', 'en']];
```

**Comment by Spomky** [comment]
Hi 👋,

> https://github.com/symfony/symfony/pull/52986 changed the way, the Accept-Language header is interpreted.
However, I'm not sure the exact match is always what you want.

With the input `Accept-Language: de-de, en` and the supported locales `['de', 'en']`, `en` is selected as it is an exact match. I may be wrong, but there should be no differences between 7.1+ and the previous versions.
In any cases and to be in line with [RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-14.4), I will propose a fix if it is not the case.

> A language-range matches a language-tag if it exactly equals the tag, or if it exactly equals a prefix of the tag

**Comment by Toflar** [comment]
I agree with https://github.com/symfony/symfony/pull/57388#issuecomment-2165587910 - thus I'm closing. Thanks for investigating, though @Spomky ❤️
