### ISSUE TITLE
[Uid] isValid fails when passing non Rfc4122 IDs

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#57398]
### Symfony version(s) affected

7.1.1

### Description

When trying to validate UUIDs in a format that's not Rfc4122 it'll always fail.

### How to reproduce

```php
Uuid::isValid("1CCD2w4mK2m455S2BAXFht"); //should be true since it's a valid UUIDv7 in base58 format.
```

### Possible Solution

The `isValid` seems to contain a regex that checks for the Rfc4122 structure, probably should be expanded to check the other representations as well.

**Comment by derrabus** [comment]
I understand that you _want_ to validate UIDs in representations other than RFC 4122, but the fact that the `isValid()` does not support your favorite representation (yet?) is certainly not a bug.

**Comment by KDederichs** [comment]
well depends on how you look at it, since it's not saying it has to be RFC 4122 anywhere but yeah, if you look at it like that it's a feature request to extend `isValid` to work with all the supported representations

**Comment by kaznovac** [comment]
related: #51540
