### ISSUE TITLE
[Container] cache:warmup failed to produce route cache, cache:clear works

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#57429]
### Symfony version(s) affected

7.1.1

### Description

While upgrading from 7.0 to 7.1, my app started saying no routes exist.

I was doing

```Dockerfile
RUN bin/console cache:warmup --no-interaction -vvv
```

in my Dockerfile, cache folder doesn't exist before the command runs.

### How to reproduce

```
rm -rf var/cache
bin/console cache:warmup --no-interaction -vvv
ls var/cache/prod/url_* # no files
```

### Possible Solution

Have warmup behave exactly like clear would if it's running without a prior cache being present.

Alternatively, if this is impossible, have warmup throw it if notices there's no prior cache present because this is way too subtle of a change.

### Additional Context

#53450 intended to fix this, but was closed.

**Comment by umulmrum** [comment]
This is especially dangerous when deploying to a readonly file system (e.g. AWS Lambda), as the router will try to generate the file on-demand but fails to write then. Currently this keeps me from upgrading to 7.1.

**Comment by dkarlovi** [comment]
@umulmrum this is exactly why I've noticed this, but as noted, `cache:clear` works correctly for me, try that.

**Comment by umulmrum** [comment]
`cache:warmup` works again for me since 7.1.2 - thanks for fixing :slightly_smiling_face:

**Comment by dkarlovi** [comment]
@umulmrum weird nobody tagged this issue but it still got fixed. :)

@xabbuh do you know which PR fixed it by any chance?

**Comment by xabbuh** [comment]
#57554 should be the fix. I missed that it wasn’t already linked when closing this issue.
