### ISSUE TITLE
[security] The "AccessDecisionManager" always abstains when passing a `class-string` instead of an `object` to a `CacheableVoterInterface`

### ISSUE THREAD

**Issue by yakobe** [symfony/symfony#57454]
### Symfony version(s) affected

7.1

### Description

If we pass a class constant to `is_granted` then the [CacheableVoterInterface::supportsType](https://github.com/symfony/symfony/blob/c0e30bb06bb4c12efc8bad13f7cb732954cb0182/src/Symfony/Component/Security/Core/Authorization/Voter/CacheableVoterInterface.php#L29) method will receive the string `"string"` instead of the class string.

This causes the access decision manager to cache "false" and **always** abstain instead of voting. This is because the `supportsType` method usually do something like this:

```php
    public function supportsType(string $subjectType): bool
    {
        return is_a($subjectType, Choice::class, true);
    }
```

### How to reproduce

Create a cacheable voter like this:

```php
use Symfony\Component\Security\Core\Authorization\Voter\Voter;

class MyClassVoter extends Voter
{
    public function supportsAttribute(string $attribute): bool
    {
        return 'write' === $attribute;
    }

    public function supportsType(string $subjectType): bool
    {
        return is_a($subjectType, MyClass::class, true);
    }

    protected function supports(string $attribute, mixed $subject): bool
    {
		// we can just return true here because we do all the checks in `supportsType` and `supportsAttribute`
        return true;
    }

    protected function voteOnAttribute(string $attribute, mixed $subject, TokenInterface $token): bool
    {
		$decision = // some security checks. eg the user is an admin and in a certain user-group etc
        return  $decision;
    }
}

```

then call isGranted on with the class constant

```php
$this->container->get('security.authorization_checker')->isGranted('write', MyClass::class)
```

### Result
The voter will never be called because `supportsType` receives `"string"` instead of `"\MyNamespace\MyClass"` and therefore returns false.

### Possible Solution

The problems arises because we do not have an `object` on the following line of the `AccessDecisionManager`:

https://github.com/symfony/symfony/blob/c0e30bb06bb4c12efc8bad13f7cb732954cb0182/src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php#L89

Perhaps a simple check to see if the class exists would help. Something like: 

```php
$keyObject = \is_object($object) ? $object::class : 
                       (class_exists($object) ? $object : get_debug_type($object));

```

### Additional Context

Perhaps I am doing something wrong with the voters and the `$subject` should **always** be an `object` and not a class string. However, using a class string has been useful for scenarios where we dont have an `object` yet. For example, if you want to add some complex logic to work out if a user can create certain classes. You could create the class first and then check on that, but it is not always possible (eg in controller attributes etc).

I would be happy to contribute a fix if desired. I created this bug to verify if/how it needs fixing first.

**Comment by stof** [comment]
a string `Foo` is still a string. It is not a value of the type `Foo`.

If you want to vote on a string, your voter has to says that it supports the string type as a type of subject.

**Comment by yakobe** [comment]
@stof Yes that's possible. But it's a bit misleading and would lose a good opportunity for caching. It would also mean that the supportsType method would have to return true for all strings, and make it useless since it would then match every object. 

Why not use the class string the same way it is used for objects? It is safer and more flexible. 

Or maybe a better question: why not support it if it is safer and improves caching? What down side would the change bring?

**Comment by stof** [comment]
@yakobe to me, this is making things a lot worse (and inconsistent with the similar APIs in the serializer component). `supportsType` is about determining whether your voter supports a given **type**. Your change means that the argument passed to that method is sometimes a type and sometimes the subject itself (making the API a lots more confusing).

Thus, I suspect that your patch actually makes things slower: when a string value is passed, you trigger the autoloader to check whether it is an existing class (not counting the fact that your code is broken if the value is a different kind of value than a string), which will likely slow down the cache lookup for any string value which is not a class name.
And it is also a BC break for any project that properly implement support for strings by understanding what their type is (or just reading the phpdoc of the interface, which explains what is passed there).
And your change also makes it impossible to properly cache the very common case where the voter does **not** support voting on a class name string but only on object instances.

**Comment by yakobe** [comment]
@stof They are good points. Like I say, I'm just trying to understand the right way to approach this with the voters. 

I even considered that maybe the subject should always be an object, and never a class string. But that would mean we always have to instantiate an object first to vote on it, which might not always be possible. Is it the recommended use for voters tho?

If we are meant to allow voting based on class strings then how would we cache for that?

Also, what is the use case for a "string" subject that is not a class string? I guess you could do `isGranted("write", "a nice string")` but I can't think of a use case. However, maybe I just haven't been exposed to those use cases ☺️. 

Ps: thank you for having discussion with me. Maybe a different solution is needed, but it helps to consider options.

**Comment by stof** [comment]
@yakobe for the case of creating new objects, I generate have a dedicated _attribute_ that I vote on, and my subject is either a parent object (for instance voting for `CREATE_COMMENT` with a subject being `$blogPost`) when I have a relevant parent for the object being created, or `null` otherwise.

**Comment by yakobe** [comment]
@stof interesting idea! I have been using generic attributes like "read" "write" etc and using the class string to identify it. I guess using a dedicated attribute like "CREATE_COMMENT" could solve it, and even make the caching faster since it will be excluded very quickly for other votes. 

Would you do that for other attributes too to keep consistency? Eg "UPDATE_COMMENT" and the object if you have one and null otherwise just to check "can the user update comments in general"?

Just out of interest, do you have an example for a string subject? Like I wrote in my previous comment, I can't think of one? If there isn't one it still might be ok to make the change I proposed so that people like me don't have a problem.

**Comment by stof** [comment]
I'm voting on `->isGranted('EDIT', $comment)` (or indeed `null` when there is no associated object, but for an `EDIT` action, this would be unlikely as we edit _something_). I do have voters voting on `null` for things like `LIST_DRAFT_POSTS` for instance.

In 13 years using the Symfony security component, I never implemented a single voter voting on something else than an object or null (btw, older versions of Symfony had a documented contract of `object|null` for that argument).

> If there isn't one it still might be ok to make the change I proposed so that people like me don't have a problem.

Your change still has all the drawbacks I listed above.
note that the biggest one is that it is actually a BC break, as it means that such change is forbidden in our process.

**Comment by yakobe** [comment]
Ok. What do you mean by this:

> And it is also a BC break for any project that properly implement support for strings by understanding what their type is (or just reading the phpdoc of the interface, which explains what is passed there).

Especially the part about reading the phpdoc of the interface. 

If i can understand all the best practices then perhaps I can help contribute some of them to the docs to help people avoid the pitfalls I'm experiencing 😅

**Comment by stof** [comment]
Any project that has implemented `supportsType` as `return $subjectType === 'string';` would break if we do the suggested change. That's why this change is breaking backward compatibility and cannot be accepted.

**Comment by yakobe** [comment]
Ah, I think I understand now; You meant that it would work differently to what is written in the [phpdoc of the CacheableVoterInterface](https://github.com/symfony/symfony/blob/c0e30bb06bb4c12efc8bad13f7cb732954cb0182/src/Symfony/Component/Security/Core/Authorization/Voter/CacheableVoterInterface.php#L27). 

I'm not sure i agree about the BC break since it would check if it can resolve to a class string and then give `string` anyway. The only possibility would be if someone used a class string and **really really** wants to cache the type by string, which sounds improbable. I agree, tho, that it would be a performance hit. Albeit only for voters that want to vote on a `string` attribute... which you say you should not probably do (and, as you say,`subject` used to even be `object|null`). The doc comment could also be changed to accommodate it. But hey... 🤷 It sounds like our use case is not best practice, and perhaps we should reorganise the voters no not use class strings as a subject.

Perhaps it would be good to document such things. The symfony documentation is really good, but it is very lacking when it comes to the voting system. There are not many best practices or information about to structure them efficiently and safely.
Searching online seems to just bring more people asking what the best practices are. How to vote on "create" seems omitted very often, and to be something that i see lots of people confused about.

What do you say about opening a github discussion to collect best practices; things that are advisable and things that are not. Where to keep `attributes`, what are good `subjects`, how granular should they be, etc etc? If the discussion brings some agreed best practices then perhaps we can add them to the docs?

**Comment by stof** [comment]
@yakobe but if it can resolve to a class string, it changes the behavior of the **existing** code, calling different voters. This is **exactly** the definition of a BC break.

**Comment by yakobe** [comment]
Whether it is "technically a BC break" is only relevant if it actually affects people and the use case is actually desired. 

However... 

I already conceded and said that it might not be the most logical change and there may be better ways to handle this. I will close this issue but, before I do (to avoid comments on a closed issue), I would just like to try to get a resolution that will help people like me.... The questions have moved on to best practices and documentation.

>Perhaps it would be good to document such things. The symfony documentation is really good, but it is very lacking when it comes to the voting system. There are not many best practices or information about to structure them efficiently and safely.
Searching online seems to just bring more people asking what the best practices are. How to vote on "create" seems omitted very often, and to be something that i see lots of people confused about.
>
>What do you say about opening a github discussion to collect best practices; things that are advisable and things that are not. Where to keep attributes, what are good subjects, how granular should they be, etc etc? If the discussion brings some agreed best practices then perhaps we can add them to the docs?

**Comment by stof** [comment]
As Symfony has no way to inspect 100% of the (private) codebases using it before doing a change, we cannot know whether a change will affect people by checking whether that case is used.
this is precisely the reason for our strict backward compatibility policy.

**Comment by yakobe** [comment]
You can let go of the BC break 😄. Yes, it is "technically" one. No, I disagree it is relevant (people do not have to agree on everything). Most importantly... I already conceded that the change is probably not the best. So I am agreeing with you there. 👍 

Can we please discuss the other points? 😄

**Comment by stof** [comment]
To suggest documentation improvements, I suggest you to open an issue in https://github.com/symfony/symfony-docs/issues instead, so that this is discussed with the documentation team (which might not read this issue at all)

**Comment by yakobe** [comment]
Ok. I will try to raise something there.
