### ISSUE TITLE
HTTP Cache preventing 304 response code with Etag

### ISSUE THREAD

**Issue by nguyenk** [symfony/symfony#57452]
### Symfony version(s) affected

5.4.36

### Description

Hello Folks,

I'm Running into troubles using HTTP Cache + Etags.

After digging for a while, I understand that HTTP Cache is returning the cached entry with 200 HTTP code instead of 304 response.

Therefore, my front end keeps asking for the resource from the Backend. Of course it's serving from the cache, but still this is generating some load.

### How to reproduce

# config/packages/framework.yaml
```yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    # ...
    http_cache: true
```

# MyController.php
```php
    #[Route('/some-route', methods: ['GET'])]
    public function ping(Request $request): JsonResponse
    {
        $response = new Response();
        $response->setEtag("v1");
        $response->setPublic();
        if (! $response->isNotModified($request)) {
            return (new JsonResponse('To be cached'))->setEtag("v1");
        }

        return $response;
    }
```

  * First request returns a 200
  * Second request returns a 200, while I'm expecting a 304
  
From what I understand, `Symfony\Component\HttpKernel\HttpCache\HttpCache` is stripping the `If-None-Match` header, which makes `Response::isNotModified()` not able to  return 304.

Does it mean, that Etag and HTTPCache are not compatible ?

Any explenation / help would be much appreciated !

**Comment by smnandre** [comment]
I believe you forgot to call `->setPublic()`

```diff
   #[Route('/some-route', methods: ['GET'])]
    public function ping(Request $request): JsonResponse
    {
        $response = new Response();
        $response->setEtag("v1");
        $response->setPublic();
        if (! $response->isNotModified($request)) {
-            return (new JsonResponse('To be cached'))->setEtag("v1");
+            return (new JsonResponse('To be cached'))->setPublic()->setEtag('v1');
        }

        return $response;
    }
```

With, i get a 304 as expected

**Comment by nguyenk** [comment]
Hello @smnandre. Thank you for a such quick response.

In fact it turns out Google Chrome dev tools was misleading me. Indeed, for unknown reason, chrome is showing the original 200 return http code whereas Firefox or `curl --head` are displaying 304.

Sorry for the mistake. 

Have a nice day.
