### ISSUE TITLE
Composer installation of symfony/property-access not possible

### ISSUE THREAD

**Issue by ntzrbtr** [symfony/symfony#57471]
### Symfony version(s) affected

7.0.0

### Description

When trying to install/update symfony/property-access, I get the following error message:

```
curl error 3 while downloading https://repo.packagist.org/p2/symfony/property-access
  .json: URL using bad/illegal format or missing URL
```

### How to reproduce

In a repo that uses symfony/property-access, call `composer update --dry-run`

**Comment by derrabus** [comment]
Please report this to Composer, please.
