### ISSUE TITLE
Neither the property "hasXdebugInfo"exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector".

### ISSUE THREAD

**Issue by cbfoodomarket** [symfony/symfony#57477]
### Symfony version(s) affected

5.2

### Description

After upgrading from PHP 8.1 to PHP 8.2, the profiler doesn't work anymore and I get this issue => 

`Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "hasXdebugInfo" nor one of the methods "hasXdebugInfo()", "gethasXdebugInfo()"/"ishasXdebugInfo()"/"hashasXdebugInfo()" or "__call()" exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector"." at /var/www/applications/mainstack/vendor/symfony/web-profiler-bundle/Resources/views/Collector/config.html.twig line 67`

### How to reproduce

go to home page in dev environnement with profiler true

**Comment by xabbuh** [comment]
Symfony 5.2 is not maintained anymore. Do you experience the same on 5.4? If so, please create a small example application that allows to reproduce it.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
