### ISSUE TITLE
[Validator][RFC] Unique Constraint could have a `errorPath` parameter

### ISSUE THREAD

**Issue by Crovitche-1623** [symfony/symfony#57503]
### Description

It could be a great improvement if the `Unique` Constraint could take a `errorPath` parameter (like the `UniqueEntity` constraint) pointing to the field that is a duplicate. This will be even more relevant [if this PR is merged](https://github.com/symfony/symfony/pull/47714).

### Example

Using the example provided in the documentation:
```php
<?php
// src/Entity/PointOfInterest.php
namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class PointOfInterest
{
    #[Assert\Unique(fields: ['latitude', 'longitude'], errorPath: 'latitude')]
    protected array $coordinates;
}
```

**Comment by norkunas** [comment]
Like https://github.com/symfony/symfony/pull/57436 ? :)

**Comment by Crovitche-1623** [comment]
@norkunas Yes exactly. Thank you for your work, I didn't see your PR.
