### ISSUE TITLE
[Messenger] Add  the `#[AsMessage]` attribute

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#57506]
### Description

Proposition is to add a new `#[AsMessage]` attribute for messenger messages, which could serve many purposes.

## Simple use case

First one here: replace the `framework.messenger.routing` section in configuration allowing the user to directly set the targetted transport on classes.

```php
namespace App\Message;

use Symfony\Component\Messenger\Attribute\AsMessage;

#[AsMessage(transport: 'async')]
#[AsMessage(transport: 'other')]
#[AsMessage(transport: ['foo', 'bar'])]
class AddProduct
{
}
```

Easy one, using a bit of reflection to read the attribute in the `Symfony\Component\Messenger\Transport\Sender\SendersLocator` class is enough.

Note: I also researched a way to put this introspection inside a middle, but routing seem to happen prior to that.

@stof mentionned that messages are not services in https://github.com/symfony/symfony/issues/33912#issuecomment-2182899547 which makes the attribute non parseable during container compilation, in this use case, that's not a problem since we can read it at runtime in the senders locator.

I think that in order to allow user to override hardcoded attributes, the `framework.messenger.routing` project configuration must override `#[AsMessage]` the attribute: this also solves some testing related use cases as mentioned by @rela589n in https://github.com/symfony/symfony/issues/33912#issuecomment-2183951706

## More complex use cases

It was mentionned in the same issue the need be able to alias messages, for example: `App\Message\AddProduct` -> `add_product`:

```php
namespace App\Message;

use Symfony\Component\Messenger\Attribute\AsMessage;

// Names are here for the sake of example
#[AsMessage(alias: 'add_product', legacy_aliases: ['backward_compat_add_product'])]
class AddProduct
{
}
```

For this to work and in order to be able to map from an alias to a PHP class name, it is required that names are registered prior runtime, hence during container compilation.

This is a problem because it forces the messages to become services. Any ideas about that ?

**Comment by alexandre-daubois** [comment]
For the record, here's my try on this feature a year and a half ago: https://github.com/symfony/symfony/pull/49143

**Comment by pounard** [comment]
@alexandre-daubois this at least answers my question about message being services. Anyway, the first feature proposal remains easy to implement without having messages being services.

**Comment by rvanlaak** [comment]
Great enhancement, thanks! Helps a lot in putting configuration context close to implementation. Not pro or con "framework coupling", but to give other engineers clear hints what these classes are about.

I'd even say; let the Messenger component throw exceptions when these annotated classes are used in wrong contexts (e.g. when being configured as handler / transport).
