### ISSUE TITLE
Property accessor : nullsafe on an array

### ISSUE THREAD

**Issue by remi-vasco** [symfony/symfony#57510]
### Symfony version(s) affected

6.4.7

### Description

I'am using the property accessor component. I want to retrieve informations on an indexed array.
The index may not exist. I can not use the nullsafe operator after retrieving a not existing index.

### How to reproduce

```
$group = new \stdClass();
$group->name = 'Admin';

$std = new \stdClass();
$std->groups = [$group];

$propertyAccessor = PropertyAccess::createPropertyAccessor();
```
`dump($std);` to see that i have the correct structure
```
^ {#653
  +"groups": array:1 [
    0 => {#927
      +"name": "Admin"
    }
  ]
}
```
Display name of group in position 0 (`groups[0].name`)
```
dump($propertyAccessor->getValue($std, 'groups[0].name'));
^ "Admin"
```

Display name of group in position 1 (`groups[1].name`)
```
dump($propertyAccessor->getValue($std, 'groups[1].name'));
```
*Error:*
```
In PropertyAccessor.php line 383:
                                                                                                                 
  Cannot read property "name" from an array. Maybe you intended to write the property path as "[name]" instead.
```
Note : while an error is expected here (since [1] does not exists), the wording is a bit strange because `$propertyAccessor->getValue($std, 'groups[1].name')` will return `null` and not an array

-----

So what if I use null safe operator ? (`groups[0]?.name` or `groups[1]?.name`)
```
dump($propertyAccessor->getValue($std, 'groups[0]?.name'));
```
*Error:*
```
In PropertyPath.php line 125:
                                                                                        
  Could not parse property path "groups[0]?.name". Unexpected token "?" at position 9. 
```

This error is not what expected

### Possible Solution

maybe the solution is in the change of the regexp in PropertyPath.php

**Comment by alexandre-daubois** [comment]
After a quick Look at https://symfony.com/doc/current/components/property_access.html#reading-from-arrays, shouldn't you use `groups[1?].name` instead?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
