### ISSUE TITLE
Unhandled BadRequestHttpException when submitting the login form without username or password

### ISSUE THREAD

**Issue by gremo** [symfony/symfony#57532]
### Symfony version(s) affected

7.1

### Description

This https://github.com/symfony/security-http/commit/a8c6e8cab3d2a462e92df544c08ccb81bf0a6430 breaks the login form. Now submitting the form with an empty username and password would throw an exception.

![image](https://github.com/symfony/symfony/assets/1532616/a0ed3d46-110c-4738-97dd-ff110432dbd4)

### How to reproduce

Create a login form and submit the form withhout filling the username or password field.

### Additional Context

Happens to me after upgrading to 7.1 from 7.0.

**Comment by xabbuh** [comment]
Fixed in #57378, it will be part of the next patch release.

**Comment by gremo** [comment]
@xabbuh thanks, is there a quick workaround while waiting for the patch?

**Comment by derrabus** [comment]
Use a dev snapshot of `symfony/security-http`.
