### ISSUE TITLE
[Serializer] Call to undefined function is_mixed()

### ISSUE THREAD

**Issue by jkatruska** [symfony/symfony#57549]
### Symfony version(s) affected

7.1.1

### Description

When I have simple DTO with property that has data type mixed 

```
class MixedTypeConstructorDto
{
    public function __construct(
        //phpcs:ignore SlevomatCodingStandard.Classes.RequireSingleLineMethodSignature.RequiredSingleLineSignature
        #[Groups(["api"])]
        public mixed $mixed,
    ) {
    }
}
```
deserialization is failing on call to undefined function `is_mixed`. I can see this is already fixed in https://github.com/symfony/serializer/blob/7.1/Normalizer/AbstractObjectNormalizer.php but no new version was released so can we please release it? 

### How to reproduce

Deserialize anything to class with mixed property

**Comment by derrabus** [comment]
Duplicate of #57314.

> so can we please release it?

We will. Use a dev snapshot in the meantime.
