### ISSUE TITLE
[HttpClient] Let curl handle transfer encoding led to a change in behavior

### ISSUE THREAD

**Issue by ddegasperi** [symfony/symfony#57544]
### Symfony version(s) affected

5.4

### Description

With the backport-patch #54517 to symfony 5.4 the http-client sends a empty request body to the server when using a multipart form data.

### How to reproduce

With the following code snippet I receive a empty request body on the server:

```php

$formData = new FormDataPart([
    'degree' => '90',
    'file' => new DataPart(
        $fileResource, // a resource not a string
        'image.jpg',
        'image/jpeg'
    )
]);

$response = $client->request('POST', '/api/image/rotate/', [
    'headers' => $formData->getPreparedHeaders()->toArray(),
    'body' => $formData->bodyToIterable(),
]);

```

The client runs on a server with:
PHP Version: 7.4.33
Curl: 7.61.1

### Possible Solution

A possible workaround is to add the following header `Transfer-encoding: chunked` to the request, but this would break once HTTP/2 protocol is used.

The patch seems to work just with a more recent version of Curl (e.g. 8.8), so an update of this dependency would be another solution

### Additional Context

Since Symfony 5.4 is supported also for PHP >=7.2.5, which often runs on systems where dependencies like curl are not necessarily/easaly updatable and I wonder if it was right to backport this patch to this version as it has visibly brought about a change in behavior.

**Comment by nicolas-grekas** [comment]
At the moment, I don't see any way to fix this issue in all cases.
We cannot always know ahead of time if h1.1 or h2 is going to be used so we cannot decide if we can send the header ourselves or not.
Could anyone investigate which version of curl fixed the behavior? That might be a start.

**Comment by ddegasperi** [comment]
@nicolas-grekas thank you, with the new version 5.4.41 the code behaves exactly as before and has solved my problem
