### ISSUE TITLE
Ban strtok() from the codebase

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#57542]
strtok() is considered for deprecation in https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_strtok_function
whether or not this it accepted, we shouldn't use this function, for the same reasons that it might be considered: this is a stateful function.

We should do this on branch 5.4, same as we do when fixing php-src deprecations.

**Comment by derrabus** [comment]
If the function is _not_ deprecated, I'd prefer to do this change on 7.2 tbh. Do you know when this will be voted on?

**Comment by wouterj** [comment]
Note that we only use this function in the stateless way.

**Comment by alexandre-daubois** [comment]
> Do you know when this will be voted on?

The debate looks particularly heated, I guess it could take some time before the vote being triggered

**Comment by nicolas-grekas** [comment]
> Note that we only use this function in the stateless way.

yes but no: the function still keeps the string in memory in case the stateful API is used, there is no way around (except maybe calling strtok again with the empty string after calling it...)

**Comment by nicolas-grekas** [comment]
> Do you know when this will be voted on?

In ~2 weeks: 8.4 freezes on August 13th

**Comment by that-guy-iain** [comment]
Considering how often PHP deprecates a function and then undeprecates it in later releases may it would be worth while waiting until the next release?

**Comment by nicolas-grekas** [comment]
We don't really need php-src's lead here. The statefulness of the function is enough to ban it.
