### ISSUE TITLE
[Webhook] SerializerInterface is not actually needed

### ISSUE THREAD

**Issue by jenky** [symfony/symfony#57567]
### Symfony version(s) affected

7.x

### Description

```
You cannot use the "webhook transport" service since the Serializer component is not installed. Try running "composer require symfony/serializer-pack". 
```
A quick search shows that this line is the only place where the serializer is used in the webhook component.

https://github.com/symfony/webhook/blob/67762b59de4b9e3c6918c44a345f59030923b82d/Server/JsonBodyConfigurator.php#L24

To be fair I don't think this is a bug, however serializer is not really needed to encode the event payload since it's always `array`, `json_encode` is fine.

### How to reproduce

Create a  new `SendWebhookMessage` then dispatch it without installing the serializer

### Possible Solution

Remove `SerializerInterface` and replace 

```php
$body = $this->serializer->serialize($event->getPayload(), 'json');
```
with
```php
$body = \json_encode($event->getPayload());
```

**Comment by n0rbyt3** [comment]
```symfony/webhook``` requires ```symfony/remote-event``` which requires ```symfony/messenger``` which finally requires ```symfony/serializer```.

```symfony/messenger``` provides custom ```SerializerInterface``` implementations and uses the component to encode and decode ```Envelope``` instances if any serializer is set.

However, I don't see any usages of ```symfony/messenger``` inside ```symfony/remote-event```. This needs to be checked and may can be removed, so ```symfony/webhook``` can add ```symfony/serializer``` as optional dependency then.

**Comment by jenky** [comment]
`symfony/messenger` **does not require** `symfony/serializer` as far as I know. Otherwise `symfony/serializer` should be installed when I install `symfony/webhook`

**Comment by n0rbyt3** [comment]
Well, it does: https://github.com/symfony/messenger/blob/7.1/composer.json#L33

**Comment by jenky** [comment]
It's a dev dependency, which is not installed in my case as expected. Messenger uses [PhpSerializer](https://github.com/symfony/messenger/blob/7.1/Transport/Serialization/PhpSerializer.php) by default if you don't specify custom serializer which doesn't need `symfony/serializer` to encode the message. 

Anyway you missed my point, you don't need the serializer component to turn an `array` to JSON string. If you do really need it then make serializer optional in `JsonBodyConfigurator` 

```php
public function __construct(
    private readonly ?SerializerInterface $serializer = null,
) {
}

// 

$body = $this->serializer?->serialize($event->getPayload(), 'json') ?? \json_encode($event->getPayload());
```

**Comment by n0rbyt3** [comment]
Sorry, I missed it's the dev dependency block. You're right. Since it's optional, SerializerInterface should be nullable and ```json_encode``` should be used as fallback.

**Comment by xabbuh** [comment]
see #57881
