### ISSUE TITLE
[Mailer] ESMTP EHLO checks for capabilities (including STARTTLS) on 127.0.0.1 even if actual host is an external one.

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#57568]
### Symfony version(s) affected

All.

### Description

The EHLO command fetching the Capabilities in ESMTP checks the capabilities of 127.0.0.1, see
https://github.com/symfony/mailer/blob/2eaad2e167cae930f25a3d731fec8b2ded5e751e/Transport/Smtp/EsmtpTransport.php#L142
It always checks against `$this->getLocalDomain()`, which is hardcoded to `[127.0.0.1]`.

Am I missing something? Shouldn't it check the capabilities of the actual host to connect to?

### How to reproduce

Because of this behaviour we have the following problem:
* localhost (127.0.0.1) has STARTTLS enabled, but the localhost MTA is not used by th application
* symfony/mailer should connect to an external host instead (like "mail.example.org:25")  -- _which has no STARTTLS_ in our case
* using the Mailer component now checks capabilities of localhost -> "cool, it has STARTTLS, so force-using it"
* Mailer thus tries to use STARTTLS with mail.example.org:25 -> fails

### Possible Solution

I know there's the option to set `auto_tls=false` in later versions (which we sadly can not use in our application just yet, because symfony/mailer is an implicit dependency by the TYPO3 framework in our case), but using the SMTP capabilities from 127.0.0.1 when actually an external host is configured, is wrong in any case, no?

The ESMTP code should always check the capabilities of the host-to-connect-to.

**Comment by n0rbyt3** [comment]
> It always checks against ```$this->getLocalDomain()```, which is hardcoded to ```[127.0.0.1]```.

That's wrong. It defaults to 127.0.0.1, but can be set with ```setLocalDomain(string $domain)```. ```EsmtpTransportFactory``` calls that method if the ```local_domain``` parameter is set.

Docs: https://symfony.com/doc/current/mailer.html#other-options

**Comment by ghost** [comment]
You are right, but in our case `local_domain` is not set/used (the project in question uses TYPO3 10, which did not support DSN string passthrough to symfony).

**Comment by n0rbyt3** [comment]
You need to set this: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/MAIL.html#confval-globals-typo3-conf-vars-mail-transport-smtp-domain

This TYPO3 configuration is used to call ```setLocalDomain```: https://github.com/TYPO3/typo3/blob/3a35d2d6615c71f563ae4e02f1641fc5cfd48cbe/typo3/sysext/core/Classes/Mail/TransportFactory.php#L118:L120

**Comment by ghost** [comment]
This doc is from the main branch. The older TYPO3 10 does not support this.

**Comment by ghost** [comment]
But this report is independent of TYPO3, anyways (even if later version allow for more fine grained configuration). The EHLO capabilities check, if not configured explicitly via `local_domain`, should by default in any case go to the host instead of to 127.0.0.1. Or not?

**Comment by n0rbyt3** [comment]
> This doc is from the main branch. The older TYPO3 10 does not support this.

TYPO3 10 allows you to set ```dsn``` as option: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/Mail/TransportFactory.php#L161:L168

> The EHLO capabilities check, if not configured explicitly via ```local_domain```, should by default in any case go to the host instead of to 127.0.0.1. Or not?

The EHLO command expects the client hostname. I guess the value is hard-coded for performance reasons. Changing the behavior would be a BC break.

**Comment by xabbuh** [comment]
closing here then, thank you @n0rbyt3 for the help
