### ISSUE TITLE
[AssetMapper] Missing dependency in latest version

### ISSUE THREAD

**Issue by maelanleborgne** [symfony/symfony#57583]
### Symfony version(s) affected

6.4.9, 7.0.9, 7.1.2

### Description

Error message : `The service "asset_mapper.asset_package" has a dependency on a non-existent service "assets._default_package".`

I believe a bug was introduced in the latest release. A check on the use of the `Asset` component [was removed](https://github.com/symfony/symfony/pull/57533/files#diff-e4f52d5033296421d02e360c8355aa1931bdfb0c12579f4815ea02b724322c0cL1337). The `asset_mapper.asset_package` is no longer removed from the container, leading to a missing dependency error.

### How to reproduce

- Create a new project.
- `composer require asset-mapper`

**Comment by xabbuh** [comment]
see #57589
