### ISSUE TITLE
[HttpKernel] Optional warmers erroneously enabled under Windows

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#57599]
### Symfony version(s) affected

6.4.9

### Description

The string comparison here https://github.com/symfony/symfony/blob/f064b5de36e7a3a49d6e204a74027c37b31191e3/src/Symfony/Component/HttpKernel/Kernel.php#L548 fails under Windows even though it's the same path, since `$cacheDir` and `$buildDir` will have differing directory separators, e.g.

```
C:\Users\foobar\www\symfony\var\cache\prod
C:/Users/foobar/www/symfony/var/cache/prod
```

This leads to `$cacheWarmer->enableOptionalWarmers();` erroneously being executed in `Kernel::initializeContainer()`.

The issue is already alleviated in the 6.4 branch via https://github.com/symfony/symfony/commit/6ca2390533908c84329c66ad5cbe34ae0de1a1b7.

However I was wondering whether defensive programming should be applied here and use `Path::normalize()` on both paths, in order to make sure that the string comparison of these paths will always be accurate.

wdyt?

### How to reproduce

Install e.g. `symfony/website-skeleton` `6.4.9` under Windows and have an optional cache warmer implemented. The optional cache warmer will be run - even though the build path and cache paths are the same.

**Comment by nicolas-grekas** [comment]
>However I was wondering whether defensive programming should be applied here and use Path::normalize() on both paths, in order to make sure that the string comparison of these paths will always be accurate.

realpath() does that - that's its purpose.

**Comment by fritzmg** [comment]
@nicolas-grekas `realpath()` does _not_ normalize the directory separator of a path. It only resolves paths to their actual absolute paths and resolves symlinks in the process - but the directory separators will not be normalized to forward slashes. They will be forced to the directory separator of the current OS instead.

**Comment by nicolas-grekas** [comment]
AFAIK it does...

**Comment by fritzmg** [comment]
No, `realpath()` does not normalize to forward slashes. See the following example:

```php
var_dump(realpath(__DIR__.'/foo'));
var_dump(realpath(__DIR__.'/foo/bar'));
```

`foo` is a folder, while `foo/bar` is a relative symlink to `../bar`. The output under Windows will be

```
string(25) "C:\Users\fmg\www\test\foo"
string(25) "C:\Users\fmg\www\test\bar"
```

**Comment by xabbuh** [comment]
Does that matter? `realpath()` is applied on both paths. So on Windows they will both contain backslashes instead of forward slashes.

**Comment by fritzmg** [comment]
I'd argue that `Kernel::initializeContainer()` cannot be sure that the paths its retrevies via `$this->container->getParameter('...')` both have the same directory separators. Sure, `Kernel::getKernelParameters()` sets these parameters with `realpath()` - but this could have been overridden somewhere. Furthermore, if `realpath()` returns `false` for whatever reason, the path is used as is and thus the directory separators might differ again.

Besides, `$this->container->getParameter('kernel.cache_dir');` should ideally return the same result as `$this->getCacheDir()`, should it not? Same as well for `kernel.build_dir` and `getBuildDir()`.

**Comment by nicolas-grekas** [comment]
That's a lot of efforts to talk about a theoretical issue.
We favor real-world feedback, so that here, I consider the situation good enough. If not, one should open an issue with that real-world issue they're facing, and only then we'd consider.

**Comment by fritzmg** [comment]
> That's a lot of efforts to talk about a theoretical issue.

Well as a Windows user I can tell you that this isn't just theoretical 😉
Anyways the issue or question was whether defensive programming should be employed when using string comparisons with paths.
