### ISSUE TITLE
Doctrine MongoDB PersistentCollection cloning inside Symfony Form

### ISSUE THREAD

**Issue by alexcasalboni** [symfony/symfony#5760]
I'm using DoctrineMongoDBBundle and my Document has a ReferenceMany relation with itself (simple=true).

In order to keep lifecycle events working I had to set 'by_reference'=>false in the form type.

Then I've noticed that I had a persisting error when I tried to change the collection, but **only** when I was submitting an empty collection.

I found out that doctrine was trying to delete a PersistentCollection without an Owner and this behaviour is caused by the **__clone** operation, that is performed at this [line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L349).

Here is my workaround: everything works fine if I transform the PersistentCollection into an ArrayCollection during the postLoad event. This way I can still have lifecycle events and I get no errors submitting an empty collection.

Where is the problem? Is this a Symfony Form issue or a DoctrineMongoDB one?

**Comment by xabbuh** [comment]
Can any of you create a small example application that allows to reproduce the issue?

**Comment by jankramer** [comment]
This issue is no longer relevant for me. Given that it's so old, you might as well close it as far as I'm concerned.

**Comment by xabbuh** [comment]
Thank you for the feedback. I am closing here then. But if anybody else experiences this issue, please leave a comment and best also add a reproducible example application and we can reopen.
