### ISSUE TITLE
[AssetMapper] import package withou esm 

### ISSUE THREAD

**Issue by tito10047** [symfony/symfony#57604]
### Symfony version(s) affected

6.4

### Description

I want import specific version of javascript package which is very old. from 2013 . 

Specific this one [animate.css@3.1.1/animate.css](https://cdn.jsdelivr.net/npm/animate.css@3.1.1/animate.css)

But asset mapper show me 404 error message something with +esm url.

Im tried add package to importmap.php manualy, but after that this css file is downloaded as javascript file.

I bought a template from a databank that requires this old library. that's why I need her

Any idea how to solve this problem?

Thanks

### How to reproduce

run one of this commands
```/bin/php bin/console importmap:require animate.css@3.1.1/animate.min.css```
```/bin/php bin/console importmap:require animate.css@3.1.1```

or add it to importmap.php manually
```
    'animate.css/animate.css' => [
        'version' => '3.1.1',
    ],
```

**Comment by tito10047** [comment]
Manual import works, im just forgot add type. So this solve my problem.
```
    'animate.css/animate.css' => [
        'version' => '3.1.1',
		'type' => 'css',
    ],
```
But its bug that cant be imported autmaticaly by command?

**Comment by tito10047** [comment]
So, Im understand why cant import package with  ```importmap:require animate.css@3.1.1``` its writen in [documentation](https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages).

So, last things not working is command 
```php bin/console importmap:require animate.css@3.1.1/animate.min.css```

Its say error :

>   Unable to find the latest version for package "animate.css" - try specifying the version manually.

**Comment by smnandre** [comment]
This specific (and a bit old) package does not provide any packages.json metadata we can use. So if you found a way to make it work ( `sf i:req animate.css/animate.css` did work for me too), i think there is not much more we can do there 🤷‍♂️

**Comment by tito10047** [comment]
Thanks.
