### ISSUE TITLE
[String] snake() method changes in 7.1.2 breaks symfony/ux-translator

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony#57612]
### Symfony version(s) affected

7.1.2

### Description

After upgrading to Symfony 7.1.2 this morning, Symfony UX Translator  won't compile anymore with Webpack.

Here is part of the error:

```
Syntax Error: Missing initializer in const declaration. (1:39)

> 1 | export const THIS_VALUE_SHOULD_BE_FALSE. = {"id":"This value should be false.","translations":{"validators":{"en":"This value should be false.","fr":"Cette valeur doit \u00eatre fausse.","nl":"Deze waarde moet onwaar zijn."}}};
```

Downgrading symfony/string to 7.1.1 solves the issue.

### How to reproduce

```php
echo (new UnicodeString('This value should be false.'))->snake()->toString();
// symfony/string 7.1.1: this_value_should_be_false
// symfony/string 7.1.2: this_value_should_be_false.
```

### Possible Solution

The bug has been introduced with this PR: https://github.com/symfony/symfony/pull/57497
Reverting this solves the issue.

I guess it is a BC break?

**Comment by derrabus** [comment]
cc @arczinosek

**Comment by jmsche** [comment]
FYI the patch included in #57594 does not seem to fix the issue.

**Comment by xabbuh** [comment]
Can you please try #57615?

**Comment by jmsche** [comment]
@xabbuh The patch works... For the string I wrote as example above :sweat_smile: 

For translations with built translation keys it's still a huge BC break...

Let's just take this example:

```yaml
form:
    none: No item selected
```

UX Translator previously created a key for the translation, called `FORM_NONE` (I guess String somehow replaced the link between the two keys with an underscore), now the translation seems to be created with the `FORMNONE` key.

Edit: I'm writing this simple example, but in my case it's more than 300 translations that are not generated correctly anymore.

**Comment by bobvandevijver** [comment]
The `snake` update broke cache tags for me, but the fix in #57615 does solve my issue. For completeness, these are the output I recorded with the different versions.

| Version | Input | Output | 
| --- | --- | --- |
| 6.4.8 | `/ContainerOxPwblf\ResearchInstituteServiceGhostAad4a5e` | `container_ox_pwblf_research_institute_service_ghost_aad4a5e` |
| 6.4.9 | `/ContainerOxPwblf\ResearchInstituteServiceGhostAad4a5e` |  `/container_ox_pwblf\research_institute_service_ghost_aad4a5e` |

With the proposed fix the behaviour of 6.4.8 returns for us.

**Comment by xabbuh** [comment]
@jmsche Can you debug what input is passed to the `snake()` method when the returned value is `FORM_NONE`? With that info I can take another look into what else needs to be fixed.

**Comment by jmsche** [comment]
@xabbuh It's transforming `form.none` to `FORM_NONE`.

**Comment by jkgroupe** [comment]
Same issue with the version `symfony/string:6.4.9`. I downgraded it to 6.4.8
