### ISSUE TITLE
[ErrorHandler] DebugClassLoader raises return type declaration deprecations even with #[\ReturnTypeWillChange]

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#57624]
### Symfony version(s) affected

7.1.1

### Description

With this code

```php
final class FilteredAttributesBuilder implements ArrayAccess
{
    // (...)
    /**
     * @phan-suppress PhanUndeclaredClassAttribute
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        $this->builder->offsetUnset($offset);
    }
}
```

DebugClassLoader will still raise a deprecation:

```
User Deprecated: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "OpenTelemetry\SDK\Common\Attribute\FilteredAttributesBuilder" now to avoid errors or add an explicit @return annotation to suppress this message.
```

The purpose of the attribute is to do this type of forward notification "We know this will change in the future and now you know too". Arguably, this deprecation is superfluous here because the attribute could be seen as equivalent to a `@return` annotation, especially since this is 3rd party code.

### How to reproduce

1. Load https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Common/Attribute/FilteredAttributesBuilder.php using DebugClassLoader
2. get deprecation as noted prior

### Possible Solution

Skip the deprecation if the attribute is present.

**Comment by nicolas-grekas** [comment]
That's the expected behavior: `#[\ReturnTypeWillChange]` is not actionable because it doesn't tell what the new return type is going to be. You should add the proper `@return` and the deprecation will disappear.
