### ISSUE TITLE
`snake` method of String component returns a non clean string

### ISSUE THREAD

**Issue by sebdeleze** [symfony/symfony#57629]
### Symfony version(s) affected

7.0.9

### Description

Since version 7.0.9, the behavior of the `snake` method has changed. This problem was detected during the dump of translations in [symfony/ux-translator](https://github.com/symfony/ux-translator/blob/2.x/src/TranslationsDumper.php#L169).

Now, the translation keys are incorrect, because the braces and the dots are preserved, as you can see on this screenshot:

<img width="976" alt="Capture d’écran 2024-07-03 à 08 49 59" src="https://github.com/symfony/symfony/assets/6112685/0504b501-7694-4271-b021-b9d048232625">

Not sure it's the desired behavior, but if it's the case I will open another issue for translator dumper.

### How to reproduce

```php
s('The file is too large. Allowed maximum size is {{ limit }} {{ suffix }}.')->ascii()->snake()->toString()
```
Before 7.0.9, this instruction returns the string `the_file_is_too_large_allowed_maximum_size_is_limit_suffix`

Since 7.0.9, this instruction returns the string `the_file_is_too_large._allowed_maximum_size_is_{{_limit_}}_{{_suffix_}}.`, with braces and dot at the end.

**Comment by xabbuh** [comment]
The issue will be gone with 7.0.10 as we reverted the change causing this in #57616.

**Comment by sebdeleze** [comment]
Thanks for the quick reply @xabbuh !
