### ISSUE TITLE
Specify a different user when checking isGranted

### ISSUE THREAD

**Issue by pauljura** [symfony/symfony#57639]
### Description

I like the idea of voters, but the problem is that they only work for the currently logged in user. I would like to perform access checks on behalf of other users.

Take the standard blog website as an example. Users have access to posts. But suppose I want to share a post with other users. I want to know whether Alice can view the post, to see if I can share it with her.

So instead of writing
```
if ($this->isGranted('view', $post)) { ... }
```
I want to write
```
if ($this->isGranted('view', $post, $user)) { ... }
```

Another use case would be for command line processes. For example, Bob requests to run a report that takes a long time. I have a command that runs in the background, and I want it to verify that Bob has access to the report he is requesting. I can't do that right now with voters.

**Comment by Seb33300** [comment]
Are you trying to impersonate an user?
https://symfony.com/doc/current/security/impersonating_user.html

**Comment by wouterj** [comment]
Hi! We've another issue about this topic already: https://github.com/symfony/symfony/issues/43372 So I'm going to close this one as duplicate.
