### ISSUE TITLE
[symfony/property-info] Can't handle Collection annotations

### ISSUE THREAD

**Issue by bumburoom** [symfony/symfony#57634]
### Symfony version(s) affected

6.4.9

### Description

The property reader symfony/property-info/Util/PhpStanTypeHelper.php doesn't recognized the type of a collection property and try to access an not existing array key at line 169.

`return [new Type($subTypes[0]->getBuiltinType(), true, $subTypes[0]->getClassName(), $subTypes[0]->isCollection(), $subTypes[0]->getCollectionKeyTypes(), $subTypes[0]->getCollectionValueTypes())];`

### How to reproduce

The property with annotation like that can be successful extracted
 
`/** @var ?Permission[] $permissions*/`
  `  public ?array $permissions = null;`

The following annotation can not be extracted and cause a PHP warning "Undefined array key 0"
`/** @var ?Collection<int, Permission> $permissions*/`
   ` public ?Collection $permissions = null;`

**Comment by xabbuh** [comment]
Can you please check if #57617 fixes this?

**Comment by bumburoom** [comment]
> Can you please check if #57617 fixes this?

@xabbuh yes it does. Some idea when the patch will be available? Also as I can see, this was a PR for 5.4, not 6.4 will this patch also available for 6.4?

**Comment by xabbuh** [comment]
We regularly merge branches up. So changes done in 5.4 will eventually also land in 6.4, 7.0, 7.1 and 7.2.

**Comment by bumburoom** [comment]
> We regularly merge branches up. So changes done in 5.4 will **eventually** also land in 6.4, 7.0, 7.1 and 7.2.

sounds promising :)
