### ISSUE TITLE
Keep possibility to disable in-memory caching of routes

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#57640]
### Description

Here is one use case for the feature that was postponed in #53059. Opening as a new issue so it does not get lost in the already-closed issue. We can close this one here once #53059 is re-opened.

The use case is that it may be necessary to work with different sets of routes during functional tests. The `Router` keeps the routes in a  `private static $cache` property, which makes it impossible to change the routes once one set has been loaded.

Setting `$cache_dir` to `null` disables the part of the code where routes are dumped to a cache file and the results of that file are loaded into `the ::$cache` property.

**Comment by derrabus** [comment]
The code that handles this static cache is here:

https://github.com/symfony/symfony/blob/68a5704edace3371b649e779fc31ee860a19bd01/src/Symfony/Component/Routing/Router.php#L294-L305

So, as far as I understand it, this is a cache for the _compiled_ routes that only kicks in if someone disabled Opcache (which is the default on CLI and your tests).

This basically means that you – during your functional tests – recompile the router with a different set of routes for the same kernel and environment. Does that sound about right?

**Comment by mpdude** [comment]
~Absolutely. Insane?~ Maybe a more precise description would be that I have a custom route loader that provides different sets of routes for various tests. The kernel is shut down between different tests, but routes persist across tests (even across different `Router` instances, since the container is reset as well) in the `::$cache` static property.

I'd need to check, but it might be that during those tests, it makes no sense to dump the compiled routes to a file either, since they'd never be re-used... but that's just overhead, no functional difference.

**Comment by mpdude** [comment]
I see that `getCompiledRoutes()` helps sharing the compiled route set between the Matcher and Generator code paths... but does this have to be `static`? 

Is there a use case of sharing compiled route sets across different `Router` instances?

**Comment by nicolas-grekas** [comment]
can't you use a different cache path for each set of routes? the code is written with the assumption that one file = one set of rules, and that assumption doesn't look insane to me

**Comment by derrabus** [comment]
Sharing between those two is not the motivation. It's rather that parsing a large PHP file is expensive. This is a poor man's Opcache replacement.

And this also means: If you were to run your functional tests on a machine with Opcache enabled for CLI, you will run into similar problems. The static cache would be bypassed, but Opcache would say, "hey I've compiled this file already, I'm going to serve it from my bytecode cache!", which will screw you over just as this static cache does already.

**Comment by derrabus** [comment]
I mean, how many different sets of routes are you testing against? If we're talking about two or three or four, you could maybe use different environments for them (e.g. instead of `test` you have `test1` and `test2`). This way, you might even reuse caches between test runs which might speed up your functional tests significantly.

**Comment by mpdude** [comment]
I'll have to think that through...

Why is it relevant to have a `static` property?

**Comment by derrabus** [comment]
Opcache is static as well. This is as close as we can get to Opcache's behavior without actually using Opcache.

**Comment by nicolas-grekas** [comment]
because if file contents are immutable, caching in a static property improves sharing of the cache

**Comment by mpdude** [comment]
> caching in a static property improves sharing of the cache

... for people who create different instances of the `Router`? Is that a use case we want to optimize for?

(Update – Maybe I understand: Test suites that use the same set of routes again and again but have no opcache enabled benefit from keeping the routes in memory that way, to achieve caching across different `Router` instances/tests.)

> can't you use a different cache path for each set of routes?

and 

> And this also means: If you were to run your functional tests on a machine with Opcache enabled for CLI, you will run into similar problems.

This is why I initially made it possible to disable file-based caching entirely in #47496.

**Comment by mpdude** [comment]
Only a quick, superficial check, but relevant test suites also pass when I do not set the `cache_dir` to `null` but use a non-static `$cache` property instead.

**Comment by mpdude** [comment]
> Opcache is static as well.

You mean in the sense that once the file has been loaded during a request/process, it might be configured to give the same results again when the file is `required` once again?

There is special code in `\Symfony\Component\Config\ResourceCheckerConfigCache::write` that invalidates the opcache when cache files are written.

**Comment by derrabus** [comment]
> There is special code in `\Symfony\Component\Config\ResourceCheckerConfigCache::write` that invalidates the opcache when cache files are written.

We could do the same with our static cache, right? 🤔

**Comment by mpdude** [comment]
But you don't know when the file is written.

**Comment by derrabus** [comment]
> But you don't know when the file is written.

Why's that?

**Comment by mpdude** [comment]
I guess all I am asking for is a Router config setting to either disable file dumping/loading entirely and/or prevent caching in the `static` property 😇

**Comment by mpdude** [comment]
> > But you don't know when the file is written.
> 
> Why's that?

Ah! We call `\Symfony\Component\Config\ConfigCacheInterface::write` from within the Router, so that might be a suitable moment :+1:

**Comment by mpdude** [comment]
I'll try that. Still, being able to set the `cache_dir` to null from within framework config would disable all the file-based overhead I don't need in the first place, but that may well be a personal itch.

**Comment by nicolas-grekas** [comment]
Did you try setting the `router.cache_path` parameter to null?

**Comment by mpdude** [comment]
I added `router.cache_dir` myself in #47496 😅 and forgot about it since I was so focused on configuration-based settings instead of tweaking parameters directly.

So, the idea is to remove `framework.router.cache_dir` as a config setting without replacement (#52962), not add a config setting to disable the file-based caching (#53059) but keep `router.cache_dir` around as a semi-official configuration value to achieve the same results?

Would work for me.

**Comment by derrabus** [comment]
> Did you try setting the `router.cache_path` parameter to null?

If you meant `router.cache_dir`, we've deprecated that in #52962.

**Comment by nicolas-grekas** [comment]
we've deprecated the config option but not the parameter IIRC

**Comment by derrabus** [comment]
> So, the idea is to remove `framework.router.cache_dir` as a config setting without replacement (#52962), not add a config setting to disable the file-based caching (#53059) but keep `router.cache_dir` around as a semi-official configuration value to achieve the same results?
> 
> Would work for me.

I'd rather explore the path of fixing file-based caching for your scenario instead of relying on obscure ways to disable that functionality, tbh.

**Comment by mpdude** [comment]
> I'd rather explore the path of fixing file-based caching for your scenario
 
You mean https://github.com/symfony/symfony/issues/57640#issuecomment-2208422046? PR incoming.

Or do you mean that my test suites should use different environments and/or kernel cache dirs when working through different route configurations? I'll look into that, but seems to be a bit too complex to circumvent a feature I don't want to use in the first place (file-based caching of compiled routes).

**Comment by nicolas-grekas** [comment]
an obscure solution for an obscure need might fit ;)

**Comment by mpdude** [comment]
Trust me, I've spared some details to make this bearable for you guys.

**Comment by mpdude** [comment]
Hope #57645 is what @derrabus was expecting.

**Comment by derrabus** [comment]
> Hope #57645 is what @derrabus was expecting.

Yes! 🥳

**Comment by derrabus** [comment]
Oh, and did you check if that change fixes your problem?

**Comment by mpdude** [comment]
Only superficially, but it seems so, yes. Still, I'll set the `router.cache_dir` parameter to `null` additionally, since it entirely disables the loading/dumping code that the tests do not benefit from.

Thank you guys for the healthy discussion. As always, it was a pleasure working with you – you're always open-minded and interested in solutions, not dismissing suggestions right away.

**Comment by derrabus** [comment]
> Thank you guys for the healthy discussion. As always, it was a pleasure working with you – you're always open-minded and interested in solutions, not dismissing suggestions right away.

I thank you for making me dig into exciting Symfony code I haven't read for ages. 😅

**Comment by mpdude** [comment]
Code that feels like 🥃 to you, I hope 😉.
