### ISSUE TITLE
[Messenger] InvalidCatch: WrappedExceptionsInterface

### ISSUE THREAD

**Issue by rela589n** [symfony/symfony#57667]
### Description

Currently if anyone will try to catch `WrappedExceptionsInterface`, he will receive following psalm static analysis error:

```
ERROR: InvalidCatch
at /home/rela589n/Projects/opensource/phphd/exceptional-validation-bundle/Messenger/ExceptionalValidationMiddleware.php:31:9
Class/interface Symfony\Component\Messenger\Exception\WrappedExceptionsInterface cannot be caught (see https://psalm.dev/132)
        try {
            return $stack->next()->handle($envelope, $stack);
        } catch (WrappedExceptionsInterface $exception) {
            /** @var WrappedExceptionsInterface&Throwable $exception */

            $thrownException = new MessengerThrownException($exception);
```

It would make sense to make all exception interfaces extend `Throwable` in order to avoid this issue:

```diff
-interface WrappedExceptionsInterface
+interface WrappedExceptionsInterface extends \Throwable
{
    /**
     * @return \Throwable[]
     */
    public function getWrappedExceptions(?string $class = null, bool $recursive = false): array;
}
```

It's a minor enhancement, but it would still improve DX when working with Symfony

**Comment by n0rbyt3** [comment]
Personally, I don't recommend catching ```WrappedExceptionsInterface``` nor making it extending ```\Throwable```. For me it's an internal interface that is used to extend the definition of other exceptions. Also the documentation doesn't mention that interface in any way and it's only used in internal listeners.

Like other symfony components, there's an ```ExceptionsInterface``` that can be caught. The documentation for the messenger component always catches ```\Throwable```.

Just out of interest: what's the use case to get the wrapped exceptions?
