### ISSUE TITLE
[String] Snake method doesn't handle special characters in 7.1.2 (BC)

### ISSUE THREAD

**Issue by mathop** [symfony/symfony#57695]
### Symfony version(s) affected

7.1.2

### Description

The handling of special characters appears to have been removed in version 7.1.2.

### How to reproduce

```php
echo u('Symfony is great / awesome:')->snake()->toString();
// 7.1.1: symfony_is_great_awesome
// 7.1.2: symfony_is_great_/_awesome:
```

**Comment by derrabus** [comment]
Duplicate of #57612.

**Comment by mathop** [comment]
@derrabus #57612 is marked as closed, that's why I opened a new issue.

**Comment by xabbuh** [comment]
#57612 is closed because the issue has already been fixed (by reverting the PR causing the issue) and will be part of the next patch releaees
