### ISSUE TITLE
symfony/cache pool always returning new instance

### ISSUE THREAD

**Issue by gzhegow1991** [symfony/symfony#57703]
The idea of the pool is not an immutability.
Idea of the pool is to reduce memory and accessing shared data from any place of the app.

Also when you return always new instance you represent the moment when you last time ask storage about stored value.

Correct behavior is to store assoc with all produced items to always receive same instance inside one PHP process. And there's no good behavior to clear that pool at runtime, so best one i guess - is to limit size of the heap, that is built by last access date and maybe second criteria as stored data size. It means serialization have to be done on ->set() instead of ->save().

And again you could meet the problem when your counter was changed with another process. Its about data consistency/concurrency, and best stuff you can do with - is to implement onChange(fn(new, current, original)), like a version control on optimistic locking.

Yes, correct behavior is like you implement it with `function get(fnCalculate)`.

Worst thing here is possibility that cache could be saved directly outside the place you need actual value. And then as always - when you working with stored and runtime data - main trap is to update it without possibility to compare new value with stored one, thats why storages usually implement increment and decrement features as incoming commands instead of setValue() stuff.

So correct stuff is to mark PSR-6 deprecated at all... and follow some another interface.

**Comment by xabbuh** [comment]
I do not fully understand this issue. Do you have some concerns with the documentation? Then please clarify what offsets you want to see changed or added.

If on the other hand this is about the code (and that’s how it looks to me), we should move this to the code repository instead. Though I still have problems to understand what issues you experience and what your proposed solution is.

**Comment by gzhegow1991** [comment]
I dont know organization and processes in your github, so you can move it anywhere the team will read it.

**Comment by xabbuh** [comment]
I have moved this issue to the code repository, but you will still have to provide more details what your request is about. Is this a bug report? A feature request? What exactly do you propose?

**Comment by nicolas-grekas** [comment]
This behavior is by design. Receiving the same instance would allow mutating the state of the object in the pool and thus break the two-fetch same-state invariant. Cache pools are not about object identity but about state preservation.
That being said, there is a way to achieve what you want: ArrayAdapter with its $storeSerialized set to false will behave like you want here. You can chain it with another pool to achieve the behavior with every pool.

Closing since this has been answered.

**Comment by gzhegow1991** [comment]
```
$cache = new ChainAdapter([
    new ArrayAdapter(0, false),
    new FilesystemAdapter('mycounter', 0, __DIR__ . '/var/cache'),
]);

$cacheItem = $cache->getItem('mycounter');
$cacheItem2 = $cache->getItem('mycounter');
$cacheItem3 = $cache->getItem('mycounter');

dd($cacheItem, $cacheItem2, $cacheItem3); // #14 / #10 / #15
```

Case: 

```
$cacheItem = $cache->getItem($key = 'hello');
$cacheItem->set($limit = 2000);
$cache->save($cacheItem);

foreach ($queue as $command) {
  $cacheItemQueue = $cache->getItem($key = 'hello');
  $cacheItemQueue->set($limit = 1000);

  foreach ($command->getSomeList() as $item) {
      $cacheItemCommand = $cache->getItem($key);
      var_dump($limitCurrent = $cacheItemCommand->get()); // 2000
      // ... do some
      $cacheItemCommand->set(--$limitCurrent); // damn, CacheItem uses old stored value, ignores $limit...
  }
  
  var_dump($cacheItemQueue->get()); // 1000
}

var_dump($cacheItem->get()); // 2000
```

As i remember, CacheItemPool doc will not represent that you MUST call ->set() then ->save() as short as you can

So, or Pool is not a Pool, or Standart is not a Standart, or Symfony not a Symfony.

**Comment by gzhegow1991** [comment]
Guess i'm wrong, and the `counters` (mutex stuff) is not a `cache` case at all, thats maybe the point and biggest mistake i made while deep diving.

So the cache is about `shared access to data, with at most rarely as possible calculation when expired` (beta and randomly expiration stuff, also the result is the same for all processes)

And yes, then "PSR-6" with their "Pool" word should be deprecated, because is not a Pool, just the regular service, that is returning value objects.

**Comment by gzhegow1991** [comment]
Guess, library should be extended in a row with `Marshaller` also to interface of `Locker` to be more useful.

Locker could be:

1. filesystem/php : 
```
$h = fopen('w+');
if (flock($h = LOCK_EX | LOCK_NB)) {
# ... your code
flock($h, LOCK_UN);
}
fclose($h); // be aware, if app closed by exception that happens above in `your code` section - you get the problems.
```
* Easy to implement
* Unable to share between servers
* Unable to set TTL of the lock, cause of PHP has no internal process manager (you call it "php is synchronyous language" that is wrong) to hold all processes in single root process

2. pdo/database:
```
START TRANSACTION;
SELECT id FROM locks WHERE id = :lockId FOR UPDATE;
if (! $row) {
INSERT (id, locker) VALUE (:lockId, :processId);
SELECT id FROM locks WHERE id = :lockId FOR UPDATE; # again
}
# ... your code
UPDATE locks SET locker = NULL WHERE id := lockId AND locker = :processId;
COMMIT;
```
* Unable to TTL.
* DB locks can cause deadlocks but only if you lock second row by condition of first row, nothing else.

3. redis:
* using lua script that is send as one command
* also you can set TTL - its a good option if you not sure is exception could happen in your code

```
Main idea "lock if empty or not-exists with value/pid, then unlock if lock value equals pid.
Actually the lock is simple thing that forces any process to one of:
1. throw exception immediately ("non-blocking")
2. start `while (true)` loop until lock disappeared ("blocking")
```

Locking case solves all problems including premature cache expiration.

**Comment by stof** [comment]
Locking case is solved by symfony/lock, not by symfony/cache

**Comment by gzhegow1991** [comment]
> Locking case is solved by symfony/lock, not by symfony/cache

Seems a point.

And, sorry, without `symfony/lock` the `psr/cache` is just half-repository interface...

Actually... tags and clearing is a good point. Btw `symfony/cache` is a best implementation i know for a moment. That damn `psr/cache` and `psr/simple-cache` "interfaces" is broken on idea level.

**Comment by stof** [comment]
To me, this looks like you are trying to use PSR-6 for another use case than what it has been designed for. It is not meant to be a mutex API, nor a generic interface exposing underlying power of many storage engines.
For the use case of *caching*, there is no need to compare the old cached value to the new one. And if multiple processes are recomputing the same cache entry concurrently (because they all get a cache miss when reading it), it is not an issue either.

Note that the symfony/cache-contracts interface exposes a *different* caching API (symfony/cache implements both interfaces), but it does not involve locking either.

**Comment by nicolas-grekas** [comment]
Well the cache-contracts define an API that allows wrapping fetch+save operations in a lock. And actually, it does lock by default using a filesystem handle. More advanced locking strategies can be configured using a callback wrapper (see setCallbackWrapper).
