### ISSUE TITLE
[Form] EntityType option to work with big choices in view

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#57724]
### Description

In some cases in EntityType we need to use Select2 for speedup rendering tens of thousend rows in field

If I use `'choices' => []` we will got validate errors from selected with Select2 field

Would be greate to have `'ajax' => true` option, which dont send on frontend choices, but validate submitted data, as traditional

WDYT?

### Example

```
 $builder
            ->add('contact', EntityType::class, [
                'class' => Contact::class,
                'choice_label' => 'name',
                'required' => true,
                'placeholder' => '',
                'ajax' => true,
            ])
```

<img width="1007" alt="Screenshot 2024-07-15 at 11 19 10" src="https://github.com/user-attachments/assets/00632204-b1a0-491e-9536-9ef3d6e65378">

**Comment by xabbuh** [comment]
If I understand you correctly, the only thing this new option would change is that the choices would not be populated in the generated `FormView`?

**Comment by andreybolonin** [comment]
@xabbuh yep

**Comment by xabbuh** [comment]
sounds reasonable to me, though I would probably try to come up with a name other than `ajax`

**Comment by MatTheCat** [comment]
This should already be possible by changing the choice loader with something similar to [the UX Autocomplete’s](https://github.com/symfony/ux/blob/bdd3107b91d1fcdb4cf004fd8c0b9e82ee9a356e/src/Autocomplete/src/Form/ChoiceList/Loader/ExtraLazyChoiceLoader.php)?

**Comment by andreybolonin** [comment]
https://github.com/symfony/symfony/pull/52503 something like we need

**Comment by yceruto** [comment]
This is exactly what https://github.com/symfony/symfony/pull/52503 is for!

@xabbuh I came up with the `choice_lazy` option instead. Is it okay? We could discuss it in the PR if you like.
