### ISSUE TITLE
Backport "[FrameworkBundle] Fix warming up routes" for 6.4.9

### ISSUE THREAD

**Issue by rejhgadellaabsl** [symfony/symfony#57727]
### Symfony version(s) affected

6.4.9

### Description

Since 6.4.9[1], the `drupal/simplesamlphp_auth` module will sometimes throw an error when attempting to log in the user:

> The router "Symfony\Component\Routing\Router" cannot be warmed up because it does not implement "Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface".

[1] The bug might have been introduced in 6.4.8 it never occured because there was another error (#57316) 

### How to reproduce

Using Drupal 10.2.7 or higher with the simplesaml_auth 4.0.0 module, try to log in.

### Possible Solution

It looks like this was fixed in 7.1.2 (see #57554 and 35d085dc18b494d20b75728ecb222543e760c515), but would appreciate if this could be backported for 6.4.x.

### Additional Context

Also see the [related simplesamlphp_auth bug](https://www.drupal.org/project/simplesamlphp_auth/issues/3452457#comment-15678676)

**Comment by xabbuh** [comment]
Can you try to debug which commit broke the previous behaviour (or provide a small example application that allows to reproduce it)?

**Comment by rejhgadellaabsl** [comment]
I'm afraid that putting together a simple example application isn't very straightforward for me. We run into the bug in a Drupal site that uses the simplesamlphp_auth module. I'm not sure where I would need to begin to find where / when this bug started occurring.

In the [related simplesamlphp_auth bug ticket](https://www.drupal.org/project/simplesamlphp_auth/issues/3452457#comment-15678676), someone provided a back-ported patch for 6.4.9, based on #57554. AFAICT, that fixes the issue for us, but others report that they're still seeing the issue. That's pretty much all I know...

**Comment by xabbuh** [comment]
Looking at the error message and [the stack trace](https://www.drupal.org/project/simplesamlphp_auth/issues/3452457#comment-15687825) I am not sure that #57554 would actually help here. The referenced bug seems to fail over the router being an instance of the `Router` class from the Routing component (which indeed does not implement the `WarmableInterface`) while the class patched in #57554 is the `Router` class from the FrameworkBundle.

Is it expected in Drupal that the `router` service uses the class from the component and not the one from the component?

**Comment by xabbuh** [comment]
Let's close here for now as said before I don't see how #57554 would help with that concrete problem. We can consider to reopen once we have more information.
