### ISSUE TITLE
[AssetMapper][UX-Autocomplete] Unable to generate a URL for the named route ux_entity_autocomplete

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#57731]
### Symfony version(s) affected

7.1

### Description

In phpunit-bridge tests I get `<!-- Unable to generate a URL for the named route &quot;ux_entity_autocomplete&quot; as such route does not exist. (500 Internal Server Error) -->`

As classic install in CI/CD:
`composer inst `
`bin/console importmap:install`
`vendor/bin/simple-phpunit`

Any ideas?
In `symfony:serve` mode all works fine (no errors with autocomplete)

### How to reproduce

1) install symfony ux-autocomplete
2) create field with `#[AsEntityAutocompleteField]`
3) insert `{% block importmap %}{{ importmap('app') }}{% endblock %}` in your template with autocomplete field
4) run tests, extends from WebTestCase

**Comment by MatTheCat** [comment]
Seems like you’re missing [the route import file](https://github.com/symfony/recipes/blob/main/symfony/ux-autocomplete/2.6/config/routes/ux_autocomplete.yaml)?

**Comment by andreybolonin** [comment]
@MatTheCat thx, you are right )
