### ISSUE TITLE
[YAML] cannot use interface constants with yaml parser

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#57736]
### Symfony version(s) affected

7.1

### Description

php now supports interface constants, but I'm getting an error when trying to parse a YAML file that uses them.  This does not happen when using a class that implements the interface.

The error:

Error: Cannot declare interface App\Metadata\PixieInterface, because the name is already in use

### How to reproduce

The interface

```php
namespace App\Metadata;
interface PixieInterface
{
    const IMAGE_TABLE='image';
}
```

The class that implements it to get the constants.
```php
final class ClevelandObjectWorkflow implements PixieInterface
{
```

The yaml file that fails
```yaml
tables:
    !php/const App\\Metadata\\PixieInterface::IMAGE_TABLE: []
```

Works
```yaml
tables:
    !php/const App\Workflow\Cleveland\ClevelandObjectWorkflow::IMAGE_TABLE: []
```

### Possible Solution

Obviously, this only works in versions of PHP that support interface constants.

**Comment by xabbuh** [comment]
I cannot support your issue (see https://github.com/xabbuh/issue-57736). Can you please modify the linked project in a way that allows to reproduce it?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
