### ISSUE TITLE
[HttpClient] Misleading workaround 411 Length Required error

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#57742]
### Symfony version(s) affected

6.4.3 

### Description

As per the doc, by default, the HttpClient streams the body contents when uploading files which can cause the server to answer with 411 Length Required (I experienced it with AWS)

The [documentation](https://symfony.com/doc/current/http_client.html#uploading-data) suggests a workaround: to turn the body into a string so it doesn't get streamed.

```
$client->request('POST', 'https://...', [
    // ...
    'body' => $formData->bodyToString(),
]);
```

=> But it doesn't work because the header `Content-Type: multipart/form-data; boundary=xxx` is then missing

I found the issue with Symfony 6.4.3, and it must be present with Symfony 7.x as the code looks the same

### How to reproduce

```
$body['file'] = DataPart::fromPath($filePath);

$parts = new FormDataPart($body);

// This fails
$this->httpClient->request(
	Request::METHOD_POST,
	$uploadUrl,
	[
		'body' => $parts->bodyToString(),
		// uncomment to make it work
		//'headers' => $parts->getPreparedHeaders()->toArray(),
	]
);
```

I'm uploading to a private URL so I cannot share it 😞 

### Possible Solution

`\Symfony\Component\HttpClient\HttpClientTrait::normalizeBody()` takes care of adding the `Content-Type: multipart/form-data; boundary=xxx` header when missing from the request: this is great👍 

But it only happens when the body is an array so the header is missing.

# If you think this is a documentation issue
The documentation should be
```
$client->request('POST', 'https://...', [
    // ...
    'body' => $formData->bodyToString(),
    'headers' => $formData->getPreparedHeaders()->toArray(), // ⬅️ NEW
]);
```

# If you think this is a code issue
Turning the body into a string looks like a hack to make the HttpClient always send the `Content-Length` header.
What I think would be a better solution is to add a `streaming` option, `true` by default for BC, to disable streaming.
It may look like this:
```
$client->request('POST', 'https://...', [
    // ...
    'body' => $formData,
    'streaming' => false,
]);
```

**Comment by nicolas-grekas** [comment]
This is indeed a doc issue, your suggestion for it is correct. PR welcome there.

**Comment by xabbuh** [comment]
see symfony/symfony-docs#20046
