### ISSUE TITLE
Unicode String snake case - regression in latest fixes

### ISSUE THREAD

**Issue by kevinpapst** [symfony/symfony#57782]
### Symfony version(s) affected

6.49 and others

### Description

Follow up of #57497 and #57612 and #57616

Behavior os `snake()` still contains a BC break. 
I did not check whether this was introduced by the original change or one of the fixes.

For years the string`123-customer,with/special#name` was converted to `123-customer_with_special_name`.
Now it returns `123-customer,with/special#name`.

Many characters are not converted as before/expected.

### How to reproduce

```twig
{{ '123-customer,with/special#name'|u.snake }}
```
shows `123-customer,with/special#name` instead of the expected `123-customer_with_special_name`

### Possible Solution

Revert previous "fixes"?

**Comment by xabbuh** [comment]
What you experience has been fixed by reverting the initial PR (#57497) in #57616. I nonetheless opened a PR to add a test to prevent future regressions (see #57789).

**Comment by kevinpapst** [comment]
Ah, so sorry ... I missed that the fix was not yet released 😊 thanks for test additional test!
