### ISSUE TITLE
{{ render(path()}} make the loading time 2 or 3 time slower in prod Env if APP_DEBUG not set to 1

### ISSUE THREAD

**Issue by MathewMielvac** [symfony/symfony#57800]
### Symfony version(s) affected

6.4.*

### Description

{{ render(path()}} make the loading time 2 or 3 time slower in prod Env if APP_DEBUG not set to 1

Create a new project, on 6.4
Controller as in the repo linked, as twig,
APP_ENV=dev (or prod)
APP_DEBUG=1 
Load time : 464 ms

APP_ENV=dev (or prod)
APP_DEBUG=0 
Load time : 1.17 s

Slack : https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1721639543495729

### How to reproduce

https://github.com/MathewMielvac/my_project_directory

**Comment by xabbuh** [comment]
I cannot reproduce your observation. Here are two Blackfire profiles:

- dev environment, debug enabled: https://blackfire.io/profiles/acb5cbcd-3f0e-4ae0-ad1f-6d0f15562ed7/graph
- prod environment, debug disabled: https://blackfire.io/profiles/c794e433-1345-4112-863d-4bb873a085fa/graph

And here is a comparison of both profiles: https://blackfire.io/profiles/compare/20ba47d4-7e27-4b46-b86d-24bc16f4378a/graph

**Comment by MathewMielvac** [comment]
I'm sorry i don t have blackfire licence, so i can t give you link, 

you tested with 2 diff env

The issue is that :  

Prod env APP_DEBUG 0 time > Prod env APP_DEBUG=1 time 
(in my case)

![image](https://github.com/user-attachments/assets/cdb4ff2f-d879-41e0-b69c-3a5f9105c31a)
![image](https://github.com/user-attachments/assets/702e0f5c-dd32-48eb-9bae-a27fdd15f817)

**Comment by xabbuh** [comment]
I still cannot reproduce it. Here is a profile where debug is enabled for the prod environment: 
https://blackfire.io/profiles/b99486b5-6498-433c-a76e-d7bd935eb755/graph As expected it is slower than with debug disabed.

**Comment by MathewMielvac** [comment]
So i don t know how to help you to reproduce it 

PHP 8.3.9 (cli) (built: Jul  5 2024 12:03:46) (NTS)
Symfony CLI version 5.10.2

/etc/php/8.3/cli/php.ini :
https://pastebin.com/3DNi63P5

**Comment by xabbuh** [comment]
Then you will have to debug this yourself I am afraid as we won’t be able to help you without being able to reproduce.
