### ISSUE TITLE
[Debug][Toolbar] How to higlight deprecations with yellow now ?

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#57821]
### Description

In past deprecations highlighted as warnings, now it just ordinary info.
Maybe need some config to return previous behavior ?

### Example

![изображение](https://github.com/user-attachments/assets/988fa6f0-df49-4676-b0e4-febac468cbcf)

**Comment by MatTheCat** [comment]
This was discussed in https://github.com/symfony/symfony/issues/36279, https://github.com/symfony/symfony/pull/36948, and  https://github.com/symfony/symfony/pull/37105 got merged in 5.2 :grin:

**Comment by zorn-v** [comment]
But I need "yellow color" on them. How to return it ?

**Comment by MatTheCat** [comment]
Override the `toolbar` block of the WebProfilerBundle’s `logger.html.twig`; see https://symfony.com/doc/current/bundles/override.html#templates.

**Comment by zorn-v** [comment]
That block just for tooltip. I need highlight in toolbar. It show that something wrong (deprications is wrong).

**Comment by zorn-v** [comment]
Whats next ? Just remove deprecations and refuse "BC promise" ?

**Comment by wouterj** [comment]
Thanks for referencing the tickets @MatTheCat.

As you can see in those discussions, there was a need for a way to differentiate warnings (yellow color) and deprecations (yellow color).

Ultimately, deprecations are mostly a todo list to indicate what needs to be done before a next major upgrade. They never are items that require immediate action. They are not "wrong". As such, it was decided that showing the item (with the number) is enough and it needs no new color to be introduced to the toolbar.

Can you share the use-case for requiring it to be yellow in these scenarios?

**Comment by zorn-v** [comment]
> Override the `toolbar` block of the WebProfilerBundle’s `logger.html.twig`

Thanks, was innatentive before
```twig
{% set status_color = collector.counterrors ? 'red' : collector.countwarnings or collector.countdeprecations ? 'yellow' : 'none' %}
```

Close then

**Comment by zorn-v** [comment]
@wouterj
> Can you share the use-case for requiring it to be yellow in these scenarios?

If deprecation in some library you can detect in early and make pull request if needed. 
Not at time when you decide to increase major version and wait indefinite amount of time when it fixed.
Just another number in toolbar is not noticeable at all.
