### ISSUE TITLE
[Scheduler] Support running missed tasks only once instead of for every missed run date

### ISSUE THREAD

**Issue by felixbrucker** [symfony/symfony#57858]
### Description

Assume you have the following periodic task configured:
```php
#[AsPeriodicTask(frequency: '1 minute', schedule: 'main', method: 'test')]
readonly class MyClass
{
    public function test(): void
    {
       echo "test\n";
    }
}
```
and the following Schedule:
```php
#[AsSchedule('main')]
final readonly class MainSchedule implements ScheduleProviderInterface
{
    public function __construct(
        private CacheInterface $cache,
        private LockFactory $lockFactory
    ) {}

    public function getSchedule(): Schedule
    {
        return (new Schedule())
            ->stateful($this->cache)
            ->lock($this->lockFactory->createLock('main-scheduler'));
    }
}
```

When running the worker for the first time the task is executed after 1 minute, and then runs every minute, as expected.
When closing the worker and restarting it, it continues on from where it left off (the task is executed after less than a minute). This is fine if you worker is online always.

Assume you leave the worker offline for 10 minutes, after starting it again the task will run 10 times, for every minute it missed.

This is not desired, if it missed a run it should run only once on startup of the worker and then run according to schedule again.

I was unable to find a configuration option or similar for this unfortunately.

**Comment by valtzu** [comment]
This is a feature of stateful schedules. Maybe you shouldn't use stateful schedule for your use case?

**Comment by felixbrucker** [comment]
Without stateful a task that is scheduled to run while the worker is not running will not be run once the worker is running again, only on the next run of the task, which is not desired

**Comment by felixbrucker** [comment]
consider the following example:
- the worker runs in 5 min intervals
- you have a task that is scheduled for `every 10 minutes` (or anything larger than 5 minutes)
 
the task will never run without stateful

**Comment by valtzu** [comment]
> the worker runs in 5 min intervals

Maybe this is where things go wrong, scheduler is meant to be running all the time.

---

I get what you're asking, but don't have a solution for you unfortunately, hopefully someone else will.

**Comment by felixbrucker** [comment]
it is considered best practice to run the worker in intervals as php/libraries do not do a good job wrt memory cleanup and memory leaks

That interval is often given as 1hr, where jobs with intervals longer than 1hr will never run without stateful

**Comment by felixbrucker** [comment]
> I get what you're asking, but don't have a solution for you unfortunately, hopefully someone else will.

I hope so too, to be honest i felt like the expected default behavior would be the behavior i am asking for, not the one currently implemented, i mean the usecase for rapid execution of the same function is pretty limited, at least it seems to me.

**Comment by eltharin** [comment]
I agree, 
@valtzu with a worker running all the time, if you have a schedule every 10 minutes, your worker fail and you relaunch in 1 hour, you have 6 schedule launched where once can be suffisant.
Or conversely, you have a schedule every 12 hours, last launch was at 8h00 worker fail at 12h00, you don't want task be launch at 12h00 but 20h00
