### ISSUE TITLE
[FrameworkBundle][Uid] UuidV1 case depends on `uuid` installed or not

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony#57878]
### Symfony version(s) affected

6.4, 7.0, 7.1 (?)

### Description

I found a strange bug while running the FrameworkBundle tests locally

```
Symfony\Bundle\FrameworkBundle\Tests\Functional\UidTest::testArgumentValueResolverEnabled
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'0aa49ee6-4de7-11ef-9275-ca8c1eeac807'
+'0AA49EE6-4DE7-11EF-9275-CA8C1EEAC807'
```

```php
// Symfony/Bundle/FrameworkBundle/Tests/Functional/UidTest.php

$client->request('GET', '/1/uuid-v1/'.$uuidV1 = new UuidV1());
$this->assertSame((string) $uuidV1, $client->getResponse()->getContent());
```

It took me some time to realize my local PHP still had the "uid" extension installed.

So the problem comes down to this in 

```php
// Symfony/Component/Uid/UuidV1.php

public function __construct(?string $uuid = null)
{
    if (null === $uuid) {
        $this->uid = uuid_create(static::TYPE);
    } else {
        parent::__construct($uuid, true);
    }
}
```

`uuid_create` from the Symfony polyfill only generates lowercase strings, but the `uuid_create` from the extension does not. 

So when the ArgumentResolver works, as it set the `$uuid` arguments, the `parent::__construct` is called, where a `strtolower` is applied to `$this-uid`

### How to reproduce

Install the uuid extension and run the FrameworkBundle functional tests

### Possible Solution

Add a strtolower (or any optimized strtr) in the UuiV1 constructor ?  (if so i'll open a PR) 

Or do you think we need to ensure all uid values are stored internally in lowercase ? 

...

Or this should not be considered a bug at all ?

**Comment by stof** [comment]
Given that the [predefined routing requirements for uuids](https://github.com/symfony/symfony/blob/5938c51403b567fca54ef758071f54622475f141/src/Symfony/Component/Routing/Requirement/Requirement.php#L28-L35) enforce lowercase, I think we should enforce the usage of lowercase even when using the PHP extension (if we want to optimize things when using the polyfill which already guarantees lowercase, we might want to use `\extension_loaded('uuid')` to make the check conditional but optimized by OPCache)

**Comment by nicolas-grekas** [comment]
And the polyfill should behave exactly like the extension.

**Comment by smnandre** [comment]
@stof @nicolas-grekas thanks for the quick answers! 

So to confirm, next actions would be:

[Symfony\Component\Uid\UuidV1](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Uid/UuidV1.php)
- add a `strtolower`/`strtr` in the constructor (when $uuid is null) to enforce lowercase

[Symfony\Polyfill\Uuid\Uuid](https://github.com/symfony/polyfill-uuid/blob/1.x/Uuid.php)
- make the `uuid_create` returns uppercase string (to mimic the extension)

@stof there is alreay this check in the [bootstrap.php](https://github.com/symfony/polyfill-uuid/blob/1.x/bootstrap.php) file of the polyfill 

Do you suggest we add it somewhere in the component code ?

**Comment by smnandre** [comment]
Is `strtr` still something we use ? 

Looks to me it's always slower than `strtolower` in recent PHP versions: https://3v4l.org/qbdah#v8.3.9

**Comment by nicolas-grekas** [comment]
strtolower has been optimized in recent versions of PHP indeed

**Comment by derrabus** [comment]
> And the polyfill should behave exactly like the extension.

I recall that I've had that problem with the different casing on different machines a couple of years ago. I might be utterly mistaken, but I think I came to the conclusion that the behavior of the extension with regards to UUID casing depended on the libraries the extension was compiled against.

**Comment by smnandre** [comment]
> the behavior of the extension with regards to UUID casing depended on the libraries the extension was compiled against.

So... do you think we need to change the polyfill ?

**Comment by derrabus** [comment]
No because the polyfill already reflects _a_ correct behavior.
