### ISSUE TITLE
symfony mailer alternative transport not working

### ISSUE THREAD

**Issue by alexdawn** [symfony/symfony#57871]
I have an issue with the symfony mailer either their is a bug or the docs are wrong.

I have a config:
```
framework:
  mailer:
    transports:
      transport1: smtp://127.0.0.1:1025
      transport2: smtp://127.0.0.1:1026
```

https://symfony.com/doc/current/mailer.html#multiple-email-transports
both are instances of mailcatcher. Regardless of what header I set in the docs:

`$email->getHeaders()->addTextHeader('X-Transport', 'transport2');`

I see all emails going to transport1.

I also see symfony has not stripped out the header (what the docs say should happen) looking in the raw email in the first mailcatcher instance I see `X-Transport: transport2`

_Originally posted by @alexdawn in https://github.com/symfony/monolog-bundle/issues/372#issuecomment-2256141850_

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by alexdawn** [comment]
> Can you create a small example application that allows to reproduce your issue?

I'll see if I have the time to make something up. Using xdebug I've just seen that the class:
vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php

doesn't have a send method like that of:
vendor/symfony/mailer/Transport/Transports.php
which has the logic to check for sibling transports and defer to that transport if the X-Transport Flag is set.

The code I'm working with has autowired the first SMTP transport. Will see if I can add a third dummy transport that just will be the default transport that gets instanced to a Transport class that is smart enough to use the X-Transport flag

**Comment by xabbuh** [comment]
> The code I'm working with has autowired the first SMTP transport. Will see if I can add a third dummy transport that just will be the default transport that gets instanced to a Transport class that is smart enough to use the X-Transport flag

Do you mean that `$mailer` (as in the docs example) in your case is the `SmtpTransport` but not the Symfony mailer service?

**Comment by alexdawn** [comment]
> > The code I'm working with has autowired the first SMTP transport. Will see if I can add a third dummy transport that just will be the default transport that gets instanced to a Transport class that is smart enough to use the X-Transport flag
> 
> Do you mean that `$mailer` (as in the docs example) in your case is the `SmtpTransport` but not the Symfony mailer service?

Yes everything seems to be working sensibly with the in built `mailer:test` command as that seems to be autowiring a suitable TransportInterface and I can specify transport1 or transport2 whereas the code I'm trying to work with is a message handler autowiring in a SmtpTransport (!?) despite both have the same construction signature and I can't see any service.yaml that would treat the two differently.

**Comment by xabbuh** [comment]
If you use one of the transports directly, you are not using the mailer which will inspect the header mentioned above. If you fix your message handlers code to inject the mailer instead, everything should work as expected. I am closing here for now as this doesn't look like a bug. Thank you for understanding.

But feel free to send a pull request or open an issue in the [documentation repository](https://github.com/symfony/symfony-docs) if you think that this needs some clarification.

**Comment by simonjacob1** [comment]
```
framework:
    mailer:
        message_bus: false
        transports:
            main: '%env(MAILER_DSN)%'
            alternative: '%env(MAILER_DSN_IMPORTANT)%'
```

nothing worked for me whatsoever, but including `message_bus: false` solved the issue for some reason.
