### ISSUE TITLE
[symfony/security-bundle] The file debug_console.php does not exist (in: .../vendor/symfony/security-bundle/Resources/config).  

### ISSUE THREAD

**Issue by ClaireSer** [symfony/symfony#57883]
### Symfony version(s) affected

7.1.3

### Description

I've updated the SecurityBundle of Symfony from 7.1.2 to 7.1.3 and when I then launch the simple command "php bin/console doctrine:schema:update --dump-sql", I get this error : 
`In FileLocator.php line 73:
  The file "debug_console.php" does not exist (in: "[...]/vendor/symfony/security-bundle/Resources/config").`

I don't have the error again when I go back to version 7.1.2.

### How to reproduce

- Run "composer require security"
- Then run "php bin/console doctrine:schema:update --dump-sql"

**Comment by xabbuh** [comment]
I fail to see how this could happen. The file does still exist: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/SecurityBundle/Resources/config/debug_console.php

Can you please create a small example application that allows to reproduce  this issue?

**Comment by ClaireSer** [comment]
Ok that's weird, I cannot reproduce the issue now...
Thank's for your help anyway.
