### ISSUE TITLE
Sendgrid-Bridge Silently Loosing Mails when Limit is Reached

### ISSUE THREAD

**Issue by GenieTim** [symfony/symfony#57904]
### Symfony version(s) affected

7.1.2

### Description

In the free plan of Sendgrid, only 100 E-Mails are included per day. When this limit is reached, the sendgrid-bridge still accepts E-Mails, acts as if they were sent out, while Sendgrid actually does not accept and/or send them. I would prefer if e.g. together with the failover mailer DSN the mailer would switch to another mailer that still works.

### How to reproduce

Create a free SendGrid account, use the Symfony Sendgrid Mailer Bridge, and send more than 100 E-Mails using this account within a day.

**Comment by xabbuh** [comment]
Can you please debug what is happening under the hood? Does Sendgrid not response with an error? Or is this error somehow swallowed by Symfony?

**Comment by GenieTim** [comment]
I have a `level: debug` log file, which contains absolutely no sign of an error. I would argue the error is swallowed by Symfony, if there is one. What can I do to further debug?

**Comment by xabbuh** [comment]
Please use a debugger like Xdebug to see what actually happens after the mailer transport tried to deliver an e-mail via Sendgrid. What is the response of the Sendgrid server and how does Symfony deal with it?

**Comment by xabbuh** [comment]
Closing here for now as there’s not much we can do without further information. But we can consider to reopen when we have more details. Thank you for understanding.

**Comment by GenieTim** [comment]
Yes, sorry, I am still on it; I have tried with the debugger and could not reproduce getting the error codes that Sendgrid claims to send when the limit is over; insofar, I blaim Sendgrid's API. I am in contact with the support to figure out whether it could be something else as well.

I have meanwhile switched to using `sendmail+api` as the DSN, as that one does not seem to be affected by this problem.
