### ISSUE TITLE
Error when deserializing ArrayObject with annotation

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#57914]
### Symfony version(s) affected

7.1

### Description

I got an error when deserializing an `ArrayObject` with annotation

```
Undefined variable $class at symfony/serializer/Normalizer/AbstractObjectNormalizer.php:753
```

### How to reproduce

```php
final readonly class Dto
{
    /**
     * @param ArrayObject<string,mixed> $prop
     */
    public function __construct(
        public ArrayObject $prop
    ) {
    }
}

$data = '{"prop": {"key": "value"}}';
$serializer->deserialize($data, Dto::class, 'json');
```

### Possible Solution

Removing the annotation will fix the issue. But, static analyzers will complain about that

**Comment by rynhndrcksn** [comment]
If I remember correctly, Symfony 7 dropped support for annotations and now only supports attributes. That may be causing the problem you're running into.

**Comment by derrabus** [comment]
Sorry, but that's incorrect. There's no attribute that would replace a PHPDoc comment.

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by rynhndrcksn** [comment]
@derrabus Thank you for the clarification! Apologies for that, I completely missed the fact it was a PHPDoc 🤦🏻‍♂️

**Comment by asispts** [comment]
@derrabus here's the reproducer https://github.com/pts-archive/symfony-issues-57914

**Comment by rynhndrcksn** [comment]
It looks like inside the `Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php` class, inside the `validateAndDenormalize` method, there's a couple checks happening, I'll paste them below:

```php
if ($collectionValueBaseType instanceof ObjectType) {
    $typeIdentifier = TypeIdentifier::OBJECT;
    $class = $collectionValueBaseType->getClassName() . '[]';
    $context['key_type'] = $collectionKeyType;
    $context['value_type'] = $collectionValueType;
} elseif (TypeIdentifier::ARRAY === $collectionValueBaseType->getTypeIdentifier()) {
    // get inner type for any nested array
    $innerType = $collectionValueType;

    // note that it will break for any other builtinType
    $dimensions = '[]';
    while ($innerType instanceof CollectionType) {
        $dimensions .= '[]';
        $innerType = $innerType->getCollectionValueType();
    }

    if ($innerType instanceof ObjectType) {
        // the builtinType is the inner one and the class is the class followed by []...[]
        $typeIdentifier = TypeIdentifier::OBJECT;
        $class = $innerType->getClassName() . $dimensions;
    } else {
        // default fallback (keep it as array)
        if ($t instanceof ObjectType) {
            $typeIdentifier = TypeIdentifier::OBJECT;
            $class = $t->getClassName();
        } else {
            $typeIdentifier = $t->getTypeIdentifier();
            $class = null;
        }
    }
}
```

In this case, both the `if` and `elseif` checks fail and there's no `else` statement to initialize the `$class` variable. If I add the missing `else` statement, like in the following:

```php
if ($collectionValueBaseType instanceof ObjectType) {
    $typeIdentifier = TypeIdentifier::OBJECT;
    $class = $collectionValueBaseType->getClassName() . '[]';
    $context['key_type'] = $collectionKeyType;
    $context['value_type'] = $collectionValueType;
} elseif (TypeIdentifier::ARRAY === $collectionValueBaseType->getTypeIdentifier()) {
    // get inner type for any nested array
    $innerType = $collectionValueType;

    // note that it will break for any other builtinType
    $dimensions = '[]';
    while ($innerType instanceof CollectionType) {
        $dimensions .= '[]';
        $innerType = $innerType->getCollectionValueType();
    }

    if ($innerType instanceof ObjectType) {
        // the builtinType is the inner one and the class is the class followed by []...[]
        $typeIdentifier = TypeIdentifier::OBJECT;
        $class = $innerType->getClassName() . $dimensions;
    } else {
        // default fallback (keep it as array)
        if ($t instanceof ObjectType) {
            $typeIdentifier = TypeIdentifier::OBJECT;
            $class = $t->getClassName();
        } else {
            $typeIdentifier = $t->getTypeIdentifier();
            $class = null;
        }
    }
} else {
    // default fallback (keep it as array)
    if ($t instanceof ObjectType) {
        $typeIdentifier = TypeIdentifier::OBJECT;
        $class = $t->getClassName();
    } else {
        $typeIdentifier = $t->getTypeIdentifier();
        $class = null;
    }
}
```

The command no longer fails with `Warning: Undefined variable $class` and it works!

I checked if this error occurs on the `6.4` branch, and it does not.
![image](https://github.com/user-attachments/assets/108b78e8-5372-4ad5-9eb7-c5b32f1ff653)

I checked if this error occurs on the `5.4` branch, and this happens:
```php
PHP Fatal error:  Declaration of Symfony\Component\Cache\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed in /home/ryan/projects/symfony-core/src/Symfony/Component/Cache/CacheItem.php on line 49
Symfony\Component\ErrorHandler\Error\FatalError^ {#46
  #message: "Compile Error: Declaration of Symfony\Component\Cache\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed"
  #code: 0
  #file: "/home/ryan/projects/symfony-core/src/Symfony/Component/Cache/CacheItem.php"
  #line: 49
  -error: array:4 [
    "type" => 64
    "message" => "Declaration of Symfony\Component\Cache\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed"
    "file" => "/home/ryan/projects/symfony-core/src/Symfony/Component/Cache/CacheItem.php"
    "line" => 49
  ]
}
```

Which makes me believe this doesn't have to be merged into either the `5.4` or `6.4` branches?

@derrabus If this looks like an acceptable solution, I can make a PR.

**Comment by xabbuh** [comment]
@rynhndrcksn Your findings look correct to me. Can you open a PR with your changes and also add a test case to prevent regressions?

**Comment by rynhndrcksn** [comment]
@xabbuh I can do that! I'll get it done later today when I'm off work.

**Comment by rynhndrcksn** [comment]
After looking more into it, I'm not sure what I previously found is indeed the issue (or at least the only issue). I created the following test in `AbstractObjectNormalizerTest.php`:

```php
public function testDeserializeJsonIntoArrayObject()
{
    $data = '{"foo": {"key": "value"}}';

    $normalizers = [new ObjectNormalizer(null, null, null, new PhpDocExtractor())];
    $encoders = [new JsonEncoder()];
    $serializer = new Serializer($normalizers, $encoders);

    $actual = $serializer->deserialize($data, DummyWithArrayObject::class, 'json');
    $this->assertInstanceOf(DummyWithArrayObject::class, $actual);
    $this->assertInstanceOf(\ArrayObject::class, $actual->foo);
    $this->assertSame(1, $actual->foo->count());
}

// To assist with testing, I also made a new class.
class DummyWithArrayObject
{
    /** @var \ArrayObject<string, mixed> */
    public $foo;
}
```

The final assertion (`$this->assertSame(1, $actual->foo->count());`), always fails because the count of `$foo` is showing as 0. Which is definitely unexpected. If I remove the fix I had found previously, I get the expected `Undefined variable $class` error message.

Out of curiosity, I `dd()`'d the `$actual` variable, and get the following output:

```php
^ Symfony\Component\Serializer\Tests\Normalizer\DummyWithArrayObject^ {#1283
  +foo: ArrayObject {#1237
    storage: []
    flag::STD_PROP_LIST: false
    flag::ARRAY_AS_PROPS: false
    iteratorClass: "ArrayIterator"
  }
}
```

Which also made me curious, so I wrapped the reproducer's `$this->serializer->deserialize()` call in a `var_dump()` and got the following output:

```php
^ Symfony\Component\TypeInfo\Type\ObjectType^ {#201
  -className: "ArrayObject"
}
object(App\Command\Dto)#237 (1) {
  ["prop"]=>
  object(ArrayObject)#158 (1) {
    ["storage":"ArrayObject":private]=>
    array(0) {
    }
  }
}
```

This, to me, helps verify that my original guess might've only been partially correct, and there's still something else missing.

Unfortunately I have barely worked with the Serializer component before, so I'm not quite sure what else could be causing this and someone else might have to take over debugging this issue.

I'll also provide the link to the commit with the above changes on my forked copy of Symfony, if that can help at all: https://github.com/rynhndrcksn/symfony/commit/5152de5d1c78f53c3a0e25f464ad3416d7ccf0ad

**Comment by xabbuh** [comment]
As far as I can see this also didn't work properly before Symfony 7.1 (where the TypeInfo component was introduced). On older Symfony versions the code doesn't run into an error but the `ArrayObject` also isn't deserialized properly.

**Comment by xabbuh** [comment]
I think I got it. @rynhndrcksn I have reused your commit to draft #57928.

**Comment by rynhndrcksn** [comment]
Ah okay, thank you for the information! I appreciate it!
