### ISSUE TITLE
[symfony/process] BC break with Process::isTerminated() when a process fail at start

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#57946]
### Symfony version(s) affected

7.1.0

### Description

Before 7.1, when a process failed at start because the command does not exists, nothing was different from a process who failed because of the exit code of the command.

Since 7.1, when the command does not exists (example: `unknown-command`), a new `ProcessStartFailedException` is throwned. It's interesting, why not, but then, `$process->isTerminated()` always return `false`. Before 7.1 (7.0, 6.x and before), in this particular case, `$process->isTerminated()` returned `true`.

From my point of view, it's a huge bc break, because we can't just try / catch the new exception, all the code who use `$process->isTerminated()` should be modified.

### How to reproduce

```php
$process = new Process(['unkown-command']);
try {
    $process->run();
// This exception is throwned in 7.1, but doesn't exists before (7.0, 6.x etc)
} catch (\Symfony\Component\Process\Exception\ProcessStartFailedException) {
}

var_dump(
    $process->isStarted(), // all versions : true
    $process->isTerminated(), // 7.0 and before : true, 7.1 : false
    $process->isSuccessful() // all versions : false
);
```

See https://github.com/steevanb/symfony-issue-57946

### Possible Solution

To be honnest, i don't know. Since `Process::isTerminated()` do not return a stored property, but call `updateStatus()` then check `$this->status`, I don't know how to fix it.

**Comment by stof** [comment]
@ausi @nicolas-grekas do you have any insight here ? this seems to be related to https://github.com/symfony/symfony/pull/52409

**Comment by xabbuh** [comment]
Same as #57722?

**Comment by stof** [comment]
@xabbuh no. This looks different (even though it is related). This issue does not complain about the fact we throw a ProcessStartFailedException but about the fact that a process that fails starting is not considered terminated after catching the exception.

**Comment by steevanb** [comment]
I agree with @stof , unless throwing a new exception is a bc break to me: before 7.1, starting a command who do not exists do not throw an exception, now it is.

So the same code will not work with 7.0 and 7.1: in 7.1 we have to catch the exception and do something, in 7.0 the code continue.

**Comment by stof** [comment]
@steevanb only invalid commands throw an exception immediately now (if you were using `->mustRun()` or other APIs throwing an exception on failure, those commands would have triggered an exception already)

**Comment by steevanb** [comment]
@stof yes i know, but here i speak about `run()`, not `mustRun()`.

To be honnest, i don't think `ProcessStartFailedException` is a good choice when we use `run()`, because `mustRun()` exists.

And again, same code in 7.0 and 7.1 will not work, to me it's a bc break.
I can understand the exception, but calling `isTermimated()` will not return the same value between 7.0 and 7.1, it's a problem.

**Comment by ausi** [comment]
> @ausi @nicolas-grekas do you have any insight here ? this seems to be related to #52409

As far as I can remember, this was a change in PHP itself in version 8.3, see https://github.com/php/php-src/issues/12589

**Comment by ausi** [comment]
> ```php
> $process->isStarted(), // all versions : true
> ```

This seems odd, when a `ProcessStartFailedException` is thrown this should be `false`.

**Comment by ausi** [comment]
@steevanb I was not able to reproduce your result. Executing your code snippet with version 7.1.3 results in the following output (`$process->isStarted()` is also `false` as it should be):

```
bool(false)
bool(false)
bool(false)
```

> This issue does not complain about the fact we throw a ProcessStartFailedException but about the fact that a process that fails starting is not considered terminated after catching the exception.

Which is the correct behavior I think, calling `isStarted()` returns `false` as it should and a process that was never started is not considered to be terminated I think. It behaves identical to something like `new Process([…], '/not/existing/cwd')->run()` always did.

> And again, same code in 7.0 and 7.1 will not work, to me it's a bc break.

I think the “correct” usage that works fine with 7.0 and 7.1 is something like:

```php
<?php
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\RuntimeException;

$process = new Process(['unkown-command']);
try {
	$process->run();
} catch (RuntimeException) {}

if ($process->isSuccessful()) {
	// Handle success
} else {
	// Handle failure
}
```

> but calling `isTermimated()` will not return the same value between 7.0 and 7.1, it's a problem.

Can you tell us more about the use case of checking `isTermimated()` in your code?

---

I agree that this is not optimal, but as the behavior change comes from PHP itself not Symfony, and there are other cases where `->run()` throws exceptions (invalid cwd, using windows, any other `proc_open()` failure,…) I think it is not justified to create a BC layer for that (which would not be that easy as I tried that first in #52409).

**Comment by steevanb** [comment]
@ausi Problem is not with `isSarted()`, but with `isTerminated()`

I don't understand how it cames from PHP, because i use the same PHP version (8.3) for my tests with symfony/process 7.0 and 7.1 but I don't have the same behavior.

**Comment by steevanb** [comment]
I've created a little repository to try it: https://github.com/steevanb/symfony-issue-57946

You will see the same code, with PHP 8.3, who has not the same behavior between symfony/process 7.0 and 7.1.

**Comment by ausi** [comment]
> I don't understand how it cames from PHP

Please run your test.php with PHP 8.2. With that you should see the different behavior between PHP 8.2 and 8.3. You can find more details about the behavior change in the PHP ticket: https://github.com/php/php-src/issues/12589

**Comment by steevanb** [comment]
Yes, and i'm sorry, but `symfony/process 7.0` with `PHP 8.2` or `8.3` do not throw and exception, and have the same behavior.
`symfony/process 7.1` with `PHP 8.2` have the same behavior too.

But `symfony/console 7.1` with `PHP 8.3` throw an exception.

Go to https://github.com/steevanb/symfony-issue-57946, see the output, and you can try it with `./test`.

**Comment by ausi** [comment]
> `symfony/process 7.1` with `PHP 8.2` have the same behavior too.
> 
> But `symfony/console 7.1` with `PHP 8.3` throw an exception.

Yes, that is what I meant. This shows that the origin of the changed behavior comes from PHP itself.

**Comment by steevanb** [comment]
@ausi And no ;) Symfony 7.0 and 7.1 do not have the same behavior with PHP 8.3. That's what i wrote in my last message: no exception with PHP 8.3 and Symfony 7.0 (first line of my message), but an exception is throwned with same PHP version but Symfony 7.1 (3rd line).

Please use my repository, and try it by yourself, I don't know how to explain it better than with examples and facts.

**Comment by nicolas-grekas** [comment]
Same as #57722 by @ToshY indeed.

I had a quick look and my advice here would be to retry calling proc_open with a string instead of an array when the array fails. This should lead to restoring the previous behavior.

Anyone up for a PR?

**Comment by nicolas-grekas** [comment]
FTR, php-src is emitting warnings that start with the following:
- `CreateProcess failed, error code: ` on Windows
- `posix_spawn() failed: ` when php is compiled with spawn support
- `Exec failed: ` or `Fork failed: ` otherwise.

We could sniff those prefix, but I don't know if that would provide anything over just retrying with a string when an array was passed and proc_open fails. I'd guess not.

**Comment by ausi** [comment]
> my advice here would be to retry calling proc_open with a string instead of an array when the array fails.

Makes total sense, why didn’t I think of that 🙈

> Anyone up for a PR?

https://github.com/symfony/symfony/pull/58189
