### ISSUE TITLE
Using IsCsrfTokenValid with private entity Id.

### ISSUE THREAD

**Issue by OrianeMrt** [symfony/symfony#57953]
### Description

Hello, 
It would be nice to be able to use the IsCsrfTokenValid with a private id.
Currently it's possible with : ` #[IsCsrfTokenValid(new Expression('"delete_author" ~ args["author"].id'))]`
But if the id is private, an error occurs:  `Cannot access private property AppEntityAuthor::$id`

**Comment by stof** [comment]
Expression language does not have a magic operator to try using getter to access properties (as it must support being compiled to a PHP expression without a dedicated runtime). Use `args["author"].getId()` to access the id through a getter.

**Comment by OrianeMrt** [comment]
Yes, I tested it too late, it's why I closed it. Maybe update the Symfony news ?
