### ISSUE TITLE
jsDeliver packages that use special characters in their 'import' statements fail the IMPORT_REGEX test in jsDelivrEsmResolver.php

### ISSUE THREAD

**Issue by IanAtOcucom** [symfony/symfony#57969]
### Symfony version(s) affected

6.4 and upward

### Description

The package `@progress/kendo-ui` imports jQuery as `jQuery$1` (url https://cdn.jsdelivr.net/npm/@progress/kendo-ui@2024.3.806/+esm )

This breaks the regex at https://github.com/symfony/asset-mapper/blob/7.1/ImportMap/Resolver/JsDelivrEsmResolver.php#L31

### How to reproduce

Try to require any package where the `import` statement uses a valid javascript variable name (any char, number class plus $, _) that doesn't match the regex `\w`. as an example, `@progress/kendo-ui` which requires jsQuery using the variable name `jQuery$1`

### Possible Solution

The regex could be rewritten to `'#(?:import\s*(?:[\w\$\d]+,)?(?:(?:\{[^}]*\}|[\w\$\d]+|\*\s*as\s+\w+)\s*\bfrom\s*)?|export\s*(?:\{[^}]*\}|\*)\s*from\s*)("/npm/((?:@[^/]+/)?[^@]+?)(?:@([^/]+))?((?:/[^/]+)*?)/\+esm")#'` to capture $, but this is still fraught with danger as javascript variable names may include [Unicode surprises](https://262.ecma-international.org/15.0/index.html?_gl=1*1oaoejw*_ga*MTc0NjI0MzAyNC4xNzIzMjQ2OTg4*_ga_TDCK4DWEPP*MTcyMzI0Njk4Ny4xLjAuMTcyMzI0Njk4Ny4wLjAuMA..#sec-identifier-names). 

### Additional Context

Additionally, if the content is very large, there may be pcre.backtrack_limit errors. (trying to replace the `[\w\$\d]` references with `[^\s]` references would lead to NULL results in preg_replace_callback due to backtrack errors in the regex.)

This feature may need to be completely rewritten to avoid regular expressions.

**Comment by smnandre** [comment]
I started something some time ago, maybe it's time to rework on it https://github.com/symfony/symfony/pull/54134

**Comment by IanAtOcucom** [comment]
For the immediate need, `[\w\d\$]` would be enough to cover most Latin-alphabet variable names, ignoring people who might want to write perfectly-valid `import 변하기쉬운것  from "도서관";`

And this is an _immediate_ need.

**Comment by smnandre** [comment]
Do you want to open a PR with your suggestion?

**Comment by IanAtOcucom** [comment]
I do not. I am not well-positioned to contribute to OSS projects in this role.

**Comment by smnandre** [comment]
Can you check if this PR solves your problem ? https://github.com/symfony/symfony/pull/58046

**Comment by IanAtOcucom** [comment]
That PR Resolves my issue, thanks!

**Comment by IanAtOcucom** [comment]
This bug also affects 7.x

**Comment by smnandre** [comment]
Yep, this PR targets the lowest maintained version concerned by the bug (6.4), and symfony mergers will propagate the fix up to the most recent one (7.1 & 7.2)

https://symfony.com/doc/current/_build/maintainer_guide.html#step-3-merge-it-into-the-other-branches

It's just a matter of time ;)
