### ISSUE TITLE
Port Number Not Included in absolute_url() and url() Functions

### ISSUE THREAD

**Issue by ucscode** [symfony/symfony#58023]
### Symfony version(s) affected

7.1.*

### Description

When using Symfony's Twig functions `absolute_url()` or `url()`, the generated URL does not include the port number if the application is accessed through a domain with a specific port number. This results in URLs being generated without the necessary port, which can cause issues when working with non-standard ports.

**Example:**

- **URL Accessed:** `localhost:7000`
- **Twig Code:**
  ```twig
  {{ absolute_url(path('name')) }}
  ```
- **Actual Result:**
  ```
  http://localhost/path/to/route
  ```
- **Expected Result:**
  ```
  http://localhost:7000/path/to/route
  ```

**Expected Behavior:**

The `absolute_url()` and `url()` functions should include the port number in the generated URLs when the application is accessed via a domain with a specific port beyond `80` and `443`

### How to reproduce

1. Access a Symfony project through a URL with a port number (e.g., `localhost:7000`).
2. Use the `absolute_url()` or `url()` function in a Twig template to generate a URL.
3. Observe that the port number is omitted from the generated URL (specifically on `TemplatedEmail`)

### Possible Solution

Ensure that the URL generation functions respect the port number configured in the request. This might involve updating the URL generator service to include the port number when generating absolute URLs.

### Additional Context

- Twig version: 3.0
- Web server: Apache 2.4

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ucscode** [comment]
> Can you create a small example application that allows to reproduce your issue?

Sorry, it was my error.

The functions were called through a custom command from the terminal

```bash
bin/console app:campaign:process
```

Within the command, an instance of `TemplatedEmail()` was created to access the twig template.

However, I noticed information like `$_SERVER['SERVER_NAME']`, etc are not available in the terminal.

And that should probably be the reason why there is no port (nor server name).

**Comment by xabbuh** [comment]
Setting the default URI for the router to use in those contexts schuld help: https://symfony.com/doc/7.2/routing.html#generating-urls-in-commands
