### ISSUE TITLE
symfony/http-foundation got a bug in Request:get

### ISSUE THREAD

**Issue by dozer111** [symfony/symfony#58034]
### Symfony version(s) affected

\>= 6.3 <= 7.1

### Description

Hi, I have a controller action

```php
public function create(DomainEntity1 $id, array $profile, Request $request): ResultInterface{}
```

this controller before was run with [qandidate/symfony-json-request-transformer](https://github.com/qandidate-labs/symfony-json-request-transformer)

now, i want to remove it and use symfony without it

in 6.3 release you add `getPayload` method to fix the same problem as in library https://symfony.com/blog/new-in-symfony-6-3-request-payload

---

seems your argument resolver has a bug. In current realization I got error

```
{"code":"exception_occurred","level":"system","data":{"origin":{"message":"Controller \"CompanyName\\Profile\\Service\\Player\\Controller\\PlayerController::create\" requires that you provide a value for the \"$profile\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one."},"previous":[]},"source":null}
```

but, when i change https://github.com/dozer111/http-foundation/blob/7.1/Request.php#L648-L649 this code to 

```php
    public function get(string $key, mixed $default = null): mixed
    {
        if ($this !== $result = $this->attributes->get($key, $this)) {
            return $result;
        }

        if ($this->query->has($key)) {
            return $this->query->all()[$key];
        }

        if ($this->getPayload()->has($key)) {
            return $this->getPayload()->all()[$key];
        }

        return $default;
    }
```

- the code works fine

can you change `->request->` to `->getPayload()->` ?

or there was a reason why you dont do it before?

### How to reproduce

i send the POST request to controller with body

```json
{
  "profile" : {
    "locale" : "en_US",
    "license" : "general",
    "ref_code" : "organic",
    "locked_at" : null,
    "elements" : {
      "type" : "profile",
      "size" : 2,
      "elements" : [ {
        "type" : "emails",
        "opt_out" : true,
        "collection" : [ {
          "type" : "email",
          "email" : "test@test.com",
          "primary" : false
        } ]
      }, {
        "type" : "phones",
        "opt_out" : true,
        "collection" : [ {
          "type" : "phone",
          "phone" : "+1234567890",
          "primary" : true
        } ]
      } ]
    }
  }
}
```

### Possible Solution

https://github.com/dozer111/http-foundation/blob/7.1/Request.php#L648-L649

change `->request->` on `->getPayload()->`

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by n0rbyt3** [comment]
If you want to use the feature, you need two steps:
1. define a DTO that matches your payload
2. add ```#[MapRequestPayload]``` as attribute to your controller argument

Please see the docs for additional hints using the attribute: https://symfony.com/doc/current/controller.html#mapping-request-payload

**Comment by ro0NL** [comment]
Note `Request::get()` is internal, and should not be relied upon.

**Comment by dozer111** [comment]
after careful debug the problem was found on my side

sorry for disturbing(
