### ISSUE TITLE
[HtmlSanitizer] strips links with relative scheme, e.g. "//example.com"

### ISSUE THREAD

**Issue by virtualize** [symfony/symfony#58073]
### Symfony version(s) affected

6.4.8

### Description

HTML Sanitizer strips `src` attributes that contain links with a relative scheme, e.g. `//example.com`. In my example a YouTube url inside a src attribute. If I regex replace the `//` with `https://` HTML Sanitizer keeps the link. 
On the contrary, when using a `href` the relative scheme is also kept.

Setting `allow_relative_links: true` does not work unfortunately. `force_https_urls: true` has not effect either. And even adding `//` to `allowed_link_schemes: ['//', 'http', 'https']` does not work.

Using this config
```php
framework:
    html_sanitizer:
        sanitizers:
            test_sanitizer:
                allow_safe_elements: true
                allow_static_elements: true
                allow_relative_links: true
                allow_elements:
                    iframe: '*'
``` 

As discussed here: https://github.com/symfony/symfony/discussions/58071

### How to reproduce

```php
// First, run "composer require symfony/html-sanitizer"
// Then, execute this file:
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\HtmlSanitizer\HtmlSanitizer;
use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;

$sanitizer = new HtmlSanitizer(
    (new HtmlSanitizerConfig())
        ->allowSafeElements()
        ->allowStaticElements()
        ->allowRelativeLinks()
        ->allowLinkSchemes(['//', 'http', 'https'])
        ->forceHttpsUrls()
        ->allowElement('iframe', '*')
);

$iframe = '<p><iframe src="//example.com"></iframe></p>';
$image = '<p><img src="//example.com" alt="Image"></p>';
$link = '<p><a href="//example.com"></a></p>';

echo $sanitizer->sanitize($link)."\n";
echo $sanitizer->sanitize($iframe)."\n";
echo $sanitizer->sanitize($image)."\n";
```

**Comment by tgalopin** [comment]
I tested your reproducer locally and the issue seems to be that you use allowRelativeLinks which is dedicated to links (a tags) instead of allowRelativeMedias which is used for anything else (img, iframe, ...).

Using your reproducer, this works as excepted on my side:

```php
<?php

require_once __DIR__.'/../autoload.php';

use Symfony\Component\HtmlSanitizer\HtmlSanitizer;
use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;

$sanitizer = new HtmlSanitizer(
    (new HtmlSanitizerConfig())
        ->allowSafeElements()
        ->allowStaticElements()
        ->allowRelativeMedias()
        ->allowLinkSchemes(['//', 'http', 'https'])
        ->forceHttpsUrls()
        ->allowElement('iframe', '*')
);

$iframe = '<p><iframe src="//example.com"></iframe></p>';
$image = '<p><img src="//example.com" alt="Image"></p>';
$link = '<p><a href="//example.com"></a></p>';

echo $sanitizer->sanitize($link)."\n";
echo $sanitizer->sanitize($iframe)."\n";
echo $sanitizer->sanitize($image)."\n";
```

Can you confirm?

**Comment by xabbuh** [comment]
Let’s close here then.

**Comment by virtualize** [comment]
Thanks Titouan. I can confirm using`allow_relative_medias` works as expected. 
I should have read the [docs](https://symfony.com/doc/current/html_sanitizer.html#force-allow-media-urls) thoroughly.
