### ISSUE TITLE
[WebLink] preload Twig function doesn't render attributes

### ISSUE THREAD

**Issue by thomas-keck** [symfony/symfony#58111]
### Symfony version(s) affected

7.1.3

### Description

Hello everyone,

I try to generate preload link with `preload()` Twig function :
`<link rel="preload" href="{{ preload(asset('styles/app.scss'), { as: 'style' }) }}">`

But HTML result doesn't contain the `as="style"` attribute :
`<link rel="preload" href="/assets/styles/app-d72b530dc03a65de87af4f62f521defd.css">`

The app is broken in browser because the styles aren't loaded.

I tried to clean Symfony cache, compile again assets, both in DEV and PROD environment. Attribute doesn't show up.

This bug can be reproduced with new Symfony project (see below).

Am I missing something ?

### How to reproduce

1. Clone the Symfony project https://github.com/thomas-keck/symfony_issue_web_link (built with `symfony new` and with single HomeController, `app.css` is included in `base.html.twig`)
2. `composer install`
3. `symfony serve`
4. Go to project root URL in your browser and inspect code

### Additional Context

Preload code in `base.html.twig` :
![SCR-20240828-iwcj-2](https://github.com/user-attachments/assets/3449c74a-3b17-4d8e-90d3-d84abb2be00f)

HTML source code in `<head>` :
![SCR-20240828-iyiz-2](https://github.com/user-attachments/assets/bdb74a06-e7cd-4ad5-a23f-6d647840fa03)

DevTools console warning :
![SCR-20240828-jyuz](https://github.com/user-attachments/assets/992a94c7-0b2e-40d6-8e53-a662f32943c4)

**Comment by stof** [comment]
The `preload` function cannot render the `as` attribute, as it is a function used inside the value of the `href` attribute.

**Comment by thomas-keck** [comment]
@stof I use Twig preload function like in WebLink's doc https://symfony.com/doc/current/web_link.html

**Comment by fracsi** [comment]
`preload` function adds a HTTP header to the response object.
See the [docs](https://symfony.com/doc/current/web_link.html#how-does-it-work).
> The WebLink component manages the Link HTTP headers added to the response. When using the preload() function in the previous example, the following header was added to the response: Link </app.css>; rel="preload"; as="style"

**Comment by thomas-keck** [comment]
I misunderstood the docs, thank you @fracsi .
