### ISSUE TITLE
[ErrorHandler] DebugClassloader: introduce an annotation to signal definite intent to add/change the return typehint of a method

### ISSUE THREAD

**Issue by mondrake** [symfony/symfony#58128]
### Description

Right now, DebugClassloader triggers a deprecation when a method with no return typehint implements/extends from a method that has in the docblock a `@return` annotation that specifies a type.

This has 2 limitations at the moment:

1. the check is limited to extending/implementing classes in a different vendor only
2. the deprecation is only 'potential' i.e. there is no certainty if/when it will happen, as it may be related to BC considerations etc

In Drupal we have a large legacy of unhinted code, and these limitations make difficult for us to engage in a managed journey to introduce return typehints. See https://drupal.slack.com/archives/C1BMUQ9U6/p1724921060882849 for some discussion.

We would suggest to introduce an annotation, say `@return-type-will-change`, to signal to DebugClassloader that the change WILL positively happen, so that deprecation triggered can be more effective in pressing for typehinting of the extending/implementing classes before next release; that deprecation can then be triggered also for classes in the same vendor.

### Example

For example, in an interface file have this: 

```php
/**
 * Returns the height of the image.
 *
 * @return int|null
 *   The height of the image, or NULL if the image is invalid.
 *
 * @return-type-will-change in drupal:12.0.0
 *
 * @todo Uncomment return type hint in drupal:12.0.0.
 * @see https://www.drupal.org/project/drupal/issues/3470951
 */
public function getHeight()/* : ?int */;
```

and then any class whose method is not typehinted will trigger a deprecation like

`Method "%s::%s()" will add "%s" as a native return type declaration in version 12.0.0. Implement the typehint in %s "%s" now to avoid errors.`

**Comment by mondrake** [comment]
Also see https://www.drupal.org/project/drupal/issues/3333824

**Comment by nicolas-grekas** [comment]
I'm not sure to understand: how is this different from having both `#[ReturnTypeWillChange]`  and `@return`?

**Comment by mondrake** [comment]
`#[ReturnTypeWillChange]` attribute is a way to 'force' an **implementing** method to keep no signature even if the interface asks for it, so it has a different purpose:

> [...] In case the return type cannot be declared for an overriding method due to PHP cross-version compatibility concerns, a #[\ReturnTypeWillChange] attribute can be added to silence the deprecation notice.

Looking at parents `@return` annotations, conversely, is correct, but it does not work well if you have very well documented interfaces but very little implementations that have done the typehint addition - you will get just thousands (in Drupal, literally) of deprecations like 'method... _might add_ ... native return type'. That will be too noisy, 

So the proposal here is to indicate exactly which method will get what typehint, and by when, so that a project like Drupal could make the transition in bits and pieces and still have accurate messaging of which methods need to be adjusted.

**Comment by stof** [comment]
@nicolas-grekas I think this corresponds to a past discussion we had. Currently, the DebugClassLoader treats any `@return` phpdoc on a method without a native return type as a tentative return type. The request here would be to have an explicit opt-in for tentative return types.

**Comment by mondrake** [comment]
Ah, and having _both_ ` #[ReturnTypeWillChange]` and `@return` together: if I understand well it will be no good for Drupal's BC - that would mean actually doing the change on the interface, then adding ` #[ReturnTypeWillChange]` to the implementing methods. But Drupal's ecosystem is made of contrib/custom modules that leverage core's interfaces: those will break with TypeError and be forced to adjust, which is not compliant with Drupal's BC policy.

**Comment by catch56** [comment]
Yes @stof's summary is correct - adding the opt-in means that we can suppress the general tentative return type message (although we don't need to because Drupal's contrib modules are all inside the Drupal namespace, so it never gets triggered anyway), and then _not _ suppress the opt-in message so that implementing classes get a deprecation message that they know they can't ignore.

**Comment by mondrake** [comment]
Filed a tentative PR, #58134
