### ISSUE TITLE
TransportResponseTrait::stream() - $fromLastTimeout improperly calculated

### ISSUE THREAD

**Issue by d42ohpaz** [symfony/symfony#58125]
### Symfony version(s) affected

v7.1.2 v7.1.1 v7.1.0 v7.1.0-RC1 v7.1.0-BETA1 v7.0.10 v7.0.9 v7.0.8 v7.0.7 v7.0.6 v7.0.5 v7.0.4 v7.0.3 v7.0.2 v7.0.1 v7.0.0 v7.0.0-RC2 v7.0.0-RC1 v7.0.0-BETA3 v7.0.0-BETA2 v7.0.0-BETA1 v6.4.10 v6.4.9 v6.4.8 v6.4.7 v6.4.6 v6.4.5 v6.4.4 v6.4.3 v6.4.2 v6.4.1 v6.4.0 v6.4.0-RC2 v6.4.0-RC1 v6.4.0-BETA3 v6.4.0-BETA2 v6.4.0-BETA1 v6.3.12 v6.3.11 v6.3.10 v6.3.9 v6.3.8 v6.3.7 v6.3.6 v6.3.5 v6.3.4 v6.3.3 v6.3.2 v6.3.1 v6.3.0 v6.3.0-RC2 v6.3.0-RC1 v6.3.0-BETA3 v6.3.0-BETA2 v6.3.0-BETA1 v6.2.14 v6.2.13 v6.2.12 v6.2.11 v6.2.10 v6.2.9 v6.2.8 v6.2.7 v6.2.6 v6.2.5 v6.2.4 v6.2.3 v6.2.2 v6.2.1 v6.2.0 v6.2.0-RC2 v6.2.0-RC1 v6.2.0-BETA3 v6.2.0-BETA2 v6.2.0-BETA1 v6.1.12 v6.1.11 v6.1.10 v6.1.9 v6.1.8 v6.1.7 v6.1.6 v6.1.5 v6.1.4 v6.1.3 v6.1.2 v6.1.1 v6.1.0 v6.1.0-RC1 v6.1.0-BETA2 v6.1.0-BETA1 v6.0.20 v6.0.19 v6.0.18 v6.0.17 v6.0.16 v6.0.15 v6.0.14 v6.0.13 v6.0.12 v6.0.11 v6.0.10 v6.0.9 v6.0.8 v6.0.7 v6.0.6 v6.0.5 v6.0.4 v6.0.3 v6.0.2 v6.0.1 v6.0.0 v6.0.0-RC1 v6.0.0-BETA3 v6.0.0-BETA2 v6.0.0-BETA1 v5.4.42 v5.4.41 v5.4.40 v5.4.39 v5.4.38 v5.4.37 v5.4.36 v5.4.35 v5.4.34 v5.4.33 v5.4.32 v5.4.31 v5.4.30 v5.4.29 v5.4.28 v5.4.27 v5.4.26 v5.4.25 v5.4.24 v5.4.23 v5.4.22 v5.4.21 v5.4.20 v5.4.19 v5.4.18 v5.4.17 v5.4.16 v5.4.15 v5.4.14 v5.4.13 v5.4.12 v5.4.11 v5.4.10 v5.4.9 v5.4.8 v5.4.7 v5.4.6 v5.4.5 v5.4.4 v5.4.3 v5.4.2 v5.4.1 v5.4.0 v5.4.0-RC1 v5.4.0-BETA3 v5.4.0-BETA2 v5.4.0-BETA1 v5.3.16 v5.3.15 v5.3.14 v5.3.13 v5.3.12 v5.3.11 v5.3.10 v5.3.9 v5.3.8 v4.4.51 v4.4.50 v4.4.49 v4.4.48 v4.4.47 v4.4.46 v4.4.45 v4.4.44 v4.4.43 v4.4.42 v4.4.41 v4.4.40 v4.4.39 v4.4.38 v4.4.37 v4.4.36 v4.4.35 v4.4.34 v4.4.33 v4.4.32 v4.4.31

### Description

If you look at [git blame for TransportResponseTrait at lines 153-157](https://github.com/symfony/symfony/blame/6.4/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L153-L157), you'll see the following condition block. In the `if` expression, the condition will always evaluate to false. I'm guessing this should have been an OR and not an AND?

### How to reproduce

```php
if ($fromLastTimeout = 0.0 === $timeout && '-0' === (string) $timeout) {
    $timeout = null;
} elseif ($fromLastTimeout = 0 > $timeout) {
    $timeout = -$timeout;
}
```

### Possible Solution

Change the block to read:

```php
if ($fromLastTimeout = (0.0 === $timeout || '-0' === (string) $timeout)) {
    $timeout = null;
} elseif ($fromLastTimeout = 0 > $timeout) {
    $timeout = -$timeout;
}
```

**Comment by alexandre-daubois** [comment]
> the condition will always evaluate to false

Are we sure about that? I suspect it actually helps handle floating point error. Did you have a case where the condition should have been true and wasn't?

**Comment by d42ohpaz** [comment]
@alexandre-daubois I stand corrected. I just checked parsing the conditions again, and `-0.0` does indeed cast to `'-0'` as a string. I am not sure how I missed that the first time around. My apologies. :)
