### ISSUE TITLE
Form ChoiceType Field with expend for radio button

### ISSUE THREAD

**Issue by nassiry** [symfony/symfony#58137]
### Symfony version(s) affected

6.4

### Description

creating form choice type field for radio buttton with option expended true, is working but when I set HTML5 required option to false it's auto adding new radio button with label NONE and empty value. so my question is why it's adding auto field.

### How to reproduce

`
->add('fieldname', ChoiceType::class, [
                'choices' => [
                    'one' => "1",
                    'tow' => "2"
                ],
                'expanded' => true,
                'required' => false,
            ])
`

### Additional Context

If set back HTML5 option required to true there is no auto field.

**Comment by MatTheCat** [comment]
This is the `ChoiceType`’s `placeholder`: https://symfony.com/doc/current/reference/forms/types/choice.html#placeholder

It is automatically set in your case because as a user there is no way to unselect a radio button; you have to select the placeholder instead.

**Comment by nassiry** [comment]
thanks I thought the placeholder is only required for select, and the doc is not cleared about this. after debugging source code I found it also.
```
} elseif ($options['expanded'] && '' === $placeholder) {
                // never use an empty label for radio buttons
                return 'None';
            }
```

 now by adding placeholder to false, it solve problem.

**Comment by MatTheCat** [comment]
Indeed, I believe you may close this issue and open another in https://github.com/symfony/symfony-docs/
