### ISSUE TITLE
[Dotenv][DebugCommang]: Сommand ignores dotenv_path setting in composer.json

### ISSUE THREAD

**Issue by scruwi** [symfony/symfony#58158]
### Symfony version(s) affected

5.4

### Description

The console command `bin/console debug:dotenv` ignores the `dotenv_path` setting specified in the composer.json file.

### How to reproduce

Let's assume that `.env*` files should be located in the directory `<app_root>/config`

1. Set the .env file path in composer.json using dotenv_path:

```json
    "extra": {
        "runtime": {
            "dotenv_path": "config/.env"
        }
    }
```

2. Instantiate command:

```php
$projectDirectory = '/var/www/api';
new DebugCommand($_ENV['APP_ENV'], $projectDirectory);
```

3. Run the console command `bin/console dump:dotenv`
4. Observe that the command does not use the specified path.

### Possible Solution

Use the same logic as in the `dotenv:dump` command to determine the `dotenv_path`.

**Comment by nicolas-grekas** [comment]
Fixed in 7.1 by #52638
