### ISSUE TITLE
[Yaml] Dumping with no value (like Docker Compose volumes section) isn't supported

### ISSUE THREAD

**Issue by gremo** [symfony/symfony#58155]
### Symfony version(s) affected

7.1

### Description

There is no way to dump  a YAML section "without values".

### How to reproduce

Dumping the following "Docker Compose volumes section":

```php
$yaml = Yaml::dump([
  'volumes' => [
    'db-data' => null,
  ],
]);
```

Will result in:

```yaml
volumes:
    db-data: null
```

Using an empty string istead will result in:

```yaml
volumes:
    db-data: ''
```

There is actually no way to dump "without value" like:

```yaml
volumes:
    db-data:
```

**Comment by xabbuh** [comment]
There is technically no difference if `null` is dumped instead of nothing. I am labeling this as a feature request as being able to dump nothing instead of `null` should be opt-in through a flag if we were to implement this.
