### ISSUE TITLE
[HttpClient] HttpClientTrait -> Content-Type header overridden when pass body option with application/json header value

### ISSUE THREAD

**Issue by VitekSkrip** [symfony/symfony#58174]
### Symfony version(s) affected

7.1

### Description

When pass request body with content type header, for example, application/json it overrides to application/x-www-form-urlencoded. Guess, somebody missed condition ```!isset($options['normalized_headers']['content-type'][0])``` like was here https://github.com/symfony/symfony/blame/8dc8ae8f312e5b6dd56e226d5e29724ce68a5757/src/Symfony/Component/HttpClient/HttpClientTrait.php at line 97 

### How to reproduce

Its clear

### Possible Solution

Guess, somebody missed condition ```!isset($options['normalized_headers']['content-type'][0])``` like here https://github.com/symfony/symfony/blame/8dc8ae8f312e5b6dd56e226d5e29724ce68a5757/src/Symfony/Component/HttpClient/HttpClientTrait.php at line 97

**Comment by nicolas-grekas** [comment]
If you pass an array as option body, this means you're posting a form. If you want to send json, either use option json or pass the body as a json string.
Closing as that's the expected behavior.

**Comment by VitekSkrip** [comment]
@nicolas-grekas  But [HTTPClient's](https://symfony.com/doc/current/http_client.html#uploading-data) doc contains 
---
When uploading data with the POST method, if you don't define the Content-Type HTTP header explicitly, Symfony assumes that you're uploading form data and adds the required 'Content-Type: application/x-www-form-urlencoded' header for you
---

**Comment by nicolas-grekas** [comment]
I guess we could improve the doc a bit. Note that it also contains:

> When uploading JSON payloads, use the json option instead of body. The given content will be JSON-encoded automatically and the request will add the Content-Type: application/json automatically too

Passing an array to option body implies that the client knows how to encode that array into a raw body string. Sniffing the content-type for that is not implemented. (and I'm not sure we should)

**Comment by VitekSkrip** [comment]
Thank u 4 fast answers @nicolas-grekas
