### ISSUE TITLE
[UriSigner] Move hashing algo from hardcoded in computeHash() to config

### ISSUE THREAD

**Issue by PrInStPL** [symfony/symfony#58180]
### Description

The choice of algorithm should be configurable, so that it can be selected depending on security needs. I believe that sha256 is not sufficient at the moment, and based on it, you can easily generate app_secret based on the signed url, if we do not provide another value in the configuration to the constructor.

**Comment by lyrixx** [comment]
> I believe that sha256 is not sufficient at the moment

Can you share some references about this statement?

> you can easily generate app_secret based on the signed url

Could you provide a reproducer?

**Comment by PrInStPL** [comment]
Sorry, my mistake. This thread shouldn't be here because it concerns a specific situation, when we are on default symfony and SymfonyCasts/verify-email-bundle settings and we are working with both user-supplied variables and weak APP_SECRET.
