### ISSUE TITLE
When using CollectionType, "data" is empty in the "entry_type" form

### ISSUE THREAD

**Issue by justin-oh** [symfony/symfony#58196]
### Symfony version(s) affected

6.4.10

### Description

When using `CollectionType` like this in some parent entity/form type:

```php
$builder->add('children', CollectionType::class, [
    'entry_type' => ChildType::class,
]);
```

I go into my `ChildType::buildForm(FormBuilderInterface $builder, array $options)` function to find `$options['data']` is not set and `$builder->getData()` is `NULL`.

### How to reproduce

Create a basic parent `OneToMany` child entity structure with custom form types for each and use `CollectionType` in the parent. You will not have access to the data in the child form type.

This is because `CollectionType` only offers `entry_options` which is passed to the `entry_type`. There is no way to specify the value of `'entry_options' => ['data' => ...]` such that each entry's data corresponds to the appropriate item in the collection.

### Possible Solution

In `ResizeListener::preSetData`, I found if I edit the code as follows, I can access the expected `$options['data']` in my child form type:

```diff
// Then add all rows again in the correct order
foreach ($data as $name => $value) {
+   $this->options['data'] = $value;
    $form->add($name, $this->type, array_replace([
        'property_path' => '['.$name.']',
    ], $this->options));
}
```

**Comment by stof** [comment]
The form component does not make any guarantee about the availability of data in the `buildForm` method of the form type. The data can be provided later by `$form->setData()` (potentially coming from a parent).
And even when it is available, there is no guarantee that it is the final data (as `->setData()` could still be called even if some data was provided in `createForm()`.

**Comment by justin-oh** [comment]
If I can do this:

```php
$builder->add('child', ChildType::class, [
    'data' => $parent->getChild(),
]);
```

and have access to `$child = $options['data'];` inside `ChildType::buildForm()`, it should follow that there is a reasonable way to do the same for `CollectionType` and `entry_type` / `entry_options`. In which case, this is maybe less of a bug and more of a feature request.

**Comment by justin-oh** [comment]
I realize this is possible and probably recommended to go through form events.

Leaving an example for future people who want to access their entity in a CollectionType form prior to the form being built:

```php
// App\Form\ParentType
namespace App\Form;

use App\Entity\Parent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('children', CollectionType::class, [
            'entry_type' => ChildType::class,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Parent::class,
        ]);
    }
}
```

```php
// App\Form\ChildType
namespace App\Form;

use App\Entity\Child;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Event\PreSetDataEvent;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChildType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            [$this, 'onPreSetData']
        );
    }

    public function onPreSetData(PreSetDataEvent $event): void
    {
        $form = $event->getForm();
        $child = $event->getData();

        // $form->add(...);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Child::class,
        ]);
    }
}
```
