### ISSUE TITLE
Symfony ACL - issue deleting an ACE and resulting ace_order of remaining ACEs in the ACL

### ISSUE THREAD

**Issue by bdscarboro** [symfony/symfony#5820]
I have a question I hope you might be able to help with. I'm using ACL to secure individual entities (using object ACEs). So for example I have an entity with one ACL containing 5 object Aces, corresponding to 5 people that have access to the entity. In my app's UI, I revoke access to that entity for one of those 5 people. In my code I find and delete that one object ace. This all works fine, but this is also where the problem comes in. Prior to deleting that ACE, the acl_entries table shows the 5 entries and the ace_order field contains 0,1,2,3,4 for those records. However after deleting the ACE, the 4 remaining ACEs have order 0,0,1,3 (notice there is no order=2). In later code, where we try to save that ACL again, an exception is thrown "invalid index (2)" as it tries to access element #2 in the array. So not sure if I'm doing something wrong, or if this is a bug in the symfony ACL code. Any suggestions would be most appreciated!

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
