### ISSUE TITLE
Nested TranslatableMessage-s aren't translated properly by DataCollectorTranslator

### ISSUE THREAD

**Issue by KopiasCsaba** [symfony/symfony#58213]
### Symfony version(s) affected

6.4

### Description

Hi everyone,

First of all, thank you for all your hard and awesome work on this project.

So, it seems by the code, and i also red somewhere that TranslatableMessage can be nested by it's parameters.

It does work through twig, and although untested, probably with the translator.default as well.

But in developer mode there is a DataCollectorTranslator above that, and an obscure thing prevents it to work properly.

### How to reproduce

```php
#[Route('/test')]
public function test(TranslatorInterface $t): Response
{
        dump(get_class($t)); // DataCollectorTranslator
        dump($t->trans(t('test.outer', ['price' => t('test.price')]))); // "Price is {price}" instead of "Price is foobar"
}
```

With a translation file:
```yaml
test.outer: 'Price is {price}'
test.inner: 'foobar'
```

### Possible Solution

I believe this would solve it:

in:  app/vendor/symfony/translation/DataCollectorTranslator.php

```php
$trans = $this->translator->trans($id = (string) $id, $parameters, $domain, $locale);
```

$id is casted to string, so removing that would solve this (and i don't know what other issue would it cause, if any).

TranslatableMessage->__toString() is just returning the $message, so thats why we get "Price is {price}" instead of "Price is foobar".

### Additional Context

Also

public function trans(?string $id, array $parameters = [], ?string $domain = null, ?string $locale = null): string

does not copy entirely the TranslatableInterface when it comes to ?string instead of string for $id.

**Comment by naturefund-falk** [comment]
Your translation file does not contain test.price, maybe you mixed it with test.inner?

**Comment by KopiasCsaba** [comment]
Oh I probably messed up the example in the hurry, will check. Most probably everything still holds true though.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
