### ISSUE TITLE
Make translations extraction possible for dynamic translation keys in twig templates

### ISSUE THREAD

**Issue by Tsounabe** [symfony/symfony#58212]
### Description

Hello,

Twig dynamic translation keys are ignored by the `translations:extract` command.
While it is possible to use a dynamic key in the twig template, they are ignored by the translations extract command.
It would be nice to fully handle this dynamic translation key behavior.

### Example

```
{# example.html.twig #}

{% set key = 'key.one' %}
{{ key|trans }} 
```

`sf translation:extract --force`

**Before:**
`key.one` is not extracted and is not present in the xliff file.

**After:**
`key.one` is extracted and is present in the xliff file.

**Comment by stof** [comment]
Dynamic translation keys (be it in Twig or in PHP) cannot be extracted as the extractor has no way to know which values the variable can have at runtime.

The case shown here is a simple case where the variable is defined just before and so can only have one value. With a full static analyzer, such case could be extracted (except that there is no such static analyzer for Twig and running a full phpstan run as part of the PHP extractor would be slow as hell, while being dependent on the project being clean regarding a phpstan analysis). But any case receiving a variable from elsewhere would still not be extractable even with a full static analyzer.

**Comment by Tsounabe** [comment]
Thanks for this clear answer.
