### ISSUE TITLE
 Unable to find a consumer for message of type "sendgrid".

### ISSUE THREAD

**Issue by nbwebdevafo** [symfony/symfony#58217]
### Symfony version(s) affected

7.1.3

### Description

I installed https://github.com/symfony/sendgrid-mailer and created the webhook. Accessing the URL /webhook/sendgrid works and returns Not Acceptable. The moment sendgrid tries to send a payload it throws an exception:

```
{
  "message": "Uncaught PHP Exception Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: \"Handling \"Symfony\\Component\\RemoteEvent\\Messenger\\ConsumeRemoteEventMessage\" failed: Unable to find a consumer for message of type \"sendgrid\".\" at HandleMessageMiddleware.php line 124",
  "context": {
    "exception": {
      "class": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
      "message": "Handling \"Symfony\\Component\\RemoteEvent\\Messenger\\ConsumeRemoteEventMessage\" failed: Unable to find a consumer for message of type \"sendgrid\".",
      "code": 0,
      "file": "/home/..../vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124",
      "previous": {
        "class": "Symfony\\Component\\RemoteEvent\\Exception\\LogicException",
        "message": "Unable to find a consumer for message of type \"sendgrid\".",
        "code": 0,
        "file": "/home/.../vendor/symfony/remote-event/Messenger/ConsumeRemoteEventHandler.php:31"
      }
    }
  },
  "level": 500,
  "level_name": "CRITICAL",
  "channel": "request",
  "datetime": "2024-09-10T02:54:08.172968-04:00",
  "extra": {}
}
```

Same thing happens when you test with Postman. To clarify, I have the following defined:

```
framework:
    webhook:
        routing:
            sendgrid:
                service: mailer.webhook.request_parser.sendgrid
                secret: '' # Leave blank if you dont want to use the signature validation
```

And

```
#[\Symfony\Component\RemoteEvent\Attribute\AsRemoteEventConsumer(name: 'sendgrid')]
class SendGridConsumer implements ConsumerInterface
{
    public function consume(RemoteEvent|MailerDeliveryEvent $event): void
    {
        // your code
    }
}
```

What could be reason for this?

### How to reproduce

Follow the steps in the README: https://github.com/symfony/sendgrid-mailer

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by nbwebdevafo** [comment]
> Can you create a small example application that allows to reproduce your issue?

Company policy does not allow public repos... and there nothing special here. Just have mailer component installed with https://github.com/symfony/sendgrid-mailer/

I don't know how to help you.

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug. I can hardly believe that publishing such a repo is against your company's policy.

**Comment by nbwebdevafo** [comment]
> Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug. I can hardly believe that publishing such a repo is against your company's policy.

So you are telling me that by installing a fresh symfony + mailer will help you solve this bug?

**Comment by derrabus** [comment]
No, I'm telling you that whoever makes an attempt at helping you will need to be able to reproduce your issue.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
