### ISSUE TITLE
[Validator] `Charset` validator should have been named `Encoding` instead

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#58227]
### Description

The two terms are not interchangeable:

* `Charset` determines a collection of available glyphs (Unicode). So `Charset` validator would possibly check if the codepoint makes sense for the character set.
* `Encoding` determines how the corresponding glyphs are encoded in bytes (`utf8`, `utf16`, etc). So the `Encoding` validator would verify if the bytes representation can be decoded back to a series of codepoint.

Originally defined at https://github.com/symfony/symfony/pull/53154

**Comment by derrabus** [comment]
Naming things is hard. 😓 

I just took a look at the PR again. Apparently, the constraint was named `Encoding` in the first proposal, but was later changed after a comment by @nicolas-grekas in https://github.com/symfony/symfony/pull/53154#issuecomment-1866070658.

The problem with `Encoding` is that it's a very broad term with different meanings depending on the context. A better name could've been `CharacterEncoding` for instance.

But now that the feature has been shipped, we cannot simply rename the constraint. We would need to deprecate the `Charset` constraint and add a replacement with a better name. We have to decide if it's really worth it.

cc @alexandre-daubois

**Comment by nicolas-grekas** [comment]
HTML uses charset for that concept, so it's not invented here.
Let me close as this is good enough, and alternatives are not better.

**Comment by zerkms** [comment]
@nicolas-grekas 

> HTML uses charset for that concept, so it's not invented here.

HTML started using it *before* those were two distinct terms. Just because someone uses it as a legacy is a weird justification, but oh well.

> and alternatives are not better.

This report was not about "better or worse", it was about "correct" and "incorrect". Current use of terms is misleading and incorrect :shrug:

**Comment by nicolas-grekas** [comment]
encoding is equally misleading - base-64 is an encoding.

"character set encoding" might be the most accurate, but seriously, charset is well understood.

**Comment by alexandre-daubois** [comment]
@zerkms If it helps, see this constraint as "check the string uses the charset of the given encoding".

**Comment by zerkms** [comment]
> check the string uses the charset of the given encoding

@alexandre-daubois :point_up: this phrase as-is makes very little sense. You encode "with" or "using" encoding. It's not a property, it's a mechanism. See how naming things wrong, then trying to explain them using the terms wrong makes it even worse? o_O

"Check the string is Unicode encoded with provided encoding" <- may be this.

**Comment by alexandre-daubois** [comment]
It was just a way of saying so that you could see things from another angle, maybe my example doesn't speak for you. That's OK.
I think Nicolas is right, there won't be a perfect solution, and now that the constraint has been merged, I don't think it's worth making the change.
