### ISSUE TITLE
[RFC] Get logs emitted by a particular service

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#58237]
### Description

There is just a task left to close #36668: adding information about deauthentication in the profiler’s security panel.

When investigating I found there was no API to collect such data, so I wondered if we couldn’t simply display some logs in the profiler. This would e.g. allow to easily know why a specific authenticator didn’t support the request, or why the `ContextListener` logged you out…

I just wrote “simply” but there is one issue: AFAIK there is no way to get the logs emitted by a particular service.

The first idea that came to mind is to decorate loggers so that each one is unique and keep what it logged in memory. Then, a locator would allow to get those logs given the service which emitted them.

Enabling this behavior would be opt-in for each service not to consume too much memory, and only in debug mode since I don’t see much use-cases otherwise.

I don’t even know if something like that is possible to implement, but I guess I have to ask if it makes sense before trying!

**Comment by stof** [comment]
There is no such concept as the origin of logs to identify each service.

Distinguishing different log sources is the reason why MonologBundle has the concept of channels, which are actually separate logger instances with an associated name (that gets included in the logs). However, by default, SecurityBundle applies the same `security` channel on all its services.
If you want more granularity, you could use a compiler pass (with a priority high enough to run before the MonologBundle pass configuring channel loggers) to change the `monolog.channel` tag on some services to make them use their own dedicatd channels.
The "Logs" panel of the WebProfilerBundle UI already supports filtering logs by channel.

However, for the case of https://github.com/symfony/symfony/issues/36668, maybe it is a matter of ensuring that the right logs are present in the `security` channel more than splitting them in a different channel.

**Comment by MatTheCat** [comment]
Indeed it seems what I want is Monolog channels :thinking: 

> for the case of https://github.com/symfony/symfony/issues/36668, maybe it is a matter of ensuring that the right logs are present in the security channel more than splitting them in a different channel.

Having to filter logs in a different panel doesn’t seem user-friendly to me; what I imagined is that e.g. when you expand a skipped authenticator in the profiler’s security panel, you can see the logs it emitted which could explain why it was.

**Comment by stof** [comment]
The WebProfilerBundle does not know with logger channel is used by which authenticator (or even if it uses a logger at all), so extracting the associated logs from the LoggerCollector would be quite hard to implement.

**Comment by MatTheCat** [comment]
Welp Iʼve got no idea then 😅

Thanks @stof for your feedback, Iʼm closing this.
