### ISSUE TITLE
[Mailer] Sendgrid: Support EU based sendgrid accounts

### ISSUE THREAD

**Issue by mallezie** [symfony/symfony#58230]
### Description

Sendgrid now offers the feature to send / store data on EU based servers. 

More info: https://www.twilio.com/en-us/blog/send-emails-in-eu

To use this feature programmatically with the email API you need to use a different host when using EU based servers. 

For the sendgridApiTransport the host for EU based servers is 'api.eu.sendgrid.com' and for sendgridSmtpTransport it is 'smtp.eu.sendgrid.net'. However the (non-EU) hosts are hardcoded in the transport plugin, so we would need a check in place to select / override the hostname for both transports.

**Comment by stof** [comment]
Looking at the official Sendgrid SDKs, they call this concept `region`, with values `global` for the existing supported host and `eu` for the EU-based one (indicating that they might add more regions in the future if needed).

I suggest updating the sendgrid transport factory to support a `region` option in the query string of the DSN (defaulting to `global` if not present).
Contributions are welcome to implement that (you can inspire from the mailgun bridge which already has a concept of region)
