### ISSUE TITLE
[AmqpMessenger] always return bool from messenger amqp conncetion ack and nack

### ISSUE THREAD

**Issue by NetBT** [symfony/symfony#58253]
### Symfony version(s) affected

6.1.11

### Description

Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned

/vendor/symfony/amqp-messenger/Transport/Connection.php in Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack at line 444

    public function ack(\AMQPEnvelope $message, string $queueName): bool
    {
        return $this->queue($queueName)->ack($message->getDeliveryTag());
    }

### How to reproduce

Same as #51397

**Comment by xabbuh** [comment]
Symfony 6.1 has reached the end of life a long time ago. You will to update to 6.4 or 7.1.

**Comment by NetBT** [comment]
> Symfony 6.1 has reached the end of life a long time ago. You will to update to 6.4 or 7.1.

We have a plan to upgrade the version, but it still needs several weeks.
