### ISSUE TITLE
[HttpClient] URL with colon is not correctly parsed

### ISSUE THREAD

**Issue by philipzeyen** [symfony/symfony#58313]
### Symfony version(s) affected

5.4

### Description

The `HttpClientTrait::parseUrl` Method cannot parse Urls containing a colon correctly.
EDIT: Solution developed in #58218 does not fix this problem

### How to reproduce

```php
$client = new NativeHttpClient([ // this client can be replaced with others
    'base_uri' => 'https://host.tld/'
]);
$response = $client->request(Request::METHOD_DELETE, 'foo/bar:1/baz');
// throws following exception: 'Symfony\Component\HttpClient\Exception\TransportException: Could not resolve host "foo"'
```

### Possible Solution

Adding the configured `base_uri` before calling PHPs `parse_url`

**Comment by ajgarlag** [comment]
Possible duplicate of #54332. See #58218 for the fix.

**Comment by philipzeyen** [comment]
Hey @ajgarlag 
i tried the solution developed in #58218. It does not fix this problem.
Have forgotten to mention it

**Comment by nicolas-grekas** [comment]
parse_url() oddities, see how PHP understands this URL:
https://3v4l.org/appLK

This case could be added to https://github.com/php/php-src/issues/12703

Add a / prefix if you can that'd work with https://github.com/symfony/symfony/pull/58218

**Comment by nicolas-grekas** [comment]
Closed by #58218

**Comment by nicolas-grekas** [comment]
Sorry, I meant this URL is just incompatible with parse_url in a too broken way. Use a / prefix instead.

**Comment by nicolas-grekas** [comment]
Actually I figured out a workaround in #58836
