### ISSUE TITLE
Symfony 6.4 custom logout "Unable to logout with CSRF token validation"

### ISSUE THREAD

**Issue by valeriy-efimov** [symfony/symfony#58311]
### Symfony version(s) affected

6.4.10

### Description

I'm trying to add a custom logout route using the documentation. https://symfony.com/doc/6.4/security.html#logout-programmatically

But i can't logout because faced with error "Unable to logout with CSRF token validation"

I don`t want use $security->logout(false); without CSRF protection

### How to reproduce

```
namespace App\Controller\SecurityController;

use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Routing\Attribute\Route;

class SecurityController
{
    #[Route(path: '/logout', name: 'logout')]
    public function someAction(Security $security): Response
    {
        $response = $security->logout();

        return $this->redirectToRoute('login');  
    }
}

<a href="{{ path('logout', {'token' : csrf_token('logout')}) }}">

```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by valerii-efimov** [comment]
Hello @xabbuh, sure

https://github.com/valeriy-efimov/symfony-custom-logout

Pls use this commands for setup project

`make build`
`make up`
`make bash`

`composer install`
`bin/console doctrine:fixtures:load `

After it follow url [localhost/login](localhost/login) and use this credentials 
test@test.com
123456

after login try to follow Logout url on the same page

**Comment by Spomky** [comment]
The logout key is missing from the [security.yaml file](https://github.com/valeriy-efimov/symfony-custom-logout/blob/main/config/packages/security.yaml#L17).
See https://symfony.com/doc/current/security.html#logging-out
The controller is not required anymore with 6.4.x: https://symfony.com/blog/new-in-symfony-6-4-simpler-logout

Also, I recommend the use of form `POST` request and the use of `logout_path`.
Note that the CSRF token is automatically managed with this twig method.

Before:

```twig
<!--Before-->
<a href="{{ logout_path('main') }}">Logout</a>

<!--After-->
<form method="post" action="{{ logout_path('main') }}">
    <button type="submit">Logout</button>
</form>
```

---

For the record: https://github.com/symfony/symfony/issues/51313#issuecomment-1685219937

**Comment by valerii-efimov** [comment]
Hello @Spomky, Thanks for the answer! 
But if i added 

```
  logout:
      csrf_parameter: token
      csrf_token_generator: security.csrf.token_manager
```

My method in SecurityController is ignored

```
    #[Route(path: '/logout', name: 'logout')]
    public function logout(Security $security): Response
    {
        try {
            $security->logout();
        } catch (Exception) {
        }

        return $this->redirectToRoute('login');
    }
```
I need this logic because default functionality return 500 (LogoutException Invalid CSRF token.) error when user tries to logout at same url.


When I changed security.yaml

```
            logout:
                path: _logout (different route name)
                csrf_parameter: token
                csrf_token_generator: security.csrf.token_manager
```

It works as I need. But it seems to me that these are some kind of crutches.

**Comment by Spomky** [comment]
> My method in SecurityController is ignored

Yes, the request is intercepted and the logout listener will perform the logout actions.
The controller is not needed at all with [the new feature](https://symfony.com/blog/new-in-symfony-6-4-simpler-logout).

> I need this logic because default functionality return 500 (LogoutException Invalid CSRF token.) error when user tries to logout at same url.

The CSRF changes for each request so yes it will raise an error if an invalid CSRF is sent.

>   logout:
      csrf_parameter: token
      csrf_token_generator: security.csrf.token_manager

Can be symplified:

```yaml
security:
   firewalls:
     main:
        logout:
            enable_csrf: true
```

**Comment by xabbuh** [comment]
I am closing here as the behaviour is expected as explained.
