### ISSUE TITLE
Can't assign an array to a hidden form element value

### ISSUE THREAD

**Issue by speller** [symfony/symfony#58330]
### Symfony version(s) affected

7.0.2

### Description

I expect the following code to work:
```php
$form->add('foo', HiddenType::class, ['data' => ['value1', 'value2']]);
```
And produce the following input fields in the form:
```html
<input type="hidden" name="foo[0]" value="value1"/>
<input type="hidden" name="foo[1]" value="value2"/>
```
But I'm getting the following error:

> Warning: Array to string conversion

How to fix it?

### How to reproduce

-

**Comment by xabbuh** [comment]
This is expected. The `HiddenType` can only handle strings. You are probably looking for wrapping your hidden fields in a [CollectionType](https://symfony.com/doc/current/reference/forms/types/collection.html).

**Comment by speller** [comment]
@xabbuh In my case, the `collection` widget is overridden by the EasyAdmin framework so when I try to use the collection type, I get a lot of unneeded HTML with the unneeded field label. Since EasyAdmin is represented on the Symfony website, I assume this is a part of the Symfony "ecosystem" and using the proposed solution doesn't work as expected and should be fixed.

Currently, to get what I need, I have to add a custom Twig template and apply custom properties to form fields to skip EasyAdmin's collection template application.

So I think there should be either a fix in EasyAdmin or a fix in Symfony for easier support of array values.

**Comment by xabbuh** [comment]
Please open an issue in the EasyAdminBundle repository. If there needs to be a way to influence the HTML rendered by the bundle, it should be handled over there.
