### ISSUE TITLE
Own Connection can not be added to Connection object since message bus 7.1.0

### ISSUE THREAD

**Issue by froemken** [symfony/symfony#58354]
### Symfony version(s) affected

7.1.4

### Description

Hello,

you have removed following line with symfony doctrine messenger bus 7.1.0:
https://github.com/symfony/doctrine-messenger/blob/v7.0.9/Transport/Connection.php#L70

Since then it's not possible anymore to set own Connection object via your Transport/Connection constructor. As I haven't found any further possibility to set own Connection it's IMO a bug.

In comment above it seems that "connection" should be part of options:
https://github.com/symfony/doctrine-messenger/blob/v7.0.9/Transport/Connection.php#L56

But, I can't find `$this->configuration['connection']` in full Transport/Connection object.

IMO it looks like you want to add it as option, but the job was not done completely ;-) 

Calling line in TYPO3 Source:
https://github.com/TYPO3/typo3/blob/v13.3.0/typo3/sysext/core/Classes/Messenger/DoctrineTransportFactory.php#L42

Issue at TYPO3 Forge:
https://forge.typo3.org/issues/105079

### How to reproduce

I tried following example: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.2/Feature-97700-AdoptSymfonyMessengerAsAMessageBusAndQueue.html

### Possible Solution

Add line 

```
$this->driverConnection = $driverConnection;
```

to your message bus Transport/Connection object.

### Additional Context

TYPO3 13.3

**Comment by xabbuh** [comment]
The only change that was done between 7.0 and 7.1 is that the property is now set using constructor property promotion. Neither the property itself was removed nor is the value passed to the constructor not assigned.

Closing therefore as I don't see anything wrong here.

**Comment by froemken** [comment]
Oh damn. Haven't seen the constructor propagation. Sorry. But, as it runs now, I must have done something else...

Wait. I have upgraded MariaDB in my DDEV system from 10.3 to 10.11.

Maybe that solves the issue.
