### ISSUE TITLE
[Serializer] ArrayDenormalizer silently fails if data is empty object or array

### ISSUE THREAD

**Issue by tombohub** [symfony/symfony#58367]
### Symfony version(s) affected

7.1

### Description

Deserializing to array of objects silently failes if content is single empty object or single empty array, but not if array of single empty object.

### How to reproduce

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Serializer;

$encoders = [new JsonEncoder()];
$normalizers = [new ObjectNormalizer(), new ArrayDenormalizer()];

$serializer = new Serializer($normalizers, $encoders);


class A
{
    public function __construct(public string $name)
    {
    }
}

/**
 * silently fails
 */
$serializer->deserialize('{}', A::class.'[]', 'json');

/*
 * silently fails
 */
$serializer->deserialize('[]', A::class.'[]', 'json');

/**
 * errors
 */
$serializer->deserialize('[{}]', A::class.'[]', 'json');



// using AbstractNormalizer::REQUIRE_ALL_PROPERTIES

/**
 * silently fails
 */
$serializer->deserialize('{}', A::class . '[]', 'json', [AbstractNormalizer::REQUIRE_ALL_PROPERTIES => true]);

/*
 * silently fails
 */
$serializer->deserialize('[]', A::class . '[]', 'json', [AbstractNormalizer::REQUIRE_ALL_PROPERTIES => true]);

/**
 * errors
 */
$serializer->deserialize('[{}]', A::class . '[]', 'json', [AbstractNormalizer::REQUIRE_ALL_PROPERTIES => true]);


```

### Possible Solution

Raise error because it's empty object or array is not expected

**Comment by alaugks** [comment]
In my opinion, the [exception](https://github.com/symfony/symfony/blob/2fe419e5ef498309c1b92a032a592935d667032f/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L413) needs to be thrown. To create an instance of class A, the `name` property must exist in the JSON. Even with `new A();` a PHP exception would be thrown.

With a nullable type declaration, the error message is not thrown.

```php
class A
{
    public function __construct(public ?string $name)
    {
    }
}
```

**Comment by mtarld** [comment]
Decoding `'{}'` or `'[]'` with the `JsonEncoder` will result as an empty array.
Therefore, according to me there is nothing unexpected here neither silenced failures.

Let's say that we have the following normalizer:
```php
$normalizer = new Serializer([new ObjectNormalizer(), new ArrayDenormalizer()]);
```
And the following class:
```php
class A
{
    public function __construct(
        public string $property,
    ) {
    }
}
```
Then:
- `$normalizer->denormalize([], A::class.'[]')` will return an empty array, and this is perfectly normal, because this is an empty collection, therefore no `A` are tried to be instantiated.
- `$normalizer->denormalize([], A::class)` will throw a `MissingConstructorArgumentException`, because we try to instantiate a `A` without the required argument.
- `$normalizer->denormalize([[]], ExampleObject58367::class.'[]')` will throw a `MissingConstructorArgumentException`, because when we try to instantiate the first element of the list, it misses the required argument.

Do I miss something?

**Comment by xabbuh** [comment]
Closing here as per the explanations from https://github.com/symfony/symfony/issues/58367#issuecomment-2437702780. Thank you for understanding.

If you disagree though please feel free to comment and we can consider to reopen.

**Comment by tombohub** [comment]
@xabbuh any other language gives error when deserializing `{}` or `[{}]`. Accepted is half baked argument.

@mtarld yes, you are missing `{}` and `[{}]`.  You gave examples only for `[]` and `[[]]`

**Comment by mtarld** [comment]
@tombohub, I don't understand what "silently fails" mean to you.

According to my tests, everything behaves as expected:
```php
$serializer = new Serializer([new ObjectNormalizer(), new ArrayDenormalizer()], [new JsonEncoder()]);

// This is perfectly normal, because this is an empty collection, therefore no A are tried to be instantiated.
$this->assertSame([], $serializer->deserialize('[]', A::class.'[]', 'json'));

// This is perfectly normal, because this is an empty object, which can be considered as an empty collection
$this->assertSame([], $serializer->deserialize('{}', A::class.'[]', 'json'));

try {
    $serializer->deserialize('[{}]', A::class.'[]', 'json');
    $this->fail('MissingConstructorArgumentsExcept must be thrown');
} catch (MissingConstructorArgumentsException) {
    // An exception must be thrown because when we try to instantiate
    // the first element of the list, it misses the required argument.
    $this->addToAssertionCount(1);
}
```

**Comment by tombohub** [comment]
@mtarld `{}` cannot be considered empty collection for deserializing. This is an error. `{}` cannot be deserialized into an php array. `{}` is an empty object, not empty collection. How many times have ever somebody deserialized single object and got an array and said "It's ok. Array will do."? 

If `{}` is an empty collection what is `{"name": "koko"}`? Is it a full collection? If it's only a single object then how can `{}` be an empty collection with less information then `{"name": "koko"}`? Some string with less information becomes more encompassing than string with more information. That means json `{}` === `[{}]`. 

@xabbuh This is what needs to be:

1. `[]` -> warning, nobody wants empty collection when deserializing
2. `[{}]` -> warning, same thing, gives error now, even better
3. `[{}]` -> with `REQUIRE_ALL_PROPERTIES` -> Error, doesn't have required properties
4. `{}` -> Error, json not deserializable into an array of objects.

**Comment by mtarld** [comment]
> [] -> warning, nobody wants empty collection when deserializing

IMHO no warning is needed here, as we cannot control all the time what we are going to deserialize 

> [{}] -> warning, same thing, gives error now, even better

This should fail the same way as `{}` fails for `A::class`

> [{}] -> with REQUIRE_ALL_PROPERTIES -> Error, doesn't have required properties

This should fail the same way as `{}` fails for `A::class`

> {} -> Error, json not deserializable into an array of objects.

Agreed! :slightly_smiling_face:  This must fail the same way as if we've had deserialized `true`, `'foo'` or 16
