### ISSUE TITLE
SendgridRequestParser converts only the first event on the webhook 

### ISSUE THREAD

**Issue by salvatorepandolfi** [symfony/symfony#58398]
### Symfony version(s) affected

7.x

### Description

When send grid pack more than one events in a webhook request, the parser only takes the first one and ignore the others.
Apparently the events are always connected to the same message id, but what happen if the first action listed is not the one more meaningful?
For instance, if I want to track down the open actions and this is not the first one on the packed list of action received in a request, I'll lose the sensitive information.

### How to reproduce

Go to the https://app.sendgrid.com/settings/mail_settings/webhook_settings
create a new event webhook
click on test integration button

### Possible Solution

return an array of AbstractMailerEvent instead of a single event

**Comment by stof** [comment]
there is an in-progress work at https://github.com/symfony/symfony/pull/58248 to allow parsing multiple remote events from a webbook payload.
