### ISSUE TITLE
symfony/telegram-notifier sends always notification

### ISSUE THREAD

**Issue by haivala** [symfony/symfony#58436]
### Symfony version(s) affected

6.4.12

### Description

Setting
```
        $telegramOptions = (new TelegramOptions())
            ->parseMode('HTML')
            ->disableWebPagePreview(true)
            ->disableNotification(true);
```
Does not have any effect. It always sends notification to everybody in the channel.

### How to reproduce

Setting
```
        $telegramOptions = (new TelegramOptions())
            ->parseMode('HTML')
            ->disableWebPagePreview(true)
            ->disableNotification(true);
```
and sending message and see if you got a notification.

**Comment by haivala** [comment]
Ok the documentation is not clear what does it mean to "not send notification" This is from telegram docs:
> Sends the message [silently](https://telegram.org/blog/channels-2-0#silent-messages). Users will receive a notification with no sound.

**Comment by nicolas-grekas** [comment]
This could have been named `silentNotification` I guess.
Can you please send a PR to the doc to improve it?
