### ISSUE TITLE
[HttpClient] Support closures and `Stringable` in header options

### ISSUE THREAD

**Issue by cdaguerre** [symfony/symfony#58439]
### Description

It would be great if the HttpClient could accept closures and/or `Stringable` arguments that are evaluated when the request is created / sent. See below for an example use case.
If it sounds reasonable I can open a PR for this.

### Example

```php
public function __construct(HttpClientInterface $httpClient, string $uri, string $apiKey, string $secret)
{
    $this->httpClient = $httpClient->withOptions([
        'base_uri' => $uri,
        'headers' => [
            'X-Signature' => fn() => hash('sha256', $apiKey.$secret.time()),
         ]
    ]);
}
```

**Comment by nicolas-grekas** [comment]
I fear this might be hard to implement: headers are stored in a normalized format, which means the closure would be resolved immediately.

You might try writing a decorating http-client instead, that'd compute these dynamic headers in the request method. (use DecoratorTrait to help.

**Comment by cdaguerre** [comment]
Thanks for the quick response @nicolas-grekas 
Actually header normalization already supports Stringable [here](https://github.com/symfony/symfony/blob/24f9ef809a91c4ac7772510a891e87f61ff955a8/src/Symfony/Component/HttpClient/HttpClientTrait.php#L284).
Don't you think that moving string casting to the [`prepareRequest` method](https://github.com/symfony/symfony/blob/24f9ef809a91c4ac7772510a891e87f61ff955a8/src/Symfony/Component/HttpClient/HttpClientTrait.php#L189) would be enough ?
Something by the lines of:

```php
foreach ($options['headers'] as $header => $values) {
    if ($values instanceof \Stringable) {
        $options['headers'][$header] = (string) $values;
    }
}

**Comment by stof** [comment]
normalized headers have to be strings due to the way they are used. And changing that could also be a BC break for custom clients btw.

**Comment by cdaguerre** [comment]
Alright, it's more a DX related thing than a limitation and decoration is fine, even if it requires extra boilerplate for little complexity. 
I'm not sure why this would be a BC break and it's not really documented that headers are stringable.
Also, passing a Closure as header causes a segfault (which might be related to "the way they are used" @stof ?), if you want I can open a PR checking that the argument is NOT a closure to improve DX in that case if you like.

**Comment by nicolas-grekas** [comment]
I thought this RFC was about just-in-time evaluation of headers, where closures passed to "withOptions" would be evaluated later. That part is likely hard.
If the point is not lazy-evaluation, then there's no use case accepting closures.
Then, if something segfaults, it should be prevented :)

**Comment by stof** [comment]
@cdaguerre the BC break would be that `normalized_headers` would not be containing strings anymore, which changes the type received by inner clients during decoration.

**Comment by cdaguerre** [comment]
You're right @nicolas-grekas, thats what the RFC is actually about and I believe it's a valid use case (typically for time based authentication signatures in long running processes, etc.).
I don't really see why it would be hard to implement but I'm probably missing something.
As for the BC part: I don't really think we would be breaking anything because I don't think there are any "inner" client implementations [out there](https://packagist.org/providers/symfony/http-client-implementation) (but you never know). If there are any, they would probably be using the `HttpClientTrait` which would "carry" contain the changes anyway... don't you think @stof ?

I opened a PR to improve DX and explicitely prevent passing closures for now.

**Comment by nicolas-grekas** [comment]
I think a decorating HTTP client that adds the dynamic headers in the request method would be the best approach.
Let me close here :)

**Comment by cdaguerre** [comment]
Alright, thanks for your time!
Sorry for the confusion, still haven't figured out where the segfault actually comes from...
