### ISSUE TITLE
Class not found when using autoloader

### ISSUE THREAD

**Issue by barchard** [symfony/symfony#58438]
### Symfony version(s) affected

6.4.11

### Description

Due to this global value wrapper, I'm receiving a run-time error when trying to use the cache.

### How to reproduce

Setting the expiration, causing the crash. If this expiration is omitted, the code works as normal.

```
$this->getCache()->get(md5($this->url), function (ItemInterface $item): string {
    $item->expiresAfter(15);
    return '';
});
```

### Possible Solution

Use a name-space class instead

### Additional Context

```
Uncaught Error: Class "�" not found in /path/vendor/symfony/cache/CacheItem.php:172
Stack trace:
#0 /path/vendor/symfony/cache/Adapter/AbstractAdapter.php(74): Symfony\Component\Cache\CacheItem-&gt;pack()
#1 /path/vendor/symfony/cache/Adapter/AbstractAdapter.php(134): 
...
```

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by barchard** [comment]
I'm having trouble reproducing it via a simple `composer` script, but I did notice something. As this class name is unicode, it is not being exported, uploaded or something properly. Please see the two screenshots attached. One from the package installed via composer and one uploaded via FTP to dev. Is there a reason why a unicode character was used? 

![CleanShot 2024-10-04 at 21 05 17@2x](https://github.com/user-attachments/assets/91fdf6c1-4868-4ce5-b49a-494c142f8cb5)
![CleanShot 2024-10-04 at 21 04 57@2x](https://github.com/user-attachments/assets/933c1925-1f47-44fc-be28-3213f35d3662)

**Comment by xabbuh** [comment]
Let's close here then as this is not a bug in the Symfony codebase but something that you need to fix in your deployment. Thank you for understanding.
