### ISSUE TITLE
Add option to prevent pre-filling translations

### ISSUE THREAD

**Issue by jawira** [symfony/symfony#58451]
### Description

Hello Symfony Team. I'm working on a Symfony project where we manage our translations using the `translation:extract` command, and our team uses Weblate to handle the actual translation process. However, we’ve encountered an issue when extracting translation strings. The command currently pre-fills the `<target>` tags with the source message, and this slows down our translation workflow.

When the `translation:extract` command is executed, the `<target>` tags are automatically populated with the same values as the `<source>` tags. For example:

```xml
<trans-unit id="haoBXCQ" resname="inventory.item_status.missing">
    <source>inventory.item_status.missing</source>
    <target>inventory.item_status.missing</target>
</trans-unit>
```

This behavior causes Weblate to consider the string is already translated, which slows down our translation team workflow. Ideally, the `<target>` tags should be empty when the translation file is updated, so Weblate can identify that the strings still require translation.

### Example

It would be incredibly helpful if the `translation:extract` command could offer an additional option (e.g., `--no-fill` or `--empty-target`). This option would prevent the command from automatically filling the `<target>`, leaving them empty by default. For example:

```console
bin/console translation:extract --force --prefix="" --no-fill fr
```

```xml
<trans-unit id="haoBXCQ" resname="inventory.item_status.missing">
    <source>inventory.item_status.missing</source>
    <target></target>
</trans-unit>
```

This would help us better integrate Symfony's translation system with Weblate (and potentially other translation management tools) that rely on empty <target> tags to detect untranslated strings.

Thank you for considering this feature request :)

**Comment by stof** [comment]
This looks like a legitimate use case.

@jawira do you want to contribute to implement this ?

**Comment by jawira** [comment]
@stof yes, I would be happy to implement this option :) 
Could you provide me with some pointers or suggestions on how to approach it? Any advice would be really helpful.

**Comment by stof** [comment]
To make it compatible with existing extractors without changes, I would suggest that the `--no-fill` option (or whatever its final name will be) makes the command configure the extractor to use a special prefix (like `"\0extracted\0"` which is very unlikely to appear at the beginning of actual messages thanks to the NUL bytes) and then clean the extracted catalogue by replacing any message starting with this prefix with an empty string.

**Comment by jawira** [comment]
Ok got it, I will provide a PR soon.
