### ISSUE TITLE
[ErrorHandler] DebugClassLoader triggers deprecations for "final" problem in vendors

### ISSUE THREAD

**Issue by nikophil** [symfony/symfony#58463]
### Symfony version(s) affected

all

### Description

Hello,

if a vendor class has a problem towards a wrong internal usage of `@final`, an error `E_USER_DEPRECATED` will be triggered with the message

> User Deprecated: The "Vendor\SomeClass::method()" method is considered final. It may change without further notice as of its next major version. You should not extend it from "Vendor\SomeOtherClass".

I think this should not occur, because the problem has to be fixed upstream, I wanted to be sure that this is a bug and not the desired behavior before providing a fix.

### How to reproduce

load a class from vendors which has a method which overrides another method marked as `@final`

### Possible Solution

`DebugClassLoader` should not trigger deprecations for classes which come from another vendor.

I'm not sure how to guess a file is in a vendor, though :thinking: just checking if the class is in a file located in `vendor` directory is an easy pick, but this directory can be configured in Composer... any thought?

**Comment by nicolas-grekas** [comment]
This is definitely a problem with the vendor. Try sending them a PR.

**Comment by nikophil** [comment]
Yes of course, but it feels weird that vendor classes are validated as well as userland classes

**Comment by nicolas-grekas** [comment]
I'm closing as won't fix, vendor issue, we're just turning the light on here.
