### ISSUE TITLE
[Notifier] Support LINE Messaging API bridge

### ISSUE THREAD

**Issue by pan93412** [symfony/symfony#58474]
### Description

[LINE Notify](https://notify-bot.line.me/closing-announce) has been discontinued by LINE and will soon be removed.

The recommended replacement is the [LINE Messaging API](https://developers.line.biz/en/docs/messaging-api/sending-messages/#reply-messages), which offers greater functionality. It’s advisable to transition to this API as the replacement for LINE Notify.

Keep in mind that the LINE Messaging API provides far more capabilities compared to LINE Notify, allowing us to potentially support additional Notification properties, rather than being limited to just subject.

Related: https://github.com/symfony/symfony/pull/48466

### Example

https://github.com/line/line-bot-sdk-php?tab=readme-ov-file#call-api
https://github.com/line/line-bot-sdk-php/blob/master/examples/EchoBot/src/LINEBot/EchoBot/Route.php

**Comment by fabpot** [comment]
Do you want to work on the replacement?

**Comment by pan93412** [comment]
> Do you want to work on the replacement?

I haven't tried the LINE Messaging API. I may take over this issue if I have tried and is familiar with this API.

**Comment by fabpot** [comment]
@kurozumi Maybe you can help as well?

**Comment by pan93412** [comment]
@fabpot I am currently working on a prototype. Hopefully it can be done today.

**Comment by pan93412** [comment]
I have implemented the LINE Bot bridge. You can review here: https://github.com/symfony/symfony/pull/58527
