### ISSUE TITLE
Directory name is invalid on clear chace

### ISSUE THREAD

**Issue by DIOHz0r** [symfony/symfony#58480]
### Symfony version(s) affected

7.1.1

### Description

I'm getting this message after running a composer command.

...
Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  The directory name is invalid.
!!
Script @auto-scripts was called via post-update-cmd

### How to reproduce

1. Start a new project

>  symfony new test-app --api

2. Install package symfony/test-pack

> composer require test

### Additional Context

PHP 8.3.8 (cli) (built: Jun  4 2024 18:52:26) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans

**Comment by xabbuh** [comment]
What output do you get when running `bin/console cache:clear -vvv`?

**Comment by DIOHz0r** [comment]
bin/console works ok but if I do a `composer update -vvv` this is the output 

```
Looking at all rules.
Something's changed, looking at all rules again (pass #1)
Dependency resolution completed in 0.003 seconds
Analyzed 520 packages to resolve dependencies
Analyzed 2338 rules to resolve dependencies
Nothing to modify in lock file
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Installing dependencies from lock file (including require-dev)
> pre-operations-exec: Symfony\Flex\Flex->recordOperations
Nothing to install, update or remove
Generating autoload files
> post-autoload-dump: Symfony\Component\Runtime\Internal\ComposerPlugin->updateAutoloadFile
90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-update-cmd: Symfony\Flex\Flex->update

Run composer recipes at any time to see the status of your Symfony recipes.

> post-update-cmd: PHPCSStandards\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->onDependenciesChangedEvent
Running PHPCodeSniffer Composer Installer
PHPCodeSniffer Composer Installer is uninstalled
> post-update-cmd: @auto-scripts
> auto-scripts: Symfony\Flex\Flex->executeAutoScripts
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 1
!!  The directory name is invalid.
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by xabbuh** [comment]
I am afraid you will need to somehow debug what's the actual directory name the script is failing with. At least I cannot reproduce the behaviour by running the two commands from the issue description.

**Comment by DIOHz0r** [comment]
The issue was with the PHP installation, which got broken during some upgrades, sorry for the wrong report.
