### ISSUE TITLE
[HttpClient] Stream throws exception

### ISSUE THREAD

**Issue by nacholibre** [symfony/symfony#58498]
### Symfony version(s) affected

5.4.16

### Description

First of all, thanks for your work on Symfony, it's a great tool and your efforts are much appriciated!

`symfony/http-client` version is 5.4.16

`HttpClientInterface::stream()` sometimes throws exceptions, but according to the documentation it should not.

### How to reproduce

It's pretty hard to reproduce this, my app runs through a list of urls and fetches them concurrently (3 urls is the concurrency level)

Stacktrace:
```
{
    "class": "Symfony\\Component\\HttpClient\\Exception\\TransportException",
    "message": "CONNECT tunnel failed, response 503 for \"[https://xxxx\](https://xxxx)".",
    "code": 0,
    "file": "/www/sites/xx/vendor/symfony/http-client/Chunk/ErrorChunk.php:65",
    "trace": [
        "/www/sites/xx/vendor/symfony/http-client/Response/CommonResponseTrait.php:154",
        "/www/sites/xx/vendor/symfony/http-client/Response/TransportResponseTrait.php:53",
        "/www/sites/xx/vendor/symfony/http-client/Response/AsyncResponse.php:263",
        "/www/sites/xx/vendor/symfony/http-client/Response/ResponseStream.php:42",
        "/www/sites/xx/src/Service/SomeService.php:213",
```

On line 213 in `SomeService` I have
```php
        // ..
        foreach($urls as $url) {
            $responses[] = $this->httpClientRequest($url); // this returns basic $this->httpClient->request('GET'....;
        }

        foreach($this->httpClient->stream($responses) as $response => $chunk) { # <<<< line 213
        // ..
```

**Comment by xabbuh** [comment]
5.4.16 is nearly two years old (released in November 2022). Do you experience the same with the latest patch release (which is 5.4.44)?

**Comment by nicolas-grekas** [comment]
Note that I don't see any bug here. Your proxy answers with a failure. You can deal with it, or let the exception bubble down like now. It's on you. The doc should tell about how to handle errors.

**Comment by nacholibre** [comment]
@nicolas-grekas maybe `throw` should be added to the phpdoc of the interface method?

Now it looks like this:
```php
    /**
     * Yields responses chunk by chunk as they complete.
     *
     * @param ResponseInterface|iterable<array-key, ResponseInterface> $responses One or more responses created by the current HTTP client
     * @param float|null                                               $timeout   The idle timeout before yielding timeout chunks
     */
    public function stream($responses, float $timeout = null): ResponseStreamInterface;
```

**Comment by nicolas-grekas** [comment]
stream() doesn't throw. The line that throws is a foreach. What throws are the methods of the iterator returned by stream(). This is documented IIRC.
