### ISSUE TITLE
[Doctrine][Messenger] Fix Identity columns not supported by Oracle driver

### ISSUE THREAD

**Issue by devloop42** [symfony/symfony#58504]
### Symfony version(s) affected

6.4.12

### Description

**Error Message**
IdentityColumnsNotSupported > DriverException > TransportException : An exception occurred in the driver: The driver does not support identity columns.

**Context**
Usage of async symfony/messenger with doctrine as transport

**Explanation**

When dealing with an Oracle database, the dispatched message is well inserted into the database but an exception is encountered when trying to get the last inserted id. That exception lead to a **rollback** and therefore a failing process of queing the messages.
IDs are generated with sequence instead of identity column as you have it with MySQL database for exemple.
A specific treatment is needed as done for PostgreSQL database

### How to reproduce

**Environment**
- PHP 8.3
- Symfony 6.4.12
- OS : Windows
- DB : Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0
- Extensions: oci_8_19, ...

**How to reproduce**
1. Set up a project

- Create a symfony web project
- Create a Controller/route to use as test

2. Check symfony/messenger works well as sync

- Install symfony/messenger if not installed
- Create a message and it's handler and test the dispatch and execution of the hander

3. Test symfony/messenger works well as **async**
- Install symfony/doctrine-messenger
- Set the process as async

When testing the async process, the error should appear as the message can't be recorded into the database

[Stack-Traces.txt](https://github.com/user-attachments/files/17299722/stack-traces.txt)

### Possible Solution

Target the OraclePlatform to get the last inserted id as needed for that database :

```
...
    elseif ($this->driverConnection->getDatabasePlatform() instanceof OraclePlatform) {
          $sequenceName = strtoupper($this->configuration['table_name'].'_seq');

          $this->driverConnection->executeStatement($sql, $parameters, $types);
                
          $result = $this->driverConnection->fetchOne('select last_number from user_sequences where sequence_name = \''.$sequenceName.'\'');

          $id = (int) $result;

          if (!$id) {
              throw new TransportException('no id was found in Oracle for sequence: '.$sequenceName);
          }
    }
...
```

_Important_ :
- On GitHub, for the [6.4.x](https://github.com/symfony/doctrine-messenger/blob/6.4/Transport/Connection.php) version, a solution is implemented but doesn't work and produce an error (ORA-02289). Should be adapted as shown above
  - Maybe it is in beta as the deployed version on my machine doesn't have that elseif block !
- Fix should also be ported to symfony/doctrine-messenger 7.1.x

**Comment by xabbuh** [comment]
#54566 does not (fully) solve this. Do I understand that correctly?

**Comment by xabbuh** [comment]
@rjd22 FYI

**Comment by rjd22** [comment]
@xabbuh I don't have a very new Oracle version to test this on. But I would say unless they deprecated something my solution should solve this.

Honestly using the user_sequences table to get the last id sounds like something that is not portable between different Oracle versions.

Edit: checked but my changes are not yet in 6.12

**Comment by devloop42** [comment]
> #54566 does not (fully) solve this. Do I understand that correctly?

@xabbuh : Yes. It doesn't solve the issue. Generated sequences always end with _seq (in my case anyway and if size not limited by config). And the request to get the ID ('_SELECT '.$sequenceName.'.CURRVAL FROM DUAL_') throws ORA-08002 error.

@rjd22 : I do agree. Using the user_sequences table is pretty ugly but I don't have a better solution as _sequenceName.**currval**_ is not supported.

**Comment by rjd22** [comment]
Well I would recommend doing some extended research what the new official way of getting currval is so I can check backwards compatibility. I cannot imagine it's using the user_sequences table.

I don't have access to your Oracle version so I cannot do the research myself.

**Comment by devloop42** [comment]
My bad. _**'SELECT '.$sequenceName.'.CURRVAL FROM DUAL'**_ works like a charm 👍 . I was testing that request outside the current session.

**Comment by devloop42** [comment]
For the sequence name, the auto_setup create it by adding the suffix **_seq** to the table name. And so far, all generated sequences by doctrine have been set that way. Is there a reason for forcing it as prefix to the table name ?

**Comment by rjd22** [comment]
No reason except that prefixed sequences are an old Oracle default I fell back on. It might have changed in the years.

Edit: I have no strong feelings about the prefixing or suffixing so if feel it's better to change it you're free to make an PR.

**Comment by devloop42** [comment]
@rjd22, @xabbuh  : It's advised to not submit the PR on symfony/doctrine-messenger but on symfony/symfony instead.
But that repo is not proposed as base repository ... What am I missing 😶?

**Comment by xabbuh** [comment]
You need to fork the symfony/symfony repository and make the changes in that fork not in your fork of the symfony/doctrine-messenger repository.
