### ISSUE TITLE
[Notifier][Firebase] Deprecated endpoint

### ISSUE THREAD

**Issue by valeriy-efimov** [symfony/symfony#58543]
### Symfony version(s) affected

6.4.10

### Description

Hello!
My project uses symfony/firebase-notifier but as far as I understand google has changed the API. And now this package doesn't work. Api return error "Deprecated endpoint".
But firebase-notifier is still not updated. 
![image](https://github.com/user-attachments/assets/04898289-1653-4330-b46c-c9c4728928e0)
https://firebase.google.com/docs/cloud-messaging/migrate-v1

What to do?

### How to reproduce

```
        $chatMessage = new ChatMessage(
            $message,
            new WebNotification($deviceToken, $options, $customData),
        );

        $this->chatter->send($chatMessage);
  
```

**Comment by xabbuh** [comment]
I am closing here as we already have an issue about this (see #51147). Thank you for understanding.
