### ISSUE TITLE
[Serializer] BC break after automatic addition of default groups

### ISSUE THREAD

**Issue by stollr** [symfony/symfony#58576]
### Symfony version(s) affected

7.1

### Description

This [PR](https://github.com/symfony/symfony/pull/51514) introduced a BC break in 7.1, which can be very problematic.

I used class names as regular groups, before 7.1 and now, properties get serialized, which weren't serialized, before.

### How to reproduce

Example:
```php
class User {
    #[Groups(['CurrentUser'])]
    public string $name;
    #[Groups(['CurrentUser'])]
    public Membership $membership;
}

class Membership {
    #[Groups(['Membership'])]
    public string $privateKey;
    #[Groups(['CurrentUser', 'Membership'])]
    public string $name;
}

$user = $userRepository->findOneBy(['id' => '...']);
$serializer->normalize($user, 'json', ['groups' => ['CurrentUser']]);
```

In PHP 7.1 the `privateKey` property will get normalized, although I have changed nothing. This can be a **security issue**, because unprevileged users may see data which was not intended for them.

I just became aware of this, because of my automatic tests.

### Possible Solution

I'd prefer to see this PR to be reverted, but I guess this won't happen. Maybe an option could be introduced to disable the addition of those magic groups.

**Comment by Seldaek** [comment]
Related to #57350

**Comment by Seldaek** [comment]
Maybe a solution to remove the risky BC break would be to set `Membership.Default` (i.e. `ClassName.Default`) + `Default` as default groups on properties, so if you want to target using the class name you can do it but you need `.Default` still.

cc @mtarld

**Comment by stollr** [comment]
Isn't it enough to just use the `Default` group for this behaviour? What is the advantage of having two ways to make properties serialize always?

**Comment by Seldaek** [comment]
I assume the intent was that if you have a graph of objects, this gives you an easy way to use the class names as group names to serialize default properties of class A and B but not C or D if you pass `['A.Default', 'B.Default', 'read']` as serialization group for example. At least I can see value in that, but not sure if that's the only thing.

**Comment by stollr** [comment]
That would make sense. But then the current implementation is buggy. If you look at my example, you'll notice that i have passed "CurrentUser" as group and still "privateKey" was serialized.

**Comment by mtarld** [comment]
Thanks, @Seldaek, for pinging me :slightly_smiling_face: 

Actually, the aim of the `Default` group is to serialize a property no matter if zero, or many groups are provided. Let's say we have the following properties
```php
class MyClass
{
	public string $noGroup;
	
	#[Groups('custom')]
	public string $customGroup;
	
	#[Groups('Default')]
	public string $defaultGroup;
	
	#[Groups('MyClass')]
	public string $classGroup;
}
```
- `$noGroup` will be serialized only if groups are `[]`
- `$customGroup` will be serialized if groups are `[]` or `['custom']`
- `$defaultGroup` will be serialized no matter the groups provided, such as `[]`, `['custom']`, `['Default']` or `['whatever']`
- `$classGroup` will as well be serialized no matter the groups provided **as soon as the serialized class is MyClass**

That's being said, I agree that it can cause issue if such convention was already introduced in projects.
Therefore, IMO, we should introduce a context value, such as `ENABLE_DEFAULT_GROUPS`, defaulting to `false` in 7.x and defaulting to `true` in 8.x (with a gentle forward compatibility path).

WDYT?

**Comment by Seldaek** [comment]
I'm still kinda confused, by adding `#[Groups('Default')]` you are saying "this is ALWAYS serialized", but by default a property without group is... only serialized if no groups are chosen? 

What about if you serialize with groups `['Default']` could you edit your post above to add that case to the various use cases for clarity? And can you also include examples with the classname because it's not clear to me how it behaves/when it's used.

But yes making this optional sounds safer for BC as this issue highlights this can have fairly tricky consequences.

**Comment by stollr** [comment]
I have another idea to mark those "magic" groups. We could prepend them with `$`. This is good for BC and at the same time it shows that these are special groups.

**Comment by mtarld** [comment]
> I'm still kinda confused, by adding #[Groups('Default')] you are saying "this is ALWAYS serialized", but by default a property without group is... only serialized if no groups are chosen?

Exactly, a property without group is only serialized if no group has been provided in the context. That's why `Default` has been introduced: serializing a property, no matter the groups given in the context.

These can be compared to validation groups of the validator component.

`Default`, and `MyClass` groups are not means to be given in context, but rather only defined on top of attributes.

**Comment by mtarld** [comment]
> I have another idea to mark those "magic" groups. We could prepend them with $. This is good for BC and at the same time it shows that these are special groups.

In my opinion, I'd keep the same syntax as the validator component to be consistent across Symfony components.
Plus, these groups have been introduced in 7.1, and changing their names could be result in a BC break for other people, so the context value might be the less harming choice here.

**Comment by stollr** [comment]
At the current state the same syntax as in the validator component is used, **but another logic**. And this is the most confusing. Please have a look at https://symfony.com/doc/current/validation/groups.html.

> With this configuration, there are three validation groups:
> 
> `Default`
>     Contains the constraints in the current class and all referenced classes that belong to no other group. In this example, it only contains the city field. 
> `User`
>     Equivalent to all constraints of the User object in the Default group. This is always the name of the class. The difference between this and Default is explained in How to Sequentially Apply Validation Groups. 
> `registration`
>     This is a custom validation group, so it only contains the constraints that are explicitly associated with it. In this example, only the email and password fields. 
> 
> Constraints in the `Default` group of a class are the constraints that have either **no** explicit group configured or that are configured to a group equal to the class name or the string Default.

Considering your example

* `$noGroup` should be serialized if groups are `[]`, `['Default']` or `['MyClass']`
* `$customGroup` should be serialized only if groups contain `['custom']`
* `$defaultGroup` should  be serialized in the same cases as `$noGroup`
* `$classGroup` should be serialized if groups contain `['MyClass']` only

So please use another syntax or use the same logic. Anything else is a no go, imho.

**Comment by mtarld** [comment]
You're right @stollr, I'll try to submit a fix to have the same logic as the validator, and making it opt-in, thanks!

**Comment by stollr** [comment]
That would be great. Thank you 🙂

**Comment by Gog0** [comment]
@mtarld is it still a subject you plan to work on ? I'm interested in this feature as it would be very convenient in some cases. I'd be happy to help or work on a PR myself if necessary.
