### ISSUE TITLE
[Voter] Attribute of type `Expression` prevents some `Voter` to be cached

### ISSUE THREAD

**Issue by elementaire** [symfony/symfony#58588]
### Symfony version(s) affected

v5.4.0-BETA1 and later

### Description

We use the `unanimous` strategy for our `access_decision_manager`.

Our issue is all our custom `Voter` extending `CacheableVoterInterface` can not be aware if the attribute is an `Expression`.

Because of the method signature `public function supportsAttribute(string $attribute): bool;` in the interface `CacheableVoterInterface`, `AccessDecisionManager` bypasss the call and assumes it supports, meaning the voter must vote.

So, we have a lot of Voter checking if the attribute is an `Expression` in our implementation of `public function vote(TokenInterface $token, mixed $subject, array $attributes): int;` from `VoterInterface` and always abstains.

(Some are called because `supportsType` return `true`.)

**I think it breaks the purpose of caching.**

And it breaks the contract "By returning false to either `supportsAttribute` or `supportsType`, the voter will never be called for the specified attribute or subject." of `CacheableVoterInterface` because `supportsAttribute` is never called.

Friendly notification @jderusse because it is around your code.

### How to reproduce

1. Get the reproducer:

```
$ git clone git@github.com:elementaire/symfony-voter-reproducer.git
$ cd symfony-voter-reproducer
$ composer install
$ symfony server:start
```
2. Open your browser and navigate to the url given by the command.
3. Open the `Symfony Profiler`, `Security` tab.
4. Open the `Access Decision` tab and click on `Show voter details`.
5. See `FooVoter` ([see file](https://github.com/elementaire/symfony-voter-reproducer/blob/main/src/Service/Security/Voter/FooVoter.php)) being called despite it supports only `ROLE_FOO` attribute.

![image](https://github.com/user-attachments/assets/7f619cbb-52c7-4207-91e1-9399868bfad3)

### Possible Solution

Adapt `AccessDecisionManager::getVoters` method to call `supportsAttribute` if the `attribute` can be `stringify` (have method `__toString` like `Expression` has, is an integer, etc.).

Dirty example (i did not handle all cases (scalar mostly)):

```php
    private function getVoters(array $attributes, $object = null): iterable
    {
// REMOVED
//        $keyAttributes = [];
//        foreach ($attributes as $attribute) {
//            $keyAttributes[] = \is_string($attribute) ? $attribute : null;
//        }
// END REMOVED
        // use `get_class` to handle anonymous classes
        $keyObject = \is_object($object) ? $object::class : get_debug_type($object);
        foreach ($this->voters as $key => $voter) {
            if (!$voter instanceof CacheableVoterInterface) {
                yield $voter;
                continue;
            }

            $supports = true;
            // The voter supports the attributes if it supports at least one attribute of the list

// REPLACED $keyAttributes by $attributes
            foreach ($attributes as $keyAttribute) {
// ADDED
                if ($keyAttribute instanceof Expression && $voter instanceof ExpressionVoter || ($voter instanceof TraceableVoter && $voter->getDecoratedVoter() instanceof ExpressionVoter)) {
                    $keyAttribute = null;
                } else {
                    $keyAttribute = \is_string($keyAttribute) ? $keyAttribute : ($keyAttribute instanceof \Stringable ? (string) $keyAttribute : null);
                }
// END ADDED

                if (null === $keyAttribute) {
                    $supports = true;
                } elseif (!isset($this->votersCacheAttributes[$keyAttribute][$key])) {
                    $this->votersCacheAttributes[$keyAttribute][$key] = $supports = $voter->supportsAttribute($keyAttribute);
                } else {
                    $supports = $this->votersCacheAttributes[$keyAttribute][$key];
                }
                if ($supports) {
                    break;
                }
            }
            if (!$supports) {
                continue;
            }

            if (!isset($this->votersCacheObject[$keyObject][$key])) {
                $this->votersCacheObject[$keyObject][$key] = $supports = $voter->supportsType($keyObject);
            } else {
                $supports = $this->votersCacheObject[$keyObject][$key];
            }
            if (!$supports) {
                continue;
            }
            yield $voter;
        }
    }
```

Additionally, it fixes `RoleVoter` and `AuthenticatedVoter` which always abstain.

![image](https://github.com/user-attachments/assets/fd0cda8d-f96a-40d2-a4d7-2cc75a1fe9f5)

**Comment by stof** [comment]
Stringifying the expression is not the solution, because it means that voting would happen on a **different** attribute

**Comment by stof** [comment]
And hardcoding a special case for Expression and ExpressionVoter in this code is not a solution either (other custom voters are also able to support non-string attributes)

**Comment by elementaire** [comment]
I agree with both your comments. Finally, i am understanding the method `supportsAttribute` is misnamed.

It is not related to the `Voter` itself (because `vote` can be called with other attribute) but it refers to be cacheable only.

And we have not any mechanism to prevent `Voter` to be called, have we?
