### ISSUE TITLE
An exception has been thrown during the rendering of a template ("array_reduce(): Argument #1 ($array) must be of type array, Symfony\Component\VarDumper\Cloner\Data given").

### ISSUE THREAD

**Issue by soyUnaGata** [symfony/symfony#58586]
### Symfony version(s) affected

6.4 and 7.1

### Description

Hello! I just faced an issue when updating from Symfony 5 to 6.4. I also tried updating to version 7.1, but it didn't fix the problem.

![image](https://github.com/user-attachments/assets/6ac7f8db-2d80-4016-a8b9-547bfa48cef9)
![image](https://github.com/user-attachments/assets/96a16c4e-c5e4-4f80-a1a5-3e14f11d12c1)

I encounter this issue in the profiler when trying to view the Logs section.
Versions of the tools:
"symfony/web-profiler-bundle": "6.4.11"
 "symfony/debug-bundle": "6.4.8"

### How to reproduce

Go to profiler and try to open Logs sections.
Other sections works good.

### Possible Solution

When I'm changing this in template   {% set compilerLogTotal = collector.compilerLogs|reduce((total, logs) => total + logs|length, 0) %}
to this 
   {% set compilerLogTotal = 0 %}
 {% set compilerLogCount = collector.compilerLogs|length %}
 It's become working, but I'm not sure that it's correct.

### Additional Context

If you need any additional information, please let me know.
It's my first update ever, so thank you in advance.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by soyUnaGata** [comment]
> Can you create a small example application that allows to reproduce your issue?

Hello! I'm so sorry, but in empty (only one controller and twig template) I also tried to add some date, it's working. 
So maybe it's because of other packages 😔
Sorry, for wasting your time

**Comment by alexandre-daubois** [comment]
Can you close the issue as solved if it's now ok for you please? 🙂
