### ISSUE TITLE
Profiler's form page crashes when form types uses nested options

### ISSUE THREAD

**Issue by 7-zete-7** [symfony/symfony#58665]
### Symfony version(s) affected

6.4.12

### Description

When using nested options with in depth normalisation in a form, the following profiler error occurs:
> An exception has been thrown during the rendering of a template ("Notice: Object of class Symfony\Component\VarDumper\Cloner\Data could not be converted to int").

The traceback error occurs in `vendor/symfony/web-profiler-bundle/Resources/views/Collector/form.html.twig:651`, but I could not find an obvious reason for this error.

### How to reproduce

Reproducer: https://github.com/7-zete-7/symfony-form-profiler-reproducer-1

**Comment by vltrof** [comment]
Greetings! 
Kinda new in OSS, maybe doing something wrong 

But I have done some investigation
Seems like problem in type comparing

```php
{% for option, value in data.passed_options %}
                <tr>
                    <th>{{ option }}</th>
                    <td>{{ profiler_dump(value) }}</td>
                    <td>
                        {# values can be stubs #}
                        {% set option_value = value.value|default(value) %}
                        {% set resolved_option_value = data.resolved_options[option].value|default(data.resolved_options[option]) %}
                        {% if resolved_option_value == option_value %}
                            <em class="font-normal text-muted">same as passed value</em>
                        {% else %}
                            {{ profiler_dump(data.resolved_options.seek(option)) }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
 ```

After replacing comparing with twig function  **is same as** everything works fine
```php
{% for option, value in data.passed_options %}
                <tr>
                    <th>{{ option }}</th>
                    <td>{{ profiler_dump(value) }}</td>
                    <td>
                         values can be stubs
                        {% set option_value = value.value|default(value) %}
                        {% set resolved_option_value = data.resolved_options[option].value|default(data.resolved_options[option]) %}
                        {% if option_value is same as(resolved_option_value) %}
                            <em class="font-normal text-muted">same as passed value</em>
                        {% else %}
                            {{ profiler_dump(data.resolved_options.seek(option)) }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
```

May be it will be useful for your investigation

**Comment by vltrof** [comment]
Greetings! 
Seems extracting passed/resolved value works incorrect when null/false passed/resolved
So I sent PR where I have tried to fix the problem. Maybe codestyle should be fixed, because of ternary

**Comment by 7-zete-7** [comment]
Thanks, @vltrof!
