### ISSUE TITLE
[DoctrineBridge] `UuidGenerator` generates a new `Uuid` even if the entity id is already set.

### ISSUE THREAD

**Issue by slutsky** [symfony/symfony#58677]
### Symfony version(s) affected

7.1.5

### Description

`UuidGenerator` generate a new `Uuid` even if the entity id is already set.

For example we have entity with id as `Uuid`:
```php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity]
class ExampleEntity
{
    #[ORM\Id()]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator('doctrine.uuid_generator')]
    #[ORM\Column(type: UuidType::NAME)]
    public Uuid $id;
}
```

If we set id manually and try to generate new with `UuidGenerator`. The `UuidGenerator` return new `Uuid`, but the existed expected:

```php
public function testIdInitializedBeforePersist(): void
{
    /** @var EntityManagerInterface $entityManager */
    $entityManager = self::getContainer()->get(EntityManagerInterface::class);

    $expectedId = Uuid::v4();

    $exampleEntity = new ExampleEntity();
    $exampleEntity->id = $expectedId;

    $entityManager->persist($exampleEntity);

    self::assertEquals($expectedId, $exampleEntity->id); // Failure. Doctrine generate new id.
}
```

### How to reproduce

An example demonstrating the issue is here: https://github.com/slutsky/symfony-uuid-generator-regeneration-example

1. Run docker containers:

```bash
docker-compose up -d
```

2. Install dependencies:

```bash
docker-compose exec php composer install
```

3. Run migrations:

```bash
docker-compose exec php bin/console doctrine:migrations:migrate
```

4. Run tests

```bash
docker-compose exec php bin/phpunit
```

### Possible Solution

Possible to get the identifier from the entity class metadata and return the old value if it is not empty.

**Comment by alexandre-daubois** [comment]
I think this is normal Doctrine's behavior and not especially related to the Uuid generators. The generator is called by Doctrine but it's role is not to check whether the entity already has an ID or not

**Comment by slutsky** [comment]
OK. If possible, please delete this issue.
