### ISSUE TITLE
PasswordStrength Validator doesn't allow for PassswordStrength::STRENGTH_VERY_WEAK

### ISSUE THREAD

**Issue by abunch** [symfony/symfony#58684]
### Symfony version(s) affected

7.1.5

### Description

PasswordStrength Validator doesn't allow for PassswordStrength::STRENGTH_VERY_WEAK

PasswordStrength will not allow use of a strength below 1 
`if ($this->minScore < 1 || 4 < $this->minScore) {
throw new ConstraintDefinitionException(sprintf('The parameter "minScore" of the "%s" constraint must be an integer between 1 and 4.', self::class));
}`

despite having the following constant:
`public const STRENGTH_VERY_WEAK = 0;`

### How to reproduce

Create any form that uses the PasswordStrength validator and try setting the allowed strength to zero.  The most expedient path would be to use the maker bundle and `make:user`, `make:security:form-login`,  `make:reset-password`.  The newly created ChangePasswordFormType form will implement the PasswordStrength validator, you only need to adjust the minScore option.
`new PasswordStrength(['minScore' => PasswordStrength::STRENGTH_VERY_WEAK])`

### Possible Solution

Adjust the if statement that checks the minScore from

`if ($this->minScore < 1 || 4 < $this->minScore)`

to

`if ($this->minScore < 0 || 4 < $this->minScore)`

**Comment by alexandre-daubois** [comment]
What's the purpose of allowing a min score of "Very weak"/0? If you want to allow any password, then the constraint shouldn't be added at all.

**Comment by abunch** [comment]
I'm not here to debate the merits of password strength - if "very weak" wasn't meant to be an option it could have been left out, yet, there it is.  The project I'm working on wants to configure password strength from zero while in development to 5 when in production.

**Comment by derrabus** [comment]
> if "very weak" wasn't meant to be an option it could have been left out, yet, there it is.

It's there because it's the lowest possible value that the estimator can report.

> The project I'm working on wants to configure password strength from zero while in development to 5 when in production.

A value of zero basically means that the password strength does not matter. You'd be running the estimator and discard the result. If that's what you want, just omit the constraint in that situation.

**Comment by xabbuh** [comment]
I am closing here for the reasons explained by @alexandre-daubois and @derrabus. Thank you for understanding.

**Comment by abunch** [comment]
Looks like I hit a nerve.

**Comment by xabbuh** [comment]
We are open for constructive feedback, taking the issue on a personal level is not something we accept. If you can show us how setting the minimum score to `STRENGTH_VERY_WEAK` differs from allowing all passwords, we can happily reopen.

**Comment by abunch** [comment]
Not really interested in arguing about this.  It seems clear you don't want to address this, you can leave the issue closed.
