### ISSUE TITLE
[Profiler] Latest button is no longer present

### ISSUE THREAD

**Issue by BTHAdrien** [symfony/symfony#58693]
### Description

Hello, since the new profiler design, we doesn't anymore have the "Latest" button on homepage...
![Capture d’écran du 2024-10-28 14-40-30](https://github.com/user-attachments/assets/fd5c6e4f-d3f8-45da-b761-5e85cbc7d4d1)
We have to go to one log to have the button.
This feature was really very useful, I don't understand why it's no longer there...
Thanks 🫣

### Example

Just like oldest version of profiler

**Comment by stof** [comment]
@javiereguiluz can you handle this one please ?

**Comment by BTHAdrien** [comment]
Thanks a lot !

**Comment by xabbuh** [comment]
@BTHAdrien Do you by chance know if this was an issue exclusive for Symfony 6.4 or is Symfony 7 affected too (the code around this part is different between the versions and I had to resolve conflicts when merging up).

**Comment by BTHAdrien** [comment]
> @BTHAdrien Do you by chance know if this was an issue exclusive for Symfony 6.4 or is Symfony 7 affected too (the code around this part is different between the versions and I had to resolve conflicts when merging up).

No sorry I couldn't test on Symfony 7, I wouldn't know how to answer you

**Comment by BTHAdrien** [comment]
> @BTHAdrien Do you by chance know if this was an issue exclusive for Symfony 6.4 or is Symfony 7 affected too (the code around this part is different between the versions and I had to resolve conflicts when merging up).

I just tested and the shortcuts are not present on symfony 7 either

**Comment by xabbuh** [comment]
Thank you for the feedback. 👍 Let's reopen here then.

**Comment by BTHAdrien** [comment]
> Thank you for the feedback. 👍 Let's reopen here then.

The template is a little bit different in Symfony 7. I tested and fixed it with the same fix.
![image](https://github.com/user-attachments/assets/01eec274-8f06-4700-861d-34e0021317f7)
In results.html.twig

**Comment by xabbuh** [comment]
thanks for the feedback, see #58762
