### ISSUE TITLE
Mistake in validator component translation for serbian (latin) - problem with plural options

### ISSUE THREAD

**Issue by knezmilos13** [symfony/symfony#58691]
### Symfony version(s) affected

6.4 (version I'm on), but possibly all versions starting from 5.4

### Description

When length validation in a form fails, this error is shown:

Unable to choose a translation for "Vrednost je predugačka. Trebalo bi da ima {{ limit }} karaktera ili manje.|Vrednost je predugačka. Trebalo bi da ima {{ limit }} karaktera ili manje." with locale "sr_Latn" for value "20". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").

It appears that serbian (latin) translations - validators.sr_Latn.xlf - are missing one of plural-options. Serbian needs three, and there are only two provided. When third is added, the validation works properly (form field is shown with appropriate error message in serbian). Serbian can use both latin and cyrillic script - per personal preference, letters of two scripts are completely interchangeable - and the serbian-cyrillic version of xlf file (validators.sr_Cyrl.xlf) does have three translation options.

I've managed to find the commit that made the change - before this commit there were three options for plurals:
https://github.com/symfony/symfony/commit/bdee377856957cdfd00dbafd0cd30a0d44bbae10
This is present from version 5.4

I could fix this, as well as some mistakes in the translations themselves I've noticed, but I'm not sure on which version should I make a pull request. I don't know if there were any changes in the validation/translation component before/after my own version (6.4). Perhaps the change in the commit above was actually valid in 5.4? Although if that was true, whoever made the change should have changed the cyrillic translation as well, but they didn't.

### How to reproduce

Use serbian latin locale.
Have entity with a property configured with Length validation.
Have form for said entity.
When using form, enter text longer than what is allowed by the Length validation. 
Submit form.

### Possible Solution

Add third plural-option to translations in validators.sr_Latn.xlf.
I can make a pull request, just need a pointer on which version/branch of symfony should I do it.

**Comment by stof** [comment]
Translations are updated in the lowest maintained branch, so this should be submitted to the 5.4 branch.
