### ISSUE TITLE
HttpClientDataCollector fails if proc_open is disabled via php.ini

### ISSUE THREAD

**Issue by ZaneCEO** [symfony/symfony#58700]
### Symfony version(s) affected

7.1.6

### Description

[HttpClientDataCollector::escapePayload](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php#L256) creates a `new Process()` -> it fails if `proc_open` is disabled:

> The Process class relies on proc_open, which is not available on your PHP installation.

### How to reproduce

```
        $request =
            $this->httpClient->request('POST', 'https://www.linkedin.com/oauth/v2/accessToken', [
                "body"  => [
                    "grant_type"    => "authorization_code",
                    "code"          => "11111111",
                    "redirect_uri"  => 'https://example.com',
                    "client_id"     => 'abc',
                    "client_secret" => 'ddd'
                ]
            ]);

        $content = $request->getContent(false);

        throw new \Exception();
```

### Possible Solution

[escapePayload](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php#L256) could be modified to avoid `new Process()` and generate the command in-place.

### Additional Context

escapePayload [is called only](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php#L197) if the request has either a json content or a body.

**Comment by nicolas-grekas** [comment]
Ah indeed.

The fix should be this:
```php
if ($useProcess ??= function_exists('proc_open') && class_exists(Process::class)) {
```

Can you please send a PR targetting branch 5.4?

**Comment by ZaneCEO** [comment]
Great, thanks for the feedback!

I'll gladly prepare the PR later today

**Comment by ZaneCEO** [comment]
The function is not present in:

- [5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)
- [6.0](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)
- [6.1](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)
- [6.2](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)

[It looks like it was introduced in 6.3](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php)

I submitted the PR
