### ISSUE TITLE
[Process] ExecutableFinder on Windows should maybe not rely on where?

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#58734]
### Symfony version(s) affected

5.4+

### Description

You can see that the ExecutableFinder if it cannot find an executable by itself in the PATH will then refer to there `where` command here https://github.com/symfony/symfony/blob/839a02bbace31e71bdd92d0b475066a14454b1dc/src/Symfony/Component/Process/ExecutableFinder.php#L89-L94

However this has a few problems:

- This searches in current directory, per the command's description:
  > By default, the search is done along the current directory and in the paths specified by the PATH environment variable.

  This is perhaps ok as a fallback if no real executable exists... BUT:
- This does not find built-in commands like rmdir, copy and others which means it might revert to using a local rmdir.exe when used to make https://github.com/symfony/symfony/pull/58710 - I worked around this in the Composer PR [here](https://github.com/composer/composer/pull/12180/commits/b1915c28b8ffe1374b1b660fe0b17888a630185a) but this is not an exhaustive list of built-in commands, just a list of common ones I found by playing with `where` and seeing which it could find and not (for built-in ones it errors and does not find an exe, unless you have an exe in CWD). If someone knows where to find a complete list of built-in commands that might be valuable (cc @johnstevenson here too sorry :D)
- if using `where` we should ensure that the error output is caught, right now ExecutableFinder calls `where` using a plain `exec()` call which leaks errors to stderr, e.g. `(new Symfony\Component\Process\ExecutableFinder())->find('lala');` outputs `INFO: Could not find files for the given pattern(s).` to stderr. (found this [here](https://github.com/composer/composer/actions/runs/11637788033/job/32411550319?pr=12180#step:14:101))

So I think in ExecutableFinder it might be ok to keep as is, I'm mostly opening this issue to document my findings.. But in the context of #58710 it's wrong for built-ins, and maybe built-ins should be added to ExecutableFinder so that it can just "find" these as e.g. `rmdir => rmdir` and not transform these in any way.

### How to reproduce

above

**Comment by nicolas-grekas** [comment]
From ChatGPT:

Internal Commands in cmd.exe

    Directory and File Commands
        CD (Change Directory)
        CHDIR (Change Directory, alias of CD)
        CLS (Clear Screen)
        COPY (Copy files and directories)
        DEL or ERASE (Delete files)
        DIR (List directory contents)
        MKDIR or MD (Make directory)
        MOVE (Move files and directories)
        PUSHD (Push directory onto stack)
        POPD (Pop directory from stack)
        RD or RMDIR (Remove directory)
        REN or RENAME (Rename files or directories)
        TYPE (Display contents of a file)

    System and Session Commands
        BREAK (Set or clear extended CTRL+C checking)
        COLOR (Set the Command Prompt colors)
        DATE (Display or set date)
        ECHO (Display messages or turn command echoing on/off)
        EXIT (Exit Command Prompt)
        LABEL (Edit a disk label)
        PROMPT (Change the Command Prompt appearance)
        SET (Set environment variables)
        TITLE (Set the Command Prompt window title)
        TIME (Display or set system time)
        VER (Display Windows version)
        VOL (Display disk volume label and serial number)

    Command Control and Flow
        CALL (Call a batch file from another batch file)
        FOR (Loop through a set of files or items)
        GOTO (Jump to a labeled line in a batch script)
        IF (Conditional processing in batch scripts)
        PAUSE (Pause execution and wait for user input)
        REM (Add comments in batch scripts)
        SHIFT (Modify positional parameters in batch files)
        START (Start a program in a new window)
        SETLOCAL (Begin localization of environment changes in a batch file)
        ENDLOCAL (End localization of environment changes in a batch file)

    Network and Communication Commands
        FTYPE (Display or modify file types used in file extension associations)
        PATH (Display or set search path for executables)
        ASSOC (Modify file extension associations)

    Miscellaneous Commands
        HELP (Display help information for internal commands)
        MKLINK (Create symbolic links)

**Comment by nicolas-grekas** [comment]
The stderr leaking is fixed in https://github.com/symfony/symfony/pull/58723

The first issue doesn't look like one to me: what matters is giving PATH the highest precedence (but I'm wondering what calling `where` provides actually, since it re-does what we did in PHP before). Might be a change for 7.x.

About built-in commands :disappointed: 
I see no other option than listing them in ExecutableFinder...

**Comment by nicolas-grekas** [comment]
Same question for `command -v` BTW: `command -v cd` returns `cd` but when using the array-style command, `cd` cannot work since it's a shell built-in...

**Comment by Seldaek** [comment]
Indeed cd does not work but I cannot find a built-in in bash that is really needed/sensible to use, unlike rmdir which is quite useful. cd for example I don't think it makes any sense using array stye commands as you cannot combine multiple commands.

**Comment by Seldaek** [comment]
@nicolas-grekas will you still do the removal of the where/command -v calls? Could do in 7.2 IMO to reduce BC risk.
