### ISSUE TITLE
[PsrHttpMessageBridge] Resolver and listener not registered in service container

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#58741]
### Symfony version(s) affected

6.4.*

### Description

The psr-http-message-bridge component contains a [PsrResponseListener](https://github.com/symfony/psr-http-message-bridge/blob/f16471bb19f6685b9ccf0a2c03c213840ae68cd6/EventListener/PsrResponseListener.php) and a [PsrServerRequestResolver](https://github.com/symfony/psr-http-message-bridge/blob/f16471bb19f6685b9ccf0a2c03c213840ae68cd6/ArgumentValueResolver/PsrServerRequestResolver.php). They are not registered in the service container by the component, neither is explained how (and why) to do that manually, in the [documentation](https://symfony.com/doc/current/components/psr7.html). 

### How to reproduce

![image](https://github.com/user-attachments/assets/a3b7d323-fa56-4102-9e4d-17f25b86ff05)

**Comment by derrabus** [comment]
Not a bug: the integration simply hasn't been built into FrameworkBundle. See #52372 for previous discussions on that topic.

**Comment by tjveldhuizen** [comment]
Thanks for that reference, I was looking in previous issues, but forgot to check PR's as well.
