### ISSUE TITLE
[DoctrineBridge] Deprecation impossible to fix

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#58756]
Hello, 

My code trigger deprecations, and it seems they are impossible to fix, because my vendors don't include these attributs

```
1x: Since symfony/doctrine-bridge 6.3: Registering "Orpi\Cache\InvalidateCacheEventSubscriber" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.
```

extract from my composer.json

```
doctrine/common                          3.4.5   
doctrine/dbal                            3.9.3   
doctrine/deprecations                    1.1.3   
doctrine/doctrine-bundle                 2.13.0  
doctrine/doctrine-migrations-bundle      3.3.1
doctrine/event-manager                   2.0.1
doctrine/orm                             2.20.0  
symfony/doctrine-bridge                  6.4.13  
```

ref: https://github.com/symfony/symfony/blob/cb22affdc12189fc2ad493771ee7564e3d2007cb/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L211

Looks related to https://github.com/symfony/symfony/pull/47864 /cc @derrabus

**Comment by derrabus** [comment]
You don't have this attribute?

https://github.com/doctrine/DoctrineBundle/blob/7bfb8e834aa1e82d107d5f7cfa139c0c5eb45581/src/Attribute/AsDoctrineListener.php

**Comment by lyrixx** [comment]
WAhoo, Sorry for the noise!!! I do have it, But I really missed it. Again, sorry :(

**Comment by derrabus** [comment]
No worries. 🙂
