### ISSUE TITLE
PropertyInfo PhpStanExtractor is incompatible with version 2.0 of phpstan/phpdoc-parser

### ISSUE THREAD

**Issue by Steveb-p** [symfony/symfony#58796]
### Symfony version(s) affected

5.4, 6.4, 7.2

### Description

A new version of PHPStan's parser has been released (2.0.0).

Installation with 2.0.0 causes issues with the following code:
https://github.com/symfony/symfony/blob/3ee749073358a2e096193994176dc054806b62f1/src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php#L82

Because `ConstExprParser` now has required constructor arguments.

Since this is an optional dependency, how are we going to handle it?

### How to reproduce

In my case it was any project using `symfony/serializer-pack`. Since this also installed the `phpstan/phpdoc-parser` with any version, I received 2.0.0.

**Comment by stof** [comment]
Supporting both versions of the package should be easy (for 2.0, we need to create a config object in its default config and pass it to all those constructors instead of using those constructors with their default constructor arguments), so I suggest we add support for version 2.0 in a patch release

**Comment by derrabus** [comment]
PR welcome.

**Comment by xabbuh** [comment]
I'm on it

**Comment by xabbuh** [comment]
see #58800

**Comment by chriskapp** [comment]
Also for others, if you use `symfony/type-info` `v7.1.6` calling `PropertyAccess::createPropertyAccessor()` with PHP-doc parser 2 causes the issue:

```
Too few arguments to function PHPStan\\PhpDocParser\\Lexer\\Lexer::__construct(), 0 passed
```

but the PR https://github.com/symfony/symfony/pull/58804 from @xabbuh resolves this, so we only need to wait for a next release at the `symfony/type-info` package.
