### ISSUE TITLE
symfony/string EnglishInflector spelling mistakes in a coupla plurals

### ISSUE THREAD

**Issue by adamcameron** [symfony/symfony#58797]
### Symfony version(s) affected

7.1

### Description

See https://github.com/symfony/string/blob/7.1/Inflector/EnglishInflector.php#L361

There is no such word "matricies", as per "appendix", it should be "appendices" ("es", not "ies").

Same just above with "indicies"... it should be "indices".

Refs:
- https://en.wiktionary.org/wiki/matrix#English
- https://en.wiktionary.org/wiki/index#English

Great lib though, thanks for yer hard work!

### How to reproduce

```
public function testPluraliseNonStandardPlural()
{
    $inflector = new EnglishInflector();
    $plurals = $inflector->pluralize('matrix');

    $this->assertEquals('matrices', $plurals[0]);
}
```

**Comment by stof** [comment]
@adamcameron your test is wrong as it explicitly ignores alternatives returned by the inflector, using only the first one.
The guarantee we (try to) make is that the correct plural will be in the list being returned. But it might not be the first one.
However, in that case, `matrices` is not in the list at all, so there is still a legitimate issue.

This inflector was initially implemented based on the needs of the PropertyAccess component, where we need to find the adder and remover methods for a collection. Having multiple alternatives allows us to check whether one of the alternatives matches an existing method.

A fool-proof implementation of an inflector returning a single plural for each word would require bundling a full English dictionary.

**Comment by adamcameron** [comment]
@stof my repro case is not exhaustive, it's just demonstrating that what could be expected is the word "matrices" which *is* a plural of "matrix", whereas - as I pointed out - "matricies" *is not a word* (emphasis just for clarity).

Note the title of the issue is "...spelling mistakes..." not "I expect my favourite value to be returned in the 0th position of the array" ;-)

All good though... someone else got it, and the other issue cited here fixes it. Nice one!
