### ISSUE TITLE
Missing language codes

### ISSUE THREAD

**Issue by ghalse** [symfony/symfony#58798]
### Symfony version(s) affected

5.4.46, 6.4.14, 7.1.7, 7.2.0-BETA2

### Description

Symfony was recently updated to include locale information from ICU 75.1, which is a great improvement.

Unfortunately, this version of the ICU data still does not include information for many languages, particularly African ones (including the official languages of a number of African countries). The result is that projects that depend on Symfony cannot be localised into these languages. (See [here](https://github.com/simplesamlphp/simplesamlphp/issues/2305) for an example.)

The newer 76.1 release of the ICU data includes several more African languages, including the specific ones I'm interested in (being a number of South Africa's official languages).

### How to reproduce

Setting a language locale to `st`, `st_ZA`, or `st_LS` uses the default fallback or results in an error, despite being a valid language (Southern Sotho/Sesotho) and having been included in the ISO 639-1 language codes for over a decade.

### Possible Solution

Updating the locale information to ICU 76.1 (based on CLDR 46) will add support for more languages.

**Comment by xabbuh** [comment]
see #58802
