### ISSUE TITLE
[Form][FrameworkBundle][HttpKernel] param `validator.translation_domain` param not available

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#58833]
### Symfony version(s) affected

7.2.0

### Description

If `symfony/form` is not available, you get the following exception:

> Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "validator.translation_domain".

I believe #58187 caused this bug.

### How to reproduce

Install a Symfony 7.2 app w/o `symfony/validator` or `symfony/form`.

**Comment by xabbuh** [comment]
Can you confirm that #58834 fixes this?
