### ISSUE TITLE
Interface for InputBag because its a final class

### ISSUE THREAD

**Issue by Scarbous** [symfony/symfony#58835]
### Description

I want to test my code, which want access the `Request::cookies` property

The `Request` create InputBag [instance on the fly](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/HttpFoundation/Request.php#L231), so I cant mock it.

The best solution from my point of view would be to add a `InputBagInterface`.

### Example

```php
$this->createMock(InputBag::class)
```

**Comment by xabbuh** [comment]
Can you elaborate a bit more on your use case? How would being able to mock the class help when the `Request` class still manages its instance?

**Comment by Scarbous** [comment]
@xabbuh Thank you for your fast response.


My test case looks like:
```php
$event = $this->prophesize(StorefrontRenderEvent::class);
$request = $this->prophesize(Request::class);
$cookies = $this->prophesize(InputBag::class);

$request->cookies = $cookies->reveal();
$cookies->get('foo_bar')
    ->willReturn($value ?? '');

$event->getRequest()
    ->willReturn($request->reveal());

$this->subject->onStorefrontRender($event->reveal());
```

The implementation I want to test looks like:
```php
public function onStorefrontRender(StorefrontRenderEvent $event): void
    {
        $value = $event->getRequest()->cookies->get('foo_bar');

        $event->setParameter('additionalValue', $value);
    }
```

**Comment by xabbuh** [comment]
Why do you need to mock the `InputBag` class here? I don't see the advantage over just relying on the class being used as is.

**Comment by Scarbous** [comment]
I want to mock up everything I don't control myself. In the case of a unit test, I want to encapsulate everything so that I only execute my code and, in the best case, only work against interfaces.

**Comment by chalasr** [comment]
I'm against this proposal as manual instantiation is fine and has advantages over mocking for the use case at hand. 
I suggest to read about the *[Don't mock what you don't own](https://thephp.cc/articles/do-not-mock-what-you-do-not-own)* principle, and https://blog.frankdejonge.nl/testing-without-mocking-frameworks/ also.

**Comment by Scarbous** [comment]
@chalasr Thank you for the clarification. I think we can close this issue for now.
