### ISSUE TITLE
HWIOAuthBundle broken with 7.2

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/symfony#58845]
### Symfony version(s) affected

v7.2.0-BETA1

### Description

When upgrading from 7.1 to v7.2.0-BETA1 or v7.2.0-BETA2, [HWIOAuthBundle](https://github.com/hwi/HWIOAuthBundle) is broken.

I go this error:

`HWI\Bundle\OAuthBundle\Security\Http\Firewall\RefreshAccessTokenListener::__construct(): Argument #1 ($oAuthAuthenticator) must be of type HWI\Bundle\OAuthBundle\Security\Http\Authenticator\OAuthAuthenticator, Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator given`

### How to reproduce

Relevant code:
https://github.com/hwi/HWIOAuthBundle/blob/2.2.0/src/Security/Http/Firewall/RefreshAccessTokenListener.php#L22

### Additional Context

Caused by #57425? Not sure if this is a bug or something that should be changed in HWIOAuthBundle.

**Comment by nicolas-grekas** [comment]
Please report this to the bundle also. It looks like a decorator makes too strict assumptions.

**Comment by Shoplifter** [comment]
I have the same issue with a simple CustomLoginAuthenticator extending `Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator`, no HWIO Bundle in the game.
Just let me know if you need more information.

**Comment by chalasr** [comment]
To complete what Nicolas said, this happens because Symfony decorates authenticators in debug mode. Overall, authenticators are pretty similar to controllers in the sense they are not meant to be injected nor called directly other than by the authenticator manager itself. As such one shouldn't enlarge their API with custom behavior but provide them with your own services doing so instead, so you can reuse those services elsewhere the way you want.
Closing as this is not something we can fix.

**Comment by stephanvierkant** [comment]
Thanks! There is a PR already: https://github.com/hwi/HWIOAuthBundle/pull/2020

But both [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) and [hwi/HWIOAuthBundle](https://github.com/hwi/HWIOAuthBundle), the two most popular libraries in this area (https://packagist.org/?query=oauth2%20client) appear to no longer be maintained.

If you want to help with this, see https://github.com/hwi/HWIOAuthBundle/issues/2019 or https://github.com/thephpleague/oauth2-client/issues/1041.

**Comment by MLukman** [comment]
Here is my workaround for this "backward-incompatibility" issue:

```
    #[Route('/auth/connect/{client}', name: 'app_auth_connect')]
    public function connect(OAuth2Authenticator|TraceableAuthenticator $oauth2, $client): Response
    {
        if ($oauth2 instanceof TraceableAuthenticator) {
            $oauth2 = $oauth2->getAuthenticator();
        }
```
