### ISSUE TITLE
Redis6ProxyTrait incompatible with PhpRedis 6.1.0 interface

### ISSUE THREAD

**Issue by HMAZonderland** [symfony/symfony#58886]
### Symfony version(s) affected

All using phpredis 6.1 and Redis6ProxyTrait

### Description

In the [phpredis 6.1.0 release](https://github.com/phpredis/phpredis/blob/6.1.0/redis.stub.php#L1817) the interface for hset is defined as:
```php
public function hSet(string $key, mixed ...$fields_and_vals): Redis|int|false;
```

The [`Redis6ProxyTrait` trait](https://github.com/symfony/cache/blob/6.4/Traits/Redis6ProxyTrait.php#L30) implements this as:
```php
public function hSet($key, ...$fields_and_vals): \Redis|false|int
{
    return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->hSet(...\func_get_args());
}
```

This triggers a Compile error:
```
Compile Error: Declaration of Symfony\Component\Cache\Traits\Redis6ProxyTrait::hSet($key, $fields_and_vals): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false
```

### How to reproduce

1. Install phpredis 6.1.0
2. Call the hset function through a class that implemented the trait.

### Possible Solution

Implement the phpredis interface correctly.

**Comment by xabbuh** [comment]
Which version of the Cache component do you have installed?

**Comment by HMAZonderland** [comment]
This finding is from 6.4.11.

**Comment by HMAZonderland** [comment]
This issue is mentioned in phpredis: https://github.com/phpredis/phpredis/issues/2562

**Comment by stof** [comment]
This is weird. 6.4.11 should be compatible with phpredis 6.1.0 as it includes the patch. 

the signature in 6.4.11 is compatible with the Redis signature (removing the parameter types is fine, as widening parameter types in a child class is allowed).
However, the error message you are getting is suspicious because the signature it mentions does not match the Symfony source code.

Error message: `Redis6ProxyTrait::hSet($key, $fields_and_vals): Redis|int|false`
Source code: `Redis6ProxyTrait::hSet($key, ...$fields_and_vals): Redis|int|false`

For some reason, it looks like the second parameter is not variadic on the system in which you are getting the error. Please check that you are indeed using an unmodified 6.4.11 version.

**Comment by HMAZonderland** [comment]
Okay, I did some researching to make this reproducible:

Made this Docker file:
```Dockerfile
FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    unzip \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

RUN apt-get update && apt-get install -y redis-server

RUN pecl install redis-6.1.0 \
    && docker-php-ext-enable redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY composer.json composer.json
COPY example.php example.php

RUN composer install

EXPOSE 6379

CMD ["sh", "-c", "service redis-server start && php example.php"]
```

Include this `composer.json`
```
{
  "name": "phpredis/example",
  "require": {
    "php": "^8.2",
    "symfony/cache": "v6.4.11"
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  }
}
```

Then include this `example.php` file:
```php
<?php
declare(strict_types=1);

require 'vendor/autoload.php';

use Symfony\Component\Cache\Traits\Redis6Proxy;

$redisInstance = new Redis6Proxy();

$redisInstance->setKey('test_key', 'Hello, Redis with Redis6ProxyTrait!');
$value = $redisInstance->getKey('test_key');

var_dump($value);
```

Then build the container and run it:
```
% docker build -t phpredis-example .
```

Then run it:
```
% docker run --rm phpredis-example

Starting redis-server: redis-server.

Fatal error: Declaration of Symfony\Component\Cache\Traits\Redis6ProxyTrait::hSet($key, $fields_and_vals): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false in /var/www/html/vendor/symfony/cache/Traits/Redis6ProxyTrait.php on line 30
```

**Comment by stof** [comment]
@HMAZonderland this does not work because `COPY composer.json composer.json` tries to copy a composer.json file that is not provided in your reproducer

**Comment by HMAZonderland** [comment]
@stof thanks! Noticed it was missing. I have included it now.

**Comment by stof** [comment]
OK, found it. The link you shared for the Symfony source code was not for 6.4.11 but for the latest 6.4 branch. So the solution for this is simple: update to 6.4.12 or newer, where the issue is already fixed.

**Comment by HMAZonderland** [comment]
Aha, thanks!
