### ISSUE TITLE
Installing fake-sms-notifier as a dev packages does not work

### ISSUE THREAD

**Issue by toby-griffiths** [symfony/symfony#58929]
### Symfony version(s) affected

7.1.8

### Description

I wanted to use the fake notifier during testing, but don't need it on the production site, so I installed it as a `--dev` package… then spent about 45 mins & lots of step debugging, trying to work out why it wasn't working.

### How to reproduce

Install the package using composer require --dev symfony/fake-sms-notifier.

Try to send an SMS notification.

### Possible Solution

Is it possible to allow this package to be installed just in dev, since it's a primarily development style package?

Or at least lets update the docs to make this clear.  Happy to PR, but if we can make it support dev only, all the better.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by toby-griffiths** [comment]
> Can you create a small example application that allows to reproduce your issue?

Here you go…

https://github.com/toby-griffiths/fake-sms-notifier-demo

**Comment by nicolas-grekas** [comment]
What does it mean "it doesn't work"? How does it behave?

**Comment by xabbuh** [comment]
I see where this is coming from. `ContainerBuilder::willBeAvailable()` will return `false` for `symfony/fake-sms-notifier` which means that the transport service will be removed which in turn leads to the following error:

```
$ php bin/console app:send-fake-sms

In Transport.php line 165:
                                                 
  The "fakesms+logger" scheme is not supported.
```

**Comment by GromNaN** [comment]
This logic is in the [`FrameworkExtension`](https://github.com/symfony/symfony/blob/bec056a93aedad096b40fe9f0dae24b37c527778/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2909C43-L2911).

**Comment by 94noni** [comment]
I remember commenting such subject back then
https://github.com/symfony/symfony/pull/39949/files#r564443227
https://github.com/symfony/symfony/issues/40625#issuecomment-809330360

I think it could be wise to move such notifier/fake being available for --dev dependencies

**Comment by xabbuh** [comment]
see #59213
