### ISSUE TITLE
Can not use `Aws\Credentials\InstanceProfileProvider` for credentials read from the instance metadata

### ISSUE THREAD

**Issue by speller** [symfony/symfony#58932]
### Symfony version(s) affected

latest

### Description

On EC2 instances, AWS access credentials can be pulled from the instance metadata. This is the safest way to authenticate requests to AWS API from an instance.

But Symfony doesn't support this way. It requires to always use the key pair which adds complexity and lowers security.

### How to reproduce

Just try configuring the SqsClient with `Aws\Credentials\InstanceProfileProvider` as the `credentials` parameter value.

**Comment by stof** [comment]
Which SqsClient are you talking about ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
