### ISSUE TITLE
AutoconfigureTag overrides Autoconfigure

### ISSUE THREAD

**Issue by Justinas-Jurciukonis** [symfony/symfony#58957]
### Symfony version(s) affected

7.0

### Description

Previously we had following configuration:

```yaml
services:
    _instanceOf:
        App\Validation\Entity\ActiveRecordValidatorInterface:
             shared: false
             lazy: true
             tags: ['app.tag.validation']
```

This allowed us to get all validators and mark them non-shared.

I am migrating this configuration into PHP Attributes using [this documentation](https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags). It states:

> If you need more capabilities to autoconfigure instances of your base class like their laziness, their bindings or their calls for example, you may rely on the [Autoconfigure](https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/DependencyInjection/Attribute/Autoconfigure.php) attribute.

But it seems that order of PHP Attributes matter and `AutoconfigureTag` overrides any previous `Autoconfigure` attribute, even through `AutoconfigureTag` does not accept anything more than tag configuration

### How to reproduce

```php
use Symfony\Component\DependencyInjection\Attribute\Autoconfigure;
use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;

#[
    Autoconfigure(lazy: true, shared: false),
    AutoconfigureTag(self::class),
]
interface ActiveRecordValidatorInterface
```

All services implementing this interface are _shared_ and _eager_ services (_ReadOnlyValidator_ as example):

<img width="585" alt="Screenshot 2024-11-21 at 10 59 14" src="https://github.com/user-attachments/assets/002ff685-3494-41a7-a7c7-bac36213a959">

---

But if I _merge_ these attributes or switch them in place, than it becomes correct:

```php
#[
    AutoconfigureTag(self::class),
    Autoconfigure(lazy: true, shared: false),
]
```

**or**

```php
#[Autoconfigure(tags: [self::class], lazy: true, shared: false)]
```

<img width="587" alt="Screenshot 2024-11-21 at 11 01 52" src="https://github.com/user-attachments/assets/22fd8c5a-1d64-4093-9334-2f296fc96a8f">

**Comment by GromNaN** [comment]
Which exact version are you using? It looks similar the bug fixed by https://github.com/symfony/symfony/pull/57298

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
