### ISSUE TITLE
Request::setTrustedProxies() should allow -1 $trustedHeaderSet

### ISSUE THREAD

**Issue by mfb** [symfony/symfony#58975]
### Symfony version(s) affected

7.2.0-RC1

### Description

I believe that the Request::setTrustedProxies() method should allow -1 for its $trustedHeaderSet argument, but it currently only allows 0 thru 63

```
 * @param int-mask-of<Request::HEADER_*> $trustedHeaderSet A bit field to set which headers to trust from your proxies
```

### How to reproduce

Run phpstan on code such as

```php
$request::setTrustedProxies($proxies, $request->getTrustedHeaderSet());
```

**Comment by xabbuh** [comment]
Passing `-1` here does not make sense. What behaviour would you expect when passing a list of proxies with a header set of `-1`?

**Comment by mfb** [comment]
I have no idea what -1 means, but -1 is the default value of the property in the Request class

**Comment by xabbuh** [comment]
That’s the value when no trusted headers have been configured. Using this does not make much sense when you want to configure trusted proxies.

**Comment by mfb** [comment]
I was trying to configure a proxy IP address without a trusted header in a functional test.

**Comment by xabbuh** [comment]
Looks like passing `0` then is the solution.

**Comment by stof** [comment]
Trusting proxy IPs without trusting any headers does not actually make sense though. The whole point of trusting proxies is to trust the headers they send.

**Comment by mfb** [comment]
It sounds like the work around would be that if the trusted header set is -1 (has not been configured) I should configure it to 0 - i.e. it's intentional that it cannot be configured to -1 despite that being a possible value.

**Comment by mfb** [comment]
By the way, I completely agree that trusting proxy IPs without trusting any headers does not actually make sense.  This was just some silly functional test code.

**Comment by mfb** [comment]
Actually, what I found is that passing -1 means trust all headers?

So, passing 0 is definitely not the same as -1.

**Comment by mfb** [comment]
Well, I think what I will do is refactor the functional test to avoid testing the -1 case.
