### ISSUE TITLE
Backport secrets:reveal command into at least Symfony 6.4 LTS version

### ISSUE THREAD

**Issue by Dr-Shadow** [symfony/symfony#58978]
### Description

Hello,

For security reasons I would appreciate being able to reveal one of the many secrets we could have instead all of them on the command line in previous Symfony versions. Would it be possible to backport the command into previous versions of Symfony especially LTS one ?

Thanks in advance for your time.

**Comment by stof** [comment]
We don't backport new features into patch versions of older series. Patch releases receive only bug fixes.

**Comment by Dr-Shadow** [comment]
Ok thanks for replying, good to know for now.
