### ISSUE TITLE
[PropertyInfo] @Internal directive on class prevents custom read/write extractor implementation

### ISSUE THREAD

**Issue by Guarrakesh** [symfony/symfony#58988]
### Symfony IsVersions(s) Affected
All
### Description
I'm trying to use a custom Read/Write Info Extractor within the PropertyAccessor.
```php
// CustomReadExtractor.php
class CustomReadExtractor implements PropertyReadInfoExtractorInterface {
        public function getReadInfo(string $class, string $property, array $context = []): ?PropertyReadInfo;
        {
               //custom logic
        }
}

// example usage
$extractor = new CustomReadExtractor();
(new PropertyAccessorBuilder)->setReadInfoExtractor($extractor);
```
Howevery, the class `PropertyReadInfo` is marked as `@internal` in it's docblock, causing the IDE and PHPStan to complain about usage of internal members.

I assume that creating a custom extractor is something that should be supported, as the [documentation ](https://symfony.com/doc/current/components/property_info.html#extractors) states _[...] While you can create your own extractors, the following are already available to cover most use-cases_

The same problem is with `PropertyWriteInfo` while implementing a custom class for `PropertyWriteExtractorInterface`.

Is it a wanted limitation or something we can fix?

### Example

The new `PropertyReadInfo` and `PropertyWriteInfo` should not be marked as `@internal`

Before:

```php
/**
 * The property read info tells how a property can be read.
 *
 * @author Joel Wurtz <jwurtz@jolicode.com>
 *
 * @internal
 */
final class PropertyReadInfo
{
}
```

After
```php

/**
 * The property read info tells how a property can be read.
 *
 * @author Joel Wurtz <jwurtz@jolicode.com>
 *
 */
final class PropertyReadInfo
{
```

**Comment by mtarld** [comment]
Hey @Guarrakesh, indeed, I think something's going wrong here.

`PropertyReadInfoExtractorInterface` is not internal, but `PropertyReadInfo` is. Which makes implementing `PropertyReadInfoExtractorInterface` impossible to implement without going against the internal usage rule.

I think that your fix is the good approach. Up to create a PR? :slightly_smiling_face:
