### ISSUE TITLE
Cannot run multiple commands through php -a 

### ISSUE THREAD

**Issue by f2h2h1** [symfony/symfony#58994]
### Symfony version(s) affected

6.4

### Description

Cannot run multiple commands through php -a  in git for windows bash

### How to reproduce

The following command only outputs once, it is expected to output twice
```
username@host MINGW64 /c/dev
php -a <<- 'EOF'
    require __DIR__.'/vendor/autoload.php';
    $application = new \Symfony\Component\Console\Application();
    putenv('COLUMNS=80');
    putenv('LINES=50');
    $application->setAutoExit(false);
    $application->run();
    $application->run();
EOF
```

### Possible Solution

annotate 201 or 203 line of this file `vendor/symfony/console/Application.php`

```php
if (!$phpHandler) {
    if (set_exception_handler($renderException) === $renderException) {
        // restore_exception_handler(); // 201
    }
    restore_exception_handler(); // 203
} elseif (!$errorHandler) {
    $finalHandler = $phpHandler[0]->setExceptionHandler(null);
    if ($finalHandler !== $renderException) {
        $phpHandler[0]->setExceptionHandler($finalHandler);
    }
}
```

### Additional Context

Tested environment
- OS: windows 11
- PHP: 8.1.26 NTS x64
- Docker: NO
- Shell: Bash
- Symfony version: 6.4

**Comment by GromNaN** [comment]
I've just tested your example with PHP 8.3.13 and 8.1.30, and I can't reproduce the problem. As expected I get 2 times the result of the default list command. What are you trying to do?

**Comment by f2h2h1** [comment]
PHP 8.3.13  does not have such an issue,


> I've just tested your example with PHP 8.3.13 and 8.1.30, and I can't reproduce the problem. As expected I get 2 times the result of the default list command. What are you trying to do?


In some cases, I want to test some objects in the project, but I don't want to create new files for them

**Comment by GromNaN** [comment]
Closing as duplicate of https://github.com/symfony/symfony/issues/58993
