### ISSUE TITLE
[RFC] Support asymmetric visibility in VarDumper

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony#58996]
### Description

Currently, VarDumper shows visibility of attributes with the standard notation : `-` for private props, `#` for protected ones and `+` for public ones.

Should the new asymmetric visibility released in PHP 8.4 be supported as well? I think it would be nice and make the display more complete and truthful. But I'm curious to hear other opinion if that would be useful to you. If so, how should it be displayed?

### Example

Given the following example:

```php
class AsymmetricVisibility
{
    public protected(set) mixed $publicPrivate;
}
```

We could for example dump `+get/#set publicPrivate ...`, although I'm really not convinced by this syntax.

---

If this gets accepted, I'd like to take care of the implementation 🙂

**Comment by stof** [comment]
I don't think this is important. Dumping is about seeing the state of the object (which is a reading operation so using the read visibility in the prefix makes sense).
If you want to know that a class declares a property with a different write visibility, looking at the class definition is a lot simpler than instantiating an object (which requires knowing how to initialize it, and so probably involves looking at the class definition) and dumping it.

**Comment by alexandre-daubois** [comment]
Let's close this for the mentioned reason. Thanks for the feedback 👍
