### ISSUE TITLE
Unable to run commands through php -a

### ISSUE THREAD

**Issue by f2h2h1** [symfony/symfony#58993]
### Symfony version(s) affected

6.4

### Description

Unable to run commands through php -a in git for windows bash

### How to reproduce

The following command will not have output
```
username@host MINGW64 /c/dev
php -a <<- 'EOF'
    require __DIR__.'/vendor/autoload.php';
    $application = new \Symfony\Component\Console\Application();
    $application->run();
EOF
```

### Possible Solution

try changing it to this way
```
username@host MINGW64 /c/dev
php -a <<- 'EOF'
    require __DIR__.'/vendor/autoload.php';
    $application = new \Symfony\Component\Console\Application();
    putenv('COLUMNS=80');
    putenv('LINES=50');
    $application->run();
EOF
```

### Additional Context

Tested environment
- OS: windows 11
- PHP: 8.1.26 NTS x64
- Docker: NO
- Shell: Bash
- Symfony version: 6.4

**Comment by f2h2h1** [comment]
Another similar issue https://github.com/symfony/symfony/issues/58994

**Comment by stof** [comment]
what do you mean by "Unable to run commands" ? what happens ?

**Comment by f2h2h1** [comment]
Without these two liines, the command line will not run
```
putenv('COLUMNS=80');
putenv('LINES=50');
```

![image](https://github.com/user-attachments/assets/3a6667e1-7d76-4bb4-9851-059df420497f)


![image](https://github.com/user-attachments/assets/8c962dd4-fafb-4a57-ba01-408110c429d1)

**Comment by f2h2h1** [comment]
PHP 8.3.13 does not have such an issue,

**Comment by xabbuh** [comment]
@f2h2h1 How about PHP 8.2 and 8.1.31 (the latest patch release)?

**Comment by f2h2h1** [comment]
@xabbuh The issues exists in 8.1 and 8.2

PHP 8.1
![图片](https://github.com/user-attachments/assets/8ded652b-015b-47a1-988f-cdbfe857e4b8)


PHP 8.2
![图片](https://github.com/user-attachments/assets/9551bdef-beac-4273-a4b5-5d433a0b8aa3)

**Comment by xabbuh** [comment]
So if I understand it correctly the issue is that the `COLUMNS` and `LINES` env variables are not populated when running PHP with the `-a` option but are otherwise?

**Comment by f2h2h1** [comment]
emem, what is mean otherwise?
PHP run with the -a option need to set `COLUMNS` and `LINES` env variables,

**Comment by xabbuh** [comment]
I meant are these two environment variables present when running the command PHP 8.3?

**Comment by f2h2h1** [comment]
even without these two variables, PHP 8.3 can still run

**Comment by xabbuh** [comment]
I have tried this myself with PHP 8.1.31 as well as with PHP 8.2.26 but I cannot reproduce the behaviour you describe. Can you please debug what happens inside `Application::run()` where the `COLUMNS` and `LINES` env vars are populated and what's the result calculated by `Terminal::getHeight()` and `Terminal::getWidth()` respectively?

**Comment by f2h2h1** [comment]
The script will exit when encountering this method
`fopen('php://stdout', 'w')`

```json
[
    {
        "file": "D:\\magento-ce\\vendor\\symfony\\console\\Terminal.php",
        "line": 84,
        "function": "hasVt100Support",
        "class": "Symfony\\Component\\Console\\Terminal",
        "type": "::"
    },
    {
        "file": "D:\\magento-ce\\vendor\\symfony\\console\\Terminal.php",
        "line": 52,
        "function": "initDimensions",
        "class": "Symfony\\Component\\Console\\Terminal",
        "type": "::"
    },
    {
        "file": "D:\\magento-ce\\vendor\\symfony\\console\\Application.php",
        "line": 140,
        "function": "getHeight",
        "class": "Symfony\\Component\\Console\\Terminal",
        "type": "->"
    },
    {
        "file": "php shell code",
        "line": 1,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
    }
]
```

vendor\symfony\console\Terminal.php
```php
    /**
     * Returns whether STDOUT has vt100 support (some Windows 10+ configurations).
     */
    private static function hasVt100Support(): bool
    {
        return \function_exists('sapi_windows_vt100_support') && sapi_windows_vt100_support(fopen('php://stdout', 'w'));
    }
```

**Comment by cmb69** [comment]
This is not really an issue with Symfony, but rather a glitch of PHP on Windows prior to PHP 8.3.0. The resource returned by the `fopen()` call will be closed after `sapi_windows_vt100_support()` returns (when not run from a script file), and that closes stdout. Symfony could likely work around this by keeping the resource referenced (say in a global variable), so that it won't be closed.
