### ISSUE TITLE
[Validator] Change in behavior of Unique constraint in Symfony 7.2.0

### ISSUE THREAD

**Issue by Wojdylak** [symfony/symfony#59037]
### Symfony version(s) affected

7.2.0

### Description

In #57436 a change was introduced that affects the behavior of the Unique constraint. Specifically, a line was added in UniqueValidator:
```php
->atPath("[$index]" . (null !== $constraint->errorPath ? ".{$constraint->errorPath}" : ''))
```
This change now adds [$index] to every propertyPath, even when errorPath isn't set. This alters the previous behavior and might cause issues, especially in existing implementations where the index wasn't part of the path.

It would be great if this change could be made optional or if the old behavior could be kept to avoid breaking compatibility with older code.

### How to reproduce

Compare the `propertyPath` for an array field with a Unique constraint in Symfony 7.1 (which should be just the property name, e.g., `propertyName`) and Symfony 7.2.0 (where it includes the index, e.g., `propertyName[$index]`).

**Comment by xabbuh** [comment]
I am not sure I understand the problem. Can you create a small example application where the new feature causes an issue?

**Comment by Wojdylak** [comment]
I have an entity with an array property that has a Unique constraint. In my test, I checked this constraint, and here's what i observed:

- In symfony 7.1, the validation `propertyPath` was:
```json
{
   "propertyPath": "actions",
   "message": "Provided configuration contains errors. Please add only unique variants."
}
```
- In Symfony 7.2, the validation `propertyPath` changed to
```json
{
   "propertyPath": "actions[1]",
   "message": "Provided configuration contains errors. Please add only unique variants."
}
```

**Comment by norkunas** [comment]
So it's a problem to you that the `propertyPath` now points to the duplicated value? Or a problem is that you need to change your tests?

**Comment by Wojdylak** [comment]
Yes, I consider changing the response structure in a minor version a BC break. Even though it may seem minor, such changes can impact existing tests and integrations, especially since I use this response not only in Symfony forms but also in my API.

**Comment by norkunas** [comment]
Ok I agree (and sorry for a BC break), but now that it's released, it's easier to adapt tests/integrations than wait for a new release, no? :D

**Comment by Wojdylak** [comment]
I understand, and I've managed to adopt for now, but the issue is that this change happened between 7.1 and 7.2, not between 6.4 and 7.0. If I want to maintain support for both ^6.4 and ^7.2 in my application, I need to introduce conditional logic, e.g., adding conditions to my tests to handle the difference, which complicates things unnecessarily. It would be great if a fix could be considered to restore consistency.

**Comment by xabbuh** [comment]
Would #59060 help?

**Comment by Wojdylak** [comment]
Yes, this will help, Thank you! :D
