### ISSUE TITLE
[Security] Cannot have a custom authenticator which implements `EventSubscriberInterface`

### ISSUE THREAD

**Issue by misaert** [symfony/symfony#59071]
### Symfony version(s) affected

7.2.0

### Description

Hi,

When I try to update from Symfony `7.1` to `7.2`. I have an error on cache clear:
```
$ bin/console cache:clear

In RegisterListenersPass.php line 129:
                                                                                                                                             
  Service "debug.App\Security\MyCustomAuthenticator" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".  
```

It seems to be related to:
- https://github.com/symfony/symfony/pull/57369

When I add this code on `vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php` line 646:
```php
        if ($container->hasDefinition('debug.security.firewall')) {
            foreach ($authenticationProviders as $authenticatorId) {
                if ($authenticatorId === MyCustomAuthenticator::class) {
                    continue;
                }

                $container->register('debug.'.$authenticatorId, TraceableAuthenticator::class)
                    ->setDecoratedService($authenticatorId)
                    ->setArguments([new Reference('debug.'.$authenticatorId.'.inner')])
                ;
            }
        }
```

It works.

Is it an issue? Why I can't implement `EventSubscriberInterface` anymore?

Thanks,

Mickaël

### How to reproduce

I created a repository: https://github.com/misaert/test-custom-authenticator/commits/main/.

The last commit is with Symfony `7.2`. Before this, we can launch `bin/console cache:clear` but with this commit, we have this error:
```
$ bin/console cache:clear

In RegisterListenersPass.php line 129:
                                                                                                                                             
  Service "debug.App\Security\MyCustomAuthenticator" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".  
                                                                                                                                             
```

**Comment by roverwolf** [comment]
I ran into the same issue when trying to upgrade to 7.2.0.

My workaround was to pull the event subscriber portions into their own class.

**Comment by misaert** [comment]
Thanks for your reply.

It is a possibility. But I wonder if it is a bug. @MatTheCat, do you think it is?

Thanks

**Comment by MatTheCat** [comment]
Looks like a bug yes 😅

I guess this is not the only case of a service decorated by two different `Traceable`, but no other comes to mind and I don't know how this is handled.

**Comment by MatTheCat** [comment]
@misaert could you check #59278 fixes your issue? :pray:

**Comment by misaert** [comment]
Hi @MatTheCat,

Yes, it works with this fix :+1: 

Thank you :slightly_smiling_face:
