### ISSUE TITLE
Firewall ContextListener Ignores `#Ignore` Attribute During Serialization

### ISSUE THREAD

**Issue by tugrul** [symfony/symfony#59094]
### Symfony version(s) affected

6.4.15

### Description

The `ContextListener` in Symfony uses the native PHP serializer, which does not respect the `#Ignore` attribute on user object fields. This results in the entire user object, including sensitive fields, being serialized into the session.

### How to reproduce

Just put a breakpoint at line 172 and see `$token` variable on inspector.

https://github.com/symfony/security-http/blob/7.2/Firewall/ContextListener.php#L172

### Possible Solution

The session storage should respect the `#Ignore` attribute to avoid serializing unnecessary or sensitive fields.

**Comment by wouterj** [comment]
Hi! This is intended, depending on the whole Serializer component just to serialize the user object into the session would be quite overkill. Besides, the PHP serializer has a very optimized format for storing objects (i.e. the serializer component doesn't store the classname of the object, so we have no way to determine what to deserialize it into).

It's best not to store any sensitive fields in the User object, but if you do you can use the `UserInterface::eraseCredentials()` method that will be called before serializing the user into the session (although this might get deprecated in #59106. I think you can also use PHP's `__serialize()`/`__deserialize()` methods).

**Comment by tugrul** [comment]
@wouterj I know `__serialize()` and `__deserialize()` can solve but it is headache to construct a serializer plan whole fields to skip a single field. 

And it need always has attention when add or remove fields from. 

Hard to understand Symfony's crew. Have motivated to make unnecessary super smart features for simple requirements sometimes. But also ignores the things necessary like this.

**Comment by wouterj** [comment]
Like I said, it's two incompatible serialization formats. The Symfony serializer does not include implementation details like the PHP classname in the serialized format. This is not possible to implement.

Anyways, the best solution is to never store plaintext sensitive values in objects you know are exposed to the outside world (like the User object).

**Comment by tugrul** [comment]
I actually not keep sensitive information. Uploaded file causes serialization error by vich uploader. I currently solved by vich uploader's event subscriber like below.

```php
class VichUploaderSubscriber implements EventSubscriberInterface
{
    public function onUploadComplete(Event $event): void
    {
        $object = $event->getObject();

        if ($object instanceof User) {
            $object->setAvatarFile(null);
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            Events::POST_UPLOAD => 'onUploadComplete'
        ];
    }
}

```

I think object normalizer can handle the attributes like this.

When serialize:
```php
$session->set($this->sessionKey, serialize([ get_class($token), $normalizer->normalize($token) ]));
```

When unserialize:
```php
[ $className, $data ] = unserialize($session->get($this->sessionKey));
$token = $denormalizer->denormalize($data, $className);
```
