### ISSUE TITLE
[MapQueryString] Weird behavior while mapping integer variable

### ISSUE THREAD

**Issue by marcelowzd** [symfony/symfony#59104]
### Symfony version(s) affected

7.1.9

### Description

While trying to map a GET request to a DTO which contains a nullable integer variable, symfony does not initialize the entity and also does not respond to the request with the validation error.

### Create the following DTO ### 
```
use Symfony\Component\Validator\Constraints as Assert;

readonly class FilterDTO {
  public function __construct(
    #[Assert\NotBlank(allowNull: true, message: "The ID must not be blank.")]
    #[Assert\Positive(message: "The ID must be positive.")]
    public ?int $id = null,

    #[Assert\NotBlank(allowNull: true, message: "The name must not me blank.")]
    #[Assert\NoSuspiciousCharacters]
    public ?string $name = null,
  )
  {

  }
}
```
### Create the following controller ### 
```
#[Route(path: "/test", name: "test", methods: ["GET"], format: "json")]
public function readAll(
  #[MapQueryString] FilterDTO $filter = new FilterDTO
): JsonResponse 
{
   dd($filter);
   return $this->json(data: [$filter]);
}
```
###  In the browser, postman or any other tool, make the requests to the endpoint /test ###
The first request will generate the following output (/test):
![ok_result](https://github.com/user-attachments/assets/5e0015fa-85d3-4625-a999-25ba8089c528)
The second request will generate the following output (/test?id=x):
![wrong_result](https://github.com/user-attachments/assets/aa8baa10-9c61-483b-a03a-358fc193e514)

### Additional Context

If using any other constraint, like Length, in a string field, symfony correctly validates the field and returns a 404 error, but with integer fields it does not respond with the validation error and also does not create the DTO (the fields become not initialized).

**Comment by devprodjaz** [comment]
Creating a new project --webapp with v7.1.9 was able to reproduce

**Comment by vltrof** [comment]
Greetings! 
I have experimented with issue and found interesting behavior

First of all if you removing readonly DTO modifier you will solve your problem

The next thing to mention is related to Serializer component and how is it work

https://github.com/symfony/serializer/blob/7.2/Normalizer/AbstractObjectNormalizer.php#L339
```php
$object = $this->instantiateObject($normalizedData, $mappedClass, $context, new \ReflectionClass($mappedClass), $allowedAttributes, $format);
```
When $normalizedData passed it tries create object
```php
try {
                $instance = $reflectionClass->newInstanceArgs($params);

                // do not set a parameter that has been set in the constructor
                foreach ($unsetKeys as $key) {
                    unset($data[$key]);
                }

                return $instance;
            } catch (\TypeError $e) {
                if (!isset($context['not_normalizable_value_exceptions'])) {
                    throw $e;
                }

                return $reflectionClass->newInstanceWithoutConstructor();
            }
            ```

**Comment by vltrof** [comment]
Greetings! 
I have experimented with issue and found interesting behavior

First of all if you removing readonly DTO modifier you will solve your problem

The next thing to mention is related to Serializer component and how is it work

https://github.com/symfony/serializer/blob/7.2/Normalizer/AbstractObjectNormalizer.php#L339
```php
$object = $this->instantiateObject($normalizedData, $mappedClass, $context, new \ReflectionClass($mappedClass), $allowedAttributes, $format);
```
When $normalizedData passed it tries create object
https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L431C13-L446C14
```php
         try {
                $instance = $reflectionClass->newInstanceArgs($params);

                // do not set a parameter that has been set in the constructor
                foreach ($unsetKeys as $key) {
                    unset($data[$key]);
                }

                return $instance;
            } catch (\TypeError $e) {
                if (!isset($context['not_normalizable_value_exceptions'])) {
                    throw $e;
                }

                return $reflectionClass->newInstanceWithoutConstructor();
            }
 ```
and get an error here and return empty object where constructor wasn't call (via reflection)
then normalizer tries set prop via property accessor 
and there we get an error

0 => "The property "id" in class "App\Controller\FilterDTO" is a promoted readonly property." 

https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L517C5-L559C6
```php
    private function writeProperty(array $zval, string $property, mixed $value, bool $recursive = false): void
    {
        try {
            if (PropertyWriteInfo::TYPE_NONE !== $mutator->getType()) {
               // ...
            } elseif ($object instanceof \stdClass && property_exists($object, $property)) {
                //...
            } elseif (!$this->ignoreInvalidProperty) {
                if ($mutator->hasErrors()) {
                    throw new NoSuchPropertyException(implode('. ', $mutator->getErrors()).'.');
                }
                //...
            }
        } catch (\TypeError $e) {
            //...
        }
    }
```

So we throw NoSuchPropertyException

And it is intercepted without any action 
https://github.com/symfony/serializer/blob/7.2/Normalizer/ObjectNormalizer.php#L143C4-L150C6
```php
protected function setAttributeValue(object $object, string $attribute, mixed $value, ?string $format = null, array $context = []): void
    {
        try {
            $this->propertyAccessor->setValue($object, $attribute, $value);
        } catch (NoSuchPropertyException) {
            // Properties not found are ignored
        }
    }
```

I hope it will be useful for fixing

**Comment by vltrof** [comment]
Also important thing to mention 
MapQueryString seems to have default disable_type_enforcement = true  which cause avoiding type error 
https://github.com/symfony/serializer/blob/7.2/Normalizer/AbstractObjectNormalizer.php#L917
(MapRequestPayload doesn't have this context param set and throw type error)

And it is no sense to set it to false because then even int passed value will throw error :(

Also here is reproducer to test 
https://github.com/vltrof/symfony-issue-59104
(remove readonly and behavior will be correct)

**Comment by vltrof** [comment]
Also it can be related with that issue
https://github.com/symfony/symfony/issues/50690#issuecomment-1668565547

**Comment by ovidiuenache** [comment]
@marcelowzd thank you for raising this issue!

@vltrof thank you for the input! It seems we followed the same steps in understanding/reproducing this. :smile: 

I've added my input in the PR. Let me know what you think!

**Comment by vltrof** [comment]
@ovidiuenache 
Hello! Yeah, probably a good solution because all required logic already exists.

But a little idea about this situation 
May be it is possible to handle exactly this error we get in property accessor? 
Technically we are able to set readonly prop which was not inited via reflection

**Comment by dearaujoj** [comment]
There is also the fact that the NotBlankValidator is not going to be triggered for integer with request /test?id as the resolved value is null that makes the validator returns true in the validation process.

**Comment by ovidiuenache** [comment]
@dearaujoj this is unrelated to the issue and to the `RequestPayloadValueResolver` class.

If you send the request as `/test?id` then (after the fix) both properties will be set to null since that is their default value in the DTO provided in the initial example and the validators will skip it, yes. This is the expected behavior.

If this is undesired then the solution is to adapt the DTO or the validation rules to your specific needs.
