### ISSUE TITLE
Twig function csrf_token('authenticate') returns 'csrf_token'

### ISSUE THREAD

**Issue by cavias** [symfony/symfony#59111]
### Symfony version(s) affected

7.2.0

### Description

I am building a login form according to instructions here https://symfony.com/doc/current/security.html#form-login

When I make the following code:
`<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">`

The function `csrf_token('authenticate')` generates thes tring `csrf_token` instead of an actual token. Making my login not work. 

By comparison, executing `csrf_token('randomstring')` does generate a valid token.

What is happening here?

### How to reproduce

Seems to be as simple as doing `csrf_token('authenticate')` in Twig.

**Comment by Crovitche-1623** [comment]
By default, the new CSRF system is stateless since 7.2. That’s not a bug @cavias

**Comment by cavias** [comment]
> By default, the new CSRF system is stateless since 7.2. That’s not a bug @cavias

@Crovitche-1623 the word stateless is not mentioned in neither Security login nor CSRF documentation, so I am failing to understand why this is relevant or what implications it has for this usecase? 

See https://symfony.com/doc/current/security.html#form-login
And https://symfony.com/doc/current/security/csrf.html

**Comment by Crovitche-1623** [comment]
@cavias You are right the documentation is not updated yet (see https://github.com/symfony/symfony-docs/issues/20306) but it's already enabled (see https://symfony.com/blog/new-in-symfony-7-2-stateless-csrf). See in this [section](https://symfony.com/blog/new-in-symfony-7-2-stateless-csrf#how-does-stateless-csrf-work), the `authenticate` value is set by default

**Comment by Crovitche-1623** [comment]
As you probably installed Symfony 7.2, you also got the following recipe : https://github.com/symfony/recipes/pull/1337

**Comment by dearaujoj** [comment]
@cavias I tried to reproduce it on a fresh 7.2 simple project with a protected page and login form and the login worked with the stateless csrf with string "csrf-token"

**Comment by cavias** [comment]
@Crovitche-1623 Thank you, that at least gives me some pointers as to what is going on. Disabling stateless_token_ids seems to "fix" it for now, but of course I'd like to get this working in the future. I see there is also a Stimulus csrf controller provided which I assume is relevant somehow. 

Once documentation is released on how to actually use this I will re-enable it. The app won't be live for a few months anyways, and I am getting a bit tired of all the github deep-diving I have to do to get things working.

I will close this issue.

**Comment by nicolas-grekas** [comment]
The behavior you describe is correct and expected. The stateless CSRF protection that you enabled by adopting the recipe update leads to these not-random tokens.
Then, you write: "Making my login not work.", and this doesn't gives us any hint about what doesn't work.

**Comment by cavias** [comment]
> The behavior you describe is correct and expected. The stateless CSRF protection that you enabled by adopting the recipe update leads to these not-random tokens. Then, you write: "Making my login not work.", and this doesn't gives us any hint about what doesn't work.

All I'm getting when trying to login is the error message "CSRF token invalid". I should have specified that, my apologies. 

I'm assuming the Stimulus csrf controller is supposed to do something here, but which data attributes with which data it needs, I do not know.

**Comment by Crovitche-1623** [comment]
You probably need to set a `data-controller="csrf-protection"` to your csrf input and replace the `{{ csrf_token('authenticate') }}` by `csrf-token` (with the stateless id configuration). That's what I did to make it work !

**Comment by nicolas-grekas** [comment]
Oh, this might be something to add to the doc, right? PR welcome!

**Comment by Crovitche-1623** [comment]
@nicolas-grekas also to the `make:security:form-login` command no ?

**Comment by nicolas-grekas** [comment]
Definitely

Le sam. 7 déc. 2024 à 15:35, Thibault G. ***@***.***> a
écrit :

**Comment by Hanhan1989** [comment]
The issue described above has been fixed in version 7.2.1.
In version 7.2.0, the update process automatically generated a CSRF configuration file (‎config/packages/csrf.yaml). As of version 7.2.1, this file is no longer generated.

This is my assumption.

**Comment by whataboutpereira** [comment]
It seems to me that with stateless enabled and without the csrf-protection controller we'll be left without a token based CSRF check completely?

**Comment by nicolas-grekas** [comment]
`data-controller="csrf-protection"` is required indeed if you enabled the JS snippet (which you did if you accepted the recipe update)

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/pull/1373 and linked issues

**Comment by Menelion** [comment]
Hello! I was directed here from discussion #59382 I created. I still cannot fix it for my setup (`dev` environment, debug on, Windows, no Docker). Stimulus bundle is here, but for some reason `make:assets-install public` does nothing, there is no `assets` directory inside `public` (I don't know if that is normal or not). This in `login.twig.html` still gives invalid CSRF token:

```html
        <input type="hidden" name="_csrf_token"
        data-controller="csrf-protection"
        value="csrf_token"
        >
```

Any ideas appreciated. // CC @nicolas-grekas

**Comment by nicolas-grekas** [comment]
If you cannot make it work, remove the csrf.yaml file brought by the recipe to revert back to previous behavior.

**Comment by RobQuistNL** [comment]
I'm just seeing 'csrf-token' in the value field. No Javascript, no cookies, no headers being sent. Request comes through "OK".

I had to delete the config;
```
# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
```

to make CSRF actually work (so there are now random values in the field, making it stateful again).

With this setup (as described by [this blog post](https://symfony.com/blog/new-in-symfony-7-2-stateless-csrf)), it seems to work, but all request work, making this seemingly CSRF protection, useless.

**Comment by Crovitche-1623** [comment]
@RobQuistNL You don't see any value because that's the point of the CSRF stateless check ! It's done using cookies and not a form value.

**Comment by RobQuistNL** [comment]
@Crovitche-1623 What cookie would that be? I see no cookies being sent in the request.

I see these 2;
```
main_deauth_profile_token=197ddd; PHPSESSID=3c2be52776f1dfb0972e43f21446ade9
```

If I edit both and submit the form, it succeeds and no CSRF error is reported.

**Comment by Crovitche-1623** [comment]
@RobQuistNL Add the mandatory data-controller on your CSRF input then. See: 

https://github.com/symfony/symfony-docs/pull/20530

**Comment by RobQuistNL** [comment]
@Crovitche-1623 that wasn't there indeed. I've added it, but its still simply accepting the request.

FYI: there is 0 javascript in the webpage. Should the be more stuff added? I'd think it would be a local piece of javascript code. But how does that work for people that have JS disabled?

**Comment by RobQuistNL** [comment]
Please note that all the paged so far have been generated using `php bin/console make:controller Login` and others, straight from the documentation.

I don't know exactly when the input field was added to the twig template, but it didn't add the `data-controller="csrf-protection"` as the docs here state; https://symfony.com/doc/current/security.html#form_login-csrf

**Comment by RobQuistNL** [comment]
Also the registration form as generated by;
```
composer require symfonycasts/verify-email-bundle
php bin/console make:registration-form
```

just shows this;
```html
    <form name="registration_form" method="post">
        <div>(... just the form elements ...)</div>

        <button type="submit" class="btn">Sign up</button>
    <input type="hidden" id="registration_form__token" name="registration_form[_token]" data-controller="csrf-protection" value="csrf-token" /></form>
```

and it doesn't matter if I remove / edit cookies and submit. It just succeeds.

**Comment by RobQuistNL** [comment]
If I however change the value `csrf-token` to something else, I get this error; `The CSRF token is invalid. Please try to resubmit the form.`

**Comment by Hanhan1989** [comment]
> If I however change the value `csrf-token` to something else, I get this error; `The CSRF token is invalid. Please try to resubmit the form.`

Symfony now enables Turbo UX by default, you will need to activate the AssetMapper
