### ISSUE TITLE
Streamline one more exception for the bridges regarding option classes

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#59120]
Take for example the [GoIpTransport](https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Notifier/Bridge/GoIp/GoIpTransport.php), it contains the following lines:

https://github.com/symfony/symfony/blob/c98b02aff916ac864f3dc140dd84fac7029a7a39/src/Symfony/Component/Notifier/Bridge/GoIp/GoIpTransport.php#L65-L67

I would like to have a dedicated exception class `UnsupportedOptionsException`, basically the same as I did in 
* https://github.com/symfony/symfony/pull/39365

This could be done for all bridges which already use options.

> [!NOTE]  
> It is important to also raise the notifier version to `7.3` in the `composer.json` files where this new exception is used.

**Comment by tborealis** [comment]
I'll take a look at this
