### ISSUE TITLE
Compatibility issue with Symfony 7.2: Cannot create a "Symfony\Component\TypeInfo\Type\NullableType" error

### ISSUE THREAD

**Issue by scorpion3dd** [symfony/symfony#59137]
### Symfony version(s) affected

7.2.0

### Description

After upgrading Symfony to version 7.2, my project stopped working with the following error:
Cannot create a "Symfony\Component\TypeInfo\Type\NullableType" with "mixed" because it is already nullable in . (which is being imported from "/var/www/back/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

This error points to the api_platform type in my config/routes/api_platform.yaml file:
api_platform:
resource: .
type: api_platform
prefix: /api

The issue seems to be related to changes introduced in Symfony 7.2, specifically in the redesigned TypeInfo component, as explained in this blog post: [New in Symfony 7.2: Redesigned TypeInfo Component](https://symfony.com/blog/new-in-symfony-7-2-redesigned-typeinfo-component).

It appears that the mixed type is now always nullable, and API Platform may not handle this properly. Before the update, everything worked fine with Symfony 7.1.

### How to reproduce

Steps to Reproduce:

Use Symfony 7.2 and the latest version of API Platform.
Create a basic api_platform.yaml file like the one above.
Access any route managed by API Platform.
Expected Behavior:
The routes should be processed normally without any errors.

Actual Behavior:
The error mentioned above is thrown, and the application fails to start.
http://prntscr.com/tT42Y1r46TGI

Steps Taken:
Updated all dependencies to their latest versions.
Cleared the Symfony cache (php bin/console cache:clear).
Verified that the error disappears when downgrading Symfony to version 7.1.

Please let me know if further details or logs are needed.

**Comment by xabbuh** [comment]
Here is a test that allows to reproduce the error:

```php
public function testNullable()
{
    $mixed = Type::mixed();

    $this->assertSame($mixed, Type::nullable($mixed));
}
```

Status: Reviewed

**Comment by soyuka** [comment]
Isn't that fixed already? https://github.com/api-platform/core/commit/4d7deeaf794178b5496ae989520095831a86df8a 

Versions: [v4.0.11](https://github.com/api-platform/core/releases/tag/v4.0.11) [v3.4.8](https://github.com/api-platform/core/releases/tag/v3.4.8) 

Also, not a symfony issue imo.

**Comment by mtarld** [comment]
Indeed, sounds like an issue in API Platform here.
But, with a fresh install (Symfony 7.2 and API Platform 4.0), I cannot reproduce the issue.

And, IMHO that doesn't make sense to convert a mixed to its nullable version as it's already nullable. Therefore, this exception is logical.
But it might be room for improvement by making `Type::nullable` method no-op when dealing with a mixed type.

**Comment by xabbuh** [comment]
What's a bit unfortunate though is that `mixed` and `null` are not instances of `NullableType` and thus passing them to `Type::nullable()` and thus behaves differently than passing a `NullableType` object.

**Comment by mtarld** [comment]
Agreed. What I had in mind was to update the `nullable` method to handle them properly:
```php
public static function nullable(Type $type): Type
{
    if ($type->isNullable()) {
        return $type;
    }

    return new NullableType($type);
}
```
But, even if 7.2 just has been released, this will update the return type and therefore will be a BC break :face_with_diagonal_mouth:

**Comment by chalasr** [comment]
If it's the best fix for the case at hand I'd agree to do it as a bugfix given it is broken today.
