### ISSUE TITLE
[TypeInfo] Add UnknownType

### ISSUE THREAD

**Issue by DavidBadura** [symfony/symfony#59144]
### Description

The type info component is very cool, we are replacing our manual reflection implementation with this component.

Currently the component cannot handle "no type". An `UnsupportedException` is thrown with the message: Cannot find any resolver for "null" type.

My suggestion would be to add another type called `UnknownType`. There is something like this in other type systems such as: https://github.com/sebastianbergmann/type/blob/main/src/type/UnknownType.php

Before:

```php
$reflectionType = $reflectionParameter->getType(); // null

if ($reflectionType === null) {
    throw new ArgumentTypeIsMissing($method->getName());
}

$type = $this->typeResolver->resolve($reflectionType);

if ($type instanceof ObjectType) {
    return [$type->getClassName()];
}
```

After:

```php
$reflectionType = $reflectionParameter->getType(); // null

$type = $this->typeResolver->resolve($reflectionType);

if ($type instanceof UnknownType) {
    throw new ArgumentTypeIsMissing($method->getName());
}

if ($type instanceof ObjectType) {
    return [$type->getClassName()];
}
```

This is not a big problem for us, but could be an improvement. What do you think?

**Comment by mtarld** [comment]
Hey @DavidBadura, thanks for the review! It's always nice to have feedbacks :slightly_smiling_face: 

IMHO, the "there is no type that can be resolved" is by definition not a type.
That's why it sounds strange to me to represent it by something extending the `Type` class.

Therefore, I'd stick with the exception here. This would lead you to write the following code instead:
```php
$reflectionType = $reflectionParameter->getType(); // null

try {
    $type = $this->typeResolver->resolve($reflectionType);
} catch (UnsupportedException) {
    throw new ArgumentTypeIsMissing($method->getName());
}

if ($type instanceof ObjectType) {
    return [$type->getClassName()];
}
```

WDYT?

**Comment by stof** [comment]
I tend to agree with @mtarld here.

Adding `UnknownType` would also force any code dealing with a type to deal with the UnknownType.

**Comment by DavidBadura** [comment]
That makes sense and I also considered catching this exception.

The only thing I'm wondering is whether I really want to catch `UnsupportedException`. Because this exception is thrown in other cases too: https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/TypeInfo/TypeResolver/TypeResolver.php#L50

I would then hide other errors because the exception would be a bit too general. 
I would rather stick with my solution and check beforehand whether the type has not been set.

That is totally fine and I understand why you might not want to add UnknownType. :+1:

**Comment by wouterj** [comment]
I agree with the others here. I would probably favor the "check if there is a type first" approach, and only ask for info about the type if there is one.

So let's close here. Thanks for starting this little discussion @DavidBadura!
