### ISSUE TITLE
lint:container - kernel.secret is still mandatory

### ISSUE THREAD

**Issue by vencakrecl** [symfony/symfony#59197]
### Symfony version(s) affected

7.2.1

### Description

```
 [ERROR] You have requested a non-existent parameter "kernel.secret". A non-empty value for the parameter               
         "kernel.secret" is required. Did you forget to configure the "framework.secret" option?  
```

### How to reproduce

```bash
php bin/console lint:container
```

**Comment by xabbuh** [comment]
Works for me on a fresh project started with the Symfony CLI. Please create a small example application that allows to reproduce this.

**Comment by vencakrecl** [comment]
```bash
symfony new secret-demo --version="7.2.x-dev" --api
cd secret-demo
sed -i '' "s/secret: '%env(APP_SECRET)%'/secret: ''/g" config/packages/framework.yaml
php bin/console lint:container
```

**Comment by xabbuh** [comment]
Well, when starting a new application with the `--api` option, you get an application with API Platform installed. Apparently this installs packages that rely on services that need the `kernel.secret` parameter.

**Comment by vencakrecl** [comment]
According to this article https://symfony.com/blog/new-in-symfony-7-2-optional-secret, it should be optional but it's still mandatory https://github.com/symfony/symfony/blob/90856c6649f6aa747ef1e975dbde681233c101e9/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L323

**Comment by xabbuh** [comment]
It is optional if no service in your application depends on it (you can check that by starting a new application where you don't pass the `--api` option).
