### ISSUE TITLE
[symfony/phpunit-bridge] `SYMFONY_DEPRECATIONS_HELPER=weak` conflicts with PHPUnit's (10) `--fail-on-warning` 

### ISSUE THREAD

**Issue by mislavjakopovic** [symfony/symfony#59208]
### Symfony version(s) affected

6.4

### Description

Recently I have added `failOnWarning (--fail-on-warning)` to my PHPUnit 10 config and pipelines due to bad commit which caused warnings in several tests.

This did not work as expected and I've spent a lot of time turning the codebase inside out figuring out where the problem was. Turns out environment variable `SYMFONY_DEPRECATIONS_HELPER` was set to `weak` and because of it PHPUnit just reported tests as fully passed, without marking them with warning `"W"`. It still outputted warnings though, but tests passed.

Here's an example of output with `SYMFONY_DEPRECATIONS_HELPER=weak`:
```
PHPUnit 10.5.20 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.25
Configuration: /opt/atlassian/pipelines/agent/build/phpunit.xml.dist
Warning: Undefined array key "issuer" in /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php on line 24
...
Warning: Undefined array key "issuer" in /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php on line 24
Warning: Undefined array key "issuer" in /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php on line 24
..
Warning: Undefined array key "issuer" in /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php on line 24
.
Warning: Undefined array key "issuer" in /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php on line 24
.                                                             7 / 7 (100%)
Time: 00:22.806, Memory: 32.00 MB
OK (7 tests, 48 assertions)
```

I was surprised to find that when I set `SYMFONY_DEPRECATIONS_HELPER=disabled` this behavior went away and PHPUnit worked as expected, marking tests with warnings and actually returning error exit code as expected:
```
PHPUnit 10.5.20 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.25
Configuration: /opt/atlassian/pipelines/agent/build/phpunit.xml.dist
WWWWWWW                                                             7 / 7 (100%)
Time: 00:34.623, Memory: 78.00 MB
7 tests triggered 1 PHP warnings:
1) /opt/atlassian/pipelines/agent/build/src/TwoFactor/GoogleAuthenticator.php:24
Undefined array key "issuer"
Triggered by:
* App\Tests\Functional\ApplicationJobAdResourceTest::testPublicJobAdForPrivate (5 times)
  /opt/atlassian/pipelines/agent/build/tests/Functional/ApplicationJobAdResourceTest.php:338
OK, but there were issues!
Tests: 7, Assertions: 48, Warnings: 1.
```
Output is cut down version from pipelines, but the code behaves the same locally under Docker setup.

I believe this might be a bug, as deprecation related variables should not affect handling of PHP warnings and intended behavior of PHPUnit.

### How to reproduce

1. Add `SYMFONY_DEPRECATIONS_HELPER=weak` to `.env.test.local`
2. Create a test with something that will produce a warning such as accessing undefined array key
3. Run it with `vendor/bin/phpunit --fail-on-warnings`.

One would expect for it to mark tests as passed but with warnings, however it just marks them as fully passed. To test "expected behavior", change `SYMFONY_DEPRECATIONS_HELPER=disabled`.

### Additional Context

PHP 8.1.25 with default `php-development.ini` config.

**Comment by stof** [comment]
The symfony/phpunit-bridge does not support PHPUnit 10+ (in Symfony 7.2, we added support for PHPUnit 11 for features of the bridge other than the deprecation handling).

**Comment by mislavjakopovic** [comment]
> The symfony/phpunit-bridge does not support PHPUnit 10+ (in Symfony 7.2, we added support for PHPUnit 11 for features of the bridge other than the deprecation handling).

First of all thank you for fast reply.

This is interesting to me as I didn't notice that when updating to PHPUnit 10. Since the behavior of component in that case is unexpected though, I'd expect that `symfony/phpunit-bridge` would define conflict constraints for PHPUnit 10+.

Do you perhaps know is there any specific reason why that was not implemented?

**Comment by stof** [comment]
@mislavjakopovic PHPUnit 10 is a full rewrite of the internal implementation of PHPUnit, which is not compatible with what the deprecation handling feature of the bridge does (PHPUnit 10 rewrote entirely the way its error handler works, and we cannot use our own error handler there without breaking PHPunit).
If you use PHPUnit 10+, use the native handling of deprecations available in PHPUnit. But be careful that in PHPUnit 10, it is not feature-equivalent with the bridge, as some features were implemented only as part of PHPUnit 11. This is why Symfony itself will migrate to PHPUnit 11.3+ for it CI, without ever using PHPUnit 10 (this work is in progress)

**Comment by mislavjakopovic** [comment]
Understood, makes sense. Will try and remove `symfony/phpunit-bridge` and upgrade to PHPUnit 11.3+ in near future.

Thank you for these information, have a nice weekend!

**Comment by D3strukt0r** [comment]
@stof Would there be any downside to still using the PhpUnit Bridges version of the deprecation handling with PhpUnit 12? I can still achieve this by writing a PHPUnit Extension and calling `DeprecationErrorHandler::register(getenv('SYMFONY_DEPRECATIONS_HELPER'))` in there (or the `bootstrap.php`).

The native deprecation handling doesn't allow me yet to be informed about indirect deprecations without causing the test run to fail (https://github.com/sebastianbergmann/phpunit/issues/6484). Also, the native way is much more information-bloated, while the bridge's way is more compact and gives a better overview, so I'd prefer to use the bridge.

e.g. Symfony Configuration Deprecations (e.g. `doctrine.orm.proxy_dir`) fall under indirect (which is technically false, but I don't think it could be detected as a "self" deprecation), and probably many examples more. If we don't see those, they will never be tackled.

**Comment by stof** [comment]
The DeprecationErrorHandler is only one part of the setup of the bridge though. Registering it alone will conflict with the error handler of PHPUnit, and it might not allow you to make the testsuite fail properly on deprecations (the integration with the test runner is separate)

**Comment by D3strukt0r** [comment]
I see what you mean @stof, in another project the `self::expectUserDeprecationMessage` didn't work anymore. how would the integration with the test runner need to be done? even possible?

**Comment by stof** [comment]
No. That's why we consider that the deprecation reporting system of the bridge is supported only on PHPUnit 9 and older.

This system was relying on hacks to hook into the runner, and those hacks don't work anymore on PHPUnit 10+ due to the rewrite of the runner.
You need to use the native PHPUnit feature on PHPUnit 10+ (we recommend PHPUnit 11+ to have equivalent features)
