### ISSUE TITLE
Non-existent parameter "kernel.default_locale"

### ISSUE THREAD

**Issue by yaroslaw74** [symfony/symfony#59204]
### Symfony version(s) affected

7.3

### Description

I'm trying to configure StofDoctrineExtensionsBundle. In the stof_doctrine_extensions.yaml file, I set the stof_doctrine_extensions.default_locale parameter to '%kernel.default_locale%'. As a result, I get the error: "You have requested a non-existent parameter "kernel.default_locale" while loading extension "stof_doctrine_extensions"." There was no such error in Symphony 7.1.

### How to reproduce

stof_doctrine_extensions:
    default_locale: '%kernel.default_locale%'

**Comment by xabbuh** [comment]
I cannot reproduce this.  Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
