### ISSUE TITLE
[symfony-cli] Add symfony command tests:run for --webapp flag

### ISSUE THREAD

**Issue by malakanov** [symfony/symfony#59207]
### Description

When we create a new symfony app with flag --webapp by calling

`symfony new my_project_directory --version="7.2.x-dev" --webapp` (see [https://symfony.com/doc/current/setup.html](url)) 

the `symfony/test-pack` component is installed along with it.

After all for execute tests we need run command `php bin/phpunit`

It might be worth adding a feature to symfony command `tests:run` which will execute `php bin/phpunit`  for the case of new creation application with flag `--webapp`

### Example

Run all tests of the application which call `php bin/phpunit`

`symfony tests:run`

**Comment by alexandre-daubois** [comment]
I think this issue should be created in https://github.com/symfony-cli/symfony-cli

**Comment by malakanov** [comment]
Move to [https://github.com/symfony-cli/symfony-cli/issues/549](url)
