### ISSUE TITLE
Error with getReference and Attribute in Entity in Symfony 7 and Doctrine 3 

### ISSUE THREAD

**Issue by ebootingdev** [symfony/symfony#59216]
Hi everyone,

I have this case, which works fine:

```php
    //Entity
    /**
     * @var MainState
     */
    #[ORM\JoinColumn(name: 'id_state', referencedColumnName: 'id')]
    #[ORM\ManyToOne(targetEntity: MainState::class)]
    private $state;

    //Controller
    $entity->setState($this->entityManager->getReference(MainState::class, 1));
```

But when I do it this way:

```php
   //Entity
   #[ORM\JoinColumn(name: 'id_state', referencedColumnName: 'id')]  
   #[ORM\ManyToOne(targetEntity: MainState::class)]
    private ?MainState $state = null;
```

   //Controller
   This line doesn't work and throws an error:
```php
    $entity->setState($this->entityManager->getReference(MainState::class, 1));
```
```
    PHP Fatal error:
    Uncaught TypeError: Cannot assign __PHP_Incomplete_Class to property App\\Entity\\Entity::$state of type ?App\\Entity\\MainState
```  

I have to replace:

    $entity->setState($this->entityManager->getReference(MainState::class, 1));

with:

    $entity->setState($this->repositoryMainState()->find(1));

Why doesn't getReference work?
[composer.json](https://github.com/user-attachments/files/18143710/composer.json)
 

_Originally posted by @ebootingdev in https://github.com/symfony/symfony/discussions/59215_

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ebootingdev** [comment]
"I found the error:
https://stackoverflow.com/questions/965611/forcing-access-to-php-incomplete-class-object-properties
I was calling a session_start() beforehand, and that was causing the error."
