### ISSUE TITLE
Compatibility issue with Symfony 7.2.1: Symfony\Component\TypeInfo\Type::union(): Return value must be of type ... error

### ISSUE THREAD

**Issue by scorpion3dd** [symfony/symfony#59223]
### Symfony version(s) affected

7.2.1

### Description

After upgrading Symfony to version 7.2.1, my project stopped working with the following error:
Symfony\Component\TypeInfo\Type::union(): Return value must be of type Symfony\Component\TypeInfo\Type\UnionType, Symfony\Component\TypeInfo\Type\BuiltinType returned

The issue seems to be related to changes introduced in Symfony 7.2, specifically in the redesigned TypeInfo component, as explained in this blog post: [New in Symfony 7.2: Redesigned TypeInfo Component](https://symfony.com/blog/new-in-symfony-7-2-redesigned-typeinfo-component).

### How to reproduce

Steps to Reproduce:

Use Symfony 7.2.1.
Open any application page.
Expected Behavior:
The application page should be processed normally without any errors.

Actual Behavior:
The error mentioned above is thrown, and the application fails to start.
http://prntscr.com/Q8XV-Y0k2tzy

Steps Taken:
Updated all dependencies to their latest versions.
Cleared the Symfony cache (php bin/console cache:clear).
Verified that the error disappears when downgrading Symfony to version 7.2.1.

Please let me know if further details or logs are needed.

**Comment by xabbuh** [comment]
Can you confirm that in your source code you use something like `mixed|null` to describe type information?

**Comment by scorpion3dd** [comment]
I searched the project and actually found this line  mixed|null  :
http://prntscr.com/wht0YfMTRyJy
when this line is there - there is an error
when I deleted this line, the error disappeared and the page opens without errors

**Comment by mtarld** [comment]
I think [this PR](https://github.com/symfony/symfony/pull/59271) might fix the issue :slightly_smiling_face:
