### ISSUE TITLE
Php 8.4 Property Hooks not compatible with symfony interfaces

### ISSUE THREAD

**Issue by carl-sauter** [symfony/symfony#59222]
### Symfony version(s) affected

7.2.0

### Description

Getter in interfaces (for example UserInterface) are displayed as property hooks in my IDE (PhpStorm):
<img width="786" alt="image" src="https://github.com/user-attachments/assets/f6f20246-05db-48c4-9bbe-f7e39fe61a0e" />

But without explicitly adding the `getRole()` function (in this example) I get the following error: 
```
Attempted to call an undefined method named "getRoles" of class "App\Entity\Identity\InetOrgPerson".
```
although the roles property does exists. This also applies to other interfaces for example: PasswordAuthenticatedUserInterface.

### How to reproduce

Replace `getRoles()` function in the user implementing `UserInterface` with a public property `$roles`

**Comment by stof** [comment]
A property hook is **not** a getter method. So adding a public property does not satisfy an interface asking for a `getRoles` method (even if it uses a property hook, which is something that is purely internal to your class anyway).

There is no bug here. If you want to implement the interface, you need to implement the methods being defined in the interface. That's how PHP works.

**Comment by carl-sauter** [comment]
But does my IDE shows me the interface with property hooks and not the getter method. In addition the IDE doesn't blames me for not implementing a getRoles method. So it seems the php compiler is perfectly fine with this.

**Comment by stof** [comment]
The UserInterface you are showing here with a public property `$roles` instead of a `getRoles` method is **not** the interface defined in Symfony: https://github.com/symfony/symfony/blob/dd882dbbd4910dce577d5bd280920e259dd782a5/src/Symfony/Component/Security/Core/User/UserInterface.php#L47

Make sure you are not editing files in your vendor folder.

**Comment by carl-sauter** [comment]
Seems like PhpStorm is also editing files in the vendor folder when running their suggested refactoring to replace getter & setter with property hooks

**Comment by stof** [comment]
@Kinqdos make sure you enable their composer support, which marks the vendor folder as special in the project. And if it is already enabled and the refactoring still changes it, report a bug to Jetbrains.

**Comment by carl-sauter** [comment]
For anyone who wants to keep track of this

https://youtrack.jetbrains.com/issue/WI-80059/Propertyhooks-refactoring-changes-files-in-vendor-folder
