### ISSUE TITLE
Custom Password Strength Estimator not working

### ISSUE THREAD

**Issue by attilajakab** [symfony/symfony#59235]
### Symfony version(s) affected

7.2.*

### Description

Custom Password Strength Estimator not working when following the official guide, section **Customizing the Password Strength Estimation**:
https://symfony.com/doc/current/reference/constraints/PasswordStrength.html#customizing-the-password-strength-estimation

Results in error:
```
"Notice: Object of class App\\Validator\\CustomPasswordStrengthEstimator could not be converted to int"
```

In Symfony's `Symfony\Component\Validator\Constraints\PasswordStrengthValidator` in `validate` method the `$strength` variable should be of type integer, but instead it is the custom password strength estimator class object:
<img width="668" alt="image" src="https://github.com/user-attachments/assets/44ab8ffe-251a-428d-8c23-2f15db24f202" />

The `__invoke` method of the custom password strength estimator class not gets triggered:
<img width="266" alt="image" src="https://github.com/user-attachments/assets/3e4c1125-ed47-45f9-8173-b7db00fad4d9" />

### How to reproduce

Create custom password strength estimator following the official guide, section **Customizing the Password Strength Estimation**:
https://symfony.com/doc/current/reference/constraints/PasswordStrength.html#customizing-the-password-strength-estimation

Assert the `PasswordStrength` constraint on `User` entity's `password` field:
<img width="413" alt="image" src="https://github.com/user-attachments/assets/36eb9b0e-2b5f-4677-b273-472b287c7c8d" />

Create a form type for password creation on `User` entity:
<img width="349" alt="image" src="https://github.com/user-attachments/assets/d7115479-ce2b-4d97-85cb-ca4f5f34e1b5" />

Try to submit a password through the form. The follow error will be returned:
```
"Notice: Object of class App\\Validator\\CustomPasswordStrengthEstimator could not be converted to int"
```

### Possible Solution

It seems like on line 43 the custom password strength estimator class is instantiated, but then the object is not invoked, so the `__invoke` method of the customer estimator never gets triggered, thus not returning an integer, but it is the custom estimator class object itself inside `$strength` variable:
<img width="668" alt="image" src="https://github.com/user-attachments/assets/44ab8ffe-251a-428d-8c23-2f15db24f202" />

**The proposed fix** could be like this inside `Symfony\Component\Validator\Constraints\PasswordStrengthValidator` `validate` method:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/59710ff8-cb4e-41df-b9a4-948c2afe6a6e" />
Tested and is working as expected.

### Additional Context

Using PHP 8.3.

**Comment by stof** [comment]
How does your custom estimator looks like ?

**Comment by stof** [comment]
OK, found it. this is not a bug in the code but in the documentation. The `!service_closure` tag in the Yaml config file is about creating a ServiceClosureArgument, which injects a closure that returns a service. This is not the way to inject a callable that calls a service.

In https://symfony.com/blog/new-in-symfony-6-3-dependency-injection-improvements#using-autowiring-to-generate-closures, we announced new attributes for configuring autowiring. This `!service_closure` tag is the equivalent (for explicit configuration rather than autowiring) of what `#[AutowireServiceClosure]` does, while you need the equivalent of `#[AutowireCallable]`, which is provided by `!closure`:

```yaml
# config/services.yaml
services:
    custom_password_strength_estimator:
        class: App\Validator\CustomPasswordStrengthEstimator

    Symfony\Component\Validator\Constraints\PasswordStrengthValidator:
        arguments: [!closure '@custom_password_strength_estimator']

```

**Comment by stof** [comment]
I sent a PR fixing the documentation

**Comment by attilajakab** [comment]
@stof Thanks, it is working now as expected!

**Comment by xabbuh** [comment]
let's close here in favour of symfony/symfony-docs#20476 then
