### ISSUE TITLE
Typo in NoPrivateNetworkHttpClient resulting in PHP error

### ISSUE THREAD

**Issue by Jontsa** [symfony/symfony#59244]
### Symfony version(s) affected

7.1.0

### Description

It looks like there is a typo in NoPrivateNetworkHttpClient since Symfony 7.1.0. The client is accessing `$options` array key "header" when it should be "headers".

https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpClient/NoPrivateNetworkHttpClient.php#L141

```
$options['header'] = array_filter($options['header'], $filterContentHeaders);
```

results in error `Undefined array key "header"`.

### How to reproduce

n/a

### Possible Solution

Replacing "header" with "headers" fixes the issue

```
$options['headers'] = array_filter($options['headers'], $filterContentHeaders);
```

**Comment by stof** [comment]
Can you send a PR with the fix (and ideally with a test to prevent regressions) ?

**Comment by Jontsa** [comment]
#59250
