### ISSUE TITLE
HttpClient Response->getInfo contains unredirected url when getContent is not called first

### ISSUE THREAD

**Issue by ThomasBerends** [symfony/symfony#59284]
### Symfony version(s) affected

7.2.1

### Description

According to the ResponseInterface of the HttpClient, the getInfo call should contain "url (string) - the last effective URL of the request".

It does contain the url in both cases, but it returns the entered unredirected url when getContent() has not been called yet. If Response->getContent has been called, it will then return the correct url.

### How to reproduce

Reproducer here: https://github.com/ThomasBerends/http_client_reproducable
There's two commands, `app:expected` and `app:unexpected`.

Expected:
``` 
$response = $this->httpClient->request('GET', "https://www.php.net/notfound");
// Fetch content
$response->getContent();
// Get the correct (redirected) url
dump($response->getInfo()['url']);
// "https://www.php.net/manual-lookup.php?pattern=notfound&lang=en&scope=404quickref"
```

Unexpected:
``` 
$response = $this->httpClient->request('GET', "https://www.php.net/notfound");
// Get the correct (redirected) url
dump($response->getInfo()['url']);
// "https://www.php.net/notfound"
```

**Comment by nicolas-grekas** [comment]
getInfo didn't resolve any state, it just returns the current one. If you call it before the redirection happened, you get the state before.
Call getStatusCode for example if you don't want to wait for the whole content.

**Comment by ThomasBerends** [comment]
@nicolas-grekas Thanks for your reply. I expected ->request to only return the Response object when the request was fully complete. I understand now that is not the case. Thanks for the advice, I'll use getStatusCode instead.

**Comment by stof** [comment]
@ThomasBerends `request` does not wait, by design of the component. This is what allows to perform multiple concurrent requests (by requesting them all before waiting for their response states)
