### ISSUE TITLE
Count constraint docblock causes psalm and phpstan fail on max 0 value

### ISSUE THREAD

**Issue by aguerre** [symfony/symfony#59307]
### Symfony version(s) affected

7.2.0

### Description

This PR https://github.com/symfony/symfony/pull/58049 affected psalm and phpstan validation on Count constraint use:

<pre><font color="#C01C28">ERROR</font>: InvalidArgument - src/XXXX/Model/<font color="#C01C28"><b>MyModel.php:44:31</b></font> - Argument 1 of Symfony\Component\Validator\Constraints\Count::__construct expects int&lt;1, max&gt;|null, but 0 provided (see https://psalm.dev/004)
        new Assert\Count(max: <span style="background-color:#C01C28"><font color="#FFFFFF">0</font></span>),
</pre>

With 
```
    #[Assert\AtLeastOneOf([
        new Assert\Count(max: 0),
        new Assert\IsNull(),
        new AppAssert\IsValidSignature(),
    ])]
    private ?array $signature = [];
```
My $signature is an array of coordinates and can be empty for some frontend reasons.

### How to reproduce

Use Count constraint with max : 0 

### Possible Solution

Change @param max dockblock to accept zero

**Comment by xabbuh** [comment]
see #59310
