### ISSUE TITLE
Flash message are not in session when using a form

### ISSUE THREAD

**Issue by micter59** [symfony/symfony#59330]
### Symfony version(s) affected

7.2.1

### Description

I'm using flash message in many location of my app.
It display correctly everywhere except when I render a form.
I don't see why it should be different.

### How to reproduce

Below is the code of a method in a controller. This controller extends from abstractController. If i put the "addFlash" on an other route, where there is no form, the flash message display correctly.
In the "famille/new.html.twig" template, variable app.flashes is empty if I try to dump it.
```

#[Route('/new', name: 'famille_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $famille = new Famille();
        $form = $this->createForm(FamilleType::class, $famille);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->familleManager->save($famille);
            return $this->redirectToRoute('famille_index', [], Response::HTTP_SEE_OTHER);
        }

       $this->addFlash("success", "test notif depuis famille_new");

        return $this->render('famille/new.html.twig', [
            'famille' => $famille,
            'form' => $form
        ]);
    }

```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by micter59** [comment]
If I create a github repo, would it be ok for you ? Maybe I can isolate a small part of my app, and put it on a public repo.

**Comment by xabbuh** [comment]
Yes, having a repository on GitHub one could check out to reproduce your issue would be great.

**Comment by micter59** [comment]
I did copy the minimum of files to recreate the issue, but now there's no issue. So I understand I will have to look through what I add to these minimum files to see what cause the problem. I'll close this issue, as the problem seems to come from something in my code. Next time I'll do this before posting an issue... Thank you.

**Comment by smaniren** [comment]
did you find the problem?

**Comment by micter59** [comment]
No. At the time of the problem, I took the minimum set of files to recreate the issue, and I never could reproduce. So I took this minimum set of file, and added the rest of the project progressively.
