### ISSUE TITLE
[Form] PropertyPath with null values in the path

### ISSUE THREAD

**Issue by morgen2009** [symfony/symfony#5936]
Actually, this is not clear issue of PropertyPath, but I do not know, what behaviour would be best. If one of properties within the path is null, the PropertyPath could not compute the next one in the sequence and breaks with exception.

The use case is a form to edit and create new wares, where the user can edit human frendly ware nummer instead of id. The datatransformer cares about the conversion nummer => ware. For new items, this construction breaks, because PropertyPath could not compute path.

```
    $form
        ->add('article', 'text', array('property_path' => 'ware.article'))
        ->add('count')
        ->add('price')
    ;
```

**Comment by ryancastle** [comment]
I think ignoring nulls makes sense, if nobody can come up with anything more robust. If it's null I think it could essentially fall back to `'mapped' => false`.

Although perhaps the best real-world solution is just to use an event listener, so you can hide the field from the form altogether when there is nowhere for the data to live. Quietly throwing away user submitted data isn't fantastic.

**Comment by xabbuh** [comment]
I am closing this old issue. It seems no-one cared enough about it and I am also not sure we can/should handle this in the Form component itself.
