### ISSUE TITLE
[Form] Improve default form error messages

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#5946]
I think that in order to provide a better user experience, we should improve the error messages shipped with the Form component by default. I am **not** talking about the error messages in the Validator component.

If I use the Validator component stand-alone, getting an error such as "This value is not a valid number" is fine. If I use the Form component, displaying that message for a form field is a bit awkward. Even worse are the tons of "This value is invalid" messages.

I suggest to
1. Set sensible defaults for the "invalid_message" options in all core types. These defaults should be user friendly, such as "Please enter a valid email address." (or better, if you have suggestions)
2. Duplicate the error messages of the Validator component into the Form component and change the translations to be more user friendly (in the web form context, again, such as "Please enter a valid number" or better). This will mean a bit more maintenance work, but much better UX.

Opinions? How would you ideally like the error messages to be when you submit an erroneous field?

**Comment by ShinDarth** [comment]
so there was a PR for this and then it was closed, is it still valid?

**Comment by chalasr** [comment]
Indeed, it seems there is not enough interest/feedback on this issue, same for a bunch of similar (old) ones.

**Comment by hiddewie** [comment]
Based on symfony/symfony#14106, I've made #27142.

**Comment by xabbuh** [comment]
As I wrote in https://github.com/symfony/symfony/pull/27142#issuecomment-421545459 the new messages would be a BC break for everyone relying on the old ones for custom translations and for those languages where we cannot provide new translations (could be solved by generic translations though). To mitigate this we would need to introduce an option that would allow to opt into the improved messages. I am not sure if we want to do that.
