### ISSUE TITLE
[Translation] Add support for the MessageFormatter class

### ISSUE THREAD

**Issue by hason** [symfony/symfony#6009]
Instead of reinventing wheel in #4797, #4884, #5547,  we should use the [MessageFormatter](http://www.php.net/manual/en/class.messageformatter.php) class. Read more:
- http://userguide.icu-project.org/formatparse/messages
- http://www.zyxist.com/en/archives/134
- https://github.com/auraphp/Aura.Intl/blob/develop/src/Aura/Intl/IntlFormatter.php
- https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php

**Comment by shehi** [comment]
Question: I came here searching for gender-specific translation capability - is this topic being actively discussed and/or developed?

**Comment by fkrauthan** [comment]
Any news on progress for this?

**Comment by Koc** [comment]
@fkrauthan see linked PRs above

**Comment by HeahDude** [comment]
@fkrauthan Will soon be closed by https://github.com/symfony/symfony/pull/18314 :)

**Comment by fkrauthan** [comment]
@HeahDude I just skipped thru that article and it seems like the step into the right direction but it seems like that https://github.com/webfactory/icu-translation-bundle would still be superior as it allows you to mix multiple formattings (e.g. select for gender + count + number formatting for count - see https://github.com/webfactory/icu-translation-bundle/blob/master/Resources/doc/index.rst#nested-conditions). Or will that be possible with #18314 too?
