### ISSUE TITLE
[HttpKernel] HttpCache Store uses headers for matching

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#6024]
see https://github.com/symfony/HttpKernel/blob/master/HttpCache/Store.php#L127

as things are currently if one f.e. wants to modify the cookies, one needs to modify the headers `cookie` value and not the parsed cookies.

this complicates the process quite a bit:
https://gist.github.com/4078842

we initially expected that we could simply modify the cookie bag:

```
    private function removeUnusedCookies(Request $request)
    {
        foreach ($request->cookies as $key => $value) {
            if (!in_array($key, $this->cookieWhitelist)) {
                $request->cookies->remove($key);
           }
        }

        return $request;
    }
```

I am not sure what the best approach is here .. should we just have special handling for cookies in `Store` (which might lead to a BC break)? Should we just provide some helpers to make it easier to modify cookies like in the above gist?

**Comment by mpdude** [comment]
@lsmith77 is this still an open issue for you?

**Comment by lsmith77** [comment]
well haven’t come across this in maaaaany years. so I guess no
