### ISSUE TITLE
[FrameworkBundle] bundle:install / remove commands

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#6082]
I have been thinking about this for a while and I think the best way to have bundles added to the kernel etc when you install one from composer is to do this from the symfony console.

The main issue is that if it's done with a composer hook/script, it'll fire at random when you install an old bundle, or if you upgrade a bundle it will remove/install it if it's installed as a zip. Lots of issues.

On the other hand, a bundle:install command could take a package name, install it via composer, and once installed prompt you if it should be enabled for all envs or only dev/test, and prompt if it should register a config/routing/.. automatically. Similarly bundle:remove would clean up the config, routing and whatnot, instead of leaving users with all that dirty work to do.

The downside is it probably means having composer as a dependency of the command.

**Comment by Ener-Getick** [comment]
I just discovered this thread... and ironically I created [a bundle for that](https://github.com/EXSyst/QuickInstallBundle) last week.
It uses Sensio's `KernelManipulator` to add bundles to the app kernel and can configure bundles  (the bundles most provide a configurator for that).

Would you like to restart talking about that?

**Comment by xabbuh** [comment]
Imo this is something that doesn't belong to the core. How often does one really need something like this?

**Comment by Ener-Getick** [comment]
@xabbuh this is useful each time you install a bundle (so mostly at the begining of a project).
It is something only for dev env so i agree, i'm not sure this belongs to symfony, maybe we could integrate such command in a sensio bundle?

**Comment by gnugat** [comment]
Surely this can now be closed, thanks to Symofny Flex?

**Comment by fabpot** [comment]
Indeed!
