### ISSUE TITLE
[Security][Feature request] Extend AclProvider and AclVoter interfaces

### ISSUE THREAD

**Issue by jalliot** [symfony/symfony#6170]
Hi all,

The ACL subcomponent is quite powerful today but there are two features that are not made easy to use:
* Class ACEs
* Class field ACEs

Indeed, in order to use those, you need to already have a domain object.
But what if you want to setup a class (or class field) ACE on some SID to authorize one operation on all existing and future objects, maybe even before there is an existing one.
Today you cannot without creating a "fake" OID by hand (with for instance `ID=0`).

The MutableAclProviderInterface should be extended to allow creating class (and class field) ACEs without OID but only a class name.

Besides, the AclVoter should also be extended in order to support passing a class name instead of a domain object. If a class name is passed, then the voter will only look for class and class field ACEs.
That would be useful for instance for a `CREATE` permission that you would setup on class ACEs and that would allow some SIDs to create domain objects for that particular class.

The latter point should also be implemented in [JMSSecurityExtraBundle](https://github.com/schmittjoh/JMSSecurityExtraBundle) in expressions (which, IIRC, do not even support object field ACEs at the moment).

/see schmittjoh/JMSSecurityExtraBundle#60

/cc @schmittjoh

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
