### ISSUE TITLE
[Form] Rename "always_empty" in PasswordType to "reset_on_submit"

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#6325]
Right now, the naming of that option is a bit misleading (see #5855).

This change can be done once the terminology of *binding* has been changed to *submitting* (see #5493).

**Comment by fabpot** [comment]
What do we do here? IMO, keeping the current name is the best option; deprecating something by renaming by something else that is not much clearer is probably adding too much work for everything for a very small benefit. So, I'm :-1:

**Comment by webmozart** [comment]
What about "show_submitted_data"?

```php
$form->add('password', 'password', array(
    'show_submitted_data' => true,
));
```

By default, the option value would be `false` (submitted data is not shown).

**Comment by juliendidier** [comment]
@webmozart :+1:

**Comment by romqin** [comment]
:+1:

**Comment by fabpot** [comment]
Closing as there is no consensus on the new name and doing that after 2.8 will not be an option anymore.
