### ISSUE TITLE
[Console] Make text output of HelpCommand docopt compliant

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#6329]
The whole thing already feels like [docopt](http://docopt.org/) a bit - but by changing a few things, adding default values etc I think we could do better.

Another thing that might be good in addition to having ->setHelp() in the commands is a ->setUsage() that would take an array of usage examples that can be dumped on top of the help text in the Usage section.

**Comment by fabpot** [comment]
What about closing this one? I don't think it would add much value.

**Comment by Seldaek** [comment]
IMO it's a good thing for consistency/user expectations and following standards, but if nobody does it it definitely has no value :)

**Comment by WouterJ** [comment]
I agree with @Seldaek. I also thought @fabpot also loved to follow available standards as much as possible :)

**Comment by fabpot** [comment]
If nobody cared in the last two years, it probably means that it's not that important :) But again, if someone wants to work on something, I'm open to review the patch.
