### ISSUE TITLE
[3.0] [Form] should rebind if data was changed in event and validation fails

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#6399]
I have the form with 3 fields integer, and 2 dates, In the bind event I change the order of the dates so they are in ascending order. Everything works just fine, if there is no error in the integer field. However if the validation of  the form fails, that changed order is not replicated and the field values stay as the user has submitted them. IMHO the changed fields should be bound again in case that validation fails.

``` php
$builder->addEventListener(FormEvents::BIND, function (FormEvent $event) {
    if (null === ($data = $event->getData())) {
        return true;
    }

    //start date should be smaller than end date
    if ($data->getEndDate() < $data->getStartDate()) {
        $ed = $data->getEndDate();
        $data->setEndDate($data->getStartDate());
        $data->setStartDate($ed);
    }
    $event->setData($data);

    return true;
});
```

**Comment by szymach** [comment]
Why not add a middleware container to the form instance? So basically you would pass some data into the form, it would make a copy of the values it uses and only that copy would actually be subject to change during form submission. Then, when form is valid, you update the underlaying array or object instance. I know this brings up tons of issues as well (like how to handle fetching data in form events), but maybe this is something to go on?

**Comment by xabbuh** [comment]
@mvrhov Is this still relevant? If so, can you create a small example application? I am not sure I understand your use case.

**Comment by mvrhov** [comment]
Sorry, but I have no idea. I don't know even in which project I needed this.
I've also moved completely from PHP/Symfony to go, so this should be a nonissue to me.
