### ISSUE TITLE
[3.0] [HttpFoundation] clean up/redesign Request class

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#6406]
There are several inconsistent method names and I think the class can be better designed.
- Synchronization of setters, getters, and parameter bags (server etc.) is unclear and inconsistent. For example there is a `setMethod` method which also modifies the ServerBag but there is no `setPath`. So either a Request should be immutable or mutable. But we have a mix of it. Furthermore, some getters a cached like `getPathInfo` and some are not like `getHost`. So when modifying the public parameter bags, sometimes it has influence on the Request getters and sometimes not. See also #10478
- `getUriForPath` is wrong. The correct name according to the current behavior would be `getUriForPathInfo`
- the names for `getBaseUrl` and `getBasePath` are both unfortunate because the only difference is the inclusion of the script file name and has nothing to do with URL vs path.

<del>The method name for `Request::getPathInfo()` is so bad because
1. it returns the path of a URI and not a "path info" (there is no such thing in the URI spec)
2. it suggest to return "more info" in form of an array like the php function [pathinfo](http://php.net/manual/en/function.pathinfo.php]) does, but it only returns the plain path
So the name is really confusing as it does not behave similar to phps pathinfo() and is also semantically wrong.
I suggest to deprecate `getPathInfo()` and introduce `getPath()`.
Working with it bothered me ever since. And I think we should fix that now before it's too late.</del>

Changing some names like `baseUrl` (that also does not exist in CGI terms) will need to be reflected in the routing component as well.

**Comment by Tobion** [comment]
PSR-7 looks good to me. So IMO Symfony 3.0 Request/Response should be based on that.

**Comment by andig** [comment]
> So IMO Symfony 3.0 Request/Response should be based on that.

Is there any specific work going in that direction? I've recently ported our app (https://github.com/volkszaehler/volkszaehler.org) to HTTPKernelInterface (and ReactPHP...) and would like to understand where to go with this once PSR-7 is alive.

**Comment by jrobeson** [comment]
@andig : that might depend on if we can get a PSR for HttpKernelInterface too. once PSR-7 is voted on, then hopefully we can move towards that.

**Comment by ewgRa** [comment]
> So either a Request should be immutable or mutable
I make some profiling and realize that isSecure, getHost and so on methods usually return same result, because headers and server bags that is involved in results of this methods usually is not changed. And for now there is a lot of unnecessary calculations. Immutable request can help to avoid them.

**Comment by andig** [comment]
> There are several inconsistent method names and I think the class can be better designed.

I would like to add that the constructors (if not using the factory methods) make it easy to create inconsistent representations. If I e.g. construct with `$request` parameters but forget `$content`, the request object will itself represent something that doesn't exist in HTTP. I was wondering if such logical inconsistencies should be errored or warned (probably not) or corrected by the `Request` implementation?

If off-topic please ignore.
