### ISSUE TITLE
Yaml parsing of serialized PHP objects within array

### ISSUE THREAD

**Issue by dtrethewey** [symfony/symfony#6498]
Yaml parser fails with error:

```
[ErrorException]                                                                                                                                                 
  Notice: unserialize(): Error at offset 118 of 117 bytes in 
/home/darren/dev/chasingworlds/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php 
line 381
```

Simple example:

``` php
    $yaml = 'test: { key: "value", date: !!php/object:O:8:"DateTime":3:{s:4:"date";s:19:"2012-12-25 00:00:00";s:13:"timezone_type";i:3;s:8:"timezone";s:13:"Europe/London";} }';
    $result = \Symfony\Component\Yaml\Yaml::parse($yaml);
```

The error is due to the regex within **Inline::parseScalar** stripping off the closing bracket of the serialized PHP object, because a "}" is a delimiter and is not included in the match:

``` php
    elseif (preg_match('/^(.+?)('.implode('|', $delimiters).')/', substr($scalar, $i), $match)) {
        $output = $match[1];
        $i += strlen($output);
    }
```

A very hacky fix is to replace the case statement in **Inline::evaluateScalar** for PHP objects with:

``` php
    case 0 === strpos($scalar, '!!php/object:'):
        $scalar = substr($scalar, 13);
        if(substr($scalar, -1) != '}') {
            $scalar .= '}';
        }
        return unserialize($scalar);
```

I'm sure there is a much more elegant solution by improving the regex expression to include a check for the PHP object...but I don't get on well with regex :(

If I get the chance I may look into it myself, but my hacked fix is working for what I need and I've got stacks I want to get on with first.

**Comment by xabbuh** [comment]
reopen as we actually didn't remove the feature

**Comment by Ener-Getick** [comment]
I think the real problem here is that it isn't really compliant to the yaml spec.
What do you think about replacing the current syntax (eg `!php/object:b:0;`) by a safer one `!php/object "b:0;"`?

**Comment by xabbuh** [comment]
see #24464

**Comment by xabbuh** [comment]
closing for the reasons given by @GuilhemN in https://github.com/symfony/symfony/pull/24464#issuecomment-335021061
