### ISSUE TITLE
[Form] 12H format for Time Field

### ISSUE THREAD

**Issue by tworzenieweb** [symfony/symfony#6587]
Is there a way to use 12H format in Time Field?

**Comment by lologhi** [comment]
:+1:

**Comment by jarofgreen** [comment]
+1 please https://github.com/OpenACalendar/OpenACalendar-Web-Core/issues/379

**Comment by jarofgreen** [comment]
So I've just been digging into this and I see what may be an easy answer, at least in "choice" mode ....

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php

Has this in it:

     $hours = $minutes = array();
                foreach ($options['hours'] as $hour) {
                    $hours[$hour] = str_pad($hour, 2, '0', STR_PAD_LEFT);
                } 

This is what is passed to the Hours dropdown widget. This has the effect of splatting over whatever values you try to pass it, and crucially, splatting over whatever keys and values you try to pass.

If I replace the code with

                foreach ($options['hours'] as $value=>$hour) {
                    $hours[$value] = $hour;
                }

And then set up my form like this:

    $hours = array(
			0=>'midnight',
			1=>'1am',
			2=>'2am',
			3=>'3am',
			4=>'4am',
			5=>'5am',
			6=>'6am',
			7=>'7am',
			8=>'8am',
			9=>'9am',
			10=>'10am',
			11=>'11am',
			12=>'noon',
			13=>'1pm',
			14=>'2pm',
			15=>'3pm',
			16=>'4pm',
			17=>'5pm',
			18=>'6pm',
			19=>'7pm',
			20=>'8pm',
			21=>'9pm',
			22=>'10pm',
			23=>'11pm',
		);
    $startOptions = array(
			'date_widget'=> 'single_text',
			'date_format'=>'d/M/y',
			'model_timezone' => 'UTC',
			'view_timezone' => $timeZoneName,
			'hours'=> $hours,
		);
    $builder->add('start_at', 'datetime' , $startOptions);

It works!

![screen shot 2015-04-13 at 10 57 50](https://cloud.githubusercontent.com/assets/85656/7113463/0306dcd0-e1cc-11e4-9ea4-aa1fee479d02.png)

Obvs, this is not a patch that could be applied right away. The str_pad stuff that was there before was there for a reason and can't just be removed. A proper patch would have to check if user had passed keys and values and use them if so, or do the str_pad stuff if not.

But hopefully this will reformulate this bug report: in "choices" mode, the Time widget splats all over key/value data in hours and if this was fixed developers could specify 12 hour, 4 hour or whatever odd hour scheme they liked really easily.

**Comment by jarofgreen** [comment]
Looking at this again quickly, I would guess the proper thing to do is set the default and let programmers override this. Oh, and this applies to minutes and seconds to.

```
diff --git a/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php b/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php
index 49f77c5..a7e9f83 100644
--- a/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php
+++ b/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php
@@ -55,33 +55,17 @@ class TimeType extends AbstractType
             );
 
             if ('choice' === $options['widget']) {
-                $hours = $minutes = array();
-
-                foreach ($options['hours'] as $hour) {
-                    $hours[$hour] = str_pad($hour, 2, '0', STR_PAD_LEFT);
-                }
-
                 // Only pass a subset of the options to children
-                $hourOptions['choices'] = $hours;
+                $hourOptions['choices'] = $options['hours'];
                 $hourOptions['placeholder'] = $options['placeholder']['hour'];
 
                 if ($options['with_minutes']) {
-                    foreach ($options['minutes'] as $minute) {
-                        $minutes[$minute] = str_pad($minute, 2, '0', STR_PAD_LEFT);
-                    }
-
-                    $minuteOptions['choices'] = $minutes;
+                    $minuteOptions['choices'] = $options['minutes'];
                     $minuteOptions['placeholder'] = $options['placeholder']['minute'];
                 }
 
                 if ($options['with_seconds']) {
-                    $seconds = array();
-
-                    foreach ($options['seconds'] as $second) {
-                        $seconds[$second] = str_pad($second, 2, '0', STR_PAD_LEFT);
-                    }
-
-                    $secondOptions['choices'] = $seconds;
+                    $secondOptions['choices'] = $options['seconds'];
                     $secondOptions['placeholder'] = $options['placeholder']['second'];
                 }
 
@@ -190,9 +174,9 @@ class TimeType extends AbstractType
         };
 
         $resolver->setDefaults(array(
-            'hours' => range(0, 23),
-            'minutes' => range(0, 59),
-            'seconds' => range(0, 59),
+            'hours' => array_map(function($hour) { return str_pad($hour, 2, '0', STR_PAD_LEFT); }, range(0, 23)),
+            'minutes' => array_map(function($mins) { return str_pad($mins, 2, '0', STR_PAD_LEFT); }, range(0, 59)),
+            'seconds' => array_map(function($secs) { return str_pad($secs, 2, '0', STR_PAD_LEFT); }, range(0, 59)),
             'widget' => 'choice',
             'input' => 'datetime',
             'with_minutes' => true,
```

If someone from the project gives the nod that this could be a good option, I'm happy to boot up a VM with PHP 5.5 so I can test this against the branch master which I notice is branded V3? Would be cool to get this in that.

**Comment by yvoloshin** [comment]
Hi @jarofgreen ,
Thank you for introducing this patch! I'm trying to implement it by creating an extension of TimeType (named MyTimeType) in my project and adding your changes to the extension. MyTimeType was added to config.yml under `doctrine: dbal: types: time: 'MyTimeType\location'`. The problem is that the property I'm trying to enter in 12-hour format belongs to DateTimeType, not TimeType. As far as I understand, DateTimeType uses DateType and TimeType to create a DateTimeType object. My question is, how can I direct DateTimeType to use MyTimeType instead of TimeType? 
Thank you for any help!

**Comment by jarofgreen** [comment]
Hello @yvoloshin - I have been meaning to sit down and make this into a separate package I could use for ages .... if you have any luck with this please let me know!
In answer to your question .... I would have to have a good look again - but I think from memory I was thinking I was going to have to clone DateTimeType to - just to get it to use the new TimeType! 
I do mean to get to this - just have so many other things on my to-do list! Please let me know if you have success.

**Comment by yvoloshin** [comment]
Thanks for the reply @jarofgreen! I haven't been able to get anywhere with this and decided to leave it as 24-hour format. Your future package would super useful!

**Comment by musicjerm** [comment]
In my case, I wanted to use a single_text widget to use with the bootstrap-timepicker plugin.  A simple workaround is to use a text field and set up a data transformer to convert to and from a datetime object with `format("h:i A")`.

**Comment by joshforcier** [comment]
In case anyone else finds this, here is how I did it.

In my form:

            ->add('StartTime', TimeType::class, array(
                'placeholder' => array(
                    'hour' => 'Hour',
                    'minute' => 'Minute',
                ),
                'label' => 'Start Time',
                'required' => false,
                'widget' => 'single_text' // this is key

Which gave me an input like this:
![capture](https://user-images.githubusercontent.com/25648233/51937247-c0b80a80-23cf-11e9-9c79-926fc45322a8.PNG)

    <input type="time" id="calendar_StartTime" name="calendar[StartTime]" class="form-control">

Which automatically saves in my db as 24-hour time.

**Comment by seb-jean** [comment]
This feature would be really cool!

**Comment by kingchills** [comment]
Anyone else running into this, I am currently using a workaround of resetting the view transformers, and adding my own view transformer with the the format of the data i am using.  

`$builder->get($field)->resetViewTransformers()
                ->addViewTransformer(new DateTimeToStringTransformer(null, null, 'g:ia'));`

**Comment by xabbuh** [comment]
I am closing this old issue as it seems that noone cared enough to implement it.
