### ISSUE TITLE
[Form] Add options "min" and "max" to NumberType

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#6732]
Hi,

At the moment, using the Range validation constraint, we can set up a min & max for a numeric value in an entity property.

Html5 offers min & max attributes for number inputs, so we can also enforce this client-side in any form:
```php
$builder
    ->add('aNumber', 'number', array(
            'attr' => array('min' => 1, 'max' => 100)
    ))
```

It may be nice to offer min & max options for number field type. It seems pretty logical, as some other fields already have such attributes (ie `max_length` for text fields).

The syntax may be:
```php
$builder
    ->add('aNumber', 'number', array(
            'min' => 1,
            'max' => 100
    ))
```
These attributes will be used client-side & the submitted object will be validated too.

What do you think?
I'm ok about contributing the code (& tests & doc), but I wanted the idea to be reviewed first.

**Comment by hhamon** [comment]
+1

**Comment by Tobion** [comment]
What's the point of adding these options instead of using attr? All attributes that have no backend logic have actually been removed, e.g. max_length, pattern, read_only. So I'm rather -1 on doing the same thing with two different approaches.

**Comment by webmozart** [comment]
As I said, I'm also against adding options if we can also use the attributes. See #15014.

**Comment by mohamedchibani** [comment]
thank you
