### ISSUE TITLE
[Translation] Multiple problems

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#6765]
Hi!

We are having a hard time working with translations, mainly with the translation:update command.

Here is a list of issues (sorry, its gonna be a long one :)):

# 1. PoFileDumper #

Po files should not be dumped without a header. It causes a lot of problems, including charset issues.

	msgid ""
	msgstr ""
	"Content-Type: text/plain; charset=UTF-8\n"
	"Content-Transfer-Encoding: 8bit\n"
	"Project-Id-Version: \n"
	"POT-Creation-Date: \n"
	"PO-Revision-Date: \n"
	"Last-Translator: \n"
	"Language-Team: \n"
	"MIME-Version: 1.0\n"
	"X-Generator: Poedit 1.5.4\n"

This header is generated by poedit, a popular editor.

An absoulute minimum would be the first 4 lines, with an empty line after it.

# 2. PotFileDumper #

POT is a nice addition to PO, it makes work easier. Should be available.

# 3. TranslationLoader #

Translation loader should not be local aware.

	$extension = $catalogue->getLocale().'.'.$format;
	$files = $finder->files()->name('*.'.$extension)->in($directory);

As you can see, right now it only loads files for the given locale. Some formats (like POT) are not localized yet, and even localized formats should include all translation keys, regardless of the locale. Its **very** hard to keep track of your translation files if you have to do it manually, and working on an international app with 5+ languages.

# 4. TranslationUpdateCommand #

## 4.1. Extraction ##

The command should try to extract keys from: twig, php, forms (I don't know if there any more)

Right now its only working for twig.

## 4.2. Bundle / Namespace ##

Right now it only works for a single bundle. It should work for namespaces as well. Furthermore, we sould be able to dump all translations into one file per locale. Translators are very confused by the per bundle approach, and they are right.

# 5. TwigExtractor #

Fixed by 83382bc7986ffe6322f8078af816f226d65737c0

Twig extractor should work with trimmed messages.

	$catalogue->set($message[0], $this->prefix.$message[0], $message[1] ? $message[1] : $this->defaultDomain);

Should change this to:

	$catalogue->set(trim($message[0]), $this->prefix.trim($message[0]), $message[1] ? $message[1] : $this->defaultDomain)

# 6. PR #

I would gladly make a PR for this, in fact I did a first version a while back, #6191, I would just have to iron out some details. Unfortunately no response what so ever until now and it's not the kind of issue that you can just create a bundle for.

Any notes would be greatly appreciated.

Thanks.

**Comment by fabpot** [comment]
Closing this meta issue. Feel free to reopen tickets for things that are not fixed yet.
