### ISSUE TITLE
[Translation] Need to create dummy files, when using eg. DB translation loaders

### ISSUE THREAD

**Issue by canni** [symfony/symfony#6930]
For now, if you want to load messages from for example DB, or other external source,
when you implement yours custom `LoaderInterface` class, an register is as a loader service, it shows that this doesn’t work out-of-the-box.

For example you register custom Loader aliased `db`; for that to work, you have to create a dummy empty file under Bundle's translations folder - for every domain and locale you have in DB:
- messages.en_us.db
- messages.pl_pl.db
- app.en_us.db

etc...

This is because Framework's Bundle omits loaders that [don't use files](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Translation/TranslationLoader.php#L54)

Fixing this will probably be a BC break, so before I post PR for that I want to hear some feedback :)

**Comment by mpdude** [comment]
Close in favor of #6978?

**Comment by mpdude** [comment]
I think this issue should be closed; see my remarks in #6978 how to make this work.
