### ISSUE TITLE
[Form] Support format without "y", "M" or "d" in DateField

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7147]
DateField should support formats that don't contain the letters "y", "M" or "d" in order to select partial dates (e.g. months). The default values of the fields, when left away, should be the corresponding parts of the UNIX base timestamp 1970-01-01.

Example:

``` php
$builder->add('expires_at', 'date', array(
    'format' => 'MMyyyy',
));
```

A date submitted here will always have day "1", e.g. "2013-02-01".

Further related work:

TimeType currently supports the "with__" options for achieving this functionality (including or excluding single parts of the time). We should think about deprecating the "with__" options and supporting a "format" option instead, if this improves consistency.

**Comment by DanielBadura** [comment]
Any news on this?

**Comment by mvrhov** [comment]
@DanielBadura Nobody is working on this feel free to implement and crate apull request.

**Comment by xabbuh** [comment]
I am closing this old issue as it seems that noone cared enough to implement it.
