### ISSUE TITLE
[Form] Deprecate `max_length` option

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7148]
There is no logic behind the `max_length` option except for setting the `maxlength` attribute in the HTML tag. Consequently, the option should be removed and usages changed to:

```php
$builder->add('field', 'text', array(
    'attr' => array('maxlength' => ...),
));
```

**Comment by WouterJ** [comment]
This can be closed as it was fixed with https://github.com/symfony/symfony/pull/10001
