### ISSUE TITLE
[Config] RFC - Simplify and redesign ResourceInterface

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#7176]
Currently, [Config/ResourceInterface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Resource/ResourceInterface.php) and its implementations serve a single purpose - that is, checking whether data from a ConfigCache is still valid. For that, the cache is associated with a set of Resources which can later be checked for freshness. ConfigCache seems to be the only client of ResourceInterface right now.

The problem with the interface is that it somewhat assumes that resources are filesystem objects. Just as Loaders (Config/Loader/LoaderInterface) can load about anything, the same should be true for Resources.

For example, it is no problem to have a loader pull some information (think of translations) from a database. At a later time, you might need to check if the generated message catalogue is still up to date.

Implementing ResourceInterface in this case is difficult - __toString() and getResource() hardly make sense for "translations from a database", and at least to getResource() is the Loader's job. Anyway, both methods are not used by ConfigCache as the current sole client. 

__Freshness check based on timestamp__

Checking isFresh($timestamp) - which means "is the Resource still the same as it was at $timestamp" - might also be implemented differently for the said database. 

The $timestamp need not be a timestamp but just an opaque identifier (think ETag). Even more, as Resource implementations being serialized carry resource type-specific data anyway (a filename, for example), the entire way of validating them should be encapsulated in the Resource. That is, a Resource could upon creation get or keep what it needs for validation. 
For example, a FileResource would grab the mtime() of the underlying file, keep it along with the filename (in its serialized form) and later on (when unserialized) check the mtime() again, comparing the two values.

__A more simple, self-validating Resource interface__

All this would lead to a ResourceInterface like

````
namespace Symfony\Component\Config\Resource;

interface ResourceInterface
{
    /**
     * Returns true if the resource has been updated since it has been created.
     * @return Boolean true if the resource haseen updated, false otherwise
     */
    public function hasChanged();
}

````
*plus* the requirement the implementors are (un)serializable without side effects.

__Resource checks using services__

I also [made a suggestion](https://github.com/symfony/AsseticBundle/issues/168#issuecomment-13608074) how  Resource validation could be shifted from the Resource implementation to some kind of "voter" or "checker" class which allows for using services (a database connection, a loader implementation) during the check which is not possible if the check has to be within the unserialized resource.

That would even leave Resource as a marker interface and have the "voter" implement a single "hasChanged(Resource $r)" method.

__To sum up__

I think simplifying the ResourceInterface would be a good thing to do because
* it adds conceptual clarity
* yields a segregated interface
* allows for new Resource types that can reflect what loaders can already do

Shifting the freshness check from Resource implementations to some kind of "voter"/"checker" additionally makes it possible to use services for validation, being a solution for [at least one issue](https://github.com/symfony/AsseticBundle/issues/168).

Opinions please. Will do the work if others agree :-).

__Update__: The current WIP is #7230.

**Comment by mpdude** [comment]
@stof What do you think? This is an old issue and not entirely up to date, but maybe something worth discussing for 3.0?

**Comment by stof** [comment]
@mpdude yes, it would be great to solve this issue. We would have to re-evaluate #7230

**Comment by mpdude** [comment]
@stof What is the right way to change or deprecate an interface for 3.0? I don't see how this could be done with deprecation error messages.

**Comment by apfelbox** [comment]
@mpdude I think adding the PHPDoc and a global trigger_error in the head of the file.

**Comment by mpdude** [comment]
Ok, and what about removing methods from an interface?

**Comment by mpdude** [comment]
@stof #15692 is the first step towards this, would be great if you could have a look at it.
