### ISSUE TITLE
[Routing] add support for optional placeholders in the host

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#7306]
Optional placeholders are not implemented yet for the host (unlike the path). 
So given `{subdomain}.domain.com` it cannot match `domain.com` because the dot is statically required.

Ref. #6821

**Comment by beccha** [comment]
+1

**Comment by mowcixo** [comment]
+1

**Comment by vitalyiegorov** [comment]
+1

**Comment by jonathanbull** [comment]
+1

**Comment by eversonaraujo** [comment]
+1

**Comment by nicolas-grekas** [comment]
Anyone willing to submit an implementation?

**Comment by nicolas-grekas** [comment]
Actually there was one which has been closed unreviewed: #10254
Anyone willing to take over/review/try/validate/etc., please do!

**Comment by Tobion** [comment]
Closing as I haven't had the need for this yet. If someone else needs the feature, feel free to create a PR.
