### ISSUE TITLE
[Routing] security conditions on routes

### ISSUE THREAD

**Issue by henrikbjorn** [symfony/symfony#7425]
As we all use GitHub we have seen that they use two different roots. One for the unlogged users and one for those who is logged in. Facebook does the same thing.

Currently this is "not really" possible without if statements etc in the controller it self. So myabe something like http://robots.thoughtbot.com/post/22605580334/constrain-yourself should be added.

**Comment by Tobion** [comment]
There are expressions now available in matching routes. But this won't help the given use case since as @acasademont said, the security is not available at this point.

**Comment by fabpot** [comment]
Closing as it's not possible
