### ISSUE TITLE
[Validator] Import constraints from another class

### ISSUE THREAD

**Issue by guilhermeblanco** [symfony/symfony#7502]
Most of the times, you define your validation rules inside of your Entities.
Some Forms require only a subset of data that your Entity contains, forcing you to create FormModels and copying Validator rules from one place to the code.
As everybody knows, copying means trouble and duplication, which means that if an update happens only at one location, you have an inconsistency in your code. In this situation, it'll be a missing validation rule.
To mitigate this problem, Symfony Validator component should have an ability to "import" validation rules from another location (class/property). Example:

``` php
class UserUpdateFormModel
{
    /**
     * We only allow user name updates.
     *
     * @Assert\Import(from="@ICUserProfileBundle:User", property="name")
     */
    protected $name; 
}
```

It seems to be possible already, since ClassMetadata in the validator component already has a mergeConstraints() function. What do you guys think?

**Comment by Simperfit** [comment]
@javiereguiluz I would like to implement this, do we wait for some approval before creating the PR ?

**Comment by javiereguiluz** [comment]
@Simperfit honestly, I would always wait for approval before sending a pull request ... unless the change is very simple and you don't mind if your PR is ultimately rejected.

**Comment by fabpot** [comment]
I don't think we will ever implement this in core. Let's close.
