### ISSUE TITLE
Add support get/has-like or/and callback method to PropertyAccess component

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#7530]
We are using Propel1 with Taggable behavior. It adds to model next methods: `getTag($name)/setTag($name, $value)/hasTag($name)/removeTag($name)`.

As temporary sollution we are "wrapped" this methods with magic `__get/__set/__isset/__unset` but now we need add other 1:n related entities: `getAttribute($name)/setAttribute($name, $value)/...`.

It would be nice add something like:

``` php
$builder
  ->add('attr_one', null, array('property_path_write' => function($object, $name, $value) {
    $object->setTag($name, $value);
}))
```

**Comment by chalasr** [comment]
Closing in favor of #5013 then.
