### ISSUE TITLE
Flexible Fatal Error Pages

### ISSUE THREAD

**Issue by jeremylivingston** [symfony/symfony#7572]
I think that the addition of a nice display of fatal errors is a huge improvement in Symfony 2.2.

However, I think that this should be taken one step further. I feel that fatal errors should be displayed to end-users in a way that is similar to 404s and 500s. These situations allow custom pages to be created so the users can have the most ideal experience.

Currently, if a user hits a fatal error in a production environment, they're given a blank white screen or their browser's error screen. Obviously, fatal errors should never happen in production, but there should at least be a way to handle them when they do.

Are there any plans to implement this in the future?
Thank you!

**Comment by mercefan** [comment]
Quoting @GromNaN code, could it be possible to delete the `echo '503 Service Unavailable';` line?
In case of an error produced with a XML Response, this specific line, breaks the `error.xml.twig` XML format, so the final should be like:

```php
 $error = error_get_last();
        if (1 === $error['type'] && false === headers_sent()) {
            // send a 503
            header('HTTP/1.0 503 Service Unavailable');
            header('Retry-After: 10');
        }
```

**Comment by nicolas-grekas** [comment]
Closing as this should be solved now that the Debub ErrorHandler is registered by default.
