### ISSUE TITLE
[Form] Set translation_domain on choices

### ISSUE THREAD

**Issue by patie** [symfony/symfony#7611]
I thinking about option for set translation domain on each element

maybe something like that with translation_id@domain or translation_id:domain

```
       $builder->add('language', 'choice', array(
            'label'                            => 'language_of_report@user',
            'choices'                          => array(
                \Acme\BackBundle\Entity\User::LANGUAGE_EN  => 'english@main',
                \Acme\BackBundle\Entity\User::LANGUAGE_DE  => 'german@main',
            )
        ));
```

i know its will not often used, but imho not BC breakes and sometimes its necessary..

What do you think ?

**Comment by Tobion** [comment]
Fixed with new `choice_translation_domain` option.
