### ISSUE TITLE
Kernel charset, twig charset and templates encoding

### ISSUE THREAD

**Issue by bamarni** [symfony/symfony#7617]
see #7532

If I change my app charset by overriding Kernel::getCharset() method, for a basic HTML page using twig as templating engine, the response Content-Type will automatically get updated, for example "text/html; charset=ISO-8859-15".

But this is problematic for templates I don't have control over, for example templates provided by the framework or third-party bundles, because they may use a different encoding, if it's the case, apparently the response content, (or maybe only some part of the response content? (when overriding third party bundles)) wouldn't be using the charset specified in the header.

**Comment by WouterJ** [comment]
This has been fixed now by #13715
