### ISSUE TITLE
[4.0] [Form] Remove duplicated HTML attributes

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7709]
(Copied from #6522)

With the current implementation, the attributes passed in the `attr` option are rendered both in the `<form>` tag (new) and in the `<div>`/`<table>` tag of the form (for BC).

``` php
$form = $this->createForm('my_form', $formData, array(
    'attr' => array(
        'id' => 'foo',
        'class' => 'bar',
    ),
));
```

Template:

``` html
{{ form(form) }}

->

<form id="foo" class="bar">
    <div id="foo" class="bar">
        <!-- rows -->
    </div>
</form>
```

Solutions that come to mind:

(a) Move the rendering of the attributes from the `<div>`/`<table>` tag to the `<form>` tag **for the root form**. This breaks BC because the `form_widget()` call for the root form does not output the attributes anymore then. Nested forms are not affected.

``` html
<form id="foo" class="bar">
    <div><!-- no attrs! -->
        <!-- rows -->
    </div>
</form>
```

(b) Don't render a `<div>` tag **for the root form** and do as in (a) for the table layout. This obviously also breaks BC. Nested forms are not affected.

``` html
<form id="foo" class="bar">
    <!-- rows -->
</form>
```

(c) Don't render any attributes in the `<form>` tag. Maintains full BC.

``` html
<form>
    <div id="foo" class="bar">
        <!-- rows -->
    </div>
</form>
```

Opinions?

While (c) is the best solution from a BC point of view, I think it is rather unintuitive. As a newcomer, if I put a "class" attribute on a form, I would expect it to be on the outermost `<form>` tag, not on some `<div>` within.

(a) and (b), on the other hand, break BC for those people that use `form_widget()` to render the complete form. I don't know how many people would be affected by this, [this poll](http://twtpoll.com/p3y7vb) tries to gather some data about that. IMO both (a) and (b) are more intuitive and future-proof.

My favorite is (b) because it removes a useless `<div>` from the default markup.

**Comment by MatTheCat** [comment]
Is there a chance to see this fixed one day?

**Comment by artursvonda** [comment]
Was the solution proposed in https://github.com/symfony/symfony/pull/18138 basically correct? I could take that solution and create a new PR targeted at master (Symfony v5).

**Comment by curry684** [comment]
I don't think there ever was consensus on what was correct. The amount of things that could go wrong in projects all over the world are huge, and likely only a handful of them could be found by unit tests as it's a superficial template change - albeit with potentially huge consequences. I'm not really sure that balances the need to fix it to be honest.

Perhaps we should consider an alternative approach with a flag that enables 'correct' rendering for those projects where it matters, or we should specifically fix `id` attributes as it's the only one that has to be unique in a document thus causing potential JS/CSS issues.

I fear we're kinda stuck in 10 years legacy on this one without a clear route to a "clean" fix.

**Comment by webmozart** [comment]
@curry684 I agree.
