### ISSUE TITLE
[3.0] [Form] Inconsistency between isValid() and the "valid" template variable

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7737]
I'm calling out for you to decide how to resolve the inconsistency between the `Form::isValid()` method and the `valid` variable available in the template:

* `isValid()` returns `false` if a form was not submitted. This way it is possible to write concise controller code:

```php
$form = $this->createForm(...);
$form->handleRequest($request);

if ($form->isValid()) {
    // only executed if the form is submitted AND valid
}
```

* `valid` contains `true` if a form was not submitted. This way it is possible to rely on this variable for error styling of a form.

```twig
<div{% if not form.vars.valid %} class="error"{% endif %}>
```

We have two alternatives for resolving this problem:

1. Leave the inconsistency as is.
2. Make `isValid()` return `true` if a form was not submitted (consistent with `valid`)
3. Revert to the 2.2 behavior of throwing an exception if `isValid()` is called on a non-submitted form (not consistent with `valid`).

Both 2. and 3. will require additional code in the controller:

```php
$form = $this->createForm(...);
$form->handleRequest($request);

if ($form->isSubmitted() && $form->isValid()) {
    // only executed if the form is submitted AND valid
}
```

What do you think?

**Comment by JHGitty** [comment]
What do you think now? Because it is referenced to 3.0 a BC break would be allowed.

**Comment by dosten** [comment]
I prefer the option 2, seems to be the more intuitive.

**Comment by xabbuh** [comment]
> I would go for n°3 as an unsubmitted form is neither valid or invalid. Despite the additional code.

I feel the same. Though we then again would have another inconsistency: If the form was not submitted before, you would not be able to call `isValid()`, but you would still be able to use `valid` in the template.

**Comment by Ener-Getick** [comment]
please see #17644
