### ISSUE TITLE
[RFC][Config] Split Config component? 

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#7796]
If I am not overlooking something, the Config component consists of three things that have little to nothing to do with each other:
* Configuration definition/validation (in Config/Definition)
* Configuration loading (in Config/Loader) 
* Caching things in a file on disk with a revalidation mechanism (ConfigCache et. al.)

I came across a PR discussion lately (will try to find it again) in which (Drupal?) folks complained about depending on the Config component IIRC. Not sure whether the dependency itself was a problem or a dependency on too much/wrong stuff, though.

It was just an observation I wanted to log somewhere. If it was a deliberate decision, feel free to close it. Needless to say that'd be a BC break.

**Comment by mpdude** [comment]
Something we should discuss again for 3.0, or already too late?

**Comment by mpdude** [comment]
@stof do you still consider this split worthwhile?

**Comment by fabpot** [comment]
I think it's not worthwhile

**Comment by mpdude** [comment]
Ok, you guys decide – feel free to close it.
