### ISSUE TITLE
[3.0] [Form] - Rename data-prototype attribute to data-collection-protoype

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#7833]
`data-prototype` does not accurately reflect the contents of the attribute. I propose the following attributes on collections for Symfony 3.0.
- `data-form-type='collection'` - label this form widget as a collection
- `data-collection-prototype` - Stores the collection prototype string
- `data-collection-prototype-name` - The prototype name. Used for label replacement.
- `data-collection-allow-add` - The collection allows prototypes to be added
- `data-collection-allow-delete` - The collection allows prototypes to be deleted

See: #5145 & #7713

**Comment by fabpot** [comment]
Closing this old issue as it didn't get any traction.
