### ISSUE TITLE
[Form] Improve guessing mechanism

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#7868]
Currently, the guessing mechanism is not very efficient, because it needs to do type and metadata introspection which naturally is slow. It is also limited, because options cannot be guessed when the type is fixed in the builder.

For example, assume that a property "firstName" does not have a `NotNull` constraint. When you do

```
$builder->add('firstName', 'text');
```

the field will still be required, because guessing is only activated when the type parameter is omitted. To improve this status quo
1. guessing should be made more efficient by generating optimized guessers for model classes
2. option guessing should be activated even when the "type" parameter is given

(1) is a requirement for (2), because activating guessing for every field consequently needs a very efficient guessing mechanism.
##### Implementation Suggestion

To realize the above, I suggest to add two interfaces, `FormGuesserInterface` and `FormGuesserStrategyInterface` (which replaces the current `FormTypeGuesserInterface`). Both are very similar, but while `FormGuesserStrategyInterface` returns `Guess` instances with confidence values about the correctness of the guessed value, `FormGuesserInterface` returns plain PHP values.

Each form extension can optionally provide a guesser strategy, for example `ValidatorGuesserStrategy` and `DoctrineGuesserStrategy`. The form core will use a `StrategyBasedGuesser` that is initialized with a list of these strategies and then resolves the guesses to plain PHP values.

Additionally, the form core should implement a `GeneratorBasedGuesser` that generates optimized PHP classes for each model class and then uses these classes for guessing. For an example see below.
###### FormGuesserInterface

``` php
interface FormGuesserInterface
{
    /**
     * @param string $class The class name to guess for.
     * @param string $property The property name to guess for.
     * @return string The form type to use.
     */
    public function guessType($class, $property);

    /**
     * @param string $type The used form type.
     * @param string $class The class name to guess for.
     * @param string $property The property name to guess for.
     * @return array The options to use.
     */
    public function guessOptions($type, $class, $property);
}
```
###### FormGuesserStrategyInterface

``` php
interface FormGuesserStrategyInterface
{
    /**
     * @param string $class The class name to guess for.
     * @param string $property The property name to guess for.
     * @return TypeGuess The form type to use together with a confidence level.
     */
    public function guessType($class, $property);

    /**
     * @param string $type The used form type.
     * @param string $class The class name to guess for.
     * @param string $property The property name to guess for.
     * @return OptionGuess[] The options to use together with confidence levels
     * and applicable form types.
     */
    public function guessOptions($type, $class, $property);
}
```
###### TypeGuess

``` php
use Symfony\Component\Form\Guess\Guess;

class TypeGuess extends Guess
{
     /**
      * @return string The guessed type.
      */
     public function getType();
}
```
###### OptionGuess

``` php
use Symfony\Component\Form\Guess\Guess;

class OptionGuess extends Guess
{
     /**
      * @return string The option name.
      */
     public function getOption();

     /**
      * @return string The guessed option value.
      */
     public function getValue();

     /**
      * @return string[] The applicable form types.
      */
     public function getApplicableTypes();
}
```
###### Generated Guesser Example

``` php
// Generated guesser for the "Person" model class
class PersonGuesser implements ClassSpecificFormGuesserInterface
{
    public function guessType($property)
    {
        switch ($property) {
            case 'gender':
                return 'choice';
            default:
                return 'text';
        }
    }

    public function guessOptions($type, $property)
    {
        switch ($property) {
            case 'gender':
                return array(
                    'required' => true,
                    'choices' => array('male', 'female'),
                );
            case 'firstName':
                return array(
                    'required' => false,
                );
            default:
                return array();
        }
    }
}
```

**Comment by onetest** [comment]
+1

**Comment by webmozart** [comment]
ref #7868

**Comment by alterphp** [comment]
As described in #15314, a better guesser mechanism would take account of active validation_groups in order to render the correct options. Here is a following example :

```php
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="string", length=255)
     * @Assert\Length(max=140, groups={"front.chat"})
     * @Assert\Length(max=255, groups={"admin.creation", "admin.edition"})
     */
    protected $content;
```

The maxlength attr option should take account of which validation_group is enabled.

**Comment by aromer** [comment]
+1 
I'm perfectly fine with explicitly stating the type of my field, but I need the required and min/max values to accurately reflect the validation.

**Comment by aromer** [comment]
This issue is about 3 years old now. What would it take to get some movement on it? I should be able to offer some development time to assist with it. We're going to be building out some client side validation soon and I'd rather spend dev cycles contributing back then hacking around the issue.

**Comment by WouterJ** [comment]
I think what's missing here is someone to work on it. I like the idea and it seems like other people (including some core team members) like it as well. You can create a PR with "WIP" in its title (Work In Progress), so we can start discussing the feature very quickly. Seeing an (even unfinished) implementation always works better in order to get feedback on it.

**Comment by ABM-Dan** [comment]
I have never contributed to a project of Symfony's scale, but I am considering working on this specific issue, if that helps.

**Comment by weaverryan** [comment]
@ABM-Dan That would be wonderful :). And if you have any issues or do something "wrong", it won't be a big deal - we can help. But if someone can champion this issue and create a WIP PR, that could finally get this moving!

**Comment by felipyamorim** [comment]
+1
This is really usefull, can't wait for that.

**Comment by Upgreydd** [comment]
+1

**Comment by higidi** [comment]
+1

**Comment by Mathieudewet** [comment]
Hi guys, what do you think about having a form builder using propertyInfo and classMetadata, with a matching table (overridable by optionsResolver )
$propertyInfos = $propertyInfo->getTypes('FooClass', 'foo');
switch (true) {
  case ($propertyInfos[0]['builtinType'] === 'object' && $propertyInfos[0]['class'] = 'DateTime') : 
            $formType = DateTimeType::class;
            break;
            ...

Enabling all properties by default, allowing to disabled each one passing disabled: true in optionsResolver, in the same way passing the label splitting the camel cased options to have it.
e.g. myProperty => My property.

Moreover can we include it in the makerBundle in order to let it create each needed entities form ?
If this makes sense to you guys i'll be glad to open a PR, and likefully be supervised.

**Comment by xabbuh** [comment]
I am closing this old issue as it seems that noone cared enough to implement it.
