### ISSUE TITLE
[Form] ResizeListener forces a specific data format requirement on the model

### ISSUE THREAD

**Issue by searbe** [symfony/symfony#7905]
This is a follow-up to my comments in issue #7828.

All subscribers listening for a PRE_SET_DATA event will receive _model_ data. This can be problematic since certain field types start to dictate a very specific format for data in the model. even with a data transformer in place.

For example, in my usecase I have model data which could work with the CollectionType, which registers a ResizeListener internally. My data needs transforming before hitting the ResizeListener, as it expects a certain format of data. Since the ResizeListener receives _model_ data on PRE_SET_DATA, there is no mechanism to prepare the data for the listener. The end result is I have to modify the model data itself to get it through the ResizeListener.

Ultimately, a PRE_SET_DATA listener can introduce a specific data format requirement on the model, which can't be solved by simply adding a data transformer.

My thoughts are that if listeners (or at least the ResizeListener specifically) received normalised data, which a transformer can take care of, it wouldn't be possible to impose specific format requirements on the model.

**Comment by fabpot** [comment]
Closing as this issue is stalled.

**Comment by ugomeda** [comment]
Bumping this issue. I have a model with a field `$translations` containing a list of translations and the following DataTransformer to transform my `["translationId" => "Translation Value"]` array into `[["id" => "translationId", "value" => "TranslationValue']]` :

```php
<?php

namespace MyNamespaceForm;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class TranslationTransformer implements DataTransformerInterface
{
    public function transform($translations)
    {
        if ($translations === null) {
            return [];
        }

        $formData = [];
        foreach ($translations as $id => $value) {
          $formData[] = ["id" => $id, "value" => $value];
        }

        return $formData;
    }

    public function reverseTransform($formData)
    {
        $data = [];
        foreach ($formData as $line) {
          if (isset($data[$line['id']])) {
            $failure = new TransformationFailedException("Duplicated key");
            $failure->setInvalidMessage("workspace.translation.duplicate_key");

            throw $failure;
          }
          $data[$line['id']] = $line['value'];
        }

        if (count($data) === 0) {
          return null;
        }

        return $data;
    }
}
```

I was able to hack my way around the problem, but when I tried to add the key `messages.news_label`, this happened :

```
Symfony\Component\Form\Exception\InvalidArgumentException:
The name "messages.news_label" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").

  at vendor/symfony/symfony/src/Symfony/Component/Form/FormConfigBuilder.php:782
  at Symfony\Component\Form\FormConfigBuilder::validateName('messages.news_label')
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormConfigBuilder.php:118)
  at Symfony\Component\Form\FormConfigBuilder->__construct('messages.news_label', null, object(EventDispatcher), 
```
