### ISSUE TITLE
Undefined Index: ancestor_id

### ISSUE THREAD

**Issue by vsrmob** [symfony/symfony#8108]
Database: DB2
Symfony version 2.2:

It is failing in class aclProvider.php with undefined index ancestor_id. Dynamic SQL statement has "ANCESTOR_ID" , whereas in aclProvider.php, it is defined as "ancestor_id".

Srinivasa Varrey

**Comment by fabpot** [comment]
Closing as ACLs have been removed from Symfony Core.
