### ISSUE TITLE
[2.3][Form] HiddenEntityType

### ISSUE THREAD

**Issue by kl3ryk** [symfony/symfony#8293]
Hi,

I have created HiddenEntityType (https://gist.github.com/kl3ryk/5781916), to transform value of hidden field into Entity. I was using FormBuilderInterface::getParent() to get Entity class. But in Symfony 2.3 function FormBuilderInterface::getParent was removed. So is there any way to retreive parent form data_class name (https://gist.github.com/kl3ryk/5781916#file-hiddenentitytype-php-L36)?

**Comment by webdevilopers** [comment]
Any news on this?

**Comment by xabbuh** [comment]
Can you give a use case for which you would need such a form type?

**Comment by Koc** [comment]
@xabbuh for ajax loaded data like autosuggests - when choice list is too big

**Comment by xabbuh** [comment]
Not sure that we need a complete new form type for this. Having an additional option (maybe provided by a form type extension) looks sufficient to me.

**Comment by Koc** [comment]
yes, @xabbuh see #15053

**Comment by Tobion** [comment]
Closing as duplicate of #6602
