### ISSUE TITLE
Consolidate repository names

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8295]
Now that Github [supports repository renaming with redirection](https://github.com/blog/1508-repository-redirects-are-here) I suggest to consolidate the repository names (a) with each other and (b) with their Composer package names (naming convention wise, i.e. lower case plus hyphens).

Status quo:

* github.com/symfony/symfony (Composer: symfony/symfony)
* github.com/symfony/symfony-standard (Composer: symfony/framework-standard-edition)
* github.com/symfony/HttpFoundation (Composer: symfony/http-foundation)
* github.com/symfony/DomCrawler (Composer: symfony/dom-crawler)
* etc.

Better:

* github.com/symfony/symfony (Composer: symfony/symfony)
* github.com/symfony/symfony-standard (Composer: symfony/framework-standard-edition)
* **github.com/symfony/http-foundation** (Composer: symfony/http-foundation)
* **github.com/symfony/dom-crawler** (Composer: symfony/dom-crawler)

It's a small change, but it's worth it IMO (considering that there are no drawbacks).

**Comment by stof** [comment]
The API is now redirected, so we might reconsider this issue.

**Comment by WouterJ** [comment]
This naming standard is already used for the newer packages, so big +1 to make everything consistent (if it doesn't cause problems, but these should be solved by the redirection).

**Comment by fabpot** [comment]
Indeed, now that Github is doing the right thing, let's do that. I will try to make it happen this week.

**Comment by fabpot** [comment]
Done
