### ISSUE TITLE
[3.0] [Form] Add/remove collection rows in PATCH requests without sending the existing rows

### ISSUE THREAD

**Issue by glumb** [symfony/symfony#8301]
I'm trying to update a form collection item with a PATCH request and or `$form->submit($request,false);`. Either way, all items are removed from the collection except the new one.

``` php
        echo "Items from the database ------------------------------------";
        \Doctrine\Common\Util\Debug::dump($entity->getItems(), 1);

        $form->submit($request,false);

        echo "Items in the form ------------------------------------";
        \Doctrine\Common\Util\Debug::dump($form->get('items')->getData());

        echo "updated items ready to save to database";
        \Doctrine\Common\Util\Debug::dump($entity->getItems(), 1);
```

I submit the form with modifications for item[0] `entity[items][0][description]` `test 1234`.
The output dump is shown below.

``` php
Items from the database ------------------------------------
array(2) {
  [0]=>
  string(29) "CoBo\RecipeBundle\Entity\Item"
  [1]=>
  string(29) "CoBo\RecipeBundle\Entity\Item"
}

Items in the form ------------------------------------
array(1) {
  [0]=>
  object(stdClass)#776 (8) {
    ["__CLASS__"]=>
    string(29) "CoBo\RecipeBundle\Entity\Item"
    ["id"]=>
    int(248)
    ["description"]=>
    string(9) "test 1234"
  }
}

updated items ready to save to database
array(1) {
  [0]=>
  string(29) "CoBo\RecipeBundle\Entity\Item"
}
```

As said, item[1] got removed. I'm not quite sure, if this is the expected behaviour, since a PATCH request should not remove items?!

**Comment by andosteinmetz** [comment]
Has there been any development on this front? I am also trying to make modifications to a resource, and to send a user-submitted log entry along with the changes.

The log entries are in a collection owned by the resource in a one-to-many relationship. I'd like to be able to add a new entry without needing to send all previous log entries in the request. With the current behavior, the new log-entry is overwriting the first log entry owned by the resource.

Does Symfony support the original PATCH spec or only MERGE PATCH?

**Comment by HeahDude** [comment]
Hi @andosteinmetz I was not comfortable with having https://github.com/symfony/symfony/pull/17771 as a bug fix, we eventually find another fix for it, but this can easily bring this feature.

**Comment by HeahDude** [comment]
In the meanwhile I suggest you call submit directly or use your own `RequestHandler`, it's very easy. It just call `Form::submit()` given the request verb and data.

**Comment by andosteinmetz** [comment]
Thanks @HeahDude for the quick response! If you have time, could you expand a little further? I'm quite new to Symfony/Doctrine. 

Is the main difference that I have to set `clear_missing` to `true`, or do I need to handle the request in a more customized way?

**Comment by HeahDude** [comment]
When you do [`$form->handleRequest($request)`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L113) in a controller, it checks two things:

- the method, if it matches the form config then go and submit

- if the data is get from request go and submit

[`Form::submit`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L496) takes two arguments, the data and the second `$clearMissing` is used to know if you should ignore missing fields or enforce setting the model data to `null` by overwriting.

This is just decided by the handler by comparing the verb with PATCH, as this one should NOT overwrite data.

If you need more control, you can either:

-  call `$form->submit($request->request->get('form_name'), false)` to enforce the behavior

- implements [`RequestHandlerInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/RequestHandlerInterface.php) and use `$builder->setRequestHandler($this->requestHandler)` in your type by injecting it as a service. Be careful though, this only has sense on a root form, fields submit their children in cascade and get mapped back to the root.

- use a `PRE_SUBMIT` event to access the submitted data array get from the request with `$event->getData()` AND the pre set data with `$event->getForm()->getData()` to hold your logic in there, normalising data, adding/removing fields, etc...

My PR would give more control by allowing the configuration to change internally the submit process whatever the level is.

Hope that helps :)

**Comment by HeahDude** [comment]
Oh I forgot you can also use there is a fourth work around that allows to be closer to the model hydration: implements the [`DataMapperInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/DataMapperInterface.php), see https://github.com/symfony/symfony-docs/pull/6900 for an attempt to explain this missing part of the doc.

**Comment by xabbuh** [comment]
I am closing this old issue as it seems that noone cared enough to implement it.
