### ISSUE TITLE
Exiting the user switching does not reload the old user

### ISSUE THREAD

**Issue by stof** [symfony/symfony#8321]
when exiting the user switching, the listener set the original token in the security context without reloading the user from the user provider. This leads to some nasty bugs if your application relies on the user being managed by Doctrine for instance.

I generally don't serialize the whole object graph of the user (there is no need to store relations in the session as the user will be reloaded anyway). but this means that the page displayed when exiting the user switching will break because relations would not be available.

**Comment by adamelso** [comment]
Is this the same issue addressed by https://github.com/symfony/symfony/pull/15137/files#diff-c19daa95ade0ae9e5e6d811196255274R166 ?

**Comment by chalasr** [comment]
@stof is this still relevant?

**Comment by jakzal** [comment]
I just tested this on 2.3, which is the latest branch the fix referenced by @adamelso exists. I can confirm that **both** users are refreshed when exiting the impersonated user.
