### ISSUE TITLE
abstract class AuthenticationManagerInterface states return never null, example + UserAuthenticationProvider returns null

### ISSUE THREAD

**Issue by denshade** [symfony/symfony#8401]
I'm creating my own implementation for AuthenticationManagerInterface. 
This interface explicitly states:

```php
/**
     * Attempts to authenticates a TokenInterface object.
     *
     * @param TokenInterface $token The TokenInterface instance to authenticate
     *
     * @return TokenInterface An authenticated TokenInterface instance, never null
     *
     * @throws AuthenticationException if the authentication fails
     */
public function authenticate(TokenInterface $token);
```
So return must NEVER be null. 

I use UserAuthenticationProvider as an example and this reads as follows:

```php
/**
     * {@inheritdoc}
     */
    public function authenticate(TokenInterface $token)
    {
        if (!$this->supports($token)) {
            return null;
        }
```

This conflicts with what the interface prescribes. What am I to do? Follow the interface or the example?

**Comment by javiereguiluz** [comment]
Closing it as fixed because of what @jakzal said: `UserAuthenticationProvider` returns `null` in some cases ... but `AuthenticationProviderManager` takes care of that.
