### ISSUE TITLE
CssSelector should be configured properly when used for HTML or XML

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#8404]
... but that's not really possible when using it from BrowserKit as the Crawler is created directly.

From #8286:

    In functional test, since the crawler is instanciated by the de browser kit (which 
    know the content-type), Can we imagine the browser kit call for us
    disableHtmlExtension or enableHtmlExtension

**Comment by stof** [comment]
This will be fixed in Symfony 2.8 thanks to #15934
