### ISSUE TITLE
Encapsulate AppKernel creation somewhere

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#8500]
I want add 3rd required parameter to constructor of my AppKernel. But this constructor calls somewhere where I don't know:

1. `web/app.php`, `web/app_dev.php`, `app/console`
2. in unserialization of Kernel
3. in cache:clear command
4. maybe also somewhere.

The problem is that constructor not defined as final and no any interface that dissallow me to change its signature. But in fact - this is hardcoded.

So I propose add something like app kernel initialiser (service) which would calls in described above places.

**Comment by TomasVotruba** [comment]
I'm also for *won't fix*, since it's been a long time with no progress.
