### ISSUE TITLE
Support for chaining authentication providers that shares the same security context

### ISSUE THREAD

**Issue by pschirch** [symfony/symfony#8606]
Hi,

in my current project I implemented a proprietary single sign-on service authentication provider that logs in users automatically. If the automatism fails, I want to provide a fallback through another authentication provider ( _http_basic_, _form_login_).

I read about chaining user providers but nothing about chaining authentication providers that shares the same security context. Is it possible to do this?

I would be grateful for any advice.

**Comment by javiereguiluz** [comment]
Closing as fixed by #14673. It's not fixed "automatically" (you must implement the actual code yourself) but #14673 provides the means to do so more easily than before.
