### ISSUE TITLE
Authentication with the same context through two different authentication types

### ISSUE THREAD

**Issue by christian-kolb** [symfony/symfony#8614]
I want to authenticate two firewals through the same context, but that does not seem to work when one uses different authentication types like one with http_basic and one with form login.

As excample see this post on stackoverflow:
http://stackoverflow.com/questions/11801622/how-to-authenticate-on-2-different-symfony2-firewalls-at-the-same-time

Cheers
Christian

**Comment by sunra** [comment]
+1 for making this possible/easier out of the box

**Comment by tayhimself** [comment]
+1 for making this possible/easier out of the box
I want a user that is authenticated to have access to another firewall without having to create new routes.

I am using multiple guard authenticators, and tried to log in the user automatically like this. 

      $token = new UsernamePasswordToken($user, $user->getPassword(), "main", $user->getRoles());
      $this->get("security.token_storage")->setToken($token);
      $event = new InteractiveLoginEvent($request, $token);
      $this->get("event_dispatcher")->dispatch("security.interactive_login", $event);

I can't use the same entry point for both authenticators as suggested [in the docs].(http://symfony.com/doc/3.4/security/multiple_guard_authenticators.html
)

**Comment by curry684** [comment]
@weaverryan I think you should take a look at the comment above as I think the docs are right here.
