### ISSUE TITLE
MutableAclProvider SecurityIdentity restrict

### ISSUE THREAD

**Issue by awers** [symfony/symfony#8699]
Hi! Have a problem with using security identities different from UserSecurityIdentity and RoleSecurityIdentity. Can you please change examination of *SecurityIdentity classes to appropriate interfaces, because I even unable to extends from those classes, because they are "final".

Thanks

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
