### ISSUE TITLE
[Form] Add support for form* attributes to submit buttons

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8732]
See http://www.w3schools.com/tags/tag_button.asp

**Comment by WouterJ** [comment]
This is quite tricky to implement, as these methods override things of the root form. E.g. imagine something like this:
```php
$formFactory->createFormBuilder()
    ->setMethod('POST')
    // ...
    ->add('submit', 'submit', array(
        'form_attr' => array('method' => 'GET'),
    ))
    ->getForm();
```

Now, the `SubmitType` needs to adjust the root form type or the root form type needs to be aware of some setting of a child `SubmitType`. Can you share your idea on how to implement this?

**Comment by vudaltsov** [comment]
I probably misunderstand smth, but these attributes should not be handled by backend, they are for frontend usage only. So if smbd needs to submit current form to a different action by pressing button B, she can do
```php
->add('submitB', SubmitType::class, [
    'attr' => [
        'formaction' => $this->router->generate('route')
    ]
])
```
or similar thing in twig.

ping @HeahDude

**Comment by xabbuh** [comment]
I agree with @vudaltsov. I don't think we need to do anything here.
