### ISSUE TITLE
[Form] Implement "label_html" option

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8733]
A "label_html" option should be implemented as an alternative to "label", which may contain markup that will not be escaped.

**Comment by fabpot** [comment]
Closing this old issue. Apparently, nobody asked for it anyway.

**Comment by lukepass** [comment]
Sorry for reopening this old thread but a `label_html` option could be really useful for terms of service labels. Thanks.

**Comment by ThomasLandauer** [comment]
A boolean `label_html` option was merged at https://github.com/symfony/symfony/pull/31375
