### ISSUE TITLE
[Form] Support event listeners in buttons

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8735]
The event POST_SUBMIT (and potentially PRE_SUBMIT, PRE_SET_DATA and POST_SET_DATA) should be supported on buttons. Using this event, dynamic functionality can be built into forms that depends on whether a button was clicked or not:

``` php
$builder->get('refresh')->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
    $refresh = $event->getForm();
    $form = $refresh->getParent();

    if ($refresh->isClicked()) {
        // do something with $form
    }
});
```

May be related to #5807.

**Comment by wiejakp** [comment]
Long forgotten post I see. I do agree this should be added. Otherwise there's no way to remove buttons dynamically, ex: removing certain buttons based on user role.

**Comment by fabpot** [comment]
@wiejakp Would you try to work on implementing this feature?

**Comment by wiejakp** [comment]
@fabpot, might attempt this if time allows.

**Comment by Romaxx** [comment]
@wiejakp Current hack is to place SubmitType **BEFORE** an hidden element (or an element used in your form), addListener to the element and get parent getClickedButton() method.


```
$builder->add('mybutton',SubmitType::class);
$builder->add('ghostelement',HiddentType::class);


$builder->get('ghostelement')->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
    $form = $event->getForm();

    if ($form->getParent()->getClickedButton() == $form->get('mybutton')) {
        // mybutton clicked
    }
});
```

**Comment by wiejakp** [comment]
@Romaxx , I'm not sure that's the case we're talking about. Buttons not being included in Form Event listeners means that buttons themselves aren't able to be removed from form model. Please note that this example clearly demonstrates behaviour that button is excluded from:

`<?php
/**
 * (c) International Code Council
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

/**
 * Automatically remove form elements based on users' role.
 */
class RoleFormTypeExtension extends AbstractTypeExtension
{
    /**
     * @var Security
     */
    private $security;

    /**
     * @param Security $security
     */
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $detach = false;
        $role   = $options['role'];

        // Check $role.
        if ($role && false === $this->security->isGranted($role)) {
            $detach = true;
        }

        // Check $hide.
        if (true === $options['hide']) {
            $detach = true;
        }

        // detach form or element when at least one rule agree
        if ($detach) {
            $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
                $form = $event->getForm();

                if (!$form->isRoot()) {
                    $parent = $form->getParent();
                    $parent->remove($form->getName());
                }
            });
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'role' => null,
            'hide' => false,
        ]);
        $resolver->setAllowedTypes('role', ['string', 'null']);
        $resolver->setAllowedTypes('hide', 'boolean');
    }

    /**
     * @return string[]
     */
    public static function getExtendedTypes(): array
    {
        return [
            FormType::class,
        ];
    }
}`

**Comment by Romaxx** [comment]
to @wiejakp, @webmozart dont talk about button removal, but listener actions 'dynamic functionality can be built into forms that depends on whether a button was clicked or not', so my response is in that way.

**Comment by wiejakp** [comment]
> to @wiejakp, @webmozart dont talk about button removal, but listening button 'dynamic functionality can be built into forms that depends on whether a button was clicked or not', so my response is in that way.

Ok, gotcha. I edited my post because it clicked in after few minutes.

**Comment by wiejakp** [comment]
@fabpot , I'm wondering if you might have a  word of advice on problem from this puzzle. I'm having an issue with button type's parent removing button form type from it's children collection, and I hope you have an idea why, or when should I call my event. Seems like buttons `createView()` and `setData()` are out of the question (button dont't support data, and view changes seem to be too late(?)).

PR in question: https://github.com/wiejakp/form/pull/2

Extension for testing:

```<?php

declare(strict_types=1);

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

/**
 * Class RoleFormTypeExtension
 *
 * @package App\Form\Extension
 */
class RoleFormTypeExtension extends AbstractTypeExtension
{
    /**
     * @var Security
     */
    private $security;

    /**
     * @param Security $security
     */
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if ($options['hide'] ?? null) {
            // Using FormEvents::PRE_SET_DATA to remove common fields from paren's form view.
            $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
                $form = $event->getForm();

                if (!$form->isRoot()) {
                    $form->getParent()->remove($form->getName());
                }
            });

            /**
             * TODO: issues:
             * - pre/post build view doesn't seem to be working
             * - pre/post finish view doesn't seem to be working
             */
            $builder->addEventListener(FormEvents::PRE_FINISH_VIEW, function (FormEvent $event) {
                $form = $event->getForm();

                if (!$form->isRoot()) {
                    $form->getParent()->remove($form->getName());
                }
            });
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['hide' => false]);
        $resolver->setAllowedTypes('hide', 'boolean');
    }

    /**
     * @return string[]
     */
    public static function getExtendedTypes(): array
    {
        return [FormType::class];
    }
}
```

Form type for testing:

```<?php

declare(strict_types=1);

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class DefaultType
 *
 * @package App\Form\Type
 */
class DefaultType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // works just fine
             ->add('text', TextType::class, [
                'label' => 'TextType',
                'hide'  => true,
            ])
            // parent can't remove
            ->add('button', ButtonType::class, [
                'label' => 'ButtonType',
                'hide'  => true,
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }
}
```

**Comment by xabbuh** [comment]
I fail to see a real use case for this feature. So I am going to close here. We can reconsider this decision in the future if more information pops up that indicates otherwise.
