### ISSUE TITLE
[Form] Let disabled text fields (and potentially others) use __toString() if set to an object

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8761]
A convenient way to "display" data is to add a disabled text field to a form:

``` php
$builder->add('category', 'text', array('disabled' => true));
```

Currently, this fails due to the following error:

> The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies__CG__\DeepSpaceOne\GameBundle\Entity\ShipClass. You can avoid this error by setting the "data_class" option to "Proxies__CG__\DeepSpaceOne\GameBundle\Entity\ShipClass" or by adding a view transformer that transforms an instance of class Proxies__CG__\DeepSpaceOne\GameBundle\Entity\ShipClass to scalar, array or an instance of \ArrayAccess.

**Comment by xabbuh** [comment]
I am closing here as this didn't receive any traction. Additionally, I do think that automatically transforming some object into a string should be considered as too much magic.
