### ISSUE TITLE
[DOM Crawler] Parses characters incorrectly

### ISSUE THREAD

**Issue by michaelcullum** [symfony/symfony#8770]
It parses `&bull;` in html as `ÔÇó`:

The following is from the output of a test that should pass:
```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'phpBB ÔÇó Free and Open Source Forum Software'
+'phpBB &bull; Free and Open Source Forum Software'
```

**Comment by jakzal** [comment]
Closing as there's no feedback. My [earlier tests](https://travis-ci.org/jakzal/symfony/builds/23999828) prove everything's fine on PHP > 5.3.3. Trying to fix this for older PHP versions is not worth the effort needed. Especially, that Symfony 2.7 will support PHP >= 5.3.9. I have submitted a PR to the docs to warn users of old PHP versions.
