### ISSUE TITLE
[Form] Button::isSubmitted() should return false if not clicked

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#8817]
The method `Button::isSubmitted()` should be equivalent `Button::isClicked()`. That is, if a button was clicked, the method `isSubmitted()` should return `true` and `false` otherwise.

**Comment by WouterJ** [comment]
Is this considered a BC break, if so, how can we work around it?

**Comment by sstok** [comment]
This can be solved with an option `thread_clicked_as_submitted` (or something more friendly).

Status: reviewed

**Comment by xabbuh** [comment]
I am closing here. We cannot make this change without breaking BC and adding a config options to enable the new behaviour isn't better than using `isClicked()` instead of `isSubmitted()`.
