### ISSUE TITLE
[Finder] UnexpectedValueException "Connection refused" with FTP use

### ISSUE THREAD

**Issue by pilotftzi** [symfony/symfony#8868]
Hello,

I use Finder with

$finder->in('ftp://user:password@example.com/pub/');

Access to the directory "/pub/" is allowed. I can see it from my browser.
The rest of this directory on ftp-server is not allowed to access.
But the one in which I'm trying to go - available, I checked out of the browser. And the root directory is also available.

But Finder return UnexpectedValueException at the root dir and a "pub" directory:

RecursiveDirectoryIterator::__construct(): connect() failed: Connection refused

Exception trace:
 () at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php:49
 RecursiveDirectoryIterator->__construct() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php:49
 Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Finder/Adapter/PhpAdapter.php:35
 Symfony\Component\Finder\Adapter\PhpAdapter->searchInDirectory() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php:785
 Symfony\Component\Finder\Finder->searchInDirectory() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php:692
 Symfony\Component\Finder\Finder->getIterator() at /home/andreybolonin/www/tourobzor_xmlparser/src/Andreybolonin/PackTourBundle/Parser/TpgParser.php:74
 Andreybolonin\PackTourBundle\Parser\TpgParser->getAndSaveSpoList() at /home/andreybolonin/www/tourobzor_xmlparser/src/Andreybolonin/PackTourBundle/SpoManager.php:36
 Andreybolonin\PackTourBundle\SpoManager->getOperatorList() at /home/andreybolonin/www/tourobzor_xmlparser/src/Andreybolonin/PackTourBundle/Command/SpoUpdateCommand.php:21
 Andreybolonin\PackTourBundle\Command\SpoUpdateCommand->execute() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:244
 Symfony\Component\Console\Command\Command->run() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/andreybolonin/www/tourobzor_xmlparser/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /home/andreybolonin/www/tourobzor_xmlparser/app/console:27

P.S. Several other ftp servers accessible by login and password work fine with Finder. But this does not work.

Tell me what to do please.

**Comment by WouterJ** [comment]
As this seem like a user support question and it hasn't recieved any activity since its creation (1+ year ago), I would propose to close this issue.

**Comment by giorgiopagnoni** [comment]
I'm having the same issue. I can read and write files on my FTP server with no problem with Filezilla and Cyberduck, but somehow it just doesn't work with Symfony finder. I have tried downgrading the finder to no avail.

This is my script file:
```
require __DIR__ . '/vendor/autoload.php';

$finder = new \Symfony\Component\Finder\Finder();

$server = 'ftp://username:pwd@myserver/';
$finder->in($server);
$finder->ignoreUnreadableDirs(true);

// ok

foreach ($finder as $file) {
   // it fails at this very moment
    continue;
}
```

```
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(ftp://...@...): failed to open dir: operation failed in /Users/giorgiopagnoni/PhpstormProjects/untitled/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:52
Stack trace:
#0 /Users/giorgiopagnoni/PhpstormProjects/untitled/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(52): RecursiveDirectoryIterator->__construct('ftp://...:...', 4096)
#1 /Users/giorgiopagnoni/PhpstormProjects/untitled/vendor/symfony/finder/Finder.php(809): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('ftp://...:...', 4096, true)
#2 /Users/giorgiopagnoni/PhpstormProjects/untitled/vendor/symfony/finder/Finder.php(682): Symfony\Component\Finder\Finder->searchInDirectory('ftp://...:...')
#3 /Users/giorgiopagnoni/PhpstormProjects/untitled/script.php(15): Symfony\Component\Finder\Finder->getIterator()
#4 {main}
  thrown in /Users/giorgiopagnoni/PhpstormProjects/untitled/vendor/symfony/finder/Iterator/Recurs
```iveDirectoryIterator.php on line 52
