### ISSUE TITLE
[Finder] Duplicated results when used two times

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#8871]
Hello, 

When i run the code below, on the second search, the results are duplicated.

``` php
$finder = new Finder();
$first_results = $finder->in('/my/path')->files()->name('/my_pattern/');

 // [...] some code

$second_results = $finder->in('/my/path')->files()->name('/another_pattern/');
```

But if i run that code, it works as intended :

``` php
$finder = new Finder();
$first_results = $finder->in('/my/path')->files()->name('/my_pattern/');

 // [...] some code

$finder = new Finder();
$second_results = $finder->in('/my/path')->files()->name('/another_pattern/');
```

**Comment by inouire** [comment]
Sorry for the old post, but what about providing some kind of a "reset" method on the finder instance, that would reset only the memorized path(s)  ? This would allow to keep the same research criteria, but for a search in another directory.

**Comment by J7mbo** [comment]
Sorry for the old post, but providing a "reset" method would be useful here.

**Comment by FyiurAmron** [comment]
is adding

`public function resetDirs() { $this->dirs = []; }`

to `Finder.php` too much to ask?

**Comment by xabbuh** [comment]
A `reset()` method looks like something that could be added without pain.

@symfony/deciders What do you think?

**Comment by fabpot** [comment]
Having a `reset()` method sounds like a possibility. Not a big fan of this solution, but I suppose that's the only "reasonable" thing to do.

**Comment by javiereguiluz** [comment]
What about the comment from @J7mbo above?

> Finder::create() returns a new instance, this will do :)

So we don't need to add a `reset()` method, right?

**Comment by fabpot** [comment]
hmm, @javiereguiluz is right. Why would I do `$finder->reset()` instead of `Finder::create()`?

**Comment by xabbuh** [comment]
@javiereguiluz The issue with `create()` is that it creates a completely new instance (i.e. dropping all the configuration you did before). As far as I understood comments users seem to want to reuse an instance and only do some "finetuning" before getting the next results.

**Comment by lyrixx** [comment]
It's not the same. `create` return a really new finder. You may want to add some initial filter, get all matching files, reset it, then get others file.

**Comment by javiereguiluz** [comment]
I see ... but then you are adding a `reset()` method that doesn't truly resets ... it resets some things (`in()`) while not resetting others (all the search criteria). It's confusing to me.

**Comment by xabbuh** [comment]
`reset()` may not be the best name (maybe `clearResults()` or something like that). But adding a method like that looks like the only option to solve the reported use case to me.

**Comment by fabpot** [comment]
There is another option, `clone`-ing the finder instance before calling `in()`.

I agree the `reset()` is confusing.

**Comment by lyrixx** [comment]
I usually use clone indeed ;)
I don't know why but many people don't think to clone PHP Object.

**Comment by FyiurAmron** [comment]
that's exactly why I proposed to name the method explicitly `resetDirs`, so that it would, well, only reset `$dirs`.

Alternatively, maybe just make `$dirs` protected instead of private, and allow the user to extend the class and add the method if he needs it? Or add a `protected function setDirs($dirs) { $this->dirs = $dirs; } ` ? Changing current Finder behaviour is impossible neither with extension nor with configuration.

**Comment by cdarken** [comment]
If only there was a way to extend the class and write my own reset(), but I'm afraid I can't, as all properties are private.

**Comment by Destroy666x** [comment]
+1 for the `resetDirs` suggestion

**Comment by cdarken** [comment]
@Destroy666x while you're at it, please make relevant properties `protected` as now they're all `private`.

**Comment by fabpot** [comment]
Re-closing as there are already many ways, with cloning being the probably better way.
