### ISSUE TITLE
allowing conditional async (hinclude) loading

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#8889]
In response websites most developers simply load the same content regardless of the device and then rearrange the content depending on the device. This is of course not ideal for mobile users which are short on bandwidth and then end up with websites that expect them to scroll endlessly.

So it would be great if there would be some way to add some conditions on the async load (maybe via some callback) that for example only does the async load on click or when one has scrolled down far enough.

I am not sure if this is even possible with the hinclude.js lib as it exists today, so maybe some work also would need to be done on that lib.

**Comment by fabpot** [comment]
Closing as nobody really worked on that anyway. And it does not seem something for core anyway.
