### ISSUE TITLE
XLIFF Standard Placeholders

### ISSUE THREAD

**Issue by Lumbendil** [symfony/symfony#8919]
It'd be nice if symfony2 coud support XLIFF standard placeholders.

Here they are explained: http://www.ibm.com/developerworks/xml/library/x-localis2/

Example:

`<source>My text with a <g id="323">placeholder</g></source>`

**Comment by javiereguiluz** [comment]
I'm closing this issue because it hasn't registered any activity in almost 3 years. @Lumbendil I'm sorry that your proposal didn't get enough attention from the community.
