### ISSUE TITLE
Bug: YAML parser includes Tags as part of the parsed value

### ISSUE THREAD

**Issue by pwolanin** [symfony/symfony#9040]
http://www.yaml.org/spec/1.2/spec.html#id2802346

The "Failsafe schema" says:

"The failsafe schema is guaranteed to work with any YAML document. It is therefore the recommended schema for generic YAML tools. "

10.1.2. Tag Resolution

All nodes with the “!” non-specific tag are resolved, by the standard convention, to “tag:yaml.org,2002:seq”, “tag:yaml.org,2002:map”, or “tag:yaml.org,2002:str”, according to their kind.

So, it would seem the parser should at a minimum handle tags in this failsafe way.  As best I can tell that would essentially mean stripping them out.

At the moment, if you put even the YAML !!str tag at the beginning of a string it's included in the value, which is certainly not in any conformity to the spec.

**Comment by fabpot** [comment]
Not supported by our parser and it will probably never be supported.
