### ISSUE TITLE
Allow using multiple template candidates when rendering twig template (like include)

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#9071]
```php
// there is no possibility do smth like this
$templates = array(
    sprintf('MissProjectBundle:StaticPage:custom/%s', $page['template']),
    'MissProjectBundle:StaticPage:static_page_layout.html.twig'
);

return $this->render($templates);

// and we should use workaround
return new Response($this->get('twig')->resolveTemplate($templates)->render(array()));
```

**Comment by fabpot** [comment]
I'm closing this one as the Templating layer on top of Twig is going to be deprecated in 3.0; the recommended way is going to be to use plain Twig, where you can do that easily as this is built-in.

**Comment by stof** [comment]
@fabpot no more templating engine abstraction in 3.0 ?

**Comment by fabpot** [comment]
@stof In 2.7, I want to be able to use plain Twig without having another layer of abstraction; that's already almost possible now.

**Comment by stof** [comment]
@fabpot I know that. But your previous comment lets think that you want to remove the other way in 3.0 entirely

**Comment by fabpot** [comment]
I want to move the Templating component (and all its derivative classes that come with FrameworkBundle) outside of Symfony "core".
