### ISSUE TITLE
[Doctrine] Ignore binary data in array of params

### ISSUE THREAD

**Issue by vpetrovych** [symfony/symfony#9096]
This is linked to https://github.com/symfony/symfony/issues/7012
The issue seems to still exist when you're using $qb->expr()->in() to add array of binary data.

I tried to fix the issue the following way:
https://github.com/vladykx/symfony/commit/842a8c49c5fe2e17b9a72179bf7d67b0405cf31b

**Comment by weaverryan** [comment]
Fixed at #15128 thanks to you doing all the work @vpetrovych :).
