### ISSUE TITLE
Problem with yaml parser and line breaks in folded style blocks

### ISSUE THREAD

**Issue by micha149** [symfony/symfony#9105]
I noticed a problem with the yaml parser component in version 2.3.3. The folded style block seem to not correctly parse line breaks which includes indents oder blank lines. 

Here is a small example:

    small:
        test: >
            <h2>A heading</h2>

            <ul>
                <li>a list</li>
                <li>may be a good example</li>
            </ul>

I would expect a resulting string like:

    <h2>A heading</h2><ul><li>a list</li><li>may be a good example</li></ul>

Currently I receive something like that:

    <h2>A heading</h2>

    <ul>    <li>a list</li>    <li>may be a good example</li></ul>

The parse should not replace the line break and all following white spaces with a space. Lines with no content should be omitted too.

**Comment by xabbuh** [comment]
see #16864
