### ISSUE TITLE
[Form] Deleting many to many relationship fails after binding form

### ISSUE THREAD

**Issue by Stefun** [symfony/symfony#9142]
I'll explain issue by giving example what I have faced.

I have entities in which employee has many skills.So there is many-to-many relationship between employee and skill entities. Now lets say I have employee form which has skill collection.skill is added dynamically in twig through ajax.

If I delete one skill from lets say 3 after binding form it shows 2.but it won't persist in database. While all other changes in object reflects in database why not this one?

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback and because the (unconfirmed) issue probably refers to an unmaintained Symfony version. If the problem persist in newer Symfony versions, please reopen the issue. Thanks!
