### ISSUE TITLE
[Form] Add generic way for overriding nested options

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#9177]
We currently use various different ways for influencing the options of the children of an added type:

a) By letting _one_ option accept _multiple values_ for the children (e.g. the "empty_value" option in DateType)

``` php
$form->add('updatedAt', 'date', array(
    'empty_value' => array(
        'day' => 'The day...',
    ),
));
```

b) By having dedicated "options" options (e.g. "options" in CollectionType, "first_options"/"second_options" in RepeatedType)

``` php
$form->add('password', 'repeated', array(
    'type' => 'password',
    'first_options' => array(
        'required' => true,
    ),
));
```

And in #3825, a third possibility was suggested:

c) By having _one_ dedicated option per child and option (e.g. "day_widget", "month_widget" etc.)

``` php
$form->add('updatedAt', 'date', array(
    'day_widget' => 'text',
    'month_widget' => 'choice',
));
```

These different alternatives
- are inconsistent
- need to be implemented manually
- need to be changed whenever a new child option should be supported

Therefore I propose adding a generic way for overriding nested options by supporting a special syntax in the options array:

`@child(/nestedChild)*[#option]`

Examples:

``` php
$builder->add('updatedAt', 'datetime', array(
    '@date' => array(
        'required' => true,
        '@day' => array(
            'empty_value' => 'The day...',
        ),
    ),
));

// equivalent to

$builder->add('updatedAt', 'datetime', array(
    '@date' => array(
        'required' => true,
    ),
    '@date/day' => array(
        'empty_value' => 'The day...',
    ),
));

// equivalent to

$builder->add('updatedAt', 'datetime', array(
    '@date#required' => true,
    '@date/day#empty_value' => 'The day...',
));
```

Additionally, setting an option for all children at once should be supported:

``` php
$builder->add('updatedAt', 'datetime', array(
    '@date/*#empty_value' => '...',
));
```

References:
- #3825 
- #6350
- #6910 
- #8396
- #8443
- #10012

**Comment by gnat42** [comment]
This would be a fantastic feature to land in 2.7 if possible. Its a real annoyance to work around.

**Comment by backbone87** [comment]
i think the inherit options should get their own option entry:
```php
    $resolver->setDefaults(array(
        'inherit_options' => array(
            '@day/required' => true,
        ),
    ));
```
this solves multiple problems:
- less to none refactoring of the options component
- less conflicts with legacy code (only 1 new common option entry)
- provides an explict ordering of the inheritance "instructions", which solves overwrite problems (`'@*/required' => false, '@day/required' => true,`), since the options component does not maintain a comprehensive option entry order

**Comment by backbone87** [comment]
what i also noticed: this feature does not resolve #12314 in any means, since the prototype is its "own" form, that is not connected to the original, except for sharing some configuration

**Comment by backbone87** [comment]
some more thoughts:
i think the following syntax, is most likely to avoid BC issues:
`^  ( (@[^/]+|\*)(/@[^/]+|/\*)*(/\*\*)? | \*\* )?  #  (.+)  $`

```php
$resolver->setDefaults(array(
  'inherit_options' => array(
    '#required' => false,
    '#inherit_options' => array(
      '@child/**#required' => false
    ),
    '@day#required' => true,
  ),
));
```

**Comment by xabbuh** [comment]
I am not convinced that we need this. For example, in many core types where we need to provide options that are ultimately passed through to a nested type we first perform some validation as not all options are useful in all contexts, but also depend on some other option set for the parent type. Thus, this feature wouldn't save as much here, but is something that still needs to be maintained.

@symfony/deciders What do you think?

**Comment by yceruto** [comment]
Could it be already cover by the feature "Nested Options Definition" introduced since Symfony 4.2?
* https://github.com/symfony/symfony/pull/27291
* https://symfony.com/doc/current/components/options_resolver.html#nested-options

This would at least solve the issue of override some nested options.

**Comment by linaori** [comment]
I'm not in favor of this. The problem I see here is that if I have a form type that explicitly doesn't provide an option for an inner type, it can be bypassed and change the behavior of the form.

I'm of opinion that if you want to have the option to configure an inner field, the wrapper form should provide this configuration option. Yes it's slightly repetitive, yet makes it possible to restrict configuration where needed.

Any configuration for nested types should be configured through the wrapper.

**Comment by xabbuh** [comment]
let's close here then
