### ISSUE TITLE
[Form] PercentType does not work as expected

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony#9179]
In one of my forms, I use the percent type to convert input into an integer.

In saw some issue with the following abstract type

``` php
$builder->add('battery', 'percent', array('type' => 'integer'));
```

When input is array('battery' => 15.0001), form validation return an error on battery field, but everything is fine for the 15.0000 value.

switching to the following clears the error:

``` php
$builder->add('battery', 'integer', array());
```

I wanted to add Unit tests for the percent Type but these are skipped because of the ICU version I have.

**Comment by xabbuh** [comment]
@bburnichon I tried to reproduce your issue, but both `15.00000` as well as `15.00001` result in the integer `15` for me.

**Comment by bburnichon** [comment]
Oh, that's an old issue! I do not work on the impacted project anymore. I think issue could be closed then if it cannot be reproduced.
