### ISSUE TITLE
Infinite redirect for authenticated users when RememberMe key is changed

### ISSUE THREAD

**Issue by kostiklv** [symfony/symfony#9203]
If a user is authenticated with `RememberMeToken` and has an active session, when secret key used in `RememberMeAuthenticationProvider` is changed, an infinite redirect loop occurs. (It's a very rare case, but I just faced this when migrating a site to a different server, which was configured with a different `secret`)

When secret keys don't match, `RememberMeAuthenticationProvider` [throws](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php#L39) `BadCredentialsException`, however firewall's `ExceptionListener` does not remove the token from the session on this exception. [It does](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L189), though, on `AccountStatusException`.

Not sure if it's the correct fix, but I'd change the exception thrown in `RememberMeAuthenticationProvider` to `CredentialsExpiredException`.

**Comment by WouterJ** [comment]
I know this is quite an old issue and nicely said, it hasn't received much attention...

I'm trying to reproduce the described bug, as there doesn't seem to be many big changes related to this feature between 2013 and now. However, I can never get to a state where the `RememberMeAuthenticationProvider` discovers that the keys are not equal...

What I'm doing/the result:

* Created a secured area with a firewall that uses the remember me functionality
* Login as user
* Changed key of the remember me functionality
* Removed login session
* Refresh page -> Logged out as [`TokenBasedRememberMeServices#processAutoLogin()`](https://github.com/symfony/Security/blob/master/Http/RememberMe/TokenBasedRememberMeServices.php#L57) doesn't have 2 the same hashes (as the key is included in the hash). This removes the RememberMeToken.

When using the DoctrineTokenProvider and `PersistentTokenBasedRememberMeServices`, the key is never used and there are no problems.

**Comment by xabbuh** [comment]
@kostiklv Can you provide a fork of the Symfony Standard Edition that reproduces your issue?

**Comment by xabbuh** [comment]
@kostiklv I'm closing here as we cannot reproduce your issue. Feel free to reopen if you can provide more information.
