### ISSUE TITLE
Mispelled method name requested in 2.3.5

### ISSUE THREAD

**Issue by linuxatico** [symfony/symfony#9205]
Hi, 
I have a property "integrazioni" in entity "Contratto" with associated methods addIntegrazioni, removeIntegrazioni, getIntegrazioni. 
When I try to submit my form I get this error:

 **Neither the property "integrazioni" nor one of the methods "addIntegrazionus()", "setIntegrazioni()", "__set()" or "__call()" exist and have public access in class "ABC\MyBundle\Entity\Contratto".
500 Internal Server Error - NoSuchPropertyException **

It should look for the right "addIntegrazioni" which is already present, not this one. 

Linuxatico

**Comment by Tobion** [comment]
Closing as this is already covered in #5013
