### ISSUE TITLE
[Feature] App Engine Support

### ISSUE THREAD

**Issue by zachrbrown** [symfony/symfony#9238]
Since it is not possible to write to the filesystem in Google App Engine, Symfony is unusable, as it has to write out its class maps / cache (and doctrine with its proxy classes) to a directory on the filesystem. 

It's also possible that I missed something in the documentation  that would allow me to circumvent this issue, but as of now, there doesn't seem to be a way to do this.

**Comment by itavero** [comment]
What is the current state of this feature request? Is Google App Engine supported, and if not, what needs to be done to make it Symfony 2 compatible with GAE?

**Comment by eddiejaoude** [comment]
> Unfortunately, the cache contains absolute paths.

This has now been fixed (well a couple of months ago).

**Comment by GromNaN** [comment]
GAE now supports the tempnam() and sys_get_temp_dir() functions : https://cloud.google.com/appengine/docs/php/#tempnam_and_sys_get_temp_dir_support

**Comment by jakzal** [comment]
Is there anything missing for GAE support?

**Comment by shouze** [comment]
@jakzal yes it lacks at least some documentation (can be more general thant just GAE as Heroku or deployments on containers with ready only code can be in the scope too). I think it can work BTW even if a little tricky at the moment.

For example we can't warmup the entire sf2 cache prior to deploy an app (or I have no idea how to do that). It would be cool to ensure that sf2 cache has no writes during the entire life of a deployed application.

**Comment by xabbuh** [comment]
> yes it lacks at least some documentation (can be more general thant just GAE as Heroku or deployments on containers with ready only code can be in the scope too). I think it can work BTW even if a little tricky at the moment.

@shouze Could be worth adding an article to the [Deployment section of the Symfony cookbook](http://symfony.com/doc/current/cookbook/deployment/index.html). Do you mind opening an issue over there or maybe even better start a pull request?

**Comment by bangpound** [comment]
I did some work with GAE and Symfony and collected my advice and code here: https://github.com/caxy/AppEngineBridge

**Comment by nicolas-grekas** [comment]
Can someone try to setup a Symfony app on Google App Engine (and write a bit of doc about it)?
It should be doable now.
ping @zachrbrown @shouze /others

**Comment by shouze** [comment]
@nicolas-grekas ok so the whole sf2 cache can be warmup from now in 1 pass? If you tell me how to accomplish that... I'm very interested!

**Comment by bangpound** [comment]
I have published two packages https://github.com/caxy/AppEngineBundle and https://github.com/caxy/AppEngineBridge and am updating the documentation on the bundle (which has some helpful features for integrating with GAE users) before this weekend. Also note that Google has published a fork of the standard edition 2.3 https://cloud.google.com/appengine/docs/php/symfony-hello-world?hl=en

**Comment by fabpot** [comment]
Symfony should work fine on Google AppEngine now. It there are some problems, specific issues should be created instead of using this old and generic one.
