### ISSUE TITLE
[Security] updateAcl() will not update class ace if it was already loaded for some other acl

### ISSUE THREAD

**Issue by drscre** [symfony/symfony#9239]
Let's imagine i have two objects of the SAME class, _p1_ and _p2_ with identities _o1_ and _o2_ . Both objects have  ACL's.

I want to add new class ace through _$acl1_ and then modify it through _$acl2_

```php
$acl1 = $aclProvider->findAcl($o1);
$acl2 = $aclProvider->findAcl($o2);

$acl1->insertClassAce($sid, 4);
$aclProvider->updateAcl($acl1);
// Both acls see the class ace - OK
var_dump($acl1->getClassAces()[0]->getMask()); // prints 4.
var_dump($acl2->getClassAces()[0]->getMask()); // prints 4.

$acl2->updateClassAce(0, 42);
// Both acls see the updated class ace - OK
var_dump($acl2->getClassAces()[0]->getMask()); // prints 42.
var_dump($acl1->getClassAces()[0]->getMask()); // prints 42.

$aclProvider->updateAcl($acl2); // [!!] Changes will not be saved to database
```

And to my surprise changes are not saved to DB.

It looks like security component assumes that _class ace_ belongs to the first ACL which loaded it. This is counterintuive, since class ACE should not belong to any particluar OBJECT acl, since it is a CLASS acl.  And in the code you may not remember which acl used this ace for the first time.

**Comment by dhanielo** [comment]
I solved this with:
* Before change
` $aclProvider->propertyChanged($ace, 'mask', $ace->getMask(), $maskBuilder->get())`
Example:

```
$builder = new MaskBuilder();
$buider
    ->add('VIEW')
    ->add('EDIT')
    ->add('DELETE');

foreach ($aces as $ace) {
    if (!($ace instanceof Entry) || !$ace->getSecurityIdentity()->equals($securityIdentify))
        continue;
    $aclProvider()->propertyChanged($ace, 'mask', $ace->getMask(), $maskBuilder->get());
    $ace->setMask($maskBuilder->get());
    $aceExists = true;
    break;
}

$aclProvider->updateAcl($acl);
```
I also agree that the design is not good. That might be interesting (I not yet tested):

https://github.com/wemakecustom/symfony-acl-bundle

Ping @drscre @guilro @wemakecustom @lemoinem @lavoiesl

**Comment by lavoiesl** [comment]
Hey @dhanielo, thanks for your interest in our bundle. Unfortunately, it is not really maintained or tested. As of now, I would advise against using it in production. Moreover, the Symfony team has stated multiple times in the pass that it does not want to tie a core component to Doctrine ORM.

I also consider ACLs to be kinda deprecated. If you want to do security in Symfony, I would strongly suggest that you look into [Security Voters](http://symfony.com/doc/current/cookbook/security/voters_data_permission.html). I have a blog article cooking up for advanced voters if you are interested.

**Comment by dhanielo** [comment]
@lavoiesl thanks for information, I was unaware of these considerations. I will work thinking in same.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
