### ISSUE TITLE
[Form] allow default value set by the `data` option to be overwritten

### ISSUE THREAD

**Issue by craue** [symfony/symfony#9240]
See craue/CraueFormFlowBundle#89.

**Comment by HeahDude** [comment]
I'm not sure I understood it well but `data` option always has precedence on given data only due to this block https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormFactory.php#L75,
so it is an expected behaviour and changing it would be a BC break, right ?

**Comment by xabbuh** [comment]
as @HeahDude said this is the expected behaviour
