### ISSUE TITLE
[Session] strict session / session fixation

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#9258]
Is there anything we need or can do about https://wiki.php.net/rfc/strict_sessions ?
It is applied in PHP 5.5.3.

> There is user land solution that validates session data, but this method is not widely adopted.

**Comment by MacDada** [comment]
[The PHP docs say](https://secure.php.net/manual/en/session.configuration.php#ini.session.use-strict-mode):

> Enabling session.use_strict_mode is mandatory for general session security. All sites are advised to enable this.

So I'd like to turn it on. I guess, I should do it on `php.ini` level, not in Symfony?

Symfony would ignore my setting, as [it's not in `$validOptions`](https://github.com/symfony/symfony/blob/v3.2.6/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L308).

**Comment by sstok** [comment]
@MacDada please see #22352 👍
