### ISSUE TITLE
[PropertyAccess] Allow different prefixes than "add" and "remove"

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#9336]
Currently, adders and removers must be prefixed with "add" and "remove". When applying DDD, this sometimes doesn't make sense, for example:

``` php
class Contact
{
    public function addGroup(ContactGroup $group) { }
    public function removeGroup(ContactGroup $group) { }
}
```

Here it would make much more sense to prefix the methods with "join" and "leave":

``` php
class Contact
{
    public function joinGroup(ContactGroup $group) { }
    public function leaveGroup(ContactGroup $group) { }
}
```

The PropertyAccessor should provide a way to use these methods.

**Comment by TomasVotruba** [comment]
@webmozart  Is this still relevant?

I've been using this component so this might be easy.



What's the final decision? I would be for custom callbacks. Because there might be loads off different prefixes like has/join/leave/remove/attach/add/get/set etc... (just from the top of my head).

Any relevant sources?

**Comment by TomasVotruba** [comment]
Ping @webmozart

**Comment by webmozart** [comment]
@TomasVotruba Indeed this is not such an easy pick. [This post in #9336](https://github.com/symfony/symfony/issues/5013#issuecomment-22811845) and the following posts explain how this could be solved in a nice manner.

The difficulty is that, if we use annotations to configure property paths, we also have to provide XML and YAML mappings, as we do in other places. That's quite a bit of work and duplicating what we already have in other components. A solution for this problem (at least for XML) would be [native support for XML-based annotations in Doctrine](https://webmozart.io/blog/2014/10/24/defining-php-annotations-in-xml/), and as far as I know (ping @Ocramius) this is WIP.

The benefit is that the PropertyAccess-based serializer would become more powerful, as would the Form component.

**Comment by lrlopez** [comment]
@webmozart I've been studying how metadata gets loaded by other Symfony components (i.e. Validator, Routing, etc.) and you're right: there is a lot of overlapping. I'm about to try replicating the loader code from the Validator component while taking out any unneeded feature as a first approach. 

Later we can figure out how to extract all metadata loaders their own independent component. The library you pointed out, `jms/metadata` could be used as a base (it seems to be rather stable) so we'd just have to implement the annotation, YAML and XML drivers. Then we could refactor all the current code that need metadata info to use the new component.

**Comment by lrlopez** [comment]
Ouch! I've just noticed that the Symfony Serializer component includes some mapping magic. I'll have a look into it.

**Comment by fabpot** [comment]
Just a quick note: `jms/metadata` cannot be used due to licensing issues.

The loader from the Validator component is the one that we need to get rid of. All the other components are already using a standardized way.

**Comment by Ocramius** [comment]
> and as far as I know (ping @Ocramius) this is WIP.

It's not something for ORM 2.x anyway. We are crunching on it, but far from getting anywhere soon, sorry.

**Comment by sstok** [comment]
https://github.com/rollerworks/metadata/ MIT licensed, documentation is missing currently.
You can see a working implementation in https://github.com/rollerworks/search-metadata

Feel free to reuse my work and move it Symfony :+1:

**Comment by lrlopez** [comment]
Thanks @fabpot for the hint. I had already changed my mind and used the Serializer mapping as the implementation reference because I found its code much cleaner. Anyway, it hurt a lot copying so many LOCs, it just doesn't seem right.

@sstok, I'll have a look into it, I really appreciate your offer.

**Comment by lyrixx** [comment]
@Korbeil https://github.com/symfony/symfony/pull/30704 has been merged. Does it help this issue?

**Comment by Korbeil** [comment]
> @Korbeil #30704 has been merged. Does it help this issue?

Yes, now you can instantiate PropertyAccessor with custom `$writeInfoExtractor` and you can give him: `new ReflectionExtractor(null, null, ['join', 'leave']);` to use theses prefixes.

In `services.yaml`, you'll have to do:
```yaml
CustomWriteInfoExtractor:
  class: Symfony\Component\PropertyAccess\PropertyAccessor
  arguments:
    $arrayMutatorPrefixes: ['join', 'leave']

Symfony\Component\PropertyAccess\PropertyAccessorInterface: 
  arguments:
    $writeInfoExtractor: '@CustomWriteInfoExtractor'
```
