### ISSUE TITLE
dynamic "code" loading

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#9341]
This ticket will likely spawn other tickets. The idea is that this ticket will group them and serve as an entry point to people joining the discussion.

The goal is to make it possible for Symfony2 component using applications to dynamically add code to the application enabling people to for example download modules/Bundles from the web and enabling them. This will usually mean regenerating the DIC and routing caches.

/cc @crell @drak @Tobion @lolautruche @dmitriysoroka

**Comment by javiereguiluz** [comment]
Closing it in favor of #6082, which is older and it's asking the same feature.
