### ISSUE TITLE
[Form] Simplify form theming

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#9371]
I guess most of form theming relies on adding classes to widget attributes (or label, or container). What about creating wrapper around attributes with some helpers like `addClass`, `removeClass`?
for example 
```
{% label_attr.addClass('required') %}
// or
{% addClass(label_attr, 'required') %}
```
instead of
```
{% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
```

or 
```
{% set label_attr.for = id %}
```
insead of
```
{% set label_attr = label_attr|merge({'for': id}) %}
```

**Comment by fabpot** [comment]
Closing this old ticket as nobody ever step up with a solution that does not impact performance.
