### ISSUE TITLE
[DependencyInjection] add a flag to have invalid service definitions be removed on dump

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#9401]
Often when a Bundles deals with optionally supported integration into other Bundles it becomes necessary to write compiler passes to either dynamically load those optional services or remove those optional services if they were already loaded in the extension and it turns out their dependencies do not exist.

See for example https://github.com/nelmio/NelmioApiDocBundle/pull/265

Now it would be interesting if there would be a way to flag a service so that if on dump the service would trigger an invalid definition exception, it is simply removed.

So for example if the service ``bar`` is not defined, then the service ``foo`` would be removed as well:
```
<service id="foo" class="Acme\DemoBundle\SomeClass" on-invalid="remove">
    <argument type="service" id="bar" />
</service>
```

I guess this could get a bit tricky if removing one service makes another invalid etc. So it could potentially make the dumping process take longer. But it would remove the need for a lot of compiler passes.

**Comment by fabpot** [comment]
Re-reading this issue, I think this is a bad idea. I wished to have this exact feature more than once, but removing services when something is wrong can lead to WFT effects. As we can do the same via a custom pass, I'd vote :-1: for adding this feature.

**Comment by stof** [comment]
I'm also :-1: for this. It goes against DX because it means that any mistake in the service definition would make it disappear silently
