### ISSUE TITLE
[Form] Support \DateTimeImmutable

### ISSUE THREAD

**Issue by stof** [symfony/symfony#9508]
These form types should support a way to use the DateTimeImmutable class of PHP 5.5 (only on PHP 5.5+ obviously) for applications using it.

This involves accepting them as input and returning an immutable datetime as model data after the transformation.

The easiest implementation is probably to add a new value for the [`input` option](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L219) and add a transformer converting the immutable date into a mutable one (so that the norm data stays a DateTime class).

If a new major version of Symfony bumps the requirement to PHP 5.5+, the normalized data could then be switched to the DateTimeImmutable class to simplify the logic (which is currently cloning the DateTime to avoid modifying the original one.

**Comment by webdevilopers** [comment]
:+1: Came from similar discussion: https://github.com/symfony/symfony/pull/15362#issuecomment-126878746

**Comment by xabbuh** [comment]
Fixed by #18548?

**Comment by stof** [comment]
@xabbuh not fully. The form will now accept a DateTimeImmutable on the model side for the existing data, but it will always use `DateTime` when setting the data back. We need to provide a new value for the `input` option for full support (to allow having the Form converting it back to an immutable one)

**Comment by vudaltsov** [comment]
@stof, @xabbuh, I'll do a PR on this by the end of this week

**Comment by vudaltsov** [comment]
see #25273

**Comment by stof** [comment]
#25273 does not do it: it changes the norm data itself, instead of adding support for choosing between DateTime and DateTimeImmutable for the model data. So the link in the previous comment is misleading.

**Comment by vudaltsov** [comment]
Yes, I am sorry for the previous comment. I should have explained that it's only the half way to adding support for `DateTimeImmutable`.
