### ISSUE TITLE
[Console] Consider adding an event that allow us intercept events

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#9538]
When we were discussing about how introduce console events, [I talked about  the possibility of intercepting all events in order to include a new parameter](https://github.com/symfony/symfony/pull/6124#issuecomment-13038358). Now, using the `console.command` is possible to add such parameter but we can't retrieve its value.

I think it can be achieved introducing a `pre` and `post` bound event, where in the first we have the opportunity to append a new option and in the second retrieve its value and perform some action. 

Seems like other users [have the same use case](http://php-and-symfony.matthiasnoback.nl/2013/11/symfony2-add-a-global-option-to-console-commands-and-generate-pid-file/) and for now the only workaround is very ugly and not recommended.

**Comment by TomasVotruba** [comment]
@marcospassos Is this issue still relevant? How do you approach it now?

**Comment by WouterJ** [comment]
This is now possible in 2.8/3.0, as https://github.com/symfony/symfony/pull/15938 is merged. See the test included in that PR on how to achieve this.

**Comment by TomasVotruba** [comment]
Great! This issue can be closed then, right?

**Comment by marcospassos** [comment]
Yes, @TomasVotruba. Thanks!

**Comment by TomasVotruba** [comment]
@marcospassos Thank you
