### ISSUE TITLE
cookie_domain with multiple domains and wildcards

### ISSUE THREAD

**Issue by wholehogsoftware** [symfony/symfony#9744]
We have a 'white label' system in place where our system responds to multiple domains. For example:

customer-1.com
customer-2.com

We use a kernel event listener to catch the current domain and show specific assets and content which allows each client to customize the platform.

Then, we have an affiliate program that allows partners to refer users using a vanity URL. For example:

partner-1.customer-1.com
partner-2.customer-2.com

The issue we have run into is that, in order to use wildcards in our cookie domain, we must set cookie_domain in config.yml which means we are limited to using a single domain.

Is there a different way to handle this?

A workaround would be to redirect the user twice but I would like to avoid that. The first redirect would take them from partner-1.customer-1.com to the main customer-1.com and then the cookie would be set without specifically setting cookie_domain. Once that is done, the user could be redirected to the requested route/URI. The result is that the default behavior of using the current domain as the cookie_domain would then take over.

**Comment by nicolas-grekas** [comment]
Closing as this should be solvable with environment variables now. Please report back if not.

**Comment by aistis-** [comment]
Hi @wholehogsoftware 

How did you solve case? I have a similar one. As I don't want to expose a session to other white-label by any means, I am probably going to write a custom session handler. I am using MySQL for storing the session, so will add an extra column which will contain a session domain or WL identifier 🤔

**Comment by mathroc** [comment]
I'm interested to. @nicolas-grekas I don't see how environment variables are helping here, do you mean we should have different environment variables per vhost ?

**Comment by boosen** [comment]
> Hi @wholehogsoftware
> 
> How did you solve case? I have a similar one. As I don't want to expose a session to other white-label by any means, I am probably going to write a custom session handler. I am using MySQL for storing the session, so will add an extra column which will contain a session domain or WL identifier 🤔

I encounter same problem recently,  I solved this case with response subscriber and it seems work fine for me:

```
$cookieDomain = $this->getCookieDomain($request->getHost());
$cookies = $response->headers->getCookies();
if (($cookieDomain != $request->getHost()) && !empty($cookies)) {
    foreach ($cookies as $cookie) {
        if ($cookie instanceof Cookie && $cookie->getDomain() != $cookieDomain) {
            $newCookie = Cookie::create(
                $cookie->getName(),
                $cookie->getValue(),
                $cookie->getExpiresTime(),
                $cookie->getPath(),
                $cookieDomain,
                $cookie->isSecure(),
                $cookie->isHttpOnly(),
                false,
                $cookie->getSameSite()
            );

            $response->headers->setCookie($newCookie);
            $response->headers->removeCookie($cookie->getName(), $cookie->getPath(), $cookie->getDomain());
        }
    }
}

```
Please note that the event priority must be less than -1000 (the session listener):
```
    public static function getSubscribedEvents(): array
    {
        return [
            ResponseEvent::class => [
                ['onKernelResponse', -1024]
            ]
        ];
    }
````

With this solution,  no need to create new session handler.

**Comment by wholehogsoftware** [comment]
@boosen I don't remember. The original comment is a decade old and I haven't used Symfony in years. Sorry I can't be of more assistance!

Edit: Oh, I see. You're proposing a solution. Crazy to see this is still a thing a decade later!
