### ISSUE TITLE
[WebProfilerBundle][BUG] Error while encoding non utf-8 post parameters

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#9799]
Web profiler could not correctly display non utf-8 post parameters:
https://www.dropbox.com/s/sxpljovpn5p3uuf/Screenshot%202013-12-17%2015.01.57.png

error happens in twig template WebProfilerBundle/Resources/views/Profiler/bag.html.twig

```
    {% for key in bag.keys|sort %}
            <tr>
                <th>{{ key }}</th>
                {# JSON_UNESCAPED_SLASHES = 64, JSON_UNESCAPED_UNICODE = 256 #}
                <td>{{ bag.get(key)|json_encode(64 b-or 256) }}</td>
            </tr>
        {% endfor %}
```

**Comment by javiereguiluz** [comment]
Is this issue something that we still want to fix ... or should we consider it as "won't fix"?

**Comment by fabpot** [comment]
I would close it as a won't fix.
