### ISSUE TITLE
[Form] empty_norm_data option

### ISSUE THREAD

**Issue by sirian** [symfony/symfony#9886]
At this moment method Form::viewToNorm converts empty string to null when no transformers registered for a type:

```
$transformers = $this->config->getViewTransformers();

if (!$transformers) {
    return '' === $value ? null : $value;
}
```

But this is inconvenient for `text` type. What should I do to treat empty string as empty string and not as null? 
Of course I could create DummyTransformer and add it to necessary fields. But it would be great to provide an option like `empty_norm_data`

```
class DummyTransformer implements DataTransformerInterface
{
    public function transform($value)
    {
        return $value;
    }

    public function reverseTransform($value)
    {
        return $value;
    }
}
```

**Comment by WouterJ** [comment]
I think the transformers exists for exactly this reason, to transform one value (null) to the expected value (empty string)?

Furthmore, as this issue didn't receive any attention in 1.5 years, I think we should either decide to add this option to Symfony or close the issue (as nobody seemed interested in this option, I think closing is the most logical choice).

**Comment by jakzal** [comment]
Let's close as there are few ways of solving this already (an event listener, a data transformer). It seems to be a rare edge case anyway.
