### ISSUE TITLE
[Form] Allow to customize error message according to data transformer failures

### ISSUE THREAD

**Issue by egeloen** [symfony/symfony#9891]
Hey!

I dig into an issue with the form component.

First, the use case:

A customer would like to have a date form field splitted in a single text field for the date  part and two dropdown fields for the hour and minute. For invalid input, it would like to get different error messages according to what was wrong. The different cases are:
- The date is invalid (in case of wrong date input)
- The hour is invalid (in case of wrong hour input)
- The minute is invalid (in case of wrong minute input)

The problem:

The issue is this kind of error is detected by the data transformer which can only result to one error message (invalid_message).

An idea how the form component can provide this kind of error messages?

**Comment by ogizanagi** [comment]
This is possible now that #20978 is merged by specifying the message or message key to use when throwing a `TransformationFailedException`.
