### ISSUE TITLE
[HttpFoundation] Request::getContent() behavior for null value

### ISSUE THREAD

**Issue by LukasRos** [symfony/symfony#9942]
When creating a new Request object with Request::create(), my assumption would be that its content only relies on the input parameters and not any other state.

My issue: If I do not sent _$content_ in _Request::create()_ (default setting = _null_) this is a request without content, so I'd expect _getContent()_ to return _null_. But I observed and confirmed in the code that _getContent()@_returns the value of _php://input_.

Is this desired and I need to use a workaround or should this be fixed as a bug?

**Comment by cordoval** [comment]
just curious why this change was reverted and if this is still actionable or an easy pick.

**Comment by sstok** [comment]
The only change was a test to ensure and empty string was returned (*proof its broken*), but did not contain any actual changes to the Request class, as those changes would break the BC.

**Comment by pimolo** [comment]
Could this issue be closed then?
cc @symfony/deciders

**Comment by pimolo** [comment]
Could this issue be closed then?
cc @weaverryan

**Comment by javiereguiluz** [comment]
Closing as "fixed" by #12652.

**Comment by xabbuh** [comment]
@javiereguiluz but #12652 was reverted in 58fcb8d51531a4250e981c693e8856e2629edfa6

**Comment by xabbuh** [comment]
However, rereading the issue I agree we can close here as we cannot change the class without break BC.
